### ISSUE TITLE
It is recommended to communicate in English as much as possible (建议尽量使用英语沟通所有的需求和评论)

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#10]
为了未来更方便的将Nacos推进到CNCF或者Apache社区孵化，我们恳求大家尽量
用英文发proposal，issue或者comments等，尤其是高质量的那些。（当然，仍然是非强制的）

如果您觉得中文交流更舒服，作为一个建议，您可以尝试在中文的后面加上简单的英语摘要。

In order to promote Nacos to the CNCF or Apache community more conveniently
in the future, we beg you to publish the proposal，issue or comments in English，Especially those of high quality (Of course, it is still non-mandatory).

If you feel that Chinese communication is more comfortable, as a suggestion, you can try to add a simple English summary.

**Comment by lixyou** [comment]
I can't use english....

**Comment by xuechaos** [comment]
@lixyou you could try it slowly. our documentation must include Chinese.  : )

**Comment by windhc** [comment]
@lixyou You can try the translation tool

**Comment by xelat09** [comment]
你更好地适应变化的风和学习中文，我做了同样的事情，我来自非洲（英语/法语已经可用）
Apache and CNCF are not worth it
