### ISSUE TITLE
nacos是否可以设置 配置刷新时间，和设置配置延迟刷新时间，比如是否支持设置在10分钟后配置生效

### ISSUE THREAD

**Issue by wyx-98** [alibaba/nacos#10003]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 985492783** [comment]
Why not publish config after ten minutes?

**Comment by KomachiSion** [comment]
You can do this feature in `listener`.  nacos push the new config to your app and your app can create an async task in your `listener` and the async task started after ten minutes.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
