### ISSUE TITLE
2.x为什么配置了账号的只读权限，仍然可以操作上下线实例 

### ISSUE THREAD

**Issue by guozongkang** [alibaba/nacos#10008]
Server 2.1.2
配置了账号的只读权限。 但是使用该账号登录nacos控制台，仍然可以点击实例列表中的下线按钮。是有BUG？  还是Nacos默认的只读权限是没用的？

**Comment by KomachiSion** [comment]
1. 需要开启鉴权功能。
2. 需要创建角色， 账号，权限，并将三者进行关联。

**Comment by guozongkang** [comment]
> 1. 开启鉴权功能

开启鉴权后，客户端需要新增配置下，获取服务信息时都携带账号密码？

**Comment by KomachiSion** [comment]
那可以自己开发鉴权插件，按照你们的需求接入你们自己的鉴权体系

https://nacos.io/zh-cn/docs/v2/plugin/auth-plugin.html

**Comment by KomachiSion** [comment]
或者通过openAPI 来构建你们独立的控制台。

**Comment by KomachiSion** [comment]
另外 账号是这可以设置某个命名空间的只读权限的，这样应该就不能上下线了。

只要把只读权限给予某个角色， 角色再赋予某个账号

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
