### ISSUE TITLE
`sh startup.sh` can not start service in ubuntu22.10, should be replaced to `bash startup.sh`

### ISSUE THREAD

**Issue by riverify** [alibaba/nacos#10009]
**Describe the bug**
`sh start.sh` can not start service in ubuntu22.10.

**Additional context**
`sh` should be replaced to `bash`

**Comment by KomachiSion** [comment]
`#!/bin/bash` is the file header,  sh should work well.

Is the ubuntu22.10's problem?

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
