### ISSUE TITLE
NacosNamingService注入容器时机

### ISSUE THREAD

**Issue by tianhanjun** [alibaba/nacos#10001]
请问springclould整合nacos时NacosNamingService是如何注入容器的

**Comment by YunWZ** [comment]
Ref *Spring-Cloud-Alibaba*：
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnDiscoveryEnabled
@ConditionalOnNacosDiscoveryEnabled
public class NacosServiceAutoConfiguration {

	@Bean
	public NacosServiceManager nacosServiceManager() {
		return new NacosServiceManager();
	}

}

public class NacosServiceManager {

	private volatile NamingService namingService;

	private volatile NamingMaintainService namingMaintainService;
         // ...
}
```

**Comment by tianhanjun** [comment]
NacosServiceManager 这个组件注入的时候似乎并不会注入所依赖的NamingService，是在其他环节注入的吗？

**Comment by YunWZ** [comment]
> 

https://github.com/alibaba/spring-cloud-alibaba/blob/78e789bc35fa735db23c7a44d05b06491f984689/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosServiceManager.java

**Comment by tianhanjun** [comment]
这里好像是创建对象，创建的对象并没有交给容器吧

**Comment by tianhanjun** [comment]
![image](https://user-images.githubusercontent.com/50659759/220856749-7974468a-044e-4d00-b3e2-2aa52fbcfbc9.png)

**Comment by YunWZ** [comment]
> 容器

是的。SCA中通过`NacosServiceManager`使用`NamingService`, 而不是直接使用。

**Comment by YunWZ** [comment]
> ![image](https://user-images.githubusercontent.com/50659759/220856749-7974468a-044e-4d00-b3e2-2aa52fbcfbc9.png)

。。。
看下源码，用的是懒加载，不会一开始就创建NamingSesrvice

**Comment by tianhanjun** [comment]
可是通过容器对象 我又能获取到NamingService的具体实现NacosNamingService

**Comment by tianhanjun** [comment]
懒加载是体现在具体哪里啊

**Comment by KomachiSion** [comment]
The problem should move to Spring Cloud Alibaba community.
