### ISSUE TITLE
nacos官网监听配置的java sdk，长时间使用返回500 token失效

### ISSUE THREAD

**Issue by dongduang** [alibaba/nacos#10000]
![sdk](https://user-images.githubusercontent.com/44309094/220839971-be0939bd-1385-4bd4-80d4-ab192cc88ab4.png)
使用上述官网java sdk
![token过期](https://user-images.githubusercontent.com/44309094/220840028-86a1e02e-99a7-4541-9ab0-ad1ffcfd2dd1.png)
长时间使用token失效

client使用2.0.3的jar包
server端2.1.2

**Comment by KomachiSion** [comment]
看下日志， 是否有login失败的日志。如果没有，本地debug看下login线程为什么没有更新新的token。

或者看下token的ttl是不是设置过短。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.

**Comment by dongduang** [comment]
client版本升到2.3.0正常，2.0.3版本的token失效原因未知
