### ISSUE TITLE
Utility classes should not have public constructors

### ISSUE THREAD

**Issue by 4yDX3906** [alibaba/nacos#10018]
**Describe the bug**
Utility classes, which are collections of static members, are not meant to be instantiated.   Even abstract utility classes, which can be extended, should not have public constructors.
Java adds an implicit public constructor to every class which does not define at least one explicitly.   Hence, at least one non-public constructor should be defined.

I found the com/alibaba/nacos/common/utils package under classes have a lot of Utility classes without private structure constructor.

**Reference material**
![image](https://user-images.githubusercontent.com/89574863/221809969-f65dcf4a-0d9c-4920-bb6b-27c150b5922d.png)

**Comment by KomachiSion** [comment]
when you add the private constructor, how to do unit test the constructor?

I have no idea for this rule, the public constructor has no effect.
