### ISSUE TITLE
2.2.0线程一直增加

### ISSUE THREAD

**Issue by 836154942** [alibaba/nacos#10016]
2.2.0版本，单机启动，docker部署，线程一直增多，1-2一个新增线程，怎么排查。。

**Comment by 836154942** [comment]
新增到1400个线程貌似不在增加了。。求思路

**Comment by KomachiSion** [comment]
jstack看一下新增的线程是什么。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
