### ISSUE TITLE
2.1.0版本的双写问题 (The dual-write problem occurred in version 2.1.0)

### ISSUE THREAD

**Issue by qisongsl** [alibaba/nacos#10028]
**Describe the bug**
版本为2.1.0 官方文档有介绍为默认关闭双写功能 。但是我这边用接口查询（curl -X GET 'localhost:8848/nacos/v1/ns/upgrade/ops/metrics'）“isDoubleWriteEnabled = true”还是开启了双写

Version 2.1.0 Official documents describe how to disable the dual-write function by default. But here I use query interface (curl -x GET 'localhost: 8848 / nacos/v1 / ns/upgrade/ops/metrics') "isDoubleWriteEnabled = true" or write opens the double

**Expected behavior**
版本从2.0.3更新到了2.1.0

Version 2.0.3 was updated to 2.1.0
![image](https://user-images.githubusercontent.com/126650564/222068793-25b29ebb-48f7-41ff-9c88-7b58b9ccc547.png)
![image](https://user-images.githubusercontent.com/126650564/222068952-136f112b-773f-4621-bae2-96a7e9953bd7.png)
![image](https://user-images.githubusercontent.com/126650564/222069145-191d17f7-6dbe-437a-acae-e90a118b5595.png)

**Comment by KomachiSion** [comment]
新部署的2.1版本时默认关闭双写的， 

但是2.0其他版本升级上去的时候， 因为默认时开启双写的， 如果没有关闭过的话， 这个信息是写在raft中的，会被继承在2.1版本中。

**Comment by qisongsl** [comment]
> 新部署的2.1版本时默认关闭双写的，
> 
> 但是2.0其他版本升级上去的时候， 因为默认时开启双写的， 如果没有关闭过的话， 这个信息是写在raft中的，会被继承在2.1版本中。

会降级么 2.0.3会降级然后会集群注册会不正常 也有情况是应用启动不了 如果想关闭怎么关闭 现在调用关闭接口不允许了

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-upgrading.html

这里面有关闭双写的接口。

**Comment by wzshuang** [comment]
@KomachiSion 请问一下，我是全新部署的2.1.0版本，isDoubleWriteEnabled 为什么也是true呢

**Comment by wzshuang** [comment]
并且我调用关闭双写的接口，也关不了，isDoubleWriteEnabled 仍然为true
```
[root@k8s-master1 nacos-2-sfs-0_logs]# curl -X PUT 'http://192.168.3.62:40848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false'
caused: Upgrade from 1X feature has closed, please set `nacos.core.support.upgrade.from.1x=true` in application.properties;
```

**Comment by bilibilibalala** [comment]
> 并且我调用关闭双写的接口，也关不了，isDoubleWriteEnabled 仍然为true
> 
> ```
> [root@k8s-master1 nacos-2-sfs-0_logs]# curl -X PUT 'http://192.168.3.62:40848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false'
> caused: Upgrade from 1X feature has closed, please set `nacos.core.support.upgrade.from.1x=true` in application.properties;
> ```

你好解决了吗，一样的问题

**Comment by bilibilibalala** [comment]
> > localhost:8848/nacos/v1/ns/upgrade/ops/metrics
> 
> 2.1.0内部逻辑处理是关闭了的, `/metrics` 接口应该是bug？试试'GET'调用'/nacos/v1/ns/operator/switches'

谢谢，这个接口查出来是false。

**Comment by bilibilibalala** [comment]
> > localhost:8848/nacos/v1/ns/upgrade/ops/metrics
> 
> 2.1.0内部逻辑处理是关闭了的, `/metrics` 接口应该是bug？试试'GET'调用'/nacos/v1/ns/operator/switches'

但是用这个接口的话，2.0.3查出来dooubleWriteEnabled也是false，那是不是不能当作生效依据
