### ISSUE TITLE
bate发布ip地址后不生效

### ISSUE THREAD

**Issue by wonkp** [alibaba/nacos#10027]
2.1.0版本bate配置完对应ip地址后，拉取到的配置项是正式配置，而不是bate版本的配置

**Comment by KomachiSion** [comment]
Can some one in community try to reproduce and research the problem?

**Comment by YunWZ** [comment]
I can't reproduce this problem.

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.
