### ISSUE TITLE
The `/META-INF/native-image/io.netty/*` in the `nacos-client-2.2.1-RC.jar` has some problem

### ISSUE THREAD

**Issue by wangliang181230** [alibaba/nacos#10026]
The `/META-INF/native-image/io.netty/*` in the `nacos-client-2.2.1-RC.jar` has some problem.

`nacos-client-2.2.1-RC.jar` 中的 `/META-INF/native-image/io.netty/*` 文件，存在一些问题。

1. 里面配置的类名并没有拼接上 `com.alibaba.nacos.shaded.` 前缀，而已经shade进来的类是复制到了 `com.alibaba.nacos.shaded` 包下了的。
2. 另外，要考虑的一个问题是这些文件是否需要shade进来？根据GraalVM官方推荐，应该将相关配置文件提交到 https://github.com/oracle/graalvm-reachability-metadata 中，而不是jar文件内。

# 见以下几张图片：
![图片](https://user-images.githubusercontent.com/1527893/220240491-81881061-1e3f-4771-95da-c4014f70231d.png)
![图片](https://user-images.githubusercontent.com/1527893/222065666-2f25873b-fae7-441a-8eaf-fd166a76596a.png)
![图片](https://user-images.githubusercontent.com/1527893/222066084-302dd3ac-025a-4119-a833-0e4d7946a5a6.png)

**Comment by wangliang181230** [comment]
@Tonibrown20 @KomachiSion PTAL

**Comment by pupupupu1** [comment]
T_T目前基于cloud Aliababa Nacos的项目集成netty相关依赖的时候，使用native-image打包会出现netty aot失败问题

**Comment by wangliang181230** [comment]
> T_T目前基于cloud Aliababa Nacos的项目集成netty相关依赖的时候，使用native-image打包会出现netty aot失败问题

报什么错？把堆栈发出来一下，可能我可以提供解决方案。

**Comment by wangliang181230** [comment]
> 我在spring-cloud-alibaba的issues发起了，目前还没解决呢，大哥帮忙看看 [alibaba/spring-cloud-alibaba#3158](https://github.com/alibaba/spring-cloud-alibaba/issues/3158)

好的，我先看看。

**Comment by KomachiSion** [comment]
shaded 的时候把 netty和grpc的native-image打进来了， 其实应该说明netty和grpc其实是带有native-image的吧， 那nacosclient是否应该遵循GraalVM的官方推荐去做？ 或者是模仿netty和grpc， 把nacos自己的native-image和sharded的native-image都打进来，并且修改为正确的路径？

**Comment by wangliang181230** [comment]
> shaded 的时候把 netty和grpc的native-image打进来了， 其实应该说明netty和grpc其实是带有native-image的吧， 那nacosclient是否应该遵循GraalVM的官方推荐去做？ 或者是模仿netty和grpc， 把nacos自己的native-image和sharded的native-image都打进来，并且修改为正确的路径？

我比较偏向官方推荐的做法，因为一旦有问题，可随时提交PR去改。

**Comment by wangliang181230** [comment]
> 或者是模仿netty和grpc， 把nacos自己的native-image和sharded的native-image都打进来，并且修改为正确的路径？

是的，要shade进来，必须把对应的类路径给改为正确的路径，否则这些错误路径的配置就没有存在的意义了。

**Comment by wangliang181230** [comment]
> > > T_T目前基于cloud Aliababa Nacos的项目集成netty相关依赖的时候，使用native-image打包会出现netty aot失败问题
> > 
> > 
> > 报什么错？把完整的日志发出来一下，可能我可以提供临时解决方案。
> 
> 我在spring-cloud-alibaba的issues发起了，目前还没解决呢，大哥帮忙看看 [alibaba/spring-cloud-alibaba#3158](https://github.com/alibaba/spring-cloud-alibaba/issues/3158)

@pupupupu1 你先用tracing agent，把动态特性的调用自动跟踪下来，自动生成配置文件。然后再打包native-image。
参考springboot的说明：https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.using-the-tracing-agent

**Comment by pupupupu1** [comment]
> 
> 参考springboot的说明：https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.advanced.using-the-tracing-agent

嗯嗯native:compile方案我可以打包啦，不过我此前一直尝试的是文档中的BuildPacks：
https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.developing-your-first-application.buildpacks
之前提供的issues中的异常日志也都是来自mvn -Pnative spring-boot:build:image而提示的，看起来就没有读取到/META-INF/native-image中的配置一样

**Comment by pupupupu1** [comment]
不幸的是我native:compile之后，还是不行issues的异常日志异常，放弃放弃 T_T

**Comment by pupupupu1** [comment]
@wangliang181230 
老哥我还是使用spring-data-redis然后exclude了lettuce，导入了jedis，这样可以避免引入netty而和nacos进行原生编译产生冲突，最终运行起来啦，感谢！
