### ISSUE TITLE
启用故障转移时产生的问题

### ISSUE THREAD

**Issue by ThreeJ939** [alibaba/nacos#10038]
故障转移本地磁盘文件如下（订阅了其他服务，服务端返回的clusters字段为空字符，所以生成的文件名未拼接clusters字段）

![image](https://user-images.githubusercontent.com/48232229/222657286-af8f9b84-4ebe-4c22-b9f3-9221af308e9b.png)

当启用故障转移时，从磁盘读取`ServiceInfo`进缓存时会执行到下面的代码

![image](https://user-images.githubusercontent.com/48232229/222659269-ad4e3f6e-4f0f-4343-8e9d-a1dfcf0cfe5a.png)
![image](https://user-images.githubusercontent.com/48232229/222660398-79a40714-f099-4d1a-9f04-2a949db70a7a.png)

当读取`DEFAULT_GROUP%40%40mall-auth`这个文件名时无法通过上面的逻辑会抛异常

`nacos-server`版本`2.2.1`  ,`nacos-client`版本`1.4.2`

**Comment by YunWZ** [comment]
@i will resolve it@

**Comment by KomachiSion** [comment]
Can you see the client 2.x has this problem?
