### ISSUE TITLE
core-auth.log 疯狂打印 DEBUG auth start, request: POST /nacos/v1/cs/configs/listener

### ISSUE THREAD

**Issue by luankun88** [alibaba/nacos#10035]
单机部署nacos2.1.1版本，几个小时就能够打印日志高达 500M以上
![image](https://user-images.githubusercontent.com/29765300/222354035-af6b2702-043b-4421-b112-b77b6c995406.png)

**Comment by YunWZ** [comment]
这是DEBUG级别的日志，你的日志级别设置成DEBUG当然就会打印了

**Comment by luankun88** [comment]
我并没有设置啊，是nacos默认的。目前排查到可能是nacos的源码的日志配置能解决，还没验证。

**Comment by luankun88** [comment]
![image](https://user-images.githubusercontent.com/29765300/222417070-451b8b1d-064a-4027-b0a1-e24f38463694.png)

**Comment by luankun88** [comment]
在nacos-server服务端的conf/nacos-mysql.sql，有日志级别的配置，待明天验证结果，告诉大家

**Comment by luankun88** [comment]
在nacos-server服务端的conf/nacos-mysql.sql，有日志级别的配置，待明天验证结果，告诉大家

**Comment by luankun88** [comment]
在nacos-server服务端的conf/nacos-mysql.sql，有日志级别的配置，待明天验证结果，告诉大家

但nacos默认很多日志级别都是DEBUG，不友好，希望后续能优化一下默认日志级别

**Comment by KomachiSion** [comment]
core-auth应该也是设置了日志轮转， 大小和时间都会轮转， 如果磁盘比较小， 可以修改轮转的大小和时间，或者日志级别。

鉴权的日志和其他不同， 很多时候对请求排查的信息要求较高， 如果出现问题再去开启debug日志查看信息，可能会丢失重要信息，所以日志级别比较低，目前默认是DEBUG。 这里可以社区讨论看看， 是改为INFO还是保持现状。

**Comment by KomachiSion** [comment]
There is no discuss for a long time, I think there is no need to change the default setting from community response.
