### ISSUE TITLE
Nacos configuration list fuzzy query is invalid

### ISSUE THREAD

**Issue by 77321660** [alibaba/nacos#1003]
nacos版本：0.9.0
1、配置管理--配置列表
通过data id、group 模糊查询无效

2、服务管理---服务列表
通过服务名称查询，输入test，然后回车，期望优化为可直接查询。不用点击查询按钮

**Comment by nkorange** [comment]
@77321660 配置的模糊查询需要添加通配符*

**Comment by nkorange** [comment]
服务列表回车查询这个我们后续会支持。

**Comment by loadchange** [comment]
@77321660 目前版本支持回车

**Comment by bigbenfather** [comment]
配置的模糊查询需要添加通配符*，这个最好有个提示，我也以为是个bug
