### ISSUE TITLE
compare history version

### ISSUE THREAD

**Issue by ArdenCHan** [alibaba/nacos#10039]
compare history version should refresh first

**Comment by ArdenCHan** [comment]
![image](https://user-images.githubusercontent.com/36724106/222676260-303679e2-a2e4-4d35-874e-51457be15a2e.png)

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/223001348-f785db28-1893-44cf-a9e0-1eaeac0ecbe2.png)

I can do compare histroy version and no problem in console.nacos.io

**Comment by ArdenCHan** [comment]
首次进入历史版本，直接点击历史对比，报了500
重新刷新页面之后再对比就有了

**Comment by KomachiSion** [comment]
我也没复现，我首次进去就可以了。。

**Comment by KomachiSion** [comment]
如果能复现麻烦把具体报错发一下。

**Comment by ArdenCHan** [comment]
![image](https://user-images.githubusercontent.com/36724106/223674387-cfaff81d-e38f-4603-81b0-bc04829c63c9.png)

**Comment by ArdenCHan** [comment]
![image](https://user-images.githubusercontent.com/36724106/223674569-1a13bd26-0198-4104-8f37-74c68da70802.png)
这里的dataid 和 group为空

**Comment by KomachiSion** [comment]
你试着清理一下缓存，之后重试呢

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.
