### ISSUE TITLE
调整startup.sh关于gc log配置

### ISSUE THREAD

**Issue by LeePui** [alibaba/nacos#10049]
**Is your feature request related to a problem? Please describe.**
目前的startup.sh中对于gc log的配置分了jdk9之前和之后，jdk9之前配置为：`-XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M`，也就是10个gc文件，每个100m。jdk之后的配置为：`filecount=10,filesize=102400`，实际上这里每个gc文件变为了100k，可以通过jcmd看到：
![image](https://user-images.githubusercontent.com/14257862/223053793-96d98e60-fa58-467c-a1db-32214f249169.png)
同时也可以看到gc文件大小为100k一个：
![image](https://user-images.githubusercontent.com/14257862/223053904-727696b5-d863-4725-a781-291a208505f5.png)

100K太小了，不能很好的诊断gc问题，建议设置为和JDK9之前的一样，每个为100m.

我可以提交一个pr将它修改为100m。

**Comment by KomachiSion** [comment]
可以自行修改
