### ISSUE TITLE
Open API 无法注销实例

### ISSUE THREAD

**Issue by Tan-Pchan** [alibaba/nacos#10040]
版本： 2.2.0
![image](https://user-images.githubusercontent.com/68987741/222687619-8685e4c3-e823-497b-bd14-d6a5ccdef0c6.png)
![image](https://user-images.githubusercontent.com/68987741/222687787-73126a30-a213-4577-850d-483686b6647c.png)

**Comment by YunWZ** [comment]
这个实例信息是否有后台进程（项目）在使用，当后台进程发送心跳时会自动注册。
如果不想让A该实例信息被消费方感知，可以在控制台手动“下线”。

**Comment by Tan-Pchan** [comment]
该实例为持久化实例，应由服务端发起心跳检测。另也有测试过，手动在控制台进行下线动作，通过API依然无法注销实例。

**Comment by KomachiSion** [comment]
下线只是打一个标记，让订阅方收不到这个地址， 服务端里还有这个实例。

删除不掉得看下服务端有没有报错，或者那里设置是不是有错误。

**Comment by KomachiSion** [comment]
下线只是打一个标记，让订阅方收不到这个地址， 服务端里还有这个实例。

删除不掉得看下服务端有没有报错，或者那里设置是不是有错误。

**Comment by r-rhythm** [comment]
我也遇到同样的问题,调用官方给的open_api`DELETE 'http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.example&group=com.alibaba.nacos'`仍然无法将实例移除(持久化的实例)

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/223906273-a6628b66-dc89-4242-9f19-62153d72681c.png)
![image](https://user-images.githubusercontent.com/37170243/223906338-32250fc0-6373-470f-b0c0-c3ccebf18b9b.png)
![image](https://user-images.githubusercontent.com/37170243/223906423-4541df52-ee4e-41c6-89b9-eaa144597fce.png)
![image](https://user-images.githubusercontent.com/37170243/223906454-aaf95594-23e7-4da7-af6f-495cda94e62f.png)

nacos console demo (nacos.console.io) 版本为2.2.0.1 经过测试无法复现。 功能没问题，应该和部署的环境有关，需要看下本地环境的日志等信息。

**Comment by KomachiSion** [comment]
`No more response from author, and community can't reproduce problem.

**Comment by qiulin** [comment]
同样遇到该问题，日志里面显示：

```
remove instance from non-exist client
```
