### ISSUE TITLE
完全不理解这nacos的配置为什么一会在vm参数上配置，一会在spring配置文件里配置

### ISSUE THREAD

**Issue by Liang-Dongxing** [alibaba/nacos#10057]
![image](https://user-images.githubusercontent.com/19583575/223662590-2c937110-bbeb-412d-add2-7a849d8ac351.png)

**Comment by YunWZ** [comment]
¿¿¿
这不是你自己的IDE的配置？

**Comment by githubcheng2978** [comment]
其实服务端这种问题更多，也没有统一规范。 好像服务端想要脱离springboot，但模块间又严重依赖spring容器，不知道当初这个地方为什么要这样子设计。 正常来说spring对配置已经管理得很好了。

**Comment by KomachiSion** [comment]
因为有些通用模块（比如common和api），server和client都有用， 但是client不依赖spring， 没办法使用spring的配置管理机制。

这个工作已经在进行了，client和server的大部分参数应该已经收敛。

一些未覆盖到的和更基础的模块中的参数还需要梳理和方案。

**Comment by KomachiSion** [comment]
因为有些通用模块（比如common和api），server和client都有用， 但是client不依赖spring， 没办法使用spring的配置管理机制。

这个工作已经在进行了，client和server的大部分参数应该已经收敛。

一些未覆盖到的和更基础的模块中的参数还需要梳理和方案。
