### ISSUE TITLE
How do I find source code of nacos-client-1.2.0?

### ISSUE THREAD

**Issue by kvhuang** [alibaba/nacos#10059]
Is it possible to get the source code for the 'nacos-client-1.2.0' artifact? I have searched extensively but haven't been able to locate it. Specifically, I'm trying to understand the functionality of two Java classes: 'com.alibaba.nacos.client.naming.NacosNamingService' and 'com.alibaba.nacos.client.naming.net.NamingProxy'. Although I cloned the Nacos repository, I couldn't find the implementation of these classes in the source code. The 'nacos-client' module is listed as a dependency in the POM file, which suggests that it may be coming from an external source. I even checked my local Maven repository, and while the JAR file contains the classes, there is no README file or any other documentation that might provide clues as to where the source code is located. I'm wondering if it's possible that the source code is proprietary?

**Comment by KomachiSion** [comment]
use tag `1.2.0` 

https://github.com/alibaba/nacos/tree/1.2.0
