### ISSUE TITLE
nacos-client can not communicate with nacos server

### ISSUE THREAD

**Issue by dinobot71** [alibaba/nacos#10066]
**Describe the bug**

When connecting to Nacos Server with nacos-client (1.2.0), 

```
https://xxxxxxxxxxxxxxxx/nacos/v1/ns/instance?app=xxxxxx&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&ip=172.17.0.2&weight=1.0&ephemeral=true&serviceName=xxxxx-xxxxxxx&encoding=UTF-8&groupName=xxxxxxxx&namespaceId=xxxxxxxxxx-xxxx-xxxx-xxxxxxxxxxx&port=11001&enable=true&healthy=true&clusterName=DEFAULT
```

Nacos server replies with status 411 - Content Length required.  This is the correct response for Nacos server to give, since the Content-Length header is in fact missing.   We checked with WireShark and found that the nacos-client class NamingProxy appears to POST the request incorrectly, POST body is empty and it is not sending a header of "Content-Length: 0", and this is why Nacos Server is replying with a 411 status.  This in turn blocks our application from communicating with Nacos Server.  

*So, we can not use Nacos.*

**Expected behavior**

Per HTML protocol for POST:   https://httpwg.org/specs/rfc9110.html#field.content-length  we expect that the nacos-client classes (in particular NamingProxy) will send requests to nacos server and always include a Content-Length header even when the body size is 0.  This in turn would allow Nacos server to reply normally, and not break our communication with Nacos server.  Content-Length header should always be sent, even when the body size is 0. 

**Actual behavior**

The exception we are getting is on NamingProxy in nacos-client:1.2.0:

```
at [com.alibaba.nacos.client.naming.net](http://com.alibaba.nacos.client.naming.net/).NamingProxy.reqAPI(NamingProxy.java:490)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:395)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:391)
        at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:210)
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
        at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:64)
```

The exception is an HTTP status of 411 after sending the request /nacos/v1/ns/instance...  The  status that comes back from Nacos server is 411 and the status phase is "Length Required".  

WireShark shows that nacos-client is sending:

```
Hypertext Transfer Protocol
     [truncated]POST /nacos/v1/ns/instance?app=xxxxxxxx&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&ip=172.17.0.2&weight=1.0&ephemeral=true&serviceName=xxxxxxxxxxxx&encoding=UTF-8&groupName=xxxxxxx&namespaceId=9
        [ [truncated]Expert Info (Chat/Sequence): POST /nacos/v1/ns/instance?app=xxxxxxxxx&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&ip=172.17.0.2&weight=1.0&ephemeral=true&serviceName=xxxxxxxxxxxx&encoding=UTF-8&gr]
            [POST /nacos/v1/ns/instance?app=xxxxxxxxxxx&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&ip=172.17.0.2&weight=1.0&ephemeral=true&serviceName=xxxxxxxxxxxxxxxxxxxxx&encoding=UTF-8&groupName=xxxxxx&namespaceId=9933166c-dfa9-]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: POST
        Request URI [truncated]: /nacos/v1/ns/instance?app=xxxxxxxxx&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&ip=172.17.0.2&weight=1.0&ephemeral=true&serviceName=xxxxxxxxxxxxxxxxx&encoding=UTF-8&groupName=xxxxxxxxxxx&names
            Request URI Path: /nacos/v1/ns/instance
            Request URI Query [truncated]: app=xxxxxxxxxxxx&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&ip=172.17.0.2&weight=1.0&ephemeral=true&serviceName=xxxxxxxxxxxxxxxxx&encoding=UTF-8&groupName=xxxxxxxxxxx&namespaceId=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
                Request URI Query Parameter: app=xxxxxxxxxx
                Request URI Query Parameter: metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D
                Request URI Query Parameter: ip=172.17.0.2
                Request URI Query Parameter: weight=1.0
                Request URI Query Parameter: ephemeral=true
                Request URI Query Parameter: serviceName=xxxxxxxxxxxxxxxxxxxxxxx
                Request URI Query Parameter: encoding=UTF-8
                Request URI Query Parameter: groupName=xxxxxxxxxx
                Request URI Query Parameter: namespaceId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                Request URI Query Parameter: port=11001
                Request URI Query Parameter: enable=true
                Request URI Query Parameter: healthy=true
                Request URI Query Parameter: clusterName=DEFAULT
        Request Version: HTTP/1.1
    Client-Version: 1.2.0\r\n
    User-Agent: Nacos-Java-Client:v1.2.0\r\n
    Accept-Encoding: gzip,deflate,sdch\r\n
    RequestId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n
    Request-Module: Naming\r\n
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8\r\n
    Accept-Charset: UTF-8\r\n
    Host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx\r\n
    Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n
    Connection: keep-alive\r\n
    \r\n
```
As you can see, the request is clearly missing the Content-Length header (when body size is 0). Perhaps because there is no body, the logic inside NamingProxy does not add the header?  However, this is not compliant with HTTP protocol per:

https://httpwg.org/specs/rfc9110.html#field.content-length

The nacos-client code should ALWAYS include a Content-Length header, even when the body size is 0.  

**How to Reproduce**

Use nacos-client:1.2.0 to register with Nacos service.  
nacos-client will send  the  /nacos/v1/ns/instance POST, but not include a Content-Length header
nacos-server will respond with a 411 client error
nacos-client will generate an exception 
Application will fail to register with Nacos server.

**Desktop (please complete the following information):**

- OS: Windows
- nacos-client: v1.2.0
- nacos: v2.0.2
- JVM: OpenJDK 1.8.0_362
- Maven: 3.9.0
- Application is a spring boot application
 - SDK: alibaba nacos and nacos-client

**Additional context**

I looked around on the internet trying to find the source code for nacos-client, but I can not find any.  Its not clear what the full fix is...since I can't see the source code, I can't suggest anything further. :(  Basically it looks like the logic for sending PUT or POST requests is dropping the Content-Length header when it should not be.  Fixing that, should resolve the issue.

Maybe we are using the wrong version of nacos-client?  Maybe this was fixed already?  I am new to Nacos so I am not familiar with what the latest code is.  If we are just using a really old version that we shouldn't be using...please let me know.

[pom_xml.txt](https://github.com/alibaba/nacos/files/10929243/pom_xml.txt)

**Comment by Daydreamer-ia** [comment]
to be honest, v1.2.0 is too old actually. May be you can try v1.4.x or v2.x directly. It is recommend to use v2.x.

**Comment by dinobot71** [comment]
Thanks, we'll give that a try.  I'm guessing v2.x is available in the same Maven repo; is there any chance for us to get the source code for the client artifact?

**Comment by KomachiSion** [comment]
I test the client 1.2.0 directly connect with server 2.2.0.1. It can work well. So I think it the environment problem. Is there some vip or vpn in between your clients and server?

**Comment by dinobot71** [comment]
There is internet and cloud infrastructure in the middle; but it doesn't explain why the client is not sending the content-length header; Wireshark is running on my own desktop ... before anything even reaches the internet, and already its clear the client isn't sending the content-length header.    But...it may be the case that the version of nacos on the other end...is an earlier version...and that earlier version, may not be so strict; it might the case that earlier versions of nacos (server) don't mind if there is no content-length header.  It might also be possible that the cloud infrastructure is the part rejecting the request because of the missing header; I haven't yet confirmed that part as happening or not.  

At the same time; I am also testing now with upgrading our client to use v2.x of client with v2.x of the server...I think that may actually resolve the problem anyways, so there won't be a need to investigate this older version.  I'm still working on our upgrade, I'm hopeful that I have an answer there within a day or so.

If the upgrade also fails in the same way, I will start looking closer at what is "in the middle" to see if something else is rejecting the request. I'm also running the client and server locally in docker (without SSL) so I can easily check the upgraded system with wireshark and know for sure what headers are there...if the header is missing but the upgraded version works...that seems pretty clear that the problem is the cloud infrastructure in the middle.  If it is in the middle only, then we would certainly like to add a feature request that nacos client sends the missing header...so it is more compatible with a broader selection of cloud infrastructure, and not just AWS.

I'll get back to you in a day or so with confirmation either way.

**Comment by dinobot71** [comment]
Hi, we've been testing more and using v2.x of  nacos client with v2.x of nacos does not seem to have the same issues; it appears that in v2.x, gRPC is used as the main wait to communicate between the client and nacos (on port 9848).  So for v2.x on both client and server...there are no issues around the HTTP content-length header...because its not using HTTP :)

We have been trying to get nacos and nacos clients working in Google; and we've found that it can only really work if nacos is  deployed in a VM or cluster with a public IP address (not in CloudRun and not behind a load balancer or backend).  This has been the only way we found to avoid the "411" error :( 

I think what is happening is that Google load balancers and/or backends are very strict with HTTP compliance.  They absolutely require the content-length header. At the same time, if you put nacos behind a load balancer or backend, it usually only maps a single port, i.e. 8848...so in that mode, the clients can't use gRPC, and they use http on 8848...its only in that case...when the problem occurs, because nacos is forced to use http protocol, and Google infrastructure requires the content-length header, and nacos-client code for http protocol doesn't always send the content-length header.

I think it should be ok though to use gRPC; some of our clients will be in CloudRun; but I think we can use a VPC Connector to allow the CloudRun instance to talk to the VM / cluster where we have nacos deployed.   

However, there are larger problems I think; with some of the clients being in CloudRun, I'm not sure the nacos method of using the IP address to identify clients will always work.  CloudRun is doing its own managed auto-scaling, and the IP addresses for the client endpoints are dynamic/ephemeral.  

We do already have an example running where we have a couple of clients in CloudRun and nacos is in a private VM...but with a public IP address.  It seems like even the Google VPC Connector is somehow requiring the content-length header :(    We will be doing some more testing there.

The end result is that we can't use nacos in combination with a Google load balancer, backend or other Google infrastructure that requires strict compliance with HTTP protocol...because in some cases either nacos or nacos-client (even version 2.x) does not send the content-length header, and Google rejects the request with a 411 error.  

Note that while using a public IP address without a loadbalancer works...its not secure :(  We are trying to have a private cluster for our services that are not running in CloudRun.

We'll do some more testing, but I think this issue can be closed, its only a problem when trying to specifically use nacos/nacos-client with Google infrastructure.  I don't know if your project intends to support Google, maybe not, and if not...then this is not a problem :)

**Comment by dinobot71** [comment]
I will close the issue as I'm not sure your project intends to support Google.

**Comment by dinobot71** [comment]
I do see this:

https://cloud.google.com/load-balancing/docs/https/

Which does talk a little bit about load balancing both normal and gRPC traffic at the same time.  It might be that we just need to create a Google load balancer that can handle gRPC as well.  We will give it a shot :)

**Comment by dinobot71** [comment]
hmmm,  in case it helps us fit nacos into Google...is there a way to configure the clients to always use http and not attempt to use gRPC?  Not because we don't want to, but because http might be easier to get things setup and running in Google.
