### ISSUE TITLE
dataId有超过2个冒号时，不能正常获取配置？

### ISSUE THREAD

**Issue by sniper-xx** [alibaba/nacos#10067]
**Describe the bug**
nacos 版本:  v2.2.0
nacos client 版本: v2.2.0-rc

dubbo生成的配置项带有两个':'， 如: org.xxx.user.service.UserService:1.0::provider:test-service-provider， 我通过nacos native api直接读取配置数据时，content总是为空;

配置中心 dataId: org.xxx.user.service.UserService:1.0::provider:test-service-provider

客户端代码:
 ``` java
       var configService = NacosFactory.createConfigService(props);
        String content = configService.getConfig(dataId", "dubbo", 5000);
        System.out.println(content);
```

问题：
  content总是为 null

备注： 

自己创建的配置项，如果只有一个 ':' 可以访问， 超过2个时，也同样不能访问。 可以断定，客户端配置没有问题，问题估计出在dataId的规则上

请问这是bug，还是其他原因所导致？

**Comment by Daydreamer-ia** [comment]
不是 `data` 的规则限制，只是这个 `:` 符号确实刁钻了点。`nacos` 的配置即使在使用了外部数据源，会把数据加载到文件系统的，然后查询的时候，是从文件系统加载出来的(除非你用内嵌的 `derby` 否则都是从文件系统)。具体是在 `{$nacos-home}` 下的 `data` 目录，最终会以 `dataId` 为文件名存储，而大部分操作系统，比如 `windows` 对文件命名是不允许出现这个符号的，所以会导致查询不出来。

**Comment by Daydreamer-ia** [comment]
@KomachiSion 这块在查询的时候，能否在文件系统配置加载空结果的情况下，从数据库里查询一次来给查询做一次兜底呢？

**Comment by sniper-xx** [comment]
> @KomachiSion 这块在查询的时候，能否在文件系统配置加载空结果的情况下，从数据库里查询一次来给查询做一次兜底呢？

昨天也跟踪源码到这里了。 希望能增加数据库查询兜底机制，或者调整文件存储命名规则，不然windows下适配dubbo就存在问题。

**Comment by Daydreamer-ia** [comment]
@i will resolve it
