### ISSUE TITLE
Will healthcheck lead to Instance#metadata change loss?

### ISSUE THREAD

**Issue by Lin-1997** [alibaba/nacos#10064]
while construct InstancePublishInfo in com.alibaba.nacos.naming.core.v2.service.ClientOperationService#getPublishInfo, there are:
`
if (null != instance.getMetadata() && !instance.getMetadata().isEmpty()) {
            extendDatum.putAll(instance.getMetadata());
}
`
however, instancePublishInfo#extendDatum are never update even Instance#metadata are updated in InstanceMetadataProcessor.

But in com.alibaba.nacos.naming.healthcheck.v2.PersistentHealthStatusSynchronizer, if an instance's health staus changed, it will call com.alibaba.nacos.naming.utils.InstanceUtil#parseToApiInstance (which copy InstancePublishInfo#extendDatum into a new Instance), and submit a new Raft request to update this Instance.
So, if the instance#metadata was changed, and this change was not update that one in InstancePublishInfo. will this change on instance#metadata loss?

**Comment by KomachiSion** [comment]
No problem, when the changes request from raft apply, the metadata is not empty, so the new change will be used into instance.

**Comment by PRANRAVEE** [comment]
ในวันที่ จ. 13 มี.ค. 2023 09:57 杨翊 SionYang ***@***.***>
เขียนว่า:

**Comment by Lin-1997** [comment]
> No problem, when the changes request from raft apply, the metadata is not empty, so the new change will be used into instance.

Does this mean there is no need to put instance#metadata into instancePublishInfo#entendDatum?

**Comment by KomachiSion** [comment]
No, some framework or users will register instance with metadata, and the metadata should saved and synced.

**Comment by Lin-1997** [comment]
> No, some framework or users will register instance with metadata, and the metadata should saved and synced.

As mentinoed above, thoes useful metadata are saved in InstanceMetadata, and synced by InstanceMetadataProcessor, which haven't update InstancePublishInfo.
when users query Instance, they pares instance from InstancePublishInfo by com.alibaba.nacos.naming.core.v2.index.ServiceStorage#parseInstance, whihc is:

`Instance result = InstanceUtil.parseToApiInstance(service, instanceInfo);
Optional<InstanceMetadata> metadata = metadataManager.getInstanceMetadata(service, instanceInfo.getMetadataId());
metadata.ifPresent(instanceMetadata -> InstanceUtil.updateInstanceMetadata(result, instanceMetadata));`

so, the metadata saved in InstancePublishInfo is actually useless

**Comment by KomachiSion** [comment]
I think you has mistake, If there is no metadata from `metadataManager` which add by `update API` the orginal metadata from register will be used.

**Comment by KomachiSion** [comment]
In other words, the metadata from `update API` has higher priority.

**Comment by Lin-1997** [comment]
fine, thanks
