### ISSUE TITLE
How to use nacos LDAP plugin with dingding login

### ISSUE THREAD

**Issue by zonghay** [alibaba/nacos#10076]
How to use nacos LDAP plugin with dingding login
请问，Nacos LDAP plugin如何兼容钉钉扫码登陆
需要做哪些兼容

**Comment by zonghay** [comment]
i want learn more information about these properties:
nacos.core.auth.ldap.url=ldap://localhost:389
nacos.core.auth.ldap.basedc=dc=example,dc=org
nacos.core.auth.ldap.userDn=cn=admin,${nacos.core.auth.ldap.basedc}
nacos.core.auth.ldap.password=admin
nacos.core.auth.ldap.userdn=cn={0},dc=example,dc=org
nacos.core.auth.ldap.filter.prefix=uid
nacos.core.auth.ldap.case.sensitive=true

**Comment by wuchubuzai2018** [comment]
感觉LDAP插件可能不行吧，估计得开发个SSO插件或登录回调的插件接口，一般这种扫码的都需要提供一个回调地址，扫完码后，会将当前用户的登录信息，通过某种加密的标识传递给回调地址，然后去解析出当前用户名，然后模拟注册和会话

**Comment by wuchubuzai2018** [comment]
根据个人的SSO开发经验，个人觉得开发思路是这样的：
1、在Nacos源码中，定义一个钉钉插件工程或SSO插件工程，然后定义一个控制器Controller，负责定义钉钉的回调接口，接受钉钉的code参数，然后，在定义一个钉钉标准SPI请求解析User的接口或者默认就直接解析
2、解析出来以后，一般有两种解决思路：
方式一：用户不存在，注册用户，分配默认角色和权限
方式二：然后将解析出来的用户与nacos用户做匹配，从而调用Nacos的登录用户逻辑完成登录

**Comment by zonghay** [comment]
> 根据个人的SSO开发经验，个人觉得开发思路是这样的： 1、在Nacos源码中，定义一个钉钉插件工程或SSO插件工程，然后定义一个控制器Controller，负责定义钉钉的回调接口，接受钉钉的code参数，然后，在定义一个钉钉标准SPI请求解析User的接口或者默认就直接解析 2、解析出来以后，一般有两种解决思路： 方式一：用户不存在，注册用户，分配默认角色和权限 方式二：然后将解析出来的用户与nacos用户做匹配，从而调用Nacos的登录用户逻辑完成登录

方法二的与nacos用户做匹配没太理解，麻烦解释一下

**Comment by KomachiSion** [comment]
From the discussion, I think it's a custom plugin request. Can support implemented after 2.1.0 by users with auth plugin.
