### ISSUE TITLE
k8s 部署NACOS ，设置了env : NACOS_AUTH_ENABLE=true  ，但是权限验证还是未生效

### ISSUE THREAD

**Issue by songbogit** [alibaba/nacos#10074]
`      - env:
        - name: NACOS_REPLICAS
          value: '3'
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: mysql.host
        - name: MYSQL_SERVICE_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: mysql.db.name
        - name: MYSQL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: mysql.port
        - name: MYSQL_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: mysql.user
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: mysql.password
        - name: NACOS_AUTH_ENABLE 
          value: "true" 
        - name: MODE
          value: cluster
        - name: NACOS_SERVER_PORT
          value: '8848'
        - name: PREFER_HOST_MODE
          value: ip
        - name: MYSQL_SERVICE_DB_PARAM
          value: >-
            characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
        - name: NACOS_SERVERS
          value: >-
            10.55.41.11:8848
            10.55.41.12:8848
            10.55.41.13:8848`

进入到容器中 查看nacos进程：
root         1     0  5 16:44 ?        00:01:47 /usr/lib/jvm/java-1.8.0-openjdk/bin/java -server -Xms1g -Xmx1g -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.core.auth.enabled=true -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/health:/home/nacos/plugins/cmdb:/home/nacos/plugins/mysql -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar --spring.config.additional-location=file:/home/nacos/conf/ --spring.config.name=application --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

部署完成之后，通过curl测试登录依然可以获取配置，按理来说 启动的参数“-Dnacos.core.auth.enabled=true”优先级大于配置中，这样应该是可以覆盖生效的，为什么是无效的能帮忙解答一下吗，

**Comment by songbogit** [comment]
![图片](https://user-images.githubusercontent.com/12811306/224280890-2155ac06-b21a-4b34-a2b3-89dec936d007.png)
没有账号密码依然可以获取配置

**Comment by KomachiSion** [comment]
不生效有两种可能：
1. -D参数位置不对， 部分jdk版本可能存在bug， -D参数写在两段-XX或者-X之间，不会被读取（jdk认为已经读取过了，会忽略掉），可以arthas之类的调用一下System.getProperties()看一下。
2. 配置文件中已经有这个参数了， 按照spring boot的设计，配置文件优先-然后是环境变了-然后是jvm（我印象中是这样），Spring cloud才变成bootstrap-配置中心-jvm-环境变量。

关于为什么环境变量优先：需要支持动态修改配置文件变更的情况，如果jvm优先，就无法实现动态加载，只能重启了。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
