### ISSUE TITLE
notify RpcClient is obtained preferentially

### ISSUE THREAD

**Issue by vnjohn** [alibaba/nacos#10079]
com.alibaba.nacos.client.config.impl.ClientWorker.ConfigRpcTransportClient#queryConfig

In this method, RpcClient will be created first. Is it OK to execute the logic code in if? If it is empty, then call the getOneRunningClient method to create a new RpcClient

RpcClient rpcClient = getOneRunningClient();
if (notify) {
    CacheData cacheData = cacheMap.get().get(GroupKey.getKeyTenant(dataId, group, tenant));
    if (cacheData != null) {
        rpcClient = ensureRpcClient(String.valueOf(cacheData.getTaskId()));
    }
}

**Comment by KomachiSion** [comment]
I don't know what's your question.

**Comment by vnjohn** [comment]
有个疑问，在 ConfigRpcTransportClient#queryConfig 方法中，将首先创建 RpcClient。是否可以理解为可以先执行 if 中逻辑代码?如果它是空的，那么再调用 getOneRunningClient 方法来创建一个新的 RpcClient？
