### ISSUE TITLE
nacos_exception_total mestrics is not find in the prometheus monitor

### ISSUE THREAD

**Issue by qinghuozhang** [alibaba/nacos#10071]
服务端和nacos client 都使用的nacos2.1.1，在promethes中除了nacos_exception_total{name='db'}这个指标可以监控到，其他的nacos_exception_total指标都无法监控到。另外如果想通过nacos监控微服务的上下线，该怎么做，谢谢

**Comment by KomachiSion** [comment]
nacos_exception_total太模糊，意义不大，已经移除漫长时间了。

> 想通过nacos监控微服务的上下线

https://nacos.io/zh-cn/docs/v2/plugin/trace-plugin.html

**Comment by qinghuozhang** [comment]
> 

呃，感谢，看到了。这种方式应该没办法集成prometheus来告警吧。。

**Comment by KomachiSion** [comment]
在插件中自己处理成prometheus内容即可。
