### ISSUE TITLE
节点down掉，gateway不能秒级刷新缓存的路由

### ISSUE THREAD

**Issue by qinghuozhang** [alibaba/nacos#10086]
i have two nodes, when one node is closed,can refresh the route info cached in the gateway?now i close one ,the gateway still send to the closed service.
一个服务有两个节点，当其中一个节点关掉的时候，能否主动刷新gateway中缓存的路由信息。现在我关掉一个节点，网关仍然后路由到已经关闭的节点上去。大概发送了不超过三次之后就全部发送到正常的节点了。浏览了一下issue列表，看到一个评论说nacos-client升级到2.1.0之后会快很多，不知道是否正确。以及CSDN上看其他的文章发现大家也有同样的问题，是否需要对gateway做一些配置，请指出来，谢谢

**Expected behavior**
期待gateway中的路由路由能立刻刷新

**Actually behavior**
从日志中可以看到nacos中的节点已经秒级下线了。但是gateway依然发送请求到关闭的节点了，

**Desktop (please complete the following information):**
 - nacos采用docker方式部署
 - Version ：nacos-server 2.1.1, nacos-client 2.0.3
 - SDK ：spring-cloud-alibaba-nacos

**Comment by KomachiSion** [comment]
Please move to gateway community.

**Comment by DCloudCoder** [comment]
请问作者 这问题你是如何处理的 我现在也遇到同样的情况
