### ISSUE TITLE
When the native nacos breaks the network with the service publisher(via iptables), other subscribers will get expried service list from other not native nacos.

### ISSUE THREAD

**Issue by Kiddo-scf** [alibaba/nacos#10088]
**Describe the bug**
1、启动 2 台 nacos 节点，让一个客户端注册服务 A 的一个实例 到 nacos1；
2、nacos1 断开与该客户端的网络（iptables），然后结束客户端进程（此时 nacos1 还会不停向 nacos2 发送 该客户端的 VERIFY 信息续约）；
3、启动一个新的客户端，向 nacos2 sub 服务A  ，此时还是可以拉取到服务A的实例

**Expected behavior**
责任nacos 与 服务发布者 断开网络后，不应再向其他 nacos 节点发送此 client 的 VERIFY 信息续约，而是清除 非责任nacos 节点中该 client 的缓存，从而避免其他订阅者拉取到脏数据。

**Actually behavior**
责任nacos 持续发送 断网client 的 VERIFY 信息，且订阅者拉取到过期的服务列表。

**Comment by KomachiSion** [comment]
客户端版本？

如果是2.x， 断网后需要等待链接断开，会自动摘除，摘除会发布DELETE事件，不仅不会发verify，也会直接摘除非责任节点的数据。

如果是1.x， 断网单个服务节点并没有作用，因为心跳请求发送到非责任节点，也会被路由到责任节点，所以实例依旧在续约心跳，无论责任节点还是非责任节点，都不会移除。

所以这个不是bug，是你测试方式有问题。只要数据还在，就应该发verify， 只有数据已经移除了，才应该停止。

**Comment by Kiddo-scf** [comment]
是 2.x 版本。 “断网后需要等待链接断开，会自动摘除”，这个等待时间大概是多长，至少按以上操作步骤，在一个小时内都没有触发 DELETE 事件，并且我的 服务发布者 早就下线了，而其他订阅者还是可以获取到这个服务实例，这结果显然不对吧。

**Comment by Kiddo-scf** [comment]
我的问题在于 服务发布者 下线后，其他 订阅者 还是在很长一段时间内能够获取到其发布的实例列表，而这些都是过期数据了。

**Comment by Kiddo-scf** [comment]
我的问题在于 服务发布者 下线后，其他 订阅者 在很长一段时间内还是能够获取到其发布的实例列表，而这些都是过期数据了。

**Comment by Kiddo-scf** [comment]
我的问题在于 服务发布者 下线后，其他 订阅者 在很长一段时间内还是能够获取到其注册的实例列表，而这些都是过期数据了。

**Comment by Kiddo-scf** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
服务端有过期检测， 会出现out of date之类的日志， 在服务端的remote-xxx.log里面

**Comment by Kiddo-scf** [comment]
@KomachiSion 那其他订阅者拉到的过期服务实例列表，这怎么解决？

**Comment by KomachiSion** [comment]
`过期` 是你定义的， 从nacos角度来看， 这个连接如果没有被移除， 那就是没过期。 服务端里数据还在，客户端获取到是正常的。

**Comment by Kiddo-scf** [comment]
@KomachiSion  服务实例的进程已经退出了（不存在 “服务端里数据还在”），而其他订阅者还能拿到这个实例的 ip，这明显是不正常的吧？感觉你没理解我的意思。

**Comment by Kiddo-scf** [comment]
@KomachiSion  服务实例的进程已经退出了，而其他订阅者还能拿到这个实例的 ip，这明显就是不正常的吧？只讨论现象。

**Comment by Kiddo-scf** [comment]
这应该是属于设计层面上的 bug 吧？连接没有被移除，不代表客户端进程还一直存在。

**Comment by KomachiSion** [comment]
这就好比心跳， 心跳不发了，但是程序还在，从服务端来看怎么判定。反之亦然。

目前nacos通过链接（2.x）和心跳（1.x）来判断服务是否存在。 tcp链接的准确度比心跳还是更准确的。

进程不在了 tcp链接一定不在了， 进程出问题，tcp的pingpong一般也有问题，也会被移除。

所以你的情况只是断网后， 连接的pingpong是否还能够正常被服务端收到。

如果是进程停止了， 但是服务端没感知到，或者是DELETE时间没有同步到其他节点导致其他节点的订阅者还能获取到， 这属于其他问题了。需要具体问题具体分析。

**Comment by Kiddo-scf** [comment]
@KomachiSion 嗯是的，我 case 中的场景就是 断网后还将这个客户端（publisher）进程关闭，并且从现象来看，显然是 nacos节点没有感知到该客户端已经挂了。

**Comment by KomachiSion** [comment]
断网的节点的

**Comment by Daydreamer-ia** [comment]
> 这应该是属于设计层面上的 bug 吧？连接没有被移除，不代表客户端进程还一直存在。

`Instance` 实例里有一个 `healthy` 属性，如果你针对服务的健康状态要求比较高的话，订阅者在获取到列表的时候，其实可以通过这个属性知道它是否正常

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
