### ISSUE TITLE
Springcloud服务启动异常，code=403,msg=unknown user

### ISSUE THREAD

**Issue by miaoyahong** [alibaba/nacos#10087]
配置信息如图
![image](https://user-images.githubusercontent.com/30410291/224732475-15a945b6-f901-441e-bae2-1df7e5a658b4.png)
JDK17，依赖如下
![image](https://user-images.githubusercontent.com/30410291/224733118-db36acba-e2bb-4b18-aac9-d6bda15701f0.png)
![image](https://user-images.githubusercontent.com/30410291/224732817-156cfd8b-a90e-47bd-be4d-1bb8ac5ea7a2.png)
报错信息
![image](https://user-images.githubusercontent.com/30410291/224733742-fece26fa-0b5d-4094-902c-8182f8861e13.png)
我debugger一下发现启动时NacosConfigProperties的init方法被执行了三次，第一次没有注入配置信息，后面两次有注入
![image](https://user-images.githubusercontent.com/30410291/224734415-b44367ae-3458-4384-9373-d04ea99c2680.png)
![image](https://user-images.githubusercontent.com/30410291/224734458-67724f91-55c4-4d4c-a26a-3c6646a51002.png)
但是服务注册是正常的
![image](https://user-images.githubusercontent.com/30410291/224735098-782ce45c-cc1e-46c2-87a5-fd55eedb1300.png)

**Comment by KomachiSion** [comment]
Please move issue to spring cloud alibaba
