### ISSUE TITLE
Can't find latest docker image 2.2.0.1

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#10096]
Only 2.2.0 here:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/1269496/224970010-340efe32-ab8b-4df6-a904-e977698a4f3c.png">

Could anyone trigger the release process?

**Comment by KomachiSion** [comment]
2.2.0 is enough, 2.2.0.1 only force required `token.secret.key`, others is same as 2.2.0.

Using 2.2.0 and set change `token.secret.key` is same as `2.2.0.1`.

**Comment by KomachiSion** [comment]
@paderlol Should release 2.2.0.1 docker images?

**Comment by wilsonwu** [comment]
In my understanding, every offical release should with docker image, and could we add the release process in CI? or I can contribute it (suggest move the dockerfile into this repo instead of in another standalone repo)

**Comment by tianwen2019** [comment]
docker image build by yourself :)
自己动手丰衣足食

**Comment by wilsonwu** [comment]
> docker image build by yourself :) 自己动手丰衣足食

如果这样，阿里不如把nacos捐出来吧，这么有用户基础的一个好的开源产品，这样下去前途堪忧。

**Comment by paderlol** [comment]
感谢指正,我已经发布了最新的版本,如果我没有看到, 其实大家可以自己提PR,合并后会自动发布. 它就是开源的,我也是其中的贡献者而已.
