### ISSUE TITLE
Only slim version of docker image support arm64

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#10097]
<img width="770" alt="image" src="https://user-images.githubusercontent.com/1269496/224974159-28d19ad3-fdce-4263-bb23-3369fbf930bb.png">
This need to be fixed.

**Comment by KomachiSion** [comment]
I can't get your problem, I see the tag has shown arm64

**Comment by wilsonwu** [comment]
I mean only v2.2.0-slim with arm64 arch, the v2.2.0 image only has amd64.

**Comment by KomachiSion** [comment]
yes, the reason is rocksdb  2.2.0 dependency can't support arm64 with openJDK.

The slim images is same codes with 2.2.0, but chech the jdk with warpper jdk to support m1 and arm64.

**Comment by wilsonwu** [comment]
Got it, I think we can have some docs to notice this to users.

**Comment by KomachiSion** [comment]
In 2.2.1, the rocksdb has been upgrade to support arm64 and m1 with openJDK, After several version test, the slim docker images may be not need to release.

**Comment by wilsonwu** [comment]
> In 2.2.1, the rocksdb has been upgrade to support arm64 and m1 with openJDK, After several version test, the slim docker images may be not need to release.

i thinks some different use cases request different images, need discuss for it based on some experienced people.

**Comment by KomachiSion** [comment]
The different cases should users build their owner images by themselves.

nacos images release is only to make users test and for the most common deploy. So we will only release one case image.

The `slim` images is for the same version but `can't work well` in some sys.

**Comment by wilsonwu** [comment]
@KomachiSion Understood, thanks for that, let's close this issue.
