### ISSUE TITLE
Why 2.0.4-slim support arm64 arch, but 2.1.2-slim missed it?

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#10109]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1269496/225505506-b7ec76b8-d5d8-47c7-bc83-9b44a9e14dfe.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1269496/225505576-7020d253-358d-4792-8361-90dd863a432a.png">

Shell we please make the release process more professional and automatically?

**Comment by paderlol** [comment]
The earliest script does not support arm64, is later optimized to support, if you think not enough you can submit PR, I am also one of the contributors @wilsonwu

**Comment by wilsonwu** [comment]
That is so confused, why the earlier version support amd64 and arm64, the later version can't support? Does the code be rollbacked? @paderlol

**Comment by wilsonwu** [comment]
And I checked the commit history:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/1269496/225879494-14fc8bbb-2cc5-4d24-9020-0eacd3013bfd.png">

from Mar. 22 the arm64 arg still there.

BTW, suggest don't directly submit commit to main branch, use PR instead, that is not a personal repo.

**Comment by KomachiSion** [comment]
I think it's only a tag description problem.  the 2.1.2-slim should also support arm64.

**Comment by wilsonwu** [comment]
@KomachiSion Seems not like that, I checked, the 2.1.2-slim like below:
```
regctl-darwin-amd64 manifest get nacos/nacos-server:v2.1.2-slim   
Name:        nacos/nacos-server:v2.1.2-slim
MediaType:   application/vnd.docker.distribution.manifest.v2+json
Digest:      sha256:51ceee8edf0df103ba0086107796c6667f64c7e3cce3889ef960336364be8749
Total Size:  178.8MB

Config:
  Digest:    sha256:b7bf3b593bd16e2168f6d7ab06365108b80ee0bf5e69bdcc8faec6fa74e30532
  MediaType: application/vnd.docker.container.image.v1+json
  Size:      6904B

Layers:

  Digest:    sha256:1efc276f4ff952c055dea726cfc96ec6a4fdb8b62d9eed816bd2b788f2860ad7
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      31.37MB

  Digest:    sha256:a2f2f93da48276873890ac821b3c991d53a7e864791aaf82c39b7863c908b93b
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      1.582MB

  Digest:    sha256:1a2de4cc94315f2ba5015e6781672aa8e0b1456a4d488694bb5f016d8f59fa70
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      210B

  Digest:    sha256:d2421c7a4bbfc037d7fb487893cc5fe145e329dfb39b5ee6557016bf6c34072d
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      41.7MB

  Digest:    sha256:e3eb9e5854dfe12819b8e67c0465f94ab1089c75afc37ac312d889b453018183
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      115B

  Digest:    sha256:70e7839a31e67a9ec508d3fb4835633a59114a7738823ab9be3f99ccf70235ce
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      104.2MB

  Digest:    sha256:2a445d34ae39b98ae64654074b54d885c6fbbfe6063d57ca471a2324c8307092
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      1920B

  Digest:    sha256:58408fae13a199c3105b5afa540a59d2643ceb60d42bbbba14e6a05649039158
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      1364B

  Digest:    sha256:6a177547f7faaeabd6709482b6a554015d2b662731f9ebba310707dd6e851dbe
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      189B

  Digest:    sha256:1162e6244ba592995df15b620bd495fb76dda22b0e5205e4e2e69f7f93b0a574
  MediaType: application/vnd.docker.image.rootfs.diff.tar.gzip
  Size:      1929B
```

And the 2.2.0-slim that support arm and amd shows this:
```
regctl-darwin-amd64 manifest get nacos/nacos-server:v2.2.0-slim
Name:        nacos/nacos-server:v2.2.0-slim
MediaType:   application/vnd.docker.distribution.manifest.list.v2+json
Digest:      sha256:e9a4a10384399fce92f47e9115f5f3ee6375fef899735747b24f72468984619c

Manifests:

  Name:      docker.io/nacos/nacos-server:v2.2.0-slim@sha256:647c74dbad634c65eb542d102e48da1c9be4304ded253396d092ac71f4005816
  Digest:    sha256:647c74dbad634c65eb542d102e48da1c9be4304ded253396d092ac71f4005816
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      docker.io/nacos/nacos-server:v2.2.0-slim@sha256:b1c8972c972bbf311ebf80531ca4c20969272b12b61da4609efe1da40ed93576
  Digest:    sha256:b1c8972c972bbf311ebf80531ca4c20969272b12b61da4609efe1da40ed93576
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```

**Comment by paderlol** [comment]
I just checked the Dockerfile.slim, and I don't see any difference, Let me check later

**Comment by paderlol** [comment]
> That is so confused, why the earlier version support amd64 and arm64, the later version can't support? Does the code be rollbacked? @paderlol
I just checked the commit logs for 2.1.1 and 2.1.2 files, and there is no difference with the current `Dockerfile.slim`

**Comment by paderlol** [comment]
Thanks again,  I just redistributed for **v2.1.1-slim** and **v2.1.2-slim**  and used the same code as then, both arm64 and amd64 are already supported.
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/7919984/226586650-e457a177-61d5-4c1d-96b2-3f03c7822f3e.png">

and I didn't change anything, which doesn't make sense. then I can only suspect that someone has manually posted an image.
