### ISSUE TITLE
NacosTraceSubscriber 为什么不生效

### ISSUE THREAD

**Issue by qinghuozhang** [alibaba/nacos#10106]
nacos server和client都是2.2.0版本，gateway中仿照nacos-plugin中的demo集成了NacosTraceSubscriber
，但是服务上下线的时候并没有触发NacosTraceSubscriber的事件打印日志出来

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/225494912-1c736607-9138-49c4-b5d9-93de4d9c991a.png)

Trace plugin is a server plugin, your gateway should be client part. So it has no used.

client contain `subscribe` feature from started version, Please see `Java-SDK` document.
