### ISSUE TITLE
About QVD-2023-6271  

### ISSUE THREAD

**Issue by jinanxiaolaohu** [alibaba/nacos#10103]
How can I resolve this security problem About QVD-2023-6271  
in https://mp.weixin.qq.com/s/5lE_9I6-r1CE8CYtUZG1rQ

In your doucument, 

Sholud I Change "nacos.core.auth.enabled" and "nacos.core.auth.default.token.secret.key" both

Or Change "nacos.core.auth.default.token.secret.key"  only ? 

IF change both , Should we update our app to access my nacos server? 

Thanks

**Comment by YunWZ** [comment]
both are required

**Comment by KomachiSion** [comment]
If your app don't set the username and password, you should set the user and password to your app and restart.

**Comment by KomachiSion** [comment]
Suggest move to #10105 to discuss.
