### ISSUE TITLE
nacos 1.4.3 页面创建完用户的用户名就会多一个nacos,的前缀（如nacos,username这样）  导致下面的关联都失效了，此版本如何解决问题

### ISSUE THREAD

**Issue by wsw136** [alibaba/nacos#10107]
After the user's user name is created on the page of nacos 1.4.3, there will be one more nacos prefix (such as nacos, username), which causes the following associations to be invalid. How to solve the problem in this version

![image](https://user-images.githubusercontent.com/36026057/225488408-6582216b-e75d-4c76-9fc6-54fd229dd563.png)
![image](https://user-images.githubusercontent.com/36026057/225488506-913c2f73-288a-4c58-af06-242913d30198.png)
![image](https://user-images.githubusercontent.com/36026057/225488578-2689f55a-0ecf-419c-b7e5-dd2870e8bfca.png)

**Comment by wsw136** [comment]
![image](https://user-images.githubusercontent.com/36026057/225488801-1da8260d-1e58-424e-8e70-de86a996efa7.png)

**Comment by KomachiSion** [comment]
This bug has been fixed in new version, Please upgrade to 1.4.4 or 2.X and clean the web cache and retry.

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
