### ISSUE TITLE
when I tried to add @RefreshScope to Controller ,It did not take effect

### ISSUE THREAD

**Issue by Raremaa** [alibaba/nacos#1010]
Here my code:
`
@RestController
@RequestMapping("/config")
@RefreshScope
public class ConfigController {

	@Value("${useLocalCache:false}")
	private boolean useLocalCache;

	@RequestMapping("/get")
	public boolean get() {
		return useLocalCache;
	}
}
`
I tride to use @RefreshScope to auto-update my config.
When I first run my project,I can get  useLocalCache from Nacos config.What's more,I change this variable in Nacos config,my project dont update automatically

**Comment by xyang0917** [comment]
同问

**Comment by mouse2001xu** [comment]
the same question

**Comment by fangjian0423** [comment]
please use the right [version mapping]( https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E ) and refer [nacos-config-example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example).
