### ISSUE TITLE
与spring-cloud-starter-alibaba-nacos-discovery存在兼容性问题

### ISSUE THREAD

**Issue by MI-cool** [alibaba/nacos#10110]
spring-cloud-starter-alibaba-nacos-discovery 2.2.9.RELEASE版本采用如下配置

<img width="316" alt="image" src="https://user-images.githubusercontent.com/9128391/225521111-c4346d14-1a3f-4bdc-aa14-c1aa78a7563e.png">

会遇到"serverList is empty,please check configuration"

**Comment by KomachiSion** [comment]
endpoint 和serverAddr是两种不同的设置方式， 目前的逻辑没有问题，不需要进行修改。

**Comment by MI-cool** [comment]
没问题我不会提交PR，麻烦按截图验证

**Comment by MI-cool** [comment]
之前的端口8848和nacos server默认端口一样，乍看上去有歧义。
<img width="323" alt="image" src="https://user-images.githubusercontent.com/9128391/225531865-6e16a817-ba38-44e1-beb5-e173fc3acb85.png">
curl localhost:8080 会返回 localhost:8848

**Comment by KomachiSion** [comment]
没看懂问题， endpoint模式我们验证过没问题。

endpoint是地址服务器地址， 完整的请求应该是${endpoint}/nacos/serverlist

返回的地址应该不带有端口号如：1.1.1.1

然后client再去访问1.1.1.1:8848。

**Comment by KomachiSion** [comment]
或者你看下升级nacos-client是否能解决， 我印象中有一个客户端版本被社区改出过问题， 具体哪个版本忘记了。

**Comment by MI-cool** [comment]
> 或者你看下升级nacos-client是否能解决， 我印象中有一个客户端版本被社区改出过问题， 具体哪个版本忘记了。

刚刚验证了一下，nacos-client 2.2.0已经没有这个问题了
