### ISSUE TITLE
Proposal about file path encode

### ISSUE THREAD

**Issue by Daydreamer-ia** [alibaba/nacos#10119]
## Background
某些操作系统在文件的命名上有特殊字符的限制，有些用户针对某些特殊字符又有述求，如 `dubbo` 在很多配置上会需要使用到 :，而在有些操作系统，如 `Windows` 不支持该字符，导致外部数据源的配置无法加载到文件系统。
在有外部数据源的情况下，配置查询的时候优先读取文件系统配置文件，如果含有特殊字符，那么该文件大概率是不存在的，导致查询出现 `404` 情况(但实际配置是存在的)。
相关 `issue`：#10067

### 核心组件
- `PathEncoder`：负责针对**具体某个操作系统**，对路径判断是否编码以及具体编码操作，服务端启动时只会使用一个或不使用 `PathEncoder`；
- `PathEncoderManager`：负责识别当前操作系统，决定使用哪个 `PathEncoder`，如果没有当前操作系统没有 `PathEncoder`，那就不做路径编码；<br/>
也就是说，把判断路径要不要编码分成两部分：**当前平台用不用做路径编码**、**在指定平台下这个路径用不用编码**。
- 判断平台用不用编码就取决 `PathEncoder` 存不存在；
- 判断具体平台下某个路径用不用编码，就在 `PathEncoder::needEncode()` 实现；

### 具体实现
1. 怎么识别系统 `os` 需不需要替换
可选方式：
● `File::createNewFile()`，当文件名非法时，会返回 `false`(这种开销有点大, 放弃使用)
● 采用正则匹配，如果发现含有非法字符，就让进行重新编码(目前实现)

2. 在哪里收敛这个替换文件名的操作，保证读写的原子性
配置从外部数据源 `IO` 到本地文件系统的操作，在服务端启动、配置变更操作时，在 `ConfigCacheService` 中完成，具体是使用 `DiskUtil` 工具类(包括在配置进行查询的时候)。
故：在`DiskUtil`工具类 `IO` 操作前，添加一个中间层进行文件名的替换，将编码、解码和匹配 `key` 判断是否编码抽象成接口,在 `needEncode(String key)` 返回 `true` 时进行替换，编码方式根据各自操作系统特殊处理。
比如：`windows` 不支持 `/` 、`:`、 `?`、 `"`、 `<`、 `>`、 `|`、 `\`，就将他们进行替换，其他操作系统在有述求的时候再重新实现  `PathEncoder` 进行处理。

为了拓展性着想，所以让这块做成插件式，然后各自操作系统使用对应的 `PathEncoder`。`PathEncoderManager` 负责去加载已经实现的所有 `PathEncoder`，通过 `System.getProperty("os.name")` 知道当前平台，然后对应系统该操作系统的 `PathEncoder`。在一个 `Server` 下，只会有 `0` 个或 `1` 个 `PathEncoder` 在运行。
判断路径要不要编码分成两部分：**当前平台用不用编码**、**在当前平台下这个路径用不用编码**。
- 判断**平台用不用编码**就取决 `PathEncoder` 存不存在；
- 判断**具体平台**下某个路径用不用编码，就在 `PathEncoder::needEncode()` 实现；
<img width="1000" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225803891-c7a9c856-3aec-4c7f-b944-ebd3b1ef97aa.png">

<img width="504" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225804493-ab7485ff-514f-4198-b70d-89795d3f5a53.png">
<br/>
<img width="504" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225804656-645e8612-6157-406c-939f-a8f90f5dedad.png">

`PathEncoder` 收集到 `PathEncoderManager` 中，与外界隔离，通过 `PathEncoderManager` 暴露编码和解码接口，同时 
 `PathEncoderManager` 负责识别 `OS` 激活对应编码器。最后将 `PathEncoderManager` 嵌入到 `DiskUtil` 的 `IO` 流程中，在操作前对文件/目录进行编码即可。
<img width="504" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225805469-c3ffdf79-417c-4c59-9ea3-e7f4cfafa364.png">

## Example
将 `Nacos-Sever` 部署在 `Windows` 下，`PathEncoderManager` 在类加载的时候，就 `SPI` 加载所有的 `PathEncoder`，然后通过 `System.getProperty("os.name")` 得知当前部署平台，匹配对应平台的 `PathEncoder`。
在调用 `PathEncoderManager::encode(path)` 的时候，`PathEncoderManager::encode` -> 判断是否激活 `PathEncoder`(判断当前平台是否需要路径编码) -> `PathEncoder` 启用时，`PathEncoder::needEncode(path)` -> 

> 关于编码为何不使用 `URLEncoder`？

不采用 `UrlEncoder` 是因为发现有如 `*` 虽然符合 `URL` 编码，但是 `Windows` 并不合法，需要再进行额外处理，代码会变得复杂。再加上很多操作系统支持的字符，在 `URL` 编码里不支持，使用 `URLEncoder` 会造成多余字符的编码，而且多余编码多了，会导致文件名长度变长，有概率会超过 `OS` 最大文件名长度，`Windows`下禁用的词不多，所以决定单独对字符进行处理。

## End
​感谢你的阅读！以上是我针对特殊字符处理的 `proposal`。如果有哪些场景没有考虑到或者设计上存在问题，希望你能在评论区给我留言。我期待着收到你的宝贵建议，非常感谢！

## Background
In order to improve robustness for Nacos, it will load config from external data source to disk. However, some file systems have restrictions on special characters in the naming of files, and some users have requirements for special characters. For example, the character ":" is illegal for Windows, but it is indispensible if you are using dubbo.
Related issues: #10067

## Solution
1. How to identify whether the name of file needs to be replaced for os?
optional: 
- Using `File::createFile()` api, it will return `false` if naming is illegal. But it is expensive.(Abandoned)
- Use regular expressions to match file names to determine whether they are legal.(Using)
2. Where can we complete the operation of replacing the file name and ensure the atomicity of reading and writing?
The operation of loading configs from external data source to disk is completed in the 'ConfigCacheService' when server starting or config change. More detail is available in `DiskUtil`(Including query config).
Therefore, we can replace special character before `DiskUtil` write config to disk. We will not always do that, because some OS don't need to replace special character. Extract encoding, decoding, and matching 'key' to determine whether to encode into an interface. We replace some characters when `needEncode(String key)` return `true`, and the detail of encoding and decoding are delegated to the implement of actual OS.
For example, Windows OS does not support /, :, ", <, >,  |, replace them, and other operating systems will re-implement `PathEncoder` for processing when required.
<img width="1000" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225803891-c7a9c856-3aec-4c7f-b944-ebd3b1ef97aa.png">
For the sake of extensibility, making `PathEncoder` being plug-ins, and then use the corresponding `PathEncoder` for each 
 OS.
<img width="504" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225804493-ab7485ff-514f-4198-b70d-89795d3f5a53.png">
<br/>
<img width="504" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225804656-645e8612-6157-406c-939f-a8f90f5dedad.png">
`PathEncoder`s are collected into the `PathEncoderManager` and isolated from the outside world. The encoding and decoding interfaces are exposed through the `PathEncoderManager`, while `PathEncoderManager` is responsible for identifying the OS and activating the corresponding encoder.
Finally, embed `PathEncoderManager` into the 'IO' process of `DiskUtil`, and encode the name of file/directory before `IO`.
<img width="504" alt="2023-03-14_202720" src="https://user-images.githubusercontent.com/83362909/225805469-c3ffdf79-417c-4c59-9ea3-e7f4cfafa364.png">

> Why not use 'URLEncoder' for encoding?

The reason why `UrlEncoder` is not used is because it has been found that '*' conforms to the URL code, but it is not legal for Windows, requiring additional processing, and the code can become complex. In addition, many characters supported by the operating system are not supported in the URL code. Using `URLEncoder` may cause encoding of redundant characters, and excessive encoding can lead to the longer file name, with a probability of exceeding the OS maximum file name length. There are not many disabled words for Windows, so it is decided to process the characters separately.

## End
​Thank you for reading! The above is my proposal for special character processing. If there are any scenarios that have not been considered or have design issues, I hope you can leave me a message in the comment. I am looking forward to receiving your valuable suggestions. Thank you very much!

**Comment by KomachiSion** [comment]
1. 识别os系统的问题，始终没有看到回答，究竟是如何判断这个os需要替换path？

**Comment by Daydreamer-ia** [comment]
> 1. 识别os系统的问题，始终没有看到回答，究竟是如何判断这个os需要替换path？

每个操作系统都有一个 `PathEncoder`，在 `needEncode(path)` 判断，比如 `Windows` 下的就是判断是否含有那几个非法字符，用**正则**实现的，具体代码看 #10101 里的 `WindowsEncoder` 文件

**Comment by Daydreamer-ia** [comment]
> 1. 识别os系统的问题，始终没有看到回答，究竟是如何判断这个os需要替换path？

在 `PathEncoderManager` 根据当前操作系统决定是否启动或者选择使用哪个 `PathEncoder`，比如 `Windows` 就使用 `WindowsEncoder`，对于 `Linux` 的没有字符限制，就不做冗余的编码处理。然后具体判断某个路径是否要编码和如何编解码，就交给 `PathEncoder` 完成。

**Comment by Daydreamer-ia** [comment]
> 1. 识别os系统的问题，始终没有看到回答，究竟是如何判断这个os需要替换path？

目前只有 `Windows` 有需求，所以只实现了 `Windows` 的 `PathEncoder`，后续如果有其他操作系统也有需要，再去重新拓展一个 `PathEncoder` 就好。
如果哪里还有问题的话，我再想想

**Comment by KomachiSion** [comment]
看起来有一些疑惑， `needEncoder`不是应该在调用`Encoder`之前判断吗？ 交给`Encoder`自己来判断感觉不太好，感觉应该是由`Manager`来判断， 举个例子， 比如`:` 在linux系统下的时候，其实根本不需要调用到`WindowsEncoder`，应该走`LinuxEncoder`或者直接不需要走`Encoder`。

**Comment by KomachiSion** [comment]
我感觉流程应该是：
`Manager.encode` --> `Manager.needEncoder(private method)` -true-> `Manager.findEncoder` --> `Encoder.encode()`
或  `Manager.encode` --> `Manager.needEncoder(private method)` -false   --> `return original path`

**Comment by KomachiSion** [comment]
还有一点， Encoder里同时有encode和decode方法应该不合理，可以考虑换成PathConverterManager 和PathConverter或其他更高涵盖了`encode`和`decode`语义的。

**Comment by Daydreamer-ia** [comment]
> 看起来有一些疑惑， `needEncoder`不是应该在调用`Encoder`之前判断吗？ 交给`Encoder`自己来判断感觉不太好，感觉应该是由`Manager`来判断， 举个例子， 比如`:` 在linux系统下的时候，其实根本不需要调用到`WindowsEncoder`，应该走`LinuxEncoder`或者直接不需要走`Encoder`。

是的。`needEncode(path)` 方法在 `PathEncoder` 里实现，但是在 `PathEncoderManager` 里调用的，`PathEncoderManager` 对上层只暴露两个接口：`encode` 和 `decode`。在 `PathEncoderManager::encode()` 里先调用 `PathEncoder::needEncode()`，在返回为 `true` 才会调用 `PathEncoder::encode`

**Comment by Daydreamer-ia** [comment]
> 看起来有一些疑惑， `needEncoder`不是应该在调用`Encoder`之前判断吗？ 交给`Encoder`自己来判断感觉不太好，感觉应该是由`Manager`来判断， 举个例子， 比如`:` 在linux系统下的时候，其实根本不需要调用到`WindowsEncoder`，应该走`LinuxEncoder`或者直接不需要走`Encoder`。

没有实现`Linux` 系统的 `PathEncoder`，这类系统在部署运行服务端的时候是不会激活 `PathEncoder` 的，即不做任何编码

**Comment by Daydreamer-ia** [comment]
> 我感觉流程应该是： `Manager.encode` --> `Manager.needEncoder(private method)` -true-> `Manager.findEncoder` --> `Encoder.encode()` 或 `Manager.encode` --> `Manager.needEncoder(private method)` -false --> `return original path`

这个调用链路是对的，按照目前的逻辑就是这样。

**Comment by Daydreamer-ia** [comment]
> 看起来有一些疑惑， `needEncoder`不是应该在调用`Encoder`之前判断吗？ 交给`Encoder`自己来判断感觉不太好，感觉应该是由`Manager`来判断， 举个例子， 比如`:` 在linux系统下的时候，其实根本不需要调用到`WindowsEncoder`，应该走`LinuxEncoder`或者直接不需要走`Encoder`。

`PathEncoderManager` 会在服务端启动的时候去识别平台，然后用 `SPI` 加载所有已经实现的 `PathEncoder`，如果当前平台和所有的`PathEncoder`都不匹配，就不会开启编码，比如目前只实现 `Windows` ，其他平台都不会做任何编码，`WindowsEncoder` 也不会激活。
也就是，我把判断路径要不要编码分成两部分：当前平台用不用编码、在当前平台下这个路径用不用编码。判断平台用不用编码就取决 `PathEncoder` 存不存在，判断具体平台下某个路径用不用编码，就在 `PathEncoder::needEncode()` 实现
