### ISSUE TITLE
The namesapce settings is invalid when service registed on nacos

### ISSUE THREAD

**Issue by winnyboy** [alibaba/nacos#1011]
Below is my confirgaution section of nacos:
spring.application.name=gateway-service
spring.cloud.nacos.discovery.server-addr=10.96.6.27:8848
spring.cloud.nacos.discovery.namespace=899d31c8-18d8-488e-ab20-cddb1266768e
spring.cloud.nacos.config.server-addr=10.96.6.27:8848
#spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.shared-dataids=common.properties
spring.cloud.nacos.config.refreshable-dataids=common.properties
spring.cloud.nacos.config.namespace=899d31c8-18d8-488e-ab20-cddb1266768e

when service started, its can read settings from the configurtion setting in different namespace of nacos , but service only registed in namespace of public, not the specified of the namespaceid

服务注册时配置的namespace无效，服务永远只注册到public命名空间，而不会注册到在配置中指定的命名空间， 但config指定的命名空间却是有效的。

**Comment by nkorange** [comment]
Naming supports namespace, see #806 .
