### ISSUE TITLE
Spring boot upgrade to version 2.6 ConfigFileApplicationListener outdated nacos auto-refresh nacos failure or 1.0 version How to solve?

### ISSUE THREAD

**Issue by bambooToxic** [alibaba/nacos#10122]
Spring boot upgrade to version 2.6 ConfigFileApplicationListener outdated nacos auto-refresh nacos failure or 1.0 version Due to the relatively large systems Not all migrated to nacos2.0 version above If there is a solution at present The current situation is urgent, so it cannot be upgraded

spring boot 升级到2.6版本 ConfigFileApplicationListener 已过时 nacos自动刷新失败 nacos还是1.0版本 由于系统比较庞大  无法全部迁移到nacos2.0以上版本  目前是否有解决方案  后续慢慢升级 目前情况比较紧急所以没办法升级  
![image](https://user-images.githubusercontent.com/25840025/225857739-5574154b-7718-411f-a525-efa527fdc2b9.png)

**Comment by hujun-w-2** [comment]
提供一下nacos-spring-project和nacos-spring-boot-project的版本，还有配置信息

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
