### ISSUE TITLE
bug: Always return true, code : " !Arrays.asList(new boolean[1]).stream().anyMatch(Boolean.FALSE::equals) "

### ISSUE THREAD

**Issue by varyuan** [alibaba/nacos#10128]
**Describe the bug**
Always return true, code : " !Arrays.asList(new boolean[1]).stream().anyMatch(Boolean.FALSE::equals) "
Impact Code:com.alibaba.nacos.core.distributed.raft.NacosStateMachine#adapterToJRaftSnapshot
line 281

总是返回true,"!Arrays.asList(new boolean[1]).stream().anyMatch(Boolean.FALSE::equals)"
影响代码:com.alibaba.nacos.core.distributed.raft.NacosStateMachine#adapterToJRaftSnapshot
第281行

**Expected behavior**
Check whether all the values in boolean [] are true. If yes, return true, otherwise return false
要实现的结果是 检查boolean[]中是否全为true, 是则返回true,否则返回false

**Actually behavior**
Always return true
永远返回true

**How to Reproduce**
已提交pr #10129 
```java
import java.util.Arrays;

public class SimpleTest {

    public static void main(String[] args) {
        System.out.println(oldCode());
        System.out.println(newCode());
        System.out.println(Arrays.asList(new boolean[5]).size());
        System.out.println(Arrays.asList(new Boolean[5]).size());
    }

    // 要实现的结果是 检查boolean[]中是否全为true, 是则返回true,否则返回false
    // 旧代码, 永远返回true, 不管results里面元素是什么, 因为Arrays.asList(results) 把boolean[] 当成一个元素加入到新数组
    public static boolean oldCode() {
        boolean[] results = new boolean[5];// 元素默认值false
//        Arrays.fill(results, true);
        return !Arrays.asList(results).stream().anyMatch(Boolean.FALSE::equals);
    }

    //
    public static boolean newCode() {
        Boolean[] results = new Boolean[5];
        Arrays.fill(results, Boolean.FALSE);
        return Arrays.stream(results).allMatch(Boolean.TRUE::equals);
    }
}
```

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Salhazry** [comment]
9bb12bdddfcd11cff0b6087c076bbd9604e63ffa
