### ISSUE TITLE
Consider bumping protobuf-java to 3.22+

### ISSUE THREAD

**Issue by n1x0l4s** [alibaba/nacos#10137]
Building the project, I get class access errors, like https://github.com/protocolbuffers/protobuf/issues/11986 

the related commit is https://github.com/protocolbuffers/protobuf/commit/c658e27529ccf4a000724ab3622f1b807c85449b

**Comment by n1x0l4s** [comment]
Fresh clone from branch `develop` with aliyun's maven mirror, the OS is Windows, the build produced `emptyList() is not public in LazyStringArrayList; cannot be accessed from outside package` and thus searched for a bit and provided related protobuf commit. Would you elaborate what other environment details needed to  be addressed?

**Comment by KomachiSion** [comment]
I use linux sys or mac sys to do build with jdk8 and jdk11. I work well.

The maven mirror is default open repo.

**Comment by KomachiSion** [comment]
I don't has window sys and no use window sys to build. Need community help to test.

About the protobuf-java version, If upgrade 3.22+ has no compatibility issues, It can be upgrade without immediatly.

**Comment by n1x0l4s** [comment]
For now leave the issue open as force loading `protobuf-java 3.22.2` here on my local dev machine solves the issue. I suggest closing this after verifying upgrade compatibility.

**Comment by KomachiSion** [comment]
Welcome submit PR.

**Comment by n1x0l4s** [comment]
Upon further inspection, this non issue is local since my former build generated entity from protoc 3.22 which has compability conflits with protobuf-java 3.21.11. The protoc maven plugins were locally masked by local maven profile settings.
Since no `.emptyList()` from protobuf project is being used in this code base, the upstream change has no affect, thus closing the issue.
