### ISSUE TITLE
Could not resolve placeholder 'NACOS_AUTH_IDENTITY_KEY' in value "${NACOS_AUTH_IDENTITY_KEY}"

### ISSUE THREAD

**Issue by wuai1024** [alibaba/nacos#10130]
升级到最新的Nacos v2.2.1后，启动报这个错误。

**Comment by himuyu** [comment]
我也遇到这个问题，请问怎么解决呢

**Comment by yeyoui** [comment]
v2.2.1我折腾一小时没解决，后面放弃了用 v2.2.0成功了

**Comment by wuai1024** [comment]
我解决了，需要添加3个参数。

**Comment by sui-mu** [comment]
添加了哪几个参数呢？

**Comment by wuai1024** [comment]
> MAC m2 启动成功。 版本： v2.2.0.1-slim 在启动时我指定了 platform: linux/arm64 docker-compose.yml 如下：
> 
> ```
> version: '3.8'
> services:
>   nacos:
>     container_name: nacos
>     image: nacos/nacos-server:v2.2.0.1-slim
>     platform: linux/arm64
>     ports:
>       - "8848:8848"
>       - "9848:9848"
>       - "9849:9849"
>     volumes:
>       - ./nacos/conf:/home/nacos/conf
>       - ./nacos/logs:/home/nacos/logs 
>     #restart: 
>     environment:
>       - MODE=standalone
>       - SPRING_DATASOURCE_PLATFORM=mysql
>       - MYSQL_SERVICE_HOST=mysql
>       - MYSQL_SERVICE_DB_NAME=nacos
>       - MYSQL_SERVICE_USER=nacos
>       - MYSQL_SERVICE_PASSWORD=nacos
> ```

你这个不是最新版，最新版本是 v2.2.1

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/blog/announcement-token-secret-key.html

**Comment by gy8409** [comment]
> 需要额外添加这三个参数
> 
> ```shell
> NACOS_AUTH_TOKEN=
> NACOS_AUTH_IDENTITY_KEY=
> NACOS_AUTH_IDENTITY_VALUE=
> ```

这几个参数加在哪里呢？

**Comment by wuai1024** [comment]
> > 需要额外添加这三个参数
> > ```shell
> > NACOS_AUTH_TOKEN=
> > NACOS_AUTH_IDENTITY_KEY=
> > NACOS_AUTH_IDENTITY_VALUE=
> > ```
> 
> 这几个参数加在哪里呢？


如果是docker启动的，就放在 env里，正常启动的放配置文件里。之前我更新的时候文档还没更新，你现在看看最新文档，更新了没有。

**Comment by qinggemei** [comment]
看公告有些写

**Comment by qinggemei** [comment]
docker run  --name nacos2.2.1 --env NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789  --env NACOS_AUTH_IDENTITY_KEY=serverIdentity --env NACOS_AUTH_IDENTITY_VALUE=security --env PREFER_HOST_MODE=hostname --env MODE=standalone --env NACOS_AUTH_ENABLE=true -p 8848:8848 nacos/nacos-server:v2.2.1
