### ISSUE TITLE
java.lang.ref.Finalizer

### ISSUE THREAD

**Issue by lovlyhao** [alibaba/nacos#10135]
nacos-server 2.0.2 、nacos-clinet 2.0.2 属性引用 com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.Recycler$WeakOrderQueue$Head

![226091599-27f36f86-97e0-4eed-af1a-4a17398a8bf7](https://user-images.githubusercontent.com/30038949/226093238-acc69a0e-5d94-45b1-8405-548bdfdf206d.png)

**Comment by KomachiSion** [comment]
I can't get what's your problem. Do you want to say the memory usage?

It should be a weak refence queue of grpc, if the queue is full means your client can't handle response or your server can handle request.

**Comment by lovlyhao** [comment]
是这样的， 项目fullgc 124次， 然后dump下内存信息 ，用mat分析如下

![image](https://user-images.githubusercontent.com/30038949/226279796-710df554-b475-4769-b6b9-907469fa95b0.png)

大对象如下
![image](https://user-images.githubusercontent.com/30038949/226279872-1b040dff-420d-4ef2-b1a1-7f5ff6ed0593.png)

查看了with incoming references  如下 
![image](https://user-images.githubusercontent.com/30038949/226280256-cf9cd763-5b3a-49d6-a53f-d452de213d87.png)

看了com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.Recycler.WeakOrderQueue.Head 里重写了finalize 
![image](https://user-images.githubusercontent.com/30038949/226280394-1cf19476-8ca6-447f-ac91-586bed76a062.png)


目前也不是很懂， 跟进目前信息猜测是nacos-client 2.0.2 出现了问题 


@KomachiSion

**Comment by KomachiSion** [comment]
这段代码是grpc的代码， 只是为了避免和用户自己引入的grpc版本冲突而选择了shaded进client中。

可以试着升级一下新版本的client，看下新版本所依赖的grpc是否存在这个问题。

**Comment by lovlyhao** [comment]
我试试

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
