### ISSUE TITLE
How to use https to access the registration center nacos

### ISSUE THREAD

**Issue by niget** [alibaba/nacos#1013]
我在源码中,找到了  com.alibaba.nacos.client.naming.tls.enable  参数,可以开启https,但是为什么不能直接通过在配置文件中编写https://的方式来实现呢?

相反,我写了http或者https以后,会导致注册失败,因为访问时候会变成 http://http:// 这样子

另外,目前只能通过 System.setProperty("com.alibaba.nacos.client.naming.tls.enable", "true"); 这样的方式来开启么? 还是有什么可以配置的参数呢

同样的,还有端口号问题,必须强制填写443,否则就会默认加上8848.  我觉得 com.alibaba.nacos.client.naming.net.NamingProxy  应该多些判断,少一些http://和端口号的硬编码

**Comment by nkorange** [comment]
@niget https is not supported by Nacos now.
