### ISSUE TITLE
特定运行环境下获取不到配置

### ISSUE THREAD

**Issue by WhoisX** [alibaba/nacos#10136]
使用k8s 部署 spring cloud alibaba  nacos-client版本为2.2.0
运行用户为root

无法获取nacos配置 同时/root/logs/nacos下 会输出日志文件 但是文件内容为空.
降级到2.1.2后 故障消失

**Comment by KomachiSion** [comment]
故障是说日志没打印出来还是配置获取不到？

**Comment by KomachiSion** [comment]
特定运行环境是什么环境？

**Comment by WhoisX** [comment]
> 故障是说日志没打印出来还是配置获取不到？

日志不输出 配置也获取不到

**Comment by WhoisX** [comment]
> 特定运行环境是什么环境？
我这里是k8s下跑的容器, 之前本地测试 发现把 spring cloud打包成docker image 启动也会触发这个bug
基础镜像是 : anapsix/alpine-java:8_server-jre_unlimited

**Comment by KomachiSion** [comment]
我使用原生nacos-client 2.2.0 + nacos-server 2.2.0进行配置获取（系统centos7 和 macOS均正常）， 无法复现问题。

可能和环境或者应用包冲突有关，需要您自行排查下或提供更多信息

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by joyce0323** [comment]
解决了吗？k8s下部署的nacos2.2.0 获取到的[Nacos Config] config[dataId=mysql.properties, group=DEFAULT_GROUP] is empty。
非k8s部署的，centos下直接jar启动的服务就可以

**Comment by joyce0323** [comment]
> 解决了吗？k8s下部署的nacos2.2.0 获取到的[Nacos Config] config[dataId=mysql.properties, group=DEFAULT_GROUP] is empty。 非k8s部署的，centos下直接jar启动的服务就可以

问题解决了，原因是k8s部署之后grpc端口没映射出来，放开9848和9849端口访问就OK了。
![image](https://github.com/alibaba/nacos/assets/25663382/095b20dc-5561-417d-8ca6-77f98259d86c)
