### ISSUE TITLE
nacos2.1.1extension-configs的拓展配置的修改不会动态刷新和客户端的这个接口nacosConfigManager.getConfigService().getConfig(dataId, group, 5000L);获取不到配置中心的配置返回的是null

### ISSUE THREAD

**Issue by BigBigFeiFei** [alibaba/nacos#10139]
**Describe the bug**
1.我在使用hippo4j实现动态线程池,然后写了一个demo，集成了nacos2.1.1的服务端、客户端还有集成sprinBoot、springCloudAliBaBa相关依赖,调试源代码发现nacos2.1.1的nacosConfigManager.getConfigService().getConfig(dataId, group, 5000L);获取不到配置中心的配置返回的是null
hipp4j的代码如下：
‘public String getProperties() throws Exception {
        Map<String, String> nacosConfig = bootstrapConfigProperties.getNacos();
        String dataId = nacosConfig.get(DATA_ID);
        String group = nacosConfig.get(GROUP);
        return nacosConfigManager.getConfigService().getConfig(dataId, group, 5000L);
    }
’
接口代码获取不到nacos服务端的扩展配置信息，扩展配置信息更新也没有回调hippfj的监听器
‘ @Override
    public void afterPropertiesSet() throws Exception {
        Map<String, String> nacosConfig = bootstrapConfigProperties.getNacos();
        nacosConfigManager.getConfigService().addListener(nacosConfig.get(DATA_ID),
                nacosConfig.get(GROUP), new Listener() {

                    @Override
                    public Executor getExecutor() {
                        return dynamicRefreshExecutorService;
                    }

                    @Override
                    public void receiveConfigInfo(String configInfo) {
                        dynamicRefresh(configInfo);
                    }
                });
        log.info("Dynamic thread pool refresher, add nacos cloud listener success. data-id: {}, group: {}", nacosConfig.get(DATA_ID), nacosConfig.get(GROUP));
    }
’
上面两段代码都是在hipp4j的NacosCloudRefresherHandler类中
下面这个是hipp4j项目的gitHub地址,也是我们国人写的一个开源项目
https://github.com/opengoofy/hippo4j

demo中的pom依赖版本如下：
<hippo4j.version>1.4.3-upgrade</hippo4j.versio>
<spring.boot.version>2.3.12.RELEASE</spring.boot.version>
<spring-cloud.version>Hoxton.SR12</spring-cloud.version>
 <spring-cloud-alibaba.version>2.2.9.RELEASE</spring-cloud-alibaba.version>
<nacos-client.version>2.1.1</nacos-client.version>

开发环境使用的是本地单建的单机环境的nacos2.1.1的服务端和mysql5.7.16的数据库（这两项都使用的是docker本地部署）
使用的是windows10(64位)电脑

集成的demo验证了nacos2.1.1的在nacos管理修改主配置文件是可以热更新的

**Expected behavior**
访问http://192.168.40.31:8080/getInfo/helloWorld
可以看到我在nacos上配置的hipp4j-dev的动态数据源的message-consume线程池的核心线程参数修改后，请求控制器的这个接口会变

http://192.168.40.31:8080/getInfo/helloWorld2
这个接口是请求本地验证nacos原本的动态刷新是正常的，修改nacos上的主配置中的变量a，b的值是会变的

**Actually behavior**
A clear and concise description of what you actually to happen.
访问http://192.168.40.31:8080/getInfo/helloWorld
在nacos管理后台配置hipp4j-dev的动态数据源的message-consume线程池的核心线程参数修改后不会被刷新

问题有两个：
1.nacos2.1.1的客户端源码也看了加上打了端的调试过，发现extension-configs的拓展配置的修改不会动态刷新，只有主配置文件修改会动态刷新。
2.nacos2.1.1的客户端的这个接口nacosConfigManager.getConfigService().getConfig(dataId, group, 5000L);获取不到配置中心的配置返回的是null。

**Comment by BigBigFeiFei** [comment]
链接：https://pan.baidu.com/s/1lhurLomC4Kybac2DyLdLlg 
提取码：nrg4
上面提的那个有些格式问题，这个是demo的分享地址

**Comment by KomachiSion** [comment]
问题1: 请转到spring cloud alibaba社区。
问题2: namespaceId, group, dataId的值都是正确的吗？ 如果都是正确的，服务端有这个配置吗？

**Comment by BigBigFeiFei** [comment]
配置是对的，服务端也有这个配置的

**Comment by BigBigFeiFei** [comment]
![image](https://user-images.githubusercontent.com/35337873/226274352-31374af8-522b-4545-b4af-f9fd62a449c2.png)

**Comment by BigBigFeiFei** [comment]
上面的demo的yml配置如下,主配置是可以热更新的：
![image](https://user-images.githubusercontent.com/35337873/226282685-61081ebb-1c3f-4b06-834a-50777a333acc.png)
但是extension-configs配置不会更新

**Comment by BigBigFeiFei** [comment]
我在使用hippo4j实现动态线程池的时候，使用如下版本：
springBoot版本：2.3.12.RELEASE
spring-cloud版本：Hoxton.SR12
spring-cloud-alibaba版本：2.2.9.RELEASE
nacos的服务端和客户端2.1.1
hippo4j-config-spring-boot-starter版本：1.4.3-upgrade
发现修改nacos的了拓展配置或者是共享配置不会热更新触发hippo4j的动态刷新的监听器的原因已经找到了：
1.是spring-cloud-alibaba版本：2.2.9.RELEASE的nacos的动态刷新注册监听器的时候是以匿名内部类的方式，由于这个版本导致1.4.3-upgrade的NacosCloudRefresherHandler类装配afterPropertiesSet()方法中添加它自己的监听器失效，从而导致更改了扩展配置的动态线程池的配置也无效
2.spring-cloud-alibaba版本：2.2.9.RELEASE存在的问题确实是修改扩展配置和共享配置不会热更新，这个问题是否是这个版本的bug还是这个版本不支持这两种配置的热更新？

想要在上面这几个版本下使用hippo4j依赖nacos2.1.1实现动态线程池需要修改
com.alibaba.cloud.nacos.refresh下的NacosCloudRefresherHandler在注册nacosCloud注册匿名监听类的监听器里面找到hippo4j的data-id和group配置然后去触发hippo4j的动态刷新的逻辑，前提是将之前配置hippo4j在nacos的扩展配置的配置放到nacos上项目的主配置，这样就可以愉快的使用hippo4j了

**Comment by KomachiSion** [comment]
问题1，麻烦转到spring cloud alibaba 社区。

这里只处理问题2: `nacosConfigManager.getConfigService().getConfig(dataId, group, 5000L)`

如果地址正确，namespaceId，group和dataId正确， 且服务端能够确认存在这个配置，那只有请求超时或者请求失败才会返回null，这个时候应该日志里有信息，可以看下业务日志里是否有对应错误日志， 或者到${user.home}/logs/nacos/config.log看下有无对应查询配置的日志。

**Comment by BigBigFeiFei** [comment]
![image](https://user-images.githubusercontent.com/35337873/226774756-8b514f92-f837-4e28-bd65-949d3b09be43.png)
![image](https://user-images.githubusercontent.com/35337873/226774794-774268b5-960e-4e40-9226-09cf0f01c620.png)
上面的图是nacos-server的日志和nacos的配置

**Comment by BigBigFeiFei** [comment]
demo第一启动拉取是null的主配置的变更后可以拉取到，但是配置成扩展配置或者是共享配置第一次和后面修改扩展配置和共享配置都拉取不到的（getConfig接口）

**Comment by BigBigFeiFei** [comment]
demo第一启动拉取是null的主配置的变更后可以拉取到，但是配置成扩展配置或者是共享配置第一次和后面修改扩展配置和共享配置都拉取不到的（getConfig接口）

**Comment by BigBigFeiFei** [comment]
hippo4j实现动态线程池的demo教程分享：
https://mp.weixin.qq.com/s/yHfo8SSsi5k95Y9YLqPgng

**Comment by BigBigFeiFei** [comment]
![image](https://user-images.githubusercontent.com/35337873/227075759-b929bd86-8546-4d5e-9087-cdd5adbcb606.png)
![image](https://user-images.githubusercontent.com/35337873/227075852-ab82dd23-661f-4299-867d-98d1db6a6907.png)
![image](https://user-images.githubusercontent.com/35337873/227075628-471c4a21-a478-4c9e-a1e8-abc77b013097.png)
大佬这个 String dataId = ((ConfigPublishRequest) request).getGroup();是不是取错了？复制粘贴的时候对应关系没有改对么？

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/227859419-07a2c5ed-ad61-4bca-b7b7-6f754d7cfd70.png)

配置查找的是xxx.yaml, 存在nacos的配置是xxx 名字就对不上，not found很正常。

> 问题1，麻烦转到spring cloud alibaba 社区。
> 
> 这里只处理问题2: `nacosConfigManager.getConfigService().getConfig(dataId, group, 5000L)`
> 
> 如果地址正确，namespaceId，group和dataId正确， 且服务端能够确认存在这个配置，那只有请求超时或者请求失败才会返回null，这个时候应该日志里有信息，可以看下业务日志里是否有对应错误日志， 或者到${user.home}/logs/nacos/config.log看下有无对应查询配置的日志。

所以之前让你确认dataid是不是一致。

**Comment by KomachiSion** [comment]
spring cloud会根据`config-file-type`自动帮你补全配置dataId， 所以你要在nacos中发布xxx.yaml的配置才行， 缺了`yaml`后缀， nacos认为你要找的xxx.yaml不存在，所以就获取不到你想要的配置了。
