### ISSUE TITLE
请问dockerhub上发布nacos镜像是官方维护的么？

### ISSUE THREAD

**Issue by youngcle** [alibaba/nacos#10157]
请问dockerhub上发布nacos镜像是官方维护的么？

社区中
nacos-group/nacos-docker中反馈了一些linux 容器中standalone模式无法启动问题，

[load derby-schema.sql error](https://github.com/nacos-group/nacos-docker/issues/317)

[从docker hub拉取的镜像在单例模试下运行报错，弄不懂发生了什么，我什么都没改。](https://github.com/nacos-group/nacos-docker/issues/287)

这问题在我本人ubuntu这里从版本2.1后，持续到最新的2.2.1，

在windows docker desktop环境下没有这问题。

不知这里是否能有些官方指导。

thx

**Comment by Accelerator96** [comment]
#9742 可以参考这个issue下面的方法

**Comment by youngcle** [comment]
> #9742 可以参考这个issue下面的方法

我刚测试通过，才看到您的回复，
感谢指点
