### ISSUE TITLE
Does nacos have an official python package?

### ISSUE THREAD

**Issue by Chise1** [alibaba/nacos#10151]
I have only found Nacos-Group users providing the python package for nacos, but it has not been updated for a long time and there is no support for new versions of nacos.
只找到一个nacos-group的在提供nacos的python包，但是看起来不像是官方的组织，python包只支持到nacos1.3x，并且已经很久没更新了，还存在nacos的鉴权bug（多说一句：有人提交了修复的pr，但是没人合并）。

**Comment by KomachiSion** [comment]
1. nacos-group就是nacos的社区，其中的python-sdk应该是最全的python-sdk
2. 目前这个仓库的维护者可能已经不怎么参与社区，你可以进行主动贡献，成为python-sdk的committer，逐渐接管这个仓库。
