### ISSUE TITLE
nacos开启auth后token到期怎么自动续

### ISSUE THREAD

**Issue by ghairui** [alibaba/nacos#10167]
安全要求升级nacos开启auth=true，服务端、客户端都是2.0.3，客户端代码中configService中put了username、password，启动后正常get和publish，但是过了nacos.core.auth.default.token.expire.seconds默认的5小时后，就403了。
请教一下大佬，这个怎么能认程序中不报这个，没有自动续期的配置吗，现在只能是5小时重启一次客户端，就算调大过期时间也不是办法。

**Comment by KomachiSion** [comment]
当然有自动续期， 客户端内有一个线程会自动续期

SecurityProxy.login 在哪里调用。

**Comment by ghairui** [comment]
我用arthas看了，线程里没有com.alibaba.nacos.client.Worker，像是start里login了一次后，下面的scheduleWithFixedDelay没执行一样

**Comment by KomachiSion** [comment]
这就要具体排查一下你的环境了， 是不是哪里使用上有问题导致线程池被关闭了。或者定位下什么情况会导致scheduleWithFixedDelay没执行，说明一下情况，然后讨论并提交一个PR来修复这个问题。

**Comment by KomachiSion** [comment]
duplicate with #10160

**Comment by ghairui** [comment]
后来找到了，是容器部署时指定CPU核数太小或未指定，导致该线程池计算核心线程数时算的是1，导致login只执行一次，未执行后续计划。
