### ISSUE TITLE
是否可以在风险公告中也将 1.4.5 的版本号写进去？

### ISSUE THREAD

**Issue by coolbeevip** [alibaba/nacos#10161]
我看到这个[风险公告](https://nacos.io/zh-cn/blog/announcement-token-secret-key.html)说明中写了 2.2.1 ，但是好像遗漏了 1.4.5

**Comment by KomachiSion** [comment]
contribution weicome

**Comment by coolbeevip** [comment]
> contribution weicome

我没有找到 website 的仓库...

**Comment by KomachiSion** [comment]
Merged
