### ISSUE TITLE
在docker中如何使用插件功能

### ISSUE THREAD

**Issue by yangxj96** [alibaba/nacos#10166]
nacos版本2.2.1 
在docker环境中,怎么把postgresql的插件放进去并且生效,
我在本机中命令行运行nacos,可以把插件放到nacos主目录的plugins中.
在docker中我在/home/nacos创建了plugins目录并且把插件放进去,但是并没有加载插件

**Comment by 985492783** [comment]
把本地的nacos打包成docker镜像就行了，你的操作只是新增了个目录，并没有将包依赖进去
