### ISSUE TITLE
我有个k8s里面的有状态nacos集群生产环境在使用，重启nacos后等待20分钟nacos一直处于1.x mode

### ISSUE THREAD

**Issue by cwxiaoc** [alibaba/nacos#10163]
我有个k8s里面的有状态nacos集群生产环境在使用，重启nacos后等待20分钟nacos一直处于1.x mode
情况如下：
1. nacos集群是3节点，单节点资源1cpu  2g内存
2. 访问nacos的应用数量38个，双节点。共计76个client

观察 logs/naming-server.log，一直提示 upgrade check result failed

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-upgrading.html

**Comment by cwxiaoc** [comment]
原因可以分享下吗？

**Comment by KomachiSion** [comment]
双写模式是为了升级时做的兼容状态， 运行稳定后要关闭双写，关闭集群从1.X启动的情况。

如果集群已经升级完成，不关闭双写，重启节点会导致其他节点运行在2.X， 新重启节点运行在1.X，数据就难以同步。
