### ISSUE TITLE
[Config Api help request] Is there any api get config list under certain namespace?

### ISSUE THREAD

**Issue by xiangtianyu** [alibaba/nacos#10168]
Is there any api get config list under certain namespace?
是否有api能够获取到具体命名空间下的配置列表

I can not find such api in docs, and the dashboard api is only effect when add such param '&search=accurate', it may be a bug?
我没看到文档里面有类似的接口，而且我看dashboard里面调用的接口好像只有加上'&search=accurate'参数以后才能够正常返回config列表，这似乎是bug？

**Comment by 985492783** [comment]
不是bug,带参数show=all的v1接口直接使用只能获取到某个具体的文件的内容，详情可以看[nacos官方文档1.x-OpenAPI](https://nacos.io/zh-cn/docs/open-api.html)
查询接口提供了两种search=accurate精确查询和search=blur模糊查询的功能，如果你想要查询具体命名空间下的配置列表，指定tenant参数就可以，确实文档还没有

**Comment by xiangtianyu** [comment]
> 不是bug,带参数show=all的v1接口直接使用只能获取到某个具体的文件的内容，详情可以看[nacos官方文档1.x-OpenAPI](https://nacos.io/zh-cn/docs/open-api.html) 查询接口提供了两种search=accurate精确查询和search=blur模糊查询的功能，如果你想要查询具体命名空间下的配置列表，指定tenant参数就可以，确实文档还没有

连token都不加也能返回这个也不是bug吗？

**Comment by 985492783** [comment]
> > 不是bug,带参数show=all的v1接口直接使用只能获取到某个具体的文件的内容，详情可以看[nacos官方文档1.x-OpenAPI](https://nacos.io/zh-cn/docs/open-api.html) 查询接口提供了两种search=accurate精确查询和search=blur模糊查询的功能，如果你想要查询具体命名空间下的配置列表，指定tenant参数就可以，确实文档还没有
> 
> 连token都不加也能返回这个也不是bug吗？

2.2.1版本后nacos.core.auth.enabled默认为false不开启鉴权，如果需要开启鉴权可以查看官网文档具体操作[官网文档-鉴权](https://nacos.io/zh-cn/docs/v2/guide/user/auth.html)
不知道能不能解决你的问题
