### ISSUE TITLE
nacos中data文件夹有路径配置项么

### ISSUE THREAD

**Issue by yugezuishuai** [alibaba/nacos#10173]
nacos中data文件夹能自定义路径么

**Comment by yugezuishuai** [comment]
nacos中data文件夹有路径配置项么

**Comment by 985492783** [comment]
![image](https://user-images.githubusercontent.com/73023513/227157845-51093890-3475-42d0-b0d3-2b29ed686cf7.png)
打包的时候修改下这个试试

**Comment by KomachiSion** [comment]
目前不能改，什么原因需要改这个？

**Comment by yugezuishuai** [comment]
> 目前不能改，什么原因需要改这个？
