### ISSUE TITLE
spring boot admin 无法获取nacos服务(2022.0.0-RC)

### ISSUE THREAD

**Issue by karl-chanel** [alibaba/nacos#10172]
spring cloud alibaba 2022RC 版本，spring boot admin无法获取注册到nacos的服务，切换到2021版可以获取

**Comment by MentosL** [comment]
您好  方便提供一下demo嘛  我也可以帮忙看下

**Comment by karl-chanel** [comment]
spring boot 3. 0    spring cloud alibaba 2022    nacos 2.2.0 
你可以自己去试一下,服务可以正常的注册到nacos,spring boot admin server也可以正常注册到nacos,但是他无法从nacos获取服务并显示他们的信息,我一直以为是我自己配置有什么错误然后检查一遍又一遍，看了好多文章，最后直接将spring boot 降到的 2.6.11 ，也就是spring boot  admin server 从3.0.0讲到2.6.8后，可以从nacos中获取到服务，eureka应该不会有这种情况，spring bootadmin 官方就用的eureka做的demo,应该是nacos这边的问题

**Comment by KomachiSion** [comment]
肯定是spring那边的适配问题啊， 你用原生的nacos-client（不用spring boot）看能不能获取？

**Comment by KomachiSion** [comment]
建议把issue 提交到spring cloud alibaba 社区排查。

**Comment by karl-chanel** [comment]
应该是springbootadmin的问题这是那边的issue连接[issue2201](https://github.com/codecentric/spring-boot-admin/issues/2201)
