### ISSUE TITLE
在开启认证的情况下能否不通过session验证用户名

### ISSUE THREAD

**Issue by Accelerator96** [alibaba/nacos#10176]
因为Nacos默认鉴权，主要是为防止业务错用的弱鉴权体系，不是防止恶意攻击的强鉴权体系。需要更复杂的也可以自己去通过spi实现

有时候也会有需要通过http请求的方式去调用修改密码的接口

通过accesstoken来验证会简单些，也会少很多因为session引起的问题

并且应用是无状态的情况下对云原生支持会比较好些

发现很多issue都是这个相关的问题
#10169 #9109 #8107

**Comment by MentosL** [comment]
提交增加 accessToken获取用户信息的方式，来处理当前登录校验  #10200
