### ISSUE TITLE
在nacos Selector机制下达到保护阈值，未触发雪崩（selector信息由cmdb插件获得）

### ISSUE THREAD

**Issue by LLLWD** [alibaba/nacos#10178]
**Describe the bug**
在nacos Selector机制下达到保护阈值，未触发雪崩（selector信息由cmdb插件获得）
1. 通过cmdb获取到ip以及label信息，格式是这样的(对ip进行了处理)
ip : 1.1.1.9
az: sg9
ip : 1.1.1.19
az: sg9
ip: 2.2.2.10
az: sg10
ip: 2.2.2.20
az: sg10
ip: 2.2.2.30
az: sg10
ip: 2.2.2.40
az: sg10

2. 同时用脚本向nacos进行服务注册

#!/bin/bash
for((i=1;i<=10000;i++));
do
curl -X POST 'http://ip:port/nacos/v1/ns/instance?port=8848&healthy=true&ip=1.1.1.9&weight=1.0&serviceName=test'
curl -X POST 'http://ip:port/nacos/v1/ns/instance?port=8848&healthy=false&ip=1.1.1.19&weight=1.0&serviceName=test'
curl -X POST 'http://ip:port/nacos/v1/ns/instance?port=8848&healthy=true&ip=2.2.2.10&weight=1.0&serviceName=test'
curl -X POST 'http://ip:port/nacos/v1/ns/instance?port=8848&healthy=true&ip=2.2.2.20&weight=1.0&serviceName=test'
curl -X POST 'http://ip:port/nacos/v1/ns/instance?port=8848&healthy=true&ip=2.2.2.30&weight=1.0&serviceName=test'
curl -X POST 'http://ip:port/nacos/v1/ns/instance?port=8848&healthy=false&ip=2.2.2.40&weight=1.0&serviceName=test'
sleep 10s;
done

此时sg9健康比例0.5; sg10健康比例0.75；all ip健康比例0.66
![image](https://user-images.githubusercontent.com/73591531/227167686-331802a9-3809-4e8e-b845-d7717d4d1dec.png)

3. 在面板上配置保护阈值为0.7 CONSUMER.label.az=PROVIDER.label.az
3.1 模拟客户端获取serviceIp
3.1.1获取全部实例
curl -X GET 'nacosip:port/nacos/v1/ns/instance/list?serviceName=test&clientIP=3.3.3.3'
触发了雪崩保护，"reachProtectionThreshold":true。    （符合预期）
3.1.2获取sg9实例
curl -X GET 'nacosip:port/nacos/v1/ns/instance/list?serviceName=test&clientIP=1.1.1.9'
未触发雪崩保护，"reachProtectionThreshold":false。**（不符合预期）**
研究这里为什么没有触发雪崩保护时，打印了com.alibaba.nacos.naming.utils.ServiceUtil#selectInstancesWithHealthyProtection函数中的newHealthyCount 和allInstances.size()变量
newHealthyCount = 5.   （这个5我理解是未经过selector机制筛选的4台健康实例+ sg9中1台健康实例） 
allInstances.size() = 2.  (这个2我理解是sg9的机器数量）
所以5/2
`if ((float) newHealthyCount / allInstances.size() <= threshold) {} `这里面的雪崩保护没有被触发
3.1.3获取sg10实例
curl -X GET 'nacosip:port/nacos/v1/ns/instance/list?serviceName=test&clientIP=2.2.2.10'
未触发雪崩保护，"reachProtectionThreshold":false    （符合预期）
===================
3.2 将保护阈值设置为0.99 
重新模拟客户端获取sg9 sg10 all的ipList
3.2.1 all 触发保护阈值（符合预期）
3.2.2 sg9未触发保护阈值 **（不符合预期）**
newHealthyCount: 5
allInstances.size(): 2
3.2.3. sg10未触发保护阈值 **（不符合预期）**
newHealthyCount: 7
allInstances.size(): 4

5. 所以我理解这是一个bug（如果理解错误，请指教）
原代码：
long newHealthyCount = healthyCount;
if (originalTotal != allInstances.size()) {
    for (com.alibaba.nacos.api.naming.pojo.Instance allInstance : allInstances) {
        if (allInstance.isHealthy()) {
            newHealthyCount++;
        }
    }
}
======
修改后：
// long newHealthyCount = healthyCount;
long newHealthyCount = 0L;
// if (originalTotal != allInstances.size()) {
    for (com.alibaba.nacos.api.naming.pojo.Instance allInstance : allInstances) {
        if (allInstance.isHealthy()) {
            newHealthyCount++;
        }
    }
// }

6. 修改代码后重新设置保护阈值为0.7 和0.99两种情况；分别模拟all sg9 sg10 所获取的ipList，均符合预期

7. merge request 
 https://github.com/alibaba/nacos/pull/10177

**Desktop (please complete the following information):**
 - OS:Centos
 - Version nacos-server 2.2.0
 - Module naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java  & nacos-cmdb-plugin

**Comment by pixystone** [comment]
确实是有问题，PR reopen一下，我给了Review

**Comment by LLLWD** [comment]
> 确实是有问题，PR reopen一下，我给了Review

是这样重新提交一个plz merge吗（还是把close的open，第一次在开源项目上提交merge，抱歉）

**Comment by pixystone** [comment]
那个close的可以reopen的
