### ISSUE TITLE
nacos 1.4.2 multiple instances in the registration list of nacos

### ISSUE THREAD

**Issue by huzhonglu1** [alibaba/nacos#10174]
Excuse me, after the microservice restarts in k8s,in nacos 1.4.2, there will be multiple instances in the registration list of nacos, and both the deleted pod and the newly created pod are present, resulting in occasional access errors. How can I solve this problem?

**Comment by KomachiSion** [comment]
1. Do deregister before stop pod ( or in pre-stop)
2. call `updateInstance` api to set `enabled=false` before stop pod and call `updateInstance` api to set `enabled=true` after pod start

The 1.X client use heartbeat to check the pod healthy, if no deregister before stop pod, the pod will become unhealthy after 15s default and removed after 30s default.
