### ISSUE TITLE
[Add org logo] Could we add DaoCloud logo to the README file

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#10189]
For enterprise level usage, DaoCloud support Nacos as Microservices registration center and configuration center for customers. 

Could we add DaoCloud logo into README file.

**Comment by KomachiSion** [comment]
Of cource, you can add logo url to readme file by submit PR.

**Comment by wilsonwu** [comment]
> Of cource, you can add logo url to readme file by submit PR.

OK, thanks, I will do it ASAP.
