### ISSUE TITLE
SpringCloud整合nacos启动异常: Connection is unregistered

### ISSUE THREAD

**Issue by InsaneLighter** [alibaba/nacos#10186]
环境：
win10
jdk 1.8
版本：
nacos server 2.1.1
springboot 2.3.12.RELEASE
springcloud ali 2.2.9.RELEASE
springcloud Hoxton.SR12

异常描述：
服务端是本地源码构建后**单机**启动(未配置数据库)，客户端启动报错**Connection is unregistered**，服务端日志remote.log中重复出现server is over limited的警告，定位到本地服务端文件limitRule，最初启动应该是空值，但是由于个人操作limitRule文件生成了如下内容(文件删除了印象中应该是这样的)：
`{"monitorIpList":["1.1.1.1","2.2.2.2"],"countLimit":1,countLimitPerClientIpDefault:-1,countLimitPerClientIp:[]}`
countLimit为1会导致checkLimit中isOverLimit为true，只要有一个连接就报错。

问题：
1. limitRule文件什么时候会在单节点启动写入数据
2. 上面描述这种情况除了手动清空配置文件内容还有其他的解决方案吗

**Comment by KomachiSion** [comment]
可能是你在本地运行过unit test， unit test生成了这个限流规则在本地文件里， 删除掉即可。

限流插件已经在2.2.X进行重构， 2.3版本会作为社区可开发插件公开。

**Comment by InsaneLighter** [comment]
本地测试复现了问题，是执行了单元测试
