### ISSUE TITLE
DataID one-click migration

### ISSUE THREAD

**Issue by duweixing** [alibaba/nacos#1018]
## Issue Description

Can you add a migration feature to DataID?

### Describe what happened (or what feature you want)
Such as:
NameSpaceDev has a global.properties in it
I can copy it into nameSpaceTest or nameSpaceStaging with one click;
I don't know if this is going to be a huge benefit;
My English is not very good, I don't know whether I have expressed clearly. If the request function is not appropriate, please forgive me.

**Comment by nkorange** [comment]
@duweixing  Is this for configurations or services

**Comment by nkorange** [comment]
@duweixing 你可以用中文来描述你的问题。

**Comment by duweixing** [comment]
emmm,我看了半天都是英文交流的，我以为 为了国际化都用英文呐。
我其实就是问下，以后会不会加个一键迁移的功能；
比如：我有多个namespace，
namespace1,namespace2,namespace3....，
场景：
如果我在namespace1中添加了一个DataID配置，我想把这个配置复制到namespace2，和namespace4中；如果为了简便，是否会有一键迁移到指定namespace下的功能？

**Comment by nkorange** [comment]
参考 #1115 ，已经在开发了
