### ISSUE TITLE
nacos K8S部署突然挂掉无法启动，报错 Error creating bean with name 'authFilterRegistration' defined in class path resource [com/alibaba/nacos/core/auth/AuthConfig.class]

### ISSUE THREAD

**Issue by r023875206** [alibaba/nacos#10185]
<html>
<body>

2023-03-24 14:01:20,539 ERROR Startup errors :
--
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
Fri, Mar 24 2023 2:01:20 pm | at com.alibaba.nacos.Nacos.main(Nacos.java:35)
Fri, Mar 24 2023 2:01:20 pm | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Fri, Mar 24 2023 2:01:20 pm | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Fri, Mar 24 2023 2:01:20 pm | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Fri, Mar 24 2023 2:01:20 pm | at java.lang.reflect.Method.invoke(Method.java:498)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Fri, Mar 24 2023 2:01:20 pm | Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:479)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
Fri, Mar 24 2023 2:01:20 pm | ... 16 common frames omitted
Fri, Mar 24 2023 2:01:20 pm | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilterRegistration' defined in class path resource [com/alibaba/nacos/core/auth/AuthConfig.class]: Unsatisfied dependency expressed through method 'authFilterRegistration' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilter' defined in class path resource [com/alibaba/nacos/core/auth/AuthConfig.class]: Unsatisfied dependency expressed through method 'authFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authConfigs': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'NACOS_AUTH_IDENTITY_KEY' in value "${NACOS_AUTH_IDENTITY_KEY}"
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:212)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:203)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:97)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:260)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:234)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5211)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
Fri, Mar 24 2023 2:01:20 pm | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
Fri, Mar 24 2023 2:01:20 pm | at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
Fri, Mar 24 2023 2:01:20 pm | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
Fri, Mar 24 2023 2:01:20 pm | at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.StandardService.startInternal(StandardService.java:430)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
Fri, Mar 24 2023 2:01:20 pm | at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
Fri, Mar 24 2023 2:01:20 pm | ... 21 common frames omitted
Fri, Mar 24 2023 2:01:20 pm | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilter' defined in class path resource [com/alibaba/nacos/core/auth/AuthConfig.class]: Unsatisfied dependency expressed through method 'authFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authConfigs': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'NACOS_AUTH_IDENTITY_KEY' in value "${NACOS_AUTH_IDENTITY_KEY}"
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
Fri, Mar 24 2023 2:01:20 pm | ... 61 common frames omitted
Fri, Mar 24 2023 2:01:20 pm | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authConfigs': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'NACOS_AUTH_IDENTITY_KEY' in value "${NACOS_AUTH_IDENTITY_KEY}"
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
Fri, Mar 24 2023 2:01:20 pm | ... 75 common frames omitted
Fri, Mar 24 2023 2:01:20 pm | Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'NACOS_AUTH_IDENTITY_KEY' in value "${NACOS_AUTH_IDENTITY_KEY}"
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:230)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:79)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:60)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:594)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:153)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:149)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.PropertySourcesPropertyResolver.getPropertyAsRawString(PropertySourcesPropertyResolver.java:74)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:159)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1332)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
Fri, Mar 24 2023 2:01:20 pm | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
Fri, Mar 24 2023 2:01:20 pm | ... 87 common frames omitted
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,542 WARN [WatchFileCenter] start close
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,548 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/conf
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,550 WARN [WatchFileCenter] already closed
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,550 WARN [NotifyCenter] Start destroying Publisher
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,550 WARN [NotifyCenter] Destruction of the end
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,551 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,618 WARN [ThreadPoolManager] Start destroying ThreadPool
Fri, Mar 24 2023 2:01:20 pm |  
Fri, Mar 24 2023 2:01:20 pm | 2023-03-24 14:01:20,618 WARN [ThreadPoolManager] Destruction of the end

</body>
</html>

**Comment by KomachiSion** [comment]
是否镜像版本是latest， 重启导致新拉取了最新镜像，最新版本因删除了`token.scecrt.key`的默认值，需要自定义设置之后才能启动， 这部分在优化， 近期会出不开鉴权时一个不强依赖的个版本。

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/blog/announcement-token-secret-key.html
