### ISSUE TITLE
caused: Parameter conditions "search=blur" OR "search=accurate" not met for actual request parameters

### ISSUE THREAD

**Issue by clcc2019** [alibaba/nacos#10187]
**Describe the bug**

When searching in Nacos with the parameter conditions "search=blur" OR "search=accurate", the actual request parameters are not being met.

**Expected behavior**

The search should display results according to the specified search parameter.

**Actually behavior**

No results are being displayed when using the "search=blur" or "search=accurate" parameters.

**How to Reproduce**
1. Go to Nacos search bar.
2. Enter "search=blur" or "search=accurate".
3. Press enter.
4. No results are displayed.

**Desktop (please complete the following information):**
- OS: Centos
- Version: nacos-server 2.2.1, nacos-client 2.2.1
- Module: naming/config
- SDK: original

**Additional context**
This issue is occurring consistently for all users on version 2.2.1 of Nacos. Please let me know if any additional information is needed to fix this issue.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by tekintian** [comment]
I have the same problems!   with standalone mode and embedded Storage .  on the dashboard , when click the User Management -> User List menu and Role management  , it case the same problem.

use external mysql database is ok!
