### ISSUE TITLE
求助！centos7.6 使用docker安装nacos集群，提示用户名或密码错误，F12显示403

### ISSUE THREAD

**Issue by nsdsb123** [alibaba/nacos#10194]
centos7.6 使用docker安装nacos集群，提示用户名或密码错误，F12显示403，同时这台机使用docker安装的zabbix等程序登录全部显示403

**Comment by KomachiSion** [comment]
那应该是用户名密码不正确，或者zabbix等程序没有输入用户名密码。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by nsdsb123** [comment]
> No more response from author, I think this is a env problem.

后面我排查发现，是因为使用默认密码nacos/nacos登录的时候，公司的网络会拦截简单密码，导致登录不了
