### ISSUE TITLE
Failed to start dubbo service cluster

### ISSUE THREAD

**Issue by xingcun** [alibaba/nacos#1019]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
先启动一个dubbo服务提供者A，再启动一个dubbo消费者
再启动一个dubbo服务提供者B
nacos上注册成功，但集群失败。只会调用服务提供者A，不会调用服务提供者B
必须启动服务提供者A,B，再启动dubbo消费者，才集群成功

### Describe what you expected to happen
这是bug，还是说未实现的功能

### How to reproduce it (as minimally and precisely as possible)

1. <dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>2.6.6</version>
		</dependency>
2. <dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.0.0-RC2</version>

### Tell us your environment
windows 10

**Comment by nkorange** [comment]
@xingcun Dubbo客户端会监听实例列表变化的，能否把消费端日志发出来看看

**Comment by Carles1983** [comment]
先启动一个启动一个dubbo消费者（启动时设置consumer的check=false），再dubbo服务提供者。实际调用时会包provider没有启动或注册。

**Comment by nkorange** [comment]
> 先启动一个启动一个dubbo消费者（启动时设置consumer的check=false），再dubbo服务提供者。实际调用时会报provider没有启动或注册。
> com.alibaba dubbo 2.6.6
> springcloud Greenwich.RELEASE
> springboot 2.1.0.RELEASE
> springcloudAlibaba 0.2.1.RELEASE

请到Dubbo的仓库汇报这个问题。
