### ISSUE TITLE
NACOS1.4.2偶发nacos自动刷新配置为null

### ISSUE THREAD

**Issue by gaorun588** [alibaba/nacos#10192]
@Component
@Data
@RefreshScope
@ConfigurationProperties(prefix = "menu")
public class TodoConfig {

    private String systemId;

    private Map<String, String> urls;
}

线上正常运行几个月，最近出现线上问题，获取到systemId和urls均为null，导致空指针异常，排查未发现网络问题，求大佬指教，谢谢！

**Comment by KomachiSion** [comment]
看下${user.home}/logs/nacos/config.log中有没有收到最新配置。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
