### ISSUE TITLE
控制台新增Nacos自己的配置中心

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#10197]
我觉得随着插件和功能越来越多，配置项也越来越多，需要一个页面展示出nacos的哪些功能是否开启以及哪些功能点的配置，例如鉴权是否开启，数据库是Embedded or External，数据源是什么，当然都需要脱敏处理
>是只用在console中添加代码，不会影响其他模块

为什么需要
1. 功能迭代快，有可能有些功能已经有了但是用户不知道
2. 展示方便，我自己nacos-server的功能不需要翻阅源代码或者官方文档才知道哪些是关掉的
3. 方便用户纠错，例如我想打开某个功能，操作失误，但是就可以在控制台中感知到

**Comment by KomachiSion** [comment]
I think this issue can follow #10153

**Comment by KomachiSion** [comment]
From the PR, I think it has repeats and it makes complex.

Now the console has api `/state` and can return this info.

And in https://github.com/alibaba/nacos/issues/10153 we extend a `ModuleState` SPI to collect module switch to show.

I think current should reuse them.

And After we need a dynamic switch, we should has more design for this feature, which need think how to sync to cluster and how to maintain and how to show them.

**Comment by 985492783** [comment]
> From the PR, I think it has repeats and it makes complex.
> 
> Now the console has api `/state` and can return this info.
> 
> And in #10153 we extend a `ModuleState` SPI to collect module switch to show.
> 
> I think current should reuse them.
> 
> And After we need a dynamic switch, we should has more design for this feature, which need think how to sync to cluster and how to maintain and how to show them.

nice design, switch function just need to extend `states` field

I have an idea about cluster switch. What if we set the switch Config as ConfigInfo into the storage layer? Nacos-server could hold a private `ConfigInfo` about itself, and each cluster node could subscribe to the ConfigInfo-change. If it wants to changes, it would be like publishing a ConfigInfo in the cluster, and then each node would be notified the changes and do something.

**Comment by KomachiSion** [comment]
> > From the PR, I think it has repeats and it makes complex.
> > Now the console has api `/state` and can return this info.
> > And in #10153 we extend a `ModuleState` SPI to collect module switch to show.
> > I think current should reuse them.
> > And After we need a dynamic switch, we should has more design for this feature, which need think how to sync to cluster and how to maintain and how to show them.
> 
> nice design, switch function just need to extend `states` field
> 
> I have an idea about cluster switch. What if we set the switch Config as ConfigInfo into the storage layer? Nacos-server could hold a private `ConfigInfo` about itself, and each cluster node could subscribe to the ConfigInfo-change. If it wants to changes, it would be like publishing a ConfigInfo in the cluster, and then each node would be notified the changes and do something.

The switches save into storage, you should consider the storage is center or cluster.

Such as, storage in `database` will cause the naming module depend `database` force.
If storage in `jraft`, still cause config depend `jraft` force.

So if you want to design a dynamic switch Config for nacos self. You should consider how the switches synced and saved.

**Comment by 985492783** [comment]
i will improve state first, what about do some state-description to reduce developer usage costs
And i prefer to put switchState realize in plugin module and then replace originalState
