### ISSUE TITLE
[Bug] Some logo images are broken, let's remove them and replace as text

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#10196]
Some logo images are broken in repo home README file, let's remove them and replace as text.

**Comment by KomachiSion** [comment]
There is need to discuss how to solve these logo, not directly remove them.

**Comment by wilsonwu** [comment]
replace them to text, and I found some of them already dead.

**Comment by wilsonwu** [comment]
Currently these logo images broken:
美菜, 松格科技, 集萃智能, 吾享, 拓深科技, 郑州山水, 长亮科技, 深圳易停车库, 武汉日创科技, 易管智能, 云帐房, 知氏教育, 三诺生物
In PR: #10198 
Anyone can provide worked image please comment here.

**Comment by KomachiSion** [comment]
看下能否找到新的logo替换下，如果公司已经注销了的话可以删除。

**Comment by wilsonwu** [comment]
先找一批：
美菜，貌似不是个长期链接，先凑合用吧：https://www.meicai.cn/img/logo.9210b6eb.jpg
松格科技，实在找不到网站：https://img5.tianyancha.com/logo/lll/3aad34039972b57e70874df8c919ae8b.png@!f_200x200
集萃智能：https://www.jsic-tech.com/Public/uploads/20191206/5de9b9baac696.jpg
吾享：https://www.wuuxiang.com/theme/images/common/logo1.png
拓深科技：http://www.tpson.cn/static/upload/image/20230111/1673427385140440.png

**Comment by wilsonwu** [comment]
以上是目前找到的logo，实在找不到的会将图片移除，将名字写在最后。
