### ISSUE TITLE
求助 ，重启nacos导致业务故障

### ISSUE THREAD

**Issue by romanticmj** [alibaba/nacos#10209]
背景：线上使用nacos作为注册中心，由三个节点组成的集群
现象：重启其中一个非leader的nacos节点时，部分服务出现了报错，报错内容是从namingservice查到的示例列表为空
请问什么时候会向业务服务推送空的实例列表
日志记录：
从metric中记录的ipcount可以看出来，未被重启的一台nacos的ipcount指标有明显的下降
<img width="821" alt="image" src="https://user-images.githubusercontent.com/21699352/228170023-1ae27d63-3c5e-4238-9858-dd2c2492bd03.png">
从未被重启的nacos节点的naming-push.log中，查到了部分push时候DataSize是0
naming-push.log.2023-03-27.0:2023-03-27 22:13:03,430 INFO [PUSH-SUCC] 79ms, all delay time 625ms, SLA 624ms, Service{namespace='public', group='DEFAULT_GROUP', name='myservice', ephemeral=true, revision=8}, DataSize=0, target=192.168.1.1
naming-push.log.2023-03-27.0:2023-03-27 22:13:03,430 INFO [PUSH-SUCC] 79ms, all delay time 625ms, SLA 624ms, Service{namespace='public', group='DEFAULT_GROUP', name='myservice', ephemeral=true, revision=8}, DataSize=0, target=192.168.1.2
naming-push.log.2023-03-27.0:2023-03-27 22:13:03,430 INFO [PUSH-SUCC] 79ms, all delay time 625ms, SLA 624ms, Service{namespace='public', group='DEFAULT_GROUP', name='myservice', ephemeral=true, revision=8}, DataSize=0, target=192.168.1.3
naming-push.log.2023-03-27.0:2023-03-27 22:13:03,433 INFO [PUSH-SUCC] 82ms, all delay time 628ms, SLA 627ms, Service{namespace='public', group='DEFAULT_GROUP', name='myservice', ephemeral=true, revision=8}, DataSize=0, target=192.168.1.4

**Comment by KomachiSion** [comment]
可以看naming-server.log 和naming-event,log 看下这个服务被移除的原因。

另外可以考虑开启客户端的推空保护功能，反之异常情况导致的空列表情况。

**Comment by romanticmj** [comment]
好的，从故障期间的naming-server.log和naming-event.log里都没有找到这个服务被移除的原因
> 我们业务服务是通过域名连接的nacos，假如 ABC是三个nacos节点，重启的是A
> 推测是过程是
> 业务服务x的所有节点通过域名与A建立channel（都是临时节点），这时A下线
> BC长时间没有收到x的心跳，认为已下线，开始进行移除操作，将x的所有节点移除，并向其他订阅的业务服务推送空列表导致的
> 目前计划在nacos服务端补充一些grpc的打点日志来定位复现下

查阅[阿里云文档](https://help.aliyun.com/document_detail/453374.html)，写的可以服务端配置推空保护，我们现在使用的2.0.3版本，好像是没有这个功能，拉了最新的2.2.1也没有看到，这个是没有开源出来是么？
那我们这边只能在客户端增加推空保护nacos.discovery.namingPushEmptyProtection=true，然后重启所有客户端服务是么？

**Comment by KomachiSion** [comment]
> 好的，从故障期间的naming-server.log和naming-event.log里都没有找到这个服务被移除的原因
> 
> > 我们业务服务是通过域名连接的nacos，假如 ABC是三个nacos节点，重启的是A
> > 推测是过程是
> > 业务服务x的所有节点通过域名与A建立channel（都是临时节点），这时A下线
> > BC长时间没有收到x的心跳，认为已下线，开始进行移除操作，将x的所有节点移除，并向其他订阅的业务服务推送空列表导致的
> > 目前计划在nacos服务端补充一些grpc的打点日志来定位复现下
> 
> 查阅[阿里云文档](https://help.aliyun.com/document_detail/453374.html)，写的可以服务端配置推空保护，我们现在使用的2.0.3版本，好像是没有这个功能，拉了最新的2.2.1也没有看到，这个是没有开源出来是么？ 那我们这边只能在客户端增加推空保护nacos.discovery.namingPushEmptyProtection=true，然后重启所有客户端服务是么？

那个是服务端的推空保护是阿里云的商业版本自己加的， 社区版本没有。

社区版本需要在客户端进行开启，nacos.discovery.namingPushEmptyProtection=true。 因为只有实际使用方才知道是不是需要进行保护。

**Comment by KomachiSion** [comment]
主要还是想排查出为什么会下跌，看日志像是2.0以上的版本。  我记得以前修复一个续约相关的问题。具体issue找不到了。

主要是用1.x客户端的时候， 心跳续约的信息没有通过同步进行传递到其他节点， 如果责任节点发生切换（比如重启某个节点或者断网），有一部分实例在切换后会因为心跳过期移除，然后再从客户端补偿回来。

这个问题在2.x的某个版本修复了， 心跳信息会从distro协议的`verify`操作中同步过去。反之我这边做过很多这种重启的操作，暂时还没在新版本发现其余节点实例数下跌的情况，除非是那个时候正好有业务发布或者连接断开了。

**Comment by KomachiSion** [comment]
> 主要还是想排查出为什么会下跌，看日志像是2.0以上的版本。 我记得以前修复一个续约相关的问题。具体issue找不到了。
> 
> 主要是用1.x客户端的时候， 心跳续约的信息没有通过同步进行传递到其他节点， 如果责任节点发生切换（比如重启某个节点或者断网），有一部分实例在切换后会因为心跳过期移除，然后再从客户端补偿回来。
> 
> 这个问题在2.x的某个版本修复了， 心跳信息会从distro协议的`verify`操作中同步过去。反之我这边做过很多这种重启的操作，暂时还没在新版本发现其余节点实例数下跌的情况，除非是那个时候正好有业务发布或者连接断开了。

这时候会在naming-server中有AUTO-DELETE之类的日志。
