### ISSUE TITLE
mysql能注入nacos吗？

### ISSUE THREAD

**Issue by suozq1** [alibaba/nacos#10205]
我看了官方网，其中提到nacos支持mysql健康检查，那是否意味着可以把mysql注入nacos,但官网并没有任何相关介绍，难道我就像注入一般服务那样就行吗？那redis呢？有人知道怎么搞吗？

**Comment by KomachiSion** [comment]
1. 注册持久化服务实例（ip端口为mysql的）
2. 控制台上编辑健康检查方式为tcp（或mysql）

**Comment by KomachiSion** [comment]
> 1. 注册持久化服务实例（ip端口为mysql的）
> 2. 控制台上编辑健康检查方式为tcp（或mysql）

tcp方式只是探测端口， mysql方式会按照mysql协议进行尝试访问（不会执行sql）

**Comment by suozq1** [comment]
非常感谢，我按照你说的试了下，通过post：http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=mysql&ip=127.0.0.1&port=3306，成功进行了注册，但控制台并没有修改健康检查的地方，我修改了集群的配置，改为tcp,3306,仍无作用，保存后，服务还是会消失

**Comment by KomachiSion** [comment]
说明你注册的服务是临时的， 注册持久化的服务要加ephemeral=false

**Comment by suozq1** [comment]
> 说明你注册的服务是临时的， 注册持久化的服务要加ephemeral=false

这个确实能注入成功，那在程序中，如果使用呢？springcloud中，直接配置服务名也用不了
