### ISSUE TITLE
Optimize nacos default application.properties configuration

### ISSUE THREAD

**Issue by yuyijq** [alibaba/nacos#10206]
我们在实际运维nacos集群的时候发现几个跟默认配置相关的问题，这些问题都是碰到实际问题的时候才发现的，如果nacos默认的配置文件就能解决就更好了：
1. Nacos里的监控指标默认没有暴露
2. 我们是通过SLB访问Nacos集群，SLB需要healthcheck，默认未暴露
3. springboot tomcat新的版本里默认关闭了tomcat的mbean，导致收集不到tomcat的指标，而这些指标对于nacos集群健康状况很重要
4. nacos的tomcat access log日志量非常大，默认是按照天切割，而access log又没有按照大小切割的方式，所以最好改成每小时滚动一次。

**Comment by KomachiSion** [comment]
1. 不能默认打开，会被质疑有数据泄漏风险（即使是监控数据也是数据，安全不和你讲道理）。
2. 同理
3. 4可以提一个PR改动下。

**Comment by KomachiSion** [comment]
Closed by #10207
