### ISSUE TITLE
Optimizing code when distro is not applicable

### ISSUE THREAD

**Issue by varyuan** [alibaba/nacos#10218]
## Issue Description

In the class DistroFilter, when distroEnabled is false or run in Standalone or healthyList is empty, The request must be processed by the current server, no need to calculate distroTag

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
Whatever situation, the `distroTag` is the basic information for distro calculation, which not only in `DistroFilter`, also for `healthy check`, `beat check` and so on. So the `distroTag` must be calculate I think.

For distroEnabled is false and Standalone, the responsible has enhancement.

And healthyList is empty is exception situation, not affect the distro handle logic.

**Comment by varyuan** [comment]
> Whatever situation, the `distroTag` is the basic information for distro calculation, which not only in `DistroFilter`, also for `healthy check`, `beat check` and so on. So the `distroTag` must be calculate I think.
> 
> For distroEnabled is false and Standalone, the responsible has enhancement.
> 
> And healthyList is empty is exception situation, not affect the distro handle logic.

file change can see pr: `https://github.com/alibaba/nacos/pull/10213`

**Comment by KomachiSion** [comment]
I know the PR, I means we should discuss in issue first.

My answer is the `distroTag` should caculate.

**Comment by KomachiSion** [comment]
No more response from author, I think the enhancement is not much effect but may cause problem. So won't do it.
