### ISSUE TITLE
nacos-server-1.4.5在redhat7.8系统上修改端口无效

### ISSUE THREAD

**Issue by lyon121024** [alibaba/nacos#10217]
**Describe the bug**
nacos-server-1.4.5在redhat7.8系统上修改端口无效

**Expected behavior**
我希望将nacos-server-1.4.5的服务端口从8848改为27010

**Actually behavior**
实际上我修改了conf/application.properties中的 server.port=27010，然后用 ./bin/startup.sh -m standalone 启动，但是发现nacos-server的端口还是8848。我试了好多次。

**How to Reproduce**
1. 从github下载nacos-server-1.4.5.zip到服务器，然后unzip 
2. vim conf/application.properties , 修改server.port=27010
3. ./bin/startup.sh -m standalone  && tail -f /data/nacos/logs/start.out
4. 发现日志：nacos 1.4.5
5. Running in stand alone mode,
6. Port: 8848
7. Pid: 6000
8. 并且使用ss -lntp 也观察到nacos使用的是8848端口。且浏览器能够访问。

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.8 (Maipo)
 - Version : nacos-server-1.4.5
 - Module : config
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
The problem come from #9617.

Please modified the bin/startup.sh line 119

```
JAVA_OPT="${JAVA_OPT} --spring.config.additional-location=optional:${CUSTOM_SEARCH_LOCATIONS}"
```

to

```
JAVA_OPT="${JAVA_OPT} --spring.config.additional-location=${CUSTOM_SEARCH_LOCATIONS}"
```

**Comment by lyon121024** [comment]
thanks! It's very useful
