### ISSUE TITLE
naming grpc client 没有传递appname

### ISSUE THREAD

**Issue by wangdongyun** [alibaba/nacos#10210]
现在代码，注册中心初始化client的传递label，可以看到没有appname
~~
 Map<String, String> labels = new HashMap<>();
labels.put(RemoteConstants.LABEL_SOURCE, RemoteConstants.LABEL_SOURCE_SDK);
labels.put(RemoteConstants.LABEL_MODULE, RemoteConstants.LABEL_MODULE_NAMING);
~~

配置中心是有传递的
![image](https://user-images.githubusercontent.com/6995309/228174942-ba2d829d-a849-48cf-97b3-86c6e4658efd.png)

服务端日志统计
![image](https://user-images.githubusercontent.com/6995309/228174454-50f8e112-5614-41ca-97e5-c39fadaac696.png)

希望，注册中心客户端传递 appname 这个label！

**Comment by yuhaowin** [comment]
@i will solve it@
I want to help solve this issues.
