### ISSUE TITLE
Domain Socket support

### ISSUE THREAD

**Issue by rushwing** [alibaba/nacos#10215]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We're trying to use nacos for both local machine microservices and remote distribute microservices.
On the local machine, we had several microservices using gRPC to communicate with each other. 
We plan to implement service registry and discovery in one of the microservices.
To prevent reinventing wheels, we're trying to use nacos in standalone mode on a local machine.
For the special security concern, we're tending to use domain socket rather than listening on the port of localhost.

We're wondering whether nacos support domain socket or not? I didn't find any useful information online.

**Describe alternatives you've considered**
If it's not possible, we might consider to write a simple service registry and discovery by ourselves.

**Additional context**
Please also provide suggestions to use nacos on a local machine.
Is there any other limitations to use locally without any remote network connections?

**Comment by KomachiSion** [comment]
I think not support for now, and no plan to support in current roadmap.

I have no idea for your situation of your service registry and discovery in local and remote.

Do you want to local service discovery other local service first?

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
