### ISSUE TITLE
nacos2.2.0版本 无法获取namespace 为public的配置

### ISSUE THREAD

**Issue by liukefu2050** [alibaba/nacos#10214]
**Describe the bug**
    使用的版本信息：
        
        <spring-boot.version>3.0.4</spring-boot.version>
        
        <spring-cloud.version>2022.0.1</spring-cloud.version>
        
        <spring-framework.version>6.0.6</spring-framework.version>
        
        <spring-cloud-alibaba.version>2022.0.0.0-RC1</spring-cloud-alibaba.version>
        nacos-client 版本：nacos-client-2.2.1-RC
       nacos-server 版本：nacos2.2.0
       NacosConfigService.java 中断点调试方法：private String getConfigInner(String tenant, String dataId, String group, long timeoutMs) throws NacosException 
第184行：ConfigResponse response = worker.getServerConfig(dataId, group, tenant, timeoutMs, false);
其中tenant 传参分别为“”  时 能获取配置信息，然而tenant传参public时却返回空。

**Expected behavior**
nacos  namespace传public 和 "" 应该返回一致结果

**Actually behavior**
其中tenant 传参分别为“”  时 能获取配置信息，然而tenant传参public时却返回空。

**How to Reproduce**
![QQ图片20230329102015](https://user-images.githubusercontent.com/21030225/228409969-584bace3-2d4b-4903-88c0-bb78367181f1.png)

**Additional context**

**Comment by KomachiSion** [comment]
duplicate with #9846
