### ISSUE TITLE
Please tell me why the client chooses "grpcClientProxy" or "httpClientProxy" through the "ephemeral" attribute?

### ISSUE THREAD

**Issue by bigdou666** [alibaba/nacos#10216]
请教一下，为什么要通过“ephemeral“属性来判断使用“grpcClientProxy”或“httpClientProxy”
![image](https://user-images.githubusercontent.com/44945800/228415728-027f7327-527b-4097-934f-8604a17d6fc5.png)
![image](https://user-images.githubusercontent.com/44945800/228415787-7001a657-1020-48ac-8ba9-1dd9c0790129.png)

**Is your feature request related to a problem? Please describe.**
I think whether the instance is temporary or not has nothing to do with the request protocol.
我认为实例是否为临时的，与请求协议无关

**Comment by KomachiSion** [comment]
是的， 只是目前还没有实现注册持久化服务的grpc接口，所以暂时用的是http的注册服务接口。

**Comment by KomachiSion** [comment]
duplicate with #9981

**Comment by bigdou666** [comment]
http可以实现注册临时实例吗

**Comment by Daydreamer-ia** [comment]
> http可以实现注册临时实例吗，在客户端配置中并没有发现有关配置

可以，具体参考 `NamingHttpClientProxy`，但是 `2.x` 对临时实例的处理已经固化为 `grpc`

**Comment by bigdou666** [comment]
好的， 感谢答复
