### ISSUE TITLE
Nacos2.1.1版本，流量峰值期间和压测期间Nacos相关接口返回404

### ISSUE THREAD

**Issue by quan7u** [alibaba/nacos#10228]
**Describe the bug**
使用方式：SpringCloud业务组件通过Nginx连接到Nacos
最近在流量峰值时段，和压测期间，组件内nacos client抛出异常
![image](https://user-images.githubusercontent.com/32817309/228723002-6747c314-f698-4a48-8693-e6da595d0230.png)

排查Nginx，异常期间代理到Nacos的请求均响应404
![image](https://user-images.githubusercontent.com/32817309/228723408-7c7dfb30-bdb2-4cab-b401-8910e9fc6073.png)
上图过滤了所有404响应的access.log

最后判断异常由Nacos造成的，看nacos相关日志（日志太多，不知道看哪个。。。粗看异常时段的日志，并没有找到有用的信息

**Actually behavior**
请教下如何定位具体问题出处，目前nacos日志应该没有完全利用好

**Desktop (please complete the following information):**
 - OS: [CentOS 7.9]
 - Version [nacos-server 2.1.1, nacos-client v1.4.2]
 - Module [naming/config]
 - SDK [espring-cloud-alibaba-nacos]

**Additional context**
压测期间，nacos所在主机的TCP的InSegs、OutSegs骤减
![image](https://user-images.githubusercontent.com/32817309/228724437-2c36b6a4-386d-4fdd-8bc3-d2df9406b663.png)

Nacos监控 alert 推送失败
![image](https://user-images.githubusercontent.com/32817309/229019267-49bbf52e-3240-4a2f-9e3a-45575cb29057.png)

**Comment by drgnchan** [comment]
从ng日志来看：/nacos/v1/ns/** 正常响应；/nacos/v1/cs/** 都404。
有没有可能是，ng的配置文件中路径的正则表达式没有配置正确？建议检查下ng的配置，或者截图看看

**Comment by quan7u** [comment]
昨天压测流量不经过Nginx，没有再出现read timeout、404问题

怀疑是Nacos不能和内网流量共用负载，待验证

**Comment by KomachiSion** [comment]
404是nginx抛出的，你看错误日志里有power by nginx。

如果是nacos直接抛出的404， 不会有这个日志。你需要看你的nginx配置是不是不正确。

**Comment by quan7u** [comment]
将业务Nginx和Nacos负载Nginx隔离开进行压测，业务Nginx出现相同的错误，**排除Nacos**

upstream配置了keepalive之后，没有再出现404错误，但仍然存在错误：`connect() failed (110: Connection timed out) while connecting to upstream`、`no live upstreams while connecting to upstream`

主机负载没有压力，连接数未满，upstream指向组件运行正常，还在找问题，先关闭这个issue了。。。欢迎大家给点排查思路
