### ISSUE TITLE
【help】修改了nacos.core.auth.default.token.secret.key后，登录管理页面提示用户名密码错误

### ISSUE THREAD

**Issue by syl000** [alibaba/nacos#10221]
## Issue Description

Type: *help*

### Describe what happened (or what feature you want)

i change config:nacos.core.auth.default.token.secret.key,i can't login manage page use my password
我修改了配置中默认的token secret key，修改完成后重启服务，用以前的用户名密码无法登录管理页面了。
我的问题是正常修改这个配置会影响到登录吗？

### Describe what you expected to happen

Do I need to generate a passphrase with a new secret key?what should I do？
需要通过新的secret key生成密码吗？如何生成呢？

### How to reproduce it (as minimally and precisely as possible)

1. change config:nacos.core.auth.default.token.secret.key
2. restart sevice
3. login manange page

### Tell us your environment
Nacos 2.0.2
Running in stand alone mode, All function modules

**Comment by dbgee** [comment]
随意生成一个大于32bit 的字符串，然后base64 编码就行了

**Comment by syl000** [comment]
> 

我的问题不是如何生成secret.key，而是我修改了默认的secret.key后，管理页面无法登录了，提示用户名密码错误，所以我想了解下修改secret.key后需要根据新的secret.key生成mysql中的users.password字段吗？

**Comment by dbgee** [comment]
> > 随意生成一个大于32bit 的字符串，然后base64 编码就行了
> 
> 我的问题不是如何生成secret.key，而是我修改了默认的secret.key后，管理页面无法登录了，提示用户名密码错误，所以我想了解下修改secret.key后需要根据新的secret.key生成mysql中的users.password字段吗？

不需要的
