### ISSUE TITLE
nacos-sdk-go_v2.2.1_config_client_err_bug

### ISSUE THREAD

**Issue by IvanWhisper** [alibaba/nacos#10222]
## Issue Description
Type: *bug report* or *feature request*

+ version:  `v2.2.1`
+ bug file: `github.com/nacos-group/nacos-sdk-go/v2/clients/config_client`
+ func name: `getConfigInner`

bug: v2.2.1    this  err shloud be cacheErr, err is always !=nil   

 ```
func (client *ConfigClient) getConfigInner(param vo.ConfigParam) (content string, err error) {
	//   ...
	response, err := client.configProxy.queryConfig(param.DataId, param.Group, clientConfig.NamespaceId,
		clientConfig.TimeoutMs, false, client)
	if err != nil {
		logger.Infof("get config from server error:%v ", err)
		if clientConfig.DisableUseSnapShot {
			return "", errors.Errorf("get config from remote nacos server fail, and is not allowed to read local file, err:%v", err)
		}
		cacheContent, cacheErr := cache.ReadConfigFromFile(cacheKey, client.configCacheDir)
               // bug: v2.2.1    this  err shloud be cacheErr, err is always !=nil   
		if err != nil {
			return "", errors.Errorf("read config from both server and cache fail, err=%v", cacheErr)
		}
		return cacheContent, nil
	}
	return response.Content, nil
}
```
### Describe what happened (or what feature you want)

if nacos-server can not connect,  local file can load.
代码中错误判定使用了错误变量名字，导致没办法把本地缓存的数据返回出来

### How to reproduce it (as minimally and precisely as possible)

shloud be

```
		cacheContent, cacheErr := cache.ReadConfigFromFile(cacheKey, client.configCacheDir)
		if cacheErr  != nil {
			return "", errors.Errorf("read config from both server and cache fail, err=%v", cacheErr)
		}

```

**Comment by IvanWhisper** [comment]
![8a85f07b-ed0d-437b-9b87-b4f2a27cf8d5](https://user-images.githubusercontent.com/25240029/228515097-a5b6792f-d8f4-4635-8ece-fcc21475ba68.jpeg)

**Comment by KomachiSion** [comment]
Is it nacos-go-sdk bug? 

If so, please move issue to https://github.com/nacos-group/nacos-sdk-go

**Comment by binbin0325** [comment]
Have been solved
