### ISSUE TITLE
In the Consolse module,  can the value of  @PropertySource in the ConsoleConfig.class  be modified as "classpath:/application.properties"

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#10229]
In the Consolse module,  can the value of  @PropertySource in the ConsoleConfig.class  be modified as "classpath:/application.properties" if the funtion of nacos has no influence.

**Comment by KomachiSion** [comment]
The change maybe cause the config read from error properties file.

**Comment by KomachiSion** [comment]
No more response from author, the changes may cause more problem, so close issue first.
