### ISSUE TITLE
2.1.1版本一直报错

### ISSUE THREAD

**Issue by lululu-sir** [alibaba/nacos#10226]
【【【Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/E:/environment/nacos-server-2.1.1/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.1.1.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set】】】
我的数据库配置都是对的，一旦将spring.datasource.platform=mysql注释去掉，就会报这个错误，网上的方法均试过都无法解决

**Comment by yswang1024** [comment]
spring.sql.init.platform=mysql  试试这样

**Comment by lululu-sir** [comment]
> spring.sql.init.platform=mysql 试试这个

这个虽然不报错，但是在nacos配置列表还是取不到我数据库的配置。【Nacos started successfully in stand alone mode. use embedded storage】成功的输出是这样的，并没有读到我的数据库外部连接，请问是什么原因啊。

**Comment by KomachiSion** [comment]
spring.sql.init.platform 这个参数应该是2.2开始支持的，

之前需要用spring.datasource.platform

配置之后出现报错，说明你的数据库连不上或者没有库或者表。

查看下nacos.log 的完整报错日志或者config-fatal的报错日志。找到为什么你数据库连不上。

**Comment by wuchubuzai2018** [comment]
1、对于2.2以前的版本，如果在单机模式的启动（明确指定了standalone）的情况下，不加spring.datasource.platform=mysql参数不会报错的，因为默认会执行derby
2、如果默认没指定单机模式，则为集群cluster模式，那么未指定参数spring.datasource.platform=mysql就会报错，如果指定了spring.datasource.platform=mysql参数，但是未配置下方的JDBC参数，则也会有错误
建议检查一下

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
