### ISSUE TITLE
Chore: 配置从历史中回滚会丢失配置格式，均变为 text

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#10224]
**Describe the bug**
配置从历史中回滚会丢失配置格式，均变为 text

**Expected behavior**
配置从历史中回滚继续保留历史的配置格式

**Actually behavior**
配置从历史中回滚后配置格式均变为 text

**Additional context**
配置 beta 时也没有保留这些属性，比较麻烦。
表结构 `his_config_info` 和 `config_info_beta` 需要增加列 `type` varchar(64) DEFAULT NULL,

**Comment by CherishCai** [comment]
relate https://github.com/alibaba/nacos/issues/9823

**Comment by 985492783** [comment]
see #8800 has been fixed but not merge

**Comment by CherishCai** [comment]
Thanks, Break changes to database tables, it's better to wait for major versions to merge

**Comment by CherishCai** [comment]
duplicate relate https://github.com/alibaba/nacos/issues/8799
