### ISSUE TITLE
求助，nacos是否有服务的上线下接口api

### ISSUE THREAD

**Issue by Lctiv** [alibaba/nacos#10238]
**Is your feature request related to a problem? Please describe.**
我的业务场景需要前台页面有按钮控制服务的上线、下线，nacos是否有api调用实现服务的上线下线，达到跟nacos管理页面点击服务下线一个效果。或者有其他方式达到控制该服务无法被调用。控制方式就是我前台页面点击，调用后台的某个接口达成这样的效果。
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 985492783** [comment]
模拟控制台发送put请求就可以

**Comment by KomachiSion** [comment]
[更新实例](https://nacos.io/zh-cn/docs/v2/guide/user/open-api.html#2.3)

**Comment by Lctiv** [comment]
> 模拟控制台发送put请求就可以

请问如何获取token？为啥open api没有支持服务上下线api调用，open api里的注销服务，注销实例是服务下线的意思吗？我调用了删除服务一直提示Please unregister instance first ，调用了注销实例再删除服务仍然如此，我这边场景就是需要在自定义页面可以对服务进行上下线操作，不是在nacos管理页面，我看了控制台nacos页面需要token，这个token我代码里如何获取，谢谢，不胜感激！！！

**Comment by 985492783** [comment]
1. 用最新版本nacos关闭鉴权（我暂时不知道这个功能是否完成）
2. 用网站，postman或者其他方式以restful方式模拟发送登陆请求，需要判断token是否过期，过期重新获取

**Comment by Lctiv** [comment]
> 1. 用最新版本nacos关闭鉴权（我暂时不知道这个功能是否完成）
> 2. 用网站，postman或者其他方式以restful方式模拟发送登陆请求，需要判断token是否过期，过期重新获取

好的谢谢，明白你的意思了，模拟nacos登录获取token然后模拟控制台发送服务上下线的接口请求，也就是说nacos的open api是不直接支持服务的山下线的，没有提供该功能的API对吧？这个需求应该挺多吧，针对服务上下线的api

**Comment by yyqangular1** [comment]
@Lctiv 可以达到效果的，[更新实例](https://nacos.io/en-us/docs/open-api.html#2.3)就是实现这个功能的open API。

**Comment by Lctiv** [comment]
你好，您给出的是v2版本的api吧？
网络问题GitHub登录不是，这里请教一下 。之前一直用的V1的API，发现很多属性描述都不清晰，现项目全部改用v2的api，但是

查询服务详情接口返回报错
GET :http://localhost:8848/nacos/v2/ns/service?serviceName=model-xinanjiang


{
&nbsp; &nbsp; "timestamp": "2024-01-30T16:13:53.926+08:00",
&nbsp; &nbsp; "status": 404,
&nbsp; &nbsp; "error": "Not Found",
&nbsp; &nbsp; "path": "/nacos/v2/ns/service"
}




LiuChuang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月9日(星期二) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 求助，nacos是否有服务的上线下接口api (Issue #10238)





 
@Lctiv 可以达到效果的，更新实例就是实现这个功能的open API。
