### ISSUE TITLE
部署v2.2.1后“关于Nacos默认token.secret.key及server.identity风险说明及解决方案” 无效

### ISSUE THREAD

**Issue by jC8WbQ2cH4ymFBk** [alibaba/nacos#10233]
**Describe the bug**
I want to fix token.secret.key risk , so i upgrade nacos to v2.2.1 ,but  our security department test can still log in without password used defult SecretKey012345678901234567890123456789012345678901234567890123456789 , but  I have regenerated the JWT and Auth Token

为了解决token.secret.key 安全问题，我们升级到v2.2.1版本，并且自定义了 AUTH相关的
[root@nacos-2 nacos]# env |grep AUTH
NACOS_AUTH_IDENTITY_VALUE=eyJhbGci****************
NACOS_AUTH_TOKEN=*****************
NACOS_AUTH_ENABLE=true
NACOS_AUTH_IDENTITY_KEY=XXXXX

但公司安全部门还是可以使用默认的secret key （SecretKey012345678901234567890123456789012345678901234567890123456789）免密码登陆

**Comment by Byqin** [comment]
最新版本，只要header请求里，Host值只要为ip值就可以正常访问，但是请求的数据不是正确，比如 ：
curl -i -s -k -X 'GET' -H 'Host: 127.0.0.1'  'http://xxx.xxx.com/nacos/v1/auth/users?pageNo=1&pageSize=10' 返回的数据比实际的用户多，且密码也和实际的不一样。如果Host值改为“xxx.xxx.com”就可以正常拦截，请问这个host限制是在哪里配置呢

**Comment by jC8WbQ2cH4ymFBk** [comment]
我这边是用K8S部署的，因此限制host 访问这个比较好使用，比如ingress 或者LB ACL .

你也可以考虑前端用nginx来实现host限制

**Comment by KomachiSion** [comment]
我本地测试， 可以生效， 你需要看下是不是你自己部署的时候没有修改为新的token或者镜像版本不正确。
