### ISSUE TITLE
docker latest（2.2.1） 使用插件切换postgresql 启动一直报Failed to load driver class org.postgresql.Driver in either of HikariConfig class loader or Thread context classloader

### ISSUE THREAD

**Issue by xl-0909** [alibaba/nacos#10230]
启动一直报Failed to load driver class org.postgresql.Driver in either of HikariConfig class loader or Thread context classloader
已确认插件里面引入了驱动包 并且放到了plugins文件夹下

```properties
### Deprecated configuration property, it is recommended to use `spring.sql.init.platform` replaced.
# spring.datasource.platform=mysql
spring.sql.init.platform=postgresql

### Count of DB:
db.num=1

### Connect URL of DB:
db.url.0=jdbc:postgresql://xxxxxx/nacos?tcpKeepAlive=true&reWriteBatchedInserts=true&ApplicationName=nacos_java
db.user.0=xxxx
db.password.0=xxxx

### Connection pool configuration: hikariCP
db.pool.config.connectionTimeout=30000
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=20
db.pool.config.minimumIdle=2
db.pool.config.driverClassName=org.postgresql.Driver
```

**Comment by KomachiSion** [comment]
`Failed to load driver class org.postgresql.Driver` 加载class出现问题，要么是类不存在， 要么是类冲突。

**Comment by xl-0909** [comment]
![image](https://user-images.githubusercontent.com/30011762/229036672-34917732-3883-488c-bcad-9126bbcf61e8.png)
确认过了确实是有的
冲突的话 这个插件我自己打包的只引了一次一个版本 没有其他包了呀

**Comment by wuchubuzai2018** [comment]
1、建议先试试非Docker的环境是否可以
2、其次再试试2.2.0版本是否可以，我记得我是基于2.2.0开发的
3、其次再试试单独下载PostgreSQL,JDBC驱动包，然后删除插件包里面的pg的包类

**Comment by wuchubuzai2018** [comment]
再看看我的仓库上面其他人遇到的现在自己是否也遇到过：
https://github.com/wuchubuzai2018/nacos-datasource-extend-plugins/issues/2

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.
