### ISSUE TITLE
nacos2.2.1中，启动生产者服务时会多拉起接口服务

### ISSUE THREAD

**Issue by CoCoYuYuan** [alibaba/nacos#10248]
![image](https://user-images.githubusercontent.com/111859745/229308809-3b0abb1e-e776-4a01-aee0-c1651a36b46d.png)
这里是服务元数据 providers:com.lc.service.FeignTestService::
![image](https://user-images.githubusercontent.com/111859745/229308836-2d6dd802-ff23-4409-8df7-ed1b1db1a704.png)
这里是启动的生产者 cloud-provider-service
![image](https://user-images.githubusercontent.com/111859745/229308860-53409271-a4f3-4f0d-9ec4-0fe0d575dedd.png)

我比较困惑，为什么接口层的这个会被拉起，他不在生产者这层里面，它只是作为一个引用的存在，在生产者这层里面的确用到了FeignTestService作为接口实现层的调用，不过我不理解为什么同一服务会有多个这个。

请劳烦告知我该怎么调整

**Comment by KomachiSion** [comment]
Please move issue to dubbo, not nacos' problem.
