### ISSUE TITLE
[Feature]Front: 权限控制-权限管理-添加权限-资源可选填写任意文本

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#10240]
**Is your feature request related to a problem? Please describe.**

目前添加权限时，资源只能选取 namespace 级别作为授予，授予后也非常友好地显示为命名空间。如下图

![image](https://user-images.githubusercontent.com/16837364/229036084-d8dc12cd-d3b4-40f8-af73-1e5b487e7470.png)

![image](https://user-images.githubusercontent.com/16837364/229036234-559bcd03-20c4-4ac5-a9f5-38282a4c5f1f.png)

而如果有更细化的权限需求时，例如 group 级别，更甚 dataId 级别的细化权限。其实服务端是根据正则去判断的，故而本已支持，期望前端也允许选择去填写任意文本，例如：`[namespace]:[group]:config/dataId*` 灵活地授予权限。如下图

![image](https://user-images.githubusercontent.com/16837364/229037321-c9103d6c-c5ed-42b2-8515-edd6855268b2.png)

![image](https://user-images.githubusercontent.com/16837364/229037059-6c48ca27-fedd-459c-98a2-9043e5a6f011.png)

**Describe the solution you'd like**
服务端本已支持根据正则去判断的权限，期望前端也允许选择去填写任意文本（兼容旧逻辑），例如：`[namespace]:[group]:config/dataId*` 灵活地授予权限。

**Additional context**
我不专于前端 nodejs，仅会改为 input ，而兼容旧逻辑则改不出来，故而提此 issue 看是否有前端同学支持，谢谢

**Comment by KomachiSion** [comment]
可以自行开发鉴权插件，然后针对自己的鉴权插件去修改对应的前端功能。

社区提供的版本只提供namespace级别的资源请求。不支持跟细粒度的鉴权功能。
