### ISSUE TITLE
nacos 2.2.0 prometheus路由404

### ISSUE THREAD

**Issue by rechardwang** [alibaba/nacos#10243]
```
sh-4.2# curl http://127.0.0.1:8848/nacos/actuator/prometheus
{"timestamp":"2023-03-31T18:24:34.823+08:00","status":404,"error":"Not Found","message":"No message available","path":"/nacos/actuator/prometheus"}
```
原来使用2.0.1部署到k8s中后是有监控路由的，升级到2.2.0后就是404，官方文档中也没有说明是有改变什么吗？

**Comment by 985492783** [comment]
need to set property management.endpoints.web.exposure.include=*, prometheus default close now

**Comment by KomachiSion** [comment]
安全工程师认为默认开启会造成数据泄漏风险， 在2.1.0中默认关闭，需要手动开启。

**Comment by rechardwang** [comment]
额  我是容器化部署的  我想开启这个功能但是我在文档中并没有找到 打开他的 环境变量，手动去改配置文件也不现实，有没有相关的说明 @KomachiSion

**Comment by kybt** [comment]
我是用helm部署的，具体应该怎么修改values.yaml来打开management.endpoints.web.exposure.include=* 这个参数呢

**Comment by 985492783** [comment]
> 我是用helm部署的，具体应该怎么修改values.yaml来打开management.endpoints.web.exposure.include=* 这个参数呢

-Dmanagement.endpoints.web.exposure.include=*可行么

**Comment by zhaoge26** [comment]
> > 额 我是容器化部署的 我想开启这个功能但是我在文档中并没有找到 打开他的 环境变量，手动去改配置文件也不现实，有没有相关的说明 @KomachiSion
> 
> spring的配置读取机制是环境变量优先于文件，可以尝试设置同名环境变量key value：`management.endpoints.web.exposure.include=prometheus`

就是按照这个“spring的配置读取机制是环境变量优先于文件”，在pod里设置环境变量
要么在你的helm chart里添加个env，如果你想直接在当前改，那就sts? 加个env
- name: management.endpoints.web.exposure.include
   value: prometheus

**Comment by CharesLee** [comment]
> > > 额 我是容器化部署的 我想开启这个功能但是我在文档中并没有找到 打开他的 环境变量，手动去改配置文件也不现实，有没有相关的说明 [@KomachiSion](https://github.com/KomachiSion)
> > 
> > 
> > spring的配置读取机制是环境变量优先于文件，可以尝试设置同名环境变量key value：`management.endpoints.web.exposure.include=prometheus`
> 
> 就是按照这个“spring的配置读取机制是环境变量优先于文件”，在pod里设置环境变量 要么在你的helm chart里添加个env，如果你想直接在当前改，那就sts? 加个env
> 
> * name: management.endpoints.web.exposure.include
>   value: prometheus

请问这个问题有解决方案吗？
