### ISSUE TITLE
[讨论]Nacos naming高可用部署方案探讨

### ISSUE THREAD

**Issue by yuyijq** [alibaba/nacos#10253]
最近我们生产上的Nacos naming服务出现一些问题，我们在内部讨论了如何保障naming高可用的方案，现在想和社区的同学一起讨论一下，该方案有何问题。
先说一下背景：
1. 这里主要讨论Nacos naming
2. 我们目前仅仅使用了naming的临时Instance，所以只涉及distro protocol
3. 我们目前使用的是1.x的client，但是近期会向2.x客户端升级，所以本方案也包括2.x

这里不能附加图片，就用文字描述一下吧：
1. 客户端通过LB(nginx)访问Nacos，不通过多ip直连的方式
2. 使用nginx的一致性哈希路由算法，将对相同service的所有请求都转发到相同的Nacos节点上。比如有客户端注册service1，被哈希到Nacos node1，有客户端查询service1的实例列表，也被转发到Nacos node1。
3. 需要给Nacos实现较完善的健康检查，提供给nginx，当发现某节点不健康的时候，nginx将该节点摘除。

该方案的好处是，每个节点基本上是“单兵作战”，节点之间几乎不会相互影响(目前，我们发现Nacos节点之间相互影响，给Nacos的可用性带来很大问题)，增减节点就可以带来相应的可用性。另外， 因为一个服务的所有操作都由单个节点处理，所以基本上可以提供最好的一致性。

目前看，该方案基本是结合了1.x和2.x：
在1.x中，Nacos在DistroFilter中实现了转发，将操作转发给”责任节点“，基本上和我上面的方案类似(但Nacos未对list进行转发)。
在2.x中, Nacos没有了像1.x中那种责任节点的东西了，所以reg service和list service可能请求到不同的节点，当节点之间通信出现问题的时候，会严重的影响一致性，进而影响业务服务的可用性。

目前仅从代码上看，该方案实施应该没有什么问题，就怕还有什么隐藏的细节问题，欢迎大家探讨。谢谢

另外，实施该方案也需要对Nacos进行一些改造：
1. 如果使用1.x，需要将service name放到所有URL上(针对service的请求，不针对service的请求不用放)，或者放到请求的http header里(不过阿里云的ALB不支持根据http header路由)
2. 如果使用的是2.x，则使用的是gRPC，处理起来较为麻烦，不过也有办法，我已经本地验证过
3. 给Nacos实现较为完善的健康检查。

**Comment by yuyijq** [comment]
UPDATE: 发现这个方案在2.x里是不work的
2.x的gRPC连接开始建立的时候，会发一个ConnectionSetupRequest，然后server端内存里会记录connectionId:connection。但是ConnectionSetupRequest里并没有service name。
也就是2.x的gRPC的连接是有状态的...

**Comment by KomachiSion** [comment]
没看懂。

LB(nginx)使用tcp转发9848. grpc链接在哪个节点，所有数据就都在哪个节点上， 其他节点只接收这条链接的同步信息， 链接出问题会自动重连。

distro 转发在2.x中也存在，主要是兼容1.x的客户端。 责任节点计算换成了IP：port， 防止部分服务实例过多导致负载不均衡。

**Comment by KomachiSion** [comment]
No more response from author, I think this problem is author's misunderstanding.
