### ISSUE TITLE
Instance metadata在nacos不同节点不一致

### ISSUE THREAD

**Issue by yuyijq** [alibaba/nacos#10259]
今天发现一个临时Instance的metadata在Nacos server不同节点不一致的问题
这个metadata是通过NacosNamingMaintainService的updateInstance写入的，最后发现其中有两个Nacos server node有这个元数据，有一个节点没有。
看服务端代码，这个是通过jraft作一致性保证的，通过集群状态也没发现集群有什么异常，查了和raft相关的一些日志，也未发现有什么异常，有两个节点有这个元数据，那理论上raft应该是commit了的。另外，这个数据已经个把小时了，仍然不一致。
重启可能会恢复，但是为了查问题，暂时还没有对节点进行重启。

不知道能不能提供点线索可以定位具体问题。

使用的Nacos是官方下载的 2.1.2 jar包运行，使用的配置文件也是官方的。

**Comment by yuyijq** [comment]
UPDATE: 看了下日志，大概在3月19号，这个不一致的节点的raft好像就已经不work了，但是我们好像并没有什么检查机制能发现这一点。
Nacos console上 集群管理->节点列表里也没有表现出任何异常

**Comment by yuyijq** [comment]
UPDATE: 没找到什么线索后，将有问题节点重启，重启后状态变成一致的了。
目前对jraft不太熟悉，还不清楚这是啥问题导致的。
感觉nacos这边最好有个status或者metrics，可以发现raft有问题的情况..

**Comment by yuyijq** [comment]
UPDATE: 看起来是jraft的什么bug，我去jraft社区咨询一下

**Comment by wuwen5** [comment]
+1

**Comment by yuyijq** [comment]
这个问题查清楚了，具体的排查详情参见：https://github.com/sofastack/sofa-jraft/issues/952

这个问题的根本原因是： https://github.com/alibaba/nacos/issues/10291

所以我把这个issue关闭，然后在 #10291 里跟踪
谢谢
