### ISSUE TITLE
2.2.1启动报错

### ISSUE THREAD

**Issue by Ambitionyzh** [alibaba/nacos#10269]
Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set。
经排查是
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
默认数据库名是nacos，而建表时默认数据库名为nacos_config，改成一致就可以了。

**Comment by Ambitionyzh** [comment]
还是挺坑的，既然都是默认配置为啥不搞成一样的呢，我这个小菜鸡查资料看了半天，还好我之前启动过低版本的nacos有对应的配置文件发现问题了。。

**Comment by KomachiSion** [comment]
我没找到那里有写默认创建的数据库名加`nacos_config`。

提供的默认SQL 只有表名，没有库名。

**Comment by Ambitionyzh** [comment]
![Uploading P30406-155015.jpg…]()
最上面有一个库名的。

**Comment by Ambitionyzh** [comment]
/*   数据库全名 = nacos_config   */
/*   表名称 = config_info   */，每一个建表上面都有这样的注释，感觉有一定误解。

**Comment by KomachiSion** [comment]
可能是导出文件的同学自己的数据库是设置叫这个名字的， 可以提个PR修复一下。消除误解。

**Comment by Ambitionyzh** [comment]
本来想了两种方案，一种是删除注释，一种是修改默认数据库连接配置。有一位同学已经先提了第一种方案，大佬看下这两种方案采纳哪个。

**Comment by KomachiSion** [comment]
移除无效注释影响肯定更小。

**Comment by Ambitionyzh** [comment]
这位王同学是项目维护人员么？用他的pr就可以了吧？虽然我也很想提一个pr，毕竟这是我这个小菜鸡第一次提issue😂，还是感谢大佬的回复。

**Comment by KomachiSion** [comment]
> 

不是，也是社区同学。

**Comment by KomachiSion** [comment]
> 这位王同学是项目维护人员么？用他的pr就可以了吧？虽然我也很想提一个pr，毕竟这是我这个小菜鸡第一次提issue😂，还是感谢大佬的回复。

想要PR的话， 社区有很多contribute welcome的issue， 可以选择几个尝试一下。
