### ISSUE TITLE
 Are there any plans to support Oracle

### ISSUE THREAD

**Issue by Yogurt-lei** [alibaba/nacos#1027]
## Are there any plans to support Oracle

Are there any plans to support other database ? e.g. Oracle, sql server ?

**Comment by paderlol** [comment]
We will support the follow-up plan

**Comment by nkorange** [comment]
#534 is related to this issue.

**Comment by shinji3887** [comment]
已经9月份了，何时可以支持oracle？

**Comment by nkorange** [comment]
We are considering totally remove the MySQL dependency so users don't have to configure any database. 

Closing this issue because we probably won't support Oracle in the future.
