### ISSUE TITLE
nacos开启认证模式，客户端无法拉取nacos上的配置

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#10275]
因为安全扫描nacos有漏洞，所以开启nacos的认证模式。
nacos.core.auth.enabled=true
nacos.core.auth.system.type=nacos

因为之前测试过，用spring-cloud-starter-alibaba-nacos-config好像dataid必须要和服务名一致，觉得不方便所以一直用nacos-config-spring-boot-starter-0.2.1。

0.2.1版本nacos.config没有username和password的配置选项，所以打算升级到0.2.12版本，但该版本无法拉取配置(没有任何报错)。

0.2.9版本开始用2.0的client，也是因为grpc的问题引起吗？请问该如何解决？

nacos：2.0.0
springboot：2.1.4.RELEASE

 <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.12</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

 <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.0.2</version>
        </dependency>

**Comment by system51** [comment]
加上这个参数试试
NACOS_AUTH_TOKEN = 32位字符串（转换成base64位编码）

**Comment by KomachiSion** [comment]
看下${user.home}/logs/nacos/config.log

另外可能是spring boot的版本过低，虽然拉到了配置，但是spring boot的版本没有适配导致没有刷新到应用中。

**Comment by saiyujs** [comment]
nacos.log没什么异常的日志
![image](https://user-images.githubusercontent.com/62423061/230315229-7b8a282c-6291-4c03-abed-3bacd519f388.png)


密钥也使用官方建议的
![image](https://user-images.githubusercontent.com/62423061/230315010-6728b4ad-f07b-4fe7-abe6-225946d3e01f.png)

springboot版本试过提高到2.2.6和2.4.9
2.2.6测试结果和2.1.4一致
2.4.9启动有错误日志，已经有配置username和password
![image](https://user-images.githubusercontent.com/62423061/230315643-be0898ec-2f9b-4d5f-8ea3-e82a66b6aa3d.png)

**Comment by lixiongliang** [comment]
nacos.core.auth.enabled
nacos.core.auth.server.identity.key
nacos.core.auth.server.identity.value
这几个配置改了没有

**Comment by saiyujs** [comment]
nacos.config.server-addr
nacos.config.username
nacos.config.password

config的相关配置必须要放在bootstrap，不能放在application。。。
不太懂这样设计的理由
