### ISSUE TITLE
caused: Parameter conditions "search=blur" OR "search=accurate"

### ISSUE THREAD

**Issue by system51** [alibaba/nacos#10274]
**Describe the bug**
An error occurs on the access control page

![image](https://user-images.githubusercontent.com/26198108/230293182-f4b518df-a3b8-4c0b-935e-efe3b9000dd3.png)

**Expected behavior**

**How to Reproduce**
upgrade v2.2.0.1

**Comment by KomachiSion** [comment]
I use 2.2.1 version test. It works well.

Please clean cache of browser and retry.

**Comment by system51** [comment]
It's a caching problem
