### ISSUE TITLE
公网IP无法注册到nacos，请问怎么解决

### ISSUE THREAD

**Issue by onexuan** [alibaba/nacos#10287]
环境 nacos 2.1.1

比如：nacos 公网IP：1.1.1.1 内网IP：172.168.0.10 端口：8848

由于业务需要，nacos和A微服务同一个云服务地区，B微服务在另一云服务地区

A微服务配置用内网IP可以注册到nacos
nacos.server.ip=172.168.0.99
nacos.config.server-addr=192.168.0.10:8848
nacos.discovery.server-addr=192.168.0.10:8848

B微服务用公网IP无法注册到nacos
nacos.server.ip=2.2.2.2 公网IP
nacos.config.server-addr=1.1.1.1:8848
nacos.discovery.server-addr=1.1.1.1:8848

用nv -c XXX.XXX.XXX 端口，A和B互相通的

**Comment by KomachiSion** [comment]
这和nacos没什么关系，应该是网络设置的环境问题。

内网能访问说明nacos的进程是正确的。

**Comment by wilsonwu** [comment]
大概率是你的公网IP有防火墙或进出规则之类的设置，请检查一下相关配置。
