### ISSUE TITLE
Nacos use a database presence configuration, and the console service list page cannot query the data

### ISSUE THREAD

**Issue by imxiongying** [alibaba/nacos#1028]
## Issue Description

version is 0.8.0

Type: *bug report* 

### Describe what happened (or what feature you want)
When I use the database configuration, the end service can register to nacos, but the console service list page can not find the data, using `nacos/v1/ns/instances` can query the registered service data.

### Describe what you expected to happen

Data can be found on the console service list page

**Comment by nkorange** [comment]
@imxiongying Paste your code and the screenshot of Nacos console please.

**Comment by nkorange** [comment]
Close due to no feedback from user.
