### ISSUE TITLE
nacos2.0.3 ,本地开一个服务实例，线上一个服务实例，关闭本地服务实例，超过30秒也不自动下线

### ISSUE THREAD

**Issue by hupujrsgit** [alibaba/nacos#10289]
nacos2.0.3 ,本地开一个服务实例，线上一个服务实例，关闭本地服务实例，超过30秒也不自动下线
我的操作是 在本地开一个服务实例，线上开一个服务实例，两个都注册上nacos了，但是我正常关闭本地的服务实例，nacos 过了30秒后，我本地服务实例还是健康状态，不自动修改状态并且进行自动下线。 这里下线是因为我手动进行点击下线了
![image](https://user-images.githubusercontent.com/57165757/230702702-815b44c0-ab48-46b0-b467-2a6f98bc0bfb.png)
![image](https://user-images.githubusercontent.com/57165757/230702718-96ea5f17-138f-4311-8e03-97ff84e570d8.png)

**Comment by KomachiSion** [comment]
1. 确认是否还有心跳在发送。
2. 确认下nacos服务端是否有问题，心跳检测是否打开。

**Comment by hupujrsgit** [comment]
> 1. 确认是否还有心跳在发送。
> 2. 确认下nacos服务端是否有问题，心跳检测是否打开。

在哪里查看是否心跳还在发送， 和查看心跳检测是否打开

**Comment by KomachiSion** [comment]
1. 抓包或者改变naming-event.log的日志级别
2. curl -X GET '127.0.0.1:8848/nacos/v1/ns/operator/switches' 中有一个类似healthCheckEnabled的开关。
3. 看下protocol-distro.log和naming-distro.log是否有报错。

**Comment by hupujrsgit** [comment]
查看了naming-event.log日志，最新日期好像是3月份的

查看了healthCheckEnabled 是true
![image](https://user-images.githubusercontent.com/57165757/230819245-d8c56f8a-19ec-4425-84e5-da41e1995f8c.png)

看了下naming-distro.log 出现了null ,不过时间是2月份的
![image](https://user-images.githubusercontent.com/57165757/230819170-f15638e3-f616-4687-ae78-ce2d09283a4c.png)
protocol-distro.log 没日志

**Comment by KomachiSion** [comment]
心跳日志是naming-event.log的DEBUG日志，需要先修改日志级别。

**Comment by KomachiSion** [comment]
protocol-distro.log没日志就是异常情况。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
