### ISSUE TITLE
调用open-api接口和application.properties文件设置永久实例不生效

### ISSUE THREAD

**Issue by santerxing** [alibaba/nacos#10280]
当版本环境：
nacos-client ： 1.4.1
nacos-server：2.0.2

重现步骤：
用了以下两种方式设置永久实例都不成功，在控制台依然显示为临时实例
1、调用open-api接口设置永久实例，接口返回ok。控制台显示临时实例为true，接口不生效
curl --location --request PUT 'url/nacos/v1/ns/instance?port=8182&ip=10.128.1.55&weight=1.0&serviceName=serviceName&ephemeral=false'
2、application.properties文件设置永久实例，重启服务后不生效
![image](https://user-images.githubusercontent.com/32251057/230538703-345ec8c3-d5f2-4366-aa82-04a1cee43647.png)

控制台结果
![image](https://user-images.githubusercontent.com/32251057/230538890-006934c6-1348-42de-b9d0-b9956dd5c8b4.png)

**Comment by KomachiSion** [comment]
1. 服务已经定义成非持久化服务，后续实例只能是非持久化的。
2. 实例摘除后等待服务自动清理（默认1min），或者实例摘除后手动删除该服务后重试。
3. 升级服务端版本， 如果服务已经存在且定义为非持久化，再注册持久化服务时会拦截。

**Comment by santerxing** [comment]
收到，谢谢你
