### ISSUE TITLE
Nacos 2.2.1 start in cluster mode with derby datesource, consle print "Nacos is starting..." continuously

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#10281]
I download nacos 2.2.1 source coed and run in local computer. I try to make two tomcats to run nacos in cluster mode with derby datasource. About to VM options, one of tomcats add below properties:
-Dserver.port=8877
-Dnacos.functionMode=naming
-DembeddedStorage=true
-Dnacos.standalone=false
-Dnacos.home=D:\nacos-cluster\nacos-8877-env
the other of tomcats add below properties:
-Dserver.port=8977
-Dnacos.functionMode=naming
-DembeddedStorage=true
-Dnacos.standalone=false
-Dnacos.home=D:\nacos-cluster\nacos-8977-env
 
and then I specify the cluster by the property "nacos.member.list=127.0.0.1:8877,127.0.0.1:8977". When I run the tomcat whose server.port is 8877, its consle print "Nacos is starting..." continuously. Util I run the other tomcat whose server.port is 8977, Nacos started successfully in cluster mode use embedded storage. Why the situation don't happen when running in cluster mode with mysql datasource?

**Comment by KomachiSion** [comment]
See alipay-jarf.log to find whether your raft has leader.

The derby need sync data by jraft in cluster mode. If no leader for derby, the dump operation will not completed, so that node can't start.

**Comment by huayangchan** [comment]
> 

I have check alipay-jarf.log，a leader node was not successfully elected if the only one tomcat run. Why must multiple nodes start to successfully elect the leader node when runing in cluster mode with derby datasource?

**Comment by KomachiSion** [comment]
one node can elect leader. Maybe you old config saved in raft metadata, or your cluster.conf has more than one node.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by huayangchan** [comment]
I found the problem have been sovled in nacos 2.3.0. May I ask what improvements have been made?

**Comment by huayangchan** [comment]
I found the problem have been sovled in nacos 2.3.0. May I ask what improvements have been made?

**Comment by halegreen** [comment]
this issue seems not fixed in nacos v2.4.3, same issue here
