### ISSUE TITLE
nacos2.2.1使用自定义数据库，启动错误，服务拒绝访问

### ISSUE THREAD

**Issue by gffguo** [alibaba/nacos#10290]
nacos版本 2.2.1
docker单机启动
启动命令
docker run --network mynet --ip 172.19.0.2 -e JVM_XMS=64m -e JVM_XMX=64m -e JVM_XMN=16m  -e MODE=standalone -e PREFER_HOST_MODE=hostname -e NACOS_AUTH_ENABLE=true -v /root/nacos/logs:/home/nacos/logs --restart always --name nacosX -p 5011:8848 -p 6011:9848 -p 6012:9849 -d nacos/nacos-server

appication配置
![image](https://user-images.githubusercontent.com/69896971/230730681-18167c2a-f5ec-459f-a23a-d264d31587ae.png)

我不知道怎么处理，因为我测试的，不使用自己数据库，它可以启动成功，正常访问web服务，可是只要使用数据库，它就无法启动【数据库版本 mysql 8.0.25】
docker logs

![image](https://user-images.githubusercontent.com/69896971/230730752-08f46614-bb8c-4df8-b0e7-888b07b30354.png)

**Comment by KomachiSion** [comment]
OOM了，内存设置过小了。

**Comment by gffguo** [comment]
感谢大佬。我不太会这个，之前用的64m可以运行，这次重启换了新版本后，启动不了了
