### ISSUE TITLE
Nacos运维API是否有提供raft集群管理能力

### ISSUE THREAD

**Issue by little-cui** [alibaba/nacos#10296]
**Is your feature request related to a problem? Please describe.**

- 如何通过API查看集群leader当前在哪个节点上？
- 在一些有明确故障计划的场景，比如集群的leader所在某个AZ计划停电，想提前运维接入，将另一个AZ中的备节点升级成leader，提前进行切换，减少故障发生时叠加选主流程。

**Describe the solution you'd like**

希望有点像ETCD提供的member命令行，先增加一个member，剔除leader，达到leader切换的效果。

**Describe alternatives you've considered**

**Additional context**

**Comment by godhth** [comment]
有的

**Comment by godhth** [comment]
https://github.com/alibaba/nacos/blob/develop/core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java#L66-L69

**Comment by little-cui** [comment]
感谢答复，但怎么判断当前集群哪个节点是leader呢？是否有API支持

**Comment by little-cui** [comment]
> https://github.com/alibaba/nacos/blob/develop/core/src/main/java/com/alibaba/nacos/core/controller/CoreOpsController.java#L66-L69

感谢答复，但怎么判断当前集群哪个节点是leader呢？是否有API支持

**Comment by KomachiSion** [comment]
控制台的集群管理中的元数据有raft相关信息。

或者使用/nacos/v2/core/cluster/nodes查看

**Comment by little-cui** [comment]
可以的，感谢回答
