### ISSUE TITLE
Nacos排除了jraft-core对com.alipay.sofa:bolt的依赖会导致问题

### ISSUE THREAD

**Issue by yuyijq** [alibaba/nacos#10291]
Nacos在引入jraft-core的依赖的时候，排除了对com.alipay.sofa:bolt的依赖会导致问题
jraft里有很多代码会依赖bolt里一些类，不知道为什么Nacos要排除bolt

我在使用Nacos 2.1.2版本的时候，遇到一个Nacos Instnce的metadata不同步的问题，最后排查发现是Nacos排除bolt的依赖导致的，我向jraft社区提交了issue，最后发现是这个问题： https://github.com/sofastack/sofa-jraft/issues/952

**Comment by KomachiSion** [comment]
bolt是sofa的rpc通信协议框架，底层是hessian实现 和 rpc-grpc-impl的rpc实现冲突，如果是因为移除这个导致的问题。那其实还是jraft的问题， 依赖解耦没有处理干净。
