### ISSUE TITLE
share: mysql  (external storage) in nacos cluster mode should connect to only one db(or dbcluster mode)

### ISSUE THREAD

**Issue by AndyWu2015** [alibaba/nacos#10299]
share my test result :
1、nacos cluster mode, embedded storage, nacos will use jraft to sync data.
2、nacos cluster mode, external storage，different nacos node connects to one mysql db, it is ok, data will sync naturally.
3、nacos cluster mode, external storage，different nacos node connects to different mysql db，it will not sync data.

**Comment by KomachiSion** [comment]
of cource, your datasource is different. the data should be different.
