### ISSUE TITLE
[Bug] Nacos启动逻辑问题

### ISSUE THREAD

**Issue by wilsonwu** [alibaba/nacos#10294]
**Describe the bug**
如果内置数据库启动时间慢的话，nacos会启动失败。

**Expected behavior**
希望在nacos启动时有一个检测数据库连接的机制保证正常启动顺序，而不是一味的增加nacos启动等待时间

**Comment by KomachiSion** [comment]
现在配置中心的dump操作强依赖数据库，其就是在检测数据库连接，甚至检测的是数据库是否可用，如果无法使用就会等待并重试。

目前的描述我不太明确`检测数据库连接的机制保证正常启动顺序` 是什么机制。如果只是保证数据库不可用时无法启动，目前有：
1. 如果数据库无法连接，导致Spring 创建Datasource失败， 会停止启动，抛出异常。
2. 如果数据库连接慢，或者数据库操作慢，Dump操作会保持节点一直staring，直到dump操作完成再启动。
3. 配置中心要求dump操作完成后（即配置数据快照ready）后才能启动，**不能**加入机制在数据库不ready，无法dump数据时启动， 这会导致配置下发错误引发业务故障。

**Comment by wilsonwu** [comment]
我们遇到一个问题，简单描述一下：
如果使用内置数据库情况，Nacos在启动时会尝试连接数据库，通常情况数据库启动是比较快的，但是我们遇到这个情况可能是集群有些异常，造成性能影响，所以在Nacos启动的时候数据库程序还没有ready，这样就会产生异常导致nacos启动失败，具体细节如果有遗漏请 @Accelerator96 补充。

所以觉得逻辑应该是Nacos启动时候尝试连接数据库如果失败的话就结束了，是否要加一个重试机制，来尝试更多连接次数？

**Comment by KomachiSion** [comment]
从实现上比较困难， 实际连接数据库操作不在nacos中，而在spring jpa中，spring jpa在连接失败后不会初始化datasource，而后续bean初始化时又需要datasource，导致bean初始化失败，这会直接导致spring容器启动失败。

如果需要加这个机制，就需要看下是否能在spring jpa中或者连接池中添加这个重试机制。

**Comment by jlukeny** [comment]
该问题怎么解决的？
