### ISSUE TITLE
After the same service is restarted, the registration is reported to nacos repeatedly.

### ISSUE THREAD

**Issue by winter-git** [alibaba/nacos#1031]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

spirngcloud服务向nacos注册成功后 ，在次重启这个Springcloud服务 ，服务重启会报错

### Describe what you expected to happen

重启后能注册成功
### How to reproduce it (as minimally and precisely as possible)

1. 首次启动nacos服务
2. 启动一个Spring cloud服务，并注册成功注册到nacos服务
3. 注册成功后重启这个Spring cloud 服务，此时这个springcloud服务会重启失败

### Tell us your environment

MacOS 版本10.13.4 (17E199)
Nacos版本nacos-server-1.0.0-RC3.tar.gz
spring-cloud版本Greenwich.SR1
nacos-config-spring-boot-starter版本0.2.1
nacos-discovery-spring-boot-starter版本0.2.1

### Anything else we need to know?
nacosk控制台
![image](https://user-images.githubusercontent.com/20594863/55845586-100b7b80-5b75-11e9-975e-dd780ef93ba2.png)
错误日志
![image](https://user-images.githubusercontent.com/20594863/55845594-1b5ea700-5b75-11e9-9ea7-687eb4023f37.png)

**Comment by nkorange** [comment]
same problem with #1029
