### ISSUE TITLE
web控制台点击导入配置无任何反应

### ISSUE THREAD

**Issue by Tancen** [alibaba/nacos#10318]
**Describe the bug**
web控制台点击导入配置无任何反应

**Expected behavior**
弹出窗口选择文件导入配置

**Actually behavior**
无任何反应，并且 console 打印 "SyntaxError: "undefined" is not valid JSON" 和 "caught ReferenceError: goLogin is not defined"

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version 2.2.2

**Comment by luo-zhan** [comment]
居然还有这么大的bug，难以置信

**Comment by wilsonwu** [comment]
@KomachiSion 请问2.2.3是否包含这个bug的fix？

**Comment by wilsonwu** [comment]
> @KomachiSion 请问2.2.3是否包含这个bug的fix？

看到release note里面有，建议打上对应已包含变更的版本label。
