### ISSUE TITLE
nacos-naming with Jakarta in SpringBoot 3.x

### ISSUE THREAD

**Issue by ITSweets** [alibaba/nacos#10315]
nacos-naming and Jakarta packages are not compatible in SpringBoot 3.x. The SpringBoot 3.x javax package became Jakarta, requesting adaptation.

**Comment by YunWZ** [comment]
There are currently no plans to support spring-boot 3.x

**Comment by ITSweets** [comment]
Well, so when is support planned? Is it in half a year or how long?

**Comment by KomachiSion** [comment]
duplicate with #9535
