### ISSUE TITLE
How to remove the login function section of the nacos console in v2.x

### ISSUE THREAD

**Issue by massive688** [alibaba/nacos#10313]
I tried the file operation to replace the specified properties in `conf/application.properties`, but it didn't work. Without logging in, I still redirect to the login page. I am using the Docker deployed Nacos
我尝试了文件的操作替换了application.properties中的指定属性,但是没有效果。没有登录的情况，还是会重定向到登录页面,我使用的是docker部署的nacos
```properties
## spring security config
### turn off security
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**
#nacos.security.ignore.urls=${NACOS_SECURITY_IGNORE_URLS:/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**}
```

**Comment by 985492783** [comment]
docker的版本应该还没支持，2.3会解决这个问题

**Comment by KomachiSion** [comment]
2.2.2 has fixed. Please use new version and set `auth.enable=false`

**Comment by KomachiSion** [comment]
duplicate with #10153

**Comment by massive688** [comment]
> 2.2.2 has fixed. Please use new version and set `auth.enable=false`

After Docker v2.2.2 is started, the console address still jumps to the login page, I don't understand what you are saying
