### ISSUE TITLE
The log level cannot be dynamically modified

### ISSUE THREAD

**Issue by clcc2019** [alibaba/nacos#10314]
**Describe the bug**
Use api to dynamically modify the log level of nacos server components
**Expected behavior**
Support dynamic modification of log levels for all components
**Actually behavior**
Unable to modify component log level
**How to Reproduce**
2、服务端业务日志大量打印且无法动态调整日志级别。这个问题在 1.1.3 已经得到优化，可以通过 API 的方式来进行日志级别的调整，调整日志级别的方式如下：

# 调整naming模块的naming-raft.log的级别为error:
curl -X PUT '$nacos_server:8848/nacos/v1/ns/operator/log?logName=naming-raft&logLevel=error'
# 调整config模块的config-dump.log的级别为warn:
curl -X PUT '$nacos_server:8848/nacos/v1/cs/ops/log?logName=config-dump&logLevel=warn'

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server v2.0.3, nacos-client 2.0.3]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by clcc2019** [comment]
/nacos/v1/ns/operator/log?logName=naming-raft&logLevel=error The interface is not authenticated

**Comment by KomachiSion** [comment]
what's your problem? the change log level failed? or the api no authenticated?

**Comment by KomachiSion** [comment]
I test in new version, the api can change the log level successfully.

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.
