### ISSUE TITLE
NACOS_TOKEN_AUTH doesn't work in docker image v1.4.5

### ISSUE THREAD

**Issue by fortime** [alibaba/nacos#10311]
**Describe the bug**
Setting NACOS_TOKEN_AUTH doesn't change the default secret key in `nacos/nacos-server:v1.4.5-slim`. It seems that `conf/application.propertes` is wrong.

**Expected behavior**
According to [this blog](https://nacos.io/zh-cn/blog/announcement-token-secret-key.html), before v2.1.0, `nacos.core.auth.default.token.secret.key` is used. Otherwise, `nacos.core.auth.plugin.nacos.token.secret.key` is used.

**Actually behavior**
In `nacos/nacos-server:v1.4.5-slim`, `conf/application.propertes` contains `nacos.core.auth.plugin.nacos.token.secret.key=${NACOS_AUTH_TOKEN}` instead of `nacos.core.auth.default.token.secret.key=${NACOS_AUTH_TOKEN}`.

**How to Reproduce**
Running this command `docker run --rm --entrypoint grep -it nacos/nacos-server:v1.4.5-slim token conf/application.properties`.

**Desktop (please complete the following information):**
not related

**Additional context**
I have checked the following versions:
wrong: v1.4.5-slim(amd64/arm64), v1.4.4-slim(arm64)
right: v1.4.3(amd64)

**Comment by KomachiSion** [comment]
@paderlol it seems docker repo config file problem.

**Comment by KomachiSion** [comment]
1.4.5 docker images has re-publish.

**Comment by fortime** [comment]
1.4.4 is also affected, I think it should republish too.
