### ISSUE TITLE
关于Nacos-Client中的MetricsMonitor里面提供的指标该如何使用呢？

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#10317]
## Issue Description
如图的指标：
![image](https://user-images.githubusercontent.com/35629966/231636167-6bef2c43-ca27-4421-bf88-d285a8023eef.png)

Nacos Client默认将它们注册到defaultRegistry中，这些指标使用SpringBootActuator如何暴漏呢？
SpringBootActuator中对应CompositeMeterRegistry里面包含PrometheusMeterRegistry，SpringBootActuator将会暴漏io.micrometer.prometheus.PrometheusMeterRegistry#registry中的所有指标，但是它和Nacos Client注册到io.prometheus.client.CollectorRegistry#defaultRegistry中的指标没有任何关系呀，我不知道Nacos Client将如何暴漏这些指标？

**Comment by KomachiSion** [comment]
会被记录到micrometer中，导入任何micrometer的具体实现，如prometheus实现后，通过prometheus exporter去采集。

具体不同的实现有不同的获取方式，请参考对应实现的文档获取。
