### ISSUE TITLE
nacos1.4.2开启鉴权，新建的只读或只写账户，应用服务起不来，提示认证失败

### ISSUE THREAD

**Issue by git-ssyang** [alibaba/nacos#10329]
开启鉴权配置，新建一个只读或只写的账号后，应用服务配置nacos并使用该账号，启动服务注册到nacos中，但会报错，提示认证失败
将新建的账号分配了读写权限，应用服务就可以正常起来

**Comment by KomachiSion** [comment]
说明你的应用启动同时需要读写权限，即应用会读nacos数据也会写nacos数据。
看描述是使用问题， 和nacos无关。

**Comment by xuxiaowei-com-cn** [comment]
我用的是 nacos 2.2.2，只能使用默认用户 nacos 才能启动服务，新建用户无论如何授权都不能认证成功。在数据库中，将新建用户的角色改为 ROLE_ADMIN 就可以启动服务了。

**Comment by xuxiaowei-com-cn** [comment]
https://github.com/alibaba/nacos/issues/10347
