### ISSUE TITLE
Hope to support Prometheus service discovery

### ISSUE THREAD

**Issue by wshzp09876** [alibaba/nacos#1032]
Hope to support Prometheus using nacos as a service discovery source.

**Comment by wshzp09876** [comment]
Prometheus support use service discovery to dynamic add monitor point. So current the SD mode support consul, k8s. Hope we can add nacos SD to Prometheus SD support to integrate the Prometheus with nacos together.

**Comment by nkorange** [comment]
We hope someone familiar with Prometheus can contribute for it, feel free to ask me for any question about Nacos.

**Comment by vicykie** [comment]
+1

**Comment by STRRL** [comment]
How about making an adaptor like [eureka-consul-adapter](https://github.com/twinformatics/eureka-consul-adapter) instead of native-way for prometheus.

Or export to a file that compatible with prometheus' file_discovery.

**Comment by nkorange** [comment]
@STRRL I think this is the recommended way. Can you implement this adapter for Nacos?

**Comment by STRRL** [comment]
@nkorange Thanks for your trust.
I will try it during this Labor day holiday. XD

**Comment by nkorange** [comment]
> @nkorange Thanks for your trust.
> I will try it during this Labor day holiday. XD

Great, if you have any problem you can contact me.

**Comment by wshzp09876** [comment]
use Prometheus  File SD + jar（little client work with APIs and generate json file）
then customize a docker images: put the prometheus and that jar into a images

It works for me currently, still hope we can have direct prometheus SD with nacos


Reference:
https://prometheus.io/docs/guides/file-sd/

**Comment by STRRL** [comment]
@i will solve it@

**Comment by nkorange** [comment]
@STRRL Are you working on this issue?

**Comment by STRRL** [comment]
Sorry, I forgot it for almost three weeks. 
But I already find out the way to make nacos be compatible with consul. 

I will upload my work later.

**Comment by little3201** [comment]
Hurry up

**Comment by BinWu1989** [comment]
Hi ,Is there any update on this? If the process is stuck ,I will do the job

**Comment by little3201** [comment]
No any update

**Comment by xuande** [comment]
@STRRL Can you share the solution ?

**Comment by BinWu1989** [comment]
I implmented as the [eureka-consul-adapter](https://github.com/twinformatics/eureka-consul-adapter) way to implements the interfaces the consul providies ,seems it works as expected 。The interfaces needed are below:
(1)/v1/agent/self
(2)/v1/catalog/services
(3)/v1/catalog/service/{serviceName}

**Comment by little3201** [comment]
How work with it

发自我的iPhone

**Comment by xuande** [comment]
参考[eureka-consule-adapter](https://github.com/twinformatics/eureka-consul-adapter)实现的[nacos-consul-adapter](https://github.com/xuande/nacos-consul-adapter),在prometheus配置文件中使用consul_sd_configs配置nacos-consul-adapter地址可以实现从nacos中动态发现服务地址

**Comment by bigcatpan** [comment]
@STRRL Hi, Have you solved it？

**Comment by STRRL** [comment]
> @STRRL Hi, Have you solved it？

No. I did not work on it for a long time.

Maybe you take a try on https://github.com/xuande/nacos-consul-adapter and https://github.com/afghanistanyn/prometheus-nacos-sd mentioned in above comments.
