### ISSUE TITLE
关闭SwitchDomain.isDistroEnabled()后Nacos Naming功能不正常

### ISSUE THREAD

**Issue by yuyijq** [alibaba/nacos#10337]
switchDomain.isDistroEnabled()关闭后，Nacos Naming的“responsible”计算就相当于失效了，这会导致一些问题：
1. 健康检查，原来只有responsible node才会负责健康检查，现在是所有节点都进行健康检查，如果一个没有收到心跳的节点判断不健康就会导致判断失误。
2. 数据同步，之前只从responsible node向其他节点同步，现在可能会循环同步了
3. 节点之间数据校验也可能存在同样问题

感觉既然提供了这个开关，但是开关调整后功能又不正常，有点奇怪

**Comment by KomachiSion** [comment]
如果只使用持久化服务， 可以关闭distro协议以减少无效转发。如果需要是有非持久化服务， 那么distro协议作为非持久化服务的同步手段， 关闭肯定会导致问题。

**Comment by KomachiSion** [comment]
另外此开关可以作为部分高压场景的临时恢复手段，关闭后因为不会集群间转发请求， 可以让服务端逐渐恢复后再开启。

**Comment by KomachiSion** [comment]
正常情况下保持其默认开启即可。
