### ISSUE TITLE
Raft log cleanup problem

### ISSUE THREAD

**Issue by chenzhiguo** [alibaba/nacos#10333]
**Describe the bug**
I found that the `LOG` file in this directory, `/home/nacos/data/protocol/raft/naming_instance_metadata/log/`, was very large and did not automatically delete or shrink. Is this a bug? What to do with this huge log file?

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 2.0.4]

**Comment by chenzhiguo** [comment]
Can somebody take a look at this? This relates to the `jraft` component and is the log it outputs.  @jun1st @martin-g @zhfish

**Comment by martin-g** [comment]
Why me ? :-)

**Comment by chenzhiguo** [comment]
> Why me ? :-)

^_^ Github auto recommended

**Comment by KomachiSion** [comment]
Please learn the raft protocol, the log large means your application call update instance api frequently and continue write raft  log.

The Log is maintain by jraft, It should be removed some old log when the snapshot saved with 30min interval.

**Comment by chenzhiguo** [comment]
`LOG` files run for several months and accumulate large amounts of data. I know from `jraft` that snapshot needs to be enabled, but does nacos not enable snapshot by default? If it's turned on by default, wouldn't the `LOG` keep growing and not decreasing?

**Comment by KomachiSion** [comment]
Of cource snapshot is enabled, you can see in alipay-jraft.log, has some log for snapshot dump and delete.

**Comment by chenzhiguo** [comment]
That's weird, because by default snapshot is enabled, the log is still growing.

**Comment by KomachiSion** [comment]
You can move to jraft community to find out how to clear this LOG file or whether can remove it.
