### ISSUE TITLE
getConfig读取的配置是旧的

### ISSUE THREAD

**Issue by frankywen** [alibaba/nacos#10332]
版本：nacos-client 2.0.3

服务描述
OPS： devops系统，集成nacos-cleint，管理多台服务器上的服务配置，并支修改发布到nacos
AGENT：安装在每台服务器上，集成nacos-cleint，用于接收OPS请求，并执行相应业务功能，如：更新配置(从naocs读取再写入指定文件)

问题描述
OPS修改配置后发布到nacos, 通知AGENT更新配置，这时AGENT读取到的配置是旧的。查看getConfig实现，发现会先读failover里本地缓存的数据，怀疑是读取了该配置导致。failover里缓存文件是何时生成的，如果是该问题，能否增参数控制不走failover.

**Comment by KomachiSion** [comment]
nacos-client不会写failover文件， failover是用户手动创建的文件和内容， 用于nacos-server完全无法使用时， 业务方还需要修改配置的场景。

方法就是创建failover文件，并且把新的配置写在failover中， 属于故障很严重时候的临时恢复手段。

你这个描述更像AGENT没有订阅这个配置， 只是启动的时候获取了一次。可以在控制台上看这个配置的订阅者有没有这个agent。

另外看修改的配置的ns，group，dataId是不是和agent使用的完全相同。

**Comment by frankywen** [comment]
AGENT 不会订阅这个配置，调用nacos-client的getConfig获取的，ns，group，dataId是完全相同，那nacos服务里的配置读取有缓存吗？

**Comment by frankywen** [comment]
nacos服务端里，配置会有缓存吗？什么时候更新？

**Comment by KomachiSion** [comment]
会先读取服务端里的， 读取不到读本地缓存。

一般本地缓存在${user.home}/nacos/config/....

**Comment by KomachiSion** [comment]
可以查看日志，对比历史记录里的md5，如果日志里的md5和服务端记录的一致， 那说明nacos-client获取到了新的配置， 只是应用自己不用新配置。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
