### ISSUE TITLE
yaml偶现启动报错，去掉注释某几个字符后成功

### ISSUE THREAD

**Issue by YeJiaL** [alibaba/nacos#10334]
service: Nacos 2.1.2
client:  spring-cloud-starter-alibaba-nacos-config 2021.0.1.0  springboot 2.6.7
表现现象启动失败，但若去掉注释的某几个字符，则能启动成功
log如下
`
{"timestamp":"2023-04-04T14:31:26.905+0800","description":"parse data from Nacos error,dataId:vna-data-service-prod.yml,data:server:\n  port: xxxx\n  servlet:\n    context-path: /vna/data\n    \nspring:\n  datasource:\n    type: com.alibaba.druid.pool.DruidDataSource\n    driverClassName: org.mariadb.jdbc.Driver\n    url: jdbc:mysql://xxxx/xxx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true\n    username: root\n    password: xxxx\n    druid:\n      # 初始连接数\n      initialSize: 30\n      # 最小连接池数量\n      minIdle: 30\n      # 最大连接池数量\n      maxActive: 30\n      # 配置获取连接等待超时的时间\n      maxWait: 60000\n      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒\n      timeBetweenEvictionRunsMillis: 300000\n      # 配置一个连接在池中最小生存的时间，单位是毫秒\n      minEvictableIdleTimeMillis: 300000\n      # 配置一个连接在池中最大生存的时间，单位是毫秒\n      maxEvictableIdleTimeMillis: 900000\n      testWhileIdle: false\n      # 配置检测连接是否有效\n      validationQuery: SELECT 1\n      testOnBorrow: false\n      testOnReturn: false\n      webStatFilter:\n        enabled: true\n      statViewServlet:\n        enabled: true\n        # 设置白名单，不填则允CheckController许所有访问\n        allow:\n        url-pattern: /druid/*\n        # 控制台管理用户名和密码\n        login-username: xxxx\n        login-password: xxxx\n      filter:\n        stat:\n          enabled: true\n          # 慢SQL记录\n          log-slow-sql: true\n          slow-sql-millis: 1000\n          merge-sql: true\n        wall:\n          config:\n            multi-statement-allow: true\n\nmybatis-plus:\n  mapper-locations: classpath:/mapper/**/*.xml\n  configuration:\n    map-underscore-to-camel-case: true\n    cache-enabled: false\n    default-statement-timeout: 5\n    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl\n    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl\n    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler\n  check-config-location: false\n  type-enums-package: com.xx.uplus.cetus.**.enums\n\nlogging:\n  level:\n    com.xxx.uplus.cetus: debug\n    com.alibaba.nacos.client.naming: WARN\n    com.alibaba.nacos.client.config.impl: WARN\n    org.springframework: WARN\n\n# Swagger配置\ncustom:\n  swagger:\n    enabled: true\n\n# Swagger配置\nswagger:\n  enabled: true\n  title: 联影大数据中台接口文档\n  description: 联影大数据中台\n  version: 1.0\n\n#日志相关配置\napp:\n  name: ${spring.application.name}\n  logical-code: 81\n\n#UAP 认证配置\nauth:\n  enable: false  # 集成uap权限开关 默认true需要认证\n  # 可匿名访问路由列表\n  anon: /swagger-ui/**,/swagger/**,/webjars/**,/swagger-resources/**,/v3/api-docs\n  oidc:\n    provider:\n      # 统一登录服务地址 (oidc 获取 加密参数)\n      baseUrl: http://xxx/uap_auth\n    token:\n      offset: -1 #token 校验时间偏移量，单位（秒）（可以推迟token过期时间，hsw有使用）\n      header: Authorization #token 请求头，可不填，默认为 Authorization\n  online-validate:\n    enabled: true  #是否开启 token 实时校验，不开启则只验证 token 签名是否合法\n  #自定义接口权限拦截属性\n  config:\n    enabled: false  #是否开启权限拦截,默认false不开启\n    expire-time: 1800  #权限信息缓存时间 s\n    exclude-path-patterns: /v1/common,/v1/api/**  #不走权限拦截器接口url\n    app-key: xxxx  #当前应用的clientId\n","service":"vna-data-service","logger":"com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder","thread":"main","version":"1.1.1","tid":"","stack":"java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024\n\tat org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[snakeyaml-1.29.jar!/:na]\n\tat org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:135) ~[snakeyaml-1.29.jar!/:na]\n\tat org.springframework.boot.env.OriginTrackedYamlLoader$OriginTrackingConstructor.getData(OriginTrackedYamlLoader.java:99) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat org.yaml.snakeyaml.Yaml$1.next(Yaml.java:514) ~[snakeyaml-1.29.jar!/:na]\n\tat org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:198) ~[spring-beans-5.3.19.jar!/:5.3.19]\n\tat org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166) ~[spring-beans-5.3.19.jar!/:5.3.19]\n\tat org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:84) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat com.alibaba.cloud.nacos.parser.NacosDataParserHandler.parseNacosData(NacosDataParserHandler.java:92) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:97) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:149) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103) ~[spring-cloud-starter-alibaba-nacos-config-2021.0.1.0.jar!/:2021.0.1.0]\n\tat org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.1.2.jar!/:3.1.2]\n\tat org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.1.2.jar!/:3.1.2]\n\tat org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.1.2.jar!/:3.1.2]\n\tat org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:613) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:381) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.7.jar!/:2.6.7]\n\tat com.uih.uplus.vna.DataApplication.main(DataApplication.java:26) ~[classes!/:na]\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]\n\tat org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[vna-data-service.jar:na]\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[vna-data-service.jar:na]\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[vna-data-service.jar:na]\n\tat org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[vna-data-service.jar:na]\n"}
`

**Comment by KomachiSion** [comment]
这是spring解析yaml失败， 与nacos无关，请提交到Spring cloud alibaba 社区。
