### ISSUE TITLE
using the Nacos2.2.2 and 达梦8 databases，update config function error ！！！！

### ISSUE THREAD

**Issue by yanborer** [alibaba/nacos#10335]
Nacos version 2.2.2
Database：达梦8

问题：
更新配置信息，提示以下信息：

caused: PreparedStatementCallback; 违反表[CONFIG_INFO]唯一性约束; nested exception is dm.jdbc.driver.DMException: 违反表[CONFIG_INFO]唯一性约束;caused: 违反表[CONFIG_INFO]唯一性约束;

检查nacos源码，核心类是ExternalStoragePersistServiceImpl.java，方法为insertOrUpdate。
发现在2.2.2版本中，捕获的异常是DuplicateKeyException，但是达梦数据库抛出的异常是DataIntegrityViolationException。
而在2.2.1版本（含）之前，捕获的异常是DataIntegrityViolationException，DuplicateKeyException是它的一个子类。

正常捕获的异常应为DataIntegrityViolationException

**Comment by yanborer** [comment]
2.2.1(含)之后的版本，捕获的异常是DuplicateKeyException。
2.2.0的版本，捕获的异常是DataIntegrityViolationException

**Comment by KomachiSion** [comment]
[        } catch (DataIntegrityViolationException ive) { // Unique constraint conflict

](https://github.com/alibaba/nacos/blob/d2e16a3e420a23dce1801de95ef9a4b3f91b3e89/config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalStoragePersistServiceImpl.java#L466)

**Comment by KomachiSion** [comment]
2.2.2的tag，捕获的是DataIntegrityViolationException

**Comment by yanborer** [comment]
在release中下载2.2.1版本，反编译nacos-server.jar，出现的是DuplicateKeyException
![image](https://user-images.githubusercontent.com/36002224/233283720-2f8f6d1e-725f-4a20-8bde-b90572c21ac2.png)

**Comment by KomachiSion** [comment]
merge to #10335 discussion
