### ISSUE TITLE
The number of nacos console instances and the number of clusters are abnormal.

### ISSUE THREAD

**Issue by winter-git** [alibaba/nacos#1033]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
一台电脑 起了两个不同的服务 每个服务都是集群数目=2，实例数=2，健康实例数=1健康实例数是正确的

application.properties配置：

nacos.config.server-addr=127.0.0.1:8848
nacos.discovery.server-addr=127.0.0.1:8848
nacos.discovery.register-enabled=true
spring.cloud.nacos.config.file-extension=properties,yml,yaml
management.endpoints.web.exposure.include='*'

server.port=22001
spring.application.name=example-nacos-web-dev

### Describe what you expected to happen
单服务注册的时候，nacos控制台显示的实例数和集群数都显示1

### How to reproduce it (as minimally and precisely as possible)

1. 首次启动nacos服务
2. 启动一个Spring cloud服务，并注册成功注册到nacos服务
3. 登陆nacos控制台查看服务列表

### Tell us your environment
MacOS 版本10.13.4 (17E199)
Nacos版本nacos-server-1.0.0-RC3.tar.gz
spring-cloud版本Greenwich.SR1
nacos-config-spring-boot-starter版本0.2.1
nacos-discovery-spring-boot-starter版本0.2.1

### Anything else we need to know?
![image](https://user-images.githubusercontent.com/20594863/55848038-400b4c80-5b7e-11e9-994b-44c203a223dc.png)
![image](https://user-images.githubusercontent.com/20594863/55848046-44376a00-5b7e-11e9-8bef-2c15cba2b6e3.png)

**Comment by nkorange** [comment]
@winter-git nacos-client版本多少？

**Comment by winter-git** [comment]
<version>0.2.1</version>

**Comment by winter-git** [comment]
> @ winter-git nacos-client版本多少？

<version>0.2.1</version>

**Comment by winter-git** [comment]
> @ winter-git nacos-client版本多少？

0.2.1-RC1

**Comment by nkorange** [comment]
这个问题有两个原因：客户端版本太低，服务端没有做参数校验。请升级到最新的nacos客户端，服务端会加上参数校验。
