### ISSUE TITLE
nacos-config-spring-boot-starter不支持springboot3 ？？？？？

### ISSUE THREAD

**Issue by yqbboy** [alibaba/nacos#10340]
**Describe the bug**
我目前把springboot升级到了3.0.5版本，同时nacos-config-spring-boot-starter和nacos-discovery-spring-boot-starter使用的是0.2.12版本。目前的问题是，配置注入会失败。

部分代码：
@NacosValue(value = "${switch.monitor.enabled:false}")
 private Boolean switchMonitorEnable;

通过debug，发现switchMonitorEnable为null。

```xml
<dependency>
                <groupId>com.alibaba.boot</groupId>
                <artifactId>nacos-config-spring-boot-starter</artifactId>
                <version>0.2.12</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.boot</groupId>
                <artifactId>nacos-discovery-spring-boot-starter</artifactId>
                <version>0.2.12</version>
            </dependency>
```

JDK版本：openjdk17
springboot:3.0.5

**Comment by KomachiSion** [comment]
duplicate with #9535
