### ISSUE TITLE
nacos-1.3.2出现集群注册状态不一致，有两个follower，一个candidate，没有leader。

### ISSUE THREAD

**Issue by xiaoqiaoqiao888** [alibaba/nacos#10344]
## Issue Description
nacos-1.3.2出现集群注册状态不一致，有两个follower，一个candidate，没有leader。
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos-1.3.2出现集群注册状态不一致，有两个follower，一个candidate，没有leader。对交易是否有影响？

### Describe what you expected to happen
判断对交易是否有影响？以及如何解决？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
1.3.2 is too old, please upgrade to new version.

Or provide more information.

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
