### ISSUE TITLE
nacos 2.2.2 集群部署，调用注册中心的时候，三个节点只有一个节点可以用，另外两个节点报错400

### ISSUE THREAD

**Issue by Willbefine123** [alibaba/nacos#10345]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Willbefine123** [comment]
使用的版本是2.2.2

**Comment by KomachiSion** [comment]
Please follow the issue template provide detail information. Current information is not enough.

**Comment by Willbefine123** [comment]
使用curl发起注册请求，集群中的三个节点ip03能正常注册 另外两个节点报错400
curl --request POST --url 'http://ip01:28848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080&username=nacos&password=xxx'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   435  100   435    0     0   4408      0 --:--:-- --:--:-- --:--:--  4484<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>


$ curl --request POST --url 'http://ip02:28848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080&username=nacos&password=xxx'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   435  100   435    0     0   4382      0 --:--:-- --:--:-- --:--:--  4438<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>


$ curl --request POST --url 'http://ip03:28848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080&username=nacos&password=xxx'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2  100     2    0     0     20      0 --:--:-- --:--:-- --:--:--    21ok

**Comment by 15155280807** [comment]
可以看下NacosAsyncRestTemplate这个模板调用的方法，好像是http工具类的问题，我换了工具类访问正常

**Comment by Willbefine123** [comment]
我是用curl命令模拟注册的，一个节点一直都是正常的，另外两个节点一直不行

**Comment by Willbefine123** [comment]
> 可以看下NacosAsyncRestTemplate这个模板调用的方法，好像是http工具类的问题，我换了工具类访问正常

我不是用程序调用的，是用curl命令模拟注册的，一个节点一直都是正常的，另外两个节点一直不行

**Comment by KomachiSion** [comment]
看看日志有什么信息， 目前信息太少，无法判断。

**Comment by AgYZY** [comment]
这个问题有什么进展吗，我们升级到2.2.1或者2.2.2集群也有这个问题，单机部署是正常的。集群部署，把正常节点停掉，剩余两个节点随机有一个变得正常了，然后把停掉的节点重新启动，是正常的，然后刚刚变得正常的节点又不能用了。开始以为是只有leader节点正常，后来发现是随机的，没发现规律。

**Comment by KomachiSion** [comment]
我自己的环境无法复现， 主要看下日志中有没有其他的报错信息。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem and community can't reproduce problem.

**Comment by daishanc** [comment]
这个问题可有进展，我升级到2.2.3集群也有这个问题，单机部署是正常的。版本信息： springboot版本2.3.2.RELEASE，springcloud版本Hoxton.SR6，springcloudalibaba版本2.2.6.RELEASE

**Comment by daGzhoulizhi** [comment]
同样问题希望这个bug有新的进展： 
nacos 版本：2.2.2  & 2.2.3
部署方式： K8S 集群
nacos 对程序配置的host ：  nacos-cs:8848
复现方法：
1. 在nacos web 界面 对服务 进行上下线操作
2. 后端程序也会有报错
自测：
在每个pod 用 curl命令进行api 接口 v1/ns/instance 请求
后端程序报错截图：
<img width="1662" alt="9D34F46B-E686-4b10-BAC7-94DA368044FA" src="https://github.com/alibaba/nacos/assets/142370904/b5053544-75d9-4eaf-879d-26fe1a5826e6">
nacos web 界面截图：
![image](https://github.com/alibaba/nacos/assets/142370904/d5425a0d-3884-4681-92f9-62e2e2dc873e)

**Comment by guoxu0514** [comment]
你检查一下，你配置文件的nacos.core.auth.server.identity.key、nacos.core.auth.server.identity.value这俩配置项，看看配置的值是否有空格
