### ISSUE TITLE
在go fiber 中开启prefork SO_REUSEPORT后，用 go client 发现服务一直错误，关掉就要没问题。

### ISSUE THREAD

**Issue by ninjashixuan** [alibaba/nacos#10346]
go fiber 中开启prefork为true， 使用go client服务发现整个进程就挂掉

环境
rpc服务端注册使用：go-zero & nacos
web调用端使用 go fiber 框架
client sdk : github.com/zeromicro/zero-contrib/zrpc/registry/nacos

稳定复现。

**Comment by KomachiSion** [comment]
尝试只使用nacos-go-sdk是否可以注册， 如果只使用nacos-go-sdk可以， 那应该是go fiber的问题。
