### ISSUE TITLE
The remote configuration file is used in the remote configuration file 远端配置文件中使用远端的配置文件 

### ISSUE THREAD

**Issue by EucalyZ** [alibaba/nacos#10359]
是否不支持在nacos远端配置文件中使用远端的配置文件，只能在本地的配置中调用到

Whether the remote configuration file is not supported in the remote configuration file of nacos and can only be invoked in the local configuration file

**Comment by KomachiSion** [comment]
你的意思是配置A中的变量从B配置中读取？

这个nacos不支持， 配置之间没有关联关系。内容对nacos来说是黑盒。

在应用中可以自己做一下， 或者用spring cloud类似的框架会自动做。
