### ISSUE TITLE
com.alibaba.nacos.naming.core.Service#groupName value error

### ISSUE THREAD

**Issue by paulzhangcc** [alibaba/nacos#1036]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
In the code ”com.alibaba.nacos.naming.core.ServiceManager#createEmptyService“
When an service is created,the field[groupName] of Service is seted "DEFAULT_GROUP", Whether groupName should be obtained by the parameter serviceName? because serviceName is NamingUtils.getGroupedName(serviceName, groupName)

![image](https://user-images.githubusercontent.com/12210796/55862683-84f9a800-5bab-11e9-85ef-d1bf9ad95e15.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos version:1.0.0-RC3

**Comment by nkorange** [comment]
@paulzhangcc The 'groupName' inside a Service is not in use now, but it should be corrected anyway. Can you fix it?

**Comment by paulzhangcc** [comment]
@nkorange i have fixed and pull a request ,tiltle is 'fix-1036'

**Comment by nkorange** [comment]
@paulzhangcc Thank your!
