### ISSUE TITLE
请问spring-cloud-starter-alibaba-nacos-discovery 2021.0.5.0版本应该对应哪个版本的openfeign和ribbon？

### ISSUE THREAD

**Issue by kingsley1215** [alibaba/nacos#10369]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Please move to spring cloud alibaba community
