### ISSUE TITLE
 Error clicking to import configuration

### ISSUE THREAD

**Issue by walkonroad** [alibaba/nacos#10368]
<!-- Here is for bug reports and feature requests ONLY! 

**Describe the bug**
error: Error clicking to import configuration。The import windowdoes not appear。

**Expected behavior**
when clicking to import configuration ,then the import window appears。

**Actually behavior**
The import windowdoes not appear

**How to Reproduce**
![image](https://user-images.githubusercontent.com/18378551/233832688-622a7599-6683-474a-b81a-b3cd25246a80.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version 2.2.2
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

No errors  when starting using the  embedded storage mode。
But there are errors  when starting using external storage mode。

**Comment by KomachiSion** [comment]
#10318
