### ISSUE TITLE
[Summer 2023] 新增达梦数据库插件实现/Added Dameng database plug-in implementation

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#10373]
开源之夏是由中科院软件所“开源软件供应链点亮计划”发起并长期支持的一项暑期开源活动，旨在鼓励在校学生积极参与开源软件的开发维护，培养和发掘更多优秀的开发者，促进优秀开源软件社区的蓬勃发展，助力开源软件供应链建设。

Nacos将会作为指导组织参加本次的[“开源之夏2023”](https://summer.iscas.ac.cn/)

## 背景

去年的编程之夏中，Nacos社区完成了数据库插件的设计和实现工作#8312，并在社区的帮助下新增了postgreSQL的支持#9499，同时Oracle数据库的插件适配工作社区也有同学正在进行中。目前已经适配或即将适配的数据库中，都是国外的常用数据库，暂时缺少对国内数据库的适配。同时社区中也有很多希望能够适配国产数据库的需求，比如达梦数据库#9614,#8280,#5306 。

因此社区希望有同学能够参考目前MySQL、PGSQL等插件实现，对国产达梦数据库新增一个数据库插件的实现。

这将有助于Nacos社区更好地满足国内用户的需求，同时也将为国内数据库的推广和发展做出贡献。希望同学能够积极参与，共同推动Nacos社区的发展。

## 目标

为Nacos适配达梦数据库，在nacos-group/nacos-plugin工程下添加达梦数据库插件。

## 难度

基础

## 导师
李艳林
yan.lin2009@163.com

## 产出要求

- 在nacos-group/nacos-plugin工程下添加达梦数据库插件
- 添加对应文档内容

## 能力要求

- 熟悉Java编程语言
- 熟悉至少一个MySQL、PostgreSQL、Oracle等常用数据库
- 熟悉markdown

----
Open Source Promotion Plan is a summer program organized by the Institute of Software Chinese Academy of Sciences and long-term supported by the Open Source Software Supply Chain Promotion Plan. It aims to encourage college students to actively participate in the maintenance and development of open source software, promote the vigorous development of open source software communities, and build the open source software supply chain together.

Nacos will join [The Summer 2023](https://summer-ospp.ac.cn/) as the mentoring organization.

## Background

Last year's Summer OSPP, the Nacos community completed the design and implementation of the database plugin in #8312, And with the help of the community, added support for postgreSQL in #9499. At the same time, the community is also working on adapting the Oracle database plugin in #9498. 

Currently, the databases that have been adapted or are about to be adapted are commonly used foreign databases, and there is a lack of adaptation for domestic databases. At the same time, there are many demands in the community to adapt domestic databases, such as the `Dameng` database #9614, #8280, #5306.

Therefore, the community hopes that students can refer to the current MySQL, PGSQL plugins to implement a database plugin for domestic `Dameng` databases. This will help the Nacos community better meet the needs of domestic users, and also make contributions to the promotion and development of domestic databases. We hope that enthusiastic students can actively participate and jointly promote the development of the Nacos community.

## Target 

Adapt the `Dameng` database for Nacos, add a `Dameng` database plugin under the nacos-group/nacos-plugin project.

## Difficulty
Basic

## Mentor
Yanlin Li
yan.lin2009@163.com

## Output Requirements

- Add `Dameng` database plugin under the nacos-group/nacos-plugin project.
- Add `Dameng` database plugin documentation content.

## Technical Requirements
- Familiar with Java programming language
- Familiar once database like MySQL, PostgreSQL or Oracle
- Familiar with writing markdown documents

**Comment by huawuque404** [comment]
这个插件像已经刚刚有人完成了，现在在开源之夏的项目里是不是就不能参加这个项目了

**Comment by KomachiSion** [comment]
> 这个插件像已经刚刚有人完成了，现在在开源之夏的项目里是不是就不能参加这个项目了

是的， 由于该课题已经被社区同学提前完成了， 因此该课题将被取消。

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-plugin/pull/24
https://github.com/nacos-group/nacos-plugin/pull/26

**Comment by dylan-tao** [comment]
> 开源之夏是由中科院软件所“开源软件供应链点亮计划”发起并长期支持的一项暑期开源活动，旨在鼓励在校学生积极参与开源软件的开发维护，培养和发掘更多优秀的开发者，促进优秀开源软件社区的蓬勃发展，助力开源软件供应链建设。
> 
> Nacos将会作为指导组织参加本次的[“开源之夏2023”](https://summer.iscas.ac.cn/)
> 
> ## 背景
> 去年的编程之夏中，Nacos社区完成了数据库插件的设计和实现工作#8312，并在社区的帮助下新增了postgreSQL的支持#9499，同时Oracle数据库的插件适配工作社区也有同学正在进行中。目前已经适配或即将适配的数据库中，都是国外的常用数据库，暂时缺少对国内数据库的适配。同时社区中也有很多希望能够适配国产数据库的需求，比如达梦数据库#9614,#8280,#5306 。
> 
> 因此社区希望有同学能够参考目前MySQL、PGSQL等插件实现，对国产达梦数据库新增一个数据库插件的实现。
> 
> 这将有助于Nacos社区更好地满足国内用户的需求，同时也将为国内数据库的推广和发展做出贡献。希望同学能够积极参与，共同推动Nacos社区的发展。
> 
> ## 目标
> 为Nacos适配达梦数据库，在nacos-group/nacos-plugin工程下添加达梦数据库插件。
> 
> ## 难度
> 基础
> 
> ## 导师
> 李艳林 [yan.lin2009@163.com](mailto:yan.lin2009@163.com)
> 
> ## 产出要求
> * 在nacos-group/nacos-plugin工程下添加达梦数据库插件
> * 添加对应文档内容
> 
> ## 能力要求
> * 熟悉Java编程语言
> * 熟悉至少一个MySQL、PostgreSQL、Oracle等常用数据库
> * 熟悉markdown
> 
> Open Source Promotion Plan is a summer program organized by the Institute of Software Chinese Academy of Sciences and long-term supported by the Open Source Software Supply Chain Promotion Plan. It aims to encourage college students to actively participate in the maintenance and development of open source software, promote the vigorous development of open source software communities, and build the open source software supply chain together.
> 
> Nacos will join [The Summer 2023](https://summer-ospp.ac.cn/) as the mentoring organization.
> 
> ## Background
> Last year's Summer OSPP, the Nacos community completed the design and implementation of the database plugin in #8312, And with the help of the community, added support for postgreSQL in #9499. At the same time, the community is also working on adapting the Oracle database plugin in #9498.
> 
> Currently, the databases that have been adapted or are about to be adapted are commonly used foreign databases, and there is a lack of adaptation for domestic databases. At the same time, there are many demands in the community to adapt domestic databases, such as the `Dameng` database #9614, #8280, #5306.
> 
> Therefore, the community hopes that students can refer to the current MySQL, PGSQL plugins to implement a database plugin for domestic `Dameng` databases. This will help the Nacos community better meet the needs of domestic users, and also make contributions to the promotion and development of domestic databases. We hope that enthusiastic students can actively participate and jointly promote the development of the Nacos community.
> 
> ## Target
> Adapt the `Dameng` database for Nacos, add a `Dameng` database plugin under the nacos-group/nacos-plugin project.
> 
> ## Difficulty
> Basic
> 
> ## Mentor
> Yanlin Li [yan.lin2009@163.com](mailto:yan.lin2009@163.com)
> 
> ## Output Requirements
> * Add `Dameng` database plugin under the nacos-group/nacos-plugin project.
> * Add `Dameng` database plugin documentation content.
> 
> ## Technical Requirements
> * Familiar with Java programming language
> * Familiar once database like MySQL, PostgreSQL or Oracle
> * Familiar with writing markdown documents

nacosplus来啦，针对多种数据库（包含信创数据库）提供支持，达梦数据库经过严格测试后，即将上线，详见：https://github.com/dylan-tao/nacos-plus
