### ISSUE TITLE
如何区分console和nacos-client链接auth所使用的用户名和密码

### ISSUE THREAD

**Issue by sourirer** [alibaba/nacos#10372]
Situation：
目前使用auth的方式提供给nacos-client进行链接。
但是这会导致client直接拿到username/password以及url
可以使用这个信息直接登录console

Request：
client使用的auth信息仅用来进行client相关的操作，此auth无法用以登录console
如何完成呢？

**Comment by KomachiSion** [comment]
开发自定义鉴权插件。

默认的鉴权插件只能给命名空间级别的资源授权，是通用的，不区分client还是console。
