### ISSUE TITLE
k8s搭建nacos集群，三个节点启动正常，但是在nacos的控制台只显示一个节点

### ISSUE THREAD

**Issue by juda666a** [alibaba/nacos#10370]
如图所示
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/51785878/233839374-5bd6d60f-73cc-49c7-a971-c7f1eb327691.png">
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/51785878/233839414-3ad6fec5-11dd-42b5-9bff-3d6e0cb106d8.png">
k8s版本:1.27.1
nacos版本:2.2.2
docker版本:23.0.4
nacos通过NodePort方式暴露8848端口供外部访问，具体yaml配置文件如下
<img width="383" alt="image" src="https://user-images.githubusercontent.com/51785878/233839505-572f136c-f989-40c0-b463-fc9b17d41104.png">

**Comment by KomachiSion** [comment]
说明部署方式有问题，要么单例模式启动了，要么没配置cluster.conf文件或者对应的cluster环境变量。

建议去nacos-k8s或者nacos-docker 项目中先试下example。

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/234740383-2baf0f40-04d2-4092-bfe1-194593730bcc.png)
明显配置有问题啊， 集群模式启动没配置集群列表。

**Comment by juda666a** [comment]
> 



> ![image](https://user-images.githubusercontent.com/37170243/234740383-2baf0f40-04d2-4092-bfe1-194593730bcc.png) 明显配置有问题啊， 集群模式启动没配置集群列表。

是的，少加了一个配置，把这一段加上就好了
![image](https://user-images.githubusercontent.com/51785878/235012967-9eeb3938-816e-4965-bd11-8f922fe88bab.png)
