### ISSUE TITLE
[Summer 2023] 为nacos-spring-boot-starter支持适配spring boot 3 / Support Springboot 3 for nacos-spring-boot-starter.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#10375]
开源之夏是由中科院软件所“开源软件供应链点亮计划”发起并长期支持的一项暑期开源活动，旨在鼓励在校学生积极参与开源软件的开发维护，培养和发掘更多优秀的开发者，促进优秀开源软件社区的蓬勃发展，助力开源软件供应链建设。

Nacos将会作为指导组织参加本次的[“开源之夏2023”](https://summer.iscas.ac.cn/)

## 背景

Spring boot 前段时间发布了Springboot3， 支持了GraalVM运行方式。 Nacos-client于2.2.1版本也支持了GraalVM编译，并配合Spring-Cloud-Alibaba发布了Springboot3的对应版本。
但是社区中有不少用户并没有使用Spring Cloud，而是依旧使用传统Springboot，而nacos-spring-boot-starter目前并不支持Springboot3，#9997 #9535 。

因此，社区希望nacos-spring-boot-starter进行升级，支持Springboot3，以满足用户的需求，方便用户在Springboot3的同时继续使用Nacos。

## 目标

在Springboot3下，nacos-spring-boot-starter正常进行动态配置和服务发现功能；同时支持GraalVM编译及运行。

## 难度
基础

## 导师
胡俊
510830970@qq.com

## 产出要求

- 升级nacos-spring-boot-starter使其支持Springboot3
- 升级nacos-spring-boot-starter使其支持GraalVM编译及运行
- 更新nacos-spring-boot-starter文档

## 能力要求

- 熟悉Java编程语言
- 熟悉Springboot运行机制
- 了解GraalVM编译及运行方式
- 熟悉markdown

----

Open Source Promotion Plan is a summer program organized by the Institute of Software Chinese Academy of Sciences and long-term supported by the Open Source Software Supply Chain Promotion Plan. It aims to encourage college students to actively participate in the maintenance and development of open source software, promote the vigorous development of open source software communities, and build the open source software supply chain together.

Nacos will join [The Summer 2023](https://summer-ospp.ac.cn/) as the mentoring organization.

## Background

Recently, Spring Boot released Spring Boot 3, which supports GraalVM runtime. Nacos-client also supports GraalVM compilation in version 2.2.1 and has released a corresponding version for Spring Boot 3 in conjunction with Spring Cloud Alibaba. However, many users in the community still use traditional Spring Boot instead of Spring Cloud, and nacos-spring-boot-starter currently does not support Spring Boot 3 (#9997 #9535).

Therefore, the community hopes that nacos-spring-boot-starter can be upgraded to support Spring Boot 3, in order to meet the needs of users and make it easier for them to use Nacos while using Spring Boot 3.

## Target 

Under Spring Boot 3, nacos-spring-boot-starter can perform dynamic configuration and service discovery functions normally, while also supporting GraalVM compilation and runtime.

## Difficulty
Basic

## Mentor
Jun Hu
510830970@qq.com

## Output Requirements

- Upgrade nacos-spring-boot-starter to support Spring Boot 3
- Upgrade nacos-spring-boot-starter to support GraalVM compilation and runtime
- Update the documentation of nacos-spring-boot-starter

## Technical Requirements

- Familiar with Java programming language
- Familiar with Spring Boot runtime mechanism
- Understand GraalVM compilation and runtime
- Familiar with writing markdown documents

**Comment by onexuan** [comment]
期待

**Comment by D1zzzY1** [comment]
老师您好 我对这个项目很感兴趣 不过没有什么开源经验 可以参与到这个项目中嘛

**Comment by hujun-w-2** [comment]
> 老师您好 我对这个项目很感兴趣 不过没有什么开源经验 可以参与到这个项目中嘛

符合https://summer.iscas.ac.cn/中的资格，有研究技术的想法，就可以报名

**Comment by D1zzzY1** [comment]
好的 老师 我去研究一下 出一版初稿发给您看看

**Comment by hujun-w-2** [comment]
如果有技术方案，可以通过开源之夏正式提交报名哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2023年5月19日(星期五) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] [Summer 2023] 为nacos-spring-boot-starter支持适配spring boot 3 / Support Springboot 3 for nacos-spring-boot-starter. (Issue #10375)





 
好的 老师 我去研究一下 出一版初稿发给您看看

**Comment by yanlongma** [comment]
Today, many projects are using springboot3 + dubbo3 as a microservices framework. so we not dependency springcloud.
Therefore, it is necessary to officially adapt springboot3 in time, otherwise it will only go down to springboot2.7.

@KomachiSion 
Think!

**Comment by dujie-js** [comment]
感觉dubbo3.0挺好，没必要切换Springcloud 这个维护感觉还是有必要的

**Comment by chenglin321** [comment]
各位大佬,最后弄好了没?

**Comment by ilaotan** [comment]
2023年都快结束了，还搞不搞？要不重新立个2025年开源之夏的flag吧 多给一年。

**Comment by hujun-w-2** [comment]
> 2023年都快结束了，还搞不搞？要不重新立个2025年开源之夏的flag吧 多给一年。

已经开发完成了，本周会发一个版本

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/releases/tag/0.3.0-RC
