### ISSUE TITLE
nacos 节点内存持续增长，最终OOM

### ISSUE THREAD

**Issue by WVenus** [alibaba/nacos#10386]
Nacos Version： 2.0.4 
节点数： 3节点
pod资源限制：  limit 16G
jVM 参数： XMX：12G ； XMS：10G  ；XMN 2G
nacos 上的注册服务数量： 700
问题现象： 在运行一段时间后，leader节点就会出现OOM 情况。

![image](https://user-images.githubusercontent.com/39941928/234232507-b5edb37c-66a3-4e3f-8949-f626cad43d02.png)

![image](https://user-images.githubusercontent.com/39941928/234232569-977a3290-1843-4449-8727-c7e7dceb2ad6.png)

![image](https://user-images.githubusercontent.com/39941928/234241588-0c2d1e65-4e55-457d-b428-ef28d9461c0a.png)

![image](https://user-images.githubusercontent.com/39941928/234241671-3e3dd97d-e601-4b12-bb48-690281918482.png)

![1682505660900](https://user-images.githubusercontent.com/39941928/234551392-5454a8f8-7a00-45aa-82c8-474e00d594bb.png)

**Comment by WVenus** [comment]
主要是我想确认一下，有哪些原因会导致线程一直创建，最终nacos oom掉，如果是业务逻辑问题，我根据得到的信息，整理一下输出提交给研发。

**Comment by KomachiSion** [comment]
看目前的内存信息可能是你的应用客户端有问题，导致推送一直失败重试。看下naming-push.log信息

**Comment by WVenus** [comment]
@KomachiSion  里面日志确实非常多，我抽取了一分钟的日志。 大佬指点一下
[naming-push.txt](https://github.com/alibaba/nacos/files/11339060/naming-push.txt)

**Comment by KomachiSion** [comment]
udp提送全部失败了， 查看下网路环境。 是不是udp无法联通， 是的话把支持推送的客户端版本改成2.0.0. 关闭掉udp推送。

**Comment by WVenus** [comment]
使用nc测试UDP，网络环境是正常的，本集群没有做网络策略的限制。  请问下还有什么问题会导致这个UDP提送失败吗？

**Comment by WVenus** [comment]
目前客户端是670多个，我尝试启动50或者100个，看看CPU和内存是不是持续增长状态。 因为UDP双向验证网络都是正常的。

**Comment by KomachiSion** [comment]
那就是多出来的那部分客户端，可能有一部分是不通的

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by GitHub42096** [comment]
I also encountered the same problem，how to solve it,
Is it really a network problem?
