### ISSUE TITLE
NacosLogging issue cause too many logback-* threads

### ISSUE THREAD

**Issue by feg545** [alibaba/nacos#10385]
**Describe the bug**
The 'NacosLogging' singleton class supports both slf4j and logback implementations, and I currently use logback.
The 'NacosLogging#loadConfiguration()' method is called in multiple places, and each time it is called, it goes into 'LogbackNacosLogging' and loads
'classpath:nacos-logback.xml', since scan="true" and scanPeriod="30 seconds" are configured in this xml, so in 'CongfigurationAction#processScanAttrib()"
A thread pool is created in the Scheduled Refresh profile.

---
`NacosLogging`单例类支持slf4j和logback两种实现，我目前使用的是logback。
`NacosLogging#loadConfiguration()`方法在多个位置被调用，每次被调用时会进入`LogbackNacosLogging`，并加载
`classpath:nacos-logback.xml`，由于这个xml中配置了scan="true", scanPeriod="30 Seconds"，因此在`CongfigurationAction#processScanAttrib()"
中会创建一个线程池定时刷新配置文件。

**Expected behavior**

1. The nacos-logback .xml in the nacos-client package can be left without configuring scan
2. Avoid multiple calls to 'NacosLogging#loadConfiguration()'

---
1. nacos-client包中的nacos-logback.xml如无必要可不配置scan
2. 避免`NacosLogging#loadConfiguration()`多次调用

**Actually behavior**
A clear and concise description of what you actually to happen.

Currently I use spring-cloud-starter-alibaba-nacos-config and spring-cloud-starter-alibaba-nacos-discovery
Both of these will call 'NacosLogging#loadConfiguration()', resulting in duplicate creation of the logback thread pool.

---
目前我使用了spring-cloud-starter-alibaba-nacos-config和spring-cloud-starter-alibaba-nacos-discovery
这两个都会调用`NacosLogging#loadConfiguration()`,导致重复创建logback线程池。

**How to Reproduce**
1. Springboot-Web project
2. The default log is slf4j + logback
3) Introduce spring-cloud-starter-alibaba-nacos-config
4) Introduction of spring-cloud-starter-alibaba-nacos-discovery
5. Start the project in debug mode and observe the thread state
---
1. springboot-web项目
2. 默认日志为slf4j + logback
3. 引入spring-cloud-starter-alibaba-nacos-config
4. 引入spring-cloud-starter-alibaba-nacos-discovery
5. debug模式启动项目，观察线程状态

**Desktop (please complete the following information):**
 - OS: Window10
 - Version nacos-client: 2021.0.4.0
 - Module: client
 - SDK: spring-cloud-starter-alibaba-nacos-config, spring-cloud-starter-alibaba-nacos-discovery

**Additional context**

**Comment by KomachiSion** [comment]
升级新版本客户端， scan的配置已经被移除了。

至于多次加载loadConfiguration的问题， 是spring的机制， 没办法处理。

**Comment by feg545** [comment]
是否可以在`LogbackNacosLogging#loadConfiguration()`中判断loggerContext是否非空，如果非空就不进行初始化？
或者先使用loggerContext#stop() 方法来释放资源

**Comment by KomachiSion** [comment]
loggerContext#stop()  不能调用， 因为这个会导致应用自身的日志配置也移除。

判断非空应该可行， 有兴趣的话可以做一下。

但是scan配置已经移除后，这个问题应该已经不存在了。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
