### ISSUE TITLE
nacos "导入配置"  has no response

### ISSUE THREAD

**Issue by HeyMagX** [alibaba/nacos#10383]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
When I click the button named "导入配置"，it doesn't work.

### Describe what you expected to happen
it will show the web of selecting which files to import

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
windows
nacos 2.2.2

**Comment by KomachiSion** [comment]
duplicate with #10318
