### ISSUE TITLE
不同网段集群搭建，服务分布注册在不同nacos中，但是相互却调不到

### ISSUE THREAD

**Issue by zhouzong** [alibaba/nacos#10393]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhouzong** [comment]
请问是必要要在同网段服务器上搭建吗

**Comment by zhouzong** [comment]
我用的是2.1.1版本

**Comment by KomachiSion** [comment]
和网段没什么关系， 互相调不到说明你网络不通。

而且看描述注册到不同nacos集群里， 那数据都是不一样的， 肯定没法互相调用。 这个属于你使用的问题了。

**Comment by wilsonwu** [comment]
这种用法比较少见，如果使用互通的网络下多个nacos注册若干服务互相调用成功的话，可以分享一下用法。
