### ISSUE TITLE
seata连接nacos集群，心跳400刷日志

### ISSUE THREAD

**Issue by white1208** [alibaba/nacos#10391]
seata连接nacos集群（3台）后，
注册到了A，后续nacos心跳（/nacos/v1/ns/instance/beat）请求发送到
B或C报400，后台一直刷日志，请求到注册A返回200

心跳报错日志
![1](https://user-images.githubusercontent.com/15647160/234487000-652c4566-f13b-4efa-9ce1-37b8a6d906d4.png)

心跳请求到注册nacos服务端
![2](https://user-images.githubusercontent.com/15647160/234487100-bb66e84f-099e-4e5f-a79a-028d1f1f7df2.png)

心跳请求到非注册nacos服务端
![3](https://user-images.githubusercontent.com/15647160/234487185-389b2562-03db-484b-95c6-99638e7053da.png)

server nacos version 2.2.2
client seata version 1.6.1

nacos docker 启动设置

![4](https://user-images.githubusercontent.com/15647160/234488266-cc12fc1b-56aa-454c-b5ab-9061e2f525e5.png)

**Comment by KomachiSion** [comment]
可能是url长度超长了，试着升级nacos-client版本到新版本。

**Comment by white1208** [comment]
> 可能是url长度超长了，试着升级nacos-client版本到新版本。
感觉不像是长度的问题啊，客户端seata内部依赖的nacos1.4.2，
我改不了啊

**Comment by shfpflyawei** [comment]
@KomachiSion 
我这边也遇到了类似问题，我使用的是nacos集群2.2.2然后seata版本是1.3.0
我的问题是微服务启动的时候，seata客户端连接nacos集群会遇到400问题，这是偶发性的，重启微服务POD 就正常，
而且只有在启动的时候会偶尔出现
![09812fc7dca8f17bf3686a7653af96e1](https://user-images.githubusercontent.com/34828547/236413728-cc347721-ab5d-4c03-8a5f-88ce165bd1f2.png)

**Comment by KomachiSion** [comment]
exclude掉nacos-client，然后增加新的版本的dependency。
