### ISSUE TITLE
nacos-client启动报错java.lang.UnsatisfiedLinkError java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.netty.channel.epoll.Native

### ISSUE THREAD

**Issue by MrCoderYu** [alibaba/nacos#10399]
**Describe the bug**
nacos-client启动报错java.lang.UnsatisfiedLinkError java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.netty.channel.epoll.Native

**Desktop (please complete the following information):**
 - OS: linux
 - Version nacos-client 2.1.0
 - Module [e.g. naming]
 - SDK grpc 1.39.0 netty 4.1.52.Final

**Comment by KomachiSion** [comment]
Please solve your app dependencies conflict.
