### ISSUE TITLE
v2.2.2版本，nacos.core.auth.enabled=true 后，仅 ROLE_ADMIN 角色才能请求 配置监听接口

### ISSUE THREAD

**Issue by 1052687889** [alibaba/nacos#10402]
由v2.2.0升级到版本v2.2.2后，POST /nacos/v1/cs/configs/listener接口必须为ROLE_ADMIN的角色才能正常响应，使用自己创建的用户请求会抛错403 forbidden。
用户配置
![image](https://user-images.githubusercontent.com/25763013/234821704-3d458e04-4c84-4a95-a1d2-f534af176641.png)
![image](https://user-images.githubusercontent.com/25763013/234821412-ce65ac85-6a67-45f4-bddf-2ac77728dca8.png)
![image](https://user-images.githubusercontent.com/25763013/234821614-0a5016cf-b045-407f-95bd-2843002e6c0f.png)
使用自己创建的账户请求响应403截图
![image](https://user-images.githubusercontent.com/25763013/234823562-a754873c-78bb-44bd-8647-4804f8e65085.png)
使用ROLE_ADMIN角色账户请求成功截图
![image](https://user-images.githubusercontent.com/25763013/234823329-75cbab8c-4408-4a72-a3f6-771c207d4a76.png)

并且把nacos回滚到v2.2.0后这个问题消失了。

**Comment by nuo010** [comment]
这个问题是怎么解决的
