### ISSUE TITLE
com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet#peers 

### ISSUE THREAD

**Issue by paulzhangcc** [alibaba/nacos#1040]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet#peers is not thread safety,
Errors may occur for java.util.ConcurrentModificationException

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
@paulzhangcc Yes, but with a tiny possibility. And the peers can recover from such exception. So it's not very urgent to make it thread-safe.
