### ISSUE TITLE
注册700个服务，nacos leader节点出现OOM

### ISSUE THREAD

**Issue by 50133142** [alibaba/nacos#10405]
nacos生产问题：
   nacos 版本： 2.0.4
   注册上的服务： 不足700个
   内存： pod limit 16G ，JVM XMX 12G  XMS 10G XMN 2G 
   现象： nacos leader 节点出现OOM，其余节点不会OOM， java_heapdump.hprof文件太大了10几个G,   MemoryAnalyzer都打不开
看nacos源码 ，也不知道哪里除了问题

**Comment by wilsonwu** [comment]
这个问题比较难弄，需要完整的日志或dump文件才能逐步分析并改进。

**Comment by wilsonwu** [comment]
好像和这个issue同出一辙，可以参考：https://github.com/alibaba/nacos/issues/10386
