### ISSUE TITLE
Nacos2.2.2 Create namespace commit prompt 403

### ISSUE THREAD

**Issue by 53517230** [alibaba/nacos#10413]
After the development of the Nacos 2.2.2 authentication plug-in is completed, the NACOS stand-alone machine starts normally, and the namespace creation cannot be authorized.

Permission authentication has been turned on
nacos.core.auth.enabled=true

**Comment by KomachiSion** [comment]
see document, the sercet.key , identity.key and identity.value must be filled with valided.

**Comment by yuanrengu** [comment]
<img width="760" alt="image" src="https://github.com/alibaba/nacos/assets/5828006/cc534068-3547-4611-8779-3706a3ee59a3">

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
