### ISSUE TITLE
Add failover config enabled switch

### ISSUE THREAD

**Issue by Daydreamer-ia** [alibaba/nacos#10418]
**Is your feature request related to a problem? Please describe.**
中文:
当我们发起 `getConfig()` 时，首先会尝试获取 `failover` 配置，并且会在 `failover` 配置存在的情况下直接启用。
但在有的时候，我们的 `failover` 配置并不是一次性的，并不希望使用完后就把`failover` 配置删除，但是如果不删除的话，获取配置就直接启用`failover` 而不是去服务端获取，这不是我们希望的。希望可以像 `Naming` 模块那样，在获取`failover` 配置之前先进行检查，在开启`failover` 模式的情况下，才去读取`failover` 配置。

Eng:
When we request to get config, it will get failover file first. It will use failover configs if they are present. Sometimes, our failover configs are not one time and we don't want to delete them after using. However, if we don't delete them, it will enable failover directly and then obtain the configs instead of request to server, which is not what we want. So we hope that adding the check for failover mode before obtaining them, just like the Naming module, and only read the failover configs when the failover mode is enabled.

 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
中文:
为了保持原有的兼容性，默认情况下`failover` 机制开启，并且在遇到任何未预料到的情况时都默认`failover` 机制开启(保持旧版本兼容)。只有在手动关闭 `failover` 机制时，才会关闭，不会再去读取`failover` 配置(即使 `failover` 配置存在)

Eng:
In order to maintain original compatibility, the failover mode is enabled by default, and is also when encountering any unexpected situations. It will be turned off only when we annotation that failover mode is manually turned off  which cause the failover configs will no longer be read (even if the failover configs exists).

**Comment by KomachiSion** [comment]
wrong understand, the failover is different with snapshot.

failover need user add failover file which client will not write it auto.

And for config, the snapshot is important, if no config, the app can't start. But naming has no data only call provider error.

So the config need force snapshot when call server failed.

**Comment by Daydreamer-ia** [comment]
> wrong understand, the failover is different with snapshot.
> 
> failover need user add failover file which client will not write it auto.
> 
> And for config, the snapshot is important, if no config, the app can't start. But naming has no data only call provider error.
> 
> So the config need force snapshot when call server failed.

thanks, i think i get it
