### ISSUE TITLE
Nacos yaml config file validator is not valid in console UI

### ISSUE THREAD

**Issue by ruansheng8** [alibaba/nacos#10416]
## BUG描述
从Nacos文档描述来看是有提供`Yaml`格式配置的校验功能, 实际测试时发现`Yaml`错误格式的配置无法被检测出
![image](https://user-images.githubusercontent.com/24709538/235345307-1d4faa02-9153-4a0d-be91-2c3bfa4ae7b1.png)

## 期望
期望可以正确识别出错误的格式, 并显示相关告警信息, 例如: 
![image](https://user-images.githubusercontent.com/24709538/235345020-caac6cda-2c72-45ad-9525-ed2411e55368.png)

## BUG复现
使用以下错误的格式(重复key)依然可以通过验证并发布, 导致程序获取时解析配置失败从而无法读取到配置.
该问题无法在业务服务解决, 因为业务服务加上了配置格式的校验会导致解析失败后无法读取到配置.

![image](https://user-images.githubusercontent.com/24709538/235344995-208007c9-be70-4cce-9afa-887fce8158aa.png)

## 版本信息
Nacos server : 2.2.2

**Comment by KomachiSion** [comment]
console 使用的开源编辑器校验的格式能力有限， 可以看下哪个开源前端组件编辑器可以支持，在开源协议许可的情况下可以升级下编辑器。

**Comment by DarrenLuo** [comment]
@i will solve it@
