### ISSUE TITLE
ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.census.InternalCensusTracingAccessor

### ISSUE THREAD

**Issue by luyanfeng** [alibaba/nacos#10428]
![图片](https://user-images.githubusercontent.com/5779510/236364097-e39daa2e-d39a-479a-9d02-58f17961a5b5.png)

Am I missing anything?

**Comment by KomachiSion** [comment]
Ignore it, the log is debug log, grpc use it to judge which code it uses.
