### ISSUE TITLE
客户端处理服务端的请求时，异常处理是否有问题？

### ISSUE THREAD

**Issue by DSSLP** [alibaba/nacos#10427]
![image](https://user-images.githubusercontent.com/57716709/236210440-c3dee231-e953-4977-8074-2348b394db94.png)

当244行和247行处理有异常时，会被其内部捕获到，而并不会被253行所捕获。因此253行并不会捕获到异常，从而不会sendResponse(errResponse)。如有误请指正，谢谢

**Comment by Bo-Qiu** [comment]
对的，此处感觉逻辑上是有问题的，客户端在com.alibaba.nacos.common.remote.client.RpcClient#handleServerRequest处理serverRequest后，若有异常会被直接捕获，并返回一个null。如此即使客户端处理server请求有异常，并不会走到io.grpc.stub.StreamObserver#onNext的catch中，立即返回server端一个ErrorResonse。而是直接不响应，等待server端认为此处推送超时后，再重新进行推送。
![image](https://github.com/alibaba/nacos/assets/46370663/e3d67ca8-6169-4a34-b1ca-c160b159750d)

**Comment by Bo-Qiu** [comment]
此处如需要进行调整，可以将其指派给我，我会在近期提一个PR以修复此问题

**Comment by horizonzy** [comment]
> 此处如需要进行调整，可以将其指派给我，我会在近期提一个PR以修复此问题

是的，的确有问题。
