### ISSUE TITLE
nacos2.2.x版本，为啥启动一会就异常了

### ISSUE THREAD

**Issue by ymwfish** [alibaba/nacos#10431]
G:\nacos-muti\nacos-server-2.2.2\nacos\bin>startup.cmd -m standalone
"nacos is starting with standalone"

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 2.2.2
,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 13132
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://169.254.102.223:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

2023-05-06 10:31:47,695 INFO Tomcat initialized with port(s): 8848 (http)

2023-05-06 10:31:47,939 INFO Root WebApplicationContext: initialization completed in 8460 ms

```
 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x00007ff8196f03a9, pid=13132, tid=13156

 JRE version: Java(TM) SE Runtime Environment (17.0.6+9) (build 17.0.6+9-LTS-190)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.6+9-LTS-190, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
 Problematic frame:
 C  [librocksdbjni1057805303790301532.dll+0x5203a9]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 G:\nacos-muti\nacos-server-2.2.2\nacos\bin\hs_err_pid13132.log

 If you would like to submit a bug report, please visit:
   https://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.
```

**Comment by richielii** [comment]
我的也是这样，求解决方案

**Comment by KomachiSion** [comment]
There must be some problem in your env and jdk version. The problem is not throw by nacos but jdk.

Maybe you jdk version is not windows version.

**Comment by MajorHe1** [comment]
java.lang.UnsatisfiedLinkError: C:\Users\majorhe\AppData\Local\Temp\librocksdbjni8806104336389244797.dll: Can't find dependent libraries

我当时nacos 2.1.x 版本运行正常， 升级到 2.2.2 的报错是这样的，跟你有点不一样，共同点是都有这个关键词 librocksdbjni.dll 的问题

可以先考虑排查一下 visual c++ redistributable 2015 是否装好，我装了之后问题解决

**Comment by CatZhao** [comment]
检查一下你的环境变量，我碰到了同样的问题。虽然 nacos 手册上说 jdk要 1.8 及以上版本，但我实测是我的 jdk 是"1.8.0_345"是不支持的。

解决办法是重新装个高版本的 jdk，然后修改 startup.sh ,加一行export JAVA_HOME=/opt/homebrew/Cellar/openjdk@17/17.0.6/libexec/openjdk.jdk/Contents/Home (改成你自己的高笨笨 jdk 安装目录。问题解决。

**Comment by KomachiSion** [comment]
我本地环境jdk版本1.8.0_361， 是没有问题的， 不清楚更老一点的jdk版本是否不支持。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by ToMySoul** [comment]
同上，版本jdk1.8  nacos2.2.2  ；删除重新解压压缩包可以解决，关闭再开启没问题，第二天启动不了。

**Comment by isdasdqwe** [comment]
我也是，standalone启动如果创建了配置文件，不按ctrl+c关闭而是直接点关闭后就报这个。如果是cluster启动，配了集群直接就报这个了
# Problematic frame:
# C  [librocksdbjni2223750722922053829.dll+0x5203a9]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

**Comment by oracle1112** [comment]
原因 librocksdbjniXXXX.dll 是nacos引入rocksDB数据存储的问题

简单粗暴的方式：

删除nacos目录下的data文件夹 ，重新启动nacos就可以了

**Comment by wbcnr** [comment]
### jdk 1.8.0_102，windows ，也会报这个错。
解决办法：删除后重新解压，再启动正常。
推测：是上一次关闭的时候没有正常关闭，直接关闭了运行窗口造成的。

**Comment by nanlaogou** [comment]
> 原因 librocksdbjniXXXX.dll 是nacos引入rocksDB数据存储的问题
> 
> 简单粗暴的方式：
> 
> 删除nacos目录下的data文件夹 ，重新启动nacos就可以了

用这个办法解决了，感谢

**Comment by raccoon7363** [comment]
删除nacos目录下的data文件夹 ，重新启动nacos就可以了


用这个方法解决了
