### ISSUE TITLE
NACOS 2.2.2 集群模式下，未开启鉴权，无法导入配置

### ISSUE THREAD

**Issue by 122468462** [alibaba/nacos#10433]
**Describe the bug**
在集群的模式下，如果未开启鉴权功能的时候，无法使用导入配置的功能。
Under the condition of the cluster, if you do not unlock the function of authentication, cannot use import configuration function.

**Expected behavior**
控制台会出现以下错误：
The console will appear the following error:
**Uncaught ReferenceError: goLogin is not defined**

**Actually behavior**
于是就在控制台运行了以下脚本，问题得以解决：
Then run the following script, the console problems are resolved:
**goLogin=function(){}**

**How to Reproduce**
1. 开启集群模式：MODE=cluster
2. 不开启鉴权：NACOS_AUTH_ENABLE=false
3. 进入Nacos配置列表页面
4. 点击导入配置

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by wilsonwu** [comment]
@KomachiSion with issue dup with? could you please add comment?
