### ISSUE TITLE
配置推送过程优化

### ISSUE THREAD

**Issue by zhwaaaaaa** [alibaba/nacos#10439]
nacos 2.x 版本做 grpc 配置 推送的时候， 只是通过 requestBiStream 推送一个 ConfigChangeNotifyRequest{dataId, group,tenant} ，并不包含 content 和 md5 。 客户端收到 dataId 之后，需要重新从发起 request -> ConfigBatchListenRequest
 才能 拿到 content 和 md5
希望可以像 订阅 naming serverlist 一样 ， ConfigChangeNotifyRequest
直接把 content 和 md5 带过来。这样客户端不用再次发起 请求，流程更加简单并且与 naming 的推送流程一致

**Comment by KomachiSion** [comment]
配置不行， 配置的content内容可能非常大，直接推送原始数据会打爆客户端。

只给md5，客户端根据自身处理能力去get比较合理。

服务的话数据量相对小一些，只要不错用，可以直接推送数据。
