### ISSUE TITLE
Python服务注册后，健康状况一时为true，一时为false

### ISSUE THREAD

**Issue by zyoung1212** [alibaba/nacos#10448]
Python服务注册后，健康状况一时为true，一时为false，而且还有离线的情况

使用的是NacosClient.send_heartbeat，每5秒发送了一次心跳，每次返回的信息为：{'clientBeatInterval': 5000, 'code': 10200, 'lightBeatEnabled': True}

nacos服务端版本为2.1.2

**Comment by KomachiSion** [comment]
1. 是不是服务端没有组成集群
2. 是不是设置了心跳超时时间小于心跳间隔

**Comment by wilsonwu** [comment]
加大超时时间试试，看看是不是网络稳定性等问题。

**Comment by zyoung1212** [comment]
> 

谢谢回答，但是我查看日志，每5秒都有心跳返回信息的（{'clientBeatInterval': 5000, 'code': 10200, 'lightBeatEnabled': True}）

**Comment by zyoung1212** [comment]
> 1. 是不是服务端没有组成集群
> 2. 是不是设置了心跳超时时间小于心跳间隔

是有集群的，而且心跳间隔5秒，每次都有返回（{'clientBeatInterval': 5000, 'code': 10200, 'lightBeatEnabled': True}），应该没有你说的这种情况吧？

**Comment by KomachiSion** [comment]
python客户端应该在注册服务后会自动进行续约， 不需要再主动调用send beat。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by xinwangu** [comment]
> 解决方案：
> 
> 孩子已经很努力寻找方案解决了，对比java注册方式，对比nacos配置中心到服务中心的方法和参数； 找到差异：【服务名】有坑 python按照nacos包的参数进行注册，配置的是：SERVICE_NAME 实际没有使用正确的服务名。正确格式改为：DEFAULT_GROUP_NAME+“@@”+SERVICE_NAME
> 
> client.send_heartbeat(service_name=DEFAULT_GROUP_NAME+"@@"+SERVICE_NAME, ip=SERVICE_IP, port=SERVICE_PORT) 1
> 
> ———————————————— 版权声明：本文为CSDN博主「砰然已心动」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。 原文链接：https://blog.csdn.net/MJ_Zm/article/details/127802203

你好，目前没有支持2.X版本的python sdk吧？我是用的v2版本的API去注册和发送心跳（每5秒），SERVICE_NAME也是用的上述所说的格式，但是有时还是出现健康实例数减少或者实例数减少的问题。在nacos的服务列表一直手动刷新该列表页,实例数和健康实例数不稳定，会一直变，请问你出现这个问题了吗

**Comment by xinwangu** [comment]
> > 解决方案：
> > 孩子已经很努力寻找方案解决了，对比java注册方式，对比nacos配置中心到服务中心的方法和参数； 找到差异：【服务名】有坑 python按照nacos包的参数进行注册，配置的是：SERVICE_NAME 实际没有使用正确的服务名。正确格式改为：DEFAULT_GROUP_NAME+“@@”+SERVICE_NAME
> > client.send_heartbeat(service_name=DEFAULT_GROUP_NAME+"@@"+SERVICE_NAME, ip=SERVICE_IP, port=SERVICE_PORT) 1
> > ———————————————— 版权声明：本文为CSDN博主「砰然已心动」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。 原文链接：https://blog.csdn.net/MJ_Zm/article/details/127802203
> 
> 你好，目前没有支持2.X版本的python sdk吧？我是用的v2版本的API去注册和发送心跳（每5秒），SERVICE_NAME也是用的上述所说的格式，但是有时还是出现健康实例数减少或者实例数减少的问题。在nacos的服务列表一直手动刷新该列表页,实例数和健康实例数不稳定，会一直变，请问你出现这个问题了吗

应该是解决了，我把使用的注册，发送心跳V2接口改为了调用V1接口就可以了

**Comment by dreamycloud** [comment]
nacos 2.2.1，一样的问题，经测试发现传group_name参数就会有问题，不传就正常
