### ISSUE TITLE
nacos长连接压测跟官网提供数据相差甚远

### ISSUE THREAD

**Issue by dongduang** [alibaba/nacos#10446]
问题：目前只压测了单节点，官网单节点长连接可达9000，现只压到3500

主机配置：cpu核数及内存均大于官网提供的8核，16G（未关注数据库配置，跟这有关吗？）
nacos server版本：2.2.1
压测工具：jemeter
压测方式：http方式；ip:port/nacos/v1/cs/configs/listener；Long-Pulling-Timeout=60000
压测过程：
1. nacos server启动参数：-Xmx=2G 长连接不到2000，节点就挂掉了，nacos server log ->  java.lang.OutOfMemoryError: Java heap space
2. nacos server启动参数：-Xmx=4G 长连接不到2700，节点就挂掉了，nacos server log ->  java.lang.OutOfMemoryError: Java heap space
3. nacos server启动参数：调整启动参数使用跟官网一样的jvm配置，长连接不到3500，节点就挂掉了，nacos server log ->  java.lang.OutOfMemoryError: Java heap space
![image](https://user-images.githubusercontent.com/44309094/236763839-bed397f7-6933-4f5f-85f4-f94a81ad1d01.png)

**Comment by KomachiSion** [comment]
你是不是对长连接有什么误解。。

你这个压测是长轮训。。不是长连接

长连接指的是grpc连接数。

**Comment by dongduang** [comment]
那我应该如何去压测出这个长连接的容量呢？

**Comment by wilsonwu** [comment]
需要看一下压测手段是什么样的，之前压测过几轮，发现最终自己写一个压测程序才能正常压到类似官方的数据效果。

**Comment by KomachiSion** [comment]
> 那我应该如何去压测出这个长连接的容量呢？

部署多个施压机， 每个施压机创建N个nacosclient进行连接。

**Comment by dongduang** [comment]
ConfigService configService = NacosFactory.createConfigService(properties);
configService.addListener(..);
用官网java sdk这种方式创建多次来验证容量吗？

**Comment by KomachiSion** [comment]
对，差不多，一个ConfigService就是一条长连接， 单台机器可以依据配置发布200～500不等的长连接。

实际使用的时候一般单台pod不会超过2～4条

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
