### ISSUE TITLE
客户端获取加密配置，客户端对配置内容计算的MD5值和nacos服务端对配置内容计算的MD5值不一致，导致一直longPolling

### ISSUE THREAD

**Issue by gdutLiang** [alibaba/nacos#10447]
**Describe the bug**

- nacos服务端:

使用aes加密配置获得的MD5如下：
`md5=b2ed7b4e88bd4912a17d7db8fa141eeb`

- 客户端：

引入的包
```
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2021.1</version>
</dependency>
```
获取使用aes加密配置获得的MD5如下：
` md5=a355df68a2634f255441965d724e9bb4`

客户端和服务端的对配置内容计算的MD5不一致，导致客户端对nacos服务端并没有更新的配置一直[com.alibaba.nacos.client.Worker.longPolling]

**Expected behavior**
nacos中加密的配置不更新情况下，客户端不应该一直去nacos服务端拉取配置

**Actually behavior**
nacos中加密的配置不更新情况下，客户端一直去nacos服务端拉取配置

**How to Reproduce**
1. nacos服务端创建cipher-aes-test.properties配置文件。配置内容任意
2. 客户端使用spring-cloud-starter-alibaba-nacos-config获取加密的配置文件
3. 观察客户端日志，发现日志一直刷新，如下：
```
 [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.16.97_8848-sit] com.alibaba.nacos.client.config.impl.ClientWorker >> get changedGroupKeys:[cipher-aes-test.properties+public+sit]
2023-05-08-17:09:14.190 [INFO ] [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.16.97_8848-sit] com.alibaba.nacos.client.config.impl.ClientWorker >> [fixed-192.168.16.97_8848-sit] [data-received] dataId=cipher-aes-test.properties, group=public, tenant=sit, md5=a355df68a2634f255441965d724e9bb4, content=app.test.config.aesName=CCmm
app.test.config.aesCompany=google.com, type=properties
```

**Desktop (please complete the following information):**
 - OS: Centos
 - Version  [nacos-server 2.2.1]
 - Module  [config]
 - SDK [spring-cloud-starter-alibaba-nacos-config]

**Additional context**
初步分析原因：
客户端读取加密的配置文件，计算MD5值使用的是解密后的配置内容，而nacos服务端保存发布配置文件计算MD5的值使用的是加密后的配置内容。导致客户端和服务端对配置内容计算的MD5值不一致，客户端认为当前加密的配置文件被更新了，所以一直往服务端拉取配置

**Comment by CherishCai** [comment]
nacos-client 是哪个版本？

**Comment by CherishCai** [comment]
可能存在它 引入的 nacos-client  版本过低，建议覆盖成最新版本试试
```xml
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2021.1</version>
</dependency>
```

**Comment by gdutLiang** [comment]
引入新版本nacos-client已解决问题
```
<dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.2.1</version>
</dependency>
```
