### ISSUE TITLE
阿里云的SLB和nacos2.2的冲突

### ISSUE THREAD

**Issue by pengkang1991** [alibaba/nacos#10443]
- Version：nacos 2.2
nacosclient无法通过SLB连接nacos集群
8848，9848，9849 3个端口都是开通的，用本地nginx做负载均衡没有问题，用SLB就连接不上。

我在阿里云服务器上搭建了一个nacos集群服务，然后使用SLB作为负载均衡。如下：
nacos01:8848
nacos02:8848      <-------------- nacosSLB
nacos03:8848
应用程序调用nacosSLB却请求不上，debug发现是 nacosSLB:9848端口不通的问题，于是又做了一个辅助，如下：
nacos01:9848
nacos02:9848      <-------------- nacosSLB:9848
nacos03:9848
然后还是报错，nacosSLB:9848是通了，但是还是报错，经调试发现是nacosSLB:9848 无法返回 nacos01:9848 的200信息.

阿里云那边反馈是 阿里云的slb有回访的问题，也就是slb代理的服务器不能反向访问SLB，是否会因此导致 nacosclient无法通过SLB连接nacos集群，。

**Comment by jaimyjie** [comment]
8848，9848，9849 3个端口都打开通试试

**Comment by pengkang1991** [comment]
> 8848，9848，9849 3个端口都打开通试试

8848，9848，9849 3个端口都是开通的，用本地nginx做负载均衡没有问题，用SLB就连接不上。

**Comment by jaimyjie** [comment]
1. SLB端口 必须跟nacos端口一致，如SLB用8848，nacos端也必须是8848，不能用其他端口对应关系
2. 用TCP协议

**Comment by pengkang1991** [comment]
> 1. SLB端口 必须跟nacos端口一致，如SLB用8848，nacos端也必须是8848，不能用其他端口对应关系
> 2. 用TCP协议

你好，你的意思是这样吗，不能使用（SLB）config.nacos.con 的443端口是吧，而是像下面那样设置是吧，如下：。
nacos01:8848
nacos02:8848 <-------------- config.nacos.con:8848
nacos03:8848

那9848端口的代理是否也要配置呢，如下：
nacos01:9848
nacos02:9848 <-------------- config.nacos.con:9848
nacos03:9848

**Comment by pengkang1991** [comment]
报错了： NacosException: http error, code=403,msg=unknown user
配置如下：

nacos01:8848
nacos02:8848 <-------------- （https）config.nacos.con:8848
nacos03:8848

**Comment by KomachiSion** [comment]
阿里云自己卖的nacos就使用 slb做前端负载的，不可能不能用，应该还是哪里设置有问题

**Comment by KomachiSion** [comment]
It seems has solved problem, the new error info is auth not users. not issue problem.
