### ISSUE TITLE
注册370-380 左右 单机版nacos服务就挂了

### ISSUE THREAD

**Issue by 50133142** [alibaba/nacos#10449]
注册370-380实例左右 单机版nacos服务就挂了，
nacos版本2.0.4
CPU 快 3000% 多时候就打不开页面了 。内存只耗了不到2G
![image](https://user-images.githubusercontent.com/42038247/236797376-89c5eab3-4741-446a-84e1-4ad54994639d.png)
注册实例配置了如下参数，加大心跳间隔时间
metadata:
          preserved.heart.beat.interval: 19000 #心跳间隔。时间单位:毫秒。心跳间隔
          preserved.heart.beat.timeout: 30000 #心跳暂停。时间单位:毫秒。 即服务端6秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.ip.delete.timeout: 30000 #Ip删除超时。时间单位:毫秒。即服务端9秒收不到客户端心跳，会将该客户端注册的实例删除：

**Comment by KomachiSion** [comment]
jvm参数如何设置？
cpu占比这么高， 可以打一下火焰图看下cpu消耗在哪里。
注册实例的方式是什么？ 不停的registerInstance吗？

**Comment by wilsonwu** [comment]
我看截图里面内存好多，cpu本身是有多少？是不是cpu本身不够？

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
