### ISSUE TITLE
希望加入多人协作编辑配置功能【编辑并发问题】

### ISSUE THREAD

**Issue by chenghegui** [alibaba/nacos#10460]
## 希望加入多人协作编辑配置功能
目前存在以下问题：
1. 多人同时编辑，后一个人提交的配置丢失前一个人提交的配置问题；
2. 打开的配置编辑页面一段时间，不刷新的情况下，期间有其他人提交该配置文件，此时再修改该配置文件，依然可以提交，将会覆盖前一个人提交的配置
3. 
复现：
1.在谷歌浏览器打开编辑配置文件
2.在edge浏览器也打开同一个配置文件
4.在谷歌浏览的新增配置，提交
5.在edge也新增配置，提交
6.步骤3提交的配置丢失了

### 希望加入提交校验：
1.  提交时判断，修改的文件是否是最新版本文件，若不是最新版本，则提示有版本更新，拒绝提交。
2. 
 nacos 1.4.1

**Comment by wilsonwu** [comment]
按照目前的设计要实现协作编辑难度有点大，从配置本身的原则来看尽可能将配置颗粒度划小，避免大量配置堆在一个配置文件中，这样有助于控制读取效率和更新推送后的影响，所以从这个角度来看，协作编辑也就没有那么高的要求了。

**Comment by KomachiSion** [comment]
以前社区也讨论过这个问题。这个问题实际上是管理问题。及时是其他产品也基本都不会包含这个功能， 因为数据的设计就是将修改结果覆盖。 同样的如ZK等产品，也有一样的问题，先查询出来，然后等一段时间再基于结果修改后再写入数据， 也存在一样的覆盖问题，一般这里的并发问题指的是， 并发同时发起修改请求，保证修改的内容不会串， 而不会管2个内容之间是否冲突。

如果你需要对配置进行多人协作， 应该要用的是类似git的工具，在开发环境中进行协作。 在生产环境中应该只以最终版本为准。

**Comment by chenghegui** [comment]
好的 多谢各位大佬  我目前的操作简直做了前端md5的值比较校验，能勉强解决这个情况

**Comment by 985492783** [comment]
> 以前社区也讨论过这个问题。这个问题实际上是管理问题。及时是其他产品也基本都不会包含这个功能， 因为数据的设计就是将修改结果覆盖。 同样的如ZK等产品，也有一样的问题，先查询出来，然后等一段时间再基于结果修改后再写入数据， 也存在一样的覆盖问题，一般这里的并发问题指的是， 并发同时发起修改请求，保证修改的内容不会串， 而不会管2个内容之间是否冲突。
> 
> 如果你需要对配置进行多人协作， 应该要用的是类似git的工具，在开发环境中进行协作。 在生产环境中应该只以最终版本为准。

apollo的话应该是有这个功能，后覆盖的会报错，其实我们也可以做，因为已经有publishConfigCas这个接口了，也可以添加一个字段判断一下是否需要管理，需要管理就走CAS端口，不需要就走publishConfig

**Comment by wilsonwu** [comment]
> > 以前社区也讨论过这个问题。这个问题实际上是管理问题。及时是其他产品也基本都不会包含这个功能， 因为数据的设计就是将修改结果覆盖。 同样的如ZK等产品，也有一样的问题，先查询出来，然后等一段时间再基于结果修改后再写入数据， 也存在一样的覆盖问题，一般这里的并发问题指的是， 并发同时发起修改请求，保证修改的内容不会串， 而不会管2个内容之间是否冲突。
> > 如果你需要对配置进行多人协作， 应该要用的是类似git的工具，在开发环境中进行协作。 在生产环境中应该只以最终版本为准。
> 
> apollo的话应该是有这个功能，后覆盖的会报错，其实我们也可以做，因为已经有publishConfigCas这个接口了，也可以添加一个字段判断一下是否需要管理，需要管理就走CAS端口，不需要就走publishConfig

同时编辑，后提交的会报错这个是有必要的功能，只要提交的时候验证一下开始编辑时缓存的内容是否与最新内容相同就可以实现，比较容易，也比较有用。

**Comment by KomachiSion** [comment]
CAS接口只能保证同时提交的时候，后提交的报错。 但是解决不了issue中的场景，即AB同时获取旧版本，A提交完成后，B再提交。

**Comment by 985492783** [comment]
> CAS接口只能保证同时提交的时候，后提交的报错。 但是解决不了issue中的场景，即AB同时获取旧版本，A提交完成后，B再提交。

控制台打开配置的时候获取md5，然后提交修改的时候把这个md5带上做CAS，就不会出现两个人同时修改一份配置了，但是运维接口有点难搞

**Comment by yuanrengu** [comment]
本质上是管理问题，通过管理手段去解决会更直接。

**Comment by chenghegui** [comment]
目前实现方案【无需重启nacos服务器】：
1. 修改前端代码，在提交前拉取一次最新版本md5【使用的现有接口】；
2. 比较md5是否等于编辑配置文件版本的md5，相等则说明是最新版，可直接提交；否则，提示是否拉取最新配置，点击确认，则将最新的content填充进来，刚编辑的内容需要重新填写；点击取消，则取消本次修改；
3. 前端代码打包部署在ngnix，后面通过nginx地址登录访问配置中心。

**Comment by 985492783** [comment]
> 目前实现方案【无需重启nacos服务器】：
> 
> 1. 修改前端代码，在提交前拉取一次最新版本md5【使用的现有接口】；
> 2. 比较md5是否等于编辑配置文件版本的md5，相等则说明是最新版，可直接提交；否则，提示是否拉取最新配置，点击确认，则将最新的content填充进来，刚编辑的内容需要重新填写；点击取消，则取消本次修改；
> 3. 前端代码打包部署在ngnix，后面通过nginx地址登录访问配置中心。

你这做法只能解决并发提交的情况，但是解决不了并行提交，两个人同时提交获取同一个md5导致两个人都可以提交，如果要做，必须调用publishConfigCAS这个接口才行

**Comment by chenghegui** [comment]
> 

是的，同一时刻提交的概率远远小于同时编辑，已经能满足我司的情况，目前在源码里面没有看到publishConfigCAS接口
