### ISSUE TITLE
NACOS 2.3.0-SNAPSHOT启动后打开nacos界面，v1/console/server/announcement 接口报500

### ISSUE THREAD

**Issue by Az-Captain** [alibaba/nacos#10463]
**Describe the bug**
After start nacos server,open chrome visit localhost:8848/nacos ,Open Google browser, enter the page to prompt the interface to report error information [caused: Handler dispatch failed;nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;caused: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;]

![image](https://github.com/alibaba/nacos/assets/70265420/362ba3db-9089-4238-b252-733f532c0307)
![image](https://github.com/alibaba/nacos/assets/70265420/7c719125-caf8-4856-9553-0093aeee7f0a)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/6821c689-f4cb-4464-a38d-5ea7cbf731e4)

I test it can found the api can return value normally. Maybe your env has problem.

From your error info, `java.lang.NoSuchMethodError` maybe your deploy with dependency conflict so that the nio class is different.

**Comment by youkuzazazazaza** [comment]
我使用的是zulu8.74.0.17-ca-jdk8.0.392-linux_aarch64也存在这个问题，请问您解决了吗。
