### ISSUE TITLE
english version bug in some UIs

### ISSUE THREAD

**Issue by figoisxjs** [alibaba/nacos#10470]
![image](https://github.com/alibaba/nacos/assets/1586021/8da5cde1-7eb7-41a8-9636-0147c5662ab5)
![image](https://github.com/alibaba/nacos/assets/1586021/ca273612-c1ce-43e1-89f8-49bc284fb9ef)
![image](https://github.com/alibaba/nacos/assets/1586021/2cb6723f-289e-4408-8c5f-78080dd7182e)
 some Chinese field descriptions in English UI

**Comment by wilsonwu** [comment]
Thanks for your report, PR submitted to fix it. https://github.com/alibaba/nacos/pull/10472
