### ISSUE TITLE
Seata 客户端获取 Nacos 配置，提示配置数据不存在

### ISSUE THREAD

**Issue by hzy970907** [alibaba/nacos#10477]
JDK Version：8
Seata Version：1.6.0
Nacos Version：2.0.4
Dubbo Version：3.0.3

Seata 客户端获取配置，提示config data not exist。

![image](https://github.com/alibaba/nacos/assets/26761454/9b24a564-d591-4faa-9111-a99298474fda)
![image](https://github.com/alibaba/nacos/assets/26761454/c0b373bd-0423-4c0c-9a67-2d04112d7de6)
![image](https://github.com/alibaba/nacos/assets/26761454/51e3b7db-975a-4146-b775-79bc715939e1)
![image](https://github.com/alibaba/nacos/assets/26761454/a6890fe8-03f7-447f-986c-31b41b56d8cd)

Seata 的 registry 和 config 我选用 Nacos，Nacos 配置列表里存在此配置，通过debug对比，dataId、group、namespace都能对上，但是响应结果提示 config data not exist。

**Comment by liuchaojie-work** [comment]
namespace:  不要设置public,直接空着

**Comment by hzy970907** [comment]
好的，感谢，解决了
