### ISSUE TITLE
建议优化

### ISSUE THREAD

**Issue by wangshengji** [alibaba/nacos#10474]
1. com.alibaba.nacos.config.server.service.repository.ConfigInfoPersistService#createPaginationHelper 代码实现每次调用都会创建一个新对象

2. com.alibaba.nacos.config.server.utils.ResponseUtilTest    java: 程序包sun.security.action不存在 。跑test代码的时候报错的。 jdk版本 graalvm17

**Comment by KomachiSion** [comment]
1. 如果不是每个请求创建一个独立对象， 公用对象在并发请求处理时可能有线程安全问题。
2. com.alibaba.nacos.config.server.utils.ResponseUtilTest java:没有依赖sun.security.action

**Comment by Daydreamer-ia** [comment]
i will resolve it
