### ISSUE TITLE
nacos客户端过SLB后频繁掉线

### ISSUE THREAD

**Issue by smallhorsegg** [alibaba/nacos#10476]
1. 之前客户端都是走集群svc访问naocs一切正常。
2. 迁移部分业务后  访问路径改为   pod-slb-nginx controller-svc   频繁掉线            已经把nginx-controller中  proxy_timout注释

**Comment by KomachiSion** [comment]
那就需要你看下slb的设置是否有问题了，导致链接一直断开或者访问异常。

2.x客户端的话， nginx设置一定要设置成tcp转发，不能设置成http或http2

**Comment by guozongkang** [comment]
SLB和server集群建立的grpc长连接是无状态的，但是nacos 客户端维护的grpc连接是有connectionId的

**Comment by KomachiSion** [comment]
如果是无状态的说明你slb的设置不对， 设置成http了， 如果设置的是tcp的话是一一对应的。

**Comment by guozongkang** [comment]
> 如果是无状态的说你slb的设置不对，设置成http了，如果设置的是tcp的话是一一对应的。

已经设置成TCP了。  你说的slb是指 clb还是alb。   clb应该是可以的。 但是alb会出问题

**Comment by smallhorsegg** [comment]
> > 如果是无状态的说你slb的设置不对，设置成http了，如果设置的是tcp的话是一一对应的。
> 
> 已经设置成TCP了。 你说的slb是指 clb还是alb。 clb应该是可以的。 但是alb会出问题

目前我用的是CLB   后面挂了ingress    客户端通过ingress访问nacos集群。

**Comment by smallhorsegg** [comment]
> > 如果是无状态的说你slb的设置不对，设置成http了，如果设置的是tcp的话是一一对应的。
> 
> 已经设置成TCP了。 你说的slb是指 clb还是alb。 clb应该是可以的。 但是alb会出问题

但是我现在用tcpservice也不行，把nacos所有的tcp端口全部放到clb中  还仍然掉线。

**Comment by KomachiSion** [comment]
那是不是ingress有问题导致的？ 我自己设置的ng是ok的。

**Comment by smallhorsegg** [comment]
> 那是不是ingress有问题导致的？ 我自己设置的ng是ok的。

已经把ingress去掉  直接走4层lb试试

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
