### ISSUE TITLE
editor.main.js在linux服务器不能完全加载成功，Http报错206

### ISSUE THREAD

**Issue by pipi2142001** [alibaba/nacos#10484]
nacos版本：2.0.4
部署在一台Linux服务器上，可以登录访问，但在配置详情里无法配置内容，F12查看是editor.main.js没有完全加载，http请求报错206【editor.main.js是1.8M，其他小的js文件可以正常加载】：
![image](https://github.com/alibaba/nacos/assets/2289204/7bde3c4a-0bf2-40a9-8524-ce83acd1b858)
换了几个版本的nacos，也是一样的 问题

但是部署在其他linux服务器，又是正常的。
![image](https://github.com/alibaba/nacos/assets/2289204/78e9c6f7-ecfa-4610-84f7-895d7d00a0e0)

这八成是服务器配置问题，但问了运维，他们说没查出问题。
请问有遇到过这问题吗？有好的建议么？谢谢

**Comment by onewe** [comment]
中间是否经过 ng 代理?

**Comment by KomachiSion** [comment]
nacos应该没有这方面配置， 估计是网络或者网络代理的设置限制了传递大js？ 可以试着抓包分析一下，在那一层中断了。

**Comment by pipi2142001** [comment]
> 中间是否经过 ng 代理?

没有NG代理。
在网上查了NG的是有类似设置可以解决：
proxy_buffer_size 128k;
proxy_buffers   32 128k;
proxy_busy_buffers_size 128k;

**Comment by KomachiSion** [comment]
那就得看linux服务器的各种系统参数有什么区别了。

**Comment by KomachiSion** [comment]
环境问题只能自行多排查了。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
