### ISSUE TITLE
nacos2.2.2版本关于使用oracle插件提示No DataSource Set的问题

### ISSUE THREAD

**Issue by changs0115** [alibaba/nacos#10481]
数据源配置如下：
![image](https://github.com/alibaba/nacos/assets/39237753/fd7d4225-49ad-40de-9d71-8fd8bd508873)

运行.\startup.cmd -m standalone后提示No DataSource Set
![image](https://github.com/alibaba/nacos/assets/39237753/f6aa6ecd-a141-4245-858d-cdc67cac8752)

**Comment by onewe** [comment]
引入了 oracle 数据源插件没？

**Comment by changs0115** [comment]
oracle插件及驱动包已放在nacos的home目录下的plugins目录下
![image](https://github.com/alibaba/nacos/assets/39237753/6328ea35-4956-4536-a515-37f9d42259ae)

**Comment by onewe** [comment]
从这个日志来看我判断不出问题所在, 建议您本地debug 一下

**Comment by onewe** [comment]
看日志 貌似数据源插件是加载到了, 可能在初始化 dataSource 的时候报错了, 可以看看其他的错误日志

**Comment by changs0115** [comment]
JdbcTemplate没有设置DataSource
![image](https://github.com/alibaba/nacos/assets/39237753/c6485296-43c7-4519-ab03-9e7d3815135c)

**Comment by onewe** [comment]
`db.pool.config.connectionTestQuery=SELECT * FROM dual` 属性是否配置

**Comment by tomlikeyou** [comment]
> `db.pool.config.connectionTestQuery=SELECT * FROM dual` 属性是否配置

请问这个配置信息需要在哪里配置

**Comment by onewe** [comment]
application.properties 里面,由于数据库不同 testQuery 也需要跟着更改

**Comment by Sulbsld** [comment]
13 May 2023 Cmt 12:19 tarihinde changs0115 ***@***.***> şunu
yazdı:

**Comment by changs0115** [comment]
> 
配置了。
db.pool.config.connectionTestQuery=SELECT * FROM dual

**Comment by changs0115** [comment]
> application.properties 里面,由于数据库不同 testQuery 也需要跟着更改

配置了一样的报错

**Comment by tomlikeyou** [comment]
> > application.properties 里面,由于数据库不同 testQuery 也需要跟着更改
> 
> 配置了一样的报错
可以排查一下是否是jdk版本问题，本地之前使用jdk8.162失败，后更改为8.371成功。

**Comment by KomachiSion** [comment]
看下config-fatal.log 中有没有一些信息。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a plugin implement problem.

**Comment by dylan-tao** [comment]
> 数据源配置如下： ![image](https://private-user-images.githubusercontent.com/39237753/238124522-fd7d4225-49ad-40de-9d71-8fd8bd508873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTAwMzIsIm5iZiI6MTcxNTYwOTczMiwicGF0aCI6Ii8zOTIzNzc1My8yMzgxMjQ1MjItZmQ3ZDQyMjUtNDlhZC00MGRlLTlkNzEtOGZkOGJkNTA4ODczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE0MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjOTJhOGVjMGE0NTMzMWQxOGQ2YTdmNzNmZDhlNTU5NjE3MWVkZTBiOGI4NDdmZmQ2MTI1Mzk5ZDUzMGRhNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YRQ2gyl5eI9xStXgU1TUjm1vIecQJwxemdRyAROR89E)
> 
> 运行.\startup.cmd -m standalone后提示No DataSource Set ![image](https://private-user-images.githubusercontent.com/39237753/238124472-f6aa6ecd-a141-4245-858d-cdc67cac8752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTAwMzIsIm5iZiI6MTcxNTYwOTczMiwicGF0aCI6Ii8zOTIzNzc1My8yMzgxMjQ0NzItZjZhYTZlY2QtYTE0MS00MjQ1LTg1OGQtY2RjNjdjYWM4NzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE0MTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkODNiNjUzZDZkNzc5YzRiNzM3NGJmMzBmNzM5YzQ0NTE4YzdlZjBmMTU3M2VhMjUyNjg0OTcwMjRhY2FmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BX-MZ0u6koGaFQh5JpiwW7F9LIr4xIf2pxvAmRwCSLI)

nacosplus来啦，针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
