### ISSUE TITLE
订阅服务时是否应该忽略集群顺序

### ISSUE THREAD

**Issue by ldyedu** [alibaba/nacos#10483]
使用 Java SDK 订阅逻辑集群时，可以传入一个集群列表。但如果同一个 `NamingService` 先后以 `A,B` 和 `B,A` 的集群顺序订阅服务，除了初次订阅时 `A,B` 的 `EventListener` 会被调用，之后服务端推送的信息都会标记 `B,A` 集群，且只有 `B,A` 的 `EventListener` 会被调用了。

因为订阅集群时的顺序不同， `InstancesChangeNotifier` 在执行 `registerListener()`方法时会生成不同的 key，比如`DEFAULT_GROUP@@myService@@A,B`和 `DEFAULT_GROUP@@myService@@B,A`，这会被认为是两个不同的订阅。

但是在逻辑上感觉订阅集群时不应该考虑集群的顺序，集群的不同顺序还会浪配一些资源，比如 `ServiceInfoHolder` 会对各种排列顺序的 `ServiceInfo` 都进行缓存，像是`A,B,C`,`B,A,C`,`C,A,B`等等，实际上它们订阅的都是同一组集群。

订阅服务时是否应该忽略集群的顺序，比如先对集群列表按字典序排序，相同集群组生成一致的 `clusterString`，然后再注册监听器和发起订阅。

``` Java
    @Override
    public void subscribe(String serviceName, String groupName, List<String> clusters, EventListener listener)
            throws NacosException {
        if (null == listener) {
            return;
        }
        Collections.sort(clusters); // 先对 clusters 排序
        String clusterString = StringUtils.join(clusters, ",");
        changeNotifier.registerListener(groupName, serviceName, clusterString, listener);
        clientProxy.subscribe(serviceName, groupName, clusterString);
    }
```
![ServerInfo](https://github.com/alibaba/nacos/assets/112548822/95372211-b29b-4101-a1f1-9060b095c17f)

![EventListener](https://github.com/alibaba/nacos/assets/112548822/d50bc453-7e83-4759-94be-5962c7781c9e)

Nacos 版本：2.2.2
JDK 版本：1.8.0_202
操作系统：Windows 11

**Comment by Daydreamer-ia** [comment]
hey，你好，这里的问题将会在新版本中修复，并且这里会在修复后提供更大的灵活性！！

**Comment by KomachiSion** [comment]
refer to #10374

**Comment by KomachiSion** [comment]
目前应该是有序的，不同的cluster内容会被当作不同的2个订阅。

会通过#10374 进行一定程度解决并给予可拓展的能力。
