### ISSUE TITLE
nacos2.2.2 控制台权限控制失效

### ISSUE THREAD

**Issue by zhaobo3k** [alibaba/nacos#10489]
新装2.2.2并启动服务后，控制台完全不需要用户密码认证，直接进入，配置并没修改，只改了个端口号；
印象中0.8版本以后用户名密码是必须的吧？
同一个版本在另一台机器上是正常的

**Comment by Daydreamer-ia** [comment]
`nacos.core.auth.enabled=false` 默认关闭的

**Comment by KomachiSion** [comment]
Please see change log and release blog.

After 2.2.2 when auth disabled, the login page is removed. (Because your auth has closed, login page will misleading users).

**Comment by zhaobo3k** [comment]
ok!
