### ISSUE TITLE
远程注册成功后，然后不知名的注册本地服务

### ISSUE THREAD

**Issue by ghj1040110333** [alibaba/nacos#10482]
![image](https://github.com/alibaba/nacos/assets/27838019/13b84fd5-0137-4f3d-afca-9035ebcde2a9)

**Comment by Daydreamer-ia** [comment]
`Client not connected, current status: STARTING` 检查一下客户端和服务端连接是否正常

**Comment by ghj1040110333** [comment]
多谢您的回答。

**Comment by ghj1040110333** [comment]
但是有一个疑问，服务是部署在linux系统上，客户端在windows系统可以注册成功，但是客户端在linux系统上报上面错误

**Comment by KomachiSion** [comment]
那就是环境问题了， 是不是windows的机器网络可以通， linux的机器网络不能通。

**Comment by alone-ship** [comment]
客户端成功注册到服务端，但有个问题，客户端配置了server-addr=ip:端口它还是会去请求本地的127.0.0.1，导致一直在报错

**Comment by KomachiSion** [comment]
那就是应用自身问题了， 看下是否还有别的组件或者代码，自己创建了个nacos的client，然后请求127.0.0.1.  可以自己debug或者dump内存排查。

**Comment by alone-ship** [comment]
原来是我在项目的根pom文件中导入的config和bootstrap，移除掉就没有那个问题了

**Comment by alone-ship** [comment]
找到原因了，原来是config配置好像不能写在application，只能写在bootstrap里面，我把application.yml换成bootstrap.yml后完全没有问题了

**Comment by KomachiSion** [comment]
> 找到原因了，原来是config配置好像不能写在application，只能写在bootstrap里面，我把application.yml换成bootstrap.yml后完全没有问题了

这个是spring cloud的规范， 一个用于启动初始化， 一个是应用配置。nacos属于启动初始化那一类。
