### ISSUE TITLE
nacos元数据删除不了

### ISSUE THREAD

**Issue by wangenji2015** [alibaba/nacos#10495]
nacos后台管理中，元数据有多个字段，删除其中一个，还显示存在

**Comment by wangenji2015** [comment]
在application.yml配置的metadata，在服务管理界面，编辑，无法删除元数据

**Comment by KomachiSion** [comment]
元数据是由客户端注册上来的运行时数据吗？ 那样是无法删除的，可以通过覆盖注册进行修改和删除。

原因：metadata分为运行时数据和运维时数据，运行时数据是客户端在注册时带上的实例的metadata，运维时数据是运维人员通过openAPI或者控制台进行修改和添加的元数据，元数据冲突时运维时数据具有更高优先级。通过API删除的元数据只能是运维时数据。

这么做的原因主要是：
如果允许删除了运行时数据，当出现客户端闪断等情况， 服务端删除了实例后再根据心跳或补偿等方式重新注册时， 数据任然以运行时的为准，被删除的数据还是会存在（因为是临时的实例），运维时数据是运维人员根据实际情况编辑的，会进行记忆和持久化。

综上，如果元数据是客户端自己注册上来的，那就需要客户端来删除，如果是通过API添加的元数据，通过API修改。

**Comment by wangenji2015** [comment]
> 元数据是由客户端注册上来的运行时数据吗？ 那样是无法删除的，可以通过覆盖注册进行修改和删除。
> 
> 原因：metadata分为运行时数据和运维时数据，运行时数据是客户端在注册时带上的实例的metadata，运维时数据是运维人员通过openAPI或者控制台进行修改和添加的元数据，元数据冲突时运维时数据具有更高优先级。通过API删除的元数据只能是运维时数据。
> 
> 这么做的原因主要是： 如果允许删除了运行时数据，当出现客户端闪断等情况， 服务端删除了实例后再根据心跳或补偿等方式重新注册时， 数据任然以运行时的为准，被删除的数据还是会存在（因为是临时的实例），运维时数据是运维人员根据实际情况编辑的，会进行记忆和持久化。
> 
> 综上，如果元数据是客户端自己注册上来的，那就需要客户端来删除，如果是通过API添加的元数据，通过API删除。

好的，谢谢，覆盖注册只能通过修改配置重启服务进行吗

**Comment by zhousw** [comment]
我也碰到这个问题，重新注册后元数据不会更新，端口都是上一次注册的，倒致重启失败，需要手工删除服务才有用

**Comment by KomachiSion** [comment]
> > 元数据是由客户端注册上来的运行时数据吗？ 那样是无法删除的，可以通过覆盖注册进行修改和删除。
> > 原因：metadata分为运行时数据和运维时数据，运行时数据是客户端在注册时带上的实例的metadata，运维时数据是运维人员通过openAPI或者控制台进行修改和添加的元数据，元数据冲突时运维时数据具有更高优先级。通过API删除的元数据只能是运维时数据。
> > 这么做的原因主要是： 如果允许删除了运行时数据，当出现客户端闪断等情况， 服务端删除了实例后再根据心跳或补偿等方式重新注册时， 数据任然以运行时的为准，被删除的数据还是会存在（因为是临时的实例），运维时数据是运维人员根据实际情况编辑的，会进行记忆和持久化。
> > 综上，如果元数据是客户端自己注册上来的，那就需要客户端来删除，如果是通过API添加的元数据，通过API删除。
> 
> 好的，谢谢，覆盖注册只能通过修改配置重启服务进行吗

如果应用本身没有入口再次调用注册接口， 那只能重启。
