### ISSUE TITLE
nacos2.2.0支持prometheus sd，如何设置label

### ISSUE THREAD

**Issue by lingxing1128** [alibaba/nacos#10493]
nacos 2.2.0版本已经支持prometheus sd，但是如何添加额外的label信息呢
![image](https://github.com/alibaba/nacos/assets/46616642/b4aa7394-243c-4795-a2f3-f1bf1b29e4e8)

**Comment by Shiyajian** [comment]
![image](https://github.com/alibaba/nacos/assets/23068050/e48f9566-bc6d-4568-bedc-d76ac81bd521)

同样的问题，这个clusterName应该是应用名称，而不是group_name

**Comment by lingxing1128** [comment]
> ![image](https://user-images.githubusercontent.com/23068050/238547671-e48f9566-bc6d-4568-bedc-d76ac81bd521.png)
> 
> 同样的问题，这个clusterName应该是应用名称，而不是group_name

那个是集群名称，你可以在application.properties里面设置，如果不设置默认是default
![image](https://github.com/alibaba/nacos/assets/46616642/b189f9c1-7586-49bf-b9ad-46748448cda0)

**Comment by Shiyajian** [comment]
@lingxing1128 是我表达的问题。 

我真正想说的不是，groupName值的问题。 而是想表达。目前 /nacos/prometheus 只有一个字段`__meta_clusterName`字段，缺少`__meta_applicationName`等字段，有效信息太少。

**Comment by KomachiSion** [comment]
nacos没有applicationName的属性， 一般applicationName对应的就是serviceName

**Comment by Shiyajian** [comment]
> nacos没有applicationName的属性， 一般applicationName对应的就是serviceName

重点不是这个字段叫什么名字。  applicationName也好，serviceName也好，appName 也好，name 也好。 

重点是现在  /nacos/prometheus 返回的数据，只有一个 meta_clusterName的字段。 @KomachiSion

**Comment by karsonto** [comment]
请问需要添加什么label？

**Comment by KomachiSion** [comment]
返回的字段有哪些应该是prometheus sd协议规定的吧， nacos这个接口只是对接prometheus sd协议。 需要添加什么label？

**Comment by KomachiSion** [comment]
我理解的prometheus sd，是prometheus通过nacos发现对应服务的ip，然后到对应的ip上去获取实际的监控数据，监控数据的label应该由应用直接吐给prometheus，而不是通过nacos给prometheus。

**Comment by lingxing1128** [comment]
> 我理解的prometheus sd，是prometheus通过nacos发现对应服务的ip，然后到对应的ip上去获取实际的监控数据，监控数据的label应该由应用直接吐给prometheus，而不是通过nacos给prometheus。

label的数据是从naocs拉取的吧，如果不是通过元数据吐给prometheus，那可能会存在一些路径访问不到等问题。按你说的sd只是获取应用的ip和端口号，其它lable还需要promehteus去拉取然后再自行实现lable的组装，这样不是多了一步操作了吗，我的理解就是label就是元数据，就像spring-boot-admin对接nacos时候，直接用的nacos的元数据

**Comment by KomachiSion** [comment]
No more response from author, I think it's not nacos' problem.
