### ISSUE TITLE
Nacos distributed calling function is not perfect

### ISSUE THREAD

**Issue by xingcun** [alibaba/nacos#1050]
## Issue Description
1.使用fegin调用服务A,与服务B,设置权重功能不生效，下线功能生效
2.使用dubbo服务时，下线功能也不生效

服务名|分组|集群数目|实例数|健康实例数
--|:--:|--:|:--:|--:
xc-dubbo-service| DEFAULT_GROUP|1|2|2
xc-customer| DEFAULT_GROUP|1|2|2
xc-gate| DEFAULT_GROUP|1|1|1

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
当将xc-customer中的一个实例权重设置为20
用xc-gate网关调用xc-customer，调用比例还是1:1
当将xc-customer中的一个实例下线时，只会调用一个xc-customr（下线功能正常）

当将xc-dubbo-service中的一个实例，无论是设置权重还是设置下线
分布式功能完全不受影响

### How to reproduce it (as minimally and precisely as possible)

1. nacos 1.0 
2. alibaba2.6.6
3. spring-cloud-alibaba0.2.1.RELEASE  gateway+openfeign

### Tell us your environment
window10

**Comment by paderlol** [comment]
下线的issue应该在最新版本已经修复了，至于权重已经在规划了

**Comment by xingcun** [comment]
> 下线的issue应该在最新版本已经修复了，至于权重已经在规划了

dubbo的下线不起作用，用的就是1.0最新正式版本

**Comment by paderlol** [comment]
这个下线是dubbo nacos registry这边的issue，不是nacos的

**Comment by paderlol** [comment]
不好意思，说错了，下线这块不是的，你看下nacos client在2.6.6用的哪个版本

**Comment by xingcun** [comment]
> 不好意思，说错了，下线这块不是的，你看下nacos client在2.6.6用的哪个版本
我已经更换1.0 rc3
```
<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.0.0-RC3</version>
		</dependency>
```
