### ISSUE TITLE
nacos的gz包里面，文件夹的命名能否带上版本号

### ISSUE THREAD

**Issue by lw-tech** [alibaba/nacos#10502]
第一次见每个版本解压之后的文件夹名字是一样的，都叫nacos，直接导致后续版本把之前版本的配置全覆盖掉了。你们这么偷懒良心不会痛吗？

**Comment by wilsonwu** [comment]
感谢您的反馈，目前社区缺乏管理机制，所有版本发布都比较随意，并没有靠谱的流程支持。

**Comment by KomachiSion** [comment]
没理解问题， 压缩包本身带了版本号啊。方便统一部署，内部文件夹统一都是nacos作为名字。

这不是偷懒的问题。就是这样设置的。 不同的人需求不同。如果你觉得希望内部文件夹名字不同，可以自行通过tag来打包。
