### ISSUE TITLE
The metadata data will not be updated after the service of the permanent instance is re registered.

### ISSUE THREAD

**Issue by zhousw** [alibaba/nacos#10505]
Scenario description:
The framework is Spring Cloud Alibaba, with a registration center of nacos2.1.2 and an rpc framework of dubbo. Multiple Spring Cloud applications are packaged into war and run in a tomcat. The instance is registered as a permanent instance, and the port generated by dubbo is a random port.
BUG description:
After restarting the service, the random port used this time may not be consistent with the previous random port. In this case, the registered port number for the service is the latest port number, but the Dubbo random port displayed in the NACOS console is still the previous one. The phenomenon is that the information in the metadata is still old,
In this case, when other consumer services receive changes and then ask Dubbo to call, there may be a situation where the service cannot be found. The simple description is that the metadata data is not updated after the permanent instance of the service is re registered.

**Comment by KomachiSion** [comment]
The registered port is depend the application, nacos server only receive the register request and get ip and port from request.

So do you means that your application port change, but instance registered in nacos server port no change?

If so, may be you should check whether the application register with new port.

**Comment by zhousw** [comment]
> 注册端口取决于应用程序，nacos 服务器仅接收注册请求并从请求中获取 ip 和端口。
> 那么，您的意思是您的应用程序端口更改了，但是在 nacos 服务器端口中注册的实例没有更改吗？
> 如果是这样，您可能应该检查应用程序是否注册到新端口。

我已经确认过，新注册的服务端口已变化，我通过telnet命令查看dubbo服务验证了确实是改变了端口的，但nacos服务端这边显示的还是旧的，我只能每次删除后重启才能变成正确的端口及metadata信息。

**Comment by KomachiSion** [comment]
可以写一个demo程序，直接用nacos-client注册，然后关闭再改端口重新注册， 如果ok， 那就还是SCA+Dubbo注册的信息有问题。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem and current information is not enough to find problem.
