### ISSUE TITLE
是否需要增加方法，能够直接取消服务的订阅而不必传入 EventListener

### ISSUE THREAD

**Issue by ldyedu** [alibaba/nacos#10501]
您好，目前 Nacos Client （2.2.2）在取消订阅时，需要指定要移除的 `EventListener`，想要完全取消订阅时就必须记录同一个服务下的所有 `EventListener`。但是如果订阅时直接传入了未记录 `lambda` 表达式或匿名内部类，是否可能会造成该服务永远无法取消订阅？因为只有一个服务的所有 `EventListener` 为空时，Nacos 才会真正向服务端取消订阅。

是否需要增加一组方法，比如 `unsubscribeAll()`，可以直接移除一个服务的所有 `EventListener` 并取消对它的订阅，应对订阅无法取消的现象发生呢。

**Comment by Daydreamer-ia** [comment]
服务和监听器是一对多的关系，这里是把指定的服务里这个监听器给移除掉

**Comment by Daydreamer-ia** [comment]
通知回调将会在未来进行重构

**Comment by Daydreamer-ia** [comment]
监听回调将会在新版本重新调整，refer to https://github.com/alibaba/nacos/issues/10374

**Comment by ldyedu** [comment]
> 服务和监听器是一对多的关系，这里是把指定的服务里这个监听器给移除掉

是的，只是现在想直接完全取消一个订阅（如果它有多个监听器）有些麻烦，期待新版本。
