### ISSUE TITLE
java sdk 这个是谁写的啊，太不负责了。

### ISSUE THREAD

**Issue by vanniuner** [alibaba/nacos#10507]
![CleanShot 2023-05-17 at 21 37 36](https://github.com/alibaba/nacos/assets/7248023/49a0cc02-c73b-4f66-84cd-48de0c707055)

java sdk 进行实例下线一堆问题，文档写的到处都是问题。太不负责了。你们的中间件可是有很多人用欸，文档怎么优化都不过分吧

引入依赖，这里面还有`project.groupId` f.............

**Comment by wilsonwu** [comment]
感谢您的反馈，Nacos社区虽然发展了这么多年，但是规则和规矩都没有任何统一的规划，固定社区参与者也是寥寥无几，目前所知的企业用户也都是凑合用，期待能有社区热心者能够带领大家将社区做的更好。

**Comment by capitalR** [comment]
我也是想集成nacos sdk实现服务实例的上下线功能,按照官方java sdk文档做的demo,NamingGrpcClientProxy::requestToServer方法中的响应结果对象response的resultCode是200,但是实际上实例是没有下线的. @sincebyte 你跑通了整个功能了吗?是有哪里需要注意的吗?
