### ISSUE TITLE
Failed to update config when publish for custom datasource plugin ,the insertOrUpdate logic is deeply bind to the DuplicateKeyException  class

### ISSUE THREAD

**Issue by BinWu1989** [alibaba/nacos#10512]
**Describe the bug**

I use the plugin system to implement the datasource for the dm database ,however when edit the config and publish the config ,the backend throw DataIntegrityViolationException out and failed the update the config.The DataIntegrityViolationExcetion(the parent class of DuplicateKeyException) will not be caught when ExternalConfigInfoPersistServiceImpl.insertOrUpdate execute ,so it will not execute the update step
**Expected behavior**
when update ,use the id parameter or catch more general exceptions to deal with insertOrUpdate logic,or follow the orther External***ServiceImpl to just use DataIntegrityViolationException  exception
**Actually behavior**
![image](https://github.com/alibaba/nacos/assets/15190107/d9e5117e-d86b-484f-ad8c-e04e2c47103d)

**How to Reproduce**
1. implement a thirdparty datasource plugin which are not exactly same implement the mysql driver
2. update the config
3. error occurs that failed to update config

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version 2.2.2
 - Module ExternalConfigInfoPersistServiceImpl.insertOrUpdate
 - SDK original

**Comment by BinWu1989** [comment]
@li-xiao-shuang could you please kindly to have a look about this issue?

**Comment by KomachiSion** [comment]
move to #10353 discuss
