### ISSUE TITLE
docker部署nacos2.0.4集群，集群的节点列表显示，除了本节点状态是UP，其他节点状态一直在UP、SUSPICIOUS、DOWN来回变动

### ISSUE THREAD

**Issue by xlzlyyy** [alibaba/nacos#10515]
用docker部署了nacos2.0.4集群：
docker脚本如下：

docker run -d  \
--net=host \
-e PREFER_HOST_MODE=ip \
-e MODE=cluster \
-e NACOS_SERVERS="xxx:8848 xxx:8848 xxx:8848" \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=xxx \
-e MYSQL_SERVICE_PORT=3306 \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=xxxx \
-e MYSQL_SERVICE_PASSWORD=xxxx \
-e NACOS_AUTH_ENABLE=true \
-e JVM_XMS=10g \
-e JVM_XMX=10g \
-e JVM_XMN=6g \
-v /data/xxx/data:/home/nacos/data \
-v /data/xxx/logs:/home/nacos/logs \
--name nacos \
--restart=always \
nacos/nacos-server

部署了3个节点，部署完后，应用程序也能连接集群正常使用。
每个节点的web都能正常访问，但是查看菜单:集群管理->节点列表，发现每个节点除了本节点的状态是up，其他两个节点的状态一直在UP、SUSPICIOUS、DOWN来回变化。
查看/nacos/v1/ns/upgrade/ops/metrics，三个节点均如下：
upgraded = true 
isAll20XVersion = true 
isDoubleWriteEnabled = true 
doubleWriteDelayTaskCount = 0 
serviceCountV1 = 0 
instanceCountV1 = 0 
serviceCountV2 = 0 
instanceCountV2 = 0 
subscribeCountV2 = 0 
responsibleServiceCountV1 = 
0 responsibleInstanceCountV1 = 0 
ephemeralServiceCountV2 = 0 
persistentServiceCountV2 = 0 
ephemeralInstanceCountV2 = 0 
persistentInstanceCountV2 = 0 
service.V1.not.in.V2 = 
service.V2.not.in.V1 =
去3个节点查看日志发现nacos-cluster.log一直在刷：
--   Failed to communicate with the node  其他两个节点。

**Comment by KomachiSion** [comment]
说明你部署的环境， 节点之间互相访问不通， 环境问题自查。

**Comment by gavinwang668** [comment]
是你的环境问题，可以关闭该issue了。2.x的nacos，每个版本，我都docker和K8S部署过，没有问题

**Comment by S994754** [comment]
The simplifying variable occurs like the SQL database which IP: **9999:220:335** 
Desktop: FJLCALA

**Comment by KomachiSion** [comment]
`Failed to communicate with the node` 这就是请求失败，一般是网络不通造成的， 或者看下具体的错误内容是什么。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by zyhui98** [comment]
这个问题我知道原因了，是判断状态的逻辑有问题。

解决方案：
检查节点元数据，是否metaDataMap中四个key（naming_instance_metadata、naming_persistent_service、naming_persistent_service_v2、naming_service_metadata）的leader不一样，如果不一样，逐步缩到一台再增加到3台。
`public RestResult<String> leave(@RequestBody Collection<String> params) throws Exception {
        Collection<Member> memberList = MemberUtil.multiParse(params);
        memberManager.memberLeave(memberList);
        final NacosAsyncRestTemplate nacosAsyncRestTemplate = HttpClientBeanHolder.getNacosAsyncRestTemplate(Loggers.CLUSTER);
        final GenericType<RestResult<String>> genericType = new GenericType<RestResult<String>>() {
        };
        final Collection<Member> notifyList = memberManager.allMembersWithoutSelf();
        notifyList.removeAll(memberList);
        CountDownLatch latch = new CountDownLatch(notifyList.size());
        for (Member member : notifyList) {
            final String url = HttpUtils
                    .buildUrl(false, member.getAddress(), EnvUtil.getContextPath(), Commons.NACOS_CORE_CONTEXT,
                            "/cluster/server/leave");
            nacosAsyncRestTemplate.post(url, Header.EMPTY, Query.EMPTY, params, genericType.getType(), new Callback<String>() {
                @Override
                public void onReceive(RestResult<String> result) {
                    try {
                        if (result.ok()) {
                            LoggerUtils.printIfDebugEnabled(Loggers.CLUSTER,
                                    "The node : [{}] success to process the request", member);
                            MemberUtil.onSuccess(memberManager, member);
                        } else {
                            Loggers.CLUSTER
                                    .warn("The node : [{}] failed to process the request, response is : {}", member,
                                            result);
                            MemberUtil.onFail(memberManager, member);
                        }
                    } finally {
                        latch.countDown();
                    }
                }
                
                @Override
                public void onError(Throwable throwable) {
                    try {
                        Loggers.CLUSTER.error("Failed to communicate with the node : {}", member);
                        MemberUtil.onFail(memberManager, member);
                    } finally {
                        latch.countDown();
                    }
                }
    
                @Override
                public void onCancel() {
        
                }
            });
        }
        
        try {
            latch.await(10_000, TimeUnit.MILLISECONDS);
            return RestResultUtils.success("ok");
        } catch (Throwable ex) {
            return RestResultUtils.failed(ex.getMessage());
        }
    }`

**Comment by zyhui98** [comment]
这个问题我知道原因了，是判断状态的逻辑有问题。

解决方案：
检查节点元数据，是否metaDataMap中四个key（naming_instance_metadata、naming_persistent_service、naming_persistent_service_v2、naming_service_metadata）的leader不一样，如果不一样，逐步缩到一台再增加到3台。

**Comment by zyhui98** [comment]
> 这个问题我知道原因了，是判断状态的逻辑有问题。
> 
> 解决方案： 检查节点元数据，是否metaDataMap中四个key（naming_instance_metadata、naming_persistent_service、naming_persistent_service_v2、naming_service_metadata）的leader不一样，如果不一样，逐步缩到一台再增加到3台。

leader一样也是需要停到只有一台，然后停掉的在一台台启动。
