### ISSUE TITLE
Nacos 1.0.0 GA support Smooth release？

### ISSUE THREAD

**Issue by porkie2016** [alibaba/nacos#1051]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
公司现在用Spring Cloud 里的Eureka作为注册中心，发布某个微服务时，其他调用方总是会在其发布期间报错，导致这个时候总是收到一些线上报警，尽管调整了Eureka的一些定时参数，但还是无法做到完全地平滑发布。

### Describe what you expected to happen
Nacos 1.0.0 GA 版本同时支持AP和CP一致性，是不是能够解决上面所说的平滑发布的问题？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
Yes. There are two solutions:
1. Use [nacos-sync](https://github.com/nacos-group/nacos-sync) to synchronize your services from Eureka to Nacos.
2. Use [Spring Cloud Alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) double-registry to transport the services.

**Comment by porkie2016** [comment]
thanks，I  just learn the Nacos souce code,and yet a question I have : if  a service provider as Nacos Client is killed like 'kill -9' ,the Nacos Server or the service consumer can get it in real-time? if can't, does the Nacos Server only know by Heartbeat mechanism？Heartbeat mechanism may cause delay .

**Comment by nkorange** [comment]
@porkie2016 There are two types of instances (same meaning as provider) in Nacos: ephemeral instance and persistent instance.
* For ephemeral instance: It takes 15 seconds to find the provider disconnected and 30 seconds to remove it.
* For persistent instance: it takes about 2 seconds to find the provider disconnected and set unhealthy, but the provider will not be removed.

Nacos client can exclude the unhealthy instances from consumers.
