### ISSUE TITLE
Inconsistency Between the Front End and Back End During Namespace Adding

### ISSUE THREAD

**Issue by wyb9975** [alibaba/nacos#10517]
**Describe the bug**
When a namespace is added, only the frontend verifies the namespace. Therefore, the backend interface can be invoked to insert dirty data that does not meet the rules.

**Expected behavior**
Failed to insert namespace data that does not meet the rule when the backend interface is invoked to add the namespace data.

**Actually behavior**
Invoke the backend interface to add namespace data that does not meet the rule. The insertion is successful.

**How to Reproduce**
1. Invoke the interface for adding a namespace whose name contains invalid fields, such as @ and #.
2. Data is successfully inserted.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version nacos-server 2.1.0
 - Module console
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Daydreamer-ia** [comment]
i will resolve it
