### ISSUE TITLE
No DataSource set

### ISSUE THREAD

**Issue by xggz** [alibaba/nacos#10521]
能否优化一下nacos的数据库配置，或者更明显的提示具体的错误信息，每次部署nacos都会因为“No DataSource set”卡半天。

**Comment by wuchubuzai2018** [comment]
我来处理一下，我提交的PR应该会解决这个事情

**Comment by KomachiSion** [comment]
No DataSource set 是 spring jpa爆出的异常，如果要修改，需要研究一下datasource 注入spring的流程，然后在合理的地方提示原因。

目前数据库连接失败的错误主要都在config-fatal, nacos-persistence(2.3.0)和nacos.log里。

**Comment by wuchubuzai2018** [comment]
> No DataSource set 是 spring jpa爆出的异常，如果要修改，需要研究一下datasource 注入spring的流程，然后在合理的地方提示原因。

我研究了一下，本质还是数据库连接参数设置错误，导致连接不上，然后代码中未给jdbctemplate设置初始化数据源所致。
![GGG](https://github.com/alibaba/nacos/assets/42382506/5b7cc853-a40e-4b76-b4f1-3d621c595cf3)

个人的想法还是在构造连接的时候进行下数据源连接的检测，目前的版本的代码提交

**Comment by KomachiSion** [comment]
是否把这个日志打印的位置重复打印在nacos.log或者start.out里就可以解决这个问题？

**Comment by wuchubuzai2018** [comment]
> 是否把这个日志打印的位置重复打印在nacos.log或者start.out里就可以解决这个问题？

感觉是，再结合你在PR中提到的那个是否可写的问题，我有时间在测试一下写权限的问题。然后把那个日志的地方，把warn级别改成error级别。
这样就可以两方面去告诉：
一个是构造连接后，进行检测判断，确认连接可以用
一个就是你说的是否可写，如果不可写，也进行提示

**Comment by pengten** [comment]
`apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: cloud
    k8s.kuboard.cn/name: nacos
  name: nacos
  namespace: default
  resourceVersion: '511749'
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nacos
  serviceName: nacos-headless
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-05-26T16:14:15+08:00'
        pod.alpha.kubernetes.io/initialized: 'true'
      creationTimestamp: null
      labels:
        app: nacos
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nacos
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: MODE
              value: standalone
            - name: NACOS_REPLICAS
              value: '1'
            - name: MYSQL_SERVICE_HOST
              value: 192.168.65.4
            - name: MYSQL_SERVICE_DB_NAME
              value: nacos
            - name: MYSQL_SERVICE_PORT
              value: '3306'
            - name: MYSQL_SERVICE_USER
              value: root
            - name: MYSQL_SERVICE_PASSWORD
              value: '12345678'
            - name: SPRING_DATASOURCE_PLATFORM
              value: mysql
            - name: NACOS_AUTH_IDENTITY_KEY
              value: authKey
            - name: NACOS_SERVER_PORT
              value: '8848'
            - name: NACOS_APPLICATION_PORT
              value: '8848'
            - name: PREFER_HOST_MODE
              value: hostname
            - name: NACOS_SERVERS
              value: 'nacos-0.nacos-headless.default.svc.cluster.local:8848'
            - name: NACOS_AUTH_IDENTITY_VALUE
              value: '123456'
            - name: nacos.core.auth.server.identity.key
              value: authKey
            - name: nacos.core.auth.server.identity.value
              value: '123456'
            - name: NACOS_AUTH_TOKEN
              value: token123456
          image: 'nacos/nacos-server:v2.2.2-slim'
          imagePullPolicy: IfNotPresent
          name: nacos
          ports:
            - containerPort: 8848
              name: client
              protocol: TCP
            - containerPort: 9848
              name: client-rpc
              protocol: TCP
            - containerPort: 9849
              name: raft-rpc
              protocol: TCP
            - containerPort: 7848
              name: old-raft-rpc
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate`
2.2.2-smil，  这个yaml一直提示 no datasource set，  其他服务都连上了mysql，就nacos不行。  前两天是多重启几次可能会好，今天一直没好过，难道是随缘读环境变量吗...

**Comment by pengten** [comment]
我的问题解决了，MySQL需要用其他客户端去链接进行“唤醒”。   不过没搞明白为什么Nacos自己没有完成这个所谓的“唤醒”动作，非得从其他渠道使用一下MYSQL才能使用显得很不合理。

**Comment by onewe** [comment]
如果是所谓的 `唤醒`, 是 8 小时问题话, 可以设置一下 mysql 参数或者 nacos 的连接池参数

**Comment by KomachiSion** [comment]
> 我的问题解决了，MySQL需要用其他客户端去链接进行“唤醒”。 不过没搞明白为什么Nacos自己没有完成这个所谓的“唤醒”动作，非得从其他渠道使用一下MYSQL才能使用显得很不合理。

这怎么看上去的都不是Nacos的问题啊，是你设置了MySQL的某种功能，导致必须要用某种特殊的方式去`唤醒`你的MySQL，才能允许Nacos的连接连上。你得排查清楚为什么需要做`唤醒`，Nacos 才能被你的MySQL允许连接，然后你将这个设置更新到Nacos的jdbcUrl上，或者更新到hikari连接池的配置中。

**Comment by wuyuweixin** [comment]
> ![image](https://user-images.githubusercontent.com/30648785/240852303-f9820f2f-ffa1-4de2-bb8a-0b071d45abc1.png)
> 
> k8s下这样配置，重启整个k8s集群的时候会出现NoDatasource set，需要重新修改几次环境变量重启才能成功。

这个问题遇到几次了

**Comment by edhn3000** [comment]
> 是否把这个日志打印的位置重复打印在nacos.log或者start.out里就可以解决这个问题？

支持，启动一直报No DataSource set找不到头绪，直到看到了你说的config-fatal.log才发现了bad SQL grammar错误，使用的pg库有表权限问题。nacos分很多的日志，这对排查问题似乎并不太友好，对于阅读者不知道错误会在哪个文件里，一直主要的错误也可以包含在nacos.log里
