### ISSUE TITLE
nacos2.2.0 Use prometheus for metrics

### ISSUE THREAD

**Issue by kybt** [alibaba/nacos#10537]
nacos 2.2.0 deployed with helm requires monitoring using prometheus, but no data is available，Monitoring data was previously available with version 2.0.4

# curl http://127.0.0.1:8848/nacos/actuator/prometheus
{"timestamp":"2023-05-24T08:24:34.823+08:00","status":404,"error":"Not Found","message":"No message available","path":"/nacos/actuator/prometheus"}

How does the configuration need to be modified to support prometheus monitoring?

**Comment by carlo-zhang** [comment]
在配置里面增加这个字段 management.endpoints.web.exposure.include=*
或者启动参数中添加           `            - name: JAVA_OPT
              value: >-
                -Dmanagement.endpoints.web.exposure.include=*`

**Comment by kybt** [comment]
我是用helm部署的，只能通过修改values.yaml的方式，尝试加入management.endpoints.web.exposure.include=*到values.yaml中，但是启动后还是获取不到数据

**Comment by KomachiSion** [comment]
it's spring boot actuator configuration, you should config it in `nacos/conf/application.properties`

management.endpoints.web.exposure.include=prometheus
