### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.http.nio.reactor.ConnectingIOReactor

### ISSUE THREAD

**Issue by zhang1995632** [alibaba/nacos#10536]
1 spring boot 3.0 spring cloud 2022.0.2  spring-cloud-alibaba 2022.0.0.0-RC1
maven config 
` <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.5.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpasyncclient</artifactId>
            <version>4.1.5</version>
        </dependency>`
Are there any other configurations that need to be introduced now? 
It will prompt you when you start: java.lang.ClassNotFoundException: org.apache.http.nio.reactor.ConnectingIOReactor

**Comment by springcloud-boot** [comment]
ClassNotFoundException always comes up in times of conflict.
I think you should check your maven config. exclude conflict

**Comment by zhang1995632** [comment]
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            </dependency>
                   <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

**Comment by zhang1995632** [comment]
this is my maven config

**Comment by zhang1995632** [comment]
spring boot 3.0 spring cloud 2022.0.2 spring-cloud-alibaba 2022.0.0.0-RC1

**Comment by springcloud-boot** [comment]
你用idea的插件  来检查下 nio的相关依赖. 排除标红的
![image](https://github.com/alibaba/nacos/assets/39367636/555e6df3-7733-4d32-96da-1c77a88cbc4a)

**Comment by zhang1995632** [comment]
![image](https://github.com/alibaba/nacos/assets/41946899/abd6dbe6-60a1-4abe-b00d-41762ea13c80)
检查了 没有包冲突

**Comment by KomachiSion** [comment]
It's not nacos' problem. your application depend `org.apache.http.nio.reactor.ConnectingIOReactor` but not import depend jar. 

You should check by yourself.
