### ISSUE TITLE
当配置增删改查失败的时候，留下操作失败的ERROR日志

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#10539]
![image](https://github.com/alibaba/nacos/assets/58767027/5162ffe7-ad94-4650-8265-81677bce2e2e)
写入数据库失败时，会导致：
![image](https://github.com/alibaba/nacos/assets/58767027/69d31c8b-6d3d-4b12-9f2b-db8fc1aa0d8f)
当有如上图所示发布配置失败时，留下ERROR日志

**Comment by realJackSun** [comment]
@i will solve it@

**Comment by wilsonwu** [comment]
This is a good first issue :)

**Comment by realJackSun** [comment]
> This is a good first issue :)

Not first issue, hh

**Comment by wilsonwu** [comment]
> > This is a good first issue :)
> 
> Not first issue, hh

Good first issue means anyone want to contribute this project can be start from this issue without any experience.

**Comment by KomachiSion** [comment]
@realJackSun Please solve #10353 together, the catch exception has both problem in DuplicateKeyException and DataIntegrityViolationExcetion
