### ISSUE TITLE
Slow inter-service calls. 服务之间调用变慢

### ISSUE THREAD

**Issue by mltneal** [alibaba/nacos#10530]
When using Nacos version 2.1.1, the inter-service call between a single node with authentication mode has a relatively low response time. However, when I deploy three nodes with authentication mode, the response time for inter-service calls increases significantly by around 15ms (after multiple calls). Is this normal? If there is a problem, how should I troubleshoot and solve it?
使用nacos本版2.1.1，单节点+鉴权模式服务之间调用耗时较少，但是当我部署三节点+鉴权模式服务之间调用耗时明显提高了大概15ms左右（已经多次调用了），这种情况是否正常，如果有问题应该怎么排查解决呢

**Comment by mltneal** [comment]
使用的序列化方式是kryo

**Comment by KomachiSion** [comment]
应用之间调用变慢和nacos没有关系， 应用流量不经过nacos

**Comment by mltneal** [comment]
我观察到access_log日志，在应用没有流量的情况下，每天大概将近500M，大概每秒都有各个服务的注册请求，这个正常吗；会不会跟服务之间调用慢有关系呢

**Comment by Daydreamer-ia** [comment]
> 我观察到access_log日志，在应用没有流量的情况下，每天大概将近500M，大概每秒都有各个服务的注册请求，这个正常吗；会不会跟服务之间调用慢有关系呢

Nacos作为注册中心，只负责协调和存储分布式环境的元数据，和具体的调用无关

**Comment by KomachiSion** [comment]
> 我观察到access_log日志，在应用没有流量的情况下，每天大概将近500M，大概每秒都有各个服务的注册请求，这个正常吗；会不会跟服务之间调用慢有关系呢

你说的流量应该是业务流量，  只要你有应用启动并且需要注册/订阅/发布 配置和服务， 那就和nacos有流量，但是是异步的。

建议你最好学习一下注册&配置中心和微服务之间的关系。应该能帮助你理解问题。

**Comment by mltneal** [comment]
感谢解答，我再排查下同一网段内dubbo本身为什么调用速度上会有差异
