### ISSUE TITLE
nacos2.1.1 client full gc后不能自动重新注册

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#10541]
nacos 服务端和客户端都是使用的2.1.1；nacos中通过健康检查机制来保证服务的注册，客户端 full gc后，发现不能自动注册至服务端，这种情况有遇到过吗

**Comment by KomachiSion** [comment]
看nacos-client日志，是不是一直没有重连到服务端。自动重连自动恢复注册也有日志。

**Comment by FengJinghHua** [comment]
ok，复现好我更新，BTW 源码应该是在这块com.alibaba.nacos.common.remote.client.start()?

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by lxqgithub** [comment]
> nacos 服务端和客户端都是使用的2.1.1；nacos中通过健康检查机制来保证服务的注册，客户端 full gc后，发现不能自动注册至服务端，这种情况有遇到过吗

解决了吗？
