### ISSUE TITLE
nacos-api 中关于serviceName在不同接口中含义不同的问题

### ISSUE THREAD

**Issue by DmiyDing** [alibaba/nacos#10552]
最近在使用nacos-api对nacos进行一系列操作时发现，NamingMaintainService和NamingService接口中，入参的serviceName的含义不同。

例如：
namingService#getAllInstances接口中serviceName是应用名；
而namingMaintainService#updateInstance中的serviceName是group + Constants.SERVICE_INFO_SPLITER + 应用名。

通过断点调试才知道有这样潜在逻辑存在。期望在提供api接口的时候，保持统一。同一个字段名称在相关接口中的含义保持统一。
谢谢！

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/61abb144-9ca4-4e9e-82ad-dfa8109cb7e0)
![image](https://github.com/alibaba/nacos/assets/37170243/8b7c82a1-4f9a-40fe-a06d-9b9190168ce8)
![image](https://github.com/alibaba/nacos/assets/37170243/dc35c58a-a596-4039-b293-ae51526ec6ce)
![image](https://github.com/alibaba/nacos/assets/37170243/9ba13a13-398c-49a0-b91e-a245f0c02b69)

是一样的，只是你使用方法的问题。

**Comment by KomachiSion** [comment]
只输入serviceName时， 会自动使用DEFAULT_GROUP

**Comment by DmiyDing** [comment]
> ![image](https://user-images.githubusercontent.com/37170243/241146425-61abb144-9ca4-4e9e-82ad-dfa8109cb7e0.png) ![image](https://user-images.githubusercontent.com/37170243/241146592-8b7c82a1-4f9a-40fe-a06d-9b9190168ce8.png) ![image](https://user-images.githubusercontent.com/37170243/241146626-dc35c58a-a596-4039-b293-ae51526ec6ce.png) ![image](https://user-images.githubusercontent.com/37170243/241146657-9ba13a13-398c-49a0-b91e-a245f0c02b69.png)
> 
> 是一样的，只是你使用方法的问题。

你先看看那两个接口呢？

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
