### ISSUE TITLE
V1.0.0 the menu “service list” redirect to login page

### ISSUE THREAD

**Issue by libinwalan** [alibaba/nacos#1055]
V1.0.0,click the menu “service list” redirect to login page. I tried RC version,this problem always come up.
V0.9 works good.
![image](https://user-images.githubusercontent.com/6059942/56011763-b8f3db00-5d1b-11e9-831c-73daaa9197ff.png)

**Comment by zhou-hao** [comment]
+1

**Comment by nkorange** [comment]
Clear browser cache

**Comment by jianghaofeng** [comment]
+1

**Comment by libinwalan** [comment]
> Clear browser cache

When i meet this problem, i cleared all the browser cache, include storage and cookie.But nothing changed

**Comment by zhou-hao** [comment]
change url =>  http://127.0.0.1:8884

**Comment by bearwind** [comment]
I have also met this problem before. Pressing ctrl+F5 to force refresh the cache of chrome could work well.

**Comment by libinwalan** [comment]
> I have also met this problem before. Pressing ctrl+F5 to force refresh the cache of chrome could work well.

thanks.
