### ISSUE TITLE
ERROR got exception. unknown user!

### ISSUE THREAD

**Issue by rola0411** [alibaba/nacos#10569]
![image](https://github.com/alibaba/nacos/assets/46880610/bccdbae6-f0d0-4d77-adcd-954df02ef5d9)

请问下，这个是什么原因。nacos.log 每几秒刷一堆这个日志

**Comment by KomachiSion** [comment]
去掉应用配置文件中的username和password.

**Comment by rola0411** [comment]
十分感谢。

**Comment by dlaolao** [comment]
> 去掉应用配置文件中的username和password.

![image](https://github.com/alibaba/nacos/assets/79901012/2eb62a1e-4983-49fc-b7be-507707fb02e8)
配置文件里 没有username 和password   怎么一直在报这个
