### ISSUE TITLE
nacos 新版，docker版本没有同步更新

### ISSUE THREAD

**Issue by wuai1024** [alibaba/nacos#10566]
目前 docker hub 上面都还是 tag  v2.2.2版本的，没有新版 v2.2.3

![image](https://github.com/alibaba/nacos/assets/13379708/323d61db-1cab-4197-bfe9-a38eb3552129)

**Comment by wilsonwu** [comment]
已经提交PR更新发布docker镜像（https://github.com/nacos-group/nacos-docker/pull/340），但没有有权限的人帮忙处理。

**Comment by wilsonwu** [comment]
@KomachiSion 能否找一下有权限的人帮忙合并：https://github.com/nacos-group/nacos-docker/pull/340

并发布2.2.3版本docker image？

**Comment by KomachiSion** [comment]
PR 我合并了， 发版本需要等待 @paderlol 有空

**Comment by KomachiSion** [comment]
新版本docker镜像已发布
