### ISSUE TITLE
请完善v2.2.x之后版本的在线文档

### ISSUE THREAD

**Issue by mustangxu** [alibaba/nacos#10560]
请官方认真完善[auth文档](https://nacos.io/zh-cn/docs/v2/guide/user/auth.html)，尤其是在2.2.x安全更新之后。按照目前的文档配置，启用auth后应用启动失败。于是尝试各种配置组合，纯粹是在碰运气，对安全性更是没有详细的指引。请从官方角度在文档中明确解释以下问题：
1. `nacos.core.auth.server.identity.key`的具体作用是什么？
2. `nacos.core.auth.server.identity.value`的具体作用是什么？
3. 上述1、2之间的关系是什么？配置成一样/不一样的值对安全性分别有什么影响？
4. `NACOS_AUTH_TOKEN`的具体作用是什么？新版本下到底有没有默认值？（亲测如果不配置该值启动失败）
5. env配置的key和参数配置的key的对应关系，比如，`NACOS_AUTH_TOKEN`对应的是`nacos.core.auth.server.`下哪个键？

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/789e4571-566e-422b-b322-d819cf964e7c)

1. 2. 3 均在文档中有，请认真阅读整个文档内容。
4. 没有默认值，作用文档中有
5. docker工程的readme中有描述env的内容含义。

**Comment by lifedever** [comment]
复议，这俩值到底是什么意思，随便配？还是通过什么产生的密钥对？

**Comment by zhanjinhao** [comment]
Set the value of `nacos. core. auth. server. identity. key` to the key of the HTTP header, and set the value of `nacos. core. auth. server. identity. value` to the value of the header above. http request do not need authentication.
