### ISSUE TITLE
服务注册一段时间后大范围掉线

### ISSUE THREAD

**Issue by skippyb1** [alibaba/nacos#10567]
版本：2.1.1
服务端报错日志

![image](https://github.com/alibaba/nacos/assets/23324514/ac1da887-1273-4e30-b11c-360aebafadfb)

**Comment by KomachiSion** [comment]
From your log, it seems your env has some problem. 

The health check task should put in queue and health check thread will get task from queue. But your env throw `InterruptedException` which means your queue task thread has been interrupted by yourself.

So I think you should check your deploy env first. Whether has some auto maintain script do handle the nacos server, such as shutdown. Or check whether OOM in your env.

**Comment by skippyb1** [comment]
没有oom，想问一下  什么情况下健康检查的线程可能被打断 ，会不会跟nacos client有关系，我正在抓取客户端的日志，等待这种情况的再次发生

**Comment by KomachiSion** [comment]
搜索引擎或者AI： Java 线程中断 InterruptedException

我的理解就是有地方主动调用了interrupt方法，或者停止了线程池，或者停止了进程。OOM也有可能导致。

**Comment by skippyb1** [comment]
问题已经定位 感谢

**Comment by Sulbsld** [comment]
S DGS djdd
