### ISSUE TITLE
Please refine the comments for sql's fields

### ISSUE THREAD

**Issue by EricMo** [alibaba/nacos#10571]
There are some fields in the database that are missing the necessary comments; Hopefully, the community can refine the comments and improve the readability of the database

| Table                | Fields                                            |
| -------------------- | ------------------------------------------------- |
| config_info          | c_desc,app_name,c_desc,c_use,effect,type,c_schema |
| config_tags_relation | nid                                               |
| his_config_info      | ALL                                               |
| permissions          | ALL                                               |
| roles                | ALL                                               |
| users                | ALL                                               |

**Comment by KomachiSion** [comment]
@EricMo Welcome submit PR.
