### ISSUE TITLE
【Question】自建用户用于nacos客户端应用验证时，如果对namespace开启只读将也无法注册该空间的服务

### ISSUE THREAD

**Issue by acexy** [alibaba/nacos#10573]
1. 创建用户A
2. 分配该用户某一角色B，该角色B只有对于namespace C拥有只读权限
3. 使用A用户客户端进行nacos中心访问，读取空间C的配置文件，同时将自己服务注册只nacos中心作为服务

得到错误，授权失败（针对于服务发现功能，配置可以正常获取）

问题：

1. 对于服务发现功能，如果没有写权限的用户是否没有权限注册服务 （测试增加写权限后可以注册）
2. 是否可以考虑增加权限项控制服务注册权限，实际使用中可能使用的一个namespace来处理一个环境的配置和服务发现功能，但是又不想客户端写配置

**Comment by KomachiSion** [comment]
注册中心和配置中心可以使用不同的用户密码，给不同的权限即可。

**Comment by KomachiSion** [comment]
如果需要用同一个账号，针对不同的行为作出不同的鉴权行为，这种属于自定义需求， 可以开发自定义鉴权插件实现。

**Comment by acexy** [comment]
可以。
