### ISSUE TITLE
nacos-client 1.4.2版本和对应的Spring Cloud Alibaba Version版本是否有log4j安全漏洞

### ISSUE THREAD

**Issue by YeJiaL** [alibaba/nacos#10584]
log4j-core>2.17才是安全版本
nacos-client 1.4.2版本是否不安全
![image](https://github.com/alibaba/nacos/assets/26019928/32e72d87-e6c4-4b56-b662-27a588799399)

![image](https://github.com/alibaba/nacos/assets/26019928/c524f44b-74e7-4b44-a65d-8a06a792e4c5)

**Comment by KomachiSion** [comment]
nacos-client only compile step need log4j, not directly depend log4j.  log framework should  be imported by your application. logback or log4j both ok.
