### ISSUE TITLE
Nacos client has been creating threads and has not destroyed them

### ISSUE THREAD

**Issue by lidaming1** [alibaba/nacos#10595]
When I used the nacos version 2.1.0 client, I found that the nacos grpc client executor thread was constantly created but not destroyed during the server operation, but it was destroyed in the local Windows environment
![image](https://github.com/alibaba/nacos/assets/65325238/8bc15735-dddb-482a-8f4e-90e62d2cd4be)

**Comment by lidaming1** [comment]
This is my nacos registration code,Is there any problem? or I need only one nacos service address to register my service

```
String serverAddr = =http://nacos-1.com,http://nacos-2.com,http://nacos-3.com
Properties properties = new Properties();
properties.setProperty(PropertyKeyConst.SERVER_ADDR, serverAddr);
properties.setProperty(PropertyKeyConst.NAMESPACE, namespace);
naming = new NacosNamingService(properties);
```

**Comment by KomachiSion** [comment]
1. Make sure the NacosNamingService only create once.
2. Make sure your env `Runtime.getRuntime().availableProcessors()` get right cpu process number.

**Comment by lidaming1** [comment]
1、Before executing the above code, I made a judgment on whether the `NacosNamingService` has been assigned a value, and the above code was only executed once
2、In other where, I also use `Runtime. getRuntime(). availableProcessors()` to create a Thread pool. Through the dump file, we can verify that this method returns the correct number of CPU cores

**Comment by onewe** [comment]
Is the application running in Weblogic or another web container ? Perhaps doesn't destroy NacosNamingService when the servlet container closing.

**Comment by lidaming1** [comment]
My programs run on Alibaba Cloud servers, and the environment message is:

**Comment by KomachiSion** [comment]
The thread is bind for each nacos client instance, the rate of thread of client is 8 * cpu : 1, which means that if `Runtime. getRuntime(). availableProcessors()` is `1`, the thread number of nacos client instance is `8:1`.

So you can dump memory and dump thread each hours to observe,
1. If the thread increase continuously, which means your app has wrong usage, app create new nacos client instance continuously and without `shutdown`.
2. If the thread not increased, but with a large number, which means `Runtime. getRuntime(). availableProcessors()` is read error number, such as read from node but not pod limit. At this case, you can fix the `Runtime. getRuntime(). availableProcessors()` or set `-D nacos.common.processors=1`

**Comment by lidaming1** [comment]
Just now I dumped memory, and the nacos threads did not continue to grow, but it created about 600 threads, which seems to be the same as you said, the `Runtime. getRuntime(). availableProcessors()` is read error, thank you for your answer
