### ISSUE TITLE
when nacos client used nacos address as config value, there is a bug at choose nacos server methd which used a fixed index value when get the nacos server list

### ISSUE THREAD

**Issue by 1em0n9527** [alibaba/nacos#10598]
**Describe the bug**
when nacos client used nacos address as config value, there is a bug at choose nacos server methd which used a fixed index value when get the nacos server address array

当 nacos 客户端使用地址服务器作为配置时，在通过nacos地址服务器拿到 nacos server 列表后，取的一个固定下标获取 server 地址，导致当有多个客户端请求，请求没有被平均分散到各个 server

**Expected behavior**
different nacos client request  should go to different nacos server

多个客户端请求应该是均分到各个 nacos server 地址

**Actually behavior**
different nacos client connect request  should go to the same nacos server

多个客户端请求跑到同一个 nacos server 地址

**How to Reproduce**
com.alibaba.nacos.client.naming.core.ServerListManager#currentIndex
is initialized a **random** value only when !serverList.isEmpty()
```java
   public ServerListManager(NacosClientProperties properties, String namespace) {
        this.namespace = namespace;
        initServerAddr(properties);
        if (!serverList.isEmpty()) {
            currentIndex.set(new Random().nextInt(serverList.size()));
        }
        if (serverList.isEmpty() && StringUtils.isEmpty(endpoint)) {
            throw new NacosLoadException("serverList is empty,please check configuration");
        }
    }
```
and is not considerate to the values at serversFromEndpoint

ServerListManager#currentIndex 下标值初始化为随机值的逻辑有问题，nacos 客户端如果使用 nacos address server (地址服务器) 作为配置，该下标值没有被初始化，而是一个固定值，导致所有的客户端都是用同一个 nacos server

pr 稍后提交

**Comment by KomachiSion** [comment]
will be changed in `genNextServer`

**Comment by KomachiSion** [comment]
你的意思是，如果走地址服务器模式， 每个节点都是取一个固定值是吗？

**Comment by 1em0n9527** [comment]
> 你的意思是，如果走地址服务器模式， 每个节点都是取一个固定值是吗？

是的
