### ISSUE TITLE
NamingEvent contains changed instance list

### ISSUE THREAD

**Issue by finefuture** [alibaba/nacos#10591]
**Is your feature request related to a problem? Please describe.**
NamingEvent contains changed instance list, we need to know which instance was changed

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
refer to #10374. 

Will be consider with #10374 together.

**Comment by KomachiSion** [comment]
The feature is relative more features like group subcribers and new notify way #10374 .

So community will redesign and consider this feature into #10374. 

Sorry for your PR and if you need this feature for now, you can do this login in your `Listener`.
