### ISSUE TITLE
nacos 2.2.3 目录下产生file： 文件夹

### ISSUE THREAD

**Issue by bo8888** [alibaba/nacos#10593]
在nacos 1.4.4 和nacos 2.1 都无此问题
ll nacos |awk '{print $1,$NF}'
drwxrwxr-x bin
drwxr-xr-x conf
drwxr-xr-x data
-rw-r--r-- derby.log
drwxr-xr-x file:
-rw-r--r-- LICENSE
drwxr-xr-x logs
-rw-r--r-- NOTICE
drwxrwxr-x target
drwxr-xr-x work

ls nacos/file\:/

`XXXXX/nacos/target/nacos-server.jar\!/BOOT-INF/classes\!/data/tps/`

**Comment by KomachiSion** [comment]
is It tomcat accesslog auto create?

**Comment by KomachiSion** [comment]
`server.tomcat.basedir=file:.` in application.properties.

**Comment by bo8888** [comment]
> `server.tomcat.basedir=file:.` in application.properties.

this conf is in the application.properties,and the dir is null
du -sh *
20K     bin
92K     conf
485M    data
0       derby.log
0       file:
20K     LICENSE
82M     logs
4.0K    NOTICE
151M    target
0       work

**Comment by BlackJia** [comment]
同样的问题。file: 文件夹还是会创建，并且 accesslog 配置 不生效。
配置如下

#*************** Access Log Related Configurations ***************#
### If turn on the access log:
server.tomcat.accesslog.enabled=false
### The access log pattern:
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i

### The directory of access log:
server.tomcat.basedir=/usr/src/nacos/bin/

**Comment by Vain-vayne** [comment]
![image](https://github.com/alibaba/nacos/assets/62093339/d8d4035f-23ca-400e-993d-3a22e614e9be)
![image](https://github.com/alibaba/nacos/assets/62093339/e7726544-109b-4b0f-97c4-6bf3af67ff94)
![image](https://github.com/alibaba/nacos/assets/62093339/f46b3f38-00a8-4f04-8589-6e5375a7e56d)

**Comment by KomachiSion** [comment]
I only found the relative changes about the `file:` is tomcat basedir, the dir is no affect for nacos running, please community help found the create locate if not  tomcat basedir

**Comment by ijustyce** [comment]
> I only found the relative changes about the `file:` is tomcat basedir, the dir is no affect for nacos running, please community help found the create locate if not tomcat basedir

除了 file: 外，还有个 derby.log 这个文件，这个文件是？可以改位置嘛？我们最近在考虑升级到最新，发现多了 file: 以及 derby.log ，多谢了。

**Comment by bo8888** [comment]
> 文件

derby.log 是嵌入式数据库derby的日志，我用mysql它也会创建，但是不会写东西进去，也算个bug

**Comment by bo8888** [comment]
> I only found the relative changes about the `file:` is tomcat basedir, the dir is no affect for nacos running, please community help found the create locate if not tomcat basedir

if i set server.tomcat.basedir  null,  it will report 
` Failed to bind properties under 'server.tomcat.basedir' to `java.io.File``

if i set server.tomcat.basedir file:. or . or ./log ,it is all create the dir file: 
2.2.3 is a bug version,plase repair it in the version 2.2.3.1

**Comment by DarrenLuo** [comment]
@i will solve it@

**Comment by yoyo837** [comment]
#10593 didn't fix the unexpected `derby.log` file, does anyone know the latest on it?

**Comment by DarrenLuo** [comment]
I processed the folder file: only, and not deal the derby.log

**Comment by yoyo837** [comment]
> I processed the folder file: only, and not deal the derby.log

I create a new issue for trace that https://github.com/alibaba/nacos/issues/11502.
