### ISSUE TITLE
nacos配置内容编写不了

### ISSUE THREAD

**Issue by Dxixixi** [alibaba/nacos#10597]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Dxixixi** [comment]
编写不了配置文件

**Comment by 985492783** [comment]
Please provide error information and screenshots to help locate the problem

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.
