### ISSUE TITLE
ClientWorker.LongPollingRunnable will be executed repeatedly

### ISSUE THREAD

**Issue by zhaoche27** [alibaba/nacos#1060]
版本：1.0.0

1，ClientWorker.LongPollingRunnable  run方法 finally（executorService.execute(this);） 会导致重复执行
2，executor.scheduleWithFixedDelay  会重复执行

**Comment by hxy1991** [comment]
ClientWorker.LongPollingRunnable run方法 finally（executorService.execute(this);） 为了让当前这个任务持续执行，这也是保持长轮询监听变更的地方。

"executor.scheduleWithFixedDelay" 调用了 "ClientWorker.checkConfigInfo"，其中有个”longingTaskCount > currentLongingTaskCount“ 判断，保证不会重复执行。
