### ISSUE TITLE
Nacos is using MySQL connector 5.1.34. thus, MySQL 8 is not supported

### ISSUE THREAD

**Issue by TTTTTAAAAAKKKKEEEENNNN** [alibaba/nacos#1061]
Nacos is using MySQL connector 5.1.34, so it may cause problems when connecting to a MySQL 8 server.

Temporary solution would be putting a MySQL 8 connector into classpath or plugin directory, or recompile the project with MySQL 8 connector (e.g. mysql-connector-java-8.0.13).

So far (in version 1.0.0), the problem is not solved.

Changing pom to use MySQL 8 connector should be a good solution since MySQL 8 connector supports MySQL servers with lower version

**Comment by nkorange** [comment]
@TTTTTAAAAAKKKKEEEENNNN MySQL 8 driver doesn't support connecting to lower version server. So the current solution seems to be the only solution
