### ISSUE TITLE
Nacos 存在 SQL 注入漏洞

### ISSUE THREAD

**Issue by 313988838** [alibaba/nacos#10613]
**Describe the bug**

可利用 URL：http://10.0.8.2:18848/nacos/v1/cs/ops/derby

Nacos 源码 config server 中有个接口，没有做任何的鉴权，即可执行 sql 语句，可
以泄漏全部数据漏洞点在于 module：nacos-config 的 com.alibaba.nacos.config.server.
controller.ConfigOpsController 中。代码只限制了需要包含 select，因此，导致可以执行任
意的 select 查询语句通过测试，可以用以下的语句查询到所有数据库信息
select * from users
select * from his_config_info
select * from config_info

下载最新2.2.3版本下来验证依然都存在这个问题

使用的单机并未使用mysql数据库
**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. Go to '...' 输入 http://localhost:8848/nacos/v1/cs/ops/derby?sql=select * from users
2. Click on '....'  回车
3. Scroll down to '....'  页面显示账号密码
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] 
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by LeiMl0608** [comment]
1.4.6的版本也有同样的问题
1。输入 http://127.0.0.1:8848/nacos/v1/auth/users?pageNo=1&pageSize=9&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY3MjkyMTE3OX0.ptWhA96HlxbfFWB2Lff2RylPKtgbMEPLXOLLFQbMhPs
2。Click on '....' 回车
3。Scroll down to '....' 页面显示账号密码

**Comment by KomachiSion** [comment]
derby 数据库不能像其他外置数据库一样，使用外置的jdbc链接，因此需要一个运维接口来执行SQL语句。

该接口就是这样一个用于对derby 数据库进行操作的一个接口，因此他是个功能，而非注入漏洞。麻烦先了解一下原理。

该接口添加了鉴权，如果开启鉴权后应该在无身份信息时被拦截。  如果你觉得这个功能对你来说是漏洞，请不要使用derby数据库进行部署，使用外置数据库，如mysql等。

**Comment by freesme** [comment]
在浏览器匿名模式未登录Nacos控制台，直接访问 `/nacos/v1/cs/ops/derby?sql=select * from config_info` 可以获取到所有配置数据接口并不受登录控制台鉴权控制

**Comment by freesme** [comment]
在浏览器匿名模式未登录Nacos控制台，直接访问 `/nacos/v1/cs/ops/derby?sql=select * from config_info` 可以获取到所有配置数据

该接口并不受登录控制台鉴权控制，鉴权应该是存在问题的

**Comment by freesme** [comment]
在浏览器匿名模式未登录Nacos控制台，直接访问 `/nacos/v1/cs/ops/derby?sql=select * from config_info` 可以获取到所有配置数据

该接口并不受登录控制台鉴权控制，这样接口鉴权是没有问题的吗？ @KomachiSion

**Comment by Gnaiqll** [comment]
有什么解决办法吗
