### ISSUE TITLE
2.2.3 鉴权问题

### ISSUE THREAD

**Issue by tonycody** [alibaba/nacos#10618]
升级到 2.2.3 之后，不开启鉴权。控制台没有任何认证。但开启了鉴权，客户端也要鉴权。

我的需求就是控制台要求鉴权，客户端不要求鉴权。

如何解 ....

**Comment by xuechaos** [comment]
这部分其实是安全合规要求，鉴权逻辑就要强鉴权。
你的场景没有办法开启强鉴权，简单说，如果客户端不鉴权可以通过，控制台开启的鉴权也基本没什么效果。
如果只要控制台的登录的话，服务端鉴权插件有返回是否要登录的开关，这部分打开可以帮助你像原来一样登录，但是集群还是没有鉴权的。比较建议开启客户端鉴权。

**Comment by KomachiSion** [comment]
> 升级到 2.2.3 之后，不开启鉴权。控制台没有任何认证。但开启了鉴权，客户端也要鉴权。
> 
> 我的需求就是控制台要求鉴权，客户端不要求鉴权。
> 
> 如何解 ....

2.1.0后支持自定义扩展鉴权插件， 您可以自行实现插件，识别客户端请求和控制台请求，只对需要鉴权的请求进行鉴权。

**Comment by bestwxc** [comment]
123

**Comment by bestwxc** [comment]
狗。
