### ISSUE TITLE
DockerHub上没有1.4.6版本的镜像

### ISSUE THREAD

**Issue by badwolfbay** [alibaba/nacos#10610]
docker hub上最新版本的镜像只有2.2.3版本的镜像，而没有1.4.6版本的。
![image](https://github.com/alibaba/nacos/assets/8099669/6ba48047-f688-49be-9ed6-65dd42f93d46)

**Comment by wilsonwu** [comment]
@paderlol shell we solve this problem?

**Comment by zhranklin** [comment]
建议提供一下1.4.6的镜像, 最近的CVE漏洞可能会有很多用户需要, 谢谢~

**Comment by wilsonwu** [comment]
感谢大家提醒，跟随jar包发布对应镜像是一个非常严谨，正确且负责的操作，看有权限发布的维护者是否可以帮忙发布。

**Comment by learn0208** [comment]
是否可以把dockerfile公开，这样即使你们不更新dockerhub，用户也可自行构建镜像

**Comment by wilsonwu** [comment]
> 是否可以把dockerfile公开，这样即使你们不更新dockerhub，用户也可自行构建镜像

镜像相关的代码和配置文件都在这个仓库：https://github.com/nacos-group/nacos-docker

**Comment by KomachiSion** [comment]
![Uploading image.png…]()

**Comment by raybj** [comment]
可以拉进行，版本号加个“v”就行了：
