### ISSUE TITLE
控制台集群节点状态异常

### ISSUE THREAD

**Issue by songbaicheng** [alibaba/nacos#10612]
版本是2.2.1，在本地开了三个端口配置的集群启动之后，登录哪一个节点的管理台就只显示当前节点为up，其他的为down，每个节点都能正常访问。

**Comment by wilsonwu** [comment]
感觉你这个问题在于节点间没有互相组成高可用模式，每个单独都是可用，但是和其他节点组合不正常。

**Comment by songbaicheng** [comment]
可是我已经配置成集群模式都已经节点间互相发现了，只是状态异常

**Comment by wilsonwu** [comment]
是不是互相的网络配置有一些限制？导致状态检测不成功？影响这个的因素还是有点多。

**Comment by songbaicheng** [comment]
好像是我服务注入进来之后就好了，感谢感谢
