### ISSUE TITLE
Docker image JVM OPTS parames FAQ

### ISSUE THREAD

**Issue by tonycody** [alibaba/nacos#10614]
![image](https://github.com/alibaba/nacos/assets/6773121/db871b74-f8a5-4374-a92f-197c36f7bcd2)

Why is it not allowed to change the GC type? Default CMS and cannot be modified. For what reason?

Version:2.2.3

**Comment by KomachiSion** [comment]
docker image is a sample and default recommand params for most of users, If you has your own request, please build your own docker image for your env.

**Comment by tonycody** [comment]
> docker 镜像是大多数用户的示例和默认命令参数，如果您有自己的请求，请为您的 env 构建自己的 docker 镜像。

支持灵活一点又影响什么呢？
