### ISSUE TITLE
2.0.3升级2.2.3 配置列表不显示内容，有报错信息。

### ISSUE THREAD

**Issue by JackloveJam** [alibaba/nacos#10620]
我将nacos 2.0.3 升级到2.2.3
在配置列表页面 报错
I will upgrade nacos 2.0.3 to 2.2.3

Error reported on the configuration list page

caused: serialize page error, dataId=, group=;caused: PreparedStatementCallback; bad SQL grammar [SELECT id,data_id,group_id,tenant_id,app_name,content,encrypted_data_key FROM config_info WHERE tenant_id LIKE ? OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY]; nested exception is java.sql.SQLSyntaxErrorException: Column 'ENCRYPTED_DATA_KEY' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE statement then 'ENCRYPTED_DATA_KEY' is not a column in the target table.;caused: Column 'ENCRYPTED_DATA_KEY' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE statement then 'ENCRYPTED_DATA_KEY' is not a column in the target table.;caused: Column 'ENCRYPTED_DATA_KEY' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE statement then 'ENCRYPTED_DATA_KEY' is not a column in the target table.;

**Comment by KomachiSion** [comment]
Please check the sql file and you database table struecture before do upgrade.
