### ISSUE TITLE
关于权重（weight）= 0 的处理

### ISSUE THREAD

**Issue by limng06** [alibaba/nacos#10628]
当权重为0时候，是否可能将这个实例作为备选backup，即当其它服务都不可用状态下的备选，类似nginx的backup。

When the weight is 0, can this instance be considered as a backup as a standby in case other services are unavailable? Similar to how Nginx uses backup servers when the main server fails.

**Comment by KomachiSion** [comment]
建议您使用元数据来实现，权重的含义主要用来控制流量。

**Comment by 985492783** [comment]
可以通过gateway和metadata来实现
