### ISSUE TITLE
无法添加角色为ROLE_ADMIN的用户

### ISSUE THREAD

**Issue by Accelerator96** [alibaba/nacos#10625]
业务中使用中需要有一个用户名不为'nacos'的 ROLE_ADMIN用户
但是创建的时候发现
<img width="1057" alt="image" src="https://github.com/alibaba/nacos/assets/13599846/b69347ea-adc4-4fe4-8c2e-c96673020c39">

然后去看了下代码
<img width="813" alt="image" src="https://github.com/alibaba/nacos/assets/13599846/8bf8ad8b-e6fe-4cb5-87ee-fa0a8ffe124e">

是出于什么考虑不允许添加角色为ROLE_ADMIN的用户呢？
内置数据库下如果需要添加这类用户，该怎么做？

**Comment by YunWZ** [comment]
只能通过数据库添加

**Comment by Accelerator96** [comment]
接口权限能放开嘛？ 需要通过api的形式添加管理员用户。生产环境上操作数据库有时候会很麻烦。

**Comment by KomachiSion** [comment]
默认鉴权插件不允许添加管理员用户， 可以自行实现鉴权插件，按照实际使用需求扩展。
