### ISSUE TITLE
麒麟V10下，loongarch64 龙芯架构， librocksdbjni-linux64.so:无法打开共享对象文件

### ISSUE THREAD

**Issue by ljh205sy** [alibaba/nacos#10630]
麒麟V10下，loongarch64 龙芯架构， librocksdbjni-linux64.so:无法打开共享对象文件
[root@vap test]# uname  -a
Linux vap.kafka.com.cn 4.19.90-52.22.sm3.03.v2207.a.ky10.loongarch64 #1 SMP Sun May 14 15:09:34 CST 2023 loongarch64 loongarch64 loongarch64 GNU/Linux

nacos version:  2.2.2
jraft-core-1.3.12
rocksdbjni-7.10.2.jar

在麒麟的操作系统里面，使用龙芯的LOONGARCH64架构，出现了这样的一个异常，
Caused by: java.lang.UnsatisfiedLinkError: /opt/test/rocksdb/librocksdbjni-linux64.so: /opt/test/rocksdb/librocksdbjni-linux64.so: 无法打开共享对象文件: 没有那个文件或目录 (Possible cause: can't load AMD 64-bit .so on a LOONGARCH64-bit platform)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)  

 Linux loongarch64 好像是对rocksdb不支持，有好的意见吗？

**Comment by ljh205sy** [comment]
![image](https://github.com/alibaba/nacos/assets/25653599/f01eb9f8-0b60-4044-81d4-2297b7c9e41a)
错误截图如上

**Comment by KomachiSion** [comment]
可以自行切换至其他raft log 实现， jraft社区提供了其他的实现类型

比如 https://github.com/sofastack/sofa-jraft/tree/master/jraft-extension/java-log-storage-impl

**Comment by ljh205sy** [comment]
![image](https://github.com/alibaba/nacos/assets/25653599/a83c5c64-09cc-485d-a7e0-829c74485f4b)
RocksDB在该机器下重新编译，重新生成rocksDBJNI， 
# 指定librocksdbjni.so文件路径，如果没有该文件，会从jar文件内查找，最后会放到/tmp目录下。tmp/librocksdbjni.so没有权限
JAVA_OPT="${JAVA_OPT} -Djava.library.path=${BASE_DIR}/target"

编译版本：rocksdb-7.10.2
jraft版本： 1.3.13
<dependency>
    <groupId>com.alipay.sofa</groupId>
    <artifactId>jraft-parent</artifactId>
    <version>1.3.13</version>
</dependency>

**Comment by wuyad** [comment]
> ![image](https://private-user-images.githubusercontent.com/25653599/245644440-a83c5c64-09cc-485d-a7e0-829c74485f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjQ1NjYsIm5iZiI6MTcwMTE2NDI2NiwicGF0aCI6Ii8yNTY1MzU5OS8yNDU2NDQ0NDAtYTgzYzVjNjQtMDljYy00ODVkLWE3ZTAtODI5Yzc0NDg1ZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA5Mzc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MzVmZmY3M2IwODQzYTljYTRmZWJjODNlZWE4NTVhYWUxOGRiMTJlNWNiNDYwYWI2OGU3MTcwZDQ5YTQ2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P691GGRcSjrZH8M4Y8Y2yYI-7D4tPpiIP9VKu52sj54) RocksDB在该机器下重新编译，重新生成rocksDBJNI，
> 
> # 指定librocksdbjni.so文件路径，如果没有该文件，会从jar文件内查找，最后会放到/tmp目录下。tmp/librocksdbjni.so没有权限
> JAVA_OPT="${JAVA_OPT} -Djava.library.path=${BASE_DIR}/target"
> 
> 编译版本：rocksdb-7.10.2 jraft版本： 1.3.13 com.alipay.sofa jraft-parent 1.3.13

现在解决了没？可以在龙芯下使用了吗？

**Comment by zhangshdn** [comment]
> 可以自行切换至其他raft log 实现， jraft社区提供了其他的实现类型
> 
> 比如 https://github.com/sofastack/sofa-jraft/tree/master/jraft-extension/java-log-storage-impl

能具体说下如何操作吗

**Comment by pandaoknight** [comment]
宿主机：loongarch64 + openEuler24.03，可以简易修改rocksdb的代码后，编译出所需 librocksdbjni*.so 供jraft和nacos 2.3.0使用。

待会儿提供镜像出来。
