### ISSUE TITLE
2.0.4升级到2.2.3，使用的Derby ，控制台不可用

### ISSUE THREAD

**Issue by fsckzy** [alibaba/nacos#10635]
因为是测试环境，使用的 derby，没有用外置的 mysql。
从 2.0.4升级到2.2.3，数据是从2.0.4的 data/derby-data 拷贝到 2.2.3 的 data/derby-data 目录下，打开控制台，使用旧密码登录成功，但随便点击一个提示

`caused: serialize page error, dataId=, group=;caused: PreparedStatementCallback; bad SQL grammar [SELECT id,data_id,group_id,tenant_id,app_name,content,encrypted_data_key FROM config_info WHERE tenant_id LIKE ? OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY]; nested exception is java.sql.SQLSyntaxErrorException: Column 'ENCRYPTED_DATA_KEY' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE statement then 'ENCRYPTED_DATA_KEY' is not a column in the target table.;caused: Column 'ENCRYPTED_DATA_KEY' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE statement then 'ENCRYPTED_DATA_KEY' is not a column in the target table.;caused: Column 'ENCRYPTED_DATA_KEY' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE statement then 'ENCRYPTED_DATA_KEY' is not a column in the target table.;`

![image](https://github.com/alibaba/nacos/assets/34021474/fd20ffc7-f388-4bb2-81ba-14fd318a1ac6)

控制台能登录，所以数据是可用的，但是不能点击功能，是不是数据库未做兼容？

**Comment by onewe** [comment]
看样子是差字段, 建议对比一下 https://github.com/alibaba/nacos/blob/develop/distribution/conf/derby-schema.sql

**Comment by KomachiSion** [comment]
derby 应该是自动建表和升级表结构的，是我记错了还是插件化改出问题了？社区可以帮忙排查下。

**Comment by onewe** [comment]
数据是从 2.0.4的 data/derby-data 拷贝到 2.2.3 的 data/derby-data 目录下 这种操作估计不会自动增加 `ENCRYPTED_DATA_KEY ` 字段

**Comment by fsckzy** [comment]
从控制台把所有的配置导出，然后启动新版的nacos，再导入这些配置文件，用户密码之类的重新手动配置，目前发现的方法。
