### ISSUE TITLE
将dubbo服务通过代理层按服务名路由到多个相互无感知的nacos集群，有没有有过类似经验的

### ISSUE THREAD

**Issue by goku0502** [alibaba/nacos#10636]
目前使用nacos作为dubbo2.x的注册中心，考虑后续服务数目增加，使用代理层将服务路由到不同的nacos集群，代理层可横向扩展，此方案是否有缺陷？

**Comment by KomachiSion** [comment]
那你如何做发现， 发现也通过代理层吗？这样代理层会变成一个大中心，稳定性依然是需要保证的。

**Comment by goku0502** [comment]
> 那你如何做发现， 发现也通过代理层吗？这样代理层会变成一个大中心，稳定性依然是需要保证的。

对的，所有客户端请求都会由代理转发给nacos集群。稳定性方面目前主要是部署上代理层集群前置了一个F5，实现上碰到连接nacos超时也会进行重试，配合客户端本身的重试。大佬帮忙看看当前这种方案还有哪些功能、性能、稳定性或者其他方面欠缺的点？

**Comment by KomachiSion** [comment]
只要能保证代理层本身的高可用和稳定性，问题就不会太大。最终评估还是要看实际的使用场景。

**Comment by KomachiSion** [comment]
No more response from author.
