### ISSUE TITLE
Nacos 2.2.3 开启认证之后，服务无法注册，user not found!

### ISSUE THREAD

**Issue by jinghao198851** [alibaba/nacos#10637]
项目中使用的版本，springboot 2.6.11  springcloud 2021.0.4  springcloudAlibaba 2021.0.4.0  nacos 2.1.0 根据项目需要，现要把nacos升级到2.2.3 并开启认证，同时要求数据库密码加密、通过https访问：

1、	通过在nacos-config中ExternalDataSourceProperties.java 的poolProperties.setPassword(getOrDefault(password, index, password.get(0)).trim());中添加解密方法实现数据库密码加密。
2、	通过在nacos-console中的resource新增jks文件，application.properties添加ssl相关配置完成https的访问

完成后打包部署，nacos启动后，在配置文件application.properties中修改：
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.server.identity.key=authKey
nacos.core.auth.server.identity.value=authSecurity
nacos.core.auth.plugin.nacos.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789
开启认证。
微服务中首先排除原nacos-client依赖，并引入nacos-client 2.2.3版本的依赖， 然后在配置文件中添加spring.cloud.nacos.username和spring.cloud.nacos.password 发现在启动时，报错：
com.alibaba.nacos.api.exception.NacosException: user not found!
![image](https://github.com/alibaba/nacos/assets/43603918/f9605d8c-9bda-40d2-af9c-97744e6ab534)
也尝试过添加spring.cloud.nacos.discoviery.username和spring.cloud.nacos.discoviery.password，也是报相同错误。

**Comment by jinghao198851** [comment]
测试可能是https的问题，如果不改https功能，则可以注册上。那么https应该怎么配置才能不影响注册呢？

**Comment by achi1879** [comment]
我也遇到这个问题了，请问怎么解决呢
