### ISSUE TITLE
修改nacos配置后，控制台一直刷报错ERROR [yh-commodity,,,] 1 --- [ternal.notifier] c.a.nacos.client.config.impl.CacheData   : [config_rpc_client] [notify-error] dataId=blade-prod.yaml, group=DEFAULT_GROUP, md5=95802cc5b361e2bc30c7d8933e22d9da, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@127fa701 tx=null

### ISSUE THREAD

**Issue by shenningfly** [alibaba/nacos#10632]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by shenningfly** [comment]
![image](https://github.com/alibaba/nacos/assets/84237129/fdbaa321-dfd7-4ad9-889d-260a68df4994)

**Comment by shenningfly** [comment]
使用2.0.0版本

**Comment by KomachiSion** [comment]
你实现的配置回调的listener一直在抛出异常，请自查Listener所抛出的异常并解决。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by supernf** [comment]
I encountered the same problem when starting a project with jar。no problem when starting it with idea,

**Comment by firmianaQ** [comment]
解决了吗 一样的问题
