### ISSUE TITLE
spring cloud gateway整合spring cloud security oauth2 jwt，配置中心从eureka迁到nacos之后，通过网关走openfeign调用服务，token无法中继

### ISSUE THREAD

**Issue by huanti** [alibaba/nacos#10633]
spring boot：2.3.12.RELEASE
spring cloud：Hoxton.SR12
spring cloud alibaba：2.2.9.RELEASE
nacos：2.1.0
现象：1、项目用spring cloud gateway, spring cloud security oauth2做了jwt模式的认证和鉴权，将注册中心从eureka换到了nacos，认证接口正常，但是通过网关用网关的ip的方式openfeign调用A服务的接口，A服务中无法获取到SecurityContextHolder中已经认证的用户信息，信息为空。
2、如果A服务和网关的ip相同（在nacos的服务详情中看到的注册的ip相同），则通过网关用ip方式openfeign调用A服务，则可以获取到用户信息。
3、通过网关调用服务，如果在nacos上注册的服务的ip和网关是相同ip，或者说和认证服务的ip相同，则openfeign获取用户信息没有问题，ip不同，则无法获取用户信息。

**Comment by KomachiSion** [comment]
业务之间的调用异常，和nacos无关，nacos只负责发现。业务自己进行的ip比对要业务自己进行处理。

**Comment by huanti** [comment]
请问一下，为什么eureka可以，换了nacos就不行了，有没有哪里需要特殊处理的，网关和在nacos注册的服务的ip相同就可以，ip不同就不行了，谢谢了

**Comment by huanti** [comment]
你好，请问一下，为什么eureka可以，换了nacos就不行了，有没有哪里需要特殊处理的，网关和在nacos注册的服务的ip相同就可以，ip不同就不行了，谢谢了
















在 2023-06-13 09:42:14，"杨翊 SionYang" ***@***.***> 写道：

业务之间的调用异常，和nacos无关，nacos只负责发现。业务自己进行的ip比对要业务自己进行处理。

**Comment by KomachiSion** [comment]
这个和注册中心没有关系， 问题在网关的适配逻辑上，要看网关的逻辑。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
