### ISSUE TITLE
open-api发布配置出错

### ISSUE THREAD

**Issue by waterlang** [alibaba/nacos#10646]
open-api使用的是form-data模式，我的content存储的是xml格式，我请求的原始报文：
`http://192.168.22.129:8848/nacos/v1/cs/configs?tenant=6aef8a96-4515-4f27-98d8-80aa3603bacf&dataId=demo_rule&group=DEFAULT_GROUP&content=<?xml version="1.0" encoding="utf-8"?>
<flow> 
  <nodes> 
    <node id="s1" name="普通脚本" type="script" language="groovy"> <![CDATA[
                def a=3;
                def b=2;
                userDownloadDTO.setUsers(a*b);
            ]]> </node>  
    <node id="s2" name="选择脚本" type="if_script" language="groovy"> <![CDATA[
                def count = userDownloadDTO.getUsers();
                return false;
            ]]> </node>  
    <node id="s3" name="条件脚本" type="script" language="groovy">userDownloadDTO.setUsers(100);</node>
  </nodes>  
  <chain name="chain1">THEN(s1,s2,s3);</chain> 
</flow>
&type=xml`

这个content直接通过nacos的控制台添加是完全正常的。

`<?xml version="1.0" encoding="utf-8"?>
<flow> 
  <nodes> 
    <node id="s1" name="普通脚本" type="script" language="groovy"> <![CDATA[
                def a=3;
                def b=2;
                userDownloadDTO.setUsers(a*b);
            ]]> </node>  
    <node id="s2" name="选择脚本" type="if_script" language="groovy"> <![CDATA[
                def count = userDownloadDTO.getUsers();
                return false;
            ]]> </node>  
    <node id="s3" name="条件脚本" type="script" language="groovy">userDownloadDTO.setUsers(100);</node>
  </nodes>  
  <chain name="chain1">THEN(s1,s2,s3);</chain> 
</flow>
`

**Comment by KomachiSion** [comment]
控制台发布配置，sdk发布配置使用的就是openAPI的发布配置。 估计是你直接调用的时候，没有把内容放在body上，放在uri上，但是又没有做uriencode导致的。 应该是使用问题。

**Comment by waterlang** [comment]
恩，使用问题，没uriencode，放body就Ok了。
