### ISSUE TITLE
服务列表中无服务

### ISSUE THREAD

**Issue by civetming** [alibaba/nacos#10645]
版本NACOS2.1.1

我是用docker部署的，控制台服务列表中无服务，实际功能是正常的，已经开了端口8848，9848
 
![image](https://github.com/alibaba/nacos/assets/44012892/e6906b00-f08e-4604-b93e-11b5fb08be96)

服务查询接口报错，返回503
**server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]**

**Comment by KomachiSion** [comment]
说明集群部署有问题， distro协议还没有初始化完， 我猜测是集群间通信有故障，导致distro的快照始终无法拉到，所以distro协议一直是非ready的状态。

**Comment by wilsonwu** [comment]
看一下nacos-server启动日志是否有详细信息

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
