### ISSUE TITLE
HTML injection cause URL redirection

### ISSUE THREAD

**Issue by chriscczhou** [alibaba/nacos#10640]
**Describe the bug**
 - Test with nacos version 2.2.1.
 - Nacos  three parameters  `pageNo`、`pageSize`、`search` have HTML injection cause URL redirection.

**Expected behavior**
The page is print error.

**Actually behavior**
But evil people can use one of three parameters to achieve URL redirection.

**How to Reproduce**
Payload:`/nacos/v1/auth/users?pageNo=%3Cmeta%20http-equiv=%22refresh%22%20content=%220;url=http://www.baidu.com%22%3E&pageSize=9&search=blur1`

**Comment by DarrenLuo** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
I'm confused for this behavior and whether need to fix.

A Attacker run an attack command like `/nacos/v1/auth/users?pageNo=%3Cmeta%20http-equiv=%22refresh%22%20content=%220;url=http://www.baidu.com%22%3E&pageSize=9&search=blur1` to nacos through web browser, and result the attacker get a result that his/her web browser redirect to `baidu`.

It's a very confused operation, I think it's no need to fix this confused problem.
