### ISSUE TITLE
能够只在页面开启认证，nacos客户端不开启认证，就像2.0.1版本一样

### ISSUE THREAD

**Issue by john1337** [alibaba/nacos#10653]
能够只在页面开启认证，nacos客户端不开启认证，就像2.0.1版本一样，现在最新的2.2.3版本貌似一旦开启auth认证，客户端也需要填写用户名密码了

**Comment by 985492783** [comment]
你说的是secretKey？客户端不可能不用密码的，页面和客户端走的都是http和rpc的统一鉴权接口

**Comment by john1337** [comment]
> 你说的是secretKey？客户端不可能不用密码的，页面和客户端走的都是http和rpc的统一鉴权接口

secretKey是key，跟我说的验证没关系，这个key只能说是生成token的密钥而已

**Comment by KomachiSion** [comment]
那有什么意义， 接口全部不鉴权， 所有人都可以调用， 页面只加了一个无用的登录页其实反而是严重的误导，这点在change log中说的很清楚。

如果你们的需求中确实需要，可以自定义鉴权插件来实现。
