### ISSUE TITLE
responsibleTag.hashCode() % Integer.MAX_VALUE

### ISSUE THREAD

**Issue by sid659** [alibaba/nacos#10661]
DistroMapper：
private int distroHash(String responsibleTag) {
        return Math.abs(responsibleTag.hashCode() % Integer.MAX_VALUE);
}
这里取余是?    不应该是return responsibleTag.hashCode() & Integer.MAX_VALUE吗？

**Comment by DarrenLuo** [comment]
我猜测这里是为了获取一个hash值的绝对值，即一个正整数，但是会有一个特殊的情况，Math.abs(Integer.MIN_VALUE) 的返回值是 -2147483648，需要做一个取余操作得到 1

**Comment by KomachiSion** [comment]
> 我猜测这里是为了获取一个hash值的绝对值，即一个正整数，但是会有一个特殊的情况，Math.abs(Integer.MIN_VALUE) 的返回值是 -2147483648，需要做一个取余操作得到 1

基本是这个问题， Java中的hashCode会出现负数，负数取余数是负数， 因此需要abs一下取绝对值。

多数情况下， `Math.abs(responsibleTag.hashCode() % Integer.MAX_VALUE);` 和 `responsibleTag.hashCode() & Integer.MAX_VALUE` 是相等的，但是负数的情况下，两者的结果不一致。

所以这里需要保持算法的一致性，避免负载不均。
