### ISSUE TITLE
由于AP模式spring environment刷新配置项时拉取的是旧的配置文件，但缓存为最新的配置文件，导致不再重新拉取

### ISSUE THREAD

**Issue by qnnn** [alibaba/nacos#10665]
各位老师好，最近遇到个问题，方便帮忙看看吗。版本 1.4.1
简单描述下就是

1. 配置变更，长轮询监听后第一次拉取拉取到的是最新的配置文件内容。此时触发NacosContextRefresher的AbstractSharedListener监听事件去刷新spring的environment。（第一次配置拉取，为最新配置文件内容）

2. 但在LegacyContextRefresher#updateEnvironment去刷新environment时，是重新构建一个applicationContext，此时由于ap模式，可能拉取的是旧的配置文件。此时refresh keys changed为空（第二次配置拉取，为旧配置文件内容）

3. 此时由于ClientWorker的CacheMap已为最新配置文件内容和md5，所以客户端不会重新触发配置变更，导致environment对象中的配置项并没有得到变更。

   

   在spring cloud alibaba中看到类似的issue，是说在这边提。
   [client端会请求两次server端获取content](https://github.com/alibaba/spring-cloud-alibaba/issues/2230)

**Comment by KomachiSion** [comment]
这是spring cloud的bug， nacosclient在listner的时候会返回一个保证绝对一致的配置。 但是spring cloud不使用，而是自身再去get一次配置， 这个就越过了nacos的一致性机制，没法100%保证正确，

https://github.com/alibaba/spring-cloud-alibaba/issues/3322

**Comment by thetcc** [comment]
我在springboot 集成spring-cloud版的nacos starter 也遇到了这个问题，客户端已收到nacos变更的推送，缓存里看到配置已经变成新的了，但是LegacyContextRefresher#updateEnvironment去刷新environment时，获取到的是旧的配置文件。

请问这个是怎么解决的呢
