### ISSUE TITLE
nacos2.2.3 启动报错http error, code=403,msg=user not found!,dataId=application-pro.yml,group=DEFAULT_GROUP,tenant=

### ISSUE THREAD

**Issue by YANGQINZ** [alibaba/nacos#10673]
nacos2.2.3 启动报错http error, code=403,msg=user not found!,dataId=application-pro.yml,group=DEFAULT_GROUP,tenant=

配置文件
# Tomcat
server:
  port: 8081

# Spring
spring:
  application:
    # 应用名称
    name: xxx
  #profiles:
    # 环境配置
    #active: pro
  config:
    activate:
      on-profile: pro
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  main:
    allow-circular-references: true
  cloud:
    nacos:
      # 配置中心地址
      discovery:
        username: nacos
        password: nacos
        # 注册组
        group: DEFAULT_GROUP
        namespace: public
        server-addr: xxx:8848
      config:
        username: nacos
        password: nacos
        # 配置组
        group: DEFAULT_GROUP
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs[0]:
          data-id: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          refresh: true
        shared-configs[1]:
          data-id: application-secret-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
          refresh: true
        context-path: /nacos
        namespace: public
        server-addr: xxx:8848
    gateway:
      httpclient:
        max-header-size: 10240

**Comment by shixuxi** [comment]
鉴权不对的样子

**Comment by Simon-HZ** [comment]
我也碰到这个问题，而且昨天似乎还没出现，使用的nacos server 版本2.2.3，但是client版本2.1.0

**Comment by KomachiSion** [comment]
`user not found!` your usage problem or configuration problem.

**Comment by Simon-HZ** [comment]
> `user not found!` your usage problem or configuration problem.

我是以nacos源码2.2.3本地进行编译，然后nacos-plugin 含加密插件的工程修改依赖的nacos版本号为2.2.3， install本地仓库nacos-aes-encryption-plugin，然后业务工程引入这个新打的加密插件访问没有配置变动的nacos服务也会报错403，请问nacos和nacos-plugin有推荐的项目引用版本么？怀疑是依赖版本问题

**Comment by czy0505** [comment]
我也有同样的问题，需要排查一下spring-cloud-starter-alibaba-nacos-discovery，spring-cloud-starter-alibaba-nacos-config包引入的版本是不是匹配。我改成2.2.9.RELEASE这个版本，就没有问题了。
如果引入了spring-cloud-alibaba-dependencies，直接改成2.2.9RELEASE也可以。
![image](https://github.com/alibaba/nacos/assets/30620076/bb779919-1373-4602-89b5-722ccfcd8980)

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by ChenAiwei** [comment]
jackson-databind 升级到[2.15.2](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.15.2)有问题，会提示 code=403,msg=user not found! 但是版本降级后就可以

**Comment by fengyuke** [comment]
jackson-databind升级后，jackson-core也要同步升级，否则是会报错403，示例：
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-core</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <artifactId>jackson-databind</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
            <version>2.16.0</version>
        </dependency>
        <dependency>
            <artifactId>jackson-core</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
            <version>2.16.0</version>
        </dependency>

**Comment by gyjx** [comment]
您这个问题最后怎么解决的？我也遇到这个问题了。
https://github.com/alibaba/nacos/issues/13056

**Comment by ching7** [comment]
> 您这个问题最后怎么解决的？我也遇到这个问题了。 [#13056](https://github.com/alibaba/nacos/issues/13056)

如果检查确认配置和nacos服务没有问题，一般是由于jackson等版本依赖冲突了，可以检查一下依赖树
