### ISSUE TITLE
缺少nacos最新版本与spring cloud nacos config/nacos discovery版本的对应关系

### ISSUE THREAD

**Issue by jiehao2019** [alibaba/nacos#10676]
## Issue Description

 文档

### Describe what happened (or what feature you want)
nacos 官网上（ https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html ）说Nacos与spring-cloud-starter-alibaba-nacos-config/ spring-cloud-starter-alibaba-nacos-discovery 的版本对应关系在spring-cloud-alibaba的wiki上维护的，网址是https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E ，如下图
![image](https://github.com/alibaba/nacos/assets/60006900/2f53aeba-274f-4970-b761-1b098fbd9caa)
但上图中nacos 2.x的版本最新只到2.2.1， 1.x的版本最新只到1.4.2. 而目前2.x的最新版本是2.2.3，1.x的最新版本是1.4.6. 也就是说缺少2.2.2/2.2.3，1.4.3/1.4.4/1.4.5/1.46这几个版本对应关系。

另外，在maven中央仓库上查看spring-cloud-starter-alibaba-nacos-discovery最近的几个版本，可以看到其引用的nacos版本分别如下：
![image](https://github.com/alibaba/nacos/assets/60006900/40fa2ceb-2151-4297-b3bc-284559cc8f35)

- spring-cloud-starter-alibaba-nacos-discovery版本为2020.0.RC1， nacos-client版本为1.4.1
- spring-cloud-starter-alibaba-nacos-discovery版本为2021.0.1.0， nacos-client版本为1.4.2
- spring-cloud-starter-alibaba-nacos-discovery版本为2021.0.4.0， nacos-client版本为2.0.4
- spring-cloud-starter-alibaba-nacos-discovery版本为2021.0.4.0， nacos-client版本为2.2.0
- spring-cloud-starter-alibaba-nacos-discovery版本为[2021.1](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2021.1)， nacos-client版本为1.4.1
- spring-cloud-starter-alibaba-nacos-discovery版本为[2022.0.0.0-RC1](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2022.0.0.0-RC1)， nacos-client版本为2.2.1-RC
- spring-cloud-starter-alibaba-nacos-discovery版本为[2022.0.0.0-RC1](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery/2022.0.0.0-RC2)， nacos-client版本为2.2.1

也没有2.2.2/2.2.3，1.4.3/1.4.4/1.4.5/1.46这几版本。还是说这几个版本可以和上述的discovery版本都兼容？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
It depend SCA release. Please move to SCA community.

**Comment by KomachiSion** [comment]
Normally, all version can adapt for SCA
