### ISSUE TITLE
怎么禁用端口

### ISSUE THREAD

**Issue by hw1992** [alibaba/nacos#10675]
一般使用时该端口为Nacos集群间Raft协议的通信端口，不承载客户端请求，因此老版本可以通过禁止该端口

**Comment by wilsonwu** [comment]
建议通过系统防火墙操作，如果用k8s部署就更容易在svc层操作。

**Comment by KomachiSion** [comment]
端口不能完全禁止， 是禁止从外部访问，集群内还是需要访问的。

禁止方式依据部署不同有很多方式可以禁止，这个可以询问你们自己环境的运维工程师。
