### ISSUE TITLE
[Question] Data skewness may occur during server node gray upgrades

### ISSUE THREAD

**Issue by Daydreamer-ia** [alibaba/nacos#10670]
**Describe the bug**
在1.4.x版本，Distro协议可以把心跳和注册的流量压力分散到集群的各个节点。但是在2.x版本，由于建立的通信通道是长连接，Distro协议不再分散流量到集群内，而是直接对请求进行处理。

故障场景：如果要对集群节点进行灰度升级的话，客户端会从下线的节点切换到别的节点，切换后建立的又是长链接，由于服务端节点是灰度进行的(逐台进行)，会不会最后导致压力全部连接到集群中的一台或者两台，造成数据倾斜的问题？
异常表现：个别节点内存和CPU占用极高，其他节点负载很低

问题：客户端或者服务端有措施可以规避或者预防这种情况发生吗？

In version 1.4.x, the Distro protocol can distribute the traffic of heartbeat and registration to various nodes in the cluster. However, in version 2.x, due to the use of long connections for communication, the Distro protocol no longer distributes traffic to other nodes in the cluster, but processes requests directly.

Scenario: If gray upgrade is performed on nodes in the cluster, the client will switch from the offline node to another node. Since the server nodes are upgraded one by one, will this cause the pressure to be concentrated on one or two nodes in the cluster and cause data skewness?

Symptom: high memory and CPU usage on individual nodes, while other nodes have low loads.

Question: Are there any measures that clients or servers can take to mitigate or prevent this scenario from happening?

**Comment by KomachiSion** [comment]
2.x has reload connection api, you can call the api to reload the connection to other nodes step by step.

Or implement control plugin by yourself. If you found one node in cluster has low connection, other node can reject new connection and reload to the low pressure  node.

**Comment by Daydreamer-ia** [comment]
> 2.x has reload connection api, you can call the api to reload the connection to other nodes step by step.
> 
> Or implement control plugin by yourself. If you found one node in cluster has low connection, other node can reject new connection and reload to the low pressure node.

i see. Em... Maybe we need to improve the document about `ServerLoaderController` which describes this in <a href="https://nacos.io/zh-cn/docs/open-api.html">运维指南<a/>

**Comment by KomachiSion** [comment]
> > 2.x has reload connection api, you can call the api to reload the connection to other nodes step by step.
> > Or implement control plugin by yourself. If you found one node in cluster has low connection, other node can reject new connection and reload to the low pressure node.
> 
> i see. Em... Maybe we need to improve the document about `ServerLoaderController` which describes this in [运维指南](https://nacos.io/zh-cn/docs/open-api.html)

Yes, Welcome you add it into document.

**Comment by stone-98** [comment]
如果没人优化该文档，我将会对它进行优化。

**Comment by stone-98** [comment]
@i will slove it@
