### ISSUE TITLE
2.2.3版本nacos服务端长时间运行，堆外内存一直增长。运行10+个小时堆外内存占用达到了堆内存大小的2倍以上，是否在使用netty的直接内存时存在内存泄露

### ISSUE THREAD

**Issue by zhangrenbin** [alibaba/nacos#10671]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
那你要问grpc了， nacos没有直接使用netty 使用的是grpc

你可以通过`-XX:MaxDirectMemorySize=` 来设置最大堆外内存大小。
