### ISSUE TITLE
Nacos Docker可以配置Ldap进行权限认证吗？

### ISSUE THREAD

**Issue by L2421800049** [alibaba/nacos#10678]
nacos镜像 nacos/nacos-server:v2.2.0
ldap版本号 3
期望在docker中配置环境变量，启用ldap进行身份认证

**Comment by Daydreamer-ia** [comment]
只需要把宿主机的配置文件的 `nacos.core.auth.system.type`、 `nacos.core.auth.enabled` 和 `nacos.core.auth.ldap` 前缀的配置进行配置，然后把宿主机的配置挂载映射进 `Nacos` 容器即可

**Comment by L2421800049** [comment]
感谢，已经成功
