### ISSUE TITLE
请教一个关于NamingFactory.createNamingService()的问题  

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#10681]
这个为什么使用反射去构建而不是使用 new 关键字？ 

有什么说法吗？

**Comment by 985492783** [comment]
client依赖api，而NamingFactory在api-module里面，只能通过反射加载类的方式去获取实例，其他没啥

**Comment by MangerLe** [comment]
> client依赖api，而NamingFactory在api-module里面，只能通过反射加载类的方式去获取实例，其他没啥

明白了，多谢
