### ISSUE TITLE
the instance still receives dubbo request after set it status to down in nacos

### ISSUE THREAD

**Issue by luger1990** [alibaba/nacos#10683]
![nacos](https://github.com/alibaba/nacos/assets/2096878/86428955-3ced-477f-8754-3e43f3050ad6)

the instance still receives dubbo request after set it status to down in nacos， just like picture above.please take a look.

**Comment by PRANRAVEE** [comment]
ส่งจากโทรศัพท์มือถือ Huawei ของฉ-------- ข้อความต้นฉบับ --------จาก: Luger Smith ***@***.***>วันที่: ส. 24 มิ.ย. 2023 18:58ถึง: alibaba/nacos ***@***.***>สำเนา: Subscribed ***@***.***>เรื่อง: [alibaba/nacos] the instance still receives dubbo request after set it status to down in nacos (Issue #10683)

the instance still receives dubbo request after set it status to down in nacos， just like picture above.please take a look.

**Comment by KomachiSion** [comment]
dubbo not use the weight of nacos, dubbo has their own weight and route rule in `metadata`.

But the change `enabled` is work, when the enabled is false, nacos will not push this instance to dubbo.

**Comment by luger1990** [comment]
> ![nacos](https://user-images.githubusercontent.com/2096878/248471912-86428955-3ced-477f-8754-3e43f3050ad6.png)
> 
> the instance still receives dubbo request after set it status to down in nacos， just like picture above.please take a look.

![image](https://github.com/alibaba/nacos/assets/2096878/f1cac7dc-c82c-4bdd-b2ed-1edb8f3528c3)
where can i change the status of `enabled`

**Comment by KomachiSion** [comment]
> ![nacos](https://user-images.githubusercontent.com/2096878/248471912-86428955-3ced-477f-8754-3e43f3050ad6.png)
> 
> the instance still receives dubbo request after set it status to down in nacos， just like picture above.please take a look.

your right red frame

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
