### ISSUE TITLE
Nacos文档->控制台手册语句错误

### ISSUE THREAD

**Issue by renliangyu857** [alibaba/nacos#10699]
**Describe the bug**
![1687835270(1)](https://github.com/alibaba/nacos/assets/28523136/f05eb44e-1e8c-482f-8752-1a8b87120634)
方面应改为方便

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by 985492783** [comment]
welcome to contribute
