### ISSUE TITLE
域名不支持相对路径

### ISSUE THREAD

**Issue by hidao** [alibaba/nacos#10696]
比如说我配置server-addr：http://aaa.com:80/nacos/ ，是用不了的

**Comment by 985492783** [comment]
server-addr格式为ip:port,不需要带url

**Comment by KomachiSion** [comment]
为什么要这么配置，参数意思应该是address， 不是uri。

**Comment by hidao** [comment]
> 为什么要这么配置，参数意思应该是address， 不是uri。

在生产环境，我们或许不这么配置，但在开发测试环境中，我们的基础服务都在k8s中，并不会每一个项目都会配置一个独立的域名（由于权限问题每次需要运维人员去配置域名，需要等待其他人的时间），所以而是使用同一个域名不同的路径来分发项目请求。

**Comment by KomachiSion** [comment]
所以这是你们开发环境中的特殊场景，这其实并不符合标准，如果需要这么使用，就需要你们自己修改做适配了。
