### ISSUE TITLE
Repeat registering instance caused short period data inconsistency

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#10693]
**Describe the bug**

It's found in Nacos Distro protocol, if the client registered the same instance twice, Nacos servers would have about 2 seconds period data inconsistency after 3 minutes of the second registration.

**Expected behavior**

No inconsistency.

**Actually behavior**

inconsistency happened

**How to Reproduce**

1. register ephemeral instances ins.1 and ins.2 to service svc.1 to Nacos cluster(should be a multiple nodes Nacos cluster)
2. start a client subscribe the service svc.1 (make sure it connected to another Nacos node other than the registrater.)
3. wait for 10 seconds
4. register the instance ins.1 to Nacos cluster
5. wait for 3 minutes
6. client would receive a offline notification of ins.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version nacos-server 2.1.2, nacos-client 2.1.2
 - Module naming
 - SDK original

**Additional context**

This bug is related to the Distro protocol revision refresh mechanism, seems for the same instance registration, the updated revision would not be spread to other Nacos nodes.

The only one revision update is triggered here:

```java
    private static void processBatchInstanceDistroData(Set<Service> syncedService, Client client,
            ClientSyncData clientSyncData) {
        BatchInstanceData batchInstanceData = clientSyncData.getBatchInstanceData();
        if (batchInstanceData == null || CollectionUtils.isEmpty(batchInstanceData.getNamespaces())) {
            Loggers.DISTRO.info("[processBatchInstanceDistroData] BatchInstanceData is null , clientId is :{}",
                    client.getClientId());
            return;
        }
        ...
        client.setRevision(clientSyncData.getAttributes().<Integer>getClientAttribute(ClientConstants.REVISION, 0));
    }
```

And the beat timestamp of the instance is not updated because the revision is not identical:

```java
    public boolean verifyClient(DistroClientVerifyInfo verifyData) {
        ConnectionBasedClient client = clients.get(verifyData.getClientId());
        if (null != client) {
            // remote node of old version will always verify with zero revision
            if (0 == verifyData.getRevision() || client.getRevision() == verifyData.getRevision()) {
                client.setLastRenewTime();
                return true;
            } else {
                Loggers.DISTRO.info("[DISTRO-VERIFY-FAILED] ConnectionBasedClient[{}] revision local={}, remote={}",
                        client.getClientId(), client.getRevision(), verifyData.getRevision());
            }
        }
        return false;
    }
```

Then after 3 minutes, the expired client cleaner would consider the instance is dead, and remove it:

```java
    private static class ExpiredClientCleaner implements Runnable {
        
        private final ConnectionBasedClientManager clientManager;
        
        public ExpiredClientCleaner(ConnectionBasedClientManager clientManager) {
            this.clientManager = clientManager;
        }
        
        @Override
        public void run() {
            long currentTime = System.currentTimeMillis();
            for (String each : clientManager.allClientId()) {
                ConnectionBasedClient client = (ConnectionBasedClient) clientManager.getClient(each);
                if (null != client && client.isExpire(currentTime)) {
                    clientManager.clientDisconnected(each);
                }
            }
        }
    }
```

**Comment by nkorange** [comment]
duplicated with https://github.com/alibaba/nacos/issues/10056

**Comment by AngusYGChen** [comment]
mark
