### ISSUE TITLE
专业版的nacos控制台（2.1.2版本），命名空间比较多的情况下，配置管理-配置列表无法展示所有的命名空间，无法对命名空间下的文件进行编辑。

### ISSUE THREAD

**Issue by zhanghj1010** [alibaba/nacos#10691]
![image](https://github.com/alibaba/nacos/assets/137743970/265c1e73-07d3-49cf-9a92-8f37d8e80590)

**Comment by KomachiSion** [comment]
Can you try the newest version? It might fix in new version.

**Comment by DarrenLuo** [comment]
![image](https://github.com/alibaba/nacos/assets/6427009/8cfa5ed9-34f2-442c-8ce8-b7d7128388bd)
我看了一下开发中的版本看起来是修复了这个问题了的
