### ISSUE TITLE
客户端服务注册问题 - client registration issue

### ISSUE THREAD

**Issue by yfh0918** [alibaba/nacos#107]
客户端服务注册后，再断开，然后换个端口号注册 再断开，再换个端口号再注册，这个时候服务器这边所有的服务以及之前断开的服务都还在，

**Comment by xuechaos** [comment]
@yfh0918  hi 问下 的环境信息是那个Nacos版本的，你断开的操作具体是什么？

**Comment by yfh0918** [comment]
@xuechaos用的版本是nacos-server-0.2.1

**Comment by yfh0918** [comment]
@xuechaos 目前断开服务采用Runtime.getRuntime().addShutdownHook 方式

**Comment by yfh0918** [comment]
@xuechaos 断开操作就是直接 kill -9 （这个操作不会调用Runtime.getRuntime().addShutdownHook 的deregister）,我现在 把-9去掉了 采用kill方式 就会调用Runtime.getRuntime().addShutdownHook 的deregister了

**Comment by nkorange** [comment]
kill -9 不会注销实例，已经提了issue #175 来支持这个功能
