### ISSUE TITLE
client 端的快照是否可以支持可配置

### ISSUE THREAD

**Issue by slatonwu** [alibaba/nacos#10700]
Client端的配置信息目前会在本地保存一份的快照，有一些敏感数据是不能在本地缓存的，这个快照是否可以支持多种保存形式或者可以支持不保存快照？

**Comment by 985492783** [comment]
敏感信息可以参考 [配置加密](https://nacos.io/zh-cn/docs/v2/plugin/config-encryption-plugin.html)，应该可以解决你的问题

**Comment by slatonwu** [comment]
是不能存储在客户端本地，不是加不加密的问题，安全上过不了

**Comment by 985492783** [comment]
可以往spring-cloud-alibaba也提个issue问下

**Comment by slatonwu** [comment]
这个保存快照是在nacos-client下进行的，spring-cloud-alibaba是对nacos-client进行的在封装吧

**Comment by KomachiSion** [comment]
call `SnapShotSwitch.setIsSnapShot(false)`, but it will cause can't get any config when nacos server down or the network problem.

**Comment by slatonwu** [comment]
thanks
