### ISSUE TITLE
nacos控制台创建服务，服务列表确不显示

### ISSUE THREAD

**Issue by 1424019919** [alibaba/nacos#10702]
创建一个test服务
![image](https://github.com/alibaba/nacos/assets/79009117/5c69f74c-adfd-4040-8548-3f456360e3e8)
创建完成后服务列表显示为空
![image](https://github.com/alibaba/nacos/assets/79009117/18b713db-eaf2-4926-b9de-b65f659fa1f2)

**Comment by wilsonwu** [comment]
如果一个服务长时间没有实例会被清除，是不是由于这个原因？

**Comment by KomachiSion** [comment]
另外确保命名空间选择正确。

**Comment by 1424019919** [comment]
> 另外确保命名空间选择正确。

这个是在控制台直接创建的服务，不是通过API接口或者客户端启动的服务，应该不存在命名空间错误的情况

**Comment by 1424019919** [comment]
> 如果一个服务长时间没有实例会被清除，是不是由于这个原因？

这个是创建完服务后立刻查看列表，我试了好多次，有时候可以列表中可以看到新创建的服务，但是大部分情况都看不到

**Comment by wilsonwu** [comment]
您说的这个场景我还是比较少使用，都是通过程序注册实例间接创建服务，如果一个服务存在，但是没有实例，感觉也没有太多实用价值

**Comment by 1424019919** [comment]
> 您说的这个场景我还是比较少使用，都是通过程序注册实例间接创建服务，如果一个服务存在，但是没有实例，感觉也没有太多实用价值

hhh,确实没有太大的实用价值，自己重构nacos控制台的时候无意间发现的问题

**Comment by KomachiSion** [comment]
注册和创建服务后，会先存储成实例级别的数据，然后再异步聚合成服务级别的数据，所以会有一定的延迟。
