### ISSUE TITLE
控制台yaml语法

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#10703]
![image](https://github.com/alibaba/nacos/assets/73023513/75f4fef2-6f32-4372-bb2e-61436c1380bb)
现在这个yaml分析器的支持很不友好，注释也会识别有问题

**Comment by wilsonwu** [comment]
一般情况yaml字段名不建议用.隔开，比如：
```
abc:
  def.ghi: 123
```

```
abc:
  def:
    ghi: 123
```

有些lib会用.来解析级联字段，这样就没法区分这两种情况。

不过强制这样写也是可以正常解析，具体要看前端库的实现，可能不好修改。

**Comment by 985492783** [comment]
> 一般情况yaml字段名不建议用.隔开，比如：
> 
> ```
> abc:
>   def.ghi: 123
> ```
> 
> ```
> abc:
>   def:
>     ghi: 123
> ```
> 
> 有些lib会用.来解析级联字段，这样就没法区分这两种情况。
> 
> 不过强制这样写也是可以正常解析，具体要看前端库的实现，可能不好修改。

主要不是这个问题，正常写一个test: 123现在也会这样，不知道改了啥东西

**Comment by KomachiSion** [comment]
最近有人提交了一个对控制台yaml编辑器的改动，不清楚是否和那个改动有关。你有空可以研究下。

**Comment by 985492783** [comment]
@DarrenLuo 修改的时候有留意这个问题吗，应该是改了yaml的语法解析，但是没有修改解析返回值的后续操作吧

**Comment by DarrenLuo** [comment]
> @DarrenLuo 修改的时候有留意这个问题吗，应该是改了yaml的语法解析，但是没有修改解析返回值的后续操作吧

只是修改了对于 yaml 语法解析使用的库，对于 yaml 语法的判断更加标准，避免之前一些重复 key 等问题未进行提醒的情况，晚上可以看看对于这里提到的这种用例是否可以避免

**Comment by DarrenLuo** [comment]
不好意思，这里我发现问题了，换了校验库之后调错方法了，导致所有的yaml校验都失败了，马上修复
