### ISSUE TITLE
NACOS  2.1.2  web页面关闭登录功能无效。

### ISSUE THREAD

**Issue by ljh205sy** [alibaba/nacos#10701]
NACOS  2.1.2  web页面关闭登录功能无效。

按照官方修改方案，关闭登录功能无效，这个怎么处理 ？
![image](https://github.com/alibaba/nacos/assets/25653599/5cc635ec-69f9-4130-8668-65abfb1a04dc)

本地的配置截图如下：
![image](https://github.com/alibaba/nacos/assets/25653599/f2d5d78a-e9da-4205-8c25-cbefff79d536)

**Comment by 985492783** [comment]
If you want to use the full functionality, upgrade to v2.3.0, v2.1.2 just change backend can't ignore login page, but it still take effect.
In 2.1.2 you can go directly to the console url and skip the login page, or try any user and password.

**Comment by KomachiSion** [comment]
Please Upgrade to 2.2.2

**Comment by ljh205sy** [comment]
> Please Upgrade to 2.2.2
I was upgrade NACOS 2.2.3， but login nacos successed on chrome。
![image](https://github.com/alibaba/nacos/assets/25653599/624b5576-638d-4ea3-b072-560678ab6319)
![image](https://github.com/alibaba/nacos/assets/25653599/b7cdc3c7-fefe-420a-a38c-4f76880258ad)

**Comment by KomachiSion** [comment]
Move to https://github.com/alibaba/nacos/issues/10725
