### ISSUE TITLE
2.2.3 Error occurred when modifying the configuration file in Linux version: Field 'nid' does not have a default value;

### ISSUE THREAD

**Issue by xinlong68** [alibaba/nacos#10712]
2.2.3 Error occurred when modifying the configuration file in Linux version:
                                caused: PreparedStatementCallback; SQL [INSERT INTO his_config_info(id, data_id, group_id, tenant_id, app_name, content, md5, src_ip, src_user, gmt_modified, op_type, encrypted_data_key) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)]; Field 'nid' doesn't have a default value; nested exception is java.sql.SQLException: Field 'nid' doesn't have a default value;caused: Field 'nid' doesn't have a default value;

The Windows version does not.

![windows](https://github.com/alibaba/nacos/assets/120259702/a644190b-24fa-4424-a75f-29b0028b48d9)
![linux](https://github.com/alibaba/nacos/assets/120259702/68db9e04-ccbb-42a4-87f4-d8dba4e78fda)

It was found that the nid column in the Linux version did not autoincrement, does it need to be changed to an autoincrement column?

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/blob/eec0585d55c23ba5c046cd4c6dc1ec115f651ab8/distribution/conf/mysql-schema.sql#L139C53-L139C53

The official release contain auto_increment, your problem is not community problem but yours.
