### ISSUE TITLE
为什么不让用户只看到他有权限的命名空间而展示了所有的命名空间？

### ISSUE THREAD

**Issue by LesterDong** [alibaba/nacos#10713]
假设用户A只有命名空间spaceA的读写权，用户登录之后仍然能看到其他命名空间，但是点击之后提示“没有xxx命名空间的访问权限！”，不展示这些不相关的命名空间不是更好吗？

**Comment by KomachiSion** [comment]
因为鉴权是在获取数据之前，如果有list namespace的权限， 就会显示所有数据， 然后在操作对应命名空间的时候再校验对应权限。

如果你希望只显示有权限的数据， 可以创建自定义的鉴权插件， 并添加对应接口的切面或Filter过滤无权限数据。

**Comment by LesterDong** [comment]
好的 我试试 多谢~
