### ISSUE TITLE
v2.0.xnacos 起不来，报 no data set,参考网上改超时参数，没用。。。。。

### ISSUE THREAD

**Issue by mourenz** [alibaba/nacos#10719]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Daydreamer-ia** [comment]
please provide more detail about error msg
