### ISSUE TITLE
How to do HTTP health check use register instance port

### ISSUE THREAD

**Issue by Joey777210** [alibaba/nacos#10722]
**Is your feature request related to a problem? Please describe.**
When I use nacos for service discovery, I might want to config health check by HTTP. 
Can I use the port that register by client? And How? 
If can not be done, may be we can support this feature? 

**Describe the solution you'd like**
A way to health check by client registered port.

<img width="1103" alt="截屏2023-07-03 19 10 27" src="https://github.com/alibaba/nacos/assets/53630996/8ccd4f60-62e3-4d0d-bd3f-02a14417e84a">

**Comment by Daydreamer-ia** [comment]
这种检查是服务端主动下探的，适用于永久服务；对于临时服务并不适用，临时实例是要求 `sdk` 主动上报的。也就是说，你这里没得选，除非切换为永久服务

**Comment by Joey777210** [comment]
@Daydreamer-ia 永久节点中似乎也没找到可以将Instance上报的port作为探活端口的配置方法

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/a62a1de6-c53d-4f7c-9a28-476ead889561)

使用ip端口进行检查设置为true，就会用注册的ip端口来进行检查。

**Comment by Joey777210** [comment]
文案感觉有点迷惑，我晚些提交pr修改下？

**Comment by KomachiSion** [comment]
老得文案如此，应该是考虑到意思和对齐平衡，再多加一些字，比如`实例的`，可能会过长。

**Comment by KomachiSion** [comment]
可以的

**Comment by KomachiSion** [comment]
Any PR for this issue？ @Joey777210  If #10799 has fix this PR, please close it.
