### ISSUE TITLE
tomcat版本低了有漏洞，该怎么替换？

### ISSUE THREAD

**Issue by planefeiji** [alibaba/nacos#10726]
发现2.2.3目前的tomcat版本低了，能怎么升级tomcat版本？

**Comment by wilsonwu** [comment]
可以考虑从镜像中解决。

**Comment by planefeiji** [comment]
没有容器化

**Comment by KomachiSion** [comment]
2.2.3应该依赖的是比较新的spring boot了， tomcat应该是spring boot web引入的， 看下spring boot是否有新版本升级了tomcat，可以在2.3版本中升级上去。

如果来不及的话可以自行修改版本并编译部署。

**Comment by ZhangShenao** [comment]
是不是可以把 spring-boot-starter-web 中的 tomcat-embed exclude 掉，然后引入高版本的？

**Comment by KomachiSion** [comment]
> 是不是可以把 spring-boot-starter-web 中的 tomcat-embed exclude 掉，然后引入高版本的？

自己这么做可以，不保证兼容性。
