### ISSUE TITLE
nacos server频繁上下线正常服务

### ISSUE THREAD

**Issue by LeePui** [alibaba/nacos#10733]
nacos server : 版本2.0.4，三节点组成集群，对外提供一个VIP，VIP负载均衡采用轮训方式
nacos client version: 1.4.0。
目前发现的情况是：nacos server中的naming-server.log中时刻在打印以下类型的日志：

> 2023-07-05 10:42:08,915 INFO Client connection 10.1.124.94:59525#true connect
2023-07-05 10:44:18,277 INFO Client connection 10.1.124.94:59525#true disconnect, remove instances and subscribers
2023-07-05 10:45:28,953 INFO Client connection 10.1.124.94:59525#true connect
2023-07-05 10:49:18,300 INFO Client connection 10.1.124.94:59525#true disconnect, remove instances and subscribers
2023-07-05 10:50:29,605 INFO Client connection 10.1.124.94:59525#true connect

上面日志中的客户端ip不是固定的，是每个客户端ip都会出现。
使用arthsa在10.1.124.94这客户端持续观察心跳请求和响应，`watch  com.alibaba.nacos.client.naming.net.NamingProxy sendBeat "{params, returnObj}" -x 3`，客户端每隔五秒发送一次心跳，且每回都能收到响应，持续观察期间，server日志中有出现该服务disconnect, remove instances and subscribers，一分钟又connect的日志。客户端的cpu, gc, 网络均为正常。
![image](https://github.com/alibaba/nacos/assets/14257862/8af75521-4fc0-4be9-9c01-1140608f599a)

问题：在客户端心跳正常的情况下，为何nacos-server日志中持续打印客户端下线又上线的日志？目前发现每天能打印1G多的该日志，几乎每个客户端的ip都会出现在该上下线的日志中，但实际上客户端是在正常工作和发送心跳的。

求助在客户端表现均正常的情况下，为何server端还会频繁持续的上下线该服务呢？这是否会给服务发现带来影响？

**Comment by KomachiSion** [comment]
看端口应该是udp的监听端口，udp的监听续约是没10s一次，如果节点多且server端前置有负载均衡时可能会超过client移除时间，导致client被过期移除。

一般情况下忽略即可，推荐是升级到2.0以上的客户端。

**Comment by LeePui** [comment]
> 看端口应该是udp的监听端口，udp的监听续约是没10s一次，如果节点多且server端前置有负载均衡时可能会超过client移除时间，导致client被过期移除。
> 
> 一般情况下忽略即可，推荐是升级到2.0以上的客户端。

谢谢，我验证了下，确实是udp端口来的。
还有个疑问，udp协议在nacos server中是用来推送订阅的服务变更给客户端的，这里为何udp续约不通过就要将客户端移除呢？不是按照心跳的时间嘛？不知道理解的是否有误

**Comment by KomachiSion** [comment]
如果不续约不移除，那么如果使用方使用不正确（不进行取消订阅，直接停止订阅者进程）， 订阅者会不被移除，一只占用内存，直至OOM。

**Comment by KomachiSion** [comment]
2.x客户端没有这个问题。

**Comment by huangyudili** [comment]
杨老师方便说下udp续约不通过的设计吗，我们这边系统生产也碰上了这个问题，架构同这位老师一样，区别是我们这边会出下不定期的服务掉线，看了您的解释感觉可能和您说的udp续约有关

**Comment by LeePui** [comment]
> 杨老师方便说下udp续约不通过的设计吗，我们这边系统生产也碰上了这个问题，架构同这位老师一样，区别是我们这边会出下不定期的服务掉线，看了您的解释感觉可能和您说的udp续约有关

可以先看一下server中的naming-server.log是否会移除服务的日志。
