### ISSUE TITLE
Request for batch configuration comparison

### ISSUE THREAD

**Issue by Anton6661** [alibaba/nacos#10736]
Hi, we use different Nacos for test, pressure test, development environment, and use nacos namespace to distinguish different microservices, we also have configuration for canary environment by creating different Group

So then, it's a huge amount of work to compare these configuration, I was wondering if there's any way to do a comparison for below request

1. Comparing in different Nacos environment and get an output
2. Comparing in a same Nacos environment for different Group and get an output

**Comment by KomachiSion** [comment]
There is not nacos api can do this.

You can comparing your configuration with api like console and add this batch comparison feature by yourself.
