### ISSUE TITLE
nacos-cluster-grpc-executor 线程数量很多

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#10738]
最近在调研 nacos server 在 rpc 长连接下的性能，由于担心 rpc 线程池数量不够（类似担心 tomcat 最大线程数不够一样），设置了 jvm 参数：-Dremote.executor.times.of.processors=256，然后发现，nacos-cluster-grpc-executor 以及 nacos-grpc-executor 的线程数量均为 1024 个，查看源码发现相关代码如下：

```java
public static final ThreadPoolExecutor sdkRpcExecutor = new ThreadPoolExecutor(
        EnvUtil.getAvailableProcessors(RemoteUtils.getRemoteExecutorTimesOfProcessors()),
        EnvUtil.getAvailableProcessors(RemoteUtils.getRemoteExecutorTimesOfProcessors()), 60L, TimeUnit.SECONDS,
        new LinkedBlockingQueue<>(RemoteUtils.getRemoteExecutorQueueSize()),
        new ThreadFactoryBuilder().daemon(true).nameFormat("nacos-grpc-executor-%d").build());

public static final ThreadPoolExecutor clusterRpcExecutor = new ThreadPoolExecutor(
        EnvUtil.getAvailableProcessors(RemoteUtils.getRemoteExecutorTimesOfProcessors()),
        EnvUtil.getAvailableProcessors(RemoteUtils.getRemoteExecutorTimesOfProcessors()), 60L, TimeUnit.SECONDS,
        new LinkedBlockingQueue<>(RemoteUtils.getRemoteExecutorQueueSize()),
        new ThreadFactoryBuilder().daemon(true).nameFormat("nacos-cluster-grpc-executor-%d").build());
```
这里 sdkRpcExecutor 是 nacos server 处理 nacos client 请求的线程池， clusterRpcExecutor 是处理 nacos server 间请求的线程池，另外，在 GrpcClusterServer.java 中发现如下代码：
```java
public ThreadPoolExecutor getRpcExecutor() {
    if (!GlobalExecutor.clusterRpcExecutor.allowsCoreThreadTimeOut()) {
        GlobalExecutor.clusterRpcExecutor.allowCoreThreadTimeOut(true);
    }
    return GlobalExecutor.clusterRpcExecutor;
}
```
即，clusterRpcExecutor 如果不允许核心线程被回收，则设置为允许，这能避免 nacos-cluster-grpc-executor 线程池不会一直保持在 1024

这里，我有一个疑问，clusterRpcExecutor 的配置需要和 sdkRpcExecutor 一样吗？nacos server 2.x 间的 rpc 请求也很多？另外，如果是 nacos server 维护，我们停止一个节点，该节点的连接被快速转移到其余节点，这种情况下，clusterRpcExecutor 和 sdkRpcExecutor 均会快速长高，比如，我这里，两者均会快速涨到 1024，之后 clusterRpcExecutor 再降低，这不利于资源的充分利用呀，我的意思是，受内存限制，假设 线程数量 设置到 2048 是理想值，由于同时存在  clusterRpcExecutor 和 sdkRpcExecutor，那么 sdkRpcExecutor 只能设置到 1024，因为对应的 clusterRpcExecutor 也为 1024，之后虽然 clusterRpcExecutor 会因为超时释放线程，但释放了也没法让 sdkRpcExecutor 使用。是否应该让 clusterRpcExecutor 的配置不要和 sdkRpcExecutor 一模一样呢？

**Comment by KomachiSion** [comment]
其实cluster的可以减少一点，但是不应该减少太多。

主要是很多客户端操作会触发集群之间的同步和请求，所以太低的话， 可能导致集群之间的同步出现问题。

**Comment by ijustyce** [comment]
> 其实cluster的可以减少一点，但是不应该减少太多。
> 
> 主要是很多客户端操作会触发集群之间的同步和请求，所以太低的话， 可能导致集群之间的同步出现问题。

理解，这里，是否有一个推荐的比例，比如 cluster 1 个 线程，sdk 2 个 线程。

另外，默认的 16倍 是否恰当？在 4 核 16 g 内存下，cluster 和 sdk 将均默认为 64 个线程，这比起 tomcat 默认的 200 个线程要少了很多的，而 tomcat 默认的 200个，网上太多的观点都以为不够用，一般是建议设置到 1000 左右。

我想了解下，设置为 cpu 的 16 倍，这里选择 16 而不是别的值，是压测得出的结论还是凭感觉给出的一个值呢？

**Comment by KomachiSion** [comment]
压测出来的， 16倍的情况下，能在持久的峰值QPS/TPS请求下，把CPU资源使用干净的同时保证程序稳定。

继续扩大倍数会导致CPU频繁切换，性能下降， 倍数降低，CPU资源使用不满。

当然这个倍数和环境实际使用的CPU类型，框架，jdk版本可能都有关系。因此是可配置的。

**Comment by KomachiSion** [comment]
至于cluster和sdk的比例， 需要根据场景来调配：

比如查询请求多，写请求少， 可以1:4甚至更高

如果反过来就还是推荐保持1:1
