### ISSUE TITLE
docker nacos 2.0.3版本不能匹配mysql8.0.27，启动报错No DataSource set  我已经配置了driver但是不能正常启动

### ISSUE THREAD

**Issue by AcuteSZW** [alibaba/nacos#10747]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Please provider more information and check fully in log to see why datasource can't build.
