### ISSUE TITLE
官网2.0代码与最新包不符

### ISSUE THREAD

**Issue by baozi-2019** [alibaba/nacos#10740]
``https://nacos.io/``中服务注册样例代码与2.2.4版nacos-client api完全不符。现在在哪里能看到最新client的用法

**Comment by wilsonwu** [comment]
需要有参与者贡献一下更新官网内容。

**Comment by baozi-2019** [comment]
所以现在想用client只能自己读代码？

**Comment by wilsonwu** [comment]
> 所以现在想用client只能自己读代码？

我觉得是的，Nacos使用的人不少，但是社区参与者确实比较零散，大家一起努力吧。
