### ISSUE TITLE
NamingEvent add getGroupName and getClusters method

### ISSUE THREAD

**Issue by dongfangshangren** [alibaba/nacos#1075]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

when subscire different serviceName or cluster or group, we can use same EventListener

### Describe what you expected to happen

```java
EventListener listener = new EventListener(){
   public void onEvent(Event event){
        NamingEvent namingEvent = (NamingEvent)event;
        //namingEvent.getClusters();
        // namingEvent.getGroupName();
        List<Instance> instances = namingEvent.getInstances();
        //do some work
   }
}

namingService.subscribe("service1",Arrays.asList("cluster1"),  listener);
namingService.subscribe("service1", Arrays.asList("cluster2"),  listener);

namingService.subscribe("service2", "group1",  listener);
namingService.subscribe("service2", "group2",  listener);
```

### How to reproduce it (as minimally and precisely as possible)

As describe above

### Tell us your environment

nacos 1.0.0

**Comment by nkorange** [comment]
@dongfangshangren Is this a bug report or a feature request? Nacos supports one listener for multiple services now.

**Comment by dongfangshangren** [comment]
@nkorange Indeed, Nacos support one  listener for multiple services,  but NamingEvent don't provide method to obtain clusterName and groupName

Issue updated, this is feature request

**Comment by nkorange** [comment]
@dongfangshangren OK, it will be fixed.

**Comment by Albert-Hugo** [comment]
@nkorange I would like to fix this.

**Comment by nkorange** [comment]
@Albert-Hugo Great!
