### ISSUE TITLE
Prometheus sd api security is not compatiable with nacos original security configs

### ISSUE THREAD

**Issue by Joey777210** [alibaba/nacos#10752]
**Describe the bug**
I'm a bit confused of how to use the prometheus auth. Has anyone tested the code in `PrometheusAuthFilter` and `PrometheusSecurityConfiguration` ? 
`nacos.core.auth.enabled=false` is not working for `PrometheusAuthFilter`. 
And it seems not compatible with the original security configs either.

**Comment by Joey777210** [comment]
I think we have to re-design auth module for prometheus sd.
Use nacos's org Annotation `@Secured` seems to be the easy way.

**Comment by KomachiSion** [comment]
prometheus support OAuth and Basic Auth, But nacos' auth is self system, not OAuth and Basic Auth implementation.

So prometheus module should not use nacos' auth

**Comment by Joey777210** [comment]
ok，but how current security codes in prometheus modul support works？

**Comment by KomachiSion** [comment]
Added from https://github.com/alibaba/nacos/pull/9912 .

It seems use spring security directly to support standard Basic Auth. 

The original PR author has AFK and no submit usage document.

I think you can help community to enhance the auth usage if it can't work like other issue and add more document about this feature.

**Comment by KomachiSion** [comment]
@Joey777210 any process？

**Comment by KomachiSion** [comment]
If no process for this issue, I suggest add current usage document first and close #10662 . Keep this issue todo in next version.

**Comment by karsonto** [comment]
@i will solve it@
