### ISSUE TITLE
[Question] RuntimeConnectionEjector doesn't use the loadClient and redirectAddress

### ISSUE THREAD

**Issue by Daydreamer-ia** [alibaba/nacos#10761]
**Describe the bug**
`ServerLoadController` 内有几个关于 `Rebalance` 服务端负载的 `api` ，但是对于接口接收到的参数 `loadClient` 和 `redirectAddress` 并没有做任何处理，只是将其设置进 `RuntimeConnectionEjector` 属性，默认的 `RuntimeConnectionEjector` 实现并没有使用到像 `ServerLoadController` 控制器注释说明的那样将连接重定向到指定的 `redirectAddress` 上，只是做了连接的健康检查，而不是像 `/reloadClient` 那样将连接重定向到`redirectAddress` 。

相关的api：
- "/reloadCurrent"
- "/smartReloadCluster"

这两个接口并不会发挥任何作用，这个插件是需要用自定义的吗？

There are several `APIs` in the `ServerLoadController` that address the workload of the `Rebalance` server, but the parameters `loadClient` and `redirectAddress` received by the interface are not processed. They are only set to the `RuntimeConnectionEjector` property, and the default `RuntimeConnectionEjector` implementation does not redirect the connection to the specified redirectAddress as stated in the comments on the `ServerLoadController` controller, just did a health check on the connection, instead of redirecting the connection to redirectAddress like `/reloadClient`.

related api：
- "/reloadCurrent"
- "/smartReloadCluster"

These two interfaces will not have any effect. Does this plugin require customization?

**Comment by KomachiSion** [comment]
感觉是bug，我使用的时候也遇到了， 限流插件重构之前是生效的 @shiyiyue1102 看下，或者指导 @Daydreamer-ia 修复下。

**Comment by KomachiSion** [comment]
感觉是bug，我使用的时候也遇到了， 限流插件重构之前是生效的 @shiyiyue1102 看下，或者指导 @Daydreamer-ia 修复下。
