### ISSUE TITLE
nacos-client2.2.4版本中的guava30.1-jre版本漏洞问题

### ISSUE THREAD

**Issue by LeeQiYu888** [alibaba/nacos#10768]
我在项目中的nacos-client升级到2.2.4版本后，扫描漏洞时扫描到nacos-client里面有guava30.1-jre版本，该版本存在高危漏洞，但是nacos-client2.2.4已经是最新版本，而且其他最近的几个版本里面guava都是30.1-jre版本，请问这个问题怎么解决，guava存在位置如图所示：
![image](https://github.com/alibaba/nacos/assets/83531876/c0804c56-2b91-4644-b631-104792650444)
或者说这个guava组件可以排除掉，或者跟换版本吗？

After the nacos-client in my project was upgraded to version 2.2.4, when scanning for vulnerabilities, I found that there was guava30.1-jre version in nacos-client, which had high-risk vulnerabilities, but nacos-client2.2.4 was already the latest version. And in the other recent versions, guava is all 30.1-jre version. How to solve this problem? The location of guava is shown in the figure:
![image](https://github.com/alibaba/nacos/assets/83531876/c0804c56-2b91-4644-b631-104792650444)
Or can this guava component be excluded, or can the version be changed?

**Comment by Bo-Qiu** [comment]
可在POM文件中将sdk自带的guava包排除掉，再主动引入一个你需要的版本的guava依赖。
替换后建议对核心功能进行验证，避免由于兼容问题导致功能异常。
![image](https://github.com/alibaba/nacos/assets/46370663/e10364f6-0a91-4326-9738-cfa6d1ecec3b)

**Comment by LeeQiYu888** [comment]
非常感谢你的回答，这种方法我试过了，不太行，不好意思，我觉得我之前没有表达清楚。是这样的，我项目中引入了nacos-client这个依赖，测试那边扫描出来有一个漏洞，路径是“nacos-client-2.2.4.jar/META-INF/maven/com.google.guava/guava/pom.xml”，而我们在项目中搜索guava，是不存在的，如下图所示：
![image](https://github.com/alibaba/nacos/assets/83531876/9e517c79-4ce0-4f13-ad93-d0ff52c618ce)
因为在项目中根本不存在，所以在pom文件中无法排除，但是他确实存在于nacos-client这个包里
![image](https://github.com/alibaba/nacos/assets/83531876/c11f264b-e4a3-43b0-b582-0a5c7d60a48d)
这种情况怎么解决呢？

**Comment by Bo-Qiu** [comment]
由于Nacos Java SDK在2.0版本后引入了gRPC，为了避免用户业务引入的gRPC版本不同导致冲突，使用了shaded技术将部分依赖直接封装进nacos-client中，导致nacos-client较大。 如果用户未自行引入gRPC或确认版本无冲突，希望使用纯净版的nacos-client以减小依赖，可以使用classifier来指定使用纯净版。
这样貌似是可行的，可以详细了解下 试试看
![image](https://github.com/alibaba/nacos/assets/46370663/52443623-a002-4404-8a8d-3c7e3691cf87)
![image](https://github.com/alibaba/nacos/assets/46370663/6f60df1d-32b3-4c57-93f4-4ad4dce3610f)

**Comment by LeeQiYu888** [comment]
好的好的，解决了，非常感谢

**Comment by herozeng** [comment]
2.0.4 也有这个问题，没有纯净版吗
