### ISSUE TITLE
能否支持静态变量的注入？

### ISSUE THREAD

**Issue by slatonwu** [alibaba/nacos#10763]
能否支持static 的 变量的注入？

**Comment by 985492783** [comment]
创建config监听器，回调修改static变量

**Comment by slatonwu** [comment]
最好是也可以通过@NacosValue("${}")注入

**Comment by 985492783** [comment]
springcloud可以用value注解，直接支持set方法，springboot你可以自己试试

**Comment by KomachiSion** [comment]
可以把需求提交到nacos-spring-boot-starter，然后关联过来。
