### ISSUE TITLE
Nacos2.0.3 data source does not support pgsql

### ISSUE THREAD

**Issue by zhangdejin-tom** [alibaba/nacos#10762]
使用Nacos2.0.3 无法使用pgsql作为数据源，报错信息如下：
![image](https://github.com/alibaba/nacos/assets/67250298/d1371336-b874-4083-a2f8-f41e092db7d9)

**Comment by wuchubuzai2018** [comment]
对的，nacos2.2开始才支持Postgresql数据源插件

**Comment by KomachiSion** [comment]
2.2之后的版本有数据源插件， 之前的版本仅支持mysql协议和derby数据库
