### ISSUE TITLE
适配国产数据库，达到信创要求

### ISSUE THREAD

**Issue by EightMonth** [alibaba/nacos#10772]
是否可以支持一款国产数据库，达到信创要求。现在nacos已无法在全信创环境中使用，希望可以支持。

**Comment by 985492783** [comment]
https://github.com/nacos-group/nacos-plugin/tree/develop/nacos-datasource-plugin-ext/nacos-dm-datasource-plugin-ext

**Comment by EightMonth** [comment]
请问有指南么，是需要修改哪部分代码

**Comment by 985492783** [comment]
可以看下文档是否满足需求，nacos现在是插件化，实现应该有很多，https://github.com/nacos-group/nacos-plugin/tree/develop/nacos-datasource-plugin-ext

**Comment by onewe** [comment]
如果用 oceanbase 应该能完美兼容
