### ISSUE TITLE
Support toml format 

### ISSUE THREAD

**Issue by kpvt001** [alibaba/nacos#10774]
**Describe the solution you'd like**
Support toml format 

**Describe alternatives you've considered**

**Additional context**

**Comment by DarrenLuo** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
What's means toml format?  config module? config module is not relative config type, all type will save as text.

The type only used in console to improve usage.

**Comment by onewe** [comment]
I guess that just add new format on the console-ui 🤔

**Comment by KomachiSion** [comment]
> I guess that just add new format on the console-ui 🤔

If so, welcome community go ahead.  Add console-ui with `toml` in type selector and upgrade an editor which support `toml`
