### ISSUE TITLE
nacos2.1.2单机启动，默认配置，只改了mysql连接。一段时间后内存溢出，cpu飙高

### ISSUE THREAD

**Issue by dubujianghu** [alibaba/nacos#10779]
nacos2.1.2版本，单机启动后，一切正常可以正常注册服务。但是一段是时间后nacos服务假死，top命令可以看到cpu飙高，垃圾回收fullgc占用大量并发线程。日志文件报内存溢出。无法注册服务。详情见线程堆栈
[nacos2.1.2线程堆栈.txt](https://github.com/alibaba/nacos/files/12034913/nacos2.1.2.txt)

**Comment by wilsonwu** [comment]
请问分配的cpu和内存是多少？

**Comment by dubujianghu** [comment]
您好，nacos使用的是默认的shartup.sh脚本启动的：sh startup.sh -m standalone，看了下脚本里面应该是分配了1g的内存。本身服务器的资源很丰富，256G内存，没错，我说的是内存。56核cpu。但是nacos运行一段时间就会报上诉堆栈错误。重启后又正常。不知道啥原因。

**Comment by dubujianghu** [comment]
> 请问分配的cpu和内存是多少？
您好，nacos使用的是默认的shartup.sh脚本启动的：sh startup.sh -m standalone，看了下脚本里面应该是分配了1g的内存。本身服务器的资源很丰富，256G内存，没错，我说的是内存。56核cpu。但是nacos运行一段时间就会报上诉堆栈错误。重启后又正常。不知道啥原因。

**Comment by wilsonwu** [comment]
哈哈，jvm的内存调到2g试试，根据我的经验1g运行nacos非常勉强。

**Comment by KomachiSion** [comment]
需要查看用量， console.demo.io 设置的是512M内存， 运行起来没有任何问题

如果大量使用的情况下， 肯定是要加大内存的。

**Comment by dubujianghu** [comment]
感谢大佬们，默认standalone.sh 单机模式启动，配置是512m，我改成了4G目前运行没啥问题了。
