### ISSUE TITLE
服务启动正常可以拿到nacos的配置文件,但是无法注册到nacos上.

### ISSUE THREAD

**Issue by shawnhuang94** [alibaba/nacos#10781]
启动debug,也没有进入到NacosServiceRegistry类下的register方法中.

整体环境
jdk 11
mysql 5.7.42
springboot 2.7.11
springcloud alibaba 2021.0.5.0
springcloud 2021.0.5
nacos 2.2.0

demo地址:
https://github.com/shawnhuang94/springcloud-nacos 的work-flow-service服务

[Uploading 启动日志.log…]()

**Comment by KomachiSion** [comment]
那是应用的问题，请自行排查或者提交至SCA社区。
