### ISSUE TITLE
nacos 源码启动报错（执行 com.alibaba.nacos.Nacos#main 方法）

### ISSUE THREAD

**Issue by longyunqi** [alibaba/nacos#10780]
代码：基于7.12 的develop 拉取的代码
分析原因：
**1.** 项目启动时spring 加载 com.alibaba.nacos.naming.web.NamingConfig#distroFilter 
![Image_20230713112007](https://github.com/alibaba/nacos/assets/49145582/c88205bc-e4b4-414d-ba2a-f838257d4c69)

**2**.com.alibaba.nacos.naming.web.DistroFilter 依赖  DistroMapper 实例

![Image_20230713112025](https://github.com/alibaba/nacos/assets/49145582/542a3ecd-fe1f-436f-ac47-15bf066fc27f)
**3.** com.alibaba.nacos.naming.core.DistroMapper 只有有参构造，从而导致初始化报错
![Image_20230713112025](https://github.com/alibaba/nacos/assets/49145582/49f47554-5340-4d43-aa89-faa1f384ac4b)

报错内容： ERROR Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'distroFilterRegistration' defined in class path resource [com/alibaba/nacos/naming/web/NamingConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.FilterRegistrationBean]: Factory method 'distroFilterRegistration' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'distroFilter': Unsatisfied dependency expressed through field 'distroMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'distroMapper' defined in file [D:\projectplace\Nacos\naming\target\classes\com\alibaba\nacos\naming\core\DistroMapper.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverMemberManager' defined in file [D:\projectplace\Nacos\core\target\classes\com\alibaba\nacos\core\cluster\ServerMemberManager.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.core.cluster.ServerMemberManager]: Constructor threw exception; nested exception is ErrCode:500, ErrMsg:jmenv.tbsite.net

### 报错文件：
[nacos.log](https://github.com/alibaba/nacos/files/12035075/nacos.log)

**Comment by KomachiSion** [comment]
看报错你使用了地址服务器，但是没有设置地址服务器地址， 使用了默认的jmenv.tbsite.net， 然后没有这个域名。

请再看下文档，启动的时候需要设置cluster.conf， 如果想单例模式启动，请添加-Dnacos.standalone=true

**Comment by longyunqi** [comment]
@KomachiSion  是参考这个文档：https://nacos.io/zh-cn/docs/v2/quickstart/quick-start.html ？ 我看文档里面没有说需要进行额外特殊配置呢？

**Comment by longyunqi** [comment]
@KomachiSion 
   感谢回复！ 
  请问一下cluster.conf 配置和单例模式启动 的相关文档路径是什么呢？我在官网的这个路径没有看到相关文档：https://nacos.io/zh-cn/docs/v2/quickstart/quick-start.html

**Comment by marchocode** [comment]
Try this way.

```bash
bin\startup -m standalone
```

**Comment by KomachiSion** [comment]
> @KomachiSion 感谢回复！ 请问一下cluster.conf 配置和单例模式启动 的相关文档路径是什么呢？我在官网的这个路径没有看到相关文档：https://nacos.io/zh-cn/docs/v2/quickstart/quick-start.html

快速开始使用的是编译好的运行包启动单例模式启动，不涉及源码启动， 需要源码启动请根据快速开始的启动脚本，研究启动参数和启动类。 然后自行选择需要的启动参数并设置好启动类运行。
