### ISSUE TITLE
nacos 适配达梦数据库出现com.sun.proxy.$Proxy124 cannot be cast to com.alibaba.nacos.plugin.datasource.mapper.Mapper

### ISSUE THREAD

**Issue by HuangRenhui** [alibaba/nacos#10782]
![lQLPJxSnpm4t4ZrNAsnNBK-w-dzc-UCkEaoEpN3BSkDiAA_1199_713](https://github.com/alibaba/nacos/assets/25076816/cc3392a9-78ca-4eac-9917-019a1baee15b)
在com.alibaba.nacos.plugin.datasource.MapperManager#findMapper 114行代码中
return (R) MapperProxy.createSingleProxy(mapper);
出现com.sun.proxy.$Proxy124 cannot be cast to com.alibaba.nacos.plugin.datasource.mapper.Mapper

**Comment by DarrenLuo** [comment]
@i will solve it@

**Comment by HuangRenhui** [comment]
had solve

**Comment by rongxingsun** [comment]
@DarrenLuo 请问你是怎么处理的，我用2.3.0版本也出现类似的问题
class jdk.proxy2.$Proxy112 cannot be cast to class com.alibaba.nacos.plugin.datasource.proxy.MapperProxy

**Comment by HuangRenhui** [comment]
> @DarrenLuo 请问你是怎么处理的，我用2.3.0版本也出现类似的问题 class jdk.proxy2.$Proxy112 cannot be cast to class com.alibaba.nacos.plugin.datasource.proxy.MapperProxy

you can look here: https://blog.csdn.net/time_poster/article/details/131846280
