### ISSUE TITLE
nacos2.2.3启动报错

### ISSUE THREAD

**Issue by liuxuejava** [alibaba/nacos#10788]
When I started Nacos, an error was reported:
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

**Desktop (please complete the following information):**
 - OS: [e.g. windows10]
 - Version [e.g. nacos-server 2.2.3, nacos-client 2.0.4]
 - Module [e.g. naming/discovery]
 - SDK [e.g. spring-cloud-alibaba-nacos]

**Additional context**
![image](https://github.com/alibaba/nacos/assets/19323303/5db040ea-efd6-4afd-8eee-e31cf2f3cd8d)

**Comment by KomachiSion** [comment]
It seems your jdk has problem in your env. Can you change an new env or change the jdk version to retry?

**Comment by liuxuejava** [comment]
> It seems your jdk has problem in your env. Can you change an new env or change the jdk version to retry?

I reinstalled the environment, uninstalled nacos, and reinstalled it. The first time it started successfully, but running it again later still reported an error

**Comment by KomachiSion** [comment]
The first time can started mean code has no problem, and start again failed means the env has some problem after first start.

Such as some resource conflict or other env problem.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by ganfuer** [comment]
解压nacos后。首先要配置startup  中是单机 还是 集群。来回切换启动方式会出现上述问题。
