### ISSUE TITLE
1.4.0版本更新配置报错：没有可用的bean

### ISSUE THREAD

**Issue by beareverse** [alibaba/nacos#10790]
具体报错如下，各位给看看这是为啥呢：
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'threeItemsController': Unsatisfied dependency expressed through field 'validateThreeItemsHandler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'validateThreeItemsHandler': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type '*.RpcVariableService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@javax.annotation.Resource(shareable=true, lookup=, name=, description=, authenticationType=CONTAINER, type=class java.lang.Object, mappedName=)}
[ERROR] 2023-07-14 16:04:48.177 [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.100.184_8848-9a1e5a89-b6ac-4adf-bb3b-f5b4afd28262] o.s.b.diagnostics.LoggingFailureAnalysisReporter - [TID:N/A] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field validateThreeItemsHandler in ThreeItemsController required a bean of type '*.RpcVariableService' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type '*.RpcVariableService' in your configuration.

**补充：在validateThreeItemsHandler中注入了Environment对象**

**Comment by KomachiSion** [comment]
Not nacos' problem, the bean is app's bean, not nacos.
