### ISSUE TITLE
[Bug Report] Methods `selectInstances` and `selectOneHealthyInstance` of `NacosNamingService` never trigger `subscribe` action

### ISSUE THREAD

**Issue by YunWZ** [alibaba/nacos#10800]
**Describe the bug**
Methods `selectInstances` and `selectOneHealthyInstance` of `NacosNamingService` never trigger `subscribe` action.

Event if parameter `subscribe` is `true`.

**Expected behavior**
Both methods should get newlest serviceinfo from nacos server.

**Actually behavior**
Always get outdated serviceinfo from local.

**How to Reproduce**
1. start an application and register to nacos server, called `provider`.
2. start other application(called `consumer`) and subscribe `provider` from nacos server.
3. stop `consumer` and `provider`.
4. now, restart `provider` app, bug chang ip or port of this app;
5. restart `consumer` app, and then get `provider` serviceinfo from nacos-server by `NacosNamingService.selectInstances(subscribe=true)` or `NacosNamingService.selectOneHealthyInstance(subscribe=true).

**Comment by Bo-Qiu** [comment]
Thanks for your report, this is in line with issue #10585, I've created a PR to solve it.
