### ISSUE TITLE
某一台应用读取nacos配置丢失

### ISSUE THREAD

**Issue by DarkNightMN** [alibaba/nacos#10806]
环境：nacos服务端2.1.0  
           nacos客户端1.2.0 
           java应用：springboot 2.3.4.RELEASE
java配置项：
 @Slf4j
@Data
@Configuration
@NacosConfigurationProperties(prefix = "account.disable", dataId = NacosConst.DATA_ID_WEB, type = ConfigType.PROPERTIES, groupId = NacosConst.DEFAULT_GROUP, autoRefreshed = true)
public class AccountDisableMonitorConfig {
    private Map<Long, AccountDisableMonitor> monitor;

    @Data
    public static class AccountDisableMonitor {
        private Long secondsAgo;
        private Long leastCount;
        private BigDecimal warningRate;
        private List<Long> tagIdList;
    }
}

nacos配置项：
account.disable.monitor.4.tagIdList=57
account.disable.monitor.4.secondsAgo=60
account.disable.monitor.4.leastCount=5
account.disable.monitor.4.warningRate=50

问题：变更nacos配置并且发布之后，5台应用server中，有一台server未获取到某一行配置项（如tagIdList为null），其他几台server都能获取到，需要重新发布一次才行。（偶发，几个月就可能出现一次，导致线上空指针）

自查：nacos的logs/config-trace.log 并未发现异常，当时都是pull|ok

**Comment by 985492783** [comment]
集群模式？如果是的话客户端1.x版本很容易出现这种情况，最好升级到2.x，应该就不会了

**Comment by DarkNightMN** [comment]
> 集群模式？如果是的话客户端1.x版本很容易出现这种情况，最好升级到2.x，应该就不会了

nacos服务端2.x是单点部署的，java服务端应用（使用了nacos-client 1.x）是集群的。是指这种情况吗？那我尝试升级下版本，感谢。

**Comment by KomachiSion** [comment]
pull ok就表示服务端推送是正常的， 客户端收到配置之后，交由框架进行处理并应用到对应属性配置中。

所以这里可能是应用框架出的问题，而不是nacos配置丢失。

你可以从nacos-client的日志和本地快照中确认是否收到了最新配置。如果日志和快照中的配置文件是最新的，但是出现了配置丢失的情况，那肯定是应用自身或者应用框架的问题导致的。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
