### ISSUE TITLE
Nacos对永久实例探活的任务转移问题

### ISSUE THREAD

**Issue by DSSLP** [alibaba/nacos#10808]
1、目前看到nacos对永久实例探活时，是每个服务端节点探活自己负责的永久实例，判断当前服务节点是否为该永久实例的探活责任节点的逻辑如下：
![image](https://github.com/alibaba/nacos/assets/57716709/3af4d0a0-f749-4f3c-afdc-d9b49ae0f684)

2、而当某个服务节点B挂了时，按道理它所负责探活的实例应该转移到其它服务节点上。转移逻辑如下：
（1）服务节点间两两之间会互相探活
（2）当服务节点A探活服务节点B多次失败后，节点A将节点B的状态置为down，并发出MembersChangeEvent
（3）从而上述1中的healthyList会把B节点删除，即长度变为size-1，从而达到探活实例任务重分配的效果
![image](https://github.com/alibaba/nacos/assets/57716709/2819b941-da57-4d4e-89af-34c366460ca2)

3、如果1/2逻辑我理解的没问题的话，那这里会存在一个问题：2（2）中只是A单方面把B置为down，并没有通知其它节点，或者说不是所有节点一起做出的down决定，那么会导致节点A的确是重分配了探活实例任务，但其它节点可能探活的B是正常的，因此探活实例的任务分配还是按照B未失活的情况下进行分配。此时会导致以下三个问题：
（1）A节点重分配了，原A节点的任务没有被其他节点执行
（2）B节点down了，但它的任务也并未被其它节点执行
（3）可能有多个节点同时探活同一个永久实例，由于A节点的分配策略和其它节点不同，导致同一个任务被两个节点执行

想问下关于探活永久实例任务转移这块逻辑是否是存在问题呢？还是我理解有误，望指出，谢谢！
期待回复！

**Comment by KomachiSion** [comment]
这块逻辑没有问题。

1. B节点挂了的情况，除了A以外，其他节点探测也会失败，也会变为Down，因此B的探测会被其他节点分散承担，同样的A节点和其他节点的探测任务也会被重新分配。
2. 如果只是AB节点之间网络异常，那么此时属于网络隔离的状态，根据CAP理论， 此时AB节点各自按照自己的分区进行健康探测，尽可能保证各自节点数据正确性，等待网络恢复后再通过协议一致数据。

**Comment by DSSLP** [comment]
> 这块逻辑没有问题。
> 
> 1. B节点挂了的情况，除了A以外，其他节点探测也会失败，也会变为Down，因此B的探测会被其他节点分散承担，同样的A节点和其他节点的探测任务也会被重新分配。
> 2. 如果只是AB节点之间网络异常，那么此时属于网络隔离的状态，根据CAP理论， 此时AB节点各自按照自己的分区进行健康探测，尽可能保证各自节点数据正确性，等待网络恢复后再通过协议一致数据。


那如果是第2点的话，那分区这段时间内不就会造成某些实例没有被探活到么？这个是被允许的吗？

如有A B C节点，有 1 2 3 4 5 6永久实例，正常情况下A判活的是 1 4， B判活的是 2 5， C判活的是3 6；

A和B之间网络异常，导致A识别的正常节点变为A C，B中的为B C， C由于正常，仍为A B C, 因此探活任务分配为：
A探活的变为 1 3 5，类似的B探活的变为1 3 5，而C还是之前的分配 3 6，从而导致了2实例在分区这段时间内一直未被节点探活。

**Comment by KomachiSion** [comment]
被允许的， 根据CAP理论， AP无法保证所有节点同时数据时一直的，只能尽可能保证， 牺牲一定的一致性而保证可用性，反观CP是牺牲可用性来保证一致性（即出现这个情况的时候，有部分节点是不可读写的）。

同时就你的例子而言

AB之前出现网络异常，此时已经处于异常状态，那么保证集群自身可用性的情况下，尽可能让多数节点能够被探测，而少量节点被降级，保持原始状态，并不违背AP原则。

**Comment by KomachiSion** [comment]
之后网络恢复，ABC节点重新计算责任节点， 各自探测恢复，则自然恢复自愈。

**Comment by KomachiSion** [comment]
当然这个问题是可以继续作为优化点去优化的， 如果能够保证所有节点在所有情况下都能探测到，且集群都是一致的肯定是最好的。

**Comment by DSSLP** [comment]
> 当然这个问题是可以继续作为优化点去优化的， 如果能够保证所有节点在所有情况下都能探测到，且集群都是一致的肯定是最好的。

明白了。

那其实nacos服务节点是接入Jraft的了，是不是可以由主服务节点负责探测所有备服务节点的心跳，从而主判断健康服务节点，并将其同步给所有备服务节点。这样的话所有服务节点维护的健康服务节点是一致的。

这样的话，即使主探测某些备失活，则健康节点数也会相应减少，但每个健康节点分配的任务就会增多，从而不会某些实例没有被探活到。

**Comment by KomachiSion** [comment]
那样leader的压力会很大， 当规模大的时候相当于单点压力，水平扩容形同虚设。

**Comment by KomachiSion** [comment]
而且一个AP协议依赖另外一个CP协议， 这样结论不是一个CAP，而是异常情况下可能只剩P，可能是不太合理的

**Comment by DSSLP** [comment]
> 而且一个AP协议依赖另外一个CP协议， 这样结论不是一个CAP，而是异常情况下可能只剩P，可能是不太合理的

最后再请教一个问题，这里的一个AP协议依赖另外一个CP协议是怎么理解呢？我理解针对持久化实例，使用的都是CP协议吧？应该是不存在AP协议了，如果改成不是两两间探活，而是通过主探活，这是不是应该就只有一个CP协议呢？

**Comment by KomachiSion** [comment]
数据的存储的确是通过CP（raft）协议同步的，但是分片进行健康检查，计算责任节点的工作，是复用了distro协议的分片责任节点的逻辑。这两部分实际上解耦的状态。

如果直接使用Jraft选主来健康检查， 那么leader的压力无限大。

如果继续使用分片责任节点来进行健康检查， 这时候他的协议是AP，而不是CP（再次强调莫不是数据同步，而是健康检查）。
如果这时候又通过leader来分配达成责任节点共识（类似选主）， 那么是AP依赖CP选主，再进行AP责任节点分配。所以是AP依赖CP，故障时会变成选不出主，AP责任节点算不出来，健康检查职只能按照缓存来分配，导致更大面积的降级。

**Comment by DSSLP** [comment]
> 数据的存储的确是通过CP（raft）协议同步的，但是分片进行健康检查，计算责任节点的工作，是复用了distro协议的分片责任节点的逻辑。这两部分实际上解耦的状态。
> 
> 如果直接使用Jraft选主来健康检查， 那么leader的压力无限大。
> 
> 如果继续使用分片责任节点来进行健康检查， 这时候他的协议是AP，而不是CP（再次强调莫不是数据同步，而是健康检查）。 如果这时候又通过leader来分配达成责任节点共识（类似选主）， 那么是AP依赖CP选主，再进行AP责任节点分配。所以是AP依赖CP，故障时会变成选不出主，AP责任节点算不出来，健康检查职只能按照缓存来分配，导致更大面积的降级。

明白了，非常感谢！
