### ISSUE TITLE
does nacos support springboot 2.1.4?

### ISSUE THREAD

**Issue by promise06** [alibaba/nacos#1080]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
The SpringBoot Endpoint can't be discovered by nacos. The SpringBoot Version is "2.1.4.RELEASE".
The nacos plugin version is "0.2.1.RELEASE"
It reports the message like "o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'nacos-discovery' contains invalid characters, please migrate to a valid format."

### Describe what you expected to happen
nacos work with springboot 2.1.4

### How to reproduce it (as minimally and precisely as possible)

1. Deploy an application using springboot 2.1.4
2. Run it
3. Access the nacos api : "/nacos/v1/ns/instance/list", it reports the service is not found

### Tell us your environment
Oracle JDK 1.8
SpringBoot 2.1.4

**Comment by nkorange** [comment]
report it in [Spring Cloud Alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) please.
