### ISSUE TITLE
k8s 连接  MySQL 集群需借助 MySQL router ，怎么部署

### ISSUE THREAD

**Issue by loren-coding** [alibaba/nacos#10819]
使用 sidecar 的方式，希望先启动 sidecar 后，再启动 nacos，依然报错：No DataSource set

![image](https://github.com/alibaba/nacos/assets/49785430/55aecd5f-22b1-424d-ae78-a4543e28b478)
 
![image](https://github.com/alibaba/nacos/assets/49785430/bba2e54f-dbc6-478d-89e0-549fe0cc375d)

**Comment by yearnxiao** [comment]
只能说你操作姿势不对

**Comment by KomachiSion** [comment]
这应该和nacos没有什么关系， 对nacos来说就是用jdbc去连这个url。 no datasource set就是这个url连不上。
