### ISSUE TITLE
客户端无缝开启鉴权 How can the client gracefully enable authentication

### ISSUE THREAD

**Issue by goofmi** [alibaba/nacos#10820]
服务端开启鉴权，客户端立马就会出现连接报错，客户端如何优雅开启鉴权？
When authentication is enabled on the server, a connection error occurs immediately on the client. How can the client gracefully enable authentication?

**Comment by KomachiSion** [comment]
肯定要先在客户端中先添加用户名密码，服务端再开启鉴权。
否则客户端无身份请求， 服务端又开启鉴权了，肯定要拒绝。

**Comment by KomachiSion** [comment]
没有开启鉴权的服务端，有没有用户名密码都可以连接上
所以悖论不存在
