### ISSUE TITLE
OpenAPI V2（HTTP）心跳异常

### ISSUE THREAD

**Issue by lu-xiaoshuang** [alibaba/nacos#10822]
**Describe the bug**
通过OpenAPI V2 (HTTP)的心跳接口周期性（5s）发送心跳，NACOS Server返回20404。

**Expected behavior**
NACOS Server心跳接口返回10200。

**Actually behavior**
NACOS Server心跳接口返回20404。

**How to Reproduce**
1. 部署NACOS集群（3台机器）
2. 编写程序使用OpenAPI V2 (HTTP)与NACOS集群通信
2.1 随机挑选NACOS集群的一台Server，程序调用/nacos/v2/ns/instance接口创建服务实例（临时），创建成功
2.2 周期任务：随机挑选NACOS集群的一台Server，程序调用/nacos/v2/ns/instance/beat接口发送心跳，起初一段时间NACOS Server返回10200，几分钟后NACOS Server返回20400
3. 登录NACOS集群的Server，有些服务器的日志中出现：[AUTO-DELETE-IP] service: alice, ip: bob

**Desktop (please complete the following information):**
 - OS: CentOS
 - Version: nacos-server 2.2.2
 - Module: naming
 - SDK: OpenAPI V2 (HTTP)

**Additional context**
怀疑随机选择NACOS Server发送心跳与NACOS底层数据一致性机制之间存在缺陷

**Comment by KomachiSion** [comment]
V2 http openAPI还有心跳接口？ 应该没有心跳接口才对

**Comment by KomachiSion** [comment]
我看了下， 还真有beat接口， 这个接口不应该存在， v2应该是使用grpc的长连接方式， 不需要beat接口的。

**Comment by hujun-w-2** [comment]
你好，你搭建集群的时候有配置集群的配置文件(cluster.conf)吗？日志中是否还有其他的警告或者错误日志？

**Comment by hujun-w-2** [comment]
返回20404是表示没找到服务，先检查一下cluster.conf文件，然后可以截一下每个节点集群管理的图

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
