### ISSUE TITLE
grpc port setting

### ISSUE THREAD

**Issue by Pigeon-fancier** [alibaba/nacos#10838]
The gRpc port on the client is configurable. You do not need to follow the server configuration

If there is a configuration, the configuration takes effect. It is not the original port + offset mode

**Comment by wilsonwu** [comment]
This is point Nacos can improve on.

**Comment by wilsonwu** [comment]
The offset mode has a little conflict with the Cloud Native concept, it would be better if it can be optimized.

**Comment by KomachiSion** [comment]
It's so confused, Cloud Native concept also has problem for configurable. your port is not stabled. configurable also don't know which you should config.  Same problem with offset.

**Comment by KomachiSion** [comment]
So I think it's offset work well and same with configurable. Because the offset itself is configurable.

**Comment by wilsonwu** [comment]
IMO, the better way is client set the correct port directly instead of auto offset, that means just fix the container port like 8848 and 9848, don't use 8848 and 8848+1000, for NodePort it will auto change to 3xxxx and 3yyyy, just use the 3xxxx and 3yyyy in client config, don't use 3xxxx and 3xxxx+1000 automatically.

**Comment by KomachiSion** [comment]
But this way you need config two ports and let users feel two ports. Of cource we know can config it .

But consider upgrading users, new users and most of standard users, the offset and setting offset way is more simple and more esay.

And directly config port can't solve any acutally problem.  In port changed container or different port env. All users still learn two ports and config two ports which same with the offset configuration.

**Comment by Pigeon-fancier** [comment]
Because the port of nacos server is very easy to configure port transfer, I hope that the client side can freely configure port, or it can be said that the port is occupied in most cases. At this time, I hope that all nacos servers can configure port transfer freely when they use the same configuration file. Of course, this is just my opinion, if you have a better idea, hope to update in time!

**Comment by wilsonwu** [comment]
For compatibility, it should not be removed the auto offset directly, but still many ways to improve it, for example, allow client to config both two ports, and by default without the specific configuration just keep the auto offset work.

**Comment by KomachiSion** [comment]
I'm not recomand to change the way, which can't sovle any problem and make user confused to different version has different way.

And also for two way configuration, more confused which one i should use.

For most of users, the standard usage with default offset is enough. and For upgrade from 1.X users, it's more easy.

**Comment by wilsonwu** [comment]
If the old design can't be change only for don't want to make people confused, all new things should not be generated.

So it is useless for discuss here, that is the project roadmap thing, let's leave this to the right people to consider.

**Comment by KomachiSion** [comment]
The right thing should to do, of cource. But this thing is not right.

The reason has been provided before, Do many things and no any enhance and make users more confused how to use. It's a *wrong* thing. Please don't make one thing and change the concept to `all new things should not be generated`.

If you don't want accept the discussion, you can do any you think in your fork repo.

**Comment by hmleo** [comment]
grpc  port offset can be default use http port + 1000, but should suppert user construct client with custom property.

if one client program need connect differenct nacos server and the server have different offset value, how deal with it ???
