### ISSUE TITLE
nacos-config-spring-boot-starter 什么时候可以支持snakeyaml3.0

### ISSUE THREAD

**Issue by yueye** [alibaba/nacos#10839]
snakeyaml1.33版本以下有漏洞，目前nacos-config-spring-boot-starter0.2.12去初始化配置文件时候使用到了snakeyaml的org.yaml.snakeyaml.constructor的默认构造方法，该方法在snakeyaml3.0中已去除

**Comment by KomachiSion** [comment]
请提交该issue到nacos-spring-boot-starter repo中。
