### ISSUE TITLE
Annotation@Configuration is used together with annotation @RefreshScope. After changing Nacos, the latest data cannot be obtained

### ISSUE THREAD

**Issue by ximenfeixue** [alibaba/nacos#10845]
**Describe the bug**

**Expected behavior**
After nacos is changed, the caller gets the changed value

**Actually behavior**
2023-07-24 08:04:13,365 [INFO] [TID: N/A ] [GID:] (nacos.client.cachedata.internal.notifier) o.s.c.e.e.RefreshEventListener.handle:73 - Refresh keys changed: [data.provider.sets]

After nacos is changed, the caller gets the value before the change

**How to Reproduce**
1. Go to `@Configuration
@RefreshScope
public class SportDataServiceConfig {
    @Value("#{${data.provider.sets:}}")
    public Map<SportType, Set<DataProvider>> sportTypeSetMap;

    public Map<SportType, Set<DataProvider>> getSportTypeSetMap() {
        return sportTypeSetMap;
    }
}
@Service
@RefreshScope
public class Test {

    @Resource
    private SportDataServiceConfig sportDataServiceConfig;

    public Set<DataProvider> getPrimaryDataProviderSet(SportType sportType) {
        if (sportDataServiceConfig.getSportTypeSetMap().containsKey(sportType)) {
            return sportDataServiceConfig.getSportTypeSetMap().get(sportType);
        }
        return Sets.immutableEnumSet(DataProvider.ALL);
    }
}
`
3. Click on 'update naos value',
4. Scroll down to 'getPrimaryDataProviderSet'
5. See errors

**Desktop (please complete the following information):**
 - OS: [ Centos]
 - Version [nacos-server  2.04, nacos-client 2.04]
 - SDK [ spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Please move to spring cloud alibaba community
