### ISSUE TITLE
多数据源使用问题

### ISSUE THREAD

**Issue by qnnn** [alibaba/nacos#10842]
各位老师好，关于nacos 1.4多数据源使用上有些问题，我看到配置中心可以使用多个数据源，并且存在多数据源的健康探测及选主，此时这多个数据源都是可读可写的吗，有什么方式保证多个数据源之间的数据一致吗，是通过数据库之间互为主从还是。

**Comment by wilsonwu** [comment]
感觉这个问题并不是nacos强相关问题，可以考虑存储同步支持或您所说的主从同步之类的方式。

**Comment by qnnn** [comment]
> 

感谢老师解答。因为多数据源如果可以做到可读可写，同时数据也是一致的可以大大提升系统可用性，方便了解一下您们在实现多数据源时是如何做到数据源之间的可读可写跟数据同步吗。或者是最佳实践等，非常感谢！

**Comment by qnnn** [comment]
> 感觉这个问题并不是nacos强相关问题，可以考虑存储同步支持或您所说的主从同步之类的方式。

感谢老师解答。因为多数据源如果可以做到可读可写，同时数据也是一致的可以大大提升系统可用性，方便了解一下您们在实现多数据源时是如何做到数据源之间的可读可写跟数据同步吗。或者是最佳实践等，非常感谢！

**Comment by qnnn** [comment]
> 不客气，市面上最靠谱的方式还是通过存储进行数据同步来保证数据一致性的前提下增加性能，各个厂商的存储都有类似能力和特性，可以参考，纯软件方式貌似没有特别好的方案。

好的，非常感谢老师耐心解答！
