### ISSUE TITLE
I want to contribute to the development of Nacos

### ISSUE THREAD

**Issue by e1se2t** [alibaba/nacos#10844]
![image](https://github.com/alibaba/nacos/assets/67528597/528099ec-5c2f-45ac-a4ef-e71bbe883269)
I want to participate in the construction of Nacos. What are the requirements or qualifications that I need to meet?
我想参与Nacos的建设，我需要具备什么条件？我想是Java方面的

**Comment by onewe** [comment]
[nacos-rust-sdk](https://github.com/nacos-group/nacos-sdk-rust) 欢迎贡献 👏

**Comment by KomachiSion** [comment]
Welcome.

No specified condition need, only you can continue contribute community. No only codes, like document, sdk, and anythings about Nacos is ok.

If you are the first time to contribute, I recommend you start from the tag `contribution welcome` and `good first issue`.
