### ISSUE TITLE
 nacos重启后 再重启服务 会出现读取不到nacos配置文件的问题

### ISSUE THREAD

**Issue by unbeatablerabbit** [alibaba/nacos#10852]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [Unbuntu]
 - Version [nacos-server 2.0.3, nacos-client 1.3.1]
 - SDK [ spring-cloud-alibaba-nacos]

情况是我们在进行灾备演练。然后在nacos2.0.3 结束掉三个集群中的两个实例，然后重启这两个实例。
重启后发现服务全部掉了。与https://github.com/alibaba/nacos/issues/7108这个情况类似。

然后重启后。集群管理里面的状态正常。但是本地启动服务链接nacos配置的配置报找不到。
必须在配置管理里面-编辑，点击发布才可以生效。想问下这里需要在nacos里面加什么配置吗？
**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Additional context**

**Comment by KomachiSion** [comment]
信息过少，请排查客户端及服务端日志，寻找可能的问题。

**Comment by unbeatablerabbit** [comment]
你好，内网服务器，无法推日志到线上，大概是2.0.3版本的jaft选举有问题，在ui界面点击下线后，实际上有一个分节点一直上线下线。

**Comment by unbeatablerabbit** [comment]
然后，nacos2.0.3会出现假启动。每次需要去编辑页面。点击上限，才能读取到配置

**Comment by KomachiSion** [comment]
上线和下线指的是什么？ 服务实例的上下线吗？还是nacos server的？

服务实例的上下线， 请查看nacos文档关于openAPI中，对于变更实例的说明，有记忆时间。

**Comment by unbeatablerabbit** [comment]
nacos server的上下线。比如说nacos-server重启了。之前的配置就读取不了

**Comment by KomachiSion** [comment]
这是不符合预期的， 需要看下server端里有没有什么异常或者错误。

**Comment by unbeatablerabbit** [comment]
我更新了2.2.3版本，貌似就没这个问题了。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
