### ISSUE TITLE
nacos1.2.1 yml update map key failed

### ISSUE THREAD

**Issue by zdd1998** [alibaba/nacos#10866]
**Describe the bug**
firstly，i write a map config on nacos,like this
    myMap:
      "[中文]": value
but when i update the key to 英文，i can still get 中文 from myMap.
anyone meet same problem like this?    

**Expected behavior**
I want nacos map can add  key->value and also delete a key

**Actually behavior**
It seems like only can add key, but delete key failed.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
I can't get your problem from your issue description. Please detail description your problem.

**Comment by zdd1998** [comment]
for example
![image](https://github.com/alibaba/nacos/assets/39595293/9d02538f-252e-465e-8191-69852e8c917e)
i use a map to resolve this data，and i can get ‘中文’ from this map,the value is ‘Chinese’
but when i modify this map key like this
![image](https://github.com/alibaba/nacos/assets/39595293/2bc9473b-2989-4ee3-82b9-f0da13537ff5)
 i can still get ‘中文’ from this map，and also get ‘普通话’
but in fact，i want to delete the ‘中文’ from this map

**Comment by KomachiSion** [comment]
1. whether the config in nacos console changed?
2. whether your app subscribe config, please see nacos console of this config subscribe list.
3. If console show the subscriber existed and the md5 is same, means the config has pushed to your app, but you app don't use the new config.
4. If so, you should check your app whether open auto refresh and use NacosConfig annotation in spring boot. 

If you use spring cloud, please submit issue to spring cloud community.
