### ISSUE TITLE
Import configuration cannot be used on the web management page in version 2.2.2（导入配置点击无反应）

### ISSUE THREAD

**Issue by Azi-mi** [alibaba/nacos#10864]
Type: bug report or feature request

## Describe what happened (or what feature you want)
Clicking on the import configuration button on the web management page in version 2.2 did not respond.
（在Nacos2.2.2的Web界面点击导入配置无反应）

## Describe what you expected to happen
Click the Import Configuration button to import the configuration.

## Tell us your environment
windows11，nacos2.2.2

**Comment by KomachiSion** [comment]
#10318
