### ISSUE TITLE
How to continue sending requests to service instances with a health status of false（如何向健康状态为false的服务实例继续发请求）

### ISSUE THREAD

**Issue by flyletc** [alibaba/nacos#10863]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
When the health status of a service instance in nacos is false, nacos will stop making requests to that service instance
（当nacos中的服务实例健康状态为false时，nacos将停止向该服务实例发请求）
### Describe what you expected to happen
How to continue sending requests to service instances with a health status of false
（如何向健康状态为false的服务实例继续发请求）

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by flyletc** [comment]
> 服务发现时，使用namingService.getAllInstances()等方法都可以获取到不健康实例。是否需要将请求发送到不健康的实例是由RPC框架决定的，nacos-sdk无法决定。

能通过某些配置项，来实现这个需求吗。

**Comment by Bo-Qiu** [comment]
在Spring Cloud Alibaba中，当Nacos用作注册中心时，默认情况下，它不会将请求发送到标记为不健康的实例。但如果你确实需要这样做，可以尝试以下步骤：

禁用 Nacos 的健康检查
默认情况下，Nacos 会排除掉未通过健康检查的实例，所以，我们需要先禁用健康检查功能。

yaml
nacos:
  discovery:
    health-check-mode: none # 将健康检查模式设置为none
自定义 Ribbon 的负载均衡策略
然后，你可能需要自定义 Ribbon 的负载均衡策略，因为默认的负载均衡策略是不会选择标记为不可用的实例的。

首先，创建一个新的 IRule 实现类，这个类将作为你的负载均衡规则。
java
public class MyRule extends AbstractLoadBalancerRule {

    @Override
    public void initWithNiwsConfig(IClientConfig clientConfig) {}

    @Override
    public Server choose(Object key) {
        ILoadBalancer lb = getLoadBalancer();
        List<Server> allServers = lb.getAllServers(); // 获取所有服务器，包括不健康的实例
        // 在这里实现你的负载均衡逻辑，如随机、轮询等
        // 如果你要将请求发送到不健康的实例，也需要在这里处理
    }
}
更新你的 Spring Cloud 配置，使用新的负载均衡规则：
yaml
your-service-name:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.MyRule
请注意，这种方式通常并不推荐，因为将请求发送到不健康的实例可能导致请求失败或者性能下降。但如果你有特殊的需求，你可以尝试这种方法。

另外，这只是一种可能的解决方案，并不能保证在所有情况下都能生效。你可能需要根据你的实际情况调整以上代码和配置。

具体细节可能得看看springcloudAlibaba的注册发现模块和负载均衡模块的实现了

**Comment by flyletc** [comment]
> health-check-mode: none
非常感谢解答，但是在较高的nacos版本中 health-check-mode: none好像没有了这项配置，是否更改为其他配置项了

**Comment by flyletc** [comment]
> 在Spring Cloud Alibaba中，当Nacos用作注册中心时，默认情况下，它不会将请求发送到标记为不健康的实例。但如果你确实需要这样做，可以尝试以下步骤：
> 
> 禁用 Nacos 的健康检查 默认情况下，Nacos 会排除掉未通过健康检查的实例，所以，我们需要先禁用健康检查功能。
> 
> yaml nacos: discovery: health-check-mode: none # 将健康检查模式设置为none 自定义 Ribbon 的负载均衡策略 然后，你可能需要自定义 Ribbon 的负载均衡策略，因为默认的负载均衡策略是不会选择标记为不可用的实例的。
> 
> 首先，创建一个新的 IRule 实现类，这个类将作为你的负载均衡规则。 java public class MyRule extends AbstractLoadBalancerRule {
> 
> ```
> @Override
> public void initWithNiwsConfig(IClientConfig clientConfig) {}
> 
> @Override
> public Server choose(Object key) {
>     ILoadBalancer lb = getLoadBalancer();
>     List<Server> allServers = lb.getAllServers(); // 获取所有服务器，包括不健康的实例
>     // 在这里实现你的负载均衡逻辑，如随机、轮询等
>     // 如果你要将请求发送到不健康的实例，也需要在这里处理
> }
> ```
> 
> } 更新你的 Spring Cloud 配置，使用新的负载均衡规则： yaml your-service-name: ribbon: NFLoadBalancerRuleClassName: com.example.MyRule 请注意，这种方式通常并不推荐，因为将请求发送到不健康的实例可能导致请求失败或者性能下降。但如果你有特殊的需求，你可以尝试这种方法。
> 
> 另外，这只是一种可能的解决方案，并不能保证在所有情况下都能生效。你可能需要根据你的实际情况调整以上代码和配置。
> 
> 具体细节可能得看看springcloudAlibaba的注册发现模块和负载均衡模块的实现了
非常感谢解答，但是在较高的nacos版本中 health-check-mode: none好像没有了这项配置，是否更改为其他配置项了

**Comment by flyletc** [comment]
> 在Spring Cloud Alibaba中，当Nacos用作注册中心时，默认情况下，它不会将请求发送到标记为不健康的实例。但如果你确实需要这样做，可以尝试以下步骤：
> 
> 禁用 Nacos 的健康检查 默认情况下，Nacos 会排除掉未通过健康检查的实例，所以，我们需要先禁用健康检查功能。
> 
> yaml nacos: discovery: health-check-mode: none # 将健康检查模式设置为none 自定义 Ribbon 的负载均衡策略 然后，你可能需要自定义 Ribbon 的负载均衡策略，因为默认的负载均衡策略是不会选择标记为不可用的实例的。
> 
> 首先，创建一个新的 IRule 实现类，这个类将作为你的负载均衡规则。 java public class MyRule extends AbstractLoadBalancerRule {
> 
> ```
> @Override
> public void initWithNiwsConfig(IClientConfig clientConfig) {}
> 
> @Override
> public Server choose(Object key) {
>     ILoadBalancer lb = getLoadBalancer();
>     List<Server> allServers = lb.getAllServers(); // 获取所有服务器，包括不健康的实例
>     // 在这里实现你的负载均衡逻辑，如随机、轮询等
>     // 如果你要将请求发送到不健康的实例，也需要在这里处理
> }
> ```
> 
> } 更新你的 Spring Cloud 配置，使用新的负载均衡规则： yaml your-service-name: ribbon: NFLoadBalancerRuleClassName: com.example.MyRule 请注意，这种方式通常并不推荐，因为将请求发送到不健康的实例可能导致请求失败或者性能下降。但如果你有特殊的需求，你可以尝试这种方法。
> 
> 另外，这只是一种可能的解决方案，并不能保证在所有情况下都能生效。你可能需要根据你的实际情况调整以上代码和配置。
> 
> 具体细节可能得看看springcloudAlibaba的注册发现模块和负载均衡模块的实现了

非常感谢解答，但是在较高版本的nacos中好像没有了这个配置项``nacos: discovery: health-check-mode: none``，是已经替换成其他配置项了吗

**Comment by KomachiSion** [comment]
`nacos: discovery: health-check-mode: none` 这个配置项从来就不存在，上述的解答是让你在loadbalancer中进行解决，意思是不要使用默认的loadbalancer而是自定义loadbalance规则。

**Comment by flyletc** [comment]
> `nacos: discovery: health-check-mode: none` 这个配置项从来就不存在，上述的解答是让你在loadbalancer中进行解决，意思是不要使用默认的loadbalancer而是自定义loadbalance规则。

好的了解

**Comment by 985492783** [comment]
> 在Spring Cloud Alibaba中，当Nacos用作注册中心时，默认情况下，它不会将请求发送到标记为不健康的实例。但如果你确实需要这样做，可以尝试以下步骤：
> 
> 禁用 Nacos 的健康检查 默认情况下，Nacos 会排除掉未通过健康检查的实例，所以，我们需要先禁用健康检查功能。
> 
> yaml nacos: discovery: health-check-mode: none # 将健康检查模式设置为none 自定义 Ribbon 的负载均衡策略 然后，你可能需要自定义 Ribbon 的负载均衡策略，因为默认的负载均衡策略是不会选择标记为不可用的实例的。
> 
> 首先，创建一个新的 IRule 实现类，这个类将作为你的负载均衡规则。 java public class MyRule extends AbstractLoadBalancerRule {
> 
> ```
> @Override
> public void initWithNiwsConfig(IClientConfig clientConfig) {}
> 
> @Override
> public Server choose(Object key) {
>     ILoadBalancer lb = getLoadBalancer();
>     List<Server> allServers = lb.getAllServers(); // 获取所有服务器，包括不健康的实例
>     // 在这里实现你的负载均衡逻辑，如随机、轮询等
>     // 如果你要将请求发送到不健康的实例，也需要在这里处理
> }
> ```
> 
> } 更新你的 Spring Cloud 配置，使用新的负载均衡规则： yaml your-service-name: ribbon: NFLoadBalancerRuleClassName: com.example.MyRule 请注意，这种方式通常并不推荐，因为将请求发送到不健康的实例可能导致请求失败或者性能下降。但如果你有特殊的需求，你可以尝试这种方法。
> 
> 另外，这只是一种可能的解决方案，并不能保证在所有情况下都能生效。你可能需要根据你的实际情况调整以上代码和配置。
> 
> 具体细节可能得看看springcloudAlibaba的注册发现模块和负载均衡模块的实现了

你这是gpt的回答吧

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
