### ISSUE TITLE
dm org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; 违反表[config_info]唯一性约束; nested exception is dm.jdbc.driver.DMException: 违反表[config_info]唯一性约束  

### ISSUE THREAD

**Issue by HuangRenhui** [alibaba/nacos#10861]
ExternalConfigInfoPersistServiceImpl.java
    @Override
    public void insertOrUpdate(String srcIp, String srcUser, ConfigInfo configInfo, Timestamp time,
            Map<String, Object> configAdvanceInfo, boolean notify) {
        try {
            addConfigInfo(srcIp, srcUser, configInfo, time, configAdvanceInfo, notify);
        } catch (DuplicateKeyException ive) { // Unique constraint conflict
            updateConfigInfo(configInfo, srcIp, srcUser, time, configAdvanceInfo, notify);
        }
    }
this is DuplicateKeyException ,but extend datasource dm/kingbase is DataIntegrityViolationException，it can not  catch exception,so update failed.
spring-jdbc：SQLStateSQLExceptionTranslator
classcode is 23,so throw DataIntegrityViolationException
![image](https://github.com/alibaba/nacos/assets/25076816/32c4ce26-bc77-4155-b539-f2bfe8b728d6)

mysql enter SQLErrorCodeSQLExceptionTranslator.java 
![image](https://github.com/alibaba/nacos/assets/25076816/1e77a629-0ae3-46ea-91b9-711f333b4703)

**Comment by KomachiSion** [comment]
duplicate with #10353, move to #10353 discussion
