### ISSUE TITLE
GlobalExecutor.scheduleUdpSender trigger Memory leak on nacos2.2.3

### ISSUE THREAD

**Issue by Mararesliu** [alibaba/nacos#10867]
**Describe the bug**
UdpConnector#sendDataWithCallback
GlobalExecutor.scheduleUdpSender trigger Memory leak
**Expected behavior**
send udp callback do not trigger memory leak

**Actually behavior**
queue occupy heap memory cause  by udp send callback

**How to Reproduce**
1、run 6k+ instance for a few days，if lantecy network better
2、see heap memory change

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] centos7
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] nacos-server 2.2.3, nacos-client 1.4.1
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
use Executors.newScheduledThreadPool is  an unbounded queue。

**Comment by Mararesliu** [comment]
use Executors.newScheduledThreadPool is an unbounded queue and unlimited pool size

**Comment by Mararesliu** [comment]
JVM use 4G

**Comment by KomachiSion** [comment]
There is no memory leak, each udp subscriber will beat for 10s interval, and no beat will remove the subscriber.

And each push retry max twice. So the memory can be released, otherwise no 2.2.3, all server include 0.X, memory is leaked.

If you think it use many memory, means your client is 1.X version and sub many service, and your env udp connection can't work. So the udpSender will retry for each push twice and waiting some time.

You can upgrade your client to 2.X, which will not use grpc to push data not udp.

**Comment by Mararesliu** [comment]
nacos server stuck, occupy  all memory on Test。We know client upgrade should be dealed ,but Client version can not upgrade in time follow with nacos server version on Production。We plan to upgrade server version, and upgrade client one by one  for a period of time。

**Comment by Mararesliu** [comment]
i see what u said remove UdpConnector's map. But it's no because that. The matter is  so many work queue java.util.concurrent.RunnableScheduledFuture[] (about 93w). It may be the runnable can not  finished in time.

**Comment by KomachiSion** [comment]
queue still increase means your push task added continuously and your old task stiil timeout and need to retry twice. 

You should research from you env from follow:

1. see whether your services registered into nacos is not stable, naming-server.log can see whether services changed continuously
2. your udp push failed, check the upd env is work well and the udp push ip and port is right.
3. If you can't use udp push and large change services is expected, you should close the udp push feature by set push Version. `curl -X PUT "127.0.0.1:8848/nacos/v1/ns/ops/switches?entry=pushVersion&value=java:2.0.0"`
