### ISSUE TITLE
能否使用外部配置文件来配置Nacos服务器地址等属性

### ISSUE THREAD

**Issue by ldcsaa** [alibaba/nacos#10869]
**应用场景**
我的项目是Springboot项目，与运行环境相关的配置都存储在配置中心，所以应用只需打包一次，就可以把该包发布到DEV/QA/PROD等环境。

现在的问题是：不同环境的配置中心地址不一样。可选处理方式：
  1. 用spring.profile把所有环境的nacos地址都写在应用程序内部的各个profile配置文件中，显得不优雅，又容易造成信息泄露
  2. 用 JVM 参数 -Dspring.cloud.nacos.config.server-addr，每个应用的启动命令都要添加且不容易修改

**其它中间件示例**
1. Dubbo： 可以通过 JVM参数 -Ddubbo.properties.file 指定一个外部配置文件，Dubbo注册中心等信息可以配置在文件
2. Apollo ：它的 Meta Server 地址默认配置在 /opt/settings/server.properties 文件

**建议**
类似 Dubbo 和 Apollo，Nacos 也提供一个外部配置文件选项，方便应用在不同环境中部署

**Comment by DarrenLuo** [comment]
emmmm，springboot的配置文件是可以外置的啊，引用一下[官方文档](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config)

也就是说jar外部的配置文件优先级高于内部，直接在jar所在文件夹增加一个application.yaml应该就可以覆盖掉jar包内部的配置，如果觉得同级目录容易泄露信息或者不优雅，那么也可以指定配置文件所在位置 `-Dspring.config.location`

**Comment by KomachiSion** [comment]
首先这个问题和Nacos，Apollo，dubbo都无关， 配置中心地址本身就是放在spring cloud的bootstrap里，spring cloud本身支持对bootstrap的参数进行外部配置。

至于你说的，要加一个单独的参数来控制，需要提交issue到SCA社区
