### ISSUE TITLE
tag代码编译都有报错  ，develop分支没有问题

### ISSUE THREAD

**Issue by ysuzhaixuefei** [alibaba/nacos#10874]
nacos-sys 模块报错  程序包org.springframework.context不存在
分支是2.2.1

我这里用develop分支编译是没问题的  其他的tag拉下来编译都有问题

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/8e63d1ca-22f3-4b6f-a645-45b4d919a693)

I can't reproduce.  build with 2.2.1 tag in my env is no problem. Please check your env cache and env problem.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
