### ISSUE TITLE
nacos2.2.0 版本，配置nginx后无法登录

### ISSUE THREAD

**Issue by cuizhixuan** [alibaba/nacos#10873]
![image](https://github.com/alibaba/nacos/assets/89146826/90360ee6-d92f-4ae7-93b1-f16371c8521e)

caused: When allowCredentials is true, allowedOrigins cannot contain the special value \"*\" since that cannot be set on the \"Access-Control-Allow-Origin\" response header. To allow credentials to a set of origins, list them explicitly or consider using \"allowedOriginPatterns\" instead.;

location ^~ /nacos/ {
        proxy_pass http://127.0.0.1:8848;
        proxy_read_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Proto http;
}

**Comment by KomachiSion** [comment]
不走nginx可以登录吗？ 如果可以的话就是niginx配置的问题，需要自查。

**Comment by cuizhixuan** [comment]
> 不走nginx可以登录吗？ 如果可以的话就是niginx配置的问题，需要自查。

本地可以的

**Comment by cuizhixuan** [comment]
> 不走nginx可以登录吗？ 如果可以的话就是niginx配置的问题，需要自查。

通过ip+端口的方式可以登录

**Comment by KomachiSion** [comment]
那应该是nginx配置的问题，这需要您自查nginx配置了。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
