### ISSUE TITLE
Question about nacos performance test report

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/nacos#1088]
> https://nacos.io/en-us/docs/nacos-naming-benchmark.html?spm=a2c4e.11153940.blogcont698930.12.6f7564delic4CR
性能测试结论
Nacos服务发现性能测试都是针对重点功能，通过对3节点规模集群进行压测，可以看到接口性能负载和容量。
压测容量服务数可达60W，实例注册数达110W，集群运行持续稳定，达到预期；
注册/查询实例TPS达到 13000 以上，接口达到预期；

我的疑问：100w的实例，5s一次心跳，每秒的心跳就20w了。nacos的tps才一万多，根本承受不了这么高的心跳。
说明这个性能测试是没有发送心跳请求的，一点都不真实啊！然后就对外宣传支持百万级的实例，很容易误导大家啊。

**Comment by nkorange** [comment]
官网目前的测试报告确实是压的HTTP注册接口TPS，也确实没有心跳上报，这一点你是对的。

关于百万实例容量及心跳，Nacos也确实是支持的，但是需要Nacos集群进行水平扩容，后面会更新官网的测试报告来修正这一描述。
