### ISSUE TITLE
Nacos 2.2.1 使用内嵌数据库+集群模式，关闭一半节点就会报错，配置文件无法正常使用

### ISSUE THREAD

**Issue by sheldon-lu** [alibaba/nacos#10894]
2.2.1版本 
情况：两台服务器，每一台启动3个nacos服务，使用内置数据库。正常6个nacos服务组成集群，一切正常，如果突然关闭其中一台服务器，只剩3个nacos服务，就会报错
日志以及页面错误：The Raft Group [nacos_config] did not find the Leader node

集群如果一半节点挂了之后，不能重新选主？
![image](https://github.com/alibaba/nacos/assets/31846425/decdd7e7-d940-4c4b-90bb-299f13853ea7)

**Comment by KomachiSion** [comment]
raft需要半数以上节点投票， 你一下干掉半数，肯定不行。

请参考raft相关资料查看
