### ISSUE TITLE
nacos多环境配置文件缓存问题?

### ISSUE THREAD

**Issue by chengyonghu** [alibaba/nacos#10899]
nacos 1.3.0版本
多命名空间
多环境开发
操作步骤: XX命名空间-->克隆到XX新的命名空间;
在切换成刚刚克隆的新环境,启动工程有时会提示配置文件找不到;
需要手动编辑配置文件(编辑->发布,但是不作任何更改),此时配置文件会生效;
有时候需要编辑多次才会生效,很疑惑!!!!!

**Comment by KomachiSion** [comment]
感觉和编辑发布没什么关系， 什么内容都不修改， md5是不会变的。

感觉要么是客户端没有获取到配置，要么是获取到了配置但是应用没有使用到，具体可以看下client的日志和server的日志。或者看下控制台上这个配置的监听者的md5是否和配置的md5一致。

**Comment by chen-jie** [comment]
多套nacos连接同一个数据库也有相同的问题。
nacos集群1改了某个配置，nacos集群2能在控制台页面上显示出来，但是连接nacos集群2的服务读不到，需要在nacos集群2上编辑发布，连接nacos集群2的服务才能读到配置。

**Comment by KomachiSion** [comment]
这是必然的啊， 集群1和集群2本来就没有关联性， 用同一个数据库还会导致数据冲突。 这是你部署使用问题，建议稍微了解一下配置中心的同步机制。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by marksmansj** [comment]
> 这是必然的啊， 集群1和集群2本来就没有关联性， 用同一个数据库还会导致数据冲突。 这是你部署使用问题，建议稍微了解一下配置中心的同步机制。

请问一下，如果我希望nacos双中心多活部署的话，如下方式是否可行？
1、配置中心
我在idc1部署nacos1连接mysql1 ，然后在idc2部署nacos2连接mysql2 ，mysql1和mysql2通过两个机房的专线做主从同步 ， 这样我在idc1 nacos1发布的配置，也会同步到idc2 nacos2 。
2、注册中心
每个机房的应用各自通过nacos域名注册进各自idc的nacos
