### ISSUE TITLE
1.0.0 Questions about dynamically changing the log level

### ISSUE THREAD

**Issue by lynk-coder** [alibaba/nacos#1089]
I found that once I configured spring-cloud-starter-alibaba-nacos-config, the dynamic level of my log will not take effect. I wonder if this is a BUG, or how do I need to adjust it?

springboot 2.x+springcloud+nacos+logback

LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
loggerContext.getLogger("org.mybatis.log.sql").setLevel(Level.valueOf(Config.IS_BEBUG?"debug":"warn"));

Dynamic failure

**Comment by lynk-coder** [comment]
"???????????????

**Comment by nkorange** [comment]
@lynk-coder Did you try other version of spring-cloud-starter-alibaba-nacos-config? Does the problem still exist?

**Comment by lynk-coder** [comment]
I've tried the current version, which is still under construction, and the problem persists.

spring-cloud-alibaba-dependencies
0.9.1.BUILD-SNAPSHOT

**Comment by nkorange** [comment]
@lynk-coder Can you paste or upload a minimum runnable source package to reproduce this problem?

**Comment by lynk-coder** [comment]
Ok, let me try.

**Comment by lynk-coder** [comment]
Resolved, I initialize the dynamic switch log level code after the Config configuration can be.
