### ISSUE TITLE
Should we provide a configuration item for the maximum number of push retries, instead of directly hardcoding it to 50 times in the code?

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#10891]
**Is your feature request related to a problem? Please describe.**
Should we provide a configuration item for the maximum number of push retries, instead of directly hardcoding it to 50 times in the code?

**Describe the solution you'd like**
Provide a configuration item for the maximum number of push retries, instead of directly hardcoding it to 50 times in the code.

**Describe alternatives you've considered**
Provide a configuration item for the maximum number of push retries, instead of directly hardcoding it to 50 times in the code.

**Additional context**
'''
![image](https://github.com/alibaba/nacos/assets/46370663/70aa5603-437d-4a80-ad92-d3b409d1b29f)
'''

**Comment by Bo-Qiu** [comment]
I will submit a PR, and if necessary, it can be merged.

**Comment by KomachiSion** [comment]
Should not, duplicate with #10727

**Comment by Bo-Qiu** [comment]
But the task in the push configuration is set with a default retry limit of 50, not set to retry forever.

**Comment by Bo-Qiu** [comment]
By the way, for configuration, the client will actively pull from the server side, so there won't be a situation where the data is inconsistent between the client and the server.

**Comment by KomachiSion** [comment]
OK
