### ISSUE TITLE
Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

### ISSUE THREAD

**Issue by catch6** [alibaba/nacos#10890]
**Describe the bug**
使用 SpringCloud Alibaba 2022.0.0.0 版本，nacos-client使用 2.2.3(2.2.1也试过)，在启用的时候会出现警告日志
```
2023-08-01 10:02:14.071 [               ]  WARN [  restartedMain] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.2)

2023-08-01 10:02:14.968 [               ]  WARN [  restartedMain] c.a.nacos.client.logging.NacosLogging    : Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

```

**Expected behavior**
正常启动无警告

**Actually behavior**
出现警告

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: Macos m1 pro
 - Version nacos-server 2.2.3, nacos-client 2.2.3
 - Module naming
 - SDK spring-cloud-starter-alibaba-nacos-discovery

**Additional context**
下面是 debug 的一些信息：
<img width="658" alt="image" src="https://github.com/alibaba/nacos/assets/15259698/cc54ec12-b59c-4a5f-9c13-5c603892e394">
首先这里没明白，如果不存在`ch.qos.logback.core.model.Model`就把userVersion置为 1， logback1.4.5有这个类，所以userVersion并没有设置为 1，而是默认值 2，这就导致下面在进行 filter 过滤后，集合已经没有元素，这时去 get(0)发送下标越界异常
<img width="962" alt="image" src="https://github.com/alibaba/nacos/assets/15259698/311a1819-8842-4f21-8cca-d10be513a104">

<img width="975" alt="image" src="https://github.com/alibaba/nacos/assets/15259698/193cac39-0899-4dec-9d67-defd814e27b3">

<img width="1120" alt="image" src="https://github.com/alibaba/nacos/assets/15259698/b1b7ab48-906e-431d-aa05-f1d76cb7277f">

**Comment by catch6** [comment]
确实是，添加了logback-adapter依赖就可以了，不过 SpringBoot3.0.2默认就是依赖 logback1.4.5，而且adapter里也没几个文件，完全可以集成到nacos-client里来呀。

引入这个依赖，还需要随时关注什么时候nacos-client兼容logback1.4.x了，以便移除对adapter的依赖

**Comment by imyxiao** [comment]
昨天看到SCA release 2022.0.0.0了，马上升级，就看到这个问题了。

[Load Logback Configuration of Nacos fail](https://github.com/alibaba/spring-cloud-alibaba/issues/3413)

**Comment by KomachiSion** [comment]
> @KomachiSion 感谢！确实是，添加了logback-adapter依赖就可以了，不过 SpringBoot3.0.2默认就是依赖 logback1.4.5，而且adapter里也没几个文件，完全可以集成到nacos-client里来呀。
> 
> 引入这个依赖，还需要随时关注什么时候nacos-client兼容logback1.4.x了，以便移除对adapter的依赖

直接集成过来就会出现老版本的兼容问题了，因为nacos项目在构建编译的时候需要指定一个logback版本来执行，只是默认用哪个版本的问题。

**Comment by KomachiSion** [comment]
随着logback1.4版本逐渐被接受和升级，后续版本默认版本应该会变为1.4，老版本会出adapter来适配。不过具体什么时候做这个升级，要看社区的投票结果。

**Comment by cavellpotter** [comment]
> logback的1.4版本对旧版本不兼容， Nacos-Group下有一个适配logback1.4版本的工程 https://github.com/nacos-group/logback-adapter

网关项目中使用会报错
https://github.com/nacos-group/logback-adapter/issues/3

**Comment by fgyang** [comment]
我本的的异常为 Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from null,最后不是nacos-logback.xml而是一个null,各位大佬知道为什么么？版本为2022.0.0.0-RC2
