### ISSUE TITLE
nacos config 报  ErrCode:-400,ErrMsg:endpoint is blank

### ISSUE THREAD

**Issue by wenfer** [alibaba/nacos#1090]
配置了yaml文件的配置
![图片](https://user-images.githubusercontent.com/16834499/56481161-3d9ae200-64f0-11e9-9f79-a8aca60382c7.png)
![图片](https://user-images.githubusercontent.com/16834499/56481170-48ee0d80-64f0-11e9-90e0-19e8dc132496.png)

<img width="1234" alt="QQ20190422-111833@2x" src="https://user-images.githubusercontent.com/16834499/56481194-6c18bd00-64f0-11e9-85e1-c7219146112f.png">

**Comment by nkorange** [comment]
Nacos client版本？
