### ISSUE TITLE
引入nacos后的初始化顺序问题

### ISSUE THREAD

**Issue by zengshuimu** [alibaba/nacos#10902]
![企业微信截图_16909626753952](https://github.com/alibaba/nacos/assets/103546816/68200a65-a9fc-49c2-b5ee-489bd78ec4a1)

如图原本 执行顺序 是1 2，引入nacos后变成了2 1，导致初始化create database 未执行 便连接了数据。从而出错。这种情况应该如何处理呢，换句话来说，mybatisplus的执行顺序比主应用的@PostConstruct提前运行了，这部分代码如何处理呢，请求指点

**Comment by wangshengji** [comment]
org.springframework.beans.factory.config.BeanFactoryPostProcessor#postProcessBeanFactory 尝试下这个方法进行数据库初始化。在Bean 为创建之前进行

**Comment by zengshuimu** [comment]
> org.springframework.beans.factory.config.BeanFactoryPostProcessor#postProcessBeanFactory 尝试下这个方法进行数据库初始化。在Bean 为创建之前进行

好的~谢谢。已解决。
