### ISSUE TITLE
The ConfigCacheService class has incorrectly used the @Autowired annotation.

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#10908]
**Describe the bug**
The ConfigCacheService class improperly uses the Autowired annotation to decorate a static member variable, and the ConfigCacheService class is not annotated with the component annotation.

**Expected behavior**
Use ApplicationContext.getBean() method to obtain the bean object and assign it to this static member variable.

**Actually behavior**
The ConfigCacheService class improperly uses the Autowired annotation to decorate a static member variable, and the ConfigCacheService class is not annotated with the component annotation.

**Additional context**
![image](https://github.com/alibaba/nacos/assets/46370663/5bdf5efa-cae8-4c15-8ed0-283168f4d6aa)

**Comment by Bo-Qiu** [comment]
If it is indeed a bug and there's a necessity for correction, I will submit a Pull Request.

**Comment by KomachiSion** [comment]
@shiyiyue1102 Please make sure this issue
