### ISSUE TITLE
Remove the udpport parameter parameter.

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#10906]
**Is your feature request related to a problem? Please describe.**

In the latest version, the udp port parameter is not used, so whether to remove the udpport parameter.

In the latest version of Nacos Client, the udpport parameter is only used in the NamingClientProxy#queryInstancesOfService method. Currently, several dependencies are found, as shown below：

https://github.com/alibaba/nacos/blob/837012488904e5df40875283d8a2dac84a085c07/client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java#L234-L251

https://github.com/alibaba/nacos/blob/837012488904e5df40875283d8a2dac84a085c07/client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java#L294-L308

https://github.com/alibaba/nacos/blob/837012488904e5df40875283d8a2dac84a085c07/client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java#L366-L380

https://github.com/alibaba/nacos/blob/837012488904e5df40875283d8a2dac84a085c07/client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java#L178-L219

The parameters passed to udpport here are all 0 and it does not take effect. Can it be removed?

**Comment by KomachiSion** [comment]
The parameter is used by NamingHttpClientProxy, for 1.X api adapt.
After 2.2.0, The method of NamingHttpClientProxy can be change to unsupported.

The issue https://github.com/alibaba/nacos/issues/10824 has start to do this, I think you can move to this issue discussion together.
