### ISSUE TITLE
nacos-client更新实例时，为什么会将控制台修改的实例元数据复原呢？

### ISSUE THREAD

**Issue by wyjie0** [alibaba/nacos#10907]
nacos client版本：2.2.3
nacos server版本：2.2.3
注册实例时，元数据设置为{"A":"value1"}；控制台界面将元数据修改为{"A":"value2"}；代码中调用修改实例方法成功后，控制台上看到元数据被复原成了{"A":"value1"}，这是为什么呢？在client和server代码中都没看到有使用缓存的地方

**Comment by Bo-Qiu** [comment]
能将具体的复现步骤写明一下吗？便于复现定位问题。 （比如调用修改实例方法  具体是哪个API）

**Comment by wyjie0** [comment]
> 能将具体的复现步骤写明一下吗？便于复现定位问题。 （比如调用修改实例方法 具体是哪个API）

步骤如下：
1. client调用`com.alibaba.nacos.api.naming.NamingService#registerInstance(java.lang.String, java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)` 注册实例，此时元数据为{"A":"value1"}
2. 控制台修改该实例元数据为{"A": "value2";"B": "valueB"}
3. client调用`com.alibaba.nacos.api.naming.NamingMaintainService#updateInstance(java.lang.String, java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)`方法修改实例，此时两种情况：
    3.1 如果修改时没有给实例设置元数据，方法调用成功后，控制台上元数据被复原为{"A": "value1"}
    3.2 如果修改时新增元数据{"C": "valueC"}，方法调用成功后，控制台上元数据为{"A": "value1"; "C": "valueC"}

**Comment by Bo-Qiu** [comment]
按照操作步骤可复现此问题，确实是Bug，我会在近期对其进行修复，感谢反馈。

**Comment by wyjie0** [comment]
> 按照操作步骤可复现此问题，确实是Bug，我会在近期对其进行修复，感谢反馈。

好的，是什么原因导致的呢？我在新增元数据的时候，看server端收到只有新增的字段，是server端在哪儿用了缓存吗？
还有一个问题，修复后`updateInstance`这个方法是可以新增、修改元数据，不会冲掉控制台的修改吗？

**Comment by wyjie0** [comment]
> 

找到原因了

**Comment by Bo-Qiu** [comment]
com.alibaba.nacos.naming.core.v2.index.ServiceStorage#parseInstance时，会用InstanceMetadata中的实例元数据和InstancePublishInfo中的实例元数据结合生成返回结果中的实例元数据。
 在删改实例元数据时，没考虑删改InstancePublishInfo中的metadata信息，当InstanceMetadata中不存在InstancePublishInfo相对应的键值对时，会将InstanceMetadata中的键值对一并作为metadata返回。

**Comment by Bo-Qiu** [comment]
算是设计上的缺陷吧，优先以InstanceMetadata中的键值对为准，当InstanceMetadata中meatada的键值对未覆盖到InstancePublishInfo的metadata键值对时，InstancePublishInfo中的metada键值对会被返回。InstancePublishInfo中的metada不会被增删改。

**Comment by Bo-Qiu** [comment]
现在有两种思路:
一种是修改实例metadata时不光修改InstanceMetadata也修改InstancePublishInfo，但这不太符合InstancePublishInfo的语义（InstancePublishInfo表示注册时的实例信息）
第二种是针对metadata设计标志，当有对其进行更新操作后，只以metadata的实例元数据为准，不再使用InstancePublishInfo的元数据，只有当未更新写入过metadata时，才以InstancePublishInfo的元数据为准。
具体解决方案会和社区讨论好后 提交PR。

**Comment by Bo-Qiu** [comment]
> > 按照操作步骤可复现此问题，确实是Bug，我会在近期对其进行修复，感谢反馈。
> 
> 好的，是什么原因导致的呢？我在新增元数据的时候，看server端收到只有新增的字段，是server端在哪儿用了缓存吗？ 还有一个问题，修复后`updateInstance`这个方法是可以新增、修改元数据，不会冲掉控制台的修改吗？

会覆盖掉的。元数据更新不是增量，而是直接以当前传递的 覆盖掉之前的。

**Comment by wyjie0** [comment]
> 

好的

**Comment by wyjie0** [comment]
> 现在有两种思路: 一种是修改实例metadata时不光修改InstanceMetadata也修改InstancePublishInfo，但这不太符合InstancePublishInfo的语义（InstancePublishInfo表示注册时的实例信息） 第二种是针对metadata设计标志，当有对其进行更新操作后，只以metadata的实例元数据为准，不再使用InstancePublishInfo的元数据，只有当未更新写入过metadata时，才以InstancePublishInfo的元数据为准。 具体解决方案会和社区讨论好后 提交PR。

好的，是否也可以将实例最新的元数据和client传的元数据合并，实例最新元数据中如果存在相同key就覆盖，不存在就新增

**Comment by Bo-Qiu** [comment]
本质上就是要解决 “无法通过updateInstance移除实例注册时写入的元数据信息” 这个问题。

**Comment by KomachiSion** [comment]
并没有问题， maintainService 写的就是运维用的， updateInstance调用的是更新实例的接口， openAPI中写明了， 这个更新接口有更高的优先级。

目前client在注册服务的元数据是运行时数据， 运维接口更新的数据为运维元数据， 服务端会合并，冲突时以运维元数据优先。

**Comment by Bo-Qiu** [comment]
> 并没有问题， maintainService 写的就是运维用的， updateInstance调用的是更新实例的接口， openAPI中写明了， 这个更新接口有更高的优先级。
> 
> 目前client在注册服务的元数据是运行时数据， 运维接口更新的数据为运维元数据， 服务端会合并，冲突时以运维元数据优先。

okkk

**Comment by wyjie0** [comment]
> 本质上就是要解决 “无法通过updateInstance移除实例注册时写入的元数据信息” 这个问题。

我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧

**Comment by Bo-Qiu** [comment]
> > 本质上就是要解决 “无法通过updateInstance移除实例注册时写入的元数据信息” 这个问题。
> 
> 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧

这个设计其实并没有问题，是我理解错了，老哥。

元数据存在两种，一种是运行时元数据，一种是运维元数据。在管控界面做变更（或者调用运维接口），修改的是全量运维元数据，运行时元数据是注册时上传的不允许增删改。

使用时，是服务端将运行时元数据和运维元数据进行结合后返回给客户端的，若存在相同key时，使用运维元数据的k-v，若不存在直接将二者合并返回。

**Comment by wyjie0** [comment]
> 

按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。

**Comment by wyjie0** [comment]
> > 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧
> 
> 按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。

更直观的现象是，maintainService调用两次updateInstance方法，第二次新增的元数据，会把第一次新增的元数据冲掉

**Comment by Bo-Qiu** [comment]
> > > 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧
> > 
> > 
> > 按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。
> 
> 更直观的现象是，maintainService调用两次updateInstance方法，第二次新增的元数据，会把第一次新增的元数据冲掉

规则是如此的，每次调用运维接口更新的元数据 会覆盖历史的运维元数据。  直接使用当前传递的metadataMap 替换掉 历史的matadataMap，不是增量操作。

代码如下：
‘’‘
public void updateInstanceMetadata(Service service, String metadataId, InstanceMetadata instanceMetadata) {
        if (!instanceMetadataMap.containsKey(service)) {
            instanceMetadataMap.putIfAbsent(service, new ConcurrentHashMap<>(INITIAL_CAPACITY));
        }
        instanceMetadataMap.get(service).put(metadataId, instanceMetadata);
    }
’‘’

**Comment by Bo-Qiu** [comment]
简单举个例子，  实例的运行时元数据为k1-v1， 你调用了两次运维接口设置运维元数据，第一次调用传递 k1-vv, k2-v，这时候查出来的结果就是k1-vv,k2-v。 此时server中存储的运行时元数据为k1-v1，运维元数据为k1-vv, k2-v。  第二次调用运维接口更新时，传递的值k3-v，此时server中存储的运维元数据将直接被替换为k3-v，如此查出来的结果将是k1-v1,k3-v。

针对运维元数据 不是进行的增量，而是直接用新map 替换掉原有map。  如果只做增量，那运维元数据将无法被删除了，只能增和改，这样用起来也是不太符合实际场景的。

**Comment by Bo-Qiu** [comment]
老哥你的需求应该是 ”需要增量更新运维元数据，而不是直接覆盖“  对吧？  针对这个需求我确认下是否可以在新版本Sdk中提供一个增量更新运维元数据的接口

**Comment by wyjie0** [comment]
> > > > 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧
> > > 
> > > 
> > > 按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。
> > 
> > 
> > 更直观的现象是，maintainService调用两次updateInstance方法，第二次新增的元数据，会把第一次新增的元数据冲掉
> 
> 规则是如此的，每次调用运维接口更新的元数据 会覆盖历史的运维元数据。 直接使用当前传递的metadataMap 替换掉 历史的matadataMap，不是增量操作。
> 
> 代码如下： ‘’‘ public void updateInstanceMetadata(Service service, String metadataId, InstanceMetadata instanceMetadata) { if (!instanceMetadataMap.containsKey(service)) { instanceMetadataMap.putIfAbsent(service, new ConcurrentHashMap<>(INITIAL_CAPACITY)); } instanceMetadataMap.get(service).put(metadataId, instanceMetadata); } ’‘’

这段代码我后买你看到了， 用的注册时元数据和运维元数据合并，之前你说是bug我还以为这里是有问题

**Comment by wyjie0** [comment]
> 老哥你的需求应该是 ”需要增量更新运维元数据，而不是直接覆盖“ 对吧？ 针对这个需求我确认下是否可以在新版本Sdk中提供一个增量更新运维元数据的接口

是有这个需求，我看OpenAPI有更新、删除元数据的接口，不过client还没有；
这个需求我目前也可以用其他方法来实现，每次传全量元数据

**Comment by Bo-Qiu** [comment]
> > > > > 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧
> > > > 
> > > > 
> > > > 按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。
> > > 
> > > 
> > > 更直观的现象是，maintainService调用两次updateInstance方法，第二次新增的元数据，会把第一次新增的元数据冲掉
> > 
> > 
> > 规则是如此的，每次调用运维接口更新的元数据 会覆盖历史的运维元数据。 直接使用当前传递的metadataMap 替换掉 历史的matadataMap，不是增量操作。
> > 代码如下： ‘’‘ public void updateInstanceMetadata(Service service, String metadataId, InstanceMetadata instanceMetadata) { if (!instanceMetadataMap.containsKey(service)) { instanceMetadataMap.putIfAbsent(service, new ConcurrentHashMap<>(INITIAL_CAPACITY)); } instanceMetadataMap.get(service).put(metadataId, instanceMetadata); } ’‘’
> 
> 这段代码我后买你看到了， 用的注册时元数据和运维元数据合并，之前你说是bug我还以为这里是有问题

上文的这段代码是更新运维元数据的代码com.alibaba.nacos.naming.core.v2.metadata.InstanceMetadataProcessor#updateInstanceMetadata，是直接用新值全量覆盖旧值的。   

你说的使用运维元数据和运行时元数据结合的代码，应该是com.alibaba.nacos.naming.core.v2.index.ServiceStorage#parseInstance这段
‘’‘
private Instance parseInstance(Service service, InstancePublishInfo instanceInfo) {
        Instance result = InstanceUtil.parseToApiInstance(service, instanceInfo);
        result.getMetadata().clear();
        Optional<InstanceMetadata> metadata = metadataManager
                .getInstanceMetadata(service, instanceInfo.getMetadataId());
        metadata.ifPresent(instanceMetadata -> InstanceUtil.updateInstanceMetadata(result, instanceMetadata));
        return result;
    }
’‘’

**Comment by Bo-Qiu** [comment]
> > 老哥你的需求应该是 ”需要增量更新运维元数据，而不是直接覆盖“ 对吧？ 针对这个需求我确认下是否可以在新版本Sdk中提供一个增量更新运维元数据的接口
> 
> 是有这个需求，我看OpenAPI有更新、删除元数据的接口，不过client还没有； 这个需求我目前也可以用其他方法来实现，每次传全量元数据

可以的，通过sdk增量更新接口元数据的接口，我和社区讨论一下哇，如果可以，将会在下版本提供此功能。   
现在解决你的问题的话，通过每次传全量元数据确实能解决。

**Comment by wyjie0** [comment]
> > > > 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧
> > > 
> > > 
> > > 按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。
> > 
> > 
> > 更直观的现象是，maintainService调用两次updateInstance方法，第二次新增的元数据，会把第一次新增的元数据冲掉
> 
> 规则是如此的，每次调用运维接口更新的元数据 会覆盖历史的运维元数据。 直接使用当前传递的metadataMap 替换掉 历史的matadataMap，不是增量操作。
> 
> 代码如下： ‘’‘ public void updateInstanceMetadata(Service service, String metadataId, InstanceMetadata instanceMetadata) { if (!instanceMetadataMap.containsKey(service)) { instanceMetadataMap.putIfAbsent(service, new ConcurrentHashMap<>(INITIAL_CAPACITY)); } instanceMetadataMap.get(service).put(metadataId, instanceMetadata); } ’‘’

我确认了一下，这一步是拿的最新的运维元数据和更新的运维元数据做的合并；
com.alibaba.nacos.naming.core.v2.index.ServiceStorage#parseInstance到了这个方法里用的本次更新的运维元数据和运行时元数据合并

**Comment by Bo-Qiu** [comment]
> > > > > 我认为应该不是解决“无法通过updateInstance移除实例注册元数据”，而是解决“无法合并多次updateInstance更新的元数据”吧
> > > > 
> > > > 
> > > > 按照上面说的， 控制台更新元数据和client maintainService调用updateInstance更新元数据，都是更新的运维元数据，那么这两次的更改应该合并吧，但实际上是每次修改都是基于运行时元数据做的合并。
> > > 
> > > 
> > > 更直观的现象是，maintainService调用两次updateInstance方法，第二次新增的元数据，会把第一次新增的元数据冲掉
> > 
> > 
> > 规则是如此的，每次调用运维接口更新的元数据 会覆盖历史的运维元数据。 直接使用当前传递的metadataMap 替换掉 历史的matadataMap，不是增量操作。
> > 代码如下： ‘’‘ public void updateInstanceMetadata(Service service, String metadataId, InstanceMetadata instanceMetadata) { if (!instanceMetadataMap.containsKey(service)) { instanceMetadataMap.putIfAbsent(service, new ConcurrentHashMap<>(INITIAL_CAPACITY)); } instanceMetadataMap.get(service).put(metadataId, instanceMetadata); } ’‘’
> 
> 我确认了一下，这一步是拿的最新的运维元数据和更新的运维元数据做的合并； com.alibaba.nacos.naming.core.v2.index.ServiceStorage#parseInstance到了这个方法里用的本次更新的运维元数据和运行时元数据合并

你看的代码入口应该是这个com.alibaba.nacos.naming.controllers.InstanceController#batchUpdateInstanceMetadata哇，通过这个接口可以实现增量更新元数据的需求。 但是sdk和控制台并未调用此接口，你可通过curl进行调用来实现增量更新配置

**Comment by wyjie0** [comment]
> 看的代码入口应该是这个com.alibaba.nacos.naming.controllers.InstanceController#batchUpdateInstanceMetadata哇，通过这个接口可以实现增量更新元数据的需求。 但是sdk和控制台并未调用此接口，你可通过curl进行调用来实现增量更新配

是我debug的时候看错了。既然就是这样设计的，那我就用全量传的方式来实现我的功能了。感谢

**Comment by KomachiSion** [comment]
batchUpdateInstanceMetadata 这个接口是1.4版本由社区添加的beta接口， 公开到现在，很少有人反馈这个接口有关问题（估计并没有多少人使用），且官方开发者并不使用这个接口（也不推荐使用），因此稳定性无法保证，一直处于beta状态。

其次batch接口主要是解决update接口会全量覆盖1.x服务端的元数据（会导致大量元数据丢失）问题提供的方便接口，但是2.x中从升级上分离了运行时和运维时数据， 因此大多数用户其实直接用update接口进行单次就能满足需求（毕竟运维操作不会频繁变更）。

少量频繁的变更需求需要具体看场景而定，但是大多数都是个人的独立需求，没有太大的公共性，因此社区不太考虑这种特殊需求场景。建议有需要的还是按照全量内容值改动的方式操作，比较安全。
