### ISSUE TITLE
config-dump.log 日志文件记录大量日志信息

### ISSUE THREAD

**Issue by nierdayede** [alibaba/nacos#10912]
首先声明以下几点：
1、nacos-server 从1.4.3升级到2.2.3才出现这个问题，1.4.3没有该问题
2、nacos-server启动前仅修改了db及auth 相关配置，未做其它配置修改
3、是nacos-server记录的报错信息，而非集成到项目内的client部分
4、当前为windows系统，linux系统暂未升级，尚不确定是否会有同样的问题
5、其实就是 #10910 那个问题
6、或许是我没有表达清楚，但是请拜托别在没有弄清楚问题的情况下就直接标记label:status/invalid，我确定我能看懂错误信息的字面意思，我想知道根本原因。

具体部分错误日志（都是类似的）：
2023-08-02 00:00:00,014 ERROR [dump-exception] save disk error. com.xxx.xxx.service.xxx:::provider:data-xxx+dubbo, java.io.FileNotFoundException: D:\Program\nacos-2.2.3\data\config-data\dubbo\com.xxx.xxx.service.xxx:::provider:data-xxx (文件名、目录名或卷标语法不正确。)
2023-08-02 00:00:00,017 ERROR [dump-exception] save disk error. com.xxx.xxx.service.xxx:::provider:data-user+dubbo+test, java.io.FileNotFoundException: D:\Program\nacos-2.2.3\data\tenant-config-data\test\dubbo\com.xxx.xxx.service.xxx:::provider:data-user (文件名、目录名或卷标语法不正确。)

排查及分析过程：
经过源码排查发现报错信息是 com.alibaba.nacos.config.server.service.ConfigCacheService 内的某个方法抛出，在保存配置文件并缓存md5的过程中，未找到文件，并提示文件名、目录名或卷标语法不正确。

那么如果文件名、目录名或卷标语法不正确，是否意味着这个文件根本就没有创建成功，那从文件的路径 \data\config-data 和 \data\tenant-config-data 入手，可以找到 com.alibaba.nacos.config.server.service.dump.disk.ConfigRawDiskService.saveToDisk(String dataId, String group, String tenant, String content)，具体如下：

    /**
     * Save configuration information to disk.
     */
    public void saveToDisk(String dataId, String group, String tenant, String content) throws IOException {
        File targetFile = targetFile(dataId, group, tenant);
        FileUtils.writeStringToFile(targetFile, content, ENCODE_UTF8);
    }
    
    /**
     * Returns the path of the server cache file.
     */
    private static File targetFile(String dataId, String group, String tenant) {
        File file = null;
        if (StringUtils.isBlank(tenant)) {
            file = new File(EnvUtil.getNacosHome(), BASE_DIR);
        } else {
            file = new File(EnvUtil.getNacosHome(), TENANT_BASE_DIR);
            file = new File(file, tenant);
        }
        file = new File(file, group);
        file = new File(file, dataId);
        return file;
    }

根据实际生成的目录，结合targetFile方法，得出tenant=test，group=dubbo，dataId=com.xxx.xxx.service.xxx:::provider:data-xxx
windows系统文件或目录名称不能包含 ‘：’ 而dataId却包含了多个 ‘：’ ，且dataId非我主动指定，是nacos按自己的规则生成。
此时，已能确定是因为这个缓存的配置文件因为 dataId含有非法字符导致未创建成功，最终导致记录错误日志。

请问这个问题，应该如何避免，是要修改什么配置，还是我在某个地方做错了什么？
敬请指点，谢谢。

**Comment by KomachiSion** [comment]
1. nacos不会自己生成dataid， dataid均有用户指定。
2. 社区应该解决过这个问题， 你可以搜一下issue， 针对文件系统，对文件名和路径有encode逻辑，默认兼容旧版本格式应该是关闭的状态。
