### ISSUE TITLE
集群模式配置中心不同步

### ISSUE THREAD

**Issue by YenchangChan** [alibaba/nacos#10918]
nacos版本： 2.2.3
我期望跨数据中心部署nacos集群，每个中心使用不同的mysql，防止某一个中心挂了可以无缝切换到另一个中心。因此该中心不能只有一个mysql，因为mysql部署在哪个中心都不合适。我尝试过使用derby方式部署集群，但是失败，因此考虑使用每个节点一个mysql，部署成功。
集群部署架构如下：
![image](https://github.com/alibaba/nacos/assets/43897067/563435ee-6874-4a73-940c-bb8ce6ed2947)

集群状态：
![image](https://github.com/alibaba/nacos/assets/43897067/f9839b50-6def-4a66-8944-ea3d6cbda3b0)

目前遇到的问题：
服务中心可以生效，注册到任意节点，集群其他节点均能同步信息。
配置中心无法同步。我在node3上创建配置文件，但是在node1和node2上均没有同步：
node1：
![image](https://github.com/alibaba/nacos/assets/43897067/5109ff9b-b6be-4ecb-9a74-36b72df547d6)

node2：
![image](https://github.com/alibaba/nacos/assets/43897067/44cc94fa-2a65-47ef-bc8f-3606112cca29)

node3：
![image](https://github.com/alibaba/nacos/assets/43897067/8603c6e7-b9c1-4cb8-babe-212a8115609a)

在node1和node2上能看到日志如下：
config-dump.log
```
2023-08-07 09:45:18,593 INFO [dump-task] add task. groupKey=eoi+DEFAULT_GROUP, taskKey=eoi+DEFAULT_GROUP++false

2023-08-07 09:45:18,645 INFO [remove-ok] eoi+DEFAULT_GROUP not exist.

2023-08-07 09:47:40,573 INFO [dump-task] add task. groupKey=aaaaaaa+DEFAULT_GROUP, taskKey=aaaaaaa+DEFAULT_GROUP++false

2023-08-07 09:47:40,659 INFO [remove-ok] aaaaaaa+DEFAULT_GROUP not exist.

2023-08-07 09:47:43,460 INFO [dump-task] add task. groupKey=abc+test, taskKey=abc+test++false

2023-08-07 09:47:43,465 INFO [remove-ok] abc+test not exist.

2023-08-07 09:48:08,368 INFO [dump-task] add task. groupKey=111111111+DEFAULT_GROUP, taskKey=111111111+DEFAULT_GROUP++false

2023-08-07 09:48:08,384 INFO [remove-ok] 111111111+DEFAULT_GROUP not exist.

2023-08-07 09:48:22,396 INFO [dump-task] add task. groupKey=abc+test, taskKey=abc+test++false

2023-08-07 09:48:22,400 INFO [remove-ok] abc+test not exist.
```
config-trace.log:
```
2023-08-07 09:48:08,384|192.168.101.94|111111111|DEFAULT_GROUP|null|null|1691372888345|192.168.101.96|dump|remove-ok|39|0
2023-08-07 09:48:22,400|192.168.101.94|abc|test|null|null|1691372902385|192.168.101.96|dump|remove-ok|15|0
```

请问为什么配置中心不能在集群间同步？从日志看，其他节点应该是已经收到了配置，但是没有入库。
或者这种跨中心的集群还有没有什么比较好的方案？

**Comment by 985492783** [comment]
配置中心的一致性是靠数据库保证的，我理解上这种情况需要维护的是数据库的中心集群一致性，而不是中间件一致性

**Comment by YenchangChan** [comment]
那如果需要跨数据中心部署nacos集群，有什么成熟的技术方案吗？

**Comment by KomachiSion** [comment]
数据库主备库多数据中心部署 + nacos多数据中心部署

**Comment by YenchangChan** [comment]
MySQL MGR模式应该能满足我的要求。

**Comment by marksmansj** [comment]
> nacos版本： 2.2.3 我期望跨数据中心部署nacos集群，每个中心使用不同的mysql，防止某一个中心挂了可以无缝切换到另一个中心。因此该中心不能只有一个mysql，因为mysql部署在哪个中心都不合适。我尝试过使用derby方式部署集群，但是失败，因此考虑使用每个节点一个mysql，部署成功。 集群部署架构如下： ![image](https://private-user-images.githubusercontent.com/43897067/258678848-563435ee-6874-4a73-940c-bb8ce6ed2947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQ1OTcsIm5iZiI6MTcxNTI0NDI5NywicGF0aCI6Ii80Mzg5NzA2Ny8yNTg2Nzg4NDgtNTYzNDM1ZWUtNjg3NC00YTczLTk0MGMtYmI4Y2U2ZWQyOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzY2E5NzQyZDAxYWIyNmNmYTQzODRlZGZlODQ4MDM3M2MzOTk4ZDk1ZjhlNjY0ZTViMjE4MzlmOTIzZjkyNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XfbzeCHBwgA3UMnjNo-iWHkjxiOJSPLml9gdqZ2njto)
> 
> 集群状态： ![image](https://private-user-images.githubusercontent.com/43897067/258679765-f9839b50-6def-4a66-8944-ea3d6cbda3b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQ1OTcsIm5iZiI6MTcxNTI0NDI5NywicGF0aCI6Ii80Mzg5NzA2Ny8yNTg2Nzk3NjUtZjk4MzliNTAtNmRlZi00YTY2LTg5NDQtZWEzZDZjYmRhM2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YjIyYThkMGMyYTBhNDcxMDlhZTQ5M2JkOTdjNGUwNmQ1NTA2NzUxNDY4MWUzMTBmNmE3MmY3NmE1ZDhlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0vQjd6qRaXrCh0VK7BVzHig43yNKYlyeIUB9Dmm_qA4)
> 
> 目前遇到的问题： 服务中心可以生效，注册到任意节点，集群其他节点均能同步信息。 配置中心无法同步。我在node3上创建配置文件，但是在node1和node2上均没有同步： node1： ![image](https://private-user-images.githubusercontent.com/43897067/258679819-5109ff9b-b6be-4ecb-9a74-36b72df547d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQ1OTcsIm5iZiI6MTcxNTI0NDI5NywicGF0aCI6Ii80Mzg5NzA2Ny8yNTg2Nzk4MTktNTEwOWZmOWItYjZiZS00ZWNiLTlhNzQtMzZiNzJkZjU0N2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMmM3MGZkMTYxZWZmZDUzMzk5NGEzODVlMTQ5MjBjMDdkMGIzOWYzOGIwZWQwYjhmZjc5OWU3NGI2ZjEzYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dXrvlcM7iKkgea80Gq3HDk5q1U_9uLnMWuRHvuAcuA4)
> 
> node2： ![image](https://private-user-images.githubusercontent.com/43897067/258679912-44cc94fa-2a65-47ef-bc8f-3606112cca29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQ1OTcsIm5iZiI6MTcxNTI0NDI5NywicGF0aCI6Ii80Mzg5NzA2Ny8yNTg2Nzk5MTItNDRjYzk0ZmEtMmE2NS00N2VmLWJjOGYtMzYwNjExMmNjYTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMDRhNmYxM2FmYmQzODk3OWMwZjI1MjIxY2FjMmM1YzZmMGEzMGYzMWE4YTNiZmQ5ZjE1M2M2ZjMyMjUwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mt-wCbyqQy9J_gjSnlO3fLyjRDS2M--bZX57469KF9o)
> 
> node3： ![image](https://private-user-images.githubusercontent.com/43897067/258680487-8603c6e7-b9c1-4cb8-babe-212a8115609a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQ1OTcsIm5iZiI6MTcxNTI0NDI5NywicGF0aCI6Ii80Mzg5NzA2Ny8yNTg2ODA0ODctODYwM2M2ZTctYjljMS00Y2I4LWJhYmUtMjEyYTgxMTU2MDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4NDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjM2Q5YjZkNzU1ODA3NzM1ZjlhZDU5MzFjNWM0ZDk2MDU2MzhmY2YyMWI2ZmFkZDZmODkyNDQ0MjEzMWQ0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0OJ5IazBEhK82XPi0QaoUyfZSfOyz_vCAL5jgP0sHqU)
> 
> 在node1和node2上能看到日志如下： config-dump.log
> 
> ```
> 2023-08-07 09:45:18,593 INFO [dump-task] add task. groupKey=eoi+DEFAULT_GROUP, taskKey=eoi+DEFAULT_GROUP++false
> 
> 2023-08-07 09:45:18,645 INFO [remove-ok] eoi+DEFAULT_GROUP not exist.
> 
> 2023-08-07 09:47:40,573 INFO [dump-task] add task. groupKey=aaaaaaa+DEFAULT_GROUP, taskKey=aaaaaaa+DEFAULT_GROUP++false
> 
> 2023-08-07 09:47:40,659 INFO [remove-ok] aaaaaaa+DEFAULT_GROUP not exist.
> 
> 2023-08-07 09:47:43,460 INFO [dump-task] add task. groupKey=abc+test, taskKey=abc+test++false
> 
> 2023-08-07 09:47:43,465 INFO [remove-ok] abc+test not exist.
> 
> 2023-08-07 09:48:08,368 INFO [dump-task] add task. groupKey=111111111+DEFAULT_GROUP, taskKey=111111111+DEFAULT_GROUP++false
> 
> 2023-08-07 09:48:08,384 INFO [remove-ok] 111111111+DEFAULT_GROUP not exist.
> 
> 2023-08-07 09:48:22,396 INFO [dump-task] add task. groupKey=abc+test, taskKey=abc+test++false
> 
> 2023-08-07 09:48:22,400 INFO [remove-ok] abc+test not exist.
> ```
> 
> config-trace.log:
> 
> ```
> 2023-08-07 09:48:08,384|192.168.101.94|111111111|DEFAULT_GROUP|null|null|1691372888345|192.168.101.96|dump|remove-ok|39|0
> 2023-08-07 09:48:22,400|192.168.101.94|abc|test|null|null|1691372902385|192.168.101.96|dump|remove-ok|15|0
> ```
> 
> 请问为什么配置中心不能在集群间同步？从日志看，其他节点应该是已经收到了配置，但是没有入库。 或者这种跨中心的集群还有没有什么比较好的方案？

请问一下，多中心部署nacos找到解决方案了么？
