### ISSUE TITLE
Nacos 2.2.1 添加了@LoadBalanced注解无法通过服务名调用

### ISSUE THREAD

**Issue by HappyAxin** [alibaba/nacos#10915]
![image](https://github.com/alibaba/nacos/assets/46963688/aa5e180f-502c-4dff-81c7-3063778328cd)
![image](https://github.com/alibaba/nacos/assets/46963688/cad1a743-4100-4383-8068-8ddd81ff41ef)
![image](https://github.com/alibaba/nacos/assets/46963688/c4e587c4-b47a-4fb1-9be2-6e49b121d9b6)
![image](https://github.com/alibaba/nacos/assets/46963688/0f46b32b-204e-4a17-8e8c-d7ec1a7d0ff6)
![image](https://github.com/alibaba/nacos/assets/46963688/9986a452-8906-4e74-a894-ed8ba9e865c9)
![image](https://github.com/alibaba/nacos/assets/46963688/af9e44c7-2b08-43c7-8f76-1925e70f65ed)
报错信息
![image](https://github.com/alibaba/nacos/assets/46963688/a3c9c05e-9d77-4bbb-adfc-c9d56dbff2f7)

开发环境：jdk 17 ,springboot3, springcloud alibaba 2022.0.0.0

服务中心这两个服务都有
![image](https://github.com/alibaba/nacos/assets/46963688/299f1e99-f267-4406-bbc7-45fdad93419b)

**Comment by HappyAxin** [comment]
服务中心这两个服务都有
![image](https://github.com/alibaba/nacos/assets/46963688/e0ac0bb4-202e-44fe-9842-4a9b916431c9)

**Comment by chnaan** [comment]
这个注解需要有对应的LoadBalancerClient实现
![image](https://github.com/alibaba/nacos/assets/43342034/707bbf9c-3bdb-4aef-ba08-4803c8bbcc85)
你看下你的项目有这个bean不
![image](https://github.com/alibaba/nacos/assets/43342034/1d85e150-9de4-4381-bb35-12878ff4198c)

**Comment by HappyAxin** [comment]
> 这个注解需要有对应的LoadBalancerClient实现 ![image](https://user-images.githubusercontent.com/43342034/258384964-707bbf9c-3bdb-4aef-ba08-4803c8bbcc85.png) 你看下你的项目有这个bean不 ![image](https://user-images.githubusercontent.com/43342034/258385090-1d85e150-9de4-4381-bb35-12878ff4198c.png)

什么意思？是还要去实现LoadBalancerClient？

**Comment by chnaan** [comment]
ribbon有对应的实现

**Comment by HappyAxin** [comment]
> ribbon有对应的实现
那我就是直接用@LoadBalanced注解呀，怎么还要我去实现这个LoadBalancerClient？:\

**Comment by HappyAxin** [comment]
> ribbon有对应的实现

那我就是直接用@LoadBalanced注解啊，怎么还要去实现LoadBalancerClient接口？这不是循环调用么？

**Comment by imsuperman0920** [comment]
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-loadbalancer</artifactId>
</dependency>
```
这个 pom 有么？

**Comment by HappyAxin** [comment]
> ```
> <dependency>
>     <groupId>org.springframework.cloud</groupId>
>     <artifactId>spring-cloud-starter-loadbalancer</artifactId>
> </dependency>
> ```
> 
> 这个 pom 有么？

嗯嗯，就是加了这个就解决了，谢谢！

**Comment by imsuperman0920** [comment]
请问你的两个服务都是在一个 group 下的么？

**Comment by chnaan** [comment]
> > ribbon有对应的实现
> 
> 那我就是直接用`@LoadBalanced`注解啊，怎么还要去实现`LoadBalancerClient`接口？这不是循环调用么？

意思是说这个注解只是标识，具体的实现可以引用ribbon的，或者上边说的spring cloud loadbalance
