### ISSUE TITLE
Could not initialize Logback Nacos logging from classpath:nacos-logback.xml

### ISSUE THREAD

**Issue by 200645049** [alibaba/nacos#10924]
**Describe the bug**

This warning will be reported when the project starts: Could not initialize Logback Nacos logging from classpath:nacos-logback.xml
But when I put nacos-logback.xml in the project, this error will still be reported

项目启动的时候会报这个警告：Could not initialize Logback Nacos logging from classpath:nacos-logback.xml
但是当我在项目里面放入nacos-logback.xml以后，仍然会报这个错误

**Expected behavior**
...

**Actually behavior**
...

**How to Reproduce**

restart project

启动项目就会报错

**Desktop (please complete the following information):**

nacos client version: 2.2.3
spring-cloud-starter-alibaba-nacos-config version: 2022.0.0.0
spring-cloud-starter-alibaba-nacos-discovery version: 2022.0.0.0

**Additional context**
![image](https://github.com/alibaba/nacos/assets/48009199/b284a7ce-e159-48d5-8a8b-cfde56cd90df)
![image](https://github.com/alibaba/nacos/assets/48009199/c887019b-ba5c-487c-b5b4-9fb5a7a960d0)

**Comment by 200645049** [comment]
spring-cloud-dependencies: 2022.0.4
spring-boot-dependencies: 3.1.2

**Comment by KomachiSion** [comment]
duplicate with #10890
