### ISSUE TITLE
求助nacos客户端解密方案

### ISSUE THREAD

**Issue by YshGitHubfcasd** [alibaba/nacos#10928]
**本地环境配置的文件，有nacos的账号和密码加密的，有什么方案能在spring启动的时候就加个解密操作，导致时密文的nacos客户端一启动就报错**
尝试方案
1. spring扩展：实现EnvironmentPostProcessor接口将OriginTrackedMapPropertySource中的配置做解密，虽然这里成功了但是com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl#login方法中读取的还是未解密的值【失败】
2. spring扩展：实现ApplicationContextInitializer接口和上面一样的结果【失败】

_nacos远程的配置文件内容解密已解决_
1. jasypt【推荐】
2. 重写NacosConfigDataLoader【jvm类加载机制覆盖源码的类】
3. 听说有个spring的刷新事件可扩展，没尝试，应该也可实现解密

**Comment by KomachiSion** [comment]
1. nacos有提供加解密的自定义插件，可以开发自定义的加解密插件。
2. 如果不打算在nacos-client就进行解密， 那就和nacos没什么关系了，从工作流来看，当nacos-client返回了密文配置后，如何做解密操作是应用自己的事，应该到对应应用框架的社区进行讨论。
