### ISSUE TITLE
删除永久实例 提示 metadata is not present

### ISSUE THREAD

**Issue by linzhixiang** [alibaba/nacos#10927]
**Describe the bug**
当前版本是2.1.0 ，使用 v1/ns/instance 提示 read time out , 使用v2/ns/instance 删除提示 metadata is not present

**Comment by linzhixiang** [comment]
这个情况如何删除永久化实例呢，在不影响其他服务注册的情况下

**Comment by HappyAxin** [comment]
把服务停了，然后去`Nacos\nacos\data\protocol\raft`这个文件夹下删

**Comment by linzhixiang** [comment]
这种不过其他服务都要重新启动，不会自动注册。影响太大了

**Comment by HappyAxin** [comment]
看看这个https://blog.csdn.net/qq_43520746/article/details/132169804

**Comment by linzhixiang** [comment]
![image](https://github.com/alibaba/nacos/assets/20457072/dd3e03e0-e71d-42e7-ac8d-be2bb8dbb03c)
![image](https://github.com/alibaba/nacos/assets/20457072/c46bc693-bde3-424e-b69f-9b286d925118)

**Comment by linzhixiang** [comment]
![3](https://github.com/alibaba/nacos/assets/20457072/f0c60718-d7ee-4b5f-87e7-350d420317e1)

**Comment by Thakhun** [comment]
> 

> 

> 

>

**Comment by HappyAxin** [comment]
> ![3](https://user-images.githubusercontent.com/20457072/259343835-f0c60718-d7ee-4b5f-87e7-350d420317e1.png)

少了参数么？看下文档吧：https://nacos.io/zh-cn/docs/v2/guide/user/open-api.html#2.2

**Comment by linzhixiang** [comment]
![image](https://github.com/alibaba/nacos/assets/20457072/6ec34658-e16e-4829-ba1b-e76de702a31c)
没少，serverName,ip,port 三个必填的。奇怪的是2套环境，一套能成功，另一套就报错。

**Comment by KomachiSion** [comment]
那估计是另一套环境的部署有问题，或者代码有自行改动过。

我自己部署的最新版本测试是没问题的。

**Comment by linzhixiang** [comment]
那估计跟版本有关系，2.2.3是可以的，2.1.0注销报错。

**Comment by KomachiSion** [comment]
the version has solve the problem.
