### ISSUE TITLE
Nacos 2.2.1 com.alibaba.nacos.api.exception.NacosException: errCode: 400, errMsg: Current service DEFAULT_GROUP@@stock-service is persistent service, can't register ephemeral instance. 

### ISSUE THREAD

**Issue by HappyAxin** [alibaba/nacos#10920]
同一个服务中无法同时存在临时实例和非临时实例？
Can't have both temporary and non-temporary instances in the same service?
`com.alibaba.nacos.api.exception.NacosException: errCode: 400, errMsg: Current service DEFAULT_GROUP@@stock-service is persistent service, can't register ephemeral instance. `
![image](https://github.com/alibaba/nacos/assets/46963688/92832839-9f38-4169-8467-a5e7b44aeca9)
![image](https://github.com/alibaba/nacos/assets/46963688/ec5af624-399c-4e1b-911d-32e53c523742)

**Comment by ZhangShenao** [comment]
设计如此。 在2.x版本之后，持久化属性被提升到服务级别了，一个服务只能被定义成持久化或非持久化服务，服务下不能同时包含持久化和非持久化实例。

**Comment by HappyAxin** [comment]
> 

为啥这样设计？出于什么考虑？

**Comment by HappyAxin** [comment]
> 设计如此。 在2.x版本之后，持久化属性被提升到服务级别了，一个服务只能被定义成持久化或非持久化服务，服务下不能同时包含持久化和非持久化实例。

为什么这样子设计？出于什么考虑？

**Comment by ZhangShenao** [comment]
一个服务下同时存在临时实例和持久实例，这种情况在逻辑上讲是矛盾的，因为这两种实例的持久化和健康检查方式都不同，运维起来难度比较高，而且实际使用的场景也很少。
