### ISSUE TITLE
临时节点，服务端有主动探活机制吗？

### ISSUE THREAD

**Issue by flying-2077** [alibaba/nacos#10934]
背景
  公司目前用nacos的临时节点注册服务的，发现provider如果和nacos出现网络中断，服务会在nacos节点列表停留大概15min。

问题
   nacos服务端对于临时节点，支持服务端主动探活吗？ 检测到服务假死或者其他异常做节点下线处理

**Comment by KomachiSion** [comment]
目前没有

**Comment by openai8** [comment]
这个是做什么用的

**Comment by flying-2077** [comment]
> 

目前在测试节点异常时，nacos列表页的表现

**Comment by LiujunjieALiling** [comment]
> 背景 公司目前用nacos的临时节点注册服务的，发现provider如果和nacos出现网络中断，服务会在nacos节点列表停留大概15min。
> 
> 问题 nacos服务端对于临时节点，支持服务端主动探活吗？ 检测到服务假死或者其他异常做节点下线处理

有的啊，如果实例长时间不续约，会在注册中心保留15s，超过的话就会自动下线

**Comment by EddyChina** [comment]
> 我们的服务部署在腾讯云cvm，直接断电关机（虚拟机），用的dubbo，使用nacos临时节点，发现服务实例列表在控制台能保存15min，能问下这个是什么原因吗?

我最近也遇到这个问题了.  相关 issue https://github.com/alibaba/nacos/issues/10909.  我这里是一直无法下线, 除非重启 nacos.

**Comment by flying-2077** [comment]
@EddyChina 这个https://github.com/alibaba/nacos/pull/10509 已经merge到develop分支了

**Comment by KomachiSion** [comment]
> #10509

Fix by

**Comment by flying-2077** [comment]
@KomachiSion 这个https://github.com/alibaba/nacos/pull/10509  是否已经合并到主干分支，如果合并了，具体是哪个版本？2.x?

**Comment by EddyChina** [comment]
> @KomachiSion 这个#10509 是否已经合并到主干分支，如果合并了，具体是哪个版本？2.x?

同问
