### ISSUE TITLE
持久化实例，健康检查的频率有参数修改吗

### ISSUE THREAD

**Issue by hasaiki123** [alibaba/nacos#10932]
当我使用nacos客户端进行持久化实例注册后，在页面配置完http探测健康检查。比如我自己定义的/health接口
接口的逻辑会清晰打印每次访问的时间，我查阅资料，nacos server会每隔2000ms+5000ms内的随机时间进行健康探测。
实时上打印出来的时间也基本符合。

我想知道健康探测的时间可以自己定义频率吗？如果有，请问在哪里可以定义呢？

**Comment by JianweiWang** [comment]
目前Nacos支持在server端全局修改健康检查频率，具体可以查看方法：com.alibaba.nacos.naming.controllers.v2.OperatorControllerV2#updateSwitch
