### ISSUE TITLE
nacos 开启鉴权后 /nacos/v1/core/cluster/nodes 这个接口依然能访问，我如何访问不到

### ISSUE THREAD

**Issue by Friends8822** [alibaba/nacos#10933]

**Comment by Friends8822** [comment]
希望帮忙回答下，现在说是系统漏洞，把ip暴露出去了，我应该如何解决这个问题

**Comment by springcloud-boot** [comment]
如果你的客户端连接nacos 是通过局域网访问, 建议你把nacos的外网访问禁用掉即可. 这样就不会有这个风险了.;

nacos本身的代码 AuthFilter 有问题,  如果你开启了鉴权, 但是header里面没有传递:
nacos.core.auth.server.identity.key  配置的值的话, 他就会默认鉴权通过.

**Comment by springcloud-boot** [comment]
目前只有通过外部的方式,防火墙,白名单. 或者更改源码 
com.alibaba.nacos.core.auth.AuthFilter

**Comment by springcloud-boot** [comment]
或者把 NacosClusterController  这个类中用到的方法使用  @Secured  修饰也可以的

官方既然开放这个接口估计是,就是想让你在局域网内访问, 不要暴露外网

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/d34a4cc9-b39f-4472-85e5-0f6ed8cfeffc)

这个接口应该是有鉴权的， 不知道你使用的哪个版本。

或者你鉴权开启没有成功，实际上没有开启

**Comment by springcloud-boot** [comment]
那应该是版本问题了.  我用的版本来回答他的,这个的确是没有@Secured
![image](https://github.com/alibaba/nacos/assets/39367636/5416cb89-945e-41a7-90e8-b3f31b8b8d83)

**Comment by 985492783** [comment]
哪个版本的，develop分支里的我应该是修复了

**Comment by ymd-one** [comment]
2.2.2、2.2.3都有这个问题，这两天扫漏洞把这个问题扫出来了，改源码，挺好解决

**Comment by Friends8822** [comment]
我用的是nacos2.2.3版本的，目前是有这个问题

**Comment by Friends8822** [comment]
这个是我的配置文件
server.servlet.contextPath=/nacos
server.error.include-message=ALWAYS
server.port=8848
spring.datasource.platform=mysql

db.num=1
db.url.0=xxx
db.user=xxx
db.password=xxx

db.pool.config.connectionTimeout=30000
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=20
db.pool.config.minimumIdle=2
management.metrics.export.elastic.enabled=false

management.metrics.export.influx.enabled=false
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i

server.tomcat.basedir=file:.
nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/v1/console/server/**
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.caching.enabled=true
nacos.core.auth.enable.userAgentAuthWhite=false
nacos.core.auth.server.identity.key=hwariot
nacos.core.auth.server.identity.value=hwariot
nacos.core.auth.plugin.nacos.token.expire.seconds=18000
nacos.core.auth.plugin.nacos.token.secret.key=hwariotO3mAeJdzGrL6gzlBeHjMbrgCCM9uB5BWcN2f71Gs1v3s0DKKxc9ONTwnW9sV
nacos.inetutils.ignored-interfaces[0]=eth0

**Comment by Friends8822** [comment]
还有就是如果我修改gitbub上的源代码，修改后我怎么打包成二进制形式放到linux 下使用？

**Comment by laiyuner** [comment]
打包命令可以参考building文件，根目录下执行 mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by wangchun2008** [comment]
> 希望帮忙回答下，现在说是系统漏洞，把ip暴露出去了，我应该如何解决这个问题

请教一下，这个问题最后怎么解决了？
