### ISSUE TITLE
Alibaba Cloud EDAS uses nacos problem

### ISSUE THREAD

**Issue by mostcool** [alibaba/nacos#1094]
1、现在Nacos 1.0.0 是否已经兼容了ANS？
2、兼容的话，若本地使用Nacos做服务注册与发现，生产使用ANS做服务注册与发现，该如何配置？
3、假如测试环境和生产环境都在阿里云EDAS部署，使用Nacos做服务注册与发现，如何区分命名空间？

**Comment by pbting** [comment]
1. 云上 ANS 已经兼容了 Nacos 1.0.0
2. 你们需要通过 EDAS 来管理你们的应用，通过 EDAS 来管理你们的应用的话，不需要做任何配置，本地开发好就可可以直接通过 EDAS 来部署了
3. 你的意思是应用虽然被 EDAS托管了，但是注册中心想用自己搭建的 nacos 集群吗？

**Comment by mostcool** [comment]
> 1. 云上 ANS 已经兼容了 Nacos 1.0.0
> 2. 你们需要通过 EDAS 来管理你们的应用，通过 EDAS 来管理你们的应用的话，不需要做任何配置，本地开发好就可可以直接通过 EDAS 来部署了
> 3. 你的意思是应用虽然被 EDAS托管了，但是注册中心想用自己搭建的 nacos 集群吗？

3、不是你所说的意思。我们本地使用Nacos，但发布到EDAS时，还是全套使用EDAS产品，服务注册与发现仍然用ANS。此时如果EDAS有两套环境：测试环境和生产环境，如何隔离现个环境下的服务？

**Comment by mostcool** [comment]
> 1. 云上 ANS 已经兼容了 Nacos 1.0.0
> 2. 你们需要通过 EDAS 来管理你们的应用，通过 EDAS 来管理你们的应用的话，不需要做任何配置，本地开发好就可可以直接通过 EDAS 来部署了
> 3. 你的意思是应用虽然被 EDAS托管了，但是注册中心想用自己搭建的 nacos 集群吗？

2、只需要本地开发好，发布到EDAS不需要修改任何配置？spring.cloud.nacos.discovery.sever-addr和dubbo.registry.address都不需要配置吗？
3、不是你所说的意思。我们本地使用Nacos，但发布到EDAS时，还是全套使用EDAS产品，服务注册与发现仍然用ANS。此时如果EDAS有两套环境：测试环境和生产环境，如何隔离现个环境下的服务？

**Comment by pbting** [comment]
2、不需要改
3、你是想要了解 EDAS  本身如何区分自己是测试环境还是生产环境，还是想要了解如何在 EDAS 上，如何解决你们有两个不同的环境。如果是后者的话，你就建两个不同的 namespace，你们自己区分哪一个是你们的测试环境，哪一个是生产环境。要是前者的话，EDAS 对外部用户就只有哥正是可用的生产环境。

**Comment by jumkey** [comment]
@pbting
配置spring.cloud.nacos.discovery.sever-addr 部署到edas报错 是否还缺少什么配置
`com.alibaba.nacos.api.exception.NacosException: failed to req API:http://100.100.27.5:8848/nacos/v1/ns/instance/list. code:404 msg: <html><head><title>Apache Tomcat/7.0.59.463 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.59.463</h3></body></html>`

**Comment by pbting** [comment]
> @pbting
> 配置spring.cloud.nacos.discovery.sever-addr 部署到edas报错 是否还缺少什么配置
> `com.alibaba.nacos.api.exception.NacosException: failed to req API:http://100.100.27.5:8848/nacos/v1/ns/instance/list. code:404 msg: <html><head><title>Apache Tomcat/7.0.59.463 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.59.463</h3></body></html>`

目前青岛 region 支持，其他region 还在持续升级中。

**Comment by pbting** [comment]
截止到 2019-05-21 为止，所有 region 都已支持 nacos client 进行服务的注册于发现。
