### ISSUE TITLE
The logic of the com.alibaba.nacos.auth.config.AuthConfigs#validate method can be optimized.

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#10947]
**Describe the bug**

**Expected behavior**
When ‘nacos.core.auth.enable.userAgentAuthWhite’ is true, there is no need to verify ‘nacos.core.auth.plugin.nacos.token.secret.key’ and ‘nacos.core.auth.server.identity.value’.

**Actually behavior**
When ‘nacos.core.auth.enable.userAgentAuthWhite’ is true, the verification is still executed.

**Comment by KomachiSion** [comment]
No need.

The enabledUserAgent is only for upgrade from old version and change the identity info.

Community force users to config the identity info when open auth.
