### ISSUE TITLE
com.alibaba.nacos.config.server.service.repository.embedded.EmbeddedConfigInfoPersistServiceImpl#findConfigInfo(java.lang.String, java.lang.String, java.lang.String) has a bug.

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#10940]
**Describe the bug**
com.alibaba.nacos.config.server.service.repository.embedded.EmbeddedConfigInfoPersistServiceImpl#findConfigInfo(java.lang.String, java.lang.String, java.lang.String) has a bug.
'''java
public ConfigInfoWrapper findConfigInfo(final String dataId, final String group, final String tenant) {
        final String tenantTmp = StringUtils.isBlank(tenant) ? StringUtils.EMPTY : tenant;
        ConfigInfoMapper configInfoMapper = mapperManager.findMapper(dataSourceService.getDataSourceType(),
                TableConstant.CONFIG_INFO);
        final String sql = configInfoMapper.select(
                Arrays.asList("id", "data_id", "group_id", "tenant_id", "app_name", "content", "md5", "type",
                        "encrypted_data_key"), Arrays.asList("data_id", "group_id", "tenant_id"));
        final Object[] args = new Object[] {dataId, group, tenantTmp};
        return databaseOperate.queryOne(sql, args, CONFIG_INFO_WRAPPER_ROW_MAPPER);
        
    }
'''
The SQL statement did not query the 'gmt_modified' field, leading to a result where 'lastModifiedTs' is always 0.

When lastModifiedTs is 0, the method com.alibaba.nacos.config.server.service.ConfigCacheService#dumpWithMd5 cannot execute properly.
<img width="858" alt="image" src="https://github.com/alibaba/nacos/assets/46370663/cb9dd834-10c7-4585-9bb9-cd91237f31c3">

**Expected behavior**
The SQL statement should query the 'gmt_modified' field.

**Actually behavior**
The SQL statement did not query the 'gmt_modified' field.

**Comment by shiyiyue1102** [comment]
This is indeed a bug  when nacos running  in cluster mode and using derby database. it should be fixed

**Comment by Bo-Qiu** [comment]
> This is indeed a bug when nacos running in cluster mode and using derby database. it should be fixed

I fixed it and create a PR, please review it, thx!
