### ISSUE TITLE
Misleading "caused: no ips found for cluster DEFAULT in service DEFAULT_GROUP@@nacos.test.3;" is reported when running example CURL to register service

### ISSUE THREAD

**Issue by NickWong77** [alibaba/nacos#10949]
**Describe the bug**
Steps to reproduce
1. start nacos in standalone mode 
2. Use this example to register service: http://127.0.0.1:8848/nacos/v1/ns/instance?port=8848&healthy=true&ip=11.11.11.11&weight=1.0&serviceName=nacos.test.3&encoding=GBK&namespaceId=n1 (example from https://nacos.io/zh-cn/docs/open-api.html)

**Actually behavior**
Observed: Error is reported "caused: no ips found for cluster DEFAULT in service DEFAULT_GROUP@@nacos.test.3" 
Note: Even the actual service is not started,  the error should be more clear on this 1) service should be able to register 2) service down information could be mentioned in the error message.

**Expected behavior**
The service register should be successful or nacos reports register failure with reason. "caused: no ips found for cluster DEFAULT in service " should be improved to be more accurate and meaningful.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version [e.g. nacos-server 2,2,3]

**Additional context**
Use the node SDK API will result in same error reported.

**Comment by E1se2t** [comment]
This error occurs because there are no available IP addresses in the cluster of the xxx service，Are you sure there is? If the specified IP address 11.11.11.11 cannot be accessed on the network, Nacos will also not be able to find any available instances

**Comment by springcloud-boot** [comment]
Prompt question.
This problem beacause you can't have namespace 'n1';
If you remove the url param  namespaceId=n1, it can work success.

**Comment by NickWong77** [comment]
It does not work @KomachiSion @springcloud-boot . "caused: no ips found for cluster DEFAULT in service DEFAULT_GROUP@@nacos.test.3;" is still reported. Please reopen this.
