### ISSUE TITLE
nacos 2.1.0 error  code=403 msg= user not found!

### ISSUE THREAD

**Issue by wangzhiqiangzzz** [alibaba/nacos#10943]
question：Occasional error (403) and the configuration file cannot be obtained will occur when starting the project

1. nacos version 2.1.0 client JAVA SDK version 2.1.0
2. Bootstrap-sit.yml correctly configures username and password

**Comment by KomachiSion** [comment]
username is not existed or the password is not right.

**Comment by ruitongbi-eb** [comment]
I also encountered this problem. There is no problem when other services use username/password to register, but when the configuration center pulls the configuration file, this error is reported.

**Comment by ruitongbi-eb** [comment]
Oh!!! My problem is solved. It seems that it is a bootstrap version issue.

**Comment by KomachiSion** [comment]
Other services has no problem means nacos work well and should check the problem in that app, such as app contain multiple configuration and app read different config for each time.

Or try to upgrade the version of nacos and SCA to see whether the problem fixed.
