### ISSUE TITLE
反斜杠延续，Backslash (Line Continuation)，不支持？not support?

### ISSUE THREAD

**Issue by gMan1990** [alibaba/nacos#10957]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. edit a YAML context
2. use Backslash (Line Continuation)
3. click `save`
4. `配置信息可能有语法错误, 确定提交吗?`

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
应该是控制台前端使用的开源校验组件不支持，需要提交到对应的校验组件支持后，我们升级版本。

**Comment by KomachiSion** [comment]
实际上对使用应该不影响， nacos服务端不会解析yaml，都是以字符串形式保存和推送， 实际的解析是应用程序自行解析。

**Comment by gMan1990** [comment]
@KomachiSion hhh, 程序使用上有问题

```text
mybatis-plus1: aaa\
bbb

org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'reader', line 72, column 1:
    bbb
    ^
could not find expected ':'
```

**Comment by gMan1990** [comment]
可以了，要加引号

```text
: "aaa\
bbb"
```

就会得到 `mybatis-plus1=aaabbb`

**Comment by KomachiSion** [comment]
那这是程序自己解析的问题， nacos不会解析配置，需要应用自己解决

**Comment by gMan1990** [comment]
@KomachiSion 是的。然后就是编辑提交的校验，得升级下吧，`配置信息可能有语法错误, 确定提交吗?` `NACOS2.0.3`

**Comment by KomachiSion** [comment]
编辑提交那个需要看前端依赖的开源组件是否支持，如果那个组件本身不支持就没办法，要么换组件，要么提issue给组件，待其新版本支持后进行升级。

**Comment by gMan1990** [comment]
> 编辑提交那个需要看前端依赖的开源组件是否支持，如果那个组件本身不支持就没办法，要么换组件，要么提issue给组件，待其新版本支持后进行升级。

行的，你知道是哪个吗？你来提交下？
再提交1个，properties 里 配置0 length 字符，也会提示警告

```text
aaa=a
bbb=
ccc=c
```

**Comment by KomachiSion** [comment]
看社区有没有同学愿意接手这个需求，如果没有的话你可以考虑自己来。

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
