### ISSUE TITLE
求助服务名忽略大小写问题

### ISSUE THREAD

**Issue by 2021404** [alibaba/nacos#10962]
nacos：2.1.x
使用：在只用OpenFeign远程调用时，怎么样可以忽略@FeignClient中填写的服务名称与已经注册到nacos服务上的服务名称大小写问题

**Comment by KomachiSion** [comment]
nacos大小写敏感，FeignClient中填写的服务名需要与nacos中的一致。

**Comment by 2021404** [comment]
有没有什么方式可以解决这个问题？

**Comment by KomachiSion** [comment]
修改FeignClient中配置的服务名
