### ISSUE TITLE
Nacos registration center, I click offline service, but it will take some time to see the traffic stop

### ISSUE THREAD

**Issue by helei810304** [alibaba/nacos#1096]
nacos注册中心，我点击下线服务，但是要隔一段时间才会看到流量停止。

请问 服务调用刷新serverList 的机制是什么，是否有什么配置可以配置

**Comment by nkorange** [comment]
@helei810304 Spring Cloud还是Dubbo?Spring Cloud本身使用Ribbon是有延时的，需要修改Ribbon配置。Dubbo应该是立即生效的。

**Comment by ltylty** [comment]
> @helei810304 Spring Cloud还是Dubbo?Spring Cloud本身使用Ribbon是有延时的，需要修改Ribbon配置。Dubbo应该是立即生效的。

 Spring Cloud 的Ribbon配置怎么修改呢？有没有办法让服务下线的时候触发Ribbon缓存刷新？

**Comment by woshishitou** [comment]
> > @helei810304 Spring Cloud还是Dubbo?Spring Cloud本身使用Ribbon是有延时的，需要修改Ribbon配置。Dubbo应该是立即生效的。
> 
> Spring Cloud 的Ribbon配置怎么修改呢？有没有办法让服务下线的时候触发Ribbon缓存刷新？
> nacos可以通过调用接口的方式让服务下线吗？停服务之前调一个接口先从nacos下线也可以解决。

请问找到解决办法了吗？
