### ISSUE TITLE
[high-risk bug] gRpc reconnect will cause service offline after next register connection come in

### ISSUE THREAD

**Issue by ethenoscar2011** [alibaba/nacos#10975]
**Describe the bug**

**This is a preview of the test  architecture diagram.**

* **Nacos Version** : 2.1.1
* **GRPC Client Version**: 2.1.0
* We use hook to controller the service status (`online` or `offline`) by the http api: `/nacos/v1/ns/instance`

![image](https://github.com/alibaba/nacos/assets/8588117/5db110ef-5e3d-436b-8e47-bff5634fa173)

We should restart nginx as we install new modules on it , but terrifying event has occurred，service is auto change to offline, cause the 503 service unavailable !

![image](https://github.com/alibaba/nacos/assets/8588117/6fc402e7-d0d5-4c66-ba19-d497125de903)

**Expected behavior**

The grpc reconnect should not reset the status of the service instance !

**Actually behavior**

The grpc reconnect reset the online status to offline while the second reconnect occurred !

**How to Reproduce**

Preparing for the reproduce environment 
* 3 nginx docker containers : `nginx:latest` (it contains the stream modules)
* 3 nacos server for cluster mode
* 1 or 2 service instance use the discovery mode 

The nginx stream setting is like this (_this is only an example , you should change the `ip:port` as yours_)

```
stream {
	upstream devnacos_client {
	    server 10.4.51.133:18848;
	    server 10.4.51.133:18850;
	    server 10.4.51.133:18852;
	}
	server {
	    listen 8848 so_keepalive=20m::5;
	    proxy_pass devnacos_client;
	    proxy_connect_timeout 5s;
	    proxy_timeout 300s;
	}
	upstream devnacos_client_grpc {
	    server 10.4.51.133:19848;
	    server 10.4.51.133:19850;
	    server 10.4.51.133:19852;
	}
	server {
	    listen 9848 so_keepalive=20m::5;
	    proxy_pass devnacos_client_grpc;
	    proxy_connect_timeout 5s;
	    proxy_timeout 300s;
	}
}
```

The docker container create demo 
```
docker run --name nacos-test-01 -itd -p 8848:8848 -p 9848:9848 -v /data/tmp/nginx/nginx.conf:/etc/nginx/nginx.conf nginx
docker run --name nacos-test-02 -itd -p 8868:8848 -p 9868:9848 -v /data/tmp/nginx/nginx.conf:/etc/nginx/nginx.conf nginx
docker run --name nacos-test-03 -itd -p 8878:8848 -p 9878:9848 -v /data/tmp/nginx/nginx.conf:/etc/nginx/nginx.conf nginx
```

The client discovery settting should focus on this : 
```
      discovery:
        watch-delay: 1000
        enabled: true
        group: ${spring.profiles.active}
        # we use http to control the status , so this should be disabled
        instance-enabled: false 
        namespace: public
```

**Steps to reproduce the behavior:**

_To simplify the reproduction steps, I will use a single instance for verification._

1. Start the chatws service 8797
![image](https://github.com/alibaba/nacos/assets/8588117/1202c230-5a16-4c7b-8720-1af0b1038b6a)

2. Use the api or use the online button to make the instance online
![image](https://github.com/alibaba/nacos/assets/8588117/ba62e1b9-2595-4417-8b61-d3ee36a77cb3)

3. Check which nginx the grpc client is connect now , here I assum it is `nacos-test-01`, and I restart it by `docker restart nacos-test-01`
4. This is the first time the grpc reconnect , and you will find that : the instance status is right now 
![image](https://github.com/alibaba/nacos/assets/8588117/2cd23187-f4bc-4b31-a2dd-f50046ce37b8)

5. But if you wait for 1 minute and restart the nginx which the grpc client is connected now (assuming it is `nacos-test-02`), `docker restart nacos-test-02`, and after it reconnect again , you  will find this : the instance is offline
![image](https://github.com/alibaba/nacos/assets/8588117/b577a1a0-c06a-47f1-a87d-7e47ed841422)

The scenario described above is a simple reproduction. **However**, if there are two instances of "chatws" - 18797 and 8797, and let's say the production is currently being deployed. If instance 8797 had experienced gRPC reconnection before, the deployment process could cause 8797 to become offline while 18797 has not finished starting up yet. As a result, other clients that use service discovery to request the chatws interface will receive notifications from the Nacos server indicating that there are no available instance nodes, leading to a service error with a 503 status code.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version nacos-server 2.1.1, nacos-client 2.1.0 (_The latest version also has the same problem_)
 - Module `com/alibaba/nacos/naming/consistency`
 - SDK original

**Additional context**

I found that this may cause by the different logic in register instance and DistroClientDataProcessor::upgradeClient 

The logic in `com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java::registerInstance` has the clear expired InstanceMetadataEvent job 

![image](https://github.com/alibaba/nacos/assets/8588117/c8b4335f-796c-46a4-98b3-3d61f7a629f2)

While the `com/alibaba/nacos/naming/consistency/ephemeral/distro/v2/DistroClientDataProcessor.java::upgradeClient` not doing this after it receive the  client register event (_The comments is my tracing and fix idea_)
![image](https://github.com/alibaba/nacos/assets/8588117/64a720a1-cec3-4b20-af32-3f33d9017319)

**Comment by ethenoscar2011** [comment]
@KomachiSion 您看看我上面的场景，帮忙确定下，目前是稳定复现，生产节点也是被影响了很多，一旦有网络波动，基本会G

**Comment by 845146913** [comment]
在nacos.discovery.instance-enabled=false配置+nacos-client使用update接口上下线的情况下，我们也采用这种断开中间nginx网络，来模拟网络抖动的现象来复现了重连后服务被置为下线状态的问题；
我们的项目是在k8s下部署的，最终的解决方案是弃用instance-enabled=false+update的方式，改动手动register、deregister调用（如：k8s启用preStop、postStart钩子调用自定义restful接口保证流量）；
register/deregister关键步骤：
1，spring.cloud.nacos.discovery.register-enabled=false;
2，自定义restful接口(register/deregister)，核心调用：
`NacosServiceRegistry serviceRegistry = applicationContext.getBean(NacosServiceRegistry.class);
// 注册
serviceRegistry.register(applicationContext.getBean(NacosRegistration.class));
// 反注册
serviceRegistry.deregister(applicationContext.getBean(NacosRegistration.class));`
3，preStop、PostStart钩子调用自定义接口；

**Comment by ethenoscar2011** [comment]
> 在nacos.discovery.instance-enabled=false配置+nacos-client使用update接口上下线的情况下，我们也采用这种断开中间nginx网络，来模拟网络抖动的现象来复现了重连后服务被置为下线状态的问题； 我们的项目是在k8s下部署的，最终的解决方案是弃用instance-enabled=false+update的方式，改动手动register、deregister调用（如：k8s启用preStop、postStart钩子调用自定义restful接口保证流量）； register/deregister关键步骤：
> 
> 1. spring.cloud.nacos.discovery.register-enabled=false;
> 2. 自定义restful接口(register/deregister)，核心调用：
> 
> `NacosServiceRegistry serviceRegistry = applicationContext.getBean(NacosServiceRegistry.class);
> 
> // 注册 serviceRegistry.register(applicationContext.getBean(NacosRegistration.class));
> 
> // 反注册 serviceRegistry.deregister(applicationContext.getBean(NacosRegistration.class));`
> 
> 3. preStop、PostStart钩子调用自定义接口；
> 
> @ethenoscar2011 @KomachiSion

嗯 这种方式是比较保妥的
