### ISSUE TITLE
关于'No DataSource Set'错误提示的建议

### ISSUE THREAD

**Issue by blue-star-seeker** [alibaba/nacos#10977]
我使用nacos/nacos-server:latest镜像启动了nacos服务，并且按照dockerhub上的说明配置充分的参数，然而还是遇到了'No DataSource Set'，原因是需要先初始化数据库脚本。
建议：要么自动创建，或者网页上加个提示"请先自己启动数据库脚本"

**Comment by wilsonwu** [comment]
感谢您的建议，如果单纯使用nacos-server镜像是这样的，因为初始化数据库的操作是独立的，通过operator的方式就可以自动化进行。

如果您觉得网站中那个位置最适合加这个提示可以指出，我可以去添加相关内容。

**Comment by KomachiSion** [comment]
应该在dockerhub的启动说明和文档上添加内容。

**Comment by ZhangShenao** [comment]
docker hub 官方文档上应该已经有提示了：'If you use a custom database, you need to initialize the database script yourself for the first time.' 
https://hub.docker.com/r/nacos/nacos-server
