### ISSUE TITLE
Nacos 2.1.4版本，在权限控制菜单中增加了用户、角色后，在 "权限管理" 里增加了对某个命名空间 "动作" 为 "只读(r)" 的角色名有，用新增加的用户登录后，仍然可以删除对应的命名明见，且可以对命名空间的配置项进行修改和发布。

### ISSUE THREAD

**Issue by leo-pan** [alibaba/nacos#10974]
k8s 部署如何将这个改成nacos.core.auth.enabled 这个参数改成true呢？我尝试改过这个参数，NACOS_AUTH_CACHE_ENABLE  还是不生效。不知道这个参数是不是对应nacos.core.auth.enabled这个参数，我看配置文件没有这个参数

**Comment by KomachiSion** [comment]
1. 我印象中没有2.1.4版本， 如果是自己打的镜像，自行处理。
2. 文档和docker工程中都有参数说明，自行寻找说明
https://nacos.io/zh-cn/docs/v2/quickstart/quick-start-docker.html
https://github.com/nacos-group/nacos-docker
