### ISSUE TITLE
为什么springboot服务注册nacos后，serverAddr会发生变化

### ISSUE THREAD

**Issue by FlanceVoV** [alibaba/nacos#10985]
环境：
springboot 3.0.2
springcloud 2022.0.1
spring-cloud-alibaba-dependencies 2022.0.0.0
nacos: 2.2.2

配置：
![image](https://github.com/alibaba/nacos/assets/38349614/cc755749-db50-43eb-8b4b-b987d7d7e162)

问题：
![image](https://github.com/alibaba/nacos/assets/38349614/f2e18303-4e6c-470e-9799-39a136f1af82)
连接地址发生了变化，grpc连接地址使用的是本机局域网ip，没有使用nacos服务端ip

**Comment by KomachiSion** [comment]
Your input discovery address is 192.168.50.97.

The configuration maybe from your jar resources, your config in config center and so on. You should check your application, when and how change the address to 192.168.50.97. Because nacos not change it by client.
