### ISSUE TITLE
Abuse of Service Name

### ISSUE THREAD

**Issue by jifengnan** [alibaba/nacos#1098]
### Issue Description
Type: *feature request*

### Describe what feature you want

目前service name被到处引用，导致凡是和其相关的改动都极其难以实施，即使某人通过通读源码将所有相关地方都改到了，但很难保证后面的人添加新功能时不栽跟头。(Currently, service names are used directly in many places, which makes maintanance difficult.)

之所以提出这个问题，是因为我在试图实现 #883 的需求时，发现至少要改5个类的十几处代码才行，这让我一直在思考如何进行全面的测试而不敢提交代 码（单元测试远远不够）。(The reason I raise this is because when I tried to implement the requirement #883 , I found I had to change at  least a dozen codes in five classes, which kept me thinking about how to conduct comprehensive testing(unit test is far from enough))

### Describe what you expected to happen

凡是用到service name的地方都必须从service获取（service.getName）。(Wherever service name is used, it must be obtained from service)

**Comment by nkorange** [comment]
@jifengnan Can you show some example codes of abuse of service name in Nacos? That can help us understand the problem you address.

**Comment by jifengnan** [comment]
@nkorange 
比如说Instance和Cluster中都包含serviceName，如果支持大小写不敏感这个功能，这里的代码就必须改。
其他的还有KeyBuilder中的buildEphemeralInstanceListKey, buildPersistentInstanceListKey和matchServiceName方法。PushService中的serviceName属性，ServiceManager中的service Map和ServiceManager.ServiceKey的serviceName属性。

这五个类是我研究了很久代码之后最终得到的最小修改集合，依赖于五个类的方法那就更加海量了。

**Comment by nkorange** [comment]
使用 #1107 跟踪就行
