### ISSUE TITLE
2.2.1版本，SpringBoot应用比nacos启动快，连接几次连接不上就退出了，查看了源码，建议修改以下内容。

### ISSUE THREAD

**Issue by baiguoz** [alibaba/nacos#10983]
1，nacos注册的核心方法是 requestToServer
![image](https://github.com/alibaba/nacos/assets/26618272/34f5f99e-f9d8-4ce8-a2e7-8d7d38b1246d)
如图，这里有个一个 rpcClientConfig.retryTimes() ， 希望这里的startUpRetryTimes 可以配置，用户可以设置重连次数是最好的
重连3次根本不够用，在应用比nacos启动快的情况下，注册不上。

2，
![image](https://github.com/alibaba/nacos/assets/26618272/0c56a340-6e04-4f08-8884-61dd7232e9fb)

如图，如果1连接不上，2这里根本不会走到redoForInstances方法和redoForSubscribes 方法
建议将下面判断去掉，因为如果注册上了，对应方法循环就是空的，就没有问题，如果注册信息变更了，重新注册也没有什么问题
 if (!redoService.isConnected()) {
            LogUtils.NAMING_LOGGER.warn("Grpc Connection is disconnect, skip current redo task");
            return;
        }

**Comment by KomachiSion** [comment]
重连次数是无限的，你截图的代码只是单次重连的重试次数， 单次连接失败出去之后， 会有一个异步线程一直检查并发起重连。

你可以用一个简单的方式测试，写个main方法，只使用nacos-client， 然后写一个无效地址，在main方法最后写while死循环。 你会发现logs/nacos/remote.log中一直在尝试重连。

这里说连接几次连不上退出，应该是你应用自己的问题。可能某个请求异常之后抛出异常导致了程序的退出。

**Comment by baiguoz** [comment]
作为配置中心的时候重连是无限次数的，作为注册中心，试了好久，都不行

**Comment by baiguoz** [comment]
最简单的，你用Ruoyi的gateway，去掉 spring-cloud-starter-alibaba-nacos-config ，只剩下注册中心 spring-cloud-starter-alibaba-nacos-discovery 就会自动退出了

**Comment by cptjackwu** [comment]
我也遇到相同的问题，用docker去重启nacos和一个自己的服务，然后就一直注册不上去，一直报grpc connection is disconnect, skip current redo  task

**Comment by cptjackwu** [comment]
这是必现的问题，当服务先启动，它会尝试去重连nacos，然后过一会在去启动nacos，后面会重连上，但是在nacos上没有发现该服务注册上去。如果是正常启动nacos，然后再启动服务，这个时候服务正常注册上去，然后把nacos停掉，然后过会在重启nacos，这个时候服务是能重新注册上去的。

**Comment by KomachiSion** [comment]
我自测没有问题，
客户端版本2.2.1
服务端版本2.2.1

客户端先启动，注册一个服务实例
报错not Starting， naming.log限制grpc connection is disconnect, skip current redo task

随后启动服务端，服务端启动完成2s后，客户端停止报错，控制台能查看到该服务实例。

**Comment by KomachiSion** [comment]
测试直接使用的nacos-client，没有包gateway没有包spring boot。

同样 2.2.4 也测试了， 共测试了10次， 一次都没有复现。

**Comment by cptjackwu** [comment]
如果使用
  <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>


        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

      <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.2.3</version>
        </dependency>
这两个依赖，就会出现nacos注册中心上面没有该服务实例，我换了2.2.3的版本试了，还是一样的问题，docker启动的nacos-server，然后项目依赖那几个包，先启动项目，然后再启动nacos-server，这个时候抱错没有了，但是实例一直没有注册上去

**Comment by cptjackwu** [comment]
如果使用

<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.2.3</version>
        </dependency>
先启动服务实例，然后docker启动nacos-server-v2.2.3版本，最后服务不报错，但是服务没有注册到nacos上![image](https://github.com/alibaba/nacos/assets/24241502/f8802d32-d11e-450d-bd84-66a85c0421b6)![image](https://github.com/alibaba/nacos/assets/24241502/ce65824f-b666-4dc4-a4d4-b4ab01543d84)

**Comment by cptjackwu** [comment]
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>


<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>



<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>2.2.3</version>
</dependency>


如果项目中使用这样的依赖，更新到新的版本2.2.3的版本，试了下还是一样的问题，唯一的不同就是Grpc Connection is disconnect, skip current redo task
不在打印，但是nacos上面服务一直没有注册上去




在 2023-08-25 14:21:24，"杨翊 SionYang" ***@***.***> 写道：

测试直接使用的nacos-client，没有包gateway没有包spring boot。

同样 2.2.4 也测试了， 共测试了10次， 一次都没有复现。

**Comment by KomachiSion** [comment]
我是用SCA的example，先启动example再启动nacos server，进行测试，也没有问题。无法复现，总感觉是你们环境的问题，nacos server后启动就会一直连不上。

**Comment by baiguoz** [comment]
我发送一个网关的代码，不需要连接数据库，直接可以启动
现象1：只配置
<dependency&gt;
    <groupId&gt;com.alibaba.cloud</groupId&gt;
    <artifactId&gt;spring-cloud-starter-alibaba-nacos-discovery</artifactId&gt;
</dependency&gt;



不配置config，程序启动运行，nacos不启动的情况下重连几次之后程序就退出了，不会一直重连。如果不配置注册中心（spring-cloud-starter-alibaba-nacos-discovery），程序也不会自动退出。




现象2：同时配置了之后
<!-- SpringCloud Alibaba Nacos 注册中心--&gt;
<dependency&gt;
    <groupId&gt;com.alibaba.cloud</groupId&gt;
    <artifactId&gt;spring-cloud-starter-alibaba-nacos-discovery</artifactId&gt;
</dependency&gt;

<!-- SpringCloud Alibaba Nacos Config --&gt;
<dependency&gt;
    <groupId&gt;com.alibaba.cloud</groupId&gt;
    <artifactId&gt;spring-cloud-starter-alibaba-nacos-config</artifactId&gt;
</dependency&gt;

程序启动，nacos还没启动，注册中心尝试连接几次之后就不再连接了，注册中心的连接还一直在重试。nacos晚起动后，配置中心没有问题，注册依然没有注册上，nacos页面也没有显示。







***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月21日(星期一) 上午9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 2.2.1版本，SpringBoot应用比nacos启动快，连接几次连接不上就退出了，查看了源码，建议修改以下内容。 (Issue #10983)





 
重连次数是无限的，你截图的代码只是单次重连的重试次数， 单次连接失败出去之后， 会有一个异步线程一直检查并发起重连。
 
你可以用一个简单的方式测试，写个main方法，只使用nacos-client， 然后写一个无效地址，在main方法最后写while死循环。 你会发现logs/nacos/remote.log中一直在尝试重连。
 
这里说连接几次连不上退出，应该是你应用自己的问题。可能某个请求异常之后抛出异常导致了程序的退出。

**Comment by KomachiSion** [comment]
所以归根结底还是应用的问题。。  应用判断这里没有注册成功应该要退出，所以退出了。。 如果while 死循环硬等， nacos-client是没有问题的。

**Comment by baiguoz** [comment]
但是项目里面没有做任何关于nacos的判断哦，只是使用了&nbsp;
<dependency&gt;
	<groupId&gt;com.alibaba.cloud</groupId&gt;
	<artifactId&gt;spring-cloud-starter-alibaba-nacos-discovery</artifactId&gt;
</dependency&gt;

然后配置了ip ，账号和密码


你的建议是手动编码的方式引入&nbsp;nacos-client 去连接吗？
&nbsp;



***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2023年9月7日(星期四) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] 2.2.1版本，SpringBoot应用比nacos启动快，连接几次连接不上就退出了，查看了源码，建议修改以下内容。 (Issue #10983)





 
所以归根结底还是应用的问题。。  应用判断这里没有注册成功应该要退出，所以退出了。。 如果while 死循环硬等， nacos-client是没有问题的。

**Comment by KomachiSion** [comment]
那你应该提交这个问题到spring cloud alibaba社区， 因为注册发起测在spring cloud应用上，如果Spring cloud标准定义就是注册服务失败需要退出程序，那么就应该是这样的， 如果不是，可以提issue或pr到spring cloud alibaba社区优化此问题。
