### ISSUE TITLE
客户端下线失败

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#10989]
The nacos client uses 1.4.4   The server uses 2.0.2  

Question:
The API deregisterInstances provided by the client SDK is called successfully, but the instance is not offline.
Use the management page to click the offline button to log off successfully. 

View source code:
 The client SDK finally calls/nacos/v1/ns/instance   It uses del.    The service name is spliced    XXX@@XXX

View the server management page console, and call the offline button    /nacos/v1/ns/instance  使用put    服务名未做拼接

**Comment by KomachiSion** [comment]
You should use the client SDK which registerInstances to call `deregisterInstances`, otherwise your registerInstances SDK still maintain the heartbeat and connection, and will redo the registerInstances to server.

**Comment by MangerLe** [comment]
> You should use the client SDK which registerInstances to call `deregisterInstances`, otherwise your registerInstances SDK still maintain the heartbeat and connection, and will redo the registerInstances to server.

多谢大佬
