### ISSUE TITLE
nacos控制台修改运行时服务元数据消费者和生产者调用失败

### ISSUE THREAD

**Issue by zhangtong001** [alibaba/nacos#10987]
1.原有可以正常调用的dubbo服务的providers和consumers服务，经过在控制台修改实例中的group的k,v内容后，调用失败了（No provider available from registry）
期望：想要通过实时修改运行时服务实例的元数据，达到通过控制台或者api将运行中的服务集群，动态的分组目的。
问题背景：全链路压测数据和流量分流

**Comment by KomachiSion** [comment]
与nacos无关， 修改后可能是dubbo的路由规则过滤掉的对应provider，请提交到dubbo社区。

**Comment by zhangtong001** [comment]
好的，换了个其他方式解决了。
