### ISSUE TITLE
客户端和管理端页面的问题

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#10992]
1.  使用客户端SDK的删除实例API之后，为什么客户端查询实例依然可以查询到？
     但是使用管理端页面下线之后，使用客户端查询就查询不到了？
     客户端SDK删除实例和管理端页面下线的区别是什么？

2. CatalogController 里面的接口和客户端SDK的API区别是什么啊？

**Comment by KomachiSion** [comment]
1. 删除实例即注销实例，需要使用注册实例的SDK进行注销，否则连接和心跳在另外一个SDK依旧存在，会续约补偿回来。
2. 管理端的下线是管控操作，标记该实例为下线状态（但是实例依旧存在，未注销），标记为下线的实例消费端发现不了，很多时候用于无损下线或临时摘除流量排查问题等。
3. CatalogController是控制台的展示页面，会展示所有信息状态，用于运维操作。SDK的API是使用端数据，就比如标记下线的实例，控制台需要还能看到，但是消费端不应该看到。

**Comment by MangerLe** [comment]
> 1. 删除实例即注销实例，需要使用注册实例的SDK进行注销，否则连接和心跳在另外一个SDK依旧存在，会续约补偿回来。
> 2. 管理端的下线是管控操作，标记该实例为下线状态（但是实例依旧存在，未注销），标记为下线的实例消费端发现不了，很多时候用于无损下线或临时摘除流量排查问题等。
> 3. CatalogController是控制台的展示页面，会展示所有信息状态，用于运维操作。SDK的API是使用端数据，就比如标记下线的实例，控制台需要还能看到，但是消费端不应该看到。

明白了，多谢大佬
