### ISSUE TITLE
spring cloud  Could not find a parent resultmap with id  

### ISSUE THREAD

**Issue by yz8654773** [alibaba/nacos#10990]
使用本地数据库的配置是可以读取到mapper 能正常使用，修改成使用nacos配置中心后出现能正常加载配置，包括数据库初始化那些，就是在用的时候出现找不到map ， Could not find a parent resultmap with id 'com.artcloud.dao.user.mapper.AppVersionMapper.BaseResultMap'Exception异常={} ，

**Comment by yz8654773** [comment]
补充：
nacos服务器版本 2.2.3  
pom：        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>

**Comment by KomachiSion** [comment]
Not nacos‘ problem, nacos only push config to your app, the mapper is not nacos' responsibility, please check your app by yourself.

**Comment by yz8654773** [comment]
嗯嗯，找到问题了，开发没用过配置映射。现在好了
