### ISSUE TITLE
Still can get the instance after deregister the instance

### ISSUE THREAD

**Issue by jasonsuzhou** [alibaba/nacos#11]
While debug the nacos client, after I register the instance, there is one cache file generated in user's home folder like /home/jason/nacos/naming/default/com.mh.nacos010.helloWorldService.
Later I call the deregister method to deregister the instance, but I can still get the instance by the getAllInstances method, after check I found that the cached file not removed, so when execute getAllInstances  it will first get from local disk cache.
Is this feature designed like this?

**Comment by nkorange** [comment]
Yes, it's by design, but only when the service has one last instance. 
It's for preventing the client receive empty subscribe data and thus causing unknown behavior. 
If you want to remove the service regardless the number of instances, you have to use HTTP API '/nacos/v1/ns/api/remvDom?dom=$your_service'.

**Comment by jasonsuzhou** [comment]
Did you mean that if invoke deregister via java SDK will not actually remove the instance from nacos server when there is only one instance for the service?

**Comment by jasonsuzhou** [comment]
Did you mean that if invoke deregister via java SDK will not actually remove the instance from nacos server when there is only one instance for the service?

**Comment by jasonsuzhou** [comment]
Did you mean that if invoke deregister via java SDK will not actually remove the instance from nacos server when there is only one instance for the service?

**Comment by nkorange** [comment]
@jasonsuzhou Yes.

**Comment by jasonsuzhou** [comment]
thanks
