### ISSUE TITLE
2.2.0服务发现模块压测性能问题

### ISSUE THREAD

**Issue by HUWEIWEI0105** [alibaba/nacos#11003]
# 测试环境
- 服务端：8U/16GB，3节点，2.2.0
- 客户端：4U/8GB，5节点，2.2.0
- 在[官方](https://nacos.io/zh-cn/docs/v2/guide/admin/nacos2-naming-benchmark.html)启动参数中取消使用内置数据库，其余配置保持完全一致。

# 问题描述
在压测过程中发现几个问题想请教一下：
### 永久实例-注销接口
**现象：** 施压机5 * 线程数20，在压测永久实例注销接口时，服务数/实例数100w，前期注销接口运行正常，实例数不断降低，客户端服务端无报错，大约稳定运行10分钟后，客户端开始大量报错ErrCode:500, ErrMsg: failed to req API:/nacos/v1/ns/instance after all servers tried: org.apache.http.conn.ConnectionTimeoutException: Connect to xx:xx:xx:xx:xxxx failed: connect time out。从服务端监控看health check数量突然大量增加（从500K到4Mil），rt升高，吞吐量降低。
**问题：** 请问在什么情况下health check数会大量增加呢，查看客户端cpu、内存等无问题，有什么方法进一步排查是客户端还是服务端的问题吗？目前增加客户端资源压测过，以及永久实例/服务降低到50w压测，都存在相同的问题。相同情况下100w临时实例压测无问题。

### 临时实例-长连接测试
**现象：** 根据[官方性能测试报告](https://developer.aliyun.com/article/847432)，启动 一定数量施压机，每台施压机启动一定数量线程，每个线程一个客户端，每个客户端从服务池中随机选择 5 个服务进行注册，随后随机订阅 5 个服务池中的服务，随后对注册的实例进行变更（注销实例）。在服务端总长连接数量超过2000时，客户端就会出现大量报错ErrCode:-401, ErrMsg:Client not connected, current status:UNHEALTHY，同时大量push failed。
**问题：** 客户端和服务端指标和资源没有明显异常，CPU、内存都不高，从下表看，客户端单机并发能达到2000，使用5台施压机，单机600线程开始报错。看起来更像是服务端限制？
施压机数量 | 每台线程数 | 客户端总数 | 实际服务数/实例数 | 现象
-- | -- | -- | -- | -- |
1 | 200 | 200 | 1000 | 稳定运行
1 | 400 | 400 | 2000 | 稳定运行
1 | 600 | 600 | 3000 | 稳定运行
1 | 1000 | 1000 | 5000 | 稳定运行
1 | 2000 | 2000 | 10000 | 稳定运行
1 | 4000 | 4000 | 20000 | 客户端报错：ErrCode:-401, ErrMsg:Client not connected, current status:UNHEALTHY
5 | 200 | 1000 | 5000 | 稳定运行
5 | 400 | 2000 | 10000 | 稳定运行
5 | 600 | 3000 | 15000 | 客户端报错：ErrCode:-401, ErrMsg:Client not connected, current status:UNHEALTHY

**Comment by KomachiSion** [comment]
永久实例测试：健康检查会根据ip port拆分责任节点，由责任节点进行健康探测， 如果ip port过于聚集，会导致某一个节点探测压力过大。而且永久实例不需要一直调用接口续约， 只需要一次注册即可。

从长连接压测来看，8c的服务端，抗3k～4k连接量级应该很轻松，这里出现异常很可能是系统环境导致的， 可以看一下tcp的一些相关参数，以及文件句柄等一些参数，是否有限制。

**Comment by HUWEIWEI0105** [comment]
> 永久实例测试：健康检查会根据ip port拆分责任节点，由责任节点进行健康探测， 如果ip port过于聚集，会导致某一个节点探测压力过大。而且永久实例不需要一直调用接口续约， 只需要一次注册即可。
> 
> 从长连接压测来看，8c的服务端，抗3k～4k连接量级应该很轻松，这里出现异常很可能是系统环境导致的， 可以看一下tcp的一些相关参数，以及文件句柄等一些参数，是否有限制。

您好，第一个问题补充说明一下：测试环境是是100个客户端每个客户端注册100w个实例（每个实例只注册一次），然后随机注销实例，实例的ip和port都是随机生成的。前期注册和注销是稳定运行，health check一直保持在500k左右，但是运行一段时间后，注销接口客户端开始报错时，看到服务端的health check突然大量增加，客户端数量是一直保持100个，不知道health check增加和注销接口超时这些有关系吗？

**Comment by HUWEIWEI0105** [comment]
能问一下压测报告中网络带宽是多大吗？

**Comment by KomachiSion** [comment]
> > 永久实例测试：健康检查会根据ip port拆分责任节点，由责任节点进行健康探测， 如果ip port过于聚集，会导致某一个节点探测压力过大。而且永久实例不需要一直调用接口续约， 只需要一次注册即可。
> > 从长连接压测来看，8c的服务端，抗3k～4k连接量级应该很轻松，这里出现异常很可能是系统环境导致的， 可以看一下tcp的一些相关参数，以及文件句柄等一些参数，是否有限制。
> 
> 您好，第一个问题补充说明一下：测试环境是是100个客户端每个客户端注册10000个实例（每个实例只注册一次），然后随机注销实例，实例的ip和port都是随机生成的。前期注册和注销是稳定运行，health check一直保持在500k左右，但是运行一段时间后，注销接口客户端开始报错时，看到服务端的health check突然大量增加，客户端数量是一直保持100个，不知道health check增加和注销接口超时这些有关系吗？

不确定，可能是因为线程耗尽资源，或者连接资源耗尽导致的。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
