### ISSUE TITLE
Inconsistency in naming between CDS and Kubernetes services affecting XDS communication

### ISSUE THREAD

**Issue by PoisonGravity** [alibaba/nacos#11001]
Issue description:

I'm aiming to incorporate Istio-like functionalities within Nacos. The objective is to dynamically generate RDS, LDS protocols based on user input for VirtualService and DestinationRule. Given that Istio uses Kubernetes service names for its routing configurations and that these names are typically translated to Envoy's Cluster names, it becomes imperative that the names are consistent throughout.

Currently, the naming convention used in the developed EDS and CDS generators in Nacos does not align with the Kubernetes service names. Even if the Listener and Route configurations decipher the Kubernetes service names, and the EDS and CDS protocols have their unique naming conventions, there might be inconsistency issues. 

If the naming is not uniform, there could be routing mismatches or Envoy might not find the correct Endpoints for a Cluster.This discrepancy might lead to severe communication issues within the XDS protocols, resulting in Envoy being unable to locate the correct Cluster for routing.

To ensure seamless communication between Nacos and Envoy, it seems crucial to make the CDS naming consistent with Kubernetes service names. Are there any recommendations or best practices to address this inconsistency?

VirtualService Example:
<img width="547" alt="Screenshot 2023-08-22 at 03 16 15" src="https://github.com/alibaba/nacos/assets/107403926/bb1bbfd3-dc10-46c6-ac7b-0a31887a7da6">

DestinationRule Example:
<img width="458" alt="Screenshot 2023-08-22 at 03 16 24" src="https://github.com/alibaba/nacos/assets/107403926/a5e13794-226d-4a79-8833-a3d9a34209af">

Current naming convention used in CDS:
<img width="912" alt="Screenshot 2023-08-22 at 03 14 00" src="https://github.com/alibaba/nacos/assets/107403926/599c1c82-b799-4743-8cc6-3416f4c1f4d7">

**Comment by KomachiSion** [comment]
Is it for summer #10389？

**Comment by KomachiSion** [comment]
No more response from author, set duplicate
