### ISSUE TITLE
Spring cloud after booting

### ISSUE THREAD

**Issue by wenfer** [alibaba/nacos#1100]
nacos   1.0
spring-cloud-alibaba  0.2.2 release
服务启动后一直刷日志，如果服务多刷的也多。如果注册中心有服务被删除，即使是非健康状态，而且没有被订阅或使用，所有的服务都会报错提示该服务找不到

<img width="1038" alt="QQ20190424-144214@2x" src="https://user-images.githubusercontent.com/16834499/56637853-3b2aba80-669f-11e9-801e-dd1ccc4a7409.png">

**Comment by wenfer** [comment]
how to disable the log

**Comment by nkorange** [comment]
Set ```-Dcom.alibaba.nacos.naming.log.level=warn```
