### ISSUE TITLE
无法正常获取命名空间

### ISSUE THREAD

**Issue by freemankevin** [alibaba/nacos#11004]
![1692691129700_20719F74-0442-4137-A10A-11705E846CC1](https://github.com/alibaba/nacos/assets/71524776/8e0df995-746b-4419-baa0-3d4019dbc9a2)
![image](https://github.com/alibaba/nacos/assets/71524776/4c78bed2-affd-49f4-a072-1a3eebad03ff)

手动新建一个配置后，又能正常了：
![image](https://github.com/alibaba/nacos/assets/71524776/39ce0436-a6bd-4897-898e-59bb50a1b8c3)

**Comment by KomachiSion** [comment]
清理一下浏览器缓存再试试呢

**Comment by freemankevin** [comment]
时而有，时而无

**Comment by KomachiSion** [comment]
我再console.nacos.io中没有复现出来，  应该是你截图中没有选择namespace吧，我看选择的情况，ns的字体颜色是蓝色的

**Comment by IJiaPu** [comment]
> 时而有，时而无

我也没有复现出来，有没有更多细节

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.

**Comment by freemankevin** [comment]
啊，是这样子，我后面也没有遇到了...
