### ISSUE TITLE
when a node in the nacos cluster is down, the registered service will restart

### ISSUE THREAD

**Issue by xianhuadezhuren** [alibaba/nacos#11013]
The nacos deployed in the k8s cluster has three nodes. After one node is restarted, the entire cluster cannot be used, and the registered service will restart.

**Comment by KomachiSion** [comment]
The problem is not nacos' problem, your app restart is your apps' action.

And what's the default for the cluster can't be used ?

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
