### ISSUE TITLE
nacos-server 2.2.3 默认命令空间（public）下，自定义用户鉴权失败

### ISSUE THREAD

**Issue by zhjike0801** [alibaba/nacos#11011]
服务器版本： nacos-server 2.2.3
客户端版本： nacos-client 2.2.3
触发条件：
nacos-server开启权限认证，  客户端使用 默认命名空间public， 自定义用户，进行服务注册
报auth failed 错误

原因：
客户端代码  com.alibaba.nacos.client.naming.utils.InitUtils下  initNamespaceForNaming方法，当namespace为空时，会默认设置public

服务端代码 plugin-default-impl

com.alibaba.nacos.plugin.auth.impl.roles.NacosRoleServiceImpl 类里面hasPermission(NacosUser nacosUser, Permission permission)方法

public boolean hasPermission(NacosUser nacosUser, Permission permission) {
       .....
        
        // For other roles, use a pattern match to decide if pass or not.
        for (RoleInfo roleInfo : roleInfoList) {
            List<PermissionInfo> permissionInfoList = getPermissions(roleInfo.getRole());
            if (CollectionUtils.isEmpty(permissionInfoList)) {
                continue;
            }
            for (PermissionInfo permissionInfo : permissionInfoList) {
                String permissionResource = permissionInfo.getResource().replaceAll("\\*", ".*");
                String permissionAction = permissionInfo.getAction();
                if (permissionAction.contains(permission.getAction()) && Pattern.matches(permissionResource,
                        joinResource(permission.getResource()))) {
                    return true;
                }
            }
        }
        return false;
    }
	
	
	joinResource方法 未对public 做特殊处理，返回结果为public:DEFAULT_GROUP:naming/xxx-app
	permissionResource=:.*:.*
	Pattern.matches 匹配结果false
	
	
备注： 客户端 获取配置的时候 ，默认namespace不会设置成public , 会以""字符串传递，joinResource=:DEFAULT_GROUP:naming/xxx-app 匹配结果true

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/3525, current move to https://github.com/alibaba/nacos/issues/9846 discuss.
