### ISSUE TITLE
nacos2.x必现的bug，springboot服务比nacos先启动，这个时候springboot服务永远无法注册到nacos上

### ISSUE THREAD

**Issue by cptjackwu** [alibaba/nacos#11017]
这是必现的问题，当springboot服务先启动，它会尝试去重连nacos，然后过一会在去启动nacos，后面会重连上，但是在nacos上没有发现该服务注册上去。如果是正常启动nacos，然后再启动服务，这个时候服务正常注册上去，然后把nacos停掉，然后过会在重启nacos，这个时候服务是能重新注册上去的。
![1692933124731](https://github.com/alibaba/nacos/assets/24241502/2a1289a2-af67-4bfb-b5e3-92c7fd418905)

当重连成功的时候，NamingGrpcRedoService 这个类的onConnected()没有再去调用，RedoScheduledTask也没有再去执行
![image](https://github.com/alibaba/nacos/assets/24241502/cdc960c1-a9a6-4cfa-a901-671646a6f6b1)

**Comment by KomachiSion** [comment]
请升级版本后重试，老版本是需要注册成功才会执行redo， 新版本优化了逻辑。

**Comment by cptjackwu** [comment]
nacos-server 和nacos-client都要升级到最新版本吗？我试了将nacos-client升级到2.2.4，nacos-server还是2.0.4的版本，这种情况还是不行，没有注册上去

**Comment by cptjackwu** [comment]
我将nacos-server和nacos-client都升级到2.2.3的版本，还是不行，虽然不抱错，但是没有注册到nacos上面![EF5982BDE3D88F6D2D8ECEA1B3CD5849](https://github.com/alibaba/nacos/assets/24241502/8c4316ec-0750-4b29-9ce3-9fed367853f5)![image](https://github.com/alibaba/nacos/assets/24241502/dd6daab3-472f-4b82-babe-5bb510fefdef)

**Comment by cptjackwu** [comment]
现在只能把nacos先启动，然后再去启动服务实例

**Comment by KomachiSion** [comment]
那就是你应用的问题了， 我在#10983 中已经回复了，单纯使用nacos-client是没有任何问题的， 只能说明你应用在注册失败后，要么退出了，要么shutdown了nacos-client。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
