### ISSUE TITLE
搭建nacos 2.2.3集群并开启鉴权后启动失败

### ISSUE THREAD

**Issue by dbatool** [alibaba/nacos#11015]
我在搭建nacos 2.2.3集群并开启鉴权后启动失败（我已 iptables -F关闭了防火墙），nacos端口没有监听，请各位大神帮我看下是什么问题，谢谢。

##################################################################################################
#.报错信息如下：

[root@localhost ~]# cat /data/nacos_8848/logs/start.out | egrep "(Error|ERROR|errCode)"

2023-08-24 19:48:55,891 ERROR Startup errors : 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/data/nacos_8848/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.2.3.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; 

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
errCode: 500, errMsg: java.lang.NullPointerException 

##################################################################################################
#.如下是我的搭建过程

mkdir -p /data/
tar -zxf nacos-server-2.2.3.tar.gz -C /opt/
mv /opt/nacos /data/nacos_8848

touch /data/nacos_8848/conf/cluster.conf
chmod 755 /data/nacos_8848/conf/cluster.conf
cat > /data/nacos_8848/conf/cluster.conf <<EOF
10.30.3.231:8848
10.30.3.232:8848
10.30.3.233:8848
EOF

注：3台机器，我都修改了 /data/nacos_8848/conf/application.properties 如下几个参数：

nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.server.identity.key=example
nacos.core.auth.server.identity.value=example
nacos.core.auth.plugin.nacos.token.secret.key=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
nacos.core.auth.default.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789

#.如下是3台机器的启动命令
sh /data/nacos_8848/bin/startup.sh -p embedded

**Comment by KomachiSion** [comment]
看起来是创建embeddedDumpService的时候报错了， 能否提供更多日志信息？

**Comment by dbatool** [comment]
我把logs目录打包了，下载地址是：http://iso.sqlfans.cn/logs.zip，谢谢大神了。

**Comment by dbatool** [comment]
没有配置mysql导致的

**Comment by lihongjing-2023** [comment]
请问是否集群部署的情况下必须使用外置数据库呀，不能只使用内置数据库吗

**Comment by lihongjing-2023** [comment]
请问是否集群部署的情况下必须使用外置数据库呀，不能只使用内置数据库吗？
