### ISSUE TITLE
拓展配置和共享配置未加载

### ISSUE THREAD

**Issue by w1036460519** [alibaba/nacos#11018]
依赖
`plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.2'
    id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.wlj'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

ext {
    set('springCloudAlibabaVersion', "2022.0.0.0-RC2")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'cn.hutool:hutool-all:5.8.20'
    implementation 'com.alibaba:fastjson:2.0.35'
    implementation 'commons-codec:commons-codec:1.15'

    implementation 'org.projectlombok:lombok:1.18.28'
    annotationProcessor "org.projectlombok:lombok:1.18.28"

}

dependencyManagement {
    imports {
        mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:${springCloudAlibabaVersion}"
    }
}`

`spring:
  application:
    name: wang
  cloud:
    nacos:
      config:
        server-addr: 10.20.2.67:8848
        extension-configs:
          - data-id: lian
            refresh: true
          - data-id: jiang
            refresh: true
  config:
    import:
      - optional:nacos:${spring.application.name}
#      - optional:nacos:lian
#      - optional:nacos:jiang
server:
  port: 9001
`
extension-configs配置的属性没有处理，是不是springboot3以后需要什么别的配置才能引入加载拓展配置的类，还是extension-configs配置被淘汰了。

**Comment by KomachiSion** [comment]
not nacos' problem, plrase move to SCA community.
