### ISSUE TITLE
It seems that there might be a concurrency safety issue in the refresh method of ClusterRpcClientProxy.

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#11028]
**Describe the bug**

https://github.com/alibaba/nacos/blob/a2c6e7450062166731ba3b51cb2af3815a525c1d/core/src/main/java/com/alibaba/nacos/core/cluster/remote/ClusterRpcClientProxy.java#L86-L106

Regarding the refresh method, could there be a concurrency safety issue? 

If multiple threads enter the while code block simultaneously, it's possible that the first thread has already removed the RpcClient, and the second thread executes:

```java
RpcClientFactory.getClient(next1.getKey()).shutdown();
```

This could result in a NPE.

**Expected behavior**

I think it's important to have a null check when obtaining the RpcClient in this context.

**Actually behavior**

There are concurrency safety issues

**Comment by KomachiSion** [comment]
Good idea, you can submit pr and add the null check.

**Comment by stone-98** [comment]
Upon closer examination of the issue, I've noticed that other relevant removal operations are synchronous, as seen in:
https://github.com/alibaba/nacos/blob/2428a503e4f3791b68c5542571d74406766ecaff/client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java#L594-L626

https://github.com/alibaba/nacos/blob/2428a503e4f3791b68c5542571d74406766ecaff/client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java#L397-L406
It appears that the RpcClient#refresh method lacks the synchronization-related logic. Consequently, I believe it would be prudent to transfer this synchronization state into the RpcClientFactory, managing it internally. This approach aims to prevent the recurrence of such omissions in the future.

**Comment by stone-98** [comment]
@KomachiSion Do you find this approach feasible? If it appears viable, I'll submit a pull request to address this issue.
