### ISSUE TITLE
服务启动，不会连接配置中心

### ISSUE THREAD

**Issue by jiangjinggit** [alibaba/nacos#11029]
NACOS 版本 2.2.2

spring boot项目添加如下依赖：
<properties>
        <java.version>11</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>2.4.2</spring-boot.version>
        <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
</properties>

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

添加如下配置：bootstrap.properties

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
server.port=8080
spring.application.name=nacos-study
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
spring.cloud.nacos.config.namespace=dev

服务启动不会去连接nacos服务端，感觉nacos客户端没有启动，没有任何报错
![image](https://github.com/alibaba/nacos/assets/35126441/cd4b99c2-41cc-44fd-9b08-a9793a101abd)

我的问题：为什么引入了依赖：spring-cloud-starter-alibaba-nacos-config，不会自动注入nacos配置客户端，连接nacos服务，是因为客户端版本跟服务端版本不匹配导致的吗？

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/tree/master/nacos-spring-boot-samples/nacos-config-sample/src/main/java/com/alibaba/boot/nacos/sample

**Comment by jiangjinggit** [comment]
我看你们给的例子代码，依赖的版本都已经非常老旧了，都不支持用户名和密码连接

**Comment by jiangjinggit** [comment]
官方有交流群吗？我看官网给的叮叮交流群二维码已经失效了，交流群反馈会更加及时一点，麻烦给一下群链接，我这边的需求挺紧急的，感谢大佬！

**Comment by KomachiSion** [comment]
spring cloud问题请移步 spring cloud alibaba 社区。

**Comment by jiangjinggit** [comment]
官方有交流群吗？我看官网给的叮叮交流群二维码已经失效了，交流群反馈会更加及时一点，麻烦给一下群链接，我这边的需求挺紧急的，感谢大佬！

**Comment by jiangjinggit** [comment]
nacos官方交流群帮忙给一下，谢谢了

**Comment by IJiaPu** [comment]
> nacos官方交流群帮忙给一下，谢谢了
> 

Nacos官网底下有交流群

**Comment by KomachiSion** [comment]
你这个问题到nacos交流群可能意义不大， 建议去Spring cloud alibaba的社区repo 或者 找对应的技术交流群可能比较好。

另外nacos官网最新blog的群二维码应该是对的。
