### ISSUE TITLE
The server reported that the service not found is abnormal.

### ISSUE THREAD

**Issue by yfh0918** [alibaba/nacos#1103]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by yfh0918** [comment]
客户端和服务端都是1.0.0rc2 linux环境 错误信息 service not found : DEFAULT_GROUP@@

**Comment by nkorange** [comment]
异常服务名导致。
