### ISSUE TITLE
naming service: subscribe a service and get the changed instance aways not effect

### ISSUE THREAD

**Issue by lchpersonal** [alibaba/nacos#11034]
**Describe the bug**
use nacos client 2.2.0 and nacos server 2.2.0 , use batchRegisterInstances to register two intances of service B.
I am conducting frequent online and offline testing on Service B, and when Service A subscribes to Service B's status using NamingService.subscribe, I found that there is a probability that I will not receive any messages regarding changes in Service B

**Expected behavior**
Service B conducts frequent online and offline testing, receiving callback for every online or offline event

**Actually behavior**
Sometimes events can be received, sometimes they cannot be received, and there is no pattern

**Comment by KomachiSion** [comment]
see log `naming-push.log` in server and log `naming.log` in service A .

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
