### ISSUE TITLE
Some code review issues

### ISSUE THREAD

**Issue by IJiaPu** [alibaba/nacos#11035]
Type: Code Review
Code review, found some IDE prompts, such as:

Q1、Duplicate addressing & duplication
Before modification -> StringUtils.isBlank(ClassA.get(PropertiesB)) ? StringUtils.EMPTY : ClassA.get(PropertiesB);
After modification -> StringUtils.defaultEmptyIfBlank(ClassA.get(PropertiesB))

Q2、One more comparison
before -> Arrays.asList("single string")
after -> Collections.singletonList("single string")

Q3、One more thing
Relax......

**Comment by KomachiSion** [comment]
I comment in PR. Would you mind split more small PRs and link PRs.

**Comment by IJiaPu** [comment]
OK！tonight!
> I comment in PR. Would you mind split more small PRs and link PRs.

**Comment by IJiaPu** [comment]
相应会修改三个模块：config、core、common

该ISSUE分四个PR：
PR-1、Core模块，调整IDE提示的拼写、冗余拆箱、单个String构造List方法。【无运行影响】
PR-2、Common模块，添加StringUtils.defaultEmptyIfBlank()方法。【无运行影响，下一个PR的必要条件】
PR-3、Config模块，基于PR-2，将现有三元表达式冗余寻址方法替换掉。【合并PR-2后，该PR无运行影响】
PR-4、Config模块部分IDE提示消除。【无运行影响】

 @KomachiSion

**Comment by IJiaPu** [comment]
> I comment in PR. Would you mind split more small PRs and link PRs.

步子迈大了，我还是一个一个慢慢来吧！

**Comment by IJiaPu** [comment]
**As the figure shows，start with IDE......
e....**

这个多少有些赘述，我还是中文表达吧，我的中文比较好！

![image](https://github.com/alibaba/nacos/assets/110883801/cc1087b7-779b-4507-a24c-671f78e345a0)

如图所示，在使用IDE启动Nacos时候，接口“/announcement”返回空值。这里的提示语正常启动情况下为：
_当前集群没有开启鉴权，请参考<a href="https://nacos.io/zh-cn/docs/v2/guide/user/auth.html">文档</a>开启鉴权~_

由于IDE这种启动方式下，“nacos/conf“目录下并不会有“announcement.conf”文件。当然，**打包好的不会存在这种情况**。

所以，我的疑问有两个：
1、是否考虑在何种情况下，都正常提示（我可以理解，事实上开发人员提不提示这个无碍，只是一个统一的问题）
2、单机启动模式下也提示为”当前集群“是否合理？

如何解决反而我有些疑惑，我在这里说一下思路，希望杨哥予以指正：
1、继续保持提示语在单独的文件中，通过Class.getResource()判断路径中是否还有”jar!“，从而判断出是IDE还是打包好的jar启动，然后从不同的路径中获取该文件，但是由于该文件在另一个模块中，如此一来，显得更累赘。
2、提示语写在该接口所在的模块中，或是classpath中的.conf形式，或是.class的文件中定义直接拿字符串，但这样却又有些背离初衷，写死确实不合适，如果该文件涉及用户自定义提示语，就更不合适了！

所以我想知道杨哥在写这里的时候，是如何考量的？或者当时没有考量，那么现在了解后，假设作为一个需求，会如何考量？

@KomachiSion 

此刻脑子有点儿懵，语言组织不顺，但我想意思杨哥应该可以get到，我先去洗碗，等您回复！

**Comment by KomachiSion** [comment]
>1、是否考虑在何种情况下，都正常提示（我可以理解，事实上开发人员提不提示这个无碍，只是一个统一的问题）
>2、单机启动模式下也提示为”当前集群“是否合理？

其实都不是问题， 单例模式其实是集群的一种特殊情况，确定的单机且确定不会进行扩容的模式。

读文件的方式是给予部署的用户进行自定义扩展，或托管的云厂商能够自己做引导的扩展， 本地debug调试的时候，可以在${user.home}/nacos/conf 目录下复制一个文件过去，或者直接忽略。

**Comment by IJiaPu** [comment]
> >1、是否考虑在何种情况下，都正常提示（我可以理解，事实上开发人员提不提示这个无碍，只是一个统一的问题）
> 
> >2、单机启动模式下也提示为”当前集群“是否合理？
> 
> 
> 
> 其实都不是问题， 单例模式其实是集群的一种特殊情况，确定的单机且确定不会进行扩容的模式。
> 
> 
> 
> 读文件的方式是给予部署的用户进行自定义扩展，或托管的云厂商能够自己做引导的扩展， 本地debug调试的时候，可以在${user.home}/nacos/conf 目录下复制一个文件过去，或者直接忽略。

明白，感谢解惑，是我过于钻牛角了
