### ISSUE TITLE
Access control of resource in Nacos

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1105]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Access control is numerously required by the community, which is helpful to isolate the resources between different users in production environment.

### Describe what you expected to happen

Different users can be assigned different levels of access privileges for the resources in Nacos, such as service, configuration.

### Anything else we need to know?

Similar requests have been mentioned in #400, #505, #513, etc.

**Comment by xiaojun207** [comment]
我们公司的系统，分布于公网上的不同环境中，所以，注册配置中心，会暴露在公网环境。需要在服务注册和获取配置等方面，都需要增加权限认证校验。

**Comment by xiaolongyuan** [comment]
> 我们公司的系统，分布于公网上的不同环境中，所以，注册配置中心，会暴露在公网环境。需要在服务注册和获取配置等方面，都需要增加权限认证校验。
> 大概什么时候，nacos可以使用权限认证相关功能，谢谢

你这种情况还是上VPN吧  在公网也太危险了吧

**Comment by nkorange** [comment]
大家觉得授权的粒度到namespace是否就够了，是否需要到group或者dataId？

**Comment by MagakiReimu** [comment]
> 大家觉得授权的粒度到namespace是否就够了，是否需要到group或者dataId？

希望可以到group级别，namespace未使用的情况会比较多

**Comment by ordercard** [comment]
1.2.0(Mar 4th, 2020)  这个版本的为什么在我用nacos账号登录看不到权限管理这项
