### ISSUE TITLE
RpcClientTlsConfig.properties在获取 protocols 时代码  有bug

### ISSUE THREAD

**Issue by EddyChina** [alibaba/nacos#11059]
源代码里直接设置的是这个 key, 而不是 get(key)的 value 值. 
![image](https://github.com/alibaba/nacos/assets/25081163/73bdd18c-c1de-4de2-8e37-b2f79723249c)

![image](https://github.com/alibaba/nacos/assets/25081163/5eac7d62-65ed-4e50-9053-628a30f409a6)

**Comment by KomachiSion** [comment]
@EddyChina Welcome PR

**Comment by stone-98** [comment]
@i will solve it@
