### ISSUE TITLE
突然发现2.2.3版本控制台没有退出按钮

### ISSUE THREAD

**Issue by maguoliang888** [alibaba/nacos#11062]
**Describe the bug**
2.2.3版本控制台没有退出按钮，尝试清除cookie，也依旧有问题，无法跳转到登录页

**Expected behavior**
有退出按钮，可以退出控制台到登录页面

**Actually behavior**
有退出按钮，无法退出控制台到登录页面

**How to Reproduce**
2.2.3版本启动后，打开控制台并登录后，无法找到退出按钮

**Desktop (please complete the following information):**
 - OS: 版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎5/‎10
操作系统版本	22621.2215
体验	Windows Feature Experience Pack 1000.22662.1000.0

 - Version nacos-server 2.2.3

**Additional context**

![image](https://github.com/alibaba/nacos/assets/67767897/64ed11f9-8a8e-4a3a-bd6d-d30de53012f8)

**Comment by IJiaPu** [comment]
没有开启鉴权，就没有登陆。没有登陆，自然没有退出！
