### ISSUE TITLE
Nocosconfig is used together with eureka, sometimes the service is not registered on eureka

### ISSUE THREAD

**Issue by zsywangyi** [alibaba/nacos#1106]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 生产环境部署了一个nacos config实例，使用eureka注册中心
2. 出问题的项目线上部署了6个实例,springboota版本2.1.3.RELEASE，<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>，spring-cloud-alibaba-dependencies版版本0.9.0.RELEASE。
3. 问题：nacos配置中心修改配置后，服务自动先从eurka上踢掉，然后自动重新注册，6个实例不能全部注册进去eurka。
4.本地同一个项目6个实例，测试了几次，发布修改后的配置文件，大部分时间都能注册进eureka，个别情况不能全部注册进去。

**Comment by nkorange** [comment]
这是个Eureka的问题

**Comment by zsywangyi** [comment]
项目是线上一直运行着的项目，以前是没有问题的；只是这次加入nacos config，出现的问题，你确定是eureka的问题，不是nacos cofig的问题？？？？？？

**Comment by zsywangyi** [comment]
#增加以下配置，可解决
eureka:
  client:
    #allowedRatePerMinute = 60 * this.burstSize / this.replicationIntervalSeconds
    instance-info-replication-interval-seconds: 20
    healthcheck:
      enabled: true
