### ISSUE TITLE
Why Use HTTP for Registration of the Nacos2.0 Raft Protocol

### ISSUE THREAD

**Issue by chgang** [alibaba/nacos#11078]
Why Use HTTP for Registration of the Nacos2.0 Raft Protocol ?

**Comment by E1se2t** [comment]
在Nacos 2.0中，HTTP注册主要是为了解决Raft协议的集群内部通信和数据同步的问题

**Comment by KomachiSion** [comment]
The persistence service usage like DNS, maintainer ops it by controller but not client or sdk. So Http is better way to do it.

Also for remove useless codes in client, Future will support register persistent instance by client though grpc, but the http register persistent instance will be keeped.
