### ISSUE TITLE
关于raft反序列化漏洞后的推荐版本咨询

### ISSUE THREAD

**Issue by huanghuangzym** [alibaba/nacos#11075]
## Issue Description

Type: 问题咨询

官方目前主页推荐的nacos版本是2.1.1
但是现在有raft 反序列化漏洞

(https://blog.nsfocus.net/nacos-raft/)

受影响版本

4.0 <= Nacos < 1.4.6
0.0 <= Nacos < 2.2.3
不受影响版本

Nacos < 1.4.0
4.6 <= Nacos < 2.0.0
Nacos >= 2.2.3

那么请问社区，目前推荐的版本是多少？ 需要更换到大于2.2.3么？

**Comment by KomachiSion** [comment]
最好是升级到新版本， 做了网络访问拦截后，主要看还有哪些网断可以访问到这个端口。

如果只有nacos集群内的机器能访问到，那升级与否无所谓（因为攻击者能够攻击的时候已经在nacos集群机器内了，直接可以执行命令，不会再绕一下远程执行）。

如果还有办公网或其他非nacos节点服务器能访问，那最好还是升级一下，避免其他服务器被攻破后基于此扩大范围。

**Comment by huanghuangzym** [comment]
![image](https://github.com/alibaba/nacos/assets/15240576/b5db32c7-31c3-4a8d-8d73-6d44c6033a45)
我看官网推荐的还是2.1.1版本
我这里需要的是一个比较稳定的版本，我有两个问题
1  这个漏洞可以在2.1.1上修复么
2  如果不修复，官网当前的最佳推荐版本需要更新么？

**Comment by KomachiSion** [comment]
欢迎PR文档进行更新， 推荐版本为2.2.3

**Comment by huanghuangzym** [comment]
> 欢迎PR文档进行更新， 推荐版本为2.2.3

可以帮忙review下么? 
https://github.com/nacos-group/nacos-group.github.io/pull/379

**Comment by KomachiSion** [comment]
merged
