### ISSUE TITLE
nacos 是否可以专门划分一个模块去编写对应编写springboot的适配呢

### ISSUE THREAD

**Issue by dujie-js** [alibaba/nacos#11071]

**Comment by 985492783** [comment]
可以看下https://github.com/nacos-group/nacos-spring-boot-project

**Comment by 985492783** [comment]
可以看下https://github.com/nacos-group/nacos-spring-boot-project

**Comment by dujie-js** [comment]
> 可以看下https://github.com/nacos-group/nacos-spring-boot-project

这个感觉快一年没有维护了，还有后续维护计划吗

**Comment by 985492783** [comment]
有的后续有springboot3.0的支持，但是发版时间不确定，一年没维护的原因是nacos-client1.x->2.x的变动很大，客户端版本升上去之后2.x的客户端大部分能力和接口都是相同的，所以nacos-server版本更新就行了，客户端保持2.x理论上都能用
