### ISSUE TITLE
Nacos-Sync将数据从zookeeper迁移到Nacos的疑问

### ISSUE THREAD

**Issue by fsx379** [alibaba/nacos#11077]
请教个问题，使用Nacos-Sync将数据从zookeeper迁移到Nacos，在配置DemoService  服务的同步任务后，如何在Nacos中保活。
这个阶段，应用provider端还没有切换到Nacos上，所以没有心跳续约。
是Nacos-Sync 来模拟的？这个大概能支持多大的实例量？

**Comment by KomachiSion** [comment]
sync模拟心跳， 支持的量根据节点的规格而定。
