### ISSUE TITLE
使用k8s 集群  部署的nacos服务，2.03版本，当其中某台nacos A自动重启后，springboot应用无法自动注册到该nacos A，其他消费者也会报 No provider available from registry prod-nacos-0.prod-nacos.prod-middleware.svc.cluster.local,错误， 该需要手工重启springboot应用才行，有时需要多次手工重启应用才行，spring dubbo版本  2.7.8，nacos-client 版本，这个问题通过升级nacos版本到2.2.3版本能解决么

### ISSUE THREAD

**Issue by wangfei6633** [alibaba/nacos#11081]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by YunWZ** [comment]
你的Nacos server是StatefulSet吗? 如果不是,那么新启动的server节点, 需要从其他节点同步数据之后才可用.

**Comment by KomachiSion** [comment]
Bad issue template, all information in title but not in description.
