### ISSUE TITLE
Quick start document service discovery demo request error

### ISSUE THREAD

**Issue by Nicholas2015** [alibaba/nacos#1108]
## Issue Description
Service discovery request path is incorrect and requires the same parameter request as service registration.
Type: *bug report*

### Describe what happened (or what feature you want)
1.Service discovery request path does not exist
2.Request parameter missing

### Describe what you expected to happen
Modify the request in the Quick Start Document Service Discovery to be the correct request method
follows as:
curl -X GET 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'

### How to reproduce it (as minimally and precisely as possible)
1. Reproduce with the service discovery request in the Quick Start document

### Tell us your environment
windows10、jdk1.8、maven3.3、nacos1.0

**Comment by nkorange** [comment]
@Nicholas2015 Yes, you can query for a service only after you have registered it.
