### ISSUE TITLE
集群其中一个节点无法下线，其它节点正常

### ISSUE THREAD

**Issue by krisgh** [alibaba/nacos#11082]
Hi All,
我的集群有3个节点（A,B,C) , 目前再A点下线服务，B、C都能正常下线，但A点无效。
尝试再B、C下线服务，也只有A无效。

请问这是什么问题？看了所有日志，没有发现有关系的，请问有什么排查方向？

**Comment by seajelly** [comment]
我也遇到了相似的问题，请问您那边有进展吗

**Comment by IJiaPu** [comment]
可以描述详细点儿吗？具体的Nacos版本，使用什么方式部署的集群？采用什么途径进行的下线操作？

**Comment by IJiaPu** [comment]
最近的版本在web管理页面点击【下线】调用http请求的方式已经【暂停】使用了。

**Comment by IJiaPu** [comment]
https://github.com/alibaba/nacos/pull/8700

**Comment by IJiaPu** [comment]
上述是关于在Web端控制下线的，如果是采用其他方式下线，详细说明下过程

**Comment by krisgh** [comment]
@IJiaPu 多谢回复。
我是用的版本是NACOS2.1.2，操作方式就是在web页面点下线按钮。
在我处理问题过程中，因为同步的原因，重启服务时脱离了集群，在单点情况下A点下线功能又正常了。
我删除了raft目录，重启服务加入集群后，问题又出现了。

**Comment by KomachiSion** [comment]
如果是你说的服务是注册到nacos上的服务， 那么可能集群部署的问题， 查看BC节点中的集群信息， 看下A是否在BC节点中被识别为集群节点。以及他们的raft数据是否一致。
