### ISSUE TITLE
Research on open source Raft implementations and choose the most appropriate one to replace the current Nacos Raft implementation

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1109]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Introduce a new Raft implementation to Nacos.

### Describe what you expected to happen

1. Research on and compare different open source Raft implementations.
2. Select one implementation to analyze, optimize and test.
3. Replace the current Raft implementation in Nacos with the new one.

**Comment by Moriadry** [comment]
Have you consider a better raft implement by self, actually I believe translate from etcd/raft is a not bad choice.

**Comment by nkorange** [comment]
> Have you consider a better raft implement by self, actually I believe translate from etcd/raft is a not bad choice.

There are two reasons for why we want to introduce an existing library instead of writing a new one:
1. Many mature libraries are already available and abstracted enough to be used, so we don't have to recreate another one.
2. A new written Raft implementation is usually flawed and unstable.

**Comment by killme2008** [comment]
Hi, i am the [sofa-jraft](https://github.com/sofastack/sofa-jraft) maintainer. SOFAJRaft is a production-level, high-performance Java implementation opensourced by antfin , it is test well and have many useful features, and it is used in many production environment.

If you are interested, we can try to replace nacos current raft implementation by sofa-jraft, we can create a pull request.

**Comment by nkorange** [comment]
> Hi, i am the [sofa-jraft](https://github.com/sofastack/sofa-jraft) maintainer. SOFAJRaft is a production-level, high-performance Java implementation opensourced by antfin , it is test well and have many useful features, and it is used in many production environments.
> 
> If you are interested, we can try to replace nacos current raft implementation by sofa-jraft, we can create a pull request.

Thank you for your interest, we have a dingding group (23388803) discussing this work now. Please join it so we can discuss in more details.
