### ISSUE TITLE
升级nacos2.2.3后，漏洞扫描依旧显示存在身份认证绕过漏洞

### ISSUE THREAD

**Issue by alargewhale** [alibaba/nacos#11090]
problem：
Spring Security是一个能够为基于Spring的企业应用系统提供声明式的安全访问控制解决方案的安全框架。
Spring Security存在使用未前缀的双通配符模式造成 WebFlux 安全绕过漏洞，在WebFlux的Spring Security配置中使用“**”作为模式，会导致Spring Security和Spring WebFlux之间模式不匹配，并可能造成安全绕过。

版本比对检测原理：检查当前系统中spring-security-config版本是否在漏洞版本范围内|版本比对检测结果：- spring-security-config
  当前安装版本：5.7.9
  应用相关信息：
  - 进程PID：2110722
  - SpringBoot项目包路径：/app/nacos-server-2.2.3/target/nacos-server.jar
  - SpringBoot子包名称：spring-security-config-5.7.9.jar
该主机存在此漏洞

描述：公司linux服务器上nacos的版本是2.2.3，根据github上开发者曾经的回复已经解决了这个问题，但最新版本依旧存在此问题。2023.9.4

**Comment by KomachiSion** [comment]
我印象中spring版本的升级是在2.3.0做的（还没有发版）最新的spring boot版本是2.7.15，对应的spring-security-config 是5.7.10。

不过这个机制nacos中并未使用， 应该不受影响， 包扫描只能说你依赖了这个版本有风险， 不是说一定存在这个问题。

**Comment by alargewhale** [comment]
非常感谢你的回复，我明白了
