### ISSUE TITLE
nacos在K8s上部署有跨K8S集群的方案吗？即在在两个K8S集群上部署nacos组成一个nacos集群。

### ISSUE THREAD

**Issue by nokic** [alibaba/nacos#11092]
nacos在K8s上部署有跨K8S集群的方案吗？即在在两个K8S集群上部署nacos组成一个nacos集群。

**Comment by KomachiSion** [comment]
只要网络能通，ip/域名能感知即可，其实和nacos无关，主要在于你怎么跨k8s打通网络和ip
