### ISSUE TITLE
centos7.9+nacos2.2.3+mysql8

### ISSUE THREAD

**Issue by wzg0120** [alibaba/nacos#11097]
**Describe the bug**
nacos2.2.3，使用mysql8 执行sql，启动服务后，无法登录，response：user not found!
从mysql processlist可以看到 已经连接到数据库了

nacos2.2.3, executing sql using mysql8, failed to log in after starting the service, response: user not found!
You can see from the mysql processlist that you have connected to the database

**Desktop**
 - OS: centos7.9
 - Version nacos-server 2.2.3

**Comment by IJiaPu** [comment]
是否有导入新版的SQL脚本？

**Comment by wzg0120** [comment]
已解决
[文档 ](https://nacos.io/zh-cn/docs/v2/guide/admin/console-guide.html)
登录管理
