### ISSUE TITLE
Nacos监听频繁报错

### ISSUE THREAD

**Issue by ywx-stack** [alibaba/nacos#11095]
我使用openAPI（版本为1.x）实现了一个Nacos服务监控的功能；
具体实现步骤：
启动一个定时任务，每分钟运行一次：运行的内容如下2步
1.先使用“查询服务列表”接口(/nacos/v1/ns/service/list)，获取服务列表；
2.再使用“查询服务下的实例列表”接口（/nacos/v1/ns/instance/list）,获取该服务的实例，如果实例列表hosts为空，则认为服务丢失，发送报警。

但在具体的运行过程中，经常会出现 先报警 ，报警后一分钟又恢复。

不知是什么地方出现了问题~

**Comment by YunWZ** [comment]
Talk is cheap, ...

**Comment by ywx-stack** [comment]
> Talk is cheap, ...

不好意思，代码还有一些其它逻辑比较混乱，主要就是下面这个
![image](https://github.com/alibaba/nacos/assets/59912014/5678d829-d938-465b-810c-d0d059239bcd)

![image](https://github.com/alibaba/nacos/assets/59912014/584b6d5f-c82d-42ae-afe3-3352cb37de18)

**Comment by KomachiSion** [comment]
听描述大概率是provider掉线了

**Comment by ywx-stack** [comment]
> 听描述大概率是provider掉线了

那有建议的解决方式吗？ 目前我的一个思路是在出现异常的时候，重复check两次，不知是不是会减少误报的概率。

**Comment by KomachiSion** [comment]
自查provider问题， 是否是压力过大，或者网络问题，导致连接断开了或心跳发送失败了。

**Comment by ywx-stack** [comment]
> 自查provider问题， 是否是压力过大，或者网络问题，导致连接断开了或心跳发送失败了。

多个provider都出现了这个问题，并非某个provider持续报错。并且尝试了发现丢失实例后，延期3s，重复check2次，还是会频繁误报。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
