### ISSUE TITLE
不知道服务名的情况下，如何监听服务的上下线

### ISSUE THREAD

**Issue by frankywen** [alibaba/nacos#11098]
如题
在不知道服务名的情况下，如何监听所有服务的上下线？
* com.alibaba.nacos:nacos-client:2.2.0
* com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2021.0.5.0
* com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2021.0.5.0
* 未使用spring-cloud-gateway

**Comment by 985492783** [comment]
可以通过运维接口获取所有服务，自己在本地维护上下线变化

**Comment by frankywen** [comment]
> 可以通过运维接口获取所有服务，自己在本地维护上下线变化

目前是这样做的，没有现成的接口？

**Comment by KomachiSion** [comment]
什么场景需要？  一般来说只有网关应用可能需要监听所有服务的增减。 这个会在Nacos3.0通过模糊订阅完成。

**Comment by KomachiSion** [comment]
#10380

**Comment by frankywen** [comment]
> 什么场景需要？ 一般来说只有网关应用可能需要监听所有服务的增减。 这个会在Nacos3.0通过模糊订阅完成。

是的，就是在网关服务上需要使用到。

**Comment by KomachiSion** [comment]
> > 什么场景需要？ 一般来说只有网关应用可能需要监听所有服务的增减。 这个会在Nacos3.0通过模糊订阅完成。
> 
> 是的，就是在网关服务上需要使用到。

网关应用目前就是定时查询service列表， 自行决定是否订阅该列表中的服务。

**Comment by KomachiSion** [comment]
> 我这有个场景： 就是对于一个服务A和服务B，服务B上线下线的时候，服务A监听到此事件，然后更新A里的某些状态并做特殊处理。服务B可用的时候，服务A可以调用服务B的功能，不可用的时候，服务A的部分功能受限。

你这个需求，是监听服务实例列表，不是监听服务列表。 监听服务实例列表一直都有

**Comment by KomachiSion** [comment]
Issue can be merged to opss
