### ISSUE TITLE
启动应用报错，没有找到 Class InstantiationAwareBeanPostProcessorAdapter

### ISSUE THREAD

**Issue by Leard-K** [alibaba/nacos#11096]
**Describe the bug**
springboot3.1.3
Dubbo3.2.5，注册中心使用 nacos
JDK20
为了使用nacos当配置中心
引用 nacos-config-spring-boot-starter 后，启动应用后报错提示：没有找到 Class InstantiationAwareBeanPostProcessorAdapter

**Comment by KomachiSion** [comment]
duplicate with #10375
