### ISSUE TITLE
nacos-client在使用logback时默认开启packagingData会触发logbcak未修复的缺陷（Blocked when many exceptions happen）

### ISSUE THREAD

**Issue by ice-wuu** [alibaba/nacos#11093]
nacos-client中配置nacos-logback.xml
<configuration debug="false" scan="false"  packagingData="true">
logback缺陷描述：
https://jira.qos.ch/browse/LOGBACK-1697
https://github.com/qos-ch/logback/pull/598

**Comment by KomachiSion** [comment]
可以测试一下，关掉的话日志文件会大多少，如果差异不大的话可以默认关掉。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and community no body response this issue, which means this problem is not need to fix
