### ISSUE TITLE
配置列表选择后，重新搜索，非结果中的项未删除

### ISSUE THREAD

**Issue by eduosi** [alibaba/nacos#11104]
**Describe the bug**

配置列表中，第一次搜索，对搜索结果全选后，再次搜索，点击“克隆”，还存在第一次搜索时选中的但不再第二次搜索结果中的项。

**Expected behavior**
应清除不在第二次搜索结果中的数据。

**Actually behavior**
包含了第一次搜索结果中选择的数据，但这些数据不在第二次搜索结果中。

**How to Reproduce**
1. 使用关键词 'admin' 进行搜索：得到以下结果
![1057050623](https://github.com/alibaba/nacos/assets/1698316/111595a0-fc78-4c99-ab84-fbb9f90ecca6)

2. 点击 '全选'
3. 点击 '克隆'
![4130730959](https://github.com/alibaba/nacos/assets/1698316/41ad3e1f-3823-465a-b1b5-92dae636c93f)

4. 使用关键词 'admin-web' 进行搜索：得到以下结果
![693815882](https://github.com/alibaba/nacos/assets/1698316/d89d7728-ebc7-4f81-9024-89e228605077)

5. 点击 '克隆'
![350173245](https://github.com/alibaba/nacos/assets/1698316/b10d0ac8-f5ce-4200-b399-57f9728e30ea)

**Desktop (please complete the following information):**
 - OS: [MacOS 13.5]
 - Version [nacos-server 2.1.0]
 - Module [配置管理 => 配置列表]

**Additional context**

**Comment by KomachiSion** [comment]
我印象中是有人提了需求，说要多次添加搜索结果。

如果你需要重制的话， 应该刷新下页面即可。

**Comment by KomachiSion** [comment]
No more response from author, it seems community not interesting this issue.
