### ISSUE TITLE
springboot+netty注入到nacos中spring cloud gateway 如可配置

### ISSUE THREAD

**Issue by renguoqing123** [alibaba/nacos#11108]
客户端和服务端是通过TCP长连接进行请求的，目前我服务端使用的通信框架是spring boot+netty，然后也是注入到了nacos中，请问如果我进行TCP通信（只能ip和端口）,spring cloud gateway这边我应该怎么配置呢？

**Comment by KomachiSion** [comment]
请移步到Spring cloud社区，如果你使用的是SCA， 请提交issue至SCA社区。
