### ISSUE TITLE
springcloud整合nacos拉取配置失败

### ISSUE THREAD

**Issue by jiangyy7** [alibaba/nacos#11103]
在nacos中配置属性，在配置文件中通过三个横杆隔开(---),项目启动无法获取配置属性。由于在拉取配置的时候三个横杆隔开会被分隔两个文档，导致spring在绑定属性的时候根据属性名获取属性值为空。
![截屏2023-09-08 10 56 58](https://github.com/alibaba/nacos/assets/143685573/b038a6dc-c566-46f7-b3dd-d823a4428dc5)
<img width="786" alt="截屏2023-09-08 10 53 08" src="https://github.com/alibaba/nacos/assets/143685573/999abbc8-a7b8-4c52-a679-b360da4932bc">
截图是获取属性的方法，当没有三个横杆隔开的时候属性值是平铺的这样就能获取

**Comment by KomachiSion** [comment]
nacos-client不会区分内容， 请debug到nacos-client中查看是否获取到，或者看nacos-client日志是否获取到。

有可能nacos-client获取到了配置，回调给了SCA，但是SCA不处理或者处理失败。这样的话需要提交issue到SCA社区。
