### ISSUE TITLE
SpringCloud naocs online and offline issues，上线下线问题

### ISSUE THREAD

**Issue by Capttt1988** [alibaba/nacos#11112]
版本：config和discovery均是2.2.10-RC1。

场景：开发环境，为了避免服务冲突，在yml中配置了nacos.discovery.instance-enabled=false，服务默认处于下线状态。网络断线重连后（断线重连时间大于配置的删除实例时间，即preserved.ip.delete.timeout:3000），服务会处于上线状态，请问这是bug，还是配置问题，哪里配置错了？有大佬分析解决下吗？（ps：可以通过插拔网线等方式复现）

目前临时解决方式：preserved.ip.delete.timeout配置间隔超长，即删除实例时间大于网络断线重连时间，这样该实例未被删除，网络连接后，该实例依然可以处于下线状态。

Version: Both config and discovery are 2.2.10-RC1.

Scenario: In the development environment, in order to avoid service conflicts, nacos. discovery. instance enabled=false is configured in yml, and the service is offline by default. After a network disconnection and reconnection (the disconnection and reconnection time is greater than the configured instance deletion time, which is preserved. ip. delete. timeout: 3000), the service will be in an online state. Is this a bug or a configuration issue? Where is the configuration error? Is there a leader who can analyze and solve it? (ps: can be reproduced by plugging or unplugging network cables, etc.)

At present, the temporary solution is: the configuration interval of preserved. ip. delete. timeout is too long, that is, the deletion time of the instance is greater than the network disconnection and reconnection time. This way, the instance has not been deleted, and after the network connection, the instance can still be offline.

**Comment by KomachiSion** [comment]
是否调用过更新实例接口，将enaled状态修改为true？
如果是的话， 请看更新实例接口的相关文档说明， 元数据有记忆能力， 防止断线重连后修改的运维参数被覆盖。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
