### ISSUE TITLE
非持久化客户端注册示例ID为null

### ISSUE THREAD

**Issue by llm163520** [alibaba/nacos#11117]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.2.3, nacos-client 2.1.0]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos]

**Additional context**

当参数spring.cloud.nacos.discovery.ephemeral=true，非持久化实例时；grpc注册后返回的实例ID(instanceId)为null
![image](https://github.com/alibaba/nacos/assets/22343834/c2b92af8-8094-4286-b80d-bec35e3a0aa2)
当参数spring.cloud.nacos.discovery.ephemeral=false，持久化实例时；能正常返回实例ID(instanceId)
![image](https://github.com/alibaba/nacos/assets/22343834/00bdee45-311a-4f5e-92dd-9ea44b0bd347)

**Comment by KomachiSion** [comment]
fixed by #10812
