### ISSUE TITLE
nacos load the config content ,if it contains Chinese characters will  throw yml parse exception

### ISSUE THREAD

**Issue by pengzhizhuo** [alibaba/nacos#1111]
## Issue Description
When using nacos to dynamically load nacos configuration content by environment (spring.profiles.active), if the nacos configuration contains any Chinese characters, including Chinese comments or Chinese configuration values, an exception will be thrown when the nacos configuration be loaded between the project starting, The exception is as follows:

> 

org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1                                                                                                                                                    at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)                                                                                                                                                                       at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)                                                                                                                                                             at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)                                                                                                                                                             at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)                                                                                                                                                                         at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)                                                                                                                                                              at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)                                                                                                                                                               at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)                                                                                                                                                                    at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)                                                                                                                                               at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)                                                                                                                                                                        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)                                                                                                                                                                       at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:72)                                                                                                                                                                           at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:112)                                                                                                                                                         at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:542)                                                                                                                                                                                           at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:160)                                                                                                                                                     at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:134)                                                                                                                                                     at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.createProperties(YamlPropertiesFactoryBean.java:135)                                                                                                                    at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:115)                                                                                                                           at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:100)                                                                                                               at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:75)                                                                                                                        at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:179)                                                                                                      at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:159)                                                                                                at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:88)                                                                                                                       at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94)                                                                                                   at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649)                                                                                                                                                   at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)                                                                                                                                                      at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)                                                                                                                                                                 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)                                                                                                                                                                at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)                                                                                                                                                                at com.mydt.dtgas.service.ServiceApplication.main(ServiceApplication.java:16)                                                                                                                                                                 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                                                                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                                                                                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                                                                      at java.lang.reflect.Method.invoke(Method.java:498)                                                                                                                                                                                           at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)                                                                                                                                                             at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)                                                                                                                                                                          at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)                                                                                                                                                                          at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)                                                                                                                                                              Caused by: java.nio.charset.MalformedInputException: Input length = 1                                                                                                                                                                                 at java.nio.charset.CoderResult.throwException(CoderResult.java:281)                                                                                                                                                                          at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)                                                                                                                                                                                  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)                                                                                                                                                                                      at java.io.InputStreamReader.read(InputStreamReader.java:184)                                                                                                                                                                                 at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)                                                                                                                                                                       at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183)                                                                                                                                                                       ... 36 common frames omitted
--

**Comment by nkorange** [comment]
This is a [Spring Cloud Alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) issue.

**Comment by pigxcloud** [comment]
@pengzhizhuo  如果用的windows 的话 改下系统编码 成 UTF-8

**Comment by ljh205sy** [comment]
https://jingyan.baidu.com/article/d7130635e8a38413fdf4753b.html   按照这个方式改了系统的编码，还是乱码

**Comment by ljh205sy** [comment]
获取nacos配置中心配置，用java -jar的方式启动就会报这个错误，有好的解决方案吗？

**Comment by ylh23y** [comment]
命令启动需要加编码：java -Dfile.encoding=utf-8 -Xms2g -Xmx2g -Xmn1g -server -jar pool-auth.jar

**Comment by chenquanyu** [comment]
It seems to be the same [issue](https://github.com/alibaba/spring-cloud-alibaba/issues/1200).
