### ISSUE TITLE
关于升级nacos-client2.2.4的问题

### ISSUE THREAD

**Issue by tianliu94321** [alibaba/nacos#11119]
我们的环境如下，请问可以直接排除spring-cloud-starter-alibaba-nacos-discovery里的nacos-client-2.2.0,
直接引入 nacos-client-2.2.4吗, 需要升级nacos-server的版本吗
nacos 2.1.2 
springboot  2.3.12.RELEASE
spring-cloud.version  Hoxton.SR12 
spring-cloud-alibaba.version 2.2.9.RELEASE

**Comment by KomachiSion** [comment]
理论上可以直接引入，SCA应该没有使用反射之类的功能。

服务端不需要升级。

**Comment by tianliu94321** [comment]
好的。谢谢

> 理论上可以直接引入，SCA应该没有使用反射之类的功能。
> 
> 服务端不需要升级。
