### ISSUE TITLE
使用K8S启动集群，外部mysql作为存储，是否有必要使用pvc持久化

### ISSUE THREAD

**Issue by jsczrangel** [alibaba/nacos#11114]
如题，在生产环境使用过程中，或多或少遇到过有节点和集群raft不一致的问题，遇到这个问题只能清理pvc内数据盘，重新同步。
在nacos-k8s项目里，quickstart里那样，如果不给nacos挂载数据盘，而配置信息都在mysql里，在生产环境是否有弊端?

**Comment by jjxx54** [comment]
关注

**Comment by KomachiSion** [comment]
存储的数据不一样， 如果你对注册中心模块的元数据和开关数据不关心， 可以不挂载。 如果关心则需要挂载。

mysql存储的是命名空间以及配置中心的数据， 注册中心不依赖mysql
