### ISSUE TITLE
nacos2 开启鉴权后，配置文件里只能配置管理员用户才能连接nacos，非管理员用户则authorization failed!

### ISSUE THREAD

**Issue by zzldnl** [alibaba/nacos#11121]
这个问题困扰很久，升级nacos2后，配置文件里只能配置管理员用户和密码才能认证通过，其他用户设置有权限也无法连接，就是如此吗？

**Comment by KomachiSion** [comment]
说明没有给新用户赋权。

**Comment by habwang** [comment]
https://github.com/alibaba/nacos/issues/10347
