### ISSUE TITLE
Dose nacos support client to register config changing listener？

### ISSUE THREAD

**Issue by Albert-Hugo** [alibaba/nacos#1112]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Support client to register listener for config changing.

### Describe what you expected to happen

If key's value changed from v1 to v2 ,client should be able to register a listener to do something

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
1.0.0

**Comment by nkorange** [comment]
It already supported now. Refer to [doc](https://nacos.io/zh-cn/docs/sdk.html).

**Comment by Albert-Hugo** [comment]
> It already supported now. Refer to [doc](https://nacos.io/zh-cn/docs/sdk.html).

I see, thanks. In addition, after trying a example test. I think if will be nice to add a content handler to handle the changed content instead of leaving whole content.

**Comment by nkorange** [comment]
Why need 'changed content'? In most cases the users only care about the eventual full content.

**Comment by Albert-Hugo** [comment]
Because some case the user may need to change a config and depends on this config to change program logic at runtime.

**Comment by nkorange** [comment]
@Albert-Hugo Yes, but why they need the changed content only?

**Comment by Albert-Hugo** [comment]
> @Albert-Hugo Yes, but why they need the changed content only?

Sorry for not clarify my point. What I want to point out is that for a specific file format  e.g. properties config. I think it will be nice to know which { key : value } was updated.

**Comment by nkorange** [comment]
> > @Albert-Hugo Yes, but why they need the changed content only?
> 
> Sorry for not clarify my point. What I want to point out is that for a specific file format e.g. properties config. I think it will be nice to know which { key : value } was updated.

This is already supported for [Spring Nacos](https://github.com/nacos-group/nacos-spring-project).
