### ISSUE TITLE
Remove cluster list page namespace info

### ISSUE THREAD

**Issue by tonycody** [alibaba/nacos#11129]
⚰ Remove the namespace information from the node list page, as the node list has nothing to do with namespaces and should not display namespace information

⚰ configurationManagement8: 'Configuration Management',case sensitive

🐛 Fix, when adding configurations using the default public namespace, the namespace is shown as empty or nodefine

✨#Configuration list page
- PageTitle is added to show the description, if there is no description, it will show the name, hide the namespace ID, and keep the function of namespace ID copying.
- Removed the Create New Configuration function from the right + icon and replaced it with the Create Configuration button on the left.
- Multi-language configuration fixes and adds new hints

✨#Cluster list, namespace list, service list, list of listeners, version history
- Unified the style of all right-side buttons to the left side.
- Namespaces are now displayed in a unified style.

✨#PageTitle, Copy, NameSpace
- Optimization of basic components, added Chinese and English information, namespace description presentation and other functions

**Comment by chen-jie** [comment]
namespace ID copying  is not working in nacos 2.3.0
