### ISSUE TITLE
2.2.4选择服务无法下线

### ISSUE THREAD

**Issue by wp2code** [alibaba/nacos#11136]
**版本信息**
 - nacos-server  2.2.3（下载的启动包，页面打开是2.2.4）
 - nacos-client 2.2.1
 - springboot 2.3.12.RELEASE
 - spring-cloud.version Hoxton.SR12

**问题**
应用服务无法下线 ,服务端（nacos-server）日志**nacos.log** 报如下异常
**caused: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)Z**
**截图**
![1694689142363](https://github.com/alibaba/nacos/assets/12785365/8fda1a9b-ef08-4fdc-ab25-65831fd5043b)

**Comment by KomachiSion** [comment]
console.nacos.io 即部署的2.2.3版本的部署包， 测试并无问题，无法复现。

看报错问题应该是类冲突导致的，推测是你从错误的地方下载了别人魔改的部署包或者是自行修改了依赖内容的版本导致的。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
