### ISSUE TITLE
[Nacos Client 1.4.5] 客户端一直会去请求 http://100.100.100.200/latest/meta-data/ram/security-credentials/

### ISSUE THREAD

**Issue by lovewe** [alibaba/nacos#11148]
![image](https://github.com/alibaba/nacos/assets/15944280/0f7ed1ce-70d4-43b4-871d-86e3991fd0c0)
![image](https://github.com/alibaba/nacos/assets/15944280/aa47d1ca-5bc2-4712-85c9-8a298718c858)
![image](https://github.com/alibaba/nacos/assets/15944280/95bc7517-ac9b-409f-b5ab-3204ac8dbba5)
![image](https://github.com/alibaba/nacos/assets/15944280/ba4ff494-63d3-4c9a-95b9-8cede6cf92f6)
![image](https://github.com/alibaba/nacos/assets/15944280/fc3251e2-bc80-49ba-bf10-594a327e0687)

在injectRoleName方法中ramRoleName 被默认设置为空字符串，在getSecurityCredentialsUrl()方法中，判断了this.ramRoleName != null

**Comment by KomachiSion** [comment]
1.4.6中已修复，请升级至1.4.6版本

**Comment by KomachiSion** [comment]
#10525
