### ISSUE TITLE
请问nacos能否实时或动态获取dataID的创建动作

### ISSUE THREAD

**Issue by wangpengshao** [alibaba/nacos#11144]
当下项目存在以下场景，就是项目可能会临时创建多个DATAID,也就是多个配置文件。请问Nacos是否能动态监听新创建的dataID呢,或者监听命名空间的创建和修改动作

**Comment by KomachiSion** [comment]
目前不支持， Nacos3.0中有规划模糊订阅功能，能够监听配置的创建和删除操作。

**Comment by wuchubuzai2018** [comment]
个人觉得，可以使用Canal监听mysql的binlog日志，然后监听那张config_info表和命名空间那张表

**Comment by KomachiSion** [comment]
No more response from author, the issue can be merged to ospp
