### ISSUE TITLE
cipher-aes 配置文件再次编辑时conetent会变成明文

### ISSUE THREAD

**Issue by lch-ye** [alibaba/nacos#11141]
When fixing the cipher-aes storage configuration file, only the encrypted content will be stored in the database when the file is first created. Modifying the configuration file again will cause the encrypted content in the database to become plaintex.

1. go to nacos config craete yaml file.
2.  client on new yaml file , use cipher-aes.
3. update cipher-aes yaml file, nacos db  content changed from ciphertext to plaintext.

修复cipher-aes存储配置文件时，只有首次创建文件才会在数据库中存储加密内容，再次修改配置文件，数据库中的加密内容会变成明文的缺陷问题。

**Comment by E1se2t** [comment]
@i will slove it@

**Comment by KomachiSion** [comment]
it's need to pass encryptedDataKey when  encrypting and publishing configurations, otherwise nacos plugin don't know how to encrypt the content.

**Comment by E1se2t** [comment]
> it's need to pass encryptedDataKey when encrypting and publishing configurations, otherwise nacos plugin don't know how to encrypt the content.

![image](https://github.com/alibaba/nacos/assets/67528597/7eed181c-bb7b-4f84-b00f-2f81c8669933)
Is the encrypted content generated using the plugin secretKey and content，I don t see the role of encryptedDataKey here

**Comment by E1se2t** [comment]
![image](https://github.com/alibaba/nacos/assets/67528597/41aec646-6794-4e61-b6e3-0955430ddf4b)
I believe this change can be made，remove this judgment

**Comment by E1se2t** [comment]
![image](https://github.com/alibaba/nacos/assets/67528597/5b276242-d3df-4d7b-829d-6b2a2589f5ac)
我认为可以去掉这个判断，改成这个样子，每次创建&发布配置都会根据secretKey和content生成加密内容

**Comment by E1se2t** [comment]
有没有可以讨论issue的地方...在GitHub上沟通一次好慢，核心贡献者群我能进吗？怎么才能进呢？

**Comment by E1se2t** [comment]
@KomachiSion 请问有Contributor群聊吗？官方给的群都是“僵尸”群，在GitHub上跟你们沟通一次比较麻烦，解决一个issue等待回复的时间跨度太长了，我有挺多问题想讨论的，如果有类似群聊，我需要达到什么标准才可以加入？

**Comment by KomachiSion** [comment]
插件有一种情况是在客户端加密后传入服务端。  这种情况传输过程中也是密文。

控制台是因为不支持插件扩展， 所以只能在服务端进行加密，你看起来才是都是在服务端生成的。

**Comment by E1se2t** [comment]
那就是有两种情况了

**Comment by E1se2t** [comment]
> 插件有一种情况是在客户端加密后传入服务端。 这种情况传输过程中也是密文。
> 
> 控制台是因为不支持插件扩展， 所以只能在服务端进行加密，你看起来才是都是在服务端生成的。

那就是有两种情况：
客户端直接加密配置后传入服务端，这个情况传输过程中content也是密文，所以无需再次加密
控制台发布配置，这个时候需要通过服务端加密

可不可以在ConfigController#searchConfig方法的响应对象ConfigInfo里面加一个字段，用于区分是否是控制台侧进行的配置发布，这样在控制台侧发布配置的时候，就能通过这个字段去判断是否需要对content进行加密了，现在的问题就是控制台侧发布配置的时候encryptedDataKey不为空，导致服务端以为不需要对content进行加密了，是否能加一个字段区分这种控制台测发布配置的情况

或者说大佬你还有什么好的方法吗？

**Comment by E1se2t** [comment]
那就是有两种情况：
1. 客户端直接加密配置后传入服务端，这个情况传输过程中content也是密文，所以无需再次加密
2. 控制台发布配置，这个时候需要通过服务端加密

可不可以在ConfigController#searchConfig方法的响应对象ConfigInfo里面加一个字段，用于区分是否是控制台侧进行的配置发布，这样在控制台侧发布配置的时候，就能通过这个字段去判断是否需要对content进行加密了，现在的问题就是控制台侧发布配置的时候encryptedDataKey不为空，导致服务端以为不需要对content进行加密了，是否能加一个字段区分这种控制台测发布配置的情况

或者说大佬你还有什么好的方法吗？

**Comment by KomachiSion** [comment]
主要还是要梳理一下加密插件的工作流，这块之前是 @li-xiao-shuang 做的， 等后面有空了我再和 @shiyiyue1102 等配置中心的大佬一起梳理下吧。

**Comment by Saoforest** [comment]
想问一下这个问题有进展了吗？二次编辑密文就变明文了

**Comment by shiyiyue1102** [comment]
this bug is fixed  in PR https://github.com/alibaba/nacos/pull/12061 and already release in version 2.4.0-beta
