### ISSUE TITLE
v2.2.3版本登录页面的问题

### ISSUE THREAD

**Issue by hongshenggit** [alibaba/nacos#11153]
有个小问题，想讨论一下，
v2.2.3版本通过浏览器登录控制台http://ip:8848/nacos ，每次重定向到登录页面，都会带上?namespace=&pageSize=&pageNo=这些参数，由于没有登录，会提示，权限认证失败的问题，

而v2.2.1版本会正常跳转到登陆页面，未携带参数http://ip:8848/nacos/#/login

期望结果：输入http://ip:8848/nacos，跳转到登陆页面，http://ip:8848/nacos/#login

虽然不影响使用，但是想看看这个问题能不能通过配置解决
![image](https://github.com/alibaba/nacos/assets/87966434/87ad43cd-4d53-47b0-9aba-11cea73a5f22)
上图是我通过k8s部署，创建 nodePort类型的service暴露8848端口

**Comment by huangkemingyyds** [comment]
建议控制台的ui，做一个全局登录用户的捕获，没有登录的话，统一返回登录页进行登录。derby目前确实存在没有登录的情况下可以在其他页面切换，虽然没有数据展示。

**Comment by HL2554169233** [comment]
这完全就是鉴权跳转没做好
