### ISSUE TITLE
Add Versioning for Nacos config.

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#11158]
**Is your feature request related to a problem? Please describe.**

目前nacos的比对配置以及CAS发布都是通过md5来做的，我们这里为什么不用版本号呢？
如果用版本号的话，对比md5性能肯定会好一些，而且适用场景也多一些。
比如最近开源之夏的K8S的Configmap与Nacos中的配置的同步的场景，现在采用md5的话感觉不是很好保证Nacos中的配置与Configmap的一致性，但是如果是版本号的话，就很好处理了。（k8s里面的资源也有版本号的概念-resourceVersion（递增），很方便判断哪个配置是最新的，可以直接把configmap的版本号作为关键字段存在nacos的版本号中）

主要是版本号对比md5的优点：
- 他能比较出哪个是最新的配置
- 性能更优

**Describe the solution you'd like**

nacos config新增版本号字段。

**Describe alternatives you've considered**

或者想办法使nacos config中md5含义上进行增强，使它可以判断哪个是最新的配置。

**Additional context**

None provided.

**Comment by KomachiSion** [comment]
但是版本号需要准确维护版本号，基于数据库还好做一点，因为数据库帮你锁好了， 如果以后持久化功能不是很好维护版本号的时候，就麻烦了。

md5还有个好处，因为客户端和服务端之间就是通过md5来准确维护一致性，反正都需要计算一次，就复用md5，这样也就不存在所谓的性能更优了。

**Comment by KomachiSion** [comment]
No more response from author, it seems community not interesting this issue.
