### ISSUE TITLE
[ERROR] LocalConfigInfoProcessor: save snapshot error

### ISSUE THREAD

**Issue by Floweryu** [alibaba/nacos#11151]
**Describe the bug**
ERROR com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor: save snapshot error
![image](https://github.com/alibaba/nacos/assets/45811382/382e5552-7070-476e-93bc-4c9bbbdbe12e)
Is the file path too long?

nacos-client version is 2.1.0

**Comment by KomachiSion** [comment]
FileNotFoundException, may be your path is not exist, please make sure your file system can be writen and your user has right privalige for the path.

**Comment by KomachiSion** [comment]
The error not effect usage but effect the cache, If can't get config from server(such as server down, network problem), your app will not get the config from snapshot.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by Floweryu** [comment]
This error does not affect service use，so can close this issue.
