### ISSUE TITLE
Nacos2.2.3服务端+1.4.1客户端读写配置时出现user not found

### ISSUE THREAD

**Issue by wuchubuzai2018** [alibaba/nacos#11164]
**Describe the bug**
Nacos2.2.3服务端+1.4.1客户端读写配置时出现user not found
nacos server version:2.2.3
nacos client version:1.4.1
spring cloud alibaba:2.2.5.RELEASE
测试几次发现：
新建的用户启动的时候无法读取配置，提示user not found，默认的nacos用户可以读取，但是写入的时候，提示user not found
不知道是不是版本存在问题，2.2.3的服务端的加密的几个配置都设置了，控制台也分配了权限，控制台访问没问题
**Expected behavior**
微服务程序上可以正常访问和读写

**Actually behavior**
提示：user not found

**Comment by zzzxx** [comment]
问一下 ，怎么解决啊， 我也是这个问题
