### ISSUE TITLE
元数据不更新问题

### ISSUE THREAD

**Issue by wuxingyun** [alibaba/nacos#11165]
我在元数据加了 version=1.1.7.1，我新发布服务代码中设置 version=1.1.8.1，我也把镜像中的jar 反编译查看里面配置是version=1.1.8.1，但是 nacos 上面还是 version=1.1.7.1，但是有些服务却是 version=1.1.8.1

**Comment by KomachiSion** [comment]
元数据加version=1.1.7.1是通过 更新实例的接口加的吗？ 是的话看文档中关于更新实例接口的说明，有记忆能力，有跟高优先级。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
