### ISSUE TITLE
Nacos 控制台 BUG

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#11163]
在控制台修改了某个实例得元数据之后，会有两个请求，一个请求时更新数据
一个请求时更新完之后会做一个查询。但是在第二个查询得时候发现查询出来得数据时更新之前得数据。
需要刷新一下页面，在次查询数据才会正常。

**Comment by KomachiSion** [comment]
非bug， 生成查询数据本身就是异步生成的。如果修改完立刻去查询， 在异步生成的情况下，可能会还未生成数据。是符合预期的，如果需要控制台自动刷新能查询到，可能需要对控制台做一点优化。
