### ISSUE TITLE
Version 1.0.0,when i offline an service instance, all service disconect mysql | redis

### ISSUE THREAD

**Issue by leeweikung** [alibaba/nacos#1116]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1.   watch service detail    查看服务详情
2.  click offline button of one instance   点击其中一个实例的下线按钮
3.  and then all service instance disconect mysql and  redis   然后所有的服务实例都连接不上数据库及高速缓存

### Tell us your environment
AWS EC2,  docker deployment

**Comment by nkorange** [comment]
Should be a problem of database.
