### ISSUE TITLE
为什么下载nacos源码后，项目里面缺少这三个实体类呢

### ISSUE THREAD

**Issue by CCode9-3** [alibaba/nacos#11168]
com.alibaba.nacos.consistency.entity.ReadRequest;
 com.alibaba.nacos.consistency.entity.Response;
 com.alibaba.nacos.consistency.entity.WriteRequest;

**Comment by Rikeyc** [comment]
这个需要使用protobuf编译，会自动动生成

**Comment by huangkemingyyds** [comment]
![image](https://github.com/alibaba/nacos/assets/66153067/f1421dd3-2b50-489f-a368-f641c3f3f0a6)

**Comment by KomachiSion** [comment]
see FaQ
