### ISSUE TITLE
如何配置nacos 实现禁止公网ip访问呢 

### ISSUE THREAD

**Issue by UltramanNoa** [alibaba/nacos#11176]
我们搭建的nacos集群在A,B,C,D,E,F分别在各自的服务器上  然后通过腾讯云负载均衡分配的虚拟ip来负载到各自机器上  现在通过负载均衡虚拟ip可以访问，但是通过各机器的公网ip还是可以直接访问到；
请问我该如何配置才能禁止直接通过公网ip访问到各个机器上呢？

**Comment by wuchubuzai2018** [comment]
1、入站规则，限制只允许指定IP访问

**Comment by KomachiSion** [comment]
和nacos没什么关系，是环境网络的问题。
