### ISSUE TITLE
Default page size configuration for list pages

### ISSUE THREAD

**Issue by cqkxzyi** [alibaba/nacos#11175]
The default page size for the list page is 10. After modifying the size, the refresh page changes back to 10. I hope to be able to record the page size modified by the user.

**Comment by huangkemingyyds** [comment]
这个应该是一个新的需求，单从功能实现上来说的话，个人觉得可以aop入手实现，需要新增一张记录操作的表，记录内容：用户，时间，分页数变更（由10变更20）等。当然，还有前端这块的交互问题，比如要在哪展示，展示哪些信息，查看、修改是否需要权限等等。

**Comment by KomachiSion** [comment]
This custom feature, I think you can develop your self manager console ui to solve it.
