### ISSUE TITLE
动态刷新问题

### ISSUE THREAD

**Issue by tutuerhao** [alibaba/nacos#11173]
源码位置：org.springframework.cloud.context.scope.GenericScope#destroy()
问题：如果两个bean有依赖关系，A依赖B，如果先销毁A还未销毁B，此时有个请求进来需要加载A，那就读到了过期的B了
<img width="867" alt="image" src="https://github.com/alibaba/nacos/assets/29938085/f8bba0c2-39e0-47f2-8ed9-3794914f0a5e">

**Comment by huangkemingyyds** [comment]
在销毁Bean的过程中，org.springframework.cloud.context.scope.GenericScope#destroy0方法会先获取当前缓存中所有的BeanLifecycleWrapper对象，并清空缓存。然后对每个BeanLifecycleWrapper对象进行销毁操作。

在执行销毁操作时，会获取与该Bean对应的写锁，并在finally块中释放写锁。**这样可以保证在销毁Bean的过程中不会被其他请求加载到过期的Bean**。

因此，在多线程环境下，如果有一个请求进来需要加载A，而此时A还未被销毁，那么该请求会被阻塞等待锁，直到A被销毁完毕后才会加载A。所以不会读取到过期的B。

我认为在该情况下不会读取到过期的B

**Comment by KomachiSion** [comment]
Not nacos‘ problem, please move to spring cloud community.
