### ISSUE TITLE
nacos 客户端2.2.1 服务端 2.0.4 删除配置不生效

### ISSUE THREAD

**Issue by Code-WangShuai** [alibaba/nacos#11170]
nacos 客户端2.2.1 服务端 2.0.4 删除配置不生效
复现步骤:
1. 添加配置
xxx:
   xxlist:
      -  "A"
      -  "B"
动态刷新正常,删除 "xxList[1]" 刷新也正常,但是把配置完全删掉之后, 动态刷新 不会清空, 会保留最后一次删除前的值
![image](https://github.com/alibaba/nacos/assets/49975230/09582114-8f1b-4909-a360-90f828b88c49)
此时nacos的配置文件是空的.

**Comment by KomachiSion** [comment]
这和nacos没关系， 你可以查看nacos-client的日志，应该是有下发的， 但是应用可能会忽略空配置，保留之前配置。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
