### ISSUE TITLE
[BUG] 重启后持久实例数量归0

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/nacos#11178]
版本：2.1.0 
现象： 服务重启后持久实例数据归0 ，控制台和SDK 都拉取不到实例
服务端发现 services are automatically cleaned 清理服务的log 
同时发现log ：
WARN There are no [com.alibaba.nacos.naming.core.v2.event.client.ClientOperationEvent.ClientRegisterServiceEvent] publishers for this event, please register

怀疑是nacos raft 状态机先于事件消费者的bean 启动了，导致事件丢失，没有加到ClientServiceIndexesManager#publisherIndexes 中

我想问下这个问题是已知的吗，是否在后续版本修复了

**Comment by huangkemingyyds** [comment]
是否跟这个issues是同一个问题
https://github.com/alibaba/nacos/issues/11135

**Comment by KomachiSion** [comment]
升级到新版本，中间有个版本修复过类似问题。

**Comment by KomachiSion** [comment]
#9231
