### ISSUE TITLE
on project nacos-client: Error creating shaded jar: Unsupported class file major version 61 -> [

### ISSUE THREAD

**Issue by Acechengui** [alibaba/nacos#11177]
My name is jdk17, and the source code download is 2.2.3. The compilation is running normally, but there is an error during packaging. On project nacos client: Error creating shaded jar: Unsupported class file major version 61, may I ask if the source code does not support jdk17 packaging? Because some content has been modified based on the source code, it needs to be repackaged for clarification

**Additional context**

**Comment by KomachiSion** [comment]
source code is supported, but maven shaded plugin maybe not, you can try to upgrade the maven plugin to retry.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
