### ISSUE TITLE
Group supports background entry, page selection by drop-down box

### ISSUE THREAD

**Issue by rushsky518** [alibaba/nacos#1117]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)
group 支持后台录入，页面通过下拉框选择

**Comment by nkorange** [comment]
麻烦详细描述下，group指的是服务发现里的还是配置管理里的？group目前是可以动态添加的，没有预先配置group列表的功能。

**Comment by rushsky518** [comment]
config 里面的 group

**Comment by nkorange** [comment]
> config 里面的 group，希望做到页面录入，创建配置的时候，从下拉列表选择

目前group都是动态添加的，如果是从下拉列表选择，就会导致每次都需要录入一个新的group，不够灵活。
