### ISSUE TITLE
Reports security issues during ldap login

### ISSUE THREAD

**Issue by robin2017** [alibaba/nacos#11182]
If the attacker knows the ldap username, he can log in with the LDAP username and nacos password, bypassing ldap security authentication. Currently, LDAP users log in and write a record to the user table in the database with a fixed password: nacos
如果攻击者知道ldap的用户名，那可以使用LDAP_username账号和nacos密码登录，绕过ldap的安全认证。因为目前LDAP用户登录后会在数据库中的user表中写入一条记录，该记录的密码为固定值：nacos

Therefore, it is recommended to change the password value to a random number:nacos+UUID.randomUUID()
因此建议密码值改为随机数:nacos+UUID.randomUUID()

**Comment by robin2017** [comment]
<img width="1684" alt="image" src="https://github.com/alibaba/nacos/assets/19527904/d791acb4-4be4-4897-adef-3831424b6de1">

**Comment by reza13733** [comment]
Ytrg

**Comment by KomachiSion** [comment]
LDAP插件没有修改密码的能力吗？ 一旦插入了就只能使用这个密码吗？

**Comment by robin2017** [comment]
> LDAP插件没有修改密码的能力吗？ 一旦插入了就只能使用这个密码吗？

1、nacos接入ldap，ldap里面存储了用户密码，用户为什么要改？除非这个是初始密码才会让用户改
2、更重要的是，这个改了密码，并不会同步到ldap中，还让用户记住nacos和ldap两个密码？

**Comment by robin2017** [comment]
> LDAP插件没有修改密码的能力吗？ 一旦插入了就只能使用这个密码吗？

LDAP插件说白了就是认证时通过LdapTemplate调用下ldap接口，验证通过后在nacos数据库中创建一条记录，并没有反向写ldap的能力，所以也没法修改ldap数据，只是修改nacos自己的users表数据

**Comment by KomachiSion** [comment]
所以这个密码其实并没有意义， 主要还是看用户在ldap中写入的密码。

**Comment by Daydreamer-ia** [comment]
在ldap模式下，并不会用db的密码来比对login in的。所以你的说法不成立，除非是一开始用的ldap，然后重启切换成nacos模式的auth。
