### ISSUE TITLE
服务内存居高不下

### ISSUE THREAD

**Issue by xiaoyuwang1987** [alibaba/nacos#11186]
xmx配置最多3.5g，但是目前容器使用已经快到4.5g 一段时间容器就要重启，怀疑内存泄露
![image](https://github.com/alibaba/nacos/assets/24749103/a775fd9f-bd9a-41a8-a59a-4ef650a6c9af)

![1695631189030_3E4C2417-CD01-4936-B61D-E5256189A10C](https://github.com/alibaba/nacos/assets/24749103/59891cd0-5808-439d-a0c4-cea7175140c3)
![image](https://github.com/alibaba/nacos/assets/24749103/1b59b2e2-25b4-4539-ba38-4d1de0113269)

![image](https://github.com/alibaba/nacos/assets/24749103/93a878a4-df6c-41c9-9ee1-dcbdcb68749f)

**Comment by KomachiSion** [comment]
1. 这个nacos有什么关系， 你应用的内存泄漏自己dump内存排查
2. 内存使用超出了设置-xmx，自查容器，限制，jdk以及堆外内存等，

**Comment by xiaoyuwang1987** [comment]
> 1. 这个nacos有什么关系， 你应用的内存泄漏自己dump内存排查
> 2. 内存使用超出了设置-xmx，自查容器，限制，jdk以及堆外内存等，

xmx有设置 现在比如jvm已经设置3.5但是容器现在设置4.5 容器还在运行 里面还在跑 不懂是不是线程数太多 占用对外内存
