### ISSUE TITLE
配置了相同key时，正在运行的程序配置@RefreshScope的@Value无法获取数据

### ISSUE THREAD

**Issue by wangyongsen** [alibaba/nacos#11181]
在程序运行过程中，配置了相同的key，此时服务会报错:
![image](https://github.com/alibaba/nacos/assets/26532471/8e6fe381-48c3-43d5-b5d7-aa647699830d)
但是为什么在未修改之前，服务@RefreshScope下的@Value无法获取数据
Could not resolve placeholder 'gaode.key' in value "${gaode.key}"

不明白为什么会影响到当前的运行

**Comment by KomachiSion** [comment]
报错为yaml格式解析错误，Nacos不负责解析配置内容，请自查应用解析配置的位置，或提交至对应框架社区进行提问。

目前信息看起来应该是需要您到SCA社区去咨询一下。
