### ISSUE TITLE
修改配置的疑问

### ISSUE THREAD

**Issue by WangPei0316** [alibaba/nacos#11196]
修改一个配置时，会先尝试插入，然后捕获唯一约束异常，再进行update。  这样做的目的是什么？  我们在适配达梦数据库时，还需要单独再加一个sql-error-codes.xml标记达梦的6602唯一约束报错code码，有一天客户换了个版本，这个code码又换成6625，又得加上这个code，未免有些繁杂。 可否直接提前查这个配置是否存在，就不用再捕获异常后再插入了

**Comment by E1se2t** [comment]
#10672

**Comment by Bo-Qiu** [comment]
这样有并发风险

**Comment by KomachiSion** [comment]
通过唯一约束是通过数据库的行锁和事务来保证并发操作时的一致性问题。

先查询再插入或更新会导致操作非原子， 并发问题会全部落在引擎测，但引擎是分布式系统，无法彻底保证（请参考CAP），因此暂时使用唯一约束来执行是最合理的。

至于dameng数据库的错误码变更的问题，是因为dameng数据库的错误码还没有到达稳定状态导致的，错误码的映射和补全需要根据版本跟上，这是插件适配时无可奈何的问题。
