### ISSUE TITLE
code-style 失效

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/nacos#11191]
我使用项目中的 style/nacos-code-style-for-idea.xml 格式化代码后，无法通过nacos 的格式化检查，这是为什么？

我按照文档导入的文件：
Preferences/Settings --> Editor --> Code Style --> Schema --> Import Schema --> IntelliJ IDEA code style XML
举例：
ProtocolAuthService 这个类，格式化后无法通过检查
格式化前：
![image](https://github.com/alibaba/nacos/assets/32947555/8954b187-03df-474c-af49-8d2a4bef51ff)
格式化后：
![image](https://github.com/alibaba/nacos/assets/32947555/780617e9-de96-460d-85ce-4ee0a18105a7)
报错：
![image](https://github.com/alibaba/nacos/assets/32947555/f84400b6-22b5-4a83-9caf-69f19fe64484)

**Comment by KomachiSion** [comment]
你的p标签没有终止， 这种情况需要p标签和内容写在同一行。

**Comment by KomachiSion** [comment]
这种缺少内容的问题，reformat肯定修复不了， 需要你自己修复。

**Comment by Cczzzz** [comment]
它原来是好的，是用了Style文件格式化后坏了，不能通过maven 插件检查
