### ISSUE TITLE
batchRegisterInstance Why is there no recalculateRevision

### ISSUE THREAD

**Issue by E1se2t** [alibaba/nacos#11192]
在registerInstance方法中，ClientManager根据clientId获取客户端的信息，然后recalculateRevision方法重新计算了客户端的版本号
https://github.com/alibaba/nacos/blob/57efe9f5201280a7c273a70b3ac75fe78bae3dea/naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java#L55-L75

但是我看batchRegisterInstance却没有这个recalculateRevision的操作，如果是批量注册的Instance，难道就不用重新计算客户端版本号了吗？
https://github.com/alibaba/nacos/blob/57efe9f5201280a7c273a70b3ac75fe78bae3dea/naming/src/main/java/com/alibaba/nacos/naming/core/v2/service/impl/EphemeralClientOperationServiceImpl.java#L78-L101

那Distro的DistroDataRequest发送gRpc去verifyData的时候，如果是批量注册的那些Instance，客户端版本号也没变，那这就算校验成功了吗？
https://github.com/alibaba/nacos/blob/57efe9f5201280a7c273a70b3ac75fe78bae3dea/naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/impl/EphemeralIpPortClientManager.java#L126-L141

batchRegisterInstance是不是也需要有recalculateRevision这个操作呢？

**Comment by Bo-Qiu** [comment]
这应该是个Bug

**Comment by E1se2t** [comment]
> 这应该是个Bug

我也觉得是个BUG，我准备等 @KomachiSion 确认之后再提交一个PR

**Comment by KomachiSion** [comment]
辛苦提交一个PR
