### ISSUE TITLE
配置项回滚失败 - Configuration Rollback Failure

### ISSUE THREAD

**Issue by JaredTan95** [alibaba/nacos#112]
# 报告错误
通过`配置列表`选择莫个配置的`历史版本`，选择莫个配置进行回滚操作，回滚操作过后，返回`配置列表`，发现该配置项消失。
[nacos-issue](https://github.com/alibaba/nacos/issues/new)
[filing-good-bugs](http://fantasai.inkedblade.net/style/talks/filing-good-bugs/)

**Comment by JaredTan95** [comment]
@xuechaos

**Comment by xuechaos** [comment]
@JaredTan95 问下 的环境信息是那个版本，你操作的0.3分支的控制台么？
