### ISSUE TITLE
请教Nacos is starting...一直循环怎么回事,本地集群启动正常,上线集群启动一直Nacos is starting...,并且无报错

### ISSUE THREAD

**Issue by yhttqc654** [alibaba/nacos#11203]
2023-09-28 09:42:45,898 INFO Nacos is starting...

2023-09-28 09:42:46,905 INFO Nacos is starting...

2023-09-28 09:42:47,915 INFO Nacos is starting...

2023-09-28 09:42:48,924 INFO Nacos is starting...

2023-09-28 09:42:49,926 INFO Nacos is starting...

2023-09-28 09:42:50,939 INFO Nacos is starting...

2023-09-28 09:42:51,939 INFO Nacos is starting...

2023-09-28 09:42:52,939 INFO Nacos is starting...

**Comment by stone-98** [comment]
检查cluster.conf配置是否正确，

**Comment by Bo-Qiu** [comment]
<img width="907" alt="image" src="https://github.com/alibaba/nacos/assets/46370663/8ee96970-d32b-4b99-a199-db9f723c7088">
最终一定会失败或者成功的，可以等待一段时间看看，持续几分钟打印Nacos is starting的话，猜测是项目初始化从数据库分批全量dump配置表中的数据过慢（配置表中配置条目数较多）。

**Comment by yhttqc654** [comment]
cluster.conf和application.properties还有nacos-mysql.sql数据库在本地集群启动的时候已经配置好了可以完成启动,原本是用的2.1.0的版本后来我换了1.4.0的版本的nacos也出现Nacos is starting...,主要是start.out和nacos.log里面的信息全是Nacos is starting...让我找不着北了,目前先单机启动用着等有时间整个项目去调试整合nacos

**Comment by yhttqc654** [comment]
上面这个启动时间从一开始是连续的,到后面持续几分钟等待这个启动时间并没有持续刷新,而是一直到2023-09-28 09:42:52,939 INFO Nacos is starting...这个时间就卡着不动了

**Comment by stone-98** [comment]
之前有很多和你这个类似的issue，你可以参考之前的issue看一下是否和他们的问题类似，通常都是配置的问题。

**Comment by yhttqc654** [comment]
了解我今天一直在看各种解决方案,部署到线上我这边主要就是改动了cluster.conf里面的ip和端口信息,其他的配置没有变动

**Comment by tomlikeyou** [comment]
改动了cluster.conf的话，启动时候集群之间会建立连接，看是否是集群部署某一个节点部署问题，防火墙是否开了，端口是否开放

**Comment by yhttqc654** [comment]
端口没有设限,防火墙已经关闭,暂时先把问题关闭,后续花时间单独研究这一块

**Comment by yhttqc654** [comment]
1
