### ISSUE TITLE
the interfaces bypass security authentication

### ISSUE THREAD

**Issue by zmapleshine** [alibaba/nacos#1120]
![image](https://user-images.githubusercontent.com/12667610/56790720-e4a4b400-6837-11e9-9320-5d7179fbf408.png)
As shown in the figure above, it is the query profile details interface provided by the Nacos platform.

These interfaces can be obtained directly without authentication，
I think this is a serious security problem!

**Comment by nkorange** [comment]
This problem is already known and will be solved in #1105
