### ISSUE TITLE
a defects in nacos 0.6.2，always debug

### ISSUE THREAD

**Issue by antz-H** [alibaba/nacos#1121]
There is a defects in nacos0.6.2 ，I use the
springboot with the version is 1.5.8.RELEASE ,and its log4j2‘s version is 2.7 ,

com.alibaba.nacos.client.logger.option.Log4j2ActivateOption#activateAppender(java.lang.String, java.lang.String, java.lang.String) , there is no method of .setConfiguration(configuration) ,it is not compatible its result in so mang logs of debug and has a nullpointexception .

![image](https://user-images.githubusercontent.com/43114886/56797805-1b82c600-6848-11e9-9adf-bf9c6279692e.png)

**Comment by nkorange** [comment]
@antz-H Can you upgrade your nacos-client version to 1.0.0?

**Comment by antz-H** [comment]
> @antz-H Can you upgrade your nacos-client version to 1.0.0?

I try , the original defects is resolved，but anthos defects is appeared ;

2019-04-26 17:46:51,796 main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender

**Comment by nkorange** [comment]
@antz-H Is your log4j property file not under directory ```resources```?

**Comment by antz-H** [comment]
no，in my idea‘s resource，it is the classpath




| |
陈真娥
|
|
邮箱：huang7230468@163.com
|

签名由 网易邮箱大师 定制

On 04/26/2019 18:54, Fury Zhu wrote:

@antz-H Is your log4j property file not under directory resources?

**Comment by nkorange** [comment]
@antz-H Can you write a demo to reproduce this?

**Comment by antz-H** [comment]
This is the demo of nacos ,you can run it  , finally , appear a warn ，like ' main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender'


https://github.com/antz-H/nacos-log4j-demo.git

![image](https://user-images.githubusercontent.com/43114886/57203170-4efbe800-6fe0-11e9-9326-6afe80121850.png)

**Comment by hxy1991** [comment]
There is really no log4j2 configuration file in your demo.

**Comment by antz-H** [comment]
i know ，it is default




| |
陈真娥
|
|
邮箱：huang7230468@163.com
|

签名由 网易邮箱大师 定制

On 05/07/2019 10:12, Keep wrote:

There is really no log4j2 configuration file in your demo.

**Comment by antz-H** [comment]
I have already add  a log4j2-spring.xml  at the project , it still appear the error

main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender
@hxy1991

**Comment by antz-H** [comment]
https://github.com/antz-H/nacos-log4j-demo.git

**Comment by nkorange** [comment]
Already fixed in #996 which is merged to branch develop. Now you have two options:
1. Use logback instead of log4j2
2. Build Nacos server from source of develop branch

**Comment by antz-H** [comment]
Thank You !!!
