### ISSUE TITLE
nacos1.4.4版本，编码格式问题报错

### ISSUE THREAD

**Issue by LT519** [alibaba/nacos#11229]
nacos是1.4.4集群模式共三台机器
创建的nacos数据库命令为：
create database nacos character set utf8mb4 collate utf8mb4_general_ci;
添加配置中包含表情包，报错“发布失败，请检查参数是否正确。”
![image](https://github.com/alibaba/nacos/assets/31436779/6056a2fe-9934-4274-b331-4034f39dff21)
查看nacos日志报错信息如下：
2023-10-07 20:28:48,958 ERROR CONSOLE - unknown exception, request: /nacos/v1/cs/configs from 20.5.1.1

org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\x9F\x98\x8A"}...' for column 'content' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x8A"}...' for column 'content' at row 1
这种是bug还是配置问题？如何排查并解决？

**Comment by KomachiSion** [comment]
数据库创建配置问题，创建的数据库表不支持emoji， 自行修改数据库配置解决
