### ISSUE TITLE
nacos配置一更新，kibana就收集不到日志了

### ISSUE THREAD

**Issue by zzq666666** [alibaba/nacos#11227]
spring-cloud-starter-alibaba-nacos-discovery:2.2.1.RELEASE
spring-cloud-starter-alibaba-nacos-config:2.2.1.RELEASE
nacos-client:1.2.1
logback-core:1.2.3
slf4j-api:1.7.3.0

nacos配置一更新，kibana就收集不到日志了，麻烦给提供下思路，我该怎么去排查和定位问题？

**Comment by KomachiSion** [comment]
nacos配置是否推送到应用了， 如果已经推送到了，那就和nacos无关了。 需要自查应用和kibana的兼容性问题。

**Comment by KomachiSion** [comment]
No more response from author, and it's not nacos problem
