### ISSUE TITLE
nacos的api似乎一直无法获得dataid,这是出于安全考虑吗?

### ISSUE THREAD

**Issue by qicaihuoyan** [alibaba/nacos#11239]
nacos的api似乎一直无法获得dataid,这是出于安全考虑吗?
当大部分的api又都需要dataid这个字段,就变得很麻烦

**Comment by KomachiSion** [comment]
因为配置中心从场景来说， 应用是知道自己依赖了哪些配置（及dataId）， 而客户端是给应用使用的，所以不需要获取dataid的api。

只有运维（控制台）需要获取dataId，用来展示和检索， 所以控制台能获取到。

**Comment by KomachiSion** [comment]
如果你的场景需要感知到dataid， 请确认使用方式是正确的。

或者按照自己的构想fork nacos进行改造部署。但是需要自行评估对应的性能、安全、错用导致的稳定性问题。
