### ISSUE TITLE
nacos持久化实例探测频率过多

### ISSUE THREAD

**Issue by poemkcm** [alibaba/nacos#11230]
在使用持久化实例作为注册对象时，发现nacos服务端会以1.25s频次发起健康探测。
客户端版本：2.2.3
服务端版本：2.2.3
测试步骤：以单机启动服务端，注册一个持久化实例

目前观测下来的问题：

1. TIME-WAIT保留在服务端

虽然是nacos主动探测的，但是挥手是nacos服务端发起的。如果是客户端发起，那么time-wait实际上可以甩给客户端，但现在情况恰恰相反。

2. 频次太多

1.25s作为健康检测，我觉得过于频繁了。翻看代码
com.alibaba.nacos.naming.healthcheck.v2.processor.HealthCheckCommonV2#reEvaluateCheckRT

`checkRT = (long) ((params.getFactor() * task.getCheckRtNormalized()) + (1 - params.getFactor()) * checkRT);`

可以发现在计算因子以0.75作为默认值时，计算得到的填充频次是1.25. 计算逻辑如下：
令checkRT为x，则下一轮填充频次为：0.75 * x + (1-0.75) * 2 * x = 1.25x

该计算逻辑，通过wireshark可验证

![image](https://github.com/alibaba/nacos/assets/145087580/2ff6ea50-7113-4ba3-bca1-2bd0b3f4407c)

3. 占用内存过多

每分钟占用60+以上的TIME-WAIT socket，也就是说事实上60+的SK && SK_BUFF没有释放，共计消耗400KB。
以2s作为维度，采样10次抓取结果如下：

![image](https://github.com/alibaba/nacos/assets/145087580/0c6b8d8f-c6fd-4ddf-8633-cf68479e1439)

socket占用内存如下：
![image](https://github.com/alibaba/nacos/assets/145087580/8f46e734-e0be-431d-8b4a-e74461e0c0f4)

如果以2C4G作为配置，搭建3节点集群，那么接收500个CP实例时，每个节点会消耗200M内存 ：400K * 500 = 200MB

**Comment by KomachiSion** [comment]
问题1&3 可以修改timewait相关tcp参数， 比如修改timewait回收时间， 和timewait连接复用。

问题2 可以修改 SwitchDomain.HealthParams 修改

**Comment by KomachiSion** [comment]
问题1&3 可以修改timewait相关tcp参数， 比如修改timewait回收时间， 和timewait连接复用。

问题2 可以修改 SwitchDomain.HealthParams 修改

**Comment by poemkcm** [comment]
1. time-wait 连接复用你是指打开tcp_tw_reuse ？

2. 服务端发起探活，能否对特定端口做探活呢？

在HttpHealthCheckProcessor中可以指定端口，tcp探活是否也可以这样做？

在结合每秒固定频率（#3中讨论为什么现在是1s间隔）的情况下，我观察到的现象是服务端每秒会发起短连接，作为探活依据。
这个频次下，我觉得对于协议栈压力有点大了。

3. com.alibaba.nacos.naming.misc.SwitchDomain.TcpHealthParams事实上只约定了最大、最小、因子参数。


`private int max = 5000;   
private int min = 1000;
private float factor = 0.75F;`

如果只是改动factor因子，在网络正常情况下，其实意义不大。结合reEvaluateCheckRT来看

`checkRT = (long) ((params.getFactor() * task.getCheckRtNormalized()) + (1 - params.getFactor()) * checkRT)`

checkRT每次都以上次往返时长代入计算，那么在网络正常的情况下，事实上，上一轮的checkRT与本轮的checkRT相差不大。
我们可以令checkRT为x，因为多项式中以(1-factor)作为因子，所以factor事实上是小于1的实数。

可得出这样的公式： f * x + (1-f) * x = x 。

所以事实上就会以第一次间隔x为基数，一直保持同频率探活。

**Comment by KomachiSion** [comment]
1. 是的
2. 可以，ClusterMetadata中的healthyCheckPort=xxx和useInstancePortForCheck=false指标
3. `        if (checkRT < params.getMin()) {
            checkRT = params.getMin();
        }` 设置最小值应该是有用的，会影响x的值。

**Comment by poemkcm** [comment]
感谢回复1&&2，这两个问题我现在清楚了。

对于3，我的环境服务端是默认配置，所以没有提交配置文件。
翻看TcpHealthParams，发现代码中给了默认值。最小值是1000，最大值是5000.


`private int max = 5000;  private int min = 1000; private float factor = 0.75F;`

我检查了com.alibaba.nacos.naming.healthcheck.v2.processor.HealthCheckCommonV2#reEvaluateCheckRT，确实在代码首尾两侧做了保护，或者说做了边界截断。不过，我一开始提交的wireshark截图，可以证明运行时跑出来的checkRT就是在[1000, 2000] 之间。

结合我上一次推导出的公式，目前可以推断在网络良好的环境下（可以认为本机虚拟机与宿主机通信是最好的网络环境），探测频率确实过于密集了。

如果需要其他日志文件，或是重现步骤，我可以提供。我这边是nacos源码环境，也可以定制化trace/log。

**Comment by poemkcm** [comment]
通过idea我查询TcpHealthParams.setMin()是没有引用的，这里是否能对外暴露配置？
还有个问题，在后续的3.0规划中，持久化实例设计会有大改吗？健康检测会动吗？

**Comment by KomachiSion** [comment]
TcpHealthParams的set方法是给json反序列化使用的， 其他的也一致。

健康检查部分确实有计划重新设计一下， 一方面不应该和类型绑定（持久化非持久化），另一方面是健康检查的配置方式可以优化。

**Comment by poemkcm** [comment]
有以下几个困惑烦扰解答下：

1.如果要在线上调整TcpHealthParams，是否只能通过url: naming/switches？
该接口确实是以反序列化方式灌入字段，但只能全量调整。是否存在单字段调整？

2.线上调整SwitchDomain有官方最佳实践吗？
我昨天看了阿里云专业版，发现商业版本不支持查询SwitchDomain，只提供trace类监控。

如果我使用商业版，是不是就无法自行更改探测频率了？

3.能否在服务端启动时，自行初始化TcpHealthParams参数？
目前在2.2.3中没有找到相关代码，是否支持实现？没有的话，能否提交PR？

4.健康检测不区分实例类型不太理解？
目前存在两种实例类型，2.X又要求service中所有实例类型统一。从这个角度推导，健康检测应该是做分类实现。你说的不和类型绑定，能给个例子展开一下吗？

**Comment by KomachiSion** [comment]
1. 目前只能作为全局变量使用。
2. SwitchDomain都是运维方面的内容，商业化不开放正常，商业化团队会帮助用户管理。如何调整频率之类的，可以提问商业化团队
3. 不需要，这个参数是通过jraft同步并持久化的，变更过后重启自动会加载快照中的值。除非你在变更的时候，加了debug参数，这样仅对本次本节点生效。
4. 非持久化实例固定为心跳/连接检测，不支持主动探测，持久化实例反之。 这是使用方式决定的，非持久化实例需要由客户端自己注册，自己保持活性，一旦不保持，服务端就会移除。 持久化是类似dns的模式，需要运维人员维护添加或移除，因此需要一种探测机制来判断对应ip健康与否。
5. 一个服务同时存在持久化和非持久化本身不合理，什么服务是即持久化又非持久化的，这是互斥的属性。但是其实健康检查本质上和实例的存在可以解耦，类似liveness和readness的存在，liveness是活性探测，对应非持久化的心跳和连接保持（持久化实例永存，不存在liveness）；readness才是健康检查，哪怕心跳在续约，但是可能不主动响应了，这部分其实持久化非持久化都一样。

**Comment by poemkcm** [comment]
我理解要在nacos中重新定义liveness && readiness。

对于持久实例与非持久实例，两者的liveness应该是不同的。

持久实例：实例存储在服务端，但我不知道其节点是否存活，因此我要主动探测。
非持久实例：实例的生命周期无法主动感知，也就是传统意义上的节点续租。

对于readiness，两者的语义是一致的，解决了liveness后，需要由WebClient（目前2.X没有，借用WebFlux概念）暴露端点，实现ready语义。

从这个角度来说，是否可以做以下结论：
1. 2.X目前只能提供liveness probe
2. 持久实例的readiness需要自行解决。即自行开放一个endpoint，由control panel探测。这样不影响后续迭代升级nacos 3.0版本
3. 持久实例探测频率暂时通过SwitchDomain控制
4. 健康检查配置方式2.X还会更改吗？可以提交PR吗

**Comment by KomachiSion** [comment]
nacos的监控检查和k8s中的liveness和readness是不同的， 因为k8s能够对应用节点进行操作（kill， restart，pending）等，而nacos只是一个注册中心，能做的是通知订阅测这个服务的ip可能存在问题。

Nacos未来的改造方向是将  实例数据是否保留 和 实例是否健康 解耦开， 实现类似liveness和readness的功能。

> 2.X目前只能提供liveness probe

非持久化实例提供类似liveness，不提供readness；持久化实例提供类似readness，没有liveness。

> 持久实例的readiness需要自行解决。即自行开放一个endpoint，由control panel探测。这样不影响后续迭代升级nacos 3.0版本

如上，类似liveness需要自行解决，不是类似readness

> 持久实例探测频率暂时通过SwitchDomain控制

是的

> 健康检查配置方式2.X还会更改吗？可以提交PR吗

 功能上不会做大修改，小的优化点和bugfix会合入，大的功能性修改和配置方式修改应该会放在3.0上做。

**Comment by poemkcm** [comment]
我本来想提交一个PR，尝试改进SwitchDomain的配置方式，目前看来先放一放吧。

但我对于liveness && readiness的表述还是有些困惑：

> Nacos未来的改造方向是将 实例数据是否保留 和 实例是否健康 解耦开

持久实例目前已经保存在jraft里，健康检测是由IpPortBasedClient发起，存储与健康检测已经是隔离的。jraft是sofa团队提供的类库，并不是早期自己实现的raft代码。

**Comment by KomachiSion** [comment]
感觉你把所有东西耦合在一起理解了。

1. jraft还是自己实现的raft，都是raft， raft只是一致性协议，并不是存储协议，也就是说，数据通过那种一致性协议进行了同步。
2. 数据都是存储在内存/磁盘中。只是存储在磁盘时，对应的是持久化数据，使用了raft协议来更高优先级保证一致性（CP），而内存数据用Distro协议同步，优先保证可用性（AP）。
3. 实例数据是否保留 和 实例是否健康 目前没有解耦。 也就是粗暴的直接根据是否是持久化服务区分为`实例数据是否保留(非持久化）` 和 `实例是否健康（持久化）`， 未来的方向是无论是否持久化，都有这两个部分内容，只不过 非持久化的服务是否保留利用连接和心跳自动移除，持久化服务必须要使用者通过API来控制移除； `实例是否健康` 则完全基于用户配置来进行检查（tcp端口探测也好，http协议检查也好，其他可拓展的方式检查也好）。

**Comment by poemkcm** [comment]
我看了第三点终于明白了你之前说的解耦开的意思，确实大多数人就是根据运行行为和捕捉到的trace来区分持久实例 && 非持久实例。似乎持久实例就是要持久化，非持久实例存在ram model里。两者的健康检测自然也要按照这个来做区分。

**Comment by huang714669** [comment]
> nacos的监控检查和k8s中的liveness和readness是不同的， 因为k8s能够对应用节点进行操作（kill， restart，pending）等，而nacos只是一个注册中心，能做的是通知订阅测这个服务的ip可能存在问题。
> 
> Nacos未来的改造方向是将 实例数据是否保留 和 实例是否健康 解耦开， 实现类似liveness和readness的功能。
> 
> > 2.X目前只能提供liveness probe
> 
> 非持久化实例提供类似liveness，不提供readness；持久化实例提供类似readness，没有liveness。
> 
> > 持久实例的readiness需要自行解决。即自行开放一个endpoint，由control panel探测。这样不影响后续迭代升级nacos 3.0版本
> 
> 如上，类似liveness需要自行解决，不是类似readness
> 
> > 持久实例探测频率暂时通过SwitchDomain控制
> 
> 是的
> 
> > 健康检查配置方式2.X还会更改吗？可以提交PR吗
> 
> 功能上不会做大修改，小的优化点和bugfix会合入，大的功能性修改和配置方式修改应该会放在3.0上做。

想了解一下3.0版本计划什么时候上线?  我们使用临时实例，也想做一些上报机制的扩展，比如集成一个http /health接口。
