### ISSUE TITLE
nacos 开源版本迭代问题

### ISSUE THREAD

**Issue by flying-2077** [alibaba/nacos#11246]
1、目前看到很多pr都合并到了develop分支上，但是稳定版本发版周期很长，而且看只是挑选了develop的个别pr合并到稳定版本。如果发现稳定版本的bug，并提交了pr，急需要上线，就需要被迫使用develop分支吗？

2、为什么很多pr merge到develop后，只是选择几个pr的代码merge到主干分支？

**Comment by KomachiSion** [comment]
1. 你说的稳定版本是指什么？ main分支吗？ 每次发布都会把develop整个分支合并到main分支，然后在main分支进行tag和发布。
2. develop分支就是主干分支， main分支只作为发布和记录。

**Comment by KomachiSion** [comment]
2.3.0因为涉及到很多大改动，确实时间比较久， 中间没有发布fix版本主要是因为没有大的block issue。

如果对应的bug很影响您使用， 又等不急新的版本， 可以在fork分支中，将fix的pr和commit cheery-pick进去，然后先自行打包部署使用，等后续新版本发布后， 再酌情升级即可。

**Comment by JoinFyc** [comment]
> 2.3.0因为涉及到很多大改动，确实时间比较久， 中间没有发布fix版本主要是因为没有大的block issue。
> 
> 如果对应的bug很影响您使用， 又等不急新的版本， 可以在fork分支中，将fix的pr和commit cheery-pick进去，然后先自行打包部署使用，等后续新版本发布后， 再酌情升级即可。

我怎么找到 v2.2.3版本，git tag没有，拉master fork下吗？
