### ISSUE TITLE
raft日志清理

### ISSUE THREAD

**Issue by yuanyong1014** [alibaba/nacos#11245]
nacos：2.2.0
系统：centos7.5
/data/protocol/raft/naming_persistent_service_v2/log
/data/protocol/raft/naming_instance_metadata/log
/data/protocol/raft/naming_service_metadata/log
上述3个目录下的LOG.old.xxxxxxxxx 文件是否有机制去删除，如果没有我能不能写个定时去删除

**Comment by KomachiSion** [comment]
duplicate with #11145
