### ISSUE TITLE
About openapi - Publish configuration

### ISSUE THREAD

**Issue by allegrox** [alibaba/nacos#11242]
**Describe the bug**
From the official documentation, an example of using openapi to publish a nacos configuration is as follows:
curl -d 'dataId=nacos.example' \
  -d 'group=DEFAULT_GROUP' \
  -d 'namespaceId=public' \
  -d 'content=contentTest' \
  -X POST 'http://127.0.0.1:8848/nacos/v2/cs/config'
where "contentTest" is the content to be published.
When the content I actually publish contains the "&" symbol, the content is truncated and the result is uncontrollable. What method should I use to wrap this content?
Please give an example. I am using curl to work in a shell program.

**Desktop (please complete the following information):**
 - OS:  centos 7.9
 - Version nacos-server 2.2
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
https://nacos.io/en-us/docs/open-api.html

**Comment by KomachiSion** [comment]
please do urlencode if your content has special words for url.
