### ISSUE TITLE
docker环境下 升级到nacos2.2.3版本配置开启鉴权并配置了 相关鉴权内容为什么登录密码还是nacos

### ISSUE THREAD

**Issue by uncle-pier** [alibaba/nacos#11257]
配置如下图
![1697531643562](https://github.com/alibaba/nacos/assets/13642516/16cd5eef-e306-4949-b137-e4c67d2d32a3)

**Comment by KomachiSion** [comment]
建议仔细阅读文档内容， 分清用户名密码，及IDENTITY相关信息的不同。
