### ISSUE TITLE
can not to bind aliyun ECS machine Intranet address

### ISSUE THREAD

**Issue by AllenJol** [alibaba/nacos#1125]
my environment:
CentOS 7.4 x86_64
nacos version is: nacos-server-0.9.0
I used Standalone mode and when I want to bind aliyun ECS Intranet address，italway bind 0.0.0.0,Although I restart the nacos server, it still bind 0.0.0.0。
the parameter i add to nacos config is: nacos.inetutils.ip-address=my_address:port

Chinese：
我的环境是：
CentOS 7.4 x86_64
nacos版本是:nacos-server-0.9.0
我在nacos配置文件中添加nacos.inetutils.ip-address=阿里云ECS内网地址：port 以后，重启nacos服务，他仍然监听0.0.0.0的地址，请问如何才能正确让他变成监听内网地址呢？是不是参数不对？如果不对，请问应该是加哪个参数才能解决？谢谢

**Comment by nkorange** [comment]
@AllenJol 哪个配置文件？谁监听？

**Comment by AllenJol** [comment]
更改的配置文件是：application.properties,想让8848端口监听阿里云内网地址而不是0.0.0.0 
现在只能监听0.0.0.0 如下：
tcp        0      0 0.0.0.0:8848            0.0.0.0:*

请求您的帮助。谢谢

**Comment by nkorange** [comment]
@AllenJol 设置server.address为内网IP属性试试

**Comment by AllenJol** [comment]
换成server.address是可以了非常感谢您的帮助。
