### ISSUE TITLE
Derby initialization fail due to timeout set too short

### ISSUE THREAD

**Issue by bs352** [alibaba/nacos#11252]
**Describe the bug**
When launching on a machine with slower disk, the embeded derby database could timeout during initialization.

**Expected behavior**
Leave enough time for derby to finish initialization. Currently the default timeout is 3 seconds.

**Actually behavior**
Connection to derby is attempted and timed-out before derby could finish initialization.
Exception thrown: org.apache.derby.iapi.error.StandardException: Login timeout exceeded.

**How to Reproduce**
When running using docker, try set the environment variable:
-e JAVA_OPT="-Ddb.pool.config.connectionTimeout=1000"
this will further reduce the timeout from 3s to 1s, and the instance is very likely to fail.

**Environment:**
 - OS: Kylin V10
 - CPU: Hygon C86 7285
 - Version: Nacos-server 2.2.3-slim image from dockerhub

**Additional context**
I noticed in commit "a09058169ceb2cf742f53c71361a285e413993c0", the default connection timeout defined in class "DataSourcePoolProperties" is changed from 30s to 3s, is this change intented?
If not, can I change it back to 30s? I am willing to submit a merge request.

Full startup failure log is attached:
[nacos-bug.log](https://github.com/alibaba/nacos/files/12918868/nacos-bug.log)

**Comment by KomachiSion** [comment]
The old change should has background and change to 3s by default, I think the env with lower disk, it should be change the configuration in the special env, not change the default value.

**Comment by bs352** [comment]
Just noticed. the default application.properties file in this repository have a timeout default value of 30000ms, which make sense, the old change from 30s to 3s in code is always overriden by the config file in default setup. I really couldn't see the background of changing the timeout value to 3s in code.

After further digging, the issue is caused by the fact that, the application.properties in nacos-docker repository does not have this timeout default value set, which exposed the changed timeout value in code:
https://github.com/nacos-group/nacos-docker/blob/master/build/conf/application.properties

**Comment by KomachiSion** [comment]
Welcome to submit PR to enhance the docker images parameters and add the document to describe it.

**Comment by bs352** [comment]
> Welcome to submit PR to enhance the docker images parameters and add the document to describe it.

PR submmited. feedback welcome.
https://github.com/nacos-group/nacos-docker/pull/370
