### ISSUE TITLE
当本地禁用日志配置时，不需要加载日志nacos-{xx}.xml配置

### ISSUE THREAD

**Issue by llm163520** [alibaba/nacos#11250]
nacos-client目前会强制加载日志配置(nacos-{xx}.xml)，无法通过配置关闭；
日志输出为：
Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from null
示例配置：
nacos:
  logging:
    default:
      config:
        enabled: false
    config:

期望支持通过配置关闭强制加载

**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by llm163520** [comment]
`nacos:
  logging:
    default:
      config:
        enabled: false
    config`

**Comment by KomachiSion** [comment]
nacos-client 在jar中自带了配置文件，即使加载失败也不会影响应用本身的启动和加载，无非是导致日志打印到业务日志中。

客户端日志作为nacos-client的最直观手段，正常情况下会被单独维护在额外的目录中，必须要开启，暂不支持，也暂无计划支持关闭。

**Comment by llm163520** [comment]
不是，我是说明显知道这个异常了。从代码的健壮性上来说就不需要去执行这个动作了
该处代码有两个问题：


***@***.***
 
发件人： 杨翊 SionYang
发送时间： 2023-10-18 15:07
收件人： alibaba/nacos
抄送： limliu; Author
主题： Re: [alibaba/nacos] 当本地禁用日志配置时，不需要加载日志nacos-{xx}.xml配置 (Issue #11250)
nacos-client 在jar中自带了配置文件，即使加载失败也不会影响应用本身的启动和加载，无非是导致日志打印到业务日志中。
客户端日志作为nacos-client的最直观手段，正常情况下会被单独维护在额外的目录中，必须要开启，暂不支持，也暂无计划支持关闭。

**Comment by llm163520** [comment]
1、



***@***.***
 
发件人： 杨翊 SionYang
发送时间： 2023-10-18 15:07
收件人： alibaba/nacos
抄送： limliu; Author
主题： Re: [alibaba/nacos] 当本地禁用日志配置时，不需要加载日志nacos-{xx}.xml配置 (Issue #11250)
nacos-client 在jar中自带了配置文件，即使加载失败也不会影响应用本身的启动和加载，无非是导致日志打印到业务日志中。
客户端日志作为nacos-client的最直观手段，正常情况下会被单独维护在额外的目录中，必须要开启，暂不支持，也暂无计划支持关闭。

**Comment by KomachiSion** [comment]
1. 描述异常内容不完整， 如何触发？ 操作流程是什么？
2. 你说明显知道这个异常，我实际使用中，包括大量客户实际使用中都没有遇到这个异常，有没有可能是你的环境，或者你的app本身存在某种冲突或者错误使用导致的？

**Comment by KomachiSion** [comment]
3. 你所说的禁用本地日志，禁用的是你应用的日志吗？ 前面也解释过， nacos-client需要日志，用于客户端测问题的排查，作为最有效的排查手段，目前不提供方式进行禁止。

**Comment by llm163520** [comment]
1、描述异常内容不完整， 如何触发？ 操作流程是什么？
我本地已经有自己的日志配置文件，切正常加载；目前看日志输出提示加载失败（nacos-{xx}.xml）; 翻阅实际的代码存在缺陷，已调整
2、你说明显知道这个异常，我实际使用中，包括大量客户实际使用中都没有遇到这个异常，有没有可能是你的环境，或者你的app本身存在某种冲突或者错误使用导致的？
我理解是加载日志这块的处理逻辑缺陷导致，已提交PR；可以参阅
3、你所说的禁用本地日志，禁用的是你应用的日志吗？ 前面也解释过， nacos-client需要日志，用于客户端测问题的排查，作为最有效的排查手段，目前不提供方式进行禁止。
可以忽略禁用这个说法，其实就是代码缺陷；其具体缺陷，参考之前的反馈

**Comment by KomachiSion** [comment]
PR能否关联一下这个issue

**Comment by llm163520** [comment]
> PR能否关联一下这个issue

https://github.com/alibaba/nacos/pull/11251
