### ISSUE TITLE
win11 Unicode UTF-8  启动不了

### ISSUE THREAD

**Issue by paint404** [alibaba/nacos#11259]
![image](https://github.com/alibaba/nacos/assets/61998207/5e837075-37e1-445c-a411-e0a4f10e0939)
打开这个功能的时候就启动不了，java 8 ，win11 Nacos v2.2.3

**Comment by KomachiSion** [comment]
启动不了错误是什么？
看描述 Unicode UTF8本身是windows的beta功能， 可能其本身存在问题。

**Comment by miaozikeji** [comment]
启动窗口一闪就没了，都没有错误信息

**Comment by KomachiSion** [comment]
日志呢？

**Comment by miaozikeji** [comment]
logs文件夹都不会生成，是不是可以理解压根就没有到写日志就已经崩溃了，对了我的nacos在中文路径下，是不是编码导致中文路径读不到，直接死翘翘了

**Comment by tomlikeyou** [comment]
中文路径可能会对此产生影响，可以尝试安装路径为英文重试

**Comment by paint404** [comment]
没错，换个英文路径就ok

**Comment by tomlikeyou** [comment]
没问题的话可以issue关闭
