### ISSUE TITLE
many errors like  NamingProxy 400，pls help

### ISSUE THREAD

**Issue by shaoxuanshuo** [alibaba/nacos#11271]
issue:
only one pod got these error like  NamingProxy 400， and java code almost work well 

error log：
{"time":"2023-10-20 09:19:43.276","logger":"com.alibaba.nacos.client.naming","level":"ERROR","thread":"com.alibaba.nacos.naming.beat.sender","stack":"com.alibaba.nacos.client.naming.net.NamingProxy:617[callServer]","stackTrace":"com.alibaba.nacos.api.exception.NacosException: <!doctype html><html lang=\"en\"><head><title>HTTP Status 400 – Bad Request</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:541)\n\tat com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)\n\tat com.alibaba.nacos.client.nam

nacos version:
2.2.1  
k8s version
v1.18.9

config:
            - name: NACOS_ADDR
              value: >-
                nacos-0.nacos-headless.nacos.svc.cluster.local:8848,nacos-1.nacos-headless.nacos.svc.cluster.local:8848,nacos-2.nacos-headless.nacos.svc.cluster.local:8848
            - name: NACOS_NAMESPACE
              value: 4bc376a8-22a9-4c89-acff-c8448448b6b0
            - name: NACOS_USERNAME
              value: bap
            - name: NACOS_PASSWORD
              value: Es389di4vJP

Many thanks，
 shaoxuanshuo

**Comment by KomachiSion** [comment]
No enough informaton, please check network, node status, logs and request content

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
