### ISSUE TITLE
2.2.3利用登录绕过bug后，停留在首页未跳转至登录界面

### ISSUE THREAD

**Issue by Devil-QAQ** [alibaba/nacos#11277]
2.2.3利用登录绕过bug后，停留在首页未跳转至登录界面
![image](https://github.com/alibaba/nacos/assets/79952322/fc20c1cb-4dbb-4299-8ea1-1b7a03b255a8)

**Comment by Sle09** [comment]
通过Nacos默认token.secret.key漏洞，绕过登录后，访问集群管理-节点列表，仍然可以访问到数据，这种没办法修改了吗？
![image](https://github.com/alibaba/nacos/assets/79521887/fc063db6-973c-4c68-9d17-89d02c17c099)

**Comment by KomachiSion** [comment]
没看懂，是不是没开启鉴权功能？

**Comment by Sle09** [comment]
> 没看懂，是不是没开启鉴权功能？
鉴权功能开了，服务也正常启用了，通过Nacos默认token.secret.key漏洞确实访问不到大多数的后台数据，但就是有这几个功能点（命名空间、节点列表）还是可以查看，危害总归还是有点的。

**Comment by WangPei0316** [comment]
想问下您这个操作环境是啥样的，是chrome浏览器+Windows操作系统吗？

**Comment by WangPei0316** [comment]
> > 没看懂，是不是没开启鉴权功能？
> > 鉴权功能开了，服务也正常启用了，通过Nacos默认token.secret.key漏洞确实访问不到大多数的后台数据，但就是有这几个功能点（命名空间、节点列表）还是可以查看，危害总归还是有点的。

@Sle09 您这个操作环境和步骤是啥样的，我这边试了下无法复现，但是有一个客户可以稳定复现出来。

**Comment by Sle09** [comment]
> > > 没看懂，是不是没开启鉴权功能？
> > > 鉴权功能开了，服务也正常启用了，通过Nacos默认token.secret.key漏洞确实访问不到大多数的后台数据，但就是有这几个功能点（命名空间、节点列表）还是可以查看，危害总归还是有点的。
> 
> @Sle09 您这个操作环境和步骤是啥样的，我这边试了下无法复现，但是有一个客户可以稳定复现出来。

我是Windows平台搭建的Nacos，然后操作步骤就是正常的替换返回包。

HTTP/1.1 200
Date: Thu, 10 Nov 2022 01:27:16 GMT
Content-Type: application/json
Content-Length: 13
Connection: close
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Security-Policy: script-src 'self'
Server: elb

{"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYxODEyMzY5N30.nyooAL4OMdiByXocu8kL1ooXd1IeKj6wQZwIH8nmcNA","tokenTtl":18000,"globalAdmin":true}

**Comment by KomachiSion** [comment]
获取命名空间list的接口是公开接口，无需鉴权（否则控制台功能受影响）

节点列表鉴权问题已被修复 #10587
