### ISSUE TITLE
nacos-peer-finder-plugin can support ARM platform.

### ISSUE THREAD

**Issue by ahululu** [alibaba/nacos#11282]
When I used helm to deploy a nacos cluster on the ARM platform, I got an error, as follows:
`exec /install.sh: exec format error
`
**values.yaml**

```bash
global:
  mode: cluster
#  mode: cluster

############################nacos###########################
namespace: nacos
nacos:
  image:
    repository: nacos/nacos-server
    tag: v2.1.1-slim
    pullPolicy: IfNotPresent
  plugin:
    enable: true
    image:
      repository: nacos/nacos-peer-finder-plugin
      tag: 1.1
      pullPolicy: IfNotPresent
```
   Help，Thanks very much

**Comment by KomachiSion** [comment]
What's the nacos-peer-finder-plugin? 

I has no idae for this plugin, should you found out the community of provided nacos-peer-finder-plugin?

**Comment by ahululu** [comment]
The plugin config comes from this helm file: https://github.com/nacos-group/nacos-k8s/blob/master/helm/values.yaml.
Finally solved the problem:
1. build https://github.com/kubernetes-retired/contrib/blob/master/peer-finder/peer-finder.go
`go mod init peer-finder && go mod tidy  && GOARCH=arm64 GOOS=linux go build peer-finder.go`
2. The file generated above replaces this file https://github.com/nacos-group/nacos-k8s/blob/master/plugin/peer/peer-finder
3. Build Docker  https://github.com/nacos-group/nacos-k8s/tree/master/plugin
4. Modify the https://github.com/nacos-group/nacos-k8s/blob/master/helm/values.yamlplugin image and replace it with the self-packaged image above
