### ISSUE TITLE
nacos控制台访问404

### ISSUE THREAD

**Issue by wx24736** [alibaba/nacos#11288]
nacos版本: 2.1.2
部署集群: ack 1.24.6-aliyun.1
控制台地址: /nacos/#/configurationManagement?dataId=&group=&appName=&namespace=&pageSize=&pageNo=
问题现象: 控制台访问刷新几次就提示404
![image](https://github.com/alibaba/nacos/assets/41844950/b343756c-52e3-4bf3-8ad2-a049cf2eed28)
![image](https://github.com/alibaba/nacos/assets/41844950/e851a293-bac4-4fa2-a18b-71d527f50666)

**Comment by KomachiSion** [comment]
这应该是您创建的nginx代理的问题，和nacos无关，需要您自行排查
