### ISSUE TITLE
如何使用prometheus监控注册到nacos的服务在线状态？

### ISSUE THREAD

**Issue by duskxiaohefen** [alibaba/nacos#11289]
最近因为注册到nacos的服务无故掉线，导致业务故障，遂需要监控注册到nacos在线状态，但是官方现有文档中无此指标。

**Comment by Daydreamer-ia** [comment]
注册到nacos的服务对nacos来讲算业务数据，并不算指标吧。如果有些服务频繁掉线，或许你可以自己根据轨迹追踪插件做一个辅助监控。文档：[轨迹追踪](https://nacos.io/zh-cn/docs/v2/plugin/trace-plugin.html)

**Comment by KomachiSion** [comment]
Nacos提供的指标应该是nacos自身的相关内容，比如服务数，实例数，配指数。

单个服务的注册，下线，注销都是业务数据，无法做到独立统计。的确可以根据需求实现一个 追踪的插件来看某个服务的上下线情况。

但是这种无故的下线，通常都和应用本身有关。还是要着重排查为什么应用会和nacos断链，或者不再续约。
