### ISSUE TITLE
analysis service leak memory

### ISSUE THREAD

**Issue by xiaoyuwang1987** [alibaba/nacos#11280]
![image](https://github.com/alibaba/nacos/assets/24749103/e25c1ca8-ef4b-48bc-84a4-99b73c5d66d0)
![image](https://github.com/alibaba/nacos/assets/24749103/dd0b1a0c-b9e1-43bc-880f-12b37da68ca6)

![image](https://github.com/alibaba/nacos/assets/24749103/f1e7356a-885f-44e3-8b31-67e9d4de9708)

**Comment by KomachiSion** [comment]
From the memory dump, it seems no any leak memory,  the totak memory only use 76MB, Please check your own app.
