### ISSUE TITLE
nacos logback warn

### ISSUE THREAD

**Issue by fgyang** [alibaba/nacos#11285]
我本的的异常为 Load Logback Configuration of Nacos fail, message: Could not initialize Logback Nacos logging from null,最后不是nacos-logback.xml而是一个null,各位大佬知道为什么么？版本为2022.0.0.0-RC2

**Comment by KomachiSion** [comment]
麻烦提供更详细的信息，比如完整的报错堆栈， 复现方式或复现代码

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
