### ISSUE TITLE
Nacos Spring Boot 快速开始，无法读取配置中心的值

### ISSUE THREAD

**Issue by TheMelody** [alibaba/nacos#11284]
官方文档地址，[https://nacos.io/zh-cn/docs/quick-start-spring-boot.html](https://nacos.io/zh-cn/docs/quick-start-spring-boot.html)

完全按照这个文档来的，pom.xml中的版本，和官方的[示例工程](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-boot-example/nacos-spring-boot-config-example)的版本保持一致。

一开始使用最新的版本，无法获取，后面降级到和官方的[示例工程](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-boot-example/nacos-spring-boot-config-example)的版本一致的版本。

结果：
无法获取nacos中配置的数据值，是我食用方式不对吗？

**Comment by 985492783** [comment]
可以贴一个demo出来吗

**Comment by TheMelody** [comment]
> 可以贴一个demo出来吗

Demo地址：[https://wwbl.lanzout.com/iFS8X1csas2h](https://wwbl.lanzout.com/iFS8X1csas2h)

**我本地的效果如下**：

https://github.com/alibaba/nacos/assets/9635441/e5d99986-0917-4b1e-8e88-22106abf60d6

**Comment by 985492783** [comment]
你使用了springboot3.x，支持3.0的springboot还没发版，你可以试试降到2.x或者使用springcloudAlibaba，那边有可能已经支持了，可以去看下，另外如果使用springbootstarter建议使用最新版，前面版本跟文档对不上

**Comment by TheMelody** [comment]
> 你使用了springboot3.x，支持3.0的springboot还没发版，你可以试试降到2.x或者使用springcloudAlibaba，那边有可能已经支持了，可以去看下，另外如果使用springbootstarter建议使用最新版，前面版本跟文档对不上

好了，提个小建议：如果版本不匹配建议SDK抛一个正确的异常提示；
