### ISSUE TITLE
Druid读取数据库配置异常

### ISSUE THREAD

**Issue by BrotherJie** [alibaba/nacos#11283]
我使用nacos 2.2.3的集群，数据库连接池使用druid 1.2.11，数据库的密码加密后存放在配置文件里，程序可以正常启动，但是运行一段时间后会报下面的错误。
[Druid-ConnectionPool-Create-531378187] ERROR com.alibaba.druid.pool.DruidDataSource - [run, 2815]- create connection SQLException, url ....... , errorCode 1045, state 28000 java.sql.SQLException: Access denied for user 'root'@'10.188.36.60'(using password: YES)。
数据库的配置文件并没有做过变更，且数据库没有动过，已排查mysql和druid的连接池也没有线程过多的问题

**Comment by BrotherJie** [comment]
不用Nacos用传统的配置可以连上，但是配置文件放nacos也能连上，神奇的是偶尔会出现上面的报错并不是一直会出现

**Comment by stone-98** [comment]
我觉得这应该不是nacos的问题~

**Comment by stone-98** [comment]
是指运行期间偶尔出现还是说启动的时候偶尔出现呢？

> 不用Nacos用传统的配置可以连上，但是配置文件放nacos也能连上，神奇的是偶尔会出现上面的报错并不是一直会出现

**Comment by stone-98** [comment]
要是启动的时候没有报错，那说明连接上了，并且运行期间配置文件没有做过变更，那么nacos不会对mysql的用户信息做任何改动，所以我觉得这应该不是nacos的原因。

**Comment by BrotherJie** [comment]
启动的时候没有报错可以连上，就是运行一段时间不定期会出现上面的错误，这个期间没有变更过数据库。而且一旦出现上面的问题，就会持续报错，重启应用后这个问题又解决了。类似的问题其他人也出现过，也都是靠重启才解决问题，我想是不是nacos对加密的密码做了什么处理

**Comment by KomachiSion** [comment]
nacos对配置内容不会做任何处理， 如果你有做加密，也是自行通过加密插件或在应用中自己做的。

而且刚启动能连上，说明nacos没有问题， 已经完成了配置下发的工作， 后续运行时nacos是不参与的。

应该不是nacos的问题，需要自行排查了
