### ISSUE TITLE
建议去掉contextPath默认值contextPath=/nacos或默认为/

### ISSUE THREAD

**Issue by slatonwu** [alibaba/nacos#11292]
当nacos服务没有指定contextPath，即直接通过域名访问时，如： https://xxx.com     nacos-client默认会在 https://xxx.com 后面加上/nacos 导致请求nacos配置时报403或其他错误，目前发现的有：
1、使用dubbo时，在dubbo.registry下是没有配置contextPath的地方的，必须在启动的时候通过System.setProperty("contextPath","/"); 指定。
2、使用nacos-config-spring-boot-starter 时必须配置acos.config.context-path=/ 才能正常使用。
不能默认为/  有cotextPath的时候再配置吗？特别是使用dubbo等第三框架时没有配置contxtPath的地方，特别不友好，而且文档上也没有说明会给定默认值

**Comment by slatonwu** [comment]
有没有contextPath应该让用户来选择是否需要，而不是默认给定一个，这样更符合使用习惯

**Comment by KomachiSion** [comment]
nacos-client在内部已经封装完成对/nacos的补充，对用户使用而言，不涉及所谓的contextPath添加等问题， 只有对此contextPath有特殊要求的用户，自行修改就好。
