### ISSUE TITLE
java.net.ConnectException: no available server, currentServerAddr

### ISSUE THREAD

**Issue by XiaoLi3538** [alibaba/nacos#11290]
项目启动可以正常启动，nacos也可以正常访问，但是如果闲置一两个小时不操作项目和nacos就会报这个错误，这是因为啥？

**Comment by stone-98** [comment]
no available server. 大概率是网络抖动导致请求`Server`超时导致的把。

**Comment by stone-98** [comment]
按道理就算是一段时间内网络抖动，出现请求`Server`超时的情况，当网络稳定后，他自己也会恢复。

**Comment by KomachiSion** [comment]
这要看你部署的环境是不是有什么闲置回收资源之类的操作，比如长时间没请求之类进入休眠，缩容等导致。
