### ISSUE TITLE
Nacos1.4.1修复未授权访问后无法打开客户端----Unable to open client after fixing unauthorized access

### ISSUE THREAD

**Issue by zhangyutian999** [alibaba/nacos#11308]
我们使用的版本是1.4.1，修改了Nacos配置文件中的application.properties配置文件nacos.core.auth.enabled=true，开启服务身份识别功能，再次打开nacos客户端报错404。

We used version 1.4.1, which modified the configuration file application.properties.nacos.core.auth.enabled=true , enabled the service identity function, and opened the nacos client again with error 404.

现在我们无法确定是哪里出现了问题，希望大家可以解决我们的问题。

Now we are not sure where the problem is, we hope you can solve our problem.

PS:Nacos服务端正常启动 
PS:The Nacos server starts normally.

**Comment by KomachiSion** [comment]
404和开启鉴权功能无关，且信息过少，无法排查。
