### ISSUE TITLE
注释太少,可不可以多加点注释

### ISSUE THREAD

**Issue by lianglinux5** [alibaba/nacos#11319]
最近在看nacos源码,看能不能多加点注释

**Comment by 985492783** [comment]
静态方法和接口会有doc，类也有doc，业务逻辑可能不会加注释

**Comment by KomachiSion** [comment]
建议可读性的代码来替代注释， 注释可能会被漏掉修改， 但是代码本身可读的话更重要。

对实际暴露出的API，比如客户端中的ConfigService和NamingService，会写比较详细的注释来说明使用。
其他的内部逻辑更倾向于用可读性代码替代注释。
