### ISSUE TITLE
nacos SwitchRefresher类中的Swith开关配置

### ISSUE THREAD

**Issue by lpfCode** [alibaba/nacos#11314]
背景想利用本地缓存做nacos容灾
我有个问题
该文件下00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00可以通过nacos配置写入初始值来指定0或者1吗？我看了源码 没找到写入的地方 想确认下。

**Comment by KomachiSion** [comment]
不支持，这个文件需要容灾时显示写入，且不是有nacos-client写入，而是由用户自行创建文件并写入内容。

因为是纯粹的容灾，用于人工干预的，所以只能有人工来控制，不能有nacos-client自行控制。
