### ISSUE TITLE
How to Init Configuration of Microservice by Yaml Files?

### ISSUE THREAD

**Issue by alanthssss** [alibaba/nacos#11322]
When deliver offline clusters to customer,  I should initlize configurations of microserves.
I want to know how could I init these configurations by a `Configuration as Code` way instead of `export and import database`
I could not find the way out if it was already exists.
Need help, Thanks.

**Comment by lianglinux5** [comment]
view  com.alibaba.nacos.example.ConfigExample  see if it is

**Comment by alanthssss** [comment]
> view com.alibaba.nacos.example.ConfigExample see if it is

@lianglinux5 thank you.
The example seems not cover my requirement.

**Comment by alanthssss** [comment]
I found out that I can export yaml configurations at Naocs's namespace page.
I need the code way to finish the configing instead of the UI way.

**Comment by KomachiSion** [comment]
the configuration format is not relative by Nacos.  Nacos only save them as text and push it to client.

Client only compare the md5 and notify your listeners when md5 is diff.

So you should parse the config by yourself or using some app framework to help you do this.

**Comment by KomachiSion** [comment]
If you want to publish configs by client, you can use publish api.

**Comment by cofecatt** [comment]
Yaml may not be able to set default values, you should set default values through code

**Comment by alanthssss** [comment]
@KomachiSion @cofecatt 
Thanks for all the above feedback. 
Actually Nacos works well on code client by java/go or other sdk.
Originally, I need setup plenty of default values in some enterprise scenarios.
Cheers.

**Comment by KomachiSion** [comment]
I think it's not nacos' problem, nacos is the program help your app to do service manager and config manager, but the default value of you app config is your app custom logic, I think you should do it in app or in other program.

**Comment by alanthssss** [comment]
@KomachiSion thanks for feedback

Actually its original requirement is how to init nacos's configs productively in enterprise scenarios, not noly for default configs.
