### ISSUE TITLE
无法修改配置，今天上来不能修改了，以往都可以

### ISSUE THREAD

**Issue by Ch2EnAo** [alibaba/nacos#11320]
![image](https://github.com/alibaba/nacos/assets/44825004/8c0200a9-7264-4e29-bf80-f17e0a050dce)

**Comment by KomachiSion** [comment]
如果版本没有变更过， 没有重新发布过的话， 可能是你的浏览器有问题，可以尝试清理浏览器缓存后重试或者换个浏览器。

也可能是配置中有什么特殊符号，导致ui解析出错了。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
