### ISSUE TITLE
NacosNamingService initialization problem

### ISSUE THREAD

**Issue by jiangminbing** [alibaba/nacos#1132]
NacosNamingService 初始化方法中，默认读取缓存中的数据
       this.cacheDir = System.getProperty("com.alibaba.nacos.naming.cache.dir");
        if (StringUtils.isEmpty(this.cacheDir)) {
            this.cacheDir = System.getProperty("user.home") + "/nacos/naming/" + this.namespace;
        }
假如有两个服务A1 端口：1111，A2 端口：2222，注册serviceName为A， nacos 服务端器重启前没有删除原来服务，这样子缓存没有被清除。A2服务停用并弃用，在使用selectOneHealthInstances读取A服务的时候会读到端口2222，只能通过手动找到对应路径将缓存进行删除。

**Comment by nkorange** [comment]
@jiangminbing 可以配置namingLoadCacheAtStart属性来决定启动时是否从缓存读取数据。
