### ISSUE TITLE
我的数据源还没初始化完Nacos 就上线了

### ISSUE THREAD

**Issue by Yule-Momoko** [alibaba/nacos#11323]
**Describe the bug**
我的数据源还没初始化完Nacos 就上线了 怎么办
**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
duplicated with #11327
