### ISSUE TITLE
nacos-server-2.2.1 启动后频繁fullgc

### ISSUE THREAD

**Issue by vanto-** [alibaba/nacos#11324]
version：nacos-server-2.2.1  nacos-client-1.4.4
jvm -xms 34576m -xmx 34576m

nacos-server fullgc，After dumping the JVM memory, if you find a large number of LongPollingService$ClientLongPolling objects  

![image](https://github.com/alibaba/nacos/assets/3469401/0d829fc9-f74d-4b6c-96ff-006095d90f71)

**Comment by KomachiSion** [comment]
LongPolling costing many memory is expected, Please upgrade to 2.X client to use long connection to release more performance.
