### ISSUE TITLE
nacos 在db数据源没初始化完就把实例注册上去了

### ISSUE THREAD

**Issue by Yule-Momoko** [alibaba/nacos#11327]
**Describe the bug**

nacos 在db数据源没初始化完就把实例注册上去了

**Expected behavior**
在db数据源完全初始化完在将实例注册到nacos

**Actually behavior**
A clear and concise description of what you actually to happen.
无
**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Nacos nacos' problem, when to register is your app behavior.
