### ISSUE TITLE
nacos 如何设置 通过 /health 来做健康检查

### ISSUE THREAD

**Issue by Yule-Momoko** [alibaba/nacos#11328]
**Describe the bug**

**Expected behavior**
nacos 如何设置 通过 /health 来做健康检查
**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Can't get the key issue point.

What's the health check target? Nacos server, app instance?
