### ISSUE TITLE
nacos在Linux服务器正常启动，且可以正常注册应用，但访问首页显示空白页

### ISSUE THREAD

**Issue by mayadexintu** [alibaba/nacos#11329]
在官方github分别下载了nacos-server-2.0.1.tar.gz、2.0.4.tar.gz、2.2.0.tar.gz、2.2.3.tar.gz等几个版本安装尝试，每个版本都能正常安装、运行、注册应用，但访问首页时显示空白页面，报错提示访问：/nacos/js/main.js失败，未能获取到对应的js信息，请问使用什么方式可以解决这个问题？

**Comment by KomachiSion** [comment]
估计和你的浏览器或者部署环境有关，看下是否有防火墙之类的东西拦截了js的获取。

**Comment by mayadexintu** [comment]
> 估计和你的浏览器或者部署环境有关，看下是否有防火墙之类的东西拦截了js的获取。

可能是环境的问题，但是找不到解决方向，系统上防火墙没开启，然后除了main.js的请求外，其他js都能正常获取

**Comment by mayadexintu** [comment]
> 估计和你的浏览器或者部署环境有关，看下是否有防火墙之类的东西拦截了js的获取。

原因找到了，是系统的内存少的问题，内存不足导致图形界面无法打开，多谢你的回答
