### ISSUE TITLE
nacos客戶端和服務端的版本兼容性

### ISSUE THREAD

**Issue by alexwylp** [alibaba/nacos#11331]
版主好，最近准备对nacos集群进行升级：
1）1.4.2希望升到1.4.6，客户端普遍采用1.4.1、1.4.2
2）2.2.0希望升到2.2.3，客户端普遍采用2.2.0

想咨询一下：
1）上述情况，服务端补丁版本升级（第三位），对同代较老的客户端是否兼容，如：
      客户端1.4.1能兼容访问服务端1.4.6，客户端2.2.0能兼容访问服务端2.2.3
2）是否有nacos客户端和服务端的兼容性匹配表可供参考？

谢谢！

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-compatibility

**Comment by alexwylp** [comment]
版主好，大方向的兼容性清楚了，2.x的服务端兼容1.x的客户端。就是小版本内的兼容性如何（尤其是1.4.x版本内）？
如1.4.1/1.4.2的客户端，是否能兼容访问1.4.6的服务端？

谢谢！

**Comment by KomachiSion** [comment]
兼容

**Comment by alexwylp** [comment]
谢谢！

**Comment by alexwylp** [comment]
谢谢！
