### ISSUE TITLE
Unable to refresh the configuration on the corporate application

### ISSUE THREAD

**Issue by a1242902560** [alibaba/nacos#11333]
**Describe the bug**
5 hours after the application starts, the nacos configuration is changed, and the application cannot listen for updates

**Expected behavior**
config refresh

**Actually behavior**
config not refresh

**How to Reproduce**
**nacos client version: 2.0.2**

The company's test, integration, and pre-shipment environment is configured with only **one** cpu core
in this method: com.alibaba.nacos.common.utils.ThreadUtils#getSuitableThreadCount(int) ,Only 1 core can be returned

**class field: com.alibaba.nacos.client.config.impl.ConfigTransportClient#executor**
This thread pool is a periodic thread pool, if there is only one thread, once one method is blocked, it will block other threads from executing
However, this thread pool is mainly responsible for two tasks, one token refresh and one configuration listening
**Configuration listening is an endless loop, and token refreshes are blocked in single-core pods**

![image](https://github.com/alibaba/nacos/assets/128970488/13c9fece-1b06-469e-bcaf-8bea8825b4d6)

![image](https://github.com/alibaba/nacos/assets/128970488/44d201b3-ea37-4ff7-8ee8-3cc3184f72c8)

**Comment by a1242902560** [comment]
公司的测试、集成、预发几乎所有的应用都只有1个核心，线程池核心线程数只有1个。配置刷新线程是一个end loop,会阻塞token的刷新线程

**Comment by KomachiSion** [comment]
Please upgrade to new version, the problem maybe fixed already

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
