### ISSUE TITLE
nacos2.2.1 版本部署完后集群无法选举

### ISSUE THREAD

**Issue by llylhz** [alibaba/nacos#11349]
![image](https://github.com/alibaba/nacos/assets/42568584/00c1e809-b9be-4594-8b0f-cf1748901d22)
![image](https://github.com/alibaba/nacos/assets/42568584/be06161d-de4e-4632-93e7-b5a6e81a7735)

**Comment by KomachiSion** [comment]
域名差个 `.`

**Comment by llylhz** [comment]
这个问题我在其他问题下面发现了，目前已经成功了，谢谢，我很好奇为什么加点，我环境变量重新定义域名不好使



---- 回复的原邮件 ----
| 发件人 | 杨翊 ***@***.***> |
| 日期 | 2023年11月09日 16:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alibaba/nacos] nacos2.2.1 版本部署完后集群无法选举 (Issue #11349) |

域名差个 .

**Comment by Zhang123-bot1** [comment]
please assign to me
