### ISSUE TITLE
linux安装部署完成后，本地页面/nacos能访问，但是springboot无法连接，切换多个版本都不行

### ISSUE THREAD

**Issue by hjtjava** [alibaba/nacos#11347]
nacos放在本机运行是可以正常springboot连接的，放在linux服务器上无法连接，但是通过域名+端口+/nacos能看到管理界面，服务器防火墙未开启

**Comment by hjtjava** [comment]
nginx配置如下
upstream cluster {
        server 192.168.88.123:8848;
}
 server {
       listen     21002;
        server_name localhost;
        location / {
                proxy_pass http://cluster;
        }
        location /nacos {
                proxy_pass http://cluster/nacos;
        }

    }

**Comment by 985492783** [comment]
2.x版本需要开放9848端口的tcp长连接。

**Comment by hjtjava** [comment]
> 2.x版本需要开放9848端口的tcp长连接。

意思是还需要开放一个9848端口吗，这个9848可以是其他端口指定到9848吗 还是必须同名的端口

**Comment by 985492783** [comment]
默认是nacos端口号+1000，可以通过nacos.server.grpc.port.offset这个配置修改，建议直接将用同名的指定

**Comment by KomachiSion** [comment]
文档中有说明，请先阅读文档
