### ISSUE TITLE
Delete Throw Exception statement.

### ISSUE THREAD

**Issue by 20144101037** [alibaba/nacos#11359]
**Describe the bug**
Delete Throw Exception statement.
**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by realJackSun** [comment]
Could you plz explain your question more in detail?
