### ISSUE TITLE
spring boot and nacos Could not resolve placeholder

### ISSUE THREAD

**Issue by vansAir** [alibaba/nacos#11351]
springboot version 2.7.16
nacos version 2.0.3
nacos-config-spring-boot-starter version 0.2.12
Able to obtain configuration files
But value$ cannot get the value
The value in Figure 4 comes from the printed nacosConfig data in com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder#doBuild

![1](https://github.com/alibaba/nacos/assets/37164988/b71e448f-0634-482b-89c9-1ccf5987aaa5)
![5](https://github.com/alibaba/nacos/assets/37164988/c0310a0f-30e6-442f-a13b-a4851f987913)
![2](https://github.com/alibaba/nacos/assets/37164988/cb501221-c149-4d1c-af40-ed1f470648d8)
![3](https://github.com/alibaba/nacos/assets/37164988/12a32282-d3dc-4fb0-ac9b-0243bfa29c3c)
![4](https://github.com/alibaba/nacos/assets/37164988/06c60366-15f9-45d0-a4ff-76908c2205c6)

springboot 版本2.7.16
nacos版本2.0.3 
nacos-config-spring-boot-starter版本0.2.12
能获取配置文件
但是value$无法获取值
 图4的值来自于打印的com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder#doBuild内的nacosConfig数据

**Comment by Dios314** [comment]
同样的问题
生产环境和测试环境一套配置
测试环境可以获取配置
生产环境无法
一路追踪
发现是
RpcClient.request()去获取配置的时候
返回
![img_v3_0251_2bf1d104-75ed-4da4-a207-ad7622b9f6fg](https://github.com/alibaba/nacos/assets/45736371/7f80286e-3968-45bd-9d08-db31856f04de)
然而我访问nacos后端页面的时候是有的

**Comment by KomachiSion** [comment]
自行确认命名空间，group，dataId，地址是否正确。
从描述上看应该是这几项有一个是错的问题。

**Comment by Dios314** [comment]
这几项已经反复确认过很多次是没有问题的
同样的环境 同样的配置
生产环境一套 测试环境一套
我把nacos地址改成测试环境就可以成功读取配置
改成生产环境就读取不到

**Comment by vansAir** [comment]
> 自行确认命名空间，group，dataId，地址是否正确。 从描述上看应该是这几项有一个是错的问题。

![6](https://github.com/alibaba/nacos/assets/37164988/992c6ad7-db3a-45e3-892c-c6f62e633738)
springboot单体项目必须配置以上 配置项,且以上配置项默认为false,文档里面只让配置了address @Dios314 这样配置试一下吧 不行就没办法了

**Comment by vansAir** [comment]
> 这几项已经反复确认过很多次是没有问题的 同样的环境 同样的配置 生产环境一套 测试环境一套 我把nacos地址改成测试环境就可以成功读取配置 改成生产环境就读取不到



> 这几项已经反复确认过很多次是没有问题的 同样的环境 同样的配置 生产环境一套 测试环境一套 我把nacos地址改成测试环境就可以成功读取配置 改成生产环境就读取不到

group 如果namespace和id不一样 要使用id作为namespace配置

**Comment by Dios314** [comment]
这些问题早就排查过
你没理解我的问题
我这里有两套一模一样的环境
生产和测试
nacos地址改为测试环境就可以成功读取到配置
改为生产就不可以 
两者的不同只是nacos地址不同
不是你所说的这些常见的错误

**Comment by Dios314** [comment]
包括 用户名 密码 版本 命名空间 配置文件
全部是一摸一样的

**Comment by vansAir** [comment]
> 包括 用户名 密码 版本 命名空间 配置文件 全部是一摸一样的

2.x版本需要开放9848端口的tcp长连接。有没有可能生产环境9848端口被屏蔽了

**Comment by Dios314** [comment]
> > 包括 用户名 密码 版本 命名空间 配置文件 全部是一摸一样的
> 
> 2.x版本需要开放9848端口的tcp长连接。有没有可能生产环境9848端口被屏蔽了

如果被屏蔽了
是无法请求成功的
很显然是请求成功了

**Comment by AyaittoBestCouple** [comment]
> > > 包括 用户名 密码 版本 命名空间 配置文件 全部是一摸一样的
> > 
> > 
> > 2.x版本需要开放9848端口的tcp长连接。有没有可能生产环境9848端口被屏蔽了
> 
> 如果被屏蔽了 是无法请求成功的 很显然是请求成功了

大佬碰到和你类似的问题了，想问问解决了嘛？怎么解决的？
