### ISSUE TITLE
服务未启动也会自动注册一个实例

### ISSUE THREAD

**Issue by wufy1113** [alibaba/nacos#11353]
![Uploading image.png…]()
没办法删除,不能使用,启动nacos自动注册

**Comment by wufy1113** [comment]
![image](https://github.com/alibaba/nacos/assets/55790831/d892d6d9-89cb-4401-aa15-1d0aa56e8b89)

**Comment by 985492783** [comment]
环境提供一下，注册方式是什么

**Comment by KomachiSion** [comment]
nacos不会自动注册，启动有说明这个服务一直开着，自动发心跳，请自查。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
