### ISSUE TITLE
The best project!!!

### ISSUE THREAD

**Issue by yuanpli** [alibaba/nacos#11357]
Cannot startup one-click with docker or docker-compose
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by stone-98** [comment]
如果你认为有改进的空间，欢迎提出，甚至可以参与改进，而非仅仅提出批评。

**Comment by zsh2401** [comment]
建议关闭，最垃圾的issue。
请详细描述你的问题，而不是一味发泄情绪，否则大家只会觉得是你自己技不如人。
