### ISSUE TITLE
注册服务已关闭但nacos一直不下线

### ISSUE THREAD

**Issue by wade-bigdata** [alibaba/nacos#11350]
**Describe the bug**
微服务架构，部署在k8s上，当k8s下线服务后， 偶尔会出现如下现象：下线服务一直存在nacos上，除非重启nacos服务才会消失。

**Desktop (please complete the following information):**
 - OS: LINUX
 - Version: docker镜像 nacos-server:v2.2.3, nacos-client 2.2.4

**Additional context**

**Comment by xiaoyuwang1987** [comment]
我是整台服务器重启也碰到这个问题，有人说要30分钟后server端才能看到服务不在

**Comment by KomachiSion** [comment]
可能是断网的bug，可以在nacos-server上netstat看下是否有对应的9848连接， 如果没有的话。说明不是不是bug，应该是部署的问题。需要自查部署是否有问题。

**Comment by KomachiSion** [comment]
duplicate #11258
