### ISSUE TITLE
Nacos集群节点和服务频繁上下线问题

### ISSUE THREAD

**Issue by NotTellY0u** [alibaba/nacos#11356]
Nacos服务端从1.4.2升级到1.4.6，Spring Boot的Nacos-Client版本依赖是1.3.1，6月份升级之后，近几天出现Nacos集群节点和服务频繁上下线问题，日志中看不到异常信息，是Nacos服务端和客户端版本不兼容吗？还有有其他可能性？希望大佬解答一下

**Comment by KomachiSion** [comment]
兼容性没问题，服务频繁上下线说明服务存在稳定性问题了， 比如FullGC， CPU等。 导致心跳断断续续，不稳定。
