### ISSUE TITLE
未登录时候1.4.6还存在sql注入（1.4.6 There is also SQL injection）

### ISSUE THREAD

**Issue by oday-xiexin** [alibaba/nacos#11358]
When the program is not logged in, requesting this interface can obtain data ip:8848/nacos/v1/cs/ops/derby?sql=select%20*%20from%20users

**Comment by Daydreamer-ia** [comment]
It may be fixed in the later version, i cannot reproduce it in v2.3.0-BETA. Please upgrade nacos-server then retry.

**Comment by realJackSun** [comment]
did this fixed your question? https://github.com/alibaba/nacos/pull/4245

**Comment by oday-xiexin** [comment]
> did this fixed your question? #4245

I don't think so. I think the code is 1.41 integration, but I am already using version 1.4.6

**Comment by KomachiSion** [comment]
It's a feature of maintain derby datasource, not injection.

If no this feature and api, you has `no way` to connect to derby database to query original data and maintain database.

derby is not like MySQL or other standarad database, you can't use any outer connection to operation.

If you don't want this feature, please remove this api in your fork.
