### ISSUE TITLE
没有pod了，服务建康实例数多个，且一直显示上线

### ISSUE THREAD

**Issue by airacle** [alibaba/nacos#11362]
K8S部署的nacos 2.3.3，客户端是nacos 1.x，K8S部署的服务在preStart调更新接口enabled=true  [因为这个问题](https://github.com/alibaba/nacos/issues/11315)（原来有preStop里调更新接口做服务下线enabled=false），现在发现服务pod都没有了，但是实例数有8个，而且一直都在。应该在调试preStart时调enabled=true，但容器没正常拉起，重试了几次导致的。
1、问题是pod一直都没有，没有心跳nacos不会自动注销服务吗？
![image](https://github.com/alibaba/nacos/assets/1285903/1092b7c7-5f23-4e51-8702-04f172c809db)

![image](https://github.com/alibaba/nacos/assets/1285903/85e96498-6627-4f62-9f03-a3888f41b2cf)
![image](https://github.com/alibaba/nacos/assets/1285903/2ecb78ad-23eb-4a1e-8aba-a6fc076e9bcb)

2、全部点“下线”，再点删除也不行。临时实例，没有pod了，也没法在客户端调注销接口。要怎么处理才能删除？
![image](https://github.com/alibaba/nacos/assets/1285903/8e8d448a-1302-4a7d-964c-657492d1ce7d)

**Comment by Daydreamer-ia** [comment]
首先 `nacos-server` 临时实例是在客户端一致保持心跳来续约才会存在服务端的，否则在超时后会被自动剔除的。而服务在实例都掉完后也会被删除。可以检查一下提供注册的那个 `client` 端是否真的关了或者看一下 `nacos-server` 的 `access-log` 看是不是还有心跳的请求来到服务端。

**Comment by KomachiSion** [comment]
1. pod存不存在在nacos测不感知， nacos只看是否有连接和心跳。
2. 上线下线按钮是运维操作，只是标记成是否在线，和连接心跳无关。
3. 无法删除说明连接（心跳）还在，需要先找到它，然后从客户端测进行注销

**Comment by airacle** [comment]
pod不存在了，还能发心跳？在三个nacos下，日志里也没看到发心跳的
![image](https://github.com/alibaba/nacos/assets/1285903/97f81608-a310-4a30-825c-983a98356132)


整个集群就没这个pod ip了
![image](https://github.com/alibaba/nacos/assets/1285903/f37b929f-1b8e-4fbc-bd1c-528752f3523d)



![image](https://github.com/alibaba/nacos/assets/1285903/5cb4c1c0-6412-4d34-b521-2fed1e6a3c33)
删除pvc和nacos的文件，重新部署过nacos，没有pod在nacos服务列表中还一直在。

**Comment by KomachiSion** [comment]
心跳日志是debug日志，你需要打开debug才能看到
pod看不到不代表pod不存在， 有一种pod叫幽灵pod， 意思就是pod看似销毁了，且pod的service都移除了，访问不通，但是pod对应的进程还在node中运行。

**Comment by airacle** [comment]
确实是进程还在，kill掉就好了，谢谢。
