### ISSUE TITLE
dubbo3 使用 rest 协议，传递 URL 路径参数时带中文，会进行 URL 编码，且不会自动解码

### ISSUE THREAD

**Issue by wiscloud** [alibaba/nacos#11364]
![image](https://github.com/alibaba/nacos/assets/52514676/d685aa79-0045-45bb-ab71-3e0cd1659f4d)
调用时获取到的是经过 url 编码后的数据，返回的也是经过 url 编码后的数据

**Comment by Daydreamer-ia** [comment]
`nacos` 不做调用的编解码啊，只负责提供服务调用地址而已
