### ISSUE TITLE
Nacos supports local storage to remove mysql

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#1136]
## Issue Description

Nacos supports local storage to remove mysql，because mysql deployment costs are relatively high

### Describe what happened (or what feature you want)
Use derby+raft  replace mysql

### Describe what you expected to happen
Nacos supports local storage to remove mysql

**Comment by wfnuser** [comment]
I see the LocalDataSourceServiceImpl already implement DataSourceService using derby, so what's this issue all about?
To remove the mysql part completely?

**Comment by liupengpop** [comment]
Which version of MySQL are you planning to remove?
