### ISSUE TITLE
Flaky test in api Module caused by Nondeterministic ObjectMapper Ordering

### ISSUE THREAD

**Issue by Sujishark** [alibaba/nacos#11369]
**Describe the bug**

Creating this issue to address 3 tests:

```
com.alibaba.nacos.api.config.ability.ServerRemoteAbilityTest.testSerialize
com.alibaba.nacos.api.config.remote.response.ConfigChangeBatchListenResponseTest.testSerializeSuccessResponse
com.alibaba.nacos.api.config.remote.request.ConfigBatchListenRequestTest.testSerialize
```

**Expected behavior**

The assertion at the above mentioned tests are expected to succeed irrespective of the arrangement of the JSON string.
This was found by using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.

**Actually behavior**
Encountered the following errors while using NonDex tool:

```
com.alibaba.nacos.api.config.ability.ServerRemoteAbilityTest.testSerialize
org.junit.ComparisonFailure: expected:<{"[supportRemoteConnection":false,"grpcReportEnabled":tru]e}> but was:<{"[grpcReportEnabled":true,"supportRemoteConnection":fals]e}>
	at com.alibaba.nacos.api.config.ability.ServerRemoteAbilityTest.testSerialize(ServerRemoteAbilityTest.java:55)

```

```
java.lang.AssertionError
	at com.alibaba.nacos.api.config.remote.response.ConfigChangeBatchListenResponseTest.testSerializeSuccessResponse(ConfigChangeBatchListenResponseTest.java:46)

```

```
java.lang.AssertionError
	at com.alibaba.nacos.api.config.remote.request.ConfigBatchListenRequestTest.testSerialize(ConfigBatchListenRequestTest.java:37)

```

I've a fix ready for this. Can I proceed and create PR ?

**How to Reproduce**

The above mentioned logs were encountered while using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool tool. The following code is for the test - com.alibaba.nacos.api.config.ability.ServerRemoteAbilityTest.testSerialize:

```
cd nacos
mvn install -pl api -am -DskipTests
mvn -pl api edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.alibaba.nacos.api.config.ability.ServerRemoteAbilityTest#testSerialize
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: Sonoma 14.0
 - Maven Version: 3.6.3
 - Module: api
 - SDK: Original

**Comment by Daydreamer-ia** [comment]
i will resolve it

**Comment by Daydreamer-ia** [comment]
hi, pr welcome

**Comment by Sujishark** [comment]
Greetings,

Thankyou :)

I've made the changes. Please look into
https://github.com/alibaba/nacos/pull/11373.

Is it necessary for me to sign the CLA ?

Thanks and regards,
Sujithra Rajan.

**Comment by Sujishark** [comment]
> hi, pr welcome

Greetings, the proposed solution is as follows: (https://github.com/alibaba/nacos/pull/11373 is the pull request for the same.)
Proposed fixes addresses the non-determinism.

1. ObjectMapper.writeValueAsString() internally calls [getDeclaredFields()](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--) which doesn't maintain order. I used MapperFeature.SORT_PROPERTIES_ALPHABETICALLY to enable alphabetical ordering of elements of 'json' for it to be constant all the time. 
2. Sorted the expected value in assert statements.

Can you please review the same and approve?

**Comment by Daydreamer-ia** [comment]
> > hi, pr welcome
> 
> Greetings, the proposed solution is as follows: (#11373 is the pull request for the same.) Proposed fixes addresses the non-determinism.
> 
> 1. ObjectMapper.writeValueAsString() internally calls [getDeclaredFields()](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--) which doesn't maintain order. I used MapperFeature.SORT_PROPERTIES_ALPHABETICALLY to enable alphabetical ordering of elements of 'json' for it to be constant all the time.
> 2. Sorted the expected value in assert statements.
> 
> Can you please review the same and approve?

wait for @KomachiSion

**Comment by Sujishark** [comment]
Sure Thankyou :)
