### ISSUE TITLE
阿里云购买了ARM倚天版服务器无法启动nacos，附加解决方案

### ISSUE THREAD

**Issue by ahgaoyong** [alibaba/nacos#11367]
解决方案是升级jar包，rocksdbjni-7.7.3.jar升级到rocksdbjni-7.10.2.jar，

在源码的最外层的pom.xml文件的700行左右添加依赖
`<dependency>
                <groupId>org.rocksdb</groupId>
                <artifactId>rocksdbjni</artifactId>
                <version>7.10.2</version>
            </dependency>`
然后重新编译
本人折腾了一天了，终于是搞定了，客户为了最大化省钱，必须要买arm倚天版的服务器，折腾死我了

自己编译nacos的方法：[https://blog.csdn.net/qq_41684621/article/details/131587402](https://blog.csdn.net/qq_41684621/article/details/131587402)

百度找到了相关资料，说是rocksdbjni不支持，尝试自己升级版本，编译后竟然可以了
**其实主要是因为rocksdb不支持，不过rocksdb新版本已经做了支持了，希望官方可以考虑同步升级该jar包**

以下资料来自百度相关
![image](https://github.com/alibaba/nacos/assets/13848697/db3d9fad-c976-4c2c-889f-9adbb89f9d62)

![image](https://github.com/alibaba/nacos/assets/13848697/5bff4dc5-2cd3-4f32-b3e9-63db7f46988f)

**Comment by KomachiSion** [comment]
rocksdb 是从jraft依赖进来的， 新版本应该已经是升级过jraft和对应的rocksdb了，应该已经支持arm架构了。欢迎测试一下

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
