### ISSUE TITLE
nacos服务启动失败，报错 librocksdbjni.dll

### ISSUE THREAD

**Issue by mmtou** [alibaba/nacos#11360]
nacos启动报错，problematic frame：
   [librocksdbjnixxxx.dll]
![error](https://github.com/alibaba/nacos/assets/12110944/eaaa0cbe-65dd-457e-b13f-215fa2461960)

## 版本
**2.2.1**

## 问题描述
第一次启动没问题，电脑关机后再启动，有时服务停了再启动就会出现；电脑上vc库都是正常的。

## 临时解决方案
删除data目录

**Comment by KomachiSion** [comment]
环境问题，需要自行解决

**Comment by mmtou** [comment]
@KomachiSion 如果是环境问题，第一次启动为什么没有问题呢？删除data目录后再启动也没有问题啊

**Comment by flyerxp** [comment]
一样，第一次没问题，第二次就不行了。
