### ISSUE TITLE
Springboot-admin cannot monitor services registered in nacos with context-path

### ISSUE THREAD

**Issue by pengls** [alibaba/nacos#1137]
springboot-admin：
@Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(value = "spring.cloud.nacos.discovery.watch.enabled", matchIfMissing = true)
    public NacosWatch nacosWatch(NacosDiscoveryProperties nacosDiscoveryProperties) {
        return new NacosWatch(nacosDiscoveryProperties);
    }

服务A使用context-path: /xx
在springboot-admin控制台可以看到这个服务，但是是无法监控的，标红了

**Comment by fangjian0423** [comment]
Could you please provide a project that reproduces the issue?
