### ISSUE TITLE
服务端的udp发送和客户端的定时更新的时间问题

### ISSUE THREAD

**Issue by nameIsNoPublic** [alibaba/nacos#11371]
A调用B， B下线后。A的本地缓存还没变更，nacos也没主动通知(或者Client端的udp由于某种原因没有接收到)， 此时A访问B会报错，这种情况有没有好的解决方案？或者已经有了解决方案

**Comment by KomachiSion** [comment]
升级2.0以上版本，使用grpc双向流进行推送
