### ISSUE TITLE
Detected an HTTP host header attack vulnerability in the target URL

### ISSUE THREAD

**Issue by oday-xiexin** [alibaba/nacos#11375]
我用的是1.4.6版本，安测扫描：检测到目标URL存在http host头攻击漏洞
http://内网ip:8848/nacos(HOST)www.fff.com
为了方便的获得网站域名，开发人员一般依赖于HTTP Host header。例如，在php里用_SERVER["HTTP_HOST"]。但是这个header是不可信赖的，如果应用程序没有对host header值进行处理，就有可能造成恶意代码的传入。web应用程序应该使用SERVER_NAME而不是host header。 
作为使用者该如何解决这个漏洞？
Detected an HTTP host header attack vulnerability in the target URL
Http://intranet ip: 8848/nacos (HOST) www.fff.com
For the convenience of obtaining website domain names, developers generally rely on HTTP Host headers. For example, in PHP, using_ SERVER ["HTTP_HOST"]. However, this header is not trustworthy, and if the application does not process the host header value, it may cause malicious code to be passed in. Web applications should use SERVER_ Name instead of host header.
How can users solve this vulnerability?

**Comment by KomachiSion** [comment]
Nacos不会使用host header去执行一些操作，本身不存在这个问题， 如果你觉得有这方面风险， 可以自行搜索spring boot应用如何避免host header问题，然后进行spring的设置修改。

**Comment by KomachiSion** [comment]
No more response from author, It seems not nacos' problem.
