### ISSUE TITLE
namespace copy fail 

### ISSUE THREAD

**Issue by huangkemingyyds** [alibaba/nacos#11374]
**Describe the bug**
![image](https://github.com/alibaba/nacos/assets/66153067/a1345ad4-6849-40ab-9dbb-634efecbe683)

使用 localhost + ip访问是可以复制的， 内网 + ip 就出现这个问题了

**Comment by KomachiSion** [comment]
这说明你的网络有拦截，自查网络设置及网络环境。 Nacos代码上不会阻止。

**Comment by KomachiSion** [comment]
localhost走的是回环地址，不会走到你的网络环境上，所以能复制。 使用内网地址就会走到你网络环境上，如果你们公司/家里路由器/防火墙有相关设置，会被拦截等等。

**Comment by huangkemingyyds** [comment]
公司内网有防火墙
