### ISSUE TITLE
Naocs does not notify clients when the value is set to 0

### ISSUE THREAD

**Issue by bingtianyiyan** [alibaba/nacos#11387]
**Describe the bug**
Naocs does not notify clients when the value is set to 0, and clients can receive change notifications as long as the set value is greater than or less than 0

nacos version 2.0.3 
client is use github.com/nacos-group/nacos-sdk-go/v2/clients 

<img width="512" alt="1700120492491" src="https://github.com/alibaba/nacos/assets/48984656/25fd3d01-ed66-4a65-9024-75ec25bfe8cd">

**Comment by KomachiSion** [comment]
I think it's not nacos' problem, nacos do not parse the the config content, only compare md5. You say value is not 0, the app can work, but 0 is not work, it might be your app ignore the 0 value and only read the not 0 values.
