### ISSUE TITLE
nacos控制台更新配置项，无法自动刷新

### ISSUE THREAD

**Issue by zqszzs** [alibaba/nacos#11386]
项目启动可以从nacos拉取到最新配置，但是启动后在nacos服务页面更新配置项，客户端无法自动刷新
客户端未出现  ”o.s.cloud.endpoint.event.RefreshEventListener“ 更新日志
修改后通过调用http://127.0.0.1:8088/actuator/refresh可以更新

spring-cloud-alibaba版本:     com.alibaba.cloud:spring-cloud-alibaba-commons:jar:2021.0.1.0
nacos版本:                              com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:jar:2021.0.1.0

配置代码：
![image](https://github.com/alibaba/nacos/assets/38514696/4569ef46-d660-4a89-a60c-213f23e83358)

application.yaml
![image](https://github.com/alibaba/nacos/assets/38514696/5fba278b-3675-42be-9c4d-baade8de5843)

nacos配置：
![image](https://github.com/alibaba/nacos/assets/38514696/e4c2fd89-37bb-4c04-87e8-ecb2dd23a62e)

服务端更新配置后，但是调用spring actuator/refresh接口，可以发现配置发生变化，但是客户端并未更新，也没有日志输出
![image](https://github.com/alibaba/nacos/assets/38514696/c9099de5-4390-4e17-88e3-e357b5721490)

**Comment by 985492783** [comment]
请根据springcloud alibaba文档进行配置刷新，
optional:nacos:common.yaml?refresh=true

**Comment by zqszzs** [comment]
> 项目启动可以从nacos拉取到最新配置，但是启动后在nacos服务页面更新配置项，客户端无法自动刷新 客户端未出现 ”o.s.cloud.endpoint.event.RefreshEventListener“ 更新日志 修改后通过调用[http://127.0.0.1:8088/actuator/refresh可以更新](http://127.0.0.1:8088/actuator/refresh%E5%8F%AF%E4%BB%A5%E6%9B%B4%E6%96%B0)
> 
> spring-cloud-alibaba版本: com.alibaba.cloud:spring-cloud-alibaba-commons:jar:2021.0.1.0 nacos版本: com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:jar:2021.0.1.0
> 
> 配置代码：

**Comment by zqszzs** [comment]
![image](https://github.com/alibaba/nacos/assets/38514696/5f02e545-2c9d-46ce-862e-1a5e952e02b6)
加上了还是没作用

**Comment by 985492783** [comment]
可以在springcloud alibaba这个仓库提issue
