### ISSUE TITLE
dm database dont throw DuplicateKeyException

### ISSUE THREAD

**Issue by limng06** [alibaba/nacos#11389]
**Describe the bug**
```java
    public void insertOrUpdate(String srcIp, String srcUser, ConfigInfo configInfo, Timestamp time,
            Map<String, Object> configAdvanceInfo, boolean notify) {
        try {
            addConfigInfo(srcIp, srcUser, configInfo, time, configAdvanceInfo, notify);
        } catch (DuplicateKeyException ive) { // Unique constraint conflict
            updateConfigInfo(configInfo, srcIp, srcUser, time, configAdvanceInfo, notify);
        }
    }
```
i'm using dm-db, when insert failed ,dm dont throw DuplicateKeyException which make update failed.
 
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; 违反表[CONFIG_INFO]唯一性约束条件[UK_CONFIGINFO_DATAGROUPTENANT]; nested exception is dm.jdbc.driver.DMException: 违反表[CONFIG_INFO]唯一性约束条件[UK_CONFIGINFO_DATAGROUPTENANT]

**Comment by limng06** [comment]
nacos-datasource-plugin 虽然做了 但是本身的限制还有很多，对dm oracle等数据库的限制依然很多，想要光通过 nacos-datasource-plugin适配几乎式不可能的，比如  oracle，和 dm（oracle兼容）下  insert '' 空字符串在oracle下会同等与null，所以很多查询都做不了，现在暴露的plugin接口，很难扩展。

**Comment by KomachiSion** [comment]
duplicate with #10353

**Comment by KomachiSion** [comment]
> nacos-datasource-plugin 虽然做了 但是本身的限制还有很多，对dm oracle等数据库的限制依然很多，想要光通过 nacos-datasource-plugin适配几乎式不可能的，比如 oracle，和 dm（oracle兼容）下 insert '' 空字符串在oracle下会同等与null，所以很多查询都做不了，现在暴露的plugin接口，很难扩展。

这个是因为oracle不支持，应该想办法在插件中做兼容转换，比如insert为空字符串的时候，改成一个特殊字符、或者查询的时候如果是空字符串，条件应该是is Null或同等条件。

**Comment by KomachiSion** [comment]
如果觉得不好适配， 那么具体是哪些地方不好适配， 有什么解决方案吗？
