### ISSUE TITLE
nacos-1.4.6版本在windows下修改配置文件始终不生效

### ISSUE THREAD

**Issue by Alleyf** [alibaba/nacos#11399]
**Describe the bug**
**nacos-1.4.6版本在windows下修改配置文件始终不生效，人就使用target目录下的默认配置，无法以application.properties文件的新配置启动。**

**Expected behavior**
修改application.properties文件的端口以进行集群部署

**Actually behavior**
修改端口失败，还是默认运行在8848端口

**How to Reproduce**

1. windows下：

修改bin目录下的**startup.cmd**文件：
将：`set "NACOS_CONFIG_OPTS=--spring.config.additional-location=optional:%CUSTOM_SEARCH_LOCATIONS%"`
改为：`set "NACOS_CONFIG_OPTS=--spring.config.additional-location=%CUSTOM_SEARCH_LOCATIONS%"`

2. lunux下修改对应**startup.sh**配置即可

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/10526

**Comment by KomachiSion** [comment]
Welcome PR to v1.x-develop

**Comment by DiligenceLai** [comment]
After modification, the problem has been solved. I deployed Nacos cluster locally for testing, and all nodes in the cluster performed normally.
![44a7ba1a91fa537401201d506254302](https://github.com/alibaba/nacos/assets/96920907/f695e7a8-509c-4ae3-ae3d-e77d9751c7b3)
