### ISSUE TITLE
Identifying Microservices in the Project

### ISSUE THREAD

**Issue by OguzcanOzdemir** [alibaba/nacos#11395]
Hello, I'm exploring the project and noticed it includes several small software components and microservices. Could you please help identify which components are specifically microservices? This information will be very helpful for my understanding of the project's architecture. Thank you!

**Comment by KomachiSion** [comment]
The project is very simple for using.

1. the main components is only `server` and `client`.
2. server has two main feature `naming` which is for service discovery and `config` for configuration management.
3. the `server` can be run with most easily with [quick start](https://nacos.io/en-us/docs/v2/quickstart/quick-start.html).
4. the `client` can be run with most easily with [example](https://github.com/alibaba/nacos/tree/v1.x-develop/example/src/main/java/com/alibaba/nacos/example)
5. the `naming` feature is likely `eureka`, one microservice clients register some services to `server` and other client subscribe these services and get the real `IP` of these service, then the client can call the `services` by self.
6. the `config` feature is likely `configserver` of spring cloud, the app maintainer can change the configuration of microservice in console, and the program will listen the configuration from server and get the new configuration.
