### ISSUE TITLE
请问构建nacos集群时，通过VIP+nginx构建性能好还是直接注册到集群性能好？

### ISSUE THREAD

**Issue by qq670176019** [alibaba/nacos#11398]
集群方式一：直接注册到nacos集群，并用逗号连接
集群方式二：使用nginx对N个nacos进行反向代理，8848端口以及9848端口都要反向代理，然后程序注册到这个VIP中
问题：请问构建nacos集群时，通过VIP+nginx构建性能好还是直接注册到集群性能好？官方推荐哪一种方式？

**Comment by 985492783** [comment]
直连性能肯定更好，但是节点替换麻烦，第二种可以屏蔽掉nacos ip＋port的变化

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。

**Comment by qq670176019** [comment]
> 直连性能肯定更好，但是节点替换麻烦，第二种可以屏蔽掉nacos ip＋port的变化

谢谢

**Comment by KomachiSion** [comment]
如果nginx的设置合理，且机能不存在瓶颈的话， 性能不会差太多，毕竟nginx本身的性能很高。

但是需要有nginx能维护能力和排查问题的能力。否则不如直连简单粗暴。

但是通过vip来管理的话，确实能够减少置换/扩/缩容导致的业务测变更压力，最终决定用那种方式需要您自己评估下。

**Comment by qq670176019** [comment]
> 如果nginx的设置合理，且机能不存在瓶颈的话， 性能不会差太多，毕竟nginx本身的性能很高。
> 
> 但是需要有nginx能维护能力和排查问题的能力。否则不如直连简单粗暴。
> 
> 但是通过vip来管理的话，确实能够减少置换/扩/缩容导致的业务测变更压力，最终决定用那种方式需要您自己评估下。

谢谢您的回复！
现在用的是VIP方式，把N个nacos的8848端口和9848端口分别进行了反向代理，nginx的worker_progress和worker_connections等参数优化之后，性能瓶颈很高，也进行了压测，是可以的；我们线上业务用的是阿里云，如果想要方便扩展和维护，我感觉用上阿里云的负载均衡是一个不错的选择。
