### ISSUE TITLE
Nacos 2.2.4 没有安装包吗？

### ISSUE THREAD

**Issue by liaozan** [alibaba/nacos#11392]

**Comment by xiohuchi** [comment]
同问：Nacos 2.2.4 没有安装包？

**Comment by liaozan** [comment]
> 同问：Nacos 2.2.4 没有安装包？

2.2.4 server 没有升级，修复的是 client 的问题，直接下载 2.2.3 就好了

**Comment by liaozan** [comment]
<img width="892" alt="image" src="https://github.com/alibaba/nacos/assets/26990889/b1573735-3e6a-44c5-aa34-c6099c2da3e4">
