### ISSUE TITLE
mysql nacos_config system lock 偶现，还未找到规律，会占用大量mysql进程

### ISSUE THREAD

**Issue by yangbiyao** [alibaba/nacos#11394]
![image](https://github.com/alibaba/nacos/assets/1548647/cffe10b6-0b28-4e69-a735-73688bc3bcb4)
如图

**Comment by KomachiSion** [comment]
能找到是哪个SQL执行的lock吗？

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
