### ISSUE TITLE
user not found

### ISSUE THREAD

**Issue by dev-123456** [alibaba/nacos#11409]
nacos从1.2.1升级到2.2.3版本，并且设置了用户名密码，curl命令可以带用户名密码调用nacos，但是springcloud应用报user not foud，已经在yml中配置了username和password。

**Comment by YuShiwen** [comment]
Could you please provide the version of springcloud so that I can reproduce it locally and take a look.

麻烦提供一下springcloud的版本，我在本地复现一下看看

**Comment by KomachiSion** [comment]
或者发一下应用日志，spring cloud会打印对应nacos配置到日志中。

**Comment by dev-123456** [comment]
> Could you please provide the version of springcloud so that I can reproduce it locally and take a look.
> 
> 麻烦提供一下springcloud的版本，我在本地复现一下看看

springboot 2.2.4.RELEASE
springcloud 2.1.0.RELEASE

**Comment by KomachiSion** [comment]
> springcloud

这个spring cloud的版本不支持username和password插件， 需要升级

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.

**Comment by Jenfong** [comment]
> nacos从1.2.1升级到2.2.3版本，并且设置了用户名密码，curl命令可以带用户名密码调用nacos，但是springcloud应用报user not foud，已经在yml中配置了username和password。
version mismatch ,need to sync version of  nacos's server and client versions
+ nacos server 
 > I just upgrade to 2.2.3 from 2.1.2
+ nacos client:
    - spring-cloud-starter-alibaba-nacos-config : 2021.0.5.0
    - nacos-client : 2.2.0

error:
13:29:41.241 [main] ERROR c.a.c.n.r.NacosServiceRegistry - [register,81] - nacos registry, gateway register failed..

need update as follow
```yml
        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
          <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.2.3</version>
        </dependency>

```
