### ISSUE TITLE
codeStyle.md Spelling errors

### ISSUE THREAD

**Issue by xw-zzz** [alibaba/nacos#11403]
**Describe the bug**
[https://github.com/alibaba/nacos/blob/develop/style/codeStyle.md]( codeStyle)

checkstyle is right
![image](https://github.com/alibaba/nacos/assets/31612579/fade0c8b-6b74-4927-8d9f-d05e05428048)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
welcome PR
