### ISSUE TITLE
Provide a way to invoke config module inside Nacos

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1141]
## Issue Description

Type: *feature request*

### What feature you want

Config module in Nacos provides RESTful methods for users to store some important K-V data for their applications. And it's also useful for the other modules in Nacos. We want the config module can abstract some bean that can be injected in other modules so the CRUD of configuration can also be invoked by other modules.

**Comment by Albert-Hugo** [comment]
I would like to try this one.

**Comment by nkorange** [comment]
> I would like to try this one.

Great. If you have interest to become a committer of Nacos, add to this Dingding group: 23335652

**Comment by Albert-Hugo** [comment]
> > I would like to try this one.
> 
> Great. If you have interest to become a committer of Nacos, add to this Dingding group: 23335652

Thanks.

**Comment by nkorange** [comment]
@Albert-Hugo Are you working on this issue?

**Comment by KomachiSion** [comment]
duplicate with #3785
