### ISSUE TITLE
Optimize ServiceInfo.validate() to reduce memory usage

### ISSUE THREAD

**Issue by JorringHsiao** [alibaba/nacos#11414]
## Description
Source location [com.alibaba.nacos.api.naming.pojo.ServiceInfo](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/pojo/ServiceInfo.java).

```java
public boolean validate() {
    if (isAllIPs()) {
        return true;
    }
    
    if (hosts == null) {
        return false;
    }
    
    List<Instance> validHosts = new ArrayList<>();
    for (Instance host : hosts) {
        if (!host.isHealthy()) {
            continue;
        }
        
        for (int i = 0; i < host.getWeight(); i++) {
            validHosts.add(host);
        }
    }
    //No valid hosts, return false.
    return !validHosts.isEmpty();
}
```

+ the weight of instance ranges from `0` to `10,000` ([com.alibaba.nacos.naming.constants.Constants.MAX_WEIGHT_VALUE](https://github.com/alibaba/nacos/blob/develop/naming/src/main/java/com/alibaba/nacos/naming/constants/Constants.java))
+ according to code logic, we can know `validHosts.size()` = `h1*w1+h2*w2+...+hx*wy` ≈ `hosts.size() * weight` (extreme case)
+ suppose that in the extreme case,  `validHosts.size()` also starts from at least `10,000`
+ mainly there is no other important, especial use for `validHosts` 
These are the reasons I give for optimize.

## Optimized
Change the variable `List<Instance> validHosts` to `boolean existValidHosts`.
```java
public boolean validate() {
    if (isAllIPs()) {
        return true;
    }
    
    if (hosts == null) {
        return false;
    }
    
    boolean existValidHosts = false;
    for (Instance host : hosts) {
        if (!host.isHealthy()) {
            continue;
        }
        
        if (host.getWeight() > 0) {
            existValidHosts = true;
            break;
        }
    }
    return existValidHosts;
    // or 
    // return hosts.stream().filter(Instance::isHealthy).anyMatch(i -> i.getWeight() > 0);
}
```

**Comment by Daydreamer-ia** [comment]
hi, pr welcome.
