### ISSUE TITLE
The import configuration button of the nacos backend management system does not work

### ISSUE THREAD

**Issue by Red-Kal** [alibaba/nacos#11421]
nacos后台管理系统 导入配置按钮不管用
The import configuration button of the nacos backend management system does not work
![Snipaste_2023-11-23_17-22-58](https://github.com/alibaba/nacos/assets/113286950/5eac0902-955f-4243-8122-7a35826e008f)

**Comment by 985492783** [comment]
if version<2.3 ,linked #10318
