### ISSUE TITLE
When nacos use enhancement such as opentelemetry javaagent or skywalking javaagent,etc, the server cannot connect to the client

### ISSUE THREAD

**Issue by AlchemyDing** [alibaba/nacos#11422]
**Describe the bug**
When nacos use enhancement such as opentelemetry javaagent or skywalking javaagent,etc, the server cannot connect to the client.
In the getInternalChannel method of GrpcConnectionInterceptor.java, serverCall is usually enhanced to ForwardingServerCall.SimpleForwardingServerCall, then ServerStreamHelper.getServerStream (serverCall), serverCall will not instanceof ServerCallImpl
[skywalking](https://github.com/apache/skywalking-java/blob/main/apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/server/ServerInterceptor.java#L68)
[opentelemetry](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/grpc-1.6/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_6/TracingServerInterceptor.java#L59)
![image](https://github.com/alibaba/nacos/assets/88769332/f7274a84-ab48-4ba1-896f-a0c8eda7d8bf)

**Expected behavior**
Connect the server and client normally
**Actually behavior**
the server cannot connect to the client.

**How to Reproduce**
VM options set opentelemetry javaagent

**How to Resolve**
determine ForwardingServerCall.SimpleForwardingServerCall type in GrpcConnectionInterceptor.java and convert to ServerCallImpl or turn off the grpc enhancement of the javaagent

**Comment by AlchemyDing** [comment]
If you think it needs to be fixed, please assign this issue to me

**Comment by KomachiSion** [comment]
1. The ServerStreamHelper is in sofa-jraft. If you want to fixit, please submit issue and PR to sofa-jraft.
2. sofa-jraft is imported by nacos-server, you mean add skywalking and opentelemetry javaagent to nacos-server?

**Comment by AlchemyDing** [comment]
@KomachiSion i run nacos-server with -javaagent:/../opentelemetry-javaagent.jar or skywalking-javaagent,
What I mean is that Nacos makes a judgment about this before using Sofa jraft;

**Comment by AlchemyDing** [comment]
soft-jraft only provide method to take serverStream from ServerCallImpl,But when nacos uses it, it's not ServerCallImpl.class,that has been enhanced by the javaagent ,become ForwardingServerCall.SimpleForwardingServerCall.class

**Comment by AlchemyDing** [comment]
![image](https://github.com/alibaba/nacos/assets/88769332/c44bb19b-fe9a-4574-b49d-aa3323b427d0)

**Comment by AlchemyDing** [comment]
I think adding this code would be better
```
private Channel getInternalChannel(ServerCall serverCall) {
    ServerCall<?, ?> call = serverCall;
    if (serverCall instanceof ForwardingServerCall.SimpleForwardingServerCall) {
        try {
            Method method = ForwardingServerCall.SimpleForwardingServerCall.class.getDeclaredMethod("delegate");
            method.setAccessible(true);
            Object invoke = method.invoke(serverCall);
            if (invoke instanceof ServerCall<?, ?>) {
                call = (ServerCall<?, ?>) invoke;
            }
        } catch (Exception e) {
            // ignore
        }
    }

    ServerStream serverStream = ServerStreamHelper.getServerStream(call);
    return NettyChannelHelper.getChannel(serverStream);
}
```

**Comment by KomachiSion** [comment]
I see the sofa-jraft has merged the PR, After released, nacos can upgrade to new jraft version to solve it.

**Comment by AlchemyDing** [comment]
OK, Thank you.

**Comment by ixiaoyi93** [comment]
I wonder if this issue was resolved after that version?

**Comment by AlchemyDing** [comment]
> I wonder if this issue was resolved after that version?

[2.3.1](https://github.com/alibaba/nacos/releases/tag/2.3.1)
