### ISSUE TITLE
upgrade nacos-server 1.4.1 to 2.2.X

### ISSUE THREAD

**Issue by sunalive2013** [alibaba/nacos#11420]
升级nacos-server时候，两集群六节点，在升级第一个集群前两个节点时候，服务正常注册在注册中心中，但是当升级到最后一个节点时，当升级完毕后，所有的注册上的服务，包括其他节点全部自动下线。
nacos-server：1.4.1 -> 2.2.2
nacos-client: 1.4.2

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/b6cbf3e1-6747-49cc-aaf5-ce0e8dbaee07)

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-upgrading.html
