### ISSUE TITLE
接口自动化持续测试方案

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#11423]
nacos单测只能覆盖单个场景以及mock场景，希望有一种方式能快速检索每次改动或者调整接口后带来的风险。
持续测试：
注册->登录->注销
注册->获取配置（client或者openApi）->修改配置 -> 验证配置
注册->注册服务->修改元数据->....
....

持续测试带来的好处是避免手动验证，并且在每次发版前跑完所有流程会避免发版出openApi的一些bug
不过用例太多以及复杂，不知道是否需要或者nacos内部有
产品：例如metasphere或者apifox

**Comment by KomachiSion** [comment]
主仓库的 nacos-test 模块，
以及Actions中的PUSH-CI

**Comment by KomachiSion** [comment]
或者有更好的CICD方式也可以在社区中应用。
