### ISSUE TITLE
client version is1.4.2, server version is 2.1.0, Single threaded udp push delay of 30 minutes

### ISSUE THREAD

**Issue by wangjie19930521** [alibaba/nacos#11431]
client version is1.4.2, server version is 2.1.0

environment:
OS: [e.g. Centos] centos7
Version [e.g. nacos-server 2.1.0, nacos-client 1.4.2] 
Module [e.g. naming/naming]
SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
jvm 20G (old:10G. new:10G)

happen:
1.Single threaded udp push delay of 30 minutes
2.The client receives delayed data and directly overwrites it
3.There is a risk of memory overflow

Can we change it to multi-threaded push by subscriber hash (IP+port)

**Comment by KomachiSion** [comment]
Please upgrade to 2.x client, use grpc to push data. The UDP push might remove in future.
