### ISSUE TITLE
密码错误，却提示用户不存在，让人很困惑

### ISSUE THREAD

**Issue by MuChenMuXuan** [alibaba/nacos#11448]
curl -X POST '127.0.0.1:8848/nacos/v1/auth/login' -d 'username=nacos&password=nacos'

nacos账号是存在的，密码是错误的。接口返回：
user not found!

期望返回：
密码错误

**Comment by 985492783** [comment]
我记得是为了防止有人hack账号，所以统一都抛出user not found

**Comment by Daydreamer-ia** [comment]
登录本身就该这样，因为如果直接密码错误的话，就被外部的人知道账号是存在的

**Comment by MuChenMuXuan** [comment]
> 登录本身就该这样，因为如果直接密码错误的话，就被外部的人知道账号是存在的

看来debug时，需要从防黑客的角度思考问题
