### ISSUE TITLE
断连后未重新连接  Ignore error event,isRunning:false,isAbandon=false

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/nacos#11443]
我在排查一个go 客户端断链的问题，发现go 的写法其实和java 一模一样。
问题就是 Ignore error event,isRunning:false,isAbandon=false 出现这个log 。为什么 isRunning:false 的时候不触发重新连接？

创建连接
1. 是先发送 stream 
2. Thread.sleep(100L);
3. 将状态改为 Running

如果sleep 期间stream 发送错误，状态将为 Running，不会重新连接。
![image](https://github.com/alibaba/nacos/assets/32947555/59873aa9-bc1c-415c-85a2-46b5741b6374)
只需在GrpcBiStreamRequestAcceptor  150 行添加错误就可以复现。

这是是否是个问题呢

**Comment by Cczzzz** [comment]
还有另外一种情况，如果一元请求重试失败后，也会将状态改为 非Running。此时stream 发生错误也不会重新连接

**Comment by stone-98** [comment]
老版本的确有这个问题，默认睡眠100ms就认为注册成功，目前在java的sdk目前已经修复了，会接受到注册成功的响应才会认为将状态置为running。

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
