### ISSUE TITLE
I hate projects without documentation.

### ISSUE THREAD

**Issue by aiai97** [alibaba/nacos#11440]
Everytime I tried to generate java documentation in nacos,I want a whole picture of nacos api.Unfornately,there is barely few information in nacos official website.I have a strong belief that it is essentail to have enough comments for readable codes.Can you guys please polish your code?It is not that friendly at all for an aboslute beginner as I do.I mean,maybe you guys can just put a java doc maven plugin in several pom files and I am pretty sure this minor change will make a world better place.

**Comment by KomachiSion** [comment]
Each release of nacos contain a java doc jar.  You means the java doc jar you can't download or the information in the java doc is not enough?

**Comment by KomachiSion** [comment]
No more response from author.
