### ISSUE TITLE
naos从2.1.0升级至2.2.3后开启鉴权应用报错

### ISSUE THREAD

**Issue by hsg1204** [alibaba/nacos#11454]
![image](https://github.com/alibaba/nacos/assets/39757660/e663bf4f-5b77-4828-bd95-582bd60dd131)
应用的springcloud 阿里巴巴版本是<spring-cloud-alibaba.version>2.2.9.RELEASE</spring-cloud-alibaba.version>
nacos client版本是2.1.0

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
