### ISSUE TITLE
2.3.0 版本使用内置数据库集群部署后，发布配置会报：RowMapper is required 错误

### ISSUE THREAD

**Issue by xiaobin-zhang** [alibaba/nacos#11459]
## Issue Description

Type: bug repor

2.3.0 版本使用内置数据库集群部署后，发布配置会报：RowMapper is required 错误。

![1701440018968](https://github.com/alibaba/nacos/assets/19240244/fd1231b7-412f-4f9f-aac1-9681dfe09961)

### How to reproduce it (as minimally and precisely as possible)

1.  搭建nacos集群
2.  使用命令启动 `-p embedded`
3.  在控制台发布配置报错

### Tell us your environment

windows , linux 环境都报错

**Comment by onewe** [comment]
@xiaobin-zhang 抱歉, 我晚点看看, 现在没时间
