### ISSUE TITLE
Nacos 2.0.3 内存无法释放

### ISSUE THREAD

**Issue by 7talen** [alibaba/nacos#11464]
## 问题描述
Nacos版本2.0.3，客户端实例数1W左右，某个节点上连接减少了，但是内存并没有得到释放。

![302901701675624_ pic](https://github.com/alibaba/nacos/assets/35684983/9975b903-b6d0-43a9-8c56-441e7126176a)
1）节点3上面的连接去了节点2，导致节点2的内存下降，但是节点3的内存并没有得到释放；

**Comment by Bo-Qiu** [comment]
能给更详细一些的描述信息吗：
1.比如你这个监控中指标具体意义是指什么？
2.是使用的naming模块，客户端会请求创建临时实例吗？还是说用的是config模块。

建议如果怀疑存在内存溢出的话，可以直接dump，使用MAT之类的工具分析是否存在内存溢出

**Comment by KomachiSion** [comment]
Java进程，堆内存申请之后不会归还给系统，请到Java官方文档中查找对应说明
