### ISSUE TITLE
nacos容器部署进程回收不掉

### ISSUE THREAD

**Issue by yanshicheng** [alibaba/nacos#11462]
在k8s集群跑的 nacos-server:v2.2.3 
运行一段时间查询进程 168 Ssl  112****5 JRaft-Rpc-Closu 这个睡眠进程有上百，请问这个是 bug吗，导致服务负载飙升。
 34 Ssl  116212 JRaft-RPC-Proce 这个进程也有几十个

**Comment by baisuyan** [comment]
> 在k8s集群跑的 nacos-server:v2.2.3 运行一段时间查询进程 168 Ssl 112****5 JRaft-Rpc-Closu 这个睡眠进程有上百，请问这个是 bug吗，导致服务负载飙升。 34 Ssl 116212 JRaft-RPC-Proce 这个进程也有几十个



> 是线程还是进程， 如果是进程的话，我没有见过这个进程，不知道其他人是否有见过。
> 
> 但是看你描述，如果线程/进程是睡眠的状态，应该不会影响负载。

测试

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
