### ISSUE TITLE
Proxy110 cannot be cast to com.alibaba.nacos.plugin.datasource.proxy.MapperProxy

### ISSUE THREAD

**Issue by 1148260649** [alibaba/nacos#11461]
![image](https://github.com/alibaba/nacos/assets/45970803/51d91c0b-4062-4209-b79c-c55749cdba31)
启动失败，提示 mapperproxy 该如何修改
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
com.sun.proxy.$Proxy110 cannot be cast to com.alibaba.nacos.plugin.datasource.proxy.MapperProxy

**Comment by 1148260649** [comment]
> What's the `com.sun.proxy.$Proxy110`? Can you template to describe how to happen?
I didn't do anything, but I encountered this error when starting the Nacos source code in standalone mode.

**Comment by KomachiSion** [comment]
console.nacos.io is staring with standalone mode, no happen this problem, Please provide how to reproduce this problem.

**Comment by rongxingsun** [comment]
> console.nacos.io is staring with standalone mode, no happen this problem, Please provide how to reproduce this problem.
jdk是17版本嘛

**Comment by 309283175** [comment]
#11497 
```
MapperProxy
Map<String, Mapper> SINGLE_MAPPER_PROXY_MAP
```
