### ISSUE TITLE
Startup in xml mode, unable to get nacos configuration data

### ISSUE THREAD

**Issue by CjqDy** [alibaba/nacos#1147]
dubbo 2.6.6 +dubbo-register-nacos 0.0.1+nacos-springcontext 0.2.2-RC1
provider and consumer startup with xml mode , unable to get nacos configuration data

in the Startup class：
@SpringBootApplication
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "127.0.0.1:8848"))
@NacosPropertySource(dataId = "nacos-consumer-application.properties")
@ImportResource(locations = {"classpath:/spring/spring.xml"})
@ServletComponentScan

in the nacos configuration 
dataId : nacos-consumer-application.properties
configuration:

server.port=8089
server.context-path=/demoApplication
dubbo.application.name=exueyun-bussiness-sit-consumer002
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
dubbo.application.qosPort=33333
spring.aop.proxy-target-class=true
spring.aop.auto=true

submit success
startup the main  class success....

Nacos Config Metadata : dataId='nacos-consumer-application.properties', groupId='DEFAULT_GROUP', beanName='applicationConsumer', bean='null', beanType='class com.orange.ApplicationConsumer', annotatedElement='null', xmlResource='null', nacosProperties='{serverAddr=127.0.0.1:8848, encode=UTF-8}', nacosPropertiesAttributes='{encode=${nacos.encode:UTF-8}, serverAddr=${nacos.server-addr:}, namespace=${nacos.namespace:}, contextPath=${nacos.context-path:}, endpoint=${nacos.endpoint:}, secretKey=${nacos.secret-key:}, accessKey=${nacos.access-key:}, clusterName=${nacos.cluster-name:}}', source='org.springframework.core.type.StandardAnnotationMetadata@3cf8a235', timestamp='1556518726857'

but see the property  dubbo.application.name  also exueyun-bussiness-sit-consumer 
not exueyun-bussiness-sit-consumer002

i try to use nacos.xml mode to use 

<nacos:global-properties server-addr="127.0.0.1:8848" />
<nacos:property-source data-id="nacoss-consumer-application.properties" auto-refreshed="true"/>
<nacos:annotation-driven ></nacos:annotation-driven>

also unable to read the nacos configuration

**Comment by nkorange** [comment]
This should be a configuration problem of Dubbo client. Report it to [Dubbo](https://github.com/apache/incubator-dubbo) please.
