### ISSUE TITLE
Nacos 2.3.0 内置数据库三节点集群，导入配置报错：未读取到合法数据，请检查导入的数据文件

### ISSUE THREAD

**Issue by xiaobin-zhang** [alibaba/nacos#11479]
**Describe the bug**
Nacos 2.3.0 内置数据库三节点集群，导入配置报错：未读取到合法数据，请检查导入的数据文件

**Expected behavior**

**Actually behavior**
![918eebfac51c4a8adb10349eb1e82be](https://github.com/alibaba/nacos/assets/19240244/5e56018b-444f-4b12-a209-944525e6a29d)

**How to Reproduce**
1. 搭建三节点集群，使用内置数据库启动
2. 创建命名空间，新增配置
3. 选中配置，导出查询结果
4. 导入配置，选中第三步导出的文件，相同配置下拉框选择`覆盖`
5. 弹出提示框：未读取到合法数据，请检查导入的数据文件

**Desktop (please complete the following information):**
 - OS: centos8
 - Version: nacos-server 2.3.0
 - Module : config

**Additional context**

**Comment by onewe** [comment]
@xiaobin-zhang 我用最新的代码测试过了, 没有复现这个问题.  应该是被 #11465 这个 PR 给解决了
