### ISSUE TITLE
修改nacos yaml配置文件，重复打印一段日志

### ISSUE THREAD

**Issue by jiubukaiji** [alibaba/nacos#11476]
<img width="1919" alt="Snipaste_2023-12-06_16-59-20" src="https://github.com/alibaba/nacos/assets/52603818/a652a902-bf9a-4c8c-b6f9-a71bffbe8896">

修改nacos yaml配置文件，重复打印一段日志：
[com.alibaba.nacos.client.Worker] WARN stdout [fixed-10.1.19.172_38848] [notify-currentSkip] dataId=controller.yaml, group=DEFAULT_GROUP, md5=4448034c82e9646c192afc47ceac9f78, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@3f4aaeb3, listener is not finish yet,will try next time.

重启后就没有了

**Comment by KomachiSion** [comment]
配置变更的回调线程，调用NacosContextRefresher$1@3f4aaeb3的时候卡住了，需要看下NacosContextRefresher$1@3f4aaeb3中哪里阻塞住了。

**Comment by KomachiSion** [comment]
建议下次复现时， 通过jstack 命令dump出线程栈，然后提交issue到SCA社区。
