### ISSUE TITLE
bug:  前端页面显示异常

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/nacos#11485]
![image](https://github.com/alibaba/nacos/assets/77964041/70628d32-1f4d-4891-b2d0-98f3a327aebe)

使用 chrome 无痕模式打开页面，出现奇怪符号

**Comment by 985492783** [comment]
Ctrl+R刷新下

**Comment by 985492783** [comment]
这个bug感觉是渲染问题，反正每次刷新几次就好了

**Comment by yuluo-yx** [comment]
> 这个bug感觉是渲染问题，反正每次刷新几次就好了

okay, 看到这个问题了，就顺手反馈一下
