### ISSUE TITLE
2.3.0单机版本下 "配置管理" -> "配置列表" -> "命名空间" 展示命名空间ID有误

### ISSUE THREAD

**Issue by HESQAQ** [alibaba/nacos#11481]
**Describe the bug**
2.3.0单机版本下 "配置管理" -> "配置列表" -> "命名空间" 展示的实际为 "命名空间描述"
**Expected behavior**
展示正常的命名空间ID
**Actually behavior**
A clear and concise description of what you actually to happen.
![image](https://github.com/alibaba/nacos/assets/37676951/0b9923f2-1dd5-4ad8-8a2c-14431016c8ef)

**How to Reproduce**
1. 新建命名空间
2. 回到配置列表, 逐个切换查看"命名空间"
3. "配置管理" 命名空间展示的不是命名空间ID

**Desktop (please complete the following information):**
 - OS: Centos
 - Version:  nacos-server 2.3.0

**Additional context**
无

**Comment by HESQAQ** [comment]
> 我看了下这个显示的是命名空间描述或者命名空间名，但是复制的还是命名空间id，如果觉得前者需要改欢迎贡献
![image](https://github.com/alibaba/nacos/assets/37676951/d9f9886a-9471-40b4-bdb8-61b97ce2e217)
2.2.0版本中点击按钮会出现复制成功弹窗

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/7668ce47-5425-4189-b0f6-d90802ce7774)

好像js会报错， 需要社区的前端大佬帮忙修复下

**Comment by DarrenLuo** [comment]
@i will solve it@

**Comment by 985492783** [comment]
这个我记得我 #11445 里面一起修掉了，原icon有点问题，换成了FaCopy，can close issue

**Comment by HESQAQ** [comment]
fixed

**Comment by Ryoui** [comment]
2.3.2点复制js报错：
![图片](https://github.com/alibaba/nacos/assets/18000474/ceb585fe-1ec1-44c3-bf28-2f289c7f4cdf)
