### ISSUE TITLE
 Users of the version 2.3.0 database plug-in need to modify the source code to add database paging dialect support.

### ISSUE THREAD

**Issue by jfly-cloud** [alibaba/nacos#11480]
ExternalUserPersistServiceImpl:
![image](https://github.com/alibaba/nacos/assets/61487624/5a4ac55b-6a54-4bf4-9bc7-652221a912dc)

PageHandlerAdapterFactory:
![image](https://github.com/alibaba/nacos/assets/61487624/ea24b245-c8ed-4569-975a-5af410e66b51)

**Comment by huangkemingyyds** [comment]
想请教一下，怎么在auth-plugin中利用SPI机制，优雅的扩展出对其他数据库的支持？    我希望能扩展出当前对这些数据库的支持。   @KomachiSion 
![image](https://github.com/alibaba/nacos/assets/66153067/46d74fae-b985-47ff-b1e9-bc438a24c09e)

**Comment by wuchubuzai2018** [comment]
> 想请教一下，怎么在auth-plugin中利用SPI机制，优雅的扩展出对其他数据库的支持？ 我希望能扩展出当前对这些数据库的支持。
### 一、熟悉并了解下Nacos的插件设计和开发机制
1、项目中的NacosServiceLoader类会在启动的时候，加载所有springboot模式下的SPI接口约定文件的类，封装在该类中：Map<Class<?>, Collection<Class<?>>> SERVICES = new ConcurrentHashMap<>()
2、然后我们就可以在源码中开发一个插件业务的接口，并提供一个XXXXManager结尾的类，该类目前在Nacos中都采用单例设计模式来定义，比如：AuthPluginManager等，该类负责加载当前业务的所有SPI实现，注册到内存Map中，然后在具体业务中就可以去根据自己的需要进行选择
3、插件开发者创建自己的插件实现后，利用spring-boot提供的loader.path机制，放到nacos的plugins文件夹下，该机制在startup.bat中进行了声明
###二、插件开发
1、首先，一般需要再主仓库中进行插件接口、插件manager的类的定义、插件实现类的路由和选择
2、然后，插件开发者，创建自己的插件工程实现自己的逻辑，如感觉不错，可以贡献给naocs-plugins仓库

**Comment by KomachiSion** [comment]
这个问题在其他issue中也回答过， 插件之间应该是独立的， auth插件不应该依赖datasource插件，这种设计是有问题的。

当然，如果你自己实现的自定义auth插件想要依赖datasource插件是可以的，但是并不是很建议这样做。

如果有鉴权插件适配其他数据源的诉求，可以通过以下方式实现：
基于当前的nacos鉴权插件，将其SQL进行修改，打包成自己的鉴权插件。
基于鉴权插件开发文档，按照需求重新开发自定义鉴权插件。

**Comment by KomachiSion** [comment]
Noop, plugins is dependent design, only the default auth plugin is an implementation demo and for adapt the old versions to use.

So it should not implement other dataousrce support by depend datasource plugin. Because it will cause other plugin develop with no used dependency.

**Comment by KomachiSion** [comment]
Of cource, community can contribute a auth plugin with other datasource by depending the datasource plugin.

But it should be contribute to nacos-group/nacos-plugin repo or open source in developers' repo.

**Comment by KomachiSion** [comment]
BTW, The default auth plugin use database to place data with most simple way, it might be replaced by jpa.

But the result may cause high depended by jpa, hibernate or other orms. The dependency increase might consider together.

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
