### ISSUE TITLE
使用shared-configs配置refresh后无法处理加密的配置项

### ISSUE THREAD

**Issue by 472424633** [alibaba/nacos#11486]
NACOS-2.2.4在使用shared-configs配置公共配置文件并开启refresh热加载时无法对jasypt-spring-boot-starter加密ENC()内的数据解密

配置如下
      discovery:
        server-addr: nacos1:8895,nacos2:8895,nacos3:8895
        namespace: 11111
      config:
        server-addr: nacos1:8895,nacos2:8895,nacos3:8895
        prefix: ${spring.application.name}-${spring.profiles.active}
        file-extension: yml
        namespace: 11111
        shared-configs:
          - data-id: application.properties
            group: DEFAULT_GROUP
            refresh: true  # 动态刷新配置

使用prefix 加载的独立配置 做 refresh没有问题可以正常解析出ENC()的加密内容
在使用shared-configs 并配置 refresh: true 来做公共配置时 refresh无法解析出ENC()加密的内容获取的参数为完整的 ENC(XXXXXX)。

**Comment by KomachiSion** [comment]
nacos不负责对配置内容作处理， 这部分内容应该在应用测或者SCA测处理。可以将issue移到SCA社区询问一下。
