### ISSUE TITLE
Nacos2.0配置中心为什么要有一个5min的全量拉取，是因为长连接推送会存在推送失败的情况嘛

### ISSUE THREAD

**Issue by lovejaychou** [alibaba/nacos#11487]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Daydreamer-ia** [comment]
兜底策略

**Comment by lovejaychou** [comment]
> 兜底策略

好的，大佬。麻烦问下一般都是为哪些异常case兜底呀

**Comment by Daydreamer-ia** [comment]
> 麻烦问下一般都是为哪些异常case兜底呀

网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。

**Comment by lovejaychou** [comment]
> > 麻烦问下一般都是为哪些异常case兜底呀
> 
> 网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。

好的，大佬帮忙看下我的思路是否正确呀。 也就是说当发生配置变更时，如果由于网络原因，一直推送失败，会忽略这条变更，然后增加这个5分钟定时拉取来兜底，保证配置最终能更新到客户端是嘛。

**Comment by Daydreamer-ia** [comment]
> > > 麻烦问下一般都是为哪些异常case兜底呀
> > 
> > 
> > 网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。
> 
> 好的，大佬帮忙看下我的思路是否正确呀。 也就是说当发生配置变更时，如果由于网络原因，一直推送失败，会忽略这条变更，然后增加这个5分钟定时拉取来兜底，保证配置最终能更新到客户端是嘛。

大概是这样，不过服务端推送失败并不会忽略，有对应的退避策略然后再去重试推送

**Comment by lovejaychou** [comment]
> > > > 麻烦问下一般都是为哪些异常case兜底呀
> > > 
> > > 
> > > 网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。
> > 
> > 
> > 好的，大佬帮忙看下我的思路是否正确呀。 也就是说当发生配置变更时，如果由于网络原因，一直推送失败，会忽略这条变更，然后增加这个5分钟定时拉取来兜底，保证配置最终能更新到客户端是嘛。
> 
> 大概是这样，不过服务端推送失败并不会忽略，有对应的退避策略然后再去重试推送

好的   大佬，我还有一个疑问，如果有对应的退避策略一直重试的话，为什么还需要额外加一个定时拉取逻辑来兜底呢，好像重试也能保证配置最终更新到客户端呀

**Comment by Daydreamer-ia** [comment]
> > > > > 麻烦问下一般都是为哪些异常case兜底呀
> > > > 
> > > > 
> > > > 网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。
> > > 
> > > 
> > > 好的，大佬帮忙看下我的思路是否正确呀。 也就是说当发生配置变更时，如果由于网络原因，一直推送失败，会忽略这条变更，然后增加这个5分钟定时拉取来兜底，保证配置最终能更新到客户端是嘛。
> > 
> > 
> > 大概是这样，不过服务端推送失败并不会忽略，有对应的退避策略然后再去重试推送
> 
> 好的 大佬，我还有一个疑问，如果有对应的退避策略一直重试的话，为什么还需要额外加一个定时拉取逻辑来兜底呢，好像重试也能保证配置最终更新到客户端呀

应用对服务目录和配置都比较敏感，推送失败不一定哪次才会成功，让客户端主动去拉取以尽快感知到变更

**Comment by Daydreamer-ia** [comment]
> > > > > 麻烦问下一般都是为哪些异常case兜底呀
> > > > 
> > > > 
> > > > 网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。
> > > 
> > > 
> > > 好的，大佬帮忙看下我的思路是否正确呀。 也就是说当发生配置变更时，如果由于网络原因，一直推送失败，会忽略这条变更，然后增加这个5分钟定时拉取来兜底，保证配置最终能更新到客户端是嘛。
> > 
> > 
> > 大概是这样，不过服务端推送失败并不会忽略，有对应的退避策略然后再去重试推送
> 
> 好的 大佬，我还有一个疑问，如果有对应的退避策略一直重试的话，为什么还需要额外加一个定时拉取逻辑来兜底呢，好像重试也能保证配置最终更新到客户端呀

而且，这次失败的推送只是针对一个服务端节点来说的，其他服务端节点不感知这次变更推送的。如果此时推送一直失败，然后客户端又断开和服务端的连接，那重新和别的节点建立连接后，变更就丢了。

**Comment by lovejaychou** [comment]
> > > > > > 麻烦问下一般都是为哪些异常case兜底呀
> > > > > 
> > > > > 
> > > > > 网络问题导致某些推送变更无法实时推送到应用，加个兜底去做。其实对应在 `Naming` 模块也有的。
> > > > 
> > > > 
> > > > 好的，大佬帮忙看下我的思路是否正确呀。 也就是说当发生配置变更时，如果由于网络原因，一直推送失败，会忽略这条变更，然后增加这个5分钟定时拉取来兜底，保证配置最终能更新到客户端是嘛。
> > > 
> > > 
> > > 大概是这样，不过服务端推送失败并不会忽略，有对应的退避策略然后再去重试推送
> > 
> > 
> > 好的 大佬，我还有一个疑问，如果有对应的退避策略一直重试的话，为什么还需要额外加一个定时拉取逻辑来兜底呢，好像重试也能保证配置最终更新到客户端呀
> 
> 而且，这次失败的推送只是针对一个服务端节点来说的，其他服务端节点不感知这次变更推送的。如果此时推送一直失败，然后客户端又断开和服务端的连接，重新和别的节点建立连接后，新建立的服务端节点不知道有推送的，如果没有客户端主动对账，那变更就丢了。

当客户端和其他服务器节点重新建联的话，增加对账逻辑， 这种应该比 5min定时拉取  性能高一点吧， 因为连接的持续时间应该会超过5分钟吧

**Comment by KomachiSion** [comment]
重连对单个配置的对账逻辑也是有的，但是5min定时拉取的对账是针对任何有遗漏的场景做兜底。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
