### ISSUE TITLE
login interface in 2.3.0

### ISSUE THREAD

**Issue by songbaicheng** [alibaba/nacos#11483]
When I used the 'standalone-mysql-8.yaml' arrangement method of version 2.3.0, I found that there was no login interface. I checked the documentation and said that the configuration of 'nacos.core.auth.enabled' has been required after 2.2.2. Open, but when I checked the environment variables and entered the terminal, I found that there was no such configuration item. I would like to ask if I need to manually add it to the application.properties file in the container or is there any more recommended method?

**Comment by KomachiSion** [comment]
the docker images can open auth by set ENV. but if use demo `standalone-mysql-8.yaml` , the auth is not open.

If you want to open auth. you should transfer the auth ENV to docker or k8s setting based on demo `standalone-mysql-8.yaml`.

**Comment by songbaicheng** [comment]
I succeeded in modifying the configuration in the application.properties file under the example/init.d directory.
