### ISSUE TITLE
There is a bug in CheckDbHealthTask method

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#11498]
**Describe the bug**
There is a bug in CheckDbHealthTask method.
<img width="900" alt="image" src="https://github.com/alibaba/nacos/assets/46370663/1bc69552-1458-42ee-a7e8-5acc77d6d0cd">
When config_info_beta is empty, the database health check always fails.

**Expected behavior**
When config_info_beta is empty, if the db is healthy, the health check is successful.

**Actually behavior**
When config_info_beta is empty, the database health check always fails.

**Comment by shiyiyue1102** [comment]
has been merge to develop branch ,close this issue

**Comment by superYuanC** [comment]
麻烦问下，这个bug，在哪个发行版本修复了
