### ISSUE TITLE
关于在生产环境中使用多namespace进行服务隔离的想法！

### ISSUE THREAD

**Issue by 3721518** [alibaba/nacos#11492]
现有环境的描述：
1，部署了基于三台服务器组成的Nacos集群，版本是2.0.3。
2，启用了namespace名称空间并开启了鉴权和用户验证来进行java运行时的环境隔离。
3，现使用环境有测试，UAT及预发，截止到目前为止一直使用的非常nice！！！
问题都有啥：
1，根据即将上线的项目的要求和特点，需要部署同样一套三节点的Nacos集群，版本同上。（已部署）。
2，根据地区来区分应用，并启用namespace来隔离应用内的服务。
3，启用鉴权，启用namespace，为各namespace启用用户验证（代码里会写好nacos的地址及namespace用户密码等）。
3.1, 疑问1：各namespace下已经注册上去的java服务能够做到配置及消息的请求的完全隔离吗？
3,2, 疑问2：我想开启访问策略，让指定的IP网段往指定的namespace空间去注册服务，请问是否可行？
3.3, 疑问3：基于疑问2所说的，我这样做《开启服务身份识别功能》是否可实现？
！！！请熟悉的楼主或者作者，帮忙解答下谢谢了，万分感谢。

**Comment by KomachiSion** [comment]
1. namespace只能保证从nacos获取服务和配置时，是绝对隔离的，一个client只能属于一个namespace；但是无法保证你应用存在2个不同的namespace的client，这部分需要应用测自行保证。
2. 不能，默认鉴权插件只能按照用户名密码进行访问策略控制，如果需要基于网段制定访问，需要自行开发鉴权插件实现
3. 可行，但是需要做很多保证逻辑，避免错误的认知导致故障，且这部分逻辑需要自行实现。
