### ISSUE TITLE
关于SpringCloud和nacos版本匹配的问题

### ISSUE THREAD

**Issue by shining-stars-lk** [alibaba/nacos#11491]
## 介绍
近期我们发现了QVD-2023-6271的漏洞，要求nacos的版本在2.2.1以上。但我们的Springboot版本为2.3.12.RELEASE、springcloud版本为Hoxton.SR12。查看alibaba的wiki，版本最高对应到Spring Cloud Alibaba 2.2.10-RC1 对应的nacos为2.2.0，还是在这个漏洞之内，我想在目前现有的springcloud版本把nacos升级到2.2.1。会有问题吗

**Comment by tomlikeyou** [comment]
nacos新版本的特性可能cloud对应版本没做适配，最好看下nacos 每个release版本发布修改的信息。

**Comment by KomachiSion** [comment]
基本上不会有问题，client的api是相对稳定的，但是建议先测试一下， 因为SCA中的实现可能有变化，如果有使用到反射之类的，可能会有不符合预期的地方。

**Comment by shining-stars-lk** [comment]
我是客户端使用的client还是2.0.3，服务端的nacos升到了2.2.4。简单测试了使用feign调用是可以的。 应该没什么事吧

**Comment by KomachiSion** [comment]
一般不会有问题，但是还是建议全量测试一下， 然后逐渐灰度更新。

**Comment by shining-stars-lk** [comment]
自己已解决
