### ISSUE TITLE
Unexpected derby.log file generated in current user directory

### ISSUE THREAD

**Issue by yoyo837** [alibaba/nacos#11502]
**Describe the bug**
In macOS,  run nacos with `/User/xxx/nacos/bin/start.sh`, unexpected `derby.log` file generated in current user directory.

**Expected behavior**
No unexpected log file generated.

**Actually behavior**
Unexpected derby.log file generated in current user directory.

**How to Reproduce**
Just run start nacos.

**Desktop (please complete the following information):**
 - OS: [macOS latest]
 - Version [2.2.4 with #10638 fixed source code]
 - Module [e.g. naming/config]
 - SDK [Oracle jdk 1.8.0_391 aarch64]

**Additional context**

**Comment by yoyo837** [comment]
Ref: https://github.com/alibaba/nacos/issues/10593

**Comment by DarrenLuo** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
The latest version 2.3.0 may fix this version, can someone test for the 2.3.0?

**Comment by KomachiSion** [comment]
I see, the derby.log is a logs when you use derby database.

so the derby.log will exist in work dir. It's match expectations.

**Comment by yoyo837** [comment]
> I see, the derby.log is a logs when you use derby database.
> 
> so the derby.log will exist in work dir. It's match expectations.

On macOS, are the `$HOME` directory and the `workdir` directory you mentioned the same thing?

It appears under `$HOME`, is this expected? I think it should appear in a folder with a certain name, not appear directly.

**Comment by KomachiSion** [comment]
I work on macOS, and the derby.log appear on the `nacos.work.dir`, not int `$HOME`.

**Comment by KomachiSion** [comment]
It might be some config diff in your macOS system, so that the derby read the config and print the log to `$HOME`.

**Comment by yoyo837** [comment]
> It might be some config diff in your macOS system, so that the derby read the config and print the log to `$HOME`.

Thanks for reply. Where should I check to find this difference config. I would be grateful if you could provide some guidance.

**Comment by KomachiSion** [comment]
I have no idea for this problem. Because I don't find this problem, maybe you can check your nacos dir is whether same as `$HOME` or some env properties special.

And you can move to derby community to find the derby.log information.

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
