### ISSUE TITLE
永久实例的应用场景是什么

### ISSUE THREAD

**Issue by doubelejjyy** [alibaba/nacos#11517]
永久实例的应用场景是什么？

**Comment by yang-zhang99** [comment]
一些基础的组件例如数据库、缓存等需要注册。这些不能上报心跳，如果这种类型的服务要注册，就需要作为持久化实例注册。官方的那本书《Nacos 架构与原理》里面不是有提到么？

**Comment by KomachiSion** [comment]
以及一些类DNS场景， 有些应用需要由运维PE人员维护的需要发现的域名和服务。都可以使用持久化服务来进行。
