### ISSUE TITLE
Nacos2.0.1控制台显示 "readyToUpgrade": false,

### ISSUE THREAD

**Issue by zhou-lang** [alibaba/nacos#11513]
## Issue Description
nacos管理控制台显示
    "raftPort": "7848",
    "readyToUpgrade": false,
    "version": "2.0.1"

我准备把nacos集群准备从2.0.1升级到2.2.1.  但是现在管理控制台显示  "readyToUpgrade": false,  这种情况可以按照官方升级文档进行升级吗？可能会有什么问题。
如果提示    "readyToUpgrade": false, 这种情况不能直接升级的话。我应该从哪些日志中查找相关的问题，来解决这个"readyToUpgrade": false的现象。

**Comment by zhou-lang** [comment]
目前nacos集群是3个节点。 如果管理控制台显示 "readyToUpgrade": false 这种状态下强制升级的话。可能会造成什么问题？

 如果只是比如节点之间数据有差异，强制升级会造成部分注册信息丢失，造成部分项目不平滑，可能会重启这种情况。是不是如果能接受部分项目不平滑的现象（比如避开访问高峰，在晚上操作，不平滑也只是部分项目重启，升级完成后就可以恢复），就可以按照nacos的升级文档进行了？

还是说，只要控制台提示"readyToUpgrade": false   就不能升级，强制升级会彻底失败，造成集群挂掉？

**Comment by KomachiSion** [comment]
readyToUpgrade是自动升级的状态标记， 意味着自动检查升级的任务发现以下情况：

1. 双写任务还有未完成的
2. 服务数/服务提供者数未一致。

造成上述情况的可能性有很多，有可能是服务提供者本身有抖动导致的， 也可能是集群搭建错误导致的。没办法一概而论。

readyToUpgrade：false 和 执行强制升级没有必然因果关系， 强制升级一定会成功，只是如果搭建有问题的情况下强制升级，可能会导致集群见数据不一致。

**Comment by zhou-lang** [comment]
OK. 谢谢。双写任务三个星期前关掉了。
可能原因就是 服务数/服务提供者数未一致。 因为现在的集群3个节点上，有一个节点的nacos.log 日志输出不是太正常。可能是这个节点有问题。

**Comment by diaodiaofly** [comment]
> OK. 谢谢。双写任务三个星期前关掉了。 可能原因就是 服务数/服务提供者数未一致。 因为现在的集群3个节点上，有一个节点的nacos.log 日志输出不是太正常。可能是这个节点有问题。

你问题解决了不？有没有遇到集群3个节点，因为机器宕机最后一个节点一直加入不了集群？

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
