### ISSUE TITLE
Request feature form case that some server nodes can not sending data to others but can accept data because of the fqdn UnknownHostException issue

### ISSUE THREAD

**Issue by Linzyoo** [alibaba/nacos#11519]
**Is your feature request related to a problem? Please describe.**
We met an issue in Nacos  AP case:
 one server node with UnknownHostException continually when send data to other nodes by fqdn.
 from this one  server node view, it can not send data to other nodes  but can accept data from them(the status would be set UP, and failure count would be clear). So the other nodes are health almostly.
 from the other two server nodes view, it can send data to the server node(the status would be up), but can not accept data from one(no check operation,  so would not be update to down)
 Then the issue node would receive request and data continually, but can not sync data to other nodes, and the server nodes would be in status of unconsistency.

**Describe the solution you'd like**
We expect that nacos could support this case. When the one server node can not send but accept from other nodes, that means it  can not send all of data which it writes to others, if other nodes still forwad request to this server node,  then it will be in unconsistency. Readiness should check this then this endpoint would not receive request. other nodes should mark it as unhealthy then they will not send request to this node.

**Describe alternatives you've considered**

**Additional context**

**Comment by Linzyoo** [comment]
If the statuses of the nodes could be two dimensions?  send and accept 
From one node view , check the other's status
| Send to | Receive from | Node health |
|--------|--------|--------|
| Success | Success | Health |
| Success | Failure (do not recevie in serverl intervals) | Unhealth |
| Failure | Success | Unhealth |
| Failure | Failure | Unhealth |
From one node view, check in readiness
| Send to | Receive from | Node Health|
|--------|--------|--------|
| Failure | Success | unready |

**Comment by KomachiSion** [comment]
I can't get the key point in issue, I think the problem just single connection due to the UnknownHost with DNS or CoreDNS error.

**Comment by Linzyoo** [comment]
> I can't get the key point in the issue, I think the problem is just a single connection due to the UnknownHost with DNS or CoreDNS error.
Yes, the key issue is that one pod has an UnknownHost problem. And when it happens, the nacos server can not work completely because it is in an inconsistent state. So I feel that it is better to take this case in and mark the issue pod as unhealthy, after that the nacos server can work with other pods correctly.

**Comment by KomachiSion** [comment]
You mean in this case, other nodes should fast to mark this node as `down` status like `Connection Refused`?

**Comment by Linzyoo** [comment]
> You mean in this case, other nodes should fast to mark this node as `down` status like `Connection Refused`?

Yes, not "fast" but needs to do so, and should mark itself as "unhealthy" too.  

By doing these two items, the nacos server can work correctly.

**Comment by Linzyoo** [comment]
If this request is approved，I can contribute on it. Please take a look at the solution I mentioned in  my previous posts. Thanks.

**Comment by KomachiSion** [comment]
I think other nodes which connect to the problem node mark the node as `Down` directly maybe ok.

But the problem node should not be. For nacos, each node is dependent and only judge the status by report. So the problem node don't know why or whether set self to unhealthy.

**Comment by Linzyoo** [comment]
> I think other nodes which connect to the problem node mark the node as `Down` directly maybe ok.
> 
> But the problem node should not be. For nacos, each node is dependent and only judge the status by report. So the problem node don't know why or whether set self to unhealthy.

To remove the problem pod/node from the endpoints, we need to mark the pod/node as unhealthy.

Let's take a look at this case: the pod/node can not send info to any of others, but can receive info from all of others.  That means the pod can not send the registering info to others, then others know nothing about the instances information which register to this pod. And it can receive the info from others, that means others are working fine now. Itself should have some issues.

**Comment by KomachiSion** [comment]
Nacos can't solve all of situations. For AP system, in your said situation, it's hard to judge whether is it's problem or other nodes problem, it only can do promise its `Availability` in `AP`, it should received and handle request. If set self to down, and mark other all of nodes down, the request will failed and violate the `AP`.

In this situation, the maintainer should fast to remove this node from front and clusters. Or moving this node to other health situation. And the AP protocol will consistent their datum to match the `Partition` in `AP`

**Comment by KomachiSion** [comment]
There is no response more than 3 weeks, it seems not reasonable request from the latest comments, close first
