### ISSUE TITLE
请问可以在2.x版本的配置中开放空服务清理功能开关吗

### ISSUE THREAD

**Issue by Eternity-LG** [alibaba/nacos#11515]
**Is your feature request related to a problem? Please describe.**
I can't get the serviceName when i integration nacos-sdk to display serviceName in my console if the service isEmpty，the serviceName has been cleaned.

**Describe the solution you'd like**[
I hope there is a switch that can control the cleaning of empty services

**Describe alternatives you've considered**

**Comment by KomachiSion** [comment]
I can't get the reason why not remove service.

I think you can set the expired time to a long time to implement it. But I think close the auto clean will cause the memory leak so not support plan for this.

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
