### ISSUE TITLE
nacos config module use case fail fix and coverage optimize to 70%

### ISSUE THREAD

**Issue by shiyiyue1102** [alibaba/nacos#11520]
current coverage:

![image](https://github.com/alibaba/nacos/assets/20452676/c6b5919e-7a83-4423-9448-1252df8f48cf)

aim to : no failed test cases and coverage up to 70%

**Comment by realJackSun** [comment]
sub project: Add unit tests for package com.alibaba.nacos.config.server.service.dump https://github.com/alibaba/nacos/issues/11531
