### ISSUE TITLE
Does Nacos support prefix-based wildcard listener?

### ISSUE THREAD

**Issue by SpireCat** [alibaba/nacos#11533]
**Is your feature request related to a problem? Please describe.**
We are using Nacos as the configuration center on our project.Our product form determines that we have many configuration items with the same prefix, like "a.b.c1" "a.b.c2" ... Can I implement a listener to listen to "a.b.*"? I went through the entire code and couldn't find a way to do that.

**Describe the solution you'd like**
Listen to all data prefixed with a string using * as a wildcard.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by KomachiSion** [comment]
plan to support in Nacos 3.X

**Comment by KomachiSion** [comment]
duplicate with #10380

**Comment by KomachiSion** [comment]
in #10380 description 

> 在社区贡献者中，已经有贡献者针对配置中心的模糊订阅能力进行了[设计](https://www.yuque.com/nacos/mydt7c/xogf1qngugkbl0vq) .
