### ISSUE TITLE
nacos 有做支持国产数据库的规划吗？

### ISSUE THREAD

**Issue by wanghaiyongyw** [alibaba/nacos#11535]
目前信创要求已经很普遍了，nacos是否有可能支持国产GauessDB数据库呢

**Comment by wangzheyuan** [comment]
GaussDB兼容PostgreSQL，nacos-plugin仓库有支持PostgreSQL的插件。

**Comment by onewe** [comment]
可以自己写个插件, [nacos-plugin ](https://github.com/nacos-group/nacos-plugin) 模仿这个仓库的实现, 还是很简单的

**Comment by KomachiSion** [comment]
nacos-plugin中有dameng数据库的插件， 其他的国产数据库也可以通过插件的方式支持， 欢迎贡献插件
