### ISSUE TITLE
如何控制nacos 在db数据源初始化完 之后再进行服务上线

### ISSUE THREAD

**Issue by Yule-Momoko** [alibaba/nacos#11534]
**Describe the bug**
如何控制nacos 在db数据源初始化完 之后再进行服务上线
**Expected behavior**
如何控制nacos 在db数据源初始化完 之后再进行服务上线
**Actually behavior**
A clear and concise description of what you actually to happen.
如何控制nacos 在db数据源初始化完 之后再进行服务上线
**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by onewe** [comment]
有什么特殊的场景么？

**Comment by Yule-Momoko** [comment]
> 有什么特殊的场景么？

因为数据源还没初始化完 nacose 中应用服务就上线了 这样访问使用应用api就会报错

**Comment by onewe** [comment]
请移步到 SCA 社区, 看看是不是初始化顺序的问题

**Comment by Yule-Momoko** [comment]
> 请移步到 SCA 社区, 看看是不是初始化顺序的问题

？？？？

**Comment by onewe** [comment]
https://github.com/alibaba/spring-cloud-alibaba
