### ISSUE TITLE
[Nacos Client] There is a bug in ServiceInfoHolder.isChangedServiceInfo() 

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#11537]
客户端在ServiceInfoHolder类的 isChangedServiceInfo() 方法里面
判断服务端推送过来的实例列表与本地内存的实例列表是否有变化，
如果有，才会触发用户通过subscribe方法注册的listener回调。

这个方法在99.9%的正常情况下是没问题的，
但是在我们的网关代客户端进行注册的场景中有问题，问题出在下面这一段代码

 
![企业微信截图_17031415701524](https://github.com/alibaba/nacos/assets/53824889/d3dcac6d-d674-4339-954e-a87db25db63c)

将list转换成map进行比较，节约时间，可以理解。

Map的key是ip+port，99.9%的情况都是唯一的，所以基本上没出过问题。

但是在我们网关代客户端进行注册的场景中（网关代注册是架构设计如此，原因之一是为了防止过多的客户端直连服务端）：

客户端ClientA通过网关A注册，当网关A需要发版升级时，为了保证流量平滑无损无感，先由客户端ClientA主动切换到网关B进行注册，一段时间后，网关A再注销客户端ClientA的实例。

在这一段时间之内，注册中心有两个ClientA的实例，IP和端口完全一样（就是元数据信息不一样）。
推送到客户端时，经过list转换成map的操作，其中一个实例信息会被覆盖掉。
这就导致 isChangedServiceInfo() 方法后续的的判断失真。
网关A的注销操作减少了一条实例信息，但是并不能正确触发listener回调，进一步引发基于这个listener回调的各种业务问题。

去掉list转map的操作，直接用list来比较，太耗时了；
用别的字段来当key，就要对每个实例都进行key的计算，也很耗时；
有没有低成本的解决方案？

**Comment by KomachiSion** [comment]
没有低成本的方案， 这个是取舍，快速对比的话肯定会丢失一部分信息，这是变快的代价；如果需要全量对比，那么必然要比对的东西多，时间自然要久。

这里唯一能做的，可能就是把isChangedServiceInfo由方法抽象成接口， 默认实现提供目前的方式，需要严格对比，同时觉得可以接受增加的时间的1%的场景，可以自行拓展对应的比较方式。

**Comment by MajorHe1** [comment]
> 没有低成本的方案， 这个是取舍，快速对比的话肯定会丢失一部分信息，这是变快的代价；如果需要全量对比，那么必然要比对的东西多，时间自然要久。
> 
> 这里唯一能做的，可能就是把isChangedServiceInfo由方法抽象成接口， 默认实现提供目前的方式，需要严格对比，同时觉得可以接受增加的时间的1%的场景，可以自行拓展对应的比较方式。

抽象成接口的话，整个ServiceInfoHolder类变成接口，然后提供默认实现，再通过SPI机制允许用户扩展？

**Comment by KomachiSion** [comment]
ServiceInfoHolder本身就在client中，用户本身就依赖的， 不需要SPI机制拓展。 只需要用户和注册监听器一下注册一下比较器就行。

**Comment by KomachiSion** [comment]
当然暴露给用户的肯定不是ServiceInfoHolder， 而是类似ServiceInfoComparator的接口，以及namingService的一个类似registerServiceInfoComparator的接口

**Comment by KomachiSion** [comment]
Any plan to do this issue?

If no plan to do, I think we can close issue first.
