### ISSUE TITLE
dataId前缀为cipher的单测覆盖不够全面

### ISSUE THREAD

**Issue by YuShiwen** [alibaba/nacos#11544]
当dataId开头为字母cipher时，这种情况的单测覆盖不够全面，我这边想补充一下。
具体修改如下：
1.新增类EncryptionAesHandlerTest，作为类EncryptionHandlerTest单测案例的补充，新增的EncryptionAesHandlerTest类中EncryptionPluginService的子类实现方法更具体，采用真实的AES加密方式进行验证。
<img width="414" alt="image" src="https://github.com/alibaba/nacos/assets/61678924/7051735d-2908-42df-906f-d1d3c5dde3ae">

2.新增类ConfigEncryptionFilterTest1，作为类ConfigEncryptionFilterTest单测案例的补充
    - 在类ConfigEncryptionFilterTest中，只对ConfigEncryptionFilter#doFilter方法中调用其他方法的执行次数做了校验，没有对执行结果做校验。
    - 在类ConfigEncryptionFilterTest中，没有对是否执行了EncryptionHandler#encryptHandler和其后续逻辑进行校验，只校验了ConfigRequest#getDataId和ConfigRequest#getConten是否至少执行一次，dataId前缀不为cipher时，也会执行这两个方法。
    - 补充单侧案例类ConfigEncryptionFilterTest1，对每次执行完ConfigEncryptionFilter#doFilter方法后的执行结果做了校验(对configRequest的getContent方法和getEncryptedDataKey方法的返回结果进行校验，对configResponse的getContent方法和getEncryptedDataKey方法的返回结果进行校验)

<img width="490" alt="image" src="https://github.com/alibaba/nacos/assets/61678924/df73e1e4-5e40-4abb-96d4-e47b4588dae7">

3.修改已有类AbstractConfigAPI_CITCase，补充了一个单测案例：dataId前缀为cipher时，publishConfig和getConfig会执行ConfigFilterChainManager#doFilter方法，会调用ConfigEncryptionFilter#doFilter对content进行一些操作，最终会调用此次新增的EncryptionPluginService匿名子类对content进行AES加解密。以前的单测案例没有走到这块加解密的逻辑。
<img width="464" alt="image" src="https://github.com/alibaba/nacos/assets/61678924/f35f50d0-6a6d-4f68-88b2-16ff4765427b">

**Comment by YuShiwen** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
welcome submit PR

**Comment by YuShiwen** [comment]
> 欢迎提交PR

FOR #11546  , 辛苦review一下
