### ISSUE TITLE
nacos2.0.4集群3节点使用过程的异常情况

### ISSUE THREAD

**Issue by diaodiaofly** [alibaba/nacos#11548]
初期使用3节点集群的使用正常，双写未关闭。
运行一段时间后，某一个节点所在机器因为资源紧张，导致宕机；发现问题后重新启动nacos，一直加入不了集群
尝试1：将故障节点启动，将ip和端口维护到另外2个节点的cluster.conf,发现15秒后这2节点会自动将刚加的ip:端口节点剔除

尝试2：将故障节点停止，将故障节点ip端口维护进另外2个节点cluster.conf，此时依然会被快速剔除。

尝试3:  将data目录清除，将故障节点启动后，再维护另外2个节点的cluster.conf，将故障节点的ip：端口加入，此时依然会被剔除

针对这种节点异常情况各位大佬，有没有好的建议或经验？

**Comment by KomachiSion** [comment]
没停双写正常， 升级完成后需要停止双写。

**Comment by KomachiSion** [comment]
另外就是建议尽快升级到2.1以上版本。

**Comment by diaodiaofly** [comment]
> 另外就是建议尽快升级到2.1以上版本。

集群节点，挨个一个一个节点升级，会有什么影响不？目前都是2.0.4

**Comment by KomachiSion** [comment]
已经达到稳定状态的2.0.4 停止双写后升级不会有问题。
