### ISSUE TITLE
AbstractConfigChangeListener 监听不到事件

### ISSUE THREAD

**Issue by WilliamUUUU** [alibaba/nacos#11543]
如题：我在使用自定义监听事件时，当配置发生变化时`receiveConfigChange`方法不会执行
```java
@Component
public class NacosListener extends AbstractConfigChangeListener implements InitializingBean
{
    @Autowired
    private NacosConfigManager nacosConfigManager;

    private static final AfterNacosConfigChangeHandler afterNacosConfigChangeHandler = AfterNacosConfigChangeHandler.INSTANCE;

    @Value("${spring.profiles.active}")
    private String env;

    @Value("${spring.application.name}")
    private String applicationName;


    @Override
    public void afterPropertiesSet() throws Exception
    {
        String s1 = applicationName + "-" + env + ".yaml";
        nacosConfigManager.getConfigService().addListener(s1, env, this);
    }

    @Override
    public void receiveConfigChange(ConfigChangeEvent configChangeEvent)
    {
        Collection<ConfigChangeItem> changeItems = configChangeEvent.getChangeItems();
        // 浏览账号白名单是否已经更新
        boolean loginLimitCountMapFlag = false;
        for (ConfigChangeItem changeItem : changeItems)
        {
            if (changeItem.getKey().contains("app.loginLimitCountMap") && !loginLimitCountMapFlag)
            {
                afterNacosConfigChangeHandler.addEvent(new ClearUserLoginCountLimitCache());
                loginLimitCountMapFlag = true;
            }
        }
        afterNacosConfigChangeHandler.startProcess();
    }

//    @Override
//    public void innerReceive(Properties properties)
//    {
//        for (String stringPropertyName : properties.stringPropertyNames())
//        {
//
//            System.out.println(properties.getProperty(stringPropertyName));
//        }
//    }
}
```
但是当我继承`AbstractListener`时，当配置变化时可以正常进入方法
这是我的版本及依赖
```xml
        <springcloud.version>2021.0.1</springcloud.version>
        <springcloud-alibaba.version>2021.0.1.0</springcloud-alibaba.version>
```
```xml
        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
```

**Comment by KomachiSion** [comment]
请发起订阅，你不发起订阅怎么知道要回调你的listenr呢。

https://github.com/alibaba/nacos/blob/develop/example/src/main/java/com/alibaba/nacos/example/ConfigExample.java

**Comment by WilliamUUUU** [comment]
> 请发起订阅，你不发起订阅怎么知道要回调你的listenr呢。
> 
> https://github.com/alibaba/nacos/blob/develop/example/src/main/java/com/alibaba/nacos/example/ConfigExample.java

我在`afterPropertiesSet`方法里已经添加了监听
```java
nacosConfigManager.getConfigService().addListener(s1, env, this);
```
`this`就是本listener呀

**Comment by KomachiSion** [comment]
配置文件的类型是properties或者yml吗？ 这个监听器好像只能支持这两种类型

**Comment by WilliamUUUU** [comment]
> 配置文件的类型是properties或者yml吗？ 这个监听器好像只能支持这两种类型

![image](https://github.com/alibaba/nacos/assets/120109439/365093b7-56d0-4e25-8082-86821d7d2254)
是yaml格式的

**Comment by KomachiSion** [comment]
控制台上显示的type是吗？ 不是说内容格式

**Comment by WilliamUUUU** [comment]
> 控制台上显示的type是吗？ 不是说内容格式

![image](https://github.com/alibaba/nacos/assets/120109439/240bec56-642a-44c9-961e-0c8c30c5c7a6)
也是yaml格式的

**Comment by godhth** [comment]
我咋好像没问题
![image](https://github.com/alibaba/nacos/assets/63696328/7d35a685-678f-43ef-82f5-2d44620000af)
![image](https://github.com/alibaba/nacos/assets/63696328/b6da9d32-8cbf-48c3-a3f0-986d7bb4e9fe)

**Comment by WilliamUUUU** [comment]
> 我咋好像没问题 ![image](https://private-user-images.githubusercontent.com/63696328/295869320-7d35a685-678f-43ef-82f5-2d44620000af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzA0NzYsIm5iZiI6MTcwNTEzMDE3NiwicGF0aCI6Ii82MzY5NjMyOC8yOTU4NjkzMjAtN2QzNWE2ODUtNjc4Zi00M2VmLTgyZjUtMmQ0NDYyMDAwMGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA3MTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNWM1ZTQwMWFiYTg3NmU5YWJkYTdjOWZlM2E1ODFjYTA3NTNmNTQ3ODRkYjE4OGE4Mzk2NTZmNTQwMDI3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fUGHBNnMs_vIl1ZLUC4yHgt2Oo7_8HsmG-AA7M7WAb4) ![image](https://private-user-images.githubusercontent.com/63696328/295869398-b6da9d32-8cbf-48c3-a3f0-986d7bb4e9fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzA0NzYsIm5iZiI6MTcwNTEzMDE3NiwicGF0aCI6Ii82MzY5NjMyOC8yOTU4NjkzOTgtYjZkYTlkMzItOGNiZi00OGMzLWEzZjAtOTg2ZDdiYjRlOWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA3MTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Y2EzY2IxOWZjMjk4OWYyY2I0ODlkZjA3OGJhMzdhNjkwYzY2ZmNlMjliYTJlY2YwNjNlZTBlZTBmN2JjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xr3qonmWpIg61p2q_a4J3RaJGWBtwZ80BL_qOoaV0JY)

你使用的starter版本是多少呀，nacos服务是什么版本

**Comment by godhth** [comment]
starter 2021.0.1.0
server 2.3.0

**Comment by YuShiwen** [comment]
我这边也是ok的
运行截图：
<img width="1095" alt="image" src="https://github.com/alibaba/nacos/assets/61678924/18f5506f-25e8-4600-a2c8-7a60c29c2280">
<img width="1666" alt="image" src="https://github.com/alibaba/nacos/assets/61678924/d90c4e1b-5161-4402-a90e-62c3f810ba5f">

版本：
nacos-service 2.3.0
```xml
<springcloud-alibaba.version>2021.0.1.0</springcloud-alibaba.version>
<spring.cloud.version>Hoxton.SR9</spring.cloud.version>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>${springcloud-alibaba.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>${spring.cloud.version}</version>
        </dependency>
```

测试代码：
```Java
@Component
public class NacosListener extends AbstractConfigChangeListener implements InitializingBean {

    @Autowired
    private NacosConfigManager nacosConfigManager;

    @Value("${spring.profiles.active}")
    private String env;

    @Value("${spring.application.name}")
    private String applicationName;


    @Override
    public void afterPropertiesSet() throws Exception {
        String dataId = applicationName + "-" + env + ".yaml";
        nacosConfigManager.getConfigService().addListener(dataId, env, this);
    }

    @Override
    public void receiveConfigChange(ConfigChangeEvent configChangeEvent) {
        Collection<ConfigChangeItem> changeItems = configChangeEvent.getChangeItems();
        System.out.println(JSONObject.toJSONString(changeItems));
        for (ConfigChangeItem changeItem : changeItems) {
            if (changeItem.getKey().contains("app.loginLimitCountMap")) {
                System.out.println("app.loginLimitCountMap发生变更!");
            }
        }
    }
}
```

**Comment by KomachiSion** [comment]
It seems work well in new version. 

Might be usage problem.
