### ISSUE TITLE
本地idea连接不了服务器nacos

### ISSUE THREAD

**Issue by suxaiolong** [alibaba/nacos#11552]
服务器正常启动，页面也可以访问，在本地启动服务连接服务器nacos时报错Client not connected, current status:STARTING，ping、防火墙、安全组全部正常

**Comment by 985492783** [comment]
9848端口开了吗

**Comment by suxaiolong** [comment]
没有开9848

**Comment by 985492783** [comment]
客户端2.x的话要把服务端9848端口打开

**Comment by suxaiolong** [comment]
好的好的，谢谢
