### ISSUE TITLE
配置历史保留问题

### ISSUE THREAD

**Issue by john-ran** [alibaba/nacos#11563]
请问nacos使用mysql作为后端数据库，其中his_config_info的内容会一直保存吗？或者会保留多久呢？

**Comment by godhth** [comment]
默认30天，可以通过nacos.config.retention.days 配置

**Comment by john-ran** [comment]
nacos.config.retention.days 这个配置是哪个版本开始启用的？我发现我2.2.2版本的配置文件默认没有nacos.config.retention.days这个配置 手动添加到application.properties文件就可以吗？

**Comment by KomachiSion** [comment]
默认文件中没有，需要手动添加

**Comment by john-ran** [comment]
好的 多谢 我试试

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
