### ISSUE TITLE
nacos 2.2.0 在数据源还没有初始化完就将应用上线了

### ISSUE THREAD

**Issue by Yule-Momoko** [alibaba/nacos#11569]
**Describe the bug**
我的应用是 先启动spring boot 启动完成之后初始化 druid 数据源 但是在 数据源还没有初始化完成 nacos 就把我的应用上线了 导致调用请求 由于数据源尚未初始化而报错

**Expected behavior**
希望 nacos 可以等我的数据眼初始化完成之后再将应用上线
**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
服务注册是应用自己的行为，和nacos无关，nacos是接收注册请求的一方，需要应用自己控制注册进度。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
