### ISSUE TITLE
如何监听服务上线下，求个 2.x 版本写法

### ISSUE THREAD

**Issue by imsuperman0920** [alibaba/nacos#11565]
hello team
如何监听一个 serviceName 实例的上下线，也就是注册一个 naming 的监听
之前用过 1.4 版本的 api，现在升级到 2.2.3 了（客户端版本 2.2.1），求个 springboot 中新版本的写法 （sca 版本 2022.0.0.0）

**Comment by 985492783** [comment]
目前应该只能监听服务名下的所有服务，然后在客户端侧做上下线判断，社区中模糊查询在支持这块了，具体可见#10380

**Comment by imsuperman0920** [comment]
@985492783 多谢回复，我用 NacosServiceManager 搞定了，就是想要指定服务名下的所有实例信息。真是没找到示例代码，一顿翻源代码
