### ISSUE TITLE
`java.lang.IllegalStateException: unable to find local peer: c9c1b4e91d2a:8848, all peers: [192.168.24.139:8850, 192.168.24.139:8849, 192.168.24.139:8848]`

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1156]
docker 启动的集群模式
遇到了读取的不是ip 而是一个容器id  多机器部署的
`java.lang.IllegalStateException: unable to find local peer: c9c1b4e91d2a:8848, all peers: [192.168.24.139:8850, 192.168.24.139:8849, 192.168.24.139:8848]`

**Comment by nkorange** [comment]
Refer to [doc](https://nacos.io/zh-cn/docs/deployment.html) to configure the prefered IP of Nacos server.
