### ISSUE TITLE
springboot 从nacos上 拉取配置不是最新的

### ISSUE THREAD

**Issue by SmartKarven** [alibaba/nacos#11570]
各位大佬好！
我使用nacos作为配置中心的时候出现了一个问题：
**本地idea 运行正常
测试环境 k8s上运行拉取的不是最新的nacos 配置。**
springboot:2.5.5
spring-cloud-starter-alibaba-nacos-config:2021.0.1.0
这是配置nacos上的配置：
![image](https://github.com/alibaba/nacos/assets/19932305/25fa6f13-c933-4225-b37e-2dccbf80acae)
k8s 上运行拉取到打印的的配置：
![image](https://github.com/alibaba/nacos/assets/19932305/41fb7020-c435-44d7-8e54-47fd2ed88ff6)
日志身上并没有最新新增的日志。使用@Value 注解 类上也加了@RefreshScope
而且项目还是重新运行后拉取的。
有经验的大佬帮解答一下，谢谢！

**Comment by KomachiSion** [comment]
请提交issue到spring cloud alibaba 社区
