### ISSUE TITLE
Nacos2.3获取不到配置

### ISSUE THREAD

**Issue by dofindme** [alibaba/nacos#11575]
使用的环境是JDK17 Springboot3 ，版本是官方对应的版本
Nacos2.2.3 server，但是client是2.2.1，在seata读取配置的时候获取不到配置文件
![image](https://github.com/alibaba/nacos/assets/18459525/0645f2e3-7a7d-47b6-89e8-a0fe7bd1e935)

但是我直接访时ok的
![image](https://github.com/alibaba/nacos/assets/18459525/59191ccd-b624-41f7-bcf2-aba3778eff4d)

暂时没看到 GRpc是怎么调用nacos服务的，但是返回的是 
![image](https://github.com/alibaba/nacos/assets/18459525/1ae8cfa6-f1d3-4159-b8fb-77f108298635)

grpc调用细节
![image](https://github.com/alibaba/nacos/assets/18459525/8b25c023-a2f1-46cb-8818-535c8790382b)

由于nacos部署的docker 开放3个端口
![image](https://github.com/alibaba/nacos/assets/18459525/1b3baf54-8b0f-4b0b-9175-a6d1dbce96b0)

 seata配置文件
![image](https://github.com/alibaba/nacos/assets/18459525/7b7e8135-f51f-4663-9c2a-ed8190bbab5e)

日志报错
![image](https://github.com/alibaba/nacos/assets/18459525/1aeb41e5-e10f-4a65-bda1-03dafd006c8c)

请解答，之前版本是springboot2系列版本没问题，升级为springboot3之后 seata就不行了，不知道是seata的问题还是nacos的问题，追的日志是nacos没获取到配置。感谢！

**Comment by dofindme** [comment]
![image](https://github.com/alibaba/nacos/assets/18459525/8d367ade-cb26-49c2-955e-056fba1580e1)
nacos配置了所需的配置文件

**Comment by dofindme** [comment]
我把nacos-client降级为1.4.6版本就可以

**Comment by 112921482** [comment]
2.*版本要开放9848和9849两个端口

**Comment by dofindme** [comment]
> 2.*版本要开放9848和9849两个端口

开放的啊

**Comment by KomachiSion** [comment]
看nacos-client的日志， 在${user.home}/logs/nacos/config.log

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
