### ISSUE TITLE
/nacos/v1/console/server/state 401 error

### ISSUE THREAD

**Issue by brucelpt** [alibaba/nacos#1157]
### Describe what happened (or what feature you want)
When I logged in, there was a 401 error
### How to reproduce it (as minimally and precisely as possible)

1. I use the browser developer tools to check the network, found with the back-end request/nacos/v1 / console/server/state return 401 error,
Resopense is 
{"timestamp":"2019-04-30T03:39:01.266+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/nacos/v1/console/server/state"}
But I have successfully logged in, and the request back end reported an error that 401 did not log in

### Tell us your environment

linux Nacos V1.0.0

**Comment by nkorange** [comment]
@brucelpt Clear browser cache.

**Comment by brucelpt** [comment]
@nkorange it's malfunction. I hava clear browser cache.

**Comment by nkorange** [comment]
![image](https://user-images.githubusercontent.com/4593375/56947626-547cac80-6b60-11e9-80fa-3086172532a7.png)

Clicked this?

**Comment by liangzhiyuanxxx** [comment]
![clipboard](https://user-images.githubusercontent.com/20085380/59325030-0ab4e380-8d14-11e9-9bfb-090c2d710c04.png)

**Comment by brucelpt** [comment]
![image](https://img-blog.csdnimg.cn/20190612170606167.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2JydWNlbHB0,size_16,color_FFFFFF,t_70)
yes,my problem is the same to you.But that doesn't prevent nacos from working properly
I tried to insert pictures into the reply but failed.

**Comment by brucelpt** [comment]
Looks like it worked

**Comment by brucelpt** [comment]
Looks like it worked

**Comment by brucelpt** [comment]
> ![image](https://user-images.githubusercontent.com/4593375/56947626-547cac80-6b60-11e9-80fa-3086172532a7.png)
> 
> Clicked this?
Sorry, I forgot to reply this question due to my busy work.
NO,I am using Google browser to clear browsing data.
![image](https://img-blog.csdnimg.cn/20190612171510719.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2JydWNlbHB0,size_16,color_FFFFFF,t_70)
