### ISSUE TITLE
最新的Nacos配置中心一致性问题

### ISSUE THREAD

**Issue by lovejaychou** [alibaba/nacos#11582]
1.4.2版本的Nacos配置中心如果使用外部数据库的话，对应的流程如下：
1、任意一个NacosServer接收到写请求，更新对应数据库
2、数据库更新成功后，该NacosServer向集群内所有NacosServer节点（包括自己）发送配置更新事件
3、当接收到配置更新事件后，NacosServer根据对应的group和DataId请求数据库，然后将该配置对应的最新值刷新到自身内存，并将该值写入到本地文件中。
4、NacosServer每6小时向数据库发送全量dump的兜底请求来保证一致性

现有最新版本还是上述这个流程嘛，如果这样的话，当NacosServer写完数据库宕机后，对应的配置更新事件会丢失，只能等到6个小时过后，其他节点才会接收到最新值嘛

**Comment by Bo-Qiu** [comment]
最新版本实现了增量对账的逻辑，每15s各nacos-server节点会查询数据库 进行增量对账

**Comment by lovejaychou** [comment]
> 最新版本实现了增量对账的逻辑，每15s各nacos-server节点会查询数据库 进行增量对账

大佬，能麻烦给个源码文件名提示吗  想具体研究下
