### ISSUE TITLE
WARN [IS LEADER] no leader is available now!

### ISSUE THREAD

**Issue by gibsonx** [alibaba/nacos#1158]
## Issue Description

Type: *bug report* or *feature request*

2019-04-30 16:10:15,000 WARN [IS LEADER] no leader is available now!

2019-04-30 16:10:30,000 WARN [IS LEADER] no leader is available now!

2019-04-30 16:10:45,000 WARN [IS LEADER] no leader is available now!

### Describe what happened (or what feature you want)

following error returned  after started 3 nacos node already started in cluster mode .  once I opened the browser and tried to access web console,  

 "server is STARTING now, please try again later! " 

### Describe what you expected to happen

access into web console

### How to reproduce it (as minimally and precisely as possible)

1.   every time start nacos with cluster mode  in K8s  

### Tell us your environment

k8s 1.12

**Comment by nkorange** [comment]
Execute this command for every Naco server and see what comes out:
```curl '$nacos_server:8848/nacos/v1/ns/operator/servers'```
