### ISSUE TITLE
2024年了，为什么还要在代码里面写拼接sql来实现crud

### ISSUE THREAD

**Issue by kkrgwbj** [alibaba/nacos#11583]
当前很多运营商项目都是买的oracle数据库，但是nacos默认支持mysql和derby。看了下官方扩展插件可以重写一些mapper查询的sql来支持oracle，但是源码里面各种拼接嵌套sql，改动太大。

2024年了，为什么不直接引入mybatis-flex这种优秀的持久化框架，本身框架底层已经兼容了各种数据库方言支持，而选择了 非常麻烦的拼接sql方案来实现数据库方言适配。。。

**Comment by 985492783** [comment]
适配的代价是重量级，nacos-plugin仓库也提供了很多插件直接使用，无需手动扩展，另外引入别人的框架也会有导致耦合问题

**Comment by kkrgwbj** [comment]
可能一开始的架构决定了这样吧，但是 一开始如果引入了，后续就没有这么多麻烦的事情，尤其是适配SQL方言这块或者你们可以考虑引入JPA。

**Comment by KomachiSion** [comment]
这样会引入了一个很重的ORM框架， 作为一个基础底座应用，这样变重并不是很好。目前制品包已经达到了150M左右，相比老版本的50M已经大了很多， 如果再引入各类ORM框架，估计奔着250M就去了。

**Comment by huangkemingyyds** [comment]
jpa也是够用的，sql也本身也不复杂。如果是引用orm出现了bug，也是不能及时修复的。

**Comment by KomachiSion** [comment]
另外根据seata的反馈， 使用orm可能会导致性能下降（orm中有很多反射，bean copy， 以及动态sql逻辑） 我们其实都不需要，但是又是资源损耗。

**Comment by KomachiSion** [comment]
综上所述，目前nacos之类的基础组建其实并不合适直接用orm框架。

**Comment by dylan-tao** [comment]
> 当前很多运营商项目都是买的oracle数据库，但是nacos默认支持mysql和derby。看了下官方扩展插件可以重写一些mapper查询的sql来支持oracle，但是源码里面各种拼接嵌套sql，改动太大。
> 
> 2024年了，为什么不直接引入mybatis-flex这种优秀的持久化框架，本身框架底层已经兼容了各种数据库方言支持，而选择了 非常麻烦的拼接sql方案来实现数据库方言适配。。。

nacosplus针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
