### ISSUE TITLE
nacos升级到2.3.0后，元数据大小限制导致部分API无法注册

### ISSUE THREAD

**Issue by ShellFoo** [alibaba/nacos#11588]
![image](https://github.com/alibaba/nacos/assets/9038243/cecd8b5e-7e5d-4464-b26e-9fac3350cbae)

![image](https://github.com/alibaba/nacos/assets/9038243/8fa9a0a3-1030-4b1c-a6ea-d338d2c7592a)

2.3.0服务端默认开启参数校验的开关，元数据长度不能超过1024，导致部分方法过多的API无法注册，请问除了关闭校验开关、拆分API外，有没有其他方法能够增加元数据的限制长度呢？

**Comment by 985492783** [comment]
我看了下配置这边目前是写死的，但是可以通过nacos.core.param.check.checker来切换校验规则，目前只有现成的规则，如果需求紧急可以看下文档自己实现一个校验插件，实现这个com.alibaba.nacos.common.paramcheck.AbstractParamChecker类并按照spi规则打包放进plugin文件夹下

**Comment by ShellFoo** [comment]
> 我看了下配置这边目前是写死的，但是可以通过nacos.core.param.check.checker来切换校验规则，目前只有现成的规则，如果需求紧急可以看下文档自己实现一个校验插件，实现这个com.alibaba.nacos.common.paramcheck.AbstractParamChecker类并按照spi规则打包放进plugin文件夹下

好滴，感谢解答。我先扩展下校验规则，不过还是希望能增加配置来控制这个元数据长度。

**Comment by KomachiSion** [comment]
正常默认情况下不建议元数据包含太多内容，最好的方式还是拆分开，控制其元数据内容。一般1024的长度可以涵盖绝大部分场景了。

如果是自身特殊需求，可以考虑拓展一下来处理。 后续也看下社区反馈，元数据大小是否需要一个配置来修改。

**Comment by ShellFoo** [comment]
> 正常默认情况下不建议元数据包含太多内容，最好的方式还是拆分开，控制其元数据内容。一般1024的长度可以涵盖绝大部分场景了。
> 
> 如果是自身特殊需求，可以考虑拓展一下来处理。 后续也看下社区反馈，元数据大小是否需要一个配置来修改。

出现问题的是几个比较基础的API，看了下有个API里是有40来个方法，消费方比较多、短期还不好拆分，就先扩展解决了。
感谢解答。

**Comment by hechangli** [comment]
nacos.core.meta.max.size=10485760  可以用不？如果不能用怎么扩展
