### ISSUE TITLE
Nacos用作配置中心的话，能够支持百万级别的客户端连接嘛

### ISSUE THREAD

**Issue by lovejaychou** [alibaba/nacos#11580]

**Comment by lovejaychou** [comment]
Nacos用作配置中心的话，能够支持百万级别的客户端连接嘛，大概要部署多少Nacos节点呢

**Comment by KomachiSion** [comment]
百万级别是可以支持的，但是可能需要：

1. 单机规格可能需要比较大，如8C16G、16C32G。
2. 同时数据库可能需要更高规格，或者属于可扩展的数据库，否则大量查询和发布会导致数据库成为阻塞。
3. Nacos节点可能需要扩容到80～100台。

另外问下什么场景会用到百万级别连接的配置中心， 感觉快要赶上整个阿里的用量了

**Comment by lovejaychou** [comment]
> 百万级别是可以支持的，但是可能需要：
> 
> 1. 单机规格可能需要比较大，如8C16G、16C32G。
> 2. 同时数据库可能需要更高规格，或者属于可扩展的数据库，否则大量查询和发布会导致数据库成为阻塞。
> 3. Nacos节点可能需要扩容到80～100台。
> 
> 另外问下什么场景会用到百万级别连接的配置中心， 感觉快要赶上整个阿里的用量了

没有什么具体的场景  我就是自己思考下系统的扩展性
