### ISSUE TITLE
When does Nacos release v1.4.7?

### ISSUE THREAD

**Issue by wyt** [alibaba/nacos#11596]
Can a member of the Nacos team answer this question?

**Comment by KomachiSion** [comment]
Any block problem in 1.4.6？

1.X has entry maintain status. If not block issues, the release will be long time, or not do release.

**Comment by KomachiSion** [comment]
The first recommand is to upgrade to upper 2.1

**Comment by KomachiSion** [comment]
1.4.7 Maybe release in next week（before 2024.1.20）

**Comment by KomachiSion** [comment]
1.4.7 released.
