### ISSUE TITLE
[ERROR] Failed to execute goal on project nacos-istio: Could not resolve dependencies for project com.alibaba.nacos:nacos-istio:jar:2.2.1

### ISSUE THREAD

**Issue by xukai-1** [alibaba/nacos#11593]
[ERROR] Failed to execute goal on project nacos-istio: Could not resolve dependencies for project com.alibaba.nacos:nacos-istio:jar:2.2.1
: The following artifacts could not be resolved: com.alibaba.nacos:nacos-config:jar:2.2.1, com.alibaba.nacos:nacos-naming:jar:2.2.1, com.
alibaba.nacos:nacos-core:jar:2.2.1: com.alibaba.nacos:nacos-config:jar:2.2.1 was not found in https://repo.maven.apache.org/maven2 during
 a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

This is an error message.

I tried mvn compile . Unable to solve.

**Comment by xukai-1** [comment]
my maven version 3.6.3 or 3.9.0，idea2023.3

**Comment by KomachiSion** [comment]
The 2.2.1 tag I can mvn install. And the release also not problem.

Maybe your env has some problem.

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
