### ISSUE TITLE
在使用配置中心功能时，MySQL数据源下，Nacos支持MySQL MGR模式嘛

### ISSUE THREAD

**Issue by lovejaychou** [alibaba/nacos#11599]
各位大佬，麻烦问下在使用配置中心功能时，MySQL数据源下，Nacos支持MySQL MGR模式嘛

**Comment by KomachiSion** [comment]
我理解是支持的，但是我没有测试过。

MGR只是MySQL 自己的多节点同步方式，对nacos来说，只要jdbcurl没问题，应该就可以。
