### ISSUE TITLE
  Replace the console address for launching the console

### ISSUE THREAD

**Issue by HL2554169233** [alibaba/nacos#11600]
<img width="1893" alt="微信图片_20240107154208" src="https://github.com/alibaba/nacos/assets/39996953/692afee1-bf14-4981-a569-54bea5be5c21">

When logging in for authentication now, the login page address should be provided instead of index.xml

http://localhost:8848/nacos/#/login

**Comment by 985492783** [comment]
If you are not logged in, you will be redirected to the login page

**Comment by KomachiSion** [comment]
I think no need to do.

if open auth, and no logged, will auto redirect to login page.
if open auth and logged, should not to login page.
if not open auth, should not to login page.
