### ISSUE TITLE
No service to register for nacos clien with spring cloud stream rabbit

### ISSUE THREAD

**Issue by legiorange** [alibaba/nacos#1160]
boot 2.0.3
cloud  Finchley

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
        </dependency>

----
@SpringCloudApplication
@EnableDiscoveryClient
@EnableAutoConfiguration (exclude = HibernateJpaAutoConfiguration.class)
@ImportResource({ "classpath:applicationContext.xml" })
@ComponentScan
@Configuration
@EnableRedisHttpSession
public class ShiroAuthServer {
///
}
----
 
2019-04-30 16:49:25.184  INFO 2504 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : No service to register for nacos client...
 

why just use stream-rabbit ,then project can't registering ?

**Comment by legiorange** [comment]
btw nacos 1.0.0

**Comment by nkorange** [comment]
Report it to [SCA](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) please.
