### ISSUE TITLE
nacos.core.auth.server.identity.key和nacos.core.auth.server.identity.value启动校验问题

### ISSUE THREAD

**Issue by HL2554169233** [alibaba/nacos#11601]
AuthConfigs类的一个代码片
    @PostConstruct
    public void validate() throws NacosException {
        if (!authEnabled) {
            return;
        }
        if (StringUtils.isEmpty(nacosAuthSystemType)) {
            throw new NacosException(AuthErrorCode.INVALID_TYPE.getCode(), AuthErrorCode.INVALID_TYPE.getMsg());
        }
        if (StringUtils.isEmpty(serverIdentityKey) || StringUtils.isEmpty(serverIdentityValue)) {
            throw new NacosException(AuthErrorCode.EMPTY_IDENTITY.getCode(), AuthErrorCode.EMPTY_IDENTITY.getMsg());
        }
    }

这里如果是standalone模式启动，为什么还要校验以下两个配置的值呢？
nacos.core.auth.server.identity.key=serverIdentity
nacos.core.auth.server.identity.value=security

这两个配置不应该是集群模式下，多个nacos服务端通信才需要配置的吗，用于跳过token鉴权，因为nacos服务之间的通信是可信的
这里没明白为什么单机模式下也校验了

**Comment by KomachiSion** [comment]
是的， 单机模式可以不校验， 之前做校验的时候没有处理这个场景， 可以提一个pr优化一下。

不过这个机制也快被淘汰了，引擎之间的通信已经基本都转移到grpc上了， 目前保留机制和http接口主要是兼容升级。 后续版本这个应该会移除。

**Comment by godhth** [comment]
@ i will solve it @

**Comment by KomachiSion** [comment]
@godhth The old PR implementation with some problem, I have revert it.

Standalone mode only effect the identity information, not effect the auth system type.
