### ISSUE TITLE
SQL files are redundant

### ISSUE THREAD

**Issue by chenzhiguo** [alibaba/nacos#11606]
This project is just a database 'nacos', but there are 4 database initialization sql files. And it's not all the same, it's not a big problem, but it affects the quality of the project's intuitive code.
Clean Up and remove redundant SQL files as soon as possible, please.

**Comment by KomachiSion** [comment]
I found 3 SQL file in codes, 

one is for init mysql database.
one is for derby database auto init.
And one for upgrade for 1.4.0

I think the first two file can't delete.
third file may delete after discussion.

Can you tell community the 4rd files?

**Comment by chenzhiguo** [comment]
`config/src/main/resources/META-INF/derby-schema.sql`
`config/src/main/resources/META-INF/nacos-db.sql`
`console/src/main/resources/META-INF/derby-schema.sql`
`distribution/conf/derby-schema.sql`
`distribution/conf/mysql-schema.sql`

**Comment by KomachiSion** [comment]
sql file in config and console is not duplicate.

it's used by run with source code, when you run nacos with source code, the `distribution` module not import into class-path.

the sql need be loaded.

**Comment by chenzhiguo** [comment]
The point I'm making is not that they are repetitive, but that they are inconsistent.

**Comment by KomachiSion** [comment]
> The point I'm making is not that they are repetitive, but that they are inconsistent.

Welcome submit PR to consist them, using `distribution` as template.

**Comment by Bo-Qiu** [comment]
I'll solve it.
