### ISSUE TITLE
nacos-server集群在2.2.3升级到2.3.0，或者2.3.0集群降级到2.2.0。已运行的服务出现两条相同注册记录

### ISSUE THREAD

**Issue by Comven** [alibaba/nacos#11602]
After upgrading the nacos cluster from 2.2.3 to 2.3.0 in the testing environment, the number of registered services has doubled, and during this period, the directories such as data and status have been deleted. Finally, all nodes can only be shut down and attention should be paid to starting the Nacos node before the registration service can be restored to one。（nacos-server集群从2.2.3升级到2.3.0或者从2.3.0降级到2.2.3，原本注册的服务信息会显示两个，且注册的IP地址与端口都相同。升级或者降级期间删除了nacos-server的data、status等目录。最后只有将所有节点关闭后再挨个逐一启动nacos-server节点，注册服务才会恢复成一个实例信息）

![image](https://github.com/alibaba/nacos/assets/8464801/1c26bf40-f1d1-4f24-b1dc-03aed8e648a9)

![image](https://github.com/alibaba/nacos/assets/8464801/7319cebe-183a-4090-b910-0c5048ce5de0)

**Comment by KomachiSion** [comment]
没遇到过，有个机制是重启服务端的话， 部分同步数据会保留3分钟，这3分钟期间可能存在双份数据，这个机制是保护发布、意外重启过程时，由于客户端重连速度的快慢，影响数据抖动的。

最好能复现的时候， 查一下日志之类的。

**Comment by Comven** [comment]
> 没遇到过，有个机制是重启服务端的话， 部分同步数据会保留3分钟，这3分钟期间可能存在双份数据，这个机制是保护发布、意外重启过程时，由于客户端重连速度的快慢，影响数据抖动的。
> 
> 最好能复现的时候， 查一下日志之类的。

经过测试的确是触发了您说的数据保留3分钟这个机制，3分钟后数据就会恢复成一条记录。

**Comment by libogithub2018** [comment]
就算出现多条信息，但是在这段时间内，服务的调用也不会出现问题吧？

**Comment by Comven** [comment]
> 就算出现多条信息，但是在这段时间内，服务的调用也不会出现问题吧？

是的，服务调用没有问题

**Comment by HadwinLing** [comment]
大佬，我想问问，你们升级集群是直接替换jar 包的形式升级吗？/data 目录要删除吗？如果升级过程中有问题，你们是怎么回滚的呀？
