### ISSUE TITLE
There are many warnings for using springboot3.2 

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/nacos#11616]
There are many warnings for using springboot3.2 #6249
nacos 2.3.0
![image](https://github.com/alibaba/nacos/assets/31852897/6f578afb-9666-4b77-bd61-5eab519f96a7)

**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
No any information in this issue, the old issue has closed by author means the problem has been solved by himself/herself. And it's not nacos' problem.

If your problem is same with this issue, please check codes and env by yourself.

If not, please submit more information.

**Comment by JavaLionLi** [comment]
> No any information in this issue, the old issue has closed by author means the problem has been solved by himself/herself. And it's not nacos' problem.
> 
> If your problem is same with this issue, please check codes and env by yourself.
> 
> If not, please submit more information.

There are warnings after the nacos sentinel seata update to springboot 3.2

**Comment by KomachiSion** [comment]
All of warning log and classes is spring cloud classes, you should move the issue to SCA community.
