### ISSUE TITLE
Questions about setting the default number of threads on the client

### ISSUE THREAD

**Issue by zhongqishang** [alibaba/nacos#11618]
**Is your feature request related to a problem? Please describe.**

Nacos is a great component! 

We use it with flink/spark/hive in the bigdata hadoop system. Our machine cpu is 80. Each machine has about 60+ containers, which is 60+ JVM instances. According to `ThreadUtils.getSuitableThreadCount()` The result will be 128.  It caused a lot of thread usage.

That is, 128 `com.alibaba.nacos.client.Worker` and 64 `com.alibaba.nacos.client.naming.updater.xx`.

For server side, use `ThreadUtils.getSuitableThreadCount()` to set thread num is suitable.
But for client side, i think this is not a suitable default value.

Now i via `-Dnacos.common.processors=2` to set.

**Describe the solution you'd like**

Add max thread count value config or default thread count value for client side.
BTW, include client side grpc client

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by KomachiSion** [comment]
I think the suitable thread based on processor number is right logic, but I think client provide config the max count thread size also right.

But the problem is, what's the default max count value?  If same with now, default no limit, only when users config the max count, it works. Is it ok?

**Comment by zhongqishang** [comment]
> I think the suitable thread based on processor number is right logic, but I think client provide config the max count thread size also right.
> 
> But the problem is, what's the default max count value? If same with now, default no limit, only when users config the max count, it works. Is it ok?

I think i get you said the right logic is for the most cloud/container env. right? 
I agree with that, but for some phisycal machine deploy multiple app, this default value may not be suitable. 

Consider compatible and for most scenarios, and same with now is appropriate. Add a new parameter and it is appropriate to explain it in the documentation.

**Comment by KomachiSion** [comment]
If add this configuration to set max thread count, the document must be updated and it's in plan.

The problem is what's the default value of max thread count, if no setting, the value is -1 and means use old logic with `ThreadUtils.getSuitableThreadCount()` .

**Comment by zhongqishang** [comment]
I think no setting and the default value is -1 and means use old logic is reasonable. 
This will be not effect user upgrade client version, and provided a code way to set max thread count.

**Comment by KomachiSion** [comment]
> I think no setting and the default value is -1 and means use old logic is reasonable. This will be not effect user upgrade client version, and provided a code way to set max thread count.

If no arguemnt, welcome to submit PR to do this.
