### ISSUE TITLE
关于nacos适配达梦数据库的一些问题

### ISSUE THREAD

**Issue by Handikang** [alibaba/nacos#11614]
[](https://developer.aliyun.com/article/976299)
**因为项目需要我根据上面的教程将nacos-2.0.4修改了关于达梦的配置之后打包了，然后基于打包的快照写了个dockerfile，然后基于这个nacos镜像，我使用docker-compose启动了nacos，但是容器一直在重启，而且容器日志显示：**

nacos-server  | /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Djava.ext.dirs=/usr/lib/jvm/java-1.8-openjdk/jre/jre/lib/ext:/usr/lib/jvm/java-1.8-openjdk/jre/lib/ext -Dloader.path=/home/nacos/libs -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/home/nacos/plugins/health,/home/nacos/plugins/cmdb,/home/nacos/plugins/selector -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/home/nacos/conf/ --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos-server  | nacos is starting with standalone
nacos-server  | nacos is starting，you can check the /home/nacos/logs/start.out

**这是我的dockerfile：**

FROM openjdk:8-jre-alpine

# Set the maintainer label
LABEL maintainer="yourname@example.com"

# Set environment variables
ENV MODE="standalone"
ENV JVM_XMS="512m"
ENV JVM_XMX="512m"
ENV JVM_XMN="256m"

# Set working directory for Nacos
WORKDIR /home/nacos

# Copy the Nacos server directory from your host to the image
COPY nacos/ /home/nacos/

# Make sure the scripts are executable
RUN chmod +x /home/nacos/bin/startup.sh

# Expose the necessary port
EXPOSE 8848

# Set the volume for external data and logs
VOLUME ["/home/nacos/logs", "/home/nacos/data"]

# Specify the startup command
ENTRYPOINT ["sh", "/home/nacos/bin/startup.sh", "-m", "standalone"]

**这是我的docker-compose服务配置：**

nacos:
    image: 172.16.16.40:5000/idata/primihub/nacos-server:v2.0.4_DM_x86_0.2
    container_name: nacos-server
    environment:
      MODE: standalone
      JVM_XMS: 512m
      JVM_XMX: 512m
      JVM_XMN: 256m
      DB_POOL_CONFIG_DRIVERCLASSNAME: dm.jdbc.driver.DmDriver
      JAVA_OPT: "-Dloader.path=/home/nacos/libs"
    volumes:
      - /disk01/primihub-deploy/docker-one-in-one/data/dm/DmJdbcDriver18-8.1.2.79.jar:/home/nacos/libs/DmJdbcDriver18-8.1.2.79.jar
      - /disk01/primihub-deploy/docker-one-in-one/data/dm/application.properties:/home/nacos/conf/application.properties
      - /home/nacos/logs/:/home/nacos/logs
    privileged: true
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8848/nacos"]
      interval: 10s
      timeout: 10s
      retries: 3

**Comment by Handikang** [comment]
https://developer.aliyun.com/article/976299
我根据这个教程打包nacos-2.0.4的

**Comment by KomachiSion** [comment]
您可能需要找这篇文章的作者了解一下，教程文章本身并非nacos社区提供的。

另外nacos2.2之后的版本提供了数据源插件， 并且社区有对于达梦数据库的插件， 可以试用一下。如果有插件使用问题，可以提交对应issue
