### ISSUE TITLE
nacos 2.2.3升级到2.3.0版本后，一直报ERROR [db-error] master db xx.xx.xx.xx down.

### ISSUE THREAD

**Issue by akinlau** [alibaba/nacos#11615]
nacos 2.2.3升级到2.3.0版本后，nacos.log日志一直刷ERROR [db-error] master db xx.xx.xx.xx down.日志，想问一下是什么问题，要怎么解决？
![image](https://github.com/alibaba/nacos/assets/14191294/2aa4903f-4ffc-4da6-b227-42c4db72ce8a)

**Comment by Bo-Qiu** [comment]
develop分支新的提交已修复此问题
https://github.com/alibaba/nacos/pull/11500
