### ISSUE TITLE
nacos and netbird conflict

### ISSUE THREAD

**Issue by youlvlv** [alibaba/nacos#11621]
**Describe the bug**
if i use netbird,i can't start my spring boot application ,it blocking at start ,application prompt me  
[Nacos Config] Listening config: dataId=  group=DEFAULT_GROUP
i stop netbird , my application is normal.

如果我在系统中运行了 netbird 应用，那么我将无法启动我的 spring boot 应用，他被阻塞在启动中。他提示我
[Nacos Config] Listening config: dataId=  group=DEFAULT_GROUP
当我停止 netbird 后，我的应用程序恢复了正常

**Expected behavior**
application is normal run 

**Actually behavior**
application is blocking

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [MacOS 14.2.1]
 - Version [e.g. nacos-server 2.3.0, nacos-client 2.2.1]
 - Module [e.g. config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos]
 -  [netbird](https://github.com/netbirdio/netbird) 

**Additional context**

**Comment by KomachiSion** [comment]
说明netbird应用改动了传入给nacos的dataID，改为了空字符串，导致获取不到配置，应用自然无法启动。

应该要排查netbird应用， 寻求netbird应用的帮助，或者自行排查为什么会影响到传入给nacos-client的dataid参数。
