### ISSUE TITLE
默认的反脆弱插件存在优化点

### ISSUE THREAD

**Issue by floor07** [alibaba/nacos#11626]
public LocalSimpleCountRateCounter(String name, TimeUnit period) {
        super(name, period);
        slotList = new ArrayList<>(DEFAULT_RECORD_SIZE);
        for (int i = 0; i < DEFAULT_RECORD_SIZE; i++) {
            slotList.add(new TpsSlot());
        }
        long now = System.currentTimeMillis();
        
        if (period == TimeUnit.SECONDS) {
            startTime = RateCounter.getTrimMillsOfSecond(now);
        } else if (period == TimeUnit.MINUTES) {
            startTime = RateCounter.getTrimMillsOfMinute(now);
        } else if (period == TimeUnit.HOURS) {
            startTime = RateCounter.getTrimMillsOfHour(now);
        } else {
            //有bug
            getTrimMillsOfSecond(now);
        }
    }

除了这里还有：SlotCountHolder 中的interceptedCount 总是0

 static class SlotCountHolder {
        
        AtomicLong count = new AtomicLong();
        
        AtomicLong interceptedCount = new AtomicLong();
        
        @Override
        public String toString() {
            return "{" + count + "|" + interceptedCount + '}';
        }
    }
注：
SimpleCountRuleBarrier并没有处理interceptedCount 
    @Override
    public TpsCheckResponse applyTps(BarrierCheckRequest barrierCheckRequest) {
        long count = rateCounter.getCount(barrierCheckRequest.getTimestamp());
        long maxCount = getMaxCount();
        if (MonitorType.INTERCEPT.getType().equals(getMonitorType()) && maxCount >= 0 && count >= maxCount) {
            return new TpsCheckResponse(false, TpsResultCode.DENY_BY_POINT, "tps over limit :" + maxCount);
        }
        rateCounter.add(barrierCheckRequest.getTimestamp(), barrierCheckRequest.getCount());
        return new TpsCheckResponse(true, TpsResultCode.PASS_BY_POINT, "success");
    }

**Comment by floor07** [comment]
#11625

**Comment by floor07** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
[](url)
