### ISSUE TITLE
nacos 2.3.0 DumpChangeConfigWorker  NPE

### ISSUE THREAD

**Issue by coderwsll** [alibaba/nacos#11632]
数据库用的derby集群
定时任务增量对数的逻辑中查询删除、修改等变更结果的Map中，key：数据库列名是大写的，在convertDeletedConfig、convertChangeConfig中用小写的列名去匹配，匹配不到结果，出现空指针问题

DumpChangeConfigWorker .run->EmbeddedConfigInfoPersistServiceImpl.findDeletedConfig->DistributedDatabaseOperateImpl.queryMany    返回集合中列名是大写的
EmbeddedConfigInfoPersistServiceImpl.convertChangeConfig  中 ((Timestamp) map.get("gmt_modified")).getTime();空指针

![1704878982053](https://github.com/alibaba/nacos/assets/44053545/234ac77c-1fd5-4650-973a-ba2b9e90ec63)
![1704879755050](https://github.com/alibaba/nacos/assets/44053545/fb731247-0dc3-40d1-9359-20b2d02379d2)

**Comment by Bo-Qiu** [comment]
试了下，确实能复现这个问题。需要集群模式启动的同时，使用内置的数据库derby，生产场景大概率不会这么用，不过确实是个问题。
<img width="910" alt="image" src="https://github.com/alibaba/nacos/assets/46370663/04de77aa-1db0-4564-90dd-9e4d6fd503d6">

**Comment by Bo-Qiu** [comment]
我近期修复下这个问题，感觉jdbcTemplate查询时直接指定好RowMapper最好，而不是查出List<Map<String, Object>>再调转换接口手工将Map对象转换为自定义实体对象。

**Comment by coderwsll** [comment]
> 试了下，确实能复现这个问题。需要集群模式启动的同时，使用内置的数据库derby，生产场景大概率不会这么用，不过确实是个问题。 <img alt="image" width="910" src="https://private-user-images.githubusercontent.com/46370663/295820782-04de77aa-1db0-4564-90dd-9e4d6fd503d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTc2ODAsIm5iZiI6MTcwNDk1NzM4MCwicGF0aCI6Ii80NjM3MDY2My8yOTU4MjA3ODItMDRkZTc3YWEtMWRiMC00NTY0LTkwZGQtOWU0ZDZmZDUwM2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNDI5ZTVlZWRiY2RiN2FiOGM2NWE4MmUwYjEyMGUwMDgwM2E3OTRmZDllZmYwNTAzZDU5ODMxMjg1Y2E3MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixg2VNciuzoNAZBG77AvqV6GjNgtQOFRjtB-g-63wEo">

生产为什么不推荐集群使用derby呀？我们目前打算生产使用derdy  😂

**Comment by Bo-Qiu** [comment]
> > 试了下，确实能复现这个问题。需要集群模式启动的同时，使用内置的数据库derby，生产场景大概率不会这么用，不过确实是个问题。 <img alt="image" width="910" src="https://private-user-images.githubusercontent.com/46370663/295820782-04de77aa-1db0-4564-90dd-9e4d6fd503d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTc2ODAsIm5iZiI6MTcwNDk1NzM4MCwicGF0aCI6Ii80NjM3MDY2My8yOTU4MjA3ODItMDRkZTc3YWEtMWRiMC00NTY0LTkwZGQtOWU0ZDZmZDUwM2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3MTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNDI5ZTVlZWRiY2RiN2FiOGM2NWE4MmUwYjEyMGUwMDgwM2E3OTRmZDllZmYwNTAzZDU5ODMxMjg1Y2E3MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixg2VNciuzoNAZBG77AvqV6GjNgtQOFRjtB-g-63wEo">
> 
> 生产为什么不推荐集群使用derby呀？我们目前打算生产使用derdy 😂

https://github.com/alibaba/nacos/issues/9800 大概原因可参考此issue

**Comment by coderwsll** [comment]
> 我近期修复下这个问题，感觉jdbcTemplate查询时直接指定好RowMapper最好，而不是查出List<Map<String, Object>>再调转换接口手工将Map对象转换为自定义实体对象。

嗯嗯，传入RowMapper比较理想，convertDeletedConfig和 convertChangeConfig 也不用重复去写。 EmbeddedHistoryConfigInfoPersistServiceImpl.convertDeletedConfig 中 gmt_modified 单位转换也有问题
![1704958123805](https://github.com/alibaba/nacos/assets/44053545/500dbdfa-cfa0-4dad-9d94-57045d5c6704)
