### ISSUE TITLE
相同的windows环境，nacos1.4.3运行正常，但是nacos2.x却报错，无法找librocksdbxxx.dll

### ISSUE THREAD

**Issue by zang568** [alibaba/nacos#11630]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by zang568** [comment]
测试了2.1.0，2.2.0,2.3.0版本，都报错

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/issues/4336#issuecomment-734058280

**Comment by zang568** [comment]
我比较了1.4.3和2.3.0的启动日志数据，1.4.3版本启动时protocol-raft.log文件没有内容，而2.3.0版本启动时有打印消息，是不是说明启动时没有调用jraftserver，也就没有调用rocksdb，所以不会报错



---- 回复的原邮件 ----
| 发件人 | 杨翊 ***@***.***> |
| 日期 | 2024年01月11日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alibaba/nacos] 相同的windows环境，nacos1.4.3运行正常，但是nacos2.x却报错，无法找librocksdbxxx.dll (Issue #11630) |

#4336 (comment)

**Comment by zang568** [comment]
2.3.0版本必须启动时就加载jraftserver吗？如果非集群模式，是不是可以不加载？



---- 回复的原邮件 ----
| 发件人 | 杨翊 ***@***.***> |
| 日期 | 2024年01月11日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alibaba/nacos] 相同的windows环境，nacos1.4.3运行正常，但是nacos2.x却报错，无法找librocksdbxxx.dll (Issue #11630) |

#4336 (comment)

**Comment by zang568** [comment]
我比较了1.4.3与2.3.4的启动日志信息，protocol-raft.log在1.4.3版本启动时，没有写入内容，2.3.0版本会写入“Initializes the Raft protocol, raft-config info ”等等信息，是不是说明1.4.3版本在启动时没有调用jraftserver，所以没有加载rocksdb.dll，因此也就不会报错
