### ISSUE TITLE
2.2.0 naming-push.log大量PUSH-FAIL超时

### ISSUE THREAD

**Issue by junechouiscoming** [alibaba/nacos#11637]
nacos服务端：2.2.0
应用客户端：2.x

非udp推送，服务端到客户端的telnet，ping均无问题
<img width="1972" alt="image" src="https://github.com/alibaba/nacos/assets/28861676/53974081-5298-4de3-ae71-5fcdd7d9dcff">

1、请问grpc的推送有重试次数吗？看udp是最大重试2次的，grpc没看到相关设置，配置文件里面只有如下配置
<img width="614" alt="image" src="https://github.com/alibaba/nacos/assets/28861676/5b37cf86-45fe-42dd-b20e-ab495f066abe">

2、可能由于一直在重试，导致Nacos堆外内存涨的很厉害，在堆外没限制的情况下，容器limit16g，xmx12g的时候，隔段时间容器内存使用超过limit，被系统oom kill掉；当堆外限制在2g的时候，naming-push.log里面会出现close的日志，如下所示
<img width="1958" alt="image" src="https://github.com/alibaba/nacos/assets/28861676/79d70a43-363b-4306-b19b-42985c36c8e2">

**Comment by KomachiSion** [comment]
说明订阅者应用测存在故障或性能瓶颈，建议分析一下日志中的 subsciber ip 找到对应的节点进行排查

**Comment by junechouiscoming** [comment]
@KomachiSion 问题已更新，麻烦协助看下。


> 说明订阅者应用测存在故障或性能瓶颈，建议分析一下日志中的 subsciber ip 找到对应的节点进行排查

不止一个应用，涉及到十几个应用。而且这是线下环境，线上业务量更大，同样的这些应用没有出现过异常

**Comment by junechouiscoming** [comment]
另外想咨询下，1.x的客户端连接2.x的naming服务端，由于k8s集群的特殊性，client -> server的网络是通的，因此调用服务端的beat和list接口是没有问题的；server -> client的网络是不通的，因此push永远不会成功，这种情况会导致什么问题吗？

**Comment by shiyiyue1102** [comment]
> 当

server -> client的网络是不通，会导致直接内存会上涨，在最新的develop分支上，我们解决了直接内存溢出的问题，我们在推送时判断了推送队列的积压报文数量，不会无限往客户端推送报文，但是持续3分钟报文积压，会在服务端将连接关闭，导致连接抖动问题

**Comment by shiyiyue1102** [comment]
> 另外想咨询下，1.x的客户端连接2.x的naming服务端，由于k8s集群的特殊性，client -> server的网络是通的，因此调用服务端的beat和list接口是没有问题的；server -> client的网络是不通的，因此push永远不会成功，这种情况会导致什么问题吗？

server -> client的网络不通，会导致直接内存会上涨，在最新的develop分支上，我们解决了直接内存溢出的问题，我们在推送时判断了推送队列的积压报文数量，不会无限往客户端推送报文，但是持续3分钟报文积压，会在服务端将连接关闭，导致连接抖动问题

**Comment by junechouiscoming** [comment]
@shiyiyue1102 除了server端直接内存的上涨，对client端会有什么影响吗？

**Comment by KomachiSion** [comment]
超时除了2.0.X版本的客户端，在reflection版本冲突的情况下， 会出现固定推送超时的情况， 目前没有发现其他bug导致此问题的情况。

有这类问题都是client有问题（CPU、GC、线程、网络）等导致的，所以主要还是找出哪个或者哪些ip最初开始出现推送超时，解决掉对应的应用的问题后，问题自然会解决。

至于develop分支上的优化，只是nacos的一种自我保护机制，防止单个连接或少量连接由于无法处理推送的数据而导致内存使用超量的风险，从而影响到其他连接和应用。但是无法解决client本身有问题导致的推送数据处理慢或者不处理而推送超时的问题。

**Comment by junechouiscoming** [comment]
> 超时除了2.0.X版本的客户端，在reflection版本冲突的情况下， 会出现固定推送超时的情况， 目前没有发现其他bug导致此问题的情况。
> 
> 有这类问题都是client有问题（CPU、GC、线程、网络）等导致的，所以主要还是找出哪个或者哪些ip最初开始出现推送超时，解决掉对应的应用的问题后，问题自然会解决。
> 
> 至于develop分支上的优化，只是nacos的一种自我保护机制，防止单个连接或少量连接由于无法处理推送的数据而导致内存使用超量的风险，从而影响到其他连接和应用。但是无法解决client本身有问题导致的推送数据处理慢或者不处理而推送超时的问题。

ok，明白了。
那这种推送失败会导致什么吗？因为我发现即使有大量超时，对应的应用使用方也并没有反馈过问题，还是我们通过Nacos监控发现的

**Comment by KomachiSion** [comment]
会导致发现服务地址列表变慢或者感知不到，如果应用本身发布不频繁或容灾使用较为标准，基本不会有业务影响

**Comment by junechouiscoming** [comment]
> 会导致发现服务地址列表变慢或者感知不到，如果应用本身发布不频繁或容灾使用较为标准，基本不会有业务影响

明白了，多谢解答。

**Comment by Cczzzz** [comment]
> > 另外想咨询下，1.x的客户端连接2.x的命名服务端，由于k8s集群的特殊性，客户端->服务器的网络是通的，因此调用服务端的beat和list接口是没有问题的；服务器->客户端的网络是不通的，因此push永远不会成功，这种情况会导致什么问题吗？
> 
> 服务器->客户端的网络不通，会导致直接内存会增长，在最新的开发分支上，我们解决了直接内存溢出的问题，我们在时候进行了自定义不会队列的积压报文数量，无限往客户端活跃报文，但是持续3分钟报文积压，会在服务端将连接关闭，导致连接死机问题

最新的开发分支上，我们解决了直接内存溢出的问题 ，这是那个commit ，我们也遇到了堆外内存持续增长的问题

**Comment by guozongkang** [comment]
> > 另外想咨询下，1.x的客户端连接2.x的naming服务端，由于k8s集群的特殊性，client -> server的网络是通的，因此调用服务端的beat和list接口是没有问题的；server -> client的网络是不通的，因此push永远不会成功，这种情况会导致什么问题吗？
> 
> server -> client的网络不通，会导致直接内存会上涨，在最新的develop分支上，我们解决了直接内存溢出的问题，我们在推送时判断了推送队列的积压报文数量，不会无限往客户端推送报文，但是持续3分钟报文积压，会在服务端将连接关闭，导致连接抖动问题

你好，我们也需要了同样的问题，服务端大量PUSH-FAIL，直接内存暴涨，直至服务器宕机。  我看这个是一月份的Isseu，目前修复代码已经发布了么？  是哪个版本发布的，或者可以把commit的链接发我么
