### ISSUE TITLE
nacos 2.3.0 CONFIG_INFO_STATE_WRAPPER_ROW_MAPPER  未注册

### ISSUE THREAD

**Issue by coderwsll** [alibaba/nacos#11635]
定位：
ConfigRowMapperInjector.injectConfigRowMapper 中未注册CONFIG_INFO_STATE_WRAPPER_ROW_MAPPER  

问题：
使用derby集群启动，配置变更发布最后一步查询配置信息结果（EmbeddedConfigInfoTagPersistServiceImpl.getConfigInfoOperateResult）异常：IllegalArgumentException:RowMapper is required
<img width="683" alt="e07d32a9698f904d359c770be4b02e0" src="https://github.com/alibaba/nacos/assets/44053545/4f918a0a-78d2-49d9-b62d-35cc751a17b2">

![1704882379711](https://github.com/alibaba/nacos/assets/44053545/c0e4a1b3-161e-4399-bc60-d4bc6c9f8b02)

**Comment by shiyiyue1102** [comment]
这个问题已经在 #11465 中解决
