### ISSUE TITLE
 raft loads snapshot bug

### ISSUE THREAD

**Issue by godhth** [alibaba/nacos#11645]
**Describe the bug**
当集群重启时，如果集群ip变化了，而raft会加载快照信息，导致raft ip还是上一次的集群信息
When a cluster restarts, if the cluster ip address changes, raft loads snapshot information. As a result, the raft ip address is the same as the last cluster information
![image](https://github.com/alibaba/nacos/assets/63696328/f6a5ace7-2484-4766-bd7b-2c3ad1cab959)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
invalid request, raft is strict mode for maintain, if you change the ip, you should remove old ip and add new ip by raft command. 
Not auto check and change it to others.
