### ISSUE TITLE
Error to process server push response

### ISSUE THREAD

**Issue by purgeyao** [alibaba/nacos#11654]
**Describe the bug**
客户端异常
Two client startup exceptions are reported
```
ERROR [,,,] 66919 --- [229.76.212-2340] c.a.n.c.remote.client.grpc.GrpcClient    : [1705300626632_39.164.140.146_55207]Error to process server push response: {"headers":{},"abilityTable":{"supportPersistentInstanceByGrpc":true},"module":"internal"}
```

**Expected behavior**
客户端异常
Two client startup exceptions are reported

**Actually behavior**
报错原因？
Cause of error？

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.3.0, nacos-client 2.1.0]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos,spring-cloud]

**Additional context**

**Comment by purgeyao** [comment]
启动客户端报的错，仅使用配置或调用，只会有一行报错，如两个功能都使用就会有两行报错，客户端服务正常启动。
If an error is reported when the client is started, only the configuration or invocation is used. If two functions are used, two lines will be reported, and the client service starts normally。

**Comment by Daydreamer-ia** [comment]
这个错误可以忽略。在V2.3.0版本支持能力协商，会在建立连接的时候把服务端的能力表和客户端能力表发送给对端。客户端也是在V2.3.0版本才做能力协商支持，更早的版本客户端没有支持。不会原有的业务流程有任何影响。#8458

This error can be ignored, to be honest. The nacos-server V2.3.0 support ability negotiation. It will send its features it supports when they set up connection. The client begin to support ability negotiation from V2.3.0 too. The previous version do not support. Nothing wrong will happen by it. #8458

**Comment by Daydreamer-ia** [comment]
i will resolve it.
