### ISSUE TITLE
using Chain of Responsibility to refactor ConfigQueryRequestHandler and ConfigServletInner

### ISSUE THREAD

**Issue by shiyiyue1102** [alibaba/nacos#11659]
using Chain of Responsibility refactor ConfigQueryRequestHandler  and ConfigServletInner, replacing current serval if-else statements. 

Create ConfigQueryHandler and ConfigQueryHandlerChain,ConfigQueryHandlerChainBuilder.
To exact BetaConfigQueryHandler-beta ,TagConfigQueryHandler-tag,FormalConfigQueryHandler-formal .

ConfigQueryHandlerChainBuilder builder with Handler of ordered name [ beta,tag,formal], if any handler matches this request,handler the request and return , delivery to next handler if not match.

ConfigQueryHandlerChainBuilder may design as a SPI interface ,for extensibility

**Comment by Bo-Qiu** [comment]
I wanna take it over, please assign to me, thx.

**Comment by MatthewAden** [comment]
@i will solve it@
