### ISSUE TITLE
nacos 2.1.2 开启监控后服务注册成功但在列表无显示

### ISSUE THREAD

**Issue by longlv2** [alibaba/nacos#11657]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
After enabling the configuration management.endpoints.web.exposure.include=* in Nacos, the service can be registered successfully and configuration can be retrieved. However, the services are not displayed in the web UI under the Service Configuration and Service List sections.

### Tell us your environment

nacos version: v2.1.2

**Comment by KomachiSion** [comment]
控制台看不到有两种可能：
1. 命名空间不正确
2. 没注册成功。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
