### ISSUE TITLE
非临时实例持久化的方式

### ISSUE THREAD

**Issue by Zzzz1111** [alibaba/nacos#11656]
你好，请问版本2.1.2非临时实例持久化的方式的是快照文件存储么？ 查找了{user.home}/nacos/data/naming/data/public目录没有找到对应的持久化文件

**Comment by KomachiSion** [comment]
存储在raft协议中， {user.home}/nacos/data/protocol/raft 下。 通过raft快照和raft log进行持久化。

**Comment by Zzzz1111** [comment]
好的好的，十分感谢
