### ISSUE TITLE
项目启动注册nacos时本地生成的logs和nacos目录支持修改？非源码启动

### ISSUE THREAD

**Issue by luocwu** [alibaba/nacos#11651]
项目启动注册nacos时本地生成的logs和nacos目录支持修改？

**Comment by luocwu** [comment]
最好能通过yml文件配置的形式进行路径修改

**Comment by Bo-Qiu** [comment]
spring配置文件中配置或者环境变量配置 nacos.logs.path

**Comment by Bo-Qiu** [comment]
> 如果是springboot中的yml文件支持配置吗？

可以的

**Comment by KomachiSion** [comment]
也可以-DJM.LOG.PATH=${yourPath}

这样日志就会在${yourPath}/logs下
