### ISSUE TITLE
nacos不支持跨namespace获取数据

### ISSUE THREAD

**Issue by XuZhenWei** [alibaba/nacos#11665]
目前项目中有两套nacos环境（测试和预发线上），在测试环境中，每个微服务会建一个自己的namespace，共有四五十个微服务。目前有些配置是各服务通用的，想建一个公共的namespace来放通用配置，目前看下来是不支持跨namespace获取配置吗？

**Comment by KomachiSion** [comment]
namespace是强隔离属性，一个客户端仅属于一个namespace，如果一定要一个应用同时访问多个namespace，需要在应用中创建多个client，归属不同的namespace，并自行管理。
