### ISSUE TITLE
如何在Nacoe的默认配置文件规则中排除动态环境变量下的配置文件

### ISSUE THREAD

**Issue by fank025** [alibaba/nacos#11666]
Configuration rules for Nacos configuration files
${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

When the project uses spring. profiles. active='@profiles.active@ ', the nacos configuration center will default to checking the ${spring. application. name} - @ profiles. active @. ${spring.cloud.nacos.config.file-extension} configuration file.
NacosPropertySourceBuilder will also check if the file exists and report an error

[nacos.client.cachedata.internal.notifier] [NacosPropertySourceBuilder]  : get data from Nacos error,dataId:${spring.application.name}-@profiles.active@.${spring.cloud.nacos.config.file-extension}
com.alibaba.nacos.api.exception.NacosException: dataId invalid
	at com.alibaba.nacos.client.config.utils.ParamUtils.checkKeyParam(ParamUtils.java:102)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:144)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94)

May I ask if it is possible to ignore the situation with this configuration file

**Comment by KomachiSion** [comment]
配置中心变量需要有应用自身进行替换， nacos作为配置中心仅进行配置的发布、下发，内容对nacos来说是黑盒，不会进行变量的替换。

**Comment by KomachiSion** [comment]
> 配置中变量需要由应用自身进行替换， nacos作为配置中心仅进行配置的发布、下发，内容对nacos来说是黑盒，不会进行变量的替换。
