### ISSUE TITLE
org.springframework.cloud.spring-cloud-starter-alibaba-nacos-config 0.9.0版本接入nacos2.3启动报用户不存在 如何解决

### ISSUE THREAD

**Issue by UltramanNoa** [alibaba/nacos#11662]
老项目 包还用的org.springframework.cloud.spring-cloud-starter-alibaba-nacos-config 0.9.0版本接入nacos2.3启动报用户不存在 如何解决 在配置里加了username和password还是不行

**Comment by UltramanNoa** [comment]
org.springframework.cloud:spring-cloud-starter-alibaba-nacos-discovery v0.9.0.RELEASE Enable authentication when upgrading nacos 2.3.0. Service startup report: user not found!

MSG:
ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sat Jun 10 15:35:54 GMT+08:00 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>



pom：
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies</artifactId>
    <version>Greenwich.SR2</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.9.0.RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.6.5</version>
</dependency>

<dependency>
    <groupId>com.alibaba.spring</groupId>
    <artifactId>spring-context-support</artifactId>
    <version>1.0.2</version>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>0.9.0.RELEASE</version>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>0.9.0.RELEASE</version>
</dependency>

我可以在不更改 org.springframework.cloud:spring-cloud-starter-alibaba-nacos-discovery v0.9.0.RELEASE 包的情况下解决此错误吗？ 如果需要如何更新maven依赖？ 我至少可以更改为哪个版本才能使项目正常运行？ 因为项目中也使用了dubbo ，更新org.springframework.cloud:下的alibaba 相关的包会影响到dubbo

**Comment by KomachiSion** [comment]
这个版本过旧， 应该不支持username和password，可以尝试升级一下。

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
