### ISSUE TITLE
自研注册中心+配置中心 并兼容 nacos client 是否存在开源协议的冲突？

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#11669]
我看到，nacos 是基于  Apache-2.0 license 协议开源的，按照该开源协议，修改后可以闭源，但每个被修改的文件，都需要放置版权说明，而我要做的是，使用 go 开发一个兼容 nacos client （java、go、nodejs）的注册中心+配置中心，并不涉及使用 nacos 相关的代码

我们内部大量使用 nacos，有多个集群，但作为配置中心，nacos 并不能满足我们的需求，不像 apollo 那样，有机房、环境等概念；另外，我们已经放弃 java 转 go，java 的服务大量使用 1.x 的 client，且不会有升级的打算，而 1.x 的client ，由于非 hash 一致，nacos server 重启会大量下线上线，存在一些问题，我们内部魔改了 nacos server，而这导致的后果是，我们内部的 nacos server 已经较难和社区同步，社区有新的功能，我们合并进来需要一定时间，然后发布测试、预发、生产，耗费周期较长，最关键的是，截止目前，我们容器化部署的方案一直无法落地，因为需要 cluster.conf 文件，且需要指定自己的 ip

基于这些原因，我们准备基于 golang 自研 注册中心和配置中心，但由于存量业务，我们自研的服务需要兼容 nacos 原生的 client，这便有了这个疑问。自研服务除了兼容 nacos 原生 client  外，和 nacos 无关，功能上也不对标 nacos，**仅为容器部署，降本增效**

**Comment by KomachiSion** [comment]
我理解通信上没有许可证限制，许可证应该只保护代码层面。所以兼容nacos-client不会有协议冲突的问题。

**Comment by ijustyce** [comment]
> 我理解通信上没有许可证限制，许可证应该只保护代码层面。所以兼容nacos-client不会有协议冲突的问题。

好的，多谢。

**Comment by chuntaojun** [comment]
i think you can see this https://github.com/chuntaojun/apiserver-nacos

**Comment by ijustyce** [comment]
> i think you can see this https://github.com/chuntaojun/apiserver-nacos

I will coding myself and only care about the license.
