### ISSUE TITLE
服务发现一直保留网络不通的注册服务

### ISSUE THREAD

**Issue by 474420502** [alibaba/nacos#11677]
**Describe the bug**
![image](https://github.com/alibaba/nacos/assets/9397764/b4eeffff-7708-44c8-8e35-9e908d07a253)
![image](https://github.com/alibaba/nacos/assets/9397764/1c61b68f-8385-4d87-934c-f8721fb2601f)

这个服务已经不健康了,网关直接断开, 一直保持健康状态.均衡负载策略一直循环调用到这个节点, 几乎无解.除了重启, 重启后只要这样操作又复现.

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
集群部署有问题，节点之间必然存在 cluster.conf文件不相等的情况或server节点频繁访问失败的情况（集群见网络问题）
