### ISSUE TITLE
config service dataId check

### ISSUE THREAD

**Issue by Moriadry** [alibaba/nacos#1167]
## Issue Description

feature request

### Describe what happened (or what feature you want)

Why we cannot have "/" char as valid char among our data id in nacos-config?  I believe this can suit many system, including file system well.

**Comment by nkorange** [comment]
因为本地缓存要用这个dataId名称当文件名称。  有一些字符不能作为文件名称。会影响缓存
数据模型上一个dataId对应的是一个配置文件
