### ISSUE TITLE
docker集群启动一直提示启动中

### ISSUE THREAD

**Issue by frosro** [alibaba/nacos#11676]
docker run --name nacos \
-e MODE=cluster  \
-p 8848:8848 \
-p 9848:9848 \
-e NACOS_AUTH_ENABLE=true \
-e NACOS_SERVER_PORT=8848 \
-e NACOS_SERVERS="192.168.2.161:8848 192.168.2.162:8848 192.168.2.183:8848" \
-e NACOS_SERVER_IP=192.168.2.161 \
-e NACOS_AUTH_IDENTITY_KEY=dsepnacoskey \
-e NACOS_AUTH_IDENTITY_VALUE=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg= \
-e NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789 \
-e EMBEDDED_STORAGE=embedded \
-v /data/nacos:/home/nacos/data \
-d nacos/nacos-server:2.0.2

结果一直在启动，请问是什么原因
![1705655709664](https://github.com/alibaba/nacos/assets/45985927/a7071ae9-2e93-4030-8f25-6cad15576c13)

**Comment by 985492783** [comment]
如果是单机，使用单机模式启动

**Comment by frosro** [comment]
> 如果是单机，使用单机模式启动

不，我就是想部署集群，但是又不想弄个数据库

**Comment by 985492783** [comment]
集群应该是要等所有集群都上线才行，你这边是怎么操作的

**Comment by frosro** [comment]
> 集群应该是要等所有集群都上线才行，你这边是怎么操作的

就是这个命令在三台服务器上分别执行，启动nacos容器，但是看日志，三台都一直提示在启动中，等了很久都没有启动完成。换成mysql数据库这种数据源又可以

**Comment by KomachiSion** [comment]
说明集群间的访问不通， raft选不出leader导致配置中心无法ready， 用外置数据库只要能连接上数据库就可以。
