### ISSUE TITLE
spring-boot3.0.13读取nacos配置的logback配置失败

### ISSUE THREAD

**Issue by lucky845** [alibaba/nacos#11673]
项目从2.7.13升级到3.0.13后，org.springframework.boot.logging.logback.LogbackLoggingSystem类中的configureByResourceUrl方法判断的是path是否以.xml结尾，使用logging.config=http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-common.xml方式的配置无法使用了，请问有其他方式配置吗
<img width="888" alt="image" src="https://github.com/alibaba/nacos/assets/84754814/914c33b3-6b1a-4e2c-aae3-a2537efc9ee4">

**Comment by YuShiwen** [comment]
@i will solve it@

**Comment by YuShiwen** [comment]
> 项目从2.7.13升级到3.0.13后，org.springframework.boot.logging.logback.LogbackLoggingSystem类中的configureByResourceUrl方法判断或者路径是否以.xml结尾，使用logging.config=http://${spring .cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-common.xml方式的配置无法使用了，请问还有其他方式配置吗 <img alt="图像" width="888" src="https://private-user-images.githubusercontent.com/84754814/297582915-914c33b3-6b1a-4e2c-aae3-a2537efc9ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTU1NjcsIm5iZiI6MTcwNTk5NTI2NywicGF0aCI6Ii84NDc1NDgxNC8yOTc1ODI5MTUtOTE0YzMzYjMtNmIxYS00ZTJjLWFhZTMtYTI1MzdlZmM5ZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZWUwZDVmMzgxMjdkN2M1MWVjMzVkMDg5MGI5Njg0MzhhNmQxNTYyMDU0OTU3ZTM1OTg4YTFiOTA4MmVhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zjxe3zK_QMYFFFI9Zi_zV8N4CmpwE_l__TwFFlSbqsw">

麻烦提供一下pom.xml文件中nacos的依赖

**Comment by YuShiwen** [comment]
看下是哪种依赖引入，版本号也麻烦提供一下
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>xxx</version>
</dependency>

<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>xxx</version>
</dependency>

<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>xxx</version>
</dependency>

**Comment by lucky845** [comment]
`        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2022.0.0.0</version>
        </dependency>`

**Comment by lucky845** [comment]
> > 项目从2.7.13升级到3.0.13后，org.springframework.boot.logging.logback.LogbackLoggingSystem类中的configureByResourceUrl方法判断或者路径是否以.xml结尾，使用logging.config=http://${spring .cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-common.xml方式的配置无法使用了，请问还有其他方式配置吗 <img alt="图像" width="888" src="https://private-user-images.githubusercontent.com/84754814/297582915-914c33b3-6b1a-4e2c-aae3-a2537efc9ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTU1NjcsIm5iZiI6MTcwNTk5NTI2NywicGF0aCI6Ii84NDc1NDgxNC8yOTc1ODI5MTUtOTE0YzMzYjMtNmIxYS00ZTJjLWFhZTMtYTI1MzdlZmM5ZWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3MzQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZWUwZDVmMzgxMjdkN2M1MWVjMzVkMDg5MGI5Njg0MzhhNmQxNTYyMDU0OTU3ZTM1OTg4YTFiOTA4MmVhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zjxe3zK_QMYFFFI9Zi_zV8N4CmpwE_l__TwFFlSbqsw">
> 
> 麻烦提供一下pom.xml文件中nacos的依赖； 看下是哪种依赖引入，版本号也麻烦提供一下哈
> 
> ```
> <dependency>
>     <groupId>com.alibaba.nacos</groupId>
>     <artifactId>nacos-client</artifactId>
>     <version>xxx</version>
> </dependency>
> 
> <dependency>
>     <groupId>com.alibaba.boot</groupId>
>     <artifactId>nacos-config-spring-boot-starter</artifactId>
>     <version>xxx</version>
> </dependency>
> 
> <dependency>
>     <groupId>com.alibaba.cloud</groupId>
>     <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>     <version>xxx</version>
> </dependency>
> ```

`        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2022.0.0.0</version>
        </dependency>`

**Comment by KomachiSion** [comment]
This Issue has more than one month no response. But I see the the usage is spring cloud alibaba. Should we move this issue to SCA community to find answer. The configuration in nacos is only push to app(SCA), but how to use is not nacos' feature but SCA.
