### ISSUE TITLE
nacos服务端开启鉴权的情况下，是否会对已经发布业务服务（通过nacos客户端链接）产生稳定性的影响？

### ISSUE THREAD

**Issue by bearxiongzhen** [alibaba/nacos#11678]
Nacos服务端未开启客户端鉴权情况下，将JAVA服务队外发布，nacos的客户端链接nacos服务器没有添加
properties.put("username","${username}");
properties.put("password","${password}");用户名与密码（缺失）
在上面这种情况下，在nacos服务端将客户端鉴权开启，这种情况下我的JAVA服务再未添加鉴权的情况下，除了拉取配置失败的问题，还会影响到JAVA服务的稳定性吗？

**Comment by KomachiSion** [comment]
会。 心跳会失败，服务会被移除。查询服务列表会失败， 如果使用的规范的话， 在服务提供者ip未发生变化的情况下， 靠缓存可以支撑短期内的业务调用，但是长期必然导致问题（变更无法被感知等等）

**Comment by kody1025** [comment]
> 会。 心跳会失败，服务会被移除。查询服务列表会失败， 如果使用的规范的话， 在服务提供者ip未发生变化的情况下， 靠缓存可以支撑短期内的业务调用，但是长期必然导致问题（变更无法被感知等等）

请问应该如何解决这个问题呢？

**Comment by kody1025** [comment]
> 会。 心跳会失败，服务会被移除。查询服务列表会失败， 如果使用的规范的话， 在服务提供者ip未发生变化的情况下， 靠缓存可以支撑短期内的业务调用，但是长期必然导致问题（变更无法被感知等等）

请问应该如何解决呢？ 只能客户端加鉴权重启吗？
