### ISSUE TITLE
有流量染色的开发计划吗？

### ISSUE THREAD

**Issue by wzkris** [alibaba/nacos#11675]
想通过注册中心实现流量染色、实例打标等功能，完成各种发布方式。不知道nacos有没有开发计划？

Want to achieve traffic coloring, instance marking and other functions through the registry to complete a variety of publishing methods. I wonder if nacos has a development plan?

**Comment by KomachiSion** [comment]
流量染色功能超出了nacos的涉及范围， nacos主要是做服务发现和配置管理的， 不会入侵到业务的实际流量管理中，可能会和其他产品合作来实现，比如Higress，SCA，Dubbo等。

实例打标其实现在就可以， 通过实例的元数据就可以打标， 订阅服务的时候获取到所有实例信息中有这个元数据内容。
