### ISSUE TITLE
如何在启动二进制版本的nacos时，设置日志级别为debug呢？

### ISSUE THREAD

**Issue by startjava** [alibaba/nacos#11687]
logging.level.root=DEBUG
好像无效，日志并没有增加。

**Comment by Daydreamer-ia** [comment]
`nacos` 有提供动态调整日志级别的 `api`，你可以先用这个解决一下问题，但是需要接口是有认证的
可以使用 `/v2/core/log`(1.x版本用 `/v1`) 去手动设置，请求体是需要携带 `logName` 和 `logLevel`.
`logName` 可取值有：`core-auth`、`core`、`core-raft`、`core-distro`、`core-cluster`
`logLevel`：`DEBUG` 等需要全大写的值
![image](https://github.com/alibaba/nacos/assets/83362909/1d4b04e1-5f66-4d4e-be36-605e2cf22ecc)
