### ISSUE TITLE
When will the 1.4.7 docker image be uploaded?

### ISSUE THREAD

**Issue by spacewander** [alibaba/nacos#11686]
## Issue Description

When will the 1.4.7 docker image be uploaded?

### Describe what happened (or what feature you want)

The 1.4.7 was just released last week. But there is no corresponding docker image for it.
https://hub.docker.com/r/nacos/nacos-server/tags

### Describe what you expected to happen

We can pull the docker image with the latest v1 release

**Comment by KomachiSion** [comment]
doing, waiting for some days.

**Comment by KomachiSion** [comment]
released I see
