### ISSUE TITLE
bug report:properties

### ISSUE THREAD

**Issue by yihukurama** [alibaba/nacos#1168]
## Issue Description
When I use durid properties like [spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000] the nacos tell maybe has errors  and if I add new values programs can not read sometimes

Type: *bug report* 
### How to reproduce it (as minimally and precisely as possible)

1. write nacos properties by [spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000]
2. nacos tell it maybe has error
3. add other value like kfcustomservice.fixrate=600000
4.start program,the program can not read kfcustomservice.fixrate

### Tell us your environment
springboot 1.5.20  windows server 2012 java8

### Anything else we need to know?
i think is the nacos check some errors ,the new properties not work.However the properties work when do not use nacos

**Comment by nkorange** [comment]
@yihukurama Try with one property per line.

**Comment by yihukurama** [comment]
spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
this properties is the example for druid. maybe has other way to set it. do u have any ideas?
![image](https://user-images.githubusercontent.com/15700462/57517833-4857d280-734a-11e9-948d-c71d35142aa1.png)

**Comment by nkorange** [comment]
Which annotation are you using?
