### ISSUE TITLE
nacos适配国产化数据库

### ISSUE THREAD

**Issue by gjf001** [alibaba/nacos#11685]
适配国产化数据库时，不止需要实现文档中的接口，还需要实现分页处理类PageHandlerAdapter，并在PageHandlerAdapterFactory中添加对应的处理类，版本是2.3.0

**Comment by KomachiSion** [comment]
PageHandlerAdapterFactory只是鉴权插件的实现， 并非数据库插件的实现。

对于page的分页适配，需要在对应需要分页的接口实现中，由适配数据库的插件自行实现。
