### ISSUE TITLE
集群部署nacos后，线上注册服务总是报错?caused: errCode: 500, errMsg: do metadata operation failed ;caused: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [naming_service_metadata] did not find the Leader node;caused: The Raft Group [naming_service_metadata] did not find the Leader node;

### ISSUE THREAD

**Issue by danielmlc** [alibaba/nacos#11683]
去查了日志：
protocol-raft.log：
![image](https://github.com/alibaba/nacos/assets/16604995/4c4d28ee-0af8-42a9-9441-9f9595317b40)

alipay-jraft.log：
![image](https://github.com/alibaba/nacos/assets/16604995/1843f3fa-eda1-4534-8504-327e39953a81)

OS: ubuntu22.04
nacos:2.3.0

**Comment by KomachiSion** [comment]
did not find the Leader node

you should check whether you deploy cluster right and set configuration right.

**Comment by danielmlc** [comment]
@KomachiSion 
![image](https://github.com/alibaba/nacos/assets/16604995/b06af928-15ed-4317-9e82-fe158b229f70)
节点数据也只有这些

**Comment by KomachiSion** [comment]
I think you deploy with big problem, the node think it's ip is 10.233.xxxx, but your cluster.conf is hostnames. 

You should use `nacos.inetutils.prefer-hostname-over-ip=true` to let node use hostname or domain as self address and make sure your env address is same with hostname.

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.
