### ISSUE TITLE
nacos客户端2.2.0升级到2.3.0后,配置中心读取不到配置 [Nacos Config] config[dataId=**.yml, group=DEFAULT_GROUP] is empty

### ISSUE THREAD

**Issue by TechnologyLiu** [alibaba/nacos#11699]
**Describe the bug**
1.项目之前一直用的依赖:nacos2.3.0,客户端2.2.0,使用正常,昨天把客户端升级到2.3.0后,发现无法获取到配置文件
2.看源码请求中响应未找到该配置文件报500
3.将nacos客户端切换回2.2.0后,则可以正常获取配置
**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
- JDK21
- SpringBoot3.2.2,SpringCloud2023.0.0,SpringCloudAlibaba2022.0.0
- nacos2.3.0

**Additional context**
下面是配置信息
server:
  port: 9000
  servlet:
    context-path: /

spring:
  profiles:
    # 环境配置
    active: @profiles.active@
  application:
    # 应用名称
    name: shop-gateway

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
      username: nacos
      password: nacos
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml

**Comment by dazer007** [comment]
遇到类似情况，升级到nacos2.3有bug, 2.2正常； nacos  2.3不加载nacos里面的配置

**Comment by KomachiSion** [comment]
请提供对应日志， 或单独使用nacos-client2.3.0进行测试。

**Comment by TechnologyLiu** [comment]
1.Nacos-client2.3.0,客户端2.3.0,debug源码这里获取不到配置
2.Nacos-client2.3.0,客户端2.2.0可以获取到
![微信截图_20240129084915](https://github.com/alibaba/nacos/assets/43312856/5494839a-0971-4217-9127-613d06be9cc2)


> 请提供对应日志， 或单独使用nacos-client2.3.0进行测试。

**Comment by KomachiSion** [comment]
说明配置不存在，请检查该dataid，group， namespace在console上存在

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
