### ISSUE TITLE
Data ID is required ".properties" when create

### ISSUE THREAD

**Issue by chenlistanley** [alibaba/nacos#1169]
## Issue Description

Type: *bug report* or *feature request*
feature request

### Describe what happened (or what feature you want)
Create Configuration, the Data ID is required ".properties", else not work

### Describe what you expected to happen
As format is to choose the file extension, then the Data ID should not expect again.

### How to reproduce it (as minimally and precisely as possible)

1. Create Configuration in Nacos, fill in the Data ID with "zuul-service", and the format is selected "properties"
2. Bring up "zuul-service", observe the properties is not loaded successfully.
3. Delete "zuul-service" from configurations, then create a new one with "zuul-service.properties" as Data ID, others follow the same. And this time the properties is loaded successfully.

### Tell us your environment
Nacos 1.0.0
spring-boot-starter-parent 2.1.4.RELEASE
spring-cloud-dependencies Greenwich.RELEASE
spring-cloud-alibaba-dependencies 0.9.0.RELEASE
java11

**Comment by nkorange** [comment]
.properties is required in Spring Cloud, refer to https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md

**Comment by fangjian0423** [comment]
It is recommand to use file extension because if you don't use it, you must click `detail` button to make sure which extension the dataId used.

**Comment by MagakiReimu** [comment]
@nkorange chenlistanley‘s meaning is when use nacos web create a new configuration, we need to check format, this format check can specify the configuration file suffix format，instead of adding a suffix to the dataid.

**Comment by MagakiReimu** [comment]
@nkorange When we creating a new configuration, after selecting the format, we no longer need to add a suffix to the dataid. Now the purpose of format selection is to format the configuration content, does it？

**Comment by nkorange** [comment]
> @nkorange chenlistanley meaning is When we creating a new configuration, after selecting the format, we no longer need to add a suffix to the dataid. Now the purpose of format selection is to format the configuration content, does it？

For spring cloud, .properties is needed by default in data id.
