### ISSUE TITLE
Nacos service registration issues

### ISSUE THREAD

**Issue by QixianX** [alibaba/nacos#11698]
After the services are restarted in batches, the registed service will drop one by one. After about 30 minutes, the service will regist successfully.

log:
nacos.common.remote.client.grpc.GrpcClient-server check fail, please check server ****, port 9848 is available, java.util.concurent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNKNOWN .... caused by: java.lang.illegalArgumentException: Invalid padding '4907232'. Padding must between be 0 and 256(inclusive)

nacos version: 2.2.3
nacos jdk: 8u332
cpu: arm64
sys: ASIANUX 7

**Comment by KomachiSion** [comment]
maybe your network or cluster deploy with problem, please check your network env and pod resources. such as CPU and so on.

**Comment by QixianX** [comment]
> maybe your network or cluster deploy with problem, please check your network env and pod resources. such as CPU and so on.

I think both the network and cluster deploy are healthy, cause this issue is happened after we upgraded nacos from 1.4.2 to 2.2.3.

**Comment by KomachiSion** [comment]
java.lang.illegalArgumentException: Invalid padding '4907232'. Padding must between be 0 and 256(inclusive)

 which means your network transport package lose or package changed by env so that the server or client read and decode package failed with illegal information.

The problem should check in your env by yourself.

**Comment by QixianX** [comment]
> ` java.lang.illegalArgumentException: Invalid padding '4907232'. Padding must between be 0 and 256(inclusive)`
> 
> which means your network transport package lose or package changed by env so that the server or client read and decode package failed with illegal information.
> 
> The problem should check in your env by yourself.

Thanks :)

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.

**Comment by xule27** [comment]
> > ` java.lang.illegalArgumentException: Invalid padding '4907232'. Padding must between be 0 and 256(inclusive)`
> > which means your network transport package lose or package changed by env so that the server or client read and decode package failed with illegal information.
> > The problem should check in your env by yourself.
> 
> Thanks :)

so do you fix it?

**Comment by LL3706** [comment]
这个问题最后解决了吗
