### ISSUE TITLE
Smoothly upgrade MySQL corresponding to Nacos without downtime 不停机平滑升级Nacos对应的MySQL

### ISSUE THREAD

**Issue by designer-framework** [alibaba/nacos#11697]
Concerns about upgrading MySQL:
   The old Nacos node connects to the main database (MySQL5.7), the new node connects to the slave database, and the MySQL of nacos-server is upgraded to 8.0 one by one. The Nacos console is not operated during the upgrade process, and the table data of the main database will change, resulting in the master-slave database. Are there transient inconsistencies?

Current MySQL upgrade plan (MySQL5.7 upgraded to 8.0):
MySQL master-slave replication, and then the slave node is promoted to the master node. The master database has read and write permissions (MySQL5.7), and the slave database only has read and write permissions (MySQL8.0) before the Nacos cluster upgrade is completed. After the upgrade is completed, the slave database will be upgraded to read and write permissions.

升级MySQL顾虑: 
   Nacos旧节点连接主库(MySQL5.7), 新节点连从库, 逐个升级nacos-server的MySQL至8.0, 升级过程不操作Nacos控制台, 主库的表数据会发生改变, 从而导致主从数据库存在短暂不一致的情况吗？

目前的MySQL升级方案（MySQL5.7 升级至8.0）：
MySQL主从复制, 然后从节点升级为主节点。主库有读写权限(MySQL5.7), 从库在Nacos集群升级完成之前只有读权限(MySQL8.0), 升级完成后从库提升为读写权限

**Comment by Daydreamer-ia** [comment]
在没有别的应用使用 `mysql` 相同库的情况下，如果不去操作 `nacos-server` 就不会有写操作进行，包括租户模块和配置模块，服务上下线就没影响

**Comment by designer-framework** [comment]
> 看了好几遍，没看懂问题。。
> 
> 你是说升级MySQL主库，会不会造成数据变化吗？ 我理解不会，在没有写请求的情况下，Nacos不会自己进行配置的操作。除非MySQL升级过程中有问题，导致数据库本身数据丢失或变更（binlog还是很稳定的，一般不会）。



> 看了好几遍，没看懂问题。。
> 
> 你是说升级MySQL主库，会不会造成数据变化吗？ 我理解不会，在没有写请求的情况下，Nacos不会自己进行配置的操作。除非MySQL升级过程中有问题，导致数据库本身数据丢失或变更（binlog还是很稳定的，一般不会）。

谢谢, 在不操作控制台的情况下, 是不会有写数据库的行为对吧？  如果是这样, 那完全可以使用主从复制, 然后从库升级成主库的方案来做这件事

**Comment by designer-framework** [comment]
> 看了好几遍，没看懂问题。。
> 
> 你是说升级MySQL主库，会不会造成数据变化吗？ 我理解不会，在没有写请求的情况下，Nacos不会自己进行配置的操作。除非MySQL升级过程中有问题，导致数据库本身数据丢失或变更（binlog还是很稳定的，一般不会）。

谢谢, 在不操作控制台的情况下, 是不会有写数据库的行为对吧？  如果是这样, 那完全可以使用主从复制, 然后从库升级成主库的方案来做这件事

**Comment by designer-framework** [comment]
> 在没有别的应用使用 `mysql` 相同库的情况下，如果不去操作 `nacos-server` 就不会有写操作进行，包括租户模块和配置模块，服务上下线就没影响

谢谢, , 那完全可以使用主从复制, 然后从库升级成主库的方案来做这件事
