### ISSUE TITLE
json数组配置怎么获取

### ISSUE THREAD

**Issue by zhongjunDeng** [alibaba/nacos#11692]
json格式的配置文件如果是kry-value格式能直接通过@Value获取到，但如果是数组怎么获取呢？
![Uploading nacos.png…]()

**Comment by 985492783** [comment]
理论上和yaml中获取是一致的，List，set都可以

**Comment by KomachiSion** [comment]
it's spring cloud or spring cloud alibaba's problem, please move issue to relative community.
