### ISSUE TITLE
Nacos Web管理端登录和服务注册登录入口能否分开。

### ISSUE THREAD

**Issue by luyiArye** [alibaba/nacos#11691]
目前Nacos的登录入口都是同一个，并且都通过nacos.core.auth.system.type同一个配置来控制认证方式。
![image](https://github.com/alibaba/nacos/assets/11347768/79cd4adc-d692-44b9-9ad9-6d0870b47490)

是否考虑将Web管理端认证和服务注册认证分开，真实情况可能希望web管理端采用Ldap认证，服务注册的认证依然走数据库或者其他更高效的认证方式。

**Comment by KomachiSion** [comment]
请自行开发自己的鉴权插件，然后针对管控端进行权限校验， 对客户端进行放行。
