### ISSUE TITLE
深色主题UI适配不完美

### ISSUE THREAD

**Issue by IJiaPu** [alibaba/nacos#11708]
如下图所示，测试环境：Edge浏览器版本120.0.2210.144 (正式版本) (arm64)，及Safari，都出现适配不完美卡白块
Nacos版本：2.3.1-snapshot
期待完美适配，包含：
1、当前banner配色在深色模式下的突兀感
2、右侧、下方的白条
3、按钮

<img width="340" alt="image" src="https://github.com/alibaba/nacos/assets/110883801/7feb5280-2ece-4262-9144-0b16670bbd59">

<img width="1380" alt="image" src="https://github.com/alibaba/nacos/assets/110883801/d98429d0-e299-49ff-b2ca-f0845c0a40fb">

<img width="1324" alt="image" src="https://github.com/alibaba/nacos/assets/110883801/448fd869-fb28-444e-9493-5da59d549b0e">

**Comment by 985492783** [comment]
按钮不太好改，一般深色模式按钮是绿+白，nacos的主题是蓝+白，改起来太突兀了
