### ISSUE TITLE
nacos v2.1.0版本修改用户密码 报authorization failed!

### ISSUE THREAD

**Issue by zhifan917** [alibaba/nacos#11705]
集群版本：2.1.0
环境：kubernetes部署
问题：当通过kubernetes部署，NACOS_AUTH_ENABLE为true后，集群节点为3个节点时，修改默认用户密码，或者新增的用户的密码，就会报403 authorization failed!
如果集群节点为一个，或者NACOS_AUTH_ENABLE为false后，修改密码正常。
当前因为是生产要用，且要求是2.1.0版本。该如何解决该问题；

**Comment by zhifan917** [comment]
![image](https://github.com/alibaba/nacos/assets/40556830/66106ad9-0028-4e8d-9b10-711b99682ffa)

**Comment by Daydreamer-ia** [comment]
三个服务端节点需要使用的是同一个数据源吗？

**Comment by zhifan917** [comment]
> 三个服务端节点使用的是同一个数据源吗？

容器化部署的，yaml文件中配置的，都是连接的mysql

**Comment by KomachiSion** [comment]
节点前是否有挂在vip等网络转发设备？  2.1.0的身份好像是绑定在session里的， 如果有转发设备如nginx，可能会导致session切换后丢失身份。

可以尝试直连进行修改试试，  这个问题我记得在后续版本已经修复。也可以尝试升级版本解决

**Comment by zhifan917** [comment]
> 节点前是否有挂在vip等网络转发设备？ 2.1.0的身份好像是绑定在session里的， 如果有转发设备如nginx，可能会导致session切换后丢失身份。
> 
> 可以尝试直连进行修改试试， 这个问题我记得在后续版本已经修复。也可以尝试升级版本解决

三个节点时挂在serverice下，是nodeport，用serverice直连也是一样的问题，无法修改密码。主要是因为客户端的包都是2.1.0的，单纯升级服务端版本也不行，所以暂时还没发升级，就很难受，只能想着看是否可以解决该问题了

**Comment by KomachiSion** [comment]
新版本服务端兼容旧服务端，单独升级服务端是没有问题的。

**Comment by zhifan917** [comment]
> 新版本服务端兼容旧服务端，单独升级服务端是没有问题的。

您的意思是新版本服务端兼容旧的版本服务端，java的客户端版本包不升级到对应新版本服务端版本也是可以的哈，大佬

**Comment by KomachiSion** [comment]
是的，  nacos的最新的服务端兼容从1.2～2.3所有版本的客户端
