### ISSUE TITLE
Console通知面板在英文界面仍然显示中文

### ISSUE THREAD

**Issue by lcmarvin** [alibaba/nacos#11706]
如下图所示：

<img width="1459" alt="image" src="https://github.com/alibaba/nacos/assets/98330341/63a740fd-db82-48fd-826f-4f89eeec9eb8">

**Comment by Daydreamer-ia** [comment]
pr welcome

**Comment by lcmarvin** [comment]
> pr welcome

Notice的具体内容是通过接口`/v1/console/server/announcement`获取到的，需要在点击中英文切换时再次请求接口吗？这样的话接口需要带上当前语言参数。或者具体内容不通过接口获取，直接放到console-ui里，就可以用已有的方式实现中英文切换。

不太清楚出于什么考虑，Notice的具体内容需要从接口获取。

**Comment by KomachiSion** [comment]
Notice的内容根据不同的环境，部署人员可以修改，如果写死在ui中，修改需要编译，不是很合适。

由于内容是可以修改的， 如果有必要可以通过announcement文件修改为双语内容。

**Comment by lcmarvin** [comment]
https://github.com/alibaba/nacos/pull/11729 尝试修复该问题，但点击中英文切换按钮后，需刷新页面才生效，不知该思路是否合适？

**Comment by 985492783** [comment]
> #11729 尝试修复该问题，但点击中英文切换按钮后，需刷新页面才生效，不知该思路是否合适？

我觉得后台可以直接改成英文，就目前来说，nacos-server并没有国际化，所有国际化都在前端做的，感觉没必要因为一个公告接口做这个事情 @KomachiSion

**Comment by KomachiSion** [comment]
接口的目的不在于国际化，而在于提示内容的自定义，不能前段写死， 必须通过接口内容返回，至于接口的实现可以变更，用于实现国际化。

**Comment by lcmarvin** [comment]
`console-guide.conf` 应该有同样的问题。
