### ISSUE TITLE
服务多实例进行滚动更新重启中断

### ISSUE THREAD

**Issue by coolqz** [alibaba/nacos#11719]
nacos版本：2.2.3
服务多实例注册到nacos上，当对服务进行滚动更新重启的时候，会中断个7,8秒，查看gateway的日志，中断的是gateway转发到了已经关闭的实例上，这种情况是否和nacos的实例健康检查时间有关，这种情况有没有办法解决

**Comment by KomachiSion** [comment]
1. 服务提供者是nacos1.x的客户端还是2.x客户端， 1.x的客户端需要停止的时候主动发起注销，否则需要等30s（默认）才会移除节点。 2.x则很快，基本关闭的同一秒就会移除。
2. gateway是否通过订阅的模式监听下游服务， 如果是自己轮询查询服务列表来更新，那么中断多少时间依赖于gateway自身的轮训间隔。 通过订阅的方式的话，才能保证秒级感知变更。
