### ISSUE TITLE
Information leak on namespace endpoint

### ISSUE THREAD

**Issue by bs352** [alibaba/nacos#11714]
Hello community, 

We had an internal security scan that revealed the endpoint: 
“/v1/console/namespaces” can be accessed anonymously even when nacos.core.auth.enabled=true

This behavior is reproducible in latest version: 2.3.0

**Expected behavior**
When auth is enabled, the endpoint should return 403 forbidden.

**Actually behavior**
Namespace information is exposed to anonymous user when auth is enabled.

**How to reproduce**
In a nacos deployment, with auth enabled.
Try access http://localhost:17003/nacos/v1/console/namespaces
All namespace information is returned as a json.

**Fix proposal**
The issue can be easily fixed by adding "Secured" annotation to the endpoints. If this approach is acceptable, can anyone assign this issue to me? I am happy to submit a PR.

**Comment by floor07** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
namespaces list is public data and api, no need to auth.
