### ISSUE TITLE
@javais Please reopen an issue and we will follow up. The current issue theme is not the one you described.

### ISSUE THREAD

**Issue by imkiven** [alibaba/nacos#1171]
@javais 请重开一个issue，我们会跟进。当前这个issue主题并不是你描述的那个问题

_Originally posted by @nkorange in https://github.com/alibaba/nacos/issues/916#issuecomment-487389493_

**Comment by imkiven** [comment]
遇到同样的问题，搜索后发现普遍存在

**Comment by nkorange** [comment]
@imkiven 请描述你的问题

**Comment by imkiven** [comment]
以集群方式部署nacos的时候，总有一个节点心跳包报server is down now,的错误，控制台页面也可以打开，可以看到配置，但是看不到注册服务

**Comment by nkorange** [comment]
> 以集群方式部署nacos的时候，总有一个节点心跳包报server is down now,的错误，控制台页面也可以打开，可以看到配置，但是看不到注册服务

说明集群组建有问题，看下Server端错误日志：{nacos.home}/logs

**Comment by imkiven** [comment]
> > 以集群方式部署nacos的时候，总有一个节点心跳包报server is down now,的错误，控制台页面也可以打开，可以看到配置，但是看不到注册服务
> 
> 说明集群有问题，看下Server端错误日志：{nacos.home}/logs

主要看了start.log 和 nacos.log 并没有发现错误信息，其他日志文件也没有报错

**Comment by nkorange** [comment]
@imkiven naming-*.log看看

**Comment by imkiven** [comment]
也没有报错信息

**Comment by nkorange** [comment]
> 也没有报错信息

Server的所有日志都没报错吗？重启是否能解决？

**Comment by nkorange** [comment]
#1091 修复了类似问题，会在1.0.1发布，不知道能否解决你的问题，到时候请你用1.0.1试下
