### ISSUE TITLE
Define different values for NODE_INFO_ERROR,NODE_DOWN_FAILURE

### ISSUE THREAD

**Issue by easynet-cn** [alibaba/nacos#11718]
**Describe the bug**
NODE_INFO_ERROR,NODE_DOWN_FAILURE have the same code "23001" in com.alibaba.nacos.api.model.v2.ErrorCode

**Expected behavior**
Define different values for NODE_INFO_ERROR,NODE_DOWN_FAILURE

**Actually behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
Default branch

**Additional context**

**Comment by KomachiSion** [comment]
welcome PR

**Comment by easynet-cn** [comment]
@i will solve it@
