### ISSUE TITLE
Nacos connection retry question

### ISSUE THREAD

**Issue by cxhello** [alibaba/nacos#11712]
### Used Component version

> Spring Boot 2.3.2.RELEASE
Spring Cloud Hoxton.SR9
Spring Cloud Alibaba 2.2.6.RELEASE
Nacos Client 2.1.2
Nacos Server 2.2.3

### Problem Description

Our applications are deployed using docker compose (including nacos). The physical machines deployed to the customer company will occasionally be restarted. Currently, we do not do the startup sequence of the containers. Sometimes the Spring Boot application will start before the Nacos Server, and I learned that the Nacos Client will keep retrying. The current problem is that after Nacos Server is started, the Spring Boot application still cannot connect to Nacos Server, but I use the docker command to manually restart the Spring Boot application and it returns to normal (docker restart nacos-client). So I'm confused and want to ask for advice.

我们的应用是采用 docker compose 方式部署的（包括nacos），部署到客户公司的物理机器偶尔会重启，当前我们没有做容器的启动顺序。有时 Spring Boot 应用会优先于 Nacos Server 启动，我了解到 Nacos Client 会一直重试。目前的问题是当 Nacos Server 启动后，Spring Boot 应用还是无法连接 Nacos Server，但我使用 docker 命令手动重启 Spring Boot 应用就恢复正常(docker restart nacos-client）。所以我比较困惑，想请教一下。

### Error log

Caused by: com.alibaba.nacos.api.exception.NacosException: user not found!

Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING

<img width="1318" alt="image" src="https://github.com/alibaba/nacos/assets/49056040/008f945f-185f-4657-8e8b-097c6c30b971">

<img width="1339" alt="image" src="https://github.com/alibaba/nacos/assets/49056040/e0741524-0351-4225-976b-6813b4ae257f">

One of these two situations will always occur.

### Remark

My issue looks similar to this. https://github.com/alibaba/nacos/issues/7481

**Comment by KomachiSion** [comment]
1. user not found is means your username or password is not right.
2. Client not connected, current status:STARTING means your application not connection to nacos, but the nacos-client is try to connect server continuously.

You can do a simple test for nacos-client re-connection:

1. only use nacos-client without any spring boot like nacos example. new NamingService and do register to localhost.
2. After the client register failed, you start any nacos server, standalone or cluster mode both ok.
3. After server start finished, see the console and found the service registered.
4. you can see the log in ${user.home}/logs/nacos/naming.log and remote.log to see the retry process.
5. use new client version please. There is no retry on register failed in old version like 2.0.X.

**Comment by cxhello** [comment]
@KomachiSion Thanks for your answer, I'll try it later.
