### ISSUE TITLE
docker部署v2.3.0，修改默认端口后，界面能访问，但是客户端注册不了

### ISSUE THREAD

**Issue by shanhm1991** [alibaba/nacos#11713]
![image](https://github.com/alibaba/nacos/assets/12453756/84eae58e-d2a5-44d8-a3f0-3a4abefe47c3)

容器中启动确实端口是11001，界面也可以访问，但是注册失败

nacos registry, x-demo register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='15.64.4.74:11001', username='', password='', endpoint='', namespace='', watchDelay=30000, logName='', service='x-demo', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={IPv6=null, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='15.64.68.33', networkInterface='', port=38080, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}},
com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING

**Comment by KomachiSion** [comment]
请查看文档， 修改端口的话，还需要开放对应的grpc端口

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
