### ISSUE TITLE
nacos-server如何从2.0.3升级到2.1.x

### ISSUE THREAD

**Issue by lizhuquan0769** [alibaba/nacos#11731]
目前生产部署了2.0.3版本3节点集群，想升级到更新的版本2.1.2，但是在官网找不到升级操作指引，请问改如何升级？

**Comment by KomachiSion** [comment]
除了1.X升级到2.0或2.1时需要特殊对双写等操作， 其他的版本升级均一致：

1. 应用新的 nacos-mysql.sql， 主要目的是确认表结构是否有变化。
2. 替换新的二进制包， 一般替换nacos/target下的jar文件
3. （可选）diff conf/application.properties 找到新增的配置内容并添加到旧的 conf/application.properties中，主要是防止某些配置参数更换了新的key。
4. （可选）diif bin/startup.sh 或 bin/startup.cmd 找到新增的启动命令并添加到旧的中，同样主要是防止某些配置参数更换了新的key。
