### ISSUE TITLE
Nacos部署对外需要开放哪些端口？只开放8848就可以了吗？另外请问集群内部需要开通哪些端口？

### ISSUE THREAD

**Issue by john-ran** [alibaba/nacos#11737]
Nacos部署对外需要开放哪些端口？只开放8848就可以了吗？另外请问集群内部需要开通哪些端口？

**Comment by KomachiSion** [comment]
请看文档
https://nacos.io/docs/latest/upgrading/200-compatibility/

**Comment by john-ran** [comment]
已知晓
