### ISSUE TITLE
Use non-public namespace configuration in nacos standalone mode to listen but not refresh configuration

### ISSUE THREAD

**Issue by 17396900506** [alibaba/nacos#1173]
如题：
在使用nacos standalone模式下 
![image](https://user-images.githubusercontent.com/44998458/57215111-8e492980-701e-11e9-8694-222ccdc122d8.png)
自定义的namespace 不能正常使用  
![image](https://user-images.githubusercontent.com/44998458/57215150-a5881700-701e-11e9-889e-7f4781289cf3.png)
能够监听到配置信息有修改，但是不能刷新配置，是什么原因？

nacos版本：
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-alibaba-nacos-config</artifactId>
            <version>0.2.1.RELEASE</version>
        </dependency>

**Comment by nkorange** [comment]
请提交到 [Spring Cloud Alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba)，应该是客户端配置有问题
