### ISSUE TITLE
ConfigController  getConfig 和 detailConfigInfo 对 tenant 的行为 不一致

### ISSUE THREAD

**Issue by zhwaaaaaa** [alibaba/nacos#11748]
Nacos 2.2.2

GET /nacos/v1/cs/configs?&group=DEFAULT_GROUP&dataId=ccdd&tenant=public&show=all

这个接口 加 show=all 访问的是 detailConfigInfo 。如果 tenant 指定为 public。获取不到 配置。不加 show=all 访问的方法是 getConfig 则可以，里边 有特殊 处理。会把 public 变为 "" 空
```tenant = NamespaceUtil.processNamespaceParameter(tenant);```

**Comment by zhwaaaaaa** [comment]
当 tenant 为public 的时候 ，增加 show=all 参数 的时候 拿不到数据
GET /nacos/v1/cs/configs?&group=DEFAULT_GROUP&dataId=ccdd&tenant=public&show=all

**Comment by KomachiSion** [comment]
tenant需要传入id，而不是命名空间的名字

public为名字，id为空字符串。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
