### ISSUE TITLE
security report

### ISSUE THREAD

**Issue by Chosir** [alibaba/nacos#1174]
## Issue Description
Hi,dear Contributers ,Insecure Permissions was found when using this system.
Type: security report

### Describe what happened (or what feature you want)
when we visited this URL:
http://192.168.30.21:8848/nacos/v1/cs/configs?search=accurate&dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&namespaceId=

json data can be obtained directly without authentication:
`{"totalCount":14,"pageNumber":1,"pagesAvailable":2,"pageItems":[{"id":6,"dataId":"order-dev.yaml","group":"DEFAULT_GROUP","content":"server:\r\n  port: 8001\r\n\r\nspring:\r\n  application:\r\n    name: order\r\n\r\n  #### 数据库配置\r\n  datasource:\r\n    druid:\r\n      url: jdbc:mysql://192.168.30.21:3306/tourism?autoReconnect=true&useSSL=false\r\n      username: root\r\n      password: 12#$%%^56\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      initial-size: 5\r\n      max-active: 30\r\n      min-idle: 5\r\n      max-wait: 60000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500\r\n\r\n  cloud:\r\n    nacos:\r\n      discovery:\r\n        server-addr: 192.168.30.21:8848\r\n\r\n#### mybatis 配置\r\nmybatis:\r\n  mapper-locations: classpath:mapper/*.xml\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n\r\n#### feign 配置\r\nfeign:\r\n  httpclient:\r\n    enabled: true\r\n","md5":null,"tenant":"","appName":""}`

Thank you for your great contribution！
### Tell us your environment
docker ,nacos version 1.0.0 ,centos7

**Comment by nkorange** [comment]
Will be fixed in #1105
