### ISSUE TITLE
Why can't I find the nacos-mysql.sql file under nacos/conf?

### ISSUE THREAD

**Issue by BlueGalaxyForest** [alibaba/nacos#11744]
## Issue Description
Why can't I find the nacos mysql.sql file under nacos/conf?
 
![6E0ZT0W BNT8}54ARQQTL 0](https://github.com/alibaba/nacos/assets/95743709/413762e7-193d-483d-ac85-9e5edb6e5e5e)

### Describe what happened (or what feature you want)
The previous version of nacos2. x had a nacos-mysql. sql file under conf, but now it cannot be found and has been replaced by derby schema. SQL and mysql schema. SQL;

### Describe what you expected to happen
I hope to enable Nacos standalone mode, but the provided SQL files are all cluster related

 
### Tell us your environment
CentOS7;nacos2.2.3

**Comment by Daydreamer-ia** [comment]
I remember that the mysql-schema.sql file is the same, just different file name. Which data source you use will not affect the deploy mode you decide.

**Comment by BlueGalaxyForest** [comment]
Thanks for your reply!
