### ISSUE TITLE
docker nacos

### ISSUE THREAD

**Issue by emp-java** [alibaba/nacos#11741]
可以在启动参数里加上初始化时用户名密码的配置吗，默认nacos/nacos

**Comment by opencmit2** [comment]
nacos 用户密码是在数据库导入的时候设置的。
![1708326425767](https://github.com/alibaba/nacos/assets/112474703/5401b67e-82e1-4409-82ac-e6bdd29da755)

**Comment by KomachiSion** [comment]
初始化集群的时候可以自行在数据库中修改密码。
