### ISSUE TITLE
question：Does Nacos only support polling for querying service online/offline status?

### ISSUE THREAD

**Issue by ShenFeng312** [alibaba/nacos#11743]
Could it provide a watch mechanism similar to Zookeeper?

**Comment by Daydreamer-ia** [comment]
Nacos v1.x provides poll and push mode for service directory notify. It is the same in Nacos v2.x. But the channel in 2.x is powdered by grpc, while 1.x is using udp and http.

**Comment by Daydreamer-ia** [comment]
if you wanna to add notify callback logic, you can use listener like [example](https://github.com/alibaba/nacos/blob/develop/example/src/main/java/com/alibaba/nacos/example/ConfigExample.java)
