### ISSUE TITLE
关于nacos注册中心，异地多活部署方式的讨论

### ISSUE THREAD

**Issue by floor07** [alibaba/nacos#11758]
nacos2.0+，引入了AP模式的Distro协议，该协议支持nacos注册的实例同步，应该不需要nacos-sync了吧？
仅仅将多中心部署一个大集群即可吧

**Comment by seedscoder** [comment]
不知道这个能不能解决你的疑问
> NacosSync是一个支持多种注册中心的同步组件,基于Spring boot开发框架,数据层采用Spring Data JPA,遵循了标准的JPA访问规范,支持多种数据源存储,默认使用Hibernate实现,更加方便的支持表的自动创建更新

[https://nacos.io/zh-cn/docs/nacos-sync.html](url)

**Comment by Daydreamer-ia** [comment]
`Distro` 是**集群内**服务数据同步协议，`Distro` 协议的 `verify` 心跳不可能跨很大区域的，如果多集群使用 `Distro` 做数据同步，延迟会很大的。而且我觉得多集群服务数据同步是依赖外部组件的， `nacos-sync`  用定时任务的方式，去连接集群以 `sdk` 去拉取服务信息，然后再注册到目标集群内去的，这样不同集群也不会有任何耦合关系。

**Comment by floor07** [comment]
> `Distro` 是**集群内**服务数据同步协议，`Distro` 协议的 `verify` 心跳不可能跨很大区域的，如果多集群使用 `Distro` 做数据同步，延迟会很大的。`nacos` 多集群服务数据同步是依赖外部组件的， `nacos-sync` 用定时任务的方式，去连接集群以 `sdk` 去拉取服务信息，然后再注册到目标集群内去的，这样不同集群也不会有任何耦合关系。

专业，关于Distro我看看

**Comment by KomachiSion** [comment]
Distro不适合做集群间的数据一致性， 因为它是一个星形AP一致性协议， 如果需要将两个集群数据组合成一致，就必须将两个集群组合成一个大集群，不仅对Server的压力指数级增加， 同时还因为不同地域的高延迟导致大概率重复进行同步。

目前nacos-sync可以作为多集群`服务`数据同步的一个解决方案，但是一般情况下nacos-sync是作为迁移工具使用， 长期运行需要自行保证nacos-sync的稳定性及容灾能力建设。

**Comment by floor07** [comment]
总结:  异地多活组成大集群，大概率有2个问题，如果节点多server同步压力大，最终一致延迟高。

**Comment by ddl1228** [comment]
nacos-sync只会同步服务的注册信息，不会同步服务的配置信息吗？因为我们使用nacos既作为注册中心也作为配置中心
