### ISSUE TITLE
Question: 一共有几个地方有登录？

### ISSUE THREAD

**Issue by gMan1990** [alibaba/nacos#11757]
我知道的，看起来有2个

1 控制台 https://nacos.io/zh-cn/docs/v2/guide/admin/console-guide.html
2 nacos-client.jar 里有密码的配置项，不过我没设置

请问这2个地方，是共用的吗？如果不是共用的，如果修改第2处的密码

**Comment by 985492783** [comment]
是共用的，client的用户名密码是用来登陆的，在控制台可以控制用户的权限之类的

**Comment by gMan1990** [comment]
@985492783 1. 控制台，`默认用户名/密码为： nacos/nacos`。然后我把密码改了。
2. nacos-client.jar, 我没配置 `nacos.config.username` 和 `password`，它也能读取到内容。点解？

**Comment by 985492783** [comment]
nacos客户端也支持ak，sk的鉴权方式，可看[Nacos鉴权](https://nacos.io/docs/latest/plugin/auth-plugin/#%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8F%92%E4%BB%B6)，至于没配置就能登陆，或许是你没有打开nacos.core.auth.enabled鉴权能力
