### ISSUE TITLE
[Feature] MemberLookup 的插件功能

### ISSUE THREAD

**Issue by fanthos** [alibaba/nacos#11756]
**Is your feature request related to a problem? Please describe.**

目前 MemberLookup 有2个并且不支持扩展。
希望集群部署的 MemberLookup 加入插件支持，可以更方便的进行集群部署（比如不需要共享存储）

**Describe the solution you'd like**

MemberLookup 加入基于DNS的服务发现
- java.net.InetAddress#getAllByName(java.lang.String)

或者基于数据库的服务发现
- 数据库表中每一行是每一个服务实例

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangyang-0722** [comment]
基于数据库的服务发现可以通过地址服务器寻址实现吧

**Comment by fanthos** [comment]
> 基于数据库的服务发现可以通过地址服务器寻址实现吧

是配置环境变量吗？我现在这么用的，但是不能动态扩容。最新代码中只有本地文件（支持监听变更）和环境变量两种方式，其他的不直接支持。

目前dns只支持单个ip，peerfinder支持多ip但是需要单独的进程。

**Comment by publicize-y** [comment]
nacos.core.member.lookup.type=address-server,这个我看源码是支持动态扩容的啊，有个线程一直在轮询

**Comment by godhth** [comment]
可以使用nacos.core.member.lookup.type=address-server，地址服务器，在地址服务器里自定义实现相关逻辑

**Comment by fanthos** [comment]
找到了个文档，好像这个需要用address-server来扩容，而不是内置插件

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/8310.

The work has been processing by students. If it finished, will be released by 2.4.0. Otherwise it will be released by 3.0.
