### ISSUE TITLE
Nacos-client 1.0 and spring boot 2 environment can not use the file specified by Dlogging.config

### ISSUE THREAD

**Issue by icc99** [alibaba/nacos#1175]
## Issue Description

 *bug report* 

### Describe what happened (or what feature you want)

启动的时候指定-Dlogging.config=log4j2.xml
但log4j2.xml里面的配置都不生效, 每次生效的都是 classpath:log4j2.xml
**但如果使用nacos-client 0.2.1版本就没有这个问题**

### Describe what you expected to happen
-Dlogging.config=log4j2.xml 应该这里指定的文件生效

### How to reproduce it (as minimally and precisely as possible)

1. 环境
spring boot 2.0.9
nacos-client 1.0
centos7 
2. 
启动参数 -Dlogging.config=log4j2.xml
3. 
启动

### Tell us your environment
spring boot 2.0.9
nacos-client 1.0
centos7

**Comment by icc99** [comment]
暂时通过修改 LogUtils源码解决
```
public class LogUtils {

    public static final Logger NAMING_LOGGER = LoggerFactory.getLogger(LogUtils.class);


    public static Logger logger(Class<?> clazz) {
        return getLogger(clazz);
    }

}
```

**Comment by nkorange** [comment]
Use ```nacos.logging.config``` in 1.0.0
