### ISSUE TITLE
Registration Center: Can services in different namespaces be called from each other?

### ISSUE THREAD

**Issue by github-lig** [alibaba/nacos#1176]
对于某些公共服务，如果注册到不同的命名空间下，我们如何相互调用呢？刚才测试了一下，一个服务不可以注册到多个命名空间下。
比如网关进行路由转发的时候，如果和微服务不在一个命名空间下，就不可以直接进行转发了吧？

**Comment by nkorange** [comment]
你可以只用默认的命名空间啊

**Comment by 2417796669** [comment]
那命名空间对于服务注册是否有些鸡肋了，基本上开发，测试，线上都会有一套Nacos。在开发环境下，如果我们都用同一个命名空间，那时不时的就会出现请求到别人的本地环境，如果别人还在Debug，就很难受。

**Comment by nkorange** [comment]
明白你的意思了，有些服务是命名空间隔离，有的是公共可见的，貌似需求是合理的。

**Comment by jifengnan** [comment]
@nkorange 
namespace的用处我也感到很困惑，感觉目前对单一公司来说这个属性意义不大。

在nacos官网上提供的一个场景是用于开发环境，测试环境，生产环境的隔离。但事实上应该没有公司会让生产环境和测试环境共用一个注册中心，因为这样做会有很多隐患，而好处却实在有限。

在 [阿里巴巴基于 Nacos 实现环境隔离的实践](https://mp.weixin.qq.com/s?__biz=MzI0NTE4NjA0OQ==&mid=2658360200&idx=1&sn=9b1d343a7d49ac75d90a1210d69219a9&chksm=f2d590e6c5a219f00609cf44a9bb06c8062f5f760b14919b8b69571fa41c52342c6c49d83de9&mpshare=1&scene=2&srcid=&from=timeline&isappinstalled=0&ascene=45&devicetype=iOS10.0.2&version=1700032a&nettype=WIFI&abtest_cookie=BAABAAoACwASABMABQAjlx4AW5keAL%2BZHgDZmR4A3JkeAAAA&lang=zh_CN&fontScale=100&pass_ticket=%2BxRgszwmzDP43JfSFflCUDS6JlKABV0Y3M8eA%2BXUJ0drd7rlA89n3i52eVO96O%2FY&wx_header=1) 中提到了子环境的概念，也就是说，生产环境可能会根据不同标准进一步隔离成若干个独立的子环境。这似乎可以成为使用namespace的一个场景。

另外，就我的理解，nacos的前身是阿里云使用的某款中间件，而阿里云是面向很多企业的，这些企业间的注册信息配置信息肯定是不希望被互相访问的，所以在阿里云这种场景下namespace就显得很有必要了。

不知道我的理解是否正确。

**Comment by nkorange** [comment]
@jifengnan namespace主要是进行业务隔离的，多个业务或者部门可以用一个Nacos，但是数据都相互屏蔽。

**Comment by bayernjava** [comment]
> 明白你的意思了，有些服务是命名空间隔离，有的是公共可见的，貌似需求是合理的。

这个需求很普遍，特别是开发环境，有些通用的服务对全员可见，有些则只能自己调用。之前都是通过eureka的region和zone来实现的，nacos有类似的功能么？

**Comment by syzpig** [comment]
Excuse me, is there any solution to this need? Service isolation and development environment isolation

**Comment by chuntaojun** [comment]
> Excuse me, is there any solution to this need? Service isolation and development environment isolation

I'll try to solve it，You can communicate with me by email or by nailing dvx6ro

**Comment by dotnet123** [comment]
Waiting for the latest news

**Comment by chuntaojun** [comment]
这里给一个解决方案，代码已实现

> 大致思路

* 用户仅需要设置其他服务所在的namespace，其他全部由nacos内部完成服务调用
* 查询时
        * 优先进行同namespace下的服务查询
        * 查询失败，判断是否有other-namespace参数
            * 存在：根据public-space参数的顺序顺序查找{最先匹配}
            * 不存在：按照原有逻辑处理

> 使用方法

how to use share-namespace

if you want to set group with share-namespace, follow this example(group parameter not required)

```properties
shareNamespace={namespaceId[:group]},{namespaceId[:group]} 
```

```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = NamingApp.class, properties = {"server.servlet.context-path=/nacos"},
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class SelectServiceInShareNamespace_ITCase {

    private NamingService naming1;
    private NamingService naming2;
    @LocalServerPort
    private int port;
    @Before
    public void init() throws Exception{
        NamingBase.prepareServer(port);
        if (naming1 == null) {
            Properties properties = new Properties();
            properties.setProperty(PropertyKeyConst.SERVER_ADDR, "127.0.0.1"+":"+port);
            properties.setProperty(PropertyKeyConst.SHARE_NAMESPACE, "57425802-3058-4507-9a73-3229b9f00a36");
            naming1 = NamingFactory.createNamingService(properties);

            Properties properties2 = new Properties();
            properties2.setProperty(PropertyKeyConst.SERVER_ADDR, "127.0.0.1"+":"+port);
            properties2.setProperty(PropertyKeyConst.NAMESPACE, "57425802-3058-4507-9a73-3229b9f00a36");
            naming2 = NamingFactory.createNamingService(properties2);
        }
        while (true) {
            if (!"UP".equals(naming1.getServerStatus())) {
                Thread.sleep(1000L);
                continue;
            }
            break;
        }
    }

    @Test
    public void testSelectInstanceInShareNamespaceNoGroup() throws NacosException, InterruptedException {
        String service1 = randomDomainName();
        String service2 = randomDomainName();
        naming1.registerInstance(service1, "127.0.0.1", 90);
        naming2.registerInstance(service2, "127.0.0.2", 90);

        Thread.sleep(1000);

        List<Instance> instances = naming1.getAllInstances(service2);
        Assert.assertEquals(1, instances.size());
        Assert.assertEquals(service2, NamingUtils.getServiceName(instances.get(0).getServiceName()));
    }

    @Test
    public void testSelectInstanceInShareNamespaceWithGroup() throws NacosException, InterruptedException {
        String service1 = randomDomainName();
        String service2 = randomDomainName();
        naming2.registerInstance(service1, groupName, "127.0.0.1", 90);
        naming3.registerInstance(service2, "127.0.0.2", 90);

        Thread.sleep(1000);

        List<Instance> instances = naming3.getAllInstances(service1);
        Assert.assertEquals(1, instances.size());
        Assert.assertEquals(service1, NamingUtils.getServiceName(instances.get(0).getServiceName()));
        Assert.assertEquals(groupName, NamingUtils.getServiceName(NamingUtils.getGroupName(instances.get(0).getServiceName())));
    }

}
```

> 自编译使用

自编译使用：https://github.com/chuntaojun/nacos/tree/soc2019_namespace

**Comment by roadog** [comment]
> 这里给一个解决方案，代码已实现
> 
> > 大致思路
> 
> * 用户仅需要设置其他服务所在的namespace，其他全部由nacos内部完成服务调用
> * 查询时
>   * 优先进行同namespace下的服务查询
>   * 查询失败，判断是否有other-namespace参数
>   * 存在：根据public-space参数的顺序顺序查找{最先匹配}
>   * 不存在：按照原有逻辑处理
> 
> > 使用方法
> 
> how to use share-namespace
> 
> if you want to set group with share-namespace, follow this example(group parameter not required)
> 
> ```ini
> shareNamespace={namespaceId[:group]},{namespaceId[:group]} 
> ```
> 
> ```java
> @RunWith(SpringRunner.class)
> @SpringBootTest(classes = NamingApp.class, properties = {"server.servlet.context-path=/nacos"},
>     webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
> public class SelectServiceInShareNamespace_ITCase {
> 
>     private NamingService naming1;
>     private NamingService naming2;
>     @LocalServerPort
>     private int port;
>     @Before
>     public void init() throws Exception{
>         NamingBase.prepareServer(port);
>         if (naming1 == null) {
>             Properties properties = new Properties();
>             properties.setProperty(PropertyKeyConst.SERVER_ADDR, "127.0.0.1"+":"+port);
>             properties.setProperty(PropertyKeyConst.SHARE_NAMESPACE, "57425802-3058-4507-9a73-3229b9f00a36");
>             naming1 = NamingFactory.createNamingService(properties);
> 
>             Properties properties2 = new Properties();
>             properties2.setProperty(PropertyKeyConst.SERVER_ADDR, "127.0.0.1"+":"+port);
>             properties2.setProperty(PropertyKeyConst.NAMESPACE, "57425802-3058-4507-9a73-3229b9f00a36");
>             naming2 = NamingFactory.createNamingService(properties2);
>         }
>         while (true) {
>             if (!"UP".equals(naming1.getServerStatus())) {
>                 Thread.sleep(1000L);
>                 continue;
>             }
>             break;
>         }
>     }
> 
>     @Test
>     public void testSelectInstanceInShareNamespaceNoGroup() throws NacosException, InterruptedException {
>         String service1 = randomDomainName();
>         String service2 = randomDomainName();
>         naming1.registerInstance(service1, "127.0.0.1", 90);
>         naming2.registerInstance(service2, "127.0.0.2", 90);
> 
>         Thread.sleep(1000);
> 
>         List<Instance> instances = naming1.getAllInstances(service2);
>         Assert.assertEquals(1, instances.size());
>         Assert.assertEquals(service2, NamingUtils.getServiceName(instances.get(0).getServiceName()));
>     }
> 
>     @Test
>     public void testSelectInstanceInShareNamespaceWithGroup() throws NacosException, InterruptedException {
>         String service1 = randomDomainName();
>         String service2 = randomDomainName();
>         naming2.registerInstance(service1, groupName, "127.0.0.1", 90);
>         naming3.registerInstance(service2, "127.0.0.2", 90);
> 
>         Thread.sleep(1000);
> 
>         List<Instance> instances = naming3.getAllInstances(service1);
>         Assert.assertEquals(1, instances.size());
>         Assert.assertEquals(service1, NamingUtils.getServiceName(instances.get(0).getServiceName()));
>         Assert.assertEquals(groupName, NamingUtils.getServiceName(NamingUtils.getGroupName(instances.get(0).getServiceName())));
>     }
> 
> }
> ```
> 
> > 自编译使用
> 
> 自编译使用：https://github.com/chuntaojun/nacos/tree/soc2019_namespace

We really need this implementation !!!!!!

**Comment by chuntaojun** [comment]
@roadog 这个是可以解决你们的需求是吗

**Comment by roadog** [comment]
> @roadog 这个是可以解决你们的需求是吗？是否自编译了这个分支去尝试了下

We have not tried this branch yet, but we need this solution.

**Comment by AllenJol** [comment]
首先我是一名运维人员。我们有两个项目，每个项目都有三套环境。UAT、pre、prod。然后三套配置文件。两个项目用了同一个nacos，以命名空间来区分三个环境。但是不同的命名空间貌似无法互相访问配置文件。导致必须将配置放在同一个命名空间下。但是这又有一个DataID不能相同的必要条件。如果相同则会提示冲突。

**Comment by 2417796669** [comment]
> 首先我是一名运维人员。我们有两个项目，每个项目都有三套环境。UAT、pre、prod。然后三套配置文件。两个项目用了同一个nacos，以命名空间来区分三个环境。但是不同的命名空间貌似无法互相访问配置文件。导致必须将配置放在同一个命名空间下。但是这又有一个DataID不能相同的必要条件。如果相同则会提示冲突。

难道你们是想不同的环境共用某些配置吗？

**Comment by 2417796669** [comment]
> 首先我是一名运维人员。我们有两个项目，每个项目都有三套环境。UAT、pre、prod。然后三套配置文件。两个项目用了同一个nacos，以命名空间来区分三个环境。但是不同的命名空间貌似无法互相访问配置文件。导致必须将配置放在同一个命名空间下。但是这又有一个DataID不能相同的必要条件。如果相同则会提示冲突。

**Comment by 2417796669** [comment]
@AllenJol 难道你们是想不同的环境共用某些配置吗？ 如果像这样的话，可以考虑用groupid

**Comment by chuntaojun** [comment]
> @AllenJol 你们是想不同的环境共用某些配置吗？ 如果像这样的话，可以考虑用groupid

agree

**Comment by AllenJol** [comment]
您好！
   是这样的。我现在的情况是开发反馈：两个项目，两个命名空间，同一套测试环境下，A项目无法访问B项目下的某些配置。但是开发又想通过不同命名空间，A项目访问B项目的配置。




------------------ 原始邮件 ------------------
发件人: "ktoto"<notifications@github.com>;
发送时间: 2019年7月12日(星期五) 下午3:45
收件人: "alibaba/nacos"<nacos@noreply.github.com>;
抄送: "Ever丶丨淡忘丨"<471733951@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/nacos] Registration Center: Can services in differentnamespaces be called from each other? (#1176)



 
首先我是一名运维人员。我们有两个项目，每个项目都有三套环境。UAT、pre、prod。然后三套配置文件。两个项目用了同一个nacos，以命名空间来区分三个环境。但是不同的命名空间貌似无法互相访问配置文件。导致必须将配置放在同一个命名空间下。但是这又有一个DataID不能相同的必要条件。如果相同则会提示冲突。
  
难道你们是想不同的环境共用某些配置吗？

**Comment by AllenJol** [comment]
但是好像group的话没法指定注册中心的group。之前开发有提到过这个问题

**Comment by 2417796669** [comment]
@AllenJol 现在注册中心确实无法指定group。你们开发的需求现在应该是满足不了，A项目指定了命名空间后，就不可以访问另一个命名空间下的配置了。建议还是两个项目放到同一个namespace下。

**Comment by AllenJol** [comment]
嗯 非常感谢您的帮助。我这边现在和nacos微信群另一位群友的沟通下发现用另一种方法就是同一个ns下，dataid配置使用项目简称的前缀来区分

**Comment by AllenJol** [comment]
有需要的小伙伴也可以尝试这种方法，临时解决这个问题

**Comment by chuntaojun** [comment]
> @AllenJol 现在注册中心确实无法指定group。你们开发的需求现在应该是满足不了，A项目指定了命名空间后，就不可以访问另一个命名空间下的配置了。建议还是两个项目放到同一个namespace下。

可以指定group的吧

[wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config)

spring.cloud.nacos.config.ext-config[2].data-id=ext-config-common03.properties
spring.cloud.nacos.config.ext-config[2].group=REFRESH_GROUP
spring.cloud.nacos.config.ext-config[2].refresh=true

**Comment by 2417796669** [comment]
注册服务没有group这一说吧。只区分了namespace




------------------ 原始邮件 ------------------
发件人: "liaochuntao"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 下午4:07
收件人: "alibaba/nacos"<nacos@noreply.github.com>; 
抄送: "2417796669"<2417796669@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [alibaba/nacos] Registration Center: Can services in differentnamespaces be called from each other? (#1176)



 
@AllenJol 现在注册中心确实无法指定group。你们开发的需求现在应该是满足不了，A项目指定了命名空间后，就不可以访问另一个命名空间下的配置了。建议还是两个项目放到同一个namespace下。
  
可以指定group的吧
 
wiki
 
spring.cloud.nacos.config.ext-config[2].data-id=ext-config-common03.properties
 spring.cloud.nacos.config.ext-config[2].group=REFRESH_GROUP
 spring.cloud.nacos.config.ext-config[2].refresh=true

**Comment by chuntaojun** [comment]
> 注册服务没有group这一说吧。只区分了namespace
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "liaochuntao"<notifications@github.com>; 发送时间: 2019年7月12日(星期五) 下午4:07 收件人: "alibaba/nacos"<nacos@noreply.github.com>; 抄送: "2417796669"<2417796669@qq.com>; "State change"<state_change@noreply.github.com>; 主题: Re: [alibaba/nacos] Registration Center: Can services in differentnamespaces be called from each other? (#1176) @AllenJol 现在注册中心确实无法指定group。你们开发的需求现在应该是满足不了，A项目指定了命名空间后，就不可以访问另一个命名空间下的配置了。建议还是两个项目放到同一个namespace下。 可以指定group的吧 wiki spring.cloud.nacos.config.ext-config[2].data-id=ext-config-common03.properties spring.cloud.nacos.config.ext-config[2].group=REFRESH_GROUP spring.cloud.nacos.config.ext-config[2].refresh=true — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

服务没有开放，但是配置可以，对于服务的跨namespace你可以看看我提供的解决方案是否满足需求

**Comment by 2417796669** [comment]
嗯，我们这边会尝试一下



------------------ 原始邮件 ------------------
发件人: "liaochuntao"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 下午4:11
收件人: "alibaba/nacos"<nacos@noreply.github.com>; 
抄送: "2417796669"<2417796669@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [alibaba/nacos] Registration Center: Can services in differentnamespaces be called from each other? (#1176)



 
注册服务没有group这一说吧。只区分了namespace
 …
 ------------------ 原始邮件 ------------------ 发件人: "liaochuntao"notifications@github.com; 发送时间: 2019年7月12日(星期五) 下午4:07 收件人: "alibaba/nacos"nacos@noreply.github.com; 抄送: "2417796669"2417796669@qq.com; "State change"state_change@noreply.github.com; 主题: Re: [alibaba/nacos] Registration Center: Can services in differentnamespaces be called from each other? (#1176) @AllenJol 现在注册中心确实无法指定group。你们开发的需求现在应该是满足不了，A项目指定了命名空间后，就不可以访问另一个命名空间下的配置了。建议还是两个项目放到同一个namespace下。 可以指定group的吧 wiki spring.cloud.nacos.config.ext-config[2].data-id=ext-config-common03.properties spring.cloud.nacos.config.ext-config[2].group=REFRESH_GROUP spring.cloud.nacos.config.ext-config[2].refresh=true — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
  
服务没有开放，但是配置可以，对于服务的跨namespace你可以看看我提供的解决方案是否满足需求

**Comment by chuntaojun** [comment]
我觉得你们是不是可以用group的概念做这个事情？

**Comment by chuntaojun** [comment]
We believe that the group can solve this problem, before the scheme and the concept of nacos exist discrepancy, so new scheme pr connection as below
