### ISSUE TITLE
Failed to compile and install nacos from source

### ISSUE THREAD

**Issue by h2cone** [alibaba/nacos#11767]
**Describe the bug**

Following the compilation instructions from [CONFIGURE ENCRYPTION](https://nacos.io/en/docs/latest/plugin/config-encryption-plugin/), it is required to compile nacos and install it into the local repository before compiling the plugin. However, an error occurred after running the build command:

```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.2.2:jar (default-jar) on project nacos-default-plugin-all: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :nacos-default-plugin-all
```

**How to Reproduce**

1. `git clone git@github.com:alibaba/nacos.git`
2. `cd nacos && mvn -B clean package install -Dmaven.test.skip=true`

**Desktop (please complete the following information):**
 - OS: windows-x86_64
 - Version: nacos develop, Apache Maven 3.9.6

**Additional context**

This is the compilation and installation log: [build.log](https://github.com/alibaba/nacos/files/14371754/build.log)

**Comment by KomachiSion** [comment]
Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.2.2:jar

please check your maven source by yourself.

BTW, The CI build, and my local env build with source code both ok. The code is low possible with problem.
