### ISSUE TITLE
Unable to create the directory [H:..\nacos\bin\file:.] to use as the base directory

### ISSUE THREAD

**Issue by Hugeman-piexl** [alibaba/nacos#11772]
![image](https://github.com/alibaba/nacos/assets/85328019/815a96d1-33f9-4a26-8d36-282ee63612ae)

start Nacos2.1.0 and report an error,like above!!!
it means nacos need a directory which name is file:. to use .However it is impossible to create in my windows!

![image](https://github.com/alibaba/nacos/assets/85328019/de423070-ae52-4d22-8e4c-eaf00b3c3211)
In linux , it is OK to create.

How to solve it?
Please!!!

**Comment by KomachiSion** [comment]
Upgrade new version please, it seems solved in new version.

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.
