### ISSUE TITLE
为什么最新的nacos-naming,nacos-consistency这些模块jar包在Maven仓中找不到

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#11779]
请问一下为什么有些nacos的模块在[maven ](https://mvnrepository.com/artifact/com.alibaba.nacos?p=1)Maven仓中没有，有些模块的版本也缺失，如naming，不把nacos的全部jar包传到maven仓是出于什么原因的考虑？

**Comment by 985492783** [comment]
因为只有客户端要推仓库，naming，consistency属于服务端能力，没有项目服务端推依赖的，原本也不是为了开放给别人引用，如果有需要可以拉develop分支自行打包
