### ISSUE TITLE
配置中心多人修改覆盖问题 

### ISSUE THREAD

**Issue by ZhiQinIsZhen** [alibaba/nacos#11776]
在历史Issue中，看到别人已经提过这个功能。
回复是：可以用管理来避免，但是程序就是避免人为约束。
加一个提示也是好的，其实不是同时提交的问题。
是有些人会在修改前，就打开编辑页面没有退出，然后大家先后提交后就会覆盖之前编辑内容。
希望能增加一个版本提示。
有些人长时间占用编辑页面却不知道在提交时覆盖了别人的内容，有一个提示会友好一点。

**Comment by 985492783** [comment]
看了一下后端已经用cas接口，貌似前端加个md5字段和提示下就ok

**Comment by shiyiyue1102** [comment]
> 看了一下后端已经用cas接口，貌似前端加个md5字段和提示下就ok

是的，编辑页面保存下当前的md5值，在更新的时候把expectMd5传给后端做下cas校验即可

**Comment by geekerzhou** [comment]
+1 这个问题极其蛋疼，线上还可以管理下。测试环境如何管理，大家并行开发多个分支多个功能。经常相互覆盖。

**Comment by 985492783** [comment]
@i will solve it@

**Comment by 985492783** [comment]
has been fixed
