### ISSUE TITLE
Docker 集群部署，重启后 cluster.conf 文件内容被自动清空

### ISSUE THREAD

**Issue by troyzhxu** [alibaba/nacos#11770]
## 运行环境
* 使用镜像（Image）: nacos/nacos-server:v2.2.3-slim
* 运行方式（集群默式，3 个节点）：
```
docker run -d --name nacos-server \
    --log-opt max-size=10m --log-opt max-file=5 \
    -e SPRING_DATASOURCE_PLATFORM=mysql \
    -e MYSQL_SERVICE_HOST=xxxx.mysql.rds.aliyuncs.com \
    -e MYSQL_SERVICE_DB_NAME=xxxx \
    -e MYSQL_SERVICE_USER=xxxx \
    -e MYSQL_SERVICE_PASSWORD='xxxx' \
    -e NACOS_AUTH_ENABLE=true \
    -e NACOS_AUTH_TOKEN=xxxx \
    -e NACOS_AUTH_IDENTITY_KEY=xxx \
    -e NACOS_AUTH_IDENTITY_VALUE=xxx \
    -v /srv/nacos-server/conf:/home/nacos/conf \
    -v /srv/nacos-server/logs:/home/nacos/logs \
    -p 7848:7848 -p 8848:8848 -p 9848:9848 -p 9849:9849 \
    nacos/nacos-server:v2.2.3-slim
```

其中将容器内的 `/home/nacos/conf` 目录映射到了宿主机的 `/srv/nacos-server/conf` 目录，用与放置配置文件

## 问题重现（在其中一个节点 172.19.0.21 上重启）

一旦重启了 Docker 容器，则 cluster.conf 配置文件就被自动清空，如图：

![image](https://github.com/alibaba/nacos/assets/29403889/3b665e03-0a19-4d9c-be64-dd3244b2d2fe)

重启后，Docker 容器状态正常：

![image](https://github.com/alibaba/nacos/assets/29403889/1ad127d5-c9b9-4b98-8efe-93f6512a2792)

另外只有 `cluster.conf` 这一个文件会被清空，另外的 `application.properties` 则不会，配置在里面的内容仍然保留：

![image](https://github.com/alibaba/nacos/assets/29403889/7448f977-723c-4325-9d14-4b1eef25c168)

集群配置文件中的 172.19.0.21 是本机 IP，另外两个节点的 172.19.0.2 与 172.19.77.186 均正常运行着 Nacos 服务，并且 cluster.conf 配置正常。

请问这个问题可能是什么造成的，应该从哪里着手排查？

**Comment by troyzhxu** [comment]
> 分别映射到三个conf文件

不太明白你表单的意思，我现在是整个目录做的映射：
```
-v /srv/nacos-server/conf:/home/nacos/conf
```
这样不行吗？

**Comment by troyzhxu** [comment]
> 分别映射到三个conf文件

你的意思三个配置文件单独映射吗？

```
-v /srv/nacos-server/conf/application.properties:/home/nacos/conf/application.properties \
-v /srv/nacos-server/conf/cluster.conf:/home/nacos/conf/cluster.conf  \
-v /srv/nacos-server/conf/nacos-logback.xml:/home/nacos/conf/nacos-logback.xml \
```
我试了，效果一样的，仍然一启动 cluster.conf 就被清空：

![image](https://github.com/alibaba/nacos/assets/29403889/c9793d58-709e-41d5-9416-46cc389fb92b)

**Comment by 985492783** [comment]
我理解错了

**Comment by troyzhxu** [comment]
解决了，原来 docker 启动需要使用参数来指定集群地址：
```
-e NACOS_SERVERS='172.19.77.186:8848 172.19.0.21:8848 172.19.0.2:8848'
-e NACOS_SERVER_IP='172.19.0.21'
```

**Comment by pigmanwlj** [comment]
> 解决了，原来 docker 启动需要使用参数来指定集群地址：
> 
> ```
> -e NACOS_SERVERS='172.19.77.186:8848 172.19.0.21:8848 172.19.0.2:8848'
> -e NACOS_SERVER_IP='172.19.0.21'
> ```

搞定搞定，got it,  Thx
