### ISSUE TITLE
一个服务可以注册到多个命名空间吗？比方说网关（Spring Cloud Gateway）服务

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/nacos#11785]
您好
一个服务可以注册到多个命名空间吗？比方说网关（Spring Cloud Gateway）服务，我多个项目在不同命名空间，现在网关也是有对应的数量，可以仅不是一个网关，但注册到各项目的命名空间吗，各项目共用一个网关

**Comment by 985492783** [comment]
可以，但是网关拉服务列表要看网关实现有没有这个能力，而且命名空间是用来隔离的，这样搞就没有意义了，如果想区分可以通过group区分同名服务

**Comment by jaimyjie** [comment]
> 可以，但是网关拉服务列表要看网关实现有没有这个能力，而且命名空间是用来隔离的，这样搞就没有意义了，如果想区分可以通过group区分同名服务

要怎么做，我测试下

**Comment by jaimyjie** [comment]
> 越过框架层注入NamingService这个类自己注册就行了，但是最好别这么做，框架层帮你组装了服务发现和注册，有可能你这么搞之后拿不到服务列表的，理论上来讲应该是网关层隔离命名空间的，但是基础微服务可以注册多个命名空间被调用，而不是你这种

谢谢
