### ISSUE TITLE
[Optimize] optimize the use of map

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#11782]
很多旧代码，对map使用不当，重复调用多次hash，可以优化掉。
例如：
INSTANCE = ConcurrentHashMap<>();天然带锁
![image](https://github.com/alibaba/nacos/assets/73023513/a21a93f7-b32e-4151-8d5b-afb00ad21414)
又例如：
![image](https://github.com/alibaba/nacos/assets/73023513/3f777585-3bc2-4861-a4e2-397fe36aca1a)
代码中有很多，本次一次优化

**Comment by Henriqu331** [comment]
I'll look for the answer ok

**Comment by KomachiSion** [comment]
建议分批次提交，或者按照模块提交

**Comment by KomachiSion** [comment]
PR合并了 不过建议下次分模块提交

**Comment by 985492783** [comment]
> PR合并了 不过建议下次分模块提交

ok
