### ISSUE TITLE
How can I change the max number of configurations in one namespace?

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/nacos#1178]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Now, the max number of configurations in one namespace is 200.

### Describe what you expected to happen
I want to change this number upper. Or how can I share configuration over namespace?

### How to reproduce it (as minimally and precisely as possible)
1. 
2. 
3. 

### Tell us your environment
nacos-server-1.0.0

**Comment by nkorange** [comment]
This number is not in use now, you can create more than 200 configurations.
