### ISSUE TITLE
remove httpclient from NamingClientProxy

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#11792]
这个httpclient应该可以删了吧，我理解client也可以无损升级
![image](https://github.com/alibaba/nacos/assets/73023513/e96126e7-9fef-4a2d-898d-ce3ddfe5ef18)

**Comment by KomachiSion** [comment]
暂时不能删除，因为有部分接口需要兼容使用http请求（比如注册/注销持久化服务）。

同时极少量用户有使用到MaintainaNamingService，其中均会用到Http请求。

等到MaintainaNamingService从nacos-client中独立、并且给予一段时间过渡后，再移除，然后通过文档和FaQ的方式告知社区，新版本client（比如3.0），注册持久化服务时不再支持2.3之前的服务端。
