### ISSUE TITLE
fallback version bug

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1179]
控制台发现有个bug   之前我在操作版本回退的时候  回退成功发现配置文件删除了
刚刚同事回退成功  发现配置文件也没有了   这个bug偶尔会出现

**Comment by nkorange** [comment]
如果配置只有一个版本，回退就会删除配置

**Comment by 1346735074** [comment]
但是  我这两个配置不是一个版本   有5 6个

**Comment by 1346735074** [comment]
偶尔会出现回退删除  然后创建了  历史版本是在的
这样的话回退  线上很危险的

**Comment by nkorange** [comment]
> 偶尔会出现回退删除 然后创建了 历史版本是在的
> 这样的话回退 线上很危险的

这是设计上是这样的，可以讲讲你的建议
