### ISSUE TITLE
logback.xml Incorrect configuration

### ISSUE THREAD

**Issue by heihei180** [alibaba/nacos#11793]
**Describe the bug**
 this file example/src/main/resources/logback.xml config the log file path is error.

line 23 and line 26.
like this:

```xml

        <file>/Users/xiweng.yy/logs/nacos/perf.log</file>
        
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>/Users/xiweng.yy/logs/nacos/perf.log.%i</fileNamePattern>
            <maxIndex>${JM.LOG.RETAIN.COUNT:-7}</maxIndex>
        </rollingPolicy>

```
i think should use

```xml

        <file>${user.home}/logs/nacos/perf.log</file>
        
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <fileNamePattern>${user.home}/logs/nacos/perf.log.%i</fileNamePattern>
            <maxIndex>${JM.LOG.RETAIN.COUNT:-7}</maxIndex>
        </rollingPolicy>

```
 

**Expected behavior**
modify the log file 's path.

**Actually behavior**
use  `/Users/xiweng.yy/logs/nacos/` , but i'm not `xiweng.yy`

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] : *ubuntu*
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] : *dev* 
 - Module [e.g. naming/config]:  *example* 
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]:  *original*

**Additional context**

I have reported this incorrect configuration before, but I made a mistake https://github.com/apache/rocketmq/issues/7879

**Comment by KomachiSion** [comment]
Welcome PR
