### ISSUE TITLE
Dose the  incremental MCP supported now?

### ISSUE THREAD

**Issue by zhengzepeng** [alibaba/nacos#11797]
I saw this article [Nacos 融合Istio 下发xDS协议](https://nacos.io/docs/latest/ecology/use-nacos-with-istio/), but it confused me because i saw the source code and it didn't support `nacos.istio.server.full`.
Dose the  incremental MCP supported now? Or xds protocol (like cds/eds) supported now? Or it will support in the future, any plan?

**Comment by KomachiSion** [comment]
`nacos.istio.mcp.server.enabled` is enough， the document is provided by community, might the article author implement the new feature but not contribute to community, and forget to remove it from his/her contribute document.

Welcome submit PR to help us correct the document.

**Comment by zhengzepeng** [comment]
> `nacos.istio.mcp.server.enabled` is enough， the document is provided by community, might the article author implement the new feature but not contribute to community, and forget to remove it from his/her contribute document.
> 
> Welcome submit PR to help us correct the document.

thx
