### ISSUE TITLE
服务器重启后，依赖于nacos配置中心的服务，需要再次手动重启才能正常使用

### ISSUE THREAD

**Issue by flyletc** [alibaba/nacos#11807]
**Describe the bug**
服务器重启后，依赖于nacos配置中心的服务，需要再次重启才能正常使用

After the server restarts, it depends on the services in the nacos configuration center and needs to be restarted again to function properly

**Expected behavior**
After the server restarts, services that rely on the Nacos configuration center can also start normally
服务器重启后，依赖于nacos配置中心的服务也能正常启动

**Actually behavior**
After the server restarts, it depends on the services in the nacos configuration center and needs to be restarted again to function properly
服务器重启后，依赖于nacos配置中心的服务，需要再次重启才能正常使用

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.3.0, nacos-client 1.4.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
服务器断电后自动重启，我们期望所有服务能正常启动，目前发现nacos启动较慢，一些服务依赖nacos上的配置进行初始化，当nacos启动完全后，有些服务是不正常的，例如网关没有获取到对应的路由配置，接收到请求后会直接返回404

After the server loses power, it automatically restarts. We expect all services to start normally. Currently, we have found that Nacos starts slowly, and some services rely on the configuration on Nacos for initialization. When Nacos is fully started, some services are abnormal, such as the gateway not obtaining the corresponding route configuration. After receiving the request, it will directly return 404

**Comment by 985492783** [comment]
可以考虑集群模式，单机容灾不行

**Comment by flyletc** [comment]
> 可以考虑集群模式，单机容灾不行

目前期望是，nacos与应用部署在同一台服务器上，服务器断电自动重启后，整个服务也可用，不需要人工干预

**Comment by Daydreamer-ia** [comment]
> > 可以考虑集群模式，单机容灾不行
> 
> 目前期望是，nacos与应用部署在同一台服务器上，服务器断电自动重启后，整个服务也可用，不需要人工干预

按照我的理解，你的问题是你们那边服务和 `nacos-server` 启动顺序问题，这个并不在 `nacos` 的范畴，建议是在你们机器上去增加服务启动的脚本，在确定 `nacos-server` 准备完毕后再去启动你们的服务

**Comment by flyletc** [comment]
> > > 可以考虑集群模式，单机容灾不行
> > 
> > 
> > 目前期望是，nacos与应用部署在同一台服务器上，服务器断电自动重启后，整个服务也可用，不需要人工干预
> 
> 按照我的理解，你的问题是你们那边服务和 `nacos-server` 启动顺序问题，这个并不在 `nacos` 的范畴，建议是在你们机器上去增加服务启动的脚本，在确定 `nacos-server` 准备完毕后再去启动你们的服务

感谢

**Comment by KomachiSion** [comment]
正常情况下，nacos-server启动后会自动继续获取配置， 你可以拿纯粹的nacos-client试一下。

如果网关中有逻辑，比如访问nacos失败就shutdown掉client，然后也不重试了， 这样话就必须要重启网关了。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
