### ISSUE TITLE
Nacos 2.0.0 BEAT-mysql5.7.32 使用mysql数据库启动时，地址填写127.0.0.1能连接成功，填写开放ip就连接失败

### ISSUE THREAD

**Issue by MrWQ** [alibaba/nacos#11805]
版本：Nacos 2.0.0 BEAT
数据库：mysql5.7.32 
使用mysql数据库启动时，地址填写开放ip就连接失败（图1）
数据库已经开放远程连接，远程使用mysql客户端可以连接成功（图2）
使用mysql数据库启动时，地址填写127.0.0.1能连接成功（图3）
![1](https://github.com/alibaba/nacos/assets/31604279/60b8fa64-691f-4c0b-bb05-8c41fcf1a143)
![2](https://github.com/alibaba/nacos/assets/31604279/c1e30452-d33e-4c3e-9c7d-7fbcd46b7604)
![3](https://github.com/alibaba/nacos/assets/31604279/5d1c58da-fe00-4b92-9f95-388b8f3da30c)

**Comment by KomachiSion** [comment]
1. 版本过旧，请升级后再试
2. nacos透传了输入的jdbc串，如果连接失败，大概率是有参数设置不正确，或数据库驱动不兼容，需要自行排查下版本，网络，参数配置等问题。

**Comment by MrWQ** [comment]
从截图上可以看到。jdbc串肯定是没有问题的，因为我只是把127.0.0.1改成了10.78.2.20，其它没改动。127.0.0.1是lo网卡，10.78.2.20是ens3网卡。

**Comment by KomachiSion** [comment]
那就是环境问题，你填写本地的数据库可以访问，填写外部的不行，就说明代码上没有问题，必然是无法连接外部的数据库导致的，

而且报错也是jdbc尝试了3次，都无法获得任何数据包，说明网络上压根就没通。

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.
