### ISSUE TITLE
权限控制-用户-角色-权限管理

### ISSUE THREAD

**Issue by Eleven-M** [alibaba/nacos#11806]
nacos-docker 启动后
登录管理后台，通过权限控制-用户-角色-权限管理 新增角色，用户gust，设置只读权限。
退出用户切换 新建 public 配置，正常是不能新建。

退出用户切换nacos用户。通过权限控制-用户-角色-权限管理 新增角色，用户server-manager，设置读写权限。
退出用户切换server-manager 新建 server 配置，正常新建，但是没有查看历史版本，没有操作人，正常操作人为当前用户。

退出用户切换gust用户，查看server-manager创建的server配置，可以操作回滚，更新。正常不应该能操作。

ErrorBug：
操作记录中缺少 新建、更新操作人
权限只读，可以操作数据。

**Comment by 985492783** [comment]
新版本复现不出来，查看下你的鉴权能力是否打开

**Comment by 985492783** [comment]
http://localhost:8848/nacos/v1/console/server/state中的auth_enable

**Comment by KomachiSion** [comment]
看描述应该是未开启鉴权。
