### ISSUE TITLE
Could you generate sha1sum or sha256sum text for  nacos-server-xxx.tar.gz/nacos-server-xxx.zip in release-asset-list when released?

### ISSUE THREAD

**Issue by aihua** [alibaba/nacos#11800]
**Is your feature request related to a problem? Please describe.**
Cannot check whether the file is unmodified from the original after download nacos-server-xxx.tar.gz/nacos-server-xxx.zip in release-asset-list.

**Describe the solution you'd like**
Could you generate sha1sum or sha256sum text for  nacos-server-xxx.tar.gz/nacos-server-xxx.zip in release-asset-list when released? For example, go to [https://github.com/erlang/otp/releases/tag/OTP-26.2.2](https://github.com/erlang/otp/releases/tag/OTP-26.2.2), you will see  [SHA256.txt](https://github.com/erlang/otp/releases/download/OTP-26.2.2/SHA256.txt)  for checking.
 
@KomachiSion

**Comment by KomachiSion** [comment]
Have some maven plugin can direct build the sha256sum or sha1sum? when mvn install or maven package?

**Comment by aihua** [comment]
> Have some maven plugin can direct build the sha256sum or sha1sum? when mvn install or maven package?

Maybe you can refer to the flile [otp/.github/workflows/main.yaml](https://github.com/erlang/otp/blob/OTP-26.2.2/.github/workflows/main.yaml) Line 598-606, or [Secure your Travis CI releases – part 1: checksum with SHA](https://blogs.itemis.com/en/secure-your-travis-ci-releases-part-1-checksum-with-sha) or [actions-generate-checksum](https://github.com/marketplace/actions/generate-checksum).

**Comment by KomachiSion** [comment]
> > Have some maven plugin can direct build the sha256sum or sha1sum? when mvn install or maven package?
> 
> Maybe you can refer to the flile [otp/.github/workflows/main.yaml](https://github.com/erlang/otp/blob/OTP-26.2.2/.github/workflows/main.yaml) Line 598-606, or [Secure your Travis CI releases – part 1: checksum with SHA](https://blogs.itemis.com/en/secure-your-travis-ci-releases-part-1-checksum-with-sha) or [actions-generate-checksum](https://github.com/marketplace/actions/generate-checksum). @KomachiSion

Can you help community to add a actions yaml, when new version released, the actions runs and download new release package, and calculate the sha256 or sha1 to upload to release asserts.
