### ISSUE TITLE
信创不准使用MySQL。我可以在不修改nacos的前提下直接使用mariadb吗

### ISSUE THREAD

**Issue by pengkaiyan** [alibaba/nacos#11803]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 985492783** [comment]
driver被写死了，如果mariadb和mysql方言一致的话可以用release中tag的版本自己修改打包

**Comment by huangkemingyyds** [comment]
还可以考虑其他数据库，目前社区有插件支持，oracle，达梦、postgresql

**Comment by KomachiSion** [comment]
driver是可以修改的，`db.pool.config.driverClassName`

**Comment by KomachiSion** [comment]
另外，所有支持mysql协议的数据库都可以直接使用，比如tidb， 我记得mariadb也是兼容mysql协议的。

**Comment by dylan-tao** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

nacosplus针对多种数据库（包含信创数据库）提供支持， MariaDB近一周内上线，详见：https://github.com/dylan-tao/nacos-plus
