### ISSUE TITLE
怎么配置nacos权重的更新间隔

### ISSUE THREAD

**Issue by yoboygo** [alibaba/nacos#11808]
在使用spring-cloud-nacos中，在控制台修改了权重之后，客户端要等待30s才可以拉取到，尝试了spring.cloud.nacos.discovery.watch-delay不起作用，请问这个时间间隔可以配置吗？

**Comment by 985492783** [comment]
这个issue应该提给springcloud-alibaba这个仓库里，这个拉取频率不是我们控的
