### ISSUE TITLE
nacos can't connect mysql8.0.16？？

### ISSUE THREAD

**Issue by lovewuqiang** [alibaba/nacos#1180]
error：org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)

application properties content

spring.datasource.platform=mysql

db.num=1
db.url.0=jdbc:mysql://192.168.1.11:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
db.user=root
db.password=root

I have copy mysql-connector-java-8.0.13.jar to os directory plugin/mysql,but it no work...

**Comment by lovewuqiang** [comment]
Mysql Too many connection failures
Solution：mysqladmin -u xxx -p flush-hosts
It's all fixed

**Comment by wangjiahao0505** [comment]
infeasible
