### ISSUE TITLE
配置中心模糊查询

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#11812]
![image](https://github.com/alibaba/nacos/assets/73023513/aaaea1d7-d763-4a74-bbaa-844bc055464b)
这个功能被砍了吗，我看这个接口没有重写dataId的逻辑了，并且*也被鉴权插件拦住了，需要加上这个功能还是直接去掉这段说明

**Comment by Bo-Qiu** [comment]
个人认为此功能还是很有必要的

**Comment by KomachiSion** [comment]
鉴权插件为什么会拦截*？

**Comment by KomachiSion** [comment]
应该是参数校验的拦截了， 现在应该是通过开关打开模糊搜索了吧，前端可以把这个关掉？

**Comment by 985492783** [comment]
> 应该是参数校验的拦截了， 现在应该是通过开关打开模糊搜索了吧，前端可以把这个提示去掉？

说错了，是被参数校验插件给拦截了

**Comment by KomachiSion** [comment]
No more response from author, and the feature is implemanted by switch.
