### ISSUE TITLE
We need the jar package used by the console module

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [alibaba/nacos#11814]
**Is your feature request related to a problem? Please describe.**
I want to run Nacos service directly in the project, but I am missing the jar package: the reason is that you did not publish all the jar packages to the Maven central repository.

我想直接在项目中运行Nacos服务，但我缺少jar包：原因是您没有将所有jar包发布到Maven中央存储库。

**Describe the solution you'd like**
I hope that when releasing a new version, the jar package used by the [console](https://github.com/alibaba/nacos/tree/develop/console) module can also be released to the Maven central repository

我希望在发布新版本时，[console](https://github.com/alibaba/nacos/tree/develop/console) 模块 使用的jar包也可以发布到Maven中央存储库

**Describe alternatives you've considered**
In order to meet my requirements, I built and released the jar package required for the [console](https://github.com/alibaba/nacos/tree/develop/console) module myself. Although releasing a jar package now only requires modifying one parameter of the GitLab CI/CD pipeline, I believe this is not the optimal solution. And I see that there are many people in Maven who have similar expectations as me, and they have also compiled and released jar packages themselves.

为了满足我的需求，我构建并发布了 [console](https://github.com/alibaba/nacos/tree/develop/console) 模块所需的jar包。虽然现在发布jar包只需要修改GitLab CI/CD 流水线的一个参数，但我认为这不是最佳解决方案。我看到Maven中有很多人和我有类似的期望，他们自己也编译并发布了jar包。

1. https://github.com/xuxiaowei-io/nacos/blob/main/.gitlab-ci.yml
2. https://github.com/xuxiaowei-io/nacos-console-ui/blob/main/.gitlab-ci.yml
3. https://framagit.org/xuxiaowei-io/nacos/-/jobs/2278559
4. https://framagit.org/xuxiaowei-io/nacos-console-ui/-/jobs/2278565

**Additional context**
![20240312-10-54-56-DESKTOP-8E6LUNV-4914-chrome-8VbtEsaV30](https://github.com/alibaba/nacos/assets/46893436/f17195a2-1ea7-4d9f-b0b7-47032a2ed7c3)
![20240312-10-55-12-DESKTOP-8E6LUNV-4915-chrome-iBZfqQxOS5](https://github.com/alibaba/nacos/assets/46893436/6eecc866-48df-4faf-8ce9-87cfbdc3fff1)
![20240312-10-56-18-DESKTOP-8E6LUNV-4916-chrome-1OusMlyPTl](https://github.com/alibaba/nacos/assets/46893436/be2f9993-0340-47c3-b7a7-013e25c5bae4)
![20240312-10-56-29-DESKTOP-8E6LUNV-4917-chrome-yVFAPn6IOW](https://github.com/alibaba/nacos/assets/46893436/7e8d529e-a6c5-4a8d-9289-cddcac87e0d3)

**Comment by xuxiaowei-com-cn** [comment]
我观察到 [console](https://github.com/alibaba/nacos/tree/develop/console) 模块所需的 jar 包 https://repo1.maven.org/maven2/io/xuxiaowei/nacos/

![20240312-11-07-06-DESKTOP-8E6LUNV-4919-chrome-BlOyS9HAcR](https://github.com/alibaba/nacos/assets/46893436/2ae6fdd8-1563-41c8-b339-8fa8763185e7)

**Comment by KomachiSion** [comment]
不支持， Nacos 除了common，api，plugin和client以外， 只通过制品包、docker镜像的形式发布可运行程序，不单独提供jar。

如需要需要自定打包发布
