### ISSUE TITLE
Optimize the memory usage of nacos server——server.max-http-header-size

### ISSUE THREAD

**Issue by Aresxue** [alibaba/nacos#11810]
**Is your feature request related to a problem? Please describe.**
The server.max-http-header-size parameter enabled by default will cause a waste of memory

**Describe the solution you'd like**
Remove the server.max-http-header-size parameter

**Additional context**
In order to solve the problem of #1069 , nacos added server.max-http-header-size=524288 by default. It was said to be a temporary solution at the time, but it was not optimized later. Configuring this parameter resulted in a waste of memory. In the actual heap snapshot, it is found that most of the requested byte arrays are 0. If it is just for an interface, then transforming the interface is a better choice.

**Comment by KomachiSion** [comment]
It's add for nacos1.x client, nacos1.x client need more size to keep the request can be accept when register many service and subscribe many service.

If you client all upgrade to 2.x, you can change this parameters to default value, but if you client contain many 1.x version, suggest you keep the size to avoid unexpected `400 bad request`.

For community, only when nacos server not supported nacos 1.x client, the size will be reduce or remove.
