### ISSUE TITLE
2.3.0 BUG

### ISSUE THREAD

**Issue by JunsyYJS** [alibaba/nacos#11813]
After starting and using the Nacos service normally for a period of time, it automatically crashes with the error: [db-load-err] load jdbc.properties error, but the DB cluster is connected and used normally with all other tools

**Comment by KomachiSion** [comment]
It should be your nacos cluster has network problem or configuration problem, so that it can't connect to db.

I can't reproduce your problem in my env. Or you provide more log info?

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.
