### ISSUE TITLE
关于配置中心的疑问，Nacos 2.2.3集群健康节点数未过半，仍然能正常提供服务

### ISSUE THREAD

**Issue by butIBeenLowKEY** [alibaba/nacos#11818]
在测试环境做服务高可用时顺便测了下Nacos集群，我使用的是三节点的Nacos Docker集群，mysql数据源，停掉主节点A，接着再停新选举出来的主节点B之后，只剩下节点C，此时配置中心仍然能正常提供服务，可以正常发布配置，监听配置的服务可以正常获取到新的配置。但是按照raft协议的说法此时活动节点数未过半，应该无法再写入新的配置，这里Nacos是有做了什么特殊处理吗。

**Comment by KomachiSion** [comment]
Nacos 是CP+AP协议， 当不健康节点超过半数时， 会降级部分功能：比如控制台上的标记下线服务，修改权重，修改，发布，删除持久化服务等。

但是核心功能： 如发布配置、修改配置、获取配置、发布临时服务、删除临时服务、订阅（获取）服务，不受影响，进一步提高Nacos的高可用能力。

**Comment by butIBeenLowKEY** [comment]
> Nacos 是CP+AP协议， 当不健康节点超过半数时， 会降级部分功能：比如控制台上的标记下线服务，修改权重，修改，发布，删除持久化服务等。
> 
> 但是核心功能： 如发布配置、修改配置、获取配置、发布临时服务、删除临时服务、订阅（获取）服务，不受影响，进一步提高Nacos的高可用能力。

明白了，我们先前有点误解，以为对临时实例来说，注册中心相关功能就是Distro协议，配置中心的相关功能都是严格以raft协议那一套机制运行。

**Comment by chuntaojun** [comment]
配置中心走的是数据库+星型广播，没有一致性协议吧
