### ISSUE TITLE
Hello, my version of nacos2.2.3 with the authentication function enabled cannot use the API to get the configuration file.

### ISSUE THREAD

**Issue by Changego** [alibaba/nacos#11820]
Hello, my version of nacos2.2.3 with the authentication function enabled cannot use the API to get the configuration file.

Note: If the default authentication plug-in is enabled, enter the username and password in the Header. But I don't know how to add it, and I see that the API documentation has no content.

Waiting for your reply, thank you very much.

**Comment by KomachiSion** [comment]
It's not a nacos' problem I think. 

If you use nacos-client, you don't need think how to add username and password in the Header, you only config them into your nacos-client like document show.

And if not use nacos-client, it just an http request, different http client may have diff way to inject header. If you use with this way, you should see the document for your http client, and submit issue to your http client community not nacos.

such as ask AI: how to add header in http request by curl

Answered by GPT:

To add headers to an HTTP request using `curl`, you can use the `-H` or `--header` option followed by the header you want to include. You can specify as many header lines as needed by using multiple `-H` flags. Here's the basic syntax:

```sh
curl -H "Header-Name: Header-Value" [URL]
```

For example, if you want to make a request with a custom `Content-Type` and `Authorization` header, you might do something like this:

```sh
curl -H "Content-Type: application/json" -H "Authorization: Bearer YourAuthToken" [URL]
```

This command will send an HTTP request to the `[URL]` with the `Content-Type` header set to `application/json` and the `Authorization` header set to `Bearer YourAuthToken`.

Remember to replace `Header-Name` and `Header-Value` with the actual header names and values you want to use, and replace `[URL]` with the URL you're sending the request to. If you need to include special characters in the header values, make sure to use quotes as shown in the examples.

**Comment by Changego** [comment]
Yes, this is not nacos's problem. I just don't know the API request method. Although I have asked GPT to try, it seems that the connection failed, so I am looking for your help to confirm. 
Thanks a lot.

**Comment by Changego** [comment]
Make sure you've tried.Always report error 
`"status":403,"error":"Forbidden","message":"user not found!","path":"/nacos/v1/cs/configs`
