### ISSUE TITLE
共享配置和扩展配置是否也能加一个fileExtension这样的参数

### ISSUE THREAD

**Issue by publicize-y** [alibaba/nacos#11825]
目前在用共享配置和扩展配置时，控制台的Data Id必须带类型尾缀，实际使用过程中感觉不太方便。目前我们想把共享配置的文件类型给更改掉，文由properties改成yaml，我们发现不支持修改DataId，导致只能把共享配置给重新删掉，新建一个配置 取名以yaml结尾。这里的共享配置和扩展配置是否能增加一个fileExtension这样的参数，便于修改

**Comment by publicize-y** [comment]
![1](https://github.com/alibaba/nacos/assets/73219873/0e59be5a-6b35-4c3b-a4b4-41d34ee05087)
![2](https://github.com/alibaba/nacos/assets/73219873/2dc13f8e-1012-4ff1-8b0e-d75ee049d82a)

**Comment by KomachiSion** [comment]
这个issue需要提交到spring cloud alibaba社区了， nacos没有对dataId的后缀做限制，这个应该是spring cloud加的限制。
