### ISSUE TITLE
/nacos/v1/ns/operator/servers this api access failed!

### ISSUE THREAD

**Issue by jisongxi** [alibaba/nacos#11832]
nacos version: 2.3.1

curl "10.169.68.116:8848/nacos/v1/ns/operator/servers"

{"timestamp":"2024-03-14T19:57:57.512+08:00","status":501,"error":"Not Implemented","message":"no such api:GET:/nacos/v1/ns/operator/servers","path":"/nacos/v1/ns/operator/servers"}

Is this api abandon？ Which one  should be used!

**Comment by KomachiSion** [comment]
This api has been marked deprecated after 1.3.0, and in 2.2.0 removed.

you can use `curl -X GET '$ip:8848/nacos/v2/core/cluster/node/list'?state=UP` to get all healthy server nodes.

**Comment by jisongxi** [comment]
thanks
