### ISSUE TITLE
Replace error message 'failed to req API:/nacos/v1/ns/instance/list after all servers' to more specific message

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1184]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

The error message 'failed to req API:/nacos/v1/ns/instance/list after all servers' is too blurred.

### Describe what you expected to happen

Replace this message to more specific message.

**Comment by kexianjun** [comment]
I have encountered this exception, can you tell me what's the cause?

**Comment by nkorange** [comment]
The latest code has updated the error message:
![image](https://user-images.githubusercontent.com/4593375/61045123-ca2cb080-a40c-11e9-8a3c-8665db877496.png)
