### ISSUE TITLE
1.4.2使用固定的udp端口号

### ISSUE THREAD

**Issue by ray202208** [alibaba/nacos#11848]
目前1.4.2这个版本的代码还可以继续增加功能吗？
由于公司原因，想使用固定的udp端口，但是目前只支持环境变量方式，这种方式对我们有点麻烦（需要给每个服务都增加）
想增加其他方式，比如通过Properties方式

**Comment by KomachiSion** [comment]
1.X不再新增功能， 如果有需要的话，可以fork源码，然后自行修改后打包使用。
