### ISSUE TITLE
openAPI in `nacos/v2/ns/client/*` can't handle batch registered services

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#11843]
**Describe the bug**
If I register service with batch register, the openAPI in `nacos/v2/ns/client/*`  like `/nacos/v2/ns/client/publish/list?clientId=` will return null ip, 0 port and null cluster

```
{
    "namespace": "public",
    "group": "DEFAULT_GROUP",
    "serviceName": "test",
    "registerInstance": {
        "ip": null,
        "port":0,
        "cluster":null
    }
}
```

**Expected behavior**
response right instance info in batch Instance

**Actually behavior**
return null info

**How to Reproduce**
1. Register any batch instance by nacos-client.
2. curl `/nacos/v2/ns/client/publish/list?clientId=` with your clientId.
3. See the result with null ip.

**Comment by Daydreamer-ia** [comment]
i will resolve it

**Comment by wxm155** [comment]
i want to resolve it

**Comment by KomachiSion** [comment]
> i want to resolve it

Sorry, the issue has been resolved by https://github.com/alibaba/nacos/pull/11845
