### ISSUE TITLE
最新的nacos版本能打成war包部署在tomcat里面吗

### ISSUE THREAD

**Issue by z624023251** [alibaba/nacos#11849]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by z624023251** [comment]
最新的nacos版本能打成war包部署在tomcat里面吗，会有兼容性问题吗？我现在用的版本是2.3.1

**Comment by KomachiSion** [comment]
之前的版本可以的话， 新版本就可以， nacos本身接口的兼容性是保证的。
