### ISSUE TITLE
nacos 2.3.1  健康检查3s打印一次日志

### ISSUE THREAD

**Issue by wangj919** [alibaba/nacos#11857]
**Describe the bug**
Nacos server health check print log in 3 seconds Long connection metrics detail, Total count =0, sdkCount=0, clusterCount=0 

**Expected behavior**
Is it possible to print less connection check logs, or is this due to something now

**Actually behavior**
3s Prints once 

RpcScheduledExecutor.COMMON_SERVER_EXECUTOR.scheduleWithFixedDelay(() -> {
        runtimeConnectionEjector.doEject();
    }, 1000L, 3000L, TimeUnit.MILLISECONDS);

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.4
 - Version [e.g. nacos-server 2.3.1, nacos-client 2.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by stone-98** [comment]
I feel like it wouldn't have much of an impact...

**Comment by KomachiSion** [comment]
You can change the log config in `nacos/conf/nacos-logback.xml` to change the log keep day time and keep size to adapt your env and your disks.

I think the metrics information print per 3s is not much problem. 

And I don't think all of things configurable is best, it will cause the configuration too many to hard maintain, If community want config the frequently of connection metrics print, Please refer to issues, if it's a community consensus, we can make it configurable in new version.

**Comment by KomachiSion** [comment]
No more response from author, It seems currently behavior is ok.
