### ISSUE TITLE
springboot2.7.x版本和nacos最新的客户端版本0.2.12不兼容

### ISSUE THREAD

**Issue by z624023251** [alibaba/nacos#11858]
springboot2.7.x版本和nacos最新的客户端starter版本0.2.12不兼容

这两个放一起用启动会报
java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata

能否提供一个可以兼容springboot2.7.x版本的客户端包

**Comment by z624023251** [comment]
经过测试和springboot2.4.0以上的版本都不兼容，有支持计划吗

**Comment by z624023251** [comment]
加入spring-cloud-context模块能解决问题

**Comment by SeakyLuo** [comment]
> 加入spring-cloud-context模块能解决问题

什么版本 @z624023251 我加了但是没搞定

**Comment by GFTXWD** [comment]
你server版本对吗？我目前nacos-config-spring-boot-starter和nacos-discovery-spring-boot-starter使用0.2.12，spring boot 2.7.18, nacos server 2.5.1，没有问题了
