### ISSUE TITLE
GraalVM support for nacos-client

### ISSUE THREAD

**Issue by chickenlj** [alibaba/nacos#11853]
Currently, both alibaba/spring-cloud-alibaba and apache/dubbo supports native image and can work well with certain versions of nacos-client. 

But they achieved that by scanning the dynamic operations in nacos manually. So it's better for nacos-client do the scanning and add the configuration to each released package for each new version.

https://github.com/alibaba/spring-cloud-alibaba/issues/3656

https://github.com/apache/dubbo/blob/3.3/dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/aot/NacosReflectionTypeDescriberRegistrar.java

**Comment by lmm1990** [comment]
fixed #11860
