### ISSUE TITLE
nacos2.2.3版本开启了鉴权，/nacos/v1/console/server/announcement 报没有开启鉴权

### ISSUE THREAD

**Issue by LL3706** [alibaba/nacos#11865]
nacos2.2.3版本已经开启了鉴权，但是调/nacos/v1/console/server/这个接口，返回没有开启授权

**Comment by KomachiSion** [comment]
那你访问一下别的接口，看下是否真的鉴权了。或者清理一下浏览器缓存后重试。如果还是不对，就升级一下nacos版本。

**Comment by LL3706** [comment]
别的接口都有鉴权，我看源码里面/nacos/v1/console/server/这个接口的返回值是写死的，这个接口是做什么用的，是不是这个接口没什么用

**Comment by 985492783** [comment]
要看你的state接口的返回值，跟announcement关系不大，只有state接口查询到没开启鉴权才会报announcement的信息

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.

**Comment by whenandwhy** [comment]
升级到2.5.3，也是开启了鉴权，被安全软件扫到这个接口/nacos/v1/console/server/announcement，显示{"code":200,"message":null,"data":"当前集群没有开启鉴权，请参考<a href=\"https://nacos.io/zh-cn/docs/v2/guide/user/auth.html\">文档</a>开启鉴权~"}
