### ISSUE TITLE
nacos2.2.3集群部署，客户端正常注册服务。在客户端虚拟机突然宕机后，该服务实例一直未被主动剔除，导致交易异常。

### ISSUE THREAD

**Issue by qazx404** [alibaba/nacos#11876]
求助如何解决？

**Comment by stone-98** [comment]
2.2.3好像的确有这个问题，之前也有类似的issue，关联issue：https://github.com/alibaba/nacos/issues/10909
在2.3.0版本中修复了，关联pr：https://github.com/alibaba/nacos/pull/10509
看看是不是这个问题，如果是的话，建议升级下版本。

**Comment by qazx404** [comment]
> 2.2.3的确有这个问题，之前也有类似的issue，关联issue：#10909 在2.3.0版本中修复了，关联pr：#10509 看看是不是这个问题，如果是的话，建议升级下版本。

感谢
