### ISSUE TITLE
Update instance health status

### ISSUE THREAD

**Issue by pheaktraloma** [alibaba/nacos#11870]
Dear Nacos team. Please help to check this endpoint: /nacos/v2/ns/health/instance
================================================================
curl -d 'serviceName=services_token3' \
  -d 'ip=127.0.0.1' \
  -d 'port=8000' \
  -d 'healthy=true' \
  -X PUT 'http://127.0.0.1:8848/nacos/v2/ns/health/instance'
==== Display Message ===
{"code":30000,"message":"server error","data":"health check is still working, service: DEFAULT_GROUP@@services_token3, cluster: DEFAULT"}

we can't use this endpoint for update healthy status true.
thank you.

![image](https://github.com/alibaba/nacos/assets/150645689/6e3cddb2-0a37-46af-a353-ac61a7fbf63c)

**Comment by stone-98** [comment]
Why is there no 'clusterName' in the request body?

**Comment by pheaktraloma** [comment]
I'm follow the document. the field validation only: (ip, port and healthy). so we need to put clusterName right?

**Comment by pheaktraloma** [comment]
https://nacos.io/en/docs/v2/guide/user/open-api/#2.16

**Comment by KomachiSion** [comment]
1. Make sure your cluster is exist in service, you can get the infomation in console or by `instance/list` API.
2. Make sure your health check type is `None`, if the health check type is `TCP`,`HTTP` or `MySQL`, the API will fail because there is async task to maintain the health status.

**Comment by pheaktraloma** [comment]
![Screenshot from 2024-03-25 17-26-36](https://github.com/alibaba/nacos/assets/150645689/4e1e3e92-816a-4b49-98b5-2e0bbf19d650)
i'm check this endpoint -> instance/list api display like this.

**Comment by pheaktraloma** [comment]
Can you help to check this endpoint. because i'm using still message (servers error) 
![Screenshot from 2024-03-26 09-25-12](https://github.com/alibaba/nacos/assets/150645689/fae42fff-f53a-4aed-8727-9443049f38b1)
-X PUT 'http://127.0.0.1:8848/nacos/v2/ns/health/instance'

**Comment by KomachiSion** [comment]
> 1. Make sure your cluster is exist in service, you can get the infomation in console or by `instance/list` API.
> 2. Make sure your health check type is `None`, if the health check type is `TCP`,`HTTP` or `MySQL`, the API will fail because there is async task to maintain the health status.

As comment said, you must check your service health check type is `None`, other type is not support directly change the instance health

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
