### ISSUE TITLE
浏览器禁止了非安全域的 navigator.clipboard 对象

### ISSUE THREAD

**Issue by bwangll** [alibaba/nacos#11879]
https://github.com/alibaba/nacos/blob/a7d9ef2fe8557f0e41305546101b5a236a7266b5/console-ui/src/components/Copy/index.jsx#L40
clipboard只有在安全域名下才可以访问(https、localhost)，在http域名下只能得到undefined；

**Comment by KomachiSion** [comment]
具体的影响是？

**Comment by bwangll** [comment]
页面上无法复制命名空间id

**Comment by bwangll** [comment]
> 具体的影响是？

复制失败并且没有提示，具体在配置页面，服务页面都存在这个情况

**Comment by hnyyghk** [comment]
@hnyyghk will solve it@
