### ISSUE TITLE
Can't Updated Healthy Status 

### ISSUE THREAD

**Issue by pheaktraloma** [alibaba/nacos#11884]
Dear Nacos team. Please help to check this endpoint: /nacos/v2/ns/health/instance
curl -d 'serviceName=services_token3'
-d 'ip=127.0.0.1'
-d 'port=8000'
-d 'healthy=true'
-X PUT 'http://127.0.0.1:8848/nacos/v2/ns/health/instance'
==== Display Message ===
{"code":30000,"message":"server error","data":"health check is still working, service: DEFAULT_GROUP@@services_token3, cluster: DEFAULT"}
1. I think this message server error from your side. 
2. Status code: 30000
Doc#2.16
https://nacos.io/en/docs/latest/guide/user/open-api/#2.16

===== Nacos Service lasted version ====

![Screenshot from 2024-03-27 09-31-14](https://github.com/alibaba/nacos/assets/150645689/a88a6e4a-b5bd-4aac-bcc4-848162449ffd)

we can't use this endpoint for update healthy status true.
thank you.

**Comment by KomachiSion** [comment]
#11870
