### ISSUE TITLE
Nacos Client will create nacos and logs directory in user home, can I set them to other paths?

### ISSUE THREAD

**Issue by zihluwang** [alibaba/nacos#11888]
When an app used Nacos started, `nacos` and `logs` will be created in user home path, and there is no way to remove it. This settings is very annoying, especially for Mac users. I home maybe I missed something important to set it, any ideas?

**Comment by stone-98** [comment]
可以通过
```
-Dnacos.home
```
进行指定。

**Comment by zihluwang** [comment]
> 可以通过
> 
> ```
> -Dnacos.home
> ```
> 
> 进行指定。

This seems to be a server config, how about client config?
