### ISSUE TITLE
用户目录下会有一个file:的文件夹

### ISSUE THREAD

**Issue by spairy** [alibaba/nacos#11886]
nacos_2.2.3服务端会在用户目录下产生一个file:的文件夹，完整路径为：
/home/username/file:/home/username/software/nacos/nacos/target/nacos-server.jar!/BOOT-INF/classes!/data/connection
/home/username/file:/home/username/software/nacos/nacos/target/nacos-server.jar!/BOOT-INF/classes!/data/tps

请问这个是干什么的？如何改变这个路径？

**Comment by KomachiSion** [comment]
没遇到过这个问题， 可能是本地配置有问题？ 导致读取的nacos.home 出现错误

**Comment by spairy** [comment]
在哪个目录下执行nacos的启动命令（绝对路径或相对路径/startup.sh），就会在这个目录下生成一个file:的文件夹。您说的nacos.home是需要额外配置的吗？我在本地环境中没有设置nacos相关的环境变量。

**Comment by KomachiSion** [comment]
升级新版本再试一下呢？

**Comment by spairy** [comment]
试了2.2.0和2.3.0不会生成，2.2.1、2.2.2、2.2.3会生成。

**Comment by 8562364** [comment]
Hello everyone,
 I think I can confirm how it came about. I'm using MacOS mbp16 and nacos 2.3
1. Open Idea  
2. Open the Terminal function of idea 
3. Enter the startup command sudo /Users/username/software/nacos/nacos2.3/bin/startup.sh -m standalone  
4. The "file:"" folder appears in the project I opened
