### ISSUE TITLE
Embedded Nacos suport

### ISSUE THREAD

**Issue by ralf0131** [alibaba/nacos#1188]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Dubbo now support Nacos as registry center and config center. However, the unit tests can not be executed unless there is an existing nacos server available. This is difficult when you run continuous integration on Travis.

### Describe what you expected to happen

Nacos Server should be able to works as an embedded server. Just like embedded zookeeper

**Comment by Moriadry** [comment]
@nkorange  when will this be provided?

**Comment by KomachiSion** [comment]
Remove to #3785
