### ISSUE TITLE
nacos版本2.0，堆内存持续上升，高峰时期达到95%，内存无法有效/及时的回收

### ISSUE THREAD

**Issue by wmhxhfive** [alibaba/nacos#11885]
**1.线上配置**
线上集群配置 8c/20g的集群，客户端没有采用slb的连接方式，采用a:8848,b:8848,c:8848的配置链接；
jvm的参数配置为：-server -Xms15g -Xmx15g -Xmn8g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m

**线上问题**
![237eab9323ca594ffea3469f0f378eb](https://github.com/alibaba/nacos/assets/32756614/51b295c7-0ed2-4442-aa00-3fa6a4a0b39c)
堆内存高峰时期达到95%；
**用mat工具进行分析，没发现明显的内存泄漏，分析结果如下**
![mat2](https://github.com/alibaba/nacos/assets/32756614/fbd8661d-201e-4c4a-87fd-552ffb0ab4f9)
![mat1](https://github.com/alibaba/nacos/assets/32756614/f9e606dd-54ec-4801-9d79-62d5481a9bd5)
等待大神解救

**Comment by 985492783** [comment]
client版本是不是1.x的，太低了升级到2.x

**Comment by KomachiSion** [comment]
没看懂问题，堆内存高很正常啊， 因为内存够的时候不会触发GC，不触发GC的话就不会回收使用的内存。

只要不是GC过于频繁，特别是FullFc过于频繁就没有问题。

**Comment by wmhxhfive** [comment]
> 没看懂问题，堆内存高很正常啊， 因为内存够的时候不会触发GC，不触发GC的话就不会回收使用的内存。
> 
> 只要不是GC过于频繁，特别是FullFc过于频繁就没有问题。

现在gc的频率是每半个小时回收一次，极端的时候内存占用达到95%

**Comment by 985492783** [comment]
1. YGC半小时一次基本和没有qps差不多了
2. 极端的时候内存占用达到95%，看下你gc后的数据，gc前数据没有意义
3. 堆内存可以调低点

**Comment by KomachiSion** [comment]
我看监控图， 是很正常的， 堆内存使用率高，GC后降低到较低的水平，符合java的内存管理通性， 只要确认GC类型、频率和时间都在正常就可以。

**Comment by KomachiSion** [comment]
No more response from author, It seems no problem for nacos cluster.
