### ISSUE TITLE
nacos 2.3.1 客户端bug，导致修改配置内容后 服务端一直在推送 ConfigChangeNotifyRequest

### ISSUE THREAD

**Issue by huhongjie2014** [alibaba/nacos#11880]
客户端方法：com.alibaba.nacos.client.config.impl.ClientWorker.ConfigRpcTransportClient#initRpcClientHandler  中

rpcClientInner.registerServerRequestHandler((request, connection) -> {
                if (request instanceof ConfigChangeNotifyRequest) {
                    # 下行代码缺少return
                    handleConfigChangeNotifyRequest((ConfigChangeNotifyRequest) request, rpcClientInner.getName());
                }
                return null;
            });

**Comment by stone-98** [comment]
@i will solve it@
