### ISSUE TITLE
老年代越来越大不会回收

### ISSUE THREAD

**Issue by dingciguang123** [alibaba/nacos#11889]
老年代老是满，FGC无法回收不了，麻烦帮忙看下
![1711539578559](https://github.com/alibaba/nacos/assets/48422230/c9511c98-8b4b-4d99-9f57-e1a0124c920d)
![1711539495126](https://github.com/alibaba/nacos/assets/48422230/01b12ff1-d991-4852-9a53-cd7f622033a7)

**Comment by stone-98** [comment]
请你提供更详细的信息，比如是否是sdk端？版本信息？
老版本的client频繁发生配置的情况下，有内存泄漏问题。 https://github.com/alibaba/nacos/issues/10471

**Comment by dingciguang123** [comment]
客户端版本是2.2.4
服务端版本是2.3.0
内存泄露的是服务端

**Comment by 985492783** [comment]
分配的堆内存多少，参数看看

**Comment by akinlau** [comment]
JAVA_OPT="${JAVA_OPT} -server -Xms4g -Xmx4g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m"
JAVA_OPT="${JAVA_OPT} -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${BASE_DIR}/logs/java_heapdump.hprof"
JAVA_OPT="${JAVA_OPT} -XX:-UseLargePages"

**Comment by stone-98** [comment]
2.3.0这个LruCache没看到地方用呀，怎么会占用将近1gb的内存。

**Comment by stone-98** [comment]
2.3.0版本StringPool用的是google的cache，你这个应该不是2.3.0版本的server把？

**Comment by akinlau** [comment]
上面版本给错了，是2.2.3版本的

**Comment by KomachiSion** [comment]
升级到2.3.1试试看

**Comment by akinlau** [comment]
上周升级到了2.3.1，再观察一段时间看看

**Comment by KomachiSion** [comment]
No more response from author, It seems new version has solved this problem.
