### ISSUE TITLE
以双机方式实现高可用是否可行

### ISSUE THREAD

**Issue by jaydonshi** [alibaba/nacos#11899]
请问，在只有2台虚机的情况下，如何实现nacos的高可用？

nacos文档中提到集群部署至少需要3个节点才能实现，现在我们实际只给提供了2台虚机。请问能否利用HA软件以vip+故障切换的方式实现nacos的高可用。既2个节点上只有一个nacos运行，检测到nacos发生故障时，切换vip到另外节点，同时启动另外节点的nacos。数据库连接同一个，应该不会丢失数据。

不知道这种允许模式有没有什么问题。

**Comment by 985492783** [comment]
可以，不过一台挂了整个服务就不可用了

**Comment by Bo-Qiu** [comment]
个人感觉，如果只作为配置中心使用，两个实例问题不大；
作为注册中心使用时，要保证高可用，最好还是2n+1个节点（n>0），只有两个节点和单点服务没啥区别，挂了一台整个服务都不可用了。

**Comment by KomachiSion** [comment]
如果完全不使用持久化服务，并且不会通过控制台和openAPI修改服务/实例元数据的话，注册中心2节点也可以高可用， 挂一个节点会影响持久化服务的注册，注销和服务/实例元数据的修改， 不影响临时实例的注册，注销，和所有服务的订阅、查询。

**Comment by butIBeenLowKEY** [comment]
> 个人感觉，如果只作为配置中心使用，两个实例问题不大； 作为注册中心使用时，要保证高可用，最好还是2n+1个节点（n>0），只有两个节点和单点服务没啥区别，挂了一台整个服务都不可用了。

作为注册中心也可以

**Comment by jaydonshi** [comment]
感谢各位的回答，改天搭个测试环境我测试一下。

**Comment by haeho7** [comment]
> 感谢各位的回答，改天搭个测试环境我测试一下。

突然也想到这种使用方式:

1. 两台服务器 Docker 分别跑一个 nacos `standalone` 模式单机容器；
2. 两个 nacos 单机容器都连接同一个 `MySQL` 数据库；
3. 两台服务器再分别部署 `keepailved` 组件做 vip 主备切换；
4. 应用这边使用 `vip + 端口` 的方式连接 nacos 进行注册；

刚好搜到这个 issues，但是看了一下各位大佬的解答，没理解 `注册中心2节点也可以高可用`，是指可以采用上述 `standalone + keepailved` 的方式部署，还是指两个节点必须使用 `cluster` 模式部署。

所以想请问下你测试结果和使用情况怎么样，可以满足需求不？
