### ISSUE TITLE
nacos 在k8s 环境下，重启后，第一次访问接口总是报错

### ISSUE THREAD

**Issue by dugujiujian** [alibaba/nacos#11898]
环境：自己日常搭建环境，阿里云k8s 集群部署
nacos版本：2. 0.1 

nacos 在k8s 环境下，重启后，应用内第一次访问接口总是报错，第二次访问正常

**Comment by stone-98** [comment]
可以贴一下错误信息。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem.
