### ISSUE TITLE
grpc 服务注册失败时返回了成功

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#11895]
<img width="978" alt="图片" src="https://github.com/alibaba/nacos/assets/6041166/9392b063-ffbb-426b-80d8-5c5b296ff8a9">
这里，应该抛出异常，而不是简单返回；

nacos 建连后是发送事件，换言之，是异步将 connectionId 加入到 clientManager 里面的，go sdk 建连后，最快 100 毫秒就会注册服务，我们上线服务丢失，查询 log 发现：
`Client connection xxx already disconnect`
然后查询 go 的 log，发现真是丢失的服务的 connectionId，在高并发大量建连并注册的场景下，这里存在风险，建议抛出异常，而不是 return

**Comment by stone-98** [comment]
java sdk现在最新版本建立connection时，将等到server的response才会认为是连接建立成功，go的估计还是老版本的逻辑，发起连接后，等待指定默认时间就认为成功了，感觉一个是这里要抛出异常，还要一个go sdk也需要同步下java sdk的逻辑。

**Comment by ijustyce** [comment]
> java sdk现在最新版本建立connection时，将等到server的response才会认为是连接建立成功，go的估计还是java sdk老版本的逻辑，发起连接后，等待指定默认时间就认为成功了，感觉一个是这里要抛出异常，还要一个go sdk也需要同步下java sdk的逻辑。

这里最好抛出异常，避免 sdk 等待时间不足，出现服务丢失的情况；go sdk 除了这个，还存在[其他问题](https://github.com/nacos-group/nacos-sdk-go/issues/736)，也会导致服务丢失，我本地压测时，go sdk 需要修复这个bug，且 nacos server 也需要抛出异常时才能做到 nacos server 宕机重启服务数量不减少，服务不丢失；

**Comment by Bo-Qiu** [comment]
确实应该抛出异常更合理
