### ISSUE TITLE
Nacos CPU surges, nacos.log keeps refreshing the error log: "user not found!"

### ISSUE THREAD

**Issue by opencmit2** [alibaba/nacos#11901]
**Describe the bug**

Nacos CPU surges, nacos.log keeps refreshing the error log: "user not found!"

**Expected behavior**
背景： 修改了默认的nacos 密码， 业务有部分密码未及时更新。

然后发现nacos.log日志不停的刷新“user not found!”一直到CPU 占用100%，调大了CPU后也解决不了问题。 

1、通过NetworkPolicy限制业务namespace访问， 重启nacos后 nacos server变正常。
2、逐个开启业务请求nacos后又发现日志刷新“user not found!”。
3、再次使用NetworkPolicy只能让nacos三节点相互访问， 日志也还是不停的刷新“user not found!”，最终nacos pod不停的重启。

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]  nacos-server  2.2.3 ，nacos-client 2.1
 - Module [e.g. naming/config] naming/config
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
**Additional context**

**Comment by Bo-Qiu** [comment]
https://github.com/alibaba/nacos/issues/11494
貌似问题已修复，client sdk 升级至最新版本试试

**Comment by opencmit2** [comment]
Hi @Bo-Qiu 
我的配置中是开启认证的。
```text
nacos.core.auth.enabled=true
```

**Comment by 0781614260** [comment]
في الاثنين، ١ نيسان، ٢٠٢٤, ٥:٥٤ ص opencmit2 ***@***.***> كتب:

**Comment by KomachiSion** [comment]
`user not found!` 说明你用户名密码不存在，或者配置错误，和https://github.com/alibaba/nacos/issues/11494无关。

**Comment by opencmit2** [comment]
@KomachiSion 
但是令人惊讶的是，它竟然能导致CPU使用率急剧上升，以至于nacos都无法正常运行。

**Comment by KomachiSion** [comment]
> @KomachiSion 但是令人惊讶的是，它竟然能导致CPU使用率急剧上升，以至于nacos都无法正常运行。

因为密码存储要加密，加密解密是CPU密集型的操作，而且极其密集[狗头] 正常不会这么频繁调用，只有配置了错误的用户名密码的时候， 大量客户端重试的时候才会

**Comment by KomachiSion** [comment]
当然你可以实现你自己的鉴权插件， 使用更高性能或者更安全的加密解密组件，甚至不进行加密存储都可以，插件中的具体实现由你自定义了。

**Comment by opencmit2** [comment]
@KomachiSion 
感谢解答，大概知道是怎么回事了。
