### ISSUE TITLE
nacosV2.1.1 error:Request error, please try again later!

### ISSUE THREAD

**Issue by DoubleLeo** [alibaba/nacos#11907]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
when save config, raise Request error, please try again later!

### Describe what you expected to happen
save success.

### How to reproduce it (as minimally and precisely as possible)

1. input a long config
2. save
3. error happens

### Tell us your environment
client:chrome 121.0.6167.185
server:ubuntu 20.04.6,nacos 2.1.1

### Anything else we need to know?
see pictures:
![image](https://github.com/alibaba/nacos/assets/3361414/e050ae6e-e23b-4901-8722-8cfca894a6fe)

Thanks.

**Comment by DoubleLeo** [comment]
![PixPin_2024-04-02_00-07-40](https://github.com/alibaba/nacos/assets/3361414/c5287278-e359-45c7-9d6d-37d38e0d8dc2)

see errinfo,config save ok in db,but config get interface raise a exception.

**Comment by KomachiSion** [comment]
Please provide more information such as relative logs.

Or upgrade to new version and retry.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem.
