### ISSUE TITLE
console-ui npm run build 报错 error 

### ISSUE THREAD

**Issue by Zmaxtm** [alibaba/nacos#11906]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
![image](https://github.com/alibaba/nacos/assets/150814203/d808c40e-c8c6-44cf-831d-8e0f134b110e)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
node -v
v18.19.1

**Comment by KomachiSion** [comment]
plase use v12
