### ISSUE TITLE
nacos-gprc-client-executor continuously creates thread bug

### ISSUE THREAD

**Issue by CloudLasting** [alibaba/nacos#11911]
version：
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2023.0.0.0-RC1</version>
        </dependency>

description：
Through monitoring, it has been found that the nacos gprc client executor is continuously creating threads. Could you please confirm if this is a bug.
<img width="503" alt="image" src="https://github.com/alibaba/nacos/assets/11511934/58c44d83-1fc2-419c-b4ab-4d2e21a06937">

**Comment by godhth** [comment]
会根据cpu核数计算合适的线程池参数，如果是k8s的pod请检查下limit。

![image](https://github.com/alibaba/nacos/assets/63696328/6f7a4fb7-4ed3-462b-9125-914fa7d5d9d5)
或者自定义下线程池参数
![image](https://github.com/alibaba/nacos/assets/63696328/0b7b1150-fb07-4949-9791-5820f897dbfc)

**Comment by KomachiSion** [comment]
线程池id并不能说明问题， 因为nacos-gprc-client-executor是动态线程池， 会随着性能压力关闭和新增线程，并发高的时候创建新的线程，最大不超过上限， 并发低的时候关闭无用线程池释放资源，最低不超过coresize

**Comment by CloudLasting** [comment]
你们判断吧，可以重现看下，之所以是线程池那肯定是在一定范围内的线程复用，而不是频繁创建线程，我忘了说明的是这个id是从1一直涨上来的，从表面看没有复用，压力也是持续加压的未曾中断，我只是反馈下，个人觉得不太合理

**Comment by KomachiSion** [comment]
是一定程度上复用， 如果并发量很小，会一直使用core数量的线程，如果短时间内有很多并发请求，才会扩容线程池。

同时扩容后的线程池会有一个keepalive时间，超过这个时间没有新任务才会缩容。

不同于原生线程池，队列满了才会扩线程， 这样弹性并发的效果会比较弱。
