### ISSUE TITLE
Can you unify the dependency packages of the same function?

### ISSUE THREAD

**Issue by jqncc** [alibaba/nacos#1191]
jackson / fastjson
guava /commons-lang
slf4j /commons-logging
这几个架包功能相同或类似的能否统一使用一个
现在项目依赖的架包太多太杂,所以希望相同或类似功能的包尽量能统一

**Comment by nkorange** [comment]
@jqncc It makes sense, welcome to contribute for it.

**Comment by zhaoyuguang** [comment]
@I will try finish this issue@

**Comment by JackSun-Developer** [comment]
@zhixiangyuan How is it going?

**Comment by KomachiSion** [comment]
Someone has fixed in 2.1.0
