### ISSUE TITLE
nacos client 1.x 取消配置监听导致死循环，cpu占满

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#11917]
取消所有配置监听后 cacheMap 将为空，checkUpdateDataIds 调用 checkUpdateConfigStr 并传入空字符串，checkUpdateConfigStr 有判空，若为空字符串，不发送网络请求，直接返回，最终导致 LongPollingRunnable 空转
建议 LongPollingRunnable 也做下判空操作，若 cacheMap 为空，则 return，该问题可稳定复现，只需监听配置，取消配置监听即可。

<img width="919" alt="image" src="https://github.com/alibaba/nacos/assets/6041166/5c89f0b6-09fd-4178-b447-461d84254ad0">  

<img width="985" alt="image" src="https://github.com/alibaba/nacos/assets/6041166/d97b7981-3d2c-4059-9199-8f654606c66a">

**Comment by KomachiSion** [comment]
如果有监听了多个配置，取消一个配置的监听，应该不会有这问题吧？

另外看下2.x的client是否也存在这个问题？

**Comment by ijustyce** [comment]
> 如果有监听了多个配置，取消一个配置的监听，应该不会有这问题吧？
> 
> 另外看下2.x的client是否也存在这个问题？

感觉是这样，同一个 listener 监听的 dataid 都取消了，那么就死循环了，监听多个，取消 1 个是OK的。我们内部使用的 是 2.1.2 粗略看了下 2.1.2 的代码，没有判空，理论上也存在问题。
```java
@Override
public void startInternal() {
    executor.schedule(() -> {
        while (!executor.isShutdown() && !executor.isTerminated()) {
            try {
                listenExecutebell.poll(5L, TimeUnit.SECONDS);
                if (executor.isShutdown() || executor.isTerminated()) {
                    continue;
                }
                executeConfigListen();
            } catch (Throwable e) {
                LOGGER.error("[ rpc listen execute ] [rpc listen] exception", e);
            }
        }
    }, 0L, TimeUnit.MILLISECONDS);
    
}
```

**Comment by shiyiyue1102** [comment]
2.x没有问题，没有信号量的情况下，是5s检查一次，和1.x有差别
