### ISSUE TITLE
I use the openapi of nacos version 2.3.1 to send heartbeat packets, which will trigger the protection threshold.

### ISSUE THREAD

**Issue by yyyyuck** [alibaba/nacos#11912]
I use the openapi of nacos version 2.3.1 to send heartbeat packets, which will trigger the protection threshold.

code:
`def send_heartbeat():
    params = {
        "serviceName": register_service_name,
        "ip": register_ip,
        "port": register_port,
        "namespaceId": namespace,
        "groupName": group,
        "beat": json.dumps({
            "ip": register_ip,
            "port": register_port,
            "serviceName": register_service_name
        })
    }
    while True:
        try:
            # response = requests.put(f'{server_addresses}{heart_beat_url}', params=params, auth=auth)
            response = requests.put(f'{server_addresses}{heart_beat_url}', params.get('beat'), params=params, auth=auth)
            check_status(response)
        except Exception as e:
            print(e)
        time.sleep(5)`

It will happen on the nacos server:
![Snipaste_2024-04-02_15-28-08](https://github.com/alibaba/nacos/assets/75251374/0de52ddb-a805-488b-b9e9-324975918d0d)

**Comment by yyyyuck** [comment]
uri /nacos/v1/ns/instance/beat

**Comment by KomachiSion** [comment]
There **must** be some request parameter wrong, such as group name , service name ,ip , port or clusterName.

Or you service is persistence service, which is not use heart beat to do health check.

you can print the response message and information , not only check the status.

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
