### ISSUE TITLE
The abnormal exit mechanism does not take effect

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#11926]
os：eulerosv2r12
jdk：1.8
nacos：2.1.0
We are doing performance testing because there is a large amount of disk space in the container and errors are reported.
After checking the source code, I found an abnormal exit mechanism, but it didn't work.
At the same time, I have a question. Is it reasonable to exit the process directly?

The reason is that nacos cannot correctly determine the exception return information.
os：eulerosv2r12
jdk：1.8
nacos：2.1.0
我们在做性能测试因为容器内磁盘空间大量报错，
查阅源码发现有异常退出机制 但并未奏效。
原因是nacos的无法正确判断异常返回信息。
同时有个疑问 这里直接退出进程是否合理。

error log
> config_20240402075128821.zip:2024-04-02 07:51:13.662+02:00 |ERROR|com.alibaba.nacos.server.DumpTaskManager.0||||124|com.alibaba.nacos.config.dumpLog [dump-exception] save disk error. tenant12345678901234567890123456712345678901234567890123456789012345678901234567890123456789012345_344481+group_tenant12345678901234567890123456712345678901234567890123456789012345678901234567890123456789012345_102511+2111, java.nio.file.FileSystemException: /***********/data/tenant-config-data/2111/group_tenant12345678901234567890123456712345678901234567890123456789012345678901234567890123456789012345_102511/tenant12345678901234567890123456712345678901234567890123456789012345678901234567890123456789012345_344481: No space left on device

not work code
https://github.com/alibaba/nacos/blob/2f494313ffec86ef57bd7318fa5a678ffd27dedd/config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java#L142

**Comment by KomachiSion** [comment]
可以优化一下判断条件，把equals改为contains

但是不能一异常就退出， 要考虑到普通的IO异常
