### ISSUE TITLE
nacos 客户端对其他编程语音的支持与维护

### ISSUE THREAD

**Issue by huyang19881115** [alibaba/nacos#11920]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

目前看了下python 连接 nacos-server 好像代码好久也不更新，并且连接其他的有问题。

**Comment by KomachiSion** [comment]
除go和java sdk， 其余多语言sdk暂时由社区贡献者自行维护， 如果你有意愿，可以加入我们，申请成为某个sdk的负责人。

**Comment by huyang19881115** [comment]
哎， 技术太菜，没办法胜任，不过开源弄得挺好的



***@***.***
 
发件人： 杨翊 SionYang
发送时间： 2024-04-08 10:09
收件人： alibaba/nacos
抄送： 胡洋; Author
主题： Re: [alibaba/nacos] nacos 客户端对其他编程语音的支持与维护 (Issue #11920)
除go和java sdk， 其余多语言sdk暂时由社区贡献者自行维护， 如果你有意愿，可以加入我们，申请成为某个sdk的负责人。
