### ISSUE TITLE
Failed to compile nacos and install to the local repository

### ISSUE THREAD

**Issue by farmer-liuz1024** [alibaba/nacos#11933]
**Describe the bug**
An error was reported when the multi-data source plug-in compiled nacos and installed into the local repository.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:50 min
[INFO] Finished at: 2024-04-08T15:21:49+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.2.2:jar (default-jar) on project config-test: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
[ERROR]
```

**How to Reproduce**
1. `git clone git@github.com:alibaba/nacos.git`
2. `cd nacos && mvn -B clean package install -Dmaven.test.skip=true`

**Desktop (please complete the following information):**
 - OS: Windows 10 专业版  x64
 - Version nacos-2.2.4、maven 3.9.6、jdk1.8
 - Module nacos-config-test 2.2.4

**Additional context**
This is the compilation and installation log：
[build.log](https://github.com/alibaba/nacos/files/14902361/build.log)

**Comment by KomachiSion** [comment]
add profile `-Prelease-nacos`

**Comment by farmer-liuz1024** [comment]
@KomachiSion ：Add -Prelease-nacos and the result looks like this
` Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.2.4:shade (default) on project nacos-client: Error creating shaded jar: duplicate entry: META-INF/services/com.alibaba.nacos.shaded.io.grpc.ServerProvider -> [Help 1]`

**Comment by KomachiSion** [comment]
I have no idea about this,  The CI and IT in github run with ubuntu and centos is working well. And My Local env is macos with intel x64 also work well.

And many others for community also can work well.

Maybe there some env problem or setting wrong cause the problem? I have no windows env and can't help you. Let community try find the problem.

**Comment by farmer-liuz1024** [comment]
Thanks for your reply. I'll try again.

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.

**Comment by mikolls** [comment]
> 感谢您的回复。我会再尝试。

请问您解决了吗，我也遇到了这个问题

**Comment by mikolls** [comment]
> Thanks for your reply. I'll try again.

May I ask if you have resolved it? I’ve encountered the same issue.

**Comment by mikolls** [comment]
My solution is:

   Use the maven command to package: ``mvn -B clean install -Dmaven.test.skip=true``

   No need for ``mvn package``

   package + install will cause packaging twice, so maven-jar-plugin will prompt: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.

   references link: 
      [stackoverflow](https://stackoverflow.com/questions/40964500/maven-jar-plugin-3-0-2-error-you-have-to-use-a-classifier-to-attach-supplementa )
      [maven](https://maven.apache.org/pom.html)

   Desktop:

	OS: Windows 10 专业版 x64
	Version：nacos-2.4.0、maven 3.9.6、jdk1.8

**Comment by farmer-liuz1024** [comment]
@mikolls : It's OK if I execute package first and then install.
