### ISSUE TITLE
No such extension com.alibaba.dubbo.registry.RegistryFactory by name nacos

### ISSUE THREAD

**Issue by MrQiaoLei** [alibaba/nacos#1193]
xml配置如下：
    <dubbo:registry address="nacos://127.0.0.1:8848"/>
    <dubbo:protocol name="dubbo" port="20880"/>
包正常引入：
          <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-registry-nacos</artifactId>
                <version>${dubbo-registry-nacos.version}</version>
            </dependency>
nacos启动正常，页面可正常访问：http://192.168.1.183:8848/nacos/index.html

**Comment by nkorange** [comment]
Report it to Dubbo please.

**Comment by Scalaaaaaa** [comment]
我的按照下面的方案就不报这个错了
把下面的依赖的groupId改一下
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-registry-nacos</artifactId>
    <version>2.7.4.1</version>
</dependency>

改成
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>dubbo-registry-nacos</artifactId>
    <version>2.6.7</version>
</dependency>

**Comment by Chunghwa-2018** [comment]
@Scalaaaaaa 用 com.alibaba 依然存在此问题
