### ISSUE TITLE
n version 2.3.1, the NacosFactory. createConfigService method cannot resolve domain names. Is there a good method to replace it?

### ISSUE THREAD

**Issue by dengyichao** [alibaba/nacos#11938]
**Describe the bug**
Hello, the client of version 2.3.1 of Nacos is calling NacosFactory. createConfigService (pro); When using this method, an error occurred and the domain name data could not be resolved. Is there a better alternative now? The specific code is as follows

**Expected behavior**
Can use domain name to obtain configuration values on Nacos

**Actually behavior**
Unable to obtain relevant nacos configuration data using domain nam

**How to Reproduce**

1、native code
InputStream resourceAsStream = XxConfig.class.getClassLoader().getResourceAsStream("bootstrap.yml");
        properties = new Properties();
        try {
            properties.load(resourceAsStream);
            Properties pro = new Properties();
            pro.put("serverAddr", properties.getProperty("server-addr"));
            pro.put("namespace", properties.getProperty("namespace"));
            logger.info("正在从bootstrap.yml中读取文件，server-addr:" +  properties.getProperty("server-addr") + ";namespace:" + properties.getProperty("namespace"));
            ConfigService configService = NacosFactory.createConfigService(pro);
            String config = configService.getConfig(DATA_ID, GROUP, 5000);
            if(StringUtils.isBlank(config)){
                throw new RuntimeException("从bootstrap.yml获取的config文件内容为空，初始化配置失败");
            }
            logger.info("从bootstrap.yml获取的config文件内容为：" + config);
2、Config=configService. getConfiguration (DATA_iD, GROUP, 5000);

The data obtained from this code is a null value. I have checked that DATA-ID and GROUP are both correct. If I change the value of the serverAddr field from domain name to IP address, I can successfully obtain the relevant data. However, my service runs in k8s and cannot use the actual domain name

**Comment by KomachiSion** [comment]
I test for 2.3.1.  The domain can work well. Maybe you should check the logs in `${user.home}/logs/nacos/*`

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
