### ISSUE TITLE
Can contextPath of client be configured

### ISSUE THREAD

**Issue by paascloud** [alibaba/nacos#1194]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848/naco]) tried: failed to req API:http://127.0.0.1:8848/naco/nacos/v1/ns/instance. code:401 msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed May 08 18:26:28 CST 2019</div><div>There was an unexpected error (type=Unauthorized, status=401).</div><div>Unauthorized</div></body></html>

### Describe what you expected to happen

public static String WEB_CONTEXT = "/nacos";
public static String NACOS_URL_BASE = WEB_CONTEXT + "/v1/ns";
public static String NACOS_URL_INSTANCE = NACOS_URL_BASE + "/instance";

客户端在生成URL调用服务端的时候, 在URL会多一个/nacos的前缀

### How to reproduce it (as minimally and precisely as possible)

cat conf/application.properties

server.contextPath=/
server.servlet.contextPath=/

### Tell us your environment
macOS

**Comment by nkorange** [comment]
You can set a customized web context only when Naco server provides this context. Did you set the property ```nacos.naming.web.context```?

**Comment by paascloud** [comment]
How to use the spring cloud configuration?

for example  spring-cloud-alibaba

**Comment by nkorange** [comment]
你是设置了nacos.naming.web.context还是没设？
