### ISSUE TITLE
nacos订阅服务死循环，推送消息  naming.subscribe(service, event -> {}

### ISSUE THREAD

**Issue by JuniorRay** [alibaba/nacos#11949]
@PostConstruct
    public static void init() throws Exception {
        Properties properties = new Properties();
        properties.setProperty("serverAddr", "192.168.15.130:8848");
        properties.setProperty("namespace", "public");
//        properties.setProperty(PropertyKeyConst.USERNAME, myDefinedConfig.getNacosUsername());
//        properties.setProperty(PropertyKeyConst.PASSWORD, myDefinedConfig.getNacosPassword());
        NamingService naming = NamingFactory.createNamingService(properties);
        List<ServiceInstancesVO> allServiceInstances = NacosUtil.getAllServiceInstance(naming);
        serviceNames = allServiceInstances.stream().map(ServiceInstancesVO::getAppId).collect(Collectors.toList());
 
        for(String service : serviceNames) {
            naming.subscribe(service, event -> {
                log.info("触发监听");
                List<Instance> instances =  ((NamingEvent)event).getInstances();
                String serviceName = ((NamingEvent)event).getServiceName();
                cache.computeIfAbsent(serviceName, k -> instances.size());
                if(cache.get(serviceName) <instances.size()){
                    cache.put(serviceName, instances.size());
                }
                if(instances.size() <cache.get(serviceName)) {
                    log.info("============服务下线"+ serviceName);
                    cache.put(serviceName, instances.size());
                    try {
                        sendDingDingMessage(2,(NamingEvent)event);
                    } catch (InterruptedException | IOException e) {
                        e.printStackTrace();
                    }
                }else {
                    log.info("============服务上线"+ serviceName+",当前节点数量："+instances.size());
                    try {
                        sendDingDingMessage(1,(NamingEvent)event);
                    } catch (InterruptedException | IOException e) {
                        e.printStackTrace();
                    }

                }
            });
        }
    }
    
    这段代码放在spring容器中,就会死循环推送消息！！！！，但是如果放在main函数中通过sleep 阻塞就没有问题！！！
    
    
      public static void main(String[] args) throws Exception {
        init();
        Thread.sleep(Integer.MAX_VALUE);
    }

**Comment by JuniorRay** [comment]
已找到原因：
NacosNamingService中如果调用了getAllInstances,或者selectInstances
则会死循环订阅！！！


 public List<Instance> getAllInstances(String serviceName, String groupName, List<String> clusters,
            boolean subscribe) throws NacosException {
        ServiceInfo serviceInfo;
        String clusterString = StringUtils.join(clusters, ",");
        if (subscribe) {
            serviceInfo = serviceInfoHolder.getServiceInfo(serviceName, groupName, clusterString);
            if (null == serviceInfo || !clientProxy.isSubscribed(serviceName, groupName, clusterString)) {
                serviceInfo = clientProxy.subscribe(serviceName, groupName, clusterString);
            }
        } else {
            serviceInfo = clientProxy.queryInstancesOfService(serviceName, groupName, clusterString, 0, false);
        }
        List<Instance> list;
        if (serviceInfo == null || CollectionUtils.isEmpty(list = serviceInfo.getHosts())) {
            return new ArrayList<Instance>();
        }
        return list;
    }

**Comment by stone-98** [comment]
低版本没有加这个判断 !clientProxy.isSubscribed(serviceName, groupName, clusterString)，2.3.0版本已经修复这个问题了，

**Comment by KomachiSion** [comment]
没看懂，nacos自身没有循环订阅的逻辑，这段逻辑自身也是一个单向循环。

**Comment by JuniorRay** [comment]
只要你在订阅服务的方法回调接口listener内部，调取NamingService.selectInstances，机会触发死循环订阅直至oom我看了最新的nacos2.3.0版本依然存在这个逻辑，只是把方法封装复用了一下。bug我怀疑还是存在的。



---原始邮件---
发件人: "杨翊 ***@***.***&gt;
发送时间: 2024年4月11日(周四) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] nacos订阅服务死循环，推送消息  naming.subscribe(service, event -&gt; {} (Issue #11949)




 
没看懂，nacos自身没有循环订阅的逻辑，这段逻辑自身也是一个单向循环。

**Comment by KomachiSion** [comment]
那我觉得是使用方法错误， 为什么在listener中还要调用NamingService.selectInstances？ listner的方法中已经给予了最新的实例列表了。

**Comment by KomachiSion** [comment]
而且解释不通的是： 为什么放main里面运行就可以， 放spring里就不行？

**Comment by JuniorRay** [comment]
不在订阅里调用，在其他方法里面调用查询实例也会造成本身订阅的死循环递归



---原始邮件---
发件人: "杨翊 ***@***.***&gt;
发送时间: 2024年4月15日(周一) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] nacos订阅服务死循环，推送消息  naming.subscribe(service, event -&gt; {} (Issue #11949)




 
那我觉得是使用方法错误， 为什么在listener中还要调用NamingService.selectInstances？ listner的方法中已经给予了最新的实例列表了。

**Comment by KomachiSion** [comment]
还是看不懂，为什么会死循环， get都是单向次的操作，而且同一个service的订阅已经存在的话，不会重新发起订阅请求， 除非外层订阅的服务和里层get的服务不相同，但是也就重复一次。

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
