### ISSUE TITLE
删除空服务时，发布DeregisterServiceTraceEvent 传参错误

### ISSUE THREAD

**Issue by Happy-26** [alibaba/nacos#11951]
在 `ServiceNameFilter#doFilter()`方法中，使用`groupName@@serviceName`作为一个新的服务名，在`ServiceController#remove()`方法中，发布`DeregisterServiceTraceEvent`事件时，未对组装后的serviceName进行处理，源代码如下：

    @DeleteMapping
    @TpsControl(pointName = "NamingServiceDeregister", name = "HttpNamingServiceDeregister")
    @Secured(action = ActionTypes.WRITE)
    public String remove(@RequestParam(defaultValue = Constants.DEFAULT_NAMESPACE_ID) String namespaceId,
            @RequestParam String serviceName) throws Exception {
        getServiceOperator().delete(namespaceId, serviceName);
        NotifyCenter.publishEvent(
                new DeregisterServiceTraceEvent(System.currentTimeMillis(), namespaceId, "", serviceName));
        return "ok";
    }

修改后的代码如下：

    @DeleteMapping
    @TpsControl(pointName = "NamingServiceDeregister", name = "HttpNamingServiceDeregister")
    @Secured(action = ActionTypes.WRITE)
    public String remove(@RequestParam(defaultValue = Constants.DEFAULT_NAMESPACE_ID) String namespaceId,
            @RequestParam String serviceName) throws Exception {
        
        getServiceOperator().delete(namespaceId, serviceName);
        NotifyCenter.publishEvent(
                new DeregisterServiceTraceEvent(System.currentTimeMillis(), namespaceId,
                        NamingUtils.getGroupName(serviceName), NamingUtils.getServiceName(serviceName)));
        return "ok";
    }

**Comment by KomachiSion** [comment]
有工具类：NamingUtils 来获取groupName和serviceName
