### ISSUE TITLE
在k8s跑的nacos集群,nacos版本是1.4.3， 就这样毫无征兆的bug出现了

### ISSUE THREAD

**Issue by wsw136** [alibaba/nacos#11958]
![企业微信截图_20240412175036](https://github.com/alibaba/nacos/assets/36026057/9e7c0541-c663-43bf-b7ef-fb81589c86bc)

在k8s里的业务pod已经正常下线了，但在nacos中业务实例不会自动剔除已经失效的个数。

**Comment by KomachiSion** [comment]
1. 查看日志，是否有什么错误日志可以排查
2. 查看部署集群是否正确，比如cluster.conf中是否有多余的ip，或者节点间的cluster.conf不一致
3. 如果上述都没有发现问题，可以考虑升级到2.X版本，1.X版本已经很旧了。

**Comment by wsw136** [comment]
> 1. 查看日志，是否有什么错误日志可以排查
> 2. 查看部署集群是否正确，比如cluster.conf中是否有多余的ip，或者节点间的cluster.conf不一致
> 3. 如果上述都没有发现问题，可以考虑升级到2.X版本，1.X版本已经很旧了。

当时nacos日志没有看出有异常，在nacos页面查看集群状态也是正常的，没有出现2个leader，  这个情况无法复现，也是随机性的概率出现。 
那现在官方最新的2.3.2版本如何？

**Comment by KomachiSion** [comment]
这个问题我自己的环境中没有出现过，社区中反馈有问题的反馈，大多数都是部署的时候没有部署正确导致的，比如每个节点的cluster.conf不一致。

**Comment by wingyiu** [comment]
这个问题我这也出现了，而且界面没有地方手动删除

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.
