### ISSUE TITLE
[Bug]：Can not aquire the specific config

### ISSUE THREAD

**Issue by robocanic** [alibaba/nacos#11967]
**Describe the bug**

environments:
- java version: corretto 21
- nacos sdk/client version:  2.3.2
- nacos deployment mode: standalone, windows10 PC

I start a dubbo service on local PC(the code of this dubbo service comes from the [dubbo-samples](https://github.com/apache/dubbo-samples/tree/master/10-task/dubbo-samples-shop/dubbo-samples-shop-user)), using nacos client 2.2.0.  And it works fine, the service registered and I can find the config and service info through the console:
![image](https://github.com/alibaba/nacos/assets/79916872/1810a478-daed-4dbc-876d-46a653c741c5)
![image](https://github.com/alibaba/nacos/assets/79916872/9d8f16b2-39be-4276-bb78-1f66bceecedf)

Following the  "quick start" of the [ official website](https://nacos.io/docs/latest/guide/user/sdk/#_top) ,  I  want to get the config content of "dataId=org.apache.dubbo.samples.UserService:::provider:shop-user, group=dubbo" as below:
``` java
public class NacosApplication {
    public static void main(String[] args) {
        String content;
        try {
            String serverAddr = "localhost:8848";
            String dataId = "org.apache.dubbo.samples.UserService:::provider:shop-user";
            String group = "dubbo";
            Properties properties = new Properties();
            properties.put("serverAddr", serverAddr);
            ConfigService configService = NacosFactory.createConfigService(properties);
            content = configService.getConfig(dataId, group, 5000);
            System.out.println("content is:"+content);
        } catch (NacosException e) {
            e.printStackTrace();
        }
    }
}
```
The expected result config content should be :
![image](https://github.com/alibaba/nacos/assets/79916872/f3aa1a05-d992-48ad-9fc2-6c0406eebd52)
But it returns null:
![image](https://github.com/alibaba/nacos/assets/79916872/610a536d-dd8f-43d7-80e5-8ab9c3e71ea7)

Then I change  the dataId and group to try to aquire another config content:
```java
public class NacosApplication {
    public static void main(String[] args) {
        String content;
        try {
            String serverAddr = "localhost:8848";
            String dataId = "org.apache.dubbo.samples.UserService";
            String group = "mapping";
            Properties properties = new Properties();
            properties.put("serverAddr", serverAddr);
            ConfigService configService = NacosFactory.createConfigService(properties);
            content = configService.getConfig(dataId, group, 5000);
            System.out.println("content is:"+content);
        } catch (NacosException e) {
            e.printStackTrace();
        }
    }
}
```
It works fine just as below, which is really wired:
![image](https://github.com/alibaba/nacos/assets/79916872/b0a64613-bac1-4b37-ac22-2ff56af5c37f)
![image](https://github.com/alibaba/nacos/assets/79916872/67304fcf-5d82-45e5-b155-9ab53b370340)

I have confirmed that the dataId and group is the same as the console shows, I have no idea for this bug, can someone tell me where the problem lies?

**Comment by 985492783** [comment]
你好，麻烦将不可用的配置内容，dataId和group发一下，我复现下看看

**Comment by robocanic** [comment]
> 你好，麻烦将不可用的配置内容，dataId和group发一下，我复现下看看

dataId: org.apache.dubbo.samples.UserService:::provider:shop-user
group: dubbo
content: {"annotations":[],"canonicalName":"org.apache.dubbo.samples.UserService","codeSource":"file:/D:/code/dubbo-samples/10-task/dubbo-samples-shop/dubbo-samples-shop-user-api/target/classes/","methods":[{"annotations":[],"name":"register","parameterTypes":["org.apache.dubbo.samples.User"],"parameters":[],"returnType":"boolean"},{"annotations":[],"name":"getInfo","parameterTypes":["java.lang.String"],"parameters":[],"returnType":"org.apache.dubbo.samples.User"},{"annotations":[],"name":"login","parameterTypes":["java.lang.String","java.lang.String"],"parameters":[],"returnType":"org.apache.dubbo.samples.User"},{"annotations":[],"name":"timeoutLogin","parameterTypes":["java.lang.String","java.lang.String"],"parameters":[],"returnType":"org.apache.dubbo.samples.User"}],"parameters":{"anyhost":"true","pid":"20560","interface":"org.apache.dubbo.samples.UserService","side":"provider","dubbo":"2.0.2","application":"shop-user","release":"3.2.7","executor-management-mode":"isolation","file-cache":"true","methods":"getInfo,login,register,timeoutLogin","deprecated":"false","qos.port":"20994","service-name-mapping":"true","timeout":"1000","generic":"false","bind.port":"20884","token":"d9f0fc3f-2fc6-4684-9405-e8c2311df916","qos.anonymous.access.permission.level":"PROTECTED","bind.ip":"2.0.0.1","prefer.serialization":"fastjson2,hessian2","background":"false","dynamic":"true","qos.anonymous.access.allow.commands":"metrics","timestamp":"1713234842852"},"types":[{"enums":[],"items":[],"properties":{},"type":"boolean"},{"enums":[],"items":[],"properties":{"realName":"java.lang.String","password":"java.lang.String","mail":"java.lang.String","phone":"java.lang.String","env":"java.lang.String","username":"java.lang.String"},"type":"org.apache.dubbo.samples.User"},{"enums":[],"items":[],"properties":{},"type":"java.lang.String"}],"uniqueId":"org.apache.dubbo.samples.UserService@file:/D:/code/dubbo-samples/10-task/dubbo-samples-shop/dubbo-samples-shop-user-api/target/classes/"}

**Comment by 985492783** [comment]
我用jdk8和jdk21都没有复现出来，客户端debug看下请求

**Comment by robocanic** [comment]
debug:
![image-20240416172752667](https://github.com/alibaba/nacos/assets/79916872/c8c28d52-41c9-4d3b-9424-5c2d5f29f027)


config-dump.log

![image-20240416173742502](https://github.com/alibaba/nacos/assets/79916872/4d02621f-ca08-41c9-96d1-1940f1dd8ee9)


config-pull-check.log

![image-20240416173834122](https://github.com/alibaba/nacos/assets/79916872/9496a604-a7e7-4282-9d5c-3b7dab260574)

看起来是server端有些问题

**Comment by KomachiSion** [comment]
新版本应该在写缓存的时候有进行encode的，是否是系统版本读取的时候没读取正确？

可以看下 PathEncode 和PathEncodeManager是否没有用上或者读取错误导致没有识别到用Windows的PathEncode

**Comment by KomachiSion** [comment]
看了下，好像是个bug， 之前PathEncode只作用于服务端， 之后DiskUtil合并到common的时候，发现common中已经有一个一样的DiskUtil了， 所以删除了config模块的DiskUtil

**Comment by KomachiSion** [comment]
#10101

**Comment by KomachiSion** [comment]
com.alibaba.nacos.config.server.service.dump.disk.ConfigRawDiskService

DiskUtil被迁移到了这个上面，但是丢失了#10101中的encode修复

**Comment by robocanic** [comment]
这个问题在哪些版本中存在？
