### ISSUE TITLE
Nacos springcloud war包方式 外置tomcat 部署项目。无法注册，服务列表查询不到

### ISSUE THREAD

**Issue by assoda1314** [alibaba/nacos#11974]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
应该是启动部署方式或配置问题导致未发起注册， 可以查看nacos-client相关日志进行确认， 如果发起了注册， 会有REGISTER-SERVICE的关键词信息。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem.
