### ISSUE TITLE
Aliyun high cpu load warnning

### ISSUE THREAD

**Issue by lxs2016** [alibaba/nacos#11978]
### what happed

cause high cpu load warnning,we checked the project and found that frequently GC maybe the reason. Then we dumped stack file from sever that the class RetryStream took large part of memory.

![image-20240417113852220](https://github.com/alibaba/nacos/assets/20491159/3cf2e7c7-5977-4a0e-becd-f8fb35b6d056)

![image-20240418180353628](https://github.com/alibaba/nacos/assets/20491159/2027f2d0-08da-4aa8-a0fd-bc2a842138a9)

Above are 2 pics about memory snapshot，i wanna know which case can cause this problem?

###

**Comment by KomachiSion** [comment]
Has your network with problem or nodes has down?  

I think the retryStream is a grpc work flow to do retry. 

And there is a strange thinks, the grpc client is too many, The grpcClient should be `n` size. But your node has 710000.

**Comment by KomachiSion** [comment]
Please help us to check this issue. @shiyiyue1102

**Comment by KomachiSion** [comment]
@lxs2016 please provide more information such as your deploy env, cluster size, and logs.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem and can't reproduce in community.
