### ISSUE TITLE
Unable to get profile other than localhost

### ISSUE THREAD

**Issue by youlvlv** [alibaba/nacos#11973]
**Describe the bug**
If I use local nacos, I can get the configuration file normally, but if I use remote nacos, I can't get any configuration files, and when I change the log level to debug, the console does not have any warnings or exceptions

**Expected behavior**
The normal configuration file is obtained

**Actually behavior**
An empty configuration file was obtained

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [nacos-server 2.3.0, spring-cloud-alibaba 2023.0.0.0-RC1]
 - Module [e.g. naming/config]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**

**Comment by KomachiSion** [comment]
It seems env problem, please check your app connection to remote nacos successfully and configure correct dataid, group and namespace.

**Comment by youlvlv** [comment]
I have checked the relevant configuration, I even copied my local nacos to the remote server, the problem still occurred, I copied the remote nacos to the local, but the configuration file can also be obtained normally

> It seems env problem, please check your app connection to remote nacos successfully and configure correct dataid, group and namespace.

**Comment by KomachiSion** [comment]
> I have checked the relevant configuration, I even copied my local nacos to the remote server, the problem still occurred, I copied the remote nacos to the local, but the configuration file can also be obtained normally
> 
> > It seems env problem, please check your app connection to remote nacos successfully and configure correct dataid, group and namespace.

From the description, I can be sure it is configuration problem or env problem. 
1. Maybe you app config is force connection `localhost`  domain.
2. the network from your app to remote nacos has problem.

**Comment by youlvlv** [comment]
> > I have checked the relevant configuration, I even copied my local nacos to the remote server, the problem still occurred, I copied the remote nacos to the local, but the configuration file can also be obtained normally
> > > It seems env problem, please check your app connection to remote nacos successfully and configure correct dataid, group and namespace.
> 
> From the description, I can be sure it is configuration problem or env problem.
> 
> 1. Maybe you app config is force connection `localhost`  domain.
> 2. the network from your app to remote nacos has problem.



I checked my application, and his link address is fine, and my local nacos is always open. After I changed the configuration file, it won't start properly. For the second point, if I can't connect to the remote nacos, I should get a warning or exception in the console, but I don't see any warning or exception

**Comment by KomachiSion** [comment]
see logs, default in ${user.home}/logs/nacos

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem. And from current information, it's a large possible configuration problem.

**Comment by youlvlv** [comment]
> see logs, default in ${user.home}/logs/nacos

what I need to see that log?
