### ISSUE TITLE
集群节点metadata不一致，已经移除的节点ip还在metadata中

### ISSUE THREAD

**Issue by weiya1990** [alibaba/nacos#11970]
集群节点metadata不一致，已经移除的节点ip还在metadata中，并且cluster.conf已经删除移除的节点alipay-jraft.log日志显示还去连接已经移除的节点
![image](https://github.com/alibaba/nacos/assets/38902618/59105c38-53ab-46e8-82b1-80ac0ce7fa7b)

**Comment by KomachiSion** [comment]
如果一次性删除超过半数，那么删除一定会失败，这是raft协议定义的， raft的metadata变更也需要走leader。

**Comment by weiya1990** [comment]
最后删除data目录重启解决了

**Comment by KomachiSion** [comment]
删除data目录，可能导致数据丢失， 建议后续单次运维操作不能超过半数。

**Comment by wzshuang** [comment]
> 删除data目录，可能导致数据丢失， 建议后续单次运维操作不能超过半数。

请问下data目录存放的哪些数据，删除后有什么影响，有相关的文档链接参考一下吗
