### ISSUE TITLE
Nacos 2.2.3 CPU飙高 一直在grpc连接等待

### ISSUE THREAD

**Issue by huimantou** [alibaba/nacos#11982]
Nacos 2.2.3  openjdk1.8_272 达梦数据库 aaarch64
三台集群主一台机器挂掉后，主节点CPU飙高  一直在连接等待超时（过一段时间，最后一台机器也出现cpu飙高，等到超时）
![微信图片_20240419165056](https://github.com/alibaba/nacos/assets/73589906/2412039a-b039-43e7-ba38-7d3850cd530f)

**Comment by KomachiSion** [comment]
没有找到线程名叫 grpc-defaut-wo...的线程， 是否是jraft生成的grpc线程重试导致的？需要社区帮忙排查一下

**Comment by huimantou** [comment]
CPU飙高的两台机器上面，jdk快照线程文档里面，都发现这个线程，正常的nacos运行是有这个线程的，选举线程grpc重试会导致这个问题？

> 没有找到线程名叫 grpc-defaut-wo...的线程， 是否是jraft生成的grpc线程重试导致的？需要社区帮忙排查一下

**Comment by KomachiSion** [comment]
方便的话， 抓一下火焰图，看一下这个线程实际的堆栈信息

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem.

**Comment by liuziyi16** [comment]
问题是否解决了呢？同样遇到grpc-default-wo导致cpu飙高的问题了，2.3.0版本

**Comment by lunig1231** [comment]
您定位到问题了么,能不能请教一下怎么解决的呢.

**Comment by huimantou** [comment]
jdk版本缺陷



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年11月6日(周四) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] Nacos 2.2.3 CPU飙高 一直在grpc连接等待 (Issue #11982)


lunig1231 left a comment (alibaba/nacos#11982)
 
您定位到问题了么,能不能请教一下怎么解决的呢.

**Comment by nameyongyang** [comment]
> jdk版本缺陷
> […](#)
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2025年11月6日(周四) 下午3:07
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [alibaba/nacos] Nacos 2.2.3 CPU飙高 一直在grpc连接等待 (Issue [#11982](https://github.com/alibaba/nacos/issues/11982))
> 
> 
> lunig1231 left a comment ([alibaba/nacos#11982](https://github.com/alibaba/nacos/issues/11982))
> 
> 您定位到问题了么,能不能请教一下怎么解决的呢.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，请教一下你们jdk最后升级到什么版本了呢？
