### ISSUE TITLE
grpc连接持续为UNHEALTHY状态

### ISSUE THREAD

**Issue by JianweiWang** [alibaba/nacos#11984]
**Describe the bug**
直接内存发生oom error后grcp连接持续为UNHEALTHY状态。oom问题自动恢复后，连接状态无法恢复正常。

**Expected behavior**
oom问题自动恢复后，连接状态自动恢复正常。

**How to Reproduce**
持续大流量推送压测，单机流量500MB/s以上，基本可以稳定复现。

**Desktop (please complete the following information):**
 - OS: Centos
 - Version  nacos-server 2.1.2
 - Module Naming
 - SDK original

**Comment by KomachiSion** [comment]
需要从两个方向来优化这个问题：
1. 先排查为什么会oom， 是真的内存不足，还是哪里使用方式不正确导致的。
2. 如果出现oom，恢复之后没有自愈的问题是需要修复的。

可以分为两个步骤进行。
