### ISSUE TITLE
r-nacos(rust实现的nacos服务)申请贡献到nacos社区

### ISSUE THREAD

**Issue by heqingpan** [alibaba/nacos#11986]
r-nacos目前是我的人个项目，关于项目贡献到社区，之前在线下和@xuechaos 有过初步的沟通 。

现在申请把r-nacos贡献到nacos社区 ，项目贡献到社区要走什么流程？

---

r-nacos简介：

r-nacos是一个用rust实现的nacos服务。相较于java nacos来说，是一个提供相同功能，启动更快、占用系统资源更小（初始内存小于10M）、性能更高、运行更稳定的服务。

r-nacos设计上完全兼容最新版本nacos面向client sdk 的协议（包含1.x的http OpenApi，和2.x的grpc协议）, 支持使用nacos服务的应用平迁到 r-nacos。 

仓库： https://github.com/r-nacos/r-nacos

**Comment by CherishCai** [comment]
🐮👍

**Comment by KomachiSion** [comment]
Welcome！

我们需要确认一下：
1. 目前这个项目应该是您的个人项目对吧
2. 需要签署您 https://cla-assistant.io/alibaba/nacos 

都完成之后， 我们可以进行仓库的迁移工作。

**Comment by heqingpan** [comment]
第1点，目前是我的个人项目。
第2点，协议的内容看了一遍没什么问题。协议签署流程是怎样的，是支持直接在线上操作的吗？

**Comment by xuechaos** [comment]
欢迎 @heqingpan  和 r-nacos 项目 加入社区 🎉 🎉 🎉 🚀 🚀 🚀

**Comment by heqingpan** [comment]
> 欢迎 @heqingpan 和 r-nacos 项目 加入社区 🎉 🎉 🎉 🚀 🚀 🚀

很高兴可以加入社区与大家一起为社区添砖加瓦 :-)

**Comment by 985492783** [comment]
rust的nacos和java的nacos能在同一个集群共生吗，如果不能升级起来可能有点难

**Comment by heqingpan** [comment]
> rust的nacos和java的nacos能在同一个集群共生吗，如果不能升级起来可能有点难

目前基础集群协议实现不同，不支持在同一集群共生。

方案一：

如果不需要灰度，可以同时运行两个集群后，再借助nginx/haproxy这类流量网关切流，可以支持秒切。
配置中心数据可提前迁移，注册中心切换后完成注册大概在10秒内左右能全部重新注册（不能的nacos client和数量级，需要的时间有所区别）。整体这个切换所需时间很短，如果加上client的缓存，理论上基本可以做到无感。

方案二：
如果迁移想要较长时间做灰度的话，可以考虑同时运行两个集群，通过同步工具（比如nacos-sync）为两个集群做数据同步。

一般的场景方案一应该已经足够。

**Comment by KomachiSion** [comment]
> 第1点，目前是我的个人项目。 第2点，协议的内容看了一遍没什么问题。协议签署流程是怎样的，是支持直接在线上操作的吗？

https://cla-assistant.io/alibaba/nacos 这个链接点击进去，然后最下面有个sign的按钮， 签署完毕即可。

**Comment by heqingpan** [comment]
> > 第1点，目前是我的个人项目。 第2点，协议的内容看了一遍没什么问题。协议签署流程是怎样的，是支持直接在线上操作的吗？
> 
> https://cla-assistant.io/alibaba/nacos 这个链接点击进去，然后最下面有个sign的按钮， 签署完毕即可。

线上协议已签署。
后面还有什么流程吗？
是不是完成代码仓库迁移即可？

**Comment by KomachiSion** [comment]
> > > 第1点，目前是我的个人项目。 第2点，协议的内容看了一遍没什么问题。协议签署流程是怎样的，是支持直接在线上操作的吗？
> > 
> > 
> > https://cla-assistant.io/alibaba/nacos 这个链接点击进去，然后最下面有个sign的按钮， 签署完毕即可。
> 
> 线上协议已签署。 后面还有什么流程吗？ 是不是完成代码仓库迁移即可？

是的，可以开始仓库迁移了。

**Comment by heqingpan** [comment]
仓库已完成迁移： https://github.com/nacos-group/r-nacos
