### ISSUE TITLE
仅当作配置中心使用，应该配置哪几个端口的出入站规则

### ISSUE THREAD

**Issue by witt-bit** [alibaba/nacos#11987]
医院的项目，对端口的开放非常敏感，项目期望内网部署，仅作为配置中心使用，通过`spring.cloud.nacos.discovery.enabled=false`禁用了注册中心的功能，实际应该开放哪几个端口的访问

经过测试，出战规则仅开放9848端口即可

**Comment by KomachiSion** [comment]
如果只有2.X的客户端，仅需要9848， 8848是1.X客户端和控制台及http openAPI的端口。
