### ISSUE TITLE
There is also the same problem, cluster.conf does not have localhost or 127.0.0.1, three nodes, one of which always reports this error, the console can open

### ISSUE THREAD

**Issue by imkiven** [alibaba/nacos#1199]
也有同样的问题， cluster.conf 没有localhost或者127.0.0.1，三个节点，其中一个节点始终报这个错误，控制台可以打开

_Originally posted by @imkiven in https://github.com/alibaba/nacos/issues/1189#issuecomment-490723616_

**Comment by nkorange** [comment]
请在这个issue补充具体报错信息
