### ISSUE TITLE
2.2.3版本使用docker部署之后，登录进入，无法修改密码，并且访问不到用户列表和权限列表

### ISSUE THREAD

**Issue by S18336980125Y** [alibaba/nacos#12006]
2.2.3开启鉴权功能之后，无法修改用户名密码，并且无法访问用户列表
![image](https://github.com/alibaba/nacos/assets/110363201/dd1171d7-9b92-4d0c-8b7b-dfb26aa7e08c)
![image](https://github.com/alibaba/nacos/assets/110363201/471ca4c3-03f0-415b-817d-8dd6be0f28e6)
docker中查看nacos的日志也未报错，求助~！

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/f7151fe4-e28b-4674-8b9c-3de6f4adb20d)

我自己部署的2.3.2可以， 应该是你部署的环境有问题，看下响应里的具体错误是啥，或者看下是不是数据库连接有异常。

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.

**Comment by Anddio** [comment]
> ![image](https://private-user-images.githubusercontent.com/37170243/325454443-f7151fe4-e28b-4674-8b9c-3de6f4adb20d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTY4MDMsIm5iZiI6MTczMDI1NjUwMywicGF0aCI6Ii8zNzE3MDI0My8zMjU0NTQ0NDMtZjcxNTFmZTQtZTI4Yi00Njc0LThiOWMtM2RlNmY0YWRiMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAyNDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZWFiZjU2OTU3YjMwZmYxMzRhNTFlMjc5Yjc3MDExODU5M2Q3MTQyMTI3ZGQ0ZTc0YWEwYzgwMWMyM2QwZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XZhuHKMUUJ6HyxShMYVs_sCZV-fQQimEvctkdr_tP7E)
> 
> 我自己部署的2.3.2可以， 应该是你部署的环境有问题，看下响应里的具体错误是啥，或者看下是不是数据库连接有异常。

本地部署的nacos 2.4.3可以访问用户列表和权限列表；在蓝鲸7使用镜像v2.4.3部署，访问不了用户列表和权限列表

**Comment by Anddio** [comment]
@KomachiSion

**Comment by Anddio** [comment]
![image](https://github.com/user-attachments/assets/226d08ae-edb2-4e47-99cb-1e1c34b95e6d)
