### ISSUE TITLE
替换NotifyCenter#publisherMap的key的类型

### ISSUE THREAD

**Issue by kang-hl** [alibaba/nacos#12007]
key类型由String类型替换为Class类型，性能应该会有提升。

**Comment by The-Gamer-01** [comment]
我看感觉好像也可以，搜了下资料感觉也行

**Comment by KomachiSion** [comment]
NotifyCenter的性能达到瓶颈了吗？ 我记得当时重构这个东西的时候，做过新能压测， 性能已经很好，可以满足非常大量的需求了。

**Comment by KomachiSion** [comment]
No more discussion from community, This enhancement has no need for now.
