### ISSUE TITLE
Nacos cluster modifies the same service configuration file but only one service has been modified

### ISSUE THREAD

**Issue by mybug99** [alibaba/nacos#1200]
Nacos集群修改同一个服务配置文件但是只有一个服务修改了，只有一个有效，另一个服务直接恢复了我项目启动时的配置，        （这个是单独服务的时候修改会修改了一次然后再马上修改一次会无效，当修改一次后需要等一会在修改一个服务才能同步到，不然会恢复到我项目启动时默认的配置）![image](https://user-images.githubusercontent.com/43434812/57435895-263e5180-7271-11e9-8c50-54b4007e9397.png)
![image](https://user-images.githubusercontent.com/43434812/57435905-2b9b9c00-7271-11e9-92d2-09de8e08778d.png)
![image](https://user-images.githubusercontent.com/43434812/57435913-2e968c80-7271-11e9-91f1-ed59215556a9.png)

**Comment by mybug99** [comment]
两个服务名字一样的

**Comment by mybug99** [comment]
有人吗？？？？？

**Comment by mybug99** [comment]
为何没人理我！！

**Comment by paderlol** [comment]
是配置服务修改服务？请问你用的是cloud 还是直接自己引用Nacos client啊

**Comment by mybug99** [comment]
> 是配置服务修改服务？请问你用的是cloud 还是直接自己引用Nacos client啊

是的配置服务修改服务的配置文件，只有一个服务生效了其余的服务直接变成我启动时自己配置的那个内容了，是springcloud的服务，nacos的client是0.9.0

**Comment by nkorange** [comment]
请到 [Spring Cloud Alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) 提交你的问题，应该是没有配置自动刷新导致。
