### ISSUE TITLE
misspelled word

### ISSUE THREAD

**Issue by My-Summerice** [alibaba/nacos#12009]
The word "Nacso-Watch-Task-Scheduler" is misspelled here and should be "Nacos-Watch-Task-Scheduler"
![image](https://github.com/alibaba/nacos/assets/74168668/36d785a4-c35f-4144-b70e-424ceb5c5439)
com.alibaba.cloud.nacos.discovery.NacosWatch#getTaskScheduler

**Comment by cold-l** [comment]
@i will solve it@

I wanna take it. thx.
