### ISSUE TITLE
1.1.3升到1.4.7 开启权限控制后，登录成功，显示权限认证失败

### ISSUE THREAD

**Issue by maxwell-knight-zf** [alibaba/nacos#12015]
```
nacos.core.auth.enabled=true
nacos.core.auth.enable.userAgentAuthWhite=false
nacos.core.auth.server.identity.key=nacos
nacos.core.auth.server.identity.value=nacos
```
也没有权限控制菜单
![image](https://github.com/alibaba/nacos/assets/130677315/04d0542e-d9af-4da4-bfd8-325f7a76ab94)

**Comment by KomachiSion** [comment]
说明并为给对应角色和用户赋权。

**Comment by lkz-service** [comment]
这个问题怎么解决的

**Comment by maxwell-knight-zf** [comment]
页面是授权的菜单也没有显示。
对比了两个版本的数据库，发现1.1.3版本的数据库缺少permissions表。
将permissions表补上，再重启就可以了

**Comment by maxwell-knight-zf** [comment]
> 说明并为给对应角色和用户赋权。

1.1.3版本的数据库缺少permissions表
