### ISSUE TITLE
startupsh does not support environment variables specifying heap memory size settings

### ISSUE THREAD

**Issue by caoyanan666** [alibaba/nacos#12013]
For Example，I create Environment JAVA_OPT=-XX:+UseG1GC -Xms500m -Xmx500m， nacos startup.sh will ignore my setting and force use "-Xms512m -Xmx512m -Xmn256m" or "-Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m"，
I want to use a size setting that is consistent with the actual business. For example, in an environment where costs are reduced and efficiency is increased, the boss only gives 1g of memory, and high availability must be required. In this case, I need to lower the heap memory size setting.

**Comment by KomachiSion** [comment]
Nacos docker images support this feature that set memory from ENV.

If you want release package also support it, I recommend to use a ENV to save it, such as `CUSTOM_NACOS_MEMORY`, If this ENV is not exist, use current default value, otherwise use CUSTOM_NACOS_MEMORY.

**Comment by caoyanan666** [comment]
OK, I'll adjust it.
