### ISSUE TITLE
为什么mysql-schema.sql中没有“服务管理”相关的内容呢？只有“配置管理”和“用户“等相关的Table

### ISSUE THREAD

**Issue by Laine-S** [alibaba/nacos#12020]
**使用mysql作为datasource**
我正在使用mysql作为nacos的datasource，但我发现“服务管理”的内容并没有被写入到mysql中，数据库初始化文件：mysql-schema.sql中创建的Table也没有和“服务管理”相关的，仅有只有“配置管理”和“用户“等相关的table
请问这是为什么呢？是我使用的方式不对吗？“服务管理”的数据被写到了哪里呢？

**Comment by The-Gamer-01** [comment]
我的理解是
配置管理相关的配置会写入到MySQL或者Derby中，主要取决于配置；
服务管理相关的会根据AP或CP模式写入内存，比如AP直接使用ConcurrentHashMap进行服务存储，CP使用JRaft进行存储

**Comment by Laine-S** [comment]
> 我的理解是 配置管理相关的配置会写入到MySQL或者Derby中，主要取决于配置； 服务管理相关的会根据AP或CP模式写入内存，比如AP直接使用ConcurrentHashMap进行服务存储，CP使用JRaft进行存储

请问为什么服务管理相关的内容只会写入内存呢？如果nacos宕机重启，岂不是所有的服务管理信息都丢失了。这样设计的原因是什么呢？

**Comment by KomachiSion** [comment]
服务的使用形态意味着会频繁的变更（注册，注销，心跳时间维护等），且服务更多的使用场景是临时服务，因此不依赖数据库存储是更优的方案：

至于你说的宕机重启，服务信息丢失的问题，不会出现：
1. 启动时会从其他节点获取快照加载；
2. 持久化服务和元数据信息是通过raft协议同步的，会将log存储在磁盘中，磁盘中没有也会从leader中获取，所以不会丢失
3. 临时服务会从其他节点获取快照，并实时保持心跳续约，若出现心跳续约时数据不存在，会从leader中重新同步一份，同时临时服务还和客户端保持着续约关系，若服务端所有节点均没有这部分数据，客户端会重新发起一次注册。

**Comment by Laine-S** [comment]
> 服务的使用形态意味着会频繁的变更（注册，注销，心跳时间维护等），且服务更多的使用场景是临时服务，因此不依赖数据库存储是更优的方案：
> 
> 至于你说的宕机重启，服务信息丢失的问题，不会出现：
> 
> 1. 启动时会从其他节点获取快照加载；
> 2. 持久化服务和元数据信息是通过raft协议同步的，会将log存储在磁盘中，磁盘中没有也会从leader中获取，所以不会丢失
> 3. 临时服务会从其他节点获取快照，并实时保持心跳续约，若出现心跳续约时数据不存在，会从leader中重新同步一份，同时临时服务还和客户端保持着续约关系，若服务端所有节点均没有这部分数据，客户端会重新发起一次注册。

肥肠有道理！感谢感谢！
