### ISSUE TITLE
[Bug]: Nacos reports an error when using nacos-postgresql-datasource-plugin-ext: java.lang.ClassCastException

### ISSUE THREAD

**Issue by mikolls** [alibaba/nacos#12022]
**Describe the bug**
An error occurs when starting with the PostgreSQL plugin：java.lang.ClassCastException: com.sun.proxy.$Proxy114 cannot be cast to com.alibaba.nacos.plugin.datasource.mapper.Mapper

**How to Reproduce**
1. [Download the plugin and configure the PostgreSQL data source in the Nacos source code](https://nacos.io/docs/latest/plugin/datasource-plugin/)，
2. [nacos-plugin url](https://github.com/nacos-group/nacos-plugin)
3. Turn on the database log: ```nacos.plugin.datasource.log.enabled=true```
4. Start nacos
5. See errors
![image](https://github.com/alibaba/nacos/assets/41845795/70e194d2-d755-40b9-abe5-f5916d098fa2)
6. After trying, it was found that after setting```nacos.plugin.datasource.log.enabled=true```, the code will go through this part of the logic: 
![image](https://github.com/alibaba/nacos/assets/41845795/e5243c68-c819-4438-b947-3bf4cde286a3)

But in fact, the interface cannot be obtained here 

![image](https://github.com/alibaba/nacos/assets/41845795/585ee41b-7966-4c40-8c0d-26e7f7451ebb)

You can see that ConfigInfoMapperByPostgresql does not implement any interface 

![image](https://github.com/alibaba/nacos/assets/41845795/e68345f3-1fb6-4ffc-ba7e-37b818499f91)

The one that implements the interface is ConfigInfoMapperByMySql 

![image](https://github.com/alibaba/nacos/assets/41845795/1ab54659-bbc3-43b8-bb09-efb0b5fffad7)
![image](https://github.com/alibaba/nacos/assets/41845795/a3f0c2b5-fece-45dd-82ea-72524f607b67)
![image](https://github.com/alibaba/nacos/assets/41845795/38fc6086-a9a2-4457-bedd-bd76a981bb47)
7. Therefore, only when using the database plugin and setting```nacos.plugin.datasource.log.enabled=true```will an error occur, whereas Nacos’ built-in MySQL and Derby do not have this error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version nacos2.3.2 or nacos2.4.0
 - Module naming-config

**Additional context**
Complete stack information
[log.txt](https://github.com/alibaba/nacos/files/15096866/log.txt)

**Comment by mikolls** [comment]
If it needs to be fixed, please assign it to me

**Comment by KomachiSion** [comment]
I remember this problem has been fixed in new version. Can you try new version?
