### ISSUE TITLE
nacos2.0版本如何清除本地客户端的缓存

### ISSUE THREAD

**Issue by YshGitHubfcasd** [alibaba/nacos#12023]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]ed to happen.

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors
 is.

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]ed to happen.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Additional context**

**Comment by KomachiSion** [comment]
缓存默认存放在${user.home}/nacos 目录下， 直接移除该目录即可。

**Comment by YshGitHubfcasd** [comment]
在windows下没有看到这个目录，
![image](https://github.com/alibaba/nacos/assets/131887501/eec15db5-cad6-4b11-ad90-57161de40ba1)
我将data删除了还是读以前的配置，真是难办

**Comment by 985492783** [comment]
window一般在C盘\用户\username\nacos下，linux在/nacos里面

**Comment by KomachiSion** [comment]
服务端没有缓存，你需要删除客户端的缓存。

**Comment by KomachiSion** [comment]
而且最骚的是你明明问题是如何删除客户端缓存， 然后去删除的是服务端的数据，我也是服了

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.

**Comment by YshGitHubfcasd** [comment]
在windows下没有找到客户端nacos目录（全局搜索都没有），这个nacos客户端缓存配置是写在哪呀，我以为是那个data文件，后面我删除重新配置（服务端），果然还是读以前的，但客户端缓存着实没找到在哪清除，我就算重新安装naocs还是读以前
