### ISSUE TITLE
使用nacosClientApi来完成更新某个dataId下面的配置，接口显示调用成功，但是nacos里面的内容却没有更新，nacos-client的版本是1.4.6

### ISSUE THREAD

**Issue by atguiguwy** [alibaba/nacos#12032]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by atguiguwy** [comment]
这个是之前封装好的，突然出现了这个bug

**Comment by KomachiSion** [comment]
我自己测试没有复现， 请确认命名空间，group，dataId传入正确，或自行排查可能的问题。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem.
