### ISSUE TITLE
different field between instance/list and instance

### ISSUE THREAD

**Issue by qingyu31** [alibaba/nacos#1203]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
we can get an instance detail from *GET /nacos/v1/ns/instance* or field named hosts  from */nacos/v1/ns/instance/list*

- /nacos/v1/ns/instance defines an instance as
```json
{
	"metadata": {},
	"instanceId": "10.10.10.10-8888-DEFAULT-nacos.test.2",
	"port": 8888,
	"service": "nacos.test.2",
	"healthy": false,
	"ip": "10.10.10.10",
	"clusterName": "DEFAULT",
	"weight": 1.0
}
```

-/nacos/v1/ns/instance/list defines an instance as
```json
{
		"valid": true,
		"marked": false,
		"instanceId": "10.10.10.10-8888-DEFAULT-nacos.test.1",
		"port": 8888,
		"ip": "10.10.10.10",
		"weight": 1.0,
		"metadata": {}
	}
```
*I'm confused with field named "valid","marked","healthy" and somewhere "enable"*
### Describe what you expected to happen
the same instance in different api should have same scheme I think.
and there are no any explain for response of openapi what I indeed need.

### How to reproduce it (as minimally and precisely as possible)
from openapi document.
https://nacos.io/en-us/docs/open-API.html

### Tell us your environment
openapi doc

### Anything else we need to know

**Comment by nkorange** [comment]
@qingyu31 Thank you for your advice, we will unify the results and supplement the document soon.

**Comment by qingyu31** [comment]
> @qingyu31 Thank you for your advice, we will unify the results and supplement the document soon.

I'm working on nacos sdk in golang. I wanna to know does `valid` equal `healthy`  or `valid` equal `enable`. I'm still confused after reading nacos in java.

**Comment by nkorange** [comment]
> > @qingyu31 Thank you for your advice, we will unify the results and supplement the document soon.
> 
> I'm working on nacos sdk in golang. I wanna to know does `valid` equal `healthy` or `valid` equal `enable`. I'm still confused after reading nacos in java.

'valid' is identical to 'healthy'.
