### ISSUE TITLE
通过界面设置weigh，重新上线的服务如果IP不变，权重还是0

### ISSUE THREAD

**Issue by yoboygo** [alibaba/nacos#12033]
我在后台界面上设置了一个服务的权重为0，然后重启了服务，添加了参数：spring.cloud.nacos.discovery.weight=1，新上线的服务权重还是0。测试发现只有服务停机大概1分钟左右，新上线的服务权重才会按照参数注册。
请问关于这个机制有没有详细的说明？如果我想实现服务的权重按照client端的启动参数注册，覆盖nacos server端的配置，需要做那些配置？谢谢！

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/guide/user/open-api/#2.3

> 通过该接口更新的元数据拥有更高的优先级，且具有记忆能力；会在对应实例删除后，依旧存在一段时间，如果在此期间实例重新注册，该元数据依旧生效；您可以通过nacos.naming.clean.expired-metadata.expired-time及nacos.naming.clean.expired-metadata.interval对记忆时间进行修改
