### ISSUE TITLE
nacos源码方式启动，设置单机模式无效

### ISSUE THREAD

**Issue by zhl19911203** [alibaba/nacos#12034]
我下载的2.3.2的tag，然后Nacos启动类添加环境变量MODE=standalone无效
添加vm启动参数-Dnacos.standalone=true这个可以生效

<img width="1623" alt="image" src="https://github.com/alibaba/nacos/assets/36956485/a50c3370-e7f4-46b4-a2df-3450313367ee">

**Comment by KomachiSion** [comment]
·MODE=standalone· 这个参数是nacos docker镜像使用的， 本地源码启动不生效
