### ISSUE TITLE
Windows server 2012 R2在cmd用单例模式启动nacos2.3.2报错EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=，java环境1.8,64位，之前的1.4.1的版本是可以正常启动，请问怎么解决

### ISSUE THREAD

**Issue by mazhm** [alibaba/nacos#12049]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
信息过少，无法判断问题，可以尝试多安装一些必要的VC++运行库后重试。

**Comment by mazhm** [comment]
感谢回复，nacos版本降到2.3.0运行正常了，偶尔会出现上面所提到错误，删掉已运行nacos，重新解压新的nacos文件又恢复正常

**Comment by KomachiSion** [comment]
我的理解2.3.0和2.3.2没有大的改动，都是fix java层面的代码， 所以信息太少了，没法判断问题到底出在哪。

**Comment by KomachiSion** [comment]
而且删除文件重新部署就可以，说明代码层面没有问题，感觉更像是环境触发的随机问题。

**Comment by mazhm** [comment]
nacos2.3.2版本启动必定会报错，2.3.0版本是第一次启动正常，后面再启动就有可能报错。并且都是相同版本的Windows server系统，只有两三台有这样的问题，其他都没问题。也没办法去查系统是否缺少某些必要的系统文件

**Comment by KomachiSion** [comment]
这些报错内容都是jvm或系统层面的报错， 不是java代码的报错，社区没太好的办法帮助你。

jvm层面报错要么是jdk版本和os系统不兼容，要么是os系统本身有bug，只能说更换jdk版本或者拉平os层面的区别，甚至是硬件层面的区别。

除了jdk，还有可能是rocksdb和os或硬件不兼容导致的，这个就只能等待rocksdb的修复或者更新了。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by songyifei** [comment]
I finally found a way to solve this problem, just delete the "C:\Users\songyifei\nacos\data" directory, and the new run is back to normal
