### ISSUE TITLE
nacos如何适配OceanBase

### ISSUE THREAD

**Issue by HY-love-sleep** [alibaba/nacos#12042]
貌似nacos官方不支持OceanBase作为数据源？ 如何适配oceanbase数据库呢？ 求大佬指导下方向

**Comment by KomachiSion** [comment]
OceanBase 支持MySQL协议，可以使用mysql jdbc直连， 直接将地址修改为OceanBase的地址即可。

**Comment by j2ee-haydon** [comment]
用docker最新版本安装的nacos，oceanbase数据库，配置的mysql模式直连，怎么也启动不了，就是初始化不了数据源，，这个还需要些什么特殊配置吗？？
 - SPRING_DATASOURCE_PLATFORM=mysql
  - MYSQL_SERVICE_HOST=192.168.0.190
  - MYSQL_MASTER_SERVICE_PORT=2883
  - MYSQL_SERVICE_USER=root
  - MYSQL_SERVICE_PASSWORD=root
  - MYSQL_SERVICE_DB_NAME=nacos_docker
