### ISSUE TITLE
为什么发布配置会失败

### ISSUE THREAD

**Issue by triggergun** [alibaba/nacos#12057]
try {
    // 初始化配置服务，控制台通过示例代码自动获取下面参数
  String serverAddr = "{serverAddr}";
  String dataId = "{dataId}";
  String group = "{group}";
  Properties properties = new Properties();
  properties.put("serverAddr", serverAddr);
    ConfigService configService = NacosFactory.createConfigService(properties);
  boolean isPublishOk = configService.publishConfig(dataId, group, "content");
  System.out.println(isPublishOk);
} catch (NacosException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}

这个案例为什么发布失败。文档也没有具体描述。

**Comment by KomachiSion** [comment]
请给出发布失败的报错信息， 以及${user.home}/logs/nacos 日志中的相关信息

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge problem.
