### ISSUE TITLE
edas deployment, registration center report 400

### ISSUE THREAD

**Issue by mrjiangyan** [alibaba/nacos#1206]
## Issue Description
bug report

### Describe what happened (or what feature you want)
edas 部署服务的时候一直提示如下的错误:

当查询某个服务名找不到服务节点的时候，不要返回 400 了，直接提示没有服务节点就好

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
@mrjiangyan 请贴出具体错误信息
