### ISSUE TITLE
使用内置数据库的集群模式启动3节点Nacos，批量删除配置，会导致ConfigCacheService下的CACHE不更新

### ISSUE THREAD

**Issue by ZrBac** [alibaba/nacos#12062]
**Describe the bug**
使用内置数据库的集群模式启动3节点Nacos，批量删除配置，会导致ConfigCacheService下的CACHE不更新，只删除了底层数据，不会发布事件处理缓存
![image](https://github.com/alibaba/nacos/assets/33156501/4b2c0f43-b77e-45d9-89ae-4a19fed34755)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by chuntaojun** [comment]
这个集群 + raft 的配置中心模式，为了提升整体的 tps，不需要走水平发布通知了，因为 raft 本身的舒服同步就包括了这一步走，因此这个 ConfigCacheService 本身的逻辑转移到了 raft 状态机当中去了

**Comment by ZrBac** [comment]
> 这个集群 + raft 的配置中心模式，为了提升整体的 tps，不需要走水平发布通知了，因为 raft 本身的舒服同步就包括了这一步走，因此这个 ConfigCacheService 本身的逻辑转移到了 raft 状态机当中去了

实验过，k8s部署三个pod，使用内置数据库，通过批量删除接口删除配置，服务还能通过缓存读到已删除的配置信息，但是通过接口已经查不到了

**Comment by ZrBac** [comment]
> EmbeddedConfigDumpApplyHook 这里针对批量删除的场景有bug， ![image](https://private-user-images.githubusercontent.com/20452676/329532519-391c3e91-41ed-4560-8d52-0ad2e2763b47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTA3OTEsIm5iZiI6MTcxNTM5MDQ5MSwicGF0aCI6Ii8yMDQ1MjY3Ni8zMjk1MzI1MTktMzkxYzNlOTEtNDFlZC00NTYwLThkNTItMGFkMmUyNzYzYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAxMjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NmNjNWQ2YjllNzY3MTQ5YmUxMzRiNDJmZDAzZDg0MGZkZWIyM2M4MmFiMDI1OTYzMTVkOTQ3MzlkOTI3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtJStxaoGPGM6kmJmxp9BRjXJHAiVVEFiWuDh14FhOk)
> 
> @ZrBac 你本地测试下，把这个问题修复掉是不是就好了，如果可以的话，提交个PR

ok，我试试

**Comment by ZrBac** [comment]
已验证，根因为该问题导致

**Comment by shiyiyue1102** [comment]
> > EmbeddedConfigDumpApplyHook 这里针对批量删除的场景有bug， ![image](https://private-user-images.githubusercontent.com/20452676/329532519-391c3e91-41ed-4560-8d52-0ad2e2763b47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTA3OTEsIm5iZiI6MTcxNTM5MDQ5MSwicGF0aCI6Ii8yMDQ1MjY3Ni8zMjk1MzI1MTktMzkxYzNlOTEtNDFlZC00NTYwLThkNTItMGFkMmUyNzYzYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAxMjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NmNjNWQ2YjllNzY3MTQ5YmUxMzRiNDJmZDAzZDg0MGZkZWIyM2M4MmFiMDI1OTYzMTVkOTQ3MzlkOTI3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtJStxaoGPGM6kmJmxp9BRjXJHAiVVEFiWuDh14FhOk)
> > @ZrBac 你本地测试下，把这个问题修复掉是不是就好了，如果可以的话，提交个PR
> 
> 已验证，确实为该bug导致

ok，你是否可以提交一个pr修复下呢

**Comment by ZrBac** [comment]
> > > EmbeddedConfigDumpApplyHook 这里针对批量删除的场景有bug， ![image](https://private-user-images.githubusercontent.com/20452676/329532519-391c3e91-41ed-4560-8d52-0ad2e2763b47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTA3OTEsIm5iZiI6MTcxNTM5MDQ5MSwicGF0aCI6Ii8yMDQ1MjY3Ni8zMjk1MzI1MTktMzkxYzNlOTEtNDFlZC00NTYwLThkNTItMGFkMmUyNzYzYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAxMjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NmNjNWQ2YjllNzY3MTQ5YmUxMzRiNDJmZDAzZDg0MGZkZWIyM2M4MmFiMDI1OTYzMTVkOTQ3MzlkOTI3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtJStxaoGPGM6kmJmxp9BRjXJHAiVVEFiWuDh14FhOk)
> > > @ZrBac 你本地测试下，把这个问题修复掉是不是就好了，如果可以的话，提交个PR
> > 
> > 
> > 已验证，确实为该bug导致
> 
> ok，你是否可以提交一个pr修复下呢

已经提交了

**Comment by shiyiyue1102** [comment]
> > > > EmbeddedConfigDumpApplyHook 这里针对批量删除的场景有bug， ![image](https://private-user-images.githubusercontent.com/20452676/329532519-391c3e91-41ed-4560-8d52-0ad2e2763b47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTA3OTEsIm5iZiI6MTcxNTM5MDQ5MSwicGF0aCI6Ii8yMDQ1MjY3Ni8zMjk1MzI1MTktMzkxYzNlOTEtNDFlZC00NTYwLThkNTItMGFkMmUyNzYzYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDAxMjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NmNjNWQ2YjllNzY3MTQ5YmUxMzRiNDJmZDAzZDg0MGZkZWIyM2M4MmFiMDI1OTYzMTVkOTQ3MzlkOTI3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtJStxaoGPGM6kmJmxp9BRjXJHAiVVEFiWuDh14FhOk)
> > > > @ZrBac 你本地测试下，把这个问题修复掉是不是就好了，如果可以的话，提交个PR
> > > 
> > > 
> > > 已验证，确实为该bug导致
> > 
> > 
> > ok，你是否可以提交一个pr修复下呢
> 
> 已经提交了

好的，那这个issue就关了
