### ISSUE TITLE
Nacos registered rpc service ip address is incorrect

### ISSUE THREAD

**Issue by love-somnus** [alibaba/nacos#1207]
nacos版本为0.9.0部署在香港阿里云，以dubbo的形式注册的rpc服务，虽然注册成功，但最后在nacos控制台服务列表中看到的ip，既不是局域网ip，也不是自身公网ip，经查询是美国的ip，也不知道从那里冒出获取到的。

![QQ图片20190510175040](https://user-images.githubusercontent.com/9479032/57518792-763e1680-734c-11e9-93de-a7be8a2f93e1.png)

**Comment by nkorange** [comment]
这个IP是dubbo客户端读取的，请把这个问题汇报给dubbo
