### ISSUE TITLE
Unraveling Nacos Cluster Anomalies???

### ISSUE THREAD

**Issue by Kiki513H** [alibaba/nacos#12075]
I deployed a Nacos cluster. The environment consists of machines A, B, and C. There are a total of 10 services deployed. After the services start, both Nacos instances on machines A and B have all 10 services registered. Initially, when the services start on machine C, all 10 services are also registered. However, after 1 minute, while machines A and B still have all 10 services, machine C loses several services.

**Comment by KomachiSion** [comment]
Please  make sure your cluster deploy without error, such as cluster.conf file same and no more invalid nodes. Then make sure the network between nacos server nodes are work well, include 8848,7848,9849 ports.

What's more, you said you deploy in A and B env is work well, but in C env has problem, Might there are some differernt in env C other than nacos' problem.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by Kiki513H** [comment]
> No more response from author for a long time, and this problem seems env problem.
I apologize for not responding for so long, please understand. The environments of C and B are identical; A is a Linux machine, and B and C are also Linux machines. I discovered something very strange: when A starts up, it registers an additional Cluster that originally does not belong to this cluster. Details are as follows:
![image](https://github.com/alibaba/nacos/assets/130541435/97052607-0f97-4d15-a209-1d2df86943b0)

**Comment by Kiki513H** [comment]
> No more response from author for a long time, and this problem seems env problem.

I found that 8848 registers itself regardless of the machine it is on.
