### ISSUE TITLE
springboot2.7.0启动单元测试报错403,user not found

### ISSUE THREAD

**Issue by LifetimeTender** [alibaba/nacos#12078]
中文:
版本: springboot2.7.0, nacos2.2.0, nacos客户端2.3.2
在不更改任何代码, 配置的情况下, spring应用可以正常启动, 但是启动单元测试报错:ErrCode:403, ErrMsg:http error, code=403,msg=user not found!,dataId=xxx,group=xxx,tenant=xxx

English:
version: springboot2.7.0, nacos2.2.0, nacos client2.3.2
The spring application starts normally without changing any code or configuration, but the unit test starts with an error:ErrCode:403, ErrMsg:http error, code=403,msg=user not found!,dataId=xxx,group=xxx,tenant=xxx

**Comment by KomachiSion** [comment]
大概率是你单元测试时读取的配置文件没有设置用户密码，而你直接启动时读取的配置文件或者jvm参数中有用户密码。

**Comment by KomachiSion** [comment]
这种只能自行排查一下，为什么spring为什么没有读取到密码，或者看下是不是漏了配置。

**Comment by LifetimeTender** [comment]
> 大概率是你单元测试时读取的配置文件没有设置用户密码，而你直接启动时读取的配置文件或者jvm参数中有用户密码。

设置了的,不设置的话启动项目都有问题的

**Comment by LifetimeTender** [comment]
> 大概率是你单元测试时读取的配置文件没有设置用户密码，而你直接启动时读取的配置文件或者jvm参数中有用户密码。

最后排查出来的问题是nacos客户端版本不匹配,nacos客户端降级到2.2.0就OK了.但是很奇怪的一个点,既然nacos客户端不匹配那么为什么正常启动项目就没问题

**Comment by KomachiSion** [comment]
1. 我测试2.3.2客户端和2.2.0服务端是可以正常登录请求的， 应该还是配置哪里不正确，只是刚好你降级版本的时候修复掉了。
2. 项目能启动，能正常获取配置和服务，说明你的服务端没有开启鉴权，不需要输入用户密码

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
