### ISSUE TITLE
服务注册后立即获取服务列表，结果为空。

### ISSUE THREAD

**Issue by lfygh** [alibaba/nacos#12087]
背景描述:
nacos单机模式启动，在使用Nacos作为注册中心融合SpringCloud时，应用启动后进行服务自动注册，服务注册后，调用nacos的rest api获取服务列表，结果为空。延迟几秒后再获取，就有结果了。请问可能是什么原因？是有什么策略吗？

调用nacos的rest api(`/nacos/v2/ns/instance/list`)获取服务列表的时机是监听到 InstanceRegisteredEvent 事件。监听ApplicationReadyEvent事件同样也获取不到结果。

'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2022.0.0.0'

**Comment by Daydreamer-ia** [comment]
`nacos` 服务注册操作是异步的，所以没办法马上获取。如果希望在注册后进行回调，建议用订阅接口

**Comment by lfygh** [comment]
> `nacos` 服务注册操作是异步的，所以没办法马上获取。如果希望在注册后进行回调，建议用订阅接口

好的，谢谢
