### ISSUE TITLE
同一台机器多个服务获取不同 namespace 下的配置会错乱

### ISSUE THREAD

**Issue by wanghaida** [alibaba/nacos#12085]
环境：

- nacos 2.3.2

假设同一台机器：

- 有 aaa 服务，连接 nacos，获取 namespace 为 `prod` 的 `base` 配置，配置内容为 `aaa123`。
- 有 bbb 服务，连接 nacos，获取 namespace 为 `test` 的 `base` 配置，配置内容为 `bbb456`。

有如下结果：

1. 如果先启动 aaa 服务，那么获取到的配置为 `aaa123`，再启动 bbb 服务，获取到的配置也为 `aaa123`。
2. 停止 aaa 服务，bbb 服务的 `subscribe` 收到变化，内容为 `bbb456`。
3. 再启动 aaa 服务，获取到的配置为 `bbb456`。

颠倒 aaa 和 bbb 的启动顺序同理。测试了二进制启动方式和 Docker 启动方式，均有如上的问题。

**Comment by KomachiSion** [comment]
我自己拿nacos-client测试，不存在这样的问题， 请首先排查应用启动的配置文件、环境变量和jvm参数等，确认同一个机器的两个服务没有共享同一个本地配置导致读取的命名空间错误。

同时可以从nacos-client的log中看到底获取配置时获取了哪个命名空间。

再次也可以使用nacos-example模块中的样例，使用纯粹的nacos-client测试，以此来确定是您应用本身存在读取命名空间配置的问题。

**Comment by wanghaida** [comment]
node 包 nacos 的问题，获取的是缓存，我提错仓库了。
