### ISSUE TITLE
How Download files from the service when start run project and Load file at startup?

### ISSUE THREAD

**Issue by pussyboots** [alibaba/nacos#1208]
Whether nacos can download all configuration files in the environment to the local as the Disconf starts, so that the service can hang to read the local file configuration.
If so, which path the file will be downloaded to.

I hope that when the project starts, download the file from the configuration center to the local, then read the SQL configuration of the file, Redis configuration and so on.

springboot2.x project

```
<dependency>
	<groupId>com.alibaba.boot</groupId>
	<artifactId>nacos-config-spring-boot-starter</artifactId>
	<version>0.2.1</version>
</dependency>
```

How to use the annotation ``` @NacosProperty  ``` and  ```  @NacosPropertySources ```

Thanks.

**Comment by nkorange** [comment]
Is it something like confd? Refer to #1237
