### ISSUE TITLE
每次出现 NacosClientAuthServiceImpl， 然后服务就卡住了，一定要重启才能恢复正常

### ISSUE THREAD

**Issue by daishuhua** [alibaba/nacos#12080]
**Describe the bug**
"The service will only get stuck if the message '[ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success' appears after it has started."

**Expected behavior**
 it will continue to provide service.

**Actually behavior**
Actually, I didn't do anything

**How to Reproduce**
This issue will occur every two or three days.

**Desktop (please complete the following information):**
 - OS: Centos
 - Version: nacos-server 2.0.2
 - Module: naming/config
 - SDK: spring-cloud-alibaba-nacos
- JDK:  openjdk version "1.8.0_292" x64

**Comment by KomachiSion** [comment]
you should check why your app stuck, nacos-client load plugin will not stuck your application.

you see "The service will only get stuck if the message '[ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success' appears after it has started." Only means nacos load nacos auth plugin success, but not means it make your app stuck.

you should use jstack to find out the main thread do what when your app stuck.
