### ISSUE TITLE
Nacos 内置 Spring Boot2 升级 Spring Boot3

### ISSUE THREAD

**Issue by cnrainbing** [alibaba/nacos#12089]
1. Nacos 内置Spring Boot 版本 2.17.x 能否升级为 3.2.x 版本
2. spring-boot-admin 版本2.7.x 能否升级为 3.2.x 版本

**Comment by huangkemingyyds** [comment]
我记得没错的话，开源之夏应该在做了

**Comment by KomachiSion** [comment]
#12028
