### ISSUE TITLE
springboot服务不定时下线，与nacos断开连接，在下线时close_wait连接突然增多，平时没有

### ISSUE THREAD

**Issue by hzx7787** [alibaba/nacos#12098]
![7acb06c50b8aac976047a26da5ac250](https://github.com/alibaba/nacos/assets/15191774/e568eb18-2999-48d4-96ef-8bd28153da1b)
![aa6c6b39862b52d403698cfc21b2dc1](https://github.com/alibaba/nacos/assets/15191774/bbb12510-9870-4470-aa3c-f81c7adf173e)

**Comment by KomachiSion** [comment]
invalid host or port
请自查域名解析服务。

如果使用了代理，请检查代理协议是否支持tcp协议。
