### ISSUE TITLE
单机Nacos2.3.2修改密码提示信息

### ISSUE THREAD

**Issue by liuyuchuan** [alibaba/nacos#12093]
**Is your feature request related to a problem? Please describe.**
单机部署Nacos 2.3.2 修改默认帐号密码，提示信息只有图标，没有文字提示，不友好。
<img width="299" alt="83d59bba-0792-417a-9396-8de2d387994d" src="https://github.com/alibaba/nacos/assets/12453224/dcb98d4f-aa97-48f4-ad2e-93f3ca66bbf1">

**Describe the solution you'd like**
图标提示的同时，提供友好的文字提示

**Describe alternatives you've considered**
「修改成功」或「更新成功」

**Additional context**
<img width="341" alt="image" src="https://github.com/alibaba/nacos/assets/12453224/a4bc4541-b80f-4621-9644-7e7da97b1d74">

**Comment by psxjoy** [comment]
The issues with `Edit passwords`, `Create user`, and `Delete user` in standalone mode are all the same. I see this as a great opportunity to contribute to the Nacos open-source project. If no one else has claimed it, feel free to assign it to me.@KomachiSion

**Comment by wzshuang** [comment]
@i will solve it@
