### ISSUE TITLE
【OpenApi】How to listen the config change based on the 2.x  version nacos?【Implementing a v2.x nacos python sdk】

### ISSUE THREAD

**Issue by KunxiSun** [alibaba/nacos#12094]
**Describe the bug**

I am working on a nacos 2.x python sdk. Based on the [OpenAPI V2.x document ](https://nacos.io/docs/v2/guide/user/open-api/#1.1), I cannot find any records related to the config listener.

Only the following Apis are found
[Get Setting](https://nacos.io/docs/v2/guide/user/open-api/#1.1)
[Create Setting](https://nacos.io/docs/v2/guide/user/open-api/#1.2)
[Delete Setting](https://nacos.io/docs/v2/guide/user/open-api/#1.3)
[Get the history setting list](https://nacos.io/docs/v2/guide/user/open-api/#1.4)
[Get a specific version setting](https://nacos.io/docs/v2/guide/user/open-api/#1.5)
[Get the last version setting](https://nacos.io/docs/v2/guide/user/open-api/#1.6)
[Get all setting of a namespace](https://nacos.io/docs/v2/guide/user/open-api/#1.7)

**Expected behavior**
To support other language like python, can use nacos to register service, the v2 document should have api to listen the config change.

**Actually behavior**
I tried the v1 path, it can have response.
path: /nacos/v1/cs/configs/listener 
response: data_id%02group_name%02name_space%01

**How to Reproduce**
1. Go to [nacos v2.x Open api](https://nacos.io/docs/v2/guide/user/open-api/#%E9%85%8D%E7%BD%AE%E7%AE%A1%E7%90%86)

**Comment by Daydreamer-ia** [comment]
The `2.x` channel is implemented by grpc which is different from `1.x`, not just simple http. May be you need to get some info about grpc and do some research for how to design grpc channel from other language nacos-sdk. By the way, the nacos-python-sdk supports `1.x` config change listening supported by long polling.

```python
import nacos
SERVER_ADDRESSES = "server addresses split by comma"
NAMESPACE = "namespace id"

client = nacos.NacosClient(SERVER_ADDRESSES, namespace=NAMESPACE)
data_id = "config.nacos"
group = "group"


def listen(args):
   print(args)


client.add_config_watcher(data_id, group, listen)
```

**Comment by KunxiSun** [comment]
@Daydreamer-ia 
Thanks for your respons.

As you mentioned, nacos 2.x support grpc. I think it is a nice change from v1.x to v2.x, and I do know something about grpc(not too much).

As far as I know, the grpc requires a proto file to auto generate code for different language, where can I found the proto file of nacos?

**Comment by KunxiSun** [comment]
@Daydreamer-ia 

By the way, does the method to send heartbeat in nacos 2.x changed? The [OpenAPI V2.x document ](https://nacos.io/docs/v2/guide/user/open-api/#1.1) does not have any hints about how to send heartbeat.

However, I tried `/nacos/v2/ns/instance/beat` to send heartbeat, and it works, even though it is not mentioned in the documentation.
