### ISSUE TITLE
nacos加载yml配置文件中的信息时机太早,出现某些包还没有处理完yml配置,nacos无法获取正确的配置

### ISSUE THREAD

**Issue by aiYunS-love** [alibaba/nacos#12101]
例子:
        我对yml中的所有ip地址进行了加密操作,springboot启动加载时,应当加载解密之后的信息,但是nacos很早就要加载nacos服务的地址,导致获取的是加密的ip,无法连接nacos服务.redis,rabbitmq等软件都是正常加载的,请提高通用型 兼容性
![WX20240515-144734@2x](https://github.com/alibaba/nacos/assets/58358565/bbcb7613-de79-41da-b3f7-aab1a41362b3)

**Comment by KomachiSion** [comment]
和nacos无关， bean的加载顺序是应用程序和spring控制的， 如果需要使用解密starter，请自行确保解密starter在配置加载之后执行。

**Comment by KomachiSion** [comment]
或者有什么方案可以提供，以无侵入的方式确保能够保证解密

**Comment by KomachiSion** [comment]
那可以帮助社区排查一下问题，以更好的兼容这个场景。

一般来说，配置的加载肯定要早于其他的starter，比如redis等，否则redis之类的starter已经完成初始化配置的时候， 配置还没有从nacos中读取，那肯定是有问题的。

**Comment by KomachiSion** [comment]
issue先关闭了， 如果有结果可以重新提交一个issue说明问题原因，如果能带有修复方案，或者直接向nacos-spring-boot repo提交PR就更好了。
