### ISSUE TITLE
nacos集群某个节点每间隔1天左右宕机，问题持续近3天了，麻烦大佬们给个排查思路，感谢！！！

### ISSUE THREAD

**Issue by Kl0513** [alibaba/nacos#12108]
nacos版本：2.1.0
集群节点数：4个
服务器配置（aws-ec2）：8核16G
JVM参数：-Xms4g -Xmx4g -XX:+UseG1GC，其他参数默认
问题补充：nacos宕机时，服务器CPU/内存/磁盘都是健康状态，nacos日志也未找到对应error信息，重启后服务又正常

![image](https://github.com/alibaba/nacos/assets/35092648/9e6c7fb8-4207-41e0-8234-7fe3f0637123)
![image](https://github.com/alibaba/nacos/assets/35092648/2d6a6305-f700-48bf-a0b5-56920cba381c)
![image](https://github.com/alibaba/nacos/assets/35092648/d1681d39-839a-4509-8fd2-fb86638104b0)
![image](https://github.com/alibaba/nacos/assets/35092648/9c1762e8-95e0-496e-b872-533e510957a3)

**Comment by bwangll** [comment]
看一下/var/log/message日志？是不是内核kill的

**Comment by Kl0513** [comment]
> 看一下/var/log/message日志？是不是内核kill的

![img_v3_02av_990b752e-cb86-4832-8fc8-8670cb67228h](https://github.com/alibaba/nacos/assets/35092648/7a5eb73c-4e2a-4c01-bfac-3a83b284a3b1)
查询到关于nacos的就这些日志

**Comment by Kl0513** [comment]
> 看一下/var/log/message日志？是不是内核kill的

在该目录下看了宕机当天日志，没有相关异常，都是一些如下信息：
![image](https://github.com/alibaba/nacos/assets/35092648/ed99baf4-9d62-4517-9b67-db05b9751e3c)

**Comment by KomachiSion** [comment]
nacos只会在磁盘满的时候自杀， 其他任何情况下都不会自行宕机（至少进程会存在）。

如果出现了机器整体宕机，或者进程消失， 那么应该是操作系统（或者k8s）执行的kill。

如果通过/var/log/message等系统相关日志以及k8s状态排查未果， 可以考虑更换一下机器后重试。

**Comment by Kl0513** [comment]
> nacos只会在磁盘满的时候自杀， 其他任何情况下都不会自行宕机（至少进程会存在）。
> 
> 如果出现了机器整体宕机，或者进程消失， 那么应该是操作系统（或者k8s）执行的kill。
> 
> 如果通过/var/log/message等系统相关日志以及k8s状态排查未果， 可以考虑更换一下机器后重试。

1.nacos部署方式是采用jar
2.磁盘目前使用率50%多点：
![image](https://github.com/alibaba/nacos/assets/35092648/5495b18d-a238-49ef-a4c9-0a86fc215c47)
3. 日志/var/log/message有排查过，宕机时间段没有异常日志

**Comment by KomachiSion** [comment]
那估计还是系统环境本身的问题，或者机器故障了，建议换一台机器试一下。

**Comment by Kl0513** [comment]
> 那估计还是系统环境本身的问题，或者机器故障了，建议换一台机器试一下。

nacos宕机时间段，config-fatal.log出现如下日志，有没有可能是mysql导致的啊？ 
![image](https://github.com/alibaba/nacos/assets/35092648/9247ee5d-a18b-4e1c-8c7d-212bef69cf85)

**Comment by KomachiSion** [comment]
这个是正常的， 及时mysql有问题，nacos也不会宕机。
怀疑是机器故障了，建议换一个机器试试。

**Comment by Kl0513** [comment]
> 这个是正常的， 及时mysql有问题，nacos也不会宕机。 怀疑是机器故障了，建议换一个机器试试。

关于机器故障的问题专门找aws的工程师看了，经过验证没有问题；而且该相同类型EC2实例，我们买了有近20台，不同实例上部署很多springcloud微服务全家桶、nacos、seata等服务，但就是nacos会自己宕机，所以机器有故障可能性很低。
其次，通过Grafana+Prometheus与nacos openAPI观测，怀疑可能是集群负载不均导致某个节点负载过大引发宕机，理由如下：
1.springcloud集成是通过ip直连方式（未使用SLB模式）：spring.cloud.nacos.discovery.server-addr: ip1:8848,ip2:8848,ip3:8848,ip4:8848(共4个节点)，很容易导致客户端与服务端长链接集中于某一个nacos节点
2.当某1个nacos节点宕机时 长链接断开，与该宕机节点原有链接客户端会与剩余3个节点建立长链接；最终导致宕机节点重启后负载为0
3.promethuse监控截图：
![image](https://github.com/alibaba/nacos/assets/35092648/8cf1583c-1a5f-4c33-81b3-4b531fcb831e)
![image](https://github.com/alibaba/nacos/assets/35092648/6dd0c09a-8858-4bcb-a195-e91608092085)
4.获取集群链接负载信息：curl -X GET http://ip:8848/nacos/v2/core/loader/current/cluster
![image](https://github.com/alibaba/nacos/assets/35092648/76230446-57dc-498f-a15b-7ad6d74c4dc6)

**Comment by KomachiSion** [comment]
怎么看都像是这台机器有问题。。 连接根本就打不进去吧。

**Comment by Kl0513** [comment]
> 怎么看都像是这台机器有问题。。 连接根本就打不进去吧。

应该是nacos节点宕机后，客户端与集群其他节点建立了长连接，导致该宕机节点客户端连接数为0；通过OpenAPI接口/nacos/v2/core/loader/current/reloadCurrent手动调节集群负载后，可以观察到该宕机节点是有客户端连接的

**Comment by Kl0513** [comment]
> 怎么看都像是这台机器有问题。。 连接根本就打不进去吧。

最近又宕机了，拿到最新日志(nacos.log)：
![image](https://github.com/alibaba/nacos/assets/35092648/72a401e9-f31c-4301-ac1a-518257fbb952)
![image](https://github.com/alibaba/nacos/assets/35092648/62f44e44-04dd-4835-92d8-a41dc30e4628)

**Comment by KomachiSion** [comment]
这日志就是nacos server收到了 kill 指令了，出发了shutdown hook， 这么看来反而证明了是系统杀掉了 nacos进程。 建议还是排查下系统日志，以及调整下jvm参数等。
