### ISSUE TITLE
请问2.3.0把quickstart功能去掉了吗

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#12109]
请问2.3.0把quickstart功能去掉了吗

**Comment by KomachiSion** [comment]
没看懂问题，你说的quickstart是只文档中quickstart吗？

**Comment by KomachiSion** [comment]
没看懂问题，你说的quickstart是只文档中quickstart吗？

**Comment by KomachiSion** [comment]
No more response from author for a long time, and the problem description not clear.
