### ISSUE TITLE
Highly available, client connected.

### ISSUE THREAD

**Issue by gstripe** [alibaba/nacos#1211]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
高可用的时候，客户端能否跟eureka一样的配置，写上多个地址。因为不想用VIP。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
@gstripe 可以配多个IP的，用逗号分隔即可
