### ISSUE TITLE
nacos服务存在jar包冲突，启动服务连接不到nacos，nacos后台报错NoSuchMethodError

### ISSUE THREAD

**Issue by doutd** [alibaba/nacos#12110]
nacos2.2.0版本，nacos能正常启动，浏览器访问正常，但是在ide中启动服务连接不到nacos，nacos后台报错NoSuchMethodError，排查发现nacos的jar包中nacos下边的jar包，nacos-client里边包含nacos-api和nacos-common这两个jar包里的类，路径和类名都一样，报错也是这里面的类报的，这个要怎么解决

### Tell us your environment
Windows11，idea2024.1.1，nacos2.2.0

### Anything else we need to know?
两个jar包里同一个类下的方法参数不一样
![lQLPJwobXDxEB0XM9c0EWbC11-D0lVggQQYxYp8QT20A_1113_245](https://github.com/alibaba/nacos/assets/169966039/dec05a98-e4ab-45f9-aa1d-0e814189676e)
![lQLPJwQ9yPOyNoXNATnNA36w1OiIoJHgVDgGMWKFRPMxAA_894_313](https://github.com/alibaba/nacos/assets/169966039/31d957d8-b425-4c9b-96b8-2f41cfdb92d2)
![lQLPKHdBOeY8JoXNAS3NBEaweM9NPRwNwmYGMWKFRPMxAQ_1094_301](https://github.com/alibaba/nacos/assets/169966039/a4a041e1-f8fb-4414-89b3-1b56d3d286c3)

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/guide/user/sdk/#_top

nacos-client会自带api和common， 不需要额外引入， 如果额外引入，可能因为包名问题导致冲突。

只有在使用pure 纯净版客户端时才需要引入api和common
