### ISSUE TITLE
nacos service registration ip error

### ISSUE THREAD

**Issue by Coolllh** [alibaba/nacos#12125]
When starting the stand-alone nacos service locally on windows, nacos is registered to some random ip on my Intranet by default, such as 192.168.19.1, and I expect the ip to be localhost

**Comment by KomachiSion** [comment]
the ip of you registered is custom parameter, nacos not get the ip.

please see the API document:

https://nacos.io/docs/latest/guide/user/sdk/#%E6%B3%A8%E5%86%8C%E5%AE%9E%E4%BE%8B


If you do not call this api directly, maybe you should go to the app framework community to ask the configuration about the registered ip.

**Comment by Coolllh** [comment]
I achieved my goal by modifying 'nacos.inetutils.ip-address=127.0.0.1' in the nacos configuration file, but I was confused because I didn't need to modify the ip in the configuration file before, and it was localhost by default. But now I have to take the initiative to modify the configuration file

**Comment by KomachiSion** [comment]
nacos server read self ip by read first one non-loop network interface ip. 

so if your network interface ip is random and not specified ip as localhost or 127.0.0.1, nacos will default use the random ip as nacos server self ip.
