### ISSUE TITLE
Dubbo integration nacos

### ISSUE THREAD

**Issue by CjqDy** [alibaba/nacos#1213]
我用的版本是 dubbo 2.7.1 dubbo-registry-nacos 2.7.1 nacos-client 1.0.0-RC3
这个是我在dubbo 和 nacos 的demo中看到的版本
debug了相关代码

在nacos-client 包 调用NamingProxy里的callServer方法 在进行到
HttpResult result = HttpClient.request(url, headers, params, "UTF-8", method); 发起请求的的时候
返回的result.code 为400 result.content为
dom not found: DEFAULT_GROUP@@providers:com.orange.demo.service.DemoService

所以怀疑是否是nacos-client版本存在问题

**Comment by nkorange** [comment]
@CjqDy 控制台是否能查到providers:com.orange.demo.service.DemoService这个服务？

**Comment by CjqDy** [comment]
@nkorange 没有注册成功，一般400可能是参数错误  但是看了一遍参数 
url, headers, params, "UTF-8", method  这几个参数都有数据，所以不知道啥问题了。
而且在dubbo的代码块里也没有对400这个错误码做处理

**Comment by nkorange** [comment]
你发的错误是订阅方的，查询不到。看下注册方报的什么错？

**Comment by CjqDy** [comment]
> 你发的错误是订阅方的，查询不到。看下注册方报的什么错？

我记得这个方法是在注册服务的时候也调用了，等会我dubbo 切换到2.7版本再看一下

**Comment by CjqDy** [comment]
@nkorange 我知道什么问题了 ，我只更新了项目里的dubbo 和 nacos版本 到2.7.1  
nacos server版本没有改还是0.0.9的，
HttpResult result = HttpClient.request(url, headers, params, "UTF-8", method)
两个版本的请求参数有较大的区别  所以一直请求失败，现在可以了

**Comment by yangzeyimomo** [comment]
> @nkorange 我知道什么问题了 ，我只更新了项目里的dubbo 和 nacos版本 到2.7.1
> nacos server版本没有改还是0.0.9的，
> HttpResult result = HttpClient.request(url, headers, params, "UTF-8", method)
> 两个版本的请求参数有较大的区别 所以一直请求失败，现在可以了

nacos server版本是哪个包?
