### ISSUE TITLE
数据库还原后，配置信息获取不对

### ISSUE THREAD

**Issue by xqj-0511** [alibaba/nacos#12132]
**Describe the bug**
nacos服务采用docker服务方式运行，采用mysql数据库进行配置数据保存。
在nacos服务端运行时，对数据库进行了一次数据还原。此时用SDK方式获取的配置信息并非是当前数据库中保存的配置数据。

假如用Open API方式调用，参数中带上show=all可以获取到最新的配置信息，不带则不行。
GET http://localhost:8848/nacos/v1/cs/configs?show=all&dataId=test&group=DEFAULT_GROUP
GET http://localhost:8848/nacos/v1/cs/configs?dataId=test&group=DEFAULT_GROUP

**Expected behavior**
获取到数据库当前的配置信息。

**Actually behavior**
获取到的数据并非是最新数据

**How to Reproduce**
1. 创建一份配置信息test，然后备份数据库
2. 修改test配置内容，随便修改一个配置信息
3. 进行数据库还原

docker镜像: nacos/nacos-server   v2.2.1

这种情况是因为nacos服务端有缓存导致的吗？怎么刷新

**Comment by ZrBac** [comment]
服务端的ConfigCacheService会存取和更新配置的缓存信息，以减少IO，提升请求性能。你通过数据库的配置数据还原方式，不会触发代码的缓存刷新，可以尝试重启下服务端pod。
