### ISSUE TITLE
nacos部署在k8s里面，无法暴露非80端口

### ISSUE THREAD

**Issue by xhrg** [alibaba/nacos#12147]
我的nacos部署在k8s里面，无法暴露非80端口出来。现在使用的是最新版的nacos

配置的地址如下
spring.cloud.nacos.discovery.server-addr = domain:8848

这个8848可以通过ingress改为 a.domain:80 ，如果客户端固定端口+1000，则是1080，但是无非转发非80端口

请问有什么方案吗

**Comment by KomachiSion** [comment]
这个需要您自己解决。环境的网络问题nacos无能为力

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by freshgeek** [comment]
真难搞
