### ISSUE TITLE
配置数 统计信息不一致

### ISSUE THREAD

**Issue by fctee** [alibaba/nacos#12140]
后端存储使用 mysql，配置数量 网页数据和 数据库数量是一致的。但是 prometheus 接口统计的数量不一致，并且 config-memory.log 中统计的 groupCount 也不一致。请问是什么原因
![微信截图_20240529152342](https://github.com/alibaba/nacos/assets/26137008/0e5584d6-fdb0-49b2-afaf-d0b96481ad32)
![微信截图_20240529152223](https://github.com/alibaba/nacos/assets/26137008/2e98706d-2818-42aa-8bfe-6c0765371d1c)
![微信截图_20240529152126](https://github.com/alibaba/nacos/assets/26137008/91cad577-2595-4958-8ea6-eef52a7ac37b)

**Comment by ZrBac** [comment]
参考这个issue
https://github.com/alibaba/nacos/issues/12062

**Comment by fctee** [comment]
> 参考这个issue，看看是不是类似的问题 #12062

验证了，用最新代码 打包  
2.4.0 版本还是有问题

**Comment by ZrBac** [comment]
https://github.com/alibaba/nacos/issues/12132

**Comment by fctee** [comment]
重新导入数据验证后正常
