### ISSUE TITLE
Nacos connection exception log output is too frequent

### ISSUE THREAD

**Issue by hyw520110** [alibaba/nacos#1214]
在nacos重启或停掉的情况下，应用中的nacos连接异常日志输出太频繁：200毫秒不到输出一次

**Comment by nkorange** [comment]
will be tracked in #1327

**Comment by nkorange** [comment]
Seems not same cause with #1327

**Comment by chuntaojun** [comment]
> 在nacos重启或停掉的情况下，应用中的nacos连接异常日志输出太频繁：200毫秒不到输出一次

config模块还是naming模块？

**Comment by nkorange** [comment]
已经解决了 #1341
