### ISSUE TITLE
springboot服务偶发与nacos server断连导致下线后重新注册

### ISSUE THREAD

**Issue by zwxzxz** [alibaba/nacos#12157]
nacos 2.0.4版本

naming-server.log打印日志

![image](https://github.com/alibaba/nacos/assets/48942885/b2957f89-2c58-4cd5-905f-a419a2bd6fab)

config-memory.log日志：断连服务使用long-pulling连接nacos，只有使用这个方式的微服务会断连

![image](https://github.com/alibaba/nacos/assets/48942885/f3b4a88b-ac36-45f5-b5d8-74b0a5d1b606)

服务报错日志片段截取：服务部署在K8S中
![image](https://github.com/alibaba/nacos/assets/48942885/565f8a19-0b55-401b-b07f-45f1695f564a)

![image](https://github.com/alibaba/nacos/assets/48942885/d44f40cc-2f35-454b-8b40-25097dd7445a)

![image](https://github.com/alibaba/nacos/assets/48942885/d2dd4ae3-4950-41bc-ac61-884248d3b356)

**Comment by KomachiSion** [comment]
看到我云里雾里的， long-polling不就是30s重连一次的吗？ 而且你说的掉线不是naming模块的吗？ 和config的longpolling什么关系。

而且报错是链接超时， 链接超时就是网络问题或性能问题，说明tcp的链接请求就没得到反馈。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and current information is not enough to judge problem.
