### ISSUE TITLE
Nacos 订阅者列表应用名unknown

### ISSUE THREAD

**Issue by BYNepenthe** [alibaba/nacos#12152]
**Describe the bug**
Nacos 订阅者列表应用名unknown，增加了-Dproject.name 这个启动参数也没有用，增加了 spring:cloud:nacos:discovery:metadata: appName 也不行

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [nacos-server 2.3.1, nacos-client 2.2.0]

**Comment by wanglinjie168** [comment]
麻烦问下这个怎么解决的？

**Comment by Dario-s-j** [comment]
Ok

Em ter., 31 de dez. de 2024, 03:45, wanglinjie168 ***@***.***>
escreveu:
