### ISSUE TITLE
集群模式操作服务下线，服务在其中一个节点不能成功下线/Cluster mode operation service offline, service cannot be successfully offline on one of the nodes

### ISSUE THREAD

**Issue by ZhangC001** [alibaba/nacos#12151]
集群模式操作服务下线，服务在其中一个节点不能成功下线/Cluster mode operation service offline, service cannot be successfully offline on one of the nodes

**Describe the bug**
版本2.1.0, 集群模式，节点数3， 以节点A B C示例，在A节点和B节点的管理界面操作服务下线后，A节点和B节点的服务状态更新成功，变为下线，但是在C节点依旧显示为在线，并且有少量流量被路由到已经下线的服务实例，在C节点管理界面操作服务下线，依然是A节点和B节点的服务状态成功变更为下线，C节点的服务状态依旧为在线, 对C节点操作过重启，问题依然存在/Version 2.1.0, Cluster mode with 3 nodes. Taking node A, B, and C as example, after operating the service offline on the WEB page of nodes A and B, the service status of nodes A and B was successfully updated and changed to offline. However, at node C, it still show online and a small amount of traffic was still routed to the offline service instance. When operating the service offline on the WEB page of node C, the service status of nodes A and B was still successfully changed to offline. The service status of node C remained online. and already try restarted  node C,  but the problem still exists.

**Desktop (please complete the following information):**
 - OS:  Centos
 - Version nacos-server 2.1.0
 - Module naming
 - SDK  spring-cloud-alibaba-nacos

**Additional context**
查看了nacos.log、name-event.log和protocaol-sidtro.log, 没有发现什么错误信息/I checked the nacos.log, name-event.log and protocaol-sidtro log, but did not find any error messages

**Comment by KomachiSion** [comment]
C节点和AB节点的raft没有组成集群， 看protocol-raft.log, naming-raft.log alipay-jraft.log.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by ZhangC001** [comment]
![image](https://github.com/alibaba/nacos/assets/32049533/61993874-85a4-41ea-9a26-88620e3d2f8e)
C节点重启protocol-raft.log的日志，看着集群是建立了的，并且获取到了leader
![image](https://github.com/alibaba/nacos/assets/32049533/489e98c3-9b68-4dc3-af30-594ada3e5324)
naming-raft.log 启动日志
![image](https://github.com/alibaba/nacos/assets/32049533/89b8b4ee-4a35-4667-9b65-f7b4bcbf02fa)
alipay-jraft.log 日志，是否可能是raft的Snapshot数据冲突，清除data目录数据，重启重建集群是否可行

**Comment by ZhangC001** [comment]
> C节点和AB节点的raft没有组成集群， 看protocol-raft.log, naming-raft.log alipay-jraft.log.

感谢回复

**Comment by ZhangC001** [comment]
抱歉忘记开启邮件通知了，非常感谢回复，今天才看到，我查看了日志，发下集群构建是成功了的，是否可能是因为Snapshot的数据有问题导致的，如果删除问题节点下data目录数据重启，解决问题是否可行



***@***.***
 
发件人： 杨翊 SionYang
发送时间： 2024-06-06 15:54
收件人： alibaba/nacos
抄送： ZhangC001; Author
主题： Re: [alibaba/nacos] 集群模式操作服务下线，服务在其中一个节点不能成功下线/Cluster mode operation service offline, service cannot be successfully offline on one of the nodes (Issue #12151)
Closed #12151 as not planned.
