### ISSUE TITLE
nacos2.3.1通过openapi发送心跳实例不能维持实例的健康状态

### ISSUE THREAD

**Issue by bigyou** [alibaba/nacos#12161]
**Describe the bug**
![image](https://github.com/alibaba/nacos/assets/3096477/cf73b2a3-6883-43c5-a081-2d5e916dfc8f)

如图所示 在nacos2.3.1版本中，ClientBeatProcessorV2的60行获取instance是null，不能进入更新实例心跳时间的逻辑，导致实例会在15s以后进入不健康状态并被移除。

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
什么情况下会是null？ 

我理解只有正好这个实例因为心跳过期而被移除时， 这个值是null， 是null的话对执行结果没有影响。

**Comment by KomachiSion** [comment]
我测试2.3.1+ nacos1.4.7客户端并不会掉线。

**Comment by bigyou** [comment]
> 我测试2.3.1+ nacos1.4.7客户端并不会掉线。

通过 curl命令定时请求心跳接口： 
curl -X PUT '127.0.0.1:8848/nacos/v1/ns/instance/beat?serviceName=nacos.test.2&beat=%7b%22cluster%22%3a%22c1%22%2c%22ip%22%3a%22127.0.0.1%22%2c%22metadata%22%3a%7b%7d%2c%22port%22%3a8080%2c%22scheduled%22%3atrue%2c%22serviceName%22%3a%22jinhan0Fx4s.173TL.net%22%2c%22weight%22%3a1%7d&accessToken=' 



在nacos1.4.6 通过上述方式请求心跳接口，注册实例能保持健康状态。 
nacos2.3.1 通过上述方式请求心跳接口，注册实例不能保持健康状态，在15s后会被标记为不健康，30s后会被删除

**Comment by bigyou** [comment]
> 什么情况下会是null？
> 
> 我理解只有正好这个实例因为心跳过期而被移除时， 这个值是null， 是null的话对执行结果没有影响。

![image](https://github.com/alibaba/nacos/assets/3096477/4cb57c24-b3a2-4891-9769-65516bc9da0e)
59行新new了一个service对象，和  ConcurrentHashMap<Service, InstancePublishInfo> publishers 里缓存的key 不是同一个service吧，这里通过 publishers.get(service) 是不是拿不到 缓存的 InstancePublishInfo ？

**Comment by bigyou** [comment]
> curl -X PUT '127.0.0.1:8848/nacos/v1/ns/instance/beat?serviceName=nacos.test.2&beat=%7b%22cluster%22%3a%22c1%22%2c%22ip%22%3a%22127.0.0.1%22%2c%22metadata%22%3a%7b%7d%2c%22port%22%3a8080%2c%22scheduled%22%3atrue%2c%22serviceName%22%3a%22jinhan0Fx4s.173TL.net%22%2c%22weight%22%3a1%7d&accessToken='

问题已经清楚了：
这里 https://nacos.io/docs/v1/open-api/#2.6 提供的心跳请求示例数据有问题：
url上的serviceName和beat结构体内的serviceName不一致导致的这个问题，具体分析如下。


![image](https://github.com/alibaba/nacos/assets/3096477/e7413401-52a6-4dc1-90d1-e74aa3de9de4)

**Comment by bigyou** [comment]
看是否有必要做一下教校验：
心跳请求url中的servicename 属性和beat对象中的servicename属性需要一致？
