### ISSUE TITLE
集群模式下，某一个节点重启第一次distro数据全量同步失败

### ISSUE THREAD

**Issue by zimubit001** [alibaba/nacos#12160]
**Describe the bug**
版本2.1.0, 集群模式，节点数3，当某一个节点重启，首次进行distro全量服务信息拉取时失败，在 protocol-distro.log 日志会有如下报错

![image](https://github.com/alibaba/nacos/assets/86195667/44aaa5cd-2ee6-4438-9e89-a54948406232)

**Comment by KomachiSion** [comment]
失败可能是因为网络问题， 失败之后会重试，不影响。

**Comment by zimubit001** [comment]
我们的网络在同一个网段，网络没问题，每一次启动都会有这个报错，这种情况，该节点的服务实例不是完整的，在下一次重试前，如果客户端做服务发现会拉取到空的实例列表。

**Comment by KomachiSion** [comment]
Distro 作为AP协议，优先保证系统可用性， 所以加载是异步加载，不能阻塞启动； 但是Distro协议的启动依赖了Member report，所以正常情况下开始做数据同步时， 已经能够正常建立server间链接， 至少我自己部署的所有环境里还没有发现过这个问题。

可以看下你的环境里是否有环境层面的依赖，比如节点在端口启动前，其他节点访问不到该节点或该节点无法访问其他节点的情况。
可以看下nacos-cluster.log日志。和~/logs/nacos/remote.log。

如果找不到问题，建议你将重启节点延迟暴露到vip上。或打开推空保护开关

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
