### ISSUE TITLE
服务列表和配置管理列表页面下面能不能加上总记录数

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/nacos#12178]
服务列表和配置管理列表页面下面能不能加上总记录数
因为数量大时，重启所有服务，要人工数数量来看看服务是否都起来了

**Comment by HMYDK** [comment]
后端有返回count，ServiceList.js也接受了count赋值到total，估计是前端渲染出问题了，导致没显示（maybe

**Comment by misakacoder** [comment]
@HMYDK 
本来就有总数显示吧
![image](https://github.com/alibaba/nacos/assets/36252937/2d1238f1-9ace-4de9-a053-f2c1fec7a4b9)
他这应该是想看看监听中的服务有多少从而判断服务是否都启动起来，但是配置监听中必须传参数来查询，监听的dataId和groupId不一样的话，看起来也不直观
![image](https://github.com/alibaba/nacos/assets/36252937/5a8fe6ae-4ec2-44ba-afd4-dcfece1b430b)
