### ISSUE TITLE
nacos upgrade: Client not connected,current status:STARTING

### ISSUE THREAD

**Issue by smallemployees** [alibaba/nacos#12174]
**Describe the bug**
The client cannot connect to the server
**Expected behavior**
How to quickly complete the upgrade process
**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by stone-98** [comment]
这个是有什么问题吗？nacos升级过程中，客户端断连然后再重连是正常现象。

**Comment by KomachiSion** [comment]
Client not connected,current status:STARTING means your client  can't connect to server,

please check your server start, port export successfully, and you client configuration is right.
