### ISSUE TITLE
cannot deploy nacos server inside EDAS

### ISSUE THREAD

**Issue by k4124k** [alibaba/nacos#1217]
## Issue Description

Type: *bug report* 

cannot deploy nacos server inside EDAS.

### Describe what happened (or what feature you want)

when you deploy nacos server inside EDAS,  namespace will be repaced with EDAS env -- ALIBABA_ALIWARE_NAMESPACE 

### Describe what you expected to happen

custom namespace should be primarily

### How to reproduce it (as minimally and precisely as possible)

1. deploy nacos server inside EDAS
2. startup app with nacos client

### Anything else we need to know?

found in nacos-client 0.9.1+

**Comment by nkorange** [comment]
@k4124k Your problem is your namespace id is overridden and you don't want it to be replaced?

**Comment by k4124k** [comment]
yes

**Comment by nkorange** [comment]
use -Dnamespace=xxxx to override the system environment variable.

**Comment by k4124k** [comment]
same question with system property - tenant.id / acm.namespace

**Comment by nkorange** [comment]
> same question with system property when use public namespace - tenant.id / acm.namespace

We found it's a bug of nacos-client. We will fix it in Nacos 1.0.1 in this month.
