### ISSUE TITLE
请问监听有考虑过回调接口是一个数组吗

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#12183]
我们使用nacos的2.1.0客户端时 将nacos的客户端集成在我们的公用sdk中 并且将configservice通过单例的方式提供出去
在使用过程中 发现一个问题 就是公用sdk中监听的配置 在业务使用过程中 如果业务也需要监听此配置 
会导致监听回调函数只有一个能使用 
请问这样设计的背景是啥 有没有曾经遇到过的问题 导致这样的设计

**Comment by KomachiSion** [comment]
应该是你的用法有问题， 同一个配置应该是可以有多个listener的，除非这个第一个listener回调逻辑有问题，报错了或者卡住，才会导致后面的listner不执行。

所以你应该在共有的地方监听这个配置，加一个listener， 业务应该自建一个listener也发起监听。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
