### ISSUE TITLE
Unable to create or change a table without a primary key

### ISSUE THREAD

**Issue by xiangyanw** [alibaba/nacos#12197]
**Describe the bug**
Failed to create tables when initialing MySQL DB using `mysql-schema.sql` in AWS RDS Multi-AZ DB Cluster. Error message as below:

```
Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.
```

This is because sql_require_primary_key is set to true in MySQL cluster. But `roles` and `permissions` table have no primary key.

**Expected behavior**
Be able to init table successfully.

**Actually behavior**
Failed to create table `roles` and `permissions`.

**How to Reproduce**
1. Create an AWS RDS MySQL Cluster;
2. Download `mysql-schema.sql`;
3. Init database by `mysql-schema.sql`;
4. See errors

**Desktop (please complete the following information):**
 - MySQL version: 8.0.35
 - Deployment option: Multi-AZ DB Cluster
 - Nacos version: 2.3.2

**Additional context**

**Comment by miclosgyjf** [comment]
> **Describa el error** No se pudieron crear tablas al inicializar la base de datos MySQL usando `mysql-schema.sql`el clúster de base de datos AWS RDS Multi-AZ. Mensaje de error como el siguiente:
> 
> ```
> Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.
> ```
> 
> Esto se debe a que sql_require_primary_key está configurado en verdadero en el clúster MySQL. Pero `roles`la `permissions`tabla no tiene clave principal.
> 
> **Comportamiento esperado** Ser capaz de iniciar la tabla con éxito.
> 
> **En realidad, el comportamiento** no pudo crear la tabla `roles`y `permissions`.
> 
> **Cómo reproducir** Pasos para reproducir el comportamiento:
> 
> 1. Cree un clúster MySQL de AWS RDS;
> 2. Descargar `mysql-schema.sql`;
> 3. Iniciar base de datos por `mysql-schema.sql`;
> 4. Ver errores
> 
> **Escritorio (por favor complete la siguiente información):**
> 
> * Versión de MySQL: 8.0.35
> * Opción de implementación: Clúster de base de datos Multi-AZ
> * Versión de Nacos: 2.3.2
> 
> **Contexto adicional** Agregue aquí cualquier otro contexto sobre el problema.

**Comment by miclosgyjf** [comment]
> > **Describe el error** No se pudo crear tablas al inicializar la base de datos MySQL usando `mysql-schema.sql`el clúster de base de datos AWS RDS Multi-AZ. Mensaje de error como el siguiente:
> > ```
> > Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Esto se debe a que sql_require_primary_key esté configurado en verdadero en el clúster MySQL. Pero `roles`la `permissions`tabla no tiene clave principal.
> > **Comportamiento esperado** Ser capaz de iniciar la tabla con éxito.
> > **En realidad, el comportamiento** no pudo crear la tabla `roles`y `permissions`.
> > **Cómo reproducir** Pasos para reproducir el comportamiento:
> > 
> > 1. Cree un cluster MySQL de AWS RDS;
> > 2. Descargar `mysql-schema.sql`;
> > 3. Iniciar base de datos por `mysql-schema.sql`;
> > 4. Ver errores
> > 
> > **Escritorio (por favor complete la siguiente información):**
> > 
> > * Versión de MySQL: 8.0.35
> > * Opción de implementación: Clúster de base de datos Multi-AZ
> > * Versión de Nacos: 2.3.2
> > 
> > **Contexto adicional** Agregue aquí cualquier otro contexto sobre el problema.

**Comment by miclosgyjf** [comment]
https://github.com/alibaba/nacos/issues/273#issue-380519741
