### ISSUE TITLE
nacos uses 'http_sd_configs' which is not well adapted to prometheus

### ISSUE THREAD

**Issue by kuman62** [alibaba/nacos#12196]
**Describe the bug**
Prometheus uses the http_sd_configs method, and the labels field in its protocol does not support the symbols . and -

#Nacos 
#http://127.0.0.1:8848/nacos/prometheus   http return
[{"targets":["192.168.31.20:9084"],"labels":{"preserved.register.source":"SPRING_CLOUD"}}]

#prometheus.yml
scrape_configs:
  - job_name: 'nacos-public'
    http_sd_configs:
      - url: http://127.0.0.1:8848/nacos/prometheus

#prometheus run log
ts=2024-06-09T18:29:25.243Z caller=refresh.go:80 level=error component="discovery manager scrape" discovery=http config=nacos-public msg="Unable to refresh target groups" err="\"preserved.register.source\" is not a valid label name"

**Comment by KomachiSion** [comment]
the metadata is registered by users, which means registered by yourself, please registered without this words when you want to use prometheus sd.

if use replace to _ , it might cause the message means dropped. See community suggest and callback.

BTW. I think we can add an switch properties to open or close this feature.

**Comment by taomaree** [comment]
> BTW. I think we can add an switch properties to open or close this feature.
good idea.

label `"preserved.register.source":"SPRING_CLOUD"`  is auto added by nacos  sdk, 
and  another example is label `"management.endpoints.web.base-path":"/xxxx" ` , which auto exported by nacos sdk, label name contains two  invalid words `. ` and `-` .
above 2 label name are not controlled or registered by enduser, and prometheus can't parse these label names, then this scrape job failed, this job results show nothing.

maybe convert label name from `. ` and `-`   words to` _ `  in prometheus/src/main/java/com/alibaba/nacos/prometheus/utils/PrometheusUtils.java only affect prometheus exporter info.

**Comment by KomachiSion** [comment]
> > BTW. I think we can add an switch properties to open or close this feature.
> 
> good idea.
> 
> label `"preserved.register.source":"SPRING_CLOUD"` is auto added by nacos sdk, and another example is label `"management.endpoints.web.base-path":"/xxxx" ` , which auto exported by nacos sdk, label name contains two invalid words `. ` and `-` . above 2 label name are not controlled or registered by enduser, and prometheus can't parse these label names, then this scrape job failed, this job results show nothing.
> 
> maybe convert label name from `. ` and `-` words to`_` in prometheus/src/main/java/com/alibaba/nacos/prometheus/utils/PrometheusUtils.java only affect prometheus exporter info.

the label is not added by nacos sdk， it added by applications. same with `management.endpoints.web.base-path`.
