### ISSUE TITLE
[bug]disk failover datasource not keep status

### ISSUE THREAD

**Issue by shalk** [alibaba/nacos#12207]
**Describe the bug**
I try to use client discovery  feature "failover on disk ", when create failover switch file `00-VIP-SWICH-...`. 

The client log print `failover-mode is on`,  a few second later, log print `failover switch changed, new: off`

Because in DiskFailoverDataSource,  switch file is not change, so lastModifiedMillis == modified and `return new FailoverSwitch(Boolean.FALSE);`

I think this is bug in early pr, i will fix it.

**Expected behavior**
expect failover switch is alway on 

**Actually behavior**
failover switch is off at last

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
so should we change the judgement but not add an status to keep this way?

**Comment by shalk** [comment]
> so should we change the judgement but not add an status to keep this way?

when  lastModifiedMillis == modified , we do not know what is lastSwitch ?  

MeanWhile switchParams is useless,  and the judegement can be improve. 

what is your opinion ?

**Comment by KomachiSion** [comment]
> > so should we change the judgement but not add an status to keep this way?
> 
> when lastModifiedMillis == modified , we do not know what is lastSwitch ?
> 
> what is your opinion ?

OK, I know what's your mean, I think your change is a way to fix this problem. Or we reuse the `switchParams`.

If `switchParams` contain key `FAILOVER_MODE_PARAM`, we use the values, else return false. Is it ok?

**Comment by shalk** [comment]
Yes , `switchParams` can be reuse. pr have been updated
