### ISSUE TITLE
[Ask] Nacos external datasource config, nacos version 2.2.3

### ISSUE THREAD

**Issue by bubua12** [alibaba/nacos#12211]
### question: the config `spring.sql.init.platform=mysql` & `spring.datasource.platform=mysql`
i have some question about the `application.properties` in `/nacos/conf/`, and i use mysql as external datasource, when i use the config `spring.datasource.platform=mysql`, and i open the nacos config center, it seems the exception occure, like Bad SQL `java.sql.SQLSyntaxErrorException`  at cloumn `ENCRYPTED_DATA_KEY` on table `config_info`, but the `config_info` has the column, then i open the `spring.sql.init.platform=mysql` and close the `spring.datasource.platform=mysql`, it worked. so i  would like to ask what this configuration `spring.sql.init.platform=mysql` means, just replaced `spring.datasource.platform=mysql`?

```properties
#*************** Config Module Related Configurations ***************#
### If use MySQL as datasource:
### Deprecated configuration property, it is recommended to use `spring.sql.init.platform` replaced.
# spring.datasource.platform=mysql
# spring.sql.init.platform=mysql
```

**Comment by KomachiSion** [comment]
This is spring boot behavior, `spring.sql.init.platform` is a new parameters and `spring.datasource.platform` is old parameters for some version, But no one know when spring remove to support old parameter.

So as the properties comment:
```
### Deprecated configuration property, it is recommended to use `spring.sql.init.platform` replaced.
```

**Comment by bubua12** [comment]
✔ Thank you, that's right, I understand, thank you very much
![image](https://github.com/alibaba/nacos/assets/169867857/e953d850-dabd-4a5f-8527-cbb3573b6885)
