### ISSUE TITLE
使用官方提供的注销nacos实例的api成功调用后nacos上的该服务没有被注销。

### ISSUE THREAD

**Issue by bubb1eP** [alibaba/nacos#12223]
`NamingService namingService = NamingFactory.createNamingService(
                    nacosDiscoveryProperties.getNacosProperties());
                    namingService.deregisterInstance(customerServiceInstance.getServiceId(),
                        customerServiceInstance.getHost(),
                        customerServiceInstance.getPort());`
                        使用此段代码注销nacos实例失败，试过很多获取namingService然后注销实例的方法都失败了。这是bug吗还是我哪里环节出问题了

**Comment by bubb1eP** [comment]
> `NamingService namingService = NamingFactory.createNamingService( nacosDiscoveryProperties.getNacosProperties()); namingService.deregisterInstance(customerServiceInstance.getServiceId(), customerServiceInstance.getHost(), customerServiceInstance.getPort());` 使用此段代码注销nacos实例失败，试过很多获取namingService然后注销实例的方法都失败了。这是bug吗还是我哪里环节出问题了

我确保我的服务名，服务ip，和端口是没有问题。本地环境试的

**Comment by HMYDK** [comment]
没看见你用namingService注册instance呀

**Comment by shaojunjieSJJ** [comment]
我想注销这两个服务
![image](https://github.com/user-attachments/assets/01a5958d-6d5d-4b93-a21c-f7eda362828a)
![image](https://github.com/user-attachments/assets/736ab3f2-76eb-4cfe-91c7-08b66d6fa1ce)
![image](https://github.com/user-attachments/assets/34a91ba5-d622-4d02-9c75-74def0b58bab)
![image](https://github.com/user-attachments/assets/c8d3e755-7e83-43aa-8005-8bc55b9015c4)
![image](https://github.com/user-attachments/assets/f8ba35b3-99bf-4d24-a861-596e21bed3b3)
实际上它们仍然在线。
