### ISSUE TITLE
我已经更改了nacos的数据存储方式为Mysql，为什么还会在主目录下自动生成一个名为nacos的文件夹

### ISSUE THREAD

**Issue by zhuzhegithub** [alibaba/nacos#12222]
我已经更改了nacos的数据存储方式为Mysql，为什么还会在主目录下自动生成一个名为nacos的文件夹，用于存放SQLite数据库文件及日志。而且删除之后还会再次生成。这样导致我的配置文件直接全部暴露在服务器上了。

**Comment by kangzhaok** [comment]
2.x版本会默认将配置保存在文件中，sdk获取的配置都是从文件中获取

**Comment by KomachiSion** [comment]
本地磁盘缓存， 查询配置的请求优先读取磁盘缓存，避免所有查询流量打穿到数据库中，导致数据库成为容量瓶颈

**Comment by wuchubuzai2018** [comment]
Nacos的这种设计非常有用，一个是会在服务端的本地磁盘上缓存，一个是在客户端的本地磁盘上缓存，记得之前nacos由于某种原因丢失了mysql数据，然后就去磁盘上找到了缓存配置文件，恢复了
