### ISSUE TITLE
The nacos configuration file for running a single node is empty

### ISSUE THREAD

**Issue by thewindsrise** [alibaba/nacos#12237]
**Describe the bug**
The nacos configuration file for running a single node is empty.

**Expected behavior**
I would like to be able to read the configuration parameters in this configuration file.

**Actually behavior**
If you can't read this configuration file, it's not that the configuration parameters in the file can't be found, it's that the entire file can't be found.

**How to Reproduce**
1. Execute the command:  `./startup.cmd -m standalone` to run on a single node.
2. A new cfg namespace is created, and a configuration file with the group cfg and file name tset1.yaml is created in this namespace.
3. The configuration file is read in kotlin code by @Value annotations.
4. There are warnings：[main] c.a.c.n.c.NacosConfigDataLoader : [Nacos Config] config[dataId=test1.yaml, group=cfg] is empty.
5. There are errors：Could not resolve placeholder 'sck.flag.test1' in value "${sck.flag.test1}".

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Version [e.g. nacos-server 2.3.2, nacos-client 2.3.2]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos]

**Additional context**
Here's a screenshot of my nacos config file:
<img width="1255" alt="6a9d369bc6faa2ba27bedaab2166faf" src="https://github.com/alibaba/nacos/assets/165985940/52dc81aa-c45c-41cc-b64e-c544b47a926c">
I debugged and found that nacos running on a single node will try to load the configuration file in the local `C:\Users\wjf\nacos\config\fixed-cfg-127.0.0.1_8848_nacos\data\config-data-tenant\cfg\cfg\test2.yaml` directory, but I don't have this file locally, Here is a screenshot：
<img width="1280" alt="f1710e805fe9c702f3bc8f1188d1ca3" src="https://github.com/alibaba/nacos/assets/165985940/2875561d-2e04-4171-8558-9571c142131a">

**Comment by KomachiSion** [comment]
The failover feature is for users can upgrade configuration when nacos server can't work.

The failover file need users create by themselves. If no this file, nacos client will not open failover feature and only read configuration from nacos server.

If you can't get config from server, please check why nacos-client can't get config or can't connect to server please.

**Comment by thewindsrise** [comment]
Using the stand-alone database schema has solved this problem, the database is configured in the 'conf/application.properties' file in the nacos server installation directory, and then the service works normally.
