### ISSUE TITLE
There is an inconsistency between Nacos's local configuration information and the database configuration information, and this inconsistency cannot be automatically resolved.

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#12231]
**Describe the bug**
When inserting and updating configurations in the database, the gmt_modified field is set using the local timestamp of the Nacos node rather than the database's built-in time function. This can lead to inconsistencies between the server node data and the database data when different Nacos nodes concurrently modify the same configuration, and this inconsistency cannot be automatically resolved.

**Expected behavior**
When inserting and updating configurations in the database, the time-related field values need to be set using the time obtained from the database's built-in time function.

**Actually behavior**
When inserting and updating configurations in the database, the gmt_modified field is set using the local timestamp of the Nacos node rather than the database's built-in time function.

**Comment by caoyanan666** [comment]
这个会让pg报错，
![image](https://github.com/user-attachments/assets/38212261-b940-499e-93d3-dbef3126fb0e)

**Comment by caoyanan666** [comment]
https://github.com/nacos-group/nacos-plugin/pull/46/files
