### ISSUE TITLE
After the virtual machine server is suspended, the applications in the server will not be taken offline

### ISSUE THREAD

**Issue by Anme47854** [alibaba/nacos#12234]
nacos:2.2.2
Scenario: In ESXi, the virtual machine is actively suspended (company server crashes, performing environment simulation), but the applications in the virtual machine are still in the service cluster

**Comment by Anme47854** [comment]
After actively killing the application, nacos disappears during registration

**Comment by KomachiSion** [comment]
If the application stiil send heartbeat to nacos and the connection still active, nacos will think the instance is keepalive and keep it.

only when the heartbeat failed reach the count/ connection lost/ call deregistered, nacos server delete this instance.

So If your virtual machine is actively suspended, but it still can send heartbeat to nacos, and keep the connection. It are still  in the service cluster.
