### ISSUE TITLE
2.2.3 Nacos启动约5分钟后，提示StackOverflowError Exception

### ISSUE THREAD

**Issue by ReNolaColor** [alibaba/nacos#12245]
**Describe the bug**
2.2.3 Nacos启动约5分钟后，提示StackOverflowError Exception

**Additional context**
Nacos未变更升级
MySQL从8.0.22升级至8.0.37

相同Nacos和MySQL的服务，在部分环境出现StackOverflowError ，在部分环境正常
![0ca184069e60de9e2c1f6342f792dd3a](https://github.com/alibaba/nacos/assets/173138920/847d7415-23e7-4ad6-aaef-b079e0650d22)

**Comment by KomachiSion** [comment]
目前没有反馈发生过此类问题，可能需要您使用jstack指令看一下什么地方出现了类似递归的调用。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and current information is not enough to judge problem.
