### ISSUE TITLE
nacos kubernetesspring boot application config and register failed

### ISSUE THREAD

**Issue by nzb15555196162** [alibaba/nacos#12241]
**Describe the bug**
In the kubernetes environment, the springboot application uses nacos as the configuration center and registration center exception
**Expected behavior**
In the kubernetes environment, the springboot application uses nacos as the configuration center and registration center ok

**Actually behavior**
In the kubernetes environment, the springboot application uses nacos as the configuration center and registration center exception

**How to Reproduce**
see my below screenshot
in kubernetes:
1 
![1](https://github.com/alibaba/nacos/assets/18350673/c60c9451-cca9-42e7-ac0f-dac82f810bc6)
![2](https://github.com/alibaba/nacos/assets/18350673/754b151c-c43a-48b4-bb3f-43fba6076b64)
2 when i remove nacos configuration in kubernetes
![1](https://github.com/alibaba/nacos/assets/18350673/dd58f574-947d-4137-882c-af54cfcdf880)
![2](https://github.com/alibaba/nacos/assets/18350673/1d03f88b-d0ad-46a9-8a3c-348003bb68f4)
3 local start 
![1](https://github.com/alibaba/nacos/assets/18350673/df8d5a6d-93b3-40fd-a6c7-f79a78e5b91b)
![2](https://github.com/alibaba/nacos/assets/18350673/8ccc5078-656c-419f-b944-7ed2e2db6534)

**Desktop (please complete the following information):**
 - OS: Centos7.9
 - Version nacos-server 2.1, nacos-client 1.3.1
 - Module naming/config/register
 - SDK original, spring-cloud-alibaba-nacos

**Additional context**

**Comment by KomachiSion** [comment]
it's not nacos' problem I think. you should check your application can read the init bootstrap configuration from k8s

**Comment by nzb15555196162** [comment]
> it's not nacos' problem I think. you should check your application can read the init bootstrap configuration from k8s

I have shown 3 scenarios
1. the centos7 kubernetes application obtains the nacos configuration abnormally. The application starts abnormally, which leads to the application registration abnormally. However, the command line obtains the application configuration normally. See my screenshots
![2](https://github.com/alibaba/nacos/assets/18350673/fb07846f-7abe-4cbf-9cfe-e7296dec7094)

3. the centos7 kubernetes application removes the nacos configuration function. The application obtains the configuration from the configuration file. The application starts normally and registers nacos
4. the windows application obtains the nacos configuration normally, starts normally and registers to nacos
Through my verification, the problem is a problem with centos kubernetes nacos. The problem lies in the application obtaining the nacos configuration.

**Comment by KomachiSion** [comment]
From you description, I think it's your application problem. When you application deploy with k8s, it will not read configuration from nacos, but use local config, or when it get config during starting, the network is not well, and waiting the application end, the pod ready and network well.

I suggest you to see the nacos-client log `${user.home}/logs/nacos/config.log` to see whether get target config and whether with error.

**Comment by nzb15555196162** [comment]
> From you description, I think it's your application problem. When you application deploy with k8s, it will not read configuration from nacos, but use local config, or when it get config during starting, the network is not well, and waiting the application end, the pod ready and network well.
> 
> I suggest you to see the nacos-client log `${user.home}/logs/nacos/config.log` to see whether get target config and whether with error.
It should be closed now, because everything is ok with the new kubernetes cluster
