### ISSUE TITLE
【BUG】命名空间200限制，是显示错误吗

### ISSUE THREAD

**Issue by JaneYork** [alibaba/nacos#12242]
**Describe the bug**
nacos2.3.2，命名空间限制200，这个是界面显示忘记修改了？

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
<img width="1334" alt="image" src="https://github.com/alibaba/nacos/assets/29787967/9b75a634-e036-4ec3-858d-91e6b1c49a7d">

**Comment by kangzhaok** [comment]
不是bug，显示的你当前的配置项总数/200

**Comment by kangzhaok** [comment]
其实并没有限制总数不能超过200

**Comment by KomachiSion** [comment]
曾经规划过限制单个命名空间的配置个数限制等等， 但是社区版其实没有实现，所以事实上没有限制， 这里就显示了默认值。
