### ISSUE TITLE
如何处理 kubelet 异常，没有删除服务容器，导致 nacos 临时实例无法下线问题

### ISSUE THREAD

**Issue by littlejiancc** [alibaba/nacos#12248]
**Describe the bug**
使用场景
k8s 环境下，使用 nacos 作为配置中心和服务注册、发现和负载均衡。服务往 nacos 上注册的是 podIP
问题
节点负载过高导致 Kubernetes 触发重新调度，出现异常节点上的 kubelet 因为负载高或者 kubelet 挂了，并没有删除 Pod，导致服务仍然向 Nacos 发送心跳包，使得 Nacos 显示两个健康实例但实际有一个不健康的情况

对于这种情况改如何去处理呢

目前想到有两个方案：

1. 不使用nacos的服务发现，使用k8s原生的服务发现

2. 使用非临时服务，有订阅者自行判断是否使用

**Comment by KomachiSion** [comment]
这两种方案都不能彻底解决。
1. k8s原生服务发现，kubelet挂了pod不一定会删除或标记为不健康（看readniess如何配置）， apiserver上还有这个数据。最终还是需要在订阅测做路由或者改路由规则。
2. 使用非临时服务，同样的，探测失败后变成不健康，nacos也只会标记成不健康，不会移除，所以还是需要订阅者判断。而且还有数据维护工作上的事，需要手动或别的手段来删除过期不健康的节点（类似kubelet给你做的事）。

社区推荐的方案是：保持当前注册订阅模式， 在订阅者测可以进行重试和主动探测的方式，标记一些暂时可能有异常的ip，路由选择时暂时剔除，这也是现在大多数应用框架和RPC框架的策略。

不过分布式方案目前没有银弹，最终选择何种方案需要根据你能接受的改动和预期的行为来做。最终选择何种方案需要根据自身需求决定。

**Comment by littlejiancc** [comment]
@KomachiSion 明白了，灰常感谢
