### ISSUE TITLE
配置管理-配置列表页面的配置总数重复展示

### ISSUE THREAD

**Issue by misakacoder** [alibaba/nacos#12246]
左上角和右下角都展示了配置总数，是否有些重复了。还有右下角的配置总数没有做国际化处理

![image](https://github.com/alibaba/nacos/assets/36252937/d0050e1d-421f-41fe-9085-e0bcb57bd24e)

**Comment by KomachiSion** [comment]
多处显示应该没关系，有的人可能更喜欢看上面的总结，有的人更习惯看表格的分页。

国际化处理可以提交pr帮助社区优化一下。
