### ISSUE TITLE
如何用 OpenAPI 发布配置接口修改单个配置项？

### ISSUE THREAD

**Issue by Nehcknarf** [alibaba/nacos#12247]
`curl.exe -X POST "http://localhost:8848/nacos/v2/cs/config?username=nacos&password=nacos&dataId=prod.properties&group=DEFAULT_GROUP&type=properties&content=spring.datasource.druid.password=123456"`
我这样修改会覆盖原有的其他配置项，仅剩spring.datasource.druid.password这条，我想只修改spring.datasource.druid.password一项要怎么做呢？

**Comment by kangzhaok** [comment]
目前做不了，除非你把这一项单独抽离到一个dataid

**Comment by kangzhaok** [comment]
或者你将修改后的所有内容都push上去

**Comment by Nehcknarf** [comment]
> 或者你将修改后的所有内容都push上去

感觉只能这样了
