### ISSUE TITLE
regular strings cannot be dynamically updated

### ISSUE THREAD

**Issue by xiaocaichao** [alibaba/nacos#12250]
**Describe the bug**
When the configuration value is a regular string, after modifying and publishing the regular on the server, the dynamic hot update of the configuration becomes invalid, and the latest regular string cannot be obtained

**Expected behavior**

**Actually behavior**
Normal hot update

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [ Centos]
 - Version [ nacos-server 2.2.3, nacos-client 2.1.0]
 - Module [ config]
 - SDK [nacos-config-spring-boot-starter:0.2.12]

**Additional context**

**Comment by KomachiSion** [comment]
It's not nacos' problem I think. Nacos only push the full config text to your application, how to refresh config to your application is your application working, or your app framework's working.

I suggest you submit issue to your app framework's community, such as Spring Cloud alibaba.

**Comment by xiaocaichao** [comment]
> It's not nacos' problem I think. Nacos only push the full config text to your application, how to refresh config to your application is your application working, or your app framework's working.
> 
> I suggest you submit issue to your app framework's community, such as Spring Cloud alibaba.

i use @NacosValue in springboot Service to get the dynamic config value，  if the value is not a regular string， it works well。
I don't think it's a problem with the development framework, is it？

**Comment by KomachiSion** [comment]
> > It's not nacos' problem I think. Nacos only push the full config text to your application, how to refresh config to your application is your application working, or your app framework's working.
> > I suggest you submit issue to your app framework's community, such as Spring Cloud alibaba.
> 
> i use @NacosValue in springboot Service to get the dynamic config value， if the value is not a regular string， it works well。 I don't think it's a problem with the development framework, is it？

No, it's just the problem development framework, nacos only push the new full configuration to lisntener. But the app how to parse the configuration and how to use new config, and how to refresh the old config is not nacos' problem. Because when nacos notify full new  configuration to lisntener, nacos' work has finished.
