### ISSUE TITLE
client使用endpoint方式连接nacos，然后把地址服务器上的nacos ip切换至其他ip后，client程序过段时间会出现403

### ISSUE THREAD

**Issue by misakacoder** [alibaba/nacos#12257]
分支：develop

原因：修改地址服务器上的nacos ip后，config和naming的ServerListManager刷新了serverList，但是鉴权插件没有刷新serverList。当鉴权插件持有的token过期后，一直向旧的nacos server请求token，旧的nacos server已经下线了，所以刷新不了token。

naming的rpc client持有的serverList：

![image](https://github.com/alibaba/nacos/assets/36252937/0577c686-7514-4864-9d14-4fdc911c4d47)

config的rpc client持有的serverList：

![image](https://github.com/alibaba/nacos/assets/36252937/bb584633-5801-4095-b34a-d06bacedf8c0)

auth plugin持有的serverList：

![image](https://github.com/alibaba/nacos/assets/36252937/5c2b429c-0c7b-4ad0-a602-d1ea2542d44d)

异常：
![image](https://github.com/alibaba/nacos/assets/36252937/ff554f80-a2be-4d04-911d-9e5a97a9d904)
![image](https://github.com/alibaba/nacos/assets/36252937/b3ff4449-1c77-40ef-8aa3-c214f0351d82)

**Comment by KomachiSion** [comment]
Yes, it need be enhanced, but it depend issue https://github.com/alibaba/nacos/issues/12189. 

Please wating https://github.com/alibaba/nacos/issues/12189 finished and use unified serverlist manager to do.

**Comment by misakacoder** [comment]
@KomachiSion 这个bug我重新提交了一个pr，你看看有没有问题
