### ISSUE TITLE
k8s中部署的nacos2.0.3升级到2.2.3

### ISSUE THREAD

**Issue by zzzxx** [alibaba/nacos#12264]
在k8s中部署的 2.0.3版本，并且已经通过crontab关闭了双写
升级2.2.3版本的方式如下：
1、使用2.2.3原始镜像构建新的镜像开启鉴权
FROM harbor.dshytest.com/dshy-basic/nacos-server:v2.2.3
RUN echo "nacos.core.auth.enabled=true" >> /home/nacos/conf/application.properties
2、 修改2.2.3版本的yaml文件 添加一下配置，其他的配置和2.0.3配置检查过基本一致
            - name: NACOS_AUTH_IDENTITY_KEY
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: nacos.core.auth.server.identity.key

            - name: NACOS_AUTH_IDENTITY_VALUE
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: nacos.core.auth.server.identity.value

            - name: NACOS_AUTH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: nacos.core.auth.plugin.nacos.token.secret.key

3、k8s的configmap添加以下配置
nacos.core.auth.plugin.nacos.token.secret.key    SecretKey012345678901234567890123456789012345678901234567890123456789 
nacos.core.auth.server.identity.key    serverIdentity 
nacos.core.auth.server.identity.value     security 
4、通过yaml文件进行升级

5、升级成功后， web页面退出，重新登录后，可以正常访问，nacos集群状态正常
本地windows电脑调试  jdk版本 oracle-jdk 1.8.0 331  能够连接登录上。

6、k8s集群中已经运行的Pod 会报错, 重新启动pod后也是会报错。
 use not found 
Caused by: com.alibaba.nacos.api.exception.NacosException: Invalid signature
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271) ~[nacos-client-2.0.3.jar:?]
	... 12 more

Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.

这个是什么问题，要怎么解决

**Comment by KomachiSion** [comment]
首先是两个问题：
1. `Invalid signature` 一般情况下是两者的secret.key不同导致的，但也有jdk的bug会导致Hmac算法不支持从而提示`Invalid signature`，首先确认secret.key的配置是一致的，然后再确认jdk是否有Hmac算法的bug。

2. Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.
这个问题提示的挺明确的， 建议按照文档看一下，强制关闭双写。应该是你2.0.3的时候没有关闭过，而2.2之后不再支持双写，所以协议不支持了。

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/issues/12097

**Comment by zzzxx** [comment]
java version "1.8.0_361"

**Comment by zzzxx** [comment]
这个是我2.0.3版本的配置 ，是默认的配置，没有进行修改

**Comment by zzzxx** [comment]
这个是我2.0.3版本的配置 ，是默认的配置，没有进行修改
![图片](https://github.com/alibaba/nacos/assets/22747106/de918695-79e9-44f9-9337-0a2b81d18c5d)
我在升级2.2.3版本是直接使用这个  secret.key  是否可以

**Comment by zzzxx** [comment]
![图片](https://github.com/alibaba/nacos/assets/22747106/5c75eb6b-3027-487b-b342-1a67cbf02867)

**Comment by KomachiSion** [comment]
可以是可以， 但是建议还是用标准的base64编码， 根据上述issue的反馈， 非标准的token的长度可能会影响不同版本的兼容性。
