### ISSUE TITLE
Prometheus get db error due to db check error

### ISSUE THREAD

**Issue by 2022019070014** [alibaba/nacos#12262]
![20240621101525](https://github.com/alibaba/nacos/assets/110577978/11292269-55bf-497d-809d-869b1ac8177e)
![02604](https://github.com/alibaba/nacos/assets/110577978/07deaffe-5f55-4638-a700-800bbbddad08)

because of no data in table config_info_beta , this check alway be false ,  can use "SELECT 1 id  FROM dual "  Instead

**Comment by misakacoder** [comment]
It should just test whether the database connection is normal. If it is not normal, DataAccessException will be thrown, so it doesn't matter what SQL is used.

**Comment by 2022019070014** [comment]
> It should just test whether the database connection is normal. If it is not normal, DataAccessException will be thrown, so it doesn't matter what SQL is used.

it throws exception  if there is no data in the table

![20240625121602](https://github.com/alibaba/nacos/assets/110577978/967b331f-27a7-4b2e-8743-6f382eb90f0d)

**Comment by misakacoder** [comment]
when the query result is empty, the method jdbcTemplate.queryForMap will throw an exception, but try catch handles the exception.

this is a screenshot of the code running in the develop branch. I think the code in your screenshot is not the latest one.

![image](https://github.com/alibaba/nacos/assets/36252937/995046fb-a168-47c6-9878-0b8f104775c4)

**Comment by 2022019070014** [comment]
> when the query result is empty, the method jdbcTemplate.queryForMap will throw an exception, but try catch handles the exception.
> 
> this is a screenshot of the code running in the develop branch. I think the code in your screenshot is not the latest one.
> 
> ![image](https://private-user-images.githubusercontent.com/36252937/342598744-995046fb-a168-47c6-9878-0b8f104775c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyOTg2MDYsIm5iZiI6MTcxOTI5ODMwNiwicGF0aCI6Ii8zNjI1MjkzNy8zNDI1OTg3NDQtOTk1MDQ2ZmItYTE2OC00N2M2LTk4NzgtMGI4ZjEwNDc3NWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA2NTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMDM0YzUzNjE2NTQ5NWNlZGQyNzJkYzU5MmJjY2Q0OWVmNTg2YWU4YWU3MTNhODg4MTE0NjVlOGM3YWY0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pr2hM0l_YlaRUao555N3dW7IX94J3raPhmg_3lDk-F0)

thanks ,this bug was fixed in latest version ~_~
