### ISSUE TITLE
使用namingservice注册实例注销实例，发现比如A服务无法注销B服务，这个是正常情况吗？

### ISSUE THREAD

**Issue by bubb1eP** [alibaba/nacos#12269]
`public Boolean get(String data) {

        CustomerServiceInstance customerServiceInstance = JSON.parseObject(data, CustomerServiceInstance.class);
        boolean isOnline = YesNoEnum.YES.getCode().equals(customerServiceInstance.getIsOnline());
        try {
            NamingService namingService = nacosServiceManager.getNamingService();

            if (isOnline) {
                Instance instance = new Instance();
                instance.setMetadata(customerServiceInstance.getMetadata());
                instance.setIp(customerServiceInstance.getHost());
                instance.setPort(customerServiceInstance.getPort());
                instance.setServiceName(customerServiceInstance.getServiceId());
                namingService.registerInstance(customerServiceInstance.getServiceId(), instance);
                log.info("服务上线成功data：{}", data);
            } else {
                namingService.deregisterInstance(customerServiceInstance.getServiceId(),
                        customerServiceInstance.getHost(),
                        customerServiceInstance.getPort());
                log.info("尝试注销服务实例：服务名={}, IP={}, 端口={}", customerServiceInstance.getServiceId()
                        , customerServiceInstance.getHost(), customerServiceInstance.getPort());
                log.info("服务下线成功data：{}", data);
            }
        } catch (NacosException e) {
            log.error("服务注册失败data：{} error:{}", data, e.getErrMsg());
            return false;
        }
        return true;
    }
    `

**Comment by KomachiSion** [comment]
正常，非持久化实例只有注册服务的客户端才能注销其注册的服务实例。

否则不是别人写个bug，给你全注销了。。。
