### ISSUE TITLE
ConditionDistributedEmbedStorage这块的逻辑是不是存在问题？

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#12273]
public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
        return DatasourceConfiguration.isEmbeddedStorage() && !EnvUtil.getStandaloneMode();
    }
isEmbeddedStorage的取值就是EnvUtil.getStandaloneMode()啊，为什么要这样写？？？
![Clip_2024-06-22_22-20-20](https://github.com/alibaba/nacos/assets/51878514/8cb3ed1e-7c07-4e51-8586-9a0a4d9676ee)
![Clip_2024-06-22_22-20-34](https://github.com/alibaba/nacos/assets/51878514/2565789a-471f-46e7-afda-6230d6b49f5f)

**Comment by MangerLe** [comment]
![Clip_2024-06-22_22-25-34](https://github.com/alibaba/nacos/assets/51878514/69dcb4ff-0c8c-40dc-872a-984f33dfaef6)
 这个是不是也不需要后面重复的去判断了？？

**Comment by KomachiSion** [comment]
有区别， 默认值是standalonemode， 但是集群模式时也可以指定derby数据库作为存储， 此时会由于设置的不同，导致虽然不是standalone， 但是isEmbeeded=true

**Comment by MangerLe** [comment]
> 有区别， 默认值是standalonemode， 但是集群模式时也可以指定derby数据库作为存储， 此时会由于设置的不同，导致虽然不是standalone， 但是isEmbeeded=true

你的意思是 会导致isEmbeddedStorage的取值和EnvUtil.getStandaloneMode()取值不一样？？  现在看起来这两个的取值是一样的 所以没理解

**Comment by KomachiSion** [comment]
bin/startup.sh -p embedded

这样启动的时候不加standaone，就会以集群模式启动EmbeddedStorage。

此时getStandaloneMode和isEmbeddedStorage不一致。

**Comment by MangerLe** [comment]
> 时getStandaloneMode和isEmbeddedStorage不一致

明白了，谢谢。打扰您了！
