### ISSUE TITLE
After the NamingService shutdown, there are still related threads remaining 停止NamingService后仍然有相关线程残留

### ISSUE THREAD

**Issue by cfdou** [alibaba/nacos#12278]
**Describe the bug**
Use Namingservice to get the instance information, and call shutdown after the use is over, but there are still threads left. I'm not sure if it's a bug or if it's because I'm using it incorrectly
使用Namingservice获取实例信息，使用结束后调用shutdown，但是还有线程残留。我不确定这是不是bug，或者这是因为我的使用方式不正确

**Expected behavior**
When shutdown is called, all related threads can be terminated
调用shutdown后，所有相关的线程都能结束

**Actually behavior**
After the shutdown is called, there are still two threads
调用shutdown后，仍然存在两个线程
![image](https://github.com/alibaba/nacos/assets/93538514/79502b87-8da6-4d2c-a266-a7aebbff1ca0)

**How to Reproduce**
1. Create a NamingService using the NamingFactory
2. Call shutdown to stop the Namingservice 
3. Use visualvm to see what threads are running
```java
Properties properties = new Properties();
properties.put(PropertyKeyConst.SERVER_ADDR, "server_addr");
properties.put(PropertyKeyConst.NAMESPACE, "namespace");
NamingService namingService = NamingFactory.createNamingService(properties);
List<Instance> allInstances = namingService.getAllInstances("service_name");
namingService.shutDown();
``` 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Version: nacos-server 2.1.0, nacos-client 1.4.1 nacos-api 1.4.1
 - Module:  naming
 - SDK: original

**Comment by KomachiSion** [comment]
事件通知机制是共享的，同一个类型的事件线程是共享的， 如果关闭其中一个客户端实例就关闭事件线程，可能影响其他客户端的订阅。

仅有这2～3个线程并不影响。

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/blob/affb57fa2e90c0dcf17446ac9290cf8509eac14a/common/src/main/java/com/alibaba/nacos/common/notify/NotifyCenter.java#L130
---
建议只有你确保 shutdown 的时候，你所有的 nacos-client 都正常关闭了，才可以调用
