### ISSUE TITLE
nginx 配置后 /nacos 跳转异常，502

### ISSUE THREAD

**Issue by CxistHans** [alibaba/nacos#12272]
**Describe the bug**
如题

**Expected behavior**
希望 /nacos 的时候能正常访问

**Actually behavior**
访问
http://nacos.example.com:13000/nacos 的时候，被调整到 http://nacos.example.com/nacos
端口消失了，并且 页面 502

**How to Reproduce**

nginx 配置:
```conf
server {
    listen 13000;
    server_name nacos.example.com ;
    location / {
       resolver 127.0.0.11;
       set $nacos "nacos";
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_pass http://example-base-$nacos:8848; # This uses the upstream directive definition to load balance
    }
}
```
访问
http://nacos.example.com:13000/nacos 的时候
被重定向到 http://nacos.example.com/nacos
1. 端口消失了
2.并且 页面 502

**Desktop (please complete the following information):**
 - Version v2.3.2

**Comment by KomachiSion** [comment]
nginx的设置问题不在nacos社区的解决访问内，如确认直接访问时可以的话， 那么请自行解决nginx配置问题。

**Comment by CxistHans** [comment]
@KomachiSion 没有任何方向？或者提示？

**Comment by KomachiSion** [comment]
> @KomachiSion 没有任何方向？或者提示？只是加了个 set $nacos "nacos"; 如果是:
> 
> ```yaml
> server {
>     listen 13000;
>     server_name nacos.example.com ;
>     location / {
>        resolver 127.0.0.11;
>        proxy_set_header Host $host;
>        proxy_set_header X-Real-IP $remote_addr;
>        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>        proxy_pass http://example-base-nacos:8848; # This uses the upstream directive definition to load balance
>     }
> }
> ```
> 
> 是可行的

当然，你修改的nginx设置导致失效了，当然是自行解决，社区不负责答疑nginx的，也做不到答疑nginx的配置。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
