### ISSUE TITLE
nacos在k8s部署，是否可以选择无状态服务

### ISSUE THREAD

**Issue by xhrg** [alibaba/nacos#12275]
nacos部署3个节点的集群，生产环境，在k8s中，是否可使用无状态服务的pod。

**Comment by KomachiSion** [comment]
建议不要，因为nacos本身是有状态的。无状态启动可能会导致一定的数据不一致风险。

**Comment by KomachiSion** [comment]
当然如果您充分理解nacos的运行原理，能够使用无状态pod启动时出现异常时快速解决并维护数据，任何方式启动都行。
