### ISSUE TITLE
nacos server2.3.0 开启了鉴权后，nacos client1.1.4无法通过配置username和password通过鉴权

### ISSUE THREAD

**Issue by shllove** [alibaba/nacos#12287]
nacos server2.3.0 开启了鉴权后，nacos client1.1.4无法通过配置username和password通过鉴权
由于老项目不能直接升级，老项目springboot为1.5版本，如何使老的nacos client可以正常访问 nacos服务？

**Comment by KomachiSion** [comment]
nacos 1.2.0开始支持username和password鉴权， 之前的版本不支持，请升级版本（客户端）
