### ISSUE TITLE
2.2.1、2.2.2、2.2.3、2.2.4版本，在达梦数据库下，更新配置信息，提示违反唯一性约束

### ISSUE THREAD

**Issue by yanborer** [alibaba/nacos#12289]
数据库：达梦8
Nacos：2.2.3
操作：更新配置信息时，提示违反唯一性约束。
检查：
1、检查Nacos运行日志发现，违反的异常是：DataIntegrityViolationException 。
2、检查Nacos源码，在2.2.3的tag下，发现捕获的异常是DuplicateKeyException。
3、检查2.2.1、2.2.2、2.2.3、2.2.4的源码，发现捕获的异常都是DuplicateKeyException。
4、自2.3.0开始，对以上两个异常都进行了捕获验证。

https://github.com/alibaba/nacos/blob/45e155f0bc09d5a99070f693613b3c1a5564f00e/config/src/main/java/com/alibaba/nacos/config/server/service/repository/extrnal/ExternalConfigInfoPersistServiceImpl.java#L177

2.2.0版本中，已修复该问题，后续版本中未修复。
#10335

**Comment by KomachiSion** [comment]
请升级版本， 我看最新的代码修改为先查询是否存在，存在则更新，不存在则插入， 而且即使是2.3的版本， 也是进行了异常类型的区分， DuplicateKeyException必定执行更新，DataIntegrityViolationException则是尝试更新。

**Comment by yanborer** [comment]
只能先升级版本了。
但是在信创的安全版服务器上会导致以下异常，在信创的通用版服务器上没有问题：
java.lang.UnsatisfiedLinkError：/tmp/librocksdbjni2509561674859471596.so：failed to map segment from shared object 

检查是因为jraft协议调用服务器的动态链接库，很多信创的厂商都对nacos依赖的动态链接库进行了重构，保证在安全版服务器上正常使用。

**Comment by yanborer** [comment]
只能先升级版本了。
但是在信创的安全版服务器上会导致以下异常，在信创的通用版服务器上没有问题：
java.lang.UnsatisfiedLinkError：/tmp/librocksdbjni2509561674859471596.so：failed to map segment from shared object 

检查是因为jraft协议调用服务器的动态链接库，很多信创的厂商都对nacos依赖的动态链接库进行了重构，保证在安全版服务器上正常使用。
