### ISSUE TITLE
[Warning] Accepted a connection with deprecated protocol 'TLSv1.1' 

### ISSUE THREAD

**Issue by lliuql** [alibaba/nacos#12284]
**Describe the bug**
SHOW VARIABLES LIKE 'log_error';
log_error	./mysql102.err

`2024-05-24T17:17:52.603981Z 92550 [Warning] Accepted a connection with deprecated protocol 'TLSv1.1' for account `nacos`@`%` from host `192168.10.113`. Client supplied username `nacos``

I hope to make this warning disappear. No special treatment was done, just started nacos on a single machine

**Expected behavior**
I hope this warning does not appear.

**Actually behavior**
There is this warning now.
**How to Reproduce**
SHOW VARIABLES LIKE 'log_error';
less log_error	./mysql102.err

**Desktop (please complete the following information):**
  - OS: CentOS 7
  - Version: nacos-server 1.4.0

**Additional context**

**Comment by KomachiSion** [comment]
nacos use new mysql jdbc already, please setting your jdbcurl to open new TLS version replace the default TLS version.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
