### ISSUE TITLE
The Nacos server is version 2.2.3. After enabling authentication, newly registered users cannot use it for service registration, but user nacos can

### ISSUE THREAD

**Issue by shllove** [alibaba/nacos#12286]
The Nacos server is version 2.2.3. After enabling authentication, newly registered users cannot use it for service registration, but user nacos can.

nacos服务端为2.2.3版本，在开启认证后，新注册的用户不能用来进行服务注册，但用户nacos可以

由于我们有老的springboot（版本为1.5），对于老版本使用nacos，不支持分组和命名空间的特性，所以没有升级前只能先采用public命名空间，但是开启认证后，无法使用自定义用户进行注册

请问这个有新版本会进行解决吗？ 目前老的springboot升级难度较大，期待回复

The Nacos server is version 2.2.3. After enabling authentication, newly registered users cannot use it for service registration, but Nacos can
Due to our old Spring Boot (version 1.5), using Nacos for the old version does not support grouping and namespace features. Therefore, before upgrading, we can only use the public namespace. However, after enabling authentication, we cannot register using custom users
May I ask if there is a new version that will resolve this issue? At present, upgrading old Springboot is difficult, and we look forward to hearing back.

**Comment by KomachiSion** [comment]
duplicate with #12287
