### ISSUE TITLE
Linux服务器上利用Docker启动nacos，一启动后，nacos占用CPU即超过100%

### ISSUE THREAD

**Issue by 02maple** [alibaba/nacos#12290]
nacos V2.2.3
在Linux服务器上一启动，nacos服务占用cpu即超过百分之百
docker run -d --name nacos --privileged --cgroupns host -e JVM_XMX=512m -e MODE=standalone -e JVM_XMS=512m -e JVM_XMN=256m -p 8848:8848/tcp -p 9848:9848/tcp --restart=always -w /home/nacos nacos/nacos-server:v2.2.3
![image](https://github.com/alibaba/nacos/assets/112541176/8749adc6-f87f-4e50-8d1e-47b6d369f53b)

**Comment by 02maple** [comment]
目前发现，如果停止了jenkins服务，nacos就会恢复正常，如果启动了jenkins，nacos服务占用的cpu会过高

**Comment by CorrectPath** [comment]
我也是这样，但是我根本没有jenkins服务
![屏幕截图 2024-09-04 163830](https://github.com/user-attachments/assets/4fb4b156-8b00-4459-a919-e4b82c49c31d)

**Comment by 02maple** [comment]
> 我也是这样，但是我根本没有jenkins服务 ![屏幕截图 2024-09-04 163830](https://private-user-images.githubusercontent.com/179119218/364619823-4fb4b156-8b00-4459-a919-e4b82c49c31d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNTc5ODAsIm5iZiI6MTczNjI1NzY4MCwicGF0aCI6Ii8xNzkxMTkyMTgvMzY0NjE5ODIzLTRmYjRiMTU2LThiMDAtNDQ1OS1hOTE5LWU0YjgyYzQ5YzMxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwN1QxMzQ4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGFkOTA2NTIzMDQ1NGNhNzNmZWQ1OGEwNzA0NjZiNDU2ZjIwYmJlMDY1ZmI5OTEzYzRiYzkxYzg2MDIzNjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWc-TvGEbzJIIj21j7QVB-Ve30XLH3Rn4_O06fRnLbk)

你可以看下是不是内存占满了，我后面发现是自己的服务器内存跑满了，就会cpu占用很高
