### ISSUE TITLE
nacos uses vip+nginx load balancing to cause a client to appear  UNAVAILABLE: Network closed for unknown reason

### ISSUE THREAD

**Issue by tanglinyan** [alibaba/nacos#12297]
**Describe the bug**
nacos uses vip+nginx load balancing to cause a client to appear UNAVAILABLE: Network closed for unknown reason
This works when accessing specific nacos nodes, but does not work when load balancing via nginx
Is nacos http service stateless, and if so, what about grpc

UNAVAILABLE: Network closed for unknown reason appears once every 3 seconds

hosts.conf
192.168.4.151 yanfa-nacos1
192.168.4.145 yanfa-nacos2
192.168.4.146 yanfa-nacos3

**Desktop (please complete the following information):**
 - OS: macos
 - Version nacos-server-2.3.2
 - SDK spring.cloud.alibaba.version:2023.0.1.0,dubbo:3.2.12

**Additional context**
<img width="1100" alt="image" src="https://github.com/alibaba/nacos/assets/33612347/0d370221-6be1-42e7-8e19-cd6b7981305e">

<img width="1130" alt="image" src="https://github.com/alibaba/nacos/assets/33612347/32b497c8-c601-490f-bb50-704fed45cb67">

<img width="1831" alt="image" src="https://github.com/alibaba/nacos/assets/33612347/65e24466-02e8-484f-909f-57e1ccb6a2d9">

**Comment by KomachiSion** [comment]
It should be your nginx or vip will close the connection with an interval.

Please make sure your nginx and vip transport by tcp but not http and https. And make sure them will not reuse and redistribution connection with any dimensions.

I suggest you try to connect nacos server directly, if connect directly is ok. there must be some config problem in vip or nginx to close connection each 3 seconds.

**Comment by tanglinyan** [comment]
It is normal to use VIP or connect to one nacos service
The above error occurs with nginx load balancing
My related configuration is provided above

**Comment by tanglinyan** [comment]
I hope you can help me. This problem has been bothering me for a long time

**Comment by KomachiSion** [comment]
stream {

    upstream grpc_server {
       server 127.0.0.1:9848;
    }

    server {
        listen 9080 so_keepalive=on;
        limit_conn connectRemoteLimit 32;
        limit_conn connectRemoteLimitAll 9000;
        proxy_responses 1;
        proxy_timeout 20s;
        proxy_pass grpc_server;

    }
}

I use this configuration in nginx work well. you can try it. If can't work well. I suggest you find out which configuration make the connection closed by nginx or vip by yourself.

**Comment by tanglinyan** [comment]
Thank you very much. I'll try it your way.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.

**Comment by xujunhua555** [comment]
> ```
> stream {
> 
>     upstream grpc_server {
>        server 127.0.0.1:9848;
>     }
> 
>     server {
>         listen 9080 so_keepalive=on;
>         proxy_responses 1;
>         proxy_timeout 20s;
>         proxy_pass grpc_server;
> 
>     }
> }
> ```
> 
> 我在nginx中使用这个配置，效果很好，你可以试试，如果效果不好，建议你自己去看看是哪个配置让nginx或者vip关闭了连接。

用了这个之后最后没有再出现这个问题了吗？
