### ISSUE TITLE
数据源替换为postgresql后导入配置时报错

### ISSUE THREAD

**Issue by 15971557251** [alibaba/nacos#12295]
使用postgresql数据源替换mysql  导入配置时报错,数据源配置如下：
spring.datasource.platform=postgresql
spring.sql.init.platform=postgresql

db.pool.config.driverClassName=org.postgresql.Driver

db.url.0=jdbc:postgresql://127.0.0.1:5432/nacos?targetServerType=primary&tcpKeepAlive=true&reWriteBatchedInserts=true&ApplicationName=nacos_java
db.user.0=postgres
db.password.0=postgres

报错信息如下：
caused: serialize page error,
dataId=,
group=;caused: PreparedStatementCallback;bad SQL grammar[
    SELECT id,
    data_id,
    group_id,
    tenant_id,
    app_name,
    content,
    encrypted_data_key FROM config_info WHERE tenant_id LIKE?LIMIT 0,
    10
];nested exception is org.postgresql.util.PSQLException: ERROR: LIMIT#,
#syntax is not supported 建议：Use separate LIMIT and OFFSET clauses.位置：117;caused: ERROR: LIMIT#,
#syntax is not supported 建议：Use separate LIMIT and OFFSET clauses.位置：117;

**Comment by KomachiSion** [comment]
什么版本？ 是否引入了pg插件？

**Comment by KomachiSion** [comment]
No more response from author for a long time, and current information is not enough to judge problem.
