### ISSUE TITLE
grpc 5s重复注册一次服务，集群之间可以同步数据，但是无法同步客户端的lastRenewTime

### ISSUE THREAD

**Issue by bwangll** [alibaba/nacos#12299]
**Describe the bug**
客户端5s进行一次重复注册，每次reversion加1，非责任节点会verify失败，发起同步，但是同步不更新lastRenewTime，只有verify成功才会执行client.setLastRenewTime();
但是集群同步是5s进行一次，而重复注册也是5s进行一次。导致无法更新lastRenewTime，最终3分钟后被客户端检查器(ExpiredClientCleaner)断开连接。下次同步就会正常。
最终导致订阅3分钟出现一次节点下线。

Client 5s to repeat the registration once, each time the reversion plus 1, non-responsible nodes will verify the failure to initiate the synchronization, but the synchronization does not update the lastRenewTime, only verify the success of the execution of client.setLastRenewTime();
But cluster synchronization is done once in 5s, and repeat registration is also done once in 5s. As a result, lastRenewTime cannot be updated, and eventually disconnected by ExpiredClientCleaner after 3 minutes. Next time the synchronization works fine.
**Expected behavior**
集群之间同步客户端数据时，要更新client的lastRenewTime。
在DistroClientDataProcessor#upgradeClient方法中增加client.setLastUpdatedTime();

To update the lastRenewTime of client when synchronizing client data between clusters.
Add client.setLastUpdatedTime(); in DistroClientDataProcessor#upgradeClient method.

**Comment by KomachiSion** [comment]
为什么客户端需要每5s进行一次重新注册，用法可能存在问题。

**Comment by KomachiSion** [comment]
另外我读了最新版本的代码， 当你主动做重复注册时， 责任节点会revision+1， 同时出发主动同步， 主动同步到其他节点时， 其他节点也会出发了setRevision操作， 因此在verify的时候，会发现revision一致，从而更新时间。

及时有一次因为异步导致verify不通过，触发重新推送，也会在下一次verify时通过。所以不存在问题。
如果您读的代码存在此问题，可以升级版本后重试。

**Comment by bwangll** [comment]
这个逻辑我看到了，主要是5s刷新一次，正好会导致每次版本号都增加，永远verify失败，然后同步也不更新时间。3分钟断开一次。用法上确实存在问题，刷新太频繁。

**Comment by nkorange** [comment]
@bwangll 你的Nacos版本是多少？
