### ISSUE TITLE
nacos 服务注册后老是自动掉，同样的配置，子工程的网关不会..人已经麻了

### ISSUE THREAD

**Issue by cy-6359** [alibaba/nacos#12292]
![1719415850874](https://github.com/alibaba/nacos/assets/75932412/c55d2619-3b98-463b-bb14-5ea2bcf399aa)

开了debug模式好像也没有看出什么问题

**Comment by cy-6359** [comment]
![1719415850874](https://github.com/alibaba/nacos/assets/75932412/c415de6b-9ef7-49ec-8474-63fb1b969d8a)
启动服务后，可以活半分钟作用，然后就健康状态false，然后就掉... 最后直接被咔掉  java项目

**Comment by cy-6359** [comment]
docker run -p 8848:8848 -p 9848:9848 --name Nacos \
   -e MODE=standalone \
   -e SPRING_DATASOURCE_PLATFORM=mysql \
   -e MYSQL_SERVICE_HOST=host.docker.internal \
   -e MYSQL_SERVICE_PORT=3333 \
   -e MYSQL_SERVICE_DB_NAME=nacos \
   -e MYSQL_SERVICE_USER=root \
   -e MYSQL_SERVICE_PASSWORD=Cy635950334! \
   -d nacos/nacos-server:v2.3.2-slim
   
   这是启动Nacos命令， macOS

**Comment by cy-6359** [comment]
问题已解决...依赖问题。

**Comment by LL3706** [comment]
具体是啥依赖问题，冲突了吗
