### ISSUE TITLE
以应用为中心隔离配置问题

### ISSUE THREAD

**Issue by zhuchunlai** [alibaba/nacos#123]
查看Nacos代码和存储设计发现，整体是以DataId、Group和Tenant来隔离配置的，系统中有设计appName，但发现隔离中并没有使用它，关于此设计有一些疑问，按实际业务场景来看，整体应该是以app来隔离配置，在此之上支持配置的继承与覆盖，想了解下Nacos关于这块的设计考量和最佳实践。谢谢

**Comment by yfh0918** [comment]
nacos的配置粒度是文件级别 一般dataId就是配置文件名，groupId的配置粒度一般大于等于应用名，也可以配成应用名，可以是应用名+其他的组合名称，另外如果是云原生支持的话就需要用到租户的概念 就是Tenant也可以认为是namespace
