### ISSUE TITLE
相同永久实例在不同nameSpace下面健康检测问题

### ISSUE THREAD

**Issue by chen10038** [alibaba/nacos#12301]
因为测试环境一直公用的同一套nacos   所以每次提测nameSpace会新建。
nacos 版本：2.3.1
nacos-client版本：2.2.1
springboot版本：2.7.15
配置： spring.cloud.nacos.discovery.ephemeral=false   //注册永久实例
步骤：1、 创建nameSpace1 ,注册服务和实例到nameSpace1   ，查看nacos服务列表页面，服务正常注册。健康状态为true。正常。
           2、杀掉服务。再次查看nameSpace1的服务列表页面，健康状态为false。正常
           3、创建nameSpace2，修改服务配置（只修改了注册的nameSpace）,其他配置完全一致。重启服务。
           4、查看nameSpace2的服务列表   服务正常注册，实例显示健康。查看nameSpace1的服务列表，服务实例也显示健康。
           5、再次杀掉服务。nameSpace1的实例健康状态显示false   nameSpace2的健康状态显示true.。 nameSpace2网关依旧能转发到
  被杀掉的服务上面。
nameSpace1的服务状态：
![image](https://github.com/alibaba/nacos/assets/32610642/5aea52c2-91d3-4e21-822c-b31a72276951)

nameSpace1的实例状态
![image](https://github.com/alibaba/nacos/assets/32610642/8ece1390-b7b1-43bf-ae0c-90fa261a5b26)

nameSpace2的服务状态
![image](https://github.com/alibaba/nacos/assets/32610642/b7953e02-650e-4d37-9f64-aee922ba6c30)

nameSpace2的实力状态：
![image](https://github.com/alibaba/nacos/assets/32610642/7f372179-f9e0-4421-a3df-0323ba298ad5)

查看nacos日志没有发现具体问题。请帮忙排查一下问题。

PS: 直接使用openApi注册服务和实例也存在该问题。 （永久实例）。

**Comment by KomachiSion** [comment]
两个实例是出了namespace以外，其他全一样吗？

**Comment by chen10038** [comment]
是的。 只是在application文件中   修改了nameSpace配置

**Comment by chen10038** [comment]
![image](https://github.com/alibaba/nacos/assets/32610642/83735ebe-bf0c-4900-a469-48b6e833a5c9)

![image](https://github.com/alibaba/nacos/assets/32610642/0ebd27ed-b602-4d16-b3a6-24d7df6d0f2c)


是不是这引起的问题 ？ beat对象不区分nameSpace。   第一个nameSpace对应的Beat对象执行完检查任务后   第二个就不执行了

**Comment by chen10038** [comment]
看代码确实  最开始所有的任务都是顺序执行的，   第二个nameSpace因为key已经cancel过      最后在PostProcessor#run中不会执行具体tcp连接逻辑     所以后面nameSpace下面的服务没法更新 。  是不是只需要修改 Beat对象的toString方法  就可以解决？当时toString  没有加nameSpace是出于什么考虑？

**Comment by chen10038** [comment]
![image](https://github.com/alibaba/nacos/assets/32610642/c0b29052-c0d6-4197-8c7f-abac95b32d77)

我用arthus 反编译并加载代码 ，加了日志看了一下。   其他的nameSpace的服务检测在这里都被拦截了 ， 我怀疑就是instance没有正常结束。尝试去掉代码块中的return, 再看nacos后台 ，所有nameSpace下的服务状态都符合了预期，   但是不确定这样会引起的其他问题。 希望还是能协助帮找到一个更好的解决方案。

**Comment by chen10038** [comment]
![image](https://github.com/alibaba/nacos/assets/32610642/4114b459-e91c-48b3-bb95-2878ae0f36ac)

另外  这的TimeOutTask代码里面需不需要调用   instance.finishCheck(); ？

**Comment by chen10038** [comment]
我感觉我发现了问题  Beat对象的toSring  不区分nameSpace
![image](https://github.com/alibaba/nacos/assets/32610642/4f446a1b-a5ab-4d60-a4d2-ccfd2ec4ade0)


![image](https://github.com/alibaba/nacos/assets/32610642/9aad01ca-db7d-4d68-85c0-c91420a92ad3)
不同nameSpace下如果多线程同时执行    有一个key就会被取消

![image](https://github.com/alibaba/nacos/assets/32610642/34c7036d-f4e7-44df-84b5-ddca1cf748f6)


因为最开始重置了instance开始标志   丢失key以后状态一直没办法重置回去    所以后续的检测其实就一直未进行了    
就形成了最上面评论的那个现象  。


我拉取源码进行了toString方法修改   进行验证   最终符合了预期效果。

请协助看一下这样修改有没有其他问题
