### ISSUE TITLE
版本2.2.3开启了鉴权之后还是发现控制台获取命名空间列表的接口没有鉴权的问题

### ISSUE THREAD

**Issue by zhangyq233** [alibaba/nacos#12309]
**Describe the bug**
开启鉴权之后发现这个接口 ip/nacos/v1/console/namespaces 可以随意访问，无需用到token  

**Expected behavior**
肯定是不能访问，提示报错才对

**Actually behavior**
返回了当前的所有命名空间信息

**How to Reproduce**
1. 配置文件开启鉴权
2. 浏览器访问 http://ip:port/nacos/v1/console/namespaces

**Desktop (please complete the following information):**
 - OS: Centos
 - Version: nacos-server 2.2.3

**Comment by KomachiSion** [comment]
命名空间列表是一个public接口，类似获取云上环境支持哪些region和哪些产品。目前没有加上鉴权的计划。

**Comment by zhangyq233** [comment]
> 命名空间列表是一个public接口，类似获取云上环境支持哪些region和哪些产品。目前没有加上鉴权的计划。

请问还有哪些是 public 接口，是否有对应的文档描述？
