### ISSUE TITLE
How to use Jasypt to encrypt the password in Nacos

### ISSUE THREAD

**Issue by mitht** [alibaba/nacos#12303]
SpringBoot 2.7.10

```bash
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2021.0.4.0</version>
</dependency>

<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2021.0.4.0</version>
</dependency>

dependency>
    <groupId>com.github.ulisesbocchio</groupId>
    <artifactId>jasypt-spring-boot-starter</artifactId>
    <version>3.0.3</version>
</dependency>
````

The bootstrap.properties configuration is as follows:

jasypt.encryptor.password=123456
jasypt.encryptor.algorithm=PBEWithHmacSHA512AndAES_128

spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.username=admin
spring.cloud.nacos.discovery.password=ENC(qTE6iEN1qFBmCWeOeCmxoJmlrWPhBZS9QZ3JlAI)

Using the encrypted password to connect to Nacos results in a 403 error.

com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg-user not
found! , dataId-app-application-dev.yml,group-DEFAULIGROUP,tenant=1234dddddddddd

**Comment by KomachiSion** [comment]
Please submit issue to spring cloud alibaba.

Nacos only recived the configuration. jasypt decode password is spring logic handler.
