### ISSUE TITLE
使用ceph块存储，启动nacos时报错

### ISSUE THREAD

**Issue by wangyd1988** [alibaba/nacos#12300]
使用ceph块存储创建nacos时，nacos报此错误，请帮忙解决，谢谢
![image](https://github.com/alibaba/nacos/assets/81305854/7fb9b5d9-03db-4980-803b-173e1e0388a1)

**Comment by KomachiSion** [comment]
无法创建本地derby数据库， 环境问题请自行解决，以保证nacos有权限进行本地文件的创建，修改和读取。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
