### ISSUE TITLE
support openapi for get all namespace for naming

### ISSUE THREAD

**Issue by shalk** [alibaba/nacos#12302]
**Is your feature request related to a problem? Please describe.**
get all namespace for naming can not get by openapi. 

Meanwhile the `/nacos/v2/console/namespace/list` is relate with config and database 

**Describe the solution you'd like**
I want to add  `/nacos/v2/naming/namespace/list` to support openapi for  naming .
This is can be implement in  NamespaceControllerV2    by `ServiceManager.getInstance().getAllNamespaces()` 

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
namespace is a core content, not naming namespace. So not add api for naming such as `/nacos/v2/naming/namespace/list`

I think this issue can be discuss with #12191
