### ISSUE TITLE
feature: Provide several commonly used implementations of NacosConfigConverter

### ISSUE THREAD

**Issue by lw5946** [alibaba/nacos#1230]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
The Nacos console can use a variety of configuration formats to create new configurations, such as properties, json, yaml, and so on.
but `Listener` just gives me configuration data of `String` type.
I saw `NacosConfigConverter` in the source code, but no specific functionality was implemented.

### Describe what you expected to happen
I can convert configurations in different formats into objects I need through `NacosConfigConverter`.

**Comment by nkorange** [comment]
Currently you can use [nacos-spring](https://github.com/nacos-group/nacos-spring-project) to recognize configurations in .properties file.

**Comment by chuntaojun** [comment]
I will solve it

**Comment by chuntaojun** [comment]
你的意思是由nacos-spring-project提供自动读取配置并根据参数转为相应对象的功能？

**Comment by lw5946** [comment]
> 你的意思是由nacos-spring-project提供自动读取配置并根据参数转为相应对象的功能？

@chuntaojun  最好是nacos直接提供此功能吧，而且最好不要用新的参数，file-extension 参数就可以知道是什么格式的配置

**Comment by KomachiSion** [comment]
I think consider type in client is not reasonable, ui provide type is only help user and console to reformat and check format.

But for client, it just is string, and call back to your listener, you can do parse in your listener, if you want to understand the type, you can make the dataId as .yml or .properties and so on.
