### ISSUE TITLE
热更新配置触发listener阻塞

### ISSUE THREAD

**Issue by knowyi** [alibaba/nacos#12306]
Yesterday at 16:13, the production team made modifications to the Nacos configuration. At that time, during peak business hours, they kept prompting that the listener was not finished yet, will try next time， And afterwards, the service instance survived but was not available, and the final restart did not prompt the listener to be not finished yet, will try next time。 I'm not sure if the unavailability of the service was caused by this error. Today, in a pressure test scenario, I returned to modify the nacos configuration and finally reproduced this error. However, the service can still request normally

场景描述：
昨天16：13生产修改nacos配置，当时业务高峰期修改后一直提示listener is not finish yet,will try next time，并且之后服务实例存活，但是不可用，最终重启不在提示listener is not finish yet,will try next time。不确定服务不可用是否是这个错误导致。今天在压测场景下，不停修改nacos配置，触发热更新，最终重现这个报错，服务目前还是可以正常请求。
![image](https://github.com/alibaba/nacos/assets/7392434/a1ff58da-204f-482e-9f92-f36557c4672c)

压测场景 jstack打出了线程堆栈 
[thread_dump.txt](https://github.com/user-attachments/files/16082627/thread_dump.txt)

**How to Reproduce**
Simulate high concurrency scenarios during pressure testing and continuously modify the nacos configuration to generate heat updates

**Desktop (please complete the following information):**
 - OS:  Centos
 - Version [ nacos-server 2.2.3]
 - Module  config
 - SDK spring-cloud-alibaba-nacos 2.2.9.RELEASE

**Comment by knowyi** [comment]
我在这个issue https://github.com/alibaba/nacos/issues/10033 也看到了相同的问题 不知道是否已经解决？

**Comment by KomachiSion** [comment]
listener是由您自行实现的， 如果listener内部有阻塞操作，需要您自行进行阻塞的异步化处理或消除阻塞。此问题非Nacos的问题。

如果您的listener是由应用框架实现的， 请提交issue到应用框架中询问是否修复。

**Comment by knowyi** [comment]
我没有明白这个问题，我用的是spring-cloud-alibaba-nacos 你的意思是@RefreshScope的问题吗？

**Comment by knowyi** [comment]
> listener是由您自行实现的， 如果listener内部有阻塞操作，需要您自行进行阻塞的异步化处理或消除阻塞。此问题非Nacos的问题。
> 
> 如果您的listener是由应用框架实现的， 请提交issue到应用框架中询问是否修复。

我没有明白这个问题，我用的是spring-cloud-alibaba-nacos 你的意思是@RefreshScope的问题吗？
