### ISSUE TITLE
Problems with upgrading from nacos 2.0.1 to the new version

### ISSUE THREAD

**Issue by mimishy2000** [alibaba/nacos#12307]
I am currently using nacos version 2.0.1, and I am now planning to upgrade to a later version to accommodate the features of Spring Boot.
When I access the configuration list of the web console after upgrading from 2.0.1 to 2.3.2, the following error message occurs, which prevents me from obtaining and viewing the configuration properly.

![image](https://github.com/alibaba/nacos/assets/30401670/b6f1a8c4-03e4-47fe-8a5e-b861f505847a)

I then tried to switch to version 2.1.2, and the web console's configuration list did not display a full list of namespaces.Which version of this bug was fixed after 2.1.2?

![image](https://github.com/alibaba/nacos/assets/30401670/54a73a09-b071-4181-9802-3f03ab911066)

**Comment by mimishy2000** [comment]
I have created dozens of namespaces, but the configuration list interface does not fully display all of them, preventing me from viewing other namespaces and managing configuration information.

**Comment by wuchubuzai2018** [comment]
从2.1开始，数据库里面的表字段有变化，好像是新增了一个加密key的字段，建议兄弟比对一下最新版本的SQL表结构和2.1差了那几个字段，补充一下。直接升级会因为字段缺失导致失败的，而且错误提示也是这个原因

**Comment by KomachiSion** [comment]
https://nacos.io/docs/next/manual/admin/upgrading/

2.3.X same with 2.4.X

**Comment by mimishy2000** [comment]
> 从2.1开始，数据库里面的表字段有变化，好像是新增了一个加密key的字段，建议兄弟比对一下最新版本的SQL表结构和2.1差了那几个字段，补充一下。直接升级会因为字段缺失导致失败的，而且错误提示也是这个原因

的确是这样，新版本多了ENCRYPTED_DATA_KEY这个字段，我新增这个字段就没出现访问异常了。
