### ISSUE TITLE
nginx nacos 模块 贡献到 nacos-group

### ISSUE THREAD

**Issue by zhwaaaaaa** [alibaba/nacos#12317]
[nginx-nacos-module](https://github.com/zhwaaaaaa/nginx-nacos-upstream) 目前是我的人个项目，关于项目贡献到社区，之前在线下和@KomachiSion有过初步的沟通 。

现在申请把它贡献到nacos社区 ，项目贡献到社区要走什么流程？

#### nginx-nacos-module 简介：
nginx nacos module 是一个 nginx 订阅 nacos 的插件。

nginx 订阅 nacos，实现 服务发现 和 配置 动态更新。支持 nacos 1.x 的  udp 协议 和 nacos 2.x 的 grpc 协议 

nginx 订阅 nacos 获取后端服务地址，不用在 upstream 中配置 ip 地址，后端服务发布下线自动更新。
nginx 订阅 nacos 获取配置，写入 nginx 标准变量。（配置功能，只支持 grpc 协议）。

**Comment by KomachiSion** [comment]
欢迎

请确认该项目是您的个人项目，而非公司项目。

确认是个人项目的话， 请签署贡献的CLA，https://cla-assistant.io/alibaba/nacos

完成之后可以开始操作迁移仓库了。

**Comment by zhwaaaaaa** [comment]
已经签署

**Comment by zhwaaaaaa** [comment]
点 transfer repository 出现
```
You don’t have the permission to create public repositories on nacos-group
```

**Comment by KomachiSion** [comment]
> 点 transfer repository 出现
> 
> ```
> You don’t have the permission to create public repositories on nacos-group
> ```

发起了一个邀请，你看下邮件或者github的站内信，加入一下。
