### ISSUE TITLE
nacos sync distroData fail

### ISSUE THREAD

**Issue by linjikun** [alibaba/nacos#12314]
**Describe the bug**
nacos内存溢出重启后报错 Send request fail, response = DistroDataRequest{header={},requestId='null'}, retryTime= 1,errorMessage= java.util.concurrent.ExecutionException:io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: message exceeds maximun size: 10485760: 19140174

open jdk 1.8，nacos-2.2.3

**Comment by KomachiSion** [comment]
这个报错不是内存溢出， 是你的单次请求大小超过了限制，请调整`nacos.remote.server.grpc.sdk.max-inbound-message-size`和`nacos.remote.server.grpc.cluster.max-inbound-message-size` 参数

**Comment by linjikun** [comment]
> 这个报错不是内存溢出， 是你的单次请求大小超过了限制，请调整`nacos.remote.server.grpc.sdk.max-inbound-message-size`和`nacos.remote.server.grpc.cluster.max-inbound-message-size` 参数

已经尝试过，配置这两个参数是无效的，官方的版本提示，这两个是2.3.0之后的参数，我使用的版本是2.2.3，然后看了源码，配置以下两个参数
-Dnacos.remote.client.grpc.maxinbound.message.size=
-Dnacos.remote.server.grpc.maxinbound.message.size=
依旧没有用

**Comment by junechouiscoming** [comment]
@linjikun 我们这边也有这个报错，请问您这两个参数调整成多少了呢？最后报错还是10485760吗？

**Comment by linjikun** [comment]
> @linjikun 我们这边也有这个报错，请问您这两个参数调整成多少了呢？最后报错还是10485760吗？

怎么配置都没有用，最后还是报错达到上限10485760

**Comment by junechouiscoming** [comment]
@linjikun  确定配置对了吗？我这边试了下，改完之后可以生效，下面是启动参数，调到了50M
![image](https://github.com/user-attachments/assets/b335038c-d98c-48a7-bd18-03b5bf87af92)

**Comment by linjikun** [comment]
> @linjikun 确定配置对了吗？我这边试了下，改完之后可以生效，下面是启动参数，调到了50M ![image](https://private-user-images.githubusercontent.com/28861676/348206987-b335038c-d98c-48a7-bd18-03b5bf87af92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzYxNjQsIm5iZiI6MTcyMDc3NTg2NCwicGF0aCI6Ii8yODg2MTY3Ni8zNDgyMDY5ODctYjMzNTAzOGMtZDk4Yy00OGE3LWJkMTgtMDNiNWJmODdhZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzODIxZWE4NTZmYmExODJmYjViYjI2NjdhNzdjOWFmYTMwNjRlZTg5YzJkZGRmODljOThiYjA2NmJhN2VhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQQ3oKVCLrNPw9cX1sByP_-7lca3-8Oro3D5NuLylHQ)
我这边是在application.properties的文件配置的，难道需要在启动参数配置才生效吗

**Comment by linjikun** [comment]
> @linjikun 确定配置对了吗？我这边试了下，改完之后可以生效，下面是启动参数，调到了50M ![image](https://private-user-images.githubusercontent.com/28861676/348206987-b335038c-d98c-48a7-bd18-03b5bf87af92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzYxNjQsIm5iZiI6MTcyMDc3NTg2NCwicGF0aCI6Ii8yODg2MTY3Ni8zNDgyMDY5ODctYjMzNTAzOGMtZDk4Yy00OGE3LWJkMTgtMDNiNWJmODdhZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzODIxZWE4NTZmYmExODJmYjViYjI2NjdhNzdjOWFmYTMwNjRlZTg5YzJkZGRmODljOThiYjA2NmJhN2VhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQQ3oKVCLrNPw9cX1sByP_-7lca3-8Oro3D5NuLylHQ)

你使用的是什么版本的nacos

**Comment by junechouiscoming** [comment]
@linjikun 对的，-D注入，你可以再试试，我在测试环境调成10kb后，稳定复现这个报错。2.2.0的

**Comment by junechouiscoming** [comment]
> 这个报错不是内存溢出， 是你的单次请求大小超过了限制，请调整`nacos.remote.server.grpc.sdk.max-inbound-message-size`和`nacos.remote.server.grpc.cluster.max-inbound-message-size` 参数

@KomachiSion 请问下，这个单次请求是请求什么？会随着时间增大吗？这个值设置大了会有什么问题？现在我们发现这个错可能会导致节点实例数不一致

**Comment by linjikun** [comment]
2.2.3版本，通过-D的方式配置参数后，问题修复
