### ISSUE TITLE
开启鉴权后，在本地用用户名密码配置项目可以启动，但同样配置发到docker后，就无法启动了，一直提示用户名不存在

### ISSUE THREAD

**Issue by lvgitt** [alibaba/nacos#12316]
After enabling authentication, the project can be started locally by configuring the username and password. However, once the same configuration is sent to Docker, it cannot be started and keeps prompting that the username does not exist

[A clear and concise description of what you expected to happen.](nacos-server:v2.3.2)
![image](https://github.com/alibaba/nacos/assets/44693144/9dd39ac7-07e3-4b8c-9424-619d601f1694)
![image](https://github.com/alibaba/nacos/assets/44693144/16eb8927-2735-4f1a-aa05-da8e866cb2f5)

ERROR com.alibaba.nacos.client.config.impl.ClientWorker Line:1032 - [config_rpc_client] [sub-server-error]  dataId=xx-xx-stag.yml, group=DEFAULT_GROUP, tenant=nacos-stag, code=Response{resultCode=500, errorCode=403, message='user not found!', requestId='null'}

**Comment by KomachiSion** [comment]
从描述上看是环境问题或者是应用配置问题：
1. 需要确认运行环境的配置正确，包括连接的nacos集群、用户名密码等
2. 需要确认所连接nacos集群确实存在对应用户名密码。

**Comment by lvgitt** [comment]
> 从描述上看是环境问题或者是应用配置问题：
> 
> 1. 需要确认运行环境的配置正确，包括连接的nacos集群、用户名密码等
> 2. 需要确认所连接nacos集群确实存在对应用户名密码。

是不是其他issue中提到的nacos所在docker中jdk版本的问题？目前jdk版本为openjdk version "1.8.0_402"，
关于这个jdk问题nacos最新版是否能兼容下呢？

**Comment by KomachiSion** [comment]
1. 有可能是jdk的版本问题
2. 无法兼容， 因为sha256算法依赖系统操作，而其操作被封装到jdk中了。如果需要兼容，需要自行完整实现一整套sha算法。完全没必要。

**Comment by KomachiSion** [comment]
另外这个应该是jdk的bug，还是需要jdk社区来修复。

除非jdk发出公告，不再支持此算法，或者仅oracle jdk支持， openjdk不支持。
