### ISSUE TITLE
k8s部署nacos集群后查看日志alipay-jraft.log , protocol-raft.log, naming-raft.log, nacos.log，nacos-cluster.log没有报错，集群节点状态也是UP，但是没有选出来leader和follower

### ISSUE THREAD

**Issue by foreverloveali** [alibaba/nacos#12319]
集群的节点信息只有下面的内容，没有naming信息，没有集群的leader和follower标识
![image](https://github.com/alibaba/nacos/assets/65100093/aa5defac-5185-465e-9480-5adeb10265ec)

**Comment by KomachiSion** [comment]
截图里-0节点就是leader 啊

**Comment by foreverloveali** [comment]
![image](https://github.com/alibaba/nacos/assets/65100093/7210f204-e7d9-4d16-9709-fc77304395d8)
没有这个state字段也是正常的吗？

**Comment by KomachiSion** [comment]
新版本正常， state这个字段早就废弃了。

**Comment by KomachiSion** [comment]
因为新版本中raft不再只有一个group，而是拆分成了4个group，每个raft-group都有独立的leader，state一个字段不能很好的表示leader信息。
