### ISSUE TITLE
nacos2.3.2 修改密码报错

### ISSUE THREAD

**Issue by XuFulLai** [alibaba/nacos#12312]
nacos2.3.2 修改密码报错
![Uploading 1720096744533.jpg…]()

**Comment by HMYDK** [comment]
你的图是不是挂了。。。

**Comment by XuFulLai** [comment]
<img width="1280" alt="Snipaste_2024-07-05_14-39-20" src="https://github.com/alibaba/nacos/assets/91860662/2cc7bd94-a8f0-4357-9d54-557cda2aa809">
<img width="1274" alt="Snipaste_2024-07-05_14-39-47" src="https://github.com/alibaba/nacos/assets/91860662/560a86c2-c69a-4875-bfc1-96053621f1de">
报错图如上

**Comment by KomachiSion** [comment]
请求返回的response payload是什么？

**Comment by pengweizhong** [comment]
把缓存清理一下再试试

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
