### ISSUE TITLE
dubbo and nacos Problems encountered

### ISSUE THREAD

**Issue by xinchungitHub** [alibaba/nacos#1231]
Combining Nacos with dubbo, both microservices have service A interface to call service B. Service B invokes service A interface, and it will report errors if it starts directly.
The error information is as follows:
failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@providers:com.xc.service.app.AppOrderService:1.0.0

Why define an interface as a way of service? Once there are more interfaces, the list of services can't be seen.

**Comment by xinchungitHub** [comment]
And when I set it up
dubbo.reference.com.foo.BarService.check: false
dubbo.reference.check: false
dubbo.consumer.check:  false
dubbo.registry.check:  false

There's only one log that's similar to for loop error reporting.
failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/list. code:404 msg: service not found:

**Comment by nkorange** [comment]
@xinchungitHub The service 'providers:com.xc.service.app.AppOrderService:1.0.0' has to be registered before you query for it.
