### ISSUE TITLE
【UI 页面功能请求】希望为配置列表、服务列表中的命名空间添加排序、检索功能

### ISSUE THREAD

**Issue by WangJincheng4869** [alibaba/nacos#12311]
**Is your feature request related to a problem? Please describe.**
当命名空间较多时，想要找到某个命名空间非常困难。
> When there are many namespaces, it is very difficult to find a certain namespace.

**Describe the solution you'd like**
1. 为配置列表、服务列表中的命名空间添加排序、检索功能。
2. 配置列表、服务列表中命名空间和列表采用左右解构布局
3. 可以为命名空间添加分组（仅为了方便管理），可以在配置列表、服务列表中使用 tree 结构显示。

> 1. Add sorting and retrieval functions to the namespaces in the configuration list and service list.
> 2. The namespaces and lists in the configuration list and service list adopt a left and right deconstruction layout
> 3. Grouping can be added to namespaces (for ease of management only), and tree deconstruction can be used to display in configuration lists and service lists.

**Describe alternatives you've considered**
为配置列表、服务列表中的命名空间添加排序、检索功能。
> Add sorting and retrieval functions to the namespaces in the configuration list and service list.

### 我的使用场景
其实 namespace 比较多我是在开发环境遇到的，线上环境如果项目不到一定的规模应该很难用到。
1. 我们是统一安装了一个 nacos，每个开发人员会有自己的 namespace 作为自己的开发环境。
2. 一个人可能开发多个项目，所有一个人就会有多个 namespace。
3. UAT 环境也会用这个 nacos 环境，所以就会导致 namespace 特别的多。

问：为什么要都用一个 nacos 环境？
答：因为穷掉底了，电脑只装一个 IDEA 做开发都卡的一批，再装其他环境电脑干冒烟了也跑不动。

> In fact, I encountered many namespaces in the development environment. If it is an online environment and the project is not of a certain scale, it should be difficult to use.
> 1. We have installed a unified nacos, and each developer will have their own namespace as their own development environment.
> 2. One person may develop multiple projects, so one person will have multiple namespaces.
> 3. The UAT environment also uses this nacos environment, which leads to a particularly large number of namespaces.
> 
> Q: Why do we need to use the same nacos environment?
> A: Because I am extremely poor, my computer only needs to install one batch of IDEA for development, and even if I install it in other environments, my computer won't be able to run even if it smokes.

**Comment by HMYDK** [comment]
感觉只要把现有的namespace平铺的模式换成一个下拉选择就可以解决你的问题。就像是MSE的界面那样。
至于对namespace分组，应该是个小众需求。

**Comment by WangJincheng4869** [comment]
> 感觉只要把现有的namespace平铺的模式换成一个下拉选择就可以解决你的问题。就像是MSE的界面那样。 至于对namespace分组，应该是个小众需求。

分组的确可有可无，但是如果改成下拉那么 namespace 较少的人用起来就会比较麻烦，需要多点一下。并且下拉框选项多了之后也不好找。

1. 如同改成下拉框可以选择记住上一次的选择结果，同时下拉框支持检索功能（检索最好同时支持 id 和名字检索），默认名字排序。
2. 既然使用下拉框，那么完全可以同时显示名字和id，这样更容易区分当前是哪个 namespace。说实话日常使用中不少初学者都会把名字和 id 弄混。
3. 如果 namespace 的筛选支持配置横向平铺还是垂直平铺（就像浏览器的标签页一样可配）那么可以适配更多使用场景，多中需求都可以适配。

**Comment by KomachiSion** [comment]
这个其实比较众口难调，
命名空间多的用户希望下拉，并且能检索。
命名空间少的用户觉得现在挺好，很直观又便捷操作。

社区只能遵从大多数用户的需求和用法，采用直观的列出的方式，毕竟绝大多数用户应该不会有很多很多的命名空间，对于命名空间很多的用户，暂时只能说声抱歉；同时社区也不是很推荐过多命名空间的用法。但是也不会限制这样使用。

至于做成下拉的形式，如果社区中有同学希望做的话，可以优化后提交PR，不过我建议这里可以补充一个前端开关，让用户在选择命名空间展示的风格。

**Comment by 985492783** [comment]
开关确实可以引进社区，分组我觉得nacos不是oa社区肯定不会实现，不过想要树形分组很简单，自己搞个前端接自家的oa或者devops，然后把nacos控制台用iframe套进去就完了，nacos控制台的namespace是以queryParam形式传入的，改的时候修改iframe即可，开关可以的话指派给我，我一样放在设置中心里 @KomachiSion

**Comment by mhdifarahani** [comment]
ransfer repository: mhdifarahani/mhdi
Transfer this repository to another user or to an organization where you have the ability to create repositories.
Required fields are marked with an asterisk (*).
To understand admin access, teams, issue assignments, and redirects after a repository is transferred, see [Transferring a repository](https://docs.github.com/repositories/creating-and-managing-repositories/transferring-a-repository) in GitHub Help.
Transferring may be delayed until the new owner approves the transfer.

New owner
*

Select one of my organizations


Specify an organization or username
