### ISSUE TITLE
客户端疑似内存泄漏

### ISSUE THREAD

**Issue by pengweizhong** [alibaba/nacos#12326]
客户端疑似内存泄漏，版本号v2.3.2  (当前最新稳定版，使用的对应的客户端版本号)
![img_v3_02ck_5aafd561-5582-4557-864b-ce919626a42g](https://github.com/alibaba/nacos/assets/48546556/43349022-96c7-4f1f-b727-65c64c30479e)

**Comment by kk01001** [comment]
![image](https://github.com/alibaba/nacos/assets/35054306/e2eaad49-b620-41d7-a487-c7bd729326f2)
服务端也泄漏了

**Comment by YunWZ** [comment]
@kk01001 @pengweizhong 能否提供一下jvm内存信息呢？可以通过jmap dump一下

**Comment by KomachiSion** [comment]
1. 这不是内存泄漏， 是你的应用停止时未正确调用shutdown方法关闭客户端，或关闭时触发shutdownhook，导致线程池未正确关闭。（线程池为deamon线程，只有主动关闭，或jvm销毁时才会被销毁）
2.服务端同理， 我在我的环境使用shutdown脚本关闭时从未出现过此提示。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.

**Comment by pengweizhong** [comment]
好的谢谢，我再观察一段时间
