### ISSUE TITLE
应用部分配置文件取不到配置

### ISSUE THREAD

**Issue by wetool19** [alibaba/nacos#12327]
1、应用重新发版后部分dataId获取不到配置文件，观察nacos日志后在nacos-persistence.log文件里报
2024-07-08 00:01:01,327 ERROR [db-error] master db  down.

2024-07-08 00:01:11,328 ERROR [db-error] master db  down.

2、nacos 控制台能正常访问配置文件。
3、nacos version: 2.3.0

**Comment by KomachiSion** [comment]
看下应用测，${user.home}/logs/nacos/config.log，是否有收到新配置， 如果收到了，说明不是nacos的问题，是应用未使用新配置。

如果未收到，看下是否应用未监听配置，只是启动时get了一次配置。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and current information is not enough to judge problem.
