### ISSUE TITLE
请教问题：怎么在nacos服务端统一修改临时服务心跳检测时间(健康度标记异常时间)？

### ISSUE THREAD

**Issue by robertfly888** [alibaba/nacos#12322]
背景：
1、客户端使用非java服务调用nacos注册服务，并通过api主动上报心跳来维持健康状态。
2、目前nacos默认检测15秒没有心跳则会标记服务为异常，超过30秒没有心跳则会剔除临时服务ip。
注：nacos版本2.3.2或2.2.3等。
问题：
1、如何在nacos服务端，修改未上报心跳标记服务未异常的时间(现默认15秒)？
2、如何在nacos服务端，修改未上报心跳剔除服务的时间(现默认30秒)？

**Comment by KomachiSion** [comment]
目前不支持修改全局的心跳时间，这个影响面很大，会导致一些不希望敏感的应用变得敏感。

目前仅支持注册服务实例的时候，添加对应的参数进行设置。
