### ISSUE TITLE
[Plugin][Bug]Auth Plugin resource parser can't parser v2 config openAPI namespaceId.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#12333]
**Describe the bug**
Resource Parser is auth plugin basic to generator resource from request.
For current config resource parser, it only get namespace Id from http request with parameter `tenant`, which is used in v1 openAPI for config module to request namespace.

But after version 2.2, Nacos add v2 openAPI and the namespace parameter is unified to `namespaceId`. So the resource parser need to support parse v2 openAPI.

**Expected behavior**
It can parse right resource for v2 openAPI.

**Actually behavior**
Config module resource parser  lose the `namespaceId` for v2 openAPI.

**Desktop (please complete the following information):**
 - Version nacos 2.2.0 ~ latest(2.3.3)
 - Module config

**Comment by Bo-Qiu** [comment]
I'll fix it, please assign it to me, thx!
