### ISSUE TITLE
Spring Cloud Gateway获取配置中心的配置为空数据

### ISSUE THREAD

**Issue by zgy520** [alibaba/nacos#12339]
版本：
Spring Boot: 3.3.0
Spring Cloud: 2023.0.2
spring-cloud-starter-alibaba-nacos-config: 2023.0.1.0
spring-cloud-starter-gateway 使用的是反应式的，非mvc架构
程序可以正常启动，配置中心连接也正常，如下所示：
![image](https://github.com/alibaba/nacos/assets/6573014/06836f7b-48a3-4aa1-8c65-6558fa9a5e38)
![image](https://github.com/alibaba/nacos/assets/6573014/b62439c5-58d3-4cc9-b5f3-66a1ae8cd365)

能启动，说明程序可以读取到配置文件了，经测试发现，如果找不到文件或者配置文件中，不存在对应的属性的话，程序在启动时会报错的。
但是在获取属性的值时，返回null，获取值的方式如下：
![image](https://github.com/alibaba/nacos/assets/6573014/0f3c7d5b-b36c-4c36-baf0-8e25652209f0)

在nacos中的配置如下：
![Uploading image.png…]()

调试好久不知道问题发生在了哪，换成非spring cloud gateway的程序，读取同一个配置文件时没有问题的，怀疑是使用spring clould gateway的响应式模式导致的。
请问该问题该如何解决？

**Comment by KomachiSion** [comment]
请提交issue 到Spring Cloud Alibaba社区排查。

从你的描述和日志中，应用已经从nacos中获取到了配置， 至于应用和框架为什么没有使用该配置，已经超出了nacos的作用范围。
