### ISSUE TITLE
nacos集群轮机重启后，临时服务数量不一致，部分服务实例数也不一致

### ISSUE THREAD

**Issue by junechouiscoming** [alibaba/nacos#12344]
环境信息：
服务端：2.2.0，2节点集群，k8s deployment部署，仅用作dubbo3的注册中心；jvm xmx和xms都为12g，xmn4g
客户端：2.1.0，使用dubbo的backup格式连接的注册中心
两个节点9848总连接数6000+，服务数量1600+

现象描述：修改jvm配置需要销毁pod轮机重启，不保留data里面的数据，轮机重启的顺序为先重启2，2上面的长连接全部去到了1上面，观察一段时间后，再重启1，1上面的长连接全部去到了2上面。然后伴随着应用发版，1上面开始有了一些长连接。

完成分别打开两个节点的控制台，发现有一些服务的实例数会差几个，而且有差异的这些服务，2都是少于1的

日志都无明显报错

----------------------------

看到个issue也是出现了实例数不一致的问题，但是他那边会有raft报错，我们这的naming-raft.log和alipay-jraft.log都没有报错，[#12260](https://github.com/alibaba/nacos/issues/12260)

所以想请问下，nacos仅作为dubbo的注册中心来使用（已经使用了外部存储，如有dubbo元数据信息会存储到数据库），是不是可以无状态部署？data目录里面的数据以及控制台里面的节点元数据会不会造成这种服务实例数不一致的情况？

**Comment by mhdifarahani** [comment]
> 环境信息： 服务端：2.2.0，2节点集群，k8s deployment部署，仅用作dubbo3的注册中心；jvm xmx和xms都为12g，xmn4g 客户端：2.1.0，使用dubbo的backup格式连接的注册中心 两个节点9848总连接数6000+，服务数量1600+
> 
> 现象描述：修改jvm配置需要销毁pod轮机重启，不保留data里面的数据，轮机重启的顺序为先重启2，2上面的长连接全部去到了1上面，观察一段时间后，再重启1，1上面的长连接全部去到了2上面。然后伴随着应用发版，1上面开始有了一些长连接。
> 
> 完成分别打开两个节点的控制台，发现有一些服务的实例数会差几个，而且有差异的这些服务，2都是少于1的
> 
> 日志都无明显报错
> 
> 看到个issue也是出现了实例数不一致的问题，但是他那边会有raft报错，我们这的naming-raft.log和alipay-jraft.log都没有报错，[#12260](https://github.com/alibaba/nacos/issues/12260)
> 
> 所以想请问下，nacos仅作为dubbo的注册中心来使用（已经使用了外部存储，如有dubbo元数据信息会存储到数据库），是不是可以无状态部署？data目录里面的数据以及控制台里面的节点元数据会不会造成这种服务实例数不一致的情况？

**Comment by KomachiSion** [comment]
是重启期间不一致，还是之后都不一致？ 

 之前batch register有个provider的统计问题，会导致统计数据错误（实际数据是一致的）

#11058，这个问题应该2.3.0修复了。

**Comment by junechouiscoming** [comment]
之后都不一致，持续性的，经排查nacos.log里面有这样的报错日志，通过修改启动参数重启后一致了
![image](https://github.com/user-attachments/assets/03dcc611-2c34-4708-8804-474cb3074506)

```
-Dnacos.remote.client.grpc.maxinbound.message.size=52428800 -Dnacos.remote.server.grpc.maxinbound.message.size=52428800
```
