### ISSUE TITLE
some druid config not work

### ISSUE THREAD

**Issue by csfrez** [alibaba/nacos#1234]
## Issue Description
When I use durid properties like 

**

> spring.datasource.druid.initial-size=1
> spring.datasource.druid.min-idle=1
> spring.datasource.druid.max-active=20
> spring.datasource.druid.test-on-borrow=true

**
are work OK
but not work use these
**

> spring.datasource.druid.filter.stat.enabled=true
> spring.datasource.druid.filter.slf4j.enabled=true
> spring.datasource.druid.web-stat-filter.enabled=true
> spring.datasource.druid.stat-view-servlet.enabled=true

**

Type: bug report

### Tell us your environment
springboot 1.5.20 druid-spring-boot-starter 1.1.16 windows10 java8

**Comment by nkorange** [comment]
@csfrez Please inform your Nacos version please.

**Comment by csfrez** [comment]
> @csfrez Please tell your Nacos version.

1.0.0

**Comment by csfrez** [comment]
> @csfrez Please tell your Nacos version.

1.0.0

**Comment by nkorange** [comment]
Nacos doesn't use this configurations and of course not modify the configurations. So what happened if you exclude your Nacos client dependency?

**Comment by csfrez** [comment]
> Nacos doesn't use this configurations and of course not modify the configurations. So what happened if you exclude your Nacos client dependency?

If I use the local configuration, all the parameters are OK.
