### ISSUE TITLE
server:   port: 14511 spring:   application:     name: provider-service   main:     allow-bean-definition-overriding: true dubbo:   application:     name: provider-service   registry:     address: nacos://127.0.0.1:8848   scan:     base-packages: com.test.provider.service.impl   protocol:     name: dubbo     port: 15511

### ISSUE THREAD

**Issue by mhdifarahani** [alibaba/nacos#12347]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mhdifarahani** [comment]
https://github.com/Foundation-Devices/passport2.git

**Comment by KomachiSion** [comment]
Please resubmit new issue, and describe issue in issue detail, not in title.
