### ISSUE TITLE
sceinntist

### ISSUE THREAD

**Issue by mhdifarahani** [alibaba/nacos#12348]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by mhdifarahani** [comment]
i can see my properties

**Comment by mhdifarahani** [comment]
> i can see my properties
ransfer repository: mhdifarahani/mhdi
Transfer this repository to another user or to an organization where you have the ability to create repositories.
Required fields are marked with an asterisk (*).
To understand admin access, teams, issue assignments, and redirects after a repository is transferred, see [Transferring a repository](https://docs.github.com/repositories/creating-and-managing-repositories/transferring-a-repository) in GitHub Help.
Transferring may be delayed until the new owner approves the transfer.

New owner
*

Select one of my organizations


Specify an organization or username

**Comment by KomachiSion** [comment]
invalid information
