### ISSUE TITLE
Is it possible that we can delete data/protocol/raft on nacos startup to avoid jraft issues?

### ISSUE THREAD

**Issue by zcz3313** [alibaba/nacos#12341]
we upgrade nacos from 1.4.x -> 2.3.2 in standalone mode, sometimes we found jraft couldn't connect itself as below

![image](https://github.com/alibaba/nacos/assets/8746495/2d658516-5258-4ec8-9bad-ffa8dedcea7c)

after delete data/protocol/raft and restart nacos, it works fine.

we think this is possibly related with upgrading, but we see this issue https://github.com/alibaba/nacos/issues/12260
so this issue maybe exist in 2.x all the time.

Is it possible that we can delete data/protocol/raft on nacos startup to avoid jraft issues automatically?

**Comment by zcz3313** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
It's not jraft issue, it is your maintainer behavior issue.

raft maintain need under half of nodes in cluster.

special for standalone mode, you should make sure the ip/host of standalone node is same with the old one. Jraft is a strict raft implementation, the metadata include the leader and member info will be persisted. So the new ip/host for standalone mode changed, it will connect to old ip/host to try vote a leader but one ip/host is down.

If you delete data/protocol/raft, the metadata lose and the node only think it only contain itself. So it can vote self as leader.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
