### ISSUE TITLE
Which SpringBoot or Spring Cloud Alibaba version for Nacos 2.3.2?

### ISSUE THREAD

**Issue by HappyAxin** [alibaba/nacos#12351]
Which SpringBoot or Spring Cloud Alibaba version for Nacos 2.3.2?
![image](https://github.com/user-attachments/assets/e94f1e20-34b5-4864-9f09-954cdac54760)

**Comment by KomachiSion** [comment]
1. it should be move to Spring cloud alibaba community to find out the answer, it might be new version to use default new version nacos-client.
2. If you don't want upgrade spring cloud version, you can use exclusion tag in maven to exclude default version client, and depend your wanted version like 2.3.2 or 2.3.3 instead.

**Comment by beliefCR7** [comment]
![图片](https://github.com/user-attachments/assets/4a084692-4ae1-4dee-931a-c4717cc9e0ba)
