### ISSUE TITLE
After npm install in console, maven build will fail.

### ISSUE THREAD

**Issue by wfnuser** [alibaba/nacos#1235]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
After npm install in console, maven build will fail.

### Describe what you expected to happen
After npm install, maven build should still work.

### How to reproduce it (as minimally and precisely as possible)

1.  cd /${nacos_directory}/console/src/main/resources/static/console-fe
2. npm install
3. cd /${nacos_directory}
4. mvn clean package -Dmaven.test.skip=true -U -X
5. it will stuck in " maven-resources-plugin:3.0.2:resources (default-resources) @ nacos-console " for a long time, and finally "java.lang.OutOfMemoryError: Java heap space"

**Comment by KeRan213539** [comment]
遇到同样的问题,但是我这边三四十分钟了都没报错,一直卡在那...
我是用的 cnpm install 构建的 console-fe
初步判断是因为 install 后生成的 node_modules 造成的,虽然在maven-resources-plugin 插件中排除了这个目录,还是没用.感觉是就算排除了目录,插件还是会去扫描,只是输出的时候不输出...

**Comment by wfnuser** [comment]
我感觉有点解不来 研究了好久了，主要不太懂maven resource plugin的运行机制 include exclude都试过了... 有大佬来指点一下嘛？

**Comment by KeRan213539** [comment]
我也各种试过了...

**Comment by nkorange** [comment]
我试了下，node_modules直接删除就行了

**Comment by KeRan213539** [comment]
是删除就行了,但是这样就没法同一份代码即做前端又做服务端.
我现在是分了两份代码解决的,一份代码写服务端,一份代码写前端,前端的那份不用IDEA打开,也不编译服务端.
如果能解决的话,就可以一份代码前后端都做了...不过这貌似是maven的问题,与nacos无关
