### ISSUE TITLE
nacos cluster.conf add ip:port records issue

### ISSUE THREAD

**Issue by chixiaopao** [alibaba/nacos#12352]
**Describe the bug**
nacos version: 2.1.2
when I use nacos cluster mode, configure it in cluster.conf using dns.
referring to KomachiSion's suggestion in this issue link. @KomachiSion 
https://github.com/alibaba/nacos/issues/3858
the ip information is still added.

**Actually behavior**
An IP record is automatically added.
![image](https://github.com/user-attachments/assets/2a1b365a-bb19-4ea1-89cc-e5b064ec2b0b)
Error Logs (unable to find local peer: addedIp + port)
![image](https://github.com/user-attachments/assets/16fc5341-483e-4367-92c1-931b53b1ee70)

**How to Reproduce**
use dns for nacos cluster mode

**Desktop (please complete the following information):**
 - Centos
 - Version nacos 2.1.2

**Comment by chixiaopao** [comment]
Our company does not let us know the IP information. so this parameter : nacos.inetutils.ip-address is not ok for us.

**Comment by chixiaopao** [comment]
After research, it is necessary to configure nacos.inetutils.ip-address as the dns address, but the dns address must meet the following rules:
[a-zA-Z0-9][-a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62 })+\.?

**Comment by KomachiSion** [comment]
sorry, I can't get the key point in your issue, in nacos k8s demo, it use dns(domain) way to configura cluster.conf and it works well in my k8s env for thousands of nacos cluster.

Is it your domain config with wrong?

**Comment by chixiaopao** [comment]
hi @KomachiSion 

thank you for your feedback.
We haven't used k8s yet.
Our prod env and dev env are isolated. We can't login the prod env to do some operations, and our admin does not allow us to directly use IP to config cluster.conf in the prod env. We can only use hostname/dns to config it.
after my test, If use hostname/dns, nacos will check whether its own IP is in the cluster.conf list when it starts. If it does not exist, it will add the IP to the list. I looked at the source code and found that (nacos.inetutils.ip-address or nacos.server.ip) is configured as hostname/dns then no new record will be added to cluster.conf during detection.

But there is a regex rule: [a-zA-Z0-9][-a-zA-Z0-9]{0,62}(.[a-zA-Z0-9][-a-zA-Z0-9]{0,62 })+.?  which is used for check the hostname/dns, it need the hostname/dns must be contains (.) in the hostname/dns, I don't think it makes sense. Our company's host name does not have (.) when it is defined.

I'm not sure if my understanding is correct. I directly modified the regular expression and configured nacos.inetutils.ip-address: hostname in the prod env. Is this correct?

**Comment by chixiaopao** [comment]
sorry, this is correct regular expression: [a-zA-Z0-9][-a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62})+\.?

**Comment by KomachiSion** [comment]
The regex rule of DNS is standard rule from community, I think the check is useful. So in community version, the check logic should not change.

But for your company situation, if you think you must use hostname as the dns result. you can change the regex rule in your deployment env.

For use hostname, `nacos.inetutils.prefer-hostname-over-ip=true` will be ok. If it can't work well, such as auto read hostname with wrong hostname, then try to use  `nacos.inetutils.ip-address: hostname`

**Comment by chixiaopao** [comment]
> The regex rule of DNS is standard rule from community, I think the check is useful. So in community version, the check logic should not change.
> 
> But for your company situation, if you think you must use hostname as the dns result. you can change the regex rule in your deployment env.
> 
> For use hostname, `nacos.inetutils.prefer-hostname-over-ip=true` will be ok. If it can't work well, such as auto read hostname with wrong hostname, then try to use `nacos.inetutils.ip-address: hostname`

ok，got it，thanks a lot for your feed back，I will close this issue.
