### ISSUE TITLE
The NacosCheckStyle.xml file does not support CheckStyle plugin version 9 and above.

### ISSUE THREAD

**Issue by Bo-Qiu** [alibaba/nacos#12357]
**Is your feature request related to a problem? Please describe.**
The NacosCheckStyle.xml file does not support CheckStyle plugin version 9 and above.

**Describe the solution you'd like**
The NacosCheckStyle.xml file does not support CheckStyle plugin version 9 and above.

**Describe alternatives you've considered**
The NacosCheckStyle.xml file does not support CheckStyle plugin version 9 and above.

**Comment by Bo-Qiu** [comment]
<img width="507" alt="image" src="https://github.com/user-attachments/assets/86815629-94af-45ba-8b1f-7219c8da335b">

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/blob/develop/style/NacosCheckStyle_9.xml has fixed, please check and read the https://github.com/alibaba/nacos/blob/develop/style/codeStyle.md again?
