### ISSUE TITLE
授权接口中的 *:* 字段表示什么含义

### ISSUE THREAD

**Issue by a1156698162** [alibaba/nacos#12365]
我通过nacos接口 /nacos/v1/auth/permissions 对用户进行授权成功后，发现用户依旧没有权限查看对应的namespace下的配置信息。请求截图如下
![image](https://github.com/user-attachments/assets/c7ee2d2f-fa0b-43ea-9b14-3073b282fff3)
但是，通过nacos的后管页面为用户添加权限是生效的，对比了下请求。通过页面授权是resource 字段 对应的值后面跟了 *:*
![image](https://github.com/user-attachments/assets/d1c350e1-9223-419c-939d-0c3247697ed5)
请问 *:* 表示什么含义？

**Comment by KomachiSion** [comment]
通配符，意味着命名空间下所有的资源。

如果不加* ，那么意味是操作命名空间本身，而不是命名空间下所有资源

**Comment by KomachiSion** [comment]
这个*应该只是资源的内容，操作权限是action的rw。
