### ISSUE TITLE
nacos集群 1.x升级到2.0.3，服务拉取配置出现：special characters are not allowed

### ISSUE THREAD

**Issue by xiaqingdongxue** [alibaba/nacos#12361]
nacos集群按官网配置，1台nginx搭载3台nacos节点，nginx默认开启了gzip压缩，1.0版本获取配置正常。按照官网（https://nacos.io/docs/v2/upgrading/200-upgrading/）平滑升级2.0.3后，服务拉取yml配置，出现乱码错误日志，将nginx gzip压缩关闭后正常，请问是什么原因?

**Comment by xiaqingdongxue** [comment]
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2.2.2.RELEASE</version>
</dependency>

**Comment by KomachiSion** [comment]
2.2.2.RELEASE 依赖的是1.3.2的nacos-client ，这个版本有bug，升级一下客户端版本即可。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.
