### ISSUE TITLE
nacos-server-2.1.2.tar.gz 版本出现的问题

### ISSUE THREAD

**Issue by laoruijin** [alibaba/nacos#12373]
<img width="921" alt="efd203f80d28984a37890ae0a39be1f" src="https://github.com/user-attachments/assets/cf5ee8b6-3025-46e6-9b53-46e1f25875ae">
<img width="711" alt="6a34a17d37f414f35e780495a4065c1" src="https://github.com/user-attachments/assets/09655aad-1fe4-444d-aec9-3fd8161af2f5">
<img width="907" alt="bffec57822cb7c75f4989e286e63a11" src="https://github.com/user-attachments/assets/e1a4f5f3-40a4-474a-bfa4-086ed39a2bfb">

**Comment by KomachiSion** [comment]
能否描述一下问题？  只看接图不知道问题是什么。
