### ISSUE TITLE
2.0.3升级到2.2.x+

### ISSUE THREAD

**Issue by waymen** [alibaba/nacos#12375]
老师们，询问下升级到细节

## 2.0.3升级到2.2.x+

1. 目前使用的是2.0.3版本，升级到2.2.x+或2.3+版本，数据库结构有变化吗，是否可以直接升级
2. 升级后客户端sdk是否必须要与nacos是相同的版本， 如果sdk是2.0.3，nacos是高版本会有影响吗
3. 原有的nacos是集群+nginx负载的模式，为了升级新版本，是否可以滚动更新（升级一个，在升级其其它）这种模式是否会影响业务

**Comment by waymen** [comment]
> 老师们，询问下升级到细节
> 
> ## 2.0.3升级到2.2.x+
> 1. 目前使用的是2.0.3版本，升级到2.2.x+或2.3+版本，数据库结构有变化吗，是否可以直接升级
> 2. 升级后客户端sdk是否必须要与nacos是相同的版本， 如果sdk是2.0.3，nacos是高版本会有影响吗
> 3. 原有的nacos是集群+nginx负载的模式，为了升级新版本，是否可以滚动更新（升级一个，在升级其其它）这种模式是否会影响业务

还有就是升级的话，推荐2.2.x版本还是最新的2.3.2

**Comment by NagaResst** [comment]
数据库结构是有变化的  多了几个列  滚动升级的情况我就不清楚了 没试过

**Comment by waymen** [comment]
> 数据库结构是有变化的 多了几个列 滚动升级的情况我就不清楚了 没试过

那怎么弄呢，如果是升级，原先的数据库

**Comment by NagaResst** [comment]
> > 数据库结构是有变化的 多了几个列 滚动升级的情况我就不清楚了 没试过
> 
> 那怎么弄呢，如果是升级，原先的数据库

多几个列而已 百度搜一下  直接alter就行 别的都不用改

**Comment by waymen** [comment]
目前使用的是2.0.3版本，升级到2.2.x+或2.3+版本，数据库结构有变化吗，是否可以直接升级
升级后客户端sdk是否必须要与nacos是相同的版本， 如果sdk是2.0.3，nacos是高版本会有影响吗
原有的nacos是集群+nginx负载的模式，为了升级新版本，是否可以滚动更新（升级一个，在升级其其它）这种模式是否会影响业务

**Comment by KomachiSion** [comment]
duplicate with #12415
