### ISSUE TITLE
如何对存在nacos mysql库里的user表里nacos控制台密码进行反解密？

### ISSUE THREAD

**Issue by DeBruyne2020** [alibaba/nacos#12370]
请教下老师：
                 现在想获取nacos的控制台密码，好像只可能从mysql库里查询，但是，我试了一下使用nacos的加密方式对密码进行加密，每次生成的密码不一样，所以想问下老师们  有没有办法对存在nacos mysql库的nacos控制台密码（user表里的密码）进行反解密？

**Comment by HMYDK** [comment]
控制台更新密码不行嘛？为啥要去数据库解密😼

**Comment by DeBruyne2020** [comment]
> 控制台更新密码不行嘛？为啥要去数据库解密😼

老师   就是不希望更新， 只是单纯要查看，要比对

**Comment by KomachiSion** [comment]
BCrypt不支持反解密的， 因为是加盐加密算法， 只能通过Bcrypt的match方法，进行比对。
