### ISSUE TITLE
页面灰度发布接口：取值疑问

### ISSUE THREAD

**Issue by HMYDK** [alibaba/nacos#12381]
![image](https://github.com/user-attachments/assets/edd111db-fc01-4da5-b0b3-58ee98430f18)

灰度ip为什么放到header中？后端接口也是从header中取值。其实请求表单中也已经存在ip参数了。

![image](https://github.com/user-attachments/assets/4dc04e9c-bde3-4a36-bdc5-6a1624ebc4b5)

**Comment by shiyiyue1102** [comment]
历史接口设计如此，没有特别的原因
