### ISSUE TITLE
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'communicationController' defined in URL [jar:file:/D:/PISX_20180329/02_WORK/01_softWare/apache-maven-3.5.3/repository/com/alibaba/nacos/nacos-config/1.0.0/nacos-config-1.0.0.jar!/com/alibaba/nacos/config/server/controller/CommunicationController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure : No DataSource set

### ISSUE THREAD

**Issue by lhzhou180606** [alibaba/nacos#1239]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'communicationController' defined in URL [jar:file:/D:/PISX_20180329/02_WORK/01_softWare/apache-maven-3.5.3/repository/com/alibaba/nacos/nacos-config/1.0.0/nacos-config-1.0.0.jar!/com/alibaba/nacos/config/server/controller/CommunicationController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure : No DataSource set

![image](https://user-images.githubusercontent.com/39972617/57990891-7f15b180-7add-11e9-871d-2ad1e21305de.png)

**Comment by nkorange** [comment]
Please paste your error stack.
