### ISSUE TITLE
nacos-config-spring-boot-starter(0.3.0-RC) 获取配置无效

### ISSUE THREAD

**Issue by robben009** [alibaba/nacos#12394]
spring-boot-starter-web(3.2.3)
nacos-config-spring-boot-starter(0.3.0-RC)  
两者结合后动态获取配置并不生效。其中启动日志中的NacosConfigPropertiesUtils正确打印了配置信息，但是最后提示[Nacos Config Boot] : The preload configuration is not enabled

**Comment by KomachiSion** [comment]
是不是auto-refresh开关没有打开？ 建议看一下nacos-spring-boot的example用例，实验试一下。

**Comment by robben009** [comment]
后续能支持下yml的最新版本不？

**Comment by robben009** [comment]
> 是不是auto-refresh开关没有打开？ 建议看一下nacos-spring-boot的example用例，实验试一下。

发现原因了，如果采用application.yml的形式配置的话，均会启动失败，无论snakeyaml是什么版本。
而application.properties形式配置的话，必须是snakeyaml的版本必须是2.0以下。否则会报错

Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found

后续能支持下yml的最新版本不？

**Comment by KomachiSion** [comment]
@hujun-w-2 这个问题有解决吗？

**Comment by hujun-w-2** [comment]
1. The preload configuration is not enabled 这个报错说明配置加载开关没打开，设置一下这个参数nacos.config.bootstrap.enable=true
2. 使用 spring-boot-starter-web(3.2.3)
nacos-config-spring-boot-starter(0.3.0-RC)、snakeyaml 2.2未复现NoSuchMethodError相关报错

**Comment by robben009** [comment]
> 1. The preload configuration is not enabled 这个报错说明配置加载开关没打开，设置一下这个参数nacos.config.bootstrap.enable=true
> 2. 使用 spring-boot-starter-web(3.2.3)
>    nacos-config-spring-boot-starter(0.3.0-RC)、snakeyaml 2.2未复现NoSuchMethodError相关报错

试试https://github.com/robben009/testNacos  这个项目启动下，直接启动即可，能复现此问题

**Comment by hujun-w-2** [comment]
> > 1. The preload configuration is not enabled 这个报错说明配置加载开关没打开，设置一下这个参数nacos.config.bootstrap.enable=true
> > 2. 使用 spring-boot-starter-web(3.2.3)
> >    nacos-config-spring-boot-starter(0.3.0-RC)、snakeyaml 2.2未复现NoSuchMethodError相关报错
> 
> 试试https://github.com/robben009/testNacos 这个项目启动下，直接启动即可，能复现此问题

好的，我先用你的工程试试

**Comment by hujun-w-2** [comment]
用你的工程试过了，application.properties形式配置是没问题的，yml的形式确实存在问题，不过已经在最新版本修复了，近期会发布正式版

**Comment by robben009** [comment]
> 用你的工程试过了，application.properties形式配置是没问题的，yml的形式确实存在问题，不过已经在最新版本修复了，近期会发布正式版

ok

**Comment by 15102552479** [comment]
我也是这个问题，请问怎么解决

**Comment by robben009** [comment]
> 我也是这个问题，请问怎么解决

放弃使用yml形式配置，改用*.properties

**Comment by neal-wyz** [comment]
> 用你的工程试过了，application.properties形式配置是没问题的，yml的形式确实存在问题，不过已经在最新版本修复了，近期会发布正式版

正式版什么时候发布？
