### ISSUE TITLE
nacos 现在发版就这么随意吗？版本号都不修改一下？

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [alibaba/nacos#12403]
发版都不修改 pom.xml 的版本号？

https://github.com/alibaba/nacos/compare/2.4.0...2.4.0.1

![Screenshot_20240722_224633_com huawei browser](https://github.com/user-attachments/assets/3899b14d-b063-44d5-ae16-dc3a33df83cb)

**Comment by KomachiSion** [comment]
紧急fix不会修改pom中的版本号， 同样的情况在2.2.0.1中也是一致的行为。
