### ISSUE TITLE
2.4.0 出现命名空间页面请求挂起，请求无响应，其他页面功能正常

### ISSUE THREAD

**Issue by zyjnicemoe** [alibaba/nacos#12407]
命名空间页面
![image](https://github.com/user-attachments/assets/a9604562-2edd-42b6-936c-e03533ad392c)

请求:
curl 'http://localhost:30050/nacos/v1/console/namespaces?&namespaceId=undefined' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,en-AU;q=0.5' \
  -H 'AccessToken: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcyMTczODE4M30.hnCgJg5zsH-P_gg5Y86URwFxbGo-rXrdjCMpVh2BCXYnuVwe2N5PgWYT8EEwmcxf' \
  -H 'Authorization: {"accessToken":"eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcyMTczODE4M30.hnCgJg5zsH-P_gg5Y86URwFxbGo-rXrdjCMpVh2BCXYnuVwe2N5PgWYT8EEwmcxf","tokenTtl":18000,"globalAdmin":true,"username":"nacos"}' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: Idea-caca3a49=861eaa56-18b1-4b11-96d9-6739d73b0dd0; Hm_lvt_fca67c0402c411679af17b69c06e092c=1710989386; Hm_lvt_6edd69cc926242ec43e7194677fb8040=1709192594,1710830702,1711531312; Hm_lvt_5dd2e8c97962d57b7b8fea1737c01743=1715909935,1716453596' \
  -H 'Referer: http://localhost:30050/nacos/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"'

请求接口截图
![image](https://github.com/user-attachments/assets/a5f072f1-90f9-4b30-95d0-7f8ae70e493f)

![image](https://github.com/user-attachments/assets/95353124-6ee4-48fb-9108-e737e58f0b96)

配置管理新增配置时命名空间出现： undefined
![image](https://github.com/user-attachments/assets/8c8ce25a-cb09-4d1a-83f1-cae64eb808c7)

**Comment by HMYDK** [comment]
![image](https://github.com/user-attachments/assets/a87145f9-a1af-415a-9ed3-70dec9428e11)

版本：2.4.0
数据库：内置 、mysql

没有复现问题。

**Comment by HMYDK** [comment]
你是点了「刷新」按钮，然后请求挂起？

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
