### ISSUE TITLE
nacos-client线程数太多

### ISSUE THREAD

**Issue by caoyanan666** [alibaba/nacos#12402]
我找到过一个文档，https://help.aliyun.com/zh/mse/support/what-do-i-do-if-the-number-of-nacos-threads-is-excessively-large
也就是说，我启动一个dubbo application，用nacos服务注册与发现，对于同一个nacos server，会启动多个Nacos ConfigService And NamingService，
希望ConfigFactory和NamingFactory创建client的时候可以缓存，减少空转的线程资源
我实现了一个demo，
![image](https://github.com/user-attachments/assets/5d93b10f-d8cb-4670-b000-f8563e79264c)
看一下这个思路可以吗

**Comment by KomachiSion** [comment]
正常情况下 一个应用的naming和config是各一个， 如果框架需求多个（比如多注册中心等），那么应该有框架自行缓存client的实例对象。

如果是一个服务和一个配置就创建一个新的client对象， 那么就是错用问题， 我记得dubbo的2.7.8版本有这个问题， 之后修复过。你看下你是否命中了这个版本，如果是其他版本，建议和对应的应用框架社区进行讨论。
