### ISSUE TITLE
使用外部数据源时，更新配置后立马获取，返回的还是修改前的配置

### ISSUE THREAD

**Issue by pgrightwu** [alibaba/nacos#12404]
问题描述：
服务端nacos2.3.0，使用外部数据源(mysql、pg、dm)，通过client更新配置，并且接口返回成功后，立马获取对应配置，返回的还是老的配置，大概一百ms后获取的才是新的配置，使用derby时未能复现。

复现demo：
![微信图片_20240723135504](https://github.com/user-attachments/assets/03c738a6-c215-4ca1-90e4-d58e953b8b6b)

**Comment by Bo-Qiu** [comment]
nacos 是 AP模型，配置写入时是写入到数据库，通过 grpc 查询配置时读取的是 nacos server 本地磁盘的配置内容。 nacos server 本地的数据更新是通过 cluster notify 或者定时对账 触发 DumpTask，从数据库拉取配置更新本地磁盘的内容。

**Comment by KomachiSion** [comment]
建议使用监听配置的方式，只在应用启动时首次获取配置使用getConfig。
