### ISSUE TITLE
Request to change db storage to pg

### ISSUE THREAD

**Issue by FreemanKevin** [alibaba/nacos#12419]
Now no one is maintaining and handling the security issues of MySQL. Is it possible to directly change the MySQL storage to postgresql, or make it directly compatible with postgresql without the need for users to develop a separate nacos branch themselves?

**Comment by 985492783** [comment]
nacos has pg plugin，use spi inject into nacos

**Comment by fuhouyu** [comment]
you can see this [pg plugin example](https://github.com/fuhouyu/nacos-multiple-datasource/tree/main), hope it helps you.

**Comment by FreemanKevin** [comment]
thanks.
