### ISSUE TITLE
关于升级的问题

### ISSUE THREAD

**Issue by waymen** [alibaba/nacos#12415]
目前使用的是2.0.3版本，升级到2.2.x+或2.3+版本，数据库结构有变化吗，是否可以直接升级
升级后客户端sdk是否必须要与nacos是相同的版本， 如果sdk是2.0.3，nacos是高版本会有影响吗
原有的nacos是集群+nginx负载的模式，为了升级新版本，是否可以滚动更新（升级一个，在升级其其它）这种模式是否会影响业务

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/manual/admin/upgrading/

**Comment by KomachiSion** [comment]
sdk的话是兼容的， 不是必须升级， 但是建议升级， 2.0.3的sdk太低了版本， 可能有一些比较严重的bug

**Comment by KomachiSion** [comment]
> 原有的nacos是集群+nginx负载的模式，为了升级新版本，是否可以滚动更新（升级一个，在升级其其它）这种模式是否会影响业务

应该不会， 如果升级时还能够通过nginx控制流量应该更稳定。建议现在测试环境升级预演一下。

**Comment by waymen** [comment]
> > 原有的nacos是集群+nginx负载的模式，为了升级新版本，是否可以滚动更新（升级一个，在升级其其它）这种模式是否会影响业务
> 
> 应该不会， 如果升级时还能够通过nginx控制流量应该更稳定。建议现在测试环境升级预演一下。

谢谢老师
