### ISSUE TITLE
2.4.0修改密码报错session过期，无法修改密码

### ISSUE THREAD

**Issue by mazhm** [alibaba/nacos#12412]
![image](https://github.com/user-attachments/assets/2b2e6dd3-55bc-4140-82c7-0ee63cbd1be9)
![image](https://github.com/user-attachments/assets/4fdcbc98-7f53-489c-9b24-dfcbbfa48004)

**Comment by KomachiSion** [comment]
duplicate with #12395, please use 2.4.0.1
