### ISSUE TITLE
开启鉴权后无法登录

### ISSUE THREAD

**Issue by Style-Tender** [alibaba/nacos#12431]
**Describe the bug**
开启鉴权后无法登录，登录报错：caused: Invalid key: javax.crypto.spec.SecretKeySpec@fa765332; 
提示用户名/密码错误

**Desktop (please complete the following information):**
 - OS: Centos 7.9
 - Version nacos-server 2.4.0.1

**Additional context**
JDK版本：1.8.0_411
mysql：8.0.36

在第一次打开控制台时，会跳转register的页面，输入密码nacos后，就无法登录了。
查看数据库中，已经存在了一个用户，`role`表中也有一条新的数据，但保存的密码与老版本的密码有所不同:
数据库里密码的值为：`$2a$10$DLrW9E6zFU5dghqfpOPA6.FMskdcoyH3DA/FpQ2YMRUPsCMBf8nD.`

看了别的issues，有说是jdk版本问题，但尝试了1.8.0_391和1.8.0_202版本，还是会报错。

是否有人可以帮助一下我？

**Comment by HMYDK** [comment]
nacos用的哪个版本？数据库user有id主键么？

**Comment by Style-Tender** [comment]
> nacos用的哪个版本？数据库user有id主键么？

@HMYDK 你好，nacos用的2.4.0.1，数据库users表没有id主键，我看conf里面的sql文件，创建users表时就没有id

**Comment by HMYDK** [comment]
参考下这个issue #12097 .
换个jdk版本试下。

**Comment by Style-Tender** [comment]
> 参考下这个issue #12097 . 换个jdk版本试下。

这个issue之前看过了，尝试了里面提到的几个版本都不行，比如`1.8.0_391` , `1.8.0_251`

**Comment by KomachiSion** [comment]
请问是本地源码启动的还是用发布版部署的？ 前者可以debug一下，打个断点看下， 如果是发布版部署的， 可以arthas抓一下看看， 这里的提示不是很友好， 两个异常是同一个提示。

#12097 评论了，希望有人提个PR，把两个提示分开一下，目前还没有人提PR。

```
    private Mac getMacInstance(Key key) {
        try {
            Mac instance = Mac.getInstance(jcaName);
            instance.init(key);
            return instance;
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            throw new IllegalArgumentException("Invalid key: " + key);
        }
    }
```

**Comment by HMYDK** [comment]
@Style-Tender 是否方便在你的环境中执行以下代码，然后贴一下代码输出的内容？

```
import javax.crypto.Mac;
import java.security.Provider;
import java.security.Security;

public class ListMacAlgorithms {
    public static void main(String[] args) {
        for (Provider provider : Security.getProviders()) {
            for (Provider.Service service : provider.getServices()) {
                if (service.getType().equals("Mac")) {
                    System.out.println(provider.getName() + ": " + service.getAlgorithm());
                }
            }
        }
    }
}
```

**Comment by Style-Tender** [comment]
@HMYDK @KomachiSion 感谢2位，我这边把系统改成CentOS 8.5，jdk使用1.8.0_391之后，恢复了正常，可能是哪边有缓存没有清掉。
