### ISSUE TITLE
客户端是否有实现dataId模糊查询配置文件信息接口吗？

### ISSUE THREAD

**Issue by chengyouling** [alibaba/nacos#12437]
Nacos-client version：2.3.0

**Comment by KomachiSion** [comment]
不支持，也暂无计划支持， 原因是正常应用需要哪些配置其实应用应该是清晰知晓的， 模糊匹配会很容易造成数据泄露等问题。

3.0有计划支持分组级别的配置监听需求，来满足一些网关类应用的需求。同时后续有计划通过单独发布一个maintainer sdk来提供给范围查询的API来满足一些平台型的需求。
