### ISSUE TITLE
The nacos2.4 version uses the pg database as an external database, and an error is reported when querying the page.

### ISSUE THREAD

**Issue by 1831619130** [alibaba/nacos#12439]
![image](https://github.com/user-attachments/assets/1e0df536-2dff-45b0-a4e2-787b065b7dee)
![image](https://github.com/user-attachments/assets/51ac90c1-f528-4aa1-9999-3053cb9d9fa6)
![image](https://github.com/user-attachments/assets/ef9ae48e-20c0-4a67-acb2-755f2d267c21)
![image](https://github.com/user-attachments/assets/95cfe5df-50d6-4f94-9735-d34df070f2e6)
[nacos日志.zip](https://github.com/user-attachments/files/16421502/nacos.zip)

**Comment by 1831619130** [comment]
nacos这个源码在哪里能下载？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月30日(星期二) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] The nacos2.4 version uses the pg database as an external database, and an error is reported when querying the page. (Issue #12439)





 
你的postgresql中的插件sql存在问题，pg的分页应该是LIMIT OFFSET，你的这个是Mysql的语法。
 修改你的pg插件中的sql，或参考pg example

**Comment by fuhouyu** [comment]
> nacos这个源码在哪里能下载？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/nacos" ***@***.***&gt;; 发送时间:&nbsp;2024年7月30日(星期二) 下午2:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/nacos] The nacos2.4 version uses the pg database as an external database, and an error is reported when querying the page. (Issue #12439) 你的postgresql中的插件sql存在问题，pg的分页应该是LIMIT OFFSET，你的这个是Mysql的语法。 修改你的pg插件中的sql，或参考pg example — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

官方提供的[插件地址](https://github.com/nacos-group/nacos-plugin/tree/develop/nacos-datasource-plugin-ext)。

**Comment by 7FreezingPoint** [comment]
> > nacos这个源码在哪里能下载？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "alibaba/nacos" _**@**_._**>; 发送时间: 2024年7月30日(星期二) 下午2:50 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [alibaba/nacos] The nacos2.4 version uses the pg database as an external database, and an error is reported when querying the page. (Issue #12439) 你的postgresql中的插件sql存在问题，pg的分页应该是LIMIT OFFSET，你的这个是Mysql的语法。 修改你的pg插件中的sql，或参考pg example — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 官方提供的[插件地址](https://github.com/nacos-group/nacos-plugin/tree/develop/nacos-datasource-plugin-ext)。

可以出pg的nacos镜像吗

**Comment by fuhouyu** [comment]
> > > nacos这个源码在哪里能下载？
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "alibaba/nacos" _**@**_._**>; 发送时间: 2024年7月30日(星期二) 下午2:50 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [alibaba/nacos] The nacos2.4 version uses the pg database as an external database, and an error is reported when querying the page. (Issue #12439) 你的postgresql中的插件sql存在问题，pg的分页应该是LIMIT OFFSET，你的这个是Mysql的语法。 修改你的pg插件中的sql，或参考pg example — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 官方提供的[插件地址](https://github.com/nacos-group/nacos-plugin/tree/develop/nacos-datasource-plugin-ext)。
> 
> 可以出pg的nacos镜像吗

官方似乎没有pg的镜像，自己做了构建。你可以参考这个[nacos-multiple-datasource](https://github.com/fuhouyu/nacos-multiple-datasource)

**Comment by KomachiSion** [comment]
目前社区自行维护的插件都还没有达到很稳定的程度，基本都在beta阶段，所以暂时不会默认带入release中，欢迎大家积极测试，多发现问题以及多帮忙社区做插件上的优化，随着插件的成熟，就可以带入到release中，这样官方镜像中就会有对应插件的支持了。
