### ISSUE TITLE
v2.3.2 his_config_info表为什么gmt_create和gmt_modified字段时间不一样？

### ISSUE THREAD

**Issue by linux-time** [alibaba/nacos#12436]
gmt_create加了8小时，而gmt_modified只有部分行有加8小时。
![image](https://github.com/user-attachments/assets/c7a07f5f-ddbc-44b3-9f6a-32a9c529224e)

**Comment by ricmi** [comment]
me too

**Comment by Sunrisea** [comment]
多个节点吗？是不是数据库和某些nacos server节点设置的时区不一致，gmt_modified是Nacos Server传的，gmt_create是数据库生成的

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
