### ISSUE TITLE
springcloudalibaba2022.0.0.0-RC2使用nacos2.2.1无法注册服务

### ISSUE THREAD

**Issue by wangwenming0918** [alibaba/nacos#12443]
## Issue Description

Type: *bug report* or *feature request*

1. 这是我的pom.xml文件，java17
![image](https://github.com/user-attachments/assets/8e4dc2f7-be38-45ef-9fe5-a04c1570bb35)

2.订单服务的pom.xml文件，java17
![image](https://github.com/user-attachments/assets/a2d235a7-849f-4990-868e-9e2bd0748452)

3.订单服务的yml配置文件
![image](https://github.com/user-attachments/assets/7f548b90-b676-40dd-a9f0-288565aa0ff5)
4、成功启动项目
![image](https://github.com/user-attachments/assets/25cb3717-0c4f-4c27-8bef-1988d06bc7ec)
5、不会把服务注册到nacos2.2.1中
![image](https://github.com/user-attachments/assets/57553d1c-d00e-4f7a-bf06-465522c120a2)

**Comment by KomachiSion** [comment]
你的命名空间是dev， 你查询的命名空间是public
 
 请把配置文件中的namespace移除后重试。

**Comment by wangwenming0918** [comment]
多谢大佬，确实是这个问题
