### ISSUE TITLE
nacos2.3.2升级到2.4.1报错无法启动

### ISSUE THREAD

**Issue by yinmin2020** [alibaba/nacos#12440]
使用的是k8s启动的服务
我对比了2.3.2和2.4.1的初始化sql没变化 application.properties2个版本之间 也没变化 就是startup.sh 稍微有点参数资源的变化 启动后就报了这些  看起来是代码问题？
![6d6ce0dc8aaff49896b3e8beb4fe2ae](https://github.com/user-attachments/assets/1f8a69b2-2ee9-4c21-8a65-a6b80a963048)

**Comment by ygqygq2** [comment]
看看上面日志，是不是这个问题
https://github.com/nacos-group/nacos-docker/issues/424
