### ISSUE TITLE
2.4.0.1 集群,使用derby ，移植环境修改ip 之后，删除 data/protocol 数据丢失

### ISSUE THREAD

**Issue by hujiang75277381** [alibaba/nacos#12448]
版本：2.4.0.1
问题：如题

**Comment by KomachiSion** [comment]
内部存储，数据都存储在data目录中， 如果删除目录中的文件，同时修改了cluster.conf后， 当选举时的leader不存在快照文件时，数据丢失是符合预期的。

正确的运维逻辑应该是， 挂载data目录在外部盘内；同时运维操作时应保证单次操作的节点数不大于半数;如果出现ip变更，还需要修改cluster.conf等文件，并确认操作后的raft 选举正确，变更期间不建议删除data目录， 如果因故障等原因必须要删除，也需要保证删除的节点数小于半数，甚至只删除某一个节点。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
