### ISSUE TITLE
API push of 2mb file failed

### ISSUE THREAD

**Issue by wawameizhangya** [alibaba/nacos#12441]
**Describe the bug**

 Using only Go language to push configurations greater than 2mb directly fails

 
 
**Desktop (please complete the following information):**
 
 - Version: nacos-server 1.3.2

**Comment by wawameizhangya** [comment]
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/e2a58fdd-b8cd-4fb6-9af0-0d362d711628">
I tested the official demo and found the same issue. Does nacos not support large file push

**Comment by KomachiSion** [comment]
Http post size has limited for default by tomcat. If you want to support large file. Please set relative config in application.properties, such as `server.tomcat.max-swallow-size=-1`.

But this is not suggested. It is suggested to split config to muiltple configs.

**Comment by wawameizhangya** [comment]
application.properties： 

server.tomcat.max-http-form-post-size=-1 
server.tomcat.max-swallow-size=-1

 
<img width="840" alt="image" src="https://github.com/user-attachments/assets/47e2b1a7-061d-4c97-aceb-74dd578755e4">

**Comment by wawameizhangya** [comment]
设置了两个参数，但是目前看通过api和web都是不支持的

**Comment by wawameizhangya** [comment]
> erties, such as `server.tomcat.max-swallow-size=-1`.

这个和版本有关系么，我这用的版本比较老1.3.2，我看naocs 1.3.2 的springboot里面是2.1.1的，这参数是2.3.3 支持的，和这个有关系么

**Comment by KomachiSion** [comment]
老版本可能参数是旧的参数， 可以自行搜索一下， 这个是tomcat的参数， 可以在搜索引擎搜索一下旧版本的参数是哪个。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
