### ISSUE TITLE
Do default values of heart beat mechanism in version 2.3.2 are same as older version ?

### ISSUE THREAD

**Issue by sichenyong** [alibaba/nacos#12457]
I found nothing about the default value of heart beat mechanism in official doc

I tried to find a result in source code,  nothing found!

here are definition, but no default values
```java
	/**
	 * Heart beat interval. Time unit: millisecond.
	 */
	private Integer heartBeatInterval;

	/**
	 * Heart beat timeout. Time unit: millisecond.
	 */
	private Integer heartBeatTimeout;

	/**
	 * Ip delete timeout. Time unit: millisecond.
	 */
	private Integer ipDeleteTimeout;
```

Do default values same as older version?

**Comment by HMYDK** [comment]
there are three method in `Instance`
![image](https://github.com/user-attachments/assets/5e6d4d25-b0a4-4aca-b176-4217f8c7a45d)

![image](https://github.com/user-attachments/assets/7552d8b0-9cb5-4482-ae9b-5ecc9d23cf05)

**Comment by KomachiSion** [comment]
BTW, this three parameters is used in nacos1.x client, when use 1.x client and 2.x server, the three parameters also work.

But if use nacos2.x client, due to the heart beat upgarde to long connection, the three parameters will not be used.
