### ISSUE TITLE
注册的服务名带有#号,web端查看详情报错

### ISSUE THREAD

**Issue by fgfgdfgdf** [alibaba/nacos#12451]
**Describe the bug**
If the registered service name has a # sign, the web client will report an error when viewing the details

**Expected behavior**
show detail info

**Actually behavior**
web client pops: ' caused: service DEFAULT_GROUP@@GATEWAY is not found!;' and server log with 'com.alibaba.nacos.api.exception.NacosException: service DEFAULT_GROUP@@LOGIN is not found!'

**How to Reproduce**
1. register Instance and name has "#"
2.  look this instance info on web client
3. See errors

**Desktop (please complete the following information):**
 - Centos
 - Version [e.g. nacos-server 2.4.0.1, nacos-client 2.3.2]

**Comment by fuhouyu** [comment]
web页面使用的是hash模式，使用#号时，会看作前端的一个子路由。在调用后端接口时，参数会缺失，造成查询错误。
<img width="956" alt="image" src="https://github.com/user-attachments/assets/38a607d9-23a6-44ad-8c4c-823acfec8f06">

**Comment by KomachiSion** [comment]
试一下通过API直接查询是否能够查询出来？

**Comment by fgfgdfgdf** [comment]
用api可以查询的.要么客户端处理服务名称带#的情况,要么服务器禁止带#的服务名

**Comment by wzshuang** [comment]
@KomachiSion 已关闭的issue还可以修复吗，我打算在页面跳转时，对name进行encode
