### ISSUE TITLE
nacos 2.2.3部署Liunx报错can`t find denpendent libraries

### ISSUE THREAD

**Issue by Harry-Qin** [alibaba/nacos#12455]
nacos2.2.3部署到Liunx（3.10.0-957.el7.x86_64）报错 can`t find denpendent libraries 错误

**Comment by fuhouyu** [comment]
参考这个：https://nacos.io/blog/faq/nacos-user-question-history16294/

**Comment by KomachiSion** [comment]
这个问题普遍是jdk安装的版本和系统版本不匹配导致的。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by Harry-Qin** [comment]
问题已找到，是由于rocksdb-jar无法获取到 librocksdbjin.so 文件的原因
