### ISSUE TITLE
只安装jre可以正常运行nacos 2.4.0吗？

### ISSUE THREAD

**Issue by guoxiangdaxia** [alibaba/nacos#12458]
由于我们有安全制度，linux服务器只能安装jre，不可以安装jdk。已知安装 java-1.8.0-openjdk-devel.x86_64是可以登录。但是换成了jre版本 java-1.8.0-openjdk-headless 。就登录就报错了。caused:Invalid key:javax.crypto.spec.SecretKeySpec@fa7579d9;

**Comment by KomachiSion** [comment]
可以的，如果登陆报错， 可以查看一下https://github.com/alibaba/nacos/issues/12446，更换一下jre的版本。
