### ISSUE TITLE
nacos2.4.0适配kingbase

### ISSUE THREAD

**Issue by HY-love-sleep** [alibaba/nacos#12456]
请问nacos2.4.0能将kingbase8.6设置为外部数据源吗， 如果可以的话请问应该如何操作呢， 按照之前SPI的方法好像不太兼容了。

**Comment by fuhouyu** [comment]
你可以参考下这个项目：https://github.com/nacos-group/nacos-plugin/tree/develop/nacos-datasource-plugin-ext

**Comment by KomachiSion** [comment]
如果当前的plugin在2.4.0不兼容的话， 可以在这个issue评论一下报错信息，或者直接提交PR修复。

**Comment by HY-love-sleep** [comment]
报错找不到数据源：
![image](https://github.com/user-attachments/assets/e495ec58-710d-4389-b7a3-6af1732773b6)
![image](https://github.com/user-attachments/assets/57bc39d4-d42f-41bf-a76a-6c4ba2030f1d)
![image](https://github.com/user-attachments/assets/fa3f28c6-3575-4e0b-870d-2794f2ba95ff)

**Comment by HY-love-sleep** [comment]
> 如果当前的plugin在2.4.0不兼容的话， 可以在这个issue评论一下报错信息，或者直接提交PR修复。

请问下， 我本地测试启动日志和页面都没报错， 但是一直处于loading状态， 应该如何排查呢？
![image](https://github.com/user-attachments/assets/705f9373-ac6c-416c-a84a-84479ff7798e)
![image](https://github.com/user-attachments/assets/ed25b0cf-33d7-4305-a07b-e06b53457c1b)

**Comment by KomachiSion** [comment]
nacos-persistent.log日志有信息吗
