### ISSUE TITLE
[Question] 取消服务订阅事件如何触发

### ISSUE THREAD

**Issue by Happy-26** [alibaba/nacos#12467]
请问如何触发取消服务订阅事件，现在在使用轨迹追踪插件时，发现有取消服务订阅事件，但是不知道如何触发？

**Comment by KomachiSion** [comment]
unsubscribe 接口

https://nacos.io/docs/latest/manual/user/java-sdk/usage/#47-%E5%8F%96%E6%B6%88%E7%9B%91%E5%90%AC%E6%9C%8D%E5%8A%A1

**Comment by KomachiSion** [comment]
另外，连接断开时也会触发

**Comment by Happy-26** [comment]
谢谢
