### ISSUE TITLE
about web resoucres

### ISSUE THREAD

**Issue by anpu2018** [alibaba/nacos#1246]
Some resources of the web in the company's intranet environment need to be downloaded from alibaba cdn. Can it be modified to load the root path?

**Comment by nkorange** [comment]
Yes, this makes sense.

**Comment by loadchange** [comment]
> Some resources of the web in the company's intranet environment need to be downloaded from alibaba cdn. Can it be modified to load the root path?
Can you provide a screenshot of the network panel?

**Comment by nkorange** [comment]
Will be tracked in #1520
