### ISSUE TITLE
The issue with Nacos configuration log output.

### ISSUE THREAD

**Issue by guodeng1219** [alibaba/nacos#12462]
My actual configuration center port number is 8849, but the Nacos configuration tool class outputs 8848. I have successfully pulled the configuration, and the Nacos configuration properties printed by the method executed after Spring Boot initialization show 8849. What could be the reason for this discrepancy?
![image](https://github.com/user-attachments/assets/667d6d0c-a316-4968-8326-bc22d68fa0c7)
Here are the versions of JDK, Spring Boot, Spring Cloud, and Nacos that I am using.
![image](https://github.com/user-attachments/assets/9bfb580e-b00c-4f5f-adf4-e0d8ad2943ba)

**Comment by KomachiSion** [comment]
print 8848 means the NacosConfigProperties read the value is empty or 8848. Maybe you should debug to find out NacosConfigProperties read which configuration. 

If can't find problem. Please submit issue to spring cloud alibaba community.
