### ISSUE TITLE
客户端经常报com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.TimeoutException: Waited 3000 milliseconds异常

### ISSUE THREAD

**Issue by besthanliu** [alibaba/nacos#12468]
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 78437 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@29473b57[status=PENDING, info=[GrpcFuture{clientCall=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@6b48c374, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@79c1c26f, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@1428183e}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:195)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:306)
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:521)
	at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:369)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	

请问有什么配置可以让延长这个3000 ms的超时时间.
我在nacos配置中心配置:
![image](https://github.com/user-attachments/assets/76848960-0df0-4896-81c3-68ebc4b8fc22)

 
但没生效

**Comment by HMYDK** [comment]
same as #12103

**Comment by HMYDK** [comment]
```xml
nacos:
  config:
    config-long-poll-timeout: 500009
```

1. 以上配置对应：`PropertyKeyConst`中的超时时间配置-->`configLongPollTimeout`

2. `ClientWorker`在初始化时，会解析以上配置，获取一个「最大超时时间」，并赋值`timeout`
![image](https://github.com/user-attachments/assets/be4bfa5c-91e9-493a-9067-fcde972bd80c)


3. 但后续`ClientWorker`中的方法没有使用上述的`timeout`，而是代码中默认使用**3000**
![image](https://github.com/user-attachments/assets/7f4ba8ad-a5eb-429c-a601-55c991ebb1cb)



@KomachiSion 默认值3000的设定是考虑到上层框架（dubbo、sc）的限制？还是说这算是一个bug？

**Comment by besthanliu** [comment]
> ```
> nacos:
>   config:
>     config-long-poll-timeout: 500009
> ```
> 
> 1. 以上配置对应：`PropertyKeyConst`中的超时时间配置-->`configLongPollTimeout`
> 2. `ClientWorker`在初始化时，会解析以上配置，获取一个「最大超时时间」，并赋值`timeout`
>    ![image](https://private-user-images.githubusercontent.com/27269137/355695681-be4bfa5c-91e9-493a-9067-fcde972bd80c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTI4NDMsIm5iZiI6MTcyMzAxMjU0MywicGF0aCI6Ii8yNzI2OTEzNy8zNTU2OTU2ODEtYmU0YmZhNWMtOTFlOS00OTNhLTkwNjctZmNkZTk3MmJkODBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2MzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMDRjNzI3YTFiNmRkZWQ2ZTM4OWViNjM1NDMzZWJlZDZhNjE4MzRhODQyYWYzNTU0ZDMzMGMwZGNhOTZlZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c1vAx9dnXxjC2Qm2qSWpAbQy26p86sG4yuay1hra5H0)
> 3. 但后续`ClientWorker`中的方法没有使用上述的`timeout`，而是代码中默认使用**3000**
>    ![image](https://private-user-images.githubusercontent.com/27269137/355696403-7f4ba8ad-a5eb-429c-a601-55c991ebb1cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTI4NDMsIm5iZiI6MTcyMzAxMjU0MywicGF0aCI6Ii8yNzI2OTEzNy8zNTU2OTY0MDMtN2Y0YmE4YWQtYTVlYi00MjljLWE2MDEtNTVjOTkxZWJiMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2MzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZTZlNDE3MDkxYzkwZjg1NjQzNmQ1MmMxZjcwY2Y3NTg2NDRhYzZjN2JmMTFkMDI5OWFjY2JjNTRhYWE1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ohg7QEOofjM9IBaCaf2iLSPdPpCzWut8huke4j5_7-A)
> 
> @KomachiSion 默认值3000的设定是考虑到上层框架（dubbo、sc）的限制？还是说这算是一个bug？

我这个也是从代码里找到的: com.alibaba.nacos.common.remote.client.grpc.DefaultGrpcClientConfig.Builder.fromProperties(Properties)

我试了相关配置不生效,不过这些java opt有用:

-Dnacos.remote.client.grpc.timeout=${请求超时，单位毫秒，默认3000}

检测所连接的服务端是否健康，不健康则触发重连
-Dnacos.remote.client.grpc.server.check.timeout=${服务端健康检测，单位毫秒，默认3000}

检测当前连接状态是否健康，不健康则触发重连
-Dnacos.remote.client.grpc.health.timeout=${连接健康检测，单位毫秒，默认3000}

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/manual/user/java-sdk/properties/#24-%E8%BF%9E%E6%8E%A5%E7%9B%B8%E5%85%B3

文档里有说明， 目前连接相关的配置暂时仅支持 jvm参数。

**Comment by besthanliu** [comment]
@KomachiSion 这个配置直接无效
![image](https://github.com/user-attachments/assets/69ac1670-cbff-4ac6-b34f-4b02f847ba6a)
![image](https://github.com/user-attachments/assets/2f9dc1ff-6588-4052-9b9e-3b6121b3892d)
