### ISSUE TITLE
Endpoint can't be accessed, Colima Env

### ISSUE THREAD

**Issue by linksgo2011** [alibaba/nacos#12463]
**Describe the bug**

Endpoint can't be access, due to the network issue 

<img width="892" alt="image" src="https://github.com/user-attachments/assets/5a942e16-6374-4036-906c-1f7e0cd3075e">

**Expected behavior**

I can access to Nacos admin 

**Actually behavior**
 It shows me networkissue 

**How to Reproduce**

- Mac M2 OS
- Docker
- Colima env for Docker

**Additional context**
Same docker env, but redis/mysql works well

**Comment by fuhouyu** [comment]
if nacos start success, check your docker port 8848 is open.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
