### ISSUE TITLE
Nacos对于Service Metadata大小的限制问题

### ISSUE THREAD

**Issue by dobyte** [alibaba/nacos#12466]
Nacos能够将Service Metadata的1024大小限制改为可配置的。很多场景下，我们都是需要Service Metadata超过1024限制的。

**Comment by KomachiSion** [comment]
1024的长度其实已经很长了， 目前已知只有dubbo的服务在某些场景下容易超过，
可以描述一下您metadata中的用法和内容吗？

长度可配置看下社区是否有同学愿意修改，加一个配置进行修改好了。

**Comment by fuhouyu** [comment]
@i will solve it@

**Comment by zsdning** [comment]
我也遇到这个场景，这个长度超过1024或者多少后，会出现什么问题
