### ISSUE TITLE
dataId seataServer.properties 404 not found

### ISSUE THREAD

**Issue by slievrly** [alibaba/nacos#12475]
**Describe the bug**

case1: dataId consists of lowercase letters and dots

dataId：seataserver.properties  
group:   SEATA_GROUP

![image](https://github.com/user-attachments/assets/02334c3d-6245-4594-93ef-881e172e1640)
![image](https://github.com/user-attachments/assets/9e750fe6-d67f-4529-b6b1-031ad079eef5)

test OK

case2: dataId consists of upper and lower case letters and dots
dataId：seataServer.properties 
group:   SEATA_GROUP

![image](https://github.com/user-attachments/assets/3f364ee9-bed5-4887-a4a6-335007bc5e39)
![image](https://github.com/user-attachments/assets/4cdef846-5024-476e-8013-a86de2e612a4)

test Fail

<br class="Apple-interchange-newline">

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version : Nacos-Server 2.4.0
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by fuhouyu** [comment]
<img width="633" alt="image" src="https://github.com/user-attachments/assets/749c798a-e097-463a-851e-4d6bbf3b7194">
check your config, after `seataServer.properties` exists special character

**Comment by KomachiSion** [comment]
I see,  your `seataServer.properties` with the special word `^@` which can show in browser, Please remove old config and publish a new one without `^@`  retry.
