### ISSUE TITLE
问题咨询

### ISSUE THREAD

**Issue by hezhangbo** [alibaba/nacos#12476]
微服务注册到nacos后IP如:192.168.1.3，过段时间，微服务所在的服务器IP自动发生了变化如192.168.1.4，但是微服务是没有重启的，服务器也没有重启。nacos中的服务IP还是192.168.1.3，怎样才能让这个IP自动变成192.168.1.4，而不是人为的重启服务或服务器

**Comment by ALiSang-Mr** [comment]
我提供一下我的想法吧：你可以在微服务注册自己的IP到数据库里或缓存里，然后监听服务器IP，判断比较如果当前服务器IP发生了变化，就调用nacos的客户端API下线此服务，再获取新的IP地址去调用注册服务的方法，这样就不需要人为的重启服务了

**Comment by ALiSang-Mr** [comment]
我提供一下我的想法吧：你可以在微服务注册自己的IP到数据库里或缓存里，然后监听服务器IP，判断比较如果当前服务器IP发生了变化，就调用nacos的客户端API下线此服务，再获取新的IP地址去调用注册服务的方法，这样就不需要人为的重启服务了，你可以试试

> 微服务注册到nacos后IP如:192.168.1.3，过段时间，微服务所在的服务器IP自动发生了变化如192.168.1.4，但是微服务是没有重启的，服务器也没有重启。nacos中的服务IP还是192.168.1.3，怎样才能让这个IP自动变成192.168.1.4，而不是人为的重启服务或服务器

**Comment by KomachiSion** [comment]
这是什么神奇的用法，ip变了但是服务器没重启。。。

如果是这种特殊的场景， 只能是自行判断，然后注册新ip，注销旧ip了

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
