### ISSUE TITLE
springboot 2.X已经停更了 目前已经出现了很多CVE问题 希望可以将server服务升级到boot3.X版本并支持一下虚拟线程 这样性能肯定会提高一些 安全性也有保障

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/nacos#12471]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
planning in Nacos 3.0 and doing in https://github.com/alibaba/nacos/issues/12028
