### ISSUE TITLE
Namespace contains underline can not fetch config

### ISSUE THREAD

**Issue by jsbxyyx** [alibaba/nacos#12470]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] windows10
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] 2.2.3
 - Module [e.g. naming/config] config
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo] original

**Additional context**

**Comment by KomachiSion** [comment]
Please provider more detail information in issue description

**Comment by jsbxyyx** [comment]
nacos console config:
namespace id: 2_0

application log like:
...... fixed-nacos-svc_8848_nacos-20....

**Comment by KomachiSion** [comment]
I test in my env, work well, can you provide an demo for community to reproduce?

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
