### ISSUE TITLE
Question about metadata update

### ISSUE THREAD

**Issue by Fengshawn** [alibaba/nacos#12488]
## Issue Description
![image](https://github.com/user-attachments/assets/a4014906-0ad0-4fd9-be9f-d7125fd3460b)

Hi guys,
I am using Nacos for GPUs discovery. Like the screenshot shows, I have a service deployed on several nodes, each node has 3 GPUs (executors).  Because I am using metadata to record status of each GPU, when GPU is doing AI model inferencing, it would call Nacos sdk to update corresponding executor{i}, idle -> busy, when inferencing is over. executor{i} busy -> idle  

I was expected metadata could only update one key, but it turns out that each time when I try to update a single key in metadata, it would replace the old metadata with a new one
Is there any API or method to only update a single key in metadata rather than all keys in metadata?

### Tell us your environment
Nacos 2.4.0

Thans anyway

**Comment by KomachiSion** [comment]
The metadata is an whole object for nacos instance and service, so the update api and register api only can accept an whole metadata to do update and whole replaced.

There is some one in community commit an `patch` api to update one or some of metadata keys, but it is still an beta api. And no response about this API. 

https://nacos.io/docs/latest/manual/user/open-api/#36-%E6%89%B9%E9%87%8F%E6%9B%B4%E6%96%B0%E5%AE%9E%E4%BE%8B%E5%85%83%E6%95%B0%E6%8D%AE

For your situation, my suggestion and the best way is:

Build and register an instance in your GPU app, and see all executors with idle, keep this instance object in app memory.
When some works is doing, and executors become busy, set the instance metadata with all executors status and redo register for this instance with same nacos client obj to replaced metadata. Also redo this when works finished and executors become idle.

In this way, you can  be easy to maintain the executors status for the final status and don't consider how to update one key.

**Comment by Fengshawn** [comment]
Thanks for your reply,
I may consider assigning a "virtual" IP/Port" for each GPU, so that each GPU executor(process) is a instance, just to avoid multi GPU executors(process) compete for one metadata and that works, thanks anyway
