### ISSUE TITLE
帮忙：鉴权问题

### ISSUE THREAD

**Issue by waymen** [alibaba/nacos#12482]
请教下，我将nacos升级到了最新的2.4版本，但是默认是直接不需要用户名与密码就可以进控制台的，因为提示要开启鉴权，但是开启鉴权以后业务就掉线了，因为代码上没有开启鉴权
能不能控台还是提示需要用户密码登录，程序上不开启什么鉴权（像以前版本一样）

**Comment by HMYDK** [comment]
没有升级客户端？

**Comment by KomachiSion** [comment]
目前不支持， 正在开发中https://github.com/alibaba/nacos/issues/12017
