### ISSUE TITLE
Namespaces are presented as lists

### ISSUE THREAD

**Issue by tonycody** [alibaba/nacos#12486]
![image](https://github.com/user-attachments/assets/f4c1faeb-4e96-433f-81ee-a51be4c4f570)

1. Namespaces can only be selected one at a time
2. After more namespaces, the existing display area will be very messy, resulting in the page being propped up very strangely.

Based on the above 2 points, it is suggested that the namespaces should be presented in a list on each page to make it more friendly.

1.命名空间每次只能选一个
2.命名空间多了之后在现有的显示区域会很乱，导致页面也被撑的很奇怪

基于以上2点，建议命名空间在各页面以列表呈现会更友好一些。

**Comment by tonycody** [comment]
I'll fix it.

**Comment by 985492783** [comment]
see #12311

**Comment by KomachiSion** [comment]
I seems finished in #12311
