### ISSUE TITLE
springcloud nacos 1.5.1版本注册时添加鉴权账号密码，报403错误，求解怎么配置

### ISSUE THREAD

**Issue by wangb3592** [alibaba/nacos#12496]
依赖版本：
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>1.5.1.RELEASE</version>
        </dependency>
注册配置：
spring：
  cloud:
    nacos:
      discovery:
        username: test
        password: test
        server-addr: 127.0.0.1:8848
报错：
**java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([127.0.0.1:8848]) tried: failed to req API:127.0.0.1:8848/nacos/v1/ns/service/list. code:403 msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Aug 15 22:18:07 GMT+08:00 2024</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>**

**Comment by KomachiSion** [comment]
版本过低，不支持，升级到新版本的spring cloud alibaba即可。

具体从那个版本开始支持，请到spring cloud alibaba社区询问
