### ISSUE TITLE
Separate spring cloud starter Alibaba Acos discovery dependencies from the springboot project

### ISSUE THREAD

**Issue by zzuchen** [alibaba/nacos#12499]
I want to set the scope of the spring-cloud-starter-alibaba-nacos-discovery dependency used in the springboot project to provided, then package the project into a war package, move the dependencies related to spring-cloud-starter-alibaba-nacos-discovery to the lib public directory of tomcat, and finally deploy the war package to tomcat. However, I encountered an error that it could not be started. Is this method feasible from a technical point of view?

**Comment by KomachiSion** [comment]
please move to spring cloud alibaba community
