### ISSUE TITLE
整个nacos控制台，账号无权限的命名空间不显示，即显示有权限的命名空间。如配置管理和服务管理里面的各列表，还有命名空间管理

### ISSUE THREAD

**Issue by jaimyjie** [alibaba/nacos#12500]
整个nacos控制台，账号无权限的命名空间不显示，即显示有权限的命名空间。如配置管理和服务管理里面的各列表，还有命名空间管理

谢谢

**Comment by KomachiSion** [comment]
目前不支持，鉴权是针对资源的前置检验， list接口的权限只要有，应该就是展示出内容，至于选择对应无权限资源时再提示对应资源无权限，否则的话鉴权和数据就必须耦合。这个目前社区没有对此支持的计划。

如果您需要，可以自行修改源码，将鉴权插件侵入到数据处理的过程中，对返回数据进行过滤。

**Comment by jaimyjie** [comment]
感觉理解不一致，今天看了下代码和数据库结构，如配置管理的列表(如下图红色位置)，是独立一个接口调用所有命名空间出来，用户点击某个命名空间，再调用另外接口判断是否有权限进去。理论是红色部分这个接口改下，仅把自己有分配命名空间权限的列出来就可以。其他地方不用改，但我不太懂js，自己搞不定，如果老师有空看看是否可以安排下，实在不行，我再研究下js自己来，谢谢
![image](https://github.com/user-attachments/assets/d655b40d-f75c-4c56-8302-4ac169b86f61)

**Comment by 985492783** [comment]
有点道理，我觉得加个是否鉴权的参数，默认false就好了，控制台传true做鉴权筛选一下，运维操作调用不会改变行为

**Comment by KomachiSion** [comment]
很好理解的事情， 鉴权针对的是接口的做的， 比如listNamespace接口， 是在调用这个接口之前，判断是否有这个接口的权限，而listNamespace里没有具体的namespace参数， 那么只要有这个接口权限，验证权限就通过了，那么就会去读取namespace列表的数据。且由于鉴权已经结束了，所以不会对返回的namespace数据进行过滤。

如果需要满足issue描述的需求， 就不能只在接口前做鉴权，而是需要在接口前做一次鉴权， 有没有list权限，有的话，获取数据，然后再对数据再进行一次鉴权过滤，这就导致鉴权入侵了业务代码（至少需要判断具体的类型，比如listNamespace，listService，listConfig 等等）。

当然我理解你们的需求，在一些特殊场景可能是不希望看到没权限的内容在列表中出现，但是这个场景对于社区本身的鉴权插件设计有一定的冲突，所以目前不会支持，您可以自行在fork代码中加入这个逻辑。
