### ISSUE TITLE
[Bug] Watch the wrong application.properties file when starting up the nacos server

### ISSUE THREAD

**Issue by lingyufei** [alibaba/nacos#12519]
**Describe the bug**
When staging up the nacos server, `registerWatcher` would be invoked. However, the file being watched is `/home/user/nacos/conf/application.properties`, and the file and properties being reloaded in the `onChange` method is `classpath/application.properties` or `${spring.config.additional-location}/application.properties`. It's inconsistent.

**Expected behavior**
The file being watched and the file being reloaded should be the same, which should be `classpath/application.properties` or `${spring.config.additional-location}/application.properties`.

**Actually behavior**
Currently, the file being watched is `/home/user/nacos/conf/application.properties`, and the file and properties being reloaded in the `onChange` method is `classpath/application.properties` or `${spring.config.additional-location}/application.properties`.

**How to Reproduce**
1. Go to 'com.alibaba.nacos.core.listener.StartingApplicationListener#registerWatcher'
2. Check the following code:
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/c1b89083-0a1c-4ec5-a65d-d8401f4c2faf">

**Desktop (please complete the following information):**
 - OS: macos
 - Version 2.4.1

**Additional context**

**Comment by KomachiSion** [comment]
The feature should be watch `$nacos_home/conf/application.properties`. so current behavior is not problem.

And from the `startup.sh`, the `spring.config.additional-location` is `file:${BASE_DIR}/conf/` and `BASE_DIR` is `$nacos_home` 

And from my test, this feature can work well in 2.4.1.

```text
nacos.log:2024-09-02 14:14:17,744 INFO Get historyConfigCleaner config from env, activeHistoryConfigCleaner{ activeHistoryConfigCleaner=nacos}
nacos.log:2024-09-02 14:14:17,750 INFO Get topN config from env, TopNConfig{enabled=true, topNCount=10, internalMs=30000}
nacos.log:2024-09-02 14:14:37,745 INFO Get historyConfigCleaner config from env, activeHistoryConfigCleaner{ activeHistoryConfigCleaner=nacos}
nacos.log:2024-09-02 14:14:37,750 INFO Get topN config from env, TopNConfig{enabled=false, topNCount=10, internalMs=30000}
```

I set `nacos.core.monitor.topn.enabled` from true to false, it can read and effect.
