### ISSUE TITLE
使用nacos-server:v2.4.0.1升级到nacos-server:v2.4.1版本启动报错

### ISSUE THREAD

**Issue by liuxin638507** [alibaba/nacos#12512]
3节点集群模式，使用nacos-server:v2.4.0.1升级到nacos-server:v2.4.1版本启动报错，回退到2.4.0.1又正常
![image](https://github.com/user-attachments/assets/96afaee3-b103-4f6c-93e9-be0646e0fab3)

**Comment by KomachiSion** [comment]
没看到有错误，看到的是启动成功，然后server被主动shutdown了。可能需要排查下你自己的环境， 是不是有什么脚本会执行kill或者shutdown

**Comment by liuxin638507** [comment]
> 没看到有错误，看到的是启动成功，然后server被主动shutdown了。可能需要排查下你自己的环境， 是不是有什么脚本会执行kill或者shutdown

就是更换了nacos-server:v2.4.1镜像，其他什么操作也没有，就是启动不起来，换成nacos-server:v2.4.0.1又好了，而且重新创建nacos库，初始化使用的脚步是：https://github.com/alibaba/nacos/blob/develop/distribution/conf/mysql-schema.sql，仍然启动报错，k8s环境v1.30.3和v1.28.10都试过了也一样

**Comment by KomachiSion** [comment]
从上面的截图日志看，是启动起来了， 然后又被停止了， 你看下你k8s的liveness配置之类的是不是有问题，导致会杀pod

**Comment by liuxin638507** [comment]
> 从上面的截图日志看，是启动起来了， 然后又被停止了， 你看下你k8s的liveness配置之类的是不是有问题，导致会杀pod

你能看下我上面的回复吗？要是配置有问题，为什么我用2.4.0.1怎么都好使，用2.4.1上面已经描述的很清楚，麻烦你按上面部署验证就能知道问题所在

**Comment by KomachiSion** [comment]
那你把liveness去掉试试看。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by liuxin638507** [comment]
> 那你把liveness去掉试试看。

我改成v2 接口现在启动正常了,但是v1使用升级前v2.4.0.1j版本镜像的时候是可以的，不知道v1和v2健康接口具体有什么区别
~~~bash
        startupProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            scheme: HTTP
            port: 8848
            path: /nacos/v2/console/health/readiness
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          httpGet:
            scheme: HTTP
            port: 8848
            path: /nacos/v2/console/health/livenes
~~~
