### ISSUE TITLE
when registry center and config center separate，I found a bug

### ISSUE THREAD

**Issue by cens7** [alibaba/nacos#1251]
## When the configuration center is separated from the registry, there are problems with the configuration center files.

Type: *bug report* or *feature request*

### 
hello. In the development process, we separate the configuration center from the registry. When the configuration file is published carelessly in the registry, the configuration file we see in the configuration center is also up to date, because they share the same database. However, the configuration files actually used in the application were released in the configuration center for the last time. This problem has been bothering me for a long time. The solution is to redistribute the configuration file in the configuration center.

I hope You can fix this bug. Thanks.

**Comment by nkorange** [comment]
Not quite understand what your problem is. Currently the start mode of Nacos doesn't really separate the code of config module and naming module.
