### ISSUE TITLE
Add nacos server login password complexity

### ISSUE THREAD

**Issue by liuliqw** [alibaba/nacos#12518]
Now Nacos server login password complexity is too simple, there is a certain security risk.
We want to increase the complexity of the Naocs Server login password, and increase the corresponding validation

**Comment by 985492783** [comment]
see [auth plugin](https://nacos.io/docs/latest/plugin/auth-plugin/)

**Comment by KomachiSion** [comment]
From 2.4.0, remove the defult password, and you can setting an custom password. You can set an complex password.

And even you sue before 2.4.0, you also can change the password to complex one.

If nacos default auth plugin can't adapt yout wanted. You can implementation your own auth plugin .
