### ISSUE TITLE
nacos2.4.1较大概率不进行raft选主

### ISSUE THREAD

**Issue by wuqtao** [alibaba/nacos#12526]
k8s环境启动3节点集群，经常有一个节点长时间卡在Nacos is staring…状态，pod启动两三分钟后alipay-jraft.log日志文件依然为空，无选主日志，pod多次重启后有概率可以成功启动。
其他正常节点，一般启动后5s左右alipay-jraft.log日志文件就会有日志输出。
   2.4.0.1等之前版本无该问题，希望尽快修复，谢谢。

**Comment by KomachiSion** [comment]
无法复现此问题，能否在复现时 使用jstack指令输出一下堆栈， 看下main方法的堆栈位置是卡在哪里。

**Comment by wuqtao** [comment]
> 无法复现此问题，能否在复现时 使用jstack指令输出一下堆栈， 看下main方法的堆栈位置是卡在哪里。

我这边是大概率(复现率90%以上)复现的，我下面贴下jstack信息，有个死锁

**Comment by wuqtao** [comment]
![IMG_20240823_091414](https://github.com/user-attachments/assets/8e3a1b9f-92d9-4efa-958c-f2a50da5d1be)
![IMG_20240823_091425](https://github.com/user-attachments/assets/06369164-6cc8-4fa2-bfa9-92e5e6722827)
![IMG_20240823_091453](https://github.com/user-attachments/assets/e496d805-91dc-4385-87ba-584323f8c81d)
![IMG_20240823_091505](https://github.com/user-attachments/assets/03fcf5cd-9495-459c-956b-0a360b238a67)
![IMG_20240823_091512](https://github.com/user-attachments/assets/a4e97b0b-e36b-47b9-84bf-0a80368b66f6)
![IMG_20240823_091521](https://github.com/user-attachments/assets/830a0456-4b2c-4171-a001-dbc7cf390223)

**Comment by wuqtao** [comment]
![IMG_20240823_101229](https://github.com/user-attachments/assets/bcaafa11-50c7-4b9e-8702-e93cea080aa7)
![IMG_20240823_101308](https://github.com/user-attachments/assets/4dc5fb83-8bcb-461d-85a3-aa0e5c9da873)

**Comment by KomachiSion** [comment]
拍照看起来太麻烦了，同时也无法检索， 能否上传一份stack文件。

**Comment by KomachiSion** [comment]
另外部署模式是集群+derby？

**Comment by wuqtao** [comment]
> 另外部署模式是集群+derby？

对的，集群+derby

**Comment by wuqtao** [comment]
> 拍照看起来太麻烦了，同时也无法检索， 能否上传一份stack文件。

[nacos-jstack.log](https://github.com/user-attachments/files/16776909/nacos-jstack.log)
here is the log of jstack

**Comment by fuxiuzhan** [comment]
多线程初始化bean导致死锁了。
