### ISSUE TITLE
如果nacos集群所有节点宕机，影响是？

### ISSUE THREAD

**Issue by andyyumiao** [alibaba/nacos#12523]
如果nacos集群所有节点宕机（集群不可用），这时的对配置和服务发现的影响分别是什么呢？
请问这里有没有相关的文档和代码说明，想咨询了解下细节

**Comment by 985492783** [comment]
nacos官方sdk的服务发现和配置都是有本地快照的，服务器不可用的情况下会加载快照

**Comment by KomachiSion** [comment]
影响：

新发布的服务会无法被探测到。
新发布的配置无法被应用获取到。
新应用启动时如果本地没有配置快照，可能无法启动。
