### ISSUE TITLE
Windows nacos use ip:port to create a snapshot folder failed

### ISSUE THREAD

**Issue by wangzeyan999** [alibaba/nacos#1253]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Failed to create local snapshot folder
本地快照文件夹创建失败

### How to reproduce it (as minimally and precisely as possible)

1.  : Special symbol ':' causes folder creation to fail  (特殊符号 ':' 导致文件夹创建失败)
```
class-method:
com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor.saveSnapshot(String envName, String dataId, String group, String tenant, String config)

// envName="fixed-192.168.2.10:8848-tenantId"
boolean isMdOk = file.getParentFile().mkdirs();
if (!isMdOk) {
	log.error(envName, "NACOS-XXXX", "save snapshot error");
}

```

### Tell us your environment
1.  windows  
2.  nacos-config-spring-boot-0.2.1
3.  bootstrap.yml 

> nacos.config:
  serverAddr: "192.168.2.10:8848"

**Comment by nkorange** [comment]
Yes, currently you have to avoid to use colon as part of data id in Windows.
