### ISSUE TITLE
nacos管理端界面输入框输入内容只要包括 [] 中的一个，查询会报HTTP Status 400 – Bad Request错误

### ISSUE THREAD

**Issue by LiuRambo** [alibaba/nacos#12530]
当前使用情况为除 服务管理 -> 服务列表 -> 服务名称输入框 输入中括号查询正常外，其余输入框输入只要包含中括号就回报错

**Comment by HMYDK** [comment]
非常规用法。一般来讲，不会有这种使用方式。

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/manual/user/parameters-check/#24-serviceservicename

分组之类的参数，不允许特殊字符， 服务名限制比较宽，但是也有限制。
