### ISSUE TITLE
配置中心添加appname级别权限控制

### ISSUE THREAD

**Issue by kangzhaok** [alibaba/nacos#12535]
目前nacos配置中心可根据命名空间区分环境，但是缺少appname级别的权限控制，希望能够实现appname级别的权限控制。
根据公司需求已完成appname权限控制，欢迎各位老师沟通交流。

**Comment by KomachiSion** [comment]
app 在nacos中是一个很弱化的概念，一般作为配置和服务的或者订阅者的一个标签，如果鉴权需要和app绑定，那么就使得app成为一个强概念了， 和社区的设计有很大冲突， 目前社区应该不会接受。

您可以将这个权限控制作为一个plugin的实现插件， 贡献到nacos-group/nacos-plugin中， 并在对应插件的readme中表达使用方式等。

**Comment by kangzhaok** [comment]
> app 在nacos中是一个很弱化的概念，一般作为配置和服务的或者订阅者的一个标签，如果鉴权需要和app绑定，那么就使得app成为一个强概念了， 和社区的设计有很大冲突， 目前社区应该不会接受。
> 
> 您可以将这个权限控制作为一个plugin的实现插件， 贡献到nacos-group/nacos-plugin中， 并在对应插件的readme中表达使用方式等。

app目前看更多是一个数据权限，通过nacos-plugin想了一下不太能够实现。

**Comment by KomachiSion** [comment]
app是个标记概念， 意味着你可以不指定app，使用默认值'unkown', 若需要和鉴权绑定，那么意味着你**必须**指定app，且不能指定错误，

这导致app从一个可选的标记概念，变成一个强相关的权限概念， 这和其设计初衷， 方面在某种可选程度上进行资源标记和过滤有极大冲突，所以目前大概率不会在社区支持。

Nacos的资源概念只有3层：命名空间、Group、和资源名（服务或配置dataId）

这3者即使唯一性保证，也是获取对应资源的主要索引。

默认鉴权插件仅提供到命名空间这个层级，因为命名空间被设计为资源的强隔离维度（客户端无法访问不同命名空间的资源）。

**Comment by KomachiSion** [comment]
No more response from discussion, and from current discussion, the feature should not be supported.
