### ISSUE TITLE
2.2.0.1控制台服务详情页，点上线，服务依然无法上线

### ISSUE THREAD

**Issue by yangaoting** [alibaba/nacos#12546]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

服务实例是正常的，但是点上线也上线不了，遇到好几次，都是通过改服务名重启实例，解决的。想知道这是什么原因导致的

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
需要更多细节， 只看描述推测是集群搭建的有问题， 导致raft无法选主，点击上下线的操作本质是修改元数据，而修改元数据是通过raft实现的，让raft无法选主时，这部分功能会被降级。

**Comment by waymen** [comment]
同遇到这个问题，k8s部署的三个pod，在控制台点击下线，没反应，浏览器没看到什么异常

**Comment by KomachiSion** [comment]
看下浏览器控制台，看下response的信息。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
