### ISSUE TITLE
通过restful接口更新持久化switchdomain失败

### ISSUE THREAD

**Issue by zds-bryant** [alibaba/nacos#12545]
本地存储了但是没有更新内存里的
<img width="689" alt="image" src="https://github.com/user-attachments/assets/a549ebf0-5ed9-4dd6-aebb-6f4c648db423">
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/96114705-c2e0-4214-8b8f-ef729306105b">

**Comment by zds-bryant** [comment]
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/8a1e6f7c-ad93-4668-850b-1a8152f55cc3">
<img width="748" alt="image" src="https://github.com/user-attachments/assets/e7047dce-c41a-45e7-a30b-0f29e8876603">

**Comment by zds-bryant** [comment]
是哪里使用的有问题吗

**Comment by XiaZhouxx** [comment]
试试debug=true呢

**Comment by zds-bryant** [comment]
> 试试debug=true呢

这个更新了内存里，但是无法持久化

**Comment by XiaZhouxx** [comment]
> > 试试debug=true呢
> 
> 这个更新了内存里，但是无法持久化

老哥我看了一下历史的issue 应该是这个原因 #11446,可以看看版本和尝试更改这个参数, 但是我看你使用的是standalone模式？`StandalonePersistentServiceProcessor` 这个启动模式下开启了这个参数还是会无法更新内存. 并且我看在2.4.1版本已经重构了这里的代码并且standalone启动模式只能使用debug=true才能修改内存中的值, 请教一下大佬 @KomachiSion 这里是设计就是如此还是有什么原因吗？

**Comment by zds-bryant** [comment]
非常感谢老哥 @XiaZhouxx 的解答，确实，我对单机模式下这个无法持久化的动作不太理解，不知道是否设计如此还是之后会调整 请教一下大佬 @KomachiSion

**Comment by zds-bryant** [comment]
@XiaZhouxx 我看了2.4.1的源代码是没问题的，本地试过了
