### ISSUE TITLE
Nacos服务端 1.2.1 版本 OOM

### ISSUE THREAD

**Issue by javazhangyi** [alibaba/nacos#12540]
Nacos服务器版本1.2.1 OOM，由于org.apache.communs.dbcp PoolableConnectFactory创建了太多对象

服务配置
     2G内存，3个节点，服务注册数7个
     备注：三个节点发现是，都已经无法提供服务

hprof文件截图
![image](https://github.com/user-attachments/assets/8db4571a-63a0-4da9-b8df-ebc597d4af68)

崩溃导致直接原因
![image](https://github.com/user-attachments/assets/e8da6ed8-dbda-406f-ae62-d29e16cd141c)

![image](https://github.com/user-attachments/assets/0fafcc8e-b727-45b8-a52a-7657df4a6252)

**Comment by KomachiSion** [comment]
版本过旧，请升级到新版本后尝试。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.
