### ISSUE TITLE
关闭 /actuator接口失败问题

### ISSUE THREAD

**Issue by a1156698162** [alibaba/nacos#12544]
nacos-server版本2.2.2，nacos服务端开启了鉴权并且将/actuator/** 从配置nacos.security.ignore.urls中移除
![image](https://github.com/user-attachments/assets/cdcbd671-cedc-4910-921f-b583ae615edf)
在不登录的情况下/actuator接口正常访问。预期是想访问的时候报403
![image](https://github.com/user-attachments/assets/f90d85ee-4a73-46d2-b7e9-9a7ff3f17418)

**Comment by kangzhaok** [comment]
AuthFilter中对于方法有Secured注解的才会鉴权

**Comment by a1156698162** [comment]
将/actuator/** 从配置nacos.security.ignore.urls 删除后依然能正常访问也不对吧

**Comment by KomachiSion** [comment]
nacos的鉴权不依赖spring security， nacos.security.ignore.urls应该是从1.2.1之前版本遗留的配置（早起版本没有鉴权系统，只是简单依赖spring security做了一个登录）。

**Comment by a1156698162** [comment]
意思是nacos.security.ignore.urls这个配置是没有用的吗

**Comment by KomachiSion** [comment]
> 意思是nacos.security.ignore.urls这个配置是没有用的吗

是的，如果选择使用nacos的默认鉴权插件，nacos.security.ignore.urls这个值最终会被设置为`*` 

只有使用其他的自定义鉴权插件的时候， 这个值才会生效。

**Comment by a1156698162** [comment]
好的，感谢
