### ISSUE TITLE
Health check in nacos 1.0 server list has BUG

### ISSUE THREAD

**Issue by dannylincn** [alibaba/nacos#1255]
当同一个服务有多个实例数时（如3个），健康检查有问题。
所有实例都下线了，但“健康实例数”还是3，服务也不能删除。
删除服务报错：specified service has instances, serviceName : DEFAULT_GROUP@@nacos-discovery-server
点击服务，进服务详情，显示3个实例健康状态还是true.

**Comment by nkorange** [comment]
@dannylincn 你是如何下线服务的？

**Comment by JayWenChao** [comment]
@nkorange 好像在1.1.3也有这个问题，Delete service error: specified service has instances, serviceName 没有办法删除，服务实例实际上已经下线了，但是服务依旧停留在 private Map<String, Map<String, Service>> serviceMap = new ConcurrentHashMap<>();
