### ISSUE TITLE
使用运维API修改SwitchDomain部分开关无效.

### ISSUE THREAD

**Issue by XiaZhouxx** [alibaba/nacos#12555]
`Nacos 2.4.1`根据官网最新文档运维API 开关参数说明
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/2da8846a-fcb4-4816-9865-c452fd1ec005">
使用修改SwithDomain接口
<img width="1116" alt="image" src="https://github.com/user-attachments/assets/61336ad9-b87b-49fb-a862-8482d2456da4">
根据开关名称修改部分开关无效（例如`defaultPushCacheMillis, distroEnable, healthCheckEnabled 等`）
发现是entry参数内部匹配名称和`/switches`返回的开关名不一致导致, 这个是文档的遗漏还是代码问题吗？

**Comment by KomachiSion** [comment]
部分开关的显示名字和修改时的名字有一定区别， 这个属于历史遗留问题，我记得之前有个issue说打算处理这个问题，但是后来社区同学可能忙别的去了， 没有完成，文档应该是按照GET的参数名写的， 如果有空的话可以帮忙更新一下文档，加一列来表示更新该参数时需要的entry名。

**Comment by XiaZhouxx** [comment]
大佬我想尝试解决这个问题可以吗？我发现还有一些问题
1. `SwithDomain`很多配置没有引用已被废弃的是否可以剔除？
2. `version 2.4.1 standalone`启动模式非`debug=true`下已经无法调用修改,这个是设计不支持吗? 2.4.0之前支持修改但是无效, 只会持久化修改后的.
3. 是否支持`batch`? 我看现有代码逻辑是支持`entry=batch`使用`SwitchDomain Json`值的方式修改(例如`HttpHealthParams`参数逻辑上只能通过batch) 但是会绕过部分开关的值校验逻辑, 以往的文档都是没有提到的.
4. 遗漏`pushCSharpVersion`的处理.

**Comment by KomachiSion** [comment]
> SwithDomain很多配置没有引用已被废弃的是否可以剔除？

这个我记得之前有一个issue在处理， 不过具体配置是否可以移除需要更多PMC进行确认

> version 2.4.1 standalone启动模式非debug=true下已经无法调用修改,这个是设计不支持吗? 2.4.0之前支持修改但是无效, 只会持久化修改后的.

我测过可以， 如果不能修改， 请自查一下是否raft选主有问题。

> 是否支持batch? 我看现有代码逻辑是支持entry=batch使用SwitchDomain Json值的方式修改(例如HttpHealthParams参数逻辑上只能通过batch) 但是会绕过部分开关的值校验逻辑, 以往的文档都是没有提到的.

不支持，也没有计划支持， 开关接口理论上不会经常调用，如果确实有需要修改，可多次调用。

> 遗漏pushCSharpVersion的处理.

可以提交PR修复
