### ISSUE TITLE
jdk21模块化项目集成nacos.client报错

### ISSUE THREAD

**Issue by aszdKing** [alibaba/nacos#12551]
编译报错 java: 找不到模块: nacos.client

**Comment by luxiao0000** [comment]
因为模块命名为com.google.gson，在META-INF/version/9/module-info中，😮‍💨

**Comment by luxiao0000** [comment]
不理解官方为何如此命名

**Comment by KomachiSion** [comment]
没看懂问题，麻烦提供更详细的描述和报错上下文信息。

**Comment by luxiao0000** [comment]
对比fastjson2，一看就明白
<img width="717" alt="image" src="https://github.com/user-attachments/assets/04a59788-279f-4cc7-80b0-324589aa7e51">
<img width="663" alt="image" src="https://github.com/user-attachments/assets/5f11f3e2-c00c-4f3b-8b6e-2a709e5b5d0c">

**Comment by luxiao0000** [comment]
原因我想我明白了，maven-shade-plugin插件打包时会把gson里的模块化描述文件带过来，导致nacos-client错误的使用了gson的模块化描述文件

**Comment by KomachiSion** [comment]
还是没明白， 这个shaded进来的描述文件会影响什么？

**Comment by luxiao0000** [comment]
就会导致当前issues的问题，shade阶段不会编译，只是二次打包，所以不会暴露问题，https://openjdk.org/jeps/201。复现方法，构建一个模块化工程，requires nacos-client就会复现问题

**Comment by KomachiSion** [comment]
还是没太理解。 2.0.0也使用了shaded，为什么没有问题呢。

**Comment by luxiao0000** [comment]
2.0.0依赖的gson还没有模块化，所以没有问题

**Comment by KomachiSion** [comment]
> 2.0.0依赖的gson还没有模块化，所以没有问题

那有办法修复吗

**Comment by luxiao0000** [comment]
已提 pull/12660
