### ISSUE TITLE
SQLException: ERROR: LIMIT #,# syntax is not supported Hint during add configuration data from WebUI

### ISSUE THREAD

**Issue by leoxhj** [alibaba/nacos#12554]
**Describe the bug**
How we deploy nacos `v2.3.2` with `pgs 14`, also add pgs jar file in images, and installation is just work fine, and when we're trying to configure from WebUI, it throw error:

```bash
caused: serialize page error, dataId=, group=;caused: PreparedStatementCallback; bad SQL grammar [SELECT id,data_id,group_id,tenant_id,app_name,content,encrypted_data_key FROM config_info WHERE tenant_id LIKE ? LIMIT 0,10]; nested exception is org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported Hint: Use separate LIMIT and OFFSET clauses. Position: 117;caused: ERROR: LIMIT #,# syntax is not supported Hint: Use separate LIMIT and OFFSET clauses. Position: 117;
```

**Expected behavior**
config data is added without any error

**Actually behavior**
Add config data error

**How to Reproduce**
1. Go to Configuration Management -> Configurations -> create configuration
2. Input 'DataId' = "test", format=Text, 'Configuration content‘ = "test"
3. Click button 'Publish'
4. See errors

**Comment by fuhouyu** [comment]
you need enabled pg plugin,check your application.properties, `spring.datasource.platform=postgresql`.

**Comment by leoxhj** [comment]
pgs plugin already enabled, otherwise, it won't be deployed successfully at all.

**Comment by leoxhj** [comment]
if I'm correct, this issue's root cause is the pagehelper (Paging for configuration data query) used in WebUI in incompatible, so basically nacos developers need to deep look into this issue, you can refer to this online topic is discussing on it
https://blog.csdn.net/qq_39187593/article/details/133275167

**Comment by fuhouyu** [comment]
This is a paging error. datasource plugin are designed to handle these SQL differences.
I'm testing the nacos 2.3.2 and pg plugin https://github.com/nacos-group/nacos-plugin,it running success.
<img width="1843" alt="image" src="https://github.com/user-attachments/assets/e2911b74-d8c1-4b0c-808e-c400280168ee">
there may be a problem with your pg plugin. you can test use the plugin 

[nacos-postgresql-datasource-plugin-ext-1.0.0-SNAPSHOT.zip](https://github.com/user-attachments/files/16755516/nacos-postgresql-datasource-plugin-ext-1.0.0-SNAPSHOT.zip)

**Comment by leoxhj** [comment]
@fuhouyu Thank you very much for your quick answer, I forgot where I downloaded the jar file as nacos official does provide the jar file, I don't have a local build environment to build the jar file. I will try the one you provided and get back to you once tested.

**Comment by leoxhj** [comment]
@fuhouyu it just worked perfectly with your provided jar file, I'm so grateful. 
by the way, is it possible to release this jar file officially for people who don't have the local Java environment to build on their own?

**Comment by fuhouyu** [comment]
I'm not very clear about this.It may be that it is still in the testing stage and has not been released.
