### ISSUE TITLE
linux  docker 启动2.0.4版本的nacos报错

### ISSUE THREAD

**Issue by cptjackwu** [alibaba/nacos#12567]
Error creating bean with name 'tcpSuperSenseProcessor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/healthcheck/TcpSuperSenseProcessor.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.healthcheck.TcpSuperSenseProcessor]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Error while initializing SuperSense(TM).

**Comment by KomachiSion** [comment]
能否提供更多的详细日志？就是你现在贴出的错误的上下几十行

仅从现在给出的错误，`java.lang.IllegalStateException: Error while initializing SuperSense(TM).` 似乎和nacos似乎没什么关系， nacos不依赖SuperSense(TM)

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem not nacos‘ problem。
