### ISSUE TITLE
再k8s 1.17 版本中，使用 ingress 部署 2.4.1 版本，遇到端口问题

### ISSUE THREAD

**Issue by VinnyWan** [alibaba/nacos#12572]
按照官方实践部署之后，配置有 ingress如下
`
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  labels:
    appName: nacos-headless
    env: inte
    project: nacos
  name: inte-nacos-headless
  namespace: nacos
spec:
  rules:
  - host: nacos.qa.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nacos-headless
          servicePort: 8848
`

service 如下
`
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: nacos
  labels:
    app: nacos-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    ## 兼容1.4.x版本的选举端口
    - port: 7848
      name: old-raft-rpc
      targetPort: 7848
  selector:
    app: nacos
`
遇到一个问题， 当域名设置为nacos.qa.com时， k8s 集群外部应用访问这个域名是 grpc 会自动添加 1000， 但是这个端口是不对外开放的， 麻烦问下也有好的方案吗？
自建机房目前只想到一种方案
nginx TCP 四层代理到k8s的 nodeport 上，想问问还有其他方案吗？ 谢谢

**Comment by KomachiSion** [comment]
这个问题可能要移到higress 社区询问一下， 我看nacos的deploy中，9848是暴露到services里的

**Comment by johnlanni** [comment]
你是想让nacos grpc注册接口暴露到公网上吗？然后同时想暴露8848和9848？那只能通过不同的path区分开才可以。
另外要注意下nacos基于一条grpc的HTTP2连接维持服务状态，似乎不能在7层网关做负载均衡，因为网关会把客户端连接过来的grpc unary请求发到不同的nacos后端。

**Comment by VinnyWan** [comment]
> 是让nacos grpc注册接口对外公开吗？然后同时想对外公开8848和9848？那只能通过不同的路径区分开才可以。 另外要注意下nacos基于一条grpc的HTTP2连接你维持服务状态，好像不能在7层网关做负载均衡，因为网关把客户端连接过来的grpc一元请求发到不同的nacos耳机。

对的是对外公开的，是需要看下如何做才会比较优雅点

**Comment by VinnyWan** [comment]
> 我看nacos的deploy中，9848是暴露到services里的，这个可能要问下ingress专家

也可以很直接使用services 啊 但是k8s 集群外部的应用就不能直接使用了，只能使用 nodeport 进行访问了

**Comment by 985492783** [comment]
貌似nginx-ingress-nginx-tcp可以满足你的需求？你试试，通过配置configmap实现的
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  8848: "nacos.qa.com:8848"
  9848: "nacos.qa.com:9848"
  9849: "nacos.qa.com:9849"
```

**Comment by 985492783** [comment]
网关大概率实现不了，console用七层ingress-nginx反向代理，grpc用4层dns+vip吧

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems not nacos' problem.
