### ISSUE TITLE
配置文件分组问题

### ISSUE THREAD

**Issue by fcc651497387** [alibaba/nacos#12579]
未来版本希望可以 单独配置分组 单独配置分组
分组可以单独管理
在新建配置文件的时候可以 下拉选择已创建的分组

**Comment by 985492783** [comment]
group本身就是一个虚拟的概念

**Comment by KomachiSion** [comment]
是希望group和namespace一样单独管理吗？

那可能对整体使用方法上的调整会很大。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
