### ISSUE TITLE
nacos是不是部分配置不可生效啊

### ISSUE THREAD

**Issue by zxh451200** [alibaba/nacos#12588]
spring:
    main:
        banner-mode: off

为啥我配置这个还是有banner
![333333333333333](https://github.com/user-attachments/assets/9ce06801-4a25-42d6-9043-43ae0542c9df)

**Comment by HMYDK** [comment]
这不会成为项目的启动配置😂

**Comment by XiaZhouxx** [comment]
这个和nacos本身无关， 应该是取决于你使用的SDK是怎么加载配置的, 比如我自己在使用的`alibaba.cloud的sdk` 这个问题就是因为加载nacos配置的顺序在绑定spring.main配置之后所以会导致这个配置读取不到不生效

**Comment by KomachiSion** [comment]
这个问题应该是spring cloud本身定义的配置加载顺序和生命周期有关， spring cloud在读取远程配置中心的配置之前， 会加载本地一定的配置（不然都不知道远程配置的地址是什么），所以这个banner应该是这个时候加载的， 在远程配置中设置banner=false无效时因为这个配置的生效时间早于获取远程配置，无论用哪种配置中心（apollo也好，consul，sc的configserver也好）应该效果都是一样的。
