### ISSUE TITLE
## [Codecov](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba) Report

### ISSUE THREAD

**Issue by A6976** [alibaba/nacos#12590]
## [Codecov](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba) Report
Attention: Patch coverage is `15.03532%` with `842 lines` in your changes are missing coverage. Please review.
> Project coverage is 66.61%. Comparing base [(`64b9e8d`)](https://app.codecov.io/gh/alibaba/nacos/commit/64b9e8d3f7afc733a00d6d35d5344cbca5c060ba?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba) to head [(`7f84376`)](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba).
> Report is 13 commits behind head on develop.

<details><summary>Additional details and impacted files</summary>

[![Impacted file tree graph](https://app.codecov.io/gh/alibaba/nacos/pull/11856/graphs/tree.svg?width=650&height=150&src=pr&token=l4XELZqush&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba)](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba)

```diff
@@              Coverage Diff              @@
##             develop   #11856      +/-   ##
=============================================
- Coverage      67.81%   66.61%   -1.20%     
- Complexity      8893     8945      +52     
=============================================
  Files           1237     1254      +17     
  Lines          40443    41399     +956     
  Branches        4286     4422     +136     
=============================================
+ Hits           27425    27580     +155     
- Misses         11046    11805     +759     
- Partials        1972     2014      +42     
```

| [Files](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba) | Coverage Δ | |
|---|---|---|
| [...acos/client/config/impl/ConfigTransportClient.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-Y2xpZW50L3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvY2xpZW50L2NvbmZpZy9pbXBsL0NvbmZpZ1RyYW5zcG9ydENsaWVudC5qYXZh) | `86.11% <ø> (ø)` | |
| [...n/java/com/alibaba/nacos/api/common/Constants.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-YXBpL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvYXBpL2NvbW1vbi9Db25zdGFudHMuamF2YQ==) | `53.84% <0.00%> (-4.49%)` | :arrow_down: |
| [...emote/response/ConfigBatchFuzzyListenResponse.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-YXBpL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvYXBpL2NvbmZpZy9yZW1vdGUvcmVzcG9uc2UvQ29uZmlnQmF0Y2hGdXp6eUxpc3RlblJlc3BvbnNlLmphdmE=) | `0.00% <0.00%> (ø)` | |
| [...mote/response/FuzzyListenNotifyChangeResponse.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-YXBpL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvYXBpL2NvbmZpZy9yZW1vdGUvcmVzcG9uc2UvRnV6enlMaXN0ZW5Ob3RpZnlDaGFuZ2VSZXNwb25zZS5qYXZh) | `0.00% <0.00%> (ø)` | |
| [...remote/response/FuzzyListenNotifyDiffResponse.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-YXBpL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvYXBpL2NvbmZpZy9yZW1vdGUvcmVzcG9uc2UvRnV6enlMaXN0ZW5Ob3RpZnlEaWZmUmVzcG9uc2UuamF2YQ==) | `0.00% <0.00%> (ø)` | |
| [...m/alibaba/nacos/config/server/model/CacheItem.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-Y29uZmlnL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvY29uZmlnL3NlcnZlci9tb2RlbC9DYWNoZUl0ZW0uamF2YQ==) | `76.38% <0.00%> (-3.33%)` | :arrow_down: |
| [...java/com/alibaba/nacos/client/utils/ParamUtil.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-Y2xpZW50L3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvY2xpZW50L3V0aWxzL1BhcmFtVXRpbC5qYXZh) | `86.17% <62.50%> (-5.88%)` | :arrow_down: |
| [...onfig/server/configuration/ConfigCommonConfig.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-Y29uZmlnL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvY29uZmlnL3NlcnZlci9jb25maWd1cmF0aW9uL0NvbmZpZ0NvbW1vbkNvbmZpZy5qYXZh) | `72.72% <40.00%> (-27.28%)` | :arrow_down: |
| [...mote/request/AbstractFuzzyListenNotifyRequest.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-YXBpL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvYXBpL2NvbmZpZy9yZW1vdGUvcmVxdWVzdC9BYnN0cmFjdEZ1enp5TGlzdGVuTm90aWZ5UmVxdWVzdC5qYXZh) | `0.00% <0.00%> (ø)` | |
| [...acos/config/server/service/ConfigCacheService.java](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba#diff-Y29uZmlnL3NyYy9tYWluL2phdmEvY29tL2FsaWJhYmEvbmFjb3MvY29uZmlnL3NlcnZlci9zZXJ2aWNlL0NvbmZpZ0NhY2hlU2VydmljZS5qYXZh) | `75.34% <0.00%> (-1.09%)` | :arrow_down: |
| ... and [17 more](https://app.codecov.io/gh/alibaba/nacos/pull/11856?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba) | |

... and [32 files with indirect coverage changes](https://app.codecov.io/gh/alibaba/nacos/pull/11856/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba)

------

[Continue to review full report in Codecov by Sentry](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=footer&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba). Last update [64b9e8d...7f84376](https://app.codecov.io/gh/alibaba/nacos/pull/11856?dropdown=coverage&src=pr&el=lastupdated&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=alibaba).

</details>

_Originally posted by @codecov-commenter in https://github.com/alibaba/nacos/issues/11856#issuecomment-2008961135_

**Comment by KomachiSion** [comment]
No useful information in issue.

**Comment by A6976** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by A6976** [comment]
- [ ]
