### ISSUE TITLE
nacos的docker容器一启动就CPU占用率过高导致无限重启

### ISSUE THREAD

**Issue by CorrectPath** [alibaba/nacos#12603]
**Describe the bug**
nacos的docker容器一启动就CPU占用率过高导致无限重启
As soon as Naco's Docker container is started, the CPU usage is too high, resulting in an infinite restart
![屏幕截图 2024-09-04 163830](https://github.com/user-attachments/assets/a2c9675d-a9e8-4f50-8587-2adad88c13c7)

昨天还正常使用了今天突然就不行了
It was working fine yesterday, but today it suddenly doesn't work

环境变量
environment variable
[NACOS_AUTH_IDENTITY_VALUE=2xxx PREFER_HOST_MODE=hostname SPRING_DATASOURCE_PLATFORM=mysql MYSQL_SERVICE_HOST=mysql MYSQL_SERVICE_USER=root MYSQL_SERVICE_PASSWORD=123456 MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true NACOS_AUTH_IDENTITY_KEY=2222 NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789 MODE=standalone MYSQL_SERVICE_DB_NAME=nacos_config MYSQL_SERVICE_PORT=3306 PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 JAVA_VERSION=jdk8u372-b07 JAVA_HOME=/opt/java/openjdk BASE_DIR=/home/nacos CLASSPATH=.:/home/nacos/conf: CLUSTER_CONF=/home/nacos/conf/cluster.conf FUNCTION_MODE=all NACOS_USER=nacos JAVA=/opt/java/openjdk/bin/java JVM_XMS=1g JVM_XMX=1g JVM_XMN=512m JVM_MS=128m JVM_MMS=320m NACOS_DEBUG=n TOMCAT_ACCESSLOG_ENABLED=false TZ=Asia/Shanghai]

一些日志
section of the log
![屏幕截图 2024-09-04 172054](https://github.com/user-attachments/assets/0c4c6fa6-4311-4f17-a5a7-433dc28f82e7)

**Comment by CorrectPath** [comment]
来个人救救我😭
anyone help me?😭

**Comment by KomachiSion** [comment]
可以使用arthas抓一下火焰图，看一下什么地方消耗比较大，

或者统计一下qps和tps，看一下是否是因为请求过多。

**Comment by CorrectPath** [comment]
> 可以使用arthas抓一下火焰图，看一下什么地方消耗比较大，
> 
> 或者统计一下qps和tps，看一下是否是因为请求过多。

我目前还是在学习使用nacos，所以基本上没有请求

**Comment by CorrectPath** [comment]
不知道有没有人在关注我这个问题，目前我通过将nacos依赖的数据库名从nacos_config改成了nacos并且同时修改了nacos的配置文件里的数据库URL，解决了日志中报错Error creating bean with name ‘memoryMonitor‘ 、‘externalDumpService‘。然后剩下一个报错‘instanceMetadataProcessor’。无论如何也没能解决，无奈，将镜像remove掉并重新run了一个。好消息是目前能够正常运行，坏消息是我前两次也是这么解决的，然后第二天就会出现无限重启的情况，不知道明天它还能不能正常运行，不能的话我还会再来的。😥

**Comment by CorrectPath** [comment]
现在是我把nacos依赖的数据库名从nacos_config改成nacos的第二天，正常工作了，如果下周一它还没出问题我就可以结束这个issue了
