### ISSUE TITLE
standalone mode java opts -Dnacos.standalone=true not work

### ISSUE THREAD

**Issue by dupengcheng** [alibaba/nacos#1260]
## Issue Description

*bug report* 

### Describe what happened (or what feature you want)

standalone mode java opts -Dnacos.standalone=true not work

### Describe what you expected to happen
a problem maybe in this code. i will fix it.
https://github.com/alibaba/nacos/blob/develop/core/src/main/java/com/alibaba/nacos/core/utils/SystemUtils.java

    public static boolean STANDALONE_MODE = Boolean.getBoolean(STANDALONE_MODE_PROPERTY_NAME);

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
I think the original code is correct. So did you really encounter this error?

**Comment by dupengcheng** [comment]
> I think the original code is correct. So did you really encounter this error?

![image](https://user-images.githubusercontent.com/11847818/59581303-04a17700-9107-11e9-852b-9c3b3d52a20f.png)

sorry  ,  set VM options , not  Environment variables
