### ISSUE TITLE
历史版本保留天数写死了，希望可以跟着nacos.config.retention.days配置动态变化

### ISSUE THREAD

**Issue by shengbinxu** [alibaba/nacos#12614]
<img width="913" alt="image" src="https://github.com/user-attachments/assets/4b6f0182-5235-4412-989c-233426fc036c">

**Comment by 985492783** [comment]
contribute welcome

**Comment by muzhi9018** [comment]
@i will solve it@

**Comment by shengbinxu** [comment]
> @i will solve it@

我已经提交代码了，https://github.com/alibaba/nacos/pull/12616
可以帮忙review下，谢谢～
