### ISSUE TITLE
openAPI获取配置存在的问题

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#12620]
Set the state to 404 if the configuration in the ConfigServletInner class does not exist.
在ConfigServletInner类中配置不存在的时候将相应状态设置为404。
![image](https://github.com/user-attachments/assets/e13bb959-b8f4-4334-bc60-62f2a32e631d)

In the callServer method of the NamingHttpClientProxy class, an exception was thrown for 404.
NamingHttpClientProxy类中callServer方法中，对于404抛出了异常。
![image](https://github.com/user-attachments/assets/60c356c2-b171-4a92-a834-6442145b3c1f)

So the client-side approach here will simply report an error if the configuration does not exist. Throwing an exception also caused the request to be retried three times for a configuration that did not exist.
那么这里使用客户端的方法在配置不存在的时候就直接报错了。因为抛异常还导致配置不存在的这个请求重试了三次。
![image](https://github.com/user-attachments/assets/b7cc91a2-45fb-455f-aacc-1b1f6fdd4774)

I understand that the configuration does not exist, but the request is normal so it should not be set to 404. Should be the corresponding response code for the document.
我理解配置不存在，但是请求是正常的所以不应该设置为404。应该是文档的对应的响应码。

I see no problem with the handling in the NamingHttpClientProxy class, so should I change the state of the response if the configuration is not present
我觉得NamingHttpClientProxy类中的处理没有问题，所以是否应该修改配置不存在时响应的状态

**Comment by KomachiSion** [comment]
需要分情况讨论， v1/cs的接口，考虑到多个旧版本client的兼容性问题，不建议修改，避免造成旧版本客户端有更多兼容性问题。

v2/cs的接口可以改，但是我理解v2接口统一做过状态吗和错误吗的重构，应该没问题。

然后是客户端的修改，http方式的调用其实已经被废弃， 事实上现在2.x的客户端使用的是grpc进行获取配置和服务的调用，NamingHttpClientProxy和HttpClientWorker应该都已经不被调用。

1.x客户端本身不演进了，基本只修复一些安全漏洞，如果功能本身没有问题，也不推荐修改避免不兼容老版本服务端。

**Comment by MangerLe** [comment]
> 需要分情况讨论， v1/cs的接口，考虑到多个旧版本client的兼容性问题，不建议修改，避免造成旧版本客户端有更多兼容性问题。
> 
> v2/cs的接口可以改，但是我理解v2接口统一做过状态吗和错误吗的重构，应该没问题。
> 
> 然后是客户端的修改，http方式的调用其实已经被废弃， 事实上现在2.x的客户端使用的是grpc进行获取配置和服务的调用，NamingHttpClientProxy和HttpClientWorker应该都已经不被调用。
> 
> 1.x客户端本身不演进了，基本只修复一些安全漏洞，如果功能本身没有问题，也不推荐修改避免不兼容老版本服务端。

1.0可以不修改，但是对于2.0来说，这个接口在官方文档上存在，并且配置不存在的情况下不应该是404.
2.x的客户端使用的是grpc进行获取配置和服务的调用，NamingHttpClientProxy和HttpClientWorker应该都已经不被调用。 但是这个在2.0里面提供了，不能说提供了不让用。反过来说，我直接发http请求，404也不应该呀。我个人理解哈，有问题请指点指点

**Comment by KomachiSion** [comment]
2.0都用grpc请求来获取配置了， 实际上NamingHttpClientProxy和HttpClientWorker已经不被使用了。所以改不改意义不大。

可以看下grpc的对应获取配置请求是否还是类似的逻辑。
