### ISSUE TITLE
K8s 部署单节点 Nacos 2.4.1 CPU飙升

### ISSUE THREAD

**Issue by mianba** [alibaba/nacos#12629]
环境：
kubernetes
docker
nacos/nacos-server:2.4.1
启动参数：
JDK: 1.8-openjdk
客户端：
1.1.4  版本
    老项目-自己调整jar包,重写了NamingProxy
    数量 **160个应用**
2.4.1  版本
新项目-10几个项目
参数：-XX:SurvivorRatio=8 -Xms12g -Xmx12g -Xmn6g  只调整了 启动jvm 参数，其他通过官方提供的脚本启动，目前找不到飙升的原因

 -XX:+UseConcMarkSweepGC 
-XX:+UseCMSCompactAtFullCollection
 -XX:CMSInitiatingOccupancyFraction=70
 -XX:+CMSParallelRemarkEnabled 
-XX:SoftRefLRUPolicyMSPerMB=0 
-XX:+CMSClassUnloadingEnabled 
-Dnacos.standalone=true 
现象：
1. 容器CPU没有限制，最多占用100多个CPU
![image](https://github.com/user-attachments/assets/bd0a5699-2b47-4240-bd4b-74192a330a69)
![image](https://github.com/user-attachments/assets/43032124-a5ad-48e8-9861-fd5e093d68a5)

2. 访问 前端UI 有明细卡顿 接口访问5秒左右

**Comment by mianba** [comment]
拉取日志发现 core-auth.log 日志较大，1天6G
![image](https://github.com/user-attachments/assets/9144459c-ed9c-4287-b036-820383374027)
一直打印日志
/nacos/v1/ns/instance/list 等信息
![image](https://github.com/user-attachments/assets/34b2fba8-7cd2-4d77-898a-3e6da0758771)

**Comment by KomachiSion** [comment]
可以看一下login接口的调用量，是不是login接口有大量调用。

**Comment by mianba** [comment]
> 可以看一下login接口的调用量，是不是login接口有大量调用。

配置了下

**Comment by mianba** [comment]
另外 由于测试环境Nacos 负载较高 客户端2.4.2，本地访问超时，在idea 设置以下参数不起作用 -Dnacos.remote.client.grpc.timeout=60000 -Dnacos.remote.client.grpc.server.check.timeout=60000 -Dnacos.remote.client.grpc.health.timeout=60000

**Comment by XiaZhouxx** [comment]
> 另外 由于测试环境Nacos 负载较高 客户端2.4.2，本地访问超时，在idea 设置以下参数不起作用 -Dnacos.remote.client.grpc.timeout=60000 -Dnacos.remote.client.grpc.server.check.timeout=60000 -Dnacos.remote.client.grpc.health.timeout=60000

你的客户端版本太低了 1.1.4应该是不支持grpc的吧

**Comment by mianba** [comment]
看来这两篇，感觉跟这个很像

**Comment by KomachiSion** [comment]
1.1.4客户端版本太低了， 不支持轻量心跳且不支持查空降级，

看起来是这两个问题导致心跳接口操作过多且查询了很多空服务（1s查一次）

建议客户端升级到1.4.X试一下。

**Comment by mianba** [comment]
> 1.1.4客户端版本太低了， 不支持轻量心跳且不支持查空降级，
> 
> 看起来是这两个问题导致心跳接口操作过多且查询了很多空服务（1s查一次）
> 
> 建议客户端升级到1.4.X试一下。

谢谢老师的回答，我们试一下 升级到1.4.x ，另外老师 由于我们框架是基于springboot 1.5.x+springcoud cloud alibaba 0.1.2构建的，如果不能升级到1.4.x  我们应该如何解决这个问题，修改源码吗

**Comment by KomachiSion** [comment]
那可能只能基于1.1.4的客户端源码，修改部分这些接口调用频率后发布到内部仓库使用了。

客户端的api没有太大改动， 只要没有使用到nacos的inner api，应该不太会有升级问题。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.

**Comment by mianba** [comment]
问题解决了，调整了登录时用户名和密码机制，下次登录采用token，服务端启用了缓存，现在200台机器 三台负载 每台大约2.5C 左右

**Comment by saytesnake** [comment]
> 问题解决了，调整了登录时用户名和密码机制，下次登录采用token，服务端启用了缓存，现在200台机器 三台负载 每台大约2.5C 左右

我也是遇到类似这样的问题，想问一下，“调整了登录时用户名和密码机制，下次登录采用 token” 这个是如何做的呢？

**Comment by Dario-s-j** [comment]
Ok

Em sex., 3 de jan. de 2025, 12:04, Jacky Tang ***@***.***>
escreveu:
