### ISSUE TITLE
nacos.core.member.lookup.type=address-server 模式下，重启nacos集群时候如果 /nacos/serverlist 接口故障或者不稳定，可能导致nacos集群重启瘫痪

### ISSUE THREAD

**Issue by xzxiaoshan** [alibaba/nacos#12621]
明确配置 nacos.core.member.lookup.type=address-server 的前提下。

**当前程序现状** 

第一次启动时nacos正常从远程接口读取members，并同步存入本地 cluster.conf 缓存，然后程序启动了定时同步接口数据到 cluster.conf 的动作。如果接口调用失败，则nacos启动失败。

**讨论点** 

第一次启动nacos正常，一直正常工作。某日 address-server 接口服务挂了或者网络异常不能正常调用 /nacos/serverlist 接口，此时因为业务需要重启 nacos 集群。问：应该启动成功还是应该启动失败？

[当前程序现状] 当type=address-server时，现在代码是在nacos启动时强依赖这个接口。是否应该优化程序，当接口调用失败并且本地存在 cluster.conf 缓存时，正常加载 cluster.conf 成功启动。

**个人建议**

有优化的必要，nacos集群第一次部署启动时候，因为用户需求配置了`nacos.core.member.lookup.type=address-server`，按照强依赖启动时合理的，接口调用失败nacos无法启动，正常。

但是后期nacos一直正常运行时，因为需要要重启 nacos集群。此时再强依赖 address-server 接口，就可能很不合适了。

理由：
1、address-server 虽然为 nacos 提供 members，但是它本身不是 nacos 集群的一部分，nacos 集群能否正常运行或者重启，不应该强依赖这个接口。

2、整因为 address-server 不属于nacos的一部分，被疏于管理出现接口无法访问，也很有可能存在的。

3、运维人员在不知情 address-server 宕机的情况下，因为业务需要重启 nacos 服务，可能出现整个 nacos 集群无法再启动起来。进而导致业务系统崩掉。

**优化建议，如下图所示**

address-server 无法被正常访问时，如果本地存在 cluster.conf 缓存，则应启动成功。因为同时启动的定时同步程序仍然会持续和该接口保持联系，直到提供 members 的接口恢复后可以同步新的members 到cluster.conf 中。

> 大部分情况下，members 变动的概率是不高的。所以缓存的 cluster.conf 用于启动一般是符合业务系统正常运行需求的。

![f8470667cbf7b0c6385efe0132821ad5](https://github.com/user-attachments/assets/a4e67d4e-08d2-40f6-b7cb-cdc6c92034bd)

**Comment by chuntaojun** [comment]
i think it's good idea

**Comment by KomachiSion** [comment]
如果地址服务器异常， 启动的服务将无法找到对应的集群地址，此时应该及时停止，若此时的cluster。conf缓存是旧的或者错误的，能启动访问会造成数据错乱造成更大问题。

这时候应该设置改为File模式，手动更新clustr.conf文件。而不是用自动更新维护的clustr.conf。

**Comment by xzxiaoshan** [comment]
原来的代码，coluster.conf 就是自定定时更新的。

**Comment by xzxiaoshan** [comment]
nacos 正常运行时，如果出现了集群接口不可用，nacos 没有任何警示提示。
nacos 每隔几秒自动同步集群接口时，如果多次同步失败，是否应该在 nacos 的UI界面首页增加醒目的提示？

当前issue 提出的内容，是影响nacos启动的。

**Comment by KomachiSion** [comment]
没看懂你说的逻辑， 地址服务器如果运行过程中出现问题， 不会影响正在运行的server和client节点，这会使用缓存继续运行，只会影响变更和重启的节点。

影响启动就是符合预期的行为，上面的回复也说明了这么处理的原因，启动失败就是显示的提示你现在地址服务器有问题，临时修复可以切换成file模式使用conf文件启动。

地址服务器的监控告警不是应该单独监控吗？ 在nacos的UI提示中做感觉挺奇怪的， 毕竟Nacos又不是监控系统，一定要做的话，可以通过日志监控实现。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
