### ISSUE TITLE
nacos-grpc-client-executor bug

### ISSUE THREAD

**Issue by SkillKingwjl** [alibaba/nacos#12632]
![image](https://github.com/user-attachments/assets/b58b09f8-f33c-47d4-8ac3-7a4db97edc50)
nacos-grpc-client-executor Always creating

**Comment by SkillKingwjl** [comment]
![image](https://github.com/user-attachments/assets/6af330ed-63f2-4b25-a01b-b9f11640a864)

**Comment by SkillKingwjl** [comment]
version：2.4.0.1

**Comment by KomachiSion** [comment]
It's no problem. thread will auto create when tps high and destroy when tps is low.

just get the count whether less than `Runtime.getProcessor * 8`

**Comment by SkillKingwjl** [comment]
Get
