### ISSUE TITLE
2.4.1版本nacos数据目录复制到其他机器上，服务注册后服务列表显示空白

### ISSUE THREAD

**Issue by tm2018** [alibaba/nacos#12639]
操作步骤：
在A机器上安装nacos，启用鉴权配置，使用默认数据库;将整个nacos目录（包括data文件夹）打包，在B机器上启动；
启动应用，应用能注册到nacos(应用启动日志和端口完全正常)，但是nacos服务列表里面服务无显示。

PS:
交付类项目，需要用脚本安装nacos，并预置nacos数据，因此之前2.2.3、2.3.0、2.3.2版本都采用拷贝目录（包括data目录）的方式，安装nacos，之前版本此方式未出现上述问题。

**Comment by KomachiSion** [comment]
服务是持久化服务还是非持久化服务？

如果是持久化服务，需要保证新旧机器的cluster.conf文件一致，因为raft是严格协议，之前的leader信息和member信息都记录在数据内，如果新机器的ip变了， 导致和之前记录的member信息不一致，会选不出leader从而导致无法加载旧数据。

如果是非持久化服务， 那么整个集群迁移之后数据肯定不存在了，需要客户端重新连接重新发送心跳和注册。

**Comment by KomachiSion** [comment]
配置和命名空间数据是持久化在数据库中的， 只要数据库是同一个，且联通性可读性无问题即可。

**Comment by tm2018** [comment]
> 配置和命名空间数据是持久化在数据库中的， 只要数据库是同一个，且联通性可读性无问题即可。

首先，单机启动的nacos，且未添加clust.conf。
其次，在2.2.3 2.3.0 2.3.2版本，同样的操作都是正常的，唯独2.4.1版本出现此情况；昨天又验证了一次，该问题必现。

**Comment by libogithub2018** [comment]
我现在也出现该问题，nacos服务端升级从2.2.0升级到2.4.1后本地源码启动服务，启动正常，然后启动客户端，启动正常日志打印已经成功注册，但是在nacos的客户端网页上看不见已经注册的任何服务，但是服务端升级到2.4.2版本后客户端服务都能看见，显示。

**Comment by flyme6** [comment]
> 我现在也出现该问题，nacos服务端升级从2.2.0升级到2.4.1后本地源码启动服务，启动正常，然后启动客户端，启动正常日志打印已经成功注册，但是在nacos的客户端网页上看不见已经注册的任何服务，但是服务端升级到2.4.2版本后客户端服务都能看见，显示。

我也是

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.

**Comment by MrYangZC** [comment]
2.4.1问题太多了，升级到2.4.2 就行
