### ISSUE TITLE
nacos 额外数据源不支持配置 数据库驱动 导致加载报错

### ISSUE THREAD

**Issue by silent-night-no-trace** [alibaba/nacos#12634]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

修改源码使其支持 数据库驱动配置 

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
Fixed by #9439

**Comment by silent-night-no-trace** [comment]
这个并没有解决 没有引入driverClassName的 配置

**Comment by silent-night-no-trace** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
![image](https://github.com/user-attachments/assets/eae941bb-da64-4dc9-8fbf-9d02eb4532ae)

**Comment by KomachiSion** [comment]
spring的bind会读取set方法， 然后反射调用注入。

**Comment by silent-night-no-trace** [comment]
这个有点写死吧 相当与给每个 DB 都是一样的数据连接驱动

最好和连接db 连接信息 以及 用户密码 类似的级别配置 每个库级别的配置
多数据源下可能是不同的 库  对应的不同的 数据库连接驱动

**Comment by bes2008** [comment]
> 这个有点写死吧 相当与给每个 DB 都是一样的数据连接驱动
> 
> 最好和连接db 连接信息 以及 用户密码 类似的级别配置 每个库级别的配置 多数据源下可能是不同的 库 对应的不同的 数据库连接驱动

这样的使用场景合理吗？

**Comment by KomachiSion** [comment]
我觉得不合理吧，同一个nacos会拿异构数据库做主备吗？ 那样也不支持动态切换吧。

nacos的数据库插件也不支持动态切换，是启动的时候选择一个。

所以我觉得现有的机制完全满足了。没必要每个db用不同的driver吧

**Comment by silent-night-no-trace** [comment]
如果支持灵活配置会不会更好， 同时也保留的之前的配置

**Comment by silent-night-no-trace** [comment]
但是存在支持多数据源的场景吧，如果既支持了多数据源 但是不不支持灵活配置 是不是有点局限？

**Comment by xuechaos** [comment]
嗯  多个数据源的场景都需要重启进行配置，运行时置换的目前是不支持，也会引入一些变化，这块看可以先不考虑
不过nacos目前支持多个数据源本身，适配情况按版本来需要要考虑有个机制减少插件适配成本
