### ISSUE TITLE
Nacos server 端出现NPE

### ISSUE THREAD

**Issue by dankoCao** [alibaba/nacos#12635]
当前版本 2.1.0-BETA， 在我们生产环境，偶尔出现了NPE的错误，最近变的频繁起来，一天大概10来条，错误信息如下、

![image](https://github.com/user-attachments/assets/ab42f8dd-0b92-487c-8d70-a38e24a19beb)

业务侧报错信息如下：
```
2024-09-10 02:05:45.973 ERROR [com.alibaba.nacos.client.Worker:c.a.n.c.r.client] Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, retryTimes=0,errorMessage=null
```
我在issues列表中查找到了类似的问题：https://github.com/alibaba/nacos/issues/9733 ， 表象和我们的类似，但是我又看了他提交的修复，https://github.com/alibaba/nacos/pull/9798 ， 这个修复改的是StringPool中的第58行，我们上面的报错是在第52行，和我们的不一样，这个问题的根因是什么，是否有彻底修复

**Comment by XiaZhouxx** [comment]
你要看修复这个之后的发布版本是多少, 我看合并记录至少都是在2.2.1+

**Comment by dankoCao** [comment]
https://github.com/alibaba/nacos/issues/9733 这个问题是在2.2.1版本中修复的，但是我们这个错误感觉和之前的不一样，从错误信息来看是StringPool 第52行抛了NPE， 已修复的问题是在第58行加了null判断， 我现在有点迷惑，这感觉不是同一个问题

**Comment by XiaZhouxx** [comment]
看了一下52行确实也可能导致NPE, 我看2.3.0+ 更新修复了这里的实现
<img width="577" alt="image" src="https://github.com/user-attachments/assets/4d52d4f8-3bd4-4702-8a2f-bef74b375e81">

**Comment by XiaZhouxx** [comment]
> 看了一下52行确实也可能导致NPE, 我看2.3.0+ 更新修复了这里的实现 <img alt="image" width="577" src="https://private-user-images.githubusercontent.com/34960122/365980935-4d52d4f8-3bd4-4702-8a2f-bef74b375e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjEyMzcsIm5iZiI6MTcyNTk2MDkzNywicGF0aCI6Ii8zNDk2MDEyMi8zNjU5ODA5MzUtNGQ1MmQ0ZjgtM2JkNC00NzAyLThhMmYtYmVmNzRiMzc1ZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA5MzUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNGY5NGRmMDQ3YjdkZjhlMjVjMGJmYzU1MmNmOGMxYWI1MDZlM2UyYzYwNDNlZDU3MDYwZGQ0NjY1ZmVlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cYF1pI2MCvFFoBx7TzhTP7bIdGG3R49wBw_-LcB76_Q">

看了下这里的是2.1.1就修复了的

**Comment by dankoCao** [comment]
下了2.1.1版本，看着确实是修复了
![image](https://github.com/user-attachments/assets/d1140b34-c51e-4501-a940-5c176e8f0b19)

我还有点好奇，什么场景下会命中这个bug

**Comment by dankoCao** [comment]
看了2.1.1 发布版本报告，问题见：https://github.com/alibaba/nacos/issues/8153
