### ISSUE TITLE
缺陷修复pgsql不支持“·“”号

### ISSUE THREAD

**Issue by floor07** [alibaba/nacos#12631]
caused: PreparedStatementCallback; bad SQL grammar
 [SELECT id,quota,`usage`,`max_size`,max_aggr_count,max_aggr_size,tenant_id FROM tenant_capacity 
 WHERE tenant_id = ?]; nested exception is org.postgresql.util.PSQLException:
 错误: 操作符不存在: ` integer 建议：没有匹配指定名称和参数类型的操作符. 
 您也许需要增加明确的类型转换. 位置：17;caused: 错误: 操作符不存在: 
 ` integer 建议：没有匹配指定名称和参数类型的操作符. 您也许需要增加明确的类型转换. 
 位置：17;

**Comment by floor07** [comment]
@i will slove it

**Comment by fuhouyu** [comment]
这个昨天提交了PR #12628 。
如果去除`，由于`usage`为Mysql关键字，在数据源为Mysql的情况下，会有SQL问题。

**Comment by huangkemingyyds** [comment]
这个应该要对pgsql 插件中修复这个问题

**Comment by KomachiSion** [comment]
我查了一下， 应该是传给插件的字段名有问题

**Comment by KomachiSion** [comment]
duplicate with #12625
