### ISSUE TITLE
2.4.2 新建了命名空间  无法查看   重新建 又提示命名空间已经存在

### ISSUE THREAD

**Issue by silent-night-no-trace** [alibaba/nacos#12633]
**Describe the bug**

2.4.2 新建了命名空间  无法查看   重新建 又提示命名空间已经存在
![image](https://github.com/user-attachments/assets/2670cfa9-073f-4854-bfc6-9bf4e4fb4007)

**Expected behavior**
新建后正常显示 

**Actually behavior**
A clear and concise description of what you actually to happen.
新建无法显示 并且再次新建提示命名空间已经存在
**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
部署方式，和使用的数据库是？

**Comment by wangqd00** [comment]
同样的问题，server下载下来啥都不改按教程单机部署就会有这个问题

**Comment by KomachiSion** [comment]
duplicate with #12631
