### ISSUE TITLE
nacos服务端升级到2.4.1版本后，看不见注册的服务

### ISSUE THREAD

**Issue by libogithub2018** [alibaba/nacos#12648]
1.nacos服务端从2.2.0版本升级到2.4.1版本，使用本地nacos源码启动服务，服务启动正常，然后本地启动客户端，客户端启动正常，且日志打印显示已经成功注册，但是在nacos的客户端网页上看不见已经注册的任何服务，但是把服务端升级到2.4.2版本后客户端网页可以看见，显示注册的服务。

Translation:

1. The Nacos server was upgraded from version 2.2.0 to version 2.4.1. The service was started using the local Nacos source code, and it started normally. Then, the local client was started, which also started normally, and the logs indicated that it had successfully registered. However, no registered services were visible on the Nacos client web page. After upgrading the server to version 2.4.2, the client web page could see and display the registered services.

客户端：
![image](https://github.com/user-attachments/assets/5fcf786a-504d-4509-9657-3d4346b19e23)

![image](https://github.com/user-attachments/assets/e292c704-4077-4a4d-bfa6-5802d87e2c75)

![image](https://github.com/user-attachments/assets/2dc1b9a4-35ee-41e2-8c07-9e94cc9e18af)

服务端：

![image](https://github.com/user-attachments/assets/21251868-1196-44ff-95a4-70188455176f)

![image](https://github.com/user-attachments/assets/84fafce6-dcaf-4690-b680-54cb7fc8e38c)

![image](https://github.com/user-attachments/assets/479c78a8-9b34-43ff-b833-b7bee9594398)

**Comment by nkorange** [comment]
你看的界面是配置中心，注册中心点下面的service management：
<img width="908" alt="image" src="https://github.com/user-attachments/assets/96b8455c-752c-4613-b1b9-6d92b966ee88">

**Comment by libogithub2018** [comment]
我只是截取快了没注意，一样的
![image](https://github.com/user-attachments/assets/bef1c4bc-8959-4d3c-885a-26699e1b76b2)

**Comment by flyme6** [comment]
我试了下，
1.先停集群 nacos
2.把 data 目录下的文件清除掉。
3.启动集群 nacos
4.重新退出登录 nacos


总感觉是 页面缓存问题，后台服务可以正常调用。

**Comment by libogithub2018** [comment]
后台服务是可以互相调用，只是页面看不见而已，但是页面缓存都清空了还是一样，而且我是单节点部署的nacos服务

**Comment by flyme6** [comment]
> 后台服务是可以互相调用，只是页面看不见而已，但是页面缓存都清空了还是一样，而且我是单节点部署的nacos服务

你按照这个步骤试试
1.先停集群 nacos
2.把 data 目录下的文件清除掉。
3.启动集群 nacos
4.重新退出登录 nacos
5.重启你的应用包

**Comment by libogithub2018** [comment]
我直接升级2.4.2了，2.4.1搞烦了，晚点我试一试你说的这个步骤，但是我的nacos服务和客户端都是单节点的。

**Comment by flyme6** [comment]
> 我直接升级2.4.2了，2.4.1搞烦了，晚点我试一试你说的这个步骤，但是我的nacos服务和客户端都是单节点的。

好嘞

**Comment by KomachiSion** [comment]
大概率是命名空间配置问题， 配置的命名空间id不存在。

**Comment by flyme6** [comment]
> 大概率是命名空间配置问题， 配置的命名空间id不存在。

只更换了 jar 包，其他没动。

**Comment by libogithub2018** [comment]
> 很大概率是命名空间配置问题，配置的命名空间id不存在。

数据库有该命名空间，并且上面图中页面也有显示111的命名空间，我直接使用默认的pulic也是一样。
![image](https://github.com/user-attachments/assets/ee7d0f49-7475-4d5c-939c-dcc52efbeb67)

**Comment by KomachiSion** [comment]
可以查看server的 naming-server.log日志，查看你这个服务究竟注册到哪个命名空间下了。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.

**Comment by Halfmoonly** [comment]
> 我只是截取快了没注意，一样的 ![image](https://github.com/user-attachments/assets/bef1c4bc-8959-4d3c-885a-26699e1b76b2)

朋友你好，我也遇到了同样的问题。  我的解决办法是本地的bootstrap.yaml中配置命名空间id，而不是命名空间名称。  可能是2.4.1的bug吧
