### ISSUE TITLE
数据库表字段调整建议（`usage`,`max_size`）

### ISSUE THREAD

**Issue by darkpara** [alibaba/nacos#12649]
2.4.2版本升级。在做达梦数据库兼容适配时发现，出现了数据库报错
功能：权限控制-权限管理
![image](https://github.com/user-attachments/assets/c4d44046-79f4-4f51-9fc4-74e873e51f25)
报错原因经确认为sql执行报错，达梦数据库无法识别符号 `
sql： SELECT id,quota, `usage`,`max_size` ,max_aggr_count,max_aggr_size,tenant_id FROM tenant_capacity WHERE tenant_id = ''

建议：考虑到后续对多种数据库的适配性，是否能将usage 调整为 usage_  ,max_size 调整为 max_size_ ，避免关键字冲突的前提下，适配更多的数据库。

**Comment by bes2008** [comment]
调整字段的可能性不大，可使用 插件  https://github.com/bes2008/nacos-plugins 解决
