### ISSUE TITLE
be start error

### ISSUE THREAD

**Issue by lisihan0607** [alibaba/nacos#12646]
start time: Fri Sep 13 15:44:43 CST 2024
INFO: java_cmd /usr/java/jdk1.8.0_311-amd64/bin/java
INFO: jdk_version 8
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/app/doris-2.0.2/be/lib/java_extensions/preload-extensions/preload-extensions-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/doris-2.0.2/be/lib/java_extensions/java-udf/java-udf-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/doris-2.0.2/be/lib/hadoop_hdfs/common/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
*** Query id: 0-0 ***
*** tablet id: 136074 ***
*** Aborted at 1726213487 (unix time) try "date -d @1726213487" if you are using GNU date ***
*** Current BE git commitID: b387ac2 ***
*** SIGILL illegal operand (@0x5637ccdc4a50) received by PID 655533 (TID 656169 OR 0x7fbd53fcf700) from PID 18446744072851573328; stack trace: ***
 0# doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*) at /root/src/doris-2.0/be/src/common/signal_handler.h:417
 1# os::Linux::chained_handler(int, siginfo*, void*) in /usr/java/jdk1.8.0_311-amd64/jre/lib/amd64/server/libjvm.so
 2# JVM_handle_linux_signal in /usr/java/jdk1.8.0_311-amd64/jre/lib/amd64/server/libjvm.so
 3# signalHandler(int, siginfo*, void*) in /usr/java/jdk1.8.0_311-amd64/jre/lib/amd64/server/libjvm.so
 4# 0x00007FBED0C5B690 in /lib64/libc.so.6
 5# bitdienc32 at /root/src/doris-2.0/be/src/clucene/src/ext/for/bitutil.c:384
 6# p4nd1enc32 at /root/src/doris-2.0/be/src/clucene/src/ext/for/vp4c.c:414
 7# lucene::index::SDocumentsWriter<char>::appendPostings(lucene::util::ArrayBase<lucene::index::SDocumentsWriter<char>::ThreadState::FieldData*>*, lucene::index::STermInfosWriter<char>*, lucene::store::IndexOutput*, lucene::store::IndexOutput*) in /app/doris-2.0.2/be/lib/doris_be
 8# lucene::index::SDocumentsWriter<char>::writeSegment(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) in /app/doris-2.0.2/be/lib/doris_be
 9# lucene::index::SDocumentsWriter<char>::flush(bool) in /app/doris-2.0.2/be/lib/doris_be
10# lucene::index::IndexWriter::doFlush(bool) in /app/doris-2.0.2/be/lib/doris_be
11# lucene::index::IndexWriter::flush(bool, bool) in /app/doris-2.0.2/be/lib/doris_be
12# lucene::index::IndexWriter::closeInternal(bool) in /app/doris-2.0.2/be/lib/doris_be
13# lucene::index::IndexWriter::close(bool) in /app/doris-2.0.2/be/lib/doris_be
14# doris::segment_v2::InvertedIndexColumnWriterImpl<(doris::FieldType)26>::close() at /root/src/doris-2.0/be/src/olap/rowset/segment_v2/inverted_index_writer.cpp:111
15# doris::segment_v2::InvertedIndexColumnWriterImpl<(doris::FieldType)26>::finish() at /root/src/doris-2.0/be/src/olap/rowset/segment_v2/inverted_index_writer.cpp:501
16# doris::segment_v2::ScalarColumnWriter::write_inverted_index() in /app/doris-2.0.2/be/lib/doris_be
17# doris::segment_v2::SegmentWriter::finalize_columns_index(unsigned long*) at /root/src/doris-2.0/be/src/olap/rowset/segment_v2/segment_writer.cpp:879
18# doris::VerticalBetaRowsetWriter::_flush_columns(std::unique_ptr<doris::segment_v2::SegmentWriter, std::default_delete<doris::segment_v2::SegmentWriter> >*, bool) at /root/src/doris-2.0/be/src/olap/rowset/vertical_beta_rowset_writer.cpp:141
19# doris::VerticalBetaRowsetWriter::flush_columns(bool) at /root/src/doris-2.0/be/src/olap/rowset/vertical_beta_rowset_writer.cpp:166
20# doris::Merger::vertical_compact_one_group(std::shared_ptr<doris::Tablet>, doris::ReaderType, std::shared_ptr<doris::TabletSchema>, bool, std::vector<unsigned int, std::allocator<unsigned int> > const&, doris::vectorized::RowSourcesBuffer*, std::vector<std::shared_ptr<doris::RowsetReader>, std::allocator<std::shared_ptr<doris::RowsetReader> > > const&, doris::RowsetWriter*, long, doris::Merger::Statistics*) at /root/src/doris-2.0/be/src/olap/merger.cpp:270
21# doris::Merger::vertical_merge_rowsets(std::shared_ptr<doris::Tablet>, doris::ReaderType, std::shared_ptr<doris::TabletSchema>, std::vector<std::shared_ptr<doris::RowsetReader>, std::allocator<std::shared_ptr<doris::RowsetReader> > > const&, doris::RowsetWriter*, long, doris::Merger::Statistics*) at /root/src/doris-2.0/be/src/olap/merger.cpp:351
22# doris::Compaction::do_compaction_impl(long) at /root/src/doris-2.0/be/src/olap/compaction.cpp:351
23# doris::Compaction::do_compaction(long) at /root/src/doris-2.0/be/src/olap/compaction.cpp:124
24# doris::CumulativeCompaction::execute_compact_impl() at /root/src/doris-2.0/be/src/olap/cumulative_compaction.cpp:87
25# doris::Compaction::execute_compact() at /root/src/doris-2.0/be/src/olap/compaction.cpp:106
26# doris::Tablet::execute_compaction(doris::CompactionType) at /root/src/doris-2.0/be/src/olap/tablet.cpp:1859
27# std::_Function_handler<void (), doris::StorageEngine::_submit_compaction_task(std::shared_ptr<doris::Tablet>, doris::CompactionType, bool)::$_0>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:291
28# doris::ThreadPool::dispatch_thread() in /app/doris-2.0.2/be/lib/doris_be
29# doris::Thread::supervise_thread(void*) at /root/src/doris-2.0/be/src/util/thread.cpp:470
30# 0x00007FBED0A65F1B in /lib64/libpthread.so.0
31# __clone in /lib64/libc.so.6

**Comment by KomachiSion** [comment]
not nacos‘ problem
