### ISSUE TITLE
Naming local cache may be ignored in a rare scenario

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#12644]
**Describe the bug**

Naming local cache may be ignored in a rare scenario. So even when local cache is not empty, user's invocation would still get exception.

**Expected behavior**

If local cache is not empty, Nacos client should never throw exception.

**Actually behavior**

In a rare case, when local cache is not empty, user's invocation would get exception.

**How to Reproduce**

It's hard to reproduce but it did happen in our production environment. Here is the related logic:

in the method at [getServiceInfoBySubscribe](https://github.com/alibaba/nacos/blob/3a9003bc7cbb642ef836975bde65e596e87eb697/client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java#L336):
1. first it tried to get service info from local cache;
2. then it will check if local cache is null or client is not subscribed:
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/f9e7c0df-befb-4242-bc6b-ad782206948b">
3. if yes, it will try to subscribe from remote Nacos server.

Usually it will work, because whenever `clientProxy.isSubscribed(...)` returns false, it means the [Nacos client](https://github.com/alibaba/nacos/blob/3a9003bc7cbb642ef836975bde65e596e87eb697/common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java#L516) has just reconnected to Nacos server and closed the old connection:
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/7bc897ee-cf14-4dc4-b9bc-2049ba2d00d2">

As new connection is ready, so the subscribe request would succeed.

But if the new connection is down immediately again so the subscribe request failed, then in the method `getServiceInfoBySubscribe`, an exception will be thrown.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version: nacos-server 2.1.2, nacos-client 2.1.2
 - Module: naming
 - SDK: spring-cloud-alibaba-nacos 2021.1

**Additional context**

I suggest to add a protection logic in the method `getServiceInfoBySubscribe`, so that whenever the local cache is not empty, the remote request error or any other exception will be ignored.

**Comment by KomachiSion** [comment]
When client call subscribe api to do sub, it should throw exception when connection not ready and subscribe failed, which notify users there is some exception for connection and should retry or do other operation.

If call `getAllInstances` with `subscribe=true`, It can be discuss whether it should throw exception when cache exist.

In my option, when `subscribe=true`, connection not ready should throw exception to notify, because users think `getAllInstances` is get instances from service, not only cache.

**Comment by nkorange** [comment]
In current implementation, `subscribe=true` and Nacos server disconnected would not throw exception. Only when `subscribe=true` and reconnect succeed and re-subscribe failed would cause exception.

**Comment by KomachiSion** [comment]
> In current implementation, `subscribe=true` and Nacos server disconnected would not throw exception. Only when `subscribe=true` and reconnect succeed and re-subscribe failed would the client throw exception.

Why `subscribe=true` and Nacos server disconnected would not throw exception？ I think it also throw exception.

**Comment by nkorange** [comment]
I have tested it.

1. Start local Nacos server.
2. Register service test.1 locally.
3. Run a consumer with the following code:
```java
public static void main(String[] args) throws Exception {
        NamingService namingService = NamingFactory.createNamingService("127.0.0.1:8848");
        while (true) {
            System.out.println(namingService.getAllInstances("test.1", true));
            Thread.sleep(5000L);
        }
    }
```
4. shutdown Nacos server.

The consumer code can still return the instance list of test.1

**Comment by nkorange** [comment]
I suggest to change the method `getServiceInfoBySusbcribe` to the following logic:
```java
private ServiceInfo getServiceInfoBySubscribe(String serviceName, String groupName, String clusterString,
            boolean subscribe) throws NacosException {
        ServiceInfo serviceInfo;
        if (subscribe || !EnvUtil.isDirectQueryEnabled()) {
            serviceInfo = serviceInfoHolder.getServiceInfo(serviceName, groupName, clusterString);
            if (null == serviceInfo || !clientProxy.isSubscribed(serviceName, groupName, clusterString)) {
                try {
                    serviceInfo = clientProxy.subscribe(serviceName, groupName, clusterString);
                } catch (NacosException ne) {
                    NAMING_LOGGER.warn("getServiceInfoBySubscribe subscribe failed, {}", serviceName);
                    // 只有订阅失败，且本地缓存也为空的情况下，才抛异常：
                    if (serviceInfo == null) {
                        throw ne;
                    }
                }
            }
        } else {
            serviceInfo = clientProxy.queryInstancesOfService(serviceName, groupName, clusterString, 0, false);
        }
        return serviceInfo;
    }
```

**Comment by KomachiSion** [comment]
I see,  it might be when first time call `clientProxy.subscribe`, `clientProxy.isSubscribed` will return true so that loop call will not entry condition.

And when first call while starting, it must be return `false` and entry condition to call  `clientProxy.subscribe` and throw exception by connection loss.

I think your changes is ok. just do some enhance for Method complexity, such as extract to a new method to cover the logic.

**Comment by BDL-LTD** [comment]
> **Describe the bug**
> 
> Naming local cache may be ignored in a rare scenario. So even when local cache is not empty, user's invocation would still get exception.
> 
> **Expected behavior**
> 
> If local cache is not empty, Nacos client should never throw exception.
> 
> **Actually behavior**
> 
> In a rare case, when local cache is not empty, user's invocation would get exception.
> 
> **How to Reproduce**
> 
> It's hard to reproduce but it did happen in our production environment. Here is the related logic:
> 
> in the method at [Blakeling@yahoo.com](https://github.com/alibaba/nacos/blob/3a9003bc7cbb642ef836975bde65e596e87eb697/client/src/main/java/com/alibaba/nacos/client/naming/NacosNamingService.java#L336):
> 
> 1. first it tried to get service info from local cache;
> 2. then it will check if local cache is null or client is not subscribed:
> 
> <img alt="image" width="1049" src="https://private-user-images.githubusercontent.com/4593375/367137087-f9e7c0df-befb-4242-bc6b-ad782206948b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzM1NDksIm5iZiI6MTczMDQzMzI0OSwicGF0aCI6Ii80NTkzMzc1LzM2NzEzNzA4Ny1mOWU3YzBkZi1iZWZiLTQyNDItYmM2Yi1hZDc4MjIwNjk0OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMDM1NDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjY4MjdjYzc2ZWZlZmU3MTViOWQ4MGI3MDUwNjExYzA1NTJjOGI3Y2UzNWU2MDA5ZjMwNTI1NmUzN2ViYzc5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uWNgeACwVUtYNT26LEtJxx9MA9F9FE2s9E5j0Uppjpw"> 3. if yes, it will try to subscribe from remote Nacos server.
> Usually it will work, because whenever `clientProxy.isSubscribed(...)` returns false, it means the [Nacos client](https://github.com/alibaba/nacos/blob/3a9003bc7cbb642ef836975bde65e596e87eb697/common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java#L516) has just reconnected to Nacos server and closed the old connection: <img alt="image" width="1104" src="https://private-user-images.githubusercontent.com/4593375/367137907-7bc897ee-cf14-4dc4-b9bc-2049ba2d00d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzM1NDksIm5iZiI6MTczMDQzMzI0OSwicGF0aCI6Ii80NTkzMzc1LzM2NzEzNzkwNy03YmM4OTdlZS1jZjE0LTRkYzQtYjliYy0yMDQ5YmEyZDAwZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMDM1NDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhhMDlkOTJmZDg3NmQzZmQ2NmMwNmQ4Yzk1NmFhMjhiMDU3ZjY1NTdkMDg3ZWE5MmI5NzU3ZTExYzE0YjRmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.g-Wx2lgHzZyfOWCwxk1cXzvcj-dzOyLXzroRVIAeehA">
> 
> As new connection is ready, so the subscribe request would succeed.
> 
> But if the new connection is down immediately again so the subscribe request failed, then in the method `getServiceInfoBySubscribe`, an exception will be thrown.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [MR BLAKE DAMIAN LING]
> * Version: nacos-server 2.1.2, nacos-client 2.1.2
> * Module: naming
> * SDK: spring-cloud-alibaba-nacos 2021.1
> 
> **Additional context**
> 
> I suggest to add a protection logic in the method `getServiceInfoBySubscribe`, so that whenever the local cache is not empty, the remote request error or any other exception will be ignored.
