### ISSUE TITLE
钉钉群二维码过期

### ISSUE THREAD

**Issue by lingfengchencn** [alibaba/nacos#12651]
群二维码已经过期。。

另外，python v2的版本有计划么？我写了一天，发现现在open api的不能保持。使用长链接么？
求指导。

<img width="592" alt="image" src="https://github.com/user-attachments/assets/c3e45981-577e-4647-9a5b-377ca61fd088">

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-group.github.io/pull/810
