### ISSUE TITLE
使用达梦数据源插件，内部还是存在SQL不兼容问题。

### ISSUE THREAD

**Issue by taohanlin** [alibaba/nacos#12656]
开发需求：自定义达梦数据插件，将jar包放在nacos的plugins中。
遇到问题：启动nacos，查询命名空间报错，nacos内部服务中，还存在不支持扩展达梦的语句存在。

<img width="713" alt="image" src="https://github.com/user-attachments/assets/fae4b467-8fb7-4d9e-a86d-c9263eed4460">

<img width="459" alt="image" src="https://github.com/user-attachments/assets/8d38daa6-f913-438b-aeca-979ad5ee3fc9">

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/dc880d0f-d797-4c84-bcbb-f489fc20e542">

**Comment by bes2008** [comment]
着急的话，可以有如下 几种方案：

1. 退回到`<=2.4.1`，但`2.4.1` 之前 有漏洞
2. 自己改插件，重新编译构建
3. 使用第三方插件：https://github.com/bes2008/nacos-plugins 版本

**Comment by KomachiSion** [comment]
duplicate with #12625

**Comment by taohanlin** [comment]
<img width="925" alt="image" src="https://github.com/user-attachments/assets/4d8eef93-0155-49ee-91d3-9fe1bfd3dbe9">

     //插件TenantCapacityMapperByDaMeng类中，重写select，替换特殊符号解决；

       @Override
	public String select(List<String> columns, List<String> where) {
		// 达梦数据库，移除反引号
		List<String> newColumns = columns.stream()
				.map(column -> column.replace("`", ""))
				.collect(Collectors.toList());
		return super.select(newColumns, where);
	}
