### ISSUE TITLE
Nacos 1.1.0 local integration spring boot 2.0 read yaml configuration will appear to read less than configuration, can only be changed to properties file

### ISSUE THREAD

**Issue by zushilong003** [alibaba/nacos#1265]
nacos 1.1.0本地 整合spring boot 2.0 读取yaml配置 会出现读取的不到配置，只能改成properties文件

	@NacosValue(value = "${hbase.zookeeper.quorum}", autoRefreshed = true)
	private String quorum;

  
hbase:
  zookeeper:
    quorum: 10.xxx.1x.43
    port: 2181

**Comment by nkorange** [comment]
yml格式目前不支持，请参考[nacos-spring#33](https://github.com/nacos-group/nacos-spring-project/issues/33)
