### ISSUE TITLE
[Issue] The Open API of namespaces list can't be access

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/nacos#12665]
**Describe the bug**
The SQL error on accessing the Open API of namespaces list(`/v2/console/namespace/list`).

**Expected behavior**
The expected response content:
```json
{
  "code": 0,
  "message": "success",
  "data": [
          {
                  "namespace": "",
                  "namespaceShowName": "public",
                  "namespaceDesc": null,
                  "quota": 200,
                  "configCount": 1,
                  "type": 0
          }
  ]
}
```

**Actually behavior**
The actual response content : 
```json
{
  "code": 10002,
  "message": "data access error",
  "data": "PreparedStatementCallback; bad SQL grammar [SELECT id,quota,`usage`,`max_size`,max_aggr_count,max_aggr_size,tenant_id FROM tenant_capacity WHERE tenant_id = ?]; nested exception is java.sql.SQLSyntaxErrorException: Lexical error at line 1, column 17.  Encountered: \"`\" (96), after : \"\"."
}
```

**How to Reproduce**
1. Start Nacos Server on the Docker environment
2. Access the Open API `/v2/console/namespace/list`
3. Get the unexpected result

**Desktop (please complete the following information):**
 - OS: Windows and Linux 
 - Version: Nacos Server Docker Image [2.4.2](https://hub.docker.com/layers/nacos/nacos-server/v2.4.2/images/sha256-988f3a61cb444bc84647164c47978cfd8e28c0e2a626fc230e81fd3b48571d55?context=explore)
 - Module: Open API - Namespaces list

**Comment by Bo-Qiu** [comment]
FYI
https://github.com/alibaba/nacos/issues/12625
