### ISSUE TITLE
spring boot Nacos can not registerInstance

### ISSUE THREAD

**Issue by zushilong003** [alibaba/nacos#1266]
@SpringBootApplication
@NacosPropertySource(groupId = "DEFAULT_GROUP", dataId = "spring-boot-mybatis", autoRefreshed = true)
@MapperScan("com.winter.mapper")
public class SpringbootMybatisDemoApplication {

	@NacosInjected
	private NamingService namingService;

	@Value("${server.port}")
	private int serverPort;

	@Value("${spring.application.name}")
	private String applicationName;

	@PostConstruct
	public void registerInstance() throws NacosException {
		namingService.registerInstance(applicationName, "127.0.0.1", serverPort);
	}

	public static void main(String[] args) {
		SpringApplication.run(SpringbootMybatisDemoApplication.class, args);
		System.out.println("********Spring boot loading finished********");
	}
}

Caused by: java.lang.UnsupportedOperationException: Only support to inject types[[interface com.alibaba.nacos.api.config.ConfigService]] instance , however actual injected type [interface com.alibaba.nacos.api.naming.NamingService] in member[private com.alibaba.nacos.api.naming.NamingService com.winter.SpringbootMybatisDemoApplication.namingService]

**Comment by chuntaojun** [comment]
if you want to use NamingService，you shoud set `nacos.discovery.server-addr` or use @EnableNacosDiscovery

**Comment by zushilong003** [comment]
spring boot project no spring cloud   can not set nacos.discovery.server-addr

**Comment by chuntaojun** [comment]
you can see here [nacos-discovery-configuration-metadata](https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-discovery-spring-boot-autoconfigure/src/main/resources/META-INF/spring-configuration-metadata.json)

or If you don't mind, you can add my nails to communicate. My nail number: dvxx6ro

**Comment by chuntaojun** [comment]
> spring boot project no spring cloud can not set nacos.discovery.server-addr

you can see here [nacos-discovery-configuration-metadata](https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-discovery-spring-boot-autoconfigure/src/main/resources/META-INF/spring-configuration-metadata.json)

or If you don't mind, you can add my nails to communicate. My nail number: dvxx6ro
