### ISSUE TITLE
Nacos TIME_WAITING线程占用cpu高的问题

### ISSUE THREAD

**Issue by ZhangDeLei** [alibaba/nacos#12663]
nacos版本：2.0.1

nacos在使用率不高的情况下，各个TIME_WAITING线程cpu占用高，请问这个是怎么回事？
【线程CPU利用率】
![cpu](https://github.com/user-attachments/assets/cac801be-f4a4-4f1a-8981-8baddde72b10)

**Comment by Bo-Qiu** [comment]
生成火焰图看看

**Comment by Bo-Qiu** [comment]
同时 2.0.1 版本比较老，存在一些未修复的缺陷，建议升级至较新版本

**Comment by ZhangDeLei** [comment]
> 同时 2.0.1 版本比较老，存在一些未修复的缺陷，建议升级至较新版本

问题找到了，部分应用密码配置错了，导致一直重试密码导致cpu升高。
