### ISSUE TITLE
执行mvn test失败

### ISSUE THREAD

**Issue by dabao1990** [alibaba/nacos#12672]
[root@localhost ~]#cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"

spack install --overwrite --keep-stage --no-checksum -y nacos@2.4.2  maven@3.6.3
cd nacos@2.4.2
mvn test

[INFO] Running com.alibaba.nacos.client.naming.cache.DiskCacheTest
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
/home/stage/root/spack-stage-nacos-2.4.2-brwm3lgh57qmwhhiqu5myl3qrsi3nwta/spack-src/client/target/test-classes/cache/
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.025 s <<< FAILURE! -- in com.alibaba.nacos.client.naming.cache.DiskCacheTest
[ERROR] com.alibaba.nacos.client.naming.cache.DiskCacheTest.testReadCacheForAllSituation -- Time elapsed: 0.010 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <0>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
at com.alibaba.nacos.client.naming.cache.DiskCacheTest.testReadCacheForAllSituation(DiskCacheTest.java:93)
at java.lang.reflect.Method.invoke(Method.java:498)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.ArrayList.forEach(ArrayList.java:1257)
[INFO] Running com.alibaba.nacos.client.env.NacosClientPropertiesTest
[INFO] Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s -- in com.alibaba.nacos.client.env.NacosClientPropertiesTest
[INFO] Running com.alibaba.nacos.client.env.SearchablePropertiesTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s -- in com.alibaba.nacos.client.env.SearchablePropertiesTest
[INFO] Running com.alibaba.nacos.client.env.convert.CompositeConverterTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s -- in com.alibaba.nacos.client.env.convert.CompositeConverterTest
[INFO] Running com.alibaba.nacos.client.env.SystemEnvPropertySourceTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s -- in com.alibaba.nacos.client.env.SystemEnvPropertySourceTest
[INFO] Running com.alibaba.nacos.client.logging.NacosLoggingTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.373 s -- in com.alibaba.nacos.client.logging.NacosLoggingTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DiskFailoverDataSourceTest.testGetSwitchForFailoverEnabled:62 expected: <1> but was: <0>
[ERROR]   DiskCacheTest.testReadCacheForAllSituation:93 expected: <2> but was: <0>
[INFO]
[ERROR] Tests run: 685, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Alibaba NACOS 2.4.2 2.4.2:
[INFO]
[INFO] Alibaba NACOS 2.4.2 ................................ SUCCESS [  1.576 s]
[INFO] nacos-api 2.4.2 .................................... SUCCESS [  9.125 s]
[INFO] nacos-common 2.4.2 ................................. SUCCESS [01:07 min]
[INFO] nacos-consistency 2.4.2 ............................ SUCCESS [  4.536 s]
[INFO] nacos-plugin 2.4.2 ................................. SUCCESS [  0.087 s]
[INFO] nacos-datasource-plugin 2.4.2 ...................... SUCCESS [  2.077 s]
[INFO] nacos-custom-environment-plugin 2.4.2 .............. SUCCESS [  1.420 s]
[INFO] nacos-sys 2.4.2 .................................... SUCCESS [  5.638 s]
[INFO] nacos-persistence 2.4.2 ............................ SUCCESS [  7.686 s]
[INFO] nacos-auth-plugin 2.4.2 ............................ SUCCESS [  3.792 s]
[INFO] nacos-auth 2.4.2 ................................... SUCCESS [  5.678 s]
[INFO] nacos-trace-plugin 2.4.2 ........................... SUCCESS [  1.379 s]
[INFO] nacos-control-plugin 2.4.2 ......................... SUCCESS [  6.429 s]
[INFO] nacos-core 2.4.2 ................................... SUCCESS [ 52.009 s]
[INFO] nacos-encryption-plugin 2.4.2 ...................... SUCCESS [  1.691 s]
[INFO] nacos-config-plugin 2.4.2 .......................... SUCCESS [  1.461 s]
[INFO] nacos-config 2.4.2 ................................. SUCCESS [01:04 min]
[INFO] nacos-cmdb 2.4.2 ................................... SUCCESS [  0.119 s]
[INFO] nacos-naming 2.4.2 ................................. SUCCESS [01:29 min]
[INFO] nacos-address 2.4.2 ................................ SUCCESS [  6.245 s]
[INFO] nacos-logger-adapter-impl 2.4.2 .................... SUCCESS [  0.078 s]
[INFO] nacos-logback-adapter-12 2.4.2 ..................... SUCCESS [  4.447 s]
[INFO] nacos-log4j2-adapter 2.4.2 ......................... SUCCESS [  4.674 s]
[INFO] nacos-client 2.4.2 ................................. FAILURE [01:38 min]
[INFO] nacos-plugin-default-impl 2.4.2 .................... SKIPPED
[INFO] nacos-default-auth-plugin 2.4.2 .................... SKIPPED
[INFO] nacos-default-control-plugin 2.4.2 ................. SKIPPED
[INFO] nacos-default-plugin-all ........................... SKIPPED
[INFO] nacos-istio 2.4.2 .................................. SKIPPED
[INFO] nacos-prometheus 2.4.2 ............................. SKIPPED
[INFO] nacos-console 2.4.2 ................................ SKIPPED
[INFO] nacos-test 2.4.2 ................................... SKIPPED
[INFO] nacos-config-test 2.4.2 ............................ SKIPPED
[INFO] nacos-naming-test 2.4.2 ............................ SKIPPED
[INFO] nacos-core-test 2.4.2 .............................. SKIPPED
[INFO] nacos-example 2.4.2 ................................ SKIPPED
[INFO] nacos-distribution 2.4.2 ........................... SKIPPED

**Comment by KomachiSion** [comment]
It can't be reproduce in github ci and my local env. 

Have you change some codes in your local env?

**Comment by dabao1990** [comment]
> It can't be reproduce in github ci and my local env.
> 
> Have you change some codes in your local env?



> It can't be reproduce in github ci and my local env.
> 
> Have you change some codes in your local env?
应该是我在测试时导入了source ../spack-build-env.txt，影响了mvn test；我去掉之后，测试通过
