### ISSUE TITLE
关于客户端1.3.2+服务端版本1.4.7 读取文件乱码问题

### ISSUE THREAD

**Issue by DimonHo** [alibaba/nacos#12675]
nacos服务端有个配置文件，配置文件中有类似这种 `# 中文注释`
当服务端1.4.6时，用客户端1.2.1或1.3.2都能正常读取配置文件
服务端升级到1.4.7后，用客户端1.2.1能正常读取配置，但1.3.2读取配置却是乱码。为什么？

**Comment by KomachiSion** [comment]
1.3.2有bug，可以升级新版本的客户端后尝试

**Comment by DimonHo** [comment]
> 1.3.2有bug，可以升级新版本的客户端后尝试

那为什么1.3.2搭配1.4.6的服务端又不会出现乱码呢？服务端升级到1.4.7之后，才会出现这个乱码问题，所以我不确定到底是客户端问题还是服务端问题。

**Comment by KomachiSion** [comment]
1.4.5之后的服务端都没有修改过逻辑， 只修复安全问题， 所以应该是客户端的问题， 1.3.0～1.3.2版本有已知的获取配置乱码问题，问题会出现在slb/nginx开启gzip支持时。

**Comment by KomachiSion** [comment]
而且如果是服务端问题， 1.2.1也获取会乱码

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.
