### ISSUE TITLE
After configuring the log4j2 configuration file for business applications, start the alarm report log

### ISSUE THREAD

**Issue by xiebin123456** [alibaba/nacos#12682]
![image](https://github.com/user-attachments/assets/3b653a4c-9e0b-4ca4-a18f-ed8d71ebd370)

        <Logger name="com.alibaba.nacos.shaded.io.grpc" level="${nacosClientProperty:com.alibaba.nacos.config.log.level:-info}"
            additivity="false">
            <appender-ref ref="ASYNC-REMOTE"/>
        </Logger>

It should be modified to

        <Logger name="com.alibaba.nacos.shaded.io.grpc" level="${nacosClientProperty:com.alibaba.nacos.config.log.level:-info}"
            additivity="false">
            <appender-ref ref="ASYNC_REMOTE"/>
        </Logger>

**Comment by KomachiSion** [comment]
welcome to PR

**Comment by xiebin123456** [comment]
@xiebin123456  will solve it
