### ISSUE TITLE
nacos  grafana dashboard is too old

### ISSUE THREAD

**Issue by bwangll** [alibaba/nacos#12683]
nacos grafana dashboard is too old, and grafana is now updated to 12. I hope to update nacos 'indicator kanban and support grafana12.
希望更新 nacos 的 grafana 看板。上次更新时间为2020-10-22T05:51:59，目前已经和新版 grafana 不兼容了

**Comment by KomachiSion** [comment]
welcome to contribution.

**Comment by shengbinxu** [comment]
@i will solve it@

**Comment by bwangll** [comment]
版本说错了，首先，第一点，新版本的ui用react写的，这个是靠grafana自动转的，第二点，自带的告警已经失效了，需要更改。很多告警指标和nacos2的内容不匹配。需要优化一下

**Comment by shengbinxu** [comment]
> 第一点，新版本的ui用react写的，这个是靠grafana自动转

这个具体影响什么？问题是什么？

第二点，我来看下

**Comment by bwangll** [comment]
偶尔会导致cpu那几个看板变为数字

**Comment by shengbinxu** [comment]
https://github.com/nacos-group/nacos-template/pull/15

你可以使用nacos-grafana-upper-2.4.json 这个配置。

新的配置看起来没有报警相关的看板，我不了解报警这块的原始需求，所以目前只能这样了

**Comment by shengbinxu** [comment]
> [nacos-group/nacos-template#15](https://github.com/nacos-group/nacos-template/pull/15)
> 
> 你可以使用nacos-grafana-upper-2.4.json 这个配置。
> 
> 新的配置看起来没有报警相关的看板，我不了解报警这块的原始需求，所以目前只能这样了

该配置适用于nacos2.4之后的版本

**Comment by bwangll** [comment]
谢谢了
