### ISSUE TITLE
2.4.2.1 使用jdk8 nacos成功启动，但访问页面报这个错：nacos 访问页面 caused: Handler dispatch failed;nested exception is java.lang.NoSuchMethodError:  java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;; caused: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;

### ISSUE THREAD

**Issue by yinchuanqi** [alibaba/nacos#12680]
nacos版本2.4.2.1
jdk版本1.8.0_391

nacos 访问页面 caused: Handler dispatch failed;nested exception is java.lang.NoSuchMethodError:  java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;; caused: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;

**Comment by pengzonli** [comment]
caused: Handler dispatch failed;nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;caused: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;;

me too.

**Comment by riggzh** [comment]
docker version same

**Comment by Vain-vayne** [comment]
Nacos version: 2.4.2.1

JDK version: openjdk version "1.8.0_422"  
Console refresh error:  
2024-09-24 09:01:32,374 ERROR CONSOLE /nacos/v1/console/server/guide
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

JDK version: openjdk version "11.0.24" 2024-07-16
Refresh Normal

**Comment by Vain-vayne** [comment]
下载 Nacos 2.4.2.1 源码后, 用jdk 1.8 编译一遍就没问题了, 应该是安装包编译的问题

**Comment by strengthen7** [comment]
遇到同样的问题，是不是官网发布的包不是用1.8编译的？

**Comment by mrpc2030** [comment]
![image](https://github.com/user-attachments/assets/c53c6f72-fa39-49e0-b57d-630a1fb61cb8)

**Comment by muscidaes** [comment]
![Uploading Snipaste_2024-09-25_10-45-53.png…]()

**Comment by KomachiSion** [comment]
应该是发版的时候jdk版本改了，需要替换发布一下。

**Comment by KomachiSion** [comment]
已更新，请重新下载发布包或docker镜像。
