### ISSUE TITLE
2.0.3版本访问报错403

### ISSUE THREAD

**Issue by Coder-Cole** [alibaba/nacos#12681]
我当前使用的是2.0.3版本nacos，运行了一段时间后，修改了nacos.core.auth.default.token.secret.key和nacos.core.auth.server.identity.key、nacos.core.auth.server.identity.value的默认值，启动服务后再此访问页面或者调用接口显示403，请问是还需要修改哪里的配置才能更新这些值吗

**Comment by tm2018** [comment]
nacos.core.auth.enabled=true

**Comment by KomachiSion** [comment]
需要重新login一下， 因为修改了secret.key， 之前的token就已经失效了。

**Comment by Dz6666** [comment]
需要确认是否开启鉴权 : NACOS_AUTH_ENABLE 开启后重新创建token，以及nacos 还支持设置token 的ttl   NACOS_AUTH_TOKEN_EXPIRE_SECONDS

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
