### ISSUE TITLE
LifecycleProcessor not initialized

### ISSUE THREAD

**Issue by hhfdna** [alibaba/nacos#1269]
my project is based on springframework4.2.1,when i add nacos-spring-context in pom.xml,
it introduced spring-context3.2.8,which is conflict with spring-context4.2.1,when i exlcude 3.2.8, Error occured durering startup:

java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.spingframework.context.support.ClasspathXmlApplicationContext....
...

does nacos-spring-context not support spring 4 framework!

if any reply, i will be very appreciate!

**Comment by hhfdna** [comment]
problem solved. i fixed it by modifying nacos-spring-context-0.2.3-RC1. The class com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher does not compatible with spring 4.X, due to the following method:
@Override
    public void publishEvent(ApplicationEvent event) {

        if (context.isRunning()) {
            context.publishEvent(event);
        } else {
            deferredEvents.add(event);
        }

    }
nacos invokes this method during ApplicationContext initialization. in spring3.X ,when context initialization is not finished, calling lifecycle method( eg. isRunning) on context will not throw an IllegalStateException, spring3 will just return false, the else clause will be executed instead, context initialization won't be break.
while in spring4, calling lifecycle method before context is initialized will throw an java.lang.IllegalStateException: LifecycleProcessor not initialized, the startup process will be interrupted.
The revision is simply easy: adding try-catch clause, that's all. But it toke me three whole day to find it!!

**Comment by nkorange** [comment]
Thanks for your report and solution.
