### ISSUE TITLE
Instances that do not go offline and stop in time within the heartbeat detection period 

### ISSUE THREAD

**Issue by xiaolianghu** [alibaba/nacos#12707]
心跳检测周期内，未及时下线停止的实例

Nacos currently supports temporary instances to maintain activity by heartbeat reporting. The default interval for sending a heartbeat is 5 seconds. Nacos server will set the instance as unhealthy after 15 seconds without receiving a heartbeat, and remove the temporary instance after 30 seconds without receiving a heartbeat.
If the current instance has been stopped but is within the heartbeat detection cycle, nacos returns the stopped instance, causing an error.Is there any way to avoid it?

Nacos 目前支持临时实例使用心跳上报方式维持活性，发送心跳的周期默认是 5 秒，Nacos 服务端会在 15 秒没收到心跳后将实例设置为不健康，在 30 秒没收到心跳时将这个临时实例摘除。
如果当前实例已经停止，但是刚好处于心跳检测周期内，那么nacos会返回这个已停止的实例，导致错误。有什么办法可以避免吗？

**Comment by shengbinxu** [comment]
这个问题，主要涉及到`jvm shutdown hook`、`spring 优雅停机`等相关知识。
我写了个demo（参考项目中readme），来演示“如何在基于nacos做服务发现的微服务项目中实现优雅停止”

https://github.com/shengbinxu/GracefulShutdown

**Comment by KomachiSion** [comment]
客户端升级到2.0以上版本， 正常停止时会通过连接断开时间快速移除实例，只有意外停止（如宕机等）才会保留这个心跳30s移除的情况。能够解决大部分正常情况下的临时实例摘除慢的问题。

当然不升级客户端版本也是可以的即使移除的，spring cloud alibaba， dubbo等框架都会在shutdownhook中主动注销注册的实例。

如果是自己进行的注册，按照@shengbinxu的demo进行操作应该可行。

**Comment by King1031** [comment]
基于以上建议，我们升级客户端版本到2.4.2，并调整客户端心跳间隔和超时时间分别为100ms和1000ms。但是在并发测试中发现还是会有实例无法访问的错误。始终会有一点时间间隔内获取到的实例检测是健康的但实际是访问不到的。跟踪源码发现NacosNamingService.selectOneHealthyInstance在调用Balancer.getHostByRandomWeight时通过host.isHealthy()筛选客户端，返回了true，这里的Instance对象是不是有缓存导致更新不及时？在不添加feign等实现负载均衡情况下，有什么处理方案可以实现getHostByRandomWeight始终能返回健康的实例吗？
![image](https://github.com/user-attachments/assets/c4b657c5-6164-4f8f-8f6e-a024070a0219)

**Comment by shengbinxu** [comment]
尝试理解下你的问题：
A请求B，B1下线了（升级了B的客户端之后，B1实例停止后，注册中心目前能立即剔除B实例）
但是A还是请求到了下线的B1

如果是这样的话：
1、A一定是有缓存的。大概是30s左右从nacos server更新一次实例列表
2、解决方法：如我的demo中所述：
<img width="922" alt="image" src="https://github.com/user-attachments/assets/5954d655-c7fd-47c0-bea3-d2f57fdd47cd">

**Comment by KomachiSion** [comment]
> 基于以上建议，我们升级客户端版本到2.4.2，并调整客户端心跳间隔和超时时间分别为100ms和1000ms。但是在并发测试中发现还是会有实例无法访问的错误。始终会有一点时间间隔内获取到的实例检测是健康的但实际是访问不到的。跟踪源码发现NacosNamingService.selectOneHealthyInstance在调用Balancer.getHostByRandomWeight时通过host.isHealthy()筛选客户端，返回了true，这里的Instance对象是不是有缓存导致更新不及时？在不添加feign等实现负载均衡情况下，有什么处理方案可以实现getHostByRandomWeight始终能返回健康的实例吗？ ![image](https://private-user-images.githubusercontent.com/32608606/375614962-c4b657c5-6164-4f8f-8f6e-a024070a0219.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTY0NTUsIm5iZiI6MTcyODcxNjE1NSwicGF0aCI6Ii8zMjYwODYwNi8zNzU2MTQ5NjItYzRiNjU3YzUtNjE2NC00ZjhmLThmNmUtYTAyNDA3MGEwMjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA2NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTJhNDU0N2JhM2RmYWQ1MTRkNjU5NmEyODNjMzk5OTZiMjA2NGNmMzU5MTQ4M2U2MGNlYTc1MjMyMzJlMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ND1_Jx41h69PQ9v8Hpqe_SJo_RKw1EeFGu96ICllKpY)

feign 和loadbalance 有自己的缓存，在30s～1min不等，csdn上有人分析过，因为feign 和loadbalance 的逻辑就是定时get列表，然后更新自己的缓存， 不是使用订阅的方式，虽然nacos及时推送的数据，更新了nacos-client自身的缓存，但是feign 和loadbalance 没有listener来监听，而是按照周期查询，这就容易导致这个问题。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
