### ISSUE TITLE
服务下线的时候报错,我使用的是nacos 2.4.0   模式cluster

### ISSUE THREAD

**Issue by baibin20** [alibaba/nacos#12700]
![image](https://github.com/user-attachments/assets/d6bb8139-67cf-450c-9e1e-f895cb013244)

**Comment by baibin20** [comment]
求助求助

**Comment by KomachiSion** [comment]
集群部署存在问题， 请查看cluster.conf文件是否正确。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by baibin20** [comment]
> 集群部署存在问题， 请查看cluster.conf文件是否正确。

![image](https://github.com/user-attachments/assets/c667129d-c207-48a1-891e-2db980d3f647)
这是我当前的配置
