### ISSUE TITLE
Findbugs checked for some bugs

### ISSUE THREAD

**Issue by ylh23y** [alibaba/nacos#1270]
![Uploading image.png…]()

**Comment by ylh23y** [comment]
![09](https://user-images.githubusercontent.com/13464610/58369153-25701580-7f29-11e9-8316-786afc0f341b.png)

**Comment by nkorange** [comment]
Which find-bugs plugin are you using and can you upload the detailed errors? We actually already analyze Nacos code using a find-bugs plugin and no error reported.

**Comment by ylh23y** [comment]
![搜狗截图20190612140130](https://user-images.githubusercontent.com/13464610/59326914-a0537180-8d1a-11e9-9ba0-fc8445acb808.png)
FindBugs-IDEA  版本v1.0.1

**Comment by ylh23y** [comment]
![0612143535](https://user-images.githubusercontent.com/13464610/59328617-62a51780-8d1f-11e9-882e-21864281ebf3.png)

**Comment by ylh23y** [comment]
最新的代码扫描的也有好多bug

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
