### ISSUE TITLE
服务注册上了，但是访问失败20004，”no matched ip found“？

### ISSUE THREAD

**Issue by soundmemories** [alibaba/nacos#12706]
使用python写了脚本，在服务器上注册了一个pygwalker服务，从nacos/8848管理页面的管理列表中也能查看到注册的服务，如下图：
![image](https://github.com/user-attachments/assets/466dd972-0acc-44d8-866e-a9742d5ed691)
![image](https://github.com/user-attachments/assets/e05b237d-165d-4f9d-8c9c-275c6e1281d3)
但是本地通过nacos访问实例信息，始终报错，如下图所示：
![image](https://github.com/user-attachments/assets/ec8aff91-f9ea-444e-bcf8-4d5a24d6df32)
注册的pygwalker服务，我尝试使用docker部署，ip为172.18.0.22，还是报20004，"no matched ip found!"，这个问题可能出在哪里呢？有没有办法解决一下呢？
先感谢各位大佬解答了！

**Comment by shengbinxu** [comment]
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/e2a6347f-44ce-4b7a-9d6b-fca5baa7087b">
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/508776aa-0eba-45eb-a5a5-28e4c408336c">

我本地试了下，我觉得原因在于你注册实例时设置了`spring.cloud.nacos.discovery.cluster-name`，但是查询时没有加clusterName参数

**Comment by soundmemories** [comment]
> <img alt="image" width="1413" src="https://private-user-images.githubusercontent.com/3232275/372130799-e2a6347f-44ce-4b7a-9d6b-fca5baa7087b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzMyODMsIm5iZiI6MTcyODQzMjk4MywicGF0aCI6Ii8zMjMyMjc1LzM3MjEzMDc5OS1lMmE2MzQ3Zi00NGNlLTRiN2EtOWQ2Yi1mY2E1YmFhNzA4N2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDAxNjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZiZDljNDk1OWEyNDU0MWRjNzBiMmYyNmI1MzlmMjJjYWY4NGY5YjNiYTc3MWRlZjBlODJiYWZhYmFhZWM4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xdabEfmjFwDyNmBIUAVFQ4dnJGixzFd5BkJv7Ik4DXU"> <img alt="image" width="1419" src="https://private-user-images.githubusercontent.com/3232275/372130899-508776aa-0eba-45eb-a5a5-28e4c408336c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzMyODMsIm5iZiI6MTcyODQzMjk4MywicGF0aCI6Ii8zMjMyMjc1LzM3MjEzMDg5OS01MDg3NzZhYS0wZWJhLTQ1ZWItYTVhNS0yOGU0YzQwODMzNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDAxNjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQyZDZlZDljMTQwNjBkMDIzMDdlNjc1ZTM1OTgwZjQ2YmU1MzVlMjRlYmZhZmEyNzc0OTU5NTJhMTNlNmY0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.W68FCPvqp6D9XMuwD3hxsoQgDOUQs6CFLvHkSXfYd08">
> 我本地试了下，我觉得原因在于你注册实例时设置了`spring.cloud.nacos.discovery.cluster-name`，但是查询时没有加clusterName参数

先谢谢您的回答，我刚才试了下，还是会出问题，如下图所示：
![image](https://github.com/user-attachments/assets/91518d57-60cd-4eb1-ae2d-673618065d2a)
但是其他服务是java写的是可以访问的，如下如所示：
![image](https://github.com/user-attachments/assets/6eaf15e2-4c18-49b3-add4-22afb9092815)
其他能访问的服务，即使不加clusterName也是能访问的：
![image](https://github.com/user-attachments/assets/58ea4edb-f0e0-4d90-9e55-e98c2f987c58)

**Comment by shengbinxu** [comment]
了解了。
<img width="1463" alt="image" src="https://github.com/user-attachments/assets/36ab81a2-cf09-4d13-84c5-4fbd9c424041">
看nacos源码，这里对比的是ClusterName、ip、port
当api中这三个参数，和注册中心注册的值一致的时候，才会返回。
对于你的问题，我想不到其他可能性了

**Comment by soundmemories** [comment]
好的，谢谢您的回答，我再研究看看，如有需要再来向您请教，感谢！

**Comment by soundmemories** [comment]
> 了解了。 <img alt="image" width="1463" src="https://private-user-images.githubusercontent.com/3232275/374761285-36ab81a2-cf09-4d13-84c5-4fbd9c424041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzQ4MTMsIm5iZiI6MTcyODQzNDUxMywicGF0aCI6Ii8zMjMyMjc1LzM3NDc2MTI4NS0zNmFiODFhMi1jZjA5LTRkMTMtODRjNS00ZmJkOWM0MjQwNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDA0MTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhiYzcwNmNlZWRmMDdhNDRiYzhhNmI3ZGE1ZjI1NTE4NWNiODI0YmE5MGE5ZDZmNDU2NjMzYTVkY2JlNmQwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.c8D9H2_I1ls4yq169YHCyRBxZ6PUwqWgZslL-I07HBY"> 看nacos源码，这里对比的是ClusterName、ip、port 当api中这三个参数，和注册中心注册的值一致的时候，才会返回。 对于你的问题，我想不到其他可能性了

好的，谢谢您的回答，我再研究看看，如有需要再来向您请教，感谢！

**Comment by XiaZhouxx** [comment]
应该就是上面老哥说的clusterName的问题, 看下你python的脚本指定一下这个配置为DEFAULT就行了吧
<img width="224" alt="image" src="https://github.com/user-attachments/assets/ba7c8d4f-1f76-402a-ab09-56bc5e0fb3dc">

**Comment by soundmemories** [comment]
> 应该就是上面老哥说的clusterName的问题, 看下你python的脚本指定一下这个配置为DEFAULT就行了吧 <img alt="image" width="224" src="https://private-user-images.githubusercontent.com/34960122/374764684-ba7c8d4f-1f76-402a-ab09-56bc5e0fb3dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzY1MjIsIm5iZiI6MTcyODQzNjIyMiwicGF0aCI6Ii8zNDk2MDEyMi8zNzQ3NjQ2ODQtYmE3YzhkNGYtMWY3Ni00MDJhLWFiMDktNTZiYzVlMGZiM2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAxMTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDBmNTY4NDg4YmFmZThmMmNjNWVkZjBkZGI3ZjJiYTg4NmMxNWFkMjZmZjFhMGMwZGRlODI3YWQwZjViZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rl9gf-n9hEpfsGpv-W_EpIEAzlAt8H3nutQZJgMVtmM">

试了下，真是这个问题：
![image](https://github.com/user-attachments/assets/3314df85-4bc9-4954-bba7-f25a475c42ef)
需要在注册服务时候加上cluster_name="DEFAULT"才行，不然真访问不到服务，谢谢您了！

**Comment by soundmemories** [comment]
> 了解了。 <img alt="image" width="1463" src="https://private-user-images.githubusercontent.com/3232275/374761285-36ab81a2-cf09-4d13-84c5-4fbd9c424041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzY1MjIsIm5iZiI6MTcyODQzNjIyMiwicGF0aCI6Ii8zMjMyMjc1LzM3NDc2MTI4NS0zNmFiODFhMi1jZjA5LTRkMTMtODRjNS00ZmJkOWM0MjQwNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDExMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmIzODAyMDYzODNlMDRhNTI1YzY0OWQyNDYzYjM1ODlkZGU4MDVhZGUzYTUxODk5NzI4YjRkMTA4OTRmMzYzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rukoOnj0yj3wtGSaSAYuZ_wfSzfHFqMPR-ansWnYg_A"> 看nacos源码，这里对比的是ClusterName、ip、port 当api中这三个参数，和注册中心注册的值一致的时候，才会返回。 对于你的问题，我想不到其他可能性了

您好，确实是cluster_name的问题，在python注册服务时必须加上这个参数，不然真访问不到服务！
![image](https://github.com/user-attachments/assets/b1a8d02c-0f1f-4d91-9722-44e0cdf49d84)
![image](https://github.com/user-attachments/assets/65cad180-d7b4-46bf-b0fa-682f9ed8ff15)
