### ISSUE TITLE
Nacos cannot log off normally

### ISSUE THREAD

**Issue by zcl8515991** [alibaba/nacos#12718]
我是使用k8s部署的nacos集群，集群使用正常，但是使用nacos下线服务的时候报错 {"timestamp":"2024-10-11T10:48:20.186+08:00","status":400,"error":"Bad Request","message":"receive invalid redirect request from peer 10.233.76.97","path":"/nacos/v1/ns/instance"} 每次报错请求的ip地址也不用 ，这个问题应该怎么解决

I deployed a Nacos cluster using k8s, and the cluster was functioning normally. However, when I tried to log off the service using Nacos, an error occurred {"timestamp": "2024-10-11T10:48:20.186+08:00", "status": 400, "error": "Bad Request", "message": "receive invalid redirect request from peer 10.233.76.97", "path": "/nacos/v1/ns/instance"}. The IP address of each error request is not required. How can I solve this problem

**Comment by KomachiSion** [comment]
部署的集群有问题，cluster.conf文件肯定不一致。

**Comment by zcl8515991** [comment]
不是这个问题 我是用k8s部署的 三个pod是共用的配置文件 不存在不一致

**Comment by zcl8515991** [comment]
不是这个问题 我是用k8s部署的 三个pod共用的cluster.conf文件

**Comment by KomachiSion** [comment]
receive invalid redirect request 

这个报错只能是集群之间的节点不统一， 原因是需要转发到leader进行处理写请求， 但是发起转发的节点所计算的责任leader和接受转发的节点所计算的责任leader不一致。

目前发现的原因只有各个节点的member列表不一致， 可以通过运维api，看一下是不是member不一致。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
