### ISSUE TITLE
version nacosv2.3.1  and env NACOS_AUTH_CACHE_ENABLE: 'true' can not enable

### ISSUE THREAD

**Issue by only21tender** [alibaba/nacos#12714]
I use nacos version v 2.3.1 , and default 
NACOS_AUTH_SYSTEM_TYPE  :nacos
NACOS_AUTH_ENABLE :false  
while I login nacos, it will be login auth and without no insert user and pass.

deploy it in k8s
when I set core auth in configmap

data:
 MYSQL_SERVICE_DB_NAME: user 
 MYSQL_SERVICE_DB_PARAM: >-characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
 MYSQL_SERVICE_HOST: mysql-url
 MYSQL_SERVICE_PASSWORD: pass
 MYSQL_SERVICE_PORT: '3306'
 MYSQL_SERVICE_USER: databases
 **NACOS_AUTH_CACHE_ENABLE: 'true'  -- notation here**
 SPRING_DATASOURCE_PLATFORM: mysql

and restart statefulset nacos ,then cat config in pod
[root@nacos231-0 nacos]# cat conf/application.properties |grep -i auth
###The auth system to use, currently only 'nacos' and 'ldap' is supported:
nacos.core.auth.system.type=${NACOS_AUTH_SYSTEM_TYPE:nacos}
###worked when nacos.core.auth.system.type=nacos
nacos.core.auth.plugin.nacos.token.expire.seconds=${NACOS_AUTH_TOKEN_EXPIRE_SECONDS:18000}
nacos.core.auth.plugin.nacos.token.secret.key=${NACOS_AUTH_TOKEN:}
###Turn on/off caching of auth information. By turning on this switch, the update of auth information would have a 15 seconds delay.
**nacos.core.auth.caching.enabled=${NACOS_AUTH_CACHE_ENABLE:false}  -- notation here**
nacos.core.auth.enable.userAgentAuthWhite=${NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE:false}
nacos.core.auth.server.identity.key=${NACOS_AUTH_IDENTITY_KEY:}
nacos.core.auth.server.identity.value=${NACOS_AUTH_IDENTITY_VALUE:}
nacos.security.ignore.urls=${NACOS_SECURITY_IGNORE_URLS:/,/error,/

the environment of NACOS_AUTH_CACHE_ENABLE which I set in configmap , it does't effect.

please help me

**Comment by KomachiSion** [comment]
It will be replaced directly, it depend spring boot read the configuration from env and properties file.

Why do you think this config is not enabled?
