### ISSUE TITLE
Nacos内存持续增长

### ISSUE THREAD

**Issue by nextvirus** [alibaba/nacos#12715]
Nacos 内存持续增长，通过监控可以看到堆栈内存的使用率并不高，但是内存一直在上涨，每次涨幅很小，都是几M，排查到最后感觉唯一的异常是有很多等待的线程，但是通过 https://help.aliyun.com/zh/mse/support/what-do-i-do-if-the-number-of-nacos-threads-is-excessively-large 此文档的排查方法排查过，线程是正常的。能不能提供一个继续向下排查的思路。

 - OS: CentOS7
 - Version： nacos-servre 2.0.4 nacos-client 2.0.4

**Comment by KomachiSion** [comment]
对内存能否GC掉？ 能GC掉就没有问题。

**Comment by nextvirus** [comment]
堆内存可以GC，但是整体的内存在慢慢上涨，每天大概涨几十M，这个内存有什么方法具体向下排查吗？

**Comment by cpftest** [comment]
建议排查是否是网络连接不释放

**Comment by nextvirus** [comment]
确实有网络连接不释放这个情况，这个情况能不能提供下相关的处理文档

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
