### ISSUE TITLE
2.3.0 tomcat版本漏洞

### ISSUE THREAD

**Issue by tangfan123** [alibaba/nacos#12717]
2.3.0 tomcat版本漏洞，手动解压jar包，替换9.0.90 tomcat-core ，启动报错，Unable to start embedded Tomcat

**Comment by KomachiSion** [comment]
升级最新版本尝试呢， 我记得2.4.2版本升级过tomcat-core

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems new version has solved this problem.
