### ISSUE TITLE
在nacos控制台操作dubbo注册的服务上下线后, 重启元数据没有更新

### ISSUE THREAD

**Issue by eye-gu** [alibaba/nacos#12713]
dubbo使用nacos注册中心, 第一次启动注册成功, 然后在控制台对服务操作了下线然后上线, 再重启dubbo, 重启后服务的元数据没有更新.

nacos: 2.3.2 standalone
nacos-client: 2.3.2
dubbo: 3.2.11

**Comment by eye-gu** [comment]
我发现原因了, 控制台上修改服务后, `NamingMetadataManager`会保存起来, 所以后续拿到的一直是老的. 我目前找到的方法是缩小`nacos.naming.clean.expired-metadata.expired-time`配置, 然后重启的时候, 停一段时间, 使元数据过期再启动. 还有其他方法么?

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/manual/user/open-api/#33-%E6%9B%B4%E6%96%B0%E5%AE%9E%E4%BE%8B

openAPI中有说明，通过控制台和openAPI直接修改的元数据（包含上下线状态）会记忆且在实例注销后保留一段时间，放置因网络等其他原因导致抖动时元数据丢失。

**Comment by bwangll** [comment]
> https://nacos.io/docs/latest/manual/user/open-api/#33-%E6%9B%B4%E6%96%B0%E5%AE%9E%E4%BE%8B
> 
> openAPI中有说明，通过控制台和openAPI直接修改的元数据（包含上下线状态）会记忆且在实例注销后保留一段时间，放置因网络等其他原因导致抖动时元数据丢失。

最近也在想这个问题，感觉需要把实例的元数据和nacos对实例维护的元数据做一个重构，拆分开。控制台的上线下操作是一个优雅的更新动作。但是实例元数据可能包含业务逻辑，需要使用更新后的内容。不能单纯使用历史数据来解决问题。希望可以考虑这个点。后续做一个优化。

**Comment by eye-gu** [comment]
我觉得最好页面上能反映出来, 当前元数据来自于client还是缓存中的, 方便排查
