### ISSUE TITLE
阿里巴巴开发规范不是不建议使用Executors创建线程池，为什么nacos还是在使用，不用担心OOM吗？

### ISSUE THREAD

**Issue by yuxuefeifei** [alibaba/nacos#12725]
public static final class Managed {
        
        private static final String DEFAULT_NAMESPACE = "nacos";
        
        private static final ThreadPoolManager THREAD_POOL_MANAGER = ThreadPoolManager.getInstance();
        
        /**
         * Create a new single executor service with default thread factory and register to manager.
         *
         * @param group group name
         * @return new single executor service
         */
        public static ExecutorService newSingleExecutorService(final String group) {
            ExecutorService executorService = Executors.newFixedThreadPool(1);
            THREAD_POOL_MANAGER.register(DEFAULT_NAMESPACE, group, executorService);
            return executorService;
        }
        
        /**
         * Create a new single executor service with input thread factory and register to manager.
         *
         * @param group         group name
         * @param threadFactory thread factory
         * @return new single executor service
         */
        public static ExecutorService newSingleExecutorService(final String group, final ThreadFactory threadFactory) {
            ExecutorService executorService = Executors.newFixedThreadPool(1, threadFactory);
            THREAD_POOL_MANAGER.register(DEFAULT_NAMESPACE, group, executorService);
            return executorService;
        }

**Comment by KomachiSion** [comment]
规范中不建议使用Executors是因为使用者不一定知晓线程池使用时的量级，不停放入task导致内存不足。

实际使用时，根据场景评估不太会出现不停引入task，或场景需要task不可丢弃时， 应该创建长队列的场景，与其自行创建无限队列线程池（Integer.MAX) ，不如直接创建Executors来的简单优雅。

规划的主要目的是让人引起此处的重视，都一步思考和评估，而不是完全禁止使用。

**Comment by JunJieLiu51520** [comment]
线程池创建时，不指定线程名称就是耍流氓，排查问题时不能快速定位到代码

**Comment by KomachiSion** [comment]
ThreadFactory 有设置线程名。
