### ISSUE TITLE
k8s 元数据同步nacos 失败

### ISSUE THREAD

**Issue by swq499809608** [alibaba/nacos#12726]
k8s 及 nacos 版本：
 k8s : v1.25.5  nacos:2.3.2
 
nocos 配置：
 cat application.properties |grep sync
    nacos.naming.distro.syncRetryDelay=5000
    nacos.k8s.sync.enabled=true
nacos env:
  [root@nacos-0 conf]# env|grep sync.en
  nacos.k8s.sync.enabled=true

java 服务启动k8s.sync 配置：

[root@nacos-0 conf]# cat ../bin/docker-startup.sh |grep sync
  JAVA_OPT="${JAVA_OPT} -Dnacos.k8s.sync.enabled=true"

实际效果：
[root@nacos-0 conf]# ps -ef |grep sync
root           1       0 16 21:26 ?        00:01:26 /usr/lib/jvm/java-1.8.0-openjdk/bin/java -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSParallelRemarkEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+CMSClassUnloadingEnabled -XX:SurvivorRatio=8 -server -Xms24g -Xmx24g -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.core.auth.enabled=true -Dnacos.k8s.sync.enabled=true -Dnacos.preferHostnameOverIp=true -Dnacos.member.list= -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/home/nacos/plugins,/home/nacos/plugins/health,/home/nacos/plugins/cmdb,/home/nacos/plugins/selector -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar --spring.config.additional-location=file:/home/nacos/conf/ --spring.config.name=application --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

结论： 无生效!

**Comment by 985492783** [comment]
没有日志吗

**Comment by KomachiSion** [comment]
该功能在2.X版本中并不支持，计划在3.X版本中支持
