### ISSUE TITLE
nacos 2.4.0版本，在更改statefulset的replicas数之后，原有pod的cluster.conf不会更新

### ISSUE THREAD

**Issue by Umbrallerstackcode** [alibaba/nacos#12739]
yaml配置文件的变量引用了configmap的变量
![image](https://github.com/user-attachments/assets/e0388047-dc5b-41d5-a211-37f54c9f149f)
但是在扩容之后，nacos集群由3个节点，变成4个节点
![image](https://github.com/user-attachments/assets/d28e537e-21ba-4a4d-8626-ae52327e24ff)

然后查看各个节点的cluster.conf配置，发现只有新增节点的配置文件中有所有节点的DNS
![image](https://github.com/user-attachments/assets/ac652429-2d57-47fa-a62b-2fadf58887e1)

随后把新增节点的DNS加入到configmap中，执行apply之后，还是只有新增节点有最全配置
configmap中的配置如下：
![image](https://github.com/user-attachments/assets/4d3e8908-1430-4140-921c-d3976a6e8278)

各个节点的cluster.conf
![image](https://github.com/user-attachments/assets/454e58cf-07b1-4ab0-88a4-8b4e1f0d557a)

**Comment by KomachiSion** [comment]
该文件需要您自行进行变更，可以通过operator、configmap等手段进行变更， 可以到nacos-k8s repo 社区尝试获取支持。

**Comment by Umbrallerstackcode** [comment]
好的，谢谢

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems configuration problem
