### ISSUE TITLE
Fail to discover registered service

### ISSUE THREAD

**Issue by chineseboytom** [alibaba/nacos#1274]
1. Service registration(Ok):
curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
2. Service discovery(Failed):
curl -X GET 'http://127.0.0.1:8848/nacos/v1/ns/instances?serviceName=nacos.naming.serviceName'
It return nothing

**Comment by nkorange** [comment]
Use 
```
curl -X GET 'http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=nacos.naming.serviceName'
```
please.
