### ISSUE TITLE
nacos extension-configs多环境配置不生效

### ISSUE THREAD

**Issue by tutut5512** [alibaba/nacos#12754]
1.版本
spring-cloud-starter-alibaba-nacos-config: 2021.0.6.1
nacos服务端版本:2.2.3
application.yml配置:

appid: com.wesports.ws
## log
logging:
  level:
    org.springframework.web: trace
    com.wesports: trace
    com.alibaba.nacos: debug
    org.springframework.cloud: debug
## server
server:
  port: 9300
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
    accept-count: 0
    keep-alive-timeout: 300
    threads:
      max: 2000
      min-spare: 20
  servlet:
    context-path: /ws/sports
    encoding:
      charset: UTF-8
      enabled: true
      force: true
## spring
spring:
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: wesports-ws
    env: local
    switch:
      config:
        basic: true
        cache: true
        httpClient: true
        redis: true
        redisson: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix: /
      suffix: .html
  redis:
    cluster:
      nodes:
        - localhost:7001
        - localhost:7002
        - localhost:7003
        - localhost:7004
        - localhost:7005
        - localhost:7006
      max-redirects: 2
    lettuce:
      pool:
        max-idle: 10
        max-wait: 500
        max-active: 8
        min-idle: 0
    password: qwe123!@#
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: xxx:8848
        group: ${spring.profiles.active}
      config:
        server-addr: xxx:8848
        extension-configs:
            - data-id: ws-app-test.yaml
              group: DEFAULT_GROUP
              refresh: true
## rocketmq
rocketmq:
  #  consumer:
  #    group: boxing_pay_out_group
  #    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
  #    pull-batch-size: 10
  name-server: 43.198.184.127:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: test_group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
## fastjson
fastjson:
  parser:
    safeMode: true
## knife4j
knife4j:
  enable: true
  production: false
  openapi:
    title: 接口文档
    description: ""
    version: v1.0.0

代码中使用:
@Slf4j
@Data
@Component
public class NacosYamlConfig {
    @Value("${app}")
    private String app;

}

启动报错,获取不到 app配置

**Comment by tutut5512** [comment]
上面的格式发生了变化,我重新编辑
# 版本描述
spring-cloud-starter-alibaba-nacos-config: 2021.0.6.1
nacos服务端版本:2.2.3
# 配置文件
appid: com.wesports.ws
logging:
  level:
    org.springframework.web: trace
    com.wesports: trace
    com.alibaba.nacos: debug
    org.springframework.cloud: debug
server:
  port: 9300
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
    accept-count: 0
    keep-alive-timeout: 300
    threads:
      max: 2000
      min-spare: 20
  servlet:
    context-path: /ws/sports
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: wesports-ws
    env: local
    switch:
      config:
        basic: true
        cache: true
        httpClient: true
        redis: true
        redisson: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix: /
      suffix: .html
  redis:
    cluster:
      nodes:
        - localhost:7001
        - localhost:7002
        - localhost:7003
        - localhost:7004
        - localhost:7005
        - localhost:7006
      max-redirects: 2
    lettuce:
      pool:
        max-idle: 10
        max-wait: 500
        max-active: 8
        min-idle: 0
    password: qwe123!@#
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: xxx:8848
        group: ${spring.profiles.active}
      config:
        server-addr: xxx:8848
        extension-configs:
            - data-id: ws-app-test.yaml
              group: DEFAULT_GROUP
              refresh: true
rocketmq:
  name-server: 43.198.184.127:9876
  producer:
    group: test_group
    sendMessageTimeout: 10000
    retryTimesWhenSendFailed: 2
    retryTimesWhenSendAsyncFailed: 2
    maxMessageSize: 4096
    compressMessageBodyThreshold: 4096
    retryNextServer: false
fastjson:
  parser:
    safeMode: true
knife4j:
  enable: true
  production: false
  openapi:
    title: 接口文档
    description: ""
    version: v1.0.0
# 代码使用
@Slf4j
@Data
@Component
public class NacosYamlConfig {
    @Value("${app}")
    private String app;

}

启动报错,找不到app变量

**Comment by tutut5512** [comment]
启动日志
2024-10-17 11:48:55.273 logback [main] INFO  [] o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: [BootstrapPropertySource@1749590097 {name='bootstrapProperties-wesports-ws-local.properties,DEFAULT_GROUP', properties={}}, BootstrapPropertySource@345703799 {name='bootstrapProperties-wesports-ws.properties,DEFAULT_GROUP', properties={}}, BootstrapPropertySource@1463877470 {name='bootstrapProperties-wesports-ws,DEFAULT_GROUP', properties={}}]

**Comment by KomachiSion** [comment]
看下${user.home}/logs/nacos/config.log 日志 是否有订阅和收到对应的dataId配置。

如果日志中没有订阅和获取的日志， 那么看下配置是有有错误导致spring cloud没有读取nacos的配置（比如nacos的地址、dataid、group、namespace等）

如果已经收到了配置，那么请提交ISSUE至spring cloud alibaba咨询。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
