### ISSUE TITLE
docker镜像application.properties中缺少配置

### ISSUE THREAD

**Issue by Super-Orion** [alibaba/nacos#12750]
nacos版本: v2.4.3
异常文件: /conf/application.properties
缺少配置项: nacos.core.auth.enabled=ture
这个是故意删除的吗，现在默认会以不鉴权的方式启动，但是通常情况下不会以这种方式使用吧

**Comment by 985492783** [comment]
默认不开启鉴权，如果需要通过-e环境变量传进去

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/manual/admin/auth/#3-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF%E9%89%B4%E6%9D%83

选择docker镜像部署的tag查看

**Comment by bwangll** [comment]
> nacos版本: v2.4.3 异常文件: /conf/application.properties 缺少配置项: nacos.core.auth.enabled=ture 这个是故意删除的吗，现在默认会以不鉴权的方式启动，但是通常情况下不会以这种方式使用吧

把配置文件映射进去。自己写 比环境变量舒服一些，或者自己重新 build 一下镜像。nacos 的参数挺多的，个人感觉映射比较好。环境变量可配置的不算太多

**Comment by KomachiSion** [comment]
能够按照自己需求自行编译镜像当然最好、 社区绝大多数人使用官方镜像，通过环境变量进行一些常用功能的开关是足够的。

**Comment by Super-Orion** [comment]
> 能够按照自己需求自行编译镜像当然最好、 社区绝大多数人使用官方镜像，通过环境变量进行一些常用功能的开关是足够的。

okok 我这都行，只是做了升级，然后出现了这个问题，感觉这种常用配置缺失可能会引起误解
