### ISSUE TITLE
nacos有适配sw64架构的版本吗？

### ISSUE THREAD

**Issue by jack6266** [alibaba/nacos#12759]
如题： Nacos有适配sw64架构 + kylin V10 的版本吗？

**Comment by Jasonyou-boy** [comment]
Nacos 是使用Java实现的 运行在虚拟机中 ，在不调用本地方法的情况下，也许不需要适配特定指令集和操作系统吧？这应该是JVM的事情。

**Comment by bes2008** [comment]
@Jasonyou-boy 
nacos 使用了 rocksdbjni，如果rocksdbjni没有适配 sw64，nacos也不能正常使用的

**Comment by jack6266** [comment]
没有适配的架构，nacos可以移除rocksdb的依赖吗？

**Comment by jack6266** [comment]
> @Jasonyou-boy nacos 使用了 rocksdbjni，如果rocksdbjni没有适配 sw64，nacos也不能正常使用的


没有适配的架构，nacos可以移除rocksdb的依赖吗？

**Comment by KomachiSion** [comment]
rocksdb是由jraft引入的， jraft可以通过spi引入非rocksdb的raft log实现，可以到jraft社区询问一下如何配置。

rocksdb是jraft的默认实现， 也是jraft的推荐实现，社区会采用jraft推荐的实现，需要替换的话可以自行替换。

**Comment by CherryRum** [comment]
编译了一个版本支持sw-64的nacos-2.4.3,麒麟官网仓库的2.0.3的rpm包不能使用.
见下面地址 https://www.cnblogs.com/lylhqy/p/19093798
