### ISSUE TITLE
【Bug Report】使用Derby数据库时，历史记录清理超过30天的历史时，会把近期的历史记录一起清除

### ISSUE THREAD

**Issue by Melod-YI** [alibaba/nacos#12769]
derby数据库清除历史记录时，sql写的是 id in。 因为id这个字段在update时用的都是之前的id，同一个配置的多条历史的id是一样的。
in后面的sql查出一条记录时，这个配置所有的历史都会被清理掉，哪怕记录时近期才有的。

![image](https://github.com/user-attachments/assets/046d0b52-4d14-4b72-804b-c5112faca6fe)

![image](https://github.com/user-attachments/assets/d61e0f3b-3f6d-49cb-b42c-189975726d8b)

这个bug在2.1.x发现，看目前2.4.x的代码里依旧存在。
可以考虑把id换成nid。

**Comment by Melod-YI** [comment]
![image](https://github.com/user-attachments/assets/e53beef5-6171-46f3-9860-9c4c0975b0b6)

**Comment by MatthewAden** [comment]
似乎确实有这个问题
> 新增配置 :
> id -> 生成的分布式ID
> 更新配置:
> id -> 更新前的id
> 删除配置:
> id -> 删除的配置的id

有个疑问，为什么不直接把 sql 写成 `delete from his_config_info where gmt_modified < ?`

**Comment by Melod-YI** [comment]
> 似乎确实有这个问题
> 
> > 新增配置 :
> > id -> 生成的分布式ID
> > 更新配置:
> > id -> 更新前的id
> > 删除配置:
> > id -> 删除的配置的id
> 
> 有个疑问，为什么不直接把 sql 写成 `delete from his_config_info where gmt_modified < ?`

可能是derby语法和mysql不一样？（猜的）
但是这里看起来应该写nid，而不是id、

**Comment by Melod-YI** [comment]
@KomachiSion 
这是否可以视为bug，我可以提供修复。

**Comment by shiyiyue1102** [comment]
可以改成和mysql一样，根据时间删除

**Comment by KomachiSion** [comment]
> @KomachiSion 这是否可以视为bug，我可以提供修复。


Welcome PR

**Comment by Bo-Qiu** [comment]
> 可以改成和mysql一样，根据时间删除

Derby 数据库不支持使用 LIMIT 关键字来限制 DELETE 语句中受影响的行数，使用 nid 即可， nid 在 config_history 中是唯一的

**Comment by Melod-YI** [comment]
> > 可以改成和mysql一样，根据时间删除
> 
> Derby 数据库不支持使用 LIMIT 关键字来限制 DELETE 语句中受影响的行数，使用 nid 即可， nid 在 config_history 中是唯一的

这个还是有一些问题。请教下需要limit数量是基于什么考量呢？

这个where xx in xx 的写法似乎有性能问题。再his记录较多的情况下，即使实际需要清理的条目为0条。这条sql的执行也会超过5秒。然后会导致以10分钟为周期，出现请求超时、readiness健康检查失败甚至触发选主的情况。

看下是不是把保留历史记录的约束条件修改一下。由仅看日期，修改为同时看日期和条数。
这样保证his表的记录数一直处于一个性能较好的范围内。
