### ISSUE TITLE
NACOS 2.4.0 模式 cluster 下线服务的时候报错

### ISSUE THREAD

**Issue by baibin20** [alibaba/nacos#12767]
![image](https://github.com/user-attachments/assets/0bc35e4c-0788-4fa1-8b88-695b01300f66)
我的是k8s集群,然后下线的时候报错
这是我的配置:
![image](https://github.com/user-attachments/assets/b4e59bda-5027-4231-8fb5-00a5fef80008)
![image](https://github.com/user-attachments/assets/e9f00ea0-b375-41e7-8bee-ddc8ab7f9530)

**Comment by libogithub2018** [comment]
删除nacos、data目录下的protc目录

**Comment by baibin20** [comment]
> 删除nacos、data目录下的protc目录

![image](https://github.com/user-attachments/assets/b5ec1143-244c-48f6-b9df-d61bd3bce232)
删掉了还是不行

**Comment by KomachiSion** [comment]
肯定是部署的集群有问题， 查看cluster.conf文件是否有多余ip，是否集群每个节点的文件均一致， 也可以到控制台的集群管理页面查看每个节点的列表状态是否一致。

**Comment by baibin20** [comment]
> 肯定是部署的集群有问题， 查看cluster.conf文件是否有多余ip，是否集群每个节点的文件均一致， 也可以到控制台的集群管理页面查看每个节点的列表状态是否一致。

![image](https://github.com/user-attachments/assets/d11bfc59-f724-49be-86f5-3a5b1125383b)
这是我集群的配置界面
![image](https://github.com/user-attachments/assets/20e93eab-4e83-45e1-9c06-38473838fc90)
这是我的cluster.conf文件

**Comment by KomachiSion** [comment]
实际多了一个ip，说明你部署的集群没有打开hostname或者domain优先， 节点认为自己的ip不再cluster里，会把自身加入的列表里。

https://nacos.io/docs/latest/manual/admin/system-configurations/#11-%E5%85%A8%E5%B1%80%E5%8F%82%E6%95%B0

nacos.inetutils.prefer-hostname-over-ip 要调整为true

**Comment by baibin20** [comment]
> 实际多了一个ip，说明你部署的集群没有打开hostname或者domain优先， 节点认为自己的ip不再cluster里，会把自身加入的列表里。
> 
> https://nacos.io/docs/latest/manual/admin/system-configurations/#11-%E5%85%A8%E5%B1%80%E5%8F%82%E6%95%B0
> 
> nacos.inetutils.prefer-hostname-over-ip 要调整为true

好的,可以了,谢谢
