### ISSUE TITLE
nacos start failed when server have a highly load

### ISSUE THREAD

**Issue by tm2018** [alibaba/nacos#12779]
nacos start failed when server restart which due to my jars is starting,  it show me timeout when connect to Derby sql. i know why ,but other middleware like mysql/redis/rabbitmq never occour the same errors.

当服务器重启后（nacos和应用在同一台机器），由于应用程序比nacos先启动，会导致服务器负载很高，nacos启动报错连接【本地】Derby数据库（只开启了鉴权，未使用三方数据库）超时。

我能够理解服务器负载高，nacos连接本地库超时的状况，但是其他中间件如redis/mysql/rabbitmq，负载高的情况下依然能够正常启动。

所以想知道是否当前连接本地数据库的机制有问题，或者有没有参数能够增加连接超时时间或者其他方式能减少此状况发生的概率呢？

**Comment by KomachiSion** [comment]
如果无法连接上数据库，必须不能启动， 否则你将获取到空的配置，影响你的业务稳定性（除非你能在业务逻辑中很好的规避这个问题，比如自行处理空配置）

但是并不是所有用户都会，所以为了保证数据一致性（客户端和服务端的），当启动无法连接数据库时，不能启动并提供服务。

不同的产品对数据、稳定性等的要求不一致，例如你提交的：mysql， 本身是单机且依赖磁盘，负载高也就是读取慢或者无法响应请求。

至于超时的问题，主要分为两块：
1. derby数据库自身启动的，因负载高而启动失败，这目前没有什么好办法，只能降低负载，分配更多资源给数据库启动；
2. sql运行超时，可以通过`db.pool.config.connectionTimeout`, `db.pool.config.initializationFailTimeout`等参数提高数据库连接池的一系列超时时间， `db.pool.config.*` 本质上就是将对应的参数注入到Hikari连接池的配置中， 具体Hikari连接池还有哪些参数增加jdbc的超时时间， 可以参考Hikari连接池的文档。

**Comment by KomachiSion** [comment]
最建议的方式还是排查负载高的原因，解决负载问题，否则可能会有无穷的问题等着你去解决（不仅仅指Nacos，其他的所有组件、业务本身，都会出现不可预知的问题）
