### ISSUE TITLE
The error message is not user-friendly when adding duplicate permissions.

### ISSUE THREAD

**Issue by zhouchunhai** [alibaba/nacos#12773]
**Describe the bug**
The error message is not user-friendly when adding duplicate permissions.

**Expected behavior**
I expect a friendly error message, such as 'This permission already exists, please do not add it again.'

**Actually behavior**
The prompt is not friendly enough, as it prints out backend stack trace information.

**How to Reproduce**
1. Enter the permission management page.
2. Add a permission.
3. Add the same permission again.
4. See errors

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [nacos-server 2.4.1]
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**
![image](https://github.com/user-attachments/assets/0f927cf4-3e84-48b2-8bcb-efc36476e299)

**Comment by zhouchunhai** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
Can you upgrade to new version and retry?

**Comment by zhouchunhai** [comment]
version 2.4.3 still has this problem.
![image](https://github.com/user-attachments/assets/4eeeac4f-07b1-42ae-9e36-554c67cfb016)
