### ISSUE TITLE
Nacos2.4.3版本和2.3.1版本，分别添加version-hb后，deploy到私服，走自动化部署工具部署启动报错

### ISSUE THREAD

**Issue by bing568186255** [alibaba/nacos#12774]
环境：
jdk1.8
操作步骤
1、下载Nacos2.4.3源码，更改<revision>2.4.3-hb</revision>,mvn clean deploy到maven私服
2、套一个空的app，依赖maven坐标
  <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-console</artifactId>
            <version>2.4.3-hb</version>
       </dependency>，编写main方法，调用Nacos.main(args)
3、所有配置mysql、cluster配好
4、启动报hession包冲突，（但我看了2.4.2已解决，且在极端情况下jdk17才会出现），以下是报错部分信息：
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.alibaba.nacos.consistency.serialize.NacosHessianSerializerFactory.<init>(NacosHessianSerializerFactory.java:60)

The following method did not exist:

    com.caucho.hessian.io.SerializerFactory.getClassFactory()Lcom/caucho/hessian/io/ClassFactory;

The calling method's class, com.alibaba.nacos.consistency.serialize.NacosHessianSerializerFactory, was loaded from the following location:

    jar:file:/workspace/AppNacos/lib/nacos-consistency-2.4.3-hb.jar!/com/alibaba/nacos/consistency/serialize/NacosHessianSerializerFactory.class

The called method's class, com.caucho.hessian.io.SerializerFactory, is available from the following locations:

    jar:file:/workspace/AppNacos/lib/hessian-3.3.6.jar!/com/caucho/hessian/io/SerializerFactory.class
    jar:file:/workspace/AppNacos/lib/hessian-4.0.63.jar!/com/caucho/hessian/io/SerializerFactory.class

The called method's class hierarchy was loaded from the following locations:

    com.caucho.hessian.io.SerializerFactory: file:/workspace/AppNacos/lib/hessian-3.3.6.jar
    com.caucho.hessian.io.AbstractSerializerFactory: file:/workspace/AppNacos/lib/hessian-3.3.6.jar
5、降低nacos版本到2.3.1，重复上述步骤依旧报错
6、尝试排除sofa下的hessian-3.3.6.jar，启动无报错，但8848本地telnet直接拒绝访问
7、退回到2.0.3版本重复上述步骤，正常，nacos集群自动化部署完毕。

期望用2.2.1+版本nacos服务，并接入公司自动化部署工具！期待大佬们的回复，谢谢！
疑问：hession冲突我这里启动必现，应该不是我deploy的问题？

**Comment by KomachiSion** [comment]
2.4.2解决的hessain 问题， 因为在jdk17情况下会有无法找到方法的问题，因为hessain旧版本不支持jdk17， 因此只能推动sofa-jraft升级hessain， 所以新版本回滚了降低hessain版本以解决冲突的改动。

hessain的重估问题，大概和nacos自身的冲突问题无关， 仅与你项目中自行依赖的版本和nacos引入的版本差异过大导致（看起来你的项目依赖的事4.0的hessain，而nacos和jraft使用的都是3.x的版本， 一般大版本更新会带有极大的架构改动，从而导致一定程度的不兼容， 这个问题估计得你自己尝试解决了。 可以考虑将项目中的hessain版本降低到3.x后尝试。

**Comment by bing568186255** [comment]
> 2.4.2解决的hessain 问题， 因为在jdk17情况下会有无法找到方法的问题，因为hessain旧版本不支持jdk17， 因此只能推动sofa-jraft升级hessain， 所以新版本回滚了降低hessain版本以解决冲突的改动。
> 
> hessain的重估问题，大概和nacos自身的冲突问题无关， 仅与你项目中自行依赖的版本和nacos引入的版本差异过大导致（看起来你的项目依赖的事4.0的hessain，而nacos和jraft使用的都是3.x的版本， 一般大版本更新会带有极大的架构改动，从而导致一定程度的不兼容， 这个问题估计得你自己尝试解决了。 可以考虑将项目中的hessain版本降低到3.x后尝试。

谢谢回复！我的项目没有依赖任何jar，pom里面只依赖了nacos-console，你们可以试一下我这种操作方法；现在我换了一种方式，我用下载下来官方的nacos-server-2.4.3.jar 做为一个项目，实现了自动化部署，谢谢你！

**Comment by bing568186255** [comment]
close

**Comment by 15589957397** [comment]
> close

我也遇到这个问题，请问怎么解决的。使用v2.4.3
