### ISSUE TITLE
k8s的nacos集群，使用python书写巡检脚本，调用nacos接口有问题

### ISSUE THREAD

**Issue by Umbrallerstackcode** [alibaba/nacos#12783]
对于k8s部署的nacos集群，我有多个pod，我想通过访问api的方式，用python脚本将获取的各个pod监控信息（类似给prometheus开放的那种接口），但是遇到的问题是，api的cs下面的list信息虽然有pod的id或者ip，但是监控的信息量太少，而开放的metrics又无法知道我当前获取的是哪个pod的监控信息

所以我的问题是，有没有一个综合上面两个的一个接口，我看官方文档api，没找到，不知道大佬能给个提示不？？

**Comment by KomachiSion** [comment]
没看懂问题。。

**Comment by KomachiSion** [comment]
你是想要监控nacos，还是监控你的应用。

**Comment by Umbrallerstackcode** [comment]
我是想通过接口对部署在k8s上的nacos集群进行巡检，现在有一个问题，就是访问k8s的svc，然后去获取接口的数据，这时候我无法知道是哪个pod返回的监控参数，就是说访问http://192.168.8.181:30848/nacos/actuator/prometheus出来的结果，我无法看到与哪个pod相关

第二个问题，官方上面说的api v1版，可以获取集群leader，但实际操作后返回501的结果，但是我在控制台上面的节点元数据，可以正常看到集群leader的，所以我搞不懂，这是接口的问题还是说我集群的问题，但是目前看集群没问题

**Comment by KomachiSion** [comment]
1. actuator返回的监控数据，本身就只反应这个节点自身的数据， 区分指标来源是采集器要做的事， 并非暴露指标的节点。
2. 新版本中已经移除了直接获取leader的接口， 因为新版本的raft 有至少4个 raft gourp， 每个group的leader可能是不同的节点，需要获取leader可以通过`nodes` api获取node的metadata，然后取你最希望监控的raft gourp的leader作为leader。

**Comment by Umbrallerstackcode** [comment]
对于答复1，auto返回节点的信息，但是我访问的是k8s的service，返回的信息中没有任何pod或者节点信息的标识，我最开始的疑问也是这个，怎么样才能让当前pod节点和他的数据信息一起返回，麻烦大佬解答下

**Comment by KomachiSion** [comment]
采集监控不是在k8s集群内，通过pod信息去采集吗？ 应该不实用service吧， service是提供给微服务上游使用的。

如果需要将pod信息一起返回，那需要您自行修改代码，在所有metrics中添加自定义lebel来记录

**Comment by Umbrallerstackcode** [comment]
你说的那种在pod内采集的方式是使用prometheus这种监控系统进行的，我问题最开始已经说了，我是通过python自己写的巡检脚本去调用部署在k8s上的nacos集群，这时运行巡检脚本，我必然是要在主机节点上运行py文件，那这时就需要访问service，你可以测试，返回的autoscaler信息没有当前pod的ID标识，如果没有其他方式的话，那这个是不是就是当前nacos的bug呢？

**Comment by Umbrallerstackcode** [comment]
如何在metrics中添加自定义标签

**Comment by KomachiSion** [comment]
> 你说的那种在pod内采集的方式是使用prometheus这种监控系统进行的，我问题最开始已经说了，我是通过python自己写的巡检脚本去调用部署在k8s上的nacos集群，这时运行巡检脚本，我必然是要在主机节点上运行py文件，那这时就需要访问service，你可以测试，返回的autoscaler信息没有当前pod的ID标识，如果没有其他方式的话，那这个是不是就是当前nacos的bug呢？

不属于， 因为metrics只暴露自身节点的监控数据，来采集的时候你是知道你采集的是哪个pod的，  至于你通过service来采集metrics，这本身逻辑就有问题，因为你这样一次采集只能采集到1个节点的数据， 本身就不全。

如果一定要这样做，你需要自行想办法在metrics指标中添加对应的标签和label。

比如通过一个代理中转，加上对应label，或者直接修改nacos源代码添加当前节点的信息到metrics，自行打包部署。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
