### ISSUE TITLE
网关api-gateway，从springboot2.3.3RELEASE版本升级到2.6.13版本，dataId读取properties文件可以，但是yaml文件启动总是卡主？

### ISSUE THREAD

**Issue by 15102552479** [alibaba/nacos#12787]
**Is your feature request related to a problem? Please describe.**
网关api-gateway，从springboot2.3.3RELEASE版本升级到2.6.13版本，启动总是卡主？
如图所示

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 15102552479** [comment]
![1](https://github.com/user-attachments/assets/6022cf36-ab1e-4691-bbc1-3edf1468dfa6)

**Comment by KomachiSion** [comment]
![image](https://github.com/user-attachments/assets/90c0c443-88b9-4a01-92b6-dd18bf21ffaa)

配置的用户密码有误， 导致无法获取最新配置。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
