### ISSUE TITLE
images of docs in  use-nacos-with-kubernetes  has error about 404 not found

### ISSUE THREAD

**Issue by OhIAmFine** [alibaba/nacos#1279]
The images in `https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html` has errors.
It seems to has the wrong img url.
https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html
![image](https://user-images.githubusercontent.com/10390004/58449002-4f4d5600-813c-11e9-84fc-2acb2af5567f.png)

**Comment by nkorange** [comment]
Thanks, we will fix it soon.

**Comment by nkorange** [comment]
Already fixed.
