### ISSUE TITLE
nacos前端显示历史版本(保留30天)

### ISSUE THREAD

**Issue by qq516249940** [alibaba/nacos#12794]
nacos前端显示历史版本(保留30天)，我们修改了nacos.config.retention.days=60，前端依旧显示30.

![image](https://github.com/user-attachments/assets/1f057879-707d-45b4-82d9-ea94c15601e6)

nacos version 2.4.2  2.4.3

![image](https://github.com/user-attachments/assets/39187099-824b-4bc6-b40e-25a5e65d66d0)

**Comment by fuhouyu** [comment]
#12614 看下这个，已经有pr了。
