### ISSUE TITLE
希望可以增加nacos-server的maven依赖 这样可以通过maven导入server依赖启动 便于调试和单元测试

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/nacos#12790]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JavaLionLi** [comment]
目前自动化单元测试流水线还得写shell脚本单独启动一个nacos服务 太恶心了 seata那边提供了server依赖就很方便单元测试 不用特意搭建一个seata就可以单元测试

**Comment by KomachiSion** [comment]
调试可以用docker启动一个单机实例，或者部署一个。

单元测试依赖一个实际环境？  那你做的应该不是单元测试， 至少是集成测试。

单元测试的一个要点就是不依赖环境， 可重放可独立。

至于maven中发布nacos-server， 目前没有这方面计划。

**Comment by KomachiSion** [comment]
> 写一些 插件时，可能会用到 nacos-common, nacos-core包，建议发布到maven 仓库 @KomachiSion

common有， 而且插件对应的包有发布到maven仓库， 比如nacos-auth-plugin。

**Comment by KomachiSion** [comment]
core 因为也是强依赖spring的，写插件也不应该依赖，所也没有计划发布到maven仓库。

**Comment by bes2008** [comment]
@KomachiSion 刚才确认了一下，写插件时，会用到 nacos-common, nacos-sys两个模块。
如您据说，nacos-common已发布，但目前nacos-sys是没有的。

**Comment by JavaLionLi** [comment]
希望可以把所有的包都发到maven 大家各取所需

**Comment by KomachiSion** [comment]
> @KomachiSion 刚才确认了一下，写插件时，会用到 nacos-common, nacos-sys两个模块。 如您所说，nacos-common已发布，但目前nacos-sys是没有的。

sys是依赖spring 的基础module， 属于服务端的module，目前没有计划发布。

**Comment by KomachiSion** [comment]
> 希望可以把所有的包都发到maven 大家各取所需

短期内暂时没有这个计划
