### ISSUE TITLE
2.4.3版本使用使用镜像部署后,权限控制里的用户列表在获取用户列表时一直显示Request error,please try again later!

### ISSUE THREAD

**Issue by Anddio** [alibaba/nacos#12800]
使用环境：
nacos镜像v2.4.3
部署平台蓝鲸7
k8s部署
配置环境：
![image](https://github.com/user-attachments/assets/13373804-95a6-479c-9308-61f628fb2bd7)

出现问题：
![image](https://github.com/user-attachments/assets/6c19f903-5cc0-4ce4-b812-9abf282079c0)

![image](https://github.com/user-attachments/assets/80886da5-c333-4094-b56e-831bc9fb401c)

复现：
部署nacos镜像完成后，登录进nacos网页端，点进权限控制里的用户列表，此时还是能正常获取用户列表的。
之后不动nacos网页端,不做任何操作，挂机一段时间后，再去点击权限控制里的用户列表，就会产生用户列表获取失败的问题。
网页端提示：Request error,please try again later!

**Comment by KomachiSion** [comment]
看报错应该是网络问题， 连接被reset了，建议从环境层面进行排查，看下是否有网络设备reset了连接， 比如vpn， vip，转发器等

**Comment by Anddio** [comment]
我下载非镜像nacos2.4.3版本在本地运行是能够正常运行的，并且没有使用vpn。网络设备等reset了连接的可能性很小，因为其它的请求都正常。

**Comment by KomachiSion** [comment]
那是不是k8s的 services或 enovy reset的， 官方镜像和官网的非镜像可运行包是同一个包（镜像就是从非镜像可运行包下载的然后打成的镜像）

所以这个问题大概率真的是环境相关问题。

**Comment by Anddio** [comment]
但是如果是环境问题，应该所有的请求都有这个问题才对，但是我测试了其它的请求，都正常，只有获取用户列表时才异常。我在蓝鲸7上看日志，日志没有显示什么异常。

**Comment by Anddio** [comment]
而且我在issues上也看到过别人也有类似问题，
https://github.com/alibaba/nacos/issues/12006

**Comment by KomachiSion** [comment]
> 但是如果是环境问题，应该所有的请求都有这个问题才对，但是我测试了其它的请求，都正常，只有获取用户列表时才异常。我在蓝鲸7上看日志，日志没有显示什么异常。

如果是代码问题，你不用镜像部署也会出现， 这里唯一的区别和变量就是部署的环境。

**Comment by Anddio** [comment]
nacos基础环境已经被你们打包好放入镜像里面了，部署镜像时使用的环境是你们配置的。平台上运行镜像时是正常的

**Comment by Anddio** [comment]
本地运行是用本地的环境

**Comment by Anddio** [comment]
k8s部署、运行日志也无异常

**Comment by Anddio** [comment]
你觉得是平台环境问题就是平台环境问题吧

**Comment by Anddio** [comment]
没有解决方法和思路就算了

**Comment by huabanyu8411** [comment]
You can clean up the Chrome browser cache and try again
