### ISSUE TITLE
nacos 2.1.2 有手动触发生成快照的接口吗

### ISSUE THREAD

**Issue by yangpengboo** [alibaba/nacos#12801]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
没看懂问题， 触发生成什么快照？ 服务端的，客户端的，配置的还是服务的。

**Comment by yangpengboo** [comment]
> 没看懂问题， 触发生成什么快照？ 服务端的，客户端的，配置的还是服务的。

服务端每个集群节点生成快照文件data/protocol/raft/nacos_config/snapshot，现在默认是半小时自动生成一次
nacos.core.protocol.raft.data.snapshot_interval_secs=30

**Comment by KomachiSion** [comment]
不清楚你用的哪个版本， 给你最新版本的对应接口

https://nacos.io/docs/latest/manual/admin/admin-api/?source=blog#19-raft-%E7%9B%B8%E5%85%B3%E6%93%8D%E4%BD%9C
