### ISSUE TITLE
pod注册上去是宿主机地址但是nacos中显示的是k8s分配的地址

### ISSUE THREAD

**Issue by baibin20** [alibaba/nacos#12807]
![image](https://github.com/user-attachments/assets/be0f638f-e712-456e-8e96-caa3d7ecbd9c)
这是我k8s中pod的ip地址我做了hostNetwork: true 这个配置,这个是在pod中配置的
然后我注册到nacos上的地址是k8s的分配:10.233.111.0
![image](https://github.com/user-attachments/assets/81230295-9b70-42f3-950e-400affafd255)

**Comment by KomachiSion** [comment]
nacos-client的注册接口你可以看一下， 注册的ip是由应用传递给nacos的，不是nacos自行获取的，  所以如果显示的是pod ip，你期望是宿主机ip， 你需要修改你的应用， 读取宿主机ip。

如果你使用的是其他的应用框架帮您注册的实例， 请提交issue至对应框架上。

**Comment by baibin20** [comment]
> nacos-client的注册接口你可以看一下， 注册的ip是由应用传递给nacos的，不是nacos自行获取的， 所以如果显示的是pod ip，你期望是宿主机ip， 你需要修改你的应用， 读取宿主机ip。
> 
> 如果你使用的是其他的应用框架帮您注册的实例， 请提交issue至对应框架上。

那我在nacos注册时候怎么配置宿主机

**Comment by linwumingshi** [comment]
spring.cloud.nacos.discovery.ip

**Comment by baibin20** [comment]
> spring.cloud.nacos.discovery.ip

我是k8s架构,我可以在k8s中设置吗?如果可以怎么设置?

**Comment by baibin20** [comment]
> > > spring.cloud.nacos.discovery.ip
> > 
> > 
> > 我是k8s架构,我可以在k8s中设置吗?如果可以怎么设置?
> 
> sorry，我搞错了。您这个不是SpringCloud的。

没关系,那我这种情况如何解决

**Comment by KomachiSion** [comment]
这个问题和nacos没有关系， 您应该到k8s社区询问， pod里如何获得宿主机ip

**Comment by baibin20** [comment]
> 这个问题和nacos没有关系， 您应该到k8s社区询问， pod里如何获得宿主机ip
> 
> 然后在应用里获取到这个宿主机ip， 然后调用register接口时使用宿主机ip

问题已解决,谢谢
