### ISSUE TITLE
【Tongyi Lingma】Cannot use the plugin in VSCode, since version 1.4.4

### ISSUE THREAD

**Issue by lk101** [alibaba/nacos#12806]
首先，很抱歉在这里提出与nacos无关的bug，但我实在找不到哪里可以反馈通义灵码的VSCode插件问题，如果您知道相关的反馈途径，请告知我，我会在第一时间删除/关闭此issue，谢谢！

Firstly, I apologize for creating an issue here that is not related to Nacos. However, I am really unable to find a place to provide this feedback. If you have any feedback channels related to this issue, please let me know and I will delete/close this issue as soon as possible. Thank you!

**Describe the bug**
自从1.4.4版本后，VSCode的通义灵码插件就出现了操作面板空白的情况，导致在VSCode中无法正常使用了。效果如下：

![image](https://github.com/user-attachments/assets/c0f95aac-e3aa-4bb9-9890-7af6031ea1d3)

目前1.4.4版本和最新的1.4.5版本均存在此问题，但回滚到1.4.3版本，问题现象消失，通义灵码又可以正常使用了。
BTW：Intellij IDEA plugin各版本均正常工作

**Expected behavior**
在未来的版本中，能够修复此问题，使最新版本的通义灵码插件能够在VSCode上正常使用

**Actually behavior**
Refer to the bug description.

**How to Reproduce**
Omitting operational steps, please refer to the bug description.

**Desktop (please complete the following information):**
- OS：Windows 11 家庭中文版 23H2 22631.4391
- CPU：12th Gen Intel(R) Core(TM) i5-12450H   2.00 GHz
- RAM：16.0 GB (15.7 GB 可用)
- OS Type：64 位操作系统, 基于 x64 的处理器
- Network：雇主网络限制了白名单外的网络访问，阿里云相关的网址只开放了通义灵码api访问网址和登录通义灵码的必须网址
- VSCode：1.95.1(user setup)
- Other VSCode plugins：
![image](https://github.com/user-attachments/assets/b33dbf4f-79bc-4950-a147-2a14dad000db)
![image](https://github.com/user-attachments/assets/35bb8c65-14e8-4a40-a344-b05e911baf97)

**Additional context**
None.

**Comment by KomachiSion** [comment]
我也不知道，可以帮你问问，不保证有结果，issue可以先放几天，如果实在没有结论，过几天还是会close的，抱歉。
