### ISSUE TITLE
Nacos CWE-942 漏洞问题

### ISSUE THREAD

**Issue by gaoxing-china** [alibaba/nacos#12811]
Nacos没有开启CORS配置，但当Request标头带Origin是任意域名时，Nacos服务返回的Response Headers中开启了Access-Control-Allow-Origin配置，并且是请求头中Origin的值，例如请求是header中加了，Origin = https://www.sssss.com , nacos返回的response headers中就会包括：Access-Control-Allow-Origin= https://www.sssss.com， Access-Control-Allow-Credentials=true；

**Comment by KomachiSion** [comment]
是的 ，Nacos没有开启CORS配置， 所有的跨域请求都会接收并处理，方便1.X客户端、和控制台进行嵌入。

Nacos被设计为内部网络的服务发现和配置管理系统，不建议开放服务到公开性质的网络中使用，同时Nacos有自身的身份验证和权限机制，正常来说既是来自跨域等请求，在开启鉴权后也需要进行身份和权限认证，较大程度阻止相关问题。

如果您有关于这方面的诉求， 可以描述您的使用场景和需求， 看下后续版本是否提供配置支持，3.0版本中可能会对很多这方面的内容做修改， 如果您的使用场景和需求可以的话，3.0版本中可以添加。

**Comment by gaoxing-china** [comment]
使用场景：
       我们的SpringCloud应用，使用nacos（2.2.3）版本作为服务发现和配置管理系统，整个应用是私有化部署到客户的服务器环境内，客户对应用多所有反问地址找安全团队做了漏洞扫描，其中包括nacos管理系统的访问地址，安全团队给出的安全报告针对nacos管理系统访问地址给出了一个“高”级别的漏洞，同时包括一个“中”级别的漏洞；

**高风险漏洞**，类别：CWE-942，对象：NACOS 管理平台，影響範圍：
https://r-sit-nacos.*******.com/nacos/console-ui/public 
https://r-sit-nacos.*******.com/nacos/console- ui/public/js/codemirror.lib.json-lint.js 
https://r-sit-nacos.*******.com/nacos/console- ui/public/js/codemirror.addone.lint.js 
https://r-sit-nacos.*******.com/nacos/console-ui/public/js/vs 
https://r-sit-nacos.*******.com/nacos/console- ui/public/js/vs/editor 
https://r-sit-nacos.*******.com/nacos/console- ui/public/js/diff_match_patch.js 
https://r-sit-nacos.*******.com/nacos/console- ui/public/js/codemirror.addone.fullscreen.js 
https://r-sit-nacos.*******.com/nacos/console- ui/public/js/codemirror.js 
https://r-sit-nacos.*******.com/nacos/css
        問題描述：這個 CORS 錯誤配置可能讓攻擊者從受害者的用戶代理加 載的惡意頁面，對易受攻擊的網站執行 AJAX 查詢。為了 執行經過身份驗證的 AJAX 查詢，伺服器必須在回應標頭 中指定 "Access-Control-Allow-Credentials: true"，同時 "Access-Control-Allow-Origin" 標頭可能錯誤地設置為 null 或惡意頁面的網域。即使這個錯誤配置不允許經過身份驗 證的 AJAX 請求，未經身份驗證的敏感內容仍可能被存取(例如內部網網站)。惡意頁面可能屬於惡意網站，也可能 是有漏洞的可信任網站(例如 XSS 漏洞、支持未經 TLS 的 HTTP 通訊協定，允許透過中間人攻擊注入代碼等)。
       改善建議：如果網頁資源包含敏感資訊，應在 "Access-Control-Allow- Origin" 標頭中正確指定來源。只有真正需要此資源的受信 任網站才能在此標頭中被指定，並應採用最安全的通訊協 定。

      中风险漏洞，类别：OWASPA05:2021-安全設定缺陷，对象：NACOS 管理平台，影響範圍：
https://r-sit-nacos.*******.com/nacos
     問題描述：檢測到您的網站未最佳化 CSP 安全性設定。 內容安全策略(CSP)是附加性的安全措施，有助於檢測 和緩解某些類型的攻擊，包括跨域腳本攻擊(XSS)和數 據注入攻擊。 CSP 提供了一組標準 HTTP 標頭，允許網站 所有者聲明允許瀏覽器在該頁面上加載的已批准內容來源- 涵蓋的類型包括 JavaScript，CSS，HTML 框架，字體，圖 像和可嵌入對象，例如 Java applet，ActiveX，音頻和視頻 文件。
      改善建议：• 限制外部連入的檔案和禁用 inline 語法，這是預設全部阻 擋的寫法，也是最嚴格最安全的方案，設定範例如下 content-security-policy:default-src 'none';
• 增加外部連入的白名單，限制外部連入的來源，請避免 在來源 url 中使用「*」，設定範例如下
content-security-policy:default-src 'none'; script-src 'self' https://www.google.com;
• 避免在 CSP 設定中使用「unsafe-inline」

**问题请教：**
请问以上漏洞是否有应对方案？只是关闭公网访问或者是否可以指定可访问的域名？

**Comment by KomachiSion** [comment]
目前没有针对这方面的配置项，如果需要的话可能需要修改代码`com.alibaba.nacos.console.config.ConsoleConfig#corsFilter`

可以考虑给社区提交一个PR，把这个值作为可选参数进行配置。

**Comment by gaoxing-china** [comment]
收到，感谢！

**Comment by Self-revolution** [comment]
我也遇到这个问题了，现在支持配置吗
