### ISSUE TITLE
服务注册成功，但是获取不到对应配置

### ISSUE THREAD

**Issue by molemole2** [alibaba/nacos#12812]
最近在做项目springboot2升级到springboot3，这是我升级以后得版本：spring Cloud Alibaba Version为2023.0.0.0-RC1，Spring Cloud Version为2023.0.0，Spring Boot Version为3.2.0，服务启动后注册是成功的，但是获取不到对应的配置文件信息,起初以为是nacos版本过低，把nacos从2.0.2版本升级到了2.3.2版本，还是不行。下面是我的bootstrap.yml配置信息
spring:
  application:
    # 应用名称
    name: ruoyi-gateway
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        # 服务注册地址
        server-addr: ***.**.***:8848
        namespace: ai
      config:
        # 配置中心地址
        server-addr: ***.**.***:8848
        # 配置文件格式
        file-extension: yml
        refresh-enabled: true，问题是服务正常注册了，但是获取不到ruoyi-gateway.yml的配置信息

**Comment by molemole2** [comment]
![20241103-231933](https://github.com/user-attachments/assets/b9afa11a-3976-4240-b798-3260422d9940)
nacos服务上可以看到服务注册了，但是就是获取不到对应的文件配置

**Comment by fuhouyu** [comment]
这应该是和配置文件的加载优先级有关。
[spring-cloud-config](https://docs.spring.io/spring-cloud/docs/2020.0.1/reference/htmlsingle/#config-first-bootstrap)
设置该值为true: `spring.cloud.bootstrap.enabled=true`
或者加入该依赖试下
```
 <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```

**Comment by molemole2** [comment]
> 这应该是和配置文件的加载优先级有关。 [spring-cloud-config](https://docs.spring.io/spring-cloud/docs/2020.0.1/reference/htmlsingle/#config-first-bootstrap) 设置该值为true: `spring.cloud.bootstrap.enabled=true` 或者加入该依赖试下
> 
> ```
>  <dependency>
>     <groupId>org.springframework.cloud</groupId>
>     <artifactId>spring-cloud-starter-bootstrap</artifactId>
> </dependency>
> ```

![img_v3_02ga_ccb62e9b-e8b3-446e-94f1-c329487dce0g](https://github.com/user-attachments/assets/6c6f0d21-c322-4df7-b6e9-06f0dd68e885)
![img_v3_02ga_196808ea-d67e-4cf6-9d9c-b5bf1966108g](https://github.com/user-attachments/assets/7d0d73fe-07df-4d1c-8b5d-ea88857f7a8c)
项目存在此依赖，但是没有你说的这个配置项

**Comment by KomachiSion** [comment]
Spring Cloud  的配置方式可能有改动，建议到spring cloud alibaba的官网文档中查看一下新的配置方式。

若还有问题，可以将issue 转到spring cloud alibaba社区询问。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.

**Comment by xiaojiewhisper** [comment]
这个问题解决了吗？我按照官网推荐的版本  还是不行呢
