### ISSUE TITLE
更新元数据，不移除serviceStorage的缓存

### ISSUE THREAD

**Issue by floor07** [alibaba/nacos#12828]
更新元数据，已移除serviceStorage的缓存

**Comment by floor07** [comment]
@i will solved it @ https://github.com/alibaba/nacos/pull/12827

**Comment by KomachiSion** [comment]
Why update metadata need remove serviceStorage?

**Comment by floor07** [comment]
client更新元数据后，serviceStorage 如果不更新，控制台显示的还是旧的

**Comment by KomachiSion** [comment]
但是会更新啊

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
