### ISSUE TITLE
本地调试nacos源码报错无法启动Tomcat

### ISSUE THREAD

**Issue by zhrgithub** [alibaba/nacos#12821]
本地调试nacos源码报错无法启动Tomcat
本地环境Java8
Maven 3.8
配置单例启动不生效
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/5fe78df6-9fde-4b55-8371-a2e760a5cd42">

![本地调试nacos源码报错无法启动Tomcat](https://github.com/user-attachments/assets/960081fc-7e77-4ef8-a26f-4f684ed06857)

**Comment by KomachiSion** [comment]
请查看上下文日志，看下具体的原因。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
