### ISSUE TITLE
Nacos集群，运行一段时间后，个别节点不定时出现CPU飙升的情况

### ISSUE THREAD

**Issue by shuguangFJ** [alibaba/nacos#12820]
服务端版本：2.3.2/2.4.2.1
客户端版本：2.3.2
三个节点组成的一个集群，不定时的会出现个别节点CPU飙升，使用率达到100%，进程挂掉的情况。

线程运行情况：
![t](https://github.com/user-attachments/assets/57e75663-231d-45b5-b8ab-10cefb344179)

使用netstat命令，查看到9848,9849端口有很多CLOSE_WAIT状态的连接。

**Comment by KomachiSion** [comment]
没有遇到过这个情况， 操作系统是windows吗？

**Comment by shuguangFJ** [comment]
操作系统用的麒麟
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Sword)"

**Comment by KomachiSion** [comment]
可以打印一下CPU占用高的线程的堆栈， 看一下是否是Nio的Selector占用了CPU资源， 如果是的话，那应该是jdk NIO的bug，和window上的问题一样，

如果不是的话， 可以把堆栈贴出来， 看一下什么地方占用了过高的CPU。

也可以用arthas抓一下火焰图，可能更直观一点。

**Comment by shuguangFJ** [comment]
> 可以打印一下CPU占用高的线程的堆栈， 看一下是否是Nio的Selector占用了CPU资源， 如果是的话，那应该是jdk NIO的bug，和window上的问题一样，
> 
> 如果不是的话， 可以把堆栈贴出来， 看一下什么地方占用了过高的CPU。
> 
> 也可以用arthas抓一下火焰图，可能更直观一点。

这是之前抓的堆栈信息和火焰图
[103836.zip](https://github.com/user-attachments/files/17808158/103836.zip)

**Comment by KomachiSion** [comment]
从火焰图来看，感觉是grpc的queue实现有问题， 在这个系统下会把CPU跑满， 可以到grpc社区搜索一下对应issue，看下是配置的问题还是版本问题。

我的环境是复现不出这个问题。

**Comment by KomachiSion** [comment]
Any respsone？

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.

**Comment by wfqian** [comment]
老哥，你解决了吗？ 我现在生产也碰到了这个问题。
