### ISSUE TITLE
nacos跨集群数据同步问题咨询

### ISSUE THREAD

**Issue by wxrqforever** [alibaba/nacos#12825]
Hi

我们在生产环境部署了主备两套nacos，服务信息的主备同步我了解到可以使用nacos-sync，想了解一下，配置信息的同步是否有类型的工具？
我目前没有了解到有相关的配套组件/工具，所以想是否可以从mysql层面同步主备两个db的数据，想咨询一下，这么做是否有潜在的风险，此外是否也可以作为一种服务信息同步的方案。

以上，期待您的回复。

**Comment by KomachiSion** [comment]
1. nacos-sync主要用于迁移的场景， 即短期内进行服务的数据同步，长期使用则需要考虑sync自身的稳定性问题以及nacos-server的性能负载问题，不是很推荐。
2. 配置目前没有实时同步工具，同样也是因为迁移可以通过导入导出配置的方式迁移，所以目前没有实时方式。

从运维和微服务最佳实践的角度，不是很推荐配置两个共享集群进行实时数据同步的方案， 如果需要做多机房容灾，可以根据机房的属性（比如同城、异地）导致的网络延迟等情况来定，看是跨机房组集群， 还是走机房内闭环的方案。

**Comment by wxrqforever** [comment]
> 1. nacos-sync主要用于迁移的场景， 即短期内进行服务的数据同步，长期使用则需要考虑sync自身的稳定性问题以及nacos-server的性能负载问题，不是很推荐。
> 2. 配置目前没有实时同步工具，同样也是因为迁移可以通过导入导出配置的方式迁移，所以目前没有实时方式。
> 
> 从运维和微服务最佳实践的角度，不是很推荐配置两个共享集群进行实时数据同步的方案， 如果需要做多机房容灾，可以根据机房的属性（比如同城、异地）导致的网络延迟等情况来定，看是跨机房组集群， 还是走机房内闭环的方案。

感谢答疑
我们当前的场景是是跨区域部署两套nacos集群，比如深圳和上海，其中深圳作为主集群对外服务，上海作为备份不对外服务。我们希望南京作为备份能够接近实时同步获取到广州的注册信息和配置信息。

我们目前是打算注册信息的同步就通过nacos-sync，而配置信息可能是通过一个周期性的脚本进行同步。关于回答中提到的不是很推荐nacos-sync作为长期数据同步方案，这方面能否展开介绍一下，是否是曾经有过相关类似的实践，它的部署会对nacos会带来很大的性能负载吗？

**Comment by KomachiSion** [comment]
> > 1. nacos-sync主要用于迁移的场景， 即短期内进行服务的数据同步，长期使用则需要考虑sync自身的稳定性问题以及nacos-server的性能负载问题，不是很推荐。
> > 2. 配置目前没有实时同步工具，同样也是因为迁移可以通过导入导出配置的方式迁移，所以目前没有实时方式。
> > 
> > 从运维和微服务最佳实践的角度，不是很推荐配置两个共享集群进行实时数据同步的方案， 如果需要做多机房容灾，可以根据机房的属性（比如同城、异地）导致的网络延迟等情况来定，看是跨机房组集群， 还是走机房内闭环的方案。
> 
> 感谢答疑 我们当前的场景是是跨区域部署两套nacos集群，比如深圳和上海，其中深圳作为主集群对外服务，上海作为备份不对外服务。我们希望南京作为备份能够接近实时同步获取到广州的注册信息和配置信息。
> 
> 我们目前是打算注册信息的同步就通过nacos-sync，而配置信息可能是通过一个周期性的脚本进行同步。关于回答中提到的不是很推荐nacos-sync作为长期数据同步方案，这方面能否展开介绍一下，是否是曾经有过相关类似的实践，它的部署会对nacos会带来很大的性能负载吗？

nacos-sync 需要保持可用性至少需要2～3副本部署， 意味着同一个服务可能会被2～3个服务同时进行同步， 实际的请求量比源集群会高2～3倍至少。

同时单个nacos-sync的同步服务数量也是有上限的，如果按照命名空间或者服务名拆分部署的话，nacos-sync的数量可能比nacos-server的数量还多。

**Comment by wxrqforever** [comment]
明白了 多谢
