### ISSUE TITLE
When a service is deleted from the list of services, all services that are not associated with the deleted service will report an error.

### ISSUE THREAD

**Issue by xinchungitHub** [alibaba/nacos#1283]
首先我们设计的每个微服务,相当于一个小项目,我们项目之间不会互相调用更没有什么订阅关系
当我把其中一个服务删除掉之后,所有服务都会报错. 我想要的是那个服务假如我不想要了,我把他删除掉,但是我其他服务并没有订阅他啊,是因为nacos设置相同分组就代表相互订阅吗

**Comment by nkorange** [comment]
@xinchungitHub 没有订阅的话，不会去查询的，检查下是否哪里有订阅。
