### ISSUE TITLE
NacosSer2.3.2经常出现微服务重启后就连接不上，一直断开连接

### ISSUE THREAD

**Issue by miwucc** [alibaba/nacos#12831]
K8上部署nacosSer，single模式启动，用service地址端口暴漏给微服务来连接。会偶发性的出现，15个微服务实例连上来获取配置和注册应用，突然有一个重启之后，就一直连不上了。报connection disconnected。不管怎么样都连不上，其他的微服务重启又能连上。
然后一直等待，可能等个几小时后又能连接了，然后第二天可能某一段时间又会出现这种现象持续几个小时。
<img width="1263" alt="1f551e1f7774e5f1c9a540a759e1ab1" src="https://github.com/user-attachments/assets/818df9fd-33fc-4327-996c-40e28dc333a3">

出现这个现象的时候，看了nacos日志，JVM GC，连接数都正常。用telnet测试ip和端口连通性没有任务问题，nacos连接的mysql负载也没有任何问题，但是就是连不上。求大佬给一下排查思路。

k8s:1.30.0
istio：1.23.2 网络模式ipvs
nacosSer版本：2.3.2
nacosClient版本：2.2.0

**Comment by KomachiSion** [comment]
我的理解应该是网络环境问题吧， 15个服务都正常，只有1个不正常，排除法大概率也是这一个不正常的服务本身或者环境有问题吧。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
