### ISSUE TITLE
未授权访问api咨询

### ISSUE THREAD

**Issue by yanshicheng** [alibaba/nacos#12835]
访问api没有登陆会直接展示信息，请问这个是官网允许的还是算漏洞，当前版本是 2.3.2 
If you access the api without logging in, you will directly display the information. Is this allowed by the official website or is it a vulnerability? The current version is 2.3.2
![image](https://github.com/user-attachments/assets/4b5f68da-154f-4791-8cd1-f02243490d81)

**Comment by KomachiSion** [comment]
此接口为公开接口，很多其他issue已经回答过，请自行检索
