### ISSUE TITLE
添加服务列表变化的监听

### ISSUE THREAD

**Issue by gjf001** [alibaba/nacos#12839]
我们SpringCloud服务中使用了动态路由，新服务注册到nacos后，可以监听到该服务，我们的程序会自动为该新服务添加新的路由。
之前使用的2.1.2版本，通过修改源码，服务注册完后，发送rabbitmq，但升级到2.4.3后，按照之前的方法修改了源码，可以正常启动和注册，但服务点击下线的时候报错

**Comment by KomachiSion** [comment]
自行修改源码后， 问题排查需要自行处理，或者提供具体的错误内容。社区才能够给予讨论和解决方案。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems custom source code modified problem
