### ISSUE TITLE
nacos2.4.3 NacosException: Client not connected,current status:UNHEALTHY

### ISSUE THREAD

**Issue by Marswxq** [alibaba/nacos#12846]
客户端突然出现：NacosException: Client not connected,current status:UNHEALTHY

**Comment by KomachiSion** [comment]
duplicate with #10916

**Comment by KomachiSion** [comment]
Please check network or client work load first.

Or provider more information.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
