### ISSUE TITLE
org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found

### ISSUE THREAD

**Issue by xiaohaiGit** [alibaba/nacos#12848]
**Describe the bug**
使用最新的nacos-config-spring-boot-starter:0.3.0-RC , 报错 <org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found ，发现原因是与依赖的底层的snakeyaml 接口SafeConstructor 不兼容，在snakeyaml 2.0 版本后，SafeConstructor  没有无参构造了。但是在nacos 中，依然使用SafeConstructor的无参构造。导致报错

**Expected behavior**
org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found

**Actually behavior**
org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by xiaohaiGit** [comment]
![16e5ff6e4b799dc6800cb153d25ce0bdce669aab1062a5d13d3963b35dac1982QzpcVXNlcnNcRGVsbFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMzIxOTAwODE1X3YyXEltYWdlRmlsZXNcMTczMTU0OTYzMDE0MF9ENTI0NzQyNC1DNkRBLTRjMjctQkMzNi05Nzg3QTUzMDk4RUMucG5n](https://github.com/user-attachments/assets/d34fd960-244f-49e8-9c27-16ea9cbdf9a6)

**Comment by xiaohaiGit** [comment]
![16e5ff6e4b799dc6800cb153d25ce0bdce669aab1062a5d13d3963b35dac1982QzpcVXNlcnNcRGVsbFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMzIxOTAwODE1X3YyXEltYWdlRmlsZXNcMTczMTU0OTYzMDE0MF9ENTI0NzQyNC1DNkRBLTRjMjctQkMzNi05Nzg3QTUzMDk4RUMucG5n](https://github.com/user-attachments/assets/9e6a2141-a2f0-4e9a-88a5-382fa822045d)

**Comment by xiaohaiGit** [comment]
这个问题是出在使用springboot 3.2.0 + 的版本出现了。试了下3.1 版本的，没有这个问题。这说明， 现在的nacos springboot 版本，没有兼容最新的springboot

**Comment by KomachiSion** [comment]
duplicate with #12076。

welcome submit pr to fix it.
