### ISSUE TITLE
支持yaml 配置格式校验

### ISSUE THREAD

**Issue by melin** [alibaba/nacos#12847]
支持yaml 配置格式校验，有时候配置格式错误了，保存时候不校验，只有启动应用读取配置，才发现配置格式错误。

**Comment by KomachiSion** [comment]
配置内容对nacos来说是黑盒， console上的编辑器应该有简单的红线提示， 引擎不会对格式做校验，如果有需求，可以考虑开发自定义插件来处理：

https://nacos.io/docs/latest/plugin/config-change-plugin/

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
