### ISSUE TITLE
nacos v2版本接口已经无配置监听，处于什么原因考虑

### ISSUE THREAD

**Issue by Wang-Jun-Chao** [alibaba/nacos#12849]
V1版本接口 https://nacos.io/docs/v1/open-api/
配置管理
[获取配置](https://nacos.io/docs/v1/open-api/#1.1)
[监听配置](https://nacos.io/docs/v1/open-api/#1.2)
[发布配置](https://nacos.io/docs/v1/open-api/#1.3)
[删除配置](https://nacos.io/docs/v1/open-api/#1.4)
[查询历史版本](https://nacos.io/docs/v1/open-api/#1.5)
[查询历史版本详情](https://nacos.io/docs/v1/open-api/#1.6)
[查询配置上一版本信息](https://nacos.io/docs/v1/open-api/#1.7)

V2版本接口 https://nacos.io/docs/v2/guide/user/open-api/
配置管理
[获取配置](https://nacos.io/docs/v2/guide/user/open-api/#1.1)
[发布配置](https://nacos.io/docs/v2/guide/user/open-api/#1.2)
[删除配置](https://nacos.io/docs/v2/guide/user/open-api/#1.3)
[查询配置历史版本列表](https://nacos.io/docs/v2/guide/user/open-api/#1.4)
[查询具体版本的历史配置](https://nacos.io/docs/v2/guide/user/open-api/#1.5)
[查询配置上一版本信息](https://nacos.io/docs/v2/guide/user/open-api/#1.6)
[查询指定命名空间下的配置列表](https://nacos.io/docs/v2/guide/user/open-api/#1.7)

**Comment by KomachiSion** [comment]
v2版本客户端监听配置是通过gprc协议实现的， http接口为admin或console接口， 所以不需要监听接口

**Comment by Wang-Jun-Chao** [comment]
对应的nacos-python-sdk没有对一下的功能

**Comment by KomachiSion** [comment]
nacos-python-sdk有监听配置的对应接口，不需要您自行调用订阅接口的配置。请升级nacos-python-sdk至新版本。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
