### ISSUE TITLE
In version 2.4.3 startup.sh cann't get right java path

### ISSUE THREAD

**Issue by duudo** [alibaba/nacos#12852]
**Describe the bug**
Deploy nacos version 2.4.3 in Kylin V10, if java exists in linux system env as linked, the startup.sh script can not get the link source path of java, this results in wrong value of -Djava.ext.dirs and user failed to login. Got the exception of "caused: No Such Algorithm: HmacSHA256"

**Expected behavior**
 if java exists in linux system env as linked, the startup.sh script can get the right link source path of java.

**Actually behavior**
User failed to login. Got the exception of "caused: No Such Algorithm: HmacSHA256"

**How to Reproduce**
1. Install jre in linux system Kylin V10 by yum install jre-8.
2. Deploy nacos 2.4.3 in Kylin V10.
3. Nacos server started successfully.
4. Login in console use user nacos, set password as nacos
5. Login use nacos/nacos, got wrong username and password.
6. check network response, got "No Such Algorithm: HmacSHA256"

**Desktop (please complete the following information):**
 - OS:  Kylin V10
 - Version nacos-server2.4.3
 - openjdk version "1.8.0_272"

**Comment by duudo** [comment]
startup.sh line   49-57, change to as following:

if [ -z "$JAVA_HOME" ]; then
        #JAVA_PATH=$(which java)
	JAVA_PATH=`dirname $(readlink -f $(which java))`
        if [ -z "$JAVA_PATH" ]; then
            error_exit "Please set the JAVA_HOME variable in your environment, We need java(x64)! jdk8 or later is better!"
        fi
        #JAVA_HOME=$(dirname "$JAVA_PATH")/..
        JAVA_HOME=$(dirname "$JAVA_PATH")/
        export JAVA_HOME=$(cd "$JAVA_HOME" && pwd)
  fi

**Comment by KomachiSion** [comment]
说明你的linux环境不支持hmacsha256 算法， 大概率与jdk版本有关，可参考 https://github.com/alibaba/nacos/issues/12097
