### ISSUE TITLE
使用  Dragonwell JDK 21 无法启动

### ISSUE THREAD

**Issue by WangJincheng4869** [alibaba/nacos#12857]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

![图片](https://github.com/user-attachments/assets/e8695ff2-3c63-4c07-9556-f27382d09ab3)

**Comment by KomachiSion** [comment]
`Please set java_home in your environment`

**Comment by WangJincheng4869** [comment]
> `Please set java_home in your environment`

其实我环境变量里配置了 `JAVA_HOME`，但是 nacos 就是读取不到。还有就在我将其注册为服务后也是同样读取不到，最后我是通过修改 `startup.sh` 解决的。

这个环境变量的问题经常遇到配置完程序无法读取的情况，哪位大神有更好的方法吗？最好不需要重启服务器。
