### ISSUE TITLE
spring cloud nacos持久化实例配置健康检查配置是否可以通过配置文件配置

### ISSUE THREAD

**Issue by hasaiki123** [alibaba/nacos#12863]
**Is your feature request related to a problem? Please describe.**
我正在使用spring cloud alibaba nacos，当我使用持久化实例时，我想使用http健康检查，但是我看网上资料是在web控制台对服务进行选择配置，如下：
![image](https://github.com/user-attachments/assets/cad091de-f259-4738-a0f8-ab42971dcc96)

然后我看到官方sdk有如下代码：
Cluster cluster = new Cluster();
cluster.setName("TEST5");
AbstractHealthChecker.Http healthChecker = new AbstractHealthChecker.Http();
healthChecker.setExpectedResponseCode(400);
healthChecker.setCurlHost("USer-Agent|Nacos");
healthChecker.setCurlPath("/xxx.html");
cluster.setHealthChecker(healthChecker);

我想知道的是，请问在使用spring cloud alibaba nacos时，是否可以通过配置文件设置持久化实例的健康检查方式为http，像spring cloud consul这样：
![image](https://github.com/user-attachments/assets/4a9ae412-94e4-4a79-9d07-8d0f4a47ddd0)
从而替代再去web console进行手动配置。

**Describe the solution you'd like**

使用spring cloud alibaba nacos时可以支持通过配置文件配置http健康检查。

**Comment by KomachiSion** [comment]
Nacos 3.0有规划 maintainer client，类似现在client中的MaintainerNamingService。

另外Nacos3.0也有规划将健康检查和 服务类型解耦的功能。

至于希望通过spring cloud的配置来开启和设置， 建议提交issue到spring cloud alibaba 社区
