### ISSUE TITLE
nacos 服务端版本为1.4.6，关于权限管理的需求

### ISSUE THREAD

**Issue by wsw136** [alibaba/nacos#12868]
nacos namespace都是用默认的public的，在nacos权限管理中，a，b，c用户的账号登录仅可以进行配置修改，d的账号是给应用与nacos连接使用 ,  我这边测试过这些用户在nacos授权都需要有rw授权才可以 ，那abc的账号能够与d的账号有办法隔离开吗 ？ 据说可以使用用户组进行隔离，但要如何开启这个功能吗

**Comment by KomachiSion** [comment]
可以给d账号单独授予另一角色，那个角色只绑定读权限即可

**Comment by wsw136** [comment]
> 可以给d账号单独授予另一角色，那个角色只绑定读权限即可

![ee07186e-81b2-45e8-9455-ff8cf21741eb](https://github.com/user-attachments/assets/4c63a544-8a9f-4771-822a-685ece76974c)
这个就是只读权限的应用账号启动报403权限不足的错误了

**Comment by KomachiSion** [comment]
因为你程序还想写数据（服务） 所以提示403，这种情况你必须是读写权限

**Comment by KomachiSion** [comment]
你可以生成2个用户，一个给只读权限，给config使用，一个给读写权限，给discovery使用，且把config的namespace和naming的namespace分开，两个用户授予不同命名空间的不同权限。

**Comment by wsw136** [comment]
> 你可以生成2个用户，一个给只读权限，给config使用，一个给读写权限，给discovery使用，且把config的namespace和naming的namespace分开，两个用户授予不同命名空间的不同权限。

只读权限不满足呀，我的title下正文的需求都写得比较清晰了

**Comment by wsw136** [comment]
> 你可以生成2个用户，一个给只读权限，给config使用，一个给读写权限，给discovery使用，且把config的namespace和naming的namespace分开，两个用户授予不同命名空间的不同权限。

那不同的命名空间如何做到配置自动同步

**Comment by KomachiSion** [comment]
为什么要在不同的命名空间中做同步？ 如果是需要的场景， 说明这两个配置就是同一个配置， 应该放在同一个命名空间下。

**Comment by wsw136** [comment]
> 为什么要在不同的命名空间中做同步？ 如果是需要的场景， 说明这两个配置就是同一个配置， 应该放在同一个命名空间下。

应用启动的配置和config下的配置是一样的，但也想将应用启动账号和config账号权限进行隔离

**Comment by wsw136** [comment]
> 为什么要在不同的命名空间中做同步？ 如果是需要的场景， 说明这两个配置就是同一个配置， 应该放在同一个命名空间下。

应用启动的配置和config下的配置是一样的，但也想将应用启动账号和config账号权限进行隔离

**Comment by KomachiSion** [comment]
> > 为什么要在不同的命名空间中做同步？ 如果是需要的场景， 说明这两个配置就是同一个配置， 应该放在同一个命名空间下。
> 
> 应用启动的配置和config下的配置是一样的，但也想将应用启动账号和config账号权限进行隔离

抱歉 完全没有看懂。。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.

**Comment by wsw136** [comment]
> > > 为什么要在不同的命名空间中做同步？ 如果是需要的场景， 说明这两个配置就是同一个配置， 应该放在同一个命名空间下。
> > 
> > 
> > 应用启动的配置和config下的配置是一样的，但也想将应用启动账号和config账号权限进行隔离
> 
> 抱歉 完全没有看懂。。

 多谢了，我这边已经暂时没有问题了，希望nacos应用在人员权限管理方面做得更精细化。
