### ISSUE TITLE
Feature request:Supports synchronization of the same dataId data in different namespace

### ISSUE THREAD

**Issue by stanvl** [alibaba/nacos#1287]
1、Support for registration services based on hostname
2、Nacos-sync supports synchronization of data between different nacos clusters according to namespace and dataId
3、Supports synchronization of the same dataId data in different namespace

**Comment by KeRan213539** [comment]
i will solve it

**Comment by nkorange** [comment]
The 1st and the 3rd feature are finished.

**Comment by KeRan213539** [comment]
### 关于第二个需求:
#### 在 nacos-sync 项目中增加配制同步功能:
同步功能单向,指定某节点(集群)为源,指定某些节点(集群)为目标,源的配制修改后,向目标同步(源覆盖目标)
* 指定namespace,同步整个namespace
* 指定单个配制(namespace和dataId),同步指定的配制

**Comment by KomachiSion** [comment]
second request please move to `nacos-sync` project
