### ISSUE TITLE
Nacos [配置中心]  缓存不一致，Config dump的时候，通过时间戳判断是否是旧数据不合理

### ISSUE THREAD

**Issue by dongyun-coder** [alibaba/nacos#12879]
**问题描述**
1. nacos 配置中心不同节点出现了缓存不一致
2. 原因描述

ConfigCacheService 在更新dump的逻辑 (最新代码）
如果时间戳小于当前值，拒绝此次dump
  ```
 //check timestamp
            boolean lastModifiedOutDated = lastModifiedTs < ConfigCacheService.getLastModifiedTs(groupKey);
            if (lastModifiedOutDated) {
                DUMP_LOG.warn("[dump-ignore] timestamp is outdated,groupKey={}", groupKey);
                return true;
            }
```

生产上出现了日志，导致最新的变更, 没有成功更新缓存
![image](https://github.com/user-attachments/assets/4d4cfb61-0801-4c1e-aabd-34f28fcf3dd9)

3. 问题

这里用时间戳预期是避免旧数据的覆盖，可能是考虑到 集群内部同步的一些retry任务（retry任务时间戳可能比较旧），但是没有什么道理！
- dump 单线程的，都是从db拉取的最新的数据，不存在覆盖的问题，永远都是最新的数据
- 这个时间戳在短时间如果高频写入，会出现丢失更新的问题。
   这里举一个反例，比如 t1\t2 针对同一个dataid修改两次，t1<t2,但是因为gc等原因，t2先执行的 update db,  并且完成集群内部广播，成功执行完dump，t1 此时刚刚执行update db 成功，磁盘缓存就会导致最后一个更新丢失。

**Comment by KomachiSion** [comment]
我影响中这个lastModified时间是由数据库自动生成的， 所以应该不存在并发写时， 旧时间戳覆盖新时间戳的问题。如果我记错了请纠正。

dump的触发有几个不同的触发点， 比较常见的时配置变更时的主动dump，和定时进行的全量对账dump， 这两种dump是处于不同的线程进行，所以问题1：`dump 单线程的，都是从db拉取的最新的数据，不存在覆盖的问题，永远都是最新的数据` 可能不一定对。

**Comment by KomachiSion** [comment]
@shiyiyue1102 帮忙确认一下

**Comment by Sunrisea** [comment]
使用的服务端是什么版本的

**Comment by MatthewAden** [comment]
更新配置时候的 lastModified 是数据库自动生成的
![image](https://github.com/user-attachments/assets/1ef45884-2da8-4d9e-a870-5112b0556e7f)

**Comment by dongyun-coder** [comment]
我使用的是2.1.1 的版本，这个版本里面 数据库的时间 并非数据库生成的时间

> 进行

> 我影响中这个lastModified时间是由数据库自动生成的， 所以应该不存在并发写时， 旧时间戳覆盖新时间戳的问题。如果我记错了请纠正。
> 
> dump的触发有几个不同的触发点， 比较常见的时配置变更时的主动dump，和定时进行的全量对账dump， 这两种dump是处于不同的线程进行，所以问题1：`dump 单线程的，都是从db拉取的最新的数据，不存在覆盖的问题，永远都是最新的数据` 可能不一定对。

对，我忽略了 全量dump的场景

**Comment by dongyun-coder** [comment]
> 更新配置时候的 lastModified 是数据库自动生成的 ![image](https://private-user-images.githubusercontent.com/70270642/389243843-1ef45884-2da8-4d9e-a870-5112b0556e7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDEzODMsIm5iZiI6MTczMjUwMTA4MywicGF0aCI6Ii83MDI3MDY0Mi8zODkyNDM4NDMtMWVmNDU4ODQtMmRhOC00ZDllLWE4NzAtNTExMmIwNTU2ZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YTQxZThjNjdkMzQxNjAxNmE3MWEyNzllOWMzZDZmMjJjZTAwMmY2YTExZjIxNTg1OGNiMmZlNGZlNmMwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZQA3s3G_QtoA6XF-OYBt74nsN4_GIPJ9EAry5EnrLvM)

我使用的是2.1.1 的版本

**Comment by Bo-Qiu** [comment]
> > 更新配置时候的 lastModified 是数据库自动生成的 ![image](https://private-user-images.githubusercontent.com/70270642/389243843-1ef45884-2da8-4d9e-a870-5112b0556e7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDEzODMsIm5iZiI6MTczMjUwMTA4MywicGF0aCI6Ii83MDI3MDY0Mi8zODkyNDM4NDMtMWVmNDU4ODQtMmRhOC00ZDllLWE4NzAtNTExMmIwNTU2ZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YTQxZThjNjdkMzQxNjAxNmE3MWEyNzllOWMzZDZmMjJjZTAwMmY2YTExZjIxNTg1OGNiMmZlNGZlNmMwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZQA3s3G_QtoA6XF-OYBt74nsN4_GIPJ9EAry5EnrLvM)
> 
> 我使用的是2.1.1 的版本，看上去升级就可以解决了？

是的，新版本已修复，改为使用数据库自动生成的时间戳

**Comment by dongyun-coder** [comment]
> > > 更新配置时候的 lastModified 是数据库自动生成的 ![image](https://private-user-images.githubusercontent.com/70270642/389243843-1ef45884-2da8-4d9e-a870-5112b0556e7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDEzODMsIm5iZiI6MTczMjUwMTA4MywicGF0aCI6Ii83MDI3MDY0Mi8zODkyNDM4NDMtMWVmNDU4ODQtMmRhOC00ZDllLWE4NzAtNTExMmIwNTU2ZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4YTQxZThjNjdkMzQxNjAxNmE3MWEyNzllOWMzZDZmMjJjZTAwMmY2YTExZjIxNTg1OGNiMmZlNGZlNmMwNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZQA3s3G_QtoA6XF-OYBt74nsN4_GIPJ9EAry5EnrLvM)
> > 
> > 
> > 我使用的是2.1.1 的版本，看上去升级就可以解决了？
> 
> 是的，新版本已修复，改为使用数据库自动生成的时间戳

好的。

**Comment by shiyiyue1102** [comment]
在2.3.0+版本已经修复该问题，见 https://github.com/alibaba/nacos/pull/10533
