### ISSUE TITLE
The Nacos server load is high

### ISSUE THREAD

**Issue by jointigers** [alibaba/nacos#12882]
![nacos-2](https://github.com/user-attachments/assets/a667b46a-3423-45e6-a37a-98ec5ec5e153)

## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
The Nacos server's system load tends to increase approximately every seven days and then drops back down.The number of configs and services has not changed.

nacos server每隔几天cpu利用率会高一下，然后又降下去。config和service数量没有变化

### Anything else we need to know?
![nacos-2](https://github.com/user-attachments/assets/87da355f-b0ff-4969-b95a-774b1ade3035)

**Comment by KomachiSion** [comment]
我的多数环境都无法复现此问题， 

可以在load，cpu使用率较高时，通过抓取cpu火焰图分析一下，哪些地方耗费了较高的cpu

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce and the information is not enough.
