### ISSUE TITLE
CVE Critical issue in Nacos 2.3.2

### ISSUE THREAD

**Issue by leoxhj** [alibaba/nacos#12897]
Hello team,

We have been reported by our security team that nacos has some `CVE Critical` issue detected, the security issue is `priority-zero` for us, so we're asked to fix them ASAP, do you have any plan to fix the CVE issue, I attached 3 jar files which we were reported.

![image](https://github.com/user-attachments/assets/1ecce342-f12e-4890-a0ea-6716739a2d8e)

**Comment by KomachiSion** [comment]
fixed in new version, please upgrade to latest version.

**Comment by leoxhj** [comment]
> fixed in new version, please upgrade to latest version.

Thanks @KomachiSion for your prompt response, may I know from which version since 2.3.2 are fixed those jar CVE issues as today we have no plan yet to upgrade to latest due to some conflict may caused to our applications. thanks

**Comment by KomachiSion** [comment]
check out 2.3.2 tag, do fixes and compile by yourself to use. Upgrade mysql jdbc is no effect I think, but upgrade spring component you should do some test before your deploy prod env.
