### ISSUE TITLE
注册到nacos中的微服务ip变动后，如何在不重启为服务端的情况下，微服务间的访问依旧可用

### ISSUE THREAD

**Issue by lwx314781** [alibaba/nacos#12899]
项目使用中遇到这种情况，整个微服务启动后，使用没问题，但是将部署该服务的笔记本拿到其它地方后，也就是IP发生变化后，发现无法正常使用，发现原来是注册到nacos中的ip还是之前未变换前的，所以导致无法访问。
  
可以实现，当微服务的ip发生变化时，向nacos重新注册服务吗，还是说目前就有这种方式，需要如何配置呢

**Comment by KomachiSion** [comment]
这和你的程序有关，一般应用程序只会在启动时获取一次本地ip，并调用nacos的api进行注册。

如果您有这方面的使用场景，那么需要您自行编写一个监听本机ip变化的逻辑，然后自行调用api进行注册注销。

nacos-client并不会获取本机ip进行自行注册， 一般是应用框架或应用程序自身编写的代码发起的
