### ISSUE TITLE
Whether SpringBoot3 is supported

### ISSUE THREAD

**Issue by tangyongfu** [alibaba/nacos#12893]
SpringBoot2.7.18 has been discontinued, and there are vulnerabilities, can you consider supporting SpringBoot3?

**Comment by shiyiyue1102** [comment]
supporting SpringBoot3 is in developing，may be released in nacos 3.0， youou can follow the follow-up updates

**Comment by tangyongfu** [comment]
您好，我已收到您的邮件，有时间再回复您。
