### ISSUE TITLE
jasypt对nacos配置信息加密失败

### ISSUE THREAD

**Issue by chenjunwenhao** [alibaba/nacos#12898]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chenjunwenhao** [comment]
使用nacos做注册中心和配置中心，只能写到bootstrap.yml中。jasypt对application加密可以，bootstrap加密失败

**Comment by fuxiuzhan** [comment]
准确来说nacos作为配置中心的时候是扩展propertySourceLocator扩展点，把远端的配置拉取加入到本地的environment中。jasypt是在容器启动的时候对env中的propertySource做代理，容器在获取变量的时候jasypt检测到value是特定格式如：ENC（。。。）就进行解密操作返回解密后的内容。这两个独立工作，互不影响。或者你的问题再详细一点，贴出演示内容。

**Comment by shiyiyue1102** [comment]
推荐使用nacos的加解密插件机制实现配置加解密，对上层使用方(Spring Cloud Alibaba) 无感，https://nacos.io/zh-cn/docs/v2/plugin/config-encryption-plugin.html

**Comment by KomachiSion** [comment]
总感觉这个issue应该提交给jasypt吧， 如果对bootstrap.yml无法加密， 那么其他的spring cloud的配置中心大概率也不行

**Comment by chenjunwenhao** [comment]
问题描述：
由于使用的nacos配置中心，先通过nacos的连接信息去连接nacos拉取配置信息。
jasypt是在建立nacos连接之后解密的，所以刚开始建立nacos连接是没有解密的。
问题解决：
使用spring的EnvriomentPostProcessor，生命周期是在nacos建立连接之前。
通过EnvriomentPostProcessor对envrionment进行解密并重新赋值，问题解决。
总结：
执行顺序的原因。
是应该提到jasypt，对这种拉取配置中心的应该都不支持。
通过spring的EnvriomentPostProcessor解决。

**Comment by KomachiSion** [comment]
> 问题描述： 由于使用的nacos配置中心，先通过nacos的连接信息去连接nacos拉取配置信息。 jasypt是在建立nacos连接之后解密的，所以刚开始建立nacos连接是没有解密的。 问题解决： 使用spring的EnvriomentPostProcessor，生命周期是在nacos建立连接之前。 通过EnvriomentPostProcessor对envrionment进行解密并重新赋值，问题解决。 总结： 执行顺序的原因。 是应该提到jasypt，对这种拉取配置中心的应该都不支持。 通过spring的EnvriomentPostProcessor解决。

这个顺序是spring cloud决定的， cloud本身抽象的逻辑中就需要从远端配置中心获取配置，并加入到PropertiesSource的责任链中，因此在读取完本地配置之后，就会直接去读取远端配置中心获取配置，这时候肯定要建立连接。等待全部配置读取完成，jasypt才被调用的话，那么配置肯定不会进行解密生效。

这方面的问题起始应该是jasypt对于spring cloud的适配不够准确，不能涵盖到所有配置场景导致的。

既然问题解决了，可以留给后续类似问题的同学一个参考
