### ISSUE TITLE
Nacos 服务可以注册上，但是读取不到配置文件 V2.4.3 版本

### ISSUE THREAD

**Issue by xiaojiewhisper** [alibaba/nacos#12908]
Nacos版本为2.4.3 ，jdk版本17 
Springboot版本为3.3.5 
spring-cloud 2023.0.3
spring.cloud.alibaba.version  2023.0.1.3

本人配置如下

![image](https://github.com/user-attachments/assets/1c24c4bf-9ff5-4d5d-8451-c2081c552917)

配置文件如下
![image](https://github.com/user-attachments/assets/668ef0e4-7ac3-4239-b5a3-d36997a4c101)

配置文件内容
![image](https://github.com/user-attachments/assets/e2b78c43-14ca-4bbb-8604-88dad2d2ef39)

**Comment by znbtczy** [comment]
我也是能成功注册服务，读取不到配置，你的问题解决了吗
