### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config:2023.0.1.3 NacosConfigAutoConfiguration is not eligible for getting processed by all BeanPostProcessors

### ISSUE THREAD

**Issue by RainStarMorn** [alibaba/nacos#12902]
**Describe the bug**
配置中心启动警告
![image](https://github.com/user-attachments/assets/861c84c7-02cb-4190-a79b-45f4630182ac)
![image](https://github.com/user-attachments/assets/4f947807-704a-45b8-8299-b1940f1a4360)

**Actually behavior**
引入spring-cloud-starter-alibaba-nacos-config:2023.0.1.3启动项目后，打印了警告日志，项目正常启动，但配置中心不生效。切换至2023.0.1.2版本后此警告不再出现，配置中心正常启动。

**How to Reproduce**
新建Springboot项目引入下述依赖
`dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'

    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2023.0.1.3'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2023.0.1.3'
}`
启动项目后复现。版本及具体环境在下方

**Desktop:**
 - OS: Windows10 
 - JDK: 21
 - Version:
     - Spring Cloud Alibaba 2023.0.1.3
     - Spring Cloud 2023.0.1
     - Spring Boot 3.2.4
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos-config:2023.0.1.3]

**Comment by KomachiSion** [comment]
Please submit issue to Spring Cloud Alibaba community.
