### ISSUE TITLE
最新的nacos版本(2023.0.1.3)支持spring cloud gateway mvc 模式吗

### ISSUE THREAD

**Issue by J-v-o-i-a-l** [alibaba/nacos#12900]
最新的nacos版本(2023.0.1.3)支持spring cloud gateway mvc 模式吗?
我从官网没看到有升级说明之类的

**Comment by KomachiSion** [comment]
nacos本身的升级和spring cloud并无关系， 一般来说是兼容的，因为API并没有变化， 建议转移issue到spring cloud alibaba 社区咨询一下。

**Comment by J-v-o-i-a-l** [comment]
感谢
