### ISSUE TITLE
The official website example failed to run

### ISSUE THREAD

**Issue by liucyu** [alibaba/nacos#1291]
## 步骤
- 本地按照官网教程搭建好nacos
- 新建springcloud项目，pom文件来自[nacos-spring-cloud-example/](https://github.com/nacos-group/nacos-examples/blob/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example/pom.xml)
- 按照官网给的步骤依次配置[Nacos-config](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config)
# 结果
拿不到配置，但是如果按照纯Java方式却能获取到配置

`bootstrap.properties`:

`spring.application.name=nacos-config`
`spring.cloud.nacos.config.server-addr=127.0.0.1:8848`

![image](https://user-images.githubusercontent.com/13191643/58543814-bfd69e80-8232-11e9-9937-e876befd1cb0.png)
日志
`2019-05-29 16:44:12.704  INFO 65456 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='nacos-config.properties'}]}`

代码
![image](https://user-images.githubusercontent.com/13191643/58544175-5b680f00-8233-11e9-8158-ca34e341524c.png)

结果
![image](https://user-images.githubusercontent.com/13191643/58544055-252a8f80-8233-11e9-834c-9f7627b0fac4.png)

**Comment by nkorange** [comment]
如果是nacos-client没问题，但是spring-cloud-nacos有问题，请到[spring cloud alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba)提交issue。

**Comment by liucyu** [comment]
@nkorange 我的springboot版本是2.1.4.RELEASE   springcloud版本是 Greenwich.SR1

**Comment by nkorange** [comment]
请到[spring cloud alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba)提交issue。
