### ISSUE TITLE
我们使用NACOS 2.3.1，外置mysql数据库，有条sql qps值异常的高，相对于当前其他业务

### ISSUE THREAD

**Issue by Jinshi-yue** [alibaba/nacos#12918]
我们使用NACOS 2.3.1，外置mysql数据库，有条sql qps值异常的高，5~7qps/s，相对于当前其他业务异常的高：
SELECT
  username,
  password
FROM
  users
WHERE
  username = 'nacos'；
并且我们用户表中没有nacos这个用户，我们想确认一下，是否某些版本的 Nacos 或其插件可能在认证过程中固定尝试 nacos 用户导致，否则这可能是外部一直在尝试恶意攻击

**Comment by KomachiSion** [comment]
没有哪个版本会默认使用nacos用户尝试，但是如果应用在初始化nacos-client的时候配置了这个user，那么就会尝试login这个用户。

建议排查一下所有应用配置，或者抓包看一下username=nacos的请求的来源，分析一下是由内部应用配置错误导致的还是真的有外部恶意攻击，然后进行对应的处理。

**Comment by Jinshi-yue** [comment]
好的，非常感谢
