### ISSUE TITLE
[optimize] config history comparison and rollback function optimize

### ISSUE THREAD

**Issue by shiyiyue1102** [alibaba/nacos#12925]
**Is your feature request related to a problem? Please describe.**
current config history page .

![image](https://github.com/user-attachments/assets/4158048b-dbad-4be9-bbde-608c4337fb9b)

current config history page .

![image](https://github.com/user-attachments/assets/4324d902-d51e-4115-a85e-709b7b5adea9)

click detail ，what for the Content ？what for the md5？is it the original version or updated version for that time?

![image](https://github.com/user-attachments/assets/398c0ccf-17c0-4687-8806-85c412d4270b)

click rollback ，what for the Content ？what for the md5？we should rollback to the original version or updated version for that time?

it‘s not very clear. we want to optimize it.

**Describe the solution you'd like**
detail history page 
show the original version and updated version for the history detail
create a new api ，getHistoryDetail contains old value and new value 
rollback page
show the original version and updated version for the history detail ,and provide two-version rollback 

show more explicit information and make  operations more explicit 

Is anyone interested in contributing to  this issue？

**Comment by DirtyBit64** [comment]
`@i will solve it@`

**Comment by DirtyBit64** [comment]
May I ask if the original version refers to the previous version of this version? For example, in the sequence v0->v1->v2, when a user views the history details of v1, should it display v0 | v1 or v1 | v2?

**Comment by shiyiyue1102** [comment]
> May I ask if the original version refers to the previous version of this version? For example, in the sequence v0->v1->v2->v3, when a user views the history details of v2, should it display v1 + v2 or v2 + v3?

time1：   insert v0 ,  detail  shows :  old-empty new-v0
time2：  change v0 -> v1 ,  detail shows :  old-v0 new-v1
times:     change v1->v2 ,  detail  shows :  old-v1 new-v2
times:     change v2->v3 ,  detail  shows :  old-v2 new-v3
time4:    delete  v3 ,  detail  shows :  old-v3 new-empty

**Comment by DirtyBit64** [comment]
> > May I ask if the original version refers to the previous version of this version? For example, in the sequence v0->v1->v2->v3, when a user views the history details of v2, should it display v1 + v2 or v2 + v3?
> 
> time1： insert v0 , detail shows : old-empty new-v0 time2： change v0 -> v1 , detail shows : old-v0 new-v1 time3: change v1->v2 , detail shows : old-v1 new-v2 time4: change v2->v3 , detail shows : old-v2 new-v3 time5: delete v3 , detail shows : old-v3 new-empty

OK, I understand. I think the API implementation method can be as follows: click on the details page of a historical configuration, js calls the API to pass the unique nid of the historical configuration to the backend, the backend finds the historical configuration and processes it differently according to different operation types, and the returned DTO has newMd5 and newContent compared to the previously returned ConfigInfo. If this is what you want to achieve, I can try to solve it.

**Comment by shiyiyue1102** [comment]
> returned

ok， expect your pr.
