### ISSUE TITLE
问题： 在控制台点击节点下线，没有下线成功，也没有报错

### ISSUE THREAD

**Issue by waymen** [alibaba/nacos#12924]
版本: 2.2.1
部署方式: 3节点nacos集群在k8s集群上运行
访问方式: ingress nginx 

问题：控制台点击节点下线，没有报错，但是节点还是提示UP。不知道有没有下线成功

<img width="770" alt="image" src="https://github.com/user-attachments/assets/4ea78b60-fdf4-4f09-8820-53117499045c">

刷新一下，还是显示UP
<img width="713" alt="image" src="https://github.com/user-attachments/assets/090ed931-4c36-4d29-997f-952ab43a035c">

**Comment by KomachiSion** [comment]
该接口已经暂停支持：

#9155

**Comment by waymen** [comment]
> 该接口已经暂停支持：
> 
> #9155

谢谢老师
