### ISSUE TITLE
【问题】 Nacos2.x 集群模式下，服务订阅推送

### ISSUE THREAD

**Issue by ningObito** [alibaba/nacos#12936]
有个问题咨询下，就是Nacos集群模式下，有3台nacos节点，其中服务A的一个实例注册到Nacos节点1上，且与Nacos节点1建立grpc连接。服务B订阅了服务A, 假设服务B也有一个实例注册到Nacos节点2上，且与Nacos节点2建立grpc连接。那么服务A的这个注册实例（Nacos节点1上）发生变化的时候，是如何通过Nacos节点2的grpc连接通知服务B的呢？ 
![image](https://github.com/user-attachments/assets/a6698091-d742-4252-b501-4566000e2d7b)

代码是service发生变化，会通知所有这个service的订阅者实例，然后就到了上述的代码，可是在集群模式下，这个connectionManager中里面会有所有实例的连接么？这里不是很理解。希望能解答。谢谢

**Comment by 985492783** [comment]
基于distro，最终一致的将结果广播到各个节点

**Comment by ningObito** [comment]
@985492783  但是我看这个connectionManager的代码里是用一个Map存的connecitions，且只有注册的时候才会往这个connections的map里存入。 所以不是很理解。而且grpc连接，如果需要往某个订阅者推送消息，是不是一定要找到这个订阅者连接的nacos节点才能推送呀

**Comment by 985492783** [comment]
订阅是1对1，但是请求是某个节点处理完后扩散到所有节点，a节点的变更推送到其他节点，其他节点广播到所有订阅者

**Comment by ningObito** [comment]
@985492783  谢谢解答
