### ISSUE TITLE
The release package contains a low version of the hession package, causing a vulnerability scan exception

### ISSUE THREAD

**Issue by wzqiang1332** [alibaba/nacos#12937]
**Describe the bug**
The release package contains a low version of the hession package, causing a vulnerability scan exception

![36d8bb80256bf7a2d5d3eec2e43f1af](https://github.com/user-attachments/assets/524b0c0f-7d01-4a80-a8bf-c563aac12d8b)
![image](https://github.com/user-attachments/assets/306bf449-5a81-4976-a900-d8b75d871da1)

**Expected behavior**
Remove the hession package dependency from 3.3.6

**Actually behavior**
The release package contains a low version of the hession package, causing a vulnerability scan exception

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version 2.4.3
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
duplicate with #11963
