### ISSUE TITLE
> 您好，我是在校学生，去年也参加过summer2021并成功结题。我想问下此issue中的感知K8S的服务上下线信息，是指的用户选择Nacos中的服务，然后通过api-server的接口来查询这些服务元数据吗？谢谢您的回答。

### ISSUE THREAD

**Issue by Sussmann1368** [alibaba/nacos#12938]
> 您好，我是在校学生，去年也参加过summer2021并成功结题。我想问下此issue中的感知K8S的服务上下线信息，是指的用户选择Nacos中的服务，然后通过api-server的接口来查询这些服务元数据吗？谢谢您的回答。

可以通过开源之夏官网联系对应的导师沟通

_Originally posted by @li-xiao-shuang in https://github.com/alibaba/nacos/issues/8309#issuecomment-1124508099_

**Comment by 985492783** [comment]
应该是通过watch apiserver pod annotation来感知服务上下线

**Comment by KomachiSion** [comment]
是将k8s的服务数据同步到nacos中，通过nacos-client和api查询 nacos和k8s中的服务的对应数据和元数据。

**Comment by KomachiSion** [comment]
后续可能会实现双向的同步和查询。
