### ISSUE TITLE
Nacos 2.3.2 can't  upload configuration file in zip way

### ISSUE THREAD

**Issue by matrix-ops** [alibaba/nacos#12939]
## Issue Description
In Nacos 2.2.3, I can use the follow command  upload my configuration file to Nacos(Alibaba Cloud MSE):
```shell
curl --request POST 'http://mse-4fb93e46-nacos-ans.mse.aliyuncs.com:8848/nacos/v1/cs/configs?import=true&namespace=public' \
--form 'policy=OVERWRITE' \
--form 'file=@"DEFAULT_GROUP.zip"'
```
But in Nacos 2.3.2(This is Alibaba Cloud MSE current version), That command return:
```shell
{"code":100005,"message":"导入的文件数据为空","data":{}}
```

I don't know whant happening，Maybe someone can help me understand that is why，I would be very very grateful.

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by matrix-ops** [comment]
I'm pretty sure i can use the same command upload configuration zip file to nacos 2.2.3(a instance created in 2 month ago )，but in nacos 2.3.2 it keep return code 100005.

**Comment by KomachiSion** [comment]
Please submit tickets to MSE.
