### ISSUE TITLE
nacos tag 0.2.0 problem

### ISSUE THREAD

**Issue by fengjianjun1** [alibaba/nacos#1293]
when i config the nacos conf
![图片](https://user-images.githubusercontent.com/16314792/58549670-94f24780-823e-11e9-88e2-e64f3d0f392c.png)
and then started 
![图片](https://user-images.githubusercontent.com/16314792/58549839-003c1980-823f-11e9-800c-b6003fbef433.png)
the port is difference.  and i can't  open then 127.0.0.1:8848/nacos/index.html  or 127.0.0.1:8080/nacos/index.html   
![图片](https://user-images.githubusercontent.com/16314792/58549917-3083b800-823f-11e9-91c0-6ea0306b9ae3.png)

**Comment by nkorange** [comment]
Nacos 0.2.0 is too old. We suggest you upgrade to the latest version 1.0.0.

**Comment by fengjianjun1** [comment]
@nkorange  thank you . I have been already switched to the 1.0.0.  it works well
