### ISSUE TITLE
nacos单机下的数据，在集群中无效。

### ISSUE THREAD

**Issue by tm2018** [alibaba/nacos#12945]
nacos版本：2.4.3  
jdk版本：openjdk17

背景：
交付类项目，需要在本地将数据配置好，部署到客户环境；之前的版本我都是在本地启动单机nacos，修改好密码后，导入正确的配置，然后复制到客户环境（客户环境可能单机部署，也可能集群部署）

现象：
1.若目标环境是单机，启动nacos后账号密码和配置与我本地配置正确无误
2.若目标环境是集群，启动nacos后提示需要**_初始化_**账号，和预期（密码已经修改/配置已经导入）不符合

PS:之前2.3、2.3.2、2.4.2.1版本，单机环境下的数据，在集群模式下依旧正常，2.4.3后，集群下数据无效。

**Comment by KomachiSion** [comment]
集群模式和单机模式不互通， 若你本地部署的单机模式， 复制之后只能以单机模式启动。

因为单机模式启动时，有一些关于数据同步的内容不会被启用，比如raft数据同步，可能会导致变更数据不可用。

**Comment by KomachiSion** [comment]
这个不是2.4.3版本才有这个问题， 是整个nacos从1.0～目前版本都具有的逻辑。

**Comment by tm2018** [comment]
> 这个不是2.4.3版本才有这个问题， 是整个nacos从1.0～目前版本都具有的逻辑。

好吧，2.3.2版本都能这样操作，那我还是老老实实的调接口去添加数据吧。
