### ISSUE TITLE
How does nacos achieve the same application for multiple machines to read different configurations?

### ISSUE THREAD

**Issue by nimil** [alibaba/nacos#1294]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
Please provide more details, i.e. background, current problem and feature requirement.

**Comment by nimil** [comment]
同一个服务集群下的不同机器读到的配置不一样，eg:机器A运行A应用需要读取配置A，机器B也运行A应用需要读取配置A，如何让机器A读到的A配置和机器B读到的B配置不一样，而其他配置项相同呢

**Comment by nkorange** [comment]
> 同一个服务集群下的不同机器读到的配置不一样，eg:机器A运行A应用需要读取配置A，机器B也运行A应用需要读取配置A，如何让机器A读到的A配置和机器B读到的A配置不一样，而其他配置项机器A和机器B相同呢

使用场景是什么？

**Comment by nkorange** [comment]
如果你指的是灰度配置，可以关注 #504
