### ISSUE TITLE
不同区域服务器，用内网注册到nacos，请问有什么解决方案可以互相调用呢

### ISSUE THREAD

**Issue by dt7-wcf** [alibaba/nacos#12958]
环境 nacos 2.1.1 + dubbo

由于业务需要，nacos和A微服务同一个云服务地区，B微服务在另一云服务地区

目前是都注册上来了，但是由于是内网注册的，服务间不能互相调用，有什么方案吗

**Comment by KomachiSion** [comment]
这个似乎和nacos没什么关系，主要在于网络环境的打通。。

如果无法通过内网的ip或域名调用， 可以考虑注册公网地址。

或者两个地区通过一个东西向网关暴露， 向各自区域的nacos中注册对端网关的域名或地址。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
