### ISSUE TITLE
2.3.2 upgrade to 2.4.2 API incompatibility causes Seata 2.0 to fail to start.

### ISSUE THREAD

**Issue by lpqoang** [alibaba/nacos#12963]
2.3.2 upgrade to 2.4.2 API incompatibility causes Seata 2.0 to fail to start.

**Comment by KomachiSion** [comment]
which API? I have no idea 2.4 change API responses.

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
