### ISSUE TITLE
Configuration key with Norway country code ("NO") is incorrectly interpreted as "false"

### ISSUE THREAD

**Issue by jason-liu475** [alibaba/nacos#12969]
**Describe the bug**
When defining a configuration key using the country code "NO" (e.g., country=NO), it is incorrectly parsed or interpreted as the boolean value false. This issue causes unexpected behavior, especially when working with international configurations that involve country codes.
![image](https://github.com/user-attachments/assets/e7123360-b24a-48f2-95c7-c911affd25f0)

**Expected behavior**
The value should be returned as "NO" (a string), matching the value defined in the configuration file.

**Actually behavior**
The value is interpreted as false (a boolean), which is incorrect.
![image](https://github.com/user-attachments/assets/433501b6-151e-48e7-b6a2-7e09d4722cb4)

**How to Reproduce**
1. Add the following key-value pair to a Nacos configuration file:
 `area:
  available:
        NO:
      code: NO
      name: 挪威
      binary: 67108864`
2. 
@Configuration
@RefreshScope
@ConfigurationProperties(prefix = "area")
public class AreaAvailableProperties {
  private Map<String,AreaAvailable> available = new HashMap<>();
}

**Environment:**
Nacos version: 2.1.2.RELEASE
Java version : 1.8
Configuration format: [.yaml]

**Additional context**
This issue might be caused by the automatic type inference or a misinterpretation of the value. Since "NO" is a valid string and not a boolean keyword, it should not be treated as such.

**Comment by butflame** [comment]
Actually I think it's the feature of `yaml`, it could be reproduced with a local file `application.yaml`, it's not a issue with nacos.
I didn't dig in that much, but found some similar discussions, FYI:
https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started#booleans
https://github.com/spring-projects/spring-boot/issues/9186

In your case I think it could be solved with single quote like below:
```yaml
  code: 'NO'
```

**Comment by butflame** [comment]
Official reference found:
https://yaml.org/type/bool.html
https://yaml.org/spec/1.2.2/#10212-boolean

**Comment by KomachiSion** [comment]
nacos don't parse configuration context, only use it as text or string,

actual parsing configuration as yaml is application.

I don't know which structure you used, if you use spring boot or spring cloud, the config parsing is spring framework todo.

If you use other structure or parsing config by yourself, please make sure the config can be parsed by yaml or your application.
