### ISSUE TITLE
nacos 3.0 版本修改配置提交后会跑到另外一个命名空间下

### ISSUE THREAD

**Issue by menghuan** [alibaba/nacos#12972]
在本地测试 nacos 3.0版本 控制台配置列表  修改某命名空间下的配置提交后会到另外一个 public 命名空间下(后者命名空间是最新的内容，前者命名空间没有新增的内容)。后者指的是public命名空间，前者是我新加的

操作过程可以参照这个视频

https://github.com/user-attachments/assets/39ee3620-004d-4aa4-aa15-f3a09107e347

**Comment by MatthewAden** [comment]
能复现这个问题，发布配置时，前端发送的参数字段名为“tenant”，而在后端中，原先版本使用的是“tenant”来进行映射处理。然而，在升级到3.0版本后，后端改为使用“namespaceId”字段。由于这一变更，后端未能正确接收到前端发送的“tenant”字段值，导致后端默认将配置修改应用到了“public”命名空间，从而引发了这个问题。

**Comment by MatthewAden** [comment]
![image](https://github.com/user-attachments/assets/3fd28aec-329d-497b-9b47-1729af3c6f10)
![image](https://github.com/user-attachments/assets/cc79e8e1-cb9f-4e3a-a8ae-9b0c6bc0a076)
![image](https://github.com/user-attachments/assets/cb5a9324-c18e-4f40-af4c-d7ef96a38ec5)

**Comment by misakacoder** [comment]
后端接口返回的tenant字段，发布配置的时候直接原封不动提交上去了，发布接口又不是用的这个字段去接收

**Comment by menghuan** [comment]
谢谢，那最后用哪个版本可以测试下这个问题？
