### ISSUE TITLE
Fix NamingMetadataManager.removeInstanceMetadata() error 

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#12970]
![1734508653153_C39C95BD-5FE2-4584-A3F7-4E8A9D1AC102](https://github.com/user-attachments/assets/09885051-2b64-47b9-ab0c-3a690968b177)

**Comment by leopornorecio** [comment]
A

**Comment by Dario-s-j** [comment]
Ok

Em qua., 1 de jan. de 2025, 00:06, Leoporno ***@***.***>
escreveu:
