### ISSUE TITLE
The size of the serviceMap is 0.

### ISSUE THREAD

**Issue by ouyangzhiming** [alibaba/nacos#1298]
DomainsManager

 public Domain getDomain(String namespaceId, String domName) {
        if (serviceMap.get(namespaceId) == null) {
            return null;
        }
        return chooseDomMap(namespaceId).get(domName);
    }

serviceMap的size 为0 啊 大哥，这个serviceMap啥时候初始化的
用的是nacos-all 0.8.0

**Comment by nkorange** [comment]
没有服务的时候size为0
