### ISSUE TITLE
在集群模式下，服务频繁打印 received push data日志的问题

### ISSUE THREAD

**Issue by zhiqiang94** [alibaba/nacos#12986]
这是一个重复的bug提交，由于上一个 [#8030](https://github.com/alibaba/nacos/issues/8030) issue被关闭，所以在此提问。
This is a duplicate bug submission， [#8030]（https://github.com/alibaba/nacos/issues/8030）The issue has been closed, so I am asking this question.

我遇到了#8030相同的问题。
I encountered the same issue as # 8030.

![Snipaste_2024-12-24_11-33-30](https://github.com/user-attachments/assets/c88519f8-26ea-44da-87b1-3b5badf6b76d)
![Snipaste_2024-12-24_11-34-06](https://github.com/user-attachments/assets/48a8208f-5a18-4ceb-8165-9e9e2c6ce568)
![Snipaste_2024-12-24_11-32-29](https://github.com/user-attachments/assets/8cfbf7d8-6aa0-46d8-bbc1-bb77d4cf5fff)

我通过修改日志级别的方式隐藏了日志，但总感觉这种方法不科学，应该找到根本原因才行
I hid the logs by modifying the log level, but I always feel that this method is not scientific and the root cause should be identified

```
logging:
  level:
    com.alibaba.nacos.client.naming: warn
```

补充一下流程：
服务 -> 域名 -> nginx -> 负载均衡（多个nacos节点） 

Supplement the process:
Service -> Domain -> nginx -> Load balancing (multiple nacos nodes)

**Comment by zhiqiang94** [comment]
在线翻译，如果用词不准确，请见谅！

**Comment by bwangll** [comment]
日志全一些，看看是俩条数据哪个字段不一样，同时naming-server.log看一下，排查思路和https://github.com/alibaba/nacos/issues/8030 一样啊

**Comment by zhiqiang94** [comment]
只有lastRefTime不一样
```
[INFO ] [2024-12-24 11:17:58] [com.alibaba.nacos.naming.push.receiver] [c.a.n.c.n.c.PushReceiver:86] - received push data: {"type":"dom","data":"{\"name\":\"DEFAULT_GROUP@@xxxxxx\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[],\"lastRefTime\":1735010278912,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":8587068008525119} from /127.0.0.1
[INFO ] [2024-12-24 11:18:10] [com.alibaba.nacos.naming.push.receiver] [c.a.n.c.n.c.PushReceiver:86] - received push data: {"type":"dom","data":"{\"name\":\"DEFAULT_GROUP@@xxxxxx\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[],\"lastRefTime\":1735010290920,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":8587080016938900} from /127.0.0.1

```

naming-server.log

```
2024-12-23 13:55:00,221 INFO Client connection 127.0.0.1:34476#true disconnect, remove instances and subscribers

2024-12-23 13:55:20,221 INFO Client connection 127.0.0.1:58306#true disconnect, remove instances and subscribers

2024-12-23 13:55:50,222 INFO Client connection 127.0.0.1:46651#true disconnect, remove instances and subscribers

2024-12-23 13:55:57,290 INFO Client connection 127.0.0.1:58306#true connect

2024-12-23 13:56:30,222 INFO Client connection 127.0.0.1:58306#true disconnect, remove instances and subscribers

2024-12-23 13:57:07,351 INFO Client connection 127.0.0.1:58306#true connect

2024-12-23 13:57:16,876 INFO Client connection 127.0.0.1:46651#true connect

2024-12-23 13:57:40,224 INFO Client connection 127.0.0.1:58306#true disconnect, remove instances and subscribers

2024-12-23 13:58:30,225 INFO Client connection 127.0.0.1:46651#true disconnect, remove instances and subscribers

2024-12-23 13:58:36,898 INFO Client connection 127.0.0.1:46651#true connect
```

**Comment by bwangll** [comment]
hosts里的节点列表中的metadata对比一下，如果也一样，看看服务提供者是不是一直在重复注册

**Comment by bwangll** [comment]
> 只有lastRefTime不一样
> 
> ```
> [INFO ] [2024-12-24 11:17:58] [com.alibaba.nacos.naming.push.receiver] [c.a.n.c.n.c.PushReceiver:86] - received push data: {"type":"dom","data":"{\"name\":\"DEFAULT_GROUP@@xxxxxx\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[],\"lastRefTime\":1735010278912,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":8587068008525119} from /127.0.0.1
> [INFO ] [2024-12-24 11:18:10] [com.alibaba.nacos.naming.push.receiver] [c.a.n.c.n.c.PushReceiver:86] - received push data: {"type":"dom","data":"{\"name\":\"DEFAULT_GROUP@@xxxxxx\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[],\"lastRefTime\":1735010290920,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":8587080016938900} from /127.0.0.1
> ```
> 
> naming-server.log
> 
> ```
> 2024-12-23 13:55:00,221 INFO Client connection 127.0.0.1:34476#true disconnect, remove instances and subscribers
> 
> 2024-12-23 13:55:20,221 INFO Client connection 127.0.0.1:58306#true disconnect, remove instances and subscribers
> 
> 2024-12-23 13:55:50,222 INFO Client connection 127.0.0.1:46651#true disconnect, remove instances and subscribers
> 
> 2024-12-23 13:55:57,290 INFO Client connection 127.0.0.1:58306#true connect
> 
> 2024-12-23 13:56:30,222 INFO Client connection 127.0.0.1:58306#true disconnect, remove instances and subscribers
> 
> 2024-12-23 13:57:07,351 INFO Client connection 127.0.0.1:58306#true connect
> 
> 2024-12-23 13:57:16,876 INFO Client connection 127.0.0.1:46651#true connect
> 
> 2024-12-23 13:57:40,224 INFO Client connection 127.0.0.1:58306#true disconnect, remove instances and subscribers
> 
> 2024-12-23 13:58:30,225 INFO Client connection 127.0.0.1:46651#true disconnect, remove instances and subscribers
> 
> 2024-12-23 13:58:36,898 INFO Client connection 127.0.0.1:46651#true connect
> ```
> 
> @bwangll 已补充相关信息 请教一下 我应该如何去排查这个问题？

naming-server.log和客户端的日志要对应，一般就是服务提供者一直刷，主要有2种情况：
1、服务注册一直在注册，断开，又注册，日志表现为connect，然后disconnect，这样客户端会收到的列表中节点数会变。
2、服务提供者更新元数据，日志表现为 Client change for service Service{XXX}，需要细看metadata是否有细微的变化，可以用文本对比工具对比一下
同时可以看看对应时间的naming-push.log日志，服务端是否推送了俩次，而且 revision的值是不一样的，这个就是用来确定俩次推送是因为服务提供者变更导致的。
这种问题一般都是服务提供者导致的。

**Comment by zhiqiang94** [comment]
```
spring:
  cloud:
    nacos:
      discovery:
        # 配置元数据
        metadata:
          # 心跳间隔。时间单位:毫秒。
          preserved.heart.beat.interval: 1000
          # 心跳暂停。时间单位:毫秒。 即服务端3秒收不到客户端心跳，会将该客户端注册的实例设为不健康；
          preserved.heart.beat.timeout: 3000
          # Ip删除超时。时间单位:秒。即服务端6秒收不到客户端心跳，会将该客户端注册的实例删除；
          preserved.ip.delete.timeout: 6000
```
感谢大佬，你说的服务一直在注册。我就看了一下服务配置的metadata，之前因为想服务快速上下线，添加了这个配置，我刚尝试注释掉这部分的配置，现在已经好了。

再请教一下，我这部分的配置怎样配 才是在一个合理的范围

@bwangll

**Comment by bwangll** [comment]
用默认值就行

**Comment by zhiqiang94** [comment]
@bwangll  感谢大佬专业的解答，帮我排查出了问题所在。

**Comment by bwangll** [comment]
> ```
> spring:
>   cloud:
>     nacos:
>       discovery:
>         # 配置元数据
>         metadata:
>           # 心跳间隔。时间单位:毫秒。
>           preserved.heart.beat.interval: 1000
>           # 心跳暂停。时间单位:毫秒。 即服务端3秒收不到客户端心跳，会将该客户端注册的实例设为不健康；
>           preserved.heart.beat.timeout: 3000
>           # Ip删除超时。时间单位:秒。即服务端6秒收不到客户端心跳，会将该客户端注册的实例删除；
>           preserved.ip.delete.timeout: 6000
> ```
> 
> 感谢大佬，你说的服务一直在注册。我就看了一下服务配置的metadata，之前因为想服务快速上下线，添加了这个配置，我刚尝试注释掉这部分的配置，现在已经好了。
> 
> 再请教一下，我这部分的配置怎样配 才是在一个合理的范围
> 
> @bwangll

刚看了一下spring-clouod-starter-alibaba-nacos-discovery的源码，使用的nacos-client是2.2.0版本，使用的grpc方式完成的服务注册，这几个参数是给nacos-client 1.x的注册方式使用的，感觉是存在问题的，不要加这几个参数，去掉就好。nacos 2.x的注册方式使用的是grpc，连接在服务就是注册成功的，连接断了，服务就是下线了。不需要关心这几个参数。

设置了有影响的原因还需要进一步看源码，感觉是一个bug。

**Comment by zhiqiang94** [comment]
> > ```
> > spring:
> >   cloud:
> >     nacos:
> >       discovery:
> >         # 配置元数据
> >         metadata:
> >           # 心跳间隔。时间单位:毫秒。
> >           preserved.heart.beat.interval: 1000
> >           # 心跳暂停。时间单位:毫秒。 即服务端3秒收不到客户端心跳，会将该客户端注册的实例设为不健康；
> >           preserved.heart.beat.timeout: 3000
> >           # Ip删除超时。时间单位:秒。即服务端6秒收不到客户端心跳，会将该客户端注册的实例删除；
> >           preserved.ip.delete.timeout: 6000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 感谢大佬，你说的服务一直在注册。我就看了一下服务配置的metadata，之前因为想服务快速上下线，添加了这个配置，我刚尝试注释掉这部分的配置，现在已经好了。
> > 再请教一下，我这部分的配置怎样配 才是在一个合理的范围
> > @bwangll
> 
> 刚看了一下spring-clouod-starter-alibaba-nacos-discovery的源码，使用的nacos-client是2.2.0版本，使用的grpc方式完成的服务注册，这几个参数是给nacos-client 1.x的注册方式使用的，感觉是存在问题的，不要加这几个参数，去掉就好。nacos 2.x的注册方式使用的是grpc，连接在服务就是注册成功的，连接断了，服务就是下线了。不需要关心这几个参数。
> 
> 设置了有影响的原因还需要进一步看源码，感觉是一个bug。

![Snipaste_2024-12-31_15-51-10](https://github.com/user-attachments/assets/bd025057-a6ff-4b7a-8b85-2a0c6e984e14)

![Snipaste_2024-12-31_15-49-18](https://github.com/user-attachments/assets/ad337b60-dbda-4fde-9c3d-e926672c9382)

在我删除配置之后，同一个服务器上的两个不同的服务，出现了很奇怪的问题，一个服务偶尔会重新注册但不频繁（启动5小时，出现了2次），但是另一个服务还是会频繁的重新注册（没之前那么夸张 但是还是很多） 两个服务中的元数据配置都已经删除掉了

**Comment by bwangll** [comment]
看一下naming-server的日志，是否频繁断开连接了。

**Comment by zhiqiang94** [comment]
> 看一下naming-server的日志，是否频繁断开连接了。

![Snipaste_2025-01-02_09-48-25](https://github.com/user-attachments/assets/604db6cb-a82c-4b5c-a75c-1e2a5a92562e)
很奇怪，并没有。在上一次删除配置之后naming-server.log就没有相关日志输出了

**Comment by Dario-s-j** [comment]
Ok

Em qua., 1 de jan. de 2025, 22:51, zhiqiang ***@***.***>
escreveu:
