### ISSUE TITLE
【漏洞】我们内部安全团队发现 nacos 一些漏洞，社区有修改意向吗

### ISSUE THREAD

**Issue by luky116** [alibaba/nacos#12980]
**Describe the bug**

我们内部使用了社区版的 Nacos，安全团队扫描代码反馈了一些潜在的问题，如果社区有意向修改，我们可以设计方案并把代码提交上来。问题如下：
1、问题1：
代码位置：com.alibaba.nacos.config.server.controller.ConfigOpsController#derbyOps
潜在问题：将y用户传入的 SQL 直接执行，可能会有安全风险：

![image](https://github.com/user-attachments/assets/8ef1ce54-d6ce-4953-b904-ad55c84106d3)

2、问题2：
代码位置：com.alibaba.nacos.config.server.controller.ConfigServletInner
潜在问题：从用户传入的 header 获取的数据，不经过校验、特殊格式去除就直接使用，可能有安全线风险
![image](https://github.com/user-attachments/assets/b0736bb5-9b1f-4cb5-9d81-c83ab3b80800)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by luky116** [comment]
内部检测有点严格，看看社区觉得是否有必要修改

**Comment by KomachiSion** [comment]
您反馈的两个问题，都已经修复了，可以升级到最新版本后重试。

**Comment by KomachiSion** [comment]
https://nacos.io/blog/release-240/?spm=5238cd80.2ef5001f.0.0.3f613b7cbSJvGV&source=blog

**Comment by KomachiSion** [comment]
https://nacos.io/blog/announcement-derby-ops-api/?spm=5238cd80.2ef5001f.0.0.3f613b7cbSJvGV&source=blog

**Comment by luky116** [comment]
收到，感谢
