### ISSUE TITLE
On the same host, multiple dubbo clients are registered, and there is only one service list instance.

### ISSUE THREAD

**Issue by greatle** [alibaba/nacos#1299]
nacos1.0， 在同一个主机上，同时启动多个dubbo客户端，启动成功后，nacos服务列表中的实例数只有一个

**Comment by greatle** [comment]
补充说明：多个dubbo客户端指同一个客户端实现的多个实例

**Comment by nkorange** [comment]
怎么配置的dubbo？

**Comment by greatle** [comment]
dubbo的xml主要配置信息为：
    <dubbo:application name="remote-client-test"  />
    <dubbo:registry address="nacos://192.168.1.126:8848" />   
    <dubbo:consumer timeout="60000" />    
    <context:component-scan base-package="com.test.remote.client"/>
    <dubbo:reference id="remoteService" interface="com.test.remote.intf.RemoteCallService" check="true"  timeout="3000" mock="false"/>

另外dubbo和dubbo-registry-nacos版本都是2.7.1

**Comment by greatle** [comment]
应该是这里有问题：
类：com.alibaba.nacos.naming.core.ServiceManager
方法：public List<Instance> updateIpAddresses(Service service, String action, boolean ephemeral, Instance... ips) throws NacosException
该方法中：
    for (Instance instance : currentIPs) {
            map.put(instance.toIPAddr(), instance);
     }
因为dubbo客户端注册的时候port始终是0，因此同一个机器上同一实现的多个客户端实例会导致instance.toIPAddr()是同一个值，后面注册的把前面注册的覆盖了

**Comment by nkorange** [comment]
> 应该是这里有问题：
> 类：com.alibaba.nacos.naming.core.ServiceManager
> 方法：public List updateIpAddresses(Service service, String action, boolean ephemeral, Instance... ips) throws NacosException
> 该方法中：
> for (Instance instance : currentIPs) {
> map.put(instance.toIPAddr(), instance);
> }
> 因为dubbo客户端注册的时候port始终是0，因此同一个机器上同一实现的多个客户端实例会导致instance.toIPAddr()是同一个值，后面注册的把前面注册的覆盖了

Consumer这个地方是会覆盖的，因为端口是一样的。

**Comment by greatle** [comment]
> > 应该是这里有问题：
> > 类：com.alibaba.nacos.naming.core.ServiceManager
> > 方法：public List updateIpAddresses(Service service, String action, boolean ephemeral, Instance... ips) throws NacosException
> > 该方法中：
> > for (Instance instance : currentIPs) {
> > map.put(instance.toIPAddr(), instance);
> > }
> > 因为dubbo客户端注册的时候port始终是0，因此同一个机器上同一实现的多个客户端实例会导致instance.toIPAddr()是同一个值，后面注册的把前面注册的覆盖了
> 
> Consumer这个地方是会覆盖的，因为端口是一样的。但是其实不影响你的服务调用的，因为这个是consumer，不是provider

是不影响服务调用。只是在管理客户端服务的时候，没法管理。比如需要临时下线某个客户端服务，此时就不能正确选择了。

**Comment by nkorange** [comment]
> > > 应该是这里有问题：
> > > 类：com.alibaba.nacos.naming.core.ServiceManager
> > > 方法：public List updateIpAddresses(Service service, String action, boolean ephemeral, Instance... ips) throws NacosException
> > > 该方法中：
> > > for (Instance instance : currentIPs) {
> > > map.put(instance.toIPAddr(), instance);
> > > }
> > > 因为dubbo客户端注册的时候port始终是0，因此同一个机器上同一实现的多个客户端实例会导致instance.toIPAddr()是同一个值，后面注册的把前面注册的覆盖了
> > 
> > 
> > Consumer这个地方是会覆盖的，因为端口是一样的。但是其实不影响你的服务调用的，因为这个是consumer，不是provider
> 
> 是不影响服务调用。只是在管理客户端服务的时候，没法管理。比如需要临时下线某个客户端服务，此时就不能正确选择了。

目前是这样的，Nacos通过IP和端口来判断实例的唯一性。这个估计只能Dubbo在设置消费者端口时使用另外的策略了。
