### ISSUE TITLE
2.5.0beta用standalone模式启动，默认使用的是mysql数据库吗，能否使用derby数据库。

### ISSUE THREAD

**Issue by WhaleFall1234** [alibaba/nacos#13003]
standalone模式启动，报 [db-load-error]load jdbc.properties error。  直接从git上下的2.5.0 beta的包，没改配置文件。
![c1ad71c52f11d6c24a0975cd36defc1](https://github.com/user-attachments/assets/1b73be6c-5c90-4a4d-aacc-f8879a450962)

**Comment by MatthewAden** [comment]
默认用的就是 derby 数据库

**Comment by WhaleFall1234** [comment]
> 默认用的就是 derby 数据库

对，之前也一直是这样的，但是我从git上下的2.5.0 beta的包，就只是把startup.cmd里的set MODE="cluster"修改为set MODE="standalone"。   我看2.4.3的包这样修改后启动也是没问题的，但是2.5.0就一直报上面的错误，我看到报错后面还有mysql连接的报错，是还有哪里需要修改吗

**Comment by misakacoder** [comment]
先在配置文件加一行配置吧
spring.sql.init.platform=derby

**Comment by WhaleFall1234** [comment]
> 先在配置文件加一行配置吧 spring.sql.init.platform=derby

ok，可以了，非常感谢

**Comment by WhaleFall1234** [comment]
配置文件添加spring.sql.init.platform=derby即可

**Comment by Dario-s-j** [comment]
Ok

Em ter., 31 de dez. de 2024, 02:19, WhaleFall ***@***.***>
escreveu:
