### ISSUE TITLE
I changed the source code to be empty, I can register the service, why, bug?

### ISSUE THREAD

**Issue by ouyangzhiming** [alibaba/nacos#1302]
public RaftPeer getLeader() {
        if (STANDALONE_MODE) {
            return local();
        }
        //oyzm
        **### if(null ==leader ){
            leader = new RaftPeer();
            //leader.ip = "192.168.200.238";
            leader.ip = "127.0.0.1";
        }**
        return leader;
    }

我改源码判断为空了，就能注册服务了，为啥啊，bug？
我改源码判断为空了，就能注册服务了，为啥啊，bug？
我改源码判断为空了，就能注册服务了，为啥啊，bug？
我改源码判断为空了，就能注册服务了，为啥啊，bug？

**Comment by nkorange** [comment]
和#1301 是一个问题？
