### ISSUE TITLE
nacosSync eureka sync to nacos, eureka can't sync to nacos with username and password

### ISSUE THREAD

**Issue by jackorjack** [alibaba/nacos#1305]
## nacosSync eureka sync to nacos, eureka can't sync to nacos with username and password, I hope to use username and password to sync

nacosSync eureka同步到nacos，eureka使用用户名和密码不能同步到nacos，希望使用用户名和密码也可以同步

**Comment by nkorange** [comment]
请到nacos-sync的仓库提一个issue
