### ISSUE TITLE
关于nacos控制台UI

### ISSUE THREAD

**Issue by zgqyfj** [alibaba/nacos#131]
在nacos的文档中提到,提供了一个 简单易用的UI TODO ,但是在当前版本(0.2.1)里并没有找到相关信息,请问一下相关功能的规划计划

**Comment by TenzeTseng** [comment]
在 0.3.0 分支中已经把UI实现了

**Comment by yanlinly** [comment]
0.3.0-RC1 has finished
demo env:
http://console.nacos.io/nacos/index.html

u can try to use it
