### ISSUE TITLE
Improve the configuration management function interface

### ISSUE THREAD

**Issue by glameyzhou** [alibaba/nacos#1313]
现在：控制台能看到当前dataId的文件下发情况，只能看到客户端的IP和对应的md5值。
缺陷：
1、下发情况界面只能看到MD5，还需要去配置界面对比下MD5，看是否一致。
2、如果同一个IP，部署同一个服务的多个应用，不能到是否全部都生效，因此界面只显示IP，无端口。
3、当前的模式是客户端通过长轮询来拉去最新的配置，如果我先推送一个最新配置到某一个节点（在某一些场景下做灰度），当前的架构应该是不支持。

针对以上三个问题，是否可以作为下个小版本的future。

**Comment by nkorange** [comment]
1和2会尽快支持，3会在 #504 里跟踪

**Comment by KomachiSion** [comment]
No one want to enhance 1 and 2 for a long time, and 3 has support. I think we can close issue first. If 1 and 2 has someone to do, should create new issue for each ehancemant
