### ISSUE TITLE
Nacos service management, modify service instance metadata is unsuccessful

### ISSUE THREAD

**Issue by greatle** [alibaba/nacos#1314]
1. 启动nacos服务
2. “服务管理”。—>"服务列表"，选择一个已经存在的注册服务 —> “详情”
3. 对选择的服务，“编辑”，修改任何一个元数据，然后“确定”提交，不能修改成功
提示“metadata format incorrect : method=xxx,xx.....”错误
后台应该需要的对metadata，后台应该需要的是json字符串，而前端传的metadata内容为非json字符串，且各个key/value值对也不是以“;”分割，而是以","分割的

**Comment by nkorange** [comment]
Will be tracked in #1354
