### ISSUE TITLE
nacos1.0 connecting mysql8.0

### ISSUE THREAD

**Issue by hmapleleaf** [alibaba/nacos#1315]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

![image](https://user-images.githubusercontent.com/45254909/58801760-0581d580-863e-11e9-88ac-094856aca8cc.png)

### Tell us your environment
windows

**Comment by fangkk0168** [comment]
Nacos.log The entire log file is submitted to help you analyze the error.

I also encountered the same error yesterday, the result is incorrectly filled in the mysql database name.

**Comment by Dhweicheng** [comment]
com.alibaba.nacos.naming.healthcheck.MysqlHealthCheckProcessor
//import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import com.mysql.cj.jdbc.MysqlDataSource;

**Comment by nkorange** [comment]
数据库配置贴一下

**Comment by liufangpu** [comment]
server.tomcat.basedir=

## spring security config
### turn off security
#spring.security.enabled=false
#management.security=false
#security.basic.enabled=false
#nacos.security.ignore.urls=/**

nacos.security.ignore.urls=/,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/login,/v1/console/health/**,/v1/cs/**,/v1/ns/**,/v1/cmdb/**,/actuator/**,/v1/console/server/**

nacos.naming.distro.taskDispatchThreadCount=1
nacos.naming.distro.taskDispatchPeriod=200
nacos.naming.distro.batchSyncKeyCount=1000
nacos.naming.distro.initDataRatio=0.9
nacos.naming.distro.syncRetryDelay=5000
nacos.naming.data.warmup=true
nacos.naming.expireInstance=true

spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://localhost:3306/nacos?serverTimezone=Asia/Shanghai&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

**Comment by liufangpu** [comment]
> server.tomcat.basedir =
> 
> ## 弹簧安全配置
> ### 关闭安全
> ＃spring.security.enabled = false 
> ＃management.security = false 
> ＃security.basic.enabled = false 
> #nacos.security.ignore.urls = / **
> 
> nacos.security.ignore.urls = /，/ **/*.css,/** / _的.js，/ ** /_ html的，/ **/*.map,/** / _.SVG，/ ** /_ .PNG，/ **/ *。 ico，/ console-fe / public /**，/ v1 / auth / login，/ v1 / console / health / **，/ v1 / cs /**，/ v1 / ns / **，/ v1 / cmdb /**，/ actuator / **，/ v1 /控制台/服务器/**
> 
> nacos.naming.distro.taskDispatchThreadCount = 1 
> nacos.naming.distro.taskDispatchPeriod = 200 
> nacos.naming.distro.batchSyncKeyCount = 1000 
> nacos.naming.distro.initDataRatio = 0.9 
> nacos.naming.distro.syncRetryDelay = 5000 
> nacos.naming.data .warmup = true 
> nacos.naming.expireInstance = true
> 
> spring.datasource.platform = mysql 
> db.num = 1 
> db.url.0 = jdbc：mysql：// localhost：3306 / nacos？serverTimezone = Asia / Shanghai＆characterEncoding = utf8＆connectTimeout = 1000＆socketTimeout = 3000＆autoReconnect = true 
> db.user = root 
> db。密码= 123456 
> spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

this is my config,but i can not start the nacos server

**Comment by liufangpu** [comment]
> > server.tomcat.basedir =
> > ## 弹簧安全配置
> > ### 关闭安全
> > ＃spring.security.enabled = false
> > ＃management.security = false
> > ＃security.basic.enabled = false
> > #nacos.security.ignore.urls = / **
> > nacos.security.ignore.urls = /，/ **/*.css,/** / _的.js，/ ** /_ html的，/ **/*.map,/** / _.SVG，/ ** /_ .PNG，/ **/ *。 ico，/ console-fe / public /**，/ v1 / auth / login，/ v1 / console / health / **，/ v1 / cs /**，/ v1 / ns / **，/ v1 / cmdb /**，/ actuator / **，/ v1 /控制台/服务器/**
> > nacos.naming.distro.taskDispatchThreadCount = 1
> > nacos.naming.distro.taskDispatchPeriod = 200
> > nacos.naming.distro.batchSyncKeyCount = 1000
> > nacos.naming.distro.initDataRatio = 0.9
> > nacos.naming.distro.syncRetryDelay = 5000
> > nacos.naming.data .warmup = true
> > nacos.naming.expireInstance = true
> > spring.datasource.platform = mysql
> > db.num = 1
> > db.url.0 = jdbc：mysql：// localhost：3306 / nacos？serverTimezone = Asia / Shanghai＆characterEncoding = utf8＆connectTimeout = 1000＆socketTimeout = 3000＆autoReconnect = true
> > db.user = root
> > db。密码= 123456
> > spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
> 
> this is my config,but i can not start the nacos server

The problem was solved!
i changed it to  spring.datasource.platform=mysql8

**Comment by liufangpu** [comment]
> server.tomcat.basedir=
> 
> ## spring security config
> ### turn off security
> #spring.security.enabled=false
> #management.security=false
> #security.basic.enabled=false
> #nacos.security.ignore.urls=/**
> 
> nacos.security.ignore.urls=/,/**/*.css,/**/_.js,/**/_.html,/**/*.map,/**/_.svg,/**/_.png,/**/*.ico,/console-fe/public/**,/v1/auth/login,/v1/console/health/**,/v1/cs/**,/v1/ns/**,/v1/cmdb/**,/actuator/**,/v1/console/server/**
> 
> nacos.naming.distro.taskDispatchThreadCount=1
> nacos.naming.distro.taskDispatchPeriod=200
> nacos.naming.distro.batchSyncKeyCount=1000
> nacos.naming.distro.initDataRatio=0.9
> nacos.naming.distro.syncRetryDelay=5000
> nacos.naming.data.warmup=true
> nacos.naming.expireInstance=true
> 
> spring.datasource.platform=mysql
> db.num=1
> db.url.0=jdbc:mysql://localhost:3306/nacos?serverTimezone=Asia/Shanghai&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
> db.user=root
> db.password=123456
> spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

The problem was solved!
i changed it to spring.datasource.platform=mysql8
