### ISSUE TITLE
Please remove the feature of config subscription triggered automatically after Nacos client started

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#1317]
Please remove the feature of config subscription triggered automatically after Nacos client started

Refer to code follows:
https://github.com/Nepxion/Discovery/blob/master/discovery-common-nacos/src/main/java/com/nepxion/discovery/common/nacos/operation/NacosOperation.java

Here I have tow configs : partial and global config, if they are are all set, my requirement is that got global finally. But the feature of subscription config automatically will cause it out-of-order.

Another issue i don't know why the same config will be triggered 2 times

Apollo works fine. I remember it also works fine in nacos 0.8 or 0.6 version

请帮忙移除Nacos客户端启动后，自动触发订阅事件

我现在有两个配置，一个是全局配置，一个是局部配置，（Key不同），如果它们都在Nacos上做了配置，那么优先取全局配置，但是因为存在自动触发订阅事件，而且触发次序是无序的（有时候先触发全局配置，再触发局部配置），那么会造成Nacos Client拿到局部配置。取消掉自动触发订阅事件的功能，由用户在启动的时候，自己去取。

除此之外，还有个问题，该自动触发的功能，会触发两次。

我测试过Apolllo，不存在这个问题

**Comment by nkorange** [comment]
后续会支持该功能

**Comment by HaojunRen** [comment]
请尽快支持，谢谢

**Comment by chuntaojun** [comment]
I will try to solve

**Comment by chuntaojun** [comment]
> 请尽快支持，谢谢

你好，我在看Apollo对于配置的Listener也是自动触发的，请问下使用Apollo是不存在监听器触发无序这个问题吗？

**Comment by HaojunRen** [comment]
我的意思是，第一次启动的时候，不应该去触发Listener，应该是由用户自己手工去获取。那么就不存在所谓的次序问题了，事实上，全局配置和局部配置，nacos上也无法判断出来。Apollo 上我测试过，不存在这个问题。

**Comment by chuntaojun** [comment]
> 我的意思是，第一次启动的时候，不应该去触发Listener，应该是由用户自己手工去获取。那么就不存在所谓的次序问题了，事实上，全局配置和局部配置，nacos上也无法判断出来。Apollo 上我测试过，不存在这个问题。

好的，理解了，

**Comment by HaojunRen** [comment]
如果你愿意我们可以在微信上交流，1394997
