### ISSUE TITLE
It can't input text in Nacos Web Console with Firefox sometimes

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#1318]
It can't input text in Nacos Web Console with Firefox sometimes

有时候在Nacos控制台页面上无法输入配置内容，我用的是Firefox浏览器，然后刷新一下页面又好了

**Comment by nkorange** [comment]
把错误内容贴一下

**Comment by HaojunRen** [comment]
没有错误，在Win10下，火狐浏览器有时候无法输入文本，也许还和输入法有关？

**Comment by nkorange** [comment]
我们这边无法复现这个问题
