### ISSUE TITLE
Can Nacos support query instances using keyword?

### ISSUE THREAD

**Issue by lexburner** [alibaba/nacos#1319]
Currently, Naocs support query services using the keyword, like this:
```
http://ip:8848/nacos/v1/ns/catalog/services?withInstances=false&pageNo=1&pageSize=10000000&keyword=providers:com.alibaba.middleware.sp.dubbo.samples.DemoApi&namespaceId=
```

in above API, the param `withInstances` decides the return result whether carry instances information, but in my test, the problem is that when I set `withInstances=true`, the `pageNo` and `keyword` will be ignored. This means Nacos only support query services without instances information using keywords, not support query services with instances information using keywords and pageable param

Can Nacos support thus query API? 
```
http://ip:8848/nacos/v1/ns/catalog/services?withInstances=true&pageNo=1&pageSize=10&keyword=providers:com.alibaba.middleware.sp.dubbo.samples.DemoApi&namespaceId=
```

**Comment by chuntaojun** [comment]
I will try to solve

**Comment by nkorange** [comment]
> I will try to solve

This is already done.
