### ISSUE TITLE
Use different properties instead of "nacos.home" 

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#132]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when considered about how to set the "nacos.home". The property is used as root path of conf , log and local data， while I need to set the dir individually in product mode

**Describe the solution you'd like**
Use different properties as root path of  conf , log and local data

**Describe alternatives you've considered**
Use “nacos.home” as default， and we can chage the root path of  conf , log and local data individually 

**Additional context**
some code，for example

com.alibaba.nacos.naming.misc.Loggers
`configurator.doConfigure(System.getProperty("nacos.home") + "/conf/nacos-logback.xml");`

com.alibaba.nacos.config.server.service.DiskUtil
`	static {
		String nacosDir = System.getProperty("nacos.home");
		if (!StringUtils.isBlank(nacosDir)) {
			APP_HOME = nacosDir;
		}
	}`

**Comment by xuechaos** [comment]
Yes, you can specify the specific value of nacos.home by modifying startup.sh.
