### ISSUE TITLE
kubectl create -f deploy/nfs/deployment.yaml

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1321]
`MountVolume.SetUp failed for volume "nfs-client-root" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/495f9f4f-695a-11e9-a037-52540036d517/volumes/kubernetes.io~nfs/nfs-client-root --scope -- mount -t nfs 172.17.79.3:/data/nfs-share /var/lib/kubelet/pods/495f9f4f-695a-11e9-a037-52540036d517/volumes/kubernetes.io~nfs/nfs-client-root Output: Running scope as unit run-10287.scope. mount: wrong fs type, bad option, bad superblock on 172.17.79.3:/data/nfs-share, missing codepage or helper program, or other error (for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program) In some cases useful info is found in syslog - try dmesg | tail or so.`

**Comment by paderlol** [comment]
你没有在nfs挂载这个共享目录吧

**Comment by 1346735074** [comment]
嗯？ 按照官方提供的文件默认执行的

**Comment by 1346735074** [comment]
@paderlol /data/nfs-share 这个共享目录已经在nfs挂载了
Export list for 10.1.1.99:
/data/nfs-share *

**Comment by paderlol** [comment]
172.17.79.3你的nfs不是这个地址吧，这个地址是我之前配置的server地址

**Comment by 1346735074** [comment]
@paderlol 已经改为了自己的10.1.1.99了

**Comment by 1346735074** [comment]
@paderlol 要执行mount 10.1.1.99:/data/nfs-share /kubernetes？

**Comment by paderlol** [comment]
你mount应该之前就执行过了，只是要配置nfs server地址改成自己就行了，我文档里面有说的，可能没写太清楚

**Comment by 1346735074** [comment]
@https://github.com/paderlol
嗯  执行showmount –a IP 可以看到/etc/exports文件里的内容  但是执行mount   抛了没有找到/data/nfs-share   Nfs不是很熟悉

**Comment by paderlol** [comment]
挂载完要重启下nfs的，我不记得具体命令了，你查一下😂

**Comment by 1346735074** [comment]
@paderlol 执行showmount -a 10.1.1.99
```
All mount points on 10.1.1.99:
10.1.1.97:/data/nfs-share
10.1.1.98:/data/nfs-share
10.1.1.99:/data/nfs-share
```
查看好像已经挂载了   k8s nfs还是这个错误

**Comment by 1346735074** [comment]
@paderlol 等了7分钟  报错莫名其妙消失了
![image](https://user-images.githubusercontent.com/36881032/58926266-2c92f100-877d-11e9-9c0e-3cc35a841252.png)

**Comment by paderlol** [comment]
看看nfs-share下面有创建文件夹吗？

**Comment by 1346735074** [comment]
@paderlol 目前k8s只部署了nfs  nfs-share里面0个文件

**Comment by paderlol** [comment]
那就是nfs没有配置成功，如果挂载成功下面会有响应的文件夹出现的，你可以检查下etc/export是否设置正确了，然后需要重启portmap 和nfs 最后执行下exportfs

**Comment by paderlol** [comment]
然后可以在客户端尝试用 showmount -e server地址看看是否成功

**Comment by 1346735074** [comment]
@paderlol showmount -e 10.1.1.99
```
Export list for 10.1.1.99:
/home/nfs       *
/data/nfs-share *
```
这个是成功 的

**Comment by paderlol** [comment]
close
