### ISSUE TITLE
Client access failed to get serverlist through endpoint

### ISSUE THREAD

**Issue by glameyzhou** [alibaba/nacos#1323]
目前通过配置endpoint的方式来访问nacos server，访问的接口地址是/nacos/serverlist，这个接口在源码中没有，并且格式也不符合/v1/之类的规范。
因此想确认下，接口/nacos/serverlist是否没有具体的实现。

**Comment by nkorange** [comment]
这个是地址服务器模式，可以参考[介绍文章](https://nacos.io/zh-cn/blog/address-server.html)。预计会在1.1.0实现

**Comment by glameyzhou** [comment]
> 这个是地址服务器模式，可以参考[介绍文章](https://nacos.io/zh-cn/blog/address-server.html)。预计会在1.1.0实现

好
