### ISSUE TITLE
Linux system deployment Nacos can not be started on a single machine

### ISSUE THREAD

**Issue by yenaikafei** [alibaba/nacos#1324]
## Issue Description

Linux system deployment Nacos can not be started to be single mode
system:ubuntu18.04
nacos:nacos-server-1.0.0.tar.gz
sh startup.sh -m standalone
report:cluster.conf not found
then:
cannot get serverlist, so exit

and Startup file report:

startup.sh: 77: startup.sh: [[: not found
startup.sh: 87: startup.sh: [[: not found
startup.sh: 89: startup.sh: [[: not found
startup.sh: 95: startup.sh: [[: not found

**Comment by gxf212** [comment]
@yenaikafei  The same as #1325 
The quick start should be updated.
Need use  'bash startup.sh -m standalone' to replace   'sh startup.sh -m standalone'

**Comment by yenaikafei** [comment]
got it, it works, thank you very much!
