### ISSUE TITLE
The quick start shoud be updated ,Otherwise nacos 1.0 cannot be started by standalone mode

### ISSUE THREAD

**Issue by gxf212** [alibaba/nacos#1325]
## Issue Description
Type: *bug report*
Desc:
I want to run nacos1.0.0CA by standalone mode, Follow the quick start. but failed.
Refer to [Quick start](https://nacos.io/zh-cn/docs/quick-start.html)
should use `sh startup.sh -m standalone`,    **in fact should update to  'bash  startup.sh -m standalone' **

### Describe what happened 
if we use  `sh startup.sh -m standalone` ,  The nacos run with cluster mode ,and failed
The error log as below:
```
root@instance-o70no2nw:/usr/local/cloud# cd nacos/bin
root@instance-o70no2nw:/usr/local/cloud/nacos/bin# sh startup.sh -m standalone
startup.sh: 78: startup.sh: [[: not found
root@instance-o70no2nw:/usr/local/cloud/nacos/bin# cat /usr/local/cloud/nacos/logs/start.out
Nacos 1.0.0  Running in cluster mode, All function modules
java.io.FileNotFoundException: /usr/local/cloud/nacos/conf/cluster.conf (No such file or directory)
2019-06-04 22:31:57,267 ERROR read cluster conf fail
```
### Describe what you expected to happen
Check the startup.sh, we can find:
`
if [[ "${MODE}" == "standalone" ]]; then
....
`
**Cause: The sh command does not recognize the "[[]]" expression**

### How to reproduce it (as minimally and precisely as possible)
1.  Use 'bash startup.sh -m standalone'
2.  Update the quick start

### Tell us your environment
Server:  Ubuntu 18.04.2 LTS x64
JDK: jdk1.8.0_211 x64
Nacos:  nacos-server-1.0.0

**Comment by kezhenxu94** [comment]
YES!! I've encountered this problem too, exactly

**Comment by yenaikafei** [comment]
Both suggestions are works!
