### ISSUE TITLE
Is NamingService and ConfigService thread safe？

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#133]
**Is your feature request related to a problem? Please describe.**
Is NamingService and ConfigService thread safe in the sdk? 

**Describe the solution you'd like**
What about adding annotion or comment

**Describe alternatives you've considered**

**Additional context**

**Comment by yanlinly** [comment]
more info, ok?

**Comment by nanamikon** [comment]
For example， in my spring project，should I register NamingService and ConfigService as a bean or build a new one with factory whenever uses it

**Comment by nkorange** [comment]
Nacos SDK is thread-safe. 
I think your comment is more likely related to whether Nacos SDK shares data between different SDK instances, and the answer is no.
