### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims (repeated 3 times)

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1330]
启动k8s nacos-pvc-nfs.yaml nfs-client-provisioner日志
`E0605 03:43:25.712382       1 leaderelection.go:234] error retrieving resource lock nacos/fuseim.pri-ifs: endpoints "fuseim.pri-ifs" is forbidden: User "system:serviceaccount:nacos:nfs-client-provisioner" cannot get resource "endpoints" in API group "" in the namespace "nacos"`

nacos0
`pod has unbound immediate PersistentVolumeClaims (repeated 3 times)`

**Comment by paderlol** [comment]
u can refer this PR [Add endpoints resource permissions into nfs-client-provisioner-runner](https://github.com/nacos-group/nacos-k8s/pull/36)
