### ISSUE TITLE
How to judge node fissure

### ISSUE THREAD

**Issue by vidytu** [alibaba/nacos#1331]
Our deployment mode is 3 nodes + 1 VIP .Recently, we found that services are constantly switching: online and offline. We found that there is a node brain fissure and all service is lost.
Is there a way to check the cleft of the node to facilitate the restart of the node?

**Comment by nkorange** [comment]
Does this happen for all services or just one service?

**Comment by vidytu** [comment]
just one

**Comment by vidytu** [comment]
all service not be found　on the Exception node
