### ISSUE TITLE
Nacos1.0, the Data Id of the configuration item contains special characters, such as ":", the value is not obtained.

### ISSUE THREAD

**Issue by greatle** [alibaba/nacos#1332]
window环境下
1. 单机版本，配置为mysql数据库，运行nacos1.0版本
2. 登陆nacos控制台，“配置列表”中新建立配置项，data id名字包含特殊字符如“:”，默认组，默认格式，任意设置配置内容，发布
3. 控制台中发布成功后，通过代理获取该配置项的值，获取值为null。获取值代码直接采用控制台页面中的“实例代码”的java代码

**Comment by nkorange** [comment]
你配置serverAddr了吗？

**Comment by greatle** [comment]
配置了serveraddr。
如果data id名字不包含特殊字符如“:”，是可以获取的，就是包含后不能获取。简单跟了下代码，是在windows系统下，根据id名字建本地文件的时候，由于“:”是否是特殊字符，在windows下不能建立对应的文件

**Comment by nkorange** [comment]
你的客户端版本是多少？

**Comment by greatle** [comment]
同服务端一样的版本1.0.0
