### ISSUE TITLE
Maybe nacos-beat can be better

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#1336]
目前的nacos的client主动心跳上报是定时上报，但是如果client本身和nacos-server之间的调用就很频繁，那么该链路基本是没问题的，不必要在这期间仍然进行心跳上报操作。我觉得可以参考dubbo的心跳设计

[Dubbo 现有心跳方案总结以及改进建议](http://dubbo.apache.org/zh-cn/blog/dubbo-heartbeat-design.html)

> 忙检测的对立面是空闲检测，我们做心跳的初衷，是为了保证连接的可用性，以保证及时采取断连，重连等措施。如果一条通道上有频繁的 RPC 调用正在进行，我们不应该为通道增加负担去发送心跳包

**Comment by nkorange** [comment]
是一个有可能的优化，可以具体说下你的方案吗？

**Comment by chuntaojun** [comment]
> 是一个有可能的优化，可以具体说下你的方案吗？

我这几天想想，顺便先看看dubbo是怎么做的，然后看看怎么结合nacos

**Comment by chuntaojun** [comment]
之前考虑了下，这个beat不能被优化，因为如果元数据被用于负载均衡的话，那么其实这个数据是需要定时去更新的
