### ISSUE TITLE
k8s nacos service leader problem

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1337]
k8s nacos service 投不出leader

naming-server.log
```2019-06-06 15:31:16,134 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos-0.nacos-headless.nacos.svc.cluster.local:8848```

naming-raft.log
```2019-06-06 15:34:30,000 WARN [IS LEADER] no leader is available now!```

**Comment by 1346735074** [comment]
`curl '$nacos_server:8848/nacos/v1/ns/operator/servers'`
nacos-0:`server is STARTING now, please try again later!`
nacos-1:`server is STARTING now, please try again later!`
nacos-2:`server is STARTING now, please try again later!`

**Comment by nkorange** [comment]
```nacos-0.nacos-headless.nacos.svc.cluster.local```这个在容器里能ping通吗？

**Comment by paderlol** [comment]
may be u can refer this [issue](https://github.com/nacos-group/nacos-k8s/issues/38)

**Comment by 1346735074** [comment]
@nkorange 这个可以ping通

**Comment by nkorange** [comment]
> @nkorange 这个可以ping通

看下 @paderlol 回复

**Comment by shaojielinux** [comment]
I have encountered this problem, how can I solve it?
