### ISSUE TITLE
macbook start nacos failure

### ISSUE THREAD

**Issue by Invincibled** [alibaba/nacos#1339]
## Issue Description

bug report

### Describe what happened (or what feature you want)

My macBookProc start bin/start.sh，it's failure

When I open the log file to view it, it seems that the local IP address was not found

### How to reproduce it (as minimally and precisely as possible)

1. download 1.0.0
2. ./start.sh 
3. 

### Tell us your environment
macOS moJave 10.14.5

**Comment by nkorange** [comment]
Paste detailed error please.
