### ISSUE TITLE
When I used nacos config that happen nacos client's config unable sync

### ISSUE THREAD

**Issue by rottenmu** [alibaba/nacos#1343]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by rottenmu** [comment]
![00](https://user-images.githubusercontent.com/49062403/59170402-0d2b0800-8b71-11e9-8a1f-df1cee82b672.jpg)
![01](https://user-images.githubusercontent.com/49062403/59170408-19af6080-8b71-11e9-83b9-6a0b3f6399a8.jpg)

**Comment by nkorange** [comment]
Paste detailed error please.
