### ISSUE TITLE
Problems encountered during service registration

### ISSUE THREAD

**Issue by kurohayan** [alibaba/nacos#1344]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([https://serviceone-test.xx.com:8]) tried: failed to req API:http://https://serviceone-test.xx.com:8/nacos/v1/ns/service/list. code:500 msg: java.net.UnknownHostException: https

### Describe what you expected to happen
Use spring.cloud.nacos.discovery.server-addr in yml environment to support https://
在yml环境下使用spring.cloud.nacos.discovery.server-addr  可以支持https://

### How to reproduce it (as minimally and precisely as possible)

1. 
spring:
  cloud:
    nacos:
      discovery:
        server-addr: https://serviceone-test.xx.com:80
2. 
3. 

### Tell us your environment
test

**Comment by nkorange** [comment]
![image](https://user-images.githubusercontent.com/4593375/59192085-ef32c700-8bb3-11e9-9714-79985cf07407.png)
Your server has an extra 'https://'

**Comment by kurohayan** [comment]
The server uses http:// to automatically jump to https://.. If you do not use https:// will return 302 redirects

**Comment by nkorange** [comment]
In your case, Did you configured your nginx with SSL configuration?

**Comment by kurohayan** [comment]
yes.Alibaba Cloud SLB

**Comment by nkorange** [comment]
From the error message, it seems you are visiting a corrupted URL
```
https://serviceone-test.xx.com:8
```

**Comment by kurohayan** [comment]
thanks

**Comment by rushsky518** [comment]
> thanks
-Dcom.alibaba.nacos.client.naming.tls.enable=true

application.properties:
spring.cloud.nacos.discovery.server-addr=serviceone-test.xx.com:80

这样不行吗？

**Comment by kurohayan** [comment]
> > thanks
> 
> -Dcom.alibaba.nacos.client.naming.tls.enable=true
> 
> application.properties:
> spring.cloud.nacos.discovery.server-addr=serviceone-test.xx.com:80
> 
> 这样不行吗？

 不行呢..因为使用了阿里的SLB,这样必定会触发http转https的配置..会直接导致302

**Comment by kurohayan** [comment]
> > > thanks
> > 
> > 
> > -Dcom.alibaba.nacos.client.naming.tls.enable=true
> > application.properties:
> > spring.cloud.nacos.discovery.server-addr=serviceone-test.xx.com:80
> > 这样不行吗？
> 
> 不行呢..因为使用了阿里的SLB,这样必定会触发http转https的配置..会直接导致302

使用ip是可以的..但由于我们服务器限制了大部分的port,进出只从两台服务器里走..所以公网是访问不到这台服务器的..缺点就是我们测试也是使用此方法..导致没法用测试服务器进行测试吧..现在我就是单独开了一台服务器进行的测试配置,感觉生产环境应该可能不会有这样的影响(不确定).因为可以走内网ip

**Comment by rushsky518** [comment]
> > > > thanks
> > > 
> > > 
> > > -Dcom.alibaba.nacos.client.naming.tls.enable=true
> > > application.properties:
> > > spring.cloud.nacos.discovery.server-addr=serviceone-test.xx.com:80
> > > 这样不行吗？
> > 
> > 
> > 不行呢..因为使用了阿里的SLB,这样必定会触发http转https的配置..会直接导致302
> 
> 使用ip是可以的..但由于我们服务器限制了大部分的port,进出只从两台服务器里走..所以公网是访问不到这台服务器的..缺点就是我们测试也是使用此方法..导致没法用测试服务器进行测试吧..现在我就是单独开了一台服务器进行的测试配置,感觉生产环境应该可能不会有这样的影响(不确定).因为可以走内网ip

方便加个钉钉吗

**Comment by kurohayan** [comment]
> > > > > thanks
> > > > 
> > > > 
> > > > -Dcom.alibaba.nacos.client.naming.tls.enable=true
> > > > application.properties:
> > > > spring.cloud.nacos.discovery.server-addr=serviceone-test.xx.com:80
> > > > 这样不行吗？
> > > 
> > > 
> > > 不行呢..因为使用了阿里的SLB,这样必定会触发http转https的配置..会直接导致302
> > 
> > 
> > 使用ip是可以的..但由于我们服务器限制了大部分的port,进出只从两台服务器里走..所以公网是访问不到这台服务器的..缺点就是我们测试也是使用此方法..导致没法用测试服务器进行测试吧..现在我就是单独开了一台服务器进行的测试配置,感觉生产环境应该可能不会有这样的影响(不确定).因为可以走内网ip
> 
> 方便加个钉钉吗

好的, 我的钉钉号:samtofor

**Comment by rushsky518** [comment]
-Dcom.alibaba.nacos.client.naming.tls.enable=true
application.properties:
spring.cloud.nacos.discovery.server-addr=serviceone-test.xx.com:443

**Comment by kurohayan** [comment]
> OK, I understand now. HTTPS will be supported soon. Thanks to your advice.

发现一个新的问题.就是nacos-config同样不支持https.其代码中直接写死boolean isSSL = false;默认不使用ssl,并且没在之后进行赋值.
还有之前的问题.应该是有两种改法一种是增加一个properties来支持ssl,一种是直接支持这样的无法spring.cloud.nacos.discovery.server-addr=https://1.2.3.4:443 (http://1.2.3.4:80)(1.2.3.4:80)这几种形式,
