### ISSUE TITLE
Whether to support the startup phase injection configuration, such as the scenario using @ConditionalOnProperty or some configuration that spring-boot-starter needs to read during the startup phase.

### ISSUE THREAD

**Issue by joewee** [alibaba/nacos#1347]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
是否支持启动阶段注入配置，比如使用@ConditionalOnProperty的场景或者是一些spring-boot-starter在启动阶段就需要读取的配置

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
hi，请到[nacos-spring-boot](https://github.com/nacos-group/nacos-spring-boot-project)发布这个问题。
