### ISSUE TITLE
The database is configured and the configured database content is not used

### ISSUE THREAD

**Issue by wangkebin1990** [alibaba/nacos#1348]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos1.0 版本,在application.properties已配置数据库内容，配置如下：
spring.datasource.platform=mysql 
db.num=1
db.url.0=jdbc:mysql://192.168.0.7:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=nacos
db.password=nacos

因系统为迁移,数据库中的config_info已有信息,但nacos配置数据库后，正常启动，使用原来的配置的用户无法登陆，只能使用默认的用户nacos登陆,且看不到任何的配置信息

### Tell us your environment
1. 版本1.0最新发布版本
2. 数据库使用的MariaDB最新版本10.4.5
3. 操作系统win10

**Comment by nkorange** [comment]
数据库中已有config_info信息指的什么？之前也是Nacos吗？

**Comment by wangkebin1990** [comment]
是的 问题已经解决了，具体原因不得而知，我在
spring.datasource.platform=mysql
db.num=1 两行之间增加一个空白行就可以了。谢谢！
