### ISSUE TITLE
A few questions about the log:

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#1349]
1. 设计不优雅，nacos既然是框架，在我看来，就不应该考虑日志的事情，日志让开发自己配置就可以了。我估计这可能是因为nacos是来源于configserver/diamond，集团是这么玩的，所以nacos也这么玩了。
2. 日志级别怎么自定义，目录怎么自定义，文件名称怎么自定义，文档没有，得自己看代码，找到对应属性。spring cloud alibaba也没有去适配。
3. 日志级别动态指定，能玩吗？我目前还没有测试。Spring Boot是可以动态修改日志级别的。像这样：http://www.itmuch.com/spring-boot/change-logger-level/

**Comment by nkorange** [comment]
Related to #882

**Comment by nkorange** [comment]
1. 麻烦具体说说哪里不优雅
2. 参考[文档](https://nacos.io/zh-cn/docs/system-configurations.html)
3. 目前不能

**Comment by eacdy** [comment]
@nkorange 不优雅上面已经说了。
nacos既然是框架，在我看来，就不应该考虑日志的事情，日志让开发自己配置就可以了

**Comment by shalk** [comment]
我在使用0.8.0的时候也遇到了一些log依赖绑定的报错，更新到1.1.0就没有了。

现在看上去没有什么问题，nacos是配置了自身的日志。

**Comment by nkorange** [comment]
> @nkorange 不优雅上面已经说了。
> nacos既然是框架，在我看来，就不应该考虑日志的事情，日志让开发自己配置就可以了

日志级别动态指定已经在 #1552支持了。没理解你说的自己配置是什么意思，目前用xml也是可以配置的。

**Comment by eacdy** [comment]
@nkorange 其实我就是觉得自己搞一套日志管理有点多余。不如直接用Slf4j的Logger打日志。
这样在Spring Boot应用里面配置就OK了。
现在要配置多处……

**Comment by KomachiSion** [comment]
1. nacos不同于其他框架，是完全依附于业务的框架，nacos中存在很多异步任务，而且是旁路链路，如果大量日志不管设置直接使用用户Logger， 输出的大量日志会影响用户使用
2. spring 动态日志是通过销毁Logger再重建实现的，在客户端测不太好实现。
