### ISSUE TITLE
Source code compilation method compiled nacos-common error, plug-in version is too old

### ISSUE THREAD

**Issue by zyftc0** [alibaba/nacos#1351]
MVN插件版本source和target的版本是6，而core等都已经改成7了，6在编译时候会报错过久，请选用7或更新

**Comment by nkorange** [comment]
> MVN插件版本source和target的版本是6，而core等都已经改成7了，6在编译时候会报错过久，请选用7或更新

你编译哪个工程报错？

**Comment by zyftc0** [comment]
COMMON啊

**Comment by nkorange** [comment]
> COMMON啊
这个应该是你的Java版本过高导致，你Java版本多少？可以先手动修改common的编辑语言版本为7

**Comment by zyftc0** [comment]
哦！~Linux版本是12，本机是8，我已经手动改了，就是改完回来告诉你们一声
