### ISSUE TITLE
Private network can't load fonts, favicon

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/nacos#1352]
## Issue Description

Type: *bug report* or *feature request*
私有网络无法加载
http://at.alicdn.com/t/font_515771_emcns5054x3whfr.woff
http://www.aliyun.com/favicon.ico

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
REPOSITORY: nacos/nacos-server:latest
IMAGE ID: fbf2aa0a0435
CREATED: 2 months ago

**Comment by anpu2018** [comment]
In fact, this problem has not been completely solved. Under the service list label, the new service and the pop-up box still have the word ali cdn. It is doubtful whether it has been tested before pr.
