### ISSUE TITLE
Nacos V1.0.0 console Close health check failed

### ISSUE THREAD

**Issue by quanquan1996** [alibaba/nacos#1357]
中：单机模式，linux环境，使用 curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080' 
注册服务，在控制台-服务管理-服务列表-服务详情-集群-集群配置，选择检查类型为none关闭健康检查。然后不生效，F12发现请求500了。
请求路径：/nacos/v1/ns/cluster
返回结果：org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.IncompatibleClassChangeError: com.alibaba.nacos.api.naming.pojo.AbstractHealthChecker and com.alibaba.nacos.api.naming.pojo.AbstractHealthChecker$None disagree on InnerClasses attribute

EN：Stand-alone mode, linux environment, use curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
To register the service, in the Console - Service Management - Service List - Service Details - Cluster - Cluster Configuration, select the check type as none to turn off the health check. Then it does not take effect, F12 finds request 500.
Request path: /nacos/v1/ns/cluster
Returns: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.IncompatibleClassChangeError: com.alibaba.nacos.api.naming.pojo.AbstractHealthChecker and com.alibaba.nacos.api.naming. pojo.AbstractHealthChecker$None disagree on InnerClasses attribute

![image](https://user-images.githubusercontent.com/30221101/59322198-ad1a9a00-8d07-11e9-8af5-becfb96b51e4.png)
![image](https://user-images.githubusercontent.com/30221101/59322213-bf94d380-8d07-11e9-8b14-15fc91d8c844.png)
![image](https://user-images.githubusercontent.com/30221101/59322225-cc192c00-8d07-11e9-8cc7-b8694de3cca6.png)

**Comment by nkorange** [comment]
感谢反馈，我们尽快修复！
