### ISSUE TITLE
A advice

### ISSUE THREAD

**Issue by IanCao** [alibaba/nacos#1358]
i find a lot of issues has been solved but it's still be opened.
and it's to diffcult to find a valid issue

so i suggest that closing the solved issue or tag a solved tag

**Comment by nkorange** [comment]
Can you give some examples? We close issues only when the related PRs are merged into master branch.

**Comment by IanCao** [comment]
yes i mean those has been solved but not merge into master

**Comment by nkorange** [comment]
> yes i mean those has been solved but not merge into master

That's our default way. What's the problem of this way?
