### ISSUE TITLE
 getSubscribeServices()  get empty service list

### ISSUE THREAD

**Issue by GreyZeng** [alibaba/nacos#1366]
## Issue Description

bug report 

### Describe what happened (or what feature you want)
nacos sdk 1.0
String serverAddr = "ip1,ip2,ip3";
NamingService namingService = NamingFactory.createNamingService(serviceAddr);
namingService.getSubscribeServices()

but get empty service list

it can not get all subscribe services

### Describe what you expected to happen
we want get service list by nacos Java SDK

### Tell us your environment

nacos 1.0 version

**Comment by nkorange** [comment]
You get empty service list because you didn't actually subscribe any service. Try with the follow code:
```
String serverAddr = "ip1,ip2,ip3";
NamingService namingService = NamingFactory.createNamingService(serviceAddr);
namingSerivce.subscribe("service.name", new EventListener);
namingService.getSubscribeServices()
```

**Comment by GreyZeng** [comment]
> You get empty service list because you didn't actually subscribe any service. Try with the follow code:
> 
> ```
> String serverAddr = "ip1,ip2,ip3";
> NamingService namingService = NamingFactory.createNamingService(serviceAddr);
> namingSerivce.subscribe("service.name", new EventListener);
> namingService.getSubscribeServices()
> ```

![](https://img2018.cnblogs.com/blog/683206/201906/683206-20190613210311707-1699115802.png)

**Comment by nkorange** [comment]
> > You get empty service list because you didn't actually subscribe any service. Try with the follow code:
> > ```
> > String serverAddr = "ip1,ip2,ip3";
> > NamingService namingService = NamingFactory.createNamingService(serviceAddr);
> > namingSerivce.subscribe("service.name", new EventListener);
> > namingService.getSubscribeServices()
> > ```
> 
> but when I visit
> http://localhost:8848/nacos
> 
> There are three services in Service List

The method ```namingService.getSubscribeServices()``` just returns the services this client subscribes, not all services of Nacos.
