### ISSUE TITLE
The methods in CatalogController can be invoked in SDK

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1368]
These methods are useful for other system to integrate and display services of Nacos.

**Comment by IanCao** [comment]
i want to solve this issule. 
this means provider a interfaceMethod in api module for user to get the services list?

**Comment by nkorange** [comment]
@IanCao Yes, you can add the methods in ```com.alibaba.nacos.api.naming.NamingMaintainService```, which is released in Nacos 1.0.1.

At meantime, if you are interested to become Committer of Nacos, join this dingding group please: 23335652

**Comment by IanCao** [comment]
get it. thank u

**Comment by nkorange** [comment]
This feature is cancelled.
