### ISSUE TITLE
offline/online instance by using nacos java client sdk  

### ISSUE THREAD

**Issue by GreyZeng** [alibaba/nacos#1369]
## Issue Description

feature request

### Describe what happened (or what feature you want)

I want offline/online instance by using nacos java client sdk  

### Describe what you expected to happen
it seems there is no api in SDK to offline/online instance 

### Tell us your environment
nacos 1.0

**Comment by nkorange** [comment]
In 1.0.1, you can use NamingMaintainService.updateInstance() to accomplish your requirement.
