### ISSUE TITLE
Log incompatibility occurs when using nacos-server-1.0.0 (custom log (log4j2 used) will not have output)

### ISSUE THREAD

**Issue by enguangzhang** [alibaba/nacos#1371]
## Issue Description
使用nacos-server-1.0.0时出现日志不兼容情况(自定义日志(使用的log4j2)不会有输出)
Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
将新版本nacos集成到springcloud（Greenwich）中，启动时报错，错误信息：main WARN No Root logger was configured, creating default ERROR-level Root logger with Console appender
，升级nacos之后才会出现这个问题
### How to reproduce it (as minimally and precisely as possible)

1. 之前用的nacos版本0.8.0，依赖版本为0.2.1.RELEASE
2. 现在nacos升级到1.0.0，依赖版本为（0.2.2.RELEASE）或者（0.9.0.RELEASE），这两个依赖版本都会出现问题
3. 是可以将服务注册上去的，也能正常调用，但是自定义的日志（使用的log4j2）不会输出

### Tell us your environment
依赖版本
           <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>0.9.0.RELEASE</version>
jdk1.8
springboot 2.1.2.RELEASE
springcloud Greenwich

**Comment by enguangzhang** [comment]
找到原因报错原因了，在spring-cloud-starter-alibaba-nacos-discovery（0.9.0.RELEASE）中所依赖的nacos-client（1.0.0）中的文件nacos-log4j2.xml内容少了一个标签：<Root level="INFO">
            <AppenderRef ref="CONFIG_LOG_FILE"/>
        </Root>

**Comment by nkorange** [comment]
> 找到原因报错原因了，在spring-cloud-starter-alibaba-nacos-discovery（0.9.0.RELEASE）中所依赖的nacos-client（1.0.0）中的文件nacos-log4j2.xml内容少了一个ROOT标签。希望更新一下maven仓库的jar包 @jun1st @mercyblitz @huangyunbin @ddatsh @nanamikon

创建一个PR来贡献你的修复吧！

**Comment by enguangzhang** [comment]
> > 找到原因报错原因了，在spring-cloud-starter-alibaba-nacos-discovery（0.9.0.RELEASE）中所依赖的nacos-client（1.0.0）中的文件nacos-log4j2.xml内容少了一个ROOT标签。希望更新一下maven仓库的jar包 @jun1st @mercyblitz @huangyunbin @ddatsh @nanamikon
> 
> 创建一个PR来贡献你的修复吧！

**Comment by enguangzhang** [comment]
> > 找到原因报错原因了，在spring-cloud-starter-alibaba-nacos-discovery（0.9.0.RELEASE）中所依赖的nacos-client（1.0.0）中的文件nacos-log4j2.xml内容少了一个ROOT标签。希望更新一下maven仓库的jar包 @jun1st @mercyblitz @huangyunbin @ddatsh @nanamikon
> 
> 创建一个PR来贡献你的修复吧！

你们近期有更新maven远程仓库nacos jar包的打算吗？

**Comment by enguangzhang** [comment]
> spring-cloud-starter-alibaba-nacos-discovery

顺便问一下spring-cloud-starter-alibaba-nacos-discovery这个也是你们在维护吗

**Comment by nkorange** [comment]
> > > 找到原因报错原因了，在spring-cloud-starter-alibaba-nacos-discovery（0.9.0.RELEASE）中所依赖的nacos-client（1.0.0）中的文件nacos-log4j2.xml内容少了一个ROOT标签。希望更新一下maven仓库的jar包 @jun1st @mercyblitz @huangyunbin @ddatsh @nanamikon
> > 
> > 
> > 创建一个PR来贡献你的修复吧！
> 
> 你们近期有更新maven远程仓库nacos jar包的打算吗？

预计月底会发布一次。spring-cloud-starter-alibaba-nacos-discovery是在另外的仓库哈，地址是：https://github.com/spring-cloud-incubator/spring-cloud-alibaba

**Comment by huanti** [comment]
请问这个问题，是月底的发布会修复么？
