### ISSUE TITLE
springcloud[springboot2.1.5] Unable to register the nacos registry

### ISSUE THREAD

**Issue by rottenmu** [alibaba/nacos#1377]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by wangkai1994** [comment]
+1

**Comment by kinun0623** [comment]
+1
![image](https://user-images.githubusercontent.com/16216334/60852988-c6423800-a22c-11e9-9fbc-f09c76d93d9b.png)

![image](https://user-images.githubusercontent.com/16216334/60853008-d9550800-a22c-11e9-842f-b9f2fb780505.png)

![image](https://user-images.githubusercontent.com/16216334/60853026-e96ce780-a22c-11e9-9f3e-ba4b3559a2b1.png)

**Comment by kinun0623** [comment]
![image](https://user-images.githubusercontent.com/16216334/60853748-0f47bb80-a230-11e9-9fab-f3adff488493.png)

**Comment by nkorange** [comment]
This is a [spring cloud alibaba](https://github.com/alibaba/spring-cloud-alibaba) issue.
