### ISSUE TITLE
How to set the type when publishConfig

### ISSUE THREAD

**Issue by zhouwenqi** [alibaba/nacos#1378]
configService.publishConfig(dataId,group,content)；
在保存配置的时候，怎么设置配置文件类型？
尤其是有个很坑的问题是，原来的文件类型是xml或yaml文件类型，用api修改完之后，就保存为text文件了。

**Comment by nkorange** [comment]
这个文件格式只是在控制台方便编辑，实际上Nacos后台不会保存该文件格式。
