### ISSUE TITLE
some enhancements for Console UI

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#1381]
1. Don't disable the textfield of 'Group' and 'Data ID'，because uses sometimes want to copy the value of those two text value. Setting them with editable false is enough
不要灰掉Group和Data ID的文本框，有时候，使用者因为Key比较难记住，希望拷贝一下。弄成不可编辑，但可复制文本即可。

2. In the config list, it is better to add a summary of config value, for example, add a large tooltip?
在配置列表里面，如果加上配置内容的概要预览也许更好，比如加个大的Tooltip，这样使用者对于很多配置，不需要一个一个点进去看

**Comment by KomachiSion** [comment]
1 has finished in new version.
2 has no plan to support.
