### ISSUE TITLE
Nacos service registry specifying namespace does not work

### ISSUE THREAD

**Issue by syzpig** [alibaba/nacos#1384]
When Nacos is registered in the ymal configuration file, the client service specifies the registry namespace, and finds that the service is not registered in the specified namespace, but registered in the default namespace, i.e. public. What is the reason? How to solve it?
在自定义命名空间时，客户端服务在ymal配置文件中注册配置nacos时，指定注册中心命名空间，发现服务没有注册到指定命名空间，而是注册到默认的命名空间中也就是public,请问这是什么原因？怎么解决？

**Comment by RongXiong2016** [comment]
I also encountered the same problem.

**Comment by syzpig** [comment]
> 我也遇到了同样的问题。

因为1.8以后，服务注册中心不在支持命名空间
