### ISSUE TITLE
Can we doc the configuration properties or environment variables?

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#1386]
Can we doc the configuration properties or environment variables?
Such as:
```
logging.level.root
nacos.logging.path
com.alibaba.nacos.naming.log.filename
```
And so on.

I think there are a lot of configuration properties, we need a doc describe these configuration properties detailed.

**Comment by eacdy** [comment]
@nkorange @jameslcj

**Comment by nkorange** [comment]
Good advice.

**Comment by nkorange** [comment]
Available in https://nacos.io/zh-cn/docs/system-configurations.html

**Comment by eacdy** [comment]
@nkorange Thanks a lot. 
But I found that some environment havn't been docuented.
Such as 
```java
    static {
        LOCAL_FILEROOT_PATH = System.getProperty("JM.LOG.PATH", System.getProperty("user.home")) + File.separator
            + "nacos" + File.separator + "config";
        LOCAL_SNAPSHOT_PATH = System.getProperty("JM.SNAPSHOT.PATH", System.getProperty("user.home")) + File.separator
            + "nacos" + File.separator + "config";
        LOGGER.info("LOCAL_SNAPSHOT_PATH:{}", LOCAL_SNAPSHOT_PATH);
    }
```

<https://github.com/alibaba/nacos/blob/1.1.3/client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java>


Could you please add these env to < https://nacos.io/zh-cn/docs/system-configurations.html> ?
