### ISSUE TITLE
upload yaml file to nacos,the default format is text

### ISSUE THREAD

**Issue by AllenJol** [alibaba/nacos#1387]
when i upload some yaml file to nacos,it default format is text when you click edit file.

The methods to resolve it is add type=yaml
for example:
curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=HelloWorld&type=yaml"

**Comment by nkorange** [comment]
It is by design. Nacos cannot detect what the format is precisely.
