### ISSUE TITLE
standalone - System lock DELETE FROM config_info WHERE data_id='com.alibaba.nacos.testMasterDB'

### ISSUE THREAD

**Issue by LegendaryFlutist** [alibaba/nacos#1393]
## Issue Description

A large number of execution in a single node environment 
sql:
{
DELETE FROM config_info WHERE data_id = 'com. Alibaba. Nacos. TestMasterDB' ,
SELECT * FROM config_info_beta WHERE id = 1 
}
in the mysql database CPU is full

### Describe what happened (or what feature you want)

After a single node has been running for some time,mysql blocks a large number of threads requesting locks
DELETE FROM config_info WHERE data_id = 'com. Alibaba. Nacos. TestMasterDB' ,

**Comment by LegendaryFlutist** [comment]
I'm constantly rebooting apps

**Comment by LegendaryFlutist** [comment]
![image](https://user-images.githubusercontent.com/49219271/59759745-52fb7500-92c3-11e9-8de2-cf5b7b9dfd99.png)

**Comment by nkorange** [comment]
This SQL is executed every 30 seconds, it should not cause so many locks normally. How frequent this SQL is executed on your MySQL server?

**Comment by lijilina** [comment]
解决了嘛
