### ISSUE TITLE
Problem of RegistryDirectory.notify method won't be invoked

### ISSUE THREAD

**Issue by XXMY** [alibaba/nacos#1394]
Hi guys,
 I met a problem which I could not fix out. I have set the property of  "check" of @Reference annotation to false, then run the consumer first to register it into the Nacos registry center. After that, I start to run the provider which my consumer referenced. When all those things are done, I start to invoke my hello-world method which contains the referenced method of provider side, then I received an Error response with "No provider available" message.
 I have checked the method of RegistryDirectory.doList() , and found methodInvokerMap property was empty. Also, I have checked the method of RegistryDirectory.notify() and debugged it, found it won't be invoked whatever provider is registered into the Nacos registry center or deregistered from there.
 Blowing is the main configuration of my project:
pom.xml file

>  
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.6</version>
            <exclusions>
                <exclusion>
                    <artifactId>netty</artifactId>
                    <groupId>org.jboss.netty</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>2.6.6</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.spring</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>1.0.2</version>
        </dependency>

applicationContext.xml

> 
        <dubbo:annotation package="com.test.dubbo"/>
        <dubbo:application name="dubboTest" owner="mams" organization="mams">
              <dubbo:parameter key="qos.enable" value="false"/>
        </dubbo:application>
        <dubbo:registry address="nacos://localhost:8848"/>

Thanks for helping

**Comment by nkorange** [comment]
Dubbo client version problem.
