### ISSUE TITLE
bug or my mistake?

### ISSUE THREAD

**Issue by chenshun00** [alibaba/nacos#1400]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
1、start springboot , inject field like userLocalCache,name,gg .  (666,444,555)
2、change properties by nacos. (userLocalxx=333,name=111,gg=22)
3、println(userLocalCache,name,gg) ===> 333,444,555, acturl ---> 333,111,222

### Describe what you expected to happen
up

### How to reproduce it (as minimally and precisely as possible)
```
@Controller
@NacosPropertySource(dataId = "nacos-config.properties", groupId = "DEFAULT_GROUP", autoRefreshed = true)
@RequestMapping("config")
@Slf4j
public class ConfigController implements CommandLineRunner {

    @NacosValue(value = "${useLocalCache:false}", autoRefreshed = true)
    private String useLocalCache;

    @NacosValue(value = "${name:陈顺}", autoRefreshed = true)
    private String name;

    @NacosValue(value = "${gg:gg}", autoRefreshed = true)
    private String gg;

    public ConfigController() {
    }

    public void setUseLocalCache(String useLocalCache) {
        this.useLocalCache = useLocalCache;
    }

    @NacosInjected
    private NamingService namingService;

    @RequestMapping(value = "/get")
    @ResponseBody
    public Object get() throws NacosException {
        return namingService.getAllInstances("aaa");
    }


    @RequestMapping(value = "/ddd")
    @ResponseBody
    public Object ddd() {
        return useLocalCache;
    }

    @Override
    public void run(String... args) throws Exception {
//        while (true) {
        Thread.sleep(4000);
//            log.info("[NacosConfigAnnoatationService]注解方式获取到的配置项目,useLocalCache={},name={},gg={} ", useLocalCache, name, gg);

//        }
    }


    @Override
    public String toString() {
        return "ConfigController{" +
                "useLocalCache='" + useLocalCache + '\'' +
                ", name='" + name + '\'' +
                ", gg='" + gg + '\'' +
                '}';
    }
}
```

pom# SpringBoot 2.1.4.RELEASE
```
  <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.0</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-actuator</artifactId>
            <version>0.2.0</version>
        </dependency>


        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-discovery-spring-boot-starter</artifactId>
            <version>0.2.0</version>
        </dependency>
```

### Tell us your environment
Mac os x

![image](https://user-images.githubusercontent.com/26037282/59756792-09a82700-92bd-11e9-81f5-65a3c6edfa93.png)

**Comment by chenshun00** [comment]
If the set method does not exist ，a exception will be throw.  `AbstractNestablePropertyAccessor#processLocalProperty`  :)

**Comment by paderlol** [comment]
> If the set method does not exist for field ，a exception will be throw. `AbstractNestablePropertyAccessor#processLocalProperty` :)


As described above, you use 0.2.0 version will have this problem, because when automatically refreshing the value using the `org.springframework.validation.DataBinder` assignment.
It requires all the attributes you need to add a setter method, can appear otherwise abnormal org.springframework.beans.NotWritablePropertyException

The Solution
1. This problem has been fixed in **nacos-config-spring-boot-starter** **0.2.1**
2. Also, you have to add setter methods to the name and gg fields if you don't want to upgrade
