### ISSUE TITLE
Does nacos only have configuration management to use MySQL? Can service discovery not use MySQL?

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#1405]
RT. 我看到nacos-mysql.sql 只有配置管理的几张表，服务发现的表是没有的，例如app_list。
所以想确认下。

**Comment by eacdy** [comment]
@nkorange

**Comment by nkorange** [comment]
No, Nacos discovery uses local disk to store all data.

**Comment by eacdy** [comment]
@nkorange I see. Thanks a lot.
