### ISSUE TITLE
Yaml format configuration file color rendering bug

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/nacos#1408]
yaml格式配置文件如果为长字符串，需要使用英文双引号，nacos显示自动换行，字符串中间包含冒号，长字符串后的配置项均渲染错误

## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
spring:
  cloud:
    gateway:
      filter:
        secure-headers:
          content-security-policy: "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src https:; style-src 'self' https: 'unsafe-inline'"

test: 123 #<---这行开始颜色渲染出错

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.0.1

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
