### ISSUE TITLE
Integrate with Istio as a service discovery backend

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1409]

**Comment by IanCao** [comment]
i'll solve it

**Comment by nkwangleiGIT** [comment]
@IanCao what's the plan for this requirement?
I think we'll add a platform adapter for istio support, and also add a watch support for Nacos service discovery? 
Thanks!

**Comment by IanCao** [comment]
> @IanCao what's the plan for this requirement?
> I think we'll add a platform adapter for istio support, and also add a watch support for Nacos service discovery?
> Thanks!

yes i have added some implements codes  in my istio repo dev_naco branch

**Comment by IanCao** [comment]
> @IanCao what's the plan for this requirement?
> I think we'll add a platform adapter for istio support, and also add a watch support for Nacos service discovery?
> Thanks!

if u're interested in this issue, we can build together, my dingding is fvkkdd1

**Comment by nkorange** [comment]
This issue is currently being worked on project [nacos-istio](https://github.com/nacos-group/nacos-istio).

**Comment by nkorange** [comment]
This is being developed by using MCP protocol of Istio.
