### ISSUE TITLE
The list of console services is not querying.

### ISSUE THREAD

**Issue by zyw** [alibaba/nacos#141]
# 报告错误
nacos-server-0.3.0-RC1.zip版本
环境：Mac
JDK: JDK8
启动后查看服务列表没有数据但是服务是可以正常消费的，微信群里面的另外一位使用windows服务可以正常查询到
![image](https://user-images.githubusercontent.com/661159/47256962-60552b00-d4ba-11e8-939c-5645e7c23441.png)
自己拉去master代码在Mac编译并启动服务可以正常查询到
![image](https://user-images.githubusercontent.com/661159/47256979-9a263180-d4ba-11e8-952e-81c48159fa07.png)

**Comment by yanlinly** [comment]
请重新下载一下，开始前端代码没编译进去导致的。

Please re-download it and start the front-end code without compiling it.
