### ISSUE TITLE
Spring Cloud Gateway integrate nacos problems

### ISSUE THREAD

**Issue by GreyZeng** [alibaba/nacos#1415]
## Issue Description

*bug report* 

### Describe what happened (or what feature you want)

Spring Cloud Gateway无法获取nacos的服务实例的上下线状态
Spring Cloud Gateway can not aware the online/offline  service instance

### Describe what you expected to happen

Spring Cloud Gateway应该拿到nacos的上线的服务实例，而非已下线的服务实例
Spring Cloud Gateway should get the online service instance，not offline instance

### How to reproduce it (as minimally and precisely as possible)

1. 在nacos下注册一个A服务，并启动两个A服务的实例（A1，A2） 
register A service in nacos， and start two instances of A service
2. 当用Spring Cloud Gateway访问A服务的时候，会负载均衡转发到A1或者A2实例
visite A service by using Spring Cloud Gateway，A1 and A2 instance will be visited。
3. 把A1下线操作，用Spring Cloud Gateway访问A服务，发现请求还是会流入A1
offline A1 instance， visite A service by using Spring Cloud Gateway，request will be in A1

### Tell us your environment
Spring boot 2.1.6.RELEASE
Nacos 1.0.RELEASE
Spring Cloud Alibaba 0.9.0.RELEASE
Spring Cloud Greenwich.SR1

**Comment by nkorange** [comment]
Maybe there is more work to do to integrate Nacos with spring-cloud-gateway. We will look into it.
