### ISSUE TITLE
Cluster Count=1,Instance Count=0, Healthy Instance Count=0

### ISSUE THREAD

**Issue by GreyZeng** [alibaba/nacos#1416]
## Issue Description

*bug report* 

### Describe what happened (or what feature you want)
Nacos web console, 
in Service List 
A service is
Cluster Count=1
Instance Count=0
Healthy Instance Count=0

is a dirty data?

BUT When I get the data from nacos java sdk  by using:
namingService.getAllInstances(A_SERVICE_NAME); ---> return empty list 
and I can not get cluster by using:   instance.getClusterName()
so when I use nacos sdk, I get cluster count = 0
when I see it in nacos web console, the cluster count = 1

### Describe what you expected to happen
the cluster count by using nacos sdk is the same of the number of the cluster count in nacos web console

### Tell us your environment
nacos client 1.0
nacos server 1.0 RELEASE(there clusters of nacos)

**Comment by nkorange** [comment]
Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.

**Comment by GreyZeng** [comment]
> Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.

But we use Spring Cloud Alibaba 0.9.0.RELEASE, it seems the latest RELEASE version of Spring Cloud Alibaba, in 0.9.0.RELEASE , the version of nacos is 1.0.0.RELEASE.

**Comment by GreyZeng** [comment]
> Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.



> > Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.
> 
> But we use Spring Cloud Alibaba 0.9.0.RELEASE, it seems the latest RELEASE version of Spring Cloud Alibaba, in 0.9.0.RELEASE , the version of nacos is 1.0.0.RELEASE.



> Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.

and I want to know , if I remove  Spring Cloud Alibaba parent dep, what can I do if I only use Nacos Discovery/Config for Spring Cloud

**Comment by GreyZeng** [comment]
> Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.

and I want to know , if I remove Spring Cloud Alibaba parent dep, what can I do if I only use Nacos Discovery/Config for Spring Cloud

**Comment by nkorange** [comment]
> > Use [NamingMaintainService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingMaintainService.java), which is available in 1.0.1, to query the cluster count of a service please.
> 
> and I want to know , if I remove Spring Cloud Alibaba parent dep, what can I do if I only use Nacos Discovery/Config for Spring Cloud

Use [this](https://nacos.io/zh-cn/docs/sdk.html) please.
