### ISSUE TITLE
Nacos C# client SDK  support

### ISSUE THREAD

**Issue by geffzhang** [alibaba/nacos#1419]
Microsoft releases Open source cross-platform .net core https://github.com/dotnet,  Upcoming Release 3.0. As a popular language, c# has an advantage in cloud-native application development,  Is there someone started to implement the c# API?

**Comment by nkorange** [comment]
No one is working on this as far as I know. You are welcome to contribute for it.

**Comment by catcherwong** [comment]
I am working on the c# SDK based on the [documentation of open-api](https://nacos.io/en-us/docs/open-api.html) .

https://github.com/catcherwong/nacos-sdk-csharp

**Comment by nkorange** [comment]
> I am working on the c# SDK based on the [documentation of open-api](https://nacos.io/en-us/docs/open-api.html) .
> 
> https://github.com/catcherwong/nacos-sdk-csharp

Nick work! Is your SDK already available? I can introduce it to the community.

**Comment by catcherwong** [comment]
Yes, I published it three months ago.

https://www.nuget.org/packages/nacos-sdk-csharp-unofficial/

**Comment by catcherwong** [comment]
Here is a simple post to introduce how to use it.

https://www.cnblogs.com/catcher1994/p/11489052.html

**Comment by leyou240** [comment]
@nkorange  I think it's time to introduce to the community. @catcherwong Good job, brother!

**Comment by KomachiSion** [comment]
close by #3018
