### ISSUE TITLE
Enhancement for Nacos console 界面优化的建议

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#142]
1. 增加修改配置的时候，Group是必选，把Group移出来，不要放在“更多高级选项里”
    Please move "Group" item out of "Advanced Options"
2. 服务详情里，增加严格权限机制，元数据不能擅自被修改
    Please add a permisson control for meta data modification in "Service Details"

**Comment by HaojunRen** [comment]
3. 在服务列表里，健康实例数为0的服务，建议高亮成下线状态的那种颜色

**Comment by yanlinly** [comment]
TO: 增加修改配置的时候，Group是必选，把Group移出来，不要放在“更多高级选项里”
Please move "Group" item out of "Advanced Options"

设计的时候考虑填写少让用户关心一些东西，但是你说的有道理，必选项要暴露的。我下一个版本修复解决掉。 多谢反馈！
When designing, consider filling in less of the user's concern for something, but what you said makes sense and must be exposed. My next version fix is fixed. Thanks for the feedback!
