### ISSUE TITLE
Using Nacos as a registration center, the integration of Dubbo in the Spring Cloud project does not display multiple instances of Dubbo consumers, only the latest one.

### ISSUE THREAD

**Issue by ACXNX** [alibaba/nacos#1424]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen

![nacos](http://wx1.sinaimg.cn/large/7acb8fb8ly1g4aj5dbz30j20xp0u0ajo.jpg)

The SpringCloud project uses Nacos as a service registry and registers with Nacos the Dubbo RPC service and the HTTP Rest service provided by the SpringBoot component. The situation is such that when there are multiple service consumers (consumers:com.acanx.dubbo.api.DemoService, there are actually two from ACANX-SpringCloud-Demo-Application and ACANX-SpringCloud-Dubbo-Service -Consumer) When they need to register to Nacos, they all consume the same Dubbo RPC service provider: com.acanx.dubbo.api.DemoService, there is only one)
However, after the registration is successful, the actual verification test indicates that the service has been successfully registered, and multiple Dubbo consumers can also call the Dubbo RPC service normally, but there is only one consumer instance of Dubbo displayed in the Nacos service list (there are actually two). It can only show the latest registered service consumers, that is, the newly registered service consumers will replace the original consumers, and will not display all service consumers as expected (ACANX-SpringCloud-Demo-Application and ACANX-SpringCloud-Dubbo-Service-Consumer) information.

SpringCloud项目，使用Nacos作为服务注册中心，同时向Nacos注册Dubbo RPC服务和SpringBoot组件提供的HTTP Rest服务。遇到问题的情况是这样的，当有多个服务消费者（consumers:com.acanx.dubbo.api.DemoService，实际有两个分别来自ACANX-SpringCloud-Demo-Application和ACANX-SpringCloud-Dubbo-Service-Consumer）需要注册到Nacos中时，他们都消费同一个Dubbo RPC服务providers:com.acanx.dubbo.api.DemoService，实际只有一个）
但是在注册成功后，实际验证测试表明服务已经成功注册，多个Dubbo消费者也能正常调用Dubbo RPC服务，但是在Nacos的服务列表里面显示的Dubbo的消费者实例只有一个（实际有两个），经测试只能显示最新注册的一个服务消费者，也就是说新注册的服务消费者会顶替原来的消费者，并不能按预期列表显示所有的服务消费方（ACANX-SpringCloud-Demo-Application和ACANX-SpringCloud-Dubbo-Service-Consumer）的信息。

### How to reproduce it (as minimally and precisely as possible)

1. Spring Cloud system, using Nacos as a service discovery and registration center
Register a service provider to provide Dubbo RPC services;
2. Register two or more service consumers to consume the services in 1.
3. Check the instance information of the Dubbo RPC service consumer in the Nacos console.

1.Spring Cloud系统，使用Nacos作为服务发现和注册中心
注册一个服务提供方，提供Dubbo RPC 服务；
2.注册两个甚至多个服务消费者，来消费1中的服务。
3.在Nacos控制台检查Dubbo RPC 服务消费者的实例信息

### Tell us your environment
- JDK11  
- Window10
- SpringCloud Greenwich.RELEASE
- SpringBoot2.1.6
- Spring Framework 5.1.8
- Nacos v1.0.1
- Dubbo 2.7.1
- spring-cloud-alibaba   v0.9.0.RELEASE

### Anything else we need to know?
![SharedScreenshot](https://user-images.githubusercontent.com/12597131/59968186-2320cb80-9568-11e9-8f7e-47e2e8e8e2a7.jpg)

**Comment by nkorange** [comment]
Already explained int #1299. It requires alteration in Dubbo.
