### ISSUE TITLE
nacos 1.0.1 mysql 5.7 login and query config_info

### ISSUE THREAD

**Issue by BeastMouth** [alibaba/nacos#1428]
## Issue Description

- When I configure MySQL as a data source, log in to Nacos and query the configuration. The system reports errors.
  The contents of the error report are as follows

  ``org.springframework.jdbc.CannotGetJdbcConnectionException: PreparedStatementCallback; uncategorized SQLException for SQL [select ID,data_id,group_id,tenant_id,app_name,content from config_info where  tenant_id=?  limit 0,10]; SQL state [null]; error code [0]; Borrow prepareStatement from pool failed; nested exception is org.apache.commons.dbcp.SQLNestedException: Borrow prepareStatement from pool failed`
  	`at com.alibaba.nacos.config.server.exception.GlobalExceptionHandler.handleDataAccessException(GlobalExceptionHandler.java:76)`
  	`at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
  	`at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

- The configuration of the database is

  `spring.datasource.platform=mysql`

  

  `db.num=1`
  `db.url.0=jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true`
  `db.user=root`
  `db.password=Hbj1996`

Please teach me how to solve this problem.Thanks

**Comment by BeastMouth** [comment]
Sorry, I pulled the dev code.
Version 1.0.0 is normal

**Comment by BeastMouth** [comment]
Sorry, I pulled the dev code.
Version 1.0.0 is normal
How do I modify the configuration in version 1.0.1

**Comment by nkorange** [comment]
The database configuration doesn't change from 1.0.0 to 1.0.1. So there must be some kind of bug or something. Did you try the package in [1.0.1](https://github.com/alibaba/nacos/releases/tag/1.0.1)?

**Comment by zhouliyu0309** [comment]
我使用的是1.0.2版本的nacos-server,在配置单机集成mysql时候遇到了同样的问题，请问最后怎么解决的。
错误如下：org.springframework.jdbc.CannotGetJdbcConnectionException: PreparedStatementCallback; uncategorized SQLException for SQL [select ID,data_id,group_id,tenant_id,app_name,content from config_info where  tenant_id=?  limit 0,10]; SQL state [null]; error code [0]; Borrow prepareStatement from pool failed; nested exception is org.apache.commons.dbcp.SQLNestedException: Borrow prepareStatement from pool failed

**Comment by nkorange** [comment]
> 我使用的是1.0.2版本的nacos-server,在配置单机集成mysql时候遇到了同样的问题，请问最后怎么解决的。
> 错误如下：org.springframework.jdbc.CannotGetJdbcConnectionException: PreparedStatementCallback; uncategorized SQLException for SQL [select ID,data_id,group_id,tenant_id,app_name,content from config_info where tenant_id=? limit 0,10]; SQL state [null]; error code [0]; Borrow prepareStatement from pool failed; nested exception is org.apache.commons.dbcp.SQLNestedException: Borrow prepareStatement from pool failed

Use package in the [release page](https://github.com/alibaba/nacos/releases) please.

**Comment by BeastMouth** [comment]
I pulled out the code according to the official document (version 1.0.1 at that time), configured MySQL for Nacos according to the document guide, and then the above problem occurred.

**Comment by BeastMouth** [comment]
后来我使用了1.0.0  今天试着在docker上拉取了官方镜像 也是正常的
