### ISSUE TITLE
Service gets a specific configuration item

### ISSUE THREAD

**Issue by lanpang** [alibaba/nacos#1429]
Type:  *feature request*

### Service gets a specific configuration item  
Different services have the same configuration template, but some specific content is different． The different content be delivered through the nacos?

### Describe what you expected to happen
**Example**
service A,config file is  
```
host="127.0.0.1"
port=8081
```
service B,config file is
```
host="127.0.0.1"
port=8081
```

**Comment by nkorange** [comment]
Not quite understand what you mean. Join dingding group 21708933 to explain it more please.
