### ISSUE TITLE
Roadmap discussion

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1433]
Nacos 1.1.0 will be released on July 5th and includes updates to features such as grayscale configuration. At the same time, Nacos will release this year's overall Roadmap, which has collected a lot of [feedback](https://github.com/alibaba/nacos/issues/960) from the community. Nacos is committed to solving user problems, and hopes that each version will bring tangible expectations and benefits to users.

So here are the main features that have been included in the Roadmap, **you can point out several features that you think are important in the response, and explain the scenarios used.**

In the end, Nacos will follow the community feedback to decide the following plan, and all the features in the roadmap can be applied for development. In short, Nacos is defined by the community!

* Grayscale configuration
* Configure permission control
* Service permission control
* Service Mesh docking, such as docking Pilot
* gRPC service discovery support
* Thrift service discovery support
* DNS protocol support, support Kubernetes DNS specification
* Confd mode rendering configuration
* Configure release approval
* Configure encryption
* Inter-cluster configuration synchronization
* Raft protocol abstraction and replacement
* Kubernetes ConfigMap docking
* Mysql dependencies can be replaced with local or other storage
* Support Kubernetes Label storage
* Support for Kubernetes health check
* Command line operation and maintenance tools similar to Zookeeper
* IPv6 support
* Nacos Go SDK
* Nacos C++ SDK

Nacos 1.1.0即将于7月5号发布，包含灰度配置等功能的更新。同时将发布的是Nacos今年整体的Roadmap，目前已经收集到社区的众多[反馈](https://github.com/alibaba/nacos/issues/960)。Nacos致力于解决用户的问题，希望每一个版本都能给用户带来切实的期待和收益。

因此在这里将已经纳入Roadmap的主要特性列举出来，**你可以在回复中将你认为比较重要的几个特性指出，并说明下使用的场景**。

最终，Nacos会按照社区的反馈来决定接下来的版本计划，同时所有在roadmap里的特性，都可以来认领开发。总之，Nacos由社区定义！

* 灰度配置
* 配置权限控制
* 服务权限控制
* Service Mesh对接，例如对接Pilot
* gRPC服务发现支持
* Thrift服务发现支持
* DNS协议支持，支持Kubernetes DNS规范
* Confd模式渲染配置
* 配置发布审批
* 配置加密
* 集群间配置同步
* Raft协议抽象及替换
* Kubernetes ConfigMap对接
* Mysql依赖可替换为本地或者其他存储
* 支持Kubernetes Label存储
* 支持使用Kubernetes健康检查
* 与Zookeeper类似的命令行运维工具
* IPv6支持
* Nacos Go SDK
* Nacos C++ SDK

**Comment by icc99** [comment]
Nacos Go SDK

**Comment by dongyinuo** [comment]
配置权限控制
服务权限控制
灰度配置

**Comment by xiaoailiang** [comment]
灰度配置
配置权限控制
服务权限控制
Service Mesh对接，例如对接Pilot
gRPC服务发现支持
Thrift服务发现支持

**Comment by 1346735074** [comment]
配置权限控制
服务权限控制
灰度配置

**Comment by jerrychenzj** [comment]
灰度配置
配置权限控制
服务权限控制

**Comment by lutao1726** [comment]
灰度配置
配置权限控制
服务权限控制

**Comment by jjlu521016** [comment]
灰度配置
配置权限控制
服务权限控制
gRPC服务发现支持
Thrift服务发现支持

**Comment by zhengxiaochuan** [comment]
灰度配置
配置权限控制
服务权限控制

**Comment by xingcun** [comment]
Mysql依赖可替换为本地或者其他存储

**Comment by Stephenzho** [comment]
灰度配置
Mysql依赖可替换为本地或者其他存储

**Comment by Hwxlol** [comment]
Nacos Go SDK

**Comment by angsen3588** [comment]
灰度配置
配置权限控制
Service Mesh对接，例如对接Pilot
gRPC服务发现支持
Thrift服务发现支持
支持使用Kubernetes健康检查

**Comment by 511098425** [comment]
灰度配置
配置权限控制
服务权限控制
配置发布审批
集群间配置同步

**Comment by 511098425** [comment]
灰度配置
配置权限控制
服务权限控制
配置发布审批
集群间配置同步
Mysql依赖可替换为本地或者其他存储

**Comment by swift9** [comment]
先把服务发现各版本 SDK，不能加命名空间的 BUG 解决掉吧

**Comment by chuawei** [comment]
IPv6支持
灰度配置
配置权限控制
服务权限控制

**Comment by frozero** [comment]
IPv6支持
灰度配置
配置权限控制
服务权限控制

**Comment by glameyzhou** [comment]
灰度配置，配置权限，服务权限。另外是否可以把项目单独拎出来一个概念，所有的服务和配置都基于项目来走。

**Comment by xsdt** [comment]
IPv6支持
灰度配置
配置权限控制
服务权限控制

**Comment by yangxi93** [comment]
IPv6支持
灰度配置
配置权限控制
服务权限控制

**Comment by legiorange** [comment]
灰度配置
配置加密(在这里我仍然推荐实现AES以及RSA算法)
配置权限控制
服务权限控制
Gateway动态路由
使用场景:
在生产环境下，灰度配置和配置权限，以及服务权限的需求呼之欲出

在这之前 Nacos仍然有待解决的问题：
可读性很好的文档
至少我看Sentinel(wiki)时不会迷惘。
今天下午卡在nacos结合gateway动态路由这里，目前仍在迷路。
大量数据加密AES比较好，所以我也推荐优先实现aes-256/aes-1024

感谢各位创造、支持并为Nacos付出实际努力的人（如果我技术好的话我也希望我是其中一员）

**Comment by shanyepifu** [comment]
灰度配置
配置权限控制
服务权限控制
gRPC服务发现支持

**Comment by bpzhang** [comment]
配置权限控制
服务权限控制
灰度配置
和Sentinel的数据打通

**Comment by winter-git** [comment]
配置灰度
配置加密
配置权限控制
服务权限控制

**Comment by inotgaoshou** [comment]
灰度配置
配置权限控制
服务权限控制
配置加密

**Comment by stanvl** [comment]
Configure permission control
Configure release approval
Configure encryption
Inter-cluster configuration synchronization

**Comment by jieliu** [comment]
Mysql依赖可替换为本地或者其他存储

**Comment by xiaolongyuan** [comment]
- 灰度配置
- 配置权限控制
- 服务权限控制
- Mysql依赖可替换为本地或者其他存储

**Comment by alexzhu0592** [comment]
- 灰度配置
- 配置权限控制
- 服务权限控制
- 配置发布审批
- 配置加密
- 集群间配置同步

**Comment by romeoblog** [comment]
灰度配置
配置权限控制
服务权限控制
配置发布审批
配置加密
集群间配置同步

**Comment by inotgaoshou** [comment]
7月5号过了，好像还没发版1.1.0？

**Comment by jifengnan** [comment]
1. 配置权限控制
2. 配置发布审批
3. 灰度配置
4. 集群间配置同步
5. 服务权限控制
6. 配置加密

**Comment by nkorange** [comment]
Roadmap is published: https://nacos.io/zh-cn/blog/nacos-roadmap.html

**Comment by yfh0918** [comment]
python sdk

**Comment by douxiaofeng99** [comment]
Mysql依赖可替换为本地或者其他存储(希望包括zookeeper）
另外，有增加开关，可以关闭nacos config
nacos config单独UI
