### ISSUE TITLE
nacos config [notify-error] from c.a.nacos.client.config.impl.CacheData

### ISSUE THREAD

**Issue by marcus-si** [alibaba/nacos#1435]
## Issue Description
When putting an method annotated by @EventListener(classes = RefreshEvent.class) in a class annotated by @Controller,  @Configuration or similar, Class c.a.nacos.client.config.impl.CacheData will throw [notify-error], and then a nacos config client cannot get the notification of property updates from a nacos server.

2019-06-26 05:07:45.701 ERROR 23164 --- [99-9d32359662c7] c.a.nacos.client.config.impl.CacheData   : [fixed-192.168.66.100_8848-ad23a4bc-49f7-4767-9499-9d32359662c7] [notify-error] dataId=ds.properties, group=DEFAULT_GROUP, md5=3291c3174cb4401d1a4d01981a5ca91b, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@3c58d8e1 tx=null

@EventListener is from org.springframework.context.event.EventListener .

Type: *bug report*

### Describe what happened (or what feature you want)

cannot get updated properties

### Describe what you expected to happen

get the notification event or property refreshment event.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
config client: windows 10
config server: linux, standalone
using spring-cloud-alibaba

**Comment by lovegames** [comment]
这个问题解决了吗,我也遇到了

**Comment by shengyayun** [comment]
It occurred in nacos-client 2.0.3.

`[com.alibaba.nacos.client.Worker.longPolling.fixed-xx.xx.xxx.xx_8848-babb7859-4214-4529-8da8-b253d1e75639,c.a.n.c.c.i.CacheData,,] [fixed-xx.xx.xxx.xx_8848-babb7859-4214-4529-8da8-b253d1e75639] [notify-error] dataId=gateway.yaml, group=DEFAULT_GROUP, md5=606d3f4d1a61a0a6c568400ed7fdcf05, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@26c1531 tx=null`

**Comment by SmallSeals** [comment]
我也遇到了，请问有解决吗？

**Comment by shengyayun** [comment]
> 我也遇到了，请问有解决吗？

我当时是因为频繁调用spring-boot-actuator的健康检查接口，降低了调用频率就没出现了。
