### ISSUE TITLE
There have a error and something are not clear

### ISSUE THREAD

**Issue by h3l** [alibaba/nacos#144]
* As the pic below, there miss a ```^``` 
![image](https://user-images.githubusercontent.com/1664952/47280728-5cd0b980-d60a-11e8-9476-a810aa8bb7e4.png)

* it will be better to document the post body type. json form and so on?
* the listen port is not the same. 8848 8080 ?
* the example can be more Runnable.
replace some like below
    ```
    http://serverIp:8080/nacos/v1/cs/configs/listener

    POST request body data:

    Listening-Configs=dataId^2group^2contentMD5^2tenant^1
    ```
    with 
    ```
    curl -x POST xxxxxxxx
    ```

**Comment by h3l** [comment]
@xuechaos

**Comment by yanlinly** [comment]
U are  right, I  fix it  today. thx !

the port is changed to 8848.

**Comment by h3l** [comment]
Maybe you guys can put the document on github, so others can contribute

**Comment by yanlinly** [comment]
It is under nacos-group. I fixed it. 
https://github.com/nacos-group/nacos-group.github.io

**Comment by h3l** [comment]
very nice
