### ISSUE TITLE
How does cluster mode roll updates

### ISSUE THREAD

**Issue by stalary** [alibaba/nacos#1440]
I want to upgrade the cluster, how to operate, turn off one upgrade one？

**Comment by nkorange** [comment]
> I want to upgrade the cluster, how to operate, turn off one upgrade one？

Basically yes. Another thing you have to check is the upgrade version. If you upgrade to Nacos 1.0.0+, you must make sure that your local server version is not smaller than 0.8.0.

**Comment by stalary** [comment]
thanks
