### ISSUE TITLE
How to configure various parameters in capacity management

### ISSUE THREAD

**Issue by lanpay-lulu** [alibaba/nacos#1445]
## Issue Description
As we know, Nacos has each single content size limits to 100k. There are also other capacity limit checks. How can we config these values?

**Comment by nkorange** [comment]
All configurable parameters are [here](https://nacos.io/zh-cn/docs/system-configurations.html), configuration content size cannot be configured currently.

**Comment by nkorange** [comment]
But you are welcome to contribute for adding new configurable parameters.
