### ISSUE TITLE
cmdb project can't start alone

### ISSUE THREAD

**Issue by Luckylau** [alibaba/nacos#1448]
the SpringBoot cmdb project can't start alone ,because  of  maven resource excludes
application.properties
it should be canceled.

**Comment by nkorange** [comment]
Which exact project did you find error? Please paste the link of it.

**Comment by Luckylau** [comment]
the project nacas-cmdb

**Comment by nkorange** [comment]
> the project nacas-cmdb

What error did you encounter? I can run this project in my local computer.

**Comment by Luckylau** [comment]
when I start CmdbApp alone, because the pom.xml of nachos-cmdb project excludes application.properties ,it cause "Could not resolve placeholder 'nacos.cmdb.dumpTaskInterval' in value ${nacos.cmdb.dumpTaskInterval}".  By the way , I can start NamingApp alone,  because the pom.xml of nacos-naming project do not exclude application.properties.

**Comment by nkorange** [comment]
> when I start CmdbApp alone, because the pom.xml of nachos-cmdb project excludes application.properties ,it cause "Could not resolve placeholder 'nacos.cmdb.dumpTaskInterval' in value ${nacos.cmdb.dumpTaskInterval}". By the way , I can start NamingApp alone, because the pom.xml of nacos-naming project do not exclude application.properties.

Which version of Nacos are you using?

**Comment by Luckylau** [comment]
> > when I start CmdbApp alone, because the pom.xml of nachos-cmdb project excludes application.properties ,it cause "Could not resolve placeholder 'nacos.cmdb.dumpTaskInterval' in value ${nacos.cmdb.dumpTaskInterval}". By the way , I can start NamingApp alone, because the pom.xml of nacos-naming project do not exclude application.properties.
> 
> Which version of Nacos are you using?

master, the newest.

**Comment by nkorange** [comment]
Set the property:
```properties
nacos.cmdb.dumpTaskInterval=3600
```
and retry.
