### ISSUE TITLE
Data missing if Notifier failed to call the listener

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1463]
```ServiceManager``` relies on the Callback of ```RecordListener``` to update its data. But if the Notifier failed to call the listener, the data will never get the second chance to be updated unless there is another write operation to this data which will trigger another notify message.

**Comment by IanCao** [comment]
i'll sove it

**Comment by KomachiSion** [comment]
This problem should has been fixed in new version by refactor to `NotifyCenter`, Please upgrade to new version.
