### ISSUE TITLE
nacos-console can provide cluster delete button

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#1469]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

nacos-console can provide cluster delete button

**Comment by cafechen** [comment]
Has this issue been fixed? If not, I wanna solve it.

**Comment by chuntaojun** [comment]
> Has this issue been fixed? If not, I wanna solve it.

If you'd like, we'd be glad to

**Comment by cafechen** [comment]
Ok, I will solve it.

**Comment by cafechen** [comment]
@i will solve it@
