### ISSUE TITLE
beat error for ephemeral instances with same serviceName, groupName, ip and port but with different clusterName

### ISSUE THREAD

**Issue by Li-JH** [alibaba/nacos#1470]
## Issue Description
bug report

### Describe what happened (or what feature you want)
env: nacos clusters of 3 servers
i create 3 ephemeral instances with same serviceName, groupName, ip and port but with different clusterName. However, i found out that only one instance could send the beat and others become unhealthy and are deleted when timed out. 
reason: map dom2beat build the key using the combination of serviceName, groupName, ip and port, causing all the instances have the same key, with the latter beatinfo overriding the former.

### Describe what you expected to happen
please help to solve this problem.

**Comment by chuntaojun** [comment]
I'll fix it

**Comment by chuntaojun** [comment]
already fix in 1.0.2， just wait
