### ISSUE TITLE
start nacos server failed when I use jenv

### ISSUE THREAD

**Issue by RojerAlone** [alibaba/nacos#1472]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)

 I use jenv to manage my JDK version, and when i use `sh startup.sh -m standalone` command to start nacos, I got the `nohup: 无法运行命令'/home/rojeralone/.jenv/bin/java': 没有那个文件或目录` log, and the start up command is `/home/rojeralone/.jenv/bin/java ...`

It's absolutely wrong JAVA_HOME.

### Tell us your environment

The nacos version is latest and I use zsh, the jenv setting is 
```
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
```

**Comment by RojerAlone** [comment]
how about getting the java home by 
`java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home'` ?

I found it in [stackoverflow](https://stackoverflow.com/questions/1117398/java-home-directory-in-linux/42706056#42706056), and I update the `startup.sh` file, like below:

```
...
else
    JAVA_PATH=`dirname $(readlink -f $(which javac))`
    if [ "x$JAVA_PATH" != "x" ]; then
      export JAVA_HOME=`dirname $JAVA_PATH 2>/dev/null`
    fi
    if [ ! -e "$JAVA_HOME/bin/java" ]; then
      java_home=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | xargs echo | sed -n 's/java\.home \= \([^._]*\)/\1/p')
      export JAVA_HOME=$(dirname $java_home)
    fi
  fi
  if [ -z "$JAVA_HOME" ]; then
        error_exit "Please set the JAVA_HOME variable in your environment, We need java(x64)! jdk8 or later is better!"
  fi
...
```
then I run the start command, it works. How about this solution? If you think it's ok, I can send a pr.

ps: the computer which I start failed is Ubuntu 16.04，and I use the original `startup.sh` to start nacos successfully on macos yesterday.

**Comment by nkorange** [comment]
It's recommended that you export your JAVA_HOME manually. The JAVA_HOME detection logic in startup.sh cannot cover all circumstances.

**Comment by RojerAlone** [comment]
I got it, thks.
