### ISSUE TITLE
It is recommended to do the trim operation when configuring the new dataid on the Nacos web page.

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/nacos#1479]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
新建配置，输入dataid时 dataid为复制的，黏贴后前面存在空格但未注意，新建配置完成后，程序拉取配置失败，查看配置列表未发现问题，查询数据库发现dataid前存在空格

### Describe what you expected to happen
dataid写入数据库前做trim操作，排除复制黏贴的空格

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos-server 1.0.1

**Comment by nkorange** [comment]
这个我感觉在控制台进行空格提醒比较好

**Comment by zhaoyuguang** [comment]
![image](https://user-images.githubusercontent.com/10150229/61117323-d24a2600-a4c8-11e9-80fd-eac2f355edd8.png)
只是在`Data ID` 处加输入的串 前后有空格的提醒 足够么？  还是`配置内容` 也加一下提醒呢

**Comment by MagakiReimu** [comment]
> ![image](https://user-images.githubusercontent.com/10150229/61117323-d24a2600-a4c8-11e9-80fd-eac2f355edd8.png)
> @MagakiReimu @nkorange 只是在`Data ID` 处加输入的串 前后有空格的提醒 足够么？ 还是`配置内容` 也加一下提醒呢

配置内容有格式颜色提示所以不需要
data-id有空格染色提示或者直接处理掉空格都可以

**Comment by nkorange** [comment]
> ![image](https://user-images.githubusercontent.com/10150229/61117323-d24a2600-a4c8-11e9-80fd-eac2f355edd8.png)
> @MagakiReimu @nkorange 只是在`Data ID` 处加输入的串 前后有空格的提醒 足够么？ 还是`配置内容` 也加一下提醒呢

配置内容不需要提醒的
