### ISSUE TITLE
Spring.cloud.nacos.config.namespace=public setting is invalid

### ISSUE THREAD

**Issue by jasoncw** [alibaba/nacos#1506]
跟踪代码发现com.alibaba.nacos.client.config.impl.ClientWorker中的getServerConfig方法使用tenant=public去发起http请求而不是namespace=public，导致返回404。
nacos-client所有的版本都有此问题。

**Comment by nkorange** [comment]
This namespace will be converted to tenant in NacosConfigService

**Comment by cookzhang** [comment]
遇到了同样问题，你应该是用的 命名空间名称 
换成  命名空间ID
