### ISSUE TITLE
 It is recommended that the shutdown.sh script close only the nodes in the current directory, not all nodes.

### ISSUE THREAD

**Issue by Comven** [alibaba/nacos#1507]
When Nacos is started in cluster mode。If we want to update one of the node. the shutdown.sh will kill all nodes, it make us have to manually close nacos or modify the shutdown. sh script。So It is recommended that the shutdown.sh script update to close only the nodes in the current directory, not all nodes.

**Comment by rushsky518** [comment]
@i will solve it@
?

**Comment by rushsky518** [comment]
@i will solve it@
??
