### ISSUE TITLE
Configuration files do not support Chinese characters？

### ISSUE THREAD

**Issue by xingkong6648** [alibaba/nacos#1509]
*bug report*
Configuration files do not support Chinese characters？If I write Chinese characters at my Nacos , it will report error in the starting log，and those Chinese characters doesn't work~
please check and fix this，Thank you very much!

**Comment by nkorange** [comment]
Which configuration file did you edit?

**Comment by xingkong6648** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi，thanks for reply! My problem is illustrated in the figure:
    
        
            
        
    
    
        
        

        
    

    On 7/11/2019 16:45，Fury Zhu<notifications@github.com> wrote： 


Which configuration file did you edit?

**Comment by nkorange** [comment]
You figure is not shown.
