### ISSUE TITLE
The node in cluster mode runs abnormally.

### ISSUE THREAD

**Issue by liyueforever** [alibaba/nacos#1512]
我使用了三台主机来测试集群，我的cluster.conf配置为：
192.168.0.72:8848
192.168.0.73:8848
192.168.0.74:8848
之后我分别启动三台机器的nacos-server，然后我遇到了下面的问题:
没有被选举为leader的两个节点都发生了异常，异常信息如下：
![image](https://user-images.githubusercontent.com/46366155/60877552-a3397780-a270-11e9-8b90-9011c40f43c6.png)
我能确保我的nacos配置中没有出现过110这个IP地址。同时我测试过Nacos0.9、1.0、1.1，结果都是一样。

环境：
CentOS 7.1.1503
JAVA 8

**Comment by rushsky518** [comment]
InetUtils.getSelfIp()

**Comment by liyueforever** [comment]
> nacos 取 ip 的代码在 InetUtils 中，配置文件的 ip 要和这个对应

**Comment by liyueforever** [comment]
> nacos 取 ip 的代码在 InetUtils 中，配置文件的 ip 要和这个对应

非常感谢您的回复。
在三台机器的Nacos配置文件application.properties中我都使用了nacos.inetutils.ip-address这个配置项来指定本机IP，同时在cluster.conf中三个Nacos的配置也是相同。
发现这个问题之后我的第一反应也是可能哪里配置错了，但是我反复检查过配置文件，三个Nacos中均没有出现过110这个IP，同时我也不懂在配置文件中没有出现过110这个IP的情况下，这个IP是怎么获取到的？并且这个问题只会发生在没有被选举为leader的两个节点上。
期待您的回复！

**Comment by rushsky518** [comment]
> > nacos 取 ip 的代码在 InetUtils 中，配置文件的 ip 要和这个对应
> 
> 非常感谢您的回复。
> 在三台机器的Nacos配置文件application.properties中我都使用了nacos.inetutils.ip-address这个配置项来指定本机IP，同时在cluster.conf中三个Nacos的配置也是相同。
> 发现这个问题之后我的第一反应也是可能哪里配置错了，但是我反复检查过配置文件，三个Nacos中均没有出现过110这个IP，同时我也不懂在配置文件中没有出现过110这个IP的情况下，这个IP是怎么获取到的？并且这个问题只会发生在没有被选举为leader的两个节点上。
> 期待您的回复！

你的问题好了吗？没有环境，复现不了，不好定位

**Comment by liyueforever** [comment]
> > > nacos取ip的代码在InetUtils中，配置文件的ip要和这个对应
> > 
> > 
> > 非常感谢您的回复。
> > 在三台机器的NACOS配置文件application.properties中我都使用了nacos.inetutils.ip地址这个配置项来指定本机IP，同时在cluster.conf中中三个NACOS的配置也是相同。
> > 发现这个问题之后我的第一反应也是可能哪里配置错了，但是我反复检查过配置文件，三个NACOS中均没有出现过110这个IP，同时我也不懂在配置文件中没有出现过110这个IP的情况下，这个IP是怎么获取到的？并且这个问题只会发生在没有被选举为领导者的两个节点上。
> > 期待您的回复！
> 
> 你的问题好了吗？没有环境，复现不了，不好定位

您好，问题还没有解决，我现在打算把之前的服务器实例销毁掉，之后再开三台新的实例来进行测试。因为配置已经确认了没有问题，那我觉得可能是环境的问题吧 但是我也不能认定 只能测试一下了

**Comment by liyueforever** [comment]
您好@rushsky518，我这边有了新的发现，希望对问题的定位有一些帮助。
我使用了新的实例来搭建集群环境，但结果跟之前一样：
没有被选举为leader的两个节点的naming-server日志文件中都输出了这个错误IllegalStateException: can not find peer: 192.168.0.110:8848。还是那句话我能够确保我的Nacos配置文件中没有出现110这个ip地址。
之后我下载了nacos的源码期望发现问题的原因，我通过异常栈信息找到了错误抛出的位置：
首先是/raft/vote接口被调用，然后从request对象中获取vote参数，之后调用RaftCore.receivedVote进行下一步处理
![image](https://user-images.githubusercontent.com/46366155/61278471-d935a900-a7e6-11e9-807c-4d8e4f419bca.png)
在RaftCore.receivedVote进行了IP地址验证的处理，之后就抛出了日志文件中的异常
![image](https://user-images.githubusercontent.com/46366155/61278518-ece10f80-a7e6-11e9-8fa0-85618cd7bf8a.png)
接着我基本上确定了应该是request中这传递的参数值可能是错误的，为了验证我的结论我使用了arthas这个工具监控程序来查看request对象中的参数信息(这里不得不赞一下 这个工具真的挺好用^_^)，之后证实了我的结论：这个错误是内部流程中接口调用时参数传递错误的问题（如果我的理解有误，请您指正）
![image](https://user-images.githubusercontent.com/46366155/61278997-d8e9dd80-a7e7-11e9-9ac7-29cf4c265fbe.png)
所以还是需要向您明确一下这个IP是怎么获取到的？期望您的再次回复~
附上一些额外的日志信息（截取自leader节点 192.168.0.74）
![image](https://user-images.githubusercontent.com/46366155/61280497-8fe75880-a7ea-11e9-9809-173c8843a879.png)
![image](https://user-images.githubusercontent.com/46366155/61280625-c7560500-a7ea-11e9-96b9-5d84784adec7.png)

**Comment by rushsky518** [comment]
加个钉钉？

**Comment by liyueforever** [comment]
> 加个钉钉？

可以，我的钉钉号：liyueforever

**Comment by liyueforever** [comment]
问题已经解决，非常感谢 @rushsky518 的帮助

**Comment by codexinfeng** [comment]
how to solve ti @liyueforever

**Comment by liyueforever** [comment]
> how to solve ti @liyueforever

我的这个问题是因为110这台机器上在早前部署了一个nacos且配置里有写72这个地址，所以110机器上的nacos会请求72来拉票，而当时我是不知道110机器上有nacos程序这件事所以才会有这个issue。
现在再看这个3年前的问题也是当时的经验不足，执着于自己部署的nacos集群做各种配置检查和版本测试，却没想到过去看一下110机器上进程的情况。
