### ISSUE TITLE
PostConstruct excute order cause BasicDataSourceServiceImpl init error.

### ISSUE THREAD

**Issue by Liqingnan** [alibaba/nacos#1513]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
Reason: BasicDataSourceServiceImpl::init may excute before PropertyUtil::init. 
Problem: I start nacos with "-Dnacos.standalone=true" and "spring.datasource.platform=mysql", but nacos still run on derby.
![nacos-bug](https://user-images.githubusercontent.com/23392703/60880263-eb0ecd80-a275-11e9-9ed2-cbaccb518cf8.PNG)
### Describe what you expected to happen
nacos uses standalone mode and run on mysql. 

### How to reproduce it (as minimally and precisely as possible)

1. debug com.alibaba.nacos.Nacos
2. set VM options:-Dnacos.standalone=true
3. add spring.datasource.platform=mysql in applicatiion.properties

### Tell us your environment
windows 8.1, jdk 11

**Comment by nkorange** [comment]
The latest code already fixed this problem.

**Comment by Liqingnan** [comment]
> The latest code already fixed this problem.

已经找到问题了, 是某次提交删除了DynamicDataSource对PropertyUtil的注入, 导致执行顺序不受控. 谢谢.
