### ISSUE TITLE
Several questions about using nacos1.1.0

### ISSUE THREAD

**Issue by lion000** [alibaba/nacos#1518]
满怀希望的过来用起了nacos，不可否认配置中心确实很好用，这里是提问题的地方，就不过分夸赞了，现在开始吐槽注册中心了。
不知道是我不会用，还是程序真有bug，几点设计的真心反人类。单例就不说了，不可能在生产环境使用，聊聊集群吧。
1、3节点，2主1备，主备的区别在于物理机房不同，但是网络是完全打通的，三台机器ping telnet完全没问题。那么问题来了，当3节点都启动之后，看start.out打出来的日志完全没问题，然后使用控制台和open api来确定集群状态，和是否有leader节点。首先不知道其他使用者有没有发现，**open api的返回值都是正确的，但是控制台的节点管理的数据，多刷几遍，数据时有时无崩溃吗？而且可以感觉集群状态其实是不对的**。
2、接着查看日志，一看这么多的日志文件，有点崩溃，毕竟免费嘛，那就一个个找，后面发现3个日志很关键。naming-server.log naming-ephemeral.log access_log.2019-07-10.log。然后tail -f这三个，**会发现各种不同的问题，虽然是INFO级别的日志！！！**先不管这些问题细节，但其实我认为这种集群状态肯定是不正确的。比如经常看到的：
![image](https://user-images.githubusercontent.com/16664111/60935138-767e7200-a2fb-11e9-842b-f12a7b381ea7.png)
不知道出于什么考虑，这是info级别的日志，但是亲测，只要集群中有节点是这种状态，服务是不可能注册成功的。
其实到这里，已经很恶心了，没有明确的地方会给出明确提示说集群的状态其实是有问题的，或者是至少有节点是不健康的吧！需要人为的一个个的看日志去分析。open api对于集群的检测其实是无效的。
3、服务注册问题。当然，在集群状态不正确的时候，肯定无法注册的。但是！直接报错503 server is down now。。。。这个错 真的看吐了。。。而且基本根据日志，基本无法分析问题的原因。。。
唉。。。先吐槽这么多吧，准备换回eureka先保证服务稳定了。
要是有大佬关注并可以解决问题，需要啥环境信息都可以提供。

**Comment by nkorange** [comment]
加我微信:nkorange，我给你解决

**Comment by Comven** [comment]
nacos的日志输出的确应该优化一下，都发布了好多个版本了，日志方面的问题还是有不少，昨儿我也提了一个日志优化方面的issue #1510

**Comment by nkorange** [comment]
> nacos的日志输出的确应该优化一下，都发布了好多个版本了，日志方面的问题还是有不少，昨儿我也提了一个日志优化方面的issue #1510

嗯嗯，感谢你的建议，我们会跟进你提的问题。

**Comment by lion000** [comment]
昨天经过大佬的指点，发现3节点集群 docker启动，集群报错，是因为3台服务器的时间不对， 有1台比其他两台慢了10分钟导致的，后面使用时间服务器同步3个节点的之后，集群启动之后，状态稳定。
强烈建议：
在搭建nacos集群的文档中，明确说明，开始工作一定要同步所有节点的时间，毕竟，这个问题在日志里面没有明确的描述，而一般排查问题，也不会想到是服务器时间不同步导致的吧。。。

**Comment by nkorange** [comment]
We will fix it in #1529
