### ISSUE TITLE
The subscriber list is not displayed correctly

### ISSUE THREAD

**Issue by Comven** [alibaba/nacos#1519]
现在将nacos-server和nacos-client都更新到1.1.0版本，首先发现的是nacos-server端应用名称栏不显示任何数据，其次客户端版本中只显示了v1.0.0和1.0.1，而我更新到的1.1.0版本的nacos-client显示的是1.0.1
![image](https://user-images.githubusercontent.com/8464801/60937253-51413200-a302-11e9-967d-47c2d42c06d9.png)

**Comment by ly641921791** [comment]
@i will solve it@

**Comment by ly641921791** [comment]
@Comven I am using the 1.1.0 version of the client did not find the client version display abnormality, can you look at the pom.xml file

**Comment by chuntaojun** [comment]
> @Comven I am using the 1.1.0 version of the client did not find the client version display abnormality, can you look at the pom.xml file

you client version is 1.1.0 in console subscribe page?

**Comment by ly641921791** [comment]
> > @Comven我用1.1.0版本的客户端没找到客户端版本显示异常，可以看一下pom.xml文件
> 
> 你的客户端版本在控制台订阅页面是1.1.0？

Yes

**Comment by chuntaojun** [comment]
> > > @Comven我用1.1.0版本的客户端没找到客户端版本显示异常，可以看一下pom.xml文件
> > 
> > 
> > 你的客户端版本在控制台订阅页面是1.1.0？
> 
> Yes

我建议你在pr中，将版本的查询改用使用这个类： com.alibaba.nacos.common.util.VersionUtils，然后在common包中创建resource文件夹，根据这个类的逻辑，使得版本不再代码中写死

**Comment by ly641921791** [comment]
> > > > @Comven我用1.1.0版本的客户端没找到客户端版本显示异常，可以看一下pom.xml文件
> > > 
> > > 
> > > 你的客户端版本在控制台订阅页面是1.1.0？
> > 
> > 
> > Yes
> 
> 我建议你在pr中，将版本的查询改用使用这个类： com.alibaba.nacos.common.util.VersionUtils，然后在common包中创建resource文件夹，根据这个类的逻辑，使得版本不再代码中写死

Ok, I will do this.
