### ISSUE TITLE
#1352 Private network can't load fonts, favicon

### ISSUE THREAD

**Issue by anpu2018** [alibaba/nacos#1520]
#1352 Private network can't load fonts, favicon
In fact, this problem has not been completely solved. Under the service list label, the new service and the pop-up box still have the word ali cdn. It is doubtful whether it has been tested before pr.

**Comment by nkorange** [comment]
@loadchange Please follow up this problem.

**Comment by nkorange** [comment]
@anpu2018 does this problem occur only in 'service list' page?

**Comment by anpu2018** [comment]
This is the case in my business scenario at present, but I don't think it's advisable to use this method of analyzing problems. We should sort out the problems from beginning to end, which will only lead to repetitive work.

**Comment by rushsky518** [comment]
![image](https://user-images.githubusercontent.com/20531420/60958363-cfb8c680-a338-11e9-9add-75aa8e1dbadf.png)
？

**Comment by anpu2018** [comment]
@rushsky518 yes
