### ISSUE TITLE
how to register a service with groupName? not cluster-name.

### ISSUE THREAD

**Issue by ghost0224** [alibaba/nacos#1528]
how to register a service with groupName? not cluster-name.

**Comment by nkorange** [comment]
With nacos-client, it is available. See [NamingService](https://github.com/alibaba/nacos/blob/develop/api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java) and [Java SDK tutorial](https://nacos.io/zh-cn/docs/sdk.html)

But with Dubbo or Spring Cloud, it relies on Dubbo and Spring Cloud extend their implementation to support invoking the new methods of Nacos client.
