### ISSUE TITLE
Visit http://localhost:8848 HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by maxid** [alibaba/nacos#1531]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
when visit http://localhost:8848 default redirect to http://localhost:8848/nacos/index.html
    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addRedirectViewController("/", "/nacos/index.html").setStatusCode(HttpStatus.PERMANENT_REDIRECT);
    }

### How to reproduce it (as minimally and precisely as possible)

1. local start nacos server
2. open chrome
3. visit http://localhost:8848

### Tell us your environment
macos 10.14.5 + chrome

**Comment by chuntaojun** [comment]
启动时会在控制台打印地址，你可以在那里看到
