### ISSUE TITLE
The Doc has some errors

### ISSUE THREAD

**Issue by sky5454** [alibaba/nacos#1532]
In LINUX  
"sh startup.sh -m standalone" is wrong. because [[]] is bash's feature, so it should be 
```bash
bash startup.sh -m standalone
```

And where should I put it into a dir? The nacos doesn't support "root" or "sudo".

**Comment by jici2016** [comment]
是这样的，https://nacos.io/zh-cn/docs/quick-start.html 里面的第三部分3.启动服务器
使用sh就会报错，用bash就可以了，感谢帮助了我

**Comment by nkorange** [comment]
![image](https://user-images.githubusercontent.com/4593375/64398597-fe80be00-d097-11e9-88ba-22b76340b101.png)

文档已修正，感谢反馈。
