### ISSUE TITLE
Add a button to hide the empty service on console

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#1535]
The empty service with no instance should not be displayed by default.

**Comment by zhaoyuguang** [comment]
I'd like to try that

**Comment by zhaoyuguang** [comment]
@nkorange  Is it better to make a selection box?
![image](https://user-images.githubusercontent.com/10150229/61116027-4cc57680-a4c6-11e9-8699-3af5e7a9d6e8.png)

**Comment by nkorange** [comment]
@zhaoyuguang Thank you for your contribution. But maybe a switch is enough.

**Comment by zhaoyuguang** [comment]
OK
