### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by anpu2018** [alibaba/nacos#1537]
Many logs and code still have version numbers of 1.0.1, not 1.1.0.

**Comment by nkorange** [comment]
Update to nacos-client 1.1.1 please, we fixed it.

**Comment by anpu2018** [comment]
> 请更新到nacos-client 1.1.1，我们修复了它。

nacos see

> Update to nacos-client 1.1.1 please, we fixed it.

I am referring to the logs and comments contained in the nacos-server.jar service.

**Comment by anpu2018** [comment]
> Update to nacos-client 1.1.1 please, we fixed it.

I am referring to the logs and comments contained in the nacos-server.jar service.

**Comment by nkorange** [comment]
> > Update to nacos-client 1.1.1 please, we fixed it.
> 
> I am referring to the logs and comments contained in the nacos-server.jar service.

Which log or comment are you referring to?

**Comment by anpu2018** [comment]
> > > Update to nacos-client 1.1.1 please, we fixed it.
> > 
> > 
> > I am referring to the logs and comments contained in the nacos-server.jar service.
> 
> Which log or comment are you referring to?

bin/logs/access_log

**Comment by nkorange** [comment]
> > > > Update to nacos-client 1.1.1 please, we fixed it.
> > > 
> > > 
> > > I am referring to the logs and comments contained in the nacos-server.jar service.
> > 
> > 
> > Which log or comment are you referring to?
> 
> bin/logs/access_log

The version printed in access log is obtained from Nacos client request header. So the root cause is Nacos client 1.1.0 carries the wrong request header and Nacos client 1.1.1 fixed it.
