### ISSUE TITLE
upgrade to 1.1.0, request the same data-id but got different result

### ISSUE THREAD

**Issue by jiaoyilun** [alibaba/nacos#1539]
my env is K8s built by referring to the k8s guide manual of the official website， and upgrade to v1.1.0.
steps:
1. change a values
2. run a test to request the same data-id  50 times ,but i got the different result
3. the next day , i run the test again ,the result is the same
ps: 
1.is it a cache?     
2.i try to rollback the version to v1.0.1, i can get the same result

**Comment by jiaoyilun** [comment]
![image](https://user-images.githubusercontent.com/1704805/61110090-04ec2280-a4b9-11e9-8a80-68f2d21fdb25.png)

**Comment by nkorange** [comment]
What is the content of configuration in your database?

**Comment by jiaoyilun** [comment]
> What is the content of configuration in your database?

json ,   but i only print the length of the content when i test

**Comment by nkorange** [comment]
> > What is the content of configuration in your database?
> 
> json , but i only print the length of the content when i test

Which is the correct one? 12118 or 11868? Or none of them?

**Comment by jiaoyilun** [comment]
> > > What is the content of configuration in your database?
> > 
> > 
> > json , but i only print the length of the content when i test
> 
> Which is the correct one? 12118 or 11868? Or neither of them?

修改之前是11868，修改后是12118，所以结果应该都是12118才是对的，我想表达的是，我改完配置之后，循环请求这个配置，交替轮流返回的是修改前和修改后的数据，结果不一致
