### ISSUE TITLE
can't download release package from aws

### ISSUE THREAD

**Issue by breakenknife** [alibaba/nacos#1546]
![image](https://user-images.githubusercontent.com/12994391/61181398-9c3bac00-a658-11e9-9afa-0a76342df8e8.png)

aws is not stateable to some city of china (I'm in ChengDu ). Can you put one in domestic? eg:aliyun.

aws对于国内用户非常不稳定,某些地区甚至无法访问, 建议发布包在国内再放一份.

**Comment by nkorange** [comment]
这个建议不错。目前你可以clone工程来自行打包，打包命令参考[BUILDING](https://github.com/alibaba/nacos/blob/develop/BUILDING).

**Comment by nkorange** [comment]
最新版本可以在Nacos社区钉钉群（群号：21708933）文件中下载。
