### ISSUE TITLE
Does Nacos have the ability to monitor changes like Apollo's ConfigChangeEvent?

### ISSUE THREAD

**Issue by xugejunllt** [alibaba/nacos#1550]
![image](https://user-images.githubusercontent.com/32354631/61199151-73c2b900-a70f-11e9-8615-cdd2d53d3849.png)
the receiveConfigInfo give me the full configiration,but I want to know if a configuration item has changed, not the full configuration.Just like apollo's ConfigChangeEvent:
![image](https://user-images.githubusercontent.com/32354631/61198925-91435300-a70e-11e9-8488-e3a465e7f21a.png)

**Comment by xugejunllt** [comment]
sorry,the order of the pictures is reversed.

**Comment by rushsky518** [comment]
@i will solve it@
