### ISSUE TITLE
The configuration center is configured with spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, and the value can be obtained through the @NacosValue annotation, but the configuration does not take effect.

### ISSUE THREAD

**Issue by jianghexing** [alibaba/nacos#1551]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jianghexing** [comment]
1,开发环境 Windows10；1.8jdk nacos启动后，配置客户端配置 spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration 去除springboot对mybatis的强交验；配置了但是没有生效；键值对可以获取到配置信息的值；但是没有去除对mybatis的交验



------------------ 原始邮件 ------------------
发件人: "Nacos Collaborate Robot"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 下午3:43
收件人: "alibaba/nacos"<nacos@noreply.github.com>; 
抄送: "pull"<1152587347@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [alibaba/nacos] The configuration center is configured withspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,and the value can be obtained through the @NacosValue annotation, but theconfiguration does not take effect. (#1551)



 
您好@jianghexing，我们在问题中检测到非英文字符。此评论是来自@ nacos-bot的自动翻译，以帮助其他用户理解此问题。
 我们鼓励您用英语描述您的问题，这对其他用户更友好。
  
配置中心配置了spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration，该值可以通过@NacosValue注释获得，但配置不生效。
 
问题说明
 
键入：错误报告或功能请求
 
描述发生了什么（或你想要什么功能）
 
描述您期望发生的事情
 
如何重现它（尽可能最小和精确）
  

 

 

  
告诉我们您的环境
 
还有什么我们需要知道的吗？
 
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by chuntaojun** [comment]
You are using nacos - spring - the boot this project?
