### ISSUE TITLE
how nacos build serverAddr should be in nacos Documentation.

### ISSUE THREAD

**Issue by haochencheng** [alibaba/nacos#1556]
This is a suggestion for user simple to use nacos  。
The problem I am having is i dont Know how the serverAddr i will be used 。
when i cant get config in nacos I have to  see the source code ，i feel sad 😭
Know that  when I saw this in nacos   oh my god ！！！😳
```java
 String[] serverAddrsArr = serverAddrsStr.split(",");
            for (String serverAddr: serverAddrsArr) {
                if (serverAddr.startsWith(HTTPS) || serverAddr.startsWith(HTTP)) {
                    serverAddrs.add(serverAddr);
                } else {
                    String[] serverAddrArr = serverAddr.split(":");
                    if (serverAddrArr.length == 1) {
                        serverAddrs.add(HTTP + serverAddrArr[0] + ":" + ParamUtil.getDefaultServerPort());
                    } else {
                        serverAddrs.add(HTTP + serverAddr);
                    }
                }
            }
            serverUrls = serverAddrs;
```
if i could see the logic in the quick start  or in the log，i will be happy 😀

**Comment by nkorange** [comment]
https://nacos.io/zh-cn/docs/system-configurations.html You can refer to this document.

![image](https://user-images.githubusercontent.com/4593375/64399765-4d305700-d09c-11e9-9651-b5318cf848cc.png)
