### ISSUE TITLE
code quality

### ISSUE THREAD

**Issue by anpu2018** [alibaba/nacos#1561]
It has been a long time since I followed the product of nacos. At present, I am responsible for the cluster of 10+ machines. I have learned a lot about the two days by reading the source code to learn design ideas.
The first is about code quality concerns: the current nacos source is full of many ancient implementations, such as many tools are written around 2015. Second, nacos code quality does not meet the requirements of Alibaba programming specifications This makes people wonder if the developer used the p3c plugin to scan before pr.
Secondly: When the open source work of eureka 2.0 came to an end, I personally thought that Consul would become the first choice in the field of registration center. The reason why I chose nacos was because of the trust of Alibaba middleware, such as rocketmq, dubbo and so on. The programmer has brought a lot of traversal, thank you very much, but now it seems that in a short time nacos can not shoulder this major responsibility, while paying attention to the open source community, more and more bugs are discovered.
Suggestion: The strength of a person is limited. I hope that in the future version of nacos ga, focus on the quality of the code, similar to this code comment https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/support/spring/FastJsonHttpMessageConverter.java is really hard to be a mature open source product. It is undeniable that there are a lot of code in nacos source code without comments.

**Comment by nkorange** [comment]
代码质量已成立专项：https://nacos.io/zh-cn/docs/feature-list.html 欢迎共建。
