### ISSUE TITLE
NacosNamingService could by created by any 'namespace' that is not existed in nacos-server

### ISSUE THREAD

**Issue by jimgreat** [alibaba/nacos#1562]
NacosNamingService does not check the usability of namespace .
The 'namespace' that is not existed in nacos-server would be post to  nacos-server .
The ServiceManager in server side also does not check the 'namespace' .

You can register an instant successfully however there is nothing in the console page.

**Comment by JackSun-Developer** [comment]
This problem seems duplicate with #4134
