### ISSUE TITLE
@NacosConfigListener  when spring init,the remote config can't be read

### ISSUE THREAD

**Issue by szd1993** [alibaba/nacos#1563]
` @NacosConfigListener(dataId = "taskjob.json", groupId = "tpsp", converter = TaskScheduleConverter.class)
    public void setTaskJobBOList(List<TaskJobConfigDTO> taskJobList) {
        TpspLogger.applicationInfoLog(logger, "update task-info.....start");
        TpspLogger.applicationInfoLog(logger, "nacos.dataId[=taskjob.json].groupId[=tpsp]", taskJobList);
        //update task
        updateTaskList(taskJobList);
        TpspLogger.applicationInfoLog(logger, "update task-info.....end");
    }`

this is my code, when spring init，the method don't run to read config;
but, when i change the config on the nacos-admin, it works.
when i change the config ,the listener works and inits  tasklist

**Comment by szd1993** [comment]
my nacos-config is a json array

**Comment by szd1993** [comment]
i got it, <nacos-spring-context.version>0.2.2-RC1</nacos-spring-context.version>  success
<nacos-spring-context.version>0.3.0</nacos-spring-context.version>   failed

**Comment by chuntaojun** [comment]
建议将此issue转移到spring-nacos-project这个项目中

**Comment by chuntaojun** [comment]
> i got it, <nacos-spring-context.version>0.2.2-RC1</nacos-spring-context.version> success
> <nacos-spring-context.version>0.3.0</nacos-spring-context.version> failed

nacos-spring-project you tried the new version?

**Comment by chuntaojun** [comment]
There is no question of the latest version
