### ISSUE TITLE
pubulic config by nacos api

### ISSUE THREAD

**Issue by cttftu** [alibaba/nacos#1564]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos version: v1.1.0
environment: windows server 2016 datacenter
I started the nacos, then i try public config by nacos api,but the response is nothing and the config is not insert into the nacso system.
nacos api:/nacos/v1/cs/configs
在windows下启动v1.1.0版本的nacos后，通过postman工具发布配置这个接口发布一个新的值，但是response无任何反应，nacos系统也没有接收到刚刚发布的配置。

**Comment by nanamikon** [comment]
看一下返回码是什么，  然后具体的请求参数也发一下
