### ISSUE TITLE
The bug encountered when upgrading nacos to mysql8

### ISSUE THREAD

**Issue by Nuoka** [alibaba/nacos#1565]
The latest source code for nacos has been adapted to mysql8.x, but if you use mysql8.x, the "db.url.0" configuration parameter of the "nacos-default.properties" file of the source code should also be adapted. If you still use the configuration parameters, the startup process will report an error.

## Issue Description

Type: bug report

### How to reproduce it (as minimally and precisely as possible)

1. Change the mysql driver version of the parent file "pom.xml" to "8.0.11"
2. Run the Nacos.java file。
3. Watch the console

### Anything else we need to know?
  When the "BasicDataSourceServiceImpl.java" file reads the mysql connection, it is recommended to determine whether it is the latest mysql version by the driver, so as to select the correct "db.url.0" parameter.
  In addition, it should prompt the user to select the correct mysql connection in a production environment.

**Comment by nkorange** [comment]
You don't have to modify pom.xml, just put the drive jar into directory {nacos.home}/plugins/mysql/
