### ISSUE TITLE
Sentinel cluster point link statistics problem

### ISSUE THREAD

**Issue by andysofan** [alibaba/nacos#1566]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

![image](https://user-images.githubusercontent.com/5241152/61422482-7c4d0680-a93e-11e9-93e0-1ec942432039.png)

### Describe what you expected to happen

原始的接口为：
@RequestMapping(value = "/echo/{str}", method = RequestMethod.GET)
    public String echo(@PathVariable("str") String str) {

但是实际 在【Sentinel 簇点链路】中是按照实际url统计的；这种rest接口如果有多个；那么在统计中会几何倍数增长！！

**Comment by sczyh30** [comment]
You may refer to https://github.com/alibaba/Sentinel/issues/286

**Comment by nkorange** [comment]
This is a [Sentinel](https://github.com/alibaba/Sentinel) issue.
