### ISSUE TITLE
Configuration management suggestions for adding new functions!

### ISSUE THREAD

**Issue by gamestarxie** [alibaba/nacos#1568]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

It is recommended that a new function be added to query directly the entire Key/Value table for each namespace:
(建议新增个功能直接查询每个namespace的全部的Key/Value的表格：)

| key | value | Data Id | Group | Application |
| -- | -- | -- | -- | -- |
| spring.datasource.druid.url | jdbc:mysql://127.0.0.1:3306/xxx | testapp | DEFAULT_GROUP |  |
| ... | ... | ... | ... | ... |

**Comment by nkorange** [comment]
你这个表格里，key和dataID是什么关系？

**Comment by gamestarxie** [comment]
> 你这个表格里，key和dataID是什么关系？

在你们现有的数据结构里，一个dataID对应的是一整个配置文件（yml/Properties/...）,所以在一个dataID里会有多个key/value，对应到我这个表格里就是dataID+key就可以确定唯一的一条配置数据
