### ISSUE TITLE
Nacos integrated zipkin exception

### ISSUE THREAD

**Issue by junjun888** [alibaba/nacos#1570]
## Issue Description

Type: *nacos 整合 zipkin,一直报错*

### Describe what happened (or what feature you want)
不报错

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/25007573/61447913-7b3ec800-a984-11e9-9098-dcdffc55883f.png)

![image](https://user-images.githubusercontent.com/25007573/61447952-8d206b00-a984-11e9-888e-db6910ad2f60.png)

### How to reproduce it (as minimally and precisely as possible)

1. 部署 nacos server 到一台服务器，不能和 zipkin 同一台 （我是 nacos server 部署到服务器，zipkin 部署在本地，才能重现，如果都部署到本地 则无法重现）
2. 配置 nacos ， 和 zipkin 客户端
 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
# zipkin + sleuth
spring.zipkin.base-url=http://127.0.0.1:9411/
# 采样比率, 生产环境得调整成 0.1 以免影响性能
spring.sleuth.sampler.probability=1.0
3. 启动

### Tell us your environment

springboot 2.0.4.RELEASE
springcloud Finchley.SR1
nacos 0.2.1.RELEASE
zipkin 和 boot 版本一致
![image](https://user-images.githubusercontent.com/25007573/61448272-2a7b9f00-a985-11e9-9703-5170e0846e47.png)

**Comment by nkorange** [comment]
Refer to these [issues](https://github.com/alibaba/nacos/issues?utf8=%E2%9C%93&q=zipkin) please.
