### ISSUE TITLE
config data not exist

### ISSUE THREAD

**Issue by hw-loading** [alibaba/nacos#1571]
[

## Issue Description
When i creat a new namespace and add a group, can't get the config in customize namespace
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Hi,  When the config under the default namespace "public", it works well. But when I create a new namespace “dev” and add a new group "DEV_GROUP",data id is "test.yaml", i use open api url “http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=test.yaml&group=DEV_GROUP” return msg is "config data not exist".

### Describe what you expected to happen
return the real cofig data

### How to reproduce it (as minimally and precisely as possible)

1. create a new namespace "dev"
2. create a new config in "dev",dateId is "test.yaml" ,group is "DEV_GROUP"
3. user open api interface to check data
  url= http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=test.yaml&group=DEV_GROUP

### Tell us your environment
JDK8，nacos 1.1.0, chrome browser

**Comment by wangyingwei001** [comment]
朋友 我也遇到了这个bug  你现在解决了吗

**Comment by daishenghao** [comment]
You have to add a pram in your url like this:
http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=test.yaml&group=DEV_GROUP&&tenant=`your customize namespace id`

**Comment by nkorange** [comment]
@daishenghao gave the correct answer.
