### ISSUE TITLE
NacosFactory.createConfigService not support namespace?

### ISSUE THREAD

**Issue by klaus-pd** [alibaba/nacos#1573]
## Issue Description
When I use NacosFactory createConfigService create addListener, found the namespace to create the data cannot be loaded, but under the public to create the same data can be loaded. I have configured the specified namespace in the configuration file that starts with springboot

<img width="535" alt="image" src="https://user-images.githubusercontent.com/9957221/61506483-d7512d00-aa14-11e9-8250-6684cdcdae96.png">
<img width="407" alt="image" src="https://user-images.githubusercontent.com/9957221/61506659-69593580-aa15-11e9-836a-cdf63ee2ede9.png">
<img width="837" alt="image" src="https://user-images.githubusercontent.com/9957221/61506674-7544f780-aa15-11e9-8601-4ae9147e4ba8.png">

### Describe what happened (or what feature you want)
If different namespaces are used to separate different environments, either in the Java way or in the application.yaml configuration, the data loading should get the configuration file under the specified namespace

### Tell us your environment
springboot 2.1.6
springcloud Finchley.SR2
springcloudalibaba 0.9.0
nacos 1.0.0
### Anything else we need to know?

**Comment by daishenghao** [comment]
You can call another constructor of `NacosConfigServer` whose param is `java.util.Properties`, and the properties can set your custom namespace.

**Comment by nkorange** [comment]
@daishenghao has given the correct answer.
