### ISSUE TITLE
Springcloud uses nacos to persist the sentinel configuration to get the nacos configuration API: /nacos/v1/cs/configs returns an exception: config data not exist

### ISSUE THREAD

**Issue by wangyingwei001** [alibaba/nacos#1580]
获取nacos配置的API:/nacos/v1/cs/configs
请求方式：Get
返回异常 为：config qdata not exist

**Comment by daishenghao** [comment]
This API works.So You can debug this code`com.alibaba.nacos.config.server.controller.ConfigServletInner#doGetConfig`, then you will know why it return an exception.

**Comment by wangyingwei001** [comment]
I started to install Version 1.1.1 of nacos, this API has problems, then I changed to version 1.1.0, this API is no problem, the original version of the problem.

**Comment by nkorange** [comment]
The result of this API depends on if you have created the configuration or not.

**Comment by wangyingwei001** [comment]
Do you have your own well-integrated code that works perfectly?




| |
柠七
|
|
邮箱：svip66666666666@126.com
|

签名由 网易邮箱大师 定制

On 07/30/2019 01:02, Fury Zhu wrote:

The result of this API depends on if you have created the configuration or not.

**Comment by nkorange** [comment]
Follow this guide please:https://nacos.io/zh-cn/docs/sdk.html
