### ISSUE TITLE
Nacos service serverAddr smartly add port 8848 ? 

### ISSUE THREAD

**Issue by 15629116378** [alibaba/nacos#1581]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I used the domain name to access the strange discovery and could not access it. Finally I found out that I added a 8848?

### Describe what you expected to happen
Don't add "smart"

### How to reproduce it (as minimally and precisely as possible)

  Will the 8848 port be added by using the domain name access via the nginx reverse proxy?

### Tell us your environment

Mac OS _ JDK 8
### Anything else we need to know?

**Comment by 15629116378** [comment]
People who use nacos are not too stupid, I hope you don't need "smart", we want flexibility.

**Comment by nkorange** [comment]
You can specify the port to 80 if you don't want 8848.

**Comment by Quarria** [comment]
@nkorange 我也遇到了这个问题，当我在客户端配置地址中心的域名时，启动就会报错，发现在请求地址中心的域名时，自动的添加了8080这个端口号，可我不需要他自动添加端口号。。请问怎么才能让请求不自动添加端口号？

**Comment by MCJIBA** [comment]
Do it like this.
https://github.com/alibaba/nacos/issues/1637#issuecomment-517372971
