### ISSUE TITLE
nacos ui clone configuration prompt "please select the configuration to export"

### ISSUE THREAD

**Issue by xiaok0928** [alibaba/nacos#1583]
我在新建的命名空间中将配置信息克隆到其他命名空间中时, 点击克隆 弹出提示"请选择要导出的配置", 并且有的时候没有选择配置也可以克隆, 提示成功但实际结果却没有成功

**Comment by xiaok0928** [comment]
nacos version 1.1.0

**Comment by KeRan213539** [comment]
第一个问题是提示文字错误造成,已修改
第二个问题是这个列表组件支持跨页选择,由于切换namespace只是刷新了列表数据,之前的选择还在, 将修改为切换namespace时清空已选择的,切换分页不清空(保留跨页选择)
