### ISSUE TITLE
Import Properties Error

### ISSUE THREAD

**Issue by YSS-1987** [alibaba/nacos#1585]
Import Propertis File  Error :
No legitimate configuration was read, please check the imported data file

**Comment by YSS-1987** [comment]
nacos version 1.1.0

**Comment by nkorange** [comment]
Please check the file format described in [document](https://nacos.io/zh-cn/blog/nacos%201.1.0.html).

**Comment by YSS-1987** [comment]
![图片](https://user-images.githubusercontent.com/53175815/63583312-5a920f80-c5cd-11e9-85f7-a7f7bcc9021c.png)

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
