### ISSUE TITLE
endpoint is blank

### ISSUE THREAD

**Issue by zcoNick** [alibaba/nacos#1586]
## Issue Description

Type: *bug report*

### Dependency 依赖
![image](https://user-images.githubusercontent.com/23350189/61627128-9a559680-acb1-11e9-8964-816a07862afb.png)
 ### Configuration & Exception 配置和报错
![image](https://user-images.githubusercontent.com/23350189/61627213-c7a24480-acb1-11e9-8fef-76d1eb6cff78.png)
### -Dparameter 这是发现application.yml中写那两个=false不管用后分别尝试的-D方式
![image](https://user-images.githubusercontent.com/23350189/61627733-10a6c880-acb3-11e9-871f-0e81959a001a.png)

### Description 中文描述
依赖没有用默认的nacos-client-1.0.0改成了当前最新的1.1.-版本；
才开始没有在application.properties中加isUseEndpointParsingRule=false和nacos.use.endpoint.parsing.rule=false；后来报错，跟代码到com.alibaba.nacos.client.config.impl.ServerListManager.initEndpoint(Properties)发现有取endpoint值，查了下endpoint干啥的，发现暂时可能用不到，故欲禁用endpoint。
尝试1：在application.properties中添加isUseEndpointParsingRule=false和nacos.use.endpoint.parsing.rule=false，无效；
尝试2：Eclipse的Arguments中添加-D参数（com.alibaba.nacos.api.SystemPropertyKeyConst.IS_USE_ENDPOINT_PARSING_RULE的注释上写了可以用-D传参），无效。

### Description with Google Translate
The dependency has not been changed to the current latest 1.1.- version with the default nacos-client-1.0.0;
I didn't start adding isUseEndpointParsingRule=false and nacos.use.endpoint.parsing.rule=false in application.properties; then I got an error and found the code to com.alibaba.nacos.client.config.impl.ServerListManager.initEndpoint(Properties) Have the value of the endpoint, check the endpoint, and found that it may not be used temporarily, so you want to disable the endpoint.
Try 1: Add isUseEndpointParsingRule=false and nacos.use.endpoint.parsing.rule=false in application.properties, invalid;
Try 2: Add the -D parameter to the Arguments of Eclipse (com.alibaba.nacos.api.SystemPropertyKeyConst.IS_USE_ENDPOINT_PARSING_RULE is written on the comment can be passed with -D), invalid.

### Question 我的问题
How to solve this exception or disable endpoint 怎么解决报错或禁用Endpoint

**Comment by nanamikon** [comment]
配置了 spring.cloud.nacos.config.server-addr 就不需要配endpoint了， 可以debug看看为啥serverAddr没有设置进去， sdk的代码是这样的

![image](https://user-images.githubusercontent.com/2010632/61920540-81d4cd00-af8c-11e9-89dc-c333aaee75f0.png)

**Comment by zcoNick** [comment]
> 配置了 spring.cloud.nacos.config.server-addr 就不需要配endpoint了， 可以debug看看为啥serverAddr没有设置进去， sdk的代码是这样的
> 
> ![image](https://user-images.githubusercontent.com/2010632/61920540-81d4cd00-af8c-11e9-89dc-c333aaee75f0.png)

貌似找到原因了，serverAddr是不是得放在bootstrap.properties/yml里面，我是放在application里面的（看Configuration那个截图是application.properties），一开始没注意到，然后把全部移到bootstrap里面就好了。
看了下源码，ServerListManager是在NacosConfigBootstrapConfiguration里面的逻辑中的创建的，所以应该是加载顺序的问题，放在application里面的读不到，不知道对不对啊。

**Comment by zcoNick** [comment]
@nanamikon 麻烦看下是不是这个问题，是的话就可以关issue了，感谢！

**Comment by nanamikon** [comment]
和spring cloud config的机制一样的，  需要在最前面初始化，  那就关了哦

**Comment by nkorange** [comment]
Please read this [article](https://nacos.io/zh-cn/docs/namespace-endpoint-best-practices.html) to further understand how to use endpoint rule.
