### ISSUE TITLE
Nacos advice

### ISSUE THREAD

**Issue by adrklang** [alibaba/nacos#1590]
Excuse me, can you achieve yml and coexistence properties file, because I now have a demand, is I had a project using dataids pull a called global - common. The properties of the global configuration file do, now I opened a project, using the way of yml configuration, so I'm configuration file - the extension for yml, but now I want to use global - common. The properties configuration, cannot be injected into the corresponding attributes, I tried to configure file-extension: yml,properties, and NacosException would appear. If it is not suitable, it can be pulled down, but the corresponding properties in it cannot be used

**Comment by nkorange** [comment]
麻烦中文描述下。

**Comment by adrklang** [comment]
你好，问题已经解决了，谢谢
