### ISSUE TITLE
The nacos as a configuration center startup priority in the spring boot project

### ISSUE THREAD

**Issue by fayechenlong** [alibaba/nacos#1597]
我在springboot项目中使用nacos作为dubbo的注册中心，nacos同时也作为配置中心，我在使用中发现一个问题，nacos配置中心的启动优先级是落后于spring boot的一些功能的，比如springboot的自带的数据源，启动优先级也落后于dubbo，导致dubbo等配置无法使用nacos进行管理，nacos配置中心启动优先级不应该是最高的么？

**Comment by zhengweiye** [comment]
我也遇到了，不懂怎么解决

**Comment by chuntaojun** [comment]
我将此issue移动到nacos-boot项目中

https://github.com/nacos-group/nacos-spring-boot-project/issues/37

**Comment by fayechenlong** [comment]
官方说 fixed in nacos-config-spring-boot-starter version 0.2.2 @zhengweiye 等这个版本吧

**Comment by yljgo** [comment]
测试了下0.2.3还是有问题

**Comment by chuntaojun** [comment]
> 测试了下0.2.3还是有问题

按wiki操作了嘛

**Comment by DaC1989** [comment]
虽然解决了，但可能有点小问题：
设置参数 nacos.config.bootstrap.enable=true不起作用
但是 nacos.config.bootstrap.log.enable=true 就可以。但我看文档，这个参数是显示日志是否打印的

**Comment by chuntaojun** [comment]
> 版本0.2.3,可能有点小问题：
> 设置参数 nacos.config.bootstrap.enable=true不起作用
> 但是 nacos.config.bootstrap.log.enable=true 就可以。但我看文档，这个参数是显示日志是否打印的

确实，因为dubbo的启动时机确实太早了，这个日志级别的加载时机可以解决问题

**Comment by kocall** [comment]
spring cloud 怎么解决呢
