### ISSUE TITLE
Support RBAC (i.e something like AWS RAM)  for configuration and service management

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#160]
Security and Access Control is a very important non-functional  ability for every product，for configuration management there are many configuration has sensitive messages，such as
AK/SK, token, identities, datasource username/password etc,  to protect all of the Resources in Nacos,
we should support RBAC for internal resources.

To do this，we can

- Support a built-in RBAC solution
- As Nacos is very care about the "adaptive to public cloud", so we'd better to support RAM(i.e. AWS RAM or Aliyun RAM or others RAM)
- Support integrating with 3rd party RBAC products 

For example:

ROLE - USER -  USER-GROUP - Resource Access Control - Action(READ, WRITE)

Service & Configuration & Ops & API  etc all are resources...

**Comment by eonezhang** [comment]
we also need local support for access control.
and we expect every app that need to get configuration from nacos server could be assigned an appid and access token. access control could be identified by those info(appid & access token)

**Comment by ruohone** [comment]
权限控制建议： 
    1.用户信息可以新建表存数据库。
    2.粒度到命名空间就可以了，配置精确到dataID。

**Comment by jinf666** [comment]
建议分阶段实现权限控制：
1.先简单实现类似于dubbo admin管理控制台的权限方式，能保证大家都安全的使用nacos做配置管理。否则有心用也不敢用于正式环境。
2.逐步实现完善的权限管理功能，满足不同颗粒度的需要。

**Comment by nope-J** [comment]
1. 可以先出一版简单的账号密码登录；
2. 后面建议添加一些权限管理，比如发布配置者可以选择哪些用户可以查他发布的配置，哪些用户可以修改。再对服务注册做类似的权限管理。

**Comment by yyt701** [comment]
nacos作为基础公共服务，安全认证还是相当重要的：
1. 控制台最基本的需要有登录功能，否则访问入口一旦暴露，很可怕；
2. login account 最好要有角色、权限可分配； 公共服务，某个账号创建的信息应该只能有该账号与管理员可以读写； 其他账号不能写，是否可读应该是可选的；
3. 其实控制台权限控制应该是通用的；
期待中，如果有这个功能更放心上生产了；

**Comment by irusist** [comment]
我们生产环境，目前有部分应用的启动配置和开关类配置使用了nacos，希望增加以下功能
 * 支持钉钉扫码登录
 *  可以配置用户与应用的关联
 *  对应用；或者针对dataId，group配置规则进行权限的控制

**Comment by zhouwenqi** [comment]
这个功能确实需要完善，前期可以先控制命名空间的权限。调研了一个2个星期，准备全切过来的，整个项目组讨论到这里了卡了，如果用一个环境的nacos管理测试、uat、生产环境的配置的话，肯定要权限区分，不然很吓人。。。

**Comment by rushsky518** [comment]
最终状态：按 namespace, group 隔离控制台用户的读、写权限

**Comment by nkorange** [comment]
Will be tracked in #1105
