### ISSUE TITLE
The nacos1.0.0 cluster deployment service is not registered, and the stand-alone deployment is normal.

### ISSUE THREAD

**Issue by tiandihai** [alibaba/nacos#1600]
【nacos1.0.0  、 spring-boot-starter-parent 2.1.0.RELEASE  、spring-cloud-dependencies Greenwich.SR2 、 spring-cloud-alibaba-dependencies  0.9.0.RELEASE】这是我说使用的相关版本信息。单机部署的时候服务注册与调用都正常。但是三个节点集群部署的时候，我的服务启动后可以看到“nacos registry, orderservice 192.168.6.213:5051 register finished”这个日志打印，但是有的时候从console页面的服务列表看不到服务，也调不通，有的时候可以从三个节点的其中移到两个节点看到服务，其他的节点看不到服务。
       我的集群节点分别在192.168.3.203:8848、 192.168.3.204:8848 、192.168.3.207:8848。之前一直是使用配置中心的，一切正常，现在想用一下服务注册，但是就出现如上所述问题。

**Comment by nkorange** [comment]
你的三台Server的时间戳是否同步？

**Comment by tiandihai** [comment]
现在三台Server的时间戳大概相差1s左右，然后服务注册看起来正常了。但是我在后台页面把集群下的某个实例点击“下线”，从页面上面看该实例状态还是正常的，不过接口调用是调不到那个下线的实例了。不知道是不是一个显示的bug。

**Comment by nkorange** [comment]
页面上不会删除这个实例的，只是会把状态改成“下线”。

**Comment by tiandihai** [comment]
我知道，正常情况下页面上面“下线”状态的颜色会变。我的意思就是页面上面没有改成“下线”状态。而且我手动点击“下线”按钮，虽然按钮上面的状态变了。但是颜色没有变。
![image](https://user-images.githubusercontent.com/6039066/62127982-fcdc1180-b305-11e9-8b9d-a72e0b2062bf.png)

![image](https://user-images.githubusercontent.com/6039066/62128012-0feee180-b306-11e9-9019-0229e2292344.png)

**Comment by tiandihai** [comment]
哦，是我理解的问题。谢了
