### ISSUE TITLE
why i cann't define  namespaceId when i add one

### ISSUE THREAD

**Issue by hikaru2025** [alibaba/nacos#1606]
in  the local nacos config-center, when i create a new namespace, there are only two options

name  & description
when i confirm,there will be a new namespaceId.
is that mean first i need to create a namespaceId,and then set this id to the project configuration?
can i first define a namespaceId,and set it in the new namespace?

**Comment by nkorange** [comment]
Namespace ID is not editable now, we are considering to support it.

**Comment by zhaoyuguang** [comment]
@hikaru2025 @nkorange 我不是很明白 具体的具体的需求是什么 现在不就是这样么？
I don't understand very well. What are the specific needs? Isn’t that the case now?
![image](https://user-images.githubusercontent.com/10150229/62341288-54040100-b515-11e9-92d2-f5f6253409b5.png)

**Comment by zhaoyuguang** [comment]
I understand that just add an input box. Can users define their own namespaceID?

**Comment by Patrick0308** [comment]
Does  namespaceId have  to be UUID ? @nkorange

**Comment by nkorange** [comment]
> I understand that just add an input box. Can users define their own namespaceID?
> 我理解只是增加一个输入框 可以用户自己定义namespaceID么

是这样的。

**Comment by nkorange** [comment]
> Does namespaceId have to be UUID ? @nkorange

不用，只要全局唯一就行

**Comment by chchfee** [comment]
@i will solve it@

**Comment by chchfee** [comment]
@i will solve it@

**Comment by chchfee** [comment]
@ready to close@

**Comment by nkorange** [comment]
@chchfee I guess PR #2192 is related to this issue. Next time you should add issue id in your commit message, So the commit and the issue can be related to each other.

**Comment by chchfee** [comment]
> @chchfee I guess PR #2192 is related to this issue. Next time you should add issue id in your commit message, So the commit and the issue can be related to each other.

OK

**Comment by nkorange** [comment]
Already fixed in #2163
