### ISSUE TITLE
How dubbo+nacos uses namespace isolation and discovery services

### ISSUE THREAD

**Issue by hong-huang** [alibaba/nacos#1607]
springCloud+nacos可以使用命名空间隔离服务。dubbo+nacos如何实现此功能：通过命名空间隔离服务

**Comment by powerttt** [comment]
I have encountered this confusion in these days.

**Comment by hong-huang** [comment]
How did you solve it?

**Comment by nkorange** [comment]
Your can set the namespace with this configuration:
```xml
<dubbo:registry address="nacos://127.0.0.1:8848?namespace=xxxxxx" />
```

**Comment by Python-IBM** [comment]
> Your can set the namespace with this configuration:
> 
> ```
> <dubbo:registry address="nacos://127.0.0.1:8848?namespace=xxxxxx" />
> ```

It's no use doing that. The Nacos background does not display the services under this namespace. What's my problem?
