### ISSUE TITLE
nacos address startup.bat probleam

### ISSUE THREAD

**Issue by liqing201104** [alibaba/nacos#1609]
nacos-address-server-1.1.0.tar.gz\bin\startup.bat 启动脚本中指定的jar包不正确
`set "JAVA_OPT=%JAVA_OPT% -Dloader.path=%BASE_DIR%/plugins/health -jar %BASE_DIR%\target\nacos-server.jar"`

**Comment by liangyangtao** [comment]
**是带来新问题了吗？ 还是我打开方式不对？**

```
git clone https://github.com/alibaba/nacos.git
cd nacos/
mvn -Prelease-nacos clean install -U 
```

如图启动，路径多了个引号

![image](https://user-images.githubusercontent.com/5389893/66994669-36037100-f100-11e9-8139-8295652149e7.png)

**Comment by liangyangtao** [comment]
@pbting @nkorange 
指定jar包名称后可用
![image](https://user-images.githubusercontent.com/5389893/66996749-d9a25080-f103-11e9-99ce-9b943c42f4e3.png)
