### ISSUE TITLE
About the nacos access log file does not have a history of saving history

### ISSUE THREAD

**Issue by cel105302** [alibaba/nacos#1613]
The log generation path is nacos-server/nacos/bin/logs/access_log.xxxx-xx-xx.log
If there is no configured history of the saved history, the disk will be full if it takes a long time.
![image](https://user-images.githubusercontent.com/32325588/61940372-dfd2d600-afc7-11e9-9e41-b29267088eb1.png)

**Comment by nkorange** [comment]
This log is the standard access log of Spring Boot, unfortunately Spring Boot doesn't provide any options to configure the max history of this log now. For the options that are available currently you can refer to [this](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html).

An alternative solution is that you can set a crontab task to clean this log.

**Comment by cel105302** [comment]
Yes, it is already handled this way.
