### ISSUE TITLE
NamingService#getServicesOfServer() method return data is empty but count ！= 

### ISSUE THREAD

**Issue by Maijh97** [alibaba/nacos#1619]
```java
   NamingService naming = NamingFactory.createNamingService("127.0.0.1:8848");
        ListView<String> servicesOfServer = naming.getServicesOfServer(0, Integer.MAX_VALUE);
```
servicesOfServer.data is empty but servicesOfServer.count != 0

**Comment by pierre94** [comment]
I have same problem.How do youmake it?

**Comment by pierre94** [comment]
Ohm…… PageNo must start from 1.  
@nkorange   I suggest that the official documentation of this function should be added

https://nacos.io/zh-cn/docs/sdk.html
