### ISSUE TITLE
Nacos1.1.0 servce Offline but nacos The service instance was not cleared

### ISSUE THREAD

**Issue by Maijh97** [alibaba/nacos#1622]
nacos 集群模式在升级1.1.0 版本后，发现 服务实例停止之后，nacos 并没有剔除， 还有，建议文档描述一下 nacos server 版本升级。 谢谢

**Comment by nkorange** [comment]
升级指南参考[文档](https://nacos.io/en-us/blog/nacos%201.1.0.html)，请问你是怎么停止实例的？

**Comment by Maijh97** [comment]
我升级是直接替换nacos-server.jar，没有把plugins目录下文件删除掉，不知道是不是这个影响的， 直接kill 掉服务的

**Comment by Maijh97** [comment]
我重新试了一下，发现删除plugins目录下的文件，服务实例监测就可以了。感谢你的回答！
