### ISSUE TITLE
/nacos/v1/ns/catalog/serviceList 401 error

### ISSUE THREAD

**Issue by caixiaoqiang** [alibaba/nacos#1626]
I've already logged in, but when I click on the list of services, I jump back to the login screen !

Request URL: http://127.0.0.1:8848/nacos/v1/ns/catalog/serviceList?startPg=1&pgSize=10&keyword=&namespaceId=
Request Method: GET
Status Code: 401 
Remote Address: 127.0.0.1:8848
Referrer Policy: no-referrer-when-downgrade

Query String Paramters :
startPg: 1
pgSize: 10
keyword: 
namespaceId:

**Comment by nkorange** [comment]
Where did you get this URL? This URL is not supported in Nacos.
