### ISSUE TITLE
The weight of the nacos service does not take effect. How can it take effect?

### ISSUE THREAD

**Issue by tiandihai** [alibaba/nacos#1628]
【nacos1.0.0  、 spring-boot-starter-parent 2.1.0.RELEASE  、spring-cloud-dependencies Greenwich.SR2 、 spring-cloud-alibaba-dependencies  0.9.0.RELEASE】
这是我所使用的相关版本。服务注册上去以后，配置了服务实例的权重，但是调用的时候还是走的轮询，权重的设置没有效果。请问，要怎么样才能生效了呢？

**Comment by cdy1996** [comment]
你是怎么配置的权重? 我印象中`ribbon`默认是没有带权重的轮询算法的. 另外你需要监听`nacos`配置的生效或者启用`springcloudconfig`的自动刷新.

**Comment by tiandihai** [comment]
我直接在后台的页面上面配置的
![image](https://user-images.githubusercontent.com/6039066/62193990-872a8100-b3ab-11e9-9563-48c28f218854.png)
这里配置之后是不能自动生效，是还需要自定义ribbon策略吗？

**Comment by cdy1996** [comment]
> 我直接在后台的页面上面配置的
> ![image](https://user-images.githubusercontent.com/6039066/62193990-872a8100-b3ab-11e9-9563-48c28f218854.png)
> 这里配置之后是不能自动生效，是还需要自定义ribbon策略吗？

对, `springcloud-ribbon`默认是没有权重的轮询算法的. 另外这个`nacos`的权重属性不一定在`springcloud` 有用到, 我司是使用元信息配置的权重+自定义`ribbon`策略
