### ISSUE TITLE
page size in the configuration list is not displayed.

### ISSUE THREAD

**Issue by xiaok0928** [alibaba/nacos#1629]
this is bug,
page size in the configuration list is not displayed.
nacos version: 1.1.0

**Comment by xiaok0928** [comment]
v 1.1.3 same too

**Comment by xiaok0928** [comment]
![image](https://user-images.githubusercontent.com/22540410/63310805-ae32fd80-c32e-11e9-8370-54623fae6462.png)

**Comment by xiaok0928** [comment]
![image](https://user-images.githubusercontent.com/22540410/63310825-bab75600-c32e-11e9-8c1c-03728436d8fc.png)
pagesize not displayed

**Comment by nkorange** [comment]
Do you mean page size cannot be edited?

**Comment by xiaok0928** [comment]
> Do you mean page size cannot be edited?

yes, and not displayed other options

**Comment by KomachiSion** [comment]
New version should fixed this problem.
