### ISSUE TITLE
The role of the failover file

### ISSUE THREAD

**Issue by wolfdriver** [alibaba/nacos#1631]
During the process of looking at the code, there are two file paths in the `LongPollingRunnable`.
 - Failover path: LOCAL_SNAPSHOT_PATH/serverName_SystemId/data/config-data/group/dataId
 - Snapshot path: LOCAL_SNAPSHOT_PATH/envName_SystemId/snapshot/group/dataId

During the file read and write process, it seems that only the snapshot path is used, but the write operation on the failover path is not found, but in the long polling service of `LongPollingRunnable `, is the failover path file detected? 
```
private void checkLocalConfig(CacheData cacheData) {
        // ....
        File path = LocalConfigInfoProcessor.getFailoverFile(agent.getName(), dataId, group, tenant);
       	if (!cacheData.isUseLocalConfigInfo() && path.exists()) {
       	}
       	if (cacheData.isUseLocalConfigInfo() && !path.exists()) {
	}

	if (cacheData.isUseLocalConfigInfo() && path.exists()
        	&& cacheData.getLocalConfigInfoVersion() != path.lastModified()) {
	}
```
Want to know what the role of the failover file is.

**Comment by H-hao** [comment]
@nkorange  你好，能解答一下吗，我也在这卡住了。

**Comment by nkorange** [comment]
这两个目录只是容灾用，正常情况下没有用的。

**Comment by H-hao** [comment]
> 这两个目录只是容灾用，正常情况下没有用的。

谢谢回复。
看了下代码 Snapshot 会在每次更新配置的时候生成，并且在服务挂掉的时候使用 Snapshot  的配置。
但是 Failover 的文件是在什么时候产生呢？好像没看到相关的代码。

**Comment by nkorange** [comment]
> > 这两个目录只是容灾用，正常情况下没有用的。
> 
> 谢谢回复。
> 看了下代码 Snapshot 会在每次更新配置的时候生成，并且在服务挂掉的时候使用 Snapshot 的配置。
> 但是 Failover 的文件是在什么时候产生呢？好像没看到相关的代码。

手动生成的。

**Comment by H-hao** [comment]
> > > 这两个目录只是容灾用，正常情况下没有用的。
> > 
> > 
> > 谢谢回复。
> > 看了下代码 Snapshot 会在每次更新配置的时候生成，并且在服务挂掉的时候使用 Snapshot 的配置。
> > 但是 Failover 的文件是在什么时候产生呢？好像没看到相关的代码。
> 
> 手动生成的。

哦哦，好的。谢谢

**Comment by zhuSilence** [comment]
> > > 这两个目录只是容灾用，正常情况下没有用的。
> > 
> > 
> > 谢谢回复。
> > 看了下代码 Snapshot 会在每次更新配置的时候生成，并且在服务挂掉的时候使用 Snapshot 的配置。
> > 但是 Failover 的文件是在什么时候产生呢？好像没看到相关的代码。
> 
> 手动生成的。

您好，容灾文件是手动生成的吗？ 我这边最近服务调用失败，跟踪了一下源码，发生本地磁盘有个容灾文件，但是我并没有手动生成过这个文件。查看了一下 'FAILOVER_SWITCH = "00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00";' 该常量的引用情况并没有找到相关生成的代码，实在好奇，还望解惑一下，谢谢。
