### ISSUE TITLE
Nacos connect to server with domain default to add port 8848 causing error

### ISSUE THREAD

**Issue by RekaDowney** [alibaba/nacos#1637]
Does the Nacos client have to communicate with the server using ip:port? When I use the ip:port corresponding to the domain name, the client connection Nacos is added with port 8848 by default, causing the connection to be rejected. Is there a way for the client to communicate with the server using domain and port 80?

Nacos客户端是不是必须使用ip:port的方式与服务端进行通信？当我使用域名反代对应的ip:port后，客户端连接Nacos默认被加上了8848端口，导致连接被拒绝。有没有办法让客户端使用domain和80端口与服务端进行通信。

比如：10.1.123.12:8848 被反代为 nacos.rr.me，这时候客户端通信时变成了 nacos.rr.me:8848

**Comment by MCJIBA** [comment]
I did have the same question.My solution is to user Nginx to do the redirect.
Nginx setting:
```
server	{
	listen	80;
	#sub domain
	server_name  nacos.ithinkcry.cn;
	location /nacos/ {
                #aliyun ECS server inner ip address 172.26.88.76
		proxy_pass http://172.26.88.76:18848/nacos/;
	}
	location / {
		  proxy_pass http://172.26.88.76:18848/nacos/;
	}
}
```

Nacos server setting(application.properties)
```
server.contextPath=/nacos
server.servlet.contextPath=/nacos
server.port=18848
```
SpringCloud project setting (application.yml)
```
spring:
  application:
    name: nacosprovider
  cloud:
    nacos:
      discovery:
        server-addr: nacos.ithinkcry.cn:80
```
