### ISSUE TITLE
/nacos/v1/cs/health/checkers 401 error

### ISSUE THREAD

**Issue by leiiiihuang** [alibaba/nacos#1638]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I want to check the health check class that is currently in effect.

### How to reproduce it (as minimally and precisely as possible)

1. Http://127.0.0.1:8848/nacos/v1/cs/health/checkers. Accessing this path will report a 401 error and will not get the correct result.
2. 
3. 

### Tell us your environment

window nacos 1.0.1

**Comment by nkorange** [comment]
You are probably trying to access ```Http://127.0.0.1:8848/nacos/v1/ns/health/checkers```?
