### ISSUE TITLE
Chinese or English / Chinese Or English?

### ISSUE THREAD

**Issue by seaoverall** [alibaba/nacos#1639]
## change the comment from Chinese to English

@pbting
pbting committed on Jun 4
 
Merge pull request #1290 from chuntaojun/develop  …

@nkorange
nkorange committed on Jun 4
  
## change the comment from Chinese to English

@pbting
pbting committed on Jun 4
 
Merge pull request #1303 from IanCao/master  …

@nkorange
nkorange committed on Jun 4
  
Merge pull request #1309 from IanCao/fixbug2  …

@nkorange
nkorange committed on Jun 4
  
## 1. 注释改成中文  …

@pbting
pbting committed on Jun 4

**Comment by nkorange** [comment]
What's your point?
