### ISSUE TITLE
Nacos Config can not load xml file in nacos by “classpath:XXX.xml”?

### ISSUE THREAD

**Issue by blackbk** [alibaba/nacos#1642]
env: nacos 1.0.1 、springboot2.1.6、spring cloud G

I  uploaded logback config file “logback-spring.xml” to nacos config，and update properties to add "logging.config=classpath:logback-spring.xml". But I get ERROR when I restart Application,  ERROR is "**java.io.FileNotFoundException: class path resource [logback-spring.xml] cannot be resolved to URL because it does not exist**".
So, how can I get "logback-spring.xml" from nacos config? Thanks very much.

**Comment by KANLON** [comment]
how to fix it?please can tell me ?

**Comment by sunnywa** [comment]
这个该如何实现呢？
