### ISSUE TITLE
Some Problems and Suggestions in Using Nacos

### ISSUE THREAD

**Issue by SaY983763** [alibaba/nacos#1644]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

1. After the start of Nacos service, many log files have been created under the logs folder, some of which are very large. It is very inconvenient to modify the nacos-logback.xml file. It is suggested to simplify and remove the useless log output.

nacos服务启动后，在logs文件夹下创建了很多日志文件，有些日志文件又很大，通过修改nacos-logback.xml文件十分不方便，建议精简，去掉无用日志输出；

2. The use of web pages is very inconvenient. Each page can only display 10. When there are many leaking services, it is inconvenient to view them. It is suggested to make a drop-down form of one page.

web页面使用非常不方便，每页只能显示十个，暴漏的服务非常多的时候，查看不方便，建议做成一页下拉形式；

3. Web Page - Service List - Details Page, whether you click on the top right corner or the top left corner to return, will not return to the original list page, but back to the home page;

web页面-服务列表-详情页，不管是点击右上角返回还是左上角返回，不会回到原来所在的列表页，而是回到首页；

4. Web page-service list shows too little service information. It is suggested that the IP and port should be displayed in the list, instead of needing some detail to see.

web页面-服务列表，显示服务信息太少，建议把ip和端口放在列表也展示，而不是需要点详细才能看到；

5. The function of web page-service list is too monotonous. It is suggested to enrich the filter conditions and disable the function for single node to facilitate exception rollback.

web页面-服务列表中功能太单调，建议丰富筛选条件，以及针对单节点禁用功能，利于异常回滚。

### Tell us your environment
v1.1.0

**Comment by nkorange** [comment]
可以使用1.1.3版本，已经对日志做了重点优化，参考 https://github.com/alibaba/nacos/issues/290

**Comment by wuwen5** [comment]
```server.tomcat.accesslog.enabled```  The recommended default value is false, Or configure the default maximum number of days

```server.tomcat.accesslog.max-days=30```

The current default configuration ``` accesslog.enabled ``` is true and Max day is - 1 (forever)
