### ISSUE TITLE
maven center Version  1.1.1 source code

### ISSUE THREAD

**Issue by pigxcloud** [alibaba/nacos#1645]
## Issue Description

maven POM

```
<!-- https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-client -->
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.1.1</version>
</dependency>
```

Where did it come from? 

releases  don`t  have

source code   1.1.0  -》 1.1.2-SNAPSHOT

### Describe what happened (or what feature you want)

need  1.1.1 source code , Because we need to keep the version in line with spring  cloud alibaba 2.1.1.

But we've always been running Nacos console based on source packages

**Comment by nkorange** [comment]
Hi, we only release client in version 1.1.1, so this version doesn't have a tag or branch. We are sorry about this inconvenience.

**Comment by pigxcloud** [comment]
- -OK
