### ISSUE TITLE
Using java sdk to register an instance, encountered problems.

### ISSUE THREAD

**Issue by czbabl** [alibaba/nacos#1646]
反复尝试官方的Java sdk注册实例中的代码。

代码：
   try {
            NamingService naming = NamingFactory.createNamingService(nacosAddress);
            naming.registerInstance("nacos.test.3", "192.168.2.104", servicePort, "TEST1");
        } catch (NacosException e) {
            e.printStackTrace();
        } finally {
        }

错误：
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried

nacos管理界面
![image](https://user-images.githubusercontent.com/4616859/62423869-4e671080-b6f9-11e9-85ab-84ac31ba817c.png)

debug:
ErrCode:500,ErrMsg:failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:400 msg: cluster name can only have these characters: 0-9a-zA-Z-, current: {"defaultCheckPort":80,"defaultPort":80,"healthChecker":{"type":"TCP"},"metadata":{},"name":"TEST1","useIPPort4Check":true}

pom.xml
![image](https://user-images.githubusercontent.com/4616859/62423890-a0a83180-b6f9-11e9-93f2-e9f00017bbec.png)

![image](https://user-images.githubusercontent.com/4616859/62423893-ad2c8a00-b6f9-11e9-812d-67eb195b1c7a.png)

**Comment by ganpanlin** [comment]
在pom里面，加入最新的nacos-client版本就可以，应该还是starter没有维护好

**Comment by nkorange** [comment]
Hi，已经更新了nacos-spring-boot版本：https://github.com/nacos-group/nacos-spring-boot-project/releases

**Comment by czbabl** [comment]
非常感谢


------------------
陈阵
 


 




------------------ 原始邮件 ------------------
发件人: "Fury Zhu"<notifications@github.com>;
发送时间: 2019年9月6日(星期五) 下午2:43
收件人: "alibaba/nacos"<nacos@noreply.github.com>;
抄送: "霸先"<czbabl@vip.qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/nacos] Using java sdk to register an instance,encountered problems. (#1646)




Hi，已经更新了nacos-spring-boot版本：https://github.com/nacos-group/nacos-spring-boot-project/releases
