### ISSUE TITLE
Nacos configuration does not automatically refresh the problem

### ISSUE THREAD

**Issue by tiandihai** [alibaba/nacos#1650]
我的springboot版本是2.1.0.RELEASE  ， nacos config版本是 0.9.0.RELEASE 。

我的bootstrap.properties配置文件如下：
![image](https://user-images.githubusercontent.com/6039066/62460547-dcec9800-b7b4-11e9-9e3c-13c8adc10372.png)
配置了 spring.cloud.nacos.config.refresh.enabled=true 。

我的启动类如下：
![image](https://user-images.githubusercontent.com/6039066/62460696-4c628780-b7b5-11e9-9069-5940f15afa97.png)

产生的现象是：
1、上面的红框中配置可以动态刷新，下面的红框中的配置没有动态刷新。
2、如果我在下面的Controller上面添加@RefreshScope注解，则下面的也可以动态刷新。
3、如果我把@RefreshScope注解添加到ServiceApplication这个启动类上面，下面的也不能动态刷新。

请问一下：
1、bootstrap.properties配置文件中配置spring.cloud.nacos.config.refresh.enabled=true，不能支持@Value注解的动态刷新吗？
2、@RefreshScope加到启动类上面不能支持全局的@Value注解的动态刷新吗？，如果每个用到@Value类上面都要加@RefreshScope，那就有点繁杂了。

**Comment by chenshao0594** [comment]
hi all  any update about this question.
thx

**Comment by chuntaojun** [comment]
是使用nacos时才会出现这个问题？

**Comment by chuntaojun** [comment]
`spring.cloud.nacos.config.refresh.enabled=true`仅仅标识配置会自动从远端拉取最新的配置，具体的`@Value`以及`Bean`的刷新和`spring-cloud`的机制有关系
