### ISSUE TITLE
nacos-console: code hilighting does not work

### ISSUE THREAD

**Issue by spawpaw** [alibaba/nacos#1654]
## Issue Description

Type: *bug report*

Scope: console

### Describe what happened (or what feature you want)
the code highlighting works fine when we are creating new configurations:
![image](https://user-images.githubusercontent.com/18007922/62518520-568b9100-b85c-11e9-96dc-8f3bf6bbfd7e.png)

but after publishing, either performing editing or viewing the detail action on that configuration, the code highlighting dose not work:
editing the config:  
![image](https://user-images.githubusercontent.com/18007922/62518627-96527880-b85c-11e9-90ec-aa920fdcd141.png)
viewing details of this config:  
![image](https://user-images.githubusercontent.com/18007922/62518661-a23e3a80-b85c-11e9-9c49-9c5f6ccb25f3.png)

### Describe what you expected to happen
the code highlighting should display as what we defined, or we can choose the code highlighting style when re-editing it.

### Tell us your environment

nacos server version: v1.0.0

**Comment by spawpaw** [comment]
The latest version's edit page have solve this problem, but the details page still have this problem:
![image](https://user-images.githubusercontent.com/18007922/63478424-5c1fe280-c4bc-11e9-8a9b-5f6e2617b7a0.png)

I dont know why editing page is using inputbox to show those configs(and the input box is not editable), but, anyway, the configs should be hilighted correctly as the editing page do.

**Comment by nkorange** [comment]
Welcome to contribute to it.
