### ISSUE TITLE
change the autoRefresh's  behaviour?

### ISSUE THREAD

**Issue by spawpaw** [alibaba/nacos#1656]
## Issue Description

Type: *feature request*

### Describe what happened
Now I'm using the nacos' config server to make my springboot app's config refresh automaticly as the following steps:
1. make the `nacos.config.auto-refresh=true` in the application.properties
2. adding `@NacosConfigurationProperties(prefix = "xxx", dataId = "application.properties")`

as common sense, the config should auto refresh (cause we have made a global config in our application.properties), but it dosent, because the `@NacosConfigurationProperties`'s `autoRefreshed` attribute has a default value `false`, so what's the meaning of the config `nacos.config.auto-refresh=true`?

### Describe what you expected to happen
should we use an enum for `autoRefresh` attr in `@NacosValue` and other related annotations?
```java
public @interface NacosValue {

    /**
     * The actual value expression: e.g. "#{systemProperties.myProp}".
     *
     * @return value expression
     */
    String value();

    /**
     * It indicates that whether the currently bound property is auto-refreshed when Nacos configuration is changed.
     *
     * @return default value is RefreshPolicy.INHERITED.
     */
    RefreshPolicy refreshPolicy() default RefreshPolicy.INHERITED;
}

enum RefreshPolicy{
    /*
    * inherit the application's config or the context's config,
    * or make it AutoRefreshPolicy.MANUAL if no context is presented
    */
    INHERITED,
    AUTO,// refresh automaticlly
    MANUAL;//do not refresh automaticlly
}
```
this may add some complexity in nacos, but improve user experience a lot  : )

### Tell us your environment
nacos server v1.1.0
nacos-client v1.1.1
com.alibaba.spring.spring-context-support v1.0.2

**Comment by chuntaojun** [comment]
I will move this issue to nacos springboot project

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/issues/54
