### ISSUE TITLE
instance healthy status are different in /instance and /list

### ISSUE THREAD

**Issue by leizhen** [alibaba/nacos#1658]
## Issue Description

* bug report *

### Describe what happened (or what feature you want)

when I query use api /instance and /list, I found that the instance healthy status are difference, and the instance is down now.

![image](https://user-images.githubusercontent.com/4723765/62592068-58109400-b904-11e9-97a5-a03737d61a90.png)

### Describe what you expected to happen

the healthy status should be false in /list

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
If all instances are unhealthy, the interface '/instance/list' would convert them all into healthy status. This is a protect mechanism in Nacos.
