### ISSUE TITLE
Detecting the config's type automaticlly?

### ISSUE THREAD

**Issue by spawpaw** [alibaba/nacos#1662]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
currently, we must assign the config type when our config is **not** `.properties`:
```java
@NacosConfigurationProperties(dataId = "application.yml", type = ConfigType.YAML)
```

### Describe what you expected to happen
why not detect the  config's type automaticlly if our data-id have a file suffix?

**Comment by chuntaojun** [comment]
you can see here：https://github.com/nacos-group/nacos-spring-project/wiki/Nacos-Spring-Project-0.3.3-%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C
