### ISSUE TITLE
@NacosPropertySource only inject Properties bug not YAML

### ISSUE THREAD

**Issue by evancyz** [alibaba/nacos#1667]
HI

I want put dbConfig into Property，so，I found the  @NacosPropertySource

when i put this properties into nacos like：
spring.datasource.driver-class-name= ***
spring.datasource.driver-class-name= ***
spring.datasource.username = ***
spring.datasource.password = ***
it works。

bug，when i put into yaml like：
spring:
    datasource:
        driver-class-name: ***
        password: ***
        url: ***
        username: ***
it not works

error display ： not found url  。。。

**Comment by chuntaojun** [comment]
it already support，see here ：https://github.com/nacos-group/nacos-spring-project/wiki
