### ISSUE TITLE
NullPointerException for parse response from /disto/datum 

### ISSUE THREAD

**Issue by EZLippi** [alibaba/nacos#1669]
## Issue Description
this issue is Associated with  [1021](https://github.com/alibaba/nacos/issues/1021)
Type: bug report

### Describe what happened (or what feature you want)

com.alibaba.nacos.naming.controllers.DistroController#get
com.alibaba.nacos.naming.controllers.DistroController#getAllDatums
has a problem that The response header[Content-Type: application/json;charset=UTF-8] is not written,Caused a problem[NullPointerException] while the client was reading
The error occurred in com.alibaba.nacos.naming.misc.HttpClient#httpGetLarge

as @nkorange say, the Content-Type header is implicitly set to 'application/json;charset=UTF-8' by NacosWebFilter, but NacosWebFilter is in config module, if i run only naming module, the server will not set Content-Type Header,then i got a NullPointException for this:
![image](https://user-images.githubusercontent.com/5326814/62748222-6a1c3f00-ba8a-11e9-8222-c2233b43d7e3.png)
![image](https://user-images.githubusercontent.com/5326814/62748246-84eeb380-ba8a-11e9-9ab2-d041b0591d8a.png)

**Comment by nkorange** [comment]
Hi, this problem is fixed in #1698
