### ISSUE TITLE
Add user guide document for UI Console

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#167]
** Description **
As v0.3.0 has built-in console (GUI), need to add user guide document to help user to use the console
more smoothly.

** HOW TO DO **

- discuss user guide doc framework and content
- first draft version
- review by our doc team
- release and publish to community

**Comment by yanlinly** [comment]
Solution: Refer to the cloud product acm to write the documentation of the console.
https://help.aliyun.com/document_detail/59956.html?spm=a2c4g.11186623.6.554.22e22d60OG2EcD

---

方案：参考云产品acm写一下控制台的文档
https://help.aliyun.com/document_detail/59956.html?spm=a2c4g.11186623.6.554.22e22d60OG2EcD

**Comment by paderlol** [comment]
@i will solve it @

**Comment by chitdayaung** [comment]
ok

**Comment by chitdayaung** [comment]
oj

**Comment by chitdayaung** [comment]
fjlvgo

**Comment by zx0zx9zx1zx9** [comment]
@yanlinly  this issue is also open，Is there anything that needs to do?

**Comment by Robyn37** [comment]
$ gem install bundler

**Comment by wilsonwu** [comment]
There is document here: https://nacos.io/zh-cn/docs/v2/guide/admin/console-guide.html
I think this issue can be closed. @KomachiSion
