### ISSUE TITLE
Can MyApplication read multiple configuration files? Can the application read multiple configuration files?

### ISSUE THREAD

**Issue by ElanZh** [alibaba/nacos#1672]
When I use Nacos as configuration center,
当我使用nacos作为配置中心时，
Can application read multiple configuration files?
应用是否可以读取多个配置文件？
Like the Consul?
就像Consul那样？
For example， appname = mall-order，if I use Consul，app will read two configuration named 'mall' and 'mall-order'.
比如说，我appname为mall-order，使用consul时两个配置都会读到，一个是mall一个是mall-order。
Dose nacos can do that?
nacos可以吗？

**Comment by ElanZh** [comment]
我都中英双语 了还要翻一把？

> > Hi @ElanZh, we detect non-English characters in the issue. This comment is an auto translation from @nacos-bot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # Can MyApplication read multiple configuration files? Can the application read multiple configuration files?
> 
> When I use Nacos as configuration center,
> When I use nacos as the configuration center,
> Can application read multiple configuration files?
> Can the application read multiple configuration files?
> Like the Consul?
> Just like Consul?
> For example， appname = mall-order，if I use Consul，app will read two configuration named 'mall' and 'mall-order'.
> For example, my appname is a mall-order. When using consul, both configurations will be read. One is mall and the other is a mall-order.
> Dose nacos can do that?
> Can nacos be?

There are already English and Chinese. What are you doing?
我都中英双语了。 还要翻一把？

**Comment by ElanZh** [comment]
> 我都中英双语 了还要翻一把？
> 
> > > Hi @ElanZh, we detect non-English characters in the issue. This comment is an auto translation from @nacos-bot to help other users to understand this issue.
> > > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> > 
> > 
> > # Can MyApplication read multiple configuration files? Can the application read multiple configuration files?
> > When I use Nacos as configuration center,
> > When I use nacos as the configuration center,
> > Can application read multiple configuration files?
> > Can the application read multiple configuration files?
> > Like the Consul?
> > Just like Consul?
> > For example， appname = mall-order，if I use Consul，app will read two configuration named 'mall' and 'mall-order'.
> > For example, my appname is a mall-order. When using consul, both configurations will be read. One is mall and the other is a mall-order.
> > Dose nacos can do that?
> > Can nacos be?
> 
> There are already English and Chinese. What are you doing?
> 我都中英双语了。 还要翻一把？

And delete Chinese in the title?
还把我中文标题干没了？

**Comment by glameyzhou** [comment]
nacos config可以读取三种类型的配置文件内容：
1、基础配置文件。
2、扩展配置文件，可以多个。
3、共享配置文件，可以多个。

你想读取那个配置文件，均需要手动指定，不知道是否满足你的需求。

**Comment by ElanZh** [comment]
> 
> 
> nacos config可以读取三种类型的配置文件内容：
> 1、基础配置文件。
> 2、扩展配置文件，可以多个。
> 3、共享配置文件，可以多个。
> 
> 你想读取那个配置文件，均需要手动指定，不知道是否满足你的需求。
谢谢，我已经在nacos sample 项目里找到了读取多个配置的示例
