### ISSUE TITLE
Instance information in the Java sdk cache will not be updated because the update thread exits

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#1674]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
缓存在sdk中的实例信息一直没有更新，  与服务端不同步

### Describe what you expected to happen
应该是需要同步的

### How to reproduce it (as minimally and precisely as possible)

生产环境出现过这个问题， 但是没有相关日志，  多次jstack发现，没有HostReactor中的更新线程堆栈，  从服务端的access日志中也印证这个问题

初步怀疑是HostReactor中更新线程没有执行的问题， 如下图， 如果出现异常，  任务将会中终止， 再也无法更新
![image](https://user-images.githubusercontent.com/2010632/62769933-90fb6500-bacc-11e9-8d11-26bfe0ac807d.png)

建议提供恢复的机制，  或者出现异常的情况下， 更新线程仍然继续执行

**Comment by easyhaloo** [comment]
> ## Issue Description
> Type: _bug report_ or _feature request_
> 
> ### Describe what happened (or what feature you want)
> 缓存在sdk中的实例信息一直没有更新， 与服务端不同步
> 
> ### Describe what you expected to happen
> 应该是需要同步的
> 
> ### How to reproduce it (as minimally and precisely as possible)
> 生产环境出现过这个问题， 但是没有相关日志， 多次jstack发现，没有HostReactor中的更新线程堆栈， 从服务端的access日志中也印证这个问题
> 
> 初步怀疑是HostReactor中更新线程没有执行的问题， 如下图， 如果出现异常， 任务将会中终止， 再也无法更新
> ![image](https://user-images.githubusercontent.com/2010632/62769933-90fb6500-bacc-11e9-8d11-26bfe0ac807d.png)
> 
> 建议提供恢复的机制， 或者出现异常的情况下， 更新线程仍然继续执行
> 
> ### Tell us your environment
> ### Anything else we need to know?

This exception has been ignored. i see that this scheduled task is a delayed exection, and if so ,it will only be executed once.

```
/**
     * Creates and executes a one-shot action that becomes enabled
     * after the given delay.
     *
     * @param command the task to execute
     * @param delay the time from now to delay execution
     * @param unit the time unit of the delay parameter
     * @return a ScheduledFuture representing pending completion of
     *         the task and whose {@code get()} method will return
     *         {@code null} upon completion
     * @throws RejectedExecutionException if the task cannot be
     *         scheduled for execution
     * @throws NullPointerException if command is null
     */
public ScheduledFuture<?> schedule(Runnable command,  long delay, TimeUnit unit);
```

**Comment by Maijh97** [comment]
@i will solve it@
