### ISSUE TITLE
k8s nacos-peer-finder-plugin unable to find local peer 

### ISSUE THREAD

**Issue by sohu234** [alibaba/nacos#1676]
**#Type "bug report"**

When i deploy nacos clusters in k8s,the nacos workload is always in ‘Unavailable’ status.
![image](https://user-images.githubusercontent.com/10140444/62769562-d10e1800-bacb-11e9-94e1-94718fc63eca.png)
and the nacos.log like this :
![image](https://user-images.githubusercontent.com/10140444/62769713-1df1ee80-bacc-11e9-9f24-d0bd835b1fd6.png)

in order to entry the nacos container, i comment  the 【readinessProbe】and [livenessProbe] in nacos-pvc-nfs.yaml,
![image](https://user-images.githubusercontent.com/10140444/62771340-8ee6d580-bacf-11e9-9a4d-2ee88b7ddcfd.png)
after entry the nacos container , cat /etc/hosts:
![image](https://user-images.githubusercontent.com/10140444/62771489-ea18c800-bacf-11e9-9bce-8debae9af0a9.png)

and then cat /home/nacos/conf/cluster.conf:
![image](https://user-images.githubusercontent.com/10140444/62772339-d9695180-bad1-11e9-8ab9-b07268ff55dd.png)

So far, we can see the host name in /etc/hosts is different with the one in /conf/cluster.conf.

and then cat /home/nacos/plugins/peer-finder/plugin.sh

![image](https://user-images.githubusercontent.com/10140444/62771724-74f9c280-bad0-11e9-8419-e6d1433f5a57.png)

why does  the plugin.sh replace the [cluster.local.] with [cluster.local] in/etc/hosts ? Is it because the host name that  peer-finder plugin parsed out end with cluster.local rather than cluster.localnacos-0? 
 if so, the plugin.sh will be  :
`#!/usr/bin/env bash
PEER_FINDER_DIR="/home/nacos/plugins/peer-finder"
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local.*/cluster.local/g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts
cd ${PEER_FINDER_DIR}
./peer-finder -on-start=${PEER_FINDER_DIR}/on-start.sh -on-change=${PEER_FINDER_DIR}/on-change.sh -service=${SERVICE_NAME} &`

but not 

`#!/usr/bin/env bash
PEER_FINDER_DIR="/home/nacos/plugins/peer-finder"
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local./cluster.local/g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts
cd ${PEER_FINDER_DIR}
./peer-finder -on-start=${PEER_FINDER_DIR}/on-start.sh -on-change=${PEER_FINDER_DIR}/on-change.sh -service=${SERVICE_NAME} &`

**Comment by paderlol** [comment]
Thanks， I will fix this error, but it may need to wait until next Monday, because I don't have a computer with me at present.

**Comment by paderlol** [comment]
I have fixed this issue
