### ISSUE TITLE
lose some living example

### ISSUE THREAD

**Issue by fanchangjifen** [alibaba/nacos#1680]
版本：nacos1.0.0
环境配置：centos7， 3台nacos server以nginx代理入口地址
问题：大概10几个服务实例，在其中两台上注册正常。再另外一台nacos server上只注册了部分实例。不知道是注册的问题，还是集群节点注册数据同步的问题！

**Comment by fanchangjifen** [comment]
补充：在正常的节点上，naming-server.log 出现很多空指针异常！而在问题节点上，日志确实正常的
![Uploading image.png…]()

**Comment by nkorange** [comment]
@fanchangjifen 使用最新的1.1.3服务端试一下。

**Comment by fanchangjifen** [comment]
nacos-client 1.1.3是否向下兼容nacos-server 1.0.0

**Comment by nkorange** [comment]
> nacos-client 1.1.3是否向下兼容nacos-server 1.0.0

一般来说是不兼容的，请保持Server为最新版本，新版本Server会兼容老版本client。
