### ISSUE TITLE
Excuse me, can application.proerties be configured with multiple environment files like spring boot?

### ISSUE THREAD

**Issue by xfuzq707** [alibaba/nacos#1682]
现在只有一个application.properties文件， 我像分几个环境，像spring boot一样，如application-dev.properties,  application-test.properties等，然而，启动的时候，加上 --spring.profiles.active=dev 并没有用，nacos支持这种吗？我看源代码它也是spring boot项目，如果有，怎么用？ 谢谢

**Comment by glameyzhou** [comment]
支持的。本来nacos config中的namespace就是环境隔离的概念。我们可以通过这个来实现。

**Comment by chuntaojun** [comment]
通过namespace命名空间
