### ISSUE TITLE
database connection pool validity detection problem

### ISSUE THREAD

**Issue by liyujun** [alibaba/nacos#1683]
# Issue Description
com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.java
line 192
// 每10分钟检查一遍连接池
ds.setTimeBetweenEvictionRunsMillis(TimeUnit.MINUTES.toMillis(10L));
ds.setTestWhileIdle(true);
ds.setValidationQuery("SELECT 1 FROM dual");

**Does not support MySQL**
Should be used “SELECT 1”

**Comment by freekry** [comment]
I don't think this is a problem.
