### ISSUE TITLE
http://nacos.io/schema/nacos.xsd    can not  be accessed

### ISSUE THREAD

**Issue by johndudo** [alibaba/nacos#1684]
http://nacos.io/schema/nacos.xsd    can not  be accessed

**Comment by johndudo** [comment]
my project is blocked by this issue.  Is there any way to continue...?

**Comment by nkorange** [comment]
Try again, this site is deploy on the github host which is not very stable for domestic users.

**Comment by hudiehekafei** [comment]
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 2 in XML document from ServletContext resource [/WEB-INF/dispatcher-servlet.xml] is invalid; nested exception is org.xml.sax.SAXParseException; systemId: http://nacos.io/schema/nacos.xsd; lineNumber: 2; columnNumber: 35; s4s-elt-character: 方案元素中不允许出现除 'xs:appinfo' 和 'xs:documentation' 之外的非空格字符。发现了 '301 Moved Permanently'。
