### ISSUE TITLE
k8s  /home/nacos/conf/cluster.conf (No such file or directory)

### ISSUE THREAD

**Issue by sohu234** [alibaba/nacos#1685]
Hi, guys. i got this exception below when i deployed nacos in k8s.
![image](https://user-images.githubusercontent.com/10140444/62919960-d5417a80-bdd6-11e9-93c6-105f33c67a2f.png)
       few days ago ,it worked fine,but today i do execute `kubectl apply -f nacos-pvc-nfs.yaml` and redeploy it and then it throw an exception above(both nacos-server image version and nacos-peer-finder-plugin image version is  latest).

 when i entry the nacos-server container and do `ls -l /home/nacos/conf` ,it shows below:
![image](https://user-images.githubusercontent.com/10140444/62920755-379b7a80-bdd9-11e9-938c-cb7c08700f4a.png)

   i want to know who create the `/home/nacos/conf/cluster.conf` file? Is it created by nacos-peer-finder-plugin ?  Why does the '/home/nacos/conf/cluster.conf' not be created ?  Thanks.

**Comment by sohu234** [comment]
Can nacos-peer-finder-plugin be open source ?

**Comment by paderlol** [comment]
1.You need to confirm if your NFS has write permission enabled.
2.   `nacos-peer-finder-plugin` This project has been open sourced. [link](https://github.com/nacos-group/nacos-k8s/tree/master/plugin)

**Comment by sohu234** [comment]
Thanks for you answered for me so quick. 
i am sure NFS has all permission. i have a question when i find out this in `on_start.sh` file
![image](https://user-images.githubusercontent.com/10140444/62922630-6ff18780-bdde-11e9-8613-15172998533c.png)
where is the environment variable `CLUSTER_CONF` be set ? 
Do u mind  open the peer-finder source ? i have no other meanings ,I was just curious.

**Comment by paderlol** [comment]
This variable is inside the [Nacos docker image](https://github.com/nacos-group/nacos-docker/blob/master/build/Dockerfile)

**Comment by sohu234** [comment]
i scale 2 pods for nacos cluster. one is work fine,but the other is not. i compared the good one's log with the not good. now show the difference below:

- the good one
![image](https://user-images.githubusercontent.com/10140444/62932489-c5379400-bdf2-11e9-8e1d-0a5257d81f33.png)

- the bad one
![image](https://user-images.githubusercontent.com/10140444/62932551-ec8e6100-bdf2-11e9-9849-05e720c327d9.png)
How can i resolve this problem? Thanks.

**Comment by paderlol** [comment]
You can try updating the peerfinder image and reboot it

**Comment by sohu234** [comment]
I have tried to ping dns sever in both good and bad containers, the present is that the network can be reachable in good container,but the bad ones can not. I think it not a bug of peer finder plugin,but a pod network issue . I will close this issue  as soon. But I need your help.




On 08/13/2019 19:30, pader wrote:

You can try updating the peerfinder image and reboot it

**Comment by paderlol** [comment]
ok，I'll do my best to help you

**Comment by sohu234** [comment]
it is not a bug of peer-finder-plugin.it is a issue of network.close this issue
