### ISSUE TITLE
Deploy the lastest release jar into maven central repository

### ISSUE THREAD

**Issue by Qsimple** [alibaba/nacos#1686]
Hi dear dev team:
  our team want to develop some service over nacos, so we need the dependency of nacos jar, such as the nacos spring client, nacos-naming. But we can't found the lastest release jar in maven central repo, hope those jar will be deployed in the coming future.

                                                                                                           Best regards
                                                                                                          simple

**Comment by chuntaojun** [comment]
if you want to use naocs in spring or spring-boot，you can see here [nacos-spring-project](https://github.com/nacos-group/nacos-spring-project) and [nacos-spring-boot-project](https://github.com/nacos-group/nacos-spring-boot-project)

**Comment by nkorange** [comment]
nacos spring client is [here](https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-spring-context). nacos naming is not supposed to be deployed.

We have deployed and will continue to deploy the latest jars to Maven repository.
