### ISSUE TITLE
Nacos on Aliyun Kubernetes leader election failure

### ISSUE THREAD

**Issue by Deathef** [alibaba/nacos#1688]
Using Alibaba Cloud's Kubernetes to deploy Nacos clusters, leader election failed.
This is my error log.
![image](https://user-images.githubusercontent.com/32616338/62925740-94049700-bde5-11e9-9985-05fd9f13ddd4.png)

I checked the naming-raft log， showed no leader.
![image](https://user-images.githubusercontent.com/32616338/62925525-1b053f80-bde5-11e9-987c-c2c51227a28a.png)
![image](https://user-images.githubusercontent.com/32616338/62925615-5142bf00-bde5-11e9-86a6-1254de80f32e.png)

**Comment by paderlol** [comment]
I saw that your namespace has changed through the log content.
you need change the address from nacos-0.nacos-headless.**default**.svc.cluster.local to nacos-0.nacos-headless.**newepoch**.svc.cluster.local

**Comment by Deathef** [comment]
> 我看到你的命名空间已经通过日志内容发生了变化。
> 你需要改变nacos-0.nacos-headless的地址。**默认** .svc.cluster.local到nacos-0.nacos-headless。**newepoch** .svc.cluster.local

Already solved, thank you
