### ISSUE TITLE
In springboot, you want to support multiple configuration file reads in a group at the same time

### ISSUE THREAD

**Issue by Dearker** [alibaba/nacos#1689]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
This issue I will be moved to nacos springboot project

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/issues/52
