### ISSUE TITLE
How to  config "naming_load_cache_at_start" in nacos-client1.0 and nacos-config-spring-boot-starter0.2.1

### ISSUE THREAD

**Issue by a421134331** [alibaba/nacos#1695]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
I want to set the attribute "naming_load_cache_at_start" , but I can`t find that in "@interface EnableNacosDiscovery" 

### Describe what you expected to happen
I want to set the  attribute "naming_load_cache_at_start" in   application.yml for springboot project

### Tell us your environment
nacos-client1.0 and nacos-config-spring-boot-starter0.2.1

**Comment by chuntaojun** [comment]
I will move this issue to nacos springboot project

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/issues/53
