### ISSUE TITLE
The configuration file is normal in yml, but it is reported to nacos.

### ISSUE THREAD

**Issue by ylh23y** [alibaba/nacos#1700]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by ylh23y** [comment]
![image](https://user-images.githubusercontent.com/13464610/63087333-7c174980-bf84-11e9-828b-03167f460053.png)

**Comment by freekry** [comment]
Can you express it clearly?

**Comment by freekry** [comment]
@ylh23y Can you express it clearly?

**Comment by ylh23y** [comment]
![搜狗截图20190816130040](https://user-images.githubusercontent.com/13464610/63144553-0a8fd780-c026-11e9-8949-094f03da11fa.png)
![搜狗截图20190816130132](https://user-images.githubusercontent.com/13464610/63144554-0a8fd780-c026-11e9-9847-710400b99375.png)
我之前用的eureka和springcloud-config作为注册和配置中心，运行都是正常的，但是现在换成nacos，就报下面的错误：
2019-08-16 12:58:29.376 ERROR 10552 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'security.oauth2.client.client-secret' to java.lang.String:

    Reason: Failed to bind properties under 'security.oauth2.client.client-secret' to java.lang.String

Action:

Update your application's configuration

Disconnected from the target VM, address: '127.0.0.1:63775', transport: 'socket'

Process finished with exit code 1
我用的版本是下面的：
	
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<version>0.9.0.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<version>0.9.0.RELEASE</version>
		</dependency>

**Comment by ylh23y** [comment]
问题找到了，配置文件里面有个@在nacos读不到：version: @project.version@，但是spring-cloud-config可以读到
