### ISSUE TITLE
After importing the configuration, the configured type becomes the default type:text

### ISSUE THREAD

**Issue by xiaok0928** [alibaba/nacos#1702]
After importing the configuration, the configured type becomes the default type:text;

nacos server version:v1.1.3
nacos:2.1.0release

**Comment by nkorange** [comment]
Can you paste some screenshoots to help us understand your problem?

**Comment by xiaok0928** [comment]
> Can you paste some screenshoots to help us understand your problem?

![image](https://user-images.githubusercontent.com/22540410/63310652-24833000-c32e-11e9-9c0d-4d48ee7aeb45.png)
![image](https://user-images.githubusercontent.com/22540410/63310657-29e07a80-c32e-11e9-835b-f4081059616a.png)
![image](https://user-images.githubusercontent.com/22540410/63310672-2f3dc500-c32e-11e9-943f-32411a08940f.png)
![image](https://user-images.githubusercontent.com/22540410/63310680-3533a600-c32e-11e9-8748-e9154c871f03.png)

**Comment by nkorange** [comment]
@xiaok0928 This config type is only meant to help display and edition, it's not a property of the configuration.

**Comment by xiaok0928** [comment]
@nkorange 
![image](https://user-images.githubusercontent.com/22540410/63331336-10f4bb00-c368-11e9-8768-1f9b718e9327.png)
在数据库里, type字段也有改变, 我不知道这样程序在加载这个配置的时候会不会出现异常,毕竟我在配置中添加的是有相关注释信息的.
如果没有影响, 建议导入的配置及克隆的配置保持原有的类型, 不然很容易误导人.
谢谢大佬.
