### ISSUE TITLE
Nacos console up and down buttons do not take effect

### ISSUE THREAD

**Issue by lishq** [alibaba/nacos#1704]
I am in the service discovery module, registering an instance to the service. Then on the details page of the nacos console. Click the go online or down button. The operation does not take effect, a refresh or previous state.

Expectation: Instance status should send changes

Nacos: 1.1.0

**Comment by chuntaojun** [comment]
You are using cloud? If so, the inside of the cloud rabbion instances of load balance components with a refresh mechanism, in the aspect of nacos, instances of up and down the line is second grade refresh, this I have analyzed in the post

**Comment by chuntaojun** [comment]
you can see here ：https://www.liaochuntao.cn/2019/06/11/java-web-45/

**Comment by lishq** [comment]
thank you very much
