### ISSUE TITLE
i use spring+springmvc+nacos,But can't be found in the spring container,What is the reason, please

### ISSUE THREAD

**Issue by ycachencheng** [alibaba/nacos#1710]
i use spring+springmvc+nacos,But can't be found in the spring container,What is the reason, please

**Comment by ycachencheng** [comment]
The datasource bean is in the xml configuration of the spring container, but the nacos parameter is not read.
![搜狗截图20190817161544](https://user-images.githubusercontent.com/8850928/63208716-47cd9580-c10a-11e9-8751-201f3c49cae5.png)

**Comment by ycachencheng** [comment]
Only the springmvc container has a role, it can not be found in the spring container

**Comment by chuntaojun** [comment]
I will move this issue to nacos spring project

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-project/issues/143

**Comment by rushsky518** [comment]
@i will solve it@

**Comment by rushsky518** [comment]
> Only the springmvc container has a role, it can not be found in the spring container

加个 钉钉 联系下？

**Comment by ycachencheng** [comment]
ok
![111](https://user-images.githubusercontent.com/8850928/63326188-4694a680-c35e-11e9-9425-9a963155768c.jpg)

**Comment by ycachencheng** [comment]
@rushsky518 厉害了，牛人，问题已经解决，非常感谢
