### ISSUE TITLE
Configserver and vipserver were originally two different products

### ISSUE THREAD

**Issue by wei7202839** [alibaba/nacos#1711]
如果要强行大一统  效果有可能适得其反

1.纯粹基于内存的注册发现,与基于磁盘的持久化数据间的差异

2.客户端正向心跳与服务端反向检测间的差异

**Comment by nkorange** [comment]
你指的适得其反是指什么？VIPServer和ConfigServer目前基于一套内核可以共用很多模块，也可以支持更多类型的服务。

**Comment by wei7202839** [comment]
1.vipServer健康检测用的是反向的服务端扫描的方式，如果对session层做分片，同一个分片的多个节点间就要有主从选举，因为执行健康检测的session节点肯定只需要一个，configServer没这个问题同一个分片内的若干节点是平等的不需要选主，因为只是被动接受心跳然后将conn维度的数据汇聚到data节点，健康检测占了vipserver很大的份额，检测方案的巨大差异会带来很大的统一成本；

2.vipserver类似于加强版DNS,数据是不能丢的，基于人为主动配置的写TPS跟服务注册发现主动上报的写TPS不是一个量级，configserver数据始终没有落盘也是这个原因，存储方案一个宜采用磁盘强一致性协议，一个只能基于内存最终一致性搞搞，如果强行统一，一个明显的问题会摆在面前，元数据要不要落盘 ？落盘了并发写能力上不去，不落盘机房一断电，非主动上报的数据会全部丢掉，如何取舍?

3.vipserver原本并没有session层与data层间的区分，configserver并不要求两者元数据的统一，但vipserver因为要主动做健康检测，势必要求session层与data层元数据层面的一致性，这会带来
数据一致性的巨大成本，如果采取vipserver架构抛弃configserver的读写分离，又不能保证写TPS,这是另外一个问题

 vipserver的创始人是我前同事，本人也搞过类似的大一统的项目，但最终不理想，当然也有可能是想复杂了，这些浅见仅供参考

**Comment by nkorange** [comment]
1. Nacos不会支持分片
2. 如果不是心跳上报能补偿的数据都要落盘，这个决策问题没有疑虑
3. 同1
