### ISSUE TITLE
The history version will not be deleted after the configuration is deleted

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#1713]
举个例子：
我创建了dataId是    aaa-bbb.yaml的配置；然后修改了2次，生成了2条历史版本数据。

然后，我删除 aaa-bbb.yaml这个配置，发现历史版本数据并没有被删除。

这样导致的问题：
假设我再次创建同名的配置，那么历史版本数据就有最初的2条数据了，很尴尬。

**Comment by chuntaojun** [comment]
This will repair in the future version
