### ISSUE TITLE
Nacos registration center downtime, the entire project service is also downtime?

### ISSUE THREAD

**Issue by liuliwei924** [alibaba/nacos#1714]
nacos 注册中心宕机后，为什么在注册中心的注册的提供者和消费者服务都宕机了，这样很尴尬，我的整个服务和消费端服务并没挂掉，只是挂了注册中心而已，按道理是可已执行本地缓存，远程直连调用的，但是nacos挂掉，导致涉及项目服务整个挂掉，是不合理的，有什么解决方案吗？

**Comment by nkorange** [comment]
提供者和消费者宕机原因确定吗？

**Comment by charlesvhe** [comment]
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
无法重现，你用的哪个版本？试试这个？

**Comment by liuliwei924** [comment]
我没有用springcloud，我用的是springboot集成，就是当我把注册中心nacos关闭后，会导致我注册的服务也挂掉。







------------------ 原始邮件 ------------------
发件人: "charlesvhe"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 下午2:08
收件人: "alibaba/nacos"<nacos@noreply.github.com>;
抄送: "泪过无痕"<1285295644@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/nacos] Nacos registration center downtime, the entireproject service is also downtime? (#1714)



                 com.alibaba.cloud                 spring-cloud-alibaba-dependencies                 2.1.0.RELEASE                 pom                 import              无法重现，你用的哪个版本？试试这个？

**Comment by liuliwei924** [comment]
> 提供者和消费者宕机原因确定吗？

确定，我是用springboot+dubbo集成nacos的注册中心和配置中心，我本想测试关闭注册中心，看能不能实现dubbo直连，结果我关闭nacos，整个消费者和提供者服务全部挂掉了

**Comment by nkorange** [comment]
估计是shutdown.sh脚本问题，你的应用的进程信息里包含nacos关键字？可以参考 #1791

**Comment by Cvimer** [comment]
如果dubbo使用zk做注册中心那么即使一个节点挂掉也不会有报错信息，但是当naco集群中有一个节点挂掉之后，业务就一直在一个节点链接不上

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([10.1.201.153:8848, 10.1.201.178:8848, 10.1.200.224:8848]) tried: failed to req API:10.1.201.153:8848/nacos/v1/ns/instance/beat. code:500 msg: java.lang.NullPointerException

**Comment by Cvimer** [comment]
如果dubbo使用zk做注册中心那么即使一个节点挂掉也不会有报错信息，但是当naco集群中有一个节点挂掉之后，业务就一直在一个节点链接不上

[ERROR] - [2019-10-14 21:25:05.580] com.alibaba.nacos.client.naming.net.NamingProxy:454 - request 10.1.200.224:8848 failed.
ErrCode:500, ErrMsg:failed to req API:10.1.200.224:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.ConnectException: Connection refused (Connection refused)

**Comment by nkorange** [comment]
关闭此issue，将在 #1507 跟踪
