### ISSUE TITLE
NamingMaintainService update instance failed

### ISSUE THREAD

**Issue by lishq** [alibaba/nacos#1716]
bug report

### Describe what happened (or what feature you want)

``` java
@NacosInjected
private NamingMaintainService namingMaintainService;

public void updateInstance(boolean enabled) throws NacosException {
        //ignore
        namingMaintainService.updateInstance(serviceName, instance);
 }

java.lang.IllegalArgumentException: no server available
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:439)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:387)
	at com.alibaba.nacos.client.naming.net.NamingProxy.updateInstance(NamingProxy.java:225)
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(NacosNamingMaintainService.java:86)
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(NacosNamingMaintainService.java:81)
	at com.alibaba.nacos.spring.factory.DelegatingNamingMaintainService.updateInstance(DelegatingNamingMaintainService.java:46)
```

An error occurred while updating an instance using the above interface

### Describe what you expected to happen

Successful operation

### Tell us your environment

<dependency>
          <groupId>com.alibaba.boot</groupId>
          <artifactId>nacos-discovery-spring-boot-starter</artifactId>
          <version>0.2.3</version>
</dependency>

client 1.1.0

### Anything else we need to know?

``` java
namingMaintainService = NamingMaintainFactory.createMaintainService("127.0.0.1" + ":" + port);
```
If you use it in this way, there is no problem

**Comment by chuntaojun** [comment]
other api is work fine？The cause of this error is caused by network, have a more detailed log information

**Comment by lishq** [comment]
![image](https://user-images.githubusercontent.com/25096777/63316577-f0b20580-c341-11e9-80cf-f3fcbdc18c64.png)

Hello, thank you for your answer. Other apis are normal.
The above figure is the instantiated property of this class, serverList=null,endpoint=null

![image](https://user-images.githubusercontent.com/25096777/63320256-c5361780-c34f-11e9-9e0a-d242a7e48f73.png)

 ```json
nacos:
  discovery:
    server-addr: 
  config:
    server-addr: 
```

It seems that the configuration is not getting the correct problem. The official configuration is such a format.

**Comment by chuntaojun** [comment]
I will move this issue to nacos spring project

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-project/issues/144
