### ISSUE TITLE
The file extension is not configurable and can be retrieved

### ISSUE THREAD

**Issue by zkzlx** [alibaba/nacos#1718]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

When the configuration is obtained, the specified configuration format can be returned.
This eliminates the need to deal with suffixes in data_Id.
It is also convenient for other developers to resolve these configurations uniformly without having to rely on the data_Id suffix.
Compatible with historical versions, the data_Id suffix takes precedence over the configuration format suffix.
![image](https://user-images.githubusercontent.com/53646873/63250010-38328600-c29d-11e9-8796-631add37633e.png)
////////////////////////////////////////////////
![image](https://user-images.githubusercontent.com/53646873/63250434-361cf700-c29e-11e9-96f0-d6011c232921.png)

**Comment by chuntaojun** [comment]
I think this is a good suggestion, we will consider it
