### ISSUE TITLE
when I use nacos config, I have some problems

### ISSUE THREAD

**Issue by hellotoworld** [alibaba/nacos#1723]
当调用nacos配置中心时候，应用启动时候没问题，启动以后会不定时的报以下错误：

 `
1. longPolling error :-- | --

2. no available server, currentServerAddr : http://nacos.internal.xxx.com:80

3. [fixed-nacos.internal.xxx.com_80-150914f4-ab51-44d6-b10d-dd3ac789cb33] [check-update] get changed dataId exception

4. [NACOS SocketTimeoutException httpPost] currentServerAddr: http://nacos.internal.xxxx.com:80， err : Read timed out

`

bootstrap.properties配置如下：

`
    spring.application.name=roboqaadmin
    spring.cloud.nacos.config.server-addr=nacos.internal.xxx.com:80
    spring.cloud.nacos.config.namespace=150914f4-ab51-44d6-b10d-dd3ac789cb33
`

pom.xml如下：
`
       <dependencies>
              <dependency>
                   <groupId>com.alibaba.cloud</groupId>
                  <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            </dependency>
      </dependencies>

		
       <dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Edgware.SR6</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			
			<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>1.5.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
		</dependencies>
	</dependencyManagement>`

**Comment by huangyangcong** [comment]
when I use nacos config, I have some problems

**Comment by duffiye** [comment]
I have some problems too

**Comment by chuntaojun** [comment]
Has submitted the pr, waiting for review
