### ISSUE TITLE
[com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.java:149] - [] [] [NA] failed to update serviceName: 127.0.0.1 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by wangyingwei001** [alibaba/nacos#1725]
[com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.java:149] - [] [] [NA] failed to update serviceName: 127.0.0.1
java.lang.NullPointerException: null

请问这是什么问题

**Comment by wangyingwei001** [comment]
用的集群版就报这个bug 单机的没问题

**Comment by chuntaojun** [comment]
failed to update serviceName: 127.0.0.1，这个服务是不是有问题？

**Comment by nkorange** [comment]
NullPointer请参考 #1993
