### ISSUE TITLE
Nacos Config cannot automatically refresh attribute values

### ISSUE THREAD

**Issue by morece** [alibaba/nacos#1726]
## Issue Description
*bug report*:In standalone environment, Nacos Config can not automatically refresh any configuration file data changes after performing the operation of changing "spring. datasource. druid. url" in the case of custom namespace.

### Describe what happened (or what feature you want)
Before modifying the value of "spring.datasource.druid.url" of yaml file, modify other properties of yaml file. The @RefreshScope+@Value in service can be refreshed automatically normally. After modifying the value of "spring.datasource.druid.url" of yaml file, @Value ("${spring.datasource.druid.url}") has not been automatically updated, and any other @Value value has been changed. Can not update automatically normally;

### Describe what you expected to happen
@ RefreshScope + @Value should normally automatically refresh attribute values
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
standalone
### Anything else we need to know?

**Comment by morece** [comment]
After restarting the service provider, the configuration can load the latest values normally

**Comment by KomachiSion** [comment]
Please use latest version to retry. If still has problem, please open a new issue let us know.
