### ISSUE TITLE
nacos 1.1.3 client EventDispatcher Design discussion

### ISSUE THREAD

**Issue by ZShUn** [alibaba/nacos#1730]
Seeing that there is a dependency on guava inside the client package, why not use guava events, but choose to build your own wheels. Is there any other consideration?

查看到client包内部有依赖guava，为什么不用guava 的事件，而是选择自己造轮子，是有什么其他考虑吗

**Comment by chuntaojun** [comment]
> Seeing that there is a dependency on guava inside the client package, why not use guava events, but choose to build your own wheels. Is there any other consideration?
> 
> 查看到client包内部有依赖guava，为什么不用guava 的事件，而是选择自己造轮子，是有什么其他考虑吗

It may be a good idea, I will go to see if it can be optimized

**Comment by ZShUn** [comment]
我在看nacos代码时发现在nacos-spring当中都是用spring event，那么nacos本身也是基于spring boot上开发，如果觉得合适。 我可以提交pr

**Comment by ZShUn** [comment]
如果修改可能会对已经使用了EventDispatcher 用户造成不兼容问题。
