### ISSUE TITLE
The console control "Items per page" has no practical effect

### ISSUE THREAD

**Issue by ly641921791** [alibaba/nacos#1734]
## Issue Description

This control has only one option

![1566314044861](https://user-images.githubusercontent.com/36787490/63360000-40bfb500-c3a0-11e9-98b8-43bbe43956df.jpg)

### Tell us your environment

Nacos version ： 1.1.0

**Comment by KomachiSion** [comment]
Issue has fixed in new version. please update to 1.3.0 at least.
