### ISSUE TITLE
 Which items of NACOS satisfy the cap theorem

### ISSUE THREAD

**Issue by jzdayz** [alibaba/nacos#1737]
Which items of NACOS satisfy the cap theorem

**Comment by Sun-Hongbin** [comment]
mixed，AP+CP。But I dont know which part is AP which part is CP
https://github.com/alibaba/nacos/issues/745

**Comment by nkorange** [comment]
CP refer to https://github.com/alibaba/nacos/tree/develop/naming/src/main/java/com/alibaba/nacos/naming/consistency/persistent/raft

AP refer to
https://github.com/alibaba/nacos/tree/develop/naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro
