### ISSUE TITLE
nacos-console: Make the namespace list and configurations list sortable

### ISSUE THREAD

**Issue by spawpaw** [alibaba/nacos#1738]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
the namespace list and the configurations list is not sortable:
![image](https://user-images.githubusercontent.com/18007922/63406326-20354080-c41c-11e9-8d8f-62990d0554b4.png)
> the namespace list is sorted by namespace id :(  
  
![image](https://user-images.githubusercontent.com/18007922/63406375-465ae080-c41c-11e9-832f-479666cb46b1.png)

### Describe what you expected to happen
why not make those fields sortable!! It's a simple work for both frontend and backend!!

![image](https://user-images.githubusercontent.com/18007922/63406690-368fcc00-c41d-11e9-9f1c-ff2a729c2c9a.png)

[a live demo there](https://ng.ant.design/components/table/en#components-table-demo-head)

### Anything else we need to know?

According to nacos limitation, one namespace can only have 200 configurations, so the sort wont  spend much computations.

**Comment by zhenxianyimeng** [comment]
@nkorange  I want try this, and I have some doubts
what except to happen when resort
For example, when I at page 2 sort desc, and then I click sort asc, does it need jump to page 1 
or still at page 2 whit new order

**Comment by KomachiSion** [comment]
Supported in new version.
