### ISSUE TITLE
Error of plugin.sh command in nacos-peer-finder-plugin

### ISSUE THREAD

**Issue by brandonfan1985** [alibaba/nacos#1739]
The plugin. SH in nacos-peer-finder-plugin has one line of code with more than one space, which prevents the command from taking effect.
specifically as follows:
cp/etc/hosts ~/hosts.new && sed -i 's/cluster.local. / cluster.local /g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts
It should be changed to:
cp/etc/hosts ~/hosts.new && sed -i 's/cluster.local./cluster.local/g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts

**Comment by nkorange** [comment]
Please report this issue to nacos-group/nacos-docker
