### ISSUE TITLE
Are the nacos has any "server id" just like zookeeper that ?

### ISSUE THREAD

**Issue by itfinally** [alibaba/nacos#1744]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Are the nacos has any "server id" just like zookeeper that ?

### Describe what you expected to happen

The global unique server id like zookeeper that. ( I read the website but found nothing )

We are planning to use the nacos to replace spring cloud and zookeeper,

that mean we are trying to use nacos to config / register other server and close other registration center, for good to management.

But also I wrote an id-generate-server at long time ago, 

and use zookeeper server id as the part of my snowflake id( The meaning is I just use the server id but no longer require any zookeeper service after that ), 

but nacos seem like not provide any unique integer like zookeeper.

So, 
are the nacos team willing to offer any unique server id like zookeeper 
or 
offer other way to help us resolve this issue?

Thank you very much.

**Comment by nkorange** [comment]
No, Nacos doesn't have a server id. Try generate your desired server id locally?

**Comment by itfinally** [comment]
Emmm...  I redesign the bit distribution of my id to adapt to Nacos.  
It also simplifies the design of my id-server, it no longer require the "server id".
