### ISSUE TITLE
The cache is still used after the configuration is updated

### ISSUE THREAD

**Issue by woxinqidai** [alibaba/nacos#1745]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
In the standalone mysql mode, the configuration file is updated or newly created, and the updated configuration is not available
`
                            if (STANDALONE_MODE && !PropertyUtil.isStandaloneUseMysql()) {
                                configInfoBase = persistService.findConfigInfo(dataId, group, tenant);
                            } else {
                                file = DiskUtil.targetFile(dataId, group, tenant);
                            }
`

The code here, while using the standalone mysql pattern, does not query the database and reads the cache file directly, but the cache file content is not updated

I don't know whether it is a bug or where I have a configuration problem

Thank you
### Tell us your environment
version: 1.1.3
docker.environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=root
      - MYSQL_SLAVE_SERVICE_HOST=mysql
      - MYSQL_SLAVE_SERVICE_DB_NAME=nacos
      - MYSQL_SLAVE_SERVICE_PORT=3306

**Comment by yjwfn** [comment]
I face the same problem, any update/create not get newest configurations.

**Comment by woxinqidai** [comment]
没有人????
