### ISSUE TITLE
The docs about nacos k8s have something make me confused

### ISSUE THREAD

**Issue by hyj1986** [alibaba/nacos#1747]
官方文档：https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html

在稍微靠后的部分：

###  使用 kubectl exec执行Nacos API 在每台节点上获取当前Leader是否一致
`for i in 0 1 2; do echo nacos-$i; kubectl exec nacos-$i curl GET "http://localhost:8848/nacos/v1/ns/raft/state"; done`

真实的执行结果会显示：
![image](https://user-images.githubusercontent.com/3008262/63484296-acee0600-c4d1-11e9-9001-09cd6f0e1330.png)

虽然也能正确去访问目标URL，但其中会有提示：
### Could not resolve host: GET; Unknown error

这就会给人带来困惑，到底是执行成功了还是有问题存在？

在CURL官方文档里面，好像使用HTTP GET方法是不用加上 GET 参数的。

所以为了文档的严谨性，建议在官方文档里面将 上面引用的代码块里面去掉 “GET” 。

谢谢！

**Comment by nkorange** [comment]
你好，这个是文档错误：```curl GET``` 需要改成 ```curl -X GET```
