### ISSUE TITLE
When the registration service is registered in version 1.1.3, the console cannot find the service problem.

### ISSUE THREAD

**Issue by xiaohanfeidao** [alibaba/nacos#1748]
本地启动nacos 服务1.1.3，使用sofa集成nacos 我使用的client 和api都是1.1.3，debug到NamingProxy中后（返回200），nacos控制台显示不出来注册的服务，后把client和api回退到0.6.0启动应用，能查出来，进过源码比对，0.6.0版本的注册时使用的是put方法，1.1.3版本使用的是post方法，感觉好奇怪，注册服务到nacos中的方法看结果应该是put，但是为什么最新的api是post？还是我的使用过程中有问题？

**Comment by nkorange** [comment]
POST是在大约0.8版本引入的，主要是为了符合POST的语义。
查看一下服务端的logs/naming-server.log以及logs/naming-event.log等有没有相关的信息。
