### ISSUE TITLE
The method  init() in DumpService is too long to read easily 

### ISSUE THREAD

**Issue by shirenchuang** [alibaba/nacos#1750]
## Issue Description

Type: code optimize

### Describe what happened (or what feature you want)
The method  init() in DumpService is too long to read easily 

### Describe what you expected to happen
I think we can optimize it

**Comment by nkorange** [comment]
Welcome to optimize it.

**Comment by shirenchuang** [comment]
我已经提过pr了。但是一直没有反应



---Original---

**Comment by chuntaojun** [comment]
> 我已经提过pr了。但是一直没有反应
> […](#)
> ---Original--- From: "Fury Zhu"<notifications@github.com&gt; Date: Fri, Aug 30, 2019 10:59 AM To: "alibaba/nacos"<nacos@noreply.github.com&gt;; Cc: "Eleven"<806638253@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [alibaba/nacos] The method init() in DumpService is too long to read easily (#1750) Welcome to optimize it. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

已经review了，按评论解决下，以及合并下冲突
