### ISSUE TITLE
In the list of services in the cluster, there are often instances that are unavailable and cannot find services, especially unstable.

### ISSUE THREAD

**Issue by ylh23y** [alibaba/nacos#1756]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 
### Tell us your environment
nacos版本1.1.3,3个本地集群,数据库为系统默认数据库
127.0.0.1:8848
127.0.0.1:8849
127.0.0.1:8847

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/13464610/63574998-9cb25580-c5bb-11e9-811d-286a7e8dd430.png)

![image](https://user-images.githubusercontent.com/13464610/63575179-07639100-c5bc-11e9-9b4d-36176c54f9b6.png)

![image](https://user-images.githubusercontent.com/13464610/63575261-34b03f00-c5bc-11e9-8fa3-5678068683a0.png)
在集群里面的在服务列表里面经常有实例不可用和发现不了服务，特别不稳定。

**Comment by nkorange** [comment]
请升级到1.1.3版本。

**Comment by ylh23y** [comment]
就是1.1.3版本有问题

**Comment by ylh23y** [comment]
> 请升级到1.1.3版本。



> 请升级到1.1.3版本。

**Comment by VolcanoOves** [comment]
我也是这个问题

**Comment by nkorange** [comment]
'127.0.0.1:8848/nacos/v1/ns/operator/servers?healthy=true' 每个节点相应执行下这个命令，看看列表是否一致 @ylh23y

**Comment by ylh23y** [comment]
在哪里执行命令

**Comment by nkorange** [comment]
> '127.0.0.1:8848/nacos/v1/ns/operator/servers?healthy=true' 每个节点相应执行下这个命令，看看列表是否一致 @ylh23y

浏览器输入这个地址，分别用8847, 8848, 8849端口

**Comment by vvsuperman** [comment]
“server is STARING now, please try again later”
but nacos had already stared

**Comment by ylh23y** [comment]
{"servers":[{"ip":"192.168.1.101","servePort":8848,"site":"unknown","weight":2,"adWeight":0,"alive":true,"lastRefTime":1574922944100,"lastRefTimeStr":"2019-11-28 14:35:44","key":"192.168.1.101:8848"}]}
{"servers":[{"ip":"192.168.1.101","servePort":8847,"site":"unknown","weight":2,"adWeight":0,"alive":true,"lastRefTime":1574923785710,"lastRefTimeStr":"2019-11-28 14:49:45","key":"192.168.1.101:8847"}]}
{"servers":[{"ip":"192.168.1.101","servePort":8849,"site":"unknown","weight":2,"adWeight":0,"alive":true,"lastRefTime":1574923847245,"lastRefTimeStr":"2019-11-28 14:50:47","key":"192.168.1.101:8849"}]}

最新的1.1.4版本测试了一下，还是有不稳定的情况
我的配置文件是下面的，有没有问题：
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8847,localhost:8849
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-dataids: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
![搜狗截图20191128145641](https://user-images.githubusercontent.com/13464610/69783896-779f3580-11ef-11ea-88ec-3124bbccbd92.png)

**Comment by wangdm0824** [comment]
我用的是1.14版本  集群模式下
运行一段时间后，nacos集群就挂掉了，nacos集群整个都访问不了
有一点很奇怪，nacos集群都down掉了，我服务之间的调用不受影响？

**Comment by wangdm0824** [comment]
> '127.0.0.1:8848/nacos/v1/ns/operator/servers?healthy=true' 每个节点相应执行下这个命令，看看列表是否一致 @ylh23y
{"servers":[{"ip":"172.31.224.147","servePort":8848,"site":"unknown","weight":1,"adWeight":0,"alive":true,"lastRefTime":1575007664394,"lastRefTimeStr":"2019-11-29 14:07:44","key":"172.31.224.147:8848"},{"ip":"172.31.224.148","servePort":8848,"site":"unknown","weight":1,"adWeight":0,"alive":true,"lastRefTime":1575007663858,"lastRefTimeStr":"2019-11-29 14:07:43","key":"172.31.224.148:8848"},{"ip":"172.31.224.149","servePort":8848,"site":"unknown","weight":1,"adWeight":0,"alive":true,"lastRefTime":1575007665340,"lastRefTimeStr":"2019-11-29 14:07:45","key":"172.31.224.149:8848"}]}

**Comment by ylh23y** [comment]
@nkorange

**Comment by nkorange** [comment]
> 我用的是1.14版本 集群模式下
> 运行一段时间后，nacos集群就挂掉了，nacos集群整个都访问不了
> 有一点很奇怪，nacos集群都down掉了，我服务之间的调用不受影响
> 
> @nkorange 请帮忙看看
> 
> ![image](https://user-images.githubusercontent.com/6170237/69853545-2d3ab900-12c2-11ea-9841-8c464aea2183.png)
> 
> ![image](https://user-images.githubusercontent.com/6170237/69853564-3461c700-12c2-11ea-9dc5-0537ea47c8a1.png)

搜一下有没有相关错误日志，gc日志、dmesg等都先看看

**Comment by wangdm0824** [comment]
> > 我用的是1.14版本 集群模式下
> > 运行一段时间后，nacos集群就挂掉了，nacos集群整个都访问不了
> > 有一点很奇怪，nacos集群都down掉了，我服务之间的调用不受影响
> > @nkorange 请帮忙看看
> > ![image](https://user-images.githubusercontent.com/6170237/69853545-2d3ab900-12c2-11ea-9841-8c464aea2183.png)
> > ![image](https://user-images.githubusercontent.com/6170237/69853564-3461c700-12c2-11ea-9dc5-0537ea47c8a1.png)
> 
> 搜一下有没有相关错误日志，gc日志、dmesg等都先看看


集群有没有最低内存限制？

**Comment by ylh23y** [comment]
用单机版本的很稳定，你们现在是否可以重现不稳定的这个问题？
 @nkorange

**Comment by nkorange** [comment]
@ylh23y 我这边环境部署都很稳定，你没有找到任何错误信息？

**Comment by ylh23y** [comment]
没有错误信息，就是分布式环境注册不稳定

**Comment by mimajiushi** [comment]
我单机版也有遇到过楼主一摸一样的问题，偶尔有的服务莫名奇妙就掉线了，没有任何为什么掉线的错误日志

**Comment by goodliukai** [comment]
我也遇到了类似问题，请问nacos客户端心跳是需要扫描所有服务端吗？还是说向一台机器发送心跳包即可同步给集群内所有机器？

**Comment by youkennkyou** [comment]
是不是本地开发时切换了网络导致ip改变从而引发了连接问题？我的leader搭建框架也出现了服务抖动的问题，他平时使用自己的网络，我怀疑是这个问题引起的

**Comment by youkennkyou** [comment]
我找到了解决方法，由于我是单机部署集群用来测试，所以ip写了127.0.0.1，我改成局域网ip后，服务不会再出现时不时断开的的问题

**Comment by niejian** [comment]
请问这个问题现在解决了吗，我现在做了个定时检查的机制，还是会有掉线的情况存在

**Comment by ylh23y** [comment]
@nkorange
这个配置服务里面是不是只能通过nginx来转发配置一个地址进行负载均衡，我之前是没有通过nginx进行负载均衡，把3个服务直接配置在才出现不稳定的情况：
下面的配置是不是错误的？
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8847
![搜狗截图20200620205529](https://user-images.githubusercontent.com/13464610/85202482-4deb5e80-b339-11ea-8b0a-a208cfd09f36.png)
