### ISSUE TITLE
RefreshScope auto refresh does not take effect

### ISSUE THREAD

**Issue by junjun888** [alibaba/nacos#1758]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

RefreshScope 标注的实体类字段无法动态刷新

### Describe what you expected to happen

RefreshScope 标注的实体类字段实现动态动态刷新

### How to reproduce it (as minimally and precisely as possible)

本人项目中存在这个数据库配置

@Bean(name = "defaultDataSource")
    @ConfigurationProperties(prefix = "spring.datasource.mysql")
    public DataSource defaultDataSource() {
        logger.info("Initialized defaultDataSource");
        return DataSourceBuilder.create().type(HikariDataSource.class).build();
    }

HikariDataSource 的字段，在被第二次设置的时候会抛出异常

 public void setJdbcUrl(String jdbcUrl)
   {
      if (sealed) throw new IllegalStateException("The configuration of the pool is sealed once started.  Use HikariConfigMXBean for runtime changes.");

      this.jdbcUrl = jdbcUrl;
   }

最后通过断点发现原因：
在 nacos 配置动态刷新的时候 cloud 会将 ConfigurationProperties 标注的对象的字典进行重新绑定。但是由于同一个数据库对象（HikariDataSource）的字段如果进行二次设置，则会抛出异常。导致广播事件无法继续。

通过查询资料发现 ，这个原因是 cloud 机制导致的
ConfigurationPropertiesRebinder 会将 ConfigurationProperties 标注的对象的字典进行重新绑定，没有做特殊处理

**Comment by chuntaojun** [comment]
I think it is spring problem, not nacos problem

**Comment by junjun888** [comment]
最后使用配置类的方式实现

@Data
@Configuration
@ConfigurationProperties(prefix = "spring.datasource.mysql")
public class MysqlDataSourceConfig {

    private String driverClassName;

    private String jdbcUrl;

    private String username;

    private String password;;
}

。。。

@Bean(name = "defaultDataSource")
    public DataSource defaultDataSource() {
        logger.info("Initialized defaultDataSource");
        HikariDataSource hikariDataSource = new HikariDataSource();
        hikariDataSource.setUsername(mysqlDataSourceConfig.getUsername());
        hikariDataSource.setPassword(mysqlDataSourceConfig.getPassword());
        hikariDataSource.setJdbcUrl(mysqlDataSourceConfig.getJdbcUrl());
        hikariDataSource.setDriverClassName(mysqlDataSourceConfig.getDriverClassName());
        return hikariDataSource;
    }
