### ISSUE TITLE
Console revenue box cannot blur search

### ISSUE THREAD

**Issue by ljynfo** [alibaba/nacos#1761]
install nacos server1.1.3  with docker，at console DataId and Group can not fuzzy search 

使用docker安装nacos server1.1.3，控制台页面DataId和Group不能模糊搜索，只是精准匹配

**Comment by freekry** [comment]
@ljynfo 可以的，你后面要加*号表示模糊匹配查询，比如：group*

**Comment by ljynfo** [comment]
> @ljynfo 可以的，你后面要加_号表示模糊匹配查询，比如：group_

谢谢大佬
