### ISSUE TITLE
Nacos configuration local cache directory

### ISSUE THREAD

**Issue by ljynfo** [alibaba/nacos#1762]
怎么指定nacos的本地缓存目录，看源码是取user.home，有没有类似apollo的apollo.cacheDir这种配置

**Comment by nkorange** [comment]
Use ```-DJM.SNAPSHOT.PATH=/xxx/xxx``` to customize the snapshot directory. 

The related code is [here](https://github.com/alibaba/nacos/blob/5f990729be5d637bced0d7497809ade614b8043a/client/src/main/java/com/alibaba/nacos/client/config/impl/LocalConfigInfoProcessor.java#L193)
