### ISSUE TITLE
His_config_info table src_user field is empty

### ISSUE THREAD

**Issue by haopangxu** [alibaba/nacos#1767]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

使用的mysql数据源，发现his_config_info表的src_user字段为空，请问如何能看到是哪个用户修改了配置文件
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
目前没有对接用户系统，所以该字段默认为空。
