### ISSUE TITLE
NACOS1.1.3 uses the cloning function to other workspaces without the configuration format will default text

### ISSUE THREAD

**Issue by zer0se7en** [alibaba/nacos#1769]
NACOS1.1.3 使用克隆功能到其他工作空间不会带上 配置格式 会默认text。

详情见图：
![4E1E0803-C0AA-4277-9EEA-832371D70045](https://user-images.githubusercontent.com/4436288/63677811-66c1db00-c820-11e9-9895-00c0fa12987f.png)

![69DEED39-D2FA-4945-8F51-59E38B7ACBEC](https://user-images.githubusercontent.com/4436288/63677815-69243500-c820-11e9-9408-cbd0eac0222c.png)

**Comment by ly641921791** [comment]
This is a bug, I think I can try to solve it
