### ISSUE TITLE
Nacos-discovery-spring-boot-starter 0.1.3 registration failed

### ISSUE THREAD

**Issue by jsen-joker** [alibaba/nacos#1771]
nacos-discovery-spring-boot-starter中在EmbeddedServletContainerInitializedEvent时间中注册服务，但是tomcat + war 没有这个事件，导致注册失败

**Comment by chuntaojun** [comment]
I will move this issue to nacos boot program

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/issues/59
