### ISSUE TITLE
How to remove unavailable services

### ISSUE THREAD

**Issue by yuguhan** [alibaba/nacos#1773]
![image](https://user-images.githubusercontent.com/36101454/63749587-55d79f00-c8de-11e9-84de-8f37bf0b3d16.png)
这个服务不能关闭，也不能下线

The service cannot be turned off or offline

**Comment by nkorange** [comment]
Please update to 1.1.3 and try it again. Usually ephemeral instances will automatically deleted after TTL(30 seconds) expired.

**Comment by yuguhan** [comment]
> Please update to 1.1.3 and try it again. Usually ephemeral instances will automatically deleted after TTL(30 seconds) expired.

![image](https://user-images.githubusercontent.com/36101454/63988042-f6aba180-cb0c-11e9-9863-4be8e53b1d16.png)
已经是1.1.3，而且这个服务因为没有ip的关系，不能进行任何操作

**Comment by nkorange** [comment]
奇怪你的实例如何注册上来的，可能是Nacos的一个bug。正常注册时，会校验IP的格式，IP为空是无法注册的。

**Comment by nkorange** [comment]
@yuguhan 能发一下复现步骤吗？
