### ISSUE TITLE
There is a bug in the console to add HTML type configuration

### ISSUE THREAD

**Issue by ly641921791** [alibaba/nacos#1775]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

When adding a html type configuration through the console, the parameter "type" is sent to the server as "text/html", which causes a problem to be displayed when editing this configuration through the console. 

<img width="751" alt="图片" src="https://user-images.githubusercontent.com/36787490/63877903-1357b480-c9fb-11e9-8d07-7c05661f5c7a.png">

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

Nacos Version : 1.1.3

**Comment by nkorange** [comment]
@ly641921791 This works for me on Chrome. What browser did you use? Try clean the browser cache and do it again.

**Comment by ly641921791** [comment]
> @ly641921791 This works for me on Chrome. What browser did you use? Try clean the browser cache and do it again.

My browser is Chrome, the browser cache is also cleaned up, the Nacos used is built from source, the version is 1.1.3

![图片](https://user-images.githubusercontent.com/36787490/63991886-0979a280-cb1c-11e9-9dc8-69abd8154d94.png)
