### ISSUE TITLE
1.1.3服务下线没有通知

### ISSUE THREAD

**Issue by greatle** [alibaba/nacos#1777]
1. 解压nacos1.1.3版本
2. 不做任何配置修改，直接运行
3. 运行一个服务注册，注册服务的subscribe。
4. 登录nacos控制台，选择服务列表中的注册服务，点击“详情”，点击“下线”，注册的监听器中接收不到相应的事件。
5. 如果"下线"后再点击“上线”或“编辑”保存都能收到对应的事情。另外1.0.0版本是在“下线”的时候也是可以收到事件的

**Comment by nkorange** [comment]
我测试了，都是能收到事件的。你有没有重现demo？

**Comment by greatle** [comment]
就一个简单的测试：

package com.test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Semaphore;

import com.alibaba.nacos.api.NacosFactory;
import com.alibaba.nacos.api.naming.NamingService;
import com.alibaba.nacos.api.naming.listener.NamingEvent;
import com.alibaba.nacos.api.naming.pojo.Instance;

public class ClientMain
{
	public static void main(String[] args) throws Exception 
	{
        test();
        Semaphore se = new Semaphore(0);
        // 不退出
        se.acquire();
	}
	
	public static void test()
	{
		String serverAddr = "192.168.1.126:8848";
		String serviceName = "testServer";
		Instance in = new Instance();
		in.setIp("localhost");
		in.setPort(100);
		Map<String, String> map = new HashMap<>();
		map.put("ip", "192.168.1.126");
		map.put("value", "test");
		in.setMetadata(map);
		try
		{
			NamingService namingService = NacosFactory.createNamingService(serverAddr);
			namingService.registerInstance(serviceName, in);
			
			// 注册监听器
			namingService.subscribe(serviceName, (event) -> 
			{
				if (event instanceof NamingEvent) 
				{
					List<Instance> list = ((NamingEvent) event).getInstances();
					for (Instance temp : list)
					{
						System.out.println("========" + temp);
					}
				}
				
			});
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}
	
}

**Comment by nkorange** [comment]
如果实例下线了，收到的list是空，那么你的这个println就不会执行了

**Comment by greatle** [comment]
那就是只能以list为空判断为下线了，而不是原来1.0.0的enabled值为false.
个人觉得还是enabled为false比较好，这样如果有多个服务实例的时候，相互间可以知道哪些服务实例是在线的，哪些是下线的

**Comment by nkorange** [comment]
并不是通过判断list为空来判断，如果注册了多个实例，会返回上线的实例。
这涉及到上层的服务框架如何使用这个推送事件，如果返回enabled=false的实例，目前dubbo和spring cloud客户端都没有做过滤，可能会造成问题。统一由Nacos客户端来进行过滤是比较推荐的做法。

**Comment by greatle** [comment]
对其他使用该服务的服务来说，是这样的不在list里的就表示不存在该服务实例，但对于服务自己需要知道是否被下线以便该服务实例做一些回调处理，则只有判断自己是否在list中了

**Comment by nkorange** [comment]
> 对其他使用该服务的服务来说，是这样的不在list里的就表示不存在该服务实例，但对于服务自己需要知道是否被下线以便该服务实例做一些回调处理，则只有判断自己是否在list中了

你可以对这个事件机制进行重载，支持返回所有实例。期待你的贡献！

**Comment by Nexuizs** [comment]
这个问题我也遇到了，解决了没？

**Comment by greatle** [comment]
增加了一个enableOnly标记属性，使用的时候，根据需要在注册的时候设置该属性；在dubbo使用的时候，注册地址中增加一个参数：<dubbo:registry address="nacos://${nacos.ip}?enableOnly=false" />，不设置该参数还是按照原来的逻辑处理；非dubbo类似的设置属性就可以了。
在我clone的库中处理了（greatle/nacos），你可以参考一下。



xuwenping050@163.com
 
发件人： Nexuizs
发送时间： 2019-12-16 18:01
收件人： alibaba/nacos
抄送： greatle; Author
主题： Re: [alibaba/nacos] 1.1.3服务下线没有通知 (#1777)
这个问题我也遇到了，解决了没？

**Comment by Nexuizs** [comment]
谢谢

**Comment by Nexuizs** [comment]
你好，我使用的是springboot + nacos 将执行器注册到nacos服务中心去，类似的属性是什么，能详细点吗

在 2019-12-16 21:05:00，"greatle" <notifications@github.com> 写道：
增加了一个enableOnly标记属性，使用的时候，根据需要在注册的时候设置该属性；在dubbo使用的时候，注册地址中增加一个参数：<dubbo:registry address="nacos://${nacos.ip}?enableOnly=false" />，不设置该参数还是按照原来的逻辑处理；非dubbo类似的设置属性就可以了。
在我clone的库中处理了（greatle/nacos），你可以参考一下。



xuwenping050@163.com

发件人： Nexuizs
发送时间： 2019-12-16 18:01
收件人： alibaba/nacos
抄送： greatle; Author
主题： Re: [alibaba/nacos] 1.1.3服务下线没有通知 (#1777)
这个问题我也遇到了，解决了没？
