### ISSUE TITLE
Vulnerability related

### ISSUE THREAD

**Issue by maomaomo1990** [alibaba/nacos#1779]
请开发团队关注一下web渗透的漏洞
目前已经发现：
1：修改状态返回码，直接绕过登录认证，直接能访问系统资源
2：http协议，登录账号信息也是直接明文传输，没有验证码，有爆破风险
3：部分链接地址，不需要登录直接可以访问
以上只是部分漏洞，开发团队可以整体做一个渗透测试，集中修复
如果用户直接将地址暴漏于公网，恶意人员，针对IP全端口扫描，将存在极大的风险

**Comment by nkorange** [comment]
目前没有权限控制，所以不推荐部署在外网环境，相关的功能在开发中，可以参考 #1105
