### ISSUE TITLE
Hardcoded file separator

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/nacos#1781]
https://github.com/alibaba/nacos/blob/0808d0cc397c0fc6a48240639aa943365a91dec7/config/src/main/java/com/alibaba/nacos/config/server/service/DiskUtil.java#L182
应用程序需要在不同的平台上运行时，使用硬编码文件分隔符会导致应用程序逻辑执行错误，可以使用独立于平台的API，如java.io.File.separator，也可以通过使用java.lang.System.getProperty("file.separator")来获取。

**Comment by JerryChin** [comment]
@i will solve it@
