### ISSUE TITLE
How use properties from nacos config in logback.xml ?

### ISSUE THREAD

**Issue by blackbk** [alibaba/nacos#1782]
I have logback config xml in springcloud project(Using nacos config & discovery v1.1.3).Then I set some datasource properties in logback-development.xml(These properties are store in nacos). But the log appender print error that properties are null when I run application.

logback-development.xml:
 ```
<appender name="redis_out" ....
.......
  <host>${LOG_REDIS_HOST}</host>
 <port>${LOG_REDIS_PORT}</port>
......
  <pattern>
 {  "app": "${spring.application.name}",
    "timestamp": "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZZ}",
......
 </appender>
```

The log appender print error like this :
**[{"app":"spring.application.name_IS_UNDEFINED",......**

It seems like properties are not active when log appender init.

**Comment by zyzhang15** [comment]
why close  the Issue , I think  it's a real problem ,Nacos and Logback  not working well toghter.   HaHa~~

**Comment by Starbucksstar** [comment]
+1，logback-spring.xml在springboot工程中遇到同样问题

**Comment by lgw79674057** [comment]
+1，logback-spring.xml在springboot工程中遇到同样问题
