### ISSUE TITLE
Wrong raft term value on WebUI after raft leader server failover.

### ISSUE THREAD

**Issue by satjd** [alibaba/nacos#1786]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Nacos cluster management WebUI gives a wrong information on raft term. After an old leader failover, a new follower will be elected as leader. However, if the previous leader restart, the term of this old leader will not be updated on the new leader. This will lead to a misleading value on this new leader's cluster management WebUI.
As the captured UI shown below, the term of an old leader(172.16.62.156) will not be updated to the term of new leader(172.16.62.154).
![Snipaste_2019-08-30_20-33-55](https://user-images.githubusercontent.com/12881658/64021870-7f572b80-cb67-11e9-9ea6-b8db60955dec.png)

Maybe this is due to the method **onChangeHealthyServerList()** is not properly implemented in **com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet**.

![image](https://user-images.githubusercontent.com/12881658/64022289-71ee7100-cb68-11e9-8981-e895dd46444f.png)

 

### Describe what you expected to happen
The term of all servers in cluster should have a same term value on the WebUI. 

### How to reproduce it (as minimally and precisely as possible)

1. Start nacos servers in cluster mode.
2. Shutdown leader server (after leader is elected).
3. Restart old leader server after a new leader is elected.
4. Access the cluster management page: http://xxx:xx/nacos/#/clusterManagement

### Tell us your environment
Jdk version: OpenJdk 8
Nacos version: Nacos Server 1.1.3
on Aliyun ECS 4C8G * 5

**Comment by nkorange** [comment]
This problem is previously reported in #1602 . We will track it there.
