### ISSUE TITLE
support custom namespace

### ISSUE THREAD

**Issue by Nicqiang** [alibaba/nacos#1789]
### this is a requirement
when we define a namespace, we must use the uuid as namespace. it  is not convenient to read and understand.
![image](https://user-images.githubusercontent.com/22723887/64061392-b29fc600-cc0c-11e9-92ce-3d53e81659d8.png)

![image](https://user-images.githubusercontent.com/22723887/64061404-e11da100-cc0c-11e9-8c46-6344c3a84172.png)

**Comment by nkorange** [comment]
Welcome to contribute to it. It's more friendly if namespace id is also editable.

**Comment by g5niusx** [comment]
> Welcome to contribute to it. It's more friendly if namespace id is also editable.

可以直接使用 namespace name 来代替 namespace id 吗？😊

**Comment by nkorange** [comment]
> > Welcome to contribute to it. It's more friendly if namespace id is also editable.
> 
> 可以直接使用 namespace name 来代替 namespace id 吗？😊

 只要保证namespace id是全局唯一的就行

**Comment by nkorange** [comment]
将会在 #1606 里进行跟踪，本issue关闭。
