### ISSUE TITLE
In springboot, multiple configuration files are supported：example

### ISSUE THREAD

**Issue by Dearker** [alibaba/nacos#1790]
@Component
public class TaskTimer {

    private final static Map<String,String> urlMap = Maps.newHashMap();

    @NacosValue(value = "${hello}",autoRefreshed = true)
    private String hello;

    @NacosInjected
    private ConfigService runConfigService;

    @Scheduled(fixedRate = 1000)
    public void getUser(){
        System.out.println("定时任务获取的配置"+"-->"+urlMap.get("hello"));

    }

    public void init(){
        urlMap.put("123",hello);
        System.out.println(urlMap.get("123"));
    }

    @NacosConfigListener(dataId = "service-provider.yaml",type = ConfigType.YAML,timeout = 500)
    public void getMap(String newContent){
        System.out.println(newContent);
        String[] split = newContent.split("\r\n");
        for (int i = 0; i < split.length; i++) {
            String[] params = split[i].split(":");
            urlMap.put(params[0],params[1]);
        }
        System.out.println(urlMap.get("hello"));
    }
}

@Order(1)
@Component
public class OrderComponent implements CommandLineRunner {

    @Autowired
    private TaskTimer taskTimer;

    @Override
    public void run(String... args) throws Exception {
        taskTimer.init();
    }
}

**Comment by chuntaojun** [comment]
I moved to nacos boot program
