### ISSUE TITLE
Management platform cluster raft term (cluster term) is not displayed properly

### ISSUE THREAD

**Issue by hjnjmjkj** [alibaba/nacos#1793]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
管理平台 集群raft term（集群任期）显示不正常

### Describe what you expected to happen
期望正常显示

### How to reproduce it (as minimally and precisely as possible)

1. 安装三台nacos1.1.3集群
2. curl 'xxxx:8848/nacos/v1/ns/raft/leader'，执行这个命令

### Tell us your environment
阿里云centos7
nacos1.1.3集群模式

### Anything else we need to know?
日志如下：
[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# curl '172.17.62.51:8848/nacos/v1/ns/raft/state'
{"peers":[{"ip":"172.17.62.50:8848","voteFor":"172.17.62.51:8848","term":9,"leaderDueMs":15721,"heartbeatDueMs":5000,"state":"FOLLOWER"},{"ip":"172.17.62.52:8848","voteFor":"","term":0,"leaderDueMs":16944,"heartbeatDueMs":5000,"state":"FOLLOWER"},{"ip":"172.17.62.51:8848","voteFor":"172.17.62.51:8848","term":9,"leaderDueMs":16747,"heartbeatDueMs":2500,"state":"LEADER"}],"services":73}[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# 
[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# 
[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# curl '172.17.62.52:8848/nacos/v1/ns/raft/state'
{"peers":[{"ip":"172.17.62.50:8848","voteFor":null,"term":0,"leaderDueMs":11187,"heartbeatDueMs":2402,"state":"FOLLOWER"},{"ip":"172.17.62.52:8848","voteFor":null,"term":0,"leaderDueMs":17626,"heartbeatDueMs":4500,"state":"FOLLOWER"},{"ip":"172.17.62.51:8848","voteFor":"172.17.62.51:8848","term":9,"leaderDueMs":19433,"heartbeatDueMs":5000,"state":"LEADER"}],"services":73}[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# 
[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# 
[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]# curl '172.17.62.50:8848/nacos/v1/ns/raft/state'
{"peers":[{"ip":"172.17.62.50:8848","voteFor":"172.17.62.51:8848","term":9,"leaderDueMs":15832,"heartbeatDueMs":2500,"state":"FOLLOWER"},{"ip":"172.17.62.52:8848","voteFor":null,"term":0,"leaderDueMs":10114,"heartbeatDueMs":1280,"state":"FOLLOWER"},{"ip":"172.17.62.51:8848","voteFor":"172.17.62.51:8848","term":9,"leaderDueMs":18725,"heartbeatDueMs":5000,"state":"LEADER"}],"services":73}[root@iZ2ze1cqhsif9nhh2ecjn1Z nacos]#

**Comment by nkorange** [comment]
会在 #1786 进行跟踪，本issue关闭
