### ISSUE TITLE
Configuring priority order

### ISSUE THREAD

**Issue by houhuacheng** [alibaba/nacos#1796]
springcloud nacos  如何设置 本地的配置优先于远程配置，比如本地配置的端口
现在连启动 命令传参数都没有起作用

**Comment by stockwyz** [comment]
你用的服务能读nacos上的配置吗？我的是  nacos1.1.3.按示例,无论如何都读不到nacos上的配置。在sentinel中配置的流控规则，我按示例修改了dashboard的源码可以同步到nacos中变成一个配置，微服务启动时可以读到流控规则。但服务的配置还是读不到。
