### ISSUE TITLE
dynamic generate namespace

### ISSUE THREAD

**Issue by luohaoGit** [alibaba/nacos#1798]
## dynamic generate namespace while using nacos in develop environment

Type:  *feature request*

### we use independent nacos server on every developer's PC to prevent invoking services on others' PC. we don't want to start a server when developing. we wish use a dev-share-server with diffrent tenant. Now, we add namespace for everyone manully, and config namespace environment variable on everyone's PC, like `namespace=uuid` and spring yml like `spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.43:8848
        namespace: ${namespace:public}  `.
It's so troublesome.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.1.3

**Comment by nkorange** [comment]
namespace is considered as a unique identity to isolate data, it should be modified very carefully. So we do not plan to support this feature.

**Comment by luohaoGit** [comment]
> namespace is considered as a unique identity to isolate data, it should be modified very carefully. So we do not plan to support this feature.

thks, I think i had find the way which deliverying http header keys that identify the target machine in micro services，anyway thks!
