### ISSUE TITLE
how to prometheus get dynamic service list from nacos server for metrics minitor?

### ISSUE THREAD

**Issue by monkeyAlwaysWin** [alibaba/nacos#1805]
## Issue Description
Prometheus how to dynamically obtain the services registered on nacos, do metrics monitoring
(prometheus如何动态获取nacos上注册的服务,去做metrics监听)
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我想通过prometheus获取naocs上的服务,去做metrics监听,不想静态配置,现在支持吗

### Describe what you expected to happen
我没有找到prometheus.yml上如何配置 如何获取nacos注册中心的服务

### How to reproduce it (as minimally and precisely as possible)
如果有的话可以告诉我如何配置,链接也行

**Comment by nkorange** [comment]
目前不支持

**Comment by xuande** [comment]
参考[eureka-consule-adapter](https://github.com/twinformatics/eureka-consul-adapter)实现的[nacos-consul-adapter](https://github.com/xuande/nacos-consul-adapter),在prometheus配置文件中使用consul_sd_configs配置nacos-consul-adapter地址可以实现从nacos中动态发现服务地址

**Comment by nkorange** [comment]
#1032 和这个问题是同一个
