### ISSUE TITLE
Nacos 1.1.3 startup.sh cannot be started in standalone under docker

### ISSUE THREAD

**Issue by mostcool** [alibaba/nacos#1806]
nacos 1.1.3 startup.sh在docker下无法单机启动。但改用1.0.1里的startup.sh就可以启动。

**Comment by mostcool** [comment]
my docker-compose.yml
`nacos:
  image: 'index.docker.io/openjdk:8-jdk-alpine'
  volumes:
    - './app:/app'
    - /etc/localtime:/etc/localtime:ro
  entrypoint:
    - /app/bin/startup.sh
    - -m
    - standalone
  net: "host"`

**Comment by nkorange** [comment]
> my docker-compose.yml
> 
> nacos:
> image: 'index.docker.io/openjdk:8-jdk-alpine'
> volumes:
> - './app:/app'
> - /etc/localtime:/etc/localtime:ro
> entrypoint:
> - /nacos/bin/startup.sh
> - -m
> - standalone
> net: "host"

请求启动时报什么错了？

**Comment by mostcool** [comment]
> > my docker-compose.yml
> > nacos:
> > image: 'index.docker.io/openjdk:8-jdk-alpine'
> > volumes:
> > 
> > * './app:/app'
> > * /etc/localtime:/etc/localtime:ro
> >   entrypoint:
> > * /nacos/bin/startup.sh
> > * -m
> > * standalone
> >   net: "host"
> 
> 请求启动时报什么错了？

不报错，一直就卡着不动。如下图：
![image](https://user-images.githubusercontent.com/2172570/68727024-36f3c980-05fe-11ea-8392-6b83311031fa.png)

**Comment by nkorange** [comment]
这个日志是正常的，程序已经在后头启动了，你要看下{nacos.home}/logs/nacos.log里面是否有报错。

**Comment by mostcool** [comment]
> 这个日志是正常的，程序已经在后头启动了，你要看下{nacos.home}/logs/nacos.log里面是否有报错。

@nkorange logs下只有一个start.out文件，这个文件里什么都没有。根本就没有生成nacos.log文件。
启动后，输出上述信息后，应用直接退出了。

**Comment by nkorange** [comment]
非docker有问题吗？

**Comment by mostcool** [comment]
> 非docker有问题吗？

没有问题，可以正常启动。
