### ISSUE TITLE
Unable to read mybatisplus multi data source configuration file

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/nacos#1810]
nacos配置文件无法读取mybatisplus多数据源配置文件

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
        </dependency>
的配置文件，这个能否帮忙支持
datasource:
    dynamic:
      primary: master            # 设置默认的数据源或者数据源组,默认值即为master
      strict: false             # 设置严格模式,默认false不启动. 启动后再为匹配到指定数据源时候回抛出异常,不启动会使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

报错信息如下：
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

Process finished with exit code 1

**Comment by songjiang951130** [comment]
```
datasource:
master:
url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
```
这个文件一点换行和都没有？格式太烂了，推荐先本地跑通环境，在把配置文件扔到nacos中
```
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://****:3306/database_name
    username: ****
    password: ***
```

**Comment by chuntaojun** [comment]
Is the use of nacos - springboot? Suggested to use, look at the wiki here the problem of nacos problem, but the corresponding nacos ecological components

[nacos-spring-boot-wiki](https://github.com/nacos-group/nacos-spring-boot-project/wiki)
