### ISSUE TITLE
Deploying Nacos error reporting in K8S environment

### ISSUE THREAD

**Issue by huohuanhuan** [alibaba/nacos#1812]
java.lang.IllegalStateException: unable to find local peer: nacos-2.nacos
headless.default.svc.clusts.default.svc.cluster.local:8848, nacos-1.nacos-headless.default.svc.cluster.local:8848, nacos-2.nac

**Comment by WywTed** [comment]
nacos-2.nacos
headless.default.svc.clusts.default.svc.cluster.local:8848

this address might be wrong .
nacos-2.nacosheadless.default.svc.cluster.local:8848

**Comment by nkorange** [comment]
You have to make sure your hostname existed in cluster.conf

**Comment by HashTableHu** [comment]
> java.lang.IllegalStateException：无法找到本地对等点：nacos-2.nacos 
> headless.default.svc.clusts.default.svc.cluster.local：8848，nacos-1.nacos-headless.default.svc.cluster.local ：8848，nacos-2.nac

最后保证cluster.config的主机名与/etc/hostname中的一致是不是就行了？
