### ISSUE TITLE
After the service goes offline, the network connection is disconnected and then restored. The display is online.

### ISSUE THREAD

**Issue by greatle** [alibaba/nacos#1814]
1. 启动nacos服务
2. 在另一机器上运行并注册一个服务
3. 登录控制台，在服务列表中可以看到该注册的服务，并是上线状态
4. 选择该注册的服务，“详情” -> "下线"，此时该服务处于下线状态
5. 模拟该服务机器断网（一分钟左右），然后在恢复
6. 查看nacos控制台，发现该服务又处于“上线” 状态了

**Comment by EZLippi** [comment]
@greatle nacos控制台的下线只是把instance的状态enabled改为false,如果断网一分钟后由于长时间没有发送心跳请求给nacos,nacos server会删除该实例，过一会网络恢复了重新发送心跳，nacos会重新注册上去，这时候注册的enable状态是客户端传递过来的，因此还是enabled, nacos采用的AP架构不建议直接去修改实例的状态，而是让实例自己上报，如果你想让服务下线，最好是给服务实例发送一个消息，让他自己去注册然后重新注册一个enabled=false的实例
