### ISSUE TITLE
Suggest adding lifecycle interface, the use of the service optimization nacos and life cycle

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#1815]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

background
1. Because the client instance may exist in the life cycle of the user program running in the process of creating-destroying-creating-destroying
2. The current client only applies for the management of the thread pool resources. For the client destruction, there is no corresponding shutdown destruction process, which is likely to cause thread pool resource leakage
Ideas
1. Create a LifeCycle
2. The unity of the life cycle inherits it

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2819

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2854

**Comment by zongtanghu** [comment]
Hi chuntaojun @chuntaojun , this issue can be assign to me , thanks.

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2819

**Comment by yfh0918** [comment]
这个Issue在本次迭代完成吗？

**Comment by chuntaojun** [comment]
> 这个Issue在本次迭代完成吗？

 You can communicate with @zongtanghu , Current issue is that the student claimed responsibility

**Comment by zongtanghu** [comment]
@yfh0918 this issue's pr will be put forward this week.
