### ISSUE TITLE
nacos 1.1.3 config data not exist

### ISSUE THREAD

**Issue by zhubinjqjy** [alibaba/nacos#1818]
## Issue Description

Type: *bug report* or *feature request*
1.1.3版本下，再nacos中新建的配置文件，需要去除后缀名才能读取配置文件信息，反之读取不到，而NacosPropertySourceLocator中，对文件的后缀名以默认properties为准，不传有DOT，在浏览器中发get请求可以获取到
![image](https://user-images.githubusercontent.com/50281090/64415161-5d116080-d0c7-11e9-9f28-0ab37cd826e7.png)

![image](https://user-images.githubusercontent.com/50281090/64415221-71edf400-d0c7-11e9-831e-53b43c1a0941.png)

![image](https://user-images.githubusercontent.com/50281090/64415249-80d4a680-d0c7-11e9-9e81-dd47b99f8e48.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.1.3

**Comment by chuntaojun** [comment]
你是用使用spring-cloud吗

**Comment by zhubinjqjy** [comment]
对


| |
朱斌
邮箱：zhubin94374@163.com
|

签名由 网易邮箱大师 定制

On 09/07/2019 10:35, liaochuntao wrote:

你是用使用spring-cloud吗

**Comment by chuntaojun** [comment]
> 对 | | 朱斌 邮箱：zhubin94374@163.com | 签名由 网易邮箱大师 定制 On 09/07/2019 10:35, liaochuntao wrote: 你是用使用spring-cloud吗 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

那这不是nacos的问题，应该和spring-cloud-alibaba-nacos有关系，我将此issue移动至spring-cloud-aliabab-nacos处，你可在看下spring-cloud-alibaba的wiki：https://github.com/alibaba/spring-cloud-alibaba/wiki

**Comment by zhubinjqjy** [comment]
好的，谢谢


| |
朱斌
邮箱：zhubin94374@163.com
|

签名由 网易邮箱大师 定制

On 09/07/2019 10:43, liaochuntao wrote:

Closed #1818.
