### ISSUE TITLE
Tomcat deployment war cannot implement automatic registration service

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#1819]
我用了1.1.0版本，sca用了最新版本，其中registration.setPort()方法显示过期了。类似#341的问题，但#341中提供的两种方式在新版本都无效。

**Comment by sundong1982** [comment]
有报错 idea没抛错导致  已解决

**Comment by cnsu-cmh** [comment]
您好，类似#341的问题，但#341中提供的两种方式在新版本都无效。 新版本的war包放tomcat里面您是怎么注册到nacos的呢？

**Comment by huayangchan** [comment]
您好，请问nacos怎么打成war包运行的？
