### ISSUE TITLE
Nacos only supports parameters defined by properties without using spring cloud.

### ISSUE THREAD

**Issue by czbabl** [alibaba/nacos#1821]
![image](https://user-images.githubusercontent.com/4616859/64470104-1deb1a00-d170-11e9-9608-c3b9454705ed.png)
![image](https://user-images.githubusercontent.com/4616859/64470110-2fccbd00-d170-11e9-97f2-5f742b5f9f3b.png)
![image](https://user-images.githubusercontent.com/4616859/64470111-407d3300-d170-11e9-8d6c-a64d79db741c.png)

我把所有的配置都放到了nacos-config-example.properties中，启动可以生效（包括端口，数据源配置）。
nacos-config-example.properties改成Yml就不行了（Yml中内容是yml格式的）。

**Comment by chuntaojun** [comment]
你是使用nacos-springboot吗？

**Comment by czbabl** [comment]
<dependency>
  <groupId>com.alibaba.boot</groupId>
  <artifactId>nacos-config-spring-boot-starter</artifactId>
  <version>0.2.2</version>
</dependency>

对的


------------------
陈阵
 


 




------------------ 原始邮件 ------------------
发件人: "liaochuntao"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 晚上10:14
收件人: "alibaba/nacos"<nacos@noreply.github.com>;
抄送: "霸先"<czbabl@vip.qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/nacos] Nacos only supports parameters defined byproperties without using spring cloud. (#1821)




你是使用nacos-springboot吗？

**Comment by chuntaojun** [comment]
> <dependency> <groupId>com.alibaba.boot</groupId> <artifactId>nacos-config-spring-boot-starter</artifactId> <version>0.2.2</version> </dependency> 对的

参考下这里：https://github.com/nacos-group/nacos-spring-boot-project/wiki

**Comment by czbabl** [comment]
好的谢谢


------------------
陈阵
 


 




------------------ 原始邮件 ------------------
发件人: "liaochuntao"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 上午9:06
收件人: "alibaba/nacos"<nacos@noreply.github.com>;
抄送: "霸先"<czbabl@vip.qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [alibaba/nacos] Nacos only supports parameters defined byproperties without using spring cloud. (#1821)



 
 com.alibaba.boot nacos-config-spring-boot-starter 0.2.2  对的
  
参考下这里：https://github.com/nacos-group/nacos-spring-boot-project/wiki
