### ISSUE TITLE
Nacos has a high CPU occupancy

### ISSUE THREAD

**Issue by imgoby** [alibaba/nacos#1829]
![image](https://user-images.githubusercontent.com/27885492/64506031-a56b9100-d308-11e9-930b-db1aa1fdea84.png)

![image](https://user-images.githubusercontent.com/27885492/64506111-ecf21d00-d308-11e9-997d-4c46ffedbcb6.png)

![image](https://user-images.githubusercontent.com/27885492/64506904-c4b7ed80-d30b-11e9-8a2b-edc7abf211d2.png)

**Comment by chuntaojun** [comment]
直接jstack分析下线程，之前有类似的原因，是NIO selector那边

**Comment by nkorange** [comment]
类似问题在 #1936 进行跟踪
