### ISSUE TITLE
Some questions about the future implementation of nacos

### ISSUE THREAD

**Issue by yuzhuyang1998** [alibaba/nacos#1837]
尊敬的nacos开发者团队:
       你们好，我们最近基于学习的目的尝试部署并成功测试了你们开发的工程，给予一些使用上的问题，提出我个人的一些想法。
        一、nacos的bean更新交给了spring去完成，假如将临时变量写在bean中将会出现数据不一致的问题，其对项目的影响极可能是无法复原的。是否可能通过开关控制是使用set方式还是更新示例的方式来实现。such as @NacosSetBean or @NacosConstructBean。
        二、这一点是基于第一点的延申，可以看到nacos判断了时间戳来判断bean的有效性，能否在这一点上提升至根据配置文件具体被修改的值来控制bean的更新域。
        最后，向敢于分享，敢于开创，敢于超越的你们，致以最诚挚的敬意。
        此致，敬礼。

**Comment by chuntaojun** [comment]
你是使用nacos-spring-project or nacos-springboot-project，还是spring-cloud-alibaba-nacos？目前的话，关于对象的更新，是参照spring的思想来做的

**Comment by nkorange** [comment]
> > 有的是直接在run里面会压的
> 
> 我建议有些任务的run()方法，干脆抽离出一个独立的方法，像`new Runable().run()`真的看着不雅，ヽ(●-`Д´-)ノ

关于代码优化，欢迎贡献！

**Comment by nkorange** [comment]
https://nacos.io/zh-cn/docs/feature-list.html 关于代码质量，已经成立专项进行整治，欢迎共建。
