### ISSUE TITLE
Get configurations api response header Content-Type value issure

### ISSUE THREAD

**Issue by pengweiqhca** [alibaba/nacos#1839]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Get configurations api response  value  should be related to config format.

Config format checked xml, but response header `Content-Type` value is `application/json`.

### Describe what you expected to happen

`text/xml` or `application/xml`

**Comment by cafechen** [comment]
@i will solve it@

**Comment by cafechen** [comment]
Has this issue been fixed?

**Comment by zongtanghu** [comment]
Can you fix this issue? @wangweizZZ

**Comment by wangweizZZ** [comment]
ok，i will fix it
