### ISSUE TITLE
Unnecessary new instances when isSendBeatOnly() is true.

### ISSUE THREAD

**Issue by darkness463** [alibaba/nacos#1842]
Line 615 ~ 622 in `com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore` of current master branch.
The creation and update of `receivedKeysMap` and `batch` is unnecessary when `switchDomain.isSendBeatOnly()` return true.

![image](https://user-images.githubusercontent.com/11989727/64682810-b35e1500-d4b4-11e9-8763-178875cab24c.png)

**Comment by nkorange** [comment]
Thanks for your advice.
