### ISSUE TITLE
namingService keep update service instance after unSubscribe all listeners

### ISSUE THREAD

**Issue by EZLippi** [alibaba/nacos#1858]
## namingService keep polling service instance after unSubscribe

Type: feature request

### Describe what happened (or what feature you want)

when subscribe for some service,HostReactor will fetch service instances from nacos server every one second, but after unSubscribe all listeners, this updateTask should be removed for avoid unnecessary resource use, but as i see, the updateTask will nerver got removed.

**Comment by nkorange** [comment]
Welcome to fix it.
