### ISSUE TITLE
web ui 配置管理回滚到第一条该配置列表找不到该条配置，通过新建同一个Data ID时历史版本数据又有了

### ISSUE THREAD

**Issue by eshun** [alibaba/nacos#186]
web ui 配置管理在配置列表新建一个test配置信息通过更改配置信息产生多条历史版本，回滚到第一条历史版本返回配置列表该配置消失了。

**Comment by yanlinly** [comment]
create rollback is delete

**Comment by yanlinly** [comment]
#434 is same problem.  we will enhance it at 1.0 version

**Comment by eacdy** [comment]
same problem.
