### ISSUE TITLE
Dubbo external configuration cannot achieved loadbalance

### ISSUE THREAD

**Issue by cyj862198490** [alibaba/nacos#1861]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
In Dubbo environment, once dubbo. protocol. port is configured in the external configuration, load balancing cannot be achieved. The same configuration can achieve load balancing by configuring dubbo. protocol. port locally and without configuring dubbo. protocol. port externally.

### Describe what you expected to happen
In Dubbo environment, dubbo. protocol. port is configurated in the external configuration, which can realize load balancing of random policy in Dubbo.

### How to reproduce it (as minimally and precisely as possible)

1. Create a project in Dubbo environment to create a unified dependency management
2. Creating service providers and service consumers
3. Make Dubbo's External Configuration

### Tell us your environment
<dubbo.version>2.7.3</dubbo.version>
<dubbo-kryo.version>2.7.3</dubbo-kryo.version>
<dubbo-actuator.version>2.7.3</dubbo-actuator.version>
<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
<spring-cloud-alibaba.version>0.9.0.RELEASE</spring-cloud-alibaba.version>
<alibaba-spring-context-support.version>1.0.2</alibaba-spring-context-support.version>

**Comment by KomachiSion** [comment]
Please use latest version to retry. If still has problem, please open a new issue let us know.
