### ISSUE TITLE
Not found MySQL8 driver

### ISSUE THREAD

**Issue by Dhweicheng** [alibaba/nacos#1865]
Nacos MySQL driver version 5.1.34，MySQL8 is not supported.
![TIM截图20190924102439](https://user-images.githubusercontent.com/13899021/65476867-de823480-deb6-11e9-94d2-6280ae778516.png)

com.alibaba.nacos.naming.healthcheck.MysqlHealthCheckProcessor
![222222](https://user-images.githubusercontent.com/13899021/65477506-1be7c180-deb9-11e9-834d-18baac62053c.png)

**Comment by nkorange** [comment]
Follow #855 to fix it.
