### ISSUE TITLE
Provide Label ability for Naming Service into NACOS for complex multi-DC scenario.

### ISSUE THREAD

**Issue by yangyshdan** [alibaba/nacos#187]
There is a scenario that for Nacos's naming search service, one single domainname may have different IPs that come from multiple datacenters. When one single client requests domianname's associated IPs from Nacos, Nacos logic could be only return the IPs that are in the same datacenter where the client server locates. 

The above scenario can be achieved by Nacos with the implementation of Label. Several notes:
 1. Nacos should provides an API that can associate the IP/hostname with different labels. The labels could be datacenter, region, application, or whatever that could be used for describe an IP.
 2. Rule could be applied to Nacos to specify the rules about how to filter the result of the IPs for naming request. For example: for source IP of the naming search request with certain label, return the IP with the same label. (label could represent datacenter, region, etc).

API Reference for associate the IP/hostname with labels:
 - API URL: /nacos/v1/ns/applyHostLabel
 - Input Parameter: 
        - String: IP
        - String: hostname
        - Hashmap<String, String>: labels

API Reference for hosts filtering, only target hosts matches certain label key/value that is from the client host should be returned.
 - API URL: /nacos/v1/ns/applyNamingResultFiltering
 - Input Parameter: 
        - String: Domainname
        - Hashmap<String>: labels (Note, label value could be *, which means matching any values)

 A callback URL should be added in case target servers are occasionally online and offline, so that Nacos server can call callback to reflect the changes.  For example, if certain IP is not marked with Label when requested, an async call should be called with the callback URL to fetch the labels.

Definition of Callback
 - Input Parameter:
      - String: URL
The return should be fixed format, such as
      - String: Hashmap<String, String>: labels

**Comment by nanamikon** [comment]
A good feature！ What's more, we have to query cmdb for lables when registe a new instance， it's better to add a paramter when registe a new instance  for adding a callback url  as follow

Definition of Call back 

-  Input Parameter:
       - String: IP

- Return :
       - String: Hashmap<String, String>: labels

**Comment by yangyshdan** [comment]
> A good feature！ What's more, we have to query cmdb for lables when registe a new instance， it's better to add a paramter for callback url when registering a new instance as follow
> 
> Definition of Callback
> 
> * Input Parameter:
>   - String: IP
> * Return :
>   - String: Hashmap<String, String>: labels
> 
> Nacos server can get labels from the callback url ， and then registe the instance with the labels

Original proposal has been update to reflect this idea.
