### ISSUE TITLE
instance will got deleted when one nacos server down

### ISSUE THREAD

**Issue by EZLippi** [alibaba/nacos#1873]
### Describe what happened (or what feature you want)

as we know ,nacos servers use distroMapper to sharding the register/heartbeat requests,only one nacos server hold the latest heartbeat timestamp of a service instance,if some nacos server shutdown for some reason for over 30 seconds, within 30 seconds ,the client cannot send heartbeat to nacos because other server treat the dead sever still alive, will redirect heartbeat request to the dead server,after 30 seconds ,other servers treat the dead server as unhealthy,distroMapper will reSharding, so the ClientBeatCheck task will mark the services earlier processed by the dead sever unHealthy, because the heartbeat timestamp is too old.

the delete log is as follow:
019-09-25 13:40:08.763 INFO [ClientBeatCheckTask] [AUTO-DELETE-IP] service: tracklist-listenlist-service:thrift, ip: {"app":"","clusterName":"default-cluster","enabled":true,"ephemeral":true,"healthy":false,"instanceHeartBeatInterval":29217,"instanceHeartBeatTimeOut":87651,"instanceId":"172.28.7.26#9161#default-cluster#tracklist-listenlist-service:thrift","ip":"172.28.7.26","ipDeleteTimeout":146085,"lastBeat":1569388927431,"marked":false,"metadata":{"preserved.heart.beat.timeout":"87651","version":"3.0.17","createTimestamp":"1567762329690","preserved.heart.beat.interval":"29217","preserved.ip.delete.timeout":"146085"},"port":9161,"serviceName":"tracklist-listenlist-service:thrift","tenant":"","weight":1000}

although the client will send heartbeat to the new server and reDeregister,but consumer will find no active provider for about 5 seconds.

**Comment by nkorange** [comment]
Now the expire timeout marking Nacos server unhealthy is already an entry in SwitchDomain, but not configurable via API. It should be configurable and the default value should be less than ```instance unhealthy timeout - heartbeat interval```.

**Comment by EZLippi** [comment]
this will not work for me, i replace the default udp push  + timer pull to http long polling,so if the server change a instance to unHealthy, the client will know immediately

**Comment by nkorange** [comment]
> this will not work for me, i replace the default udp push + timer pull to http long polling,so if the server change a instance to unHealthy, the client will know immediately

The change of the behaviors of subscriber doesn't influence the providers heartbeat and how Nacos server handles the expired instances.
