### ISSUE TITLE
The subscribers function of Service  Management can't return the right subscriber list on cluster mode

### ISSUE THREAD

**Issue by yuchaozhou** [alibaba/nacos#1878]
After looking at the code, I found that the return error was written when the synchronization loop got the subscriber.

see com.alibaba.nacos.naming.core.SubscribeManager.getSubscribers() method, at 92 line.

### Tell us your environment
Nacos 1.1.3 version

thank you.

**Comment by yuchaozhou** [comment]
``

**Comment by nkorange** [comment]
Can you paste the error detail?

**Comment by yuchaozhou** [comment]
![图片](https://user-images.githubusercontent.com/1917747/66813822-10dbfa80-ef68-11e9-89db-de6f0b42d5fe.png)
This is a loop query information method，  but the **return statement** is written early
