### ISSUE TITLE
nacos list of services is out of sync

### ISSUE THREAD

**Issue by VolcanoOves** [alibaba/nacos#1880]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

升级到1.1.3之后，使用3台节点的集群模式，用一段时间之后（可能是一周，或者几天，我没注意），三个节点的服务列表就会出现不一致，导致服务调用超时等错误。

After the upgrade to 1.1.3, with the cluster mode of 3 nodes, after a period of time (maybe a week, maybe a few days, I didn't notice), the service list of the three nodes will be inconsistent, resulting in the service call timeout and other errors.

### Describe what you expected to happen

我猜测可能是同步机制有问题，主节点的服务大多数情况下都是正常显示的，备用节点展示服务列表会存在大量不健康示例，但是这些示例可能该是正常的或者是该被移除掉的，总之需要能够正常展示服务列表，并及时更新备用节点的服务列表。

I guess may be there is something wrong with the synchronization mechanism, the master node services in most case, it is normal display, standby node shows service list will exist a large number of unhealthy examples, but the samples may be this is normal or should be removed, anyhow need to be able to show normal service list, the list of services and update the spare node.

### How to reproduce it (as minimally and precisely as possible)

与上个版本情况相同，都是部署之后开始是正常的，一段时间后就有问题了。

### Tell us your environment

centOs 7 
openJdk 8
nacos 1.1.3

**Comment by nkorange** [comment]
hi，问下有问题的节点是少数据还是多数据了？有问题的节点之间数据是不是一样的？可以把截图分享一下。

**Comment by nkorange** [comment]
经排查是某个节点启动失败，导致还是旧版本所致
