### ISSUE TITLE
After getConfigAndSignListener(dataId, DEFAULT_GROUP, 10000, new Listener()) is used to obtain the configuration to add a Listener, if the configuration of the dataId is deleted in the configuration center, the client will receive a listening feedback configured as null every 29.5s.

### ISSUE THREAD

**Issue by mabingqian** [alibaba/nacos#1883]
After getConfigAndSignListener(dataId, DEFAULT_GROUP, 10000, new Listener()) is used to obtain the configuration to add a Listener, if the configuration of the dataId is deleted in the configuration center, the client will receive a listening feedback configured as null every 29.5s.

**Comment by mabingqian** [comment]
getConfigAndSignListener(dataId, DEFAULT_GROUP, 10000, new Listener()) 添加监听器配置后，如果配置中心手动删除了dataId的数据，客户端将每29.5秒收到一个配置为null的监听反馈。

**Comment by chuntaojun** [comment]
你可以在代码中进行判断去调用移除Listener的操作，自动删除Listener的操作我觉得并不太合适

**Comment by mabingqian** [comment]
是说在nacos界面删除，然后客户端会收到null



 
---Original---

**Comment by chuntaojun** [comment]
> 是说在nacos界面删除，然后客户端会收到null
> […](#)
> ---Original--- From: "liaochuntao"<notifications@github.com&gt; Date: 2019/10/24 13:12:06 To: "alibaba/nacos"<nacos@noreply.github.com&gt;; Cc: "Author"<author@noreply.github.com&gt;;"mabingqian"<272118565@qq.com&gt;; Subject: Re: [alibaba/nacos] After getConfigAndSignListener(dataId, DEFAULT_GROUP, 10000, new Listener()) is used to obtain the configuration to add a Listener, if the configuration of the dataId is deleted in the configuration center, the client will receive a listening feedback configured as null every 29.5s. (#1883) 你可以在代码中进行判断去调用移除Listener的操作，自动删除Listener的操作我觉得并不太合适 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我知道啊，这个不是bug，如果你要删除了data-id后，取消监听，先自己收到去判断，然后移除Listener
