### ISSUE TITLE
100 cpu useage in my Development environment

### ISSUE THREAD

**Issue by modouer** [alibaba/nacos#1890]
There has some problem when I use nacos,when I run it about 30 minites in my development enviroment,It takes 100 cpu useage.

How can I resovle this problem?
dose it has resovle in a new version?
 
my development environment list:
system:windows 10
development tool:IntelLij Idea 2018.3.1 
java version "1.8.0_25"
nacos version:1.10

![image](https://user-images.githubusercontent.com/37364577/65772119-309fb000-e16c-11e9-8316-6938f7c645df.png)

**Comment by nkorange** [comment]
Which thread occupies the most CPU resources?

**Comment by nkorange** [comment]
#1936 reported the similar problem. We will replace nio to nio2 in the next version.
