### ISSUE TITLE
The version of V1.1.3, in the console, the same name file for the two namespaces, delete one, and the other is gone! !

### ISSUE THREAD

**Issue by chenxing0755** [alibaba/nacos#1891]
V1.1.3的版本。
服务端，部署在centos 7.4
客户端， 浏览器  firefox quantum，系统 MAC OS 10.14 。

在控制台，两个命名空间，public和dev，分别有1个配置文件，二者同名（dataid相同）。
删除pubic命令空间中的一个配置文件，另一个命名空间dev的配置文件也不见了！

**Comment by nkorange** [comment]
这种情况一般不会出现，你这边能复现吗？
