### ISSUE TITLE
Switching from wifi to broadband network cable during local computer development; registration ip error

### ISSUE THREAD

**Issue by qjws** [alibaba/nacos#1893]
(一) ip注册错误问题
启动时192.168.235.1 注册到了 nacos; 发现ip未在本地局域网网段,
直接换上有线后 电脑ip变为 192.168.2.29 ;但是重启项目后 nacos还是235.1
删除nacos的服务列表,重启电脑等各种手段后也没有变化;
最后 临时配置文件将ip 写死 重启nacos显示ip为192.168.2.29;终于恢复正常
(二) 通过gateway不能访问到服务;
必须调用 网关的actuator/gateway/refresh接口 后才能正常调用;
--不知道这个问题跟nacos有没有关系

版本是:
springboot: 2.1.4.RELEASE
spring-cloud: Greenwich.SR1
nacos: 1.1.3
cloud gateway: 2.1.0.RELEASE

**Comment by nkorange** [comment]
这些问题请到alibaba/spring-cloud-alibaba咨询。
