### ISSUE TITLE
Restart the Dubbo service provider, Dubbo consumers have not been able to invoke the service

### ISSUE THREAD

**Issue by Python-IBM** [alibaba/nacos#1894]
## Issue Description

When the Dubbo consumer service is running, after the Dubbo provider service is stopped, the Dubbo provider service is restarted. The Dubbo consumer service can not be transferred to the service until the Dubbo consumer service is restarted.

### Describe what happened (or what feature you want)

I hope that when the Dubbo provider service is restarted, the Dubbo consumer can call the service right away.

### How to reproduce it (as minimally and precisely as possible)

1. Dubbo Consumer Services and Dubbo Provider Services Run Normally
2. Dubbo Consumer Services Run Normally and Dubbo Provider Services Stopped
3. Restart Dubbo provider service，It takes a long time to transfer to the Dubbo provider service, about a minute.

### Tell us your environment
1、windows
2、jdk8.0
3、nacos-server-1.1.3
4、dubbo2.7.3

**Comment by majjfootman** [comment]
I met the same problem. How did you solve it? Thank you @Python-IBM

**Comment by Starbucksstar** [comment]
+1,这个问题很常见，重新部署provider后难道还需要把所有consumer都要重启一遍吗
