### ISSUE TITLE
 @ConfigurationProperties和@NacosConfigurationProperties

### ISSUE THREAD

**Issue by dxkkb24** [alibaba/nacos#1896]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
@ConfigurationProperties 可以应用在类跟方法上
@NacosConfigurationProperties 只能加在类上
这样使用nacos做配置中心对代码的入侵太大 ，能不能nacos的注解功能跟spring的功能保持一致

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
Nacos annotations are designed to better solve which objects need refersh and which don't. It makes sense to redesign these annotations. If they are directly compatible with Spring annotations, many objects or attributes that don't need to be refreshed will be included in the scope of monitoring
