### ISSUE TITLE
@Scheduled not work when use nacos config

### ISSUE THREAD

**Issue by wmj765** [alibaba/nacos#1897]
I use @Scheduled to start a job, it does not work.
but when i delete config-file on nacos(online) and keep config-file in local only,it works.

my code like this
`
@EnableScheduling
@RefreshScope
@Component
public class ScheduleTest {
	
	 @Scheduled(cron="0/1 * * * * ?") 
	 public void test() {
		 System.out.println("======================================");
	 }

}`

below are server version
spring-boot : 2.1.4.RELEASE
spring-cloud-starter-alibaba-nacos-discovery : 0.2.2.RELEASE
spring-cloud-starter-alibaba-nacos-config : 0.2.2.RELEASE

**Comment by wmj765** [comment]
More information:
@Scheduled do not work when the project  is websocket-server , but spring-boot-web project is normal; is it cause by  some thread is blocked or the threadpool is small? but why local config-file is ok?

**Comment by nkorange** [comment]
This is not a Nacos related problem, maybe you can search it on web.
