### ISSUE TITLE
Nacos console service list grouping is always DEFAULT_GROUP

### ISSUE THREAD

**Issue by shf675** [alibaba/nacos#1898]
nacos控制台服务列表分组总是DEFAULT_GROUP
服务以及配置了spring.cloud.nacos.config.group=OBILLING_GROUP
但控制台还是显示为DEFAULT_GROUP
![image](https://user-images.githubusercontent.com/7691856/66110913-53154b80-e5fa-11e9-8b82-2d6e3a7587b8.png)

**Comment by nkorange** [comment]
```spring.cloud.nacos.config.group``` is used for config module to specify group, not for service discovery.
