### ISSUE TITLE
ICON May be wrong.

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#19]
First, I'm proud to see our `Nacos` has been released! 

I find the picture above here: <https://nacos.io/#/docs/what-is-nacos.md?lang=en-us>

![image](https://user-images.githubusercontent.com/9031050/43460058-1c5cd116-9502-11e8-82e1-13cc60b65280.png)

**AFAIK, The icon of `Spring Cloud` is not OK. This is the logo of `Spring Cloud中国社区` rather than `Spring Cloud`. 
I don't think use the logo of `Spring Cloud中国社区` is a good idea, since is the forum is never a official group.**

I think WE SHOULD use official icon which Can be found here: <https://spring.io/projects> .

**Comment by xuechaos** [comment]
Thanks, you are right, the logo is wrong, I will replace this logo.
![image](https://user-images.githubusercontent.com/3983999/43464140-e0b6339a-950c-11e8-9ac7-6f8b056833ef.png)
Thanks again.

**Comment by xuechaos** [comment]
The problem has been modified in this commit. https://github.com/nacos-group/nacos-group.github.io/commit/58a58e4fd789d2334b1aec3523d59ba2af2ba06f  Mention your name. Thanks again.

![image](https://user-images.githubusercontent.com/3983999/43465280-9d088276-950f-11e8-9ed3-1022ff80efd6.png)
