### ISSUE TITLE
please check if the data is correct

### ISSUE THREAD

**Issue by howard-huang** [alibaba/nacos#1902]
I have questions at the test data, the WRITE(register instance) and READ(query instance) data are the same on table, please check~

Type: *test report*

**Comment by howard-huang** [comment]
https://nacos.io/en-us/docs/nacos-naming-benchmark.html

**Comment by nkorange** [comment]
The test we executed followed such steps: register, query and deregister. So in each context we have the same service count and instance count for register, query and deregister. The test report reflects such steps so the data is correct.
