### ISSUE TITLE
Publish configuration issues via API

### ISSUE THREAD

**Issue by 39954693** [alibaba/nacos#1904]
通过调用 Nacos Open API 向 Nacos Server 发布配置命令如下：
curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=HelloWorld"

如何将yml中的配置（多行或者折行）放入到上述命令的content参数中，
比如：
user:
  name: xxx

**Comment by nkorange** [comment]
You can refer to this article:
https://dwmkerr.com/quick-tip-sending-newlines-with-curl/
