### ISSUE TITLE
About heart beat for apache dubbo

### ISSUE THREAD

**Issue by ggzggzggz** [alibaba/nacos#1905]
Nacos client's heart beat is based of service(apache dubbo), when the number of the services grow up more and more, such as 10W+, the Nacos server will waste high CPU. there is the solution for this?

**Comment by nkorange** [comment]
Try to scale up your Nacos cluster to more nodes, like 20 nodes. We are working on replacing this heartbeat to a gRPC connection.

**Comment by ggzggzggz** [comment]
I have resolved it by use netty, and for more, as dubbo service healthy check beat, i have changed to use machine beat to resolve the problem that high TPS in nacos's server. And in the end, i gave up using nacos as dubbo service registry center because it waste more than 3 times RAM based on zookeeper.

**Comment by nkorange** [comment]
> I have resolved it by use netty, and for more, as dubbo service healthy check beat, i have changed to use machine beat to resolve the problem that high TPS in nacos's server. And in the end, i gave up using nacos as dubbo service registry center because it waste more than 3 times RAM based on zookeeper.

I'm sorry to hear that but I respect your choice. We are working on improving this heartbeat mechanism now and hope to see you again when it's done.
