### ISSUE TITLE
Set a new thread pool here, but do not open the Notifier task, whether to add executor.execute(new Notifier());

### ISSUE THREAD

**Issue by fangxuee** [alibaba/nacos#1906]
https://github.com/alibaba/nacos/blob/db8015fbc7fb7683a758e8a02083eaff0d6664dd/client/src/main/java/com/alibaba/nacos/client/naming/core/EventDispatcher.java#L142

**Comment by nkorange** [comment]
I think this is a redundant logic since the setted  executor is not used anymore.
