### ISSUE TITLE
config

### ISSUE THREAD

**Issue by muhanSng** [alibaba/nacos#1909]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by muhanSng** [comment]
As for database configuration, the source code does not support MySQL8 at present, so it needs to be modified by itself. For boot project, database configuration does not support YML format, only property format.

关于数据库配置，目前源码不支持MySQL8,需要自行修改才可以，对于boot项目，数据库配置不支持yml格式，只支持properties 格式

**Comment by nkorange** [comment]
MySQL 8可以参考 https://github.com/alibaba/nacos/pull/855
关于配置不支持yml的问题，麻烦将issue提到 https://github.com/nacos-group/nacos-spring-boot-project
