### ISSUE TITLE
the nacos container init failed

### ISSUE THREAD

**Issue by shuangxi588** [alibaba/nacos#1911]
## Issue Description
I use k8s to depoy nacos service. the nacos service can be "running" status,but the next day status is "Init:CrashLoopBackOff"

### Describe what happened (or what feature you want)
# kubectl -n nacos get pods
NAME                  READY   STATUS                  RESTARTS   AGE
mysql-master-q99dl   1/1     Running                 0          44h
mysql-slave-fjz4w    1/1     Running                 0          44h
nacos-0              0/1     Init:CrashLoopBackOff   92         21h
nacos-1              0/1     Init:CrashLoopBackOff   92         21h
nacos-2              0/1     Init:CrashLoopBackOff   92         21h

### Tell us your environment

k8s v1.12.3

### Anything else we need to know?

Events:
  Type     Reason   Age                       From                                Message
  ----     ------   ----                      ----                                -------
  Normal   Pulling  57m (x84 over 21h)        kubelet, vm-shalmk98.aegonthtf.com  pulling image "harbor.aegonthtf.com/thirdparty/nacos/nacos-peer-finder-plugin:latest"
  Warning  BackOff  2m24s (x2088 over 7h32m)  kubelet, vm-shalmk98.aegonthtf.com  Back-off restarting failed container

the nacos service is ok.

**Comment by nkorange** [comment]
@shuangxi588 Is there any crash log?

**Comment by shuangxi588** [comment]
I deleted this,it’s running status now.
                               initContainers:
                - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/nacos/plugins/peer-finder"
              name: plugindir


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Fury Zhu <notifications@github.com>
发送时间: Sunday, November 10, 2019 11:54:01 PM
收件人: alibaba/nacos <nacos@noreply.github.com>
抄送: shuangxi <shuangxi588@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [alibaba/nacos] the nacos container init failed (#1911)


@shuangxi588<https://github.com/shuangxi588> Is there any crash log?

―

**Comment by nkorange** [comment]
Use ```kubectl logs -p``` to see the previous logs of a pod.
