### ISSUE TITLE
NacosConfigListener callback  not invoked when application starts

### ISSUE THREAD

**Issue by mf1232011** [alibaba/nacos#1914]
## Issue Description
nacos client: v1.1.1
nacos server: v1.1.3
NacosConfigListener callback not invoked when application starts.
After I modify the configuration, the callback is invoked.

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I update nacos-client from 0.8.0 to 1.1.1.

### Describe what you expected to happen
I hope the configuration can be pushed to client when application starts even if I don't modify properties, so that my application may have a right initial state. It works well with nacos-client-0.8.0.

### How to reproduce it (as minimally and precisely as possible)

1. update nacos-client to 1.1.1
2. nacos-server 1.1.3

### Tell us your environment
code:
    @NacosConfigListener(dataId = "hello")
    public void onHello(String config) {
        System.out.println(config);
    }

**Comment by chuntaojun** [comment]
please tell me which version of nacos-spring-context you use

**Comment by morisenmen** [comment]
I have the same question.My Environment config like this:
nacos-client to 1.1.3
nacos-server 1.1.3
nacos-spring-context:0.3.3.
nacos-config-spring-boot-starter:0.2.3

**Comment by nkorange** [comment]
Same problem with #2004
