### ISSUE TITLE
Unable to insert nacos-mysql.sql data into mysql database

### ISSUE THREAD

**Issue by zgweimin** [alibaba/nacos#1915]
版本： nacos-1.1.3   mysql: 5.7（pxc集群）
在插入nacos-mysql.sql到数据库时提示
INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');
[Err] 1105 - Percona-XtraDB-Cluster prohibits use of DML command on a table (nacos_config.roles) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER

**Comment by nkorange** [comment]
This may have something to do with your MySQL cluster configuration about pxc_strict_mode.
