### ISSUE TITLE
*feature request* ClientWorker supports setting LongPollingRunnable task interval

### ISSUE THREAD

**Issue by RekaDowney** [alibaba/nacos#1917]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

ClientWorker#checkConfigInfo executes every 10 milliseconds now. As the code show:

```java
    public ClientWorker(final HttpAgent agent, final ConfigFilterChainManager configFilterChainManager) {

       // Omit other code

        executor.scheduleWithFixedDelay(new Runnable() {
            public void run() {
                try {
                    checkConfigInfo();
                } catch (Throwable e) {
                    LOGGER.error("[" + agent.getName() + "] [sub-check] rotate check error", e);
                }
            }
        }, 1L, 10L, TimeUnit.MILLISECONDS);
    }
```

### Describe what you expected to happen

　　I want to be able to customize the interval of checkConfigInfo  task. For example, provide a new configuration item:
`spring.cloud.nacos.config.check-interval-millis = 1000`
　　which can change the task execution interval to 1 second.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

nacos-client form 1.0.0 to 1.1.3.

Maven dependencies:

```xml

<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.0.0</version>
</dependency>

<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.1.3</version>
</dependency>

```

**Comment by chuntaojun** [comment]
This is not a long rotation interval, it is a time to do a split check on the listening task

**Comment by Reka-Downey** [comment]
> This is not a long rotation interval, it is a time to do a split check on the listening task

But it will send a request to the nacos server, 30 microservice instances will be sent 30 times, the K8S ingress logs are all squeezed by request log.

**Comment by chuntaojun** [comment]
> > This is not a long rotation interval, it is a time to do a split check on the listening task
> 
> But it will send a request to the nacos server, 30 microservice instances will be sent 30 times, the K8S ingress logs are all squeezed by request log.

checkConfigInfo is to determine whether to create a long polling monitoring task, not to initiate a request。If your nacos-server is 1.2.1, you need to re-download and deploy nacos-server. There was a problem with this version before, which has now been fixed
