### ISSUE TITLE
Dear, nacos have some problems with security scanning and vulnerability testing. Is there a related plan?

### ISSUE THREAD

**Issue by zhiguo-yang** [alibaba/nacos#1918]
先列举3个：
1.	登陆认证绕过漏洞（高危)
漏洞描述：
登录时通过更改返回的status code值即可访问系统。
漏洞地址（nacos系统：全局认证）：
举例：nacos系统》登陆
2.	没有CSRF保护的HTML表单（中危）
漏洞描述：
跨站点请求伪造，也称为一键式攻击或会话骑行，缩写为CSRF或XSRF，是一种恶意利用网站，从而从网站信任的用户传输未经授权的命令。
漏洞地址（nacos系统：全局表单）：
举例：nacos系统》配置管理》配置列表》新增（一键添加数据）
3.	账号密码（认证）漏洞（中危）
漏洞描述：
账号密码（认证）漏洞包含：登录时账号密码明文传输、用户名可以枚举、账号密码弱加密、验证码校验出错，使用GET方式传输认证信息等。
漏洞地址（微服务认证中心、nacos系统：全局认证）：
举例：nacos系统（登录时账号密码明文传输、没有防暴力破解机制）。

**Comment by nkorange** [comment]
登录和权限控制正在开发，可以参考 #1105
