### ISSUE TITLE
Can you support application name search?

### ISSUE THREAD

**Issue by Python-IBM** [alibaba/nacos#1920]
## Issue Description

Type:*feature request*

### Describe  what feature you want

I hope that Nacos management background supports application name search, which can only be found through the service name of the interface at present. It is not very intuitive to see which non-Web applications are starting.

**Comment by nkorange** [comment]
There is no builtin property of application name in Nacos. Maybe you are talking about filtering services with their metadata?

**Comment by Python-IBM** [comment]
Instead of filtering through metadata, I want to display exposed services through spring application name in the Nacos management background.

**Comment by nkorange** [comment]
> Instead of filtering through metadata, I want to search and display exposed services through spring application name in the Nacos management background.

Nacos doesn't bind with spring, so the application name has to be reflected to some common property in Nacos, like metadata.
