### ISSUE TITLE
 NACOS 1.0.0 failed to log out instance using API and restart after logout

### ISSUE THREAD

**Issue by devin01** [alibaba/nacos#1922]
NACOS1.0.0 使用api注销实例失败,注销后会重新启动
https://nacos.io/zh-cn/docs/open-api.html#2.12

NACOS 1.0.0 failed to log out instance using API and restart after logout
Https://nacos.io/zh-cn/docs/open-api.html#2.12

Need to offline instance method

**Comment by nkorange** [comment]
You can set 'enabled=false' when you invoke the update instance method.
