### ISSUE TITLE
About the nacos server address

### ISSUE THREAD

**Issue by bg1011** [alibaba/nacos#1930]
Hi,
  I find many differ configs when I use nacos for Config or Name Center，eg:
   // for dubbo service register
   dubbo.registry.address = nacos://127.0.0.1:8848
  // for spring boot config server.
  nacos.config.server-addr = 127.0.0.1:8848
  // for spring boot naming server
  nacos.discovery.server-addr=127.0.0.1:8848
  // for spring cloud naming server.
  spring.cloud.nacos.discovery.server-addr = 127.0.0.1:8848
  // for spring cloud config server.
  spring.cloud.nacos.config.server-addr=127.0.0.1:8848

    I must give different configurations when I use config and naming service meanwhile, 
whether the uniform configurations are available or provide default configurations, eg:
nacos.server.address=127.0.0.1:8848

thinks.

**Comment by nkorange** [comment]
I understand your concern, but these parameters are defined and read by each frameworks, which are out of our reach. I will forward your suggestion to Dubbo/SpringCloud team.
