### ISSUE TITLE
 expose metrics data to elasticsearch

### ISSUE THREAD

**Issue by Fyee** [alibaba/nacos#1931]
![image](https://user-images.githubusercontent.com/34262309/66698174-3a014e80-ed0e-11e9-8103-ccd248f0aad4.png)
I want  expose metrics data to elasticsearch,but i dont know
how to config elasticsearch username and password in nacos application.properties

**Comment by nkorange** [comment]
These parameters are standard Spring Boot parameters. Please refer to Spring Boot documents to seek for your answers.
