### ISSUE TITLE
Updating service info waste the CPU time on all sides

### ISSUE THREAD

**Issue by michaelmao999** [alibaba/nacos#1934]
Nacos will create one thread to update service info for each Dubbo service (HostReactor.updateServiceNow) on both service consumer and provider side, no matter whether push service works.
when the number of the services grow up more and more, all servers(the Nacos server, Dubbo service consumer and provider) will waste a lot of CPU time.

**Comment by nkorange** [comment]
If push service works, this polling interval is by default 10 seconds. The Nacos client have to keep a heartbeat with the server.

We are planing to change this polling to a merged gRPC connection, but this work has no definite time schedule now.

**Comment by michaelmao999** [comment]
There are two tasks, one is to send heartbeat data, another is to get service instance info. I make some chnges to provide batch update ability.
you can see detailed change on following URL.
https://github.com/michaelmao999/nacos/commits/develop

**Comment by nkorange** [comment]
> There are two tasks, one is to send heartbeat data, another is to get service instance info. I make some chnges to provide batch update ability.
> you can see detailed change on following URL.
> https://github.com/michaelmao999/nacos/commits/develop

Please create a PR to alibaba/nacos so we can get a better look at your work.

**Comment by nkorange** [comment]
Will be tracked in #2154
