### ISSUE TITLE
Cannot support multiple IP addresses/port on a computer in cluster mode

### ISSUE THREAD

**Issue by michaelmao999** [alibaba/nacos#1939]
Sometimes, the developer have to set up clustering environment on a computer. There are two cases that can not be support.
1.  Run multiple Nacos instance with the same IP address and different IP port on a computer.
2. Run multiple Nacos instance with multiple IP address and the same IP port on a computer (Spring boot will start web server bind all IP address by default).

Please see my bug fixing with the following URL.
https://github.com/michaelmao999/nacos/commit/2208a5e78048aefc1c8e6540c33477eaa4a353ae

**Comment by nkorange** [comment]
I think these two modes have already been supported in Nacos.
