### ISSUE TITLE
Avoiding too many threads to be created for longPull task

### ISSUE THREAD

**Issue by michaelmao999** [alibaba/nacos#1940]
ClientWorker will create thread pool based on available CPU processor for long pulling service.
But in most case, there are only one long pulling task for getting Nacos config info.

For detail, please see my bug fixing with the following URL.
https://github.com/michaelmao999/nacos/commit/00119e1ed34ef62ab17f9d3753efe7946cc2d57e

**Comment by Albert-Hugo** [comment]
So , what is needed for this? What is wrong with your solution ?
