### ISSUE TITLE
I tried to integrate nacos in the nutzboot project. I wonder how to integrate nacos

### ISSUE THREAD

**Issue by TomYule** [alibaba/nacos#1942]
## Issue Description

I tried to integrate nacos in the nutzboot project. I wonder how to integrate nacos
Not a spring project
The project address
https://github.com/nutzam/nutzboot/tree/dev/nutzboot-demo/nutzboot-demo-dubbo
There is no problem running with zookeeper
Nacos does not know how to register the service

我尝试在nutzboot 项目中集成nacos不知道该如何集成
非spring项目
项目地址
https://github.com/nutzam/nutzboot/tree/dev/nutzboot-demo/nutzboot-demo-dubbo
使用zookeeper 运行没有问题
nacos 不知道怎么注册服务

### Tell us your environment
jdk 1.8
nutzboot

**Comment by nkorange** [comment]
Not sure about how nutzboot integrate with Nacos, maybe you can ask this in nutzboot community.
