### ISSUE TITLE
When combined with docker service, I found a serious bug.

### ISSUE THREAD

**Issue by lynk-coder** [alibaba/nacos#1949]
My docker version 19.03.1, nacos version 1.1.3
When I started my nacos with swarm service, I found that once my nacos node listened on ingress network, although my client could connect to nacos discovery, my configuration could not be automatically updated.
I've tried many times, and there's a problem,
However, when I looked at my mysql, config_info table, the data did change.But my client has not been updated.And after restarting my client, the data still does not change, unless I restart my nacos-server.
Everything returned to normal when I used "--publish mode=host,target=8848,published=8848".

![1](https://user-images.githubusercontent.com/23651124/67137503-176cb980-f269-11e9-81d7-12c3df674f40.png)

![2](https://user-images.githubusercontent.com/23651124/67137506-1e93c780-f269-11e9-8965-6b3394ed4cce.png)

**Comment by lynk-coder** [comment]
docker service create \
--publish 8848:8848 \
--name zykj-nacos \
--network=mynet \
--replicas 1 \
--update-parallelism 1 \
--log-opt max-size=10m \
--log-opt max-file=3 \
--env MODE=standalone \
--mount type=bind,source=/nacos/conf/application.properties,destination=/home/nacos/conf/application.properties \
--mount type=bind,source=/logs/nacos,destination=/home/nacos/logs \
nacos/nacos-server

**Comment by lynk-coder** [comment]
Why is nobody paying attention? Can you clarify whether this problem is a bug?

**Comment by nkorange** [comment]
I'm not familiar with docker, I forward your issue to project nacos-docker.

**Comment by paderlol** [comment]
> Why is nobody paying attention? Can you clarify whether this problem is a bug?
Only these things I can't analyze is a nacos error,Can u show me the content of application properties and the nacos error log？
And you can reply me on this [issue](https://github.com/nacos-group/nacos-docker/issues/58).

Thanks

**Comment by lynk-coder** [comment]
Can you give me a contact information? It's a little hard to explain.
On 10/31/2019 22:52, pader wrote:

Why is nobody paying attention? Can you clarify whether this problem is a bug?
Only these things I can't analyze is a nacos error,Can u show me the content of application properties and the nacos error log？
And you can reply me on this issue.

Thanks
