### ISSUE TITLE
Can Nacos's highly available solution be described in detail officially?

### ISSUE THREAD

**Issue by yuesf** [alibaba/nacos#1950]
1. There is no performance test report of minimum machine configuration in Linux CentOS environment
2. Highly available deployment plan, official didn't provide details

**Comment by nkorange** [comment]
1. benchmark reports are available in https://nacos.io/zh-cn/docs/nacos-config-benchmark.html and https://nacos.io/zh-cn/docs/nacos-naming-benchmark.html, you can contribute your reports on your machine.

2. Cluster deployment is introduced in https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

**Comment by yuesf** [comment]
> * benchmark reports are available in https://nacos.io/zh-cn/docs/nacos-config-benchmark.html and https://nacos.io/zh-cn/docs/nacos-naming-benchmark.html, you can contribute your reports on your machine.
> * Cluster deployment is introduced in https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

看到这个高可用方案了， 但是太简单了。
假如 启三个nacos服务 与启一个集群有三个服务的区别在哪里？ 
因为三个nacos服务前面也可以加个vip  一个集群的三个服务前面也是加vip。

性能报告中 是高配置机器。若是1c2G的机器或2C4G 是否可以使用？

**Comment by nkorange** [comment]
1. 目前一个或者多个VIP都是一样的，多个VIP会让客户端有重试的机会；
2. 低配机器可以使用，具体容量你可以尝试压测一下。
