### ISSUE TITLE
java.lang.NoClassDefFoundError: com/alibaba/nacos/client/naming/utils/StringUtils

### ISSUE THREAD

**Issue by maoweifan** [alibaba/nacos#1951]
Nacos - client1.0.1 and above and cause abnormal Java. Lang. NoClassDefFoundError: com/alibaba/nacos/client/naming/utils/StringUtils, 1.0.0 is ok, I think excuse me if use 1.0.0 above and how to solve this problem

nacos-client1.0.1及其以上版本引发异常java.lang.NoClassDefFoundError: com/alibaba/nacos/client/naming/utils/StringUtils,1.0.0则没事,我想请问一下如果使用1.0.0以上版本怎么解决这个问题

**Comment by nkorange** [comment]
用的是Dubbo客户端？升级一下Dubbo客户端

**Comment by maoweifan** [comment]
> 用的是Dubbo客户端？升级一下

对,我的意思是,用1.0.0以上版本,会抛异常,1.0.0及其一下版本没问题

**Comment by nkorange** [comment]
> > 用的是Dubbo客户端？升级一下
> 
> 对,我的意思是,用1.0.0以上版本,会抛异常,1.0.0及其一下版本没问题

是因为Dubbo客户端依赖了这个类，新版本Dubbo客户端去掉了这个依赖

**Comment by maoweifan** [comment]
是哪个依赖?能提供一下maven的坐标吗

**Comment by nkorange** [comment]
> 是哪个依赖?能提供一下maven的坐标吗

用最新的就行
