### ISSUE TITLE
console register finished,但是健康实例数为0,应该怎样排查?

### ISSUE THREAD

**Issue by tzhanhe** [alibaba/nacos#1952]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. console register finished,但是健康实例数为0
2. 
3.

**Comment by nkorange** [comment]
检查下{user.home}/logs/nacos/naming.log看下是否注册成功

**Comment by xuande** [comment]
如果naming.log里面没有异常，清空浏览器缓存，刷新试一下
