### ISSUE TITLE
Each page of the console is not modifiable

### ISSUE THREAD

**Issue by Aresxue** [alibaba/nacos#1954]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen
Click the button on each page to modify the number of pages per page.

### How to reproduce it (as minimally and precisely as possible)

1. Click on each page, no pop-ups and optional parameters

### Tell us your environment
CentOS Linux release 7.4.1708 (Core)

**Comment by nkorange** [comment]
tracked in #1629
