### ISSUE TITLE
springboot下的client配置，可以支持不注册自身的服务吗？

### ISSUE THREAD

**Issue by wujw2017** [alibaba/nacos#1956]
类似于eureka的register-with-eureka属性。
在联调环境的时候，只需要引用其他服务，不需要注册自己到注册中心。

**Comment by chuntaojun** [comment]
可以不注册自己，具体参看wiki，

**Comment by chuntaojun** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.3-%E4%BB%A5%E5%8F%8A-0.1.3-%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C
