### ISSUE TITLE
dubbo更换nacos报错，依赖添加后没有NamingMaintainService个类

### ISSUE THREAD

**Issue by zuixiaoyao001** [alibaba/nacos#1961]
添加jar如下：zk作为注册中心只用这个即可
依赖一：
<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-spring-context</artifactId>
			<version>0.3.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-context</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
//下面是替换nacos为注册中心添加的依赖，标记为依赖二（3个）
<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo-registry-nacos</artifactId>
			<version>2.6.6</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.spring</groupId>
			<artifactId>spring-context-support</artifactId>
			<version>1.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>0.6.2</version>
		</dependency>
dubbo配置
nacos注册中心
`	<dubbo:registry address="nacos://127.0.0.1:8848" />
zk注册中心
	<dubbo:registry protocol="zookeeper" address="${zookeeper.address}" />
	<dubbo:protocol name="dubbo" port="${dubbo.port}" />

	<import resource="dubbo/applicationContext-user-dubbo.xml" />
	<import resource="dubbo/applicationContext-card-dubbo.xml" />`
启动后报错：
java.lang.NoClassDefFoundError: com/alibaba/nacos/api/naming/NamingMaintainService
然后在依赖的jar包中确实找不到这个类。
把依赖二删掉，替换为zk是没问题的，可以正常运行，加上上面依赖二，仍用zk启动仍然报错
这个是jar包版本问题吗？还是有bug?如果是jar版本问题，应该那个版本？

**Comment by chuntaojun** [comment]
nacos-client版本过低，使用1.0.1+
