### ISSUE TITLE
关于控制台上传zip配置问题的bug

### ISSUE THREAD

**Issue by 767248371** [alibaba/nacos#1965]
## Issue Description

描述：比如mac打包产生了__MACOSX和这个文件，导入时候校验发生错误，希望能过过滤掉，
但是也可以不做，因为这只是一个小问题

### How to reproduce it (as minimally and precisely as possible)

1. mac打包上传

### Tell us your environment
mac环境打包zip文件

### Anything else we need to know?
目前我自己改了源码
if (entry.getName().contains("__MACOSX") || entry.getName().contains("DS_Store")) {
                        continue;
                    }

**Comment by nkorange** [comment]
@767248371 能把你的修改贡献到Nacos吗？
