### ISSUE TITLE
关于上传zip时候，type判断的bug

### ISSUE THREAD

**Issue by 767248371** [alibaba/nacos#1966]
## Issue Description

代码如下：
   if (configInfo.getDataId().contains(SPOT)) {
                String extName = configInfo.getDataId().substring(configInfo.getDataId().lastIndexOf(SPOT) + 1).toLowerCase();
                try {
                    type = FileTypeEnum.valueOf(extName).getFileType();
                } catch (Exception ex) {
                    type = FileTypeEnum.TEXT.getFileType();
                }
            }

### Describe what you expected to happen

至少应该toUpperCase一下吧，要不然type全部text类型了

type = FileTypeEnum.valueOf(extName.toUpperCase()).getFileType();

### How to reproduce it (as minimally and precisely as possible)

上传zip配置包

### Anything else we need to know?
小bug希望大佬们修复一下

**Comment by nkorange** [comment]
欢迎你贡献修复！

**Comment by 767248371** [comment]
> 欢迎你贡献修复！

嗯嗯，好的，第一次加入开源项目，很荣幸，我先学习下怎么做。
