### ISSUE TITLE
如何配置服务注册的Group

### ISSUE THREAD

**Issue by 767248371** [alibaba/nacos#1970]
## Issue Description

在bootstrap.yml文件如何配置discovery实例的分组信息Group

spring.cloud.nacos.discovery.group 该属性不好使呀

### Describe what happened (or what feature you want)
这个是config配置，有group属性，但是为啥discovery没有group这个属性，我看到nacos提到了
关于服务注册到分组功能啊
config:
        server-addr: ${spring.cloud.server-addr}
        file-extension: yaml
        prefix: application
        group: opencloud-gateway-config

**Comment by chuntaojun** [comment]
这个将在spring-cloud-alibaba的下个版本发布，非nacos的问题
