### ISSUE TITLE
There was a bug when I used unit tests。

### ISSUE THREAD

**Issue by xlb** [alibaba/nacos#1973]
1. When I start a long transaction, the database connection reports an error,and i guess the problem occurs in this method;

`
 @EventListener public void handle(RefreshEvent event) {
 if (this.ready.get()) { 
// don't handle events before app is ready 
log.debug("Event received " + event.getEventDesc()); 
Set<String> keys = this.refresh.refresh(); 
log.info("Refresh keys changed: " + keys); 
} }
`

`25 14:55:13.214 [main] WARN com.zaxxer.hikari.pool.ProxyConnection - HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@258d7d06 marked as broken because of SQLSTATE(08003), ErrorCode(0) com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed. at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)`

2. Here is a test case

- download the code here；https://github.com/xulb-study/nacos_example/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-multi-data-ids-example 

- inti test.sql and nacos config
- use UserTest

3. this is the issues write by chinese； 
https://github.com/alibaba/nacos/issues/1968

**Comment by chuntaojun** [comment]
This should be a spring - cloud - alibaba project integration problems, I will move the issue to the spring - cloud - alibaba project
