### ISSUE TITLE
我自己部署了1.1.3版本到linux环境，这样的内存占用正常吗？

### ISSUE THREAD

**Issue by git10135405** [alibaba/nacos#1980]
我在linux部署了一个单节点nacos，数据源为mysql，仅做配置中心用，但仅仅是测试demo跑大概4天而已，如图所示占用内存正常吗？
![image](https://user-images.githubusercontent.com/35558611/67747313-68e42800-fa63-11e9-9635-eabecf871dad.png)

**Comment by nkorange** [comment]
这里虚拟内存占用较高，实际上并么有占用那么多，实际内存还是启动时分配的500多M。

**Comment by git10135405** [comment]
是的，是占用虚拟内存，这个占用大小正常吗？


---原始邮件---
发件人: &quot;Fury Zhu&quot;<notifications@github.com&gt;
发送时间: 2019年10月31日(星期四) 晚上7:43
收件人: &quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;;
抄送: &quot;git10135405&quot;<10135405@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [alibaba/nacos] 我自己部署了1.1.3版本到linux环境，这样的内存占用正常吗？ (#1980)



这里虚拟内存占用较高，实际上并么有占用那么多，实际内存还是启动时分配的500多M。
 
&mdash;

**Comment by nkorange** [comment]
虚拟内存一般问题不大，你可以用工具分析下虚拟内存的占用

**Comment by 5zyd14** [comment]
你好，请问你部署了linux，能够访问配置中心吗
