### ISSUE TITLE
om.netflix.client.ClientException: Load balancer does not have available

### ISSUE THREAD

**Issue by SwpuEsine** [alibaba/nacos#1981]
自己下载了github的spring cloud demo 然后使用feign来调用服务 发现可以正常调用返回结果, 但是公司项目  注册上去了 但是无法调通 请问什么问题
com.netflix.client.ClientException: Load balancer does not have available server for client: 
![image](https://user-images.githubusercontent.com/24284757/67821640-afd02d00-faf8-11e9-819b-fbe413fbcf54.png)

**Comment by nkorange** [comment]
{user.home}/logs/nacos/naming.log里是否有服务的获取日志？

**Comment by SwpuEsine** [comment]
已经解决了,谢谢,是因为服务名区分大小写,feign的name和服务名大小写不一致




------------------ 原始邮件 ------------------
发件人: "Fury Zhu"<notifications@github.com>; 
发送时间: 2019年10月31日(星期四) 晚上7:32
收件人: "alibaba/nacos"<nacos@noreply.github.com>; 
抄送: "&#x1F633;&#x1F633;&#x1F628;&#x1F628;&#x1F633;&#x1F633;"<1250446374@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [alibaba/nacos] om.netflix.client.ClientException: Load balancerdoes not have available (#1981)




{user.home}/logs/nacos/naming.log里是否有服务的获取日志？
