### ISSUE TITLE
support cors

### ISSUE THREAD

**Issue by xilipilige** [alibaba/nacos#1983]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
       For a pure web front-end project, the configuration file needs to be put into Nacos, but at present Nacos does not support cross domain, so there is a need to add cross domain support.

### Describe what you expected to happen
       support cors

### Anything else we need to know?
I submitted a pull request named feature_cors

**Comment by caogenyin** [comment]
This is a very useful feature，I want to have this feature
