### ISSUE TITLE
In standalone mode, the local IP is changed, resulting in the configuration not being updated.

### ISSUE THREAD

**Issue by xiannu** [alibaba/nacos#1989]
public static final String LOCAL_IP = InetUtils.getSelfIp();
在一开始读取本机ip,假如本机的ip变更，在发布新配置的时候，无法异步调用/v1/cs/communication/dataChange接口,导致数据未更新。
At the beginning of reading the local IP, if the local IP changes, when publishing the new configuration, the /v1/cs/communication/dataChange  interface cannot be called asynchronously, resulting in the data not updated.

**Comment by chuntaojun** [comment]
I will go to solve this problem

**Comment by nkorange** [comment]
@chuntaojun You can assign it to yourself.

**Comment by chuntaojun** [comment]
Under what circumstances will the local IP change? Container restarted?
