### ISSUE TITLE
在application.yml中配置nacos的地址时，不能添加http://前缘

### ISSUE THREAD

**Issue by wgslucky** [alibaba/nacos#1991]
在application.yml中添加spring.cloud.nacos.discovery.server-addr时，如果是域名的话，不能添加http://前缀。否则在注册服务的时候，请求的url在最后会少一位。比如http://www.xx.com:8848,会变成http://www.xx.com:884。

**Comment by nkorange** [comment]
是的，nacos并不希望在客户端限制访问协议。
