### ISSUE TITLE
some questions about Raft in Nacos

### ISSUE THREAD

**Issue by njuse11wu** [alibaba/nacos#1994]
Type: *bug report*

1)
in class ‘com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.java‘，the method 
'decideLeader()' and 'update()' just put peer into peers which is an instance of HashMap,not ConcurrentHashMap. Will there be thread safety issues?

com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.java 中的decideLeader()和update()方法，都是直接往hashmap中put，会不会有线程安全问题？

2)

```
public RaftPeer receivedVote(RaftPeer remote) {
        if (!peers.contains(remote)) {
            throw new IllegalStateException("can not find peer: " + remote.ip);
        }

        RaftPeer local = peers.get(NetUtils.localServer());
435  if (remote.term.get() <= local.term.get()) {
            String msg = "received illegitimate vote" +
                ", voter-term:" + remote.term + ", votee-term:" + local.term;

            Loggers.RAFT.info(msg);
            if (StringUtils.isEmpty(local.voteFor)) {
                local.voteFor = local.ip;
            }

            return local;
        }

        local.resetLeaderDue();

        local.state = RaftPeer.State.FOLLOWER;
        local.voteFor = remote.ip;
        local.term.set(remote.term.get());

        Loggers.RAFT.info("vote {} as leader, term: {}", remote.ip, remote.term);

        return local;
    }
```
let's turn to the method 'receivedVote()' in class 'com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore','(Line 435).
when two (or more) RequestVote RPCs with the same term which is higher than local term access the method concurrently,will the method vote for both of them?Is it a violation of the requirement _'Each server will vote for at most one candidate in a given term'_ , or in other words ,fails to implement first-come-first-served principle?

com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore 中的receivedVote()方法，第435行（已标出），当两个term相同且都高于local.term的RequestVote RPCs并发到来时，receivedVote()是否会同时为他们俩投票？是否违反了Raft算法中同一个节点同一个term只能投票一次的要求，或者说未能实现first-come-first-served 原则?

**Comment by satjd** [comment]
I agree, the Raft RequestVote RPC handler in Nacos (com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#receivedVote) is not thread-safe. Maybe lock this method is a solution here.

**Comment by njuse11wu** [comment]
> I agree, the Raft RequestVote RPC handler in Nacos (com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#receivedVote) is not thread-safe. Maybe lock this method is a solution here.

可以看看第一个问题，居然多线程往hashmap里put。。。我有点怀疑我的眼睛

**Comment by nkorange** [comment]
Raft协议目前有一些缺陷，会在后面的版本重构掉，可以参考 #1109

**Comment by njuse11wu** [comment]
> Raft协议目前有一些缺陷，会在后面的版本重构掉，可以参考 #1109

请问钉钉群是内部的么？是否可以加入参与讨论、学习？

**Comment by nkorange** [comment]
> > Raft协议目前有一些缺陷，会在后面的版本重构掉，可以参考 #1109
> 
> 请问钉钉群是内部的么？是否可以加入参与讨论、学习？

是公开的群，欢迎加入。
