### ISSUE TITLE
nacos cluster 添加配置文件问题

### ISSUE THREAD

**Issue by hanyunxi** [alibaba/nacos#1995]
ji

## Issue Description

集群模式下，添加配置文件，直接error：发布失败。请检查参数是否正确。
独立模式下，无任何问题，还是漏了哪些配置啊？

**Comment by nkorange** [comment]
添加配置文件指的是什么操作？

**Comment by HashTableHu** [comment]
我使用的k8s集群，稳定运行了一周，今天也出现了这个错误，提示：发布失败。请检查参数是否正确。
然后跳转到了登录界面。
