### ISSUE TITLE
nacos能设置密码进行服务注册吗？

### ISSUE THREAD

**Issue by wangzhedong** [alibaba/nacos#1996]
在阿里云上装了个nacos集群，然后我需要通过浏览器打开nacos的管理界面，所以在服务器在安全组策略的时候肯定要开放8848-8850的端口，但是开发了端口的话，别人要是知道我的ip地址，是不是其他乱七八糟的服务也可以注册到我的naco上了，所以nacos能让注册的服务也需要密码验证吗？

**Comment by nkorange** [comment]
目前不能，请参考 #1105，下个版本支持
