### ISSUE TITLE
1.1.4 Nacos点击服务列表报401  直接登出

### ISSUE THREAD

**Issue by zhangandyhui** [alibaba/nacos#1998]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. Nacos点击服务列表报401  直接登出
2. Nacos点击服务列表报401  直接登出
3. Nacos点击服务列表报401  直接登出

### Tell us your environment

localhost   standalone

**Comment by nkorange** [comment]
清除下浏览器缓存

**Comment by zhangandyhui** [comment]
> 清除下浏览器缓存

还是不行 试过的

**Comment by zhangandyhui** [comment]
> 清除下浏览器缓存
嗯 可以了 谢谢了
