### ISSUE TITLE
0431121826266455 will be considered floating point

### ISSUE THREAD

**Issue by ZhZGod** [alibaba/nacos#1999]
Why is such a value pair considered floating-point because it starts with 0? Is there a problem in judging the regularity of floating-point type?
The regularity of judging floating point numbers used by Nacos
public static final Pattern FLOAT = Pattern
            .compile("^([-+]?(\\.[0-9]+|[0-9_]+(\\.[0-9_]*)?)([eE][-+]?[0-9]+)?|[-+]?[0-9][0-9_]*(?::[0-5]?[0-9])+\\.[0-9_]*|[-+]?\\.(?:inf|Inf|INF)|\\.(?:nan|NaN|NAN))$");

It is suggested to change to this
public static final Pattern FLOAT = Pattern
        .compile("^([-+]?(\\.[0-9]+|[0-9_]+(\\.[0-9_]*)?)(?=.*_)([eE][-+]?[0-9]+)?|[-+]?[0-9][0-9_]*(?::[0-5]?[0-9])+\\.[0-9_]*|[-+]?\\.(?:inf|Inf|INF)|\\.(?:nan|NaN|NAN))$");

**Comment by nkorange** [comment]
Didn't see any code like this in Nacos, please add a link or name of class which has this code.

**Comment by ZhZGod** [comment]
NacosPropertySourceBuilder.loadNacosData()----yamlFactory.getObject()

**Comment by ZhZGod** [comment]
This is the code for org.yaml.snakeyaml to format yaml configuration

**Comment by ZhZGod** [comment]
NacosPropertySourceBuilder.loadNacosData()----yamlFactory.getObject()
YamlPropertiesFactoryBean.createProperties---process((properties, map) -> result.putAll(properties));
YamlProcessor.process(MatchCallback callback)---boolean found = process(callback, yaml, resource);
BaseConstructor.getData()-------Node node = composer.getNode();

Resolver.resolve()

**Comment by nkorange** [comment]
Please report this problem to https://github.com/nacos-group/nacos-spring-project
