### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Horrypotter** [alibaba/nacos#2001]
## Issue Description

Type: bug report

### Describe what happened
this is my yaml file, I set a variable like this:

```yaml
fieldDelimiter: "\u0001"
```
but I got “”  in my code,this variable  will not be "\u0001" in my code.though I can solve this in my code, but I think this is not good

像上面的配置在代码中会显示为“”，所以该条配置不能生效，虽然代码里能够解决，但还是希望ncos中的配置能够原样将配置送给代码。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by DoolinMa** [comment]
@Horrypotter 
if you want get string \u0001 config like this
`useLocalCache: \\u0001`

if you want get string "\u0001" config like this
`useLocalCache: "\\u0001"`
