### ISSUE TITLE
after setting "dubbo.registry.simplified" to true，service name is missing, only shows: “consumers::::”

### ISSUE THREAD

**Issue by makingtime** [alibaba/nacos#2002]
## Issue Description
bug report

### Describe what happened (or what feature you want)

after I enable meta data report by setting "dubbo.metadata-report.address = redis://xxx.xxx:6379"
and set "dubbo.registry.simplified" to true,

then in the service details (consumer side) only show below info:
```
path=com.xxx.services.DubboServiceProviderC
protocol=consumer
application=dubbo-consumer-a
release=2.7.4.1
dubbo=2.0.2
check=false
category=consumers
```

so I think if after enabling metat data report and simplified registry info, maybe we should use path as service name?

### Describe what you expected to happen

service name should not missing

### How to reproduce it (as minimally and precisely as possible)

enable meta data report by setting 
"dubbo.metadata-report.address = redis://xxx.xxx:6379"
and set "dubbo.registry.simplified" to true

### Tell us your environment
dubbo version: 2.7.4.1
config center: apollo 1.5.0
meta data center: redis 5.0.6

### Anything else we need to know?
![image](https://user-images.githubusercontent.com/53243647/68001167-e5fae180-fc9d-11e9-86f8-c926b3fca423.png)

**Comment by nkorange** [comment]
Please report this issue to Dubbo.
