### ISSUE TITLE
some wrong with updating nacos instance 

### ISSUE THREAD

**Issue by wmj765** [alibaba/nacos#2003]
## Issue Description

bug report

### Describe what happened (or what feature you want)

i start a service with one healthy instance, and it`s state are {"Ephemeral":true,"healthy":true} , 
when i want to offline this instance  with http request and param includes{""Ephemeral":false,"healthy":false"} , 
nacos console will add an a same instance just having diffrent 'Ephemeral' value , and i can not delete this instance , even through restart nacos-server and service-server;

### Describe what you expected to happen

just update the instance not add another instance when i offline/online service with diffrent 'Ephemeral' value

### How to reproduce it (as minimally and precisely as possible)

1. send a http request with postman
method : PUT 
url : http://<nacosAddr>/nacos/v1/ns/instance
param : having a diffrent 'Ephemeral' value than the original service

2. stop this service and console will leave a instance which instance count is 1  and Healthy Instance Count is 0 ,and i cant delete it

![image](https://user-images.githubusercontent.com/19549289/68015288-cc24c300-fccc-11e9-8c51-9be24ba1f9a4.png)

### Tell us your environment
spring-boot : 2.1.4.RELEASE
spring-cloud-starter-alibaba-nacos-discovery : 0.2.2.RELEASE
spring-cloud-starter-alibaba-nacos-config : 0.2.2.RELEASE

**Comment by nkorange** [comment]
1. Set ```enabled``` property of instance to offline an instance.
2. Use ```curl -X DELETE $nacos:8848/nacos/v1/ns/instance?serviceName=service-provider&ip=xxx&port=xxx&ephemeral=false``` to remove this instance.

**Comment by wmj765** [comment]
got it  ,and  'curl -x DELETE' works , thanks
