### ISSUE TITLE
bug report nacos-config-spring-boot-starter:0.1.3 can't get the config data in the service code when springboot application initials

### ISSUE THREAD

**Issue by mingzhicode** [alibaba/nacos#2004]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

服务器上有配置快照文件存在，springboot应用启动初始化过程，识别有@NacosConfigListener的方法存在并处理时，在实例化生成的configservice添加listener过程中导致了该问题，在添加listener过程中初始化生成CacheData，并在cacheData添加listener过程中，把从快照文件中读取的配置值md5保存到了listener的lastMd5属性中，导致了在ClientWork中的LongPullingRunable任务中没有触发safeNotifyListener函数，spring应用里使用配置服务的相关变量没有得到正确初始化

Background: there is snapshot file on the server and springboot application initials, and the NacosConfigListenerMethodProcessor process the beans with @NacosConfigListener annotation. 
This bug happens where adding listener to the ConfigService instance  in the NacosConfigListenerMethodProcessor's processListenerMethod method. In the process, CacheData is initializing by calling the construct method, and when CacheData instance adds listeners, the config value's md5 from snapshot file was put to the listener's "lastCallMd5" property. That makes safeNotifyListener function in the ClientWork's LongPullingRunable task not triggled because the current md5 equals lastCallMd5, and cause the data/bean in the springboot application is not initialzed correctly.

### Describe what you expected to happen
尽快修改相关代码

modify the relative code and fix the bug

### How to reproduce it (as minimally and precisely as possible)

1.服务器上有相关dataId，groupId的快照文件
   Snapshot file on the server corr
2.使用@NacosConfigListener注解
   Using @NacosConfigListener annotation
3.启动springboot应用 
   Bootstrap springboot applicatioin

**Comment by chuntaojun** [comment]
你是开启了这个参数吗：enableRemoteSyncConfig

**Comment by chuntaojun** [comment]
这不是一个bug，设计如此，监听器是监听本地配置文件与远端配置文件的变更，只有实际发生变更才会触发，如果需要利用listener的能力，建议使用com.alibaba.nacos.api.config.ConfigService#getConfigAndSignListener，程序启动时get到配置文件，然后会注册listener。listener会去监听这之后的文件变动

**Comment by GoldyMark** [comment]
@mingzhicode  我也遇到这个问题，目前有2个解决方法：
1. 在nacos配置下发前调用SnapShotSwitch.setIsSnapShot(false)，避免生成snapshot文件；（如果要使用故障转移则该方法不合适）
2. 使用InitializingBean，在bean初始化后手动赋值；
```
    @NacosInjected
    private ConfigService configService;

    private void onReceivedInner(String content) {
        // just do it
    }

@Override
    public void afterPropertiesSet() throws Exception {
        String configInfo = configService.getConfigAndSignListener(DATA_ID, GROUP_ID, TIMEOUT, new TimeoutNacosConfigListener(DATA_ID, GROUP_ID, TIMEOUT) {
            @Override
            protected void onReceived(String content) {
                onReceivedInner(content);
            }
        });
        onReceivedInner(configInfo);
    }
```
