### ISSUE TITLE
Can nacos be used to provide external interface services?

### ISSUE THREAD

**Issue by tianxia0079** [alibaba/nacos#2010]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
Not sure what you mean, please add more details.

**Comment by tianxia0079** [comment]
> Not sure what you mean, please add more details.

想用nacos 做接口服务提供，给第三方用，推荐这样用吗

**Comment by nkorange** [comment]
> > Not sure what you mean, please add more details.
> 
> 想用nacos 做接口服务提供，给第三方用，推荐这样用吗

接口服务指的是什么意思，能不能举个具体的场景？

**Comment by tianxia0079** [comment]
比如有个接口查询门禁白名单，这个数据要求安全性很高，如果把这个接口服务用nacos发布出去，让安全可靠地门禁厂商来访问。
1.有没有安全保障机制？
2.nacos是否适用于该场景？
谢谢

**Comment by nkorange** [comment]
目前Nacos还不支持权限控制，该功能会在下个版本1.2.0支持。请参考 #1105
