### ISSUE TITLE
v1.1.4 端口配置冲突 dt_socket 8000，这个为啥不做成可配置化的呢？谢谢

### ISSUE THREAD

**Issue by xshans** [alibaba/nacos#2014]
Listening for transport dt_socket at address: 8000

这个8000端口在1.1.4版本，无法配置化。

**Comment by nkorange** [comment]
这个是在startup.sh里面的，可以删除，只是debug用的：
```
JAVA_OPT="${JAVA_OPT} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"
```

**Comment by xshans** [comment]
是可以删除或者注释掉，但不应该成为正式版发布的默认选项，希望可以做成配置化或者默认就不要debug，谢谢。

**Comment by nkorange** [comment]
不好意思，发布时忘记删除了，已经更新下载包。

**Comment by xshans** [comment]
感谢辛苦付出！谢谢！
