### ISSUE TITLE
Remove fastjson dependency

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#2015]
We can discuss whether we should replace fastjson to another json library here.

**Comment by zzSleep** [comment]
我觉得,可以这么做,要么remove another json

**Comment by nkorange** [comment]
@zzSleep 你有兴趣贡献一下吗？

**Comment by zzSleep** [comment]
我先看一下源码里面这个涉及的量大不大,不大的话,我可以尝试一下

**Comment by nkorange** [comment]
> 我先看一下源码里面这个涉及的量大不大,不大的话,我可以尝试一下

比较大

**Comment by RojerAlone** [comment]
这块的改动有人在做了吗？最近 fastjson 又爆出严重安全漏洞，我们自己的服务已经全部切换至 gson，但是依赖了 nacos，这些服务都需要升级，希望官方能尽快讨论解决下，不然以后再发生这种问题代价太大了
