### ISSUE TITLE
nacos 1.1.4 - Registration service failed? code:503 msg: server is DOWN now

### ISSUE THREAD

**Issue by liulipengju** [alibaba/nacos#2017]
## Issue Description

Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
Service registration failed with error message: code:503 msg: server is DOWN now

### How to reproduce it (as minimally and precisely as possible)

1.  Registration service
2. 
3. 

### Tell us your environment
k8s deploy nacos 1.1.4 version

### Anything else we need to know?
{"cluster":"DEFAULT","ip":"192.168.23.1","metadata":{"preserved.register.source":"SPRING_CLOUD"},"period":5000,"port":7979,"scheduled":false,"serviceName":"DEFAULT_GROUP@@exam-gateway","stopped":false,"weight":1.0}

The server version is reduced to 1.1.3 and the service can be registered normally.
![TIM截图20191106154955](https://user-images.githubusercontent.com/10510950/68278814-1d59fb80-00ad-11ea-970d-e109bf79d8ac.png)

**Comment by nkorange** [comment]
Were you using standalone mode? Execute the following command on each Nacos node:
```
curl '127.0.0.1:8848/nacos/v1/ns/operator/servers?healthy=true'
```

**Comment by liulipengju** [comment]
nacos cluster

**Comment by liulipengju** [comment]
The console sees that the node is correct, with 3 nodes, one master, and 2 slave nodes.

**Comment by liulipengju** [comment]
The same yaml deployment K8S, just changed the difference between the version number, 1.1.3 and latest

**Comment by nkorange** [comment]
> The same yaml deployment K8S, just changed the difference between the version number, 1.1.3 and latest

If you were using nacos-k8s, it does not support Nacos 1.1.4 now. We will release nacos-k8s for Nacos 1.1.4 soon.

**Comment by liulipengju** [comment]
ok,thank you
