### ISSUE TITLE
http connection Keepalive is invalid，dubbo consumer has many TIME_WAIT 

### ISSUE THREAD

**Issue by jackokcc** [alibaba/nacos#2018]
Use Nacos as Dubb's registry，http connection Keepalive is invalid，dubbo consumer has many “TIME_WAIT”。

dubbo 2.7.3
nacos-client 1.1.1
jdk 8u91

The problem may lie in the following two classes，Every request  called  HttpURLConnection.disconnect()..Calling the disconnect() method may close the underlying socket if a persistent connection is otherwise idle at that time.

```
 com.alibaba.nacos.client.naming.net.HttpClient
 com.alibaba.nacos.client.config.impl.HttpSimpleClient

...
request(){
...
     } finally {
            if (conn != null) {
                conn.disconnect();
            }
        }
}
```
As per [javadoc](https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html#disconnect--)

> Each HttpURLConnection instance is used to make a single request but the underlying network connection to the HTTP server may be transparently shared by other instances. Calling the close() methods on the InputStream or OutputStream of an HttpURLConnection after a request may free network resources associated with this instance but has no effect on any shared persistent connection. Calling the disconnect() method may close the underlying socket if a persistent connection is otherwise idle at that time.

--------------------------------------------------------------------------
dubbo 在使用nacos注册中心的时候，dubbo的消费端出现大量的TIME_WAIT状态的连接，占用大量的端口，每次请求/心跳都是新建连接，没有共享连接。从javadoc看，问题可能出在HttpURLConnection的使用上，每次请求都调用了disconnect，关闭了连接。
 com.alibaba.nacos.client.naming.net.HttpClient
 com.alibaba.nacos.client.config.impl.HttpSimpleClient

**Comment by nkorange** [comment]
你试过不调用disconnect()，TIME_WAIT数会有明显下降吗？

**Comment by jackokcc** [comment]
> 你试过不调用disconnect()，TIME_WAIT数会有明显下降吗？

HttpClient代码摘出来去掉disconnect调用，连接是共用的，TIME_WAIT也是没有的，但还没有在dubbo里测试过（今天打个测试包会试下），按照文档看来，如果想重用只要关闭流就可以。

**Comment by nkorange** [comment]
> > 你试过不调用disconnect()，TIME_WAIT数会有明显下降吗？
> 
> HttpClient代码摘出来去掉disconnect调用，连接是共用的，TIME_WAIT也是没有的，但还没有在dubbo里测试过（今天打个测试包会试下），按照文档看来，如果想重用只要关闭流就可以。

我测试了一下，不调用disconnect确实会减少TIME_WAIT连接，我再测试一下其他功能。

**Comment by zrlw** [comment]
you should inform the guys who write dubbo to upgrade their lastest pom.xml which still depends on nacos-client-1.x.x
