### ISSUE TITLE
Nginx forwarded to Nacos console page editing error 

### ISSUE THREAD

**Issue by Maijh97** [alibaba/nacos#2019]
## Issue Description
在产线上部署nacos，通过NGINX 跳转到控制台地址，在配置文件的编辑页面出现错误
NGINX配置如下
`
upstream nacos-server {
     server  127.0.0.1:8848;
     }
    location /nacos/ {
        proxy_pass http://nacos-server/nacos/;
     }
`
![1573041361179_B7235163-6D6C-4ec5-BBEF-E335D5EC7867](https://user-images.githubusercontent.com/37288946/68297418-d7fbf500-00d1-11ea-9d1b-dab96781a678.png)

### Describe what happened (or what feature you want)
需要正常响应编辑页面

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
服务器为centos
naocs版本为1.1.4

**Comment by nkorange** [comment]
麻烦把错误信息截图一下

**Comment by Maijh97** [comment]
![Uploading image.png…]()

**Comment by Maijh97** [comment]
![Uploading 30a319e6e30b290dfd82e0ab2822375.png…]()

**Comment by Maijh97** [comment]
![30a319e6e30b290dfd82e0ab2822375](https://user-images.githubusercontent.com/37288946/68371180-1c8e9b80-0179-11ea-9b4d-b835edea7c98.png)

**Comment by Maijh97** [comment]
麻烦尽快回复一下具体的问题，目前部署的是生产环境。 所以很急

**Comment by nkorange** [comment]
我本地测试由nginx转发是没问题的，ERR_CONNECTION_RESET这个错误可以参考：https://www.zhihu.com/question/21512577

**Comment by Maijh97** [comment]
@nkorange 现在突然又好了，什么都没有做😶
