### ISSUE TITLE
nacos-api module:code format and clean up

### ISSUE THREAD

**Issue by FrankBian** [alibaba/nacos#202]
1. format the codes in the nacos-api module,and do cleaning up.
2. correct some words spelling in the comments.

**Comment by yanlinly** [comment]
can u provide more info?

**Comment by FrankBian** [comment]
https://github.com/alibaba/nacos/pull/205

pr#205

**Comment by FrankBian** [comment]
> can u provide more info?

https://github.com/alibaba/nacos/pull/205

pr#205

**Comment by universefeeler** [comment]
@i will solve it @FrankBian

> 1. format the codes in the nacos-api module,and do cleaning up.
> 2. correct some words spelling in the comments.
