### ISSUE TITLE
Common classes in Nacos should be unified

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#2025]
Currently there are several HttpClient classes in Nacos, they should be merged to one class. So we can avoid repeated changes like in #2018

**Comment by nkorange** [comment]
Actually there are more than one kind of classes should be unified. Some of the candidates are:
* HttpClient
* IOUtils
* StringUtils
* ...

**Comment by haochencheng** [comment]
> Actually there are more than one kind of classes should be unified. Some of the candidates are:
> 
> * HttpClient
> * IOUtils
> * StringUtils
> * ...

i create a pull request to unified IOUtils and StringUtils
the branch name is haochencheng:feature/unifiedCommonClasses 
how should i do to finished this pull request
