### ISSUE TITLE
控制台-服务列表 -谷歌浏览器访问直接退出

### ISSUE THREAD

**Issue by MrLittleHand** [alibaba/nacos#2030]
![1573130736(1)](https://user-images.githubusercontent.com/38712350/68390278-e0226600-019f-11ea-8eec-145dd4aa5901.png)
![微信截图_20191107204512](https://user-images.githubusercontent.com/38712350/68390279-e0bafc80-019f-11ea-8f16-4df744fe9b04.png)

1.1.4版本  谷歌浏览器 访问服务列表功能 直接跳到登录界面， edge浏览器无问题。

-

**Comment by nkorange** [comment]
清理浏览器缓存
