### ISSUE TITLE
Incorrect Healthy Status Returned with the api nacos/v1/ns/instance/list

### ISSUE THREAD

**Issue by BinWu1989** [alibaba/nacos#2031]
When the instance was registered with non-ephemeral configuration, the server's api /v1/ns/instance/list returns the wrong status of the service while nacos/v1/ns/catalog/instances returns correct, The next is the pictures attached.
(1) the instances api returns the correct status
![image](https://user-images.githubusercontent.com/15190107/68447512-2ff24300-021b-11ea-83e5-e58c4e865d04.png)
(2) the instance/list api return the wrong status
![image](https://user-images.githubusercontent.com/15190107/68447560-587a3d00-021b-11ea-8820-64e241a23ac4.png)

**Comment by BinWu1989** [comment]
@nkorange Please helps to check it.thanks

**Comment by nkorange** [comment]
The ```/instance/list``` API has a protect logic: if all instances are unhealthy, they will all be considered healthy. Check the code:
https://github.com/alibaba/nacos/blob/d019045656361e86c8c4040b668f4b192d77ecb4/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java#L488

**Comment by BinWu1989** [comment]
@nkorange  the default value of the protectThreshold is 0 .0F , I use the default value for this , Besides
(1) I have checked the log file ,also didn't find the related log message logged "protect threshold reached, return all ips ..."
(2)when I set the ephemeral  to false , the /instance/list api returns the correct status

**Comment by nkorange** [comment]
> @nkorange the default value of the protectThreshold is 0 .0F , I use the default value for this , Besides
> (1) I have checked the log file ,also didn't find the related log message logged "protect threshold reached, return all ips ..."
> (2)when I set the ephemeral to true which is default, the /instance/list api returns the correct status

1. Paste your  grep command.
2. Paste your result ```instance/list``` vs ```catalog/instances```.

**Comment by BinWu1989** [comment]
Sorry , It's my mistake , I got the log message. Thank for your help!
