### ISSUE TITLE
nacos控制面板中服务列表的命名空间分组失效

### ISSUE THREAD

**Issue by wangyingwei001** [alibaba/nacos#2033]
spring:
  cloud:
    nacos:
      discovery:
        namespace: 配置命名空间

这里配置了服务发现的命名空间，在nacos后台控制面板中的服务列表功能没生效 ，所有的都在public
命名空间中显示

**Comment by nkorange** [comment]
客户端 {user.home}/logs/nacos/naming.log 搜一下REGISTER关键字

**Comment by wangyingwei001** [comment]
naming-server.log是这个吗

**Comment by wangyingwei001** [comment]
> 客户端{user.home} /logs/nacos/naming.log搜一下REGISTER关键字

没看到你说的naming.log 有很多前缀是naming的日志 比如naming-server.log  ，naming-push.log  ，naming-pull.log

**Comment by nkorange** [comment]
> > 客户端{user.home} /logs/nacos/naming.log搜一下REGISTER关键字
> 
> 没看到你说的naming.log 有很多前缀是naming的日志 比如naming-server.log ，naming-push.log ，naming-pull.log

我说的是客户端的机器上的日志，不是Nacos服务端的机器。

**Comment by wangyingwei001** [comment]
01 2019-11-19 15:49:51.343 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] [] [] registering service springcloud-study with instance:{"clusterName":"DEFAULT","enabled":true,"ip":"192.168.2.18","metadata":{},"port":7071,"valid":true,"weight":1.0}
01 2019-11-19 15:58:15.815 INFO [main :c.a.n.c.naming] [BEAT] [] [] adding service:springcloud-studyto beat map.
01 2019-11-19 15:58:15.869 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] [] [] registering service springcloud-study with instance:{"clusterName":"DEFAULT","enabled":true,"ip":"192.168.2.18","metadata":{},"port":7071,"valid":true,"weight":1.0}
01 2019-11-19 16:07:04.491 INFO [main :c.a.n.c.naming] [BEAT] [] [] adding service:springcloud-study to beat map.
01 2019-11-19 16:07:04.545 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] [] [] registering service springcloud-study with instance:{"clusterName":"DEFAULT","enabled":true,"ip":"192.168.2.18","metadata":{},"port":7071,"valid":true,"weight":1.0}

**Comment by wangyingwei001** [comment]
![image](https://user-images.githubusercontent.com/44224525/69128617-b0505800-0ae7-11ea-925d-316142c9b8f8.png)
![image](https://user-images.githubusercontent.com/44224525/69128713-dbd34280-0ae7-11ea-93fb-2699511b67ec.png)
![image](https://user-images.githubusercontent.com/44224525/69128926-48e6d800-0ae8-11ea-82d4-9ca9a2d7ad13.png)

在bootstrap.yml中配置的nacos discovery namespace 配置了命名空间名称 0954b92d-c4a5-43f9-a0e3-9ced3b7a4ba5 对应的是test服务列表  但是服务启动后 就是在public服务列表中

**Comment by wangyingwei001** [comment]
有人能回答下吗

**Comment by nkorange** [comment]
@wangyingwei001 你的客户端版本是多少？

**Comment by zouht** [comment]
我这里也是. nacos1.1.3 配置了对应的namespace,但是服务依旧注册在public下面,请问有什么有效的解决办法吗

**Comment by wangyingwei001** [comment]
1.1.3

**Comment by wangyingwei001** [comment]
@nkorange 1.1.3

**Comment by nkorange** [comment]
@wangyingwei001 不可能1.1.3，1.1.3注册时会打印namespaceId信息的。你再检查一下:
https://github.com/alibaba/nacos/blob/a219dbeafc73bb91bbc07c93a8ce6b03e6b6abe5/client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java#L176

**Comment by wangyingwei001** [comment]
![image](https://user-images.githubusercontent.com/44224525/69701111-1d3aa200-1127-11ea-9db3-31b990bd3edb.png)
这里显示的就是客户端的吧

**Comment by wangyingwei001** [comment]
![image](https://user-images.githubusercontent.com/44224525/69701370-c84b5b80-1127-11ea-87af-5a651fd05b44.png)
是这吗

**Comment by wangyingwei001** [comment]
我把这个版本升级一下是吗 @nkorange

**Comment by wangyingwei001** [comment]
请问该怎么解决呢

**Comment by nkorange** [comment]
0.6.2就支持命名空间，0.8以后才支持。你升级到最新的1.1.4吧 @wangyingwei001

**Comment by wangyingwei001** [comment]
原来如此 是jar和nacos服务端都升级  还是只升级nacos服务端

**Comment by wangyingwei001** [comment]
解决了 谢谢

**Comment by wangtao19911111** [comment]
如何解决的？

**Comment by wangtao19911111** [comment]
springcloudalibaba2.2.0 我这边nacos1.2.0版本不行

**Comment by x3408** [comment]
我也是的 客户端1.2.1 cloudalibaba2.2.1 springboot2.2.7

**Comment by songweiwa** [comment]
请问下1.3.0版本单机版启动后不能命名空间不能新增分组 /nacos/v1/console/namespaces接口500异常
