### ISSUE TITLE
nacos控制台无法显示配置文件

### ISSUE THREAD

**Issue by huang6255302** [alibaba/nacos#2034]
![TIM截图20191108164258](https://user-images.githubusercontent.com/24607984/68462190-018a5d00-0247-11ea-8da4-7484419cfe51.png)
![TIM截图20191108164311](https://user-images.githubusercontent.com/24607984/68462191-0222f380-0247-11ea-9631-96ffd3d6ed80.png)

**Comment by nkorange** [comment]
清理一下浏览器缓存试试
