### ISSUE TITLE
value with e convert to big int

### ISSUE THREAD

**Issue by vvsuperman** [alibaba/nacos#2035]
### Describe what happened (or what feature you want)
set value which have e like 2343243224e12321  in nacos, but get value "infinity" in the client, when we delete e like 234324322412321, then we get the right value.

### Describe what you expected to happen
get the 2343243224e12321 in client 

### Tell us your environment
nacos 1.1.3 with spring boot 2.0.0.release

@RefreshScope
public class ConfigController{
   @Value("${somevalue}")
   String somevalue;
}

**Comment by nkorange** [comment]
I think maybe ```2343243224e12321``` is too large, try some number like ```2e3```?

**Comment by easyhaloo** [comment]
可以给个示例吗，目前我使用nacos 1.1.4并没有出现你所说的现象
![image](https://user-images.githubusercontent.com/32064710/69911870-d9180c00-145c-11ea-90e8-dc4e3649ded4.png)
![image](https://user-images.githubusercontent.com/32064710/69911878-dc12fc80-145c-11ea-9eed-2ce65f107100.png)
![image](https://user-images.githubusercontent.com/32064710/69911880-e3d2a100-145c-11ea-9257-572cce012c0b.png)
