### ISSUE TITLE
nacos部署到docker后找不到注册地址，而且docker启动服务直到不到配置

### ISSUE THREAD

**Issue by whaty** [alibaba/nacos#2036]
`
logs/naming-server.log <==
2019-11-08 17:55:02,507 INFO receive config info: unknown#172.22.0.3:8848#1573206902507#1
2019-11-08T09:55:03.842982312Z 
2019-11-08T09:55:03.842989348Z 
2019-11-08T09:55:08.121576222Z 
`
如果用docker部署微服务，nacos作为注册中心，由于docker会同时启动所有服务（提前启动好nacos），nacos会自己停掉，导致服务都起不来。如果先把nacos启动好，一个个服务启动，就没问题，这是怎么回事啊！

我在分析源码的时候发现，naming模块中用了大量队列处理并发，其中RaftCore类中出现大量队列用法，Notifier内部类的run()方法，导致了内存溢出，这段代码“ Pair pair = tasks.take();”会导致内存溢出！

RaftCore用了大量内部类，这种写法不配在阿里写代码！把一个类写了一千多行，阅读困难，也不尊重阿里编码规范！

**Comment by nkorange** [comment]
就事论事，请不要攻击贡献Nacos代码的人。如果你觉得代码质量有问题，欢迎来贡献改善。

关于你说的问题，麻烦贴出相应的错误日志或者内存分析数据。

**Comment by nkorange** [comment]
代码质量问题，在Nacos中确实存在，我们也在一步步改善，也很欢迎你来贡献高水平代码。

关于内部类的问题，目前阿里巴巴的代码规范里也没有对内部类限制使用的说明。同时，可以参考effective java 第13条：使类和成员可访问性最小，以及JDK中ArrayList，ConcurrentHashMap等都大量使用了内部类；

关于文件行数的问题，JDK中很多类都超过1000行，所以行数并不能作为代码质量判定的唯一标准。

关于内存溢出的问题，就你举的例子来说，RaftCore.Notifier类的addTask方法是有对任务做去重的，所以正常不会引起内存溢出，这些核心代码在阿里巴巴集团已经运行多年，请相信我们不会把一套未经验证的代码随便开源出去。

**Comment by whaty** [comment]
nacos部署到docker后，服务用docker单独一个个启动可以起来，用docker编排同事启动超过三个就会失败，你们自己试试。出现这个问题，看报错的时候，看到了那行代码提示死锁导致内存溢出



    


            在2019年11月09日 21:02，Fury Zhu 写道： Closed #2036.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alibaba/nacos/issues/2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180",
"url": "https://github.com/alibaba/nacos/issues/2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by whaty** [comment]
你们来源出来的nacos应该是阉割版的，绝非文档说的经得住双十一的版本



    


            在2019年11月10日 08:48，LiangCan 写道： 
        
            nacos部署到docker后，服务用docker单独一个个启动可以起来，用docker编排同事启动超过三个就会失败，你们自己试试。出现这个问题，看报错的时候，看到了那行代码提示死锁导致内存溢出



    


            在2019年11月09日 21:02，Fury Zhu 写道： Closed #2036.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alibaba/nacos/issues/2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180",
"url": "https://github.com/alibaba/nacos/issues/2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by whaty** [comment]
你们开源出来的nacos应该是阉割版的，绝非文档说的经得住双十一的版本



    


            在2019年11月10日 08:48，LiangCan 写道： 
        
            nacos部署到docker后，服务用docker单独一个个启动可以起来，用docker编排同事启动超过三个就会失败，你们自己试试。出现这个问题，看报错的时候，看到了那行代码提示死锁导致内存溢出



    


            在2019年11月09日 21:02，Fury Zhu 写道： Closed #2036.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alibaba/nacos/issues/2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180",
"url": "https://github.com/alibaba/nacos/issues/2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nkorange** [comment]
> nacos部署到docker后，服务用docker单独一个个启动可以起来，用docker编排同事启动超过三个就会失败，你们自己试试。出现这个问题，看报错的时候，看到了那行代码提示死锁导致内存溢出 在2019年11月09日 21:02，Fury Zhu 写道： Closed #2036. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180", "url": "#2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

具体报错信息贴一下？

**Comment by nkorange** [comment]
> 你们开源出来的nacos应该是阉割版的，绝非文档说的经得住双十一的版本 在2019年11月10日 08:48，LiangCan 写道： nacos部署到docker后，服务用docker单独一个个启动可以起来，用docker编排同事启动超过三个就会失败，你们自己试试。出现这个问题，看报错的时候，看到了那行代码提示死锁导致内存溢出 在2019年11月09日 21:02，Fury Zhu 写道： Closed #2036. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180", "url": "#2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

我说了，核心逻辑是一样的，RaftCore这段逻辑是基本没有变动的。

**Comment by whaty** [comment]
> > 你们开源出来的nacos应该是阉割版的，绝非文档说的经得住双十一的版本 在2019年11月10日 08:48，LiangCan 写道： nacos部署到docker后，服务用docker单独一个个启动可以起来，用docker编排同事启动超过三个就会失败，你们自己试试。出现这个问题，看报错的时候，看到了那行代码提示死锁导致内存溢出 在2019年11月09日 21:02，Fury Zhu 写道： Closed #2036. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180", "url": "#2036?email_source=notifications\u0026email_token=AGITVB4B27RQEEJYC7ZTC2LQS2YHVA5CNFSM4JKVLM62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUYCKZFA#event-2785324180", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
> 
> 我说了，核心逻辑是一样的，RaftCore这段逻辑是基本没有变动的。

给你看下截图，开始nacos起来的时候，nacos开了10个数据库连接，当我项目启动的时候，nacos自己就挂了，连接池清零了，访问8848也访问不了，说明nacos已经挂了。然后我的项目报找不到配置。
![image](https://user-images.githubusercontent.com/26294919/68559682-d5eeb900-0478-11ea-8e3c-6591f7d620d4.png)

**Comment by whaty** [comment]
> 项目

感觉nacos不稳定啊！你们咋弄到生产上的，我不敢啊

**Comment by nkorange** [comment]
> > 项目
> 
> 感觉nacos不稳定啊！你们咋弄到生产上的，我不敢啊

需要看下nacos挂的原因，dmesg | grep java或者看看{nacos.home}/logs/nacos.log里面报错

**Comment by whaty** [comment]
> > > 项目
> > 
> > 
> > 感觉nacos不稳定啊！你们咋弄到生产上的，我不敢啊
> 
> 需要看下nacos挂的原因，dmesg | grep java或者看看{nacos.home}/logs/nacos.log里面报错

该日志里面没有报错，最迟的只有启动成功的日志
![image](https://user-images.githubusercontent.com/26294919/68561548-e73bc380-0480-11ea-84e2-7a297780852d.png)

**Comment by whaty** [comment]
> > > 项目
> > 
> > 
> > 感觉nacos不稳定啊！你们咋弄到生产上的，我不敢啊
> 
> 需要看下nacos挂的原因，dmesg | grep java或者看看{nacos.home}/logs/nacos.log里面报错

数据库有以下信息，跟这个有关吗？什么情况会导致这个？
![image](https://user-images.githubusercontent.com/26294919/68561674-895bab80-0481-11ea-8f93-0e323494e30e.png)

**Comment by paderlol** [comment]
你们这是数据库主从都没启动成功，这个主从是我做的镜像演示的，你们如果完全要做生产主从，需要自己去实现。

**Comment by whaty** [comment]
> 你们这是数据库主从都没启动成功，这个主从是我做的镜像演示的，你们如果完全要做生产主从，需要自己去实现。

数据库启动成功了呀，而且能正常连接！出现这个提示，是在nacos挂掉的时候

**Comment by whaty** [comment]
> 你们这是数据库主从都没启动成功，这个主从是我做的镜像演示的，你们如果完全要做生产主从，需要自己去实现。

而且现在的关键问题，是为什么同时启动多个模块，nacos会挂了，一个个模块去启动没问题

> 你们这是数据库主从都没启动成功，这个主从是我做的镜像演示的，你们如果完全要做生产主从，需要自己去实现。

还是说开源出来的这个版本的nacos，只是提供一个注册中心、配置中心的思路，本就不是用来上生产的
