### ISSUE TITLE
希望可以直接支持Mysql 8

### ISSUE THREAD

**Issue by superxxl** [alibaba/nacos#2038]
- Mysql 8向下兼容Mysql 5

- 每次改源码去支持Mysql 8 比较麻烦

**Comment by nkorange** [comment]
https://github.com/alibaba/nacos/pull/855 请参考这个PR的说明，只需要添加驱动包到plugins/mysql目录即可。

**Comment by JL-Code** [comment]
> plugins

![image](https://user-images.githubusercontent.com/14163944/80312638-baa21b00-8818-11ea-8fa4-8854cfc81924.png)
![image](https://user-images.githubusercontent.com/14163944/80312638-baa21b00-8818-11ea-8fa4-8854cfc81924.png)
这并不能解决任何问题！！！
