### ISSUE TITLE
发现了你的bug

### ISSUE THREAD

**Issue by huohuanhuan** [alibaba/nacos#2048]
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local. /cluster.local /g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts

2个空格导致的BUG。
修改为下面即可恢复
cp /etc/hosts ~/hosts.new && sed -i 's/cluster.local./cluster.local/g' ~/hosts.new && cp -f ~/hosts.new /etc/hosts

**Comment by nkorange** [comment]
你说的是nacos-docker项目还是nacos-k8s项目？

**Comment by paderlol** [comment]
这两个空格是必要的，需要兼容没有.和有.的情况

**Comment by paderlol** [comment]
> 你说的是nacos-docker项目还是nacos-k8s项目？

他这个是指的nacos k8s里面的自动发现的插件

**Comment by huohuanhuan** [comment]
nacos-k8s  因为这2个空格，并没有修改hosts文件，所以K8S环境启动不起来

**Comment by huohuanhuan** [comment]
而我还没有能力修改你的插件。。。

**Comment by paderlol** [comment]
你这个是带点还是不带点的情况

**Comment by huohuanhuan** [comment]
cluster里面配置的是不带电，host文件里带. 因为空格的原因，插件没有修改成功hosts文件，所以导致集群异常

**Comment by paderlol** [comment]
你能截图一下你hosts里面的格式吗？我之前测试是可以的，如果改回没点就不兼容了，那可能我就会考虑移除掉插件了。

**Comment by huohuanhuan** [comment]
<img width="824" alt="6D173CBF-44D9-4fc3-9B6E-0A5FE2621940" src="https://user-images.githubusercontent.com/38578400/68639157-ab673380-053e-11ea-969d-4572a80077be.png">

**Comment by huohuanhuan** [comment]
我找了很久，最后是发现你插件里面的sed修改没有生效导致的

**Comment by paderlol** [comment]
懂了，是有这个问题，因为没办法完全的兼容，所以可能我会去掉这个，这个点由你们自己处理最好，或者移除这个peer。

**Comment by huohuanhuan** [comment]
基础比较薄弱。。目前没有能力修改你的东西，但是我觉得你可以做一个判断，如果是centos，你用一个语句，如果是另外不兼容的系统。你再用一个语句，这样就可以简单的解决这个问题

**Comment by huohuanhuan** [comment]
比如你使用下面这个语句，
if `cat /etc/redhat-release |awk '{print $1}'`;do
echo 这是centos;
done

**Comment by paderlol** [comment]
现在不是系统地问题，而是匹配空格的问题，因为有的后面是没带点的。所以必要要兼容，我有时间看下吧，你现在能自己先处理下这个吗？还有麻烦把这个issue提到nacos k8s这个工程里面，关掉这个可以吗？
