### ISSUE TITLE
Register the service to a different namespace

### ISSUE THREAD

**Issue by VolcanoOves** [alibaba/nacos#2050]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

现在有这样的一种情况，我有多个namespace管理着多个不同的微服务集群，对外输出有一个统一的网关，如何能将网关与不同的namespace中的服务进行对接，除了在网关中加入nginx的方式之外，有没有其他更合适的方式处理这种情况。

Now there is such a situation, I have multiple namespaces to manage multiple different microservice clusters, and there is a unified gateway for external output. How can I connect the gateway to services in different namespaces, except in the gateway. In addition to the nginx approach, is there any other more appropriate way to handle this situation?

**Comment by nkorange** [comment]
目前只能通过open api获取多个namespace的服务，客户端方法的支持会在权限控制支持后再考虑。

**Comment by VolcanoOves** [comment]
好吧，这样的话，现在只能将所有服务归纳在同一个namespace里，如果以后能提供服务跨namespace注册的话，可以将各个微服务集群里面的对外输出API服务再集中注册到与统一gateway同一个namespace就完美了。
