### ISSUE TITLE
k8s集群版提示no available server

### ISSUE THREAD

**Issue by wcollin** [alibaba/nacos#2051]
错误：
2019-11-12 11:05:47.314 ERROR 1 --- [3b-aa9ff143b2dc] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException httpPost] currentServerAddr: http://nacos-headless.default.svc.cluster.local.:8848， err : Read timed out
2019-11-12 11:05:47.315 ERROR 1 --- [3b-aa9ff143b2dc] c.a.n.c.config.http.ServerHttpAgent      : no available server, currentServerAddr : http://nacos-headless.default.svc.cluster.local.:8848
2019-11-12 11:05:47.316 ERROR 1 --- [3b-aa9ff143b2dc] c.a.n.client.config.impl.ClientWorker    : [fixed-nacos-headless.default.svc.cluster.local._8848-bad9158b-4e63-4004-ac3b-aa9ff143b2dc] [check-update] get changed dataId exception

java.net.ConnectException: no available server, currentServerAddr : http://nacos-headless.default.svc.cluster.local.:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352)
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

2019-11-12 11:05:47.316 ERROR 1 --- [3b-aa9ff143b2dc] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.net.ConnectException: no available server, currentServerAddr : http://nacos-headless.default.svc.cluster.local.:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352)
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

问题描述：
启动正常，过一会提示no available server，确认网络和集群dns解析正常。
![image](https://user-images.githubusercontent.com/17266901/68639317-23355e00-053f-11ea-8622-158f9014757b.png)

版本信息：
k8s 1.13.10
nacos 1.1.4
spring 2.0
jdk11

**Comment by nkorange** [comment]
执行以下命令看看：
```
curl -v 'http://nacos-headless.default.svc.cluster.local.:8848/nacos/v1/cs/health'
```

**Comment by wcollin** [comment]
> curl -v 'http://nacos-headless.default.svc.cluster.local.:8848/nacos/v1/cs/health'

/ # curl -v 'http://nacos-headless.default.svc.cluster.local.:8848/nacos/v1/cs/health'
* Expire in 0 ms for 6 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 1 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 2 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
* Expire in 0 ms for 1 (transfer 0x5564733e8620)
*   Trying 10.243.93.3...
* TCP_NODELAY set
* Expire in 149999 ms for 3 (transfer 0x5564733e8620)
* Expire in 200 ms for 4 (transfer 0x5564733e8620)
* Connected to nacos-headless.default.svc.cluster.local (10.243.93.3) port 8848 (#0)
> GET /nacos/v1/cs/health HTTP/1.1
> Host: nacos-headless.default.svc.cluster.local:8848
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 2
< Date: Tue, 12 Nov 2019 03:44:23 GMT
< 
* Connection #0 to host nacos-headless.default.svc.cluster.local left intact

**Comment by paderlol** [comment]
把k8s里面的健康检查liveiness去掉，再启动

**Comment by wcollin** [comment]
> 把k8s里面的健康检查liveiness去掉，再启动

开始就去掉了，不然集群都无法启动。

**Comment by paderlol** [comment]
看下nacos  log 你使用的是自动扩容的方式启动的吗？看下集群选主是否成功。

**Comment by wcollin** [comment]
> 看下nacos log 你使用的是自动扩容的方式启动的吗？看下集群选主是否成功。

我上面的截图是dashboard里面截图的，看着选举是成功的，我直接就启动3个。

**Comment by paderlol** [comment]
Nacos控制台显示选举成功还是k8s的控制台？k8s只能代表启动成功

**Comment by wcollin** [comment]
> Nacos控制台显示选举成功还是k8s的控制台？k8s只能代表启动成功

日志和控制台都表示成功，而且可以正常使用，是使用一段时间后开始报错的。

**Comment by nkorange** [comment]
这个问题可能和 https://github.com/alibaba/nacos/issues/2056 有关，是客户端侧的问题，下个版本会解决。

**Comment by chuntaojun** [comment]
> 这个问题可能和 #2056 有关，是客户端侧的问题，下个版本会解决。

server 端对应的任务处理逻辑也需要优化下，这周会pr

**Comment by wcollin** [comment]
> > 这个问题可能和 #2056 有关，是客户端侧的问题，下个版本会解决。
> 
> server 端对应的任务处理逻辑也需要优化下，这周会pr

OK，那我先关闭issue
