### ISSUE TITLE
service using hostname as ip value will  return 400

### ISSUE THREAD

**Issue by ryankong** [alibaba/nacos#2052]
visit by zuul will got 400 error 
and  the service provider throw error " The host [zuul.xxx.com,zuul.xxx.com] is not valid
Note: further occurrences of request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: The character [,] is never valid in a domain name.
" 
when the service provider use public hostname 
to be "spring.cloud.nacos.discovery.ip"  value

**Comment by nkorange** [comment]
Report this to alibaba/spring-cloud-alibaba please.
