### ISSUE TITLE
配置了namespace，但实际不一致

### ISSUE THREAD

**Issue by jqsl2012** [alibaba/nacos#2055]
配置了namespace，但实际不一致，dev的namespace下没有服务，全都在默认public下了。

	<nacos:global-properties server-addr="127.0.0.1:8848" namespace="2fa2ea31-d52d-4b18-aff4-824a15218502"/>

![image](https://user-images.githubusercontent.com/6802595/68730181-e92f8f00-0606-11ea-9ddc-10d71581eb6d.png)

![image](https://user-images.githubusercontent.com/6802595/68730203-f8aed800-0606-11ea-89fd-5c679df983ee.png)

**Comment by chuntaojun** [comment]
我会去看下，这个issue我会转移到nacos-spring-project项目中

**Comment by WywTed** [comment]
使用 dubbo 2.7.1  的时候也出现过这种情况， namespace 配置无效； 简单调试代码发现， 在实例化 NacosNamingService 的时候， 读不到 dubbo 的 parameter 参数，实例化完 NacosNamingService 后在加载 dubbo 相关配置时又能读到  dubbo.registry.parameters 相关参数，但这时 nacos 注册的 namespace 肯定是默认的 ‘public’ 了，这个时候应该是 来加载相关的了，但这种情况并不是一定发生，不知道是不是和相关的依赖也有关系，觉得需要 将 依赖信息也一并贴上来 @jqsl2012  （ps:  如果要临时解决这个，可以在 环境变量中加上 ‘namespace=xx’ 的配置， 因为 nacos-client 端源码会解析环境变量 ‘namespace’）
