### ISSUE TITLE
Nacos配置中心如何高可用

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/nacos#2059]
我在使用spring boot整合nacos时，注册中心可以高可用。但是配置中心如何高可用。因为我的配置文件是放在nacos配置中心的，但是设置nacos.config.server-addr=127.0.0.1:8848在127.0.0.1宕机(故意停掉后)项目就无法运行。可否用逗号隔断127.0.0.1:8848,127.0.0.2:8848,127.0.0.3:8848。如果第一个不可用就依次读下一个IP的配置

**Comment by zhuyouzhufu** [comment]
![Uploading image.png…]()

**Comment by nkorange** [comment]
请提到https://github.com/nacos-group/nacos-spring-boot-project
