### ISSUE TITLE
How to configure the database

### ISSUE THREAD

**Issue by hxy1991** [alibaba/nacos#206]

**Comment by hxy1991** [comment]
0. Create a database named `nacos_config` and import the `nacos/conf/nacos-mysql.sql`

1. Configure `nacos/conf/application.properties`
```
db.num=1
# example
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=root
```

2. Configure `nacos/conf/cluster.conf`
```
127.0.0.1
```

3. Startup
```
sh nacos/bin/startup.sh
```

4. Related documents
- [Cluster Mode Deployment](https://nacos.io/en-us/docs/cluster-mode-quick-start.html)

**Comment by hackstepz** [comment]
这种方式部署后，服务注册的时候产生 No leader at present 异常

**Comment by SizakeYang** [comment]
如果是ubuntu/debain的话,127.0.0.1需改为127.0.1.1;

If it is ubuntu/debain, 127.0.0.1 needs to be changed to 127.0.1.1
