### ISSUE TITLE
nacos在获取配置的时候返回null

### ISSUE THREAD

**Issue by iamxiaojuan** [alibaba/nacos#2060]
启动项目的时候报以下警告： There is no content for NacosPropertySource from dataId
我在断点调试的时候，发现
ClientWorker这个类调用 getServerConfig的时候（agent.httpGet 请求nacos返回配置），234这行代码返回的result code是404

这是怎么回事呢？
求大佬解疑！！

**Comment by nkorange** [comment]
看下控制台上是否有这个配置

**Comment by fesine** [comment]
使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。

**Comment by rushsky518** [comment]
> 使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。

publish 之后，马上 query，确实可能返回 null

**Comment by easyhaloo** [comment]
建议加上一个重试次数的配置开关，避免这样的情况发生

**Comment by fesine** [comment]
> > 使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。
> 
> publish 之后，马上 query，确实可能返回 null

我测试的情况nacos服务端已经配置好，并且发布状态，但根据对应的dataid查询的时候返回空，此时再对此dataid进行publish，是成功的，等几秒后，再次查询，仍然返回null。也就是说发布配置是可以的，但查询都不行。

**Comment by nkorange** [comment]
> > 使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。
> 
> publish 之后，马上 query，确实可能返回 null

你指的是bug吗，还是设计上就是这样？

**Comment by rushsky518** [comment]
> > > 使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。
> > 
> > 
> > publish 之后，马上 query，确实可能返回 null
> 
> 你指的是bug吗，还是设计上就是这样？

客户端 publish 后，server 首先写入数据库，然后异步地加载到 CACHE， 并 dump 到磁盘中，如果客户端立刻 pull，而 CACHE 中没有数据，则会 [read-lock] failed
![image](https://user-images.githubusercontent.com/20531420/70490574-bdd28e00-1b39-11ea-9e28-1dc82815a557.png)

**Comment by nkorange** [comment]
> > > > 使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。
> > > 
> > > 
> > > publish 之后，马上 query，确实可能返回 null
> > 
> > 
> > 你指的是bug吗，还是设计上就是这样？
> 
> 客户端 publish 后，server 首先写入数据库，然后异步地加载到 CACHE， 并 dump 到磁盘中，如果客户端立刻 pull，而 CACHE 中没有数据，则会 [read-lock] failed
> ![image](https://user-images.githubusercontent.com/20531420/70490574-bdd28e00-1b39-11ea-9e28-1dc82815a557.png)

@iamxiaojuan 是的，发布配置是异步的，写入数据库就返回成功。但是不一定所有Server都更新到了最新的配置。

**Comment by cdfive** [comment]
> > 使用nacos api publishConfig能成功，但通过api读取刚刚push上去的数据返回的就是null。执行代码是复制的配置页面的示例代码。
> 
> publish 之后，马上 query，确实可能返回 null

同样遇到该问题，请问有什么好的解决方式吗？发布配置后马上查询是很常见的需求。
