### ISSUE TITLE
nacos config changed could trigger log4j2 reinitialize

### ISSUE THREAD

**Issue by 631359746** [alibaba/nacos#2062]
when properties changed in yaml file at nacos console,i see the log of log4j2 reinitialize
nacos client version: 1.1.4
log4j2 version: 2.11.2

Is this normal?

**Comment by nkorange** [comment]
Which project were you using? nacos-spring, nacos-spring-boot, spring-cloud-alibaba?

**Comment by 631359746** [comment]
spring-cloud-alibaba version: 2.1.0.RELEASE

**Comment by chuntaojun** [comment]
> spring-cloud-alibaba version: 2.1.0.RELEASE

it's spring mechanism，when config change, the ApplicationContext will be refresh
