### ISSUE TITLE
Nacos 作为注册中心如何配置踢出超时服务的时间?

### ISSUE THREAD

**Issue by sunxiang0918** [alibaba/nacos#2064]
在 eureka中  server端可以配置: evictionIntervalTimerInMs来设定驱逐下线服务的时间.
                       Client端可以配置: lease-expiration-duration-in-seconds来设定 心跳移除时间.

在Nacos 我还没找到类似的配置~ 

请问,该如何配置呢?  谢谢

**Comment by nkorange** [comment]
https://nacos.io/en-us/blog/nacos%201.1.0.html 参考“服务自定义心跳周期”

**Comment by sunxiang0918** [comment]
谢谢~
找到了. 就是在配置文件中 可以配置  `ip-delete-timeout`,`heart-beat-interval`,`heart-beat-timeout`.
不过,我看文档和代码注释写的 单位是秒. 而实际试出来感觉应该是 毫秒呢~.  我配置`heart-beat-interval=2` 从DEBUG日志来看 狂打心跳日志,改成2000 差不多就是2秒心跳一次了.

另外,请问,如果是搭建的nacos集群. `server-addr`如何配置呢?是一定要把nacos集群做个VIP出来,配置成VIP? 还是可以像 eureka一样,多个服务地址可以使用逗号分隔?

**Comment by nkorange** [comment]
> 谢谢~
> 找到了. 就是在配置文件中 可以配置 `ip-delete-timeout`,`heart-beat-interval`,`heart-beat-timeout`.
> 不过,我看文档和代码注释写的 单位是秒. 而实际试出来感觉应该是 毫秒呢~. 我配置`heart-beat-interval=2` 从DEBUG日志来看 狂打心跳日志,改成2000 差不多就是2秒心跳一次了.

这个是SpringCloudAlibaba这边配置的单位和Nacos客户端里的不一致，你如果使用SpringCloudAlibaba，就以那边的文档为准。

> 
> 另外,请问,如果是搭建的nacos集群. `server-addr`如何配置呢?是一定要把nacos集群做个VIP出来,配置成VIP? 还是可以像 eureka一样,多个服务地址可以使用逗号分隔?

可以用逗号分隔。

**Comment by sunxiang0918** [comment]
哦,明白了谢谢!!

还有一个配置没找到的,就是  nacos作为服务注册和发现, 有客户端的认证机制么?  我看spring-cloud-alibaba-nacos 的配置里面有 `accessKey`和`secretKey`可以配置. 但是在Nacos服务器上 没找到在哪儿能生成AK/SK?  还是说 这里的AK/SK 就是nacos的用户名和密码?

**Comment by nkorange** [comment]
> 哦,明白了谢谢!!
> 
> 还有一个配置没找到的,就是 nacos作为服务注册和发现, 有客户端的认证机制么? 我看spring-cloud-alibaba-nacos 的配置里面有 `accessKey`和`secretKey`可以配置. 但是在Nacos服务器上 没找到在哪儿能生成AK/SK? 还是说 这里的AK/SK 就是nacos的用户名和密码?

目前还不能，请参考 #1105
