### ISSUE TITLE
请问什么时候可以支持针对dubbo服务提供者的测试功能

### ISSUE THREAD

**Issue by dolphin-zp** [alibaba/nacos#2065]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
When can I support the testing function for Dubbo service provider

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
你说的是健康检查？

**Comment by dolphin-zp** [comment]
> 你说的是健康检查？
不是的，我指的是针对dubbo服务提供者提供的服务

**Comment by nkorange** [comment]
> > 你说的是健康检查？
> > 不是的，我指的是针对dubbo服务提供者提供的服务

请详细说一下，不太清楚你说的是什么。

**Comment by nkorange** [comment]
> dubbo服务提供者将服务注册到nacos上，在nacos上可以看到所有的服务提供者提供的服务，希望nacos能够在此基础上提供一个可以测试服务的功能。

我理解这个是要模拟Consumer去调用Provider吗？

**Comment by dolphin-zp** [comment]
是的

**Comment by nkorange** [comment]
> 是的

这个功能无法在Nacos侧实现，Nacos这边无法区分注册的服务来源是Dubbo、Spring Cloud还是其他框架。Nacos的设计就是要支持跨服务框架的服务注册与发现。

**Comment by dolphin-zp** [comment]
好的，谢谢
