### ISSUE TITLE
nacos docs needs to be updated

### ISSUE THREAD

**Issue by JonSmall** [alibaba/nacos#2067]
The docs needs to be update on website address：
https://nacos.io/en-us/docs/use-nacos-with-dubbo.html

this version on this site is 2.6.5，I tried 2.7.4.1，it`s not work

better provided a complete configration project on github

**Comment by JonSmall** [comment]
<groupId>com.alibaba</groupId>
<artifactId>dubbo-registry-nacos</artifactId>
<version>0.0.1</version>

docs version 0.0.1

at this website
https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-registry-nacos
you see version at least 2.7.4.1

**Comment by nkorange** [comment]
OK, I think this document needs to be updated.
But ```dubbo-registry-nacos``` is not developed by Nacos team, it's developed by Dubbo team. So what I will do is just about the same as you, which to ask the Dubbo team about this version.

**Comment by nkorange** [comment]
@JonSmall The Dubbo team tells me the latest 2.7.4.1 should work. If you have any error you can create an issue in Dubbo project, thanks.

**Comment by nkorange** [comment]
The document is updated: https://nacos.io/zh-cn/docs/use-nacos-with-dubbo.html
