### ISSUE TITLE
Nacos-istio with pilot-mcp occured an error

### ISSUE THREAD

**Issue by huhu-sky** [alibaba/nacos#2068]
## Issue Description
testing nacos-istio mcp function
Type: *bug report*

### Describe what happened (or what feature you want)
start nacos with mcp function, and config the pilot with nacos' ip:18848, then regist a service to nacos, it occured an error
~~~
2019-11-15T11:28:42.705782Z	warn	Discarding incoming MCP resource: validation failed (nacos/providers:com.test.demo.test.api.HelloService.snmsa.ns): 2 errors occurred:
	* domain name "providers:com.test.demo.test.api.HelloService.snmsa.ns.nacos" invalid (label "providers:com" invalid)
	* invalid tag value: "providers:dubbo:com.test.demo.test.api.HelloService"


2019-11-15T11:28:42.773445Z	info	starting discovery service at http=[::]:8080 grpc=[::]:15010
~~~
### Describe what you expected to happen
N/A

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
kubectl version: v1.12.6
nacos version: 1.1.4
istio version: 1.2.2

### Anything else we need to know?
Where can i find a **detail document** to learn how to use nacos-mcp-pilot.

**Comment by nkorange** [comment]
Your can refer to https://nacos.io/en-us/blog/nacos%201.1.4.html. For this error, my guess is ```:``` is not allowed to use as part of a service name in Pilot. ```:``` should be converted to another character on Nacos side.
