### ISSUE TITLE
Document bug: the path of modify Instance api  is "/nacos/v1/ns/instance/update" instead of "/nacos/v1/ns/instance"

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#207]
**Version**
0.3.0

**Description**
In the document:

![image](https://user-images.githubusercontent.com/2010632/47891079-a6cc6180-de8c-11e8-8915-42e599d22e4a.png)

In the code:
![image](https://user-images.githubusercontent.com/2010632/47891094-b0ee6000-de8c-11e8-9bb9-7ac258425575.png)

The path descriped in the chiness and english document is wrong according to the code

**Suggestion** 
Modify the the path in the document

**Comment by nkorange** [comment]
Already fixed, thank you.
