### ISSUE TITLE
Question about the leader in the nacos cluster

### ISSUE THREAD

**Issue by jmilktea** [alibaba/nacos#2072]
I have a question, what is the role of the leader in the nacos cluster? I can still register the service and configuration with the follower node, or when the cluster has only one candidate node, I can still register the service and configuration with it, so what is the role of the leader? Thank you

**Comment by nkorange** [comment]
The Raft protocol is used to register ```persistent``` instance. By default you register ```ephemeral``` instance, which doesn't need Raft. Refer to https://nacos.io/en-us/blog/nacos1.0.0.html to learn about what ```ephemeral``` instance is.
