### ISSUE TITLE
nacos集群一个节点与其他节点的网络突然中断后，客户端仍然一直访问该节点导致心跳失败

### ISSUE THREAD

**Issue by ghyaauoo** [alibaba/nacos#2073]
我们在私有网络中部署了三个节点的nacos 集群，分别在192.168.0.11/12/13上，其中11节点为原先的leader
![image](https://user-images.githubusercontent.com/28587506/69117172-dd8e0d80-0ac9-11ea-89dc-b57c1ea9c8a5.png)
![image](https://user-images.githubusercontent.com/28587506/69117187-e7b00c00-0ac9-11ea-9c95-aa02d9a022a4.png)
今天私有网络发生故障，11节点与12、13节点的网络突然中断了，集群正常的进行了重新选举，如下：
![image](https://user-images.githubusercontent.com/28587506/69117347-4f665700-0aca-11ea-9601-edfc74913f46.png)
但是nacos的客户端程序一直在尝试与11进行心跳检测，其他服务通过feign调用该服务一直失败被降级，请问这个是什么原因，nacos版本是1.1.1，客户端版本是0.9.0。

**Comment by nkorange** [comment]
心跳失败，会触发Nacos的保护阈值，正常不会影响服务查询。同时客户端的心跳是随机请求一个Server的，所以是客户端只配置了Nacos服务端11的地址？

**Comment by ghyaauoo** [comment]
三个节点都配置了

**Comment by nkorange** [comment]
> 三个节点都配置了

那看下12，13有收到这个服务的心跳吗？
