### ISSUE TITLE
When the gateway is used in combination with the ribbon, there is often an error: java.lang.nullpointerexception: null

### ISSUE THREAD

**Issue by 377796216** [alibaba/nacos#2074]
Question
When the gateway is used in combination with the ribbon, there is often an error: java.lang.nullpointerexception: null  
Sometimes it's good, sometimes it's bad, sometimes it's OK for a day, sometimes it'll reappear in a few minutes.
But I have no problem bypassing the gateway to access the service directly.

Bug report
2019.11.19 16:04:28.441 [reactor-http-epoll-8] ERROR [org.springframework.core.log.CompositeLog.error:117] - [33d09a99] 500 Server Error for HTTP GET "/wb/upms/v1/getOrgTree?parentId=-1" java.lang.NullPointerException: null

Enhancement
SpringCloud Version：Greenwich.RELEASE
SpringCloud Alibaba Version ：2.1.0.RELEASE
jdk Version ： 1.8
SpringBoot Version:  2.1.4.RELEASE

**Comment by nkorange** [comment]
Any error stack related with Nacos?
