### ISSUE TITLE
In the service list, click the service details and then click a service to offline, but it doesn't work. You can still access the service

### ISSUE THREAD

**Issue by 377796216** [alibaba/nacos#2075]
In the service list, click the service details and then click a service to offline, but it doesn't work. You can still access the service

Enhancement
SpringCloud Version：Greenwich.RELEASE
SpringCloud Alibaba Version ：2.1.0.RELEASE
jdk Version ： 1.8
SpringBoot Version: 2.1.4.RELEASE

**Comment by nkorange** [comment]
Please use the following command to verify if server has offline this instance:
```
curl '$nacos_server:8848/nacos/v1/ns/instance/list?serviceName=xxxx&namespaceId=yyy'
```
