### ISSUE TITLE
配置页面的模糊查询无效

### ISSUE THREAD

**Issue by DarrenLuo** [alibaba/nacos#2079]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

当我在配置页面进行查询的时候不能进行模糊查询，比如我有一个 group 为 abc，我搜索 a 的话搜索不到

**Comment by DarrenLuo** [comment]
唔，看了一下源码，需要搜索 a* 才能进行模糊查询

**Comment by xiaoyifang** [comment]
最好也可以忽略大小写进行匹配,比如搜索A*
也可以搜索   *bc

**Comment by kitsrc** [comment]
@chuntaojun  * 通配符这个用法没有任何文档中发现，并且这真的是有点反常识习惯的模糊查询实现

**Comment by kitsrc** [comment]
1.3.0 中有相关更新吗？个人未发现
