### ISSUE TITLE
怎样获取局部变量

### ISSUE THREAD

**Issue by moayi** [alibaba/nacos#2088]
看demo都是获取的类的成员变量，那怎样去获取方法内部的局部变量？有没有类似于NacosValueUtil.getValue("")的方法

**Comment by nkorange** [comment]
具体是哪个demo，能否贴一下代码地址？

**Comment by moayi** [comment]
@Service
public class PurchaseOrderImpl implements PurchaseOrder {

    @NacosValue(value = "${serNo}",autoRefreshed = true)
     private  String serNo;

    @Override
    public void addPO(Order order) {
        /*@NacosValue(value = "${remoteURL}",autoRefreshed = true)
        private  String remoteURL;*/
        String remoteURL ="";
        
        System.out.println("======>"+remoteURL);
    }
}
我怎样在方法内部获取r在nacos的remoteURL对应的值，并能保证实时刷新？
