### ISSUE TITLE
Find an operation that does not require an account password to obtain remote nacos permissions/发现一个不需要帐号密码就可以获取远程nacos权限的操作

### ISSUE THREAD

**Issue by liuzhuoming23** [alibaba/nacos#2093]
首先第一步：修改本机hosts文件添加127.0.0.1 console.nacos.io（这里是你想登陆的nacos域名）
第二步：修改nacos端口为80并启动本机nacos
第三步：按照自己的nacos账号密码登录本机nacos
第四步：删除刚才的hosts配置
第五步：刷新
然后你会发现你没有console.nacos.io的nacos账号密码的情况下登进了console.nacos.io的nacos并且具有全部权限。

First step: modify the native hosts file to add 127.0.0.1 console.nacos.io (here is the nacos domain name you want to log in)
Step 2: Modify the nacos port to 80 and start the native nacos
Step 3: Log in to native nacos according to your own nacos account password
Step 4: Remove the hosts configuration just
Step 5: Refresh
Then you will find that you do not have the password of the nacos account password of console.nacos.io and log into the nacos of console.nacos.io and have full permissions.

**Comment by ontheway0101** [comment]
[JWT加密用的key都是这个](https://github.com/alibaba/nacos/blob/develop/console/src/main/java/com/alibaba/nacos/console/utils/JwtTokenUtils.java#L57)，所以会出现这种情况，建议nacos把该密钥设置可配置。

**Comment by hykjtt** [comment]
@i will solve it@
