### ISSUE TITLE
删除配置确认框中显示问题

### ISSUE THREAD

**Issue by watilion** [alibaba/nacos#2098]
在配置列表选中配置进行删除会有确认框弹出，其中有data Id和group列表，但是该列表只显示了标题，却不显示选中配置的对应信息
![删除配置确认框](https://user-images.githubusercontent.com/19620174/69475978-b2c7f000-0e0e-11ea-8036-d467d107982e.jpg)

**Comment by KeRan213539** [comment]
请详细描述复现步骤,我这边是正常的,没法复现...

**Comment by watilion** [comment]
@KeRan213539 版本为1.1.4，数据库表为1.0.1的时候创建的，复现步骤就是在配置列表选中一项配置，点击下方删除按钮就会出现这个问题，没有其他特殊操作

**Comment by KeRan213539** [comment]
@watilion 已经修复了,等更新就行
