### ISSUE TITLE
客户端的配置缓存未更新？

### ISSUE THREAD

**Issue by lianran123** [alibaba/nacos#2100]
有两组nacos集群，一个在k8s，一个在常规的虚拟机中，后端的mysql都是同一个。
当前遇到个问题，通过nacos（随意一组nacos）修改配置后，k8s中的客户端读到了新配置，虚拟机中的客户端的本地存放的配置文件也更新了，但是从程序中的日志看到配置还是旧的，重起业务也不行，直到echo 1 > /proc/sys/vm/drop_caches，新的配置才生效，这大概是什么问题？是因为pagecache中的内容没有更新掉？
nacos版本为1.1.3，在虚拟机的nacos中更新配置点了发布之后，一直无法读取到更新后的配置，但本地目录（/root/nacos/config/fixed-nacos-addr.nacos_8848-f8e76f66-0581-4703-89d7-d1f68ca031ee_nacos/snapshot-tenant/f8e76f66-0581-4703-89d7-d1f68ca031ee/HEALTH_GROUP）已经有更新后的配置文件。

**Comment by nkorange** [comment]
用的是哪个客户端？

**Comment by jianxuanbing** [comment]
版本：`1.2.0`
环境：`docker`
单机docker下，配置更新后，文件依旧没有更新
![image](https://user-images.githubusercontent.com/7100363/76389955-71505600-63a7-11ea-823a-9e1316971b72.png)

![image](https://user-images.githubusercontent.com/7100363/76390009-8f1dbb00-63a7-11ea-932d-c6491b60550f.png)
