### ISSUE TITLE
Springboot USES the switch namespace to read the configuration file with an error

### ISSUE THREAD

**Issue by tkqengineer** [alibaba/nacos#2101]
## use defalut namespace is ok
![image](https://user-images.githubusercontent.com/29010438/69523935-00279700-0fa0-11ea-8532-a2c131049035.png)

## use custom namespace is not fine
![image](https://user-images.githubusercontent.com/29010438/69524258-95c32680-0fa0-11ea-8bd1-5117a525c5cc.png)

**Comment by nkorange** [comment]
Please report this error to https://github.com/nacos-group/nacos-spring-boot-project
