### ISSUE TITLE
nacos1.1.4配置mysql5.7.18无效

### ISSUE THREAD

**Issue by wenwh** [alibaba/nacos#2107]
I use nacos1.1.4 and mysql5.7.18, and make sure application.properties is correct,but data won't be write to mysql

## steps
1. create database nacos_devtest
2. run nacos-mysql.sql in nacos_devtest.
3. add config to the bottom of application.properties
spring.datasource.platform=mysql 
db.num=1
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos_devtest?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=root123
4.double click startup.cmd to start nacos server.
5.add a namespace throught browser
6.check tenant_info data, but it's not change.

## environment
windows 7
adopteopenjdk 1.8
nacos1.14
mysql5.7.18

**Comment by nkorange** [comment]
Does the new added namespace show correctly in browser?

**Comment by wenwh** [comment]
> Does the new added namespace show correctly in browser?

yes, and I check derby, the data is update. so it seems that mysql is not used at all.

**Comment by nkorange** [comment]
Please debug at this line:
https://github.com/alibaba/nacos/blob/b7f2c6278fd442e40f4fee4b65709e1acb50f7e0/config/src/main/java/com/alibaba/nacos/config/server/utils/PropertyUtil.java#L117

No related log is printed now, which will be optimized in the next version.

**Comment by wenwh** [comment]
I have used the latest version , and the issue don't appear again, thank you.
