### ISSUE TITLE
nacos-server startup.sh issue

### ISSUE THREAD

**Issue by sp1ra1** [alibaba/nacos#2111]
## Issue Description
bug report
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I run the nacos on my ubuntu 18.04 server this afternoon while using the startup.sh, it threw an error saying it needs JAVA_HOME variable to be defined. While I run then commend 'echo "$JAVA_HOME"' and it shows the directory.

### Describe what you expected to happen
It should run normally and could be accessed by the default ports.

### How to reproduce it (as minimally and precisely as possible)

1. no need, I just fix the error, and I want to report it so you guys could have a look
2. 
3. 

### Anything else we need to know?
Actually I checked with the startup.sh, it could not get my JAVA_HOME variables, and it sets like this:

[ ! -e "$JAVA_HOME/bin/java" ] && JAVA_HOME=/usr/local/java/jdk1.8.0_221
[ ! -e "$JAVA_HOME/bin/java" ] && JAVA_HOME=/usr/java
[ ! -e "$JAVA_HOME/bin/java" ] && JAVA_HOME=/opt/taobao/java
[ ! -e "$JAVA_HOME/bin/java" ] && unset JAVA_HOME 

and the first line above is the one I modified, and it works. so I am wondering why are you guys trying to set the directory like this, since different people have different habits to install the jdk. And could you solve the problem in the next release?

**Comment by nkorange** [comment]
You can set JAVA_HOME outside of the startup.sh, like ```mvn```.
