### ISSUE TITLE
nacos可以管理xml文件并注入spring容器吗

### ISSUE THREAD

**Issue by helei-mianyang** [alibaba/nacos#2112]
nacos可以管理xml文件并注入spring容器吗

**Comment by chuntaojun** [comment]
请注意看nacos-spring-context，理论上是可以的，https://github.com/nacos-group/nacos-spring-project

**Comment by chuntaojun** [comment]
如果有相关的与Spring有关的问题

1. spring-mvc：https://github.com/nacos-group/nacos-spring-project
2. springboot：https://github.com/nacos-group/nacos-spring-boot-project
3. spring-cloud：https://github.com/alibaba/spring-cloud-alibaba
