### ISSUE TITLE
怎么把修改后的nacos-console打包到nacos-server？

### ISSUE THREAD

**Issue by hengboy** [alibaba/nacos#2113]
修改了nacos-console的界面部分内容，现在想打包到nacos-server.jar内该怎么操作？

**Comment by hengboy** [comment]
问题已经解决，在源码BUILDING文件内找到了答案

**Comment by DarrenLuo** [comment]
console/src/main/resources/static 中的代码会自动打包进入最后的 jar 包中修改前端源码的的话需要将 console-fe 中 build 出来的代码拷出来，可以使用 console/src/main/resources/static/console-fe/build 中的 copy-dist.js 和 copyFile.js 脚本自动处理
