### ISSUE TITLE
Whether nacos will support query push trajectories？

### ISSUE THREAD

**Issue by easylife94** [alibaba/nacos#2118]
## Whether nacos will support query push trajectories

Type: *feature request*

###  Push trajectories
Ali cloud application configuration management ACM product is based on nacos, there is a query push track function.However, I did not find this function in the nacos server. Will subsequent versions consider adding this feature?

**Comment by nkorange** [comment]
I think you are referring to push trace in ACM. We welcome you to contribute for it, but unfortunately we have no plan to implement it in our upcoming versions.
