### ISSUE TITLE
nacos 集群采用nginx做负载，nginx监听80端口，client默认连接8848端口

### ISSUE THREAD

**Issue by khiker007** [alibaba/nacos#2119]
## Issue Description

nacos 集群采用nginx做负载，nginx监听80端口，client默认连接8848端口

### How to reproduce it (as minimally and precisely as possible)

![image](https://user-images.githubusercontent.com/10723358/69799448-42561000-120e-11ea-835d-8b18930fecac.png)

### Tell us your environment

nacos 1.1.4

除了-Dnacos.naming.exposed.port启动参数外，还有其他方法修改端口么

**Comment by nkorange** [comment]
nacos-addr的地址加上 ```:80```
