### ISSUE TITLE
请问配置中心可以管理日志框架吗，比如log4j logback

### ISSUE THREAD

**Issue by helei-mianyang** [alibaba/nacos#2120]
请问配置中心可以管理日志框架吗，比如log4j logback

**Comment by helei-mianyang** [comment]
请问配置中心可以管理日志框架吗，比如log4j logback

**Comment by nkorange** [comment]
具体需求是什么？

**Comment by SoyMeng** [comment]
spring boot 支持日志配置

**Comment by esolve** [comment]
同问

**Comment by zhongkuiGuo** [comment]
可以把logback的xml文件放到nacos中，但是spring无法正常加载，因为nacos是通过接口/nacos/v1/cs/configs?dataId=logback-spring.xml调用读取配置，而spring中识别日志配置文件是要通过.xml后缀的，所以会报错，无法正常读取，只能把logback放到各个服务中，然后在nacos中统一写一个读取目录logging.config=classpath:×××

**Comment by zhongkuiGuo** [comment]
@helei-mianyang

**Comment by lgw79674057** [comment]
> 可以把logback的xml文件放到nacos中，但是spring无法正常加载，因为nacos是通过接口/nacos/v1/cs/configs?dataId=logback-spring.xml调用读取配置，而spring中识别日志配置文件是要通过.xml后缀的，所以会报错，无法正常读取，只能把logback放到各个服务中，然后在nacos中统一写一个读取目录logging.config=classpath:×××

你好，想问一下，你的意思是将nacos下的nacos-logback.xml放到服务中？在这个xml再加上业务的日志定义吗？

**Comment by liangyuanpeng** [comment]
看起来是和 #2605  重复的， Nacos只作为管理中心，至于配置项如何使用不应该在Nacos的责任当中。
