### ISSUE TITLE
Client heart beat package is too large

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#2123]
Consider more elegant client beat mechanism to reduce the size of package.

**Comment by lkxiaolou** [comment]
目前看来心跳的纬度为instance，服务多的时候心跳太频繁了，为什么不考虑合并心跳包发送？比如一台机器每5秒将本机所有存活的instance合并发送一次心跳，这样既减少发送次数，也可以合并心跳包，减少包大小
