### ISSUE TITLE
How can I change the login password?

### ISSUE THREAD

**Issue by LQBing** [alibaba/nacos#2125]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
I try to change the default user/password nacos/nacos, default password is so week. But I can not find any where to change them. I just find some solution like write a program to generate the encoding password string and insert the sql record by myself. Why do not you provide an UI to do it?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
UI is already provided in the latest version:

![image](https://user-images.githubusercontent.com/4593375/69860327-f1f3b680-12d0-11ea-8aca-a31b6a0e2c33.png)
