### ISSUE TITLE
部署到EDAS上每秒都会有com.alibaba.nacos.client.naming.updater的日志

### ISSUE THREAD

**Issue by yuhan0501** [alibaba/nacos#2126]
会打印类似下面的日志，如果服务找不到会打印eror的，如果有服务会有INFO的日志，为何这个日志这么频繁，而且是每个服务都会有一条？是哪里设置有问题吗？

17:23:40.498 [com.alibaba.nacos.client.naming.updater] traceId:[] ERROR com.alibaba.nacos.client.naming - [NA] failed to update serviceName: DEFAULT_GROUP@@providers:com.gigrt.midend.product.intf.hotel.service.HotelOperaCodeService:1.0.0:

**Comment by nkorange** [comment]
https://nacos.io/zh-cn/docs/faq.html#3.17
