### ISSUE TITLE
dom not found exception

### ISSUE THREAD

**Issue by bnrmaster** [alibaba/nacos#2136]
### I blocked by the same exception  mentioned in bug  #2083 
This should be caused by the mismatched server and client version,
my nacos discovery client is 2.1.1 but the server version is 0.9.0.
My problem solved after updating the server to 1.1.4
I downloaded the uncorrect version server because the link of the Nacos Server in Quick Start ( https://nacos.io/en-us/docs/quick-start.html) in English version manual is still 0.9.0.

**Comment by nkorange** [comment]
fixed
