### ISSUE TITLE
使用prometheus监控nacos但是grafana上面不展示数据

### ISSUE THREAD

**Issue by firehalt** [alibaba/nacos#2138]
.根据官方提供的教程模板，但是grafana上面不显示数据https://nacos.io/zh-cn/docs/monitor-guide.html

问题：prometheus和grafana为同一台服务器，prometheus上面有数据，在grafana导入模板后无数据，错误提示Templating init failed Datasource named prometheus was not found，我知不知道在代码改哪里，但是grafana确定已经添加了prometheus Datasource

**Comment by 92376** [comment]
我猜你是prometheus首字母大写了

**Comment by firehalt** [comment]
@92376 是grafana添加数据源的时候prometheus首字母大写了，我改回来了，还是没有数据展示，但是instance里面可以看见nacos服务器的信息，其他的没有数据展示

**Comment by 92376** [comment]
@firehalt 你看看prometheus里面有没有对应的值

**Comment by yueyemisi** [comment]
官方自己的Grafana都不显示数据了[http://monitor.nacos.io/d/Bz_QALEiz1/nacos?orgId=1](http://monitor.nacos.io/d/Bz_QALEiz1/nacos?orgId=1)，

**Comment by 92376** [comment]
![image](https://user-images.githubusercontent.com/27845606/71776212-8a641180-2fc8-11ea-9cf2-487b4abceb3b.png)
但是我的是有的 @yueyemisi

**Comment by ApheaTech** [comment]
> 我猜你是prometheus首字母大写了

牛啊，还真被说中了
