### ISSUE TITLE
sharedDataids自定义分组无效

### ISSUE THREAD

**Issue by Dhweicheng** [alibaba/nacos#2140]
![123](https://user-images.githubusercontent.com/13899021/70033335-2f668580-15ea-11ea-9559-88a53d8e7ce6.png)
`			loadNacosDataIfPresent(compositePropertySource, dataId, "DEFAULT_GROUP",
					fileExtension, isRefreshable);`
不知道这个编码的用意是什么，只能通过 ext-config来配置

**Comment by nkorange** [comment]
没在Nacos工程里看到这段代码，请把代码链接贴一下

**Comment by rushsky518** [comment]
this is  spring cloud alibaba

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1294](https://github.com/alibaba/spring-cloud-alibaba/issues/1294) via [**ZenHub**](https://www.zenhub.com/)
