### ISSUE TITLE
register error

### ISSUE THREAD

**Issue by meacial** [alibaba/nacos#2141]
**nacos-server-0.9.0**

c.a.c.n.registry.NacosServiceRegistry    : nacos registry, produce-service register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.56.1:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='produce-service', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.56.1', networkInterface='', port=8089, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}},v

_dom name can only have these characters: 0-9a-zA-Z.:_-; current: DEFAULT_GROUP@@produce-service_

**Comment by meacial** [comment]
服务注册失败，查看error为，serverName中包含了 @@ 字符，但是字符又是 NamingUtils中拼出来的

**Comment by nkorange** [comment]
你的服务名有一个下划线
