### ISSUE TITLE
Consult nacos data persistence issues.

### ISSUE THREAD

**Issue by x22x22** [alibaba/nacos#2143]
## Consult nacos data persistence issues

请问在生产的K8S环境中, nacos需要支持集群和自动扩缩容功能, 然后nacos使用的mysql做了数据持久化, 那么nacos本身的pos还需要做持久化吗?谢谢!

In the production K8S environment, nacos needs to support clustering and automatic expansion and reduction functions, and then mysql used by nacos does data persistence, so does the pos of nacos itself need to be persisted?thank you!

**Comment by nkorange** [comment]
最好加上{nacos.home}/data数据缓目录及{nacos.home}/logs日志目录。

**Comment by handong0123** [comment]
> 最好加上{nacos.home}/data数据缓目录及{nacos.home}/logs日志目录。

我想问一下 如果没有nfs 使用本地磁盘挂载 集群会有什么问题吗
