### ISSUE TITLE
支持自定义namespace id

### ISSUE THREAD

**Issue by KeRan213539** [alibaba/nacos#2145]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
配制中心和注册中心,客户端需要指定namespace的时候,只能使用namespace id.
但是namespace id是在创建namespace自动生成的,这样使用起来很不方便,例如多个开发人员,每个人在本地都有一套自己的nacos,这样每个人都得修改自己的本地配制,还不能提交,如果有在配制中增加了什么不得不提交的时候,所有人又得修改一次自己本地的配制.
希望能提供自定义namesapce id的功能,这样所有人的本地配制都可以使用相同的namcespace id

**Comment by KeRan213539** [comment]
这个功能我来完成
# 功能设计:
## 前端
1. 新增命名空间的表单中增加一个namespace id选项,用户可以自己输入,不输入则使用之前的生成规则
2. 对应下面的服务端内容中的第3点的自动检查和提示
## 服务端
1. 新增保存命名空间接口增加namespace id参数,并检查该参数是否有值
1.1. 如果有值,则检查该值是否符合规则(只能数字和字母和-)
1.2. 由于namespace id具有唯一性,需要检查是否已有相同的 namespace id存在,并做对应提示
2. 如果没有值,则按原来逻辑处理
3. 为增加用户体验,需要增加一个检查namespace id是否符合规则和是否存在的接口

**Comment by nkorange** [comment]
This issue will be tracked in #1606
