### ISSUE TITLE
NacosDiscoveryProperties.init()方法截取serverAddr错误

### ISSUE THREAD

**Issue by hexiangtao** [alibaba/nacos#2146]
# Issue Description 
NacosDiscoveryProperties类的init()方法有这样一段代码

```java
	if (serverAddr.lastIndexOf("/") != -1) {
			serverAddr = serverAddr.substring(0, serverAddr.length() - 1);
		}
```
当serverAddr格式为https://hostname时，比如https://dev.nacos.xxx.com,这里直接把serverAddr最后一个字符给去掉了。 变成https://dev.nacos.xx.co

Type: bug report

###  期望
 if (serverAddr.lastIndexOf("/") != -1)  应该判断字符串是否以"/"截结尾，而不是只判断是否包含"/"

###   代码点
```java
	if (serverAddr.lastIndexOf("/") != -1) {
			serverAddr = serverAddr.substring(0, serverAddr.length() - 1);
		}
```

### 版本
spirng-cloud-alibaba-nacos-discovery-2.1.0.RELEASE

**Comment by fangjian0423** [comment]
2.1.1.RELEASE 已修复: https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java#L198
