### ISSUE TITLE
spring cloud gateway 整合nacos，监听器无法获取到配置内容

### ISSUE THREAD

**Issue by watilion** [alibaba/nacos#2150]
想实现spring cloud gateway从nacos动态获取路由配置信息，使用configService.getConfig(dataId, group, 5000)使能获取到配置信息，但是注册监听器未进入重写的receiveConfigInfo方法
spring-cloud.version:Greenwich.SR2
spring-cloud-alibaba.version:2.1.1.RELEASE
spring-boot.version:2.1.6.RELEASE
nacos-server.version:1.1.4

            Properties properties = new Properties();
            properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
            properties.put(PropertyKeyConst.NAMESPACE, namespace);
            ConfigService configService = NacosFactory.createConfigService(properties);
            String content = configService.getConfig(dataId, group, 5000);
            log.info("获取nacos初始化配置，{}",content);
            configService.addListener(dataId, group, new Listener(){
                @Override
                public Executor getExecutor() {
                    return null;
                }
                @Override
                public void receiveConfigInfo(String configInfo) {
                    log.info("监听器获取的nacos动态路由为：{}",configInfo);
                    List<RouteDefinition> gatewayRouteDefinition = JSONObject.parseArray(configInfo,RouteDefinition.class);
                    for (RouteDefinition routeDefinition : gatewayRouteDefinition) {
                        update(routeDefinition);
                    }
                }
            });

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
但是同样的写法使用孵化器版本0.9.0.RELEASE，是能够进入receiveConfigInfo方法的

**Comment by nkorange** [comment]
这个问题麻烦提交到spring-cloud-alibaba

**Comment by watilion** [comment]
@nkorange 请问现在是修改为项目启动注册监听器时不进入receiveConfigInfo方法，后续配置变更了才会进入
