### ISSUE TITLE
How to get all config in nacos.

### ISSUE THREAD

**Issue by sunbufu** [alibaba/nacos#2157]
Hi Nacos community. 
I am working on that implement Nacos config center for [Apache ShardingSphere](https://github.com/apache/incubator-shardingsphere). But I am blocked, cause I need all config properties to build config node tree. I have no idea about how to get all config properties. Can you help me ? 
Waiting for your replay :)

==============================

Nacos 社区的朋友们，你们好。
我想集成 Nacos 作为 Apache ShardingSphere 的一种注册中心实现，但是我不知道该怎么获取全部的配置，你们可以帮助我吗？
期待你们的回复 :)

**Comment by dongzl** [comment]
the same problem to this issue~

**Comment by nkorange** [comment]
可以参考Nacos控制台页面上全量配置的查询，可以按分页获取：
https://github.com/alibaba/nacos/blob/7fab1e1d4c6ab39575cd3a80cec965280120c383/config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java#L309

**Comment by dongzl** [comment]
@nkorange , Thanks for your reply!

I read the source code about ConfigController, it read config info from nacos‘s DB with SQL directly!

Does nacos have open api to get all config info? Thanks!

![image](https://user-images.githubusercontent.com/5917359/70587302-8ed51e80-1c04-11ea-816f-21bb30cda2ed.png)
