### ISSUE TITLE
Chrome got blank page when access nacos console.

### ISSUE THREAD

**Issue by yinxuan1128** [alibaba/nacos#2161]
## Issue Description

Type: *bug report* 

### How to reproduce it (as minimally and precisely as possible)

1. can not access nacos console in chrome,but is success in Edge!
In Chrome I got a blank page.The console output is below:

### Tell us your environment

Chrome:78.0.3904.108

![ZW46UWPO3NM798EWV R$$M](https://user-images.githubusercontent.com/29925036/70490799-55d07780-1b3a-11ea-9815-fefd7a67a862.png)

**Comment by nkorange** [comment]
Clear browser cache and retry. Chrome works fine for me.

**Comment by yinxuan1128** [comment]
I've cleared the browser's chache.But it don't work!
