### ISSUE TITLE
支持同一个 namesapce 中的克隆

### ISSUE THREAD

**Issue by KeRan213539** [alibaba/nacos#2171]
相同 namesapce 中的克隆支持,判断如果是相同namespace弹出对话框修改data id, group信息

**Comment by slieer** [comment]
非常有用的issue.

**Comment by KeRan213539** [comment]
> 非常有用的issue.

已经PR了,坐等合并 o(∩_∩)o

**Comment by hello-zhengzq** [comment]
借楼问个管理台导入导出克隆的问题，目前这个导入功能是只面向在管理台导出的文件的是吗？也看不见导出文件是什么格式的内容。平时项目里用的yml和properties这种文件，如果要导入的话是否还是只能自己调运维api导？

**Comment by KeRan213539** [comment]
@hello-zhengzq 导出的格式为ZIP文件,你可以导出一个看看. 这个导入导出支持与阿里云ACM互导. 原则上来说是从控制台导出再导入到另一个实例或者namespace中,不过自己按照ZIP里的格式弄一个ZIP文件也可以导入.导出的文件中不包含namespace信息,所以可以导入到同实例的不同namespace中. zip文件中的文件夹是配制的group

**Comment by hello-zhengzq** [comment]
> 
> 
> @hello-zhengzq 导出的格式为ZIP文件,你可以导出一个看看. 这个导入导出支持与阿里云ACM互导. 原则上来说是从控制台导出再导入到另一个实例或者namespace中,不过自己按照ZIP里的格式弄一个ZIP文件也可以导入.导出的文件中不包含namespace信息,所以可以导入到同实例的不同namespace中. zip文件中的文件夹是配制的group

看见了，非常感谢。导出的文件没有后缀，想复杂了，还以为有什么特殊处理加密啥的。

**Comment by KeRan213539** [comment]
@hello-zhengzq 额,有后缀的呀. 你用的什么浏览器,nacos什么版本?我测试看看

**Comment by hello-zhengzq** [comment]
> 
> 
> @hello-zhengzq 额,有后缀的呀. 你用的什么浏览器,nacos什么版本?我测试看看

Σ(⊙▽⊙"a！firefox，1.1.4的后台，这个没理由吧...附我的导出图。另外现在导入的sdk竟然不支持传入配置文件的type，open-api是有支持，弄的我们本地自己封装了个...这个是个小问题，好像也没人关注
![图片](https://user-images.githubusercontent.com/51627771/71811663-42b8b500-30b0-11ea-8c41-20e0b449adf8.png)

**Comment by KeRan213539** [comment]
@hello-zhengzq 为了兼容阿里云ACM,所以导出的文件中没有配制的type信息,目前是根据配制文件的扩展名做了简单的文件type判断,如果配制文件没有扩展名,或者不是标准扩展名的话就默认成其他了.
firefox 确实没有扩展名, 应该是文件名中带空格造成的,导出的文件名中是完整的有时分秒的时间,但是看图里的文件名不完整,时间用了 yyyy-MM-dd HH:mm:ss格式.  
导出的文件名格式之前已经修改并PR了,下个版本应该就会有了

**Comment by hello-zhengzq** [comment]
> 了简单的文件type

收到，要是有默认匹配type的话，那刚好我的是yaml的格式，看数据库存type是yaml，我dataid配的和实际文件的扩展名是yml，这个应该也是代码目前没匹配yml？如果是没这个是否也可以PR一下

**Comment by KeRan213539** [comment]
@hello-zhengzq 我这边1.1.4导入没问题,我的daitaId是  demo-service-dev.yml
