### ISSUE TITLE
Zuul路由问题

### ISSUE THREAD

**Issue by wekin** [alibaba/nacos#2174]
我使用zuul作为路由功能, 如果zuul服务先启动, 后面的服务后启动是无法导航的, 只有比zuul先启动的服务才会正确导航, 所以你们是不是只在服务启动的时候才会去获取服务列表,还是我没有开启什么设置?

**Comment by rushsky518** [comment]
可以详细描述下问题吗

**Comment by linqijin** [comment]
你好，问题最终解决了么？我这边貌似也是这样。
