### ISSUE TITLE
Nacos启动可否不要把读取到的配置文件输出到控制台？

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/nacos#2178]
出现问题的版本是
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-nacos-config</artifactId>
                <version>2.1.1.RELEASE</version>
            </dependency>
我使用spring boot版的nacos是没有这个问题的

日志如下：
2019-12-14 00:39:04.009  INFO 1896 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Loading nacos data, dataId: 'xxx-xxx-xxxxx.yml', group: 'xxx', data: server:
  port: 9010
  servlet:
    context-path: /xxx-xxxx-xxxxx

spring:
  profiles:
    active: dev

如果待发布版本已经处理好了，麻烦发布一下maven。谢谢

**Comment by mimajiushi** [comment]
可以单独设置NacosPropertySourceBuilder 的日志输出级别    
yml配置如：    
logging:
  file:
    max-size: 10MB
    max-history: 20
  level:
    com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder: debug

**Comment by zhuyouzhufu** [comment]
谢谢前辈的提醒，不过还是建议官方把这个日志默认不要输出吧。既然已经把配置文件放到了配置中心(用户的本意肯定是安全为重)。如果考虑性能的话直接放本地不是更好吗。

**Comment by zhuyouzhufu** [comment]
谢谢前辈的提醒，不过还是建议官方把这个日志默认不要输出吧。既然已经把配置文件放到了配置中心(用户的本意肯定是安全为重)。如果考虑性能的话直接放本地不是更好吗。

**Comment by zhuyouzhufu** [comment]
谢谢前辈的提醒，不过还是建议官方把这个日志默认不要输出吧。既然已经把配置文件放到了配置中心(用户的本意肯定是安全为重)。如果考虑性能的话直接放本地不是更好吗。

**Comment by zhuyouzhufu** [comment]
谢谢前辈的提醒，不过还是建议官方把这个日志默认不要输出吧。既然已经把配置文件放到了配置中心(用户的本意肯定是安全为重)。如果考虑性能的话直接放本地不是更好吗。

**Comment by zhuyouzhufu** [comment]
谢谢前辈的提醒，不过还是建议官方把这个日志默认不要输出吧。既然已经把配置文件放到了配置中心(用户的本意肯定是安全为重)。如果考虑性能的话直接放本地不是更好吗。

**Comment by zhuyouzhufu** [comment]
谢谢前辈的提醒，不过还是建议官方把这个日志默认不要输出吧。既然已经把配置文件放到了配置中心(用户的本意肯定是安全为重)。如果考虑性能的话直接放本地不是更好吗。

**Comment by mimajiushi** [comment]
我倒觉得配置中心并不是为了配置的读安全性，更多的应该是线上动态刷新配置、统一管理配置、保护写安全(如issue #1105 中讨论的权限控制)，配置中心的配置基本是映射到java类中的，即便不输出log，安全性也没什么差别。不过具体为什么输出这条log我也不是很清楚，详细还请问@官方。

**Comment by rushsky518** [comment]
nacos 的配置文件一共有 3 份，mysql，nacos server disk，nacos client disk，为了安全是不成立的

**Comment by nkorange** [comment]
这个是Spring Cloud Alibaba客户端输出的，可以咨询下Spring Cloud Alibaba项目组
