### ISSUE TITLE
通过java sdk 注册服务时填写组名,界面出现多个服务

### ISSUE THREAD

**Issue by 419861036** [alibaba/nacos#2182]
1、通过java sdk 注册服务时填写组名,界面出现多个服务，而且只有DEFAULT_GROUP 这个组的服务可以上下线，自定义组名的服务不受控制。
2、通过sdk订阅服务后订阅界面看不到消费者

**Comment by nkorange** [comment]
1. 能否截图看看
2. 是否用的Dubbo，这可能需要找Dubbo项目组排查下

**Comment by 419861036** [comment]
springboot+dubbo(rest)  但是这个服务是我自定义的服务用于gateway网关服务发现 ，服务是通过nacos的sdk注册上去的，只有DEFAULT_GROUP 能正常工作

**Comment by nkorange** [comment]
@419861036 你用nacos-sdk直接注册的吗？

**Comment by 419861036** [comment]
嗯

**Comment by 419861036** [comment]
![image](https://user-images.githubusercontent.com/20715546/71878723-51ae6e80-3167-11ea-8e28-9e25f06f18db.png)
而且为什么 界面连个模糊查询都不支持

**Comment by nkorange** [comment]
@419861036 dataId加*可以模糊搜索。

你在控制台点击服务下线有报错吗？

**Comment by 419861036** [comment]
控制台下线不报错 ，下了刷新发现没有下线成功
