### ISSUE TITLE
SpringBoot 1.5.12.RELEASE + SpringCloud Edgware.SR3 是否能使用Nacos注册中心？

### ISSUE THREAD

**Issue by staticLin** [alibaba/nacos#2183]
试了好多个springboot版本，发现只有最低2.0.x的springboot+F版的springcloud才可以使用Nacos注册中心，版本说明中的版本没有这么低的对应版本说明。
如果知道版本信息，劳烦告知对应版本，万分感谢！

**Comment by staticLin** [comment]
使用了spring-cloud-alibaba 的 0.1.2.RELEASE版本可以使用了，但是版本说明中springboot 1.5.x 不是应该对应spring-cloud-alibaba 1.x 的版本吗？好像Maven找不到这个版本的依赖。请问一下0.1.2.RELEASE 孵化器版本的spring-cloud-alibaba 可以在生产上放心用吗？

**Comment by nkorange** [comment]
这个问题可以在spring-cloud-alibaba仓库咨询下

**Comment by jiaoyilun** [comment]
> 使用了spring-cloud-alibaba 的 0.1.2.RELEASE版本可以使用了，但是版本说明中springboot 1.5.x 不是应该对应spring-cloud-alibaba 1.x 的版本吗？好像Maven找不到这个版本的依赖。请问一下0.1.2.RELEASE 孵化器版本的spring-cloud-alibaba 可以在生产上放心用吗？

请问你最后怎么解决的，我也是用的Edgware版本，业务太多，不好升级
