### ISSUE TITLE
nacos 1.1.4 删除配置ui展示列表为空

### ISSUE THREAD

**Issue by WG-Roy** [alibaba/nacos#2184]
## Issue Description

Tnacos 1.1.4 删除配置

### Describe what happened (or what feature you want)

![image](https://user-images.githubusercontent.com/48314438/70994673-b434c180-2109-11ea-9835-20e7e331a04a.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by WG-Roy** [comment]
@i will solve it@

**Comment by nkorange** [comment]
Fixed in #2191
