### ISSUE TITLE
nacos-discovery会导致springboot的application.properties失效

### ISSUE THREAD

**Issue by bugCats** [alibaba/nacos#2198]
使用nacos作为注册中心，springboot项目为客户端，引入nacos-discovery后，springboot的application.properties会失效，文件里面的变量使用@Value获取不到。

springboot版本为：2.1.7.RELEASE
nacos-discovery版本为：com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.1.0.RELEASE

springboot配置文件目录结构如下：

resources
&nbsp;&nbsp;│
&nbsp;&nbsp;├ config
&nbsp;&nbsp;│   &nbsp;&nbsp;├ application-dev.properties
&nbsp;&nbsp;│   &nbsp;&nbsp;├ application-test.properties
&nbsp;&nbsp;│  &nbsp;&nbsp;└ application-prod.properties
&nbsp;&nbsp;│
&nbsp;&nbsp;└ application.properties

config包中，放置的是与环境有关的参数（数据库链接、缓存链接等）。
application.properties是与环境无关的参数（应用名称、端口号等），再使用`spring.profiles.active=xxx`引入对应环境的配置文件。

一旦引入com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.1.0.RELEASE jar之后，application.properties文件的`spring.profiles.active`生效，但是其他的参数便无法获取到了。

**Comment by bugCats** [comment]
将application换成bootstrap后没有问题。
还以为仅使用nacos config时，才需要将application修改成bootstrap (ಥ_ಥ)

**Comment by PWA2000** [comment]
我用yml配置文件没有发现这个问题哎.

**Comment by draco1023** [comment]
问题确实是存在的，原因在于nacos-api/nacos-client/...等jar包中都包含application.properties文件，Spring boot启动时如果classpath下存在多个application.properties，实际会加载哪一个是无法预知的，坏的情况下就会直接使用nacos-xxx里的，导致代码工程中的application.properties文件无法生效。

![image](https://user-images.githubusercontent.com/1821583/74088141-e4775b80-4acd-11ea-8912-56d78bf51624.png)

上图就是出现了坏的情况。如果代码中仅使用了yml文件配置或者使用优先级更高的bootstrap是没问题的，建议nacos系列打包时过滤掉application.properties文件。
