### ISSUE TITLE
nacos集群模式下修改配置报错

### ISSUE THREAD

**Issue by zzps** [alibaba/nacos#2200]
三节点集群控制台编辑配置的时候报错.报错如下：
org.springframework.transaction.TransactionSystemException: Could not commit JDBC transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'coocat-module-pay-DEFAULT_GROUP-17b936e8-54e7-43c9-b2ab-7aced014b857' for key 'uk_configinfo_datagrouptenant'

nacos版本：1.1.4
数据库：tidb3.0.7
系统：centos7.7
自己理解：看错误信息是我的编辑操作貌似变成了添加了操作造成唯一索引冲突

==========
我拉取了nacos源码，分析找出原因如下：
PersistService.class的insertOrUpdate方法中的逻辑是先插入数据，如果抛出的异常是DataIntegrityViolationException.class类型的异常则在捕获当中进行更新逻辑操作，而在我环境抛出的
是com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException异常，并没有被捕获，
导致如此

**Comment by nkorange** [comment]
Nacos目前只支持MySQL
