### ISSUE TITLE
auto discovery of nacos cluster instance

### ISSUE THREAD

**Issue by louchenhui** [alibaba/nacos#2201]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
我们想部署一套nacos集群，但是官方文档里边，提供了两种配置方法，一种是IP直接写在cluster.config里边，另一种是从一个接口里边获取列表，但是都不满足我们的需求。我们部署在公司的PaaS平台，IP和端口是动态映射的，所以是无法提前预知的。所以是否能提供一种方式能够实现nacos实例之间的相互发现，比如依赖zookeeper，这样虽然需要多部署一套zookeeper，但是在集群增减机器的时候可以很方便的扩展，同时也能够适合我们这样的环境。

We want to deploy a cluster of nacos, the official documentation provides two configuration methods, one is to write the IP directly in cluster.config, and the other is to get the list from an interface, but neither meets our needs . We deploy on the company's PaaS platform. IP and port are dynamically mapped, so it is impossible to predict in advance. So can you provide a way to realize mutual discovery between nacos instances, such as relying on zookeeper, so although an additional set of zookeeper needs to be deployed, it can be easily extended when the cluster is added or deleted, and it can also be suitable for environment like us.

### Describe what you expected to happen

auto discovery of nacos cluster instance

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

a paas platform  based on mesos and docker。

**Comment by nkorange** [comment]
在阿里集团内部，是支持你说的这种模式，开源没有开放这个功能，可以考虑后续支持。

**Comment by louch2** [comment]
> 在阿里集团内部，是支持你说的这种模式，开源没有开放这个功能，可以考虑后续支持。

请问大概什么时候能支持呢？是否可以提供下你们大致的思路？

**Comment by nkorange** [comment]
@louch2 可以参考这个文章：https://nacos.io/zh-cn/blog/address-server.html
