### ISSUE TITLE
spring+spring MVC不能进行自动热更新

### ISSUE THREAD

**Issue by lizhibo0914** [alibaba/nacos#2202]
<nacos:annotation-driven></nacos:annotation-driven>
    
    <nacos:global-properties server-addr="localhost:8848"/>
    
    <nacos:property-source data-id="application-dev.properties" auto-refreshed="true"/>
![image](https://user-images.githubusercontent.com/27732536/71172264-b417fb80-229a-11ea-9523-c887e955cae0.png)

**Comment by nkorange** [comment]
Which Nacos jar you are using?

**Comment by lizhibo0914** [comment]
<dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-spring-context</artifactId>
            <version>0.3.4</version>
        </dependency>

**Comment by lizhibo0914** [comment]
最新的0.3.4

**Comment by nkorange** [comment]
@chuntaojun 帮忙看下

**Comment by nkorange** [comment]
Moved to https://github.com/nacos-group/nacos-spring-project/issues/180

**Comment by chuntaojun** [comment]
got it

**Comment by chuntaojun** [comment]
存在配置优先级的
你可以去看environment是否有NacosPorpertySource这个对象，里面应该有你的配置信息

**Comment by rushsky518** [comment]
@lizhibo0914 你的问题还存在吗，nacos 部分的配置要放在 DispatcherServlet 的 xml 中

**Comment by chuntaojun** [comment]
> @lizhibo0914 你的问题还存在吗，nacos 部分的配置要放在 DispatcherServlet 的 xml 中

看样子应该是因为多个Context（父子Context）导致的问题

**Comment by jungleyoung** [comment]
> @lizhibo0914 你的问题还存在吗，nacos 部分的配置要放在 DispatcherServlet 的 xml 中

我也遇到了，确实如此。

**Comment by jungleyoung** [comment]
> @lizhibo0914 你的问题还存在吗，nacos 部分的配置要放在 DispatcherServlet 的 xml 中

在DispatcherServlet 的xml beans标签里加入xmlns:nacos="http://nacos.io/schema/nacos" http://nacos.io/schema/nacos http://nacos.io/schema/nacos.xsd 就可以热更新了。
