### ISSUE TITLE
NACOS 1.1.4 修改mysql8.0编译报错

### ISSUE THREAD

**Issue by xiaoqing0729** [alibaba/nacos#2205]
[INFO] --- jacoco-maven-plugin:0.7.8:prepare-agent-integration (default-prepare-agent-integration) @ nacos-naming ---
[INFO] failsafeArgLine set to -javaagent:E:\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.8\\org.jacoco.agent-0.7.8-runtime.jar=destfile=D:\\workspace_eclipse_hauto\\nacos\\naming\\target\\jacoco-it.exec
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (default) > :pmd @ nacos-naming >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ nacos-naming ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (default) < :pmd @ nacos-naming <<<
[INFO] 
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (default) @ nacos-naming ---
[INFO] PMD Failure: com.alibaba.nacos.naming.healthcheck.MysqlHealthCheckProcessor:76 Rule:ThreadPoolCreationRule Priority:1 手动创建线程池，效果会更好哦。.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Alibaba NACOS 1.1.4 1.1.4:
[INFO] 
[INFO] Alibaba NACOS 1.1.4 ................................ SUCCESS [  2.083 s]
[INFO] nacos-api 1.1.4 .................................... SUCCESS [  6.009 s]
[INFO] nacos-common 1.1.4 ................................. SUCCESS [  1.967 s]
[INFO] nacos-core 1.1.4 ................................... SUCCESS [  4.446 s]
[INFO] nacos-config 1.1.4 ................................. SUCCESS [ 26.887 s]
[INFO] nacos-cmdb 1.1.4 ................................... SUCCESS [  1.255 s]
[INFO] nacos-naming 1.1.4 ................................. FAILURE [ 25.022 s]
[INFO] nacos-address 1.1.4 ................................ SKIPPED
[INFO] nacos-client 1.1.4 ................................. SKIPPED
[INFO] nacos-test 1.1.4 ................................... SKIPPED
[INFO] nacos-example 1.1.4 ................................ SKIPPED
[INFO] nacos-istio 1.1.4 .................................. SKIPPED
[INFO] nacos-console 1.1.4 ................................ SKIPPED
[INFO] nacos-distribution 1.1.4 ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:08 min
[INFO] Finished at: 2019-12-20T10:46:54+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.8:check (default) on project nacos-naming: You have 1 PMD violation. For more details see: D:\workspace_eclipse_hauto\nacos\naming\target\pmd.xml -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nacos-naming

**Comment by nkorange** [comment]
你是否修改了代码？这个错误提示是违反了代码规范

**Comment by xiaoqing0729** [comment]
额，我用的开发工具是eclipse，只是按了一下ctrl + shift + o。。。
eclipse中的解释是，Ctrl+Shift+O作用是缺少的Import语句被加入，多余的Import语句被删除。
![image](https://user-images.githubusercontent.com/16095288/71235125-3acde680-2336-11ea-901a-2685de886057.png)

**Comment by xiaoqing0729** [comment]
我把代码还原，只修改那一行引用，可以编译了，谢谢
