### ISSUE TITLE
WEB UI Delete configuration interface display exception

### ISSUE THREAD

**Issue by kitsrc** [alibaba/nacos#2208]
## Issue Description
as shown in illustration
![image](https://user-images.githubusercontent.com/23493090/71334495-70aedd00-2579-11ea-83dd-0ac7e6609d21.png)

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
Same as #2184
