### ISSUE TITLE
WEB UI Paging switch problem, not available

### ISSUE THREAD

**Issue by kitsrc** [alibaba/nacos#2209]
## Issue Description
Paging switch problem, not available
as shown in illustration
分页组件不能正常使用
如图所示
![image](https://user-images.githubusercontent.com/23493090/71334633-eca92500-2579-11ea-9c0b-c029f1a76eb0.png)

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
已经在https://github.com/alibaba/nacos/pull/2147 修复
