### ISSUE TITLE
openAPI  feature requests  ,Support namespace parameters

### ISSUE THREAD

**Issue by kitsrc** [alibaba/nacos#2210]
## Issue Description
OpenAPI  发布配置 希望能支持 namespace 
![image](https://user-images.githubusercontent.com/23493090/71334839-bae48e00-257a-11ea-92b3-c5c7dde5cf55.png)

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
配置模块的namespace使用tenant参数即可
