### ISSUE TITLE
下线或者关停服务,gateway的负载还是会分到已经关掉的服务里

### ISSUE THREAD

**Issue by jackfruitran** [alibaba/nacos#2214]
网上有说是ribbon的定时任务更新可用服务列表导致的,无法及时更新可用服务,
这个是否有解决办法,
现在导致的问题是 无法无缝更新,需要去curl 接口先注销掉服务才行, 无法使用nacos的秒级切换

**Comment by nkorange** [comment]
这个问题麻烦提交到Spring Cloud Alibaba，应该是Ribbon的一些配置需要修改。

**Comment by Liesport758** [comment]
这个问题解决了？
