### ISSUE TITLE
注册好的服务心跳检测是否可以做成配置化的？

### ISSUE THREAD

**Issue by wushaohao** [alibaba/nacos#2215]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
你要配置什么参数？

**Comment by wushaohao** [comment]
比如说注册好的服务挂掉了,这个服务的心跳检测时间是否可配置?

**Comment by nkorange** [comment]
> 比如说注册好的服务挂掉了,这个服务的心跳检测时间是否可配置?

你是指心跳失效时间吗？

**Comment by wushaohao** [comment]
是的 检测服务正常的心跳时间

> 在 2019年12月27日，上午11:42，Peter Zhu <notifications@github.com> 写道：
> 
> 你是指心跳失效时间吗？

**Comment by wekin** [comment]
@nkorange 对于这种配置, 怎么没有相关文档呢

**Comment by nkorange** [comment]
@wekin 可以参考https://nacos.io/zh-cn/blog/nacos%201.1.0.html ，里面有个自定义心跳周期功能介绍
