### ISSUE TITLE
配置中心map属性删除某个key时，业务系统中实际并没有被删除

### ISSUE THREAD

**Issue by akaks** [alibaba/nacos#2218]
配置中心支持了配置listmap 属性（configuration），yaml文件如下
listMap: 
    l1: "New York Mets"
    l2: "Chicago Cubs"

当更新配置中心，将l2删除时，实际l2并不会被删除，而是会保留下来
#######################################################
The configuration center supports configuration listmap properties (configuration), and the yaml file is shown below
ListMap:
L1: "the New York Mets." "
L2: "Chicago Cubs." "
When the configuration is updated to remove l2, the actual l2 is not removed, but retained
#######################################################

## Issue Description

Type: bug report

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by akaks** [comment]
![image](https://user-images.githubusercontent.com/22937815/71437850-4baf9b00-272e-11ea-9fb1-745976b0643f.png)

目前我使用`ObjectUtils.cleanMapOrCollectionField(bean);`将bean清空，可以避免map的key删不掉的清空

**Comment by logan2013** [comment]
@akaks 请问怎么处理的，我也遇到这个问题

**Comment by mj19910923** [comment]
Nacos 2.2.0 还是有这个问题
