### ISSUE TITLE
nacos怎样获取在线的服务名称

### ISSUE THREAD

**Issue by xbcrh** [alibaba/nacos#2220]
刚开始使用nacos,使用NacosNamingService.getServicesOfServer()获取的服务是全部服务，包括了下线的服务。想要获取健康的服务，还得一个个去遍历服务有没有健康实例。看getServicesOfServer()底层是调用/nacos/v1/ns/service/list。参数除了num,size,selectorType没有其它。请教一下是否还有好的办法获取健康服务。

**Comment by nkorange** [comment]
可以参考https://github.com/alibaba/nacos/blob/45c333cf37e895ac3f1f8de7d0bfac975cb49f38/naming/src/main/java/com/alibaba/nacos/naming/controllers/CatalogController.java#L138

hasIpCount=true即意味着服务下有IP
