### ISSUE TITLE
The modified configuration does not take effect

### ISSUE THREAD

**Issue by jic138168** [alibaba/nacos#2221]
version:
nacos: 1.1.4
springboot: 2.1.10.RELEASE
spring-cloud: Greenwich.SR3
spring-cloud-alibaba: 2.1.1.RELEASE

issues:
Modify the nacos configuration,Nacos needs to be restarted to take effect.
Otherwise, the service pulls the previous configuration

**Comment by nkorange** [comment]
Please check the logs in ```{user.home}/logs/nacos/config.log``` if the configuration has been updated.
