### ISSUE TITLE
Nacos integrates Dubbo, GoS command offline does not take effect.

### ISSUE THREAD

**Issue by hyang214** [alibaba/nacos#2230]
## Issue Description

Type: *bug report*

### Describe what happened

I want to offline all dubbo providers for one specific spring boot application instance (ip + port).
So I use the GoS command 'offline' provided by Dubbo(http://dubbo.apache.org/en-us/docs/user/references/qos.html). But unfortunately, it does not work.

I read the log of nacos (naming-event.log), it seems that the nacos does not received the offline event.

### Describe what you expected to happen
One way to offline all dubbo providers of one java application instance.

### How to reproduce it (as minimally and precisely as possible)

1. telnet ip:3333 at the target ecs to enter GoS CLI.
2. call offline command

### Tell us your environment
Dubbo: 2.6.6
Nacos: 1.1.0
nacos-client: 1.0.0
dubbo-registry-ncaos: 0.0.1

### Anything else we need to know?
Nothing else.

**Comment by nkorange** [comment]
Redirect to https://github.com/apache/dubbo/issues/5544
