### ISSUE TITLE
怎样进行监听配置？

### ISSUE THREAD

**Issue by jinjie2088** [alibaba/nacos#2231]
怎么配置 监听配置，执行了接口没有看到什么反应，返回的信息是空，界面监听查询界面也为空。还有，应该看哪个日志？

![image](https://user-images.githubusercontent.com/4155721/71507274-f060e280-28be-11ea-8300-7308c4043bc9.png)

![image](https://user-images.githubusercontent.com/4155721/71507094-379aa380-28be-11ea-9195-a1846a17b1f6.png)

![image](https://user-images.githubusercontent.com/4155721/71507262-e5a64d80-28be-11ea-8c53-0409d5f7b1d1.png)

**Comment by nkorange** [comment]
请参考：
https://github.com/alibaba/nacos/blob/45c333cf37e895ac3f1f8de7d0bfac975cb49f38/client/src/main/java/com/alibaba/nacos/client/config/impl/ClientWorker.java#L480
