### ISSUE TITLE
Nacos配置中心会出现dubbo的服务

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/nacos#2236]
![image](https://user-images.githubusercontent.com/34908518/71541465-51a6b580-2994-11ea-819e-39df71528eba.png)
这个问题我觉得有点诧异，既然是配置中心怎么会冒出无关配置的dubbo服务信息
nacos控制台：配置列表
dataId：com.xxx.xxx.api.service.UserExpressDriverService:::consumer:user-consumer
Group：dubbo
点击编辑，信息如下：
{"side":"consumer","application":"user-consumer","release":"2.7.4.1","methods":"removeById,lambdaQuery,save,removeByMap,update,getObj,saveOrUpdateBatch,remove,listByIds,getBaseMapper,removeByIds,lambdaUpdate,updateBatchById,saveOrUpdate,listMaps,saveBatch,query,count,listObjs,list,getMap,updateById,pageMaps,listByMap,getById,getOne,page","lazy":"false","sticky":"false","dubbo":"2.0.2","interface":"com.user.api.service.UserExpressDriverService","qos.enable":"false"}

**Comment by khiker007** [comment]
你配置了dubbo的metadata-report了吧

**Comment by zhuyouzhufu** [comment]
# dubbo配置项如下
dubbo:
  registry:
    group: tmall
    protocol: nacos
    address: 127.0.0.1:8848?backup=127.0.0.2:8848
  application:
    name: tmall-user-producer
  provider:
    # dubbo协议端口（-1表示自增端口，从20880开始）
    port: -1
  config-center:
    group: xxx
    namespace: xxxxxxx-xxxx-xxxx-xxxx-d8b36c995544

**Comment by zhuyouzhufu** [comment]
# dubbo配置项如下
dubbo:
  registry:
    group: xxxxx
    protocol: nacos
    address: 127.0.0.1:8848?backup=127.0.0.1:8848
  application:
    name: xxxxx-user-producer
  provider:
    # dubbo协议端口（-1表示自增端口，从20880开始）
    port: -1
  config-center:
    group: xxxxx
    namespace: bc2f7f07-xxxx-xxxx-xxxx-d8b36c995544

**Comment by khiker007** [comment]
你用的2.7.5么，是不是新版本自动把元数据和注册数据分开了？我都是配置了dubbo.metadata-report.address才会在配置中心生成元数据信息，2.7.3以后的版本没有试过

**Comment by zhuyouzhufu** [comment]
谢谢，我用的是2.7.4.1.我现在排查下是不是因为版本的问题

**Comment by nkorange** [comment]
这个问题可以咨询下Dubbo的开发，可能是Dubbo的新特性导致。
