### ISSUE TITLE
com.alibaba.nacos.naming.misc.HttpClient#httpPutLarge is a little odd

### ISSUE THREAD

**Issue by rushsky518** [alibaba/nacos#2237]
![image](https://user-images.githubusercontent.com/20531420/71556433-8b9ab900-2a73-11ea-8f3e-94c9c2c1fb16.png)

![image](https://user-images.githubusercontent.com/20531420/71556467-12e82c80-2a74-11ea-851e-23509a933068.png)

byte[] content -> String
then
String -> byte[]

i suggest ByteArrayEntity. Can i change it?

**Comment by nkorange** [comment]
Welcome to contribute!

**Comment by rushsky518** [comment]
@i will solve it@
