### ISSUE TITLE
不用认证调用curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=HelloWorld" 发布配置，是不是有安全性问题？

### ISSUE THREAD

**Issue by 77321660** [alibaba/nacos#2238]
不用认证调用curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=HelloWorld" 发布配置，是不是有安全性问题？

**Comment by PWA2000** [comment]
可能开源版的做的比较简单，建议Nacos开发团队添加一个功能支持按照Group维度设置AppKey和密钥增加配置的安全性。

**Comment by 77321660** [comment]
在钉钉群问了nacos团队，下一版本1.2.0会解决这个问题

**Comment by nkorange** [comment]
参考 #1105
