### ISSUE TITLE
支持不同环境启用不同的profile

### ISSUE THREAD

**Issue by yabaowang** [alibaba/nacos#224]
springboot项目会默认启用properties(yml)文件的覆盖。
比如当active profile使用dev时， application-dev.yml 会覆盖application.yml里面的同名properties。
咱们nacos目前没有这个特性。如果使用 NacosPropertySources 配置多个properties文件，测试结果是，同名property不会产生覆盖，且无论修改同名property中的哪个，都会推送到客户端进行更新，容易造成误解。

能否做成 common配置(application.yml)下，分profile(application-dev.yml)启用不同的差异化配置呢？

**Comment by yabaowang** [comment]
springboot项目会默认启用properties(yml)文件的覆盖。
比如当active profile使用dev时， application-dev.yml 会覆盖application.yml里面的同名properties。
咱们nacos目前没有这个特性。如果使用 NacosPropertySources 配置多个properties文件，测试结果是，同名property不会产生覆盖，且无论修改同名property中的哪个，都会推送到客户端进行更新，容易造成误解。

能否做成 common配置(application.yml)下，分profile(application-dev.yml)启用不同的差异化配置呢？

**Comment by pguo65535** [comment]
@yabaowang  一个非常好的建议

**Comment by pguo65535** [comment]
@mercyblitz  @hxy1991 对于spring 生态profile的支持考虑一下在下个版本支持一下，看看profile是映射到namespace还是映射到group

**Comment by KomachiSion** [comment]
This issue is not nacos' problem.
