### ISSUE TITLE
If create config properties in other namespace. This config will delete error. The response code is 401.

### ISSUE THREAD

**Issue by xcrod** [alibaba/nacos#2240]
## Issue Description
I create a config properties in other namespace. 
Then i want to edit this config and try to save.
But is error. The response code return 401.

我创建了一个配置文件在我创建的命名空间中，然后我尝试去修改这个配置，保存之后系统提示错误，返回一个401状态码，而且无法删除，删除的请求401，并伴随着登录跳转。

 Nacos Version: 1.1.4

**Comment by xcrod** [comment]
使用的mysql 连接方式，默认分组的配置操作全部正常，其他命名空间分组的配置就没有权限删除。

**Comment by nkorange** [comment]
是用的release里面的安装包吗？

**Comment by xcrod** [comment]
> 是用的release里面的安装包吗？

不好意思，应该是我这边的安装问题，重新搭建环境之后好了。
