### ISSUE TITLE
nacos1.1.4 and mysql8.0.18

### ISSUE THREAD

**Issue by sagittar** [alibaba/nacos#2242]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/7836009/71607611-cd337d00-2bb5-11ea-9cf5-30a26062bc6d.png)

![image](https://user-images.githubusercontent.com/7836009/71607602-b9881680-2bb5-11ea-8a16-c55bddc9caf4.png)

![image](https://user-images.githubusercontent.com/7836009/71607618-df152000-2bb5-11ea-9c0f-105dae959f55.png)

![image](https://user-images.githubusercontent.com/7836009/71607634-f7853a80-2bb5-11ea-881a-99e2919e1798.png)

### Describe what you expected to happen
The same configuration, the laptop at home can be started yesterday, but not at the company today

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
看报错好像是mysql的配置没有读取到，看下和本机的配置有什么区别

**Comment by sagittar** [comment]
> 看报错好像是mysql的配置没有读取到，看下和本机的配置有什么区别

驱动程序和服务器不匹配
求人不如求己

**Comment by paderlol** [comment]
要把mysql8的驱动放在plugins mysql的目录下

**Comment by sagittar** [comment]
> 要把mysql8的驱动放在plugins mysql的目录下

哪个目录

**Comment by paderlol** [comment]
{nacos.home}/plugins/mysql/

**Comment by sagittar** [comment]
替换target/jar好了。
