### ISSUE TITLE
Log files are not displayed completely, when running nacos server in idea on windows

### ISSUE THREAD

**Issue by rushsky518** [alibaba/nacos#2245]
Configuration in " /resources/META-INF/logback/nacos.xml" file may have a error:
<include resource="META-INF/logback/nacos-included.xml"/>

Maybe only one of
nacos/naming/src/main/resources/META-INF/logback/nacos-included.xml
and
config/src/main/resources/META-INF/logback/nacos-included.xml
will work!

I can solve it.

**Comment by nkorange** [comment]
Welcome to solve it.

**Comment by rushsky518** [comment]
@i will solve it@
