### ISSUE TITLE
How to use Nacos as the configuration center and how to implement it?

### ISSUE THREAD

**Issue by jovenwang** [alibaba/nacos#2249]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jovenwang** [comment]
@ConditionalOnProperty(name = DataDruidConfig.datasource_druid_config_enabled,  matchIfMissing = true) @ConfigurationProperties public class DataSourceAutoConfig implements DataDruidConfig, EnvironmentAware, BeanDefinitionRegistryPostProcessor,ApplicationContextAware{
}
How to use Nacos as the configuration center and how to implement it?

**Comment by nkorange** [comment]
Not quite understand your need, please refer to https://nacos.io/zh-cn/docs/what-is-nacos.html for how to use Nacos.
