### ISSUE TITLE
There is a nacos-client 3.0 log problem.

### ISSUE THREAD

**Issue by TsingLiang** [alibaba/nacos#225]
java.lang.ClassNotFoundException: org.apache.logging.log4j.core.Logger
Then, I add maven dependency
<dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.7</version>
        </dependency>

**Comment by pguo65535** [comment]
would you please attach your pom.xml here? thanks.
