### ISSUE TITLE
NamingService无法注入的问题

### ISSUE THREAD

**Issue by ghyaauoo** [alibaba/nacos#2250]
springcloud nacos在使用@NacosInjected注入namingService的时候报空指针异常，无法注入。使用的版本如下：
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
	<version>0.9.0.RELEASE</version>
</dependency>
代码如下：
![image](https://user-images.githubusercontent.com/28587506/71666179-daf62780-2d9a-11ea-8750-86dedc2aa793.png)

**Comment by nkorange** [comment]
这个问题请提交到Spring Cloud Alibaba
