### ISSUE TITLE
IDEA can't recognize "@NacosValue" and so the value is regarded as "never assigned"

### ISSUE THREAD

**Issue by nangergong** [alibaba/nacos#2251]
![企业微信截图_4da5fb68-f49b-4cdf-85e1-f21b81e155f5](https://user-images.githubusercontent.com/6941690/71667356-b6507e80-2d9f-11ea-8f54-5993405380a7.png)

as shown above, IDEA can't recognize "@NacosValue" and so the value is regarded as "never assigned", how to deal with this?

**Comment by nkorange** [comment]
What's the problem with this?

**Comment by g5niusx** [comment]
> What's the problem with this?

这个功能应该是 idea 商业版的 `spring boot` plugin 提供的，这个plugin的源码应该是没有公开的，它属于idea商业版自带的插件，目前应该是解决不了。或者是让idea官方做支持。😄
![image](https://user-images.githubusercontent.com/42465572/71768200-f0ac4e00-2f4e-11ea-934f-fe075d1bc7ff.png)

**Comment by paderlol** [comment]
It looks like a code prediction and will not break the application. If you have to eliminate this check, u can disable it by the menu of inspections.
