### ISSUE TITLE
注册中心客户端能否增加配置，使得服务仅获取其他服务信息，但不注册。

### ISSUE THREAD

**Issue by jauadoc** [alibaba/nacos#2253]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
nacos作为注册中心使用时，如果因为网络环境限制，开发环境和测试环境需要共用一个nacos，本地启动了服务后会在nacos中注册，这样会导致远程无法访问注册的本地服务。

### Describe what you expected to happen
希望注册中心客户端中，增加配置项来控制是否注册当前服务

**Comment by nkorange** [comment]
这个注册是服务框架的行为，可以咨询相应的服务框架是否支持。
