### ISSUE TITLE
nacos support oracle persistent？If support？how to do？

### ISSUE THREAD

**Issue by koalas1105** [alibaba/nacos#2255]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

Does nacos 1.1.4 support oracle persistent？If support？How to do？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.1.4

**Comment by nkorange** [comment]
Nacos doesn't support Oracle.
