### ISSUE TITLE
readme file quick start wrong

### ISSUE THREAD

**Issue by yiyan1992** [alibaba/nacos#2257]
![批注 2020-01-05 204958](https://user-images.githubusercontent.com/15227616/71780389-1728c280-2ffd-11ea-89f6-062e0aa5e702.png)

![批注 2020-01-05 204957](https://user-images.githubusercontent.com/15227616/71780380-f8c2c700-2ffc-11ea-8f9d-d9a4da76a663.png)

in ubuntu18 use sh to set standalone is wrong 
should  use  bash instead of sh

**Comment by nkorange** [comment]
Moved to https://github.com/nacos-group/nacos-group.github.io/issues/83
