### ISSUE TITLE
How can nacos refresh logging behaviors, like refreshing logback-spring.xml?

### ISSUE THREAD

**Issue by nangergong** [alibaba/nacos#2259]
修改日志级别有两种方式，一种是配置文件添加如下，这种可以通过nacos修改，但是好像只有启动时生效，之后修改也不起作用了

`
logging:
  level:
    com.xx.mapper: debug
`
一种是logback-spring.xml添加如下，这种则好像不能通过nacos改

`
        <logger name="com.xxx.mapper">
            <level value="DEBUG"/>
        </logger>
`
那么如何让程序运行起来时更新日志的级别呢？

Sometimes, we want to add some debug log, like enabling mapper logging level as debug, there are two ways to do so
1) add the following to config file (.yaml or .properties)
`
logging:
  level:
    com.xx.mapper: debug
`
this can be done via nacos, but it seems to me the code block can only take effect for once on bootstrap, adding/modifying them won't work

2) add the following to logback-spring.xml
`
        <logger name="com.xxx.mapper">
            <level value="DEBUG"/>
        </logger>
`

but it seems to me that nacos can't refresh logback-spring.xml?

**Comment by chuntaojun** [comment]
这个运行时也可以修改日志级别的，具体看这个：https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-spring-boot-samples/nacos-config-sample/src/main/java/com/alibaba/boot/nacos/sample/PrintLogger.java

**Comment by esolve** [comment]
> 这个运行时也可以修改日志级别的，具体看这个：https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-spring-boot-samples/nacos-config-sample/src/main/java/com/alibaba/boot/nacos/sample/PrintLogger.java

spring-cloud上用
版本1.1.3
这个@NacosConfigListener 好像不起作用啊

**Comment by chuntaojun** [comment]
cloud暂时不支持nacos的注解

发自我的iPhone

在 2020年4月5日，02:56，esolve <notifications@github.com> 写道：

﻿

这个运行时也可以修改日志级别的，具体看这个：https://github.com/nacos-group/nacos-spring-boot-project/blob/master/nacos-spring-boot-samples/nacos-config-sample/src/main/java/com/alibaba/boot/nacos/sample/PrintLogger.java

spring-cloud上用
版本1.1.3
这个@NacosConfigListener 好像不起作用啊
