### ISSUE TITLE
如何开启全局autoRefresh, how to enable autoRefresh globally?

### ISSUE THREAD

**Issue by nangergong** [alibaba/nacos#2260]
我看目前好像有两种方式来开启全局autoRefresh

1）
@NacosConfigurationProperties(dataId = "x x x", autoRefreshed = true)

2）
在配置文件配置
nacos.config.auto-refreshed=true

对于方法1，必须要要写dataId，而不能用spring.application.name默认，而方法2好像程序不能识别这个配置，怎么回事？

**Comment by chuntaojun** [comment]
`nacos.config.auto-refreshed=true`
这个是nacos-springboot-project的预加载配置

**Comment by nangergong** [comment]
> `nacos.config.auto-refreshed=true`
> 这个是nacos-springboot-project的预加载配置

springcloud怎么办？
