### ISSUE TITLE
Can nacos client pulls all properties to local cache directory?

### ISSUE THREAD

**Issue by Holyangelmom** [alibaba/nacos#2262]
### Describe what happened (or what feature you want)
Can nacos client pulls all properties from nacos server to local cache directory when  my application startup?
just like Ctrip's Apollo and Baidu’s Disconf.

### Describe what you expected to happen
Nacos client can cache all properties to local directory. Even if nacos server is not avialable, my application can startup normally.

**Comment by paderlol** [comment]
Yes, we will also save a snapshot locally, which will be available when the server is abnormal. The file is generally defaulted to $ {user.home} /nacos/config
