### ISSUE TITLE
nacos client如何获取系统变量

### ISSUE THREAD

**Issue by ygypc** [alibaba/nacos#2263]
学习Nacos的时候，从nacos例子都是从配置文件获取 server-addr，目前微服务一般都不使用配置文件，配置中心的server-addr都是从linux的系统变量中获的，那么nacos client客户端如何从linux的系统变量中获取server-addr，进行微服务的初始化，谢谢！
在 application.properties 中配置 Nacos server 的地址：
nacos.config.server-addr=127.0.0.1:8848

 When learning Nacos, the example of Nacos is to obtain server addr from the configuration file. At present, the microservice does not use the configuration file. The server addr in the configuration center is obtained from the system variable of Linux. Then how can the Nacos client obtain the server addr from the system variable of Linux to initialize the microservice? Thank you!

**Comment by KeRan213539** [comment]
你用的是 nacos 的 spring-boot-starter吧? 这个应该是不支持的.
目前来看,如果要从环境变量取的话,估计只能直接使用 nacos client了,可以参考: https://nacos.io/zh-cn/docs/sdk.html

**Comment by chuntaojun** [comment]
如果你是使用Spring的话，spring会自动去读取相关Syetem。env参数信息，只需要确保Spring的environment中能够存在你在linux设置的系统变量即可，然后用占位符去配置即可
