### ISSUE TITLE
nacos client start error : java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by Johnnyzhoutq** [alibaba/nacos#2269]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

Nacos client start error : java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer.  
Actually，the JKD  version here is 1.8.0_231, and  Class  java.nio.ByteBuffer really does not exist a function named flip(), If nacos wants to run properly in jdk8 environment, then this may be a bug

### How to reproduce it (as minimally and precisely as possible)
1.Spring Boot version 2.1.7.RELEASE ( nothing wrong with boot )
1. JDK version 1.8.0_231
![image](https://user-images.githubusercontent.com/25298377/71881608-95a47200-316d-11ea-9271-85dce3efe63f.png)

2. spring-cloud-alibaba-dependencies version 0.9.0.RELEASE
3. Nacos-client version 1.0.0

![image](https://user-images.githubusercontent.com/25298377/71881774-f16efb00-316d-11ea-821e-94b951bbdcd6.png)
![image](https://user-images.githubusercontent.com/25298377/71881866-28451100-316e-11ea-86bb-07dd652d59d6.png)

4. JDK compile level is 1.8
![image](https://user-images.githubusercontent.com/25298377/71882415-642ca600-316f-11ea-81ea-b3e078ce47e9.png)

### Tell us your environment

the same to reproduction message ,

**Comment by nkorange** [comment]
The method ```flip()``` is class ```java.nio.Buffer```, which is the super class ```java.nio.ByteBuffer```.
