### ISSUE TITLE
add a button in the operation bar to link to the corresponding subscriber details

### ISSUE THREAD

**Issue by A-CiKe** [alibaba/nacos#2271]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
 In the service list, add a button in the operation bar to link to the corresponding subscriber details.

### Tell us your environment
nacos 1.1.3

**Comment by zhenxianyimeng** [comment]
@i will solve it@

**Comment by BollywoodMovie** [comment]
new hollywood bollywood movies is free entertainment service for every one

**Comment by BollywoodMovie** [comment]
every thing is free for every one there

**Comment by BollywoodMovie** [comment]
https://ok.ru/video/2287699757787

**Comment by itsmeee1** [comment]
I added a phone number to my account did I do it right

**Comment by errorconnection** [comment]
#7024
