### ISSUE TITLE
nacos-client的NacosConfigService类出现bug，将命名空间namespace当成tenant，去做接口请求，导致参数查询不到希望最新版本的jar包能修正这个bug

### ISSUE THREAD

**Issue by aaroncgt90** [alibaba/nacos#2275]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KeRan213539** [comment]
额.其实namespace就是tenant,不知道是历史原因还是什么,namespace的表名,相关操作的部分接口名,参数都是叫 tenant, 所以请求的接口应该是对的. 具体是请求什么接口?出什么错?如何重现?

**Comment by aaroncgt90** [comment]
出现bug的版本在nacos-client1.4的NacosConfigService将namespace封装成这tenant字段去做请求，
请求接口是/nacos/v1/cs/configs，重新结果很简单，直接在浏览器或者配置seata都是报找不到结果，具体请求可以是
http://localhost:8848/nacos/v1/cs/configs?dataId=service.vgroup_mapping.gtkq-system-seata-service-group&group=SEATA_GROUP&namespace=public
（结果返回正常）
http://localhost:8848/nacos/v1/cs/configs?dataId=service.vgroup_mapping.gtkq-system-seata-service-group&group=SEATA_GROUP
（结果返回正常）
http://localhost:8848/nacos/v1/cs/configs?dataId=service.vgroup_mapping.gtkq-system-seata-service-group&group=SEATA_GROUP&tenant=public
（结果返回错误）
而偏偏seata配置文件刚好会读取namespace，刚好又是这个类去封装http接口请求参数，导致接口查询返回结果为config data not exist
目前使用的nacos版本为1.1.3，项目框架使用springcloud

**Comment by KeRan213539** [comment]
大概清楚您的意思了:
参数名用 namespace 没问题,, 参数名用 tenant 就返回错误. 而 client使用的参数名是 tenant, 是这样子吗?
然后问题是出在 1.1.4, 而 1.1.3 没问题?

**Comment by aaroncgt90** [comment]
> 大概清楚您的意思了:
> 参数名用 namespace 没问题,, 参数名用 tenant 就返回错误. 而 client使用的参数名是 tenant, 是这样子吗?
> 然后问题是出在 1.1.4, 而 1.1.3 没问题?

不，事实上client1.1.3版本也出现这个问题，我就是试着升级到1.1.4看看相应的问题是否已经解决，结果也是相同的，并没有解决，如果client的jar包不修改的情况下，相应的查询语句就应该修改了，例如
nacos-server就要修改了

**Comment by KeRan213539** [comment]
OK,知道原因了...参数名用 namespace 是因为根本没有这个参数, 正确的参数名就是 tenant.
问题原因在于没有对 public 这个值做处理,放在 public 空间中的配制,在数据库中对应字段的值是空,而没有对 public 做处理, public 被带到查询中了,所以查不到数据. 只要在 接口处加个判断,如果值为 public 就置空就行.

**Comment by KeRan213539** [comment]
这样处理就行,在子项目 config 的 com.alibaba.nacos.config.server.controller.ConfigController的 getConfig 方法中
```
if (NAMESPACE_PUBLIC_KEY.equalsIgnoreCase(namespace)) {
     namespace = "";
}
```
exportConfig 方法里也会有这个问题

**Comment by aaroncgt90** [comment]
> 这样处理就行,在子项目 config 的 com.alibaba.nacos.config.server.controller.ConfigController的 getConfig 方法中
> 
> ```
> if (NAMESPACE_PUBLIC_KEY.equalsIgnoreCase(namespace)) {
>      namespace = "";
> }
> ```
> 
> exportConfig 方法里也会有这个问题

另外这边还由此发现一个问题，命名空间本身就不可以设置为重复，结果用命名空间名称去请求，反而查不到数据，需要用命名空间所属id才可以访问，是否能优化这个查询呢？

**Comment by KeRan213539** [comment]
这个目前不好处理,命名空间名称是可以重复的,只有ID是唯一的.
我已经提了一个在创建命名空间时可以自定义命名空间ID的PR并且已经合并了,下个版本更新就会有了

**Comment by KeRan213539** [comment]
我来改上面的问题吧...
