### ISSUE TITLE
springboot nacos 能否支持yml格式的配置文件

### ISSUE THREAD

**Issue by chenjianshuo** [alibaba/nacos#2277]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen

springboot nacos 能否支持yml格式的配置文件
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by ordercard** [comment]
支持的，私有文件只能同时支持一种

**Comment by chuntaojun** [comment]
支持，详细请看这里：https://github.com/nacos-group/nacos-spring-boot-project/wiki
