### ISSUE TITLE
How can I start a Nacos cluster through kubernetes?

### ISSUE THREAD

**Issue by q1240725729** [alibaba/nacos#2281]
Nacos uses the hostname + 8848 to connect by default, but the container hostname created by kubernetes is random
nacos.log↓↓↓↓↓↓↓↓↓↓
java.lang.IllegalStateException: unable to find local peer: nacos-7fd759558c-g9sn6:8848
docker container hostname is  nacos-7fd759558c-g9sn6

**Comment by q1240725729** [comment]
I have solved the above bugs，

But there are new problems

cat naming-raft.log you can see 
2020-01-10 03:34:45,001 WARN [IS LEADER] no leader is available now!

2020-01-10 03:35:00,001 WARN [IS LEADER] no leader is available now!

2020-01-10 03:35:15,001 WARN [IS LEADER] no leader is available now!

i see this parameter
NACOS_SERVER_IP
But I used kubernetes to deploy Nacos ，ip is random

**Comment by g5niusx** [comment]
you can refer to this project [nacos-k8s](https://github.com/nacos-group/nacos-k8s)
