### ISSUE TITLE
The method ```flip()``` is class ```java.nio.Buffer```, which is the super class ```java.nio.ByteBuffer```.

### ISSUE THREAD

**Issue by Johnnyzhoutq** [alibaba/nacos#2289]
The method ```flip()``` is class ```java.nio.Buffer```, which is the super class ```java.nio.ByteBuffer```.

_Originally posted by @nkorange in https://github.com/alibaba/nacos/issues/2269#issuecomment-571855594_

Note that this ISSUE is closed, but in fact it just answers that the JDK ByteBuffer extends from Buffer, and the flip method does exist in Buffer. 
In fact, I followed up the nacos source code in my local DEBUG and found that during the startup process, the nacos client service tried to load 
a metadata cache file from a specified path for initialization. 
There was no problem with the first startup, but the second startup (as long as it was not the first startup) , 
The code that loads the metadata cache file [ConcurrentDiskUtil.java:83] (actually byteBuffer.flip ()) 
will cause an exception, causing Throwable to be caught, and then print an ERROR error, 
prompting [java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip () Ljava / nio / ByteBuffer;]

**Comment by Johnnyzhoutq** [comment]
![image](https://user-images.githubusercontent.com/25298377/72148268-57ac8580-33db-11ea-9a11-824c789c6098.png)

**Comment by nkorange** [comment]
The ```try...catch``` is just to avoid exception thrown up to caller method. Not sure why your code throws this 'NoSuchMethod' error, seems you are the first one reporting this. If you can provide a minimum demo to reproduce this error, I can give you further help.

**Comment by Johnnyzhoutq** [comment]
ok, thank you very much.     I have upload maven project here: https://github.com/Johnnyzhoutq/nacos-issue-reproduce-demo.git.

**Comment by Johnnyzhoutq** [comment]
> The `try...catch` is just to avoid exception thrown up to caller method. Not sure why your code throws this 'NoSuchMethod' error, seems you are the first one reporting this. If you can provide a minimum demo to reproduce this error, I can give you further help.

ok, thank you very much. I have upload maven project here: https://github.com/Johnnyzhoutq/nacos-issue-reproduce-demo.git.

**Comment by Johnnyzhoutq** [comment]
> The `try...catch` is just to avoid exception thrown up to caller method. Not sure why your code throws this 'NoSuchMethod' error, seems you are the first one reporting this. If you can provide a minimum demo to reproduce this error, I can give you further help.

ok, thank you very much. I have upload maven project here: https://github.com/Johnnyzhoutq/nacos-issue-reproduce-demo.git.
