### ISSUE TITLE
spring-data-elasticsearch的配置放在nacos中无法启动

### ISSUE THREAD

**Issue by jarven-he** [alibaba/nacos#2290]
spring-data-elasticsearch的配置放在nacos中无法启动项目，但是把相同的配置放在本地的application.properties中就可以启动。

**Comment by token01** [comment]
Advice posted your nacos version and provide detailed anomalies on images or text description！

**Comment by token01** [comment]
https://nacos.io/zh-cn/docs/how-to-reporting-bugs.html

**Comment by jarven-he** [comment]
nacos-config-spring-boot-starter 0.2.4 

配置：
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
spring.data.elasticsearch.cluster-name=elasticsearch

写在本地application.properties中可以启动，写在nacos中则就无法初始化elasticsearchTemplate

**Comment by jarven-he** [comment]
重新提一个
