### ISSUE TITLE
config启动时请求报错

### ISSUE THREAD

**Issue by wolfdriver** [alibaba/nacos#2295]
在Config模块中，ServerListService类在启动时。
由于SpringBean的执行流程中，@PostConstruct注解的init()方法会在onApplicationEvent()方法之前执行。
因此`init()`中启动的定时任务`CheckServerHealthTask`会优先于`onApplicationEvent`方法执行。而`onApplicationEvent`为该定时任务提供服务访问列表（端口号）。因此当服务启动时，会因为缺少端口号，而导致`CheckServerHealthTask`任务第一次HTTP请求执行失败。

如下为`CheckServerHealthTask`任务失败的代码。第一次执行时，serverList中的地址信息中没有端口
```java
for (String serverIp : serverList) {
    String url = "http://" + serverIp + servletContext.getContextPath() + Constants.HEALTH_CONTROLLER_PATH;
    HttpGet request = new HttpGet(url);
    httpclient.execute(request, new AyscCheckServerHealthCallBack(serverIp));
}
```

**Comment by paderlol** [comment]
感谢发现问题,我马上处理一下
