### ISSUE TITLE
nacos配置spring-data-elasticsearch无法启动

### ISSUE THREAD

**Issue by jarven-he** [alibaba/nacos#2297]
spring-boot-starter-data-elasticsearch: 版本 2.1.9.RELEASE
nacos-config-spring-boot-starter  版本 0.2.4

在nacos中配置：
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
spring.data.elasticsearch.cluster-name=docker-cluster 

报错：
Description:
Parameter 1 of constructor in springfox.documentation.spring.web.plugins.WebMvcRequestHandlerProvider required a bean named 'elasticsearchTemplate' that could not be found.
Action:
Consider defining a bean named 'elasticsearchTemplate' in your configuration.
Process finished with exit code 1
无法初始化elasticsearchTemplate
将上述配置直接放在本地application.properties中，其余配置不变，则可以正常启动

**Comment by jarven-he** [comment]
我尝试搭建了一个最小依赖的项目 https://github.com/jarven-he/spring-elasticsearch-demo 。只要有
repository 继承了ElasticsearchRepository，此时将elasticsearch的配置放入nacos中，项目则无法启动。

**Comment by token01** [comment]
This project can directly download to use？

**Comment by jarven-he** [comment]
我在application.properties中配置了一个公网的elasticsearch来供测试使用，拉取代码可以直接启动。这个配置如果放在nacos中，则无法启动。

**Comment by jarven-he** [comment]
我通过测试，在不向关的类中额外引用es的配置使用nacos注入，此时再将配置放在nacos中可以启动。elasticsearchTemplate 能正常加载。 nacos是否是对这种隐式使用配置支持有问题。

**Comment by jarven-he** [comment]
如果方便可以加微信详细探讨这个问题吗？微信号17361806379

**Comment by Arvinhahaha** [comment]
您好这个问题解决了吗
