### ISSUE TITLE
nacos.standalone=true启动模式下的配置中心不支持外部数据库

### ISSUE THREAD

**Issue by yfh0918** [alibaba/nacos#230]
nacos.standalone=true启动模式下的配置中心不支持外部数据库，比如MySQL或者Oracle等等

**Comment by pguo65535** [comment]
standalone 模式的主要目的是用在个人demo, 开发和测试的时候，所以希望是0配置就能运行和使用。

一般预生产和生产上 cluster_mode时，是必须支持MySQL 或者 RDS 这种的。 支持Oracle这个是个好想

法，后面我们可以支持数据存储的扩展。

**Comment by TsingLiang** [comment]
Running Nacos with mysql in Standalone Mode docs:https://nacos.io/en-us/docs/cluster-mode-quick-start.html

**Comment by ricardo0624** [comment]
框架为啥要限制业务,我小项目就想用单机,就算单机测试我也可以用mysql的,感觉这样的设计,就是用业务来限制,不是做框架的思路

**Comment by ricardo0624** [comment]
框架原则应该限制,但是更多的非原则性问题,应该给人选择
