### ISSUE TITLE
use mvn -Prelease-nacos clean install -U build fail.cause test module build Fail

### ISSUE THREAD

**Issue by edisonmiao** [alibaba/nacos#2300]
使用 mvn -Prelease-nacos clean install -U when mvn install the module of test./Users/edison/IdeaProjects/nacos/test/src/test/java/com/alibaba/nacos/test/core/auth/Role_ITCase.java:[22,25] 找不到符号

**Comment by nkorange** [comment]
Use ```mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U``` defined in https://github.com/alibaba/nacos/blob/develop/BUILDING

**Comment by edisonmiao** [comment]
> 使用[https://github.com/alibaba/nacos/blob/develop/BUILDING中](https://github.com/alibaba/nacos/blob/develop/BUILDING)`mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U`定义的[](https://github.com/alibaba/nacos/blob/develop/BUILDING)

why cant i add tag <skipTests>true</skipTests> in pom.xml of test module to build it successful

**Comment by nkorange** [comment]
> > 使用[https://github.com/alibaba/nacos/blob/develop/BUILDING中](https://github.com/alibaba/nacos/blob/develop/BUILDING)`mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U`定义的
> 
> why cant i add tag true in pom.xml of test module to build it successful

What do you mean by 'add tag true'?

**Comment by Uetty** [comment]
[INFO] 61 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Alibaba NACOS 1.3.2 1.3.2:
[INFO]
[INFO] Alibaba NACOS 1.3.2 ................................ SUCCESS [  9.495 s]
[INFO] nacos-api 1.3.2 .................................... SUCCESS [ 13.223 s]
[INFO] nacos-common 1.3.2 ................................. SUCCESS [ 40.160 s]
[INFO] nacos-consistency 1.3.2 ............................ SUCCESS [ 16.185 s]
[INFO] nacos-core 1.3.2 ................................... SUCCESS [ 29.111 s]
[INFO] nacos-config 1.3.2 ................................. SUCCESS [ 28.285 s]
[INFO] nacos-cmdb 1.3.2 ................................... SUCCESS [  1.312 s]
[INFO] nacos-naming 1.3.2 ................................. SUCCESS [ 16.874 s]
[INFO] nacos-address 1.3.2 ................................ SUCCESS [  4.077 s]
[INFO] nacos-client 1.3.2 ................................. SUCCESS [ 23.715 s]
[INFO] nacos-istio 1.3.2 .................................. SUCCESS [  1.842 s]
[INFO] nacos-console 1.3.2 ................................ SUCCESS [ 16.042 s]
[INFO] nacos-test 1.3.2 ................................... FAILURE [  2.254 s]
[INFO] nacos-example 1.3.2 ................................ SKIPPED
[INFO] nacos-distribution 1.3.2 ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:25 min
[INFO] Finished at: 2020-09-14T01:42:45+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project nacos-test: Compilation failure: Compilation failure:
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/naming/ClientBeat_ITCase.java:[20,25] 找不到符号
[ERROR]   符号:   类 Nacos
[ERROR]   位置: 程序包 com.alibaba.nacos
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/common/NacosAsyncRestTemplate_ITCase.java:[19,25] 找不到符号
[ERROR]   符号:   类 Nacos
[ERROR]   位置: 程序包 com.alibaba.nacos
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/naming/SubscribeCluster_ITCase.java:[18,25] 找不到符号
[ERROR]   符号:   类 Nacos
[ERROR]   位置: 程序包 com.alibaba.nacos
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/naming/SelectInstances_ITCase.java:[18,25]  找不到符号
[ERROR]   符号:   类 Nacos
[ERROR]   位置: 程序包 com.alibaba.nacos
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/common/NacosRestTemplate_Interceptors_ITCase.java:[19,25] 找不到符号
[ERROR]   符号:   类 Nacos
[ERROR]   位置: 程序包 com.alibaba.nacos
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/naming/DeregisterInstance_ITCase.java:[18,25] 找不到符号
[ERROR]   符号:   类 Nacos
[ERROR]   位置: 程序包 com.alibaba.nacos
[ERROR] /build/nacos-server/nacos/test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPoll_CITCase.java:[19,25]  找不到符号

**Comment by Uetty** [comment]
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_265, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-52-generic", arch: "amd64", family: "unix"

**Comment by Uetty** [comment]
use following maven command
```
mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U
```
cause 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project nacos-api: Compilation failure: Compilation failure: 
[ERROR] 不再支持源选项 6。请使用 7 或更高版本。
```
environment
```
Vinces-MacBook-Pro:nacos vince$ java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
Vinces-MacBook-Pro:nacos vince$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 15.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "11.0.1", arch: "x86_64", family: "mac"
Vinces-MacBook-Pro:nacos vince$
```

**Comment by Uetty** [comment]
SOME FAQ

while build use idea maven plugin, and failed at [**nacos-test**], please add `-Dmaven.test.skip=true` to [IDEA -> Preferences -> Build,Execution, Deployment -> Build Tools -> Maven -> Runner -> VM Options]. 

Because IDEA 'Togle Skip Tests Mode' is use commond `-DskipTests=true`, it's not the same as `-Dmaven.test.skip=true`
