### ISSUE TITLE
spring cloud gateway整合nacos 无法根据nacos已注册服务生成路由

### ISSUE THREAD

**Issue by lixinglin213** [alibaba/nacos#2302]
springcloud 版本为Hoxton.RELEASE
springboot版本为2.2.2.RELEASE
nacos版本为2.1.0.RELEASE

一切正常，现启动消费服务和网关，将其注册到nacos中（名称为：gateway与microservice），两个服务均已注册成功(nacos列表中显示，互相使用feign调用也是没问题)

这个时候访问 http://gatewayip/port/actuator/gateway/routes  ，正常来说应该显示出microservice的路由信息，但是没有显示，直接通过http://gatewayip:port/microservice/xxx请求微服务接口也是不通的

使用eureka和consul注册中心均可。请问是nacos版本问题还是其他问题导致的呢？

**Comment by lixinglin213** [comment]
看了一下spring cloud alibaba的里程碑，在v2.2.1其中发现问题，主要原因是springcloud 升级到H版本后，更换路由基础组件导致。遇到问题可以暂时将springboot版本降为2.1.x。springcloud版本G.SR3
等里程碑完成后可以升级
[v2.2.1里程碑入口](https://github.com/alibaba/spring-cloud-alibaba/milestone/5)

**Comment by rainbowechoes** [comment]
请问你用的spring cloud alibaba是哪个版本呢？我用的是2.1.0还是无法根据服务名进行调用

**Comment by lixinglin213** [comment]
@rainbowechoes alibaba2.1.0有问题，使用最新版本试试，如果不行就降级一下springcloud版本为G版本就可以解决了
