### ISSUE TITLE
springboot nacos 使用yml格式

### ISSUE THREAD

**Issue by chenjianshuo** [alibaba/nacos#2303]
## Issue Description
springboot nacos 使用yml格式

### Describe what happened (or what feature you want)
使用nacos-config-spring-boot版本为0.2.4可以使用nacos.config.type=yaml的配置，但是如果spirngboot 为1.5.3对应的nacos-config-spring-boot 为0.1.X 的时候是不是不支持yml

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by paderlol** [comment]
好的，我们看一下

**Comment by chuntaojun** [comment]
支持yml的

**Comment by chenjianshuo** [comment]
好像还没解决

**Comment by chuntaojun** [comment]
这个0.1.2+开始就支持的，你的nacos maven依赖贴下，以及具体的使用报错或者问题描述下

**Comment by chenjianshuo** [comment]
0.2.4可以使用nacos.config.type=yaml 这个配置项来指定yaml，但是0.1.2是没有这个配置项的吧

**Comment by chuntaojun** [comment]
see here https://github.com/nacos-group/nacos-spring-boot-project/issues/102

**Comment by chuntaojun** [comment]
请看这里的配置

**Comment by chuntaojun** [comment]
如果你配置了但是不生效，提一个bug的issue到nacos-springboot这个项目中
