### ISSUE TITLE
nacos 无法支持 spring.data.elasticsearch 的配置

### ISSUE THREAD

**Issue by jarven-he** [alibaba/nacos#2305]
将spring.data.elasticsearch的配置放在nacos中无法启动，原因是 ElasticsearchAutoConfiguration使用了@ConditionalOnProperty(prefix = "spring.data.elasticsearch", name = "cluster-nodes", matchIfMissing = false)。 如何解决这个问题呢？

**Comment by paderlol** [comment]
你现在用的是spring boot nacos 还是 spring cloud alibaba

**Comment by paderlol** [comment]
如果是spring boot nacos 可以配置
``` properties
nacos.config.bootstrap.enable=true 
```
参考 [spring boot 0.2.2 以及 0.1.2版本新功能使用手册](https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.2-%E4%BB%A5%E5%8F%8A-0.1.2%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C)

**Comment by jarven-he** [comment]
可以了，谢谢
