### ISSUE TITLE
nacos支持嵌套属性(nested properties)的配置吗？ for example: keyA=XXX${keyB}XXX

### ISSUE THREAD

**Issue by c1028131070** [alibaba/nacos#2306]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
       项目原本使用PropertyPlaceholderConfigurer等方案实现属性配置，可以满足对属性keyA=XXX${keyB}XXX 的处理。
       nacos中也看到相关的处理，但好像没有实现。
 
### Describe what you expected to happen
      	protected abstract Map<String, Object>[] resolveRuntimeAttributesArray(
			T beanDefinition, Properties globalNacosProperties);
       在XmlNacosPropertySourceBuilder的实现中：
      存在			
            // TODO support nested properties
	runtimeAttributes.put(PROPERTIES_ATTRIBUTE_NAME, new Properties());
    这部分内容还没有实现是吗？还是我没有找到。
期待回复！
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
      nacos1.1.4、nacos-spring-context0.3.4

**Comment by RobinsChens** [comment]
这个问题处理了吗
