### ISSUE TITLE
Different namespaces and groups can be called to each other？

### ISSUE THREAD

**Issue by chentiefeng** [alibaba/nacos#2308]
## Spring cloud nacos discovery

Is it possible to add functions: provide methods that can call services between different namespaces and groups with each other. The current version tests the restTemplate that cannot be called. We have this application scenario

**Comment by nkorange** [comment]
I'm afraid not. I think this is against the design of Nacos, which intends to use namespace/group to isolate different users' data.

**Comment by chentiefeng** [comment]
thanks，I have a problem with my design direction
