### ISSUE TITLE
使用config做配置中心，使用dataIds不会加载所对应的分组信息

### ISSUE THREAD

**Issue by mazhai** [alibaba/nacos#2310]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
比如说我有两个分组，一个为默认分组(default_group)一个是自己创建的分组(test)，这两个分组下面都有一个common.yml的文件，我使用group指向自己创建的分组(test)，结果只加载默认分组下的文件，不会加载我指向分组下的文件

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by paderlol** [comment]
你使用的什么版本的nacos,客户端使用的spring boot 还是spring cloud alibaba, 麻烦把配置贴出来下

**Comment by mazhai** [comment]
父级项目pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.10.RELEASE</version>
    </parent>
    <groupId>com.mz.nacos.test</groupId>
    <artifactId>my-nacos-test1</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>my-nacos-discovery-consumer</module>
        <module>my-nacos-discovery-provider</module>
        <module>my-nacos-discovery-gateway-server</module>
        <module>my-nacos-config-client</module>
        <module>my-nacos-config-client-load</module>
        <module>my-sentinel-test1</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Greenwich.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
子项目
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>my-nacos-test1</artifactId>
        <groupId>com.mz.nacos.test</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>my-nacos-config-client-load</artifactId>
    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

</project>

**Comment by paderlol** [comment]
bootstrap.properties配置贴一下,我先看一下,如果有问题 我会把issue转到spring cloud alibaba 那边

**Comment by mazhai** [comment]
bootstrap.yml
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        shared-dataids: common.properties
        group: test

  profiles:
    active: dev
server:
  port: 9050

情况是这样的，我在nacos下分组为默认分组，我在默认分组下创建一个common.properties，然后我新建一个group叫test，test下面也有一个叫common.properties文件，我认为上面的配置文件会读取test组下面的common.properties，然而不是，这个问题倒是可以使用ext-config解决，但我不知道这个算不算一个bug？

**Comment by g5niusx** [comment]
可以贴一下代码吗？我这边测试了一下返回的是当前group的值。

**Comment by ZShUn** [comment]
通过查看spring cloud alibaba nacos config源码发现 group是写死的，所以你配置group并不会生效。
具体问题代码如下：
	private void loadSharedConfiguration(
			CompositePropertySource compositePropertySource) {
		String sharedDataIds = nacosConfigProperties.getSharedDataids();
		String refreshDataIds = nacosConfigProperties.getRefreshableDataids();

		if (sharedDataIds == null || sharedDataIds.trim().length() == 0) {
			return;
		}

		String[] sharedDataIdArry = sharedDataIds.split(SHARED_CONFIG_SEPARATOR_CHAR);
		checkDataIdFileExtension(sharedDataIdArry);

		for (int i = 0; i < sharedDataIdArry.length; i++) {
			String dataId = sharedDataIdArry[i];
			String fileExtension = dataId.substring(dataId.lastIndexOf(".") + 1);
			boolean isRefreshable = checkDataIdIsRefreshbable(refreshDataIds,
					sharedDataIdArry[i]);

			loadNacosDataIfPresent(compositePropertySource, dataId, "DEFAULT_GROUP",
					fileExtension, isRefreshable);
		}
	}

**Comment by ZShUn** [comment]
通过查看spring cloud alibaba nacos config源码发现 group是写死的，所以你配置group并不会生效。
具体问题代码如下：

	private void loadSharedConfiguration(
			CompositePropertySource compositePropertySource) {
		String sharedDataIds = nacosConfigProperties.getSharedDataids();
		String refreshDataIds = nacosConfigProperties.getRefreshableDataids();

		if (sharedDataIds == null || sharedDataIds.trim().length() == 0) {
			return;
		}

		String[] sharedDataIdArry = sharedDataIds.split(SHARED_CONFIG_SEPARATOR_CHAR);
		checkDataIdFileExtension(sharedDataIdArry);

		for (int i = 0; i < sharedDataIdArry.length; i++) {
			String dataId = sharedDataIdArry[i];
			String fileExtension = dataId.substring(dataId.lastIndexOf(".") + 1);
			boolean isRefreshable = checkDataIdIsRefreshbable(refreshDataIds,
					sharedDataIdArry[i]);

                        #具体问题就在下面这一行代码    
			loadNacosDataIfPresent(compositePropertySource, dataId, "DEFAULT_GROUP",
					fileExtension, isRefreshable);
		}
	}

**Comment by ZShUn** [comment]
不会生效就只会加载default_group下面的配置

**Comment by paderlol** [comment]
@ZShUn   good job
