### ISSUE TITLE
获取json配置如何获取

### ISSUE THREAD

**Issue by BlueBlackR9** [alibaba/nacos#2314]
1. 请问我springboot如何获取整个json配置：
{
    "people":{
        "a": "xxx",
        "b": "xxx"
    }
}
示例中都是获取具体某个值：@NacosValue(value = "${people.a}")
但是我想获取的是整个people，可是我这样写报错@NacosValue(value = "${people}")
请问如何获取。
2. json是数组我又该如何获取
{
    "people":[{
        "name":"xxx",
        "age":"12"
    },{
        "name":"xxx",
        "age":"13"
    }]
}

**Comment by nkorange** [comment]
请提交到https://github.com/nacos-group/nacos-spring-project
