### ISSUE TITLE
无法删除服务，specified service has instances

### ISSUE THREAD

**Issue by johnson512** [alibaba/nacos#2315]
在1.14版本中由于误操作或调试，导致我的服务列表中存在很多服务，但是无法对其进行删除。
点击删除按钮，报错：specified service has instances
![image](https://user-images.githubusercontent.com/7509100/72589003-f3d31100-3934-11ea-8e72-3a03af251d7e.png)

**Comment by nkorange** [comment]
服务下面还挂着实例，目前不允许删除，可以停止你们的应用来删除服务

**Comment by nkorange** [comment]
下个版本会支持直接删除服务。

**Comment by token01** [comment]
这是新功能吗@ @nkorange

**Comment by token01** [comment]
我能参与吗

**Comment by johnson512** [comment]
好的等下个版本再试试

**Comment by nkorange** [comment]
@token01 欢迎贡献

**Comment by g5niusx** [comment]
@token01 你已经在解决它了吗？我想尝试修复它。😄
@i will solve it@

**Comment by g5niusx** [comment]
@johnson512 请问你使用的什么框架做的服务注册，我这边想复现一下这个场景。最好可以提供一个可以复现这个场景的思路。谢谢
