### ISSUE TITLE
The documentation is unclear and confusing

### ISSUE THREAD

**Issue by sanxun0325** [alibaba/nacos#2318]
![image](https://user-images.githubusercontent.com/28588342/72593217-6517c180-393f-11ea-8792-5fef816e6a4c.png)

![image](https://user-images.githubusercontent.com/28588342/72593316-9e503180-393f-11ea-8fcf-9f68f752e3a0.png)

The tenant field is not accurately described and should be the corresponding namespace ID field

**Comment by nkorange** [comment]
fixed https://nacos.io/zh-cn/docs/open-api.html
