### ISSUE TITLE
何时能支持多种类型的数据库？如：Oracle、PostgreSQL、DB2等

### ISSUE THREAD

**Issue by yinxiaoling** [alibaba/nacos#2328]
何时能支持多种类型的数据库？

如：Oracle、PostgreSQL、DB2等

**Comment by paderlol** [comment]
目前我在做这个工作了

**Comment by yinxiaoling** [comment]
> 目前我在做这个工作了

太好了，太厉害了，能否加入一起做这个工作呢，我们也想做开源共建工作，我们还想集成一下国产数据库，因为目前国内国产化的趋势太厉害了，我们的平台微服务架构使用了Nacos为核心的，数据库导致我们国产化进程很失败。如果能一起的话就好了，我们一起来完善这个事情。

**Comment by yinxiaoling** [comment]
> 目前我在做这个工作了

方便的话留一下钉钉联系方式

**Comment by Slive** [comment]
同样关注这个问题
大概什么时候能支持呀？

**Comment by dljunzhuo** [comment]
> 目前我在做这个工作了

能说下大概什么时候上线这个功能吗？

**Comment by turtler000** [comment]
> 目前我在做这个工作了

有计划集成华为的gaussdb吗？

**Comment by asog** [comment]
> 目前我在做这个工作了

很想知道什么时候能上线，升级框架考虑nacos但是数据库限制必须oracle。

**Comment by wanchenqi** [comment]
请问现在数据库支持sqlserver吗？

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2434

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/534

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/237

**Comment by paderlol** [comment]
下个月中会出一个版本试用吧

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2862

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2910

**Comment by EnjoywithSunshine** [comment]
@paderlol  这个月都快过去了，不是说这个月中出个试用版吗? 大概还要多久？！

**Comment by paderlol** [comment]
@EnjoywithSunshine 目前已经在测试了 预计是这个小版本或者下个小版本 具体负责贡献的是这个小伙伴@ZShUn

**Comment by ZShUn** [comment]
@EnjoywithSunshine 不好意思，目前由于个人工作原因导致进度比较缓慢，目前整个项目sql已经翻译完成。后续的代码cv和BUG修改，我尽量赶上来，请见谅

**Comment by chuawei** [comment]
多数据库支持，还在继续么？

**Comment by tony-zz** [comment]
pgsql 什么时候上？

**Comment by EnjoywithSunshine** [comment]
@paderlol 从7月到9月，更新了beta版本，更新了正式版，依然看不到多数据源这块配置
@ZShUn 不是说sql翻译好了吗？bug和cv要花那么多时间？两个月的时间还没搞定？那就分块上，别一口吃个胖子，比如先上一个oracle的，这样我就不来催更！

**Comment by horizonzy** [comment]
@ZShUn 比较忙的话我可以帮忙协助开发以及测试

**Comment by ZShUn** [comment]
我下周日提一版

**Comment by ZShUn** [comment]
@horizonzy 感谢大佬帮忙

**Comment by a434950303** [comment]
持续关注 ，oracle 真的急需

**Comment by a434950303** [comment]
> 我下周日提一版

大佬 出来了吗？

**Comment by paderlol** [comment]
他今天在提pr，会有个单独分支在处理这个功能

**Comment by ZShUn** [comment]
老铁们，我再整了。  很快，莫慌

**Comment by chenpenghui93** [comment]
> 老铁们，我再整了。 很快，莫慌

请问下支持多类型数据库(oracle)的，现在有可用版本了吗？

**Comment by liubinylx** [comment]
mark下，我觉得是个优先级很高的需求

**Comment by jhyhhmail** [comment]
大佬有支持oracle的版本了吗？

**Comment by jhyhhmail** [comment]
> > 老铁们，我再整了。 很快，莫慌
> 
> 请问下支持多类型数据库(oracle)的，现在有可用版本了吗？

大佬，不好意思问一下，有大概的发布时间吗？

**Comment by ZShUn** [comment]
> @ZShUn 比较忙的话我可以帮忙协助开发以及测试

![image](https://user-images.githubusercontent.com/16457274/96091730-891f2800-0efc-11eb-9470-281279c18a68.png)
代码在这个分支，大佬有空可以搞起

**Comment by ZShUn** [comment]
@horizonzy 
![image](https://user-images.githubusercontent.com/16457274/96091850-ace26e00-0efc-11eb-96e7-3ce87fd1b20c.png)
代码已经合到这个分支了，大佬有空可以搞起

**Comment by horizonzy** [comment]
> @horizonzy
> ![image](https://user-images.githubusercontent.com/16457274/96091850-ace26e00-0efc-11eb-96e7-3ce87fd1b20c.png)
> 代码已经合到这个分支了，大佬有空可以搞起

好，抽空搞起

**Comment by li24361** [comment]
真是好消息, 项目急需oracle

**Comment by niaiwomattt** [comment]
postgresql ，希望能支持，有没有规划？展示出来看看呗。

**Comment by luamas** [comment]
什么时候能合并到dev分支去啊，急需pgsql的支持

**Comment by niaiwomattt** [comment]
昨天搞了一天，k8s 里部署不成功，总是报错 no DataSource  set，重新 docker build 都弄不好，我也不是 Java 程序员，搞不了，弃坑了！

**Comment by littleJK-sys** [comment]
Mark 一下，求Oracle类型支持，跪求

**Comment by chuntaojun** [comment]
> no DataSource set

no DataSource set由具体原因，看下报错信息，还有关注启动模式是哪一种

**Comment by babyzhang** [comment]
请问什么时候可以合并到dev，谢谢！

**Comment by CodeDWX** [comment]
> @EnjoywithSunshine 不好意思，目前由于个人工作原因导致进度比较缓慢，目前整个项目sql已经翻译完成。后续的代码cv和BUG修改，我尽量赶上来，请见谅

大佬可以问下现在有稳定版本的数据库持久化支持Oracle吗

**Comment by DemoMoon** [comment]
@ZShUn 大佬好，该分支的config模块下的modules的entity缺失QUsersEntity 类，环境编译不通过。
![image](https://user-images.githubusercontent.com/5241098/98789406-37a38380-243d-11eb-89b1-f06ce27a7d82.png)

**Comment by DemoMoon** [comment]
最近刚整了个oracle版本，大家可以参考下。 https://github.com/DemoMoon/nacos-all

**Comment by dudiao** [comment]
@DemoMoon 老哥，可以考虑提交各PR吧

**Comment by horizonzy** [comment]
> @horizonzy
> ![image](https://user-images.githubusercontent.com/16457274/96091850-ace26e00-0efc-11eb-96e7-3ce87fd1b20c.png)
> 代码已经合到这个分支了，大佬有空可以搞起

sry，前段时间没有弄这个，最近一个月会把重心放在这个上面。

**Comment by horizonzy** [comment]
> @horizonzy
> ![image](https://user-images.githubusercontent.com/16457274/96091850-ace26e00-0efc-11eb-96e7-3ce87fd1b20c.png)
> 代码已经合到这个分支了，大佬有空可以搞起

老哥，有钉钉交流一下关于多数据源的代码吗

**Comment by HelloHaiNG** [comment]
> 下个月中会出一个版本试用吧

请问一下现在多数据源的这个分支支持哪几种数据源呢

**Comment by yangszz** [comment]
同样需求

**Comment by cuizhihua127** [comment]
现在的分支版本是可用的嘛？  我clone下来启动报错

Description:

Field usersRepository in com.alibaba.nacos.config.server.auth.ExternalUserPersistServiceImpl required a bean of type 'com.alibaba.nacos.config.server.modules.repository.UsersRepository' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'com.alibaba.nacos.config.server.modules.repository.UsersRepository' in your configuration.

**Comment by tony-zz** [comment]
> 目前我在做这个工作了

马上快一年了

**Comment by niaiwomattt** [comment]
> > 目前我在做这个工作了
> 
> 马上快一年了

KPI 任务，KPI 完了，你还想着有人维护 ？仓库没关就对得起你了！

**Comment by duoqu** [comment]
> > 目前我在做这个工作了
> 
> 太好了，太厉害了，能否加入一起做这个工作呢，我们也想做开源共建工作，我们还想集成一下国产数据库，因为目前国内国产化的趋势太厉害了，我们的平台微服务架构使用了Nacos为核心的，数据库导致我们国产化进程很失败。如果能一起的话就好了，我们一起来完善这个事情。

国产化用的什么数据库？我们用达梦 dm。你用nacos可以支持国产的数据库了么

**Comment by siaron** [comment]
postgresql 有任何更新吗? 社区都反映这么强烈了. 有任何更新吗?

**Comment by babyzhang** [comment]
我等了快一年了，请问下多数据库支持还有人在搞吗？

**Comment by niaiwomattt** [comment]
> 我等了快一年了，请问下多数据库支持还有人在搞吗？

搞个屁，KPI库，KPI早完了，库你还想有人维护？

**Comment by EnjoywithSunshine** [comment]
@paderlol 代码仓库多数据源的分支已经有了，但是线上发布的nacos迟迟没有多数据源配置这块？另外有一个问题，楼上的这个“niaiwomattt”是不是你方的开发人员，说话的粗鲁程度，我觉得不是特别好，如果不是你方人员，麻烦删除它的评论
@ZShUn 帅哥，时隔多久了，这个进度有多少人关心着，麻烦说一下目前进展进度，给所有关心的人一个答复。我觉得答复一下，不会浪费太多时间的，可以吗？

**Comment by God-Gan** [comment]
给大家一个能用的集成postgresql的版本
https://github.com/tudan110/nacos

**Comment by tudan110** [comment]
我在做 postgresql 的版本啦，后续会持续更新哒，博文请参考：[https://tudan.blog.csdn.net/article/details/113400766](https://tudan.blog.csdn.net/article/details/113400766)，github：[https://github.com/tudan110/nacos](https://github.com/tudan110/nacos)

**Comment by SinLiz** [comment]
我做了一个 达梦 版本的，单机现在没问题，集群我还没测试，有没有哪位朋友搞过的，交流一下。

**Comment by duoqu** [comment]
hi，能留个微信么。交流下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月8日(周四) 中午12:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 何时能支持多种类型的数据库？如：Oracle、PostgreSQL、DB2等 (#2328)




 
我做了一个 达梦 版本的，单机现在没问题，集群我还没测试，有没有哪位朋友搞过的，交流一下。

**Comment by rbhuang** [comment]
any progress on this issue? It's critical to support other DB. Please consider the sql server support as it's the only official support we have in our environment.

**Comment by alonelaval** [comment]
已适配达梦，人大金仓。https://github.com/alonelaval/nacos/blob/dm-1.4.1/console/src/main/resources/application.properties

**Comment by liubinylx** [comment]
> 我在做 postgresql 的版本啦，后续会持续更新哒，目前我已经用上了
> 
> 1. 博文请参考：https://tudan.blog.csdn.net/article/details/113400766
> 2. github：https://github.com/tudan110/nacos

都是在给自己仓库打广告的。。。

**Comment by liubinylx** [comment]
> 已适配达梦，人大金仓。https://github.com/alonelaval/nacos/blob/dm-1.4.1/console/src/main/resources/application.properties

给自己打广告倒是很熟练

**Comment by alonelaval** [comment]
> > 已适配达梦，人大金仓。https://github.com/alonelaval/nacos/blob/dm-1.4.1/console/src/main/resources/application.properties
> 
> 给自己打广告倒是很熟练

你这话有点搞笑。我找了上面的所有的链接，没有一个可以用的。只好我自己来，我弄好了，把包也发出来了，这叫打广告？自己心里面阴暗，以为别人跟你一样阴暗？

**Comment by wuwen5** [comment]
尝试一种无需改造nacos项目采用sql替换的方式支持oracle，可以保持nacos的版本演进, 未来官方支持后也可以直接拿掉.

- 将包放入nacos-server.jar同级目录

- 修改start.sh

    `JAVA_OPT="${JAVA_OPT} -javaagent:${BASE_DIR}/target/ojdbc-mysql2oracle-1.0.0-SNAPSHOT.jar -jar ${BASE_DIR}/target/${SERVER}.jar"`

https://github.com/wuwen5/ojdbc-mysql2oracle

**Comment by li24361** [comment]
> 尝试一种无需改造nacos项目采用sql替换的方式支持oracle，可以保持nacos的版本演进, 未来官方支持后也可以直接拿掉.
> 
> * 将包放入nacos-server.jar同级目录
> * 修改start.sh
>   `JAVA_OPT="${JAVA_OPT} -javaagent:${BASE_DIR}/target/ojdbc-mysql2oracle-1.0.0-SNAPSHOT.jar -jar ${BASE_DIR}/target/${SERVER}.jar"`
> 
> https://github.com/wuwen5/ojdbc-mysql2oracle

能详细说明下吗?直接通过agent替换吗

**Comment by wuwen5** [comment]
> > 尝试一种无需改造nacos项目采用sql替换的方式支持oracle，可以保持nacos的版本演进, 未来官方支持后也可以直接拿掉.
> > 
> > * 将包放入nacos-server.jar同级目录
> > * 修改start.sh
> >   `JAVA_OPT="${JAVA_OPT} -javaagent:${BASE_DIR}/target/ojdbc-mysql2oracle-1.0.0-SNAPSHOT.jar -jar ${BASE_DIR}/target/${SERVER}.jar"`
> > 
> > https://github.com/wuwen5/ojdbc-mysql2oracle
> 
> 能详细说明下吗?直接通过agent替换吗

@li24361 是的，不过agent仅仅只是替换驱动类，因为驱动类硬编码没有支持配置(如果驱动类支持外部配置，可以不用agent,只需将包放入classpath路径中)，本项目主要实现是基于驱动包装做的sql拦截和替换,sql语法解析使用的jsqlparse, 本项目目的是不去修改原工程的基础上支持oracle(可以尝试支持其他库的语法)，在官方没有发布支持多数据库版本之前，我们修改源代码重新打包编译的方式未来bugfix的版本跟进会比较麻烦.  
btw 目前已在nacos、xxl-job项目中使用

**Comment by loca1h0sts** [comment]
> 现在的分支版本是可用的嘛？ 我clone下来启动报错
> 
> Description:
> 
> Field usersRepository in com.alibaba.nacos.config.server.auth.ExternalUserPersistServiceImpl required a bean of type 'com.alibaba.nacos.config.server.modules.repository.UsersRepository' that could not be found.
> 
> The injection point has the following annotations: - @org.springframework.beans.factory.annotation.Autowired(required=true)
> 
> Action:
> 
> Consider defining a bean of type 'com.alibaba.nacos.config.server.modules.repository.UsersRepository' in your configuration.

兄弟，你解决了吗？

**Comment by siaron** [comment]
> > > 尝试一种无需改造nacos项目采用sql替换的方式支持oracle，可以保持nacos的版本演进, 未来官方支持后也可以直接拿掉.
> > > 
> > > * 将包放入nacos-server.jar同级目录
> > > * 修改start.sh
> > >   `JAVA_OPT="${JAVA_OPT} -javaagent:${BASE_DIR}/target/ojdbc-mysql2oracle-1.0.0-SNAPSHOT.jar -jar ${BASE_DIR}/target/${SERVER}.jar"`
> > > 
> > > https://github.com/wuwen5/ojdbc-mysql2oracle
> > 
> > 
> > 能详细说明下吗?直接通过agent替换吗
> 
> @li24361 是的，不过agent仅仅只是替换驱动类，因为驱动类硬编码没有支持配置(如果驱动类支持外部配置，可以不用agent,只需将包放入classpath路径中)，本项目主要实现是基于驱动包装做的sql拦截和替换,sql语法解析使用的JSqlParser, 本项目目的是不去修改原工程的基础上支持oracle(可以尝试支持其他库的语法)，在官方没有发布支持多数据库版本之前，我们修改源代码重新打包编译的方式未来bugfix的版本跟进会比较麻烦. btw 目前已在nacos、xxl-job项目中使用

```btw 目前已在nacos、xxl-job项目中使用``` 会开源吗? 哈哈哈哈哈

**Comment by bianjp** [comment]
#4941 合并到 feature_multiple_datasource_support 分支后很久没动静了，这项工作停止了？

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by llsydn** [comment]
> 现在的分支版本是可用的嘛？ 我clone下来启动报错
> 
> Description:
> 
> Field usersRepository in com.alibaba.nacos.config.server.auth.ExternalUserPersistServiceImpl required a bean of type 'com.alibaba.nacos.config.server.modules.repository.UsersRepository' that could not be found.
> 
> The injection point has the following annotations: - @org.springframework.beans.factory.annotation.Autowired(required=true)
> 
> Action:
> 
> Consider defining a bean of type 'com.alibaba.nacos.config.server.modules.repository.UsersRepository' in your configuration.

你这个错,  是没有指定数据源导致的.  你配置下数据源, 就不会出现这个错了.  底层用的是jpa, 需要初始化数据源, 才可以实例化UsersRepository接口.

nacos.datasource.type=MYSQL
#
nacos.datasource.relational.dsList[0].url=jdbc:mysql://127.0.0.1:3306/nacos?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
nacos.datasource.relational.dsList[0].username=root
nacos.datasource.relational.dsList[0].password=root
nacos.datasource.relational.dsList[0].driver-class-name=com.mysql.jdbc.Driver
nacos.datasource.relational.dsList[0].hikari.connection-timeout=10000
nacos.datasource.relational.dsList[0].hikari.idle-timeout=120000
nacos.datasource.relational.dsList[0].hikari.max-lifetime=240000
nacos.datasource.relational.dsList[0].hikari.maximum-pool-size=20
nacos.datasource.relational.dsList[0].hikari.data-source-properties.cachePrepStmts=true
nacos.datasource.relational.dsList[0].hikari.data-source-properties.prepStmtCacheSize=250
nacos.datasource.relational.dsList[0].hikari.data-source-properties.prepStmtCacheSqlLimit=2048
nacos.datasource.relational.dsList[0].hikari.connection-test-query=SELECT 1 FROM dual

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by siaron** [comment]
- 无需改造nacos项目采用sql替换的方式支持postgresql 版本移植自https://github.com/wuwen5/ojdbc-mysql2oracle
- https://github.com/siaron/mysql2postgresql-jdbc-agent

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by idelin** [comment]
所以官方还在推进这个工作吗，已经过去2年了

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by zoujiaqing** [comment]
哈哈哈，这效率。。

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by tony-zz** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by cloorc** [comment]
> 目前我在做这个工作了

I've submitted a pull request to add postgres support, please have a look at #9760 #9761

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by KomachiSion** [comment]
#8803

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！

**Comment by dylan-tao** [comment]
目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb

**Comment by littleJK-sys** [comment]
邮件已收到，请放心我会尽快查看
每天要开心幸福哦！
