### ISSUE TITLE
How to change server port when developing?

### ISSUE THREAD

**Issue by jun1st** [alibaba/nacos#233]
try to run the project with IntelliJ, I'd like to change server port to a different one other than 8848. 

Have tried modify all found 8848 to 8080 in project, but the server still runs on port 8848

how to change that?

**Comment by xuechaos** [comment]
@jun1st hi  How did you change the port?  console project?

**Comment by jun1st** [comment]
changed every "8848" found inside "nacos-all" project.

<img width="968" alt="screen shot 2018-11-08 at 8 14 50 pm" src="https://user-images.githubusercontent.com/140474/48198180-01852200-e393-11e8-9cce-9debd9e0b45e.png">

there is no `application.properties` file found in `console` project, I also tried add one and set `server.port = 8080`

all attempts failed :(

**Comment by jun1st** [comment]
0.5.0 的版本已经支持设置端口了
