### ISSUE TITLE
订阅者列表里面是空的

### ISSUE THREAD

**Issue by juzi214032** [alibaba/nacos#2330]
Nacos版本1.1.4

我的服务提供者和服务消费者都显示在服务列表中，订阅者列表显示为空
订阅者列表不是用来显示服务消费者的吗？如果不是那是用来显示什么的呢

**Comment by chuntaojun** [comment]
是否有输入信息进行查询？

**Comment by juzi214032** [comment]
> 是否有输入信息进行查询？

尝试过输入信息和不输入信息查询，但是列表都是空的

**Comment by zhou-hao** [comment]
客户端提示注册完成，但是nacos控制台的服务列表是空的

**Comment by DraperChen** [comment]
我也存在这个问题，服务端和客户端都是1.1.4，订阅者列表为空但是可以调用

**Comment by csloter** [comment]
> > 是否有输入信息进行查询？
> 
> 尝试过输入信息和不输入信息查询，但是列表都是空的

Is the **serverName** normally provided? If the service name is invalid，the result **is** `{"subscribers":[],"count":0}`

**Comment by Dong-2017** [comment]
这个订阅者列表不是指消费者列表，而是指主动向Nacos Server发起事件监听的订阅者，比如健康检查、服务变更等事件监听的订阅者，具体可查看NacosDiscoveryEndpoint.nacosDiscovery()方法中是通过EventDispatcher去获取订阅者列表和发布事件。新版本才加了这么个订阅者列表，老版本可以订阅默认端点查看订阅者列表：http://127.0.0.1:9000/actuator/nacos-discovery

**Comment by emcchui** [comment]
我的也是，NACOS1.3.2

**Comment by caiyuanhui** [comment]
订阅者列表为空解决了吗？我也有这个问题，nacos2.0.3 集群 @csloter

**Comment by little-apppple** [comment]
@caiyuanhui nacos2.0.3 集群 订阅者列表为空 +1 ,单机的订阅者列表是有的，集群上就为空了，你有解决吗

**Comment by Roronoa-Zoro** [comment]
@little-apppple  我也遇到和你一样的问题了，你解决了不
