### ISSUE TITLE
Dubbo注册到Nacos时的服务名称

### ISSUE THREAD

**Issue by juzi214032** [alibaba/nacos#2331]
使用Dubbo注册服务到Nacos时，发现一个@Service注解就会生成一个服务，并且服务名称是全类名，十分不好管理，有什么办法设置服务的名称吗
还有就是使用了Dubbo的@Serivce注册到Nacos后，还需要使用Nacos的DiscoveryClient再注册一次吗？这样会重复吗
![](https://oss.juzibiji.top/image/20200201195732.png)

**Comment by chuntaojun** [comment]
这个和dubbo的模型已经dubbo上报的信息有关系
