### ISSUE TITLE
该版本不能支持多配置，xxx-dev或xxx-test的yaml配置读不到！！！

### ISSUE THREAD

**Issue by ynclub** [alibaba/nacos#2332]
first,i have bootstrap.properties:
spring.profiles.active=dev
spring.application.name=xxx-config
spring.cloud.nacos.config.file-extension=yaml
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=xxxxxxx-6c31-48fb-9318-dd59ba9f1900
spring.cloud.nacos.config.group=xxx_GROUP

second,at nacos, in my namespace i create the file xxx-config-dev

run my programe, error info:

Ignore the empty nacos configuration and get it based on dataId[xxx-config-dev.yaml] & group[DEMO_GROUP]

then i create the file  xxx-config

and run my programe, info is ok!

so, i belive your nacos have bug!!!

**Comment by william-xu** [comment]
Data id maps to spring.application.name, if you have configuration with Data ID ="xxx-config-dev.yaml ",  you can define spring.application.name=xxx-config-dev in application-dev.properties to use it

**Comment by chuntaojun** [comment]
You can refer to the documentation here for configuration: https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-config

**Comment by ynclub** [comment]
your doc about "支持自定义扩展的 Data Id 配置" say:
配置的优先级
Spring Cloud Alibaba Nacos Config 目前提供了三种配置能力从 Nacos 拉取相关的配置。

A: 通过 spring.cloud.nacos.config.shared-dataids 支持多个共享 Data Id 的配置

B: 通过 spring.cloud.nacos.config.ext-config[n].data-id 的方式支持多个扩展 Data Id 的配置

C: 通过内部相关规则(应用名、应用名+ Profile )自动生成相关的 Data Id 配置

当三种方式共同使用时，他们的一个优先级关系是:A < B < C

I used is c! but can't!   so I must use A or B ？

**Comment by william-xu** [comment]
我的理解是"支持自定义扩展的 Data Id 配置"这部分描述的是一个应用使用多个nacos配置以及多个应用共享相同配置的情况，这里多个共享Data ID可以认为是将一个profile中通用的配置抽取出来分开定义在不同配置中的情形。如果你已经定义了DataId 为xxx-config.yaml和xxx-config-dev.yaml的两个配置，那么应用名称设置为xxx-config，指定spring.profiles.active=dev时会使用xxx-config-dev.yaml,不指定时会使用xxx-config.yaml，不需要使用扩展模式，也不需要在本地“application-dev.properties”中重定义应用名称，具体可以查看“可支持profile粒度的配置”部分。
-----------------------------------------
What I understand is that the content you quoted above describes how can one application use multi configurations or multi apps use same sets of configurations. if you already have two configuratiosns with Data Id = "xxx-config.yaml" and Data Id = "xxx-config-dev.yaml" in nacos server, you can use profile mode instead of extension mode.

**Comment by ynclub** [comment]
I know where my problem is,  your Nacos only supports "Data ID: nacos-config.yaml",not supports 
"Data ID: nacos-config.yml" ,so I Suggest：
Nacos Should support the yml suffix, after all, everyone is used to writing this。
中国话：NACOSData ID设置里不支持xxx-config.yml简写后缀来支持多配置，要用全称xxx-config.yaml,否则bootstrap.properties里的spring.profiles.active=develop多配置开关没法对应找到相关设置，建议NACOS增加对简写后缀的支持，毕竟很多人习惯这么写
Thank you in the end for giving me a lot of inspiration
最后在这里感谢阿里的老师，能够一直给与回复和解答~~~

**Comment by chuntaojun** [comment]
对于nacos来说，data-id是强匹配，没有文件名后缀这一说法，这个是spring-cloud做的支持，nacos对于文件类别的判断是设置file-type。因此还是根据data-id是什么就写什么

**Comment by ynclub** [comment]
sorry，I known question。my NACOS: Data Id = "xxx-config-dev.yml",but my bootstrap.properties: spring.cloud.nacos.config.file-extension=yaml, my suggest:

Why does the parameter setting name use the file name method, which is not in line with human nature? There is a configuration format in NACOS settings. Why ca n’t you judge based on this? This can reduce a lot of unnecessary configuration and is not prone to errors
（中文）建议：
为什么NACOS参数设置名称要用类似文件名称的方式，不符合人性啊，NACOS设置里有配置格式，为什么不能依据这个来判断，这样可以少很多不必要的配置，也不容易出错了

**Comment by ynclub** [comment]
@chuntaojun ok, Thank you for your answer，Can solve the problem！

**Comment by chuntaojun** [comment]
因为当前的实现中并没有透传file-type信息，这个我们后面会去优化掉，也欢迎一起共建

**Comment by william-xu** [comment]
> 对于nacos来说，data-id是强匹配
@chuntaojun thank you ,got it.

**Comment by RobinsChens** [comment]
能否支持map 类型的properties配置呢，因为key是动态了

**Comment by chuntaojun** [comment]
> 能否支持map 类型的properties配置呢，因为key是动态了

 Nacos only knows the content of configuration as string, and the specific analysis is realized by the corresponding ecological components
