### ISSUE TITLE
你们知道这个安装包下载有多慢吗。。。能同步一份到官网不。。

### ISSUE THREAD

**Issue by MitrichevGoing** [alibaba/nacos#2340]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zhisheng17** [comment]
+1，可以放一份在国内，这样下载速度会比较快些

**Comment by nkorange** [comment]
加钉钉群：21708933，群文件里有
