### ISSUE TITLE
NamingService.getSubscribeServices don't return any services

### ISSUE THREAD

**Issue by fangjian0423** [alibaba/nacos#2348]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

As titled, NamingService.getSubscribeServices don't return any services by NacosDiscoveryEndpoint.

### Anything else we need to know?

Nacos-Client 1.1.4 & Nacos-Server 1.1.4

**Comment by chuntaojun** [comment]
Here to get all the subscribed services, you need to call the subscribe of NamingService, and then it will return. Here, only the data acquisition of the local memory latitude is involved.

**Comment by chuntaojun** [comment]
```java
public List<ServiceInfo> getSubscribeServices() {
        List<ServiceInfo> serviceInfos = new ArrayList<ServiceInfo>();
        for (String key : observerMap.keySet()) {
            serviceInfos.add(ServiceInfo.fromKey(key));
        }
        return serviceInfos;
    }

```
