### ISSUE TITLE
two service，application name：nacos-a，nacos-b。only nacos-a can find in nacos server

### ISSUE THREAD

**Issue by daxian-zhu** [alibaba/nacos#2351]
nacos-a
`spring:
  application:
    name: nacos-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
      file-extension: yaml
server:
  port: 8661`
nacos-b
`spring:  
   application:
    name: nacos-b
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
      file-extension: yaml
server:
  port: 8662` 
result：
![微信截图_20200207172032](https://user-images.githubusercontent.com/53220257/74017095-8d3e9180-49ce-11ea-9be5-a5aff91e2599.png)
 But if I change my name to：nacosA，nacosB
The result is right 
![微信截图_20200207172548](https://user-images.githubusercontent.com/53220257/74017269-ea3a4780-49ce-11ea-9d46-b48c8e202b19.png)

**Comment by ZShUn** [comment]
task a look config

**Comment by ZShUn** [comment]
Take a look at your config

**Comment by daxian-zhu** [comment]
> Take a look at your config

spring:
  application:
    name: nacos-a
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
      file-extension: yaml
server:
  port: 8661
