### ISSUE TITLE
最新nacos-server-1.2.0-beta.0的权限控制为什么只支持到命名空间级别和文档中说的对不上

### ISSUE THREAD

**Issue by ordercard** [alibaba/nacos#2357]
## Issue Description
  最新的beta版本 nacos-server-1.2.0-beta.0.tar.gz  
   在权限管理方面我看到的真是针对用户角色做到 命名空间级别的读写权限的控制，
我看文档中说最小是能支持到 data-id级别的，什么时候能够支持到这个data-id级别
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
目前只做到了namespace方面的权限控制，如果细化到data-id的话，考虑到页面现实的list，需要针对权限统一做过滤，可能成本太大，因此优先支持了namespace级别，data-id级别理论上是支持的

**Comment by chuntaojun** [comment]
> 目前的设计方案可以支持最小到dataId级别的鉴权，但是粒度越细在页面的展示就会越复杂，需要每个资源都去检查是否有权限然后再决定是否展示，对于数据量比较大的情况，会非常影响服务端的性能。不过可以肯定的是一定会支持命名空间级别的读写授权，用户可以在页面配置将某个命名空间的读写权限授权给某一个角色，然后再将这个角色授权给某个用户。至于更细粒度的授权，可能考虑不支持或者在1.2.0之后的版本支持。

**Comment by ordercard** [comment]
如果只到这个namespace界别是否粒度太大了~~，在我看来支持dataid是很合理的啊，如果只到namespace 级别，我个人认为粒度太大，不到dataid级别还是会出现dataid被不是该dataid的负责人修改，我之前看到过 数据库中并没有记录dataid的修改人记录，只有修改时间~~

**Comment by ordercard** [comment]
强烈建议需要支持到dataid级别

**Comment by chuntaojun** [comment]
关于操作记录的后面会增加的

**Comment by chuntaojun** [comment]
目前是完全支持data-id级别的控制的，如果有需要的话可以自行先修改下，关于是否将权限粒度继续细化，我们会进行考虑以及看社区的反馈的

**Comment by ordercard** [comment]
“目前是完全支持data-id级别的控制的，如果有需要的话可以自行先修改下”
您的意思让我们自行修改？ 有没有相关的文档教程？
 强烈建议将权限控制支持到dataid级别

**Comment by nkorange** [comment]
@ordercard 针对dataId级别的控制，会在页面展示上比较复杂，所以这个版本不支持。

**Comment by ordercard** [comment]
@nkorange  如果是是否有这样的接口做到对dataId级别的控制，让我们可以通过api的形式去给你某些用户对某些 dataid加读写权限？

**Comment by wangtoye** [comment]
同样希望有能够针对到data-id级别的权限控制

**Comment by zscboy** [comment]
强烈支持此功能！

**Comment by jerrychern** [comment]
@ordercard 您好 我在nacos控制台设置了一个read用户，角色是READ_ONLY，权限是对public只读，但是我用read用户登录还能修改配置，我使用的是nacos1.2.1，application.yml也是默认配置，是不是还要改什么，才能生效？
