### ISSUE TITLE
Nacos UI 上能否增加全局切换 namespace 下拉列表，这样使用要便捷些

### ISSUE THREAD

**Issue by mj19910923** [alibaba/nacos#2358]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
Is it possible to add a global switch namespace drop-down list on Nacos UI, which is more convenient to use
个人拙见，Nacos UI 上能否增加全局切换 namespace 下拉列表，这样使用要便捷些

![9ead6cfc39e821ff47dfd72b9edb30b](https://user-images.githubusercontent.com/6964129/74299958-3c8db680-4d89-11ea-8585-2f2524051383.png)

**Comment by zzq1314zll** [comment]
@nkorange Can i do this
