### ISSUE TITLE
why the startup.sh use javac?

### ISSUE THREAD

**Issue by leach** [alibaba/nacos#2361]
Version: 1.1.4

Startup.sh Line 44：
```
JAVA_PATH=`dirname $(readlink -f $(which javac))`
```

Why not `Java` ？

**Comment by william-xu** [comment]
Line 44  is JAVA_PATH setting.
at line 73: 
export JAVA="$JAVA_HOME/bin/java"
at line 133:
nohup $JAVA ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
