### ISSUE TITLE
Nacos使用docker部署，配置mysql主从数据库使用一段时间后主从失效

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/nacos#2362]
查看从节点发现his_config_info表数据有问题
Last_SQL_Error: Could not execute Delete_rows event on table nacos-config.his_config_info; Can't find record in 'his_config_info', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log master_log.000002, end_log_pos 133198660
然后使用数据库查看数据
![image](https://user-images.githubusercontent.com/34908518/74405430-feb38f80-4e67-11ea-818c-2ccfb2741914.png)
![image](https://user-images.githubusercontent.com/34908518/74405633-88635d00-4e68-11ea-9ae5-ae4553ae451d.png)
烦请各路大佬指点一二，不胜感激。

**Comment by zhuyouzhufu** [comment]
杭州主服务器127条数据，深圳从服务器275条数据。同一张表。

**Comment by zhuyouzhufu** [comment]
说明一下，我没有在从数据库操作过nacos-config的数据库(写操作)，全部是在页面上进行配置的修改

**Comment by zhuyouzhufu** [comment]
我的nacos-server容器已经使用了7周，从服务器最后一次记录是2019年1月20日
![image](https://user-images.githubusercontent.com/34908518/74405915-4d155e00-4e69-11ea-9fdc-2150f22f84d6.png)
![image](https://user-images.githubusercontent.com/34908518/74406121-bbf2b700-4e69-11ea-8a17-21e985f4993b.png)

**Comment by zhuyouzhufu** [comment]
docker的nacos版本为1.1.4

**Comment by paderlol** [comment]
这个问题是由于程序里面检测到master不可用 然后就切换到slave了,所以造成了这个问题,我在nacos-docker镜像里面做了主从镜像,当时是为了演示这个能力,这个其实生产会出现你这个问题,就是切到从后导致主的数据比从少,出现数据不一致的问题,所以建议改成配一台就好,后续版本会去掉这个配置两个数据库的功能的。
