### ISSUE TITLE
Nacos怎么实现像Ribbon的listOfServers功能

### ISSUE THREAD

**Issue by Kumilo** [alibaba/nacos#2363]
Nacos怎么实现像Eureka一样的listOfServers功能,以便我本地服务可以和DEV环境服务交互，
否则我得本地启动全套微服务注册到Nacos，要么将本地服务注册到DEV，然后调用DEV环境其他服务。非常麻烦~

**Comment by chuntaojun** [comment]
这个是负载均衡Ribbon实现的？直接固定某一些服务的访问ip信息

**Comment by chuntaojun** [comment]
可以看下这里，这个可能不是nacos所负责的，https://blog.csdn.net/wangmx1993328/article/details/95513359

**Comment by Kumilo** [comment]
使用nacos时，这样配置是无用的，所以感觉使用nacos最不方便的就是这点
stores:
  ribbon:
    listOfServers: example.com,google.com

**Comment by nkorange** [comment]
这个需要spring-cloud-alibaba适配ribbon来支持你的这个配置，可以到spring-cloud-alibaba提交你的问题
