### ISSUE TITLE
nacos防止恶意注册

### ISSUE THREAD

**Issue by xuqingyangjsti** [alibaba/nacos#2366]
请问什么时候，哪个版本支持防恶意注册，即服务端增加鉴权，简单密码验证也可以，谢谢，非常感谢

**Comment by ZShUn** [comment]
可以先试用一下1.2.0beat版本

**Comment by paderlol** [comment]
你说的是在注册的时候需要白名单或者带上token鉴权，类似于consul这种是吗？

**Comment by DemonsIT** [comment]
我这边也有这个问题,希望有人可以回答一下

**Comment by DemonsIT** [comment]
> 你说的是在注册的时候需要白名单或者带上token鉴权，类似于consul这种是吗？

是的,就是可以控制哪些服务可以注册,哪些不可以注册
