### ISSUE TITLE
which version of 'nacos client' and 'nacos server'   does attribute 'spring.cloud.nacos.config.shared-configs'  take effect in?

### ISSUE THREAD

**Issue by aileennian** [alibaba/nacos#2368]
## Issue Description
which version of 'nacos client' and 'nacos server'   does attribute 'spring.cloud.nacos.config.shared-configs'  take effect in?

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
bootstrap.properties
spring.cloud.nacos.config.shared-configs=redis.properties,xxx-common.properties

pom.xml
       <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>${spring-cloud-alibaba-nacos.version}</version>
        </dependency>

        @NacosProperty("amount")
        private String amount;

### Describe what you expected to happen
'amount' is in xxx-common.properties but cannot get the value;

Replace ''@NacosProperty("amount")' to '@NacosProperty("amount")' or '@NacosValue("amount")' ...and the result is the same

### How to reproduce it (as minimally and precisely as possible)
1. 
2. 
3. 

### Tell us your environment
nacos server 1.nacos-server-1.1.4
spring-cloud-starter-alibaba-nacos-config: 2.2.0.RELEASE
spring.cloud.nacos.config.server-addr=127.0.0.0:8848
spring.cloud.nacos.config.shared-configs=redis.properties,xxx-common.properties

**Comment by aileennian** [comment]
I try to replace "${amount}" with "amount" but result is the same yet.

**Comment by chuntaojun** [comment]
现在nacos的注解在spring-cloud-alibaba还不支持，后期会进行整合，请关于spring-cloud-alibaba-nacos的动态
