### ISSUE TITLE
Nacos support other famous RDBMS,for example oracle database

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#237]
一般预生产和生产上 cluster_mode时，是必须支持MySQL 或者 RDS 这种的。 支持Oracle这个是个好想

法，后面我们可以支持数据存储的扩展。

_Originally posted by @pguo65535 in https://github.com/alibaba/nacos/issue_comments#issuecomment-436607517_

**Comment by yanlinly** [comment]
存储层后续好了jpa这样跟数据库无关的框架，以便有更好的扩展性，支持更多的存储类型。
