### ISSUE TITLE
com.alibaba.nacos.naming.misc.GlobalConfig taskDispatchPeriod 参数初始值疑问

### ISSUE THREAD

**Issue by sortaxie** [alibaba/nacos#2370]
package com.alibaba.nacos.naming.misc;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Stores some configurations for Distro protocol
 *
 * @author nkorange
 * @since 1.0.0
 */
@Component
public class GlobalConfig {

    @Value("${nacos.naming.distro.taskDispatchPeriod:200}")
    private int taskDispatchPeriod = 2000;

    @Value("${nacos.naming.distro.batchSyncKeyCount:1000}")
    private int batchSyncKeyCount = 1000;

    @Value("${nacos.naming.distro.syncRetryDelay:5000}")
    private long syncRetryDelay = 5000L;

为什么 taskDispatchPeriod = 2000;  跟@Value("${nacos.naming.distro.taskDispatchPeriod:200}") 默认值不一样，而下面几个参数却都是相同的？

**Comment by zhixiangyuan** [comment]
可能是写错了，默认是应该是 200，已提交 PR
