### ISSUE TITLE
为什么名称空间下的配置，只能创建两百个，如果超出200个应用呢

### ISSUE THREAD

**Issue by baimoer** [alibaba/nacos#2372]
## Issue Description
Why can only 200 configurations be created under the namespace, if there are more than 200 applications

为什么名称空间下的配置，只能创建两百个，如果超出200个应用呢

**Comment by lyg945** [comment]
我也有这个疑问，但是发现之前都有人问过这个问题了，也给了回复：请看这个https://github.com/alibaba/nacos/issues/1694
目前这个数量的限制并不会工作，这个将来功能完善后，是可以进行扩容的。
