### ISSUE TITLE
When using the historical version configuration, this configuration will be lost

### ISSUE THREAD

**Issue by Yogurt-lei** [alibaba/nacos#2374]
## Issue Description 
When using the historical version configuration, this configuration will be lost

Type: *bug report*

### Describe what happened (or what feature you want)
When using the historical version configuration, this configuration will be lost

### Describe what you expected to happen
When using a historical version configuration, the configuration will roll back correctly

### How to reproduce it (as minimally and precisely as possible)
1. add a config
2. do some change and publish
3. try to roll back to historical version

### Tell us your environment
Version NACOS1.1.4 standalone mode
DB: Mysql

**Comment by ZShUn** [comment]
1.2.0beat already fixed

**Comment by Yogurt-lei** [comment]
@ZShUn thx a lot, i find the released **1.2.0-beta.0(Feb 5th, 2020)** has resolved the bug. this question is  same with [https://github.com/alibaba/nacos/issues/434](url)
