### ISSUE TITLE
使用导入配置，微服务启动加载不完整。With import configuration, the microservice startup load is incomplete.

### ISSUE THREAD

**Issue by Ronaltn** [alibaba/nacos#2375]
#Issue Description
Type: *bug report* 

### Describe what happened (or what feature you want)
在nacos配置列表中导入2个新配置，其中A配置是B配置的ext-config。当B配置对应的微服务启动时，未加载到A配置。
Import 2 new configurations into the nacos configuration list, where configuration A is ext-config of configuration B. When the microservice corresponding to the configuration B is started, it is not loaded into the configuration A.

### Describe what you expected to happen
导入新配置后，微服务启动应加载所有层级的配置。
After importing the new configuration, the microservice startup should fully load the configuration at all levels.

### Tell us your environment
nacos 1.1.4
spring-cloud-alibaba 2.1.1.RELEASE

**Comment by chuntaojun** [comment]
能够提供下spring-cloud-alibaba的相关配置文件信息吗？

**Comment by Ronaltn** [comment]
> 能够提供下spring-cloud-alibaba的相关配置文件信息吗？

配置信息就是很常规的yaml信息。
