### ISSUE TITLE
无法获取下线nacos服务

### ISSUE THREAD

**Issue by yqbboy** [alibaba/nacos#2378]
#1552  Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

我的某个服务注册到nacos后，我在手动停止该服务，然后使用“namingService.selectInstances(serviceName, false)” 该API无法返回下线的nacos服务。并且我使用类似其他API 也获取不到。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
项目依赖的包是
<dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>nacos-discovery-spring-boot-starter</artifactId>
      <version>0.2.3</version>
</dependency>

### Anything else we need to know?
我使用nacos版本是1.1.4，docker单机版部署

**Comment by zhixiangyuan** [comment]
您的这个问题在 [issue 1777](https://github.com/alibaba/nacos/issues/1777) 中被修复了，但是当时添加进去的 enableOnly 选项处于未知的原因被删除了，关于删除该选项的原因还需要咨询一下大牛 @nkorange

**Comment by chuntaojun** [comment]
The code did not merge because the conflict was not resolved

**Comment by zhixiangyuan** [comment]
@i will solve it@

**Comment by chuntaojun** [comment]
ok, your contribution is welcome

**Comment by zhixiangyuan** [comment]
Click the wrong button, canceled the assign, please reassign. @chuntaojun

**Comment by zhixiangyuan** [comment]
已提交 pr，现在可以通过向 NamingService 注册监听器来感知服务摘除事件，下面是一段示例代码。

```java
        NamingService.subscribe(serviceName, event -> {
            if (event instanceof NamingRemoveEvent) {
                // do some
            }
        });
```

**Comment by zhegexiaohuozi** [comment]
预计哪个正式版本会支持，期待这个功能
