### ISSUE TITLE
github 上 release 下载不了

### ISSUE THREAD

**Issue by maxiaodong58** [alibaba/nacos#2382]
可否挂一个国内镜像

**Comment by token01** [comment]
是不是考虑弄一个代理

**Comment by Ronaltn** [comment]
> 是不是考虑弄一个代理

gitee上看看有没有release可直接下载

**Comment by token01** [comment]
https://gitee.com/mirrors/Nacos/releases

**Comment by penghao03** [comment]
> https://gitee.com/mirrors/Nacos/releases

gitee是来搞笑的吗，下的压缩包是源码

**Comment by nkorange** [comment]
可以加钉钉群21708933，群文件里有最新部署包。当然从源码构建也是很推荐的。
