### ISSUE TITLE
Using nacos config results in Failed to configure a DataSource: 'url' attribute

### ISSUE THREAD

**Issue by LuciferZK** [alibaba/nacos#2383]
### Describe what happened (or what feature you want)
    Description:
    
    Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
    
    Reason: Failed to determine a suitable driver class

### Describe what you expected to happen
**Using nacos config as the configuration center, I expect to be able to read mysql data source information normally**

### Tell us your environment
1.Use mysql-connector-java 5.1.6, mybatis-plus-boot-starter 3.3.1
2.Newly created bootstrap.yml, content:
```json
spring:
  application:
    name: service-product
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 
        file-extension: yaml 
  profiles:
    active: dev 
```
3.Configuration file name in the nacos configuration list: service-product-dev.yaml

**Comment by token01** [comment]
升级一下nacos 版本试试

**Comment by andyzhaozhao** [comment]
请问解决了吗，我也遇到同样的问题

**Comment by SimonVampire** [comment]
同样遇到这样的问题

**Comment by pkaq** [comment]
同样的问题
