### ISSUE TITLE
decompressing zip file failed

### ISSUE THREAD

**Issue by Nicqiang** [alibaba/nacos#2385]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
export selected configs, but decompressing the zip file failed. 
![image](https://user-images.githubusercontent.com/22723887/75142241-a31db780-572d-11ea-8deb-7c13c2879853.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos: v.1.1.3
server: center os 7u
client: mac os catalina
browser: chrome 80.0

**Comment by token01** [comment]
升级新版 试试 nacos >=1.1.4
