### ISSUE TITLE
mysql database driver dependency version is too low

### ISSUE THREAD

**Issue by Hongpei-Chen** [alibaba/nacos#2386]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

Startup failed，if use mysql8.x
### Describe what you expected to happen
Startup successful

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
centos7
jdk7
mysql8.x

**Comment by token01** [comment]
User nacos  what version？

**Comment by token01** [comment]
https://github.com/alibaba/nacos/issues/1185

**Comment by Hongpei-Chen** [comment]
1.1.4

**Comment by chuntaojun** [comment]
确实，在issue 1185已说明如何解决mysql驱动低的问题
