### ISSUE TITLE
关于nacos1.2.0用户体验优化建议

### ISSUE THREAD

**Issue by xiaoyao1999hn** [alibaba/nacos#2388]
如题：
1.用户这里能否直接在后面给个授权按钮，点击后直接弹框给选将角色；
2.角色和权限能否放一起而不是隔离，创建角色的时候还要手填账号很奇怪；
3.用户列表里面是否能加多2列，一是用户所拥有的角色，另外一行是他拥有的权限汇总信息
4.namespace能否做成可搜索下拉框的形式展示，如果namespace太多切换查找比较麻烦

**Comment by nkorange** [comment]
@loadchange 请酌情考虑是否有必要优化
