### ISSUE TITLE
灰度发布问题

### ISSUE THREAD

**Issue by 18207556302** [alibaba/nacos#2392]
beta发布，用具体的IP有如下问题：
1.docker后没有具体的IP可以灰度
2.配置编辑后希望有一个“保存“的状态。保存后再点“生效”，而不是编辑后必须发布。这个在发版时非常重要。

**Comment by chuntaojun** [comment]
I think the second optimization would be a good user experience，What do you think?@nkorange

**Comment by 18207556302** [comment]
其实这个问题不光是添加一个保存状态的事情，试想如下场景：
应用A本次上线有配置变更，一般发版时操作如下（假如有保存状态）：
1.发版前在nacos的配置中心找到应用A使用的配置文件假设m.properties.修改m.properties保存，不发布。
2.正式发版前，将刚刚修改的m.properties文件由保存状态改成发布，此时开始发版。
3.所有A应用的实例正常发版完成。都消费新的配置文件。修改配置生效，成功升级。
上面布置3中，出现如下情况将会导致异常：
(1).如果A应用的实例比较多，发版需要一些时间，比如10个实例，发版需要半个小时，这时对于还没有发版的A应用的实例使用修改后发布的m.properties就可能出现问题。
(2)考虑发版失败，代码需要回退的情况（假如10个实例，已经发了5个实例，此时遇到异常需要回退代码），如何保证不同代码的实例取到正确的配置。此时不管你配置是否回滚，都会有一半的实例会出现配置问题。
