### ISSUE TITLE
NacosConfigListener获取动态配置YML怎么转成Properties格式

### ISSUE THREAD

**Issue by chenjianshuo** [alibaba/nacos#2393]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
获取动态配置如下

  @(dataId = "spring-nacos-demo.yml",type = ConfigType.YAML)
    public void onRecive(Properties value){
        System.out.println("Properties："+ value);
    }
打印：Properties：{weixin=, api=http://172.25.63.72:8080/weix, alarm=}

    @NacosConfigListener(dataId = "spring-nacos-demo.yml",type = ConfigType.YAML)
    public void onRecive(String value){
        System.out.println("String："+ value);
    }
打印：String：alarm:
              weixin:
    api: http://172.25.63.72:8080/weix

### Describe what you expected to happen

想打印 alarm.weixin.api:http://172.25.63.72:8080/weix

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
   <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.4</version>
        </dependency>

**Comment by chuntaojun** [comment]
you can see here：https://github.com/nacos-group/nacos-spring-project/issues/189

**Comment by esolve** [comment]
你是spring-cloud用吗？
nacos-client用的什么版本
这个监听器能起作用？
