### ISSUE TITLE
nacos 1.2.0beta0 - 登录账户密码

### ISSUE THREAD

**Issue by ringyee** [alibaba/nacos#2397]
您好，更新到1.2.0 beta 0 版本后，发现访问xxxx/nacos后，直接进就如首页了，不需要输入登录用户名和登录密码，而且，进入首页后，右上角也没有用户的按键（在1.1.3版本里面可以点击后，修改密码和退出），是这个版本去除登录功能了吗？

ps，用1.1.3的时候是ok的。

**Comment by leakey8612** [comment]
把浏览器缓存清除一下，好像新旧版本的静态文件有冲突

**Comment by mikefreemanNice** [comment]
配置 nacos.core.auth.enabled=true

**Comment by chuntaojun** [comment]
新的版本中，如果没有开启权限控制，默认是不存在登陆这一流程了，只有开启了权限控制之后，才会开启登陆这一流程
