### ISSUE TITLE
日志强依赖问题

### ISSUE THREAD

**Issue by yfh0918** [alibaba/nacos#240]
目前系统只支持有限的日志比如
com.alibaba.nacos.client.logger.LoggerFactory支持的几种日志适配器
建议是否把com.alibaba.nacos.client.logger.LoggerFactory修改成org.slf4j.LoggerFactory
或者尽可能的兼容目前主流日志模块，比如log4j等等

**Comment by yfh0918** [comment]
目前，只支持log4j-slf4j-impl ，后面希望能支持slf4j-log4j12

**Comment by hxy1991** [comment]
log4j-slf4j-impl  是 slf4j 转接到 log4j 2 的日志输出框架。

slf4j-log4j12 是 slf4j 转接到 log4j 1.x 的日志输出框架 ，而 log4j 1.x 已经在 2015 年 8 月就停止更新了。

[log4j 官方建议升级到 log4j 2](http://logging.apache.org/log4j/1.2/index.html)

**Comment by DoubleFooker** [comment]
目前看到0.2.1是支持的

**Comment by Battleloop** [comment]
:smile:

**Comment by shook2012** [comment]
nacos-client 对log4j2版本依赖太强了。实测spring-cloud-alibaba-nacos-config0.1.1Release   log4j2为2.7+，就没法实例化nacos client了。因为LogUtils  line:52 activeAppenderWithSizeRolling 调用的log4j2 中RollingFileAppender接口的方法调整了
