### ISSUE TITLE
不能退出登录，且修改密码后不能登录

### ISSUE THREAD

**Issue by silloy** [alibaba/nacos#2405]
版本：NACOS1.2.0-SNAPSHOT
通过官网提供的办法修改密码后，退出按钮消失

且修改密码不生效，原有密码也会失效

**Comment by mikefreemanNice** [comment]
配置 nacos.core.auth.enabled=true

**Comment by silloy** [comment]
添加配置后页面直接501了......can't get: /nacos 大概是这样

**Comment by silloy** [comment]
我访问 http://nacos.itcore.com.cn/nacos/#/login 进入登录页面了，但 使用nacos/nacos 报登录错误，这个我应该怎么处理，没有改过密码

**Comment by mikefreemanNice** [comment]
可以看下1.2.0 release， 默认没有登录页，nacos.core.auth.enabled默认设置为false
