### ISSUE TITLE
Why can't I access nacos with Edge browser为什么用Edge浏览器无法访问nacos

### ISSUE THREAD

**Issue by Ronaltn** [alibaba/nacos#2407]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Use the Edge browser to access the nacos console and prompt Request error, please try again later
用Edge浏览器访问nacos控制台，提示Request error,please try again later 
![微信截图_20200304124047](https://user-images.githubusercontent.com/6178643/75845876-6af53380-5e15-11ea-89f1-1203403b8ed2.png)
Using Google Chrome works fine
使用谷歌浏览器就正常

### Tell us your environment
Microsift Edge 80.0.361.62
NACOS1.2.0-beta.0

**Comment by chuntaojun** [comment]
请清空下LocalStorage里面的数据信息即可

**Comment by Ronaltn** [comment]
> 请清空下LocalStorage里面的数据信息即可

I'm fine
