### ISSUE TITLE
1.2.0 schema.sql 和 nacos-mysql.sql 的区别是什么？

### ISSUE THREAD

**Issue by silloy** [alibaba/nacos#2411]
最新版本 1.2.0 下有两个sql文件，schema.sql 和 nacos-mysql.sql 的区别是什么？我看主要区别是数据库名称不一样，如何正确使用这两个sql文件，因为我是从1.0升级到1.2的，sql 如何升级

**Comment by chuntaojun** [comment]
schema.sql 是单机模式下使用的，无需关心它；nacos-mysql.sql 是集群下模式使用的，需要用这个来初始化MySQL数据库

**Comment by wangjia2016** [comment]
![image](https://user-images.githubusercontent.com/16084076/105678961-b8482b00-5f28-11eb-8494-3ad854ecf911.png)
@chuntaojun 写反了吧 这个文档上面 nacos-mysql.sql 是单机模式下用的

https://nacos.io/zh-cn/docs/deployment.html

**Comment by yjqg6666** [comment]
建议这两个sql文件还是修改一下文件名， 这样比较直观。
