### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by GithubLiujian** [alibaba/nacos#2412]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Please look at the configuration （yaml）:
```
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS-HOST}:${NACOS-PORT}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-dataids: >
          common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension},
          redis-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        refreshable-dataids: >
          common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension},
          redis-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
```
Run with the following erro（There are the same mistakes when using "> -"）:
![image](https://user-images.githubusercontent.com/46477928/75946827-229f4980-5ed9-11ea-82ac-70718e9743a1.png)

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/46477928/75954341-710b1300-5eee-11ea-8c17-ddbe47c5f074.png)

When I query yaml's documents, when it comes to line breaking, they will be replaced by spaces.
But I checked the source code （com.alibaba.nacos.client.config.utils.ParamUtils）, But it seems that spaces are not supported.
![image](https://user-images.githubusercontent.com/46477928/75954764-6309c200-5eef-11ea-9c25-99f8a8e97edd.png)

![image](https://user-images.githubusercontent.com/46477928/75954523-d9f28b00-5eee-11ea-884f-4d853eb1c4e2.png)
![image](https://user-images.githubusercontent.com/46477928/75954630-1b833600-5eef-11ea-8c44-200929df7076.png)

Can you support ‘> -‘ or ‘>’, please?
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.1.4
spring cloud alibaba 2.1.1.RELEASE
spring cloud Greenwich.SR5

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1257](https://github.com/alibaba/spring-cloud-alibaba/issues/1257) via [**ZenHub**](https://www.zenhub.com/)
