### ISSUE TITLE
nacos occupies too high cpu under win10

### ISSUE THREAD

**Issue by GeekBud** [alibaba/nacos#2413]
## Issue Description

Because of the development needs, by starting nacos locally to simulate the online environment (Win10), when the nacos startup time is more than 30 minutes, the cpu occupancy rate will reach 80% ~ 90%, until the last occupation. This problem exists in both 1.1.3 and 1.1.4. I thought it would be resolved when the 1.1.4 version was released, but it didn't.

Type: *bug report*

### Tell us your environment
nacos 1.1.1
nacos 1.1.4
win10

### Anything else we need to know?

I don't have the ability to trace the cause of the problem, but I would be happy if I can assist you

**Comment by chuntaojun** [comment]
Is it about NIO threads?

**Comment by chuntaojun** [comment]
you can see here : https://github.com/alibaba/nacos/issues/1928
