### ISSUE TITLE
nacos客户端和服务端1.1.4，调用成功但是订阅者列表没有数据，请问什么原因

### ISSUE THREAD

**Issue by DraperChen** [alibaba/nacos#2414]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
关于订阅者列表的查询，是需要手动输入查询条件才可以的

**Comment by pi-chow** [comment]
> 关于订阅者列表的查询，是需要手动输入查询条件才可以的

刚才试了下1.2.0的也是，这个设定太奇怪了~

**Comment by yuanjinzhong** [comment]
我也想知道，订阅者列表没数据 是啥情况

https://github.com/alibaba/nacos/issues/2717

**Comment by xw-zzz** [comment]
我也是一脸懵逼
