### ISSUE TITLE
using 127.0.0.1:8848/nacos to access nacos web, prompt: Request error, please try again later!

### ISSUE THREAD

**Issue by chemphern** [alibaba/nacos#2417]
Update to new version 1.2.0, using 127.0.0.1:8848/nacos access prompt: Request error, please try again later!
Use local IP or localhost instead of 127.0.0.1, such as 192.168.1.20:8848/nacos,localhost:8848/nacos ,it work!
it is bug?

**Comment by chuntaojun** [comment]
Clear the browser's LocalStorage data

**Comment by chemphern** [comment]
Thankyou，it is ok!
