### ISSUE TITLE
Import nacos-client has ${project.version} property cause service startup failure

### ISSUE THREAD

**Issue by Beckylbj** [alibaba/nacos#2418]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
A springboot project import nacos-client 1.1.4，using maven package and 'java -jar' startup service failure, the exception is java.lang.IllegalArgumentException:Could not resolve placeholder 'project.version' in value "${project.version}".

### Describe what you expected to happen
Expect nacos-client and nacos-api delete the application.properties file or delete the vesion=${project.version} property.

### How to reproduce it (as minimally and precisely as possible)

1. A maven project using springboot 1.5.16.RELEASE.
2. Defined nacos-client dependency in pom.xml. 
![image](https://user-images.githubusercontent.com/30460887/76047832-ecc49880-5f9e-11ea-8ce3-99416ce536e7.png)

3. The maven project add plugin to exclude configuration files under classes when packaging jar.
![image](https://user-images.githubusercontent.com/30460887/76047807-e2a29a00-5f9e-11ea-8ab4-b62fba440fc3.png)

4. Using 'java -jar' startup the packaged jar.

### Tell us your environment
springboot 1.5.16.RELEASE
nacos-client 1.1.4

**Comment by Beckylbj** [comment]
maven plugin:
![image](https://user-images.githubusercontent.com/30460887/76047774-cdc60680-5f9e-11ea-9a24-28d36a59b635.png)

**Comment by Fengxq2014** [comment]
这个问题没有修复的打算吗？应用配置文件扫描会有问题
