### ISSUE TITLE
Discussion: Using Zookeeper to do the pain and coolness of Dubbo Registration Center & Configuration Center

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#242]
Discussion: Using Zookeeper to do the pain and coolness of Dubbo Registration Center & Configuration Center

讨论：用Zookeeper做Dubbo注册中心&配置中心的痛与爽

### Pain：
Performance problem
Difficulties in troubleshooting
Weak traffic scheduling

性能问题
排查问题困难
流量调度弱

### Cool：
More people used in the early days
Product stability

早期用的人比较多
产品稳定

**Comment by yfh0918** [comment]
Pain
经常莫名其妙出现连接失败等问题

Cool
简单好用

**Comment by chocod** [comment]
Pain
跨语言问题，跨语言使用不方便，需要二次开发

**Comment by 356082462** [comment]
1、zk无法进行异地多活部署，要实现注册中心的异地多活，需要部署至少2个zk集群。
2、将服务注册到多个独立的zk注册中心，服务的调整是通过调整zk中的内容实现的，调整一个服务至少需要调整2个zk中内容。造成服务治理系统研发难度高风险大，服务治理工作展开难度变大，运维管控等系统对接困难。
3、在服务节点数多的场景下，频繁修改服务配置内容，造成推送风暴，不稳定。无法应对1111这样的商业活动。
4、服务注册、服务发现、配置变更接口不统一、不同的微服务技术体系服务融合困难。
总之无法包容过去、也无法过好当下，更展望不了未来。

**Comment by superamily** [comment]
nacos什么时候支持dubbo?




发自网易邮箱大师
在2018年11月08日 14:37，zetas 写道：

1、zk无法进行异地多活部署，要实现注册中心的异地多活，需要部署至少2个zk集群。
2、将服务注册到多个独立的zk注册中心，服务的调整是通过调整zk中的内容实现的，调整一个服务至少需要调整2个zk中内容。造成服务治理系统研发难度高风险大，服务治理工作展开难度变大，运维管控等系统对接困难。
3、在服务节点数多的场景下，频繁修改服务配置内容，造成推送风暴，不稳定。无法应对1111这样的商业活动。
4、服务注册、服务发现、配置变更接口不统一、不同的微服务技术体系服务融合困难。
总之无法包容过去、也无法过好当下，更展望不了未来。

**Comment by yanlinly** [comment]
@superamily  0.6.0版本（月底正常能放出去）支持dubbo，目前对接基本完成。

**Comment by Loveugirl** [comment]
Pain
多租户支持
多园区高可用

> @superamily 0.6.0版本（月底正常能放出去）支持dubbo，目前对接基本完成。

Nacos是否支持与zookeeper的无缝衔接

**Comment by yanlinly** [comment]
> 1、zk无法进行异地多活部署，要实现注册中心的异地多活，需要部署至少2个zk集群。
你异地多活是什么意思？  
目前云计算的模型中一个Region之间多个AZ容灾我们一般叫同城容灾能力，一个城市的一个可用区出问题，另外可用区保证服务可用。
多个Region之间的容灾切流能力叫异地多活。一个Region出问题，把流量切走。

你的异地多活跟我理解的一样吗？

**Comment by yanlinly** [comment]
Nacos 0.6.0 has supported dubbo.
https://github.com/alibaba/nacos/releases/tag/0.6.0
