### ISSUE TITLE
0.8.0 how to update to 1.2.0 如何升级

### ISSUE THREAD

**Issue by justyida** [alibaba/nacos#2421]
###生产在跑的3台服务器是0.8.0的，需要升级解决权限管理问题。
###请问平滑升级的模式是啥？下面步骤是否正确？

### 1.新增naco_config数据库的permissions表
CREATE TABLE `permissions` (
  `role` varchar(50) NOT NULL,
  `resource` varchar(512) NOT NULL,
  `action` varchar(8) NOT NULL,
  UNIQUE KEY `uk_role_permission` (`role`,`resource`,`action`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

###2.备份并替换{nacos.home}/target/nacos-server.jar，逐台重启即可？？？

**Comment by chuntaojun** [comment]
yes，you can see here：https://nacos.io/zh-cn/blog/nacos%201.2.0-beta.0.html
