### ISSUE TITLE
初始化nacos.discovery.server-addr的逻辑判断问题

### ISSUE THREAD

**Issue by birkhoff-liu** [alibaba/nacos#2425]
NacosDiscoveryProperties.java line:192
具体逻辑代码：if (serverAddr.lastIndexOf("/") != -1) {
			serverAddr = serverAddr.substring(0, serverAddr.length() - 1);
		}
希望该判断逻辑加入非"/"结束

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1234](https://github.com/alibaba/spring-cloud-alibaba/issues/1234) via [**ZenHub**](https://www.zenhub.com/)
