### ISSUE TITLE
修改配置nacos.core.auth.enabled=true后，注册服务时提示failed to req API:127.0.0.1:8848/nacos/v1/ns/instance. code:403

### ISSUE THREAD

**Issue by bingxe-fengbenwu** [alibaba/nacos#2426]
修改配置nacos.core.auth.enabled=true后，注册服务时提示failed to req API:127.0.0.1:8848/nacos/v1/ns/instance. code:403，我该如何解决，spring-cloud-starter-alibaba-nacos-discovery中并没有找到配置用户名和密码的配置

**Comment by ZShUn** [comment]
如果是使用nacos1.2.0，那么可能spring cloud alibaba 并没有支持到该版本。

**Comment by ZShUn** [comment]
nacos1.2.0 开启nacos.core.auth.enabled=true后，需要在client端设置用户名密码获取到jwt后才能访问

**Comment by bingxe-fengbenwu** [comment]
是nacos1.2.0，我现在client端无法设置用户名密码，nacos.security.ignore.urls设置跳过鉴权有感觉和不设置nacos.core.auth.enabled=false没啥区别，有其他的解决方法吗

**Comment by chuntaojun** [comment]
目前其生态组件尚未正式支持nacos-client 1.2.0，所以请耐心等待下，预计这两周之内会发布

**Comment by izrh** [comment]
同样遇到这个问题，找了半天，原来是还没有支持，希望快点支持吧，支持nacos，支持阿里巴巴

**Comment by izrh** [comment]
> 
> 
> 如果是使用nacos1.2.0，那么可能spring cloud alibaba 并没有支持到该版本。

那有哪个版本是支持用properties配置自定义账号密码的吗？我先换个版本用一下

**Comment by chuntaojun** [comment]
> > 如果是使用nacos1.2.0，那么可能spring cloud alibaba 并没有支持到该版本。
> 
> 那有哪个版本是支持用properties配置自定义账号密码的吗？我先换个版本用一下？怎么配置还麻烦说一下。

那边pr已经提了，估计就这一两周之内，感谢支持～

**Comment by izrh** [comment]
> 
> 
> > > 如果是使用nacos1.2.0，那么可能spring cloud alibaba 并没有支持到该版本。
> > 
> > 
> > 那有哪个版本是支持用properties配置自定义账号密码的吗？我先换个版本用一下？怎么配置还麻烦说一下。
> 
> 那边pr已经提了，估计就这一两周之内，感谢支持～

我到时候怎么样获得最新的支持，是更新spring-cloud-alibaba-dependencies的version吗？新版发布之后会在哪里公布？

**Comment by nkorange** [comment]
> > > > 如果是使用nacos1.2.0，那么可能spring cloud alibaba 并没有支持到该版本。
> > > 
> > > 
> > > 那有哪个版本是支持用properties配置自定义账号密码的吗？我先换个版本用一下？怎么配置还麻烦说一下。
> > 
> > 
> > 那边pr已经提了，估计就这一两周之内，感谢支持～
> 
> 我到时候怎么样获得最新的支持，是更新spring-cloud-alibaba-dependencies的version吗？新版发布之后会在哪里公布？

请关注：https://github.com/alibaba/spring-cloud-alibaba 的发布计划，这个issue先关闭

**Comment by 375273058** [comment]
cluster.conf 把内容换成你本机地址服务就可以注册了,用户名和密码你自己修改mysql数据库PasswordEncoderUtil这工具类可以修改你想要的密码

**Comment by jhz820616** [comment]
> cluster.conf 把内容换成你本机地址服务就可以注册了,用户名和密码你自己修改mysql数据库PasswordEncoderUtil这工具类可以修改你想要的密码

所答非所问

**Comment by 375273058** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jhz820616"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午3:28
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"飓丰软件"<375273058@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] 修改配置nacos.core.auth.enabled=true后，注册服务时提示failed to req API:127.0.0.1:8848/nacos/v1/ns/instance. code:403 (#2426)





  
cluster.conf 把内容换成你本机地址服务就可以注册了,用户名和密码你自己修改mysql数据库PasswordEncoderUtil这工具类可以修改你想要的密码
  
所答非所问
