### ISSUE TITLE
Bug in the definition of data synchronization time

### ISSUE THREAD

**Issue by pengzhengfa** [alibaba/nacos#2428]
The definition of data synchronization time is not very standard. It should be a small bug
<img width="857" alt="1" src="https://user-images.githubusercontent.com/33858082/76141363-55466f00-609e-11ea-8c31-489a92dbf5ec.png">

**Comment by chuntaojun** [comment]
already fix，you can see this pr ：https://github.com/alibaba/nacos/pull/2381
