### ISSUE TITLE
问：新版去掉了密码登录了吗

### ISSUE THREAD

**Issue by NalHoug** [alibaba/nacos#2430]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
最新版本的登陆和权限控制绑在一起了，只有开启了权限控制才能够启用登陆功能

**Comment by liuuuu-pro** [comment]
conf/application.properties中nacos.core.auth.enabled默认为false，需要手动改为true

**Comment by aaroncgt90** [comment]
> 最新版本的登陆和权限控制绑在一起了，只有开启了权限控制才能够启用登陆功能

最新版本用localhost去访问会报错

**Comment by weiweihaha** [comment]
standalone-mysql-8，应该怎么修改配置文件才可以密码登录呢，nacos.core.auth.enabled=true也没有成功，有成功的分享下经验呗

**Comment by nkorange** [comment]
> standalone-mysql-8，应该怎么修改配置文件才可以密码登录呢，nacos.core.auth.enabled=true也没有成功，有成功的分享下经验呗

参考：https://nacos.io/zh-cn/blog/nacos%201.2.0-beta.0.html
