### ISSUE TITLE
nacos should not only support mysql

### ISSUE THREAD

**Issue by yangliu817** [alibaba/nacos#2434]
can you make nacos use jpa or hibernate as orm for support to other database manage system?

**Comment by yangliu817** [comment]
our production environment dbms is oracle, but we must consider our app support to mysql, plsql and more.

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2461

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2818

**Comment by dylan-tao** [comment]
目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb
