### ISSUE TITLE
[bug] can't find history config

### ISSUE THREAD

**Issue by sunny5541** [alibaba/nacos#2435]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

on `Historical Versions` page ,input Data ID and Group then click search .Can't find history version config ,and the web return a white screen. Same on chrome and firefox.

在历史版本的页面输入id和group后不能正常搜索配置文件的历史版本，在配置列表页面的条目后方点击更多和历史版本也不能正常显示，都会显示一个白屏。在chrome 和 firefox 是一样的结果

### Describe what you expected to happen

The configuration history can be displayed normally and the rollback function can be used

能正常显示配置的历史记录并且能使用回滚功能

### How to reproduce it (as minimally and precisely as possible)

1. 在配置列表界面 public 命名空间创建一个配置 dataid 为 test1  ，group 为 test ，格式是 TEXT 。(create a config)
2. 然后点击编辑，更新配置内容并保存(update it)
3. 然后点击条目后方的更多和历史版本，会显示白屏(show history,and return white screen)

### Tell us your environment

nacos=1.2.0
OS=Debian GNU/Linux 10
chrome=79.0

**Comment by shook2012** [comment]
遇到同样的问题

**Comment by shook2012** [comment]
@nkorange

**Comment by afewnotes** [comment]
同1.2.0版本，刚装好无法查看历史；第一次使用就碰到这种问题，对用户伤害太大

**Comment by wangtao19911111** [comment]
I had the same problem

**Comment by nkorange** [comment]
合并到 #2453
