### ISSUE TITLE
开启验证后，获取config返回403

### ISSUE THREAD

**Issue by BurningBing** [alibaba/nacos#2439]
当nacos开启验证后，使用springcloudalibaba 2.2.0获取配置时会返回403，查看源码后发现需要用户名和密码，或者header中设置userAgent，但没找到设置这些的地方，这是bug还是我哪里设置的不对，我的nacos版本是1.2

**Comment by benhot** [comment]
同问

**Comment by michaelmofa** [comment]
我也是这个问题，开启验证之后，服务都注册不上去了，也是报403，大概是服务注册的时候，要去读配置中心的文件，没有权限，所以报错了

**Comment by nkorange** [comment]
spring-cloud-alibaba 暂不支持nacos 1.2.0，可以参考PR：https://github.com/alibaba/spring-cloud-alibaba/pull/1233 进度
