### ISSUE TITLE
控制台不需要登入可直接进入主页面，并且还能修改

### ISSUE THREAD

**Issue by leakey8612** [alibaba/nacos#2443]
版本：1.2.0
问题描述：
nacos.core.auth.enabled=true
已配置
打开http://xxx:8849/nacos，没有跳转到登入页面，而是直接进入主页面，并且右上角不显示用户名，操作配置修改可直接发布成功
背景：由1.1.4升级到1.2.0，页面缓存以及cookie全部删除

**Comment by nkorange** [comment]
完整页面截图看看

**Comment by leakey8612** [comment]
没问题的页面
![没问题页面](https://user-images.githubusercontent.com/26129857/76296690-8a96cb00-62f1-11ea-84d3-9bfa36dcebdd.png)
有问题的页面
![有问题页面](https://user-images.githubusercontent.com/26129857/76296702-8ec2e880-62f1-11ea-8bcf-01d76abfb0d4.png)

**Comment by leakey8612** [comment]
有问题的这个页面，我是直接复制没问题页面的地址，然后打开另外一个浏览器，没有跳转到登入页，直接进去了

**Comment by nkorange** [comment]
能否把浏览器的url发一下

**Comment by wangtao19911111** [comment]
我也有同样问题本地部署不需要登陆
如果配置nacos.core.auth.enabled=true，则服务注册报错

**Comment by leakey8612** [comment]
http://192.168.0.234:8849/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=264020d2-9c2a-467a-a807-4e0f55d6ef9d&namespaceShowName=dev

**Comment by leakey8612** [comment]
> 我也有同样问题本地部署不需要登陆
> 如果配置nacos.core.auth.enabled=true，则服务注册报错

我们这边服务注册倒是没报错，可以正常注册

**Comment by wangtao19911111** [comment]
问下，客户端配置是什么样的，以下是我的配置，同时可否提供下你nacosserver的配置
server.port=18082
spring.application.name=service-provider
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

**Comment by nkorange** [comment]
> > 能否把浏览器的url发一下
> > http://192.168.0.234:8849/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=264020d2-9c2a-467a-a807-4e0f55d6ef9d&namespaceShowName=dev

页面里的所有功能都可用吗？

**Comment by photondragon** [comment]
我也遇到这个问题了，未登录状态下，直接输入以下地址，不会跳转到登录页面：  
https://nacos.example.com/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=

**Comment by liubiaosheng** [comment]
感觉是令牌是jwt 实现， 令牌未过期，因此就算属于登录了

**Comment by nkorange** [comment]
> @nkorange 我也发现这个问题了，未登录状态下，直接输入以下地址，不会跳转到登录页面：
> https://nacos.example.com/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=
> 
> 部署一个全新nacos实例，无需修改任何配置，以单实例运行即可重现。

默认鉴权和登录不开的。

**Comment by leakey8612** [comment]
> @nkorange 我也发现这个问题了，未登录状态下，直接输入以下地址，不会跳转到登录页面：
> https://nacos.example.com/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=
> 
> 部署一个全新nacos实例，无需修改任何配置，以单实例运行即可重现。

都可以的

**Comment by leakey8612** [comment]
> > > 能否把浏览器的url发一下
> > > http://192.168.0.234:8849/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=264020d2-9c2a-467a-a807-4e0f55d6ef9d&namespaceShowName=dev
> 
> 页面里的所有功能都可用吗？

都可以的

**Comment by photondragon** [comment]
> > @nkorange 我也发现这个问题了，未登录状态下，直接输入以下地址，不会跳转到登录页面：
> > https://nacos.example.com/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=
> > 部署一个全新nacos实例，无需修改任何配置，以单实例运行即可重现。
> 
> 默认鉴权和登录不开的。

如果配置nacos.core.auth.enabled=true，则管理页面要登录才能访问，但这个时候微服务全部无法注册

**Comment by nkorange** [comment]
> > > > 能否把浏览器的url发一下
> > > > http://192.168.0.234:8849/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=264020d2-9c2a-467a-a807-4e0f55d6ef9d&namespaceShowName=dev
> > 
> > 
> > 页面里的所有功能都可用吗？
> 
> 都可以的

@loadchange 帮忙看看，是否页面有缓存，但是右上角的账号不显示。

**Comment by 13661411934** [comment]
同 1.1.4 升级到 1.2.0 ， 有这个问题

**Comment by yotoobo** [comment]
我使用 **nacos-docker** 部署 1.2.0 , 是通过设置在compose 配置文件里添加的环境变量 **NACOS_AUTH_ENABLE=true** 来启用(这个变量是在镜像启动脚本里看到的.有一个关于它的if判断). 使用超级管理员登录,但后台左侧没有发现权限管理的菜单项.
![](https://img.pycoder.org/blog/20200314163851.png)

**Comment by fatliy** [comment]
我也遇到上面的问题，也是用的nacos-docker部署的1.2.0，使用env/nacos-standlone-mysql.env里加入NACOS_AUTH_ENABLE=true开启权限，然后在role表里加入ROLE_ADMIN的nacos角色,可以看到用户管理界面，但是不能添加用户，提示org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [INSERT into users (username, password, enabled) VALUES (?, ?, ?)]; Could not retrieve transation read-only status server; nested exception is java.sql.SQLException: Could not retrieve transation read-only status server，不知道这个权限应该怎么设置才不是只读

**Comment by lewis008** [comment]
sccxcxc

**Comment by LiamLin07** [comment]
我也有这个问题，搭好的nacos，没登录就直接进去了
![image](https://user-images.githubusercontent.com/47836780/77870436-04c4ca80-7274-11ea-9bf4-5c2fa5d59d9c.png)

**Comment by liuyu92** [comment]
请问这个修复了吗
