### ISSUE TITLE
支持yml格式

### ISSUE THREAD

**Issue by zhangyuxiansen2017** [alibaba/nacos#2444]
我们知道nacos作为配置中心可以读取yaml文件，但yaml与yml是同一个文件类型，能不能解决下呢？哈哈

**Comment by chuntaojun** [comment]
> 我们知道nacos作为配置中心可以读取yaml文件，但yaml与yml是同一个文件类型，能不能解决下呢？哈哈

这只是一个标示作用，nacos本身不会去解析这些文件格式，具体的解析都是交由生态组件去完成的，但是可以考虑说类似yaml(yml)的显示提示
