### ISSUE TITLE
1.2.0 无法修改自己的密码

### ISSUE THREAD

**Issue by photondragon** [alibaba/nacos#2451]
在centos 7 上以单实例模式启动全新的 1.2.0 版本nacos，  
以 nacos 用户登录后，点击右上角修改密码，无法修改当前用户的密码，总是提示当前密码不正确

**Comment by nkorange** [comment]
可以先在“用户管理”界面改密码，右上角改密码会尽快修复

**Comment by weinianta** [comment]
1.2.0版本的，我之前都看到用户管理过，现在为什么看不到了。判断显示的条件是啥，是不是跟数据库有关

**Comment by fatliy** [comment]
在role表里，role改为ROLE_ADMIN，就可以看到用户管理界面，GLOBAL_ADMIN不行
