### ISSUE TITLE
NacosServer1.2.0 some service provider failed to online and offline

### ISSUE THREAD

**Issue by SandNight** [alibaba/nacos#2452]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
nacos-server 1.2.0 cluster mode 
some service provider failed to online and offline, but  some  can  online and offline normally

### Describe what you expected to happen
online and offline normally

### How to reproduce it (as minimally and precisely as possible)

1. nacos-server 1.1.3 upgrade to nacos-server 1.2.0

### Tell us your environment
1. service provider
spring cloud alibaba 2.1.1.RELEASE（nacos-client 1.1.4）
2. nacos server 1.2.0 cluster mode  + mysql 

### Anything else we need to know?
There are 3 nodes in the Nacos server cluster, 2 nodes fail in the online and offline, and 1 online and offline are normal.

error
{"timestamp":"2020-03-10T09:46:39.304+0000","status":500,"error":"Internal Server Error","message":"Server failed,","path":"/nacos/v1/ns/instance"}

**Comment by nkorange** [comment]
Did you use the admin account to online/offline?

**Comment by SandNight** [comment]
> Did you use the admin account to online/offline?

Yes,I tried both the admin and the regular account

**Comment by larscheng** [comment]
I had the same problem @nkorange  @SandNight 

### environment

- Nacos-Server: V1.2.0
- Nacos-Client: V1.2.0
- Nacos server (3 instances): cluster mode

### Issue Description

After the cluster is started successfully, register a service to the cluster, enter the service details page, and perform the online / offline operation on the service. The operation fails and returns the following information: 

` {"timestamp": "2020-03-25t04:57:44.685 + 0000", "status: 500," error ":" internal server error "," message ":" server failed, "," path ":" / Nacos / V1 / NS / instance "}`



### Possible causes

The source code of Nacos server v1.2.0 is analyzed. It is found that after the request enters, load balancing is carried out, and HTTP requests are redirected. During the redirection process, parameters are lost, resulting in java.lang.nullpointerexception

Question code:

`naming/src/main/java/com/alibaba/nacos/naming/web/DistroFilter.java`

```java
HttpClient.HttpResult result =
HttpClient.request("http://" + distroMapper.mapSrv(groupedServiceName) + urlString, headerList,StringUtils.isBlank(req.getQueryString()) ? HttpClient.translateParameterMap(req.getParameterMap()) : new HashMap<>(2), body, PROXY_CONNECT_TIMEOUT, PROXY_READ_TIMEOUT, Charsets.UTF_8.name(), req.getMethod());
```

**Comment by R-anybbo** [comment]
I had the same problem

**Comment by SandNight** [comment]
nacos 1.3.0  fixed it
