### ISSUE TITLE
超级用户登录后授权，提示授权成功，但是使用被授权的用户登录，提示授权失败，

### ISSUE THREAD

**Issue by 18207556302** [alibaba/nacos#2454]
1.使用超级用户nacos给普通用户授权，提示授权成功:
![image](https://user-images.githubusercontent.com/44963951/76392465-8d0a2b00-63ac-11ea-8d46-4dd10be57b3f.png)

2.退出超级用户，使用被授权的用户登录，查看授权效果：

![image](https://user-images.githubusercontent.com/44963951/76392349-516f6100-63ac-11ea-9b3a-5de30c3e3788.png)
提示授权失败！

**Comment by nkorange** [comment]
你授权的是否也是public命名空间？

**Comment by 18207556302** [comment]
不是，我授权的是自定义的namaspace

**Comment by nkorange** [comment]
> 不是，我授权的是自定义的namaspace

那这个错误你可以忽略，因为你没有授权public命名空间

**Comment by liubiaosheng** [comment]
没有授权的命名空间 是否 可以不要展示到界面上呢

**Comment by nkorange** [comment]
> 没有授权的命名空间 是否 可以不要展示到界面上呢

这个会在下个小版本进行优化

**Comment by lin-mt** [comment]
> > 没有授权的命名空间 是否 可以不要展示到界面上呢
> 
> 这个会在下个小版本进行优化

这个问题目前好像还是存在的，public 是默认的必须有的空间（无法删除），但是开启授权之后如果没有分配任何空间权限的话，此处就没有空间可选了，这是否有冲突呢
