### ISSUE TITLE
新建namespace命名为dev后，点击提交没有任何反应，然后整个nacos页面再也刷新不出东西了

### ISSUE THREAD

**Issue by changelzj** [alibaba/nacos#2459]
新建namespace命名和描述均为"dev"后，点击提交没有任何反应，然后整个nacos页面再也刷新不出东西了，js报错  Uncaught SyntaxError: Unexpected token B in JSON at position 0
重启了nacos server仍然没有效果

After creating a new namespace named dev, clicking submit has no response, and then the whole Nacos page can no longer refresh anything, JS reports an error "uncaught syntax error: unexpected token B in JSON at position 0"

Rebooting the Nacos server still has no effect

**Comment by changelzj** [comment]
清除cookies和缓存后，新增namespace的弹框多出来一个文本框，叫做 命名空间ID(不填则自动生成)：
 在新建能够成功，希望官方关注下浏览器缓存导致的异常。。。。谢谢

After the cookies and cache are cleared, a text box is added to the pop-up box of the new namespace, which is called the “namespace ID (it will be generated automatically if it is not filled):”

After the new build is successful, I hope the official will pay attention to the exceptions caused by the browser cache.... Thanks

**Comment by HelloHaiNG** [comment]
我这里可以新建成功dev的命名空间
