### ISSUE TITLE
1.2.0 springcloud通过bootstrao.yml读取配置一直提示403

### ISSUE THREAD

**Issue by yuanboyumena** [alibaba/nacos#2460]
cloud:
    nacos:
      config:
        server-addr: xxxxx:8848
        file-extension: yml
        namespace: xxxxxxxx

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Mar 12 16:34:12 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

**Comment by chenjy1991** [comment]
如果nacos开启了验证，试试在bootstrao.yml里添加 username 和 password 两个参数
在properties中这样添加的，并成功
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos

**Comment by yuanboyumena** [comment]
> 如果nacos开启了验证，试试在bootstrao.yml里添加 username 和 password 两个参数
> 在properties中这样添加的，并成功
> spring.cloud.nacos.config.username=nacos
> spring.cloud.nacos.config.password=nacos

已经这样试过但还是不行,是不是我的maven引用的版本过低呢  方便的话,能把客户端的maven发下看看嘛  谢谢

**Comment by chenjy1991** [comment]
```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </exclusion>
    </exclusions>
    </dependency>
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.2.0</version>
</dependency>
```
然后 spring-cloud-alibaba的版本是`<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>`
上述maven是因为最新版的`spring-cloud-starter-alibaba-nacos-config`仍然依赖的`nacos-client:1.1.4`

**Comment by yuanboyumena** [comment]
> ```
> <dependency>
>     <groupId>com.alibaba.cloud</groupId>
>     <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>     <exclusions>
>         <exclusion>
>             <groupId>com.alibaba.nacos</groupId>
>             <artifactId>nacos-client</artifactId>
>         </exclusion>
>     </exclusions>
>     </dependency>
> <dependency>
>     <groupId>com.alibaba.nacos</groupId>
>     <artifactId>nacos-client</artifactId>
>     <version>1.2.0</version>
> </dependency>
> ```
> 
> 然后 spring-cloud-alibaba的版本是`<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>`
> 上述maven是因为最新版的`spring-cloud-starter-alibaba-nacos-config`仍然依赖的`nacos-client:1.1.4`

好的 我试下 3Q

**Comment by yuanboyumena** [comment]
> 如果nacos开启了验证，试试在bootstrao.yml里添加 username 和 password 两个参数
> 在properties中这样添加的，并成功
> spring.cloud.nacos.config.username=nacos
> spring.cloud.nacos.config.password=nacos

依旧报这个403这个错误,而且我发现username和password并不能被识别为属性...

**Comment by chenjy1991** [comment]
我尝试将我的`bootstrap.properties`改为了`bootstrap.yml`，云端的`application.properties`改为了`application.yml`并成功启动，获取了云端的`application.yml`，并注册了服务。详细配置如下：
```
spring:
  application:
    name: com.xxx.xxx.gateway
  cloud:
    nacos:
      config:
        server-addr: xxx.xx.xx.xx:8848
        file-extension: yml
        namespace: 4114c03a-f170-4dcd-a633-335475428bb2
        username: nacos
        password: nacos
```

**Comment by yuanboyumena** [comment]
> 我尝试将我的`bootstrap.properties`改为了`bootstrap.yml`，云端的`application.properties`改为了`application.yml`并成功启动，获取了云端的`application.yml`，并注册了服务。详细配置如下：
> 
> ```
> spring:
>   application:
>     name: com.xxx.xxx.gateway
>   cloud:
>     nacos:
>       config:
>         server-addr: xxx.xx.xx.xx:8848
>         file-extension: yml
>         namespace: 4114c03a-f170-4dcd-a633-335475428bb2
>         username: nacos
>         password: nacos
> ```

我的也是按照这个模式写的,但是启动服务时依旧无法识别用户和密码

**Comment by chenjy1991** [comment]
也许有bug，我发现我是用域名:80转发的 ip:8848，并设置了 `context-path=/`，我如果使用 IP:8848的模式，也发现了这个问题。正在努力的写issues中……

**Comment by yuanboyumena** [comment]
> 也许有bug，我发现我是用域名:80转发的 ip:8848，并设置了 `context-path=/`，我如果使用 IP:8848的模式，也发现了这个问题。正在努力的写issues中……

我看了之前有issues提到过这个问题,应该是spring-cloud-alibaba暂时还不支持1.2.0  估计这两周应该会支持

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2462

**Comment by scxs** [comment]
bootstrap.properties中添加config相关配置比如namespace、用户名、密码等
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos

application.properties中添加如下配置
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos

按照此方式添加后就没有权限问题了（nacos.core.auth.enabled=true 权限开启后 config和注册中心都要对权限配置用户和密码）

**Comment by qq31715879** [comment]
手动sdk方式读取设置账号密码还是不行
