### ISSUE TITLE
nacos-client 1.20版本 403 'unknown user!' 错误(nacos-client 1.2.0 version 403 'unknown user!' error)(google translate)

### ISSUE THREAD

**Issue by chenjy1991** [alibaba/nacos#2462]
我将nacos-server升级到1.2.0版本后，使用nacos-client 1.2.0版本进行连接，基于 spring-cloud-alibaba。

当我开启nacos-server的权限验证后，在`bootstrap.properties`中写入`username`和`password`两个参数，`server-addr`为`ip:port`,不填写`context-path`。

在项目启动时，检测到这`username`和`password`参数，`nacos-client`会进行登录操作，但请求的地址是`http://ip:8848/v1/auth/users/login`，并没有加上`/nacos`，且请求结果为`HTTP Status 404 – Not Found`,而经测试正确的地址应该是`http://ip:8848/nacos/v1/auth/users/login`

经过debug发现在`nacos-client:1.2.0`的`com.alibaba.nacos.client.security.SecurityProxy`的第86行，
`contextPath = properties.getProperty(PropertyKeyConst.CONTEXT_PATH, "/nacos");`方法并没有获取正确的`contextPath`，应该获取为`"/nacos"`但实际获取的是`""`。

最后，我通过将一个`域名:80`解析到`ip:8848/nacos`来解决了这个问题。并在`bootstrap.properties`配置`server-addr=域名:80`和`context-path=/`

我想知道，这是不是`nacos-client:1.2.0`存在的问题，还是由于我自身的错误设置导致的。谢谢

Here is what Google translates

After I upgraded nacos-server to 1.2.0, I used nacos-client 1.2.0 to connect, based on spring-cloud-alibaba.

After I enabled the permission verification of nacos-server, I wrote the two parameters `username` and` password` in `bootstrap.properties`,` server-addr` was `ip: port`, and` context-path` was not filled in .

When the project was started, the `username` and` password` parameters were detected. `Nacos-client` will perform the login operation, but the requested address is` http://ip:8848/v1/auth/users/login `, Without adding` / nacos`, and the request result is `HTTP Status 404 – Not Found`, and the correct address after testing should be` http://ip:8848/nacos/v1/auth/users / login`

After debugging, it was found in line 86 of `com.alibaba.nacos.client.security.SecurityProxy` of` nacos-client: 1.2.0`,
`contextPath = properties.getProperty (PropertyKeyConst.CONTEXT_PATH," / nacos ");` method does not get the correct `contextPath`, it should be obtained as` "/ nacos" `but the actual obtained is` "" `.

Finally, I solved this problem by resolving a `domain name: 80` to` ip: 8848 / nacos`. And configure `server-addr = domain name: 80` and` context-path = / `in` bootstrap.properties`

I want to know if this is a problem with `nacos-client: 1.2.0` or it is caused by my own wrong setting. Thank you

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1256](https://github.com/alibaba/spring-cloud-alibaba/issues/1256) via [**ZenHub**](https://www.zenhub.com/)
