### ISSUE TITLE
The role of the LeaderElectFinishedEvent event

### ISSUE THREAD

**Issue by zhanglinglf** [alibaba/nacos#2465]
## Issue Description

Type:  *feature request*

### com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet#decideLeader
```java
    if (maxApproveCount >= majorityCount()) {
            RaftPeer peer = peers.get(maxApprovePeer);
            peer.state = RaftPeer.State.LEADER;

            if (!Objects.equals(leader, peer)) {
                leader = peer;
                applicationContext.publishEvent(new LeaderElectFinishedEvent(this, leader));
                Loggers.RAFT.info("{} has become the LEADER", leader.ip);
            }
        }
```

LeaderElectFinishedEvent事件，源码未找到对该事件的处理
Hello, could you please tell me， send The LeaderElectFinishedEvent event is sent, but the handling of the event is not found in the source code?

**Comment by chuntaojun** [comment]
In a future release, this simple Raft implementation will be replaced. At present, there is no need to use the upper layer of the event, so there is no corresponding Listener
