### ISSUE TITLE
nacos使用jpa作为orm增强数据库移植性

### ISSUE THREAD

**Issue by yangliu817** [alibaba/nacos#2467]
您好! 根据nacos1.2.0的源码, 在几乎不改动源码的基础上我尝试编写了jpa模块,且经过简单测试(UI上的增删改查),  仅注释掉
BasicDataSourceServiceImpl类上的@Service注解
,另外 pom中添加该模块的依赖, 如果您考虑nacos支持其他数据库,且减少维护工作量,可参考
https://gitee.com/yangliu817/nacos-jpa 

我的邮箱 yangliu817@126.com

**Comment by MarkBellCN** [comment]
注释掉BasicDataSourceServiceImpl数据库主从切换还正常？？

**Comment by yangliu817** [comment]
> 
> 
> 注释掉BasicDataSourceServiceImpl数据库主从切换还正常？？

在JPA里面定义多个数据源,需要定义多个entitymanagefactory, 此步骤比较麻烦, 我这边为了快速写完service这边的逻辑,舍弃了主从,

**Comment by chuntaojun** [comment]
感谢你的想法以及支持，目前此支持社区已有一位同学在负责了，你可以和他进行谈论下，他的钉钉号：zfast89

**Comment by KomachiSion** [comment]
Nacos 可能不适合使用JPA的方式接入数据库， 对于多数据源的支持， 社区2.2版本通过插件化的方式支持。
