### ISSUE TITLE
Nacos 1.1.4 导出配置文件的后缀为 .html，实际导入的时候要求为 .zip 

### ISSUE THREAD

**Issue by mj19910923** [alibaba/nacos#2469]
## Issue Description

bug report

### Describe what happened (or what feature you want)
Nacos 1.1.4 导出配置文件的后缀为 .html，实际导入的时候要求为 .zip 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by dudiao** [comment]
nacos 1.2.1 也是这样

**Comment by dudiao** [comment]
后来发现是浏览器的一个插件所致：

![image](https://user-images.githubusercontent.com/38355949/80866978-3f32e480-8cc4-11ea-9f8c-3cfa3d820be0.png)

把“Chrono下载管理器”这个插件关了再下载就可以了

**Comment by mj19910923** [comment]
但是 chrono这个插件在其他站点下载功能是正常的，另外这个插件真的很香，我可不愿意卸载😑
