### ISSUE TITLE
console namespace不存在时实例不显示

### ISSUE THREAD

**Issue by wolfgangzhu** [alibaba/nacos#2470]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
在server端未配置namespace，此时服务注册时设置了一个随意的命名空间，服务注册成功，在console上的服务管理其实是无法找到该服务, 除非在console端配置，对使用者会造成疑惑。

### Describe what you expected to happen
是否采用如下方式比较合适：
1）当服务配置的namespace（非默认的Public）未配置时，服务注册是否应注册失败
2）当服务配置的namespace（非默认的Public）未配置时，console会自动创建出namespace

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.2.0

**Comment by chuntaojun** [comment]
Currently, for some reason, a namespace not created on the console cannot be displayed and persisted, which will be fixed in a future release

**Comment by KomachiSion** [comment]
duplicate with #4134
