### ISSUE TITLE
nacos 1.2.0 service register failed access denied

### ISSUE THREAD

**Issue by RevisitMoon** [alibaba/nacos#2477]
使用spring.cloud.alibaba.denpendencies 2.2.0注册服务时失败
我开启了nacos的权限验证.就不可以向nacos注册了.yml配置里也没有用户或者密码的选项
使用nacos-client 1.2.0 问题依旧
请问怎么解决

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1268](https://github.com/alibaba/spring-cloud-alibaba/issues/1268) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chuntaojun** [comment]
This function has been adapted. We are waiting for the release of spring cloud alibaba
