### ISSUE TITLE
集群部署时遇到错误Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncHttpClient-Callback"

### ISSUE THREAD

**Issue by yao012** [alibaba/nacos#2486]
## Issue Description
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AsyncHttpClient-Callback"

### Describe what happened (or what feature you want)
when the case of cluster deployment, when I temporarily started only one node A, the service seemed normal, but when I started another node B, the cup of A soared wildly. When I checked the start.out file, I found OOM, and the specific error was as follows:

### Describe what you expected to happen
normal start

### How to reproduce it (as minimally and precisely as possible)

1. Start the two nodes AB in sequence, and observe the CPU consumption of A after starting node B
2.My Settings is: JAVA_OPT="${JAVA_OPT} -server -Xms450m -Xmx450m -Xmn150m -XX:MetaspaceSize=32m -XX:MaxMetaspaceSize=64m"

### Tell us your environment
Alibaba Cloud Elastic

**Comment by yao012** [comment]
Is it because of my JVM allocation problem

**Comment by chuntaojun** [comment]
startup.sh已经对JVM的分配做了设置,集群模式下对内存的要求会高一些

**Comment by yao012** [comment]
> startup.sh已经对JVM的分配做了设置,集群模式下对内存的要求会高一些

如果手动调小就会有这样的问题？这个是1.2.0强制要求的么,如果使用1.1.4是否有类似的要求

**Comment by chuntaojun** [comment]
集群模式建议按照startup.sh里面的来，因为集群模式内部会有很多额外的工作，相比单机模式

**Comment by yao012** [comment]
ok,thanks

**Comment by yao012** [comment]
> 集群模式建议按照startup.sh里面的来，因为集群模式内部会有很多额外的工作，相比单机模式

ok,thanks
