### ISSUE TITLE
你就不能把下载的内容放到OOS上面嘛，现在的下载速度慢到爆炸了。

### ISSUE THREAD

**Issue by natureLanguageQing** [alibaba/nacos#2489]
你就不能把下载的内容放到OOS上面嘛，现在的下载速度慢到爆炸了。

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by woshiawei** [comment]
简直下不下来

**Comment by natureLanguageQing** [comment]
明明阿里云有全世界最好数据中心可是他就是不用。

**Comment by chuntaojun** [comment]
目前我做了百度网盘进行暂时的解决下载慢的问题，可以看下readme里面有这个链接

**Comment by natureLanguageQing** [comment]
你就放到oos上面吧，我现在用的docker版本的也不错。但是我想要订制的话就还是需要下载代码来看看呀。

**Comment by chuntaojun** [comment]
> 你就放到oos上面吧，我现在用的docker版本的也不错。但是我想要订制的话就还是需要下载代码来看看呀。

源码问题你可以gitee clone过去，oss的话，理论上可能只会放发行包

**Comment by Tgxiaowei** [comment]
建议复制链接使用迅雷等下载器下载
