### ISSUE TITLE
1.2.0client端sendBeat，server端无法解析

### ISSUE THREAD

**Issue by khiker007** [alibaba/nacos#2492]
## Issue Description

使用spring-cloud-alibaba，心跳数据的metadata中含有特殊字符，在body中发送beat=xxx时没有进行urlencode，导致server端接收后无法解析

### How to reproduce it (as minimally and precisely as possible)

修改client的NamingProxy的sendBeat方法，body = "beat=" + JSON.toJSONString(beatInfo)修改为"beat=" + URLEncoder.encode(JSON.toJSONString(beatInfo), "UTF-8");

**Comment by chuntaojun** [comment]
already fix in 1.2.1 and 1.3.0-beta
