### ISSUE TITLE
nacos成功启动后访问不了http://127.0.0.1:8848/nacos/index.html

### ISSUE THREAD

**Issue by rogerJason** [alibaba/nacos#2494]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by SnailDHC** [comment]
我也是，之前用的1.1.4版本，现在使用1.2版本页面无法访问
![image](https://user-images.githubusercontent.com/25739214/77070591-76577a00-6a25-11ea-95b0-ddebd836c55f.png)

**Comment by SnailDHC** [comment]
清下浏览器缓存就好了
