### ISSUE TITLE
SpringBoot thin package with used nacos error

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#2500]
我的springboot工程使用了nacos，现在我尝试对工程使用瘦身打包部署，程序启动报错。
我把nacos引用去除再进行瘦身打包，可正常运行。
![image](https://user-images.githubusercontent.com/62423061/77151374-bd4e7980-6ad0-11ea-9520-d6cca95ae332.png)

**Comment by chuntaojun** [comment]
Nacos - client? Use the nacos-springboot-peoject dependency

**Comment by saiyujs** [comment]
我用的是spring-cloud-starter-alibaba-nacos-discovery 0.2.1 和 nacos-config-spring-boot-starter 0.2.1

**Comment by chuntaojun** [comment]
看下你的配置文件

**Comment by saiyujs** [comment]
![image](https://user-images.githubusercontent.com/62423061/77992457-ade4f100-7358-11ea-8f6f-ca2bc6672913.png)
![image](https://user-images.githubusercontent.com/62423061/77992511-c81ecf00-7358-11ea-8967-d237c01afcb9.png)
![image](https://user-images.githubusercontent.com/62423061/77992540-dd93f900-7358-11ea-97a9-0c4daa8ea122.png)
图一是我的配置文件，配置nacos地址
图二是我启动类的注入，监听了dataId为schedule的配置
图三是我打瘦身包的策略

**Comment by chuntaojun** [comment]
是cloud项目的话最好统一使用cloud-alibaba-nacos
