### ISSUE TITLE
Single ConfigApp or NamingApp starts error in 1.2.0

### ISSUE THREAD

**Issue by rushsky518** [alibaba/nacos#2502]
## Issue Description

Type: *bug report* 

Single ConfigApp or NamingApp starts error in 1.2.0

**Comment by chuntaojun** [comment]
Because the control manages the beans in the console module, you cannot currently start Config or name separately

**Comment by rushsky518** [comment]
it works fine with older version

**Comment by chuntaojun** [comment]
Some of the new beans in version 1.2.0 exist in the console module, but the submodules depend on this bean, so this is a problem. We will adjust the order of dependencies later
