### ISSUE TITLE
Nacos：1.2.0(Mar 4th, 2020)无法登陆

### ISSUE THREAD

**Issue by tansuoboy** [alibaba/nacos#2505]
## Nacos：1.2.0(Mar 4th, 2020)无法登陆
Nacos：1.2.0(Mar 4th, 2020)版本
修改数据库连接之后，访问http://127.0.0.1:8848/nacos/#/login
输入默认用户名和密码之后，点击提交没反应，控制台也无错误信息。
切换1.0.0版本之后是可以登陆进去的。

**Comment by imgoby** [comment]
我也遇到同样问题：
由低版本升到1.2.0，出现无法登录。
![image](https://user-images.githubusercontent.com/27885492/77245968-df293700-6c5d-11ea-8f3a-1ad5436e483b.png)

清空浏览器缓存才可以解决。

**Comment by chuntaojun** [comment]
Some of the permission information in 1.2.0 has changed, requiring the browser to cache manually under clear sky
