### ISSUE TITLE
Console Editor Optimization

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#251]
- The edit box does not edit the area too large, can be set to 0 margin, otherwise people often click on the left can not edit
![image](https://user-images.githubusercontent.com/17695352/48202411-ba515e00-e39f-11e8-9e7e-2f539d505556.png)

**Comment by pguo65535** [comment]
I think we'd better to gen&split  this issue to several issues to track them separately.

**Comment by wfnuser** [comment]
Actually the padding of monaco-editor is used to support folding feature... So the only way to set padding to zero is to disable the folding feature.
