### ISSUE TITLE
通过nacos管理控制台添加配置，报JS错误

### ISSUE THREAD

**Issue by yangfei2018** [alibaba/nacos#2512]
main.js:38 Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined
    at main.js:38
    at main.js:93
    at Array.<anonymous> (main.js:93)
    at main.js:93
    at r (main.js:33)
    at e (main.js:33)
    at a (main.js:93)
    at t.value (main.js:38)
    at main.js:93
    at e (main.js:33)

**Comment by longnine** [comment]
可以尝试 ctrl + shift + r清理浏览器缓存

**Comment by longnine** [comment]
这种前端问题，一般都可以通过换浏览器，或清缓存解决（一般chrome和firefox最新版兼容性比较好）

**Comment by yangfei2018** [comment]
> 这种前端问题，一般都可以通过换浏览器，或清缓存解决（一般chrome和firefox最新版兼容性比较好）

已经解决了，重新启动服务打开后，可以添加成功了。

**Comment by longnine** [comment]
> > 这种前端问题，一般都可以通过换浏览器，或清缓存解决（一般chrome和firefox最新版兼容性比较好）
> 
> 已经解决了，重新启动服务打开后，可以添加成功了。

ok

**Comment by fengjx** [comment]
遇到同样的问题，用localhost访问的就会报这个错，改成本机的内网ip就可以了

**Comment by silverlight** [comment]
遇到了相同的问题，版本1.2.1。换浏览器，清理缓存均不能解决。在保存properties时会出现无法发布。
![image](https://user-images.githubusercontent.com/18061452/79095373-c9a2bb00-7d8c-11ea-8df1-12169b085d40.png)

**Comment by silverlight** [comment]
猜测是properties里面有什么字符串导致了这个问题，但是没有提示具体不知道是哪边出的问题

**Comment by seishuchen** [comment]
就这样关闭了？保存成text没问题，保存yaml就报这个异常，其它格式没尝试。
