### ISSUE TITLE
linux sh ./startup.sh  运行报错 `case `uname` in 和  syntax error near unexpected token `$'in\r''

### ISSUE THREAD

**Issue by landashu** [alibaba/nacos#2514]
![image](https://user-images.githubusercontent.com/17019818/77334533-e89ac800-6d5f-11ea-95f5-34b4d65d4d43.png)

run linux Nacos error，linux version centos7 64 ，linux command uname -a result：
Linux localhost.localdomain 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

中文：linux 下运行异常啊，运行方式 是 sh ./startup.sh  就报错，截图里的。

**Comment by landashu** [comment]
Nacos version 1.2.0 
版本为 1.2.0

**Comment by chuntaojun** [comment]
使用 bash
