### ISSUE TITLE
Nacos跨区【不同国家】同步问题

### ISSUE THREAD

**Issue by skarl-api** [alibaba/nacos#2515]
如题：

**Comment by chuntaojun** [comment]
具体问题能描述下吗，或者说有错误日志吗

**Comment by ordercard** [comment]
可以使用阿里的canal做db同步然后自己代码触发push

**Comment by ShawshankLin** [comment]
@chuntaojun 请问对于不同国家地区部署，是推荐使用endpoint进行硬隔离还是直接单独部署一套，客户端配置改成该地区的nacos
