### ISSUE TITLE
nacos1.1.4 启动 failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:localhost:8848/nacos/v1/ns/instance.

### ISSUE THREAD

**Issue by lyh19940304** [alibaba/nacos#2517]
nacos 1.1.4
spring-boot 2.2.5
spring-cloud-alibaba 2.2.0

主要报错信息是这个
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: failed to req API:localhost:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid: Your IP address is spelled incorrectly

配置是
spring.application.name=cloud-service
spring.cloud.nacos.server-addr=localhost:8848
dubbo.scan.base-packages=com.cloud
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
dubbo.registry.address=spring-cloud://localhost:8848
dubbo.cloud.subscribed-services=
dubbo.consumer.check=false

为啥总是说我的IP不合法呢

**Comment by chuntaojun** [comment]
这里的ip不合法不是指nacos的server地址不合法，而是你的服务实例的IP地址不合法，建议抓包或者看server端的access.log请求看下服务实例注册的数据信息，看下实例的ip是什么样的
