### ISSUE TITLE
nacos1.1.4 控制台上下线bug

### ISSUE THREAD

**Issue by kingstone95** [alibaba/nacos#2519]
## nacos控制台上下线bug
Type: *bug report*

### 在控制台上点击服务上下线时，当groupName 非默认时，功能存在bug， http请求参数未携带group
![image](https://user-images.githubusercontent.com/36784072/77515308-3ecc5000-6eb3-11ea-9544-cac264bb3e65.png)

###  environment
nacos 1.1.4

**Comment by token01** [comment]
新版本有解决吧

**Comment by supermareo** [comment]
> 新版本有解决吧

我用nacos 1.2.1版本，仍然存在这个问题

在nacos 1.2.1中，非默认group情况下，控制台点击服务下线，该服务的 `下线` 按钮文字变为 `上线`，但刷新后即恢复成 `下线`
同时，返回上一级界面，发现在DEFAULT_GROUP下出现了刚才下线的服务，且按钮文字为 `上线`

**Comment by MaJintao611** [comment]
我也发现了这个问题，应该还是前端请求没有带上group的问题，希望能修复一下
