### ISSUE TITLE
Setting the service to offline status does not take effect

### ISSUE THREAD

**Issue by jatsh** [alibaba/nacos#252]
# Reporting bugs
Hi, the question is that ,when the service "service-provider" state is set to offline in the console, the service can still be invoked by comsumer.  Maybe I have misunderstood something.  FYI

- provider
![](http://ww1.sinaimg.cn/large/8a70a551gy1fx13i9kyq2j22ke0u6wij.jpg)

- comsumer
![](http://ww1.sinaimg.cn/large/8a70a551gy1fx13k8n98fj22l60rcwia.jpg)

- call from consumer
![](http://ww1.sinaimg.cn/large/8a70a551gy1fx13jasj0oj20y608swfd.jpg)

# 报告错误
运行了一下nacos-example项目中的discovery部分的源码， 然后在nacos的console页面将service-provider状态设置为offline，service-comsumer仍然可以成功调用该service

运行环境：macos 10.14.1  , jdk8 , nacos 0.3.0

**Comment by nkorange** [comment]
@jatsh client getAllInstances method returns all instances of service regardless the status of instance. You can call selectInstances("service-provider", true) to filter out offline instances.

**Comment by jatsh** [comment]
@nkorange thanks for your reply, but i can't understand why set the service offline, comsumer still can call it successfully through 'restTemplate.getForObject("http://service-provider-demo/echo/" + str, String.class)' . And there are some problems of 'selectInstances("service-provider", true)' ,it doesn't look right .
![code](http://ww1.sinaimg.cn/large/8a70a551gy1fx1thno8i1j20pj056aad.jpg)

![console](http://ww1.sinaimg.cn/large/8a70a551gy1fx1thse79mj21620e3mxx.jpg)

![api](http://ww1.sinaimg.cn/large/8a70a551gy1fx1thwbd39j20pl0lgaax.jpg)

**Comment by nkorange** [comment]
@jatsh What's the version of your Nacos client? And note that setting instance offline does not change the healthy state of the instance, they are two different properties. The following code shows how client filter out disabled instances:

![image](https://user-images.githubusercontent.com/4593375/48254583-6305c900-e445-11e8-84cd-1519d2a939fd.png)

**Comment by jatsh** [comment]
@nkorange client version is 0.3.0. Just now i ran the example code again and all response comes right。
The provider services  just don't participate in load balancing after they go offline. Thanks a lot !

**Comment by nkorange** [comment]
'Offline' is useful when service instance is healthy but not willing to receive request flow.
