### ISSUE TITLE
Heartbeat open api document is wrong

### ISSUE THREAD

**Issue by mfkugergvh** [alibaba/nacos#2521]
![image](https://user-images.githubusercontent.com/9016871/77517012-52c58100-6eb6-11ea-9889-7489e90f2837.png)

The url param ‘beat’ is not actually used. In order to send a successful heartbeat of a instance, ip,serviceName,groupName and port should write directly as url param.

链接上的参数 'beat'实际上没有用。如果要发送正确的心跳，ip，serviceName，groupName和 port 这些参数需要直接作为 Url 参数发送。

**Comment by dingkegithub** [comment]
open api 文档不完善，错误码之类的说明没有
