### ISSUE TITLE
1.2.0 SpringBoot+Nacos nacos.core.auth.enabled=true时 unknown user！

### ISSUE THREAD

**Issue by cikezhangzihao** [alibaba/nacos#2536]
## 版本
* springboot版本：2.1.1
* nacos版本：1.2.0
## 问题描述：
* 当开启nacos.core.auth.enabled=true ，会报错
`Fri Mar 27 10:50:07 CST 2020
There was an unexpected error (type=Forbidden, status=403).
unknown user!`
* 如果 nacos.core.auth.enabled=false是可以正常读取到配置中心数据的，但是这样页面就是开放的，没有权限验证了
## 需要解决什么问题
* 请问下这样需要如何达到既能开启权限验证又能正常读取配置中心数据呢？

**Comment by nkorange** [comment]
看下文档：https://nacos.io/en-us/blog/nacos%201.2.0%20guide.html
