### ISSUE TITLE
wget/curl获取配置一直报错

### ISSUE THREAD

**Issue by huai168an** [alibaba/nacos#2538]
使用新的1.2.0版本，环境原因，只能通过curl或者wget来获取配置信息，1.1.4没有权限认证，可以使用API，一直等1.2.0版本的权限功能，但是curl，wget工具就无法获取配置信息了，即使加了用户名和密码还是报错：
{"timestamp":"2020-03-27T10:05:40.116+0000","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/cs/configs"}
日志文件中也是报的这种错误

我用命令：
curl -u nacos:nacos http://xx.xx.xx.xx:8848/nacos/v1/cs/configs?dataId=test&group=test&tenant=pre
wget --user=nacos --password=nacos "http://xx.xx.xx.xx:8848/nacos/v1/cs/configs?dataId=config.js&group=test&tenant=pre"

nacos认证配置：
spring.security.enabled=true
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.default.token.expire.seconds=18000
nacos.core.auth.default.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789
nacos.core.auth.caching.enabled=false

网页方式都是正常的，权限需求满足使用，但是获取应用的配置文件，暂时只使用curl或者wget来获取，但一直报错，不知道curl、wget获取时哪里的参数没对或遗漏，望求解，谢谢！！

=======================================
非常感谢各位大神的帮忙，现在有两种方法：
第一种：
1. 登录获取accessToken
curl -XPOST "http://localhost:8848/nacos/v1/auth/users/login?username=nacos&password=nacos"
2. curl -XGET "http://localhost:8848/nacos/v1/cs/configs?&dataId=test.js&group=test&tenant=pre&accessToken=xxxxxxxx"

第二种：
curl -XGET "http://localhost:8848/nacos/v1/cs/configs?&dataId=test.js&group=test&tenant=pre&username=nacos&password=nacos"

**Comment by chuntaojun** [comment]
需要通过登陆获取accessToken，然后url带上这个信息，

**Comment by ordercard** [comment]
你的用法不对，第一个curl某有加用户名密码，第二个也是同理你加的位置不对

**Comment by huai168an** [comment]
> 需要通过登陆获取accessToken，然后url带上这个信息，

登录获取accesstoken，那配置文件里面的token可以用么？

**Comment by chuntaojun** [comment]
> > 需要通过登陆获取accessToken，然后url带上这个信息，
> 
> 登录获取accesstoken，那配置文件里面的token可以用么？

那个token是由于计算加密用的，你要登陆后获取jwt这个信息

**Comment by ordercard** [comment]
curl "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=application.properties&group=DEFAULT_GROUP&username=nacos&password=nacos"
正确的用法

**Comment by huai168an** [comment]
> curl "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=application.properties&group=DEFAULT_GROUP&username=nacos&password=nacos"
> 正确的用法

可以的，这个可以用

**Comment by huai168an** [comment]
> > > 需要通过登陆获取accessToken，然后url带上这个信息，
> > 
> > 
> > 登录获取accesstoken，那配置文件里面的token可以用么？
> 
> 那个token是由于计算加密用的，你要登陆后获取jwt这个信息

嗯，试过了，可以用，现在有两种方法，这种比较安全些，不用暴露密码，非常感谢！！
