### ISSUE TITLE
nacos1.2.0 linux环境3节点集群，节点状态显示不对？

### ISSUE THREAD

**Issue by diaodiaofly** [alibaba/nacos#2541]
3个节点的集群环境，故意把LEADER停止，其他2个节点并没有选举出新的LEADER？
等待很长时间节点，2个都是FOLLOWER状态（服务会好几分钟内变为不健康）
nacos1.2.0版本
<img width="1432" alt="QQ20200328-145116@2x" src="https://user-images.githubusercontent.com/17794120/77817195-16876000-7104-11ea-86b5-ed228723adc0.png">

另一个环境的1.1.4，同样的把leader停止掉，节点状态正常
<img width="1327" alt="QQ20200328-145147@2x" src="https://user-images.githubusercontent.com/17794120/77817212-3ae33c80-7104-11ea-82bc-7518fb543c25.png">

请问这是1.2.0新版本的bug么

**Comment by diaodiaofly** [comment]
@chuntaojun help me

**Comment by chuntaojun** [comment]
看下naming-raft日志，或者你提出来下

**Comment by diaodiaofly** [comment]
> 看下naming-raft日志，或者你提出来下

[{"adWeight":0,"alive":false,"ip":"*.*.*.112","key":"*.*.*.112:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"*.*.*.113","key":"*.*.*.113:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"*.*.*.114","key":"*.*.*.114:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
（ip我隐藏了前三位）这个串里面site是unknown，不知道没有影响  其他的log感觉没什么异常

WARN [IS LEADER] no leader is available now!

received approve from peer: {"heartbeatDueMs":4000,"ip":"*.*.*.114:8848","leaderDueMs":16695,"state":"FOLLOWER","term":1,"voteFor":"*.*.*.112:8848"}

received approve from peer: {"heartbeatDueMs":4000,"ip":"*.*.*.114:8848","leaderDueMs":16695,"state":"FOLLOWER","term":1,"voteFor":"*.*.*.112:8848"}
然后没有其他的了，还发现在这种异常的集群下，服务节点也偶现不健康，但是心跳日志又正常的在打 ，服务里面也没出现其他异常

**Comment by diaodiaofly** [comment]
<img width="1256" alt="678" src="https://user-images.githubusercontent.com/17794120/77820478-9241d680-711d-11ea-914a-5a554fd44d46.png">

**Comment by yanlinly** [comment]
fix in 1.3.0 , u can try to use it

**Comment by diaodiaofly** [comment]
> fix in 1.3.0 , u can try to use it

好的  辛苦了  1.1.4这个版本我们线上业务在跑了   有空尝试下测试环境升级体验下
