### ISSUE TITLE
java.lang.NoClassDefFoundError: org/springframework/security/rsa/crypto/RsaAlgorithm

### ISSUE THREAD

**Issue by LiPeng960419** [alibaba/nacos#2542]
springboot启动nacos报错是什么问题 集成了jwt
[ERROR][2020-03-28 17:29:55,655][com.alibaba.nacos.client.Worker.longPollingfixed-39.97.99.155_8848][com.alibaba.nacos.client.config.impl.CacheData$1]: [fixed-39.97.99.155_8848] [notify-error] dataId=demo.properties, group=demoGroup, md5=5a91d2bc675b9549ba8d3e4c46b71b5e, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@69dc2548 tx=java.lang.NoClassDefFoundError: org/springframework/security/rsa/crypto/RsaAlgorithm

**Comment by chuntaojun** [comment]
客户端不集成spring-security模块，你需要排查下自己的项目依赖信息以及代码

**Comment by LiPeng960419** [comment]
没有集成这个模块，maven里jjwt 依赖包含了这个类 RsaAlgorithm

**Comment by chuntaojun** [comment]
或许是ClassLoader的问题引起的

**Comment by LiPeng960419** [comment]
<dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-rsa</artifactId>
            <version>1.0.9.RELEASE</version>
        </dependency>

加入依赖 就可以了
