### ISSUE TITLE
能否给出正确的打包jar方式

### ISSUE THREAD

**Issue by ordercard** [alibaba/nacos#2544]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U
打包成功但是无法执行。缺少静态页面文件等等
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
在项目根目录下执行此命令
