### ISSUE TITLE
nacos config更新时，本地缓存更新延迟

### ISSUE THREAD

**Issue by wolfdriver** [alibaba/nacos#2551]
在`ConfigController`中更新配置信息时，所有的本地更新均通过`ConfigDataChangeEvent`事件进行更新，而事件处理的`AsyncNotifyService`类中，即使是更新本机缓存数据，也需要通过异步HTTP请求完成。
这种情况下，即使是单台应用，也会出现publish()更新数据延迟，导致getConfig()时不能获取到最新的数据

**Comment by chuntaojun** [comment]
单机情况，如果你不是使用mysql作为存储的话，不存在本机缓存的操作，mysql的话存在，异步操作确实会存在一定的延迟
