### ISSUE TITLE
我很喜欢nacos,但是nacos的并发能力相比其他还有很大的提高,请问并发上不去,我为什么选择nacos

### ISSUE THREAD

**Issue by hlyaowan** [alibaba/nacos#2556]
![image](https://user-images.githubusercontent.com/580212/77980682-723b2e80-733a-11ea-95b8-0494774ba7be.png)
![image](https://user-images.githubusercontent.com/580212/77980696-7b2c0000-733a-11ea-8402-7ba8218c787b.png)
从阿里云官方的压测报告来看,nacos的并发能力最弱,就连已经不维护的Eureka的并发能力都比不上,给我个理由让我选择nacos

**Comment by yanlinly** [comment]
阿里云上的eureka是基于nacos实现的。压测接口抖动一些，但是基本性能都是相同的。

当然你可以找一个同样机型的原生的eureka去压一下，会比它好很多。

为什么云上要基于nacos兼容eureka呢，因为云上有一些老的eureka残留的客户，eureka不发展了，所以就兼容了一下。这个是云产品行为，你云上去选择我们兼容的eureka也是可以的，但是我建议你选择nacos，因为nacos会持续发展，最近开发的长链接能力还需继续扩大比原生eureka的性能优势。
