### ISSUE TITLE
nacos注册中心服务突然挂掉的话是不是服务之间都无法调用了？服务和服务之间的通讯必须nacos服务正常情况下吗?

### ISSUE THREAD

**Issue by areskts** [alibaba/nacos#2565]
nacos注册中心服务突然挂掉的话，是不是其他应用间的服务都无法调用了？服务和服务之间的通讯必须nacos服务正常情况下吗（已经注册过的）?

**Comment by chuntaojun** [comment]
不用，内部会有缓存的，避免nacos服务端crash导致客户端无法使用

**Comment by JackSlamDunk** [comment]
> 不用，内部会有缓存的，避免nacos服务端crash导致客户端无法使用

是哪个参数控制的?
