### ISSUE TITLE
nacos1.2.1配置更新yaml格式内容时会产生一直通知刷新问题

### ISSUE THREAD

**Issue by chmutian** [alibaba/nacos#2567]
nacos.log日志
![image](https://user-images.githubusercontent.com/31753358/78117118-d4c62480-7437-11ea-931a-792e79884e17.png)

应用端日志
![image](https://user-images.githubusercontent.com/31753358/78117253-00490f00-7438-11ea-9d0b-97c20332ef00.png)

**Comment by TaroLoveFox** [comment]
俺也一样

**Comment by Amber125208** [comment]
俺也一样

**Comment by baobeidaodao** [comment]
俺也一样

**Comment by JIE6** [comment]
我碰到过这个问题，我用的日志是logback，我在里面设置了他的输出级别。然后就不会这样了

<logger name="com.alibaba.nacos.client" level="ERROR" additivity="false"/>

**Comment by JIE6** [comment]
`<logger name="com.alibaba.nacos.client" level="ERROR" additivity="false"/>`

**Comment by dodolook8716** [comment]
> `<logger name="com.alibaba.nacos.client" level="ERROR" additivity="false"/>`

这么做掩耳盗铃啊, 我把自动刷新关了

**Comment by chuntaojun** [comment]
already fix in 1.3.0-beta. Or you can download version 1.2.1 again
