### ISSUE TITLE
Spring Cloud Gateway + nacos-discovery 未能路由到指定的服务

### ISSUE THREAD

**Issue by lichaoyue** [alibaba/nacos#2568]
spring cloud version :Hoxton.SR3
spring boot version:2.2.6.RELEASE
spring-cloud-alibaba.version: 2.2.0.RELEAS

服务提供者注册到nacos上的信息是：spring.application.name=service-gateway-provider 且在同一个namespace中

网关配置：
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: nacos-route
          uri: lb://service-gateway-provider
          predicates:
            - Path=/nacos/**

未能路由到指定的服务上，是哪个的原因

{
    "timestamp": "2020-04-01T08:43:23.857+0000",
    "path": "/nacos/getData",
    "status": 503,
    "error": "Service Unavailable",
    "message": "Unable to find instance for service-gateway-provider",
    "requestId": "54e26da2-2"
}

**Comment by lichaoyue** [comment]
group 不统一

**Comment by bibichuan** [comment]
group不统一，我的是统一的啊，还是报这个错

**Comment by shumtn** [comment]
> group不统一，我的是统一的啊，还是报这个错
兄弟你解决了吗？我也是报一样的错

**Comment by shumtn** [comment]
> group 不统一

这个问题怎么解决,都是在同一空间下也是同一个组，是版本问题么？

**Comment by bibichuan** [comment]
应该是版本的问题

**Comment by AIMWLI** [comment]
困扰2天了, 谁解决了记得回复我一下, 谢谢各位

**Comment by beichenhpy** [comment]
> 困扰2天了, 谁解决了记得回复我一下, 谢谢各位

gateway添加依赖
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
 </dependency>

**Comment by bibichuan** [comment]
<dependencyManagement>

        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.2.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>


        
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>





    </dependencies>
