### ISSUE TITLE
nacos1.2.0, 3-nodes cluster auto quit without any errors in logs

### ISSUE THREAD

**Issue by wencynyu** [alibaba/nacos#2572]
## Issue Description

nacos1.2.0, 3-nodes cluster auto quit without any errors in logs

### Describe what happened (or what feature you want)
I deploy a 3-nodes cluster(ip:xxx.xxx.xxx.10,xxx.xxx.xxx.11,xxx.xxx.xxx.12) in vm, and dispatch request to these nodes by nginx.

There is a node working normally at first, but a few minutes later, it quit automatically.

### Describe what you expected to happen
A node auto quit but without any exceptions

![捕获3](https://user-images.githubusercontent.com/30571888/78210074-908c6000-74db-11ea-8fbc-2def75cc3fe1.PNG)

![捕获1](https://user-images.githubusercontent.com/30571888/78210020-6aff5680-74db-11ea-9c05-84f127e868a8.PNG)

![捕获2](https://user-images.githubusercontent.com/30571888/78210024-6dfa4700-74db-11ea-8670-5b17918b61c0.PNG)

### Tell us your environment
vm ubuntu 18.04
java jdk1.8.0_211
nacos 1.2 cluster mode

**Comment by nkorange** [comment]
Check dmesg and /var/log/message

**Comment by wencynyu** [comment]
@nkorange thanks for your replying.I haven't use these command,but I'll try it in the future.
