### ISSUE TITLE
nacos service cache path default at root/ , how to change it

### ISSUE THREAD

**Issue by hanhuibing** [alibaba/nacos#2576]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1.   nacos client 启动后会缓存服务信息到本地root目录下：文件名如下

     DEFAULT_GROUP%40%40dubbo-consumer
     DEFAULT_GROUP%40%40dubbo-provider
     ....
2. 这个路径能改变吗？

**Comment by chuntaojun** [comment]
是{user.home}目录下，具体修改的话，设置jvm参数：com.alibaba.nacos.naming.cache.dir即可

```java
cacheDir = System.getProperty("com.alibaba.nacos.naming.cache.dir");
 if (StringUtils.isEmpty(cacheDir)) {
       cacheDir = System.getProperty("user.home") + "/nacos/naming/" + namespace;
}
```
