### ISSUE TITLE
nacos ，spring cloud can`t  use feigin  in   docker swarm

### ISSUE THREAD

**Issue by herozhou1314** [alibaba/nacos#2587]
1.Load balancer does not have available server for client
2.before use  nacos,eureka is ok
eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
3. network : overlay, and add profile:spring.cloud.inetutils.preferred-networks = 10.10.0
all the micro service all in the same network segment (like 10.10.0.xx)
I try this :https://blog.csdn.net/doinbb/article/details/103457021 
but it not work.
Did I miss any configuration？Do nacos has the same function like eureka？
I just want to  nepxion discovery（https://github.com/Nepxion/Discovery），
it trouble me for flew days ，thinks.

**Comment by jsonlisky** [comment]
I have the same problem!!
