### ISSUE TITLE
v1.2.1, Open API, Get configurations, namespace、tenant 找不到配置

### ISSUE THREAD

**Issue by Fenhy** [alibaba/nacos#2588]
## Issue Description
想整合 sentinel 的持久化, 独立命名空间, 总是读取不到配置.
排查后发现 nacos-client里的请求返回null

通过API请求配置时, 加上"命名空间"的参数, 就返回"config data not exist"了
文档: [Get configurations](https://nacos.io/en-us/docs/open-api.html#1.1)

在v1.1.4的时,  测试传参不使用"tenant" , 改成使用"namespace" 还能获取到.
刚刚试了v1.2.1 , 无论使用"tenant"、"namespace" 都提示不存在.

现在只能不使用命名空间, 去请求.

### Describe what happened (or what feature you want)
nacos配置界面 - 命名空间:default
![image](https://user-images.githubusercontent.com/16318946/78499333-a8394200-7782-11ea-8a8f-a7708cea367e.png)

请求结果
![image](https://user-images.githubusercontent.com/16318946/78499337-b71ff480-7782-11ea-8097-4b1d931e3a40.png)

nacos配置界面 - 命名空间:demo-cloud-alibaba-sentinel-rule
![image](https://user-images.githubusercontent.com/16318946/78499266-39f47f80-7782-11ea-9fe2-e9302fdf33ac.png)

请求"tenant"传参结果
![image](https://user-images.githubusercontent.com/16318946/78499294-5e505c00-7782-11ea-9345-788813cbb99c.png)

请求"namespace"传参结果
![image](https://user-images.githubusercontent.com/16318946/78499310-7cb65780-7782-11ea-9e77-7a2204a888d4.png)

还以为是新增的RBAC导致, 去给ROLE_ADMIN授权了命名空间, 也还是不行.
![image](https://user-images.githubusercontent.com/16318946/78499381-ec2c4700-7782-11ea-92cb-05e5a2ce42ea.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
本地单机, nacos v1.2.1, mysql 5.7.24 持久.

**Comment by wranglerlmx** [comment]
I have the same problem...
I configured according to dubbo official document, the parameter "nacos: //127.0.0.1: 8848? Namespace = xxx" is invalid, it is automatically recognized as PUBLIC...
I'm going crazy...
use V1.2.1

**Comment by wuyoushan** [comment]
![image](https://user-images.githubusercontent.com/17586907/79842252-1caeea80-83eb-11ea-8cff-3cfe5fd035e2.png)

![image](https://user-images.githubusercontent.com/17586907/79842494-77e0dd00-83eb-11ea-8ea6-fce96649d292.png)


http://localhost:8848/nacos/v1/cs/configs?dataId=ccc&group=DEFAULT_GROUP&tenant=aa 是可以的。

http://localhost:8848/nacos/v1/cs/configs?dataId=ccc&group=DEFAULT_GROUP&tenant=ssssss 就会出现上面的错误

demo-cloud-alibaba-sentinel-rule这个值是命名空间名称，而不是命名空间id,这个很容易搞混了。所以。传tenant的值应该去命名空间中查看demo-cloud-alibaba-sentinel-rule的命名空间id是什么。传这个值就可以请求成功了
