### ISSUE TITLE
咋啦老哥，这是哪里if/else又写反了？

### ISSUE THREAD

**Issue by missfmaster** [alibaba/nacos#2592]
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/13460299/78712869-e9c91900-794b-11ea-991a-c08f9a9571f5.png">

死循环了，不停去抓取配置，可是配置根本没有改变啊、版本1.2.1

**Comment by amenema** [comment]
俺也一样，不过经过测试，应该是自动刷新配置任务的问题，这个任务默认为200ms执行一次，我这边把refresh 改为false就没有了。你可以试一下，看看是不是这个问题。

**Comment by Amber125208** [comment]
我也有这个问题

**Comment by amenema** [comment]
这应该是配置格式不正确。我也碰见这个问题了，修改为正确的格式后，问题解决。

**Comment by alwaysBillly** [comment]
我有一次namespace配置错了，也导致死循环

**Comment by chuntaojun** [comment]
already fix in 1.3.0-beta，Or you can download version 1.2.1 again
