### ISSUE TITLE
nacos 1.2.1Permission management error

### ISSUE THREAD

**Issue by zhangkun25** [alibaba/nacos#2593]
## Issue Description
The permission control module reported an error
Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
1.When authorizing a newly added user, the ROLE_ADMIN role is prompted that it cannot be created
2.Adding a new permission in the permission management module indicates that the newly added permission does not exist
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
linux centos7.5

**Comment by zhangkun25** [comment]
![权限管理添加权限错误](https://user-images.githubusercontent.com/61378996/78735340-29f4bf80-797d-11ea-93d8-03f47de55271.png)
![用户角色绑定错误](https://user-images.githubusercontent.com/61378996/78735349-311bcd80-797d-11ea-9f4b-b8a2db475ead.png)

**Comment by wolfgangzhu** [comment]
ROLE_ADMIN is global admin role, which can't be created by console(assigned to any user), so 'ROLE_ADMIN is not permitted to create' (actually user can't be assign to ROLE_ADMIN)
