### ISSUE TITLE
Front end no request to backend

### ISSUE THREAD

**Issue by jay2033** [alibaba/nacos#2594]
## Issue Description

When nacos auth enabled and user click a no permission namespace in Configurations page, it pop-up authorization failed. After that click other namespace which user has permission there's no request to backend. 

Type: *bug report*

### Describe what happened (or what feature you want)
No request to backend

### Describe what you expected to happen
Front end should send request to backend to get configs of the namespace which he had clicked and has permission.

### How to reproduce it (as minimally and precisely as possible)

1.  
2. 
3.

**Comment by lialun** [comment]
同样的问题
