### ISSUE TITLE
nacos的openAPI可以上传配置文件吗？

### ISSUE THREAD

**Issue by Rubbernecker** [alibaba/nacos#2597]
我现在想要通过openAPI发布配置，可是我发现通过http请求添加properties配置，无法直接添加配置文件，如果使用脚本读取文件，又无法对配置进行换行，变成下面这样
![微信截图_20200408180951](https://user-images.githubusercontent.com/62733397/78772333-2d5f6980-79c4-11ea-897a-b3d7668cb4ca.png)

请问应该怎么导入多行的properties配置

**Comment by chuntaojun** [comment]
直接复制文本内容进去吧

**Comment by 18256086350** [comment]
请问上传配置文件zip包是需要什么格式吗？一直报错
{"code":100003,"message":"未读取到合法数据","data":{"succCount":0}}

**Comment by chuntaojun** [comment]
> 请问上传配置文件zip包是需要什么格式吗？一直报错
> {"code":100003,"message":"未读取到合法数据","data":{"succCount":0}}

必须是nacos导出的zip才可以
