### ISSUE TITLE
1.2.1版本服务列表刷新偶现部分应用显示触发保护阈值显示或者部分应用不显示

### ISSUE THREAD

**Issue by dongdong112233** [alibaba/nacos#2598]
1.2.1版本服务列表刷新偶现部分应用显示触发保护阈值显示或者部分应用不显示，服务绝对都是正常的，但是刷新服务列表页面会偶现触发保护阈值显示或者部分应用不显示的问题，所刷新几次总会出现

**Comment by dongdong112233** [comment]
补充说明下：是Windows测试在本地启动的3个端口做的集群，单机启动好像没有这个显示问题。集群节点都是正常的。

**Comment by youkennkyou** [comment]
我也是，一直按F5刷新页面，就会显示健康实例数不正确，现在不知道只是页面问题还是服务器也这么返回给客户端的

**Comment by liugongliushang** [comment]
我也是遇到了相同的问题，单机还好，集群就不行了，这要是生产出现这种问题是不是有点坑啊，重视一下吧！！！

**Comment by dongdong112233** [comment]
问题已经解决了，windows系统本地启动集群的时候不能使用127.0.0.1加不同端口号启动，需要改为局域网本机的ip地址，否则就会发生服务发现等相关问题。希望可以进一步优化。
