### ISSUE TITLE
apache dubbo 2.7.5 +nacos 1.2.0 认证403（nacos.core.auth.enabled=true）

### ISSUE THREAD

**Issue by liuyanghui** [alibaba/nacos#2599]
pom环境 ：apache dubbo 2.7.5 +nacos 1.2.1（nacos 1.2.0 一样） 
修改 nacos 的配置：nacos.core.auth.enabled=true
无法把服务注册到nacos ，一直提示403 
错误异常如下：
2020-04-08 20:57:58 ERROR org.apache.dubbo.configcenter.support.nacos.NacosDynamicConfiguration:243 -  [DUBBO] <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Apr 08 20:57:58 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>, dubbo version: 2.7.5, current host: 192.168.101.2
2020-04-08 20:57:59 ERROR com.alibaba.nacos.client.config.impl.ClientWorker:394 - [fixed-127.0.0.1_8848] [check-update] get changed dataId error, code: 403

**Comment by wolfgangzhu** [comment]
Current dubbo's nacos module doesn't support user-password authentication. if you want to use nacos' auth ability, you should add following code to dubbo's source and compile it.

in NacosDynamicConfiguration.java
```java
    private static void setProperties(URL url, Properties properties) {
        putPropertyIfAbsent(url, properties, NACOS_NAMING_LOG_NAME);
        putPropertyIfAbsent(url, properties, IS_USE_CLOUD_NAMESPACE_PARSING);
        putPropertyIfAbsent(url, properties, IS_USE_ENDPOINT_PARSING_RULE);
        putPropertyIfAbsent(url, properties, ENDPOINT);
        putPropertyIfAbsent(url, properties, ENDPOINT_PORT);
        putPropertyIfAbsent(url, properties, NAMESPACE);
        putPropertyIfAbsent(url, properties, ACCESS_KEY);
        putPropertyIfAbsent(url, properties, SECRET_KEY);
        putPropertyIfAbsent(url, properties, RAM_ROLE_NAME);
        putPropertyIfAbsent(url, properties, CONTEXT_PATH);
        putPropertyIfAbsent(url, properties, CLUSTER_NAME);
        putPropertyIfAbsent(url, properties, ENCODE);
        putPropertyIfAbsent(url, properties, CONFIG_LONG_POLL_TIMEOUT);
        putPropertyIfAbsent(url, properties, CONFIG_RETRY_TIME);
        putPropertyIfAbsent(url, properties, MAX_RETRY);
        putPropertyIfAbsent(url, properties, ENABLE_REMOTE_SYNC_CONFIG);
        putPropertyIfAbsent(url, properties, NAMING_LOAD_CACHE_AT_START, "true");
        putPropertyIfAbsent(url, properties, NAMING_CLIENT_BEAT_THREAD_COUNT);
        putPropertyIfAbsent(url, properties, NAMING_POLLING_THREAD_COUNT);
        loadAuthProperties(url, properties);
    }

    private static void loadAuthProperties(URL url, Properties properties) {
        putPropertyIfNotEmpty(properties, USERNAME, url.getUsername());
        putPropertyIfNotEmpty(properties, PASSWORD, url.getPassword());
    }

    private static void putPropertyIfNotEmpty(Properties properties, String key, String propertyValue) {
        if (StringUtils.isNotEmpty(propertyValue)) {
            properties.put(key, propertyValue);
        }
    }
```

NacosNamingServiceUtils
```java
    private static void setProperties(URL url, Properties properties) {
        putPropertyIfAbsent(url, properties, NACOS_NAMING_LOG_NAME);
        putPropertyIfAbsent(url, properties, IS_USE_CLOUD_NAMESPACE_PARSING);
        putPropertyIfAbsent(url, properties, IS_USE_ENDPOINT_PARSING_RULE);
        putPropertyIfAbsent(url, properties, ENDPOINT);
        putPropertyIfAbsent(url, properties, ENDPOINT_PORT);
        putPropertyIfAbsent(url, properties, NAMESPACE);
        putPropertyIfAbsent(url, properties, ACCESS_KEY);
        putPropertyIfAbsent(url, properties, SECRET_KEY);
        putPropertyIfAbsent(url, properties, RAM_ROLE_NAME);
        putPropertyIfAbsent(url, properties, CONTEXT_PATH);
        putPropertyIfAbsent(url, properties, CLUSTER_NAME);
        putPropertyIfAbsent(url, properties, ENCODE);
        putPropertyIfAbsent(url, properties, CONFIG_LONG_POLL_TIMEOUT);
        putPropertyIfAbsent(url, properties, CONFIG_RETRY_TIME);
        putPropertyIfAbsent(url, properties, MAX_RETRY);
        putPropertyIfAbsent(url, properties, ENABLE_REMOTE_SYNC_CONFIG);
        putPropertyIfAbsent(url, properties, NAMING_LOAD_CACHE_AT_START, "true");
        putPropertyIfAbsent(url, properties, NAMING_CLIENT_BEAT_THREAD_COUNT);
        putPropertyIfAbsent(url, properties, NAMING_POLLING_THREAD_COUNT);
        loadAuthProperties(url, properties);
    }

    private static void loadAuthProperties(URL url, Properties properties) {
        putPropertyIfNotEmpty(properties, USERNAME, url.getUsername());
        putPropertyIfNotEmpty(properties, PASSWORD, url.getPassword());
    }

    private static void putPropertyIfNotEmpty(Properties properties, String key, String propertyValue) {
        if (StringUtils.isNotEmpty(propertyValue)) {
            properties.put(key, propertyValue);
        }
    }
```
and in your configuration, modify the registry url to 
`nacos://username:password@127.0.0.1:8848`

**Comment by rockjing** [comment]
Dear,
just follow this question, I like to create a new version based on dubbo-2.7.6, but when I rename revision value from 2.7.6 to 2.7.6.1-SNAPSHOT to build the specific version with ur guide, it came some compile errors. Could u give me some comments?

**Comment by ych5680** [comment]
https://github.com/apache/dubbo-spring-boot-project/releases

**Comment by ych5680** [comment]
使用2.7.8的  dubbo-spring-boot-starter 可以解决这个问题

**Comment by reminisences** [comment]
> 使用2.7.8的 dubbo-spring-boot-starter 可以解决这个问题

nacos开启auth后, dubbo注册问题同上, 403 unknown user! 您项目的版本能告知下吗？
依赖如下：
dubbo/dubbo-spring-boot-starter 2.7.8
nacos/nacos-client 1.4.0
nacos-spring-context 1.0.0
nacos-config-spring-boot-starter 0.2.7

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    parameters:
      namespace: ${nacos.namespace}
      username: ${nacos.username} #这里配置不管用
      password: ${nacos.password} #这里配置不管用
    address: nacos://${nacos.username}:${nacos.password}@${nacos.service-address}:${nacos.port}
    group: ${nacos.group}
    username: ${nacos.username}  #这里配置不管用
    password: ${nacos.password}  #这里配置不管用

**Comment by reminisences** [comment]
> 使用2.7.8的 dubbo-spring-boot-starter 可以解决这个问题

求yaml里面dubbo的配置？
