### ISSUE TITLE
vipserver's pull and push mechanism performs poor comparing with longpulling

### ISSUE THREAD

**Issue by wei7202839** [alibaba/nacos#26]
每隔一秒以阻塞的形式排队拉取所有的domain信息,假设在服务发现场景,某个应用依赖了100个服务,
每秒种要创建100个短连接拉取,一方面客户端开销大,另外一方面服务端查询压力也大;

换成http2在一个连接上以非阻塞形式完成推拉的所有工作,情况会好很多;自定义非阻塞的双工协议也能起到同样的效果,但这都会增加client的依赖,不比jdk原生的httpclient好

如果采取diamond的longpulling形式,通过md5或者lastRefreshTime比对,每次都可以批量发送domain,是否可行?

**Comment by wei7202839** [comment]
复杂数据结构下的md5比较难算,但这似乎也不是个瓶颈

**Comment by nkorange** [comment]
正常情况下，UDP推送会保证数据实时性。此时这个轮询时间会由服务端下发的配置覆盖，默认为10秒。

By default the UDP push is enabled and the change of domain data is synchronized through this channel. This query cycle is then overwritten to 10 seconds by the configuration of server.

**Comment by wei7202839** [comment]
10秒一次会缓解这个问题，每次拉取数据的时候还是觉得走批量+md5(or版本号)的形式好一些
类似于diamond的探测请求   可以节省网络开销

**Comment by nkorange** [comment]
在有UDP推送的情况下，这个10秒轮询不会拉取数据，只作为心跳。如果推送没有打开，确实这种拉取策略可以改进。

In the condition UDP push is enabled, this 10-seconds polling is just a way of heartbeat. If push is disabled, yes you are correct.
