### ISSUE TITLE
The configuration list query does not support fuzzy query in the console.

### ISSUE THREAD

**Issue by hxy1991** [alibaba/nacos#260]
![image](https://user-images.githubusercontent.com/2517258/48325584-52399b00-e671-11e8-840e-52b3d7de0d1a.png)

![image](https://user-images.githubusercontent.com/2517258/48325587-549bf500-e671-11e8-9173-42c02b6cd53c.png)

**Comment by jameslcj** [comment]
you should use "*", like "micro-serviec-*"

**Comment by jameslcj** [comment]
you should use "\*", like "micro-serviec-\*"

**Comment by jameslcj** [comment]
you should add "\*", like "micro-serviec-\*"
