### ISSUE TITLE
开启认证后discovery的用户必须是nacos，换个用户会403

### ISSUE THREAD

**Issue by camelweiming** [alibaba/nacos#2600]
spring.cloud.nacos.config.username=app
spring.cloud.nacos.config.password=app
spring.cloud.nacos.config.contextPath=/nacos
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos

这样配置可以的，但是discovery.username和password换成app的画，就会403，密码都是正确的

**Comment by chuntaojun** [comment]
我这里使用并没有复现你的问题

**Comment by jsxiao** [comment]
我遇到了同样的问题, 请问你得问题解决了吗？

**Comment by jsxiao** [comment]
server 版本 1.3.2  
client 版本 1.2.1

**Comment by SessionBest** [comment]
碰到同样问题.nacos1.4  
client 1.4
