### ISSUE TITLE
登陆问题，不用密码，就可以访问

### ISSUE THREAD

**Issue by hqisog** [alibaba/nacos#2608]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
部署完成 访问 http://xxx:8488/nacos 后 直接跳转到 
http://xxxx:8848/nacos/index.html#/configurationManagement?dataId=&group=&appName=&namespace=
无需密码登陆就可以访问

### Describe what you expected to happen

需要登陆密码 才能登陆

### How to reproduce it (as minimally and precisely as possible)

1. 直接部署 1.2的nacos 就可以发现这个问题
2. 
3. 

### Tell us your environment

centos7

**Comment by chuntaojun** [comment]
是否启用了权限控制，1.2.0的登陆和权限控制是绑定在一起的，可以看下这个文档：https://nacos.io/zh-cn/blog/nacos%201.2.0%20guide.html

**Comment by hqisog** [comment]
我的意思是 我部署好后，页面上访问
http://xxx:8488/nacos  后没有跳转到 登陆页面，反而跳到了其他的页面，跳过了登陆 直接进到 管理界面了。这个和权限没关系 我也没有设置；就是nacos 用户。

**Comment by chuntaojun** [comment]
到了1.2.0就是这样子的，你没启用权限控制，不会有登陆页面

发自我的iPhone

在 2020年4月10日，14:20，Leno.Han <notifications@github.com> 写道：

﻿

我的意思是 我部署好后，页面上访问
http://xxx:8488/nacos 后没有跳转到 登陆页面，反而跳到了其他的页面，跳过了登陆 直接进到 管理界面了。这个和权限没关系 我也没有设置；就是nacos 用户。

**Comment by hqisog** [comment]
启用权限控制后是可以 跳转到登陆页面了
