### ISSUE TITLE
修改非DEFAULT_GROUP下的服务实例的权重无效，原因serviceName: service clusterName: DEFAULT ip: 10.169.222.90 port: 8080 ephemeral: true weight: 100 enabled: false metadata: { 	"preserved.register.source": "SPRING_CLOUD", 	"group": "Kunpeng" } namespaceId: dev 发送请求时没获取表单中的分组名称

### ISSUE THREAD

**Issue by vastliuzxc** [alibaba/nacos#2609]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by vastliuzxc** [comment]
导致nacos.naming.web下的DistroFilter始终获取到的都是DEFAULT_GROUP组

**Comment by Dong-2017** [comment]
![image](https://user-images.githubusercontent.com/5540758/79065486-29dd2280-7ce3-11ea-9fed-7f437d5e5145.png)
![image](https://user-images.githubusercontent.com/5540758/79065515-6f99eb00-7ce3-11ea-8d7c-ecce779ee717.png)

![image](https://user-images.githubusercontent.com/5540758/79065547-b8ea3a80-7ce3-11ea-8cf9-a0c6dc74ff03.png)


![image](https://user-images.githubusercontent.com/5540758/79065527-8e987d00-7ce3-11ea-983d-55d247917251.png)

![image](https://user-images.githubusercontent.com/5540758/79065565-e7681580-7ce3-11ea-8866-abead47f86de.png)

今天试用Nacos 1.2.1版本时也发现这个问题，编辑自定义分组时表单中没有把group字段带上，导致修改改后自定义分组的记录信息没有更新【上图1、2、3】，返回服务列表时会多出一条DEFAULT_GROUP服务记录【上图4】

**Comment by mark6688** [comment]
希望该功能能够尽快迭代上线。

**Comment by vastliuzxc** [comment]
> 希望该功能能够尽快迭代上线。

我暂时的处理方式是在
com.alibaba.nacos.naming.web.DistroFilter下的doFilter方法中通过元数据获取。客户端在元数据中配置了分组名称
metadata:
          group: ${spring.cloud.nacos.discovery.group}

**Comment by mark6688** [comment]
> > 希望该功能能够尽快迭代上线。
> 
> 我暂时的处理方式是在
> com.alibaba.nacos.naming.web.DistroFilter下的doFilter方法中通过元数据获取。客户端在元数据中配置了分组名称
> metadata:
> group: ${spring.cloud.nacos.discovery.group}

感谢提供解决方案，在分组支持之前可以先用这种方式，感谢~
