### ISSUE TITLE
dubbo的元数据发布到配置中心的问题

### ISSUE THREAD

**Issue by nyvi** [alibaba/nacos#2613]
dubbo新增了元数据中心，如果选用nacos作为注册中心，他会把元数据中心发布到nacos配置中心。
![image](https://user-images.githubusercontent.com/20055867/79086281-15923780-7d6e-11ea-9e09-02700cbbeade.png)
能否新增一个元数据中心的菜单，隔离出来

**Comment by chuntaojun** [comment]
> dubbo新增了元数据中心，如果选用nacos作为注册中心，他会把元数据中心发布到nacos配置中心。
> ![image](https://user-images.githubusercontent.com/20055867/79086281-15923780-7d6e-11ea-9e09-02700cbbeade.png)
> 能否新增一个元数据中心的菜单，隔离出来

This is a design problem for dubbo

**Comment by mercyblitz** [comment]
It's not an issue, Dubbo 2.7.0+ could use Nacos as the metadata center.

**Comment by skyding1212** [comment]
这个问题最后怎么解决了？同问！！！
