### ISSUE TITLE
Which configuration files are suitable for nacos?

### ISSUE THREAD

**Issue by kqkdChen** [alibaba/nacos#2614]
nacos is easy to use and will be configured soon, but I am a bit puzzled now which configuration files should be put into nacos?**

I tried to extract some middleware and business configuration, and created namespaces in different environments. Is this reasonable?
![image](https://user-images.githubusercontent.com/41674301/79086412-85a0bd80-7d6e-11ea-9b12-c3cbe92bc9d4.png)
Also, after using nacos for these, I deleted the original multiple application.yml in the project resource folder, because the configuration will be pulled from the nacos, but I always feel very awkward, because the first time to viewIt ’s better to go to the nacos for configuration, so it ’s more convenient to view directly in the project, so I want to ask how do you deal with this situation?Or tell me a best practice for nacos, thank you!

**Comment by kqkdChen** [comment]
In short, should I keep some application.yml configuration files in the project?

**Comment by chuntaojun** [comment]
命名空间是用于处理环境隔离的，因此对于“并在不同的环境中创建命名空间”是合理的。

实际上，任何配置都可以用nacos进行管理，但是这样的话，可能需要组件进行一些改造。比如，如果你想将nginx的配置进行管理，那么是需要其他的一些组件进行配合的

**Comment by kqkdChen** [comment]
> 命名空间是用于处理环境隔离的，因此对于“并在不同的环境中创建命名空间”是合理的。
> 
> 实际上，任何配置都可以用nacos进行管理，但是这样的话，可能需要组件进行一些改造。比如，如果你想将nginx的配置进行管理，那么是需要其他的一些组件进行配合的

那我想问下，把配置都放在配置中心的话项目里面还需要保留application.yml吗？总觉得resource下没有application.yml看起来怪怪的

**Comment by chuntaojun** [comment]
> > 命名空间是用于处理环境隔离的，因此对于“并在不同的环境中创建命名空间”是合理的。
> > 实际上，任何配置都可以用nacos进行管理，但是这样的话，可能需要组件进行一些改造。比如，如果你想将nginx的配置进行管理，那么是需要其他的一些组件进行配合的
> 
> 那我想问下，把配置都放在配置中心的话项目里面还需要保留application.yml吗？总觉得resource下没有application.yml看起来怪怪的

需要的，有一些配置内容还是需要留下，主要还是看这些配置内容的读取时机在spring的启动环节中的那个环节，如果在EnvironmentPostProcessor之前，那应该就不行了

**Comment by chuntaojun** [comment]
同时，由于nacos-client在spring整合中，需要读取相应的配置信息，而这个基本是要在yml文件里面的

**Comment by kqkdChen** [comment]
> > > 命名空间是用于处理环境隔离的，因此对于“并在不同的环境中创建命名空间”是合理的。
> > > 实际上，任何配置都可以用nacos进行管理，但是这样的话，可能需要组件进行一些改造。比如，如果你想将nginx的配置进行管理，那么是需要其他的一些组件进行配合的
> > 
> > 
> > 那我想问下，把配置都放在配置中心的话项目里面还需要保留application.yml吗？总觉得resource下没有application.yml看起来怪怪的
> 
> 需要的，有一些配置内容还是需要留下，主要还是看这些配置内容的读取时机在spring的启动环节中的那个环节，如果在EnvironmentPostProcessor之前，那应该就不行了

好的，谢谢。我还想获得一些详细的参考，有生产实践的总结吗？^_^
