### ISSUE TITLE
1.2.0开启权限验证后，openapi 无法连接nacos

### ISSUE THREAD

**Issue by hqisog** [alibaba/nacos#2616]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
需要带上url参数：accessToken

**Comment by hqisog** [comment]
有实例吗？

**Comment by hqisog** [comment]
嗯 可以拿到

**Comment by hqisog** [comment]
实例如下
1 先访问login 接口，拿到access_token 
2 如下访问 get 配置信息

http://*******:8848/nacos/v1/cs/configs?access_token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTU4Njc4MjExM30.Pqqu1h0mqcwXgvPRxJM24LIyrp4lsm1UTwJXy-H1W0k


结果
{
    "timestamp": "2020-04-13T07:48:56.529+0000",
    "status": 403,
    "error": "Forbidden",
    "message": "unknown user!",
    "path": "/nacos/v1/cs/configs"
}

具体怎么请求，希望给个实例？

**Comment by chuntaojun** [comment]
是accessToken，驼峰的

**Comment by hqisog** [comment]
nice   可以了
