### ISSUE TITLE
[1.2.1]The config service sometimes generates MD5 with a length of 31

### ISSUE THREAD

**Issue by amenema** [alibaba/nacos#2618]
This writing method in the **com.alibaba.nacos.common.utils.getMD5(byte[] bytes)**  tool class of the server will lead to the generation of MD5 with length of 31 under specific conditions.But the **com.alibaba.nacos.client.config.utils.getMD5String(String content)** tool of the client does not find the problem at present, so it will cause the MD5 generated by the client and the server to be inconsistent. So that the client always requests to update the corresponding data ID.    
__
客户端与服务端对config.content 的md5编写方式不一致，导致在特定参数下，服务端生成了31位的MD5，从而使客户端一直刷新数据。BigInteger.toString(16)会删除前导0，所以不应该用这种方式。
### case

```
bailing:
 http:
  protocol: http
```

**Comment by wangweizZZ** [comment]
@i will solve it@

**Comment by connnywilmeringBA** [comment]
https://www.youtube.com/watch?v=uFYQv9HDAXk
