### ISSUE TITLE
1.2.1 控制台无法保存properties类型的配置

### ISSUE THREAD

**Issue by silverlight** [alibaba/nacos#2622]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
在控制台中输入properties信息之后，点击发布没有任何反应。无法保存成功，发现是debug报错。启动方式为docker standalone，版本1.2.1。浏览器为chrome，尝试过清理缓存，更换浏览器均无效。
![image](https://user-images.githubusercontent.com/18061452/79105615-94559780-7da3-11ea-945d-6de5586596e7.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by letian-tang** [comment]
chrome  77.0.3865.90 可以保存

**Comment by silverlight** [comment]
> chrome 77.0.3865.90 可以保存

我发现一带注释就失败，第一次失败之后即使把注释删除都无法发布。很明显是JS的问题了

**Comment by dxch** [comment]
也遇到了这个问题。
先写成text，保存之后，再次点进去选properties保存就成功了

**Comment by silverlight** [comment]
> 也遇到了这个问题。
> 先写成text，保存之后，再次点进去选properties保存就成功了

我的做法是先保存一个不带注释的，然后再修改哈哈
