### ISSUE TITLE
nacos.core.auth.enabled=false，为何控制台仍需要登录？

### ISSUE THREAD

**Issue by mostcool** [alibaba/nacos#2624]
下载最新 nacos-server-1.2.1.zip，解压后直接单机运行，conf/application.properties 里的 nacos.core.auth.enabled=false，但打开的控制台仍然需要输入用户名密码，这是为什么？

**Comment by letian-tang** [comment]
nacos.core.auth.enabled=false 意思是client注册，读配置不需要username和password
控制台登录还是需要的

**Comment by mostcool** [comment]
> nacos.core.auth.enabled=false 意思是client注册，读配置不需要username和password
> 控制台登录还是需要的

理解错了，谢谢。
