### ISSUE TITLE
nacos配置中心在工程实施中的疑问

### ISSUE THREAD

**Issue by insiderys** [alibaba/nacos#2625]
我们的项目之前用的spring cloud config server，现在想切换到nacos，之前项目里已经有一堆配置文件了，现在要继续使用这些配置文件，好像只有一种方法，就是下面的步骤：
1、把配置文件按照指定格式打包成zip文件
2、启动nacos
3、通过nacos导入功能把配置文件导入
4、启动其它服务
这一套步骤在现场工程实施的时候感觉不方便，有没有什么方法可以在打包的时候提前把配置文件放到nacos中，第一次启动时可以不去执行这个配置文件的导入过程？

**Comment by 18256086350** [comment]
可以考虑通过脚本的形式导入配置，linux环境下你的配置zip包能导入成功吗

**Comment by insiderys** [comment]
> 可以考虑通过脚本的形式导入配置，linux环境下你的配置zip包能导入成功吗

linux下配置zip包可以正常导入的，你说的脚本形式导入是指把每个kev-value写到sql脚本吗？可是我是很多的properties文件

**Comment by 18256086350** [comment]
你是单机版还是集群版，上传的zip包

**Comment by insiderys** [comment]
> 你是单机版还是集群版，上传的zip包

单机版

**Comment by yanlinly** [comment]
目前确实只有这个方式，因为迁移场景比较小，大部分用户配置个数优先，因此我们只提供了自己的导入导出工具。
如果配置比较多，可以调用api写一个简单脚本搞一下。
