### ISSUE TITLE
When I add a new configuration end of a blank line, there  will have a problem :ClientWorker: [fixed-xxx].

### ISSUE THREAD

**Issue by zhoufangy** [alibaba/nacos#2626]
## Issue Description
Type: bug report
When I add a new configuration end of a blank line, there  will have a problem :ClientWorker: [fixed-xxx]. 
使用配置中心时，当配置文件末尾空行时会触发ClientWorker: [fixed-xxx不断请求，去除末尾空行后项目运行正常

### Describe what happened (or what feature you want)
When there is a space at the end of the configuration file, ClientWorker will continuously initiate requests until the JVM resources are exhausted.
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gdsj8e6c2wj30zu0ja0wz.jpg)
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gdsj9j8epsj32fc0p2ajo.jpg)

### Describe what you expected to happen
If the end of the configuration file is a blank line, give the user a warn, or automatically remove it.
 
### How to reproduce it (as minimally and precisely as possible)
1. add or update a configuration file 
2. add a blank line at the end, and remove all spaces in the line
3. run the service

### Tell us your environment
jdk1.8.0_121
nacos-client:1.1.4
nacos-config:2.2.0.RELASE

**Comment by wolfgangzhu** [comment]
Did you use nacos-config with version 2.2.0.RELASE?

**Comment by zhoufangy** [comment]
> Did you use nacos-config with version 2.2.0.RELASE?

Yes,I did.
