### ISSUE TITLE
nacos 控制台发布配置BUG

### ISSUE THREAD

**Issue by xiongchun** [alibaba/nacos#2627]
**环境**
LINUX CHROME
NACOS: V1.2.0
**问题**
当配置类型为properties时候，如果配置中有换行，则提交按钮会JS报错。没法发布配置。
```
Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined
```
![2020-04-14 11-30-43屏幕截图](https://user-images.githubusercontent.com/4091000/79183209-6d4ea280-7e43-11ea-8bb9-cd22c7617b0f.png)

**Comment by gaofeicm** [comment]
配置格式先选择text保存，保存后再编辑成你想要的格式。

**Comment by osworks** [comment]
> 配置格式先选择text保存，保存后再编辑成你想要的格式。

按照你说的是能保存了　但这也太折腾了　而且虽然保存成功　会有一个提示　说配置格式有问题　是否要继续保存

**Comment by gaofeicm** [comment]
nacos在发布Properties格式配置时，出现了一行内没有"="的情况，就会出现“配置格式有问题”这个提示。

**Comment by gaojjx** [comment]
> nacos在发布Properties格式配置时，出现了一行内没有"="的情况，就会出现“配置格式有问题”这个提示。

连注释都不能有吗

**Comment by wfnuser** [comment]
@chuntaojun I'm working on it. Maybe you can assign me.😄

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2574

**Comment by KomachiSion** [comment]
Fixed in new version
