### ISSUE TITLE
/nacos/v1/ns/operator/metrics 403没有权限

### ISSUE THREAD

**Issue by cai-ti** [alibaba/nacos#2636]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

/nacos/v1/ns/operator/metrics 403没有权限

**Comment by pppPositive** [comment]
你是不是开启的auth功能，尝试在operator之前使用login，获取token，然后将获取的token加在你的operator请求后面试试

**Comment by vikde** [comment]
这个在nacos 1.2.1中我也遇到了这个问题，也对问题进行了描述，可以看看是我理解错了，还是官方还在开发中
https://www.jianshu.com/p/560ba0d67c50

**Comment by cai-ti** [comment]
> 这个在nacos 1.2.1中我也遇到了这个问题，也对问题进行了描述，可以看看是我理解错了，还是官方还在开发中
> https://www.jianshu.com/p/560ba0d67c50

com.alibaba.nacos.naming.controllers.OperatorController#metrics的权限注解使用@Secured(parser = NamingResourceParser.class, action = ActionTypes.READ)来解析这个请求地址是可以的

**Comment by cai-ti** [comment]
> 你是不是开启的auth功能，尝试在operator之前使用login，获取token，然后将获取的token加在你的operator请求后面试试

服务端的权限注解问题@Secured(resource = "naming/metrics", action = ActionTypes.READ)这中方式，在控制台界面是没有地方可以分配这种资源权限的。需要解析器去转换，并且需要修改权限管理页面

**Comment by pppPositive** [comment]
> > 你是不是开启的auth功能，尝试在operator之前使用login，获取token，然后将获取的token加在你的operator请求后面试试
> 
> 服务端的权限注解问题@secured(resource = "naming/metrics", action = ActionTypes.READ)这中方式，在控制台界面是没有地方可以分配这种资源权限的。需要解析器去转换，并且需要修改权限管理页面

在上传配置文件时也遇到了403权限问题，发现源码中有个tenant参数是当做namespaceId使用的，但是请求的时候并没有set到request中，导致后面获取tenengt的时候为空，从而导致资源通过正则匹配的时候一直为false，在请求上传配置文件的时候加上了tenant=命名空间ID后就能正常上传

**Comment by xiaoguolong** [comment]
Springcloud Alibaba是不是没有集成nacos登录获取token的功能

**Comment by kweny** [comment]
nacos 服务端权限解析问题，手动在 nacos 服务端的 permissions 表中插入一条这样的数据就可以——
role：角色名称
resource：naming/metrics
action：rw 或者 r
