### ISSUE TITLE
如何从nacos1.1.4升级到1.2.1呢  

### ISSUE THREAD

**Issue by dxch** [alibaba/nacos#2637]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Maijh97** [comment]
可以参考[文档](https://nacos.io/en-us/blog/nacos%201.1.0.html)

**Comment by suood** [comment]
先别升级,1.2.1 ,我安装了1.2.1之后无法创建yaml格式的配置.
`main.js:38 Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined
    at main.js:38
    at main.js:70
    at Array.<anonymous> (main.js:70)
    at main.js:70
    at r (main.js:33)
    at e (main.js:33)
    at a (main.js:70)
    at n.value (main.js:38)
    at main.js:70
    at e (main.js:33)`
貌似我得退回旧版本了.
