### ISSUE TITLE
1.2.1版本控制台没权限时持续loading问题

### ISSUE THREAD

**Issue by beforeborn** [alibaba/nacos#2639]
## Issue Description

1.2.1版本，开启权限校验nacos.core.auth.enabled=true后，对于非管理员用户，点击上方没有权限的namespace后，会提示没有权限，并有loading图案一直存在，无法进行后续操作。应属于前端问题。
该问题在1.2.0版本不存在。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
version 1.2.1

**Comment by rcfeng** [comment]
我也发现了这个问题，并且最好不展示没有权限的namespace更合理

**Comment by KomachiSion** [comment]
fixed by #2835
