### ISSUE TITLE
logback-spring日志文件如何放进nacos里

### ISSUE THREAD

**Issue by jie6mm** [alibaba/nacos#2643]
我的现在使用的是logback日志文件，放在项目的resources目录下，
我想把它放进nacos里面然后动态读取logback-spring.xml这个文件 请问该怎么做。。。。
急急急........

**Comment by chuntaojun** [comment]
自己调用nacos-client拉取这个配置并存储到resource目录下，注意，要在logback读取这个文件之前解决

**Comment by JIE6** [comment]
> 自己调用nacos-client拉取这个配置并存储到resource目录下，注意，要在logback读取这个文件之前解决

......我不太清楚要如何做.像你所说的 - 调用nacos-client拉取这个配置并存储到resource目录下

**Comment by dodolook8716** [comment]
> > 自己调用nacos-client拉取这个配置并存储到resource目录下，注意，要在logback读取这个文件之前解决
> 
> ......我不太清楚要如何做.像你所说的 - 调用nacos-client拉取这个配置并存储到resource目录下

我觉得nacos-client在拉取配置文件的时候, 日志都初始化好了吧 
 可以考虑通过 实现 EnvironmentPostProcessor  在本地配置文件读取后, 日志组件初始化前, 去拉取配置文件.

**Comment by jie6mm** [comment]
> > > 自己调用nacos-client拉取这个配置并存储到resource目录下，注意，要在logback读取这个文件之前解决
> > 
> > 
> > ......我不太清楚要如何做.像你所说的 - 调用nacos-client拉取这个配置并存储到resource目录下
> 
> 我觉得nacos-client在拉取配置文件的时候, 日志都初始化好了吧
> 可以考虑通过 实现 EnvironmentPostProcessor 在本地配置文件读取后, 日志组件初始化前, 去拉取配置文件.

你好今天有时间试了下你说的办法，我的实现逻辑是-通过实现EnvironmentPostProcessor在项目初始化之前通过http去拉取nacos里对应的配置文件内容，然后将内容存储在本地（项目里对应的resources目录下）.
![image](https://user-images.githubusercontent.com/37128250/83236908-e113f700-a1c6-11ea-844d-56240c62d6ff.png)
我感觉这样做并不对，有点low...而且这样存在的问题是 项目第一次启动时实际是没有logback-spring.xml的配置信息的 只有在第二次后启动ide才会将其编译进classes目录下。

**Comment by dodolook8716** [comment]
> > > > 自己调用nacos-client拉取这个配置并存储到resource目录下，注意，要在logback读取这个文件之前解决
> > > 
> > > 
> > > ......我不太清楚要如何做.像你所说的 - 调用nacos-client拉取这个配置并存储到resource目录下
> > 
> > 
> > 我觉得nacos-client在拉取配置文件的时候, 日志都初始化好了吧
> > 可以考虑通过 实现 EnvironmentPostProcessor 在本地配置文件读取后, 日志组件初始化前, 去拉取配置文件.
> 
> 你好今天有时间试了下你说的办法，我的实现逻辑是-通过实现EnvironmentPostProcessor在项目初始化之前通过http去拉取nacos里对应的配置文件内容，然后将内容存储在本地（项目里对应的resources目录下）.
> ![image](https://user-images.githubusercontent.com/37128250/83236908-e113f700-a1c6-11ea-844d-56240c62d6ff.png)
> 我感觉这样做并不对，有点low...而且这样存在的问题是 项目第一次启动时实际是没有logback-spring.xml的配置信息的 只有在第二次后启动ide才会将其编译进classes目录下。

我大致明白你的意思, 考虑实现 Ordered类, 在加载配置文件之前去执行. 看一下这个类 ConfigFileApplicationListener.DEFAULT_ORDER  在它之前加载应该 就可以了

**Comment by jie6mm** [comment]
> > > > > 自己调用nacos-client拉取这个配置并存储到resource目录下，注意，要在logback读取这个文件之前解决
> > > > 
> > > > 
> > > > ......我不太清楚要如何做.像你所说的 - 调用nacos-client拉取这个配置并存储到resource目录下
> > > 
> > > 
> > > 我觉得nacos-client在拉取配置文件的时候, 日志都初始化好了吧
> > > 可以考虑通过 实现 EnvironmentPostProcessor 在本地配置文件读取后, 日志组件初始化前, 去拉取配置文件.
> > 
> > 
> > 你好今天有时间试了下你说的办法，我的实现逻辑是-通过实现EnvironmentPostProcessor在项目初始化之前通过http去拉取nacos里对应的配置文件内容，然后将内容存储在本地（项目里对应的resources目录下）.
> > ![image](https://user-images.githubusercontent.com/37128250/83236908-e113f700-a1c6-11ea-844d-56240c62d6ff.png)
> > 我感觉这样做并不对，有点low...而且这样存在的问题是 项目第一次启动时实际是没有logback-spring.xml的配置信息的 只有在第二次后启动ide才会将其编译进classes目录下。
> 
> 我大致明白你的意思, 考虑实现 Ordered类, 在加载配置文件之前去执行. 看一下这个类 ConfigFileApplicationListener.DEFAULT_ORDER 在它之前加载应该 就可以了

好的，老哥，我先按照你说的去试试。谢谢指点

**Comment by yiTian66** [comment]
我也想做这个功能，想法是将nacos上配置文件写入项目资源目录下，在idea环境运行是没有问题的，但是打成jar包在服务器上运行就出现了问题。找不到资源目录。如果你将这个问题解决了，我想和你咨询下是如何解决的。方便的话加个微信详细聊一下。yitian2837

**Comment by jie6mm** [comment]
> 我也想做这个功能，想法是将nacos上配置文件写入项目资源目录下，在idea环境运行是没有问题的，但是打成jar包在服务器上运行就出现了问题。找不到资源目录。如果你将这个问题解决了，我想和你咨询下是如何解决的。方便的话加个微信详细聊一下。yitian2837

老哥。。。这个问题我还没解决。出现的问题跟你描述的应该是一样的。在本地启动时idea运行的不不是jar包而是编译后的项目所以可以把nacos的配置文件拉取到对应的classpath目录下，通过jar启动话这样好像是做不到的

**Comment by J-TIGGER** [comment]
这种做法没有任何意义，违背了nacos实时加载配置文件的初衷

**Comment by sunnywa** [comment]
有解决方案了吗？

**Comment by renho-r** [comment]
logging:
  config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml

**Comment by sophyallen** [comment]
logging.config url must end with .xml

**Comment by jie6mm** [comment]
logging:
config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml

**Comment by luodong918** [comment]
> logging:
> config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml

不好意思，我想请教一下这里面的tenant参数是什么？

**Comment by hzwjs** [comment]
> logging:
> config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml
通过url 在浏览器中是看访问到日志文件的，但是springboot启动的时候获取不到。

**Comment by luodong918** [comment]
> > logging:
> > config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml
> > 通过url 在浏览器中是看访问到日志文件的，但是springboot启动的时候获取不到。

你也是遇到这个问题了吗？nacos中配置logback？

**Comment by JansenChang** [comment]
> > > logging:
> > > config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml
> > > 通过url 在浏览器中是看访问到日志文件的，但是springboot启动的时候获取不到。
> 
> 你也是遇到这个问题了吗？nacos中配置logback？

问题解决了么

**Comment by JansenChang** [comment]
> > > logging:
> > > config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml
> > > 通过url 在浏览器中是看访问到日志文件的，但是springboot启动的时候获取不到。
> 
> 你也是遇到这个问题了吗？nacos中配置logback？
tenant这个是命名空间,你可以在nacos里面新增一个namespace,默认的是public,如果解决问题了记得联系我

**Comment by HaiboLee** [comment]
> 
dataId 要以xml结尾好像才能读取

**Comment by sunnywa** [comment]
您的邮件我已收到。——王琦

**Comment by peanut-w** [comment]
> logging: config: http://myserver:8848/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=log&dataId=logback-renho.xml

**Comment by peanut-w** [comment]
logging.config = ${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&username=${spring.cloud.nacos.config.username}&password=${spring.cloud.nacos.config.password}&dataId=log-config.xml

**Comment by sunnywa** [comment]
您的邮件我已收到。——王琦
