### ISSUE TITLE
配置中心无法全屏

### ISSUE THREAD

**Issue by tanzzj** [alibaba/nacos#2644]
Issue Description
配置中心配置屏幕无法全屏

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/28193069/79552890-3fc95980-80ce-11ea-94e5-218bf3b9bde3.png)
提示按F1全屏，但实际无效果

### Tell us your environment
centos7.6

**Comment by rcfeng** [comment]
同问

**Comment by LXHING999** [comment]
同问2

**Comment by cmshome** [comment]
同问3

**Comment by cmshome** [comment]
为啥不直接做成按钮呢？

**Comment by jiangliuhong** [comment]
同问4

**Comment by jay2033** [comment]
同问++

**Comment by jiawuhia123** [comment]
同问++++++++++++

**Comment by rcfeng** [comment]
@KomachiSion  这个问题看解决一下？ 好久了

**Comment by jiawuhia123** [comment]
> @KomachiSion 这个问题看解决一下？ 好久了

https://github.com/alibaba/nacos/issues/4349    放入了1.4.1版本处理

**Comment by HaoLi-Rainbow** [comment]
> > @KomachiSion 这个问题看解决一下？ 好久了
> 
> #4349 放入了1.4.1版本处理

不是吧，阿sir，我都nacos2.x了还不行

**Comment by yiyingcanfeng** [comment]
> > > @KomachiSion 这个问题看解决一下？ 好久了
> > 
> > 
> > #4349 放入了1.4.1版本处理
> 
> 不是吧，阿sir，我都nacos2.x了还不行

整了个油猴脚本，调了下编辑器高度，先凑合着用吧，也不指望官方最近能改了
```javascript
// ==UserScript==
// @name         Nacos配置中心编辑器高度调整
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// 改一下match，修改成你自己的nacos访问地址
// @match        http://127.0.0.1:8848/nacos/
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    document.getElementById('root').addEventListener("DOMSubtreeModified", function(){
        if(document.getElementById('container')){
            document.getElementById('container').style.height='800px' // 高度可自行修改
        }
    }, false);
})();
```

**Comment by KomachiSion** [comment]
duplicate with #3610
Fixed by https://github.com/alibaba/nacos/pull/5507 and https://github.com/alibaba/nacos/pull/5505
