### ISSUE TITLE
Fuzzy query can't be used. After many versions, there are always bugs

### ISSUE THREAD

**Issue by kitsrc** [alibaba/nacos#2645]
## Issue Description
Fuzzy query can't be used. After many versions, there are always bugs
模糊查询无法使用，历经好多版本，一直都存在的bug
![image](https://user-images.githubusercontent.com/23493090/79625682-29b6aa00-815d-11ea-8b22-33e5dd6fdc76.png)

Type: *bug report* 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Maijh97** [comment]
@i will solve it@
