### ISSUE TITLE
ConfigChangeEvent data is empty when config listener received new config for config type which is not properties or yml 

### ISSUE THREAD

**Issue by wolfgangzhu** [alibaba/nacos#2648]
## Issue Description

Type: *bug report* or *feature request*
 
### Describe what happened (or what feature you want)
When i use console to change config for some data id and group id,  using types except yml and proeprties, ConfigChangeEvent' data field is empty.  the following is the test screen shot.
![image](https://user-images.githubusercontent.com/62163512/79681742-0cfa9f00-824f-11ea-98c5-7dbd942d5315.png)

### Describe what you expected to happen
I think for AbstractConfigChangeListener, its data {ConfigChangeEvent}  should't be `Map<String, ConfigChangeItem> data;` because the config change listener is responsible for config when  config is changed, and the event should be maintained with old value, new value, and type. 
In current implementation, it will be confused when i change the config vlaue but the data of event is empty.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 1.2.1

**Comment by Maijh97** [comment]
By looking at the source code, I found that currently only yaml and properties formats are supported. If you need other formats, you need to extend them yourself. I am considering whether the framework can provide all types of support corresponding to Nacos console?

**Comment by chuntaojun** [comment]
Internally implemented SPI extension mechanism, inheritance com.alibaba.nacos.api.config.listener.ConfigChangeParser

**Comment by chuntaojun** [comment]
> By looking at the source code, I found that currently only yaml and properties formats are supported. If you need other formats, you need to extend them yourself. I am considering whether framework can provide all types of support corresponding to Nacos console? @chuntaojun Hope to get your suggestions. If possible, I will solve this problem

you can try to support json type, other type just use spi extension to resolve
