### ISSUE TITLE
the unique index "uk_role_permission" is too lang !!!!

### ISSUE THREAD

**Issue by jackieonway** [alibaba/nacos#2651]
when upgrading nacos to 1.2.1 , I excute the creat SQL statement for permissions,  MySQL has error “Specified key was too long; max key length is 767 bytes”，My MySql version is 5.6.0. so can make the index shorter?

**Comment by 15150759568** [comment]
Is the version of the mysql database, try version 5.7.24

**Comment by jackieonway** [comment]
But company's mysql version is mostly 5.6.0 , we can not upgrading the mysql version

**Comment by chuntaojun** [comment]
You can modify the SQL statement to conform to the Mysql version, but be careful that the roles and user names are not too long
