### ISSUE TITLE
Docker中使用nacos，启动后添加配置信息，前端js报错，版本为1.2.1

### ISSUE THREAD

**Issue by gx0803** [alibaba/nacos#2652]
![image](https://user-images.githubusercontent.com/8998033/79687112-9a51e980-8277-11ea-9746-45fd7c8bff08.png)
用户管理添加新用户是chenggong成功的，但是配置管理添加新配置，不管是哪种格式，都会报这个500操作，导致发布配置失败
版本是1.2.1，docker直接拉取的最新镜像，使用单例模式部署。没有用yaml脚本。

**Comment by gaofeicm** [comment]
请移步：https://github.com/alibaba/nacos/issues/2627
