### ISSUE TITLE
Nacos集群版反复的调用/nacos/v1/ns/instance/list方法

### ISSUE THREAD

**Issue by NewwayHe** [alibaba/nacos#2655]
## Issue Description
环境
Dubbo2.7.6, Nacos1.2.1, Spring cloud alibaba2.1.2Release

### Describe what happened (or what feature you want)
错误描述
Nacos集群版反复的调用/nacos/v1/ns/instance/list方法
在Nacos服务端不间断的打印
[21/Apr/2020:03:39:45 +0000] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.0.219&serviceName=DEFAULT_GROUP%40%40providers%3Axxxxx%3A1.0.0&udpPort=65249&encoding=UTF-8 HTTP/1.1" 200 144 "-" "Nacos-Java-Client:v1.2.1"

在Nacos端中把Nacos的日志打开显示:
 Request from server: http://192.168.0.11:8848/nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.0.219&serviceName=DEFAULT_GROUP%40%40providers%3Axxxxxxxx%3A1.0.0&udpPort=65248&encoding=UTF-8
这个日志是在不间断的调用,
通过调试发现HostReactor这个线程在反复调用不停止.
### Describe what you expected to happen
恢复正常的心跳时间间隔和获取实例的时间间隔.

**Comment by nkorange** [comment]
请问是连续不停的进行查询吗，可否贴日志看一下？

**Comment by NewwayHe** [comment]
日志如第一个发言,只是把其中一个心跳包给贴出来了. 我们是采用dubbo + nacos的方式来建立系统, 通过nacos代码的分析,dubbo是基于接口的级别进行跟nacos心跳,我们约有400个服务接口, 按默认每5秒一个接口来一次心跳beat和查询状态实例,那每秒是有400/5*2个请求到nacos服务器上,如果把日志打开来那日志是刷刷的跳, 那我们同时有10个同事在建立服务跟nacos进行沟通,意味着一个服务可能会有多个provider, 那跟nacos的沟通的压力就会很大, 经常发生有人连接不上nacos的问题, 请问这种情况是否正常? 是设计如此吗? 为什么要做到接口级去做心跳保持而不是应用级跟nacos沟通? 这样系统越来越大的情况下不是很不稳定?

**Comment by nkorange** [comment]
目前是这样的，后面会改造成grpc长连接，一个客户端进程就一条连接。

**Comment by NewwayHe** [comment]
thx, 等你们的新版本.

**Comment by musarona** [comment]
这个问题在哪个版本里得到了解决呢？

**Comment by cqsgitshou** [comment]
牛逼的bug
