### ISSUE TITLE
NacosConfigService#publishConfig缺失配置类型字段

### ISSUE THREAD

**Issue by flyer5200** [alibaba/nacos#2660]
**Issue Description**
环境
Nacos1.2.1

**Describe what happened (or what feature you want)**
问题描述
com.alibaba.nacos.client.config.NacosConfigService#publishConfig 默认没有为配置内容设置type, 导致在dashboard中默认显示text类型

**Describe what you expected to happen**
增加type类型, 使dashboard能正确显示

**Comment by TsingLiang** [comment]
这个功能属于管控功能，这个需要讨论一下管控API怎么统一搞

**Comment by KomachiSion** [comment]
Have we got result or plan of this issue? There are two PR pending about this issue?
