### ISSUE TITLE
The health value of the instance always changes over and over again.

### ISSUE THREAD

**Issue by lybbyl** [alibaba/nacos#2666]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
When I use the following configuration, the health value of the instance always changes over and over again. When I read the source code, I found that the 'ClientBeatProcessor' update instance heartbeat was throwing a null pointer exception. 'ClientBeatCheckTask' will remove the instance and the instance will continue to register, causing this error.

![image](https://user-images.githubusercontent.com/20021575/79960307-d5426000-84b7-11ea-8e18-341f73476077.png)
![image](https://user-images.githubusercontent.com/20021575/79960597-2a7e7180-84b8-11ea-9207-b94b580fdccf.png)

### Describe what you expected to happen
I think it can be modified as follows
![image](https://user-images.githubusercontent.com/20021575/79960824-75988480-84b8-11ea-83a6-b30795cace76.png)

### How to reproduce it (as minimally and precisely as possible)

1. Start a cluster
2. The instance USES the default configuration
3. Then the bug will reappear

### Tell us your environment
v1.2.0

**Comment by sagexueqi** [comment]
I have the same problem as you, nacos version 1.2.0-beta0. The nacos client I used in spring cloud alibaba is version 1.1
