### ISSUE TITLE
config 发布yaml 格式错误，却没有提示

### ISSUE THREAD

**Issue by wolfgangzhu** [alibaba/nacos#2668]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
when publish such a content with type yaml, the console doesn't give a alert message 
![image](https://user-images.githubusercontent.com/62163512/79988959-db4d3680-84e1-11ea-8234-efa866a1d0b5.png)

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/62163512/79989550-94137580-84e2-11ea-876b-c643025c5261.png)

### How to reproduce it (as minimally and precisely as possible)

1.  click add config button
2. choose yaml type
3. input following content 
```yaml
a: 1
    b: 3
c: 4
d: 5
```

### Tell us your environment
nacos 1.2.1

**Comment by chuntaojun** [comment]
This is a front-end issue that does not currently affect the actual configuration resolution

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2622

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2627
