### ISSUE TITLE
nacos在本地开发的场景下如何使用？

### ISSUE THREAD

**Issue by beforeborn** [alibaba/nacos#2671]
nacos能加载本地配置文件么？
如果不能的话，那开发一个新需求，多人协作，都去改nacos配置中心的配置么？这样会相互影响吧，比如A刚改了mysql连接，B接着又改了，然后A就郁闷了。
请问这种场景如何解决？

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by freedudu** [comment]
you can use group or namespace to seperate diffirent environments
