### ISSUE TITLE
bug configService 多次创建！内存泄漏，多开线程

### ISSUE THREAD

**Issue by lybbyl** [alibaba/nacos#2674]
## Issue Description

Type: *bug report* or *feature request*
bug report

### Describe what happened (or what feature you want)
ConfigFactory.createConfigService(Properties properties) 有可能会调用多次。 并产生多个实例 里面由于有线程池长轮训服务造成内存泄漏，多开线程 等多种异常情况

错误的原因是因为NacosUtils.identify(Map<?, ?> properties) 方法造出了不同的key
在NacosConfigEnvironmentProcessor中的匿名builder 调用NacosUtils.identify方法时，由于propertie使用了
Properties buildGlobalNacosProperties() 方法，如下图 ，没有带上encode属性 ，导致产生的key为
-----> ||127.0.0.1:18848,127.0.0.1:28848,127.0.0.1:38848||||||
![image](https://user-images.githubusercontent.com/20021575/80114986-c9899300-85b6-11ea-9681-7004d9a9e97e.png)

![image](https://user-images.githubusercontent.com/20021575/80113536-06548a80-85b5-11ea-885e-e29c427c6c99.png)

当spring IOC时 调用NacosConfigurationPropertiesBindingPostProcessor 给bean做处理时，实际上Propertie中会有encode属性 产生的key如下
-----> ||127.0.0.1:18848,127.0.0.1:28848,127.0.0.1:38848|||||UTF-8|
判断没有configService 就会重新创建！

### Describe what you expected to happen
ConfigFactory.createConfigService(Properties properties)  在properties相同时 应该只被创建一次

### How to reproduce it (as minimally and precisely as possible)

客户端如下配置
![image](https://user-images.githubusercontent.com/20021575/80114581-554eef80-85b6-11ea-8758-5eaa48d9fd90.png)

![image](https://user-images.githubusercontent.com/20021575/80114634-5e3fc100-85b6-11ea-9885-d9eff4d0a47f.png)

![image](https://user-images.githubusercontent.com/20021575/80114651-639d0b80-85b6-11ea-93bb-7bb16cd573bc.png)

### Tell us your environment

 
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.4</version>
        </dependency>
    </dependencies>

### Anything else we need to know?
建议修改nacos-config-spring-boot-autoconfigure 项目中NacosUtils.identify 方法 
1：要么属性全部考虑清楚加上 
或者2：要么key更直白 只和相关的属性沾边移除encode

**Comment by wangweizZZ** [comment]
You can report this issue to   [nacos-group/nacos-spring-project](https://github.com/nacos-group/nacos-spring-project)

**Comment by lybbyl** [comment]
> You can report this issue to [nacos-group/nacos-spring-project](https://github.com/nacos-group/nacos-spring-project)

good !
