### ISSUE TITLE
建议默认使用8.0mysql驱动

### ISSUE THREAD

**Issue by lizhian** [alibaba/nacos#2676]
1 8.0版本现在越来越多人使用
2 8.0的驱动向下兼容5.7和5.6,直接使用8.0可以避免不必要的配置

**Comment by lifedre** [comment]
支持

**Comment by kuangyoubo** [comment]
> 支持

需要修改源码才可以，这个不算默认支持。

**Comment by lizhian** [comment]
升级一下依赖包就可以

**Comment by zgj123** [comment]
同意 都支持下，要不然每次升级还得编译

**Comment by kuangyoubo** [comment]
> 升级一下依赖包就可以

这样会涉及到重新打包，以后新版本出来了升级还得更改。

**Comment by lizhian** [comment]
> > 升级一下依赖包就可以
> 
> 这样会涉及到重新打包，以后新版本出来了升级还得更改。

改什么?你纠结的点是什么,没看懂

**Comment by kitsrc** [comment]
支持，不然得自己手动调整

**Comment by JL-Code** [comment]
![image](https://user-images.githubusercontent.com/14163944/80312172-55e5c100-8816-11ea-82f8-627b903e5772.png)
![image](https://user-images.githubusercontent.com/14163944/80312202-77df4380-8816-11ea-97c5-db30df859917.png)

Nacos1.2.1 连接 MySQL 8.0.18 报错。

**Comment by xinaiwunai** [comment]
支持
