### ISSUE TITLE
nacos的metadata起作用吗？

### ISSUE THREAD

**Issue by esolve** [alibaba/nacos#2677]
我看nacos的服务发现管理界面有metadata项，譬如 

{
	"preserved.register.source": "SPRING_CLOUD"
}

我想要定义自己的metadata，譬如

`
    spring:  
      cloud:
        nacos:
          metadata:
            version: v1
`

但是发现不起作用，怎么回事？

**Comment by nearzk** [comment]
metadata体现在服务注册列表的详情，是：
{
"preserved.register.source": "SPRING_CLOUD",
"version": "v1"
}
体现在Spring Cloud的yml配置文件里，是：
spring:
  cloud:
    nacos:
      config:
        discovery:
          server-addr: ip:8848
          metadata:
            version: v1

**Comment by nkorange** [comment]
可以参考spring-cloud-alibaba的文档进行metadata的设置。

**Comment by Veryfirefly** [comment]
> 可以参考spring-cloud-alibaba的文档进行metadata的设置。

请问nacos后期会支持存储其他数据类型的元数据吗？
