### ISSUE TITLE
Incocrrect instance health status

### ISSUE THREAD

**Issue by tixo** [alibaba/nacos#2678]
Type: *bug report*

Incocrrect instance health status

my instance was closed successfully ,  but the instance still display in the nacos UI ,  and display true of it's health.

I was used nacos  open api to delete this instance , open api respons "ok " ,  but it's not really ok .

So  How could I delete it？

**Comment by nkorange** [comment]
There are two possible reasons why your instance still display healthy:
1. The health check of Nacos is turned off, which you can check it using command:
```curl '127.0.0.1:8848/nacos/v1/ns/operator/switches'```
    You can turn it on using command:
```curl -X PUT '127.0.0.1:8848/nacos/v1/ns/operator/switches?entry=healthCheckEnabled&value=true'```

2. Your instance still has heartbeat to Nacos, which you can check it in access.log.
