### ISSUE TITLE
nacos服务升级到1.2.1后nacos客户端还是有很多连接注册中心的TIME-WAIT （still have too many TIME-WAIT on nacos clients while nacos servers had been upgraded to 1.2.1 )

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#2679]
## Issue Description
*bug report* 
upgrade all nacos servers to 1.2.1,  nacos client still have 2500~2800 TIME-WAITs samed as before.

### Describe what happened (or what feature you want)
my nacos client version is 1.0.0 using with dubbo registry server 2.7.2 which don't support nacos 1.2.x by now, there are still too many TIME-WAITs (about 2500~2800 )  on each nacos client, these TIME-WAITs all belong to connection with nacos config servers and dubbo registry servers.
the reason is that  the LongPollingRunnable threads ( class ClientWorker) open connections at each runing and keep running without any delay control.

### Describe what you expected to happen
Force the guys who write dubbo & dubbo-registry-nacos to support nacos-client 1.2.1.
:-)

### Tell us your environment
dubbo registry servers: version 2.7.2, deployed on 3 centos7, not clustered
nacos config servers:  version 1.2.1,  deployed on 3 centos7, not clustered

**Comment by nkorange** [comment]
Sorry we cannot force Dubbo guys do that, maybe you can submit an issue in Dubbo project.
