### ISSUE TITLE
health check is performed in the Nacos startup script 

### ISSUE THREAD

**Issue by xuechaos** [alibaba/nacos#268]
A health check is performed in the Nacos startup script to confirm that the startup was successful.

**Comment by pguo65535** [comment]
this issue is the same purpose for the same corner with #222, tell the absolutely tell those new guy loudly！ 
"Yes, Nacos server are now start successfully,  healthy & happily, you can now go ahead & move forward!!"

**Comment by hxy1991** [comment]
## Stand Alone Mode
- Whether port 8848 is already occupied ?
- ...

## Cluster Mode
- Whether port 8848 is already occupied ?
- Whether "cluster.conf" exists and configured correctly ?
- Whether the database connection information is configured in "application.properties" and configured correctly ?
- Whether the database connect successfully ?
- ...

**Comment by xuechaos** [comment]
0.6版本先把健康检查接口做好，按照k8s体系，0.7版本进行集成启动脚本。
