### ISSUE TITLE
Unable to connect to mysql8

### ISSUE THREAD

**Issue by kuangyoubo** [alibaba/nacos#2681]
## Issue Description

Unable to connect to mysql8

### Describe what happened (or what feature you want)
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ConnectionImpl.getServerCharset(ConnectionImpl.java:2983)
        at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1873)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1802)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
        ... 195 more

### Describe what you expected to happen

I want connect to mysql8

### Tell us your environment
window10
mysql 8
jdk1.8
Nacos1.2.1

**Comment by 929033778** [comment]
I have also seen other issues about mysql8.x in nacos community, and my problem has not been solved. Please give me your guidance. My configuration is as follows:

#### dev env 
`
windows8
jdk1.8
nacos-server-1.2.1
`

#### mysql 8.0.17 jar
nacos base has create dir "~/plugins/mysql/mysql-connector-java-8.0.17.jar"

#### application.properties
nacos "~/nacos-server-1.2.1/conf/application.properties" settings info 
`
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=root
`

#### exception
use "~/nacos/nacos-server-1.2.1/bin/startup.cmd" show exception:
`
org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested
exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Co
uld not create connection to database server. Attempted reconnect 3 times. Giving up.)
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81
)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
        at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl$SelectMasterTask.run(B
asicDataSourceServiceImpl.java:317)
`

**Comment by houjunhan** [comment]
use this https://github.com/houjunhan/nacos/tree/master/connect-mysql8
instead of your  ../target/nacos-server.jar
ojbk~

**Comment by 929033778** [comment]
## Windows 解决 Nacos-1.2.1 无法链接 MySQL-8.0.17 


### 先将 Nacos 项目源码下载到本地

方式一（GitHub）：git clone git@github.com:alibaba/nacos.git

方式二（Gitee）：git clone git@gitee.com:mirrors/Nacos.git


### 修改配置打包替换原有jar

修改“~/nacos/pom.xml”


```
<!-- JDBC libs -->
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
	<version>8.0.17</version>
</dependency>
```

修改“~/nacos/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/MysqlHealthCheckProcessor.java”

```
修改前
import com.mysql.cj.jdbc.jdbc2.optional.MysqlDataSource;

修改后
import com.mysql.cj.jdbc.MysqlDataSource;
```

重新编译打，参见“~/nacos/BUILDING”

```
# 进入到项目根目录，执行以下命令
$ mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U
```

复制最新打包的 jar 文件，去覆盖自己下载的 nacos-1.2.1 中jar

```
# 复制以下 jar 文件
~/nacos/distribution/target/nacos-server-1.2.1/nacos/target/nacos-server.jar

# 被覆盖的目标 jar 文件
~/nacos-server-1.2.1/target/nacos-server.jar
```

### 创建数据库及增加配置

在MySQL中创建好数据库“nacos_config”，自行在代码仓库中找脚本

在“~/nacos-server-1.2.1/conf/application.properties”增加以下配置项

```
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai
db.user=MySQL登录账号
db.password=MySQL登录密码
```

### 启动测试效果

启动“~/nacos-server-1.2.1/bin/startup.cmd”，可视化界面操作数据均可正常与 MySQL-8.0.17 交互

Nacos 默认可视化
网址：http://localhost:8848/nacos
账号：nacos
密码：nacos

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/1280
