### ISSUE TITLE
项目集成 spring cloud alibaba nacos, 启动项目后一直打印ClientWorker日志

### ISSUE THREAD

**Issue by YuizhiCode** [alibaba/nacos#2684]
项目集成 spring cloud alibaba nacos, 启动项目后一直打印ClientWorker日志.

nacos 1.21  spring cloud alibaba 2.2.1.RELEASE  

020-04-25 22:13:53.052  INFO 20396 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [polling-resp] config changed. dataId=test-auth.yaml, group=DEFAULT_GROUP
2020-04-25 22:13:53.052  INFO 20396 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[begin-auth-dev.yaml+DEFAULT_GROUP]
2020-04-25 22:13:53.054  INFO 20396 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [data-received] dataId=begin-auth-dev.yaml, group=DEFAULT_GROUP, tenant=null, md5=0080e7da0082c68da620c7cb1389ef82, content=spring:
  datasource:
会一直打印重复内容，但有时候又不打印，这让我很奇怪。

寻求一个解决的办法！！！

Project integration spring cloud alibaba nacos, always print ClientWorker logs after starting the project.

nacos 1.21  spring cloud alibaba 2.2.1.RELEASE  

020-04-25 22: 13: 53.052 INFO 20396 --- [-127.0.0.1_8848] canclient.config.impl.ClientWorker: [fixed-127.0.0.1_8848] [polling-resp] config changed. DataId = test-auth.yaml, group = DEFAULT_GROUP
2020-04-25 22: 13: 53.052 INFO 20396 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker: get changedGroupKeys: [begin-auth-dev.yaml + DEFAULT_GROUP]
2020-04-25 22: 13: 53.054 INFO 20396 --- [-127.0.0.1_8848] canclient.config.impl.ClientWorker: [fixed-127.0.0.1_8848] [data-received] dataId = begin-auth- dev.yaml, group = DEFAULT_GROUP, tenant = null, md5 = 0080e7da0082c68da620c7cb1389ef82, content = spring:
   datasource:
It will always print duplicate content, but sometimes it does not print, which makes me very strange.

Seek a solution！！！

**Comment by longit123** [comment]
+1

我这里也是前两天下载的nacos1.2.1版本，其他相关版本：
<spring.cloud.version>Greenwich.SR5</spring.cloud.version>
<spring.cloud.alibaba.version>2.1.2.RELEASE</spring.cloud.alibaba.version>
<spring.boot.version>2.1.12.RELEASE</spring.boot.version>

`
server:
  port: 54321
spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      config:
        server-addr: 192.168.2.133:8848 # nacos配置中心地址
        file-extension: yaml          
#        namespace: fca0a232-b921-4f4b-92d0-f6d6c4eb824b  # 相关环境id
        namespace: public  # 相关环境id
#        group: DEFAULT_GROUP #所属配置的组
        extension-configs:
          - data-id: database-config.properties
            group: GLOBAL_GROUP
            refresh: true
`

而且发现，上面的bootstrap.yml配置里（试了N次，必现）：
namespace配置成public，控制台就会一直刷日志（几乎一秒一次）：
`c.a.n.client.config.impl.ClientWorker    : [fixed-192.168.2.133_8848-public] [polling-resp] config changed.`

如果namespace不配置public，或者配置成其他的namespace的id，就不会刷；

客户端和nacos那台服务器的CPU也跟着上升

**Comment by YuizhiCode** [comment]
> +1
> 
> 我这里也是前两天下载的nacos1.2.1版本，其他相关版本：
> <spring.cloud.version> Greenwich.SR5 </spring.cloud.version>
> <spring.cloud.alibaba.version> 2.1.2.RELEASE < /spring.cloud.alibaba.version>
> <spring.boot.version> 2.1.12.RELEASE </spring.boot.version>
> 
> `
> 服务器：
> 端口：54321
> 春季：
> 应用程序：
> 名称：nacos-demo
> 云：
> nacos：
> 配置：
> 服务器地址：192.168.2.133 : 8848 ＃nacos配置中心地址
> 文件扩展名：yaml
> 
> #### 命名空间：fca0a232-b921-4f4b-92d0-f6d6c4eb824b＃相关环境id
> ```
>     namespace: public  # 相关环境id
> ```
> 
> #### 组：DEFAULT_GROUP＃所属配置的组
> ```
>     extension-configs:
>       - data-id: database-config.properties
>         group: GLOBAL_GROUP
>         refresh: true
> ```
> 
> `
> 
> 而且发现，上面的bootstrap.yml配置里（试了N次，必现）：
> 名称空间配置成公共的，控制台就会一直刷日志（几乎一秒一次）：
> `c.a.n.client.config.impl.ClientWorker : [fixed-192.168.2.133_8848-public] [polling-resp] config changed.`
> 
> 如果namespace不配置public，或者配置成其他的namespace的id，就不会刷；
> 
> 客户端和nacos那台服务器的CPU也跟着上升

不用公共public  的配置，就不会刷日志???

**Comment by longit123** [comment]
我这里有时候会刷，有时候不会刷，我也很难必现，但加上extension-config，然后配置成我上面说的那种情况，就必刷（注意版本）

而且坑爹的是，3台nacos，一台leader可以获取到配置信息，另两台follower有时候可以获取，有时候却不能获取，导致用nginx做upstream，都不好做，只能写死leader地址，而且有时候重启服务，leader变了，还得停服务，手动改地址。。。。。。

**Comment by longit123** [comment]
我刚又试了三种（没有extension-config）情况：
1. 不加namespace: public（没有设置任何namespace时，不刷）
2. 加namespace: xxxxxxxx-xxxxxxx-xxxxx（设置成其他id，不刷）
3. 加上namespace: public（疯狂刷）

**Comment by YuizhiCode** [comment]
> 我刚又试了三种（没有extension-config）情况：
> 
> 1. 不加namespace: public（没有设置任何namespace时，不刷）
> 2. 加namespace: xxxxxxxx-xxxxxxx-xxxxx（设置成其他id，不刷）
> 3. 加上namespace: public（疯狂刷）

我没有配置extension-config ，namespace，都是默认的
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        group: DEFAULT_GROUP
        file-extension: yaml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

**Comment by lybbyl** [comment]
https://github.com/alibaba/nacos/issues/2683
应该是同一个问题 原因出在服务器和客户端对内容md5方法不一致，导致一直触发config变更事件。

**Comment by YuizhiCode** [comment]
> #2683
> 应该是同一个问题 原因出在服务器和客户端对内容md5方法不一致，导致一直触发config变更事件。

怎么解决这个问题

**Comment by lybbyl** [comment]
> > #2683
> > 应该是同一个问题 原因出在服务器和客户端对内容md5方法不一致，导致一直触发config变更事件。
> 
> 怎么解决这个问题

1:已经有contributor 说会修改了 新版本应该会解决 更老的版本不知道有没有问题
2:将服务端和客户端的md5方法更改为一致以后， 修改server端Md5Utils的getMd5方法 为config.utls 包下的Md5类中getMD5String方法， 自己打包就行了.

**Comment by YuizhiCode** [comment]
> 者自己手动修改源码，只需将服务端和客户端的md5方法更改为一致， 修改server端Md5Util

好的，谢谢，坐等新版本了

**Comment by rcfeng** [comment]
1.3.0没解决

**Comment by wangfy1989** [comment]
1、检查下nacos 配置有没有错，可以每行后面加个空格试试。

**Comment by 785287123** [comment]
不是因为MD5的问题
client端配置public后，查询时的key为dataId+group+tenant，也就是example.properties+DEFAULT_GROUP+public
但是Server端的public为默认值 CacheData中缓存的值为dataId+group，也就是example.properties+DEFAULT_GROUP
导致在server端从缓存中查询key时，找不到该缓存获取不到MD5值，所以导致client与server的MD5值永远不相等

**Comment by JL-Code** [comment]
> 不是因为MD5的问题
> client端配置public后，查询时的key为dataId+group+tenant，也就是example.properties+DEFAULT_GROUP+public
> 但是Server端的public为默认值 CacheData中缓存的值为dataId+group，也就是example.properties+DEFAULT_GROUP
> 导致在server端从缓存中查询key时，找不到该缓存获取不到MD5值，所以导致client与server的MD5值永远不相等
> 
> 我想到的几种解决方法
> 1、public时不配置namespace
> 2、修改client端代码，配置public时默认为空
> 3、修改server端代码，public默认不采取空值

ncaos 1.3.1 ,client 没有采用 public 的 namespace 一样显示 get changedGroupKeys:[]

**Comment by doracl** [comment]
不用public就没问题了

**Comment by SmilingBug** [comment]
我这边的情况是，共享配置（扩展配置）一直无限刷新。所以临时解决方案是：暂时关闭对共享配置的自动刷新。

**Comment by liuhu** [comment]
https://github.com/alibaba/nacos/issues/2684#issuecomment-691764625
服务端应对客户端请求的 `public` namespace 做兼容处理。

**Comment by CrossLee** [comment]
> 我这边的情况是，共享配置（扩展配置）一直无限刷新。所以临时解决方案是：暂时关闭对共享配置的自动刷新。

后来怎么解决的？
