### ISSUE TITLE
No service to register for nacos client...

### ISSUE THREAD

**Issue by ghostman-git** [alibaba/nacos#2685]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
![image](https://user-images.githubusercontent.com/13376074/80284400-df32c000-8750-11ea-9e91-9bc3e0c24126.png)

2. 
![image](https://user-images.githubusercontent.com/13376074/80284412-f1acf980-8750-11ea-9b87-baf0792b0859.png)

3. 

### Tell us your environment
springBootVersion: 2.2.5.RELEASE
springCloudVersion: Hoxton.SR3
springCloudAlibabaVersion: 2.2.1.RELEASE

**Comment by ghostman-git** [comment]
Found to be related to this
![image](https://user-images.githubusercontent.com/13376074/80284857-ae07bf00-8753-11ea-8965-16bb779ff68a.png)

**Comment by ghostman-git** [comment]
![image](https://user-images.githubusercontent.com/13376074/80285516-27091580-8758-11ea-9596-e2840a0f36f3.png)
Is the colon not a problem? Not clear, but after removing the colon, the service successfully registered

**Comment by nkorange** [comment]
请咨询一下spring-cloud-alibaba项目组

**Comment by cuipy** [comment]
解决了，这么配置
server:
  port: 8283

spring:
  application:
    name: 'itms-ureport2'
  profiles:
    active: '@profile.name@' # 环境设置
  cloud:
    nacos:
      config:
        server-addr: '@nacos.server-addr@'
        namespace: '@nacos.namespace@'
        group: '@nacos.group@'
        refresh-enabled: true
      discovery:
        server-addr: '@nacos.server-addr@'
        namespace: '@nacos.namespace@'
        group: '@nacos.group@'
        service: 'itms-ureport2'

关键是 spring.cloud.nacos.discovery.service = itms-ureport2
