### ISSUE TITLE
通过源码打包jar包启动nacos时，默认为集群模式启动，如何修改成单机模式启动？

### ISSUE THREAD

**Issue by 872022610** [alibaba/nacos#2688]
### Describe what happened (or what feature you want)
下载源码打包jar包启动，会默认寻找cluster.conf，如果我只是想以单机模式启动时该怎么办？

### Describe what you expected to happen
通过jar包以单机模式启动

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by ali-1024** [comment]
# 增加启动参数
-Dnacos.standalone=true -Dnacos.home=源码目录
![image](https://user-images.githubusercontent.com/39354350/80328699-aa1e8e80-8872-11ea-981f-236912da872e.png)
