### ISSUE TITLE
bug report: Configuration list fuzzy query function bug,

### ISSUE THREAD

**Issue by kitsrc** [alibaba/nacos#2692]
## Issue Description
配置列表 模糊查询功能bug, 必须精确输入才有查询结果

![image](https://user-images.githubusercontent.com/23493090/80305579-14421f80-87f0-11ea-9eb6-4aab679604b9.png)

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by kitsrc** [comment]
Nacos 1.2.1

**Comment by wolfgangzhu** [comment]
Duplicate of #2079

**Comment by wolfgangzhu** [comment]
不过这么多人有这个问题， 建议能在console上说明提示

**Comment by xiaoyifang** [comment]
这种搜索问题，基本上都会遇到。
最好也可以忽略大小写，
并且前后都可以模糊搜索。
