### ISSUE TITLE
Keep printing ERROR log c.a.nacos.client.security.SecurityProxy: login failed:

### ISSUE THREAD

**Issue by jackgeeks2018** [alibaba/nacos#2693]
version：nacos-config2.2.1+springboot2.2.6
ERROR 1760 --- [.naming.updater] c.a.nacos.client.security.SecurityProxy  : login failed:

**Comment by zhuoqianmingyue** [comment]
My SpringBoot version： 2.1.1.RELEASE  
ERROR ：
```
[ecurity.updater] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":401,"content":"<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Apr 30 16:27:27 CST 2020</div><div>There was an unexpected error (type=Unauthorized, status=401).</div><div>Unauthorized</div></body></html>"}
```

Trying to switch to 1.2.1 still reports an error
Trying to switch to 1.1.4 does not report an error

**Comment by zhuoqianmingyue** [comment]
after the program starts will periodically execute the login method in class SecurityProxy，Then prompt Unauthorized。but it does not affect the use of the configuration center。

```java
 public boolean login(String server) {
        if (StringUtils.isNotBlank(this.username)) {
            Map<String, String> params = new HashMap(2);
            params.put("username", this.username);
            String body = "password=" + this.password;
            String url = "http://" + server + this.contextPath + "/v1/auth/users/login";
            if (server.contains("http")) {
                url = server + this.contextPath + "/v1/auth/users/login";
            }

            HttpResult result = HttpClient.request(url, new ArrayList(2), params, body, Charsets.UTF_8.name(), "POST");
            if (result.code != 200) {
                SECURITY_LOGGER.error("login failed: {}", JSON.toJSONString(result));
                return false;
            }

            JSONObject obj = JSON.parseObject(result.content);
            if (obj.containsKey("accessToken")) {
                this.accessToken = obj.getString("accessToken");
                this.tokenTtl = (long)obj.getIntValue("tokenTtl");
                this.tokenRefreshWindow = this.tokenTtl / 10L;
            }
        }

        return true;
    }
```

**Comment by chestarss** [comment]
+1

**Comment by ymiao** [comment]
i have same issue, when i debug it, it seems a nacos client bug, the url built have two http prefix, one should be omited if already have one.

![image](https://user-images.githubusercontent.com/1067153/92691736-9e40ee00-f375-11ea-877b-109c3713afd5.png)

**Comment by junqingzh** [comment]
<spring-cloud-alibaba-dependencies.version>2.2.1.RELEASE</spring-cloud-alibaba-dependencies.version>
        <spring-boot-dependencies.version>2.2.9.RELEASE</spring-boot-dependencies.version>
        <spring-cloud-dependencies.version>Hoxton.SR7</spring-cloud-dependencies.version>
此问题在这个配置版本中，仍然存在。

**Comment by Daniel-yim** [comment]
Nacos-Server: 1.3.2，
spring-cloud-starter-alibaba-nacos-config：2.2.3.RELEASE，
其中的nacos-client依赖为1.3.3版本，当前1.4.0为BETA版本。

也遇到了这个问题，抓包对nacos的/nacos/v1/auth/users/login?username=xx进行抓包，整体接口逻辑不存在问题，都是正常的。但是在我的示例中观察到HTTP数据流中提交的数据由于密码有特殊字符@，从Spring的配置加载到使用，导致被双次编码%40 -> %2540，从而导致认证失败。

遇到这个问题的小伙伴，可以注意下是否是同样的原因。

**Comment by yijianguanzhu** [comment]
我目前用docker swarm部署服务，会遇到
`
com.alibaba.nacos.client.naming.updater] ERROR c.a.n.client.security.SecurityProxy      - login failed: {"code":301,"content":""}
`
问题，但是不影响使用，和本地测试使用的是同一个nacos地址，本地没出现这个问题，spring boot版本2.2.9release，spring cloud Hoxton.SR7，spring cloud alibaba 2.2.1release，我会接着调查一下问题

**Comment by lovelyx** [comment]
idea启动项目报403错误
ERROR com.alibaba.nacos.client.security.SecurityProxy - login failed: {"code":403,"message":"unknown user!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Connection":"keep-alive","Content-Length":"13","Content-Type":"text/html;charset=UTF-8","Date":"Thu, 03 Mar 2022 02:17:47 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["13"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Thu, 03 Mar 2022 02:17:47 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF

**Comment by SunYuyang18745027903** [comment]
启动nacos连接出现ERROR 27016 --- [s.client.Worker] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"unknown user!","header":{"header":{"Accept-Charset":"UTF-8","Accept-Encoding":"gzip","Connection":"keep-alive","Content-Length":"13","Content-Type":"text/html;charset=UTF-8","Date":"Mon, 21 Mar 2022 09:31:10 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["13"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Mon, 21 Mar 2022 09:31:10 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}

**Comment by gaspire** [comment]
启动nacos连接出现ERROR 27016 :
nacos-cliet: 2.0.4
nacos-server: 2.2

2023-02-15 16:50:04.329 ERROR 20670 --- [s.client.Worker] c.a.nacos.client.security.SecurityProxy  : login failed: {"code":403,"message":"unknown user!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"13","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Wed, 15 Feb 2023 08:50:03 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["13"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Wed, 15 Feb 2023 08:50:03 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
