### ISSUE TITLE
nacos作为注册中心配置文件中enabled和register-enabled属性的关系

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#2694]
使用nacos作为注册中心的话，在discovery下有enabled和register-enabled属性，但是在NacosDiscoveryProperties类中并没有声明enabled属性，只声明了registerEnabled属性，那么配置文件中enabled这个配置项的作用在哪里体现呢

**Comment by nkorange** [comment]
请咨询spring-cloud-alibaba项目组
