### ISSUE TITLE
偶发,修改了一次key的情况下,confd-nacos,一直收到推送

### ISSUE THREAD

**Issue by koukoujiang** [alibaba/nacos#2696]
使用confd-nacos 的watch状态一直连着nacos，只修改了一次key的值的情况下, confd客户端一直收到nacos的推送, 一共发生过2次，暂时未能复现
发生的时候重启confd和nacos, 并删除key, 均没有效果
删掉key的情况下,等个几分钟，再创建这个Key貌似就好了

**Comment by AsummerCat** [comment]
这里是之前有个md5工具类未完成所有的替换的BUG现在已经解决了你手动拉取最新的nacos编译下应该可以解决了 导致client客户端 与nacos-config的md5解析不一致

**Comment by koukoujiang** [comment]
> 这里是之前有个md5工具类未完成所有的替换的BUG现在已经解决了你手动拉取最新的nacos编译下应该可以解决了 导致client客户端 与nacos-config的md5解析不一致

还有个问题，我在windows的机器上登录nacos的网页,编辑的value, confd在linux上刷出来的文件,每行会带有^M(windows的/r), 这个咋解决。。。。ps:我是在confd的源码里加了去掉^M（/r）的功能，不知道是不是这个原因导致md5不正确。

**Comment by AsummerCat** [comment]
这个问题倒是没有碰到过 你可以先修复md5的问题 再进行验证 
在不改动你当前程序的情况下  直接检出nacos编译后 修改MD5.getInstance().getMD5String()改为Md5Utils.getMD5() 可以进行快速测试 这样只改动控制台的部分 或者你降级版本试一试
