### ISSUE TITLE
where to check the latest spring-cloud-starter-alibaba starter version

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#270]
**Description**

in doc [`quick-start-spring-cloud`](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html), we says:

> 
>
添加依赖

```
<dependency>
   ...
   <version>${latest.version}</version>
</dependency>
```
but we do not tell user where to check the latest stable version.

**Comment by hxy1991** [comment]
The the latest version can be available in maven repositories such as "mvnrepository.com".

**Note**: Version 0.2.x.RELEASE is compatible with the Spring Boot 2.0.x line. Version 0.1.x.RELEASE is compatible with the Spring Boot 1.x line.

![image](https://user-images.githubusercontent.com/2517258/48423521-bd7f8c00-e79b-11e8-94fc-2981e97f5c91.png)

**Comment by pguo65535** [comment]
perfect!
