### ISSUE TITLE
nacos服务权重是不是不起作用啊？

### ISSUE THREAD

**Issue by esolve** [alibaba/nacos#2700]
系统框架用的是springcloud finchley 版本
nacos服务端和客户端都是1.1.3版本
修改nacos 服务的权重
发现不起作用
但是上下线是起作用的

是不是目前权重还不起作用？
或者怎么调整能让权重起作用？
谢谢

BTW，发现客户端的naming.log日志是空的，这个有问题吗？

**Comment by nkorange** [comment]
这个需要配置Ribbon里的NacosRule来使用，可以咨询一下spring-cloud-alibaba
