### ISSUE TITLE
the format of dataId is WRONG !!!

### ISSUE THREAD

**Issue by xinaiwunai** [alibaba/nacos#2703]
## Issue Description
***bug report***

### Describe what happened (or what feature you want)
in the Manual [quick-start-spring-cloud](https://nacos.io/en-us/docs/quick-start-spring-cloud.html)
> In Nacos Spring Cloud, the format of dataId is as follows:
> ```java
> ${prefix}-${spring.profile.active}.${file-extension}
> ```

BUT，In practice, I found that it should be
```java
${prefix}-${spring.profiles.active}.${file-extension}
```
`profiles`  is not  `profile`。Can be modified to the same？

### Describe what you expected to happen
Can be modified to the same？

### Tell us your environment
nacos: 1.2.1
spring cloud: Hoxton.SR3
spring cloud alibaba: 2.2.1.RELEASE
spring boot: 2.2.5.RELEASE

**Comment by nkorange** [comment]
Please report it to spring-cloud-alibaba
