### ISSUE TITLE
项目接入nacos，想要使用nacos的权限这块，但是bootstrap配置文件里面不知道怎么配置用户名和密码

### ISSUE THREAD

**Issue by zhangqlbc136** [alibaba/nacos#2705]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
用的是什么框架？

**Comment by zhangqlbc136** [comment]
用的springcloud，我现在是想用nacos做配置中心，供很多项目使用，当然这些项目可能是springboot的，也可能是springcloud的，也可能是dubbo的，现在只是刚开始搞springcloud的

**Comment by nkorange** [comment]
这个需要到各个框架那边去咨询下，每个框架使用的方式是不一样的。
