### ISSUE TITLE
Nacos1.2.1搭配Dubbo的SpringBoot程序到底咋弄啊？

### ISSUE THREAD

**Issue by xzknet** [alibaba/nacos#2708]
有官方的文档么？如果有麻烦在readme.md里面写一下。
另外Nacos1.2.1我用dubbo官网和alibaba官网的文档搭建以后发现服务注册不稳定【尤其nacos，各种包，什么<groupId>org.apache.dubbo</groupId>，<groupId>com.alibaba.spring</groupId>，<groupId>org.springframework.cloud</groupId>】，当有两个服务时，每次刷新都会发现有一个服务离线。
你们到底用哪个作为官方的包啊？能不能给个权威的指南啊。
迫于无奈，只好将本地的Dubbo和nacos的包降低版本使用。

`

		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId><version>2.7.5</version>
		</dependency>
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo</artifactId><version>2.7.5</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-registry-nacos</artifactId>
                       <version>2.7.3</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
                        <version>1.2.1</version>
		</dependency>
		
		<dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>nacos-config-spring-boot-starter</artifactId>
			<version>0.2.7</version>
		</dependency>
`

**Comment by xzknet** [comment]
我就是想用nacos作为服务注册以及配置中心而已，用得着给大家出这么多包，还都是你们自己出的。如果换新的包名了，老项目麻烦写一下，让大家能找过去。;(

**Comment by Rose171216** [comment]
大佬，请问使用nacos作为配置中心，springboot+dubbo+nacos，这个dubbo的初始化配置比如dubbo.application.name这个配置，就不能从nacos读到，启动报错找不到这些配置，但是其他像mysql，redis这些都可以正常读到，这个应该怎么解决呢。报错如下：Caused by: java.lang.IllegalStateException: No such application config! Please add <dubbo:application name="..." /> to your spring config.
