### ISSUE TITLE
which table does  nacos service discovery used?

### ISSUE THREAD

**Issue by yuanjinzhong** [alibaba/nacos#2709]
hello

i use the respority nacos-group/nacos-docker to docker-compose my nacos cluster,

everything works well, but i am confused : which table does  nacos service discovery used? i did not see it in mysql schema.

----------
你好，我按照文档将服务正常注册在nacos上，但是我到数据库里面居然没找到我刚刚注册的服务，难道服务注册用的是内存或者文件？因为我没找到维护服务注册记录的表
谁能给我解答一下？谢谢

**Comment by nkorange** [comment]
数据库不存储服务，服务存储在内存里或者磁盘里。

**Comment by yuanjinzhong** [comment]
配置信息存在数据库，注册得服务列表信息存在内存或者磁盘 ，对吧
