### ISSUE TITLE
arm支持吗

### ISSUE THREAD

**Issue by key1012** [alibaba/nacos#2710]
nfs-client-provisioner  在arm架构上运行
报standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by nkorange** [comment]
请提供nacos相关的信息

**Comment by key1012** [comment]
可以出一个在arm架构上部署的步骤吗？

**Comment by wecanworkitout** [comment]
希望这个问题能有解决方案

**Comment by yanlinly** [comment]
23191211  这个是我们golang的群，你可以加入讨论一下

**Comment by freemankevin** [comment]
国产化势在必行，希望官方能支持这块
