### ISSUE TITLE
properties配置文件中一条配置不能换行，否则在获取配置时出现异常

### ISSUE THREAD

**Issue by MaJintao611** [alibaba/nacos#2712]
## Issue Description

Type: *bug report* or *feature request*
bug repor

### Describe what happened (or what feature you want)
properties配置文件中一条配置不能换行，否则在获取配置时出现the config data is invalid异常

### Describe what you expected to happen
c.a.c.n.p.NacosDataPropertiesParser - the config data is invalid xxxx,\
c.a.c.n.p.NacosDataPropertiesParser - the config data is invalid xxxx,\
c.a.c.n.p.NacosDataPropertiesParser - the config data is invalid xxxxxxxx,\
c.a.c.n.p.NacosDataPropertiesParser - the config data is invalid xxxxxxx,\
c.a.c.n.p.NacosDataPropertiesParser - the config data is invalid xxxxx,\

### Tell us your environment
nacos 1.2.1
springboot 2.2.6.RELEASE
spring-cloud-starter-alibaba-nacos-config 2.2.1.RELEASE 

### Anything else we need to know?
配置文件内容示例， 如下：
fields.map[user]=id,\
            name,\
            areaId,\
            xx,\
            xxx,\
            xx

**Comment by chuntaojun** [comment]
如果想分两行卸载配置文件中应该如下写法

a=aaaaaaaaas\
dfasdfasdfasdfasdfadfasdfaf
