### ISSUE TITLE
nacos在K8S部署时候，nacos的数据可以连接外部数据库吗？

### ISSUE THREAD

**Issue by key1012** [alibaba/nacos#2713]
nacos在K8S上部署时候，nacos的数据可以连接外部数据库吗？
怎么做？

**Comment by linzehuan** [comment]
配置StatefulSet的环境变量就可以，设置MYSQL_SERVICE_HOST等参数为外数据库的配置
nacos的k8s StatefulSet
https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml
nacos的dockerfile
https://github.com/nacos-group/nacos-docker/blob/master/build/conf/application.properties

**Comment by linzehuan** [comment]
> nacos在K8S上部署时候，nacos的数据可以连接外部数据库吗？
> 怎么做？

配置StatefulSet的环境变量就可以，设置MYSQL_SERVICE_HOST等参数为外数据库的配置
nacos的k8s StatefulSet
https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml
nacos的dockerfile
https://github.com/nacos-group/nacos-docker/blob/master/build/conf/application.properties
