### ISSUE TITLE
请问订阅者列表是干嘛的？

### ISSUE THREAD

**Issue by yuanjinzhong** [alibaba/nacos#2717]
注册的2个服务都出现在服务列表里面:
![image](https://user-images.githubusercontent.com/13908993/80685412-c2540f00-8af9-11ea-97ce-0822ba975b2b.png)

但是订阅者列表里面是空的，这是什么情况
![image](https://user-images.githubusercontent.com/13908993/80685470-d5ff7580-8af9-11ea-845f-11729e574f09.png)

**Comment by MaJintao611** [comment]
订阅者列表目前需要精确查询，也就是说你需要输入服务名称和分组名称进行查询

**Comment by yuanjinzhong** [comment]
> 订阅者列表目前需要精确查询，也就是说你需要输入服务名称和分组名称进行查询

你好，想问一下，服务的调用关系咋提现出来？我是新手

**Comment by chuntaojun** [comment]
> > 订阅者列表目前需要精确查询，也就是说你需要输入服务名称和分组名称进行查询
> 
> 你好，想问一下，服务的调用关系咋体现出来？我是新手

服务的调用关系目前nacos只是支持说服务被哪些服务所订阅了
