### ISSUE TITLE
自定义分组的服务下线无效

### ISSUE THREAD

**Issue by liqingwei0816** [alibaba/nacos#2718]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
**自定义分组的服务下线无效**

### Describe what you expected to happen
服务上下线操作的表单中缺失分组字段
![image](https://user-images.githubusercontent.com/59812407/80688811-f847c200-8afe-11ea-9fdf-73d3186e085c.png)

### How to reproduce it (as minimally and precisely as possible)

1. 使用自定义分组时出现

### Tell us your environment
nacos: 1.2.1

**Comment by xiaobai14** [comment]
修改权重也无效，f12查看默认没有传group参数，导致修改的永远是DEFAULT_GROUP的组

**Comment by liqingwei0816** [comment]
在1.3-beta版本中被修复
