### ISSUE TITLE
nacos 配置回滚问题(nacos configuration rollback problem)

### ISSUE THREAD

**Issue by linkai0001** [alibaba/nacos#2731]
当指定配置历史版本中，回滚到最初的那条配置时（操作类型： 插入）， 会导致配置数据被删, 实际达到的效果应该是，回滚第一次插入时的配置，而不应该删除配置额。
当前使用的 nacos 版本为 1.2.1 

When the specified configuration history version is rolled back to the original configuration (operation type: insert), the configuration data will be deleted. The actual effect should be to return to the configuration at the first insert, not Delete the configuration amount.
The currently used nacos version is 1.2.1

**Comment by beforeborn** [comment]
前端为什么要加如果该记录的操作类型为insert，则请求类型改为delete呢？

**Comment by ly641921791** [comment]
The problem still exists in version 1.3.1

**Comment by Sohnny0** [comment]
该问题在1.3.1版本中仍然存在

**Comment by lidaoyang** [comment]
![image](https://user-images.githubusercontent.com/26211950/95727718-271cb380-0cad-11eb-8df0-faf3699a0a26.png)

**Comment by Jv0id** [comment]
部署到银行的nacox集群也出现过类似问题，回滚历史版本会删除配置。1.3.1版本。不知道新版本有没有这个问题。

**Comment by yanglongyu** [comment]
1.4.0 版本也还是存在这个问题，只能回滚到上一次修改的内容。

**Comment by tale2009** [comment]
https://github.com/alibaba/nacos/issues/4064
Nacos的历史版本概念，理解这个就是了
