### ISSUE TITLE
springboot+nacos+dubbo无法正常从nacos读取dubbo初始化配置

### ISSUE THREAD

**Issue by Rose171216** [alibaba/nacos#2735]
请问使用nacos作为配置中心，springboot+dubbo+nacos，这个dubbo的初始化配置比如dubbo.application.name这个配置，就不能从nacos读到，启动报错找不到这些配置，但是其他像mysql，redis这些都可以正常读到，这个应该怎么解决呢。报错如下：Caused by: java.lang.IllegalStateException: No such application config! Please add <dubbo:application name="..." /> to your spring config.

Please use Nacos as the configuration center, springboot + Dubbo + Nacos. The initialization configuration of Dubbo, such as dubbo.application.name, can't be read from Nacos. The startup error report can't find these configurations, but other configurations, such as MySQL and redis, can be read normally. How can we solve this problem. The error is as follows: caused by: java.lang.illegalstateexception: no such application config! Please add < Dubbo: application name = "..." / > to your spring config

**Comment by chuntaojun** [comment]
你没有使用springcloud吧，如果不是cloud，就是普通的springboot的话，可以看下这个：https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.3-%E4%BB%A5%E5%8F%8A-0.1.3-%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C

**Comment by goodpp** [comment]
注意下版本，试试nacos-config-spring-boot-starter:0.2.3+

**Comment by kocall** [comment]
有解决吗，我也遇到这个问题

**Comment by xiangyunup** [comment]
还没有解决这个问题吗，都 0.2.10 了
