### ISSUE TITLE
tenant did not do legality verification

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#2738]
tenant did not do legality verification

## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

tenant did not do legality verification

### Describe what you expected to happen
tenant did not do legality verification

### How to reproduce it (as minimally and precisely as possible)

1.  tenant can input  ../../xx 
2. There is an unauthorized risk

### Tell us your environment
all version 

### Anything else we need to know?
na

**Comment by zongtanghu** [comment]
This issue can be assiged to me. @yanlinly @chuntaojun
