### ISSUE TITLE
nacos是如何实现配置变化，所有机器上的长轮训都能返回结果呢？

### ISSUE THREAD

**Issue by Mooneal** [alibaba/nacos#2744]
请教个问题：一旦配置变更了，怎么通知所有的客户端呢。 apollo是通过定时任务扫描数据库，如果配置变更了，那么所有机器上的长轮训都会返回结果。 看源码， nacos是在应用里维持了一个sub队列，那配置变更了，只有这台机器的长轮训会返回结果啊。这个是怎么解决的呢？

**Comment by horizonzy** [comment]
后台线程检测.见LongPollingRunnable

**Comment by chuntaojun** [comment]
参见这块代码：https://github.com/alibaba/nacos/blob/develop/config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java

**Comment by chuntaojun** [comment]
> 参见这块代码：https://github.com/alibaba/nacos/blob/develop/config/src/main/java/com/alibaba/nacos/config/server/service/LongPollingService.java

以及
https://github.com/alibaba/nacos/blob/develop/config/src/main/java/com/alibaba/nacos/config/server/controller/CommunicationController.java

**Comment by chuntaojun** [comment]
服务端存在水平通知的逻辑

**Comment by Mooneal** [comment]
好的，感谢，我昨天看到了CommunicationController 这个了。明白了你们设计思想是一个节点变了，会通知到其他节点。

> 服务端存在水平通知的逻辑

**Comment by glameyzhou** [comment]
需要关注下源码，当前的client请求是放在sub队列中，web-console有变更后，会立马通知这个client。但是nacos server之间会互相周知
