### ISSUE TITLE
openAPI-查询服务列表  跨域问题

### ISSUE THREAD

**Issue by liuxliang66** [alibaba/nacos#2747]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
When the front-end called openAPI through axios, it was found that the interface querying the list of services in it had cross-domain problems, and the data could not be found. The other interfaces were normal

### Describe what you expected to happen
The address is an Intranet address。
I want to be able to face up to the display, and access through the browser out of the same results。
Error display via front-end access：
`Access to XMLHttpRequest at 'http://nacos.k8st.sjgs/nacos/v1/ns/service/list?namespaceId=&pageNo=1&pageSize=10' from origin 'http://localhost:1888' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`
Error display through browser access：
`{"count":5,"doms":["blade-user","blade-auth","blade-log","blade-system","blade-gateway"]}`
This makes me confused. All the other interfaces are normal. Only this one has problems

### How to reproduce it (as minimally and precisely as possible)
This seems a bit difficult, we are an Intranet address, but try accessing openAPI directly and calling it using axios

### Tell us your environment
k8s   docker  vue  axios

### Anything else we need to know?
I'm not sure if I made a mistake in using it here. If you are sure there is no problem, I hope you can reply and I will look for the problem

**Comment by liuxliang66** [comment]
有哪位大神遇到过？求指教

**Comment by zollty** [comment]
这个问题提了很久，怎么没人改啊
