### ISSUE TITLE
nacos client pull configuration frequency problem

### ISSUE THREAD

**Issue by jsonlisky** [alibaba/nacos#2748]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
- I hope that the nacos client polls to get the server to change the configuration at a fixed time. Letting go of the configuration, polling every 10ms seems too frequent
我希望nacos客户端轮询获取服务器变更配置的定时时间放开配置，每10ms轮询一次显得太过频繁了

### Describe what you expected to happen
- I hope that the nacos client polls to get the server to change the configuration at a fixed time. Letting go of the configuration
我希望nacos客户端轮询获取服务器变更配置的定时时间放开配置

### Tell us your environment
- nacos-client-1.1.4.jar

### Anything else we need to know?
- com.alibaba.nacos.client.config.impl.ClientWorker
- ![image](https://user-images.githubusercontent.com/44430574/81254774-a81cb280-905e-11ea-8fc2-da9bb2c93218.png)

**Comment by chuntaojun** [comment]
并不是10ms就去轮训，请注意看下checkConfigInfo()内部的逻辑

**Comment by Reka-Downey** [comment]
But it will send a request to the nacos server, 30 microservice instances will be sent 30 times, the K8S ingress logs are all squeezed by request log.

**Comment by chuntaojun** [comment]
checkConfigInfo is to determine whether to create a long polling monitoring task, not to initiate a request
