### ISSUE TITLE
nacos coredns plugin to support DNS-SD

### ISSUE THREAD

**Issue by JianweiWang** [alibaba/nacos#275]
Provide a  coredns plugin that communicates with nacos server to get instances of services to  support dns-based service discovery.

**Comment by pguo65535** [comment]
already release with 0.5.0 and will reference to the project

https://github.com/nacos-group/nacos-coredns-plugin

change to open a document required (DNS-F user guide) issue

**Comment by pguo65535** [comment]
open a new #329 doc requirement issue, and will close this issue now
