### ISSUE TITLE
K8S部署nacos之后，怎么访问nacos的管理页面

### ISSUE THREAD

**Issue by key1012** [alibaba/nacos#2750]
根据官网的教程部署在k8s上部署了nacos，现在节点正常，怎么访问管理页面，还请官方把文档补全，可以小白使用，谢谢。

**Comment by JVMAK** [comment]
这就属于个人对于k8s操作了解不深刻导致的，个人建议此issue与nacos无关，可关闭

**Comment by xiaoyifang** [comment]
@key1012 搜索下k8s如何对外暴露服务。
nodeport ,ingress,hostport等应该都可以。
