### ISSUE TITLE
what is "\logs\java_heapdump.hprof"

### ISSUE THREAD

**Issue by flymainstream** [alibaba/nacos#2753]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
Execute the startup.cmd command , response error message:
"此时不应有 _register_center\nacos-server-1.0.1\nacos"\logs\java_heapdump.hprof"。"

### Describe what you expected to happen

running nacos !!!!!!!!!

### How to reproduce it (as minimally and precisely as possible)

1. First download the nacos-server-1.0.1 in your laptop (ps: the windows version is  windows 10)
2. Then  unzip to  any folder , change directory to bin, open cmd
3. Execute the startup.cmd command 

### Tell us your environment

My laptop system vsersion is windows 10

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/44150545/81273814-08711b80-9082-11ea-934e-130e45e79abd.png)

maybe nope . thanks

**Comment by strawsyz** [comment]
我也遇到了这个问题，发现是因为路径中有 ) 存在，就会出现这个问题。
改一下路径应该能解决。
