### ISSUE TITLE
nacos管理页面能否配置成与API接口使用不同的端口？

### ISSUE THREAD

**Issue by photondragon** [alibaba/nacos#2764]
如题，我想让clients通过8848端口连接nacos服务器，而nacos管理页面通过另一个端口（比如8849）访问。

正常情况下 clients 是通过内网访问nacos服务器的，不开启安全验证。

而nacos管理页面需要通过公网访问（nacos服务器部署在云上），所以要把8848端口暴露到公网上，但是这样就可以从公网上通过以下命令直接访问API接口读取到配置信息：
```
curl -X GET 'http://your-domain.com:8848/nacos/v1/cs/configs?dataId=application.yml&group=DEFAULT_GROUP'
```
这样配置里面数据库用户名密码什么的就暴露了。

如果不把8848端口暴露到公网上，那又没法访问管理页面。

如果管理页面能用另一个端口，管理页面和API接口分别用两套认证方式，就不存在这个问题了。  
管理页面总是需要认证；而API接口可以开启认证，也可以不开启。

**Comment by ccfish86** [comment]
这个可以通过nginx把对应的location以其他端口（如80）形式映射出来。

**Comment by glameyzhou** [comment]
是不是可以尝试下，NG转发，对外就暴露一个80

**Comment by photondragon** [comment]
> 这个可以通过nginx把对应的location以其他端口（如80）形式映射出来。

具体是哪些 location 呢？

**Comment by dddNevermore** [comment]
我也碰到了这个问题,目前版本1.1.4:
api接口,如 `http:serverIp:8848/nacos/v1/cs/configs?dataId=dataIdparam&group=groupParam&tenant=tenantParam`
在postman都是可以直接访问的,对服务的增删改查接口也是一样,这相当于我的服务可以任人查询,改动,删除(如果他人知道具体id)
我认为这是极不安全的
我试着用目前最新版1.3.2:
因为1.2之后加入了鉴权,但对于API接口还是可以直接访问,可能是我没有配置?
-----------------------
还是认同一楼的建议:
API可以不鉴权,只能通过内网访问.
管理页面必须鉴权
