### ISSUE TITLE
新建配置时点击发布没反应,F12报main.js:38 Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined

### ISSUE THREAD

**Issue by baldass** [alibaba/nacos#2772]
我新建配置的时候点击发布,页面没反应,返回刷新查看不成功,
F12显示页面报错,使用的时master分支上打包的nacos server,
```
Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined
    at main.js:38
    at main.js:70
    at Array.<anonymous> (main.js:70)
    at main.js:70
    at r (main.js:33)
    at e (main.js:33)
    at a (main.js:70)
    at n.value (main.js:38)
    at main.js:70
    at e (main.js:33)
```
![bug](https://user-images.githubusercontent.com/31951988/81466214-4bf29380-9202-11ea-9098-68f458783861.png)

**Comment by laoshancun** [comment]
same issue on chrome and edge.

**Comment by baldass** [comment]
经测试当输入的配置又有几个(我设置了3个)时是可以发布的,但是如果正常项目那么多的配置(我配置了数据库,mybatis等)直接发布就会报这种错误
但是修改配置可以绕过这个bug

**Comment by laoshancun** [comment]
Comment with `#` would cause the Error,It works fine by removing comments.
