### ISSUE TITLE
建议发布版本时也发布一个对应的docker镜像

### ISSUE THREAD

**Issue by Jnoee** [alibaba/nacos#278]
有docker镜像方便测试、部署、升级，请考虑下这个需求。

另外 startup.sh 脚本最后一行是echo命令，给自制docker镜像也带来点麻烦，会导致容器运行起来马上就退出了。

**Comment by hxy1991** [comment]
👍 我们有同学在搞 docker 及 k8s 这块了，后续也会考虑跟着版本发布。感谢您的建议。

**Comment by pguo65535** [comment]
这块主要会在项目 
https://github.com/nacos-group/nacos-docker
https://github.com/nacos-group/nacos-k8s 中

等待 这一块 Ready 之后会在nacos 官网文档中将  Deployment Nacos with Kubernetes & Docker Guide 放出来
