### ISSUE TITLE
使用nacos做配置中心，可以设置配置文件的文件夹么，发现文件多了不方便管理

### ISSUE THREAD

**Issue by decademj** [alibaba/nacos#2780]
使用nacos做配置中心，可以设置配置文件的文件夹么，发现文件多了不方便管理，或者针对文件较多的时候，有什么好的建议

**Comment by chuntaojun** [comment]
> 使用nacos做配置中心，可以设置配置文件的文件夹么，发现文件多了不方便管理，或者针对文件较多的时候，有什么好的建议

目前nacos的配置设置层级就只有两层，group以及dataId，可以用group做分组，配合搜索查询
