### ISSUE TITLE
dubbo 2.7.6使用dubbo-registry-nacos注册服务，服务名不正常

### ISSUE THREAD

**Issue by yinjunonly** [alibaba/nacos#2787]
#环境
spring boot  2.x
dubbo 2.7.6
dubbo-registry-nacos 2.7.6
nacos-server 1.2.1
java 1.8

#问题
1.如下图所示，注册进去的服务没有加group的都多一个冒号，在获取服务的时候却没有加这冒号，导致服务消费的时候获取不到不到。
![image](https://user-images.githubusercontent.com/21699758/81636044-5e104400-9445-11ea-816a-ae32970feda6.png)
![image](https://user-images.githubusercontent.com/21699758/81636190-c95a1600-9445-11ea-8a8f-0598196d0b37.png)

**Comment by mercyblitz** [comment]
Please try this : https://github.com/apache/dubbo/issues/5956

**Comment by yinjunonly** [comment]
> Please try this : [apache/dubbo#5956](https://github.com/apache/dubbo/issues/5956)

No effect.

**Comment by yinjunonly** [comment]
难道不是普遍现象吗？

**Comment by xiejunxing** [comment]
解决了吗？

**Comment by xiejunxing** [comment]
> #环境
> spring boot 2.x
> dubbo 2.7.6
> dubbo-registry-nacos 2.7.6
> nacos-server 1.2.1
> java 1.8
> 
> #问题
> 1.如下图所示，注册进去的服务没有加group的都多一个冒号，在获取服务的时候却没有加这冒号，导致服务消费的时候获取不到不到。
> ![image](https://user-images.githubusercontent.com/21699758/81636044-5e104400-9445-11ea-816a-ae32970feda6.png)
> ![image](https://user-images.githubusercontent.com/21699758/81636190-c95a1600-9445-11ea-8a8f-0598196d0b37.png)
> 
> ### 请问如何解决

解决了吗？我也遇到这样的问题呀

**Comment by nickwongwong** [comment]
看了下源码
新版dubbo服务名的格式是 `{interface}:[version]:[group]`，最后一个冒号后面的空白应该是分组名

![image](https://user-images.githubusercontent.com/16626084/111104230-2bfecf80-858b-11eb-8216-f57195f5a15b.png)

https://github.com/apache/dubbo/blob/e02be08be36dcca3e986cf82a43ee121c739eb2f/dubbo-common/src/main/java/org/apache/dubbo/common/URL.java#L1483
