### ISSUE TITLE
版本1.2.1,服务上线/下线 在自定义group 无效

### ISSUE THREAD

**Issue by hexw** [alibaba/nacos#2791]
服务上线/下线 在自定义 group 无效

**Comment by hexw** [comment]
服务上线/下线 在自定义 group 无效 ,只在DEFAULT_GROUP生效

**Comment by hexw** [comment]
InstanceTable.js 中 switchState 中没传 groupName 

switchState(index, record) {
    const { instance } = this.state;
    const { ip, port, ephemeral, weight, enabled, metadata } = record;
    const { clusterName, serviceName, **groupName** } = this.props;
    request({
      method: 'PUT',
      url: 'v1/ns/instance',
      data: {
        serviceName,
        clusterName,
        **groupName**,
        ip,
        port,
        ephemeral,
        weight,
        enabled: !enabled,
        metadata: JSON.stringify(metadata),
      },
      dataType: 'text',
      beforeSend: () => this.openLoading(),
      success: () => {
        const newVal = Object.assign({}, instance);
        newVal.list[index].enabled = !enabled;
        this.setState({ instance: newVal });
      },
      error: e => Message.error(e.responseText || 'error'),
      complete: () => this.closeLoading(),
    });
  }

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2793

**Comment by chuntaojun** [comment]
@hexw 可以看下1.3.0-beta版本，问题已经修复了
