### ISSUE TITLE
1.2.1 集群模式下为什么没有显示修改人的的信息。

### ISSUE THREAD

**Issue by ordercard** [alibaba/nacos#2792]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
当我们修改配置的时候为什么不显示最后一次的修改人 ；
已经在配置的历史版本列表为什么不可以有修改人的名字和正确的更新时间
![image](https://user-images.githubusercontent.com/22793054/81673152-c1b66380-947d-11ea-817d-382d332fed52.png)

### Describe what you expected to happen

修改配置的时候为什么为什么不能显示最后一次的修改人 已经在配置的历史版本的对应的修改人是谁
并且数据库有这个字段为什么不用呢

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zhenxianyimeng** [comment]
@i will solve it@

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2699

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2863
