### ISSUE TITLE
  急 急 急 !!!!一直 报 日志  get changedGroupKeys:[] 

### ISSUE THREAD

**Issue by yumrko** [alibaba/nacos#2803]
1.如下版本 
        <boot.version>2.2.5.RELEASE</boot.version>
        <cloud.version>Hoxton.SR4</cloud.version>
        <alibabacloud.version>2.2.1.RELEASE</alibabacloud.version>

        2整合了 springcloud alibaba的 nacos sentinel seata dubbo 
        启动无问题 过一会控制太就出 get changedGroupKeys:[]
       ClientWorker类中有一个 这样的一段代码如下

      ClientWorker.LOGGER.info("get changedGroupKeys:" + changedGroupKeys);

        3 yaml 中 只配置了 
spring:
  application:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        prefix: common #自定义的略过
        server-addr: 127.0.0.1:8848
        file-extension: yaml   #默认properties

个人洁癖, 看着很不爽,老是报这个日志,很烦, 需要配置什么  怎样配置呢 还是哪里有问题 啊

**Comment by yumrko** [comment]
nacos1.2.1 版本

**Comment by yumrko** [comment]
refresh-enabled: false 就好了  但是不能自动刷新了啊

**Comment by hexw** [comment]
md5 加密问题,最新代码已修复

**Comment by hexw** [comment]
#2763 2647

**Comment by hexw** [comment]
#2647

**Comment by chuntaojun** [comment]
already fix in version 1.3.0-beta

**Comment by eimlfang** [comment]
Still happen in version 1.3.2-release

**Comment by YAOAORAN** [comment]
Still happen in version 1.3.3-release
