### ISSUE TITLE
nacos1.2.1 重新编辑配置文件 发布后 创建了新的同名配置文件

### ISSUE THREAD

**Issue by han-bing** [alibaba/nacos#2812]
nacos 版本 1.2.1
创建yaml配置文件并发布， 重新编辑文件内容后再次发布，现在显示两个重名的配置文件，配置文件内容相同。

**Comment by chuntaojun** [comment]
分组也相同吗

**Comment by han-bing** [comment]
分组相同，文件名相同，内容相同

**Comment by chuntaojun** [comment]
> 分组相同，文件名相同，内容相同

麻烦截个图，因为数据库是存在约束的，data-id+group+namespace必须是唯一的

**Comment by han-bing** [comment]
我现在没有测试条件，记得环境是debian-10，没有更多信息能提供了。
