### ISSUE TITLE
Can it support shared namespace

### ISSUE THREAD

**Issue by xinhans** [alibaba/nacos#2815]
**Appeal**: Can it support shared namespace?

**Usage scenario**: We have a lot of middle-stage services. These services are highly sophisticated and are a kind of microservices based on spring cloud. We want to distinguish development and test environments by namespace, but at the same time we want to use these highly perfect middle-stage services only. Deploy a set in our kubernetes cluster, and then both the development environment and the test environment can discover the center service of our shared namespace

**Comment by chuntaojun** [comment]
Cross-namespace is not allowed

**Comment by xinhans** [comment]
> Cross-namespace is not allowed

i know,but hope to support it in special sence.

**Comment by chuntaojun** [comment]
Namespaces are inherently used for environmental isolation, and across namespaces they lose their meaning

2020年5月15日 下午10:36，xinhans <notifications@github.com<mailto:notifications@github.com>> 写道：



Cross-namespace is not allowed

i know,but hope to support it in special sence.
