### ISSUE TITLE
Service downtime caused by thread leak

### ISSUE THREAD

**Issue by kitsrc** [alibaba/nacos#2819]
## Issue Description
Service downtime caused by thread leak
线程泄漏引起的服务宕机

线程泄漏引起 Spring-Cloud-Gateway 
Nacos 版本 1.2.1 
Spring-Cloud-Gateway   2.2.2.RELEASE

停服日志
[hs_err_pid33325.log](https://github.com/alibaba/nacos/files/4639907/hs_err_pid33325.log)

调试定位时 线程dump 日志
启动时 无请求
[thread-11252-160218.txt](https://github.com/alibaba/nacos/files/4639909/thread-11252-160218.txt)
启动后 一次请求
[thread11252-160416.txt](https://github.com/alibaba/nacos/files/4639911/thread11252-160416.txt)
启动后 10+次请求
[thread11252-160748.txt](https://github.com/alibaba/nacos/files/4639912/thread11252-160748.txt)

根据线程名称 
com.alibaba.nacos.client.config.security.updater
定位到源码 
![image](https://user-images.githubusercontent.com/23493090/82139641-fbabaf00-985b-11ea-96c3-3c636706a7ee.png)

请帮忙协助解决问题

Type: *bug report* 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
Did you use @refreshscope

**Comment by kitsrc** [comment]
yes ,  I used 

Yesterday, I closed @ refreshscope and left it idle for one night. The total number of application threads is 3415

com.alibaba.nacos.client.related thread 3300+

See the thread dump log for details

昨天关闭@RefreshScope 空载静置一晚，应用线程总数 3415
com.alibaba.nacos.client. 相关线程 3300+
具体请看 线程 dump日志
[threaddump-11968-05180946.log](https://github.com/alibaba/nacos/files/4641621/threaddump-11968-05180946.log)

**Comment by MichaelQiaoDang** [comment]
Mr LiJie !  your java is very good  but English  is very poor ！

**Comment by kitsrc** [comment]
emmmm……  The level of machine translation determines my level
机器翻译的水平决定了我的水平

**Comment by yfh0918** [comment]
可以增加一个Runtime.getRuntime().addShutdownHook,关闭的时候把ServerHttpAgent close掉，同时可以把里面用到的线程池资源做释放，或者如果全局有释放资源的地方可以做个callback处理

**Comment by yfh0918** [comment]
如果这样做没有问题的化可以让我来处理

**Comment by yfh0918** [comment]
思路如下：
具体可以做一个lifecycle接口定义生命周期，ServerHttpAgent实现lifecycle的接口，然后启动ServerHttpAgent的时候，把ServerHttpAgent注册到lifecyclemanger, 系统关闭的时候可以回调lifecycle的关闭操作做整体的资源释放

**Comment by yfh0918** [comment]
其实，引申出来可以把lifecycle作为全局接口，任何需要释放资源的都可以实现该接口

**Comment by chuntaojun** [comment]
you can see here : https://github.com/alibaba/nacos/issues/1815

**Comment by zongtanghu** [comment]
@yfh0918 @chuntaojun  I have already did this issue taks and put forward a pr this week.If you have any question, we can disscuss here.Thanks.

**Comment by yfh0918** [comment]
OK , We can do better, like jetty's life cycle management of component

**Comment by zongtanghu** [comment]
Yes, we can do it better.
