### ISSUE TITLE
nacos中的raft 发布数据问题请教

### ISSUE THREAD

**Issue by pan289091315** [alibaba/nacos#2833]
nacos中的raft发布数据时，直接 提交吗？
![image](https://user-images.githubusercontent.com/6639546/82304521-08acd780-99ef-11ea-96a4-daa6cab61f08.png)

疑问：
 raft算法不是会先预提交大多数节点吗？我看nacos raft实现直接commit一步到位。

可能造成问题：
如果调用这个方法后，leader挂了且还没有给客户端正确的答复。重新选举的时候会不会数据已经是提交的。

**Comment by chuntaojun** [comment]
Currently, the Raft protocol of the service discovery module of nacos is a variant version, not the standard Raft. Later, it will be implemented based on the 1.3.0-beta pair of Raft protocols connected to the standard

**Comment by Garlichead** [comment]
wait
