### ISSUE TITLE
配置权限后，点击无权限命名空间后页面一直loading，切换到有权限的空间仍继续loading，需要页面刷新才可以

### ISSUE THREAD

**Issue by JasonMsbaby** [alibaba/nacos#2835]
配置权限后，
点击无权限命名空间后页面一直loading，
切换到有权限的空间仍继续loading，需要页面刷新才可以
![image](https://user-images.githubusercontent.com/11964522/82339462-a371da00-9a20-11ea-8bec-6715b4ad6885.png)

**Comment by ljhrot** [comment]
@i will solve it@
