### ISSUE TITLE
How to monitor add or remove a Data Id on ConfigService?

### ISSUE THREAD

**Issue by dongzl** [alibaba/nacos#2836]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

at this issue #2335 , I want to monitor add a new key on ConfigService, and the reply suggest to use `AbstractConfigChangeListener ` . But I use this function, it doesn't meet my requirements.

### Describe what you expected to happen
If I have the key `orchestration_config.config.props`, and the content is :
```
executor.size: 16
check.table.metadata.enabled: true
```
If the `executor.size` is changed, the `AbstractConfigChangeListener `  can monitor.

But My requirement is when add or remove a **Data Id**, the `nacos-client` can monitor, and how to implement it, Thanks.

**Comment by chuntaojun** [comment]
Configuration file increases or decreases will not be monitored

**Comment by dongzl** [comment]
> Configuration file increases or decreases will not be monitored

Thanks for reply.

You meaning is if I add or remove a Data Id at nacos Configuration, it can not be monitored for the client. 

it will be support in the future?

**Comment by chuntaojun** [comment]
> > Configuration file increases or decreases will not be monitored
> 
> Thanks for reply.
> 
> You meaning is if I add or remove a Data Id at nacos Configuration, it can not be monitored for the client.
> 
> it will be support in the future?

I don't think this is a feature that can be added. Can you describe why you need this feature

**Comment by dongzl** [comment]
Hi @chuntaojun , Thanks.

Now, I am integrating nacos as `RegistryCenter` and `ConfigCenter` for [Apache ShardingSphere](https://github.com/apache/shardingsphere).

If user add some new `Data Id` for a Database schema info, 
e.g `orchestration_config.config.schema.xxxx.datasource` (a new datasource config)
       `orchestration_config.config.schema.xxxx.rule` (a new sharding rule)

It can notify ShardingSphere to refresh memory and load some data.

If nacos can't monitor add a new `Data Id`, user must restart their application.

and remove `Data Id` is a opposite process,  Thanks.

**Comment by chuntaojun** [comment]
We will consider adding this function after internal communication

**Comment by dongzl** [comment]
> We will consider adding this function after internal communication

Thanks very much.

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/1883

**Comment by KomachiSion** [comment]
duplicate with #422.

**Comment by geyunhu** [comment]
Is the function of monitor add or remove a Data Id currently supported?
