### ISSUE TITLE
Building adaptive connection channels

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#2851]
#### Background
In the process of node restart and network outage recovery, unbalanced service load will lead to hot spots and current limiting problems. Therefore, it is necessary to design lossless and measurable connection channels as balanced and changeable as possible.<br />

<a name="BL8nP"></a>
#### Design objectives
Adaptive load balancing, lossless release, push SLA measurable connection channel<br />

<a name="ltXxi"></a>
#### Reference ideas

- Adaptive back pressure, according to the capacity and load, when the pressure is high, let the client route to other nodes to prevent the single point pressure from being too high
- To restart publishing, you need to let the connection float away in advance before restarting, so as to prevent the loss of publishing traffic. The last batch of machines will not have traffic
- Server nodes are under great pressure. You can forward requests to other pressure nodes
- The mode and cycle of health examination are adjusted automatically according to the network and system pressure
- Push SLA can be measured, client exception can be sensed by server, and early warning can be given

----- 

### 构建自适应连接通道
<a name="h2NEe"></a>
#### 背景
节点重启发布和断网恢复过程中，服务负载不均衡会导致热点和限流问题。因此需要设计尽可能均衡和变更无损和可度量的连接通道。
<a name="MVW3G"></a>
#### 设计目标
自适应负载均衡，能够无损的发布，推送SLA可度量的连接通道
<a name="K8BN2"></a>
#### 参考思路

- 自适应反压，根据容量和负载，压力大时候让客户端路由到其他节点，防止单点压力过大问题
- 重启发布，需要重启前让连接提前飘走，防止发布流量损失，发不完最后一批机器没有流量
- Server节点压力大可以把请求转发其他压力小节点
- 健康检查方式、周期根据网络和系统压力自动调节
- 推送SLA可度量，客户端异常Server可感知，可以预警

**Comment by RonnieGandhi** [comment]
Hello sir,
I am Ronnie Gandhi, a Computer Science undergraduate from IIT Roorkee. I have done GSoC 2019 under CGAL, besides I have done an intern at Microsoft, Hyderabad and I am currently doing an intern there as well.

This project seems interesting to me could you please inform/guide me where to start from and what are the requirements for this project.

**Comment by yanlinly** [comment]
> Hello sir,
> I am Ronnie Gandhi, a Computer Science undergraduate from IIT Roorkee. I have done GSoC 2019 under CGAL, besides I have done an intern at Microsoft, Hyderabad and I am currently doing an intern there as well.
> 
> This project seems interesting to me could you please inform/guide me where to start from and what are the requirements for this project. I am interested in working on this project.

You can refer to this document to sign up
https://github.com/alibaba/nacos/issues/2850

**Comment by yanlinly** [comment]
> Hello sir,
> I am Ronnie Gandhi, a Computer Science undergraduate from IIT Roorkee. I have done GSoC 2019 under CGAL, besides I have done an intern at Microsoft, Hyderabad and I am currently doing an intern there as well.
> 
> This project seems interesting to me could you please inform/guide me where to start from and what are the requirements for this project. I am interested in working on this project.

Hi RonnieGandhi，Have you submitted your ideas, do you need my help?
my email is water.lyl@alibaba-inc.com. Please contact me if you have any questions.

You can follow the link below to submit your plan：

Step1:
https://github.com/alibaba/nacos/issues/2850?spm=a3c0i.14652930.2047843740.10.6b14639e5fnoiV

Step2:
https://page.aliyun.com/form/act1853231099/index.htm?spm=a2c6h.14553213.J_1935739830.1.156922c1Wstwld

**Comment by chaytanyasinha** [comment]
Hello @yanlinly I am an undergraduate.I am well experienced in Open Source.I have knowledge of Java,C++,Python and Kotlin.
I am very much interested in contributing to Nacos with this project and to get experience with you guys.
Sorry for being late and to save time I went through #2850 as suggested by you.
I am getting started with my proposal and expecting guidance from you.

**Comment by yanlinly** [comment]
> Hello @yanlinly I am an undergraduate.I am well experienced in Open Source.I have knowledge of Java,C++,Python and Kotlin.
> I am very much interested in contributing to Nacos with this project and to get experience with you guys.
> Sorry for being late and to save time I went through #2850 as suggested by you.
> I am getting started with my proposal and expecting guidance from you.


You can click on this link to submit you idea:

Chinese: https://developer.aliyun.com/topic/summerofcode2020
English: https://www.alibabacloud.com/campaign/summerofcode2020

**Comment by chaytanyasinha** [comment]
@yanlinly Sure.
