### ISSUE TITLE
Build an embedded anti fragile system

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#2853]
#### Background
Because Nacos is the most core and bottom-level service of distributed service, there is a large cluster shared by the whole company, which requires high stability, so Nacos service is required to be online forever!<br />

<a name="rt1di"></a>
#### Design objectives
100% data is not lost and 99.999% service is available.

#### Reference ideas

- Capacity management
- According to the capacity model, according to different resource types, production capacity report (Guide k8s to automatically scale) and capacity protection threshold (to prevent explosion)
- Traffic management
- Support multi-dimensional traffic (IP, access to resources, AK / SK / KP) monitoring
- Ability to dynamically adjust flow control rules
- Over capacity planning, automatic current limiting capacity
- Automatic identification of hot spot isolation capability
- Degradation capability
- Sort out all core competencies, arrange and sort out priorities, and support automatic degradation capability.
- If the total load is exceeded, it will be degraded automatically according to the service priority.
- Data disaster recovery, backup and recovery capabilities
- Support multi-level data disaster recovery mechanism
- Support data scheduled backup and recovery capability

----- 

### 构建内嵌的反脆弱体系
<a name="aJ0SG"></a>
#### 背景
由于Nacos是分布式服务最核心最底层的服务，有是一个全公司共享的大集群，对稳定性要求极高，因此需要Nacos服务永远在线！
<a name="IvRWL"></a>
#### 设计目标
数据100%不丢，服务99.999%可用的反脆弱体系。
<a name="Hkroy"></a>
#### 参考思路

- 容量管理
  - 根据容量模型自动根据不同资源类型，生产容量报告（指导K8s自动伸缩）和容量保护阈值（防止被打爆）
- 流量管理
  - 支持多维度流量（ip、访问资源、ak/sk/kp维度进行流控）监控
  - 动态调节流控规则能力
  - 超过容量规划部分，自动限流能力
  - 自动识别热点隔离能力
- 降级能力
  - 梳理所有核心能力，做好优先级的编排梳理，并且支持自动降级能力。
  - 超过总体负载，根据服务优先级，自动降级。
- 数据容灾、备份、恢复能力
  - 支持多级数据容灾机制
  - 支持数据定时备份恢复能力

**Comment by zongtanghu** [comment]
I have a strong interested in this important feature and want to participate in it. @yanlinly @chuntaojun

**Comment by jintonghuoya** [comment]
I also have a strong interested in this important feature and want to participate in it. @yanlinly @chuntaojun

**Comment by zongtanghu** [comment]
This feature issue can be assigned to me firstly. @yanlinly @KomachiSion
