### ISSUE TITLE
Unified implementation of Http requests

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#2858]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

background
1. At present, the implementation of http requests in nacos is too disorderly, JDK, HttpClient, and Netty-HttpClient
2. It is necessary to do a layer of abstract processing for httpclient in the nacos-common package, and install the specific httpclient implementation to avoid overcoupling the nacos project with a certain http implementation
Ideas
1. You can refer to the design of Spring's RestTemplate
2. At present, it is only a simple abstraction in nacos-common http, which can be optimized and reconstructed

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Maijh97** [comment]
@i will solve it@
