### ISSUE TITLE
The notify implementation within nacos-common module radiates to all nacos modules

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#2859]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

background
1. At present, whether nacos is a client or a server, the code of the event mechanism is too fragmented, and the realization of a unified event mechanism is needed
Ideas
1. The code of the current event mechanism has sunk into the notification of nacos-common
2. Replace the implementation of the notification of nacos-common with the code of the existing old event mechanism, and remove all EventDispatcher
3. According to the nature of the event, determine whether a separate event publisher is needed

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zongtanghu** [comment]
Hi chuntaojun @chuntaojun , this issue can be assign to me , thanks.

**Comment by zongtanghu** [comment]
"The notify implementation within nacos-common module radiates to all nacos modules" can be split into serveral pr, includes:

(1)Sink the Notify implementation into common module and optimize some parts.
(2)Replace the original Notify implementation in the core module and which is called places in other module;
(3)Replace Event Dispatcher in other module;

**Comment by zongtanghu** [comment]
This issue has already been finished, except for naming event dispatcher.So I will close this issue, and reopen an other issue to follow up naming event dispatch replacement.
