### ISSUE TITLE
Maven dependency optimizations, where only one version of each dependency exists

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#2860]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

background
1. At present, the internal dependencies of nacos are relatively disordered, and the unused and repeated dependencies need to be removed
2. For example, if you rely on netty, it is best to ensure that you only rely on one netty version, and do not have multiple netty versions.
Ideas
1. Clearly sort out the current maven dependencies
2. For version control, it is best to use the form of properties

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jintonghuoya** [comment]
@i will solve it@
