### ISSUE TITLE
After the Nacos 1.2.1 web interface manually creates a service, it will be automatically deleted by the system. Is this normal?

### ISSUE THREAD

**Issue by qwerplf** [alibaba/nacos#2864]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

External PV + external MySQL + modified nacos-quick-start.yaml After deployment, leaders are selected for Nacos cluster, and no error is reported by the cluster, as shown in the following figure:
![image](https://user-images.githubusercontent.com/23162792/82658521-b7545080-9c59-11ea-84c0-731177465105.png)
The web interface also shows:
![image](https://user-images.githubusercontent.com/23162792/82658564-c804c680-9c59-11ea-984f-653ab8e454fd.png)
But the problem is, I create the service manually in the web interface, and after about one minute, the service is automatically deleted. I can see the trace of creation and deletion in the log. Is this normal?
![image](https://user-images.githubusercontent.com/23162792/82658607-dc48c380-9c59-11ea-8b0b-3746abe83c79.png)
![image](https://user-images.githubusercontent.com/23162792/82658613-e1a60e00-9c59-11ea-92b0-c9a5f225df12.png)
![image](https://user-images.githubusercontent.com/23162792/82658622-e66ac200-9c59-11ea-960d-f09abfc7c6bf.png)

### Describe what you expected to happen
I just want to make sure that this behavior of the system is normal? What causes this phenomenon

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
If an empty service is automatically deleted, this is normal and you can set it "nacos.naming.empty-service.auto-clean=false"，If it is a service instance, as long as you register a non-persistent instance, it will be automatically removed

**Comment by KomachiSion** [comment]
No response more than 7 days, close issue.
