### ISSUE TITLE
DataID Load Configuration project: The default space+ The default grouping + The new dev and The new test two DataID  of bug

### ISSUE THREAD

**Issue by cunweizhao** [alibaba/nacos#2865]
## Issue Description
Today, I used nacos for configuration. I created two DataID in the default group and the default space, which can be accessed normally when using the Dev environment. When switching to the test environment, I failed to get the injected configuration information when reporting an error.
### Describe what happened (or what feature you want)
I think both environments can be accessed correctly
### How to reproduce it (as minimally and precisely as possible)
1. The version of Nacos I used was Windows nacos-server-1.2.1
2. The jar I used is spring-cloud-starter-alibaba  ，version：2.1.0.RELEASE
3. YML：
----------------------------------bootstrap.yml--------------------------------
server:
  port: 3377
spring:
  application:
    name: nacos-config-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 
      config:
        server-addr: localhost:8848 
        file-extension: yaml 
-----------------------------------end-----------------------------------------------------
---------------------------------------application.yml-------------------------------------
spring:
  profiles:
       active: dev # 开发环境
#       active: test # 测试环境
#    active: info # 开发环境
-------------------------------------end-----------------------------------------------------
--------------------------------------Test Class-----------------------------------------------
@RestController
@RefreshScope 
public class ConfigClientController {
    @Value("${config.info}")
    private String configInfo;

    @GetMapping("/config/info")
    public String getConfigInfo(){
        return configInfo;
    }
}
------------------------------------------end---------------------------------------------------------
If you don't know, you can visit my blog: https://zhaocunwei.blog.csdn.net/?orderby=UpdateTime
The title of the article is: 《【原来阿里巴巴大神也是人】-SpringCloudAlibaba之Nacos 配置中心的Bug---已经提交社区》

**Comment by chuntaojun** [comment]
Have you ever debugged the process to make sure that the data-id information that is eventually pulled is correct

**Comment by cunweizhao** [comment]
At present, I am in the learning stage and have no source code to debug. At present, DdataID is the same as DdataID, and the registration information cannot be obtained if the Group is different.

**Comment by cunweizhao** [comment]
Feels like when multiple are created, only the first one loads by default

**Comment by cunweizhao** [comment]
> 您是否调试过该过程，以确保最终提取的data-id信息是正确的

Feels like when multiple are created, only the first one loads by default

**Comment by cunweizhao** [comment]
> Have you ever debugged the process to make sure that the data-id information that is eventually pulled is correct

Feels like when multiple are created, only the first one loads by default
