### ISSUE TITLE
Nacos permissions that this set here besides nacos account and other access is 403 / nacos/v1 / ns/operator/metrics

### ISSUE THREAD

**Issue by purgeyao** [alibaba/nacos#2866]
nacos  权限这这块  ，这里设置除了nacos账号，其他访问都是403   /nacos/v1/ns/operator/metrics

导致/actuator/health  里的nacosDiscovery状态为DOWN   这个请求整体"status": "DOWN", 
我们的监控监控无法正常。

Nacos permissions that this set here besides nacos account and other access is 403 / nacos/v1 / ns/operator/metrics

... '> cause the nacosDiscovery status in/in /health to be DOWN. This request overall "status": "DOWN",
Our surveillance is not working.

<img width="853" alt="A4BC698D-361C-44A2-A73B-1694DBC87C8C" src="https://user-images.githubusercontent.com/36881032/82659504-647b9880-9c5b-11ea-9e3f-3a891518ea7b.png">
<img width="816" alt="855F3F9B-8594-41BD-8306-15CB88294CE5" src="https://user-images.githubusercontent.com/36881032/82659514-66ddf280-9c5b-11ea-833d-80fc640a8646.png">
<img width="456" alt="270F12F3-5994-49DB-98BF-1872D7F6F510" src="https://user-images.githubusercontent.com/36881032/82659524-69404c80-9c5b-11ea-9746-f7a624c4d32b.png">

**Comment by chuntaojun** [comment]
com.alibaba.nacos.naming.controllers.OperatorController#metrics

**Comment by xiaoxiangzhenyu** [comment]
『/nacos/v1/ns/operator/metrics 403』这个问题确实存在，原因是AuthFilter.doFilter()方法中的『String resource = secured.resource()』，在获取到OperatorController.metrics()的secured注解配置的resource="naming/metrics"后，没有考虑命名空间和分组，因为Permission中resource由namespaceId:groupName:serviceName的格式组成，导致最终在NacosRoleServiceImpl.hasPermission()方法中用正则匹配时不通过！

具体详情可以看下另外一位网友的帖子：https://www.jianshu.com/p/560ba0d67c50

**Comment by purgeyao** [comment]
@xiaoxiangzhenyu 首先感谢回答，是这样的。这个issue正在努力推进中

**Comment by wpt191** [comment]
首先感谢阿里大佬们的辛苦，此问题预计解决时间，这边方便告知下不。

**Comment by David-wu91** [comment]
此问题在1.3.1版本中还没得到修复，请问各位阿里大佬方便告知一下此问题的修复计划吗？

**Comment by wpt191** [comment]
用户授权相关的，是需要等1.4.0版本吗？
