### ISSUE TITLE
支持不同语言项目的服务注册和监听吗

### ISSUE THREAD

**Issue by GeTOUO** [alibaba/nacos#2867]
## 我的问题是
1. 支持c++等其它项目注册吗
2. 支持服务状态监听吗？比如服务上线下线时给其它在线的服务推送变更通知
3. 服务注册时支持扩展字段吗？比如携带服务支持的通信协议(sip,rtp,....)

**Comment by KomachiSion** [comment]
1. 目前社区官方支持golang和java，非社区官方有一些php和c#等语言的实现，**有兴趣的话欢迎贡献实现**。
2. 支持
3. 服务的可以自己添加一些元数据，不知道是否满足需求。

**Comment by Akuns** [comment]
居然没有PHP
