### ISSUE TITLE
Nacos 注册中心 springboot 版本为何不能自动获取IP

### ISSUE THREAD

**Issue by treasureMoment** [alibaba/nacos#2877]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

Nacos 注册中心 springboot 版本为何不能自动获取IP，客户端注册时还得填写IP地址

**Comment by EasonFeng5870** [comment]
@i will solve it@

**Comment by chuntaojun** [comment]
> @i will solve it@

You have to go to the nacos-springboot project to solve it

**Comment by EasonFeng5870** [comment]
> > @i will solve it@
> 
> You have to go to the nacos-springboot project to solve it

Thanks for the tips, Is in the following link, right ?
https://github.com/nacos-group/nacos-spring-boot-project

**Comment by chuntaojun** [comment]
> https://github.com/nacos-group/nacos-spring-boot-project

yes

**Comment by EasonFeng5870** [comment]
> > https://github.com/nacos-group/nacos-spring-boot-project
> 
> yes

Thanks very much,  working on it.

**Comment by EasonFeng5870** [comment]
- I found that you don't need to use `nacos.discovery.register.ip` property to mark your current startup's server ip address in the auto-register=true model, it will auto-register your local ip address by using NetUtils.localIP() method.
- Or you are using nacos.discovery.auto-register=false model and you don't want to setup ip address manualy? In that case, I think that we can support setup ip address for auto-register is false mode.
- So, which one is your need @treasureMoment ?

**Comment by treasureMoment** [comment]
I hope that if auto-register=true mode, clients can automatically register services in the configuration center without specifying IP addresses,Otherwise, you need to know the IP address of this machine when migrating services

**Comment by treasureMoment** [comment]
Or the register method of the client provides functions that do not require IP parameters

**Comment by treasureMoment** [comment]
sorry,auto-register=true 
It can meet the current needs

**Comment by treasureMoment** [comment]
Now there are other problems：
`spring:
  application:
    name: locate-service
  profiles:
    active: dev
nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 10.95.5.18:8848
    remote-first: true
    namespace: 65ffd2cc-f006-42df-a333-ea07ff874b39
    data-ids: LOCATE_WEB
    group: LOCATE
    type: yaml
    auto-refresh: true   
  discovery:
    server-addr: 10.95.5.18:8848
    auto-register: true`
This is my configuration

log info:
![image](https://user-images.githubusercontent.com/35365475/88034922-f4fb2a00-cb73-11ea-840e-1f1ffb55526e.png)
However, the registered services are not visible in the service list of the console
![image](https://user-images.githubusercontent.com/35365475/88035014-178d4300-cb74-11ea-8850-86755df0a3c1.png)

There is no problem using only the registry center

**Comment by treasureMoment** [comment]
跟踪代码发现。同时引入nacos-config-spring-boot-starter 和nacos-discovery-spring-boot-starter ，配置文件中只配置discovery，启动后 通过@NacosInjected 注入的namingService 的serverAddr 为默认的127.0.0.1:8848 非配置文件中的配置。去掉nacos-config-spring-boot-starter的引用后正常
