### ISSUE TITLE
1.2.1版本，linux下-m standalone参数不起作用？

### ISSUE THREAD

**Issue by fy8207345** [alibaba/nacos#2881]
debian 10.4系统下，1.2.1版本，使用命令：sh startup.sh -m standalone
启动时，会打出：nacos is starting with cluster。然后找不到cluster.conf，启动失败。

**Comment by chuntaojun** [comment]
可以调试下shell脚本，我这里测试是没有你说的问题的

**Comment by fy8207345** [comment]
> 可以调试下shell脚本，我这里测试是没有你说的问题的
startup.sh 第一行由
#!/bin/sh
改成
#!/bin/bash
sh解释器不行，使用bash才可以。
官网说明写的有点问题-》https://nacos.io/zh-cn/docs/deployment.html

**Comment by chuntaojun** [comment]
We'll complete that in the documentation
