### ISSUE TITLE
nacos 设置权限无效

### ISSUE THREAD

**Issue by sunjin-zbj** [alibaba/nacos#2882]
Nacos default account login, new test and production namespace new users and roles, logout with the newly created user login authority has not taken effect
![image](https://user-images.githubusercontent.com/55384013/82802414-6f2f6b00-9eb1-11ea-8104-79f629010190.png)
![image](https://user-images.githubusercontent.com/55384013/82802478-8bcba300-9eb1-11ea-98b8-77bcb25da486.png)

**Comment by sunjin-zbj** [comment]
权限配置后没生效

**Comment by xiaoguolong** [comment]
need to set application.properties >>>>nacos.core.auth.enabled=true

**Comment by lyln** [comment]
```
spring.security.enabled=true
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
```
NACOS1.2.1 application.properties 开启参数，设置不同角色，权限并不能生效

**Comment by chuntaojun** [comment]
> Nacos default account login, new test and production namespace new users and roles, logout with the newly created user login authority has not taken effect
> ![image](https://user-images.githubusercontent.com/55384013/82802414-6f2f6b00-9eb1-11ea-8104-79f629010190.png)
> ![image](https://user-images.githubusercontent.com/55384013/82802478-8bcba300-9eb1-11ea-98b8-77bcb25da486.png)

新创建的用户需要过一段时间才可以

**Comment by chuntaojun** [comment]
> ```
> spring.security.enabled=true
> nacos.core.auth.system.type=nacos
> nacos.core.auth.enabled=true
> ```
> 
> NACOS1.2.1 application.properties 开启参数，设置不同角色，权限并不能生效

是否是docker部署？

**Comment by lyln** [comment]
docker和单机部署都不可以

**Comment by Gitwangpin** [comment]
Me too！

**Comment by Gitwangpin** [comment]
Me too！ @chuntaojun

**Comment by chuntaojun** [comment]
> nacos1.3.0设置权限完全不起作用

是否是容器部署？我这里测试是ok的

**Comment by chuntaojun** [comment]
> docker和单机部署都不可以

有没有绑定好对应的namespace已经角色

**Comment by Gitwangpin** [comment]
估计和#3024一样的docke部署的
