### ISSUE TITLE
[bug report] the ip in cluster management list doesn't right when there is multiple network card

### ISSUE THREAD

**Issue by EasonFeng5870** [alibaba/nacos#2883]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
The following is network card information:
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet 10.7.248.100/32 scope global lo
>        valid_lft forever preferred_lft forever
>     inet 10.7.248.101/32 scope global lo
>        valid_lft forever preferred_lft forever
>     inet 10.7.248.102/32 scope global lo
>        valid_lft forever preferred_lft forever
>     inet 10.7.248.103/32 scope global lo
>        valid_lft forever preferred_lft forever
>     inet 10.7.248.104/32 scope global lo
>        valid_lft forever preferred_lft forever
>     inet 10.7.248.105/32 scope global lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether d0:94:66:49:50:ee brd ff:ff:ff:ff:ff:ff
>     inet 10.7.0.18/30 brd 10.7.0.19 scope global noprefixroute eth0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::48ad:5119:6982:e3fb/64 scope link noprefixroute 
>        valid_lft forever preferred_lft forever
> 3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
>     link/ether d0:94:66:49:50:f0 brd ff:ff:ff:ff:ff:ff
> 4: eth2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
>     link/ether d0:94:66:49:50:f2 brd ff:ff:ff:ff:ff:ff
> 5: eth3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
>     link/ether d0:94:66:49:50:f4 brd ff:ff:ff:ff:ff:ff

### Describe what you expected to happen

In the web console, It should show `10.7.0.18` as endpoint ip instead of `10.7.248.100`.

start Nacos up as standalone mode.

### How to reproduce it (as minimally and precisely as possible)

1. Can we set  some command when we start it up to tell nacos server to ignore some network card, like spring cloud did ? `spring.cloud.inetutils.ignored-interfaces[0]=eth0` 
2. 
3. 

### Tell us your environment
Setting up Nacos server on our online server.

**Comment by chuntaojun** [comment]
see here ： https://nacos.io/zh-cn/docs/system-configurations.html

**Comment by EasonFeng5870** [comment]
> see here ： https://nacos.io/zh-cn/docs/system-configurations.html

Thanks very much.
