### ISSUE TITLE
nacos集群作为配置中心，新增/修改配置不能同步到其他集群节点

### ISSUE THREAD

**Issue by MsencSir** [alibaba/nacos#2884]
我在本地哦同意网段下配置启动三个nacos，端口号分别问8848，8849，8850；
使用nginx作为他们负载均衡的访问点；
部分配置如下：
![image](https://user-images.githubusercontent.com/46589466/82812140-e7535c00-9ec4-11ea-97b7-0244c6a1bb63.png)

服务提供者和消费者所用依赖：
![image](https://user-images.githubusercontent.com/46589466/82812175-018d3a00-9ec5-11ea-9b69-c0de84048898.png)

服务者项目配置：
![image](https://user-images.githubusercontent.com/46589466/82812274-3d280400-9ec5-11ea-8c27-602f2d580c26.png)

服务消费者项目配置：
![image](https://user-images.githubusercontent.com/46589466/82812308-516c0100-9ec5-11ea-95dd-b01fe72b576f.png)

访问nacos的nginx的入口：
![image](https://user-images.githubusercontent.com/46589466/82812471-a6a81280-9ec5-11ea-9727-ad84bc6f9b61.png)

单独访问每个节点也都是没有问题的；

问题来了：
1.我通过nacos的nginx的入口进入的管理页面，然后新增/修改配置，发现只会更新其中的一个节点，其他两个节点配置也然是原先的！是nacos集群不支持配置同步还是我配置有问题？？？望大神指点；
2. 我继续验证关闭其中一个8848节点，查看选举是否正常，结果正常，但是我发现本地的测试程序打印的依旧是8848的节点，而且好像是固定请求这个节点了，但是我已经关掉了这个节点啊？再不关闭这个8848节点之前，请求是分发请求三个节点的。不理解？？
3.我把所有的节点都已关闭，发现除了服务消费者和提供者再报连接异常的日志，请求都是正常的！

本人第一次集成nacos,这些问题不是很理解；希望大佬们帮忙指点下；

**Comment by MsencSir** [comment]
补充一下，服务消费我才用feign作为客户端进行消费的；
![image](https://user-images.githubusercontent.com/46589466/82813945-b543f900-9ec8-11ea-8291-68ec53319e27.png)

**Comment by chuntaojun** [comment]
启动集群你要配置cluster.conf文件的

**Comment by MsencSir** [comment]
https://github.com/alibaba/nacos/issues/2884#issuecomment-633573589
肯定是都配置的哦
![image](https://user-images.githubusercontent.com/46589466/82817336-69488280-9ecf-11ea-93a3-9d29457b31ef.png)

**Comment by MsencSir** [comment]
![image](https://user-images.githubusercontent.com/46589466/82817465-a280f280-9ecf-11ea-93be-c65d9c7ca9ae.png)
https://github.com/alibaba/nacos/issues/2884#issuecomment-633573589
都是配置过的哦

**Comment by chuntaojun** [comment]
你说的配置还是旧的，是说控制台显示吗？还是说你调用open-api

**Comment by MsencSir** [comment]
![image](https://user-images.githubusercontent.com/46589466/82817846-4bc7e880-9ed0-11ea-9684-e3e4b2aeefa7.png)

没有调用open-api；直接再每个节点的cluster.conf配置的；每个节点都配置上图所示；
https://github.com/alibaba/nacos/issues/2884#issuecomment-633576711

**Comment by chuntaojun** [comment]
控制台数据是直接读取数据库的，确保一下你是读取同一个数据库连接

**Comment by MsencSir** [comment]
不是连接同一个数据库的；可能是这个问题！一语惊醒梦中人呐，我去验证下；
第2，3问题，大佬能解答下吗？
https://github.com/alibaba/nacos/issues/2884#issuecomment-633579470

**Comment by chuntaojun** [comment]
节点下线必须配合cluster.conf文件一起修改才可以；

**Comment by chuntaojun** [comment]
nacos客户端内部有缓存，避免由于服务端crash导致消费者无法请求到服务者

**Comment by MsencSir** [comment]
https://github.com/alibaba/nacos/issues/2884#issuecomment-633583479
https://github.com/alibaba/nacos/issues/2884#issuecomment-633583697
明白了。谢谢大佬的指点。
