### ISSUE TITLE
spring-cloud-alibaba发生的问题，不过可能还得nacos项目组协助解决

### ISSUE THREAD

**Issue by zlyhabib** [alibaba/nacos#2885]
<groupId>com.alibaba.cloud</groupId>
<artifactId>spring-cloud-alibaba-dependencies</artifactId>
<version>2.2.1.RELEASE</version>

nacos版本1.2.1

com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(281):
String result = serverProxy.queryList(serviceName, clusters, pushReceiver.getUDPPort(), false);
具体请求nacos api：/nacos/v1/ns/instance/list
返回json属性中不含有：groupName

导致com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(284):
processServiceJSON(result)->ServiceInfo serviceInfo = JSON.parseObject(json, ServiceInfo.class);

这个serviceInfo对象groupName属性永久为null处理后续逻辑~
spring-cloud-alibaba也可以字符串临时处理，不过组名含有特殊符号@会出问题

发生问题比如：
RibbonRule设置为NacosRule，如果自定义group，这个策略永远检测失败

**Comment by chuntaojun** [comment]
groupName已经在serviceName带上了，可以看看属性

**Comment by zlyhabib** [comment]
> groupName已经在serviceName带上了，可以看看属性

根据答复不知道我的理解是否正确，你的意思就是serviceName里的值带上group@@name这种格式字符串返回值，然后希望com.alibaba.cloud项目组client端根据@@作解析拆分出来，可是我上面说了呀，服务在起或者ui方面并没有禁止字符@，假设name=@name@,group=@group@，最终serviceName=@name@@@@group@，这个字符串解析可能出来多种结果

**Comment by chuntaojun** [comment]
这个校验的问题可以提一个pr修复下

**Comment by zlyhabib** [comment]
> 这个校验的问题可以提一个pr修复下

我写了下期望，不过也可以按照校验问题来处理，这样配置和ui都请保持对@统一作特殊处理

**Comment by chuntaojun** [comment]
服务名称是有做校验的，应该是group没有解析出来回带回去对象上

**Comment by zlyhabib** [comment]
> 服务名称是有做校验的，应该是group没有解析出来回带回去对象上
好像没有校验到啊，我这出来这种现象

spring:
  cloud:
    nacos:
      discovery:
        server-addr:  127.0.0.1:8848
        group: test@@@@ (这里请随意添加@或者修改名称)
        namespace: dev
        username: nacos
        password: [nacos]

![nacostest](https://user-images.githubusercontent.com/9606584/82882612-e594a180-9f73-11ea-9754-93400a3d6755.png)

**Comment by zlyhabib** [comment]
> 服务名称是有做校验的，应该是group没有解析出来回带回去对象上

client确实也没有解析，就算解析了，后面还有个小问题~

**Comment by zlyhabib** [comment]
目前开发branch fix实现是过滤@字符串。
不过我在想servicename是不是可以设计成json格式？这样解析就不用考虑特殊字符，而且可以无限扩展新的业务类型
