### ISSUE TITLE
表达式是什么？

### ISSUE THREAD

**Issue by tsregll** [alibaba/nacos#2887]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
 nacos dashboard中更新服务功能中有个类型为标签的服务路由类型，下面有个表达式的文本框，这个表达式如何填写有规范么？文档没找到啊

### Describe what you expected to happen
希望有详细的文档描述

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/blog/cmdb.html
