### ISSUE TITLE
The layout of the published configuration is not adaptive

### ISSUE THREAD

**Issue by hxy1991** [alibaba/nacos#289]
![image](https://user-images.githubusercontent.com/2517258/48562334-f307af00-e92c-11e8-9f71-e2b8f091715e.png)

**Comment by fengxiutianya** [comment]
@i  will solve it@
我想试试修改这个，不过现在还没有具体看nacos的前端代码，所以不知道能不能申请

**Comment by zhaoyuguang** [comment]
![image](https://user-images.githubusercontent.com/10150229/62342218-ac88cd80-b518-11e9-9d3a-6165c1e1d4b2.png)
Now it look better, this issue can close @hxy1991 @nkorange

**Comment by ljhrot** [comment]
@KomachiSion Can you close this issue?

**Comment by wuchubuzai2018** [comment]
请问这个合并到主线了吗
