### ISSUE TITLE
Will there be non-blocking and reactive support in the future?

### ISSUE THREAD

**Issue by staticLin** [alibaba/nacos#2894]
In the WebFlux environment, the number of threads is relatively small and fixed, and blocking will affect throughput more. 
Nacos use REST API obtains the ServiceInstance via HttpClient. The HttpClient is a blocking API. If nacos need to support Reactive and non-blocking, you may need to change block HttpClient to Reactor-HttpClient in the `com.alibaba.nacos.client.naming.net.NamingProxy` class , which makes Nacos Reactive and non-blocking. I am more interested in this feature, if I can, I can participate in the development work.

**Comment by chuntaojun** [comment]
I am very happy to hear this suggestion, but in the planning of nacos, we will gradually use grpc instead of rest. Therefore, we will not do further optimization for the http total, preparing to transfer the overall communication channel to grpc

**Comment by staticLin** [comment]
> I am very happy to hear this suggestion, but in the planning of nacos, we will gradually use grpc instead of rest. Therefore, we will not do further optimization for the http total, preparing to transfer the overall communication channel to grpc

thx for reply.
may i ask there will be support non-bloking/reactive grpc?

**Comment by KomachiSion** [comment]
Nacos 2.0 has supported
