### ISSUE TITLE
Nacos有集成Quarkus的打算吗

### ISSUE THREAD

**Issue by Fish-Potato** [alibaba/nacos#2895]
## Issue Description

feature request

### Describe what happened (or what feature you want)
Nacos有考虑集成到Quarkus吗？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
应该短期内没有打算，如果集成到Quarkus，是否需要有很大的改动，优势和收益是否足够大都需要讨论

**Comment by KomachiSion** [comment]
No response more than 7 days, close issue
