### ISSUE TITLE
关于服务自动注册手动上线灰度发布的功能设想

### ISSUE THREAD

**Issue by coder-dao** [alibaba/nacos#2899]
默认情况下，服务启动之后，将会自动注册到 nacos 的服务列表中，而后可以被其他服务发现。

我们想要一个功能效果：服务启动之后，自动注册到 nacos，状态为“下线”，此时不会被其他服务发现。在控制台手动点击“上线”按钮，才会启动服务发现，模拟灰度发布的效果。

手动上线，可以帮助我们在发布新版本服务时，比较优雅的实现：人工验证并确认新版本服务没问题，再手动启动服务发现，正式将服务上线。

截止到 1.2.1 版本，配置中心已经有了 beta 发布（灰度发布）的功能。
服务注册发现，是否也可以有比较优雅简便的手动上线或者灰度发布的功能？？

谢谢！

**Comment by kdyzm** [comment]
这个功能有计划搞吗

**Comment by horizonzy** [comment]
这个功能现在的nacos已经是支持的了。在客户端注册实例的时候，设置`enabled=false`即可

**Comment by dandanheng** [comment]
> 这个功能现在的nacos已经是支持的了。在客户端注册实例的时候，设置`enabled=false`即可

没有找到文档,方便发下吗

**Comment by horizonzy** [comment]
```
        Instance instance = new Instance();
        instance.setWeight(1.0);
        instance.setEphemeral(true);
        instance.setHealthy(true);
        //这个属性。
        instance.setEnabled(false);
        instance.setPort(8080);
        instance.setIp("7.7.7.7");
        Map<String, String> instanceMeta = new HashMap<>();
        instanceMeta.put("horizon", "zzz");
        instanceMeta.put("appName", "ttt");
        instanceMeta.put(PreservedMetadataKeys.INSTANCE_ID_GENERATOR, "snowflake");
        instance.setMetadata(instanceMeta);
        instance.setClusterName("xxx-cluster");
        namingService.registerInstance("mm", instance);
```

**Comment by dandanheng** [comment]
有提供配置文件吗,这岂不是需要重新编译打包

**Comment by horizonzy** [comment]
> 有提供配置文件吗,这岂不是需要重新编译打包

如果如果用原生SDK，使用的三方集成框架的话，可能需要改动第三方框架。

**Comment by dandanheng** [comment]
嗯,用的springcloud Alibaba, 还需要自己打包编译.除了这个还有别的解决方案吗

**Comment by horizonzy** [comment]
> 嗯,用的springcloud Alibaba, 还需要自己打包编译.除了这个还有别的解决方案吗

用java agent去动态改这个属性。

**Comment by wangkang-ARM** [comment]
spring.cloud.nacos.discovery.instanceEnabled=false
![302433AE-6E18-423D-84DB-3692802945C8](https://user-images.githubusercontent.com/64467312/147035102-4798d7ad-3570-48b7-b8b4-efc5676969a4.png)
