### ISSUE TITLE
What is the meaning of each log file? Do Nacos need so many log files?

### ISSUE THREAD

**Issue by hxy1991** [alibaba/nacos#290]
- nacos.log
- config-acl.log
- config-app.log
- config-client-request.log
- config-dump.log
- config-fatal.log
- config-memory.log
- config-notify.log
- config-pull-check.log
- config-pull.log
- config-sdk-request.log
- config-server.log
- config-trace.log
- naming-cache.log
- naming-debug.log
- naming-device.log
- naming-event.log
- naming-performance.log
- naming-push.log
- naming-raft.log
- naming-router.log
- naming-rt.log
- naming-server.log
- naming-tag.log
- naming-tenant.log

**Comment by pguo65535** [comment]
a very good comment, we should start a discuss. 

- what is the benefits by doing with this style
- what is the weakness  by doing with this style
- other options/way we can choose
- should we merge some of them to decrease the number of file
- is there one place/log file (such as ‘nacos.log’) should contain all of the log
- ...
