### ISSUE TITLE
nacos在CentOS Linux release 7.6.1810 jdk11.3环境下启动报错

### ISSUE THREAD

**Issue by Hotant-Bu** [alibaba/nacos#2901]
报错信息：
ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$b5014a56] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
解决方法：
换成nacos-server-1.2.0.tar.gz

**Comment by KomachiSion** [comment]
Update to newest version and retry.
If reproduce your problem, please provide full error log.

**Comment by Hotant-Bu** [comment]
This bug should be a dependency problem, there is a chance to test again.Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 SionYang"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 上午10:08
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "热热的蚂蚁"<907011673@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] nacos在CentOS Linux release 7.6.1810 jdk11.3环境下启动报错 (#2901)





 
Update to newest version and retry.
 If reproduce your problem, please provide full error log.

**Comment by KomachiSion** [comment]
In our CI environment, we use two kinds of 11jdk to do test, but is ok. So can you do some debug and find out which beans caused this problem?

**Comment by KomachiSion** [comment]
No response more than 7 days.
