### ISSUE TITLE
nacos新建配置  （nacos new configuration）

### ISSUE THREAD

**Issue by MuJianxuan** [alibaba/nacos#2906]
在使用中文输入法的时候会重复输入一个数字，比如配置端口号，如果是中文时，按1会得到11，按2会得到22.而切换成英文时却不会发生，这是为什么。

When using the Chinese input method, you will repeatedly enter a number, such as the configuration port number. If it is Chinese, press 1 to get 11, and press 2 to get 22. However, it will not happen when switching to English. This is why.

**Comment by KomachiSion** [comment]
I can't reproduce your problem, may be it's your environment or your inputs toggle twice events.

**Comment by MuJianxuan** [comment]
> 
> 
> I can't reproduce your problem, may be it's your environment or your inputs toggle twice events.
> If you change environment also can reproduce problem, please tell us what's OS and inputs.
