### ISSUE TITLE
nacos同时使用discovery和config的时候discovery的地址会被截掉最后一位字符

### ISSUE THREAD

**Issue by sslcbhyso** [alibaba/nacos#2907]
1. When nacos uses discovery and config at the same time, discovery's address is replaced and missing one, for example, if the situation is error: cloud.nacos.discovery.server-addr=http://127.0.0.1:8001; cloud.nacos.config.server-addr=http://127.0.0.1:8001
Error at startup:
DEBUG com.alibaba.nacos.client.naming [NamingProxy.java : 327] [BEAT] public sending beat to server: {"cluster":"DEFAULT","ip":"172.16.0.4","metadata":{"preserved.register.sxxxxxxxxx
WARN  com.alibaba.nacos.client.naming [HttpClient.java : 94] failed to request http://**127.0.0.1:800**/nacos/v1/ns/instancexxxxxx
ERROR com.alibaba.nacos.client.naming [HttpClient.java : 102] [NA] failed to request
Here you see that the port is one character less changed to：**127.0.0.1:800**；images:
![1](https://user-images.githubusercontent.com/24666988/83087983-24863c80-a0c5-11ea-9e25-5d4580a79457.png)

![2](https://user-images.githubusercontent.com/24666988/83087999-2bad4a80-a0c5-11ea-9f3c-2587dfed04af.png)

3. The function of using discover or config alone is normal or only IP:port is normal but add http://, both of which will appear to be the above problem

2. Later in the cloud.nacos.discovery.server-addr=http://127.0.0.1:8001 the number is changed to：cloud.nacos.discovery.server-addr=**http://127.0.0.1:80011**other configurations remain unchanged; the start is OK。images:
![3](https://user-images.githubusercontent.com/24666988/83088012-31a32b80-a0c5-11ea-8b49-b3fc15234d44.png)

Version：
1. spring-cloud-dependencies：Hoxton.SR4
2. spring-boot-dependencies ： 2.3.0.RELEASE
3. spring-cloud-alibaba-dependencies： 2.2.1.RELEASE
4. spring-cloud-starter-alibaba-nacos-discovery：0.9.0.RELEASE
5. nacos-client : 1.2.1
6. spring-cloud-starter-alibaba-nacos-config : 2.2.1.RELEASE
------------------------------------------------------------------------------------------------------

1. nacos同时使用discovery和config的时候discovery的地址会被替换并缺少一位，例如一下情况会出现错误：cloud.nacos.discovery.server-addr=http://127.0.0.1:8001 ; cloud.nacos.config.server-addr=http://127.0.0.1:8001
启动的时候报错：
WARN  com.alibaba.nacos.client.naming [HttpClient.java : 94] failed to request http://**127.0.0.1:800**/nacos/v1/ns/instancexxxxxx
ERROR com.alibaba.nacos.client.naming [HttpClient.java : 102] [NA] failed to request
这里看到端口少了一个字符变成：**127.0.0.1:800**；如图：
![1](https://user-images.githubusercontent.com/24666988/83088056-4e3f6380-a0c5-11ea-8692-58cff5522fe9.png)
![2](https://user-images.githubusercontent.com/24666988/83088058-50092700-a0c5-11ea-9e51-eb5443181b71.png)

3. 单独使用discover或者config的功能是正常的或者只填IP:port也是正常的但加上http://，两者同时使用就会出现上面的问题 

2. 后来在cloud.nacos.discovery.server-addr=http://127.0.0.1:8001后面随便加个数字变成：cloud.nacos.discovery.server-addr=http://127.0.0.1:80011这样子其他配置不变；启动就正常了。
配置如图：
![3](https://user-images.githubusercontent.com/24666988/83088071-54cddb00-a0c5-11ea-8ab1-0e291baebfaf.png)

版本号情况：
1. spring-cloud-dependencies：Hoxton.SR4
2. spring-boot-dependencies ： 2.3.0.RELEASE
3. spring-cloud-alibaba-dependencies： 2.2.1.RELEASE
4. spring-cloud-starter-alibaba-nacos-discovery：0.9.0.RELEASE
5. nacos-client : 1.2.1
6. spring-cloud-starter-alibaba-nacos-config : 2.2.1.RELEASE

**Comment by ITnufun** [comment]
serverAddr = Objects.toString(serverAddr, "");
if (serverAddr.lastIndexOf("/") != -1) {
	serverAddr = serverAddr.substring(0, serverAddr.length() - 1);
}
这是spring-cloud-alibaba-nacos-discovery 0.9.0.RELEASE版本获取属性的代码
程序员原本的意思应该是是判断最后一位是否是/
但是现在变成了是否包含/，如果包含就去掉最后一位，
所以你有两种方法使用 
1.如果属性中必须包含/的话  需要在最后随意加一个字符
2.不使用http://前缀
