### ISSUE TITLE
环境隔离配置的namespace只能在bootstrap中配置？

### ISSUE THREAD

**Issue by yangshuangpeng** [alibaba/nacos#2909]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 假设有dev,sit,uat,prod环境，namespace每次都需要手动在bootstrap中指定？还是采用application-dev.properties，application-prod.properties中指定？还是采用bootstrap-dev.properties配置方式？

### Tell us your environment

nacos1.2.1

**Comment by chuntaojun** [comment]
如果你是使用cloud，使用bootstrap-dev.properties

**Comment by yangshuangpeng** [comment]
有没有社区群了，可否能参与社区贡献了 @
