### ISSUE TITLE
getServicesOfServer方法如何使用条件过滤？

### ISSUE THREAD

**Issue by yinjunonly** [alibaba/nacos#2911]
namingService.getServicesOfServer(pageNo, pageSize, selector)

selector 我尝试了各种表达式，还是未起到过滤的作用，请问要怎样才能实现按名称模糊查找或者说只查生产者呢？

**Comment by yfh0918** [comment]
请参考源码 ServiceController的list方法中关于selector的处理

**Comment by yinjunonly** [comment]
> 请参考源码 ServiceController的list方法中关于selector的处理

没找到这个controller啊

**Comment by yfh0918** [comment]
下载服务端的代码，nacos-naming包的com.alibaba.nacos.naming.controllers.ServiceController

**Comment by chuntaojun** [comment]
selector需要配合CMDB进行使用

**Comment by chuntaojun** [comment]
// INSTANCE.metadata.xxx = 'yyy' or
// SERVICE.metadata.xxx = 'yyy'

**Comment by yinjunonly** [comment]
> // INSTANCE.metadata.xxx = 'yyy' or
> // SERVICE.metadata.xxx = 'yyy'

谢谢，我试试看

**Comment by yinjunonly** [comment]
> // INSTANCE.metadata.xxx = 'yyy' or
> // SERVICE.metadata.xxx = 'yyy'

他是有效的
