### ISSUE TITLE
cannot close nacos auth in  version 1.2.1

### ISSUE THREAD

**Issue by fedocx** [alibaba/nacos#2913]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
I update my nacos from 1.2.0 to 1.2.1,I found it require username and password when I access my nacos.but I didn't enable auth.

### Describe what you expected to happen
don't enable auth

### How to reproduce it (as minimally and precisely as possible)

1. deploy nacos 1.2.0 
2. edit yaml file ,change image from 1.2.0 to 1.2.1
3. login to nacos ,you can find it ask for auth.

### Tell us your environment
in the kubernetes ,deployed with statefulset and 3 replicas

### Anything else we need to know?
I tried edit application.properties and add env NACOS_AUTH_ENABLE ,in v1.2.1,it didn't work.

**Comment by fedocx** [comment]
Did you solved it?maby I think I  should rollback to v1.2.0


> 
> 
> I have the same problem！
> nacos version=1.2.1
> “ nacos.core.auth.enabled=false ” is not work!

**Comment by KomachiSion** [comment]
Refer to #2935
