### ISSUE TITLE
nacos1.2.1版本，创建properties类型的配置报错

### ISSUE THREAD

**Issue by taoxiaoyin** [alibaba/nacos#2915]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
nacos1.2.1版本，创建properties类型的配置报错，错误如下
<img width="916" alt="WX20200528-201037@2x" src="https://user-images.githubusercontent.com/3125643/83139780-7956a100-a11f-11ea-9f35-0c403395cb38.png">

2. 
3. 

### Tell us your environment
<img width="916" alt="WX20200528-201037@2x" src="https://user-images.githubusercontent.com/3125643/83139809-84113600-a11f-11ea-9e9b-177c6955e3e3.png">

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2908

**Comment by BodhiFlower** [comment]
I have the same problem. Is there a solution?
The same error occurs with Yaml type files.

**Comment by BodhiFlower** [comment]
Try changing the database version.
I tried mysql 8.0/5.7 error, then I reduced the database version to 5.6 and added normal configuration.

**Comment by KomachiSion** [comment]
duplicate

**Comment by taoxiaoyin** [comment]
这个bug能修复吗？1.3貌似还是不能加properties的，mysql是5.7的
