### ISSUE TITLE
获取认证服务器配置

### ISSUE THREAD

**Issue by sunshixiong789** [alibaba/nacos#2919]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我想获取认证服务器的配置 但是认证服务器是集群我应该怎么获取

### Describe what you expected to happen

![image](https://user-images.githubusercontent.com/31101988/83220726-663ae400-a1a6-11ea-9fb4-0e00016f0e99.png)

我试了一下 ，这个方式不行。  能给个方案吗

**Comment by chuntaojun** [comment]
Are you saying that the configuration is unreadable on nacos

**Comment by KomachiSion** [comment]
I think it's not problem of nacos.
