### ISSUE TITLE
github下载太慢了。能不能搞个国内下载的地址

### ISSUE THREAD

**Issue by ChadDongDongChen** [alibaba/nacos#2920]
github下载太慢了。能不能搞个国内下载的地址

**Comment by EasonFeng5870** [comment]
Hi, I checked gitee, found there is a [Nacos gitee url](https://gitee.com/mirrors/Nacos) for nacos, but only update codes daily.

Hope it can help.

**Comment by ChadDongDongChen** [comment]
good boy, thanks
