### ISSUE TITLE
日志打印

### ISSUE THREAD

**Issue by liwei08485** [alibaba/nacos#2922]
还是写中文吧，中文都国际化了。是担心乱码吗？

NACOS能否在页面增加一个日志打印的控制，可以控制打印什么日志以及日志的级别。

nacos的日志打的有点凶，每次到服务器去清理日志，比较繁琐。目前是crontab定时清理下。

**Comment by KomachiSion** [comment]
日志打印目前通过logback打印，暂时无法做到运行中切换日志输出级别。
目前如果需要减少日志打印，或者调整日志打印级别，应该只能修改集群上logback的配置文件。

**Comment by KomachiSion** [comment]
No repsonce more than days, I will close this issue.
