### ISSUE TITLE
Nacos集群 + Dubbo下provider 同时注册该集群下多个namespace

### ISSUE THREAD

**Issue by RongXiong2016** [alibaba/nacos#2928]
## Issue Description
Nacos集群 + Dubbo下provider 无法同时注册该集群下多个namespace

### Describe what happened (or what feature you want)
希望能实现 dubbo一个provider 同时注册到该集群下的多个namespace
### How to reproduce it (as minimally and precisely as possible)

1.
yml文件如下
nacos.namespace1=my-nacos?namespace=aceef1fd-6815-4938-b5fd-0cd75d934942
nacos.namespace2=my-nacos?namespace=0743f7ec-72ae-4f66-9a15-0435fa147dea
dubbo.registry.address=nacos://${nacos.namespace1}backup=${nacos.namespace2}

项目启动报错
 Invalid namespace="aceef1fd-6815-4938-b5fd-0cd75d934942?backup=my-nacos?namespace=0743f7ec-72ae-4f66-9a15-0435fa147dea" contains illegal character, only digit, letter, '-', '_' or '.' is legal.
Type: *bug report* 
2. 
3. 

### Tell us your environment
Mac os
jdk1.8
 Nacos1.1.4 集群
dubbo 2.7.6
spring boot 2.0.8

### Anything else we need to know?

**Comment by KomachiSion** [comment]
这个是否应该找dubbo实现？

**Comment by chuntaojun** [comment]
转交至dubbo
