### ISSUE TITLE
fastjson version(<=1.68) security hole

### ISSUE THREAD

**Issue by untin** [alibaba/nacos#2929]
## Issue Description

bug report

### Describe what happened (or what feature you want)
nacos use fastjson 1.58 ，and the fastjson version(<=1.68) then has serious security hole，does the fastjson security hole will affect the nacos？

**Comment by dengliming** [comment]
好像已经有人提交jackson替换fastjson的pr了, 等待全部替换删掉pom依赖就好了.

**Comment by KomachiSion** [comment]
fastjson has remove except `nacos-test`, and `nacos-test` is just a test module, will not release for users. 

detail see #2842 .
