### ISSUE TITLE
Nacos1.2.1 + dubbo 2.7.7 create too many thread

### ISSUE THREAD

**Issue by lijiaxing3045354** [alibaba/nacos#2931]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
During the project upgrade, we want to switch from zookeeper to Nacos registry. During debugging, we found that the startup speed is several times that of ZK, and the more services, the slower the startup. After further review, we found that each dubbo:service , 11 threads have been created, I have 158 services, and the number of Nacos related threads has reached 1738. The startup time has also changed from more than ten seconds using ZK to more than 200 seconds.
![image](https://user-images.githubusercontent.com/39329138/83372011-ab555500-a3f6-11ea-841a-9966accec13b.png)

### Describe what you expected to happen
It is hoped that the number of threads to be created will not be too many, the startup speed will be faster, and the Nacos project will be better and bette.

**Comment by chuntaojun** [comment]
nacos internal will not create a large number of threads, all threads are bounded, we will confirm with dubbo how they use, do you have your own operation NamingService?

**Comment by jzdayz** [comment]
Maybe you should see how many NacosNamingService objects there are.

**Comment by lijiaxing3045354** [comment]
I haven't operated NamingService。

Inspired by jzdayz, I took a look at Dubbo and Nacos objects. It is found that Dubbo has created 158 NacosRegistry objects, NacosRegistry references NacosNamingService, and NacosNamingService will create 11 threads.

The source of the problem is Dubbo. But if NacosNamingService is a singleton, this problem can be avoided in most cases.
![image](https://user-images.githubusercontent.com/39329138/83586992-7a089080-a580-11ea-849b-4b96da7b4687.png)
![image](https://user-images.githubusercontent.com/39329138/83587003-842a8f00-a580-11ea-8e6f-b9b7168c83ad.png)

**Comment by chuntaojun** [comment]
Singleton issues and resource recovery issues are being addressed. But in my opinion, when using a component, it is more important to understand how to use it to avoid problems
