### ISSUE TITLE
nacos.core.auth.enabled=false , 1.2.1 & 1.3.0Beta , is not work!

### ISSUE THREAD

**Issue by DerekHQ** [alibaba/nacos#2935]
## Issue Description
 *bug report* 

### Describe what happened (or what feature you want)
`nacos.core.auth.enabled=false`

It's not work!  

Access "http://127.0.0.1:8848/nacos"   HTTP 302
RedirectTo: "http://127.0.0.1:8848/nacos/#/login"  Route Page

### How to reproduce it (as minimally and precisely as possible)
1.  Change "nacos.core.auth.enabled=false" in application.properties

### Tell us your environment
nacos version: 1.2.1 & 1.3.0Beta   is not work!
nacos version: 1.2.0 is ok!

**Comment by chuntaojun** [comment]
You mean 1.2.1 and 1.3.0, you can go to the login page without opening the permission?

**Comment by jzdayz** [comment]
🤔 what's this?what are you mean?  @DerekHQ

**Comment by KomachiSion** [comment]
@deepsola , parameter `nacos.core.auth.enabled` means that openAPI do not check user auth, the console also need to login.

Sorry for the trouble.

**Comment by DerekHQ** [comment]
> You mean 1.2.1 and 1.3.0, you can go to the login page without opening the permission?

Yes, console page need to login aways!

**Comment by DerekHQ** [comment]
> @DerekHQ , parameter `nacos.core.auth.enabled` means that openAPI do not check user auth, the console also need to login.
> 
> Sorry for the trouble.

OK, but I want to access console without login page, How can I do?  
Nacos:v1.2.0;  It can without login page!
Thank you!

**Comment by DerekHQ** [comment]
> @DerekHQ , parameter `nacos.core.auth.enabled` means that openAPI do not check user auth, the console also need to login.
> 
> Sorry for the trouble.

I can modify code  backend or frontend, then recompile source ! 
Can you tell me, what code do I need to modify! Thank you for you help!

**Comment by KomachiSion** [comment]
> > @DerekHQ , parameter `nacos.core.auth.enabled` means that openAPI do not check user auth, the console also need to login.
> > Sorry for the trouble.
> 
> I can modify code backend or frontend, then recompile source !
> Can you tell me, what code do I need to modify! Thank you for you help!


There are many codes need to be modified, if you want to totally remove login.
For security, I recommend that you use default admin user `nacos` login to console and change password.

**Comment by Z8gO** [comment]
@KomachiSion 麻烦问一下，我在1.1.4版本确实只要配置nacos.core.auth.enabled=false 就可以不用登陆直接跳转到控制台了，1.2.1+ 以后都不行了，这个除了改代码外没有其他的办法了吗？ 配置上面不支持了吗

**Comment by quan8888** [comment]
> 

" There are many codes need to be modified, if you want to totally remove login.
For security, I recommend that you use default admin user nacos login to console and change password."
您好，麻烦问一下，目前2.1.1版本，还是这个现状吗? 还是不能关闭登录页面吗？
看到文档里的如下几个参数配置一下，是无效的
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**
