### ISSUE TITLE
Unable to connect to remote nacos server

### ISSUE THREAD

**Issue by JopenChen** [alibaba/nacos#2936]
## Issue Description
In the springboot project, the nacos server address deployed in the virtual machine is configured, that is, the remote nacos server. However, when running the project, there will be an error in the connection to http://localhost:8848.I configured the remote nacos server, which shows the local IP: port, and it shows the connection timeout, which cannot be used.(ps: Nacos server can normally access the service in the browser.)

## The Error log info
    2020-06-01 11:09:59.151 ERROR [backgroup,,,] 28840 --- [-localhost_8848] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused: connect

## Enviroment
    springboot 2.2.7 + nacos 1.3.0-BETA

I would like to know how to use nacos server deployed on a remote server in a project.Thanks!

**Comment by chuntaojun** [comment]
"Connection refused"

Make sure you have access to, not nacos issues, virtual machine network Settings and so on

**Comment by EasonFeng5870** [comment]
maybe try ip:8848

**Comment by KomachiSion** [comment]
No response more than 7 days.
