### ISSUE TITLE
Does nacos 1.1.4 support ipv6？

### ISSUE THREAD

**Issue by weiliang-ms** [alibaba/nacos#2937]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)

nacos version: 1.1.4

I can access the nacos console through ipv6，but the curl test returns 400.

![image](https://user-images.githubusercontent.com/18642754/83475654-59c5cc80-a4c1-11ea-8dc6-b5a0861af9dd.png)

![image](https://user-images.githubusercontent.com/18642754/83476221-b2499980-a4c2-11ea-92de-b269880c9e4f.png)

The nacos client does not recognize ipv6 addresses.

This is my configuration：

`spring.cloud.nacos.server-addr=fe80::16cc:c977:f6f9:431e%ens33:8848`

error log:

`java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([fe80::16cc:c977:f6f9:431e%ens33:8848]) tried: failed to req API:fe80::16cc:c977:f6f9:431e%ens33:8848/nacos/v1/ns/service/list. code:500 msg: java.net.MalformedURLException: For input string: ":16cc:c977:f6f9:431e%ens33:8848"`

### Describe what you expected to happen

Nacos supports ipv6 service registration discovery.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
CentOS7 
nacos1.1.4
openjdk1.8

**Comment by KomachiSion** [comment]
currently, Only support ipv4.

**Comment by ShuaiShuaiDa8888** [comment]
我现在也在关注这个问题，但是我现在对概念有点混淆。您说的nacos控制台是不是指的第一张图的页面，但是nacos客户端指的是什么呢？

**Comment by weiliang-ms** [comment]
抱歉我表述的可能有问题.
我所说的nacos控制台就是web访问地址，http://xxx.xxx.xxx.xxx:8848/nacos;
nacos客户端指的是集成nacos的后端服务。



 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weishuai"<notifications@github.com&gt;; 
发送时间: 2020年6月17日(星期三) 下午2:04
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "黑武士"<1067599390@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] Does nacos 1.1.4 support ipv6？ (#2937)





 
我现在也在关注这个问题，但是我现在对概念有点混淆。您说的nacos控制台是不是指的第一张图的页面，但是nacos客户端指的是什么呢？

**Comment by ShuaiShuaiDa8888** [comment]
客户端我可以理解为注册到nacos中的服务吗？
目前我了解到的信息是使用PUT注册服务的时候，重新建立一个合法的ipv6地址，得到400的响应。
在GET时又能够获取到这个实例。这就代表注册服务时，不允许使用IPv6，但是发现服务时可以发现用ipv6注册的服务。不知道我获取到的信息是否正确。您这边目前得到的结论是什么？nacos支持ipv6对服务进行注册和发现吗？我的信息是在下面的问题中获取到的：https://github.com/alibaba/nacos/issues/978

**Comment by weiliang-ms** [comment]
我这面没有做细致的测试，仅仅是把现有的服务放到IPv6环境中运行，我看官方给出的回应是暂时不支持IPv6,您那边有全链路IPv6的场景么？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weishuai"<notifications@github.com&gt;; 
发送时间: 2020年6月17日(星期三) 下午2:27
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "黑武士"<1067599390@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] Does nacos 1.1.4 support ipv6？ (#2937)





 
客户端我可以理解为注册到nacos中的服务吗？
 目前我了解到的信息是使用PUT注册服务的时候，重新建立一个合法的ipv6地址，得到400的响应。
 在GET时又能够获取到这个实例。这就代表注册服务时，不允许使用IPv6，但是发现服务时可以发现用ipv6注册的服务。不知道我获取到的信息是否正确。您这边目前得到的结论是什么？nacos支持ipv6对服务进行注册和发现吗？我的信息是在下面的问题中获取到的：#978

**Comment by ShuaiShuaiDa8888** [comment]
我这边也没有全链路的ipv6场景，也是想把Ipv4升级到ipv6，正在评估方案的可行性。您是直接把spring.cloud.nacos.server-addr的value值改成了ipv6了吗？您在哪里看到了官方给出的回复说不支持ipv6？

**Comment by weiliang-ms** [comment]
是啊spring.cloud.nacos.server-addr配置为ipv6地址，我们这边也测试了下nginx proxy_pass ipv6也是解析错误。


官方回复的是：currently, Only support ipv4.
https://github.com/alibaba/nacos/issues/2937#issuecomment-642355957



 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weishuai"<notifications@github.com&gt;; 
发送时间: 2020年6月17日(星期三) 下午2:38
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "黑武士"<1067599390@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] Does nacos 1.1.4 support ipv6？ (#2937)





 
我这边也没有全链路的ipv6场景，也是想把Ipv4升级到ipv6，正在评估方案的可行性。您是直接把spring.cloud.nacos.server-addr的value值改成了ipv6了吗？您在哪里看到了官方给出的回复说不支持ipv6？

**Comment by ShuaiShuaiDa8888** [comment]
这个确定是否支持ipv6还要看官方文档上是否注明    您现在是不是配置ipv6后nacos控制台可以访问，但是配置的nacos服务不支持？
