### ISSUE TITLE
nacos_config索引设置过长导致主从失效

### ISSUE THREAD

**Issue by zhuyouzhufu** [alibaba/nacos#2942]
Error 'Specified key was too long; max key length is 1000 bytes' on query. Default database: 'nacos-config'. Query: 'CREATE TABLE permissions

![image](https://user-images.githubusercontent.com/34908518/83541794-b4e0d900-a52c-11ea-8799-4050f22b1c45.png)
![image](https://user-images.githubusercontent.com/34908518/83541821-ba3e2380-a52c-11ea-9dc9-c46d8fcf846e.png)

**Comment by chuntaojun** [comment]
MySQL版本多少

**Comment by zhuyouzhufu** [comment]
mysql5.7.25

**Comment by zhuyouzhufu** [comment]
> MySQL版本多少
mysql5.7.25

**Comment by chuntaojun** [comment]
My mysql won't have this problem, version is 5.7.29，

**Comment by zhuyouzhufu** [comment]
> 我的mysql没有这个问题，版本是5.7.29，

数据库字符集utf8mb4

**Comment by zhuyouzhufu** [comment]
这个字段一定要设置的这么大，一定要放到组合的唯一索引中吗？又没有可能把这个字段调小一点或者将这个长字段剔除索引中

**Comment by zhuyouzhufu** [comment]
我现在的处理方法就是把这个字段调小了200，你们的长度是512，我调成了312.然后就正常了

**Comment by chuntaojun** [comment]
你的字符集引起的问题：https://stackoverflow.com/questions/11847815/error-specified-key-was-too-long-max-key-length-is-1000-bytes

**Comment by chuntaojun** [comment]
It is suggested that the permission table be changed to the LATin1 character set encoding

**Comment by zhuyouzhufu** [comment]
好的，谢谢大佬的建议
