### ISSUE TITLE
Nacos1.2.1, 3 cluster deployments, there is always one unable to access the management desk

### ISSUE THREAD

**Issue by ccDuan** [alibaba/nacos#2943]
nacos1.2.1  ， 3台集群部署，总是有一台无法访问管理台
Nacos1.2.1, 3 cluster deployments, there is always one unable to access the management desk

**Comment by ccDuan** [comment]
是哪里部署有问题吗

**Comment by chuntaojun** [comment]
有没有清空过浏览器缓存，不能访问有没有具体的错误信息

**Comment by ccDuan** [comment]
清空了一次日志看了一下，日志文件中没有error级别的日志，我是通过修改启动脚本指定不同端口的方式部署的；端口号在中间的那台不能访问，但是在其它的管理台可以看到是正常的

**Comment by chuntaojun** [comment]
访问有没有显示什么错误信息？还是根本就刷新不了网页出来

**Comment by ccDuan** [comment]
无法访问此网站网址为 http:// *****/nacos/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_UNSAFE_PORT

**Comment by chuntaojun** [comment]
那这个非nacos问题了，可以查下这个问题，应该是和浏览器的安全策略什么的有关

**Comment by KomachiSion** [comment]
No response more than 7 days
