### ISSUE TITLE
nacos集群环境下，作为配置中心的情况下，新建一个配置，会同步到集群内的其他nacos节点中吗

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#2944]
nacos集群环境下，作为配置中心的情况下，新建一个配置，会同步到集群内的其他nacos节点中吗
如果会同步的话，那么同步的机制以及原理又是怎样的呢？
是否有文档和链接地址说明

**Comment by pengyonglei** [comment]
如果你用的是外部数据库的话, 那你的配置应该就会写到数据库里面, 其他集群的节点也都是从数据库里面查询配置的, 这样应该就是同步了吧

**Comment by HelloHaiNG** [comment]
> 如果你用的是外部数据库的话, 那你的配置应该就会写到数据库里面, 其他集群的节点也都是从数据库里面查询配置的, 这样应该就是同步了吧

但是我不同节点配置的数据库是不同的情况下呢；配置在数据库中会同步吗

**Comment by chuntaojun** [comment]
> > 如果你用的是外部数据库的话, 那你的配置应该就会写到数据库里面, 其他集群的节点也都是从数据库里面查询配置的, 这样应该就是同步了吧
> 
> 但是我不同节点配置的数据库是不同的情况下呢；配置在数据库中会同步吗

一个集群只链接一个数据库集群，不是一个节点链接一个数据库的

**Comment by HelloHaiNG** [comment]
> > > 如果你用的是外部数据库的话, 那你的配置应该就会写到数据库里面, 其他集群的节点也都是从数据库里面查询配置的, 这样应该就是同步了吧
> > 
> > 
> > 但是我不同节点配置的数据库是不同的情况下呢；配置在数据库中会同步吗
> 
> 一个集群只链接一个数据库集群，不是一个节点链接一个数据库的

噢噢，没注意这点；那就没问题了
