### ISSUE TITLE
Naocs配置中心集群是否存在单点问题

### ISSUE THREAD

**Issue by hungryC** [alibaba/nacos#2946]
Naocs配置中心集群间配置采用水平通知方式，配置通过某一个configserver节点配置完成写到mysql，然后再异步通知其他cs节点取数据，如果在写到MySQL后，configserver节点挂了会怎么处理，会不会导致mysql里配置是最新的，client感知不到最新配置

**Comment by chuntaojun** [comment]
> Naocs配置中心集群间配置采用水平通知方式，配置通过某一个configserver节点配置完成写到mysql，然后再异步通知其他cs节点取数据，如果在写到MySQL后，configserver节点挂了会怎么处理，会不会导致mysql里配置是最新的，client感知不到最新配置

会有定时任务去从mysql进行一次dump操作

**Comment by hungryC** [comment]
> 
> 
> > Naocs配置中心集群间配置采用水平通知方式，配置通过某一个configserver节点配置完成写到mysql，然后再异步通知其他cs节点取数据，如果在写到MySQL后，configserver节点挂了会怎么处理，会不会导致mysql里配置是最新的，client感知不到最新配置
> 
> 会有定时任务去从mysql进行一次dump操作

定时任务的间隔是多久，我刚测试发现client感知不到最新配置，没有看到dump操作

**Comment by chuntaojun** [comment]
目前是六小时，如果出现节点crash，你可以调用这个接口 /nacos/v1/cs/ops/localCache 触发节点的全量dump操作

**Comment by KomachiSion** [comment]
No response more than 7 days.
