### ISSUE TITLE
"status":501,"error":"Not Implemented","message":"no such api:GET:/nacos/v1/ns/instances","path":"/nacos/v1/ns/instances"

### ISSUE THREAD

**Issue by joe1981** [alibaba/nacos#2948]
curl -X GET 'http://127.0.0.1:8848/nacos/v1/ns/instances?serviceName=nacos.naming.serviceName',  it show 501 status code, msg is "Not Implemented", who can help me, thanks!

**Comment by chuntaojun** [comment]
do you setting the servlet.context-path

**Comment by KomachiSion** [comment]
No response more than 7 days.
