### ISSUE TITLE
能否将com.alibaba.nacos.client.naming.ctimeout的配置放出来?

### ISSUE THREAD

**Issue by 1805214** [alibaba/nacos#2950]
![image](https://user-images.githubusercontent.com/22842710/83633391-76eac000-a5d3-11ea-9865-a410946f61c8.png)

麻烦大神考虑下网络不佳的情况

**Comment by chuntaojun** [comment]
设置JVM参数即可

**Comment by chuntaojun** [comment]
可以看下 Integer.getInteger的源码

**Comment by 1805214** [comment]
已解决.
