### ISSUE TITLE
nacos集群搭建完成，应用注册上来，日志报错，服务调用不了

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#2954]
版本：1.1.0
日志错误如下：
![企业微信截图_15912412324958](https://user-images.githubusercontent.com/33769220/83711656-64659a80-a656-11ea-8202-19baf8cce719.png)

**Comment by HelloHaiNG** [comment]
请问一下这里为什么会执行数据库的删除语句，而且data_id为什么是‘com.alibaba.nacos.testMasterDB’

**Comment by chuntaojun** [comment]
这是进行主从库自动判断的，不影响逻辑

**Comment by HelloHaiNG** [comment]
> 这是进行主从库自动判断的，不影响逻辑

但是我去调用nacos console接口查看服务列表会报服务端异常；说是nacos不可用；

**Comment by chuntaojun** [comment]
看下服务端的其他日志信息

**Comment by KomachiSion** [comment]
Refer to #1393

**Comment by KomachiSion** [comment]
No response more than **7 days**. close issue
