### ISSUE TITLE
配置中心发布和保存配置能否拆成两步

### ISSUE THREAD

**Issue by hungryC** [alibaba/nacos#2960]
现在使用nacos修改配置后只能点击发布或者灰度，有考虑在修改配置后新增个保存状态吗，配置可以保存但不发布，要不然在生产环境风险很大

**Comment by KomachiSion** [comment]
灰度发布确实是可以优化的功能，实现形式可以详细设计和讨论下，欢迎大佬贡献设计，想法和代码PR

**Comment by KomachiSion** [comment]
@hungryC 欢迎到前面的issue一起讨论 #2899
