### ISSUE TITLE
nacos作为配置中心，服务被下线

### ISSUE THREAD

**Issue by tdt008** [alibaba/nacos#2961]
测试环境由于机器有限，每个服务部署的实例不多。就经常出现一个问题： 个别服务进程是正常运行的，但是被nacos注册中心下线，导致服务被调用时抛异常。nacos作为服务注册中心的时候能不能查看每个服务上下线时间？如果客户端进程是正常的，就算被下线，也应该不停的与nacos server尝试通信。

**Comment by KomachiSion** [comment]
抱歉，麻烦修改一下标题和说明内容，我没有明白您的问题所在。

是说nacos注册中心心跳检测下线了的服务客户端，继续给nacos server发心跳，还是说手动下线的客户端 也继续发心跳？

**Comment by tdt008** [comment]
当服务A启动的时候，能正常的进行注册和服务发现；运行一段时间以后nacos就把服务A下线了，服务A的健康实例数就变为0了；此时其他服务rpc调用A服务就调用不了了，但是此时服务A的进程是正常的、正常运行。

**Comment by chuntaojun** [comment]
First, an instance of the service is taken offline, which is not listed in the return list. Logoff is a logical process closure

**Comment by KomachiSion** [comment]
> 当服务A启动的时候，能正常的进行注册和服务发现；运行一段时间以后nacos就把服务A下线了，服务A的健康实例数就变为0了；此时其他服务rpc调用A服务就调用不了了，但是此时服务A的进程是正常的、正常运行。

那需要看一下nacos的日志，看下是否是因为心跳检测认为服务A的实例已经不可达，然后移除了实例。

**Comment by KomachiSion** [comment]
No response more than 7days. Close issue
