### ISSUE TITLE
Nacos Naming元数据乱码

### ISSUE THREAD

**Issue by liji2003888** [alibaba/nacos#2962]
使用springboot集成nacos，bootstrap.yaml中增加metadata描述，配置如下：
![图片](https://user-images.githubusercontent.com/4416960/83755323-fcd43d00-a69f-11ea-94a1-b83ec73df5ca.png)

使用控制台看到注册的metadata，有时候为乱码。。。
正常时为：
![图片](https://user-images.githubusercontent.com/4416960/83755449-2f7e3580-a6a0-11ea-9ada-f17fa8bc9029.png)
刷新几次页面，出现乱码情况：
![图片](https://user-images.githubusercontent.com/4416960/83755477-3ad16100-a6a0-11ea-9958-12d7a847f376.png)

目前使用的nacos版本为1.2.1，client为spring cloud alibaba 2.2.0.RELEASE，运行环境在k8s docker下

**Comment by KomachiSion** [comment]
能否在浏览器的控制台看一下 是服务端返回的数据是乱码 还是前端展示乱码？

**Comment by sevillejewell** [comment]
服务端上报到nacos就乱码了,有些就不乱码,我们也遇见了,不知道怎么解决

**Comment by KomachiSion** [comment]
我拿1.3.0版本的demo控制台试了一下，没有复现该问题，刷新了一分钟，非常稳定。

如果1.2.1一直有这个问题，建议升级到1.3.0再试试看。

**Comment by liji2003888** [comment]
> 能否在浏览器的控制台看一下 是服务端返回的数据是乱码 还是前端展示乱码？

服务端返回的数据就乱码了，后面重新部署了一下，暂时还没出现乱码的情况。
我升级到1.3.0试试再

**Comment by lichuangjian1994** [comment]
这个问题解决了吗？
