### ISSUE TITLE
nacos1.2.0服务管理页面，无法下线（通过curl 请求api也无法删除非健康的）

### ISSUE THREAD

**Issue by gfgfggf1988** [alibaba/nacos#2966]
![QQ截图20200605125806](https://user-images.githubusercontent.com/16377180/83844276-415fe700-a739-11ea-918e-9339333be1e6.png)
![QQ截图20200605141723](https://user-images.githubusercontent.com/16377180/83844295-491f8b80-a739-11ea-854d-e86ec4f16c85.png)

**Comment by gfgfggf1988** [comment]
页面显示500  但是服务端日志在哪？我在naming.log中没有发现报错。其他日志文件中也没有

**Comment by chuntaojun** [comment]
集群模式的话，看看每个节点的日志，并查看下一些naming开头的日志信息

**Comment by gfgfggf1988** [comment]
查找了  并没有发现报错  就很奇怪

**Comment by KomachiSion** [comment]
500错误，到`nacos.log`日志文件中查找一下

**Comment by KomachiSion** [comment]
No response more than **7 days**, close issue.
