### ISSUE TITLE
用./startup.sh -m standalone 启动就有94个线程，这是正常的吗？

### ISSUE THREAD

**Issue by zscboy** [alibaba/nacos#2969]
nacos-sever版本：1.3.0
系统：CentOS Linux release 7.8.2003
没有客户端连上来

启动参数：
![image](https://user-images.githubusercontent.com/8179656/83865207-77609380-a758-11ea-90e6-a1505cab49e5.png)

jstack 查看：
![image](https://user-images.githubusercontent.com/8179656/83865311-9d863380-a758-11ea-9ccf-eb5da3b35ecf.png)

![image](https://user-images.githubusercontent.com/8179656/83865445-c60e2d80-a758-11ea-8556-42e238fe2145.png)

**Comment by dongyinuo** [comment]
正常, 不多

**Comment by dongyinuo** [comment]
nacos 中大量异步处理(线程池)

**Comment by chuntaojun** [comment]
As the number of threads is normal, we will try our best to optimize the problem of excessive resource utilization in the future without affecting nacOS performance
