### ISSUE TITLE
nacos 使用命名空间配置id问题

### ISSUE THREAD

**Issue by haochencheng** [alibaba/nacos#297]
如图：要使用nacos 的命名空间  要在bootstrap.properties配置中配置 命名空间的id 。

![image](https://user-images.githubusercontent.com/20943919/48603082-3e16d600-e9b0-11e8-9afd-c6bb464a5940.png)
![image](https://user-images.githubusercontent.com/20943919/48603101-4838d480-e9b0-11e8-9fd2-6d86f941c21f.png)

能否改成通过命名空间名称指定
 如：
`spring.cloud.nacos.config.namespace=dev`

**Comment by yangyshdan** [comment]
A good feature but involving too many effort. Currently Nacos core function, which the SDK talks to, does not support namespace name. If implementing so, it would require part of the console function migrated to Nacos core function. Considering the namespace ID usage is just okay, So I think the feature is not so urgent. I leave it to open discussion, to see if any volunteer would like to join contributing this feature.

**Comment by haochencheng** [comment]
ok

**Comment by wangjuneng** [comment]
@yangyshdan  
Enhance this feature , have tow suggest:
1. The configuration is first loaded according to the id, and if not found, the configuration is loaded with the name.
2. When build the config cache, one configuration adds two records, the key are different, one key is dataid+groupId, and the other key is dataid+groupId+teanetId

**Comment by haochencheng** [comment]
> A good feature but involving too many effort. Currently Nacos core function, which the SDK talks to, does not support namespace name. If implementing so, it would require part of the console function migrated to Nacos core function. Considering the namespace ID usage is just okay, So I think the feature is not so urgent. I leave it to open discussion, to see if any volunteer would like to join contributing this feature.

i had submit a pr to fix this.  see  https://github.com/alibaba/nacos/pull/375

**Comment by yanlinly** [comment]
public是一个公共空间，命名空间id是空串。
这块需要传入命名空间id。 请稍微注意一下~

**Comment by mylove13289** [comment]
直接更新数据库表的namespaceid。tenant_info.tenant_id
<img width="727" alt="a" src="https://user-images.githubusercontent.com/2936935/57432295-0a827d80-7268-11e9-9f48-c3eab94b11d7.png">

**Comment by zhaozhiguang** [comment]
这么久了，是过掉这个了吗

**Comment by qzmer1104** [comment]
> 这么久了，是过掉这个了吗

新建命名空间的时候可以指定id值为dev（不使用默认生成时），所以已经实现了呢
