### ISSUE TITLE
Nacos Server 1.3.0版本在线添加的新配置,客户端无法匹配

### ISSUE THREAD

**Issue by neters** [alibaba/nacos#2971]
Nacos Server: 1.3.0
复现步骤:
1. Nacos Server启动,已有配置ID如: data.yaml
2. Nacos Client启动,可以匹配到data.yaml
3. Nacos Server在线添加一个新配置,如: test.yaml, 此时Nacos Client修改应用名重启,无法匹配新添加的配置项
4. 将Nacos Server重启后,Nacos Client可以匹配到test.yaml

将Nacos Server版本回退到上一个版本,上面的问题不再复现

**Comment by chuntaojun** [comment]
集群还是单机？是使用了mysql存储还是内嵌存储

**Comment by chuntaojun** [comment]
我这里没有复现出你的问题
