### ISSUE TITLE
Nacos 图形化界面版本不一致问题

### ISSUE THREAD

**Issue by lytao123** [alibaba/nacos#2973]
Nacos Server: 1.2.1

- 背景
Nacos Server 在虚拟机 CentOS 7 上运行 ，ip 为 192.168.136.136。

- 复现步骤：
  - 1. 通过谷歌浏览器访问地址：http://192.168.136.136:8848/nacos 并登录（不正常）显示界面如下：
![image](https://user-images.githubusercontent.com/30515852/83942213-2918c680-a824-11ea-8de8-4d4c62a5ba9e.png)
  - 2. 通过火狐浏览器访问地址：http://192.168.136.136:8848/nacos  并登录（正常），显示界面如下：
![image](https://user-images.githubusercontent.com/30515852/83942230-52d1ed80-a824-11ea-9813-03fc11a8d29d.png)

- 结论
从上可以看出通过谷歌访问 Nacos 图形化界面时版本为 `0.8.0` ，而通过火狐访问版本为`1.2.1`，说明通过谷歌访问 Nacos 图形化界面时与所对应的 `1.2.1` 版本不一致。

- 附谷歌版本信息 ：
![image](https://user-images.githubusercontent.com/30515852/83942326-0f2bb380-a825-11ea-9991-c667fda6be84.png)

**Comment by chuntaojun** [comment]
浏览器清空缓存看看

**Comment by lytao123** [comment]
> 浏览器清空缓存看看

清理缓存后正常了
