### ISSUE TITLE
升级到1.3.0后，serverAddr不再支持https?

### ISSUE THREAD

**Issue by squallliu** [alibaba/nacos#2978]
升级之前
客户端可以配置severAddr：https://xxx.xx.xx
升级后 java.lang.IllegalArgumentException: Incorrect serverAddr address : https://xxx.xx.xx, example should like ip:port or domain:port
如果有break change，能在更新日志中说明吗？

**Comment by chuntaojun** [comment]
```java
String getFixedNameSuffix(String... serverIps) {
        StringBuilder sb = new StringBuilder();
        String split = "";
        for (String serverIp : serverIps) {
            sb.append(split);
            serverIp = serverIp.replaceAll("http(s)?://", "");
            sb.append(serverIp.replaceAll(":", "_"));
            split = "-";
        }
        return sb.toString();
    }
```

在代码中会被移除，所以你目前的设置并不生效，同时nacos目前也不支持https

**Comment by squallliu** [comment]
老版本确实可以用

**Comment by squallliu** [comment]
1.2.1

**Comment by chuntaojun** [comment]
我的意思是，你的https并不生效的，1.3.0对参数加入了验证机制

**Comment by squallliu** [comment]
1.3.0我改成domain:port的格式也不能用，拼的url是http协议的

**Comment by chuntaojun** [comment]
> 1.3.0我改成domain:port的格式也不能用，拼的url是http协议的

发出来看下

**Comment by squallliu** [comment]
public boolean login(String server) {
    if (StringUtils.isNotBlank(this.username)) {
      Map<String, String> params = new HashMap(2);
      params.put("username", this.username);
      String body = "password=" + this.password;
      String url = "http://" + server + this.contextPath + "/v1/auth/users/login";
      if (server.contains("http")) {
        url = server + this.contextPath + "/v1/auth/users/login";
      }

      HttpResult result = HttpClient.request(url, new ArrayList(2), params, body, Charsets.UTF_8.name(), "POST");
      if (result.code != 200) {
        SECURITY_LOGGER.error("login failed: {}", JacksonUtils.toJson(result));
        return false;
      }

      JsonNode obj = JacksonUtils.toObj(result.content);
      if (obj.has("accessToken")) {
        this.accessToken = obj.get("accessToken").asText();
        this.tokenTtl = (long)obj.get("tokenTtl").asInt();
        this.tokenRefreshWindow = this.tokenTtl / 10L;
      }
    }

    return true;
  }
这个http写死的

**Comment by chuntaojun** [comment]
> ```
> public boolean login(String server) {
>     if (StringUtils.isNotBlank(this.username)) {
>       Map<String, String> params = new HashMap(2);
>       params.put("username", this.username);
>       String body = "password=" + this.password;
>       String url = "http://" + server + this.contextPath + "/v1/auth/users/login";
>       if (server.contains("http")) {
>         url = server + this.contextPath + "/v1/auth/users/login";
>       }
> 
>       HttpResult result = HttpClient.request(url, new ArrayList(2), params, body, Charsets.UTF_8.name(), "POST");
>       if (result.code != 200) {
>         SECURITY_LOGGER.error("login failed: {}", JacksonUtils.toJson(result));
>         return false;
>       }
> 
>       JsonNode obj = JacksonUtils.toObj(result.content);
>       if (obj.has("accessToken")) {
>         this.accessToken = obj.get("accessToken").asText();
>         this.tokenTtl = (long)obj.get("tokenTtl").asInt();
>         this.tokenRefreshWindow = this.tokenTtl / 10L;
>       }
>     }
> 
>     return true;
>   }
> ```
> 
> 这个http写死的，原来配置https可以绕过去

因为还没到这一步，你的https://前缀就已经被移除了

**Comment by squallliu** [comment]
不不不，1.2.1这里是可以过的，我们一直都是这么用的，如图：
<img width="628" alt="企业微信截图_48f0f70a-74d7-4176-be6d-5b2a6693ce8c" src="https://user-images.githubusercontent.com/585678/84008698-c69b0400-a9a4-11ea-8f7b-5b71665b7d0e.png">
现在不允许配置https了，这里就自动加上了http，还是代码逻辑不统一，应该都从HttpClient. getPrefix()取schema

**Comment by chuntaojun** [comment]
先移除吧，因为目前就算你配置了https，但是底层并没有按https那一套去走，等待nacos统一支持https

**Comment by chuntaojun** [comment]
This experience will be optimized in 1.3.1
