### ISSUE TITLE
Inline storage should support importing data from external data sources

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#2979]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Inline storage should support importing data from external data sources

### Describe what you expected to happen

example

we use this command to export the data from mysql, Nacos needs to support importing this data into embedded storage

```bash
mysqldump --defaults-file="XXX" --host=0.0.0.0 --protocol=tcp --user=XXX --extended-insert=FALSE --complete-insert=TRUE --skip-triggers --no-create-info --skip-column-statistics "{SCHEMA}" "{TABLE_NAME}"
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by SheridonMarie** [comment]
Duplicate of #

**Comment by SheridonMarie** [comment]
Koi
