### ISSUE TITLE
After open auth, the username and password don't refresh when changing config file.

### ISSUE THREAD

**Issue by brandonstack** [alibaba/nacos#2983]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Background:
opened auth on dev namespace, and start the app-server, changed the password of the user, and publish the change on config file. 6hrs later, all app-server which not restart during that time, cannot connect to the nacos server.
The log is:
client :`403 error page`
auth server log: `unknow user`, `token expired`.

### Describe what you expected to happen
Whenever changing the password, the client always can login and get token.

### How to reproduce it (as minimally and precisely as possible)
1.  open auth, and start the app-server.
2. change password on admin page and apply on config file, don't restart app-server.
3. when token expired(6 hr), app-server cannot connect to server.

### Tell us your environment
just standalone. Version: v1.2.1 v1.3.0

### Anything else we need to know?
I assume the client init username and password when first start, and don't refresh when config file changing.

**Comment by chuntaojun** [comment]
You changed the password. Did nacos-Client match the password

**Comment by brandonstack** [comment]
Yes, of course, and the client can get config. And when restart nacos-client, all is well.

**Comment by chuntaojun** [comment]
Are you saying that your Nacos-Client reconfigured the password and restarted it, and after six hours, there's 403?

**Comment by brandonstack** [comment]
We reconfigured the password, not restart it. after the token expired, theres's 403. And after we restart nacos-client, everything's ok. 从nacos控制台修改密码之后, 修改配置文件, 等token失效之后, 所有的服务都连接不上了, core-auth 提示`unkown user`, `token expired`.
重启nacos-client(app-server), 之后就好了

**Comment by brandonstack** [comment]
The username and password in com.alibaba.nacos.client.security.SecurityProxy never change after startup.

**Comment by brandonstack** [comment]
![image](https://user-images.githubusercontent.com/20850218/83968541-9009ae80-a8fc-11ea-90d9-6c3963c8a07b.png)

**Comment by chuntaojun** [comment]
Are you use spring-cloud-alibaba，and discovery account password store in the nacos-config?

**Comment by chuntaojun** [comment]
Is it a single embedded storage mode

**Comment by brandonstack** [comment]
we use mysql, spring-cloud-alibaba  and discovery account password store in the nacos-config.

**Comment by chuntaojun** [comment]
You are not allowed to do this. The password of the discovery account will not be refreshed

**Comment by chuntaojun** [comment]
The account password will only be initialized when the program starts, because the cloud side maintains the nacOS instance singly

**Comment by brandonstack** [comment]
Do you mean we can't change account info during app-server running? If we change the password, all app-server halt, the whole system down. And you think it's a feature rather than a bug?

**Comment by chuntaojun** [comment]
It‘s not bug or fearure, This is not an issue with nacos, but rather with the maintenance of nacOS instances as singletons on the SpringCloud side
