### ISSUE TITLE
1.2.1升级1.3.0后，作为配置中心，spring boot无法获取到对应的配置属性值而无法启动

### ISSUE THREAD

**Issue by Spectred** [alibaba/nacos#2988]
将nacos-1.3.0作为配置中心，按照规范约定的格式进行配置，spring boot 获取不到对应的属性，而在nacos-1.2.1同样的配置可以

**Comment by chuntaojun** [comment]
standalone mode or cluster mode?

**Comment by yanlinly** [comment]
只升级server就有这个问题了？  具体sdk和server侧有什么异常没

**Comment by chuntaojun** [comment]
先用单机+外置数据库的模式吧

**Comment by yanlinly** [comment]
https://github.com/alibaba/nacos/releases/tag/1.3.0    感谢反馈，已经更新到1.3.0版本修复了
