### ISSUE TITLE
Nacos1.3.0 cannot get the configuration correctly

### ISSUE THREAD

**Issue by Gitwangpin** [alibaba/nacos#2989]
## Issue Description

Type: *bug report* or *feature request*
bug report

### Describe what happened (or what feature you want)
I downloaded the latest version 1.3.0 integrated spring Cloud discovery request to get the configuration interface with beta as the true parameter

I grabbed the package and found that I got 404 for true without beta

### Describe what you expected to happen
I have integrated the latest Spring-cloud-starter alia-Nacos-config

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
windows
idea
Spring-cloud-starter alia-Nacos-config  2.2.1.RELEASE

**Comment by chuntaojun** [comment]
standalone mode or cluster mode?

**Comment by Gitwangpin** [comment]
standalone mode .I just configured mysql instead of configuring the database .But does nacos 1.3.0 seem to have no user management?

**Comment by chuntaojun** [comment]
user management need to set nacos.core.auth.enabled=true

you mean is you publish config with beta, and client can't get this config?

**Comment by chuntaojun** [comment]
If you want client can read config which is beta, you need to add this client ip in beta white list

**Comment by Gitwangpin** [comment]
I first deployed it with Docker without configuring any environment variables. Nacos should use the built-in database.At this point, my client couldn't get any configuration, so I grabbed the packet and found a 404 because there was no beta parameter.I downloaded the official version of 1.3.0 instead of the beta version.Later, I tried using the mysql database, at which point I was able to get the configuration properly.

**Comment by chuntaojun** [comment]
could you tell me you DingTalk account ?

**Comment by Gitwangpin** [comment]
What's your E-mail address? I will send my account to your email

**Comment by chuntaojun** [comment]
liaochuntao@live.com

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2988

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2971

**Comment by Gitwangpin** [comment]
thanks !    I forgot to configure spring.datasource.platform=mysql

**Comment by yanlinly** [comment]
https://github.com/alibaba/nacos/releases/tag/1.3.0    感谢反馈，已经更新到1.3.0版本修复了
