### ISSUE TITLE
1.3.0集群安装后 节点列表显示接口找不到

### ISSUE THREAD

**Issue by xingwl2018** [alibaba/nacos#2991]
## Issue Description

Type: *bug report* or *feature request*
 
bug report
### Describe what happened (or what feature you want)

#集群管理中节点列表显示找不到接口
Interface not found in the list of nodes in cluster management

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 
![image](https://user-images.githubusercontent.com/38937448/83995739-cf7fdb80-a98c-11ea-8650-eed42de5e7d1.png)

### Tell us your environment

dockers镜像版本  1.3.0-latest；

### Anything else we need to know?

error: "Not Implemented"
message: "no such api:GET:/nacos/v1/ns/operator/cluster/states"
path: "/nacos/v1/ns/operator/cluster/states"
status: 501
timestamp: "2020-06-08T05:33:03.831+0000"

**Comment by zhuyouzhufu** [comment]
刚启动nacos-server1.3.0的时候的确会出现这个问题，在某些服务注册上去之后这个问额就消失了

**Comment by chuntaojun** [comment]
清空浏览器缓存下，这个页面不对

**Comment by xingwl2018** [comment]
可以了

**Comment by 471090819** [comment]
1.4版本在ubantu上也会出现no such api:GET:/nacos/v1/ns/operator/cluster/states
