### ISSUE TITLE
Unified code style file to do format verification and formatting

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#2992]
### Issue Description

Type: *feature request*

### Describe what you expected to happen

I hope to add a unified checkstyle file, and then use this file for format verification and formatting.

So I want to open a discussion to choose one checkstyle file:

1. google checkstyle
2. spring boot checkstyle
3. modify from other checkstyle
4. other

**Comment by zongtanghu** [comment]
I think google code checkstyple may be better choice.

**Comment by jzdayz** [comment]
google checkstyle

**Comment by KomachiSion** [comment]
From the discussion in issue and meeting at 2020.06.11. We prefer to use google style as based, and change some setting like `line warp` , `indent` and so on.

I will create `nacosCodeStyle.xml` file, init format for all code, and write a document in `nacos.io` to lead developers.

BTW, the `Alibaba Java Coding Guidelines` will also be used.

**Comment by KomachiSion** [comment]
reformat task:

- [ ] nacos-api
- [x] nacos-common
- [x] nacos-core
- [ ] nacos-client
- [x] nacos-consistency
- [x] nacos-naming
- [ ] nacos-config
- [ ] nacos-address
- [ ] nacos-cmdb
- [ ] nacos-console
- [ ] nacos-istio
- [ ] other
