### ISSUE TITLE
Nacos 1.3.0 console throw exception : Unknown system variable 'tx_read_only'

### ISSUE THREAD

**Issue by nichenghyx** [alibaba/nacos#2993]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. start the nacos V1.3.0 
2. console out this

### Tell us your environment

![image](https://user-images.githubusercontent.com/20518717/84019689-3664bb00-a9b4-11ea-81ec-ef8ba7f95ae7.png)

**Comment by chuntaojun** [comment]
Mount the driver for mySQL8.x under ${nacos.home}/plugins/mysql

**Comment by chuntaojun** [comment]
Does the cluster page always show this state? Refresh to see, or take a look at the nacos-Cluster log

**Comment by nichenghyx** [comment]
> Mount the driver for mySQL8.x under ${nacos.home}/plugins/mysql
我使用的是mysql5.6,为什么要挂载8.X的插件，还有怎么挂载这个插件，我把它用集群模式启动了之后，其他几个节点状态也显示异常

**Comment by chuntaojun** [comment]
1、You may need to upgrade mysql to 5.7.x.

**Comment by KomachiSion** [comment]
@nichenghyx , Please change your issue title to make search friendly, Thanks.
