### ISSUE TITLE
权限控制相关问题

### ISSUE THREAD

**Issue by lovegames** [alibaba/nacos#2997]
我创建两个命名空间test/dev
然后创建账号test,分配权限为test
登入test账号还是能看到和操作dev空间下的配置和服务
是我操作不对,还是权限控制没到这个级别,希望能够知道一下
谢谢!

**Comment by chuntaojun** [comment]
nacos.core.auth.enabled=true开启了吗

**Comment by lovegames** [comment]
谢谢,已解决

**Comment by taoxiaoyin** [comment]
![image](https://user-images.githubusercontent.com/3125643/84722585-3406f000-afb6-11ea-81c0-7f32a2c833a2.png)

**Comment by chuntaojun** [comment]
@taoxiaoyin What is your point

**Comment by taoxiaoyin** [comment]
开启权限控制之后，就报这个错误了，使用dev,和test不同帐户登录就有错。nacos.core.auth.enabled=true，和nacos.core.cacheing.enabled=true都是true了
