### ISSUE TITLE
Can Nacos add the description of this release when publishing the configuration ?

### ISSUE THREAD

**Issue by pengyonglei** [alibaba/nacos#2999]
## Issue Description
Type:  *feature request*

### Describe what happened (or what feature you want)
I hope to provide a field to record the content of this release during the release configuration, so that I can view what has been modified in this release in the history record

希望在发布配置的时候提供一个记录本次发布内容的字段, 让我在历史记录记录里面可以查看本次发布修改了什么

**Comment by wfnuser** [comment]
这个是说需要在nacos的持久层存一下吗？ 还是浏览器存一下就好了？

**Comment by pengyonglei** [comment]
My needs are persisted into the database, it doesn't make sense to only exist in the browser. 

我的需求是持久化到数据库里面的, 只存在浏览器里面是没有意义的
