### ISSUE TITLE
nacos默认是ap模式吗？

### ISSUE THREAD

**Issue by AnoYuan** [alibaba/nacos#3000]
nacos默认是ap模式吗？
使用默认模式当nacos集群其中一台nacos宕机，观察日志还是会进行cp的raft选举。

**Comment by AnoYuan** [comment]
使用默认的模式，3台nacos，nginx vip ，leader宕机，会进行raft选举，选举期间，没被选成leader的follower是不可用的，单独访问无法使用，被选成leader的candidate是可用的，使用nginx集群整体可用。
但是不理解，如果默认是ap模式，为什么会执行选举，没有深入读代码。

**Comment by LiujunjieALiling** [comment]
底层集群就是采用的Raft协议

**Comment by AnoYuan** [comment]
文档里表示，AP模式下是使用distro协议，多节点可以写，CP模式下使用的是raft选举，只有leader可以写，这个描述是正确的么。
还有就是默认的模式是AP模式么，或者说如何开启AP和CP模式的切换？

**Comment by AnoYuan** [comment]
> 底层集群就是采用的Raft协议

文档里表示，AP模式下是使用distro协议，多节点可以写，CP模式下使用的是raft选举，只有leader可以写，这个描述是正确的么。
还有就是默认的模式是AP模式么，或者说如何开启AP和CP模式的切换？

**Comment by jzdayz** [comment]
1.2.1临时节点是 ap distro
.持久节点 cp raft

**Comment by AnoYuan** [comment]
> 1.2.1临时节点是 ap distro
> .持久节点 cp raft

您的意思是，如果注册nacos的client节点注册时ephemeral=true，那么nacos集群对这个client节点的效果就是ap的采用distro，而注册nacos的client节点注册时ephemeral=false，那么nacos集群对这个节点的效果就是cp的采用raft。根据client注册时的属性，ap，cp同时混合存在，只是对不同的client节点效果不同？

**Comment by jzdayz** [comment]
> > 1.2.1临时节点是 ap distro
> > .持久节点 cp raft
> 
> 您的意思是，如果注册nacos的client节点注册时ephemeral=true，那么nacos集群对这个client节点的效果就是ap的采用distro，而注册nacos的client节点注册时ephemeral=false，那么nacos集群对这个节点的效果就是cp的采用raft。根据client注册时的属性，ap，cp同时混合存在，只是对不同的client节点效果不同？

 对的。

**Comment by songjiang951130** [comment]
> 1.2.1临时节点是 ap distro
> .持久节点 cp raft

什么样的节点该设计成临时节点或者永久节点呢

**Comment by yangseal** [comment]
既然说是底层集群就是采用的Raft协议，官网上说通过命令切换集群模式, 这里怎么理解了curl -X PUT '$NACOS_SERVER:8848/nacos/v1/ns/operator/switches?entry=serverMode&value=CP',不是通过客户端是不是临时节点判断的吗？好矛盾啊
