### ISSUE TITLE
使用shared-configs公共配置，启动时获取不到公共配置的属性

### ISSUE THREAD

**Issue by zhujiebing** [alibaba/nacos#3002]
## Issue Description
从spring cloud config迁移到nacos，通过dataid加spring.profiles.active来做多环境。  新建dataid application-web2.yml【共享配置】和mss-basic-center-web2.yml，当启动mss-basic-center服务时提示获取不到共享配置里面的属性【Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'fileserver.fsToken' in value "${fileserver.fsToken}"】。 谢谢
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
bootstrap.yml配置如下：
spring:
  application:
    name: mss-basic-center

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
##环境
  profiles:
    active: web2

### Tell us your environment
spring cloud alibaba 2.2.1.RELEASE；spring cloud Hoxton.SR1；spring boot 2.2.2.RELEASE;  nacos server是cmd启动的1.3.0

**Comment by chuntaojun** [comment]
nacos-server使用单机+内嵌吗？换成单机+mysql，或者重新下载下nacos-server 1.3.0

**Comment by zhujiebing** [comment]
> nacos-server使用单机+内嵌吗？换成单机+mysql，或者重新下载下nacos-server 1.3.0

找到问题了，是因为我配置里面有一个key valye是
info:
  version: @project.version@
断点loadNacosData()发现因为@符号抛异常了。

**Comment by xingwl2018** [comment]
集群模式不支持吗？我的就是获取不到文件内容，只能获取到 默认的配置方式的文件

**Comment by chuntaojun** [comment]
> 集群模式不支持吗？我的就是获取不到文件内容，只能获取到 默认的配置方式的文件

贴下配置以及nacos控制台相关配置的信息页面

**Comment by xingwl2018** [comment]
##================nacos-config-start=======================
spring.cloud.nacos.config.server-addr=192.168.2.102:8849
#文件类型,默认：properties
spring.cloud.nacos.config.file-extension=yml
#配置文件DataId;默认:${spring.application.name}-${spring.profile.active}.${file-extension:properties/yml}
spring.cloud.nacos.config.name=hystrix-config-demo-test1
#文件空间,默认：public;使用命名空间id，使用名称不生效
spring.cloud.nacos.config.namespace=dev
##文件分组,默认：DEFAULT_GROUP
spring.cloud.nacos.config.group=test
##多文件获取:1、共享文件shared-configs；2、扩展文件：extension-configs
#spring.cloud.nacos.config.shared-configs[0].group=test2
#spring.cloud.nacos.config.shared-configs[0].data-id=external_file2.yml
#spring.cloud.nacos.config.shared-configs[0].refresh=true


spring.cloud.nacos.config.extension-configs[0].data-id=external_file1.yml
spring.cloud.nacos.config.extension-configs[0].group=test
spring.cloud.nacos.config.extension-configs[0].refresh=true

##================nacos-config-end=======================
![image](https://user-images.githubusercontent.com/38937448/84336113-2bcf3f00-abc9-11ea-81df-7d11c2aec3da.png)

![image](https://user-images.githubusercontent.com/38937448/84336171-4c979480-abc9-11ea-8494-323ff36b41dc.png)

**Comment by chuntaojun** [comment]
data-id不对，注意看你配置文件内的data-id名称和控制台显示的，data-id是强匹配

**Comment by xingwl2018** [comment]
不加后缀的话  直接提示让加 后缀
java.lang.IllegalStateException: [external_file1] must contains file extension with properties|yaml|yml|xml|json

**Comment by chuntaojun** [comment]
那你重新发布一个配置在控制台吧，这是cloud那边的设计问题，非nacos问题，注意看文档以及相关wiki

**Comment by xingwl2018** [comment]
测试之后  控制台添加的文件data-id 必须是与 配置文件中配置的data-id保持一致(有后缀名)，和spring.cloud.nacos.config.name可以没有后缀名不同。

**Comment by jamie9762** [comment]
> 测试之后 控制台添加的文件data-id 必须是与 配置文件中配置的data-id保持一致(有后缀名)，和spring.cloud.nacos.config.name可以没有后缀名不同。

真不知道怎么想的,加个file-type也好啊,一会有后缀,一会没有的

**Comment by chuntaojun** [comment]
> > 测试之后 控制台添加的文件data-id 必须是与 配置文件中配置的data-id保持一致(有后缀名)，和spring.cloud.nacos.config.name可以没有后缀名不同。
> 
> 真不知道怎么想的,加个file-type也好啊,一会有后缀,一会没有的

这一块和spring cloud alibaba nacos那边的设计有关系哦，对于nacos来说，是走data-id全匹配的，不存在什么后缀的

**Comment by shuaixiaomi** [comment]
我也遇到了这个问题，我在本地配置文件里面配置了shared-configs， 启动时能获取到公共配置，但把本地配置文件的 shared-configs 删了，在nacos 上配置shared-configs ，就获取不到公共配置
