### ISSUE TITLE
Please add try{}catch{} code block in the springboot project startup class

### ISSUE THREAD

**Issue by MainPoser** [alibaba/nacos#3003]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
If the project fails to start and no error is reported, this will be a great help

### Describe what you expected to happen
Please add try{}catch{} code block in the springboot project startup class

### Anything else we need to know?
java exception mechanism

**Comment by MainPoser** [comment]
@i will solve it@

**Comment by chuntaojun** [comment]
why you want to do this？you can see com.alibaba.nacos.core.code.StartingSpringApplicationRunListener

**Comment by KomachiSion** [comment]
There are print log for start error at `logs/nacos.log`
