### ISSUE TITLE
For Nacos, whether the read configuration of the client causes frequent IO access

### ISSUE THREAD

**Issue by a6910438** [alibaba/nacos#3004]
In the Nacos example project

ConfigExample.java The information of reading configuration file in test case is read through local file

My ideal logic:

1. When the client opens the connection, it will copy the file in the local snapshot directory

2. The control center modifies the configuration information, first updates the container memory data and database information, and then notifies all clients to update the local file configuration

3. When the client reads it, it should first pass the local configuration, and then go to the request control center if it is not available

My question:

Whether such a logic can become intolerable in the case of high concurrency, even if the cluster is used, whether it will enhance the difficulty and instability of deployment, and whether it can optimize the entire logic,

Best regards

**Comment by KomachiSion** [comment]
@a6910438 Please change your issue title to make search friendly. Thanks.

**Comment by chuntaojun** [comment]
1、Not all configurations need to be listened to, just listen to the configuration you want to listen to, listen on demand.
2、The local file is only used as a disaster recovery measure to read the local file in case the server fails to work
3、Combined with the first two points, the getConfig method must ask the server side to get the latest data, and the local file should be in the post-disaster recovery process
4、If the user selects getAndSignListener, there is only one active configuration process and the others are waiting for active notifications from the server side

so it won't cause enhance the difficulty and instability of deployment

**Comment by a6910438** [comment]
nice, I agree with you very much



Can two-way notifications get rid of one party? I want the business server to focus on the business. I don't know what the problem is?

**Comment by chuntaojun** [comment]
In the future we will use grpc to replace http long-polling, If you use config-center and want to watch config change which client interest, you need to tell nacos-server you interest config list, if you remove listener in client running, sdk will auto remove watch job

**Comment by a6910438** [comment]
Thank bro
