### ISSUE TITLE
添加自定义健康检查地址时：403  resource name invalid!

### ISSUE THREAD

**Issue by xingwl2018** [alibaba/nacos#3005]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

添加异常：

error: "Forbidden"
message: "resource name invalid!"
path: "/nacos/v1/ns/cluster"
status: 403
timestamp: "2020-06-09T10:27:45.536+0000"

### Describe what you expected to happen

request url :   ip:port/nacos/v1/ns/cluster?&accessToken=xxx

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
 nacos-server 1.3.0

### Anything else we need to know?
![image](https://user-images.githubusercontent.com/38937448/84137477-56ad7c00-aa7f-11ea-95b9-7c86b6fdbc88.png)

**Comment by KomachiSion** [comment]
Please close the auth, I will try to find out and fix this problem.

**Comment by xingwl2018** [comment]
![image](https://user-images.githubusercontent.com/38937448/84218849-d7ad5780-ab01-11ea-9014-ca4b63d6f87f.png)
After the authentication is turned off, it can be added successfully. However, if the port is not assigned correctly, it is still port 80. And it seems that the health examination method will not take effect after it is modified
