### ISSUE TITLE
实例点击下线之后，在服务列表中  该服务的实例数及健康数 没有变化是这样的吗？

### ISSUE THREAD

**Issue by xingwl2018** [alibaba/nacos#3006]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
目前看来是这样。下线实例 也是该服务的实例， 并且健康与否与他是否下线其实无关。 因此下线只是不对订阅者可见，但是控制台应该没有影响。

**Comment by chuntaojun** [comment]
yes

**Comment by xingwl2018** [comment]
ok
