### ISSUE TITLE
Nacos可以和Traefik结合在一起使用吗?

### ISSUE THREAD

**Issue by neters** [alibaba/nacos#3009]
之前项目使用的网关是Traefik,然后现在想把Nacos作为服务中心引入进来,这两个能集成吗?
或者,你们有推荐与Nacos作为服务中心一起使用的网关吗?

**Comment by KomachiSion** [comment]
spring cloud gateway

**Comment by KomachiSion** [comment]
之前有试过spring cloud gateway， 其他网关理论上也可以吧，不过没测试过

**Comment by GoNorth** [comment]
请问下，nacos可以traefik集成吗？
