### ISSUE TITLE
nacos 1.1.4 k8s集群 OOM

### ISSUE THREAD

**Issue by zhangzh0508** [alibaba/nacos#3012]
nacos版本：1.1.4
环境：RHEL 7.4
           k8s 1.14.6
           k8s pox限制内存大小 2G
现象：运行几个月内，nacos-0、nacos-1、nacos-2节点均有重启现象，原因都是OOMKilled 

是因为pod限制过小吗，多少合适，OOM的原因是什么

**Comment by KomachiSion** [comment]
您服务数量，有多少？

**Comment by KomachiSion** [comment]
系统OOM killed可能不是nacos的OOM导致的，是有其他进程申请系统内存，发现内存不足，系统找一个占比较高的进程杀掉释放内存。

具体的需要您把OOM时的内存dump出来看一下，我们一起分析和定位问题。

**Comment by zhangzh0508** [comment]
> 系统OOM killed可能不是nacos的OOM导致的，是有其他进程申请系统内存，发现内存不足，系统找一个占比较高的进程杀掉释放内存。
> 
> 具体的需要您把OOM时的内存dump出来看一下，我们一起分析和定位问题。

可能我描述的有误，我意思就是pod重启，不是系统，pod里只有nacos的容器，查看k8s pod描述， 重启原因是OOM Killed。

默认nacos启动jvm配置是2g，k8spod的内存限制我开始设置是2g，我以为pod内有其他进程影响，之后我改成2.5g，但依然有pod OOMkilled 导致nacos重启

我不知道该如何将已重启的容器或pod的内存dump出来，请指教下

**Comment by KomachiSion** [comment]
我们内部运行千百个nacos集群在k8s上，从没有出现过oom的问题，如果出现了，还是得需要想办法dump出来看下内存。

> 您服务数量，有多少？

理论上2G内存可以支撑4k左右服务数量，如果您服务数量过多，的确需要的内存会很多。

**Comment by zhangzh0508** [comment]
> 我们内部运行千百个nacos集群在k8s上，从没有出现过oom的问题，如果出现了，还是得需要想办法dump出来看下内存。
> 
> > 您服务数量，有多少？
> 
> 理论上2G内存可以支撑4k左右服务数量，如果您服务数量过多，的确需要的内存会很多。

测试环境目前运行服务器300左右

**Comment by KomachiSion** [comment]
服务300左右，大约有多少实例数？

**Comment by zhangzh0508** [comment]
> 服务300左右，大约有多少实例数？

测试环境都是单节点，实例数和服务数量相同

**Comment by KomachiSion** [comment]
`k8s pox限制内存大小 2G` 
是说给每个pod分配2G内存 还是说只允许应用申请2G， 超过2G不允许申请？

**Comment by KomachiSion** [comment]
No response more than 7 days.
