### ISSUE TITLE
控制台界面导航问题

### ISSUE THREAD

**Issue by zhaidw** [alibaba/nacos#3013]
## Issue Description
*feature request* 控制台界面左上角的logo点了应该跳转到控制台首页，而不是现在的官网，这个我觉得应该改改，目前导航不好用，刷新下浏览器就不在之前打开的页面了

### Describe what happened (or what feature you want)

click left top logo of nacos console , can not go to console home page.

### Describe what you expected to happen

click left top logo of nacos console  should go to console home page.

### How to reproduce it (as minimally and precisely as possible)

all version can reproduce  it.

### Tell us your environment
I used following versions:
v1.2.1
v1.2.0

**Comment by zzq1314zll** [comment]
@KomachiSion Can i do this

**Comment by zzq1314zll** [comment]
@i will solve it@
