### ISSUE TITLE
MySQL initialization script execution failed in version 1.3.0

### ISSUE THREAD

**Issue by baolongcheng** [alibaba/nacos#3016]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

When I use version 1.3.0, there is an error in initializing the SQL execution. Through troubleshooting, I found that there is a problem in the permissions table. The error information is: specified key was too long; max key length is 767 bytes. The database used is mysql, and the database version is 5.6.44

![image](https://user-images.githubusercontent.com/40141347/84236554-5ddd9400-ab2a-11ea-9d7b-d725ca9c9f4f.png)

![image](https://user-images.githubusercontent.com/40141347/84236576-6930bf80-ab2a-11ea-9f11-4b06044d3ba7.png)

### Describe what you expected to happen

SQL executes normally and table creation is normal

### How to reproduce it (as minimally and precisely as possible)

1. This is necessary if the database is MySQL and the InnoDB used by the storage engine is stored. You only need to execute Nacos in the distribution \ conf directory- mysql.sql This script can be reproduced

**Comment by baolongcheng** [comment]
@i will solve it@

**Comment by zhaidw** [comment]
在InnoDB中，可以启用启用innodb_large_prefix参数，来使得单个索引字段的长度突破767

修改 mysql 参数  innodb_large_prefix=on

**Comment by chuntaojun** [comment]
修改你的字符集为latin1即可

**Comment by baolongcheng** [comment]
> 修改你的字符集为latin1即可

修改为latin1并不是一个很好的选择。如果修改为latin1,那么程序中的数据库的链接指定的字符集也要修改，以及其他表的默认字符集也需要同步修改，保持一致，否则后续很容易出现乱码。还是修改mysql的配置文件的参数innodb_large_prefix，修改数据库中的支持的索引长度；或者修改索引字段的长度；亦或者是升级数据库的版本会更好一些。
