### ISSUE TITLE
client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java has a error

### ISSUE THREAD

**Issue by tomakemyself** [alibaba/nacos#3019]
Type:  code errors
1. client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java method public void registerService(String serviceName, String groupName, Instance instance) throws NacosException 
code have a errors should be fixed.

在1. client/src/main/java/com/alibaba/nacos/client/naming/net/NamingProxy.java 类代码里的registerService方法里，定义了一个map：final Map<String, String> params = new HashMap<String, String>(9); 这是一个错误的定义，map的初始容量应该要是2的幂次方，虽然在内部会被强转为2的幂次方，但我们应该严谨的对待，希望官方修复，thank you！

**Comment by KomachiSion** [comment]
欢迎提交PR修复这个问题。

**Comment by jzdayz** [comment]
@i will solve it@
