### ISSUE TITLE
Adding a snapshot parameter called snapshotLogIndexMargin.

### ISSUE THREAD

**Issue by zongtanghu** [alibaba/nacos#3020]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Now, we can do snapshot saving triggered every snapshot_interval_s seconds which parameter snapshotIntervalSecs value is defined.But this has issue, if raft log is increasing slowly. It will have some unuseful snapshot.

### Describe what you expected to happen
So, we can provide a snapshot parameter called snapshotLogIndexMargin which it has already supports by SOFAJRaft.

**Comment by jzdayz** [comment]
Can i do that?

**Comment by zongtanghu** [comment]
I will resolve this feature by myself, thanks. @jzdayz

**Comment by jzdayz** [comment]
> I will resolve this feature by myself, thanks. @jzdayz

ok
