### ISSUE TITLE
nacos1.3.0权限控制不起任何作用

### ISSUE THREAD

**Issue by xujunhua555** [alibaba/nacos#3024]
任何角色的用户可以修改任意一个命名空间下的资源

**Comment by KomachiSion** [comment]
duplicate with #2997

**Comment by xujunhua555** [comment]
> duplicate with #2997 #2882

我是docker环境，docker已将将该参数设置为true，无法使用啊。。权限不起作用

**Comment by xingwl2018** [comment]
先打开权限配置
![image](https://user-images.githubusercontent.com/38937448/84339292-b7989980-abd0-11ea-8147-32e64eb31343.png)

**Comment by xujunhua555** [comment]
> 先打开权限配置
> ![image](https://user-images.githubusercontent.com/38937448/84339292-b7989980-abd0-11ea-8147-32e64eb31343.png)

NACOS_AUTH_ENABLE已经设置为true了。貌似NACOS_AUTH_CACHE_ENABLE没有设置为true

**Comment by taoxiaoyin** [comment]
failed to req API:/api//nacos/v1/ns/instance after all servers([10.12.102.184:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Jun 16 10:01:12 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
我NACOS_AUTH_ENABLE和NACOS_AUTH_CACHE_ENABLE都设置成true之后，启动就报这个错了，还需要哪里配置吗

**Comment by taoxiaoyin** [comment]
<img width="325" alt="auth" src="https://user-images.githubusercontent.com/3125643/84724802-9f9f8c00-afbb-11ea-84ea-aaaad15e5253.png">

**Comment by chuntaojun** [comment]
@taoxiaoyin 老版本升级上来记得清空浏览器缓存

**Comment by Force-King** [comment]
我不是老版本升级，刚开始使用nacos, 用的是1.3.0，也存在该问题
![image](https://user-images.githubusercontent.com/23328256/85244553-8a4fb500-b434-11ea-9a04-5c2995daa24f.png)

**Comment by yugj** [comment]
> 我不是老版本升级，刚开始使用nacos, 用的是1.3.0，也存在该问题
> ![image](https://user-images.githubusercontent.com/23328256/85244553-8a4fb500-b434-11ea-9a04-5c2995daa24f.png)

给当前这个用户加下public命名空间读取权限，不然默认进入这个页面，很难看
