### ISSUE TITLE
In cluster mode, a server node is abnormal, and a client always registers with the abnormal node when it starts.

### ISSUE THREAD

**Issue by chongli-j** [alibaba/nacos#3030]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
In cluster mode（five servers）, a server node is abnormal, and a client always registers with the abnormal node when it starts.
集群模式下，一个server节点异常(容器显示连接被占满)，某个客户端启动总是注册到异常节点。

### Describe what you expected to happen
In AP mode, a node abnormality should not affect the use of the cluster
AP模式下，一个节点异常不应该影响集群的使用

### How to reproduce it (as minimally and precisely as possible)
1. Make a node unable to establish a connection, but can ping
2. Start some clients to register

### Tell us your environment
nacos server: nacos 1.1.4
nacos discovery : 2.1.1.RELEASE
container：k8s

**Comment by KomachiSion** [comment]
Can you try to use 1.3.0 version?

**Comment by KomachiSion** [comment]
And how many services and instances in your clusters.

**Comment by chongli-j** [comment]
> Can you try to use 1.3.0 version?

1.1.4 is already used in the prod environment, upgrade version may cause too much influence

**Comment by chongli-j** [comment]
> And how many services and instances in your clusters.

this happened in our uat environment，about 200 instances

**Comment by KomachiSion** [comment]
Same service will be route to same nacos node, if the 200 instances is same service, and container has max of connection. You need to upper the max connection to solve problem.

**Comment by chongli-j** [comment]
> Same service will be route to same nacos node, if the 200 instances is same service, and container has max of connection. You need to upper the max connection to solve problem.

thanks very much.
