### ISSUE TITLE
1.3.0 的启动速度慢了很多，刚开始还以为自己配有问题，启动不了呢

### ISSUE THREAD

**Issue by tangbo170615** [alibaba/nacos#3032]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tangbo170615** [comment]
还有 个人觉得 页面的布局 上下结构，实在是 不太好看。

**Comment by chuntaojun** [comment]
是在window系统启动吗

**Comment by tangbo170615** [comment]
是的……今天拿到 1.3.0版本试了好几次，都比较慢




| |
汤波
邮箱：tangbo170615@163.com
|

签名由 网易邮箱大师 定制

在2020年06月11日 18:53，liaochuntao 写道：

是在window系统启动吗

**Comment by chuntaojun** [comment]
> 是的……今天拿到 1.3.0版本试了好几次，都比较慢 | | 汤波 邮箱：tangbo170615@163.com | 签名由 网易邮箱大师 定制 在2020年06月11日 18:53，liaochuntao 写道： 是在window系统启动吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

试着在linux环境下启动看看
