### ISSUE TITLE
编辑配置时，配置格式默认清空

### ISSUE THREAD

**Issue by shansr** [alibaba/nacos#3033]
## Issue Description

在进行配置编辑时，配置格式默认清空

### How to reproduce it (as minimally and precisely as possible)

1. 进入管理页面，点击“配置管理-配置列表”
2. 对任意配置点击编辑，进入编辑页面
3. 配置格式默认为空，选中任一配置格式如：yaml，并发布后，再次进入配置格式依然为空，且不会yaml高亮

**Comment by chuntaojun** [comment]
我这里没有复现出你的问题，请问下版本是多少

**Comment by shansr** [comment]
> 我这里没有复现出你的问题，请问下版本是多少

1.3.0

**Comment by chuntaojun** [comment]
官网demo也没有复现出你的问题，试着页面缓存清空下

**Comment by KomachiSion** [comment]
No response more than **7 days**, close issue
