### ISSUE TITLE
删除配置请求，delete请求带了body，很多反向代理不支持

### ISSUE THREAD

**Issue by sbwfnhn** [alibaba/nacos#3034]
在请中，delete的请求带了下面的Request Body，导制加了反向代理的功能，全部删除配置变成504timeout无响应。

http://nacos22.ldops.cn/nacos/v1/cs/configs?delType=ids&ids=35,
Host: nacos22.ldops.cn
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImF1dGgiOiIiLCJleHAiOjE1OTE4NzI3MTd9.9R6yXOGzEIy1-Y0q_uFmwqpnyAEBFpZSZensu0BVJOw
X-Requested-With: XMLHttpRequest
Content-Length: 12
Origin: http://nacos22.ldops.cn
Connection: keep-alive
Referer: http://nacos22.ldops.cn/nacos/
Cookie: experimentation_subject_id=IjdhMjcwYTE3LWI4Y2YtNDRkNi1hYzJiLTkwNTkxYjIwZWU0NiI%3D--2a974ba96823bf65b39ccd432ccd194dd01c27af; _ga=GA1.2.1094159438.1591237794
Cache-Control: max-age=0

request body
namespaceId=384aa673-c831-4039-aa46-09d97352ab5f

**Comment by KomachiSion** [comment]
Refer to #3216
