### ISSUE TITLE
nacos配置中心不自动刷新

### ISSUE THREAD

**Issue by yiqinghui** [alibaba/nacos#3038]
只有重启服务，或者重启nacos-spring-boot-config-example后，才能获取到最新值

![2](https://user-images.githubusercontent.com/23735927/84412540-fadf2080-ac41-11ea-8ef6-623c04de7d13.png)
![3](https://user-images.githubusercontent.com/23735927/84412542-fd417a80-ac41-11ea-96ef-dfe61e7ba775.png)
![1](https://user-images.githubusercontent.com/23735927/84412546-ff0b3e00-ac41-11ea-9aae-cd910776e917.png)

**Comment by yiqinghui** [comment]
为什么路径是 fixed-127.0.0.1:8848_nacos，应该是 fixed-127.0.0.1_8848_nacos 吧，这样是不是就不报错了。

**Comment by Maijh97** [comment]
Can I track down this issue, and if it confirms it exists, I will fix it.

**Comment by chuntaojun** [comment]
你的配置刷新通知时成功触发了的，注意看最后一个日志信息

**Comment by chuntaojun** [comment]
打印看下environment的数据，看看配置有没有刷新到environment中

**Comment by KomachiSion** [comment]
No response more than **7 days**, close issue
