### ISSUE TITLE
nacos group分组名如果非DEFAULT_GROUP则无法下线

### ISSUE THREAD

**Issue by maojing123** [alibaba/nacos#3041]
![image](https://user-images.githubusercontent.com/48919665/84457248-be88e000-ac94-11ea-9f9e-57b5813b0773.png)
如上图：服务名user-center 对应的分组名 dev。，然后点击详情
里面点击下线 提示

![image](https://user-images.githubusercontent.com/48919665/84457292-e37d5300-ac94-11ea-992b-666dae980ac6.png)
![image](https://user-images.githubusercontent.com/48919665/84457344-014ab800-ac95-11ea-8ea2-9e9a0f5e1556.png)

但是 当我刷新这个 页面的时候 。
![image](https://user-images.githubusercontent.com/48919665/84457379-10ca0100-ac95-11ea-88d1-ee74714e41d4.png)
![image](https://user-images.githubusercontent.com/48919665/84457406-25a69480-ac95-11ea-8f65-69a5dacb0579.png)

当点击浏览器的回退箭头 进入到服务列表首页 会出来一个刚操作的服务对应的默认分组，点击详情则里面是”上线“ 好像刚操作的时候 他没有将dev分组的服务下线 但是生成了一个 默认分组的 下线了。
![image](https://user-images.githubusercontent.com/48919665/84457496-6acac680-ac95-11ea-9f2e-bcb557dfbd11.png)
![image](https://user-images.githubusercontent.com/48919665/84457582-a5ccfa00-ac95-11ea-8104-8f6bf42c2b07.png)

**Comment by maojing123** [comment]
问题描述

我有一个 服务 user-center.新建的分组是 dev,对应点击详情进入 点击“下线”，按钮从“下线”变成了“上线”，
但是这个时候 如果我刷新页面 会发现 user-center,对应的dev分组的这个服务并没有下线（实际的确本地能够请求到这个服务），对应的按钮还是“下线”


这个时候 点击浏览器的“回退箭头”则 服务列表页面会出来 user-center 分组名DEFAULT_GROUP的一条记录，点击详情会发现 是“上线”，刷新整个页面则这条记录大概率会消失掉。偶尔需要刷新几次才消失。

怀疑这里 当某个服务有非DEFAULT_GROUP分组的时候，点击下线 无法生效 。
Problem Description

I have a service user-center. The newly created group is dev, corresponding to click on the details to enter Click on "offline", the button changes from "offline" to "online",
But at this time, if I refresh the page, I will find that user-center, the service of the corresponding dev group is not offline (actually, the service can be requested locally), the corresponding button is still "offline"


At this time, click the "back arrow" of the browser, and the service list page will come out. A record of the user-center group name DEFAULT_GROUP. Click the details to find that it is "online". Refreshing the entire page will most likely disappear this record. Occasionally need to refresh several times before disappearing.

It is suspected that when a service has a non-DEFAULT_GROUP group, clicking offline cannot take effect.

**Comment by KomachiSion** [comment]
which version you used?

**Comment by maojing123** [comment]
> which version you used?


The current version is 1.3.0, 
but version 1.1.3 also has problems

**Comment by maojing123** [comment]
> which version you used?

If the group is DEFAULT_GROUP, you can offline normally without such a problem
如果分组是DEFAULT_GROUP 则可以正常下线不会有这样的问题

**Comment by chuntaojun** [comment]
请刷新你的页面缓存，注意和官网demo对比下页面布局，你这个页面是老得

**Comment by KomachiSion** [comment]
I try in console_demo, it can be offline currently. And no more response. Close issue.

**Comment by jojoecfy** [comment]
我的版本是1.2.1，分组后会出现和上面一样的状况，点击下线后刷新页面页面显示未下线，如果您在测试时可以下线，请问是哪个版本呢

**Comment by chinesedate** [comment]
版本1.3.2 非DEFAULT_GROUP 可以正常下线
version 1.3.2 is ok
