### ISSUE TITLE
Can nacos-config-spring-boot-starter remove fastjson?

### ISSUE THREAD

**Issue by pengyonglei** [alibaba/nacos#3043]
Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
I hope nacos-config-spring-boot-starter removes fastjson and replaces it with gson or jackson, because our project keeps alarming. Every upgrade is troublesome

我希望nacos-config-spring-boot-starter 移除fastjson, 换成gson或者jackson, 因为我们的项目一直在报警, 每次升级就很麻烦

**Comment by KomachiSion** [comment]
Nacos 1.3.0 has removed `fastjson` already. `nacos-config-spring-boot` project will release new version recently.

**Comment by KomachiSion** [comment]
@pengyonglei you can exclusion nacos-client from nacos-spring first, and manually add nacos-client 1.3.0 for temporarily.

**Comment by pengyonglei** [comment]
May I ask when nacos-spring-boot will be released? Is there an approximate time? We are about to start the project recently.

**Comment by pengyonglei** [comment]
> @pengyonglei you can exclusion nacos-client from nacos-spring first, and manually add nacos-client 1.3.0 for temporarily.

Ok, let me try it. thanks

**Comment by KomachiSion** [comment]
> May I ask when nacos-spring-boot will be released? Is there an approximate time? We are about to start the project recently.

The question should move to nacos-spring-boot project or nacos-spring-context project. It's hard for me to answer the question.

**Comment by pengyonglei** [comment]
> @pengyonglei you can exclusion nacos-client from nacos-spring first, and manually add nacos-client 1.3.0 for temporarily.

I’ve done it as you said. Thank you

**Comment by pengyonglei** [comment]
I upgraded nacos-client to version 1.3.0, but found that the autoRefreshed function is invalid, so it still does not work. I can only wait for nacos-config-spring-boot-starter to update.

**Comment by siriusxxk21** [comment]
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.3.3</version>
        </dependency>
