### ISSUE TITLE
1.2.1版本nacos怎么切换成CP模式

### ISSUE THREAD

**Issue by zhanglanzhu521** [alibaba/nacos#3045]
## Issue Description
Hello, the version I am using is 1.2.1, with 3 clusters started. How to switch to CP mode. Use the curl -x PUT ` $NACOS_SERVER: 8848 / nacos/v1 / ns/operator/switches? Entry =serverMode&value=CP' command invalid

你好，我使用的版本是1.2.1，3台集群启动。如何切换成CP模式。用curl -X PUT `$NACOS_SERVER:8848/nacos/v1/ns/operator/switches?entry=serverMode&value=CP' 命令无效
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by jzdayz** [comment]
请使用临时节点，临时节点即为AP模式

**Comment by KomachiSion** [comment]
注册服务和实例的时候 ephemeral=false即可

**Comment by JxFor** [comment]
> 注册服务和实例的时候 ephemeral=false即可

1.2.1版本 client注册的时候，ephemeral 写死是true
