### ISSUE TITLE
Enhancement for constant variables.

### ISSUE THREAD

**Issue by jzdayz** [alibaba/nacos#3046]
## Issue Description

Type: code review

### Describe what happened (or what feature you want)

I noticed that there are some magic variables in applicationUtils and PropertyUtil, can it be written in one place,it's so messy. i think all config magic variables should be one place 

![image](https://user-images.githubusercontent.com/35563513/84479897-41765e80-acc6-11ea-9342-2e89e53137c2.png)
![image](https://user-images.githubusercontent.com/35563513/84479924-4d622080-acc6-11ea-8294-ebdb979854e9.png)

### Describe what you expected to happen

If it passes, I can do this

**Comment by jzdayz** [comment]
![image](https://user-images.githubusercontent.com/35563513/84480443-29530f00-acc7-11ea-8dfa-cd6149b36ad8.png)
so messy

**Comment by jzdayz** [comment]
- plan1
```java
public interface Constants {
    class Raft{

    }

    class Nacos{
        public static String FUNCTION_MODE_PROPERTY_NAME = "nacos.functionMode";
    }

    class Web{
        public static String ACCEPT_CHARSET = "Accept-Charset";
        public static String SERVER_PORT = "server.port";
    }
}
```
- plan2
```java

public class Constants {
    public static class Raft{

    }

    public static class Nacos{
        public static String FUNCTION_MODE_PROPERTY_NAME = "nacos.functionMode";
    }

    public static class Web{
        public static String ACCEPT_CHARSET = "Accept-Charset";
        public static String SERVER_PORT = "server.port";
    }
}

```

**Comment by KomachiSion** [comment]
Looks great, but I can't get the difference between the two plan, I think plan two is more used.

If you want to do this, please pay attention to the scope of these constants.

**Comment by jzdayz** [comment]
> Looks great, but I can't get the difference between the two plan, I think plan two is more used.
> 
> If you want to do this, please pay attention to the scope of these constants.

ok i will do it

**Comment by KomachiSion** [comment]
@jzdayz Any progress？

**Comment by jzdayz** [comment]
> @jzdayz Any progress？



Sorry, in my idea, I want to put all the constants in common module, but I found that there are constant classes in different modules, so I think that if the code is modified, the range of changes will be larger. I think the code in the future It can be unified, but I dare not move the current code

**Comment by KomachiSion** [comment]
@jzdayz you can split this issue as multiple sub task. each module each task. And refactor for each module.
After all modules has finished, then to think about merge constants and unified them.

**Comment by KomachiSion** [comment]
For example:
- [ ] refactor constants in naming module
- [ ] refactor constants in config module
....
- [ ] merge and unified constants for modules.

**Comment by jzdayz** [comment]
> For example:
> 
> * [ ]  refactor constants in naming module
> * [ ]  refactor constants in config module
>   ....
> * [ ]  merge and unified constants for modules.

OK,i got this , let me think , modify one by one

**Comment by KomachiSion** [comment]
@jzdayz There is no process for a long time, I unassign this issue for you first. If you want to solve it, please relay again with new process.

**Comment by li-xiao-shuang** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
This PR has no finished. 
but it can be do with #5726 .
