### ISSUE TITLE
web端配置中心，新加的用户没有空间权限，也能查看？

### ISSUE THREAD

**Issue by liujiling1** [alibaba/nacos#3049]
In the web-side configuration center, the newly added users can view the information in other spaces without the permission to configure the space? ? ?
Is it designed like this, or is it a bug?

web端配置中心，新加的用户没有配置空间权限，也能查看其他空间的信息吗？？？
是这么设计，还是bug？

**Comment by Eternal88** [comment]
I also encountered the same problem, nacos through the new user configuration registry 403，
The configuration center does not have this problem

我也遇到相同问题，nacos 通过新用户配置注册中心报403，配置中心无这个问题

**Comment by KomachiSion** [comment]
check #3024

**Comment by chuntaojun** [comment]
1.3.0没有这个问题，你可以部署1.3.0，同时清除浏览器缓存看看

**Comment by chuntaojun** [comment]
同时确定你的权限功能已正确开启

**Comment by kitsrc** [comment]
@chuntaojun 有关于nacos web控制台用户 权限设置为 只读 但是依然可以编辑配置这个问题有在1.3.0中解决吗？还是需要一个新的issue

**Comment by chuntaojun** [comment]
可编辑，但是不能发布吧？

**Comment by liujiling1** [comment]
docker环境，升级到最新版本，1.3.0
并且
nacos.core.auth.caching.enabled=true
nacos.core.auth.enabled=true

还是所有用户都可以互相看到对方数据，无解？

**Comment by chuntaojun** [comment]
> docker环境，升级到最新版本，1.3.0
> 并且
> nacos.core.auth.caching.enabled=true
> nacos.core.auth.enabled=true
> 
> 还是所有用户都可以互相看到对方数据，无解？

请看这个文档：https://github.com/nacos-group/nacos-docker

**Comment by liujiling1** [comment]
总结下：主要还是bug，或者说体验不好
前提：docker环境，application.properties 宿主机外部化配置
1.主要是/home/nacos/bin/docker-startup.sh 里面加载配置文件路径的顺序，导致外部配置的
nacos.core.auth.enabled=true 加载不到
![image](https://user-images.githubusercontent.com/42994141/85196996-a5c19f80-b310-11ea-9ba2-5f51e9315783.png)

2.解决办法：
----正常docker新建运行nacos
----从nacos容器里把 /home/nacos/target/nacos-server.jar 拷贝出来
----用压缩文件工具修改jar包的nacos-server.jar\BOOT-INF\classes\application.properties 属性文件，
      修改nacos.core.auth.enabled=true 
----将修改的jar包替换容器里的jar包
----重启nacos

！！！再试试看权限，有权限的刷新页面就能看到，没权限的刷新也看不到

**Comment by Deathef** [comment]
刚测试了下，只有读权限的在1.3.0依然可以编辑并发布
![image](https://user-images.githubusercontent.com/32616338/85652267-cb69f280-b6dc-11ea-88ec-f8c8a3cbb61e.png)
![image](https://user-images.githubusercontent.com/32616338/85652321-fc4a2780-b6dc-11ea-8a36-7543e2f9ab70.png)
![image](https://user-images.githubusercontent.com/32616338/85652391-28fe3f00-b6dd-11ea-97cf-a7b27f488fde.png)
![image](https://user-images.githubusercontent.com/32616338/85652405-374c5b00-b6dd-11ea-8701-a5fc7d2770ba.png)

**Comment by KomachiSion** [comment]
> 总结下：主要还是bug，或者说体验不好
> 前提：docker环境，application.properties 宿主机外部化配置
> 1.主要是/home/nacos/bin/docker-startup.sh 里面加载配置文件路径的顺序，导致外部配置的
> nacos.core.auth.enabled=true 加载不到
> ![image](https://user-images.githubusercontent.com/42994141/85196996-a5c19f80-b310-11ea-9ba2-5f51e9315783.png)
> 
> 2.解决办法：
> ----正常docker新建运行nacos
> ----从nacos容器里把 /home/nacos/target/nacos-server.jar 拷贝出来
> ----用压缩文件工具修改jar包的nacos-server.jar\BOOT-INF\classes\application.properties 属性文件，
> 修改nacos.core.auth.enabled=true
> ----将修改的jar包替换容器里的jar包
> ----重启nacos
> 
> ！！！再试试看权限，有权限的刷新页面就能看到，没权限的刷新也看不到

欢迎提交PR到nacos-docker，修改配置加载顺序。

**Comment by qwerplf** [comment]
> 总结下：主要还是错误，或者说体验不好的
> 做法：docker环境，application.properties宿主机外部化配置
> 1.主要是/home/nacos/bin/docker-startup.sh里面加载配置文件路径的顺序，导致外部配置的
> nacos.core.auth.enabled = true加载不到
> ![图片](https://user-images.githubusercontent.com/42994141/85196996-a5c19f80-b310-11ea-9ba2-5f51e9315783.png)
> 
> 2.解决方法：
> ----正常docker新建运行nacos
> ----从nacos容器里把/home/nacos/target/nacos-server.jar复制出来
> ----使用压缩文件工具修改jar包的nacos -server.jar \ BOOT-INF \ classes \ application.properties属性文件，
> 修改nacos.core.auth.enabled = true
> ----将修改
> jarjar替换容器里的jar包----重新启动nacos
> 
> ！！！再试试看权限，有权限的刷新页面可以看到，没权限的刷新也看不到
好像不需要这么做！因为在/home/nacos/bin/docker-startup.sh脚本中增加了是否开启权限认证的判断，我们只需要在启动容器的时候添加一个名为“NACOS_AUTH_ENABLE”的环境变量即可开启权限认证。
![image](https://user-images.githubusercontent.com/23162792/86330613-81ec4b00-bc7a-11ea-87dd-c443e57f88fb.png)

**Comment by liujiling1** [comment]
其实docker run时增加 -e NACOS_AUTH_ENABLE=true 就开启权限了，主要是想通过外部化配置控制权限

> docker run -d --restart=always --name my-nacos -p 8848:8848 \
-e MODE=standalone \
-e NACOS_AUTH_ENABLE=true \
-v /data/docker/nacos/application.properties:/home/nacos/conf/application.properties \
-v  /data/docker/nacos/target:/home/nacos/target \
-v /data/docker/nacos/logs:/home/nacos/logs \
nacos/nacos-server:latest

**Comment by qwerplf** [comment]
> 其实docker run时增加 -e NACOS_AUTH_ENABLE=true 就开启权限了，主要是想通过外部化配置控制权限
> 
> > docker run -d --restart=always --name my-nacos -p 8848:8848 
> > -e MODE=standalone 
> > -e NACOS_AUTH_ENABLE=true 
> > -v /data/docker/nacos/application.properties:/home/nacos/conf/application.properties 
> > -v  /data/docker/nacos/target:/home/nacos/target 
> > -v /data/docker/nacos/logs:/home/nacos/logs 
> > nacos/nacos-server:latest





> 其实docker run时增加-e NACOS_AUTH_ENABLE = true就开启权限了，主要是想通过外部化配置控制权限
> 
> > docker run -d --restart =总是--name my-nacos -p 8848：8848 
> > -e MODE = standalone 
> > -e NACOS_AUTH_ENABLE = true 
> > -v /data/docker/nacos/application.properties:/home/nacos/conf/ application.properties 
> > -v / data / docker / nacos / target：/ home / nacos / target 
> > -v / data / docker / nacos / logs：/ home / nacos / logs 
> > nacos / nacos-server：latest
