### ISSUE TITLE
Registry security verification 403

### ISSUE THREAD

**Issue by Eternal88** [alibaba/nacos#3050]
## Issue Description
1.3.0 docker cluster installation, configure security verification <NACOS_AUTH_ENABLE=true>, service registration report 403 error.
Not the nacos account.

1.3.0 docker 集群安装，配置安全验证 <NACOS_AUTH_ENABLE=true>，服务注册报 403 错误。
非 nacos 账号
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([192.168.2.50:8848, 192.168.2.50:8849, 192.168.2.50:8850]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Jun 12 16:14:23 GMT+08:00 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
`unknown user!`

Please check you create user first.

For example use new user to login the console

**Comment by Eternal88** [comment]
The new user is logged in to the console。
You can get the configuration center information,Service registration is not possible

**Comment by KomachiSion** [comment]
Can you try add `NACOS_AUTH_CACHE_ENABLE` and retry.
Like #3024

**Comment by KomachiSion** [comment]
And change your title so that others can search it friendly.

**Comment by KomachiSion** [comment]
Refer to #2945
