### ISSUE TITLE
Docker cluster configuration external mysql is invalid

### ISSUE THREAD

**Issue by Eternal88** [alibaba/nacos#3051]
## Issue Description
Install nacos in docker cluster, configure external Mysql to modify env/nacos-hostname.env <MYSQL_SERVICE_HOST>, and the log always prompts Mysql to connect to the host IP

docker 集群安装nacos,配置外部Mysql 修改 env/nacos-hostname.env  <MYSQL_SERVICE_HOST> ,日志一直提示MySQL连接地址为宿主机IP

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by paderlol** [comment]
宿主机地址？MYSQL_SERVICE_HOST 你配置的宿主机地址 还是？

**Comment by Eternal88** [comment]
MYSQL_SERVICE_HOST  配置的外部服务器地址，不是宿主机地址。启动日志提示的mysql连接是宿主机地址

**Comment by paderlol** [comment]
我这边测试不会有这个情况，你可以试下删除容器重新up一下

**Comment by Eternal88** [comment]
好的，我在试一下

**Comment by paderlol** [comment]
还有确认下你启动引用的是hostname.env

**Comment by Eternal88** [comment]
### Tell us your environment
docker 19.03.5
nacos  1.3.0   集群模式
Ubuntu 18.1
### How to reproduce it (as minimally and precisely as possible)
1. git clone https://github.com/nacos-group/nacos-docker.git
2. update nacos-hostname.env
```
#nacos dev env
PREFER_HOST_MODE=hostname
NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
MYSQL_SERVICE_HOST=xx.xx.2.63
MYSQL_SERVICE_DB_NAME=nacos_config
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=XX
MYSQL_SERVICE_PASSWORD=XX
NACOS_AUTH_ENABLE=true
NACOS_AUTH_CACHE_ENABLE=true
```
3. docker-compose -f example/cluster-hostname.yaml up  
cluster-hostname.yaml 删除了 mysql 镜像

### start.out
```
Caused by: java.sql.SQLException: Access denied for user 'admin'@'xxx.xxx.2.50' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
```

日志的mysql 地址 50是宿主机的，不是配置的63的地址

**Comment by paderlol** [comment]
不要看这个，两个问题，第一个你密码是否正确，第二你有没有创建表，你用外置数据库需要自己创建表

**Comment by Eternal88** [comment]
1. 我配置mysql地址是63的，日志显示是50的，而50的服务器上是没有mysql的
2.表有创建，nacos-mysql.sql 导入的这个脚本。

**Comment by paderlol** [comment]
那就不知道了，你们自己是不是本地配置了hosts

**Comment by Eternal88** [comment]
没有配置，直接IP访问的，容器内部也可以直接ping通63的服务器

**Comment by Eternal88** [comment]
试过直接修改 build 下面的 properties 的mysql 配置，在build docker 镜像也是不行的

**Comment by paderlol** [comment]
我这边测试了好几种，都没你这个问题，很多用户也用的外置数据库，暂时我也没有更好的办法

**Comment by paderlol** [comment]
你可以exec it进容器确定下你的环境变量是你的外置ip ，用echo $MYSQL_SERVICE_HOST

**Comment by Eternal88** [comment]
我通过env 添加 <SPRING_DATASOURCE_PLATFORM=mysql> 成功了，直接 clone **nacos-docker** 项目 hostname 没有<SPRING_DATASOURCE_PLATFORM> 这个环境，不知道是不是和这个变量有关系

**Comment by paderlol** [comment]
这个是单机用的

**Comment by Eternal88** [comment]
加了这个是成功了，我取消在试试看

**Comment by Eternal88** [comment]
删掉这个变量也成功。
非常感谢你为我解决问题
