### ISSUE TITLE
EmbeddedStoragePersistServiceImpl  and ExternalStoragePaginationHelperImpl use “+=”   to concatenated String, will cause performance  issue

### ISSUE THREAD

**Issue by showkawa** [alibaba/nacos#3056]
## Issue Description
*bug report* - performance  issue

### Describe what happened (or what feature you want)
com.alibaba.nacos.config.server.service.repository.EmbeddedStoragePersistServiceImpl 
and
com.alibaba.nacos.config.server.service.repository.ExternalStoragePaginationHelperImpl
use “+=”   to concatenated String, will cause performance  issue
### Describe what you expected to happen 
 use StringBuilder will be better, and i will handle it 

### How to reproduce it (as minimally and precisely as possible)

1. replace "+=" to StringBuilder append  method
2. 
3.

**Comment by showkawa** [comment]
@i will solve it@

**Comment by chuntaojun** [comment]
Simplify the label of issue
