### ISSUE TITLE
useLocalCache properties change true to false not effect

### ISSUE THREAD

**Issue by lchpersonal** [alibaba/nacos#3059]
Nacos 1.3.0 版本使用配置中心功能，测试时发现useLocalCache由false改为true可以生效，但是从true改为false就不实时生效了。这个bug是必现的。并且是配置里仅有useLocalCache一条配置才会出现，如果由多个配置，试了是可以的怎么修改都可以。
--------------------------------------------------------------------------------------------------------------
Nacos 1.3.0 uses the configuration center function. During the test, it is found that changing useLocalCache property from false to true takes effect, but changing from true to false does not take effect in real time. This bug is inevitable. In addition, only one configuration of uselocalcache will appear in the configuration. If there are multiple configurations, you can modify them as you try.

**Comment by lchpersonal** [comment]
我是从master分支拉取的代码自己编译的，不是直接下载的1.3.0的release版本

**Comment by lchpersonal** [comment]
nacos-config-spring-boot-starter 版本是0.1.4

**Comment by ljhrot** [comment]
@lchpersonal 你好，请你下载最新版本的 nacos ( 1.3.2 ) 再尝试一遍。

我根据目前提供的信息使用 nacos ( 1.3.0 )，nacos-config-spring-boot-starter ( 0.1.4 ) **无法复现**，我使用的客户端工程为 [nacos-spring-boot-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-boot-example/nacos-spring-boot-config-example)

我尝试复现的步骤（确认只有 `useLocalCache` 这一条配置）：
1. 启动 nacos 1.3.2
2. 启动 nacos-spring-boot-config-example
3. 执行 `curl http://localhost:8080/config/get` 返回 `false`
3. 执行 `curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=example&group=DEFAULT_GROUP&content=useLocalCache=true"` 返回 `true`
4. 执行 `curl http://localhost:8080/config/get` 返回 `true`
5. 执行 `curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=example&group=DEFAULT_GROUP&content=useLocalCache=false"` 返回 `true`
6. 执行 `curl http://localhost:8080/config/get` 返回 `false`

如果能再次复现，麻烦你写出具体的复现步骤，感谢！

**Comment by KomachiSion** [comment]
Thanks @ljhrot .

There are no response from author. We think the problem has solved in latest version. Close issue.
