### ISSUE TITLE
控制台 服务列表->详情 出现空白页面

### ISSUE THREAD

**Issue by Jnoee** [alibaba/nacos#306]
0.4.0版本，QQ浏览器极速模式和Edge，都会出现点击“详情“后出现空白页面，回退后服务列表页面也变成了空白页面，刷新后服务列表页面可显示。不是每次都出现，有时是好的就一直是好的，有时空白页面就一直是空白页面，刷新什么的都没用。

**Comment by nkorange** [comment]
@Jnoee Chrome是否有问题？

**Comment by Jnoee** [comment]
我装了一个chrome，也是同样的问题，版本 70.0.3538.102（正式版本）64位。
浏览器给出的异常时：index.js:1 TypeError: Cannot convert undefined or null to object
