### ISSUE TITLE
配置文件为cloud-alibaba-config-nacos-client-${spring.profile.active}，会一直刷日志而且很快

### ISSUE THREAD

**Issue by Ryze-Zhao** [alibaba/nacos#3065]
1、版本：Nacos1.3.0与1.2.1

2、问题描述：如果我的服务名称及配置文件为cloud-alibaba-config-nacos-client-dev.yaml时，会不停刷日志（下面有图3.3），但是如果将服务名称及配置文件改为其他名称，如cloud-alibaba-config-nacos-client1-dev.yaml时，不会一直刷了

3、图示：
3.1、nacos配置
![微信截图_20200615104125](https://user-images.githubusercontent.com/38486503/84613008-d1015480-aef4-11ea-97ba-0c78e7207cad.jpg)

3.2、服务名称为：cloud-alibaba-config-nacos-client，环境为：dev
![微信截图_20200615104341](https://user-images.githubusercontent.com/38486503/84613120-1c1b6780-aef5-11ea-865c-9e6c88fb8a8c.jpg)

3.3、启动结果（一直刷，配置是可以读取到的）
![微信截图_20200615104436](https://user-images.githubusercontent.com/38486503/84613173-466d2500-aef5-11ea-9b49-d41d8d5f7d53.jpg)

3.4、服务名称为：cloud-alibaba-config-nacos-client1，环境为：dev（仅仅多加一个1）
![微信截图_20200615104535](https://user-images.githubusercontent.com/38486503/84613226-67357a80-aef5-11ea-8b18-e1e4c4ac2918.jpg)

3.5、启动结果（这样就不会刷了，配置是可以读取到的）
![微信截图_20200615104716](https://user-images.githubusercontent.com/38486503/84613319-9a780980-aef5-11ea-87b7-e06e3dcb1e75.jpg)

4、想请教各位具体是我那步做错导致的问题，如何解决？3Q

**Comment by chuntaojun** [comment]
1.3.0重新下载部署，或者不要使用默认的单机模式，使用单机+mysql模式

**Comment by zhutx** [comment]
同样的问题，解决了吗？

**Comment by Ryze-Zhao** [comment]
准备搭建集群+mysql，尝试尝试！

**Comment by cealiu** [comment]
单机加mysql使用没有出现这个问题

**Comment by Ryze-Zhao** [comment]
> 单机加mysql使用没有出现这个问题

谢谢，的确加了MySQL就没这个问题了，无论Nacos是单机还是集群的

**Comment by Ryze-Zhao** [comment]
> 同样的问题，解决了吗？

加MySQL即可

**Comment by github24518** [comment]
提高nacos日志级别就可以解决这个问题。logback.xml
   <logger name="com.alibaba.nacos.client" level="${com.alibaba.nacos.config.log.level:-warn}"
      additivity="false">
      <appender-ref ref="STDOUT"/>
      <appender-ref ref="FILE"/>
    </logger>
  
    <logger name="com.alibaba.nacos.client.config" level="${com.alibaba.nacos.config.log.level:-warn}"
      additivity="false">
      <appender-ref ref="STDOUT"/>
      <appender-ref ref="FILE"/>
    </logger>
