### ISSUE TITLE
AP模式下走distro协议同步数据，为什么集群还是会有leader和follower的角色区分？以及如何切换模式？

### ISSUE THREAD

**Issue by chongli-j** [alibaba/nacos#3066]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
集群内部还有需要使用CP协议进行数据存储的，AP以及CP是同时在运行的

**Comment by chongli-j** [comment]
> 集群内部还有需要使用CP协议进行数据存储的，AP以及CP是同时在运行的

感谢您的回复。

**Comment by chongli-j** [comment]
> 集群内部还有需要使用CP协议进行数据存储的，AP以及CP是同时在运行的

感谢您的及时回复！
还想问一下，如果同时运行，service注册上去哪种模式是在客户端进行控制吗？客户端配置文件的参数好像没有Ephemeral。

**Comment by KomachiSion** [comment]
> > 集群内部还有需要使用CP协议进行数据存储的，AP以及CP是同时在运行的
> 
> 感谢您的及时回复！
> 还想问一下，如果同时运行，service注册上去哪种模式是在客户端进行控制吗？客户端配置文件的参数好像没有Ephemeral。

注册实例的时候，才有ephemeral参数

**Comment by chongli-j** [comment]
> > > 集群内部还有需要使用CP协议进行数据存储的，AP以及CP是同时在运行的
> > 
> > 
> > 感谢您的及时回复！
> > 还想问一下，如果同时运行，service注册上去哪种模式是在客户端进行控制吗？客户端配置文件的参数好像没有Ephemeral。
> 
> 注册实例的时候，才有ephemeral参数

**Comment by chongli-j** [comment]
> > > 集群内部还有需要使用CP协议进行数据存储的，AP以及CP是同时在运行的
> > 
> > 
> > 感谢您的及时回复！
> > 还想问一下，如果同时运行，service注册上去哪种模式是在客户端进行控制吗？客户端配置文件的参数好像没有Ephemeral。
> 
> 注册实例的时候，才有ephemeral参数

客户端启动注册实例到时候，ephemeral默认都是true，我想知道怎么注册持久化实例？是通过sever端的配置呢还是客户端配置？

**Comment by KomachiSion** [comment]
目前 客户端没有直接设置ephemeral的接口，暂时需要自定义创建`Instance` 将ephemeral设置为true，然后注册。

```
Instance instance = new Instance();
instance.setIp(ip);
instance.setPort(port);
instance.setWeight(1.0);
instance.setEphemeral(false);
NamingService.registerInstance(serviceName, instance);
```

**Comment by chongli-j** [comment]
> 目前 客户端没有直接设置ephemeral的接口，暂时需要自定义创建`Instance` 将ephemeral设置为true，然后注册。
> 
> ```
> Instance instance = new Instance();
> instance.setIp(ip);
> instance.setPort(port);
> instance.setWeight(1.0);
> instance.setEphemeral(false);
> NamingService.registerInstance(serviceName, instance);
> ```

非常感谢
有个小小的建议，目前很多issue其实都是咨询性质的，虽然有标注I f you're looking for help, please check our mail list、WeChat group and the Gitter room. 但是没有找到微信群，上面钉钉群二维码已经失效，gitter也不是很活跃。建议能有答疑的区域开放出来。
然后对于例如AP/CP模式、raft/distro协议这类相对核心的原理，希望能有个简单的官方文档说明。
再次感谢。

**Comment by KomachiSion** [comment]
We will try to update document and the link of group.
