### ISSUE TITLE
Multi-DC support

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#307]
描述：
      目前我们需要在我们多数据中心中搭建nacos集群，  计划每一数据中心搭建一个nacos集群， 集群之间通过skywalker(nacos-sync)进行数据同步。 
      搭建过程中，我们遇到几个问题
1. 业务方使用sdk，如何知道自己应该往哪个集群注册和获取数据， 为了尽量简化业务方配置，是否应该需要有一个单独的服务， 去通过本地ip获取当前数据中心对应的nacos集群，  nacos这边会不会有计划开源相应的组件
1. 我们存在多地配置同步发布的功能，  nacos这边是否会在sdk内提供类似的功能， 还是需要另外封装一个server来进行同步发布管理
1. 边缘节点支持。  一些非数据中心的边缘机房， 自身并不会搭建nacos集群，  但同样也会有配置和服务发现的需求， 所以需要连接到相邻的数据中心的nacos集群。 这里会有两个需求， 一个边缘节点是如何获取到最近的nacos集群的地址， 类似问题1， 另外一个是这里有些连接走的是公网， 网络环境不可控，如何保证服务的可用性，  是否应该在边缘机房部署一个proxy组件， 统一通过这个组件连接到nacos集群， 同时一些配置和服务的信息可以缓存在这个节点， 减少网络问题的影响。  同时想了解一下nacos这边是否有计划开源类似的组件
1.  web console是否会支持多集群管理。 主要有两个场景， 不同集群各自的管理，  服务和配置的多集群同步， 是否会考虑将部分nacos-sync的功能集成过去

**Comment by yangyshdan** [comment]
一一回答下。
 - 第一个问题  这块建议的场景是：
      - 一个数据中心一个Nacos，同时配置一个NacosSync
      - 每个NacosSync只需要手动配一次所有NacosSync集群即可。
      - 比较建议的玩法是，本地NacosSync负责拉远端的Nacos集群，同步到本地服务。
      - 以上，从业务逻辑上看，其实NacosSync只需要初始化一次配置即可。
 - 配置同步发布功能，NacosSync暂不考虑支持这块。主要还是因为配置发布是发布一次发布端即可离线，和服务注册这种需要在线同步的情况并不一样，因此没有考虑做到NacosSync。
 - 关于第三个问题，首先是服务发现问题，有一个比较土的办法，同一Region的所有机器配置一样的/etc/hosts的某个nacos集群的域名解析，但是不同region间不同。Proxy暂未设计，但是可以通过增强Nacos SDK增加本地缓存来解决，即服务端当不可用时，优先读缓存保证服务信息。
 - 可以增开一个issue来讨论。这是一个好主意，可以有一个统一console来处理。这块可能暂时再V0.8以后再考虑

**Comment by yangyshdan** [comment]
建议这块你们可能先自己做一下，我们后面吧0.8版做了以后后面会再考虑这块。

这边记录下可能需要考虑的点，供你们参考:
1. console上加入配置的记录，当用户选择多DC发布的时候，需要知道将记录记录在数据库中。
2. 下次用户改配置的时候，要先在console让用户确认，这是一个多DC的记录，确认是否多DC同步发。
3. 如果某原因造成发布失败，一定要让提示用户配置没有同步发布，是否需要回滚配置。

**Comment by pguo65535** [comment]
这块另外一块主要是要考虑  DC/Available Zone/Region  逻辑概念 和 Nacos物理集群 Mapping的推荐实践是什么

**Comment by pguo65535** [comment]
我们的 Address Server Mode 这块也需要抽象和规划一下了，这块以前有过一些讨论。
