### ISSUE TITLE
配置中心集群模式，使用embedded storage模式，集群节点间的配置数据的同步原理是什么

### ISSUE THREAD

**Issue by eazeZhou** [alibaba/nacos#3070]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

集群模式，使用embedded storage模式，集群之间各节点的配置数据是如何同步的呢？请大佬指教

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
你说的配置数据指的是什么的配置？

**Comment by chuntaojun** [comment]
https://nacos.io/zh-cn/blog/nacos-1.3.0-design.html
