### ISSUE TITLE
feature: Set config type when publishConfig in the NacosConfigService

### ISSUE THREAD

**Issue by lsw1991abc** [alibaba/nacos#3072]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
cant set the config `type` when publish config in the `NacosConfigService.java` by `nacos-client`

### Describe what you expected to happen
add `extendFields` parameter in the `publishConfig` method for custom parameters

**Comment by KomachiSion** [comment]
Refer to #2660
