### ISSUE TITLE
权限无效

### ISSUE THREAD

**Issue by taoxiaoyin** [alibaba/nacos#3080]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 我创建两个用户test,dev,同时赋予了权限test看test的命名空间，dev看dev的
然后使用test登录之后依旧能看见dev的配置文件
2. 
3. 

### Tell us your environment
1.2.1的版本

**Comment by KomachiSion** [comment]
docker env? 
see #3024

**Comment by taoxiaoyin** [comment]
我设置了。nacos.core.auth.enabled=true，和nacos.core.cacheing.enabled=true都是true了
但是还是有错误
<img width="325" alt="auth" src="https://user-images.githubusercontent.com/3125643/84725648-afb86b00-afbd-11ea-9ef1-0b1ebd349140.png">

**Comment by taoxiaoyin** [comment]
<img width="325" alt="auth" src="https://user-images.githubusercontent.com/3125643/84725690-c363d180-afbd-11ea-9a86-1a95ae5f88be.png">

**Comment by taoxiaoyin** [comment]
<img width="325" alt="auth" src="https://user-images.githubusercontent.com/3125643/84725726-da0a2880-afbd-11ea-9fa7-cd0e2bb65c96.png">

**Comment by taoxiaoyin** [comment]
ailed to req API:/api//nacos/v1/ns/instance after all servers([10.12.102.184:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Jun 16 10:01:12 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
代码启动也有这个错误

**Comment by taoxiaoyin** [comment]
https://user-images.githubusercontent.com/3125643/84722585-3406f000-afb6-11ea-81c0-7f32a2c833a2.png

**Comment by taoxiaoyin** [comment]
[https://user-images.githubusercontent.com/3125643/84722585-3406f000-afb6-11ea-81c0-7f32a2c833a2.png](url)

**Comment by MsencSir** [comment]
1.2.1 版本不支持权限功能

**Comment by taoxiaoyin** [comment]
1.3.0也一样的错误，我试了一个，是因为没有给public只读的权限。建议，如果没有读的权限，这个命名空间可否就不显示？一点就错授权失败，就使用不了

**Comment by Force-King** [comment]
确实权限无效，给了用户只读权限，但是登录还显示 编辑 和 删除 按钮，用的是最新版

**Comment by imyxiao** [comment]
使用docker创建的nacos，给了用户只读权限，但是登录还显示 编辑 和 删除 按钮

**Comment by KomachiSion** [comment]
可以看到是正常的，按钮也是正常的，只是操作的时候会返回错误

**Comment by taoxiaoyin** [comment]
建议做个优化，
1.没有权限的命名空间不要显示，目前会显示，然后点击就直接报错，报错之后就需要刷新，无法使用
2.配置文件中，无需增加帐号和密码，现在开始权限之后，配置文件就必须要配置帐号信息，导致管理平台的帐号需要暴露了

**Comment by KomachiSion** [comment]
duplicate #2945 .

**Comment by Force-King** [comment]
nacos1.3.0-Beta
开启了权限配置
```
nacos.core.auth.enabled=true
nacos.core.cacheing.enabled=true
```  
我试了，控制台权限可以起作用了，但是每次点击给定权限的命名空间，需要手动刷新才能展示。
但是项目连不上nacos注册中心。
项目启动报错如下：
`com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Jun 22 11:29:27 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>`

application.yml 配置如下：

```
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.com
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        group: DEFAULT_GROUP
        file-extension: properties
        username: nacos
        password: nacos
        contextPath: /nacos
```
maven pom.xml配置：
```
<dependencyManagement>
        <dependencies>
            <!-- spring-cloud -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Greenwich.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--Spring Cloud Alibaba-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>1.2.1</version>
            </dependency>
      </dependencies>
</dependencyManagement>
<dependencies>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </dependency>
        <!-- Nacos Discovery -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
</dependencies>
```
请问是我的配置问题有问题吗？ 还是还需增加什么配置？ 谢谢！
