### ISSUE TITLE
Data synchronization failure trigger retry logic description

### ISSUE THREAD

**Issue by pengzhengfa** [alibaba/nacos#3081]
In the original data synchronization retry logic, if the failure triggers the retry logic, it will retry every 5S in the original logic, which will inevitably affect the performance of the server,
I read the Eureka source code and use Alipay callback idea to count the number of retrial requests during the first retry. Every time the retry time is incremented on the original basis,
When the number of retries reaches 10, throw an exception, record the log, and try to retry all the time, which will inevitably affect the performance of the server,
At the code logic level, the number of retries is counted by an atomic type counter, and the time interval of retries is also increasing,
In this way, the performance of the server will not be affected by frequent retries. The purpose of throwing exception log is to facilitate subsequent manual processing. Why should I choose this solution instead of a third-party retry framework,
If you choose another retry framework, it will invade the code to some extent, which may lead to serious bugs in other functions

**Comment by pengzhengfa** [comment]
@KomachiSion Hello, please check

**Comment by KomachiSion** [comment]
Hi @pengzhengfa, I think there are no need to enhance this part. reason follow:
1. the syncTask only happen in something changes, if many changes in an interval time(default 5s), they will be merged by `service`.
2. If syncTask failed , which means that other nacos node has different data. We want to sync data quick to reduce the time windows of data difference. If you multiple interval time, which will add the risk of data difference, and may caused many clients need to register again in short time.
3. We are planing to use long-connection like gRPC to enhance, which may refactor this part totally.

**Comment by pengzhengfa** [comment]
@KomachiSion OK, thank you. Please refuse or close this request
