### ISSUE TITLE
Fix bug-login 403 when using conflict commons-codec version

### ISSUE THREAD

**Issue by huzhengnan** [alibaba/nacos#3085]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
login 403 when using commons-codec 1.4
throw a class not found exception and been cached and ignored

### How to reproduce it (as minimally and precisely as possible)

1. use commons-codec 1.11
2. 
3. 

### Tell us your environment
1.3.0 and below

**Comment by KomachiSion** [comment]
It's may be a dependency conflict for your application. We will not suggest you to change dependence package, which not test fully and may cause more problem.

**Comment by huzhengnan** [comment]
`
`

**Comment by huzhengnan** [comment]
codec 1.4 change `Charset` class name to `CharEncoding` [CODEC-278 Deprecate Charset constants in org.apache.commons.codec.Charsets in favor of java.nio.charset.StandardCharsets](https://issues.apache.org/jira/browse/CODEC-278). this dependency conflict will get a confusing 403 login error because of ignored throwable. (Maybe some other people got the same 403 for this reason ?)
```
package com.alibaba.nacos.client.security;
public class SecurityProxy {
    public boolean login(String server) {
...
    // this line will throw a class not found exception when login
    HttpClient.HttpResult result = HttpClient.request(url, new ArrayList<String>(2),
                params, body, Charsets.UTF_8.name(), HttpMethod.POST);

...
    }
}
```


```
package com.alibaba.nacos.client.security;
public class SecurityProxy {
    public boolean login(List<String> servers) {
...
        for (String server : servers) {
            if (login(server)) {
                 lastRefreshTime = System.currentTimeMillis();
                     return true;
               }
            }
        } catch (Throwable ignore) {
             // do nothing and return false
        }
...
       return false;
    }
}
```

**Comment by KomachiSion** [comment]
Which version are you used?

**Comment by huzhengnan** [comment]
Inappropriate dependence of old codec version. closed. thanks
