### ISSUE TITLE
nacos console's refreshing bug

### ISSUE THREAD

**Issue by zoscargit** [alibaba/nacos#3089]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
After one instance is registered，if you modify the Service Group name in its Configuation Set， the refreshing works in this instance, but Service Group name of this instance isn’t refreshed on the nacos console dashboard. Now if you start another instance with original Service Group name，the two instance will be included in the original Service Group on the nacos console dashboard, but actually they are not in the same group.

### Describe what you expected to happen
When the Service Group name in its Configuation Set is modified，it is necessary that the NacosContextRefresher sends a request to Nacos Server for updating the serviceMap.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>
<spring-cloud.version>Hoxton.SR1</spring-cloud.version>

**Comment by KomachiSion** [comment]
How can you update service group? It should not be changed, if your want to change to other group, you need to register with new group name again.

**Comment by zoscargit** [comment]
> 
> 
> How can you update service group? It should not be changed, if your want to change to other group, you need to register with new group name again.

Thank you for your reply. 
I'm studying spring-cloud-alibaba. Suppose that a service is used for supplying some kind of computing capability. I divide this service instances into three group, group A for business A，group B for business B， group C for frequently switching between group A and B to enhance their computing capability on schedule. So dynamic group switching is suitable in this situation. 
Since the Service Group can be changed in nacos console，I think nacos project should develop a standard for users to implement the function of updating the service instance group or make dynamic group switching disabled.

**Comment by KomachiSion** [comment]
I see, It may be a new feature. We need to discuss when and how to implement it.

**Comment by KomachiSion** [comment]
You can close this issue and create a new issue set type : feature.
Then refer this issue and describe the feature you wanted.
