### ISSUE TITLE
Deploying AddressServer reported an error and could not start

### ISSUE THREAD

**Issue by metaphysical-road** [alibaba/nacos#3091]
Description:

Field authManager in com.alibaba.nacos.core.auth.AuthFilter required a bean of type 'com.alibaba.nacos.core.auth.AuthManager' that could not be found.

The injection point has the following annotations:
  - @org.springframework.beans.factory.annotation.Autowired(required=true)
Action:

Consider defining a bean of type 'com.alibaba.nacos.core.auth.AuthManager' in your configuration

**Comment by metaphysical-road** [comment]
> Description:
> 
> Field authManager in com.alibaba.nacos.core.auth.AuthFilter required a bean of type 'com.alibaba.nacos.core.auth.AuthManager' that could not be found.
> 
> The injection point has the following annotations:
> 
> * @org.springframework.beans.factory.annotation.Autowired(required=true)
>   Action:
> 
> Consider defining a bean of type 'com.alibaba.nacos.core.auth.AuthManager' in your configuration

I can fix the the problem

**Comment by KomachiSion** [comment]
How are you start server? Start in IDE?

**Comment by metaphysical-road** [comment]
After packaging, the system starts

Packaged command
sudo mvn -P release-address clean install -Dmaven.test.skip=true

Generate jar  nacos-address-server.tar.gz

Start command
sh bin/startup.sh -s nacos-address

**Comment by metaphysical-road** [comment]
> How do you start server? Start in IDE?

After packaging, the system starts

Packaged command
sudo mvn -P release-address clean install -Dmaven.test.skip=true

Generate jar nacos-address-server.tar.gz

Start command
sh bin/startup.sh -s nacos-address
