### ISSUE TITLE
ribbon-discovery-filter-spring-cloud-starter冲突

### ISSUE THREAD

**Issue by ptlive1001** [alibaba/nacos#3092]
<dependency>
            <groupId>io.jmnarloch</groupId>
            <artifactId>ribbon-discovery-filter-spring-cloud-starter</artifactId>
            <version>2.1.0</version>
 </dependency>

如上，加入上述引用，导致LoadBalancerClient 无法获取到已注册的服务

**Comment by KomachiSion** [comment]
Please see #2885 . Is it the same problem?

**Comment by ptlive1001** [comment]
不是同一个问题
`
<dependency>
            <groupId>io.jmnarloch</groupId>
            <artifactId>ribbon-discovery-filter-spring-cloud-starter</artifactId>
            <version>2.1.0</version>
</dependency>
`
加上以上引用后，从nacos获取已注册的服务，就获取不到。

**Comment by KomachiSion** [comment]
那可能是bean冲突了，这不属于nacos的问题。bean冲突需要用户自己解决。
