### ISSUE TITLE
dynamic Service Group refreshing

### ISSUE THREAD

**Issue by zoscargit** [alibaba/nacos#3097]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Please refer to the following issue，thanks
#3089 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
@zoscargit Please add detail description about your feature. Otherwise others can't understand.

**Comment by chuntaojun** [comment]
I don't think this is a necessary feature. ServiceName +group is the only representation. If you change the grouping of the services, it means that all instances of the service will be migrated to the new grouping

**Comment by chuntaojun** [comment]
I have looked at the context of the original problem, which is the code design problem of Spring-cloud-Alibaba. Because you configure the refresh, you will re-register, but the service instance registered before is not offline, so one instance is registered under two serviceName+group. The nacos itself does not support the refresh of service grouping

**Comment by chuntaojun** [comment]
I think it would be more appropriate to call this feature the service where the dynamic change instance resides

**Comment by chuntaojun** [comment]
@KomachiSion Do you think this is more relevant to his scene

**Comment by KomachiSion** [comment]
In my option, It's not necessary to implement this feature, one instance register to provide service for one group once, it should provide for the group in the life cycle. If want to provide for other groups, it should un-register and register to other group.

**Comment by KomachiSion** [comment]
More than one month no discussion from community, and from the comment before, we think the feature is not reasonable. So close issue, thanks for your advise.
