### ISSUE TITLE
Is the opensource version has support session cluster and data cluster?

### ISSUE THREAD

**Issue by Viyond** [alibaba/nacos#31]
我想请问下，目前开源的这个版本是否已经支持将服务端集群拆分为会话集群和数据集群了。
======================================
Excuse me, I just want to know if the current opensource version has support the server cluster to be divided into two seperated cluster, as session cluster and data cluster, if not, do you have a future plan.

**Comment by pguo65535** [comment]
No, by Nacos 1.0 we current have no plan to support seperating the cluster to session cluster and data cluster,  as we think

1. keep easy-to-use(i.e setup clusters, operate just one cluster...) is more valuable than to support large service scale for most open source users
2. we think DNS-Based Service Discovery is the future in cloud native era, i.e. make it more easier to integrate with k8s or service mesh and multi-programming language stack in public cloud environment
