### ISSUE TITLE
nacos做dubbo的注册中心同一个服务器上同一个nacos做dubbo的注册中心同一个服务器上同一个生产者不能存在两个消费者

### ISSUE THREAD

**Issue by xiaotudoudenaiba** [alibaba/nacos#3100]
It is like deploying Weixin module, push module and service module on the same server. Both the push module and the service module call the Weixin module. If the push module is released first, the service module cannot be registered. Anyway, only one module can be registered. There is no conflict between ports. If the push module and the service module are not placed on the same server, there is no problem.

如同将同一个服务器上部署weixin模块，push模块，服务模块。push模块和服务模块都要调用weixin模块。如果先发布push模块，服务模块就注册不上，反正就是只能注册一个模块，端口什么的都没有冲突，如果把push模块和服务模块不放到同一台服务器上就没有问题。

**Comment by xiaotudoudenaiba** [comment]
把上面说的3个服务的dubbo的缓存文件都整合到同一个文件，上面的3个服务在同一个服务器上没有问题。但是nacos中weixin模块的消费者只有一个。本应该push模块和服务模块两个消费者

**Comment by KomachiSion** [comment]
我读了3遍 还没没太读懂。。。

意思就是1个服务和2个订阅者同时处在一个服务器下面（ip一直，端口不一致），然后服务可以顺利书册，但是消费者只能注册上一个？

**Comment by KomachiSion** [comment]
No response more than 7 days. Close issue
