### ISSUE TITLE
can't save properties config

### ISSUE THREAD

**Issue by gz-yami** [alibaba/nacos#3103]
version **1.3.0 release**

if properties like this: 

```
# port
server.port=8762
```

it will not work

chrome console error "Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined"

chinese:
properties 文件，有 "#" 注释的时候，就保存不了，控制台报错。"Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined" 

写个配置文件的时候有注释很正常呀，以前是可以的，所以认为这个是一个挺影响使用的bug。

**Comment by KomachiSion** [comment]
I try ti reproduce in 1.3.0 console demo, but failed. 

http://console.nacos.io/nacos/index.html#/configeditor?serverId=center&dataId=application-dev.yml&group=DEFAULT_GROUP&namespace=&edasAppName=&edasAppId=&searchDataId=&searchGroup=

**Comment by KomachiSion** [comment]
It may be a console bug.

**Comment by gz-yami** [comment]
> It may be a console bug.

add a new config, choose format 'properties'

use
```
# port
server.port=8762
```

if you add a new properties, It will reappear.  properties config can't save

if you update old properties, It will not reproduce.  properties config can update

chinese:
1. 新下载一个最新的 **1.3.0 release** 启动， 输入账号密码，进入“配置管理 - 配置列表 - 页面有个加号按钮，点击新建” 

新建一个配置文件，选格式为  'properties' 

输入
```
# 端口
server.port=8762
```

控制台就会报错，没有保存办法。

如果用编辑的话，是没有问题的。

**Comment by metaphysical-road** [comment]
这个在1.2.1也存在这样的问题
This problem also exists in 1.2.1

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/3173

**Comment by z589533** [comment]
这个问题一直存在，难道不打算搞好了？1.3.1也是一样

**Comment by chenhj520** [comment]
![Uploading image.png…]()

NewConfig.js  文件中 aliwareIntl对象从globalLib.js 引用，但是globalLib.js文件没有定义aliwareIntl对象。
import { getParams, setParams, request, aliwareIntl } from '../../../globalLib';

问题修复，有两处需要修改
```

       let currentLanguageCode = 'zh-cn';
        if (typeof aliwareIntl.currentLanguageCode !== 'undefined') {
          currentLanguageCode = aliwareIntl.currentLanguageCode || 'zh-cn';
        }
        Dialog.confirm({
          content: locale.confirmSyanx,
          language: currentLanguageCode,
          onOk: () => {
            this.publicConfigBeforeCheck(content);
          },
        });
```

**Comment by ljhrot** [comment]
@i will solve it@

**Comment by zongtanghu** [comment]
It's yours. @ljhrot

**Comment by ljhrot** [comment]
@zongtanghu Ok

**Comment by zongtanghu** [comment]
Okay, thanks your contribution.

**Comment by zongtanghu** [comment]
@ljhrot  any progress?

**Comment by ljhrot** [comment]
@ready to close@
