### ISSUE TITLE
feature request [WeeklyReport]  is an excellent output, please continue

### ISSUE THREAD

**Issue by ArkEvent** [alibaba/nacos#3105]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
feature request [WeeklyReport]  is an excellent output, please continue

issue 区域 [WeeklyReport] 个人觉得这是一个非常优秀的输出点，请求继续保持，谢谢

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
There was a robot to output the weekly report, translate issue and tag issue.
But the robot transfer from free to charges, Nacos community do not renew, so the robot stopped.
