### ISSUE TITLE
nacosV1.3.0集群问题

### ISSUE THREAD

**Issue by gfgfggf1988** [alibaba/nacos#3110]
nacos部署一主两从集群模式，当从节点出现宕机后，主从之间频繁发送心跳请求。通过curl调用beat的api无法获取到正常节点的返回值，此时注册的应用在服务器中kill掉，在nacos的监控器中不能正常下线。依然显示应用健康状态为正常，此时客户端负载调用注册的服务接口会出现调用不成功的问题

**Comment by KomachiSion** [comment]
请提供更多信息，比如接口调用不成功的报错（客户端和服务端），频繁心跳的日志等

**Comment by gfgfggf1988** [comment]
![nacosV1 3 0集群模式](https://user-images.githubusercontent.com/16377180/85126850-dcd87800-b260-11ea-9113-1d9f76e913b8.png)
当集群模式下，某一个从节点挂掉后，在主节点的服务器中查看naming-server.log会看见每5秒打印
![image](https://user-images.githubusercontent.com/16377180/85126916-02658180-b261-11ea-83f0-19de4cd6cb98.png)
此时，对注册的服务比如ABC，通过kill -9 杀死ABC的进程。此时在nacos控制台中看见ABC的服务状态依然是健康的，且不能下线

**Comment by gfgfggf1988** [comment]
> 请提供更多信息，比如接口调用不成功的报错（客户端和服务端），频繁心跳的日志等

请查看最新的内容

**Comment by KomachiSion** [comment]
你把节点down了，那么发心跳当然是失败的，建议了解一下raft，即使节点不健康 仍然是会继续发心跳的，以便即使检测到他上线，把它从新加会节点。

至于注册的服务被kill点，需要一段时间才能判断为非健康，不能下线需要看下控制台是否有报错，我这边实验是可以下线的。

**Comment by gfgfggf1988** [comment]
> 你把节点down了，那么发心跳当然是失败的，建议了解一下raft，即使节点不健康 仍然是会继续发心跳的，以便即使检测到他上线，把它从新加会节点。
> 
> 至于注册的服务被kill点，需要一段时间才能判断为非健康，不能下线需要看下控制台是否有报错，我这边实验是可以下线的。

把其中一个服务kill掉。在节点1（主节点）查找
![image](https://user-images.githubusercontent.com/16377180/85129794-5030b880-b266-11ea-9c32-1cee3918b158.png)
在节点2（从节点）查找
![image](https://user-images.githubusercontent.com/16377180/85129822-5cb51100-b266-11ea-9a5e-6be77ca9eeb7.png)
该服务已kill 十分钟

**Comment by gfgfggf1988** [comment]
> > 你把节点down了，那么发心跳当然是失败的，建议了解一下raft，即使节点不健康 仍然是会继续发心跳的，以便即使检测到他上线，把它从新加会节点。
> > 至于注册的服务被kill点，需要一段时间才能判断为非健康，不能下线需要看下控制台是否有报错，我这边实验是可以下线的。
> 
> 把其中一个服务kill掉。在节点1（主节点）查找
> ![image](https://user-images.githubusercontent.com/16377180/85129794-5030b880-b266-11ea-9c32-1cee3918b158.png)
> 在节点2（从节点）查找
> ![image](https://user-images.githubusercontent.com/16377180/85129822-5cb51100-b266-11ea-9a5e-6be77ca9eeb7.png)
> 该服务已kill 十分钟

当把第三个nacos节点（从节点）再恢复。在控制台列表中该服务mdd正常下线

**Comment by gfgfggf1988** [comment]
> > > 你把节点down了，那么发心跳当然是失败的，建议了解一下raft，即使节点不健康 仍然是会继续发心跳的，以便即使检测到他上线，把它从新加会节点。
> > > 至于注册的服务被kill点，需要一段时间才能判断为非健康，不能下线需要看下控制台是否有报错，我这边实验是可以下线的。
> > 
> > 
> > 把其中一个服务kill掉。在节点1（主节点）查找
> > ![image](https://user-images.githubusercontent.com/16377180/85129794-5030b880-b266-11ea-9c32-1cee3918b158.png)
> > 在节点2（从节点）查找
> > ![image](https://user-images.githubusercontent.com/16377180/85129822-5cb51100-b266-11ea-9a5e-6be77ca9eeb7.png)
> > 该服务已kill 十分钟
> 
> 当把第三个nacos节点（从节点）再恢复。在控制台列表中该服务mdd正常下线

回溯了一遍流程。
1.nacos从节点kill进程
2.kill在nacos注册的服务
3.又过去十分钟
![mdd在主节点控制台](https://user-images.githubusercontent.com/16377180/85131386-42306700-b269-11ea-8b7f-2c3f5a5fefad.png)
![mdd在从节点控制台](https://user-images.githubusercontent.com/16377180/85131429-5b391800-b269-11ea-9f1b-68732786293d.png)
此时主从节点均有服务存在。但实际上该服务已停止，当点击下线按钮
![手动下线](https://user-images.githubusercontent.com/16377180/85131470-773cb980-b269-11ea-9ada-bc62b831838c.png)

**Comment by gfgfggf1988** [comment]
> 你把节点down了，那么发心跳当然是失败的，建议了解一下raft，即使节点不健康 仍然是会继续发心跳的，以便即使检测到他上线，把它从新加会节点。
> 
> 至于注册的服务被kill点，需要一段时间才能判断为非健康，不能下线需要看下控制台是否有报错，我这边实验是可以下线的。

看一下

**Comment by gfgfggf1988** [comment]
> > > > 你把节点down了，那么发心跳当然是失败的，建议了解一下raft，即使节点不健康 仍然是会继续发心跳的，以便即使检测到他上线，把它从新加会节点。
> > > > 至于注册的服务被kill点，需要一段时间才能判断为非健康，不能下线需要看下控制台是否有报错，我这边实验是可以下线的。
> > > 
> > > 
> > > 把其中一个服务kill掉。在节点1（主节点）查找
> > > ![image](https://user-images.githubusercontent.com/16377180/85129794-5030b880-b266-11ea-9c32-1cee3918b158.png)
> > > 在节点2（从节点）查找
> > > ![image](https://user-images.githubusercontent.com/16377180/85129822-5cb51100-b266-11ea-9a5e-6be77ca9eeb7.png)
> > > 该服务已kill 十分钟
> > 
> > 
> > 当把第三个nacos节点（从节点）再恢复。在控制台列表中该服务mdd正常下线
> 
> 回溯了一遍流程。
> 1.nacos从节点kill进程
> 2.kill在nacos注册的服务
> 3.又过去十分钟
> ![mdd在主节点控制台](https://user-images.githubusercontent.com/16377180/85131386-42306700-b269-11ea-8b7f-2c3f5a5fefad.png)
> ![mdd在从节点控制台](https://user-images.githubusercontent.com/16377180/85131429-5b391800-b269-11ea-9f1b-68732786293d.png)
> 此时主从节点均有服务存在。但实际上该服务已停止，当点击下线按钮
> ![手动下线](https://user-images.githubusercontent.com/16377180/85131470-773cb980-b269-11ea-9ada-bc62b831838c.png)

此时分别查看nacos两个节点的naming-sercer.log日志，不输出。当主动请求
http://172.16.26.54:8848/nacos/v1/ns/instance/beat?app=unknown&namespaceId=public&port=9001&nofix=1&clusterName=DEFAULT&ip=172.16.124.80&serviceName=DEFAULT_GROUP%40%40dig-bmm-mdd&encoding=UTF-8
此时naming-sever.log输出

**Comment by KomachiSion** [comment]
OK，我们尝试复现一下。

**Comment by gfgfggf1988** [comment]
> OK，我们尝试复现一下。

测试出结论了么？

**Comment by KomachiSion** [comment]
1.3版本确实有这个问题 1.2.1没有 我们会尽快修复

**Comment by KomachiSion** [comment]
The bug will be fixed in 1.3.1

**Comment by liaomengge** [comment]
> 1.3版本确实有这个问题 1.2.1没有 我们会尽快修复

1.2.1版本也有这个问题
