### ISSUE TITLE
Cannot read property 'currentLanguageCode' of undefined

### ISSUE THREAD

**Issue by shinailu** [alibaba/nacos#3111]
There is an error,when i was trying to submmit a config.By the way,I use google chrome,and it happens sometimes.

this is the error message.
main.js:54 Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined

**Comment by KomachiSion** [comment]
duplicate #3103

**Comment by chenhj520** [comment]
NewConfig.js  文件中 aliwareIntl对象从globalLib.js 引用，但是globalLib.js文件没有定义aliwareIntl对象。
import { getParams, setParams, request, aliwareIntl } from '../../../globalLib';
