### ISSUE TITLE
nacos HostReactor UpdateTask log every 1 second

### ISSUE THREAD

**Issue by pengyusong** [alibaba/nacos#3119]
nacos version: 1.3.0
environment：springcloud alibaba(provider and comsumer) deploy at windows machine + nacos server deploy at aliyun.

问题描述：
       当nacos异常停止，或者网络连接断开（例如网线被拔掉），部署服务组件（provider和consumer）所在的机器会每隔1s打印日志，刷新非常频繁。

错误日志：

> 2020-06-19 08:50:48.345 ERROR 8780 --- [.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to request 
> java.net.NoRouteToHostException: No route to host: connect
> 	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_231]
> 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_231]
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_231]
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_231]
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_231]
> 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_231]
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_231]
> 	at java.net.Socket.connect(Socket.java:606) ~[na:1.8.0_231]
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_231]
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_231]
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_231]
> 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_231]
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_231]
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_231]
> 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[na:1.8.0_231]
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[na:1.8.0_231]
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[na:1.8.0_231]
> 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[na:1.8.0_231]
> 	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86) ~[nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:433) [nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:468) [nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401) [nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397) [nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:321) [nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:281) [nacos-client-1.2.1.jar:na]
> 	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:327) [nacos-client-1.2.1.jar:na]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_231]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_231]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_231]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_231]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_231]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_231]
> 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]

服务器断网，nacos挂掉，这两种情况都会出现上面的问题，导致日志文件迅速增大，而且占用CPU

经过自己的查看源码，发现错误的地方可能是HostReactor 中 UpdateTask线程，源码中设置定时运行时每隔1s执行更新，这样的频率应该时不正常的，问题代码如下：
```java
public synchronized ScheduledFuture<?> addTask(UpdateTask task) {
        return executor.schedule(task, DEFAULT_DELAY, TimeUnit.MILLISECONDS);
 }
```

这里的DEFAULT_DELAY硬编码为1s，我认为是不合理的，毕竟nacos挂掉也是偶尔会发生，每隔1s就更新太频繁了

**Comment by pengyusong** [comment]
基本可以确定是HostReactor的UpdateTask任务线程中代码问题，本应该是默认每10s执行，但是代码中写死的是1s

**Comment by KomachiSion** [comment]
请组织语言，并合理使用md功能格式化内容，目前不知道想表达的什么，也不知道日志有什么问题。

**Comment by zongtanghu** [comment]
@pengyusong 同上，麻烦重新组织下语言，日志只需要贴关键内容即可，不需要贴全部，这样子也让其他人能够帮助一起排查问题所在。

**Comment by pengyusong** [comment]
抱歉，我上面贴的太多，而且描述发散且错乱，已更改

**Comment by KomachiSion** [comment]
您使用的是单机模式吗？ 如果是集群模式， 应该打几次就会迁移到新的节点上。

然后关于这块逻辑似乎的确有些问题，之后会优化

目前可以试着调用 `PUT /nacos/v1/ns/operator/switches?entry=defaultCacheMillis&value=10000 ` 来试着提高这个updateTask的间隔。

**Comment by pengyusong** [comment]
好的，我试试。

我这边是小企业，打算用单机模式来的，不会有太大的压力，又要控制成本。

由于文档对于配置参数这一块的描述较少且分散，同时描述比较简单，在使用过程中，我对一些配置的使用感受比较困难，因为打算用单机模式，所以想尽可能的优化，许多配置都在摸索当中。

后续还是希望能出一份比较完整的配置参数列表和描述，以及如何调优等，相关文档。我喜欢阅读官方文档，并且对配置优化这一块会想深入了解，毕竟没有能力开发这种软件，但是熟练使用并可以调优，也算对自己也有一个交代，也算是觉得自己有价值的地方。

此外，相比国外的软件，个人比较看好国产nacos，实用性高，性能也不错。

加油，你们是最棒的。

**Comment by pengyusong** [comment]
sorry, 问题并没有解决，我这个日志是provider和consumer（nacos客户端）打印的，更改nacos服务器的配置并没有解决客户端的1s打印的问题。期待下一个版本对定时任务线程的频繁度，以及超时的设置，重试的设置有一个更好优化，以及增加文档描述。

问题重新打开，请开发者打上标签并关闭，感谢~

**Comment by KomachiSion** [comment]
@pengyusong 我们重新核对了一下这块的逻辑， 这个1s的硬编码是UpdateTask初始化的延迟。 之后实际运行间隔可能由个值决定
一个是`PUT /nacos/v1/ns/operator/switches?entry=defaultCacheMillis&value=10000` 另一个是 `PUT /nacos/v1/ns/operator/switches?entry=defaultPushCacheMillis&value=10000`

目前这两个值针对的是全局的，暂时不支持指定某个service

**Comment by pengyusong** [comment]
这个是对nacos服务端的配置进行修改么？这个配置能同步到客户端去咩？毕竟我这个是客户端日志频繁

**Comment by pengyusong** [comment]
两个配置都改了之后，好像可以了

**Comment by yydzxz** [comment]
> [Enhancement] Use cache time set by server when subscribe non-exist service. #3628



> 

在1.4.3版本, 更新的时候要把defaultPushCacheMillis ---> pushCacheMillis
<img width="703" alt="image" src="https://github.com/alibaba/nacos/assets/13087806/3c96121b-a7df-466e-80d2-75bf4ba49942">

**Comment by yydzxz** [comment]
> @pengyusong 我们重新核对了一下这块的逻辑， 这个1s的硬编码是UpdateTask初始化的延迟。 之后实际运行间隔可能由个值决定 一个是`PUT /nacos/v1/ns/operator/switches?entry=defaultCacheMillis&value=10000` 另一个是 `PUT /nacos/v1/ns/operator/switches?entry=defaultPushCacheMillis&value=10000`
> 
> 目前这两个值针对的是全局的，暂时不支持指定某个service


在1.4.3版本,   defaultPushCacheMilli要改为pushCacheMillis  `PUT /nacos/v1/ns/operator/switches?entry=pushCacheMillis&value=10000`

<img width="673" alt="image" src="https://github.com/alibaba/nacos/assets/13087806/729a0091-3369-4075-bbaa-f99053ca7e17">
