### ISSUE TITLE
Unreleased Resource: Database

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/nacos#3121]
https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/config/src/main/java/com/alibaba/nacos/config/server/service/repository/ExternalStoragePersistServiceImpl.java#L2459

The program can potentially fail to release a database resource.

**Comment by KomachiSion** [comment]
see JdbcTemplate.update
