### ISSUE TITLE
The new dataId of the nacos console cannot be read to the configuration（nacos控制台新建dataId无法读取到配置）

### ISSUE THREAD

**Issue by zls1099** [alibaba/nacos#3122]
[English description]
Problems deploying nacos V1.3.0:
1. Create a new dataId in the console to increase the configuration, and the configuration cannot be obtained through the code client. But by cloning the original dataId or importing the backup configuration, you can indeed read the configuration information.
2. After the above problem, after the new dataId is created, restart the nacos service, and the above dataId configuration information can be read normally.

Remarks: The problem was not found in V1.2.1

-----------------------------------------------------------------

【中文描述】
部署nacos V1.3.0问题：
1.在控制台新建dataId增加配置，通过代码客户端无法读取获得配置。但是通过克隆原有dataId或者导入备份的配置，确可以读取到配置信息。
2.上述问题在新建dataId后，重启nacos服务，确又可以正常读取上述的dataId配置信息

备注：在V1.2.1未发现该问题

**Comment by chuntaojun** [comment]
重新下载下1.3.0版本，或者使用单机+mysql的模式部署

**Comment by KomachiSion** [comment]
@chuntaojun Can you tag duplicate and refer to the old issue ?

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2989
