### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/nacos#3123]
https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/naming/src/main/java/com/alibaba/nacos/naming/misc/HttpClient.java#L567

The program can potentially fail to release a system resource.

**Comment by KomachiSion** [comment]
The inputstream is come from `HttpURLConnection`, see the doc of `HttpURLConnection` which can close stream by call disconnect method. And HttpURLConnection is manager by outer. So do no unreleaased.

And doc of `HttpURLConnection` said that if stream close, the http connection may be invalid from http server, So we think we should not close this stream directly.
