### ISSUE TITLE
JSON Injection

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/nacos#3124]
https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java#L47-L54
https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/naming/src/main/java/com/alibaba/nacos/naming/controllers/ClusterController.java#L86
https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/api/src/main/java/com/alibaba/nacos/api/naming/pojo/healthcheck/HealthCheckerFactory.java#L76
The method writes unvalidated input into JSON. This call could allow an attacker to inject arbitrary elements or attributes into the JSON entity.

**Comment by KomachiSion** [comment]
The json need a key `type`, and the type is registered by nacos. If the json has not type of type do not register, directly throw exception.

If the json has type and the type field value is registered, the method will use the real binder to bind actual validated entity.
