### ISSUE TITLE
Cross-Site Scripting: Reflected

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/nacos#3125]
https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/core/src/main/java/com/alibaba/nacos/core/utils/WebUtils.java#L64-L74

https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/naming/src/main/java/com/alibaba/nacos/naming/controllers/ApiController.java#L152

https://github.com/alibaba/nacos/blob/532aad685ec6f86e4855fbb51114f2ddd1fea3a7/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java#L522-L524

Sending unvalidated data to a web browser can result in the browser executing malicious code.

**Comment by KomachiSion** [comment]
Who know what's the `unvalidated data` and what's the `validated data`?

We return object to spring boot mvc, and can spring help to ensure the security?

**Comment by totalo** [comment]
I think it means that it needs to be encoded through web pages.
