### ISSUE TITLE
Why can't we use NACOS1.3.0 to connect MySQL5.7 to persistent Nacos configuration? 

### ISSUE THREAD

**Issue by yuxioman** [alibaba/nacos#3127]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
when we use the SQL script naming 'nacos_config' which the official website provided in Mysql5.7，the SQL script continue to execute error in Navicat.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chuntaojun** [comment]
What are the mistakes

**Comment by yuanyunchu** [comment]
> 有什么错误
执行命令
docker-compose -f example/standalone-mysql.yaml up -d

ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './example/standalone-mysql.yaml
启动就出现这个

**Comment by xzknet** [comment]
换个工具，比如说开源免费的：HeidiSQL

**Comment by KomachiSion** [comment]
No enough information and no response from author. Close issue
