### ISSUE TITLE
使用docker-compose -f example / standalone-derby.yaml up启动nacos，权限无效

### ISSUE THREAD

**Issue by yuanyunchu** [alibaba/nacos#3128]
1.已经开始权限
2.在docker中如何初始化嵌入数据库
3.conf中有个schema.sql
4.是否需要配置数据库mysql，还是可以使用自带数据库

**Comment by chuntaojun** [comment]
内嵌数据库nacos会自动初始化，权限的开启操作看nacos-group/nacos-docker的文档，docker版本不是简单的修改application.properties就可以的

**Comment by yuanyunchu** [comment]
> 内嵌数据库nacos会自动初始化，权限的开启操作看nacos-group/nacos-docker的文档，docker版本不是简单的修改application.properties就可以的

nacos-group/nacos-docker 文档只是写了安装以及application.properties的权限开始，我是实在找不出还有哪里配置权限的
