### ISSUE TITLE
nacos加了权限控制的功能，文档能好好写写吗？

### ISSUE THREAD

**Issue by wangzhedong** [alibaba/nacos#3130]
把nacos升级到1.3，知道里面加了我最为期待的权限功能，但是在官网却找不到关于这方面的任何文档说明，希望在做新功能的同时，文档同步工作也要做好

**Comment by KomachiSion** [comment]
欢迎贡献

**Comment by KomachiSion** [comment]
I will move this issue to #3073, Welcome to contribute.
