### ISSUE TITLE
when ip changed just set ip forgot to set address

### ISSUE THREAD

**Issue by fengsmith** [alibaba/nacos#3133]
![image](https://user-images.githubusercontent.com/6457270/85215750-83329380-b3af-11ea-944a-decca6768fb8.png)

![image](https://user-images.githubusercontent.com/6457270/85215698-f7b90280-b3ae-11ea-8477-d3032734289b.png)

When ip changed just set ip forgot to set address, address is associate with ip ,so when ip changed should set address also.

Later, use new address as a key of ConcurrentSkipListMap<String, Member> serverList ,but when passed parameter is an old address, so call hasMember() function use old address just return false.

**Comment by chuntaojun** [comment]
目前nacos对于这种情况支持不好，如果发现节点变更，建议修改cluster.conf后重启集群

**Comment by fengsmith** [comment]
我是在本机调试的时候，最开始电脑连的是手机热点，后来把热点关掉之后发现修改 nacos 中存储的文件，应用端的变量不会改变之后 debug 才发现的，生产环境中还没遇到类似的问题。

**Comment by KomachiSion** [comment]
或者使用hostname模式，cluster.conf填写host替换ip地址，这样只要host指向的ip是正确的即可

**Comment by fengsmith** [comment]
> 或者使用hostname模式，cluster.conf填写host替换ip地址，这样只要host指向的ip是正确的即可

嗯

**Comment by KomachiSion** [comment]
I think it's a big feature named auto-maintain server. Maybe need to design and discuss more in future.
