### ISSUE TITLE
配置中心的jdbc数据源配置不能热更新吗？需在重启springboot

### ISSUE THREAD

**Issue by deyun93** [alibaba/nacos#3143]
nacos中心版本：1.3.0
springboot版本:2.2.5
springcloud版本：sr3

如果正常配置不能热更新，有没有什么方法可以实现

**Comment by pengzhengfa** [comment]
You can add hot deployed plug-ins at the business code level

**Comment by deyun93** [comment]
> You can add hot deployed plug-ins at the business code level

can i use devtools plug-ins to solve this problem?

**Comment by pengzhengfa** [comment]
It is not recommended to modify this function in Nacos source code. You only need to add hot deployment plug-ins to your business code, which will not affect your normal use. If you modify the source code, other bugs may occur

**Comment by deyun93** [comment]
> It is not recommended to modify this function in Nacos source code. You only need to add hot deployment plug-ins to your business code, which will not affect your normal use. If you modify the source code, other bugs may occur

What plug-ins do you recommend?  Can you send me example code or a good article to understand you said.

**Comment by KomachiSion** [comment]
Why hot-update for datasource? If you want to switch database, I think you should config hostname and use VIP to change the actual ip of hostname.
