### ISSUE TITLE
Suggestions for Nacos persistence extension

### ISSUE THREAD

**Issue by pengzhengfa** [alibaba/nacos#3154]
Is adding redis to the persistence mechanism of Nacos framework helpful to enhance the performance of Nacos in the persistence mechanism,the extension of this function can be implemented by me

**Comment by chuntaojun** [comment]
Nacos has a cache mechanism inside of it, which you can look at

**Comment by pengzhengfa** [comment]
okay, thank you

**Comment by KomachiSion** [comment]
redis can be as a new datasource for store data. But we need to discuss what will be happened if use do not open presistence feature of redis. Beacuse the feature is controlled by users.

And then to decide whether support redis.

**Comment by chuntaojun** [comment]
> redis can be as a new datasource for store data. But we need to discuss what will be happened if use do not open presistence feature of redis. Beacuse the feature is controlled by users.
> 
> And then to decide whether support redis.

Redis is more suitable for the cache of configuration information to avoid sending requests to the database. However, in the design of nacos itself, a cache has been implemented using the file system of the operating system. If one more data source is added, new operation and maintenance costs and uncertainties will be introduced

**Comment by chuntaojun** [comment]
@yanlinly what do you think about it

**Comment by pengzhengfa** [comment]
I think the performance of writing disk directly in the persistence mechanism is certainly not as good as that of writing memory directly. Redis can be used as a persistent storage without setting overdue data. Of course, this will also lead to the problem of merging the original data with the new data

**Comment by chuntaojun** [comment]
However, it is far more difficult to maintain a redIS high-availability cluster than a good disk system, so as to avoid the impact of adding a layer of network factors. Once redIS goes wrong, the disaster recovery measures of the whole nacOS will have problems

**Comment by chuntaojun** [comment]
And when configuring a read, you can just use zero copy, which is not much worse than using RedIS

**Comment by chuntaojun** [comment]
Personally, I don't think the introduction of redis will bring much benefit, so it can't be said that it will bring a lot of QPS. Meanwhile, the introduction of a new component is bound to bring new operation and maintenance costs and uncertain risks, which I personally don't think is necessary

**Comment by yfh0918** [comment]
As for individuals, it's commendable to give users more choices. If the change notification mechanism of Nacos is relatively perfect, it can provide SPI mode for users to expand on their own

**Comment by chuntaojun** [comment]
> As for individuals, it's commendable to give users more choices. If the change notification mechanism of Nacos is relatively perfect, it can provide SPI mode for users to expand on their own

For server side, maybe you don't need to open a separate SPI to do it, after all, from the overall design of nacos that ascension is not clear, I think niche and the demand, the user can modify nacos source to replace this layer of disaster, but the introduction of the operational cost of this is a piece of users need to consider

**Comment by yfh0918** [comment]
At present, I totally agree with you. In the future, can Nacos server move towards componentization and hot plugin

**Comment by chuntaojun** [comment]
You can look at the architecture diagram on the website, this will happen, but which ones will be open, this is still under consideration

**Comment by yfh0918** [comment]
That's good news ，but Higher requirements for code quality

**Comment by wangcy2018** [comment]
I think this function can be extended. It can be developed in later versions. This function can be extended through the mechanism of SPI. You need to configure redis persistence directly. You can also make it if you want to persist through local disks

**Comment by KomachiSion** [comment]
Abstract to persistence label and use SPI to implement is a good way, The only think we should pay attention to is how to config them.

**Comment by KomachiSion** [comment]
So, What's the result of this discussion, I think result is that we has no need to open this enhancement for persistence for now . But we will do it in future?

**Comment by KomachiSion** [comment]
It seems that the discuss has no more response, and the result is enhance in the future. I will close it first.
