### ISSUE TITLE
如何从nacos加载 并注入JavaMailSender的配置

### ISSUE THREAD

**Issue by fringesoft** [alibaba/nacos#3155]
# Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos中配置有如下spring mail配置，但是程序启动时报
“Consider defining a bean of type 'org.springframework.mail.javamail.JavaMailSender' in your configuration.”，经验证直接将spring mail的配置写到项目的application.properties可以正常运行。
···
spring.mail.host=smtp.qq.com
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp
spring.mail.username=xxx@qq.com
spring.mail.password=xxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
···

### Tell us your environment
nacos 1.3.0
nacos-config-spring-boot-starter 0.2.7
spring boot 2.0.3.RELEASE

**Comment by fringesoft** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/issues/87

**Comment by lvlonghu-dadi01** [comment]
遇到同样的问题
