### ISSUE TITLE
mysql init sql not working on mysql utf8mb4 encoding

### ISSUE THREAD

**Issue by jdkcn** [alibaba/nacos#3162]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

```
CREATE TABLE `permissions` ( `role` varchar(50) NOT NULL, `resource` varchar(512) NOT NULL, `action` varchar(8) NOT NULL, UNIQUE INDEX `uk_role_permission` (`role`,`resource`,`action`) USING BTREE )
```

Specified key was too long; max key length is 767 bytes

### How to reproduce it (as minimally and precisely as possible)

1. create a nacos database with utf8mb4 encoding 
2. restore the init sql from https://github.com/alibaba/nacos/blob/1.3.0/distribution/conf/nacos-mysql.sql

**Comment by chuntaojun** [comment]
自己修改下长度即可，因为默认是采用latin1字符集，可以了解下mysql每种编码对应的数据长度的计算

**Comment by jdkcn** [comment]
了解过长度，通过修改长度可以绕开这个问题，问题是utf8mb4 下的长度是否能满足系统的功能要求？
