### ISSUE TITLE
Invalid gray scale test

### ISSUE THREAD

**Issue by java492** [alibaba/nacos#3164]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Clicking the publish Beata button appears and the configuration format is unchecked, rendering the grayscale test ineffective

### Describe what you expected to happen
Click the publish Beata button and the grayscale configuration service takes effect

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Linux environment
Nacos version 1.3.0
![1592903387(1)](https://user-images.githubusercontent.com/46774375/85385026-64312e80-b574-11ea-8c1b-b7d899c3d815.png)

**Comment by java492** [comment]
Rolling back the configuration also causes the configuration format to be unchecked

**Comment by ljhrot** [comment]
i will solve it

**Comment by KomachiSion** [comment]
refer to #8799
