### ISSUE TITLE
Aliyun SLB NACOS LoadBalance, Cluster Node List GET api failed..

### ISSUE THREAD

**Issue by capricornxl** [alibaba/nacos#3166]
I used Aliyun Private SLB created a LoadBalance for three nacos node.
When I visit the "Cluster Node List" menu show "no such api:GET:/nacos/v1/operator/clster/states"
But I can POST params to registration services with curl.

![image](https://user-images.githubusercontent.com/40738379/85395457-c09b4a80-b582-11ea-9a12-514dba9560d9.png)

slb:
172.26.113.244:6001

nacos node:
172.26.113.239:6001
172.26.113.240:6001
172.26.113.241:6001

![image](https://user-images.githubusercontent.com/40738379/85394834-c3e20680-b581-11ea-8509-34c039de54ad.png)
![image](https://user-images.githubusercontent.com/40738379/85394900-e1af6b80-b581-11ea-853c-5222cd802206.png)

How to solve this problem?

**Comment by chuntaojun** [comment]
你的页面和官网的demo比对下，你这个页面不是最新的，清空浏览器缓存即可

**Comment by capricornxl** [comment]
> 你的页面和官网的demo比对下，你这个页面不是最新的，清空浏览器缓存即可

感谢，果然是这个问题。
