### ISSUE TITLE
cannot read proper cache file because the path is not correct

### ISSUE THREAD

**Issue by Len888** [alibaba/nacos#3167]
## Issue Description

Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
The SpringBoot application cannot read proper cache file , the nacos version is 1.3.0, the application read the cache file in 
"C:\User\xxx\nacos\config\...", but I found the cache file stored at D:\nacos\data\tenant.....(this is the location of nacos application)

### Describe what you expected to happen
I want to know how to define a location, like the zookeeper.

### How to reproduce it (as minimally and precisely as possible)

1. normal start the application
2. 
3. 

### Tell us your environment
Windows 10, SpringBoot 2.3.0.RELEASE,SpringCloud Greenwich.SR1 , SpringCloudAlibaba2.2.1.RELEASE

**Comment by KomachiSion** [comment]
Currently, it seems that no way to change the cache file dir for config.

**Comment by Len888** [comment]
OK, thanks a lot~ But I hope this can be configured in the future version.
