### ISSUE TITLE
1.3.0 no such api:GET:/v1/ns/catalog/services

### ISSUE THREAD

**Issue by jeebeys** [alibaba/nacos#3169]
serviceManagement
{"timestamp":"2020-06-24T04:53:13.587+0000","status":501,"error":"Not Implemented","message":"no such api:GET:/v1/ns/catalog/services","path":"/v1/ns/catalog/services"}

**Comment by chuntaojun** [comment]
这个接口是存在的，可以看下官网的demo，打开控制台，这个http接口是有的

**Comment by KomachiSion** [comment]
maybe path is '/nacos/v1/ns/catalog/services' ?

**Comment by KomachiSion** [comment]
No response more than 7 days, close issue
