### ISSUE TITLE
About the period of writing ServiceInfos into the failover directory

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/nacos#3178]
## Issue Description
Type: *question*

### Describe what happened (or what feature you want)
I found that the period of writing ServiceInfos is everyday.And I think the period is long, so I want to know the background of the daily writing.
![image](https://user-images.githubusercontent.com/45141175/85694310-9922ba00-b709-11ea-8e29-d3251e74c5e8.png)

**Comment by KomachiSion** [comment]
It's experience value, the original author think do failover once for each day is enough. In fact, almost services can register again after failover. So I agree with the original authors.

**Comment by junjie-tang99** [comment]
Hi KomachiSion, thank you for your prompt answer. Maybe I express my mind not clearly. Actually I means that: if the client started yesterday, and the FailoverReatctor writed the ServiceInfo(eq: A service) into the failover directory. But after the FailoverReatctor's writing, the client need to invoke the B service. Then the HostReactor writed the B ServiceInfo into the cache director, and the FailoverReatctor didn't write. Today's morning the nacos service broke down, we should open the failover status.But the client only have the A ServiceInfo, and this situation can make client can't invoke the B service.

**Comment by KomachiSion** [comment]
The failover is a tmp way for available, just like DB back up. No matter how small this window time is set, the problem you said may happen. So we use the experience value to do this.
