### ISSUE TITLE
About the failover switch file

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/nacos#3181]
## Issue Description
Type: *question* 

### Describe what happened (or what feature you want)
The SwitchRefresher will check whether the failover switch file is exists. And the failover switch file's name is failover00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00. But I can't find the source code to setup the failover switch file or write the status into the the failover switch file. 
![image](https://user-images.githubusercontent.com/45141175/85811622-383ec480-b791-11ea-96f9-028916347ed9.png)

**Comment by KomachiSion** [comment]
It's a switch file which need user create. It will be used when there are some problem between client and server. Users can create this file and set value = 1 to open client failover feature.

It's a old logic, maybe need to discuss how to optimize it.

**Comment by junjie-tang99** [comment]
> It's a switch file which need user create. It will be used when there are some problem between client and server. Users can create this file and set value = 1 to open client failover feature.
> 
> It's a old logic, maybe need to discuss how to optimize it.

Hi, KomachiSion. Thank you for your clearly answer. I also think the moment of setting the failover switch file's value to 1 is a complicated problem. And I have two suggestions, maybe is not the best.
The first is open a interface in the nacos-client to change the failover status in the FialoverReactor when getting the instance from nacos servers. And the monitors can invoke the interface to open the failover status. That is more convenient than creating the file manually, especially in large-scale microservices situation. 
Another is add the failover strategy such as: Setting the failover switch file's value to 1 until the failure ratio reach the parameter in last 5 mins. And the user can enable this strategy alternatively.

**Comment by KomachiSion** [comment]
For the first suggestions, the failover is prepare for client can't connect server. If change status need signal from server. Why we set failover?

Second suggestions seems like an enhancement. We may discuss how to enhance this feature in future, I think, no now.

The failover feature is just in case. We should improve the availability for server to avoid use failover.
