### ISSUE TITLE
Unable to read nacos configuration file

### ISSUE THREAD

**Issue by cielswift** [alibaba/nacos#3182]
nacos version 1.3
jdk version 1.8
![image](https://user-images.githubusercontent.com/42295829/85854078-508cfe80-b7e6-11ea-85fb-a12ed2fa2bd3.png)

extension-configs:
          - dataId: other-dev.yaml
            group: DEFAULT_GROUP
            refresh: true

Unable to get content of other-dev.yaml

**Comment by KomachiSion** [comment]
you mean that you add a file `other-dev.yaml` but can't get it from console?

Can you have a try to get it from openAPI or SDK?

**Comment by cielswift** [comment]
applicationContext.getEnvironment().getProperty("person.name"); //is null 

@Value("${person.name}") 
protected String name   // start error 

Unable to read

`cloud:
    nacos:  
      discovery: 
        server-addr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
        namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68 
        group: DEFAULT_GROUP 
      config: 
        server-addr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
        file-extension: yaml  
        namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68 #开发环境
        group: DEFAULT_GROUP 
        prefix: application-dev  
        refresh-enabled: true 
        extension-configs: 
          - dataId: other-dev.yaml
            group: DEFAULT_GROUP
            refresh: true`

application-dev can get the configuration

**Comment by chuntaojun** [comment]
dataId是强匹配，注意看你的配置文件和控制台的dataId

**Comment by cielswift** [comment]
没错啊 other-dev.yaml  我如果去掉 .yaml 启动会直接报错的 
![image](https://user-images.githubusercontent.com/42295829/85940958-48ea6880-b952-11ea-8852-b1e9330aa732.png)

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/86045684-84825100-ba7e-11ea-80ba-c0b1ae3a5077.png)
我用的spring-cloud-starter-alibaba-nacos-config:2.1.2.RELEASE,
启动的时候有个信息
![image](https://user-images.githubusercontent.com/8871739/86045827-b85d7680-ba7e-11ea-92dd-8156f07b3c7c.png)
我测试的时候不支持yaml,但是可以支持properties,兄弟多看文档

**Comment by cielswift** [comment]
就是在bootstarp.yml里啊  要不然application-dev 也不会能读取到啊

**Comment by belonk** [comment]
如果我没看错的话，你的dataid：other-dev少了后缀，正确应该为other-dev.yaml, 而且必须是yaml，后缀写成yml都不行的，nacos dataid是强匹配

孙哺昌
杭州惠程信息技术有限公司·技术部

**Comment by cielswift** [comment]
＠belonk　就是other-dev.yaml　
这是完整的配置　
server:
  port: 25010
  servlet:
    context-path: /producer10
spring:
  application:
    name: producer10
  aop:
    proxy-target-class: true #使用cglib代理
  main:
    allow-bean-definition-overriding: true #bean冲突覆盖
  profiles:
    active: dev #开发模式
  redis:
    host: 127.0.0.1
    port: 6510
    password: ciel
    database: 14
  datasource:
    dynamic: #多数据源模式
      primary: master  #设置默认的数据源或者数据源组,默认值即为master ; 两套配置的主库和从库相反
      druid: #druid 全局配置
        filters: stat #Druid内置提供一个StatFilter，用于统计监控信息
        initial-size: 16
        min-idle: 16
        max-active: 32
        time-between-eviction-runs-millis: 5000
        validation-query: SELECT 1 FROM dual
      datasource:
        master:
          username: root
          password: ciel
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/spring_alibaba?seUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initial-size: 16 #单独配置
        slave1:
          username: root
          password: ciel
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/spring_alibaba1?seUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:  #使用nacos注册中心
      discovery: #注册中心
        server-addr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
        namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68 #开发环境
        group: DEFAULT_GROUP #组
      config: #配置中心
        server-addr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
        file-extension: yaml  #指定读取的配置文件后缀; dataId默认${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68 #开发环境
        group: DEFAULT_GROUP #组
        prefix: application-dev  #文件名 ;如果没有配置则默认为 ${spring.appliction.name} (优先级高)
        extension-configs:  #扩展配置其他多个配置文件
          - dataId: other-dev.yaml
            group: DEFAULT_GROUP
            refresh: false

  zipkin:  #链路追踪
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1 #percentage是采样比例

#rocketmq 事务
rocketmq:
  producer:
    group: transcation_1 #生产组
  name-server: 127.0.0.1:9876

#org:
#  dromara:
#    hmily :
#      serializer : kryo
#      recoverDelayTime : 128
#      retryMax : 30
#      scheduledDelay : 128
#      scheduledThreadMax :  10
#      repositorySupport : redis
#      started: true  #事务控制方改为true
##      hmilyDbConfig :
##        driverClassName: com.mysql.jdbc.Driver
##        url: jdbc:mysql://127.0.0.1:1672/hmily_transaction?seUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
##        username : root
##        password : ciel
#      hmilyRedisConfig:
#        hostName: 127.0.0.1
#        port: 6510
#        password: ciel


    # repositorySupport : redis
    #         hostName  : 192.168.1.68
    #         port      :  6379
    #         password  :


    # repositorySupport : zookeeper
    #         host      : 92.168.1.73:2181
    #         sessionTimeOut      :  100000
    #         rootPath  : /tcc

    # repositorySupport : mongodb
    #       mongoDbUrl  : 192.168.1.68:27017
    #       mongoDbName  :  happylife
    #       mongoUserName  : xiaoyu
    #       mongoUserPwd   : 123456

    # repositorySupport : file
    #         path      : /account
    #         prefix    :  account

dubbo: #dubbo配置
  scan:
    base-packages: com.ciel.scaproducer1.serverimpl #服务扫描包,标记有@service
  protocol:
    name: dubbo #dubbo协议
    port: 20881 #协议端口
    accesslog: true  #将访问日志输出到当前应用的log4j日志
  provider:
    version: 1.0
    accesslog: true  #将访问日志输出到当前应用的log4j日志
  registry:
    address: nacos://127.0.0.1:13100?backup=127.0.0.1:13101,127.0.0.1:13102&namespace=a998603d-3546-4ddc-9099-2ed82a6f3a68 #使用nacos注册中心
  application:
    qos-enable: false #运维服务是否开启
  consumer:
    check: false #启动时就检查服务
    version: 1.0
    timeout: 600000  #10分钟
    retries: 0 #禁止重试 为了debug

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.ciel.scaentity.entity  #实体扫描
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
    map-underscore-to-camel-case: true #数据库下划线转换
    #cache-enabled: true #开启二级缓存
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      updateStrategy: NOT_NULL  #为null 不更新
      insertStrategy: NOT_NULL
      selectStrategy: NOT_NULL

#超时10分钟
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  config: classpath:logback-spring.xml

clusters:
  datacenterId: 6
  machineId: 1

---
spring:  #多文档模式,定义一些其他配置
  profiles:
    active: dev

#分布式事务
seata:
  enabled: true
  application-id: pro10
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68
      serverAddr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
      group: DEFAULT_GROUP
  registry:
    type: nacos
    nacos:
      application: applicationName
      server-addr: 127.0.0.1:13100,127.0.0.1:13101,127.0.0.1:13102
      namespace: a998603d-3546-4ddc-9099-2ed82a6f3a68

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/86506310-ea653480-be00-11ea-9e70-fac416079d51.png)
https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html,这个图上的一段多理解解

**Comment by cielswift** [comment]
@alanfans 配置的错误在哪里?

**Comment by KomachiSion** [comment]
No more process in issue, and from the discuss, it is a usage problem.
