### ISSUE TITLE
maven install 打包出错

### ISSUE THREAD

**Issue by onexuan** [alibaba/nacos#3183]
环境：Spring boot

pom.xml
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-discovery-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>
 
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

server.port=3424
spring.application.name=users
nacos.server.ip=192.168.0.18
nacos.config.server-addr=192.168.0.18:8848
nacos.discovery.server-addr=192.168.0.18:8848

@Configuration
public class NacosRegisterConfiguration {

    @Value("${server.port}")
    private int serverPort;

    @Value("${spring.application.name}")
    private String applicationName;

    @Value("${nacos.server.ip}")
    private String nacosServerIP;

    @NacosInjected
    private NamingService namingService;

    @PostConstruct
    public void registerInstance() throws NacosException {
        namingService.registerInstance(applicationName, nacosServerIP, serverPort, applicationName);
    }
}
在idea 直接运行，一切正常

但用maven install 打包成jar时，出错
server error: such as timeout. failed to req API:/api//nacos/v1/ns/instance after all servers([192.168.0.18:8848]) tried: caused: instance format invalid: Your IP address is spelled incorrectly;

**Comment by KomachiSion** [comment]
it's not nacos' issue, you should check your local env and maven env.  I think it's your unit test problem error when installing.
