### ISSUE TITLE
The FailoverReactor can't write ServiceInfo files into the failover directory.

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/nacos#3184]
## Issue Description
Type: *bug report*

### Describe what happened (or what feature you want)
The FailoverReactor will writing the ServiceInfo files into the failover directory after the initialization of FailoverReactor. But when the failover directory existing the invalid file(eq: macOS hidden file)，the FailoverReactor will not writing the ServiceInfo files.
![image](https://user-images.githubusercontent.com/45141175/85918423-3fe79180-b895-11ea-8390-bb247d92f3a9.png)

### Describe what you expected to happen
I think FailoverReactor can filter some  invalid files.

### Tell us your environment
nacos-clitent version is 1.1.1

**Comment by KomachiSion** [comment]
Maybe fixed by #2849 #3160

**Comment by junjie-tang99** [comment]
THX
