### ISSUE TITLE
1.3.0版本单机模式启动不能查询到服务列表

### ISSUE THREAD

**Issue by 13647227317** [alibaba/nacos#3189]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
Please describe your problem issue in detail, otherwise no one can help you.

**Comment by taopaperman** [comment]
When the version is the latest 1.3.0, running in stand-alone mode, I can not see the list of services. But the console shows that the registration service is successful.

**Comment by KomachiSion** [comment]
I tried in console demo from nacos.io, it can work. I need more detail information. Such as the namespace, the way of register and so on. The best way is provide a demo project which can reproduce your problems.

**Comment by KomachiSion** [comment]
No response more than **7 days**
