### ISSUE TITLE
同namespace下不同分组之间的服务调用问题

### ISSUE THREAD

**Issue by xiazhenyou** [alibaba/nacos#3193]
![TIM图片20200628181415](https://user-images.githubusercontent.com/58844127/85944690-5d872a80-b96b-11ea-83ff-a3bad3f9dbdd.png)

同一个命名空间下，不同服务分组之间无法通过feigin进行服务调用么？
base调用 auth提示 nacos Load balancer does not have available server   ，默认分组调用没有问题

**Comment by junjie-tang99** [comment]
hi,xiazhenyou. 确实像你说的不同的分组即使是在同一个namespace下，是无法进行调用的。其实，我觉得nacos的数据模型缺少一个最佳实践的说明。比如：在多机房参场景下、SET化场景下，namespace、group、cluster分别该怎么设置。

**Comment by KomachiSion** [comment]
namespace也好，分组也还，只是在服务发现的时候进行隔离使用的。

至于namespace、group、cluster分别该怎么设置，主要还是由业务方来制定，不同的业务场景，需要的级别和要求都不相同。社区不太好给出所谓的最佳实践。

不过有一些公司的使用案例，可能可以参考下。

同时也大家把自己的使用案例写成文章发布，既能够给别人参考，也可以让大家讨论下是否有更好的使用方式。

**Comment by xiazhenyou** [comment]
我是namespace做环境隔离。想通过group做不同业务隔离的。我以为goup只是用来做分组。没想到也做服务隔离。看来只能服务注册与发现不做分组了。

**Comment by SealinRepo** [comment]
我的想法跟楼主一样的， 看来也要改成同一个分组了。。

**Comment by renshuaiya** [comment]
> 我的想法跟楼主一样的，看来也要改成同一个分组了。。



> 我是名称空间做环境隔离。想通过组做不同业务隔离的。我以为goup只是用来做分组。没想到也做服务隔离。看来只能服务注册与发现不做分组了。

我在钉钉群问管理，他说同space不同组服务间可以互调，但是我问他为什么调不通，他说：“spring cloud的设计问题”,我真是...

**Comment by KomachiSion** [comment]
我看了下大家的反馈， 感觉并没有什么问题，大家用namespace做环境隔离，比如dev，test，prod等。
然后又用group做业务隔离，既然隔离了那当然是不能调用。

至于大家所说的不同group不能调用的问题，我觉得可能是上下文没有对齐。

比如我有一个A服务， 分了2个组  G1@@A和G2@@A，这两个A之间当然是隔离的，那如果有个B服务，他想调用G1的A服务，当然是没问题的，只需要subscribe G1@@A就可以了。  无所谓B服务是G1还是G2。

**Comment by KomachiSion** [comment]
然后是spring cloud的问题，启动的时候可能指定了某个Group 从而导致其订阅和发布服务时，都只会选用指定的Group。无法像上述一样指定发布G1服务却订阅G2服务，具体需要看是spring-cloud-nacos是这么实现的还是spring-cloud的group语义就是这样的。

如果是前者，可以到spring-cloud-nacos去提issue，然后发起讨论怎么改合适，甚至自己贡献代码。
如果是后者，那么其实spring-cloud的设计层面，就希望大家使用的时候做隔离，同条链路就应该在一个分组。

**Comment by xiazhenyou** [comment]
感谢大家回答。

**Comment by jiyilee** [comment]
和楼主一样的问题，应该是大部分的需求场景。namespace隔离，group（配置分开）服务之间应该是可以相互调用的，特别是一些公用服务，不同组也要统一调用公用服务的，不然公用服务要每个项目拷贝一份，或者不用分组来相互调用了。。。 @KomachiSion

**Comment by ankelen** [comment]
我用自定义的Bean重写了NacosServiceDiscovery中的getInstances方法，使其查找服务实例的时候不传group参数，目前算是解决了我的需求，但是我不清楚这样做有什么隐藏的风险

**Comment by VicoHu** [comment]
> 我看了下大家的反馈， 感觉并没有什么问题，大家用namespace做环境隔离，比如dev，test，prod等。
> 然后又用group做业务隔离，既然隔离了那当然是不能调用。
> 
> 至于大家所说的不同group不能调用的问题，我觉得可能是上下文没有对齐。
> 
> 比如我有一个A服务， 分了2个组 G1@@A和G2@@A，这两个A之间当然是隔离的，那如果有个B服务，他想调用G1的A服务，当然是没问题的，只需要subscribe G1@@A就可以了。 无所谓B服务是G1还是G2（单从nacos角度看）。

请问一下，服务A怎么subscribe另外一个服务啊

**Comment by belonace** [comment]
> 和楼主一样的问题，应该是大部分的需求场景。namespace隔离，group（配置分开）服务之间应该是可以相互调用的，特别是一些公用服务，不同组也要统一调用公用服务的，不然公用服务要每个项目拷贝一份，或者不用分组来相互调用了。。。 @KomachiSion

我也遇到了同样的问题，公共服务怎么办？每个组或者每个NS都要部署一套吗？那这两个隔离用NS隔离就行了，为什么还要Group隔离，哎

**Comment by renshuaiya** [comment]
> > 和楼主一样的问题，应该是大部分的需求场景。namespace隔离，group（配置分开）服务之间应该是可以相互调用的，特别是一些公用服务，不同组也要统一调用公用服务的，不然公用服务要每个项目拷贝一份，或者不用分组来相互调用了。。。 @KomachiSion
> 
> 我也遇到了同样的问题，公共服务怎么办？每个组或者每个NS都要部署一套吗？那这两个隔离用NS隔离就行了，为什么还要Group隔离，哎

只是固定调具体公共服务，你参考下这个，这我线上正在用的，https://blog.csdn.net/qq_43167632/article/details/107386171

**Comment by belonace** [comment]
> > > 和楼主一样的问题，应该是大部分的需求场景。namespace隔离，group（配置分开）服务之间应该是可以相互调用的，特别是一些公用服务，不同组也要统一调用公用服务的，不然公用服务要每个项目拷贝一份，或者不用分组来相互调用了。。。 @KomachiSion
> > 
> > 
> > 我也遇到了同样的问题，公共服务怎么办？每个组或者每个NS都要部署一套吗？那这两个隔离用NS隔离就行了，为什么还要Group隔离，哎
> 
> 只是固定调具体公共服务，你参考下这个，这我线上正在用的，https://blog.csdn.net/qq_43167632/article/details/107386171

谢谢 我试试

**Comment by awm96** [comment]
/**
 * 解决nacos服务跨组调用问题，使用方式在应用本地配置文件中添加如下配置：
 * 【nacos中的dataId】.ribbon:
 *   nacos.group: 【dataId所对应的组】
 *   NFLoadBalancerRuleClassName: com.yiche.bdc.framework.core.ribbon.NacosCrossGroupRibbonRule
 * @author ligq
 * @since 2022-01-18
 */
@Slf4j
public class NacosCrossGroupRibbonRule extends AbstractLoadBalancerRule {

    @Autowired
    private NacosDiscoveryProperties nacosDiscoveryProperties;
    @Autowired
    private Environment environment;

    @Override
    public Server choose(Object key) {
        try {
            String clusterName = this.nacosDiscoveryProperties.getClusterName();
            DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer) getLoadBalancer();
            String name = loadBalancer.getName();
            String group = environment.getProperty(name + ".ribbon.nacos.group");
            NamingService namingService = nacosDiscoveryProperties.namingServiceInstance();
            List<Instance> instances = namingService.selectInstances(name, group, true);
            if (CollectionUtils.isEmpty(instances)) {
                log.warn("no instance in service {}", name);
                return null;
            }

            List<Instance> instancesToChoose = instances;
            if (StringUtils.isNotBlank(clusterName)) {
                List<Instance> sameClusterInstances = instances.stream()
                        .filter(instance -> Objects.equals(clusterName, instance.getClusterName()))
                        .collect(Collectors.toList());
                if (!CollectionUtils.isEmpty(sameClusterInstances)) {
                    instancesToChoose = sameClusterInstances;
                }
                else {
                    log.warn("A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}", name, clusterName, instances);
                }
            }

            Instance instance = ExtendBalancer.getHostByRandomWeight2(instancesToChoose);
            return new NacosServer(instance);
        }
        catch (Exception e) {
            log.warn("NacosRule error", e);
            return null;
        }
    }

    @Override
    public void initWithNiwsConfig(IClientConfig iClientConfig) {
    }
}

**Comment by chenzhiguo** [comment]
分这么多维度没啥问题，但是怎么配合spring cloud使用呢？没有明确的指导确实很让人难以理解，并且官方的的samples都很老了，也不更新一下。

**Comment by qyqcswill** [comment]
> * DynamicServerListLoadBalancer loadBalancer = (DynamicServerListLoadBalancer) getLoadBalancer();

It is not thredd safe ,don't use this!!

If you wanno get instances by serviceid , just use `public Server choose(Object key) {}`,  param of `key` actually is serviceid or serviceName.

**Comment by Harverys** [comment]
楼主有想到什么好一点解决办法了吗

**Comment by dojeee** [comment]
所以还是没有结论了吗？  我是Spring Cloud Gateway 和 Some service 分了两个group，现在Gateway无法路由到 Some service。   准备还是用同一个 group 不同的namespace。
