### ISSUE TITLE
OutOfMemoryError naming

### ISSUE THREAD

**Issue by mengwang0211** [alibaba/nacos#3199]
SpringBoot 2.1.4.REALEASE 
SpringCloud 
`Greenwich.SR2`
`spring-cloud-starter-alibaba-nacos-discovery` 0.9.0.RELEASE
nacos-client  
`1.2.1`

online service run a few days, catch OOM

logs :

20/6/28 上午12:42:37Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "com.alibaba.nacos.client.naming.updater"
2020/6/28 上午12:47:56Exception in thread "com.alibaba.nacos.client.naming.updater" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午12:50:05Exception in thread "com.alibaba.nacos.client.naming.updater" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午12:52:58Exception in thread "com.alibaba.nacos.client.naming.updater" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午12:58:02Exception in thread "com.alibaba.nacos.client.naming.updater" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午12:59:58Exception in thread "com.alibaba.nacos.client.naming.updater" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午1:02:24Exception in thread "com.alibaba.nacos.client.naming.updater" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午1:24:54Exception in thread "Catalina-utility-8" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午1:28:54Exception in thread "Catalina-utility-9" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午6:03:27Exception in thread "Catalina-utility-10" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午11:53:07Exception in thread "Catalina-utility-11" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午11:54:04Exception in thread "Catalina-utility-7" java.lang.OutOfMemoryError: Java heap space
2020/6/28 上午11:55:08Exception in thread "Catalina-utility-12" java.lang.OutOfMemoryError: Java heap space

**Comment by KomachiSion** [comment]
Please provide your JVM configuration, how many service and instance you have.

If you can dump the memory and do some analyze will be best.

**Comment by KomachiSion** [comment]
No response more than 7 days, close issue.
