### ISSUE TITLE
nacos 支持多个配置文件，配置模板抽象和继承

### ISSUE THREAD

**Issue by haochencheng** [alibaba/nacos#320]
比如有些配置是公用的 就都用一个 公用的配置文件， 在加上自己${服务名}+${profile}的差异化配置。

**Comment by pguo65535** [comment]
An example as following?

[parent-cfg]   {key1=value1, key2=value2} 
   |- [sub-cfg1]  {key3=value3  -- just add a new entry }
   |- [sub-cfg2]  {key4=value4, key2=value4 @override}

**Comment by gumutianqi** [comment]
的确，我们一般会把配置中心的配置文件拆分，例如：`global.yml mysql.yml mq.yml cache.yml sentinel.yml` 然后每个应用拿需要的配置进行组合，根据先后顺序如果有重复的，后面的覆盖前面的配置项；我现在生产环境使用的 `spring-cloud-config-server`就是这样的逻辑

**Comment by yanlinly** [comment]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config
