### ISSUE TITLE
Dubbo consumer is registered to the nacos cluster, sometimes consumers will not be found

### ISSUE THREAD

**Issue by forlangel** [alibaba/nacos#3200]
I have three servers doing nacos clusters, namely 33, 34, 35, and the version is 1.3.0.The consumer on the 33 server, displayed on nacos, will be registered to 33, but will often go to 34 to find this consumer.

**Comment by forlangel** [comment]
How to set up a consumer that can't be found on a nacos node can poll to other nodes

**Comment by KomachiSion** [comment]
Whichever node you register, the register request will be routed to one node which is responsible for service by service names. And same for finding service.

And the consumer and provider information will be synced to other nodes, so that the responsible node down.

When responsible node down, the request will be routed to a new responsible node.

So I can't get your problem.

**Comment by forlangel** [comment]
首先感谢您的回答以及您同事的邮件回复，为了表述清楚我还是用中文吧。
问题：dubbo服务注册到nacos集群，consumer偶尔找不到
服务器配置：33、34、35三台服务器，nacos集群正常部署,版本1.3.0
dubbo服务情况：
1、SpringMvc的项目通过schema的方式使用dubbo。
2、有三个应用服务A/B/C注册了三个相同的consumer,其中A、B部署在33服务器上，C部署在34服务器上，consumer使用：
`<idubbo:reference id="sysUserProvider"  interface="com.sino.provider.sys.SysUserProvider" check="false" />`
注入到spring并注册到dubbo成为consumer（三个应用服务都是这样配置的一模一样，是否是id相同造成的,A每次都会注册到33上 BC每次都会注册到34上并且存在服务覆盖现象）
出问题的场景：A应用的consumer注册在33服务器上，偶尔会报错:
`No provider available from registry 192.168.1.33:8848 for service com.sino.provider.sys.SysUserProvider on consumer 192.168.1.33 use dubbo version 2.7.4.1, please check status of providers(disabled, not registered or in blacklist).`
在nacos上是可以看到A注册的consumer的，并且是健康的.
抱歉我的描述看起来很长，因为这个是偶发的情况，导致nacos不能移植到生产环境，所以这个问题希望还是能够解决。
----------------------------------------------------------------------------------------------------------------------------------------------
First of all, thank you for your answer and your colleague's e-mail reply, in order to make it clear I still use Chinese.
Problem: The dubbo service is registered to the nacos cluster, and the consumer occasionally can't find
Server configuration: 33, 34, 35 three servers, nacos cluster normal deployment, version 1.3.0
Dubbo Services:
1, SpringMvc project through schema way to use dubbo.
2, there are three application services A/B/C registered three identical consumer, wherea A, B deployed on 33 servers, C deployed on 34 servers, consumer use:
'<idubbo: "reference id" "sysUserProvider" interface"com.sino.provider.sys.sysUserProvider" check"false" /> '
Inject into the spring and register to the dubbo to become a consumer (all three application services are configured exactly the same, whether the id is the same caused, A will register to 33 each time BC will register to 34 each time and there is a service overlay)
The scenario in question: The App's registration on 33 servers occasionally states errors:
'No provider from the registry 192.168.1.33: 8848 for service.com.sino.provider.sys.sys.SysUserServerProvider on consumer 192.168.1.33 use dubbo version 2.7.1, please check status of the servers (disabled, registered or in.)'
On nacos you can see A-registered consumer, and it's healthy.
Sorry, my description looks very long, because this is an occasional situation that prevents nacos from being ported to production, so I hope this problem can be solved.
![Uploading 微信截图_20200629152152.png…]()

**Comment by KomachiSion** [comment]
2.7.4.1dubbo有一个无法感知nacos节点，apache/dubbo#4793
应该在2.7.6修复了

或者试一下nacos1.4.0版本 也修复了一个和comsumer偶尔无法发现provider有关

**Comment by forlangel** [comment]
非常感谢，明天将着手尝试。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："杨翊 SionYang "<notifications@github.com&gt;;
发送时间：2020年11月9日(星期一) 晚上8:08
收件人："alibaba/nacos" <nacos@noreply.github.com&gt;;
抄送："Forlangel "<jhin@forlangel.com&gt;;"State change "<state_change@noreply.github.com&gt;;
主题：Re: [alibaba/nacos] Dubbo consumer is registered to the nacos cluster, sometimes consumers will not be found (#3200)
-----------------------------------

 

 
2.7.4.1dubbo有一个无法感知nacos节点，apache/dubbo#4793
 应该在2.7.6修复了
 
或者试一下nacos1.4.0版本 也修复了一个和comsumer偶尔无法发现provider有关

**Comment by KomachiSion** [comment]
Any process？ If no more question, i will close issue.

**Comment by forlangel** [comment]
没有问题了，已平稳运行三天没有出现服务丢失的问题，准备这周上生产，感谢。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："杨翊 SionYang "<notifications@github.com&gt;;
发送时间：2020年11月16日(星期一) 上午9:35
收件人："alibaba/nacos" <nacos@noreply.github.com&gt;;
抄送："Forlangel "<jhin@forlangel.com&gt;;"State change "<state_change@noreply.github.com&gt;;
主题：Re: [alibaba/nacos] Dubbo consumer is registered to the nacos cluster, sometimes consumers will not be found (#3200)
-----------------------------------

 

 
Any process？ If no more question, i will close issue.
