### ISSUE TITLE
完全关闭nacos config后 读不到本地application.properties配置

### ISSUE THREAD

**Issue by godnm** [alibaba/nacos#3203]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

我这个服务部署在很多服务器上，我想一点一点迁移到nacos config上
当我在项目maven中依赖了 spring-cloud-starter-alibaba-nacos-config
就读不到我项目本地中的依赖文件
![image](https://user-images.githubusercontent.com/64179296/85988191-44d94c00-ba21-11ea-97c3-687e61a930e9.png)
在 bootstrap.properties 加上spring.cloud.nacos.config.enabled=false也不行

### Tell us your environment

![image](https://user-images.githubusercontent.com/64179296/85988424-8d910500-ba21-11ea-8205-a99dc1a5e4d2.png)

![image](https://user-images.githubusercontent.com/64179296/85988490-a8fc1000-ba21-11ea-9742-0613c4690c38.png)

![image](https://user-images.githubusercontent.com/64179296/85987729-992ffc00-ba20-11ea-9a2f-ba10f4e566bd.png)

**Comment by zongtanghu** [comment]
You sse  itt.

**Comment by yueyuanyu** [comment]
我也遇到了同样的问题

**Comment by godnm** [comment]
是我搞错了
