### ISSUE TITLE
Replace SyncRequest with AsyncRequest in the dofilter method of DistroFilter to improve performance.

### ISSUE THREAD

**Issue by zongtanghu** [alibaba/nacos#3204]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
(1)Replace SyncRequest with AsyncRequest in the dofilter method of DistroFilter to improve performance.The original code is as below.
![image](https://user-images.githubusercontent.com/5010883/85996045-f97c6900-ba33-11ea-90b2-59a67b145cf0.png)

I think it will be improve performance for DistroFilter if it change to AsyncRequest here.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zongtanghu** [comment]
Do you think it?  @yanlinly @chuntaojun @KomachiSion

**Comment by KomachiSion** [comment]
Can't do with AsyncRequest, because users need a response. If the filter with async, the response content is not right.

**Comment by zongtanghu** [comment]
Okay, I see it.
