### ISSUE TITLE
Nacos 订阅者列表应用名unknown

### ISSUE THREAD

**Issue by Force-King** [alibaba/nacos#3215]
Nacos 服务注册成功，消费者服务也启动成功，已经测试服务消费调用都没有问题。
在使用 订阅者列表 查询某个服务的消费者时，可以查到结果，但是 ip 地址 和 应用名 展示不对：

![image](https://user-images.githubusercontent.com/23328256/86212012-e095c400-bba9-11ea-96eb-f736534b4f79.png)

请问还需要配置什么？ 有具体使用文档吗？

**Comment by KomachiSion** [comment]
方便提供demo 程序吗？ 仅靠现在提示的信息无法判断问题。

应用名如果不填默认都是unknown

地址会不会是获取到了宿主机之类的ip？

**Comment by Force-King** [comment]
> 方便提供demo 程序吗？ 仅靠现在提示的信息无法判断问题。
> 
> 应用名如果不填默认都是unknown
> 
> 地址会不会是获取到了宿主机之类的ip？

地址不对原因知道了，是因为 host 文件配置的 hostname 对应的不是真实ip,nacos 获取的应该是 hostname 吧。
但是应用名还是unknown， 请问应用名在哪里填？ 设置哪个参数？spring.application.name项目里设置了

**Comment by Force-King** [comment]
![image](https://user-images.githubusercontent.com/23328256/86323395-56179800-bc6f-11ea-946e-8cf5166fe71d.png)

如上图所示，建议增加获取 spring.application.name 配置，返回作为 appName, 因为很多时候，大家都会配spring.application.name，并不会配置 project.name 。

**Comment by yfh0918** [comment]
spingboot is a de facto standard for many applications, and one can be added spring.application.name , the order of priority is project.name after

**Comment by catalpa-tree** [comment]
> ![image](https://user-images.githubusercontent.com/23328256/86323395-56179800-bc6f-11ea-946e-8cf5166fe71d.png)
> 
> 如上图所示，建议增加获取 spring.application.name 配置，返回作为 appName, 因为很多时候，大家都会配spring.application.name，并不会配置 project.name 。

配置了project.name=test还是显示unknown，client版本1.3.3
![image](https://user-images.githubusercontent.com/69246580/106410000-d65be100-647c-11eb-875c-2350a8d231a4.png)

**Comment by catch6** [comment]
1.4.1也有这个问题，建议使用`spring.application.name`

**Comment by wushuaiping** [comment]
spring cloud alibaba nacos 2021.0.1.0也有这个问题，建议增加spring.application.name

**Comment by lance-yi** [comment]
建议直接使用spring.application.name

**Comment by gyxxxx** [comment]
> > ![image](https://user-images.githubusercontent.com/23328256/86323395-56179800-bc6f-11ea-946e-8cf5166fe71d.png)
> > 如上图所示，建议增加获取 spring.application.name 配置，返回作为 appName, 因为很多时候，大家都会配spring.application.name，并不会配置 project.name 。
> 
> 配置了project.name=test还是显示unknown，client版本1.3.3 ![image](https://user-images.githubusercontent.com/69246580/106410000-d65be100-647c-11eb-875c-2350a8d231a4.png)

你这样在配置文件设置没有用，源码是用系统环境变量获取的，想要生效需要这样设置：System.setProperty("project.name", "test")

**Comment by laughingwong001-netizen** [comment]
我是用的nacos client 2.4.1,nacos server版本是V2.2.0，查看了nacos client 2.4.1的AppNameUtil不会从spring.application.name或者是dubbo.application.name读取项目名称，目前可行方案就是在JVM启动参数里加-Dproject.name=XXXX-service。。。。
