### ISSUE TITLE
Nginx反代Nacos集群后无法发送DELETE请求

### ISSUE THREAD

**Issue by SealinRepo** [alibaba/nacos#3216]
使用example启动集群后,将默认转发的8848-8850端口使用nginx做一个统一反代.
配置如下:
![image](https://user-images.githubusercontent.com/14067275/86213675-a974e200-bbac-11ea-93d1-b148cd745512.png)

功能使用正常, 但是无法在页面上删除配置,如图
![image](https://user-images.githubusercontent.com/14067275/86213951-11c3c380-bbad-11ea-8d52-7698abeb3ba2.png)

看了Nginx错误是跟我的IP断开了链接(超时了), 怀疑是8848-8850有策略没返回数据给nginx
![image](https://user-images.githubusercontent.com/14067275/86213908-01abe400-bbad-11ea-80ef-fd697caf3dfd.png)

奇怪的是我用nginx同网段的服务器用curl -X DELETE去发送请求, 是可以删除的.
![image](https://user-images.githubusercontent.com/14067275/86214234-7c74ff00-bbad-11ea-8ab2-3525da0775d8.png)

目前怀疑是nginx配置有问题,但是除了delete请求, 好像别的功能没什么问题,有大佬能帮忙看看吗?

**Comment by KomachiSion** [comment]
Maybe Refer to #3034

**Comment by sbwfnhn** [comment]
这个是BUG，在上面#3034中已经提到了。原因就是delete请求中加了Request Body,在http1.1标准中，delete请求不能带body。很多反向代理不支持，阿里CDN明确不支持。等待修复吧。

**Comment by junjie-tang99** [comment]
> 这个是BUG，在上面#3034中已经提到了。原因就是delete请求中加了Request Body,在http1.1标准中，delete请求不能带body。很多反向代理不支持，阿里CDN明确不支持。等待修复吧。

这个问题是每个Nacos版本都这样吗？还是只有指定版本才会出现这个问题？

**Comment by hexw** [comment]
用nginx stream 4层负载
