### ISSUE TITLE
作为配置中心无法自动刷新配置

### ISSUE THREAD

**Issue by w39021384** [alibaba/nacos#3218]
在nacos上修改配置之后，控制台没有打印推送日志，应该是没接收到，需要手动调用actuator/refresh才能生效
Spring Boot版本：2.2.5.RELEASE
Spring Cloud版本：Hoxton.SR3

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
please provide more informations about nacos.
