### ISSUE TITLE
配置文件无法修改

### ISSUE THREAD

**Issue by laiyq** [alibaba/nacos#3226]
![image](https://user-images.githubusercontent.com/22766267/86315139-f19f0d80-bc5b-11ea-8b99-f207c91fee4b.png)
编辑配置文件，就算没有修改配置文件点击发布也会出错

**Comment by KomachiSion** [comment]
Please provide version， mode of nacos。

**Comment by KomachiSion** [comment]
Don't have enough information, and no response from author. closed.
