### ISSUE TITLE
after beta published, client received wrong version of config

### ISSUE THREAD

**Issue by chenqinghe** [alibaba/nacos#3230]
## Issue Description

Type: config service *bug report* 

### Describe what happened (or what feature you want)
given that i have two service instances: 192.168.10.1,192.168.10.2, original config:
```toml
version = 1
```
1. edit the config, check Beta publish to 192.168.10.1
```toml
version = 2 
```
192.168.10.1 changed to 2, 192.168.10.2 remains 1. no problem.
2. edit the beta config again, then publish. (the beta publish button is disabled, so cannot beta publish)
```toml
version = 3
```
3. check the config
at nacos:
```toml
version = 3
```
but both of two service instances received config are :
```toml
version = 1 
```

### Describe what you expected to happen
config of two service instances received both changed to "version = 3".

### How to reproduce it (as minimally and precisely as possible)
as described above.

### Tell us your environment
nacos version: 1.2.1  cluster mode, 3 nodes
client: golang with open api

**Comment by lzp0412** [comment]
@chenqinghe Are you using nacos-sdk-go  or using open api directly？

**Comment by chenqinghe** [comment]
@lzp0412 i am using open api directly.

**Comment by chenqinghe** [comment]
in standalone mode works well.

**Comment by KomachiSion** [comment]
@chenqinghe Can you use 1.3.1 version can retry?

**Comment by chenqinghe** [comment]
@KomachiSion  1.3.1 still reproduce the issue.

**Comment by shiyiyue1102** [comment]
"config_info_beta"，what do you see in this table? whether the beta config published successfully? Please provide more information

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem. If new version still has problem, please submit new issues.
