### ISSUE TITLE
nacos does not support batch export config?

### ISSUE THREAD

**Issue by apple987** [alibaba/nacos#3234]
If there are more than 30 configuration items, you need to select a batch of exports across pages. However, this cross page selection batch export function is not supported at present. You can only export one page at a time and then sort it out by yourself. It is recommended to support cross page selection for batch export of backup configuration parameters，This is especially troublesome when manually copying configuration items between several different libraries！
need this feature! thanks!

**Comment by KomachiSion** [comment]
We has no plan to do this for now.

**Comment by KomachiSion** [comment]
Community has no plan to implement this feature, and no body want to discuss this feature more than 21 days. close issue
