### ISSUE TITLE
Can gray scale publishing only fill in IP?

### ISSUE THREAD

**Issue by apple987** [alibaba/nacos#3238]
When using grayscale publishing, Nacos is on the same machine as the service. When configuring the local IP address of gray publishing directly, the configuration obtained by the program does not take effect. When writing 127.0.0.1, it can be used again. What is the reason? What's the matter?

**Comment by KomachiSion** [comment]
No, current it's an auto gray feature.

you can register service and instance with `enable=false`, and set as true one by one to get it.

**Comment by KomachiSion** [comment]
And for config center, it seems that the configuration will be apply for all subsribers.

**Comment by KomachiSion** [comment]
No repsonce more than 7 days, closed
