### ISSUE TITLE
Nacos spring cloud wants to support config group

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#3240]
nacos作为注册中心，应用A有多个集群环境，cluster1和cluster2；那么应用B调用应用A服务的时候，怎么保证应用B调用应用A集群实例是cluster1而不会负载到cluster2集群的实例中

**Comment by KomachiSion** [comment]
通过设置实例的namespace，group，cluster都可以隔离，使用哪个都可以

**Comment by HelloHaiNG** [comment]
> 通过设置实例的namespace，group，cluster都可以隔离，使用哪个都可以

我看源码中实例的group好像不能设置，只能是默认的DEFAULT_GROUP

**Comment by HelloHaiNG** [comment]
> 通过设置实例的namespace，group，cluster都可以隔离，使用哪个都可以

源码中实例没有group这个属性，应用也没办法指定group的指，只有namespac和cluster可以指定

**Comment by HelloHaiNG** [comment]
问题是我应用B通过应用名去调用应用A的时候，怎么保证应用A有两个集群的情况下，应用B调用应用A的时候负载的时候不会在两个应用A集群之间跳来跳去

**Comment by KomachiSion** [comment]
1. namespace，group， cluster都是实例的上层概念，实例中有没有这些属性并不影响发现的时候进行隔离。
2. sdk接口NacosNamingService.registerInstance(String serviceName, String groupName, String ip, int port) 了解一下
3. 应用进行发现的时候 是可以指定namespace，group，cluster的，如果不指定就都是默认值，这样就会走到一个默认族群里，如果指定了的话，他就只会发现在这个族群里的实例，自然就不会跳来跳去了。

**Comment by HelloHaiNG** [comment]
> 1. namespace，group， cluster都是实例的上层概念，实例中有没有这些属性并不影响发现的时候进行隔离。
> 2. sdk接口NacosNamingService.registerInstance(String serviceName, String groupName, String ip, int port) 了解一下
> 3. 应用进行发现的时候 是可以指定namespace，group，cluster的，如果不指定就都是默认值，这样就会走到一个默认族群里，如果指定了的话，他就只会发现在这个族群里的实例，自然就不会跳来跳去了。

如果是通过直接调用接口的方式注册应用确实可以指定实例的group,namspace,cluster这几个属性，但是如果通过配置文件的形式来注册实例，貌似目前并不支持自定义group

**Comment by KomachiSion** [comment]
> > 1. namespace，group， cluster都是实例的上层概念，实例中有没有这些属性并不影响发现的时候进行隔离。
> > 2. sdk接口NacosNamingService.registerInstance(String serviceName, String groupName, String ip, int port) 了解一下
> > 3. 应用进行发现的时候 是可以指定namespace，group，cluster的，如果不指定就都是默认值，这样就会走到一个默认族群里，如果指定了的话，他就只会发现在这个族群里的实例，自然就不会跳来跳去了。
> 
> 如果是通过直接调用接口的方式注册应用确实可以指定实例的group,namspace,cluster这几个属性，但是如果通过配置文件的形式来注册实例，貌似目前并不支持自定义group

不清楚你用的是什么配置文件，最好是能提issue到对应工程里。或者在这里提供足够的信息，不然仅以nacos项目，是支持的。

**Comment by HelloHaiNG** [comment]
> > > 1. namespace，group， cluster都是实例的上层概念，实例中有没有这些属性并不影响发现的时候进行隔离。
> > > 2. sdk接口NacosNamingService.registerInstance(String serviceName, String groupName, String ip, int port) 了解一下
> > > 3. 应用进行发现的时候 是可以指定namespace，group，cluster的，如果不指定就都是默认值，这样就会走到一个默认族群里，如果指定了的话，他就只会发现在这个族群里的实例，自然就不会跳来跳去了。
> > 
> > 
> > 如果是通过直接调用接口的方式注册应用确实可以指定实例的group,namspace,cluster这几个属性，但是如果通过配置文件的形式来注册实例，貌似目前并不支持自定义group
> 
> 不清楚你用的是什么配置文件，最好是能提issue到对应工程里。或者在这里提供足够的信息，不然仅以nacos项目，是支持的。

![企业微信截图_15940011638073](https://user-images.githubusercontent.com/33769220/86548829-5dd98400-bf70-11ea-8972-0806f6943fa5.png)
如上图中使用nacos作为注册在配置文件中NacosDiscoveryProperties并没有group这个字段可以设置；然后看了源码发现没有设置就是默认值

**Comment by KomachiSion** [comment]
https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java

我发现新版本spring-cloud-alibaba-nacos-discovery是可以设置的，具体使用问题可以提到apring-cloud-alibaba项目去。
