### ISSUE TITLE
can not start up nacos server

### ISSUE THREAD

**Issue by AlbertoWang** [alibaba/nacos#3244]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)

when using startup.sh, nacos server can not establish, here is the print from terminal:
 
/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/alberto/Downloads/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre/lib/ext:/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/lib/ext -Xloggc:/Users/alberto/Downloads/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/alberto/Downloads/nacos/plugins/health,/Users/alberto/Downloads/nacos/plugins/cmdb,/Users/alberto/Downloads/nacos/plugins/mysql -Dnacos.home=/Users/alberto/Downloads/nacos -jar /Users/alberto/Downloads/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/Users/alberto/Downloads/nacos/conf/ --logging.config=/Users/alberto/Downloads/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos is starting with cluster
nacos is starting，you can check the /Users/alberto/Downloads/nacos/logs/start.out

when I request for localhost:8848/nacos, there is ERR_CONNECTION_REFUSED
### How to reproduce it (as minimally and precisely as possible)

1. just simply run: sh startup.sh standalone

### Tell us your environment

macos
Java version: 1.8.0_221
apache-maven-3.6.1

**Comment by KomachiSion** [comment]
Information is not enough, please provide more information.
Such as version of nacos, yours os, more information, and your cluster.conf.

**Comment by KomachiSion** [comment]
Any more information? If no more response, we will close issue.

**Comment by AlbertoWang** [comment]
It seems that nacos server is started successfully, but the output in terminal is&nbsp;strange





It is supposed to output the start information of nacos server according to the&nbsp;manual





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 上午10:16
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"Fvck"<albertowang@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] can not start up nacos server (#3244)





 
Any more information? If no more response, we will close issue.

**Comment by KomachiSion** [comment]
Maybe when you request ` localhost:8848/nacos`, nacos is starting, so the 8848 port is not ready. After a little seconds waiting, it will be ok.

I will close issue, I think it's not a problem.
