### ISSUE TITLE
Nacos 1.3.0版本控制台配置问题

### ISSUE THREAD

**Issue by gfgfggf1988** [alibaba/nacos#3246]
nacos1.3.0版本，新建properties类型的配置，当配置内容存在#中文说明。点击发布无反应。
如：
【不能发布】#语言本地化 :zh_CN中文，en_US英文
                      bcf.localLan=zh_CN

【可以发布】bcf.localLan=zh_CN

**Comment by gfgfggf1988** [comment]
当发布类型为properties时，存在
bcf.dubbo.namespace=
存在key但是value无内容，也不能在控制台发布

**Comment by KomachiSion** [comment]
duplicate #3103 .
