### ISSUE TITLE
When to support spring boot 2.3 ?

### ISSUE THREAD

**Issue by magiclingfeng** [alibaba/nacos#3247]
Do you have plans to support Spring Boot 2.3 ?

**Comment by KomachiSion** [comment]
Are you means that nacos' client can support spring boot 2.3?
I think we can support spring 2.x if 2.3 do not change spring API.

**Comment by KomachiSion** [comment]
Can you try to use https://github.com/nacos-group/nacos-spring-boot-project?
Or provide your problem information to issues.

**Comment by magiclingfeng** [comment]
The spring boot version I use is 2.3.1. When I generate a project through spring initializr (https://start.spring.io/) and add nacos lib, the prompt is as follows:
<img width="1021" alt="WeChatea7394cadf77ee18119a62da927a5d61" src="https://user-images.githubusercontent.com/6637248/86553406-3e952380-bf7d-11ea-8dd4-0fd17ae3077e.png">

**Comment by KomachiSion** [comment]
@magiclingfeng you can directly add nacos-spring-boot-starter to use.

**Comment by magiclingfeng** [comment]
@KomachiSion Thanks for your reply,I try this program

**Comment by KomachiSion** [comment]
@magiclingfeng Any response?

**Comment by magiclingfeng** [comment]
It works well,sorry for replying late
