### ISSUE TITLE
Spring MVC项目中使用nacos 作为配置中心不能动态刷新的问题

### ISSUE THREAD

**Issue by ltlwill** [alibaba/nacos#3248]
请问下，这是在一个老项目Spring MVC项目中集成nacos作为配置中心，应用可以读取到nacos的配置信息，但是当nacos配置信息修改时不能动态获取，nacos 版本是 1.3.0 ，日志里已经打印出nacos的刷新日志，如图所示：
![{63275B40-25C4-4D32-AECC-83D4CC728474}_20200703172904](https://user-images.githubusercontent.com/16695334/86455031-a287d400-bd52-11ea-9314-eabec090ec58.jpg)

**Comment by ltlwill** [comment]
已经设置了 autoRefreshed = true ，依然不能动态获取配置，
@NacosPropertySource(dataId = "portal.redis.properties", autoRefreshed = true, type = ConfigType.PROPERTIES)
和
@NacosValue(value="${test.name:}",autoRefreshed=true)

**Comment by ltlwill** [comment]
调试发现数据是已经拉取到Environment中了，只是通过@NacosValue注解获取不到最新的数据，如果从Environment中获取，是能获取到最新的数据的，
![图片](https://user-images.githubusercontent.com/16695334/86502631-dce78480-bdd7-11ea-8755-38f4829ac2fb.png)
直接从Environment中能读取到最新数据：

**Comment by KomachiSion** [comment]
the reason seems that contains chinese '：' but not ':'.
