### ISSUE TITLE
Resolve the issues of codestyle of nacos-config module.

### ISSUE THREAD

**Issue by zongtanghu** [alibaba/nacos#3249]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
(1).Resolve the issue of codestyle in the nacos-config module.
(2).You can see the related issue's link: #2992.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
I think you can make the issue as multiple tasks.
