### ISSUE TITLE
获取hostname错误

### ISSUE THREAD

**Issue by ethonchen** [alibaba/nacos#325]
0.5.0的版本，发现有支持hostname功能。
部署到k8s上ip会变化，需要使用此功能
启动时加入了：
-Dnacos.preferHostnameOverIp=true 
-Dnacos.server.ip=mylocal 

不过还有报错：
![image](https://user-images.githubusercontent.com/3139756/48825054-2ae57b00-eda1-11e8-8ad6-9318fbcc2428.png)
com.alibaba.nacos.naming.core.DistroMapper 这个类 474行
![image](https://user-images.githubusercontent.com/3139756/48825094-4fd9ee00-eda1-11e8-8fce-2bc7f646d3f0.png)

获取ip需要修改为判断PREFER_HOSTNAME_OVER_IP
类似

![image](https://user-images.githubusercontent.com/3139756/48825099-5700fc00-eda1-11e8-863d-5d3fb98fa2f2.png)

**Comment by nkorange** [comment]
@ethonchen 你是单机模式吗？

**Comment by ethonchen** [comment]
不是单机模式，集群模式，我修改一下看看

**Comment by ethonchen** [comment]
@pguo65535 push不了develop分支，是需要给我一下权限吗

**Comment by ethonchen** [comment]
另外还有一个问题，k8s里面 ect hosts的设置有两个，和hostname一致的放在后面了。 inetAddress.getCanonicalHostName() 取到的是第一个，用来和 inetAddress.getHostName() 会不一致，这个我也处理一下
![image](https://user-images.githubusercontent.com/3139756/48833149-b5d07080-edb5-11e8-80c9-7dd60651cf74.png)

**Comment by nkorange** [comment]
@ethonchen 如果配置了-Dnacos.preferHostnameOverIp=true，那么你的cluster.conf里面需要配置的是hostname，你的配置是这样的吗？

**Comment by nkorange** [comment]
@ethonchen 请参考这个贡献流程进行修复：https://github.com/alibaba/nacos/blob/master/CONTRIBUTING.md

**Comment by ethonchen** [comment]
@nkorange 是的，配置了cluster.conf里面的hostname
