### ISSUE TITLE
更改配置信息，收到推送，但是没有自动刷新

### ISSUE THREAD

**Issue by wangshiminhome** [alibaba/nacos#3252]
修改配置，项目控制台打印接收到的新的配置信息
![image](https://user-images.githubusercontent.com/46372007/86507419-a0814c00-be0a-11ea-917f-c2fa86a92a69.png)
但是并没有自动刷新，获取到的还是启动时的信息
已添加@RefreshScope注解
![image](https://user-images.githubusercontent.com/46372007/86507448-e0483380-be0a-11ea-9ffd-65752bdc7d27.png)

**Comment by itlemon** [comment]
这个问题也就是说配置热修改没有生效呗。客户端接收到了配置中心的修改，但是内存中的数据并没有被修改

**Comment by itlemon** [comment]
@wangshiminhome 这个问题也就是说配置热修改没有生效呗。客户端接收到了配置中心的修改，但是内存中的数据并没有被修改，对吗

**Comment by xuxi5034241849** [comment]
哈，我也出现了这个问题，不过已经解决了，主要还是版本问题请严格参阅：https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by g0123** [comment]
换了版本还不行呢。控制天一直打印：
17:34:16,638 |-INFO in ReconfigureOnChangeTask(born:1628155576637) - Empty watch file list. Disabling 
17:34:17,912 |-INFO in ReconfigureOnChangeTask(born:1628155277911) - Empty watch file list. Disabling 
17:34:17,940 |-INFO in ReconfigureOnChangeTask(born:1628155277940) - Empty watch file list. Disabling 
17:34:18,070 |-INFO in ReconfigureOnChangeTask(born:1628155278068) - Empty watch file list. Disabling
