### ISSUE TITLE
bootstrap.yml里面的nacos地址无法在nacos应用程序的配置管理里修改，该怎么解决？

### ISSUE THREAD

**Issue by githubzhw** [alibaba/nacos#3254]
spring:
  application:
    name: test
  cloud:
    nacos:
      discovery:
         **server-addr:xxx:8848**
      config:
        **server-addr: xxx:8848**
        file-extension: yaml

**Comment by KomachiSion** [comment]
I can't get your problem. Do you means that you want to change nacos server-addr from nacos console?

**Comment by githubzhw** [comment]
> I can't get your problem. Do you means that you want to change nacos server-addr from nacos console?

是的啊，我该怎么做？

**Comment by SoyMeng** [comment]
最好提第一手需求,因为你这个问题看起来很不合理.
如果想从nacos配置中心获取配置,必须先连接到配置中心

**Comment by KomachiSion** [comment]
Other config center support this problem？
I think the config center address should not be changed.
