### ISSUE TITLE
Nacos 建议支持按项目区分服务下线和配置中心权限

### ISSUE THREAD

**Issue by Force-King** [alibaba/nacos#3255]
Naocs 权限功能目前是否 可以按 项目分配权限？ 

线上环境，会有很多项目，每个项目应该是 只有项目负责人和相关开发人员可以查看编辑。否则线上使用Nacos , 给定namespace线上环境读写权限，所有项目都可以 操作 服务下线、编辑配置，这个很危险。。。

**Comment by KomachiSion** [comment]
现在就就可以设置账号只能有某个namespace的读/写/读写权限

**Comment by Force-King** [comment]
> 现在就就可以设置账号只能有某个namespace的读/写/读写权限

意思是目前 没法 区分项目 纬度的权限是吗？

**Comment by KomachiSion** [comment]
您说的分区指的是什么？ group？

**Comment by Force-King** [comment]
> 您说的分区指的是什么？ group？

我说的是 “区分 ”， 不是 分区。。。

就是怎么可以 分权限的时候，只给 某个用户 看到或者 编辑删除 部分项目的权限，而不是所有项目。

目前用 namespace 区分了环境。 但是同一个 namespace 下有很多项目，如何按项目分配权限？

**Comment by KomachiSion** [comment]
目前没有这个功能，而且从nacos的角度也没有项目这个抽象概念。
