### ISSUE TITLE
What's the supported JDK version about the nacos-client?

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/nacos#3257]
## Issue Description
Type: *question*

### Describe what happened (or what feature you want)
After several times of investigation, we think Nacos is appropriate to our core credit card system. But now our core credit card system's JDK version is 6. So I want to know whether the nacos-client can run well under the JDK 6. And we will not use the annotations to ease for the development.

**Comment by KomachiSion** [comment]
Nacos SDK support for JDK 6.

**Comment by KomachiSion** [comment]
@junjie-tang99 , I found that there are some trouble in 1.3.0 SDK, some one change SDK compile to 7, but it should be 6. We will fix it in new verision.

**Comment by junjie-tang99** [comment]
Hi @KomachiSion , thank you for your prompt answer. If I use the nacos-server-1.2.1 and nacos-client-1.2.1 not using 1.3.0, that is OK? It can support for JDK 6?

**Comment by KomachiSion** [comment]
> Hi @KomachiSion , thank you for your prompt answer. If I use the nacos-server-1.2.1 and nacos-client-1.2.1 not using 1.3.0, that is OK? It can support for JDK 6?

1.2.1 client support JDK6.
