### ISSUE TITLE
why ConfigDataChangeEvent fired twice when new config file 

### ISSUE THREAD

**Issue by fengsmith** [alibaba/nacos#3258]
I have a question, why ConfigDataChangeEvent fired twice when new config file.
 
![image](https://user-images.githubusercontent.com/6457270/86561909-4f04c880-bf94-11ea-99ce-e977182166c9.png)
![image](https://user-images.githubusercontent.com/6457270/86561962-66dc4c80-bf94-11ea-9c7f-b58dee7d66cb.png)

**Comment by chuntaojun** [comment]
already refactor this logic

**Comment by fengsmith** [comment]
thanks.
