### ISSUE TITLE
服务下线后，日志一直刷自动删除，但是没有真正的删除掉，5s间隔刷新日志

### ISSUE THREAD

**Issue by qihaooo** [alibaba/nacos#3261]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by qihaooo** [comment]
![image](https://user-images.githubusercontent.com/26671062/86569857-a3627500-bfa1-11ea-931c-fd983c43cfcc.png)

**Comment by KomachiSion** [comment]
Versions of nacos? What's mode of nocos, standalone?

**Comment by KomachiSion** [comment]
Please describe and provide detail information of nacos, otherwise no one can help you.

**Comment by chuntaojun** [comment]
Do you mean that the service is offline means that it is set to non-external service, or the instance is closed
