### ISSUE TITLE
老哥求你了，官网扔个下载地址吧！

### ISSUE THREAD

**Issue by KiritoGit** [alibaba/nacos#3263]
在github下载太痛苦了，这下载要一个多小时啊！
![GWOB90L0($E~W9IQPSS~QX3](https://user-images.githubusercontent.com/48933983/86700688-e5dc8e00-c043-11ea-8cb0-1ab66de912d7.png)

**Comment by YEYEAKEI** [comment]
F12，复制下载链接，丢进迅雷或者其他下载软件

**Comment by hdr893487191** [comment]
迅雷下载还可以。

**Comment by geekzhi** [comment]
不会翻墙算什么程序员（🐶🐶🐶）

**Comment by KiritoGit** [comment]
> 不会翻墙算什么程序员（🐶🐶🐶）

谁说我不会翻墙！我在阿里云买的服务器搭了SS然后被阿里封了IP🐶🐶🐶

**Comment by geekzhi** [comment]
> > 不会翻墙算什么程序员（🐶🐶🐶）
> 
> 谁说我不会翻墙！我在阿里云买的服务器搭了SS然后被阿里封了IP🐶🐶🐶

哈哈哈 正常操作

**Comment by chuntaojun** [comment]
百度网盘还好吧，readme有连接的

**Comment by htynkn** [comment]
readme文件有百度网盘链接

**Comment by Force-King** [comment]
> > 不会翻墙算什么程序员（🐶🐶🐶）
> 
> 谁说我不会翻墙！我在阿里云买的服务器搭了SS然后被阿里封了IP🐶🐶🐶

肯定是你看了什么不该看的视频。。。😂
