### ISSUE TITLE
Only ROLE_ADMIN has access to api: POST /v1/cs/configs/listener

### ISSUE THREAD

**Issue by xiaozhongliu** [alibaba/nacos#3264]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Only the default account (whose role is ROLE_ADMIN) has access to api: POST /v1/cs/configs/listener.
Other accounts result in 403.

### Describe what you expected to happen
If an account has permission on a data item, it should have access to api: POST /v1/cs/configs/listener.

### How to reproduce it (as minimally and precisely as possible)
1. enable auth.
2. subscribe data change by calling api: POST /v1/cs/configs/listener.
3. it results in 403 if I don't use the default account (whose role is ROLE_ADMIN).

### Tell us your environment
MacOS Catalina
Nacos 1.3.0

**Comment by KomachiSion** [comment]
Have you empower other roles？If you do not give auth to other roles, they should get an 403.

**Comment by xiaozhongliu** [comment]
> Have you empower other roles？If you do not give auth to other roles, they should get an 403.

The account is bound a role created with permission on the target namespace.

**Comment by chuntaojun** [comment]
Are you calling open-api yourself, or operating the client，Paste some of your operation code

**Comment by xiaozhongliu** [comment]
> Are you calling open-api yourself, or operating the client，Paste some of your operation code

call the api directly:
**address**: http://127.0.0.1:8848/nacos/v1/cs/configs/listener?accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTU5NDM2Njg2MH0.ZT-OmEUi0uh3x_FcJHmRiWfaBYMY2rmhavuQpXi_gsM
**form-data before conversion**: 
{Listening-Configs:"config.dev.jsk8s-demo-bff144c9defac04969c7bfad8efaa8ea194007a6bb2-819e-47b7-a9f1-ef7008315c82"}
**headers**:
content-type:"multipart/form-data; boundary=--------------------------683220095963157563443209"
Long-Pulling-Timeout:30000

**Comment by xiaozhongliu** [comment]
> > Are you calling open-api yourself, or operating the client，Paste some of your operation code
> 
> Call the api directly:
> **address**: http://127.0.0.1:8848/nacos/v1/cs/configs/listener?accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTU5NDM2Njg2MH0.ZT-OmEUi0uh3x_FcJHmRiWfaBYMY2rmhavuQpXi_gsM
> **form-data before conversion**:
> {Listening-Configs:"config.dev.js�k8s-demo-bff�144c9defac04969c7bfad8efaa8ea194�007a6bb2-819e-47b7-a9f1-ef7008315c82�"}
> **headers**:
> content-type:"multipart/form-data; boundary=--------------------------683220095963157563443209"
> Long-Pulling-Timeout:30000
> 
> My sdk is written in nodejs(typescript), so I think it's more convenient to directly provide info as above.
> The same code works normally only for the default provided nacos/nacos account...
> 
> Please tell me if you need my code to directly run to reproduce the issue.

**Comment by xiaozhongliu** [comment]
@KomachiSion I see the issue is removed from the next milestone. May I know if there would be any further plan?
In my opinion, this is an important blocking issue. That is, authorization only works from the UI console, but not when long polling from an server side app.

**Comment by xiaozhongliu** [comment]
Resolved. Find the clue by debugging source code of nacos server.

**Comment by yu4452715** [comment]
> 解决。通过调试nacos服务器的源码找到线索。

怎么解决啊
