### ISSUE TITLE
Failed to create namespace

### ISSUE THREAD

**Issue by johnxiaohe** [alibaba/nacos#3265]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/37014780/86740195-0834d280-c069-11ea-8073-8ae61c1152d9.png)
![image](https://user-images.githubusercontent.com/37014780/86740278-1aaf0c00-c069-11ea-9a66-9e1bf3ccca27.png)

I can`t create namespace. 

### Describe what you expected to happen

create new namespace 

### How to reproduce it (as minimally and precisely as possible)

1. version： 1.21
2. use db : mysql(localhost)   and  load conf/nacos-mysql.sql file
3. create new namespace

**Comment by johnxiaohe** [comment]
download file is  .zip file

**Comment by TsingLiang** [comment]
I have tested 1.2.1. There is  no problem. If there are some pages cached?

**Comment by johnxiaohe** [comment]
No , I just use it of first time,just .zipfile  . But .tar.gz version is no problem , but it have other issuse : When I want export more than one pages  ,result just get the last page config 
我用.zip版本才会有问题。.tar.gz不会有这个问题出现。我重复下载多次也不好使。然后我就换成.tar.gz就没有问题了。但是.tar.gz我一次选择两个页面的配置导出好像只能导出最后一页的。因为再导入的时候只有最后一页的配置存在。

**Comment by KomachiSion** [comment]
@johnxiaohe can you use newest version and retry? If still can't create namespace, please let us know if this issue.

If can create namespace, please close issue.

If have other problem, I think create an new issue will be better, the issue is only for can't create namespace.
