### ISSUE TITLE
Inform the ACM SDK of the RAM role name and access the configuration   ? ?

### ISSUE THREAD

**Issue by xjhuiw** [alibaba/nacos#327]
How does nacos-client configure the ram role with a yml or property file to support the ram role in accessing the ali cloud product

**Comment by yanlinly** [comment]
this way：
-Dsecurity.credentials.url=http://100.100.100.200/latest/meta-data/ram/security-credentials/${你ECS绑定的 ECS Role}

**Comment by nkorange** [comment]
Already support RAM.
