### ISSUE TITLE
1.3.1-BETA SDK LifeCycle can't shutdown some thread executors.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#3275]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

In 1.3.1-BETA SDK, NamingServer add shutdown method to close and release resource of nacos sdk.

But for my test, It can't close executors completely. 

`com.alibaba.nacos.naming.push.receiver`
`com.alibaba.nacos.naming.client.listener`

This two threads almost keep alive

`com.alibaba.nacos.naming.failover`

the thread keep alive sometime.

### Describe what you expected to happen

After I call shutdown method, the thread and udp created by nacos should closed.

### How to reproduce it (as minimally and precisely as possible)

example code
```
    public static void testShutDown() throws NacosException, InterruptedException {
        Properties properties = new Properties();
        properties.setProperty("serverAddr", "localhost:8848");
        for (int i = 0; i < 10; i++) {
            NamingService naming = NamingFactory.createNamingService(properties);
            naming.registerInstance("nacos.test.3", "11.11.11.11", 8888, "TEST1");
            System.out.println(naming.getAllInstances("nacos.test.3"));
            naming.shutDown();
            TimeUnit.SECONDS.sleep(1);
        }
        while (true) {
            // for dump thread
            TimeUnit.SECONDS.sleep(10);
        }
    }
```

### Tell us your environment

Any version of nacos Server.
1.3.1-BETA nacos java SDK

**Comment by zongtanghu** [comment]
This issue can be assigned to me, I will put forward a pr to fix it. @KomachiSion

**Comment by zongtanghu** [comment]
I hava already tested in my local machine.The test picture is as below:

![image](https://user-images.githubusercontent.com/5010883/86888772-514e5a80-c12d-11ea-9e1a-63cb0c0e6883.png)

And I will put forward a pr. @KomachiSion

**Comment by zongtanghu** [comment]
The pr has already been merged, so this issue can be close.
