### ISSUE TITLE
Nacos namespace quota(Nacos命名空间容量问题反馈)

### ISSUE THREAD

**Issue by zls1099** [alibaba/nacos#3276]
English:

> The Nacos console gets the details of the namespace, and the case of the namespace capacity is dead
`Namespace namespaceTmp = new Namespace( tenantInfo.getTenantId (), tenantInfo.getTenantName (), 200, configCount, 2);`

> `configService.publishConfig (dataid, group, content);'publish configuration exceeds 200, display 'quantity / 200`

> Whether the namespace size exceeds capacity detection when it is not published

中文：

> nacos控制台获取命名空间详情，命名空间容量大小写死
`Namespace namespaceTmp = new Namespace(tenantInfo.getTenantId(), tenantInfo.getTenantName(), 200, configCount, 2);

> `configService.publishConfig(dataId, group, content);`发布配置超过200，显示 `数量/200`

> 命名空间大小并无发布时是否超过容量检测

**Comment by KomachiSion** [comment]
Which version do you used?

**Comment by zls1099** [comment]
> Which version do you used?

1.3.0

**Comment by chuntaojun** [comment]
这并无影响，目前容量管理还没有集成

**Comment by zls1099** [comment]
> 这并无影响，目前容量管理还没有集成

测试后发现是没有影响。但是吧，如果容量没有集成，但是控制台页面显示了个写死的，这个会让用户觉得产品不成熟，都不敢上生产

**Comment by zls1099** [comment]
No problem
