### ISSUE TITLE
Can't get config content from nacos, which seems to be caused by the dismatch between the interface exposed by nacos and the client jar.

### ISSUE THREAD

**Issue by guzhangyu** [alibaba/nacos#3278]
## Issue Description

Can't get config content from nacos, which seems to be caused by the dismatch between the interface exposed by nacos and the client jar.

### Describe what happened (or what feature you want)
Could not get the config content from nacos.

### Describe what you expected to happen
I want to get the config content from nacos.

### How to reproduce it (as minimally and precisely as possible)

1. 
config in nacos:
Data Id: demo_config.yaml
Group: DEFAULT_GROUP
MD5: 1e33cc4f81103558caa59699d68bba52
Config Content：testProp: test

2. 
String serverAddr = "localhost:8848";
        String dataId = "demo_config.yaml";
        String group = "DEFAULT_GROUP";
        Properties properties = new Properties();
        properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
        properties.put("namespace", "public");
        ConfigService configService = NacosFactory.createConfigService(properties);
        String content = configService.getConfig(dataId, group, 5000);
        System.out.println(content);
3. 

### Tell us your environment
nacos: 1.3.0
client maven dependency:
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>

**Comment by chuntaojun** [comment]
If your namespace is preset, please do not set the namespace

**Comment by guzhangyu** [comment]
I remove the namespace set,it returns the same result.In fact, I debugged the http request, and found that it requests "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=demo_config.yaml&group=DEFAULT_GROUP", then it returns the result:"config data not exist".

I checked the browser's request, and found that the request "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=demo_config.yaml&group=DEFAULT_GROUP&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate", returns the result:"{"totalCount":1,"pageNumber":1,"pagesAvailable":1,"pageItems":[{"id":"254802415819173888","dataId":"demo_config.yaml","group":"DEFAULT_GROUP","content":"testProp: test","md5":null,"tenant":"","appName":"","type":""}]}".

**Comment by chuntaojun** [comment]
you deploy nacos is cluster mode？

**Comment by guzhangyu** [comment]
standardalone mode

**Comment by chuntaojun** [comment]
> standardalone mode

Re-download the docker image, or download 1.3.0 from the github release and re-install; or use stand-alone + mysql mode

**Comment by guzhangyu** [comment]
ok, this problem is resolved by using the stand-alone + mysql mode. And then there is another one.
Environment:
application.yaml:
```
server:
  port: 8865

spring:
  application:
    name: demo_config.yaml

  cloud:
    nacos:
      config:
        namespace:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
```

nacos config:
![image](https://user-images.githubusercontent.com/5295320/87114091-4d901480-c2a2-11ea-985a-fca33d4def6a.png)

It can't get the configured value, then I debug and find that:
![image](https://user-images.githubusercontent.com/5295320/87114302-d73fe200-c2a2-11ea-9b03-00f310bfa5d5.png)

**Comment by chuntaojun** [comment]
this spring-cloud-alibaba  problem，I think you should ask them
