### ISSUE TITLE
The forked VM terminated without saying properly goodbye. VM crash or System.exit called

### ISSUE THREAD

**Issue by qwfys** [alibaba/nacos#3284]
## Issue Description

Type: *bug report* 

### Describe what happened 

In the process of compiling and packaging the command `mvn -Prelease-nacos clean install -U` on openjdk-11, an exception occurred in the test. The exception information is as follows.

```
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/lwk/Downloads/.tmp/nacos-1.3.0/common && /usr/lib/jvm/java-11-openjdk-amd64/bin/java -javaagent:/home/lwk/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/home/lwk/Downloads/.tmp/nacos-1.3.0/common/target/jacoco.exec -jar /home/lwk/Downloads/.tmp/nacos-1.3.0/common/target/surefire/surefirebooter10118149894726719252.jar /home/lwk/Downloads/.tmp/nacos-1.3.0/common/target/surefire 2020-07-09T10-53-40_463-jvmRun1 surefire5255478668029622040tmp surefire_112151400011121181144tmp
Error occurred in starting fork, check output in log
Process Exit Code: 134
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)

```

### Describe what you expected to happen

According to the explanation on https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi, the main problem occurs when there is no adaptation for openjdk11, especially the maven-surefire-plugin version does not adapt to openjdk11.

### Tell us your environment

Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-40-generic", arch: "amd64", family: "unix"

**Comment by KomachiSion** [comment]
If maven-surefire-plugin can't support openjdk11, I think you should open issue to maven-surefire-plugin not here.
