### ISSUE TITLE
集群非LEADER的节点疯狂打config.log

### ISSUE THREAD

**Issue by pengyonglei** [alibaba/nacos#3285]
nacos版本: 1.3.0

问题描述: 我们的集群有三台机器: 172.16.159.165:8848, 172.16.159.166:8849, 172.16.159.167:8850. 
现在 172.16.159.167:8850 这一台是LEADER, 其他两台是FOLLOWER. 现在LEADER的${user.home}/logs/nacos/config.log打印正常. 见下图: 
![image](https://user-images.githubusercontent.com/11027128/86993416-8bc00200-c1d6-11ea-9d2e-191a7a0982c2.png)

172.16.159.166:8849 这台的config.log见下图:

![image](https://user-images.githubusercontent.com/11027128/86993466-a98d6700-c1d6-11ea-8186-f681a8d12dee.png)

172.16.159.165:8848 这台的config.log见下图:

![image](https://user-images.githubusercontent.com/11027128/86993512-c0cc5480-c1d6-11ea-8bea-b0c8dbecbacc.png)

不正常的日志都去连接 127.0.0.1_8848. 不知道什么情况. 但是整个集群服务是可用的. 而且我试了即使我把nacos的节点kill掉. config.log仍然在输出. 求解, 如何解决这个问题

**Comment by KomachiSion** [comment]
这个日志是客户端打的不是服务端，请确认这台机器上没有启动nacos客户端。

**Comment by pengyonglei** [comment]
请问有没有办法找到是哪个客户端打印出来的日志呢? 我的服务器上面启动了很多个客户端的, 但是我查了连接的服务器地址都没有127.0.0.1:8848这个地址

**Comment by KomachiSion** [comment]
如果是测试用的客户端，可以把该机器上有依赖过nacos-client的应用逐个停止，看下是哪个客户端。

目前nacos-client没有在日志中记录是哪个客户端打印的日志，这点可能是需要优化的地方。

另外这个客户端指的是nacos-client，不是nacos-server，为了避免歧义再声明一下

**Comment by pengyonglei** [comment]
排查了一下, 的确是有一个依赖了 nacos-client 的服务没有指定 nacos.config.server-addr 导致的问题, 非常感谢您的思路排查. @KomachiSion
