### ISSUE TITLE
After the official YAML deployment to K8S, the nacos cluster failed to start.

### ISSUE THREAD

**Issue by Yangstatus** [alibaba/nacos#3291]
#2879 # Describe what you expected to happen

Log in to the administrative console after successful nacos cluster deployment

### How to reproduce it (as minimally and precisely as possible)

1. 查看naming-raft.log日志， INFO信息 2020-07-10 10:15:28,146 INFO leader timeout, start voting,leader: null, term: 3254
2. 查看naming-server.log日志, ERROR信息 java.io.IOException: failed to req API:http://nacos-1.nacos.default.svc.cluster.local:8848/nacos/v1/ns/operator/cluster/state. code:500 msg: java.net.ConnectException: Connection refused (Connection refused)

3. 查看conf/cluster.conf 文件， 配置信息 nacos-0.nacos.default.svc.cluster.local:8848
nacos-1.nacos.default.svc.cluster.local:8848
nacos-2.nacos.default.svc.cluster.local:8848

### Tell us your environment
k8s 1.16.3   Persistent NFS

**Comment by KomachiSion** [comment]
One question: 2879 has related with your problem? I see it seems two different problem.

**Comment by KomachiSion** [comment]
And for your problem. You should check first in your pods that you pods can connect to other two pods. 
If they can connect, please provide your nacos version, and the storage you used (mysql or embedded).

**Comment by Yangstatus** [comment]
> 
> 
> And for your problem. You should check first in your pods that you pods can connect to other two pods.
> If they can connect, please provide your nacos version, and the storage you used (mysql or embedded).

I tried to change the YAML template before deploying, but now I have a new problem.  
Look at the POD log display 

Hosts in list: nacos-headless.default.svc.cluster.local
2020/07/10 15:29:14 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.default.svc.cluster.local
Hosts in list: nacos-headless.default.svc.cluster.local
2020/07/10 15:29:15 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.default.svc.cluster.local
Hosts in list: nacos-headless.default.svc.cluster.local

**Comment by Yangstatus** [comment]
My YAML template is shown below:

cat  nacos-pvc-nfs.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.db.name: "nacos_devtest"
  mysql.port: "3306"
  mysql.user: "nacos"
  mysql.password: "nacos"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nfs-client-provisioner
      initContainers:
        - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/home/nacos/plugins/peer-finder"
              name: plugindir
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SERVICE_NAME
              value: "nacos-headless"
            - name: DOMAIN_NAME
              value: "cluster.local"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
          volumeMounts:
            - name: plugindir
              mountPath: /home/nacos/plugins/peer-finder
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: plugindir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: datadir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: logdir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
  selector:
    matchLabels:
      app: nacos

**Comment by KomachiSion** [comment]
It's k8s setting problem, Nacos get local host but the host is not your config host. So have the logs.

**Comment by Yangstatus** [comment]
> 
> 
> It's k8s setting problem, Nacos get local host but the host is not your config host. So have the logs.

Which configuration I need to change to fix these problems？    thanks！

**Comment by Yangstatus** [comment]
> 
> 
> It's k8s setting problem, Nacos get local host but the host is not your config host. So have the logs.

I've solved this problem. It's my configuration file.Probably related to the NACOS Service Type! 
The initialized service has no IP, only port 8848 is open！

nacos-headless                                            ClusterIP   None            <none>        8848/TCP                     5m13s


Thank you for your help ！♥
