### ISSUE TITLE
feign与nacos疑问

### ISSUE THREAD

**Issue by wpt191** [alibaba/nacos#3292]
Dear Alibaba Engineers:
         目前我们在用nacos作为服务注册中心，微服务之间调用用的是feign，但我们发现一个现象，当A调用B服务器的时候，A与B必须在nacos中心的同一个group下。我这边想咨询下，feign在进行远程服务调用的时候，两个服务可以在不同的group不。

**Comment by KomachiSion** [comment]
Nacos 可以通过3种方式隔离服务，Namespace，group和cluster。

只有在同一个namespace和group下的服务可以被发现。

cluster同样也可以进行隔离，但是只隔离实例级别。

**Comment by wpt191** [comment]
那我们有一个问题，类似淘宝这样庞大的系统，服务间调用比较复杂，注册中心都需要在一个group下吗？

**Comment by wpt191** [comment]
感谢您的答复，祝好

**Comment by arjenzhou** [comment]
@KomachiSion 
Hi, I encountered the same issue while using feign and Nacos, which are in the **same** group. 
But the feign cannot invoke the docker service in the different host while the same host can do.

**Comment by arjenzhou** [comment]
The two hosts were in one same swarm cluster, and can be found in Nacos dashboard.

**Comment by arjenzhou** [comment]
Resolved by creating docker overlay network.
