### ISSUE TITLE
在Nacos-config 2.1.2版本中，配置已从nacos拉去，但 spring上下文无法识别和加载配置

### ISSUE THREAD

**Issue by lgxisbb** [alibaba/nacos#3296]
## Issue Description
从2.1.1升级到2.1.2,  所有的配置无法被 spring 读取
2.1.1 完全正常读取, 在pom中,升级版本之后, 出现配置项无法被读取

Case 1: data has been pulled from Nacos to local
Case 2: when spring reads the configuration through propertysourcespropertyresolver, the loaded data cannot be read. Ssible)
情况1 : 数据已经从nacos拉取到本地
情况2: spring 通过PropertySourcesPropertyResolver读取配置的时候, 加载的数据无法被读取

![image](https://user-images.githubusercontent.com/33345078/87159551-1d716180-c2f4-11ea-8e79-9563dd0bff3b.png)

### How to reproduce it (as minimally and precisely as possible)

nacos-config version 2.1.1 to 2.1.2 

### Anything else we need to know?

Type: *bug report* or *feature request*

**Comment by KomachiSion** [comment]
spring-cloud？

**Comment by lgxisbb** [comment]
> spring-cloud？

yes!  in spring cloud  Greenwich.SR4

**Comment by KomachiSion** [comment]
Please use newest version of spring-cloud and retry, If problem still, please submit issue to Spring-cloud-alibaba community.
