### ISSUE TITLE
Bug in nacos-sdk-python

### ISSUE THREAD

**Issue by Aknifejackzhmolong** [alibaba/nacos#3297]
## Issue Description

Type: *bug report*

### Describe what happened

Description: The NacosRequestException and 500 error are raised while the parameter filled in the function like "client.add_naming_instance(service_name='rpi-test',ip='11.11.11.11',port=8088)"

> WARNING:root:[do-sync-req] server:121.36.31.116:8848 is not available for reason:
ERROR:root:[do-sync-req] 121.36.31.116:8848 maybe down, no server is currently available
ERROR:root:[add-naming-instance] exception All server are not available occur
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 581, in add_naming_instance
    resp = self._do_sync_req("/nacos/v1/ns/instance", None, None, params, self.default_timeout, "POST")
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 452, in _do_sync_req
    raise NacosRequestException("All server are not available")
nacos.exception.NacosRequestException: All server are not available
Traceback (most recent call last):
  File "/home/pi/Downloads/nacos/nacos-client.py", line 27, in <module>
    client.add_naming_instance(service_name='rpi-test',ip='11.11.11.11',port=8088)
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 581, in add_naming_instance
    resp = self._do_sync_req("/nacos/v1/ns/instance", None, None, params, self.default_timeout, "POST")
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 452, in _do_sync_req
    raise NacosRequestException("All server are not available")
nacos.exception.NacosRequestException: All server are not available

### How to reproduce it

Environment:
1. run in raspberry pi4B
2. run in OS like 2020-02-05-raspbian-buster-full
3. python 3.7.3
4. use function "client.add_naming_instance" with just three required parameters included service_name,ip,port

### Anything else we need to know?

It's maybe a solution:

I found it caused by "cluster_name" and "cluster_name" when they are None instead of ''.
it equal the comand below.
> curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?ip=11.11.11.11&port=8088&serviceName=rpi-test&weight=1.0&enable=True&healthy=True&metadata=None&clusterName=None'

And, client.add_naming_instance(service_name='rpi-test',ip='11.11.11.11',port=8088,cluster_name='',metadata='') is available

**Comment by KomachiSion** [comment]
I suggest open a issue in [nacos-gourp/nacos-sdk-python](https://github.com/nacos-group/nacos-sdk-python) and refer to this issue.

**Comment by Aknifejackzhmolong** [comment]
> I suggest open a issue in [nacos-gourp/nacos-sdk-python](https://github.com/nacos-group/nacos-sdk-python) and refer to this issue.

You're right
