### ISSUE TITLE
@NacosValue 相同key配置数据初始化解析问题

### ISSUE THREAD

**Issue by July-X** [alibaba/nacos#3303]
## Issue Description

```
@Data
@Configuration
@NacosPropertySource(dataId = "nacos-config-card.properties", autoRefreshed = true)
public class CardConfig {
    private final Logger logger = LoggerFactory.getLogger(CardConfig.class);
    @NacosValue(value = "${card.number:25}", autoRefreshed = true)
    private int number;
    @NacosValue(value = "${card.suit}", autoRefreshed = true)
    private String suit;

    @NacosConfigListener(dataId = "nacos-config-card.properties")
    public void defMessage(String config) {
        logger.info("default" + config);
    }
}
```

```
@Data
@Configuration
@NacosPropertySource(dataId = "nacos-config-card-gp.properties", groupId = "DEV_GROUP", autoRefreshed = true)
public class GpCardConfig {
    private final Logger logger = LoggerFactory.getLogger(GpCardConfig.class);
    @NacosValue(value = "${card.number:25}", autoRefreshed = true)
    private int number;
    @NacosValue(value = "${card.suit}", autoRefreshed = true)
    private String suit;

    @NacosConfigListener(dataId = "nacos-config-card-gp.properties", groupId = "DEV_GROUP")
    public void message(String config) {
        logger.info(config);
    }
}
```
nacos 的配置如下
![image](https://user-images.githubusercontent.com/26996625/87221448-a349e700-c39e-11ea-9043-3c2be9b27410.png)

![image](https://user-images.githubusercontent.com/26996625/87221438-95946180-c39e-11ea-8b52-fead5736eb5c.png)

### Describe what happened (or what feature you want)
现在两个bean都是读取的第一个配置

### Describe what you expected to happen

希望两个config能读取到对应的远端配置
### How to reproduce it (as minimally and precisely as possible)

1. 按照上面配置就能复现
2. 
3. 

### Tell us your environment

<spring-boot.version>2.3.0.RELEASE</spring-boot.version>
<nacos-config-spring-boot.version>0.2.7</nacos-config-spring-boot.version>
### Anything else we need to know?

目前定位到应该是 `org.springframework.core.env.PropertySourcesPropertyResolver#getProperty(java.lang.String, java.lang.Class<T>, boolean)` 这个方法里面用key去读取value的时候只匹配到propertySources中第一次遇到的元素。

请问这样的使用方式改如何处理？

**Comment by chuntaojun** [comment]
nacos-spring-project还是nacos-springboot-project，均遵从spring原本的设计，你应该避免相同key的情况出现

**Comment by cocodroid** [comment]
增加前缀去区分吧

**Comment by July-X** [comment]
> nacos-spring-project还是nacos-springboot-project，均遵从spring原本的设计，你应该避免相同key的情况出现

这里的dataId和groupId已经表明是两个不同配置了，如果因为key相同就导致数据读取问题，感觉还是有点不直观。我理解的dataId+groupId就类似spring定位到具体的properties了，应该起到隔离作用吧

**Comment by July-X** [comment]
> 增加前缀去区分吧

可以解决问题

**Comment by chuntaojun** [comment]
你可以看下spring environment的设计，不同的配置，只是优先级不同而已，就好比你用启动命令的参数去强覆盖配置文件的配置，虽然是命令行参数，但是其表现就可以当作是一个配置文件，只是表现形式不同而已

发自我的iPhone

在 2020年7月12日，16:04，July-X <notifications@github.com> 写道：

﻿

nacos-spring-project还是nacos-springboot-project，均遵从spring原本的设计，你应该避免相同key的情况出现

这里的dataId和groupId已经表明是两个不同配置了，如果因为key相同就导致数据读取问题，感觉还是有点不直观。我理解的dataId+groupId就类似spring定位到具体的properties了，应该起到隔离作用吧
