### ISSUE TITLE
the question of fastjson

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#3306]
无论是引用com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery；还是引用org.springframework.cloud/spring-cloud-starter-alibaba-nacos-discovery，都是引用fastjson。我们项目都是默认用jackson。因为fastjson的一些问题，会引发restTemplate的一些bug，请问nacos可以移除fastjson，改用jackson吗？

**Comment by KomachiSion** [comment]
nacos从1.3.0版本开始已经移除fastjson了，使用了jackson，com.alibaba.cloud的版本可能有一些延迟。

理论上可以exclude掉fastjson和nacos-client。然后手动的引入1.3.1版本的nacos-client。

但是这种做法没有经过足够的测试验证，请酌情使用。
