### ISSUE TITLE
ConfigService无法设置文件类型（Type）

### ISSUE THREAD

**Issue by mumuyuanbao** [alibaba/nacos#3308]
ConfigService无法设置文件类型Type
查看publishConfigInner方法发现并没有设置文件type
        List<String> params = new ArrayList<String>();
        params.add("dataId");
        params.add(dataId);
        params.add("group");
        params.add(group);
        params.add("content");
        params.add(content);
        if (StringUtils.isNotEmpty(tenant)) {
            params.add("tenant");
            params.add(tenant);
        }
        if (StringUtils.isNotEmpty(appName)) {
            params.add("appName");
            params.add(appName);
        }
        if (StringUtils.isNotEmpty(tag)) {
            params.add("tag");
            params.add(tag);
        }
        List<String> headers = new ArrayList<String>();
        if (StringUtils.isNotEmpty(betaIps)) {
            headers.add("betaIps");
            headers.add(betaIps);
        }
但是官方文档提供的OpenAPI
/nacos/v1/cs/configs 表示可以设置type类型。 是版本太低了么。
org.springframework.cloud:spring-cloud-context:2.2.2.RELEASE

**Comment by KomachiSion** [comment]
设置type目前应该是管控端（控制台）的功能，sdk应该没有实现。 我理解应该不影响使用。

**Comment by KomachiSion** [comment]
duplicate with #2660 #3072
