### ISSUE TITLE
Permission support group

### ISSUE THREAD

**Issue by David-wu91** [alibaba/nacos#3316]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen
目前最新版本权限控制只支持到资源（命名空间）控制，能否支持到更细粒度（如：分组（group））控制。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
暂无此功能计划

**Comment by David-wu91** [comment]
如下使用场景是典型的生产环境运维场景，能否考虑支持一下呢：
1.创建PRD命名空间，所有生产环境微服务及其配置均放在该命名空间下
2.将一定规则的微服务放在指定分组，如group1，group2，group3
3.用户页面操作只允许操作group1的配置，不能操作group2和group3分组下配置，因为该用户只维护group1下微服务

目前nacos的权限管理只支持到了命名空间，意味着只要有写权限的用户登录进来可以任意修改group1，group2，group3的配置，这样权限粒度是否过于粗。
或者根据当前nacos的功能，为支持上述使用场景，能否有较好的操作方案。

非常感谢指教一下

**Comment by KomachiSion** [comment]
需求其实是明确的，只是优先级问题。
1. 目前权限管理 社区内没有人在贡献，只有之前于1.2.0版本实现的一个粗力度的简单权限功能
2. 权限功能最多的需求在于管控端，而管控端最大的工作在控制台，目前社区内前端大佬比较少
3. 权限的多客户端兼容性需要重新设计权限整体功能，目前也没有人负责

综上所述，目前社区的优先级更加倾向于可用性，稳定性和性能问题上，而对于管控端部分的控制台和权限管理部分暂时不是需求重点。

当然如果您愿意贡献，社区是非常愿意接受的。

**Comment by KomachiSion** [comment]
No more discuss for this topic and we has no plan to implement it. I will close it first. Thanks for your contribution and advise.
