### ISSUE TITLE
[feature request] Support service instance affinity 

### ISSUE THREAD

**Issue by coolbeevip** [alibaba/nacos#3325]
This is a service instance selection policy.

For example, my scenario is that service A invokes service B

serviceA -call-> serviceB

There are two instances of serviceB-1 and serviceB-2

serviceA.affinity=beijing
serviceB-1.affinity=beijing
serviceB-2.affinity=shanghai

I want to preferentially call services with the same affinity attribute

Service A preferentially calls serviceB-1, and then calls serviceB-2 when serviceB-1 does not exist

**Comment by coolbeevip** [comment]
I read the document carefully, and I found that the cluster-name configuration can achieve a similar effect. I don’t know if I understand it correctly

**Comment by KomachiSion** [comment]
> I read the document carefully, and I found that the cluster-name configuration can achieve a similar effect. I don’t know if I understand it correctly

Yes it is, But the cluster name has no priority in nacos, you need to control and judge which cluster instance you call as preferences.
