### ISSUE TITLE
Nacos  permissions is danger

### ISSUE THREAD

**Issue by apple987** [alibaba/nacos#3329]
Nacos configuration of tourist users, read-only permissions, log in to delete services, configuration information, this is a very dangerous behavior, I hope to fix the vulnerability of permissions

**Comment by apple987** [comment]
nacos的权限控制很简单，存在风险！配置一个只读用户，登录之后可以删除配置，删除服务等操作，这些是非常危险的！

**Comment by KomachiSion** [comment]
Have you set nacos.core.auth.enabled=true?

**Comment by KomachiSion** [comment]
No response more than *7 days* ,close issue
