### ISSUE TITLE
k8s里面使用nacos，hostname获取异常

### ISSUE THREAD

**Issue by ethonchen** [alibaba/nacos#333]
k8s里面使用nacos，k8s里面 ect hosts的设置有两个，和hostname一致的放在后面了。 inetAddress.getCanonicalHostName() 取到的是第一个，用来和 inetAddress.getHostName() 会不一致，
![image](https://user-images.githubusercontent.com/3139756/48926905-dc54ef80-ef0c-11e8-99c9-f15eb3512bc8.png)

**Comment by ethonchen** [comment]
https://github.com/alibaba/nacos/pull/334

**Comment by nkorange** [comment]
你提的issue和你提的PR不是一致的。
就你提的issue来说，NetUtils类里是有相应判断的：
```
                if (inetAddress.getHostName().equals(inetAddress.getCanonicalHostName())) {
                    serverAddress = inetAddress.getHostName();
                } else {
                    serverAddress = inetAddress.getCanonicalHostName();
                }
```

**Comment by ethonchen** [comment]
NetUtils的代码没解决这个问题，
关键是 InetAddress inetAddress = InetAddress.getLocalHost();
你看我上图，这样初始化的inetAddress ，k8s里面 hostname放在 ect/hosts后面就失效了

**Comment by nkorange** [comment]
这种情况下就应该取第一个

**Comment by ethonchen** [comment]
现在的问题是k8s里面 ，hostname是放在后面的，没放到第一个
