### ISSUE TITLE
nacos 1.3.0 beta 集群 内置数据库启动问题

### ISSUE THREAD

**Issue by caopengyuan** [alibaba/nacos#3338]
Question, under Caused by: Java. Lang. RuntimeException: Nacos Server did not start because dumpservice bean construction failure:
; Nested exception is com. Alibaba. Nacos. Consistency. Exception. ConsistencyException: Data acquisition failed: Java. Util. Concurrent. ExecutionException: Com. Alibaba. Nacos. Consistency. Exception. ConsistencyException: No leader at term 1, read the from leader has error: Java. Util. Concurrent. ExecutionException: Com. Alibaba. Nacos. Consistency. Exception. ConsistencyException: No leader at term

Environment is to use nacos1.3.0, nacos - server - 1.3.0 - BETA unzip the package using the built-in database cluster, when to start the third instance, according to https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html, cluster mode. Sh startup. Sh -p embedded paper error below

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by rexlin600** [comment]
Please see if this can help you， #3341

**Comment by KomachiSion** [comment]
1.3.1 has released, please use it and retry.
