### ISSUE TITLE
！！关于nacos文档中没有完整描述dataId格式格式组合

### ISSUE THREAD

**Issue by xuxi5034241849** [alibaba/nacos#3339]
The combination of dataId format in the document is: ${prefix}-${spring.profile.active}.${file-extension}, when spring.profile.active is empty, the corresponding connector-will also not exist , The stitching format of dataId becomes ${prefix}.${file-extension}

But from the above description, I recently encountered a strange combination when building a scaffold
![image](https://user-images.githubusercontent.com/15028620/87528059-96d7ce00-c6bf-11ea-91a9-3b1e33a34119.png)
The dataid format is in use, there must be a configuration file with only ${prefix}, otherwise the project console will always print
![image](https://user-images.githubusercontent.com/15028620/87528397-0cdc3500-c6c0-11ea-80ce-7ed6fd99941b.png)
I don’t know if this is a bug, or the documentation doesn’t clearly state it.
Please help to solve

--------------------------------

文档中关于dataId格式格式组合形式是：${prefix}-${spring.profile.active}.${file-extension}，当 spring.profile.active 为空时，对应的连接符 - 也将不存在，dataId 的拼接格式变成 ${prefix}.${file-extension}

但从上述的描述说明来看.近期我在搭建脚手架的时候碰到了奇怪的组合
![image](https://user-images.githubusercontent.com/15028620/87528059-96d7ce00-c6bf-11ea-91a9-3b1e33a34119.png)
dataid格式在使用中，必须要存在一个仅有${prefix}的配置文件，否则项目控制台会一直打印
![image](https://user-images.githubusercontent.com/15028620/87528397-0cdc3500-c6c0-11ea-80ce-7ed6fd99941b.png)
我不清楚这是一个BUG，还是文档没有说明清楚.
还烦请帮助解决

**Comment by xuxi5034241849** [comment]
![image](https://user-images.githubusercontent.com/15028620/87528712-79573400-c6c0-11ea-9c1f-03625e83990d.png)
![image](https://user-images.githubusercontent.com/15028620/87528812-a3a8f180-c6c0-11ea-8f23-c06a7baa82ee.png)

**Comment by xuxi5034241849** [comment]
补充版本信息：

  mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR6"
  mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:2.2.1.RELEASE"

 springBootVersion = '2.2.1.RELEASE'

**Comment by xuxi5034241849** [comment]
![image](https://user-images.githubusercontent.com/15028620/87630941-ede5ad80-c768-11ea-9d8e-13e5e411ea58.png)
补充，已经get到源码了，这并不是BUG..  但官方文档中并未说明..  建议补充文档说明

**Comment by KomachiSion** [comment]
@xuxi5034241849 , 欢迎提PR到[文档repo](https://github.com/nacos-group/nacos-group.github.io).

**Comment by KeRan213539** [comment]
这个组合是 spring-cloud-alibaba 限制的,请参考spring-cloud-alibaba的文档
nacos本身对dataId的格式是没有任何限制的
