### ISSUE TITLE
新建用户密码中含有%时，日志提示“unknow”

### ISSUE THREAD

**Issue by wpt191** [alibaba/nacos#3342]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by wpt191** [comment]
阿里工程师您好：
       1、目前需要按照权限控制nacos登录，新建了用户，但当用户密码含有 % 时，无法正常登录。
       2、给某一个用户只让一个组有读写权限，但登陆后，人可以删除其他组的yaml文件
nacos-server-1.3.1     springboot：2.2.1

**Comment by KomachiSion** [comment]
1. 可能有些特殊字符支持的不是很好，这点需要社区一起加入完善
2. 请确认打开了服务端的权限功能`nacos.core.auth.enabled=true`

**Comment by wpt191** [comment]
好的，权限开关已经改成true，有以下现象:
1、可以看到所有组
2、点击其他组，提示没有权限，开始有一个waitting图标转圈
3、这时候我点击有权限的，也是这个转圈，需要重新刷新才可以

**Comment by wpt191** [comment]
再次感谢百忙之中解决我的问题，谢谢你
