### ISSUE TITLE
Zipkin link tracing causes Nacos registration failure

### ISSUE THREAD

**Issue by heppytt** [alibaba/nacos#3346]
Using spring cloud version Hoxton.SR4 , spring boot 2.2.6, zikpin 2.2.2 started the project, resulting in Nacos registration failure, and the project has been stuck. Have you ever encountered such problems?
![image](https://user-images.githubusercontent.com/17058423/87582313-cfea5f80-c70c-11ea-8b53-0994aaf340dc.png)
![image](https://user-images.githubusercontent.com/17058423/87582334-d7116d80-c70c-11ea-8b1b-de05b26fc278.png)
![image](https://user-images.githubusercontent.com/17058423/87582358-e1336c00-c70c-11ea-9387-63e7851cb317.png)

**Comment by KomachiSion** [comment]
duplicate with #3332

**Comment by heppytt** [comment]
Have you met me. The problem is not to report errors. Just turn the debugger button around for a while. Then check the Nacos and find that the service is not registered. Or is there any way to tell me I can debug it myself?
