### ISSUE TITLE
com.alibaba.nacos.client.config.NacosConfigService#getConfigInner exception handler

### ISSUE THREAD

**Issue by 98DE9E1F** [alibaba/nacos#3347]
## Issue Description

only com.alibaba.nacos.api.exception.NacosException#NO_RIGHT can be throw ,this were cause developer can't distinguish server error or config is null

### Describe what happened (or what feature you want)

this method return null when server error or config is null

### Describe what you expected to happen

throw error when server error

**Comment by KomachiSion** [comment]
If server error, it can use local snapshot so that it can't block your application.
If return null means both the server and your snapshot don't have the config.
