### ISSUE TITLE
在云原生下的灰度发布方案如何做

### ISSUE THREAD

**Issue by chestarss** [alibaba/nacos#3354]
从文档来看，目前nacos灰度发布是通过指定ip地址的方式做的，但是在k8s容器环境，应用重启会伴随着pod的ip变化，在灰度发布时无法预知到pod的ip

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
基于现在的nacos，暂时没法做到完全自动化的完全灰度上下线。
但是有一种思路也许可行：
k8s容器启动时，注册的服务可以设置为disabled的下线状态， 这样虽然注册上了，但是不会对外提供服务，之后通过openAPI也好，控制台也好，再把服务改成上线状态。
只是目前这块工作需要用户自己执行和操作。

**Comment by KomachiSion** [comment]
社区大佬们，如果有好的方案和思路可以在这个issue中讨论下。

**Comment by zongtanghu** [comment]
https://mp.weixin.qq.com/s/fMZuQnXiejH7_N6R2Z76pA 之前一篇介绍基于Nacos做服务的灰度发布，你可以看下和参考下； @chestarss

**Comment by Yangstatus** [comment]
能否通过k8s的探针检测来给pod启动或者停止的时候预留一些时间，这些时间能够保证我们的代码去处理服务上线和下线的过程。确保整个升级过程中是无感的？

**Comment by KomachiSion** [comment]
和k8s整合的话 需要在operator里搞事情，单独从nacos服务测是做不了的

**Comment by admin08** [comment]
API（MVC）层可以通过k8s的ingress-controller组件通过判断header里面值去路由，如果是dubbo可以通过RPC标签来做，

**Comment by admin08** [comment]
> 社区大佬们，如果有好的方案和思路可以在这个issue中讨论下。

1.首先在K8S准备两个命名空间（一个放生产应用、一个是灰度空间的应用）
2.通过ingress-controller 组件通过请求头是否带有特定的tag自动路由到不同的服务
3.我们现在用的dubbo，dubbo自带tag路由功能，从header中将tag一直传递下来，使得RPC也自动路由。当我们认为灰度服务通过检查后，可以通过nacos控制台找到相应的服务，将服务中的元数据例如：dubbo.tag 属性移除掉即可，或者看nacos是否提供API一键移除

**Comment by admin08** [comment]
> 社区大佬们，如果有好的方案和思路可以在这个issue中讨论下。

1.首先在K8S准备两个命名空间（一个放生产应用、一个是灰度空间的应用）
2.通过ingress-controller 组件通过请求头是否带有特定的tag自动路由到不同的服务
3.我们现在用的dubbo，dubbo自带tag路由功能，从header中将tag一直传递下来，使得RPC也自动路由。当我们认为灰度服务通过检查后，可以通过nacos控制台找到相应的服务，将服务中的元数据例如：dubbo.tag 属性移除掉即可，或者看nacos是否提供API一键移除

> 基于现在的nacos，暂时没法做到完全自动化的完全灰度上下线。
> 但是有一种思路也许可行：
> k8s容器启动时，注册的服务可以设置为disabled的下线状态， 这样虽然注册上了，但是不会对外提供服务，之后通过openAPI也好，控制台也好，再把服务改成上线状态。
> 只是目前这块工作需要用户自己执行和操作。

**Comment by admin08** [comment]
但是还有一个问题没有解决，使用灰度后，消息队列该如何区分消费者？

**Comment by Yangstatus** [comment]
> 但是还有一个问题没有解决，使用灰度后，消息队列该如何区分消费者？

可以在灰度发布后，对发送的消息队列环境进行判断，如果是灰度环境就转发到灰度队列中。处理消息也同理。

**Comment by admin08** [comment]
> > 但是还有一个问题没有解决，使用灰度后，消息队列该如何区分消费者？
> 
> 可以在灰度发布后，对发送的消息队列环境进行判断，如果是灰度环境就转发到灰度队列中。处理消息也同理。

我们第一时间考虑过该方案，但是其中的服务间链路错综复杂，难以实现。
1.首先我们使用的中间价是rabbitmq,最开始的方案是通过划分两个不同的vhost,做区分，同时相关服务全部部署一套灰度。（该方案由于资源不够被直接否决）

2.正如你所描述的方案中，我举一个例子：
首先A服务（生产RPC）调用B服务（生产RPC），B服务（生产RPC）中发送了一条消息，这个时候又C服务（生产RPC）进行消费
这是生产中正常的链路既：  A（生产）---->B（生产）------>mq（mq是生产和灰度共用的路由key）------>C（生产）.
-------
分割线
-------
灰度环境下：
首先A服务（灰度RPC）调用B服务（生产），B服务（灰度RPC）中发送了一条消息，这个时候又C服务（生产RPC）进行消费
这是生产中正常的链路既：  A->B->mq->C.
这两条链路中都用到B服务，但是B服务没有没有发布灰度（dubbo会自动降低到正常的生产环境），这个时候又B（生产者）又发生消息，这个时候消息就C（生产）或者C（灰度）消费。

**Comment by Yangstatus** [comment]
能否给灰度服务加标签，在MQ进行过滤，让消费者根据tag去调用RPC服务。 生产者对每条灰度消息加上标签（tag），消费者在拉取消息时通过判断决定是否仅获取带有某标签（tag）的消息。 A 灰度 （打tag）—— B （生产）—— MQ（消费者进行判断调用tag生产服务） ---> 走C 灰度

**Comment by admin08** [comment]
> 能否给灰度服务加标签，在MQ进行过滤，让消费者根据tag去调用RPC服务。 生产者对每条灰度消息加上标签（tag），消费者在拉取消息时通过判断决定是否仅获取带有某标签（tag）的消息。 A 灰度 （打tag）—— B （生产）—— MQ（消费者进行判断调用tag灰度服务） ---> 走C 灰度

没错，但是这里涉及到消息重新投递问题以及漏洞，我再打个比方：
在该链路下，B服务发送的队列确实加了tag，然后消费者去区分 ，如果监听到的消息带了tag，这个时候就重新投递消息（消费者会轮询投递），直到消息tag完全和对应的消费者tag相同才消费
A（tag） ------- B（生产）-----MQ-----C（mq消费者灰度）或者 C（mq消费者生产）

但是这这样做还是有问题，问题如下：
  当C（MQ消费者没有发布灰度的时候）链路入下：
A（tag） ------- B（生产）-----MQ-----C（mq消费者生产），意味着MQ消费者C永远都不会消费带灰度tag标签消息。因为C并没有发布灰度

目前我们想到的两个策略是：
1.C消费者连续N次接收到同一个消息，但是该消息的tag与当前消费者总是不一致满足阀值N的情况下，尝试强制消费

2.将C（mq消费者）注册到注册中心上面，并且进行维护。在每次消费的时候先看注册中心时候有活着的并且消息tag与消费者tag相同的应用，如果有则重新投递，如果没有则尝试强制消费。

**Comment by admin08** [comment]
> 能否给灰度服务加标签，在MQ进行过滤，让消费者根据tag去调用RPC服务。 生产者对每条灰度消息加上标签（tag），消费者在拉取消息时通过判断决定是否仅获取带有某标签（tag）的消息。 A 灰度 （打tag）—— B （生产）—— MQ（消费者进行判断调用tag灰度服务） ---> 走C 灰度

可能我没表述清楚我的意思，其实我想表达的是MQ（无灰度），生产和灰度同时监听相同的路由key，虽然消费者可以区分消息是否为灰度，我的意思是策略该如何，如果是监听到不属于自己的消息，是重新投递还是？如果重新投递一直没有符合的消费者，消息堆积怎么办

**Comment by KomachiSion** [comment]
There are no discussion for a long time.

**Comment by zz630** [comment]
> > 能否给灰度服务加标签，在MQ进行过滤，让消费者根据tag去调用RPC服务。 生产者对每条灰度消息加上标签（tag），消费者在拉取消息时通过判断决定是否仅获取带有某标签（tag）的消息。 A 灰度 （打tag）—— B （生产）—— MQ（消费者进行判断调用tag灰度服务） ---> 走C 灰度
> 
> 可能我没表述清楚我的意思，其实我想表达的是MQ（无灰度），生产和灰度同时监听相同的路由key，虽然消费者可以区分消息是否为灰度，我的意思是策略该如何，如果是监听到不属于自己的消息，是重新投递还是？如果重新投递一直没有符合的消费者，消息堆积怎么办
> 
> ![36f34830809345a5b9c6f623c3a9d6d](https://user-images.githubusercontent.com/35361094/89882228-1c846600-dbf9-11ea-8d5c-d87338c345f2.png)

消费者可以只部署一套不区分环境，不做实际逻辑，再带上tag发起rpc调用到c
