### ISSUE TITLE
集成springcloud-gateway网关时，无法配置路由

### ISSUE THREAD

**Issue by gaoxiang9457** [alibaba/nacos#3358]
你好，最近使用网关集成nacos时，当开启nacos发现功能后，配置路由按“/”截断url功能不生效，能帮忙提供配置方法吗？
spring:
    gateway:
      routes:
        - filters:
            - StripPrefix=3
          id: nameRoot
          predicates:
            - Path=/name/**
          uri: http://localhost:80

**Comment by pink-baby** [comment]
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            #      路由策略
            routes:
                - id: user
                  uri: lb://health-user-service
                  predicates:
                      - Path= /api/user/**
                  filters:
                      - StripPrefix=1

---------------------------------

这是我们配置的gateway，我们可以使用的，你可以参考下

**Comment by gaoxiang9457** [comment]
非常感谢，已经解决，配置文件字符集有问题
