### ISSUE TITLE
微服务端修改了server-adr不起作用的问题

### ISSUE THREAD

**Issue by zymapp** [alibaba/nacos#3360]
yml配置:
server:
  port: 6001
spring:
  application:
    name: service-common
  cloud:
    nacos:
      discovery:
        server-adr: localhost:1001  #nacos服务注册中心地址
      config:
        server-adr: localhost:1001  #nacos配置中心地址
        file-extension: yaml        #指定格式的配置
        namespace: 3db4fb90-ffc1-4954-8a55-e4a4e9e668ce
        group: group_mysql_common
    sentinel:
      transport:
        #配置sentinel的dashboard地址
        dashboard: localhost:2001
        #port:sentinel微服务端会在本地占用一个指定的HttpServer端口与Sentinel控制台端进行交互
        #默认8719端口，假如被占用了会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719
启动时提示Error：
[NACOS SocketTimeoutException httpGet] currentServerAddr:http://localhost:8848， err : connect timed out

请问已经配置为1001端口了，为什么还是访问到8848的端口呢？

**Comment by KomachiSion** [comment]
duplicate with #3361
