### ISSUE TITLE
修改默认端口8848的问题

### ISSUE THREAD

**Issue by zymapp** [alibaba/nacos#3361]
1.nacos-server-1.3.1修改了端口为1001，
  在浏览器中访问http://localhost:1001/nacos/index.html能正常登录进入到控制台管理界面
2.在微服务端修改配置指向1001端口，配置如下：
  server:
  port: 6001
spring:
  application:
    name: service-common
  cloud:
    nacos:
      discovery:
        server-adr: localhost:1001  #nacos服务注册中心地址
      config:
        server-adr: localhost:1001  #nacos配置中心地址
        file-extension: yaml        #指定格式的配置
        namespace: 3db4fb90-ffc1-4954-8a55-e4a4e9e668ce
        group: group_mysql_common
    sentinel:
      transport:
        #配置sentinel的dashboard地址
        dashboard: localhost:2001
        #port:sentinel微服务端会在本地占用一个指定的HttpServer端口与Sentinel控制台端进行交互
        #默认8719端口，假如被占用了会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719
3.启动微服务时出错了：
  提示8848的端口连接超时：
[NACOS SocketTimeoutException httpGet] currentServerAddr:http://localhost:8848， err : connect timed out
no available server
[fixed-localhost_8848-3db4fb90-ffc1-4954-8a55-e4a4e9e668ce] [sub-server] get server config exception, dataId=service-common.yaml, group=group_mysql_common, tenant=3db4fb90-ffc1-4954-8a55-e4a4e9e668ce

为什么还会访问8848呢，不是已经配置为1001了吗？

**Comment by chuntaojun** [comment]
你只配置了discovery的地址，没有配置config的地址，注意看spring-cloud-alibaba的github的wiki，自行搜索下

**Comment by Rambo1203** [comment]
我也遇到同样的问题，“没有配置 config 的地址” 这个关键点没有找到响应的配置（我理解的config地址就是 config.server-addr=127.0.0.1:8002），还请更详细的指导，感谢~！

以下是我的具体配置，我同样修改了 Nacos 客户端 application.propertie 中的端口号.
spring:
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 127.0.0.1:8002
      config:
        # 服务配置中心
        server-addr: 127.0.0.1:8002
        # 指定配置文件格式
        file-extension: yaml

**Comment by Rambo1203** [comment]
> 1.nacos-server-1.3.1修改了端口为1001，
> 在浏览器中访问[http://localhost:1001/nacos/index.html能正常登录进入到控制台管理界面](http://localhost:1001/nacos/index.html%E8%83%BD%E6%AD%A3%E5%B8%B8%E7%99%BB%E5%BD%95%E8%BF%9B%E5%85%A5%E5%88%B0%E6%8E%A7%E5%88%B6%E5%8F%B0%E7%AE%A1%E7%90%86%E7%95%8C%E9%9D%A2)
> 2.在微服务端修改配置指向1001端口，配置如下：
> server:
> port: 6001
> spring:
> application:
> name: service-common
> cloud:
> nacos:
> discovery:
> server-adr: localhost:1001 #nacos服务注册中心地址
> config:
> server-adr: localhost:1001 #nacos配置中心地址
> file-extension: yaml #指定格式的配置
> namespace: 3db4fb90-ffc1-4954-8a55-e4a4e9e668ce
> group: group_mysql_common
> sentinel:
> transport:
> #配置sentinel的dashboard地址
> dashboard: localhost:2001
> #port:sentinel微服务端会在本地占用一个指定的HttpServer端口与Sentinel控制台端进行交互
> #默认8719端口，假如被占用了会自动从8719开始依次+1扫描，直到找到未被占用的端口
> port: 8719
> 3.启动微服务时出错了：
> 提示8848的端口连接超时：
> [NACOS SocketTimeoutException httpGet] currentServerAddr:[http://localhost:8848，](http://localhost:8848%EF%BC%8C) err : connect timed out
> no available server
> [fixed-localhost_8848-3db4fb90-ffc1-4954-8a55-e4a4e9e668ce] [sub-server] get server config exception, dataId=service-common.yaml, group=group_mysql_common, tenant=3db4fb90-ffc1-4954-8a55-e4a4e9e668ce
> 
> 为什么还会访问8848呢，不是已经配置为1001了吗？

您好，请问你是如何解决的？
