### ISSUE TITLE
Self preservation of Nacos

### ISSUE THREAD

**Issue by junjie-tang99** [alibaba/nacos#3369]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)
Does Nacos have the mechanism of self preservation under the partition network like Eureka?

**Comment by KomachiSion** [comment]
What's the `self preservation` means? Is it like to prevent split brain？

**Comment by chuntaojun** [comment]
Yes, you can look at the console, you can see this code

```java
double threshold = service.getProtectThreshold();
        
if ((float) ipMap.get(Boolean.TRUE).size() / srvedIPs.size() <= threshold) {
            
      Loggers.SRV_LOG.warn("protect threshold reached, return all ips, service: {}", serviceName);
      if (isCheck) {
           result.put("reachProtectThreshold", true);
      }
            
      ipMap.get(Boolean.TRUE).addAll(ipMap.get(Boolean.FALSE));
      ipMap.get(Boolean.FALSE).clear();
}
```

**Comment by junjie-tang99** [comment]
Hi @KomachiSion,  the self preservation what I means is: Nacos server can turn into protect mode when lose most of service instances in last N minutes during the network apart. Under the protect mode the Nacos server will not eliminate the unhealthy instances, not allow register new instances, and will also return all the instances(healthy+unhealthy) to Nacos-Client.

**Comment by junjie-tang99** [comment]
> Yes, you can look at the console, you can see this code
> 
> ```java
> double threshold = service.getProtectThreshold();
>         
> if ((float) ipMap.get(Boolean.TRUE).size() / srvedIPs.size() <= threshold) {
>             
>       Loggers.SRV_LOG.warn("protect threshold reached, return all ips, service: {}", serviceName);
>       if (isCheck) {
>            result.put("reachProtectThreshold", true);
>       }
>             
>       ipMap.get(Boolean.TRUE).addAll(ipMap.get(Boolean.FALSE));
>       ipMap.get(Boolean.FALSE).clear();
> }
> ```
Hi @chuntaojun, I think these codes means: When one service reach the service's protect threshold which configed in the service metadata(default is 0), the Nacos will return all instances(healthy+unhealthy). So I don't know this strategy is same as the eureka.

**Comment by KomachiSion** [comment]
@junjie-tang99 , According to your description, the protect threshold is similar to.

The protect threshold in nacos is means that the rate healthy instances from all instances is under the threshold you set.
So nacos will return all instances(healthy+unhealthy) to sdk and any source call API.

But in nacos, will allow register new instances if service is in protect threshold.
