### ISSUE TITLE
Issue with executing shell script /bin/sh^M on Unix/Linux

### ISSUE THREAD

**Issue by Veryfirefly** [alibaba/nacos#3370]
## Issue Description
Type: Bug Report

### Describe what happened (or what feature you want)

1. After nacos is packaged, the /bin/sh^M problem will appear when executing the shell script on Linux. This is caused by script line breaks instead of LF. I checked the script in the source code and found that startup.sh and shutdown.sh are CRLF formatted line breaks
2. `ERROR OS=Windows and the assembly descriptor contains a *nix-specific root-relative-reference`. This error occurs during binary packaging in Maven, but it will not affect the packaging. I queried the documentation and found that the reason is: because the assembly task is executed on Windows, but it contains a path relative to Linux.

### Describe what you expected to happen

I submitted a PR and revised the above two questions

1. Format startup.sh and shutdown.sh. Use Unix/Linux standard line break LF to avoid converting line breaks during execution, and tested on Linux and Unix.
2. Solve the OS=Windows error when packaging Maven. Successfully packaged on Linux and Windows

### Tell us your environment

1. JDK 1.8
2. CentOS 6.9

**Comment by Veryfirefly** [comment]
#3371

**Comment by KomachiSion** [comment]
I have comment in your PR. Please check.
