### ISSUE TITLE
Nacos client端能配置多个namespace吗？

### ISSUE THREAD

**Issue by xiaoxiangzhenyu** [alibaba/nacos#3372]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
用springboot-admin与ncaos集成做微服务应用墙的监控时，因为nacos上各业务采用namespace来隔离，而springboot-admin接入nacos时，必须指定一个namespace，因此springboot-admin的应用墙中只能展示指定的namespace中的应用！
如果Nacos-client能支持多namespace配置的话，那springboot-admin就能监控指定的多个namespace下的微服务应用了。

When using springboot-admin and ncaos integration to monitor the micro-service application wall, because the services on the nacos are isolated by namespace, and when accessing the nacos, one must be specified namespace, so the springboot-admin application wall can only show the application in the specified! When Nacos-client can support multiple namespace configurations, springboot-admin can monitor microservice applications under specified multiple namespace.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sanxun0325** [comment]
The client can only configure one namespace, otherwise it violates the concept of spatial isolation.
