### ISSUE TITLE
资源路径错误不存在的资源 :8848/nacos/console-fe/public/icons/icon-font.woff2 404

### ISSUE THREAD

**Issue by jf11480** [alibaba/nacos#3378]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
错误的资源架子啊

### Describe what you expected to happen

http://服务器地址:8848/nacos/console-fe/public/icons/icon-font.woff2 404
### How to reproduce it (as minimally and precisely as possible)

1. 访问主页 服务器地址:8848/nacos/
2. 打开控制台看到 http://服务器地址:8848/nacos/console-fe/public/icons/icon-font.woff2 404
3. 

### Tell us your environment
1.3.1

### Anything else we need to know?
无

**Comment by KomachiSion** [comment]
It seems like a font files, It does not affect the usage.

**Comment by Gamuute0** [comment]
hellow

**Comment by SnapDragonQball** [comment]
tnx

**Comment by mike773666** [comment]
Hey
