### ISSUE TITLE
修改访问路径将导致静态资源无法访问

### ISSUE THREAD

**Issue by jf11480** [alibaba/nacos#3379]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
server.servlet.contextPath=/nacos 修改 server.servlet.contextPath=/
导致相关静态资源无法访问
 
### Describe what you expected to hap pen
修改 server.servlet.contextPath 静态资源路径未同步
 
### How to reproduce it (as minimally and precisely as possible)

1. 修改conf下 application.properties 种 server.servlet.contextPath=/nacos
2. 访问主页 相关静态路径未同步修改
3. 

### Tell us your environment
1.3.1

**Comment by KomachiSion** [comment]
Please do not change the `contextPath`, I think.

**Comment by jf11480** [comment]
我认为这个路径是动态的不应该写死

**Comment by KomachiSion** [comment]
的确应该是动态的，但是现在有些地方似乎对这个有一定的依赖性，如果修改可能会导致部分API有问题，因此暂时不建议修改。

或者您花点时间，整理下哪些地方是修改了这个路径之后无法访问的，在issue中列举出来，这样我们可以把工作开放到社区。每人处理一部分，应该最终会解决。
