### ISSUE TITLE
未输入账号，主页面直接弹出

### ISSUE THREAD

**Issue by weiyf16** [alibaba/nacos#3380]
安装nacos 1.1.4 版本 下载 解压后  运行windows脚本命令 startup 后 **访问http://localhost:8848/nacos  闪弹出主页面**  后出现登录页面 输入账号密码nacos 正常进入主页面

**Comment by weiyf16** [comment]
未输入账号密码，闪弹出主页面  后跳转登录玉面  不知是否影响后期使用

**Comment by KomachiSion** [comment]
It may be browser load cache first and then redirect to login page. And can you use new version and retry?

**Comment by weiyf16** [comment]
thanks
