### ISSUE TITLE
手动拼接sql参数存在SQL注入风险

### ISSUE THREAD

**Issue by ztycool** [alibaba/nacos#3382]
版本1.3.1
方法：
1. com.alibaba.nacos.config.server.service.repository.embedded.EmbeddedStoragePersistServiceImpl#configInfoCount(java.lang.String)
2. com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl#configInfoCount(java.lang.String)
![sql](https://user-images.githubusercontent.com/37068668/87879546-0e8a5d80-ca1e-11ea-81ec-f9b8c14b1206.jpg)

**Comment by KomachiSion** [comment]
Yes, it is. But I think we have pre-check for the tenant and namesapceId, it can't include special characters except `-`,`_`.

**Comment by chuntaojun** [comment]
> Yes, it is. But I think we have pre-check for the tenant and namesapceId, it can't include special characters except `-`,`_`.

and use PrepareStatement is better

**Comment by ztycool** [comment]
@KomachiSion 
api接口：com.alibaba.nacos.console.controller.NamespaceController#getNamespace
在这个接口上可以接收任意参数，恶意注入风险还是存在的
