### ISSUE TITLE
nacos 后台 当用户设置权限后 出现的问题

### ISSUE THREAD

**Issue by wangengzheng** [alibaba/nacos#3383]
## Issue Description

Type: bug

### Describe what you expected to happen
nacos 后台 默认进入是tenata public 当用户在这个tenata没有设置权限的时候 会出现 auth fail （console报错了 Uncaught (in promise)   问题出现在 点击alpha(我创建的tenata)就出现问题 (这是当前登录用户是有权限的)  url改变了 但是死活不出现列表 
只有当我刷新整个页面的时候才能出现

### How to reproduce it (as minimally and precisely as possible)

1. 
nacos docker 设置 NACOS_AUTH_ENABLE=True 
创建新用户 test
tenata 有两个列表  public alpha
帮用户test创建能够只读alpha teanta的权限
2. 
用户test登录 第一次默认在public tenata下 出现 auth fail 弹窗  点击 alpha tenatat 一直不出现 
3. 
刷新整个页面的时候 alpha tenatat下面的列表才能出现 (取决列表是否有内容)

### Tell us your environment
"NACOS_AUTH_ENABLE=true",
"NACOS_AUTH_CACHE_ENABLE=true",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"BASE_DIR=/home/nacos",
"CLASSPATH=.:/home/nacos/conf:",
"CLUSTER_CONF=/home/nacos/conf/cluster.conf",
"FUNCTION_MODE=all",
"JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk",
"NACOS_USER=nacos",
"JAVA=/usr/lib/jvm/java-1.8.0-openjdk/bin/java",
"JVM_XMS=2g",
"JVM_XMX=2g",
"JVM_XMN=1g",
"JVM_MS=128m",
"JVM_MMS=320m",
"NACOS_DEBUG=n",
"TOMCAT_ACCESSLOG_ENABLED=false",
"TIME_ZONE=Asia/Shanghai"

nacos docker 

nacos/nacos-server	latest	def682e5042d 	2 weeks ago	756MB

"Image": "sha256:def682e5042d4af748e1bf9905d716daa169d79b71b90ea3b4d7f8aaab58b94a"

### Anything else we need to know?
![无标题](https://user-images.githubusercontent.com/12171338/87894745-2db4d980-ca76-11ea-9b74-1f6b21e1fbb0.png)

**Comment by KomachiSion** [comment]
duplicate with #2945
