### ISSUE TITLE
Project language problem identified in github

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#339]
![image](https://user-images.githubusercontent.com/2010632/48964306-a3397f80-efdf-11e8-9a6b-76ebbdebc219.png)

github的页面上项目类型是JavaScript，  估计是检测到项目代码js比java代码还多了...
建议修改一下， 可以通过加入 .gitattributes  文件， 内容如下

> 
*.js linguist-language=java
*.css linguist-language=java
*.html linguist-language=java
> 
将静态文件识别为java文件， 避免误解

**Comment by hxy1991** [comment]
赞👍
