### ISSUE TITLE
想请教一个安装的问题

### ISSUE THREAD

**Issue by jinbaosheng** [alibaba/nacos#3396]
## Issue Description
window下访问nacos控制台页面显示空白
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

在window下执行安装启动命令 ，启动过程中没有报错。
能够通过地址是localhost:8848或者127.0.0.1:8848访问。但是通过内网ip地址访问nacos控制台显示是空白页。后台也没有日志报错。
### Describe what you expected to happen
在window下执行安装启动命令 ，启动过程中没有报错。
能够通过地址是localhost:8848或者127.0.0.1:8848访问。但是通过内网ip地址访问nacos控制台显示是空白页。后台也没有日志报错。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
window环境

**Comment by KomachiSion** [comment]
本地能够访问，说明nacos是启动成功的，并且能够对外提供服务。
通过内网ip无法访问，多半是网络环境上的问题。这种环境问题只能自己排查了。
比如可以通过telnet之类的命令，查看远端是否能够访问8848端口，又或者打开浏览器的控制台之类的，看下网络流是否有返回等。
nacos也有access log， 看一下是否有http访问进来。

**Comment by jinbaosheng** [comment]
谢谢您的回复。可能我没表述清楚。本机ip就是10.10.13.10。我就在nacos本机服务器的ip地址中输入http://10.10.13.10:8848/nacos/去打开控制台的，不报错，但是显示空白。按理说本机访问本机服务器不应该涉及到网络问题。后台access.log也没什么异常情况。之前我怀疑是我的hosts有问题。但是同样是tomcat服务器，我就可以用ip正常访问tomcat的首页。盼回复。

**Comment by KomachiSion** [comment]
一样的，localhost:8848能访问，说明成功启动和提供服务了，至于本机ip空白的问题，还是需要排查自己环境。比如通过浏览器控制台， curl之类的试试看。 看看到底是nacos只监听了localhost 还是 其他问题
