### ISSUE TITLE
[bug report] startup.sh complains about [[: not found

### ISSUE THREAD

**Issue by JerryChin** [alibaba/nacos#3397]
## Issue Description

startup.sh complains about [[: not found.

### Describe what happened (or what feature you want)
I'm trying to start Nacos in standalone mode by executing:

    ./startup.sh -m standalone

It output the following:

```
./startup.sh: 88: ./startup.sh: [[: not found
./startup.sh: 92: ./startup.sh: [[: not found
./startup.sh: 101: ./startup.sh: [[: not found
./startup.sh: 103: ./startup.sh: [[: not found
./startup.sh: 110: ./startup.sh: [[: not found
/usr/lib/jvm/java-8-oracle/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/icvss-project/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/lib/jvm/java-8-oracle/lib/ext -Xloggc:/home/icvss-project/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/home/icvss-project/nacos/plugins/health,/home/icvss-project/nacos/plugins/cmdb -Dnacos.home=/home/icvss-project/nacos -jar /home/icvss-project/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/icvss-project/nacos/conf/ --logging.config=/home/icvss-project/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
./startup.sh: 131: ./startup.sh: [[: not found
```

### Describe what you expected to happen

I expect Nacos is running in standalone mode and no more warning about `[[: not found`.

### How to reproduce it (as minimally and precisely as possible)

1. Just download the lastest binary release of Nacos
2. running it under Ubuntu 14.04.2 TLS

### Tell us your environment
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

nacos-server-1.3.1

### Anything else we need to know?
N/A

**Comment by KomachiSion** [comment]
Please check your local `startup.sh` is same as `distribution/bin/startup.sh`.
If they are the same, please use `sh startup.sh -m standalone` again.

**Comment by JerryChin** [comment]
@KomachiSion I've cross checked, there's no difference.  The version is nacos-server-1.3.1, the lastest release.

using `sh startup.sh -m standalone` output the same result as I posted above.

I've found these two questions on Stackoverflow, the answers, if I understand correctly,  suggest that ``[[`` should always use with `Bash` shell or any shell with this extension, clearly this rules out the default shell specified in `startup.sh` viz. `sh`.

1. [https://stackoverflow.com/questions/13542832/difference-between-single-and-double-square-brackets-in-bash](https://stackoverflow.com/questions/13542832/difference-between-single-and-double-square-brackets-in-bash)
2. [https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found](https://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found)

**Comment by KomachiSion** [comment]
So should we change the top of `startup.sh` to `#/bin/bash` will solve your problem?

**Comment by JerryChin** [comment]
@KomachiSion Yep. but if you change shabang line to `#!/bin/bash`, everything will run smoothly.

Actually I think whoever wrote this script shoule be with bash in mind, but it still bothers me as to why the author didn't notice this problem.

The downside of using bash will be risky of non-portatability.

**Comment by roadToit** [comment]
bash startup.sh -m standalone

**Comment by ljhrot** [comment]
@i will solve it@

**Comment by ljhrot** [comment]
@i will solve it@

**Comment by fyeeme** [comment]
use this on Ubuntu

```shell
bash startup.sh -m standalone
```
