### ISSUE TITLE
这是什么问题？日志报错

### ISSUE THREAD

**Issue by chenjun-1201** [alibaba/nacos#3398]
nohup: /Library/Internet: No such file or directory
我用的是mac系统

**Comment by xiaojiecapf** [comment]
？什么功能呀！找不到文件错误

**Comment by KomachiSion** [comment]
麻烦详细描述问题，不然没有上下文谁都没办法帮你。

**Comment by chenjun-1201** [comment]
环境什么的都配好了，macos启动nacos的时候:
macdeMacBook-Air:bin mac$ sh startup.sh
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/mac/Downloads/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/mac/Downloads/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/mac/Downloads/nacos/plugins/health,/Users/mac/Downloads/nacos/plugins/cmdb -Dnacos.home=/Users/mac/Downloads/nacos -jar /Users/mac/Downloads/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/Users/mac/Downloads/nacos/conf/ --logging.config=/Users/mac/Downloads/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos is starting with cluster
nacos is starting，you can check the /Users/mac/Downloads/nacos/logs/start.out


我不知道这是什么问题。

**Comment by xiaojiecapf** [comment]
一般情况下，是集群启动，需要mysql，是否可以在启动的时候，sh startup.sh -m standalone 执行这个命令  不知是否能解决你的问题，如何是源码启动的话 -Dnacos.standalone=true 添加这个参数

**Comment by chenjun-1201** [comment]
试过好多遍了，每次都打印上面的内容

**Comment by xiaojiecapf** [comment]
/Users/mac/Downloads/nacos/logs/start.out 这个文件里面是否有错误！能否发出来，查看一下！

**Comment by chenjun-1201** [comment]
发了，在最上面
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/mac/Nacos/distribution/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/mac/Nacos/distribution/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/mac/Nacos/distribution/plugins/health,/Users/mac/Nacos/distribution/plugins/cmdb -Dnacos.home=/Users/mac/Nacos/distribution -jar /Users/mac/Nacos/distribution/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/Users/mac/Nacos/distribution/conf/ --logging.config=/Users/mac/Nacos/distribution/conf/nacos-logback.xml --server.max-http-header-size=524288
nohup: /Library/Internet: No such file or directory

**Comment by chenjun-1201** [comment]
> 麻烦详细描述问题，不然没有上下文谁都没办法帮你。

回我一下，拜托了

**Comment by xiaojiecapf** [comment]
我想你还是检查一下你的电脑环境吧！

**Comment by KomachiSion** [comment]
看第一行， `/Library/Internet Plug-Ins/` 由于空格没有做转译， 因此读取成了`/Library/Internet`
启动脚本会读取您的javahome，建议修改一下java路径，这个问题应该就解决了。
