### ISSUE TITLE
The nacos cluster cannot find the host list

### ISSUE THREAD

**Issue by Yangstatus** [alibaba/nacos#3403]
When I successfully deployed the nacos cluster, I changed the TYPE of SVC from ClusterIP to NodePort!
The Nacos Pod logs output the following log information:

2020/07/21 15:35:53 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.default.svc.cluster.local
Hosts in list: nacos-headless.default.svc.cluster.local
2020/07/21 15:35:54 Have not found myself in list yet.
My Hostname: nacos-0.nacos-headless.default.svc.cluster.local
Hosts in list: nacos-headless.default.svc.cluster.local

When I change the type of nacos SVC back to ClusterIP and ClusterIP=None. Nacos POD output log is normal.

How can this situation be resolved?And I have to go through the NodePort release port! 
Thanks a lot !

**Comment by KomachiSion** [comment]
See the error, there are difference between your `cluster.conf` file and local hostName.

```
Hostname: nacos-0.nacos-headless.default.svc.cluster.local
cluster.conf: nacos-headless.default.svc.cluster.local
```
