### ISSUE TITLE
the nacos metadata automatic loss  sometime  within standalone mode in 1.2.1 version

### ISSUE THREAD

**Issue by meiliangdeng** [alibaba/nacos#3404]
hi, i use  the nacos service governance and manage the service metadata  feature, running with standalone mode in 1.2.1v and the custom php-sdk with open-api.
some open-api of my service is normal work such as the Register instance &the Send instance beat api  which include custom metadata. but it is random appearance  that service metadata automatic loss in the nacos dashboard and open-api  Query instances  also cannot get the service custom metadata, t.  I think it may be the bug of nacos and loss the meta data, how i can resolve this bug.

**Comment by KomachiSion** [comment]
Can you provide more detail information?

I haven't encountered it before and can't reproduce it through openAPI.

**Comment by meiliangdeng** [comment]
i have found the cause of the problem: after registering an instance by the Register instance api,then the heartbeat data is sent periodically every 5 seconds, but if there is network delay, beat data takes more than 10 seconds to reach the nacos server, the old instance data just now will be lost and  the current heartbeat will produce a new instance without metadata,it is like as instance metadata is loss.
