### ISSUE TITLE
nacos1.3.1 遇到了用户权限问题

### ISSUE THREAD

**Issue by noahwxr** [alibaba/nacos#3408]
Hello, there are three namespaces under Nacos, namely A, B, and C. User device names only grant C the role of read and write permissions. There is another problem, the project startup configuration read-only user reads the configuration file in C space read-only, if the password of user device name is changed, the project will report logon failure: {" code ": 403," content ":" unknown user!" } the error

The Nacos version is 1.3.1

**Comment by KomachiSion** [comment]
you means you change password in console, and then change sdk's password and restart, but return 403 error?

**Comment by KomachiSion** [comment]
No more response from author, close issue
