### ISSUE TITLE
1.3.0docker配置集群模式异常

### ISSUE THREAD

**Issue by yueyuanyu** [alibaba/nacos#3411]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

使用nacos作为注册中心,单机模式正常,但是切换到集群模式下(mode改为cluster)docker compose配置如下;
单机模式配置(运行正常)
![image](https://user-images.githubusercontent.com/33542699/88143822-76ad8f00-cc2a-11ea-9d74-ab85438882ab.png)
集群模式配置(运行异常,特别卡顿,疯狂的gc,最后导致服务宕机,只运行了一台机器)
![image](https://user-images.githubusercontent.com/33542699/88142955-fa667c00-cc28-11ea-842b-9691d2658225.png)
只在一台机器上启动了一个nacos服务,mode改为cluster后,非常的卡,服务只有部分能注册上,随便点一个都会疯狂gc 最后服务宕掉
![image](https://user-images.githubusercontent.com/33542699/88143162-57623200-cc29-11ea-8642-f32e0f42a932.png)

### Describe what you expected to happen
麻烦帮我看下是dockercompose配置有问题还是怎么回事,此外,集群信息里为什么是open-test:8848,这是哪里来的呢

### Tell us your environment

ubuntu14.04

**Comment by yueyuanyu** [comment]
不是自己基于乌班图制作镜像而导致错误的原因,使用官方原生镜像和官方提供的docker-compose-hostname那个也是这个情况

**Comment by KomachiSion** [comment]
一个个问题来
1. 集群模式卡顿，疯狂gc， 我看内存设置的有点小，XMN稍微开大点呢 768M试试， 我本地启动docker的时候3个参数就是1G 1G 768M 不会很卡，少量测试请求也不会疯狂gc
2. 另一种导致运行卡顿可能是dokcer的resource设置的很小，导致3个container之间争抢资源（需要自己排查调整试试）
3. 节点里新增了个open-test，推测是nacos在获取container 地址的时候，获取到的，然后添加到cluster里了。排查的话可以启动container之后 进去查看下hostname是什么。

**Comment by yueyuanyu** [comment]
> 一个个问题来
> 
> 1. 集群模式卡顿，疯狂gc， 我看内存设置的有点小，XMN稍微开大点呢 768M试试， 我本地启动docker的时候3个参数就是1G 1G 768M 不会很卡，少量测试请求也不会疯狂gc
> 2. 另一种导致运行卡顿可能是dokcer的resource设置的很小，导致3个container之间争抢资源（需要自己排查调整试试）
> 3. 节点里新增了个open-test，推测是nacos在获取container 地址的时候，获取到的，然后添加到cluster里了。排查的话可以启动container之后 进去查看下hostname是什么。
好的 我按你的思路逐个排查下

**Comment by yueyuanyu** [comment]
![image](https://user-images.githubusercontent.com/33542699/88161865-22fb6f80-cc43-11ea-8acd-633aa5946eed.png)

**Comment by yueyuanyu** [comment]
目前暂未解决

**Comment by KomachiSion** [comment]
@paderlol Can you help to research problems?

**Comment by yueyuanyu** [comment]
> @paderlol Can you help to research problems?

问题;
1.参考官方demo,自己拉的nacos写的空项目弄得nacos-server(主要是为了加入flyway初始化数据库),其中一直不明白9555端口的作用.
2.上面提到的opentest域名经排查发现是本机用户名,切换成ip后(之前选的是hostname),就显示的是ip了.但依旧存疑,主要是为什么集群管理那里看到的有ip又有host形式的(配置的集群列表为host+port)
3.今天在我本地win10环境下搭了个nacos-server集群,采用的cluster.conf形式,同样配置的是host+port,一启动自动添加ip+端口形式到列表中(这个问题应该是同第二点的疑问是同一个问题)
4.卡顿的原因,在我本机环境搭建的集群这次也加上了nginx 我的服务也是用的nginx地址,但是和之前一样,过了一阵后就开始卡顿,原因发现是在疯狂输出日志,日志很快就达到按G来计算的级别了.推测是日志输出问题导致的

**Comment by yueyuanyu** [comment]
`2020-07-24 15:50:57,905 INFO [NACOS-DISTRO] healthy server list changed, old: [192.168.100.104:8847, 192.168.100.104:8848, 192.168.100.104:8849, mss-nacos01.ns.me:8848, mss-nacos02.ns.me:8849, mss-nacos03.ns.me:8847], new: [192.168.100.104:8847, 192.168.100.104:8848, 192.168.100.104:8849, mss-nacos01.ns.me:8848, mss-nacos02.ns.me:8849, mss-nacos03.ns.me:8847]`
日志对应上述所说的问题2.3 为什么会默认自动加上ip+port的 我手动添加的是host+port, 此外也是发现日志输出的增长的太快(这是本机环境测试集群,暂未挪到公司的测试集群)

**Comment by paderlol** [comment]
1 问题9555是开启远程debug的，默认是关闭掉的
2.ip问题，是因为Nacos需要判断自己本机的IP，所以有host和ip两种模式，主要应对容器内部的问题，因为容器内部你如果配置宿主机ip，内部获取不到宿主机的IP
3.IP列表最终都是解析成ip的，这是server的特性
4 日志如果是心跳或者config打印的应该是有问题的，这个issue应该是修复了，可以看下1.3.0的包或者1.3.1

**Comment by yueyuanyu** [comment]
目前测试的包都是1.3.0 改成1.3.1后依旧没得到解决

**Comment by yueyuanyu** [comment]
> 1 问题9555是开启远程debug的，默认是关闭掉的
> 2.ip问题，是因为Nacos需要判断自己本机的IP，所以有host和ip两种模式，主要应对容器内部的问题，因为容器内部你如果配置宿主机ip，内部获取不到宿主机的IP
> 3.IP列表最终都是解析成ip的，这是server的特性
> 4 日志如果是心跳或者config打印的应该是有问题的，这个issue应该是修复了，可以看下1.3.0的包或者1.3.1

我自己再试试吧

**Comment by KomachiSion** [comment]
日志多推测是因为你多出来3个节点，然后服务之间的心跳一直失败的报错日志。而且你都是本地部署，相当于错误日志*3.

主要还是看下为什么你的环境设置会多出这3个域名

**Comment by yueyuanyu** [comment]
> 日志多推测是因为你多出来3个节点，然后服务之间的心跳一直失败的报错日志。而且你都是本地部署，相当于错误日志*3.
> 
> 主要还是看下为什么你的环境设置会多出这3个域名
本地环境上 cluster.conf 配置的三个host+port ,启动后默认解析成ip+port 这个时候就多了三个,这种情况如何解决呢

**Comment by paderlol** [comment]
你是说你自己配置了cluster conf？

**Comment by paderlol** [comment]
Docker镜像里面是不用自己设置cluster.conf的，配置环境变量就可以了

**Comment by yueyuanyu** [comment]
> Docker镜像里面是不用自己设置cluster.conf的，配置环境变量就可以了

你好 dockercompose集群版搭建的不是的,具体情况真说不明白了,应该感觉和大家的配置方法  没什么差别,那麻烦你帮我看下使用dockercompose集群版的yml文件写对没.目前唯一差别就是在微服务的server-addr上使用nginx反向代理地址,而不是写nacos的地址列表,不知道这一点是否是造成卡顿的原因所在

**Comment by paderlol** [comment]
你的配置文件怎么写的？方便发出来看下吗？

**Comment by yueyuanyu** [comment]
> 你的配置文件怎么写的？方便发出来看下吗？

就是问题描述中的第二张图片,集群模式,不同点是prefer_host_mode改为了ip其他是一致的

**Comment by paderlol** [comment]
你可以exec进去看下 cluster.conf吗？还有etc/hosts里面挂的是什么？

**Comment by paderlol** [comment]
你不要直接挂/etc/hosts 这个操作很危险的啊

**Comment by paderlol** [comment]
你如果需要扩展hosts文件 你可以通过下面的方式 而不是直接用宿主机的方式覆盖 这种操作会带来很多莫名其妙的问题的.
``` yaml
extra_hosts:
  - "somehost:162.242.195.82"
  - "otherhost:50.31.209.229"
```
可以看下Docker Compose官方文档[compose-file/#extra_hosts](https://docs.docker.com/compose/compose-file/#extra_hosts)

**Comment by yueyuanyu** [comment]
> 你如果需要扩展hosts文件 你可以通过下面的方式 而不是直接用宿主机的方式覆盖 这种操作会带来很多莫名其妙的问题的.
> 
> ```yaml
> extra_hosts:
>   - "somehost:162.242.195.82"
>   - "otherhost:50.31.209.229"
> ```
> 
> 可以看下Docker Compose官方文档[compose-file/#extra_hosts](https://docs.docker.com/compose/compose-file/#extra_hosts)

忘说了 直接挂载那个是取消了的 shi使用的是下面这个
![image](https://user-images.githubusercontent.com/33542699/88454856-dadb8780-cea4-11ea-8598-17ba551b6ecf.png)

**Comment by paderlol** [comment]
没有挂在hosts？ 还有你的cluster配置现在可以打开看下？

**Comment by yueyuanyu** [comment]
> 没有挂在hosts？ 还有你的cluster配置现在可以打开看下？

没懂呢?就是以上面集群版的dockercompose启动三个节点(对应得host的机器上)

**Comment by paderlol** [comment]
额,我的意思是进入容器去确认下集群配置文件里面是不是写了这些节点,或者多写了节点

**Comment by yueyuanyu** [comment]
> 额,我的意思是进入容器去确认下集群配置文件里面是不是写了这些节点,或者多写了节点
![image](https://user-images.githubusercontent.com/33542699/88455620-622afa00-cea9-11ea-9187-71e595c0567e.png)
这个是启了一个nacos节点,会在自己增加一个本机 ip地址 这个情况是对的吗

**Comment by paderlol** [comment]
不对

**Comment by paderlol** [comment]
你看这是我刚起来的
![image](https://user-images.githubusercontent.com/7919984/88456385-f5672e00-ceaf-11ea-992c-66098540841e.png)

**Comment by paderlol** [comment]
这是ip模式的 你肯定哪里配置了一个ip设置进去了
![image](https://user-images.githubusercontent.com/7919984/88456428-50992080-ceb0-11ea-962e-4ef1268c8093.png)

**Comment by paderlol** [comment]
你检查下,你拿的我的脚本比对一下吧

**Comment by yueyuanyu** [comment]
> 你检查下,你拿的我的脚本比对一下吧

![image](https://user-images.githubusercontent.com/33542699/88456979-59d8bc00-ceb5-11ea-8a45-f793ab1583ac.png)
无论是ip还是hostname模式,都会加入一个本机节点(比如最上面那张图open-test:8848那个节点实际上是这台机器用户名+端口),我确实没有手动加一个ip这种操作.你能贴个你的脚本出来吗 或者这个demo我能看下吗

**Comment by paderlol** [comment]
我知道原因了，你没有设置docker的host，因为nacos每个节点需要判断当前的节点是不是自己，不是自己的就会插入，所以选主也不会成功，推荐使用hostname模式，并且设置host，可以参考我的clusterhostname我都设置了host的，然后你的集群节点配置的这个域名是外部域名？还是你自己设置的，要和host保持一致

**Comment by paderlol** [comment]
你看我的cluster hostname里面都有设置的host，ip模式里面我会指定每个节点的ip，所以会创建一个网络

**Comment by yueyuanyu** [comment]
> 我知道原因了，你没有设置docker的host，因为nacos每个节点需要判断当前的节点是不是自己，不是自己的就会插入，所以选主也不会成功，推荐使用hostname模式，并且设置host，可以参考我的clusterhostname我都设置了host的，然后你的集群节点配置的这个域名是外部域名？还是你自己设置的，要和host保持一致

docker host? 我们一直都采用的
![image](https://user-images.githubusercontent.com/33542699/88457218-3f074700-ceb7-11ea-9172-2a0ed2e1badd.png)这种方式映射的宿主机hosts,host我都映射到对应机器ip了的 .我明白你的意思,但是我不明白你说的推荐使用"并且设置host", 是我漏了指定host的配置吗?. 正常来讲不应是在/etc/hosts中指定对应host的ip,然后映射到docker中吗,我刚才查看了使用networkmode是映射到docker中host成功了的,还有你的clusterhostname我看也是指定三个节点host,我的也是指定了三个节点并且对应docker容器中/etc/hosts中也指定了正确的host对应ip,但还是会自己加入自己节点.  如你所说的mode使用hostname而不是ip也会加入自己(open-test是宿主机名)
![image](https://user-images.githubusercontent.com/33542699/88457437-edf85280-ceb8-11ea-883c-96032e158855.png)

**Comment by paderlol** [comment]
你要etc的hosts里面能找到你配置的节点其中的一个啊，所以我让你看我的配置我的compose文件里面有指定的比如nacos1那对应就有一个nacos1 的host名

**Comment by paderlol** [comment]
version: "3"
services:
  nacos1:
    hostname: nacos1 #这里是hostname对应
    container_name: nacos1

**Comment by paderlol** [comment]
你看下面两张图,这才是正确的hosts里面的对应关系,图一是IP模式 图二是hostname模式, Nacos会去获取本机的IP然后来判断自己是属于cluster.conf里面哪一个,你的compose里面没有配置host或者指定ip,所以获取的时候是匹配不上的,这跟你映射不映射自己宿主机的hosts没有任何关系的
![image](https://user-images.githubusercontent.com/7919984/88458165-ad033c80-cebe-11ea-98aa-1c35319af847.png)
![image](https://user-images.githubusercontent.com/7919984/88458203-f9e71300-cebe-11ea-9bcc-a87802afb353.png)

**Comment by yueyuanyu** [comment]
> 你看下面两张图,这才是正确的hosts里面的对应关系,图一是**IP**模式 图二是**hostname**模式, Nacos会去获取本机的IP然后来判断自己是属于cluster.conf里面哪一个,你的compose里面没有配置host或者指定ip,所以获取的时候是匹配不上的,这跟你映射不映射自己宿主机的hosts没有任何关系的,你指定docker的host网络模式,是让你的docker去使用宿主机的网络,取消docker本身的网络隔离机制,这跟Nacos完全没任何关系
> 
> 然后说回你的编排,你配置的这个mss-nacos03.ns.me ,我不确定你用的公网域名还是自己定内部Host,如果前者建议取消 这个完全没必要,你内部集群 和外面访问用什么域名没有什么关系,如果是后者,那你肯定是要使用mode:hostname这个模式的,而且要配置我前面发的代码片段里面的hostname:mss-nacos03.ns.me 类似于这样
> 
> ```yaml
> version: "3"
> services:
>   nacos1:
>     hostname: mss-nacos01.ns.me
>     container_name: nacos1
>  # other code ....
>   nacos2:
>     hostname: mss-nacos02.ns.me
>     container_name: nacos2
>  # other code ....
>   nacos3:
>     hostname: mss-nacos03.ns.me
>     container_name: nacos3
> 
> # 这里端口都是容器内部端口 部是宿主机的
> NACOS_SERVERS=mss-nacos01.ns.me:8848 mss-nacos02.ns.me:8848 mss-nacos03.ns.me:8848
> ```
> 
> ![image](https://user-images.githubusercontent.com/7919984/88458165-ad033c80-cebe-11ea-98aa-1c35319af847.png)
> ![image](https://user-images.githubusercontent.com/7919984/88458203-f9e71300-cebe-11ea-9bcc-a87802afb353.png)

懂了 谢谢你,我拿测试环境试试,还会不会出现刚切换成cluster就瞬间巨卡的情况. 就是能够确定应该是我配置哪里有问题,但是之前没有定位到这个地方

**Comment by paderlol** [comment]
你的卡顿应该是这个选主一直没有选出来，不停在重试，错误日志飙升导致的

**Comment by paderlol** [comment]
那我暂时关闭这个issue了

**Comment by paderlol** [comment]
那我暂时关闭这个issue了

**Comment by yueyuanyu** [comment]
> 那我暂时关闭这个issue了
按照你的方式配置后现在是这个情况
![image](https://user-images.githubusercontent.com/33542699/88481942-e6a47800-cf90-11ea-9a62-cabc6b203c0d.png)

**Comment by paderlol** [comment]
你的network 是不是还是没去掉host?

**Comment by paderlol** [comment]
麻烦你按照我昨天给你截图去对比,然后把截图放出来好吗？你的配置有自定义的,没有按照我在官方给的例子,我很难去帮你排错。

**Comment by yueyuanyu** [comment]
> 麻烦你按照我昨天给你截图去对比,然后把截图放出来好吗？你的配置有自定义的,没有按照我在官方给的例子,我很难去帮你排错。
果然是network: host导致多一个注册节点,但是有个疑问我看官方示例上没有挂载host 那他如何找到其他节点呢,目前我只开了一个节点,并且在宿主机上hosts这三个nacos都指向的相同的ip,现在是这个情况,服务也没注册上去

![image](https://user-images.githubusercontent.com/33542699/88482470-f1acd780-cf93-11ea-975d-b880c099f25b.png)

**Comment by paderlol** [comment]
跟宿主机的host 没有关系的,我说了每个docker container都有自己的host,独立隔离的,Nacos Server每个节点都需要判断当前节点中的某一个和自己host要匹配,所以才需要在docker 节点配置hostname,然后跟你宿主机没有任何关系,关于这方面的问题你可能需要自己看下Dokcer官方的相关文档,宿主机访问容器用的宿主机的端口,容器内部交互 都用的容器内的端口,比如8848,因为每个Container都隔离了,所以可以都用8848,但是外部宿主机,你看到我每个都配置了不同的端口去映射.

**Comment by yueyuanyu** [comment]
> 跟宿主机的host 没有关系的,我说了每个docker container都有自己的host,独立隔离的,Nacos Server每个节点都需要判断当前节点中的某一个和自己host要匹配,所以才需要在docker 节点配置hostname,然后跟你宿主机没有任何关系,关于这方面的问题你可能需要自己看下Dokcer官方的相关文档,宿主机访问容器用的宿主机的端口,容器内部交互 都用的容器内的端口,比如8848,因为每个Container都隔离了,所以可以都用8848,但是外部宿主机,你看到我每个都配置了不同的端口去映射.

demo中设置了hostname,是基于单机多节点的情况吧,如果是多机集群的话还是要映射hosts吧 不然它怎么找到其他节点呢

**Comment by paderlol** [comment]
NACOS_SERVER_IP 用这个指定每台机器的节点Ip

**Comment by yueyuanyu** [comment]
> NACOS_SERVER_IP 用这个指定每台机器的节点Ip

我用extra_host单独加入哪两个节点的host和ip后 现在出现leader 了  但是目前的情况是,只有部分服务注册上来了,这部分我先自己排查下吧,切换成单机模式都可以全部注册.谢谢你

**Comment by paderlol** [comment]
extra_host单独加入哪两个节点的host和ip后,这个不对啊,每个节点是要设置自己的host在/etc/host,不是要把所有的节点ip在每个节点的/etc/hosts设置上,我上面不是给你举例了吗？
NACOS_SERVER_IP 用这个指定host就行了,指定这个就不会去再拿etc/host做比较了。

**Comment by yueyuanyu** [comment]
> extra_host单独加入哪两个节点的host和ip后,这个不对啊,每个节点是要设置自己的host在/etc/host,不是要把所有的节点ip在每个节点的/etc/hosts设置上,我上面不是给你举例了吗？
> NACOS_SERVER_IP 用这个指定host就行了,指定这个就不会去再拿etc/host做比较了。

是在NACOS_SERVER_IP指定当前节点host吗 (加了这句报端口冲突与我那个8544,但实际上怎么换都会报端口冲突),目前好像就只有直接加extrahost 接近成功了 难搞
![image](https://user-images.githubusercontent.com/33542699/88484625-76065700-cfa2-11ea-896c-dd5b8aeb8a92.png)

**Comment by paderlol** [comment]
你如果是多台机器,可以参考这个使用,我这个用的embedded模式的集群,三台局域网机器
``` yaml
version: "3"
services:
  nacos:
    container_name: nacos
    image: nacos/nacos-server:latest
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    ports:
      - 8848:8848
      - 7848:7848
    environment:
      - PREFER_HOST_MODE=ip
      - NACOS_SERVER_IP=192.168.24.225 #每台机器自己的局域网ip 比如这台机器就是225的局域网Ip
      - EMBEDDED_STORAGE=embedded
      - NACOS_SERVERS=192.168.24.225:8848 192.168.24.246:8848 192.168.24.202:8848
    restart: always
```

![image](https://user-images.githubusercontent.com/7919984/88502606-87cb1700-d001-11ea-867e-c3b9d4dbf5ce.png)

**Comment by yueyuanyu** [comment]
> ```yaml
> PREFER_HOST_MODE
> ```
上正式环境应该是要用hostname来搞的,如果不映射hosts的话那就算我指定了当前容器hostname(比如mss-nacos01.ns.me),NACOS_SERVERS=01,02,03  那他应该是找不到那两台机器的吧,也就会出现我上面那两个情况suspicious,也无法选举leader,服务也注册不上去.- NACOS_SERVER_IP来指定的话这个不是指定的ip吗,而且我按你说的指定host比如 NACOS_SERVER_IP=01,02,03 就会出现其他错误,报我那个用于启动的空项目端口被占用(这个空项目只是为了初始化flyway,我们对数据库的操作要求必须通过flyway),而且感觉NACOS_SERVER_IP应该是用来指定ip列表的,指定host感觉不对呢

**Comment by yueyuanyu** [comment]
> ```yaml
> PREFER_HOST_MODE
> ```



> 你如果是多台机器,可以参考这个使用,我这个用的embedded模式的集群,三台局域网机器
> 
> ```yaml
> version: "3"
> services:
>   nacos:
>     container_name: nacos
>     image: nacos/nacos-server:latest
>     volumes:
>       - ./cluster-logs/nacos1:/home/nacos/logs
>     ports:
>       - 8848:8848
>       - 7848:7848
>     environment:
>       - PREFER_HOST_MODE=ip
>       - NACOS_SERVER_IP=192.168.24.225 #每台机器自己的局域网ip 比如这台机器就是225的局域网Ip
>       - EMBEDDED_STORAGE=embedded
>       - NACOS_SERVERS=192.168.24.225:8848 192.168.24.246:8848 192.168.24.202:8848
>     restart: always
> ```
> 
> ![image](https://user-images.githubusercontent.com/7919984/88502606-87cb1700-d001-11ea-867e-c3b9d4dbf5ce.png)

上正式环境应该是要用hostname来搞的,如果不映射hosts的话那就算我指定了当前容器hostname(比如mss-nacos01.ns.me),NACOS_SERVERS=01,02,03 那他应该是找不到那两台机器的吧,也就会出现我上面那两个情况suspicious,也无法选举leader,服务也注册不上去.- NACOS_SERVER_IP来指定的话这个不是指定的ip吗,而且我按你说的指定host比如 NACOS_SERVER_IP=01,02,03 就会出现其他错误,报我那个用于启动的空项目端口被占用(这个空项目只是为了初始化flyway,我们对数据库的操作要求必须通过flyway),而且感觉NACOS_SERVER_IP应该是用来指定ip列表的,指定host感觉不对呢

**Comment by paderlol** [comment]
不知道你们为什么一定要用host访问，尤其你们还不是k8s，配置ip为啥不行？你要指定这种host的搞法，肯定需要指定extra，还有server ip同样要指定，这个你们自己权衡吧。

**Comment by paderlol** [comment]
NACOS_SERVER_IP，这个就是当本机出现多网卡得时候，指定一个地址作为nacos当前节点自己的地址，不是让你同时配三个啊，是每个节点配自己的就行了。

**Comment by yueyuanyu** [comment]
好吧 谢谢
