### ISSUE TITLE
nacos1.3.0 不同权限用户监听配置，遇到鉴权问题

### ISSUE THREAD

**Issue by dyiwen** [alibaba/nacos#3413]
Namespace: public, T1

Configuration in T1:
       dataId: api1
       group: DEFAULT_ GROUP

User: dev

Permission of dev: T1 (read and write)

When the client uses dev to listen to the API1 configuration in T1, it reports 403 permission denial. The dev must be granted at least read permission to the public in order to listen normally.

Can I allow the read-write users under the namespace to listen to the configuration under the namespace normally?
-----
命名空间:public,T1
T1中的配置：
     dataId: api1
     group: DEFAULT_GROUP
用户：dev
dev的权限：T1（read-and-write）
当客户端通过dev去监听T1中的api1配置时，报403权限拒绝，必须给dev授予public的至少读权限，才能正常监听。
可否让命名空间下的读写用户可以正常监听命名空间下的配置？

**Comment by ljhrot** [comment]
@dyiwen 你好，请问能贴一下客户端调用监听配置接口的请求参数吗？

**Comment by KomachiSion** [comment]
No more response from author, but we need more information.

**Comment by zhangjinling** [comment]
wen create user don`t have namespace public read right.listenConfig will 403.
log:
"status":403,"error":"Forbidden","message":"authorization failed!","path":"/nacos/v1/cs/configs/listener"
```
	configparam := vo.ConfigParam{DataId: dataid, Group: group, Content: "", OnChange: func(namespace, group, dataId, data string) {
		fmt.Println("ListenConfig:", namespace, group, dataId, data)
	}}
	errListen := configClient.ListenConfig(configparam)
```
