### ISSUE TITLE
是否有生产环境1.1.4升级到1.3.1的方法？

### ISSUE THREAD

**Issue by xuet0ng** [alibaba/nacos#3414]
### 现状
- 目前我们生产使用了nacos 1.1.4版本
- 统一使用了alibaba的spring cloud starter nacos，2.1.1.RELEASE版本
- 目前已经有将近100的微服务注册上去了

### 问题
由于生产环境权限管控问题，希望将nacos升级到1.2.0以上的版本，有以下几个问题麻烦咨询下：

- nacos目前为1.3.1，1.3.x后续还有版本规划么？大致时间节奏是怎么样子？
- nacos-client和nacos-server的版本是否需要严格匹配，1.1.4的nacos-client和1.3.1或者1.3.x的nacos能配合使用么？
- alibaba spring cloud starter nacos和这面nacos的版本一般是个什么节奏，目前从[wiki](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)上还未看见支持1.3.x的版本，大概什么时候能支持？
- 对于符合以上现状的生产环境nacos升级，有其他建议么？

```
           <ali-nacos-spring-client.version>2.1.1.RELEASE</ali-nacos-spring-client.version>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>${ali-nacos-spring-client.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>${ali-nacos-spring-client.version}</version>
            </dependency>
```

### 非常感谢！！！

**Comment by KomachiSion** [comment]
1. 目前nacos客户端版本和服务端版本可以通用（当然不能开鉴权，因为是1.2以后加的新功能，1.2以前的客户端肯定没有这个功能）
2. 服务端可以直接灰度逐台升级，支持平滑升级
3. alibaba spring cloud starter nacos支持1.3.1的版本正在发布中。

**Comment by xuet0ng** [comment]
> 1. 目前nacos客户端版本和服务端版本可以通用（当然不能开鉴权，因为是1.2以后加的新功能，1.2以前的客户端肯定没有这个功能）
> 2. 服务端可以直接灰度逐台升级，支持平滑升级
> 3. alibaba spring cloud starter nacos支持1.3.1的版本正在发布中。

第一点信息对我们非常重要！我在确认下
- 也就是我们可以先滚动升级nacos server到1.3.1（不开鉴权），而客户端仍然用nacos-client 1.1.4（alibaba spring cloud starter nacos的2.1.1.RELEASE版本）
- 后面考虑逐步升级客户端的jar包到最新版本

对了，请问1.1.4到1.3.1可以直接升级么？还是需要先升级到1.2.1？

**Comment by KomachiSion** [comment]
可以直接升级
