### ISSUE TITLE
使用创建的用户并授权后启动spring-cloud-gateway服务报错

### ISSUE THREAD

**Issue by David-wu91** [alibaba/nacos#3418]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
1.3.0版本，创建用户，并授予用户指定命名空间读写权限，并将此用户配置在spring-cloud-gateway服务配置文件中，启动服务后报错：2020-07-23T08:56:52,590|ERROR|boundedElastic-1|com.alibaba.nacos.client.naming||request: /nacos/v1/ns/operator/metrics failed, servers: [http://10.60.20.131:80], code: 403, msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Jul 23 08:56:52 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
duplicate with #2866
