### ISSUE TITLE
nacos  0.5 mysql数据库配置 问题

### ISSUE THREAD

**Issue by flystar32** [alibaba/nacos#342]
今天使用nacos0.5发现个现象，nacos服务使用mysql数据库时，数据库名不能使用“_”分隔，如nacos_server，会提示连接不上，改成nacosserver后成功

**Comment by hxy1991** [comment]
请问是在什么系统下操作的？有什么错误日志吗？我在 MacOS 下是没问题的。

当前版本下， `db.url` 直接设置到 `org.apache.commons.dbcp.BasicDataSource` 的 `url` 字段中，Nacos 并没有对数据库名称有任何处理。

源码可参看下：[BasicDataSourceServiceImpl.java#L134-L142](https://github.com/alibaba/nacos/blob/e05bc7a682250d10e0ef98a940bdaa962f5cb611/config/src/main/java/com/alibaba/nacos/config/server/service/BasicDataSourceServiceImpl.java#L134-L142)
