### ISSUE TITLE
什么原因会导致Nacos节点集体崩溃？怎么查询相关问题？

### ISSUE THREAD

**Issue by yyt6200** [alibaba/nacos#3422]
环境：三台服务器分别部署一个Nacos节点
情况：今天发现三台Nacos都down了
猜测：开发环境与测试环境的项目配置文件不同，测试环境比开发环境少了一项配置。加上后到现在Nacos未挂。
不知道是不是上面描述的原因，希望指导下哪里能查相关的问题（Nacos的宕机日志）

**Comment by KomachiSion** [comment]
什么版本，什么配置？

**Comment by yyt6200** [comment]
1.2.1。我说的配置是具体项目的相关配置。将项目的配置托管在nacos,项目中使用@Value获取该配置项。
这种情况发生好几次了，但似乎每次都是因为我漏加了配置才会发生，想验证下这个问题是否因为配置项导致的。

**Comment by KomachiSion** [comment]
没遇到过。。。 而且你说的配置如果是业务配置，那得根据复现的情况排查具体问题了。或许是漏配置，然后触发了某种异常状态，导致sdk不停获取配置，然后服务端扛不住挂了。但是这种说法缺乏证据。

以目前的情报和信息，我们这边无法帮助定位问题。只能您自己排查了，或者看下社区有没有别人出现过类似的问题。

**Comment by yyt6200** [comment]
今天Nacos上又碰到服务无法下线，已挂服务实例无法下线的问题。麻烦大牛指导下怎么排查问题，日志已保存。

**Comment by yyt6200** [comment]
![节点错误](https://user-images.githubusercontent.com/44914868/88520097-b2c76200-d025-11ea-9a9e-0629f6f01b9e.png)
![nacos](https://user-images.githubusercontent.com/44914868/88520107-b6f37f80-d025-11ea-8100-4dd64ed3c63d.png)
图1是已经Exited的实例，28分钟前就退出了

**Comment by yyt6200** [comment]
另外最后补充下，我将110的Nacos服务重启后，服务的实例正常了。该下线的实例下线了

**Comment by yyt6200** [comment]
大牛 有空请帮忙看下这个问题，最近经常发生这样的情况

**Comment by KomachiSion** [comment]
duplicate with #3465
