### ISSUE TITLE
偶发！服务日志上打印和Nacos的心跳日志，但是Nacos服务列表里该服务的实例是0

### ISSUE THREAD

**Issue by yyt6200** [alibaba/nacos#3423]
环境：Nacos三个节点分部在三台服务器，服务跑在Swarm中
问题：服务是两个副本，其中一个Down了，一个正常运行（日志仍在和Nacos通信），但是Nacos的服务列表是该服务的实例显示为0，也就是无这个服务实例注册到Nacos

**Comment by KomachiSion** [comment]
is duplicate with #3337？

**Comment by yyt6200** [comment]
不是，与#3337 正好相反。这次是服务仍然活着，但是在nacos上没有相关服务的实例。

**Comment by KomachiSion** [comment]
2个副本注册是实例ip地址和port一致吗？

**Comment by yyt6200** [comment]
没明白您的意思

**Comment by KomachiSion** [comment]
副本A 注册到nacos里的ip port和 副本B注册的ip port是一样的吗

**Comment by yyt6200** [comment]
A和B的port是一样的，因为他们是同一个服务。ip地址不同 一个是10.0.1.86 另一个是10.0.1.87

**Comment by yyt6200** [comment]
nacos上是看不到这两个服务的，我是在docker中输出日志看到A还和Nacos维持心跳的。B是Down掉了。

**Comment by KomachiSion** [comment]
最开始是都能看到，然后Bdown掉之后 A也从nacos中不可见了？

**Comment by yyt6200** [comment]
最初什么样我不能确定，今天有同事跟我反馈XX服务调用失败了，我上去看就是这个情况。A,B两个服务，A服务仍然在维持心跳
持续输出com.alibaba.nacos.client.config.impl.ClientWorker - get changedGroupKeys:[]。B服务因为一些原因没起的来，Application run failed 了。但即使这个情况，nacos上应该显示一个服务的实例的

**Comment by KomachiSion** [comment]
这个输出的日志是配置中心的 不是心跳，哪怕服务全关了也是有的。 是否有心跳，到3个服务端 的naming-event和naming-server，去搜一下这两个实例的ip和port 看下是不是被disabled或者delete了

主要关键字：`{POS} {IP-DISABLED}` in naming-event , `AUTO-DELETE-IP` in naming-server

**Comment by yyt6200** [comment]
OK 我去查一下

**Comment by KomachiSion** [comment]
如果想进一步确认，就需要打开服务端的debug日志，然后看naming-event里的`[CLIENT-BEAT]` 日志

**Comment by KomachiSion** [comment]
但是这样日志的量会比较大，

**Comment by KomachiSion** [comment]
Have more information？ If no I will close issue，

**Comment by yyt6200** [comment]
这个 issue 可以关闭了，但是#3465 麻烦跟进下啊。谢谢
