### ISSUE TITLE
在nacos 的client启用udp端口，可以支持指定端口么。。

### ISSUE THREAD

**Issue by hujiang75277381** [alibaba/nacos#3424]
package com.alibaba.nacos.client.naming.core#PushReceiver

    public PushReceiver(HostReactor hostReactor) {
        try {
            this.hostReactor = hostReactor;

           //我们可以指定这个udp端口么,大佬 跪求这个功能
            udpSocket = new DatagramSocket();

            executorService = new ScheduledThreadPoolExecutor(1, new ThreadFactory() {
                @Override
                public Thread newThread(Runnable r) {
                    Thread thread = new Thread(r);
                    thread.setDaemon(true);
                    thread.setName("com.alibaba.nacos.naming.push.receiver");
                    return thread;
                }
            });

            executorService.execute(this);
        } catch (Exception e) {
            NAMING_LOGGER.error("[NA] init udp socket failed", e);
        }
    }

**Comment by KomachiSion** [comment]
指定端口的话会不会有风险？ 比如要接受几台server端的推送数据，同一个端口会不会造成冲突？

**Comment by hujiang75277381** [comment]
这个端口的作用不是接受服务端的推送呢？你启动的时候固定了，后面会变化？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;杨翊&amp;nbsp;SionYang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月23日(星期四) 下午2:09
收件人:&nbsp;&quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;;
抄送:&nbsp;&quot;xiaobiesan&quot;<75277381@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] 在nacos 的client启用udp端口，可以支持指定端口么。。 (#3424)

**Comment by KomachiSion** [comment]
> 这个端口的作用不是接受服务端的推送呢？你启动的时候固定了，后面会变化？------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;杨翊&amp;nbsp;SionYang&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年7月23日(星期四) 下午2:09 收件人:&nbsp;&quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;; 抄送:&nbsp;&quot;xiaobiesan&quot;<75277381@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [alibaba/nacos] 在nacos 的client启用udp端口，可以支持指定端口么。。 (#3424)

部分场景（比如迁移升级等），同一个客户端需要双连注册中心，但是指定的时候如果指定为同一个，就冲突了。

**Comment by KomachiSion** [comment]
discussion no more response, and we think udp port should randomly.
