### ISSUE TITLE
BUG 1.3.0 configService.getConfig取不到配置内容

### ISSUE THREAD

**Issue by chestarss** [alibaba/nacos#3426]
这个接口是NacosConfigService.getConfig中调用的，前端调用的有个show=all参数是可以返回，代码里只取配置文件内容

1.3.0 用这个接口取不到数据
/nacos/v1/cs/configs?dataId=xxx.yaml&group=DEFAULT_GROUP&tenant=xxx  取不到内容
/nacos/v1/cs/configs?dataId=xxx.yaml&group=DEFAULT_GROUP&tenant=xxx&show=all 可以返回json对象

1.1.3 中可以

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by mrKyleWang** [comment]
遇到了同样的问题，新增配置后，控制台配置列表可以看到，但ConfigCacheService里的CACHE没有相应的配置，Java应用Nacos客户端无法读取

**Comment by CHNWXY** [comment]
我这边升级到1.3.1 之后，@NacosInject直接不行了，ConfigService一直是null

**Comment by wangdejian163** [comment]
同样的问题，相同windows版本1.2.1，测试三台电脑，win7无法访问，2台win10正常。
/nacos/v1/cs/configs?dataId=xxx.yaml&group=DEFAULT_GROUP&tenant=xxx 取不到内容
/nacos/v1/cs/configs?dataId=xxx.yaml&group=DEFAULT_GROUP&tenant=xxx&show=all 可以返回json对象

**Comment by qinmou** [comment]
> 我这边升级到1.3.1 之后，@NacosInject直接不行了，ConfigService一直是null

我1.3.2也遇到这个问题

**Comment by KomachiSion** [comment]
I test in nacos-1.4.0, both api can get config.

you can test in nacos demo console.nacos.io

**Comment by mrKyleWang** [comment]
I update version to 1.4.0，now it's OK

**Comment by KomachiSion** [comment]
This problem has been fixed in 1.4.0
