### ISSUE TITLE
spring+nacos，项目中的properties文件属性读取不到

### ISSUE THREAD

**Issue by xiaosuiyue** [alibaba/nacos#3430]
In my project i use spring + nacos，
nacos config file used location properties，but cat't correct load the attribute value.
![image](https://user-images.githubusercontent.com/38514572/88273640-13e0f400-cd0d-11ea-8a82-baf926fd9de1.png)

![image](https://user-images.githubusercontent.com/38514572/88273724-3115c280-cd0d-11ea-8c73-96d5325a4bff.png)

the error message is :Can't get content from dataId : ${nacos.data-id}

it's looks looks like the configuration files load order problem.

**Comment by KomachiSion** [comment]
It seems that you do not import properties to spring xml configuration.
Not nacos problem.

**Comment by xiaosuiyue** [comment]
The spring xml configration as follow,



wyinjava@126.com
 
发件人： 杨翊 SionYang
发送时间： 2020-07-23 19:05
收件人： alibaba/nacos
抄送： xiaosuiyue; Author
主题： Re: [alibaba/nacos] spring+nacos，项目中的properties文件属性读取不到 (#3430)
It seems that you do not import properties to spring xml configuration.
Not nacos problem.

**Comment by xiaosuiyue** [comment]
I tried again just now,other xml configuration can get property value defined by the properties file, but nacos xml can't



wyinjava@126.com
 
发件人： 杨翊 SionYang
发送时间： 2020-07-23 19:05
收件人： alibaba/nacos
抄送： xiaosuiyue; Author
主题： Re: [alibaba/nacos] spring+nacos，项目中的properties文件属性读取不到 (#3430)
It seems that you do not import properties to spring xml configuration.
Not nacos problem.
