### ISSUE TITLE
When the new configuration type is properties, the save fails

### ISSUE THREAD

**Issue by haichao-hub** [alibaba/nacos#3433]
## Issue Description

Type: bug

### Describe what happened (or what feature you want)
When the new configuration type is properties, the save fails
新建配置的类型 为 properties 时，保存失败

console output:
`
main.js:285 Uncaught TypeError: Cannot read property 'currentLanguageCode' of undefined
    at main.js:285
    at main.js:317
    at Array.<anonymous> (main.js:317)
    at main.js:317
    at r (main.js:14)
    at e (main.js:14)
    at a (main.js:317)
    at n.value (main.js:285)
    at main.js:317
    at e (main.js:14)
`
### Tell us your environment
version1.3.1
windows 10

### Anything else we need to know?
When the configuration type is other, it can be saved successfully
配置类型为其它时，可以保存成功

**Comment by KomachiSion** [comment]
I tried in 1.3.1 demo console, properties can be published.

**Comment by KomachiSion** [comment]
I guess your first line is a comment. If so , the issue is duplicated with #3103.

**Comment by haichao-hub** [comment]
I tried again and found that it cannot be saved if the value is empty
`
logging.level.root=

logging.level.org.mybatis=DEBUG
`

**Comment by haichao-hub** [comment]
``
I tried again and found that it cannot be saved if the value is empty
``

**Comment by yanjunnf** [comment]
Seems like your configurations content syanx is wrong. The synax of properties format should be key=value
I checked the react js code, found below:
if (validateContent.validate({ content, type: configType })) {
        this.publicConfigBeforeCheck(content);
      } else {
        Dialog.confirm({
          content: locale.confirmSyanx,
          language: aliwareIntl.currentLanguageCode || 'zh-cn',
          onOk: () => {
            this.publicConfigBeforeCheck(content);
          },
        });
      }

**Comment by zongtanghu** [comment]
Can you help to resolve this issue?  @wangwei

**Comment by ljhrot** [comment]
@zongtanghu 这个 ISSUES 跟 #3103 重复，都是 `validateContent.validate({ content, type: configType })` 校验 Properties 配置内容失败，然后进入 `else` 判断，也就是下面这块逻辑

```js
Dialog.confirm({
  content: locale.confirmSyanx,
  language: aliwareIntl.currentLanguageCode || 'zh-cn',
  onOk: () => {
    this.publicConfigBeforeCheck(content);
  },
});
```

同时 `aliwareIntl.currentLanguageCode` 这个属性是不存在的，也就是上面前端的报错信息。

**Comment by yanjunnf** [comment]
问一下，咱们这边有React环境配置和编译步骤吗？

**Comment by zongtanghu** [comment]
@ljhrot 你可以提一个pr来修复下这个前端问题吗？

**Comment by ljhrot** [comment]
> @ljhrot 你可以提一个pr来修复下这个前端问题吗？

@zongtanghu 我给 #3103 提个 PR，也会修复这个的

**Comment by ljhrot** [comment]
> 问一下，咱们这边有React环境配置和编译步骤吗？

@yanjunnf 你可以看看这个 [README](https://github.com/alibaba/nacos/blob/develop/console/src/main/resources/static/console-fe/README.md)

**Comment by yanjunnf** [comment]
> > 问一下，咱们这边有React环境配置和编译步骤吗？
> 
> @yanjunnf 你可以看看这个 [README](https://github.com/alibaba/nacos/blob/develop/console/src/main/resources/static/console-fe/README.md)

看到了，多谢。

**Comment by guanshaochi** [comment]
1.3.0发现这个问题，更新1.3.1问题依旧，暂时是通过发布为其他类型配置文件再编辑修改为properties类型去规避的

**Comment by KomachiSion** [comment]
> @zongtanghu 这个 ISSUES 跟 #3103 重复，都是 `validateContent.validate({ content, type: configType })` 校验 Properties 配置内容失败，然后进入 `else` 判断，也就是下面这块逻辑
> 
> ```js
> Dialog.confirm({
>   content: locale.confirmSyanx,
>   language: aliwareIntl.currentLanguageCode || 'zh-cn',
>   onOk: () => {
>     this.publicConfigBeforeCheck(content);
>   },
> });
> ```
> 
> 同时 `aliwareIntl.currentLanguageCode` 这个属性是不存在的，也就是上面前端的报错信息。

duplicate with #3103
