### ISSUE TITLE
bad clone behaviour

### ISSUE THREAD

**Issue by MrLonelyJacky** [alibaba/nacos#3435]
the class AbstractHealthChecker and  subclass have  bad clone behaviour, a good clone behaviour should implents cloneable interface,the subclass do not. Another way, should use super.clone method,but the subclass like Http new a object,it is bad,because 
a class extend http may implents cloneable and use super.clone method in clone method,it errors!!!!

**Comment by sanxun0325** [comment]
@i will solve it@

**Comment by sanxun0325** [comment]
@MrLonelyJacky Can you describe this problem in more detail?  If it is convenient, we can add dingding to communicate.

**Comment by MrLonelyJacky** [comment]
> @MrLonelyJacky Can you describe this problem in more detail? If it is convenient, we can add dingding to communicate.
it is my pleasure,my dingding number is vinci15151936001. u used clone method,but do not provide a good clone behaviour.

**Comment by MrLonelyJacky** [comment]
> @MrLonelyJacky Can you describe this problem in more detail? If it is convenient, we can add dingding to communicate.

**Comment by MrLonelyJacky** [comment]
@sanxun0325 it is my pleasure,my dingding number is vinci15151936001. u used clone method,but do not provide a good clone behaviour.
