### ISSUE TITLE
nacos1.2.1运行一段时间后（单机模式）服务无法访问

### ISSUE THREAD

**Issue by jguangyou** [alibaba/nacos#3438]
After the nacos1.2.1（standalone mode） has been running  for some time（about 2 hours），some service can't be accessed，the program throw the exeption：“nacos No provider available from registry localhost:9090”，if you restart the nacos
,all service will be ok。（spring cloud alibaba2.1.2+dubbo2.7.6+nacos1.2.1）

**Comment by KomachiSion** [comment]
Have any error information or system information? It can't reproduce in my env. we can't get what's problem cause your issue.

**Comment by jguangyou** [comment]
The key problem is that I haven't found any error log in all log files，but the client will report the error “failed to req API:/api//nacos/v1/ns/service/list after all servers([x.y.z.z:8848]) tried: java.net.SocketT                                                                              imeoutException: Read timed out” , meanwhile, the web console can't be accessed

**Comment by KomachiSion** [comment]
see logs/nacos_gc.log check whether has full gc.

**Comment by jguangyou** [comment]
> see logs/nacos_gc.log check whether has full 

it has no full gc，I think the jvm config has no problem too，please help me！！I cant find the problem，I have no choice

> Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 1073741824 (1024.0MB)
   NewSize                  = 536870912 (512.0MB)
   MaxNewSize               = 536870912 (512.0MB)
   OldSize                  = 536870912 (512.0MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 488636416 (466.0MB)
   used     = 329564824 (314.2975082397461MB)
   free     = 159071592 (151.7024917602539MB)
   67.44581721882963% used
From Space:
   capacity = 24117248 (23.0MB)
   used     = 4530368 (4.32049560546875MB)
   free     = 19586880 (18.67950439453125MB)
   18.784763502038043% used
To Space:
   capacity = 23068672 (22.0MB)
   used     = 0 (0.0MB)
   free     = 23068672 (22.0MB)
   0.0% used
PS Old Generation
   capacity = 536870912 (512.0MB)
   used     = 118201376 (112.72561645507812MB)
   free     = 418669536 (399.2743835449219MB)
   22.016721963882446% used

**Comment by KomachiSion** [comment]
but i can't reproduce your problem, our demo console is running in standalone mode, and still work. No problem.

You can login the machine or container of nacos server, and curl localhost to have a try.

**Comment by KomachiSion** [comment]
No more information from author, and we can reproduce problem. So close issue
