### ISSUE TITLE
配置pageSize列表

### ISSUE THREAD

**Issue by rcfeng** [alibaba/nacos#3439]
### Describe what happened (or what feature you want)

目前config默认的pageSize显示10个太少了,
建议pageSize可在nacos server配置文件中进行数组配置,
![image](https://user-images.githubusercontent.com/39292626/88380202-b1ecc100-cdd6-11ea-85a1-fd85032cf35b.png)

### Tell us your environment
1.3.1

**Comment by KomachiSion** [comment]
这块是控制台页面控制的， server配置文件中控制不了。

**Comment by rcfeng** [comment]
> 这块是控制台页面控制的， server配置文件中控制不了。

是我表达的问题, server端就是指console

**Comment by zongtanghu** [comment]
@wangweizZZ  can you resolve this issue?

**Comment by wangweizZZ** [comment]
> @wangweizZZ can you resolve this issue?

前端相关 
 - https://github.com/alibaba/nacos/blob/develop/console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js#L87    
 - https://github.com/alibaba/nacos/blob/develop/console/src/main/resources/static/console-fe/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js#L1387

**Comment by zzq1314zll** [comment]
@i will solve it@

**Comment by zongtanghu** [comment]
Okay, it's yours. @zzq1314zll

**Comment by KomachiSion** [comment]
Code changed but do not re-compile for console.

**Comment by rcfeng** [comment]
其实我提这个issue的初衷是希望能在application.properties里对这个分页的数值进行配置，我看了一下PR，目前也就是把原来写死的
[10,20,30] 抽取到了GLOBAL_PAGE_SIZE_LIST常量，这只能算是代码优化，并没有实际的功能增强
@KomachiSion @zzq1314zll

**Comment by rcfeng** [comment]
现在默认都是显示10条，我觉得可以让用户按实际使用情况配置默认的大小，而不是每次打开都切换一下大小

因为按照我个人习惯，我会一页展示比较多数据，然后通过ctrl+f 搜索直接定位到具体的配置文件，如果分页数据太小，就搜索不到了

为什么不用nacos提供的查询功能呢？ 
1.需要鼠标点到输入框
2.模糊查询还需要使用*通配符
