### ISSUE TITLE
如何修改源码使其支持PostgreSql？

### ISSUE THREAD

**Issue by CNWangTy** [alibaba/nacos#3441]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by CNWangTy** [comment]
简单修改了一下源码已经能根据配置文件连接postgresql，还没有详细测试，下周工作日上传一下代码，nacos版本 1.1.4

**Comment by KomachiSion** [comment]
#9499  #8803

**Comment by dylan-tao** [comment]
目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb
