### ISSUE TITLE
nacos-sprintboot，发布和application.properties相同的配置项，读取到的是application.properties里面的值

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#3444]
nacos1.3.1中，和sprintboot集成后，application.properties中有一配置如：
test.default=123

在nacos上更新相应配置，为
test.default=456

在controller层进行展示，显示的信息还是test.default=123

如果定义了一个配置在application.properties中是不存在的，如
test.defaultnotexists=123
进行发布，则可以正常更新显示

请问下，这个和优先级设置有关吗，在代码里好像找不到sprintboot 和 nacos 相关文件优先级的设置

**Comment by chuntaojun** [comment]
贴一下依赖

**Comment by FengJinghHua** [comment]
@chuntaojun 感谢回复， pox.xml依赖如下
        
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

**Comment by chuntaojun** [comment]
建议去看下这个项目的github的wiki，以及了解spring environment 的设计机制，没有启用remote-first，就是本地的优先
