### ISSUE TITLE
For the remote nacos

### ISSUE THREAD

**Issue by xpp666** [alibaba/nacos#3446]
For the remote nacos I configured, I can see the service registration from the service list of the console, but my local development environment keeps reporting the error "[NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err: Connection refused: connect ", but it doesn't affect the use. Why does it always show that the local nacos cannot be connected? I clearly configured other addresses

**Comment by xpp666** [comment]
> For the remote nacos I configured, I can see the service registration from the service list of the console, but my local development environment keeps reporting the error "[NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err: Connection refused: connect ", but it doesn't affect the use. Why does it always show that the local nacos cannot be connected? I clearly configured other addresses

我是用springcloud alibaba

**Comment by KomachiSion** [comment]
@xpp666 Please change the title so that it can be search friendly.

And Please provide more information, like full error log, nacos version and spring cloud version.
And provide the steps to reproduce. Providing the demo codes will be better.

**Comment by KomachiSion** [comment]
No more response and change more than ** 7 days **, close issue.
