### ISSUE TITLE
Communication between Nacos and docker

### ISSUE THREAD

**Issue by heppytt** [alibaba/nacos#3447]
我使用的场景如下
两台独立的docker服务器，一台docker里面运行nacos服务和项目基础模块，另外一台docker里面运行的项目其他功能模块，问题来了，我在同一台docker容器里面运行项目所有的功能模块注册到nacos里面可以互相访问，项目不报错，可是当我把其中一个模块装到另外一个docker服务器里面并注册到nacos里面时候，项目就访问不到我在另外一台docker服务器里面的服务了。请问是什么原因导致的啊？是我docker原因还是nacos原因？或者我应该如何配置naocs的信息，让这两台docker服务器的应用互相访问？
我使用的场景如下
两台独立的docker服务器，一台docker里面运行nacos服务和项目基础模块，另外一台docker里面运行的项目其他功能模块，问题来了，我在同一台docker容器里面运行项目所有的功能模块注册到nacos里面可以互相访问，项目不报错，可是当我把其中一个模块装到另外一个docker服务器里面并注册到nacos里面时候，项目就访问不到我在另外一台docker服务器里面的服务了。请问是什么原因导致的啊？是我docker原因还是nacos原因？或者我应该如何配置naocs的信息，让这两台docker服务器的应用互相访问？
The scenarios I use are as follows

There are two independent docker servers. One docker runs the Nacos service and project basic module, and the other docker runs other project function modules. The problem is that I run the project in the same docker container. All the functional modules are registered in the Nacos and can be accessed with each other. The project does not report errors. However, when I install one module into another docker, I can access each other When the server is registered with Nacos, the project will not be able to access my services in another docker server. What is the cause? Is it my docker or Nacos? Or how can I configure the information of naocs to make these two dockers

**Comment by KomachiSion** [comment]
I think it's docker usage problem. Because if you deploy all in one it can work. So it is not nacos‘ problem. Please turn to docker community to discuss. I close this issue.
