### ISSUE TITLE
nacosConfig与eureka 使用的时候  服务被自动STARTING

### ISSUE THREAD

**Issue by dyg4228** [alibaba/nacos#345]
nacosConfig与eureka 同时使用的时候  服务会被自动STARTING。

**Comment by shook2012** [comment]
确实这样的问题。

1	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
2	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][ERROR] CacheData$1.run(196): [fixed-config.xxxx.com_8848] [notify-error] dataId=****-web-stgb.properties, group=DEFAULT_GROUP, md5=60b9c558bca7834e7e9fdcd277eb42f4, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@30c8c25e tx=null
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
3	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] EurekaServiceRegistry.deregister(64): Unregistering application ****-web with eureka with status DOWN
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
4	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] DiscoveryClient.unregister(893): Unregistering ...
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
5	19/06/03 19:22:35.000	
[[] 06-03 19:22:35][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
6	19/06/03 19:22:35.000	
[[] 06-03 19:22:35][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][ERROR] CacheData$1.run(196): [fixed-config.xxxx.com_8848] [notify-error] dataId=****-web-stgb.properties, group=DEFAULT_GROUP, md5=60b9c558bca7834e7e9fdcd277eb42f4, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@30c8c25e tx=null
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
7	19/06/03 19:22:35.000	
[[] 06-03 19:22:35][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] EurekaServiceRegistry.deregister(64): Unregistering application ****-web with eureka with status DOWN
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
8	19/06/03 19:22:34.000	
[[] 06-03 19:22:34][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] DiscoveryClient.unregister(893): Unregistering ...
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
9	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
10	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][ERROR] CacheData$1.run(196): [fixed-config.xxxx.com_8848] [notify-error] dataId=****-web-stgb.properties, group=DEFAULT_GROUP, md5=60b9c558bca7834e7e9fdcd277eb42f4, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@30c8c25e tx=null
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
11	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] EurekaServiceRegistry.deregister(64): Unregistering application ****-web with eureka with status DOWN
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
12	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] DiscoveryClient.unregister(893): Unregistering ...
host = 1-225.txxy.aly.sa source = /data/www/logs/****-web.log sourcetype = txxy_yfb_log
13	19/06/03 19:21:33.000	
[[] 06-03 19:21:33][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...

**Comment by shook2012** [comment]
1	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
2	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][ERROR] CacheData$1.run(196): [fixed-config.xxxx.com_8848] [notify-error] dataId=****-web-stgb.properties, group=DEFAULT_GROUP, md5=60b9c558bca7834e7e9fdcd277eb42f4, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@30c8c25e tx=null
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
3	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] EurekaServiceRegistry.deregister(64): Unregistering application ****-web with eureka with status DOWN
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
4	19/06/03 19:23:05.000	
[[] 06-03 19:23:05][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] DiscoveryClient.unregister(893): Unregistering ...
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
5	19/06/03 19:22:35.000	
[[] 06-03 19:22:35][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
6	19/06/03 19:22:35.000	
[[] 06-03 19:22:35][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][ERROR] CacheData$1.run(196): [fixed-config.xxxx.com_8848] [notify-error] dataId=****-web-stgb.properties, group=DEFAULT_GROUP, md5=60b9c558bca7834e7e9fdcd277eb42f4, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@30c8c25e tx=null
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
7	19/06/03 19:22:35.000	
[[] 06-03 19:22:35][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] EurekaServiceRegistry.deregister(64): Unregistering application ****-web with eureka with status DOWN
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
8	19/06/03 19:22:34.000	
[[] 06-03 19:22:34][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] DiscoveryClient.unregister(893): Unregistering ...
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
9	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
10	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][ERROR] CacheData$1.run(196): [fixed-config.xxxx.com_8848] [notify-error] dataId=****-web-stgb.properties, group=DEFAULT_GROUP, md5=60b9c558bca7834e7e9fdcd277eb42f4, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@30c8c25e tx=null
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
11	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] EurekaServiceRegistry.deregister(64): Unregistering application ****-web with eureka with status DOWN
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
12	19/06/03 19:22:04.000	
[[] 06-03 19:22:04][com.alibaba.nacos.client.Worker.longPollingfixed-config.xxxx.com_8848][INFO] DiscoveryClient.unregister(893): Unregistering ...
host = 1-225.test.aly.sa source = /data/www/logs/****-web.log sourcetype = test_yfb_log
13	19/06/03 19:21:33.000	
[[] 06-03 19:21:33][DiscoveryClient-InstanceInfoReplicator-0][INFO] DiscoveryClient.register(804): DiscoveryClient_****-WEB/10.6.1.225:8012: registering service...

**Comment by shook2012** [comment]
确实有这样的问题。eureka会一直regist,unregist

**Comment by hao0111** [comment]
请问这个问题修复了吗？在nacos1.1.4上出现的概率比1.1.0高太多了，配置文件更新后，eureka client的服务节点publish 2次refreshEvent事件，服务节点状态，ncaos的线程startging->down->up，discoveryClient-instanceReplicate线程，状态up->down，造成上报状态错误
