### ISSUE TITLE
Problems encountered when using multiple nacos cofig

### ISSUE THREAD

**Issue by J-TIGGER** [alibaba/nacos#3450]
When nacos conifg is in use, can A-nacos-config.yaml directly call B-naocs-config.xml, I have tried various methods and failed to succeed, I can only put B-naocs-config.xml in the resource of the local application It succeeds under the directory, if it can support direct calling, it would be great!

**Comment by KomachiSion** [comment]
What's the A and B means?

**Comment by J-TIGGER** [comment]
A与B分别代表两个不同的配置文件
