### ISSUE TITLE
在使用nacos config时遇到了一个嵌套调用的问题

### ISSUE THREAD

**Issue by J-TIGGER** [alibaba/nacos#3451]
在nacos-config配置中我是这样写的：
logging: 
  config: classpath: logback-spring.xml
  file: ${logging.path}//${spring.application.name}/monitor.log  
  path: F://logs//
 其中我想将logback-spring.xml也放到nacos-config中，但是这里使用了classpath之后怎么也不能成功，只能将logback-spring.xml放到本地应用的resouce文件夹下面，有没有好的方法将logback-spring.xml放到nacos-config中做统一调用

**Comment by zongtanghu** [comment]
@wangweizZZ Can you resolve this issue?
