### ISSUE TITLE
nacos的使用文档有问题

### ISSUE THREAD

**Issue by chenjun-1201** [alibaba/nacos#3453]
https://nacos.io/en-us/docs/quick-start.html

在这个标题下Download source code from Github ##
`s://github.com/alibaba/nacos.git
cd nacos/
mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U 
ls -al distribution/target/

// change the $version to your actual path
cd distribution/target/nacos-server-$version/nacos/bi`

最后少加了一个n

**Comment by Xunzhuo** [comment]
@i will solve it@
