### ISSUE TITLE
使用 Nacos 作为 Dubbo 注册中心，控制台服务表关于Consumer的行信息缺失

### ISSUE THREAD

**Issue by liteng-xxyl** [alibaba/nacos#3454]
**Nacos版本：1.3.1
Dubbo版本：2.7.4.1**

**1. Bug描述**
![consumer](https://user-images.githubusercontent.com/44028859/88516601-21092600-d020-11ea-8045-979f5090592c.png)

**2. 个人愚见**
这也不算Bug吧，但是对于强迫症的我来说就很别扭。另外，总觉得Nacos关于Dubbo提供者和消费者的信息展示不是很一目了然。其实大多数开发者或项目管理者就是想知道Dubbo发布了那些服务，然后发布者是谁，消费者是谁。因此，我觉得以具体的服务（比如上图中的TestService）为驱动，再带出提供者和消费者可能会比较清晰一点。

或许是因为服务列表融合了作为服务发现管理注册进来的服务实例和作为Dubbo注册中心注册进来的Dubbo服务实例，所以Dubbo相关服务的信息展示就被“同化”了。这也是我觉得混乱的另一个地方，我拿一个我们项目注册的服务列表看一下：

![image](https://user-images.githubusercontent.com/44028859/88518112-82ca8f80-d022-11ea-9002-faa71887d520.png)

可以看到，作为服务发现注册的服务实例信息与作为Dubbo注册中心的Dubbo服务实例信息杂乱在一起，想找某个Duboo服务，该服务有谁提供，被谁调用就比较麻烦。当然这个我可以通过使用不同的命名空间来解决，但是将两者从逻辑上分来是不是更好一点。比如，加一个Dubbo服务列表，列表项如下：

![DubboList](https://user-images.githubusercontent.com/44028859/88518858-c1147e80-d023-11ea-8d8e-2ea14ad6705e.png)

**Comment by zzq1314zll** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
从社区最新反馈来看， 这个需求其实不是很合理。

Nacos应该为注册中心，展示的是服务和实例对应的信息，Dubbo应用对应注册了哪些服务，订阅了哪些服务，谁调用之类的其实是Dubbo的RPC测信息， 注册中心不应该为RPC定制特殊概念需求， 这个需求其实应该在dubbo-admin中实现dubbo的对应管理服务。

服务治理功能Nacos也会向着XDS等通用标准方案来实现。如果有针对Dubbo做的功能，也会以插件形式实现，不应该耦合在注册中心主干链路中。
