### ISSUE TITLE
nacos1.2.1 use 'nacos.core.auth.enabled=true' ，The Nacos client cannot dynamically refresh the configuration

### ISSUE THREAD

**Issue by GitHub42096** [alibaba/nacos#3457]
**Describe the bug**

I use nacos1.2.1 ,make property which is 'nacos.core.auth.enabled' with true, And I  use nacos client to connet my nacos server, I operate the configuration interface，But nacos client can't receive The new configuration and the value of the Java configuration bean was not updated 

使用1.2.1的nacos版本， 将该配置nacos.core.auth.enabled开启，客户端报403，覆盖源码中的ClientWorker类，去在连接的时候传入用户名、密码后，能正常启动。但是我操作nacos的管理界面，修改了配置的值，我的客户端并没有更新配置，我把nacos.core.auth.enabled=false，能正常使用

**Comment by KomachiSion** [comment]
If modified source codes and caused problem, we can't help you, because we do not how you changed.

For the first question, I recommend you used new issue temporary to describe. Which will help other find out the problem.

**Comment by GitHub42096** [comment]
> 如果修改了源代码并导致了问题，我们将为您提供帮助，因为我们没有改变您的方式。
> 
> 对于第一个问题，建议您使用临时的新问题来描述。这将帮助其他人找出问题所在。

![image](https://user-images.githubusercontent.com/34017916/88746347-ebc71a00-d17e-11ea-9eb7-5e9cb1097dd3.png)

源码我只加入了一行代码，只是为了跳过403无权限，因为你们现在不支持传入username和password，其他并没有修改过。

**Comment by KomachiSion** [comment]
@GitHub42096 see article to learn how to add username password 
https://nacos.io/en-us/blog/nacos%201.2.0%20guide.html
