### ISSUE TITLE
1.3.1客户端不能创建命名空间

### ISSUE THREAD

**Issue by ToujoursTeam** [alibaba/nacos#3462]
Request URL: http://127.0.0.1:8848/nacos/v1/console/namespaces

exception:
caused: Required String parameter 'customNamespaceId' is not present;

但是1.1.4客户端可以正常创建

**Comment by KomachiSion** [comment]
I test in nacos demo console, It can work. Maybe you need to clean the browser's cache, because `customNamespaceId` is added in 1.2, If your js file is old cached, will casue this problem.

**Comment by ToujoursTeam** [comment]
> I test in nacos demo console, It can work. Maybe you need to clean the browser's cache, because `customNamespaceId` is added in 1.2, If your js file is old cached, will casue this problem.
thank! I cleaned up the browser cache and now it works
