### ISSUE TITLE
nacos 1.1.4版本grafana 监控qps值，每过一段时间突然彪高

### ISSUE THREAD

**Issue by binke-wang** [alibaba/nacos#3464]
![1595937968(1)](https://user-images.githubusercontent.com/68905977/88663212-cb12ac00-d10d-11ea-8fb4-499ec4d65eb3.jpg)

![image](https://user-images.githubusercontent.com/68905977/88663924-e16d3780-d10e-11ea-8986-c721f3d0271a.png)
![image](https://user-images.githubusercontent.com/68905977/88663953-ea5e0900-d10e-11ea-9e20-584ce9c8f683.png)
![image](https://user-images.githubusercontent.com/68905977/88663967-ef22bd00-d10e-11ea-8c71-6eced8b59db7.png)

![image](https://user-images.githubusercontent.com/68905977/88673424-2d25de00-d11b-11ea-9db2-6f26556c5e6b.png)

**// 部署的是集群，主要是这个时间点没有去修改配置文件**
  我们在nacos 前面加了一层Nginx 访问的数据跟统计结果是有误差的

问题：
        1：上面的算法是每秒的统计吗。
        2：上面这样正常吗？

**Comment by KomachiSion** [comment]
这个飙高值似乎很不正常，可以尝试去掉rate算子，看一下原始数据是不是那时候的确有极大的变化。有可能是promethus算子的问题。

**Comment by KomachiSion** [comment]
如果打开了accesslog， 可以去日志里核对一下，当时是不是的确有那么多的请求。如果没有打开，建议打开一下，然后排查下。

**Comment by binke-wang** [comment]
原因已找到：
           我们监控的节点不是单个实例，改成监控集群单个实例看着就正常了，跟Nginx也对得上。
