### ISSUE TITLE
Nacos 1.2.1 版本.几个问题汇总

### ISSUE THREAD

**Issue by yyt6200** [alibaba/nacos#3465]
Nacos环境：110节点 111节点 112节点 三台虚拟机组成集群
服务运行环境：Swarm集群
-----------------------------------------------------------------------------------------------------------------------------------------
问题1：
Swarm中已经退出的实例，在Nacos后台上仍然在线。见图1
![节点错误](https://user-images.githubusercontent.com/44914868/88747249-f97d9f00-d180-11ea-9964-ff8e8a281fac.png)
这边有个情况需要说明，110节点的Nacos此时不在集群的节点列表中，可见图2。奇怪的问题就是，110这个节点在服务器上看运行状态还是**Active（Running）**的，但在集群列表中已经没有110这个节点了。
![1111](https://user-images.githubusercontent.com/44914868/88748466-abb66600-d183-11ea-81e7-e32fd5a4a1d2.jpg)
-----------------------------------------------------------------------------------------------------------------------------------------
问题2：
110节点在服务器上查看运行状态是**Active（Running）**，但是不在集群列表中，直接访问110后台地址也不能访问。见图3。
![nacos1](https://user-images.githubusercontent.com/44914868/88747854-37c78e00-d182-11ea-92bd-e145a75c6a75.png)
可以确定的是，不存在网络问题。Swarm与Nacos集群的网络是畅通的。
问题3：
上面阐述的两个问题，在我将110的Nacos重启后（Systemctl restart nacos.service），问题1和问题2的情况都消失了。该下线的服务下线了，集群列表也出现110节点了。
-----------------------------------------------------------------------------------------------------------------------------------------

**希望项目组的大佬们重视下我反馈的这几个问题，不是第一次发生了，前后我也提交了好几次Issues了。如果这种情况上生产就是灾难**

**Comment by horizonzy** [comment]
@chuntaojun 春少看看呢

**Comment by KomachiSion** [comment]
之前的issue已经回复过多次了，您提供的这些信息都是现象问题，我们复现不了，如果需要排查，复现时到naming-server等日志中， 查看信息，并把信息贴出来。否则没人能分析。

另外Swarm集群和nacos是无关的，对nacos而言就是机器环境，如果是swarm集群导致的环境问题，我们复现不出来就很正常了

**Comment by yyt6200** [comment]
目前的情况来看不太像是Swarm那边的问题，是Nacos节点不正常工作导致的。每次服务不及时下线都有Nacos节点不正常工作的现象存在。下面我贴下日志信息，麻烦大佬帮忙分析下

**Comment by yyt6200** [comment]
[naming-server.log](https://github.com/alibaba/nacos/files/4992357/naming-server.log)
这个是110节点的nameing-server.log文件。我是在27号发现又有服务未下线的，但是110的日志只输出到24号。

**Comment by yyt6200** [comment]
[naming-server.log](https://github.com/alibaba/nacos/files/4992366/naming-server.log)
这个是111节点的nameing-server.log文件。里面输出的是27日的日志信息。

**Comment by yyt6200** [comment]
发生这次问题的主要原因还是110节点挂了，但在110服务器上查看Nacos的运行状态还是running状态。
110节点重启后，所有问题都消失了。还需要哪些日志分析麻烦大佬再讲下，我这边尽量提供

**Comment by KomachiSion** [comment]
110节点24可能已经出现异常
查一下111节点在24日是否有把110节点从健康实例中移除

**Comment by KomachiSion** [comment]
另外110节点是进程没了吗？111节点调用110的请求我看都是拒绝连接

**Comment by yyt6200** [comment]
---》查一下111节点在24日是否有把110节点从健康实例中移除

应该查看哪个日志文件？

110节点进程在的，您看一楼的图2 服务还是running的

**Comment by KomachiSion** [comment]
从图上看，这个节点已经被移除了，虽然在运行（我没有这么启动过，不知道是否确实可行）

日志文件naming-server.log

**Comment by KomachiSion** [comment]
> 从图上看，这个节点已经被移除了，虽然在运行（我没有这么启动过，不知道是否确实可行）
> 
> 日志文件naming-server.log

建议查看一下进程是否存在，不要通过这种服务查询来看，以及本地机器curl一下试试 是不是真的以及无法提供服务了

**Comment by yyt6200** [comment]
> > 从图上看，这个节点已经被移除了，虽然在运行（我没有这么启动过，不知道是否确实可行）
> > 日志文件naming-server.log
> 
> 建议查看一下进程是否存在，不要通过这种服务查询来看，以及本地机器curl一下试试 是不是真的以及无法提供服务了

这个已经无法求证了，只能在下次发生问题的时候再次验证。下面我贴下111节点24号的日志，麻烦大佬帮忙分析下，日志里有对110节点time out的日志的。

[naming-server.2020-07-24.0.log](https://github.com/alibaba/nacos/files/4999094/naming-server.2020-07-24.0.log)

最后我还是想要强调下，不管110节点是否假死，进程是否在。在110节点手动重启后，一切都恢复正常了。
1：已经退出的服务实例下线了 
2：110节点后台可以访问了，集群里也出现了110节点。

**Comment by yyt6200** [comment]
@KomachiSion 大佬 麻烦再帮忙分析下呢

**Comment by KomachiSion** [comment]
从日志来看，3台节点都非常不稳定，不停地在进行健康服务的变更， 最后甚至出现了111自己都把自己摘除了。

这里给出几种假设，需要您自己去验证一下：
1. JVM参数过低，导致几个节点不停在gc，从而导致请求不稳定，不停的在摘除，添加。
2. 网络非常不稳定，断断续续。

**Comment by yyt6200** [comment]
您说的《不停地在进行健康服务的变更》，是注册到Nacos上的服务吗？如果是的话，这个正常的，这是我们这边的开发环境，每次提交代码到dev后，都会触发jenkins的自动构建发布，这时候就会导致服务注销重新注册了。
JVM参数我在下面贴下，麻烦大佬看下是否合理。
# JVM Configuration
#===========================================================================================
if [[ "${MODE}" == "standalone" ]]; then
    JAVA_OPT="${JAVA_OPT} -Xms512m -Xmx512m -Xmn256m"
    JAVA_OPT="${JAVA_OPT} -Dnacos.standalone=true"
else
    JAVA_OPT="${JAVA_OPT} -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m"
    JAVA_OPT="${JAVA_OPT} -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${BASE_DIR}/logs/java_heapdump.hprof"
    JAVA_OPT="${JAVA_OPT} -XX:-UseLargePages"

fi

if [[ "${FUNCTION_MODE}" == "config" ]]; then
    JAVA_OPT="${JAVA_OPT} -Dnacos.functionMode=config"
elif [[ "${FUNCTION_MODE}" == "naming" ]]; then
    JAVA_OPT="${JAVA_OPT} -Dnacos.functionMode=naming"
fi


JAVA_MAJOR_VERSION=$($JAVA -version 2>&1 | sed -E -n 's/.* version "([0-9]*).*$/\1/p')
if [[ "$JAVA_MAJOR_VERSION" -ge "9" ]] ; then
  JAVA_OPT="${JAVA_OPT} -Xlog:gc*:file=${BASE_DIR}/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400"
else
  JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"
  JAVA_OPT="${JAVA_OPT} -Xloggc:${BASE_DIR}/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M"
fi

JAVA_OPT="${JAVA_OPT} -Dloader.path=${BASE_DIR}/plugins/health,${BASE_DIR}/plugins/cmdb,${BASE_DIR}/plugins/mysql"
JAVA_OPT="${JAVA_OPT} -Dnacos.home=${BASE_DIR}"
JAVA_OPT="${JAVA_OPT} -jar ${BASE_DIR}/target/${SERVER}.jar"
JAVA_OPT="${JAVA_OPT} ${JAVA_OPT_EXT}"
JAVA_OPT="${JAVA_OPT} --spring.config.location=${CUSTOM_SEARCH_LOCATIONS}"
JAVA_OPT="${JAVA_OPT} --logging.config=${BASE_DIR}/conf/nacos-logback.xml"
JAVA_OPT="${JAVA_OPT} --server.max-http-header-size=524288"

if [ ! -d "${BASE_DIR}/logs" ]; then
  mkdir ${BASE_DIR}/logs
fi

echo "$JAVA ${JAVA_OPT}"

if [[ "${MODE}" == "standalone" ]]; then
    echo "nacos is starting with standalone"
else
    echo "nacos is starting with cluster"
fi

# check the start.out log output file
if [ ! -f "${BASE_DIR}/logs/start.out" ]; then
  touch "${BASE_DIR}/logs/start.out"
fi
# start
echo "$JAVA ${JAVA_OPT}" > ${BASE_DIR}/logs/start.out 2>&1 &
nohup $JAVA ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
echo "nacos is starting，you can check the ${BASE_DIR}/logs/start.out"

**Comment by KomachiSion** [comment]
> 您说的《不停地在进行健康服务的变更》，是注册到Nacos上的服务吗？如果是的话，这个正常的，这是我们这边的开发环境，每次提交代码到dev后，都会触发jenkins的自动构建发布，这时候就会导致服务注销重新注册了。

不是，是nacos 服务节点一直在健康和非健康之间变化。

**Comment by KomachiSion** [comment]
关于JVM，可以直接看一下nacos/logs/nacos_gcxxx.log，进去看是否存在大量Full GC和CMS GC。 如果是的话，那应该就是jvm的问题了

**Comment by yyt6200** [comment]
麻烦您帮忙看下110和111的日志文件，拷贝日期是27号（发现问题的时候，周一）
您说的Full GC和CMS GC我似乎没看到呢
[111-nacos_gc.log](https://github.com/alibaba/nacos/files/5019630/111-nacos_gc.log)
[110-nacos_gc.log](https://github.com/alibaba/nacos/files/5019629/110-nacos_gc.log)

**Comment by KomachiSion** [comment]
看24日的gc日志，所有的，因为从以前的日志看，实际出问题在24日下午

**Comment by yyt6200** [comment]
gc的日志都是在一块的...节点的logs文件夹内只有 **nacos_gc.log.0.current** 这个名称的文件。

**Comment by KomachiSion** [comment]
110的gc日志太过异常了，应该是24日16:45:07 被重启了，之后一直没有请求进入（从其他的日志看，这个时间点被集群摘除了，所以的确么有流量），我觉得可以排查下docker在24日的这个时间点是否有哪些自动操作了，因为这个gc日志在启动的时候会被清理。

**Comment by KomachiSion** [comment]
为了验证，也可以看下110上的nacos.log 和 start.out 看下这个时间点是不是真的被重启了

**Comment by yyt6200** [comment]
[start.out.log](https://github.com/alibaba/nacos/files/5032945/start.out.log)
[naocs-1.log](https://github.com/alibaba/nacos/files/5032965/naocs-1.log)
[naocs-2.log](https://github.com/alibaba/nacos/files/5032966/naocs-2.log)
[naocs-3.log](https://github.com/alibaba/nacos/files/5032967/naocs-3.log)
日志里面好像是数据库链接不上，一直在报错。Nacos.log比较大，我拆成三份了。请大牛帮忙分析下，里面怎么有这么多的日志信息？

**Comment by KomachiSion** [comment]
日志确实显示2020-07-24 16:42:40,204被110被关闭了，之后应该是被docker自动拉起，但是拉起之后一直无法获取数据库连接，导致一直无法对外提供服务。可以查看下是不是新拉起的容器和数据库之间是不是有什么障碍，因为重启之后的日志一直报的是连接超时或拒绝连接，而且异常是由mysql驱动报出来的。

这些问题其实你把所有的日志都check一下就直接能获得的，issue这来来回回是在太花时间了。

**Comment by KomachiSion** [comment]
From the log shows, the server is stopped and restart. But after restart, it can't connect to database mysql. So it can't provide service. It's a env problem. Not nacos' problem

And no more response from author. So close issue.
