### ISSUE TITLE
调用OpenApi下线服务实例偶尔不成功

### ISSUE THREAD

**Issue by bxxfighting** [alibaba/nacos#3466]
**调用OpenApi下线服务实例未成功**
我通过ansible部署java程序时，先调用了nacos的下线服务实例接口，
然后再调用当前服务实例列表接口判断对应服务实例是否下线。
有时候会出现，下线接口通过后，再调用服务实例列表时，这个服务器还在列表中，并且enabled=true
这个现象一共遇到过两次。

备注：所有接口调用都有不成功重试功能，两秒一次，重度60次。

下线接口示例：
接口：/nacos/v1/ns/instance
参数：enabled=false
返回值判断：http状态码为200，并且返回内容中包含ok。

列表接口示例：
接口：/nacos/v1/ns/instance/list
参数：
返回值判断：http状态码为200，并且判断当前服务器IP及端口号

**Comment by bxxfighting** [comment]
使用nacos版本：1.1.3

**Comment by KomachiSion** [comment]
出现的时候，查下日志，是否这个instance确实做了变动，并且同步到所有节点了。
日志应该在naming-server、naming-distro中

**Comment by bxxfighting** [comment]
> 出现的时候，查下日志，是否这个instance确实做了变动，并且同步到所有节点了。
> 日志应该在naming-server、naming-distro中

我同时发布80台机器，每一台机器都会根据自己的IP去调用下线的接口，只有一台IP为x.x.x.104的机器没有下线成功。
我这里是三台机器组成的集群，三台上我都查看了，naming-server.log中，确实没有那台服务器enabled:false的同步记录。其它机器都是有的。

**Comment by KomachiSion** [comment]
> > 出现的时候，查下日志，是否这个instance确实做了变动，并且同步到所有节点了。
> > 日志应该在naming-server、naming-distro中
> 
> 我同时发布80台机器，每一台机器都会根据自己的IP去调用下线的接口，只有一台IP为x.x.x.104的机器没有下线成功。
> 我这里是三台机器组成的集群，三台上我都查看了，naming-server.log中，确实没有那台服务器enabled:false的同步记录。其它机器都是有的。

有打开access_log吗？ 打开的话检索一下，看下是否nacos有收到这个机器下线的请求

**Comment by bxxfighting** [comment]
> > > 出现的时候，查下日志，是否这个instance确实做了变动，并且同步到所有节点了。
> > > 日志应该在naming-server、naming-distro中
> > 
> > 
> > 我同时发布80台机器，每一台机器都会根据自己的IP去调用下线的接口，只有一台IP为x.x.x.104的机器没有下线成功。
> > 我这里是三台机器组成的集群，三台上我都查看了，naming-server.log中，确实没有那台服务器enabled:false的同步记录。其它机器都是有的。
> 
> 有打开access_log吗？ 打开的话检索一下，看下是否nacos有收到这个机器下线的请求

我看了一下，运维在配置的时候，没有打开这个日志，所以看不到记录。
但是我感觉这个应该可以排除，因为在调用下线接口时，是对返回值进行了判断的。
只有http状态码是200，并且返回内容中有ok的情况下，才算是请求成功，否则就会重复调用多次

**Comment by KomachiSion** [comment]
那可能是同步的问题了。而且要在高并发的场景下才会出现，我先标记一下。

**Comment by Maijh97** [comment]
@bxxfighting 这个问题在新的版本已经修复，麻烦更新版本。
