### ISSUE TITLE
Nacos 配置文件支持加密表达式

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/nacos#347]
Nacos 控制台配置中心需要添加对某些字段加密的功能；或者提供加密表达式，至少在查看的时候，加密字段以****代替，需要输入密码才能查看；

这个需要出一个解决方案，现在是完全透明的展示。

**Comment by mtdp** [comment]
这个问题有方案么？issues 关闭了？

**Comment by gumutianqi** [comment]
这个问题会在1.0.0GA版本之前有计划么

**Comment by mylove13289** [comment]
可以参考这个方案：https://blog.csdn.net/qq_40354025/article/details/78269284
