### ISSUE TITLE
the service checksum  change frequently although all instances of the service have not changed healthy with heartbeat  normal work.

### ISSUE THREAD

**Issue by meiliangdeng** [alibaba/nacos#3471]
**Describe the bug**
the service checksum change frequently although all instances of the service have not changed healthy with heartbeat normal work.
The following example is the information comparison of two change instances(instance info not change but the checksum value have change：'499925ce37e7aa744c154540072d8b27' to 'b96526021f21e2363ab2ee152f4b2d55'):

```
{"metadata":{},"dom":"mall-lgs-service","cacheMillis":3000,"useSpecifiedURL":false,"hosts":[{"valid":true,"marked":false,"metadata":{"nacosEnv":"grey","env":"pro"},"instanceId":"10.202.14.23#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.23","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.25#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.25","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.24#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.24","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true}],"name":"DEFAULT_GROUP@@mall-lgs-service","checksum":"499925ce37e7aa744c154540072d8b27","lastRefTime":1595969064691,"env":"","clusters":""}

{"metadata":{},"dom":"mall-lgs-service","cacheMillis":3000,"useSpecifiedURL":false,"hosts":[{"valid":true,"marked":false,"metadata":{"nacosEnv":"grey","env":"pro"},"instanceId":"10.202.14.23#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.23","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.25#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.25","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.24#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.24","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true}],"name":"DEFAULT_GROUP@@mall-lgs-service","checksum":"b96526021f21e2363ab2ee152f4b2d55","lastRefTime":1595969069723,"env":"","clusters":""}

```
**Expected behavior**
if the service instance information does not change, it is expected that the checksum value will not be change

**Acutally behavior**
the service checksum change frequently although all instances of the service have not changed healthy with heartbeat normal work.

**How to Reproduce**
It only appears in some services , and there is no clear factor to reproduce it

**Desktop (please complete the following information):**
**OS:** ubuntu 14.10 and mac and windows
**Version:** [nacos-server 1.2.1, self custom php sdk with the Open-Api]
**Module:** [naming feature]
**SDK:** [self custom php sdk with the Open-Api]

**Comment by KomachiSion** [comment]
Please use issue template to describe your problem, otherwise it may be lark some important information.

**Comment by KomachiSion** [comment]
template:



**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by meiliangdeng** [comment]
**Describe the bug**
the service checksum change frequently although all instances of the service have not changed healthy with heartbeat normal work.
The following example is the information comparison of two change instances(instance info not change but the checksum value have change：'499925ce37e7aa744c154540072d8b27' to 'b96526021f21e2363ab2ee152f4b2d55'):

```
{"metadata":{},"dom":"mall-lgs-service","cacheMillis":3000,"useSpecifiedURL":false,"hosts":[{"valid":true,"marked":false,"metadata":{"nacosEnv":"grey","env":"pro"},"instanceId":"10.202.14.23#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.23","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.25#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.25","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.24#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.24","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true}],"name":"DEFAULT_GROUP@@mall-lgs-service","checksum":"499925ce37e7aa744c154540072d8b27","lastRefTime":1595969064691,"env":"","clusters":""}

{"metadata":{},"dom":"mall-lgs-service","cacheMillis":3000,"useSpecifiedURL":false,"hosts":[{"valid":true,"marked":false,"metadata":{"nacosEnv":"grey","env":"pro"},"instanceId":"10.202.14.23#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.23","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.25#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.25","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true},{"valid":true,"marked":false,"metadata":{"nacosEnv":"default","env":"pro"},"instanceId":"10.202.14.24#19588#DEFAULT#DEFAULT_GROUP@@mall-lgs-service","port":19588,"healthy":true,"ip":"10.202.14.24","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"mall-lgs-service","enabled":true}],"name":"DEFAULT_GROUP@@mall-lgs-service","checksum":"b96526021f21e2363ab2ee152f4b2d55","lastRefTime":1595969069723,"env":"","clusters":""}

```
**Expected behavior**
if the service instance information does not change, it is expected that the checksum value will not be change


**Acutally behavior**
the service checksum change frequently although all instances of the service have not changed healthy with heartbeat normal work.

**How to Reproduce**
It only appears in some services , and there is no clear factor to reproduce it

**Desktop (please complete the following information):**
**OS:** ubuntu 14.10  and mac and windows
**Version:** [nacos-server 1.2.1, self custom php sdk with the Open-Api]
**Module:** [naming feature]
**SDK** [self custom php sdk with the Open-Api]
**Additional context**
null
