### ISSUE TITLE
failed to send beat,2.2.1 nacos discovery,Param 'serviceName' is required.;

### ISSUE THREAD

**Issue by SkyXj** [alibaba/nacos#3472]
**Describe the bug**
[CLIENT-BEAT] failed to send beat: {"port":9200,"ip":"192.168.5.63","weight":1.0,"cluster":"DEFAULT","metadata":{"preserved.register.source":"SPRING_CLOUD"},"scheduled":false,"period":5000,"stopped":false}, code: 400, msg: failed to req API:/nacos/v1/ns/instance/beat after all servers([127.0.0.1:8848]) tried: caused: Param 'serviceName' is required.;
日志一直报错，failed to send beat,由于缺少参数,查看源码发现 没有地方给serviceName赋值，导致一直报错。

public void addBeatInfo(String serviceName, BeatInfo beatInfo) {
        NAMING_LOGGER.info("[BEAT] adding beat: {} to beat map.", beatInfo);
        String key = buildKey(serviceName, beatInfo.getIp(), beatInfo.getPort());
        BeatInfo existBeat = null;
        //fix #1733
        if ((existBeat = dom2Beat.remove(key)) != null) {
            existBeat.setStopped(true);
        }
        dom2Beat.put(key, beatInfo);
        executorService.schedule(new BeatTask(beatInfo), beatInfo.getPeriod(), TimeUnit.MILLISECONDS);
        MetricsMonitor.getDom2BeatSizeMonitor().set(dom2Beat.size());
    }
此处beatInfo 一直为空
注册配置中心使用的NACOS1.3.0

**Comment by KomachiSion** [comment]
I check the source code again. nacos discovery 2.2.1 use nacos-client1.2.1 default, and in 1.2.1 client, the beatInfo is init in `NacosNamingService`, and set serviceName into beatinfo in there.

So can you debug and check out why the serviceName is empty?

**Comment by SkyXj** [comment]
Thank you for your answer. In fact, my Nacos client is 1.3.0. When I change it to 1.2.1, the error disappears. But I can't find beattask, so only 1.3.0 has beat monitoring？

**Comment by KomachiSion** [comment]
Can you upgrade to 1.3.1 and retry？

**Comment by KomachiSion** [comment]
Any process？

**Comment by SkyXj** [comment]
it works correctly when i upgrade to 1.3.1,thank you
