### ISSUE TITLE
nacos1.3.1+seata1.2.0+dubbo2.7.6 too many open files

### ISSUE THREAD

**Issue by jguangyou** [alibaba/nacos#3473]
运行一段时间nacos出现” too many open files“错误，查看8848端口，出现超级多的 COLSE-WAIT，占用了太多的端口资源没有释放。这个时候nacos出现了“植物人”情况，除了进程存在，基本没有任何反应。nacos1.2.1也出现这种显现，但是没有报错。

**Comment by KomachiSion** [comment]
能统计一下数量吗？查一下是不是句柄是不是都是连接句柄，还有查一下系统最大句柄数。

**Comment by KomachiSion** [comment]
No response from author, and information is not enough, so close issue.
