### ISSUE TITLE
希望支持多注册中心， 一个服务注册到两个注册中心， 使用的时候也能需要支持多个注册中心的服务发现

### ISSUE THREAD

**Issue by ninyjun** [alibaba/nacos#3474]
希望支持多注册中心， 一个服务注册到两个注册中心， 使用的时候也能需要支持多个注册中心的服务发现
（使用场景是：有的服务需要对其它子系统暴露）

**Comment by chuntaojun** [comment]
请将该问题提至对应的微服务框架，nacos是注册与配置管理中心，不存在支持多注册中心的场景

**Comment by ninyjun** [comment]
dubbo 就支持多注册中心啊
