### ISSUE TITLE
Excuse me, what's the difference between param defaultCheckPort and defCkport ? 

### ISSUE THREAD

**Issue by majianwei0705** [alibaba/nacos#3475]
**Describe the bug**
在web端，我更改了集群配置里面的检查端口，返回了ok，但是再次打开页面的话，端口依旧是80，查看data文件，更改改到了defCkport 参数中，但是web端读取的端口看起来是 defaultCheckPort。请问是否是个bug？ 

**Expected behavior**
是否参数发生过修改，还是我用法有误？ 由于我们的环境非java相关，所以请问，如果是bug，是否会修复这个问题。

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 1.3.1, client: open api]
 - Module [naming/config]
 - SDK [open api]

**Comment by KomachiSion** [comment]
see #3005 , is it the same problem?
