### ISSUE TITLE
如何加入nacos 邮件列表（官方文档指向了如何加入dubbo邮件列表）

### ISSUE THREAD

**Issue by shenmou98** [alibaba/nacos#3477]
官方这里给的链接指向到了如何加入dubbo的邮件列表..（https://nacos.io/zh-cn/docs/community.html ）

**Comment by KomachiSion** [comment]
我点进去确实是nacos的邮件列表啊，你是说邮件列表里的内容是dubbo吗？

```
邮件列表
邮件列表建议讨论任何与Nacos有关的事情。具体请看参考手册描述如何订阅我们的邮件列表。

dev-nacos@googlegroups.com: 开发邮件列表。如果你在使用或开发Nacos中遇到任何问题,可以在这里提问题。
commits-nacos@googlegroups.com: 所有提交将被发送到这个邮件列表。如果你有兴趣Nacos的发展，你可以订阅它。
users-nacos@googlegroups.com: 在Github中提问题、更新和提交需求将被发送到这个邮件列表。
nacos_dev@linux.alibaba.com.
```

**Comment by shenmou98** [comment]
你好， 我说的是“如何加入（订阅）nacos邮件列表”，截图中“参考手册”指向了如何加入 dubbo邮件列表
![image](https://user-images.githubusercontent.com/10502050/88990345-4d6abe00-d310-11ea-8073-4b4df9381afc.png)

**Comment by KomachiSion** [comment]
因为操作步骤是一样的，所以只是个参考手册，只是把邮件地址换一下就行。

**Comment by KomachiSion** [comment]
当然如果您愿意帮我们贡献完整的操作手册我们非常欢迎。
