### ISSUE TITLE
Nacos注册应用的映射关系

### ISSUE THREAD

**Issue by gfgfggf1988** [alibaba/nacos#3482]
想问一下，有以下这样的需求，nacos的服务维护是否可以支持。
存在应用A，希望在服务列表中可以通过API注册成不同名字的服务。如A->B或A->C。
当通过namineService获取应用实例的时候，无论是从B还是C都能映射到真实的A应用上

**Comment by horizonzy** [comment]
能描述的更清楚一点吗。没有理解啥意思

**Comment by KomachiSion** [comment]
I think the mapping of service name should be maintain by apps or users, for nacos you register A, it is just A.

So I don't think it's a reasonable feature
