### ISSUE TITLE
How to enhance auth manager

### ISSUE THREAD

**Issue by fireflyhoo** [alibaba/nacos#3484]
啥时候能把权限管理做好一点啊, 参见阿波罗的配置中心, 感觉现在的配置中心权限控制做得比较差啊, 不能不同的应用配置

**Comment by KomachiSion** [comment]
欢迎共建啊

**Comment by shizhengxing** [comment]
权限控制在试图进行企业级二次开发的时候，让人很郁闷，直接弃用了全部权限控制功能，自己搞了

**Comment by KomachiSion** [comment]
@shizhengxing 欢迎贡献到社区里啊。

**Comment by yanjunnf** [comment]
我这边权限做了一定点定制，首先支持了公司的Ldap方式登录，然后每个用户默认能够看到public，同时只显示该用户有权限的namespace。

**Comment by wangtoye** [comment]
@yanjunnf 哥们，我跟你做了类似的定制，然后客户端还定制了一下，未获取到配置会继续发送一次请求到public下去获取一次。

**Comment by fireflyhoo** [comment]
而且对于某些密码的配置是否也可以支持 配置加密后的字符串. 由客户端解密, 我们当前的方案是使用 jasypt-spring-boot-starter 做客户端来解密

**Comment by fireflyhoo** [comment]
还有配置的审计功能, 谁在什么时候改了什么

**Comment by zzllkk2003** [comment]
> 我这边权限做了一定点定制，首先支持了公司的Ldap方式登录，然后每个用户默认能够看到public，同时只显示该用户有权限的namespace。

有开源吗？

**Comment by merngu** [comment]
> 我这边权限做了一定点定制，首先支持了公司的Ldap方式登录，然后每个用户默认能够看到public，同时只显示该用户有权限的namespace。

您好，想问下你们怎么配置的，我这边配置后不生效
