### ISSUE TITLE
1.3.1 BUG “Cannot get LocalHost InetAddress, please check your network!”

### ISSUE THREAD

**Issue by winsoar** [alibaba/nacos#3485]
**启动报错**
“Cannot get LocalHost InetAddress, please check your network!”

大概原因是这段代码获取 Host 失败导致的
```
InetAddress address;
try {
    address = InetAddress.getLocalHost(); 
} catch (final UnknownHostException e) {
    throw new IllegalStateException(
            "Cannot get LocalHost InetAddress, please check your network!");
}
byte[] ipAddressByteArray = address.getAddress();
workerId = (((ipAddressByteArray[ipAddressByteArray.length - 2] & 0B11)
    << Byte.SIZE) + (ipAddressByteArray[ipAddressByteArray.length - 1] & 0xFF));
```

**手动配置 worker-id 后，暂时解决**
`nacos.core.snowflake.worker-id=1`

 - OS: Centos
 - Version nacos-server 1.3.1

**Comment by chuntaojun** [comment]
InetAddress.getLocalHost(); 这段代码在你的机器运行一下

**Comment by KomachiSion** [comment]
这个地方应该优化一下，应该把里面的异常内容也抛出去。

**Comment by ljhrot** [comment]
@i will solve it@

**Comment by zhicheng-ning** [comment]
> “Cannot get LocalHost InetAddress, please check your network!”

1.3.2 也出现了这个错误，手动配置 worker-id 后，也暂时解决

- OS Version：Linux version 4.4.0-210-generic (buildd@lgw01-amd64-009) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021
- Nacos Server Version：1.3.2
