### ISSUE TITLE
1.3.0版本----权限控制模块仅能创建用户，创建角色和权限并绑定新用户后，并不能按预设权限进行控制，依然能看到所有命名空间，并能操作

### ISSUE THREAD

**Issue by forevercjh** [alibaba/nacos#3488]
![image](https://user-images.githubusercontent.com/8346331/89008167-c41db080-d33c-11ea-829a-09495a8a79ee.png)

![image](https://user-images.githubusercontent.com/8346331/89008202-d861ad80-d33c-11ea-832d-8f23d8c64292.png)

![image](https://user-images.githubusercontent.com/8346331/89008241-edd6d780-d33c-11ea-8fdf-4c82fc6c3f86.png)

**Comment by KomachiSion** [comment]
please check `nacos.core.auth.enabled=true`

**Comment by xiaoxiangzhenyu** [comment]
是不是有bug呢，我这边确定是有配置『nacos.core.auth.enabled=true』的

**Comment by KomachiSion** [comment]
我测试是没有问题的，甚至还有导致#2835、#3406之类的问题

**Comment by KomachiSion** [comment]
能看到命名空间，但是点其他命名空间会报没有权限，2835那种问题

**Comment by KomachiSion** [comment]
No more response from author and we can't reproduce the problem. close issue.

**Comment by forevercjh** [comment]
换成了1.3.1版本，增加配置后是可以的
