### ISSUE TITLE
注册中心注册事件拓展触发

### ISSUE THREAD

**Issue by haozi000005** [alibaba/nacos#3490]
希望nacos可以支持注册事件的触发的时候提供扩展代码提供回调功能，比如：
房间分配的逻辑写在注册中心中，当A进程注册的时候，可以得到分配的房间信息，希望可以提供拓展的方式来进行注入此功能。谢谢

**Comment by KomachiSion** [comment]
没有看懂，现在的subscribe功能不就是触发服务的实例发生了变更的吗？
