### ISSUE TITLE
 Improvement of configuration list

### ISSUE THREAD

**Issue by 16boke** [alibaba/nacos#3492]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
First, you can add a fuzzy query to the dataid in the configuration list, and only input part of the data ID content. Second, whether the data ID input box can also add delectable attributes.

第一，在配置列表中能不能添加对DataID的模糊查询，只输入部分data id内容。第二，Data ID输入框能不能也增加可删除属性。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Maijh97** [comment]
@16boke 第一 : 配置列表中data ID支持模糊查询的。使用方式  data* 这种方式，后面跟随 “*” 符号
第二: Data ID输入框能不能也增加可删除属性，不太明白，这里增加可删除的属性是指什么？
