### ISSUE TITLE
nacos SpringMVC placeHolder 获取不到值吗 ?

### ISSUE THREAD

**Issue by wxianfeng** [alibaba/nacos#3493]
```java
@Configuration
@EnableNacosConfig(globalProperties = @NacosProperties(
        endpoint = "${endpoint}",
        namespace = "${namespace}",
        accessKey = "${accessKey}",
        secretKey = "${secretKey}"
))
@NacosPropertySource(dataId = "abc.data", autoRefreshed = true)
public class NacosConfiguration {
}
```

传统的 SpringMVC  项目，placeHolder @NacosProperties 不能像 spring 自带的 `@Value`  获取到值，请问支持吗，如何配置?

谢谢 

nacos 版本: 0.3.6
SpringMvc 版本: 4.3.20.RELEASE

**Comment by KomachiSion** [comment]
0.3.6 is too old. And no longer maintained. Can you upgrade to 1.3.1 and retry?

**Comment by wxianfeng** [comment]
@KomachiSion 
是 `nacos-spring-context` 版本 0.3.6

**Comment by wxianfeng** [comment]
相关的 issue: 
https://github.com/alibaba/nacos/issues/529

**Comment by KomachiSion** [comment]
This issue has no discuss for a long time, Please use new version to retry, if also has problem, please submit new issue.
