### ISSUE TITLE
为什么我的maven找不到nacos-discovery2.2.1版本

### ISSUE THREAD

**Issue by wekin** [alibaba/nacos#3494]
我的项目配置spring-cloud-starter-alibaba-nacos-discovery 2.2.1后一直报红,日志也没有打印成功注册到nacos,
切换到0.2.2后成功注册到nacos,但是spring-gateway根本无法导航!!!!!

**Comment by KomachiSion** [comment]
```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>2.2.1.RELEASE</version>
</dependency>
```

If your pom can't find it. Please change your maven remote repo and retry.

**Comment by zhu1227** [comment]
改了那么多仓库依旧找不到，让我一度以为自己是错的

**Comment by GTWONDER** [comment]
解决了没老哥，我现在用maven 下载阿里的  组件也一直下载不了，配置了阿里的镜像加速器了

**Comment by zhu1227** [comment]
393792468加⬇️微信。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GTWONDER <notifications@github.com&gt;
发送时间: 2021年1月20日 10:30
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: zhu1227 <393792468@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 为什么我的maven找不到nacos-discovery2.2.1版本 (#3494)

**Comment by zhu1227** [comment]
> 解决了没老哥，我现在用maven 下载阿里的 组件也一直下载不了，配置了阿里的镜像加速器了

我的确实好了https://blog.csdn.net/weixin_41546244/article/details/110631036可以参考下，我博客的nacos版本更换

**Comment by GTWONDER** [comment]
404啊 你删除了吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhu1227"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 上午10:39
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "好幽默"<929507053@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] 为什么我的maven找不到nacos-discovery2.2.1版本 (#3494)





  
解决了没老哥，我现在用maven 下载阿里的 组件也一直下载不了，配置了阿里的镜像加速器了
  
我的确实好了https://blog.csdn.net/weixin_41546244/article/details/110631036可以参考下，我博客的nacos版本更换

**Comment by GTWONDER** [comment]
已加&nbsp; &nbsp; 好幽默


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月20日(星期三) 上午10:33
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"好幽默"<929507053@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] 为什么我的maven找不到nacos-discovery2.2.1版本 (#3494)





 393792468加⬇️微信。 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: GTWONDER <notifications@github.com&amp;gt; 
 发送时间: 2021年1月20日 10:30 
 收件人: alibaba/nacos <nacos@noreply.github.com&amp;gt; 
 抄送: zhu1227 <393792468@qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt; 
 主题: 回复：[alibaba/nacos] 为什么我的maven找不到nacos-discovery2.2.1版本 (#3494)

**Comment by zhu1227** [comment]
微信393792468



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GTWONDER <notifications@github.com&gt;
发送时间: 2021年1月20日 10:40
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: zhu1227 <393792468@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 为什么我的maven找不到nacos-discovery2.2.1版本 (#3494)





 404啊 你删除了吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "zhu1227"<notifications@github.com&amp;gt;;  
 发送时间: 2021年1月20日(星期三) 上午10:39 
 收件人: "alibaba/nacos"<nacos@noreply.github.com&amp;gt;;  
 抄送: "好幽默"<929507053@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [alibaba/nacos] 为什么我的maven找不到nacos-discovery2.2.1版本 (#3494) 
 
 
 
 
 
    
 解决了没老哥，我现在用maven 下载阿里的 组件也一直下载不了，配置了阿里的镜像加速器了 
    
 我的确实好了https://blog.csdn.net/weixin_41546244/article/details/110631036可以参考下，我博客的nacos版本更换
