### ISSUE TITLE
监听配置变化时失败,异常信息如下

### ISSUE THREAD

**Issue by xulingfeng931027** [alibaba/nacos#3497]
![image](https://user-images.githubusercontent.com/30265955/89096410-23e18d80-d409-11ea-8034-fb04adfce269.png)
java.lang.IllegalArgumentException: ExistingValue must be an instance of org.mybatis.spring.SqlSessionFactoryBean
首先异常信息没有打出来,debug到对应类下才看到.配置热部署功能失效,必须要重启才能改配置了  client版本是1.2.1

**Comment by xulingfeng931027** [comment]
ERROR [wsf-user,,,] 13176 --- [172.22.0.2_8848] com.alibaba.nacos.client.config.impl.CacheData : [fixed-172.22.0.2_8848] [notify-error] dataId=wsf-user.properties, group=DEFAULT_GROUP, md5=965c1f58ac1bcd25854655fd2cd185b5, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@498e3d72 tx=null

**Comment by wangweizZZ** [comment]
这个跟https://github.com/spring-cloud/spring-cloud-commons/issues/356 这个有关么 看着不像是nacos本身的问题

**Comment by xulingfeng931027** [comment]
> 这个跟[spring-cloud/spring-cloud-commons#356](https://github.com/spring-cloud/spring-cloud-commons/issues/356) 这个有关么 看着不像是nacos本身的问题

thanks,我查了项目中  确实在某个factoryBean的声明上使用了@configurationProperties  去掉之后就可以了
