### ISSUE TITLE
Optimization suggestions

### ISSUE THREAD

**Issue by pengzhengfa** [alibaba/nacos#3498]
In the CP architecture, data persistence to disk consumes a lot of performance. When I read the MySQL source code, I think the bufferpool caching mechanism of MySQL can be used for reference to solve the performance problem of persistence to disk

**Comment by KomachiSion** [comment]
We have plan to replace naming's raft to Jraft, maybe that plan will solve this problem.

I will tag this issue as enhancement and keep it for few days. And do some discuss for community.

**Comment by zongtanghu** [comment]
If you have interested in this optimization feature,  you can paritcipate in it. @wangweizZZ

**Comment by BobSimon** [comment]
It's so cool

**Comment by KomachiSion** [comment]
Nacos support Jtaft from 1.4

**Comment by BobSimon** [comment]
我已收到您的邮件！谢谢！
