### ISSUE TITLE
Service List Page Increase the number of pages switching function is the same as the configuration management page

### ISSUE THREAD

**Issue by lidaoyang** [alibaba/nacos#3500]
The service list page defaults to 10 items per page. When the number of services exceeds 100, it is not conducive to service queries,The service list API supports page switching. You only need to implement this function on the page.

服务列表页默认每页是10条，当服务数超过100个后不利于服务的查询，看了服务列表API是支持页数切换的，只需要页面实现该功能就好了

**Comment by ljhrot** [comment]
@KomachiSion  duplicate with #3439?

**Comment by lidaoyang** [comment]
@ljhrot What I mean is that the service list also has the same functions as the configuration list. We recommend that you have a larger number of pages.
我说的是服务列表里面里也和配置列表一样的功能，建议页数大一点。
