### ISSUE TITLE
The server address server mode cannot obtain the application.properties Variables in（ address.server.domain=xxx . xxx.com )

### ISSUE THREAD

**Issue by qm0123** [alibaba/nacos#3509]
**Describe the bug**
中文:服务端 address-server 模式无法获取从application.properties中的变量(address.server.domain=xxx.xxx.com)
英文:The server address server mode cannot obtain the application.properties Variables in（ address.server.domain=xxx . xxx.com )

**Expected behavior**
中文:可以从配置文件中获取到系统变量, 当前的方式是 系统变量和启动jvm中获取, 也应该支持从配置文件中获取. 并且增加文档描述
    获取配置的优先级:系统环境变量 -> 启动jvm(-D) -> properties
英文: the system variables can be obtained from the configuration file. The current way is to obtain the system variables from the system variables and the startup JVM. It should also support obtaining system variables from the configuration files.And add document description
Get the priority of configuration: system environment variables > start JVM (- D) - > properties

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. application.properties配置 address.server.domain=xxx.xxx.com
2. 启动 debug: address.server.domain= null

![4612C75B-D12A-466a-85B4-931B7ABD043B](https://user-images.githubusercontent.com/67568757/89245522-9043d300-d63b-11ea-9fea-86af997239fe.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Version nacos-server 1.3.1

**Comment by qm0123** [comment]
If this needs to be addressed,@i will solve it@

**Comment by KomachiSion** [comment]
Welcome to contribute. Thanks

**Comment by KomachiSion** [comment]
@chuntaojun What‘s your design? Can it be set by users?
