### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/nacos#351]
i try to run ``com.alibaba.nacos.example.App#main``

got some error like that
```
Exception in thread "main" java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([21.34.53.5:8848, 21.34.53.6:8848]) tried

```

is that right?

**Comment by nkorange** [comment]
You should deploy at least one Nacos server and set the value of property 'serverAddr' to your Nacos server address in order to run this example code. Please refer to https://nacos.io/zh-cn/docs/quick-start.html to learn how to deploy Nacos server.
