### ISSUE TITLE
在使用命令行参数(-Dserver.port = 9000)启动被nacos管理的服务客户端时,发现命令行参数没有生效

### ISSUE THREAD

**Issue by yxh-china** [alibaba/nacos#3510]
**Describe the bug**
在使用命令行参数(-Dserver.port = 9000)启动被nacos管理的服务客户端时,发现命令行参数没有生效

**Expected behavior**
希望能提供配置可以选择远程配置不覆盖命令行参数，使命令行参数优先级为最高的
**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.2.1, nacos-client 1.2.1]
 - Module [e.g. naming/config]
 - SDK [spring-cloud-starter-alibaba-nacos-config]

**Additional context**

**Comment by zzq1314zll** [comment]
一般都是配置中心的的propertySource 优先级>命令行的PropertySource>本地配置文件的PropertySource吧

**Comment by yxh-china** [comment]
> 一般都是配置中心的propertySource优先级>命令行的PropertySource>本地配置文件的PropertySource吧

可是我配置中心的配置内容并不包含这个配置，我在用命令行启动时输入的参数还是被覆盖掉了，没有生效

**Comment by zzq1314zll** [comment]
可以把你的场景描述下吗，我尝试复现下问题

**Comment by yxh-china** [comment]
> 可以把你的场景描述下吗，我尝试复现下问题

使用nacos作为配置中心和注册中心，在我的项目(配置中心不包含也不能包含端口配置)进行打包后，使用java -jar xxx.jar -Dserver.port=8000命令进行启动， 
此时期望的项目启动端口应该是8000
但是启动后返现使用的端口还是SpringBoot默认的8080端口

**Comment by zzq1314zll** [comment]
抱歉我试着模拟出场景，但是并没有出现你说的问题呀

**Comment by yxh-china** [comment]
> 抱歉我试着模拟出场景，但是并没有出现你说的问题呀

你的项目能够使用你命令行内配置的端口信息进行启动吗，我想着去尝试了spring.cloud.config.override-none、override-system-properties、allow-override进行配置，还是不能根据命令行指定的端口启动

**Comment by yxh-china** [comment]
> 抱歉我试着模拟出场景，但是并没有出现你说的问题呀

我的<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>使用的是这个版本，spring-cloud-starter-alibaba-nacos-config也是2.2.1.RELEASE

**Comment by zzq1314zll** [comment]
@yxh-china  把你操作的步骤，一步一步截图出来看看呗

**Comment by yxh-china** [comment]
> @ yxh-china 把你操作的步骤，一步一步截图出来看看呗

十分感谢，问题解决了。
不知道是不是SpringBoot版本的原因，原本的Application启动类的写法：`SpringApplication.run(AuthorServerApplication.class)`  无法把args参数传递到Spring上下文中，所以命令行参数配置无效。
现在只能使用`new SpringApplication(AuthorServerApplication.class).run(args)` 这种方式启动，就完全正常了
