### ISSUE TITLE
我们可以新增两个标签 <easy to implement ><easy to fix> 新手容易上手

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#3513]
我们可以新增两个标签 <easy to implement ><easy to fix> 新手容易上手

we can add two labels <easy to implement ><easy to fix>  Easy for novices;

**Comment by KomachiSion** [comment]
We have `good first issue` to do this.

But we have no much time to judge for each issue whether they is  `good first issue` for now.
