### ISSUE TITLE
Nacos 1.3.0在spring-alibaba服务配置中密码不能使用特殊字符

### ISSUE THREAD

**Issue by Alenx58** [alibaba/nacos#3517]
Nacos 1.3.0在spring-alibaba服务配置中密码不能使用特殊字符，否则会出现《unknown user!》

**Comment by qm0123** [comment]
@Alenx58 version: 1.3.2 服务端和客户端都无法复现这个问题,用最新版试试

**Comment by Alenx58** [comment]
@qm0123 生产环境不能随便更新啊，最新版没有这个问题就行。后期再做升级吧

**Comment by qm0123** [comment]
@Alenx58 关注1.4.0发版吧

**Comment by Alenx58** [comment]
ok
