### ISSUE TITLE
角色新增操作是不友好的

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#3518]
1. 如果输入中文就报错
![image](https://user-images.githubusercontent.com/33930711/89269629-b46bd800-d66c-11ea-8e5a-c3133109a1af.png)
2. 选择用户的时候应该变为可以搜索的下拉框，这样体验效果是不是好一些？

**Comment by KomachiSion** [comment]
Please use nacos code style to reformat your change of java code
detail see src/style/codeStyle.md
