### ISSUE TITLE
nacos开启认证了之后 权限BUG问题

### ISSUE THREAD

**Issue by areskts** [alibaba/nacos#3520]
nacos后台配置开启权限之后，用admin用户登录认证没有问题；
然而在建立一个新用户，分配各个命名空间读写权限，然后配置修改为新建的用户和密码，启动之后一直报错403 无权限问题

**Comment by KomachiSion** [comment]
I think it's same as #3388 .
Can you try to in 1.3.2 version?

**Comment by KomachiSion** [comment]
No more response from author, I think it has been fixed. Close issue.
