### ISSUE TITLE
在控制台页面服务列表菜单查看服务详情，出现空白页面

### ISSUE THREAD

**Issue by zzzxdm** [alibaba/nacos#353]
测试服务注册与发现
1、问题复现：nacos 0.5.0,Linux 端
2、首先启动nacos-server服务，启动样例工程nacos-provider和nacos-consumer，服务成功注册到nacos-server，在服务列表中查看详情没有任何问题。（linux端默认以集群方式启动，直接启动会报找不到cluster.conf配置文件的错误，而Windows端默认单机模式启动）
3、重启nacos-server,打开控制台，此时还能看到刚才注册的两个服务，但是查看详情页面会出现空白页面。（nacos-provider和nacos-consumer这两个工程都是正常运行着的,应该是服务没有重新注册的原因）

**Comment by nkorange** [comment]
curl '$nacos_server:8848/nacos/v1/ns/service/detail?serviceName=nacos-provider'  看看这个接口返回什么？

**Comment by nkorange** [comment]
repeat with #306

**Comment by zzzxdm** [comment]
> repeated with #306

没注意有人提过这个问题了，下次搜索一下有没有类似问题再提........

**Comment by zzzxdm** [comment]
> curl '$nacos_server:8848/nacos/v1/ns/service/detail?serviceName=nacos-provider' 看看这个接口返回什么？
接口返回 serivce nacos-provider' is not found! 但是这个服务确实是存在的，nacos-server中查不到，nacos-consumer却可以正常调用nacos-provicer...........

**Comment by zzzxdm** [comment]
> curl '$nacos_server:8848/nacos/v1/ns/service/detail?serviceName=nacos-provider' 看看这个接口返回什么？

另外 nacos-server控制台显示服务的健康实例数目是0，无法删除。

**Comment by nkorange** [comment]
@zzzxdm 你是单机模式吗？

**Comment by zzzxdm** [comment]
没错，是单机模式的


朱振振
电话：15236967163
QQ：771668756
E-mail: zhuzhenzhenit@163.com
 
发件人： Fury Zhu
发送时间： 2018-11-29 11:13
收件人： alibaba/nacos
抄送： zzzxdm; Mention
主题： Re: [alibaba/nacos] 在控制台页面服务列表菜单查看服务详情，出现空白页面 (#353)
@zzzxdm 你是单机模式吗？

**Comment by nkorange** [comment]
看起来是会这个service-provider从Nacos删除了，所以控制台上显示异常。

**Comment by zzzxdm** [comment]
> 看起来是会这个service-provider从Nacos删除了，所以控制台上显示异常。

还有一个问题，注册上去的服务显示健康实例数为0，而且不能删除。查看详情显示的不是空白页面。

**Comment by nkorange** [comment]
derby-data存放的不是服务列表，从控制台是可以删除实例数为0的服务的。
你说的服务正常使用什么意思？是可以从客户端获取到服务的实例列表吗？

**Comment by zzzxdm** [comment]
> derby-data存放的不是服务列表，从控制台是可以删除实例数为0的服务的。
> 你说的服务正常使用什么意思？是可以从客户端获取到服务的实例列表吗？

是服务可以正常调用，比如consumer可以正常调用provider，但是nacos控制台服务列表却显示服务的健康实例数为0，这是为什么呢？

**Comment by cuqk** [comment]
同样出现类似的问题，且健康实例数不为0，在服务节点重启后会大概率出现 这种情况 @nkorange
