### ISSUE TITLE
All tables on the page should have refresh buttons

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#3530]
All tables on the page should have refresh buttons
我觉得所有的页面table都应该加上刷新按钮

**Comment by zzq1314zll** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
刷新按钮和直接刷新页面的区别是什么？

**Comment by zzq1314zll** [comment]
> 刷新按钮和直接刷新页面的区别是什么？

用户体验不一样

**Comment by KomachiSion** [comment]
会出现很大改动吗？ 还是只是控制台上简单增加点内容即可？

**Comment by zzq1314zll** [comment]
不会影响其他的功能
