### ISSUE TITLE
Discussion: is it better to unify the response error code and error information in the restresult of client / server

### ISSUE THREAD

**Issue by qm0123** [alibaba/nacos#3532]
中:
类似图中的响应信息和返回统一做一个整合到一个类中,调用时直接使用(RestResultUtils.failed(StatusCode.NOT_FOUND))
英:
Similar to the response information and return in the diagram, they are integrated into a class and used directly when calling((RestResultUtils.failed(StatusCode.NOT_FOUND)))

![image](https://user-images.githubusercontent.com/67568757/89485955-82758580-d7d4-11ea-8513-bcd1bf7112c4.png)

**Comment by KomachiSion** [comment]
Of course, there are one issue opened before, #2857 . If you want to contribute this part. you can comment in that issue, and go for it.
