### ISSUE TITLE
change cache dir with namespace

### ISSUE THREAD

**Issue by eightroad** [alibaba/nacos#3533]
**Is your feature request related to a problem? Please describe.**
I want to change nacos cache dir. but if i special the property "com.alibaba.nacos.naming.cache.dir", the cache dir dismissed {namespce} path。

**Describe the solution you'd like**
I check the code in com.alibaba.nacos.client.naming.NacosNamingService ,seems cacheDir should mean nacos home 。see below。
it shold  cacheDir = System.getProperty("com.alibaba.nacos.naming.cache.dir")+**/naming/" + namespace;**

**Describe alternatives you've considered**

**Additional context**
the origin code is:
  private void initCacheDir() {
        **cacheDir = System.getProperty("com.alibaba.nacos.naming.cache.dir");**
        if (StringUtils.isEmpty(cacheDir)) {
            cacheDir = System.getProperty("user.home") + "/nacos/naming/" + namespace;
        }
    }

**Comment by KomachiSion** [comment]
looks good. And can you check for config module, it should have another cache dir.

What's more, there may be some other dir is depend `user.home`, we may need to organize and discuss whether these cache dirs can be processed in a unified manner.

**Comment by JackSun-Developer** [comment]
.

**Comment by JackSun-Developer** [comment]
This is concerned the unification of paths in naming module.
The unification include two parts.
1. Unifying the logging paths (see PR #3859):
    (1) If the environment variable 'JM.LOG.PATH' is set, use ${sys:JM.LOG.PATH}/nacos as the parent dir of log files.
    (2) Else, use ${sys:user.home}/logs/nacos as the parent dir of log files.
2. Unifying the cache paths:
    (1) If the environment variable 'JM.SNAPSHOT.PATH' is set, use ${sys:JM.SNAPSHOT.PATH}/nacos/naming as the parent dir of naming cache files.
    (2) Else, use ${sys:user.home}/nacos/config as the parent dir of cache files.
