### ISSUE TITLE
Authorization failed changing personal password

### ISSUE THREAD

**Issue by xiaozhongliu** [alibaba/nacos#3534]
**Describe the bug**
Authorization failed changing personal password.

**Expected behavior**
A user should be able to change personal password normally.

**Acutally behavior**
Authorization failed changing personal password.

**How to Reproduce**
![image](https://user-images.githubusercontent.com/17674404/89490573-c326cc00-d7df-11ea-8542-4d1975655cbf.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version: nacos 1.3.1

**Comment by KomachiSion** [comment]
duplicate with #3406 , please add comment under #3406
