### ISSUE TITLE
could nacos client send heart beat not use PUT method 

### ISSUE THREAD

**Issue by donlianli** [alibaba/nacos#3539]
for some firewall in comapay,PUT,DELETE HTTP method is not allowed,so cause our service client lost heart beat。
I suggest nacos consider this requirement.
thank you very much!

## Issue Description
our comany firewall forbid HTTP PUT method in cloud machine(based on kvm),so our service disappear soon after first register.

Type: *feature request*

### Describe what happened (or what feature you want)

I want change PUT,DELETE http method to POST or GET method.
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos1.3.x

**Comment by KomachiSion** [comment]
From the RestFul meaning, I think use Put and Delete method is more correctly.

And few users have issues like these methods will be blocked for now. You are the first I saw.

Does anyone else have any ideas？

**Comment by horizonzy** [comment]
this situation is too customized.if somebody be in this case,should modify source code to suit their case.

**Comment by chuntaojun** [comment]
If it is a small company's special demand, should need to customize the itself. Setting the http-Method for each HTTP request should conform to the data impact of the request. I don't think this is a place that needs to be modified

**Comment by KomachiSion** [comment]
From the community response, It seems that use original RESTful meaning is more reasonable. So close issue.
