### ISSUE TITLE
namespace 和 dataId 字符串规则作用存在重复

### ISSUE THREAD

**Issue by gumutianqi** [alibaba/nacos#354]
使用 Nacos 作为配置中心，文档中对 dataId有一段这样的描述：

> 在 Nacos Spring Cloud 中，dataId 的完整格式如下：
```
${prefix}-${spring.profile.active}.${file-extension}
```
**其中`spring.profile.active`便是环境 environment，值如：dev/test/beta**

但是文档还有一段对 namaspace 有这样的一段描述：

> **命名空间（Namespace）**
> 用于进行租户粒度的配置隔离。不同的命名空间下，可以存在相同的 Group 或 Data ID 的配置。 Namespace 的常用场景之一是不同环境的配置的区分隔离，例如`开发测试环境`和`生产环境`的资源（如配置、服务）隔离等。

---

**总结**

根据上面的了解 namespace 是用来区分不同环境的配置，那在具体的配置当中，dataId 的字符串规则又要求是`${prefix}-${spring.profile.active}.${file-extension}`，这两者在这里是否有使用冲突，让开发者理解和使用上也会存在歧义和疑问！

**Comment by kukukakiki** [comment]
规则不存在重复，spring.profile.active是可以配置多个参数逗号分割的，这样可以把公共配置文件单独提出来维护

**Comment by gumutianqi** [comment]
多配置支持功能发布后不存在该问题
