### ISSUE TITLE
Data ID模糊搜索功能失效

### ISSUE THREAD

**Issue by zjcnew** [alibaba/nacos#3545]
配置管理，Data ID这里模糊搜索搜不到任何内容，精确匹配才可以搜索到内容。

![企业微信截图_20200806180303](https://user-images.githubusercontent.com/22335594/89604662-473f8900-d89e-11ea-8085-c0e55de8b02e.png)

**Comment by lucongcool** [comment]
我刚试了下 好像group也没带模糊查询功能

**Comment by Maijh97** [comment]
模糊查询使用 `data*`这种方式，需要带有符号 `"*"`

**Comment by chuntaojun** [comment]
> 模糊查询使用 `data*`这种方式，需要带有符号 `"*"`

**Comment by zjcnew** [comment]
> > 模糊查询使用 `data*`这种方式，需要带有符号 `"*"`

能不能优化成，不要使用通配符，来模糊查询

**Comment by KomachiSion** [comment]
duplicate with #3492
