### ISSUE TITLE
Docker部署nacos1.3.0，web页面缺失权限控制

### ISSUE THREAD

**Issue by uzdz** [alibaba/nacos#3546]
开发者您好，我使用如下Docker命令：
`docker run --env MODE=standalone --name nacos -d -p 8848:8848 -v --privileged=true --restart always nacos/nacos-server`

web页面缺失了权限控制tab，请问是移除了吗？还是什么情况呢？

**Comment by KomachiSion** [comment]
我试了一下，没有是ok的，你试下清理浏览器缓存再试试呢？

**Comment by uzdz** [comment]
您好，我这边确定是没有的，已经清了缓存，也让其他同事测试了下。

请问我是不是存在表没有导入，或者配置文件没有改为true等问题呢？

![image](https://user-images.githubusercontent.com/28328355/89630771-62c48700-d8d2-11ea-8341-3879e9ed0e17.png)

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/89633171-ff3c5880-d8d5-11ea-82a5-16e5c97bbc26.png)

我这里是没有问题的。
不需要开启auth=true，我是完全按照你的指令启动的docker

**Comment by uzdz** [comment]
低版本升级需要增加如下MySQL表：

`CREATE TABLE `permissions` ( `role` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `resource` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL, `action` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL, UNIQUE KEY `uk_role_permission` (`role`,`resource`,`action`) USING BTREE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`
