### ISSUE TITLE
Typo on registering in Nacos.

### ISSUE THREAD

**Issue by arjenzhou** [alibaba/nacos#3554]
There will be a typo on starting service while using *spring-cloud-starter-alibaba-nacos* at

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/23600703/89711313-1bb2c080-d9bc-11ea-923e-5c1fa26aed50.png">

which should be Nacos not **Nacso**.

**Comment by linqunhui** [comment]
@i will solve it@

**Comment by zongtanghu** [comment]
I will find someone to resolve this issue, so this issue can be assigned to me , firstly.

**Comment by corey89757** [comment]
I will fix this

**Comment by zongtanghu** [comment]
@corey89757  It's yours.

**Comment by linqunhui** [comment]
I'm find ,this not is nacos  ,it's in the spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java

**Comment by linqunhui** [comment]
I'm find,this not in the nacos ,     It's in the spring-cloud-starter-alibaba-nacos-discovery   NacosWatch.java .  but It was revised a week ago!

**Comment by KomachiSion** [comment]
@linqunhui Well, I will close this issue.
