### ISSUE TITLE
文档写的跟坨屎一样,能写清晰一点吗?

### ISSUE THREAD

**Issue by Yangdaidai** [alibaba/nacos#3556]
文档写的跟坨屎一样,能写清晰一点吗?

**Comment by yfh0918** [comment]
你牛逼你来贡献点文档，you can you up

发自我的iPhone

**Comment by nickChenyx** [comment]
伸手党还这么粗口，你真的是恶心

**Comment by KomachiSion** [comment]
文档相关问题和意见，欢迎回复到 #3073

**Comment by plusmancn** [comment]
做开源真不容易。

**Comment by Yangdaidai** [comment]
对不起，请加强文档的编写管理------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月12日(星期一) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 文档写的跟坨屎一样,能写清晰一点吗? (#3556)
