### ISSUE TITLE
windows10，nacos1.2.1，windows睡眠模式结束后，nacos占用cpu过高。

### ISSUE THREAD

**Issue by AKM000** [alibaba/nacos#3557]
<img width="629" alt="nacos" src="https://user-images.githubusercontent.com/59811327/89728396-a26ca980-da5f-11ea-8035-3c75e9f016da.PNG">

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
Can you dump thread or use arthas find out what's cost the cpus?

And please edit your issue description with template for others friendly?

**Comment by KomachiSion** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
Add any other context about the problem here.

**Comment by AKM000** [comment]
> Can you dump thread or use arthas find out what's cost the cpus?
> 
> And please edit your issue description with template for others friendly?



> Can you dump thread or use arthas find out what's cost the cpus?
> 
> And please edit your issue description with template for others friendly?



> Can you dump thread or use arthas find out what's cost the cpus?
> 
> And please edit your issue description with template for others friendly?

今天我试着重现那个情况，但一直没有复现。如果以后出现，会联系你的。

**Comment by AKM000** [comment]
今天回来用尽各种方法尝试复现问题，没成功。
然后刷微博的时候突然电脑卡，任务管理器显示打开nacos的那个cmd程序占用cpu过高。
具体过程如下
1：在bin目录下双击startup.cmd启动程序
2：然后向nacos注册了一个服务，作为测试
3：大概十分钟后关闭服务（强制关闭）
4：弄了些其他的，nacos一直启动着（这是没有任何服务注册，就单纯一个程序运行），只是那段时间没有使用电脑
5：然后及打开微博（忘记关闭nacos了），然后电脑就卡。
以下截图来自于jvisualvm，hprof文件来自于jmap dump。
我看了一下dump文件，也看不太懂。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 上午9:03
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"hY"<3311676596@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] windows10，nacos1.2.1，windows睡眠模式结束后，nacos占用cpu过高。 (#3557)





 
Can you dump thread or use arthas find out what's cost the cpus?
 
And please edit your issue description with template for others friendly?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

2020_8_10.hprof (154.62M, 2020年09月09日 21:06 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7533303275346595851f54f71239014c50075206020052541c5606035014075553571d0b0458044e530a5604030b0b5755525107343633510101006d0c6602531f5b40405b5f335e&t=exs_ftn_download&code=1302493c

**Comment by KomachiSion** [comment]
1. 截图看不到
2. 文件太大了 不好下载，建议还是拿arthas打火焰图出来，简单又明确。

**Comment by AKM000** [comment]
抱歉，我还在学习阶段。arthas这个东西我还是第一次听说。并且那个情况是随机出现的。 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;杨翊&amp;nbsp;SionYang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月11日(星期二) 上午9:41
收件人:&nbsp;&quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;;
抄送:&nbsp;&quot;AKM000&quot;<3311676596@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] windows10，nacos1.2.1，windows睡眠模式结束后，nacos占用cpu过高。 (#3557)

**Comment by KomachiSion** [comment]
@AKM000 信息太少了，没办法判断问题。建议看一下arthas，挺好用的。

@zongtanghu 有空麻烦试着复现下。如果复现不了，那可能就是环境问题了。

**Comment by KomachiSion** [comment]
从 dump出来的线程来看，没有什么特别的线程在处理，只有netty和nio线程在轮训，看不出来是什么导致CPU升高，估计还是需要打印火焰图来分析。

**Comment by AKM000** [comment]
对，好像不是。我前天运行别的jar包，也是莫名其妙也出现了CPU占用过高的情况。这应该不是nacos的原因，应该是我系统的问题。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;杨翊&amp;nbsp;SionYang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月21日(星期五) 上午10:02
收件人:&nbsp;&quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;;
抄送:&nbsp;&quot;AKM000&quot;<3311676596@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] windows10，nacos1.2.1，windows睡眠模式结束后，nacos占用cpu过高。 (#3557)

**Comment by KomachiSion** [comment]
那我先关Issue了，之后再出现的话，建议用arthas打一下火焰图，然后再提个issue。

**Comment by tanranv5** [comment]
我也遇到了上诉问题，但是我如何用arthas生成火焰图呢？【AsyncProfiler error: Current OS do not support AsyncProfiler, Only support Linux/Mac.  】

**Comment by xmf1142987374** [comment]
我也是的，最近出现了几次，nacos 开着，然后有时候就cpu 直接占满了，然后我只好重启nacos 。我的版本是1.2.0

**Comment by xmf1142987374** [comment]
1.2.10和1.2.1 都试过了。环境： windows10 。 操作： 启动nacos  大概过两个小时~两个半小时 ，cpu 占满 居高不下 。

**Comment by xmf1142987374** [comment]
![1](https://user-images.githubusercontent.com/44333740/93870196-6afc4880-fcff-11ea-87bd-b91d9d35f7b0.png)

**Comment by xmf1142987374** [comment]
最新的nacos 版本也是这样 ，我就启动nacos  然后什么都不做，等待大概两个多小时，cpu 就突然一下子被它占满

**Comment by KamSss** [comment]
> 那我先关Issue了，之后再出现的话，建议用arthas打一下火焰图，然后再提个issue。

你好，nacos版本号1.3.2，同样出现上述问题，启动一小时左右nacos开始占满内存，麻烦看一下。

**Comment by KamSss** [comment]
@KomachiSion

**Comment by ldkkkkk** [comment]
2个小时数据库连接池里的连接失效了，然后cpu就100%了
