### ISSUE TITLE
关于Nacos1.2.1的一些玄学问题

### ISSUE THREAD

**Issue by NaiYY** [alibaba/nacos#3558]
你好，我想先感谢一下，你们的辛苦劳动付出，然后再描述一下问题
问题是这样的，先来说一下环境
WIN10 + JDK1.8 + Maven3.6.3 + SpringBoot2.3.1 + Nacos1.2.1 + SpringCloudAlibaba Nacos 2.1.0
问题是这样的，想注册一个服务进入Nacos 上

出现了一些小问题

1.Ribbon问题

这是日志信息

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-09 18:15:00.533 ERROR 9244 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method ribbonServerList in com.alibaba.cloud.nacos.ribbon.NacosRibbonClientConfiguration required a bean of type 'com.netflix.client.config.IClientConfig' that could not be found.

Action:

Consider defining a bean of type 'com.netflix.client.config.IClientConfig' in your configuration.

Process finished with exit code 1

然后通过添加一个IClientConfig实现类解决了问题

package com.rule;

import com.netflix.client.config.IClientConfig;
import com.netflix.client.config.IClientConfigKey;
import org.springframework.stereotype.Component;

import java.util.Map;

@Component
public class MyRule implements IClientConfig {
    public String getClientName() {
        return null;
    }

    public String getNameSpace() {
        return null;
    }

    public void loadProperties(String s) {

    }

    public void loadDefaultValues() {

    }

    public Map<String, Object> getProperties() {
        return null;
    }

    public void setProperty(IClientConfigKey iClientConfigKey, Object o) {

    }

    public Object getProperty(IClientConfigKey iClientConfigKey) {
        return null;
    }

    public Object getProperty(IClientConfigKey iClientConfigKey, Object o) {
        return null;
    }

    public boolean containsProperty(IClientConfigKey iClientConfigKey) {
        return false;
    }

    public String resolveDeploymentContextbasedVipAddresses() {
        return null;
    }

    public int getPropertyAsInteger(IClientConfigKey iClientConfigKey, int i) {
        return 0;
    }

    public String getPropertyAsString(IClientConfigKey iClientConfigKey, String s) {
        return null;
    }

    public boolean getPropertyAsBoolean(IClientConfigKey iClientConfigKey, boolean b) {
        return false;
    }

[CloudAlibabaStudy.zip](https://github.com/alibaba/nacos/files/5047180/CloudAlibabaStudy.zip)

    public <T> T get(IClientConfigKey<T> iClientConfigKey) {
        return null;
    }

    public <T> T get(IClientConfigKey<T> iClientConfigKey, T t) {
        return null;
    }

    public <T> IClientConfig set(IClientConfigKey<T> iClientConfigKey, T t) {
        return null;
    }
}

解决了之后
又出现另一个问题，日志如下

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.cloud.client.discovery.health.DiscoveryCompositeHealthIndicator.<init>(DiscoveryCompositeHealthIndicator.java:42)

The following method did not exist:

    org.springframework.boot.actuate.health.CompositeHealthIndicator.<init>(Lorg/springframework/boot/actuate/health/HealthAggregator;)V

The method's class, org.springframework.boot.actuate.health.CompositeHealthIndicator, is available from the following locations:

    jar:file:/Y:/repository/org/springframework/boot/spring-boot-actuator/2.3.1.RELEASE/spring-boot-actuator-2.3.1.RELEASE.jar!/org/springframework/boot/actuate/health/CompositeHealthIndicator.class

The class hierarchy was loaded from the following locations:

    org.springframework.boot.actuate.health.CompositeHealthIndicator: file:/Y:/repository/org/springframework/boot/spring-boot-actuator/2.3.1.RELEASE/spring-boot-actuator-2.3.1.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.actuate.health.CompositeHealthIndicator

Process finished with exit code 1

然后我又尝试将actuator的依赖注释掉了，然后就可以成功的使用了

可以用，我有点好奇，我与我的朋友们的环境依赖一模一样，跟着官网一步一步完成

他们的无需像我这样去做，就可以正常执行

请问一下，这是我的操作问题，还是Bug呢？

不知描述是否清晰，希望能够尽快看到答复，感激不尽.....

**Comment by NaiYY** [comment]
@chuntaojun

**Comment by KomachiSion** [comment]
如果其他人可以正常使用，那应该是您环境的问题，这个只能您自己排查下。

这里推测可能是依赖包冲突导致的，可以mvn dependency:tree看下

**Comment by NaiYY** [comment]
> 如果其他人可以正常使用，那应该是您环境的问题，这个只能您自己排查下。
> 
> 这里推测可能是依赖包冲突导致的，可以mvn

你好，就是请问是否是我版本引用有误，应该不是jar冲突，用的就是官方的三个jar包

**Comment by KomachiSion** [comment]
看了一下日志，应该还是版本冲突，spring提示actuate的方法不存在，那说明actuate的相关class存在，但是class的版本不对，所以导致method没有。 建议还是查一下依赖冲突，和是否是官方的包没有关系。
这个问题不是nacos的问题。issue我先关了。

**Comment by NaiYY** [comment]
> 看了一下日志，应该还是版本冲突，spring提示actuate的方法不存在，那说明actuate的相关class存在，但是class的版本不对，所以导致method没有。 建议还是查一下依赖冲突，和是否是官方的包没有关系。
> 这个问题不是nacos的问题。issue我先关了。

好的，多谢
