### ISSUE TITLE
nacos services register Services have been added and deleted

### ISSUE THREAD

**Issue by 285551339** [alibaba/nacos#3561]
**Describe the bug**
The nacos registry found that when the service was in use, the occasional refresh of the tomcat service was not visible.
Services are being removed all the time.

**Expected behavior**
Services are available when the registry refreshes

**Acutally behavior**
Tomcat USES external, with custom annotations added to specify the Tomcat port.

**Desktop (please complete the following information):**
 - OS: [e.g. red hat]
 - Version [e.g. nacos-server 2.1.1, nacos-client 2.1.1]

**Additional context**
![image](https://user-images.githubusercontent.com/16172632/89746795-3f762380-daee-11ea-9305-b075fb693cc4.png)
![image](https://user-images.githubusercontent.com/16172632/89746803-456c0480-daee-11ea-8d38-37f7c946fa68.png)
![image](https://user-images.githubusercontent.com/16172632/89746812-4bfa7c00-daee-11ea-9744-975d443899c8.png)
![image](https://user-images.githubusercontent.com/16172632/89746822-57e63e00-daee-11ea-96d5-e0f39c38b551.png)

**Comment by KomachiSion** [comment]
nacos-server version need be update, there are no 2.1.1 version

**Comment by KomachiSion** [comment]
And for the problem, because server do not receiver the beat of the instance, so removed. After one minutes, the beat happen again, so register it back.

I think you should find out why the beat is interrupted

**Comment by 285551339** [comment]
> nacos-server版本需要更新，没有2.1.1版本



> nacos-server版本需要更新，没有2.1.1版本

**Comment by 285551339** [comment]
> nacos-server version need be update, there are no 2.1.1 version

Sorry, wrong number ，there are 1.2.1 version

**Comment by 285551339** [comment]
> And for the problem, because server do not receiver the beat of the instance, so removed. After one minutes, the beat happen again, so register it back.
> 
> I think you should find out why the beat is interrupted

Can you make it clear
