### ISSUE TITLE
关于nacos集群在网络故障下的高可用问题

### ISSUE THREAD

**Issue by LittleM318** [alibaba/nacos#3565]
**Describe the bug**
在生产上需要模拟极端网络情况下，nacos高可用情况。
网络关系如下图所示：
![Xnip2020-08-10_16-50-53](https://user-images.githubusercontent.com/59717520/89766351-98fc4380-db2a-11ea-8699-fea343ffff51.jpg)
nacos集群之间网络连接中断
feign调用，从客户端1调用客户端2
客户端1与nacos集群中的1，2两台有网络连接，与3连接失败
客户端2与nacos集群中的1有网络连接，与2，3连接失败

**Expected behavior**
在压力测试情况下，客户端1成功调用客户端2，成功与失败情况，各百分之50.

**Acutally behavior**
有时，失败比例高于90%，有时全部成功。

想请教一下各位老师们，这种情况是正常的吗？

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
实在没看懂。
1. nacos服务直接完全网络中断？ 那就相当于部署了3台单机模式的nacos？
2. 客户端1连接nacos1和nacos2，是指随机注册到这两个节点上吗？
3. `有时，失败比例高于90%，有时全部成功。`  那总体算起来不就是约等于50%吗？
4. `从客户端1调用客户端2` 客户端之间的调用和nacos没有关系，nacos只有在注册信息变更时候才会推送给客户端，如果客户端1没有注册到nacos1上，你又网络隔离，那么客户端2肯定找不到客户端1.
