### ISSUE TITLE
Update for Writer#removeFile

### ISSUE THREAD

**Issue by Technoboy-** [alibaba/nacos#3567]
Use 
```
public boolean removeFile(final String fileName) {
        return files.remove(fileName) != null;
    }
```
instead of 
```
public boolean removeFile(final String fileName) {
        files.remove(fileName);
        return true;
    }
```

**Comment by KomachiSion** [comment]
Why do you want to replace it?

**Comment by Technoboy-** [comment]
> Why do you want to replace it?

Return true looks not accurate.

**Comment by Technoboy-** [comment]
A little improvement.
If you think it's no need , nothing impact

**Comment by KomachiSion** [comment]
@Technoboy- In my opinion, This method should be that the input fileName is no longer stay in the `files` after the call. If it does not exist, then it is also suitable for the purpose.
But your implementation will return false when fileName is non-exist. So I think it is no reasonable.
