### ISSUE TITLE
1.3.2 编辑配置时，配置格式为空

### ISSUE THREAD

**Issue by shansr** [alibaba/nacos#3573]
如新建dev.yaml 配置并发布，返回主页点击左侧-配置列表，在操作列点击“编辑”，进入编辑页面后，“配置格式”为空。如图

新建时：
![1597123055(1)](https://user-images.githubusercontent.com/53803242/89860357-d964cb80-dbd5-11ea-8c0c-65f616ff4785.png)

编辑时：
![1597123340(1)](https://user-images.githubusercontent.com/53803242/89860295-be925700-dbd5-11ea-9460-ac2c538b1bfa.jpg)

**Comment by KomachiSion** [comment]
我在demo控制台上试了下，没有问题
http://console.nacos.io/nacos/index.html#/configeditor?serverId=center&dataId=test_for_issue_3573&group=DEFAULT_GROUP&namespace=&edasAppName=&edasAppId=&searchDataId=&searchGroup=&pageSize=10&pageNo=2

**Comment by shansr** [comment]
> 我在demo控制台上试了下，没有问题
> http://console.nacos.io/nacos/index.html#/configeditor?serverId=center&dataId=test_for_issue_3573&group=DEFAULT_GROUP&namespace=&edasAppName=&edasAppId=&searchDataId=&searchGroup=&pageSize=10&pageNo=2

本人集群用的是内嵌数据库
ps: demo 控制台username/pwd ?

**Comment by KomachiSion** [comment]
> > 我在demo控制台上试了下，没有问题
> > http://console.nacos.io/nacos/index.html#/configeditor?serverId=center&dataId=test_for_issue_3573&group=DEFAULT_GROUP&namespace=&edasAppName=&edasAppId=&searchDataId=&searchGroup=&pageSize=10&pageNo=2
> 
> 本人集群用的是内嵌数据库
> ps: demo 控制台username/pwd ?

所以建议按照issue模版来填写issue，可以减少这种应答次数

1. demo 控制台使用的是standalone+内嵌数据库
2. 默认用户名密码都是nacos
