### ISSUE TITLE
nacos-server1.3.2修改心跳检查方式报403，无权限

### ISSUE THREAD

**Issue by guyanzhao11** [alibaba/nacos#3575]
**1、环境**
版本 nacos-server1.3.2
环境win10
  修改 application.properties 中的 nacos.core.auth.enabled=true   ，开启认证

启动方式
   解压 ，启动
   启动命令   cd  ${nacos}/bin

   startup.cmd   -m  standalone 
 
  2、启动后上报一个服务到nacos-server

 3、用 nacos用户通过浏览器登陆页面，修改心跳方式(默认的用户名 nacos ,密码nacos)
   操作步骤：
    点菜单  服务管理 ---服务列表  ，   任意选择一个已有的服务 ，点   “详情”  --- 集群配置  ---修改心跳为 HTTP方式  ，确认。

报文如下：
请求地址如  http://xxx:8848/nacos/v1/ns/cluster?&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTU5NzEzMzg5Nn0.Jg4ln4HilPZOADL-Zf3DBv9xHiJ_9CUbvbgnUkSQwb0
状态码  403

返回结果：
{"timestamp":"2020-08-11T07:47:16.234+0000","status":403,"error":"Forbidden","message":"resource name invalid!","path":"/nacos/v1/ns/cluster"}

  

    
如果把
nacos.core.auth.enabled=false ,重启服务，则上面操作能修改成功。

**Comment by KomachiSion** [comment]
duplicate with #3005
