### ISSUE TITLE
@Value annotation must write setter, suggest optimization implementation

### ISSUE THREAD

**Issue by tgwang** [alibaba/nacos#358]
When using the `@Value` annotation, you must add a setter method, which I think is not very elegant.

E.g:
```java
@Controller
@RequestMapping("config")
Public class ConfigController {

     @Value("${useLocalCache:false}")
     Private boolean useLocalCache;

     Public void setUseLocalCache(boolean useLocalCache) {
         this.useLocalCache = useLocalCache;
     }

     @RequestMapping(value = "/get", method = GET)
     @ResponseBody
     Public boolean get() {
         Return useLocalCache;
     }
}
```

And if you want to change the original project to the nacos configuration center, you must add a setter method to all `@Value` places, which will lead to excessive transformation costs.

Can you optimize the implementation of this feature, remove the setter method

**Comment by mercyblitz** [comment]
It is not an issue, `@Value` always supports field injection natively in Spring Framework.

**Comment by hxy1991** [comment]
This will be optimized in Nacos 0.6.0 and is expected to be released next week.

**Comment by tgwang** [comment]
> > The setter method is not required unless you need to dynamically update the configuration. This will be optimized in Nacos 0.6.0 and is expected to be released next week.
> 
> If he requires dynamical one , please use `@NacosValue` in https://github.com/nacos-group/nacos-spring-project/

I know that `@NacosValue` can achieve this capability, but the cost of the original project transformation will be very large, so `@Value` can achieve this function is the best.
