### ISSUE TITLE
docker-compose 部署时，nacos无法启动/nacos无法访问，但prometheus与grafana启动正常

### ISSUE THREAD

**Issue by MrWenBo** [alibaba/nacos#3581]
yaml文件配置如下：
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=192.168.100.240
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_SLAVE_SERVICE_HOST=192.168.100.240
      - MYSQL_SLAVE_SERVICE_PORT=3307
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=root
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: on-failure
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure

nacos.log 报错如下：
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
9167         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
9168         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
9169         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
9170         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
9171         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
9172         at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:905)
9173         at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:830)
9174         at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
9175         at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
9176         at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
9177         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
9178         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
9179         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
9180         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
9181         at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
9182         at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
9183         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
9184         at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
9185         at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
9186         at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
9187         at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
9188         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
9189         at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
9190         at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl$CheckDbHealthTask.run(ExternalDataSourceServiceImpl.java:267)
9191         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
9192         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
9193         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
9194         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
9195         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
9196         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
9197         at java.lang.Thread.run(Thread.java:748)
9198 Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
9199 
9200 The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
9201         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
9202         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
9203         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
9204         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
9205         at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
9206         at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
9207         at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
9208         at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
9209         at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
9210         at com.mysql.cj.NativeSession.connect(NativeSession.java:152)
9211         at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)
9212         ... 25 common frames omitted
9213 Caused by: java.net.UnknownHostException: ${MYSQL_SERVICE_HOST}
9214         at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
9215         at java.net.InetAddress.getAllByName(InetAddress.java:1193)
9216         at java.net.InetAddress.getAllByName(InetAddress.java:1127)
9217         at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:132)
9218         at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
9219         ... 27 common frames omitted

说明：centos上8848端口已开放，3306与3307端口及其他相应端口，在防火墙上已开

**Comment by KomachiSion** [comment]
先试用下[nacos-docker](https://github.com/nacos-group/nacos-docker/tree/master/example)的mysql example。

这个报错明显`java.net.UnknownHostException: ${MYSQL_SERVICE_HOST}`

**Comment by MrWenBo** [comment]
> 先试用下[nacos-docker](https://github.com/nacos-group/nacos-docker/tree/master/example)的mysql example。
> 
> 这个报错明显`java.net.UnknownHostException: ${MYSQL_SERVICE_HOST}`

直接用example是可以的
但是我这个就不行

**Comment by KomachiSion** [comment]
因为你没有设置这个参数啊`${MYSQL_SERVICE_HOST}`
`MYSQL_MASTER_SERVICE_HOST`这个不识别
