### ISSUE TITLE
the persist instance will lose when the server reboot

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3588]
**Describe the bug**
the logic in com.alibaba.nacos.naming.core.ServiceManager#createServiceIfAbsent can't create serviceMeta file.
if the service created by  ephemeral instance, the serviceMeta file didn't create. and then still this service, create an persist instance with in this service , the serviceMeta file will not created.because the serviceMeta file just created when the service is not exist, but the instance file created normally, reboot the server, the instance file will not load to raftStore

**Comment by KomachiSion** [comment]
I am not sure that which situation you need to register an ephemeral instance first and then register a persistent instance.

the persistent instance is used by addressServer or DNS situation. For application discovery situation, it should be always ephemeral all the time.

**Comment by horizonzy** [comment]
> I am not sure that which situation you need to register an ephemeral instance first and then register a persistent instance.
> 
> the persistent instance is used by addressServer or DNS situation. For application discovery situation, it should be always ephemeral all the time.

I just use the client-sdk for test,I notice the serviceMeta file just created when the service created, so I simulate this situation for test. if the situation is illegal, I will close it.
