### ISSUE TITLE
Support user extended health check type

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#359]
Nacos currently supports TCP, HTTP and MYSQL health check types, respectively for these three type of services. We should let more types of service in Nacos such as REDIS, MONGODB, MQ etc. and provide a way for user to implement their health checkers.

**Comment by XCXCXCXCX** [comment]
> Nacos currently supports TCP, HTTP and MYSQL health check types, respectively for these three type of services. We should let more types of service in Nacos such as REDIS, MONGODB, MQ etc. and provide a way for user to implement their health checkers.

hi, I think that in any case we need to remodel the nacos server (eg.SPI), it seems that this is not very elegant, do you think there is a better way to provide extensions?
