### ISSUE TITLE
The official recommended podcast has wrong characters

### ISSUE THREAD

**Issue by TianLuhua** [alibaba/nacos#3594]
Blog Address:
https://nacos.io/en-us/blog/nacos0.9.0.htm

![1597300382(1)](https://user-images.githubusercontent.com/13152339/90102139-912ee000-dd72-11ea-9d1c-706a4916d5d6.png)

**Comment by KomachiSion** [comment]
welcome to fix it.

**Comment by PeineLiang** [comment]
Please assign to me

**Comment by KomachiSion** [comment]
Fixed by https://github.com/nacos-group/nacos-group.github.io/pull/111
