### ISSUE TITLE
Class NamingFactory doesn't support createNaming method?

### ISSUE THREAD

**Issue by johnnywww** [alibaba/nacos#36]
I write demo through [nacos's sdk](https://nacos.io/zh-cn/docs/sdk.html). The example code like below.
`NamingService naming = NamingFactory.createNaming(System.getProperty("serveAddr"));
naming.registerInstance("nacos.test.3", "11.11.11.11", 8888, "TEST1");`
But class NamingFactory doesn't support this method, it only has createNamingService method.

**Comment by yangyshdan** [comment]
There is a typo in the doc, the correct method name is createNamingService. Plan to fix it in milestone 0.6. @xuechaos
