### ISSUE TITLE
集群单点模式下服务注册不成功

### ISSUE THREAD

**Issue by janzhou123** [alibaba/nacos#360]
# 报告错误

使用nacos-server-0.5.0.tar.gz包，standalone模式下配置正常，服务注册正常，服务发现正常；当修改到cluster模式单点本机，配置入库正常，但是服务无法注册成功。
### nacos.log显示报错
2018-11-28 14:36:23,976 ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [/nacos] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: No leader at present] with root cause
![image](https://user-images.githubusercontent.com/6056349/49135225-0cdbc580-f321-11e8-9a84-5d7c343ab437.png)

### 客户端报错
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([10.36.1.48:8848]) tried

### cluster.conf
![image](https://user-images.githubusercontent.com/6056349/49135365-71972000-f321-11e8-953e-c14f2c706890.png)

**Comment by janzhou123** [comment]
有亲 告诉 集群模式最小三节点；

**Comment by janzhou123** [comment]
开启2个节点的时候可以服务注册成功。
当开启第三个节点的时候，第三个节点后台报错。
![image](https://user-images.githubusercontent.com/6056349/49140562-87134680-f32f-11e8-87df-ce42d495e571.png)

**Comment by nkorange** [comment]
第三台的cluster.conf文件内容贴一下

**Comment by nanamikon** [comment]
这个错误我有遇过， 应该是获取本机ip的时候出问题了，  用的是InetAddress.getLocalHost()这个方法， 他会通过本机的hostname来获取ip地址，  编辑一下 /etc/hosts ,  将本机hostname和你配置的本机内网ip加上去应该就可以了

**Comment by janzhou123** [comment]
> 第三台的cluster.conf文件内容贴一下

![image](https://user-images.githubusercontent.com/6056349/49193645-b8852400-f3ba-11e8-9b34-b2b4574ec99e.png)

**Comment by nkorange** [comment]
@janzhou123 参考 @nanamikon 给的方法处理下看看
