### ISSUE TITLE
the autoclear day  in the historyConfig page not match the backend value

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3602]
**Describe the bug**
the autoclear day in the historyConfig page not match the backend value, the default day is backend is 30, but the value in can be config with the key 'nacos.config.retention.days', if the value config to another value, the html's value is not matched

![image](https://user-images.githubusercontent.com/22524871/90135953-036ce800-dda6-11ea-85f3-4b6c049a9d42.png)

**Comment by KomachiSion** [comment]
In my opinion, the retention days is not very necessary to show in console. And provide a API to get the retention days is too wasted.

I think we can remove it from console.

If we need to show it and need to read from server. I suggest that add one `getAllConfig` API, console can get one and cache in browsers.

**Comment by horizonzy** [comment]
> In my opinion, the retention days is not very necessary to show in console. And provide a API to get the retention days is too wasted.
> 
> I think we can remove it from console.
> 
> If we need to show it and need to read from server. I suggest that add one `getAllConfig` API, console can get one and cache in browsers.

if we remove it console, we should apply a another way to tell user the historyConfig remain day. user need know the thing that histroryConfig will auto clear, or if user don't this case, he think all the historyConfig can recover, but in fact, the old historyConfig already clear

**Comment by KomachiSion** [comment]
Admin document should describe this feature, and provide how to modified the retention days.
