### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by jinchaoxiang** [alibaba/nacos#3604]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

我使用nacos用户做配置项配置 
当点击修改按钮时，平台会自动退出到登录页
我发现/nacos/v1/cs/configs这个api报401状态
这个需要怎么调整系统才能使nacos用户可以修改 
以前就是用这个用户修改的
### Describe what you expected to happen

用户nacos正常修改配置
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos1.0.0

**Comment by Maijh97** [comment]
nacos server 是1.0.0 版本？ @jinchaoxiang j

**Comment by KomachiSion** [comment]
1.0.0 version is too old. Can you use 1.3.2 retry?

**Comment by jinchaoxiang** [comment]
请问如果升级到nacos1.3.2 原来的数据兼容高版本nacos吗 我的数据存储使用的是k8s 挂载目录的方式 没有用mysql

**Comment by KomachiSion** [comment]
理论上支持，建议最好备份好一下再升级下。

**Comment by KomachiSion** [comment]
No response from author, We think it has been fixed in new version. Close issue.
