### ISSUE TITLE
nacos注册中心读取加载feign配置失败问题

### ISSUE THREAD

**Issue by robin536180** [alibaba/nacos#3606]
我得注册中心是eureka, 本地的yml文件读取feign client配置信息可以正常启动; 但是换成nacos之后，读取feign client的配置信息失败，导致项目无法启动，FeignClient代码如下：

@FeignClient(name = "SimpleAnalysisFeignClient", url = "${nlp.analysis.simple}")
public interface SimpleAnalysisFeignClient {

    @PostMapping(value = GlobalConstant.SIMPLE_ANALYSIS_URL, consumes = MediaType.APPLICATION_JSON_VALUE)
    SimpleAnalysisResponse simpleAnalysis(@RequestBody SimpleAnalysisRequest simpleAnalysisRequest);

}

报错信息如下：
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'com.unioncloud.common.feignclient.SimpleAnalysisFeignClient' defined in null: Could not resolve placeholder 'nlp.analysis.simple' in value "http://${nlp.analysis.simple}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'nlp.analysis.simple' in value "http://${nlp.analysis.simple}"

然后springboot 1.5.9.Release， spring cloud Edgware.SR3, jdk 1.8， nacos server 1.3.1

请问如何解决？

**Comment by ljyhust** [comment]
配置中心也是nacos吗？如果只是用注册中心，只需要依赖spring-cloud-starter-alibaba-nacos-discovery，不需要依赖config。cloud版本需要注意兼容，建议到  spring cloud alibaba 上去看看

**Comment by robin536180** [comment]
> 配置中心也是nacos吗？如果只是用注册中心，只需要依赖spring-cloud-starter-alibaba-nacos-discovery，不需要依赖config。cloud版本需要注意兼容，建议到 spring cloud alibaba 上去看看

配置中心是eureka, 注册中心是nacos，现在不是依赖版本的问题，而是启动的时候feign client中要去读取application.yml文件中的url地址，没读取到，所以就报错了

**Comment by ljyhust** [comment]
有没有试过把url配置放到  bootstrap.yml配置中  或者 业务类创建时延迟@Lazy依赖 FeignClient？

**Comment by robin536180** [comment]
> 有没有试过把url配置放到 bootstrap.yml配置中 或者 业务类创建时延迟@lazy依赖 FeignClient？

试过把url放到bootstrap.yml中，feignclient不知道是否支持延迟加载，还没试过

**Comment by CaiJian0834** [comment]
如果nacos是以@NacosPropertySources的方式配置dataId，添加@EnableNacosConfig（要在@EnableFeignClients上面）
如果是配置文件的方式配置dataId，则开启预加载：nacos.config.bootstrap.enable=true或nacos.config.bootstrap.log-enable
