### ISSUE TITLE
配置管理导入已经存在的配置覆盖不了旧的配置

### ISSUE THREAD

**Issue by zscboy** [alibaba/nacos#3617]
nacos服务器版本：nacos-server-1.3.2
操作系统：centos 7

![image](https://user-images.githubusercontent.com/8179656/90392170-f7906700-e0c0-11ea-8a68-d6366fc8204f.png)

我就有是疑惑，选项里面有覆盖，为何操作的是是insert。如果不想覆盖，那就去掉覆盖选项，或者需要覆盖，那就改成update.

**Comment by chuntaojun** [comment]
使用内嵌数据库还是外置数据库存储

**Comment by KeRan213539** [comment]
根据上面的信息无法复现,请提供详细复现步骤

**Comment by KeRan213539** [comment]
经测试内嵌数据库下确实存在该问题

**Comment by KomachiSion** [comment]
@KeRan213539 please description reason and try to fix it.
