### ISSUE TITLE
https://nacos.io should be updated with the nacos release version updated. And it should be better.

### ISSUE THREAD

**Issue by Tsingshen** [alibaba/nacos#3625]
Compared with the other opensource software, the docs of nacos is to simple,  and the docs content are not updated with the version of nacos release version. Take the example below,

https://rancher2.docs.rancher.cn/
https://docs.gitlab.com/

I use the docs of the https://nacos.io build of my own nacos-server, and I found this problem,  and I searched online, and finally run the docker-compose with standalone-mysql-8.yaml. Also thanks ali.

**Comment by KomachiSion** [comment]
Yes, I agree the doc need to be updated and maintained. But it also need time to enhance. And we also need the help from community to build the doc content.

**Comment by KomachiSion** [comment]
Refer to #3073

**Comment by Tsingshen** [comment]
Ok, if your can realize the problem, my issue will close, and thank your again.
