### ISSUE TITLE
ClientWorker  can‘t use actuator  shutdown

### ISSUE THREAD

**Issue by maqiang** [alibaba/nacos#3627]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
Please describe your problem or feature in issue description clearly. Otherwise the template will have no effect.

**Comment by chuntaojun** [comment]
Yd that's what Springcloud-Alibaba needs to do
