### ISSUE TITLE
in nodejs, pm2 start ./bin/www, use nacos discovery

### ISSUE THREAD

**Issue by CurryChou777** [alibaba/nacos#3632]
**Failed to register with Nacos service in nodejs**
1. In the `bin / www` file, use the registration method of Nacos official website
![image](https://user-images.githubusercontent.com/22877154/90583614-2dd5ff80-e203-11ea-9f91-396020ec1d78.png)
2. In the development mode, you can directly use `npm  run start` to start
3. Once started, the service can be found in the Nacos registry
4. However, when pm2 mode is used, the above registration code remains unchanged. The startup mode is changed to `pm2 run pm2. json`. The JSON file contents are as follows
```
{
  "script": "./bin/www",
  "instances": "1",
  "env": {
    "NODE_ENV": "development"
  },
  "env_production": {
    "NODE_ENV": "production"
  }
}
```
5. pm2 start result is`errored`
View progress info，The error path is `bin/www`
![image](https://user-images.githubusercontent.com/22877154/90584406-1bf55c00-e205-11ea-814e-9cfe09bf4cea.png)
Error log
![image](https://user-images.githubusercontent.com/22877154/90584464-3deede80-e205-11ea-8cad-27bc4c3cc575.png)
6. If the service registration code is removed, pm2 starts normally

**Nodejs中使用nacos服务注册失败**
1. 在`bin/www`文件下，使用nacos官网注册方式
![image](https://user-images.githubusercontent.com/22877154/90583614-2dd5ff80-e203-11ea-9f91-396020ec1d78.png)
2. 开发模式下，直接使用`npm run start` 启动
3. 启动后，在nacos注册中心可以找到该服务
4. 但是使用pm2方式时，上述注册代码不变。启动方式变为`pm2 run pm2.json`,其中json文件内容如下
```
{
  "script": "./bin/www",
  "instances": "1",
  "env": {
    "NODE_ENV": "development"
  },
  "env_production": {
    "NODE_ENV": "production"
  }
}
```
5. pm2启动结果为`errored`
查看进程内容，提示错误路径为`bin/www`
![image](https://user-images.githubusercontent.com/22877154/90584406-1bf55c00-e205-11ea-814e-9cfe09bf4cea.png)
错误日志
![image](https://user-images.githubusercontent.com/22877154/90584464-3deede80-e205-11ea-8cad-27bc4c3cc575.png)
6. 去掉服务注册代码则pm2启动正常

**期望行为**
希望能够像dev启动中一样正常注册服务

**Expected behavior**
I hope to be able to register the service as normal as in dev startup

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
I suggest that you also open an issue to https://github.com/nacos-group/nacos-sdk-nodejs

**Comment by CurryChou777** [comment]
> I suggest that you also open an issue to https://github.com/nacos-group/nacos-sdk-nodejs

Now there is no valuable log printing

**Comment by CurryChou777** [comment]
测试发现为服务问题，nacos正常
