### ISSUE TITLE
1.3.1版本内置数据源集群会出现两个leader

### ISSUE THREAD

**Issue by ningmeng777** [alibaba/nacos#3641]
如图，在embedded集群服务器运行一段时间就会出现这种脑裂现象。
![1597825583(1)](https://user-images.githubusercontent.com/54097058/90611706-a8ba0d00-e239-11ea-85a8-e66dde96ec7f.jpg)
![1597825717(1)](https://user-images.githubusercontent.com/54097058/90611713-abb4fd80-e239-11ea-9c76-69f38060393d.jpg)

**Comment by KomachiSion** [comment]
duplicate with #3384

**Comment by ningmeng777** [comment]
这个会修复吗？
