### ISSUE TITLE
'bad variable name' error when startup server

### ISSUE THREAD

**Issue by IcebergXTY** [alibaba/nacos#3643]
**Describe the bug**
![image](https://user-images.githubusercontent.com/15325243/90706005-ca150a80-e2c6-11ea-8fae-4508c1ffc9a7.png)

**Expected behavior**
Startup success

**Acutally behavior**
Report error

**How to Reproduce**
1. download the nacos-server-1.3.2.tar.gz
2. run the startup.sh

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 with GUI, in Vmware Workstation 15 Pro 15.5.6（The host machine is windows 10 1909）
 - Version: nacos-server 1.3.2 and nacos-server 1.2.1

**Comment by IcebergXTY** [comment]
Oh！I remove the blank space in the folder name，it started.......

**Comment by KomachiSion** [comment]
> Oh！I remove the blank space in the folder name，it started.......

Yes, the dir name has blank, so the line cmd execute `export /Program/nacos` and then execute `1.3.2/single`.
