### ISSUE TITLE
seata注册到nacos指定组下，但nacos管理平台列表仍然显示默认组

### ISSUE THREAD

**Issue by wpt191** [alibaba/nacos#3645]
环境描述：
seata_server:1.3.0
nacos_server:1.3.2

问题详情：
seata注册到nacos指定组下，但nacos管理平台仍然显示默认组
（代码中注册到CBI_SITE_GROUP,但列表显示：DEFAULT_GROUP，请看截图）

截图数据：
![image](https://user-images.githubusercontent.com/62193643/90710062-292b4d00-e2d0-11ea-9645-65679a540c44.png)
![image](https://user-images.githubusercontent.com/62193643/90710073-2fb9c480-e2d0-11ea-9cf2-720b84020b67.png)

**Comment by KomachiSion** [comment]
It might be seata‘s problem, I see other server can register to target cluster.

**Comment by wpt191** [comment]
seata say: let me to as nacos.
nacos say: It might be seata‘s problem.
i:  baby has a hard time

thank you！！！

**Comment by KomachiSion** [comment]
> seata say: let me to as nacos.
> nacos say: It might be seata‘s problem.
> i: baby has a hard time
> 
> thank you！！！

Alright, From your information, I think nacos' feature has no problem. There may be some problems in usage. 
Can you provide an simple demo program in github so that we can locate the issue reason.

**Comment by KomachiSion** [comment]
@wpt191 , Any process?

**Comment by wpt191** [comment]
您好，问题已经找到，seata问题，seata1.2存在问题，升级1.3之后，正常，感谢
