### ISSUE TITLE
Nodejs-sdk support

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#365]
## Nodejs program dynamic configuration management requirements
- The foreground code sends cdn and the version number is sent to Nacos. Each time you send a version, you only need to change the Nacos to modify the version number and push it down to complete the front-end release. No need to rely on the backend at all
- Abstract the copy, announcement to a configuration file in the background. Change and change at any time
- Abstract layouts, styles into json structures, and even code snippets. A configuration push, dynamic modification.
## Nodejs service discovery requirements
- The portal Nodejs service needs to call the backend microservice to complete the business logic

So we need Nacos Eco Support nodejs language. If you have similar nodejs scenes and needs welcome reply exchange ~

## Nodejs程序动态配置管理需求
- 前台代码发cdn，版本号发到Nacos。每次发一个版本只需改一下Nacos上修改一下版本号动态推下去即可完成前端发布。完全不用依赖后端
- 将文案，公告抽象到后台一个配置文件里面。改一改，随时变化
- 将布局，风格抽象成json结构，甚至代码片段。  一个配置推送，动态修改。  
## Nodejs服务发现需求
- 入口Nodejs服务需要调用后端微服务，完成业务逻辑

因此我们需要Nacos生态支持nodejs语言。 如果大家有类似的nodejs场景和需求欢迎回复交流~

**Comment by gumutianqi** [comment]
Node.js 也需要 Nacos 的服务发现和配置管理功能，这样再通过NoCos 的DNS服务打通前端和后端

**Comment by yanlinly** [comment]
已支持，欢迎使用 
https://github.com/acm-group/acm-sdk-nodejs

**Comment by CurryChou777** [comment]
> Node.js 也需要 Nacos 的服务发现和配置管理功能，这样再通过NoCos 的DNS服务打通前端和后端

你好，请问在nodejs中使用nacos服务注册时是怎么做的？我在开发模式中使用注册服务能成功，但是使用pm2启动时则不能成功，有什么区别吗

**Comment by CurryChou777** [comment]
@yanlinly
