### ISSUE TITLE
集群状态下，集群机器间有CLOSE_WAIT状态

### ISSUE THREAD

**Issue by greatle** [alibaba/nacos#3651]
环境：
     linux:  centos7.5.1804
     nacos:  1.2.1
     mysql：5.7
     nginx： 1.16.1
1. 配置nacos集群模式，数据存储于myql中
2. 在三台机器中启动nacos
3. 配置nginx，反向代理到三台nacos集群
4. 任意启动一个服务，注册到nacos集群中，服务注册地址为nginx地址，也可以不采用nginx，直接注册到三台nacos中的任何一台
5. 登录nacos控制台，可以看见nacos集群正常，一个节点为leader，另外两个节点为follower；需要注册的服务也正常注册成功
6. 等待1分钟左右，ssh查看nacos集群机器，可以看到集群机器间有CLOSE_WAIT状态存在，该CLOSE_WAIT状态连接是leader和follower之间的连接，非注册服务和nacos服务间的连接；并且该CLOSE_WAIT主要存在follower机器上，leader机器偶尔也会出现，而且该CLOSE_WAIT状态连接似乎一直不能够正确关闭（等待2天了，连接还在，因为follower端连接占用随机端口没有变，所以应该是同一个连接）

**Comment by KomachiSion** [comment]
Can you retry to use 1.3.2? If new version still have this problem. Please notify us in issue.

**Comment by greatle** [comment]
测试了nacos1.3.2版本，CLOSE_WAIT状态任然有，只是经过一段时间后可以回收了

**Comment by KomachiSion** [comment]
我测试也发现的确有，自动回收是因为设置的时间到了，这边会再排查下，看下是不是有什么地方没有关闭连接导致的。
