### ISSUE TITLE
dubbo registry address  problem  use nacos （dubbo 使用nacos作为注册中心，注册地址偶发性异常）

### ISSUE THREAD

**Issue by smallpigchina** [alibaba/nacos#3657]
## Issue Description
dubbo 使用nacos作为注册中心，在dubbo项目启动注册时偶然会 提示 Invalid url, password without username!，
发生这种情况多启动几次即恢复正常。
项目pom依赖如下：
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>2.7.7</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-registry-nacos</artifactId>
			<version>2.7.7</version>
			<exclusions>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.dubbo</groupId>
					<artifactId>dubbo-remoting-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
application.yml:
dubbo:
  consumer:
    connections: 20
    timeout: 4000
  provider:
    connections: 30
    timeout: 3000
    threads: 30
  protocol:
    name: dubbo # Dubbo Protocol
    host: 192.168.10.146
    port: -1 # Random port
  scan:
    base-packages: xxx
  registry:
    username: nacos
    password: nacos
    address: nacos://127.0.0.1:8848
    file: "@dubbo.registry.file@"
    timeout: 5000
    parameters:
      namespace: ${project_name}
 

### Tell us your environment
jdk1.8、win10

**Comment by KomachiSion** [comment]
Can you provide more error stack log? I search from all the source code and could not find this error of `Invalid url, password without username!`

**Comment by KomachiSion** [comment]
No response more than 7 days and the information is not enough to reproduce and find problem. So close issue.
