### ISSUE TITLE
findbugs-maven-plugin version

### ISSUE THREAD

**Issue by u-ian** [alibaba/nacos#366]
0.5的版本
maven中findbugs-maven-plugin的依赖version没有3.0.1
拉取的目前是3.0.4

**Comment by xuechaos** [comment]
@u-ian 你好  是这个没有这个版本3.0.1 findbug么？
目前版本的确有个问题，是在reporting的里边的findbugs-maven-plugin版本和外部是不匹配的。这个0.6版本会修复，你说的是这个问题么？

**Comment by u-ian** [comment]
@xuechaos 嗯,是的;

**Comment by xuechaos** [comment]
@u-ian 👍
