### ISSUE TITLE
[Too many files with unapproved license] problems when  running mvn command

### ISSUE THREAD

**Issue by richard1230** [alibaba/nacos#3666]
when I run the commands as follows：
`$mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U`
error appears:

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.alibaba.nacos:nacos-console:jar:1.3.2
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 121, column 29
[WARNING] 'build.plugins.plugin.version' for org.springframework.boot:spring-boot-maven-plugin is missing. @ line 132, column 29
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.14
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 14
[INFO] os.detected.classifier: osx-x86_64
[WARNING] The project com.alibaba.nacos:nacos-all:pom:1.3.2 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Alibaba NACOS 1.3.2                                                [pom]
[INFO] nacos-api 1.3.2                                                    [jar]
[INFO] nacos-common 1.3.2                                                 [jar]
[INFO] nacos-consistency 1.3.2                                            [jar]
[INFO] nacos-core 1.3.2                                                   [jar]
[INFO] nacos-config 1.3.2                                                 [jar]
[INFO] nacos-cmdb 1.3.2                                                   [jar]
[INFO] nacos-naming 1.3.2                                                 [jar]
[INFO] nacos-address 1.3.2                                                [jar]
[INFO] nacos-client 1.3.2                                                 [jar]
[INFO] nacos-istio 1.3.2                                                  [jar]
[INFO] nacos-console 1.3.2                                                [jar]
[INFO] nacos-test 1.3.2                                                   [jar]
[INFO] nacos-example 1.3.2                                                [jar]
[INFO] nacos-distribution 1.3.2                                           [pom]
[INFO] 
[INFO] --------------------< com.alibaba.nacos:nacos-all >---------------------
[INFO] Building Alibaba NACOS 1.3.2 1.3.2                                [1/15]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nacos-all ---
[INFO] Deleting /Users/mac/IdeaProjects/nacos/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-ban-circular-dependencies) @ nacos-all ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.1:check (validate) @ nacos-all ---
[INFO] 开始检查……
检查完成。
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.8:prepare-agent (default-prepare-agent) @ nacos-all ---
[INFO] argLine set to -javaagent:/Users/mac/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/Users/mac/IdeaProjects/nacos/target/jacoco.exec
[INFO] 
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ nacos-all ---
[INFO] Skipping javadoc generation
[INFO] 
[INFO] >>> maven-source-plugin:3.0.1:jar (attach-sources) > generate-sources @ nacos-all >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-ban-circular-dependencies) @ nacos-all ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.1:check (validate) @ nacos-all ---
[INFO] 开始检查……
检查完成。
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.8:prepare-agent (default-prepare-agent) @ nacos-all ---
[INFO] argLine set to -javaagent:/Users/mac/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/Users/mac/IdeaProjects/nacos/target/jacoco.exec
[INFO] 
[INFO] <<< maven-source-plugin:3.0.1:jar (attach-sources) < generate-sources @ nacos-all <<<
[INFO] 
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar (attach-sources) @ nacos-all ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.8:prepare-agent-integration (default-prepare-agent-integration) @ nacos-all ---
[INFO] failsafeArgLine set to -javaagent:/Users/mac/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/Users/mac/IdeaProjects/nacos/target/jacoco-it.exec
[INFO] 
[INFO] >>> maven-pmd-plugin:3.8:check (default) > :pmd @ nacos-all >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:pmd (pmd) @ nacos-all ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.8:check (default) < :pmd @ nacos-all <<<
[INFO] 
[INFO] 
[INFO] --- maven-pmd-plugin:3.8:check (default) @ nacos-all ---
[INFO] 
[INFO] --- apache-rat-plugin:0.12:check (default) @ nacos-all ---
[INFO] Enabled default license matchers.
[INFO] Will parse SCM ignores for exclusions...
[INFO] Parsing exclusions from /Users/mac/IdeaProjects/nacos/.gitignore
[INFO] Finished adding exclusions from SCM ignore files.
[INFO] 87 implicit excludes (use -debug for more details).
[INFO] Exclude: .editorconfig
[INFO] Exclude: .travis.yml
[INFO] Exclude: CONTRIBUTING.md
[INFO] Exclude: CODE_OF_CONDUCT.md
[INFO] Exclude: CHANGELOG.md
[INFO] Exclude: style/codeStyle.md
[INFO] Exclude: REPORTING-BUGS.md
[INFO] Exclude: README.md
[INFO] Exclude: .github/**/*
[INFO] Exclude: doc/*
[INFO] Exclude: derby.log
[INFO] Exclude: logs/*
[INFO] Exclude: src/main/resources/static/**
[INFO] Exclude: **/istio/model/**
[INFO] Exclude: **/consistency/entity/**
[INFO] Exclude: **/*.txt
[INFO] Exclude: **/*.factories
[INFO] 8 resources included (use -debug for more details)
[INFO] Rat check: Summary over all files. Unapproved: 1, unknown: 1, generated: 0, approved: 3 licenses.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Alibaba NACOS 1.3.2 1.3.2:
[INFO] 
[INFO] Alibaba NACOS 1.3.2 ................................ FAILURE [  3.135 s]
[INFO] nacos-api 1.3.2 .................................... SKIPPED
[INFO] nacos-common 1.3.2 ................................. SKIPPED
[INFO] nacos-consistency 1.3.2 ............................ SKIPPED
[INFO] nacos-core 1.3.2 ................................... SKIPPED
[INFO] nacos-config 1.3.2 ................................. SKIPPED
[INFO] nacos-cmdb 1.3.2 ................................... SKIPPED
[INFO] nacos-naming 1.3.2 ................................. SKIPPED
[INFO] nacos-address 1.3.2 ................................ SKIPPED
[INFO] nacos-client 1.3.2 ................................. SKIPPED
[INFO] nacos-istio 1.3.2 .................................. SKIPPED
[INFO] nacos-console 1.3.2 ................................ SKIPPED
[INFO] nacos-test 1.3.2 ................................... SKIPPED
[INFO] nacos-example 1.3.2 ................................ SKIPPED
[INFO] nacos-distribution 1.3.2 ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.605 s
[INFO] Finished at: 2020-08-22T17:40:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project nacos-all: Too many files with unapproved license: 1 See RAT report in: /Users/mac/IdeaProjects/nacos/target/rat.txt -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Hey, I would except it to behave building success but it behaves  error;
is that a problem about documents or am I missing some information,
am I not understanding it correctly is my assumption wrong

**Comment by gleemanx** [comment]
哈哈 这debug信息明显是个中国人🇨🇳，然而大家都在用英文交流
