### ISSUE TITLE
nacos1.3.2 is used in conjunction with spring boot 2.1.5.RELEASE Unable to complete automatic refresh.

### ISSUE THREAD

**Issue by hjnjmjkj** [alibaba/nacos#3667]
**Describe the bug**
nacos1.3.2 is used in conjunction with spring boot 2.1.5.RELEASE
@NacosValue(value ="${hello.name:world}",autoRefreshed = true)
Unable to complete automatic refresh.

**Expected behavior**
Auto Refresh

**Acutally behavior**
Unable to complete automatic refresh.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Version [e.g. nacos-server 1.3.2, nacos-client 1.3.2]
 - Module [e.g. config]
 - SDK [e.g. original, nacos-config-spring-boot-starter 0.2.7,jdk8]

**Additional context**
 <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

nacos:
  config:
    server-addr: localhost:8848
    maxRetry: 3
    configLongPollTimeout: 10000
    configRetryTime: 3
    autoRefresh: true
    enableRemoteSyncConfig: true
    remoteFirst: true
    username: nacos
    password: nacos

**Comment by neighbor-uncleWang** [comment]
Hello, I am a novice, I am very interested in this question, can I help you?

**Comment by hjnjmjkj** [comment]
> Hello, I am a novice, I am very interested in this question, can I help you?

of course

**Comment by neighbor-uncleWang** [comment]
Ok，I will start my work

**Comment by neighbor-uncleWang** [comment]
> > Hello, I am a novice, I am very interested in this question, can I help you?
> 
> of course
ok，I will start my work

**Comment by neighbor-uncleWang** [comment]
Sorry @hjnjmjkj , when nacos1.3.2 is used together with spring boot 2.1.5.RELEASE, I did not find this problem exists. Has it been repaired? This is my example:https://github.com/neighbor-uncleWang/nacosConfigDemo

**Comment by hjnjmjkj** [comment]
> Sorry @hjnjmjkj , when nacos1.3.2 is used together with spring boot 2.1.5.RELEASE, I did not find this problem exists. Has it been repaired? This is my example:https://github.com/neighbor-uncleWang/nacosConfigDemo

Thank you very much, I just changed the nacos client to version 1.2.0. It should be nacos-config-spring-boot-starter 0.2.7 is not compatible with nacos client 1.3.2 client, although I added com.alibaba.nacos.client.utils.StringUtils.isBlank method.
