### ISSUE TITLE
I hope that the granularity of control permissions is group and dataid, but I cannot control group permissions individually.

### ISSUE THREAD

**Issue by syapollo** [alibaba/nacos#3669]
I hope that the granularity of control permissions is group and dataid, but I cannot control group permissions individually.

Describe the bug
I hope that the granularity of control permissions is group and dataid, but I cannot Authentication group permissions individually.
I found that there is a problem with the ResourceParser implementation class. After I modify it and add database data, I can Authentication the group normally. I hope I can submit code to fix this bug.

Expected behavior
I configure a request with group like this
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: mygroup
		
Authentication the group

Acutally behavior
can’t Authentication the group

How to Reproduce

Configure the nacos registration server on the client,Configure permissions in the database
Start the client
See error
Desktop (please complete the following information):

OS: [e.g. Centos]
Version [e.g. nacos-server 1.3.0, nacos-client 1.2.1]
Module [e.g. naming/config]
SDK [e.g. original, spring-cloud-starter-alibaba-nacos-discovery]

**Comment by KomachiSion** [comment]
Currently, the permissions only can control namespace level, can't support group or more fine granularity.

**Comment by syapollo** [comment]
I may be mistaken. This is not a BUG, but a requirement. I want to add code in this area. Do I need to change the problem type ?

**Comment by KomachiSion** [comment]
requirement please use feature requires template. Not use bug report template.

**Comment by syapollo** [comment]
OK
