### ISSUE TITLE
一个spring boot应用多注册中心依赖情况下的spring.autoconfigure.exclude配置问题

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#3674]
场景： 一个应用引入了nacos和zookeeper的注册中心依赖；这个时候如果应用只用zookeeper作为注册中心。那么spring.autoconfigure.exclude配置排除掉nacos自动装配类的时候，源码spring.factories中的所有自动装配的类都要排除吗还是说只需要排除某个特定的类就行。
![aaa](https://user-images.githubusercontent.com/33769220/91027667-f9ad7500-e62e-11ea-974a-e0c75c6cd778.png)

**Comment by KomachiSion** [comment]
`spring.cloud.nacos.discovery.enable=false` 不能使用吗？

**Comment by KomachiSion** [comment]
如果有spring-cloud的使用问题，建议提issue到spring-cloud-alibaba比较好，nacos社区只能简单回答一下使用上的问题

**Comment by HelloHaiNG** [comment]
> `spring.cloud.nacos.discovery.enable=false` 不能使用吗？

可以使用，但是想用spring.autoconfigure.exclude这种方式去解决，不去更改原生的配置

**Comment by HelloHaiNG** [comment]
> 如果有spring-cloud的使用问题，建议提issue到spring-cloud-alibaba比较好，nacos社区只能简单回答一下使用上的问题

好的，感谢
