### ISSUE TITLE
I hope that the granularity of control permissions is group and dataid

### ISSUE THREAD

**Issue by syapollo** [alibaba/nacos#3675]
**Is your feature request related to a problem? Please describe.**
I hope that the granularity of control permissions is group and dataid, but I cannot Authentication group permissions individually.

**Describe the solution you'd like**
I agree with the article on the url address below, and plan to make some additions based on this scheme
https://nacos.io/zh-cn/blog/nacos%201.2.0%20guide.html

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by KomachiSion** [comment]
After nacos 2.1, users can develop their own auth plugin, if want to control in group or dataid, you can develop your own plugin to do.
