### ISSUE TITLE
nacos1.3.1 集群配置节点状态异常

### ISSUE THREAD

**Issue by 2227324689** [alibaba/nacos#3680]
**Describe the bug**
Nacos1.3.1版本
采用三台机器部署集群，分别是
192.168.216.128:8848
192.168.216.129:8848
192.168.216.130:8848
按照官方文档部署集群，（3台机器连接同一个nacos数据库）启动服务之后，在集群管理菜单中显示节点列表的状态正常。
于是，我想看看leader动态选举的实现。
**Expected behavior**
希望把leader节点下线之后触发自动选举
**Acutally behavior**
停止掉leader服务节点，发现服务状态并没有发起选举。并且在leader下线的情况下，我仍然可以在剩余两台follower节点中创建配置数据。

**测试2**
我开始以为是因为三个节点都连接到同一个数据库导致的问题，于是我把三个节点的数据库分开，也就是三个节点分别连接到不同的数据库节点。然后再启动集群就发现节点状态不对了。如下图所示
![image](https://user-images.githubusercontent.com/52684867/91128224-5e71d980-e6da-11ea-9e6e-e48eb424c67f.png)

![image](https://user-images.githubusercontent.com/52684867/91128235-65005100-e6da-11ea-93a7-90778a4eb979.png)

**Comment by KomachiSion** [comment]
duplicate with #3384
