### ISSUE TITLE
还是老问题，Nacos节点崩溃后，会导致部分服务节点不下线。

### ISSUE THREAD

**Issue by yyt6200** [alibaba/nacos#3681]
这个问题反馈过多次了，Nacos版本1.2.1,服务运行环境是swarm集群。希望项目组重视下我反馈的这个问题，不是一次两次了，发生过很多次这样的情况。
另外希望科普下Nacos的宕机原因要怎么排查，按理说Nacos不应该这么不稳定，什么原因会导致Nacos的宕机？

**Comment by KomachiSion** [comment]
升版本再试试吧，你这个问题看过好几次了，根据上次的最新反馈，不是nacos节点崩溃，而是你swarm崩溃，nacos重启之后无法连接数据库。导致一直无法提供服务。

**Comment by KomachiSion** [comment]
排查当然要基于日志，先把出现问题前后时间的日志都过一遍，找到崩溃时间前，究竟有哪些异常，gc日志看看有没有fullgc存在等等。

**Comment by yyt6200** [comment]
好的，谢谢，我升级下版本再观察

**Comment by yyt6200** [comment]
大佬，昨天又发生这个情况了，26号上午10点50左右崩溃的，26号所有日志我都看了一遍了，但是看不出1234，烦请大佬帮忙过目下，我把26号的日志贴下.同时我这边也打算升级到最新的版本了，如果能找出这个潜在的问题那是最好了！
![26-214节点](https://user-images.githubusercontent.com/44914868/91374987-11ae1000-e84c-11ea-856d-9b139249422b.png)
[config-dump.log](https://github.com/alibaba/nacos/files/5133582/config-dump.log)
[config-fatal.log](https://github.com/alibaba/nacos/files/5133584/config-fatal.log)
[config-memory.log](https://github.com/alibaba/nacos/files/5133585/config-memory.log)
[config-pull-check.log](https://github.com/alibaba/nacos/files/5133586/config-pull-check.log)
[config-server.log](https://github.com/alibaba/nacos/files/5133588/config-server.log)
[config-trace.log](https://github.com/alibaba/nacos/files/5133589/config-trace.log)
[nacos_gc.log](https://github.com/alibaba/nacos/files/5133590/nacos_gc.log)
[naming-performance.log](https://github.com/alibaba/nacos/files/5133592/naming-performance.log)
[naming-server.log](https://github.com/alibaba/nacos/files/5133593/naming-server.log)
[start.out.log](https://github.com/alibaba/nacos/files/5133594/start.out.log)
core-auth.log和nacos.log文件比较大，需要传么

**Comment by KomachiSion** [comment]
建议了解一下MSE，在nacos官网的导航栏有连接。

关于自建环境问题，干脆把所有日志一起打包上传算了，有有社区有没有人愿意排查下。

**Comment by KomachiSion** [comment]
@yyt6200 升级之后还有出现吗？ 出现的时候麻烦把所有日志一起打包上传。

**Comment by yyt6200** [comment]
升级之后还出现过一次，我下次把日志保留下，谢谢

**Comment by KomachiSion** [comment]
@yyt6200 还出现过问题吗？

**Comment by yyt6200** [comment]
> @yyt6200 还出现过问题吗？

巧了，今天还真出问题了，本来整理文档打算上来提问的，今天有紧急事情要处理还在加班中。等明天空的时候我再把今天出现的问题详细描述下，升级1.3.2后比之前稳定了，但是某种特定的问题触发后会让Nacos变的不正常。具体等我明天把整理好的文档传上来后再向您请教

**Comment by yyt6200** [comment]
@KomachiSion 你好，我反馈下前天碰到的问题。
首先我还是先简述下环境：
Nacos版本：1.3.2；集群数：3；分布在三台机器上；172.18.51.214、172.18.51.215、172.18.51.216；
微服务运行环境：swarm集群；分布在三台机器上；172.18.51.214、172.18.51.215、172.18.51.216；
数据库：部署在另外一个网段上192.168.9.157上；
Nginx:172.18.51.218;代理了nacos集群，做了负载均衡；应用的注册地址为：172.18.51.218:8848
产生问题的经过：51.215服务器上docker某个容器的网络被调整了，bridge被调整成192.168段了，导致21.215这台机器访问不了192.168.9.157上的数据库，从而导致51.215节点的nacos就崩了。
![image](https://user-images.githubusercontent.com/44914868/96207759-9260d100-0f9e-11eb-989f-4ace580defee.png)
上面的图可以看出后台上是能看到215崩了的，但是215机器上用systemctl status nacos查看该节点的运行状态还是running；见下图
![image](https://user-images.githubusercontent.com/44914868/96207801-b02e3600-0f9e-11eb-8d5b-0f41fc5b104f.png)
只要最后鬼的是，集群还有两个节点仍然正常的，但是整个集群已经变的不是完全可用了（不是完全不可用）。通过查看swarm查看部分运行容器的日志发现，部分容器不停重启，因为注册不上nacos集群；是部分容器，不是所有容器。
![image](https://user-images.githubusercontent.com/44914868/96207982-161abd80-0f9f-11eb-846c-d5e9872b262e.png)
上面的图里就是某个容器注册到nacos的日志信息。显示拒绝链接。
最近几个月试用下来，我感觉nacos集群高可用上面并不是那么可靠，当某个节点宕机后，有些时候集群能正常工作，有些时候集群会变成部分可用状态。

**Comment by KomachiSion** [comment]
拒绝连接大概率是这个ip（或者vip后面的真实ip）不通，或者服务没有启动端口未监听。

51.215服务器 bridge被调整成192.168段了，那么是不是原来的ip就已经失效了？ 负载均衡有摘除吗？如果没有摘除，原来ip又失效的话，拒绝连接就是很正常的事情了。

而且拒绝连接说明客户端和服务端直接就没有建立成功连接，后面的所有服务注册，心跳都会失败。
说白了就是网络环境的问题。

**Comment by KomachiSion** [comment]
很简单验证这个问题。

绕过nginx， 直接操作nacos集群， 比如用openAPI 注册一个测试服务
```
curl -X POST 'http://(172.18.51.214、172.18.51.215、172.18.51.216):8848/nacos/v1/ns/instance?serviceName=DEFAULT_GROUP@@nacos.test.1&ip=1.1.1.1&port=8088&ephemeral=true&clusterName=TEST'

```

然后看下3个请求的反馈。

**Comment by yyt6200** [comment]
51.215网络是通的，只是51.215这台机器不能访问192.168段的服务器了（也就是nacos无法访问数据库了）。nginx应该会自动摘除不可用的地址吧？通过http://172.18.51.218:8848/nacos地址可以正常访问集群的，后台也能体现集群中51.215这个节点挂了。

**Comment by yyt6200** [comment]
再补充下，虽然51.215机器上通过systemctl status nacos命令查看节点虽然是“runing”状态，但是telnet 51.215的8848端口是不通的，51.218 代理了（51.214:8848；51.215:8848；51.216:8848）三个nacos节点，用51.218:8848/nacos访问后台没有问题的

**Comment by KomachiSion** [comment]
我有点晕。。你是说51.215（出问题的机器）从外部访问8848端口是不通的，然后其他两台集群集群能访问51.215:8848，然后51.218:8848不会负载到51.215？

**Comment by yyt6200** [comment]
不是的，51.215网络没有问题，外部可以访问，只是51.215的nacos的8848无法访问了，集群另外两个节点也无法访问到51.215这台机器上的nacos的。后台集群列表显示51.215节点的节点状态是SUSPICIOUS。
昨天晚上我又做了下实验，能复现上面一样的问题。只要想办法让nacos变成无法访问数据库就可以触发这样的问题场景。
在刚开始断开节点与数据库的一定时间内，那个节点还是up状态，只是不停的刷新nginx代理的后台地址（51.218），会不停有报错生产，意思就是JDBC无法连接之类的。过了一段时间后（估计半小时），断开与数据库连接的nacos节点会变成SUSPICIOUS状态，然后swarm中部分容器出现的问题就和我上面发的图一样，51.218:8848拒绝链接。

**Comment by yyt6200** [comment]
大牛能不能提供下联系方式？我可以录个视频发给你，从制造问题到出问题的完整过程

**Comment by KomachiSion** [comment]
加钉钉吧 提供下你的钉钉号

**Comment by yyt6200** [comment]
yyt63000

**Comment by KomachiSion** [comment]
#4045
