### ISSUE TITLE
使用nacos config 如何动态刷新    @PostConstruct 注解标注的bean 实例

### ISSUE THREAD

**Issue by lihao95** [alibaba/nacos#3684]
![image](https://user-images.githubusercontent.com/30857267/91158616-7dcc2f00-e6f9-11ea-8552-def9ed33d8f7.png)
如图中 带有 @PostConstruct注解的这样的配置，正常情况下，在界面修改后配置是不生效的，请问这个该怎么解决呢。

**Comment by fungoddd** [comment]
你可以用这种方法
`
@RefreshScope
@Configuration
public class RefreshConstant {

    @Value("${test.value1:}")
    private String testValue1Temp;
    public static String testValue1;

    @Value("${test.value2:}")
    private String testValue2;

    private static final Map<String, Object> MAP = Maps.newHashMap();

    public static String getProperty(String key) {
        if (null != MAP.get(key)) {
            return String.valueOf(MAP.get(key));
        }
        return null;
    }

    @EventListener
    public void envListener(EnvironmentChangeEvent event) {
    }

    @PostConstruct
    public void init() {
        testValue1 = testValueTemp;
        MAP.put("testValue2", testValue2);
    }
}
`

`
@RestController
@RequestMapping("/test")
public class TestController {

    @GetMapping(value = "/testValue")
    public Object test() {
     return  "testValue1:"+RefreshConstant.testValue1+" testValue2:"RefreshConstant.getProperty("testValue2");
    }
}

`

**Comment by fungoddd** [comment]
你可以用这种方法
```java
@RefreshScope
@Configuration
public class RefreshConstant {

    @Value("${test.value1:}")
    private String testValue1Temp;
    public static String testValue1;

    @Value("${test.value2:}")
    private String testValue2;

    private static final Map<String, Object> MAP = Maps.newHashMap();

    public static String getProperty(String key) {
        if (null != MAP.get(key)) {
            return String.valueOf(MAP.get(key));
        }
        return null;
    }

    @EventListener
    public void envListener(EnvironmentChangeEvent event) {
    }

    @PostConstruct
    public void init() {
        testValue1 = testValueTemp;
        MAP.put("testValue2", testValue2);
    }
}
```

```java
@RestController
@RequestMapping("/test")
public class TestController {

    @GetMapping(value = "/testValue")
    public Object test() {
     return  "testValue1:"+RefreshConstant.testValue1+" testValue2:"RefreshConstant.getProperty("testValue2");
    }
}
```
