### ISSUE TITLE
权限控制-支持用户根据Group划分权限

### ISSUE THREAD

**Issue by yunweidage** [alibaba/nacos#3689]
使用版本：1.3.2
环境：Linux Centos7
权限管理-添加权限只能针对用户添加namespace的权限，期望可以根据配置管理中的Group添加读写权限，公司根据项目制来划分团队，各自团队负责各自业务，只能根据namespace区分现在的话  其他团队都能看到配置，希望在同一个namespace可根据Group区分权限。
![image](https://user-images.githubusercontent.com/25795668/91250717-45296580-e78c-11ea-88d2-1836f360d940.png)

**Comment by KomachiSion** [comment]
There is currently no plan to support this feature.

**Comment by yunweidage** [comment]
> 当前没有计划支持此功能。

hope that can join in the future plan and expect to control the permissions of groups

**Comment by chuntaojun** [comment]
> > 当前没有计划支持此功能。
> 
> hope that can join in the future plan and expect to control the permissions of groups

当前权限代码设计已经支持，但是基于性能原因，并没有细化到group层面，你可以自行改造处理

**Comment by KomachiSion** [comment]
refer and duplicate with #3675

**Comment by yunweidage** [comment]
> > > 当前没有计划支持此功能。
> > 
> > 
> > hope that can join in the future plan and expect to control the permissions of groups
> 
> 当前权限代码设计已经支持，但是基于性能原因，并没有细化到group层面，你可以自行改造处理

OK, thank you for your reply. We have already started to try secondary development

**Comment by yunweidage** [comment]
> refer and duplicate with #3675

Thanks~
