### ISSUE TITLE
作为配置中心时要使用权限，作为注册中心时不使用权限，如何实现？

### ISSUE THREAD

**Issue by hanzhen1989** [alibaba/nacos#3690]
1、使用nacos即作为配置中心，又做为注册中心。但是一般情况下，作为配置中心时要加权限控制，但是作为注册中心是不需要进行权限控制的。
2、另外作为配置中心时，项目中只需要使用一个只读权限的用户权限就可以了，暴露在配置文件中没有问题。但是作为注册中心却需要可写权限的用户，暴露在配置文件中不好，放到其他地方又费劲。
3、再就是我用命令主动下线服务时，需要一个token，这就费劲了。

**Comment by KomachiSion** [comment]
1. 我认为权限控制都是需要的，只是哪方面有更高的需求的问题。
2. 你可以建一个只读权限用户给SDK，然后再建一个读写权限用户给控制台。
3. 下线操作是管理人员权限，不然谁都可以操作岂不是可以胡乱下线你们的服务。

**Comment by hanzhen1989** [comment]
> 1. 我认为权限控制都是需要的，只是哪方面有更高的需求的问题。
> 2. 你可以建一个只读权限用户给SDK，然后再建一个读写权限用户给控制台。
> 3. 下线操作是管理人员权限，不然谁都可以操作岂不是可以胡乱下线你们的服务。

对于问题3，主动下线时，能不能是指定用户名和密码来主动下线？

**Comment by KomachiSion** [comment]
问题1: nacos支持注册中心和配置中心分开部署，这样你可以配置中心开auth 注册中心不开auth
问题2:同1
问题3:`主动下线时，能不能是指定用户名和密码来主动下线？` 没理解这个需求，至少目前应用要下线无非自己关掉，或者应用还在，但是管理人员手动ban掉（从控制台）。通过命令来执行也没有问题，只不过开启了auth就需要在调用接口时加一个token而已。
问题4: 白名单功能可能是后期的一个优化点，但是我觉得目前不是很紧急。

**Comment by KomachiSion** [comment]
No discussion for a long time
