### ISSUE TITLE
nacos自定义权限控制分配不起作用

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#3694]
nacos版本：1.3.2
场景：新建一个"lh"的用户名，然后创建一个对应的角色列表（角色名：read-only；用户名：lh）；最后创建一个权限列表（角色名：read-only，资源：public，动作：只读(r) ）
但是最后我用lh登录nacos并在public的命名空间还是可以新建一个配置
如下图：
![image](https://user-images.githubusercontent.com/33769220/91267722-87f83700-e7a6-11ea-951f-e7b9d6912819.png)
![image](https://user-images.githubusercontent.com/33769220/91267751-96465300-e7a6-11ea-8b5e-1e0ed6a76718.png)
![image](https://user-images.githubusercontent.com/33769220/91276978-d01e5600-e7b4-11ea-8919-e723976d7a2a.png)
![image](https://user-images.githubusercontent.com/33769220/91277034-e1fff900-e7b4-11ea-8a90-08a8c1dba36c.png)

**Comment by KomachiSion** [comment]
Did you open auth feature?

`nacos.core.auth.enabled=true`

**Comment by HelloHaiNG** [comment]
> Did you open auth feature?
> 
> `nacos.core.auth.enabled=true`


> Did you open auth feature?
> 
> `nacos.core.auth.enabled=true`

no，let me try

**Comment by KomachiSion** [comment]
@HelloHaiNG Any process?

**Comment by HelloHaiNG** [comment]
> @HelloHaiNG Any process?

After configed 'nacos.core.auth.enabled=true'，it worked
thanks
