### ISSUE TITLE
nacos注册中心持久化问题

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#3696]
nacos注册中心是将服务和实例的信息保存在内存中的，有没有持久化到本地的配置呢

**Comment by KomachiSion** [comment]
非持久化的实例和服务不会持久化到本地，持久化的实例和服务会

**Comment by HelloHaiNG** [comment]
> 非持久化的实例和服务不会持久化到本地，持久化的实例和服务会

持久化到本地是指保存在文件中还是数据库中呢
