### ISSUE TITLE
使用nacos开启认证功能使用username和password时没有对认证失败状态进行处理，导致认证失败也可读取配置

### ISSUE THREAD

**Issue by jnan88** [alibaba/nacos#3697]
nacos：v1.2.1 on nacos-client-1.2.1.jar

com.alibaba.nacos.client.config.http.ServerHttpAgent.ServerHttpAgent 
securityProxy.login(serverListMgr.getServerUrls());

The status of processing login failure is not processed, and the configuration can be read even if the authentication fails

没有对处理登录失败的状态进行处理，导致认证失败也可读取到配置

**Comment by horizonzy** [comment]
pls check the authentication trigger is open in server.

**Comment by jnan88** [comment]
sorry! i check run args only set -Dnacos.core.auth.enabled=true ,not set -Dnacos.core.auth.system.type=nacos, After setting two parameters, the permissions are normal ，many thinks！
