### ISSUE TITLE
windows本地使用nacos的put请求注册服务后，过一会儿服务会消失

### ISSUE THREAD

**Issue by qq997404392** [alibaba/nacos#3699]
put  http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=example&ip=127.0.0.1&port=8080

![image](https://user-images.githubusercontent.com/23157979/91294131-a290d700-e7cb-11ea-9f50-48c1d26ff239.png)

然后服务就消失了：
![image](https://user-images.githubusercontent.com/23157979/91294164-b0def300-e7cb-11ea-8aed-0281c97f1b05.png)

**Comment by KomachiSion** [comment]
把隐藏空服务关掉再看看

**Comment by qq997404392** [comment]
> 把隐藏空服务关掉再看看

感谢！
还想问下就是这种方式注册的服务如何让它保持呢？变成空服务之后再访问就拿不到数据了。

**Comment by KomachiSion** [comment]
保持心跳啊， 您拿open api注册的服务 不保持心跳当然会被当作不健康实例。
想保持住需要定时维持心跳。
或者注册成持久化实例也行

**Comment by JackSun-Developer** [comment]
> > 把隐藏空服务关掉再看看
> 
> 感谢！
> 还想问下就是这种方式注册的服务如何让它保持呢？变成空服务之后再访问就拿不到数据了。

该情况是因为nacos有定时清除空服务的机制。详情见：
nacos/naming/src/..../nacos/naming/core/ServiceManager.java第142行启动了定时任务去清理空的服务（没有实例的服务），会使用全局线程池来固定频率地干掉空服务。

不让服务被干掉方法有两个：
1 把application.properties文件下的如下几个配置进行相应更改
nacos.naming.empty-service.auto-clean=true #改成true
nacos.naming.empty-service.clean.initial-delay-ms=50000 #或者把这个改成较大值 
nacos.naming.empty-service.clean.period-time-ms=30000 #改成较大值 
2 保证服务下一定是有实例的，并且实例网络畅通，定时发送心跳包。
