### ISSUE TITLE
There is an error in the sample code for the SDK document

### ISSUE THREAD

**Issue by johnnywww** [alibaba/nacos#37]
I write demo through [nacos's sdk](https://nacos.io/zh-cn/docs/sdk.html). There is an error exist in sample code.
``` java
NamingService naming = NamingFactory.createNaming(System.getProperty("serveAddr"));
naming.subscribe("nacos.test.3", event -> {
    if (event instanceof NamingEvent) {
        System.out.println(((NamingEvent) event).getServceName());
        System.out.println(((NamingEvent) event).getInstances());
    }
});
```
There is no method getServceName for class NamingEvent.

**Comment by yangyshdan** [comment]
Please download the latest api component source code.

The class is under package com.alibaba.nacos.api.naming.listener.
