### ISSUE TITLE
[Feature] Support Discovery Events on NamingService

### ISSUE THREAD

**Issue by mercyblitz** [alibaba/nacos#370]
Support Discovery Events:

- Registry Avaliable
- Registry Started
- Registered
- UnRegistered
- Registry Closed

**Comment by nkorange** [comment]
This may be useful feature, let me do some digging on this.

**Comment by litian33** [comment]
We use these events to refresh routes dynamically in Spring Cloud Gateway.
Or, are there any other methods to do this?
