### ISSUE TITLE
监听通过一个定时线程POST请求服务端, 这里的间隔太小了, 不可配置

### ISSUE THREAD

**Issue by qq31715879** [alibaba/nacos#3702]
executor.scheduleWithFixedDelay(new Runnable() {
            @Override
            public void run() {
                try {
                    checkConfigInfo();
                } catch (Throwable e) {
                    LOGGER.error("[" + agent.getName() + "] [sub-check] rotate check error", e);
                }
            }
        }, 1L, 10L, TimeUnit.MILLISECONDS);

监听的间隔能改成可配置吗

**Comment by horizonzy** [comment]
这个感觉可以放开，而且现在这个默认的时间太短了，这个任务里面检测cacheMap的size是否增加来调配LongPollingRunnable，这个变化其实并不是很频繁，默认的检测时间可以放长一点。

**Comment by chuntaojun** [comment]
可以改成被动触发

**Comment by horizonzy** [comment]
> 可以改成被动触发

嗯

**Comment by horizonzy** [comment]
@yanlinly it should be optimized. maybe we need an another way to solve it

**Comment by KomachiSion** [comment]
Comment from PR#3719

> 这块定时的原因是30s发一个http短连接，keep alive 30s，有变化短连接， 从而模拟长链接的行为。 但不是长链接。 因此需要定期去发短连接模拟长链接。
> 
> 为什么间隔了10ms而不是立即执行？ 担心所有服务端都挂了，不断重试把cpu搞高。 为什么不能搞太久了，因为服务端可用，要尽快发出去短连接，尽快感知服务端配置是否有变化，以便有更好的实时性
> 
> 因此这块逻辑不建议修改。 后面我们改成长链接之后，这块代码会有优化。
