### ISSUE TITLE
config server config content not refresh intime and read out content is not exists in config

### ISSUE THREAD

**Issue by Dream2Land** [alibaba/nacos#3704]
**Describe the bug**
config server config content not refresh intime and read out content is not exists in config.is there some cache?

**Expected behavior**
config conent refresh intime and remove history config cache who has deleted.

**Acutally behavior**
config conent is't refreshed and history config who has deleted was read out.

**How to Reproduce**

1. install and start nacos on windows standalone without mysql
double click startup.cmd

2. config some info
spring.datasource.password = ZUIQ9RBzzdPTE8R2PlF1kg==

3. change nacos conf/application.properties to support mysql

#*************** Config Module Related Configurations ***************#
### If use MySQL as datasource:
spring.datasource.platform=mysql

### Count of DB:
db.num=1

### Connect URL of DB:
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user=root
db.password=123456

4. start nacos with mysql
double click startup.cmd

5. set and change config info
spring.datasource.password = abcIQ9RBzzdPTE8R2PlF1kg==

6. application who use nacos config not accept new version of config
@RefreshScope
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.refresh.enabled=true

7. remove nacos server file and mysql table
delete nacos server file dir and drop all table

8. use lastest nacos server and sql to recreate env
download lastest nacos server zip,unzip, modify conf support mysql
user conf/mysql.sql recreate table,start nacos
config set:
spring.datasource.password = abcIQ9RBzzdPTE8R2PlF1kg==

9. read config...em,, is first time config info who was created by standalone with file storage.
log show password is : ZUIQ9RBzzdPTE8R2PlF1kg==

**Desktop (please complete the following information):**
 - OS: windos
 - Version nacos-server 1.3.0/2, spring-cloud-starter-alibaba-nacos-config  2.2.1
 - Module config
 - SDK spring-cloud-starter-alibaba-nacos-config

**Additional context**
i try resolve this issue by nacos server 1.3.0, failed,then delete all nacos server file and mysql table,
download lastest nacos server 1.3.2 and use sql recreate table. then config new content , but, when application read config,
the info who was created first step by standalone with file storage. it's unbelievable

**Comment by KomachiSion** [comment]
Sorry, I can't get your problem. Do you mean that you delete config but your listener do not be notified?

**Comment by Dream2Land** [comment]
> Sorry, I can't get your problem. Do you mean that you delete config but your listener do not be notified?

yes ,but it's only one of problems.  1, listener not be notified when config update  2, config like be cached even i deleted (recreate server path,table and so on)

**Comment by Dream2Land** [comment]
sorry for that i catch the cuase becuase one of dependcy module has default yml rewrite config...
