### ISSUE TITLE
Spring和SpringBoot项目能和SpringCloud一样直接用@Value注入配置吗？

### ISSUE THREAD

**Issue by hezhiqiang** [alibaba/nacos#3706]
我看文档中，Spring和SpringBoot项目是用@NacosValue注入配置，而SpringCloud是用@Value注入配置，Spring和SpringBoot项目能否统一也支持@Value注入配置？

**Comment by KomachiSion** [comment]
应该不行，@Value在springboot里是spring自己的注释，而在spring cloud里是通过配置中心获取。语义似乎不一样。

**Comment by chuntaojun** [comment]
如果要支持refresh的话，@Value注解无法支持，只能使用@NacosValue，如果是仅仅注入配置的话，那么springboot项目是可以支持@Value注解的

**Comment by chuntaojun** [comment]
具体参看wiki：https://github.com/nacos-group/nacos-spring-boot-project/wiki
