### ISSUE TITLE
集群模式nacos三个节点的控制台显示实例数不一致

### ISSUE THREAD

**Issue by zhujiebing** [alibaba/nacos#3708]
**Describe the bug**
linux部署了1.3.1server端三个节点,连接外置mysql
172.1.1.127 nacos1.com
172.1.1.128 nacos2.com
172.1.1.28 nacos3.com
分别用
172.1.1.127:8848/nacos/index.html
172.1.1.128:8848/nacos/index.html
172.1.1.28:8848/nacos/index.html
访问控制台，看到某一个两个节点集群部署的服务在控制台显示不一致。

spring cloud alibaba 2.2.1.RELEASE；spring cloud Hoxton.SR1；spring boot 2.2.2.RELEASE; 

**Additional context**
application.properties配置加入
```java
### If use MySQL as datasource:
spring.datasource.platform=mysql

### Count of DB:
db.num=1

### Connect URL of DB:
db.url.0=jdbc:mysql://ip:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user=nacos
db.password=nacos

```

cluster.conf配置如下
```java
172.1.1.127:8848
172.1.1.128:8848
172.1.1.28:8848

```

```java
<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba.nacos</groupId>
					<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba.nacos</groupId>
					<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
                         <version>1.3.0</version>
		</dependency>
```

谢谢。  服务两个节点.  26号下午三点20分注册。日志见附件。
```java

172.1.1.128 18005

172.1.1.129 18005

```
[nacos控制台实例数异常.zip](https://github.com/alibaba/nacos/files/5135614/nacos.zip)

**Comment by horizonzy** [comment]
nacos的服务端版本多少呀。还有看了下28那台机器的日志。前面几天的日志还有吗。

**Comment by zhujiebing** [comment]
[nacos控制台实例数异常.zip](https://github.com/alibaba/nacos/files/5140233/nacos.zip)

见附件，谢谢。@horizonzy

**Comment by horizonzy** [comment]
> [nacos控制台实例数异常.zip](https://github.com/alibaba/nacos/files/5140233/nacos.zip)
> 
> 见附件，谢谢。@horizonzy server端版本1.3.1 client版本1.3.0

收到日志，信息。又核查了一遍，还有再之前的吗。

**Comment by zhujiebing** [comment]
@horizonzy   在nacos/logs下只找到这几天的日志，是不是默认只保存一周的日志。

**Comment by horizonzy** [comment]
> @horizonzy 在nacos/logs下只找到这几天的日志，是不是默认只保存一周的日志。

嗯。你的nacos.log前面的还有吧。发一下28这个机器21号之前的。

**Comment by zhujiebing** [comment]
@horizonzy  nacos.log默认也只保留七天

**Comment by horizonzy** [comment]
现在看日志信息能够推测出来。28这台机器的内部处理出现了一点问题，导致后续无法收到128机器的实例同步信息。这个出问题的时候点还在21号之前。28这个节点大概是多久启动的啊，期间有没有过什么异常。比如说gc问题

**Comment by zhujiebing** [comment]
> 现在看日志信息能够推测出来。28这台机器的内部处理出现了一点问题，导致后续无法收到128机器的实例同步信息。这个出问题的时候点还在21号之前。28这个节点大概是多久启动的啊，期间有没有过什么异常。比如说gc问题

28是8月10号启动的。 到今天一共出现2次full gc。  期间没有出现过异常情况。    只是client端的服务集群有一个节点换过机器。

**Comment by horizonzy** [comment]
我们加个钉钉吧，这样交流太慢了。
钉钉:yuovs93

**Comment by horizonzy** [comment]
according the log at node(172.1.1.28) as follow: 
2020-08-21 00:00:02,398 WARN sync checksum task already in process with 172.1.1.128:8848.
this is some unknow error happen, lead the syncChecksumTasks can't release server key 172.1.1.128:8848. so if the service's instances which responsed by 172.1.1.128 has changed, the node(172.1.1.28) can't sync.

we couldn't find the root reason why syncChecksumTasks can't release server key, the log has removed. 
if someone occur this case, pls apply recent logs to help us to find the root reason.

**Comment by KomachiSion** [comment]
@zhujiebing You can restart the one nacos server which print error log. It should solve problem once.

If it happen again, please save all logs in time and open a new issue notify us.
