### ISSUE TITLE
关于docker cluster模式启动，配置文件中nacos.core.auth.enabled=true无效，管理后台与服务注册发现采用相同权限和端口的一点疑问

### ISSUE THREAD

**Issue by ztgoto** [alibaba/nacos#3709]
> > environment:
> > NACOS_AUTH_ENABLE: true
> 
> 您说的是对的，我有点不明白的是，我在application.properties设置了`nacos.core.auth.enabled=true`
> 这个设置，在非容器下启动是可以达到身份验证效果的
> 为什么在docker容器启动的时候，这个设置却是无效的，而必须在容器启动时指定environment？
> 这点我有点觉得想不通，谢谢解答。。。

系统参数高于配置文件，参考spring environment的设计

_Originally posted by @chuntaojun in https://github.com/alibaba/nacos/issues/2974#issuecomment-640372152_

我今天也是k8s部署，发现这个问题，虽说环境变量高于配置，但是我在容器env中并未发现这个环境变量，既然没有不是应该去读配置文件中的配置？没有不代表 设置的是false吧。
另外我觉得客户端的用户及权限应该与管理平台用户及权限分开，或者是将管理平台端口和注册发现端口分开，因为很多场景下，管理平台我需要外网访问，注册中心是内网访问，而且不希望服务注册的账号能在管理平台登入

**Comment by KomachiSion** [comment]
由于不清楚你的具体环境，所以无法判断为何没有读取application.properties的设置。

平台端口和注册发现端口分开可能是后续的优化方向。比如之后替换长连接之后，长连接的端口肯定不会使用http的接口了。

至于权限分开，我觉得没有必要。

对nacos服务测来说，无论是sdk还是open api 还是控制台，都是用户请求。 都要进行权限验证。

**Comment by KomachiSion** [comment]
另外，能否改一下issue title，让别人更好的搜索和理解issue含义？

**Comment by ztgoto** [comment]
> 另外，能否改一下issue title，让别人更好的搜索和理解issue含义？

在我引用的问题中有描述过application.properties nacos.core.auth.enabled=true 无效的问题。我在 容器中通过 env 命令 并未见到https://hub.docker.com/r/nacos/nacos-server 中描述的 NACOS_AUTH_ENABLE。
另外我一种使用场景就如上所说，我管理控制台需要外网由专门人员管理，这样导致nacos的注册和配置api也通过相同端口用户在外网也能访问了，但是我只希望注册和配置api可以配置成在内网访问

**Comment by KomachiSion** [comment]
权限开关实际上只有2各地方读取，1是jvm参数`nacos.core.auth.enabled` 2是application.properties `nacos.core.auth.enabled`.优先级是jvm > application.properties 

docker中的NACOS_AUTH_ENABLE环境变量实际上转化成application.properties的值。（详情可以看docker 项目中 build目录下的application.properties.

您描述的k8s设置auth无效，建议你直接进pod里 看下是不是jvm参数设置了false。

**Comment by yjygalb** [comment]
In my situation of k8s, it seems  configuration of  "nacos.core.auth.enabled=true" in application.properties is  of no avail for nacos client.
ENV NACOS_AUTH_ENABLE true must be claimed.

**Comment by yjygalb** [comment]
In my situation of k8s, it seems  configuration of  "nacos.core.auth.enabled=true" in application.properties is  of no avail for nacos client.
ENV NACOS_AUTH_ENABLE true must be claimed.

**Comment by yjygalb** [comment]
In my situation of k8s, it seems  configuration of  "nacos.core.auth.enabled=true" in application.properties is  of no avail for nacos client.
ENV NACOS_AUTH_ENABLE true must be claimed.

**Comment by yjygalb** [comment]
In my situation of k8s, it seems  configuration of  "nacos.core.auth.enabled=true" in application.properties is  of no avail for nacos client.
ENV NACOS_AUTH_ENABLE true must be claimed.

**Comment by yjygalb** [comment]
In my situation of k8s, it seems  configuration of  "nacos.core.auth.enabled=true" in application.properties is  of no avail for nacos client.
ENV NACOS_AUTH_ENABLE true must be claimed.
