### ISSUE TITLE
使用open-api 接口/nacos/v1/ns/instance注册实例健康检查无法通过

### ISSUE THREAD

**Issue by vicykie** [alibaba/nacos#371]
参数如下serviceName=nto-jobs&ip=10.1.80.166&port=8813&healthy=true&enable=true

注册上以后过段时间发现健康检查无法通过，然后就被强制剔除了实例，但是实例是真实存在且可以被访问到的。
现在的api没有了提供健康检查的选项，望提供详细的可供配置的选项

**Comment by nkorange** [comment]
@vicykie 当前注册实例需要通过SDK来注册，同时保持心跳上报。用open-api注册因为没有持续上报心跳所以会被踢掉。

**Comment by vicykie** [comment]
@nkorange 

> @vicykie 当前注册实例需要通过SDK来注册，同时保持心跳上报。用open-api注册因为没有持续上报心跳所以会被踢掉。
那如果其他类型的语言的实例需要注册，目前没有该语言的sdk咋办。

**Comment by nkorange** [comment]
@vicykie 你是哪种类型语言，如果用open-api的话，负载均衡策略、推送等功能就就要自己实现了。
