### ISSUE TITLE
nacos编辑配置文件，按F1不能全屏，配置过多，很难受

### ISSUE THREAD

**Issue by 15051863961** [alibaba/nacos#3711]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by 15051863961** [comment]
希望快点修改

**Comment by KomachiSion** [comment]
duplicate with #3610
