### ISSUE TITLE
nacos 1.2.1 的一个问题

### ISSUE THREAD

**Issue by cometogo** [alibaba/nacos#3713]
用nacos1.2.1做注册配置中心，然后网关用的springcloudgateway ，我每次重新发布应用，都要去nacos里面更新保存下gateway_config_json（这个文件是配置服务转发，断言）这个文件才能让服务正常运行，否则就是404。请问这个是什么原因导致的？请各位大神帮忙解决下呀~

**Comment by zzq1314zll** [comment]
“把断言，服务路由规则这些放在nacos-config 中，然后每次启动需要重新在nacos 页面更新保存，如果不更新保存配置就不能够生效” 是这个意思吗

**Comment by cometogo** [comment]
是的，每次都要重新去nacos重新保存下才可以

**Comment by cometogo** [comment]
> “把断言，服务路由规则这些放在nacos-config 中，然后每次启动需要重新在nacos 页面更新保存，如果不更新保存配置就不能够生效” 是这个意思吗

是的，每次都要重新去nacos重新保存下才可以

**Comment by KomachiSion** [comment]
麻烦用issue模版来描述问题，同时修改一下标题。

**Comment by cometogo** [comment]
> 麻烦用issue模版来描述问题，同时修改一下标题。

重新提交了issue,编号：3722，麻烦帮忙看下

**Comment by KomachiSion** [comment]
Refer to #3722
