### ISSUE TITLE
一个节点一直处于Candidate状态

### ISSUE THREAD

**Issue by zj519718645** [alibaba/nacos#3718]
nacos 1.3.0，有一个节点一直处于Candidate状态

**Describe the bug**
使用K8S部署，statefulset 3个节点，nacos版本1.3.0。 发现有一个节点一直处于CANDIDATE状态。 重启一样有这个问题。将CANDIDATE的pod杀掉一样会是CANDIDATE状态。

**Expected behavior**
LEADER: 1
FOLLOWER: 2
CANDIDATE: 0

**Acutally behavior**
LEADER: 1
FOLLOWER: 1
CANDIDATE: 1

**How to Reproduce**
1. 执行statefulset-nacos.yml创建nacos集群
2. 登录nacos UI查看集群状态

**Comment by horizonzy** [comment]
pls check the network. check leader can send beatInfo to the candidate node

**Comment by KomachiSion** [comment]
It may be duplicate with #3384
