### ISSUE TITLE
nacos的不成熟的建议

### ISSUE THREAD

**Issue by ivanshehl** [alibaba/nacos#372]
1.nacos-client 中的HttpSimpleClient类的方法是调用一次创建一次连接,可否使用连接池,维护一定数量(可配)的连接数,定期清除失效的连接
2.nacos服务端的配置管理这块,可否允许上传各种类型的配置文件,
3.涉及到Properties配置修改时,可否每一行隔离(即一行一个修改,新增,删除按钮),提供模糊查询
4..nacos-client可否提供对于Properties配置文件单行配置热查询功能

**Comment by hxy1991** [comment]
非常赞的建议！

1. 我们有计划作为一个优化点的。
2. 我们后续会有导入导出的功能。
3. 这个目前我们还没有计划，请问你是一个配置里面有很多 Key Value 的情况？
4. 你是比较多获取单个 Key 的情况？易用性方面我们会不断增强的。

**Comment by ivanshehl** [comment]
第3点:我在用nacos的时候我会把一个新增项当做一个Properties文件会把这个Properties文件里面的所有key/value都配置进去(不知道用的对不对),但是在维护的可能会出现人为改错影响其他行的情况,再就是我们Properties文件里面有很多key/value,虽然做了分类,但是一些文件还是会不断的增加,一定多了,就会出现找起来不方便和改错的问题,现在想想可能不需要隔离了,只需要一个模糊查询,基于模糊查询根据找到的进行修改.
第4点.我考虑多了,我可以在com.alibaba.nacos.api.config.listener.Listener 根据自己的需求扩展,如果实施查这太不合适了,

**Comment by hxy1991** [comment]
按你描述的第三点，编辑配置的页面里，当焦点在配置内容输入框的时候，按 ctrl+ F (command+F)，会出现一个搜索框，还支持正则表达式，不知是否满足你的需求。 

![image](https://user-images.githubusercontent.com/2517258/49558375-c05a4080-f945-11e8-9183-dafced05069e.png)

**Comment by KeRan213539** [comment]
希望导入导出快点出来,并且能导出全部或者选择多个导出,导入也可以导入多个.

**Comment by hyw520110** [comment]
1、连接异常（nacos重启或停掉）应用异常日志输出太频繁（200毫秒不到输出一次）；
2、心跳info日志一秒一次，建议改为debug级别
3、nacos配置文件增加加密支持（数据库密码）

**Comment by nkorange** [comment]
> 1、连接异常（nacos重启或停掉）应用异常日志输出太频繁（200毫秒不到输出一次）；
> 2、心跳info日志一秒一次，建议改为debug级别
> 3、nacos配置文件增加加密支持（数据库密码）

能分别建立三个issue吗？方便查找

**Comment by 1610220353** [comment]
我想问一下，2020年了nacos-client 中的HttpSimpleClient类的方法是调用一次创建一次连接,可否使用连接池,维护一定数量(可配)的连接数,定期清除失效的连接   这个问题解决了吗？？

**Comment by KomachiSion** [comment]
许多内容在新版本已经实现， 请尝试使用新版本。
