### ISSUE TITLE
nacos1.3.2存在3个安全漏洞

### ISSUE THREAD

**Issue by 191474639** [alibaba/nacos#3720]
1、网站修改密码处存在越权，test用户可以修改nacos用户的密码
2、nacos登录存在暴利破解风险
3、nacos密码登录使用明文传输

**Comment by KomachiSion** [comment]
1.  需要开启权限功能，否则都可以改
2. 没看懂，暴力破解指的是默认密码是nacos？
3. 这个确实有，但是nacos一般部署在内网，不太会直接暴露出来，优先级可以延后。当然老哥愿意贡献这块代码我们当然很开心接收。

**Comment by 191474639** [comment]
1、亲测，put请求这个接口http://127.0.0.1:8848/nacos/v1/auth/users?accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkb25nIiwiZXhwIjoxNTk4OTY5OTIxfQ.wKnm4jVlwpiqzhNZJ3Yp0RZPyI6fRzbCrzQnIOROjFU，参数username=dong&newPassword=123，将dong修改为nacos，就可以直接修改nacos的密码。
2、肉鸡不停的调登录接口，建议加个验证码
3、采用spring security RSA进行安全加密

**Comment by 191474639** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
1.  我实际测试，并不能修改。你能修改有两种可能：a. 你给这个账户添加了管理员权限；b.你没开启auth功能
2. 这个问题的确有，不过nacos应该属于内网应用，一般不对公开放的吧，加验证码拦截代价太大，如果有需要可以自行添加。
3. 可以考虑，但是就和问题2一样，内网应用的话优先级应该可以延后。

**Comment by wangweizZZ** [comment]
关于2、3两点。我们这之后倒是也有这种需求。如果需要，可以我们来贡献下

**Comment by KomachiSion** [comment]
2. 验证码方案可以先开个issue，社区discuss一下
3. 这里最好可以将不同的加密算法SPI化和可配置化，方便后续添加和切换加密算法

**Comment by KomachiSion** [comment]
@191474639 @wangweizZZ 如果有需要，2 3问题各自单独提一个issue吧，然后单独描述清楚。作为社区任务开放。这个issue就先关闭了
