### ISSUE TITLE
Nacos1.2.1 Gateway重启需要重新更新配置，否则404

### ISSUE THREAD

**Issue by cometogo** [alibaba/nacos#3722]
**Describe the bug**
把断言，服务路由规则这些放在nacos-config 中，然后每次启动需要重新在nacos 页面更新保存，如果不更新保存配置就不能够生效
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by chuntaojun** [comment]
之所不能生效，是因为你们只用了ConfigService.addListener，只在回调中去加载getaway的配置并load吧？

**Comment by cometogo** [comment]
> 之所不能生效，是因为你们只用了ConfigService.addListener，只在回调中去加载getaway的配置并load吧？

请问应该如何实现？

**Comment by chuntaojun** [comment]
> > 之所不能生效，是因为你们只用了ConfigService.addListener，只在回调中去加载getaway的配置并load吧？
> 
> 请问应该如何实现？

ConfigService.getAndSignListener接口，第一次主动那配置，其次再把自己加入Listener去监听

**Comment by cometogo** [comment]
> > > 之所不能生效，是因为你们只用了ConfigService.addListener，只在回调中去加载getaway的配置并load吧？
> > 
> > 
> > 请问应该如何实现？
> 
> ConfigService.getAndSignListener接口，第一次主动那配置，其次再把自己加入Listener去监听

一样效果

**Comment by chuntaojun** [comment]
> > > > 之所不能生效，是因为你们只用了ConfigService.addListener，只在回调中去加载getaway的配置并load吧？
> > > 
> > > 
> > > 请问应该如何实现？
> > 
> > 
> > ConfigService.getAndSignListener接口，第一次主动那配置，其次再把自己加入Listener去监听
> 
> 一样效果

什么一样的效果，你的代码贴一下

**Comment by cometogo** [comment]
> > > > > 之所不能生效，是因为你们只用了ConfigService.addListener，只在回调中去加载getaway的配置并load吧？
> > > > 
> > > > 
> > > > 请问应该如何实现？
> > > 
> > > 
> > > ConfigService.getAndSignListener接口，第一次主动那配置，其次再把自己加入Listener去监听
> > 
> > 
> > 一样效果
> 
> 什么一样的效果，你的代码贴一下

ConfigService configService = NacosFactory.createConfigService(properties);
            String content = configService.getConfig(dataId, group, 5000);
            configService.addListener(dataId, group, new Listener() {
                @Override
                public void receiveConfigInfo(String configInfo) {

**Comment by chuntaojun** [comment]
你们由自己把getConfig的配置去apply到gateway吗

**Comment by cometogo** [comment]
> 你们由自己把getConfig的配置去apply到gateway吗

这个是我更新到1.2.1后出现的问题，之前的版本好像没这个问题

**Comment by chuntaojun** [comment]
需要debug下，看下getConfig返回了什么，

**Comment by sanxun0325** [comment]
@cometogo 网关是用什么做的，spring cloud gateway么？如果是的话可以考虑 在RouteDefinitionRepository 的实现类初始化时加载配置到路由，并且建立监听。

**Comment by KomachiSion** [comment]
No response from author more than **7 days**

**Comment by cometogo** [comment]
> @cometogo 网关是用什么做的，spring cloud gateway么？如果是的话可以考虑 在RouteDefinitionRepository 的实现类初始化时加载配置到路由，并且建立监听。

就是用的这个
