### ISSUE TITLE
注册中心不同命名空间之间的服务能否互通？

### ISSUE THREAD

**Issue by beforeborn** [alibaba/nacos#3723]
配置中心使用了一个代码库（一个微服务）对应一个命名空间，不同测试环境对应不同group的方式，用起来没问题。
现在希望项目的注册中心也迁移到nacos，但如果按照配置中心的分配方式，不同代码库将使用不同的命名空间，但不同代码库对应的服务之间需要相互调用。
各路大神，请问这种情况有啥建议么？

**Comment by taibai233** [comment]
没太理解你的意思。
首先，你这里是不同的代码使用不同的配置文件，然后想使用同一个注册中心么？

注册中心的namespace和配置中心的namespace是无关的

**Comment by KomachiSion** [comment]
客户端创建之后，只能访问创建时指定的namespace。 
同一个代码库在同一个ns下面，不同环境通过group区分是可以的。因为启动客户端之后只会访问同一个ns下面的内容。
但是注册中心这么做应该不行。因为需要跨ns查找provider。
