### ISSUE TITLE
自定义类名不能命名为NacosProperties,否则启动报错

### ISSUE THREAD

**Issue by situhouyi** [alibaba/nacos#3724]
前提：SpringCloud中引入alibaba，使用nacos作为配置。SpringCloud相关版本使用2.0.3，spring-cloud-alibaba为2.0.2，nacos为1.2.1
问题：自己定义类，将所有自定义的nacos配置放在类中，代码如下
`@Component
@RefreshScope
public class NacosProperties {
     @Value("name")
    private String name;
}
`
启动就会报错：No qualifying bean of type 'com.alibaba.cloud.nacos.NacosDiscoveryProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

但将类名改掉后，就能正常，并能读取到配置.
[报错日志.log](https://github.com/alibaba/nacos/files/5149093/default.log)

**Comment by KomachiSion** [comment]
spring-cloud-alibaba的问题请提issue到spring-cloud-alibaba project下，这里可能没办法解决，只能简单回答一些使用上的问题。
