### ISSUE TITLE
srping 集成 nacos-client 1.2.0 版本的时候在创建ServerHttpAgent  调用securityProxy.login 时传入的为已经拼接好的服务器地址如http://xx:8848 而在login中有拼接了一次http导致登录失败

### ISSUE THREAD

**Issue by 619016140** [alibaba/nacos#3725]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Please describe your issue detail in issue template not in title.
