### ISSUE TITLE
页面刷新的时候服务的实例数一直在变化

### ISSUE THREAD

**Issue by liaogaoyu** [alibaba/nacos#3726]
![image](https://user-images.githubusercontent.com/28127914/91783087-95437480-ec31-11ea-9dcf-e3c50b2fbeed.png)
每次刷新这个实例数和健康实例数都在不停的变化

**Comment by KomachiSion** [comment]
麻烦用issue模版描述一下你的问题。目前的信息太少，无法分析定位。

**Comment by Inighty** [comment]
我也出现了这个问题  请问找到原因了吗 心跳经常返回没找到 然后又去重新注册服务实例

**Comment by Inighty** [comment]
重启了nacos服务 就好了 。。

**Comment by KomachiSion** [comment]
No response from author, and provided information is not enough to locate and reproduce problem. Close issue.

**Comment by zrlw** [comment]
我翻了一下历史帖子，这个情况不只一个版本有，1.3.1版本也有，nacos日志显示都是NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@...., value: {"instanceList":[]}
其中instanceList一直变。
所有帖子都是重启nacos服务才解决，所以我觉得应该排查nacos的raft相关代码。
