### ISSUE TITLE
跨空间调用共享配置

### ISSUE THREAD

**Issue by iyezhou** [alibaba/nacos#3728]
可以跨namespace调用共享配置吗，现在是一个环境一个namespace，但是多个环境有一些共同的配置，我想放在public中，怎么实现，建议在`NacosConfigProperties.Config`中加入namespace字段

**Comment by KomachiSion** [comment]
目前不可以，也暂时没有支持的计划。

namespace是资源隔离的最顶层设计，不同namespace所属的客户端不能相互访问。

**Comment by iyezhou** [comment]
@KomachiSion 那不同环境的相同配置共享有好的解决方案吗

**Comment by chuntaojun** [comment]
> @KomachiSion 那不同环境的相同配置共享有好的解决方案吗

使用group去区分

**Comment by iyezhou** [comment]
@chuntaojun 使用group区分的话放在哪个空间环境下呢，这个共享是对同一个工程不同环境的共享，放某个环境下另一个环境来引用该配置同样遇到跨空间问题而引用不到

**Comment by KomachiSion** [comment]
> @KomachiSion 那不同环境的相同配置共享有好的解决方案吗

同一套程序的配置放同一个namespace下，然后用group区分，通用的配置放一个group，各个环境私有配置放其他各自的group

**Comment by iyezhou** [comment]
@KomachiSion 了解了，我重新配一下，把namespace升级到项目级别

**Comment by huang-xuan** [comment]
您好，我现在每个项目是一个namespace, 但是多个项目中可能配置的内容是一样的，不能一个项目读取多个namespace吗？如果不支持。是不是只能多个项目共用一个namespace，然后通过group来区分项目？我看namespace限制最多配置200个dataid，这个生效吗？

**Comment by KomachiSion** [comment]
客户端目前不支持跨namespace访问，暂时也没有支持的计划。

200dataid限制好像是控制台的限制。

**Comment by huang-xuan** [comment]
> 客户端当前不支持跨名称空间访问，暂时也没有支持的计划。
> 
> 200dataid限制好像是控制台的限制。

那这个200限制会生效吗？项目配置多于200怎么办

**Comment by huang-xuan** [comment]
> 客户端目前不支持跨namespace访问，暂时也没有支持的计划。
> 
> 200dataid限制好像是控制台的限制。

实际配置要同一个namespace多于200，这个怎么办

**Comment by KomachiSion** [comment]
这个限制默认是关闭的，你可以在一个namespace下注册任意数量dataid

**Comment by prayjourney** [comment]
> @KomachiSion 那不同环境的相同配置共享有好的解决方案吗

同问
