### ISSUE TITLE
win10启动nacos-server-1.3.2失败

### ISSUE THREAD

**Issue by spidersq** [alibaba/nacos#3731]
遇到了与 #3730 同样的问题，只是搭建一个单机版的，而那个关联的重复问题是集群的，怎么 #3730 这个问题就直接给关闭了呢？

**Comment by shenqiuzhuyun** [comment]
`nacos\conf`目录下新建`cluster.conf`文件，内容如下:
`nacos-0.nacos-headless.default.svc.cluster.local`
`nacos-1.nacos-headless.default.svc.cluster.local`
`nacos-2.nacos-headless.default.svc.cluster.local`

**Comment by spidersq** [comment]
> `nacos\conf`目录下新建`cluster.conf`文件，内容如下:
> `nacos-0.nacos-headless.default.svc.cluster.local`
> `nacos-1.nacos-headless.default.svc.cluster.local`
> `nacos-2.nacos-headless.default.svc.cluster.local`

你好，这样确实解决了，但是也应该是个bug吧，单机运行为啥要配置集群的文件。另外，部署文档里也没提到这样做。

**Comment by KomachiSion** [comment]
单机版启动加 -m standalone了吗 加了如果还出现就需要看一下是不是有问题。我在macos和linux下测试是没问题的

**Comment by spidersq** [comment]
> 单机版启动加 -m standalone了吗 加了如果还出现就需要看一下是不是有问题。我在macos和linux下测试是没问题的

 #3730 和我遇到的都是在win10下进行单机版运行的。

**Comment by spidersq** [comment]
试了下，加了-m standalone也好使了，看来在windows下也得加此参数。希望更新下文档，文档里只说双击即可。

**Comment by KomachiSion** [comment]
#3730 不是单机版启动 他启动是直接`startup.cmd` 没有加 `-m standalone`，是集群启动。

**Comment by spidersq** [comment]
是参照的这里 https://nacos.io/zh-cn/docs/deployment.html

**Comment by KomachiSion** [comment]
文档可能有更新遗漏，欢迎提pr补全。issue是重复的没有问题，可以关闭
