### ISSUE TITLE
Nacos配置中心前端优化建议

### ISSUE THREAD

**Issue by ankeway** [alibaba/nacos#3732]
Naocs config center，In the configuration list， Each service instance configuration Is use file format to store,  for example, properties，
Naocs配置中心，配置列表中，每一个服务实例的配置采用的文件格式来存储的，例如properties
The properties inside all the configuration items to use the Key - Value, relatively concentrated interaction
properties里面所有的配置项使用Key,Value交互上比较集中
It is difficult to view, to search,
查看起来，查找起来很不方便。
Can you change a way of interaction，for a single configuration items to do a add delete modify operations，
能否转变一种交互方式，对某一个配置项，Key，value做新增删除修改的独立的配置，
for example
例如 
![image](https://user-images.githubusercontent.com/8588513/91792632-87e5b480-ec48-11ea-8949-41d4e603e229.png) 
and then，All the configuration items,  to display as a list, for a single Key-value to delete or modify，but not all heap in a properties file
然后，所有的配置信息，全部以列表的方式呈现出来，可以对某一个key，value配置进行删除或者修改，而不是全部堆在一个properties文件中

**Comment by KomachiSion** [comment]
那如果是json呢？ 如果是yml呢？ 如果是xml或者只是单纯的文本文件呢？

这种方式显然不具有通用性，属于定制需求了

**Comment by ankeway** [comment]
> 那如果是json呢？ 如果是yml呢？ 如果是xml或者只是单纯的文本文件呢？
> 
> 这种方式显然不具有通用性，属于定制需求了

存储格式不需要调整，都是key-value,就如同nacos的数据库config_info表中content字段存储的就是全部的配置明细字符串，但是程序在加载环境变量env的时候，会把这些文本内容，解析为key-value格式来加载到服务中的，而不是加载整个content内容，所以前端理论上也是可以按列表方式加载解析并显示的。可能有些难度

**Comment by KomachiSion** [comment]
你的意思是说，如果用户选择了类型是properties，然后控制台变成这种配置项界面，而不是一个可编辑文本框？

**Comment by ankeway** [comment]
> 你的意思是说，如果用户选择了类型是properties，然后控制台变成这种配置项界面，而不是一个可编辑文本框？

要是能支持properties也不错,  配置内容文本框变为一个表格列表，并且支持对某一个配置项做操作

**Comment by KomachiSion** [comment]
个人感觉不是很好，一般这个配置都是来自于原先的配置文件，我觉得大多数人更希望像编辑properties文件一样编辑配置文件。

而且可能有些应用首次使用配置中心，需要把之前的配置一项项的配置肯定很麻烦，不如直接把配置内容直接复制粘贴进来方便。

**Comment by ankeway** [comment]
> 个人感觉不是很好，一般这个配置都是来自于原先的配置文件，我觉得大多数人更希望像编辑properties文件一样编辑配置文件。
> 
> 而且可能有些应用首次使用配置中心，需要把之前的配置一项项的配置肯定很麻烦，不如直接把配置内容直接复制粘贴进来方便。

类似于 Apollo的 表格展示效果

**Comment by KomachiSion** [comment]
如果社区有意愿的话，可以做成模式切换，喜欢用表格展示和修改的用表格模式，喜欢编辑文件的用现有的格式。

只不过我认为优先级不高，而且这种模式可能只针对properties（至少json和text是不可行的）。
