### ISSUE TITLE
nacos注册的服务经常挂掉是怎么回事，页面刷新一会正常一会异常，请求服务就报503 (Service Unavailable)

### ISSUE THREAD

**Issue by wardseptember** [alibaba/nacos#3733]
nacos注册的服务经常挂掉是怎么回事，页面刷新一会正常一会异常，请求服务就报503 (Service Unavailable)。
![](http://wardseptember.top/20200901135022.png)

异常
![](http://wardseptember.top/20200901135110.png)

**Comment by KomachiSion** [comment]
nacos通过心跳来维持实例健康状态，一会正常一会儿异常显然是你服务实例的心跳上报有问题。

建议检查下网络，gc等问题。

还有请求服务报503是请求你自己的服务还是nacos控制台？ 如果是请求nacos控制台，那我觉得你可以检查一下你环境的网络了。
如果是自己的服务，那应该排查下自己的服务。

**Comment by wardseptember** [comment]
请求服务报503是请求自己的服务，请求的网关，网关也是注册在nacos的。我的前端有时可以正常登录，但是过几分钟就会自动退出。我的服务renren-fast经常挂掉，但是后台又没有报错，重启服务还是一样的错误，有时能注册上，一会就挂掉。所有服务都是在本地的，localhost。只有renren-fast经常挂掉，其他都是服务都是正常的 @KomachiSion

**Comment by KomachiSion** [comment]
> 请求服务报503是请求自己的服务，请求的网关，网关也是注册在nacos的。我的前端有时可以正常登录，但是过几分钟就会自动退出。我的服务renren-fast经常挂掉，但是后台又没有报错，重启服务还是一样的错误，有时能注册上，一会就挂掉。所有服务都是在本地的，localhost。只有renren-fast经常挂掉，其他都是服务都是正常的 @KomachiSion

那只能说明nacos没有问题，可能的问题出在网关或者renren-fast本身。 只能您自己抓包分析和排查了。

**Comment by wardseptember** [comment]
好的，谢谢
