### ISSUE TITLE
dubbo注册中心上加上命名空间,会额外多出配置文件

### ISSUE THREAD

**Issue by ni247** [alibaba/nacos#3735]
nacos和客户端版本都为1.2.1
以下为dubbo配置:
dubbo:
  scan:
    base-packages: cn.pubinfo.area.service.impl
  cloud:
    subscribed-services:
  registry:
    # 挂载到 nacos 注册中心
    address: nacos://192.168.1.116:8858?namespace=b56f24a5-0af4-4aa6-8de5-d08b374bba30
    # 注册提供服务,false为不提供服务
    register: true
    # 订阅其他服务,false不订阅
    subscribe: true
  protocols:
    dubbo:
      name: dubbo
      port: -1

以下是注册成功后多出的配置文件
![Snipaste_2020-09-01_17-26-31](https://user-images.githubusercontent.com/30631076/91833169-ecb90300-ec78-11ea-936a-679927ce655a.png)

**Comment by KomachiSion** [comment]
这个应该是dubbo的问题，建议到dubbo的社区询问。

**Comment by KomachiSion** [comment]
duplicate with #3682

**Comment by zjujunge** [comment]
遇到了同样问题，nacos作为注册中心，配置栏会多会很多配置文件

**Comment by zhangran2616** [comment]
@zjujunge 
> 遇到了同样问题，nacos作为注册中心，配置栏会多会很多配置文件

你问题最后解决了吗？
