### ISSUE TITLE
在NACOS1.1.3中，服务异常退出后，实例数不会减少，依然为1

### ISSUE THREAD

**Issue by q821863269** [alibaba/nacos#3736]
将服务注册到nacos之后
直接将pid直接杀死，没有向nacos发送取消注册
过了一会，服务的健康实例数会减少
但是，服务的实例数一直不会改变
这是为什么，大佬，救命
![image](https://user-images.githubusercontent.com/37721392/91837345-b4b4be80-ec7e-11ea-8f09-b808269723be.png)

**Comment by KomachiSion** [comment]
是不是注册成持久化实例了？

**Comment by q821863269** [comment]
> 是不是注册成持久化实例了？

![image](https://user-images.githubusercontent.com/37721392/91921841-1288eb00-ecff-11ea-922b-0d3f5de7d6c9.png)

**Comment by KomachiSion** [comment]
是所有服务的实例都不清理还是只有这一个服务不清理？

**Comment by q821863269** [comment]
> 是所有服务的实例都不清理还是只有这一个服务不清理？

所有异常下线的服务，实例数都不会清理

**Comment by KomachiSion** [comment]
把nacos的日志打包上传一下吧，让大家看看

**Comment by q821863269** [comment]
[logs.zip](https://github.com/alibaba/nacos/files/5166735/logs.zip)
大家看看

**Comment by yyt6200** [comment]
我也有同样的问题，已经反馈过很多次了，目前更新到1.3.2还是会出现这种问题。

**Comment by KomachiSion** [comment]
@q821863269 根据日志来看，nacos一直在尝试删除这个不健康ip，但是没有删除成功，推测是有旧版本的bug，删除的请求参数有误。 可以先升级一下版本试试。1.2.1或者1.3.2

**Comment by wencyGit** [comment]
> 我也有同样的问题，已经反馈过很多次了，目前更新到1.3.2还是会出现这种问题。

@yyt6200 你需要下载最新的nacos 客户端,最新版本客户端已经可以自动清除空服务

**Comment by KomachiSion** [comment]
@q821863269 Any process?

**Comment by KomachiSion** [comment]
There is no more response from author, so we think the problem has been solved by upgrading to new version.

**Comment by qzy-joe** [comment]
可以看下nacos的配置文件conf/application.propertoies中的这个参数nacos.naming.empty-service.auto-clean，
是否自动清除空服务的，默认值是true。

**Comment by sytwan** [comment]
@

> @q821863269 根据日志来看，nacos一直在尝试删除这个不健康ip，但是没有删除成功，推测是有旧版本的bug，删除的请求参数有误。 可以先升级一下版本试试。1.2.1或者1.3.2

@KomachiSion 请问是看哪个日志分析呢
