### ISSUE TITLE
配置中心配置文件yml中有@符号会报错

### ISSUE THREAD

**Issue by sjrlyy** [alibaba/nacos#3740]
xzy:
  project:
    version: @project.version@

报错信息
org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 6, column 14:
        version: @project.version@

**Comment by KomachiSion** [comment]
It's not nacos problem, please search how to use '@' in yaml.
