### ISSUE TITLE
Nacos - IllegalArgumentException: Could not resolve placeholder 'project.version' in value "${project.version}

### ISSUE THREAD

**Issue by bigbenfather** [alibaba/nacos#3741]
**Describe the bug**
An exception occurred while refreshing spring context.

**Expected behavior**
refresh success

**Acutally behavior**
IllegalArgumentException: Could not resolve placeholder 'project.version' in value "${project.version}

**How to Reproduce**
1. create a springcloud project ;
2. use nacos as configuration and service discovery;
3. add dependency jasypt-spring-boot-starter;
4. boot the application;
5.modify and publish youapplication.propertes on nacos dashbord;
6.Automatic trigger refresh your application;

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 
nacos-client-1.1.4.jar  
nacos-common-1.1.4.jar  
nacos-api-1.1.4.jar  
spring-cloud-starter-alibaba-nacos-config-2.1.1.RELEASE.jar  
spring-cloud-alibaba-nacos-config-2.1.1.RELEASE.jar  
nacos-config-spring-boot-starter-0.2.1.jar  
nacos-spring-context-0.2.2-RC1.jar  
nacos-config-spring-boot-autoconfigure-0.2.1.jar  
nacos-spring-boot-base-0.2.1.jar 

**Additional context**
In the nacos-client.jar, has a file named application.properties, it's content is "version=${project.version}",
I suspect it has something to do with this file.

**Comment by KomachiSion** [comment]
duplicate with #3528
