### ISSUE TITLE
服务变更通知问题

### ISSUE THREAD

**Issue by joenhon** [alibaba/nacos#3743]
![image](https://user-images.githubusercontent.com/39330202/91947310-1aae4e00-ed32-11ea-8619-3066b92e2089.png)
目前 我遇到注册到nacos的服务发生的上下线 并且进行了变更通知 但是并没有进行明确的下一步处理 只是打印了 一个日志
我想能否 加入一个自定义的服务变更处理的接口 还是已经存在这样一个接口

**Comment by KomachiSion** [comment]
看一下subscribe接口

**Comment by joenhon** [comment]
![image](https://user-images.githubusercontent.com/39330202/91960017-f48dab80-ed3b-11ea-8364-6728352cfe67.png)

**Comment by KomachiSion** [comment]
您只发图，不说明内容，不清楚您什么诉求，订阅接口subscribe没法满足吗？ 这个接口需要你实现一个Listener， 当服务变更后，nacos会回调这个Listener，把新的服务列表传出来，您就可以做操作了啊。

**Comment by joenhon** [comment]
我在测试 订阅，发图只是想确认下 是不是这块的代码 发布的

**Comment by joenhon** [comment]
![image](https://user-images.githubusercontent.com/39330202/91967571-ff4d3e00-ed45-11ea-8082-92466747f37a.png)

**Comment by joenhon** [comment]
目前 节点上线 能正常收到订阅， 但是下线却没有了 原有的日志订阅 也没有进 正在 找原因

**Comment by joenhon** [comment]
![image](https://user-images.githubusercontent.com/39330202/91967773-450a0680-ed46-11ea-8eb9-8427639c00cd.png)

**Comment by joenhon** [comment]
是我 zz了 断点时间太长 导致两个监听 同时收到

**Comment by joenhon** [comment]
非常感谢 您的帮助！
