### ISSUE TITLE
publish config data to Nacos error:java.lang.ClassCastException: String cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by GGBonda** [alibaba/nacos#3746]
Describe the bug:
fail publishing provider config data to Nacos config server, post result is 500, and content is 'java.lang.ClassCastException: String cannot be cast to java.lang.Boolean'.
notice: paramsValue contains props which value is "false" in String Type. 

nacos version: 1.2.1 
publish code: com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost
line:153

**Comment by TsingLiang** [comment]
give me more logs

**Comment by KomachiSion** [comment]
No response from author, and no enough information to reproduce. Close it
