### ISSUE TITLE
When can other databases be supported？It's been a long delay

### ISSUE THREAD

**Issue by guduyishuai** [alibaba/nacos#3755]
Issue 2328 is created on 20 Jan，and is also in progress now.
Could you tell us when to resolve the issue plz! 
It's important for the project not with mysql.
We are looking forward to it.
Thank you wonderful job.

**Comment by KomachiSion** [comment]
Refer to #2328 .

**Comment by KomachiSion** [comment]
See branch https://github.com/alibaba/nacos/tree/feature_multiple_datasource_support
