### ISSUE TITLE
希望nacos能提供一个公共的命名空间，其他命名空间的服务都能访问公共命名空间的内容

### ISSUE THREAD

**Issue by wangliujing** [alibaba/nacos#3756]
比如我有一个公用的文件服务器Java应用，为了每个命名空间的服务能使用该文件服务器，必须在每个命名空间下重新部署该文件服务器，建立使用public保留的命名空间作为公共的命名空间，每个命名空间都能默认使用public命名空间的服务和配置

Such as I have a common file server Java applications, for each namespace service can use the file server, must be under each namespace to redeploy the file server, set up using public reserved namespace as the naming of public space, each namespace can use public default namespace service and configuration

**Comment by chuntaojun** [comment]
命名空间是强隔离，目前没有计划做这一块，并且和nacos的整体设计方向有较大的差异

**Comment by KomachiSion** [comment]
跨namespace调用服务不就失去了隔离意义了吗？
至于是否需要设置一个公共开放的空间，需要讨论

**Comment by chuntaojun** [comment]
我觉得，目前nacos的设计来看，命名空间是持续走强隔离的设计方向去走，可以使用二级分区，group去实现弱隔离

**Comment by bleachkinsin** [comment]
理论设计应该和实践相结合，的确有这样的场景，公共微服务需要其他服务访问，每个group部署一套，的确是资源浪费

**Comment by chuntaojun** [comment]
> 理论设计应该和实践相结合，的确有这样的场景，公共微服务需要其他服务访问，每个group部署一套，的确是资源浪费

你的开发环境、生产环境、预发环境，不会都共用一个公共为服务吧，我觉得这个本身就不太合理吧？

**Comment by chuntaojun** [comment]
至少在我实习的公司和工作的公司，没遇到过这种公共服务同时服务于多个环境的

**Comment by bleachkinsin** [comment]
例如：我在生产环境上，group1是项目A的一组微服务（a.b.c.d.e），group2是项目B的一组微服务（d.e.f.g）,那么d.e就是属于两个group公用的微服务。如果d.e能单独放在一个共用的group3里面，group1和group2都能通过某种配置调用它们，那么从部署上来说，就不用每个group都部署一套。从资源消耗来说，如果这些微服务都在同一套环境中，甚至同一台服务器上时，那么也减少了内存、cpu资源的使用。而且多个环境中，一部分服务通用的，如果能公用，只部署差异服务，不是更简单吗？

**Comment by wangliujing** [comment]
就是这个意思，无奈nocas官方不采纳意见




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 中午11:45
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"王柳敬"<273833883@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] 希望nacos能提供一个公共的命名空间，其他命名空间的服务都能访问公共命名空间的内容 (#3756)





 
例如：我在生产环境上，group1是项目A的一组微服务（a.b.c.d.e），group2是项目B的一组微服务（d.e.f.g）,那么d.e就是属于两个group公用的微服务。如果d.e能单独放在一个共用的group3里面，group1和group2都能通过某种配置调用它们，那么从部署上来说，就不用每个group都部署一套。从资源消耗来说，如果这些微服务都在同一套环境中，甚至同一台服务器上时，那么也减少了内存、cpu资源的使用。而且多个环境中，一部分服务通用的，如果能公用，只部署差异服务，不是更简单吗？

**Comment by chuntaojun** [comment]
group没有强隔离，是软隔离，你可以直接操作NamingService的相关接口直接操作，至于命名空间是否按你们说的存在一个公共开放的空间，这个我仅已我个人的经历来说，变更的风险比你节约的成本要大得多我觉得

**Comment by lbrowny** [comment]
同样的问题，我这需要公共命名空间的场景是
开发环境有2个分支A,B并行开发，都会更改服务C和D，整套环境有若干服务
如果A,B两个分支分别建立name space,并且在name space下部署一套包含若干服务的环境，成本会比较高
所以希望A,B两个分支分别建立name space,但是只在各自的name space下部署服务C和D
如果C依赖服务D，他会优先去调用同name space下的服务D，没有的情况下他会去调用默认name space下的服务D
形成默认name space和自定义name space的单向隔离
目前我自己增添了一个配置项的形式声明，当本name space下没有服务时默认name space的值，不指定的情况下默认是强隔离

**Comment by icerleer** [comment]
大多数提这个问题的朋友是因为使用  namespace 来做了 group 应该做的服务组隔离。且大多是使用 Spring cloud alibaba 与 Feign 集成，然后通过nacos 完成服务注册与发现，但是Feign不提供配置指定 group, 那么自然不能实现跨 group 调用, 也就有了大家纠结的跨 "namespace" 调用。

Feign 默认在 Spring cloud alibaba 下是通过 ribbon 去实现的客户端负载均衡，那么我们可以想一下，是否可以通过自定义 LoadBalancerRule 完成这个操作。。。。

我测试了一下，完全可以！！！


![image](https://user-images.githubusercontent.com/12658216/122008944-27e18880-cdec-11eb-94fe-dfde9dcd464d.png)

**Comment by Showleen** [comment]
不明白 namespace和group的使用场景

**Comment by chuntaojun** [comment]
> 大多数提这个问题的朋友是因为使用 namespace 来做了 group 应该做的服务组隔离。且大多是使用 Spring cloud alibaba 与 Feign 集成，然后通过nacos 完成服务注册与发现，但是Feign不提供配置指定 group, 那么自然不能实现跨 group 调用, 也就有了大家纠结的跨 "namespace" 调用。
> 
> Feign 默认在 Spring cloud alibaba 下是通过 ribbon 去实现的客户端负载均衡，那么我们可以想一下，是否可以通过自定义 LoadBalancerRule 完成这个操作。。。。
> 
> 我测试了一下，完全可以！！！
> 
> ![image](https://user-images.githubusercontent.com/12658216/122008944-27e18880-cdec-11eb-94fe-dfde9dcd464d.png)

这一块可以参考下上下文链路透传，自己对相关feign、ribbon等组件进行增强，将group利用上下文进行透传处理

**Comment by WilliamShoww** [comment]
> 至少在我实习的公司和工作的公司，没遇到过这种公共服务同时服务于多个环境的

会的，真的很常见的场景，可能你们都是大公司，各种资源丰富

**Comment by WilliamShoww** [comment]
> 同样的问题，我这需要公共命名空间的场景是 开发环境有2个分支A,B并行开发，都会更改服务C和D，整套环境有若干服务 如果A,B两个分支分别建立name space,并且在name space下部署一套包含若干服务的环境，成本会比较高 所以希望A,B两个分支分别建立name space,但是只在各自的name space下部署服务C和D 如果C依赖服务D，他会优先去调用同name space下的服务D，没有的情况下他会去调用默认name space下的服务D 形成默认name space和自定义name space的单向隔离 目前我自己增添了一个配置项的形式声明，当本name space下没有服务时默认name space的值，不指定的情况下默认是强隔离

怎么做到的？

**Comment by miozus** [comment]
吓得我赶紧删了 public 命名空间下的的所有配置 💯

**Comment by zhoushenn** [comment]
这个问题你可以这样做， 本地服务不要注册到公共nacos上， spring.cloud.nacos.discovery.register-enabled = false
这样本地服务可以读nacos配置和服务，但是又不会注册到nacos上导致其他服务无法访问到的问题。

**Comment by linruikai** [comment]
> 例如：我在生产环境上，group1是项目A的一组微服务（a.b.c.d.e），group2是项目B的一组微服务（d.e.f.g）,那么d.e就是属于两个group公用的微服务。如果d.e能单独放在一个共用的group3里面，group1和group2都能通过某种配置调用它们，那么从部署上来说，就不用每个group都部署一套。从资源消耗来说，如果这些微服务都在同一套环境中，甚至同一台服务器上时，那么也减少了内存、cpu资源的使用。而且多个环境中，一部分服务通用的，如果能公用，只部署差异服务，不是更简单吗？

我也面临了同样的问题，这是我的解决方案，可以参考：https://github.com/linruikai/spring-cloud-alibaba/tree/main/spring-base/src/main/java/org/example/base/config/loadbalancer
