### ISSUE TITLE
There was an unexpected error (type=Service Unavailable, status=503). Unable to find instance for zldesign-upload

### ISSUE THREAD

**Issue by liwei2015cd** [alibaba/nacos#3757]
When using Nacos as the registry and spring cloud gateway as the gateway, the service and gateway must be in the same namespace?

**Comment by liwei2015cd** [comment]
![gateway](https://user-images.githubusercontent.com/10371702/92196131-28ceac80-eea1-11ea-9d5c-61fb65014fba.png)
![service](https://user-images.githubusercontent.com/10371702/92196135-2a987000-eea1-11ea-8af3-1181cf82ad2f.png)

**Comment by liwei2015cd** [comment]
![LB](https://user-images.githubusercontent.com/10371702/92196351-abf00280-eea1-11ea-9f3b-6f3ceaf3b2e4.png)
Provide the routing information

**Comment by sanxun0325** [comment]
@liwei2015cd Yes, the namespaces are completely isolated from each other.so the gateway should be in the same namespace as the service

**Comment by liwei2015cd** [comment]
ok, thanks!

**Comment by fattyca1** [comment]
@liwei2015cd  我用和你这个相同的配置， 给服务添加上namespace， nacos注册中心上就不会在显示服务了，然后就会报出和你这一样的错误。~  你加上namespace能注册上吗

**Comment by liwei2015cd** [comment]
> @liwei2015cd 我用和你这个相同的配置， 给服务添加上namespace， nacos注册中心上就不会在显示服务了，然后就会报出和你这一样的错误。~ 你加上namespace能注册上吗

可以的

**Comment by liwei2015cd** [comment]
> @liwei2015cd 我用和你这个相同的配置， 给服务添加上namespace， nacos注册中心上就不会在显示服务了，然后就会报出和你这一样的错误。~ 你加上namespace能注册上吗

@fattyca1 可以的，检查一下你的命名空间是否正确，如果正确，在注册中心相应的空间下看服务实例。

**Comment by fattyca1** [comment]
@liwei2015cd  ok 我试试看

**Comment by KomachiSion** [comment]
There is no repsonse from author, so we think the issue has been solved.
