### ISSUE TITLE
NacosDiscoveryClient: get service name from nacos server fail, java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by hanzhen1989** [alibaba/nacos#3766]
getServiceList时从返回结果中获取count和doms报错，因为返回的内容为null。分析了下源码，貌似只有返回的http状态为302的时候会出现这个报错。什么情况下会出现302啊？本地没有复现，所以没有本地断点调试。 nacos客户端版本是1.3.1，spring-cloud-starter-alibaba-nacos-discovery版本为2.1.2.RELEASE

![image](https://user-images.githubusercontent.com/11624934/92351952-91bb5c00-f10f-11ea-8da6-b3d48cafbe8f.png)

**Comment by KomachiSion** [comment]
分析的是`spring-cloud-starter-alibaba-nacos-discovery`源码还是nacos-client的源码？

**Comment by KomachiSion** [comment]
用issue模版描述吧，不然缺信息

**Comment by KomachiSion** [comment]
No enough information and no response from author more than **7 days**
