### ISSUE TITLE
welcome to the discussion of Nacos cluster mode

### ISSUE THREAD

**Issue by diaodiaofly** [alibaba/nacos#3771]
ZH
通常为了注册中心的稳定，生产环境会选择使用集群模式来支撑。

1、多个nginx+keepalived
2、自主机房F5负载；因为公司各项目以及场景不同上面2种方式均使用运营稳定正常
最近公司一套国外的项目环境，想尝试使用阿里云的内网slb作为负载内网的nacos集群vip，使用过程中各机器在同一个安全组内，ping和telnet均正常，只是奇怪的是，dubbo服务往slb vip注册的时候，经常性出现连接超时，部分服务显示为不健康的状态。slb作为阿里的产品，难道不支持作为这种场景下的vip使用么？

EN
Usually, for the sake of the stability of the registry, the production environment will choose to use the cluster mode to support.

1. Multiple nginx + keepalived

2. F5 load of the independent computer room; because of the different projects and scenarios of the company, the above two methods are stable and normal

Recently, in a foreign project environment, the company tried to use alicloud's intranet SLB as a Nacos cluster VIP loaded with intranet. During the use process, all machines were in the same security group, and Ping and telnet were normal. However, when Dubbo service regis
![QQ截图20200904120016](https://user-images.githubusercontent.com/17794120/92359125-4e67ea00-f11d-11ea-97ae-cab8789c23a6.png)
tered with SLB VIP, the connection timeout often occurred, and some services showed unhealthy status. As a product of Ali, does SLB not support the use of VIP in this scenario?

**Comment by KomachiSion** [comment]
自建nacos集群请自行排查，如果排查时遇到问题，请将问题相关日志及场景贴出。

建议使用issue模版进行提交。

**Comment by diaodiaofly** [comment]
> 自建nacos集群请自行排查，如果排查时遇到问题，请将问题相关日志及场景贴出。
> 
> 建议使用issue模版进行描述。

多谢提醒，可否在此贴继续讨论呢？
购买的内网slb分配的ip是172.27.228.81   监听tcp8848端口     slb后面挂载了3台ecs，nacos启动的端口分别都是8848.
应用程序配置的注册中心地址nacos://172.27.228.81:8848（slb），程序启动出现上面的1楼截图中的异常。不知我提供哪部分日志方便您帮忙看呢？

**Comment by KomachiSion** [comment]
那我先标记讨论，看下社区是否有人有相同或者类似的问题。

**Comment by KomachiSion** [comment]
然后上述那个错误可能是slb的问题，也可能是网络设置的问题。因为你是自建的nacos集群，可以考虑打开access_log，或者抓包一下看看，请求有没有从slb转发出去。

也可以问一下slb的人员，看下是不是哪里设置有问题。
