### ISSUE TITLE
需要额外的配置才能开启权限控制吗

### ISSUE THREAD

**Issue by lin-mt** [alibaba/nacos#3774]
**Describe the bug**

权限控制不生效
Permission control is not in effect

**Expected behavior**
可以成功控制权限
Permissions can be successfully controlled

**Acutally behavior**
权限配置无效
Invalid permission configuration

**How to Reproduce**
使用 standalone 模式启动（Start using the Standalone mode）
1. 创建用户名密码均为 test 的用户（Create a user whose username and password are all Test）
2. 在角色管理创建角色名用户名均为 test 的数据（In the role management, create data with the role name and the user name both as Test）
3. 创建空间名和描述均为 test 的命名空间（Create a namespace with the name and description of test）
4. 在角色管理添加角色名为 test、资源选择 test、动作选择读写（Add the role name test to role management, resource select Test, action select Read and write）
5. 退出nacos账号（Log out of nacos）
6. 登录test账号（Login to test account）
7. 成功访问 public 空间（无报错信息）[Successful access to public space (no error message)]
8. 在public空间成功发布配置（Successfully publish the configuration in public space）
![image](https://user-images.githubusercontent.com/58337359/92366585-f08ccf80-f127-11ea-9ca8-5c0f681f5d45.png)
![image](https://user-images.githubusercontent.com/58337359/92366611-f8e50a80-f127-11ea-98c3-43e2d7ea514f.png)
![image](https://user-images.githubusercontent.com/58337359/92366176-60e72100-f127-11ea-89f1-cacccab7c64e.png)
![image](https://user-images.githubusercontent.com/58337359/92366193-67759880-f127-11ea-81f0-6e6d754b4604.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 1.3.2

**Additional context**

**Comment by KomachiSion** [comment]
`nacos.core.auth.enabled=true`

**Comment by xiaoxiangzhenyu** [comment]
> `nacos.core.auth.enabled=true`

docker nacos 属性文件 外部化配置 权限不生效 问题

**Comment by KomachiSion** [comment]
docker 使用环境变量`NACOS_AUTH_ENABLE`

**Comment by lin-mt** [comment]
> `nacos.core.auth.enabled=true`

这个配置开启之后就可以了，文档里面找不到这部分的内容哈，在 `config/application.properties` 里面找到了，然后发现了这个配置 `nacos.core.auth.system.type`，后续是否有考虑 auth 相关的提供用户自定义扩展呢，如果支持用户自定义扩展的话，目前 `jar` 启动的方式好像不太方便，是否提供一个console 的 springboot starter 呢

**Comment by lin-mt** [comment]
访问没有权限的空间
![image](https://user-images.githubusercontent.com/58337359/92429244-eae4c780-f1c3-11ea-9eba-54ef168d57a6.png)
切换到有权限的空间
![image](https://user-images.githubusercontent.com/58337359/92429330-28e1eb80-f1c4-11ea-80b8-acf2d3c14221.png)

从没有权限的空间切换到有权限的空间，依然显示为加载中，可以改下前端的代码，或者只显示有权限的空间，就不会有这个问题了，使用只显示有权限的空间的这种方案解决的话（个人感觉这种方案会比较合理），这个 issue https://github.com/alibaba/nacos/issues/2454 也可以同时关闭了

PS：这个问题需要重新开一个 issue 吗

**Comment by xiaoxiangzhenyu** [comment]
> docker 使用环境变量`NACOS_AUTH_ENABLE`

谢谢

**Comment by lin-mt** [comment]
@KomachiSion hello，前面有两个疑问可以帮忙解答下吗

**Comment by KomachiSion** [comment]
> 访问没有权限的空间
> ![image](https://user-images.githubusercontent.com/58337359/92429244-eae4c780-f1c3-11ea-9eba-54ef168d57a6.png)
> 切换到有权限的空间
> ![image](https://user-images.githubusercontent.com/58337359/92429330-28e1eb80-f1c4-11ea-80b8-acf2d3c14221.png)
> 
> 从没有权限的空间切换到有权限的空间，依然显示为加载中，可以改下前端的代码，或者只显示有权限的空间，就不会有这个问题了，使用只显示有权限的空间的这种方案解决的话（个人感觉这种方案会比较合理），这个 issue #2454 也可以同时关闭了
> 
> PS：这个问题需要重新开一个 issue 吗

duplicate with #2835

**Comment by KomachiSion** [comment]
> > `nacos.core.auth.enabled=true`
> 
> 这个配置开启之后就可以了，文档里面找不到这部分的内容哈，在 `config/application.properties` 里面找到了，然后发现了这个配置 `nacos.core.auth.system.type`，后续是否有考虑 auth 相关的提供用户自定义扩展呢，如果支持用户自定义扩展的话，目前 `jar` 启动的方式好像不太方便，是否提供一个console 的 springboot starter 呢

目前没有这个计划，今后可能会对auth模块重新设计。到时候再考虑把

**Comment by KomachiSion** [comment]
No more question for this issue from author. Close issue.

**Comment by ligerman33** [comment]
> No more question for this issue from author. Close issue.



> docker 使用环境变量`NACOS_AUTH_ENABLE`

您好，docker 下哪个文件下引用到这个环境变量了，我看conf/application.properties没有引用到这个环境变量
