### ISSUE TITLE
service is not found when groupName is blank

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3779]
**Describe the bug**
service is not found when groupName is blank. if groupName is blank, when request /v1/ns/catalog/service. if DistroFilter.doFilter,it will set groupName as 'DEFAULT_GROUP', but real serviceName's groupName is blank,such as '@@service'

![image](https://user-images.githubusercontent.com/22524871/92428626-2ed6cd00-f1c2-11ea-82b5-9110bda405a8.png)
![image](https://user-images.githubusercontent.com/22524871/92428634-38f8cb80-f1c2-11ea-8f2e-545582cab93c.png)

**Comment by horizonzy** [comment]
the logic should be same as sdk.serviceName should set as groupName@@serviceName,instead of serviceName=serviceName,groupName=groupName.

**Comment by KomachiSion** [comment]
We need to discuss a solution to resolve it.

**Comment by KomachiSion** [comment]
Fixed by check registered groupName, the groupNamd can't be empty string

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/5196
