### ISSUE TITLE
nacos服务列表丢失服务数据

### ISSUE THREAD

**Issue by engimatic** [alibaba/nacos#3781]
**Describe the bug**
环境：
nacos: 1.3.2  不存储数据
spring cloud alibaba: 2.2.1
spring cloud dubbo:2.2.1
运行一段时间后，nacos服务列表，服务会间歇性丢失，时而能看到某些服务，时而丢失某些服务，导致部分服务找不到privider

**Expected behavior**
希望nacos列表服务稳定，不会丢失服务注册信息

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by engimatic** [comment]
刷新
![image](https://user-images.githubusercontent.com/14733591/92461853-5054aa80-f1fc-11ea-83b9-6fa461a9bdda.png)


![image](https://user-images.githubusercontent.com/14733591/92461888-5c406c80-f1fc-11ea-826c-5ad8a9f97c0e.png)


![image](https://user-images.githubusercontent.com/14733591/92461919-67939800-f1fc-11ea-81b0-71cbd5225a19.png)

**Comment by KomachiSion** [comment]
应该是客户端那边心跳是上报有问题，导致provider因为不健康而被删除，然后你控制台选择了隐藏空服务，就变成这样了。

建议查一下日志，看下心跳上报的问题是什么。

**Comment by cokiMing** [comment]
您好，

1.3.2版本我们这边也遇到了同样的问题，且可以复现。

具体步骤：
1.  在nacos控制台点击服务下线
2.  再在nacos控制台点击服务上线
3.  在nacos控制台删除该服务
4.  重启该服务
5.  此时刷新nacos控制台列表，就会出现服务会间歇性丢失，且一段时间后该服务出现不可用的状态

**Comment by sanxun0325** [comment]
@i will solve it@

**Comment by engimatic** [comment]
> 您好，
> 
> 1.3.2版本我们这边也遇到了同样的问题，且可以复现。
> 
> 具体步骤：
> 
> 1. 在nacos控制台点击服务下线
> 2. 再在nacos控制台点击服务上线
> 3. 在nacos控制台删除该服务
> 4. 重启该服务
> 5. 此时刷新nacos控制台列表，就会出现服务会间歇性丢失，且一段时间后该服务出现不可用的状态


暂时没有空闲时间去仔细看这个问题，不过就我的使用经验来看，感觉与dubbo注册中心有关。当使用spring-cloud当做我的dubbo registry address，虽然服务粒度维度变化了，但是引起了很多的bug。当我使用nacos当错dubbo registry address的时候，虽然在服务列表粒度变细，但是不会产生意料之外的bug

**Comment by zrlw** [comment]
> 您好，
> 
> 1.3.2版本我们这边也遇到了同样的问题，且可以复现。
> 
> 具体步骤：
> 
> 1. 在nacos控制台点击服务下线
> 2. 再在nacos控制台点击服务上线
> 3. 在nacos控制台删除该服务
> 4. 重启该服务
> 5. 此时刷新nacos控制台列表，就会出现服务会间歇性丢失，且一段时间后该服务出现不可用的状态

不用重启服务，重复执行1、2、3两次就能复现。
