### ISSUE TITLE
the springboot app can't auto refresh the value from nacos

### ISSUE THREAD

**Issue by caojiantong** [alibaba/nacos#3784]
@Configuration
@EnableNacosConfig
@EnableNacosDiscovery
@NacosPropertySource(dataId = "example",autoRefreshed = true)
public class NacosConfiguration {
}

@NacosValue(value = "${useLocalCache.test:false}",autoRefreshed = true)
    private boolean useLocalCache;

it works ,but  any one of annotation without autoRefreshed=true,it doesn't work.
@NacosPropertySource(dataId = "example")
or 
@NacosValue(value = "${useLocalCache.test:false}")

why?

**Comment by mark4z** [comment]
May be you forgot the ‘@RefeshScope’

**Comment by caojiantong** [comment]
> May be you forgot the ‘@RefeshScope’
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>
this dependecy doesn't hava the annotation,it is from springcloud

**Comment by mark4z** [comment]
> > May be you forgot the ‘@RefeshScope’
> 
> com.alibaba.boot nacos-config-spring-boot-starter 0.2.7 this dependecy doesn't hava the annotation,it is from springcloud

Sorry, the right way to use it like '@NacosValue(value = "${foo}", autoRefreshed = true)'

**Comment by DaySurprise** [comment]
but I set autoRefreshed on dataId, Is invalid?
