### ISSUE TITLE
Retryfailedtask() after failure to synchronize information

### ISSUE THREAD

**Issue by gokjava** [alibaba/nacos#3786]
retryfailedtask() after failure to synchronize information, the code is as follows
同步信息失败后调用retryfailedtask()，代码如下:
`

private void retryFailedTask(Object key, AbstractDelayTask task) {
        task.setLastProcessTime(System.currentTimeMillis()); // record time
        addTask(key, task); // readd task
 }

`

If one of the registries is inaccessible, it will lead to requests all the time. It is recommended to adjust to Eureka's idempotent growth delay synchronization.
如果其中一个注册中心无法访问，会导致一直请求，建议调整为Eureka的幂等增长延时同步。

**Comment by KomachiSion** [comment]
这里出于对实时性的考虑，没有选择幂等增加时延。
另一方面，这个地方主要处理的是归并任务，这个任务处理应该以非阻塞且常态化成功为准，实际执行同步任务在分发到异步线程的DistroExecuteTask中

**Comment by gokjava** [comment]
If one of them cannot be requested, each registration will continuously access the queue to add tasks.
如果有一台无法请求，每次注册都会不停访问像队列中添加任务。

If there are too many registered services and the queue length is too large, there will be time delay when new services are registered.
如果注册的服务多了，使得队列长度过大，会导致新的服务注册的时候出现时间方面的延时。

It is suggested to add a new policy with delay. 
建议添加一个新的有延时的策略。

**Comment by gokjava** [comment]
If one of them cannot be requested, each registration will continuously access the queue to add tasks.
如果有一台无法请求，每次注册都会不停访问像队列中添加任务。

If there are too many registered services and the queue length is too large, there will be time delay when new services are registered.
如果注册的服务多了，使得队列长度过大，会导致新的服务注册的时候出现时间方面的延时。

It is suggested to add a new policy with delay. 
建议添加一个新的有延时的策略。

**Comment by gokjava** [comment]
If one of them cannot be requested, each registration will continuously access the queue to add tasks.
如果有一台无法请求，每次注册都会不停访问像队列中添加任务。

If there are too many registered services and the queue length is too large, there will be time delay when new services are registered.
如果注册的服务多了，使得队列长度过大，会导致新的服务注册的时候出现时间方面的延时。

It is suggested to add a new policy with delay. 
建议添加一个新的有延时的策略。

**Comment by gokjava** [comment]
If one of them cannot be requested, each registration will continuously access the queue to add tasks.
如果有一台无法请求，每次注册都会不停访问像队列中添加任务。

If there are too many registered services and the queue length is too large, there will be time delay when new services are registered.
如果注册的服务多了，使得队列长度过大，会导致新的服务注册的时候出现时间方面的延时。

It is suggested to add a new policy with delay. 
建议添加一个新的有延时的策略。

**Comment by KomachiSion** [comment]
这方面考虑过了已经， 同一个服务的任务会进行合并，如果某一台无法请求，无论是否增加延时，这个服务的任务都在池子里，但是增加了延时意味着对端服务回复的时候，停留在池子里的时间变得更长，不增加延时反而能在回复的第一时间把任务处理到。
