### ISSUE TITLE
client error: invalid param. For input string: "${nacos.config.maxRetry${nacos.maxRetry:}}"

### ISSUE THREAD

**Issue by dashuaigege** [alibaba/nacos#3787]
**Describe the bug**
在1.3.1和1.3.2的版本中，若没有明确指定 nacos.config.max-retry 的值，启动springboot程序，将会报如标题所示错误。

**Expected behavior**
预期程序正常启动，该值采用默认值3

**Acutally behavior**
实际上会报如标题所示错误。

**How to Reproduce**
调试发现，在1.3.0版本中，采用的是org.apache.commons.lang3.math.NumberUtils.toInt(String str, int defaultValue)方法。
而报错的版本采用的是com.alibaba.nacos.common.utils.ConvertUtils.toInt(String val, int defaultValue)方法。
理论上报错版本的方法也没问题，但是不知道为什么在默认情况下传进来的val的值是${nacos.config.maxRetry${nacos.maxRetry:}}，导致程序出错。

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.2, nacos-client 1.3.2]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by lin-mt** [comment]
@i will solve it@

**Comment by mark4z** [comment]
@Mark4z will solve it@

**Comment by mark4z** [comment]
> **Describe the bug**
> 在1.3.1和1.3.2的版本中，若没有明确指定 nacos.config.max-retry 的值，启动springboot程序，将会报如标题所示错误。
> 
> **Expected behavior**
> 预期程序正常启动，该值采用默认值3
> 
> **Acutally behavior**
> 实际上会报如标题所示错误。
> 
> **How to Reproduce**
> Steps to reproduce the behavior:
> 调试发现，在1.3.0版本中，采用的是org.apache.commons.lang3.math.NumberUtils.toInt(String str, int defaultValue)方法。
> 而报错的版本采用的是com.alibaba.nacos.common.utils.ConvertUtils.toInt(String val, int defaultValue)方法。
> 理论上报错版本的方法也没问题，但是不知道为什么在默认情况下传进来的val的值是${nacos.config.maxRetry${nacos.maxRetry:}}，导致程序出错。
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Centos]
> * Version [e.g. nacos-server 1.3.2, nacos-client 1.3.2]
> * Module [e.g. naming/config]
> * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> 
> **Additional context**
> Add any other context about the problem here.

Mybey the problem on dubbo. I can't resume it.

**Comment by mark4z** [comment]
> **Describe the bug**
> 在1.3.1和1.3.2的版本中，若没有明确指定 nacos.config.max-retry 的值，启动springboot程序，将会报如标题所示错误。
> 
> **Expected behavior**
> 预期程序正常启动，该值采用默认值3
> 
> **Acutally behavior**
> 实际上会报如标题所示错误。
> 
> **How to Reproduce**
> Steps to reproduce the behavior:
> 调试发现，在1.3.0版本中，采用的是org.apache.commons.lang3.math.NumberUtils.toInt(String str, int defaultValue)方法。
> 而报错的版本采用的是com.alibaba.nacos.common.utils.ConvertUtils.toInt(String val, int defaultValue)方法。
> 理论上报错版本的方法也没问题，但是不知道为什么在默认情况下传进来的val的值是${nacos.config.maxRetry${nacos.maxRetry:}}，导致程序出错。
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Centos]
> * Version [e.g. nacos-server 1.3.2, nacos-client 1.3.2]
> * Module [e.g. naming/config]
> * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> 
> **Additional context**
> Add any other context about the problem here.

I can't resume it. Could u offer more info.

**Comment by dashuaigege** [comment]
<dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.3.2</version>
        </dependency>
     
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

<spring-boot.version>2.3.0.RELEASE</spring-boot.version>
采用上述版本。

**Comment by dashuaigege** [comment]
application.properties中只添加nacos.config.server-addr=127.0.0.1:8848这个配置，启动springboot程序。即会报错。

**Comment by mark4z** [comment]
The problem is not because of "${nacos.config.maxRetry${nacos.maxRetry:}}" but ConvertUtils.

In nacos-client 1.3.0 and before that init  properties from @NacosProperties  use NumberUtils, but in 1.3.1 and later change to ConvertUtils.

NumberUtils.toInt() catch the NumberFormatException and return default value. but the ConvertUtils do nothing, So the problem in here.


**NumberUtils.toInt()**
`    public static int toInt(final String str, final int defaultValue) {
        if (str == null) {
            return defaultValue;
        }
        **try {
            return Integer.parseInt(str);
        } catch (final NumberFormatException nfe) {
            return defaultValue;
        }**
    }`
**ConvertUtils.toInt()**
`    public static int toInt(String val, int defaultValue) {
        if (StringUtils.equalsIgnoreCase(val, NULL_STR)) {
            return defaultValue;
        }
        if (StringUtils.isBlank(val)) {
            return defaultValue;
        }
        **return Integer.parseInt(val);**
    }`

**Comment by mark4z** [comment]
> The problem is not because of "${nacos.config.maxRetry${nacos.maxRetry:}}" but ConvertUtils.
> 
> In nacos-client 1.3.0 and before that init properties from @NacosProperties use NumberUtils, but in 1.3.1 and later change to ConvertUtils.
> 
> NumberUtils.toInt() catch the NumberFormatException and return default value. but the ConvertUtils do nothing, So the problem in here.
> 
> ```
> NumberUtils.toInt()
>     public static int toInt(final String str, final int defaultValue) {
>         if (str == null) {
>             return defaultValue;
>         }
>         try {
>             return Integer.parseInt(str);
>         } catch (final NumberFormatException nfe) {
>             return defaultValue;
>         }
>     }
> ```
> 
> ```
> ConvertUtils.toInt()
>     public static int toInt(String val, int defaultValue) {
>         if (StringUtils.equalsIgnoreCase(val, NULL_STR)) {
>             return defaultValue;
>         }
>         if (StringUtils.isBlank(val)) {
>             return defaultValue;
>         }
>         return Integer.parseInt(val);
>     }
> ```
> 
> >

@KomachiSion So, if i want fix it. What should i do?

**Comment by horizonzy** [comment]
> > The problem is not because of "${nacos.config.maxRetry${nacos.maxRetry:}}" but ConvertUtils.
> > In nacos-client 1.3.0 and before that init properties from @NacosProperties use NumberUtils, but in 1.3.1 and later change to ConvertUtils.
> > NumberUtils.toInt() catch the NumberFormatException and return default value. but the ConvertUtils do nothing, So the problem in here.
> > ```
> > NumberUtils.toInt()
> >     public static int toInt(final String str, final int defaultValue) {
> >         if (str == null) {
> >             return defaultValue;
> >         }
> >         try {
> >             return Integer.parseInt(str);
> >         } catch (final NumberFormatException nfe) {
> >             return defaultValue;
> >         }
> >     }
> > ```
> > 
> > 
> > ```
> > ConvertUtils.toInt()
> >     public static int toInt(String val, int defaultValue) {
> >         if (StringUtils.equalsIgnoreCase(val, NULL_STR)) {
> >             return defaultValue;
> >         }
> >         if (StringUtils.isBlank(val)) {
> >             return defaultValue;
> >         }
> >         return Integer.parseInt(val);
> >     }
> > ```
> > 
> > 
> > >
> 
> @KomachiSion So, if i want fix it. What should i do?
you just fix the bug in your branch, and new pull request

**Comment by mark4z** [comment]
> > The problem is not because of "${nacos.config.maxRetry${nacos.maxRetry:}}" but ConvertUtils.
> > In nacos-client 1.3.0 and before that init properties from @NacosProperties use NumberUtils, but in 1.3.1 and later change to ConvertUtils.
> > NumberUtils.toInt() catch the NumberFormatException and return default value. but the ConvertUtils do nothing, So the problem in here.
> > ```
> > NumberUtils.toInt()
> >     public static int toInt(final String str, final int defaultValue) {
> >         if (str == null) {
> >             return defaultValue;
> >         }
> >         try {
> >             return Integer.parseInt(str);
> >         } catch (final NumberFormatException nfe) {
> >             return defaultValue;
> >         }
> >     }
> > ```
> > 
> > 
> > ```
> > ConvertUtils.toInt()
> >     public static int toInt(String val, int defaultValue) {
> >         if (StringUtils.equalsIgnoreCase(val, NULL_STR)) {
> >             return defaultValue;
> >         }
> >         if (StringUtils.isBlank(val)) {
> >             return defaultValue;
> >         }
> >         return Integer.parseInt(val);
> >     }
> > ```
> > 
> > 
> > >
> 
> @KomachiSion So, if i want fix it. What should i do?
> you just fix the bug in your branch, and new pull request

Ok, I will fix it later.

**Comment by mark4z** [comment]
> > > The problem is not because of "${nacos.config.maxRetry${nacos.maxRetry:}}" but ConvertUtils.
> > > In nacos-client 1.3.0 and before that init properties from @NacosProperties use NumberUtils, but in 1.3.1 and later change to ConvertUtils.
> > > NumberUtils.toInt() catch the NumberFormatException and return default value. but the ConvertUtils do nothing, So the problem in here.
> > > ```
> > > NumberUtils.toInt()
> > >     public static int toInt(final String str, final int defaultValue) {
> > >         if (str == null) {
> > >             return defaultValue;
> > >         }
> > >         try {
> > >             return Integer.parseInt(str);
> > >         } catch (final NumberFormatException nfe) {
> > >             return defaultValue;
> > >         }
> > >     }
> > > ```
> > > 
> > > 
> > > ```
> > > ConvertUtils.toInt()
> > >     public static int toInt(String val, int defaultValue) {
> > >         if (StringUtils.equalsIgnoreCase(val, NULL_STR)) {
> > >             return defaultValue;
> > >         }
> > >         if (StringUtils.isBlank(val)) {
> > >             return defaultValue;
> > >         }
> > >         return Integer.parseInt(val);
> > >     }
> > > ```
> > > 
> > > 
> > > >
> > 
> > 
> > @KomachiSion So, if i want fix it. What should i do?
> > you just fix the bug in your branch, and new pull request

I already create pull request.
