### ISSUE TITLE
spring.application.name

### ISSUE THREAD

**Issue by xuqing** [alibaba/nacos#379]
# Reporting bugs
如果使用bootstrap.properties，可以找到spring.application.name但是用bootstrap.yaml，则找不到spring.application.name属性。其它的像server-addr都是可以的

**Comment by flystar32** [comment]
我们的测试用例是包含这个场景的，能提供一个完整的最小复现的 example 吗？
更多的信息请参考，https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery

This case are included in our test case, can you provide a Minimal, Complete, and Verifiable example？

see this page for more information, https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery

**Comment by nkorange** [comment]
Close idle issue
