### ISSUE TITLE
JDK Http client do not handler CONTENT_ENCODING

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#3790]
**Describe the bug**
In `ResponseHandler` like `StringResponseHandler`, If the server return `gzip`  CONTENT_ENCODING, it will not try to decompress content but read content directly.
It may caused the content is not right or garbled text.

I think other `ResponseHandler` has the same problem.

**Expected behavior**
Handler `gzip` content correctly.

**Acutally behavior**
return garbled text.

**How to Reproduce**
1. publish a config in ACM
2. use 1.3.1 or 1.3.2 version SDK get the config
3. print the config got from ACM
4. See garbled text

**Desktop (please complete the following information):**
 - OS: Any OS
 - Version: nacos-client 1.3.1, 1.3.2
 - Module: config
 - SDK: original

**Additional context**
I think adding an encoding handler to do decompress will be better, which can not only support gzip.

**Comment by Maijh97** [comment]
@i will solve it@
