### ISSUE TITLE
nacos有像eurekaclient的shutdown方法吗？优雅停机需要。或者其他方式

### ISSUE THREAD

**Issue by jackding79** [alibaba/nacos#3792]

**Comment by KomachiSion** [comment]
1.3.1开始支持。
看`NamingService.shutDown` 和  `ConfigService.shutDown`

**Comment by jackding79** [comment]
@KomachiSion 好的，刚刚没找到，版本有点低了。去研究下。多谢了

**Comment by jackding79** [comment]
@KomachiSion 服务注册的时候，我把heleath状态改为false，但是一个心跳后就变正常了，怎么能保证一直处于不可用状态，直到我想让它处于可用？我看beat那里代码没法重写。

**Comment by KomachiSion** [comment]
控制台可以点击`下线`使得实例状态变为不可用（但是健康状态依然是健康），这个时候订阅者无法获取到该下线实例
