### ISSUE TITLE
控制台密码输入密码，连续点击浏览器回退，进入nacos

### ISSUE THREAD

**Issue by baozong-gao** [alibaba/nacos#3793]
系统：ubuntu 
浏览器：firefox
nacos版本：1.3.2
出错停留地址：http://console.nacos.io/nacos/index.html#/configurationManagement?dataId=&group=&appName=&namespace=&pageSize=&pageNo=
复现：使用密码提示失败后，连续点击回退按钮

**Comment by KomachiSion** [comment]
我是用safari和chrome的无痕模式都无法复现，估计是你firefox的cookie缓存生效了。

**Comment by KomachiSion** [comment]
看看社区有没有人能复现

**Comment by KomachiSion** [comment]
We can't reproduce your problem, it might  be caused by your local web cache.
