### ISSUE TITLE
服务提供者心跳怎么服务的

### ISSUE THREAD

**Issue by wu603772498** [alibaba/nacos#3794]
instance.isEphemeral() ==true 才有发起心跳
在cp 模式下，这个应该为false ，那么注册服务client如何给nacos 服务发送心跳，维护服务的状态呢

**Comment by KomachiSion** [comment]
持久化实例不通过心跳维持健康状态，是服务端主动检测，可以通过tcp http mysql等不同协议进行探测，默认tcp，只要能建立连接就认为是健康的。

细节看`com.alibaba.nacos.naming.healthcheck.HealthCheckProcessor`
