### ISSUE TITLE
nacos启动时报错

### ISSUE THREAD

**Issue by shadowhunterhh** [alibaba/nacos#3796]
昨天测试了一下用服务器和本地nacos搭建集群，但是后来已经把配置都删除了并且重启了服务器的nacos，但是本地nacos不启动时启动项目就会报错2020-09-10 10:01:21.096 [main] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS SocketTimeoutException httpGet] currentServerAddr:http://127.0.0.1:8848， err : connect timed out，可以正常连接服务器的nacos，这里报的ip也不是服务器ip，看起来似乎启动的还是集群模式，我用的启动命令是bash startup.sh -m standalone，求解怎么取消集群模式，谢谢！

**Comment by KomachiSion** [comment]
问题应该出来你客户端不在服务端， 你客户端一直在连本地8848端口。但是本地服务器没启动。

**Comment by shadowhunterhh** [comment]
> 问题应该出来你客户端不在服务端， 你客户端一直在连本地8848端口。但是本地服务器没启动。
我把nacos-server安装在服务器的，下面是本地bootstrap文件配置，server-addr配置的是服务的地址啊

# 配置中心url
spring.cloud.nacos.config.server-addr=111.229.166.***:8848
#本地开发 dev
spring.cloud.nacos.config.namespace=dev
#服务名
spring.application.name=datedu-service-base
#指定文件后缀
spring.cloud.nacos.config.file-extension=properties
#引用公共配置
spring.cloud.nacos.config.ext-config[0].data-id=common-config.properties
spring.cloud.nacos.config.ext-config[0].refresh=true

**Comment by shadowhunterhh** [comment]
> 问题应该出来你客户端不在服务端， 你客户端一直在连本地8848端口。但是本地服务器没启动。

之前一直没有问题的，直到我昨天上午试着搭建nacos集群，但是现在已经把服务器上的nacos-server重装了，本地服务启动时还是会报这个错，服务器上启动服务貌似不报错

**Comment by KomachiSion** [comment]
可以debug跟一下，`NacosConfigService` 为什么一直取localhost，而不是配置的服务器列表

**Comment by shadowhunterhh** [comment]
> 可以debug跟一下，`NacosConfigService` 为什么一直取localhost，而不是配置的服务器列表
我debug了一下，NacosConfigService第一次进去是我服务器的ip:8848，然后取到了服务器nacos上的配置，然后又进了一次，取了127.0.0.1:8848，导致后面连不上本地的nacos后报错，但是我没有任何地方配置本地nacos地址啊...现在nacos配置是存在mysql的，我在mysql查了没有相关配置，spring.cloud.nacos.config.server-addr也只配置了一个服务器的地址

**Comment by shadowhunterhh** [comment]
> 可以debug跟一下，`NacosConfigService` 为什么一直取localhost，而不是配置的服务器列表

我刚刚测试了，每次启动项目都会进两次NacosConfigService，第一次取spring.cloud.nacos.config.server-addr的配置，第二次取127.0.0.1:8848，请问除了在bootstrap中配置还有别的地方配置吗？我和同事在开发时会一直因为从本地nacos取配置而报错

**Comment by LShuai87** [comment]
@shadowhunterhh  需要将nacos的相关配置放在 bootstrap.yml配置中才能生效
