### ISSUE TITLE
权限分配后该用户有一个空间权限，登录有公共空间无权限页面就一直在loading，切换有权限的空间后页面还是loading,必须刷一下浏览器才可以，切回无权限的空间后继续提示和loading，在切回了还需要刷浏览器连接才可以

### ISSUE THREAD

**Issue by pig-stdv** [alibaba/nacos#3798]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by pig-stdv** [comment]
![image](https://user-images.githubusercontent.com/12934257/92689983-aa777c00-f372-11ea-871f-b9ca3bde609e.png)
其实有权限但是页面还停留在无权限的页面上

**Comment by pig-stdv** [comment]
一刷浏览器连接就好了，但是每次都得刷好费劲

**Comment by pig-stdv** [comment]
这个是前端的bug吧

**Comment by KomachiSion** [comment]
duplicate with #2835

**Comment by pig-stdv** [comment]
这个是在1.4.0的版本中解决么，目前看1.3.2还不行
