### ISSUE TITLE
nacos-0.5.0 控制台 我在第三页 编辑 完成后点击返回，返回分页第一页。期望：反回原有分页页面 （第三页）

### ISSUE THREAD

**Issue by haochencheng** [alibaba/nacos#380]
如题，期望编辑前是第几页就返回第几页。

**Comment by nkorange** [comment]
目前是编辑完就会停留在编辑页

**Comment by haochencheng** [comment]
@nkorange  配置列表有多个分页，我在第三页 编辑 其中的 一项 发布后 点击返回，现在会 直接返回第一页 。 不是很方便 ，期望 我在 第几页  点击返回  返回到 第几页。
![image](https://user-images.githubusercontent.com/20943919/61047215-91dba100-a411-11e9-88e8-e4c282603c16.png)

**Comment by nkorange** [comment]
不好意思，误解你的问题了

**Comment by haochencheng** [comment]
> 不好意思，误解你的问题了

没事的 是我没有描述清楚。

**Comment by song-bate** [comment]
还没解决吗
