### ISSUE TITLE
NullPointerException：RaftCore.signalPublish(RaftCore.java:195)

### ISSUE THREAD

**Issue by xiaoxiangzhenyu** [alibaba/nacos#3801]
![image](https://user-images.githubusercontent.com/5812240/92864984-5e8b0c80-f430-11ea-9a01-d538fe297648.png)

最新版本（1.3.2）的问题

**Comment by KomachiSion** [comment]
Can you provide full error log? the half of logs is hard to find out the problem.

**Comment by KomachiSion** [comment]
No necessary information to reproduce or find out problem, and author has no response. Close issue. If there are problem again, please open a new issue with full information.
