### ISSUE TITLE
Nacos删除配置后，sprintboot还是读到删除之前的值

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#3803]
在nacos server中，原来有itemKey1和itemKey2这2个配置，sprintboot读取正常
![image](https://user-images.githubusercontent.com/15244686/92875179-597f8a80-f43b-11ea-92b4-9ada168464b2.png)
![image](https://user-images.githubusercontent.com/15244686/92875245-69976a00-f43b-11ea-964c-43d63e1ee91b.png)

**这个时候删除itemKey2配置，读到还是之前的值而不是test2**
![image](https://user-images.githubusercontent.com/15244686/92875344-8764cf00-f43b-11ea-8246-651518c1d12f.png)

![image](https://user-images.githubusercontent.com/15244686/92875465-9fd4e980-f43b-11ea-93fe-1fe9f515d1eb.png)
![image](https://user-images.githubusercontent.com/15244686/92875543-b8dd9a80-f43b-11ea-871d-9f94d35f65d0.png)

**这和nacos-client本地cache有关吗，我尝试关闭本地缓存，但是似乎没开关**
![image](https://user-images.githubusercontent.com/15244686/92875745-e9253900-f43b-11ea-939d-d5f9670660de.png)

nacos版本：1.3.1
nacos-client版本1.2.0
 <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-actuator</artifactId>
            <version>0.2.7</version>
        </dependency>

**Comment by sanxun0325** [comment]
@FengJinghHua 
1：${itemKey2:test2} 是当服务启动时，如果itemKey2在nacos没有设置，则会把test2当做默认值。
2：目前@NacosValue配置更新机制：当配置文件有更新时会把整个配置内容加载回来，然后对配置内容转换成Properties，进行filed更新。
由于删除了itemKey2，则配置内容中就没有itemKey2了，所以就不会对客户端中使用itemKey2的filed进行更新。
3：这个都是在内存中和本地缓存无关。

**Comment by FengJinghHua** [comment]
@sanxun0325 谢谢你的解答，所以这是nacos的默认行为？感觉是不是如果itemKey2在nacos中被删除了，client应该更新为默认值更合适?是要改源码才可以做到这点吗，因为在nacos server端已经删除了itemKey2，在client中还读到的是删除前的值感觉有点歧义？

**Comment by sanxun0325** [comment]
@FengJinghHua 默认当前是这样的，如果在nacos中删除某个配置，client端设置成默认值这个需要讨论。
你如果想实现这样的效果，可以考虑利用配置监听去做这样的事情。

**Comment by FengJinghHua** [comment]
@sanxun0325 非常感谢，我往这方向试试，谢谢。

**Comment by jiangxch** [comment]
I have add this feature,[nacos-group/nacos-spring-project](https://github.com/nacos-group/nacos-spring-project/pull/225)

**Comment by jiangxch** [comment]
I have add this feature,[nacos-group/nacos-spring-project](https://github.com/nacos-group/nacos-spring-project/pull/225)
please review the code @sanxun0325

**Comment by waterWang** [comment]
我是这样解决的  https://waterwang.blog.csdn.net/article/details/118489812
