### ISSUE TITLE
nacos 1.3.2 + dubbo 2.7.8 cluster mode high cpu

### ISSUE THREAD

**Issue by lijiaxing3045354** [alibaba/nacos#3806]
**Describe the bug**
nacos 1.3.2 + dubbo 2.7.8 cluster mode high cpu

In our company's test environment, three Nacos instances are deployed on one machine without using containers. The CPU of each instance is about 100%.

At present, the Nacos console service list has more than 500 producer consumer services, and the configuration list has more than 1300. Want to know that CPU 100% is normal?

The attachment is the stack information that I exported

If not, how should I adjust?

Looking forward to the master's answer, thank you.

**Desktop (please complete the following information):**
 - OS: Centos
 - Version 1.3.2
 - Module naming/config
 - SDK dubbo

**Additional context**

[thread.txt](https://github.com/alibaba/nacos/files/5207615/thread.txt)

**Comment by KomachiSion** [comment]
only thread dump can help us locate problem.

Can you use `top` to find which thread is high load of CPU and provide the tid of `thread.txt`?

Or use arthus to print the profiles

**Comment by lijiaxing3045354** [comment]
[thread.txt](https://github.com/alibaba/nacos/files/5212111/thread.txt)
[mp.txt](https://github.com/alibaba/nacos/files/5212112/mp.txt)

**Comment by horizonzy** [comment]
in mp.txt.the high cpu tid is missed. you can use  'top -H -p pid', get the high nid.

**Comment by KomachiSion** [comment]
@lijiaxing3045354 There are no `tid` in your `top`, as @horizonzy said use `top -H -p pid`.

**Comment by lijiaxing3045354** [comment]
It should not have been lost, before in mp.txt Is to use "ps -mp pid -o THREAD,tid,time | sort -rn > mp.txt ”，in mp.txt more than 200 threads occupy 4% of the CPU, and the total CPU time should be 100%。Total number of threads mp.txt and thread.txt It's almost equal.

[top-H -p32002.txt](https://github.com/alibaba/nacos/files/5215669/top-H.-p32002.txt)

**Comment by lijiaxing3045354** [comment]
I used Arthas (thread - N 100 - I 5000) to diagnose the process and found no threads with high CPU consumption，Arthas does not reserve decimals in the output CPU time. It seems that the CPU time is evenly distributed to many threads. No blocked threads were found.
[arthas.txt](https://github.com/alibaba/nacos/files/5215807/arthas.txt)

**Comment by horizonzy** [comment]
in arthas.txt, the cpu occupying showed it's normally, can you apply your server's hardware info

**Comment by horizonzy** [comment]
and use `jstat -gc pid 5000` show the gc info. is the gc lead to cpu occupation.

**Comment by KomachiSion** [comment]
I see from `top-H -p32002.txt` and `arthas.txt`. And do not find high cpu.

**Comment by lijiaxing3045354** [comment]
System Information
        Manufacturer: IBM
        Product Name: System x3650 M4 : -[7915R01]-
        Family: System X

SMBIOS 2.7 present.
BIOS Information
        Vendor: IBM
        Version: -[VVE136AUS-1.60]-
        Release Date: 12/12/2013
        Address: 0xE0000
        Runtime Size: 128 kB
        ROM Size: 8192 kB
CPU Information
        32  Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
Memory Information
MemTotal:       98871456 kB
MemFree:          620304 kB
Buffers:          230596 kB
Cached:          6114832 kB
SwapCached:       871900 kB
Active:         63090676 kB
Inactive:        9408600 kB
Active(anon):   61403208 kB
Inactive(anon):  4886560 kB
Active(file):    1687468 kB
Inactive(file):  4522040 kB
Unevictable:    23767256 kB
Mlocked:        18189180 kB
SwapTotal:       8388604 kB
SwapFree:         754544 kB
Dirty:             92952 kB
Writeback:             0 kB
AnonPages:      89051744 kB
Mapped:           304824 kB
Shmem:             11344 kB

**Comment by KomachiSion** [comment]
We do not care about your machine config. We only need to know which thread cost much cpu.

**Comment by lijiaxing3045354** [comment]
None of the threads takes up a lot of CPU. Many threads (starting with http-nio-8848-exec, there are 200 in total) occupy an average core CPU, each accounting for about 0.4%.

**Comment by lijiaxing3045354** [comment]
找到原因了，问题的根源在于org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames0，line271，这个方法为了兼容旧版订阅服务名称，返回了两个serviceName，那个兼容的服务名称在nacos server上无法找到服务，就会每隔一秒（正常是10秒）去nacos server请求获取一次，因为频率过高，会导致nacos server CPU 居高不下。
在我将兼容服务名的代码注掉之后，CPU降到了50%左右，这应该是服务发现、心跳发送请求量比较大导致的，但还可以接受。
感谢两位大神的支持。

**Comment by horizonzy** [comment]
现在最新的代码已经优化了这块了。如果service下不存在实例，会降低客户端请求的频率。
