### ISSUE TITLE
Why my instance show one time  every 5 seconds ?

### ISSUE THREAD

**Issue by aiguo123** [alibaba/nacos#3812]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
my instance show one time  every 5 seconds

### Describe what you expected to happen
the instance should always exist

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
V1.0.0

### Anything else we need to know?
I have two instances,the one is normal,another show one time  every 5 seconds。
I take the interface   /nacos/v1/ns/catalog/instances?serviceName=xxxx，and found that the broken server app is null.

![image](https://user-images.githubusercontent.com/70306062/92969339-57efaa00-f4af-11ea-9a20-3d9f11a1fed6.png)

**Comment by horizonzy** [comment]
2.you can set system.param('project.name') in your nacos-client as your appName.

**Comment by horizonzy** [comment]
1.can you get more descrption for it?
2.you can set system.param('project.name') in your nacos-client as your appName.

**Comment by KomachiSion** [comment]
The reason may not be app `null`. I think it's beat info report failed. We need more information to find out the problem.
Can you open access_log and provide the client and server log to comment?

**Comment by KomachiSion** [comment]
No response and necessary information to reproduce problem. Close issue.
