### ISSUE TITLE
下载的nacos 解压后没有data和logs目录

### ISSUE THREAD

**Issue by HuChenXin123** [alibaba/nacos#3813]
<img width="824" alt="截屏2020-09-12 下午7 37 53" src="https://user-images.githubusercontent.com/71009725/92994743-772e1c00-f52f-11ea-9924-390529181107.png">

**Comment by horizonzy** [comment]
这几个文件是运行之前才会创建的

**Comment by KomachiSion** [comment]
这两个目录是运行后自动创建的。
