### ISSUE TITLE
nacos 1.3.2 The JSON string was truncated when writing Chinese characters

### ISSUE THREAD

**Issue by lijiaxing3045354** [alibaba/nacos#3815]
**Describe the bug**
DiskCache.write()->ConcurrentDiskUtil.writeFileContent()，The JSON string is truncated when writing Chinese characters，paramter content lenth is 4315,content.getBytes(charsetName) lenth is 4331.

![image](https://user-images.githubusercontent.com/39329138/93041670-a3f14900-f67f-11ea-9d52-934f4ca1f9d3.png)

**Comment by linqunhui** [comment]
没法重现您的问题@lijiaxing3045354

**Comment by lijiaxing3045354** [comment]
我使用的是Dubbo+nacos，当dubbo配置中<service>标签中的document字段包含中文字符的时候会出现这个问题。
不过看截图，在content.getBytes(charsetName)之后，字符长度会发生变化，然后channel.truncate会进行截断

**Comment by KomachiSion** [comment]
中文一个字 占1个字符串的length，当通过utf8处理成byte[]时，会变成3个字节。的确是可能会变长，这里可能需要优化一下了

**Comment by ljhrot** [comment]
@i will solve it@
