### ISSUE TITLE
/nacos/v1/ns/operator/metrics 403

### ISSUE THREAD

**Issue by mameng1992** [alibaba/nacos#3818]
A user with read and write permissions is configured in the project.But,When the project starts, the following error occurs:
[naming][548] - request: /nacos/v1/ns/operator/metrics failed, servers: [127.0.0.1:8080], code: 500, msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Sep 14 14:20:15 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>

nacos server 1.3.2
spring-cloud-starter-alibaba-nacos-discovery 2.2.2.RELEASE
spring-cloud-starter-alibaba-nacos-config 2.2.2.RELEASE

**Comment by KomachiSion** [comment]
duplicate with #2866
