### ISSUE TITLE
NacosDiscoveryClient: get service name from nacos server fail, java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by hanzhen1989** [alibaba/nacos#3819]
**Describe the bug**
getServiceList时从返回结果中获取count和doms报错，因为返回的内容为null。分析了下源码，貌似只有返回的http状态为302的时候会出现这个报错。什么情况下会出现302啊？本地没有复现，所以没有本地断点调试。 nacos客户端版本是1.3.1，spring-cloud-starter-alibaba-nacos-discovery版本为2.1.2.RELEASE

![image](https://user-images.githubusercontent.com/11624934/93052248-56350a80-f698-11ea-9aa8-5c5c36a0893a.png)

**How to Reproduce**
把注册中心从eureka换成nacos，注册中心使用集群模式。通过k8s service负载均衡代理nacos的三个节点，项目中填写的注册中心地址是k8s service负载均衡的地址

**Desktop (please complete the following information):**
 - OS: 阿里云的k8s
 - Version nacos-client 1.3.1，spring-cloud-starter-alibaba-nacos-discovery版本为2.1.2.RELEASE
 - Module naming
 - SDK spring-cloud-gateway, spring-cloud-alibaba-nacos

**Additional context**

**Comment by KomachiSion** [comment]
1. 应该是304时可能会出现这个问题。而不是302，304的状态吗定义为GET请求已处理，但是GET的内容并未发生变化
2. nacos服务端自身不会返回304状态码，很可能时负载均衡代理返回的
3. 您可以尝试在服务端和客户端都抓包查看一下，看下nacos服务端返回的数据和客户端接收到的数据是否一致。

**Comment by KomachiSion** [comment]
@hanzhen1989 Any process? If no more response, we will close this issue.

**Comment by hanzhen1989** [comment]
不使用负载均衡代理，直接填写三个nacos服务的地址，也出现这种情况呢，本地没有复现。生产环境上偶尔报一次错。

**Comment by nanpugood** [comment]
我是同样的问题，问题解决了吗
