### ISSUE TITLE
Example module in nacos project doesn't really help

### ISSUE THREAD

**Issue by poorguy-tech** [alibaba/nacos#3820]
I want to read the source code of nacos project and found that the example module in this project doesn't really help. It's hard to understand this project only by example module. 
It seems that the module is just useless comparing with nacos documentation.

**Comment by KomachiSion** [comment]
nacos-example module is an example to show a simple quick start of `nacos-client`.

if you are using spring-cloud or dubbo, there are other one example project named `nacos-group/nacos-example`

If you want to find an example for `nacos-server`, it depends the embedded nacos, but we do not implement it now.
