### ISSUE TITLE
 增加数据库版本管理特性（Add database version management features）

### ISSUE THREAD

**Issue by victor-1330** [alibaba/nacos#3822]
1.  提供数据库版本管理特性，用户无需关心数据库初始化和数据结构升级
Provide database version management features, users do not need to care about database initialization and data structure upgrade

2. 该特性提供一个开关，默认开启，有需要手工执行数据库初始化的可以通过环境变量关闭该特性
This feature provides a switch, which is turned on by default. If you need to initialize the database manually, you can turn off the feature through the environment variable

**Comment by KomachiSion** [comment]
1. I can't understand your request by your description. Do you mean like JPA done?

2. I think there is no need. If you need to initialize database manually. Just do it. nacos will use it directly.

**Comment by victor-1330** [comment]
1. nacos首次部署的时候，可以自动初始化相关表，减少部署的环节

When Nacos is deployed for the first time, the related tables can be initialized automatically to reduce the deployment phase

2. nacos后续版本升级有表结构变化或增减表时，自动执行变更，使用者不用关心数据库变化

When there are changes in the structure of tables or the increase or decrease of tables in subsequent versions of Nacos, the changes will be executed automatically, and users do not need to pay attention to the changes of database

3. 提供一个开关，用来关闭这个特性

Provide a switch to turn this feature off
