### ISSUE TITLE
nacos-client-1.2.1 can connect nacos-1.3.1; But nacos-client-1.3.2 can't connect   --  403

### ISSUE THREAD

**Issue by DerekHQ** [alibaba/nacos#3823]
When using spring-cloud-alibaba-2.2.1.RELEASE , it dependency  nacos-client-1.2.1; Our nacos server version is 1.3.1 and set auth=true;  It work ok!
But when we upgrade to spring-cloud-alibaba-2.2.2.RELEASE, it dependency  nacos-client-1.3.2; Then it can not connect to nacos server 1.3.1, it throw 403 error!
Did server-1.3.1  support  client-1.2.1 ,but not support client-1.3.2?

**Comment by KomachiSion** [comment]
Please use issue template to describe your issue. Otherwise lark too much information so that no one can help you
