### ISSUE TITLE
如何实现手动注册

### ISSUE THREAD

**Issue by TNZong** [alibaba/nacos#3824]
比如一个应用里面除了主服务端口外还有一个socket服务有一个独立端口，如何实现将socket服务注册到nacos中，实现gateway负载均衡转发

**Comment by KomachiSion** [comment]
那其实就是两个服务，registerInstance调用两次就好

**Comment by TNZong** [comment]
> 那其实就是两个服务，registerInstance调用两次就好

如果是spring cloud 项目呢，手动register这个socket 服务有点奇怪

**Comment by KomachiSion** [comment]
spring cloud项目会需要一个app注册成2个服务吗？ 我理解一个sc app就是一个service实例。可能其他的注册中心也不行？

**Comment by TNZong** [comment]
好🎱，那只能拆了
