### ISSUE TITLE
org.apache.commons.lang3 Version compatibility is not friendly

### ISSUE THREAD

**Issue by p564825336** [alibaba/nacos#3845]
**Describe the bug**
org.apache.commons.lang3 Version compatibility is not friendly

**Expected behavior**
if (StringUtils.isNotEmpty(ramRoleName)) {
		properties.put(PropertyKeyConst.RAM_ROLE_NAME,
		environment.resolvePlaceholders(ramRoleName));
}

**Acutally behavior**
This is NacosPropertiesBuilder.java
![捕获](https://user-images.githubusercontent.com/11329546/93303704-7991be00-f82e-11ea-820b-93ab34cf6c3f.PNG)
if (StringUtils.isNoneEmpty(ramRoleName)) {
		properties.put(PropertyKeyConst.RAM_ROLE_NAME,
		environment.resolvePlaceholders(ramRoleName));
}

**How to Reproduce**
1. maven pom.xml add nacos-config-spring-boot-starter
2. version is 0.2.6 or 0.2.7
3. There is a detailed example:
      ```
      <!-- https://mvnrepository.com/artifact/com.alibaba.boot/nacos-config-spring-boot-starter -->
      <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
      </dependency>
   ```

**Desktop (please complete the following information):**

 - OS: [Window10]
 - Version [nacos-config-spring-boot-starter 0.2.6, nacos-config-spring-boot-starter 0.2.7]

**Additional context**
nacos-config-spring-boot-starter 0.2.6和0.2.7版本对org.apache.commons.lang3兼容不友好

**Comment by EvanWang1991** [comment]
@i will solve it@
