### ISSUE TITLE
naming-server.log一直在跳  2020-09-17 11:35:58,967 INFO receive config info: unknown#111.229.166.xxx:8848#1600313758965#4

### ISSUE THREAD

**Issue by shadowhunterhh** [alibaba/nacos#3851]
我用三台服务器部署了集群后，发现naming-server.log一直在跳2020-09-17 11:35:58,967 INFO receive config info: unknown#111.229.166.xxx:8848#1600313758965#4，三台服务器此处的ip都是自身的ip，请问这是正常的吗？还是我的配置有误？

After Deploying the cluster with three servers, I found naming-server.log has： 
2020-09-17 11:35:58 and 967 INFO receive config INFO: Unknown# 111.229.166. XXX :8848#1600313758965#4.
 The IP of the three servers here is their own IP, is that normal?Or am I misconfigured?

**Comment by KomachiSion** [comment]
正常的，每一条数据就是服务端之间的一次心跳汇报，说明你的服务端之间的心跳是正常的。

**Comment by shadowhunterhh** [comment]
> 正常的，每一条数据就是服务端之间的一次心跳汇报，说明你的服务端之间的心跳是正常的。
感谢
