### ISSUE TITLE
同一版本nacos在windows运行一段时间后cpu占用达100%, 在linux下无此问题

### ISSUE THREAD

**Issue by xx888666** [alibaba/nacos#3854]
同一版本nacos在windows运行一段时间后cpu占用达100%, 在linux下无此问题

**Comment by KomachiSion** [comment]
方便用arthus在100%cpu的时候打一下火焰图吗？ 或者协助我们dump出来thread并且通过windows命令找到是哪个线程占用了cpu吗？

**Comment by xx888666** [comment]
> 方便用arthus在100%cpu的时候打一下火焰图吗？ 或者协助我们dump出来thread并且通过windows命令找到是哪个线程占用了cpu吗？

您好, 我用windows查看nacos哪些进程占用cpu时, 没有发现占用了很大cpu的线程, 但是发现了很多叫做New I/O worker的线程, 每个线程都占用了2%-3%的cpu

**Comment by chuntaojun** [comment]
这个应该和tomcat容器有关系

**Comment by KomachiSion** [comment]
是不是我们当前用的这个tomcat版本在window下面存在问题？ 可能需要社区使用window环境的贡献者排查下

**Comment by xx888666** [comment]
> 是不是我们当前用的这个tomcat版本在window下面存在问题？ 可能需要社区使用window环境的贡献者排查下

好的谢谢, 请问社区的网址和当前用的tomcat版本是什么呢?

**Comment by tanranv5** [comment]
AsyncProfiler error: Current OS do not support AsyncProfiler, Only support Linux/Mac.      window下怎么生成火焰图呢

**Comment by KomachiSion** [comment]
> > 是不是我们当前用的这个tomcat版本在window下面存在问题？ 可能需要社区使用window环境的贡献者排查下
> 
> 好的谢谢, 请问社区的网址和当前用的tomcat版本是什么呢?

可以根据你所使用的版本，到源代码里看一下pom文件

**Comment by KomachiSion** [comment]
> AsyncProfiler error: Current OS do not support AsyncProfiler, Only support Linux/Mac. window下怎么生成火焰图呢

**Comment by sunset535** [comment]
今天刚测了1.3.2版本  windows上面这个问题依然存在

**Comment by sunset535** [comment]
![image](https://user-images.githubusercontent.com/3860179/95724644-34d03a00-0ca9-11eb-9a86-50529087d6f0.png)
![image](https://user-images.githubusercontent.com/3860179/95724670-3a2d8480-0ca9-11eb-8752-ee330efef6c1.png)
![image](https://user-images.githubusercontent.com/3860179/95724691-3d287500-0ca9-11eb-87c1-122ab71f5904.png)

**Comment by sunset535** [comment]
@KomachiSion   用过1.1.4  1.2.1  1.3.2 这三个版本  都有同样的问题   这三个版本的tomcat版本都是9.0.13

**Comment by KomachiSion** [comment]
用develop分支打一个1.4.0-SNAPSHOT的包试一下，develop分支更新了tomcat的版本，可能会修复这个问题

**Comment by sunset535** [comment]
@KomachiSion   刚试了   还是同样的问题  
 developer分支   本地打包 1.4.0-SNAPSHOT包  9.0.38 tomcat版本
![image](https://user-images.githubusercontent.com/3860179/95815683-cbefcd00-0d4f-11eb-910d-b5245f5b3d47.png)
![image](https://user-images.githubusercontent.com/3860179/95815821-18d3a380-0d50-11eb-8a33-0b49cb823073.png)

**Comment by sunset535** [comment]
@KomachiSion   nacos启动时间是十点   大概两小时不到的时候  就会出现这个问题

**Comment by horizonzy** [comment]
@xx888666 你好。你那边的windows机器上安装过什么代理软件吗。机器上是否存在虚拟机带的虚拟网卡呢

**Comment by horizonzy** [comment]
track: https://issues.apache.org/jira/browse/HTTPCORE-650

**Comment by xx888666** [comment]
> @xx888666 你好。你那边的windows机器上安装过什么代理软件吗。机器上是否存在虚拟机带的虚拟网卡呢

你好, 没有安装过呢, 之前一切都是正常, 突然有一天开始就不行了, 中间没有安装过其他软件, 但是可能存在windows系统自动更新的情况

**Comment by KomachiSion** [comment]
Refer to #3854
