### ISSUE TITLE
请教，可以在配置详情里加上上一个版本的配置改动吗

### ISSUE THREAD

**Issue by zscboy** [alibaba/nacos#3855]
![image](https://user-images.githubusercontent.com/8179656/93432255-d60ce000-f8f7-11ea-87ac-2c1d1f38f1da.png)
这样打开配置详情页面，可以立即看到这个版本相对上个版本改了什么

类似下面这样：

![image](https://user-images.githubusercontent.com/8179656/93433127-ff7a3b80-f8f8-11ea-94b9-8e95903e0628.png)

**Comment by KomachiSion** [comment]
目前没有支持，我标记一下，看看社区有没有对此功能感兴趣贡献的。

**Comment by jzhishu** [comment]
@I will solve it@

**Comment by KomachiSion** [comment]
So this issue and PR is not submit to develop branch rather than merge into fork branch? 

Should we merge it into develop branch or not?

**Comment by jzhishu** [comment]
It should be merged into the develop branch when complete
