### ISSUE TITLE
nacos springcloud 权限控制打开后 客户端403 

### ISSUE THREAD

**Issue by yanghaolei321** [alibaba/nacos#3856]
打开nacos.core.auth.enabled=true后 客户端无法连接服务器一直报403
项目引入的是spring-cloud-alibaba-nacos的两个starter nacos-client升级版本到1.2.0
找到NacosConfigProperties这个class 是在spring-cloud-alibaba-nacos-config-2.1.1.RELEASE中
发现没有username和password字段。 这个怎么解决

**Comment by KomachiSion** [comment]
升级spring-cloud-alibaba-nacos的版本
