### ISSUE TITLE
dubbo向nacos注册时不能选择适当的命名空间

### ISSUE THREAD

**Issue by cjxiong** [alibaba/nacos#3857]
![image](https://user-images.githubusercontent.com/29563362/93437061-2424e200-f8fe-11ea-97a1-23149be6e304.png)
nacos配置中心是可以选择恰当的命名空间的，但是dubbo只能依靠版本号区分。。
想请问下是否有相关文档

Nacos configuration center is can choose appropriate namespace, but dubbo can only rely on the version number..
Would like to ask whether the relevant documents

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/use-nacos-with-dubbo.html

**Comment by cjxiong** [comment]
刚刚试了下，在dubbo.xml里面配置是不生效的。
需要在yml文件中配置后缀方可

&nbsp;
