### ISSUE TITLE
conf/cluster.conf多出两条记录

### ISSUE THREAD

**Issue by aakejiang** [alibaba/nacos#3858]
nacos 1.3.2版本

环境变量：PREFER_HOST_MODE=hostname

![image](https://user-images.githubusercontent.com/68629395/93546673-e4113e00-f995-11ea-9270-e0a6aff03624.png)

conf/cluster.conf 是被监听了么，为啥我加了三行记录（nacos-server-0:8848 nacos-server-1:8848 nacos-server-2:8848），会多出来一行注释和一个本机hostname记录？

期望：不要多加记录，以用户输入的为准。（如果检测到没有端口，自动加8848端口是可以的）

**Comment by aakejiang** [comment]
多出的第二行会导致节点变成了4个，无法选出master。

**Comment by chuntaojun** [comment]
nacos默认不是走域名模式，注意看官网的参数配置设置

**Comment by aakejiang** [comment]
@chuntaojun 这是个bug么，啥时候能解决，急！
我是k8s 部署的，如果搞成ip的，pod一重建ip就会变，每次就得改cluster.conf文件了，非常痛苦。
目前想到的就是这种写固定deployment名称的方式，通过集群dns解析，但是因为自动给我加了本机的hostname，这个方式也走不通了😓。
如果有其他更好的办法，也请告知。

**Comment by chuntaojun** [comment]
今天修复

发自我的iPhone

在 2020年9月18日，10:14，aakejiang <notifications@github.com> 写道：

﻿

@chuntaojun<https://github.com/chuntaojun> 这是个bug么，啥时候能解决，急！
我是k8s 部署的，如果搞成ip的，pod一重建ip就会变，每次就得改cluster.conf文件了，非常痛苦。
目前想到的就是这种写固定deployment名称的方式，通过集群dns解析，但是因为自动给我加了本机的hostname，这个方式也走不通了😓。
如果有其他更好的办法，也请告知。

**Comment by aakejiang** [comment]
@chuntaojun 版本1.3.1 有这个问题么，要不我先回滚到这个版本？

**Comment by chuntaojun** [comment]
重新看了下，并非bug，请设置环境变量参数nacos.server.ip=domain，告知nacos他自己的域名是什么

**Comment by aakejiang** [comment]
@chuntaojun 哪里有文档对这个参数的介绍，找了一圈没看到

**Comment by aakejiang** [comment]
另外，为啥要对用户的输入 进行 篡改呢？

**Comment by aakejiang** [comment]
name | description | option
-- | -- | --
NACOS_SERVER_IP | 多网卡下的自定义nacos服务器IP |  

加了这个后，nacos-server启动不了额

**Comment by aakejiang** [comment]
@chuntaojun 能否加钉钉聊下这个问题，已经卡好几天了，钉钉号：xsm4lfb

**Comment by KomachiSion** [comment]
启动不起来报什么错？

**Comment by LessOrMore** [comment]
我们也遇到了相同的问题，各种服务注册不成功，调试了一下午，最终发现配置文件中多了这行记录。 这个问题最终怎么解决？

**Comment by yuqiyang01** [comment]
同问这个问题，conf/cluster.conf为什么会多记录呢？

**Comment by KomachiSion** [comment]
> 同问这个问题，conf/cluster.conf为什么会多记录呢？

这部分逻辑是nacos希望当集群member发生变化时，自动更新这个文件，以保证下次启动时能够获取完整的集群信息。

另一部分逻辑是nacos检测自身的ip是否在集群里，不在的话尝试将自己加到集群Member里。

两个逻辑合起来就会变成当nacos 自身ip不在cluster.conf时，会添加cluster.conf的记录。

**Comment by KomachiSion** [comment]
所以大家配置cluster.conf时，要根据所在服务器的ip或者hostname来配置，不能根据dns上的域名配置

**Comment by KomachiSion** [comment]
如果使用域名配置，需要在启动时，配置nacos.server.ip告知nacos程序自身ip/域名，这样nacos就不会去自动获取了。

**Comment by yuqiyang01** [comment]
我是通过IP配置的，然后多的那条记录是：hostname:Port，原来配置的IP:Port的记录还在， hostname和IP会同时检测吗？ 以哪一个为准

**Comment by KomachiSion** [comment]
如果开启了hostname模式就是以hostname为准，什么都不设置默认以ip为准

**Comment by aakejiang** [comment]
@chuntaojun @KomachiSion 1.4.0 是已经修复这个问题了，什么时候release？

**Comment by KomachiSion** [comment]
1.4.0应该能修复这个问题，我会更新下文档，到时候可以按照文档上的说明试一下。

关于release，请关注动态。release了第一时间会通知

**Comment by KomachiSion** [comment]
@aakejiang 1.4.0-BETA已经发布了，可以测试一下了。如果1.4.0-BETA仍然有问题，请再提交issue告知。

**Comment by njliukang** [comment]
貌似还是没修复这个问题，我启动的时候会自动添加一个8848的端口进来

**Comment by 172821243** [comment]
现在这个问题的解决方案是什么呢？2.0.2版本还是存在该问题，cluster.conf是否可以支持域名配置

**Comment by friendyw** [comment]
在application.properties中指定nacos启动IP即可

### Specify local server's IP:
nacos.inetutils.ip-address=192.168.10.100

**Comment by markguy** [comment]
received

**Comment by Yanglmunix** [comment]
k8s 部署的修改配置文件conf/application.properties
nacos.inetutils.prefer-hostname-over-ip=true
可以解决
