### ISSUE TITLE
nacos 有客户端缓存禁用功能么   生成的缓存会包含敏感信息

### ISSUE THREAD

**Issue by Reminisd** [alibaba/nacos#3862]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
nacos分服务发现和配置中心，服务发现这边确实会缓存注册的服务信息到本地做容灾，目前好像不能禁用。

**Comment by shiyiyue1102** [comment]
配置中心的客户端缓存实际上是一个容灾目录，是用于server端宕机完全不可用的场景下容灾策略，可以通过设置静态变量的形式        SnapShotSwitch.setIsSnapShot(false);进行关闭，是否需要容灾功能需要你自行评估下

**Comment by shiyiyue1102** [comment]
配置中心的缓存是一个容灾目录，在服务端不可用时，会读取客户端本地配置，如果禁用缓存，会时区容灾功能，这个点需要评估好；
可以通过设置静态变量关闭缓存SnapShotSwitch.setIsSnapShot(false);
