### ISSUE TITLE
请问一下nacos注册中心非临时性的实例持久化到本地的方式

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#3866]
如题

**Comment by horizonzy** [comment]
通过文件的方式保存在 {user.home}/nacos/data/naming/data/public

**Comment by shizhengxing** [comment]
永久数据不是默认会存储到文件吗？

**Comment by KomachiSion** [comment]
如 @horizonzy 所说。非临时实例会持久化到本地文件。

**Comment by HelloHaiNG** [comment]
> 如 @horizonzy 所说。非临时实例会持久化到本地文件。

好的，感谢

**Comment by HelloHaiNG** [comment]
> 通过文件的方式保存在 {user.home}/nacos/data/naming/data/public
好的，感谢

**Comment by HelloHaiNG** [comment]
> 如 @horizonzy 所说。非临时实例会持久化到本地文件。



> 通过文件的方式保存在 {user.home}/nacos/data/naming/data/public

这个地址好像在配置文件里面没看到，不能修改的吗

**Comment by horizonzy** [comment]
可以修改。可以通过增加启动参数nacos.home来指定你的nacos目录

**Comment by horizonzy** [comment]
config和naming都在nacos文件夹下面
