### ISSUE TITLE
引入springboot nacos后，启动springboot 时读取不到默认的application.properties

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#3867]
springboot应用中，引入nacos client
![image](https://user-images.githubusercontent.com/15244686/93588759-72a9ad80-f9de-11ea-8d96-3b33042f8e43.png)
![image](https://user-images.githubusercontent.com/15244686/93588405-f0b98480-f9dd-11ea-997b-16f7d6589b1f.png)
然后再启动的时候sprintboot启动异常
![image](https://user-images.githubusercontent.com/15244686/93588486-0cbd2600-f9de-11ea-8be8-fad2c1dc5e21.png)
上面报错的配置是springboot application.properties配置，看起来没被生效，有人遇到过这个问题吗

**Comment by horizonzy** [comment]
有两个bean的名字重了。具体是哪个bean看下日志，看下是否是引入的nacos的start中的bean与应用中原本的bean出现了重复

**Comment by FengJinghHua** [comment]
@horizonzy 我加入了spring.main.allow-bean-definition-overriding=true后，不报上一个错误了，但是报
![image](https://user-images.githubusercontent.com/15244686/93658046-9d414800-fa6a-11ea-8a42-93824e707b25.png)错误，这jasypt.encryptor.password个配置是在application中定义的，感觉启动时把默认的application.properties覆盖了，这个怎么解决的。

**Comment by FengJinghHua** [comment]
@horizonzy 我在issue中发现了类似的情况，https://github.com/alibaba/nacos/issues/2198，但是好像没有解决方法？

**Comment by horizonzy** [comment]
我看了那个issue.你把自己的配置文件定义成yml的格式呢

**Comment by FengJinghHua** [comment]
@horizonzy 改成yml格式对项目来说可能不允许，有别的办法或者workaround吗

**Comment by horizonzy** [comment]
下载nacos的源码。找到这个starter对应版本nacos-client版本，把client的application.properties文件剔除打包。腺癌client模块的application.properties中只有一个version，可以把那个version整合到自己的properties中。

**Comment by FengJinghHua** [comment]
@horizonzy 我往这方向试试，BTW，鉴于这样的conflict，官方有考虑过在打出的包中就去掉client 下面的 application.properties吗

**Comment by FengJinghHua** [comment]
在去掉nacos-api 和nacos-client下的application.properties后，it works like normal，但是感觉不是个正解。

**Comment by horizonzy** [comment]
> 在去掉nacos-api 和nacos-client下的application.properties后，it works like normal，但是感觉不是个正解。
周一社区负责人看到了应该会处理这个情况的。

**Comment by FengJinghHua** [comment]
@horizonzy 非常感谢你

**Comment by KomachiSion** [comment]
Refer to #3528
