### ISSUE TITLE
Dynamically update metadata failed

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#3868]
When I update metata via Nacos Open Api, it display bad request. Any mistake for my PUT request in Postman?

![图片](https://user-images.githubusercontent.com/42354711/93659184-455c0e80-fa75-11ea-947d-049256323d99.png)
![图片](https://user-images.githubusercontent.com/42354711/93659190-50af3a00-fa75-11ea-8f58-bb6d83bf367e.png)

Nacos 1.3.2

**Comment by HaojunRen** [comment]
add url : curl -X PUT 127.0.0.1:8848/nacos/v1/ns/instance?serviceName=discovery-guide-service-a&ip=172.27.208.1&port=3001&metadata={"version", "stable"}

**Comment by KomachiSion** [comment]
What's the error information of 400 response?

**Comment by HaojunRen** [comment]
nacos后台没有任何抛错，返回的400异常如截图所示，建议请帮忙测试一下。补充一下，如果把metadata参数去掉，则返回ok，功能也符合预期

**Comment by KomachiSion** [comment]
返回的http reponse里没有错误信息吗？ 截图下面的内容是什么？

**Comment by HaojunRen** [comment]
截图下面内容没有实际参考意义，都是一些HTML格式的代码。其实，你本地reproduce一下就可以了

**Comment by horizonzy** [comment]
> nacos后台没有任何抛错，返回的400异常如截图所示，建议请帮忙测试一下。补充一下，如果把metadata参数去掉，则返回ok，功能也符合预期

对metadata的值进行encode试试呢

**Comment by HaojunRen** [comment]
metadata本来都是英文。没必要花时间继续讨论这个问题，你们应该花10分钟，就可以重现这个问题。我是按照nacos openapi操作手册来的，但如果是我使用方式不正确，请帮忙指正，并表示歉意

**Comment by horizonzy** [comment]
![image](https://user-images.githubusercontent.com/22524871/93963108-dfca9380-fd8e-11ea-9ebe-10f672ac7b6b.png)

![image](https://user-images.githubusercontent.com/22524871/93963090-d2150e00-fd8e-11ea-8e0c-aa145e417155.png)

**Comment by KomachiSion** [comment]
PUT和POST操作，参数应该放body里吧。

**Comment by horizonzy** [comment]
他这个是表单提交



发自我的iPhone


------------------ Original ------------------

**Comment by KomachiSion** [comment]
@HaojunRen can use body solve this problem?

**Comment by KomachiSion** [comment]
No more response from author, I think problem has been solved.

**Comment by 2YSP** [comment]
> metadata本来都是英文。没必要花时间继续讨论这个问题，你们应该花10分钟，就可以重现这个问题。我是按照nacos openapi操作手册来的，但如果是我使用方式不正确，请帮忙指正，并表示歉意

我今天也遇到了这个问题了，你解决了吗？

**Comment by fiuty** [comment]
@2YSP 我今天也遇到这个问题，要对metadata进行encode，因为有符号所以要encode编码。可以找个在线encode把你的metadata转一下再发起请求，网址：https://www.bejson.com/enc/urlencode/
