### ISSUE TITLE
i found a mistack in file NamingProxy.java

### ISSUE THREAD

**Issue by shizhengxing** [alibaba/nacos#3871]
file path : nacos/naming/src/main/java/com/alibaba/nacos/naming/misc/NamingProxy.java 
method : public static byte[] getAllData(String server) throws Exception
line : 149

<img width="924" alt="nacos-bug-1" src="https://user-images.githubusercontent.com/27763870/93669951-0906cd80-faca-11ea-9bd4-2eb7f0fe6bd3.png">

**Comment by shizhengxing** [comment]
if this confirmed,I'd like to work out it!

**Comment by horizonzy** [comment]
yes, the description don't match the error

**Comment by KomachiSion** [comment]
@horizonzy @shizhengxing welcome to fix it

**Comment by shizhengxing** [comment]
@i will solve it@
