### ISSUE TITLE
订阅者列表中服务名unknown

### ISSUE THREAD

**Issue by DongyangHu** [alibaba/nacos#3873]
## 问题描述
使用nacos-client进行服务订阅，在后台管理中查看订阅者列表，发现订阅者服务名显示unknown，请问该项是如何配置的

## nacos-client版本
```
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>1.2.1</version>
</dependency>
```

**Comment by horizonzy** [comment]
这个订阅者名称显示的是客户端的appName。可以在客户端增加启动参数project.name来指定你的应用的appName

**Comment by KomachiSion** [comment]
我印象中目前版本好像订阅的时候都用的是默认值`unknown `,可能后续需要优化。

**Comment by DongyangHu** [comment]
好的，感谢

**Comment by catalpa-tree** [comment]
@DongyangHu 解决问题了吗？我也遇到了，配了project.name还是不显示，是我的姿势不对吗？我是在bootstrap配置里配的

**Comment by hwy1782** [comment]
需要在jvm的启动参数里配置

**Comment by javaql** [comment]
去改他源码，让他支持spring.application.name
