### ISSUE TITLE
How to get notified when new service is registered

### ISSUE THREAD

**Issue by zerda** [alibaba/nacos#3875]
**Is your feature request related to a problem? Please describe.**

Hello, I'm working on a nacos ServerListUpdater implementation for ribbon.

All existed service can be subscribed with NamingService, but not the new one. (which service name is unknown as updater started.)

```
public class NacosNotificationServerListUpdater implements ServerListUpdater {
  @Override
  public void start(UpdateAction updateAction) {
    String group = discoveryProperties.getGroup();
    List<String> services = namingService.getServicesOfServer(1, Integer.MAX_VALUE, group).getData();
    for (String service : services) {
      namingService.subscribe(service, group, updateListener);
    }
  }
}
```

**Describe the solution you'd like**

I'm wondering if there is anyway to be notified when new service is registered, and/or instance is updated.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by KomachiSion** [comment]
I don't think it's a reasonable feature. Why your consumer need to subscribe all service in one group or namespace? 

What's the dependency services you should know before the app start but not get them during running.

**Comment by zerda** [comment]
> I don't think it's a reasonable feature. Why your consumer need to subscribe all service in one group or namespace?
> 
> What's the dependency services you should know before the app start but not get them during running.

You're right, my mistake. UpdateListener should be per service, and only need to subscribe consumed service(s) not all services.
