### ISSUE TITLE
注册中心服务下线不起效

### ISSUE THREAD

**Issue by shadowhunterhh** [alibaba/nacos#3877]
nacos server version：1.3.1

maven dependency version：
nacos-client  1.0.0
spring-cloud-starter-alibaba-nacos-config   1.5.1.RELEASE
dubbo-registry-nacos  2.6.9

生产者服务接口可以正常注册到nacos注册中心并且消费者可以正常调用，但是点击注册中心详情中的服务下线，等待了几分钟再尝试服务依然可以正常调用

The producer service interface can be normally registered in the nacos registry and the consumer can call normally, but click the service offline in the registry details and wait for a few minutes before trying the service can still be called normally

**Comment by ZoraZora59** [comment]
服务本地缓存的服务列表没刷新吧

**Comment by shadowhunterhh** [comment]
> 服务本地缓存的服务列表没刷新吧

需要加配置刷新吗？我下线了A服务的接口，消费者B服务还是可以调用A的那个接口

**Comment by KomachiSion** [comment]
查一下 `${user.home}/logs/nacos/naming.log` 看一下有没有收到对应服务的变更，关键词`new ips/removed ips/modified ips`

**Comment by shadowhunterhh** [comment]
> 查一下 `${user.home}/logs/nacos/naming.log` 看一下有没有收到对应服务的变更，关键词`new ips/removed ips/modified ips`

我在部署nacos的服务器，和部署提供者服务、消费者服务的服务器上都没有找到这个日志

**Comment by shadowhunterhh** [comment]
> 查一下 `${user.home}/logs/nacos/naming.log` 看一下有没有收到对应服务的变更，关键词`new ips/removed ips/modified ips`

找到了，，但是里面是空的

**Comment by shadowhunterhh** [comment]
我刚刚试了点了下线，然后刷新一下页面，他自己就变成上线了。。。而且在外层点击删除也没用，刷新一下页面那个服务就出来了，而且可以正常调用服务

**Comment by shadowhunterhh** [comment]
> 查一下 `${user.home}/logs/nacos/naming.log` 看一下有没有收到对应服务的变更，关键词`new ips/removed ips/modified ips`

请问这个是版本问题吗？如何才能解决呢？

**Comment by KomachiSion** [comment]
你可能没有理解下线按钮的含义，这个下线按钮只是在推送和查询时把这个节点移除，并不是真的删除，这个节点的健康状态依旧保持，并且端口等都是通的。

如果你希望确认下线是否已经生效，看详情页面的按钮如果变成`上线`那就是正确下线了。

**Comment by shadowhunterhh** [comment]
我懂您的意思，我点击下线后那个按钮会变成上线，应该表示该节点已经移除了，但是此时消费者调用该节点依然可以正常访问，并且页面刷新后那个按钮显示会重新变成下线，但是我看了点击下线确实调用了nacos/v1/ns/instance接口并且调用成功返回ok。

B服务的B1接口调用A服务的A1接口,服务提供者A服务的A1接口点击下线后，B1接口调用不是应该失败吗？但是却能成功调用

**Comment by horizonzy** [comment]
> 我懂您的意思，我点击下线后那个按钮会变成上线，应该表示该节点已经移除了，但是此时消费者调用该节点依然可以正常访问，并且页面刷新后那个按钮显示会重新变成下线，但是我看了点击下线确实调用了nacos/v1/ns/instance接口并且调用成功返回ok。
> 
> B服务的B1接口调用A服务的A1接口,服务提供者A服务的A1接口点击下线后，B1接口调用不是应该失败吗？但是却能成功调用

确认两个点。
1.nacos控制台服务下线是否成功
2.服务下线成功之后，consumer端是否收到了服务下线的这个通知，对本地的invokers进行刷新

**Comment by KomachiSion** [comment]
> 我懂您的意思，我点击下线后那个按钮会变成上线，应该表示该节点已经移除了，但是此时消费者调用该节点依然可以正常访问，并且页面刷新后那个按钮显示会重新变成下线，但是我看了点击下线确实调用了nacos/v1/ns/instance接口并且调用成功返回ok。
> 
> B服务的B1接口调用A服务的A1接口,服务提供者A服务的A1接口点击下线后，B1接口调用不是应该失败吗？但是却能成功调用

不会调用失败，而是应该不调用。如果一直还在调用，那就需要查一下为什么变更后没有通知到consumer。

再次强调，这个下线只是一个tag，provider本身我们不会做任何操作

**Comment by johnsonyang** [comment]
为什么关闭，这个问题，在2.2.3依然存在啊！

**Comment by shadowhunterhh** [comment]
> 为什么关闭，这个问题，在2.2.3依然存在啊！

尚未解决，但是项目评估暂时不需要这个功能

**Comment by huxipi** [comment]
这个功能很有用啊，譬如蓝绿发布可以由运维人员来操作的

**Comment by wangzhenxyz1** [comment]
> 你可能没有理解下线按钮的含义，这个下线按钮只是在推送和查询时把这个节点移除，并不是真的删除，这个节点的健康状态依旧保持，并且端口等都是通的。
> 
> 如果你希望确认下线是否已经生效，看详情页面的按钮如果变成`上线`那就是正确下线了。

如果有上线按钮，应该就没问题了，而且消费者还能查询到这个服务，那这个下线的功能只是打个tag吗，那有点违反直觉。
