### ISSUE TITLE
Error in starting Nacos

### ISSUE THREAD

**Issue by zljnx** [alibaba/nacos#3878]
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/lib/ext -Xloggc://mnt/joolun/server/nacos-server/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=//mnt/joolun/server/nacos-server/plugins/health,//mnt/joolun/server/nacos-server/plugins/cmdb -Dnacos.home=//mnt/joolun/server/nacos-server -jar //mnt/joolun/server/nacos-server/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file://mnt/joolun/server/nacos-server/conf/ --logging.config=//mnt/joolun/server/nacos-server/conf/nacos-logback.xml --server.max-http-header-size=524288
12:47:38.508 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/classes!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-web-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-json-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-datatype-jdk8-2.9.7.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-datatype-jsr310-2.9.7.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-module-parameter-names-2.9.7.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/hibernate-validator-6.0.13.Final.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/validation-api-2.0.1.Final.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jboss-logging-3.3.2.Final.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/classmate-1.4.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-web-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-webmvc-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-api-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-core-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-common-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-consistency-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/hessian-4.0.63.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-test-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-test-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jraft-core-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/asm-6.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/rocksdbjni-5.18.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jna-4.5.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jctools-core-2.1.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/disruptor-3.3.7.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/hessian-3.3.6.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/metrics-core-4.0.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/rpc-grpc-impl-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/reflections-0.9.11.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/javassist-3.21.0-GA.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/guava-24.1.1-jre.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jsr305-1.3.9.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/checker-compat-qual-2.0.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/j2objc-annotations-1.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/animal-sniffer-annotations-1.14.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-jdbc-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/HikariCP-3.4.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-jdbc-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-tx-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/commons-io-2.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/commons-lang-2.6.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/mysql-connector-java-8.0.16.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/derby-10.14.2.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/aspectjrt-1.9.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/cglib-nodep-2.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/httpasyncclient-4.1.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/httpcore-nio-4.4.10.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/commons-logging-1.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-tomcat-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/javax.annotation-api-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-websocket-9.0.13.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-core-2.10.4.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-databind-2.10.4.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-annotations-2.9.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/commons-lang3-3.4.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/micrometer-registry-prometheus-1.1.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/micrometer-core-1.1.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/HdrHistogram-2.1.9.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/LatencyUtils-2.0.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/simpleclient_common-0.5.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/micrometer-registry-influx-1.1.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/micrometer-registry-elastic-1.1.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-aop-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/aspectjweaver-1.9.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-actuator-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-actuator-autoconfigure-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-actuator-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-jasper-7.0.59.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-core-9.0.13.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/tomcat-annotations-api-9.0.13.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-el-9.0.13.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/ecj-4.4.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/netty-all-4.1.42.Final.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/async-http-client-1.7.17.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/netty-3.6.6.Final.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-core-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-jcl-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-context-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/commons-collections-3.2.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jackson-core-asl-1.9.13.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/slf4j-api-1.7.7.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/logback-core-1.2.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/mina-core-2.0.0-RC1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/javatuples-1.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/httpcore-4.4.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/httpclient-4.5.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/commons-codec-1.11.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-cmdb-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-istio-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/nacos-client-1.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/simpleclient-0.5.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/snakeyaml-1.23.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-netty-shaded-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-core-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/gson-2.8.5.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/annotations-4.1.1.4.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/perfmark-api-0.17.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/opencensus-api-0.21.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/opencensus-contrib-grpc-metrics-0.21.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-protobuf-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-api-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-context-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/error_prone_annotations-2.3.2.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-protobuf-lite-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/grpc-stub-1.24.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/proto-google-common-protos-1.17.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/protobuf-java-3.8.0.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/netty-common-4.1.31.Final.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/log4j-over-slf4j-1.7.25.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jcl-over-slf4j-1.7.25.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jul-to-slf4j-1.7.25.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-security-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-logging-2.1.1.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/log4j-to-slf4j-2.11.1.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/log4j-api-2.13.3.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-aop-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-beans-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-security-config-5.1.2.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-security-core-5.1.2.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-security-web-5.1.2.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/spring-expression-5.1.3.RELEASE.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jjwt-api-0.10.5.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jjwt-impl-0.10.5.jar!/, jar:file:/mnt/joolun/server/nacos-server/target/nacos-server.jar!/BOOT-INF/lib/jjwt-jackson-0.10.5.jar!/]
12:47:38.513 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to load property source from location 'file://mnt/joolun/server/nacos-server/conf/application.properties'
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:554)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadForFileExtension(ConfigFileApplicationListener.java:500)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:467)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$null$6(ConfigFileApplicationListener.java:448)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$7(ConfigFileApplicationListener.java:447)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:444)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:332)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:207)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:190)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466)
Caused by: java.net.UnknownHostException: mnt
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:311)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:417)
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:173)
	at org.springframework.boot.env.OriginTrackedPropertiesLoader$CharacterReader.<init>(OriginTrackedPropertiesLoader.java:159)
	at org.springframework.boot.env.OriginTrackedPropertiesLoader.load(OriginTrackedPropertiesLoader.java:74)
	at org.springframework.boot.env.OriginTrackedPropertiesLoader.load(OriginTrackedPropertiesLoader.java:63)
	at org.springframework.boot.env.PropertiesPropertySourceLoader.loadProperties(PropertiesPropertySourceLoader.java:61)
	at org.springframework.boot.env.PropertiesPropertySourceLoader.load(PropertiesPropertySourceLoader.java:47)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadDocuments(ConfigFileApplicationListener.java:572)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:526)
	... 31 common frames omitted
12:47:38.517 [Thread-4] WARN com.alibaba.nacos.common.executor.ThreadPoolManager - [ThreadPoolManager] Start destroying ThreadPool
12:47:38.518 [Thread-4] WARN com.alibaba.nacos.common.executor.ThreadPoolManager - [ThreadPoolManager] Destruction of the end

**Comment by Maijh97** [comment]
Check whether the file permissions of'mnt/joolun/server/nacos-server/conf/application.properties' are owned by the launching user.

**Comment by KomachiSion** [comment]
`Caused by: java.net.UnknownHostException: mnt`
