### ISSUE TITLE
有手动同步config的途径吗

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#3884]
请问下，nacos 和 springboot集成后，有API或其它方法能手动执行同步nacos->springboot 的配置吗，现在有longrunning的线程同步，但是在界面上提供一个手动同步的功能看起来也很好，遗憾的是我在java的SDK中没有找到。

**Comment by sanxun0325** [comment]
并不需要手动方式，客户端通过长轮询机制已经监听了文件，文件改动就会及时通知到客户端。

**Comment by KomachiSion** [comment]
没理解为什么需要手动同步？ 你修改任何内容都会触发同步。完全没必要再加这么一个功能吧

**Comment by FengJinghHua** [comment]
@sanxun0325 @KomachiSion  比如出现一些因网络或者其它因素影响了同步，导致文件改动不能及时通知到客户端，这时能手动同步，比如调个同步接口

**Comment by KomachiSion** [comment]
> @sanxun0325 @KomachiSion � 比如出现一些因网络或者其它因素影响了同步，导致文件改动不能及时通知到客户端，这时能手动同步，比如调个同步接口

nacos会自动持续同步，也没有必要手动再同步。

**Comment by FengJinghHua** [comment]
@sanxun0325 @KomachiSion  如果要实现手动同步功能，目前有轮子吗

**Comment by sanxun0325** [comment]
> @sanxun0325 @KomachiSion 如果要实现手动同步功能，目前有轮子吗
如果因为网络等其他因素影响了自动持续同步，那么你手动同步也是一样会失败的。 目前没有这样的手动触发同步功能。

**Comment by FengJinghHua** [comment]
@sanxun0325 非常感谢你的回答

**Comment by KomachiSion** [comment]
> @sanxun0325 @KomachiSion 如果要实现手动同步功能，目前有轮子吗

编辑这个配置，加一个空行或者删掉一个空行之类的都可以
