### ISSUE TITLE
Failed to rename context [nacos] as

### ISSUE THREAD

**Issue by caojiantong** [alibaba/nacos#3889]
"C:\Program Files\Java\jdk1.8.0_111\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1\lib\idea_rt.jar=64061:C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_111\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_111\jre\lib\rt.jar;D:\projects\hejiaqing\lightapp\lightapp-h5admin\target\classes;D:\myRepository\org\springframework\boot\spring-boot-starter-web\2.0.3.RELEASE\spring-boot-starter-web-2.0.3.RELEASE.jar;D:\myRepository\org\springframework\boot\spring-boot-starter\2.0.3.RELEASE\spring-boot-starter-2.0.3.RELEASE.jar;D:\myRepository\org\springframework\boot\spring-boot\2.0.3.RELEASE\spring-boot-2.0.3.RELEASE.jar;D:\myRepository\org\springframework\boot\spring-boot-autoconfigure\2.0.3.RELEASE\spring-boot-autoconfigure-2.0.3.RELEASE.jar;D:\myRepository\org\springframework\boot\spring-boot-starter-logging\2.0.3.RELEASE\spring-boot-starter-logging-2.0.3.RELEASE.jar;D:\myRepository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;D:\myRepository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\myRepository\org\apache\logging\log4j\log4j-to-slf4j\2.10.0\log4j-to-slf4j-2.10.0.jar;D:\myRepository\org\apache\logging\log4j\log4j-api\2.10.0\log4j-api-2.10.0.jar;D:\myRepository\org\slf4j\jul-to-slf4j\1.7.25\jul-to-slf4j-1.7.25.jar;D:\myRepository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;D:\myRepository\org\yaml\snakeyaml\1.19\snakeyaml-1.19.jar;D:\myRepository\org\springframework\boot\spring-boot-starter-json\2.0.3.RELEASE\spring-boot-starter-json-2.0.3.RELEASE.jar;D:\myRepository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.9.6\jackson-datatype-jdk8-2.9.6.jar;D:\myRepository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.9.6\jackson-datatype-jsr310-2.9.6.jar;D:\myRepository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.9.6\jackson-module-parameter-names-2.9.6.jar;D:\myRepository\org\springframework\boot\spring-boot-starter-tomcat\2.0.3.RELEASE\spring-boot-starter-tomcat-2.0.3.RELEASE.jar;D:\myRepository\org\apache\tomcat\embed\tomcat-embed-core\8.5.31\tomcat-embed-core-8.5.31.jar;D:\myRepository\org\apache\tomcat\embed\tomcat-embed-el\8.5.31\tomcat-embed-el-8.5.31.jar;D:\myRepository\org\apache\tomcat\embed\tomcat-embed-websocket\8.5.31\tomcat-embed-websocket-8.5.31.jar;D:\myRepository\org\hibernate\validator\hibernate-validator\6.0.10.Final\hibernate-validator-6.0.10.Final.jar;D:\myRepository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;D:\myRepository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;D:\myRepository\com\fasterxml\classmate\1.3.4\classmate-1.3.4.jar;D:\myRepository\org\springframework\spring-web\5.0.7.RELEASE\spring-web-5.0.7.RELEASE.jar;D:\myRepository\org\springframework\spring-beans\5.0.7.RELEASE\spring-beans-5.0.7.RELEASE.jar;D:\myRepository\org\springframework\spring-webmvc\5.0.7.RELEASE\spring-webmvc-5.0.7.RELEASE.jar;D:\myRepository\org\springframework\spring-context\5.0.7.RELEASE\spring-context-5.0.7.RELEASE.jar;D:\myRepository\org\springframework\spring-expression\5.0.7.RELEASE\spring-expression-5.0.7.RELEASE.jar;D:\myRepository\com\alibaba\boot\nacos-config-spring-boot-starter\0.2.7\nacos-config-spring-boot-starter-0.2.7.jar;D:\myRepository\com\alibaba\nacos\nacos-spring-context\0.3.6\nacos-spring-context-0.3.6.jar;D:\myRepository\com\alibaba\nacos\nacos-client\1.2.0\nacos-client-1.2.0.jar;D:\myRepository\com\alibaba\nacos\nacos-common\1.2.0\nacos-common-1.2.0.jar;D:\myRepository\commons-io\commons-io\2.2\commons-io-2.2.jar;D:\myRepository\com\alibaba\nacos\nacos-api\1.2.0\nacos-api-1.2.0.jar;D:\myRepository\com\alibaba\fastjson\1.2.58\fastjson-1.2.58.jar;D:\myRepository\com\google\guava\guava\22.0\guava-22.0.jar;D:\myRepository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;D:\myRepository\com\google\errorprone\error_prone_annotations\2.0.18\error_prone_annotations-2.0.18.jar;D:\myRepository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;D:\myRepository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;D:\myRepository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;D:\myRepository\io\prometheus\simpleclient\0.5.0\simpleclient-0.5.0.jar;D:\myRepository\com\alibaba\spring\spring-context-support\1.0.5\spring-context-support-1.0.5.jar;D:\myRepository\com\alibaba\boot\nacos-config-spring-boot-autoconfigure\0.2.7\nacos-config-spring-boot-autoconfigure-0.2.7.jar;D:\myRepository\com\alibaba\boot\nacos-spring-boot-base\0.2.7\nacos-spring-boot-base-0.2.7.jar;D:\myRepository\org\apache\skywalking\apm-toolkit-logback-1.x\6.2.0\apm-toolkit-logback-1.x-6.2.0.jar;D:\myRepository\org\springframework\boot\spring-boot-starter-aop\2.0.3.RELEASE\spring-boot-starter-aop-2.0.3.RELEASE.jar;D:\myRepository\org\springframework\spring-aop\5.0.7.RELEASE\spring-aop-5.0.7.RELEASE.jar;D:\myRepository\org\aspectj\aspectjweaver\1.8.13\aspectjweaver-1.8.13.jar;D:\myRepository\mysql\mysql-connector-java\5.1.46\mysql-connector-java-5.1.46.jar;D:\myRepository\org\apache\zookeeper\zookeeper\3.4.8\zookeeper-3.4.8.jar;D:\myRepository\log4j\log4j\1.2.16\log4j-1.2.16.jar;D:\myRepository\jline\jline\0.9.94\jline-0.9.94.jar;D:\myRepository\io\netty\netty\3.7.0.Final\netty-3.7.0.Final.jar;D:\myRepository\com\101tec\zkclient\0.10\zkclient-0.10.jar;D:\myRepository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;D:\myRepository\com\fasterxml\jackson\core\jackson-databind\2.10.2\jackson-databind-2.10.2.jar;D:\myRepository\com\fasterxml\jackson\core\jackson-annotations\2.10.2\jackson-annotations-2.10.2.jar;D:\myRepository\com\fasterxml\jackson\core\jackson-core\2.10.2\jackson-core-2.10.2.jar;D:\myRepository\net\sf\json-lib\json-lib\2.2.3\json-lib-2.2.3-jdk15.jar;D:\myRepository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar;D:\myRepository\commons-collections\commons-collections\3.2\commons-collections-3.2.jar;D:\myRepository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;D:\myRepository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;D:\myRepository\net\sf\ezmorph\ezmorph\1.0.6\ezmorph-1.0.6.jar;D:\myRepository\org\codehaus\jackson\jackson-core-asl\1.9.13\jackson-core-asl-1.9.13.jar;D:\myRepository\org\codehaus\jackson\jackson-mapper-asl\1.9.13\jackson-mapper-asl-1.9.13.jar;D:\myRepository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;D:\myRepository\com\thoughtworks\xstream\xstream\1.4.9\xstream-1.4.9.jar;D:\myRepository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;D:\myRepository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;D:\myRepository\org\jacoco\org.jacoco.agent\0.8.5\org.jacoco.agent-0.8.5-runtime.jar;D:\myRepository\org\springframework\spring-core\5.0.7.RELEASE\spring-core-5.0.7.RELEASE.jar;D:\myRepository\org\springframework\spring-jcl\5.0.7.RELEASE\spring-jcl-5.0.7.RELEASE.jar" com.cmcc.lightapp.h5admin.H5AdminApplication
log4j:WARN No appenders could be found for logger (org.springframework.web.context.support.StandardServletEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[Nacos Config Boot] : The preload log configuration is enabled
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [nacos] as [test] java.lang.IllegalStateException: Context has been already given a name
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:166)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:82)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:264)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:237)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:200)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:173)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.cmcc.lightapp.h5admin.H5AdminApplication.main(H5AdminApplication.java:21)

Process finished with exit code 1

what can i do to solve this problem?

**Comment by JackSun-Developer** [comment]
Is this problem encountered while starting nacos or complete starting up?

**Comment by JackSun-Developer** [comment]
Can you provide more information? In which case did you encountered this problem?

**Comment by KomachiSion** [comment]
duplicate with #3251
