### ISSUE TITLE
Can nacos support specifying the configuration file (or dir) at startup?

### ISSUE THREAD

**Issue by fafangshuai** [alibaba/nacos#3892]
Can it support specifying the configuration file (or dir) at startup? Like redis `redis-server redis.conf`. This makes it easy to deploy in different ways, such as stand-alone pseudo-distribution. tks.

**Comment by KomachiSion** [comment]
Not supported currently

**Comment by KomachiSion** [comment]
It seems no request for this feature in community. Closed first, if someone wants this feature, can submit new issue and linked this issue.
