### ISSUE TITLE
after delete  the configuration，the configuration always exists！

### ISSUE THREAD

**Issue by quinls** [alibaba/nacos#3893]
**Describe the bug**
after delete  the configuration，the configuration always exists！
删除配置后，nacos依然读到此配置，新增、修改正常

![Snipaste_2020-09-22_20-05-46](https://user-images.githubusercontent.com/33722445/93879822-077a1700-fd0f-11ea-94c1-1fb2221713a4.png)

![image](https://user-images.githubusercontent.com/33722445/93886739-61330f00-fd18-11ea-9f09-ac40e798364c.png)

**Desktop (please complete the following information):**
 - OS: [macos]
 - Version [nacos-server 1.1.4, nacos-client 1.1.4]
 - SDK [spring-cloud-alibaba 0.2.2]

**Comment by KomachiSion** [comment]
1.1.3 is to old, please use new version and retry

**Comment by quinls** [comment]
![image](https://user-images.githubusercontent.com/33722445/93886652-4bbde500-fd18-11ea-9a4c-2d31847362e8.png)

**Comment by KomachiSion** [comment]
Any process? If still no response, we will think the new version has fixed this problem and close issue.

**Comment by KomachiSion** [comment]
No more response, the new version may have fixed this problem.
