### ISSUE TITLE
can i use local disk mount instead of NFS in k8s?

### ISSUE THREAD

**Issue by handong0123** [alibaba/nacos#3894]
我能否使用本地磁盘挂载/home/nacos/data等目录，会不会造成集群问题

**Comment by KomachiSion** [comment]
不同的pod最好不要挂载在同一个本地磁盘路径，否则可能影响性能

**Comment by handong0123** [comment]
> 不同的pod最好不要挂载在同一个本地磁盘路径，否则可能影响性能

每个pod都挂载到自己的宿主机 会有问题吗 是否必须使用nfs k8s部署文档中只提到了nfs

**Comment by KomachiSion** [comment]
文档提到nfs应该只是一种方式吧，挂载到哪里应该是都可以的，只要避免多个pod的nacos写同一个实际文件就没问题。

至于实际挂载到哪，其实是k8s管理的。
