### ISSUE TITLE
Fuzzy search doesn't work（模糊搜索功能无效）

### ISSUE THREAD

**Issue by 846163908** [alibaba/nacos#3897]
The fuzzy search function has no effect. Using the fuzzy search function in the "configuration list" has no effect.

Version v1.3.2

-----------------
模糊搜索功能没有效果，在“配置列表”使用模糊搜索功能，没有效果。
版本v1.3.2

**Comment by sanxun0325** [comment]
@846163908 ,可以看一下你是如何使用的。 利用*进行模糊搜索
![image](https://user-images.githubusercontent.com/28588342/93956608-287d4f00-fd85-11ea-82cd-55eba2ca967d.png)

**Comment by 846163908** [comment]
> @ 846163908，可以看一下你是如何使用的。
> ![图片](https://user-images.githubusercontent.com/28588342/93956608-287d4f00-fd85-11ea-82cd-55eba2ca967d.png)

加*符号是可以的。 Thank you !
