### ISSUE TITLE
nacos fail to initialize in some situation

### ISSUE THREAD

**Issue by EZLippi** [alibaba/nacos#3898]
**Is your feature request related to a problem? Please describe.**
a nacos cluster with two node, nacos need to syncData from remote server when started, if network is not stable, like connection timeout or read timeout, syncAllDataFromRemote will fail, then we need to restart nacos server manually,
should this code got wrapped with a loop ?
![image](https://user-images.githubusercontent.com/5326814/93973978-b833f500-fda7-11ea-89d0-0f2b609b3465.png)

**Describe the solution you'd like**
nacos server will sleep for some seconds and retry to sync again.

**Comment by KomachiSion** [comment]
no need, the task will run in a few time if initialize = false.

see `LoadDataTask.run`

**Comment by EZLippi** [comment]
> no need, the task will run in a few time if initialize = false.
> 
> see `LoadDataTask.run`

ok , i am using a eariler version
