### ISSUE TITLE
哪个版本对dubbo进行支持？

### ISSUE THREAD

**Issue by xiaohanfeidao** [alibaba/nacos#390]
根据文档描述 0.3.0版本就会对dubbo进行支持，但是现在还没有的demo。

**Comment by hxy1991** [comment]
0.6.0 版本就和 dubbo 集成了，这周会发布。

**Comment by IronCity** [comment]
希望能尽快用到，目前在考虑中间件选型，打算用nacos+dubbo

**Comment by zhoujw8792** [comment]
期待中，最近项目也在考察想借机把配置中心引进来。dubbo已在使用，有意想不再使用dubbo的zk注册中心（因为与大数据组件的zk容易一起出问题）

**Comment by jovenwang** [comment]
com.alibaba:dubbo:2.6.5最新版本包还没有对 Registry 注册中心扩展,实现支持nacos注册,nacos会提供支持 demo

**Comment by jovenwang** [comment]
> 0.6.0 版本就和 dubbo 集成了，这周会发布。

期待中
