### ISSUE TITLE
关闭nacos(standalone模式)启动微服务看服务能否正常启动

### ISSUE THREAD

**Issue by sstong123** [alibaba/nacos#3902]
经测试：
微服务不能正常启动，卡在启动阶段。再次启动nacos后，从nacos控制台中能看到该微服务实例，但实际该实例端口并不可用，这样会造成调用方调用失败。
修改建议：
1.再次启动nacos后，微服务应该能正常启动。
或
2.微服务如果不能正常启动时，该微服务要自动退出；
或
3..微服务如果不能正常启动时，不要注册到nacos中。

**Comment by sanxun0325** [comment]
你要表达的意思就是 服务启动失败的时候 不希望注册到nacos对吧。
你可以将@EnableDiscoveryClient autoRegister 设置为false.  自己做一些逻辑，例如程序启动后 自身完成自检，然后再利用nacos-client完成注册。

**Comment by KomachiSion** [comment]
这个需求超出了nacos的能力范围，应该是微服务框架做的。

**Comment by sstong123** [comment]
可以封装在下面这个starter 里面吗？

 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

**Comment by sstong123** [comment]
可以封装在这个starter里面吗？spring-cloud-starter-alibaba-nacos-discovery

**Comment by KomachiSion** [comment]
> 可以封装在这个starter里面吗？spring-cloud-starter-alibaba-nacos-discovery

那提个issue到spring-cloud-alibaba社区吧。
