### ISSUE TITLE
调用 publishConfig 会覆盖数据库 type 字段

### ISSUE THREAD

**Issue by suikenungleung** [alibaba/nacos#3907]
版本：Spring Boot 2.3.3，Nacos Client 1.3.0，Nacos Server 1.3.2

代码 NacosConfigService 类 publishConfigInner 第 252 行 result = agent.httpPost(url, headers, params, encode, POST_TIMEOUT);

params 参数如下：

![image](https://user-images.githubusercontent.com/16551373/94164883-29fd6300-febc-11ea-9311-f8ae973916ff.png)

缺少 type 参数，请求后会覆盖数据库原本的 type，导致 type 为 null。

Nacos 控制台：

![image](https://user-images.githubusercontent.com/16551373/94166763-4f8b6c00-febe-11ea-8dcf-1cc7f72316a4.png)

以下是官方接口参数：

![image](https://user-images.githubusercontent.com/16551373/94165255-9aa47f80-febc-11ea-8ab1-d7cd55ee9ae8.png)

直接调用接口，忽略 type 参数和上面的结果相同。

![image](https://user-images.githubusercontent.com/16551373/94187661-d8b09c00-feda-11ea-9e6c-23a486e13d68.png)

**Comment by horizonzy** [comment]
如果没有传，当成text处理。text所有情况能都覆盖，因为content就是一堆字符串。如果传了，那用户传的是什么，就是什么。

**Comment by horizonzy** [comment]
@chuntaojun

**Comment by horizonzy** [comment]
> 现在有几种情况可能会导致为空.
> 1.通过openApi发布配置不传type
> 2.在控制台发布配置也不传type
> 3.sdk客户端现在没有支持type赋值，发布也是为空
> 
> 针对以上这几种情况。如果没有传，当成text处理。text所有情况能都覆盖，因为content就是一堆字符串。如果传了，那用户传的是什么，就是什么。（需不需要对用户传的type做校验，这点待定）

@chuntaojun 春少看一下这个方案呢
