### ISSUE TITLE
com.alibaba.nacos.naming.core.ServiceManager#updateInstance maybe exist problem

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3908]
**Describe the bug**
`if (!service.allIPs().contains(instance)) { ... }`. the instanceList from service.allIPs() maybe will be delay, it delay on consistencyService notify to update. so use it to judge data is incorrect. if the notify queue's data add many immediately, it will effect more

**Expected behavior**
get data from consistencyService

**Comment by KomachiSion** [comment]
I don't think so. when you call updateInstance, you must have get instance out of ServiceManager or it just register operation.

And we are a final consistency system, if we need ensure consistency the whole step like CAP, it will cost much resources.

**Comment by horizonzy** [comment]
> I don't think so. when you call updateInstance, you must have get instance out of ServiceManager or it just register operation.
> 
> And we are a final consistency system, if we need ensure consistency the whole step like CAP, it will cost much resources.

yes, but if we just update data relay the old instance, we should use consistencyService's data
