### ISSUE TITLE
启动项目时会打印三遍nacos配置中心的配置（The nacos configuration center configuration is printed three times when the project is started）

### ISSUE THREAD

**Issue by shadowhunterhh** [alibaba/nacos#3910]
**Describe the bug**
昨天开始启动本地项目时，发现命令行会打印了三遍nacos配置中心的配置。项目启动时会打印1次，启动成功后仍然会打印2次。
nacos log没有异常日志
（When I started the project, I found that the command line printed the nacos configuration center configuration file three times.The project will be printed once when started, and again twice after successful startup.Nacos log has no exception log）

**Expected behavior**
之前控制台只会打印1次配置文件，我想知道为什么现在启动集成了nacos的项目会打印3次配置文件
（Before, the console would only print the configuration file once, so I want to know why starting a project with integrated nacos now prints the configuration file three times）

**Acutally behavior**
只打印1次配置文件/不打印，或者打印3次的原因
（Reasons to print the configuration file only once, or three times）

**Additional context**
Three server cluster mode
nacos server 1.3.1
spring-cloud-starter-alibaba-nacos-config 1.5.1.RELEASE
nacos-client 1.0.0

**Comment by sanxun0325** [comment]
打印的信息或者截图可以发一下，我尝试用相同的版本，没有复现出来

**Comment by shadowhunterhh** [comment]
> 打印的信息或者截图可以发一下，我尝试用相同的版本，没有复现出来

截图如下，请帮忙分析一下,感谢！

![0SZZBOZW7L5EBX_{2G5@U5C](https://user-images.githubusercontent.com/62007136/94252129-14d51280-ff56-11ea-9ba9-bc8a469af034.png)

![3A3W@W{7$W60T6VQTE_J5_9](https://user-images.githubusercontent.com/62007136/94252140-18689980-ff56-11ea-9a08-03dc6f5c3ea7.png)

![VO2{YBMUF21})7R_}AMNV8K](https://user-images.githubusercontent.com/62007136/94252204-2f0ef080-ff56-11ea-8ad8-c93bf61c993a.png)

**Comment by sanxun0325** [comment]
@shadowhunterhh 第二次和第三次都是配置监听长轮询longPollingfixed触发的，说明配置有过修改。你可以在这个方向上查一下自己的代码在启动时 对文件是否做过更改。

**Comment by shadowhunterhh** [comment]
> @shadowhunterhh 第二次和第三次都是配置监听长轮询longPollingfixed触发的 说明配置有过修改。你可以在这个方向上查一下自己的代码在启动时,对文件是否做过更改。

具体是指什么文件的更改呢？我是本地启动应该没有更改任何文件

**Comment by sanxun0325** [comment]
@shadowhunterhh 看日志是comm-config，可以尝试升级一下spring-cloud-starter-alibaba-nacos-config。看代码逻辑 第二次和第三次打印的日志应该都是配置文件有修改触发的。

**Comment by shadowhunterhh** [comment]
> @shadowhunterhh 
spring-cloud-starter-alibaba-nacos-config升不了，我们用的springboot就是1.5版本的，要升级就改动太大了。
你意思是nacos配置中心里配置的common-config.properties配置有修改吗？那个是我引用的公共配置，这个项目自己的配置也打印了三次。而我启动时并没有更改这两个文件
