### ISSUE TITLE
exteral datasouce type is mysql，that is poor

### ISSUE THREAD

**Issue by xuyicheng1995** [alibaba/nacos#3914]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by horizonzy** [comment]
#3838

**Comment by KomachiSion** [comment]
What's your request? please clean describe your feature request or problem in issue description.

**Comment by xuyicheng1995** [comment]
> What's your request? please clean describe your feature request or problem in issue description.

in fact, there is a requirement in my project，i want to use nacos as a config center，when i read nacoss document，i found that it only support mysql in distribute mode，however， wo are not allowed to use mysql except postgres

**Comment by xuyicheng1995** [comment]
> #3
