### ISSUE TITLE
Provide common namespace configuration

### ISSUE THREAD

**Issue by lingting-gzm** [alibaba/nacos#3916]
配置命名空间时，能否提供一个公共的配置，而不是几个单独配置

When configuring the namespace, can you provide a common configuration instead of several separate configurations

**Comment by KomachiSion** [comment]
Please Move to #3756

**Comment by lingting-gzm** [comment]
我的描述有问题，我举个例子吧，我现在有个 bootstrap.yml 文件配置如下:
There is a problem with my description. Let me give you an example. I now have a bootstrap.yml file configured as follows:
`
spring:
  application:
    name: admin
  cloud:
    nacos:
      discovery:
        namespace: ng
      config:
        file-extension: yml
        namespace: ${spring.cloud.nacos.discovery.namespace}
        shared-configs:
          - application.${spring.cloud.nacos.config.file-extension}
      server-addr: nacos-server:8848
`

其中  discovery 和 config 中的namespace都是 ng, 这个配置能否简化成
The namespace in discovery and config are both ng, can this configuration be simplified to
`
spring:
  application:
    name: admin
  cloud:
    nacos:
      namespace: ng
      config:
        file-extension: yml
        shared-configs:
          - application.${spring.cloud.nacos.config.file-extension}
      server-addr: nacos-server:8848
`
直接进行单独的 namespace 配置就可以了， 如果有需要，再进行单独的配置
It’s fine to do a separate namespace configuration directly, if necessary, do a separate configuration
