### ISSUE TITLE
[Feature] in naming console, add filter function by metadata

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3917]
**Is your feature request related to a problem? Please describe.**

in naming console, we want to filter instance by metadata, such as bule/green, it will help us find the instance quickly. and in the future, we can batch operate instance such as enable/disable. this necessary is very useful.

**Comment by horizonzy** [comment]
the back-end logic complete. and the front-end need @jzhishu help.

**Comment by KomachiSion** [comment]
It's a big features. For nacos, the metadata is an inner attributes for instance and service, we do not build the index for these. 
If we need filter in console, we need looking for all services and instances.

If we have to add this feature, it might add some limitation to use, such as only filter one services.

**Comment by horizonzy** [comment]
> It's a big features. For nacos, the metadata is an inner attributes for instance and service, we do not build the index for these.
> If we need filter in console, we need looking for all services and instances.
> 
> If we have to add this feature, it might add some limitation to use, such as only filter one services.

yes. It just filter instances in services, and operration base on instances.
