### ISSUE TITLE
[Enhencement] merge config notify retry task 

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3918]
**Describe the bug**

now, if config changed, the handle server will notify other servers, but if some server is down, it will create retry notify task try again and again, untill it's successed. but if same config change two times, and some server is down, there will be two retry task try again and again. in fact, it can be merged.

**Comment by KomachiSion** [comment]
I remember config sync task also use MergeTaskEngine. We need to make sure whether config has merge task already.
If not, we also need to discuss whether it can be merged.

**Comment by horizonzy** [comment]
see com.alibaba.nacos.config.server.service.notify.AsyncNotifyService.AsyncTask#executeAsyncInvoke.

**Comment by KomachiSion** [comment]
Please give us some advise and discuss for this enhance.

**Comment by KomachiSion** [comment]
No discuss for long time, close first.
