### ISSUE TITLE
com.alibaba.nacos.naming.core.ServiceManager#updateIpAddresses juege unique instance incorrectly

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3919]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
now, we use ip+port+ephemeral to locate a instance. (see Instance.equals()). and when we register instance. but in com.alibaba.nacos.naming.core.ServiceManager#updateIpAddresses, it locate a instance by instance.datumKey(ip+port+cluster). so if we use sdk to register same(ip+port+ephemeral), different cluster, there will exist two instance.  

### Describe what you expected to happen
in com.alibaba.nacos.naming.core.ServiceManager#updateIpAddresses.locate i instance by (ip+port), if cluster not same, new cluster instance cover old cluster instance, instead of exist two instance.

phenomenon:
![image](https://user-images.githubusercontent.com/22524871/94332638-5d013d00-0009-11eb-9c8f-8d9a87990060.png)

**Comment by KomachiSion** [comment]
one instance but register to two cluster? which situation? We do not meet any request or situation which need register one service instance to same center with different clusters

**Comment by horizonzy** [comment]
I think this situation is illegal. but for code,  it should avoid it.

**Comment by KomachiSion** [comment]
cluster is upper level then instance, so I think there is no need to judge cluster. Just like no need to judge serviceName
