### ISSUE TITLE
Does Nacos support MariaDB for data persistence?

### ISSUE THREAD

**Issue by winer632** [alibaba/nacos#3921]
Does Nacos support MariaDB for data persistence?

**Comment by Ruffianjiang** [comment]
Not support. It only support file or mysql. But the task is in the scheduling.
https://nacos.io/en-us/docs/feature-list.html

**Comment by KomachiSion** [comment]
Now can support MySQL and Derby.

Multiple datasource support is developing by community.

**Comment by KomachiSion** [comment]
BTW, MariaDB is similar to MySQL, It should be directly replace.
