### ISSUE TITLE
method createServiceIfAbsent in  ServiceManager require sync

### ISSUE THREAD

**Issue by robinZhao** [alibaba/nacos#3922]
method createServiceIfAbsent in ServiceManager have  possibility of concurrent creation
require a sync here

public void createServiceIfAbsent(String namespaceId, String serviceName, boolean local, Cluster cluster)
            throws NacosException {
        Service service = getService(namespaceId, serviceName);
        if (service == null) {
            synchronized (this){
                service = getService(namespaceId, serviceName);
                if(null!=service){
                    return;
                }
                Loggers.SRV_LOG.info("creating empty service {}:{}", namespaceId, serviceName);
                service = new Service();
                service.setName(serviceName);
                service.setNamespaceId(namespaceId);
                service.setGroupName(NamingUtils.getGroupName(serviceName));
                // now validate the service. if failed, exception will be thrown
                service.setLastModifiedMillis(System.currentTimeMillis());
                service.recalculateChecksum();
                if (cluster != null) {
                    cluster.setService(service);
                    service.getClusterMap().put(cluster.getName(), cluster);
                }
                service.validate();
                putServiceAndInit(service);
                if (!local) {
                    addOrReplaceService(service);
                }
            }
        }
    }

**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Current logic, if there are many thread create Service, they will enter the `putServiceAndInit` method and then `putService` method
In `putService` method, it contain an `putServiceLock` and make sure the service map only contain one service.
So I think there is no need to lock in outer method

**Comment by KomachiSion** [comment]
I read the source code again, and found that there are some problem indeed. We will enhance this problem.

**Comment by a7217107** [comment]
i will solve it
