### ISSUE TITLE
monitoring interface for readinessProbe

### ISSUE THREAD

**Issue by HiroC222** [alibaba/nacos#3923]
Hi

nacos  version: 1.1.0
kubernetes: 1.15.3

  I hope to provide a monitoring interface for _readinessProbe_
Do not simply detect up,

The problem I have encountered is that the node is up, but access to the interface is actually abnormal
“/nacos/v1/ns/catalog/services?withInstances=false&pageNo=1&pageSize=10”

Thanks

**Comment by HiroC222** [comment]
The reason is that I found that after restarting the nacos node, the service can be started, Webpage can be login but the interface access is abnormal.

traefik access log shows response 503

**Comment by KomachiSion** [comment]
Sorry, I did not get your problem. Do you means that your nacos has started successfully, and the openAPI can be called.

But the console can't access?

**Comment by HiroC222** [comment]
Thank you for your reply

My nacos cluster has 3 nodes

Sometimes one nacos node restarte successfully, call "/nacos/actuator/health/" return {"status":"UP"}

but the openAPI can‘t be called :
"/nacos/v1/ns/catalog/services?withInstances=false&pageNo=1&pageSize=10" response 503

So I need a way to check whether node is really started successfully

**Comment by KomachiSion** [comment]
If "/nacos/actuator/health/" return "status":"UP", means the nacos has start successfully.

the interface `/nacos/v1/ns/catalog/services` return 503 means there are error in nacos server.

Can you find the error information from nacos log? And provide it to comment?

**Comment by HiroC222** [comment]
This is the problem

![image](https://user-images.githubusercontent.com/4082983/95701775-12282c00-0c7d-11eb-99ee-107ab8148f09.png)
![image](https://user-images.githubusercontent.com/4082983/95701781-15231c80-0c7d-11eb-8958-11e242f50b67.png)
![image](https://user-images.githubusercontent.com/4082983/95701787-181e0d00-0c7d-11eb-85b2-8dc87aeefd78.png)

naming-server.log：
![image](https://user-images.githubusercontent.com/4082983/95701793-19e7d080-0c7d-11eb-81fe-dd00a1962bb3.png)

Which log information do I need to provide

**Comment by HiroC222** [comment]
Search globally in the logs/ directory without any "error"

**Comment by KomachiSion** [comment]
No error or ERROR or exception in nacos.log?

**Comment by HiroC222** [comment]
Yes, this is all the logs of our nacos.log. No error

> 2020-10-13 11:02:32,604 INFO The server IP list of Nacos is [nacos-0.nacos-headless.middleware.svc.cluster.local:8848, nacos-1.nacos-headless.middleware.svc.cluster.local:8848, nacos-2.nacos-headless.middleware.svc.cluster.local:8848]
> 
> 2020-10-13 11:02:32,618 INFO Starting Nacos v1.1.0 on nacos-0.nacos-headless.middleware.svc.cluster.local with PID 30 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)
> 
> 2020-10-13 11:02:32,620 INFO No active profile set, falling back to default profiles: default
> 
> 2020-10-13 11:02:33,645 INFO Nacos is starting...
> 
> 2020-10-13 11:02:34,655 INFO Nacos is starting...
> 
> 2020-10-13 11:02:35,020 INFO Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$2e2ecc17] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
> 2020-10-13 11:02:35,136 INFO Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
> 2020-10-13 11:02:35,139 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@54422e18' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
> 2020-10-13 11:02:35,142 INFO Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$53036ec9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
> 2020-10-13 11:02:35,146 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 
> 2020-10-13 11:02:35,575 INFO Tomcat initialized with port(s): 8848 (http)
> 
> 2020-10-13 11:02:35,595 INFO Initializing ProtocolHandler ["http-nio-8848"]
> 
> 2020-10-13 11:02:35,609 INFO Starting service [Tomcat]
> 
> 2020-10-13 11:02:35,609 INFO Starting Servlet Engine: Apache Tomcat/9.0.13
> 
> 2020-10-13 11:02:35,623 INFO The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
> 
> 2020-10-13 11:02:35,656 INFO Nacos is starting...
> 
> 2020-10-13 11:02:35,721 INFO Initializing Spring embedded WebApplicationContext
> 
> 2020-10-13 11:02:35,722 INFO Root WebApplicationContext: initialization completed in 3012 ms
> 
> 2020-10-13 11:02:36,509 INFO Use Mysql as the driver
> 
> 2020-10-13 11:02:36,657 INFO Nacos is starting...
> 
> 2020-10-13 11:02:37,658 INFO Nacos is starting...
> 
> 2020-10-13 11:02:38,301 INFO Initializing ExecutorService 'applicationTaskExecutor'
> 
> 2020-10-13 11:02:38,562 INFO Adding welcome page: class path resource [static/index.html]
> 
> 2020-10-13 11:02:38,659 INFO Nacos is starting...
> 
> 2020-10-13 11:02:39,039 INFO Creating filter chain: Ant [pattern='/'], []
> 
> 2020-10-13 11:02:39,039 INFO Creating filter chain: Ant [pattern='/**/*.css'], []
> 
> 2020-10-13 11:02:39,039 INFO Creating filter chain: Ant [pattern='/**/*.js'], []
> 
> 2020-10-13 11:02:39,039 INFO Creating filter chain: Ant [pattern='/**/*.html'], []
> 
> 2020-10-13 11:02:39,039 INFO Creating filter chain: Ant [pattern='/**/*.map'], []
> 
> 2020-10-13 11:02:39,039 INFO Creating filter chain: Ant [pattern='/**/*.svg'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/**/*.png'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/**/*.ico'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/console-fe/public/**'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/v1/auth/login'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/v1/console/health/**'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/v1/cs/**'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/v1/ns/**'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/v1/cmdb/**'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/actuator/**'], []
> 
> 2020-10-13 11:02:39,040 INFO Creating filter chain: Ant [pattern='/v1/console/server/**'], []
> 
> 2020-10-13 11:02:39,082 INFO Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@54e22bdd, org.springframework.security.web.context.SecurityContextPersistenceFilter@3d9f6567, org.springframework.security.web.header.HeaderWriterFilter@2101b44a, org.springframework.security.web.authentication.logout.LogoutFilter@7e276594, com.alibaba.nacos.console.filter.JwtAuthenticationTokenFilter@3bd418e4, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@25e2ab5a, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@55562aa9, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@544820b7, org.springframework.security.web.session.SessionManagementFilter@710b18a6, org.springframework.security.web.access.ExceptionTranslationFilter@333dd51e, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@4c5474f5]
> 
> 2020-10-13 11:02:39,128 INFO Exposing 16 endpoint(s) beneath base path '/actuator'
> 
> 2020-10-13 11:02:39,168 INFO Initializing ExecutorService 'taskScheduler'
> 
> 2020-10-13 11:02:39,230 INFO Starting ProtocolHandler ["http-nio-8848"]
> 
> 2020-10-13 11:02:39,232 INFO Using a shared selector for servlet write/read
> 
> 2020-10-13 11:02:39,278 INFO Tomcat started on port(s): 8848 (http) with context path '/nacos'
> 
> 2020-10-13 11:02:39,284 INFO Started Nacos in 7.838 seconds (JVM running for 8.505)
> 
> 2020-10-13 11:02:39,285 INFO Nacos Log files: /home/nacos/logs/
> 
> 2020-10-13 11:02:39,285 INFO Nacos Conf files: /home/nacos/conf/
> 
> 2020-10-13 11:02:39,285 INFO Nacos Data files: /home/nacos/data/
> 
> 2020-10-13 11:02:39,285 INFO Nacos started successfully in cluster mode.
> 
> 2020-10-13 11:02:42,686 INFO Initializing Spring DispatcherServlet 'dispatcherServlet'
> 
> 2020-10-13 11:02:42,686 INFO Initializing Servlet 'dispatcherServlet'
> 
> 2020-10-13 11:02:42,699 INFO Completed initialization in 13 ms
>

**Comment by HiroC222** [comment]
I found that when 3 nodes restart at the same time, there will be a problem with 1 node

**Comment by KomachiSion** [comment]
Can you get the error information of `/nacos/v1/ns/catalog/services` 503?

If log without exception, and server can access, the error information maybe return through response.

**Comment by HiroC222** [comment]
curl 127.0.0.1:8848/nacos/v1/ns/catalog/services return this:

"server is DOWN now, please try again later!"

**Comment by HiroC222** [comment]
![image](https://user-images.githubusercontent.com/4082983/95821901-74f0f480-0d5d-11eb-8b47-b0d6e450d9cd.png)

**Comment by KomachiSion** [comment]
Please check the configuration of nacos-server `application.properties : nacos.naming.data.warmup`.

If it is true, the naming will support server after data load completed after restart. load data is an async process, so the nacos server actuator return ok.

 About this case, we need to discuss whether enhance actuator health status same as naming module and config module.

**Comment by HiroC222** [comment]
After setting to `false`, the problem is solved !!

Thank you for your patience!!
