### ISSUE TITLE
Support operation of selector on console

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#393]
We are about to enable user define their customized load-balance strategy, which is called 'selector'. So console edition of selector should be ready and the proposed web ui of this page is shown below.

![image](https://user-images.githubusercontent.com/4593375/49571278-cc5cf700-f973-11e8-899e-acd70dc7dad9.png)

**Comment by pguo65535** [comment]
how to bind a selector to service?

**Comment by pguo65535** [comment]
And how can we easily label services or instances or config in the future?

**Comment by nkorange** [comment]
> And how can we easily label services or instances or config in the future?

Ability to add and remove label to entity will be supported in future version.
