### ISSUE TITLE
nacos 1.3.2 Windows can not run

### ISSUE THREAD

**Issue by dongsongliu** [alibaba/nacos#3931]
**Describe the bug**
 i get the nacos 1.3.2 from https://github.com/alibaba/nacos/releases/tag/1.3.2 ;i run it user windows10  user cmd :./startup.cmd ,but i run with error, i find it defaut run use cluster mode, error like this
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
	at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:58)
;

**Expected behavior**
https://nacos.io/zh-cn/docs/deployment.html it says  nacos default use standalone mode

**Acutally behavior**
 nacos default use cluster  mode

**How to Reproduce**
https://nacos.io/zh-cn/docs/deployment.html windows start cmd modify :  
 startup.cmd -m standalone
not use 
 startup.cmd

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
i think nacos should use de

**Comment by Maijh97** [comment]
Please check if the database connection is correct.

**Comment by dongsongliu** [comment]
> Please check if the database connection is correct.

i just quick-startuse it , not use db ;  https://nacos.io/zh-cn/docs/quick-start.html quick-start docs  need update on frist use nacos ;

**Comment by KomachiSion** [comment]
startup.sh -m standalone

**Comment by dongsongliu** [comment]
i know how to run it ;but u quick-start docs is wrong;   https://nacos.io/zh-cn/docs/quick-start.html
