### ISSUE TITLE
如何自定义健康检查

### ISSUE THREAD

**Issue by MeloFocus** [alibaba/nacos#3933]
在官方文档中始终没有找到 设置健康检查的 讲解。
在控制台设置了，也似乎无法生效
![image](https://user-images.githubusercontent.com/36253326/94522649-8cf74d00-0262-11eb-95fd-0fc3a208b8f2.png)

**Comment by jsxiao** [comment]
你想怎么检查？

```
spring.cloud.nacos.discovery.heart-beat-interval=5000
spring.cloud.nacos.discovery.heart-beat-timeout=10000
```

**Comment by MeloFocus** [comment]
> 你想怎么检查？
> 
> ```
> spring.cloud.nacos.discovery.heart-beat-interval=5000
> spring.cloud.nacos.discovery.heart-beat-timeout=10000
> ```

这个配置是 客户端心跳的配置吗？

我想找，以下图片内容的使用说明
![image](https://user-images.githubusercontent.com/36253326/94523978-92559700-0264-11eb-939e-a356c6327722.png)

**Comment by MeloFocus** [comment]
(PING 或 TCP)和应用层 (如 HTTP、MySQL、用户自定义）的健康检查
![image](https://user-images.githubusercontent.com/36253326/94524038-a5686700-0264-11eb-9ce1-5b76a49e32f7.png)

**Comment by jsxiao** [comment]
> > 你想怎么检查？
> > ```
> > spring.cloud.nacos.discovery.heart-beat-interval=5000
> > spring.cloud.nacos.discovery.heart-beat-timeout=10000
> > ```
> 
> 这个配置是 客户端心跳的配置吗？
> 
> 我想找，以下图片内容的使用说明：(PING 或 TCP)和应用层 (如 HTTP、MySQL、用户自定义）的健康检查
> ![image](https://user-images.githubusercontent.com/36253326/94523978-92559700-0264-11eb-939e-a356c6327722.png)

这个就不清楚了，但我在源代码中看到过`TCP`和`HTTP`的检查类型，就是通过你第一张截图中的`检查类型`来控制的

**Comment by jsxiao** [comment]
你可以看一下server端的源代码, 能了解到许多

**Comment by sanxun0325** [comment]
当是持久化的实例时，服务端健康检查机制才会生效。ephemeral=false

**Comment by KomachiSion** [comment]
目前只有持久化的实例才可以选定健康检查方式，非持久化的实例只会使用心跳进行健康检查

**Comment by Xezeloh** [comment]
> 目前只有持久化的实例才可以选定健康检查方式，非持久化的实例只会使用心跳进行健康检查

请问持久化实例怎么配置健康检查方式

**Comment by KomachiSion** [comment]
就是在你发的描述的那个截图里设置。 可以选TCP HTTP方式。 如果是TCP方式应该输入端口就可以。
HTTP还需要输入uri

**Comment by Xezeloh** [comment]
> 就是在你发的描述的那个截图里设置。 可以选TCP HTTP方式。 如果是TCP方式应该输入端口就可以。
> HTTP还需要输入uri

那持久化实例可以用心跳的方式去做健康检查吗

**Comment by horizonzy** [comment]
> 那持久化实例可以用心跳的方式去做健康检查吗

不行。
