### ISSUE TITLE
nacos 1.3.2 集群环境下重启某一台server之后service自动上线问题 

### ISSUE THREAD

**Issue by jsxiao** [alibaba/nacos#3934]
docker部署`nacos1.3.2`版本, 集群环境。3台服务器。

控制台中下线了某个`service`,  然后在3台server上通过以下步骤检查状态

```
# 1. request 
curl http://localhost:8848/nacos/v1/ns/instance/list?serviceName=xxx-service

# 2. return

{"hosts":[],"dom":"xxx-service","name":"DEFAULT_GROUP@@xxx-service","cacheMillis":3000,"lastRefTime":1601362201710,"checksum":"1823f195f89a6c8f64daa59e4a0857ce","useSpecifiedURL":false,"clusters":"","env":"","metadata":{}}
```

最后重启其中一台nacos server. 启动后被下线的`service`自动上线了!!!

```
{"hosts":[{"ip":"192.168.1.250","port":8080,"valid":true,"healthy":true,"marked":false,"instanceId":"192.168.1.250#8080#DEFAULT#DEFAULT_GROUP@@xxx-service","metadata":{"preserved.heart.beat.timeout":"1000","preserved.ip.delete.timeout":"20000","preserved.register.source":"SPRING_CLOUD","preserved.heart.beat.interval":"1000"},"enabled":true,"weight":1.0,"clusterName":"DEFAULT","serviceName":"xxx-service","ephemeral":true}],"dom":"xxx-service","name":"DEFAULT_GROUP@@xxx-service","cacheMillis":3000,"lastRefTime":1601362282514,"checksum":"1823f195f89a6c8f64daa59e4a0857ce","useSpecifiedURL":false,"clusters":"","env":"","metadata":{}}
```

# **Please tell me why?**

**Comment by jsxiao** [comment]
将 `/home/nacos/data` 映射到宿主主机也不行

```
volumes:
      - ./data:/home/nacos/data
```

**Comment by chuntaojun** [comment]
每一台nacos-server都执行了request，然后实例都是查不到，然后重启一台就发现这个实例上线了？

**Comment by KomachiSion** [comment]
我可能知道问题所在了：

同一个service的请求会转发同一个node上处理（包括心跳），所以会导致其他两台的实例心跳时间可能比较旧，此时如果重启一台服务，该service的处理node可能发生变化，然后有刚好是健康检查周期，就把这个旧心跳的实例删除了，同时又接收到了实例心跳，所以又自动重新注册上了。这个时候之前的下线状态就失效了。

**Comment by jsxiao** [comment]
> 我可能知道问题所在了：
> 
> 同一个service的请求会转发同一个node上处理（包括心跳），所以会导致其他两台的实例心跳时间可能比较旧，此时如果重启一台服务，该service的处理node可能发生变化，然后有刚好是健康检查周期，就把这个旧心跳的实例删除了，同时又接收到了实例心跳，所以又自动重新注册上了。这个时候之前的下线状态就失效了。

说的有有点靠谱，之前也这么怀疑过。 那是不是如果某一台node在重启的时候，所有的service暂停发送心跳。等node启动之后再发送心跳。那么就不会出现此类问题了？

**Comment by jsxiao** [comment]
> 每一台nacos-server都执行了request，然后实例都是查不到，然后重启一台就发现这个实例上线了？

我的意思是，在nacos-server控制台上，点击offline（下线）。然后重启其中一台server，重启完成后发现之前offline的service变为online状态

**Comment by KomachiSion** [comment]
之前应该是考虑到同步心跳时间过于频繁，导致同步占用太多资源，所以心跳不会触发同步事件也不在数据对账范围之内，之后可能需要优化一下对账逻辑，要更新一下心跳时间，否则重启的瞬间如果卡在了健康检查期间，很可能出现把实例当作过期实例（长时间无心跳）删除掉，然后再由心跳重新注册上的问题。

**Comment by KomachiSion** [comment]
@jsxiao 您可以试下以下步骤，看能不能复现：
1. 随便注册一个服务实例，在控制台上能看到即可
2. 在控制台上点击下线
3. 等待约5～10分钟
4. 重启一台服务器
5. 再查看这个服务实例是不是上线状态

多试几次

**Comment by takeseem** [comment]
> @jsxiao 您可以试下以下步骤，看能不能复现：
> 
> 1. 随便注册一个服务实例，在控制台上能看到即可
> 2. 在控制台上点击下线
> 3. 等待约5～10分钟
> 4. 重启一台服务器
> 5. 再查看这个服务实例是不是上线状态
> 
> 多试几次

有点玩死人啊 ：（
时间成本太高

**Comment by deific** [comment]
这种场景，应该不管重启不重启，被下线的服务都应该是下线状态吧

**Comment by KomachiSion** [comment]
又进行了一段时间的排查，确认是机制问题导致的，重启的时候有两种情况会删除已注册的实例： 1. 心跳过旧，服务端认为实例已下线，删除。 2. 部分框架有自动功能，程序退出时会先去注销。
无论是哪种，关于该实例的信息会被全部删除（包括上下线信息）。因此重启之后肯定会处于上线状态，（除非程序注册的时候将上线状态置为false）。 关于这一点 eureka consul等注册中心皆是如此。 zk的临时node也是如此。

最主要的原因是注册中心不会区分实例数据的这部分信息。这部分在2.0可能在部分场景下作出优化。

**Comment by wangsenyan** [comment]
我也有疑问，每次重启后，下线的服务又上线了
