### ISSUE TITLE
CommandLineRunner/ApplicationRunner Blocking a task causes the Nacos Configuration Center listening to fail to start.

### ISSUE THREAD

**Issue by Nnaking** [alibaba/nacos#3935]
Blocking tasks were used in CommandLineRunner.run (), which prevented NacosContextRefresher.onApplicationEvent from receiving the event.

Similar problems: [#2725](https://github.com/alibaba/nacos/issues/2725)

Example:
```java
public class WebSocketController implements CommandLineRunner {

    @Override
    public void run(String... args) {
        while (true) {
            // TODO: 2020/9/29  
        }
    }
}
```

**Comment by KomachiSion** [comment]
Which the `WebSocketController` is in?

**Comment by Nnaking** [comment]
WebSocketController is a Controller that I wrote.

**Comment by Nnaking** [comment]
Implement CommandLineRunner/ApplicationRunner in the project.Blocking a task with While (true) or Thread.sleep (1000) causes Spring to fail to emit an ApplicationReadyEvent.Nacos Configuration Center listening to fail to start.

**Comment by Nnaking** [comment]
It is recommended that prompt for an error or warning when the Nacos Configuration Center does not receive an ApplicationReadyEvent.

**Comment by KomachiSion** [comment]
I don't think nacos should to judge this.

It's a spring usage problem. And nacos is hard to judge whether spring loading ready or something error.

**Comment by Nnaking** [comment]
Can Nacos add FAQ to tell consumers that The Nacos Configuration Center is listening for troubleshooting scenarios that can't be started?

**Comment by KomachiSion** [comment]
> Can Nacos add FAQ to tell consumers that The Nacos Configuration Center is listening for troubleshooting scenarios that can't be started?

We maybe enable to enhance the hint like you said before. For example, we add an task to check whether received the ready event, if not received, print warn log to describe the auto-fresh can't work.

**Comment by Nnaking** [comment]
thix.
