### ISSUE TITLE
spring user the annoation @value can"t get the new value after pushlish the nacos config

### ISSUE THREAD

**Issue by jetty-guo** [alibaba/nacos#3938]
register center should get the config always time,so I use the annoation @nacosValue alway not work...

 i excpect the @value or @nacosvalue use get the best neweset config value

**Comment by KomachiSion** [comment]
`@Value` is spring boot annotation, it will not refresh value.

If `@NacosValue` can't work, please provide your full configuration of spring, configuration of nacos. And let community help you.

**Comment by KomachiSion** [comment]
No more response from author. Close issue
