### ISSUE TITLE
为什么这里会报空指针异常呢，难道是我忘记引入其他该有的jar包了吗？

### ISSUE THREAD

**Issue by wonagequ** [alibaba/nacos#3941]
![image](https://user-images.githubusercontent.com/42529256/94695583-ab477080-0368-11eb-9c7b-a7d728c73328.png)

java.lang.NullPointerException: null
	at com.netflix.loadbalancer.ConfigurationBasedServerList.getUpdatedListOfServers(ConfigurationBasedServerList.java:54) ~[ribbon-loadbalancer-2.3.0.jar:2.3.0]

**Comment by horizonzy** [comment]
ClientConfig没有正确初始化。跟一下在哪里初始化的

**Comment by wonagequ** [comment]
> ClientConfig没有正确初始化。跟一下在哪里初始化的
好像直接就没有初始化，头都晕了

**Comment by KomachiSion** [comment]
ClientConfig是你自己实现的吗？ 你看下是不是没有注入到spring里

**Comment by KomachiSion** [comment]
It may not be nacos' problem, seems that application do not init and inject bean to spring.
