### ISSUE TITLE
login status 401 Unauthorized

### ISSUE THREAD

**Issue by caryfang** [alibaba/nacos#3942]
去年公司使用的1.1.4，今年重新安装电脑所以又下载了一次1.1.4，居然登录一直提示用户名或密码错误；

后来仔细排查，确实和另一个401 issues类似，是因为页面登录请求的是： /nacos/v1/auth/users/login  
返回：
{"timestamp":"2020-10-01T15:27:28.712+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/nacos/v1/auth/users/login"}

但conf/application.properties 文件里，配置的不需要验证权限的url里，却是v1/auth/login，

这就导致了上述问题。

去公司线上环境对比了下，去年下载的版本是好的。很奇怪现在下载的为什么会有这个问题。希望官方验证下给予修正。（或我理解错的，给予帮助解决。谢谢！）

临时解决方案：换最新版本下载使用。

**Comment by caryfang** [comment]
后来发现，是因为装过其他版本的，后来前端页面就有了js缓存，导致再启动其他版本时，js没更新，调用的接口就不对了。
多次重复刷新浏览器解决。

**Comment by KomachiSion** [comment]
清理浏览器缓存即可

**Comment by dumy0630** [comment]
遇到同样的问题，已解决，感谢！！！
