### ISSUE TITLE
naming-server日志显示某个dubbo服务实例数量持续跳变，重启nacos服务后才恢复正常

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#3945]
**Describe the bug**
重新部署几个微服务之后，发现有一个Dubbo服务不能正常访问，登录nacos注册中心查询该服务的实例数量，发现一直在0~n（实际部署实例个数）之间变化。这类问题有很多同学已经发过求助帖子了，比如：
#2329
#3726
#3733
#3572
此类问题目前的答复都是说检查服务程序、查网络，我们搞定的办法和上述帖子一样，就是重启nacos服务，所以我们觉得不如查一下nacos的raft相关代码。

**Expected behavior**
nacos注册中心能够正确获取instanceList。

**Acutally behavior**
nacos注册中心获取的instanceList数量一直在0~n（n是实际实例数量）之间变化。

**How to Reproduce**
Steps to 8reproduce the behavior:
1. 重新部署A、B微服务，A、B有相互调用的dubbo服务；
2. A服务的某个dubbo服务无法正常访问，nacos服务器的naming-server日志一直不间断地输出下列内容(除了时间变化外，其他输出内容基本相同）；
```
yyyy-mm-dd 21:38:31,332 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@providers:com.test.AuthService::, value: {"instanceList":[{"app":"unknown","clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceId":"192.168.0.30#20889#DEFAULT#DEFAULT_GROUP@@providers:com.test.AuthService::","instanceIdGenerator":"","ip":"192.168.0.30","ipDeleteTimeout":30000,"lastBeat":1601559510675,"marked":false,"metadata":{"side":"provider","methods":"logoutByUser,listMenusByUser","release":"2.7.5","deprecated":"false","dubbo":"2.0.2","threads":"80","pid":"9990","interface":"com.test.AuthService","threadpool":"fixed","timeout":"15000","generic":"false","revision":"1.4.3","retries":"0","path":"com.test.AuthService","protocol":"dubbo","application":"test-auth","iothreads":"40","dynamic":"true","category":"providers","dispatcher":"all","anyhost":"true","timestamp":"1601556357351"},"port":20889,"serviceName":"DEFAULT_GROUP@@providers:com.test.AuthService::","tenant":"","weight":1.0}]}

yyyy-mm-dd 21:38:31,930 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@providers:com.test.AuthService::, value: {"instanceList":[]}

yyyy-mm-dd 21:38:32,385 INFO receive config info: unknown#192.168.0.4:8858#1601559512385#1

yyyy-mm-dd 21:38:32,863 INFO receive config info: unknown#192.168.0.5:8858#1601559512862#1

yyyy-mm-dd 21:38:33,201 INFO receive config info: unknown#192.168.0.6:8858#1601559513200#1
```

3. 重启nacos服务之后，不再输出上述内容，nacos注册中心显示那个dubbo服务实例数量不再变了，与实际部署的数量一致，可以被正常访问了。

**Desktop (please complete the following information):**
 - OS: Centos 7.4
 - Version  nacos-server 1.2.1, nacos-client 1.2.1

**Comment by horizonzy** [comment]
Hi. can you apply some log info. search key words `to remove keys:` in naming-distro.log. and search key words `[AUTO-DELETE-IP] service:` in naming-server.log. we can infer the result from these two kinds info

**Comment by zrlw** [comment]
在nacos服务重启之前，无法正常访问的dubbo服务所在环境上的naming.log日志一直都在输出下列内容（其中ip地址以及new ips、remove ips、current ips的数量有变化，只有current ips的数量会变成0）：
```
yyyy-MM-dd hh:mm:ss,sss INFO [com.alibaba.nacos.naming.beat.sender:client.naming] [REGISTER-SERVICE] public registering service DEFAULT_GROUP@@providers:com.test.AuthService:: with instance: {"enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ip":"192.168.0.30", ... ,"weight":1}
```
上述日志中间隔一段夹杂两句：
```
yyyy-MM-dd hh:mm:ss,sss INFO [com.alibaba.nacos.client.naming.updater:client.naming] new ips(1) service: DEFAULT_GROUP@@providers:com.dcep.doms.internal.auth.AuthorizationService:: -> [{"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceId":"192.168.0.30#  ... ,"weight":1}

yyyy-MM-dd hh:mm:ss,sss INFO [com.alibaba.nacos.client.naming.updater:client.naming] current ips:(1) service: DEFAULT_GROUP@@providers:com.dcep.doms.internal.auth.AuthorizationService:: -> [{"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceId":"192.168.0.30#  ... ,"weight":1}
```
或两句:
```
yyyy-MM-dd hh:mm:ss,sss INFO [com.alibaba.nacos.client.naming.updater:client.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.dcep.doms.internal.auth.AuthorizationService:: -> [{"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceId":"192.168.0.30# ... ,"weight":1}]

yyyy-MM-dd hh:mm:ss,sss INFO [com.alibaba.nacos.client.naming.updater:client.naming] current ips:(1) service: DEFAULT_GROUP@@providers:com.dcep.doms.internal.auth.AuthorizationService:: -> [{"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceId":"192.168.0.31# ... ,"weight":1}]
```

**Comment by zrlw** [comment]
naming-distro.log和naming-server.log内容需要过两天查，我记得naming-server.log日志一直在不停地刷变化的instanceList，并没有AUTO-DELETE-IP日志。

**Comment by sanxun0325** [comment]
https://github.com/alibaba/nacos/issues/3781 可以参考一下这个.

**Comment by zrlw** [comment]
> Hi. can you apply some log info. search key words `to remove keys:` in naming-distro.log. and search key words `[AUTO-DELETE-IP] service:` in naming-server.log. we can infer the result from these two kinds info
1. 查了3台nacos注册中心的naming-distro.log文件，里面内容只有10月1日晚上9点重启nacos服务之后的内容，没有搜到remove关键字，重启nacos之前的内容貌似被nacos启动过程给自动清掉了。
2. 重启之前的naming-server日志内容在naming-server-bak.log，从10月1日晚上6点才开始有AUTO-DELETE-IP，这些日志是我们尝试重启那个已经24小时不能正常访问的dubbo服务时才出现的，9月30日下午开始这个dubbo服务就不能正常访问了，过去24小时的naming-server日志里都没有AUTO-DELETE-IP，只是持续不停说那个dubbo服务的datum is changed，而每次输出的instanceList一直在变。

请问有什么办法能重新这个问题以确认sanxun0325修改后的代码有效？

**Comment by sanxun0325** [comment]
@zrlw issue 3781的复现的方式：在服务列表上删除服务-》重启服务-》再次删除服务-》再次重启服务，就可以看到nacos 服务列表中 服务间隙性查询不到。

**Comment by zrlw** [comment]
前天尝试按照sanxun0325的方法重现，浏览器登录nacos注册中心（有3个节点）A节点管理控制台，把那个消费者实例从服务列表里删掉了，刷新页面发现实例数自动恢复（消费者部署了10台，没有重启），删了几次马上刷页面也没有刷出来跳变，就放弃了。
今天上班重新刷页面发现这个消费者的实例数量在跳变，查了日志发现就是前天删除操作时点过了二十多秒后开始出现的，3台nacos注册节点的情况如下。
1. A节点（follower）：
naming-distro.log日志没有变化，还是10月1日晚重启nacos服务时的内容； 不停增长的日志有naming-server.log, naming-event.log,nacos.log,config-client-request.log,config-memory.log,naming-push.log,nacos_gc.log.0.current。其中naming-server.log一直刷这个消费者的datum is changed，instanceList一直变；naming-event不停地刷[IP-UPDATED]（ips列表在变）、{SYNC} {IP-DEAD}（dead ips的列表在变）、{SYNC} {IP-NEW}（new ips的列表在变）；naming-push.log刷这个消费者is changed, add it to push queue；其他日志内容貌似无关，nacos_gc.log.0.current刷的是PSYoungGen（1G左右到2M左右）；nacos.log刷listen config id（各个服务都有）；config-client-request.log刷polling的timeout（没看到和这个消费者相关的ip）；config-memory.log刷long-polling的client count以及groupCount、toNotifyTaskSize信息。

2. B节点( leader）：和A节点日志类似。

3. C节点( follower）：和A节点日志类似，和A、B节点不同的是，这个节点的naming-server日志从前天最后一次删除服务列表操作二十多秒后开始，首先刷的是那个消费者的[AUTO-DELETE-IP]（现在还刷，其他两个节点没有这个）。

**Comment by KomachiSion** [comment]
3781的问题应该会在1.4.0修复，
您可以clone develop分支，然后自行打包一下测试一下，看下还会不会出现。

**Comment by KomachiSion** [comment]
@zrlw 请问您测试develop分支了吗？ 还会出现这个问题吗？

**Comment by zrlw** [comment]
> @zrlw 请问您测试develop分支了吗？ 还会出现这个问题吗？
在nacos注册中心删除服务能重现，这个用develop分支可以解决，但是
kill掉服务进程重新部署程序时出的问题没能重新过（不知道怎么才能重现），所以不清楚develop分支是否能解决重新部署时出现的问题

**Comment by zrlw** [comment]
那个消费者服务列表持续变化的环境我们还一直保留着，注册中心A节点18号上午9点的naming-distro日志出现一条之前没有的信息 (jdk 1.8, nacos1.2.1)：
error while notifying listener of key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@consumers:那个消费者
堆栈主要内容：
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)、$Itr.next(ArrayList.java.859)
at com.alibaba.nacos.naming.core.Service.updateIPs(Service.java:206)、onChange(Service.java:175, Service.java:50) 
at com.alibaba.nacos.naming.consistency.ephemeral.distro.DistroConsistencyServiceImpl$Notifier.run(DistroConsistencyServiceImpl.java:403)

**Comment by KomachiSion** [comment]
如果服务实例没有问题的话，这个issue先关了吧，订阅者列表变化再新开一个issue吧。混在一起不好检索

**Comment by yangbo1987** [comment]
这个问题最终是怎么解决的  目前我这也是出现一个服务频繁跳变

**Comment by yangbo1987** [comment]
> PS：我们的consumer和provider都在服务列表里，订阅者列表一直是空的。

我这一样订阅者 为空
环境 ：boot 2.2.6.RELEASE  nacos:1.2.1 cloud: Hoxton.SR3 alibaba:2.2.1.RELEASE

**Comment by yangbo1987** [comment]
> 如果服务实例没有问题的话，这个issue先关了吧，订阅者列表变化再新开一个issue吧。混在一起不好检索
除了重启还有啥法子么，目前就差nacos-server重启了

**Comment by zrlw** [comment]
1. 你们的实例数量是否很多，很多就会有很多心跳包，nacos注册中心tomcat线程数server.tomcat.maxThreads、nacos用户最大句柄数都需要调大。
2. nacos 1.2.1有很多毛病，推荐用1.4.2(客户端和服务端都需要升）
3. 你们如果用nacos sync，这个也需要升，nacos sync不适合实例数量频繁变化的场景，切换演练时需要先停掉，等实例全部注册完毕后再启动sync。
