### ISSUE TITLE
nacos版本切换配置转移问题

### ISSUE THREAD

**Issue by 8bun** [alibaba/nacos#3950]
请问升级nacos版本之后，之前的配置怎么转移到新版本来？

**Comment by horizonzy** [comment]
如果不是从mysql切到derby的话，配置是不需要进行转移的。之前的配置都还存在

**Comment by 8bun** [comment]
> 如果不是从mysql切到derby的话，配置是不需要进行转移的。之前的配置都还存在

我之前没配置到mysql，使用的是默认配置，数据在哪找？
