### ISSUE TITLE
 closed nacos in undertow server , report NullPointException.

### ISSUE THREAD

**Issue by jasonpyf** [alibaba/nacos#3957]
class :
io.undertow.servlet.spec.ServletContextImpl

method:
io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames()

problem:
public Enumeration<String> getInitParameterNames() {
    return new IteratorEnumeration<>(deploymentInfo.getInitParameters().keySet().iterator());
}

deploymentInfo is null.

temporary solution:
@Override
    public Enumeration<String> getInitParameterNames() {
    	if(deploymentInfo != null) {
    		return new IteratorEnumeration<>(deploymentInfo.getInitParameters().keySet().iterator());
    	} else {
    		Set<String> defaultSet = new HashSet<>();
    		return new IteratorEnumeration<>(defaultSet.iterator());
    	}
    }

**Comment by KomachiSion** [comment]
Nacos do not support undertow server currently, is your modified by yourself?

**Comment by KomachiSion** [comment]
No more response from author, close issue.
