### ISSUE TITLE
有哪个接口可供k8s的readinessProbe监测

### ISSUE THREAD

**Issue by HiroC222** [alibaba/nacos#3959]
nacos 版本: 1.1.0
kubernetes: 1.15.3

有哪个接口可以给k8s的readinessProbe提供监测？

有了登陆验证以后下面这两个就没法继续使用了。
/v1/console/health/liveness
/v1/console/health/readiness

我在使用中发现服务某个节点重启后，会出现启动成功，但是部分接口功能异常的情况，比如下面这个。
“/nacos/v1/ns/catalog/services?withInstances=false&pageNo=1&pageSize=10”

通过/nacos/actuator/health/检测无法发现问题节点。

**Comment by KomachiSion** [comment]
duplicate with  #3923
