### ISSUE TITLE
zuul 使用nacos作为配置中心无法路由转发后端服务（敏感的请求头丢失authorization）

### ISSUE THREAD

**Issue by qihaooo** [alibaba/nacos#3962]
**Describe the bug**
springcloud中使用nacos配置中心无法转发后端服务，如果使用本地的配置文件是可以转发。前提我的配置文件中配置了zuul.sensitive-headers:   而bug出现在如果使用nacos配置中心，zuul源码中ribbonfileter中sensitive-headers会带有多余的3个请求头（Cookie, Set-Cookie,Authorization）,而使用本地配置文件sensitive-headers为空。

**Expected behavior**
使用nacos时，如果配置了zuul.sensitive-headers:   uul源码中ribbonfileter中的sensitive-headers应该也为空。

**Acutally behavior**
使用nacos时，如果配置了zuul.sensitive-headers:   uul源码中ribbonfileter中的sensitive-headers为Cookie, Set-Cookie,Authorization数组

**How to Reproduce**

**Desktop (please complete the following information):**
 - windows
 - nacos-server 1.3.0, nacos-client 1.2.1]
 -config
 - spring-cloud-alibaba-nacos

**Additional context**

**Comment by KomachiSion** [comment]
`Cookie, Set-Cookie,Authorization数组` 是哪里添加进去的呢？

**Comment by qihaooo** [comment]
zuul源码中pre执行的过滤器PreDecrationFilter中添加的，
![image](https://user-images.githubusercontent.com/26671062/95701596-99c16b00-0c7c-11eb-8102-507c1a92f723.png)，如果用nacos,会执行if里面的代码

**Comment by KomachiSion** [comment]
那我觉得应该不是nacos的问题，zuul自行判断了一些内容，然后自行添加了它的header。

或者你跟一下，nacos什么地方的什么原因导致了他的判读条件变化了。

**Comment by KeRan213539** [comment]
这跟nacos没关系,我记得zuul默认是会去除authorization后转发的,网上有解决方法,搜一下.
也可以参考这个: [Zuul网关导致请求头信息丢失的解决办法](https://blog.csdn.net/czx2018/article/details/105618223)

**Comment by KeRan213539** [comment]
@qihaooo 你是用的SCA还是直接用的nacos client(spring boot)?
