### ISSUE TITLE
nacos作注册中心，集群的隔离性问题

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#3963]
场景：服务A和服务B使用nacos注册中心，服务B有多个集群，每个集群下有多个实例。现在服务A想要调用服务B下集群1中的接口，那么这个时候nacos需要怎么设置来让服务A可以调用到服务B下指定集群的实例？

**Comment by vicykie** [comment]
A 和B集群1使用同一个group，B的其他集群是其他group

**Comment by HelloHaiNG** [comment]
> A 和B集群1使用同一个group，B的其他集群是其他group

一个group不是可以有多个集群吗，那么根据group的话有可能还是做不到指定集群的调用

**Comment by KomachiSion** [comment]
`NamigService.getAllInstances(String serviceName, String groupName, List<String> clusters)`这个接口可以只获取某几个集群的实例。

spring-cloud可能需要自己添加过滤器

**Comment by HelloHaiNG** [comment]
> `NamigService.getAllInstances(String serviceName, String groupName, List<String> clusters)`这个接口可以只获取某几个集群的实例。
> 
> spring-cloud可能需要自己添加过滤器

也就是说使用nacos中心的话，服务A去调服务B，在不进行自身扩展的情况下，目前只能做到服务A只会去调用同一个namespace下的同一个group的服务B的实例，如果说这个group下有多个集群，是区分不了的是吗？只能做到group颗粒度下的精确调用？

**Comment by KomachiSion** [comment]
nacos的sdk是支持精确到cluster的，但是spring-cloud里并没有这个概念，spring-cloud的体系就是以namespace和serviceName进行区分。

**Comment by HelloHaiNG** [comment]
> nacos的sdk是支持精确到cluster的，但是spring-cloud里并没有这个概念，spring-cloud的体系就是以namespace和serviceName进行区分。

nacos不是默认支持了ribbon吗，然后源码中的NacosRule.choose()中这个逻辑我看好像有做cluster的筛选
List<Instance> instancesToChoose = instances;
			if (StringUtils.isNotBlank(clusterName)) {
				List<Instance> sameClusterInstances = instances.stream()
						.filter(instance -> Objects.equals(clusterName,
								instance.getClusterName()))
						.collect(Collectors.toList());
				if (!CollectionUtils.isEmpty(sameClusterInstances)) {
					instancesToChoose = sameClusterInstances;
				}
				else {
					LOGGER.warn(
							"A cross-cluster call occurs，name = {}, clusterName = {}, instance = {}",
							name, clusterName, instances);
				}
			}

**Comment by KomachiSion** [comment]
默认支持ribbon应该是在spring-cloud-alibaba里做的，如果是结合上有问题，请提交issue到spring-cloud-alibaba社区。
nacos社区主要是nacos服务端，基础sdk和openAPI相关，spring-cloud使用仅能做到简单回答，抱歉。

**Comment by HelloHaiNG** [comment]
> 默认支持ribbon应该是在spring-cloud-alibaba里做的，如果是结合上有问题，请提交issue到spring-cloud-alibaba社区。
> nacos社区主要是nacos服务端，基础sdk和openAPI相关，spring-cloud使用仅能做到简单回答，抱歉。
好的，感谢
