### ISSUE TITLE
1.3.2 nacos server命名空间权限问题

### ISSUE THREAD

**Issue by caishaolinlin** [alibaba/nacos#3965]
**现在我有3个环境dev、test、prd命名空间，新增账号erz，并指定dev、test读写权限。但是erz登录之后能看到所有命名空间，并且能操作prd，这个我没开的权限。
然后我把nacos.core.auth.enabled=true之后，虽然点击prd时会提示authorization failed!。
但是浏览器加载动态图直都在，而且再点其它命名空间没有任何反应，也没有请求后台，可能是前端js报错引起**
Now I have three environment dev, test, prd namespace, add the account erz, and specify the read and write permissions for dev and test. However, after logging in, erz can see all the namespace and operate prd, which I have no permission to open.
Then I put nacos.core.auth.enabled=true, authorization failed! Will be prompted when you click prd!.
However, the dynamic loading graph of the browser is always there, and there is no response when clicking on other namespace, and there is no request in the background. This may be caused by an error reported by the front-end JS

pictrue

![image](https://user-images.githubusercontent.com/6129374/95681787-4d424500-0c14-11eb-84a2-1bb592d614fc.png)

**Comment by KomachiSion** [comment]
Will fix in 1.4.0

see #2835
