### ISSUE TITLE
Is this project about to take the dubbo old road?

### ISSUE THREAD

**Issue by anpu2018** [alibaba/nacos#3966]
Many problems found before have not been modified, but anxious to broaden the ecology of the go language.

Registration found poor compatibility with access control, poor adaptability to various versions of springcloud alibaba, and many other problems.

Not to mention webadmin. Re-login after the session timeout cannot be routed to the page visited before the timeout. After viewing the details in the configuration list, it will return to the first page and so on. The most basic user experience is not guaranteed.

Nacos is a very good microservice middleware implemented based on the raft protocol. I think the ecology and user experience of the Java language are the main issues that your team should consider, rather than broadening the language adaptation to do the knowledge and not precise.

Please do not follow the old dubbo road, otherwise it will disappoint many users.

Best wishes for nacos.

**Comment by KomachiSion** [comment]
There are many problems in `nacos`, so we need more contributor and committer to enhance and upgrade it.

If you wish it become better and faster, please join us and do contributions.

Thanks.
