### ISSUE TITLE
nacos open api无法查询到已经下线的服务

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/nacos#3967]
**Describe the bug**
如果后端有需要调用open api做一些自定义处理，比如：下线、服务变动监听(生成环境有需要服务异常了短信通知负责人)等等，但发现nacos open api去查询服务时，已经下线的服务无法查询，如果都服务查询到了，open api修改服务有什么意义(比如操作服务上下线)

**Desktop (please complete the following information):**
 - OS: centos7
 - Version: nacos-server 1.3.1, nacos-client 1.3.1
 - Module: naming/config
 - SDK: spring-cloud-alibaba-nacos

**Additional context**
调用open api 接口：
1.  /nacos/v1/ns/service/list
2.  /nacos/v1/ns/instance/list

**Comment by KomachiSion** [comment]
Sorry, the openAPI current means the usage api not admin api.

We may upgrade more admin api to openAPI.

For your problem, you can use `/nacos/v1/ns/catalog/services` or `/nacos/v1/ns/catalog/instances` to search them.

**Comment by zxiaozhou** [comment]
@KomachiSion Thank you. I see
