### ISSUE TITLE
根据分组名称搜索特殊字符匹配错误的问题

### ISSUE THREAD

**Issue by kiddingYang** [alibaba/nacos#3969]
**Describe the bug**

如果服务名称为A-B的形式，根据分组名称搜索-会搜索到A-B的服务。应该是正则表达式构建错误，导致在匹配时，匹配到了分组和服务的全不名称。

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Which api or which page of console cause this problem？
 
We need to discuss whether do these enhancement and how to enhance it.

**Comment by kiddingYang** [comment]
> Which api or which page of console cause this problem？
>  
> We need to discuss whether do these enhancement and how to enhance it.

/nacos/v1/ns/catalog/services

**Comment by JackSun-Developer** [comment]
>如果服务名称为A-B的形式，根据分组名称搜索-会搜索到A-B的服务

你的意思是，服务名注册为A-B
![image](https://user-images.githubusercontent.com/58767027/109747069-74c09b00-7c11-11eb-9d7f-1bf17f9c386e.png)
，然后在分组搜索“-”时能搜到A-B服务？
![image](https://user-images.githubusercontent.com/58767027/109747097-80ac5d00-7c11-11eb-9d4c-0ce2603bb88b.png)
似乎无法复现。

**Comment by JackSun-Developer** [comment]
@kiddingYang 你的服务列表是什么样的？以及搜索规则是什么？
