### ISSUE TITLE
K8S单机模式连接MySQL

### ISSUE THREAD

**Issue by lijilina** [alibaba/nacos#3972]
我在K8S上部署了单机模式的nacos，也通过变量配置了连接的数据库，也执行了数据库的sql，可以启动web界面也可以访问，但是似乎没有使用数据库存储

nacos1.2.1
K8S 1.6.8
MySQL5.7

**Comment by KomachiSion** [comment]
单机模式默认使用derby数据库，如果需要连接MySQL 需要修改application.properties的`spring.datasource.platform=mysql`

**Comment by lijilina** [comment]
可以了 谢谢
