### ISSUE TITLE
Nacos注册中心集群模式，每个Nacos节点上注册的服务列表数据不一致

### ISSUE THREAD

**Issue by chenqinyuan** [alibaba/nacos#3975]
（leader节点41个注册服务，followerA节点39个注册服务，followerB节点37个注册服务）

- 请问是由于Nacos注册中心默认使用AP模式，导致的不一致么？
- AP模式下，服务注册数据的最终一致性是如何保证的呢？

**Comment by KomachiSion** [comment]
不一致就有问题，和AP CP没有关系。

麻烦查一下所有节点的所有日志，看下是不是有什么错误导致节点间数据不一致

**Comment by KomachiSion** [comment]
Any process or new information provided? If no more response and information, we will close issue

**Comment by KomachiSion** [comment]
@chenqinyuan your provided information is not enough to reproduce problem, and no response more than 7 days, I will close issue
