### ISSUE TITLE
Beatinfo in client will not update when client didn't call com.alibaba.nacos.client.naming.core.HostReactor#getServiceInfo

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#3976]
**Describe the bug**
in #2800. we will update beatinfo when instance changed. but if we not invoke `com.alibaba.nacos.client.naming.core.HostReactor#getServiceInfo`. it can't be updated. the problem in #2800 will exist still.

**Expected behavior**
when register instance, call `hostReactor
                        .getServiceInfo(NamingUtils.getGroupedName(serviceName, groupName), StringUtils.join(clusters, ",")`

**Comment by KomachiSion** [comment]
We need to discuss this feature, From the original design, the information of instance is based on client register and beat report. When app restarted, the information will be reset.

It seems same as eureka and consul.

And I think add this auto-fresh will cost much resources for client.

**Comment by chuntaojun** [comment]
> We need to discuss this feature, From the original design, the information of instance is based on client register and beat report. When app restarted, the information will be reset.
> 
> It seems same as eureka and consul.
> 
> And I think add this auto-fresh will cost much resources for client.

As far as I am concerned, the heartbeat is just a live operation, and the metadata information and weight should not be modified. Service: Group: Cluster: IP: port should only be synchronized

Metadata information, weights, and so on should be handled by additional interfaces

**Comment by horizonzy** [comment]
> > We need to discuss this feature, From the original design, the information of instance is based on client register and beat report. When app restarted, the information will be reset.
> > It seems same as eureka and consul.
> > And I think add this auto-fresh will cost much resources for client.
> 
> As far as I am concerned, the heartbeat is just a live operation, and the metadata information and weight should not be modified. Service: Group: Cluster: IP: port should only be synchronized
> 
> Metadata information, weights, and so on should be handled by additional interfaces

Now the beatinfo will updated if call com.alibaba.nacos.client.naming.core.HostReactor#getServiceInfo. com.alibaba.nacos.client.naming.core.HostReactor#getServiceInfo will call in com.alibaba.nacos.client.naming.NacosNamingService#getAllInstances or com.alibaba.nacos.client.naming.NacosNamingService#subscribe。if user not call one of both. the beatInfo will not update.
