### ISSUE TITLE
修改配置时候， CacheData里面safeNotifyListener方法的 Runnable.run时候报错

### ISSUE THREAD

**Issue by hongdongqu** [alibaba/nacos#3979]
springBootVersion = '2.1.6.RELEASE'
springCloudVersion = 'Greenwich.SR2'
springCloudAlibabaVersion = '2.1.2.RELEASE'
报错异常：ExistingValue must be an instance of org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean

**Comment by hongdongqu** [comment]
![image](https://user-images.githubusercontent.com/57446723/95831957-4af2fe80-0d6c-11eb-82ec-051fb5872365.png)

**Comment by hongdongqu** [comment]
![image](https://user-images.githubusercontent.com/57446723/95832019-59411a80-0d6c-11eb-894c-7f6833e2b3c8.png)

**Comment by KomachiSion** [comment]
Please use issue template to describe your problem

**Comment by KomachiSion** [comment]
看起来像是客户端收到了新配置推送，在刷新配置的时候 spring报了类型错误的异常，您需要再往深的位置跟一下，看看是不是配置不正确导致类型错误。

**Comment by KomachiSion** [comment]
@hongdongqu Any process? if no more response we will close issue.

**Comment by KomachiSion** [comment]
No response from author, close issue

**Comment by wendell-dev** [comment]
> 看起来像是客户端收到了新配置推送，在刷新配置的时候 spring报了类型错误的异常，您需要再往深的位置跟一下，看看是不是配置不正确导致类型错误。

我遇到过类似问题，但没有得到解决。

我的情况是：
1. 开启了配置动态刷新
2. 配置一个正常的配置项，这时程序正常运行
3. 更新配置，设置为一个**错误的**配置项值，如boolean型的设置为其它值（这时候会报错BindException: Failed to bind properties under 'xxxx' to boolean）
4. 更新配置，将上一步错误的配置值**修改为正确值**（预期是能够成功应用正确的配置，但结果还是上一步的报错信息）

**Comment by wendell-dev** [comment]
> 看起来像是客户端收到了新配置推送，在刷新配置的时候 spring报了类型错误的异常，您需要再往深的位置跟一下，看看是不是配置不正确导致类型错误。

@KomachiSion  hi， 还可以追踪一下这个已经被close的issue吗
