### ISSUE TITLE
修改配置当时，CacheData里面safeNotifyListener方法的Runnable.run时候报错

### ISSUE THREAD

**Issue by hongdongqu** [alibaba/nacos#3980]
springBootVersion ='2.1.6.RELEASE'springCloudVersion
='Greenwich.SR2'springCloudAlibabaVersion
='2.1.2.RELEASE'
报错异常：ExistingValue must be an instance of org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean

**Comment by KomachiSion** [comment]
duplicate with #3979
