### ISSUE TITLE
nacos是否存在类似springcloudconfig的allow-override等本地控制权限参数？或者是否支持这个参数

### ISSUE THREAD

**Issue by ShooTingst** [alibaba/nacos#3981]
现在有这样一个需求，用户希望本地设置能和nacos配置中心中存储的设置进行动态切换，故尝试运用了allow-override: true 但是发现没有效果（不管是放在nacos里还是本地的application还是bootstrap)，所以想请问一下是否存在类似参数实现这种功能？谢谢

**Comment by chuntaojun** [comment]
你可以在这里放配置

**Comment by chuntaojun** [comment]
https://blog.csdn.net/u010634066/category_9300707.html
