### ISSUE TITLE
ThreadUtils

### ISSUE THREAD

**Issue by wsj-cmm** [alibaba/nacos#3993]
public static void addShutdownHook(final Runnable runnable) {
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            @Override
            public void run() {
                runnable.run();
                Runtime.getRuntime().removeShutdownHook(Thread.currentThread());

            }
        }));
    }

**Comment by KomachiSion** [comment]
Please edit your issue description by using issue template to describe your problem.

Please change your issue title so that search and understand friendly.
