### ISSUE TITLE
DefaultPublisher

### ISSUE THREAD

**Issue by wsj-cmm** [alibaba/nacos#3994]
protected final ConcurrentHashSet<Subscriber> subscribers = new ConcurrentHashSet<Subscriber>();   
 @Override
    public void addSubscriber(Subscriber subscriber) {
        subscribers.add(subscriber);
    }
in the develop branch, i find the subscriber do not override the hashcode method

**Comment by KomachiSion** [comment]
Please edit your issue description by using issue template to describe your problem.

Please change your issue title so that search and understand friendly.
