### ISSUE TITLE
failed to request java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by chxiaowu** [alibaba/nacos#3996]
**Describe the bug**
in test env, can start ok, but in prod( custom server , new installed a  nacos server),  error as below, try  1.3.1 server and 1.3.2 server(tar install)

**Expected behavior**
service register ok

**Acutally behavior**
no service list in dashbord. (8848 can visit ok in web browser)

**Desktop (please complete the following information):**
 - OS: CentOS 7.2
 - Version: nacos-server 1.3.1/1.3.2, nacos-client 1.3.3]
 - Module: naming 
 - SDK:
      

>  <dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>         </dependency>
>         <dependency>
>             <artifactId>spring-cloud-starter-dubbo</artifactId>-->
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-dubbo</artifactId>
>         </dependency>

        
![image](https://user-images.githubusercontent.com/3086363/96116089-816e7c00-0f1a-11eb-818f-0bfe751155f0.png)

exception:
   

> 19:04:35.699 [main] INFO  o.a.d.c.bootstrap.DubboBootstrap -  [DUBBO] The registry[<dubbo:registry subscribe="false" group="redsteward" address="localhost" protocol="spring-cloud" port="0" />] will be not used as the metadata center, dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:35.759 [main] INFO  o.a.d.c.bootstrap.DubboBootstrap -  [DUBBO] DubboBootstrap has been initialized!, dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:35.817 [main] INFO  o.apache.dubbo.config.ServiceConfig -  [DUBBO] No valid ip found from environment, try to find valid host from DNS., dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:36.073 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
> 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
> 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
> 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
> 	at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:109)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
> 	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:339)
> 	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:420)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 19:04:36.080 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
> 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
> 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
> 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
> 	at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:109)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
> 	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:339)
> 	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:420)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 19:04:36.081 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
> 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
> 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
> 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
> 	at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:109)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
> 	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:339)
> 	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:420)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 19:04:36.082 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
> java.net.ConnectException: Connection refused (Connection refused)
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
> 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
> 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
> 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
> 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
> 	at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:109)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
> 	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
> 	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
> 	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:339)
> 	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:420)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 19:04:36.082 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - request: /nacos/v1/ns/instance/list failed, servers: [nacos://172.25.213.2:8848], code: 500, msg: Connection refused (Connection refused)
> 19:04:36.108 [main] WARN  o.apache.dubbo.config.ServiceConfig -  [DUBBO] Use random available port(20880) for protocol dubbo, dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:36.190 [main] INFO  o.apache.dubbo.config.ServiceConfig -  [DUBBO] Export dubbo service com.alibaba.cloud.dubbo.service.DubboMetadataService to local registry url : injvm://127.0.0.1/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=base-service-provider&bind.ip=172.25.213.1&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=base-service-provider&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&metadata-type=remote&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=14127&qos.enable=false&release=2.7.8&revision=2.2.3.RELEASE&side=provider&timestamp=1602759875781&version=1.0.0, dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:36.191 [main] INFO  o.apache.dubbo.config.ServiceConfig -  [DUBBO] Register dubbo service com.alibaba.cloud.dubbo.service.DubboMetadataService url dubbo://172.25.213.1:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=base-service-provider&bind.ip=172.25.213.1&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=base-service-provider&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&metadata-type=remote&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=14127&qos.enable=false&release=2.7.8&revision=2.2.3.RELEASE&side=provider&timestamp=1602759875781&version=1.0.0 to registry registry://172.25.213.2:8848/org.apache.dubbo.registry.RegistryService?application=base-service-provider&dubbo=2.0.2&group=redsteward&namespace=b262ae41-9d7a-45ab-8f58-db69559cd6a2&pid=14127&qos.enable=false&registry=nacos&release=2.7.8&subscribe=false&timestamp=1602759875780, dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:36.508 [main] INFO  o.a.d.q.protocol.QosProtocolWrapper -  [DUBBO] qos won't be started because it is disabled. Please check dubbo.application.qos.enable is configured either in system property, dubbo.properties or XML/spring-boot configuration., dubbo version: 2.7.8, current host: 172.25.213.1
> 19:04:37.186 [main] INFO  o.a.d.r.transport.AbstractServer -  [DUBBO] Start NettyServer bind /0.0.0.0:20880, export /172.25.213.1:20880, dubbo version: 2.7.8, current host: 172.25.213.1

**Comment by KomachiSion** [comment]
`ERROR com.alibaba.nacos.client.naming - [NA] failed to request java.net.ConnectException: Connection refused (Connection refused)` 

Please check your nacos server has start successfully, address of setting in client is right, and check the net can connect.

**Comment by KomachiSion** [comment]
`19:04:36.082 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - request: /nacos/v1/ns/instance/list failed, servers: [nacos://172.25.213.2:8848], code: 500, msg: Connection refused (Connection refused)` 

I think your configuration is wrong, your input server address to nacos is `nacos://172.25.213.2:8848` not `172.25.213.2:8848` or `http://172.25.213.2:8848`

**Comment by chxiaowu** [comment]
172.25.213.2:8848
sorry， copy mistake，not bug，
