### ISSUE TITLE
k8s部署 滚动发布 心跳接口500超时

### ISSUE THREAD

**Issue by handong0123** [alibaba/nacos#3997]
nacos：1.3.2
nacos config starter: 2.1.1.RELEASE
环境: k8s

部署方式: 3个副本， 4个固定IP(一个用作滚动发布)

nacos镜像的集群ip配置了4个，所以一直有一个节点是离线的状态
此时 配置中心的心跳会一直报错500

像这种滚动发布，ip从4个里选3个的情况， 应该怎么配置

**Comment by KomachiSion** [comment]
配置了4个，其中一个离线（未启动或网络不通），当然会一直心跳报错，因为服务端之间也会一直发心跳来认知服务端之间是健康的。

你这种情况，我建议你常态化配置3个ip，当需要滚动发布时，批量修改cluter.conf文件，nacos会自动更新

**Comment by handong0123** [comment]
是否有必要支持节点的上下线？

**Comment by KomachiSion** [comment]
平滑扩缩容能力当然是需要的，只是这个功能目前还很不完善，处于很原始的阶段。

目前只能通过依赖额外的地址服务器或者修改cluster.conf文件来进行。

**Comment by handong0123** [comment]
目前相当于服务运行时就无法修改集群配置是吗 有完善的计划吗

**Comment by KomachiSion** [comment]
上面说的这两种都是修改集群配置的方法啊。最简单的就是用cluster.conf文件来控制集群节点。

完善计划暂时没有，如果你有兴趣优化这方面功能，我们十分欢迎参与贡献。

**Comment by handong0123** [comment]
进线上容器修改cluster.conf比较繁琐而且不安全 如果通过api修改集群IP并同步到所有节点，是否符合设计思想并实现功能

**Comment by KomachiSion** [comment]
可以考虑后续提供一个修改集群节点的管理api，但是目前考虑这样安全性也不高，暂时就没有处理。

k8s可以通过operator去动态修改cluster.conf，商业化MSE目前就是这样处理的，你可以自己研究下。
