### ISSUE TITLE
nacos service discovery dont support upcase service-name

### ISSUE THREAD

**Issue by solace20** [alibaba/nacos#3998]
when i use eureka, register service-name is default upcase,so i use upcase in my gateway lb config.
but when i change to nacos, service-name is default lowercase,and my lb config can not found upcase service instance

**Comment by KomachiSion** [comment]
nacos do not change your service name to lowercase, you register your service as upper case, it will be upper case.

**Comment by solace20** [comment]
> nacos do not change your service name to lowercase, you register your service as upper case, it will be upper case.

when use eureka ,registry  with spring.application.name is default upcase , make the same with eureka,would it be friendly while change eureka to nacos?

**Comment by KomachiSion** [comment]
I don't think nacos should be same as eureka, and I don't think do operate for users configuration is a good design. So we have no plan to make the same with eureka.

For friendly usage, there are a community tools named `nacos-sync`. It may be can transfer eureka to nacos.

**Comment by KomachiSion** [comment]
Seems no more discussion, close issue.
