### ISSUE TITLE
NacosConfigProperties.server-addr未处理"/"

### ISSUE THREAD

**Issue by rootpophome** [alibaba/nacos#4000]
com.alibaba.cloud.nacos.NacosDiscoveryProperties#serverAddr
处理方式
if (serverAddr.lastIndexOf("/") != -1) {
			serverAddr = serverAddr.substring(0, serverAddr.length() - 1);
}

**Comment by rootpophome** [comment]
> .NacosDiscoveryProperties#serverAddr
> 处理方式
> if (serverAddr.lastIndexOf("/") != -1) {
> serverAddr = serverAddr.substring(0, serverAddr.length() - 1);

**Comment by KomachiSion** [comment]
please move issue to spring-cloud-alibaba community. Thanks.
