### ISSUE TITLE
SC配置中心开启权限控制，和springboot中的actuator冲突导致启动失败。

### ISSUE THREAD

**Issue by shuzhan789** [alibaba/nacos#4001]
**Describe the bug**
当配置中心 开启【NACOS_AUTH_ENABLE=true】权限控制时，和现有项目中的【spring-boot-starter-actuator：2.3.4.RELEASE】包冲突，会提示403，导致启动失败。 移除 spring-boot-starter-actuator 后项目能正常运行。
![image](https://user-images.githubusercontent.com/57164960/96210519-ad364400-0fa4-11eb-8d30-730972902a74.png)

**Desktop (please complete the following information):**
 - OS: JDK8
 - Version【spring-boot：2.3.4.RELEASE 。spring-cloud-starter-alibaba-nacos-config：2.2.3.RELEASE】测试不同版本均会出现该问题
 - SDK [nacos：1.3.2 / 1.3.1]

2020-10-16 10:52:45.209 ERROR 20364 --- [1)-192.168.93.1] com.alibaba.nacos.client.naming          : [NA] failed to request

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Oct 16 10:55:42 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611) [nacos-client-1.3.3.jar:na]

**Comment by KomachiSion** [comment]
是使用了非nacos账号吗？

**Comment by shuzhan789** [comment]
> 是使用了非nacos账号吗？

nacos的默认账户和新建的账号均是这样

**Comment by KomachiSion** [comment]
serverHealthy 会调用`/nacos/v1/ns/operator/metrics`接口，这个接口当前版本只有管理员权限的用户才可以访问，其他都会访问失败，我测试`nacos`用户不会出现这个问题，除非把这个用户的管理员权限给删除了。

1.4.0版本之后这个接口会开放权限，不需要再是管理员权限了。#2892

**Comment by KomachiSion** [comment]
1.4.0-BEAT已经发布，可以替换成1.4.0-BETA服务端后再试
