### ISSUE TITLE
Use the frontend-Maven-plugin in pom.xml to package frontend code

### ISSUE THREAD

**Issue by jzhishu** [alibaba/nacos#4002]
**Is your feature request related to a problem? Please describe.**
The main.js in [this link](https://github.com/alibaba/nacos/blob/develop/console/src/main/resources/static/js/main.js) I think is used in production environment, so it doesn't need to be managed on github

**Comment by KomachiSion** [comment]
Does Use `frontend-Maven-plugin` will cause build and compile nodejs for each `mvn install/package`?

It will depend nodejs environment and cost much time.

We need to discuss how to solve the problem before we use this.

**Comment by jzhishu** [comment]
> Does Use `frontend-Maven-plugin` will cause build and compile nodejs for each `mvn install/package`?
> 
> It will depend nodejs environment and cost much time.
> 
> We need to discuss how to solve the problem before we use this.

Yes, it will install ```node``` and ```npm```  when build project, and then ```npm install``` is executed.This process takes more time, but it may not affect developers or users
