### ISSUE TITLE
[Discuss] module dependency relation. Should common-module should relay on api-module ?

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4003]
### Describe what happened (or what feature you want)
Now common-module relay on api-module it relay on api-module class such as (`com.alibaba.nacos.api.exception.NacosException`, `com.alibaba.nacos.api.common.Constants`),if other module relay on common-module. it will relay on common-module tohether. 
In my opinion, common-module should not relay on other module. Now api-module some class such as (`com.alibaba.nacos.api.utils.StringUtils`, `com.alibaba.nacos.api.common.Constants`). I think these class should be defined in common-module. api-module should relay on common-module.

**Comment by KomachiSion** [comment]
Yes, I also think modules dependency need to be enhance.

**Comment by horizonzy** [comment]
I will have a try to enhance it.

**Comment by KomachiSion** [comment]
I suggest to discuss it first before do it.

**Comment by horizonzy** [comment]
that's fine
