### ISSUE TITLE
 Cannot create a new namespace in nacos1.3.2

### ISSUE THREAD

**Issue by zyc20001024** [alibaba/nacos#4004]
When nacos.1.3.2 is used, the namespace cannot be created. After clicking the confirmation button, the confirmation button is disabled after no response. There is no newly added namespace after refreshing the page.

在使用nacos.1.3.2时，无法新建命名空间。在点击确认按钮后，没有响应，之后确认按钮被禁用。刷新页面后也没有出现新添加的命名空间。

**Comment by KomachiSion** [comment]
Test your problem in nacos demo console. But can't reproduce, Please provide more information. Such as mode of nacos, numbers of nacos server, log contents and any more information you think useful for your problem.

**Comment by KomachiSion** [comment]
No more response from author and we can't reproduce problem by current information, close issue.
