### ISSUE TITLE
[Disscuss] Need merge client's beat when (ip+port) is same in a client ?

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4011]
**Is your feature request related to a problem? Please describe.**
Now in client, if we register N service, it will sent N beatInfo. Maybe we can add a new restApi in server, and apply a config. if trigger, client's beatinfo's (ip+port) same, just sent one beat, the beatinfo contains n serviceName.

**Comment by KomachiSion** [comment]
nacos server part will distro route by serviceName, if you merge different service beat to one request. How to route this request to right server node?

**Comment by horizonzy** [comment]
Sry, I forget distro logic when sendbeat. If server can supoort this function. authFilter need delivery the request by serviceName. It looks too customized at now. If any company need this feature,  I think this maybe reform by themselves.
