### ISSUE TITLE
使用open api 无法下线服务问题

### ISSUE THREAD

**Issue by xiahuhu1** [alibaba/nacos#4013]
### 删除服务
```bash
[root@xxx-test02 ~]# curl -X DELETE 'http://x.x.x.x:8848/nacos/v1/ns/instance?serviceName=hsp-trading&ip=x.x.x.x&port=8764&namespaceId=test'
ok[root@xxx-test02 ~]#
```
客户端执行成功返回“ok”，但是在nacos上看到服务列表中服务并没有下线依旧可以被调用。
![image](https://user-images.githubusercontent.com/38675377/96330768-a550cf80-108a-11eb-8045-fc5cea14f096.png)

**Comment by KomachiSion** [comment]
Did `hsp-trading`still send heartbeat to server?

If so, it will be add again after deleting.

**Comment by xiahuhu1** [comment]
I have not configured heartbeat detection for this service. Is there a default value for heartbeat detection? and how can i remove this default value?

**Comment by KomachiSion** [comment]
When you register instance by sdk, the heartbeat will start util you deregister the instance.

**Comment by KomachiSion** [comment]
@xiahuhu1 Any process?

**Comment by KomachiSion** [comment]
No more response from author and the problem maybe a usage problem.
