### ISSUE TITLE
按照文档要求导入naocs_config.sql文件后配置了数据库信息，登录却提示用户名密码错误

### ISSUE THREAD

**Issue by whiteS18** [alibaba/nacos#4014]
按照文档要求导入naocs_config.sql文件后配置了数据库信息，登录却提示用户名密码错误

**Comment by zbsBrave** [comment]
是不是密码没加密啊

**Comment by KomachiSion** [comment]
导入src/distribution/conf/nacos-mysql.sql试试

**Comment by whiteS18** [comment]
> 导入src/distribution/conf/nacos-mysql.sql试试

嗯嗯,我试过了,我发现是我不小心改动了配置文件中的nacos.core.auth.system.type和nacos.core.auth.enable,现在已经好了
