### ISSUE TITLE
配置新增或者编辑的时候， 编辑框出不来

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#402]
![image](https://user-images.githubusercontent.com/2010632/49568113-eba35680-f96a-11e8-88db-4fbde28a78ce.png)

这里有js错误， 服务端版本  0.5

**Comment by IronCity** [comment]
![image](https://user-images.githubusercontent.com/22296427/49708806-24457780-fc6c-11e8-8ad4-6a0fd10643ae.png)
0.6.0的页面也是 配置内容显示不出来 JS错误

**Comment by yanlinly** [comment]
@IronCity @nanamikon 
we fix in 0.8.0. u can try to test it?
http://console.nacos.io/nacos/index.html
