### ISSUE TITLE
部署文档服务发现测试url 501Not Implemented

### ISSUE THREAD

**Issue by houxiaoyi0722** [alibaba/nacos#4029]
get http://127.0.0.1:8848/nacos/v1/ns/instances?serviceName=nacos.naming.serviceName

{
    "timestamp": "2020-10-20T11:33:20.105+0000",
    "status": 501,
    "error": "Not Implemented",
    "message": "no such api:GET:/nacos/v1/ns/instances",
    "path": "/nacos/v1/ns/instances"
}

**Comment by KomachiSion** [comment]
There are one more letter in doc path, the real api is `http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName`.

We will fix it in document

**Comment by horizonzy** [comment]
> There are one more letter in doc path, the real api is `http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName`.
> 
> We will fix it in document

the right url maybe http://127.0.0.1:8848/nacos/v1/ns/instance/list

**Comment by elrondwong** [comment]
`/nacos/v1/core/cluster/nodes`
