### ISSUE TITLE
get nothing metadata when manually  online the service

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/nacos#403]
**Is your feature request related to a problem? Please describe.**
I try to do something when manually online the service,but i got the nothing metadata

**Describe the solution you'd like**
When manually change the service status(offline to online), get the metadata from EventListener

**Describe alternatives you've considered**

**Additional context**

**Comment by nkorange** [comment]
@liangyuanpeng This problem is already proposed in issue #362 . This bug will be fixed in Nacos 0.6.0, probably at this week.
