### ISSUE TITLE
nacos  for kubernetes  statefulset  -->  replicas: 5  集群就乱了

### ISSUE THREAD

**Issue by lyfcljw** [alibaba/nacos#4032]
在kubernetes 上安装 nacos  使用官方文档安装 3个节点是没问题的，但是当扩容到5个节点的时候整个集群就乱了，这个能帮解决一下吗

**Comment by KomachiSion** [comment]
错误信息是什么，现象是什么 版本是什么。

建议按照issue模版填写，否则什么情况只有您自己清楚。
