### ISSUE TITLE
There is an unnecessary scroll bar on the right side of the page

### ISSUE THREAD

**Issue by jzhishu** [alibaba/nacos#4036]
**Describe the bug**
login page:
![image](https://user-images.githubusercontent.com/39545185/96680280-caee1980-13a7-11eb-8213-a84a6e641fea.png)
index page:
![image](https://user-images.githubusercontent.com/39545185/96680380-fa9d2180-13a7-11eb-91b7-45254c6fb024.png)

**Desktop:**
 - OS: window 7 , window 10
 - Version: nacos-server 1.3.2
 - Broswer: chrome v86.0.4240.75
 - Broswer Size: 1920*1080

**Comment by jzhishu** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
Fixed in new version.
