### ISSUE TITLE
管理端中下线功能bug

### ISSUE THREAD

**Issue by Fengxq2014** [alibaba/nacos#4037]
**Describe the bug**
服务group非默认情况下，在管理端中点击下线，服务会被移动到DEFAULT_GROUP中状态为下线，非默认group中的服务依然在线

**Expected behavior**
服务group非默认时，可以正常下线

**How to Reproduce**
1. 设置服务group
2. 将服务注册到nacos中
3. 在管理端中点击下线
4. 服务依然在线，服务列表中会多一个默认group的服务，状态为下线

**Desktop (please complete the following information):**
 - OS: Centos
 - Version nacos-server 1.3.2
 - Module naming

**Additional context**

**Comment by horizonzy** [comment]
稳定复现吗？能提供一下截图吗

**Comment by Fengxq2014** [comment]
@horizonzy 稳定复现，你就按照我描述的试一下就可以了

**Comment by horizonzy** [comment]
额。我这边没法复现，显示是正常的。能提供一下你的操作步骤截图吗

**Comment by KomachiSion** [comment]
我记得这是1.2.1的一个bug，新版本已经修复了，清理一下浏览器缓存再试试 @Fengxq2014

**Comment by Fengxq2014** [comment]
@horizonzy @KomachiSion 不好意思，清缓存之后确实没问题了，之前版本是1.2.1，升级之后没清缓存

**Comment by KomachiSion** [comment]
duplicate #2609

**Comment by ChinaJeckXu** [comment]
老哥的问题，翻车了。哈哈哈，手动捂脸
