### ISSUE TITLE
startup  nacos occur error  in windows  os 

### ISSUE THREAD

**Issue by wenchaomartin** [alibaba/nacos#4038]
**Describe the bug**

 i get start from [quick-start.](https://nacos.io/en-us/docs/quick-start.html) in windows 10 os
 type the  startup.cmd ,and then  nacos start up in cluster mode ,of course , error come across

**Expected behavior**
startup in  standalone mode 
**Acutally behavior**
A clear and concise description of what you actually to happen.

startup in  cluster mode 

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

use cmd starup.cmd -m standalone instead of cmd starup.cmd in quick-start doc

**Comment by horizonzy** [comment]
you can add system param nacos.standalone=true to run nacos with standalone mode.

**Comment by horizonzy** [comment]
yes, it should be same just like Linux/Unix/Mac format.

**Comment by KomachiSion** [comment]
The document seems has some error, please use `startup.cmd -m standalone`
