### ISSUE TITLE
Use namespace of Registration Center

### ISSUE THREAD

**Issue by yunweidage** [alibaba/nacos#4039]
It is hoped that registration centers can be distinguished by namespace, and application services can be registered to different registries according to the namespace

Alibaba nacos team, work hard!

**Comment by KomachiSion** [comment]
Well, it will lead to the namespace is upper level than registration centers, it's not really reasonable.

The namespace is an inner concept of one registration center, It may not be to distinguish the registration centers.

So sorry.

**Comment by yunweidage** [comment]
> Well, it will lead to the namespace is upper level than registration centers, it's not really reasonable.
> 
> The namespace is an inner concept of one registration center, It may not be to distinguish the registration centers.
> 
> So sorry.

If it is used between multiple businesses, it is necessary to set up multiple sets of Nacos as the registration center and one set of Nacos as the configuration center, so the maintenance cost will be high,

Or through splitting, the registry and configuration center are divided into two projects, and then the registry is used only by using API or RPC method calls.
I hope to consider this in the future

Thank you very much

**Comment by KomachiSion** [comment]
For the first question, you can use same center and diff namespaces to diff businesses and apps. Only maintain one naming cluster and one config cluster.

For the second question, when Nacos was created, it was designed that the configuration and registration center can be combined or deployed separately. If split them back, It runs away from the design.

**Comment by yunweidage** [comment]
> For the first question, you can use same center and diff namespaces to diff businesses and apps. Only maintain one naming cluster and one config cluster.
> 
> For the second question, when Nacos was created, it was designed that the configuration and registration center can be combined or deployed separately. If split them back, It runs away from the design.

Thank you for your question and look forward to more perfect Nacos functions
