### ISSUE TITLE
How is the cluster pattern deployed？

### ISSUE THREAD

**Issue by 65725738** [alibaba/nacos#4046]
![Uploading 图片.png…]()
这个是文档的图片。这样的模式不就是多活吗？三台机器绑定到一个虚拟ip。
如果是集群模式应该不需要虚拟ip。直接连接三台其中一台。类似于zookeeper。

nocos到底是什么情况，这个集群模式应该如何部署？

This is a picture of the document.Isn't this a way to live more?Three machines are bound to a single virtual IP.
Virtual IP should not be required if it is in cluster mode.Directly connect one of the three.It's like a Zookeeper.
What exactly is nocos and how should this cluster pattern be deployed?

**Comment by 65725738** [comment]
图片不能展示呀。
集群模式部署

这个快速开始手册是帮忙您快速在你的电脑上，下载安装并使用Nacos，部署生产使用的集群模式。
集群部署架构图

因此开源的时候推荐用户把所有服务列表放到一个vip下面，然后挂到一个域名下面

http://ip1:port/openAPI 直连ip模式，机器挂则需要修改ip才可以使用。

http://VIP:port/openAPI 挂载VIP模式，直连vip即可，下面挂server真实ip，可读性不好。

http://nacos.com:port/openAPI 域名 + VIP模式，可读性好，而且换ip方便，推荐模式

就是这个最后一个推荐模式。

**Comment by KomachiSion** [comment]
挂vip的目的在于隐藏真实ip地址，是安全性的考虑， 你可以一个vip对应3个真实ip 也可以3个vip对应3个真实ip。

至于域名模式就更好解释了，ip可能会变，但是域名变化更少。

推荐域名 + VIP，是能够结合两种模式的优点的方式。当然缺点就是需要多维护一个域名解析和vip。

**Comment by KomachiSion** [comment]
你可以选择不用vip+域名，直接在客户端配置3个节点ip地址。

**Comment by 65725738** [comment]
意思我就跟配置zk一样。spring.cloud.nacos.config.server-addr=10.51.10.128:8848,10.51.10.129:8848,10.51.10.130:8848。这样的方式就可以用了吧。

如果用vip+域名。有个问题。想问一下。  
用域名的方式 客户端配置的是域名。 但是这个域名飘到哪一个ip是不一定的。如果飘到从机上。nacos也可以正常用吗？
集群模式nacos 主从。是都可以提交写请求吗？是不是和zk一样。从机器收到写请求，会转交给主。

但是如果这样。vip飘到从机器上。一般是不会变的。这样客户端上来的数据。每次都要转发一次呀。

**Comment by KomachiSion** [comment]
> 意思我就跟配置zk一样。spring.cloud.nacos.config.server-addr=10.51.10.128:8848,10.51.10.129:8848,10.51.10.130:8848。这样的方式就可以用了吧。

是的

>用域名的方式 客户端配置的是域名。 但是这个域名飘到哪一个ip是不一定的。如果飘到从机上。nacos也可以正常用吗？
集群模式nacos 主从。是都可以提交写请求吗？是不是和zk一样。从机器收到写请求，会转交给主。
>但是如果这样。vip飘到从机器上。一般是不会变的。这样客户端上来的数据。每次都要转发一次呀

是的

**Comment by 65725738** [comment]
三台机器 用的外网地址。
 cluster.conf 配置了 

XXX.XXX.134.62:8848
XXX.XXX.145.87:8848
XXX.XXX.147.224:8848

最新的nacos 1.3.2
三台机器 
一起动就自动增加一台。导致集群不能选举成功。什么情况？

启动后  cluster.conf变成了 。

192.168.0.170:8848
XXX.XXX.134.62:8848
XXX.XXX.145.87:8848
XXX.XXX.147.224:8848

192.168.0.51:8848
XXX.XXX.134.62:8848
XXX.XXX.145.87:8848
XXX.XXX.147.224:8848

192.168.0.130:8848
XXX.XXX.134.62:8848
XXX.XXX.145.87:8848
XXX.XXX.147.224:8848

每台机器配置文件多了一个ip。什么情况？


> 
> 
> > 意思我就跟配置zk一样。spring.cloud.nacos.config.server-addr=10.51.10.128:8848,10.51.10.129:8848,10.51.10.130:8848。这样的方式就可以用了吧。
> 
> 是的
> 
> > 用域名的方式 客户端配置的是域名。 但是这个域名飘到哪一个ip是不一定的。如果飘到从机上。nacos也可以正常用吗？
> > 集群模式nacos 主从。是都可以提交写请求吗？是不是和zk一样。从机器收到写请求，会转交给主。
> > 但是如果这样。vip飘到从机器上。一般是不会变的。这样客户端上来的数据。每次都要转发一次呀
> 
> 是的,根据协议可能不会转发，如果刚好请求的就是负责节点，就不需要转发

**Comment by 65725738** [comment]
多出来一台是 内网的ip地址。是自动加上去的。这个必须用内网吗？

**Comment by 65725738** [comment]
找到了 要配置一个参数nacos.inetutils.ip-address

**Comment by KomachiSion** [comment]
多出来的地址是nacos读取的自身ip地址，如果需要使用域名或者非本地地址，需要用-Dnacos.server.ip指定，或者用nacos.inetutils.ip-address参数指定，这样就不会找错了。
