### ISSUE TITLE
Application run failed.java.lang.NoClassDefFoundError: com/alibaba/nacos/common/util/SystemUtils

### ISSUE THREAD

**Issue by ChenJincheng-Gencent** [alibaba/nacos#4049]
spring boot version: 2.3.2.RELEASE
<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.3.RELEASE</spring-cloud-alibaba.version>
<nacos.client.version>1.3.3</nacos.client.version>
<nacos.config.version>0.8.0</nacos.config.version>

when I run an application, it run failed.And report "java.lang.NoClassDefFoundError: com/alibaba/nacos/common/util/SystemUtils".

why and how to resolve this question?

please help me, thanks.

**Comment by KomachiSion** [comment]
What's the `nacos.config.version`?

the error is can't find class `com/alibaba/nacos/common/util/SystemUtils`, which has been removed. 

So there are dependency conflict in your application.

**Comment by ChenJincheng-Gencent** [comment]
> What's the `nacos.config.version`?
> 
> the error is can't find class `com/alibaba/nacos/common/util/SystemUtils`, which has been removed.
> 
> So there are dependency conflict in your application.

My nacos.config dependency is 


<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-config</artifactId>
    <version>0.8.0</version>
</dependency>

How to resolve this conflict?

**Comment by KomachiSion** [comment]
nacos-config is too old version, which is not maintained, please use new version client to replace it.

**Comment by ChenJincheng-Gencent** [comment]
> nacos-config is too old version, which is not maintained, please use new version client to replace it.

I use new version, it works! 
 <groupId>com.alibaba.cloud</groupId>
 <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
 <version>2.2.3.RELEASE</version>

Thanks!

**Comment by Gosiy** [comment]
relative is:
spring boot version: 2.3.12.RELEASE
<spring-cloud.version>Hoxton.SR12</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.7.RELEASE</spring-cloud-alibaba.version>
nacos-config gav is:
<groupId>com.alibaba.cloud</groupId>
<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
<version>2.2.7.RELEASE</version>

when I run an application, it run failed.And report "java.lang.NoClassDefFoundError: com/alibaba/nacos/common/util/SystemUtils".

I've always followed the rules, but why ? Is it a bug ?

please help me, thanks.

**Comment by Gosiy** [comment]
relative is:
spring boot version: 2.3.12.RELEASE
<spring-cloud.version>Hoxton.SR12</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.7.RELEASE</spring-cloud-alibaba.version>
nacos-config gav is:
com.alibaba.cloud
spring-cloud-starter-alibaba-nacos-config
2.2.7.RELEASE

when I run an application, it run failed.And report "java.lang.NoClassDefFoundError: com/alibaba/nacos/common/util/SystemUtils".

I've always followed the rules, but why ? Is it a bug ?

please help me, thanks.
