### ISSUE TITLE
填写配置项时“标签”不生效，不知道是否时是使用方式不对

### ISSUE THREAD

**Issue by Yanwenjingcn** [alibaba/nacos#4050]
![image](https://user-images.githubusercontent.com/16257260/96951138-73be8500-151e-11eb-80eb-f727b0dabe23.png)
填写的标签不保存，每次填写了下次进入就没了。

四舍五入就是填了个寂寞

**Comment by KomachiSion** [comment]
which version of nacos you used?

**Comment by Yanwenjingcn** [comment]
> which version of nacos you used?

1.4.0，代码分支是develop

**Comment by shiyiyue1102** [comment]
> ![image](https://user-images.githubusercontent.com/16257260/96951138-73be8500-151e-11eb-80eb-f727b0dabe23.png)
> 填写的标签不保存，每次填写了下次进入就没了。
> 
> 四舍五入就是填了个寂寞

 你是指在创建一个配置的时候选了一个标签，然后在这个配置的编辑页面里发现标签消失了，还是说在创建其他配置的时候无法选择前一个配置里创建的标签？
