### ISSUE TITLE
nacos 控制台在服务列表中删除一个有实例的服务，直接会删除掉，心跳检查后，删掉的服务又会回来，但一直刷服务列表，这个服务一会儿有一会儿没有的

### ISSUE THREAD

**Issue by lsd2016** [alibaba/nacos#4055]
**Describe the bug**
nacos 控制台在服务列表中删除一个有实例的服务，直接会删除掉，心跳检查后，删掉的服务又会回来，但一直刷服务列表，这个服务一会儿有一会儿没有的，请问这是怎么回事儿？
之前出现过consumer调用provider时，提示没有服务提供者的问题（服务调不到），也是偶发现象，重启下consumer端，多数就好了，不行，再重启下provider consumer，也会好。

有上面问题后才想着怎么复现这问题，所以有删除服务的操作，就发现上面的问题了，但删除服务的方式用代码测试服务能调用到。

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by horizonzy** [comment]
服务通过什么方式注册的。dubbo吗？

**Comment by Maijh97** [comment]
@lsd2016 和 https://github.com/alibaba/nacos/issues/3781 问题类似，麻烦更新到1.4-BATE 版本试一下

**Comment by lsd2016** [comment]
> 用的dubbo什么版本。看下是否你是这个相同的问题。[apache/dubbo#5336](https://github.com/apache/dubbo/issues/5336)

我的dubbo是2.7.6
整体的spring cloud配置是下面的：
<spring-boot.version>2.2.5.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR3</spring-cloud.version>
<spring-cloud-alibaba-dependencies.version>2.2.1.RELEASE</spring-cloud-alibaba-dependencies.version>

**Comment by KomachiSion** [comment]
Any process for 1.4.0-BETA version.

**Comment by KomachiSion** [comment]
No response from author, we think this problem has been fixed. Close issue.
