### ISSUE TITLE
用的dubbo什么版本。看下是否你是这个相同的问题。https://github.com/apache/dubbo/issues/5336

### ISSUE THREAD

**Issue by lsd2016** [alibaba/nacos#4059]
用的dubbo什么版本。看下是否你是这个相同的问题。https://github.com/apache/dubbo/issues/5336

_Originally posted by @horizonzy in https://github.com/alibaba/nacos/issues/4055#issuecomment-716176544_

我的dubbo是2.7.6
整体的spring cloud配置是下面的：
<spring-boot.version>2.2.5.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR3</spring-cloud.version>
<spring-cloud-alibaba-dependencies.version>2.2.1.RELEASE</spring-cloud-alibaba-dependencies.version>

**Comment by KomachiSion** [comment]
Why open same issue？ Please discuss in original issue, Thanks.
