### ISSUE TITLE
[Discuss] The way to subscribe service change when data sync between nacos and zookeeper

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4062]
**Describe the problem**
For the prd env, if we use nacos, because the business is many, it hard to push business use nacos as registry by only one upgrade. We just push step by step. So it will exist nacos and zookeeper in a long time, the data sync is necessary for many users.
Now, nacosSync can sync data to each other. But when sync data from nacos to zookeeper. It need to config service which need to sync, because of client can't feel the service change. If business publish a new service and we didn't config the new service, the new service instances can't to sync, it's inconvenient for user. 
If we can feel service change automaticly, the new service instances can sync automaticly. 
So how to realize this feature.
1. Follow as instances subscribe, modify nacos-server and nacos-client to support long-polling request.
2. Modify nacos-client, add new api to request /service/list at fixed-time, according the all service's md5, if change, callback.
3. Modify nacos-sync, combine the nacos-client api, at a fixed-time to reuqest /service/list, if all service's md5 change, get the new service and subscribe it.

In my opinion, 3 is the easy way to realize it. @paderlol, how do you think it.

**Comment by KomachiSion** [comment]
Is it nacos-sync component feature？

**Comment by horizonzy** [comment]
Yes, but it depends the realization.
