### ISSUE TITLE
配置中心getconfigs延迟

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4063]
操作步骤:
1、通过nacos-spring-boot中的ConfigService.publishConfig发布数据。
2、通过nacos-spring-boot中的ConfigService.getConfig获取数据。

现象：
通过nacos-spring-boot中的ConfigService.getConfig获取最新配置数据时，会出现10s以内的随机延迟时间。

**Comment by KomachiSion** [comment]
@wanghuigithub which version you used? include client version and servers version.

**Comment by wanghuigithub** [comment]
@KomachiSion 
               <dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>nacos-config-spring-boot-starter</artifactId>
			<version>0.2.7</version>
		</dependency>

nacos-server 1.4.0

**Comment by horizonzy** [comment]
I will trace this issue.

**Comment by wanghuigithub** [comment]
查看client端代码时的一个疑问：
com/alibaba/nacos/client/config/NacosConfigService.java中的getConfigInner方法中的逻辑是优先使用本地配置。使用了
LocalConfigInfoProcessor.getFailover方法从本地磁盘获取数据。
但是，在LocalConfigInfoProcessor类中并没有找到向磁盘写数据的方法。所以，本地磁盘是一直没有数据的么？是直接请求的server端获取数据？如果这样的话感觉是不会有延迟的。

**Comment by horizonzy** [comment]
你的延迟指的是什么。是当时调用getConfig获取的是老的数据吗？大概等10秒过后再重新getConfig才获取到最新的数据吗。





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wanghuigithub <notifications@github.com&gt;
发送时间: 2020年10月27日 18:19
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 配置中心getconfigs延迟 (#4063)





 
查看client端代码时的一个疑问：
 com/alibaba/nacos/client/config/NacosConfigService.java中的getConfigInner方法中的逻辑是优先使用本地配置。使用了
 LocalConfigInfoProcessor.getFailover方法从本地磁盘获取数据。
 但是，在LocalConfigInfoProcessor类中并没有找到向磁盘写数据的方法。所以，本地磁盘是一直没有数据的么？是直接请求的server端获取数据？如果这样的话感觉是不会有延迟的。

**Comment by horizonzy** [comment]
你的发布数据的应用可能和获取数据的应用访问的nacos节点不一样。因为不同节点间数据需要同步的，只不过10秒钟太长了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wanghuigithub <notifications@github.com&gt;
发送时间: 2020年10月27日 18:19
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 配置中心getconfigs延迟 (#4063)





 
查看client端代码时的一个疑问：
 com/alibaba/nacos/client/config/NacosConfigService.java中的getConfigInner方法中的逻辑是优先使用本地配置。使用了
 LocalConfigInfoProcessor.getFailover方法从本地磁盘获取数据。
 但是，在LocalConfigInfoProcessor类中并没有找到向磁盘写数据的方法。所以，本地磁盘是一直没有数据的么？是直接请求的server端获取数据？如果这样的话感觉是不会有延迟的。

**Comment by wanghuigithub** [comment]
我使用的外部存储，MySQL

**Comment by horizonzy** [comment]
也存在同步的。mysql模式是通知变更，然后其他节点去mysql拉数据



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wanghuigithub <notifications@github.com&gt;
发送时间: 2020年10月27日 18:51
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 配置中心getconfigs延迟 (#4063)





 
我使用的外部存储，MySQL

**Comment by KomachiSion** [comment]
Maybe there are some delay for sync event or query data from db.

**Comment by horizonzy** [comment]
> Maybe there are some delay for sync event or query data from db.

According the log, the interval between publichConfig request and notifyConfigInfo request is 6s, I guess db process is slow, it lead publichConfig process too long

**Comment by KomachiSion** [comment]
I think it should change log level to debug to check whether DB write slow cause this problem. If so, need to enhance the SQLs or DB configuration

**Comment by horizonzy** [comment]
Finnaly, find the root reason. @wanghuigithub use  nacos-k8s build the cluster, but the cluster exist problem. the server node state all is SUSPICIOUS except selfnode each other, so when a server received publishConfig request, it just notify self, so other server can't sync new data.
In client, serverAddress config gateway to proxy nacos server, so when publish config, it's proxy to node1. And when getConfig, it's proxy to node2. because the ndoe can't sync, so getConfig's value is old. So he getConifg again, Finally, the getConfig request be proxy to the publishConfig server, the result is right, so he think getConfig delay.

**Comment by horizonzy** [comment]
I found that the cluster is not right, but I'm not good at nacos-k8s, anyone can help him to check it.

**Comment by wangweizZZ** [comment]
If it is a k8s problem, maybe can check coredns,make sure each node can access others by nacos-[nodeId].nacos-headless.[namespace].svc.cluster.local

**Comment by KomachiSion** [comment]
So the reason is that the network problem between pods so that the status of servers is `SUSPICIOUS`? In other words, these nodes can't build a cluster?

**Comment by wanghuigithub** [comment]
> So the reason is that the network problem between pods so that the status of servers is `SUSPICIOUS`? In other words, these nodes can't build a cluster?

yes, thanks all
