### ISSUE TITLE
历史版本回滚选择第一个版本时候会删除配置

### ISSUE THREAD

**Issue by javartisan** [alibaba/nacos#4064]
**Describe the bug**
历史版本配置回滚，当选择第一个版本时候会删除配置，选择非第一个版本可以正常工作。
跟踪前端请求发现当选择第一个版本配置时候会调用HTTP DELETED方法，非第一个版本是PSOT方法，这个应该是BUG的起因。
使用版本： nacos-server-1.3.1.zip
**Expected behavior**
选择第一个版本应该正确回滚到第一个版本

**Comment by KomachiSion** [comment]
首先不是bug，是你理解的不对，正确就是应该删除配置。

null -> v1 -> v2
      op1     op2

回滚历史时你选择了op1进行回滚，你想，回滚op1，那就是回到op1前的状态，那不就是不存在配置吗？

**Comment by gitisan** [comment]
> 首先不是bug，是你理解的不对，正确就是应该删除配置。
> 
> ```
> null -> v1 -> v2
>      op1   op2
> ```
> 
> 回滚历史时你选择了op1进行回滚，你想，回滚op1，那就是回到op1前的状态，那不就是不存在配置吗？

好吧，我理解选择op1是回滚到op1的状态。但是测试发现选择中间某一个版本也会触发删除操作，不知道是否理解错误

**Comment by javartisan** [comment]
> 首先不是bug，是你理解的不对，正确就是应该删除配置。
> 
> ```
> null -> v1 -> v2
>      op1   op2
> ```
> 
> 回滚历史时你选择了op1进行回滚，你想，回滚op1，那就是回到op1前的状态，那不就是不存在配置吗？

好吧，我理解选择op1是回滚到op1的状态。但是测试发现选择中间某一个版本也会触发删除操作，不知道是否理解错误
