### ISSUE TITLE
LoadBalancerClient cannot discover the newly registered service in time 

### ISSUE THREAD

**Issue by wmj765** [alibaba/nacos#4065]
**Describe the bug**

LoadBalancerClient cannot discover the newly registered service in time but can find after the few seconds.

**Expected behavior**
LoadBalancerClient find the newly registered service Immediately after service started

**Acutally behavior**
LoadBalancerClient find the service after a few seconds

**How to Reproduce**
1. two services total(service-a and service-b)
2. register service-a and service-b in nacos
3. restart service-b in nacos
4. start a request on the service-b and through the service-a , service-a calls service B through LoadBalancerClient

then it will return the error 503 Unable to find instance . but about 6-7 seconds later , the request will be accept.

**Desktop (please complete the following information):**
 - OS: [entos]
 - Version [nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [naming/config]
 - SDK [spring-cloud-alibaba-nacos]

**Comment by KomachiSion** [comment]
What's the LoadBalancerClient?

And for the delay, Please check naming-push.log in nacos server to check whether it push failed.

**Comment by wmj765** [comment]
LoadBalancerClient is org.springframework.cloud.client.loadbalancer  and no error log in naming-push.log.
It may be caused by the service status in nacos not being updated to the client in time , service-b is up in nacos but the client must wait a few seconds to perceive the status

**Comment by KomachiSion** [comment]
Please print some naming-push.log for your service. If push not failed, the time for delay should be less in two seconds.

If wait 6-7 seconds, it might be queried by client. Not push data.

**Comment by KomachiSion** [comment]
Any response or process?

**Comment by KomachiSion** [comment]
No response from author, We think the problem has fixed by users.
