### ISSUE TITLE
The nacos user is not locked after three consecutive login failures.

### ISSUE THREAD

**Issue by stephenxe** [alibaba/nacos#4070]
**Is your feature request related to a problem? Please describe.**

Locked upon multiple login failures will enhance system security.

**Describe the solution you'd like**

The system locks an account for a period of time after three consecutive login failures.

**Describe alternatives you've considered**

Do not expose the NACOS management page.

**Additional context**

None.

**Comment by KomachiSion** [comment]
This feature is a strong public security feature. for nacos, it should be a private net app console, so I don't think it's a high priority feature for community.

We will mark this issue to see whether community is interested for it.

**Comment by KomachiSion** [comment]
There is no body want to enhance this issue, and After 2.1 nacos support auth plugin, so I think this issue can be closed.
