### ISSUE TITLE
nacos 和 dubbo 整合,经常出现无法找到暴露的服务

### ISSUE THREAD

**Issue by w935903854** [alibaba/nacos#4072]
dubbo 服务采用 nacos 为注册中心,服务之间调用经常出现未发现暴露的服务,但是通过 nacos 控制台上面查看的话 服务都是正常启动的 ,
项目对应的版本
<spring.cloud.alibaba.version>2.2.0.RELEASE</spring.cloud.alibaba.version>
![image](https://user-images.githubusercontent.com/59118285/97252038-0bd0ad00-1844-11eb-9db2-9917fc3e0ba3.png)

**Comment by horizonzy** [comment]
你是用的哪个版本的dubbo

**Comment by zhouxufu** [comment]
这是springcloud alibaba的bug，并不是nacos的bug

**Comment by w935903854** [comment]
> 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。

服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务

**Comment by w935903854** [comment]
> 这是springcloud alibaba的bug，并不是nacos的bug
是 nacos 作为 dubbo 的注册中心才有这种问题啊,我不知道这样该怎么解决,挺麻烦的,项目最近要上生产了,这个问题偶尔在项目重启时出现.

**Comment by horizonzy** [comment]
> > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> 
> 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务

dubbo版本是多少。找不到提供端的服务是报NoProvider吗。consumer这边是一开始启动调用就报吗

**Comment by zrlw** [comment]
> > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> 
> 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务

你刷新一下nacos注册中心的控制台页面，看看服务列表里的这个provider是不是一会儿有，一会儿又没有。

**Comment by KomachiSion** [comment]
升级到1.4.0-BETA的服务端再试一下看看，可能是个旧版本的bug。

**Comment by w935903854** [comment]
> > > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> > 
> > 
> > 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务
> 
> dubbo版本是多少。找不到提供端的服务是报NoProvider吗。consumer这边是一开始启动调用就报吗

对的  主要是刚启动的时候出现这个问题

**Comment by w935903854** [comment]
> > > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> > 
> > 
> > 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务
> 
> 你刷新一下nacos注册中心的控制台页面，看看服务列表里的这个provider是不是一会儿有，一会儿又没有。

不是 一直都有  一般都只有多次重启服务  才能调通   具体原因目前不得而知

**Comment by w935903854** [comment]
> > > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> > 
> > 
> > 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务
> 
> dubbo版本是多少。找不到提供端的服务是报NoProvider吗。consumer这边是一开始启动调用就报吗

**Comment by w935903854** [comment]
> 升级到1.4.0-BETA的服务端再试一下看看，可能是个旧版本的bug。

指的是 nacos 还是 dubbo

**Comment by KomachiSion** [comment]
> > > > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> > > 
> > > 
> > > 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务
> > 
> > 
> > dubbo版本是多少。找不到提供端的服务是报NoProvider吗。consumer这边是一开始启动调用就报吗
> 
> 对的 主要是刚启动的时候出现这个问题

刚启动出现这个问题可能是获取服务列表有一点延迟，需要查一下naming-push.log和客户端的naming.log 日志 看下是什么时候收到的服务列表。

**Comment by horizonzy** [comment]
> > > > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> > > 
> > > 
> > > 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务
> > 
> > 
> > 你刷新一下nacos注册中心的控制台页面，看看服务列表里的这个provider是不是一会儿有，一会儿又没有。
> 
> 不是 一直都有 一般都只有多次重启服务 才能调通 具体原因目前不得而知

重启多次是重启consumer还是provider

**Comment by w935903854** [comment]
> > > > > 你是用的哪个版本的dubbo。我看你这个报错是consumer请求me.ddkj.inlove.rpc.user.api.IUserRpcService。但是你的provider没有暴露这个服务me.ddkj.inlove.rpc.user.api.IUserRpcService，所以在provider端报了这个错误。
> > > > 
> > > > 
> > > > 服务都已经正常暴露了,并且在 nacos 控制台中也是也可以看到的,但是不知道为什么消费端一直找不到这个提供端的服务
> > > 
> > > 
> > > 你刷新一下nacos注册中心的控制台页面，看看服务列表里的这个provider是不是一会儿有，一会儿又没有。
> > 
> > 
> > 不是 一直都有 一般都只有多次重启服务 才能调通 具体原因目前不得而知
> 
> 重启多次是重启consumer还是provider

两边都重启

**Comment by horizonzy** [comment]
我推测你的问题应该是consumer没有正确感知到nacos的节点变化。你这个消费者对应的服务提供者ip已经变了，另一个提供者把你的原来提供者的ip占了（k8s环境下ip漂的）。但是你的consumer没有感知到nacos节点变化，还是按照原来的ip去进行rpc,虽然rpc能够正常发起，但是会报错，提示`Not Found exported service me.ddkj.inlove.rpc.user.api.IUserRpcService`，因为现在的提供者没有暴露`me.ddkj.inlove.rpc.user.api.IUserRpcService`这个服务。
这个问题我推测是Rpc框架的问题，能看一下你的dubbo版本是多少吗，我记得之前dubbo是有这个问题，nacosRegistry可能无法感知到provider节点变化

**Comment by w935903854** [comment]
spring-cloud-alibaba-dubbo  2.2.0.RELEASE

**Comment by horizonzy** [comment]
> spring-cloud-alibaba-dubbo 2.2.0.RELEASE

这个整合的dubbo版本是多少，你看下maven依赖呢，org.apache.dubbo这个依赖的version

**Comment by zhouxufu** [comment]
看下这个  是不是同一种情况 
https://github.com/alibaba/spring-cloud-alibaba/issues/1360

**Comment by w935903854** [comment]
> > spring-cloud-alibaba-dubbo 2.2.0.RELEASE
> 
> 这个整合的dubbo版本是多少，你看下maven依赖呢，org.apache.dubbo的version

2.7.4.1

**Comment by horizonzy** [comment]
https://github.com/apache/dubbo/issues/5336，找下高版本的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: w935903854 <notifications@github.com&gt;
发送时间: 2020年10月29日 19:42
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] nacos 和 dubbo 整合,经常出现无法找到暴露的服务 (#4072)





   
spring-cloud-alibaba-dubbo 2.2.0.RELEASE
  
这个整合的dubbo版本是多少，你看下maven依赖呢，org.apache.dubbo的version
  
2.7.4.1

**Comment by KomachiSion** [comment]
2.7.4.1dubbo有一个无法感知nacos节点，https://github.com/apache/dubbo/issues/4793
我记得2.7.6修复了

**Comment by webeasymail** [comment]
dubbo 2.7.8 依然存在这个问题

**Comment by huangsanyeah** [comment]
I also encountered this problem. At first I thought that the interface was busy, so I performed a stress test, but it did not reproduce. Later, I upgraded the nacos version to solve the problem
before upgrade：nacos-client 1.3.1 dubbo-2.7.8
after upgrade：nacos-client 1.4.2 dubbo-2.7.8

hope useful fo you!

升级下nacos-client版本 我的问题是这样解决的 1.3.1 to 1.4.2

**Comment by huangsanyeah** [comment]
> 升级到1.4.0-BETA的服务端再试一下看看，可能是个旧版本的bug。



> dubbo 2.7.8 依然存在这个问题

看我的回复 升级下nacos-client版本试试呢

**Comment by huangsanyeah** [comment]
> > 升级到1.4.0-BETA的服务端再试一下看看，可能是个旧版本的bug。
> 
> 指的是 nacos 还是 dubbo
nacos-client1.3.1升级到1.4.2解决此问题 但是看了nacos的版本更新记录 并没有提示修复了这个Bug

**Comment by xieweidong** [comment]
dubbo 2.7.15 nacos-client 2.0.4  就是如果我重启了consumer的服务，没有重启provider的服务，报连接超时，找不到服务

**Comment by juntao224** [comment]
nacos client1.4.6,dubbo2.7.22仍然有该问题，我们部署的情况是两套服务（gray和prod）部署在同一个命名空间，同一分组，通过version进行隔离，两套都启动时会出现需要调用gray但是返回的服务全是prod,或者调用prod但是返回的服务全是gray，而且不是必现，时好时坏。停掉任意一套环境时另一套均正常。
