### ISSUE TITLE
配置中心成为leader的节点开始爆刷nacos.log日志

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#4075]
**Describe the bug**
nacos配置中心有3个节点，把原来的节点A停了之后进行了重启，期间节点C成为了leader，然后节点C的nacos.log就开始暴增模式，一刻不停地重复写下列日志：
时间戳 INFO listen config id: 配置项数据（dataid，group等内容）
时间戳 INFO listen config id 2: 重复上一行的配置项数据

**Expected behavior**
正常。

**Acutally behavior**
变态。

**How to Reproduce**
不知道怎么才能重现，之前没有遇到过。

**Desktop (please complete the following information):**
 - OS: Centos
 - Version nacos-server 1.2.1, nacos-client 1.2.1

**Comment by horizonzy** [comment]
这个是客户端的对服务端配置进行监听。客户端的config模块在初始化的时候会随机负载打散请求。config客户端模块的逻辑是，如果上一次请求的服务是ok的，会复用上一次的节点进行请求。你当时其他节点挂了，只有C了，请求都到C了。有因为有复用上次节点的逻辑，所以请求不会重新分摊到其他节点。

**Comment by horizonzy** [comment]
> **Describe the bug**
> nacos配置中心有3个节点，把原来的节点A停了之后进行了重启，期间节点C成为了leader，然后节点C的nacos.log就开始暴增模式，一刻不停地重复写下列日志：
> 时间戳 INFO listen config id: 配置项数据（dataid，group等内容）
> 时间戳 INFO listen config id 2: 重复上一行的配置项数据
> 
> **Expected behavior**
> 正常。
> 
> **Acutally behavior**
> 变态。
> 
> **How to Reproduce**
> Steps to reproduce the behavior:
> 不知道怎么才能重现，之前没有遇到过。
> 
> **Desktop (please complete the following information):**
> 
> * OS: Centos
> * Version nacos-server 1.2.1, nacos-client 1.2.1

这块我们看一下要考虑到发生这种情况下客户端的LB策略。

**Comment by zrlw** [comment]
此外诡异的是其中有一组不停刷的 listen config id和 listen config id 2日志里面有一个配置项现在查配置中心已经查不到了，还在不停地刷它的dataid，groupid和namespace id（md5没有了）

**Comment by zrlw** [comment]
我大概明白什么意思了，已经恢复正常的注册中心节点变成了follower，闲死了也没有客户端去访问，而leader被固执的客户端快要打爆了。

**Comment by zrlw** [comment]
只能重启一下各个客户端，重新平衡一下请求了么？

**Comment by horizonzy** [comment]
> 只能重启一下各个客户端，重新平衡一下请求了么？

嗯，重启一下客户端打散请求吧
