### ISSUE TITLE
java11，nacos1.3.2启动失败，报虚拟机不能创建

### ISSUE THREAD

**Issue by weiboboCN** [alibaba/nacos#4079]
![image](https://user-images.githubusercontent.com/23450893/97415594-69e2ba80-1940-11eb-8c16-e67ae077137d.png)
java11，nacos1.3.2启动失败，报虚拟机不能创建

**Comment by KomachiSion** [comment]
报错是 -Djava.ext.dirs jdk11不支持了，先自行修改下。

**Comment by weiboboCN** [comment]
谢谢，解决了(*^_^*)
