### ISSUE TITLE
Can not get hosts from nacos server. serviceId

### ISSUE THREAD

**Issue by yiming33** [alibaba/nacos#408]
使用spring-cloud-gateway  已经和nacos整合
目前启动了一个student服务、consumer服务和一个gateway服务
![image](https://user-images.githubusercontent.com/19584310/49630796-a34b6d80-fa2a-11e8-8d01-8de0123354d4.png)
在调用gateway的时候  有时候会出现找不到服务的报错
http://localhost:8090/student/v1/students/142 (8090是gateway服务的端口)

![image](https://user-images.githubusercontent.com/19584310/49630822-be1de200-fa2a-11e8-939f-6cb42470fb6d.png)
这里提示无法从nacos获取到student的host
但实际上gateway已经注册到nacos中了 并且健康运行
所以目前不知道为什么会提示如上图的错误
然后我重启了student服务
仍然报这个错误
接着我重启了gateway服务 再次调用那个url
![image](https://user-images.githubusercontent.com/19584310/49631157-ece88800-fa2b-11e8-9b14-75960fd066f3.png)
这次提示consumer服务获取不到  这我就纳闷了  我这条链路应该是从gateway代理到student  应该不会经过consumer 怎么会报这种错 但没办法 接着我把consumer服务重启了
没有任何效果 仍然提示Can not get hosts from nacos server. serviceId: consumer
这个时候我再次重启 gateway服务
![image](https://user-images.githubusercontent.com/19584310/49631321-74ce9200-fa2c-11e8-8df7-f1bd3398812e.png)
这次报错是无法获取gateway服务的host了。。。。emmm 
那我再重启一次gateway服务
![image](https://user-images.githubusercontent.com/19584310/49631359-a7788a80-fa2c-11e8-95ce-9f833a7093f8.png)
这次居然就成功了！  没有再报类似上图的问题  
几乎每次都要经历如上的步骤 重启三次gateway 我才能正常使用spring-cloud-gateway
我觉得这个情况太诡异了  我们已经准备将nacos投入到生产环境中  但是目前和spring-cloud-gateway的结合实在太不稳定了  在webflux中的webclient使用nacos  是完全没问题 没有出现过这样的问题 唯独gateway会有这样的问题  我觉得这个问题很奇葩  实在找不到原因了   如果要将nacos投入到生产环境上 必须要保证nacos功能基本的稳定性 非常看好阿里的开源技术 希望nacos的同学能给予一些帮助

以下是我spring-cloud-gateway的相关配置：
![image](https://user-images.githubusercontent.com/19584310/49631521-4ef5bd00-fa2d-11e8-80c5-38e4ffc05fd6.png)
![image](https://user-images.githubusercontent.com/19584310/49631545-62088d00-fa2d-11e8-9ae6-0822eeef1cb2.png)
![image](https://user-images.githubusercontent.com/19584310/49631554-6af95e80-fa2d-11e8-9b0e-c8a6194979c3.png)

**Comment by pguo65535** [comment]
不能更赞了

**Comment by IronCity** [comment]
目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗

**Comment by yiming33** [comment]
> 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
我目前是打算使用spring-cloud-gateway  毕竟spring的东西社区活跃度高 踩坑容易解决  我看了很多自制的api-gateway  github上能搜出来不少 但是一旦作者停止维护了 就只能靠自己维护  所以还是保守一点

**Comment by yiming33** [comment]
> 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗

目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少  但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃  踩坑也容易解决一些

**Comment by IronCity** [comment]
> > 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
> 
> 目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少 但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃 踩坑也容易解决一些

好的，我去看看spring-cloud-gateway是否能够较好的支持dubbo。

**Comment by yiming33** [comment]
> > > 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
> > 
> > 
> > 目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少 但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃 踩坑也容易解决一些
> 
> 好的，我去看看spring-cloud-gateway是否能够较好的支持dubbo。

dubbo只需要在内部服务和服务之间通讯使用就行了  gateway代理到服务的过程中 走http就可以了  没有必要gateway代理到服务也走rpc   rpc也不支持多媒体文件  网关到服务层应该是http的

**Comment by IronCity** [comment]
> > > > 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
> > > 
> > > 
> > > 目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少 但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃 踩坑也容易解决一些
> > 
> > 
> > 好的，我去看看spring-cloud-gateway是否能够较好的支持dubbo。
> 
> dubbo只需要在内部服务和服务之间通讯使用就行了 gateway代理到服务的过程中 走http就可以了 没有必要gateway代理到服务也走rpc rpc也不支持多媒体文件 网关到服务层应该是http的

对于（gateway代理到服务也走rpc）不是很理解，是指我后端服务暴露了HTTP给网关转发吗？我理解Web页面走HTTP到网关，网关 泛化（dubbo&HSF） 往后请求 通过注册中心（nacos）去后端服务获取数据

**Comment by yiming33** [comment]
> > > > > 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
> > > > 
> > > > 
> > > > 目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少 但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃 踩坑也容易解决一些
> > > 
> > > 
> > > 好的，我去看看spring-cloud-gateway是否能够较好的支持dubbo。
> > 
> > 
> > dubbo只需要在内部服务和服务之间通讯使用就行了 gateway代理到服务的过程中 走http就可以了 没有必要gateway代理到服务也走rpc rpc也不支持多媒体文件 网关到服务层应该是http的
> 
> 对于（gateway代理到服务也走rpc）不是很理解，是指我后端服务暴露了HTTP给网关转发吗？我理解Web页面走HTTP到网关，网关 泛化（dubbo&HSF） 往后请求 通过注册中心（nacos）去后端服务获取数据

嗯嗯 跟你是一个意思 之前nacos社区群里有个同学发了个自己写的网关  支持dubbo 但是我没太留意 就略过了  我看看还有记录没

**Comment by IronCity** [comment]
> > > > > > 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
> > > > > 
> > > > > 
> > > > > 目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少 但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃 踩坑也容易解决一些
> > > > 
> > > > 
> > > > 好的，我去看看spring-cloud-gateway是否能够较好的支持dubbo。
> > > 
> > > 
> > > dubbo只需要在内部服务和服务之间通讯使用就行了 gateway代理到服务的过程中 走http就可以了 没有必要gateway代理到服务也走rpc rpc也不支持多媒体文件 网关到服务层应该是http的
> > 
> > 
> > 对于（gateway代理到服务也走rpc）不是很理解，是指我后端服务暴露了HTTP给网关转发吗？我理解Web页面走HTTP到网关，网关 泛化（dubbo&HSF） 往后请求 通过注册中心（nacos）去后端服务获取数据
> 
> 嗯嗯 跟你是一个意思 之前nacos社区群里有个同学发了个自己写的网关 支持dubbo 但是我没太留意 就略过了 我看看还有记录没

多谢啊。哥们我加你钉钉好友了，批准下

**Comment by yiming33** [comment]
> > > > > > > 目前正在考虑nacos+dubbo 上生产环境，哥们有好的 API-GATEWAY推荐吗
> > > > > > 
> > > > > > 
> > > > > > 目前是打算使用spring-cloud-gateway 也看过很多其他自制的api gateway ,github上能搜出来不少 但是作者一旦停止维护 就只能靠自己维护了 所以还是选择spring的产品 毕竟社区活跃 踩坑也容易解决一些
> > > > > 
> > > > > 
> > > > > 好的，我去看看spring-cloud-gateway是否能够较好的支持dubbo。
> > > > 
> > > > 
> > > > dubbo只需要在内部服务和服务之间通讯使用就行了 gateway代理到服务的过程中 走http就可以了 没有必要gateway代理到服务也走rpc rpc也不支持多媒体文件 网关到服务层应该是http的
> > > 
> > > 
> > > 对于（gateway代理到服务也走rpc）不是很理解，是指我后端服务暴露了HTTP给网关转发吗？我理解Web页面走HTTP到网关，网关 泛化（dubbo&HSF） 往后请求 通过注册中心（nacos）去后端服务获取数据
> > 
> > 
> > 嗯嗯 跟你是一个意思 之前nacos社区群里有个同学发了个自己写的网关 支持dubbo 但是我没太留意 就略过了 我看看还有记录没
> 
> 多谢啊。哥们我加你钉钉好友了，批准下

刚才更新了下之前的回复

**Comment by liangyuanpeng** [comment]
@IronCity @yiming33  [Soul](https://github.com/Dromara/soul) 吗 社区群看到的

**Comment by chengdongwei** [comment]
目前可以指定serviceId可以访问具体地址，怎么实现根据clusterName访问呢

**Comment by IronCity** [comment]
> @IronCity @yiming33 [Soul](https://github.com/Dromara/soul) 吗 社区群看到的

Soul我也看到了，靠不靠谱？现在还在纠结是否自己造轮子

**Comment by nkorange** [comment]
@yiming33 @IronCity @liangyuanpeng 你们的问题是否解决了？

**Comment by SoftwareKing** [comment]
@yiming33 你问题目前是否解决了，没有解决的话，可以留个github仓库地址，Spring Cloud中国社区准备推出Open Gateway-代号Janus，项目参与人员来自饿了么，唯品会等具有多年网关生产经验的人开发。

**Comment by nkorange** [comment]
关闭不活跃issue，如果有需要请重新打开

**Comment by luohaoGit** [comment]
@yiming33 你好，请问你最后怎么解决的

**Comment by sagahl** [comment]
也遇到这个问题，我这里是因为这一行代码：metadata.putAll(instance.getMetadata());报错，设置meta就ok了，希望对大家有帮助。

**Comment by chenhao1893** [comment]
consumer如果复写了CommandLineRunner，在getMetadata()方法中添加代码：
Map<String, String> metadata = new HashMap<>();
metadata.put("secure", "true");
return metadata;
即可解决，亲测有效。
