### ISSUE TITLE
我看源码的时候看到getConfig获取配置的疑问

### ISSUE THREAD

**Issue by luoqiqin** [alibaba/nacos#4081]
我看源码的时候看到getConfig获取配置的时候，会先从本地文件获取，如果获取不到再通过openapi获取，然后写入本地文件，但是我调试代码的时候发现获取本地文件和写本地文件不一致，导致一直获取不到本地文件

**Comment by horizonzy** [comment]
failover -> openApi -> snapshot.
failover是用户自己写入的，获取完openApi会把数据写到snapshot。

**Comment by KomachiSion** [comment]
首先获取的failover是用户用于容灾的救急设置（比如nacos连接不上获取不到新配置），需要用户自己写入创建并写入该文件。当有该文件时优先使用。

一般情况下不会用到failover。 通过openAPI从nacos获取，然后将这份配置持久化到本地快照备查，快照文件不是容灾文件，所以写入的文件和启动初始查询的文件不同。
