### ISSUE TITLE
【nacos config】how to use type = ConfigType.JSON

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#4083]
我现在引用的是nacos-config-spring-boot-starter-0.2.7

我在nacos客户端上配置了一个json格式的配置，如下图
![image](https://user-images.githubusercontent.com/62423061/97520037-4ddd2880-19d5-11eb-9abc-3e907b3e835d.png)

我的代码
![image](https://user-images.githubusercontent.com/62423061/97520076-5df50800-19d5-11eb-8a8b-b057b690650f.png)

现象：启动时报错 java.lang.NoClassDefFoundError: com/alibaba/nacos/client/utils/StringUtils
![image](https://user-images.githubusercontent.com/62423061/97520134-7cf39a00-19d5-11eb-9035-4d47044b8bc2.png)

另外我用@NacosValue(value = "${name:jose}", autoRefreshed = true)这样接收数据正确吗？

**Comment by horizonzy** [comment]
这个应该是spring-nacos-project那边的问题
1.你配置的方式没有问题。
2.这个报错应该是nacos-config-spring-boot-starter-0.2.7中使用的StringUtils工具类是老版本的nacos-client中的。后面新版本已经把StringUtils换位置了，你可以尝试降低nacos-client的版本来解决。不确定nacos-config-spring-boot的高版本有没有改变对StringUtils的使用方式

**Comment by saiyujs** [comment]
之前为了排除fastjson，改用jackson，专门把nacos-client升到了1.3  .......

**Comment by horizonzy** [comment]
用下最近的starter呢。



发自我的iPhone


------------------ Original ------------------

**Comment by KomachiSion** [comment]
那可以关注一下nacos-spring社区，当它们发新版本的时候切换就可以了。

**Comment by horizonzy** [comment]
> 之前为了排除fastjson，改用jackson，专门把nacos-client升到了1.3 .......

`nacos-config-spring-boot-starter-0.2.7` 依赖 `spring-nacos-context-0.3.6`, 现在`spring-nacos-context-1.0.0` 已经移除了对`com.alibaba.nacos.client.utils.StringUtils`的使用。 
等下一次`nacos-config-spring-boot-starter`的发版应该就可以了，如果不急的话，可以先用老的nacos-client跑着

**Comment by saiyujs** [comment]
@qiaoweiqls 个人习惯，还是用properties，然后配的是json字符串，后台自己再转，哈哈哈
