### ISSUE TITLE
跨域不需登录权限可发布配置问题

### ISSUE THREAD

**Issue by gaoxiang9457** [alibaba/nacos#4084]
重现步骤:
1.部署两套相同环境A、B,使用相同业务数据，两套环境只有域名不同
2.A环境登录到发布配置页，B环境不登录
3.浏览器手动修改A域名为B域名，点击发布配置，B系统配置被成功发布
问题：
B环境未登录但可以发布配置

**Comment by horizonzy** [comment]
> 重现步骤:
> 1.部署两套相同环境A、B,使用相同业务数据，两套环境只有域名不同
> 2.A环境登录到发布配置页，B环境不登录
> 3.浏览器手动修改A域名为B域名，点击发布配置，B系统配置被成功发布
> 问题：
> B环境未登录但可以发布配置

两套环境用的同一个数据库吗？在服务端有没有开启权限

**Comment by KomachiSion** [comment]
两套环境的用户名密码均相同吗？
如果相同，那的确存在这个问题，nacos目前用的是Authentication方式，基于accessToken。
两套环境的用户名密码相同，在同等有效期内，accessToken的认证信息是一致的，除非两套环境的密码不同或者用户不存在。
