### ISSUE TITLE
配置记录的操作人为空

### ISSUE THREAD

**Issue by CuberWRG** [alibaba/nacos#4086]
**Describe the bug**
In Background management system, after creating a new configuration, the operator display is empty
在Nacos后台管理，创建新配置后，操作人显示为空

**Expected behavior**
The current account name should be recorded.
当前账号名字应当被记录

**How to Reproduce**
version:   1.4.0-beat
[https://img-blog.csdnimg.cn/20201029231242390.png](url)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]  CentOS Linux release 7.8.2003 (Core)
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]  nacos 1.4.0-beat
 - Module [e.g. naming/config]   config & console
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo] none.  Background management system

**Additional context**
Fixed and ready to submit PR.
已修复并准备提交PR.

**Comment by KomachiSion** [comment]
麻烦开启权限功能后再试。

**Comment by KomachiSion** [comment]
see #2792

**Comment by CuberWRG** [comment]
> see #2792

您好，使用的是nacos账号，在权限管理为其配置为rw权限，新增修改、新增配置操作后，在历史版本中，操作人仍为空

**Comment by CuberWRG** [comment]
> see #2792
[](https://img-blog.csdnimg.cn/20201030103446523.png)

**Comment by CuberWRG** [comment]
我认为，出现该问题的代码为：
    com.alibaba.nacos.config.server.utils.RequestUtil 的第76行:
            Object userObj = request.getAttribute(NACOS_USER_KEY);
    com.alibaba.nacos.console.security.nacos.NacosAuthManager 的第94行:
            req.setAttribute(RequestUtil.NACOS_USER_KEY, user);

目前对于获取用户名的方式是：登录时req.setAttribute, 需要用到username时从req中getAttribute，但是这样获取到的username肯定是空的。

**Comment by CuberWRG** [comment]
> 我认为，引起该问题的代码为：
> com.alibaba.nacos.config.server.utils.RequestUtil 的第76行:
> Object userObj = request.getAttribute(NACOS_USER_KEY);
> com.alibaba.nacos.console.security.nacos.NacosAuthManager 的第94行:
> req.setAttribute(RequestUtil.NACOS_USER_KEY, user);
> 
> 目前对于获取用户名的方式是：登录时req.setAttribute, 需要用到username时从req中getAttribute，但是这样获取到的username肯定是空的。

**Comment by KomachiSion** [comment]
目前的设计是，如果不打开权限功能，我们认为用户并不关心操作人信息，只有当打开权限功能时，我们会从accessToken中解析出实际的操作人，并透传到后续操作中。

这么设计的原因主要是操作并不一定来自于web端，有可能来自于openApi和SDK，他们可能不想web端一样必须要登录，因此你的那个实现可能获取不到user。

关于你的问题，如果您发现开启权限后，操作人还是无法被记录，请重新打开issue并且详细复现步骤

**Comment by CuberWRG** [comment]
> 目前的设计是，如果不打开权限功能，我们认为用户并不关心操作人信息，只有当打开权限功能时，我们会从accessToken中解析出实际的操作人，并透传到后续操作中。
> 
> 这么设计的原因主要是操作并不一定来自于web端，有可能来自于openApi和SDK，他们可能不想web端一样必须要登录，因此你的那个实现可能获取不到user。
> 
> 关于你的问题，如果您发现开启权限后，操作人还是无法被记录，请重新打开issue并且详细复现步骤

好的谢谢，关于这部分我已经理解了，谢谢您的讲解与回复
