### ISSUE TITLE
Configuration file changes do not take effect

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#4090]
**Describe the bug**

Modify the conf/application. The properties configuration file, after the restart Nacos, there are some configuration information cannot take effect

**Expected behavior**

Nacos should be able to read configuration information when Springboot starts loading user classes

**Acutally behavior**

Nacos can't be able to read configuration information when Springboot starts loading user classes

**How to Reproduce**
1. stop nacos
2. modify conf/application.properties =>nacos.inetutils.ip-address
3. start nacos with debug mode

**Desktop (please complete the following information):**
 - OS: Mac os
 - Version nacos1.3.2 or nacos1.4.0-beta
 - Module sys

**Additional context**

none

**Comment by KomachiSion** [comment]
@chuntaojun Please add some description in issue template

**Comment by chuntaojun** [comment]
> @chuntaojun Please add some description in issue template

already fix
