### ISSUE TITLE
配置文件克隆无效

### ISSUE THREAD

**Issue by robin-ming** [alibaba/nacos#4094]
从一个命名空间克隆配置文件到另一个,存在相同配置，仍然提示克隆成功，但目标配置文件没有改变，版本历史无记录
若选择覆盖也是相同情况

 
 
 
 版本1.3.2

**Comment by KomachiSion** [comment]
@robin-ming 麻烦按照issue模版详细填写一下复现步骤。

**Comment by KomachiSion** [comment]
I test with version nacos-1.4.0 in console.nacos.io. Can reproduce the problem.

Due to author has no response, and current information is not enough to reproduce problem. Close issue
