### ISSUE TITLE
依赖websocket的时候报错了

### ISSUE THREAD

**Issue by zhangran2616** [alibaba/nacos#4096]
![image](https://user-images.githubusercontent.com/6472032/97656095-96621800-1aa1-11eb-8184-5b2276695d04.png)

使用springcloud+nacos注册中心 依赖websocket的时候报错了。请问下这个怎么解决？

**Comment by KomachiSion** [comment]
应该是引入依赖的版本冲突了，去掉一个旧版本就好了

**Comment by zhangran2616** [comment]
> 应该是引入依赖的版本冲突了，去掉一个旧版本就好了

![image](https://user-images.githubusercontent.com/6472032/97692057-35a30180-1ada-11eb-8537-c37d9dfc0839.png)
![image](https://user-images.githubusercontent.com/6472032/97692101-4b182b80-1ada-11eb-9e8a-a65bfb74b30f.png)

请问下，我刚才查看了版本依赖 没有发现其他版本的websocket和nacos，不知道你说的哪一个冲突了？

**Comment by KomachiSion** [comment]
spring提示这个类需要一个单独的bean实现， 但是发现了2个，你查一下下面那2个bean分别来自哪个jar包，去掉一个就好了。

**Comment by luckywur** [comment]
同样的问题

**Comment by HSPCode** [comment]
您好，
一、问题描述：nacos作为注册中心，项目同时引入websocket和nacos-discovery依赖，NacosWatch获取错误的taskScheduler（websocket的NoOpScheduler）导致项目无法启动。
![image](https://user-images.githubusercontent.com/47849395/105978391-71476a80-60cd-11eb-8143-79db8a6399b3.png)
二、项目版本依赖：
（1）springboot版本2.0.3.RELEASE
（2）spring-boot-starter-websocket版本是2.0.3.RELEASE
（3）spring-cloud-starter-alibaba-nacos-discovery版本是2.0.3.RELEASE
三、问题原因：NacosWatch的taskScheduler实现类获取的是org.springframework.web.socket.config.annotation.WebSocketConfigurationSupport的内部类NoOpScheduler，这个类的scheduleWithFixedDelay(Runnable task, long delay)方法是抛出异常，导致项目启动不了。
![image](https://user-images.githubusercontent.com/47849395/105978867-f92d7480-60cd-11eb-8b51-d1d45bcd6127.png)
![image](https://user-images.githubusercontent.com/47849395/105977884-dea6cb80-60cc-11eb-8f40-6de47ac5ac86.png)
具体获取：
org.springframework.beans.factory.support.DefaultListableBeanFactory类通过classType获取
![image](https://user-images.githubusercontent.com/47849395/105980225-8e7d3880-60cf-11eb-8e88-32d862663a0a.png)

四、效果对比：
（1）项目去掉spring-boot-starter-websocket依赖，启动成功
（2）通过@Primary指定，启动成功
![image](https://user-images.githubusercontent.com/47849395/105980795-41e62d00-60d0-11eb-9210-281019a6a638.png)
（3）其他项目，未引入spring-boot-starter-websocket依赖，启动成功
五、咨询目的：这个冲突算是nacos-discovery兼容问题；还是说是个人的使用不当导致的，正确用法就是四.(2)？

**Comment by hu1632564504** [comment]
![image](https://user-images.githubusercontent.com/92993421/181813000-2086aaa3-5886-4313-9878-b1a2a36d38a6.png)
在idea里面启动可以启动成功，但是一到tomcat上面就报这个错误怎么处理
