### ISSUE TITLE
dubbo整合nacos时 nacos注册中心分组无法指定

### ISSUE THREAD

**Issue by cuoduidui** [alibaba/nacos#4097]
![image](https://user-images.githubusercontent.com/20532708/97656633-d675ca80-1aa2-11eb-9d0b-a23eab8878b5.png)

dubbo用nacos做注册中心时  分组无法指定  跟踪代码发现
![image](https://user-images.githubusercontent.com/20532708/97656712-0cb34a00-1aa3-11eb-8624-45005825419a.png)

dubbo provider 在注册时 未指定分组 系统就会走默认的DEFAULT_GROUP分组进行注册

有地方可以配置这个分组吗？
或者系统处于某些原因这样设计的？ 

有点强迫症 总感觉这个是可以配置的

**Comment by cuoduidui** [comment]
忘记说了  版本
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>2.7.7</version>

**Comment by KomachiSion** [comment]
这个需求应该提交到dubbo，nacos致死后接收方，如果dubbo注册时没有填分组，nacos分组默认值就是DEFAULT_GROUP
