### ISSUE TITLE
部署多个节点时，如何做到节点IP变化对使用方无感知

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4100]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by chuntaojun** [comment]
Please add some description in issue template

**Comment by wanghuigithub** [comment]
通过k8s方式部署集群（3个节点）。当3个节点的IP发生变化时，client端怎样可以做到无感知

**Comment by KomachiSion** [comment]
two ways to solve it:
1. use SLB or domain, and then maintain the them, client only send request to this SLB or domain.
2. use Address server to obtain the ip list of nacos server, client support endpoint mode to do this.

**Comment by wanghuigithub** [comment]
> two ways to solve it:
> 
> 1. use SLB or domain, and then maintain the them, client only send request to this SLB or domain.
> 2. use Address server to obtain the ip list of nacos server, client support endpoint mode to do this.

does both ways need to mantain client IP manually?

where can I get the specific steps of the second way。

**Comment by KomachiSion** [comment]
these two ways both do not need maintain client IP manually.

the first way only input a SLB url or domain to client. the actual ip is maintained in SLB or DNS.
the second way input an endpoint url to client. client will query ip list from endpoint by http GET method. and split them.

The second way need you build an endpoint server or address server which support query by http request.

**Comment by wanghuigithub** [comment]
> these two ways both do not need maintain client IP manually.
> 
> the first way only input a SLB url or domain to client. the actual ip is maintained in SLB or DNS.
> the second way input an endpoint url to client. client will query ip list from endpoint by http GET method. and split them.
> 
> The second way need you build an endpoint server or address server which support query by http request.

Is there some document for the second way in nacos official website?

**Comment by KomachiSion** [comment]
endpoint is a users build server, which can return ips of specified server.

Beacuse the server is user build, so there is no document about this way. We will refactor this part and enhance the document.

Currently, we suggest you use the first way to solve this problem. see https://nacos.io/en-us/docs/cluster-mode-quick-start.html

**Comment by lexburner** [comment]
you can refer to my article: https://www.cnkirito.moe/nacos-cluster-mode/
