### ISSUE TITLE
nacos config长轮询的优势是什么

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4105]
从nacos config的代码来看，long pulling就是client端定时发起HTTP请求，server端在接收到请求后，在超时时间内定时做数据比对。当配置有变更时，server端写response。
此策略不会导致client端与server端频繁的建立过多的连接么。
想问下nacos config采用这种方案的考虑是什么，以及此方案的收益是什么。

**Comment by chuntaojun** [comment]
只有上次的监听失败，才会再次建立起一个新的http链接去做，使用http协议最简单的就是用这种长轮训的模式，不需要客户端实现websocket协议或者Server Send Event协议，并且JDK底层对于http的使用是支持socket复用的，并且一般情况下，一个sdk在运行期间，同一时刻只会有一个长轮训监听任务，对于链接的过多建立问题，是不怎么严重的，同时1.3.x以及1.4.0重新优化了对于http层的使用，直接复用链接，而不是复用底层socket‘

同时这只是1.x的方案，2.x的方案将全面同步到长链接协议

**Comment by wanghuigithub** [comment]
请问「长轮询」的具体含义是指什么呢。
长是指什么。
轮询是顾名思义，指的是周期性执行？

**Comment by KomachiSion** [comment]
轮询：客户端定时向服务器发送请求，服务器接到请求后马上返回响应信息并关闭连接。 
长轮询：客户端向服务器发送请求，服务器接到请求后hold住连接，直到有新消息才返回响应信息并关闭连接，客户端处理完响应信息后再向服务器发送新的请求。 

config的长轮询，就是一直向客户端请求是否有配置出现变更，如果有，则继续通过长轮询获得新配置的过程。
优势就是相比普通的变更推送，能够同时减少客户端和服务端对于同一个配置推送是的负载峰值。因为客户端轮询具有一定的随机性。

**Comment by wanghuigithub** [comment]
> 只有上次的监听失败，才会再次建立起一个新的http链接去做，使用http协议最简单的就是用这种长轮训的模式，不需要客户端实现websocket协议或者Server Send Event协议，并且JDK底层对于http的使用是支持socket复用的，并且一般情况下，一个sdk在运行期间，同一时刻只会有一个长轮训监听任务，对于链接的过多建立问题，是不怎么严重的，同时1.3.x以及1.4.0重新优化了对于http层的使用，直接复用链接，而不是复用底层socket‘
> 
> 同时这只是1.x的方案，2.x的方案将全面同步到长链接协议

socket复用的意思是tcp连接复用？

**Comment by wanghuigithub** [comment]
> 只有上次的监听失败，才会再次建立起一个新的http链接去做，使用http协议最简单的就是用这种长轮训的模式，不需要客户端实现websocket协议或者Server Send Event协议，并且JDK底层对于http的使用是支持socket复用的，并且一般情况下，一个sdk在运行期间，同一时刻只会有一个长轮训监听任务，对于链接的过多建立问题，是不怎么严重的，同时1.3.x以及1.4.0重新优化了对于http层的使用，直接复用链接，而不是复用底层socket‘
> 
> 同时这只是1.x的方案，2.x的方案将全面同步到长链接协议

![image](https://user-images.githubusercontent.com/11936135/97794101-3ea5e700-1c30-11eb-8d89-e06b14609b37.png)
从截图中代码可以看到。同一时刻并非只有一个长轮询监听任务

**Comment by chuntaojun** [comment]
我的描述没有说死同一时刻只有一个长轮训任务，注意看我的描述：并且一般情况下，一个sdk在运行期间，同一时刻只会有一个长轮训监听任务，一般情况下
