### ISSUE TITLE
Spring boot 集成 nacos ，static 成员变量会被删除吗?

### ISSUE THREAD

**Issue by MyselfJar** [alibaba/nacos#4106]
springboot 老项目使用了大量的 static 修饰的变量，全局获取，
集成了 spring-cloud-starter-alibaba-nacos-discovery 后所有变量都为 null 了 。
这是 nacos  的机制吗? 会卸载类，重新加载一次类吗?

**Comment by KomachiSion** [comment]
spring-cloud-starter-alibaba-nacos-discovery 是服务发现使用的，没有配置获取的功能吧。
是不是应该引入spring-cloud-starter-alibaba-nacos-config

**Comment by MyselfJar** [comment]
> spring-cloud-starter-alibaba-nacos-discovery 是服务发现使用的，没有配置获取的功能吧。
> 是不是应该引入spring-cloud-starter-alibaba-nacos-config

我们是把服务注册导 nacos 上，springboot 项目，同事用了 cloud 的包，我用 spring boot 的包发现正常了。
看样子是引错包导致的。
