### ISSUE TITLE
CacheData#setInitializing 没理解这个有什么用呢？

### ISSUE THREAD

**Issue by chuailiwu** [alibaba/nacos#4109]
com.alibaba.nacos.client.config.impl.CacheData#setInitializing

**Comment by shiyiyue1102** [comment]
服务端有一个记录变更推送通知时效SLA的功能，用于统计当配置变更时，客户端多久可以拉取到最新的配置。应用启动后的首次监听查询，Initializing默认为true，则不会往请求头中添加notify标识，服务端就不会统计推送时效。

**Comment by chuailiwu** [comment]
> Initializing默认为true，

看客户端代码，Initializing默认为false的。只有在两个线程添加相同配置且同步锁产生了竞争，才会在后面的线程进来设置为true。

**Comment by chuailiwu** [comment]
> Initializing默认为true，

看客户端代码，Initializing默认为false的。只有在两个线程添加相同配置且同步锁产生了竞争，才会在后面的线程进来设置为true。

> > Initializing默认为true，
> 
> 看客户端代码，Initializing默认为false的。只有在两个线程添加相同配置且同步锁产生了竞争，才会在后面的线程进来设置为true。

public CacheData addCacheDataIfAbsent(String dataId, String group, String tenant) throws NacosException {
        CacheData cache = getCache(dataId, group, tenant);
        if (null != cache) {
            return cache;
        }
        String key = GroupKey.getKeyTenant(dataId, group, tenant);
        synchronized (cacheMap) {
            CacheData cacheFromMap = getCache(dataId, group, tenant);
            // multiple listeners on the same dataid+group and race condition,so
            // double check again
            // other listener thread beat me to set to cacheMap
            if (null != cacheFromMap) {
                cache = cacheFromMap;
                // reset so that server not hang this check
               //只有这里设置了true
                cache.setInitializing(true);
            } else {
                cache = new CacheData(configFilterChainManager, agent.getName(), dataId, group, tenant);
                int taskId = cacheMap.get().size() / (int) ParamUtil.getPerTaskConfigSize();
                cache.setTaskId(taskId);
                // fix issue # 1317
                if (enableRemoteSyncConfig) {
                    String[] ct = getServerConfig(dataId, group, tenant, 3000L);
                    cache.setContent(ct[0]);
                }
            }
            
            Map<String, CacheData> copy = new HashMap<String, CacheData>(this.cacheMap.get());
            copy.put(key, cache);
            cacheMap.set(copy);
        }
        LOGGER.info("[{}] [subscribe] {}", agent.getName(), key);
        
        MetricsMonitor.getListenConfigCountMonitor().set(cacheMap.get().size());
        
        return cache;
    }

**Comment by shiyiyue1102** [comment]
看下CacheData 的构造方法，默认是true的

**Comment by chuailiwu** [comment]
> CacheData

是的。
这里之前主要是没懂server 感知到即使没有配置变更，

**Comment by chuailiwu** [comment]
![image](https://user-images.githubusercontent.com/2288906/97864785-23c49700-1d44-11eb-892d-02e41f2f8672.png)

**Comment by chuailiwu** [comment]
![image](https://user-images.githubusercontent.com/2288906/97864843-32ab4980-1d44-11eb-8d1c-e8c2571387a1.png)
主要是这里为什么要立即返回没懂

**Comment by chuailiwu** [comment]
com.alibaba.nacos.config.server.service.LongPollingService#addLongPollingClient

 long start = System.currentTimeMillis();
            List<String> changedGroups = MD5Util.compareMd5(req, rsp, clientMd5Map);
            if (changedGroups.size() > 0) {
                generateResponse(req, rsp, changedGroups);
                LogUtil.CLIENT_LOG.info("{}|{}|{}|{}|{}|{}|{}", System.currentTimeMillis() - start, "instant",
                        RequestUtil.getRemoteIp(req), "polling", clientMd5Map.size(), probeRequestSize,
                        changedGroups.size());
                return;
            } else if (noHangUpFlag != null && noHangUpFlag.equalsIgnoreCase(TRUE_STR)) {
                LogUtil.CLIENT_LOG.info("{}|{}|{}|{}|{}|{}|{}", System.currentTimeMillis() - start, "nohangup",
                        RequestUtil.getRemoteIp(req), "polling", clientMd5Map.size(), probeRequestSize,
                        changedGroups.size());
                return;
            }

noHangUpFlag 为true时为什么要立即返回，对客户端的意义是什么呢？

**Comment by shiyiyue1102** [comment]
初始的时候，客户端添加监听器 和 内部发起http监听轮询是同时进行的，有可能 客户端只添加了一部分监听器，此时已经发起监听请求，这钟情况下，如果服务端不立即返回，那么后面添加的配置监听时效就会有30秒的延迟，应用刚启动的过程中会出现这种情况。

**Comment by chuailiwu** [comment]
> 那么后面添加
这种情况我想过，但是好像不能发生。
listener的md5值是用CacheData的md5赋值的。
如果server检查到配置有变更，changedGroups.size() > 0会生效
如果没有变更，说明客户端的内容没有变化，即使以noHangUpFlag==true的方式快速返回，但是客户端检查配置是一样的，也不会触发通知listener的逻辑

**Comment by chuailiwu** [comment]
这种情况我想过，但是好像不能发生。
listener的md5值是用CacheData的md5赋值的。
如果server检查到配置有变更，changedGroups.size() > 0会生效。
如果没有变更，说明客户端的内容没有变化，即使以noHangUpFlag==true的方式快速返回，但是客户端检查配置是一样的，也不会触发通知listener的逻辑

**Comment by shiyiyue1102** [comment]
> 这种情况我想过，但是好像不能发生。
> listener的md5值是用CacheData的md5赋值的。
> 如果server检查到配置有变更，changedGroups.size() > 0会生效。
> 如果没有变更，说明客户端的内容没有变化，即使以noHangUpFlag==true的方式快速返回，但是客户端检查配置是一样的，也不会触发通知listener的逻辑

如果客户端监听的都是不存在的配置，就会出现changedGroups.size() = 0的场景，这个时候不立即访问就会出现延迟
