### ISSUE TITLE
nacos服务注册和dubbo消费端注册

### ISSUE THREAD

**Issue by noobzhp** [alibaba/nacos#4113]
nacos服务器中心暴露了api接口以后，消费端单独引用@DubboReference接口可正常注册到nacos，如果该项目还想再注册到nacos进行一些服务转发的话会报错，
![image](https://user-images.githubusercontent.com/27613520/97821813-b2a6c480-1cee-11eb-8a23-6e58d97a4145.png)
如果是服务提供端的话就不会出错，nacos上会出现provider和application name两个服务，而消费端也想注册上consumer和一个application name，应该怎么配置呢。这是pom文件

![1604281098(1)](https://user-images.githubusercontent.com/27613520/97821940-28129500-1cef-11eb-828d-cbf506d8e0d2.jpg)

**Comment by KomachiSion** [comment]
看报错像是dubbo的问题，麻烦将这个issue提到dubbo社区
