### ISSUE TITLE
[Discuss] Shall we change Nacos-Client naming listener notify way (sync -> async)

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4115]
**Describe the topc**
Now in `com.alibaba.nacos.client.naming.core.EventDispatcher.Notifier.run`, when get serviceChange from server, it will notify  `com.alibaba.nacos.client.naming.core.EventDispatcher.Notifier.run`, find listener by serviceKey, and execute the callback.
But the callback is sync to execute, if some long time operation in the callback, it will blocking other service's notify.
Shall we add some info in docs to hint user, this callback is sync, if do long time operation, it will influence other listener or service to notify. let user execute it by thread they defined by themselves.
Or execute callback in thread pool which realized by framework.

**Comment by chuntaojun** [comment]
You can use NotifyCenter instead, which is already in the common module

**Comment by horizonzy** [comment]
I mean this logic 
![image](https://user-images.githubusercontent.com/22524871/97853597-44382580-1d33-11eb-81a5-9fd06261ba43.png)

**Comment by chuntaojun** [comment]
In the end, all event mechanisms need to be gathered into NotifyCenter. The logic you want has been implemented internally. You can see

**Comment by chuntaojun** [comment]
```java
@Override
public void notifySubscriber(final Subscriber subscriber, final Event event) {
        
        LOGGER.debug("[NotifyCenter] the {} will received by {}", event, subscriber);
        
        final Runnable job = new Runnable() {
            @Override
            public void run() {
                subscriber.onEvent(event);
            }
        };
        
        final Executor executor = subscriber.executor();
        
        if (executor != null) {
            executor.execute(job);
        } else {
            try {
                job.run();
            } catch (Throwable e) {
                LOGGER.error("Event callback exception : {}", e);
            }
        }
}
```

**Comment by horizonzy** [comment]
yeah, 👍
