### ISSUE TITLE
持久化节点服务下线时 调用deregister 方法主动下线，但是 ephemeral 属性是true 

### ISSUE THREAD

**Issue by langteng** [alibaba/nacos#4116]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by langteng** [comment]
@Override
    public void deregisterInstance(String serviceName, String groupName, String ip, int port, String clusterName)
            throws NacosException {
        Instance instance = new Instance();  // new Instance() 对象时，instance的ephemeral 属性默认是 true
        instance.setIp(ip);
        instance.setPort(port);
        instance.setClusterName(clusterName);
        
        deregisterInstance(serviceName, groupName, instance);
    }

**Comment by chuntaojun** [comment]
有重载的方法，注意看下

**Comment by KomachiSion** [comment]
请使用deregisterInstance(String serviceName, String groupName, Instance instance)方法

**Comment by langteng** [comment]
![image](https://user-images.githubusercontent.com/34200581/98089327-842b1400-1ebd-11eb-9c0d-812e1e69560d.png)
我这边的现象是，我的服务是持久化节点，服务宕机时会触发com.alibaba.cloud.nacos.registry.NacosServiceRegistry#deregister 这个方法。主动告诉Nacos 我这个服务要下线，但是上图的方法里面的 ephemeral 属性是true .  走到Nacos 服务端 之后，是从临时节点集合中下线 我的 持久化节点，这样就出问题了。

**Comment by ymingxu** [comment]
> ```
> @Override
> public void deregisterInstance(String serviceName, String groupName, String ip, int port, String clusterName)
>         throws NacosException {
>     Instance instance = new Instance();  // new Instance() 对象时，instance的ephemeral 属性默认是 true
>     instance.setIp(ip);
>     instance.setPort(port);
>     instance.setClusterName(clusterName);
>     
>     deregisterInstance(serviceName, groupName, instance);
> }
> ```
您好，我也想实现服务的持久化注册功能，您解决这个问题了吗
