### ISSUE TITLE
权限控制

### ISSUE THREAD

**Issue by TheheiWorld** [alibaba/nacos#4121]
export DEFAULT_SEARCH_LOCATIONS="classpath:/,classpath:/config/,file:./,file:./config/"
export CUSTOM_SEARCH_LOCATIONS=${DEFAULT_SEARCH_LOCATIONS},file:${BASE_DIR}/conf/

console 模块下有 application.properties 文件

这两种会导致 修改  file:${BASE_DIR}/conf 下面的 application.properties  中属性 并不生效，比如 
conf/ 下面 跟 console  模块中 都有   application.properties 文件， 都有  nacos.core.auth.enabled=true这个配置，
更改 conf/ 下面的并不能生效

**Comment by horizonzy** [comment]
how to repreduce it. 
such as:
step1.
step2.
step3.

**Comment by KomachiSion** [comment]
1.4.0 has fixed this problem.
