### ISSUE TITLE
程序停止后，会报

### ISSUE THREAD

**Issue by weinianta** [alibaba/nacos#4128]
nacos-1.4.0

![image](https://user-images.githubusercontent.com/13379708/98062626-60e67180-1e89-11eb-81a1-45d8fe51a61d.png)

**Comment by KomachiSion** [comment]
麻烦将此issue提交至spring-cloud-alibaba社区

**Comment by weinianta** [comment]
？？？

不是 nacoswatch 没有正确关闭吗？

**Comment by Maijh97** [comment]
@weinianta nacoswatch 是spring-cloud-alibaba那边的实现
