### ISSUE TITLE
@NacosValue is invalid when used in constructor parameters

### ISSUE THREAD

**Issue by BlackRen09** [alibaba/nacos#4130]
When I use @NacosValue in parameters of a constructor, I find this annotation is invalid, but @Value works.
How to solve this problem and what' s the difference between @NacosValue and @Value?
Thanks very much!

**Comment by KomachiSion** [comment]
NacosValue is annotation in spring-boot-nacos, which make the parameter can be refresh by nacos when config changed.

value is spring boot annotation.

I'm not sure whether NacosValue can be used in parameters of a constructor.
The solution I think is not use parameters of a constructor but use it in member variables.
