### ISSUE TITLE
there is a bug in file ServiceInfo

### ISSUE THREAD

**Issue by shizhengxing** [alibaba/nacos#4136]
java class name:com.alibaba.nacos.api.naming.pojo.ServiceInfo  
method:

    public ServiceInfo(String key) {  
        int maxIndex = 2;  
        int clusterIndex = 1;
        int serviceNameIndex = 0;

        String[] keys = key.split(Constants.SERVICE_INFO_SPLITER);
        if (keys.length >= maxIndex) {
            this.name = keys[serviceNameIndex];
            this.clusters = keys[clusterIndex];
        }

        this.name = keys[0];
    }`
When read cache file from disk throuth method `DiskCache.read(String cacheDir)`, the method use constructor `public ServiceInfo(String key)` to instantiate `ServiceInfo`,you can check the code in file DiskCache of line 111.
I give a example of the input param for method `public ServiceInfo(String key)` like `group@@service_name@@clusters`.

You can see when spilt with `@@` ,the `clusterIndex` should be 2 not 1, and the serviceNameIndex should be 1 not 0,and the `groupName` can be fill with data of index=0.

**Comment by shizhengxing** [comment]
if it confirmed ,i will fix it so quickly!

**Comment by KomachiSion** [comment]
OK.

When you try to fix it. Please do some test for compatibility test with old version nacos server from 1.1.3 to 1.3.2

**Comment by zrlw** [comment]
> java class name:com.alibaba.nacos.api.naming.pojo.ServiceInfo
> method:
> 
> ```
> public ServiceInfo(String key) {  
>     int maxIndex = 2;  
>     int clusterIndex = 1;
>     int serviceNameIndex = 0;
> 
>     String[] keys = key.split(Constants.SERVICE_INFO_SPLITER);
>     if (keys.length >= maxIndex) {
>         this.name = keys[serviceNameIndex];
>         this.clusters = keys[clusterIndex];
>     }
> 
>     this.name = keys[0];
> }`
> ```
> 
> When read cache file from disk throuth method `DiskCache.read(String cacheDir)`, the method use constructor `public ServiceInfo(String key)` to instantiate `ServiceInfo`,you can check the code in file DiskCache of line 111.
> I give a example of the input param for method `public ServiceInfo(String key)` like `group@@service_name@@clusters`.
> 
> You can see when spilt with `@@` ,the `clusterIndex` should be 2 not 1, and the serviceNameIndex should be 1 not 0,and the `groupName` can be fill with data of index=0.

you should consider 'key' in different situations: 
1. name
2. group@@name
3. group@@name@@cluster

**Comment by shizhengxing** [comment]
> > java class name:com.alibaba.nacos.api.naming.pojo.ServiceInfo
> > method:
> > ```
> > public ServiceInfo(String key) {  
> >     int maxIndex = 2;  
> >     int clusterIndex = 1;
> >     int serviceNameIndex = 0;
> > 
> >     String[] keys = key.split(Constants.SERVICE_INFO_SPLITER);
> >     if (keys.length >= maxIndex) {
> >         this.name = keys[serviceNameIndex];
> >         this.clusters = keys[clusterIndex];
> >     }
> > 
> >     this.name = keys[0];
> > }`
> > ```
> > 
> > 
> > When read cache file from disk throuth method `DiskCache.read(String cacheDir)`, the method use constructor `public ServiceInfo(String key)` to instantiate `ServiceInfo`,you can check the code in file DiskCache of line 111.
> > I give a example of the input param for method `public ServiceInfo(String key)` like `group@@service_name@@clusters`.
> > You can see when spilt with `@@` ,the `clusterIndex` should be 2 not 1, and the serviceNameIndex should be 1 not 0,and the `groupName` can be fill with data of index=0.
> 
> you should consider 'key' in different situations:
> 
> ```
> 1. name
> 2. group@@name
> 3. group@@name@@cluster
> ```

got it ,thanks for your reminding

**Comment by shizhengxing** [comment]
> OK.
> 
> When you try to fix it. Please do some test for compatibility test with old version nacos server from 1.1.3 to 1.3.2

ok, i will do it
