### ISSUE TITLE
Enhence the hint info in config search input to hint user fuzzy search use symbol '*'

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4141]
**Describe the feature**
many user don't know how to use fuzzy search,  I notice many issue about this situation.
#2079 #2603 #3545 #2645 #2692 #3897
Maybe we should modify the hint info to hint user use symbol '*' to fuzzy search.

**Comment by KomachiSion** [comment]
I think we can add some description in document. Or add hint in input box.

**Comment by horizonzy** [comment]
add hint info in  input box is more useful.
