### ISSUE TITLE
Document content error

### ISSUE THREAD

**Issue by woxiangwoxiangxiang** [alibaba/nacos#4142]
## Issue Description

Type: *bug report*  request*

Info: In the Nacos Document [https://nacos.io/zh-cn/docs/monitor-guide.html](here)

The prometheus.yml Code Demo miss a space 
In the code demo third line.
NOW :
 ```
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets:['{ip1}:8848','{ip2}:8848','{ip3}:8848']
```
AFTER FIX

 ```
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['{ip1}:8848','{ip2}:8848','{ip3}:8848']
```
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
any difference? I can't find the actual difference

**Comment by woxiangwoxiangxiang** [comment]
here,here,here

```
targets:['{ip1}:8848','{ip2}:8848','{ip3}:8848']
targets: ['{ip1}:8848','{ip2}:8848','{ip3}:8848']
```

This place needs a space.

**Comment by KomachiSion** [comment]
Does this space affect the result of using? Or just for formatting?

**Comment by woxiangwoxiangxiang** [comment]
"Yaml" is a well formed language, and the lack of a space will lead to compilation failure ！

**Comment by KomachiSion** [comment]
OK,  Can you submit a PR to nacos-group.github.io to fix this problem?

**Comment by woxiangwoxiangxiang** [comment]
This bug is in the official Nacos documentation, **not in the code**. How can I fix it? Can you give me an example of how I can fix it or how to do it

**Comment by KomachiSion** [comment]
I said , sumbit a PR to [nacos-group.github.io](https://github.com/nacos-group/nacos-group.github.io)

**Comment by woxiangwoxiangxiang** [comment]
Do you need to create an issue in  [nacos-group.github.io](nacos-group.github.io)

**Comment by KomachiSion** [comment]
fixed by https://github.com/nacos-group/nacos-group.github.io/issues/130
