### ISSUE TITLE
Nacos持久化什么时候可以支持oracle呀

### ISSUE THREAD

**Issue by CodeDWX** [alibaba/nacos#4145]
公司内网，目前只有oracle服务器 头大

**Comment by KomachiSion** [comment]
可以试着自行替换一下jdbc驱动和jdbc配置，不过可能分页SQL会有兼容性问题。

**Comment by KomachiSion** [comment]
或者自行打包feature_multiple_datasource_support分支试一下

**Comment by KomachiSion** [comment]
duplicate with #2328

**Comment by CodeDWX** [comment]
> 与[＃2328](https://github.com/alibaba/nacos/issues/2328)复制[](https://github.com/alibaba/nacos/issues/2328)

好的 我先试试  谢谢了

**Comment by zredMonkey** [comment]
大佬们  oracle持久化支持oracle你们搞出来了吗？求教<(*￣▽￣*)/

**Comment by dylan-tao** [comment]
> 公司内网，目前只有oracle服务器 头大

nacosplus针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
