### ISSUE TITLE
建议减少对第三方库的依赖，例如：guava

### ISSUE THREAD

**Issue by brucewuu520** [alibaba/nacos#4152]
建议减少对第三方库的依赖，例如：guava

**Comment by KomachiSion** [comment]
已经在计划中了，目前准备先去除common-lang3，一个个去除。

**Comment by zzq1314zll** [comment]
Nacos 依赖guava 相关的api可以移除，但是grpc 也是依赖的guava 的

**Comment by zzq1314zll** [comment]
我统计了下，现在nacos 中使用guava 的一些api类型，然后按照类型划分了任务

- [ ] google.common.collect.* 下面的集合 [nacos-config] [nacos-common] [nacos-naming] [nacos-core]
- [ ] google.common.base.* 下面的Objects、Strings、Joiner、Preconditions、Stopwatch 工具类 [nacos-config] [nacos-api] [nacos-commmon] [nacos-core]
- [ ] google.common.cache.* 缓存 [nacos-client] [nacos-core]
- [ ] google.common.util.concurrent.* 并发工具类，**涉及到grpc 的不用改动**
- [ ] google.common.reflect.*   TypeToken

**Comment by zzq1314zll** [comment]
@i will solve it@

**Comment by zzq1314zll** [comment]
@KomachiSion All tasks have been completed

**Comment by paruza89** [comment]
- [ ] 

- [ ] 

- [ ] 

- 

1. ### **__**

**Comment by paruza89** [comment]
> 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] ``
