### ISSUE TITLE
whether the server node reload the config data when the node restart?

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4155]
whether the server node reload the config data when the node restart?
will the node's local config be reload?

**Comment by KomachiSion** [comment]
Nacos server will dump config data from database when server start.

> will the node's local config be reload?

I can't get this problem means.

**Comment by wanghuigithub** [comment]
> Nacos server will dump config data from database when server start.
> 
> > will the node's local config be reload?
> 
> I can't get this problem means.

update the config data which store in local disk

**Comment by KomachiSion** [comment]
Yes, it is.

**Comment by wanghuigithub** [comment]
ok thanks a lot
