### ISSUE TITLE
nacos k8s文档中提到的必须要使用持久卷，否则会出现数据丢失的情况有哪些

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4156]
nacos k8s是使用statefulset部署nacos server
因为nacos server重启时，会重新从数据库dump数据。
所以文档中提到的必须要使用持久卷，否则会出现数据丢失是在什么情况下回发生数据丢失

**Comment by KomachiSion** [comment]
如果在服务发现使用了持久化实例，或者使用了derby数据库的时候，这些数据是存在nacos server的本地磁盘，如果部分数据在k8s里不挂在持久卷，在pod重启后这部分数据就会丢失。

**Comment by wanghuigithub** [comment]
使用MySQL时，且在k8s中部署nacos-server不挂持久卷时，这种情况是不是就不会丢数据

**Comment by chenshun00** [comment]
`mysql` : 看源码的时候nacos-server启动的时候会把所有数据dump出来，按这个思路我觉得无状态也是可以的，就是要解决3个节点之间的通信. 

3个k8s节点使用cluster-ip通信的话，和自己不通吧

**Comment by wanghuigithub** [comment]
> `mysql` : 看源码的时候nacos-server启动的时候会把所有数据dump出来，按这个思路我觉得无状态也是可以的，就是要解决3个节点之间的通信.
> 
> 3个k8s节点使用cluster-ip通信的话，和自己不通吧

「和自己不通吧」的意思是？没太理解

**Comment by chenshun00** [comment]
举个例子
我创建3个无状态的应用
nacos-1 --> 10.10.10.1
nacos-2 --> 10.10.10.2
nacos-3 --> 10.10.10.3

**Comment by KomachiSion** [comment]
> 使用MySQL时，且在k8s中部署nacos-server不挂持久卷时，这种情况是不是就不会丢数据

如果不使用服务发现模块的持久化实例功能，并且使用mysql作为配置持久化存储，是可以不挂持久卷，就是日志重启的时候会丢失，自己权衡。

另外mysql不应该和nacos实例放在一个pod里，不同的pod应该ip是不同的，不需要自己访问自己吧。

**Comment by wanghuigithub** [comment]
> > 使用MySQL时，且在k8s中部署nacos-server不挂持久卷时，这种情况是不是就不会丢数据
> 
> 如果不使用服务发现模块的持久化实例功能，并且使用mysql作为配置持久化存储，是可以不挂持久卷，就是日志重启的时候会丢失，自己权衡。
> 
> 另外mysql不应该和nacos实例放在一个pod里，不同的pod应该ip是不同的，不需要自己访问自己吧。

日志重启是指？

**Comment by chenshun00** [comment]
> 另外mysql不应该和nacos实例放在一个pod里，不同的pod应该ip是不同的，不需要自己访问自己吧。

nacos 3个节点之间通信，我看是有自己访问自己的. 
eg: openAPI/控制台增加一个配置，给自己和其他2个节点发送一个增加配置的请求. 
```text
                                                  --> nacos 1
openapi/console --> nacos 1 --> nacos 2
                                                  --> nacos 3
```

看的时间有点久了，不确定现在还是不是这么个逻辑. 🔢

**Comment by wanghuigithub** [comment]
> > 另外mysql不应该和nacos实例放在一个pod里，不同的pod应该ip是不同的，不需要自己访问自己吧。
> 
> nacos 3个节点之间通信，我看是有自己访问自己的.
> eg: openAPI/控制台增加一个配置，给自己和其他2个节点发送一个增加配置的请求.
> 
> ```
>                                                   --> nacos 1
> openapi/console --> nacos 1 --> nacos 2
>                                                   --> nacos 3
> ```
> 
> 看的时间有点久了，不确定现在还是不是这么个逻辑. 🔢


你提的问题好像和这个问题的主题不太一样哈

**Comment by KomachiSion** [comment]
> > > 使用MySQL时，且在k8s中部署nacos-server不挂持久卷时，这种情况是不是就不会丢数据
> > 
> > 
> > 如果不使用服务发现模块的持久化实例功能，并且使用mysql作为配置持久化存储，是可以不挂持久卷，就是日志重启的时候会丢失，自己权衡。
> > 另外mysql不应该和nacos实例放在一个pod里，不同的pod应该ip是不同的，不需要自己访问自己吧。
> 
> 日志重启是指？

如果没有挂在持久卷，nacos的日志文件在pod重启的时候会丢失。不容易排查问题。
