### ISSUE TITLE
nacos-config-spring-boot-starter is old

### ISSUE THREAD

**Issue by phpisfuture** [alibaba/nacos#4160]
springboot nacos-config-spring-boot-starter is old.
contains com.alibaba.nacos:nacos-client not compatible with the latest version.
com.alibaba.nacos.client.utils.StringUtils class not found.

**Comment by horizonzy** [comment]
see https://github.com/nacos-group/nacos-spring-boot-project/pull/155. wait next release.

**Comment by phpisfuture** [comment]
> see [nacos-group/nacos-spring-boot-project#155](https://github.com/nacos-group/nacos-spring-boot-project/pull/155). wait next release.

thankyou
