### ISSUE TITLE
Nacos 1.4 can't connect to MySQL 5.8 

### ISSUE THREAD

**Issue by itwangyun** [alibaba/nacos#4164]
When docker deployment nacos to mysql database Connection error org. Springframework. JDBC. CannotGetJdbcConnectionException: Failed to obtain a JDBC Connection;nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
Mysql is 5.8, nacos is 1.4

**Comment by horizonzy** [comment]
do you use external db? How do you confg the url?

**Comment by Tinywan** [comment]
this mysql config error

**Comment by KomachiSion** [comment]
Your provided information is not the root error of connect failed. Please check nacos.log and start.log to find out what's the real error.

**Comment by KomachiSion** [comment]
No more response from author and current provided information is not root error. So we think the author has found the root error and solve it by self. Close issue.
