### ISSUE TITLE
added editorconfig to maintain consistent coding styles

### ISSUE THREAD

**Issue by anjia0532** [alibaba/nacos#417]
**Is your feature request related to a problem? Please describe.**
英语不好，不硬凹了，烦请代为翻译一下。
在项目中发现大量代码规范不统一的情况，比如，4个空格和tab混用(在阿里规约强制要求4个空格)，不利于团队协作，或者社区贡献。

**Describe the solution you'd like**
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. 

**Describe alternatives you've considered**
除了使用sonar+checkStyle等查件进行校验外，还可以添加editorConfig，主流编辑器都支持。更便于社区贡献代码。

**Comment by hxy1991** [comment]
(IDEA Configure the code style for a project using EditorConfig)[https://www.jetbrains.com/help/idea/configuring-code-style.html]

**Comment by anjia0532** [comment]
yeap,but u lose anchor . https://www.jetbrains.com/help/idea/configuring-code-style.html#editorconfig
