### ISSUE TITLE
Nacos 1.4.0 报错“old raft protocol already stop”

### ISSUE THREAD

**Issue by aakejiang** [alibaba/nacos#4172]
**Describe the bug**

通过rest api查看节点选举状态，报错：

[root@nacos-0 logs]# curl -sS 'http://localhost:8848/nacos/v1/ns/raft/state'
caused: old raft protocol already stop;

**How to Reproduce**

分析代码：
![image](https://user-images.githubusercontent.com/68629395/98497547-43e1e200-227f-11eb-8d6f-354b42fc3b15.png)

if判断里，当变量 allMemberIsNewVersion为true时会抛该异常。修改该变量的只有judge方法：
![image](https://user-images.githubusercontent.com/68629395/98497634-82779c80-227f-11eb-87fe-e51d5425f7e3.png)

allMemberIsNewVersion初始为false，所以 !this.allMemberIsNewVersion 是true。allMemberIsNewVersion变量的话，因为我的version是1.4.0，所以allMemberIsNewVersion为true。这样 if (allMemberIsNewVersion && !this.allMemberIsNewVersion) 成立会导致this.allMemberIsNewVersion = true; 就会抛出 “caused: old raft protocol already stop;”异常

**Comment by KomachiSion** [comment]
提示很明显 旧版本的raft已经停止了，1.4.0版本使用了新的jraft，当整个集群都升级到1.4.0时，就关闭旧raft系统，使用jraft
此时调用旧raft的相关接口，报错是正确的，符合预期的。

**Comment by aakejiang** [comment]
不是升级，部署的就是1.4.0，何来关闭旧raft一说？

**Comment by KomachiSion** [comment]
直接部署1.4.0那启动的时候旧raft就被关闭了，旧raft的接口就已经不可用了。

**Comment by aakejiang** [comment]
http://localhost:8848/nacos/v1/ns/raft/state 是旧raft的接口，1.4.0已经不用这个了是吧？

**Comment by chuntaojun** [comment]
> http://localhost:8848/nacos/v1/ns/raft/state 是旧raft的接口，1.4.0已经不用这个了是吧？

是的，当整个集群都是1.4.0之后，一致性协议的信息只会有集群页面展示了～，不会开辟额外的接口进行查询

**Comment by MumfordSons** [comment]
什么意思？意思是全部都为1.4.0会抛出异常信息，但这是正常的？
