### ISSUE TITLE
Hope to 

### ISSUE THREAD

**Issue by CaseCy** [alibaba/nacos#4173]
希望能够支持从本地初始化配置文件，现在的web页面操作对于生产环境多个配置文件的添加和修改并不友好（生产环境不能够在页面上访问nacos页面，因为有安全风险，通过openApi的话只能一个一个的添加和修改）。

It is hoped that the configuration files can be initialized locally. The web page operation and open api operation are not friendly for adding and modifying multiple configuration files in the production environment (the production environment can not access Nacos page on the page, because there is a security risk, through OpenAPI, you can only add and modify one by one).

**Comment by KomachiSion** [comment]
From local loading configuration file is not nacos feature, it should be of spring-cloud or spring-cloud-alibaba.

And if you think nacos web console is not safe, you can base openAPI to develop a security console by yourself and company.
