### ISSUE TITLE
mysql no password can't connect

### ISSUE THREAD

**Issue by wp867007845** [alibaba/nacos#4175]
**Describe the bug**
![image](https://user-images.githubusercontent.com/41058332/98510020-50753300-229d-11eb-97f2-3093ba5bda73.png)

![image](https://user-images.githubusercontent.com/41058332/98509911-14da6900-229d-11eb-9d37-92a0a3635831.png)
你好，我在使用nacos1.4.0时，如果我的mysql没有设置密码，nacos是无法启动的，另外springcloud连接nacos后，使用配置，控制台总是重复打印配置
![image](https://user-images.githubusercontent.com/41058332/98510075-6daa0180-229d-11eb-8be3-9269bc9525e4.png)

**Comment by KomachiSion** [comment]
第一个问题我记得是spring的问题，配置为空字符串的时候会把这个key给过滤掉导致取这个key的时候为null，这里nacos目前会校验，如果没有输入密码会报错，可能需要讨论下是否需要继续校验这个值。

第二个问题你看下是不是namespace填了public，如果是，把namespace去掉就可以了

**Comment by wp867007845** [comment]
谢谢，已经解决了
