### ISSUE TITLE
run sh bin/ startup.sh-m standalone throw failed to req API:/api//nacos/v1/ns/instance/list after all servers

### ISSUE THREAD

**Issue by phpisfuture** [alibaba/nacos#4176]
nacos-server-1.4.0.zip
第一个运行`sh bin/startup.sh -m standalone`启动没问题。
第二次运行`sh bin/startup.sh -m standalone`启动，注册服务会报错如下：
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: server is DOWN now, please try again later!

nacos-server-1.4.0.zip
The first one to run the `sh bin/ startup.sh-m standalone` will start fine.
The second time you run the `sh bin/ startup.sh-m standalone` startup, the registration service will report the following error:
`com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: server is DOWN now, please try again later!`

**Comment by horizonzy** [comment]
本地的Ip变过了，现在新版的raft从日志从找老的节点信息。因为日志中记录的是之前的ip，导致leader无法选出，raft协议无法提供服务。如果还没有写持久化节点的话，把user.home/nacos/data/protocol这个目录删除重新启动即可。

**Comment by phpisfuture** [comment]
> 本地的Ip变过了，现在新版的raft从日志从找老的节点信息。因为日志中记录的是之前的ip，导致leader无法选出，raft协议无法提供服务。如果还没有写持久化节点的话，把user.home/nacos/data/protocol这个目录删除重新启动即可。

thankyou

**Comment by lidaoyang** [comment]
> 本地的Ip变过了，现在新版的raft从日志从找老的节点信息。因为日志中记录的是之前的ip，导致leader无法选出，raft协议无法提供服务。如果还没有写持久化节点的话，把user.home/nacos/data/protocol这个目录删除重新启动即可。

我这边测试是把1.4.0 server下面的data/protocol目录删除之后重启server才可以注册，user.home/nacos/data下面没有protocol目录。
我下次IP变了是不是还要再删除一下呢？

**Comment by horizonzy** [comment]
> > 本地的Ip变过了，现在新版的raft从日志从找老的节点信息。因为日志中记录的是之前的ip，导致leader无法选出，raft协议无法提供服务。如果还没有写持久化节点的话，把user.home/nacos/data/protocol这个目录删除重新启动即可。
> 
> 我这边测试是把1.4.0 server下面的data/protocol目录删除之后重启server才可以注册，user.home/nacos/data下面没有protocol目录。
> 我下次IP变了是不是还要再删除一下呢？

嗯。可以通过-Dnacos.server.ip配置用域名来做映射到本机

**Comment by lidaoyang** [comment]
> > > 本地的Ip变过了，现在新版的raft从日志从找老的节点信息。因为日志中记录的是之前的ip，导致leader无法选出，raft协议无法提供服务。如果还没有写持久化节点的话，把user.home/nacos/data/protocol这个目录删除重新启动即可。
> > 
> > 
> > 我这边测试是把1.4.0 server下面的data/protocol目录删除之后重启server才可以注册，user.home/nacos/data下面没有protocol目录。
> > 我下次IP变了是不是还要再删除一下呢？
> 
> 嗯。可以通过-Dnacos.server.ip配置用域名来做映射到本机

如果是集群会有这个问题吗？

**Comment by horizonzy** [comment]
> > > > 本地的Ip变过了，现在新版的raft从日志从找老的节点信息。因为日志中记录的是之前的ip，导致leader无法选出，raft协议无法提供服务。如果还没有写持久化节点的话，把user.home/nacos/data/protocol这个目录删除重新启动即可。
> > > 
> > > 
> > > 我这边测试是把1.4.0 server下面的data/protocol目录删除之后重启server才可以注册，user.home/nacos/data下面没有protocol目录。
> > > 我下次IP变了是不是还要再删除一下呢？
> > 
> > 
> > 嗯。可以通过-Dnacos.server.ip配置用域名来做映射到本机
> 
> 如果是集群会有这个问题吗？

如果是在运行过程中，ip变化的话是能感知到进行处理的。如果是中途关闭，也是一样的。

**Comment by lidaoyang** [comment]
> 嗯。可以通过-Dnacos.server.ip配置用域名来做映射到本机

这个域名映射好像不起作用。
![image](https://user-images.githubusercontent.com/26211950/98640983-fdb37e00-2365-11eb-8982-9730a4e9f922.png)
![image](https://user-images.githubusercontent.com/26211950/98641026-10c64e00-2366-11eb-90b6-4a8b74fc9901.png)
![image](https://user-images.githubusercontent.com/26211950/98641057-1b80e300-2366-11eb-8be7-1625e5ff8f40.png)

host
![image](https://user-images.githubusercontent.com/26211950/98641160-4bc88180-2366-11eb-8452-880d043b9a9f.png)

**Comment by horizonzy** [comment]
你先把protocol文件删除了，再重新启动。后面ip变了也没事

**Comment by lidaoyang** [comment]
> 你先把protocol文件删除了，再重新启动。后面ip变了也没事

就是如果nacos-server不重启，就不会有这个问题是吗？

**Comment by lidaoyang** [comment]
> 你先把protocol文件删除了，再重新启动。后面ip变了也没事

好的，thank you

**Comment by horizonzy** [comment]
是的，如果nacos-server进行了关闭，下一次启动和上一次启动期间如果ip进行了变化，会存在问题。所以通过域名来规避。

**Comment by lidaoyang** [comment]
> 是的，如果nacos-server进行了关闭，下一次启动和上一次启动期间如果ip进行了变化，会存在问题。所以通过域名来规避。

ok , thank you
