### ISSUE TITLE
The configured tags cannot be added and queried correctly

### ISSUE THREAD

**Issue by Panyulong9527** [alibaba/nacos#4177]
**Describe the bug**
我在新增和编辑配置的---更多高级选项 时，尝试添加标签 并发布，但是标签无法正确的保存，我尝试使用英文字母，或者数字，或者中文，或者各种组合，都不行。。。   我在1.3.2和1.4.0两个官方控制台样板上都尝试过，本地打架了1.3.1 也尝试过 都存在这个现在，不确定是否是我在使用上出错了。。
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by horizonzy** [comment]
有可能是缓存的问题。清除一下缓存或者用无痕模式试试

**Comment by Panyulong9527** [comment]
> 有可能是缓存的问题。清除一下缓存或者用无痕模式试试

是在chrome上试的 ，清理了缓存不好使依然存在这个现象，然后换360浏览器开了无痕模式试了情况一样，最后还是谢谢解答鸭：）

**Comment by KomachiSion** [comment]
duplicate with #4050
