### ISSUE TITLE
当数据库密码里面有特殊字符【逗号】时db密码不生效

### ISSUE THREAD

**Issue by Yanwenjingcn** [alibaba/nacos#4179]
![image](https://user-images.githubusercontent.com/16257260/98523782-45c49900-22b1-11eb-99b7-c5a085f060ff.png)
![image](https://user-images.githubusercontent.com/16257260/98523963-86bcad80-22b1-11eb-84ca-0149d8ee9d12.png)

本身db密码类似于

fsf@_gdajgnja*sdk^,

注意，我们有逗号，有逗号，有逗号

但是一直报access denied，密码错误，但是直接mysql -h XXX -u nacos -p XXXX 是可以登上。

**Comment by horizonzy** [comment]
当密码存在`,`时，设置`db.passsword`时如果没有指定`.0`的话，会通过`,`将密码进行分割，最后用下标为0的那个密码。你这种情况最终使用的密码其实是`fsf@_gdajgnja*sdk^`。注意是没有逗号的。
如果密码中存在逗号的情况，指定`db.password.0`来直接对密码进行设置。不对密码做逗号的切割。

**Comment by KomachiSion** [comment]
解释一下，nacos考虑到多个数据源的情况，db 的 url,username,password是一个列表， spring对于list列表的配置会取.n的下标或者按照分隔符分割（默认,) 因此当内容中有该分隔符的时候，可能会出问题。

建议按照xx.0=abc的方式配置

**Comment by horizonzy** [comment]
> 解释一下，nacos考虑到配置主备数据源的情况，db 的 url,username,password是一个列表， spring对于list列表的配置会取.n的下标或者按照分隔符分割（默认,) 因此当内容中有该分隔符的时候，可能会出问题。
> 
> 建议按照xx.0=abc的方式配置

要不要把默认的注释那里改成.0的，感觉这样对用户来说好一点。

**Comment by KomachiSion** [comment]
可以考虑

**Comment by bcdslg** [comment]
这种情况docker-compose 中怎么配置密码呢
