### ISSUE TITLE
OpenAPI is still available when i set nacos.core.auth.enabled=true and Nacos started successfully in cluster mode.

### ISSUE THREAD

**Issue by twogozi** [alibaba/nacos#4181]
OpenAPI is still available when i set nacos.core.auth.enabled=true and Nacos started successfully in cluster mode.
Nacos V1.3.0

**Comment by KomachiSion** [comment]
how to display your nacos cluster? docker? tar or zip?

**Comment by twogozi** [comment]
Zip

**Comment by twogozi** [comment]
> how to display your nacos cluster? docker? tar or zip?

Zip

**Comment by KomachiSion** [comment]
Choose any node has a try with API `curl -X GET ip:port/nacos/v1/ns/service?serviceName=xxx`.

If return 403 means your auth open successfully.

**Comment by twogozi** [comment]
> Choose any node has a try with API `curl -X GET ip:port/nacos/v1/ns/service?serviceName=xxx`.
> 
> If return 403 means your auth open successfully.

My nacos configuration as follows:
1.server.servlet.contextPath=/
2.server.port=8850
3.nacos.core.auth.enabled=true
All other configurations are default and i have 3 nodes.

It returns "true" when i try to use API  curl -X POST http://127.0.0.1:8850/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=helloWorld.

It returns "helloWorld" when i try to use API curl -X GET http://127.0.0.1:8850/v1/cs/configs?dataId=nacos.cfg.dataId&group=test.

**Comment by wangweizZZ** [comment]
I think `server.servlet.contextPath=/`  trigger the error . the logic in `ControllerMethodsCache` is not good  , i will fix it

**Comment by twogozi** [comment]
> I think `server.servlet.contextPath=/` trigger the error . the logic in `ControllerMethodsCache` is not good , i will fix it

i hope you will  let me know when you fixed it so i can upgrade my nacos cluster.
thanks.

**Comment by wangweizZZ** [comment]
Maybe you can avoid the error by avoiding the use of `server.servlet.contextPath=/`, I will fix it as soon as possible

**Comment by wangweizZZ** [comment]
Need more pr to fix it completely

**Comment by KomachiSion** [comment]
ok

**Comment by wangweizZZ** [comment]
Because some front-end resources currently have hard-coded the path contextPath, it is recommended to use `/nacos` as the contextPath, and try not to use '/' . Related requirements can be controlled by components such as nginx
