### ISSUE TITLE
k8s 环境下 用nacos下使用dubbo  会连接旧的服务ip情况

### ISSUE THREAD

**Issue by Reminisd** [alibaba/nacos#4184]
# env
## spring-cloud-alibaba-dependencies:2.2.1.RELEASE
![image](https://user-images.githubusercontent.com/39513283/98619664-aea62280-233e-11eb-95d5-83933142439b.png)
# 现象
当运行时候杀死pod 导致服务的ip发生变化 可以在nacos的服务列表看到服务ip已经发生变化 但还是一直在尝试连接旧的服务ip 即被杀死的服务ip 但新的ip已经生效连接

**Comment by KomachiSion** [comment]
看下comsumer那边的nacos日志，是不是已经收到了推送，或者已经感知到了ip变化。

如果nacos已经感知了变化，那就是dubbo的问题了

**Comment by Reminisd** [comment]
> 看下comsumer那边的nacos日志，是不是已经收到了推送，或者已经感知到了ip变化。
> 
> 如果nacos已经感知了变化，那就是dubbo的问题了

感知了变化 thanks
