### ISSUE TITLE
The wrong API contains “//” created by nacos-client

### ISSUE THREAD

**Issue by melonhh** [alibaba/nacos#4185]
**Describe the bug**
My service can't registry in nacos. The error info: " failed to req API:/api//nacos/v1/ns/service/list".
I start up nacos through source code (v: 1.4.0).
But when I start up nacos through binary package downloaded from release table(v:1.3.2), there is no error.
I don't change anything in my code, and both of nacos server started up normally.
The point is why there are two '/'  in the API (/api//nacos/v1/ns/service/list).

**Expected behavior**
My server can registry itself on both of nacos  servers that started up by different way. 

**Acutally behavior**
There is a error info: failed to req API:/api//nacos/v1/ns/service/list.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by horizonzy** [comment]
did you config `nacos.naming.web.context` in your client?

**Comment by melonhh** [comment]
No， So what does the nacos.naming.web.context affect? What should I do?

**Comment by melonhh** [comment]
Is there a document about it？

**Comment by horizonzy** [comment]
can you debug in you environment. see `com.alibaba.nacos.client.naming.utils.UtilAndComs#nacosUrlBase`, watch this field's change.

**Comment by KomachiSion** [comment]
It just a show error for logs, the real uri is right.

**Comment by melonhh** [comment]
Yeah，but last night the nacos server work nice,  and my server can registry in nacos ( I'm in school). today it shows error ( I'm in another place).  So what makes the real uri  can't connect to the nacos sever?

**Comment by melonhh** [comment]
I find the real reason in the [issue#4176](https://github.com/alibaba/nacos/issues/4176);

So I get：
1. the wrong api path in the error info is just a error message， not a real uri path ( ? .. ? )
2. In fact， my nacos server that have changed ip addr start up by error because of the raft protocol

Thank you.
