### ISSUE TITLE
Please vote and comments for Nacos console UI theme&style 

### ISSUE THREAD

**Issue by xuechaos** [alibaba/nacos#42]
The community decided to add a console to the Nacos 0.3 version, and now collects a console-style design draft.

Console-style design draft should have:
1. The Nacos logo should be included on the console.
2. Clear style, suitable for programmers.
3. The interaction design is simple and practical.
4. Have a link to Nacos's official website.

The community will vote on all the candidates.

**Comment by yanlinly** [comment]
Calm style    VS  Lively style , which u vote
1. Calm style
![calm](https://user-images.githubusercontent.com/17695352/45420231-39862680-b6bc-11e8-8966-229db55e30c3.png)

2. Lively style
![lively](https://user-images.githubusercontent.com/17695352/45420270-50c51400-b6bc-11e8-934e-0d77f2ec89ad.png)

**Comment by xindoo** [comment]
Calm style

**Comment by jorrellz** [comment]
Calm style+10086

**Comment by tao1991123** [comment]
Calm style

**Comment by kexianjun** [comment]
Calm style

**Comment by crystonesc** [comment]
Calm style

**Comment by mingyixu** [comment]
Calm style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by hadoop835** [comment]
lively style

**Comment by odbozhou** [comment]
Calm style

**Comment by justlikeliuen** [comment]
Calm style

**Comment by beyond0309** [comment]
Calm style

**Comment by liangyuanpeng** [comment]
Calm style

**Comment by MarkTang** [comment]
Calm style

**Comment by MarkTang** [comment]
Calm style

**Comment by yaozg** [comment]
Calm

**Comment by yanlinly** [comment]
Calm VS lively： 15：2
use Calm style

**Comment by HaojunRen** [comment]
Calm style +1

**Comment by YoKv** [comment]
Lively style

**Comment by aCoder2013** [comment]
Lively style

**Comment by zyw** [comment]
Calm style +1

**Comment by xiaoyangW** [comment]
Calm style

**Comment by xiaoyangW** [comment]
Calm style +1

**Comment by xiaoyangW** [comment]
Calm style +1

**Comment by xiaoyangW** [comment]
Calm style +1

**Comment by kavin-J** [comment]
Calm style

**Comment by myejb22** [comment]
Calm style

**Comment by myejb22** [comment]
Calm style

**Comment by myejb22** [comment]
Calm style

**Comment by myejb22** [comment]
Calm style

**Comment by Macgrady4Ever** [comment]
Calm style + 1

**Comment by Baofengqi** [comment]
Calm style + 1

**Comment by vicrobert** [comment]
Calm style

**Comment by yanlinly** [comment]
We choose Calm style.
http://console.nacos.io/nacos/index.html
