### ISSUE TITLE
应用中的配置不能自动同步到nacos

### ISSUE THREAD

**Issue by chenlushun** [alibaba/nacos#420]
**问题描述**
应用在启动的时候，应用的本地配置，不支持自动同步到nacos

例如：

```java
    @Value("${useLocalCache:false}")
    private boolean useLocalCache;

    public void setUseLocalCache(boolean useLocalCache) {
        this.useLocalCache = useLocalCache;
    }
```

应用启动之后，配置列表看不到这个配置

**期望**
nacos是外部化配置中心，即支持配置的查看，同时也支持配置的修改
例如
应用启动之后可以在配置列表看到
```properties
useLocalCache:false
```

个人觉得在注解
```java
@EnableNacosConfig
```
之后，再做一件事情，根据需要把本地的配置同步到nacos，也就是应用启动之后，可以直接在配置列表看到
这个需求做成可配置的，效果会更好。

**Comment by yanlinly** [comment]
本地配置，初始化的时候只读取一次。 自己业务逻辑可以自动修改，不需要外部触发变更。

外部配置，初始化推送一次。 变更的时候外部触发刷新配置内容，并且触发回调业务处理。

如果外部配置变化，触发了本地配置的刷新，可能会有意外的问题。 做的稍微会过了，反而会增加理解成本。 因此从设计上我们期望是单向的，有远端用远端，没有远端用本地，没有本地用代码硬编码值。 如果反过来也相互影响，这个理解成本和风险会加大。
