### ISSUE TITLE
feature_multiple_datasource_support中的config模块下的modules的entity缺失QUsersEntity 类，环境编译不通过。

### ISSUE THREAD

**Issue by DemoMoon** [alibaba/nacos#4200]
feature_multiple_datasource_support中的config模块modules的entity目录缺失QUsersEntity 类，环境编译不通过。

**Comment by DemoMoon** [comment]
补充下，也缺失QRolesEntity,QPermissionsEntity。

**Comment by paderlol** [comment]
好，我看下

**Comment by KomachiSion** [comment]
Entity可能是自动创建的，需要检查一下

**Comment by DemoMoon** [comment]
> Entity可能是自动创建的，需要检查一下

请问是需要安装什么插件吗？谢谢

**Comment by horizonzy** [comment]
> > Entity可能是自动创建的，需要检查一下
> 
> 请问是需要安装什么插件吗？谢谢

不需要安装插件，编译生成，执行命令 `mvn compile`
