### ISSUE TITLE
使用openApi发布配置时，配置项为多个"key=value"时，怎样传值

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4201]
curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=example&group=DEFAULT_GROUP&content=useLocalCache=true"

此次请求会发布配置内容useLocalCache=true

问题：如果想发布配置
useLocalCache1=true
useLocalCache2=false

content参数该怎么传

**Comment by horizonzy** [comment]
这个和nacos无关。这个应该是nacos-spring-context相关的逻辑，nacos-spring-context中关于多个key的处理，通过\n来进行切割。

**Comment by KomachiSion** [comment]
这个和`nacos-spring-context`也无关，找个搜索引擎搜索一下curl怎么用

**Comment by wanghuigithub** [comment]
> 这个和`nacos-spring-context`也无关，找个搜索引擎搜索一下curl怎么用

我想可能我没有描述清楚问题。这个并不是curl怎么用的问题。

问题详细描述：

当我参考官网文档Nacos Spring Boot时（https://nacos.io/zh-cn/docs/quick-start-spring-boot.html），产生了一个疑问。
文章中获取配置的方式如下：
![image](https://user-images.githubusercontent.com/11936135/98892564-90c1f480-24db-11eb-9681-497068dffbe1.png)

文章中发布配置的方式如下：
![image](https://user-images.githubusercontent.com/11936135/98892656-bcdd7580-24db-11eb-966c-684ac9b0a57d.png)

问题就是，在使用@NacosValue注解获取同一dataId，同一group中的配置时（多个key）,@NacosValue是根据什么分隔符对发布的配置中的多个key进行切割的。

**Comment by horizonzy** [comment]
通过`\n`

**Comment by KomachiSion** [comment]
和配置类型有关，如果是properties就是每行一个key，json的按照json的key解析，yaml就按照yaml的key解析。
