### ISSUE TITLE
配置多个IP时出错的问题

### ISSUE THREAD

**Issue by beyondfengyu** [alibaba/nacos#4208]
今天遇到一个很奇怪的问题，使用springboot配置nacos时一直获取不到配置的数据，
` AbstractNacosPropertySourceBuilder:185] - There is no content for NacosPropertySource from dataId[test.properties]`
一开始以为是配置dataId的问题，反复检查也不是。
通过nacos api直接请求又可以获取成功，说明nacos服务器没问题，配置数据也没问题吧。
然后一直跟踪源码，找到`String[] serverAddrsArr = serverAddrsStr.split(",");`，才发现可能是配置多个ip时，使用的是【；】，而不是【，】，问题解决了。
说这么多，只是想吐槽一下nacos的异常提示，这种连ip配置错了，根本就是网络异常的情况下，居然没抛出网络异常的提示，仅仅是打印一个No content。出问题了还要翻查源码才能定位，用得真心累。

**Comment by KeRan213539** [comment]
nacos是一个开源项目,需要大家来一起完善. 与其吐槽,还不如来参与贡献,大家一起完善它

**Comment by beyondfengyu** [comment]
是的，提交需求和吐槽也是一种参与方式吧。希望维护人可以更加完善。上面的问题其实也很好解决，只是有些地方不太友好。除了抛出真实的网络异常外，另外可以在文档中注释一下server-addr属性多个ip时使用的分隔符。

**Comment by KeRan213539** [comment]
> 是的，提交需求和吐槽也是一种参与方式吧。希望维护人可以更加完善。上面的问题其实也很好解决，只是有些地方不太友好。除了抛出真实的网络异常外，另外可以在文档中注释一下server-addr属性多个ip时使用的分隔符。

文档确实是个问题,比较旧也不完善,我们也在计划解决这个问题. 欢迎你参与进来一起完善,比如就这个issue,加一些友好异常日志, 或者在文档中完善下.
文档项目(官网)在: https://github.com/nacos-group/nacos-group.github.io

**Comment by chenshun00** [comment]
:) 建议在这里加一个
```java
String[] tokenized = StringUtils.tokenizeToStringArray(xxx,",; \t\n");
```
实践中确实有的人是;有的人是,不好说，这点可以学习下Spring的 [StringUtils](https://github.com/spring-projects/spring-framework/blob/0b580d194d2390c4cb860f337e146b90ba16c6f2/spring-core/src/main/java/org/springframework/util/StringUtils.java#L1151-L1153)

**Comment by mark4z** [comment]
I will fix it, so what's the solution with it? Error log or doc?

**Comment by KeRan213539** [comment]
> I will fix it, so what's the solution with it? Error log or doc?

doc and log.
See if the URL of the request can be added to the place where the exception is thrown to facilitate troubleshooting

**Comment by mark4z** [comment]
> > I will fix it, so what's the solution with it? Error log or doc?
> 
> doc and log.
> See if the URL of the request can be added to the place where the exception is thrown to facilitate troubleshooting

ok

**Comment by mark4z** [comment]
> 今天遇到一个很奇怪的问题，使用springboot配置nacos时一直获取不到配置的数据，
> ` AbstractNacosPropertySourceBuilder:185] - There is no content for NacosPropertySource from dataId[test.properties]`
> 一开始以为是配置dataId的问题，反复检查也不是。
> 通过nacos api直接请求又可以获取成功，说明nacos服务器没问题，配置数据也没问题吧。
> 然后一直跟踪源码，找到`String[] serverAddrsArr = serverAddrsStr.split(",");`，才发现可能是配置多个ip时，使用的是【；】，而不是【，】，问题解决了。
> 说这么多，只是想吐槽一下nacos的异常提示，这种连ip配置错了，根本就是网络异常的情况下，居然没抛出网络异常的提示，仅仅是打印一个No content。出问题了还要翻查源码才能定位，用得真心累。

是哪个版本的client，可以给出一些更详细的信息吗

**Comment by beyondfengyu** [comment]
@mark4z maven: nacos-config-spring-boot-starter, 0.2.7

**Comment by mask616** [comment]
@i will solve it@
