### ISSUE TITLE
no such api:GET:/v1/ns/catalog/services

### ISSUE THREAD

**Issue by twogozi** [alibaba/nacos#4212]
1.Nacos V1.3.0
2.Nacos started successfully in cluster mode (Zip)

My nacos configuration as follows:
1.server.servlet.contextPath=/
2.server.port=8850
3.nacos.core.auth.enabled=true
All other configurations are default and i have 3 nodes.

it returns "{"timestamp":"2020-11-12T06:12:42.856+0000","status":501,"error":"Not Implemented","message":"no such api:PUT:/v1/ns/instance","path":"/v1/ns/instance"}" when i try to use api 'http://127.0.0.1:8850/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'

It works when i set server.servlet.contextPath=/nacos

**Comment by KomachiSion** [comment]
same problem with #4181

**Comment by twogozi** [comment]
> 1.Nacos V1.3.0
> 2.Nacos started successfully in cluster mode (Zip)
> 
> My nacos configuration as follows:
> 1.server.servlet.contextPath=/
> 2.server.port=8850
> 3.nacos.core.auth.enabled=true
> All other configurations are default and i have 3 nodes.
> 
> it returns "{"timestamp":"2020-11-12T06:12:42.856+0000","status":501,"error":"Not Implemented","message":"no such api:PUT:/v1/ns/instance","path":"/v1/ns/instance"}" when i try to use api 'http://127.0.0.1:8850/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
> 
> It works when i set server.servlet.contextPath=/nacos

Page prompt “no such api:GET:/v1/ns/catalog/services” when i click the menu "service list" and the config is server.servlet.contextPath=/.
It works when i set server.servlet.contextPath=/nacos.

**Comment by twogozi** [comment]
> same problem with #4181

ok,thanks. i will set server.servlet.contextPath=/nacos.
