### ISSUE TITLE
Service listening configuration in the container

### ISSUE THREAD

**Issue by sanxun0325** [alibaba/nacos#4213]
**Describe the bug**
The services in the container listen for configuration, and the IP in the nacos listen for configuration list is node ip, not pod ip

I see here com.alibaba.nacos.config.server.service#LongPollingService.addLongPollingClient() , the way to get the IP

I'm not sure if this is intentional or if it needs to be improved。
```
      String ip = RequestUtil.getRemoteIp(req);

        // Must be called by http thread, or send response.
        final AsyncContext asyncContext = req.startAsync();
        
        // AsyncContext.setTimeout() is incorrect, Control by oneself
        asyncContext.setTimeout(0L);
        
        ConfigExecutor.executeLongPolling(
                new ClientLongPolling(asyncContext, clientMd5Map, ip, probeRequestSize, timeout, appName, tag));
```

**容器中的服务 监听某一个配置，在nacos监听配置列表中的IP是node IP，而不是pod IP.
  因为服务实例中的IP是pod IP,所以导致有人会对此有些疑惑**
我在com.alibaba.nacos.config.server.service#LongPollingService.addLongPollingClient() 看到了获取ip的方式。
我不确定就是这样设计的，还是需要改进。

**Comment by sanxun0325** [comment]
If improvements are needed, you can assign them to me

**Comment by chuntaojun** [comment]
I will try to resolve it

**Comment by chuntaojun** [comment]
@sanxun0325 It does need to be optimized, so we can talk about how to optimize

@paderlol @yanlinly @TsingLiang
