### ISSUE TITLE
应用总注册不到nacos服务上（单机模式）

### ISSUE THREAD

**Issue by No-Silver-J** [alibaba/nacos#4216]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

mac单机模式启动nacos服务后，本地spring cloud 微服务配置了服务注册发现，并且配置了nacos的server-addr和namespace
，启动报错**code:503 msg: server is DOWN now, please try again later!**
检查了nacos服务启动时，start.out中日志报错**Another instance of Derby may have already booted the database /usr/local/opt/nacos/data/derby-data**. 说另个实例已经占用db了，这种情况是在我执行startup脚本后，shutdown服务，再执行startup脚本后发生的，我尝试着删了derby-data文件夹，再执行startup脚本是正常的，可我的微服务依然注册不上，想问一下有什么解决方案吗

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by horizonzy** [comment]
see #4210, the same reason.

**Comment by chuntaojun** [comment]
@No-Silver-J server是什么版本？1.4.0的话发一下alipay-jraft.log日志

**Comment by chuntaojun** [comment]
> see #4210, the same reason.

We need to analyze the error message and not assume that the cause of the error is the same

**Comment by horizonzy** [comment]
It's my carelessness
