### ISSUE TITLE
单机模式下，idea Process finished with exit code 1

### ISSUE THREAD

**Issue by sunjiaqi52100** [alibaba/nacos#4218]
下载源码后vm设置单机模式下运行
Process finished with exit code 1
求解什么原因呢

**Comment by horizonzy** [comment]
需要更多信息。相关日志有吗，在你的用户目录下的nacos/logs/nacos.log中应该能看到信息

**Comment by KomachiSion** [comment]
用的那个class作为启动类？

**Comment by sunjiaqi52100** [comment]
> 用的哪个class作为启动类？

console下的nacos类为启动类，昨天怎么调也没用，最后不知道为什么好了，能起来了，然后还会偶尔出现这种问题，运行不稳定

**Comment by KomachiSion** [comment]
没有遇到过直接退出的问题， 如果出现的话一定会伴随spring的报错信息。如果您无法提供的话，就只能您自己排查一下环境信息了。

**Comment by KomachiSion** [comment]
The author do not response for a long time, and current information is not enough to judge the problem. So close issue.
