### ISSUE TITLE
3台nacos集群，为什么有2个leader的存在？这样会有影响吗？

### ISSUE THREAD

**Issue by fangdengfu** [alibaba/nacos#4221]
3台nacos集群，为什么有2个leader的存在？这样会有影响吗？

![image](https://user-images.githubusercontent.com/26423956/99014366-8ceeaa80-258d-11eb-8c4f-10f0a063ce44.png)
![image](https://user-images.githubusercontent.com/26423956/99014430-98da6c80-258d-11eb-825b-d7d8b729ff19.png)
![image](https://user-images.githubusercontent.com/26423956/99014463-a68ff200-258d-11eb-8544-c14f1debafc5.png)

**Comment by ChasingInTheWind** [comment]
#3384

**Comment by fangdengfu** [comment]
感谢
