### ISSUE TITLE
2个微服务注册在Nacos上，Group分别是A和B，那么A分组下得服务可以和B分组下的服务互相访问吗（The two micro services are registered in Nacos, and the Group is A and B respectively. So can the services under Group A and the services under Group B access each other?）

### ISSUE THREAD

**Issue by spurtAndy** [alibaba/nacos#4222]
2个微服务注册在Nacos上，Group分别是A和B，那么A分组下得服务可以和B分组下的服务互相访问吗？

The two micro services are registered in Nacos, and the Group is A and B respectively. So can the services under Group A and the services under Group B access each other?

**Comment by fangdengfu** [comment]
只要是一个nacos注册中心，应该都是可以的。
每个服务从nacos获取服务列表，只要是一个namespace下的，应该都能获取到。只要有服务列表，都可以通过协议调用得到具体的服务。所以理论上都是可以相互访问的。
我目前只是把group做功能上的分组用，没做其它的特殊用途。

**Comment by horizonzy** [comment]
> 2个微服务注册在Nacos上，Group分别是A和B，那么A分组下得服务可以和B分组下的服务互相访问吗？
> 
> The two micro services are registered in Nacos, and the Group is A and B respectively. So can the services under Group A and the services under Group B access each other?

相互访问是什么意思。

**Comment by KomachiSion** [comment]
可以的，只要是同一个namsepace下面的就可以通过nacos发现到，能不能互相访问看的是Group A和B的网络是否通畅，和nacos关系不大。

**Comment by spurtAndy** [comment]
@KomachiSion  我试了下，如果在同一个namespce下，不同group，无法获取到对方Group的服务列表，应该是隔离的。

**Comment by fangdengfu** [comment]
> @KomachiSion 我试了下，如果在同一个namespce下，不同group，无法获取到对方Group的服务列表，应该是隔离的。

你是配权限了吗，我们这里目前没有配置权限，都是可以访问的

**Comment by goddman** [comment]
不同分组之间 是隔离的

**Comment by horizonzy** [comment]
主要是看你的消费者主不主动设置cluster，如果不设置cluster，会拿service下面所有的instances。如果设置了cluster，只会去拿固定cluster下的instances

**Comment by goddman** [comment]
> 主要是看你的消费者主不主动设置cluster，如果不设置cluster，会拿service下面所有的instances。如果设置了cluster，只会去拿固定cluster下的instances
我刚接触nacos,设置cluster没理解什么意思.  集群模式跟单例模式我测试不同group都是隔离的.在配置里有个clusterName的配置,配置了也访问不了不同的group
