### ISSUE TITLE
DNS问题

### ISSUE THREAD

**Issue by HiFangfangXu** [alibaba/nacos#4226]
请问
nacos的DNS默认是启用的吗，端口值是多少
不是启用的如何启用呢

**Comment by horizonzy** [comment]
你是看到nacos有DNS功能吗？
DNS是通过持久化服务来实现的，获取DNS服务的所有实例即可。并没有什么单独端口之类的

**Comment by chuntaojun** [comment]
这个功能移步到这个项目：https://github.com/nacos-group/nacos-coredns-plugin

**Comment by spacewander** [comment]
Look like nacos-group/nacos-coredns-plugin is dead?
It can't even be compiled: https://github.com/nacos-group/nacos-coredns-plugin/issues/18
