### ISSUE TITLE
mac big sur 好像不能启动nacos了

### ISSUE THREAD

**Issue by nihaoye1995** [alibaba/nacos#4227]
使用mac更新了big sur系统后，打开nacos，显示成功了，但实际上没有开启
![image](https://user-images.githubusercontent.com/34436468/99137913-c85da780-2667-11eb-8bd6-9df9ec8d8d66.png)

**Comment by liuhaha2020** [comment]
我也是，昨天更新了11.0.1，nacos server 启动突然报 no such /Library/Internet，然后我去创建了相应的目录，又报permission deenied，我去chmod -R 777之后没用，还是报没有权限

**Comment by liuhaha2020** [comment]
<img width="570" alt="WechatIMG260" src="https://user-images.githubusercontent.com/68731715/99138071-04ddd300-2669-11eb-9b47-e04f1e24e792.png">
<img width="570" alt="WechatIMG259" src="https://user-images.githubusercontent.com/68731715/99138076-0c04e100-2669-11eb-8a55-042803ff930b.png">

**Comment by nihaoye1995** [comment]
我的是显示成功了，但是，实际没成功

**Comment by liuhaha2020** [comment]
之前的MacOS版本都没有这个问题

**Comment by liuhaha2020** [comment]
你加我vx 15372007435

**Comment by forestasen** [comment]
我的也一样，更新了big sur后，启动不了了，和你的错误一样

**Comment by liuhaha2020** [comment]
> 我的也一样，更新了big sur后，启动不了了，和你的错误一样

救救孩子叭😭

**Comment by horizonzy** [comment]
有相关的报错信息吗。

**Comment by liuhaha2020** [comment]
> 有相关的报错信息吗。

报错信息就是 no such /Library/Internet 然后创建了这个文件夹之后再启动就是没有权限 给了权限之后再启动 还是报没有权限

**Comment by horizonzy** [comment]
贴一下相关日志。

**Comment by liuhaha2020** [comment]
![image](https://user-images.githubusercontent.com/68731715/99143132-1be6ea00-2696-11eb-9841-c4ab33231fc8.png)
![image](https://user-images.githubusercontent.com/68731715/99143145-34ef9b00-2696-11eb-977f-7a3192610556.png)
![image](https://user-images.githubusercontent.com/68731715/99143160-45077a80-2696-11eb-9dc0-65e4d0327037.png)


> 贴一下相关日志。

**Comment by liuhaha2020** [comment]
> ![image](https://user-images.githubusercontent.com/68731715/99143132-1be6ea00-2696-11eb-9841-c4ab33231fc8.png)
> ![image](https://user-images.githubusercontent.com/68731715/99143145-34ef9b00-2696-11eb-977f-7a3192610556.png)
> ![image](https://user-images.githubusercontent.com/68731715/99143160-45077a80-2696-11eb-9dc0-65e4d0327037.png)
> 
> > 贴一下相关日志。

然后就是根据提示去创建这个目录，创建了目录之后报这个Internet文件夹permission deenied，我去chmod -R 777 了之后还是报没有权限

**Comment by horizonzy** [comment]
我认为是big sur 改变了nohup: 的实现方式。你那边能正常使用nohup启动一个其他程序吗。

**Comment by liuhaha2020** [comment]
> 我认为是big sur 改变了nohup: 的实现方式。你那边能正常使用nohup启动一个其他程序吗。

稍等  我试一下

**Comment by liuhaha2020** [comment]
> 我认为是big sur 改变了nohup: 的实现方式。你那边能正常使用nohup启动一个其他程序吗。

![image](https://user-images.githubusercontent.com/68731715/99143462-ac262e80-2698-11eb-9be7-47e715b47b28.png)
可以启动

**Comment by horizonzy** [comment]
> > 我认为是big sur 改变了nohup: 的实现方式。你那边能正常使用nohup启动一个其他程序吗。
> 
> ![image](https://user-images.githubusercontent.com/68731715/99143462-ac262e80-2698-11eb-9be7-47e715b47b28.png)
> 可以启动

你先自己摸索一会儿呢，晚上我帮忙看看

**Comment by liuhaha2020** [comment]
> > > 我认为是big sur 改变了nohup: 的实现方式。你那边能正常使用nohup启动一个其他程序吗。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/68731715/99143462-ac262e80-2698-11eb-9be7-47e715b47b28.png)
> > 可以启动
> 
> 你先自己摸索一会儿呢，晚上我帮忙看看

🥷🥷

**Comment by JonyChan** [comment]
并且SVN也没有了，就很无语

**Comment by horizonzy** [comment]
> > > > 我认为是big sur 改变了nohup: 的实现方式。你那边能正常使用nohup启动一个其他程序吗。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/68731715/99143462-ac262e80-2698-11eb-9be7-47e715b47b28.png)
> > > 可以启动
> > 
> > 
> > 你先自己摸索一会儿呢，晚上我帮忙看看
> 
> 🥷🥷

可能日志显示的有问题，你看下日志里面的nacos.member.list。nohup可能提示的信息有误，可能是这个文件夹/Library/Internet Plug-Ins/.......

**Comment by liuhongfeng** [comment]
> 我也是，昨天更新了11.0.1，nacos server 启动突然报 no such /Library/Internet，然后我去创建了相应的目录，又报permission deenied，我去chmod -R 777之后没用，还是报没有权限

@liuhaha2020 你那边 Mac 上的 Java 环境变量，应该用的是系统自带的 JDK，升级到 `macOS 11.0.1` 系统后，遇到和你一样的问题。

解决办法：`/usr/libexec/java_home -V`检查下 JDK 安装路径，有单独安装过 JDK 的话，将 Java 环境变量配置成单独安装的 JDK，没有安装过的话，去官网下载一个 Mac 版的 JDK ，再配置下环境变量，最后启动 Nacos 即可。

**Comment by 501956430** [comment]
这个问题应该说是nacos 不能识别mac 环境jdk路径空行转译导致寻找jdk路径错误。
Nacos应该处理修复一下这个问题吧mac big sur  都有这个问题

**Comment by liuhongfeng** [comment]
> 这个问题应该说是nacos 不能识别mac 环境jdk路径空行转译导致寻找jdk路径错误。
> Nacos应该处理修复一下这个问题吧mac big sur 都有这个问题

是这样的，在 `macOS 11.0.1` 系统上
`/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` 这样的 `Internet Plug-Ins` 存在空格的 JDK 路径无法识别，`macOS 11.0.1` 之前的系统可以识别。

`/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home` 单独安装的 JDK 路径识别没有问题。

**Comment by horizonzy** [comment]
> > 这个问题应该说是nacos 不能识别mac 环境jdk路径空行转译导致寻找jdk路径错误。
> > Nacos应该处理修复一下这个问题吧mac big sur 都有这个问题
> 
> 是这样的，在 `macOS 11.0.1` 系统上
> `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` 这样的 `Internet Plug-Ins` 存在空格的 JDK 路径无法识别，`macOS 11.0.1` 之前的系统可以识别。
> 
> `/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home` 单独安装的 JDK 路径识别没有问题。

这么看起来这个应该是操作系统的问题吧。只要目录中包含了空格了，mac的shell都无法识别到

**Comment by duanhairuo** [comment]
很多软件都会出问题，big sur 改变了 /usr/libexec/java_home -V的输出结果，解决方案

JAVA_HOME=`/usr/libexec/java_home -V 2>&1 | grep '^[[:space:]]' | grep jdk | awk '{print $NF}'`

**Comment by 501956430** [comment]
> > 这个问题应该说是nacos 不能识别mac 环境jdk路径空行转译导致寻找jdk路径错误。
> > Nacos应该处理修复一下这个问题吧mac big sur 都有这个问题
> 
> 是这样的，在 `macOS 11.0.1` 系统上
> `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home` 这样的 `Internet Plug-Ins` 存在空格的 JDK 路径无法识别，`macOS 11.0.1` 之前的系统可以识别。
> 
> `/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home` 单独安装的 JDK 路径识别没有问题。

貌似windows Program Files 路径中同样有空格

**Comment by horizonzy** [comment]
这个是mac新系统的问题，如果没有手动配置$JAVA_HOME的话，用默认的JAVA_HOME，存在空格。导致shell执行失败，手动指定一个自己的JAVA_HOME就OK

**Comment by KomachiSion** [comment]
我觉得这问题和nacos没有关系，nacos启动脚本读取的就是JAVA_HOME，mac OS新版本默认JAVA_HOME加了空格，如果不进行特殊化处理，应该所有java启动脚本都会有问题。而且由启动脚本来处理JAVA_HOME不太合理，读取到JAVA_HOME就应该直接使用。

**Comment by liuhaha2020** [comment]
> 这个是mac新系统的问题，如果没有手动配置$JAVA_HOME的话，用默认的JAVA_HOME，存在空格。导致shell执行失败，手动指定一个自己的JAVA_HOME就OK

![image](https://user-images.githubusercontent.com/68731715/99348889-98b3d700-28d5-11eb-9621-d08ee6a7218c.png)

**Comment by liuhaha2020** [comment]
> /usr/libexec/java_home -V

![image](https://user-images.githubusercontent.com/68731715/99349151-39a29200-28d6-11eb-8f90-61f1f0946c81.png)

**Comment by horizonzy** [comment]
> > 这个是mac新系统的问题，如果没有手动配置$JAVA_HOME的话，用默认的JAVA_HOME，存在空格。导致shell执行失败，手动指定一个自己的JAVA_HOME就OK
> 
> ![image](https://user-images.githubusercontent.com/68731715/99348889-98b3d700-28d5-11eb-9621-d08ee6a7218c.png)

JVA_HOME -> JAVA_HOME

**Comment by liuhaha2020** [comment]
> > > 这个是mac新系统的问题，如果没有手动配置$JAVA_HOME的话，用默认的JAVA_HOME，存在空格。导致shell执行失败，手动指定一个自己的JAVA_HOME就OK
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/68731715/99348889-98b3d700-28d5-11eb-9621-d08ee6a7218c.png)
> 
> JVA_HOME -> JAVA_HOME

挖槽。。。。。。。。。。

**Comment by liuhaha2020** [comment]
上面👆的各位同仁 孩子错了🙇 
BigSur的版本JAVA_Machines系统自带的路径是/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
但是我的电脑买回来之后我重新下载了第二个java，但是JAVA_HOME路径我粗心，写成了JVA_HOME😅
所以导致nacos启动时是使用系统自带的java启动的
![image](https://user-images.githubusercontent.com/68731715/99349901-06f99900-28d8-11eb-9e6f-f12e01890f62.png)
但是由于nacos启动可能是解析不了空格（也许是应为别的），所以导致nacos本身是没有任何报错的，而是nohup或者别的一些什么启动不起来

**Comment by thtns** [comment]
![image](https://user-images.githubusercontent.com/11975717/99471403-6c559480-2981-11eb-974f-c00036891ef2.png)
我重新指定了下java_home

**Comment by JonyChan** [comment]
下载一个新的JDK安装一下，根据上面的步骤在bash_profile中加入JAVA_HOME的位置就OK了

**Comment by whh1009** [comment]
我用的是自己配置的jdk，也是启不来。。。
还是提示：nohup: /Library/Internet: No such file or directory

**Comment by forestasen** [comment]
> 我用的是自己配置的jdk，也是启不来。。。
> 还是提示：nohup: /Library/Internet: No such file or directory

你用的bash还是zsh，如果用的zsh，把路径配置写在.zshrc里就可以了

**Comment by heguitang1214** [comment]
echo $SHELL 查看当前系统使用的shell，如果是/bin/zsh，JAVA_HOME需要配置到~/.zshrc中

**Comment by sdywcd** [comment]
1,如果你的系统偏好设置里面有java，在最底下有一个java控制界面。这个界面里的java的路径就在/Library/Internet plugin下面，这里的空格应该就是造成无法启动的原因
2，同时你也自己配置过jdk的，/usr/libexec/java_home -V 这个行这个命令你会得到2个jdk路径
3，nacos在启动的时候，应该是拿了第一个输出的jdk路径。所以会因为1的原因造成启动失败。所以我就粗暴的删除了/Library/Internet plugin下的jdk，只用自己配置的jdk
<img width="335" alt="WX20201209-153904@2x" src="https://user-images.githubusercontent.com/1400008/101599442-bb4c9200-3a34-11eb-9328-fe07bd4990f4.png">

4，然后你在启动nacos就可以了【大概你需要重启下系统】

**Comment by DokiYoloo** [comment]
应该是环境变量导致的
装完系统后 也是遇到这个
`echo $JAVA_HOME`
打印出来是空白 然后执行了下
source ~/.bash_profile
就OK了

**Comment by DokiYoloo** [comment]
补充:
可以直接将`/Library/Internet Plug-Ins/JavaAppletPlugin.plugin`重命名为`JavaAppletPlugin.plugin.bak`

**Comment by dave0824** [comment]
我这也出现了这样的问题，提示启动成功后并不能启动。我可以确认的是不是Java环境的问题：
<img width="573" alt="截屏2021-06-29 21 53 05" src="https://user-images.githubusercontent.com/51199302/123809715-6c107500-d924-11eb-84df-7459cb347006.png">
nacos 的版本是 2.0.1 Mac系统版本是：big sur 11.4
以下是打印的错误日志：
<img width="1440" alt="截屏2021-06-29 21 56 27" src="https://user-images.githubusercontent.com/51199302/123810405-f0fb8e80-d924-11eb-9112-45972d34c905.png">

**Comment by zlq0527** [comment]
> 我这也出现了这样的问题，提示启动成功后并不能启动。我可以确认的是不是Java环境的问题： <img alt="截屏2021-06-29 21 53 05" width="573" src="https://user-images.githubusercontent.com/51199302/123809715-6c107500-d924-11eb-84df-7459cb347006.png"> nacos 的版本是 2.0.1 Mac系统版本是：big sur 11.4 以下是打印的错误日志： <img alt="截屏2021-06-29 21 56 27" width="1440" src="https://user-images.githubusercontent.com/51199302/123810405-f0fb8e80-d924-11eb-9112-45972d34c905.png">

问题解决了吗

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
