### ISSUE TITLE
springboot方式如何使用namespace

### ISSUE THREAD

**Issue by walyuuc** [alibaba/nacos#423]
版本0.6.0
先在控制台创建一个命名空间test，在此空间下新建配置，及配置内容
本地配置文件增加，nacos.config.namespace=xxx
启动报错，无法解析配置Could not resolve placeholder 'xxx' in value "${xxx}"
(此前用public命名空间是可以的)

**Comment by YaoC** [comment]
Current Nacos does not support namespace name, see  #297

**Comment by yanlinly** [comment]
public是一个公共空间，命名空间id是空串。
这块需要传入命名空间id。 请稍微注意一下~
