### ISSUE TITLE
Tool class replacement for environment variable reading

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#4232]
**Is your feature request related to a problem? Please describe.**
Tool class replacement for environment variable reading

ApplicationUtil => EnvUtil

**Describe the solution you'd like**

All Environment operations are handled by EnvUtil, Some methods in EnvUtil, ApplicationUtil no longer takes over

**Describe alternatives you've considered**

**Additional context**

**Comment by horizonzy** [comment]
I will solve it.

**Comment by Maijh97** [comment]
@horizonzy Have finished?

**Comment by horizonzy** [comment]
yes.

**Comment by horizonzy** [comment]
close it
