### ISSUE TITLE
因为nacos的登录uri里包含#,nginx无法读取到nacos#后的uri

### ISSUE THREAD

**Issue by zhaolie1989** [alibaba/nacos#4234]
nginx配置如下:
upstream cluster{
    server localhost:8848;
    server localhost:8849;
    server localhost:8850;
}

server {
    listen       1111;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        #root   /usr/share/nginx/html;
        #index  index.html index.htm;
        proxy_pass  http://cluster;
    }
}

使用nginx代理访问:http://localhost:1111/nacos/#/login一直报502
因为#在nginx中为注释标签,nacos登录uri中带有#后的内容无法被nginx获取,并且在#在nginx中无法被转义

2020/11/15 15:09:42 [warn] 22#22: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /nacos/ HTTP/1.1", upstream: "http://127.0.0.1:8849/nacos/(这里因为有#号读取不到)", host: "192.168.51.197:1111"

![image](https://user-images.githubusercontent.com/49927962/99189025-035ff800-279a-11eb-9ef1-ca1fb68f5306.png)
![image](https://user-images.githubusercontent.com/49927962/99189039-24c0e400-279a-11eb-8429-b95a587eac15.png)
![image](https://user-images.githubusercontent.com/49927962/99189064-45893980-279a-11eb-9378-afc3522237be.png)

**Comment by sanxun0325** [comment]
@zhaolie1989 nginx 不应该只代理login接口吧。 你可以配置成 http://cluster; 代理转发全部接口

**Comment by zhaolie1989** [comment]
> @zhaolie1989 nginx 不应该只代理login接口吧。 你可以配置成 http://cluster; 代理转发全部接口

是配置成了http://cluster,一直显示502,根本跳不掉登录页面.找了半天原因应该是#后的url nginx识别不出,所以无法登录

**Comment by KomachiSion** [comment]
#应该是前端框架加的，我以前也用过，nginx应该是可以接收的，但是我不清楚如何配置，得麻烦查下资料

**Comment by sanxun0325** [comment]
> > @zhaolie1989 nginx 不应该只代理login接口吧。 你可以配置成 http://cluster; 代理转发全部接口
> 
> 是配置成了[http://cluster,一直显示502,根本跳不掉登录页面.找了半天原因应该是#后的url](http://cluster,%E4%B8%80%E7%9B%B4%E6%98%BE%E7%A4%BA502,%E6%A0%B9%E6%9C%AC%E8%B7%B3%E4%B8%8D%E6%8E%89%E7%99%BB%E5%BD%95%E9%A1%B5%E9%9D%A2.%E6%89%BE%E4%BA%86%E5%8D%8A%E5%A4%A9%E5%8E%9F%E5%9B%A0%E5%BA%94%E8%AF%A5%E6%98%AF#%E5%90%8E%E7%9A%84url) nginx识别不出,所以无法登录

看你最后的配置http://cluster/,试试把最后的斜线去掉
