### ISSUE TITLE
跨命名空间配置

### ISSUE THREAD

**Issue by moayi** [alibaba/nacos#4242]
config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: 85f797c2-72a4-4c4b-95c6-026d25e95ae3
        group: DEV
        ext-config[0]:
          namespace: a3cc08c5-8cbb-40a2-95a6-9169c3887fd5
          data‐id: common-datasource.yaml
          group: DEV
          refresh: true
        ext-config[1]:
          namespace: a3cc08c5-8cbb-40a2-95a6-9169c3887fd5
          data‐id: common-redis.yaml
          group: DEFAULT_GROUP
          refresh: true
后期nacos支持这种跨命名空间获取配置信息吗？

**Comment by KomachiSion** [comment]
目前没有计划支持。  从设计上来说一个应用就只属于一个ns。 跨ns之后，ns的隔离意义就不大了
