### ISSUE TITLE
Macos big sur  nacos startup failed

### ISSUE THREAD

**Issue by thtns** [alibaba/nacos#4251]
**Desktop (please complete the following information):**
 - OS: [macOS big sur    11.0.1]
 - Version [nacos-server 1.4.0]

**Additional context**
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/ifugle/File/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/ifugle/File/nacos/plugins/health,/Users/ifugle/File/nacos/plugins/cmdb -Dnacos.home=/Users/ifugle/File/nacos -jar /Users/ifugle/File/nacos/target/nacos-server.jar  --spring.config.location=file:/Users/ifugle/File/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/Users/ifugle/File/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

nohup: /Library/Internet: No such file or directory

**Comment by KomachiSion** [comment]
duplicate with #4227.
