### ISSUE TITLE
Nacos-Server HealthCheck Not Contains db-check

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/nacos#4254]
**Describe the bug**

在k8s环境上，启动了3个节点的Nacos-Server组成集群，正常运行了一段时间
某天突然出现了部分服务访问Nacos-Server返回失败的情况
检查Nacos-Server日志发现，Nacos-Server 3个节点中的1个节点访问数据库一直处于失败状态
但是Nacos-Server的健康检查 /nacos/actuator/health一直处于up状态
重启该问题节点解决问题

复现该问题：
Docker启动单节点Nacos-Server连接单台Docker版MySQL
Nacos-Server 在环境变量中management.endpoint.health.show-details=always
Nacos-Server正常提供服务，访问Nacos-Server的spring健康检查端点返回值为
{
  “status” : "UP",
  "datails": {
      "diskSpace": {
          “status” : "UP",
           "details" : {
                        ignored
            }
       }
  }
}
未包含
“db”: {
  "status" : "UP",
  "details" : {
      "database" : "MySQL",
      "hello" : "1"
  }
}

**Expected behavior**

希望的是节点出现数据库访问异常情况时，可以返回 “db” :  { "status" : "DOWN" }
利用k8s的livenessProbe直接通过返回状态码把异常节点杀掉重启

**Acutally behavior**
A clear and concise description of what you actually to happen.
/nacos/actuator/health仍然返回的是up 

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

Nacos-Server 1.3.0
Nacos-Client  1.3.0

**Comment by KomachiSion** [comment]
服务模块不强制依赖数据库，除非开启了鉴权，而且nacos来返回db信息，不合理。只能返回自身是否能提供服务。

如果您说up状态但是调用用问题，麻烦把对应的问题发出来，看下是使用问题还是服务有问题。

**Comment by chuntaojun** [comment]
nacos自己有一个接口/nacos/v1/cs/health，用于检查nacos和db之间的链接情况

**Comment by MagakiReimu** [comment]
> 服务模块不强制依赖数据库，除非开启了鉴权，而且nacos来返回db信息，不合理。只能返回自身是否能提供服务。
> 
> 如果您说up状态但是调用用问题，麻烦把对应的问题发出来，看下是使用问题还是服务有问题。

并不是说让Nacos返回数据库的健康状态，而是希望Nacos能返回数据库连接池的健康状态
实际情况是运行中的Nacos-Server集群中有一个节点，一直在抛出连接数据库异常，无法正常提供Config的服务
k8s的健康检查使用的/nacos/actuator/health，一直返回的 200 Status : UP，不会Remove掉这个异常的Pod，并重新拉起一个新的
请求被K8s的有状态负载均衡到这个异常节点的服务就会一直报错，启动失败

**Comment by KomachiSion** [comment]
/nacos/actuator/health 探测的应该是nacos集群健康状况把，如果config有问题但是naming是正常的，/nacos/actuator/health这个值也应该返回Down吗？

**Comment by MagakiReimu** [comment]
> /nacos/actuator/health 探测的应该是nacos集群健康状况把，如果config有问题但是naming是正常的，/nacos/actuator/health这个值也应该返回Down吗？

@KomachiSion 
Spring-Cloud项目，naming跟config一起用，nacos-config会不停的访问nacos-server获取config的MD5
这时nacos-server异常会导致nacos-client的config一直在报错，actuator/health/nacosConfig status会变成DOWN，health Status也会变成DOWN，进而使K8s认为服务不可用，重新拉起新的容器
虽然这个问题是由于没有在客户端使用endpoint，只配置了server-address，导致没有对naocs-server集群轮询config导致的
但是server端的异常pod没有被重启，仍会存在隐患

**Comment by chuntaojun** [comment]
你这个是客户端的“actuator/health/nacosConfig”，nacos-server端的健康状态不应该影响服务应用的正在运行，nacos-client本身是做了容灾处理的，你应该将服务应用的Pod健康探针重新设计过，服务应用的“actuator/health/nacosConfig”应该作为一个告警手段，而不是作为Pod的健康探针策略

**Comment by KomachiSion** [comment]
那是否应该像 @chuntaojun 所说的，修改k8s的健康检查接口成`actuator/health/nacosConfig`， `/nacos/actuator/health`是nacos本身是否健康，返回Up没有问题。只是在处理config请求的过程中，由于连接db失败导致处理失败，nacos是正常接受请求并处理的。

**Comment by KomachiSion** [comment]
那是否应该像 @chuntaojun 所说的，修改k8s的健康检查接口成`actuator/health/nacosConfig`， `/nacos/actuator/health`是nacos本身是否健康，返回Up没有问题。只是在处理config请求的过程中，由于连接db失败导致处理失败，nacos是正常接受请求并处理的。
