### ISSUE TITLE
nacos server 部署服务器cpu/内存占用过高，正常吗？

### ISSUE THREAD

**Issue by j2ee-haydon** [alibaba/nacos#4255]
4核16G的服务器，单机模式启动nacos server，cpu占用吕20%左右，相比eureka、spring config两个服务部署都仅有1%左右，这个是否属于正常情况？

**Comment by KomachiSion** [comment]
麻烦根据issue模版填写问题描述，否则缺少的信息太多了，无法判断。

**Comment by j2ee-haydon** [comment]
![image](https://user-images.githubusercontent.com/12794749/99508956-24a22d80-29c0-11eb-9be1-d3ab2e831a96.png)

**Comment by sanxun0325** [comment]
@j2ee-haydon 正常来说cpu利用率不会这么高的。 可以使用通过日志或工具分析一下nacos 进程下哪些线程资源消耗高。尽量多提供一些这样的信息。

**Comment by sanxun0325** [comment]
same question:https://github.com/alibaba/nacos/issues/4268
