### ISSUE TITLE
com.alibaba.nacos.sys.env.EnvUtil#getApplicationConfFileResource logic problem

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4258]
**Describe the bug**
the config file will be `nullapplication.properties`  when `-Dspring.config.location` is not set.
If `-Dspring.config.location` not set, we shouldn't load resource from file system.

**Comment by KomachiSion** [comment]
For my test, there is no problem when I don't set spring.config.location. Which situation does reproduce?

**Comment by horizonzy** [comment]
It's my expression problem. I think, if user didn't set -Dspring.config.loocation, should use `/application.properties` as default stream resource directly. Instead of load `nullapplication.properties`, the file is not exist, then load  `/application.properties` as stream resource.

**Comment by KomachiSion** [comment]
If no spring.config.location set, it should use application.properties in classpath, it seems that we have specified the ${nacos.home}/conf as the classpath, nacos should load application.properties from ${nacos.home}/conf first.

**Comment by horizonzy** [comment]
agree.

**Comment by KomachiSion** [comment]
> If no spring.config.location set, it should use application.properties in classpath, it seems that we have specified the ${nacos.home}/conf as the classpath, nacos should load application.properties from ${nacos.home}/conf first.

So now your PR means that the behavior is not what's we discribe?

**Comment by wangweizZZ** [comment]
The current startup script setting path is 
> export DEFAULT_SEARCH_LOCATIONS="classpath:/,classpath:/config/,file:./,file:./config/"
export CUSTOM_SEARCH_LOCATIONS=file:${BASE_DIR}/conf/,${DEFAULT_SEARCH_LOCATIONS}

like  `--spring.config.location=file:/Users/xxxx/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/`

And always load wrong path 
>   private static Resource getCustomFileResource() {
        String path = getProperty("spring.config.location");
        if (StringUtils.isNotBlank(path) && path.contains(FILE_PREFIX)) {
            String[] paths = path.split(",");
            **path = paths[paths.length - 1].substring(FILE_PREFIX.length());**
            return getRelativePathResource(path, "application.properties");
        }
        return null;
    }

Can we remove `DEFAULT_SEARCH_LOCATIONS` directly?

**Comment by horizonzy** [comment]
I think it can be remove.  In the code logic, we just load the last file:/ to load, just one file will effect. We already use `com.alibaba.nacos.sys.env.EnvUtil#getDefaultResource` to cover `DEFAULT_SEARCH_LOCATIONS`

**Comment by horizonzy** [comment]
> The current startup script setting path is
> 
> > export DEFAULT_SEARCH_LOCATIONS="classpath:/,classpath:/config/,file:./,file:./config/"
> > export CUSTOM_SEARCH_LOCATIONS=file:${BASE_DIR}/conf/,${DEFAULT_SEARCH_LOCATIONS}
> 
> like `--spring.config.location=file:/Users/xxxx/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/`
> 
> And always load wrong path
> 
> > private static Resource getCustomFileResource() {
> > String path = getProperty("spring.config.location");
> > if (StringUtils.isNotBlank(path) && path.contains(FILE_PREFIX)) {
> > String[] paths = path.split(",");
> > **path = paths[paths.length - 1].substring(FILE_PREFIX.length());**
> > return getRelativePathResource(path, "application.properties");
> > }
> > return null;
> > }
> 
> Can we remove `DEFAULT_SEARCH_LOCATIONS` directly?

@KomachiSion @chuntaojun

**Comment by horizonzy** [comment]
> The current startup script setting path is
> 
> > export DEFAULT_SEARCH_LOCATIONS="classpath:/,classpath:/config/,file:./,file:./config/"
> > export CUSTOM_SEARCH_LOCATIONS=file:${BASE_DIR}/conf/,${DEFAULT_SEARCH_LOCATIONS}
> 
> like `--spring.config.location=file:/Users/xxxx/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/`
> 
> And always load wrong path
> 
> > private static Resource getCustomFileResource() {
> > String path = getProperty("spring.config.location");
> > if (StringUtils.isNotBlank(path) && path.contains(FILE_PREFIX)) {
> > String[] paths = path.split(",");
> > **path = paths[paths.length - 1].substring(FILE_PREFIX.length());**
> > return getRelativePathResource(path, "application.properties");
> > }
> > return null;
> > }
> 
> Can we remove `DEFAULT_SEARCH_LOCATIONS` directly?

create new issue.
