### ISSUE TITLE
Nacos permission Bug

### ISSUE THREAD

**Issue by 309283175** [alibaba/nacos#4262]
turn on auth system, create new role ROLE_TEST,then add public resource to ROLE_TEST with rw,the data in table permissions  is:

```
role	       resource	action
ROLE_TEST	:*:*	rw
```

com.alibaba.nacos.console.security.nacos.roles.NacosRoleServiceImpl.hasPermission()
```
 String permissionResource = permissionInfo.getResource().replaceAll("\\*", ".*");
 String permissionAction = permissionInfo.getAction();
  if (permissionAction.contains(permission.getAction()) &&
       Pattern.matches(permissionResource, permission.getResource())) {
        return true;
 }
```

if i use spring.cloud.nacos.username=test register my service to nacos with public namespace,my resource is "public:DEFAULT_GROUP:naming/my-service",but the parttern is ```:.*:.*``` , **Pattern.matches(permissionResource, permission.getResource())** shoud be **true** but **false**

com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([x.x.x.x:8848]) tried: ErrCode:403, ErrMsg: authorization failed!

**Comment by horizonzy** [comment]
Hi, did you bind user `test` with role `ROLE_TEST`.

**Comment by 309283175** [comment]
@horizonzy  of course i bind user `test` with role `ROLE_TEST`.

**Comment by 309283175** [comment]
@horizonzy ,As i mentioned above ,this bug only appear with user not have `ROLE_ADMIN` and want register to public namespace.

**Comment by horizonzy** [comment]
I will have a try to reproduce it.

**Comment by sanxun0325** [comment]
when public resource permissions are set, the permissionResource should be `public:.*:.*`

**Comment by 309283175** [comment]
@sanxun0325  I have tried to modify the resource record of the database `:*:*` to `public:*:*` directly. The service registration is successful. but it has caused another problem when I log in to the console with the test user and select the public namespace, a warning of no permission will appear。

**Comment by sanxun0325** [comment]
> @sanxun0325 I have tried to modify the resource record of the database `:*:*` to `public:*:*` directly. The service registration is successful. but it has caused another problem when I log in to the console with the test user and select the public namespace, a warning of no permission will appear。

nacos server version can be tried with 1.4.0, which fixes the console problem

**Comment by 309283175** [comment]
> > @sanxun0325 I have tried to modify the resource record of the database `:*:*` to `public:*:*` directly. The service registration is successful. but it has caused another problem when I log in to the console with the test user and select the public namespace, a warning of no permission will appear。
> 
> nacos server version can be tried with 1.4.0, which fixes the console problem

ok,I will try it with 1.4.0

**Comment by horizonzy** [comment]
> when public resource permissions are set, the permissionResource should be `public:.*:.*`

maybe this situation need more thought. If config module, if publishConfig without namespace, it will cause problem.

**Comment by sanxun0325** [comment]
> > when public resource permissions are set, the permissionResource should be `public:.*:.*`
> 
> maybe this situation need more thought. If config module, if publishConfig without namespace, it will cause problem.

Yes, more testing is needed

**Comment by 309283175** [comment]
> > when public resource permissions are set, the permissionResource should be `public:.*:.*`
> 
> maybe this situation need more thought. If config module, if publishConfig without namespace, it will cause problem.

@horizonzy @sanxun0325 That's right ,I have retry this scene with 1.4.0,and the problem remains.

**Comment by 309283175** [comment]
Since the public namespace resources stored in the permission table in the existing database are `:*:*` , I think we only need to parse the public namespace prefix to a blank string  when registering the service. 
AT com.alibaba.nacos.naming.web.NamingResourceParser.parseName(Object request)
before:
`if (StringUtils.isNotBlank(namespaceId)) {
            sb.append(namespaceId);
        }`
after
`if (StringUtils.isNotBlank(namespaceId) && !"public".equals(namespaceId)) {
            sb.append(namespaceId);
        }`

**Comment by horizonzy** [comment]
I think we should compatible it in `ResourceParser`, if the `namespace` value is 'public', replace it by '';

**Comment by KomachiSion** [comment]
maybe duplicate with #3524
