### ISSUE TITLE
nacos 1.3.2 and1.4.0 The cluster modification of the externally exposed port causes the cluster node to be abnormal.

### ISSUE THREAD

**Issue by yszansx** [alibaba/nacos#4266]
I use docker-compose to run the cluster。 The dockerfile is as follows。 when the cluster get ready，At least one node is candidate。I also use the same dockerfile in nacos-server:1.3.0 and nacos-server:1.2.1 。There is no such problem。
After testing, the port exposed by container nacos1 was changed to 8848:8848, and the cluster nodes returned to normal。
100% recurrence 。 I think this is a bug and I Hope it can be improved.

version: "3"
services:
nacos1:
hostname: nacos1
container_name: nacos1
image: nacos/nacos-server:1.4.0
volumes:
- ./cluster-logs/nacos1:/home/nacos/logs
- ./init.d/custom.properties:/home/nacos/init.d/custom.properties
ports:
- "8849:8848"
- "9555:9555"
environment:
- MODE=cluster
- PREFER_HOST_MODE=hostname
- SPRING_DATASOURCE_PLATFORM=mysql
- NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
- MYSQL_SERVICE_HOST=127.0.0.1
- MYSQL_SERVICE_DB_NAME=nacos_config
- MYSQL_SERVICE_PORT=3306
- MYSQL_SERVICE_USER=nacos
- MYSQL_SERVICE_PASSWORD=123456
restart: on-failure
nacos2:
hostname: nacos2
image: nacos/nacos-server:1.4.0
container_name: nacos2
volumes:
- ./cluster-logs/nacos2:/home/nacos/logs
- ./init.d/custom.properties:/home/nacos/init.d/custom.properties
ports:
- "8850:8848"
environment:
- MODE=cluster
- PREFER_HOST_MODE=hostname
- SPRING_DATASOURCE_PLATFORM=mysql
- NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
- MYSQL_SERVICE_HOST=127.0.0.1
- MYSQL_SERVICE_DB_NAME=nacos_config
- MYSQL_SERVICE_PORT=3306
- MYSQL_SERVICE_USER=nacos
- MYSQL_SERVICE_PASSWORD=123456
restart: on-failure
nacos3:
hostname: nacos3
image: nacos/nacos-server:1.4.0
container_name: nacos3
volumes:
- ./cluster-logs/nacos3:/home/nacos/logs
- ./init.d/custom.properties:/home/nacos/init.d/custom.properties
ports:
- "8851:8848"
environment:
- MODE=cluster
- PREFER_HOST_MODE=hostname
- SPRING_DATASOURCE_PLATFORM=mysql
- NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
- MYSQL_SERVICE_HOST=127.0.0.1
- MYSQL_SERVICE_DB_NAME=nacos_config
- MYSQL_SERVICE_PORT=3306
- MYSQL_SERVICE_USER=nacos
- MYSQL_SERVICE_PASSWORD=123456
restart: on-failure

![image](https://user-images.githubusercontent.com/43443722/99627498-62aa5a80-2a6f-11eb-89cc-74017ab359d0.png)

![image](https://user-images.githubusercontent.com/43443722/99627455-57572f00-2a6f-11eb-8a80-b871314e71b2.png)

 - OS: Centos7.4
 - Version nacos-server 1.3.2, nacos-server 1.4.0
 - Module naming/config
 - SDK spring-cloud-alibaba-nacos

**Additional context**
(https://github.com/nacos-group/nacos-docker/issues/143)

**Comment by yszansx** [comment]
![image](https://user-images.githubusercontent.com/43443722/99768663-22ff7380-2b40-11eb-8dc9-13631903f0e1.png)


Candidate problems appear in the cluster. Single node can be used normally.
I tested the version above the picture, and found that all cluster candidates have problems. The database has also been compared with your example, and there is no difference in the fields. At the same time, I deployed on 6 machines and found that three machines will prompt abnormalities. As a result, microservices cannot be registered. So I returned to the 1.3.0 docker image and it returned to normal. And 1.3.0 has been running stably in the production environment for more than 2 months, 1.3.2 and 1.4.0 will be unable to register after a few days.

**Comment by paderlol** [comment]
I tried to reproduce your problem, but the result is normal. Is there anything else to configure besides port configuration?
![image](https://user-images.githubusercontent.com/7919984/100214493-ec17cc00-2f4a-11eb-8e15-9cb1b8129e90.png)
![image](https://user-images.githubusercontent.com/7919984/100214557-0356b980-2f4b-11eb-9cd4-9609f1218c7a.png)

**Comment by KomachiSion** [comment]
No response from authors, so we think the problem has been fixed by the comments. Close issue
