### ISSUE TITLE
nacos Password with special characters cannot be authenticated

### ISSUE THREAD

**Issue by enthusiastic-tice** [alibaba/nacos#4269]
**Describe the bug**
Password with special characters cannot be authenticated

**Expected behavior**
failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Nov 19 14:23:21 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>

**Comment by enthusiastic-tice** [comment]
新版本已经解决

**Comment by zhousheng2** [comment]
从哪个版本开始解决的？

**Comment by cetianyuan** [comment]
2.1.2.RELEASE&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 中午11:54
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"天天"<1447660461@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos Password with special characters cannot be authenticated (#4269)





 
从哪个版本开始解决的？
