### ISSUE TITLE
Unify the namespaceId init way in nacosConfigService and nacosNamingService

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4270]
**Describe the bug**
In nacoConfigService, if user didn't set namespace in properties, it will use `""` as default value.
In nacosNamingService, if user didn't set namespace in properites, it will use `public` str as default value.

Maybe we should unify the init way of namespace. make nacosConfigService to be same as naconsNamingService

**Comment by horizonzy** [comment]
in #4262, If we use `public:*:*` to replace `':*:*'`, when user didn't config namespace in properties, in naming module, it can work well, because the namespace will be set `public`. but in config module, it will cause problem, the namespace set as `""`. the permission can't pass.

**Comment by KomachiSion** [comment]
Move to #3525
