### ISSUE TITLE
内部数据库容灾(只有一个)

### ISSUE THREAD

**Issue by independenter** [alibaba/nacos#4274]
## Issue Description

feature request

### Describe what happened (or what feature you want)
With only single database, disaster recovery of internal database is still running

### Describe what you expected to happen
There is only single database, and internal database disaster recovery stops or skips

### How to reproduce it (as minimally and precisely as possible)

1. com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.SelectMasterTask#run 
2. 
3. 

### Tell us your environment
standalone,Single database

**Comment by zhangcly** [comment]
@i will solve it@
