### ISSUE TITLE
replace com.alibaba.nacos.config.server.result.ResultBuilder to RestResultUtil

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#4275]
**Is your feature request related to a problem? Please describe.**

replace com.alibaba.nacos.config.server.result.ResultBuilder to RestResultUtil to unify the generation of changed objects

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langghaha** [comment]
I will solve it

**Comment by Maijh97** [comment]
has been completed in pr #4299.
