### ISSUE TITLE
当配置文件有空格时，将无法匹配参数。

### ISSUE THREAD

**Issue by alonelaval** [alibaba/nacos#4278]
**Describe the bug**

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://127.0.0.1:3306/kiam_message?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root123

**Expected behavior**

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://127.0.0.1:3306/kiam_message?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root123

去掉spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver中的空格，如：
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

**Acutally behavior**

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

因为中间有空格，导致 key一直无法匹配上，程序永远起不来，找不到配置文件。

**Comment by alonelaval** [comment]
麻烦指派给我。@komachiSion

**Comment by KomachiSion** [comment]
@alonelaval 我记得properties本身不支持空格，是严格的=分割。  我们是否应该严格按照标准来做？

**Comment by alonelaval** [comment]
但是我在项目里面，是可以正常运行的，就是说没有采用 nacos 来配置的时候。

**Comment by KomachiSion** [comment]
你是说你应用如果用spring本地启动是可以带空格的？然后用nacos动态读取是不行的？

**Comment by alonelaval** [comment]
@KomachiSion 对的，昨天我测试了很多次。这个问题困扰了我几个小时，开始时以为是 naocs 版本不对，换了几个版本，因为配置信息直接从 bootstrap.properties拷贝至 nacos 里面的，就没有想过是这个问题，最后晚上回家后，灵感来了，可能觉得是这个问题，测试了一下，果然是的。

**Comment by KomachiSion** [comment]
但是按照properties的标准，=之前的是key，如果你配置的=之前有空格 那么实际的key是`xxxx ` 而不是 `xxx` 这就是properties标准，可以试一下JDK的properties，应该是这个结果。

**Comment by KomachiSion** [comment]
@alonelaval 你能先把方案梳理一下吗？ 或者跟一下spring的处理方式。

**Comment by alonelaval** [comment]
@KomachiSion 我还没有去看源码，大致的想法是在 nacos client 取回来的时候，就做相关的 trim 处理。

**Comment by KeRan213539** [comment]
> @KomachiSion 我还没有去看源码，大致的想法是在 nacos client 取回来的时候，就做相关的 trim 处理。

你是用的 nacos-spring-boot 还是 spring cloud alibaba?
目前 nacos-spring-context 1.0.0 已经解决了该问题. 但是目前的 nacos-spring-boot 版本与nacos-spring-context 1.0.0 不兼容.无法强制指定nacos-spring-context 为 1.0.0, 等 nacos-spring-boot 升级吧. spring cloud alibaba 那边最新版本应该没这个问题

**Comment by alonelaval** [comment]
用的spring cloud Ali an

**Comment by alonelaval** [comment]
> > @KomachiSion 我还没有去看源码，大致的想法是在 nacos client 取回来的时候，就做相关的 trim 处理。
> 
> 
> 
> 你是用的 nacos-spring-boot 还是 spring cloud alibaba?
> 
> 目前 nacos-spring-context 1.0.0 已经解决了该问题. 但是目前的 nacos-spring-boot 版本与nacos-spring-context 1.0.0 不兼容.无法强制指定nacos-spring-context 为 1.0.0, 等 nacos-spring-boot 升级吧. spring cloud alibaba 那边最新版本应该没这个问题

spring alibaba版本：<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
spring cloud 版本 <spring-cloud.version>Hoxton.SR8</spring-cloud.version>
nacos 版本： 1.3.2 ，1.1.4

**Comment by KeRan213539** [comment]
> 用的spring cloud Alibaba

什么版本? 升级最新版试试?  看看 nacos-spring-context 是不是 1.0.0

**Comment by alonelaval** [comment]
电脑送修了，只能下周确认了。

**Comment by KeRan213539** [comment]
> 电脑送修了，只能下周确认了。

ok

**Comment by alonelaval** [comment]
这个是我找到的 nacos 相关的包，我感觉没有你说的 nacos-spring-context.
![WeChat006ff034816ae4b1c30830d4da85c56b](https://user-images.githubusercontent.com/1763449/100400774-92bab480-3092-11eb-8434-1f8329503bb2.png)
![WeChatbd8df5650b59e286df620d58025748bd](https://user-images.githubusercontent.com/1763449/100400789-9e0de000-3092-11eb-84ee-89402440db13.png)

**Comment by KeRan213539** [comment]
貌似SCA没有使用 nacos-spring-context. 那这个问题需要SCA那边去解决了

**Comment by alonelaval** [comment]
好的。我去看看。

**Comment by KeRan213539** [comment]
这边也关闭了
