### ISSUE TITLE
请问服务能不能直接用域名进行注册

### ISSUE THREAD

**Issue by szw1026** [alibaba/nacos#4296]
nacos部署在内网，使用内网穿透映射出域名，所以只能用nacos域名注册

**Comment by horizonzy** [comment]
可以。

**Comment by szw1026** [comment]
> 可以。

域名需要备案吗

**Comment by horizonzy** [comment]
和你备案没关系



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: szw1026 <notifications@github.com&gt;
发送时间: 2020年11月21日 15:49
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 请问服务能不能直接用域名进行注册 (#4296)





  
可以。
  
域名需要备案吗
