### ISSUE TITLE
Nacos console Service list .Group search is not correct

### ISSUE THREAD

**Issue by woxiangwoxiangxiang** [alibaba/nacos#4306]
Nacos console Service list .Group search is not correct.
<img width="1440" alt="WeChatf4c28205f9159b7be6b47a9123b47cff" src="https://user-images.githubusercontent.com/29097594/99948665-bc36c000-2db4-11eb-95dd-7074f91faf1a.png">
I searched for 'Gateway' in 'group name' . There is no 'group name' with the name 'Gateway' in my data. But he was able to query the data.

**Comment by horizonzy** [comment]
Maybe this search request occur error, now when the search service request without serviceName, it will error. 
Can you press `F12` to open console, check the network console, view the response.

**Comment by woxiangwoxiangxiang** [comment]
This is the requested Network Console.

<img width="1440" alt="WeChate02cbb06139fe6f099a0c44582737471" src="https://user-images.githubusercontent.com/29097594/99953909-ea200280-2dbc-11eb-9563-61a45bdcc9a3.png">
<img width="1440" alt="WeChat9c01b0b6d2c5bfac844c8f908e13d4a1" src="https://user-images.githubusercontent.com/29097594/99953911-ebe9c600-2dbc-11eb-8be9-eb2efa1266de.png">

Request parameters are ok. Is the server side of the query logic is not correct, is a server side of the bug.

**Comment by horizonzy** [comment]
I check it, it's really bug. it's the server side problem.

**Comment by woxiangwoxiangxiang** [comment]
I can fix it

**Comment by horizonzy** [comment]
yes, recent pr #4308 modify it, you should based on it to fix this bug.

**Comment by horizonzy** [comment]
This pr https://github.com/alibaba/nacos/pull/4439 cause this issue, revert it.
