### ISSUE TITLE
Request read timeout should be same in MemberInfoReportTask and DistroFilter proxy.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4307]
**Describe the bug** 
The request read timeout in MemberInfoReportTask is 2500ms.
The request read timeout in DistroFilter proxy is 2000ms.

If A and B server network exist problem, a simple request will cost between 2000ms-2500ms. If the serviceName which responsed by B server, server A received request and proxy to B, the request will always failed.

**Expected behavior**
Unify them.

**Comment by KomachiSion** [comment]
Not always failed, if A and B server network exist problem, several times MemberInfoReportTask failed will remove server B from A, and then the serviceName will be responsed other server.

**Comment by horizonzy** [comment]
It's my expression problem. there be network delay between A and B, the network delay is 2000ms-2500ms. MemberInfoReportTask will always success, the proxy request will always failed.

**Comment by KomachiSion** [comment]
If so, I think the timeout of distro filter should be more than member info report. Of cource making them same is ok.

**Comment by horizonzy** [comment]
> If so, I think the timeout of distro filter should be more than member info report. Of cource making them same is ok.

agree.

**Comment by KomachiSion** [comment]
MemberInfoReportTask has been move to grpc, this problem solved.
