### ISSUE TITLE
add arm64 support

### ISSUE THREAD

**Issue by huwsun** [alibaba/nacos#4309]
**Is your feature request related to a problem? Please describe.**

add aarch64 support

**Describe the solution you'd like**

update jraft-core version to 1.3.5.Alpha1,in order to upgrade rocksdbjni to 5.18.4,this version provides aarch64 support.

**Describe alternatives you've considered**
none.

**Additional context**
none

**Comment by chuntaojun** [comment]
Nacos will only rely on stable versions of third-party packages, and currently Jraft is still alpha

**Comment by KomachiSion** [comment]
After Jraft release stable versions, we will upgrade it.

**Comment by KomachiSion** [comment]
Refer to #4336
