### ISSUE TITLE
client与server版本问题

### ISSUE THREAD

**Issue by jsxiao** [alibaba/nacos#4315]
目前使用 `spring-cloud-starter-alibaba-nacos-discovery:2.1.1.RELEASE` 其对应的client版本为`1.1.4`

server版本 `1.3.2`. 现在想将server升级为 `1.4.0` 不清楚client端是否需要升级，请问client和server的版本是如何对应的？

**Comment by Maijh97** [comment]
正常情况client端可以不用升级

**Comment by paderlol** [comment]
You can decide whether to upgrade a new client based on the features released by the release and the fixed issue. Normally, the version is downward compatible.

**Comment by jsxiao** [comment]
thanks a lot! I decided not to upgrade for now.
ありがとおございます！
