### ISSUE TITLE
有数据泄露风险

### ISSUE THREAD

**Issue by tristan-tsl** [alibaba/nacos#4317]
**Describe the bug**
请求open api时, 不携带accessToken仍然能请求到数据, 有数据泄露风险

**Expected behavior**

**Acutally behavior**

**How to Reproduce**
1.visit this url: <YOUR_NACOS_BASE_URI>/nacos/v1/console/namespaces?pageNo=1&pageSize=1000

**Desktop (please complete the following information):**
 - Version nacos-server 1.3.1

**Additional context**

**Comment by devfat** [comment]
The URL you visited is the page route. When you visited the page, the request sends to `Nacos console` server is `GET /v1/console/namespaces/` with accessToken header if you have logged in. 

Check the browser request `GET /v1/console/namespaces/`  if it has the accessToken header.

**Comment by tristan-tsl** [comment]
maybe the auth is not work well

**Comment by tristan-tsl** [comment]
web界面和api有明显冲突, 如果不鉴权会导致web无法使用或者api不可使用, 只能二选一

**Comment by paderlol** [comment]
清除下浏览器的缓存

**Comment by tristan-tsl** [comment]
你好, 并非在浏览器访问, 而且匿名模式下仍然可以访问

**Comment by paderlol** [comment]
匿名模式下，是不是auth没开启？

**Comment by tristan-tsl** [comment]
如何开启auth

**Comment by takeseem** [comment]
安全性上的投入太少了，不敢放密钥和敏感配置。

consul还有一个基础的ACL，能进行精细控制。

**Comment by KomachiSion** [comment]
部分接口可能是作为公共API，不需要校验，比如你例举的这个namespace列表。

**Comment by liangyuanpeng** [comment]
看起来这个问题没有解决？ 所以结论是什么？

**Comment by tristan-tsl** [comment]
自建nacos要谨慎使用, 建议结合jasypt使用

**Comment by tristan-tsl** [comment]
> 看起来这个问题没有解决？ 所以结论是什么？

自建nacos要谨慎使用, 建议结合jasypt使用
