### ISSUE TITLE
所有版本均存在的问题：LongPollingRunnable将随时间执行频率将逐渐增加

### ISSUE THREAD

**Issue by stotem** [alibaba/nacos#4325]
**Describe the bug**
LongPollingRunnable的实例是由com.alibaba.nacos.client.config.impl.ClientWorker#checkConfigInfo中通过executorService创建并执行，checkConfigInfo是由ClientWorker在创建实例时通过ScheduledExecutorService的scheduleWithFixedDelay定时执行。但LongPollingRunnable的run中将this重新放入到了线程池中继续执行，这将导致LongPollingRunnable的run有两个触发点：1、ScheduledExecutorService的scheduleWithFixedDelay；2、LongPollingRunnable自身实例执行完成后往executorService中继续放入执行任务。由于ScheduledExecutorService的scheduleWithFixedDelay会不断创建LongPollingRunnable实例，故会导致LongPollingRunnable的执行任务越来越频繁。 严重的将导致网络端口不停被占用，从而导致其它的客户端不能连接nacos的服务端口。

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by paderlol** [comment]
请问这个在什么情况下能重现这个频率很高的情况？

**Comment by paderlol** [comment]
我刚刚确认了代码,确实有两个点会触发LongPollingRunnable,但是在你描述的第一个点里面,实际是有限制的触发的。
```
public void checkConfigInfo() {
        // Dispatch taskes.
        int listenerSize = cacheMap.get().size();
        // Round up the longingTaskCount.
        int longingTaskCount = (int) Math.ceil(listenerSize / ParamUtil.getPerTaskConfigSize());
        if (longingTaskCount > currentLongingTaskCount) { 只有满足条件才会触发
            for (int i = (int) currentLongingTaskCount; i < longingTaskCount; i++) {
                // The task list is no order.So it maybe has issues when changing.
                executorService.execute(new LongPollingRunnable(i));
            }
            currentLongingTaskCount = longingTaskCount; //结束时会把这个数值赋值给一个全局变量
        }
    }
```

**Comment by stotem** [comment]
> 我刚刚确认了代码,确实有两个点会触发LongPollingRunnable,但是在你描述的第一个点里面,实际是有限制的触发的。
> 
> ```java
> public void checkConfigInfo() {
>         // Dispatch taskes.
>         int listenerSize = cacheMap.get().size();
>         // Round up the longingTaskCount.
>         int longingTaskCount = (int) Math.ceil(listenerSize / ParamUtil.getPerTaskConfigSize());
>         if (longingTaskCount > currentLongingTaskCount) { 只有满足条件才会触发
>             for (int i = (int) currentLongingTaskCount; i < longingTaskCount; i++) {
>                 // The task list is no order.So it maybe has issues when changing.
>                 executorService.execute(new LongPollingRunnable(i));
>             }
>             currentLongingTaskCount = longingTaskCount; //结束时会把这个数值赋值给一个全局变量
>         }
>     }
> ```

限制触发的逻辑是什么样子的? 我理解可以直接去掉LongPollingRunnable内部的触发点，统一由外层ScheduledExecutorServic的scheduleWithFixedDelay来定时执行。

**Comment by stotem** [comment]
> 请问这个在什么情况下能重现这个频率很高的情况？

不停的new LongPollingRunnable对象出来，不停的将this加入到executorService中继续执行，这样会导致LongPollingRunnable的run代码段增加无限多的触发点。只需要启动程序，不需要加入任务操作，随着运行时间越久创建的LongPollingRunnable对象就会越多，就会出现此问题

**Comment by paderlol** [comment]
限制的条件就是判断这个需要出发的task数量, 只有第二个点每次都会执行完出发, 第一个点只有满足一定任务数量才会触发,并且每次执行完会把这个数量给全局的`currentLongingTaskCount`变量

**Comment by sanxun0325** [comment]
> 限制触发的逻辑是什么样子的? 我理解可以直接去掉LongPollingRunnable内部的触发点，统一由外层ScheduledExecutorServic的scheduleWithFixedDelay来定时执行。

@stotem  第一个点是为了控制开启几个LongPolling task。第二个点是LongPolling task 自旋执行。 
task数量计算方式 `int longingTaskCount = (int) Math.ceil(listenerSize / ParamUtil.getPerTaskConfigSize());`

所以在第一个点不会不停的 new LongPollingRunnable

**Comment by shiyiyue1102** [comment]
1.LongPollingRunnable 实例不会无限增加，LongPollingRunnable的数量等于客户端监听总的配置数X/ 单个链接监听配置数m，m默认值是3000，可以手动设置，如果这个值设置过小，可能会导致创建很多的LongPollingRunnable  , 如果一直无限制的随机监听配置，可能会造成LongPollingRunnable过多的情况
2.LongPollingRunnable本身是一个工作任务，而不是一个线程，LongPollingRunnable每次运行完成之后，会将自己重新放入工作队列中，LongPollingRunnable实例并没有增加

建议你将你遇到的问题现象详细描述下，我们再具体分析是什么原因导致的

**Comment by stotem** [comment]
> 1.LongPollingRunnable 实例不会无限增加，LongPollingRunnable的数量等于客户端监听总的配置数X/ 单个链接监听配置数m，m默认值是3000，可以手动设置，如果这个值设置过小，可能会导致创建很多的LongPollingRunnable , 如果一直无限制的随机监听配置，可能会造成LongPollingRunnable过多的情况
> 2.LongPollingRunnable本身是一个工作任务，而不是一个线程，LongPollingRunnable每次运行完成之后，会将自己重新放入工作队列中，LongPollingRunnable实例并没有增加
> 
> 建议你将你遇到的问题现象详细描述下，我们再具体分析是什么原因导致的

项目是去年开始的，选定的是当时最新的1.1.4版本，现象是在客户端与nacos服务端均部署在本机。
1、在客户端程序中时常出现连接被拒绝或连接超时，通过对端口进行查看，端口除了出现少量的TIME_WAIT，没有发现其它的异常。
2、通过对报连接超时的情况进行tcpdump抓包分析，发现客户端请求/nacos/v1/cs/configs/listener时存在响应超时30秒到60秒情况而导致请求超时。

初步怀疑是客户端请求次数过于密集，造成了端口不正常或造成网络堵塞，待排查。

客户端异常消息如下：
com.alibaba.nacos.client.Worker.longPolling.fixed-discovery-server.sefon.com_57102][com.alibaba.nacos.client.config.http.ServerHttpAgent - 149][ERROR] - [NACOS ConnectException httpPost] currentServerAddr: http://discovery-server.sefon.com:57102, err : 拒绝连接 (Connection refused)

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([discovery-server.sefon.com:57102]) tried: failed to req API:discovery-server.sefon.com:57102/nacos/v1/ns/instance/beat. code:504 msg: {"code":"504","messages":["Service Timeout"]}

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([discovery-server.sefon.com:57102]) tried: failed to req API:discovery-server.sefon.com:57102/nacos/v1/ns/instance/beat. code:500 msg: java.net.ConnectException: 拒绝连接 (Connection refused)

[com.alibaba.nacos.client.Worker.longPolling.fixed-discovery-server.sefon.com_57102][com.alibaba.nacos.client.config.impl.ClientWorker - 550][ERROR] - longPolling error :
java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:162)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352)
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512)

**Comment by paderlol** [comment]
你现在也使用的是1.1.4吗？

**Comment by stotem** [comment]
> 你现在也使用的是1.1.4吗？

是的，目前还是1.1.4

**Comment by paderlol** [comment]
那可能存在心跳问题，在1.3.2之后修复了。

**Comment by chuntaojun** [comment]
你是有自己使用ConfigService的客户端实现吗，是的话，贴一下相关代码

**Comment by stotem** [comment]
> 你是有自己使用ConfigService的客户端实现吗，是的话，贴一下相关代码，如果你是使用Spring Cloud Alibaba的话，请贴一下相关版本，或者升级到最新的SCA版本

没有自己实现，使用的是默认NacosConfigService的实现，版本是1.1.4版本

**Comment by stotem** [comment]
请问1.4.0中新增的jmenv.tbsite.net这个域名是干嘛用的？

**Comment by paderlol** [comment]
这个以前就有

**Comment by KomachiSion** [comment]
> 请问1.4.0中新增的jmenv.tbsite.net这个域名是干嘛用的？

默认地址服务器域名，如果cluster.conf文件不存在，就会到这个地址去取nacos集群的ip信息。
