### ISSUE TITLE
install service with ipv4

### ISSUE THREAD

**Issue by chn8lij** [alibaba/nacos#4327]
## Issue Description

Type: *docker install problem* 

### Describe what happened (or what feature you want)
i install nacos with official website (https://nacos.io/zh-cn/docs/quick-start-docker.html) by docker-compose ,but the services are all listening on ipv6
### Describe what you expected to happen
how could i change it to ipv4
![image](https://user-images.githubusercontent.com/42732930/100172662-c5827280-2f03-11eb-93d9-198a422cf45e.png)

**Comment by paderlol** [comment]
This problem has nothing to do with Nacos. This is a problem with your local network card settings. Please check the problem of docker listening ipv6

**Comment by chn8lij** [comment]
> This problem has nothing to do with Nacos. This is a problem with your local network card settings. Please check the problem of docker listening ipv6

it's ok now,why i ask this question is that i install with the way of docker-compose on the official website.
