### ISSUE TITLE
nacos1.3.2升级到1.4.0配置端口无效(Nacos1.3.2 upgrade to 1.4.0 configuration port is invalid)

### ISSUE THREAD

**Issue by HalcyonDaysssss** [alibaba/nacos#4331]
1：docker-compose配置(docker-compose configuration):
![image](https://user-images.githubusercontent.com/24239032/100206434-490e8480-2f41-11eb-9998-56f3049253a1.png)

2：application.properties配置(application.properties configuration):
![image](https://user-images.githubusercontent.com/24239032/100206242-0ba9f700-2f41-11eb-853f-5fe8f33f1135.png)

3：nacos日志(nacos log):
![image](https://user-images.githubusercontent.com/24239032/100206351-2d0ae300-2f41-11eb-8491-cece014c3703.png)

ps:日志虽然显示端口8848，我依然可以用10001端口访问成功nacos，但是我的服务无法启动，报错获取配置文件失败(nacos界面显示配置文件存在),我将版本更改为1.3.2端口配置成功，服务正常启动(Although the log shows port 8848, I can still use port 10001 to access nacos successfully, but my service fails to start, and an error is reported to obtain the configuration file (the nacos interface shows that the configuration file exists). I changed the version to 1.3.2. The port configuration is successful, the service Normal start)

**Comment by paderlol** [comment]
这个问题已经解决了,是由于1.3.2以后增加了一个处理配置加载器,修改了顺序导致,Docker镜像没有进行配置顺序调整,目前已经修复了,请重新pull镜像解决。 具体参考 issue #4022 PR #4021
