### ISSUE TITLE
Nacos, as the configuration center, how to ensure the consistency of the configuration of each node in the cluster?

### ISSUE THREAD

**Issue by lchpersonal** [alibaba/nacos#4332]
Nacos作为配置中心，如何保证集群各个节点之间配置的一致性？
例如：在配置中心管理后台修改配置，调用了A节点保存配置，B节点如何知道配置变更了快速响应给连接到B节点的客户端呢？
异常场景下如何保证一致性的？

Nacos, as the configuration center, how to ensure the consistency of configuration among the nodes of the cluster? For example, if you modify the configuration in the management background of the configuration center, and call the A node to save the configuration, how does the B node know that the configuration change quickly responds to the client connected to the B node? How to ensure consistency in abnormal scenarios?

**Comment by paderlol** [comment]
* Nacos 有两种方式来进行配置保存

1. 嵌入式内存的方式,这种是通过Jraft来实现raft协议来完成一致性写入
2. 数据库的方式

* 至于节点通知,由客户端进行长轮询进行比对并更新数据

异常场景
客户端本地会有快照机制,当Nacos Server crash掉的时候,会使用本地的快照
