### ISSUE TITLE
some question about Nacos 1.4

### ISSUE THREAD

**Issue by misstouch** [alibaba/nacos#4335]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

I downloaded the latest code and used: mvn - Prelease Nacos- Dmaven.test.skip=true clean install - U command compiles, but an error is reported: too many files with unauthorized license

### Tell us your environment
localhost

**Comment by misstouch** [comment]
i was used: mvn -Prelease-nacos -Dmaven.test.skip=true -Drat.skip=true  clean install -U ，it can compile normally

**Comment by misstouch** [comment]
why

**Comment by paderlol** [comment]
What version of jdk are you using for compiling?

**Comment by misstouch** [comment]
1.8

**Comment by misstouch** [comment]
> What version of jdk are you using for compiling?
1.8

**Comment by paderlol** [comment]
All of our projects have passed the license inspection, and automatic inspection will be performed when the code is merged, so you need to provide more information or troubleshoot by yourself

**Comment by KomachiSion** [comment]
Maybe there are some special files generate by yourself in your project directory. And the rat plugin found these files and stop  the install.

**Comment by misstouch** [comment]
> All of our projects have passed the license inspection, and automatic inspection will be performed when the code is merged, so you need to provide more information or troubleshoot by yourself

OK, I'll try again
