### ISSUE TITLE
register error(for help)

### ISSUE THREAD

**Issue by CaoET** [alibaba/nacos#4337]
When I start the springboot service, the Nacos registry prompts an exception message:request: /nacos/v1/ns/instance/list failed, servers: [localhost:8848], code: 500, msg: Connection refused (Connection refused).

Hope someone can help answer, I am a novice,thank you!

I just did the basic configuration.

first:
I deployed Nacos (v1.3.2) on the server. I used the compiled version, then unzipped and started, using singleton mode (sh startup.sh -m standalone)

second:
I created the simplest springboot project, as follows
![image](https://user-images.githubusercontent.com/13093351/100307754-9fcb9b00-2fe1-11eb-96ad-7d5745f80c97.png)
![image](https://user-images.githubusercontent.com/13093351/100307775-aeb24d80-2fe1-11eb-813e-dcddd7edd631.png)
![image](https://user-images.githubusercontent.com/13093351/100307805-c093f080-2fe1-11eb-8a25-336301d9c2dd.png)
![image](https://user-images.githubusercontent.com/13093351/100307819-c8539500-2fe1-11eb-919e-67a4cc8cf69e.png)

The error information is as follows
![image](https://user-images.githubusercontent.com/13093351/100307861-e4573680-2fe1-11eb-9c5e-abbb8090ace1.png)

**Comment by paderlol** [comment]
You need to provide more detailed information, such as how you configured it and whether there is an error log

**Comment by CaoET** [comment]
I just did the basic configuration.

first:I deployed Nacos (v1.3.2) on the server. I used the compiled version, then unzipped and started, using singleton mode (sh startup.sh -m standalone)

second:I created the simplest springboot project, as follows
![image](https://user-images.githubusercontent.com/13093351/100306926-7d388280-2fdf-11eb-9263-96fdcd833f0a.png)
![image](https://user-images.githubusercontent.com/13093351/100306959-94777000-2fdf-11eb-8f12-c2f472aa7183.png)
![image](https://user-images.githubusercontent.com/13093351/100307005-b07b1180-2fdf-11eb-8fca-c2fa2a050cbf.png)
![image](https://user-images.githubusercontent.com/13093351/100307035-c983c280-2fdf-11eb-9777-b33d90e5477e.png)

The error information is as follows
![image](https://user-images.githubusercontent.com/13093351/100307081-ee783580-2fdf-11eb-9592-fe232a407ca6.png)

**Comment by paderlol** [comment]
You only configure the address of the configuration center, you also need to configure the address of the registration center in the application.properties file, please go to the official example of Spring cloud alibaba

**Comment by chuntaojun** [comment]
You just configured the server address of the configuration center, you also need to configure the server address of the registry

**Comment by CaoET** [comment]
@paderlol I got it,Thank you!
