### ISSUE TITLE
注册中心Distro协议高可用问题

### ISSUE THREAD

**Issue by MagakiReimu** [alibaba/nacos#4338]
**Describe the bug**
向Nacos-Server发送注册请求
DistroFilter line132:
`final String targetServer = distroMapper.mapSrv(groupedServiceName);`
会根据注册的服务名称和分组求算Hash值对Server集群取余，重新分发到对应的节点上注册
其中distroMapper的Server列表是基于MemberChangeEvent事件进行更新的
MemberChangeEvent的事件是由ServerMemberManager中的memberChange方法发起
memberChange方法中最后发送的服务列表事件构造函数如下
```
Event event = MemberChangeEvent.builder().members(finalMembers).build();
Collection<Member> finalMembers = allMembers();
```
```
public Collection<Member> allMembers() {
	// We need to do a copy to avoid affecting the real data
	HashSet<Member> set = new HashSet<>(serverList.values());
	set.add(self);
	return set;
}
```
```
/**
 * Cluster node list
 */
private volatile ConcurrentSkipListMap<String, Member> serverList;
/**
 * here is always the node information of the "UP" state
 */
private volatile Set<String> memberAddressInfos = new ConcurrentHashSet<>();
```
serverList是所有Server节点的列表
memberAddressInfos才是只包含状态为UP的Server列表

```
public boolean update(Member newMember) {
	Loggers.CLUSTER.debug("Node information update : {}", newMember);

	String address = newMember.getAddress();
	newMember.setExtendVal(MemberMetaDataConstants.LAST_REFRESH_TIME, System.currentTimeMillis());

	if (!serverList.containsKey(address)) {
		return false;
	}
	serverList.computeIfPresent(address, new BiFunction<String, Member, Member>() {
		@Override
		public Member apply(String s, Member member) {
			if (!NodeState.UP.equals(newMember.getState())) {
				memberAddressInfos.remove(newMember.getAddress());
			}
			MemberUtils.copy(newMember, member);
			return member;
		}
	});
	return true;
}
```
MemberInfoReportTask会定时触发该方法更新memberAddressInfos

这不是一个高可用的注册中心，高可用应该只将服务转发至UP状态的节点

**Expected behavior**
当Server集群中有出现一个异常节点，状态不为UP，服务基于Distro协议重定向至其他正常节点注册

**Acutally behavior**
A clear and concise description of what you actually to happen.
当Server集群中有出现一个异常节点，状态不为UP，服务基于Distro协议一直重定向至该异常节点将一直注册失败

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

OS： CenterOS 7
Version： nacos-server 1.3.0
Module： naming

**Additional context**

**Comment by KomachiSion** [comment]
fixed in 1.3.1 
duplicate with https://github.com/alibaba/nacos/issues/3110

**Comment by MagakiReimu** [comment]
1.3.1未修复这个问题

1.3.2的代码如下
```
            MemberUtils.syncToFile(finalMembers);
            Set<Member> healthMembers = MemberUtils.selectTargetMembers(members, member -> {
                return !NodeState.DOWN.equals(member.getState());
            });
            Event event = MembersChangeEvent.builder().members(finalMembers).build();
            NotifyCenter.publishEvent(event);
```
发送的事件的构造参数并不是healthMembers

**Comment by MagakiReimu** [comment]
@KomachiSion 
现在建了一个Nacos-Server集群，3个节点，然后修改K8s scale为2，这时nacos-2节点不可用
/nacos/v1/core/cluster/simple/nodes 返回2个节点
/nacos/v1/core/cluster/nodes 返回3个节点，其中nacos-2一直为SUSPICIOUS状态
MemberUtils.onFail
```
        // If the number of consecutive failures to access the target node reaches
        // a maximum, or the link request is rejected, the state is directly down
        if (cloneMember.getFailAccessCnt() > maxFailAccessCnt || StringUtils
                .containsIgnoreCase(ex.getMessage(), TARGET_MEMBER_CONNECT_REFUSE_ERRMSG)) {
            cloneMember.setState(NodeState.DOWN);
        }
```
这段代码并没有正确执行，如果正确执行，nacos-2应该会返回DOWN状态

最后执行的node list应该是只返回UP状态的member

**Comment by MagakiReimu** [comment]
```
try {
                asyncHttpClient
                        .post(url, Header.newInstance().addParam(Constants.NACOS_SERVER_HEADER, VersionUtils.version),
                                Query.EMPTY, getSelf(), reference.getType(), new Callback<String>() {
                                    @Override
                                    public void onReceive(RestResult<String> result) {
                                        if (result.getCode() == HttpStatus.NOT_IMPLEMENTED.value()
                                                || result.getCode() == HttpStatus.NOT_FOUND.value()) {
                                            Loggers.CLUSTER
                                                    .warn("{} version is too low, it is recommended to upgrade the version : {}",
                                                            target, VersionUtils.version);
                                            return;
                                        }
                                        if (result.ok()) {
                                            MemberUtils.onSuccess(target);
                                        } else {
                                            Loggers.CLUSTER
                                                    .warn("failed to report new info to target node : {}, result : {}",
                                                            target.getAddress(), result);
                                            MemberUtils.onFail(target);
                                        }
                                    }
                                    
                                    @Override
                                    public void onError(Throwable throwable) {
                                        Loggers.CLUSTER
                                                .error("failed to report new info to target node : {}, error : {}",
                                                        target.getAddress(),
                                                        ExceptionUtil.getAllExceptionMsg(throwable));
                                        MemberUtils.onFail(target, throwable);
                                    }
            
                                    @Override
                                    public void onCancel() {
                
                                    }
                                });
            } catch (Throwable ex) {
                Loggers.CLUSTER.error("failed to report new info to target node : {}, error : {}", target.getAddress(),
                        ExceptionUtil.getAllExceptionMsg(ex));
            }
```
是不是因为这个try-catch，没进入onError

**Comment by chuntaojun** [comment]
> ```
> try {
>                 asyncHttpClient
>                         .post(url, Header.newInstance().addParam(Constants.NACOS_SERVER_HEADER, VersionUtils.version),
>                                 Query.EMPTY, getSelf(), reference.getType(), new Callback<String>() {
>                                     @Override
>                                     public void onReceive(RestResult<String> result) {
>                                         if (result.getCode() == HttpStatus.NOT_IMPLEMENTED.value()
>                                                 || result.getCode() == HttpStatus.NOT_FOUND.value()) {
>                                             Loggers.CLUSTER
>                                                     .warn("{} version is too low, it is recommended to upgrade the version : {}",
>                                                             target, VersionUtils.version);
>                                             return;
>                                         }
>                                         if (result.ok()) {
>                                             MemberUtils.onSuccess(target);
>                                         } else {
>                                             Loggers.CLUSTER
>                                                     .warn("failed to report new info to target node : {}, result : {}",
>                                                             target.getAddress(), result);
>                                             MemberUtils.onFail(target);
>                                         }
>                                     }
>                                     
>                                     @Override
>                                     public void onError(Throwable throwable) {
>                                         Loggers.CLUSTER
>                                                 .error("failed to report new info to target node : {}, error : {}",
>                                                         target.getAddress(),
>                                                         ExceptionUtil.getAllExceptionMsg(throwable));
>                                         MemberUtils.onFail(target, throwable);
>                                     }
>             
>                                     @Override
>                                     public void onCancel() {
>                 
>                                     }
>                                 });
>             } catch (Throwable ex) {
>                 Loggers.CLUSTER.error("failed to report new info to target node : {}, error : {}", target.getAddress(),
>                         ExceptionUtil.getAllExceptionMsg(ex));
>             }
> ```
> 
> 是不是因为这个try-catch，没进入onError

这个catch住的error，不是在通信期间发生的异常，通信期间发生的异常是会在回调里面的
