### ISSUE TITLE
[Bug]编辑配置后历史版本显示错误，回滚后配置丢失

### ISSUE THREAD

**Issue by YaoC** [alibaba/nacos#434]
系统环境
- Linux hostname 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- CentOS Linux release 7.3.1611 (Core)
- java version "1.8.0_101"
- Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
- Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
- Nacos 0.5.0 or 0.6.0

复现流程
1. 新建配置
![新建配置](https://user-images.githubusercontent.com/5748889/49787940-ed9e5880-fd62-11e8-9e3d-70d643d07543.png)
使用 [Nacos Config Example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example) 测试配置生效：
![image](https://user-images.githubusercontent.com/5748889/49788112-6f8e8180-fd63-11e8-8304-1d13837cb0b5.png)
2. 修改配置
将配置中的 `user.name=test-000` 改为 `user.name=test-001`
测试应用中配置自动更新生效：
![image](https://user-images.githubusercontent.com/5748889/49788230-c2683900-fd63-11e8-8f5b-9cf9c921e201.png)

通过历史版本查看配置发现两个版本中都是 `user.name=test-000`
![image](https://user-images.githubusercontent.com/5748889/49788310-01968a00-fd64-11e8-8abf-2fe54e532058.png)
新建的配置：
![image](https://user-images.githubusercontent.com/5748889/49788375-27239380-fd64-11e8-8082-e1f858c6e445.png)
更新后的配置：
![image](https://user-images.githubusercontent.com/5748889/49788461-6225c700-fd64-11e8-8580-d23901ae64a1.png)

选择最初新建的配置进行回滚，配置文件丢失。

**Comment by 499196191** [comment]
我也遇到这种问题。

**Comment by chuntaojun** [comment]
好像仍然存在这个问题

**Comment by eacdy** [comment]
same problem.

**Comment by cocolove2** [comment]
我在1.3.0版本也遇到这个问题

**Comment by mizong** [comment]
好垃圾啊，阿里巴巴的东西不可靠，2.2.2.RELEASE版本还有
