### ISSUE TITLE
nacos access_log log file cannot be closed

### ISSUE THREAD

**Issue by huangzgx** [alibaba/nacos#4340]
**Describe the bug**

The access_log file cannot be closed. The configuration file is closed by default, but a large file is still generated every day. Is there any way to close it completely?

**Desktop (please complete the following information):**
 - OS: Centos
 - Version nacos-server 1.4.0

![image](https://user-images.githubusercontent.com/55429426/100326314-c222e000-3004-11eb-8e40-1910b8b03792.png)
![image](https://user-images.githubusercontent.com/55429426/100326381-d961cd80-3004-11eb-995a-0c6d0fc48e0c.png)

**Comment by Maijh97** [comment]
I have tested that version 1.4.0 is working properly locally. Please check whether your variable value is correct, or you can try using fixed variables first.

**Comment by Maijh97** [comment]
Such as direct set `server.tomcat.accesslog.enabled=false`

**Comment by huangzgx** [comment]
I have modified this in the test environment. It seems that there is still such a log. The screenshot below is my test environment configuration, but the access_log log has been cleaned up by me today, and I can’t map it out.

![image](https://user-images.githubusercontent.com/55429426/100332092-edf59400-300b-11eb-9357-9b0dccc9fa46.png)

**Comment by Maijh97** [comment]
After setting up and restarting the service, will the new access_log continue to be generated?

**Comment by huangzgx** [comment]
The access_log log was generated today, which is about 7GB. When this configuration is modified, the service was restarted

![image](https://user-images.githubusercontent.com/55429426/100426348-acc4b900-30cb-11eb-99cd-aaae1bb94d8d.png)

**Comment by paderlol** [comment]
Pull the image again, and then restart, it should be a configuration problem, I have dealt with it before.
Refer to this issue #4022 PR #4021
