### ISSUE TITLE
Nacos does not have the correct loading priority for its own configuration files

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#4341]
**Describe the bug**

Nacos does not have the correct loading priority for its own configuration files

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/4590

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/4590
