### ISSUE TITLE
服务无法注册实例，也无法下线实例

### ISSUE THREAD

**Issue by 435915770** [alibaba/nacos#4360]
NACOS版本：1.1.4

问题：
1、服务实例都已下线，进程已不存在
2、触发保护阈值，但实际已经没有服务实例
3、点击服务，进服务详情，显示5个实例，健康状态false
4、服务详情里无法下线实例，代码调用api无法注册新增实例、下线实例
5、删除服务报错：specified service has instances, serviceName : DEV_GROUP@@service1

**Comment by paderlol** [comment]
你server端用的哪个版本

**Comment by 435915770** [comment]
是用着nacos-server-1.1.4

**Comment by paderlol** [comment]
客户端也是1.1.4？

**Comment by 435915770** [comment]
java客户端使用的nacos client是1.1.1版本

**Comment by paderlol** [comment]
可以先把客户端升级到1.1.4

**Comment by 435915770** [comment]
使用spring-boot-starter引入的，建议使用哪个版本呢？

**Comment by paderlol** [comment]
Spring boot starter 现在官方版本不止1.1.4吧？

**Comment by paderlol** [comment]
你也可以单独升级nacos client包也行

**Comment by 435915770** [comment]
升级了client 版本到1.1.4还是一样不行。跟我们注册、下线使用的方法有关系吗？
注册调用：void registerInstance(String serviceName, String groupName, String ip, int port) throws NacosException
下线调用：void deregisterInstance(String serviceName, String groupName, String ip, int port) throws NacosException

**Comment by paderlol** [comment]
日志有错误吗？naming的日志

**Comment by paderlol** [comment]
你可以看下这个issue #2378，你的情况和这个很相似

**Comment by KomachiSion** [comment]
一直没有删除实例信息吗？看一下是不是注册成持久化实例了，如果不是持久化实例，控制台一直是非健康状态，那应该是有问题了。

**Comment by KomachiSion** [comment]
@435915770 Any process?

**Comment by KomachiSion** [comment]
No response from author, so we think this problem has been fixed in newest problem.
