### ISSUE TITLE
NACOS_SERVER_PORT不起作用

### ISSUE THREAD

**Issue by hush0** [alibaba/nacos#4366]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by hush0** [comment]
版本1.2.1    k8s   上部署的时候添加  NACOS_SERVER_PORT = 9900   集群启动后，端口还是默认的8848

**Comment by paderlol** [comment]
不是用这个变量，请改成NACOS_APPLICATION_PORT

**Comment by paderlol** [comment]
具体参考readme https://github.com/nacos-group/nacos-docker/tree/1.2.1

**Comment by hush0** [comment]
thank you
