### ISSUE TITLE
cluster.conf 启动后被修改

### ISSUE THREAD

**Issue by zhouze-java** [alibaba/nacos#4370]
我在集群配置文件中配置了3台主机   
![image](https://user-images.githubusercontent.com/45086803/100620274-3210cd80-3359-11eb-8f8c-c6d25b5d9aec.png)  
  
前面两台是在一个内网中的, 第三台是在公网上面, 三台通信都正常,但是在第一个节点启动的时候 cluster.conf 这个文件会自动给我加一条 当前主机的内网ip, 然后启动之后是这样的    
  
![image](https://user-images.githubusercontent.com/45086803/100620545-7ef4a400-3359-11eb-81ec-232fe8e92527.png)  
  
后面启动的两台就不会再加,然后选不出来leader,服务也不能正常注册,想知道为啥会给我加了一条,我应该怎么配置   
  
我的版本是1.4.0

**Comment by chuntaojun** [comment]
你需要设置nacos.server.ip=本节点的外网IP，否则本节点不知道那个IP是自己

**Comment by zhouze-java** [comment]
> 你需要设置nacos.server.ip =本次的外网IP，否则本例程不知道那个IP是自己

![image](https://user-images.githubusercontent.com/45086803/100686748-ef331200-33b9-11eb-842f-1aaacf7248dc.png)  
  
设置了之后还是一样

**Comment by chuntaojun** [comment]
> > 你需要设置nacos.server.ip =本次的外网IP，否则本例程不知道那个IP是自己
> 
> ![image](https://user-images.githubusercontent.com/45086803/100686748-ef331200-33b9-11eb-842f-1aaacf7248dc.png)
> 
> 设置了之后还是一样

你有设置了之后把cluster.conf修正回来吗？每个节点都要修改的，如果不行，改下启动脚本添加jvm参数看下

**Comment by zhouze-java** [comment]
> > > 你需要设置nacos.server.ip =本次的外网IP，否则本例程不知道那个IP是自己
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45086803/100686748-ef331200-33b9-11eb-842f-1aaacf7248dc.png)
> > 设置了之后还是一样
> 
> 你有设置了之后把cluster.conf修正回来吗？每个节点都要修改的，如果不行，改下启动脚本添加jvm参数看下

改回来了, 我只启动了第一个节点, 还是每次启动都会加一个内网ip

**Comment by zhouze-java** [comment]
换了1.3.2版本之后没有这个问题了   1.4.0不行  原因还是没找到

**Comment by paderlol** [comment]
Cluster.conf文件有改成和你nacos.server.ip一样吗？

**Comment by paderlol** [comment]
还有 nacos.server.ip不能配置在application.properties里面，你如果是在application.properties里面需要使用这个参数`nacos.inetutils.ip-address`

**Comment by zhouze-java** [comment]
> nacos.inetutils.ip-address

这个参数也试过了  效果一样   然后我换了版本就可以了

**Comment by paderlol** [comment]
nacos.inetutils.ip-address 1.4.0有问题吗？

**Comment by zhouze-java** [comment]
> nacos.inetutils.ip-address
