### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by dqxfz** [alibaba/nacos#4377]
**Describe the bug**

The error message is shown  below:

```
request: /nacos/v1/ns/instance failed, servers: [222.198.178.192:8008], code: 500, msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Dec 01 15:53:45 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>
```

I assign read permission to the role 'ROLE_TEST' and  bind user 'test' with role 'ROLE_TEST', and this error occurred when I booting program.

but it works well when I assign read-write permission to the role 'ROLE_TEST'

**Expected behavior**
I want to give the role just read permission , my project just read properties when it booting, and discovery some service when it running , so I think it  doesn't need write permission

**Acutally behavior**
There was an error when starting my program

**Desktop (please complete the following information):**
 - OS:  docker
 - Version: nacos-server 1.4.0, nacos-client 1.3.3
 - Module: naming
 - SDK: spring-cloud-alibaba-nacos 2.2.3.RELEASE

**Comment by dqxfz** [comment]
I try to replace nacos-client with version 1.4.0，but it still doesn't work

**Comment by sanxun0325** [comment]
When you want read-only permissions，did you turn off automatic registration？

**Comment by dqxfz** [comment]
> When you want read-only permissions，did you turn off automatic registration？

thanks! I just search '/nacos/v1/ns/instance' from the Official documents and find that it is the api of register instance , so users must have the write permission。 I can install them(config server and discovery server) on a  machine respectively and control permission

**Comment by dqxfz** [comment]
The problem has been solved, thanks!
