### ISSUE TITLE
can not access http://ip:8848,and may there was sth wrong with innodb

### ISSUE THREAD

**Issue by zwllxs** [alibaba/nacos#4380]
i ran: docker-compose -f example/standalone-mysql-5.7.yaml up
then i got this:
![图片](https://user-images.githubusercontent.com/5228810/100720287-ba927b00-33f8-11eb-8964-15e6dc82eb19.png)
is it a bug?
and i can't access http://ip:8848,
if i ran curl command,got this: 
![图片](https://user-images.githubusercontent.com/5228810/100720411-ea418300-33f8-11eb-9811-a1d812fc48f4.png)
so how to fix it

**Comment by zwllxs** [comment]
the content of two pics is:

mysql         | 2020-12-01T09:02:06.720688Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql         | 2020-12-01T09:02:06.732348Z 0 [ERROR] [FATAL] InnoDB: Table flags are 0 in the data dictionary but the flags in file ./ibdata1 are 0x4800!
mysql         | 2020-12-01 09:02:06 0x7f6e9d916740  InnoDB: Assertion failure in thread 140113066682176 in file ut0ut.cc line 942
mysql         | InnoDB: We intentionally generate a memory trap.
mysql         | InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
mysql         | InnoDB: If you get repeated assertion failures or crashes, even
mysql         | InnoDB: immediately after the mysqld startup, there may be
mysql         | InnoDB: corruption in the InnoDB tablespace. Please refer to
mysql         | InnoDB: http://dev.mysql.com/doc/refman/5.7/en/forcing-innodb-recovery.html
mysql         | InnoDB: about forcing recovery.
mysql         | 09:02:06 UTC - mysqld got signal 6 ;
mysql         | This could be because you hit a bug. It is also possible that this binary
mysql         | or one of the libraries it was linked against is corrupt, improperly built,
mysql         | or misconfigured. This error can also be caused by malfunctioning hardware.
mysql         | Attempting to collect some information that could help diagnose the problem.
mysql         | As this is a crash and something is definitely wrong, the information
mysql         | collection process might fail.
mysql         |
mysql         | key_buffer_size=8388608
mysql         | read_buffer_size=131072
mysql         | max_used_connections=0
mysql         | max_threads=151
mysql         | thread_count=0
mysql         | connection_count=0
mysql         | It is possible that mysqld could use up to
mysql         | key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 68196 K  bytes of memory
mysql         | Hope that's ok; if not, decrease some variables in the equation.
mysql         |
mysql         | Thread pointer: 0x0
mysql         | Attempting backtrace. You can use the following information to find out
mysql         | where mysqld died. If you see no messages after this, something went
mysql         | terribly wrong...
mysql         | stack_bottom = 0 thread_stack 0x40000
mysql         | mysqld(my_print_stacktrace+0x2c)[0x55ea8a26dfbc]


and 

[root@iZuf6dintgcdt0ovkw6zvtZ home]# curl http://127.0.0.1:8848
curl: (56) Recv failure: Connection reset by peer

**Comment by zwllxs** [comment]
but if i download the gz  file and run :  sh startup.sh -m standalone,
the website 'http://127.0.0.1:8848' can be accessed

**Comment by paderlol** [comment]
You need to delete the mounted MySQL directory volume because the Mysql volume already exists.
