### ISSUE TITLE
Spring Cloud Nacos中怎么获取配置（自定义配置文件）的值

### ISSUE THREAD

**Issue by IanZqf** [alibaba/nacos#4385]
在使用nacos spring boot版本的时候，是通过在对应的配置类中加@NacosConfigurationProperties注解实现，但据说Spring cloud nacos的对@NacosConfigurationProperties不支持，那请问下要怎么实现

**Comment by IanZqf** [comment]
具体的需求请参考https://github.com/alibaba/nacos/issues/4378

**Comment by KomachiSion** [comment]
原issue中不是已经解答了吗？ 你需要学习的是spring cloud怎么获取配置，而不是纠结NacosConfigurationProperties注解。因为他两应该是不同的入口。

**Comment by chuntaojun** [comment]
spring cloud 暂不支持@NacosXXX相关注解，如果需要，可以移步至SCA社区寻求支持

**Comment by chuntaojun** [comment]
目前SCA有自己的一套配置刷新体系（基于SC），所以nacos的注解目前SCA都还没有支持

**Comment by yanlinly** [comment]
首先依赖spring-framework/spring-boot/spring-cloud 是有不同能力的。  在不同的框架依赖程度上选择不同注解就好了。 

考虑到部分用户没有使用spring-cloud体系，所以在没有这个框架的时候，我们提供了一些注解支持。
