### ISSUE TITLE
1.3.2数据库把nacos的账号密码都删了，还能登陆？而且新改的账号密码还是无法登陆（没有特殊字符）

### ISSUE THREAD

**Issue by zhu1227** [alibaba/nacos#4386]
1.3.2的server数据库把nacos的账号密码都删了，还能使用nacos/nacos登陆？而且新改的账号密码还是无法登陆（没有特殊字符）
The server database of 1.3.2 has deleted the account and password of Nacos, and can you log in using Nacos / Nacos? And the new account password still can't log in (no special characters)

**Comment by KomachiSion** [comment]
麻烦按照issue模版详细描述下复现步骤，仅依靠当前的描述，我只能认为是缓存或者cookie还在生效中。

**Comment by zhu1227** [comment]
![1606904700(1)](https://user-images.githubusercontent.com/54474743/100860892-0feb8c80-34cc-11eb-94b3-9d1bab7ffdfa.png)
我在数据库在user表以及role表中在nacos名字后面加了个123，但是清理所有缓存后尝试用nacos123登录，账号密码错误。但是同样使用nacos/nacos却可以登录：
db.url.0=jdbc:mysql://192.168.3.189:3301/test_nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=test_nacos
db.password=test_nacos
nacos.core.auth.enabled=true
INSERT INTO `test_nacos`.`users`(`username`, `password`, `enabled`) VALUES ('nacos123', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);
INSERT INTO `test_nacos`.`roles`(`username`, `role`) VALUES ('nacos123', 'ROLE_ADMIN');

**Comment by zhu1227** [comment]
我试了一下，不改账号账号依旧是nacos而密码更改，是可以的，权限也是globalAdmin的。

**Comment by zhu1227** [comment]
不改账号账号依旧是nacos而密码更改，是可以的，权限也是globalAdmin的。暂时满足需求
