### ISSUE TITLE
Nacos配置项被删后，用@NacosValue注解springboot读值为spring配置文件中的值，而用@NacosConfigurationProperties读值则为删除前的值

### ISSUE THREAD

**Issue by lianX820** [alibaba/nacos#4388]
springboot程序中有一个配置文件为application-graph.yml，内容如下：
![graphYML](https://user-images.githubusercontent.com/57701742/100844573-00157d80-34b7-11eb-9213-45c53a58ac44.png)
其中url用@NacosValue注解：
![url](https://user-images.githubusercontent.com/57701742/100844869-5da9ca00-34b7-11eb-90b7-6b84e759efa6.png)
graph写了javabean并用@NacosConfigurationProperties注解跟配置文件绑定
![graph-bean](https://user-images.githubusercontent.com/57701742/100845059-9e094800-34b7-11eb-867c-eb8405850c2e.png)
application.yml内容如下：
![applicationYML](https://user-images.githubusercontent.com/57701742/100845529-5636f080-34b8-11eb-9be5-88d20d177609.png)

nacos server配置了相应的配置：
![nacos](https://user-images.githubusercontent.com/57701742/100846550-9fd40b00-34b9-11eb-9c2f-d48cf7f04e09.png)

启动程序，查询正常，返回的都是nacos server上的值：
![get1](https://user-images.githubusercontent.com/57701742/100847040-3274aa00-34ba-11eb-847d-c6bbdf48dd6b.png)
但当删除nacos server中配置文件的值后，用@NacosValue注解的url值为spring配置文件中的值，而用@NacosConfigurationProperties注解的graph读的还是远程删除前的值：
![nacos2](https://user-images.githubusercontent.com/57701742/100847739-289f7680-34bb-11eb-8e8c-b868a139e1d0.png)
![get2](https://user-images.githubusercontent.com/57701742/100847767-2e955780-34bb-11eb-8e8e-be80f3f3ad7b.png)

为什么graph不能读到spring配置文件中的值呢？有什么办法可以读到吗？@NacosValue和@NacosConfigurationProperties不能达到同样的效果吗

nacos版本：1.4.0
```
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.7</version>
</dependency>
```

**Comment by KomachiSion** [comment]
应该不行，不然也不需要分两个注解了。

**Comment by lianX820** [comment]
那这种用bean绑定配置的方式，有什么方式可以让它当远程值被删除时可以读到spring下配置文件的值吗？

**Comment by chuntaojun** [comment]
> 那这种用bean绑定配置的方式，有什么方式可以让它当远程值被删除时可以读到spring下配置文件的值吗？

这个目前不行

**Comment by lianX820** [comment]
好的谢谢。
另外还想问一下，在不重启spring服务的前提下，动态切换groupId或者namespace，这个可以通过什么方式做到吗

**Comment by KomachiSion** [comment]
那你可能需要自己实现一个spring的loader，当namespace改变的时候，把原来的nacos-client停止掉，然后创建一个新的nacos-client替换掉。

**Comment by lianX820** [comment]
动态更换groupId也只能这样实现吗？

**Comment by chuntaojun** [comment]
> 动态更换groupId也只能这样实现吗？

这些动态的东西，你都要自己去操作实现，本地配置的动态变更，不再springboot的设计里面
