### ISSUE TITLE
想要动态的添加dataId

### ISSUE THREAD

**Issue by helloyaoge** [alibaba/nacos#4392]
![image](https://user-images.githubusercontent.com/12529019/100878425-205c3100-34e5-11eb-82e4-e9101c77e8c6.png)

貌似初始化之后，getExtensionConfigs 就不可以动态的修改了

**Comment by chuntaojun** [comment]
你的需求是什么？nacos-client是不会有上述限制的，你可以自己根据需要动态的调整需要监听什么配置，这个应该是SCA的问题

**Comment by zongtanghu** [comment]
Please give a detailed description for this issue, @helloyaoge

**Comment by helloyaoge** [comment]
在一个namespacce，存在多个dataId ，spring cloud 在启动的时候会在配置文件中配置是否要加载某个dataId。 我会根据用户配置的dataId 动态的加载他的dataId对应的配置。spring cloud 有一个扩展配置，用的是list结构，但是，不好用。list[0] list[1] 这种，如果某个用户想把list[0] 注释掉，list[1]的索引要改动。 这个数据结构可以改成set。

**Comment by yanlinly** [comment]
> 在一个namespacce，存在多个dataId ，spring cloud 在启动的时候会在配置文件中配置是否要加载某个dataId。 我会根据用户配置的dataId 动态的加载他的dataId对应的配置。spring cloud 有一个扩展配置，用的是list结构，但是，不好用。list[0] list[1] 这种，如果某个用户想把list[0] 注释掉，list[1]的索引要改动。 这个数据结构可以改成set。

你把你的业务场景和产品使用耦合在一起表达了。 你的技术问题是什么呢？   我认为你是启动会有一些业务判断确定加载的配置，这个场景建议直接使用nacos-sdk实现。  如果使用了spring-cloud封装，你的自己把控能力就会弱化了。

**Comment by KomachiSion** [comment]
Close issue due to no response from author and the problem is an usage problem.
