### ISSUE TITLE
集群配置--更新集群 里面做任何修改保存操作都返回403

### ISSUE THREAD

**Issue by Yanwenjingcn** [alibaba/nacos#4396]
![image](https://user-images.githubusercontent.com/16257260/100990208-99fb2a00-358c-11eb-867b-f2dad4b57258.png)

![image](https://user-images.githubusercontent.com/16257260/100990492-e181b600-358c-11eb-894f-a479e33d38de.png)

版本：1.4.0 beta

想试试修改检查端口，一保存就报403

不知道是否是使用方式问题

不知道服务管理有没有更详细的文档，像更新集群的检查类型使用、服务路由类型的使用都没看到比较详细的文档讲解，看得有点懵逼

**Comment by wangweizZZ** [comment]
duplicate with #3005
