### ISSUE TITLE
Didn't clear datums in com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#shutdown.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4403]
**Describe the bug**
Now in `com.alibaba.nacos.naming.consistency.persistent.raft.RaftConsistencyServiceImpl#RaftConsistencyServiceImpl`'s constructor, it will subcribe isAllNewVersion. If it's true, will shutdown old raft core. 

In the shutdown logic, it will the clear old datums, the old datums load from old version raft file when application start, the data already act on serviceManager and service. If all server are version, we can stop the old raft work, but shouldn't clear datums.

Particularly, when I start nacos with standalone mode, `isAllNewVersion` will direct return true, there will be strange phenomenon in this case. If serviceManager listen raftCore before raftCore shutdown, it will read instances from old datum. If serviceManager listen raftCore after raftCore shuwdown, it can't read instances from old datum.

So, I think we just stop the raft core work, needn't clear old datums.

**Comment by KomachiSion** [comment]
If start standalone, it should old all raft and clear all raft data to release memory. And read data from disk directly.

**Comment by horizonzy** [comment]
> If start standalone, it should not start any raft and clear all raft data to release memory. And read data from disk directly.
> 
> But your problem might happen in one node cluster. So we need to discuss a solution to release this memory with a safety way.

I'm sure I start with standalone mode, `com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#init`, it will load data from disk, and then `com.alibaba.nacos.naming.core.ServiceManager#init`, it will listen raftCore datum, load service. In service init, it also listen raftCore datum, load instances. 

The process rely on raftCore datums, so if the process before or after datums clear, the result will not be same.

**Comment by KomachiSion** [comment]
> > If start standalone, it should not start any raft and clear all raft data to release memory. And read data from disk directly.
> > But your problem might happen in one node cluster. So we need to discuss a solution to release this memory with a safety way.
> 
> I'm sure I start with standalone mode, `com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore#init`, it will load data from disk, and then `com.alibaba.nacos.naming.core.ServiceManager#init`, it will listen raftCore datum, load service. In service init, it also listen raftCore datum, load instances.
> 
> The process rely on raftCore datums, so if the process before or after datums clear, the result will not be same.

Yes, beacuse current version has no completely implement what's I said.

**Comment by horizonzy** [comment]
I think again, it's no problem.
