### ISSUE TITLE
raftGroupMember in NodeMetaData is still three server when nacos from cluster mode with 3 to standalone mode

### ISSUE THREAD

**Issue by roadToit** [alibaba/nacos#4406]
**Describe the bug**
First，I start three nacos node on three server with cluster mode. It's OK.
Then, I stop the three nacos. And I remove the cluster.conf file on the three server.
Then, I start one of the nacos server with command: sh startup.sh -m standalone.
Result is: the nacos node start successfully and I can open the nacos console on web. Then I go to the Cluster Node List, 
the server ip is displayed, but the "raftGroupMember" in the NodeMetaData has three member which is the cluster mode three nacos server before. It's a problem. I only start one and on standalone mode, why raftGroupMember is still with three?
**Expected behavior**
raftGroupMember with member only itselfraftGroupMember 
**Acutally behavior**
A clear and concise description of what you actually to happen.
raftGroupMember with three member
**How to Reproduce**
start nacos on cluster mode with three node, when start successful then stop them.
start one of the three nacos servers on standalone mode.
open the standalone nacos server's web console
Cluster Node List, 
raftGroupMember in NodeMetaData with three server-addr, just the three cluster mode nacos server before.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] Ubuntu
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] nacos-server-1.4.0
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo] jdk1.8 spring-cloud-alibaba 2.2.3

**Additional context**

**Comment by chuntaojun** [comment]
Cluster mode and stand-alone mode are not solved by restarting. You need to clear all data under ${nacos.home}/data

**Comment by roadToit** [comment]
> Cluster mode and stand-alone mode are not solved by restarting. You need to clear all data under ${nacos.home}/data

Thank you for your answer! The problem has been resolved through your answer.
