### ISSUE TITLE
The spring cloud gateway forwards request to the services of other nacos groups

### ISSUE THREAD

**Issue by weihai4099** [alibaba/nacos#4407]
**Is your feature request related to a problem? Please describe.**

网关和业务分别注册到不同的nacos group。网关无法将请求转发到其他组的业务微服务。

**Describe the solution you'd like**

使用spring cloud gateway 做统一api 网关，理论上需要将请求调度到任意命名空间和任意组的服务。但目前的策略，微服务只能发现同命名空间下同组的服务。或者说现在的流行做法都是一个项目一个网关么？

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
命名空间是强隔离设计，就是让需要隔离的对象完全屏蔽其他对象，如果你需要感知其他，那就不是强隔离要求，是不能使用ns来进行隔离的，可以试着用group来隔离。

**Comment by KomachiSion** [comment]
比如不同的租户，不同的运行环境，这种绝对不能感知和调用到的 适合用ns来做。

**Comment by weihai4099** [comment]
您好，我现在的场景是不需要强隔离，假设在同一个ns中，gateway在一个group A，某业务服务在另一个group B。我想将gateway收到的请求可以转发到group B的服务，但现在每一个微服务只能发现和自己同group的服务。

**Comment by chuntaojun** [comment]
> 您好，我现在的场景是不需要强隔离，假设在同一个ns中，gateway在一个group A，某业务服务在另一个group B。我想将gateway收到的请求可以转发到group B的服务，但现在每一个微服务只能发现和自己同group的服务。

这是Springcloud的限制，他们没有group的概念，所以你没法实现，除非你自己操作nacos-client，是可以做到发现同个namespace下的不同group的服务

**Comment by weihai4099** [comment]
是的，我理解这个问题。但是从nacos这边来说，也可以去做改造，就看是否有必要了。既然现有的设计不支持，我想问一下，一般group常用来解决什么问题？

**Comment by chuntaojun** [comment]
> 是的，我理解这个问题。但是从nacos这边来说，也可以去做改造，就看是否有必要了。既然现有的设计不支持，我想问一下，一般group常用来解决什么问题？

springcloud-alibaba很难去支持这个，因为要支持的话，基本整个sc的体系都要改过，group你可以参考dubbo的group，

**Comment by weihai4099** [comment]
👌
