### ISSUE TITLE
read json config faild

### ISSUE THREAD

**Issue by HumorChen** [alibaba/nacos#4408]
Type: bug report
descriptions:
dataid  example
format json
![image](https://user-images.githubusercontent.com/46368749/101128518-d08f7e00-363a-11eb-84fb-ceb9764dd2bc.png)
and my java code 
![image](https://user-images.githubusercontent.com/46368749/101128606-003e8600-363b-11eb-8ef0-fa2d7faa73d1.png)
access http://localhost/nacos/systemSwitch result
![image](https://user-images.githubusercontent.com/46368749/101128685-23693580-363b-11eb-9087-c952854e9596.png)
echo placeholder value false,but if i change config format to properties or yaml，it correctly echo true、

json config {"a":1},i want to  access a with code like ,just like yaml 
@NacosValue(value = "${a:0}",autoRefreshed = true)
    private boolean systemSwitch;

my environment
springboot 2.2.2.RELEASE
nacos 0.2.7

**Comment by HumorChen** [comment]
json config ,for example 
{
    "a":1,
    "b":{
        "c":2,
        "d":3
    }
}
if i want get a,i want to  code like @NacosValue("${a:0}"),
get d code like @NacosValue("${b.d:0}")
but  i test faild, format properties or yaml success

**Comment by chuntaojun** [comment]
please see here

**Comment by chuntaojun** [comment]
or here ： https://github.com/nacos-group/nacos-spring-project/blob/master/nacos-spring-context/src/test/java/com/alibaba/nacos/spring/context/annotation/config/NacosPropertySourceJsonTest.java

**Comment by HumorChen** [comment]
> or here ： https://github.com/nacos-group/nacos-spring-project/blob/master/nacos-spring-context/src/test/java/com/alibaba/nacos/spring/context/annotation/config/NacosPropertySourceJsonTest.java

problem resolved after use type=ConfigType.JSON,thank you! but why i use format properties or yaml do not need this type config

**Comment by chuntaojun** [comment]
> > or here ： https://github.com/nacos-group/nacos-spring-project/blob/master/nacos-spring-context/src/test/java/com/alibaba/nacos/spring/context/annotation/config/NacosPropertySourceJsonTest.java
> 
> problem resolved after use type=ConfigType.JSON,thank you! but why i use format properties or yaml do not need this type config

The default configuration file parses properties
