### ISSUE TITLE
服务发现，服务的数据是存储在本地么

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4409]
服务发现中服务的数据是存储在本地么。存储在每个节点的磁盘上么。
使用k8s部署时，就必须改在持久卷了吧。
服务发现可以使用外部存储么

**Comment by KomachiSion** [comment]
目前用的是本地存储。

**Comment by wanghuigithub** [comment]
好的，本地磁盘是吧

**Comment by chuntaojun** [comment]
> 好的，本地磁盘是吧

只有注册为持久化实例才会将服务数据存储在本地，否则都是在内存中，具体的路径在${nacos.home}/data/naming中
