### ISSUE TITLE
stitic修饰的变量从nacos上读取的值为null

### ISSUE THREAD

**Issue by Cocowwy** [alibaba/nacos#4414]
stitic修饰的变量从nacos上读取的值为null
![image](https://user-images.githubusercontent.com/63331147/101274607-978e0f80-37da-11eb-8aab-3d395c197af9.png)
![image](https://user-images.githubusercontent.com/63331147/101274614-a1b00e00-37da-11eb-99c8-0d96526e843b.png)

**Comment by chuntaojun** [comment]
使用springcloud-alibaba？

**Comment by chuntaojun** [comment]
如果是使用nacos-springboot或者nacos-spring-context的，确实是无法操作static类型的变量的

**Comment by Cocowwy** [comment]
使用的是springcloud alibaba

**Comment by KomachiSion** [comment]
看一下nacos的日志，是否接收到了正确的配置推送，  如果正确接收到了， 麻烦把这个issue转给SCA社区。

**Comment by chuntaojun** [comment]
> 使用的是springcloud alibaba

你确定@Value可以给static变量赋值？

**Comment by Cocowwy** [comment]
我用的@value只能给没有修饰static的变量赋值，修饰了static的读取的为空，默认值都没有用到------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;liaochuntao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月7日(星期一) 中午1:27
收件人:&nbsp;&quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;;
抄送:&nbsp;&quot;Cocowwy&quot;<514658459@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] stitic修饰的变量从nacos上读取的值为null (#4414)

**Comment by ljhrot** [comment]
static is evil
你不应该将值注入静态变量，spring 也不支持这样的操作。

如果你无法避免这样的实现，可以在增加非静态字段的配置类（可以通过 @Value 注入的），然后在将恰当的时机将字段属性值拷贝到静态字段的类。

如果你还想实现动态刷新配置，可以看看 Spring 提供的 `RefreshScopeRefreshedEvent`
```java
@EventListener(RefreshScopeRefreshedEvent.class)
public void onRefresh(RefreshScopeRefreshedEvent event) {
    // do something
}
```

**Comment by Cocowwy** [comment]
好的，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;ljhrot&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月8日(星期二) 上午9:36
收件人:&nbsp;&quot;alibaba/nacos&quot;<nacos@noreply.github.com&gt;;
抄送:&nbsp;&quot;Cocowwy&quot;<514658459@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] stitic修饰的变量从nacos上读取的值为null (#4414)
