### ISSUE TITLE
Com. Alibaba. Nacos. Sys. File. WatchFileCenter# registerWatcher registerWatcher methods recorded in the WATCH the number of jobs is the actual number of recorded call registerWatcher method

### ISSUE THREAD

**Issue by haojiawei111** [alibaba/nacos#4415]
**Describe the bug**
Com. Alibaba. Nacos. Sys. File. WatchFileCenter# registerWatcher 
The NOW_WATCH_JOB_CNT variable in method registerWatcher  actually records the number of watchdirjobs or the number of FileWatcher, but NOW_WATCH_JOB_CNT currently records the number of calls to method registerWatcher.
This is not consistent with the original intent of creating the NOW_WATCH_JOB_CNT variable.
![图片](https://user-images.githubusercontent.com/35454277/101275528-433a5e00-37e1-11eb-9740-2664d220785e.png)

**Expected behavior**
The NOW_WATCH_JOB_CNT variable should be added one when putting WatchDirJob or when calling addSubscribe

**Comment by chuntaojun** [comment]
Welcome to contribute to the solution

**Comment by haoyann** [comment]
@I will sove it@

**Comment by haoyann** [comment]
@I will sove it@
