### ISSUE TITLE
How to configure auth authentication in Nacos OpenAPI？

### ISSUE THREAD

**Issue by xiaoymin** [alibaba/nacos#4422]
In the current OpenAPI document on Nacos official website, I don't see how to configure permissions for the interface.

Does it mean that Nacos metadata can be accessed arbitrarily using OpenAPI？

https://nacos.io/zh-cn/docs/open-api.html

**Comment by catcherwong** [comment]
Take a look on this documentation.

https://nacos.io/zh-cn/docs/auth.html

**Comment by xiaoymin** [comment]
Thanks
