### ISSUE TITLE
nacos  从哪个版本开始支持权限控制的, 1.1.4  版本是否能增加权限控制

### ISSUE THREAD

**Issue by lucian521** [alibaba/nacos#4423]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by catcherwong** [comment]
1.2.0开始支持的

可以参考下面的文档

https://nacos.io/zh-cn/blog/nacos%201.2.0%20guide.html
