### ISSUE TITLE
In ServiceController's "create" method a optional param is actually required

### ISSUE THREAD

**Issue by Xezeloh** [alibaba/nacos#4424]
**Describe the bug**
In the naming module, ServiceController's "create" method has an optional parameter protectThreshold. However, since it is a basic type and has no default value, if this parameter is not provided in actual use, an error will be reported.
naming模块中，ServiceController的create方法有一个可选参数protectThreshold，但由于其是基本类型且无默认值，在实际使用中如果不提供这个参数会导致报错。

**Expected behavior**
A request sent to the api create with out the param protectThreshold get an ok returned.

**Acutally behavior**
nacos return this:
caused: Optional float parameter 'protectThreshold' is present but cannot be translated into a null value due to being declared as a primitive type. Consider declaring it as object wrapper for the corresponding primitive type.;

**How to Reproduce**
curl -X POST "127.0.0.1:8848/nacos/v1/ns/service?serviceName=12e"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version nacos-server 1.3.2
 - Module naming

**Additional context**
No

**Comment by neighbor-uncleWang** [comment]
@i will solve it@

**Comment by neighbor-uncleWang** [comment]
To archive this goal,here is my plan:
   Modify the parameter to the packaging type, and then convert the null to 0.0L in the method.

我的计划是：
      将参数修改为包装类型，然后在方法里面将null转换为0.0L。

**Comment by Xezeloh** [comment]
> To archive this goal,here is my plan:
> Modify the parameter to the packaging type, and then convert the null to 0.0L in the method.
> 
> 我的计划是：
> 将参数修改为包装类型，然后在方法里面将null转换为0.0L。

那为啥不直接在形参那儿赋个默认值0.0

**Comment by neighbor-uncleWang** [comment]
对耶，默认值直接defaultValue

**Comment by liuweizhenhaoa** [comment]
> 对耶，默认值直接defaultValue

i want to know did you submit this issue

**Comment by neighbor-uncleWang** [comment]
周末再提交，最近工作日比较忙
