### ISSUE TITLE
nacos配置中心存储配置，linux会保存文件，文件中存在敏感信息，该如何处理？

### ISSUE THREAD

**Issue by ljh205sy** [alibaba/nacos#4425]
## Issue Description

nacos的配置中心会存储配置信息，配置信息磁盘会在磁盘中有存储，但是存储会存在系统的漏洞

[001238]/root/nacos/config/fixed-90.33.147.42_8848-a338c762-d2a7-4a2f-86f0-022c171c0928_nacos/snapshot-tenant/a338c762-d2a7-4a2f-86f0-022c171c0928/DEFAULT_GROUP/server-sys.yml:38

### How to reproduce it (as minimally and precisely as possible)

1.  启动nacos服务
2.  default空间中新增 一个server-sys.yaml文件， 文件中写入password等敏感信息
3.  敏感信息在linux文件系统中可查看到此文件，以敏感信息存在

**Comment by KomachiSion** [comment]
配置中如果有敏感数据，需要用户在发布配置时自行脱敏，然后在业务处理时自行恢复。

对nacos而言配置内容时无语意的，配置的内容是什么，nacos就保持不变地读取并保存快照。

**Comment by shiyiyue1102** [comment]
com.alibaba.nacos.client.config.utils.SnapShotSwitch#setIsSnapShot，可以通过这个静态方法关闭本地缓存，这个文件是为了容灾用的，如果服务端调用失败了会读取本地，如果关闭了，需要评估下对业务的影响
