### ISSUE TITLE
如何只针对某个namespace告警

### ISSUE THREAD

**Issue by yangyaoshierdan** [alibaba/nacos#4428]
目前根据namespace区分环境，如果只想对生产环境的namespace做监控告警，该怎么配置？

**Comment by KomachiSion** [comment]
所谓生产环境namespace是你的业务语意，nacos没法作区分。nacos上报给prometheus的监控信息应该是针对nacos整体的。 没有依据namespace（因为这个是使用方自己的业务语意）。

如果你有这个需求，可以自行修改nacos的监控信息采集。

**Comment by yangyaoshierdan** [comment]
好的，感谢大佬
