### ISSUE TITLE
怎样开启mcp

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4429]
使用k8s部署，怎样开启mcp

**Comment by chuntaojun** [comment]
nacos.istio.mcp.server.enabled=false

**Comment by wanghuigithub** [comment]
> nacos.istio.mcp.server.enabled=false
使用k8s部署。直接修改home/nacos/conf/application.properties这个文件？       
怎样观察已开启

**Comment by KomachiSion** [comment]
可以看一下官方镜像是否有环境变量可以修改这个值，如果不行，请参考官方镜像的example， 自行build镜像，build镜像时可以把这个参数在镜像中调整，这样就可以支持k8s了。

**Comment by wanghuigithub** [comment]
> 可以看一下官方镜像是否有环境变量可以修改这个值，如果不行，请参考官方镜像的example， 自行build镜像，build镜像时可以把这个参数在镜像中调整，这样就可以支持k8s了。

嗯嗯 我现在已经重新打了镜像并且加上了参数。 现在不知道观察什么指标来确认。mcp已经被开启了

**Comment by wanghuigithub** [comment]
> 可以看一下官方镜像是否有环境变量可以修改这个值，如果不行，请参考官方镜像的example， 自行build镜像，build镜像时可以把这个参数在镜像中调整，这样就可以支持k8s了。

使用nacos-docker项目重新打了镜像。做了如下修改：
配置文件中增加了nacos.istio.mcp.server.enabled=true
![image](https://user-images.githubusercontent.com/11936135/101567508-e8387f00-3a0b-11eb-91fa-5a59864f800a.png)

但是在istio-main.log中没有打印mcp server启动的日志。

**Comment by wsx812585705** [comment]
IstioConfig类中 final boolean mcpServerEnabled = false， 本地调试发现设置了nacos.istio.mcp.server.enabled=true，
启动NacosMcpServer
if (!istioConfig.isMcpServerEnabled()) {
            return;
        }
还是会return,
在ISSUE#2992提交中新增的final修饰。这是否是个bug.

**Comment by wanghuigithub** [comment]
> IstioConfig类中 final boolean mcpServerEnabled = false， 本地调试发现设置了nacos.istio.mcp.server.enabled=true，
> 启动NacosMcpServer
> if (!istioConfig.isMcpServerEnabled()) {
> return;
> }
> 还是会return,
> 在ISSUE#2992提交中新增的final修饰。这是否是个bug.

其实在nacos-docker项目中，配置文件没有被正确读取到。所以配置不会生效。我直接更改的代码，把代码中默认的false改为了true。并重新打包，构建镜像。问题解决

**Comment by LoseyourseIf** [comment]
> > IstioConfig类中 final boolean mcpServerEnabled = false， 本地调试发现设置了nacos.istio.mcp.server.enabled=true，
> > 启动NacosMcpServer
> > if (!istioConfig.isMcpServerEnabled()) {
> > return;
> > }
> > 还是会return,
> > 在ISSUE#2992提交中新增的final修饰。这是否是个bug.
> 
> 其实在nacos-docker项目中，配置文件没有被正确读取到。所以配置不会生效。我直接更改的代码，把代码中默认的false改为了true。并重新打包，构建镜像。问题解决

nacos-docker 可以配置挂载 custom.properties 开启 MCP
根本问题是  [IstioConfig.java](https://github.com/alibaba/nacos/blob/develop/istio/src/main/java/com/alibaba/nacos/istio/misc/IstioConfig.java)
中 `mcpServerEnabled` 被 final 修饰了
``` 
@Value("${nacos.istio.mcp.server.enabled:false}")
private final boolean mcpServerEnabled = false;
```
1.3.0 以后的版本只有自己修改代码打包镜像
