### ISSUE TITLE
[DISCUSS] 1.4.1 Whether you want to remove the old Raft logic

### ISSUE THREAD

**Issue by chuntaojun** [alibaba/nacos#4430]
**Is your feature request related to a problem? Please describe.**

when nacos release version to 1.4.1, the old Raft logic should remove or keep on?

in my option, 1.4.1 shoul remove old raft protocol and just use the consistency layer of the core module

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by horizonzy** [comment]
what is long raft logic?

**Comment by KomachiSion** [comment]
I would like to keep this logic to at least 1.4.2 or 1.5.0/2.1.0. The reason following:

1. If we remove it in 1.4.1. user need upgrade to 1.4.0 first and them to other version. I think we should give a range version not just one single version.
2. Jraft with nacos we need some version to push and make it more stable. Like standalone mode, startup judgement and so on. 

So I prefer that we can remove the old raft in next feature version or  main version.

**Comment by chuntaojun** [comment]
I hope to be able to remove this baggage by 2.0

**Comment by KomachiSion** [comment]
We may need to support upgrade from some 1.X version to 2.0.X version. But now we need complete 2.0.0 feature first. 

And we also need to discuss from which version of 1.X can upgrade to 2.0.X. If we only support 1.4.X upgrade to 2.0.X, we can remove this old raft logic.
