### ISSUE TITLE
Compatible problem when old raft instances file between new raft instances file.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4431]
**Describe the bug**
the old raft instances file like `com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@demoService.datum` end with `.datum`, the new raft instances file `com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@demoService` without endfix `.datum`. 
When user upgrade nacos server,  all the raft operation based on new file, the old file can't be take over.  if user register new persist instances to the old service which hold old raft instances, there will be two files about instances info. When nacos server reboot, the old instances and new instances will cover each other, the final instances result is wrong.

Append documen to tell user this situation, need change fileName to new format when upgrade server.
Or fix it in backend? 

What do you think of it. @chuntaojun @KomachiSion

**Comment by KomachiSion** [comment]
I has revert this `.datum` in 1.4.0.  The old version `.datum` has some problem when I test.

the `.datum` feature seems only affect 1.3.2 version.

**Comment by horizonzy** [comment]
> I has revert this `.datum` in 1.4.0. The old version `.datum` has some problem when I test.
> 
> In 1.3.1 and 1.3.2 which add `.datum`. The file will be created and then be removed Immediately, See #3550

That's lucky!
