### ISSUE TITLE
Configure encryption in configuration service

### ISSUE THREAD

**Issue by michaelSpica** [alibaba/nacos#4432]
**At present, most of the configuration services are configured with information such as account and password. Password information should not be exposed. Please consider the function of encrypting and storing sensitive information**

**Comment by KomachiSion** [comment]
Nacos can't judge whether the information is sensitive because it only users knows.
So I think it's a feature user need to do rather than nacos configuration center.

nacos only is a server to save, modified and distribute the config, should not control the config context itself.
