### ISSUE TITLE
'com.alibaba.nacos.consistency.entity' packages loss in module 'consistency' for  branch  2.0.0

### ISSUE THREAD

**Issue by xing0228** [alibaba/nacos#4433]
## Issue Description

'com.alibaba.nacos.consistency.entity' packages loss in module 'consistency' for  branch  2.0.0
class 'com.alibaba.nacos.consistency.ProtoMessageUtil' need import package  'com.alibaba.nacos.consistency.entity'

### Describe what happened (or what feature you want)
i will start nacos-server application on my machine, but can't starting.
error: can not found packages 'com.alibaba.nacos.consistency.entity'

### Describe what you expected to happen
i want to starting nacos-server application

### How to reproduce it (as minimally and precisely as possible)

1. start nacos-server application on  branch 2.0.0
2. 
3. 

### Anything else we need to know?

**Comment by KomachiSion** [comment]
`com.alibaba.nacos.consistency.entity` is auto generated by protobuf. Please compile or instance project by yourself.

I will upgrade the document to describe this situation.

**Comment by xing0228** [comment]
thanks . The problem has already been solved。
