### ISSUE TITLE
在mac os big sur 系统版本下无法启动nacos

### ISSUE THREAD

**Issue by sdywcd** [alibaba/nacos#4435]
1，通过官方文档提供的信息执行 
  sh startup.sh -m standalone
2，日志显示（系统中没有/Libraray/Internet文件）
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/beibei/Documents/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/beibei/Documents/nacos/plugins/health,/Users/beibei/Documents/nacos/plugins/cmdb -Dnacos.home=/Users/beibei/Documents/nacos -jar /Users/beibei/Documents/nacos/target/nacos-server.jar  --spring.config.location=file:/Users/beibei/Documents/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/Users/beibei/Documents/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
**nohup: /Library/Internet: No such file or directory**

**Comment by KomachiSion** [comment]
duplicate with #4227
