### ISSUE TITLE
Fail to create service with labelSelector.

### ISSUE THREAD

**Issue by Xezeloh** [alibaba/nacos#4436]
**Describe the bug**
I tried to create a service with labelSelector but got this:
```plain
ErrCode:400, ErrMsg:failed to req API:/api//nacos/v1/ns/service after all servers([127.0.0.1:8848]) tried: caused: specified service already exists, serviceName : DEFAULT_GROUP@@cross-site-server;
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:490)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:395)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:391)
	at com.alibaba.nacos.client.naming.net.NamingProxy.createService(NamingProxy.java:276)
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.createService(NacosNamingMaintainService.java:133)
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.createService(NacosNamingMaintainService.java:128)
	at com.alibaba.nacos.spring.factory.DelegatingNamingMaintainService.createService(DelegatingNamingMaintainService.java:89)
...
```
My code is as below:
```java
@SpringBootApplication
public class CrossSiteServerApplication {

	@NacosInjected
	private NamingMaintainService namingMaintainService;

	@NacosInjected
	private NamingService namingService;

	@Value("${spring.application.name}")
	private String applicationName;

	@Value("${service.provider.ip}")
	private String ip;

	@Value("${service.provider.port}")
	private Integer port;

	@PostConstruct
	private void registerInstance() throws NacosException {
		System.out.println(namingMaintainService);

		Service service = new Service();
		service.setAppName(applicationName);
		service.setGroupName(Constants.DEFAULT_GROUP);
		try {
			namingMaintainService.createService(
					applicationName,
					Constants.DEFAULT_GROUP,
					0,
					"CONSUMER.label.site = PROVIDER.label.site"
			);
		} catch (NacosException e) {
			e.printStackTrace();
			return;
		}

		try {
			namingService.registerInstance(applicationName, ip, port);
		} catch (NacosException e) {
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		SpringApplication.run(CrossSiteServerApplication.class, args);
	}
}
```

**Expected behavior**
Service created successfully.

**Acutally behavior**
Fail to create the service.

**How to Reproduce**
1. Run the code.
2. See the error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: nacos-server 1.3.2
 - Module: naming
 - SDK: nacos-discovery-spring-boot-starter

**Additional context**
FYI, here's another way to see a related error on the console:
1. Click the “Create Service” button.
2. Type "Dragonborn" in "Service Name" box.
3. Type "0" in "Protect Threshold" box.
3. Choose “Label” in the drop-down box "Type".
4. Type "CONSUMER.label.site = PROVIDER.label.site" in the "Selector" box.
5. Click the "OK" button.
6. See the error "caused: parsed expression failed!;" 

I try to locate the error and find this:
https://github.com/alibaba/nacos/blob/7fd4d9a5d1206063460828de747afe132466bf58/naming/src/main/java/com/alibaba/nacos/naming/selector/LabelSelector.java#L170-L176
https://github.com/alibaba/nacos/blob/7fd4d9a5d1206063460828de747afe132466bf58/naming/src/main/java/com/alibaba/nacos/naming/selector/LabelSelector.java#L247-L267
第一段代码在172行调用了一次checkInnerSyntax方法，并且给形参start赋了0值。而在checkInnerSyntax方法中，第265行，这里用了一个index++来作为索引。结合前后代码，我推测这里或许是想表达“`确认下一个元素是否在SUPPORTED_INNER_CONNCETORS`”中这样一个逻辑，但却错误地使用了`index++`，导致了错误的出现。

**Comment by horizonzy** [comment]
I will trace it.

**Comment by horizonzy** [comment]
It's really a bug, I will fix it.
