### ISSUE TITLE
nacos start mysql db 不支持jasypt 加密

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#4437]
正常情况下，nacos docker 启动的时候会传递 db password，这是个明文密码，在环境上可以通过docker inspect 获取，不符合安全策略，源码上看好像获取db password不支持 jasypt加密？ please help

**Comment by KomachiSion** [comment]
开源版不支持这样的功能，如果需要满足您自己的安全策略需求，您需要自行修改然后build镜像使用。

**Comment by KomachiSion** [comment]
你不觉得这个需求提给数据库连接池更好？ 不管是什么数据库，连接池统一接入解密 不是更好，这样什么应用都不需要再考虑密码脱敏的问题了？
