### ISSUE TITLE
集群部署时，节点间的配置数据不同步

### ISSUE THREAD

**Issue by jia19831215** [alibaba/nacos#4440]
**Describe the bug**
多节点部署时，节点间的配置数据不同步，三个节点在后台管理里显示正常，一个leader，两个follower，开始是单个节点部署到，后来加俩个节点变成集群部署，直接调用openapi后两个节点一直获取不到部分配置，启动均显示集群模式。
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version nacos 1.3.1
 - Module [e.g. naming/config]
 - SDK spring-cloud-alibaba-nacos

**Additional context**

**Comment by KomachiSion** [comment]
Which module you used? config manager or service discovery?
And what's your database used? MySQL or Derby?

**Comment by goddman** [comment]
没配置数据库吧.节点信息存储在mysql里

**Comment by KomachiSion** [comment]
No enough useful information to produce problem and to judge whether nacos' problem. And author has no response for a long time. So close issue.
