### ISSUE TITLE
nacos配置权限 服务注册补上

### ISSUE THREAD

**Issue by xr2117** [alibaba/nacos#4442]
## Issue Description

nacos配置了权限
在服务端也添加了账号密码还是连接不上
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
      discovery:
        username: nacos
        password: nacos

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
Lark information, can't reproduce problem. Please provide more information like versions of nacos, and SCA. What's the error log you get.

**Comment by xr2117** [comment]
nacos版本1.3.0 客户端2.2.1 我在nacos application.properties 开启了auth 鉴权。开启之后java服务端连接nacos 不成功，已经填写过username password

**Comment by KomachiSion** [comment]
连接不成功的错误信息是什么，是连接拒绝？连接超时 还是403 forbidden？

**Comment by xr2117** [comment]
2020-12-10 00:47:05.867 ERROR 5100 --- [0a-2b3522e30515] c.a.n.client.config.impl.ClientWorker    : [fixed-39.97.234.200_8848-2a3fe044-d21c-426a-b70a-2b3522e30515] [check-update] get changed dataId error, code: 403
2020-12-10 00:47:05.867  INFO 5100 --- [0a-2b3522e30515] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[]

**Comment by xr2117** [comment]
频繁的在刷这个403，配置信息的cloud.nacos.discovery下的username password 和 cloud.nacos.config.username password有什么区别呢？

**Comment by KomachiSion** [comment]
> 频繁的在刷这个403，配置信息的cloud.nacos.discovery下的username password 和 cloud.nacos.config.username password有什么区别呢？

discovery是配置服务发现模块的用户名密码，config是配置中心的。
如果用的是同一个 可以考虑配在上一层

```
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
```

**Comment by KomachiSion** [comment]
频繁报错403就是说明用户名密码不对了。看一下是不是有什么空格之类的

**Comment by xr2117** [comment]
> 不断报错403就是说明用户名密码不对了。看一下是不是有什么空格之类的

能给个邮箱地址么 困惑我很久 想私下联系一下这个问题 解决不掉了

**Comment by KomachiSion** [comment]
请不要私下联系，问题公开处理，方便其他遇到相同问题的同学有个参考

**Comment by KomachiSion** [comment]
@xr2117 Any process?

**Comment by KomachiSion** [comment]
No more response from author. And we can't reproduce problem.

**Comment by qq31715879** [comment]
> > 频繁的在刷这个403，配置信息的cloud.nacos.discovery下的username password 和 cloud.nacos.config.username password有什么区别呢？
> 
> discovery是配置服务发现模块的用户名密码，config是配置中心的。
> 如果用的是同一个 可以考虑配在上一层
> 
> ```
> spring.cloud.nacos.username=nacos
> spring.cloud.nacos.password=nacos
> ```

试了都不行, 单独在nacos下加, 单独在discover下加或者两者都加都是:403 Whitelabel Error Page

**Comment by qq31715879** [comment]
> > 频繁的在刷这个403，配置信息的cloud.nacos.discovery下的username password 和 cloud.nacos.config.username password有什么区别呢？
> 
> discovery是配置服务发现模块的用户名密码，config是配置中心的。
> 如果用的是同一个 可以考虑配在上一层
> 
> ```
> spring.cloud.nacos.username=nacos
> spring.cloud.nacos.password=nacos
> ```

![image](https://user-images.githubusercontent.com/21219283/105966405-959c4a80-60bf-11eb-8137-09903814f7dd.png)

**Comment by 7788xiaotao** [comment]
用默认的namespace public 需要给用户赋予ROLE_ADMIN权限，如果不赋予ROLE_ADMIN权限就需要新建一个namespace，然后对其赋予可读写权限
