### ISSUE TITLE
a lots of threads named "com.alibaba.nacos.naming.push.receiver" in "TIMED_WAITING"  ()

### ISSUE THREAD

**Issue by wanpeng19** [alibaba/nacos#4448]
we use nacos with,
<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>
after  startup the server,a lots of threads named "com.alibaba.nacos.naming.push.receiver" in status of "TIMED_WAITING",please see the image:

![threads](https://user-images.githubusercontent.com/7500228/101773923-65f1ad00-3b28-11eb-857e-10a447167300.png)

here is the jstack output:
[jstack.txt](https://github.com/alibaba/nacos/files/5672778/jstack.txt)

**Comment by horizonzy** [comment]
There should be just one thread called `com.alibaba.nacos.naming.push.receiver` normally, did you create some NacosNamingService in your application?

**Comment by KomachiSion** [comment]
`com.alibaba.nacos.client.naming.updater` number should be `(cpuNumber / 2) + 2`

You can calculate it yourself. If the thread number is multiple times `(cpuNumber / 2) + 2`. There must be multiple `NacosNamingService` object, you need to upgrade SCA version. 

The other check way is dump the heap memory and analyze whether there are multiple `NacosNamingService` object. It will faster.

**Comment by wanpeng19** [comment]
> There should be just one thread called `com.alibaba.nacos.naming.push.receiver` normally, did you create some NacosNamingService in your application?

we didn't create NacosNamingService.

**Comment by wanpeng19** [comment]
we use  com.alibaba.cloud.nacos.NacosDiscoveryProperties#namingServiceInstance to create namingService. In SCA 2.2.0.RELEASE ,namingService not be reused. This problem has been fixed in Features  "Adding the destroy lifecycle callback for NamingService #1638" .  we upgrade SCA version,resolved problem.

Thank all!

**Comment by dancer-lxp** [comment]
您好，我遇到了com.alibaba.nacos.client.naming.updater 线程不释放的问题，您能秒数简单一些么，我刚接触nacos。

**Comment by wanpeng19** [comment]
> 您好，我遇到了com.alibaba.nacos.client.naming.updater 线程不释放的问题，您能秒数简单一些么，我刚接触nacos。

请问你的  spring cloud版本是多少

**Comment by dancer-lxp** [comment]
Hoxton.SR4   您也遇到类似的问题么？


| |
刘喜鹏
|
|
15076251291@163.com
|
签名由网易邮箱大师定制
On 12/14/2020 22:29，wanpeng19<notifications@github.com> wrote：

您好，我遇到了com.alibaba.nacos.client.naming.updater 线程不释放的问题，您能秒数简单一些么，我刚接触nacos。

请问你的 spring cloud版本是多少
