### ISSUE TITLE
Can nacos support the environment configuration comparison function similar to appolo?

### ISSUE THREAD

**Issue by lidaoyang** [alibaba/nacos#4452]
Can nacos support the environment configuration comparison function similar to appolo?

nacos 可以支持类似appolo的环境配置对比功能吗？
![image](https://user-images.githubusercontent.com/26211950/101854576-ca4e5400-3b9c-11eb-96e2-8247b0bc0aa4.png)

**Comment by jzhishu** [comment]
> Can nacos support the environment configuration comparison function similar to appolo?
> 
> nacos 可以支持类似appolo的环境配置对比功能吗？
> ![image](https://user-images.githubusercontent.com/26211950/101854576-ca4e5400-3b9c-11eb-96e2-8247b0bc0aa4.png)

Could you please add more pictures to describe the function？

**Comment by lidaoyang** [comment]
> > Can nacos support the environment configuration comparison function similar to appolo?
> > nacos 可以支持类似appolo的环境配置对比功能吗？
> > ![image](https://user-images.githubusercontent.com/26211950/101854576-ca4e5400-3b9c-11eb-96e2-8247b0bc0aa4.png)
> 
> Could you please add more pictures to describe the function？

apollo is a comparison configuration item. nacos cannot do this. You can compare the differences between the two namespaces.
apollo 那边的是比较配置项，nacos这边应该做不到，可以比较2个命名空间下的配置内容的差异。

apollo 演示地址：http://106.54.227.205/config/diff.html?#/appid=liasmy&env=DEV&clusterName=default&namespaceName=development.tom-public
![image](https://user-images.githubusercontent.com/26211950/102735280-f2983880-437c-11eb-80e5-9fba9f7d4377.png)
![image](https://user-images.githubusercontent.com/26211950/102735265-e8763a00-437c-11eb-8b01-1f56058fa6ab.png)

**Comment by BlackBAKA** [comment]
@i will solve it@

**Comment by BlackBAKA** [comment]
> > > Can nacos support the environment configuration comparison function similar to appolo?
> > > nacos 可以支持类似appolo的环境配置对比功能吗？
> > > ![image](https://user-images.githubusercontent.com/26211950/101854576-ca4e5400-3b9c-11eb-96e2-8247b0bc0aa4.png)
> > 
> > 
> > Could you please add more pictures to describe the function？
> 
> apollo is a comparison configuration item. nacos cannot do this. You can compare the differences between the two namespaces.
> apollo 那边的是比较配置项，nacos这边应该做不到，可以比较2个命名空间下的配置内容的差异。
> 
> apollo 演示地址：http://106.54.227.205/config/diff.html?#/appid=liasmy&env=DEV&clusterName=default&namespaceName=development.tom-public
> ![image](https://user-images.githubusercontent.com/26211950/102735280-f2983880-437c-11eb-80e5-9fba9f7d4377.png)
> ![image](https://user-images.githubusercontent.com/26211950/102735265-e8763a00-437c-11eb-8b01-1f56058fa6ab.png)

预计提供类似apollo中配置文件所有<key,value>在不同配置文件中赋值详情列表功能接口，对格式属于properties, yaml, json任一种的配置进行比对。
