### ISSUE TITLE
使用Nacos 1.3.0时，数据源配置问题

### ISSUE THREAD

**Issue by DavyLin** [alibaba/nacos#4459]
pigx框架里面的注册中心用到了Nacos 1.3.0，我直接在application.yml里面配置了
spring:
    datasource: 
           type:driver-class-name: com.**.jdbc.driver.*Driver
          url: jdbc:nds://IP:port/****
发现是不生效的，因为项目特殊原因，jdbc驱动需要使用自己的，请问这种情况下如何切换，我看nacos-config里面的“ExternalDataSourceServiceImpl.java”类是写死的driver-class，是否无法通过配置方式实现

**Comment by KomachiSion** [comment]
那你需要自己下载源代码自行修改打包。 驱动配置将来会伴随多数据源支持一起开放。目前是规定的mysql8和derby.
