### ISSUE TITLE
多线程同时更新一个服务的2个实例的enable状态时,会出现数据不一致

### ISSUE THREAD

**Issue by EZLippi** [alibaba/nacos#4460]
**Describe the bug**

问题主要是在ServiceManager.updateIpAddresses(Service service, String action, boolean ephemeral, Instance... ips) throws NacosException 这个方法的setValid的逻辑:
我的场景是这样的, 有个服务实例很多, 有200多个, 在CI后台批量发布时很可能出现多个服务实例同时调用nacos注册接口,由于采用了无损发布的机制, 在发布前会把服务的enabled状态改成false, 发布成功后改成true,
        //todo fix并发问题, service层数据的更新和Datum数据的更新不是原子的, 先更新datum再更新service
       //假设两个线程同时调用注册接口,更新前instance1.enabled=false, instance2.enabled=fasle
        //线程1更新instance1.enabled=true, 并更新datum里的enabled=true
        //线程2更新instance2.enabled=true,这时候会把oldInstanceMap里的instance1.enabled改回false,因为Service里的数据还未更新
        //线程1更新service数据, 此时service里的instance1.enabled=true
        //线程2更新datum和service, 此时service里的instance1.enabled=false

最后导致的现象就是instance1注册的状态是enabled=true,实际被instance2的注册请求覆盖层了false

![image](https://user-images.githubusercontent.com/5326814/101892725-b6c3dd00-3bde-11eb-9770-0a1ebcb7b0bb.png)

**Comment by EZLippi** [comment]
虽然发生的概率很低, 但还是出现了

**Comment by horizonzy** [comment]
I will trace it.

**Comment by horizonzy** [comment]
同一个jvm中按理说里面应该不会同时有两个线程进去的。外面对service加了一个锁，同时应该只有一个线程进去。可能是在集群下导致的该问题，明天再好好看一下

**Comment by horizonzy** [comment]
@EZLippi Yes, it's really a bug. Which version do you use? The bug is fixed already.
Now just copy healthy and lastBeat from service's instances.
```
    private Map<String, Instance> setValid(List<Instance> oldInstances, Map<String, Instance> map) {
        
        Map<String, Instance> instanceMap = new HashMap<>(oldInstances.size());
        for (Instance instance : oldInstances) {
            Instance instance1 = map.get(instance.toIpAddr());
            if (instance1 != null) {
                instance.setHealthy(instance1.isHealthy());
                instance.setLastBeat(instance1.getLastBeat());
            }
            instanceMap.put(instance.getDatumKey(), instance);
        }
        return instanceMap;
    }
```

**Comment by KomachiSion** [comment]
Maybe refer to #3466.

**Comment by EZLippi** [comment]
ok, i see.
