### ISSUE TITLE
 When multi-language SDK is connected to Nacos 2.0, it is recommended to adjust the Type value in Metadata

### ISSUE THREAD

**Issue by catcherwong** [alibaba/nacos#4464]
When using grpc to request the nacos server, I encountered a situation where it kept returning **RequestHandler Not Found**

```
{"resultCode":500,"errorCode":500,"message":"RequestHandler Not Found","success":false}
```

The screenshot below is an example of request parameters and responses

![image](https://user-images.githubusercontent.com/8394988/101980395-f1da1500-3c9f-11eb-8797-19a48abe0620.png)

After reading the source code of nacos, I found that the full class name needs to be passed in order to successfully request.

![image](https://user-images.githubusercontent.com/8394988/101980422-2221b380-3ca0-11eb-9793-87c04f1a03a1.png)

This will be strange when connecting to multiple languages.

It might be better to replace the full class name with a meaningful alias

**Comment by chuntaojun** [comment]
Maybe we should replace the current implementation of strong Java semantics with something that makes sense, something like restful, etc

**Comment by liangyuanpeng** [comment]
> Maybe we should replace the current implementation of strong Java semantics with something that makes sense, something like restful, etc

Absolutely we need.

**Comment by catcherwong** [comment]
The following commit has solved this problem.

https://github.com/alibaba/nacos/commit/3cfa183400b02d6c3c2a4b1f180f3440343a7b5a

Using simple class name to replace full class name.
