### ISSUE TITLE
push empty protection needed

### ISSUE THREAD

**Issue by Xezeloh** [alibaba/nacos#4470]
**Is your feature request related to a problem? Please describe.**
Although the service consumer has a cache for the provider and can access to the provider normally even after Nacos shut down. However, once Nacos restarts the cache would be wiped out and cannot access to the provider for a short time.

**Describe the solution you'd like**
When pulling or receiving instances list, ignore it if it's empty.

**Describe alternatives you've considered**
No

**Additional context**
I see statements in the code trying to solve this problem, but the problem still exists. I'm not sure whether push empty protection is officially supported by the Java SDK, so I raise this issue as a functional requirement.
我在代码里看到了试图解决这个问题的语句，但这个问题还是存在。我不确定推空保护是否是java sdk正式支持的功能，所以把这个问题作为一个功能需求提出来。

**Comment by KomachiSion** [comment]
duplicate with #3880
