### ISSUE TITLE
同一项目下 多个微服务共用某一些业务配置属性，nacos可解么？

### ISSUE THREAD

**Issue by weihai4099** [alibaba/nacos#4471]
**Is your feature request related to a problem? Please describe.**

比如，都配置同样的日志配置，业务属性id，数据库地址配置等等。有现有的解决方案么？ 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
在同一个namespace下面，然后所有微服务都订阅同一个dataId就可以了

**Comment by weihai4099** [comment]
但是，每个微服务还有自己单独的配置啊 。

**Comment by KomachiSion** [comment]
nacos-client支持订阅多dataID， 如果用SCA，就去SCA社区问一下怎么配置多个dataID。SCA有可能封装过只能订阅1个dataId， 那需要提需求给SCA。

**Comment by weihai4099** [comment]
收到，感谢
