### ISSUE TITLE
403 happened when access "public" namespace by spring-cloud-starter-alibaba-nacos-discovery

### ISSUE THREAD

**Issue by xuchaoguo1983** [alibaba/nacos#4474]
**Describe the bug**

My apps has integrated **spring-cloud-starter-alibaba-nacos-discovery** with version 2.0.3.RELEASE.

I opened the auth module of nacos server(1.4.0) and created an account with right permissions to access the default public namespace.

Then I launched the apps and suppose it should work as expected but report 403 error many times.

**Expected behavior**

Launched with no error, and the app should be registered to nacos correctly.

**Acutally behavior**

Launch failed with http 403 error.

**How to Reproduce**

1. integrate your maven app (spring boot version 2.0.x) with dependency as below:

<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.0.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.0.3.RELEASE</version>
        </dependency>

2. config the bootstrap.yml as below:

spring:
  application.name: demo
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: xxxxxxx
      config:
        server-addr: nacos.xxx.com:8848
        group: ${spring.profiles.active}
        file-extension: yml
      discovery:
        server-addr: nacos.xxx.com:8848
        group: ${spring.profiles.active}
        metadata:
          version: 1.0.0

3. launch the app;

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Version nacos-server 1.4.0

**Additional context**

I debugged the nacos client code and found that when you access the nacos server, you attached a 'namespaceId' parameter with value 'public', that is the problem.

I tried with open api as well, and got the same problem.

curl -X GET 'nacos.xxxx.com:8848/nacos/v1/ns/instance/list?serviceName=dev@@demo&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjA3OTQ2MTYxfQ.5Z9gSSO1cFweZXcR-pUZua_FWvUmwe5-UJbWXCA7S6U&namespaceId=public'

after removed the **namespaceId** parameter, it works well. I bet the server has wrong check with namespaceId as 'public'.

**Comment by KomachiSion** [comment]
我测试没有问题，建议贴出完整的报错信息以及配置信息。

```
~/localtest/nacos14 » curl -X GET 'localhost:8848/nacos/v1/ns/instance/list?serviceName=dev@@demo&namespaceId=public'       xiweng.yy@B-LL8GMD6M-1650
{"timestamp":"2020-12-14T11:23:34.486+0000","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/ns/instance/list"}%

~/localtest/nacos14 » curl -X GET 'localhost:8848/nacos/v1/ns/instance/list?serviceName=dev@@demo&namespaceId=public&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYwNzk2MzA1NX0.XaybSM-75NaZ2-MfnC2L4y-ShkokMQbmOJZEF0uerO0'
{"name":"dev@@demo","clusters":"","cacheMillis":3000,"hosts":[]}%
```

配置：
```
### If turn on auth system:
nacos.core.auth.enabled=true
```

**Comment by KomachiSion** [comment]
Any process?

**Comment by KomachiSion** [comment]
No more response from author. And can't reproduce problem. Close issue
