### ISSUE TITLE
com.alibaba.nacos.client.naming.updater 线程不释放

### ISSUE THREAD

**Issue by dancer-lxp** [alibaba/nacos#4475]
我们程序现在又两万多线程 99%恶的都是 com.alibaba.nacos.client.naming.updater 线程，而且不释放，是sleeping状态，导致没有办法创建正常的线程，有遇到过类似问题的大佬么？求解答

**Comment by dancer-lxp** [comment]
使用的线程池是 scheduledthreadpoolexecutor

**Comment by KomachiSion** [comment]
建议dump一下内存 看一下有多少个`NacosNamingService`对象，推测有几百上千个吧

**Comment by KomachiSion** [comment]
Maybe refer to #4491

**Comment by GLliangcheng** [comment]
> 

你好,请问下是怎么解决的?
