### ISSUE TITLE
nacos 1.4.0 dashboard config list can't Fuzzy query

### ISSUE THREAD

**Issue by freshgeek** [alibaba/nacos#4476]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20513615/102055733-43141100-3e26-11eb-97db-78941b24d289.png)

![image](https://user-images.githubusercontent.com/20513615/102055753-4c04e280-3e26-11eb-95bd-34a1e39222d1.png)

**Expected behavior**

Fuzzy query  by Data ID  , Group 

**Acutally behavior**

the list is empty 

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by freshgeek** [comment]
We hope to fix it in this release instead of providing an iterative version

**Comment by KomachiSion** [comment]
Add * to open fuzzy query.

**Comment by freshgeek** [comment]
是否可以加入到 placeholder 中

> 添加*以打开模糊查询。
> 
> `SENTINAL_*`

**Comment by KomachiSion** [comment]
> 是否可以加入到 placeholder 中
> 
> > 添加*以打开模糊查询。
> > `SENTINAL_*`

欢迎贡献。这个很简单。

**Comment by freshgeek** [comment]
OK

> > 是否可以加入到 placeholder 中
> > > 添加*以打开模糊查询。
> > > `SENTINAL_*`
> 
> 欢迎贡献。这个很简单。
