### ISSUE TITLE
nacos自定义部分配置无法实时更新问题

### ISSUE THREAD

**Issue by song4567-sun** [alibaba/nacos#4478]
pom增加如下依赖：

     <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>

后会导致部分自定义参数无法实时更新，如：zhang.mock3类型，但是如zhang.mockUrl可实时更新，求解答。若去掉jasypt依赖无此问题。

environment: nacos-server 1.4 springboot:2.0.8

**Comment by KomachiSion** [comment]
没有看懂问题，麻烦用issue模版详细描述。

**Comment by song4567-sun** [comment]
> 没有看懂问题，麻烦用issue模版详细描述。

降低加密版本后已解决。
