### ISSUE TITLE
NACOS_SERVERS必须手动配置么

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4479]
部署NACOS_SERVERS时，必须手动配置NACOS_SERVERS么。
nacos没有做到自动识别么

**Comment by KomachiSion** [comment]
麻烦用issue模版详细描述问题，你这个描述我完全看不懂。

**Comment by wanghuigithub** [comment]
> 麻烦用issue模版详细描述问题，你这个描述我完全看不懂。

使用k8s方式部署nacos时，根据官网文档和示例应用。需要手动配置配置项NACOS_SERVERS的值。
想问下是否可以不手动配置。

**Comment by KomachiSion** [comment]
服务端之间需要做数据同步和状态同步，不配置怎么知道哪几台pod是同伴集群？

**Comment by wanghuigithub** [comment]
> 服务端之间需要做数据同步和状态同步，不配置怎么知道哪几台pod是同伴集群？

在节点数量较多时，比如万级，十万级节点时，这样配置是不是比较困难。
想问下阿里内部在上云时，使用了什么方法解决这么问题。

**Comment by KomachiSion** [comment]
你们有那么大的nacos集群吗？ 一般情况下数个，最多十数个节点就足够了吧。

阿里内部有一个叫地址服务器的东西进行管理， nacos启动的时候，去请求地址服务器RESTFul，就可以获取到所有的集群列表。 从地址服务器获取集群列表的能力开源nacos也是有的，但是地址服务器这个东西需要自己实现。

**Comment by LoseyourseIf** [comment]
> 部署NACOS_SERVERS时，必须手动配置NACOS_SERVERS么。
> nacos没有做到自动识别么

我猜这位同学是用 https://hub.docker.com/r/nacos/nacos-server 在 K8S 上搭建 Nacos 集群
如果自己不好确定 env NACOS_SERVERS 要怎么配就先填个ip1:8848启动一个pod起来看
用kubectl 进入到 pod 里面

`cat /home/nacos/conf/cluster.conf`
比如我的是这样

```
[root@nacos-server-headless-qi0717-0 conf]# cat cluster.conf 
#2020-12-16T17:27:28.549
ip1:8848
ip2:8848
ip3:8848
nacos-server-headless-qi0717-0.nacos-server-headless.micro-service.svc.cluster.local:8848

```
启动的时候和 env 不一致的会在 cluster.conf 下面多一行 按照多出来的配就OK了

**Comment by wanghuigithub** [comment]
> 你们有那么大的nacos集群吗？ 一般情况下数个，最多十数个节点就足够了吧。
> 
> 阿里内部有一个叫地址服务器的东西进行管理， nacos启动的时候，去请求地址服务器RESTFul，就可以获取到所有的集群列表。 从地址服务器获取集群列表的能力开源nacos也是有的，但是地址服务器这个东西需要自己实现。

好的，谢谢，我们目前没有这么多节点。只是好奇这个问题的更可规模化的解决方案
