### ISSUE TITLE
[NamingClient] EventDispatcher addListener使用相同服务名可以添加多个相同listener在observerMap中

### ISSUE THREAD

**Issue by lpaz010** [alibaba/nacos#4483]
**Describe the bug**
invoke `nacosNamingService.subscribe(serviceName, listener)`  three times while doing unit test with same serviceName and listener, and get `NamingEvent`  three times.
在单元测试nacosNamingService中，使用相同的serviceName和listener订阅三次，会触发三次NamingEvent事件。

**Expected behavior**
same serviveName and listener should triggle one time ,  ignore many times subscribe.
相同的监听器listener应该只触发一次NamingEvent事件。

**Acutally behavior**
`NamingEvent` triggle three times.

Question:  
is that normal ?  
这个现象是正常的吗？

**Comment by KomachiSion** [comment]
正常，设计上所有观察者模式都不会说只允许一个观察者监听一个事件。只要有观察者监听同一个事件，当这个事件有的时候必然是所有观察者都触发。

简单的设计模式问题。

**Comment by lpaz010** [comment]
> 正常，设计上所有观察者模式都不会说只允许一个观察者监听一个事件。只要有观察者监听同一个事件，当这个事件有的时候必然是所有观察者都触发。
> 
> 简单的设计模式问题。

@KomachiSion thank you, 谢谢!
所有观察者其实都是同一个实例时，也会被触发多次。即同一个观察者订阅多次，在List添加多次，触发时调用多次。觉得应该触发一次就够，本来就一个观察者。

**Comment by KomachiSion** [comment]
没有做这个区分，如果是同一个观察者，为什么要添加多次？ 既然你添加了多次，那只能认为你需要触发多次了。

**Comment by lpaz010** [comment]
> 没有做这个区分，如果是同一个观察者，为什么要添加多次？ 既然你添加了多次，那只能认为你需要触发多次了。

GET IT, THX!
明白了，感谢！
