### ISSUE TITLE
进入nacos管理页面，全空白 什么也看不到

### ISSUE THREAD

**Issue by wrysunny1953** [alibaba/nacos#4484]
![nacos_error](https://user-images.githubusercontent.com/54027919/102156543-bd8d7100-3eb8-11eb-8b48-68f15f672304.png)

**Comment by wrysunny1953** [comment]
![nacos_error](https://user-images.githubusercontent.com/54027919/102156585-c9793300-3eb8-11eb-9dea-6de7f01067b0.png)

**Comment by ljhrot** [comment]
请使用支持 HTML5 特性的浏览器进行访问

360 浏览器有两种模式，你可能使用的是兼容模式，请切换成极速模式（地址输入框右边的 IE icon）尝试访问

**Comment by sanxun0325** [comment]
@wrysunny1953 可以关注一下console 里面有没有错误信息，或者尝试换一个浏览器试试。

**Comment by wrysunny1953** [comment]
SCRIPT438: 对象不支持“assign”属性或方法
main.js (14,120301)

**Comment by wrysunny1953** [comment]
哎呦喂，极速模式可以啦，谢谢您啦

**Comment by beyond-Jack** [comment]
net::ERR_CONTENT_LENGTH_MISMATCH，看 f12 控制台，有些请求提示这个
