### ISSUE TITLE
nacos 1.4.0 角色权限无效

### ISSUE THREAD

**Issue by malversation** [alibaba/nacos#4485]
**Describe the bug**
角色权限无效

**Expected behavior**
新建用户，角色并赋权后，使用新用户登陆控制台权限无效。

**Comment by KomachiSion** [comment]
服务端开启鉴权功能了？ 无效的现象是什么？

**Comment by malversation** [comment]
@KomachiSion 
可以了，服务器没有开启鉴权功能。

**Comment by jerrychern** [comment]
nacos.core.auth.enabled=true
这样设置之后 ，客户端连接nacos都要增加用户名和密码？怎么做到不改动客户端连接方式的前提下做到控制台设置只读用户。
