### ISSUE TITLE
Nacos Server1.3.1 Can not close console

### ISSUE THREAD

**Issue by AutoTon** [alibaba/nacos#4487]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

can not close console

### How to reproduce it (as minimally and precisely as possible)

my configuration is as below:

spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=

#nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

nacos.core.auth.enabled=true

### Tell us your environment
nacos server 1.3.1

**Comment by KomachiSion** [comment]
What's the meaning of `can not close console` . Did you mean the nacos server can't stop when you call `shutdown.sh`?

**Comment by AutoTon** [comment]
can not close access of the console front pages

**Comment by AutoTon** [comment]
> What's the meaning of `can not close console` . Did you mean the nacos server can't stop when you call `shutdown.sh`?

can not close access of the console front pages

**Comment by KomachiSion** [comment]
Why want to close console page? Do you want to build console by yourself?

**Comment by AutoTon** [comment]
> Why want to close console page? Do you want to build console by yourself?

Yes.  Login by my cas.

**Comment by KomachiSion** [comment]
After 2.1, nacos support auth plugin, you can add your own auth plugin. But the console maybe should re-compile by yourself.
