### ISSUE TITLE
nacoa 在Linux打开过多文件句柄数

### ISSUE THREAD

**Issue by 15010904599** [alibaba/nacos#4490]
![image](https://user-images.githubusercontent.com/76037243/102189813-2e04b400-3ef2-11eb-90b9-139387a7d973.png)

一个nacos打开十几万的文件句柄数

**Comment by KomachiSion** [comment]
能看一下这个句柄对应的内容是什么吗？ 是不是连接？

**Comment by 15010904599** [comment]
![image](https://user-images.githubusercontent.com/76037243/102298938-0dd60300-3f8d-11eb-8973-99eedd8ebb5f.png)
![image](https://user-images.githubusercontent.com/76037243/102298958-13334d80-3f8d-11eb-9678-abed4d47da44.png)
这看着应该不是连接吧。 只是单纯启动了nacos就打开了这么多

**Comment by KomachiSion** [comment]
你使用的是derby数据库？ 那要看下是不是derby的使用方式有误。

**Comment by 15010904599** [comment]
好的

**Comment by chuntaojun** [comment]
derby文件夹的大小已经多少了

**Comment by 15010904599** [comment]
3M

**Comment by 15010904599** [comment]
![image](https://user-images.githubusercontent.com/76037243/102456403-0d686580-407c-11eb-9da4-b983315a3708.png)
 我换了mysql数据库，但是打开文件句柄数还是特别多，十九万多，我看好多都是naming_persistent_service这个下面的日志，单独启动一个nacos服务  naming_persistent_service 这个下面的日志都150多M了，这个是哪儿没配置对吗

**Comment by 15010904599** [comment]
[16861.txt](https://github.com/alibaba/nacos/files/5707738/16861.txt)
这是打开文件句柄的详细情况，请帮忙看一下

**Comment by chuntaojun** [comment]
> [16861.txt](https://github.com/alibaba/nacos/files/5707738/16861.txt)
> 这是打开文件句柄的详细情况，请帮忙看一下

你把你的nacos-server的日志发给我一下

**Comment by 15010904599** [comment]
[log.zip](https://github.com/alibaba/nacos/files/5713127/log.zip)

**Comment by 15010904599** [comment]
请问有解决办法吗

**Comment by 15010904599** [comment]
请问一般正常情况下nacos会打开多少文件句柄呢

**Comment by audiebantzhan** [comment]
Every boot:
2021-04-06 13:04:57,828 INFO Nacos is starting...
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable

**Comment by macey888** [comment]
麻烦问一下，大佬们，这个有解决方案了吗？我们也遇到了同样的问题。

**Comment by huhu-sky** [comment]
这个问题就这样不管了么？？？？
@KomachiSion @chuntaojun

**Comment by ZouJunJieNB** [comment]
遇到了同样的问题，其实是nacos默认根据你服务器的核数 * 16（默认）打开了很多线程，在nacos的application.properties 添加参数在服务启动时添加JVM启动参数设置remote.executor.times.of.processors=4 即可控制默认线程池核数，单独修改了这个参数，线程池的大小就是4 * 16，也可以在nacos启动时添加JVM参数:remote.executor.times.of.processors来控制，这样nacos的线程池的大小就是 (remote.executor.times.of.processors * remote.executor.times.of.processors)
