### ISSUE TITLE
压测Nacos集群出现异常 - Spill-over slots in symbol table with 1943 entries, hash area of 4096 slots is now full

### ISSUE THREAD

**Issue by bbcpan** [alibaba/nacos#4493]
部署架构：Nacos Server用集群方式部署，域名->单节点Ngnix->3节点Nacos
压测频率: 服务实例数6000，心跳续约频率 6W请求/分钟

当压测任务已经跑起来并且稳定在6w/分钟的情况下，
[nacos_error.log](https://github.com/alibaba/nacos/files/5695045/nacos_error.log)
启动Nacos集群，nacos.log会出现以下异常:
`java.lang.IllegalStateException: Spill-over slots in symbol table with 1943 entries, hash area of 4096 slots is now full (all 512 slots -- suspect a DoS attack based on hash collisions. You can disable the check via JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW`

naming-server.log会出现以下异常:
`java.io.IOException: failed to req API:http://10.17.162.25:8848/nacos/v1/ns/distro/datum. code:500 msg: caused: Spill-over slots in symbol table with 1907 entries, hash area of 4096 slots is now full (all 512 slots -- suspect a DoS attack based on hash collisions. You can disable the check via `JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW`;
        at com.alibaba.nacos.naming.misc.NamingProxy.syncData(NamingProxy.java:166)
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.DataSyncer.lambda$submit$0(DataSyncer.java:132)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)`

最终的影响是，导致Nacos Console小量的服务实例一直不能注册成功；

[nacos_error.log](https://github.com/alibaba/nacos/files/5695055/nacos_error.log)

**Comment by KomachiSion** [comment]
心跳请求6W？ 实例数6000？ 你一秒发10个心跳？

**Comment by KomachiSion** [comment]
你这请求数太高了，被识别成ddos拦截了。

**Comment by bbcpan** [comment]
> 你这请求数太高了，被识别成ddos拦截了。

但折算下来，才1000/秒，不算高吧？有什么办法可以在nacos上屏蔽这个checking吗？提示是：You can disable the check via JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW，但不知道怎么弄

**Comment by bbcpan** [comment]
如果我先把nacos集群启动并稳定跑起来后，再启动压测程序慢慢加大压力，就不会出现这种情况

**Comment by bbcpan** [comment]
现在我们压测，是采用jmeter发送不同的http请求到nacos server的beat心跳续约接口，模拟6000个实例的方式做的；
问题：
1）你们1w2实例压测场景，也是采用类似的方式吗？
2）你之前的描述中，涉及瞬间请求值概念，请教一下你们压测1w2的场景下，有试过压测机稳定后，重启nacos server吗？

**Comment by KomachiSion** [comment]
> 现在我们压测，是采用jmeter发送不同的http请求到nacos server的beat心跳续约接口，模拟6000个实例的方式做的；
> 问题：
> 1）你们1w2实例压测场景，也是采用类似的方式吗？
> 2）你之前的描述中，涉及瞬间请求值概念，请教一下你们压测1w2的场景下，有试过压测机稳定后，重启nacos server吗？

1. 不是 是n台施压机，每台注册几百个实例。
2. 没有
