### ISSUE TITLE
使用environment variables 配置nacos.config，依赖中使用了openfeign，热更新无效

### ISSUE THREAD

**Issue by zhaojingadmin** [alibaba/nacos#4494]
![image](https://user-`images`.githubusercontent.com/6168268/102205155-be98bf80-3f05-11eb-890a-712327ab4dc5.png)

![image](https://user-images.githubusercontent.com/6168268/102205199-cfe1cc00-3f05-11eb-9350-153f65d2203c.png)

![image](https://user-images.githubusercontent.com/6168268/102205511-3f57bb80-3f06-11eb-9768-3dfb839cb75d.png)

![image](https://user-images.githubusercontent.com/6168268/102205561-526a8b80-3f06-11eb-8afb-7b9a3a62569e.png)

**Comment by ljhrot** [comment]
请提供必要的环境信息，比如 nacos 版本以及操作系统
请提供可复现问题的步骤

**Comment by KomachiSion** [comment]
截图的内容是在哪， nacos的日志应该打印了详细错误信息和堆栈，把那个提供出来可能会更有帮助

**Comment by KomachiSion** [comment]
Please move issue to SCA community if necessary. I think it's conflict with SCA and feign.
