### ISSUE TITLE
服务订阅者接到callback时，有的服务名为空，有的不为空

### ISSUE THREAD

**Issue by wangdafang** [alibaba/nacos#4496]
##订阅者启动后，服务订阅者接到callback时，有的服务名为空，有的不为空

Type: *bug report* 

### Describe what happened (or what feature you want)
我使用NamingService.subscribe(servicename,event->{callback})方式订阅nacos上全量服务
当我服务启动时，获取到的nacos服务列表有的返回空数组(为空的数组在nacos上看是有服务列表的)，有的返回实际列表
我的服务是根据nacos的服务列表做上下线的，这导致我将返回了空数组的服务全部下线，造成了严重的系统故障，麻烦官方给解答一下原因。
备注：全部使用方式均是按照官方文档来做的，服务注册，订阅都没问题
为什么只有这个callback会有些返回空有些返回实际列表

### Tell us your environment
nacos-1.4

**Comment by horizonzy** [comment]
确认namespace,serviceName,groupName都对应上了吗。

**Comment by wangdafang** [comment]
> 确认namespace,serviceName,groupName都对应上了吗。

确认都是对应的，而且这个返回的不一定每次都是空，同一个服务也有不为空的时候，看起来像nacos订阅推送的一个bug

**Comment by KomachiSion** [comment]
是服务名为空 还是服务列表为空？
1. 先确认服务是不是一直在不停的上下线抖动
2. 控制台查询看下服务是否是一致的，没一台server端都查一下
3. 看一下${user.home}/logs/nacos/naming.log, 过滤一下会返回空的服务名，看一下是不是有什么信息。

**Comment by wangdafang** [comment]
> 是服务名为空 还是服务列表为空？
> 
> 1. 先确认服务是不是一直在不停的上下线抖动
> 2. 控制台查询看下服务是否是一致的，没一台server端都查一下
> 3. 看一下${user.home}/logs/nacos/naming.log, 过滤一下会返回空的服务名，看一下是不是有什么信息。

感谢您的回复，我定位到问题了
1.并不是服务返回的列表为空，经过反复验证是因为我开发环境使用的client与nacos服务端不一致导致的开发环境返回服务列表为空
2.导致我这次问题的原因是3个
--a.因为我修改服务下线状态时，不存在的服务名被nacos'创建出来了一个为空的服务名
--b.我程序启动时，订阅到了上面创建的空服务名
--c.这个空服务名订阅后，回调函数被调用，返回的空数组
这三个原因导致了我这次的故障
