### ISSUE TITLE
Unauthorized access leads to account and password disclosure

### ISSUE THREAD

**Issue by pykiller** [alibaba/nacos#4498]
Accessing 
/nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=
 will directly display the configuration information in nacos. And the address, account number and password in the configuration information will be displayed directly.

**Comment by wangweizZZ** [comment]
Please use the issue template to describe the problem in detail.

**Comment by KomachiSion** [comment]
Please open authorization feature in nacos server and retry. default close authorization.

**Comment by KomachiSion** [comment]
duplicate with #4500
