### ISSUE TITLE
Nacos console,  the read role have the write permission for configuration

### ISSUE THREAD

**Issue by liuxianqiang** [alibaba/nacos#4500]
**Describe the bug**
Nacos console,  the read role have the write permission for configuration
1. add a user "lxq"
2. add a role "ROLE_READ" for "lxq"
3. add "r" permission for "ROLE_READ"

**Expected behavior**
the user "lxq" can not edit the "public" configration

**Acutally behavior**
the user "lxq" can edit the "public" configration

**How to Reproduce**
see above

**Desktop (please complete the following information):**
 - OS: Mac mojave 10.14.6
 - Version: nacos-server-1.4.0
 - Module: console config
 - SDK: none

**Additional context**
same suggestion.
1. I doubt, is there any company use nacos as a ConfigServer in production.   just focus on the service registry!!!
2. the user, role, permission feature confuse me !!!

**Comment by KomachiSion** [comment]
Please open authorization feature in nacos server and retry. default close authorization.

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/auth.html

**Comment by liuxianqiang** [comment]
ok, it's work

### If turn on auth system:
nacos.core.auth.enabled=true
