### ISSUE TITLE
Unauthorized access vulnerability（DANGER）

### ISSUE THREAD

**Issue by mandarenmanman** [alibaba/nacos#4501]
Type: bug report

Describe what happened (or what feature you want)

https://nacosserver/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=

As long as it is a configuration file under the default namespace public, this interface can be obtained and exists in all versions

![image](https://user-images.githubusercontent.com/11764268/102320285-0b889e80-3fb7-11eb-85b6-c950ad16d828.png)

Tell us your environment
all

Anything else we need to know?

**Comment by KomachiSion** [comment]
#4500
