### ISSUE TITLE
k8s集群部署nacos1.4.0，leader节点raft选举成员中缺少一个节点信息，缺少的那个一直在FOLLOWER和CANDIDATE中切换

### ISSUE THREAD

**Issue by pojo** [alibaba/nacos#4503]
三台nacos节点：
  nacos-0.nacos-headless.micro-server.svc.cluster.local:8848
  nacos-1.nacos-headless.micro-server.svc.cluster.local:8848
  nacos-2.nacos-headless.micro-server.svc.cluster.local:8848

nacos-0的元数据信息
![image](https://user-images.githubusercontent.com/18011435/102333633-a63da900-3fc8-11eb-91d0-099e83131d6f.png)

nacos-1的元数据信息
![image](https://user-images.githubusercontent.com/18011435/102333695-bb1a3c80-3fc8-11eb-9811-bd1f8cdd7693.png)

nacos-02的元数据信息
![image](https://user-images.githubusercontent.com/18011435/102333749-cec5a300-3fc8-11eb-81cf-f17b13e51cf1.png)

从以上三个元数据信息看出，nacos-0的raftGroupMember属性中没有nacos-02的信息，而nacos-2的raftGroupMember中nacos-0的信息，导致nacos-2一直在FOLLOWER和CANDIDATE之间切换，请官方指导一下，谢谢~

**Comment by KomachiSion** [comment]
1.4.0版本后，我们用Jraft替换了自研的raft， `naming`这个数据已经废弃了。

当整个集群升级到1.4.0之后， 旧raft系统关闭，转移到新的raft系统，所以应该以`raftMetadata`的数据为准。

1.4.1版本我们会移除 `naming`，以免造成困昏。

**Comment by pojo** [comment]
好的，谢谢
