### ISSUE TITLE
Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed.

### ISSUE THREAD

**Issue by JemGeek** [alibaba/nacos#4508]
**Which Component**
spring cloud alibaba 2.2.3.RELEASE 
Nacos 1.4.0

**Special instructions**
This problem occurs in version 2.2.3.RELEASE. Version 2.2.2.RELEASE is normal.

**Describe the bug**
**Nacos login failed** with the following error message：

ERROR 17104 --- [ecurity.updater] c.a.nacos.client.security.SecurityProxy  : [SecurityProxy] login http request failed url: http://127.0.0.1:8848/nacos/v1/auth/users/login, params: {username=dev}, bodyMap: {password=James2020%2B}, errorMsg: errCode: 100, errMsg: Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed.  

**To Reproduce**
Component version：
spring cloud alibaba : 2.2.3.RELEASE
spring cloud : Hoxton.SR9
spring boot: 2.3.7.RELEASE

1. Set the password of Nacos account to [James2020+]
2. Start micro service project.
3. See error, nacos login failed. Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed. 

if set the password of Nacos account to [James2020],  There are no errors without special characters.

**Expected behavior**
Nacos login success.

**Screenshots**
![nacos-error.png](https://i.loli.net/2020/12/17/2ASuNMD63sXhepC.png)

**Additional context**
Windows  、Java8

**Comment by wangweizZZ** [comment]
This bug has been fixed in 1.4.0 , see  #3695
You can try to upgrade your nacos-client version。

**Comment by JemGeek** [comment]
> This bug has been fixed in 1.4.0 , see #3695
> You can try to upgrade your nacos-client version。

get it,thank u.

**Comment by xshans** [comment]
There are still the same problems in 1.4.1
