### ISSUE TITLE
关于nacos-1.4.0 版本 优雅停机的疑问

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#4511]
## Issue Description

@KomachiSion  注意到您在issue [#3792]中曾经提到

> 1.3.1开始支持。
> 看NamingService.shutDown 和 ConfigService.shutDown

经过我自己的测试，发现问题

### Describe what happened (or what feature you want)
问题一：
在 IDE 里面用Debug模式运行 nacos，然后点击停止按钮
![image](https://user-images.githubusercontent.com/53824889/102495943-b67d8300-40b1-11eb-99ac-6b90b57bedc9.png)
如图中代码所示，我后期加的控制台打印语句并没有输出
![image](https://user-images.githubusercontent.com/53824889/102497521-b1b9ce80-40b3-11eb-8b34-314fc268c5b6.png)

是否能证明NacosNamingService.shutDown()方法并没有执行？

问题二：
接问题一，将 nacos 部署到 linux服务器上运行，然后执行{nacos_home}/bin目录下提供的shutdown.sh脚本， 
接下来再进入到{nacos_home}/logs 目录下 tail -f *，
发现NacosNamingService.shutDown()方法里面对应的
        beatReactor.shutdown();
        eventDispatcher.shutdown();
        hostReactor.shutdown();
        serverProxy.shutdown();
里面的日志内容都没有输出
![image](https://user-images.githubusercontent.com/53824889/102497027-1cb6d580-40b3-11eb-8379-91875c89be76.png)

### Describe what you expected to happen
所以请问：
1.NacosNamingService.shutDown()方法和NacosConfigService.shutDown()方法究竟有没有执行？
2.如果执行了，应该去哪里看到它们的输出日志？
3.执行{nacos_home}/binmu目录下的shutdown.sh脚本就可以保证停机过程是优雅的吗？

非常感谢您的阅读跟回答

**Comment by wangweizZZ** [comment]
hi. `NamingService.shutDown` 和 `ConfigService.shutDown` 都是客户端的部分，而你所说的1、2 你都是停了服务器端，这两者没啥关系。

**Comment by MajorHe1** [comment]
> hi. `NamingService.shutDown` 和 `ConfigService.shutDown` 都是客户端的部分，而你所说的1、2 你都是停了服务器端，这两者没啥关系。

请问服务器端NacosNamingService.shutDown()方法和NacosConfigService.shutDown()方法在停机的时候会执行吗，如果会的话为什么我看不到执行的日志输出？

**Comment by wangweizZZ** [comment]
> > hi. `NamingService.shutDown` 和 `ConfigService.shutDown` 都是客户端的部分，而你所说的1、2 你都是停了服务器端，这两者没啥关系。
> 
> 请问服务器端NacosNamingService.shutDown()方法和NacosConfigService.shutDown()方法在停机的时候会执行吗，如果会的话为什么我看不到执行的日志输出？

我理解你所说的停机指的是停 nacos-server。不会执行，因为你所说的这两者都是 nacos-client 模块下的，不属于nacos-server。这个shudown 是给接入nacos-client的应用调的 :-)

**Comment by MajorHe1** [comment]
> > > hi. `NamingService.shutDown` 和 `ConfigService.shutDown` 都是客户端的部分，而你所说的1、2 你都是停了服务器端，这两者没啥关系。
> > 
> > 
> > 请问服务器端NacosNamingService.shutDown()方法和NacosConfigService.shutDown()方法在停机的时候会执行吗，如果会的话为什么我看不到执行的日志输出？
> 
> 我理解你所说的停机指的是停 nacos-server。不会执行，因为你所说的这两者都是 nacos-client 模块下的，不属于nacos-server。这个shudown 是给接入nacos-client的应用调的 :-)

感谢回复。
按照您说的， 我理解nacos-client模块就是java应用接入nacos用到的客户端，里面由应用程序自己决定是否调用shutdown方法对不对？

同时，我们的go应用使用了nacos-sdk-go作为客户端接入nacos，我注意到nacos-sdk-go中的 naming_client 和 
 config_client 并没有实现shutdown方法，请问您如何看待这个事情？

同时，我注意到nacos-server在停机的时候，ProtocolManager 的 apProtocal 对象始终是为空 （APProtocol 这个接口并没有实现类），所以distro协议并没有对停机操作做任何处理对不对？这会不会导致：
集群中的某一台nacos-server节点停机下线，集群中其余的节点需要5秒钟之后才能感知到，在这5秒钟之内，以该节点为权威节点的服务的写请求都会被转发过来，从而导致这些写请求操作都会失败？

**Comment by wangweizZZ** [comment]
1. 是的。
2. 不懂这个问题啥意义？社区肯定会尽力去支持好主流语言，go也会是重点，由于人员精力、功能特性优先级等，语言客户端之间有些不同肯定也正常。
3. 关于这一点，短时间内是会失败，且目前社区在搞支持长链接，这部分感知时间应该更会快。重试就可以了。

**Comment by MajorHe1** [comment]
明白了，谢谢
