### ISSUE TITLE
在首页左边菜单栏看不到权限配置的菜单

### ISSUE THREAD

**Issue by 929404097** [alibaba/nacos#4515]
## Issue Description

在首页左边菜单栏看不到权限配置的菜单

### Describe what happened (or what feature you want)

在首页左边菜单栏看不到权限配置的菜单
![nacos](https://user-images.githubusercontent.com/32952450/102565315-2f172a80-4118-11eb-989e-deb2a8833c6a.jpg)

### Describe what you expected to happen

在首页左边菜单栏能看到权限配置的菜单
### How to reproduce it (as minimally and precisely as possible)

1. 使用nacos1.4.0版本源码在本地启动
2. 登录nacos账号

### Tell us your environment
java 1.8
windows10
nacos1.4.0

**Comment by 929404097** [comment]
@KomachiSion

**Comment by wangweizZZ** [comment]
这边未能复现，你用的什么浏览器？建议清下浏览器缓存试试 可以打开浏览器开发者工具，看下login 接口返回的globalAdmin属性是否为true

**Comment by 929404097** [comment]
> 这边未能复现，你用的什么浏览器？建议清下浏览器缓存试试 可以打开浏览器开发者工具，看下login 接口返回的globalAdmin属性是否为true

感谢您的回复哈，在你回复之前，我重启电脑就可以了，之前我用的是chrome浏览器，也清过浏览器缓存的

**Comment by yangli-git** [comment]
> globalAdmin
我这边也有这个问题，返回值是globalAdmin属性是否为false
