### ISSUE TITLE
nacos2.0单点启动失败

### ISSUE THREAD

**Issue by yuegb** [alibaba/nacos#4520]
![1608282481(1)](https://user-images.githubusercontent.com/49386715/102596398-13ca1080-4154-11eb-9cb1-f4fb0a624ff4.jpg)

**Comment by KomachiSion** [comment]
What's the real error for your start up? your information is not right and useful.

Please provide the real error information, if you don't know, please provider whole nacos.log file.

**Comment by yuegb** [comment]
[Uploading nacos.log…]()

**Comment by yuegb** [comment]
麻烦帮忙看一下 谢谢

**Comment by KomachiSion** [comment]
日志文件的地址是无效的

**Comment by KomachiSion** [comment]
Can't reproduce and user upload log file is invalid and no response for a long time. So close issue, if the problem not solved, please submit a new issue with full information.
