### ISSUE TITLE
com.alibaba.nacos.client.Worker.longPolling发生线程死锁

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4524]
使用的客户端版本：
              <dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>nacos-config-spring-boot-starter</artifactId>
			<version>0.2.7</version>
		</dependency>

使用了此客户端的应用内存使用量飙升。
对象统计如下：
![image](https://user-images.githubusercontent.com/11936135/102683366-76caae80-420b-11eb-9abb-bf137ef06841.png)

线程堆栈如下：
![image](https://user-images.githubusercontent.com/11936135/102683379-9661d700-420b-11eb-99b4-3abe214a1375.png)

**Comment by wangweizZZ** [comment]
死锁？截图的3个waiting都是线程池的线程呀

**Comment by wanghuigithub** [comment]
> 死锁？截图的3个waiting都是线程池的线程呀

都在waiting。在waiting什么资源。没定位到
是线程池的线程也确实在waiting

**Comment by wangweizZZ** [comment]
> > 死锁？截图的3个waiting都是线程池的线程呀
> 
> 都在waiting。在waiting什么资源。没定位到
> 是线程池的线程也确实在waiting

在waiting 提交到线程池的任务，这是正常的。配置少的时候就一个longPolling线程在工作。

**Comment by wanghuigithub** [comment]
> > > 死锁？截图的3个waiting都是线程池的线程呀
> > 
> > 
> > 都在waiting。在waiting什么资源。没定位到
> > 是线程池的线程也确实在waiting
> 
> 在waiting 提交到线程池的任务，这是正常的。配置少的时候就一个longPolling线程在工作。

现在应该是好多线程都在waiting。
创建出来很多的aqs中的node对象。导致内存使用量持续增长

**Comment by KomachiSion** [comment]
dump 堆内存看一下，是不是存在很多个NacosConfigServer对象，如果是的话就是使用方式不对。一个进程不应该有多个这个对象。

**Comment by wanghuigithub** [comment]
> dump 堆内存看一下，是不是存在很多个NacosConfigServer对象，如果是的话就是使用方式不对。一个进程不应该有多个这个对象。

看了下dump，没有存在很多NacosConfigServer对象

**Comment by KomachiSion** [comment]
那就是正常的，忽略即可。waiting以应该是线程池中的线程没有task去执行，所以在等待状态。

**Comment by KomachiSion** [comment]
而且死锁的状态不是这个，建议好好学习一下JDK的线程池Executor中的BlockQueue。

**Comment by wanghuigithub** [comment]
> 那就是正常的，忽略即可。waiting以应该是线程池中的线程没有task去执行，所以在等待状态。

使用的内存持续增加。超过90%了。应该不是正常的

**Comment by wanghuigithub** [comment]
> 而且死锁的状态不是这个，建议好好学习一下JDK的线程池Executor中的BlockQueue。

waiting是在waiting什么资源呢，这个应该怎么确定

**Comment by KomachiSion** [comment]
内存使用量飙升可能是你自己的业务内容量飙升， 提供的信息无法判断是nacos的内容飙升。

waiting什么东西你截图都以及显示出来了，不懂的话自己借助搜索引擎，这里不是课堂。Java基础需要自己想办法学习。

**Comment by wanghuigithub** [comment]
> 内存使用量飙升可能是你自己的业务内容量飙升， 提供的信息无法判断是nacos的内容飙升。
> 
> waiting什么东西你截图都以及显示出来了，不懂的话自己借助搜索引擎，这里不是课堂。Java基础需要自己想办法学习。

好的，我自己学习下基础。

从上边两张图中可以看到，有非常多的com.alibaba.nacos.client.Worker.longPolling线程在因为take而waiting。并且从jmap结果也可以看到，创建了非常多数量的AQS中的Node对象。

业务代码中在获取配置时，使用了如下代码：
![image](https://user-images.githubusercontent.com/11936135/102996181-94767b80-455d-11eb-9f6e-7e21c6a8f534.png)


想问下上图中的使用方式是否会造成创建出了很多的com.alibaba.nacos.client.Worker.longPolling线程

**Comment by KomachiSion** [comment]
如果是同一个appName和groupName就不会。 如果是不同的。每2000个不同的组合就会创建一个新longPolling线程。

**Comment by KomachiSion** [comment]
AQS中的Node对象有可能不是nacos的线程池创建的，你业务如果用了线程池，也会创建。或者你自己使用了Block队列，往里放东西也会创建。 仅看对象并不能判断。

**Comment by KomachiSion** [comment]
而且如果你学习了AQS和线程池Executor就会发现， 如果Node对象很多，说明队列里应该是积压状态，那么longPolling线程应该不是waiting状态，因为他有Task需要执行。longPolling线程在waiting队列有内容，说明longPolling线程池的AQS是空的状态，那么这些Node大概率是你自己业务内容积压了。或者是从没触发过GC，是旧的无用对象， 下次GC就没了。

**Comment by wanghuigithub** [comment]
> 而且如果你学习了AQS和线程池Executor就会发现， 如果Node对象很多，说明队列里应该是积压状态，那么longPolling线程应该不是waiting状态，因为他有Task需要执行。longPolling线程在waiting队列有内容，说明longPolling线程池的AQS是空的状态，那么这些Node大概率是你自己业务内容积压了。或者是从没触发过GC，是旧的无用对象， 下次GC就没了。


表达下不同观点：从上两图中可以看出。
线程之所以waiting，是由于ScheduledThreadPoolExecutor中1081的调用导致的。
从本行开始追踪，会调用到AbstractQueuedSynchronizer的第2032行。
在AbstractQueuedSynchronizer的2035行进行了new node()的动作。
所以我认为，在线程被触发为waiting的过程中，也是会创建node对象的。

**Comment by KomachiSion** [comment]
是这样吗， 那你应该提issue给JDK。你的线程池用的AQS有死锁 会造成Node无限增长。

**Comment by wanghuigithub** [comment]
> 是这样吗， 那你应该提issue给JDK。你的线程池用的AQS有死锁 会造成Node无限增长。

哎，我自己看吧，跟你沟通已经耗尽了我最后一点耐心。
可能你技术太牛了。不屑于跟我沟通。所以字里行间基本都在diss。

**Comment by KomachiSion** [comment]
因为我们告诉你问题不在这了， 你说是这个问题，那我只能让你继续看下去定位问题，环境在你手里，我们复现不了问题。
你说线程多，又不说有几个。你要别人如何帮你。

提供的信息也是破碎化的，大家又不是你老师，又不是你下属，都是业余时间搞一搞。没有那么多精力手把手教你的。

**Comment by KomachiSion** [comment]
最后帮你一下，快速确认是不是你截图中的线程的问题
ClientWorker 的构造方法，大概451行左右（不清楚你使用的client版本，但是大概在这附近）
```
        executorService = Executors.newScheduledThreadPool(Runtime.getRuntime().availableProcessors(), new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                Thread t = new Thread(r);
                t.setName("com.alibaba.nacos.client.Worker.longPolling." + agent.getName());
                t.setDaemon(true);
                return t;
            }
        });
```

这个线程池数量等于你核心数，考虑到你截图并不全，所以需要你自己再次确认一下jstack中叫这个名字的线程数量是否是核心数。
一致的话就是正常值 不算多。

最后再说一下wating。

wating是线程池从队列中task内容，由于使用的是阻塞队列，当队列中无内容时， 线程会无限等待，直到队列有内容后，收到notify通知之后再次被激活才会运行，即使在你所说的行数会创建Node，但是由于线程本身已经block住了，不会向后执行，因此最多Node数也就等于线程数（只算这个线程池里的队列的话）。
