### ISSUE TITLE
nacos启动后会在用户目录产生两个文件，无法控制

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/nacos#4526]
**Describe the bug**
为啥docker启动已经设置了挂载日志目录，为啥还会在其他地方产生文件加，让人感觉特别乱(当前用户根目录)
![image](https://user-images.githubusercontent.com/62740686/102705965-54e33180-42c8-11eb-9d19-74c9b8417bf1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] centos mac
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] 1.4

**Comment by wangweizZZ** [comment]
不太明白你的描述，你是docker 启动nacos-server，然后截图的两个目录是在 docker 所在服务器(容器外)非挂载情况下自动生成的？docker 里跑的应用 也没这么大能耐做到这个事呀。。

**Comment by zxiaozhou** [comment]
但目前能明确的是就是nacos的信息,但是就不清楚哪产生的，，删除后果几分钟有有了
![image](https://user-images.githubusercontent.com/62740686/102716540-78819880-4317-11eb-8e86-8229113433d4.png)

**Comment by KomachiSion** [comment]
其中一个是日志目录，另一个是nacos的快照缓存和failover目录。客户端初始化时会创建，之后nacos客户端的日志会打在{user.home}/logs/nacos里， 快照缓存会保存在{user.home}/nacos里，{user.home}/nacos里的failover是容灾用的 将来可能会删除。

**Comment by zxiaozhou** [comment]
@KomachiSion 主要是这个让人感觉没法控制，莫名其妙的就产生了

**Comment by KomachiSion** [comment]
当然是可以控制的，只是我们不希望用户进行修改，因为会导致排查问题是难度增加。
随着稳定性和可观测性提升，会在文档写明方式

**Comment by heart-bool** [comment]
@zxiaozhou LocalConfigInfoProcessor.java:206, 修改方式 java -Duser.home=你想要的path 
@KomachiSion 无它意，有点轻微强迫症

**Comment by neochne** [comment]
> @Zxiaozhou LocalConfigInfoProcessor.java:206, 修改方式 java -Duser.home=你想要的path @KomachiSion 无它意，有点轻微强迫症

应该是这两个参数吧：

java -jar \
-DJM.LOG.PATH=xxx \
-DJM.SNAPSHOT.PATH=xxx
