### ISSUE TITLE
如何去掉登陆直接访问服务列表

### ISSUE THREAD

**Issue by zhansang** [alibaba/nacos#4534]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
Please describe detail of your issue in issue comment. We set this template to let you fill rather than a default comment.

Just an title is hard to understand what's your problem.

**Comment by zhansang** [comment]
how can i   view the services list  without login page.   i   set  the  auth config   like this
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**


but  when i  browse   nacos      then  the login page

**Comment by KomachiSion** [comment]
duplicate with #4538
