### ISSUE TITLE
how can i view the services list without login page

### ISSUE THREAD

**Issue by zhansang** [alibaba/nacos#4538]
how can i view the services list without login page. i set the auth config like this
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**

but when i browse nacos then the login page

**Comment by KomachiSion** [comment]
both default user and pass are `nacos`.

Or you can use openAPI to query.

**Comment by zhansang** [comment]
i do not want login page

**Comment by KomachiSion** [comment]
Now there must be login page
