### ISSUE TITLE
win10 nacos-server.1.4.0-BETA，standalone部署，nacos意外停止（重启系统）重启后服务无法注册

### ISSUE THREAD

**Issue by elylon1101** [alibaba/nacos#4539]
win10 nacos-server.1.4.0-BETA，standalone部署，nacos意外停止（重启系统）重启后服务无法注册
failed to req API:/nacos/v1/ns/service/list after all servers([127.0.0.1:8848]) tried

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        #命名空间秘钥
        namespace: c2997040-666c-4f03-a966-8838f858466e
        #自定义读取nacos配置文件（多个配置文件用逗号隔开）
        shared-dataids: config.yml,mysql.yml,redis.yml,common.yml,tx-client.yml
        #运行动态刷新nacos配置文件（多个配置文件用逗号隔开）
        refreshable-dataids: config.yml,mysql.yml,redis.yml
        #此配置对自定义扩展配置的文件扩展名没有影响
        file-extension: yml

**Comment by KomachiSion** [comment]
Maybe duplicate with https://github.com/alibaba/nacos/issues/4210
