### ISSUE TITLE
config server.tomcat.accesslog.enabled=false dosn't work!! in 1.4.0

### ISSUE THREAD

**Issue by benjava** [alibaba/nacos#4541]
upgrade nacos from 1.3.2 to 1.4.0, the config "server.tomcat.accesslog.enabled=false" dosn't work, the access_log also be find on path /logs/;

**Comment by KomachiSion** [comment]
Can you tell us you start nacos with cluster mode or standalone mode?

**Comment by KomachiSion** [comment]
Maybe Refer to #4541

**Comment by benjava** [comment]
> Can you tell us you start nacos with cluster mode or standalone mode?

standalone mode!!
