### ISSUE TITLE
java.lang.NoClassDefFoundError: com/alibaba/nacos/api/naming/NamingService

### ISSUE THREAD

**Issue by trz164** [alibaba/nacos#4549]
I've tried several versions to make sure that there are no errors in the YML configuration file, but I always prompt for errors java.lang.NoClassDefFoundError : com/alibaba/nacos/api/naming/NamingService

What is the problem and what should I do?

**Comment by KomachiSion** [comment]
There must be some dependencies conflict in your project. You need to check in your project by yourself.

The best way is print out the dependencies tree and to find out where happen this conflict.
