### ISSUE TITLE
nacos页面命名空间的配置数限制问题

### ISSUE THREAD

**Issue by David-wu91** [alibaba/nacos#4558]
**Describe the bug**
我们发现在nacos页面上命名空间有配置数为200的限制，但是通过测试，一个命名空间的配置文件数量可以超过200个，并且能够正常读取配置文件，请问这个限制的作用是什么呢

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
这个功能被关闭了，后续可能会彻底移除，控制台可能没有来得及修改。

**Comment by David-wu91** [comment]
能否了解一下设置命名空间参数的初衷是什么吗？我在另一篇贴在中看到说这个容量管理还在开发中，还没有集成到正式版本：
https://github.com/alibaba/nacos/issues/3276

**Comment by KomachiSion** [comment]
防止错用导致的配置数量无限膨胀， 最后导致数据库的操作过慢以及nacos自身的内存泄漏。
