### ISSUE TITLE
gateway return 503 after micro server restart for a long time

### ISSUE THREAD

**Issue by nunuqq1** [alibaba/nacos#4560]
I hava:
A. one gateway written in spring cloud gateway
B. one micro server  written in spring boot

1. teminate B in idea, B disappear in nacos admin page, but when request A from gateway, gateway return "Connection refused: /ip:port", after 20-30 seconds, return 503 SERVICE_UNAVAILABLE.
2. start B in idea, after full started, B appear in nacos admin page, but when request A from gateway, gateway return "503 SERVICE_UNAVAILABLE", after 20-30 seconds, return normal result

annoying me a lot during debug

**Comment by KomachiSion** [comment]
Can nacos console see the gateway and micro server? If see them. It‘s the problem of yourself. 
If can't see, please provider more information like nacos-server logs, nacos-client logs.

**Comment by sanxun0325** [comment]
@nunuqq1 in the com.netflix.Loadbalancer.AbstractServerList getUpdatedListOfServers update cycle is 30 s instance list

**Comment by KomachiSion** [comment]
It seems no nacos' problem. So I close issue.
