### ISSUE TITLE
Nacos1.4集群版本点击经常报错

### ISSUE THREAD

**Issue by kingflyok** [alibaba/nacos#4563]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29110971/103071906-96911680-45ff-11eb-955f-5ece403eb84c.png)
在我点击菜单的时候时不时会提示改错误，具体错误信息如图所示
"*org/springframework/boot/actuate/web/trace/servlet/HttpTraceFilter$CustomStatusResponseWrapper"

**Desktop (please complete the following information):**
 - OS: Centos
 - Version: nacos-server 1.4.0
 - VIP: Nginx

希望可以尽快排查解决一下，谢谢

**Comment by horizonzy** [comment]
看一下服务端的日志呢. nacos.log

**Comment by KomachiSion** [comment]
看一下服务端所有日志，把相关的错误信息都提供一下，还有浏览器也进控制台看一下， 返回的内容是什么

**Comment by KomachiSion** [comment]
No enough information and author has no more response, and we can't reproduce the problem. Close issue
