### ISSUE TITLE
使用kill -15，在程序里addShutdownHook添加钩子后，在进入这个方法的时候就会去触发Naocos注销实例，其实我在这个方法中又等待30秒的，这个情况要如何处理啊？

### ISSUE THREAD

**Issue by dengxixian008** [alibaba/nacos#4564]
**Describe the bug**
使用kill -15，在程序里addShutdownHook添加钩子后，在进入这个方法的时候就会去触发Naocos注销实例，其实我在这个方法中又等待30秒的，这个情况要如何处理啊？

**Desktop (please complete the following information):**
 - SDK 1.4.0

**Comment by KomachiSion** [comment]
啊。。这。。得问你自己啊。

**Comment by dengxixian008** [comment]
我的代码中没有主动去触发 注销接口的，仅仅就只打印了日志，代码如下：
Runtime.getRuntime().addShutdownHook(new Thread() {
			public void run() {
                    log.info(ServerPortConstant.SERVER_NAME +  " kill -15 ...");
			}
		});
打印的日志如下：
![image](https://user-images.githubusercontent.com/38934189/103080805-98fc6c00-4611-11eb-9d93-0a9d98294422.png)

**Comment by dengxixian008** [comment]
![a4](https://user-images.githubusercontent.com/38934189/103081011-03ada780-4612-11eb-8fc7-fc31d2fc1075.png)

**Comment by KomachiSion** [comment]
抱歉，我没有理解你的问题是什么。打了日志不是正常的吗？ 而且我看也没有等30s吗？

**Comment by KomachiSion** [comment]
你是不是说 你没有去注销，但是你kill -15 SCA还是去注销了服务？ 如果是这个问题，那应该SCA也添加了hook，hook触发时肯定是针对所有hook的，SCA在他的hook里做了注销操作。

**Comment by dengxixian008** [comment]
> 你是不是说 你没有去注销，但是你kill -15 SCA还是去注销了服务？ 如果是这个问题，那应该SCA也添加了hook，hook触发时肯定是针对所有hook的，SCA在他的hook里做了注销操作。

是这个意思

**Comment by KomachiSion** [comment]
那你应该阅读一下`com.alibaba.cloud.nacos.registry.NacosServiceRegistry` 或者提你的问题到SCA社区。这并非Nacos的问题。issue我先关了。
