### ISSUE TITLE
Nacos logs do not print to `nacos` logs file but print into users' application logs.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#4567]
**Describe the bug**
When nacos-client run with Spring Cloud Alibaba. almost of nacos log will print into applications' log file but not into nacos log file we expected, which will make users confused because nacos client has async-thread to execute and print result in logs.

**Expected behavior**
Almost nacos-client logs should print into ${user.home}/logs/nacos/naming.log or ${user.home}/logs/nacos/config.log

**Acutally behavior**
Print into users' application business logs file.

**How to Reproduce**
1. Clone Spring cloud alibaba source code 
2. Run with example `nacos-config-example` or `nacos-discovery-spring-cloud-config-client-example`
3. see ${user.home}/logs/nacos/naming.log or ${user.home}/logs/nacos/config.log, no logs or only little logs
4. See console, there are `com.alibaba.nacos.client.config.XXX` log info or `com.alibaba.nacos.client.naming.XXX` log info

**Desktop (please complete the following information):**
 - OS: All
 - Version All
 - Module naming and config
 - SDK spring-cloud-alibaba-nacos

**Additional context**

After researching, the reason is that spring will fire mutilple times `ApplicationEnvironmentPreparedEvent` event during init.
And each event will cause LogSystem clean and reload log configuration, Detail See `AbstractLoggingSystem` and its implementations like `LogbackLoggingSystem` or `Log4j2LoggingSystem`.
 
And nacos-client also will append its configuration into LogContext, But only once. If appending configuration after all event fired, It will work well. But if appending between two events, the nacos log configuration will be cleaned. So the log will print into users log file.

I think we should refactor the codes about nacos log load first. And then we should do changes in spring-boot-nacos and spring-cloud-alibaba-nacos to listener the `ApplicationEnvironmentPreparedEvent` and reload nacos log configuration.
Because nacos log config load should be a part of `ApplicationEnvironmentPrepared`.

But we should pay attention to the order, nacos log reload need after `LoggingSystem` reload.

**Comment by KomachiSion** [comment]
Issue Detai：

# Troubleshooting

For normal startup and init

![image](https://user-images.githubusercontent.com/37170243/103115052-1e2c6300-469c-11eb-93d5-63e6806ba8e4.png)

For trouble, problematic loading sequence and steps

![image](https://user-images.githubusercontent.com/37170243/103115129-5f247780-469c-11eb-953d-153709e97bc7.png)

# Solution

## Plan A 

Do nothing in nacos-client, only  Add listener for `ContextRefreshedEvent ` and reload configuration 

![image](https://user-images.githubusercontent.com/37170243/103115172-88450800-469c-11eb-83b3-ea79674c4f6b.png)

### Advantage:

Easy to Implementation

### Disadvantage:

Some logs during Init may also print into business log.

## Plan B

Listen properties changes event of log framework like logback and log4j2

```
logback `LoggerContextListener` 
log4j2 `PropertyChangeListener` 
```

![image](https://user-images.githubusercontent.com/37170243/103115378-4cf70900-469d-11eb-8cc8-66096d78deee.png)

### Advantage:

Whatever application framework user use. Only changes nacos-client.

### Disadvantage:

Depend on log framework. If log has no event or listener extension. This plan can't works.

## Plan C

Listen same spring events with Spring log system. And do reload after spring log system load finished.

![image](https://user-images.githubusercontent.com/37170243/103115622-4c12a700-469e-11eb-8e55-fda95d3a3b3d.png)

### Advantage:

Full meet the spring event meanings.

### Disadvantage:

We need do changes all in nacos-client, nacos-spring-context, nacos-spring-boot and SCA-nacos.

**Comment by KomachiSion** [comment]
For now, We think Plan C is best. nacos-client need to do refactor to support API of reload log configurations.

**Comment by Maijh97** [comment]
@i will solve it@
