### ISSUE TITLE
Nacos1.4 非单机模式 经常 java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by duanjiex** [alibaba/nacos#4571]
单机模式 没问题
一旦连接数据后  
curl -X POST 'http://192.168.1.2:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'

java.net.SocketTimeoutException: connect timed out%   

启动时候时候日志有很多IP 
The server IP list of Nacos is [192.168.1.2:8848, 192.168.11.112:8848, 192.168.11.116:8848, 192.168.16.101:8847, 192.168.16.102:8848, 192.168.16.103:8848]

**Comment by wangweizZZ** [comment]
是非容器部署的吗？你部署的机器ip 变过否？
如果这里边有些不是预期的ip端口，可以清理下  ~/nacos/conf/cluster.conf（具体文件地址以你实际配置为准） 文件里的ip列表。重启试试，看这个cluster.conf是否还是会出现非预期的地址。

**Comment by KomachiSion** [comment]
`java.net.SocketTimeoutException: connect timed out%` 这个是curl返回的内容吗？ 
可以到服务端看一下服务端日志吗？ 搜一下能不能搜到这个错误信息。

**Comment by KomachiSion** [comment]
No more response from author for a long time, It seems a configuration problem. We will close issue first.
