### ISSUE TITLE
1.4.0Version Server List 503

### ISSUE THREAD

**Issue by dodolook8716** [alibaba/nacos#4573]
- OS: Centos 
 - Version nacos-server 1.4.0
![image](https://user-images.githubusercontent.com/34698754/103130423-a0864880-46d7-11eb-8ce6-eb41ccd756c1.png)
![image](https://user-images.githubusercontent.com/34698754/103130580-41750380-46d8-11eb-8146-40f9ce043b68.png)

我使用docker部署集群模式, 部署后已经手动删除~/data/protocol, 并进行了重启. 现在 服务注册发现在我的项目中没有问题, 我想通过WEB UI来观察当前提供服务的实例. 我需要在页面点击查询三次才能看到我想要的信息, 进入详情需要刷新三次才能看到我想要的信息.

I use docker to deploy the cluster mode. After deployment, I have manually deleted ~/data/protocol and restarted it. Now the service registration found that there is no problem in my project. I want to observe the current service instance through the WEB UI. I need Click the query three times on the page to see the information I want, and enter the details to refresh three times to see the information I want.

我分别观察各个实例的 nacos.log 发现 错误的请求总会引发出现这个异常 `java.lang.IllegalStateException: old raft protocol already stop` 而正确的请求没有这种情况.

I observed the nacos.log of each instance and found that wrong requests always cause this exception `java.lang.IllegalStateException: old raft protocol already stop`, but correct requests do not have this situation.

![image](https://user-images.githubusercontent.com/34698754/103130813-353d7600-46d9-11eb-98f0-76df62951268.png)

**Comment by dodolook8716** [comment]
我尝试使用IP:PORT方式进行访问, 发现其中两个节点访问 服务列表 必然503

I tried to use the IP:PORT method to access, and found that two of the nodes access the service list must be 503

**Comment by KomachiSion** [comment]
我试了一下 确实是会报有这个old raft stop的错误，但是不会返回503.

能看一下返回503的时候的错误信息吗？

**Comment by KomachiSion** [comment]
另外， 第二张截图的节点元数据，全部打开看一下，截图或者复制贴出来看一下

**Comment by KomachiSion** [comment]
@dodolook8716 
我清理环境后在docker环境用1.4.0版本重新搭建了一个集群，并没有一直出现old raft stop的错误，且没有出现503的错误。

然后我又在物理机环境搭建了3台1.4.0版本的集群，也没有出现old raft stop的错误，和503的错误。

> 能看一下返回503的时候的错误信息吗？
> 另外， 第二张截图的节点元数据，全部打开看一下，截图或者复制贴出来看一下

能麻烦提供一下这两个信息吗？ 否则我们没法复现问题，只能关闭issue了

**Comment by dodolook8716** [comment]
> @dodolook8716
> 我清理环境后在docker环境用1.4.0版本重新搭建了一个集群，并没有一直出现old raft stop的错误，且没有出现503的错误。
> 
> 然后我又在物理机环境搭建了3台1.4.0版本的集群，也没有出现old raft stop的错误，和503的错误。
> 
> > 能看一下返回503的时候的错误信息吗？
> > 另外， 第二张截图的节点元数据，全部打开看一下，截图或者复制贴出来看一下
> 
> 能麻烦提供一下这两个信息吗？ 否则我们没法复现问题，只能关闭issue了

感谢你的关注.

503的错误信息截图:
![image](https://user-images.githubusercontent.com/34698754/103392516-43681800-4b59-11eb-81f3-f979fc1ab41d.png)

我分别ip:port方式访问了三个节点, 通过devtool 将 `/v1/core/cluster/nodes` 响应json 复制出来,

[node1.json.txt](https://github.com/alibaba/nacos/files/5756372/node1.json.txt)
[node2.json.txt](https://github.com/alibaba/nacos/files/5756373/node2.json.txt)
[node3.json.txt](https://github.com/alibaba/nacos/files/5756374/node3.json.txt)

**Comment by KomachiSion** [comment]
方便吧3个节点的服务端日志全部打包上传一下吗？

服务端返回server is Down now，应该是raft选主没有成功，导致状态一直是非启动。

**Comment by lx308033262** [comment]
我用k8s搭建的  感觉rafe选举还是有些问题 不太确定和k8s网络是否有关系
有些节点不正常  不知道怎么传图片  显示如下
{
    "adWeight": "0",
    "raftPort": "7848",
    "site": "unknow",
    "weight": "1"
}

有些节点正常  
{
    "adWeight": "0",
    "lastRefreshTime": 1610612210988,
    "naming": {
        "ip": "nacos-3.nacos-headless.kifs.svc.cluster.local:8848",
        "heartbeatDueMs": 2958,
        "term": -1,
        "leaderDueMs": 990,
        "state": "FOLLOWER"
    },
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "nacos-3.nacos-headless.kifs.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-1.nacos-headless.kifs.svc.cluster.local:7848",
                    "nacos-0.nacos-headless.kifs.svc.cluster.local:7848",
                    "nacos-3.nacos-headless.kifs.svc.cluster.local:7848",
                    "nacos-4.nacos-headless.kifs.svc.cluster.local:7848"
                ],
                "term": 8
            }
        }
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}

**Comment by lx308033262** [comment]
[root@nacos-4 nacos]# curl http://nacos-2.nacos-headless.kifs.svc.cluster.local:8848/nacos/v1/ns/raft/state
caused: old raft protocol already stop;[root@nacos-4 nacos]#

**Comment by KomachiSion** [comment]
raft的关键日志一般在 alipay-jraft.log , protocol-raft.log, naming-raft.log, nacos.log

把这几个文件上传一下吧。 几个节点都需要

**Comment by stalary** [comment]
我从1.3.1升级到1.4.1也遇到了这个问题

**Comment by admintertar** [comment]
也遇到这个问题，完整的日志

**Comment by admintertar** [comment]
k8s节点之间都是互通的
![image](https://user-images.githubusercontent.com/29689362/109425557-bdb2fc80-7a23-11eb-8c3f-2fc1e2dc6c2c.png)

**Comment by admintertar** [comment]
![image](https://user-images.githubusercontent.com/29689362/109425624-1a161c00-7a24-11eb-8581-f60bcfab05ea.png)
![image](https://user-images.githubusercontent.com/29689362/109425643-2b5f2880-7a24-11eb-8451-75664ca7571b.png)

**Comment by admintertar** [comment]
无法注册的服务日志
![image](https://user-images.githubusercontent.com/29689362/109425691-71b48780-7a24-11eb-995c-716605fd7c06.png)

**Comment by a386572631** [comment]
你好，这个问题有解决了么？我 k8s 1.17，nacos1.4.1也遇到了一样的问题。

**Comment by liurenbao** [comment]
我也是遇到了这个问题，生产出现故障多次了，更新pod后就会异常，nacos要重新部署才恢复

**Comment by wuwu955** [comment]
+1
