### ISSUE TITLE
[NacosConfigClient] Error: write EPIPE (address: 127.0.0.1:7777) 

### ISSUE THREAD

**Issue by Thinking80s** [alibaba/nacos#4577]
**Describe the bug**
pm2 reload trigger error

![image](https://user-images.githubusercontent.com/338079/103143986-922e4000-475c-11eb-86d4-a9bc2ea6198e.png)

sdk: 1.4.0 pm2 cluster mode

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
I can't understand your problem. Please describe it more detail.

**Comment by Thinking80s** [comment]
1、config pm2 cluster mode node app 
2、pm2 reload app
3、configClient.subscribe
when config nacos data trigger the error info

**Comment by KomachiSion** [comment]
What's pm2 cluster？

What's NacosConfigClient？ I can't find this log location.

**Comment by KomachiSion** [comment]
NodeJs client？

**Comment by Thinking80s** [comment]
> NodeJs client？

yes

**Comment by KomachiSion** [comment]
No one in community solve this issue, can submit issue to nacos-group/nacos-sdk-nodejs.
