### ISSUE TITLE
[Question] Why does the 'namespaceid' have three names

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/nacos#4580]
# Create namespace  
It name `customNamespaceId`  

# Modify namespace
It name `namespace`  

# Delete namespace 
It name `namespaceId`  

Just confused me. Is it as expected?

**Comment by liangyuanpeng** [comment]
Actually .. It also name `tenant` In API about of Configurations

**Comment by KomachiSion** [comment]
In create namespace, you can specified an id and a name for namespace, if no input namespace id. nacos will generate an UUID. And the `customNamespaceId` is your input id. 

And the id is the unified identity for namespace. So delete and update namespace use namespaceId to search the right namespace.

For the `tenant`, it is a history name for `namespace`, now nacos need to be compatible with old version client so current use `tenant` in configuration. But in future, we will use only namespace.

**Comment by liangyuanpeng** [comment]
Thanks for your replay.  

> In create namespace, you can specified an id and a name for namespace, if no input namespace id. nacos will generate an UUID. And the customNamespaceId is your input id.  

Why just use `namespaceId`?  It's the same thing.  

> For the tenant, it is a history name for namespace, now nacos need to be compatible with old version client so current use tenant in configuration. But in future, we will use only namespace.

Maybe we can add param `namespaceId` for Configurations API and keep the `tenant` for old version api.  

It is important that update [API doc](https://nacos.io/en-us/docs/open-api.html) and reduce confusion for beginners.

**Comment by KomachiSion** [comment]
> Maybe we can add param namespaceId for Configurations API and keep the tenant for old version api.

It might be a solution, and we may need a logic to ensure users must input namespace or tenant and can't have affect for old version API.

**Comment by KomachiSion** [comment]
Move to #4892
