### ISSUE TITLE
[Question] Have some API Doc some like swagger UI?

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/nacos#4581]

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/open-api.html

**Comment by HSPCode** [comment]
1.配置文件的metadata属性,可以自定义子属性
![nacos-config-metadata](https://user-images.githubusercontent.com/47849395/103397337-ed07d300-4b72-11eb-84b5-0fec279d5c1c.jpg)
2.nacos-console服务列表页面，点击详情查询实例列表时会返回这个属性
![nacos-console-api-result](https://user-images.githubusercontent.com/47849395/103397423-4ec83d00-4b73-11eb-876d-34f717eaf6bd.jpg)
