### ISSUE TITLE
nacos's rich-text

### ISSUE THREAD

**Issue by lamberfox** [alibaba/nacos#4585]
**Describe the bug**
Rich text doesn't come out when editing a configuration file. And it happens periodically.

**Expected behavior**
can edit.

**Desktop (please complete the following information):**
 - Version 1.3.2

[https://vrqn.liuliangin.com/QQ%E5%9B%BE%E7%89%8720201228102536.png](url)
[https://vrqn.liuliangin.com/QQ%E5%9B%BE%E7%89%8720201228102702.png](url)

**Comment by Maijh97** [comment]
`ERR_CONTENT_LENGTH_MISMATCH` error, should be concerned with Nginx, please check the nginx error message.

**Comment by lamberfox** [comment]
> `ERR_CONTENT_LENGTH_MISMATCH` error, may be related to Nginx, please check the nginx error message.
It was actually caused by Nginx because the log was full due to too many requests. Thank you for your patience.
