### ISSUE TITLE
config导出包能否支持编辑后再次导入nacos (Whether the config export package can support editing and then importing nacos again)

### ISSUE THREAD

**Issue by wjm0729** [alibaba/nacos#4601]
config导出包能否支持编辑后再次导入nacos

我项目有几十个config配置, 在进行重构的时候, 可能需要一次性调整所有这些配置
在现有的console-UI中, 只能逐个编辑 发布,低效而且没法对内容进行全局搜索
难以确定所有项目是否都改完了
而这样的修改在eclipse/vscode/idea中却是很简单就可以做到的

---------下面是bing翻译的-------------

Whether the config export package can support editing and then importing nacos again

My project has dozens of configurations, all of which may need to be adjusted at once while refactoring
In the existing console-ui, can only be edited and published one by one, inefficient and unable to search the content globally, it is difficult to determine whether all items have been changed. Such modifications can be done very easily in eclipse / vscode / idea

**Comment by KomachiSion** [comment]
导出之后解压缩， 然后你用工具全部改完，再压缩导入就好了啊。

**Comment by KomachiSion** [comment]
@KeRan213539 麻烦看一下是不是如果只修改内容的话，保持其他东西前后一致就可以了
@TsingLiang 麻烦看一下兼容性的问题

**Comment by wjm0729** [comment]
看了下最新的代码, 确实有支持修改导入. 但是有两个bug
1: 当在mac环境中压缩后, 文件夹中会有一些 . 开头的文件夹和系统文件 unzip 方法没有处理
2: 导入后 config 的type类型会丢失

**Comment by KomachiSion** [comment]
那是导入处理逻辑的bug 不是你这个优化能解决的。

**Comment by KeRan213539** [comment]
> 看了下最新的代码, 确实有支持修改导入. 但是有两个bug
> 1: 当在mac环境中压缩后, 文件夹中会有一些 . 开头的文件夹和系统文件 unzip 方法没有处理
> 2: 导入后 config 的type类型会丢失

1. 目前情况下, 重新压缩的包里不要带有其他东西.
2. 导出的内容本身就没有 config 的 type, 所以不存在丢失的说法. 导入的时候是根据dataid的后缀做了简单类型判断. 如果你dataid没有后缀,或者后缀无法识别.导入后默认为text
3. 不改变压缩包里目录结构的前提下,修改配制内容是没问题的,新增配制都可以. .meta.yml 文件不是必须的,里面仅包含了所属应用的信息. 就算你直接在文件系统里按照包里的结构创建一套配制再zip也是可以导入的
4. 您的这个PR我们暂时没法合并, 具体原因回复在RP里了

**Comment by wjm0729** [comment]
[导出的内容本身就没有 config 的 type]
你的这个说法我不赞同
导出时为什么就不能带上type呢? 
导出时在meta里面带上type又有什么坏处呢?
另外一个要吐槽一下的, 为什么要将 ConfigType 的 type 值定义的和实际文件后缀不一致呢?

至于第3点我可以认为你只关心核心逻辑, 不做用户体验的优化.

**Comment by wjm0729** [comment]
@KomachiSion
抱歉, 我这个改的比较早吧, 11月份左右改的吧, 可能当时主干还没有支持

**Comment by KomachiSion** [comment]
我刚试了一下，我导出2个配置，在本地解压缩修改 再压缩导入  是完全可以的。

也没有出现mac的特殊文件。

是不是和系统版本有关，我是10.15.6 macOS

至于导出没有带上type。这个是历史问题吧。要改起来可能不是特别容易。主要是兼容性问题比较难处理。

**Comment by KeRan213539** [comment]
> [导出的内容本身就没有 config 的 type]
> 你的这个说法我不赞同
> 导出时为什么就不能带上type呢?
> 导出时在meta里面带上type又有什么坏处呢?
> 另外一个要吐槽一下的, 为什么要将 ConfigType 的 type 值定义的和实际文件后缀不一致呢?
> 
> 至于第3点我可以认为你只关心核心逻辑, 不做用户体验的优化.

文件后缀和类型定义在这里FileTypeEnum, ConfigType  里是真正的 type

**Comment by KeRan213539** [comment]
#4602
