### ISSUE TITLE
Can't update the metadata of nacos instance by request open API  

### ISSUE THREAD

**Issue by 2YSP** [alibaba/nacos#4604]
nacos version: 1.3.0
I use postman to send request,
**http://127.0.0.1:8848/nacos/v1/ns/instance?groupName=SHIP_GATE&metadata={"appName":"order","version":"gray_1.0","plugins":"DynamicRoute,Auth"}&port=8082&ip=10.8.20.102&weight=5.0&ephemeral=true&serviceName=order**
the response is **HTTP Status 400 – Bad Request.**
but if I remove the metadata param try again,
  **http://127.0.0.1:8848/nacos/v1/ns/instance?groupName=SHIP_GATE&port=8082&ip=10.8.20.102&weight=5.0&ephemeral=true&serviceName=order**
It return ok.
Now I suspect it does not support metadata parameter.

**Comment by KomachiSion** [comment]
Don't suspect nacos whether support metadata parameter. You need encodeURL if you wan't set some special chars in uri.

**Comment by 2YSP** [comment]
thanks,I URLEncode the **{"appName":"order","version":"gray_1.0","plugins":"DynamicRoute,Auth"}** and it works.
