### ISSUE TITLE
【Nacos 2.0】 Is there any example, tell me how to use grpc

### ISSUE THREAD

**Issue by robotLJW** [alibaba/nacos#4611]
article：[支持 gRPC 长链接，深度解读 Nacos 2.0 架构设计及新模型](https://blog.csdn.net/alisystemsoftware/article/details/111934889)

my problem：I'm not very familiar with grpc, can you provide me with relevant use cases. thx.

**Comment by robotLJW** [comment]
@KomachiSion thx

**Comment by horizonzy** [comment]
just upgrade nacos-server and nacos-client to 2.0.0-ALPHA.1. The default protocol is grpc.

**Comment by robotLJW** [comment]
> just upgrade nacos-server and nacos-client to 2.0.0-ALPHA.1. The default protocol is grpc.

thx

**Comment by robotLJW** [comment]
**I want to ask two questions.**

1. What grpc pressure measurement tool do you use ？

2. I found some grpc testing tools. Such as jmeter's grpc plugin and ghz, but they all need to provide proto files. I did not find the corresponding proto file.

![image](https://user-images.githubusercontent.com/27326092/103516935-4beb8600-4eac-11eb-8168-17c0fcfd54b6.png)

thx

**Comment by robotLJW** [comment]
@KomachiSion thx
