### ISSUE TITLE
Class JwtTokenManager and JwtTokenUtils are duplicated

### ISSUE THREAD

**Issue by haoyann** [alibaba/nacos#4612]
**Is your feature request related to a problem? Please describe.**

Class `com.alibaba.nacos.console.security.nacos.JwtTokenManager` and `com.alibaba.nacos.console.utils.JwtTokenUtils`
are both jwt token util class.  

But JwtTokenUtils only `com.alibaba.nacos.console.utils.JwtTokenUtils#createToken` is used at `com.alibaba.nacos.console.controller.UserController#login`.
```
    public Object login(@RequestParam String username, @RequestParam String password, HttpServletResponse response,
            HttpServletRequest request) throws AccessException {
        
        if (AuthSystemTypes.NACOS.name().equalsIgnoreCase(authConfigs.getNacosAuthSystemType())) {
            NacosUser user = (NacosUser) authManager.login(request);
            
            response.addHeader(NacosAuthConfig.AUTHORIZATION_HEADER, NacosAuthConfig.TOKEN_PREFIX + user.getToken());
            
            ObjectNode result = JacksonUtils.createEmptyJsonNode();
            //            JSONObject result = new JSONObject();
            result.put(Constants.ACCESS_TOKEN, user.getToken());
            result.put(Constants.TOKEN_TTL, authConfigs.getTokenValidityInSeconds());
            result.put(Constants.GLOBAL_ADMIN, user.isGlobalAdmin());
            return result;
        }
        
        // 通过用户名和密码创建一个 Authentication 认证对象，实现类为 UsernamePasswordAuthenticationToken
        UsernamePasswordAuthenticationToken authenticationToken = new UsernamePasswordAuthenticationToken(username,
                password);
        
        RestResult<String> rr = new RestResult<String>();
        try {
            //通过 AuthenticationManager（默认实现为ProviderManager）的authenticate方法验证 Authentication 对象
            Authentication authentication = authenticationManager.authenticate(authenticationToken);
            //将 Authentication 绑定到 SecurityContext
            SecurityContextHolder.getContext().setAuthentication(authentication);
            //生成Token
            String token = jwtTokenUtils.createToken(authentication);
            //将Token写入到Http头部
            response.addHeader(NacosAuthConfig.AUTHORIZATION_HEADER, "Bearer " + token);
            rr.setCode(200);
            rr.setData("Bearer " + token);
            return rr;
        } catch (BadCredentialsException authentication) {
            rr.setCode(401);
            rr.setMessage("Login failed");
            return rr;
        }
    }
```
I found that `com.alibaba.nacos.console.utils.JwtTokenUtils#createToken` will only be used when nacosAuthSystemType != nacos , but the document describes `The auth system to use, currently only 'nacos' is supported:`, so `com.alibaba.nacos.console.utils.JwtTokenUtils` will not be used anywhere .

**Describe the solution you'd like**
Remove class JwtTokenUtils and  clean method `com.alibaba.nacos.console.controller.UserController#login`.

**Comment by horizonzy** [comment]
I think it can be removed. Now `com.alibaba.nacos.console.utils.JwtTokenUtils` supply createToken function.
And `com.alibaba.nacos.console.security.nacos.JwtTokenManager` can take over all of it. 
If we need support other`authSystemType`,  `com.alibaba.nacos.console.security.nacos.JwtTokenManager` can cover it.

**Comment by horizonzy** [comment]
Just remove class `JwtTokenUtils`, remains the extential code which support other authSystem in `com.alibaba.nacos.console.controller.UserController#login`.  `jwtTokenUtils.createToken(authentication)` can be replaced with `com.alibaba.nacos.console.security.nacos.JwtTokenManager#createToken(authentication)`
