### ISSUE TITLE
nacos1.1.4 集群节点数是否一定要大于等于3个

### ISSUE THREAD

**Issue by RongXiong2016** [alibaba/nacos#4614]
![image](https://user-images.githubusercontent.com/18466554/103434211-2acf2f00-4c39-11eb-97ea-83fd5b858522.png)

**Comment by KomachiSion** [comment]
考虑到raft选主，建议保持3个以上节点。如果只有2节点在网络隔离场景将出现raft无法选主成功造成不可写的问题
