### ISSUE TITLE
Nacos user login api only supported http protocol in Nacos Client 1.4.0

### ISSUE THREAD

**Issue by ryuhi** [alibaba/nacos#4615]
**Describe the bug**
In Nacos Client 1.4.0 SecurityProxy File, Method login
```
public boolean login(String server) {
    
   if (StringUtils.isNotBlank(username)) {
      Map<String, String> params = new HashMap<String, String>(2);
     Map<String, String> bodyMap = new HashMap<String, String>(2);
     params.put("username", username);
     bodyMap.put("password", password);
    String url = "http://" + server + contextPath + LOGIN_URL;
  
     if (server.contains(Constants.HTTP_PREFIX)) {
        url = server + contextPath + LOGIN_URL;
    }
```
Why do you can confirm all the users using nacos all use http protocol? If the user uses https protocol?

**Expected behavior**
Support both http and https protocol

**Acutally behavior**
only support http protocol in code.

**How to Reproduce**
Open the Nacos Client code in 1.4.0 version.

**Comment by wangweizZZ** [comment]
Now client support both http and https. Maybe SecurityProxy's code can improve readability later

You can use nginx to support https for nacos server. Then you need to do some configuration on the client to support https as follows.
`System.setProperty(TlsSystemConfig.TLS_ENABLE, "true");`
And  set `serverAddr` like  `https://xxxxx`

For more information, please see #3654.
