### ISSUE TITLE
NamespaceId information is not checked in Api

### ISSUE THREAD

**Issue by CaiJiHuzhuo** [alibaba/nacos#4618]
In my project, I needed to use OpenAPI to take instance offline, and I found that my NamespaceId was configured incorrectly, but the result returned to me was OK.
I noticed that none of the nacos OpenAPI checks on NamespaceId.
Such as:
When I use a namespaceId that does not exist, I can successfully register by calling the Nacos openAPI.

Here's what I think:
Now the namespace information in nacos is stored in the database. Why not also store a namespace information in memory?
When the Namespaceid is needed, check that the namespaceid is present and correct.
If need to check ,i can fix this problem.

![1](https://user-images.githubusercontent.com/22318893/103514027-c4e7df00-4ea6-11eb-9423-0c897f3e3e61.png)
![2](https://user-images.githubusercontent.com/22318893/103514037-cb765680-4ea6-11eb-9e74-53fe02c2a14b.png)

**Comment by KomachiSion** [comment]
duplicate with #4134

**Comment by KomachiSion** [comment]
@CaiJiHuzhuo This issue has existed, if you want to solve it, please move to #4134 to discuss.
