### ISSUE TITLE
nacos呼声挺高，用了后失落，提几点建议吧

### ISSUE THREAD

**Issue by kangkai9432** [alibaba/nacos#4619]
Type: feature request
1. 租户和命名空间混淆不清，一会namespaceId、一会tenant、就一个namespaceId不就完了，说明就是区分多租户的、虽然有文档说明，每次都说明一下，写文档的不累么！
2. 配置小组、服务小组、应该是2个概念，容易混淆；配置小组、服务小组、命名空间三个控制有点乱，个人感觉一个命名空间就可以
3. 健康检查个人认为检测是客户端的工作，定时上报就可以了，所以客户端要有个性化接口，客户端一定知道怎么访问mysql、redis等，什么样是健康的，用spring boot端点 health也可以啊。
4. nacos管理台，下线了列表页也看不出来，点详情才能看，一点不直观
5. spring cloud alibaba 的springboot 项目，自己想自定义健康检测通过api删除吧，只要服务启动着呢，自动还能注册，不清楚这open api用的场景
6. open api 修改不到记录，删除不到记录，不要返回OK，聊到这能不能定义一个返回统一的格式，至少最外层结构是固定的

**Comment by KomachiSion** [comment]
> 1. 租户和命名空间混淆不清，一会namespaceId、一会tenant、就一个namespaceId不就完了，说明就是区分多租户的、虽然有文档说明，每次都说明一下，写文档的不累么！

这个问题的确存在，tenant是0.X版本中的历史遗留问题，后续版本会逐渐转移到只有一个namespaceId。

>2. 配置小组、服务小组、应该是2个概念，容易混淆；配置小组、服务小组、命名空间三个控制有点乱，个人感觉一个命名空间就可以

分组区分可以进行一些弱隔离，你可能用不到，但是别人能用到。命名空间只能强隔离。

>3. 健康检查个人认为检测是客户端的工作，定时上报就可以了，所以客户端要有个性化接口，客户端一定知道怎么访问mysql、redis等，什么样是健康的，用spring boot端点 health也可以啊。

如果这么做，是不是就对业务入侵了，他需要接口来告诉nacos-client，现在我是健康的。 如果客户端进程假死了怎么办，如果心跳照发，但是用户告诉nacos-client健康状态的线程阻塞了，怎么办？

>4. nacos管理台，下线了列表页也看不出来，点详情才能看，一点不直观。 

如果觉得不好，欢迎贡献。

>5. spring cloud alibaba 的springboot 项目，自己想自定义健康检测通过api删除吧，只要服务启动着呢，自动还能注册，不清楚这open api用的场景

服务自注册，但通过外部接口确能删除掉其实是不安全的。openAPI是用于开发多语言支持或自定义支持的功能。需要理解openAPI的内容含义。

>6 open api 修改不到记录，删除不到记录，不要返回OK，聊到这能不能定义一个返回统一的格式，至少最外层结构是固定的

同4，不过贡献时请考虑兼容性。

**Comment by KomachiSion** [comment]
最后nacos是很年轻的开源项目，需要社区共同努力让它变好，越早参与，变好的越快。期待你的加入。

**Comment by liangyuanpeng** [comment]
> open api 修改不到记录，删除不到记录，不要返回OK，聊到这能不能定义一个返回统一的格式，至少最外层结构是固定的

其实这点我是很不能理解，默认返回true真的太奇怪了

**Comment by kangkai9432** [comment]
> > 4. 健康检查个人认为检测是客户端的工作，定时上报就可以了，所以客户端要有个性化接口，客户端一定知道怎么访问mysql、redis等，什么样是健康的，用spring boot端点 health也可以啊。
> 
> 如果这么做，是不是就对业务入侵了，他需要接口来告诉nacos-client，现在我是健康的。 如果客户端进程假死了怎么办，如果心跳照发，但是用户告诉nacos-client健康状态的线程阻塞了，怎么办？

@KomachiSion  这个可能是我表达有些问题，我的意思是健康检查应该由nacos-client来做，上报给nacos-server，nacos-client应该可以自定义健康检查接口，比如访问一下数据库和redis等，就像您说的防止客户端进程假死，但是根据nacos的文档，一直没找到nacos-client端如何自定义健康检查接口。

**Comment by horizonzy** [comment]
> > > 1. 健康检查个人认为检测是客户端的工作，定时上报就可以了，所以客户端要有个性化接口，客户端一定知道怎么访问mysql、redis等，什么样是健康的，用spring boot端点 health也可以啊。
> > 
> > 
> > 如果这么做，是不是就对业务入侵了，他需要接口来告诉nacos-client，现在我是健康的。 如果客户端进程假死了怎么办，如果心跳照发，但是用户告诉nacos-client健康状态的线程阻塞了，怎么办？
> 
> @KomachiSion 这个可能是我表达有些问题，我的意思是健康检查应该由nacos-client来做，上报给nacos-server，nacos-client应该可以自定义健康检查接口，比如访问一下数据库和redis等，就像您说的防止客户端进程假死，但是根据nacos的文档，一直没找到nacos-client端如何自定义健康检查接口。

这一块的文档没有进行完善。你说的这个是持久化实例会做的事，服务端会反响探活，通过访问持久化实例提供的端口进行不同协议的探活。目前支持Tcp,Http,Mysql三种探活方式。

**Comment by kangkai9432** [comment]
> 
> 
> > > > 1. 健康检查个人认为检测是客户端的工作，定时上报就可以了，所以客户端要有个性化接口，客户端一定知道怎么访问mysql、redis等，什么样是健康的，用spring boot端点 health也可以啊。
> > > 
> > > 
> > > 如果这么做，是不是就对业务入侵了，他需要接口来告诉nacos-client，现在我是健康的。 如果客户端进程假死了怎么办，如果心跳照发，但是用户告诉nacos-client健康状态的线程阻塞了，怎么办？
> > 
> > 
> > @KomachiSion 这个可能是我表达有些问题，我的意思是健康检查应该由nacos-client来做，上报给nacos-server，nacos-client应该可以自定义健康检查接口，比如访问一下数据库和redis等，就像您说的防止客户端进程假死，但是根据nacos的文档，一直没找到nacos-client端如何自定义健康检查接口。
> 
> 这一块的文档没有进行完善。你说的这个是持久化实例会做的事，服务端会反响探活，通过访问持久化实例提供的端口进行不同协议的探活。目前支持Tcp,Http,Mysql三种探活方式。

@horizonzy @KomachiSion 感觉不在一个点上，假如nacos-client连接池出现泄露，应用端口应该正常，但是业务有访问数据库的请求无响应（或者响应超时），进程处于假死状态！我的问题是nacos如何支持这种情况探活？？？

  服务端会反响探活，目前支持Tcp,Http,Mysql三种探活方式。至少mysql有业务入侵吧，nacos探活感觉这个方向发力不对！！！

**Comment by horizonzy** [comment]
对mysql检测和业务无关，只是对mysql服务进行检测是否可用。比如我的一个mysql集群需要做服务发现，只获取可用的mysql服务列表。

TCP和HTTP探活针对的是服务端口的可用性。如果服务进程出现假死的情况，但是探活端口还能提供服务的话，那么依旧认定该服务是可用的。如果你的进程假死导致探活端口无法访问的话，该服务才会被认定不可用。

**Comment by kangkai9432** [comment]
> 
> 
> 对mysql检测和业务无关，只是对mysql服务进行检测是否可用。比如我的一个mysql集群需要做服务发现，只获取可用的mysql服务列表。
> 
> TCP和HTTP探活针对的是服务端口的可用性。如果服务进程出现假死的情况，但是探活端口还能提供服务的话，那么依旧认定该服务是可用的。如果你的进程假死导致探活端口无法访问的话，该服务才会被认定不可用。

@horizonzy  假如nacos-client连接池出现泄露，应用端口应该正常，但是业务有访问数据库的请求无响应（或者响应超时），进程处于假死状态！我的问题是nacos如何支持这种情况探活？？？ 还是不支持？？？

**Comment by horizonzy** [comment]
上面的回答不是已经提到了吗。关键在与你的进程假死是否会影响端口的正常返回，如果你的进程假死，只是影响你的一些业务执行的话，不影响探活端口的返回，那么服务端认为的你的服务还是可用。如果你的进程假死，影响到了探活端口的返回，那么服务端认为你的服务就不可用了。

**Comment by kangkai9432** [comment]
@horizonzy  不跟你纠结，估计你回答很多人问题，没时间仔细看我的问题，其实我说的很清楚，你没按我的问题去回答，只是按nacos实现回答而已！
       提个功能性需求，其实就是上面的问题，业务端连接池泄露，端口正常能响应，按你们nacos探活思路，业务端是正常的，未来的版本要支持这种情况业务端下线（下线指的是其他路由，或者服务不要请求到这个业务端）

**Comment by kangkai9432** [comment]
@horizonzy @KomachiSion nacos确实非常不错，要不我也不在这里说这么多了！连接池泄露，手工下线，基于这个问题认为nacos服务注册发现体系还是有瑕疵的绝对没毛病，我说个思路，很简单，其实也是业界非常通用的做法，nacos-client发送心跳前提供自定义实现（这个实现里访问一下数据库，设置个超时时间之类的），比如说以5秒为基准，小于5秒发送给nacos-server说我很正常，超过5秒发送给nacos-server说我假死了，把我踢掉吧，当然这个心跳接口是有各种状态的，不是现在这么单一；然后nacos-server管理端在好好规划一下各种状态的展现和上下线操作，这个就基本OK了。

nginx的健康检查，spring boot 的health端点，都是在客户端实现的，大部分实现都是自己访问一下数据库、redis之类的防止假死。

**Comment by horizonzy** [comment]
> @horizonzy @KomachiSion nacos确实非常不错，要不我也不在这里说这么多了！连接池泄露，手工下线，基于这个问题认为nacos服务注册发现体系还是有瑕疵的绝对没毛病，我说个思路，很简单，其实也是业界非常通用的做法，nacos-client发送心跳前提供自定义实现（这个实现里访问一下数据库，设置个超时时间之类的），比如说以5秒为基准，小于5秒发送给nacos-server说我很正常，超过5秒发送给nacos-server说我假死了，把我踢掉吧，当然这个心跳接口是有各种状态的，不是现在这么单一；然后nacos-server管理端在好好规划一下各种状态的展现和上下线操作，这个就基本OK了。

客户端上报心跳可以考虑加一个扩展。扩展里面用户自己定义逻辑，看扩展最后是否决定上报心跳。

> nginx的健康检查，spring boot 的health端点，都是在客户端实现的，大部分实现都是自己访问一下数据库、redis之类的防止假死。

服务端反向检查可能我描述有问题，HTTP的反向检查用户可以自己对http接口进行逻辑处理，看是否返回响应值200，这里是用户自己定义的。

**Comment by KomachiSion** [comment]
> @horizonzy @KomachiSion nacos确实非常不错，要不我也不在这里说这么多了！连接池泄露，手工下线，基于这个问题认为nacos服务注册发现体系还是有瑕疵的绝对没毛病，我说个思路，很简单，其实也是业界非常通用的做法，nacos-client发送心跳前提供自定义实现（这个实现里访问一下数据库，设置个超时时间之类的），比如说以5秒为基准，小于5秒发送给nacos-server说我很正常，超过5秒发送给nacos-server说我假死了，把我踢掉吧，当然这个心跳接口是有各种状态的，不是现在这么单一；然后nacos-server管理端在好好规划一下各种状态的展现和上下线操作，这个就基本OK了。
> 
> nginx的健康检查，spring boot 的health端点，都是在客户端实现的，大部分实现都是自己访问一下数据库、redis之类的防止假死。

nacos有两种健康检查方式， 1. 针对非持久化服务，是客户端上报健康状态的方式，也就是心跳方式。 如果服务端监测到一段时间未收到心跳，就会认为实例不健康而移除。 2. 针对持久化服务，我们认为它是一直存在的，且它不一定有nacos客户端，因此，通过主动探测的方式去进行，TCP和MySQL都是进行端口连接探测，HTTP则是请求内容探测。需要根据具体情况进行。

**Comment by KomachiSion** [comment]
当然你说的这个方式也是一种新的方式， 后续可以考虑加进去。  不过具体方案需要讨论，加入的时机也需要讨论。

**Comment by chensp0668** [comment]
> 当然你说的这个方式也是一种新的方式， 后续可以考虑加进去。 不过具体方案需要讨论，加入的时机也需要讨论。

强烈要求增加上下线通知，针对注册和下线不通事件监听，预留接口可以扩展发钉钉或者企业微信或者接通电话的统一接口。

**Comment by KomachiSion** [comment]
> > 当然你说的这个方式也是一种新的方式， 后续可以考虑加进去。 不过具体方案需要讨论，加入的时机也需要讨论。
> 
> 强烈要求增加上下线通知，针对注册和下线不通事件监听，预留接口可以扩展发钉钉或者企业微信或者接通电话的统一接口。

从nacos的角度来说，通知最新实例列表是最通用的方式，无论是需要区分上下线，还是需要发送其他通知接口，都可以通过最新列表listener来实现。

**Comment by liaomengge** [comment]
> > 当然你说的这个方式也是一种新的方式， 后续可以考虑加进去。 不过具体方案需要讨论，加入的时机也需要讨论。
> 
> 强烈要求增加上下线通知，针对注册和下线不通事件监听，预留接口可以扩展发钉钉或者企业微信或者接通电话的统一接口。

这种直接拉nacos server源码，自己改一下就可以了；毕竟nacos属于开源项目，一些定制化的，都可以公司内部去改造实现。
