### ISSUE TITLE
nacos配置管理，如何在bean加载前获取到配置

### ISSUE THREAD

**Issue by adminSxs** [alibaba/nacos#4623]
比如：引入jpa包，启动项目的时候，直接就报错数据库需要指定url，说明没有先从nacos获取到配置。而是先初始化了bean，能否指定现在加载配置在初始化bean

**Comment by Maijh97** [comment]
请问是使用Spring cloud alibaba吗？还是spring boot，还有nacos 连接是怎么配置的？是配置到bootstrap.yml还是application.yml

**Comment by adminSxs** [comment]
> 请问是使用Spring cloud alibaba吗？还是spring boot，还有nacos 连接是怎么配置的？是配置到bootstrap.yml还是application.yml

使用springboot，用的bootstrap.yml配置文件

**Comment by Maijh97** [comment]
请问可以把配置文件和控制台配置贴一下吗？或者自己比对的一下namespace，和dataID配置是否正确，如果是配置在bootstrap.yml优先级应该是最高的。

**Comment by adminSxs** [comment]
我本上项目配置问题

**Comment by ZslNUPT** [comment]
> 我本上项目配置问题

我也遇到类似的问题，能告知下你是怎么解决的吗？
