### ISSUE TITLE
On the state checking mechanism between nodes in Nacos cluster

### ISSUE THREAD

**Issue by Xezeloh** [alibaba/nacos#4624]
**Is your feature request related to a problem? Please describe.**
At present, Nacos node checks the health status of other nodes by sending HTTP requests to other nodes. In this case, will the Nacos cluster split under extreme conditions?
目前Nacos节点通过向其他节点发送http请求的方式来检查其他节点的健康状态。这样的话，极端状态下，会不会出现Nacos集群分裂的情况？

**Comment by horizonzy** [comment]
如果网络发生问题，集群分裂是正常现象。distro协议还是能够继续正常工作，raft协议的话，需要保证分区后对应的分区中存在半数以上节点，才能提供服务。
