### ISSUE TITLE
Nocas not show dubbo's service details

### ISSUE THREAD

**Issue by joakapp** [alibaba/nacos#4625]
## Issue Description

Type: bug report

使用dubbo-spring-boot-project在nacos中注册时，dubbo的服务已经注册上了，但是查看详情，出现以下错误
**caused: service nxy@@providers:com.hsht.nxy.service.DubboDemoService:1.0.0: is not found!;**

### Tell us your environment

Dubbo Spring Boot (v2.7.8)

Dubbo (v2.7.8)

NACOS2.0.0-ALPHA.1

**Comment by KomachiSion** [comment]
@joakapp please check whether same problem with #4489

**Comment by joakapp** [comment]
thanks !
