### ISSUE TITLE
nacos集群模式无法做到高可用

### ISSUE THREAD

**Issue by seanything** [alibaba/nacos#4627]
failed to request serverStatus, remote server: 192.168.5.87:8848

**Comment by KomachiSion** [comment]
please use issue template to describe your problem, otherwise no body can no what's your problem.

**Comment by seanything** [comment]
**Describe the bug**
I set up a nacos cluster with 3 nodes,when the cluster has 3 nodes on,it works well.
when I close a node , I can't regster new service in the cluster

**Expected behavior**
as long as the cluster has an active node ,It should can be regstered new service

**Acutally behavior**
regstering new service failed 

**How to Reproduce**
Steps to reproduce the behavior:
1. set up a nacos cluster with 3 nodes
2. registering a new service succeed
3. close one of 3 nodes
4. registering a new service failed

**Desktop (please complete the following information):**
 - OS: [Centos7.5]
 - Version [nacos-server 1.4.0, nacos-client 1.4.0]
 - Module [naming]
 - SDK [original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
in my understanding, when registering a service in the cluster,it will request one active node of the 3 nodes .
when the request arrive the node,the node will synchronize the service's info to the other node,but there is a closed node,
so it synchronizes failed and this failed action shouldn't impact the registering action ,the truth is you throw  the exception
to the interface cause registering service failed

**Comment by KomachiSion** [comment]
which version you used? I can't reproduce your description problem in 1.4.0

**Comment by seanything** [comment]
nacos 1.4.0

**Comment by seanything** [comment]
There are 3 nodes , 192.168.0.134,192.168.0.136 192.168.0.138
when 3 nodes are active , the cluster work well,
when I close the node in 192.168.0.134,I can't register a service in cluster;
![image](https://user-images.githubusercontent.com/65645098/103963823-1f2dbc00-5195-11eb-909d-75dcfcd54f20.png)
the exception in the picture is the problem cause I can't register a service.
![image](https://user-images.githubusercontent.com/65645098/103963942-4ab0a680-5195-11eb-93ba-c10626824fbf.png)

**Comment by seanything** [comment]
though I can't register a service in cluster, I can fetch the service info registered

**Comment by KomachiSion** [comment]
Is there any error information in server or client?

**Comment by seanything** [comment]
no problem
mybe the network troubled me before 
thanks
