### ISSUE TITLE
nacos 服务列表一会有数据，一会没数据，删除服务还报错；是不是环境有问题？

### ISSUE THREAD

**Issue by weiguangzhou** [alibaba/nacos#4628]
## Issue Description
nacos 服务列表一会有数据，一会没数据，删除服务还报错；是不是环境有问题？
Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
首先注册服务
然后删除服务
查看服务列表，列表为空，隔了2秒后，又能查出来了

### Describe what you expected to happen

服务删除之后，就不要查出来了

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 
<img width="1434" alt="test" src="https://user-images.githubusercontent.com/25973619/103629031-c2ef5000-4f7a-11eb-9a37-29c23e779358.png">

### Tell us your environment
3节点的集群，具体配置不清楚

**Comment by dyiwen** [comment]
1.4也又这样的问题，服务注册的数据集群间同步不及时

**Comment by KomachiSion** [comment]
推测是raft选主问题。 麻烦提供一下版本。

**Comment by weiguangzhou** [comment]
> 推测是raft选主问题。 麻烦提供一下版本。以及与raft相关的服务端日志 如naming-raft，protocol-raft和alipay-jraft等

集群1.4.0

**Comment by KomachiSion** [comment]
日志麻烦发一下

**Comment by KomachiSion** [comment]
Not enough information to judge problems and the author has no response for a long time. Close issue first. Please upgrade to 1.4.1 and retry. If problem still in there, please provider more detail information and open a new issue.
