### ISSUE TITLE
请问下建立普通用户设置了只读权限，为啥一直报错，也无法查看

### ISSUE THREAD

**Issue by feixia5712** [alibaba/nacos#4633]
我的目的是想建立个普通用户只给查看权限，让开发使用
1 nacos版本1.3.0
2 配置文件如下
web端配置
![image](https://user-images.githubusercontent.com/12670758/103726688-853f0580-5014-11eb-9b5e-cf2c4e5b1303.png)
![image](https://user-images.githubusercontent.com/12670758/103726704-8e2fd700-5014-11eb-8451-21879e69f760.png)
![image](https://user-images.githubusercontent.com/12670758/103726721-9720a880-5014-11eb-9b38-804404eea428.png)
配置文件
![image](https://user-images.githubusercontent.com/12670758/103726936-04ccd480-5015-11eb-95d8-6305481ec50f.png)
nacos.core.auth.enabled=true也不是行
登录进入还是有编辑权限

**Comment by horizonzy** [comment]
报什么错误，发一下看看呢

**Comment by feixia5712** [comment]
nacos.core.auth.enabled=false配置普通用户，能够正常登录，但是还有编辑权限

**Comment by feixia5712** [comment]
为啥没有生效

**Comment by feixia5712** [comment]
![image](https://user-images.githubusercontent.com/12670758/103733924-c7bd0e00-5025-11eb-9d92-a98a93ba5380.png)

**Comment by horizonzy** [comment]
> nacos.core.auth.enabled=false配置普通用户，能够正常登录，但是还有编辑权限

`nacos.core-auth.enabled=true`, 权限才会生效。 
现在的权限是后台验证， 不会在前端根据权限隐藏对应的按钮。

**Comment by KomachiSion** [comment]
Usage problem. Author has no response for a long time, we think the problem has solved.
