### ISSUE TITLE
nacos client建议增加日志最多保留天数、日志累计大小控制property

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#4639]
虽然提供了nacos.logging.config这个方法，但是只是为了能够自动清理日志，把client里面自带的log4j2.xml复制一份出来加delete配置有点过于复杂了，建议加两个应用可配置的property，在log4j2NacosLogging.class或者logbackNacosLogging.class解析log配置文件时同时处理了。

**Comment by horizonzy** [comment]
The log clean policy should define by user, the default policy shouldn't auto clean it.

**Comment by horizonzy** [comment]
加两个property是什么意思？

**Comment by zrlw** [comment]
就是提供两个日志清理策略属性，好比设置日志级别为error那样：
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: error
默认情况下不清理，如果设置了就按设置的清理策略进行清理，现在清理nacos日志需要应用自定义nacos配置文件，比较啰嗦。

**Comment by horizonzy** [comment]
@KomachiSion @Maijh97 
What do you think of it.

**Comment by KomachiSion** [comment]
现在是可以配置的，只是我们文档还不是很完善

```
JM.LOG.FILE.SIZE      日志文件大小 默认10MB
JM.LOG.RETAIN.COUNT    日志文件保留数量 默认7
```

**Comment by zrlw** [comment]
JM.LOG.RETAIN.COUNT  这个我用过，只是当日最大文件数而已，比如一天生成了1000个日志，只循环留7个，但是有多少天的日志就保存多少天，我这里有台机器保存了3年的日志，每天7个日志，就是这个玩意。

**Comment by KomachiSion** [comment]
那可能需要加一下日期保留

**Comment by brothelul** [comment]
I will follow this feature.

**Comment by brothelul** [comment]
I have completed the development, test in local now.

**Comment by zcz3313** [comment]
> JM.LOG.RETAIN.COUNT 这个我用过，只是当日最大文件数而已，比如一天生成了1000个日志，只循环留7个，但是有多少天的日志就保存多少天，我这里有台机器保存了3年的日志，每天7个日志，就是这个样子：
> <img alt="nacos日志疯长" width="202" src="https://user-images.githubusercontent.com/40652892/104809450-42f1a180-5828-11eb-927f-594e9a4645bb.png">

That's it! We met the same problem.
@brotherlu-xcq When will this feature be merged into release?
