### ISSUE TITLE
请问为何配置文件热加载时，加密项没有解密  encryptor

### ISSUE THREAD

**Issue by huan415** [alibaba/nacos#4640]
![1609979852(1)](https://user-images.githubusercontent.com/37132274/103836766-f807b980-50c4-11eb-9761-cc774b3bbeee.jpg)
我是数据库password用ENC加密，修改配置文件热加载时发现DruidAbstractDataSource.setPassword, 没有解密，请问这个改如何解决

**Comment by horizonzy** [comment]
Please use issue template to describe your problem. I cann't comprehend you said.

**Comment by horizonzy** [comment]
New issue about this situation, so close this.
