### ISSUE TITLE
注册ip地址居然是客户端主动发送而不是nacos被动获取，导致很多新手上来遇到的第一个坑就是这个

### ISSUE THREAD

**Issue by ParkourLiu** [alibaba/nacos#4648]
大佬你好，刚接触nacos第二天，可以说一下，为什么不采取服务端被动获取请求注册者的ip地址吗？客户端主送发送ip地址到nacos，一是需要保证客户端获取本地地址的准确性（目前大概率获取到内网地址，除非配置网段），二是容易有欺骗性，比如请求注册者把注册ip地址指向不明地址，不明地址可保存用户请求信息，再代理回正确地址。。岂不是容易造成数据泄露？

**Comment by KomachiSion** [comment]
> 为什么不采取服务端被动获取请求注册者的ip地址吗

如果服务端客户端中间挂了代理或者SLB，有可能服务端获得的IP不是真实IP。

> 客户端主送发送ip地址到nacos，一是需要保证客户端获取本地地址的准确性（目前大概率获取到内网地址，除非配置网段），二是容易有欺骗性，比如请求注册者把注册ip地址指向不明地址，不明地址可保存用户请求信息，再代理回正确地址。。岂不是容易造成数据泄露？

客户端获取和自行获取再传递区别在于，用户可以控制多网卡地址内容。并且可以有代注册能力。是的nacos客户端更加灵活。
至于你所说的注册者把ip指向不明地址的问题，就算是主动获取地址，其他人也可以在一个其他地址注册，然后再代理回正确地址，这个应该是鉴权或者网络进行保护是事情。
