### ISSUE TITLE
nacos 集群版本一直刷新心跳和获取实例

### ISSUE THREAD

**Issue by Reminisd** [alibaba/nacos#4653]
nacos版本：1.4.0
dubbo:2.7.8
nacos的服务器访问一直打印心跳和获取实例列表的接口，访问量很多
![image](https://user-images.githubusercontent.com/39513283/103982362-52d10c00-51be-11eb-8b39-1497ba4dcbee.png)

**Comment by wangdejian163** [comment]
我的和你洽洽相反，我的是单机版的，一直打印心跳和获取实例列表的接口。nacos版本1.3.2.集群的正常。

**Comment by KomachiSion** [comment]
正常的，有注册的服务和实例 就会有心跳接口的调用
有服务的订阅者，就会有实例列表的接口调用。

如果不想打开accesslog，在`conf/application.properties`关掉accesslog`server.tomcat.accesslog.enabled=false`

**Comment by Reminisd** [comment]
> 正常的，有注册的服务和实例 就会有心跳接口的调用
> 有服务的订阅者，就会有实例列表的接口调用。
> 
> 如果不想打开accesslog，在`conf/application.properties`关掉accesslog`server.tomcat.accesslog.enabled=false`

谢谢解答 发送和检测频率有配置可以修改么

**Comment by horizonzy** [comment]
可以通过对实例的元数据设置`preserved.heart.beat.interval`来修改客户端上报心跳的间隔。值的单位为毫秒。
