### ISSUE TITLE
数据库连接变化不会自动更新连接？

### ISSUE THREAD

**Issue by zlygit** [alibaba/nacos#4655]
请教
本地window NACOS1.3.1版本
 我的nacos设置用户权限后 貌似没用 比如一个用户只设置了 读取权限 还是可以添加 删除  这样是否正常？
 想知道是不是本身就是这样的 还是我自己测试有问题

**Comment by horizonzy** [comment]
在服务端是否进行配置`nacos.core.auth.enabled=true`

**Comment by zlygit** [comment]
好的 我试试 这里我时没有配置的 我试试 估计时我自己的操作错误 多谢指教
