### ISSUE TITLE
Nacos集群的问题，3个节点，关闭一个节点，整个集群服务异常

### ISSUE THREAD

**Issue by mysunstar** [alibaba/nacos#4657]
我是采用Docker进行部署Nacos集群（Nginx+Nacos）。

Nacos的配置：
![image](https://user-images.githubusercontent.com/49060607/104084868-2254a500-5286-11eb-8185-73ab21b60b61.png)

Nginx配置：
image.png
![image](https://user-images.githubusercontent.com/49060607/104084877-2d0f3a00-5286-11eb-9aa5-ba2189948873.png)

重现部署：
1、 关闭一个节点：10.0.7.4:8849
2、错误日志截图
1）应用服务器的客户端错误日志：
image.png
![image](https://user-images.githubusercontent.com/49060607/104084883-37313880-5286-11eb-8673-298390280c64.png)

2）Nacos服务器错误日志：
image.png
![image](https://user-images.githubusercontent.com/49060607/104084887-3d271980-5286-11eb-9ebc-9120cbe3861d.png)

3）Nacos客户端错误截图：
image.png
![image](https://user-images.githubusercontent.com/49060607/104084891-4617eb00-5286-11eb-9f4e-42065f81e90a.png)

我关闭一个节点就导致整个集群服务异常，感觉做了一个伪集群。请问这是什么问题呢？

**Comment by horizonzy** [comment]
我从你们现象上看起来有相关报错日志是正常的。关闭一个节点导致整个集群服务异常的依据目前从提供的信息无法看出。

* 服务端的日志报错是因为有一个节点挂掉了，同步实例数据到那个下掉的节点connection refused也是正常的。
* 在客户端的日志来看，因为你用了nginx代理，在客户端配置的应该是nginx的地址。客户端在上报实例的心跳数据时，请求到nginx,nginx可能把请求转发到了那台已经挂掉的节点上面了，导致客户端上报心跳请求失败。
* 控制台对节点进行上下线时，下线请求通过nginx代理进行转发，可能转发到已下线的节点，导致下线节点失败。

建议在对节点进行下线之后，修改nginx的代理策略，把已经下线的节点从nginx代理策略中移除掉。再看客户端和控制台的相关操作。

**Comment by KomachiSion** [comment]
1. 看一下集群管理里面这个节点的状态
2. 控制台可以多次刷新和尝试，看下是不是稳定复现
3. 看下nginx的日志，确认是否摘除已经关闭的nacos，以及确认是否转发给了下线的nignx
4. 绕过nigix直接给nacos集群发请求试试，如果可以正常请求说明一定是nigix的问题

**Comment by mysunstar** [comment]
@KomachiSion 
1、关闭后的集群状态：
![image](https://user-images.githubusercontent.com/49060607/104151111-04955600-53d4-11eb-8323-a9f11609ccd2.png)
2、在Nginx配置剔除了该节点。还是可以控制台我直接通过访问另外一个节点操作的，不通过Nginx，还是会存在java.net.ConnectException: Connection refused (Connection refused)。发现有的服务可以下线，有的服务不可以下线。
3、我已经在Nginx配置剔除了该节点，还是心跳发送失败。

另外我发现有的服务发送给nacos服务器的心跳是正常的，并且在控制台也可以操作下线。有的服务心跳是失败的，并且在控制台操作也是失败的。当我把关闭的节点重新启动后，服务都恢复正常了。

**Comment by KomachiSion** [comment]
升级一下版本试试， 1.3.0好像有服务列表不更新的问题。 升级到1.3.2或者1.4.0试试。

**Comment by mysunstar** [comment]
@KomachiSion 我升级了1.4.0，问题解决了。感谢。
