### ISSUE TITLE
开启权限后 只有nacos 账号可以注册服务

### ISSUE THREAD

**Issue by zlygit** [alibaba/nacos#4658]
nacos-client 1.2.0 版本
开启权限后 使用nacos账号可以注册服务 其他用户设置了读写权限后 报错 求指教
如下 readAndWrite用户拥有public 读写权限 注册就会报错 （nacos 正常）
另外 readAndWrite11用户拥有namespaceId的读写权限  就可以再namespaceId中注册服务了
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sat Jan 09 16:31:19 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:490) ~[nacos-client-1.2.0.jar:na]

相关配置：
<spring.cloud.version>Hoxton.SR8</spring.cloud.version>
        <spring.cloud.alibaba.version>2.2.3.RELEASE</spring.cloud.alibaba.version>
        <alibaba-nacos-discovery>2.2.3.RELEASE</alibaba-nacos-discovery>
spring:
  cloud:
    nacos:
      discovery:
        username: readAndWrite
        password: readAndWrite
        server-addr: 127.0.0.1:8848
        #namespace: namespaceId
        enabled: true
      config:
        username: readAndWrite
        password: readAndWrite
        server-addr: 127.0.0.1:8848
        #namespace: namespaceId
        enabled: true
  application:
    name: demo8889
server:
  port: 8899
  servlet:
    context-path: /nacos

**Comment by horizonzy** [comment]
权限设置在对应的namespace下了吗。还有确认一下你的sca配置关于namespaceId的设置，需要和控制台中的id保持一致。

**Comment by zlygit** [comment]
好的 我试试 非常感谢回答

**Comment by KomachiSion** [comment]
No response from author, so we think the problem has been solved.

**Comment by 564907422** [comment]
这个问题怎么解决的

**Comment by PRANRAVEE** [comment]
ในวันที่ ศ. 24 ก.พ. 2023 10:56 564907422 ***@***.***>
เขียนว่า:

**Comment by PRANRAVEE** [comment]
ในวันที่ จ. 27 ก.พ. 2023 10:45 PRANRAVEE SEEHAKUM SEEHAKUM <
***@***.***> เขียนว่า:
