### ISSUE TITLE
Mac M1无法使用

### ISSUE THREAD

**Issue by JiangWenJie** [alibaba/nacos#4660]
start.output输出如下：
The start.out output is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/jiangwenjie/Desktop/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/jiangwenjie/Desktop/nacos/plugins/health,/Users/jiangwenjie/Desktop/nacos/plugins/cmdb -Dnacos.home=/Users/jiangwenjie/Desktop/nacos -jar /Users/jiangwenjie/Desktop/nacos/target/nacos-server.jar  --spring.config.location=file:/Users/jiangwenjie/Desktop/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/Users/jiangwenjie/Desktop/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nohup: /Library/Internet: No such file or directory

**Comment by horizonzy** [comment]
see https://github.com/alibaba/nacos/issues/4227

**Comment by EslSuwen** [comment]
> start.output输出如下：
> The start.out output is:
> /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/jiangwenjie/Desktop/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/jiangwenjie/Desktop/nacos/plugins/health,/Users/jiangwenjie/Desktop/nacos/plugins/cmdb -Dnacos.home=/Users/jiangwenjie/Desktop/nacos -jar /Users/jiangwenjie/Desktop/nacos/target/nacos-server.jar --spring.config.location=file:/Users/jiangwenjie/Desktop/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/Users/jiangwenjie/Desktop/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
> nohup: /Library/Internet: No such file or directory

老哥你能用了吗？

**Comment by JiangWenJie** [comment]
> > start.output输出如下：
> > The start.out output is:
> > /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/jiangwenjie/Desktop/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/jiangwenjie/Desktop/nacos/plugins/health,/Users/jiangwenjie/Desktop/nacos/plugins/cmdb -Dnacos.home=/Users/jiangwenjie/Desktop/nacos -jar /Users/jiangwenjie/Desktop/nacos/target/nacos-server.jar --spring.config.location=file:/Users/jiangwenjie/Desktop/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/Users/jiangwenjie/Desktop/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
> > nohup: /Library/Internet: No such file or directory
> 
> 老哥你能用了吗？

> 已解决，由于macOS jdk路径的问题引起的，使用 `/usr/libexec/java_home -V`查看你的jdk路径，发现有空格，重新配置你电脑的环境变量即可

**Comment by Langze6** [comment]
> > > start.output输出如下：
> > > The start.out output is:
> > > /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/jre/lib/ext:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/ext -Xloggc:/Users/jiangwenjie/Desktop/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/jiangwenjie/Desktop/nacos/plugins/health,/Users/jiangwenjie/Desktop/nacos/plugins/cmdb -Dnacos.home=/Users/jiangwenjie/Desktop/nacos -jar /Users/jiangwenjie/Desktop/nacos/target/nacos-server.jar --spring.config.location=file:/Users/jiangwenjie/Desktop/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/Users/jiangwenjie/Desktop/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
> > > nohup: /Library/Internet: No such file or directory
> > 
> > 
> > 老哥你能用了吗？
> 
> > 已解决，由于macOS jdk路径的问题引起的，使用 `/usr/libexec/java_home -V`查看你的jdk路径，发现有空格，重新配置你电脑的环境变量即可

我也有同样的问题，我的jdk环境变量没有空格“/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin”我的机器是MacbookPro M1
