### ISSUE TITLE
accessToken为什么headers里面传了，url里面还要传？

### ISSUE THREAD

**Issue by 985391294** [alibaba/nacos#4668]
![nacos](https://user-images.githubusercontent.com/57293296/104166718-2de6ce00-5436-11eb-8fc0-eac1576a438b.png)
想了解一下为什么两个地方都传呢？

**Comment by KomachiSion** [comment]
因为header里是的Authorization是给前端用的，而且是对象格式，不能直接使用，要解析。url才是服务端正在获取参数的地方。

**Comment by minbigtree** [comment]
header 里面用Authorization会跟nginx开启HTTP Basic Authentication冲突

**Comment by KomachiSion** [comment]
应该是会的，因为不同的鉴权标准用了同一个字段，冲突是正常的。
