### ISSUE TITLE
请确认逻辑是否合理，在使用nacos-client时，nacos-client PayloadRegistry 类在scan时，在找com.alibaba.nacos.naming.cluster.remote.response ，这个在nacos-naming包中，如果找不到报java.lang.ExceptionInInitializerError: null 异常，

### ISSUE THREAD

**Issue by bxvs888** [alibaba/nacos#4671]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version Nacos:2.0.0-ALPHA.1
 - Module naming/config
 

**Additional context**
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/298322/104254320-87d8a980-54b1-11eb-95de-8b4bd3698ea6.png">

**Comment by KomachiSion** [comment]
1. 这里设计的确不太合理，后期会优化掉
2. 我们测试使用的时候，没有出现过异常，能详细提供异常位置和影响吗？ 应该找不到也不影响使用才对。

**Comment by bxvs888** [comment]
@KomachiSion
> * 这里设计的确不太合理，后期会优化掉
> * 我们测试使用的时候，没有出现过异常，能详细提供异常位置和影响吗？ 应该找不到也不影响使用才对。
![image](https://user-images.githubusercontent.com/298322/104275129-3c3bf500-54dd-11eb-985e-2bd0cb2d7b25.png)
报错位置。
![image](https://user-images.githubusercontent.com/298322/104275180-4d850180-54dd-11eb-88a2-4a65d1e9db0c.png)

导致结果。
![image](https://user-images.githubusercontent.com/298322/104275271-6f7e8400-54dd-11eb-8d9d-34f65c1104a5.png)

**Comment by KomachiSion** [comment]
我的确没有复现你的问题，能提供你的demo工程到github吗？

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/104312982-5643fa80-5512-11eb-97e3-068010603cdb.png)

**Comment by chuntaojun** [comment]
PayloadRegistry 或许可以考虑主动注册需要扫描的packages路径，在调用scan方法
