### ISSUE TITLE
When importing or cloning configuration, the old configuration item description is lost

### ISSUE THREAD

**Issue by apple987** [alibaba/nacos#4672]
My version is 1.4.0. When I clone or import, the old configuration item remarks will be lost

**Comment by KeRan213539** [comment]
Is the old configuration missing or the cloned one?
There is no clone remarks when cloning, this will be fixed later.
Import is not supported for some special reasons. However, there will be a new version of export later, which will be implemented in the new version of export

**Comment by haoyann** [comment]
Can I fix the cloning no description?

**Comment by KeRan213539** [comment]
> Can I fix the cloning no description?

of course you can
