### ISSUE TITLE
nacos config client 在springboot/springcloud 环境中能不能支持全部配置在 nacos中？

### ISSUE THREAD

**Issue by childewuque** [alibaba/nacos#4673]
当没有nacos的时候，我们配置在application.yml中
当现在有nacos之后，我们希望本地除了nacos地址，全部配置属性都在nacos，本地不进行配置

当然，目前版本，可以通过本地 application.yml 中这样配置来进行,是不是可以省掉这一步,在项目里直接使用呢？：
server:
  port: "@server.port@"
biz:
   prop: "@biz.prop@"

**Comment by KeRan213539** [comment]
可以把除了 nacos 配制外的其他配制放到nacos中

**Comment by childewuque** [comment]
> 可以把除了 nacos 配制外的其他配制放到nacos中

不用application.yml里再引用一遍吗？ 我试试

**Comment by KeRan213539** [comment]
> > 可以把除了 nacos 配制外的其他配制放到nacos中
> 
> 不用application.yml里再引用一遍吗？ 我试试

不用的,如果你用 nacos spring boot starter 或者 spring cloud alibaba 的话, 这些配制会被放到 spring 的 env 里,可以通过spring的方式取出

**Comment by childewuque** [comment]
> > > 可以把除了 nacos 配制外的其他配制放到nacos中
> > 
> > 
> > 不用application.yml里再引用一遍吗？ 我试试
> 
> 不用的,如果你用 nacos spring boot starter 或者 spring cloud alibaba 的话, 这些配制会被放到 spring 的 env 里,可以通过spring的方式取出

嗯，免本地配置成功，感谢
我用的  <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>

**Comment by KeRan213539** [comment]
> > > > 可以把除了 nacos 配制外的其他配制放到nacos中
> > > 
> > > 
> > > 不用application.yml里再引用一遍吗？ 我试试
> > 
> > 
> > 不用的,如果你用 nacos spring boot starter 或者 spring cloud alibaba 的话, 这些配制会被放到 spring 的 env 里,可以通过spring的方式取出
> 
> 嗯，免本地配置成功，感谢
> 我用的 spring-cloud-starter-alibaba-nacos-config

客气,那这个issue我关闭了哈.不知道你有没有加钉钉群,没的话可以加一下, 群号: 30438813
