### ISSUE TITLE
nacos整合gateway

### ISSUE THREAD

**Issue by wzh900521** [alibaba/nacos#4674]
版本：springCloudAlibaba2.2.3   &   SpringCloudGateway2020.0.0

网关工程无法启动。不知道有人碰到过这个问题，启动即报错

Description:

Parameter 0 of method loadBalancerWebClientBuilderBeanPostProcessor in org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration required a bean of type 'org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction' in your configuration.

**Comment by horizonzy** [comment]
错误信息已经提示你了。
需要IOC容器中注入`DeferringLoadBalancerExchangeFilterFunction `这个bean，请确认一下这个bean是如何配置的。

**Comment by KeRan213539** [comment]
2020 改动较大,SCA还不支持. 并且这个问题应该提到 SCA那边...

**Comment by 17600904730** [comment]
添加依赖
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

**Comment by BEATREE** [comment]
mark

**Comment by fortunearterial** [comment]
mark
