### ISSUE TITLE
Dirty clientBeatCheckTask still running after service be removed. Cause The service cannot be registered properly.

### ISSUE THREAD

**Issue by MrGGGGGG** [alibaba/nacos#4676]
**Describe the bug**
There is a chance that ClientBeatCheckTask will run even after the Serivce object has been removed, resulting in subsequent registered services being removed because the lastBeatTime of instance in the dirty ClientBeatCheckTask has exceeded the time limit.

**Expected behavior**
When the service stops, the corresponding clientBeatCheckTask also stops.later,new registration of the service can run 

**Acutally behavior**
When the last instance stops,later service removed, the corresponding clientBeatCheckTask still running. cause that the new  registration of the service will be removed.

**How to Reproduce**
It happened by accident. Nacos Server has been running in our development environment for quite some time. One day suddenly found the instance dropped line every 5 seconds.

**Desktop (please complete the following information):**
 - OS: Centos
 - Version: nacos-server 1.3.2 ,nacos-client 1.3.2
 - Module: naming
 - SDK: spring-cloud-alibaba-nacos,spring boot 2.3.3.RELEASE,spring cloud Hoxton.SR8

**Additional context**
I checked the source code of nacos.  and also used the arthas to troubleshoot problems.
i stoped all services,and used the "watch command" of arthas to find which clientBeatCheckTask was still running.
here are the cmd result:

```shell
[arthas@50]$ watch com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask deleteIp '{params, returnObj, throwExp}' -x 3
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 100 ms, listenerId: 34
method=com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.deleteIp location=AtExit
ts=2021-01-12 10:13:19; [cost=1.7654ms] result=@ArrayList[
    @Object[][
        @Instance[
            MAX_WEIGHT_VALUE=@Double[10000.0],
            MIN_POSITIVE_WEIGHT_VALUE=@Double[0.01],
            MIN_WEIGHT_VALUE=@Double[0.0],
            lastBeat=@Long[1609759692421],
            mockValid=@Boolean[false],
            marked=@Boolean[false],
            tenant=null,
            app=@String[unknown],
            IP_PATTERN=@Pattern[(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):?(\d{1,5})?],
            ONLY_DIGIT_AND_DOT=@Pattern[(\d|\.)+],
            SPLITER=@String[_],
            instanceId=@String[192.168.1.230#9000#DEFAULT#DEV@@**-**-service],
            ip=@String[192.168.1.230],
            port=@Integer[9000],
            weight=@Double[1.0],
            healthy=@Boolean[false],
            enabled=@Boolean[true],
            ephemeral=@Boolean[true],
            clusterName=@String[DEFAULT],
            serviceName=@String[DEV@@**-**-service],
            metadata=@LinkedHashMap[isEmpty=false;size=1],
        ],
    ],
    null,
    null,
]
```
look at the timestamp. I run this command at '2021-01-12 10:13:19'.but the lastBeat timestamp in the instance was '1609759692421', it is '2021-01-04 19:28:12'. that is the dirty instance in clientBeatCheckTask .
`com.alibaba.nacos.naming.healthcheck.HealthCheckReactor#cancelCheck`
i guess this method maybe the reason. it does nothing when a exception occurs,just log.

**Comment by KomachiSion** [comment]
Fixed in 1.4.0. Please use newest version and retry.

**Comment by KomachiSion** [comment]
Maybe duplicate with https://github.com/alibaba/nacos/issues/3781

**Comment by MrGGGGGG** [comment]
Sorry for not checking the new release log.It does address this issue in version 1.4.0.
