### ISSUE TITLE
实例销毁后 nacos 的控制台依然能看到服务

### ISSUE THREAD

**Issue by shijianwei** [alibaba/nacos#4678]
nacos 版本1.4  集群部署
k8s 集群

重新部署后 nacos 控制台依然可以看到已经销毁的实例
每个实例的健康状态还一直在变化

**Comment by KomachiSion** [comment]
麻烦使用issue模版进行问题描述，并补充足够的信息，比如服务端日志 客户端日志，确认心跳是否还在发送等。

**Comment by KomachiSion** [comment]
Any process?
