### ISSUE TITLE
nacos 作为配置中心，配置在远程ip，但是 还有localhost:8848的请求日志

### ISSUE THREAD

**Issue by childewuque** [alibaba/nacos#4680]
不知道是否正常？是默认的？

环境：
spring cloud Hoxton.SR9  
spring boot 2.3.6.RELEASE
spring-cloud-starter-alibaba-nacos-config  2.2.3.RELEASE

配置：
spring:
  profiles: test
  cloud:
    nacos:
      config:
        server-addr: 172.19.60.202:30048

日志：

ts=2021-01-13 11:18:31.968  app=biz-gateway th=[boundedElastic-1] lv=DEBUG class=c.a.n.c.naming msg=HTTP method: GET, url: http://localhost:8848/nacos/v1/ns/service/list?app=unknown&pageSize=2147483647&groupName=DEFAULT_GROUP&namespaceId=public&pageNo=1, body: {}
ts=2021-01-13 11:18:31.981  app=biz-gateway th=[Nacos-Watch-Task-Scheduler-1] lv=DEBUG class=c.a.n.c.c.i.ConfigHttpClientManager msg=HTTP method: GET, url: http://172.19.60.202:30048/nacos/v1/cs/configs?dataId=biz-gateway-dynamicroute&group=biz, body: null

**Comment by horizonzy** [comment]
pls also config `spring.cloud.nacos.discovery.server-addr`: 172.19.60.202:30048 in your application

**Comment by childewuque** [comment]
> pls also config `spring.cloud.nacos.discovery.server-addr`: 172.19.60.202:30048 in your application

确实，因为以前是nacos作注册发现的，现在用kubernetes的注册发现了，把nacos discovery 依赖删了就没事了
