### ISSUE TITLE
2.0.0-ALPHA.1 ConfigQueryRequestHandler.readFileContent miss line char. 读配置丢失换行符

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#4681]
**Describe the bug**
ConfigQueryRequestHandler.readFileContent miss line char.
读配置丢失换行符

**Expected behavior**
Restore the original configuration content.
还原为原本的配置，直接 read 字节后转成字符串为最佳？

**Acutally behavior**
The newline character is lost, and the configuration content is inconsistent with the server after it is returned to the client MD5.
丢失换行符，配置内容返回客户端 md5 后与服务端不一致。

**Additional context**
That's what I'm dealing with right now.
暂时如此处理，但内容该是返璞归真。

config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
```java
public static String readFileContent(File file) {

        StringBuilder sb = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {

            String tempStr;
            while ((tempStr = reader.readLine()) != null) {
                // FIXME readLine lose '\n', It may not be restored because the content is inconsistent. The MD5 value of the client is different from that of the server
                sb.append(tempStr).append('\n');
            }
            sb.setLength(sb.length() - 1);

            return sb.toString();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return sb.toString();
    }
```

**Comment by CherishCai** [comment]
`org.apache.commons.io.FileUtils.readFileToString(file);`

**Comment by shiyiyue1102** [comment]
> **Describe the bug**
> ConfigQueryRequestHandler.readFileContent miss line char.
> 读配置丢失换行符
> 
> **Expected behavior**
> Restore the original configuration content.
> 还原为原本的配置，直接 read 字节后转成字符串为最佳？
> 
> **Acutally behavior**
> The newline character is lost, and the configuration content is inconsistent with the server after it is returned to the client MD5.
> 丢失换行符，配置内容返回客户端 md5 后与服务端不一致。
> 
> **Additional context**
> That's what I'm dealing with right now.
> 暂时如此处理，但内容该是返璞归真。
> 
> config/src/main/java/com/alibaba/nacos/config/server/remote/ConfigQueryRequestHandler.java
> 
> ```java
> public static String readFileContent(File file) {
> 
>         StringBuilder sb = new StringBuilder();
>         try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
> 
>             String tempStr;
>             while ((tempStr = reader.readLine()) != null) {
>                 // FIXME readLine lose '\n', It may not be restored because the content is inconsistent. The MD5 value of the client is different from that of the server
>                 sb.append(tempStr).append('\n');
>             }
>             sb.setLength(sb.length() - 1);
> 
>             return sb.toString();
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>         return sb.toString();
>     }
> ```

OK，I have reproduce this bug local ,thank you very much to report this bug.

**Comment by CherishCai** [comment]
![image](https://user-images.githubusercontent.com/16837364/105036653-bcdb9200-5a97-11eb-8f82-2d31ba1e0551.png)

![image](https://user-images.githubusercontent.com/16837364/105036695-cebd3500-5a97-11eb-9819-19e5a9a2a96b.png)
