### ISSUE TITLE
同一个消费者订阅多个生产者如何动态选择生产者服务

### ISSUE THREAD

**Issue by cloudZwj** [alibaba/nacos#4693]
在我的应用场景中，不同的生产者提供dubbo服务注册到一个nacos上并用namespace隔离，请问同一个消费者该如何做到同时订阅这些生产者提供的服务并且能够动态地选择指定生产者的服务

**Comment by KomachiSion** [comment]
这个问题超出了nacos的能力范围。nacos只负责推送当前namespace下面该服务的列表是哪些。至于怎么使用这些信息是RPC框架或用户自己决定的事情。

至于不同的namespace下的提供者，同一个消费者是只能通过多nacos客户端（每个客户端监听一个namespace实现），因为namespace是强隔离。
