### ISSUE TITLE
服务器不可达，服务无法下线，但是状态还是健康状态

### ISSUE THREAD

**Issue by gundam26** [alibaba/nacos#4702]
**Describe the bug**
nacos服务端版本1.4
nacos集群模式，服务器shutdown之后有个别在该服务器的服务在nacos中显示健康状态，并且无法强制下线
![image](https://user-images.githubusercontent.com/24378066/104577591-a21ead00-5694-11eb-8808-5f4831d4d6b7.png)
![image](https://user-images.githubusercontent.com/24378066/104577670-b5317d00-5694-11eb-8754-ac955345bf24.png)
![image](https://user-images.githubusercontent.com/24378066/104577687-bbbff480-5694-11eb-83b9-3b2ef48da9bc.png)
![image](https://user-images.githubusercontent.com/24378066/104577721-c5495c80-5694-11eb-9fc7-fea4dd1f6c45.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
duplicate with #4364. Fixed in 1.4.1
