### ISSUE TITLE
nacos cluster mode cannot elect new leader when leader is down

### ISSUE THREAD

**Issue by starskys** [alibaba/nacos#4705]
## Issue Description
bug report

### Describe what happened (or what feature you want)
I was using nacos cluster mode under windows10 enviroment, sibling nodes cannot elect new leader when leader is down,
here is my cluster.config:
#2021-01-14T23:24:01.948
172.16.0.167:8848
172.16.0.167:9000
172.16.0.167:9001
172.16.0.167:9002

### Tell us your environment
win10 standalone ,nacos 1.4.0

### Anything else we need to know?
normal status 
![normal status](https://user-images.githubusercontent.com/16967111/104686624-8cfb5a00-5738-11eb-9887-16925896023a.jpg)
abnormal status, no new leader elected after a long while
![abnormal status, no new leader elected](https://user-images.githubusercontent.com/16967111/104687860-f67c6800-573a-11eb-9fb1-397be5240eb1.jpg)

nacos-cluster.log
![nacos-cluster.log](https://user-images.githubusercontent.com/16967111/104687986-317e9b80-573b-11eb-8abe-93a26a59b4e2.png)

**Comment by KomachiSion** [comment]
Please answer some question:

1. Did you start the all four nodes ok?
2. What's the error info for elect new leader?

**Comment by starskys** [comment]
> Please answer some question:
> 
> 1. Did you start the all four nodes ok?
> 2. What's the error info for elect new leader?

Hi, I've  updated my question

**Comment by KomachiSion** [comment]
There are some upgrade for nacos in 1.4.0. Nacos 1.4.0 use jraft to replace old self-implement raft.

You provide information is old raft information. When the whole nacos cluster upgrade to up 1.4.0, the old raft system will been close and use jraft. The old raft information will not use and not update.

In 1.4.1, we enhance it, After the raft switch to jraft, the old raft information will be removed.

So I recommend that you upgrade to 1.4.1.
