### ISSUE TITLE
UI can't use in 1.4.1

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#4709]
**Describe the bug**

In 1.4.1 we interceptor all un register API. But the ui request with .html is not register so that UI console can't use.
So revert the interceptor all un register API behavior, only save the '/' support.

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by JamesLiAndroid** [comment]
Same as me, maybe can use at few minites.When I import config files, the UI can't refresh anymore. So how to resolve?

**Comment by KomachiSion** [comment]
Fix by #4708 . And Has update in https://github.com/alibaba/nacos/releases/tag/1.4.1 . Please downloan the newest package and upgrade.
