### ISSUE TITLE
新注册的服务getway客户端获取不到新服务

### ISSUE THREAD

**Issue by zhujunjieit** [alibaba/nacos#4710]
## Issue Description

如果先启动路由getway客户端，在启动具体的业务服务注册到nacos。服务正常注册到nacos;但是客户端getway没有获取到nacos的服务。
总结为：在getway启动后。新注册的服务必须重启客户端才能获取完整的服务列表

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
出现问题的情况下，麻烦看一下getway客户端的${user.home}/logs/nacos/naming.log
是不是收到了服务的新服务列表推送

如果收到了 那就是gateway的问题。
如果没收到，麻烦提供客户端日志和服务端日志。

**Comment by zhujunjieit** [comment]
getway客户端没有收到新服务推送。这个是明确的！
获取不到服务的情况如下：只有在第一个启动getway服务的，或者说getway客户端启动后在启动的新服务，新服务没有在nacos注册过的情况下；新启动的服务在nocas注册成功，界面能看到。这种情况是必然出现的
可以获取推送的情况如下：1、先启动其他服务，2、然后启动getway；getway会获取最新的服务列表；这时没有问题；
3、然后关闭其他服务；getway也会收到关闭其他服务的推送。然后重启其他服务，也会收到推送的服务通知。

**Comment by zhujunjieit** [comment]
> 出现问题的情况下，麻烦看一下getway客户端的${user.home}/logs/nacos/naming.log
> 是不是收到了服务的新服务列表推送
> 
> 如果收到了 那就是gateway的问题。
> 如果没收到，麻烦提供客户端日志和服务端日志。

getway客户端没有收到新服务推送。这个是明确的！
获取不到服务的情况如下：只有在第一个启动getway服务的，或者说getway客户端启动后在启动的新服务，新服务没有在nacos注册过的情况下；新启动的服务在nocas注册成功，界面能看到。这种情况是必然出现的
可以获取推送的情况如下：1、先启动其他服务，2、然后启动getway；getway会获取最新的服务列表；这时没有问题；
3、然后关闭其他服务；getway也会收到关闭其他服务的推送。然后重启其他服务，也会收到推送的服务通知。

**Comment by KomachiSion** [comment]
那还是gateway的问题， gateway只去订阅了启动时有的服务， 后来新加的服务不去订阅。肯定就收不到新服务内容。

**Comment by zhujunjieit** [comment]
> 那还是gateway的问题， gateway只去订阅了启动时有的服务， 后来新加的服务不去订阅。肯定就收不到新服务内容。

怎么处理

**Comment by KomachiSion** [comment]
gateway是你自己写的吗，是的话就自行查询nacos上的服务列表，订阅新出现的服务

如果不是自己写的就问gateway那边的社区。
