### ISSUE TITLE
nacos控制台退出登录，accessToken不会失效，而且，即使不带token也有办法直接请求到nacos后端接口，如图

### ISSUE THREAD

**Issue by dzh6699** [alibaba/nacos#4714]
![image](https://user-images.githubusercontent.com/29142176/104696219-e2d7fe00-5748-11eb-9702-417c566a7e8b.png)

**Comment by dzh6699** [comment]
加任意字符就可调用到后端接口

**Comment by KomachiSion** [comment]
有开启鉴权吗？

**Comment by dzh6699** [comment]
开启了


周杰伦说
wisdom.web@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 晚上6:45
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"远古程序猿"<102252122@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos控制台退出登录，accessToken不会失效，而且，即使不带token也有办法直接请求到nacos后端接口，如图 (#4714)





 
有开启鉴权吗？

**Comment by dzh6699** [comment]
请问一下您的nacos是什么版本

**Comment by KomachiSion** [comment]
1.4.1

**Comment by dzh6699** [comment]
我升级一下版本再试试，不过1.4.1的tag源码，consistency模块下com/alibaba/nacos/consistency的entity文件夹缺失，下载下来无法编译


周杰伦说
wisdom.web@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 上午9:11
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"远古程序猿"<102252122@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos控制台退出登录，accessToken不会失效，而且，即使不带token也有办法直接请求到nacos后端接口，如图 (#4714)





 
1.4.1 最新版本

**Comment by wangweizZZ** [comment]
> 我升级一下版本再试试，不过1.4.1的tag源码，consistency模块下com/alibaba/nacos/consistency的entity文件夹缺失，下载下来无法编译

这个目录的entity 文件是 `mvn compile` 根据proto文件自动生成的

**Comment by dzh6699** [comment]
明白了，谢谢




周杰伦说
wisdom.web@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 上午9:56
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"远古程序猿"<102252122@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos控制台退出登录，accessToken不会失效，而且，即使不带token也有办法直接请求到nacos后端接口，如图 (#4714)





  
我升级一下版本再试试，不过1.4.1的tag源码，consistency模块下com/alibaba/nacos/consistency的entity文件夹缺失，下载下来无法编译
  
这个目录的entity 文件是 mvn compile 根据proto文件自动生成的

**Comment by dzh6699** [comment]
这个问题OK了，不过token在用户退出登陆后不会失效

**Comment by dzh6699** [comment]
明白了，谢谢


周杰伦说
wisdom.web@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月19日(星期二) 晚上7:22
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"远古程序猿"<102252122@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos控制台退出登录，accessToken不会失效，而且，即使不带token也有办法直接请求到nacos后端接口，如图 (#4714)





 
登出和token是分开的，登出只是从web页面退出了，token里带有有效时间，只要还在有效时间内应该token都是有效的。
