### ISSUE TITLE
yaml format  \ not support

### ISSUE THREAD

**Issue by wangjia2016** [alibaba/nacos#4716]
**Describe the bug**
yaml format \ not support

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

![image](https://user-images.githubusercontent.com/16084076/104702030-66491d80-5750-11eb-854b-164f9fdc81d1.png)
![image](https://user-images.githubusercontent.com/16084076/104702094-795bed80-5750-11eb-908b-34a55d7c108e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Maybe the ui plugin not support, can you try to submit it and check whether it is right?
