### ISSUE TITLE
icon-font.woff2 ,  The file could not be accessed successfully

### ISSUE THREAD

**Issue by Chunghwa-2018** [alibaba/nacos#4717]
**Describe the bug**
Login nacos . An error occurred in the browser console. icon-font.woff2 ,  The file could not be accessed successfully!

**Expected behavior**
in nacos/console program， The file could not be found in the project.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. Go to 'http://ip:port/nacos'
2. Click on 'Google browser console'
3. Click on  'Network'

**Desktop (please complete the following information):**
 - OS: [ MacOS X / Centos]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [e.g. nacos/console]
 
**Additional context**

**Comment by KomachiSion** [comment]
This problem does not affect the use. Whether if anyone in the community is willing to repair？

**Comment by ttttangzhen** [comment]
i will fix it

**Comment by KomachiSion** [comment]
duplicate with #3378
