### ISSUE TITLE
Nacos访问Web页面报错

### ISSUE THREAD

**Issue by waidinsamkeit** [alibaba/nacos#4727]
Unable to process the request at this time: System triggered degradation

![](https://cdn.jsdelivr.net/gh/waidinsamkeit/picture@latest/2021/01/18/bbfb417b635c2fed69c7512c6806bf4d.png)
# nacos错误日志
caused: errCode: 500, errMsg: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The conformance protocol is temporarily unavailable for reading, Invalid state for readIndex: STATE_ERROR. ;
# 启动Nacos内置数据源集群问题
2021-01-18 15:21:12,490 ERROR Event listener exception : {}

**Comment by KomachiSion** [comment]
Any more information or error logs from nacos server?

**Comment by waidinsamkeit** [comment]
> os 服务器获得更多信息或错误日志吗？

I've updated the question

**Comment by KomachiSion** [comment]
Which version?

**Comment by KomachiSion** [comment]
No enough information to reproduce problem and find problem, author also no more response, so close issue first.
