### ISSUE TITLE
nacos 集群模式 kubernate启动 nacos.log   出现错误日志

### ISSUE THREAD

**Issue by tjych** [alibaba/nacos#473]
# 报告错误

版本信息: nacos 0.6.1 
![image](https://user-images.githubusercontent.com/3435617/50053655-cd600680-0173-11e9-85b1-e2a6ef2fe317.png)
![image](https://user-images.githubusercontent.com/3435617/50053659-dd77e600-0173-11e9-8c1c-746a359e1673.png)

**Comment by tjych** [comment]
@nkorange 在启动的时候。

**Comment by nkorange** [comment]
@tjych 这个不影响，启动的时候还没有选举出leader，就会写失败。
