### ISSUE TITLE
nacos-config 和 nacos-console 等可以发布 maven仓库？

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#4734]
https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-common

Server 层也想 使用 Naocs-server 端，在尽可能不变更原本 代码，直接依赖 jar包，使用 bean 覆盖方式去做自我的定制；
但是 nacos-config 和 nacos-console 都不在 mvn 仓库

**Comment by KomachiSion** [comment]
Server部分暂无此计划，目前会当作一个web应用直接在console里打成一个jar包， 如果有直接依赖的需求，建议clone源码然后自行打包。
