### ISSUE TITLE
Nacos 1.4.0 upgrade to 1.4.1, but auth is not available

### ISSUE THREAD

**Issue by peiqianggao** [alibaba/nacos#4735]
**Describe the bug**
Upgrade nacos from 1.4.0 to 1.4.1 with [ReleaseTag1.4.1](https://github.com/alibaba/nacos/releases/tag/1.4.1)
But it's not available on auth

**Expected behavior**
403 Forbidden

**Acutally behavior**
Return the user list including the default `nacos` account

```shell
$ jps -l | grep nacos
11732 /data/nacos_1.4.1/target/nacos-server.jar

$ ls -l /data/nacos_1.4.1/target/nacos-server.jar
-rw-r--r-- 1 dev dev 85519842 1月  15 10:31 /data/nacos_1.4.1/target/nacos-server.jar

$ curl -XGET 'http://127.0.0.1:8848/nacos/v1/auth/users?pageNo=1&pageSize=9'
{"totalCount":2,"pageNumber":1,"pagesAvailable":1,"pageItems":[{"username":"dev_reader","password":"$2..."},{"username":"nacos","password":"$2..."}]}
```

**How to Reproduce**
1. Download and extract the tar.gz package
2. Copy application.properties from 1.4.0 to 1.4.1 conf directory
3. Modify conf by adding auth config
```
nacos.core.auth.enabled=true
nacos.core.auth.enable.userAgentAuthWhite=false
nacos.core.auth.server.identity.key=xxx
nacos.core.auth.server.identity.value=xxxx
```
4. Start nacos 1.4.1 on standalone mode
5. Execute command
```shell
curl -XGET 'http://127.0.0.1:8848/nacos/v1/auth/users?pageNo=1&pageSize=9'
```

**Desktop (please complete the following information):**
 - OS: CentOS 7(el7.x86_64)
 - Version: nacos-server 1.4.1
 - Module: config

**Comment by KomachiSion** [comment]
There are some things changed in `startup.sh`, please not only replace nacos-server.jar. Also replace `bin` dir and retry.

**Comment by peiqianggao** [comment]
Replacing the files in ` bin` dir and it works fine, thanks a lot.
