### ISSUE TITLE
Nacos更换1.4.1版本并配置identity key value 后出现页面404

### ISSUE THREAD

**Issue by qinmou** [alibaba/nacos#4738]
问题如下
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jan 19 09:21:02 CST 2021
There was an unexpected error (type=Not Found, status=404).
Not found mehtod for path GET /nacos/

问题原因：看了下源码，1.4.1版本解决#4701issue后将下图中的method == null 判断处改为了直接返回，而不是1.3版本中判断为空后放行，进而导致nacos控制台页面直接被拦截而出现404问题
// 1.4.1版本
if (method == null) {
                // For #4701, Only support register API.
                resp.sendError(HttpServletResponse.SC_NOT_FOUND,
                        "Not found mehtod for path " + req.getMethod() + " " + req.getRequestURI());
                return;
            }
// 1.3.0版本
if (method == null) {
                chain.doFilter(request, response);
                return;
            }

还有，客户端整合nacos所发送的所有请求也会经过该过滤器，配置了identity key value 后就必须得所有请求都自带所配置key value的请求头吗，

**Comment by KomachiSion** [comment]
Fixed by #4708. 请重新下载最新的1.4.1版本进行更新。

**Comment by KomachiSion** [comment]
> 还有，客户端整合nacos所发送的所有请求也会经过该过滤器，配置了identity key value 后就必须得所有请求都自带所配置key value的请求头吗

客户端不会带，客户端需要走正式的鉴权。
