### ISSUE TITLE
控制台界面的持久服务全部显示是不健康的，界面的服务变成红色的，但服务可以正常访问

### ISSUE THREAD

**Issue by qiupan123** [alibaba/nacos#4739]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
持久化服务是服务端主动去探测的，你设置了他的探测端口了吗？设置使用服务注册的端口探测吗？ 如果都没有设置 默认是80端口探测，如果不是80端口那健康检查肯定是失败的。

**Comment by qiupan123** [comment]
写入持久服务的实例的时候有设置端口，界面服务报红也不是一直的，运行一段时间后，中间有几天突然报红的，后面又自己恢复不爆红，但服务一直都是能正常访问。

**Comment by qiupan123** [comment]
> 持久化服务是服务端主动去探测的，你设置了他的探测端口了吗？设置使用服务注册的端口探测吗？ 如果都没有设置 默认是80端口探测，如果不是80端口那健康检查肯定是失败的。

写入持久服务的实例的时候有设置端口，界面服务报红也不是一直的，运行一段时间后，中间有几天突然报红的，后面又自己恢复不爆红，但服务一直都是能正常访问。

**Comment by KomachiSion** [comment]
健康检查的端口不是写入持久化的时候的端口。可以分开的，在服务详情里集群配置里可以修改端口，或者开启使用实例注册的端口好进行检查。

你说的这个情况可能是你注册的那个ip:80可以通，之后中断了，然后又可以通了。和你所注册的服务不是一个。

**Comment by KomachiSion** [comment]
naming-event.log里也有健康检查的日志，可以check一下

**Comment by qiupan123** [comment]
> naming-event.log里也有健康检查的日志，可以check一下



> 健康检查的端口不是写入持久化的时候的端口。可以分开的，在服务详情里集群配置里可以修改端口，或者开启使用实例注册的端口好进行检查。
> 
> 你说的这个情况可能是你注册的那个ip:80可以通，之后中断了，然后又可以通了。和你所注册的服务不是一个。

> 

> 

> 健康检查的端口不是写入持久化的时候的端口。可以分开的，在服务详情里集群配置里可以修改端口，或者开启使用实例注册的端口好进行检查。
> 
> 你说的这个情况可能是你注册的那个ip:80可以通，之后中断了，然后又可以通了。和你所注册的服务不是一个。

修改端口会报403,看了好像是Bug,在不升级nacos的情况下; 那怎么开启使用实例注册的端口进行健康检查呢

**Comment by KomachiSion** [comment]
使用管理员账号也不可以修改吗？那可能只能关闭鉴权然后修改了。 应该管理员账号就可以修改了。

**Comment by qiupan123** [comment]
> 使用管理员账号也不可以修改吗？那可能只能关闭鉴权然后修改了。 应该管理员账号就可以修改了。

就是使用管理员账号的，版本是1.3.1

**Comment by qiupan123** [comment]
> > 使用管理员账号也不可以修改吗？那可能只能关闭鉴权然后修改了。 应该管理员账号就可以修改了。
> 
> 就是使用管理员账号的，版本是1.3.1

使用默认的nacos账号也报403。

**Comment by KomachiSion** [comment]
那可能需要升级到141了，应该是之前版本的bug
