### ISSUE TITLE
nacos1.2.1开启权限校验后 sentinel 1.7.1 拉取不到nacos配置中的文件  鉴权失败 :403

### ISSUE THREAD

**Issue by zhangluyang1995** [alibaba/nacos#4740]
异常描述 : 

服务启动后狂刷错误信息 : [check-update] get changed dataId error, code: 403 

nacos错误信息:  
 - - [19/Jan/2021:09:55:23 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.1" 403 299 2 Java/1.8.0_202
127.0.0.1 - - [19/Jan/2021:09:55:23 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.1" 403 299 2 

不清楚是如何使用sentinel配置进行与nacos认证的.

sentinel 配置 : 
    sentinel:
      transport:
        dashboard: sentinel-client
      eager: true
      datasource:
        ds:
          nacos:
            serverAddr: nacos-server
            namespace: dev
            # access-key: 不知道生成规则,故未配置
            # usesrname: datasource-nacos 未存在对应属性
            # password: datasource-nacos 未存在对应属性
            groupId: DEFAULT_GROUP
            dataId: sentinel.json
            data-type: json
            rule-type: gw-flow 

若想使用此功能该如何配置sentinel 达到 nacos权限认证通过呢?

**Comment by KomachiSion** [comment]
不太清楚sentinel是否支持配置nacos的用户名密码，建议转到sentinel问。

**Comment by xuxu8511** [comment]
解决了吗 最后？
