### ISSUE TITLE
NACOS1.4.1 命名空间权限不生效

### ISSUE THREAD

**Issue by iwfun** [alibaba/nacos#4743]
1.分别设置三个命名空间 PROD TEST DEV
2.分别设置两个角色（ROLE_TEST，ROLE_DEV） 分别拥有命名空间权限TEST,DEV
3.新建一个用户，赋予上述两角色权限，该用户除了拥有权限的TEST，DEV外，也能操作PROD的配置

**Comment by KomachiSion** [comment]
需要开启鉴权功能 https://nacos.io/zh-cn/docs/auth.html

**Comment by iwfun** [comment]
> 需要开启鉴权功能 https://nacos.io/zh-cn/docs/auth.html
好的 谢谢

**Comment by iwfun** [comment]
ok了
