### ISSUE TITLE
alibaba springcloud nacos 连接配置必须在bootstrap.yml，可否改成先bootstrap.yml，若无再application.yml

### ISSUE THREAD

**Issue by neo-shirley** [alibaba/nacos#4745]
springcloud 项目，引入nacos-starter，在application.yml里设置nacos的配置地址无效，要新建个bootstrap.yml，才能读取到。这样太硬性了，建议改成先bootstrap.yml，若无再application.yml

**Comment by KomachiSion** [comment]
这个机制是spring cloud定的， 是spring cloud的标准，nacos无法决定这个机制。 可以转到SCA社区去讨论下。
