### ISSUE TITLE
No such extension com.alibaba.dubbo.registry.RegistryFactory by name nacos

### ISSUE THREAD

**Issue by Chunghwa-2018** [alibaba/nacos#4747]
see Spring XML configuration driver sample，
No error in configuration。

version Info:
     <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>dubbo-registry-nacos</artifactId>
      <version>2.7.6</version>
    </dependency>
    <dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
      <version>1.4.1</version>
    </dependency>
     <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>dubbo</artifactId>
      <version>2.6.7</version>
    </dependency>
    <dependency>
      <groupId>com.alibaba.spring</groupId>
      <artifactId>spring-context-support</artifactId>
      <version>1.0.3</version>
    </dependency>

**Comment by KomachiSion** [comment]
Please move issue to dubbo

**Comment by Chunghwa-2018** [comment]
> Please move issue to dubbo. I think the error is dubbo not find the dubbo register factory for nacos. Maybe you should check the document of dubbo or check your dependency and jar lib whether include target jar.

ok
