### ISSUE TITLE
SQL注入风险

### ISSUE THREAD

**Issue by Xezeloh** [alibaba/nacos#4749]
**Is your feature request related to a problem? Please describe.**
In method getRolesByUserName and many other places, Nacos uses joined 'where' statement to do SQL query, which may lead to a risk of SQL injection.

**Describe the solution you'd like**
Using parameterized SQL query.

**Comment by KomachiSion** [comment]
Which version you used？

**Comment by Xezeloh** [comment]
> Which version you used？

1.3.2

**Comment by KomachiSion** [comment]
升级到1.4.1吧 这个问题应该已经修复了

**Comment by KomachiSion** [comment]
Fixed by #4245.
