### ISSUE TITLE
服务在运行一段时间后 大量的报failed to req API:http://nacos.hngsetc.com:8848/nacos/v1/ns/instance/list. code:404 

### ISSUE THREAD

**Issue by a5618555** [alibaba/nacos#4754]
c.a.n.a.e.NacosException: failed to req API:http://nacos.hngsetc.com:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@ai-audit-server-dev1
	at c.a.n.c.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at c.a.n.c.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at c.a.n.c.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at c.a.n.c.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at c.a.n.c.n.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at c.a.n.c.n.c.HostReactor$UpdateTask.run(HostReactor.java:318)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

nacos 0.9.0.RELEASE
没有FULL GC  线程资源应该是够用的，请问 这种异常是在什么场景才会出现

**Comment by wangweizZZ** [comment]
服务端用的是什么版本？可以控制台上看看服务是否健康

**Comment by KomachiSion** [comment]
控制台能看到这个服务吗？

**Comment by lzp0412** [comment]
是一直都有这个这个报错吗？有没有可能是服务端数据不一致，可以请求每个服务端ip看下这个服务是否会报错？

**Comment by a5618555** [comment]
> 是一直都有这个这个报错吗？有没有可能是服务端数据不一致，可以请求每个服务端ip看下这个服务是否会报错？

我通过arthas的工具    watch  com.alibaba.nacos.client.naming.net.NamingProxy queryList returnObj 的结果
![image](https://user-images.githubusercontent.com/47874195/105474565-55148980-5cd9-11eb-9c6e-0c276abc9667.png)

![image](https://user-images.githubusercontent.com/47874195/105474619-69f11d00-5cd9-11eb-8bd0-ad1e08e1d525.png)
这样的结果是正常的吗？ 很多失败的请求  报错是因为这个导致的吧？

**Comment by a5618555** [comment]
[arthas@1]$ tt -t com.alibaba.nacos.client.naming.net.NamingProxy queryList
 INDEX     TIMESTAMP                 COST(ms)     IS-RET     IS-EXP    OBJECT              CLASS                                  METHOD                                
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1065      2021-01-22 17:43:39       4.72805      true       false     0x106823c0          NamingProxy                            queryList                             
Press Q or Ctrl+C to abort.
Affect(class count: 1 , method count: 1) cost in 193 ms, listenerId: 11
 1066      2021-01-22 17:43:39       4.35229      true       false     0x106823c0          NamingProxy                            queryList                             
 1067      2021-01-22 17:43:39       3.125743     true       false     0x106823c0          NamingProxy                            queryList                             
 1068      2021-01-22 17:43:39       2.181734     true       false     0x106823c0          NamingProxy                            queryList                             
 1069      2021-01-22 17:43:39       2.120141     true       false     0x106823c0          NamingProxy                            queryList                             
 1070      2021-01-22 17:43:39       1.819007     true       false     0x106823c0          NamingProxy                            queryList                             
 1071      2021-01-22 17:43:39       1.570013     true       false     0x106823c0          NamingProxy                            queryList                             
 1072      2021-01-22 17:43:39       11.435413    true       false     0x106823c0          NamingProxy                            queryList                             
 1073      2021-01-22 17:43:39       12.117429    true       false     0x106823c0          NamingProxy                            queryList                             
 1074      2021-01-22 17:43:39       7.628943     true       false     0x106823c0          NamingProxy                            queryList                             
 1075      2021-01-22 17:43:39       4.089774     true       false     0x106823c0          NamingProxy                            queryList                             
 1076      2021-01-22 17:43:39       2.78664      true       false     0x106823c0          NamingProxy                            queryList                             
 1077      2021-01-22 17:43:39       5.437193     true       false     0x106823c0          NamingProxy                            queryList

**Comment by a5618555** [comment]
ts=2021-01-22 17:42:59; [cost=3.461561ms] result=null
ts=2021-01-22 17:42:59; [cost=4.666138ms] result=@String[{"metadata":{},"dom":"DEFAULT_GROUP@@ai-audit-server-app","cacheMillis":10000,"useSpecifiedURL":false,"hosts":[{"valid":true,"marked":false,"metadata":{"management.port":"10287","preserved.register.source":"SPRING_CLOUD"},"instanceId":"10.0.250.130#10286#DEFAULT#DEFAULT_GROUP@@ai-audit-server-app","port":10286,"healthy":true,"ip":"10.0.250.130","clusterName":"DEFAULT","weight":1.0,"ephemeral":true,"serviceName":"DEFAULT_GROUP@@ai-audit-server-app","enabled":true}],"name":"DEFAULT_GROUP@@ai-audit-server-app","checksum":"1f30e6d3544491a1394af2aeef9b4ed9","lastRefTime":1611308585875,"env":"","clusters":""}]
ts=2021-01-22 17:42:59; [cost=2.18779ms] result=null

**Comment by a5618555** [comment]
public synchronized ScheduledFuture<?> addTask(UpdateTask task) {
        return executor.schedule(task, DEFAULT_DELAY, TimeUnit.MILLISECONDS);
    }
看任务的时间 默认是1s   成捕获的情况来看  远远大于这个时间 1秒钟 有23次这样的请求  我的正常服务大概是15  请求这个时间我是否可以调整  比如10秒   我推测可能是网络问题导致   不知道我是否正确？

**Comment by a5618555** [comment]
这个请求在时候会失败 是因为网络问题吗？  这个时间在哪里能够调整。  大概1s有20多个请求   一个服务存在多个实例 这个请求量有点大

**Comment by a5618555** [comment]
@lzp0412   找到问题了  本地缓存没有更新导致的一直404   请问有什么api可以调用 让子服务进行服务刷新吗？

**Comment by KomachiSion** [comment]
哪里的本地缓存没有更新？ nacos-client还是你自己的？

**Comment by a5618555** [comment]
> 哪里的本地缓存没有更新？ nacos-client还是你自己的？

nacos-client    有3分之一还在一直请求     把对应404的服务给  在服务端建上就不会报错，实际上服务已经是不要了的   是否有心跳指令去让 nacos-client全量更新一次缓存

**Comment by KomachiSion** [comment]
没理解啊， 404不是nacos客户端去更新缓存的时候报的吗？你说这个服务你已经删除了？ 那nacos-client 有 unsubscribe方法，删除订阅，就不会一直查询不存在的服务了

**Comment by a5618555** [comment]
那nacos-client 有 unsubscribe方法 &nbsp; 全局搜索没找到该方法 客户端版本是多少？ &nbsp;在哪个类下面


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 上午9:56
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"我要换个网名。"<1027171565@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] 服务在运行一段时间后 大量的报failed to req API:http://nacos.hngsetc.com:8848/nacos/v1/ns/instance/list. code:404  (#4754)





 
没理解啊， 404不是nacos客户端去更新缓存的时候报的吗？你说这个服务你已经删除了？ 那nacos-client 有 unsubscribe方法，删除订阅，就不会一直查询不存在的服务了

**Comment by a5618555** [comment]
> 没理解啊， 404不是nacos客户端去更新缓存的时候报的吗？你说这个服务你已经删除了？ 那nacos-client 有 unsubscribe方法，删除订阅，就不会一直查询不存在的服务了

服务启动后 大多只需要关注RPC比如OpenFegin调用的那些服务       多余的服务实例是不关注的，这种client如何在注册的时候 把多余的服务屏蔽掉 有什么好的思路指导不

**Comment by a5618555** [comment]
> 没理解啊， 404不是nacos客户端去更新缓存的时候报的吗？你说这个服务你已经删除了？ 那nacos-client 有 unsubscribe方法，删除订阅，就不会一直查询不存在的服务了

服务启动后 大多只需要关注RPC比如OpenFegin调用的那些服务 多余的服务实例是不关注的，这种client如何在注册的时候 把多余的服务屏蔽掉 有什么好的思路指导不。
nacos 服务端1.0升级 有哪些版本是 兼容 1.0的客户端的？

**Comment by KomachiSion** [comment]
需要哪些服务不需要哪些服务在你启动的时候应该就知道了，不需要的服务不需要查询吧。如果用的是RPC框架，RPC框架应该会帮你控制，如果是自己用sdk操作，就需要自己选择了，这点完全是业务内容，链路已经超出了nacos的范围了。

升级的话 理论上1.X大版本之间都是兼容的，但是建议还是尽可能匹配版本或者最新版本。

**Comment by a5618555** [comment]
> 需要哪些服务不需要哪些服务在你启动的时候应该就知道了，不需要的服务不需要查询吧。如果用的是RPC框架，RPC框架应该会帮你控制，如果是自己用sdk操作，就需要自己选择了，这点完全是业务内容，链路已经超出了nacos的范围了。
> 
> 升级的话 理论上1.X大版本之间都是兼容的，但是建议还是尽可能匹配版本或者最新版本。

客户端启动后  循环调用这个任务  HostReactor.updateServiceNow  
1、我是想这个请求只去更新追踪、自己调用的服务   不需要去对整个Namespace 所有的服务进行遍历   我上面也有相关的截图 一直在 queryList相关的服务。
2、现在服务中有不少报500 time out的

**Comment by KomachiSion** [comment]
> 客户端启动后 循环调用这个任务 HostReactor.updateServiceNow
> 1、我是想这个请求只去更新追踪、自己调用的服务 不需要去对整个Namespace 所有的服务进行遍历 我上面也有相关的截图 一直在 queryList相关的服务。

这是nacos 客户端的轮训任务。调用过客户端subscribe或getAllService(..., subscribe=true)的服务，都会注册一个轮训任务。所以你看到的是正常的。

>2、 现在服务中有不少报500 time out的

这个超时的问题有很多，可能是服务端GC了，可能是请求量太大，线程不够挤压了，也可能是网络问题，意思仅仅就是尝试获取服务列表超时了。

**Comment by a5618555** [comment]
这个订阅服务的操作 请求如何修改成 订阅指定的服务 没找到相关api &nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月1日(星期一) 上午9:51
收件人:&nbsp;"alibaba/nacos"<nacos@noreply.github.com&gt;;
抄送:&nbsp;"我要换个网名。"<1027171565@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/nacos] 服务在运行一段时间后 大量的报failed to req API:http://nacos.hngsetc.com:8848/nacos/v1/ns/instance/list. code:404  (#4754)





  
客户端启动后 循环调用这个任务 HostReactor.updateServiceNow
 1、我是想这个请求只去更新追踪、自己调用的服务 不需要去对整个Namespace 所有的服务进行遍历 我上面也有相关的截图 一直在 queryList相关的服务。
  
这是nacos 客户端的轮训任务。调用过客户端subscribe或getAllService(..., subscribe=true)的服务，都会注册一个轮训任务。所以你看到的是正常的。
  
2、 现在服务中有不少报500 time out的
  
这个超时的问题有很多，可能是服务端GC了，可能是请求量太大，线程不够挤压了，也可能是网络问题，意思仅仅就是尝试获取服务列表超时了。

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/sdk.html

监听服务
