### ISSUE TITLE
nacos集群启动失败，单机版启动成功

### ISSUE THREAD

**Issue by HelloHaiNG** [alibaba/nacos#4757]
nacos集群三个节点，部署在了同一台机器；设置端口号不一样
cluster.conf文件配置如下：
![image](https://user-images.githubusercontent.com/33769220/105134053-c3661a00-5b28-11eb-90bf-d9b0ce1b8b60.png)

启动第一个nacos节点，启动报错：
![image](https://user-images.githubusercontent.com/33769220/105134150-ea245080-5b28-11eb-8fdb-dfbcf3ce6560.png)

报错原因大概是SQL语句里面的pgsql分页操作不支持limit这种写法
![image](https://user-images.githubusercontent.com/33769220/105135399-ed204080-5b2a-11eb-9013-25e256166afa.png)

重点是nacos单机版启动不报错，所以为什么单机版不用走DumpService.init()逻辑

**Comment by wangweizZZ** [comment]
pgsql --> https://github.com/alibaba/nacos/issues/2328
单机版只是为了快速体验,使用Derby本地存储,走的是对应EmbeddedDumpService 的init()逻辑
