### ISSUE TITLE
NACOS1.4.0配置中心接入后bootstrap里的设置会被清除

### ISSUE THREAD

**Issue by iwfun** [alibaba/nacos#4758]
1.接入 NACOS1.4.0 配置中心之后
```
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2.2.3.RELEASE</version>
</dependency>
```

2.在bootstrap.yml 里配置了应用名字
```
spring:
  application:
    name: iam-acl
```

3.在logback里直接读取名字
`<springProperty scope="context" name="APPLICATION" source="spring.application.name"/>`

会突然读不到
![image](https://user-images.githubusercontent.com/26781465/105134452-6ae34c80-5b29-11eb-8cff-b921c2b07bcc.png)

**Comment by iwfun** [comment]
不好意思  是 jasypt-spring-boot-starter 引起的

**Comment by baijinhua** [comment]
@iwfun 您是怎么解决的呢？
