### ISSUE TITLE
使用nacos-client 1.1.4发生线程等待CPU占用率特别高的情况

### ISSUE THREAD

**Issue by wangwenchi** [alibaba/nacos#4759]
![image](https://user-images.githubusercontent.com/5403627/105143123-640f0680-5b36-11eb-9970-105bc6cda518.png)

![image](https://user-images.githubusercontent.com/5403627/105143679-1fd03600-5b37-11eb-8634-c029efc0afca.png)
![image](https://user-images.githubusercontent.com/5403627/105143696-252d8080-5b37-11eb-8e22-f3d7b7331f64.png)
服务器CPU占用率特别高 定位到进程是nacos这边发生了线程等待的情况
如图所示 麻烦问一下 是什么情况

**Comment by wangwenchi** [comment]
"com.alibaba.nacos.client.Worker.longPolling.fixed-42.194.227.138_88" #95 daemon prio=5 os_prio=0 tid=0x00007f24b0006000 nid=0x5bbe waiting on condition [0x00007f2513d7d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e41aed70> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by horizonzy** [comment]
能多发几次thread命令的结果截图吗。看起来`com.alibaba.nacos.client.Worker.longPolling-xxx`工作线程在等待任务执行，应该不会消耗很多CPU才对。

**Comment by wangwenchi** [comment]
兄弟 你好




&nbsp;

┏&gt;№メ好の孩子在醫院，得了重感冒<┓&nbsp;&nbsp; 
∞╬═→　 ┏━ほ━━お━┓ 　←═╬∞&nbsp;&nbsp; 
∞╬═→　 ┃吃药打针点滴┃ 　←═╬∞&nbsp;&nbsp; 
∞╬═→　 ┗━ち━━ぎ━┛　 ←═╬∞&nbsp;&nbsp; 


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "赵延"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上8:29
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "王文池"<347162176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] 使用nacos-client 1.1.4发生线程等待CPU占用率特别高的情况 (#4759)





 
能多发几次thread命令的结果截图吗。看起来com.alibaba.nacos.client.Worker.longPolling-xxx工作线程在等待任务执行，应该不会消耗很多CPU才对。

**Comment by horizonzy** [comment]
可以直接在arthas中执行`thread -n 10`，查看消耗cpu前10的线程的堆栈信息。多执行几次，然后把信息放出来。

**Comment by KomachiSion** [comment]
是不是长轮训没有block住，导致不停的在发请求，可以看下服务端access_log，或者抓包看下请求频率。

**Comment by KomachiSion** [comment]
@wangwenchi 试下升级客户端试试？

**Comment by chuntaojun** [comment]
优先统计下线程的数量

**Comment by KomachiSion** [comment]
The author has no more response, we think the problem has been fixed in new version.

**Comment by drupal6** [comment]
我也遇到相同的问题了
com.alibaba.nacos.client.Worker.fixed
com.alibaba.nacos.client.config.security.updater
这2个线程的数量创建了很多，有没有不用升级版本就能解决的？
