### ISSUE TITLE
nacos配置中心的配置文件保存在哪个目录下的？是否支持启动的时初始化配置中心中的配置文件？

### ISSUE THREAD

**Issue by jast90** [alibaba/nacos#4763]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wshzp12345** [comment]
nacos 不是有配置文件的目录吗？ 初始化配置你是指 通过 启动命令指定 配置文件吗？ albert hou 邮箱：hzphlm@gmail.com 签名由 网易邮箱大师 定制 在2021年01月20日 20:28，jast 写道：

**Comment by jast90** [comment]
> nacos 不是有配置文件的目录吗？ 初始化配置你是指 通过 启动命令指定 配置文件吗？ albert hou 邮箱：hzphlm@gmail.com 签名由 网易邮箱大师 定制 在2021年01月20日 20:28，jast 写道：

是配置中心中的配置文件，不是nacos的配置文件

**Comment by KomachiSion** [comment]
${nacos/home}/conf/

**Comment by jast90** [comment]
> 可以在启动脚本中修改`--spring.config.additional-location`指定配置文件，默认`${nacos.home}/conf/application.properties`

是作为配置中心时，自己创建的配置文件，不是nacos的配置文件。我在本地nacos导出了配置中心的配置，然后部署的其他环境时直接将配置的zip包导入到nacos配置中心。

**Comment by gaiwey** [comment]
如果没有配置任何nacos的路径的话，默认应该是在这个位置：/root/nacos/config/
