### ISSUE TITLE
branch develop and branch master compile error

### ISSUE THREAD

**Issue by fy741698256** [alibaba/nacos#4768]
**Describe the bug**
develop分支、master分支、1.4.1 Tag都存在以下问题。
JRaftUtils导入了com.alibaba.nacos.consistency.entity下的几个类，而实际上entity包不存在
https://github.com/alibaba/nacos/blob/develop/core/src/main/java/com/alibaba/nacos/core/distributed/raft/utils/JRaftUtils.java
![image](https://user-images.githubusercontent.com/10907941/105321731-cc2b1e80-5c02-11eb-8f18-8a35d2a36a72.png)
https://github.com/alibaba/nacos/tree/develop/consistency/src/main/java/com/alibaba/nacos/consistency
![image](https://user-images.githubusercontent.com/10907941/105321793-e36a0c00-5c02-11eb-833b-9c7405aee00e.png)

**Expected behavior**
能够正确编译
**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by wangweizZZ** [comment]
可以看下 https://nacos.io/zh-cn/docs/faq.html , 根据 .proto文件编译时自动生成
