### ISSUE TITLE
在 isMultiInstance 模式下，多jvm操作文件，snapshot的文件缓存会有被覆盖问题

### ISSUE THREAD

**Issue by ethonchen** [alibaba/nacos#477]
com.alibaba.nacos.client.config.utils.ConcurrentDiskUtil#writeFileContent(java.io.File, java.lang.String, java.lang.String)
这个地方做了文件读写锁。
可以加上文件的 lastmodified 时间，避免多jvm下，出现异常被覆盖的情况

**Comment by yanlinly** [comment]
如果一台机器，多个进程，同时监听一个配置，最终本地磁盘值是一样的。只是可能写两次，不会产生业务错误。

代码这样写的原因是，一个jvm多个bundle之间，启动两个nacos-client实例也是一种常见。 从业务上看都不会产生错误的。

因此不做加强了，不然反而会增加代码的复杂度。
