### ISSUE TITLE
Nacos1.4.1: 发布一次配置后，抛longPolling error

### ISSUE THREAD

**Issue by lesyfly** [alibaba/nacos#4771]
Nacos1.4.1: 在nacos上发布一次配置后，service侧能收到新配置，但是马上会抛longPolling error: java.util.concurrent.RejectedExecutionException，之后就再也无法接收新配置了。

**Comment by horizonzy** [comment]
maybe same reason as https://github.com/alibaba/nacos/issues/4748

**Comment by aiyunxixi** [comment]
同样的问题 #4771

**Comment by aiyunxixi** [comment]
@lesyfly 
你好 请问最后怎么解决的？

**Comment by shixin752** [comment]
You can try to use version 2.2.3 of spring-cloud-alibaba-dependencies,After my test, it can solve this problem.

**Comment by xinlingjushi** [comment]
What is the reason for this mistake ？

**Comment by KomachiSion** [comment]
> What is the reason for this mistake ？

You need ask this question in spring-cloud-alibaba community.
