### ISSUE TITLE
nacos go版本监听不到数据变化

### ISSUE THREAD

**Issue by simake2017** [alibaba/nacos#4774]
使用nacos配置中心，用go客户端监听，但是偶尔发现，没有监听到数据变化，不确定是没有推送到nacos
还是客户端没有监听到，但是重启之后，可以从nacos拿到数据；

**Comment by sanxun0325** [comment]
@simake2017 go-sdk使用版本？ 客户端代码可以贴一下。 可以到nacos-go-sdk仓库中提问。

**Comment by KomachiSion** [comment]
Move to https://github.com/nacos-group/nacos-sdk-go
