### ISSUE TITLE
publishConfig can not push config type 

### ISSUE THREAD

**Issue by Mararesliu** [alibaba/nacos#4777]
**Describe the bug**
publishConfig can not push config type ,eg: json、xml...

**Expected behavior**
ConfigChangeItem configChangeItem = new ConfigChangeItem("type","","json").setType(PropertyChangeType.ADDED);
publishConfig(dataId, group,data,configChangeItem)
**Acutally behavior**
A clear and concise description of what you actually to happen.
have not this feature
**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Which version?

**Comment by Mararesliu** [comment]
nacos-api 1.4.0

**Comment by horizonzy** [comment]
Hi, what api did you use. I notice your demo code 
```
ConfigChangeItem configChangeItem = new ConfigChangeItem("type","","json").setType(PropertyChangeType.ADDED);
publishConfig(dataId, group,data,configChangeItem)
```

What's the logic in publichConfig.

**Comment by Mararesliu** [comment]
I want to push json config, but just can push "publishConfig(dataId, group,data)" have not type attribute

**Comment by horizonzy** [comment]
In NacosConfigService, you can use this api, set the type with value 'json'
```
    /**
     * Publish config.
     *
     * @param dataId  dataId
     * @param group   group
     * @param content content
     * @param type    config type {@link ConfigType}
     * @return Whether publish
     * @throws NacosException NacosException
     */
    boolean publishConfig(String dataId, String group, String content, String type) throws NacosException;
```

**Comment by Mararesliu** [comment]
Which version, I found NacosConfigService have not that function.
Found as follow in 1.4.0
In NacosConfigService.java
  @Override
    public boolean publishConfig(String dataId, String group, String content) throws NacosException {
        return publishConfigInner(namespace, dataId, group, null, null, null, content);
    }
     private boolean publishConfigInner(String tenant, String dataId, String group, String tag, String appName,
            String betaIps, String content) throws NacosException {
            ....
            String url = Constants.CONFIG_CONTROLLER_PATH;
        Map<String, String> params = new HashMap<String, String>(6);
        params.put("dataId", dataId);
        params.put("group", group);
        params.put("content", content);

   The tail param is content , not type.

**Comment by horizonzy** [comment]
nacos-client 1.4.1
