### ISSUE TITLE
The 1.3.1 version uses docker to start the cluster, and the node information in the Nacos console is wrong

### ISSUE THREAD

**Issue by yylfqj** [alibaba/nacos#4780]
When I use docker to deploy the nacos cluster according to the [official documentation](https://github.com/nacos-group/nacos-docker), the information in the nacos console node list is displayed incorrectly。
My server address：nacos1=192.168.100.40:8848，nacos2=192.168.100.40:8849，nacos3=192.168.100.40:8850。

The information displayed on the nacos2 console is as follows:
![1611307646(1)](https://user-images.githubusercontent.com/31428097/105472687-34e3cb00-5cd7-11eb-9032-5f135eca7ba5.jpg)
![1611307655(1)](https://user-images.githubusercontent.com/31428097/105472695-37462500-5cd7-11eb-8c05-8bc49b1eab46.jpg)
![1611307663(1)](https://user-images.githubusercontent.com/31428097/105472703-390fe880-5cd7-11eb-979f-123315f39ba2.jpg)

The nacos1 node voted for itself, the nacos2 node voted for the nacos3 node, and the nacos3 node voted for itself.

So the information in each node should be nacos1 state=FOLLOWER, nacos2 state=FOLLOWER,
nacos3 state=LEADER.

I only saw the correct display on the console of nacos1 address. The only difference is that only the nacos1 node has opened port 9555.

**Comment by KomachiSion** [comment]
Can you use new version and retry? Maybe the problem has been fixed.

**Comment by yylfqj** [comment]
> Can you use new version and retry? Maybe the problem has been fixed.

I tried it with 1.4.1 this morning. This bug has been fixed. The developer has used a new idea to get only the master node information, and the others default to slave nodes. The previous console port 8848 has now been replaced with the 7848 port of the cluster. Thanks to the nacos team for their efforts! ! !
