### ISSUE TITLE
源码运行nacos-console出现There are no [LocalDataChangeEvent] publishers for this event, please register

### ISSUE THREAD

**Issue by ldh7** [alibaba/nacos#4781]
WARN 8988 --- [           main] c.a.nacos.common.notify.NotifyCenter     : There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register
WARN 8988 --- [           main] c.a.nacos.common.notify.NotifyCenter     : There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register
 WARN 8988 --- [           main] c.a.nacos.common.notify.NotifyCenter     : There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register
WARN 8988 --- [           main] c.a.nacos.common.notify.NotifyCenter     : There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register

这个是什么问题？

**Comment by horizonzy** [comment]
这不是问题。nacos初始化启动时加载DB中的数据，加载完后会发事件，这时事件的listener只是还没有注册。

**Comment by ldh7** [comment]
后面也看不到事件注册，这个时候的其他服务启动都读不到配置信息

**Comment by horizonzy** [comment]
你可以在应用启动后通过修改配置来触发LocalDataChangeEvent事件。

**Comment by ldh7** [comment]
启动以后修改、新增配置文件没有任何反应，依旧读不到。

**Comment by jerrychern** [comment]
这个问题怎么解决？我用的1.4.2版本，还是有这个问题。
