### ISSUE TITLE
nacos升级1.3到1.4版本之后权限问题不生效

### ISSUE THREAD

**Issue by feixia5712** [alibaba/nacos#4782]
1 原版本nacos1.3.2升级之后版本1.4.0
升级方法，直接替换nacos-server.jar  重启之后，页面显示为1.4.0
2 配置文件开启权限功能参数
![image](https://user-images.githubusercontent.com/12670758/105478161-cce4b300-5cdd-11eb-829f-312c7bc872ca.png)
3 重新启动
4 页面建普通用户以及角色权限，但是没有生效，还是可以编辑删除
5 请问如何进行排查
6 直接安装使用1.4.0是没有问题的，

请问下是不是升级方式有问题，还是哪里有问题，请帮忙给思路排查下

**Comment by horizonzy** [comment]
确认一下，还是`可以编辑删除`是什么现象。现在的权限是在后端校验的，前端不根据权限进行屏蔽按钮。你的情况是是后端的校验还是能正常通过吗？

**Comment by littlePoBoy** [comment]
> 确认一下，还是`可以编辑删除`是什么现象。现在的权限是在后端校验的，前端不根据权限进行屏蔽按钮。你的情况是是后端的校验还是能正常通过吗？

就是创建个普通用户，给只读的权限，但是该用户还是可以编辑，删除配置信息，并且可以发布成功。

**Comment by feixia5712** [comment]
1   你好我想先确认下，我的升级方式对不对
2 升级后我建立的只读的用户权限但是确实页面删除，编辑都是可以的
3 请问下后台查看哪个日志文件确认下后端校验对不对

**Comment by horizonzy** [comment]
> 1 你好我想先确认下，我的升级方式对不对
> 2 升级后我建立的只读的用户权限但是确实页面删除，编辑都是可以的
> 3 请问下后台查看哪个日志文件确认下后端校验对不对

升级方式是正确的，1.4.0的配置文件加载我记得有点问题，可能配置文件中的配置没有加载到。能否升级到1.4.1的最新版本，再试试。

**Comment by feixia5712** [comment]
好的，独立安装1.4.0我验证过权限是没有任何问题的，升级到1.4.0有问题，等我升级到1.4.1先试试

**Comment by feixia5712** [comment]
> > 1 你好我想先确认下，我的升级方式对不对
> > 2 升级后我建立的只读的用户权限但是确实页面删除，编辑都是可以的
> > 3 请问下后台查看哪个日志文件确认下后端校验对不对
> 
> 升级方式是正确的，1.4.0的配置文件加载我记得有点问题，可能配置文件中的配置没有加载到。能否升级到1.4.1的最新版本，再试试。



下载1.4的包之后，把target下面的nacos-server.jar包拷贝过去，升级1.4.0为1.4.1之后，新建用户，设置只读账户还是有编辑删除权限，是不是跟升级方式有关系，还有哪些配置文件需要进行替换升级？？？

**Comment by feixia5712** [comment]
![image](https://user-images.githubusercontent.com/12670758/105570514-daa14380-5d84-11eb-8c22-8fe5495132e6.png)

**Comment by horizonzy** [comment]
> > > 1 你好我想先确认下，我的升级方式对不对
> > > 2 升级后我建立的只读的用户权限但是确实页面删除，编辑都是可以的
> > > 3 请问下后台查看哪个日志文件确认下后端校验对不对
> > 
> > 
> > 升级方式是正确的，1.4.0的配置文件加载我记得有点问题，可能配置文件中的配置没有加载到。能否升级到1.4.1的最新版本，再试试。
> 
> 下载1.4.1的包之后，把target下面的nacos-server.jar包拷贝过去，升级1.4.0为1.4.1之后，新建用户，设置只读账户还是有编辑删除权限，是不是跟升级方式有关系，还有哪些配置文件需要进行替换升级？？？

使用arthas trace 一下 AuthFilter的doFilter方法，看一下为什么没有进行拦截。

**Comment by horizonzy** [comment]
功能交互问题可以单独提一个issue来描述

**Comment by KomachiSion** [comment]
> > > 1 你好我想先确认下，我的升级方式对不对
> > > 2 升级后我建立的只读的用户权限但是确实页面删除，编辑都是可以的
> > > 3 请问下后台查看哪个日志文件确认下后端校验对不对
> > 
> > 
> > 升级方式是正确的，1.4.0的配置文件加载我记得有点问题，可能配置文件中的配置没有加载到。能否升级到1.4.1的最新版本，再试试。
> 
> 下载1.4.1的包之后，把target下面的nacos-server.jar包拷贝过去，升级1.4.0为1.4.1之后，新建用户，设置只读账户还是有编辑删除权限，是不是跟升级方式有关系，还有哪些配置文件需要进行替换升级？？？

请不要只替换jar包， 启动脚本和配置文件都有可能修改。

**Comment by feixia5712** [comment]
> > > > 1 你好我想先确认下，我的升级方式对不对
> > > > 2 升级后我建立的只读的用户权限但是确实页面删除，编辑都是可以的
> > > > 3 请问下后台查看哪个日志文件确认下后端校验对不对
> > > 
> > > 
> > > 升级方式是正确的，1.4.0的配置文件加载我记得有点问题，可能配置文件中的配置没有加载到。能否升级到1.4.1的最新版本，再试试。
> > 
> > 
> > 下载1.4.1的包之后，把target下面的nacos-server.jar包拷贝过去，升级1.4.0为1.4.1之后，新建用户，设置只读账户还是有编辑删除权限，是不是跟升级方式有关系，还有哪些配置文件需要进行替换升级？？？
> 
> 请不要只替换jar包， 启动脚本和配置文件都有可能修改。

请问下配置文件哪些地方需要修改？？

**Comment by feixia5712** [comment]
不知道官方可不可以出个升级文档做参考

**Comment by KomachiSion** [comment]
1. 升级肯定是全面升级，并不是只替换jar，这对哪个应用应该都一样。暂时不需要升级文档。
2. 配置文件需要修改哪些需要根据你自己的情况看，配置文件内容可以看配置文件中的注释也可以看官方文档中的系统参数介绍https://nacos.io/zh-cn/docs/system-configurations.html

**Comment by feixia5712** [comment]
> 1. 升级肯定是全面升级，并不是只替换jar，这对哪个应用应该都一样。暂时不需要升级文档。
> 2. 配置文件需要修改哪些需要根据你自己的情况看，配置文件内容可以看配置文件中的注释也可以看官方文档中的系统参数介绍https://nacos.io/zh-cn/docs/system-configurations.html

好的，我这边测试了，升级替换jar包，然后替换相关配置文件,启动脚本，,配置文件修改为mysql数据库源地址，然后启动，权限功能正常,其实跟把整个nacos文件夹替换掉，然后直接修改连接数据库也可以升级成功。
