### ISSUE TITLE
1.4.1 k8s 环境下集群启动有问题

### ISSUE THREAD

**Issue by KeRan213539** [alibaba/nacos#4787]
**Describe the bug**
k8s 环境下, 1.4.1 cluster.conf 中使用k8s域名,集群启动失败

**Expected behavior**
能正常解析域名和启动

**Acutally behavior**
非k8s环境下, 使用普通域名,  com.alibaba.nacos.common.utils.IPUtil#isIPv4 中可以正常解析域名
k8s环境下, 使用k8s域名, com.alibaba.nacos.common.utils.IPUtil#isIPv4 中有时能解析出域名,有时解析失败

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by liangyuanpeng** [comment]
可以在pod里面看看域名是否正常ping
