### ISSUE TITLE
关于nacos-client中的HostReactor的一点疑问

### ISSUE THREAD

**Issue by VincentCh01** [alibaba/nacos#4789]
最近在学习Nacos相关的源码中，在com.alibaba.nacos:nacos-client:1.4.0中, com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo:261行
```
 if (null == serviceObj) {
            serviceObj = new ServiceInfo(serviceName, clusters);
            
            serviceInfoMap.put(serviceObj.getKey(), serviceObj);
            
            updatingMap.put(serviceName, new Object());
            updateServiceNow(serviceName, clusters);
            updatingMap.remove(serviceName);
            
        } else if (updatingMap.containsKey(serviceName)) {
```
当有新的服务注册的时候，我发现此处 serviceInfoMap 若不存在该新服务，仍然会将服务信息put到 serviceInfoMap  中去，这将导致 HostReacot.processServiceJson(json) 中 oldService != null 的判断恒为 真
```
public ServiceInfo processServiceJson(String json) {
        ServiceInfo serviceInfo = JacksonUtils.toObj(json, ServiceInfo.class);
        ServiceInfo oldService = serviceInfoMap.get(serviceInfo.getKey());
        if (serviceInfo.getHosts() == null || !serviceInfo.validate()) {
            //empty or error push, just ignore
            return oldService;
        }
        
        boolean changed = false;
        
        if (oldService != null) {
            
            if (oldService.getLastRefTime() > serviceInfo.getLastRefTime()) {
                NAMING_LOGGER.warn("out of date data received, old-t: " + oldService.getLastRefTime() + ", new-t: "
                        + serviceInfo.getLastRefTime());
            }
            
            serviceInfoMap.put(serviceInfo.getKey(), serviceInfo);
```

当然，我并没有完全读懂整个代码的逻辑，但是我希望有人能给我解释一下。不胜感激

**Comment by horizonzy** [comment]
这里的确会是恒为真。这里判断`if(olsService != null)`应该是为了代码的严谨。虽然之前的流程已经保证了oldService一定存在，但是代码后续的迭代过程中，之前的逻辑可能会有变动，这里判断oldService是比较保险的做法。

**Comment by VincentCh01** [comment]
> 这里的确会是恒为真。这里判断`if(olsService != null)`应该是为了代码的严谨。虽然之前的流程已经保证了oldService一定存在，但是代码后续的迭代过程中，之前的逻辑可能会有变动，这里判断oldService是比较保险的做法。

为什么要保证oldService一定存在呢？如果是在新增服务的情况下，oldService不存在应该属于正常的逻辑吧

**Comment by horizonzy** [comment]
客户端关心的是serviceInfo中的hosts. 你可以看processServiceJson中的逻辑。 `if(oldService != null)`,里面判断的是hosts有没有变动(新增，修改，删除)。

**Comment by horizonzy** [comment]
> > 这里的确会是恒为真。这里判断`if(olsService != null)`应该是为了代码的严谨。虽然之前的流程已经保证了oldService一定存在，但是代码后续的迭代过程中，之前的逻辑可能会有变动，这里判断oldService是比较保险的做法。
> 
> 为什么要保证oldService一定存在呢？如果是在新增服务的情况下，oldService不存在应该属于正常的逻辑吧

不存在是ok的，存在也是ok的。

**Comment by VincentCh01** [comment]
> 客户端关心的是serviceInfo中的hosts. 你可以看processServiceJson中的逻辑。 `if(oldService != null)`,里面判断的是hosts有没有变动(新增，修改，删除)。

是的，因为我们公司的需求有一些特殊，希望在注册新服务的时候基于serviceInfo来将服务信息储存在我们的数据库内，所以现在我们的方案是在 processServiceJson 的逻辑中，新增逻辑与删除逻辑中判断 host.size() > 0 来判断是否要对我们自己的数据进行增加或删除。

**Comment by horizonzy** [comment]
嗯，可以在这里代码块中去实现你们的逻辑.
```
            if (newHosts.size() > 0 || remvHosts.size() > 0 || modHosts.size() > 0) {
                NotifyCenter.publishEvent(new InstancesChangeEvent(serviceInfo.getName(), serviceInfo.getGroupName(),
                        serviceInfo.getClusters(), serviceInfo.getHosts()));
                DiskCache.write(serviceInfo, cacheDir);
            }
```

**Comment by horizonzy** [comment]
如果没有疑问就关掉这个issue吧。

**Comment by MQPearth** [comment]
有意思
