### ISSUE TITLE
节点列表于实际成员列表不符

### ISSUE THREAD

**Issue by liangyuanpeng** [alibaba/nacos#4792]
**Describe the bug**

![image](https://user-images.githubusercontent.com/28711504/105620778-53fb6d80-5e3b-11eb-8253-91d635b3bb51.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. docker-compose部署3个节点  
2. 添加一个nacos4节点，修改集群节点的cluster.conf文件
3. 在nacos1..3查看集群列表 (nacos4集群列表符合预期)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
nacos1..3的cluster.conf修改了吗？

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough. Close issue first.
