### ISSUE TITLE
Nacos Metrics Influxdb loses full exception metrics

### ISSUE THREAD

**Issue by wangzhenxyz1** [alibaba/nacos#4795]
**Describe the bug**
Nacos Metrics loses full exception metrcis as well rt,notify_rt, nacos_timer, http_server_requests_seconds_sum partial metrics.

**Expected behavior**
Metrics includes Full Exception Metrics, as well rt,notify_rt, nacos_timer, http_server_requests_seconds_sum.

**Acutally behavior**
Lost Full Exception Metrics, as well rt,notify_rt, nacos_timer, http_server_requests_seconds_sum.

Desktop
- OS: CentoOS 7.2.1511
- Version: 1.4.0

Metrics Config:
```
### Metrics for prometheus
management.endpoints.web.exposure.include=*

### Metrics for elastic search
management.metrics.export.elastic.enabled=false
#management.metrics.export.elastic.host=http://localhost:9200

### Metrics for influx
management.metrics.export.influx.enabled=true
management.metrics.export.influx.db=nacos
management.metrics.export.influx.uri=http://a.b.c.d:8086
management.metrics.export.influx.auto-create-db=true
management.metrics.export.influx.consistency=one
management.metrics.export.influx.compressed=true
```

**Comment by jiangxiaochuan** [comment]
Can you provide the influxdb import template? @wangzhenxyz1

**Comment by wangzhenxyz1** [comment]
> Can you provide the influxdb import template? @wangzhenxyz1

I refer prometheus template configuration, reconfig the influxdb dashboard.
the configration file is the exact same as promethues template.
