### ISSUE TITLE
nginx配置跳转到Nacos地址，修改配置时，会报"Request error,please try again later!”，有大佬知道怎么解决吗？

### ISSUE THREAD

**Issue by zredMonkey** [alibaba/nacos#4797]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
先确认错误是nginx报的还是nacos报的，找到真实的错误内容，然后把真实的错误内容发出来。
还有版本等信息一起带上

**Comment by KomachiSion** [comment]
No more response from author. And current information is not enough. So close issue first
