### ISSUE TITLE
使用官方实例中的nacos-spring-boot-discovery-example注册成功后无法上报健康状态

### ISSUE THREAD

**Issue by SBFVYGA** [alibaba/nacos#480]
运行环境：linux下单机模式运行nacos server（这里的server全是默认的没有做任何修改），ip地址为192.168.111.5，端口默认8848
bug复现：使用idea运行官方实例将application.properties中的nacos.discovery.server-addr=更改为192.168.111.5:8848，在官方实例的controller.DiscoveryController 中增加一个注册方法 采用namingService来注册一个实例。这时访问http://192.168.111.5:8848/nacos/#/ 服务列表中多了一条数据，但是实例和健康都为0

**Comment by xuechaos** [comment]
![image](https://user-images.githubusercontent.com/3983999/50077427-52ecc080-021f-11e9-97e2-ce7fa3f871ce.png)

**Comment by xuechaos** [comment]
@nkorange 这个是这个用户的报错信息

**Comment by xuechaos** [comment]
![image](https://user-images.githubusercontent.com/3983999/50078363-bc6dce80-0221-11e9-83cc-054d24e795a5.png)

**Comment by SBFVYGA** [comment]
问题已经解决，是由于nacos注册成功后，会主动请求一次，但是获取的ip地址不是网卡本身的地址。而是/etc/hostname 中定义的域名地址，恰巧我这边没有定义，所以一直报错。
