### ISSUE TITLE
Nacos client publishConfig return True,but the configuration was nothing happend in management page

### ISSUE THREAD

**Issue by skyobin** [alibaba/nacos#4800]
## Issue Description
Nacos client publishConfig return True,but the configuration was nothing happend in management page.

I can`t see anything changed in management page. At the same time, i can`t get the configation throught sdk.

My code is as follows
`
Properties properties = new Properties();
properties.put(PropertyKeyConst.NAMESPACE, namespace);
properties.put(PropertyKeyConst.SERVER_ADDR, SERVER_ADDR);
properties.put("username","nacos");
 properties.put("password","nacos");
 ConfigService configService = NacosFactory.createConfigService(properties);
return configService.publishConfig(dataId , group , configurationContent , "yaml");
`
No errors occurred, and the result is true.

server nacos 1.4.1
client also 1.4.1
`<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.4.1</version>
		</dependency>`

status/need feedback

The existing configuration information can be obtained  from the server. So It can eliminate the problem of Properties information error

Just set the namespaces value , configService.publishConfig do not work
properties.put(PropertyKeyConst.NAMESPACE, namespace);

Has anyone else encountered this problem?

**Comment by sanxun0325** [comment]
More information can be provided, such as the client version and the code snippet for the query configuration,notice the namespace setting.

**Comment by skyobin** [comment]
server nacos 1.4.1
client also 1.4.1
`		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.4.1</version>
		</dependency>`

**Comment by skyobin** [comment]
> More information can be provided, such as the client version and the code snippet for the query configuration,notice the namespace setting.

server nacos 1.4.1
client also 1.4.1
<dependency> <groupId>com.alibaba.nacos</groupId> <artifactId>nacos-client</artifactId> <version>1.4.1</version> </dependency>

The existing configuration information can be obtained from the server. So It can eliminate the problem of Properties information error

**Comment by sanxun0325** [comment]
You can provide publish configurations, as well as logs when querying configurations.

**Comment by KomachiSion** [comment]
What's your namespace? if you want to publish to `public`. Please not set namespace when init nacosConfigService

**Comment by skyobin** [comment]
> What's your namespace? if you want to publish to `public`. Please not set namespace when init nacosConfigService

Thx, not to use `publish` as the keyword , it works

**Comment by skyobin** [comment]
> You can provide publish configurations, as well as logs when querying configurations.

Thx, not to use `publish` as the keyword when init configService, it works

**Comment by skyobin** [comment]
> > You can provide publish configurations, as well as logs when querying configurations.
> 
> Thx, not to use `public` as the keyword when init configService, it works

but, it set other values(eg: test,DEV..),it do not work too.
properties.put(PropertyKeyConst.NAMESPACE, 'test');

**Comment by skyobin** [comment]
it must use namespace ID.
properties.put(PropertyKeyConst.NAMESPACE, 'test');  // not work
properties.put(PropertyKeyConst.NAMESPACE, '06526f83-0cf8-497a-990e-28756e4c1d86'); // it work

namespace name: test ; namespace Id: 06526f83-0cf8-497a-990e-28756e4c1d86
