### ISSUE TITLE
spring.cloud.nacos.config.password可否自身代码处理后再设置，例如：将加密的密码，解密后再设置

### ISSUE THREAD

**Issue by sunrdd** [alibaba/nacos#4801]
当要求项目中所有的密码都不能明文的在配置文件中时，可否实现将加密的密码解密后，再进行spring.cloud.nacos.config.password的设置。

**Comment by sanxun0325** [comment]
根据哪钟算法加密，或者解密 不同的用户可能有不同的需求，这个自己按需实现NacosConfigProperties的逻辑就好。
