### ISSUE TITLE
com.alibaba.nacos.api.config.ConfigService#addListener  Comment is error？ 

### ISSUE THREAD

**Issue by beijingzhangwei** [alibaba/nacos#4806]
**If provided,** use the main thread callback, May block other configurations or be blocked by other configurations.
it should be : If **not** provided? 

code:com.alibaba.nacos.client.config.impl.CacheData#safeNotifyListener
`final long startNotify = System.currentTimeMillis();
        try {
            if (null != listener.getExecutor()) {
                listener.getExecutor().execute(job);
            } else {
                job.run();
            }
        } catch (Throwable t) {
            LOGGER.error("[{}] [notify-error] dataId={}, group={}, md5={}, listener={} throwable={}", name, dataId,
                    group, md5, listener, t.getCause());
        }`

**Comment by a7217107** [comment]
i will solve it
