### ISSUE TITLE
开启安全校验后通过getServerConfig拿配置失败

### ISSUE THREAD

**Issue by PizerLiu** [alibaba/nacos#4807]
**Describe the bug**

升级到nacos2后，还是有错误信息
![image](https://user-images.githubusercontent.com/19817160/105969394-2aed0e00-60c3-11eb-8552-816e8da6680b.png)

ServerInfo{serverIp='xx.xx.xx.xx', serverPort=9848}，9848是需要提供对应的服务端nacos支撑么

**Desktop (please complete the following information):**
spring-cloud-starter-alibaba-nacos-config 2.1.2.RELEASE + nacos-client 2.0.0-ALPHA.2

**Additional context**

**Comment by KomachiSion** [comment]
nacos2 gRPC端口是 主端口+1000 如果你是默认的就是9848.  如果有防火墙需要打开。

**Comment by PizerLiu** [comment]
必须要用nacos2-server是么，我用nacos1-server是报连不上这个。

**Comment by PizerLiu** [comment]
另外你们的代码库tag貌似有点问题：

**Comment by PizerLiu** [comment]
![image](https://user-images.githubusercontent.com/19817160/105985823-fb480100-60d6-11eb-8789-98b4a5b4928b.png)

![image](https://user-images.githubusercontent.com/19817160/105985853-0733c300-60d7-11eb-8d80-0d6c800bc33f.png)


拉的下面这个编译的Server貌似也连不上

**Comment by KomachiSion** [comment]
2.0的客户端必须要用2.0的服务端。

第二张截图我看一下。 建议先用2.0.0分支来编译

**Comment by KomachiSion** [comment]
> ![image](https://user-images.githubusercontent.com/19817160/105985823-fb480100-60d6-11eb-8789-98b4a5b4928b.png)
> 
> ![image](https://user-images.githubusercontent.com/19817160/105985853-0733c300-60d7-11eb-8d80-0d6c800bc33f.png)
> 
> 拉的下面这个编译的Server貌似也连不上

2.0.0-ALPHA2的tag不对，直接用2.0.0分支吧

**Comment by PizerLiu** [comment]
嗯  用2.0.0编译的server端可以连上rpc了，但是configService.getConfig还是拿不到配置
![image](https://user-images.githubusercontent.com/19817160/106095626-11090500-616f-11eb-9943-6d85f586dffe.png)
![image](https://user-images.githubusercontent.com/19817160/106095680-241bd500-616f-11eb-838b-4753dc6aa65e.png)

**Comment by PizerLiu** [comment]
![image](https://user-images.githubusercontent.com/19817160/106096937-62b28f00-6171-11eb-97e3-77f540b788c4.png)
.properties这种直接采用注解的是可以获取的，accessToken是加到header里的
![image](https://user-images.githubusercontent.com/19817160/106097827-f20c7200-6172-11eb-95cf-5b3647bc6ba5.png)

但是我自定义获取json的配置就不行，header里也没有accessToken
![image](https://user-images.githubusercontent.com/19817160/106098743-82978200-6174-11eb-86ba-7c8d8c9bba56.png)

**Comment by KomachiSion** [comment]
会不会是你程序里加载了复数个NacosConfigService, 但是只在其中一个配置了鉴权参数？

**Comment by KomachiSion** [comment]
能贴一下你代码中 `initConfigService`那一段吗？

**Comment by PizerLiu** [comment]
![image](https://user-images.githubusercontent.com/19817160/106237217-4b3ed900-6239-11eb-9287-038ab10ed934.png)

**Comment by PizerLiu** [comment]
暂时搞定了

![image](https://user-images.githubusercontent.com/19817160/106241323-d1aae900-6240-11eb-91e4-e6099ba8f7c7.png)

原来一直不行是使用的Factory，原因还不明

`Properties properties = new Properties();
properties.setProperty("serverAddr", NACOS_SERVER_ADDR);
properties.setProperty("namespace", NACOS_NAMESPACE);
return configService = NacosFactory.createConfigService(properties);`

**Comment by PizerLiu** [comment]
你好，再请教个问题：
cluster.conf中假如配置了3个实例，都集群方式启动了。
其中一个实例漂移到其他机器，ip变动了，nacos-cluster能否感知到，自动修改集群配置并且会热更新？

**Comment by KomachiSion** [comment]
这种情况要用域名模式，或者用operator修改cluster.conf文件

**Comment by KomachiSion** [comment]
> 暂时搞定了
> 
> ![image](https://user-images.githubusercontent.com/19817160/106241323-d1aae900-6240-11eb-91e4-e6099ba8f7c7.png)
> 
> 原来一直不行是使用的Factory，原因还不明
> 
> Properties properties = new Properties();
> properties.setProperty("serverAddr", NACOS_SERVER_ADDR);
> properties.setProperty("namespace", NACOS_NAMESPACE);
> return configService = NacosFactory.createConfigService(properties);

下面贴的是原来的代码？ 没有输入用户名密码的话肯定没有token啊。
