### ISSUE TITLE
1.4.1Nacos开启密码验证之后注册403

### ISSUE THREAD

**Issue by qq31715879** [alibaba/nacos#4809]
![image](https://user-images.githubusercontent.com/21219283/105972504-a7352080-60c6-11eb-9052-00462a43567e.png)

**Comment by KomachiSion** [comment]
请升级Spring cloud版本后再试。

**Comment by stalary** [comment]
我从1.3.1升级到1.4.1遇到了同样的问题，有什么平滑升级的方案吗？

**Comment by qq31715879** [comment]
> 请升级Spring cloud版本后再试。

Spring cloud 版本 : Hoxton.SR3

![image](https://user-images.githubusercontent.com/21219283/106076718-15bbc200-614b-11eb-8008-2e02aaa853f3.png)

**Comment by KomachiSion** [comment]
2.1.1版本官方依赖是1.1.3好像， 那个时候nacos还没有鉴权。SCA也没有用户名密码参数。
升级到最新版再试试。

**Comment by qq31715879** [comment]
> 2.1.1版本官方依赖是1.1.3好像， 那个时候nacos还没有鉴权。SCA也没有用户名密码参数。
> 升级到最新版再试试。

已经升级 还是403, 老哥帮看看版本哪里还有问题
![image](https://user-images.githubusercontent.com/21219283/106078693-c6779080-614e-11eb-8714-9005f7a646db.png)

**Comment by qq31715879** [comment]
> 2.1.1版本官方依赖是1.1.3好像， 那个时候nacos还没有鉴权。SCA也没有用户名密码参数。
> 升级到最新版再试试。

已解决, 不过必须在spring.cloud.nacos节点配置账号密码, 在discovery节点配置则不行.

**Comment by MrWTao** [comment]
请问最终的cloud版本的alibaba版本分别是啥呢，我用的cloud：Hoxton.SR8和alibaba:2.2.3.RELEASE还是403

**Comment by syapollo** [comment]
我试了下，服务端是1.4.1，客户端alibaba:2.2.3.RELEASE不可以，2.2.1可以，2.2.5可以，现在我的服务端升级到1.4.1，要求客户端端都升级，好麻烦啊~
