### ISSUE TITLE
Questions about delays in obtaining configuration content

### ISSUE THREAD

**Issue by shenzlly** [alibaba/nacos#4812]
Explain that this is not a bug question，
 
- OS: [ Centos]
 - Version [ nacos-server 1.3.2]
 - Module [config]

Deployment information: cluster mode, single node, use mysql storage
How to use: Client is not used, call server interface through api
【部署信息 ：集群模式，单节点，使用mysql存储
使用方式：未使用客户端，通过api调用server接口】

Scenario: First call the publish configuration interface publishConfig, and then call the content acquisition interface getConfig,
Occasionally, the obtained content is not up-to-date. By viewing the source code, it is found that the library will be directly checked only in stand-alone mode and internal storage.
Others are looking for the local files of the service. Here is a question. Can't I directly check the database if I use the external storage mysql?
【场景： 先调用发布配置接口publishConfig，然后调用获取内容接口getConfig，
现象偶尔会出现获取内容不是最新的，通过查看源码发现只有在单机模式并且是内部存储的情况下才会直接查库，
其他的都查找服务的本地文件， 这里有一个疑问 用了外部存储mysql 不可以直接查库吗？】
I saw that the current process is to notify other service nodes through time after the release, and then dump the data to a local file. I don't know if I understand it correctly. I want to know what are the thoughts and considerations of this design method? Thank you
【我看了下现在的流程是发布完以后通过事件通知给其他服务节点然后dump数据到本地文件，不知道我理解的对不对，我想知道这种设计方式的思想和考虑都有哪些？谢谢】

**Comment by KomachiSion** [comment]
1. Nacos can add nodes to dispatcher the pressure, but database can't. If all request query database directly, will cause database pressure and push down the database. 
2. you publishConfig in A node and getConfig in B node, some time the dump operation is not ready, so the query maybe the old cache. The best way is to listen or subscribe the dataId, it will get the new context always.

**Comment by shenzlly** [comment]
> 1. Nacos can add nodes to dispatcher the pressure, but database can't. If all request query database directly, will cause database pressure and push down the database.
> 2. you publishConfig in A node and getConfig in B node, some time the dump operation is not ready, so the query maybe the old cache. The best way is to listen or subscribe the dataId, it will get the new context always.



> 1. Nacos can add nodes to dispatcher the pressure, but database can't. If all request query database directly, will cause database pressure and push down the database.
> 2. you publishConfig in A node and getConfig in B node, some time the dump operation is not ready, so the query maybe the old cache. The best way is to listen or subscribe the dataId, it will get the new context always.

Understand, thank you for your answer
