### ISSUE TITLE
如何同步最新代码一些疑问请教

### ISSUE THREAD

**Issue by LeePui** [alibaba/nacos#4817]
Hello，我们现在打算使用Nacos替代ZK，目前使用的1.4.0，自己做了一些小改造，近期想升级到1.4.1，想请教一下关于升级的一些疑问或者最佳实践。
1、想知道Nacos修复不同版本的一些bug是如何操作的。假设1.4.0修复了几个bug，是否是重新拉一条bug分支修复的？修复后版本还是叫1.4.0不？我需要同步哪条分支的代码呢？还是说同步名字为1.4.0这个tag的代码即可。
2、每个版本是从哪条分支拉出来的？例如我现在是1.4.0，日后要升级到1.4.1。我应该同步哪条分支代码呢，还是说同步1.4.1这个tag的代码？还有日后想升级到2.0，我如何知道是否能同步呢？
3、在做完同步后，我需要测试所有的功能是否正常，我看到每个模块下面都有test，有没有办法一次性将所有的模块测试用例都执行一遍，或者想请教下你们在做升级的时候，是如何回归一次所有功能的。

由于对开源项目的流程不是很熟悉，第一次接触，所以想对这些问题先了解清楚一下。

**Comment by KomachiSion** [comment]
1. 官方修复bug只会在最新版本修复，除非这个漏洞极其影响使用才会使用同一版本号进行hotfix
2. 拉出分支自己维护后，如何升级则是您自己需要考虑的事情了。建议您基于develop分支改动，并贡献回主分支，但是动手前最好开启issue充分讨论后再动手，避免您的努力不被社区接受
3. 目前各模块单侧和test模块还不是很完善，仅作为参考，如果需要进行回归，可以使用`mvn clean test`等指令触发 详情见源码根目录下`.travis.yml`内容
