### ISSUE TITLE
v1.4.1 使用yaml配置未设置value的配置项会有错

### ISSUE THREAD

**Issue by jiushizyj** [alibaba/nacos#4818]
配置中心中通过yaml格式进行配置管理时，如果key没有设置value，并且项目中也未设置默认值值，将导致项目中无法获取到配置项

**Comment by KomachiSion** [comment]
先查看下nacos客户端的日志，看下返回的完整配置信息中是否有这个key，如果有，那就是上层框架解析yaml时的问题。不是nacos的问题。

**Comment by KomachiSion** [comment]
No more response from author, we think the problem is not nacos' problem.
