### ISSUE TITLE
naming.deregisterInstance这个方法有bug, 调用了服务仍然还没下线

### ISSUE THREAD

**Issue by BillWuSQL** [alibaba/nacos#4819]
Properties properties = new Properties();
properties.setProperty("serverAddr", hostUrl);
properties.setProperty("namespace", namespace);

NamingService naming = NamingFactory.createNamingService(properties);

naming.deregisterInstance(finalServiceName, ip, port, clusterName);

**Comment by KomachiSion** [comment]
你用A客户端注册 用B客户端注销？ 那肯定有问题啊。心跳在A客户端维系啊。

**Comment by BillWuSQL** [comment]
> 你用A客户端注册 用B客户端注销？ 那肯定有问题啊。心跳在A客户端维系啊。

这跟客户端有什么关系，我掉deregisterInstance这个接口，serviceName, ip, port 这些参数都传对了，就是一个http请求。
之前好像试过几次成功的。

**Comment by BillWuSQL** [comment]
> 你用A客户端注册 用B客户端注销？ 那肯定有问题啊。心跳在A客户端维系啊。

意思是要像官方demo一样，放在同一个NamingService实例里搞？
我这是k8s pods停机时，单独调用的一个独立接口，   不跟之前的逻辑混在一起的。

**Comment by sanxun0325** [comment]
> > 你用A客户端注册 用B客户端注销？ 那肯定有问题啊。心跳在A客户端维系啊。
> 
> 这跟客户端有什么关系，我掉deregisterInstance这个接口，serviceName, ip, port 这些参数都传对了，就是一个http请求。
> 之前好像试过几次成功的。

naming.deregisterInstance(finalServiceName, ip, port, clusterName);  如果ip和port不是当前应用的ip和端口，那么不能下线是正常情况，因为ip和port对应的那个服务还是在正常的和Nacos服务端维持心跳。

**Comment by BillWuSQL** [comment]
> > > 你用A客户端注册 用B客户端注销？ 那肯定有问题啊。心跳在A客户端维系啊。
> > 
> > 
> > 这跟客户端有什么关系，我掉deregisterInstance这个接口，serviceName, ip, port 这些参数都传对了，就是一个http请求。
> > 之前好像试过几次成功的。
> 
> naming.deregisterInstance(finalServiceName, ip, port, clusterName); 如果ip和port不是当前应用的ip和端口，那么不能下线是正常情况，因为ip和port对应的那个服务还是在正常的和Nacos服务端维持心跳。

这个我理解 ，ip和port确实是当前应用的ip和port，

**Comment by BillWuSQL** [comment]
nacos-api-1.3.3

**Comment by BillWuSQL** [comment]
> > > > 你用A客户端注册 用B客户端注销？ 那肯定有问题啊。心跳在A客户端维系啊。
> > > 
> > > 
> > > 这跟客户端有什么关系，我掉deregisterInstance这个接口，serviceName, ip, port 这些参数都传对了，就是一个http请求。
> > > 之前好像试过几次成功的。
> > 
> > 
> > naming.deregisterInstance(finalServiceName, ip, port, clusterName); 如果ip和port不是当前应用的ip和端口，那么不能下线是正常情况，因为ip和port对应的那个服务还是在正常的和Nacos服务端维持心跳。
> 
> 这个我理解 ，ip和port确实是当前应用的ip和port，

我现在是发一个请求把心跳改成500ms，来解决服务下线的问题。

**Comment by sanxun0325** [comment]
@BillWuSQL 没有太看懂你的需求，如果你想实现外部服务控制实例下线，可以参考nacos cosole的下线按钮接口。

**Comment by BillWuSQL** [comment]
> nacos cosole

明白， 那个就是rest接口来搞， 调过，不生效。那个上下线应该只是一个标记吧。。

**Comment by KomachiSion** [comment]
要注销实例 必须使用注册时使用的客户端进行注销。 实例是有状态的数据，和客户端是有关联的。用不同的客户端去注销都无法成功删除。

就好比你服务运行的好好的，有个小天才来给你删了。那你该不该续回来？

**Comment by KomachiSion** [comment]
> > nacos cosole
> 
> 明白， 那个就是rest接口来搞， 调过，不生效。那个上下线应该只是一个标记吧。。

是一个标记， 被标记下线的实例不会被推送给订阅端， 但是控制台还是能看到，因为还有可能再上线。

**Comment by BillWuSQL** [comment]
> 要注销实例 必须使用注册时使用的客户端进行注销。 实例是有状态的数据，和客户端是有关联的。用不同的客户端去注销都无法成功删除。
> 
> 就好比你服务运行的好好的，有个小天才来给你删了。那你该不该续回来？
> 
> 你调用接口，他会把实例删除掉， 但是心跳还在，还会恢复的。只能使用注册时的客户端进行注销，心跳才会停止。

Get

**Comment by xiebin2015** [comment]
我也试过，不生效，在A服务里面写了个接口，调用namingService的deregisterInstance方法
代码如图：
![image](https://user-images.githubusercontent.com/14512197/112571377-dba52e80-8e22-11eb-9821-777e0b855d9b.png)
但是服务依然还在

**Comment by Orange486** [comment]
> 我也试过，不生效，在A服务里面写了个接口，调用namingService的deregisterInstance方法
> 代码如图：
> ![image](https://user-images.githubusercontent.com/14512197/112571377-dba52e80-8e22-11eb-9821-777e0b855d9b.png)
> 但是服务依然还在
 用这个方法试试，传递一个实例参数 nacosNamingService.deregisterInstance(serviceName,groupName,instance);

**Comment by Orange486** [comment]
> 我也试过，不生效，在A服务里面写了个接口，调用namingService的deregisterInstance方法
> 代码如图：
> ![image](https://user-images.githubusercontent.com/14512197/112571377-dba52e80-8e22-11eb-9821-777e0b855d9b.png)
> 但是服务依然还在

试试这个 ，传递一个实例参数 nacosNamingService.deregisterInstance(serviceName,groupName,instance);

**Comment by Kevin-Ben** [comment]
```java
    @GetMapping(value = "deregister")
    public String deregisterInstance() {
        String serviceName = nacosDiscoveryProperties.getService();
        String groupName = nacosDiscoveryProperties.getGroup();
        String clusterName = nacosDiscoveryProperties.getClusterName();
        String ip = nacosDiscoveryProperties.getIp();
        int port = nacosDiscoveryProperties.getPort();
        log.info("deregister from nacos, serviceName:{}, groupName:{}, clusterName:{}, ip:{}, port:{}", serviceName, groupName, clusterName, ip, port);
        try {
            NamingService naming = nacosServiceManager.getNamingService(nacosDiscoveryProperties.getNacosProperties());
            naming.deregisterInstance(serviceName, groupName, ip, port, clusterName);
        } catch (NacosException e) {
            log.error("deregister from nacos error", e);
            return "error";
        }
        return "success";
    }
```

**Comment by Superhaoye** [comment]
> ```java
>     @GetMapping(value = "deregister")
>     public String deregisterInstance() {
>         String serviceName = nacosDiscoveryProperties.getService();
>         String groupName = nacosDiscoveryProperties.getGroup();
>         String clusterName = nacosDiscoveryProperties.getClusterName();
>         String ip = nacosDiscoveryProperties.getIp();
>         int port = nacosDiscoveryProperties.getPort();
>         log.info("deregister from nacos, serviceName:{}, groupName:{}, clusterName:{}, ip:{}, port:{}", serviceName, groupName, clusterName, ip, port);
>         try {
>             NamingService naming = nacosServiceManager.getNamingService(nacosDiscoveryProperties.getNacosProperties());
>             naming.deregisterInstance(serviceName, groupName, ip, port, clusterName);
>         } catch (NacosException e) {
>             log.error("deregister from nacos error", e);
>             return "error";
>         }
>         return "success";
>     }
> ```

这个应该不对，就是上面的回答，需要一个注册的客户端去注销实例，我是通过创建了一个客户端交给spring管理，全局直接用来解决的；但是感觉创建和注销实例开销太大了，不知道有没有客户端下线和上线服务的方式
