### ISSUE TITLE
希望Nacos控制台增加支持页面自适应，适用移动端。

### ISSUE THREAD

**Issue by zzzxdm** [alibaba/nacos#482]
目前nacos的控制台只支持PC端浏览器正常访问，移动端没有自适应，页面变形。希望后续支持页面自适应。

**Comment by liangyuanpeng** [comment]
这个有必要吗？

**Comment by zzzxdm** [comment]
> 这个有必要吗？

这个闲暇时可以搞一下，毕竟现在手机的使用很普遍了。我想在手机上改下配置总有这需求吧

**Comment by li-keli** [comment]
I think this can be left to the community to adapt. The core team doesn't have to do this.
In addition, I think usage scenarios are really rare, because most people use them on the Intranet. Rarely use a cell phone to control.

**Comment by liangyuanpeng** [comment]
> I think this can be left to the community to adapt. The core team doesn't have to do this.
> In addition, I think usage scenarios are really rare, because most people use them on the Intranet. Rarely use a cell phone to control.

I think so too
