### ISSUE TITLE
1.4.1版本，通过VIP+三个nacos实例组建集群，Kill某个实例后，部分业务服务仍向下线Nacos实例的进行心跳，业务服务下线失败

### ISSUE THREAD

**Issue by xiangwanli** [alibaba/nacos#4821]
**Describe the bug**
VIP集群模式，如果有nacos实例下线，部分业务服务被kill之后无法正常下线
In VIP cluster mode, if there is a Nacos instance offline, some business services cannot be offline normally after being killed

**Expected behavior**
VIP集群模式，如果有nacos实例下线，业务服务A实例1被kill之后能正常下线，其他业务服务访问服务A时不负载均衡到实例1
In VIP cluster mode, if there is a Nacos instance offline, business service a instance 1 can be offline normally after being killed, and other business services will not load balance to instance 1 when accessing service A

**Acutally behavior**
VIP集群模式，如果有nacos实例下线，部分业务服务被kill之后无法正常下线，导致仍然被引流到下线的业务服务实例
In VIP cluster mode, if there is a Nacos instance offline, some business services can not be offline normally after being killed, resulting in the business service instances still being drained to offline

**How to Reproduce**
1. 按照https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html文档中的集群部署说明中的http://VIP:port/openAPI 挂载VIP模式部署nacos集群
2. VIP（172.31.185.246） ，三个实例依次是172.31.185.2:8848，172.31.185.4:8848，172.31.185.7:8848
3. 业务服务配置NACOS地址为 172.31.185.246:8448
4. Kill某个Nacos实例，例如172.31.185.4:8848
5. 某些业务服务心跳日志报错如下*Additional context*部分
6. 如果Kill -9 某个业务服务A的实例1，nacos中服务A的实例1仍然健康，未下线。访问方式为（172.31.185.246:8848）。
7. 进一步发现，172.31.185.246已绑定到172.31.185.2 ，172.31.185.2也是Leader ， http://172.31.185.2:8848/nacos/访问服务未下线。 但是http://172.31.185.7:8848/nacos/上，服务A的实例1已下线

**Desktop (Win7 chrome 88):**
 - OS: [CentOS x64 7.3]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.2.1]
 - Module [e.g. naming/config]
 - SDK [spring boot sdk]

**Additional context**
2021-01-28 14:11:29.892 [com.alibaba.nacos.naming.beat.sender] ERROR com.alibaba.nacos.client.naming - request 172.31.185.246:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:172.31.185.246:8848/nacos/v1/ns/instance/beat. code:500 msg: org.apache.http.conn.HttpHostConnectException: Connect to 172.31.185.4:8848 [/172.31.185.4] failed: 拒绝连接
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:427)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:312)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2021-01-28 14:11:29.892 [com.alibaba.nacos.naming.beat.sender] ERROR com.alibaba.nacos.client.naming - [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"172.31.185.14","metadata":{"preserved.register.source":"SPRING_CLOUD"},"period":5000,"port":8738,"scheduled":false,"serviceName":"ga@@cooperate-case","stopped":false,"weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([172.31.185.246:8848]) tried: failed to req API:172.31.185.246:8848/nacos/v1/ns/instance/beat. code:500 msg: org.apache.http.conn.HttpHostConnectException: Connect to 172.31.185.4:8848 [/172.31.185.4] failed: 拒绝连接
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:312)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2021-01-28 14:11:34.896 [com.alibaba.nacos.naming.beat.sender] ERROR com.alibaba.nacos.client.naming - request 172.31.185.246:8848 failed.

**Comment by KomachiSion** [comment]
日志不是打印出来了吗 还是访问被kill的ip。 建议排查VIP。

另外不通过vip 直接访问nacos控制台，能看到被kill掉的实例已经变成down了？

**Comment by xiangwanli** [comment]
> 是访问被kill的ip。 建议排

已排查过vip，通过 ip a命令确认虚拟ip 172.31.185.246绑定在 172.31.185.2这台机器上，如下：
[root@xt-mg ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:d6:c0:64 brd ff:ff:ff:ff:ff:ff
    inet 172.31.185.2/22 brd 172.31.187.255 scope global dynamic eth0
       valid_lft 308012375sec preferred_lft 308012375sec
    inet 172.31.185.246/20 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:3eff:fed6:c064/64 scope link
       valid_lft forever preferred_lft forever


上面的日志打印的就很奇怪了，业务服务访问nacos的vip172.31.185.246：8848，但是确报错172.31.185.4拒绝。

如果不通过vip访问nacos ，172.31.185.2:8848被kill的服务未下线， 172.31.185.7:8848被kill的服务正常下线，。

**Comment by KomachiSion** [comment]
控制台能看到被kill的nacos实例是down的状态吗？

**Comment by xiangwanli** [comment]
> 控制台能看到被kill的nacos实例是down的状态吗？

是的， 在172.31.185.2:8848，172.31.185.7:8848两个nacos实例上的节点列表里，可以看到172.31.185.4:8848这个实例状态已经是红色的down状态。
从节点元数据里面查看信息如下：
{
    "lastRefreshTime": 1611905405462,
    "raftMetaData": {
        "metaDataMap": {
            "naming_persistent_service": {
                "leader": "172.31.185.2:7848",
                "raftGroupMember": [
                    "172.31.185.4:7848",
                    "172.31.185.2:7848",
                    "172.31.185.7:7848"
                ],
                "term": 1
            }
        }
    },
    "raftPort": "7848",
    "version": "1.4.1"
}

**Comment by xiangwanli** [comment]
> 控制台能看到被kill的nacos实例是down的状态吗？

另外，VIP+keepalived的测试脚本如下，
#!/bin/bash
count=`ps -ef|grep nacos|grep -v grep|wc -l`
if [ $count -gt 0 ];then
    exit 0
else
    exit 1
fi

肯定是172.31.185.4上面没有了nacos进程，VIP（172.31.185.246）才从绑定在172.31.185.4上变化为绑定到172.31.185.2

**Comment by KomachiSion** [comment]
我在我的网络环境（没有VIP）试了一下，没有复现这个问题，你可以试一下如果不挂载VIP，客户端直接输入所有地址试一下。

**Comment by xiangwanli** [comment]
> 我在我的网络环境（没有VIP）试了一下，没有复现这个问题，你可以试一下如果不挂载VIP，客户端直接输入所有地址试一下。

我这边按这种方式试一下。 
另外我们这边部署服务比较多，也不是所有服务都有这个问题。感觉上，部分服务绑定在实例（172.31.185.2）上， 部分绑定在（172.31.185.4）上，部分绑定在（172.31.185.7）上，停掉nacos实例后，要看业务服务后台日志是否有nacos client的报错，如果没有报错可能不影响， 如果有报错，就像是有绑定关系一样，可能会复现上述问题

**Comment by KomachiSion** [comment]
这里有2个点
1. VIP转发的节点可能转到失效节点上。
2. Nacos的distro协议会是每台服务端负责一部分服务。服务状态发生变更（比如Down，Up）会rehash一次，让责任节点重新分配。
3. 因此我建议您试一下不通过VIP而是直连nacos试一下，如果还会出这样的问题，那很可能是distro协议没有摘除Down的节点，如果只连ok，但是用vip有问题那应该就是VIP的问题了。

**Comment by xiangwanli** [comment]
> 我在我的网络环境（没有VIP）试了一下，没有复现这个问题，你可以试一下如果不挂载VIP，客户端直接输入所有地址试一下。

客户端用的 ，spring-cloud-starter-alibaba-nacos-config， 1.5.1.RELEASE，
业务服务A的配置文件bootstrap.properties 中 配置成：
spring.cloud.nacos.server-addr=172.31.185.2:8848,172.31.185.4:8848,172.31.185.7:8848

kill nacos实例 172.31.185.4:8848，确认172.31.185.4:8848状态为down。
kill 业务服务A, http://172.31.185.2:8848/nacos可查询业务服务A的健康状态仍true
http://172.31.185.7:8848/nacos可以查询业务服务A的健康状态为false。

感觉集群的各节点之间数据不一致， 有没有什么其他手段定位或者手段，判断nacos集群整体是否正常。

**Comment by KomachiSion** [comment]
关于distro协议是否有摘除down的节点，可以看下nacos服务端的naming-server.log， grep一下是否`healthy server list` 看下节点列表是否有更新。

**Comment by KomachiSion** [comment]
> > 我在我的网络环境（没有VIP）试了一下，没有复现这个问题，你可以试一下如果不挂载VIP，客户端直接输入所有地址试一下。
> 
> 客户端用的 ，spring-cloud-starter-alibaba-nacos-config， 1.5.1.RELEASE，
> 业务服务A的配置文件bootstrap.properties 中 配置成：
> spring.cloud.nacos.server-addr=172.31.185.2:8848,172.31.185.4:8848,172.31.185.7:8848
> 
> kill nacos实例 172.31.185.4:8848，确认172.31.185.4:8848状态为down。
> kill 业务服务A, [http://172.31.185.2:8848/nacos可查询业务服务A的健康状态仍true](http://172.31.185.2:8848/nacos%E5%8F%AF%E6%9F%A5%E8%AF%A2%E4%B8%9A%E5%8A%A1%E6%9C%8D%E5%8A%A1A%E7%9A%84%E5%81%A5%E5%BA%B7%E7%8A%B6%E6%80%81%E4%BB%8Dtrue)
> [http://172.31.185.7:8848/nacos可以查询业务服务A的健康状态为false。](http://172.31.185.7:8848/nacos%E5%8F%AF%E4%BB%A5%E6%9F%A5%E8%AF%A2%E4%B8%9A%E5%8A%A1%E6%9C%8D%E5%8A%A1A%E7%9A%84%E5%81%A5%E5%BA%B7%E7%8A%B6%E6%80%81%E4%B8%BAfalse%E3%80%82)
> 
> 感觉集群的各节点之间数据不一致， 有没有什么其他手段定位或者手段，判断nacos集群整体是否正常。

不一致是一直不一致吗？ nacos仅保证最终一致， 如果一段时间（一般不超过30s）后能一致，都是正常的。

**Comment by xiangwanli** [comment]
9:19 kill了172.31.185.4上的nacos实例
ps -ef | grep nacos ，确定在172.31.185.4上已经没有nacos进程。

日志上看， 这个健康状态，172.31.185.4时有时无。

Line 1679: 2021-02-02 09:19:53,338 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 10773: 2021-02-02 09:20:05,340 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.7:8848]
	Line 14238: 2021-02-02 09:23:57,149 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 14320: 2021-02-02 09:23:57,381 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 17693: 2021-02-02 09:24:01,151 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 17862: 2021-02-02 09:24:01,382 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 25726: 2021-02-02 09:24:13,383 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.7:8848]

**Comment by xiangwanli** [comment]
2021-02-02 09:24:13 之后没有再打 healthy server list changed 日志。最后状态是[172.31.185.2:8848, 172.31.185.7:8848] 应该是踢掉了 172.31.185.4:8848，但是我重试重启业务服务A，再杀掉业务服务A,，仍然是之前的情况。

直到我把，172.31.185.4:8848重新启动， 三个nacos实例上都将业务服务A下线了。

**Comment by KomachiSion** [comment]
时有时无就很有问题  我这边kill掉之后就不会再出现了。除非我重启回来

另外你看下另外一台服务端是不是也是一样的日志？

**Comment by xiangwanli** [comment]
> 9:19 kill了172.31.185.4上的nacos实例
> ps -ef | grep nacos ，确定在172.31.185.4上已经没有nacos进程。
> 
> 日志上看， 这个健康状态，172.31.185.4时有时无。
> 
> Line 1679: 2021-02-02 09:19:53,338 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
> Line 10773: 2021-02-02 09:20:05,340 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.7:8848]
> Line 14238: 2021-02-02 09:23:57,149 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
> Line 14320: 2021-02-02 09:23:57,381 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
> Line 17693: 2021-02-02 09:24:01,151 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
> Line 17862: 2021-02-02 09:24:01,382 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
> Line 25726: 2021-02-02 09:24:13,383 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.7:8848]

之前是172.31.185.2上的naming-server.log,一下日志是172.31.185.7的healthy server日志。看上去和172.31.185.2差不多，中间也有一段时间认为172.31.185.4是健康的。但是界面上看， 172.31.185.4一直是down的状态。

	Line 1742973: 2021-02-02 09:19:55,114 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 1751307: 2021-02-02 09:20:07,115 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.7:8848]
	Line 1767366: 2021-02-02 09:24:27,153 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 1767424: 2021-02-02 09:24:27,386 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848]
	Line 1775629: 2021-02-02 09:24:39,155 INFO [NACOS-DISTRO] healthy server list changed, old: [172.31.185.2:8848, 172.31.185.4:8848, 172.31.185.7:8848], new: [172.31.185.2:8848, 172.31.185.7:8848]

**Comment by KomachiSion** [comment]
如果最终都摘除了185.4 那么最终应该A服务会被下线掉才对。

**Comment by horizonzy** [comment]
@xiangwanli 老哥，你那边是稳定复现吗。能否留一个联系方式，我来跟进这个问题

**Comment by xiangwanli** [comment]
> @xiangwanli 老哥，你那边是稳定复现吗。能否留一个联系方式，我来跟进这个问题

昨天本来可以大概率复现的 ，今天又不复现了。如果再出现，有些什么日志或者信息可以收集的?

**Comment by horizonzy** [comment]
复现之后有现场联系我吧。我的钉钉: yuovs93

**Comment by KomachiSion** [comment]
Any process? If no more response, we will close issue.

**Comment by kovow** [comment]
同样的问题，也是三个nacos集群，下掉一台；这个时候服务注册，杀服务就会导致服务不显示下线，会出问题，基本上上边的描述一致
