### ISSUE TITLE
websocket依赖不兼容，NacosWatch获取错误的TaskScheduler导致项目报错

### ISSUE THREAD

**Issue by HSPCode** [alibaba/nacos#4826]
您好，
一、问题描述：nacos作为注册中心，项目同时引入websocket和nacos-discovery依赖，NacosWatch获取错误的taskScheduler（websocket的NoOpScheduler）导致项目无法启动。
![image](https://user-images.githubusercontent.com/47849395/105978391-71476a80-60cd-11eb-8143-79db8a6399b3.png)
二、项目版本依赖：
（1）springboot版本2.0.3.RELEASE
（2）spring-boot-starter-websocket版本是2.0.3.RELEASE
（3）spring-cloud-starter-alibaba-nacos-discovery版本是2.0.3.RELEASE
三、问题原因：NacosWatch的taskScheduler实现类获取的是org.springframework.web.socket.config.annotation.WebSocketConfigurationSupport的内部类NoOpScheduler，这个类的scheduleWithFixedDelay(Runnable task, long delay)方法是抛出异常，导致项目启动不了。
![image](https://user-images.githubusercontent.com/47849395/105978867-f92d7480-60cd-11eb-8b51-d1d45bcd6127.png)
![image](https://user-images.githubusercontent.com/47849395/105977884-dea6cb80-60cc-11eb-8f40-6de47ac5ac86.png)
具体获取：
org.springframework.beans.factory.support.DefaultListableBeanFactory类通过classType获取
![image](https://user-images.githubusercontent.com/47849395/105980225-8e7d3880-60cf-11eb-8e88-32d862663a0a.png)

四、效果对比：
（1）项目去掉spring-boot-starter-websocket依赖，启动成功
（2）通过@Primary指定，启动成功
![image](https://user-images.githubusercontent.com/47849395/105980795-41e62d00-60d0-11eb-9210-281019a6a638.png)
（3）其他项目，未引入spring-boot-starter-websocket依赖，启动成功
五、咨询目的：这个冲突算是nacos-discovery兼容问题；还是说是个人的使用不当导致的，正确用法就是四.(2)？

_Originally posted by @HSPCode in https://github.com/alibaba/nacos/issues/4096#issuecomment-768202136_

**Comment by KomachiSion** [comment]
SCA和其他Spring组件冲突请提交至Spring cloud alibaba 社区。

**Comment by HSPCode** [comment]
> SCA和其他Spring组件冲突请提交至Spring cloud alibaba 社区。

好的好的，打扰大佬了
