### ISSUE TITLE
[Bug] The instances still exist after client didn't sent heart beat.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#4829]
**Describe the bug**
nacos-server env: three nacos-server nodes build cluster. 
node 1: 10.248.224.223
node 2: 10.248.224.187
node 3: 10.248.224.198

1. start node1.
2. register 400 service which hold 100 instances to server.
3. start another two nacos-server nodes (node2, node3)
4. wait for a while
5. stop nacos-client
6. 10 service of 400 still exist 100 instances.

**Desktop (please complete the following information):**
 - OS: centos 7
 - Version [e.g. nacos-server 1.4.2-SNAPSHOT, nacos-client 1.4.1]
 - Module [e.g. naming]

![image](https://user-images.githubusercontent.com/22524871/106141699-74b12380-61ab-11eb-9f6e-1063141c2560.png)
![image](https://user-images.githubusercontent.com/22524871/106141717-7e3a8b80-61ab-11eb-851a-4fb2987b0d96.png)
![image](https://user-images.githubusercontent.com/22524871/106141728-85619980-61ab-11eb-932a-ed30dab1a56a.png)

**Comment by horizonzy** [comment]
界面中残余的10个服务都是由node1(10.248.224.223) 负责。
![image](https://user-images.githubusercontent.com/22524871/106148498-10df2880-61b4-11eb-9249-c877bfba5289.png)
![image](https://user-images.githubusercontent.com/22524871/106148515-163c7300-61b4-11eb-8a46-6c5732fd94b6.png)

trace node1节点(10.248.224.223)的com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask run方法，没有任何执行。
![image](https://user-images.githubusercontent.com/22524871/106148796-7501ec80-61b4-11eb-85d3-3dec52ddedb2.png)


trace node2节点(10.248.224.187)的com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask run方法，有执行，但是不是由服务不是由自己负责，直接返回。
![image](https://user-images.githubusercontent.com/22524871/106148977-ad092f80-61b4-11eb-92d2-1cdb45ee76d0.png)

显然，node1中的ClientBeatCheckTask被取消了。而只有在Service的destory方法中才会被取消。说明这10个service之前在node1中被destory过。service.destory只会在ServiceManager#onDelete被调用，而service要被delete，只会由两种触发，一种是通过openApi去调用，一种就是ServiceManager中的EmptyServiceAutoClean任务去调用，没有人为去调用openApi，这里只有是EmptyServiceAutoClean的检测任务检测到service中不存在instance了，再去删除service。

推测是serice的destory那里存在并发问题，导致后续service一直用的是ClientBeatCheckTask被cancel掉的在跑。

还需继续跟进。

**Comment by horizonzy** [comment]
推测并发问题: 
线程1在执行serviceManager.OnDelete方法.
线程2在执行DistroConsistencyServiceImpl的processData方法.

ServiceManager的onDelete对service进行了destory并且unlisten, destory会把clientBeatCheckTask cancel掉。但是还没有把service从map中移除。
![image](https://user-images.githubusercontent.com/22524871/106163106-c5cd1180-61c3-11eb-8073-576d6af11841.png)

然后其他节点同步数据到了node1. node1发现已经失去了service的监听，会创建一个service，然后对seriviceManager onchange。
![image](https://user-images.githubusercontent.com/22524871/106163363-0b89da00-61c4-11eb-8b17-26515f7fca07.png)

在serviceManagerde的onChange方法中，由于线程1还没有把service从map中移除，所以oldDom还存在，只是去更新了oldDom的一些属性，并且把oldDom对consistencyService重新监听。所以service最终clientBeatCheckTask是被取消掉了。

![image](https://user-images.githubusercontent.com/22524871/106164585-17c26700-61c5-11eb-893d-c9d1ccee830c.png)


按照以上推论的话，有一个点无法论证。线程1始终会把service从serviceMap中移除，后续在serviceMap中应该不存在这个service才对，但是从相关trace来看，serviceMap又存在这个service.

**Comment by horizonzy** [comment]
node1中的HealthCheckReactor中的futureMap为空。
![image](https://user-images.githubusercontent.com/22524871/106165326-f6ae4600-61c5-11eb-932c-be8958c96a11.png)

**Comment by KomachiSion** [comment]
So should we removed oldService from listener map first, and then to destroy old service?

**Comment by horizonzy** [comment]
> So should we removed oldService from listener map first, and then to destroy old service?

The code should be optimize. But I am not sure this solution can solve this strange case.

**Comment by horizonzy** [comment]
追加信息：node1和node2中的dataStore中数据是空的。当时我想到distroVerifyTask会去查dataStore的数据进行同步，我去watch了DataStore.keys方法，返回值的size=0. 为了进一步证实，我又去watch了DistroVerifyTask.verifyForDataStorage，返回值为null.

node1和node2中都是一样的结果。dataStore中数据是空的。service中的cluster持有instances

**Comment by horizonzy** [comment]
refer #4821

**Comment by horizonzy** [comment]
the reason see: https://www.yuque.com/minghuo/aoikaa/pnu6xs
