### ISSUE TITLE
nacos开启了8000端口, 通过构造特定请求包，可远程命令执行

### ISSUE THREAD

**Issue by qq31715879** [alibaba/nacos#4833]
JDWP定义了调试器和被调试的 Java 虚拟机之间的通信协议，通过构造特定请求包，可远程命令执行。生产环境禁止开启该服务 端口探测发现： 机器:xxxxx 开放端口:8000 服务识别: jdwp (Java Debug Wire Protocol (Reference Implementation) version 1.8) 可被命令执行

nacos默认开启了这个端口, 请问可以关闭么, 关闭之后会有什么问题吗

**Comment by KomachiSion** [comment]
nacos没有使用这个端口，你看下是不是你自己修改了启动脚本？开启了java debug。

**Comment by qq31715879** [comment]
额, 用的源码部署和release的start.sh比对了下不太一样

![image](https://user-images.githubusercontent.com/21219283/106263640-9a980000-625f-11eb-8b99-2f3337d370aa.png)

**Comment by KomachiSion** [comment]
1.1.4太旧了，应该是谁debug的时候不小心提交的， 应该很早就去掉了
