### ISSUE TITLE
控制台，集群配置功能疑问

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4837]
版本：1.4.0
在Nacos控制台中，服务列表-->服务详情-->集群配置中
“使用IP端口检查”的打开与关闭的影响是什么。
IP是指什么IP

cluster health checker的检查机制是什么样的。

**Comment by KomachiSion** [comment]
针对持久化服务的健康检查时所使用的端口。
IP为注册的服务实例IP

如果打开`使用IP端口检查`则使用服务实例注册的端口进行检查

如果关闭则使用另外设置的`检查端口`进行检查。

**Comment by wanghuigithub** [comment]
是只针对“持久化服务”的健康检查是吧。
觉得在“集群配置”中配置的信息，比较难联想到只针对“持久化服务”。个人感受
