### ISSUE TITLE
Nacos作为配置中心，Nacos客户端和Nacos Server启动顺序问题

### ISSUE THREAD

**Issue by mysunstar** [alibaba/nacos#4849]
问题：
 现在我发现Nacos客户端比Nacos服务器先启动，会导致Nacos客户端拉取配置文件失败，导致应用服务启动失败

优化建议：
Nacos客户端连接Nacos Server，发现Nacos服务异常，可进行一段时间的等待或者重试，而不是直接拉取失败，忽略拉取配置。这样就不会导致因服务启动顺序问题，导致服务启动失败。

**Comment by horizonzy** [comment]
我认为这不是一个问题。服务端没有启动时，客户端去请求获取失败本身就是正常的。不能因为服务端没有启动，就让客户端去等待。

**Comment by KomachiSion** [comment]
1. 客户端有容灾，拉去配置失败会使用本地文件缓存（即上一次拉取的配置）
2. 如果是第一次启动，那必须是失败的，因为你的应用都没有配置，那么即使运行起来也会有问题。与其hang在那里等，或者应用配置不正确，不如直接抛出明确异常告知服务端有问题更直观更安全。

**Comment by mysunstar** [comment]
@KomachiSion 你好，我正想说可以有个本地缓存文件的机制可以做，请问这个机制在哪个版本已经实现了。我现在用的是下面这个版本。
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.1.2.RELEASE</version>
        </dependency>

**Comment by mysunstar** [comment]
我看这个客户端版本已经有了，在查找本地缓存文件是在这个地方：C:\Users\Admin\nacos\config\fixed-nacosserver_8848_nacos\data\config-data\DEFAULT_GROUP\，但是实际的本地的缓存文件路径是：C:\Users\Admin\nacos\config\fixed-nacosserver_8848_nacos\snapshot\DEFAULT_GROUP，是我配置有问题吗？

**Comment by KomachiSion** [comment]
C:\Users\Admin\nacos\config\fixed-nacosserver_8848_nacos\snapshot\DEFAULT_GROUP 是对的，我记得配置只能通过JVM参数-D 来配置。

我不清楚你是如何配置的。
