### ISSUE TITLE
获取配置接口逻辑疑问

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4850]
Nacos版本：1.4.0

1、com.alibaba.nacos.config.server.controller.ConfigServletInner类的193行：if (configInfoBase == null && fileNotExist(file)) 
当为集群部署且使用外部存储时，如果file不存在。直接返回配置不存在了。
file不存在时，是否可以再读取外部存储。然后更新文件。

**Comment by horizonzy** [comment]
配置数据不是强一致的，是最终一致。如果在nacos-server节点间横向通知时，配置数据的延迟是可以接受的。

**Comment by wanghuigithub** [comment]
> 配置数据不是强一致的，是最终一致。如果在nacos-server节点间横向通知时，配置数据的延迟是可以接受的。

如果由于某种原因导致写磁盘失败。后边获取配置的请求是不是都会拿不到数据。

**Comment by shiyiyue1102** [comment]
服务端磁盘的值相当于是数据库的一层缓存，我们有机制来保证服务端磁盘和数据库的数据一致性，客户端只需要读取服务端磁盘缓存就行了，如果磁盘不存在时读取外部存储，那么这里就会有被缓存穿透的风险，会把后端存储打爆

**Comment by wanghuigithub** [comment]
> 服务端磁盘的值相当于是数据库的一层缓存，我们有机制来保证服务端磁盘和数据库的数据一致性，客户端只需要读取服务端磁盘缓存就行了，如果磁盘不存在时读取外部存储，那么这里就会有被缓存穿透的风险，会把后端存储打爆

想请教下保证服务端磁盘和数据库数据一致性的机制。

我目前了解的是在发布配置时，会向集群节点发送写磁盘的请求。

**Comment by shiyiyue1102** [comment]
> 机制



> > 服务端磁盘的值相当于是数据库的一层缓存，我们有机制来保证服务端磁盘和数据库的数据一致性，客户端只需要读取服务端磁盘缓存就行了，如果磁盘不存在时读取外部存储，那么这里就会有被缓存穿透的风险，会把后端存储打爆
> 
> 想请教下保证服务端磁盘和数据库数据一致性的机制。
> 
> 我目前了解的是在发布配置时，会向集群节点发送写磁盘的请求。
> 
> 还有其他机制来保证一致性么

现在开源是靠6小时全量dump的兜底机制来保证一致性了，这个问题和[https://github.com/alibaba/nacos/issues/4906](url)这个issue相关，后面计划会新增定时增量同步校验机制来保证异常情况下的数据一致性

**Comment by wanghuigithub** [comment]
> > 机制
> 
> > > 服务端磁盘的值相当于是数据库的一层缓存，我们有机制来保证服务端磁盘和数据库的数据一致性，客户端只需要读取服务端磁盘缓存就行了，如果磁盘不存在时读取外部存储，那么这里就会有被缓存穿透的风险，会把后端存储打爆
> > 
> > 
> > 想请教下保证服务端磁盘和数据库数据一致性的机制。
> > 我目前了解的是在发布配置时，会向集群节点发送写磁盘的请求。
> > 还有其他机制来保证一致性么
> 
> 现在开源是靠6小时全量dump的兜底机制来保证一致性了，这个问题和[https://github.com/alibaba/nacos/issues/4906](url)这个issue相关，后面计划会新增定时增量同步校验机制来保证异常情况下的数据一致性


定时同步，在同步时间内还是会存在不一致情况

**Comment by KomachiSion** [comment]
我理解
1. 写磁盘失败会有IO异常， 会重新查询并重新写
2. 写磁盘成功，然后磁盘down掉，读不到数据，这种情况下大概率程序运行本身就有问题。
3. 假设真的出现了磁盘没有问题，写没有IO异常，但是最后还是没写进去的情况，只能通过定期dump来进行更新，只是这个间隔设置的问题。

对于情况3 目前还没有出现过，以为几乎所有写磁盘操作失败，都有IO异常。
