### ISSUE TITLE
在Linux上部署会出现管理页面加载main.js过大的问题，访问极慢，请修复，谢谢

### ISSUE THREAD

**Issue by pangyandong** [alibaba/nacos#4852]
Nacos部署在Windows系统上main为1M左右，属于正常范围，但是部署在Linux上，输入ip:8848/nacos访问，会等大约1分钟才会出现登录页面，查看网络请求，发现main.js竟然加载了9.6M，显然不正常。本人使用本地虚拟机搭建Linux再次测试，问题依然存在。（注：最新bate版本和最新稳定版本都这样）。附件：Linux上加载的main.js文件
[Linux加载的的main.zip](https://github.com/alibaba/nacos/files/5908186/Linux.main.zip)

**Comment by KomachiSion** [comment]
社区有没有前端大神帮忙看下，我看源码里main.js才1.4M

**Comment by KeRan213539** [comment]
win10下也有同样问题, 1.4.1

**Comment by KomachiSion** [comment]
如何瘦身或者拆分需要社区里前端大神们帮助了。

**Comment by pangyandong** [comment]
查看源码验证了一下：
2.0.0-ALPHA.2版本main.js大小：9.2M
2.0.0-ALPHA.1版本main.js大小：1.34M
1.4.1版本main.js大小：9.2M
1.4.0以下版本main.js大小：1.3M左右

**Comment by pangyandong** [comment]
> > 社区有没有前端大神帮忙看下，我看源码里main.js才1.4M
> 
> 刚才看错分支了，最新分支是9.2M
> 
> 就是社区不断加功能，js现在就是这么大了。。

**Comment by pangyandong** [comment]
> > 社区有没有前端大神帮忙看下，我看源码里main.js才1.4M
> 
> 刚才看错分支了，最新分支是9.2M
> 
> 就是社区不断加功能，js现在就是这么大了。。

2.0.0-ALPHA.2版本main.js大小：9.2M
2.0.0-ALPHA.1版本main.js大小：1.34M
1.4.1版本main.js大小：9.2M
1.4.0以下版本main.js大小：1.3M左右

**Comment by dakai6677** [comment]
1.4.1版本不升级的话 怎么解决main.js过大的问题  直接替换吗
