### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by newsouther** [alibaba/nacos#4853]
已解决

**Comment by KomachiSion** [comment]
1. 看下日志，${user.home}/logs/nacos/config.log 以及 你的业务日志里是否有收到nacos的配置推送。
2. 看下是不是spring bean的初始化顺序有问题，比如nacos还没初始化，datasource就开始初始化了，是的话那肯定会有问题，配置都还没有拿到，如果是这个问题，可能要反馈到spring cloud alibaba了
