### ISSUE TITLE
nacos 2.0版本占用CPU的问题

### ISSUE THREAD

**Issue by starfounder** [alibaba/nacos#4855]
![image-20210127133112183](https://user-images.githubusercontent.com/69343610/106572696-ba873680-6573-11eb-857a-762624997d5f.png)
![image-20210127154424008](https://user-images.githubusercontent.com/69343610/106572706-beb35400-6573-11eb-9b4d-f3d60e5a1513.png)
如图所示
排查了之后确定是nacos的问题，一共两个java进程导致cpu炸掉，第一个进程直接关联nacos的pid，另一个查找之后是nacos的服务相关
版本为1月14号更新的版本

**Comment by starfounder** [comment]
![image-20210127133112183](https://user-images.githubusercontent.com/69343610/106572938-00dc9580-6574-11eb-9877-18c953e16ff1.png)
![image-20210127154424008](https://user-images.githubusercontent.com/69343610/106572958-06d27680-6574-11eb-88df-9f70a64b9260.png)

**Comment by KomachiSion** [comment]
能麻烦用arthas抓一下火焰图吗？ 我在mac和linux环境测试是没有问题的。

**Comment by starfounder** [comment]
> 能麻烦用arthas抓一下火焰图吗？ 我在mac和linux环境测试是没有问题的。

目前 arthas 的 profiler 命令还不支持在 Windows 下执行，在 Windows 环境下无法用 arthas 抓取信息，有其他的方法吗

**Comment by KomachiSion** [comment]
window的话我不清楚，看下能否参考linux的

```
top -p pid -H 找到哪个或哪些线程占用高

jstack pid > stack.log  dump出线程

然后把第一步找到的tid转化成16进制，到stack.log中找一下是哪个线程，把那个线程的信息发出来

```

**Comment by shiyiyue1102** [comment]
我们发现是服务端的一个定时线程池的corePoolSize设置为0的问题，会在beta版本中修复

**Comment by xugcheng** [comment]
![image](https://user-images.githubusercontent.com/3348824/114545790-f5ea6380-9c8e-11eb-95ff-905e7342f510.png)
请问这个是什么情况
