### ISSUE TITLE
Nacos console still have ServiceManagement when start service with FUNCTION_MODE config

### ISSUE THREAD

**Issue by dlzht** [alibaba/nacos#4863]
**Describe the bug**
When start server with 'startup.sh -m standalone -f config', and access 127.0.0.1:8848/nacos, nacos console still contain ServiceManagement. I am not sure if it is reasonable.

**Expected behavior**
Nacos console does not have ServiceManagement, just like this [post](https://nacos.io/en-us/blog/nacos0.9.0.html) described. 

**Desktop (please complete the following information):**
 - OS: Arch
 - Version: nacos-server 1.4.1
 - browser: Firefox 85.0

**Additional context**
log start.out: 
- Nacos 1.4.1
- Running in stand alone mode, config function modules

**Comment by KomachiSion** [comment]
I'm not sure whether it show when only use one mode. 
@chuntaojun @yanlinly, What's the behavior before?

**Comment by grapeqin** [comment]
Nacos 2.0.3 
Ubuntu18

When I start nacos with command 'bash bin/startup.sh -m standalone -f config' then the logs/start.out print 
![image](https://user-images.githubusercontent.com/6265178/142578717-bf1c7078-258c-4cac-9394-8f9906e6e03f.png)

I try to verify naming service with ‘curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=192.168.89.99&port=8080'  ’ it return 'OK'

So I guess '-f' parameter is not effect，and the console also show naming service menu like this 
![image](https://user-images.githubusercontent.com/6265178/142579168-33b29524-02e9-4976-8aae-af1cb92c3c4f.png)

is that any thing wrong？

waiting for your reply， 

best regards ! Thanks.
