### ISSUE TITLE
2.0.0-ALPHA.2 如果用户没有 public 的读权限，auth 会 403

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#4867]
一开始的 get 配置会成功，动态修改配置 Listener 获取变更 ConfigBatchListenRequest 会 403
![image](https://user-images.githubusercontent.com/16837364/106739314-f2fe4180-6653-11eb-8b99-2c1f762c6304.png)

- readhk 用户没有 public 的读权限
![image](https://user-images.githubusercontent.com/16837364/106739586-483a5300-6654-11eb-8e66-efd8b7cf96ed.png)
![image](https://user-images.githubusercontent.com/16837364/106739658-5ab48c80-6654-11eb-9668-353b10e4a2ab.png)

**Comment by KomachiSion** [comment]
listen的配置是public的吗？ 把配置发一下。

**Comment by CherishCai** [comment]
```java
        Properties properties = new Properties();
        properties.put(PropertyKeyConst.SERVER_ADDR, "127.0.0.1:8848");
        properties.put(PropertyKeyConst.NAMESPACE, "antbank_hk");

        properties.put(PropertyKeyConst.USERNAME, "readhk");
        properties.put(PropertyKeyConst.PASSWORD, "xxxxxxxxxx");

        String context = configService.getConfigAndSignListener("global-dev.properties", "APP", 1000,
                new AbstractListener() {
                    @Override
                    public void receiveConfigInfo(String configInfo) {
                        System.out.println("configInfo = " + configInfo);
                    }
                });
```

**Comment by CherishCai** [comment]
> listen的配置是public的吗？ 把配置发一下。
        properties.put(PropertyKeyConst.SERVER_ADDR, "127.0.0.1:8848");
        properties.put(PropertyKeyConst.NAMESPACE, "antbank_hk");

        properties.put(PropertyKeyConst.USERNAME, "readhk");
        properties.put(PropertyKeyConst.PASSWORD, "xxxxxxxxxx");

dataId="global-dev.properties", 
group="APP"

**Comment by CherishCai** [comment]
> listen的配置是public的吗？ 把配置发一下。

一开始的 get 配置会成功，动态修改配置 Listener 获取变更 ConfigBatchListenRequest 会 403

**Comment by KomachiSion** [comment]
namespace是不是填错了，要填namespaceId？

**Comment by CherishCai** [comment]
> namespace是不是填错了，要填namespaceId？

没有的，我自定义的 id,  不是用自动生成的 uuid

**Comment by CherishCai** [comment]
对比过不同的账号哈，用另一个有 namespace=piblic 的账号可以正常，这个账号只有 namespace=antbank_hk  则不能监听更新

**Comment by KomachiSion** [comment]
所以你没有给这个账号public的权限？ 那肯定不能读啊。

**Comment by CherishCai** [comment]
> 所以你没有给这个账号public的权限？ 那肯定不能读啊。

properties.put(PropertyKeyConst.SERVER_ADDR, "127.0.0.1:8848");
properties.put(PropertyKeyConst.NAMESPACE, "antbank_hk");
properties.put(PropertyKeyConst.USERNAME, "readhk");
properties.put(PropertyKeyConst.PASSWORD, "xxxxxxxxxx");
dataId="global-dev.properties",
group="APP"


我仅仅需要读 namespace=antbank_hk 的，所以不需要授权 public 的权限；但是目前会  403

**Comment by KomachiSion** [comment]
antbank_hk 是 命名空间的展示名还是id？  客户端使用的时候需要传入的是namespaceId，而不是展示名。

**Comment by KomachiSion** [comment]
No more response from author, so we think the problem has been sovled. Close issue

**Comment by ldwnt** [comment]
> namespace是不是填错了，要填namespaceId？

我用的server/client都是2.0.3版本，服务刚启动时server端修改配置client端能自动刷新。第二天凌晨一点开始ConfigBatchListenRequest返回403 token expired。client端用了spring-cloud-starter-alibaba-nacos-config，配置文件里写了config的namespace name，请教下是配置问题还是bug？
