### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by 284263380** [alibaba/nacos#4874]
图片看不到,代码如下

```
System.out.println("@@@@@@@@@@@@@");
//这个地方是配置,这个数据很容易捕获
String serverAddr = "syxcools.com";
String dataId = "abc";
String group = "DEFAULT_GROUP";

//下面链接的时候,不需要密码,什么的,或者权限什么的
Properties properties = new Properties();
properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
ConfigService configService = NacosFactory.createConfigService(properties);
String content = configService.getConfig(dataId, group, 5000);
System.out.println("获取内容1:"+content);

//这个地方是修改数据
boolean isPublishOk = configService.publishConfig(dataId, group, "content");
System.out.println("发布状态:"+isPublishOk);
```

我想问一下,后台的这个配置,通过上面的代码,就可以修改,删除等操作,完全不需要用户(权限的)

这个安全吗?别人知道了我的地址,岂不是随意破坏了?

**Comment by 284263380** [comment]
![image](https://user-images.githubusercontent.com/7555386/106863764-efc28e80-6703-11eb-974c-8ffd5ba4c670.png)

**Comment by 284263380** [comment]
图片看不到,代码如下


 System.out.println("@@@@@@@@@@@@@");
        String serverAddr = "syxcools.com";
        String dataId = "abc";
        String group = "DEFAULT_GROUP";
        Properties properties = new Properties();
        properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
        ConfigService configService = NacosFactory.createConfigService(properties);
        String content = configService.getConfig(dataId, group, 5000);
        System.out.println("获取内容1:"+content);
        configService.addListener(dataId, group, new Listener() {
            @Override
            public void receiveConfigInfo(String configInfo) {
                System.out.println("@@@@@@@:recieve:" + configInfo);
            }

            @Override
            public Executor getExecutor() {
                return null;
            }
        });

        boolean isPublishOk = configService.publishConfig(dataId, group, "content");
        System.out.println("发布状态:"+isPublishOk);

**Comment by 284263380** [comment]
图片看不到,代码如下

System.out.println("@@@@@@@@@@@@@");
//这个地方是配置,这个数据很容易捕获
String serverAddr = "syxcools.com";
String dataId = "abc";
String group = "DEFAULT_GROUP";

//下面链接的时候,不需要密码,什么的,或者权限什么的
Properties properties = new Properties();
properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
ConfigService configService = NacosFactory.createConfigService(properties);
String content = configService.getConfig(dataId, group, 5000);
System.out.println("获取内容1:"+content);

//这个地方是修改数据
boolean isPublishOk = configService.publishConfig(dataId, group, "content");
System.out.println("发布状态:"+isPublishOk);

**Comment by haoyann** [comment]
sdk也是需要认证的

**Comment by Maijh97** [comment]
请问nacos server有开启权限吗？

**Comment by 284263380** [comment]
我就安装完,默认的public命名空间的数据就这么可以访问了

**Comment by Maijh97** [comment]
@284263380 https://nacos.io/zh-cn/docs/auth.html 麻烦仔细查看一下文档，确认相关权限的配置已经打开

**Comment by 284263380** [comment]
确实没有开,原来是我的问题
