### ISSUE TITLE
集群情况下 ，vpn的ip会自动增加到cluster.conf文件中

### ISSUE THREAD

**Issue by xuhui54** [alibaba/nacos#4879]
当有开启vpn的的情况下，nacos会自动把vpn的ip端口增加到cluster.conf中。由于vpn重启ip变化之前增加的值会一直存在需要手动删除

**Comment by KomachiSion** [comment]
多网卡（包括vpn等）环境 需要指定ip，否则可能读取错误的ip导致cluster信息有误

https://nacos.io/zh-cn/docs/deployment.html
