### ISSUE TITLE
从1.3.0升级到1.4.1后启动报IOException

### ISSUE THREAD

**Issue by startan** [alibaba/nacos#4884]
## 从1.3.0升级到1.4.1后启动报IOException

Type: *bug report*

提示java.io.IOException: User limit of inotify instances reached or too many open files

通过sysctrl -w fs.inotify.max_user_watchs=65536可以解决，但再次重启nacos又会再报异常，需要重启linux系统并重新执行上述命令才能解决。

**Comment by KomachiSion** [comment]
是否使用了derby数据库？

**Comment by startan** [comment]
> 是否使用了derby数据库？

我们nacos连的mysql数据库。

**Comment by KomachiSion** [comment]
信息太少了，无法判断问题，先查一下打开了哪些文件句柄把 是连接还是文件。

**Comment by KomachiSion** [comment]
No more response from author and current information is not enough.
