### ISSUE TITLE
服务名去除GROUP@@前缀的优化建议

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#4885]
由于Nacos注册中心会自动把服务名处理成GROUP@@SERVICE_ID的格式，导致根据服务名去获取一些相关数据，会无法找到，用户侧需要手工把该前缀去除，才能使该逻辑处理正确

**Comment by KomachiSion** [comment]
v1的接口考虑到兼容性应该会继续保留。
v2的接口可以考虑把groupName和serviceName分离开
