### ISSUE TITLE
注册的服务前端没有分页，后端分页了！

### ISSUE THREAD

**Issue by whiteHeisenberg** [alibaba/nacos#4887]
<img width="1318" alt="截屏2021-02-05 下午3 46 10" src="https://user-images.githubusercontent.com/39074195/107004575-755c4200-67c9-11eb-8384-44db8405cd7c.png">

注册10个以上的服务，只显示10个，看接口是分页，但是前端没有分页的可选项。

**Comment by whiteHeisenberg** [comment]
页面是服务详情页面，接口是http://localhost:8848/nacos/v1/ns/catalog/instances

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/107133904-0c3f1080-6928-11eb-95ff-d957cd790f3a.png)
请清理浏览器缓存后重试。 我看是有的。

**Comment by PEIYANGXINQU** [comment]
服务有分页，进去详情里面的实例没有分页
