### ISSUE TITLE
Nacos 1.4.1在Linux服务器上部署后出现CPU飙升100%的情况

### ISSUE THREAD

**Issue by xqnode** [alibaba/nacos#4889]
Type: bug report

在腾讯云服务器上安装nacos1.4.1版本，单机启动会立即出现CPU100%的情况

启动脚本：`./startup.sh -m standalone`

<img src="https://upload-images.jianshu.io/upload_images/16442320-e7a2382639e28874.png" />

启停了好几次，但是问题仍未解决。

jstack定位到错误在这里：

<img src="https://upload-images.jianshu.io/upload_images/16442320-47ca2c1157628a53.png" />

但是找不到问题的根本原因在哪。

切换到 nacos-1.4.0版本没有出现上述问题。

有知道解决方案的小伙伴麻烦告知一下，谢谢！

**Comment by KomachiSion** [comment]
你确定是1.4.1？ 这个线程应该是2.0才有的。 是一个bug 已经修复了。

**Comment by KomachiSion** [comment]
duplicate with #4855

**Comment by xqnode** [comment]
> 你确定是1.4.1？ 这个线程应该是2.0才有的。 是一个bug 已经修复了。

确定啊，我下载的1.4.1版本
