### ISSUE TITLE
[#4701] 1.4.1版本开启认证以“/”结尾的问题，直接下载jar包启动好使，但下载源码编译完还会出现这问题bug依然存在

### ISSUE THREAD

**Issue by wangyuanfeng2018** [alibaba/nacos#4890]
1.4.1版本开启认证以“/”结尾的问题，直接下载jar包启动好使，
但下载源码编译完后启动，以"/"结尾仍然可以跳过认证

**Comment by wangyuanfeng2018** [comment]
1.4.1的tag里的源码，并没有修复[#4701]的bug，只能clone开发分支么

**Comment by KomachiSion** [comment]
tag未包含hotfix， 这个问题是后续的hotfix修复的。因为 github tag一旦标记就不能更改了。

**Comment by KomachiSion** [comment]
如果需要二次开发，可以使用cherry-pick把2个相关的修复PR自行移动到您的fock分支下进行。
