### ISSUE TITLE
源码报错

### ISSUE THREAD

**Issue by xny838754132** [alibaba/nacos#4894]
源码报错:
package com.alibaba.nacos.consistency.ConsistencyProtocol接口中引入的包
com.alibaba.nacos.consistency.entity.*不存在

**Comment by haoyann** [comment]
编译一下 mvn clean compile

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/faq.html

**Comment by xny838754132** [comment]
找到原因了 我把报错的maven从本地仓库删了 重新导入了一下就好了
