### ISSUE TITLE
Nacos 源码修改，同时支持 MySQL 和 PostgreSQL

### ISSUE THREAD

**Issue by tudan110** [alibaba/nacos#4896]
项目使用 Nacos 作为注册中心和配置中心，要求使用 PostgreSQL，Nacos 官方仅支持 MySQL，网上也没有找到可用的魔改版本，故自己花几个小时的时间魔改一下。目前我们团队已经使用上啦，希望能够帮助到大家，后续我会持续更新哒。

1. 博文请参考：https://tudan.blog.csdn.net/article/details/113400766
2. github：https://github.com/tudan110/nacos

The project uses Nacos as the registration center and configuration center, and requires the use of PostgreSQL. Nacos officially only supports MySQL, and there is no available magic version on the Internet, so I spend a few hours to modify it. At present, our team has already used it. I hope to help you. I will continue to update it in the future. 

1. For blog posts, please refer to: https://tudan.blog.csdn.net/article/details/113400766
2. github: https://github.com/tudan110/nacos

**Comment by tudan110** [comment]
pgsql 版本在 wangtan-dev 分支里

**Comment by KomachiSion** [comment]
可以试用一下multiple-datasource那个开发分支

**Comment by tudan110** [comment]
> 可以试用一下 multiple-datasource 那个开发分支

ok，看到啦

**Comment by jfly-cloud** [comment]
更新下2.0.3的postgresql代码，多谢。

**Comment by yazong** [comment]
请问改了哪些文件可以说一下吗
