### ISSUE TITLE
cpu 占用过高,出现大量日志,请求官网(版本 :  2.0.0-BETA (Feb 5th, 2021 )

### ISSUE THREAD

**Issue by bravelionet** [alibaba/nacos#4899]
本地测试 2核4G 阿里云服务器, 集群版 nacos 占用 cpu 85%(忘记截图), 当我停下 nacos后,cpu占用率直线下降, 本菜鸟看日志像是心跳,但 心跳出现频率 1秒可出现数条(两个节点注册情况下)

**日志如下 : (ip 地址已伪装, 部分日志)**
222.111.111.111 - - [07/Feb/2021:16:45:39 +0800] "PUT /nacos/v1/ns/instance/beat?app=unknown&serviceName=DEFAULT_GROUP%40%40bl-blog-dispatch&namespaceId=public&port=9090&clusterName=DEFAULT&ip=222.111.111.122 HTTP/1.0" 200 64 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:40 +0800] "PUT /nacos/v1/ns/instance/beat?app=unknown&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&namespaceId=public&port=9095&clusterName=DEFAULT&ip=222.111.111.122 HTTP/1.0" 200 64 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:41 +0800] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.186.1&serviceName=DEFAULT_GROUP%40%40bl-blog-dispatch&udpPort=65395&clusters=DEFAULT HTTP/1.0" 200 504 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:42 +0800] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.186.1&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&udpPort=65395&clusters= HTTP/1.0" 200 495 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:42 +0800] "GET /nacos/v1/cs/configs?show=all&dataId=bl-blog-dispatch.yml&group=DEFAULT_GROUP&tenant=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 347 35 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:45:44 +0800] "PUT /nacos/v1/ns/instance/beat?app=unknown&serviceName=DEFAULT_GROUP%40%40bl-blog-dispatch&namespaceId=public&port=9090&clusterName=DEFAULT&ip=222.111.111.122 HTTP/1.0" 200 64 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:45 +0800] "GET /nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs HTTP/1.0" 200 1138 57 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:45:46 +0800] "PUT /nacos/v1/ns/instance/beat?app=unknown&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&namespaceId=public&port=9095&clusterName=DEFAULT&ip=222.111.111.122 HTTP/1.0" 200 64 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:47 +0800] "GET /nacos/v1/cs/configs?show=all&dataId=bl-blog-dispatch.yml&group=blog_grep&tenant=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 363 47 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:45:49 +0800] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.186.1&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&udpPort=60364&clusters=DEFAULT HTTP/1.0" 200 502 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:49 +0800] "PUT /nacos/v1/ns/instance/beat?app=unknown&serviceName=DEFAULT_GROUP%40%40bl-blog-dispatch&namespaceId=public&port=9090&clusterName=DEFAULT&ip=222.111.111.122 HTTP/1.0" 200 64 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:51 +0800] "PUT /nacos/v1/ns/instance/beat?app=unknown&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&namespaceId=public&port=9095&clusterName=DEFAULT&ip=222.111.111.122 HTTP/1.0" 200 64 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:51 +0800] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.186.1&serviceName=DEFAULT_GROUP%40%40bl-blog-dispatch&udpPort=65395&clusters=DEFAULT HTTP/1.0" 200 504 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:52 +0800] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.186.1&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&udpPort=65395&clusters= HTTP/1.0" 200 495 2 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:54 +0800] "GET /nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs HTTP/1.0" 200 1138 37 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:45:55 +0800] "DELETE /nacos/v1/ns/instance?app=unknown&namespaceId=public&port=9090&clusterName=DEFAULT&ip=222.111.111.122&ephemeral=true&serviceName=DEFAULT_GROUP%40%40bl-blog-dispatch HTTP/1.0" 200 2 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:55 +0800] "DELETE /nacos/v1/ns/instance?app=unknown&namespaceId=public&port=9095&clusterName=DEFAULT&ip=222.111.111.122&ephemeral=true&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter HTTP/1.0" 200 2 1 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:45:57 +0800] "GET /nacos/v1/cs/configs?show=all&dataId=bl-blog-dispatch-dev.yml&group=blog_grep&tenant=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 382 1030 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:45:59 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.0" 200 - 30955 Java/1.8.0_211 -
222.111.111.111 - - [07/Feb/2021:16:45:59 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.0" 200 - 30921 Java/1.8.0_211 -
222.111.111.111 - - [07/Feb/2021:16:45:59 +0800] "GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=public&clientIP=192.168.186.1&serviceName=DEFAULT_GROUP%40%40bl-blog-ucenter&udpPort=60364&clusters=DEFAULT HTTP/1.0" 200 191 2 Nacos-Java-Client:v1.4.1 -
222.111.111.111 - - [07/Feb/2021:16:46:00 +0800] "GET /nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs HTTP/1.0" 200 1138 50 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:46:04 +0800] "GET /nacos/v1/cs/configs?show=all&dataId=bl-blog-global-common.yml&group=common_defalt_grep&tenant=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 764 46 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:46:29 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.0" 200 - 29945 Java/1.8.0_211 -
222.111.111.111 - - [07/Feb/2021:16:46:29 +0800] "POST /nacos/v1/cs/configs/listener HTTP/1.0" 200 - 29944 Java/1.8.0_211 -
222.111.111.111 - - [07/Feb/2021:16:50:21 +0800] "GET /nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs HTTP/1.0" 200 1138 38 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:50:40 +0800] "GET /nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=10&serviceNameParam=&groupNameParam=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 28 1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:50:47 +0800] "GET /nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=accurate&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs HTTP/1.0" 200 1138 888 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:50:49 +0800] "GET /nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=10&serviceNameParam=&groupNameParam=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 28 2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:50:52 +0800] "GET /nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=10&serviceNameParam=&groupNameParam=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 28 2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:50:54 +0800] "GET /nacos/v1/console/namespaces?&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 119 817 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:50:57 +0800] "GET /nacos/v1/core/cluster/nodes?withInstances=false&pageNo=1&pageSize=10&keyword=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3YW5nc3giLCJleHAiOjE2MTI3MDUzMDJ9.ICDBzLBL30q7IH90ANisBW1Le28KLfpVup-UP6nUejs&namespaceId= HTTP/1.0" 200 758 2 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36 -
222.111.111.111 - - [07/Feb/2021:16:54:04 +0800] "GET /nacos/index.html HTTP/1.0" 304 - 2 Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 -

**Comment by 284263380** [comment]
我今天也发现了.我的一个奇怪的现象是  当时我浏览器白色的空白(后来感觉是可能由于用了不小心切换到ie了),但是当时不知道为什么,后来去服务器上看log,发现 tailf config-client-request.log ,发现这个文件一直在写log(一秒写两三行的速度),类似这样:
2021-02-07 17:37:54,705|0|null|180.168.126.126|get|test_003|DEFAULT_GROUP|public|9a0364b9e99bb480dd25e1f0284c8555|unknown

我当时只注意后面那个是unknown,前面是什么没印象了(这个是正确的log,之前的log清除了),我当时还好奇,要是这么打log,岂不是磁盘根本不够用

**Comment by KomachiSion** [comment]
看日志是正常的，每个实例的心跳是5s一个。

cpu高能否用arthas抓一下火焰图，看下是什么线程占了大量CPU？

**Comment by KomachiSion** [comment]
no more response from author, and no enough information
