### ISSUE TITLE
publishConfig的时候指定NAMESPACE=public无效

### ISSUE THREAD

**Issue by 284263380** [alibaba/nacos#4900]
修改配置如果是修改public的时候,
如果指定
properties.put(PropertyKeyConst.NAMESPACE, "public");
则无法修改,publishConfig(...)的返回值是true,但是去后台看,修改,添加无效

properties.put(PropertyKeyConst.NAMESPACE, "public");这个登录配置不指定命名空间(使用默认的),
publishConfig是ok的,
这个有点奇怪呀,

**Comment by KomachiSion** [comment]
public只是命名空间的展示名字，namespaceId是""。 如果想要用默认命名空间，可以不输入此参数。客户端会自动使用默认命名空间

**Comment by 284263380** [comment]
晓得了,不过这个也很奇怪,应该namespaceId 也默认成public更好

**Comment by xluckly** [comment]
我实验了 好多次都没有更新 发现只要指定namespace 为public就不能更新

**Comment by wuwen5** [comment]
> public只是命名空间的展示名字，namespaceId是""。 如果想要用默认命名空间，可以不输入此参数。客户端会自动使用默认命名空间

这个很容易误导人啊，例如 dubbo-admin 中默认配置
```
#namespace used by nacos
admin.registry.namespace=public
admin.config-center.namespace=public
admin.metadata-report.namespace=public
```
而 nacos 默认namespace也是public, 认为是一致的，结果调代码才发现 nacos config表中匹配的tenant为”“，
界面显示的public对应的是"", 而dubbo-admin 存入的是public.
😔
