### ISSUE TITLE
nacos1.4.1 多环境无法配置多命名空间

### ISSUE THREAD

**Issue by chq1024** [alibaba/nacos#4901]
命名空间通常设置为dev,test,pro，但在公司使用过程中，部分配置为通用配置，通常设置为comment.yml，开发环境特殊配置设置为xxx-dev.yml,除多种环境外会有此项目固定配置，通常以xxx.yml设置，此时需要配置多个关联配置文件，但nacos不支持一个项目多个命名空间跨调，一个命名空间下如果放置多个项目会显得很乱。
综上所述，如果多命名空间支持跨调，就会便于设置命名空间为一个项目，可避免跨空间

**Comment by KomachiSion** [comment]
多命名空间不支持跨调。命名空间是强隔离属性。
