### ISSUE TITLE
[集群+MySQL]配置数据在服务器异常宕机场景存在不一致问题

### ISSUE THREAD

**Issue by iamhuzl** [alibaba/nacos#4906]
**Describe the bug**
在集群模式+MySQL外部存储部署方式场景下，发布配置时若出现存储到MySQL成功但通知其他server失败，配置界面查询返回最新数据，查询接口返回老数据
In the scenario of cluster mode +MySQL external storage deployment, when publishing configuration, if the storage to MySQL succeeds but other servers fail to be notified, the configuration interface query will return the latest data, and the config query api will return the old data

**Expected behavior**
修改数据库成功，配置查询接口未返回最新数据，保证数据最终一致性
Modify database successfully, config query api does not return the latest data, ensure the final consistency of data
**Acutally behavior**
The config query api interface does not return the latest data, which cannot guarantee the final consistency of the data

**How to Reproduce**
1. 启动三个节点A,B,C集群
2. 在A节点在ConfigController的publishConfig方法中ConfigChangePublisher.notifyConfigChange设置断点
3. 使用A节点IP修改配置数据
4. 停止A节点Nacos进程
5. 访问其他节点配置数据，未修改成功

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version nacos-server 1.4.2-SNAPSHOT
 - Module config

**Additional context**
建议加入数据库增量轮询机制，不完全依赖server间通知机制或采用其他一致性数据存储方案
It is recommended to add database incremental polling mechanism, which does not completely rely on inter-server notification mechanism or other consistent data storage mechanism

**Comment by horizonzy** [comment]
确认一下。是修改配置还是新增配置？在A节点操作之前其他两个节点有数据吗？

**Comment by iamhuzl** [comment]
> 确认一下。是修改配置还是新增配置？在A节点操作之前其他两个节点有数据吗？

修改配置，我的理解只要请求发送A节点，但有其他节点未通知到，然后A点宕机就出现这种情况。

**Comment by horizonzy** [comment]
是有这种问题。你说的这个问题如果A是挂了，没有通知到B，C。数据库的值是变了的，在控制台中获取的数据是数据库的数据。通过客户端去获取的数据是本地的文件，因为本地文件没有收到B，C节点的通知，数据会是老的。
不过对于客户端来说，整个集群中的数据其实是一致的。B,C的数据通过客户端去获取，都是老的数据，只是控制台显示的值对不上。

对于这种情况，现在有补偿机制, 每6个小时去从db中拉取最新的db的数据来更新本地的数据。

**Comment by iamhuzl** [comment]
这种一致性方案不太可靠，也可能通知其中一台如B后A宕机或A通知失败后重启，都有可能导致集群不一致性

**Comment by shiyiyue1102** [comment]
> 这种一致性方案不太可靠，也可能通知其中一台如B后A宕机或A通知失败后重启，都有可能导致集群不一致性
> 写入过程中落本地文件系统+写入集中存储+通知集群，这三步任意一个步骤都可能失败，6个小时补偿时间过长了

现在的一致性方案确实存在你说的这个问题，计划后面的版本中会增加定时增量比对的功能，来缩短不一致的时间窗口
