### ISSUE TITLE
长轮询的异步任务使用多线程处理

### ISSUE THREAD

**Issue by superstarchenxin** [alibaba/nacos#4907]
**Is your feature request related to a problem? Please describe.**
为什么nacos-config-server处理longPolling的异步线程只是使用newSingleScheduledExecutorService，是不是提升成多个线程来处理更优？
![image](https://user-images.githubusercontent.com/8651857/107453557-29711a80-6b86-11eb-8c22-f84dde3d990b.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chuntaojun** [comment]
The number of thread pool workers here can indeed be adjusted

**Comment by superstarchenxin** [comment]
我这边想到的解决方案：
a. 是不是可以做一个参数配置，根据使用场景，配置合适的线程池？
b. 把原来LongPolling线程池独立两个线程池
  a) 一个处理LongPolling
  b) 另一个处理DataChangeTask

**Comment by superstarchenxin** [comment]
> The number of thread pool workers here can indeed be adjusted

请问接下来是需要提交代码，进来下一阶段的讨论 和 优化吗?

**Comment by JackSun-Developer** [comment]
>a. 是不是可以做一个参数配置，根据使用场景，配置合适的线程池？
这个值得商榷，参数配置交给用户来设置，可能会增大nacos新用户的学习成本。

**Comment by superstarchenxin** [comment]
> > a. 是不是可以做一个参数配置，根据使用场景，配置合适的线程池？
> 
> 我觉得这个值得商榷，参数配置交给用户来设置，可能会增大nacos新用户的学习成本。

那直接在新版本提升连接池数量？

**Comment by shiyiyue1102** [comment]
这个线程同时处理了三种任务，一个是统计任务，10秒执行一次，一个是长轮询请求返回，这个和长链接数量有关，一个是数据变更通知线程，这个和数据变更频率有关，压力最大的应该是第二种，是每隔30秒执行一轮，具体要看实际的场景是否产生了压力了，现在阿里内部单机1万长链接，也是使用单线程处理，在系统没有出现频繁gc停顿的情况下，整体是正常的

**Comment by shiyiyue1102** [comment]
> > > a. 是不是可以做一个参数配置，根据使用场景，配置合适的线程池？
> > 
> > 
> > 我觉得这个值得商榷，参数配置交给用户来设置，可能会增大nacos新用户的学习成本。
> 
> 同意，这种内部细节直接对用户透明吧！那可以直接在新版本提升线程池的线程数量？下一步是commit吗

调大线程数可能并不能带来明显的优化效果，2.0版本里已经使用grpc长链接了，不再使用http长轮询，可以看看2.0代码里有没有类似优化的点，拥抱2.0吧

**Comment by superstarchenxin** [comment]
> 这个线程同时处理了三种任务，一个是统计任务，10秒执行一次，一个是长轮询请求返回，这个和长链接数量有关，一个是数据变更通知线程，这个和数据变更频率有关，压力最大的应该是第二种，是每隔30秒执行一轮，具体要看实际的场景是否产生了压力了，现在阿里内部单机1万长链接，也是使用单线程处理，在系统没有出现频繁gc停顿的情况下，整体是正常的

请教下为什么需要让这个线程做三种不同类型的工作？从代码实现和监控运维角度，独立出不同的线程池是否更加合适

**Comment by superstarchenxin** [comment]
> > > > a. 是不是可以做一个参数配置，根据使用场景，配置合适的线程池？
> > > 
> > > 
> > > 我觉得这个值得商榷，参数配置交给用户来设置，可能会增大nacos新用户的学习成本。
> > 
> > 
> > 同意，这种内部细节直接对用户透明吧！那可以直接在新版本提升线程池的线程数量？下一步是commit吗
> 
> 调大线程数可能并不能带来明显的优化效果，2.0版本里已经使用grpc长链接了，不再使用http长轮询，可以看看2.0代码里有没有类似优化的点，拥抱2.0吧

拥抱2.0肯定是大势所趋，但基础中间件的升级肯定不是一蹴而就的，请教下长轮询方式的支持优化，社区是怎么考虑的？

**Comment by shiyiyue1102** [comment]
> 不是

当前单线程并不会出现明显的性能问题，旧版长轮询模式下在无重大bug情况下不做更新了
