### ISSUE TITLE
配置格式丢失Configuration format missing.

### ISSUE THREAD

**Issue by zhangyu-think** [alibaba/nacos#4908]
**Describe the bug**
Configuration format missing.
配置格式丢失。

**Expected behavior**
Display configuration format.
显示配置格式。

**How to Reproduce**
1.Go to 'Configuration list'
进入配置列表
2.Add a new configuration
新增一条配置
3.Select yaml for configuration format
配置格式选择yaml
4.Click publish
点击发布
5.Then edit the newly released configuration
然后编辑这条刚刚发布的配置
6.The configuration format was found to be empty and no configuration format was selected
发现配置格式为空，没有选择任何配置格式
[See the screenshot](http://chuantu.xyz/t6/741/1612927560x1700340463.png)
**Desktop (please complete the following information):**
- OS: [Centos7.6]
- Version [nacos-server-1.4.0]

**Additional context**
I refer to the official documents to configure the cluster and use the built-in data source.
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html
我参考官方文档配置了集群，使用了内置数据源
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

**Comment by haoyann** [comment]
duplicate #4570

**Comment by zhangyu-think** [comment]
thanks
