### ISSUE TITLE
RefreshScope和value 必须同时使用的时候才能热加载实时数据。

### ISSUE THREAD

**Issue by muranjack** [alibaba/nacos#4909]
> 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩 两个必须一起用才生效，这也太麻烦了吧！！！

----
我也是1.4.1升级后发现这个问题，今天找半天，，。我的代码springcloud版本没做任何改动，推测nacos1.4.1引入的问题？

_Originally posted by @610983691 in https://github.com/alibaba/nacos/issues/1960#issuecomment-773860938_

**Comment by saxingz** [comment]
我是直接升级的1.4.1版本，也是这个问题。
控制台收到消息了，但是@Value的值没有热更新

**Comment by bastYYJ** [comment]
一直都要这样使用吧？不然都不会刷新的

**Comment by muranjack** [comment]
看一下SpringCloud版本和SpringBoot版本，新版需要添加bootstarp的启动依赖

**Comment by saxingz** [comment]
> 看一下SpringCloud版本和SpringBoot版本，新版需要添加bootstarp的启动依赖

你解决了？加什么bootstrap?  
我的cloud是Hoxton.SR10， boot是2.3.8.RELEASE

**Comment by muranjack** [comment]
<dependency&gt;
    <groupId&gt;org.springframework.cloud</groupId&gt;
    <artifactId&gt;spring-cloud-starter-bootstrap</artifactId&gt;
</dependency&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年2月20日(星期六) 中午11:36
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "是是是"<yangtao96@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] 我也是这个版本但不生效，脑壳痛&gt; 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩=?UTF-8?Q?_=E4=B8=A4=E4=B8=AA=E5=BF=85=E9=A1=BB=E4=B8=80=E8=B5=B7=E7=94=A8=E6=89=8D=E7=94=9F=E6=95=88=EF=BC=8C=E8=BF=99=E4=B9=9F=E5=A4=AA=E9=BA=BB





  
看一下SpringCloud版本和SpringBoot版本，新版需要添加bootstarp的启动依赖
  
你解决了？加什么bootstrap?
 我的cloud是Hoxton.SR10， boot是2.3.8.RELEASE

**Comment by saxingz** [comment]
> <dependency&gt; <groupId&gt;org.springframework.cloud</groupId&gt; <artifactId&gt;spring-cloud-starter-bootstrap</artifactId&gt; </dependency&gt;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年2月20日(星期六) 中午11:36 收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 抄送: "是是是"<yangtao96@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [alibaba/nacos] 我也是这个版本但不生效，脑壳痛&gt; 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩=?UTF-8?Q?_=E4=B8=A4=E4=B8=AA=E5=BF=85=E9=A1=BB=E4=B8=80=E8=B5=B7=E7=94=A8=E6=89=8D=E7=94=9F=E6=95=88=EF=BC=8C=E8=BF=99=E4=B9=9F=E5=A4=AA=E9=BA=BB 看一下SpringCloud版本和SpringBoot版本，新版需要添加bootstarp的启动依赖 你解决了？加什么bootstrap? 我的cloud是Hoxton.SR10， boot是2.3.8.RELEASE — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

加了，还是不能做到热刷新，必须要加@RefreshScope。
再确认一下，你是加了这个bootstrap，就可以热刷新了？

**Comment by muranjack** [comment]
是的，@Value我也加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年2月20日(星期六) 中午12:02
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "是是是"<yangtao96@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] 我也是这个版本但不生效，脑壳痛&gt; 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩=?UTF-8?Q?_=E4=B8=A4=E4=B8=AA=E5=BF=85=E9=A1=BB=E4=B8=80=E8=B5=B7=E7=94=A8=E6=89=8D=E7=94=9F=E6=95=88=EF=BC=8C=E8=BF=99=E4=B9=9F=E5=A4=AA=E9=BA=BB





  
<dependency&gt; <groupId&gt;org.springframework.cloud</groupId&gt; <artifactId&gt;spring-cloud-starter-bootstrap</artifactId&gt; </dependency&gt;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年2月20日(星期六) 中午11:36 收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 抄送: "是是是"<yangtao96@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [alibaba/nacos] 我也是这个版本但不生效，脑壳痛&gt; 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩=?UTF-8?Q?_=E4=B8=A4=E4=B8=AA=E5=BF=85=E9=A1=BB=E4=B8=80=E8=B5=B7=E7=94=A8=E6=89=8D=E7=94=9F=E6=95=88=EF=BC=8C=E8=BF=99=E4=B9=9F=E5=A4=AA=E9=BA=BB 看一下SpringCloud版本和SpringBoot版本，新版需要添加bootstarp的启动依赖 你解决了？加什么bootstrap? 我的cloud是Hoxton.SR10， boot是2.3.8.RELEASE — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
加了，还是不能做到热刷新，必须要加@RefreshScope。
 再确认一下，你是加了这个bootstrap，就可以热刷新了？

**Comment by saxingz** [comment]
> 是的，@value我也加了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年2月20日(星期六) 中午12:02 收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 抄送: "是是是"<yangtao96@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [alibaba/nacos] 我也是这个版本但不生效，脑壳痛&gt; 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩=?UTF-8?Q?_=E4=B8=A4=E4=B8=AA=E5=BF=85=E9=A1=BB=E4=B8=80=E8=B5=B7=E7=94=A8=E6=89=8D=E7=94=9F=E6=95=88=EF=BC=8C=E8=BF=99=E4=B9=9F=E5=A4=AA=E9=BA=BB <dependency&gt; <groupId&gt;org.springframework.cloud</groupId&gt; <artifactId&gt;spring-cloud-starter-bootstrap</artifactId&gt; </dependency&gt; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "notifications"<notifications@github.com&gt;; 发送时间: 2021年2月20日(星期六) 中午11:36 收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 抄送: "是是是"<yangtao96@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [alibaba/nacos] 我也是这个版本但不生效，脑壳痛&gt; 我升级了最新版本 1.4.1 好像是@RefreshScope和@value 必须同时使用的时候才能热加载实时数据。但是以前1.3.0的时候 没有这个限制，不知道是不是又是一个新的bug。如果按照现在这个规矩=?UTF-8?Q?_=E4=B8=A4=E4=B8=AA=E5=BF=85=E9=A1=BB=E4=B8=80=E8=B5=B7=E7=94=A8=E6=89=8D=E7=94=9F=E6=95=88=EF=BC=8C=E8=BF=99=E4=B9=9F=E5=A4=AA=E9=BA=BB 看一下SpringCloud版本和SpringBoot版本，新版需要添加bootstarp的启动依赖 你解决了？加什么bootstrap? 我的cloud是Hoxton.SR10， boot是2.3.8.RELEASE — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 加了，还是不能做到热刷新，必须要加@RefreshScope。 再确认一下，你是加了这个bootstrap，就可以热刷新了？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


spring-cloud-starter-bootstrap 应该是升级到2020版本才用的，目前我才H版本，默认就是有的。
https://spring.io/blog/2020/10/07/spring-cloud-2020-0-0-m4-aka-ilford-is-available
问题还是没有解决  233

**Comment by KomachiSion** [comment]
这里有两个区别，如果是spring-boot 必须使用RefreshScope， 因为boot的value是没有自动更新功能的。

如果是spring-cloud 理论上只需要value， 自动刷新能力是spring-cloud提供的，不是nacos提供的，如果出现无法更新配置的问题，需要提issue到spring-cloud的社区。

**Comment by saxingz** [comment]
> 这里有两个区别，如果是spring-boot 必须使用RefreshScope， 因为boot的value是没有自动更新功能的。
> 
> 如果是spring-cloud 理论上只需要value， 自动刷新能力是spring-cloud提供的，不是nacos提供的，如果出现无法更新配置的问题，需要提issue到spring-cloud的社区。

你看也挺多人反映这个问题的，我们是从Apollo迁移过来的，Apollo自动刷新很正常。nacos突然少了这个功能，很多地方都要改，麻烦还挺大的。
建议nacos也保证一下自动刷新，你们评估一下？

**Comment by KomachiSion** [comment]
但是这个不是nacos而是spring cloud的能力，nacos如果已经把新配置推送到客户端上了，回调spring cloud之后，就是spring-cloud的工作了。

**Comment by KomachiSion** [comment]
@saxingz 我刚和spring-cloud-alibaba社区沟通了一下， 他们表示是需要指定RefreshScope的。

原因是从设计上，配置刷新是一个比较大的行为，spring cloud的设计上 刷新不仅仅是把配置内容进行变更，而是整个bean对象发生了替换（需要重新生成），因为为了避免大量bean刷新导致程序运行问题，需要用户显示标记哪些bean是允许自动刷新的。

如果希望只是用@Value进行刷新， 可以提issue到spring-cloud-alibaba社区上进行讨论。
