### ISSUE TITLE
nacos server升级相关问题

### ISSUE THREAD

**Issue by catalpa-tree** [alibaba/nacos#4911]
问题一：nacos server由1.1.3升级到1.4.1,nacos client也要同时由1.1.1版本升级到1.4.1版本吗？可以继续使用1.1.1版本吗？升级顺序是先升级server还是client，还是要同时？ 
问题二：server端升级是直接替换jar包后重启吗？还需要删除什么文件吗？

**Comment by zhaidw** [comment]
一般来说是先升级服务端。
我觉得可以单独搭建个测试环境测试，没问题后操作线上环境。

**Comment by KomachiSion** [comment]
理论上1.X的服务端向下兼容所有1.X的客户端。
