### ISSUE TITLE
服务启动频繁full gc，hostReactor 被创建多个相同的对象

### ISSUE THREAD

**Issue by xiaoshun007** [alibaba/nacos#4914]
## Issue Description
com.alibaba.nacos.client.naming.core.HostReactor
292 objects
请问下，我们在使用nacos的过程中，有一个服务启动时创建了292个相同的HostReactor对象
nacos 版本1.4.1
spring cloud alibaba 2.2.3.RELEASE

![image](https://user-images.githubusercontent.com/7384775/108344215-d5b2a100-7217-11eb-9b9f-ae3addc3375f.png)
![image](https://user-images.githubusercontent.com/7384775/108344224-d6e3ce00-7217-11eb-97e1-cf41d1ee7426.png)
![image](https://user-images.githubusercontent.com/7384775/108344284-e95e0780-7217-11eb-97c4-96a9fa5a4f45.png)
![image](https://user-images.githubusercontent.com/7384775/108344322-f549c980-7217-11eb-995e-a777430674d3.png)

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
服务提供者可以启动，在启动服务消费者时，频繁full gc，jmap 如上图
top CPU线程是gc线程
![image](https://user-images.githubusercontent.com/7384775/108344684-68ebd680-7218-11eb-86be-1d724e211d27.png)
![image](https://user-images.githubusercontent.com/7384775/108344718-73a66b80-7218-11eb-8500-a722014acf58.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos  1.4.1
spring cloud alibaba 2.2.3.RELEASE

**Comment by KomachiSion** [comment]
291个NacosRegister？

问题出在这， 反馈到spring-cloud-alibaba吧。或者看下是不是你的使用方法有问题。理论上不应该有这个么多NacosRegister。

**Comment by KomachiSion** [comment]
No more response from author, and this problem is not nacos' problem
