### ISSUE TITLE
1.4.1: Nacos web console doesn't have Authority Control

### ISSUE THREAD

**Issue by mingleLoL** [alibaba/nacos#4916]
**Describe the bug**
1. deploy nacos standalone with mysql 5.7 using nacos-docker 1.4.1
2. login with username nacos and check

**Expected behavior**
Have correct access to Authority Control and have permission to access namespace public like below
![image](https://user-images.githubusercontent.com/18515285/108452090-db08fd80-72a2-11eb-84e2-6b5b2b13c747.png)

**Acutally behavior**
don't have Authority Controll access
![image](https://user-images.githubusercontent.com/18515285/108451682-34246180-72a2-11eb-944d-0052714775fe.png)
and correct role in mysql db
![image](https://user-images.githubusercontent.com/18515285/108451929-a09f6080-72a2-11eb-94a6-340ef1195dbd.png)

**How to Reproduce**
just deploy nacos via standalone mode and add NACOS_AUTH_ENABLE=true in nacos-standlone-mysql.env file.
also tried adding below info to conf/application.properites in docker container and restart.
![image](https://user-images.githubusercontent.com/18515285/108452342-4a7eed00-72a3-11eb-9b4e-569f0497a14d.png)

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Version: nacos server 1.4.1
 - Module: naming
 - SDK: NA

**Additional context**
I deployed another nacos, it works, but the one with this issue is prod env, i wanna get more info to fix it. At present I make a temp workaround that create another account from database.

**Comment by KomachiSion** [comment]
I can't reproduce this problem in my local env.

can you provider auth control detail page?

**Comment by mingleLoL** [comment]
:( the key issue is I cannot see the auth control page(no auth control menu item in web page, the screenshot with access is from the one without issue), the another account I created to use doesn't have the auth control page either.
![image](https://user-images.githubusercontent.com/18515285/108951730-7fc07c00-76a3-11eb-9912-af07a8abc830.png)
![image](https://user-images.githubusercontent.com/18515285/108951768-92d34c00-76a3-11eb-980f-00c84459edc2.png)
If I change the account "yinming"'s role to GLOBAL_ADMIN, the issue I told is still reproduced.

I doubt if the issue could be related with the env config, so I'd like to be given with any clues to produce this problem like network config etc.

**Comment by KomachiSion** [comment]
Can you have a try change the `role` as `ROLE_ADMIN` ？

**Comment by mingleLoL** [comment]
> Can you have a try change the `role` as `ROLE_ADMIN` ？

great, it works, and I rechecked the one without issue, it is "ROLE_AMDIN" indeed. the only difference with the two server I installed is that the good one is install by upgrade. perhaps the install shell has some problem. 

Anyway, the issue is resolved and thanks a lot:)
