### ISSUE TITLE
如何修改nacos管理服务的接口超时配置

### ISSUE THREAD

**Issue by weiweigaoshan** [alibaba/nacos#4918]
我有个接口数据返回时间超过30s了，通过单纯的swagger访问能够返回数据，但是通过8868/服务名 访问就报timeout ，我想请问下如何修改配置才能让接口返回不超时。

**Comment by KomachiSion** [comment]
是哪个接口？ 我认为30s不返回应该是有问题的。

如果确实需要长时间返回。那么客户端可以使用 `-Dcom.alibaba.nacos.client.naming.rtimeout=xxxx` 设置。 默认是50000ms

**Comment by weiweigaoshan** [comment]
谢谢指导，已解决；
