### ISSUE TITLE
项目中没有使用Spring Cloud只使用了Spring Boot，是否可以使用${prefix}-${spring.profiles.active}.${file-extension}该方式配置？

### ISSUE THREAD

**Issue by wushuaiping** [alibaba/nacos#4924]
## Issue Description
我的pom.xml:
```xml
  <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
...
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-gateway</artifactId>
                <version>3.0.1</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Hoxton.SR10</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
...
```
我的Application启动类注解:
```java
@NacosPropertySource(dataId = "vcs-cloudgate", autoRefreshed = true)
```
我项目中的application配置文件：
```properties
# 对应的 Nacos Cofig 中的 Data ID
spring.application.name=vcs-cloudgate
# Nacos Server 的地址
nacos.config.server-addr=127.0.0.1:8848
```
我在nacos上的配置：
dataId=vcs-cloudgate-dev.yaml
group=DEV_GROUP
```yaml
routes:
  whitelist: 
    - /proxy/app/test1
    - /proxy/app/test2
```
我在启动应用时，添加了active profile参数为`dev`。
我在Controller层获取配置：
```java
   @NacosValue(value = "${routes.whitelist:null}", autoRefreshed = true)
    private List<String> routesWhitelist;
```
最后再使用时，得到的routesWhitelist是空。
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KeRan213539** [comment]
${prefix}-${spring.profiles.active}.${file-extension} 格式是 spring cloud alibaba 定义的
nacos spring boot 需要显示的指定dataId,没有什么格式要求, 您完全可以按照您自己的想法去定义格式. 要用SCA的格式也没问题,只是需要显示的指定
具体请参考: 
https://nacos.io/zh-cn/docs/quick-start-spring-boot.html
https://github.com/KeRan213539/nacos-spring-boot-project

**Comment by wushuaiping** [comment]
> ${prefix}-${spring.profiles.active}.${file-extension} 格式是 spring cloud alibaba 定义的
> nacos spring boot 需要显示的指定dataId,没有什么格式要求, 您完全可以按照您自己的想法去定义格式. 要用SCA的格式也没问题,只是需要显示的指定dataId
> dataId 也不存在后缀的说法, 您需要指定完整的 dataId, 包括 "active profile" 和 "后缀"
> 具体请参考:
> https://nacos.io/zh-cn/docs/quick-start-spring-boot.html
> https://github.com/KeRan213539/nacos-spring-boot-project

谢谢解惑，目前还是有一些用户没有使用spring cloud微服务，而是使用的单机服务，并且不是每个人都去深入了解了nacos源码，建议在官网文档指出来这部分差异。

**Comment by KeRan213539** [comment]
> 谢谢解惑，目前还是有一些用户没有使用spring cloud微服务，而是使用的单机服务，并且不是每个人都去深入了解了nacos源码，建议在官网文档指出来这部分差异。
这个...因为 nacos 和 spring cloud alibaba 是两个不同的产品, 所以您说的这个可能不适合放在官网中...第三方或者个人博客之类的比较合适...
另外, 我印象中 @NacosPropertySource#dataId 应该可以使用 ${} 表达式

**Comment by wushuaiping** [comment]
好的 回头我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 邪影oO <notifications@github.com&gt;
发送时间: 2021年2月23日 10:21
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: Spring <603413965@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 项目中没有使用Spring Cloud只使用了Spring Boot，是否可以使用${prefix}-${spring.profiles.active}.${file-extension}该方式配置？ (#4924)





  
谢谢解惑，目前还是有一些用户没有使用spring cloud微服务，而是使用的单机服务，并且不是每个人都去深入了解了nacos源码，建议在官网文档指出来这部分差异。
  
这个...因为 nacos 和 spring cloud alibaba 是两个不同的产品, 所以您说的这个可能不适合放在官网中...第三方或者个人博客之类的比较合适...
 另外, 我印象中 @NacosPropertySource#dataId 应该可以使用 ${} 表达式

**Comment by KeRan213539** [comment]
> 好的 回头我试试 发自我的iPhone
 
好的. 如果问题解决了,烦请关闭一下这个 ISSUE  :relaxed:
