### ISSUE TITLE
nacos 1.4.1 集群中某节点下线，其余节点不能正确稳定感知状态

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#4925]
**Describe the bug**
我在 #4877 中提到过这个问题，现在再复现一遍
版本是1.4.1，用的是官方发布的release包
三台机器，分别是 172.21.1.134（记为134），172.21.1.150（记为150），172.21.1.153（记为153）

**注意看图片中的时间戳**

1. 先杀掉134机器上的nacos进程

![image](https://user-images.githubusercontent.com/53824889/108683578-c344aa00-752c-11eb-8b77-6a05e5b33d04.png)

2.在153机器的控制台上查看134节点的状态

![image](https://user-images.githubusercontent.com/53824889/108683662-deafb500-752c-11eb-97a4-27db17e747de.png)
![image](https://user-images.githubusercontent.com/53824889/108683670-e1120f00-752c-11eb-840c-dd4246e6b1a8.png)
![image](https://user-images.githubusercontent.com/53824889/108683677-e40cff80-752c-11eb-95bb-47816924e7bf.png)
![image](https://user-images.githubusercontent.com/53824889/108683681-e5d6c300-752c-11eb-86ca-7e6dd04f101e.png)

3.换成Postman访问OpenAPI提供的接口

![image](https://user-images.githubusercontent.com/53824889/108683731-fab35680-752c-11eb-9e25-d0de4e571a9b.png)

![image](https://user-images.githubusercontent.com/53824889/108683740-fdae4700-752c-11eb-9fc1-1f05dd57089a.png)

**Comment by JackSun-Developer** [comment]
我所复现出来不太一样，
相同的是：A\B\C三台机器，把A上的nacos干掉。然后B\C确实不会感知“A已挂”这个事件，并一直保持，认为A还存在。
不同的是：我这边B\C并没有出现反复无常（一会感知，一会不感知）这种情况。
我的版本：nacos1.4.2，测试方式为OpenAPI，机器是阿里云的三台docker容器。

**Comment by JackSun-Developer** [comment]
关于B\C为什么没有感知到A挂掉，分析可能的原因：
A中的nacos并未优雅的退出，导致其在退出之前没有触发IPChangeEvent事件。而ServerMemberManager类中所维护的IP列表只有在监听到该事件时，才会进行写操作（nacos1.4.2，ServerMemberManager.java line181)。没有接到这个事件的话，就没有办法把IP列表中的A清除。

**Comment by MajorHe1** [comment]
> 关于B\C为什么没有感知到A挂掉，分析可能的原因：
> A中的nacos并未优雅的退出，导致其在退出之前没有触发IPChangeEvent事件。而ServerMemberManager类中所维护的IP列表只有在监听到该事件时，才会进行写操作（nacos1.4.2，ServerMemberManager.java line181)。没有接到这个事件的话，就没有办法把IP列表中的A清除。

我印象中nacos的实现难道不应该是B\C主动去探测A的状态，如果A不活就把A的状态置为down的吗？
B\C是否感知A挂掉，应该不由A是否进行优雅退出、是否触发事件决定才对，因为A节点所在机器出现任何机器故障、断网、阻塞，B\C探测A的状态不通就应该更改状态。
是我印象错了还是代码改了？

**Comment by JackSun-Developer** [comment]
抱歉，我之前的复现方法有误，之前是用OpenAPI访问的 curl -X GET '127.0.0.1:8848/nacos/v1/ns/operator/servers'，
在这个前提下出现了：
> 把A上的nacos干掉。然后B\C确实不会感知“A已挂”这个事件，并一直保持，认为A还存在。
但我忽略了这个openapi访问方法不会过滤掉unhealthy的服务。

我重新复现了几遍，并用控制台进行观测。并没有出现您所述的问题。T_T

**Comment by JackSun-Developer** [comment]
@MajorHe1 这个暂时复现不了，可否提供一下您实验的详细信息？
以及使用的寻址模式是地址服务器方式还是cluster.conf配置文件的方式？

**Comment by MajorHe1** [comment]
> @MajorHe1 这个暂时复现不了，可否提供一下您实验的详细信息？
> 以及使用的寻址模式是地址服务器方式还是cluster.conf配置文件的方式？

请问您还需要何种详细的信息呢？
我用的是 1.4.1版本的release包，部署的机器是  腾讯云的虚拟机，寻址模式是地址服务器
地址服务器是另外一个nacos进程的配置中心服务，集群内的nacos节点都是通过OpenAPI去获取这个配置
为了排除虚拟机的干扰，我会在物理机上再试一次，稍等给到您复现结果

**Comment by MajorHe1** [comment]
@JackSun-Developer  问题已经明确，已经提了PR
