### ISSUE TITLE
OpenApi “删除服务”接口的入参和代码不一致

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#4927]
Nacos版本：1.4.0

OpenApi “删除服务”接口的入参描述为：

名称 | 类型 | 是否必选 | 描述
serviceName | 字符串 | 是 | 服务名
groupName | 字符串 | 否 | 分组名
namespaceId | 字符串 | 否 | 命名空间ID

com.alibaba.nacos.naming.controllers.ServiceController类中public String remove(@RequestParam(defaultValue = Constants.DEFAULT_NAMESPACE_ID) String namespaceId,
            @RequestParam String serviceName)

缺少groupName

如果需要按分组删除，代码里没有传groupName的位置

**Comment by KomachiSion** [comment]
不影响，因为在DistroFilter里会将groupName和serviceName进行重新组合，传递到controller里， 你可以试一下。
