### ISSUE TITLE
nacos md5有0开头不停拉取配置 

### ISSUE THREAD

**Issue by westcows00481** [alibaba/nacos#4928]
1. 官网反馈1.2.1版本的md5存在0开头的bug在1.3之后的版本解决了， 但实际上并未解决。 我们使用1.3.2的同样存在这个问题。

**Comment by KomachiSion** [comment]
能否提供一个出现问题的配置？让社区进行测试？

**Comment by westcows00481** [comment]
出现问题的yaml不方便提供， 涉及敏感信息

**Comment by westcows00481** [comment]
> 能否提供一个出现问题的配置？让社区进行测试？

**Comment by westcows00481** [comment]
上面提到的配置刷新的问题高版本也一样存在， 运行一段时间后会出现大量拉取配置的线程

**Comment by KomachiSion** [comment]
你们是只升级了客户端还是客户端服务端都升级了？ 我用最新版本测试不会出现啊。

您是怎么确认一直在拉取配置的？

还有怎么确认出现大量拉取配置的线程，能把这些信息都提供一下吗？

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem. Close it first.

**Comment by ItxiaoDz** [comment]
> 上面提到的配置刷新的问题高版本也一样存在， 运行一段时间后会出现大量拉取配置的线程

spring.cloud.nacos.config.namespace=public
是不是客户端里的namespace配成public了？如果配成public，会导致在nacos服务端中一直是比对成有修改，客户端就会一直拉取服务端数据。

**Comment by westcows00481** [comment]
> > 上面提到的配置刷新的问题高版本也一样存在， 运行一段时间后会出现大量拉取配置的线程
> 
> spring.cloud.nacos.config.namespace=public
> 是不是客户端里的namespace配成public了？如果配成public，会导致在nacos服务端中一直是比对成有修改，客户端就会一直拉取服务端数据。

对，服务端配置的是public,  客户端没单独配置这个，但是只有md5为0开头的时候才会一直刷。
