### ISSUE TITLE
nacos1.4.1，spring.application.name问题

### ISSUE THREAD

**Issue by Yanwenhui0** [alibaba/nacos#4930]
**版本：** nacos1.4.1
**问题：** 当 spring.application.name 包含字符 "-" 时，如 spring.application.name = a-b，注册到 nacos 报错：
```java
com.alibaba.nacos.api.exception.NacosException:
failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: 
ErrCode:400, 
ErrMsg:
<html>
  <body>
    <h1>Whitelabel Error Page</h1>
    <p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p>
    <div id='created'>Tue Feb 23 10:32:23 CST 2021</div>
    <div>There was an unexpected error (type=Bad Request, status=400).</div>
    <div>receive invalid redirect request from peer 127.0.0.1</div>
  </body>
</html>
```

**Comment by Yanwenhui0** [comment]
注册参数：
{
	serverAddr='127.0.0.1:8848', 
	endpoint='', 
	namespace='', 
	watchDelay=30000, 
	logName='', 
	service='spring-boot-admin-server', 
	weight=1.0, 
	clusterName='DEFAULT', 
	group='spring-boot-admin', 
	namingLoadCacheAtStart='false', 
	metadata={
		preserved.register.source=SPRING_CLOUD, 
		user.name=yanwenhui, 
		user.password=ywh169747
	}, 
	registerEnabled=true, 
	ip='192.168.100.97', 
	networkInterface='', 
	port=8080, 
	secure=false, 
	accessKey='', 
	secretKey='', 
	heartBeatInterval=null, 
	heartBeatTimeout=null, 
	ipDeleteTimeout=null
}

**Comment by haoyann** [comment]
我本地直接使用java的sdk，是可以注册服务名为`spring-boot-admin-server`的实例，你是用的什么sdk，可以提供一个demo吗，用来复现。

**Comment by KomachiSion** [comment]
No more response from author and community can't reproduce problem
