### ISSUE TITLE
Namespace能否支持多租户下的多环境需求

### ISSUE THREAD

**Issue by rengx** [alibaba/nacos#4932]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

我们已经从官网了解了namespace的设计，对于第二个角度的描述（即从多个租户(用户)的角度），有一些疑问：
> https://nacos.io/zh-cn/blog/namespace-endpoint-best-practices.html

1.每个租户能否有多个命名空间，租户可以对自己的命名空间进行管理（CURD）？这样每个租户也可以有多套环境。
2.官网中提到此功能还在规划中，请问目前的进展是怎样的？
谢谢。

We have learned about the design of the namespace from the official website. We have some questions about the description of the second angle (that is, from the perspective of multiple tenants (users))：
> https://nacos.io/zh-cn/blog/namespace-endpoint-best-practices.html

1.Can each tenant have more than one namespace, and tenants can manage their own (CURD)? In this way, each tenant can also have multiple environments.
2. It is mentioned in the official website that this function is still under planning. What is the current progress?
Thank you.

**Comment by yanlinly** [comment]
1.每个租户能否有多个命名空间，租户可以对自己的命名空间进行管理（CURD）？这样每个租户也可以有多套环境。
不会的，每个客户端命名空间映射Server一个租户。 

2.官网中提到此功能还在规划中，请问目前的进展是怎样的？
我们规划的是不同namespace映射到不同server的不同tenant上去。  更多的是按照namespace去隔离环境的诉求。

**Comment by rengx** [comment]
1.能否详细描述一下这个规划？在nacos server端增加一个tenant管理的功能吗，管理tenant和namespace的映射？nacos client端通过tenant来初始化namespace？
> 我们规划的是不同namespace映射到不同server的不同tenant上去。

2.目前的版本中，权限管理通过RBAC来配置用户的命名空间权限，以此来隔离不同用户的服务和配置数据，是否也能作为多租户的实现？
谢谢。
