### ISSUE TITLE
为什么直接用springboot集成nacos, 网页打开看不到服务名称?

### ISSUE THREAD

**Issue by sina-ma** [alibaba/nacos#4933]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
看不懂问题是什么。
