### ISSUE TITLE
1.41版本在windows中直接解压启动报错

### ISSUE THREAD

**Issue by Ewelkin** [alibaba/nacos#4937]
1.41版本下载解压后,直接启动无法成功,只有在startup.cmd中
![image](https://user-images.githubusercontent.com/53846315/108934294-9c4ebb00-7687-11eb-8d1a-f0aa923d57e2.png)
将set MODER= cluster修改为set MODER= standalone才能够正常启动并访问

**Comment by DoyuTu** [comment]
https://github.com/alibaba/nacos#step-2-start-server
试用建议使用单机模式部署或Docker。
集群模式依赖其他服务。

**Comment by JackSun-Developer** [comment]
单机使用bash startup.sh -m stadalone 就能启动
集群需要额外配置cluster.conf

**Comment by KomachiSion** [comment]
> 单机使用bash startup.sh -m stadalone 就能启动
> 集群需要额外配置cluster.conf

window 使用 `bash startup.cmd -m standalone`单例启动。

如果不想要单例启动， 则需要配置application.properties中数据库相关内容以及cluster.conf相关内容

**Comment by menggangaaa** [comment]
默认启动 不写 standalone的话 使用集群 模式启动,集群需要配置数据库,如果需要集群模式的话 可以参考这个https://zhuhuix.blog.csdn.net/article/details/108526545
