### ISSUE TITLE
规则推模式只有FlowRule的V2实现，没有其它类型规则的实现

### ISSUE THREAD

**Issue by summer9989** [alibaba/nacos#4944]
**Describe the bug**
Version: 1.8.1

前置情况：使用apollo推模式保存并推送流控规则，我司已成功走通，按照wiki描述的方案使用FlowControllerV2和前端改造。所以对整个改造方案是比较了解的。

现存问题：官方wiki包括到目前最新的1.8.1的sentinel-dashboard代码似乎也只有限流规则FlowRule配套有V2的Controller和前端代码，其它比如降级、热点、系统等规则并没有配套V2的Controller和前端代码。所以我们的疑问是：

降级、热点、系统等规则没有V2代码，是需要我们仿造FlowControllerV2自行实现吗？因为还包括前端几个文件的代码，如果自行实现可能后期同步官方新增的功能代码比较麻烦。

**Comment by km11221122** [comment]
# 这里的flow名字随便取   流控规则
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            groupId: DEFAULT_GROUP
            dataId: ${spring.application.name}
            rule-type: flow
            data-type: json
        # 授权规则    
        authority:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            dataId: ${spring.application.name}-authority-rules
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: authority
          # 降级规则  
          degrade:
            nacos:
              server-addr: ${spring.cloud.nacos.config.server-addr}
              dataId: ${spring.application.name}-degrade-rules
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: degrade
          # 热点规则    
          param-flow:
            nacos:
              server-addr: ${spring.cloud.nacos.config.server-addr}
              dataId: ${spring.application.name}-param-flow-rules
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: param-flow
          # 系统规则    
          system:
            nacos:
              server-addr: ${spring.cloud.nacos.config.server-addr}
              dataId: ${spring.application.name}-system-rules
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: system
