### ISSUE TITLE
NacosServiceRegistry Close NPE

### ISSUE THREAD

**Issue by liaomengge** [alibaba/nacos#4945]
when use graceful shutdown service, the `NacosServiceRegistry#close` not judge `namingService` isn't NULL, so then throw NPE. for below: 
```
public void nacosServiceShutDown() throws NacosException {
    this.namingService.shutDown();
    namingService = null;
    namingMaintainService = null;
}
```

**Comment by KomachiSion** [comment]
Please move this issue to spring cloud alibaba community. `NacosServiceRegistry` is spring cloud class.
