### ISSUE TITLE
4. 在你的应用启动时添加-Dcom.alibaba.nacos.client.naming.ctimeout 参数调高连接超时时间，默认是3s的超时时间

### ISSUE THREAD

**Issue by HOPE-LUO** [alibaba/nacos#4950]
4. 在你的应用启动时添加-Dcom.alibaba.nacos.client.naming.ctimeout 参数调高连接超时时间，默认是3s的超时时间

_Originally posted by @KomachiSion in https://github.com/alibaba/nacos/issues/4139#issuecomment-722079854_

在启动本地项目时vm  加上  -Dcom.alibaba.nacos.client.naming.ctimeout=5000后，项目不能正常启动了？

**Comment by KomachiSion** [comment]
无法启动的错误是什么？

**Comment by KomachiSion** [comment]
No response from author, and we can't reproduce this problem by pure nacos-client. Close issue first. If there are more information, please submit a new issue and refer this issue.
