### ISSUE TITLE
微服务下线后，其他服务能迅速收到naming remove 消息 但是负载均衡转发会在10~30秒左右才会停止

### ISSUE THREAD

**Issue by baiyuechu-123** [alibaba/nacos#4952]
通过源码我发现是updateListOfServers每30秒更新一次，有没有办法配置接受到服务变动的消息后 负载均衡这边也立即刷新呐

**Comment by JackSun-Developer** [comment]
你们的负载均衡转发是怎样配置的呢？

**Comment by baiyuechu-123** [comment]
是用的alibaba cloud 没有做额外的配置，看内部代码应该是直接依赖nacos和ribbon的

**Comment by JackSun-Developer** [comment]
这个应该是ribbon的问题
ribbon 有缓存本地，隔段时间才能刷新

**Comment by baiyuechu-123** [comment]
我尝试监听nacos上下线并主动调用ribbon的刷新 应该可以解决吧

**Comment by phantomedc** [comment]
alibaba/spring-cloud-alibaba#1554

**Comment by baiyuechu-123** [comment]
好的 我也只找到这一个办法~
