### ISSUE TITLE
The rotation of `nacos.core.auth.server.identity.value`

### ISSUE THREAD

**Issue by RobberPhex** [alibaba/nacos#4955]
# The rotation of `nacos.core.auth.server.identity.value`

**Is your feature request related to a problem? Please describe.**

After version 1.4.1+, Nacos server uses HTTP header `${nacos.core.auth.server.identity.key}:${nacos.core.auth.server.identity.value}` to authenticate:

1. There is an `Authorization` title in the HTTP protocol, which is used for authentication. So the style value of the value of `nacos.core.auth.server.identity.key` should not be empty, but should be `Authorization`. It not only facilitates standardization, but also simplifies user configuration.
2. If `nacos.core.auth.server.identity.value` needs to be leaked, or for safety, periodically modify `nacos.core.auth.server.identity.value`, during the upgrade, communication will fail to pass authentication:

Server A replaces `nacos.core.auth.server.identity.value` with a new value. Server B has not been upgraded. At this time, Server A cannot communicate with Server B.

**Describe the solution you'd like**

1. `nacos.core.auth.server.identity.key` can be left blank and replaced with "Authorization". It not only facilitates standardization, but also simplifies user configuration.
2. Provide `nacos.core.auth.server.identity.value` and `nacos.core.auth.server.identity.value2`. You can use rotation:

For `A server`->`B server` communication:
`A server` uses `nacos.core.auth.server.identity.value`.
`B server` can accept `nacos.core.auth.server.identity.value` or `nacos.core.auth.server.identity.value2`.

This allows seamless rotation of `nacos.core.auth.server.identity.value`:
1. Keep the `nacos.core.auth.server.identity.value` of all replicas as the old value, and set `nacos.core.auth.server.identity.value2` as the new value. Restart and upgrade one by one
2. Set the `nacos.core.auth.server.identity.value` of all copies to the new value, and `nacos.core.auth.server.identity.value2` remains unchanged. Restart the upgrade one by one.

---

# 配置`nacos.core.auth.server.identity.value`的轮转

**问题**

1.4.1+ 版本后, Nacos server 使用HTTP头部 `${nacos.core.auth.server.identity.key}: ${nacos.core.auth.server.identity.value}`来认证：

1. HTTP协议中有`Authorization`头部，就是为了认证使用。所以`nacos.core.auth.server.identity.key`这个值的默认值不应该为空，而应该是`Authorization`。既有利于标准化，也简化了用户配置。
2. 如果需要`nacos.core.auth.server.identity.value`泄漏，或者为了安全，定期修改`nacos.core.auth.server.identity.value`，升级期间，会导致集群通信无法认证：

A服务器将`nacos.core.auth.server.identity.value`改为了新的值，B服务器还没有升级，此时，A服务器无法和B服务器通信。

**解决方案**

1. `nacos.core.auth.server.identity.key`可以不填写，默认值为`Authorization`。既有利于标准化，也简化了用户配置。
2. 提供`nacos.core.auth.server.identity.value`和`nacos.core.auth.server.identity.value2`。可以用来轮转：

对于 `A server` -> `B server`通信，
`A server`使用`nacos.core.auth.server.identity.value`作为header的值
`B server`可以接受`nacos.core.auth.server.identity.value`或`nacos.core.auth.server.identity.value2`。

这样可以无缝轮转`nacos.core.auth.server.identity.value`：
1. 将所有集群的`nacos.core.auth.server.identity.value`仍然保持为老值，`nacos.core.auth.server.identity.value2`设置为新值。逐台重启升级
2. 将所有集群的`nacos.core.auth.server.identity.value`设置为新值，`nacos.core.auth.server.identity.value2`保持不变。逐台重启升级。

**Comment by KomachiSion** [comment]
我表达一下我的观点
1. Nacos作为一个内网应用，不应直接对公网暴露，因此identity.value泄漏也就意味着内网已经被攻破（客户端和控制台不会使用这个值，攻击者只能通过内网流量或配置文件获取），那么设置value2也没有意义，因为攻击者可以从内网直接读取配置文件获得value2
2. server.identity 方案是一个非标的临时方案，随着auth模块的重新设计和重构，将来可能会被移除，新方案需要社区安全大佬们一起来设计。
3. 即使需要多个value值，可能也是`values: -A -B`好一点？

**Comment by RobberPhex** [comment]
@KomachiSion 
1. identity.value的更换

identity.value的泄漏有多种途径：`机器被攻破`和`旁路泄漏（比如获取代码库中的配置）`。对于`机器被攻破`，首先需要拿回机器的控制权，然后更换identity.value。对于`旁路泄漏`，则需要更换identity.value。（当然，在安全最佳实践中，这种identity.value也是需要定时更换的）

无论哪种方式，都需要更换identity.value。

现在的问题是，如果需要更换`identity.value`，则需要停机更换，因为在升级到一半的过程中，nacos集群之间的通信会有问题。

所以我才会设计两个value轮转的方案。

2. `server.identity 方案是一个非标的临时方案`

目前安全上严重依赖server.identity 方案，我们需要为这种方案做一个完整的安全方案，比如如何无损地更换`identity.value`。
当然，后续再出现更完善的方案后，也需要提供相关的安全方案。

3. 为了保证兼容性，需要引入`nacos.core.auth.server.identity.value2`

如果定为`values: -A -B`，那么用户升级需要修改properties文件才可以，给用户升级带来了负担。

**Comment by KomachiSion** [comment]
1. 代码库泄漏？你们需要clone代码然后自行打包吗？ 正常的话应该是在部署脚本里同一修改吧？当然可能也有其他泄漏方式，没法做到完美。
2. 如果一定需要轮换，可以先临时开启header验证，然后修改新的identity.value后再关闭header验证。
3. value1和value2有双重泄漏的风险
4. 添加一个value2，事实上也需要改properties，和添加values区别不大。

**Comment by RobberPhex** [comment]
>     1. 代码库泄漏？你们需要clone代码然后自行打包吗？ 正常的话应该是在部署脚本里同一修改吧？当然可能也有其他泄漏方式，没法做到完美。
> 
阿里云就出现过代码库默认权限为public导致客户代码泄漏的情况，这个泄漏和发布形态无关。所以需要及时做好泄漏之后的备案。还要加上定时轮转更换，确保形成机制。
>     2. 如果一定需要轮换，可以先临时开启header验证，然后修改新的identity.value后再关闭header验证。
> 
临时开启header验证相当于又引入了漏洞，而且还是已经公开的漏洞，风险更大。
>     3. value1和value2有双重泄漏的风险
> 
双重泄漏后，可以做到无损更新（先无损更新value，再无损更新value2）。
>     4. 添加一个value2，事实上也需要改properties，和添加values区别不大。
重要的不是修改properties，而是修改properties发布，不会影响线上流量；现在修改properties会造成集群更新期间不可用。

这个issue不是为了避免信息泄漏，而且让**更新value值的时候，nacos仍然可以对外提供服务**。
