### ISSUE TITLE
mysql服务停止时启动nacos，nacos服务进程存在，后台日志报连接不上mysql；启动mysql后， nacos后台日志不再报错，但此时nacos页面无法打开，服务不可用

### ISSUE THREAD

**Issue by 18256086350** [alibaba/nacos#4957]
复现场景：nacos版本1.2.0
1.停止mysql服务
2.启动nacos服务，后台日志报错：
Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
3.启动mysql服务，后台日志不再报错，但nacos服务不可使用

测试时发现该问题，如果nacos服务正常启动，此时mysql重启，mysql服务正常，但是如果nacos服务一开始就因为mysql连接问题异常启动，mysql恢复后，也无法重连。

后续尝试1.4.1版本同样发现该问题。

**Comment by KomachiSion** [comment]
那肯定啊， nacos启动需要去数据库dump初始数据（config模块）， 如果数据库连接失败，无法初始化数据，那nacos就无法生成启动，自然不会开放监听端口，程序退出，应该会抛出异常给spring，spring 初始化阶段就会退出。

如果是先启动完成，数据dump成功后mysql才退出，这样nacos有一份数据可以提供服务，只是数据不可写，但是可以读。

我觉得这是很正常及合理的行为。

**Comment by 18256086350** [comment]
但是我们复现场景是nacos-server的进程是存在的，服务并没有退出

**Comment by KomachiSion** [comment]
Refer to #4970
