### ISSUE TITLE
注册中心默认public问题？

### ISSUE THREAD

**Issue by MHL97** [alibaba/nacos#4958]
服务一直注册在public命名空间下，尝试过nacos.discovery.namespace=XXXXX 和 dubbo.registry.parameters.namespace=XXXXX
指定命名空间，不起作用，如何处理？

**Comment by KomachiSion** [comment]
从你的配置来看，应该是用了sca+dubbo。建议提交该issue到sca社区或者dubbo社区。

或者你debug一下NacosNamingService的init方法，看一下sca或者dubbo传递给nacos的namespace是什么？然后告知sca或者dubbo社区。

**Comment by haoyann** [comment]
是配置在bootstrap文件下吗

**Comment by MHL97** [comment]
> 从你的配置来看，应该是用了sca+dubbo。建议提交该issue到sca社区或者dubbo社区。
> 
> 或者你debug一下NacosNamingService的init方法，看一下sca或者dubbo传递给nacos的namespace是什么？然后告知sca或者dubbo社区。

感谢回复！ 试了下，如果在ip后边追加?namespace=XXX参数的话可以注册到指定的命名空间，单独作为配置项的话不生效，不知道为何，有空debug去看下，感谢~

**Comment by yexiaoyu** [comment]
dubbo.registry.address=nacos://127.0.0.1:8848?namespace=d51d5b91-abbd-458f-b79d-4dc2c3943334
这样才行，奇怪的设计。
