### ISSUE TITLE
com.alibaba.nacos.client.config.impl.PropertiesChangeParser#doParse 处理带\\的值会转移成\ 

### ISSUE THREAD

**Issue by lcl2233** [alibaba/nacos#4960]
com.alibaba.nacos.client.config.impl.PropertiesChangeParser#doParse 比对全量配置 使用 Properties.load 方法导致 带\\\\的值转化为\

**Comment by KomachiSion** [comment]
Which version you used？

**Comment by lcl2233** [comment]
> Which version you used？

1.4.1

**Comment by JackSun-Developer** [comment]
I reproduced this problem.

**Comment by JackSun-Developer** [comment]
>com.alibaba.nacos.client.config.impl.PropertiesChangeParser#doParse 比对全量配置 使用 Properties.load 方法导致 带\\的值转化为\

@lcl2233 please provide your config content.

**Comment by KomachiSion** [comment]
From the reseach, the configuration will handle in nacos inner. But when user get the configuration, it will become `\\`, no error. So we think it is not a problem.
