### ISSUE TITLE
什么时候解决nacos在k8s上hostname的bug，这个问题n个版本一直存在。

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#4962]
不管手动还是自动都存在bug，在NACOS_SERVERS的hostname后加上一个点能成功启动，但在节点列表上会存在两份节点。导致使用seata等中间件就会出现问题，目前只能用非k8s部署集群。

**Comment by JackSun-Developer** [comment]
k8s上部署出现的详细bug信息方便提供一下么？
或者您也可以关注一下这个ISSUE？
https://github.com/alibaba/nacos/issues/3415

**Comment by paderlol** [comment]
关于这个后缀带点的问题,你如果搜索过nacos-k8s的issue你就会看见,这本质上根本不是Nacos的Bug,而是kubernetes 的本身的设置,在高版本上面很多K8S都默认的是 `cluster.local.`, Nacos需要取本地host去验证是否是自己的节点. 

如果不想要点 请自己更改 `--cluster-domain` 具体配置文件应该在 `/etc/kubernetes/kubelet`
如果不能去掉建议自己加上.

**Comment by sundong1982** [comment]
--cluster-domain 设置成 cluster.local.和cluster.local都试过了，也生效了，我的k8s默认是cluster.local ，任何情况nacos都能启动成功 但只有--cluster-domain=cluster.local  且 NACOS_SERVERS带点时 不会报  server is DOWN now, please try again later!  。

nacos1.4.1版
情况1：  
 --cluster-domain=cluster.local    NACOS_SERVERS不带点  pod能成功启动  请求接口报  server is DOWN now, please try again later!  。
nacos集群管理->节点列表为一条数据： nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:8848

情况2：  
 --cluster-domain=cluster.local.    NACOS_SERVERS带点  pod能成功启动  请求接口报  server is DOWN now, please try again later!  。
nacos集群管理->节点列表为一条数据： nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local.:8848

情况3：  
 --cluster-domain=cluster.local    NACOS_SERVERS带点  pod能成功启动  请求接口正常
nacos集群管理->节点列表为2条数据： 
nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local.:8848
nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:8848
这两条数据看着不靠谱，但请求接口正常，nacos网站功能能用，我在1楼描述的就是此种情况，此种情况用seata会出现莫名其妙的错误。

**Comment by admintertar** [comment]
详细日志可以看这里，希望可以解决一下
https://github.com/alibaba/nacos/issues/4573#issuecomment-787477052

**Comment by sundong1982** [comment]
此问题已经在1.4.2和2.0.1中修复
2.0.1的releases：    -[#5334] Fix Server is Down problem in k8s environment.
