### ISSUE TITLE
com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [nacos_config] did not find the Leader node 

### ISSUE THREAD

**Issue by laizuan** [alibaba/nacos#4963]
版本: 1.3.0
集群部署，部署了3个节点。文档运行了几个月后最近出现这个问题。不管有没有修改配置只要点发布就会出现异常
编辑配置 ---> yaml，点发布出现一些错误信息
`caused: errCode: 500, errMsg: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [nacos_config] did not find the Leader node ;`

**Comment by JackSun-Developer** [comment]
Please paste the error info from alipay-jraft.log

**Comment by laizuan** [comment]
We deleted the log when we restarted and will provide it to you next time
