### ISSUE TITLE
Spring项目中, 使用@NacosValue无法获取配置,  @Value可以获取配置值, 但是无法刷新

### ISSUE THREAD

**Issue by yezhengdong** [alibaba/nacos#4966]
<dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-spring-context</artifactId>
      <version>1.0.0</version>
</dependency>

@Configuration
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "172.20.10.8:8847"))
@NacosPropertySource(dataId = "webstudy-dev.yml", autoRefreshed = true)
public class NacosConfig {
}

@RestController
@RequestMapping("/config")
public class NacosConfigController {

    @NacosValue(value = "${expire:900}", autoRefreshed = true)
    private Integer sessionExpireSeconds;

    @Value(value = "${expire:900}")
    private Integer expire;

    @RequestMapping(value = "/expire", method = RequestMethod.POST)
    public RespResult sessionExpire(String name) {
        Map<String, Object> resp = new HashMap<>();
        resp.put("name", name);
        resp.put("expire", sessionExpireSeconds);
        resp.put("expire2", expire);
        return RespResult.success(resp);
    }
}

所有相关代码在上面, 

还有
1, 在项目启动时, 会去写Logback的ContextName, 是否可以去掉.
2, 在配置dataId时, 是强制要带上后缀的(properties/yml...), 在官网的Demo可以加上吗?

**Comment by KomachiSion** [comment]
Value肯定不能刷新，毫无疑问。

NacosValue无法获取配置可能需要排查下问题。

**Comment by yezhengdong** [comment]
但是在SpringBoot项目中, @NacosValue可以获取配置, 无法刷新;   @Value可以获取配置, 也可以刷新.

<dependency>
  <groupId>com.alibaba.boot</groupId>
  <artifactId>nacos-config-spring-boot-starter</artifactId>
  <version>0.2.7</version>
</dependency>

nacos:
  config:
    server-addr: 172.20.10.8:8847

@SpringBootApplication
@NacosPropertySource(dataId = "webstudy-dev.yml", autoRefreshed = true)
public class BootstudyApplication {

    public static void main(String[] args) {
        SpringApplication.run(BootstudyApplication.class, args);
    }
}

@RestController
@RequestMapping("/config")
public class NacosConfigController {

    @NacosValue(value = "${expire:900}", autoRefreshed = true)
    private Integer sessionExpireSeconds;

    @Value(value = "${expire:900}")
    private Integer expire;

    @RequestMapping(value = "/expire", method = RequestMethod.POST)
    public RespResult sessionExpire(String name) {
        Map<String, Object> resp = new HashMap<>();
        resp.put("name", name);
        resp.put("expire", sessionExpireSeconds);
        resp.put("expire2", expire);
        return RespResult.success(resp);
    }
}

**Comment by JackSun-Developer** [comment]
你用的是什么版本的nacos，我这边用最新版本的nacos复现，@NacosValue在Spring和Springboot方式中都能够正常的获取nacos端的配置+动态刷新。

**Comment by JackSun-Developer** [comment]
如果你那边有问题的话，可能是你在nacos端注册配置的时候，其groupId或dataId跟spring端不一致。

**Comment by KomachiSion** [comment]
@yezhengdong Any process? If no more response, we will think your problem has solved and close issue.

**Comment by yezhengdong** [comment]
com.alibaba.nacos nacos-spring-context 1.0.0  和  com.alibaba.boot nacos-config-spring-boot-starter 0.2.7,   请问现在最新版本是多少了, 能提供下链接吗

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-spring-boot-project

**Comment by KomachiSion** [comment]
We plan release a new version based client 1.4.1 recent weeks, you can retry after new version released

**Comment by linyongfu2013** [comment]
@Value 能获取值，要实现动态刷新，需要在类上面加个注解 @RefreshScope

@NacosValue 是真的无法获取值，全是 null，并且，你们文档里说的是用美元符，代码注释里用的是【#】，然而两者都试过，真的无法获取值。

请求重开该 issue，谢谢。

![1619073000357](https://user-images.githubusercontent.com/4011963/115666541-4a6c9d80-a377-11eb-9a6d-dd372f3d646e.jpg)

**Comment by linyongfu2013** [comment]
代码&配置如下：

![image](https://user-images.githubusercontent.com/4011963/115667126-0ded7180-a378-11eb-9e16-d0cfbd74feb6.png)

![image](https://user-images.githubusercontent.com/4011963/115667220-2bbad680-a378-11eb-83d0-86a4a58bba5f.png)

**Comment by linyongfu2013** [comment]
nacos server : 2.0.0
nacos client: 1.3.2
spring-cloud-alibaba.version: 2.2.2.RELEASE
spring boot : 2.3.7.RELEASE

**Comment by realJackSun** [comment]
@linyongfu2013 可能是这个注解和Nacos服务端配置的dataId不一致导致的。
![image](https://user-images.githubusercontent.com/58767027/121985519-76306080-cdc7-11eb-9660-1b579dbfd969.png)

**Comment by Lxml-q** [comment]
nacos server : 2.1.1
spring boot : 3.0
用@NacosConfigurationProperties和@NacosValue都直接获取不到值，更不提自动刷新了；用@Value和ConfigurationProperties能获取到值

但是把spring boot 的版本回退到2.7.3，用@NacosConfigurationProperties和@NacosValue就能获取到值
