### ISSUE TITLE
调用openapi注册服务不成功

### ISSUE THREAD

**Issue by EvanLai0819** [alibaba/nacos#4969]
调用OpenAPi注册服务时，返回结果是OK的，服务中心也能看到，但是过1分钟左右后，服务会自动被删除，查看日志发现时发现，是这样子的 
`021-02-27 00:35:19,416 INFO {POS} {IP-DISABLED} valid: 192.168.3.10:9004@DEFAULT@DEFAULT_GROUP@@product-provider, region: unknown, msg: client timeout after 15000, last beat: 1614357301297`

调用的命令是
`curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=product-provider&ip=192.168.3.10&port=9004'`

**Comment by EvanLai0819** [comment]
服务时正常运行的，不过不是spring-cloud的application

**Comment by haoyann** [comment]
这样调用api注册的是非持久化服务，需要客户端定时上报心跳，否则服务在心跳检测失败之后会把实例移除，就会出现这种情况。

**Comment by haoyann** [comment]
看你的使用场景，可以选择注册持久化服务，持久化服务的健康检查是依赖服务端的方向探活。

**Comment by EvanLai0819** [comment]
是设置ephemeral=false吗

**Comment by haoyann** [comment]
> 是设置ephemeral=false吗

是的
