### ISSUE TITLE
mysql异常情况下启动nacos服务，服务进程存在；重启mysql后，nacos依旧不能使用，处于假死状态

### ISSUE THREAD

**Issue by weiweili666** [alibaba/nacos#4970]
mysql异常情况下，nacos是否应该启动失败（目前看到是进程存在）或者说mysql启动后，nacos有相应的重连机制，而不是导致服务不可用。

**Comment by KomachiSion** [comment]
这里可能需要讨论下，因为有部分功能其实不需要依赖数据库，如果连不上数据库 进程就彻底退出，那就变成强依赖数据库。

**Comment by KomachiSion** [comment]
如果在数据库异常的情况下启动nacos，而nacos配置中心和鉴权又需要mysql， 这时候nacos应该在nacos.log会有大量异常日志吧。 实际使用中，应该会在启动时确认是否正常开启。

**Comment by 18256086350** [comment]
确实会有大量的异常日志，但是mysql恢复正常时，nacos后台不会再打印异常日志，但其实这个时候服务是不可用的，就算进程存在没什么意义

**Comment by KomachiSion** [comment]
嗯，这里需要讨论和规划一下，因为最早设计的时候只有配置中心需要数据库，服务发现是完全不需要的，后来加了鉴权之后就可能都需要数据库了。从而导致数据库连接异常完全无法使用。

需要讨论，重新设计一下依赖结构，然后花时间进行重构了。

**Comment by welpeng** [comment]
> 嗯，这里需要讨论和规划一下，因为最早设计的时候只有配置中心需要数据库，服务发现是完全不需要的，后来加了鉴权之后就可能都需要数据库了。从而导致数据库连接异常完全无法使用。
> 
> 需要讨论，重新设计一下依赖结构，然后花时间进行重构了。

这个问题有后续吗，我们也遇到了这个问题
