### ISSUE TITLE
【nacos-config接口】在长轮询的接口里是否能直接访问变化的配置内容？

### ISSUE THREAD

**Issue by superstarchenxin** [alibaba/nacos#4972]
nacos-config源码里longPolling返回后的是变动的dataId, 其实是不是可以访问变化的配置内容？减少一次短轮询获取配置的消耗
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
我猜测没有直接返回变更内容，是因为配置变更的量可能会非常大，单个配置很大的情况下如果出现大量发布变更，容易把IO打满（网络和磁盘缓存）从而影响业务的运行。 配置中心和服务发现作为旁路，不能也不应该影响到业务的运行，因此只返回dataId，然后把dataId打散去获取，把一个可能的大IO峰值拉平。减少对业务资源的占用。

**Comment by superstarchenxin** [comment]
> 我猜测没有直接返回变更内容，是因为配置变更的量可能会非常大，单个配置很大的情况下如果出现大量发布变更，容易把IO打满（网络和磁盘缓存）从而影响业务的运行。 

--》
作为配置中心，单个配置的量是有最大上限的限制吧！没记错的话是1k以内吧，不会对IO有太大影响

**Comment by KomachiSion** [comment]
但是一个长轮训监听的是2000个配置，就可能对IO有影响了。

开源社区内可能问题不大。如果业务比较多，服务配置数很多的话，就有可能有风险了。比如大促的快速扩容之类的

**Comment by superstarchenxin** [comment]
> 但是一个长轮训监听的是2000个配置，就可能对IO有影响了。
> 
> 开源社区内可能问题不大。如果业务比较多，服务配置数很多的话，就有可能有风险了。比如大促的快速扩容之类的



> 我猜测没有直接返回变更内容，是因为配置变更的量可能会非常大，单个配置很大的情况下如果出现大量发布变更，容易把IO打满（网络和磁盘缓存）从而影响业务的运行。 配置中心和服务发现作为旁路，不能也不应该影响到业务的运行，因此只返回dataId，然后把dataId打散去获取，把一个可能的大IO峰值拉平。减少对业务资源的占用。

这里又有两个问题：
1. 现在的client有做dataId的打散获取实现吗？
2. 在2.0版本的长链接实现里，是直接在一个长链接里就返回内容吗？

这个issue讨论怎么能要求commiter的同学加入？

**Comment by KomachiSion** [comment]
@chuntaojun @shiyiyue1102 Please describe for config long polling.

**Comment by chuntaojun** [comment]
我迟一些回复

**Comment by chuntaojun** [comment]
针对第一个：目前没有做dataId打散的实现，因为打散的话，涉及到动态的hash分发任务，以及worker的动态变更，目前的方式只是按照监听配置的量级来实现将监听任务划分为多个子任务来处理。
针对第二个：在2.0版本的长链接实现里，是直接在一个长链接里就返回内容吗？不是的，这里仍然是推拉结合的方式，只是推从原来的http长轮询实现转换为长链接的方式，主要优化是在推的实现这一块。

**Comment by chuntaojun** [comment]
针对第二个，后面会看下是否实现根据版本机制来解决并发引起的版本问题
