### ISSUE TITLE
swarm 部署 nacos 集群，出现多 leader 情况，并且部分节点无法响应，down 掉的情况

### ISSUE THREAD

**Issue by JarvisPongSky** [alibaba/nacos#4974]
[issues 地址](https://github.com/nacos-group/nacos-docker/issues/165#issue-818231815)

**Comment by KomachiSion** [comment]
1.4.0版本后，旧raft已经废弃，不应该再进行选主操作。

日志上看，有节点已经正确停止了旧raft，而有的节点没有停止，那肯定是出问题的节点对其他节点的版本判断上出问题了。

麻烦提供一下出问题节点的集群管理页面（包括详细内容）。

以及所有节点的日志文件。

**Comment by JarvisPongSky** [comment]
稍等下，我还原下案发现场。这可能需要几分钟。

**Comment by JarvisPongSky** [comment]
nacos 集群日志已上传 [奶牛快传](https://cowtransfer.com/s/674915c88ddc48)。

**Comment by JarvisPongSky** [comment]
刚部署是，只有 nacos2 节点没问题，nacos1、nacos3 节点都故障。

然后我把 nacos1、nacos3 删除后，重新部署新的 nacos1、nacos3，能成功加入 nacos2 集群，三个节点查看集群管理页面的元数据都是一致的。

![image](https://user-images.githubusercontent.com/53456132/109443724-4064a780-7a76-11eb-9980-5fb7d065b333.png)

![image](https://user-images.githubusercontent.com/53456132/109443762-53777780-7a76-11eb-8697-1abb505f5001.png)

![image](https://user-images.githubusercontent.com/53456132/109443784-68540b00-7a76-11eb-97ca-d5d3714ca092.png)

**Comment by JarvisPongSky** [comment]
@KomachiSion 我经过几次测试，发现了问题所在。

## 部署问题

我部署方式是采用 `docker stack deploy` 方式进行部署的，对比了官方示例 `docker-compose up` 部署方式。

`docker stack deploy` 部署的话，是一个服务一个服务部署。一个服务创建完成后，才会接着创建下一个服务。

`docker-compose up` 部署的话，是所有服务同时创建。

经过 不同部署方式的测试，发现 `docker-compose up` 部署方式并无出现集群错误的问题。

所以揣测出一个结论，如果服务不是同时创建，就会出现集群创建失败的问题。

从而延伸出 `nacos` 问题。

## nacos 问题

配置了 `NACOS_SERVERS` 集群地址，假设值为 nacos1:8848 nacos2:8848 nacos3:8848。

假设依次启动 nacos1、nacos2、nacos3。

nacos1 启动后，尝试连接其他两个节点，发现不存在，则会将节点信息进行剔除，并设置自己为 leader。

后续 nacos2、nacos3 启动后，尝试连接其他两个节点。

加入集群信息发现，nacos1 为 leader，但是 nacos1 集群信息并没有 nacos2、nacos3。

因此 nacos2、nacos3 在它们当中选举出 leader，所以才出现多 leader 的情况。

## 结论

由于 当前 1.4.1版本 nacos 集群侦测机制，需要 `NACOS_SERVERS` 集群地址的服务同时能被访问，才不会出现集群错误的情况。

所以目前 `docker stack deploy` 部署方案暂不能成功部署 ❌  。

但是 `docker-compose up` 部署方案理论也不是能完美部署的 ⚠️ 。

假设存在性能问题，各节点启动有延迟，一旦出现节点延迟启动成功，没被访问到，则也会出现集群错误的情况。（这个情况也是挺难出现，一般都能同时响应，只是由于 nacos 的机制，会存在这个问题）

**Comment by KomachiSion** [comment]
我在非docker环境，逐台启动部署无法复现问题，说明还是由于环境因素影响了选主判断和raftGroup内容。

**Comment by CraKeyBoy** [comment]
@KomachiSion 建议在 docker swarm 环境里复现。确实存在这个问题。1.4.0 可以正常部署在 docker swarm 里。

**Comment by isaacchn** [comment]
> @KomachiSion 我经过几次测试，发现了问题所在。
> 
> ## 部署问题
> 我部署方式是采用 `docker stack deploy` 方式进行部署的，对比了官方示例 `docker-compose up` 部署方式。
> 
> `docker stack deploy` 部署的话，是一个服务一个服务部署。一个服务创建完成后，才会接着创建下一个服务。
> 
> `docker-compose up` 部署的话，是所有服务同时创建。
> 
> 经过 不同部署方式的测试，发现 `docker-compose up` 部署方式并无出现集群错误的问题。
> 
> 所以揣测出一个结论，如果服务不是同时创建，就会出现集群创建失败的问题。
> 
> 从而延伸出 `nacos` 问题。
> 
> ## nacos 问题
> 配置了 `NACOS_SERVERS` 集群地址，假设值为 nacos1:8848 nacos2:8848 nacos3:8848。
> 
> 假设依次启动 nacos1、nacos2、nacos3。
> 
> nacos1 启动后，尝试连接其他两个节点，发现不存在，则会将节点信息进行剔除，并设置自己为 leader。
> 
> 后续 nacos2、nacos3 启动后，尝试连接其他两个节点。
> 
> 加入集群信息发现，nacos1 为 leader，但是 nacos1 集群信息并没有 nacos2、nacos3。
> 
> 因此 nacos2、nacos3 在它们当中选举出 leader，所以才出现多 leader 的情况。
> 
> ## 结论
> 由于 当前 1.4.1版本 nacos 集群侦测机制，需要 `NACOS_SERVERS` 集群地址的服务同时能被访问，才不会出现集群错误的情况。
> 
> 所以目前 `docker stack deploy` 部署方案暂不能成功部署 ❌ 。
> 
> 但是 `docker-compose up` 部署方案理论也不是能完美部署的 ⚠️ 。
> 
> 假设存在性能问题，各节点启动有延迟，一旦出现节点延迟启动成功，没被访问到，则也会出现集群错误的情况。（这个情况也是挺难出现，一般都能同时响应，只是由于 nacos 的机制，会存在这个问题）

works for me while using 'nacos-quick-start.yaml' in kubernetes

**Comment by KomachiSion** [comment]
This issue seems same as #4787
