### ISSUE TITLE
Nacos如何做延迟注册

### ISSUE THREAD

**Issue by LeePui** [alibaba/nacos#4975]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我们一些服务，在启动时需要做一系列初始化的工作，希望等这些初始化工作都结束后再允许这个服务被调用。
    以前我们服务暴露的是域名，负载均衡交给k8s去做，服务提供健康检查机制，启动时k8s先做一遍健康检查，服务响应通过，k8s才会加进去。
    目前服务注册到nacos上，注册的是ip，负载均衡不再由k8s去做，改为ribbon。发现nacos client是一启动就注册上去的，有没有办法先完成自定义的健康检查之类的机制，再注册呢？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by LeePui** [comment]
版本1.4.0

**Comment by KomachiSion** [comment]
目前没有办法自动完成，可以先以下线状态注册到nacos上，确认无误之后再在控制台或者使用接口把这个实例状态改为上线

**Comment by yab** [comment]
> 目前没有办法自动完成，可以先以下线状态注册到nacos上，确认无误之后再在控制台或者使用接口把这个实例状态改为上线
我们也遇到相同的问题
由于在k8s集群的pods重新ip重新注册后会改变，用上述方法，先下线，再启动ip会变，状态就直接变为上线了。

**Comment by Phoebus888** [comment]
> ## 问题描述
> 类型：_错误报告_或_功能请求_
> 
> ### 描述发生了什么（或你想要什么功能）
> 我们一些服务，在启动时需要做一系列初始化的工作，希望等这些初始化工作都结束后再允许这个服务被调用。 以前我们服务暴露的是域名，负载均衡交给K8S去做，服务提供健康检查机制，启动时k8s先做健康检查，服务响应通过，k8s会添加进去。当前 服务注册到nacos上，注册的是ip，负载均衡不再由k8s引入，改为ribbon。发现nacos客户端是一启动就注册上，有没有办法先完成自定义健康检查之类的机制，再注册呢？
> 
> ### 描述你期望发生的事情
> ### 如何重现它（尽可能最小和精确）
> 
> ### 告诉我们您的环境
> ### 还有什么我们需要知道的吗？

你解决了吗  我们也遇到了这个问题

**Comment by nishidashabia** [comment]
商业版本好像做了。要么在client注册的时候  从服务元数据 配置延迟时间。开个线程 延迟注册？ 这样得改源码了。

**Comment by hillbun** [comment]
> 由于在k8s集群的pods重新ip



> 目前没有办法自动完成，可以先以下线状态注册到nacos上，确认无误之后再在控制台或者使用接口把这个实例状态改为上线

@KomachiSion 

请问这个如何实现

**Comment by xiaorenhong** [comment]
> ## Issue Description
> Type: _bug report_ or _feature request_
> 
> ### Describe what happened (or what feature you want)
> 我们一些服务，在启动时需要做一系列初始化的工作，希望等这些初始化工作都结束后再允许这个服务被调用。 以前我们服务暴露的是域名，负载均衡交给k8s去做，服务提供健康检查机制，启动时k8s先做一遍健康检查，服务响应通过，k8s才会加进去。 目前服务注册到nacos上，注册的是ip，负载均衡不再由k8s去做，改为ribbon。发现nacos client是一启动就注册上去的，有没有办法先完成自定义的健康检查之类的机制，再注册呢？
> 
> ### Describe what you expected to happen
> ### How to reproduce it (as minimally and precisely as possible)
> 
> ### Tell us your environment
> ### Anything else we need to know?
你好  这个问题后面是怎么解决的呢  可以分享下吗  谢谢
