### ISSUE TITLE
Whether the service in the NACOS registry list becomes empty after refresh

### ISSUE THREAD

**Issue by Runcode-China** [alibaba/nacos#4984]
Environment: nacos 1.3.2 , springboot2.2.2

Problem description: 
![image](https://user-images.githubusercontent.com/66289053/109478187-e71b6900-7ab3-11eb-9bec-c53c93365404.png)

![image](https://user-images.githubusercontent.com/66289053/109478140-d539c600-7ab3-11eb-9eaa-955cea9e3b68.png)

When I refresh the page, the service named "fishery-logistics-service" will become empty.

**Comment by JackSun-Developer** [comment]
I think this is because the instances under the service didn't send heartbeats, so it is set to unhealthy.

**Comment by JackSun-Developer** [comment]
@Runcode-China Which version do you use? If you use nacos2.0.0 grpc, this problem can be avoided.

**Comment by JackSun-Developer** [comment]
You didn't register instance to the "fishery-logistics-service", so it is an empty service.
Nacos will clean up all empty services every 5 seconds.
if you want to avoid this, you can reset the configuration my modifiing application.properties.
