### ISSUE TITLE
Does nacos 1.1.3 support get namespace list api (get v1/console/namespaces) ?

### ISSUE THREAD

**Issue by lwtdev** [alibaba/nacos#4985]
When I GET 'v1/console/namespaces' with nacos 1.1.3 return 401 Unauthorized.
But works will in nacos 1.4.1 .

**Comment by JackSun-Developer** [comment]
1.1.3 also supports it.

**Comment by JackSun-Developer** [comment]
In 1.1.3, just see the source code: NamespaceController.java

**Comment by KomachiSion** [comment]
@JackSun-Developer maybe need to check, whether this API is added in 1.1.3

**Comment by KomachiSion** [comment]
Author no more response, so we think the problem has fixed.
