### ISSUE TITLE
如何获取指定命名空间的 NamingService？

### ISSUE THREAD

**Issue by tudan110** [alibaba/nacos#4986]
`NamingService namingService = NamingFactory.createNamingService(serverList);`

我参考 nacos 文档，使用上述方法获取 NamingService，但是始终获取的是默认 public 命名空间，我该如何获取我**自定义命名空间**的 NamingService 呢

**Comment by tudan110** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
NamingFactory.createNamingService(properties)

**Comment by tudan110** [comment]
谢谢指点
