### ISSUE TITLE
这些接口都不需要检验token吗？

### ISSUE THREAD

**Issue by 985391294** [alibaba/nacos#4988]
nacos服务端的接口都不检验token吗，如果我知道了ip之后岂不是可以直接拿你的配置信息了？希望后面的版本改进把这个功能给更新上吧

**Comment by JackSun-Developer** [comment]
>nacos服务端的接口都不检验token吗，如果我知道了ip之后岂不是可以直接拿你的配置信息了？希望后面的版本改进把这个功能给更新上吧

鉴权功能可以配置的，配置方法见这个地址
https://nacos.io/zh-cn/docs/auth.html

**Comment by KomachiSion** [comment]
这个issue 的信息几乎没有。能否按照issue模版填写？

或者至少提供其他相关信息吧。比如

1. 是否开启鉴权功能？
2. 哪些接口，有些接口可能不需要鉴权，所以没有加，可以发起讨论看下是否需要添加。
3. 使用的版本号是哪个？

**Comment by 985391294** [comment]
![nacos](https://user-images.githubusercontent.com/57293296/110285091-b68c7f80-801d-11eb-9820-9ff3da4f4547.png)

**Comment by 985391294** [comment]
这个接口是在config模块下面，获取配置信息的，我在一个浏览器复制接口地址到另外一个不同的浏览器可以直接拿到数据
