### ISSUE TITLE
nacos集群配置，修改检查端口，页面展示还是默认80端口

### ISSUE THREAD

**Issue by daifang-code** [alibaba/nacos#4990]
![image](https://user-images.githubusercontent.com/69003389/109607110-b21a1f80-7b62-11eb-8f2f-a3ba0a966734.png)
![image](https://user-images.githubusercontent.com/69003389/109607188-d4ac3880-7b62-11eb-9df4-bb02f5af32c1.png)

**Comment by KomachiSion** [comment]
Which version？ Can you use new version retry. I remember the new version has fixed it.

**Comment by daifang-code** [comment]
1.4.1，you can fix it at 2.0

**Comment by KomachiSion** [comment]
I use 1.4.1 demo to test, it can work well. 
So I think you maybe use old js cache.

I suggest you clean your browser cache totally and retry again.

**Comment by KomachiSion** [comment]
Author has no response and we can't reproduce problem. So we think users use old js cache. clean and retry is ok.
