### ISSUE TITLE
1.4.1 集群启动失败

### ISSUE THREAD

**Issue by duelgenji** [alibaba/nacos#4995]
版本1.4.1 下载至本地
 ./startup.sh -m standalone  单机启动成功

关闭之后尝试集群模式，修改cluster.conf，增加了3行，application.properties没改动，还是默认的8848
10.60.84.84:8848
10.60.84.84:8849
10.60.84.84:8850

执行 ./startup.sh -p embedded
start.out log一直显示 

2021-03-03 15:33:21,240 INFO Nacos is starting...
2021-03-03 15:33:22,243 INFO Nacos is starting...

下面是另外2个日志文件的截图
![image](https://user-images.githubusercontent.com/6143263/109770895-1e665300-7c37-11eb-822b-3955bad60ad9.png)
![image](https://user-images.githubusercontent.com/6143263/109771088-61282b00-7c37-11eb-9a9c-5fb6b4e8cfc1.png)

**Comment by KomachiSion** [comment]
所有节点都是按照8848启动的？ 然后cluster.conf定的是8848，8849，8850？ 那应该会有问题， jraft无法选主，导致config模块无法dump到历史数据，无法启动。 至少要能让raft选出leader才可以。

**Comment by duelgenji** [comment]
我是本地copy了三份服务，分别把application.properties 中的server port改为了8848，8849，8850，并不是都在8848启动的。

**Comment by KomachiSion** [comment]
1. 一直在starting是因为config模块需要在启动时从数据库加载数据。否则无法提供服务，而你使用了derby数据库，需要依赖jraft的nacos-config group选主，但是因为您环境的原因，一直无法选出leader。
2. 我同样在本地copy了3个节点，将server port改为了8848，8948，9048，是能够在本地顺利启动的。 所以应该还是您本地环境的问题。可以看一下除了raft以外的其他日志信息，比如nacos.log ,看看是否有其他的问题导致。

**Comment by KomachiSion** [comment]
Author has no more response, so we think the problem is deploy problem

**Comment by jeceldx** [comment]
我也遇到类似问题，请问一下有发现问题出在哪吗
