### ISSUE TITLE
通过api修改服务端日志级别不生效？

### ISSUE THREAD

**Issue by feixia5712** [alibaba/nacos#4996]
你好，根据你们提供的api，修改日志级别为啥不生效
![image](https://user-images.githubusercontent.com/12670758/109771768-2b377680-7c38-11eb-9714-73f9c396714f.png)
这个core-auth的日志级别是默认debug，时间一长会产生大量的日志，我通过curl修改返回了200，也重启nacos试了，但是没有修改成功
![image](https://user-images.githubusercontent.com/12670758/109772050-7fdaf180-7c38-11eb-8291-76f473ba481c.png)

**Comment by KomachiSion** [comment]
目前修改日志级别的接口只能修改naming和config模块的日志。core模块的需要添加一下。

**Comment by feixia5712** [comment]
请问下怎么添加一下？直接在application.properties里面添加吗？

**Comment by haoyann** [comment]
@i will solve it@

**Comment by feixia5712** [comment]
> @i will solve it@

这个问题会在新版本中修复？
