### ISSUE TITLE
nacos客户端一直连接不上，是什么原因呢？

### ISSUE THREAD

**Issue by otary** [alibaba/nacos#4999]
`
navigation-collector       | 12:20:14.180 [com.alibaba.nacos.naming.beat.sender] WARN  com.alibaba.nacos.client.naming - failed to request http://myip:8848/nacos/v1/ns/instance/beat?app=unknown&namespaceId=public&port=9899&clusterName=DEFAULT&ip=172.18.0.11&serviceName=DEFAULT_GROUP%40%40navigation-collector&encoding=UTF-8 from myip
navigation-collector       | 12:20:14.180 [com.alibaba.nacos.naming.beat.sender] ERROR com.alibaba.nacos.client.naming - [NA] failed to request 
navigation-collector       | java.net.SocketTimeoutException: connect timed out
navigation-collector       |    at java.net.PlainSocketImpl.socketConnect(Native Method)
navigation-collector       |    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
navigation-collector       |    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
navigation-collector       |    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
navigation-collector       |    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
navigation-collector       |    at java.net.Socket.connect(Socket.java:589)
navigation-collector       |    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
navigation-collector       |    at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
navigation-collector       |    at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
navigation-collector       |    at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
navigation-collector       |    at sun.net.www.http.HttpClient.New(HttpClient.java:339)
navigation-collector       |    at sun.net.www.http.HttpClient.New(HttpClient.java:357)
navigation-collector       |    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
navigation-collector       |    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
navigation-collector       |    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
navigation-collector       |    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
navigation-collector       |    at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86)
navigation-collector       |    at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:433)
navigation-collector       |    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:482)
navigation-collector       |    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401)
navigation-collector       |    at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:343)
navigation-collector       |    at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:108)
navigation-collector       |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
navigation-collector       |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
navigation-collector       |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
navigation-collector       |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
navigation-collector       |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
navigation-collector       |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
navigation-collector       |    at java.lang.Thread.run(Thread.java:748)
`

![image](https://user-images.githubusercontent.com/3916327/109900587-9766b880-7cd2-11eb-9e9a-c00ff98bd366.png)

![image](https://user-images.githubusercontent.com/3916327/109900609-9f265d00-7cd2-11eb-8d9d-ebb25de0892f.png)

**Comment by KomachiSion** [comment]
`connect timed out` check your network status and server part GC status. 
I see your service and instance is not many numbers.
So I think there are some problem in network.

If you use VPN/ VIP or other network mid-layer or translate-layer. Please check whether they shutdown the connect request.

**Comment by KomachiSion** [comment]
And also you can use openAPI to do some test in nacos-server localhost to make sure whether server part is problem.

**Comment by otary** [comment]
> `connect timed out` check your network status and server part GC status.
> I see your service and instance is not many numbers.
> So I think there are some problem in network.
> 
> If you use VPN/ VIP or other network mid-layer or translate-layer. Please check whether they shutdown the connect request.

我并未使用vpn，单实例运行，nacos client和nacos server是在同一个服务器上的，使用docker管理，两者使用同一个network，应该不存在网络通讯问题

因为在服务列表中是可以看到nacos client注册上了，如果是否可以排除网络问题？

**Comment by KomachiSion** [comment]
统计一下当前的连接数量，看下是不是有很多time wait的连接占用了，这也有可能导致连接超时。

`connect timed out` 肯定是创建4层TCP连接的3次握手出现了问题，除了nacos在FGC完全无响应的情况以外，其他出现这个通常和nacos本身没有太大关系。

**Comment by otary** [comment]
> 统计一下当前的连接数量，看下是不是有很多time wait的连接占用了，这也有可能导致连接超时。
> 
> `connect timed out` 肯定是创建4层TCP连接的3次握手出现了问题，除了nacos在FGC完全无响应的情况以外，其他出现这个通常和nacos本身没有太大关系。 多半是环境问题，目前遇到的最多的情况就是中间加了VIP或nginx，然后被限流了（连接请求直接不会发送给nacos服务端，中间测全部丢弃了）

与nacos 客户端的版本是否有关，nacos server端的是1.3.2，nacos client端用的是spring-cloud-starter-alibaba-nacos-config-2.2.1.RELEASE.jar，版本不匹配有没有可能出现timeout现象？

这个并非用于生产的项目，只是一个练习的小项目，所以限流之类的基本不用考虑，疑惑的是，如果是网络问题的话，那么为什么服务可以注册到nacos上呢？

**Comment by KomachiSion** [comment]
1. 无关 nacos-server兼容更低版本的client
2. 能够注册上，说明注册的请求没有没限流或者拦截，而后续每5s一次的心跳出现超时，说明后续频繁的心跳触发了你的限流/拦截限制。或者您服务端的连接上限等。
3. `connect timed out` 一定是在创建tcp连接是有问题。如果您一直无法确定，有一个办法可以尝试定位问题在哪部分：在客户端和服务端同时抓取网络包tcpdump，然后对比简历连接的tcp请求，看下是服务端没有收到建立连接的请求，还是收到了没有回复。从而定位是哪里的问题。

**Comment by KomachiSion** [comment]
Author has no more response, so we think there are some environment problem.
