### ISSUE TITLE
[RFC] Template or Standard  about new features,major changes,or other important things

### ISSUE THREAD

**Issue by qingdengyue** [alibaba/nacos#5]
- [ ] Template or Standard  about new features,major changes,or others important things

# Purpose

1. Everyone can participate.
2. Every things have footprint
3. The Best document for new features,major changes,or other important things
4. Every thing is clear even though i am a new comer.

**Comment by xuechaos** [comment]
@qingdengyue Sorry for the late reply. this template is for issues or PR.
https://github.com/alibaba/nacos/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
https://github.com/alibaba/nacos/blob/master/.github/PULL_REQUEST_TEMPLATE.md
