### ISSUE TITLE
nacos 0.7 控制台下线应用没效果

### ISSUE THREAD

**Issue by vicykie** [alibaba/nacos#500]
![image](https://user-images.githubusercontent.com/9333444/50320145-f979df80-0505-11e9-99b6-ec53c8f1a5ab.png)
7741端口已经下线，但还是可以被调用。。
![image](https://user-images.githubusercontent.com/9333444/50320178-2201d980-0506-11e9-9635-0c4c073b1628.png)

**Comment by nkorange** [comment]
@vicykie 提供一下你的客户端版本

**Comment by vicykie** [comment]
> @vicykie 提供一下你的客户端版本

![image](https://user-images.githubusercontent.com/9333444/50321921-0c90ad80-050e-11e9-89cc-a8b5a2e5a250.png)

**Comment by vicykie** [comment]
看出问题了，客户端版本低了。最新的0.6.2没问题。建议release一个可用的版本吧
