### ISSUE TITLE
在运维Nacos时，怎样做容量规划

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#5000]
Nacos版本：1.4.0

服务发现：

描述：对于服务发现功能，以集群模式部署Nacos。因为“服务”和“服务实例”的数据都会存储在内存中。
且每个节点存储的是全量的数据（即每个节点保存的都是所有注册到Nacos的服务和服务实例数据）。

问题：想问下，在部署Nacos时，节点的内存需要怎样做容量规划。
我想到的方法：预估有一百万实例。每个实例预估需要2K。则一百万实例需要内存2G.

问题：还想问下，当实例数增长时，怎样能做到自动感知并扩容。
我想到的方法：配置内存的报警。到触发报警时，做扩容动作（增加但实例的内存）

配置中心：
描述：对于配置中心功能，集群方式部署，每个节点也是保存了全部的配置数据在硬盘上。

问题：硬盘的初始容量规划和何时做容量扩容。因为每个应用的配置数据的量级是有差异的。
对于这类问题，有没有比较好的经验可以分享下。

**Comment by KomachiSion** [comment]
主要由几个纬度来计算：

1. QPS/TPS：主要来源是服务发现的心跳和轮训查询，以及配置的轮训查询。
简单的计算是服务实例心跳5s一次，每个服务订阅者实例每10s查询一次，配置每30s一次，监听到有配置变更会立刻去获取对应数量的配置。大致可以推算为：实例数/5+（订阅服务数*订阅者实例数）/10+（订阅配置数*实例数）/30 = TPS，然后TPS/服务节点数，尽量保持在单台节点实际的TPS在最大支撑范围的1/3（防止一台挂掉之后，请求把另一台服务端也打挂造成雪崩）。
可以通过水平扩容节点来降低每个节点的TPS。

2. 内存，或者是GC，如果是实例数或者配置数过多导致的内存不足或GC频繁导致的问题，水平扩容可能不太能够解决问题。可能需要升配比较好用。

3. 关于硬盘，主要占用是日志和配置的缓存。服务发现持久化部分的数据不会特别多。具体使用量需要根据自己的实际情况估计。
