### ISSUE TITLE
Search config by content

### ISSUE THREAD

**Issue by libinglong** [alibaba/nacos#5008]
Sometimes we have such configs:

app1.baidu.domain=www.baidu.com
app2.baidu.domain=www.baidu.com

the domain "www.baidu.com" changes someday, we want to search all config that contain "www.baidu.com".

I have finish this future and use in our service. Could I merge this future into official repository？

**Comment by JackSun-Developer** [comment]
Yes, you can, just make a PR.

**Comment by KomachiSion** [comment]
Please not directly submit PR if you want to implement some feature.
Please provider your way how to implement this feature and discuss with PMC and committer in community.

**Comment by KomachiSion** [comment]
I think you can implement this API but do not modified old.

you can add a new one and implement it.

BTW, I think this feature will cause much cost for database. Should we open this API?
@chuntaojun @yanlinly @shiyiyue1102 @TsingLiang What's your think about?

**Comment by libinglong** [comment]
> Please not directly submit PR if you want to implement some feature.
> Please provider your way how to implement this feature and discuss with PMC and committer in community.

@KomachiSion How to contact with PMC or others, by email?

**Comment by yanlinly** [comment]
This is slow sql, It has a big impact on database performance, so you can temporarily maintain it in your own branch

**Comment by libinglong** [comment]
> This is slow sql, It has a big impact on database performance, so you can temporarily maintain it in your own branch

This is used in console, and not often used.

**Comment by libinglong** [comment]
@yanlinly Should we think about again?
Usually the config center does not need to be high-performance in every scene.
In the other hand, if one have to search the config content one by one, it is very inefficient.

Config center is not like other user-oriented services.It is a backstage management service.
We should make sure with how many configs this sql will execute extremly slowly.  :)

**Comment by KomachiSion** [comment]
> @yanlinly Should we think about again?
> Usually the config center does not need to be high-performance in every scene.
> In the other hand, if one have to search the config content one by one, it is very inefficient.
> 
> Config center is not like other user-oriented services.It is a backstage management service.
> We should make sure with how many configs this sql will execute extremly slowly. :)

**Comment by libinglong** [comment]
> When the configuration scale reaches a certain size, which is dependent on the database machine. And the slow SQL will cause the database work in a low performance, which cause other operation or transaction will be blocked and
> It will cause an unstopped problem. More and more SQL and transactions will be blocked and finally all publish configuration operation can't work. so we think this API is too risk to implementation. Even it is used only console and only with low frequent.

@KomachiSion 
Yes, It's a risk. We can add a condition such as namespace or group if there is so many configs.
Every storage system has its bottleneck. But we do not need to say yes or no right now. Declaring it is a experimental feature is also a choise.

**Comment by KomachiSion** [comment]
1. If you understand the risk and think you can accept it, you can modify by yourself like your PR. But nacos community think this risk is too high, so we don't want to open this API.
2. There are seems no one in my memory to mention a similar request, we think this is not a universal request for now.

In one word, nacos community don't think it's a good way to open a high risk API for a non-universal request. Of course, you can modify source code and use it.
