### ISSUE TITLE
Add unit tests to nacos-client module in nacos2.0

### ISSUE THREAD

**Issue by shalk** [alibaba/nacos#5011]
## Issue Description

This is a sub-issue of [ISSUE #4981]
The nacos-client module coverage rate is just 15%, Could you add more unit tests to nacos-client module?

## Anything else we need to know?

To-do list:

- [x]  Add unit tests for package com.alibaba.nacos.client.config #5016 
- [x]  Add unit tests for package com.alibaba.nacos.client.naming
- [x]  Add unit tests for package com.alibaba.nacos.client.monitor
- [x]  Add unit tests for package com.alibaba.nacos.client.security
- [x]  Add unit tests for package com.alibaba.nacos.client.identify
- [x]  Add unit tests for package com.alibaba.nacos.client.logging
- [x]  Add unit tests for package com.alibaba.nacos.client.utils

**Comment by KomachiSion** [comment]
Hi @shalk, Would you like finish this issue?

**Comment by shalk** [comment]
@KomachiSion  I can solve it
