### ISSUE TITLE
配置管理-->历史版本列表中的配置内容和操作人不一致

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#5012]
Nacos版本：1.4.0

更新配置时，com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl中256行，
配置内容使用的是oldConfigInfo。srcUser传的是本次操作的用户。

当oldConfigInfo是A用户操作的。本次操作是B用户操作的。
在历史版本列表中的数据就出现配置内容是oldConfigInfo，但是操作人是B的数据。这是不正确的数据，因为oldConfigInfo是A操作的。

**Comment by KomachiSion** [comment]
@chuntaojun Is it right?

**Comment by KomachiSion** [comment]
Fixed by #5566
