### ISSUE TITLE
1.4.1版本consistency项目源码缺少com.alibaba.nacos.consistency.entity的包和相关代码，导致编译出错

### ISSUE THREAD

**Issue by pk07an** [alibaba/nacos#5014]
1.4.1版本consistency项目源码缺少com.alibaba.nacos.consistency.entity的包和相关代码，导致编译出差
详细见：ConsistencyProtocol、ProtoMessageUtil、RequestProcessor这几个类

**Comment by horizonzy** [comment]
https://nacos.io/zh-cn/docs/faq.html#3.19
