### ISSUE TITLE
The bean 'nacosConfigurationPropertiesBinder', defined in null, could not be registered. A bean with that name has already been defined in null and overriding is disabled.

### ISSUE THREAD

**Issue by lxmSn** [alibaba/nacos#5015]
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-discovery-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>

**Comment by lxmSn** [comment]
@NacosPropertySource(dataId = "example", autoRefreshed = true)

**Comment by lxmSn** [comment]
启动类上去掉下面注解不再报错
@EnableJpaAuditing(auditorAwareRef = "auditorAware")
@ComponentScan({"com.*"})

**Comment by KomachiSion** [comment]
应该是用法错误，试一下nacos-spring-boot的example 或者看一下wiki。
