### ISSUE TITLE
GroupKey in nacos-client config have some bug

### ISSUE THREAD

**Issue by shalk** [alibaba/nacos#5018]
**Describe the bug**
1.` GroupKey.getKey` will not check dataId or groupId is blank
2. `GroupKey.parseKey("f++bar")` get wrong result [f, bar, null]

**Expected behavior**
1. GroupKey.getKey should throw RunTimeException, if dataId or groupId is blank
2. GroupKey.parseKey("f++bar") should throw IllegalArgumentException

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

these unit tests will fail.
```
public class GroupKeyTest {
   @Rule
    public final ExpectedException thrown = ExpectedException.none();
    
    @Test
    public void testParseKeyIllegalArgumentException4() {
        thrown.expect(IllegalArgumentException.class);
        GroupKey.parseKey("f++bar");
    }
    
    @Test
    public void testGetKeyDatIdParam() {
        thrown.expect(IllegalArgumentException.class);
        GroupKey.getKey("", "a");
    }
    
    @Test
    public void testGetKeyGroupParam() {
        thrown.expect(IllegalArgumentException.class);
        GroupKey.getKey("a", "");
    }
}
```
**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version  nacos-client develop branch
 - Module [client/config]

**Additional context**

**Comment by shiyiyue1102** [comment]
dataId or groupId is blank  should not be allowed,  "DEFAULT_GROUP" will be set outside if groupId is empty

**Comment by shalk** [comment]
> dataId or groupId is blank should not be allowed, "DEFAULT_GROUP" will be set outside if groupId is empty
@shiyiyue1102  this code will not throw exception,

```
   String dataId = "";
        String group = "";
        configService.addListener(dataId, group, new Listener() {
            @Override
            public void receiveConfigInfo(String configInfo) {
                System.out.println("receive:" + configInfo);
            }
            
            @Override
            public Executor getExecutor() {
                return null;
            }
        });
        System.out.println("group = " + group);
```

null2defaultGroup will check group is null, not empty
```
    public void addTenantListeners(String dataId, String group, List<? extends Listener> listeners)
            throws NacosException {
        group = null2defaultGroup(group);
```

**Comment by shiyiyue1102** [comment]
> > dataId or groupId is blank should not be allowed, "DEFAULT_GROUP" will be set outside if groupId is empty
> 
> @shiyiyue1102 this code will not throw exception,
> 
> ```
>    String dataId = "";
>         String group = "";
>         configService.addListener(dataId, group, new Listener() {
>             @Override
>             public void receiveConfigInfo(String configInfo) {
>                 System.out.println("receive:" + configInfo);
>             }
>             
>             @Override
>             public Executor getExecutor() {
>                 return null;
>             }
>         });
>         System.out.println("group = " + group);
> ```
> 
> null2defaultGroup will check group is null, not empty
> 
> ```
>     public void addTenantListeners(String dataId, String group, List<? extends Listener> listeners)
>             throws NacosException {
>         group = null2defaultGroup(group);
> ```

Yes,because 'DEFAULT_GROUP' will be set if group is blank, if we focus on the method GroupKey.getKey ,blank group is not valid and should throw exception.

**Comment by shalk** [comment]
> > > dataId or groupId is blank should not be allowed, "DEFAULT_GROUP" will be set outside if groupId is empty
> > 
> > 
> > @shiyiyue1102 this code will not throw exception,
> > ```
> >    String dataId = "";
> >         String group = "";
> >         configService.addListener(dataId, group, new Listener() {
> >             @Override
> >             public void receiveConfigInfo(String configInfo) {
> >                 System.out.println("receive:" + configInfo);
> >             }
> >             
> >             @Override
> >             public Executor getExecutor() {
> >                 return null;
> >             }
> >         });
> >         System.out.println("group = " + group);
> > ```
> > 
> > 
> > null2defaultGroup will check group is null, not empty
> > ```
> >     public void addTenantListeners(String dataId, String group, List<? extends Listener> listeners)
> >             throws NacosException {
> >         group = null2defaultGroup(group);
> > ```
> 
> Yes,because 'DEFAULT_GROUP' will be set if group is blank, if we focus on the method GroupKey.getKey ,blank group is not valid and should throw exception.

so we could change null2defaultGroup to blank2defaultGroup,  and add param check in GroupKey.
