### ISSUE TITLE
 Problem in some extreme scenarios of distro protocol

### ISSUE THREAD

**Issue by sourirer** [alibaba/nacos#5020]
**Is your feature request related to a problem? Please describe.**

The situation is complex so i will use Chinese for describe.

场景一（三节点情况下，可断网位置为2）:

1，服务1，发送到nacos1，  nacos1<-->nacos2,  nacos2<-x->nacos3, nacos1<-->nacos3
  1.1 nacos1算出服务负责节点为nacos2或者nacos3，nacos2或者nacos3算出服务负责节点为nacos1，直接报错，此时违背ap

2，服务1，nacos1<-->nacos2,  nacos2<-x->nacos3, nacos1<-->nacos3， 
  2.1 发送到nacos2或者nacos3，然后此时计算服务负责节点都为自身，则数据不一致；
  2.2 发送到nacos2或者nacos3，然后计算服务负责节点为nacos1，但是nacos1计算服务负责节点不为自己负责，则报错，违背ap

场景二：以上场景可增加节点，节点增加后，可断网位置增多，场景呈几何级数复杂化。
  如： 1，2，3，4四个节点， 可断网位置增加为3

**Describe the solution you'd like**

In any net situation, nacos can work normally.

**Describe alternatives you've considered**

I didn't find some way to solve the situation so i think may be we can discuss about this 

**Additional context**

**Comment by KomachiSion** [comment]
Your description situation will cause some of service can't be handle in current distro.
It's hard to solve this situation for HTTP because of random request.

But this situation is much low probability. **ONLY** each node has their net dedicated Line and connection other nodes for each directly will happen. In actual situation. If node2 disconnect with other centers or other machines, it will disconnect with other all nodes but no only one node.

**Comment by sourirer** [comment]
> Your description situation will cause some of service can't be handle in current distro.
> It's hard to solve this situation for HTTP because of random request.
> 
> But this situation is much low probability. **ONLY** each node has their net dedicated Line and connection other nodes for each directly will happen. In actual situation. If node2 disconnect with other centers or other machines, it will disconnect with other all nodes but no only one node.

yes,but it may occur if you deploy three nacos node in different region and the net disconnect between only two of the three and it's possible.
Some accident or natural disaster could cause that so would you handle with this situation?

**Comment by KomachiSion** [comment]
> > Your description situation will cause some of service can't be handle in current distro.
> > It's hard to solve this situation for HTTP because of random request.
> > But this situation is much low probability. **ONLY** each node has their net dedicated Line and connection other nodes for each directly will happen. In actual situation. If node2 disconnect with other centers or other machines, it will disconnect with other all nodes but no only one node.
> 
> yes,but it may occur if you deploy three nacos node in different region and the net disconnect between only two of the three and it's possible.
> Some accident or natural disaster could cause that so would you handle with this situation?

We will solve it in nacos2.0 with long connection. In nacos 2.0(both server and client), the client request will handle in connected server node.

**Comment by KomachiSion** [comment]
the response server node will change to the connected server, not calculate by hash. So do no need redirect. For sync data, it will be broadcasted, even it disconnect only one node.

So we think it will be solved.

**Comment by sourirer** [comment]
> the response server node will change to the connected server, not calculate by hash. So do no need redirect. For sync data, it will be broadcasted, even it disconnect only one node.
> 
> So we think it will be solved.

So, you mean server node will response for any client request. 
No longer dispatch request by service?

**Comment by KomachiSion** [comment]
Yes, If use long connection.

**Comment by sourirer** [comment]
> Yes, If use long connection.

OK.
Thx for reply.
I will check the nacos codes of 2.0 .
