### ISSUE TITLE
nacos config 能关闭默认请求吗？

### ISSUE THREAD

**Issue by childewuque** [alibaba/nacos#5021]
环境：
  <groupId>com.alibaba.cloud</groupId>
  <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
  <version>2.2.3.RELEASE</version>

配置：
> 
spring:
  cloud: 
    nacos:
        config:
           file-extension: yaml
           namespace: order
> 

项目名：detail，在nacos里只配置了detail名的文件

能正确访问到项目名detail的配置，但是还会额外请求一些地址如下，取不到内容，不影响使用，但是监控会报出来，有没有办法关闭这些默认访问呢？
http://172.12.3.3:30048/nacos/v1/cs/configs?dataId=detail.yaml&tenant=order&group=DEFAULT_GROUP
http://172.12.3.3:30048/nacos/v1/cs/configs?dataId=detail-kubernetes.yaml&tenant=order&group=DEFAULT_GROUP
http://172.12.3.3:30048/nacos/v1/cs/configs?dataId=detail-dev.yaml&tenant=order&group=DEFAULT_GROUP
...

**Comment by KomachiSion** [comment]
这应该和配置有关， 会有这些访问说明你告诉nacos-config-client你需要监听了这几个dataId。

**Comment by childewuque** [comment]
> 这应该和配置有关， 会有这些访问说明你告诉nacos-config-client你需要监听了这几个dataId。

在哪儿配置呢？
有的项目 只是多配了多个配置文件：
        extension-configs[0]:
          data‐id: ${spring.application.name}-common.yaml
          refresh: true
        shared-configs[0]:
          data-id: company-common.yaml
          refresh: false

所有项目除了主贴里的配置，另外就配置了启动环境参数-Dspring.profiles.active=dev，nacos地址和日志level:
---
spring:
  profiles: dev
  cloud:
    nacos:
      config:
        server-addr: 172.25.30.11:30048

logging:
  level:
    com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder: DEBUG

**Comment by childewuque** [comment]
<nacos-client-version>2.2.3.RELEASE</nacos-client-version>
      
  <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>${nacos-client-version}</version>
            </dependency>

**Comment by KomachiSion** [comment]
看spring-cloud-alibaba的wiki，或者问一下spring-cloud-alibaba社区，你这个问题应该不是nacos-client的问题。
