### ISSUE TITLE
多种数据支持什么时候上线？

### ISSUE THREAD

**Issue by ly3299297** [alibaba/nacos#5023]
请问一下，什么时候上线多数据库支持，比如oracle

**Comment by haoyann** [comment]
这个分支feature_multiple_datasource_support，现在是支持oracle的

**Comment by ly3299297** [comment]
请问一下，有支持国产数据库的计划吗，有的话大概什么时候能上？

**Comment by KomachiSion** [comment]
多数据库支持还需要大量测试和性能优化， 短期内暂时不会发布，如果有需要，通过分支feature_multiple_datasource_support进行试用。
