### ISSUE TITLE
从1.4.0将raft协议实现升级为jraft,jraft依赖sofa-bolt，但是我看到打出来的包，nacos-server.jar中并无 bolt  jar包，不知是否会影响功能使用

### ISSUE THREAD

**Issue by IceFoxs** [alibaba/nacos#5024]
**Describe the bug**
从1.4.0将raft协议实现升级为jraft,jraft依赖sofa-bolt，但是我看到打出来的包，nacos-server.jar中并无 bolt  jar包，不知是否会影响功能使用.

**Expected behavior**
![image](https://user-images.githubusercontent.com/26451038/110124788-7d75c480-7dfd-11eb-90ad-85a38b75c940.png)
![image](https://user-images.githubusercontent.com/26451038/110124897-a39b6480-7dfd-11eb-9806-e419dad06f3e.png)

**Acutally behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 

**Additional context**

**Comment by KomachiSion** [comment]
nacos依赖的是jraft的grpc实现，没有使用bolt
