### ISSUE TITLE
nacos源码consistency模块缺少com.alibaba.nacos.consistency.entity包

### ISSUE THREAD

**Issue by xulifeng123789** [alibaba/nacos#5025]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by haoyann** [comment]
`mvn clean compile`
doc: https://nacos.io/zh-cn/docs/faq.html
