### ISSUE TITLE
`UpdateTask`  some logic errors

### ISSUE THREAD

**Issue by haoyann** [alibaba/nacos#5028]
**Describe the bug**
Finally code block will always execute. So `incFailCount()` will always execute. And when `queryInstancesOfService` error delayTime = -1, this task will also be stopped.
Why need add `delayTime > 0` check , should a default value be given.
https://github.com/alibaba/nacos/blob/eb36581c2c4b0a9bfc0a7837452285d0afcf530d/client/src/main/java/com/alibaba/nacos/client/naming/core/ServiceInfoUpdateService.java#L190-L201

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.0.0, nacos-client 2.0.0]
 - Module [e.g. naming]
 - SDK [java]

**Additional context**

**Comment by shalk** [comment]
this logic is added from https://github.com/alibaba/nacos/pull/2546
