### ISSUE TITLE
配置从properties类型改成yaml类型后,客户端无法获取到最新配置

### ISSUE THREAD

**Issue by ACE-Caedmon** [alibaba/nacos#503]
版本:v0.7.0
BUG描述:
一开始新增一个配置如下
![image](https://user-images.githubusercontent.com/5479755/50339765-39b37f00-0553-11e9-8d34-8d40ee3f092d.png)
然后我将配置从properties类型改成yaml类型,并修改password的值，然后发布
![image](https://user-images.githubusercontent.com/5479755/50339836-754e4900-0553-11e9-8d91-f0b024556dd9.png)
这时，客户端无法接受到最新的配置变更

**Comment by foreveryang321** [comment]
遇到同样的问题.

spring.username: root
spring.password: 123355
这个格式可以读取

**Comment by foreveryang321** [comment]
目前版本的nacos还不支持yaml的缩进格式，据说后续会支持。

如果你想用这种格式的话，可以考虑使用`spring-cloud-starter-alibaba-nacos-config` 0.2.1.RELEASE，它是支持yaml的缩进格式的。

**Comment by hxy1991** [comment]
- Nacos Spring (nacos-spring-context)  和 Nacos Spring Boot (nacos-config-spring-boot-starter) 目前还不支持 yaml 格式的，后续会支持 [issues#33](https://github.com/nacos-group/nacos-spring-project/issues/33)。
- Nacos Spring Cloud (spring-cloud-starter-alibaba-nacos-config) 是已经支持的了。
