### ISSUE TITLE
nacos client 1.4.1 auth without username with the same as the nacos default username/password as nacos/nacos,will throw 403 error

### ISSUE THREAD

**Issue by chensp0668** [alibaba/nacos#5043]
**Describe the bug**

**Expected behavior**
nacos server default username/password as nacos/nacos,while I try to open the nacos auth for the client verify,I config the application.properties the 'nacos.core.auth.enabled=true' and 'nacos.core.auth.enable.userAgentAuthWhite=false',and 'nacos.core.auth.server.identity.key=test' and 'nacos.core.auth.server.identity.value=test'
![image](https://user-images.githubusercontent.com/3975296/110264578-909eb500-7ff4-11eb-8b1a-a64334da2035.png)

The applicaion with the nacos client 1.4.1 connect error with 403 as below screenshot:
![image](https://user-images.githubusercontent.com/3975296/110264677-d0fe3300-7ff4-11eb-927f-596a151c608a.png)

In the nacos web sit guardline as below
![image](https://user-images.githubusercontent.com/3975296/110264815-1d497300-7ff5-11eb-8666-d9e43c43d8f8.png)
The relative package pom as below:
        springBootVersion = '2.3.3.RELEASE'
        springCloudVersion = 'Hoxton.SR8'
        aliCloudVersion = '2.2.5.RELEASE'

But while I user the default username/password:nacos/nacos,the client can connect to the server as well.
I seems that the application auth has a bug as above mentions.
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos

**Comment by KomachiSion** [comment]
This properties is not username and password, it is an identity for server part communication. The client should only use username and password.

I think you need read the document context of your screenshot part.
