### ISSUE TITLE
spring+dubbo项目使用 nacos作为配置中心,Environment环境变量可以去到nacos的值使用NacosValue注解获取会报错

### ISSUE THREAD

**Issue by zhengtu8080** [alibaba/nacos#5044]
![image](https://user-images.githubusercontent.com/22142075/110265103-c09a8800-7ff5-11eb-8e83-503ca4d75368.png)

**Comment by KomachiSion** [comment]
spring boot + dubbo？ or spring cloud + dubbo?

**Comment by KomachiSion** [comment]
And what's the error information?

Which version you used?

Please use issue template to description.

**Comment by zhengtu8080** [comment]
ssm + dubbo



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 SionYang"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 上午10:11
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "3（8）。图"<873519916@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] spring+dubbo项目使用 nacos作为配置中心,Environment环境变量可以去到nacos的值使用NacosValue注解获取会报错 (#5044)





 
spring boot + dubbo？ or spring cloud + dubbo?

**Comment by zhengtu8080** [comment]
spring-4.3.24 
![image](https://user-images.githubusercontent.com/22142075/110265749-40752200-7ff7-11eb-929b-2ba73f354a8e.png)

**Comment by JackSun-Developer** [comment]
这个是你的使用方法不对，改成${cc:cc}$就能跑通了。

**Comment by JackSun-Developer** [comment]
Spring自带的StringValueResolver会对${cc:dd}$进行解析，解析出来"dd"作为该配置的指，你的配置不符合Spring解析的格式，自然就报错了。

**Comment by zhengtu8080** [comment]
应该是不存在cc的配置项才会使用dd作为默认值注入进去,只要这样配置是可以正常启动的，但是配置的值一直都是dd，但是我在nacos服务器里面是配置了cc的配置项了，而且我在spring启动的时候通过Environment获取cc的配置是可以获取到的，我感觉就像是注入的属性在前，去nacos拉取属性在后导致注入没有值报的错
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JackSun-Developer"<notifications@github.com&gt;; 
发送时间: 2021年3月11日(星期四) 上午10:00
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "3（8）。图"<873519916@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] spring+dubbo项目使用 nacos作为配置中心,Environment环境变量可以去到nacos的值使用NacosValue注解获取会报错 (#5044)





 
Spring自带的StringValueResolver会对${cc:dd}$进行解析，解析出来"dd"作为该配置的指，你的配置不符合Spring解析的格式，自然就报错了。

**Comment by JackSun-Developer** [comment]
> 应该是不存在cc的配置项才会使用dd作为默认值注入进去,只要这样配置是可以正常启动的，但是配置的值一直都是dd，但是我在nacos服务器里面是配置了cc的配置项了，而且我在spring启动的时候通过Environment获取cc的配置是可以获取到的，我感觉就像是注入的属性在前，去nacos拉取属性在后导致注入没有值报的错
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "JackSun-Developer"<notifications@github.com&gt;; 发送时间: 2021年3月11日(星期四) 上午10:00 收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 抄送: "3（8）。图"<873519916@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [alibaba/nacos] spring+dubbo项目使用 nacos作为配置中心,Environment环境变量可以去到nacos的值使用NacosValue注解获取会报错 (#5044) Spring自带的StringValueResolver会对${cc:dd}$进行解析，解析出来"dd"作为该配置的指，你的配置不符合Spring解析的格式，自然就报错了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

代码里就得写成@NacosValue("${cc:dd}$")，才是正确的，能够被解析

你报错的代码里写的是@NacosValue("${cc}$")，这样会让Spring的解析器解析不出来

**Comment by JackSun-Developer** [comment]
所以最后跑通了对吧？@NacosValue能够获取nacos端的配置+动态刷新，我这边复现都没有问题。

**Comment by zhengtu8080** [comment]
![cc](https://user-images.githubusercontent.com/22142075/111585074-c2d0c380-87f9-11eb-9226-ac5c77533d33.png)
![cc2](https://user-images.githubusercontent.com/22142075/111585087-c82e0e00-87f9-11eb-81cd-ad90b9a378be.png)
按照你的配置，启动时没有问题的，但是@NacosValue注解时获取不到配置中心的值的，但是ENV里面时可以获取到配置中心的值 的

**Comment by yipixiaofeiyang** [comment]
现在我也碰到了这个问题,  最后发现nacos没有被spring容器管理, nacos在spring和springmvc容器都存一份, 项目可以正常使用, 但是配置内容改动, 却不能实时刷新, 这样没啥意义, 还不如自己用redis写个配置中心
在他们的demo中, 采用的单一的springmvc, 直接托管给springmvc容器所以没问题, 
现在这个问题解决了吗?   我也想用, 但是这问题直接影响到项目结构, 可能会放弃nacos
