### ISSUE TITLE
log日志如何看出是连的哪个数据库

### ISSUE THREAD

**Issue by ly3299297** [alibaba/nacos#5051]
请问一下，log日志如何看出是连的哪个数据库

**Comment by JackSun-Developer** [comment]
![Uploading image.png…]()

**Comment by JackSun-Developer** [comment]
nacos的config模块使用数据库，有两种选择，外置mysql或者内置derby，从start.out日志可以看

**Comment by KomachiSion** [comment]
nacos/logs/start.out 

启动完成后可以看到

`
Nacos started successfully in cluster mode. use *embedded* storage
`
