### ISSUE TITLE
请问一下多数据源哪个分支如何配置使用？

### ISSUE THREAD

**Issue by ly3299297** [alibaba/nacos#5052]
请问一下多数据源哪个分支如何配置使用？

**Comment by haoyann** [comment]
1. 编译： `mvn clean compile`
2. 数据库初始化脚本: `/distribution/conf`
3. 分支：feature_multiple_datasource_support
4. 配置文件：
```
#nacos.datasource.type=MYSQL
#
#nacos.datasource.relational.dsList[0].url=jdbc:mysql://localhost:3306/nacos-devtest?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#nacos.datasource.relational.dsList[0].username=root
#nacos.datasource.relational.dsList[0].password=root
#nacos.datasource.relational.dsList[0].driver-class-name=com.mysql.jdbc.Driver
#nacos.datasource.relational.dsList[0].hikari.connection-timeout=10000
#nacos.datasource.relational.dsList[0].hikari.idle-timeout=120000
#nacos.datasource.relational.dsList[0].hikari.max-lifetime=240000
#nacos.datasource.relational.dsList[0].hikari.maximum-pool-size=20
#nacos.datasource.relational.dsList[0].hikari.data-source-properties.cachePrepStmts=true
#nacos.datasource.relational.dsList[0].hikari.data-source-properties.prepStmtCacheSize=250
#nacos.datasource.relational.dsList[0].hikari.data-source-properties.prepStmtCacheSqlLimit=2048
#nacos.datasource.relational.dsList[0].hikari.connection-test-query=SELECT 1 FROM dual
```

**Comment by ly3299297** [comment]
![image](https://user-images.githubusercontent.com/22093961/110296192-01fa5a00-802d-11eb-81e9-04240ed91ffd.png)

**Comment by ly3299297** [comment]
报错了

**Comment by haoyann** [comment]
检查一下你的配置，我可以正常启动。

**Comment by ly3299297** [comment]
![image](https://user-images.githubusercontent.com/22093961/110297758-ca8cad00-802e-11eb-92f1-2062f583a4cb.png)
![image](https://user-images.githubusercontent.com/22093961/110297870-ded0aa00-802e-11eb-9367-d1c5d897374e.png)

**Comment by haoyann** [comment]
上面的不用配置了，使用下面的配置。
![image](https://user-images.githubusercontent.com/43994656/110298043-14759300-802f-11eb-8442-a9e367a21590.png)

**Comment by ly3299297** [comment]
还是不行，我是>mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U
打包的

**Comment by ly3299297** [comment]
请问一下，如果我想在这个分支支持一下神通数据库（跟oracle数据库很像的一个国产数据库），需要改哪些东西

**Comment by haoyann** [comment]
现在多数据源的方案是用的jpa，要看jpa支不支持这个数据库。

**Comment by ly3299297** [comment]
jap是支持的，但是我现在不知道还需要配置哪些地方或者·改动哪些地方

**Comment by haoyann** [comment]
> jap是支持的，但是我现在不知道还需要配置哪些地方或者·改动哪些地方

这个就需要自己去验证了。

**Comment by ly3299297** [comment]
适配oscar数据库：
![image](https://user-images.githubusercontent.com/22093961/110321246-5eb93d00-804c-11eb-8803-39c1656b4ce8.png)
![image](https://user-images.githubusercontent.com/22093961/110321247-5eb93d00-804c-11eb-8531-b42593db5f64.png)
![image](https://user-images.githubusercontent.com/22093961/110321268-6842a500-804c-11eb-96a6-7c9ab19736b4.png)
报错：
![image](https://user-images.githubusercontent.com/22093961/110321351-87413700-804c-11eb-8137-1fb6dd579ff0.png)

帮我看一下还需要改哪些地方

**Comment by haoyann** [comment]
`com.alibaba.nacos.config.server.configuration.datasource.DataSourceType`，这个枚举加一下

**Comment by haoyann** [comment]
`com.alibaba.nacos.config.server.configuration.RelationalDataSourceConfiguration`的@ConditionalOnExpression加一下，然后主要debug看一下这个类有没有异常`com.alibaba.nacos.config.server.configuration.datasource.DynamicDataSource`。

**Comment by ly3299297** [comment]
![image](https://user-images.githubusercontent.com/22093961/110404561-09b41000-80ba-11eb-9886-06273e2bf4c4.png)

**Comment by ly3299297** [comment]
这一步就报错了，还没到初始化DynamicDataSource

**Comment by ly3299297** [comment]
![image](https://user-images.githubusercontent.com/22093961/110405683-e7bb8d00-80bb-11eb-93a3-07298235347c.png)

**Comment by ly3299297** [comment]
我用mysql可以正常起，但是换成oscar就报错，AuthConfigs这个类没加载进来
![image](https://user-images.githubusercontent.com/22093961/110409157-cc538080-80c1-11eb-869b-abb7908b078b.png)

**Comment by haoyann** [comment]
启动的时候这个地方打断点`com.alibaba.nacos.config.server.configuration.datasource.DynamicDataSource.SelectMasterTask#run`
