### ISSUE TITLE
当客户端配置namespace为public时，LongPolling 会毫无意义的进行死循环拉取配置，然而配置无新变动

### ISSUE THREAD

**Issue by evin0329** [alibaba/nacos#5056]
### Nacos 1.4.1
J### ava 1.8
### 使用样例代码： com.alibaba.nacos.example;.ConfigExample
public class ConfigExample {

    public static void main(String[] args) throws NacosException, InterruptedException {
        String serverAddr = "localhost";
        String dataId = "test";
        String group = "DEFAULT_GROUP";
        Properties properties = new Properties();
        properties.put("serverAddr", serverAddr);
        properties.put("namespace", "public");
        ConfigService configService = NacosFactory.createConfigService(properties);
        String content = configService.getConfig(dataId, group, 5000);
        System.out.println(content);
        configService.addListener(dataId, group, new Listener() {
            @Override
            public void receiveConfigInfo(String configInfo) {
                System.out.println("receive:" + configInfo);
            }

            @Override
            public Executor getExecutor() {
                return null;
            }
        });

//        boolean isPublishOk = configService.publishConfig(dataId, group, "content");
//        System.out.println(isPublishOk);
//
//        Thread.sleep(3000);
//        content = configService.getConfig(dataId, group, 5000);
//        System.out.println(content);

//        boolean isRemoveOk = configService.removeConfig(dataId, group);
//        System.out.println(isRemoveOk);
//        Thread.sleep(3000);
//
//        content = configService.getConfig(dataId, group, 5000);
//        System.out.println(content);
//        Thread.sleep(300000);

        LockSupport.park();

    }
}

### 客户端longPolling：
![image](https://user-images.githubusercontent.com/35405705/110315095-bdc68400-8043-11eb-8695-0dd45a258c91.png)

### 服务端处理：
![image](https://user-images.githubusercontent.com/35405705/110315239-f4040380-8043-11eb-9f44-ae5e4f022231.png)

### 关键代码在ConfigCacheService.isUptodate(groupKey, clientMd5, ip, tag);
![image](https://user-images.githubusercontent.com/35405705/110315542-607f0280-8044-11eb-820d-c2b881108fcd.png)
![image](https://user-images.githubusercontent.com/35405705/110316841-41817000-8046-11eb-9ab6-1efb60675666.png)

1. 该代码片段 isUptodate的返回值 未考虑过服务端groupKey的serverMd5为空的情况 且与客户端groupKey携带的clientMd5比较时的意外情况（实际上这个MD5是正确的 是从服务端拿到的配置 计算而成的）

2. 得出问题在根据客户端在配置namespace=publc时能获取到配置内容，但在longPolling时，ConfigCacheService.getContentMd5 获取不到该namespace的Cache。

3.  问题：错误namespace为什么能获取到配置？
    定位到服务端获取配置代码：
![image](https://user-images.githubusercontent.com/35405705/110317949-d2a51680-8047-11eb-9467-6cce13cffaff.png)
![image](https://user-images.githubusercontent.com/35405705/110318031-f36d6c00-8047-11eb-9468-c3575172ded1.png)
![image](https://user-images.githubusercontent.com/35405705/110318071-fd8f6a80-8047-11eb-8660-f3f5e26df9a0.png)

NamespaceUtil的判断让namespace为public时，会出现导致能获取到配置，进而引发当前错误。

end

**Comment by haoyann** [comment]
Refer to #4682
