### ISSUE TITLE
控制台中更改服务实例的元数据，是否会被实例的下一次心跳覆盖

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#5058]
Nacos版本：1.4.0

在控制台中进行服务实例的元数据修改。本次修改的数据是不是会被
实例的下一次心跳中携带的元数据覆盖掉

**Comment by JackSun-Developer** [comment]
nacos有几种方式，SCA、Dubbo、控制台、OpenAPI、Client，可以修改后台数据。
您的意思我理解是用其他方式了服务（SCA、Dubbo、Client等），然后用控制台更改了服务实例的元数据，修改的元数据会不会被其他方式上报的心跳所影响。

我用Dubbo试了一下，不会被覆盖掉；SCA不太清楚。
OpenAPI也不会上报心跳，所以排除。
Nacos-Client方式倒有可能会导致您说的问题，（前提是必须用
>public void registerInstance(String serviceName, Instance instance)
这个API）

但手动修改一个非持久化实例的元数据，本身就是一种违规操作；正确的做法是用下面这个API来修改metadata

>public void updateInstance(String serviceName, Instance instance)

**Comment by wanghuigithub** [comment]
> nacos有几种方式，SCA、Dubbo、控制台、OpenAPI、Client，可以修改后台数据。
> 您的意思我理解是用SCA、Dubbo、Client等方式注册了服务，然后用控制台更改了服务实例的元数据，修改的元数据可能会被其他方式上报的心跳所覆盖。
> 
> 我用Dubbo试了一下，不会被覆盖掉；SCA有待进一步测试。
> OpenAPI也不会上报心跳，所以排除。
> Nacos-Client方式倒有可能会导致您说的问题，（前提是必须用
> 
> > public void registerInstance(String serviceName, Instance instance)
> 
> 这个API）
> 
> 但手动在控制台修改一个非持久化实例的元数据，本身就是一种违规操作；正确的做法是用下面这个API来修改metadata
> 
> > public void updateInstance(String serviceName, Instance instance)


1、我是使用的/nacos/v1/ns/instance/beat这个open api来一直发送心跳。
2、SCA是指？
3、不建议使用控制台更新实例的元数据？主要是看到在Nacos控制台中是可以修改实例的元数据的。
所以问下这块的使用问题。

**Comment by KomachiSion** [comment]
1. 目前如果临时实例没有续上心跳导致被摘除后，再被心跳续约回去，会导致元数据被心跳信息覆盖，但是是正常现象。
2. 使用/nacos/v1/ns/instance/beat发送心跳没有问题，在没有因删除/非健康移除等问题导致实例被删除情况下，beat接口不会覆盖已有任何信息
3. SCA=Spring Cloud Alibaba
4. 可能是他的表述错误，应该是不推荐用client的register和update接口来更新元数据，而应该通过控制台/openAPI来更新元数据。

**Comment by JackSun-Developer** [comment]
SCA指Springcloud-alibaba，Nacos控制台修改非持久化的元数据，是不太好的

>1、我是使用的/nacos/v1/ns/instance/beat这个open api来一直发送心跳

你可否帮忙测试一下，先在控制台修改了元数据，然后用这个OpenAPI来进行心跳发送，看是否原来修改的元数据会被覆盖。



在 2021-03-09 16:18:06，"wanghuigithub" <notifications@github.com> 写道：

nacos有几种方式，SCA、Dubbo、控制台、OpenAPI、Client，可以修改后台数据。
您的意思我理解是用SCA、Dubbo、Client等方式注册了服务，然后用控制台更改了服务实例的元数据，修改的元数据可能会被其他方式上报的心跳所覆盖。

我用Dubbo试了一下，不会被覆盖掉；SCA有待进一步测试。
OpenAPI也不会上报心跳，所以排除。
Nacos-Client方式倒有可能会导致您说的问题，（前提是必须用

public void registerInstance(String serviceName, Instance instance)

这个API）

但手动在控制台修改一个非持久化实例的元数据，本身就是一种违规操作；正确的做法是用下面这个API来修改metadata

public void updateInstance(String serviceName, Instance instance)

1、我是使用的/nacos/v1/ns/instance/beat这个open api来一直发送心跳。
2、SCA是指？
3、不建议使用控制台更新实例的元数据？主要是看到在Nacos控制台中是可以修改实例的元数据的。
所以问下这块的使用问题。
