### ISSUE TITLE
使用JSON类型的配置，如何解析这个JSON配置里的数组

### ISSUE THREAD

**Issue by HumorChen** [alibaba/nacos#5061]
![image](https://user-images.githubusercontent.com/46368749/110424073-2a419180-80dd-11eb-9006-cb184505a926.png)
![image](https://user-images.githubusercontent.com/46368749/110424142-480ef680-80dd-11eb-8a0b-91544394b16f.png)

像JSON的配置如何去读取数组、对象，注入到java里去，能否转成JSONObject

**Comment by JackSun-Developer** [comment]
这个我来跟进吧。

**Comment by JackSun-Developer** [comment]
nacos里面是用的Spring自带的

>AbstractBeanFactory.resolveEmbeddedValue(String value)

读取及解析value字段，这个和Spring的实现方式是同步的。如果封装成com.fasterxml.jackson.databind.node.JsonNode来解析，需要引入新的依赖，也会丧失通用性，不太合理。

**Comment by HumorChen** [comment]
那我该如何解析数组呢，有没有示范文档

**Comment by sunwenT** [comment]
同样的问题，尝试了@Value的EL形式依旧报错。只能使用代码来获取吗？还是将JSON文件转成YAML文件？

**Comment by HumorChen** [comment]
对啊，这个问题就很尴尬，我现在都是只能用字符串自己解析

**Comment by sunwenT** [comment]
兄弟，你怎么配置的可以获取字符串？

**Comment by HumorChen** [comment]
> 兄弟，你怎么配置的可以获取字符串？
直接做一条字符串获取，比如数组  1,2,3然后去split(",")

**Comment by sunwenT** [comment]
我的更复杂，我的是json数组，里面是键值对，比如
{person:[{name:zhangsan, age:10}, {name:lisi, age:20}],...}

**Comment by sunwenT** [comment]
估计用@value是不行了，但是如果用 ConfigService 的话，应该就不需要引入 nacos-config 包了，直接在代码中找到 yaml 文件里面配置的 data-id 直接取然后解析。

**Comment by HumorChen** [comment]
> 估计用@value是不行了，但是如果用 ConfigService 的话，应该就不需要引入 nacos-config 包了，直接在代码中找到 yaml 文件里面配置的 data-id 直接取然后解析。
要么做一个整的字符串，然后JSONObject去解析，或者你往数据库指呗，指向一个数据库记录的id和版本，版本或者id变了就重新去数据库加载

**Comment by sunwenT** [comment]
两个都不方便，字符串后续修改的话不太方便；从数据库找，这个配置中心的意义就不大了。看看官方咋回复吧

**Comment by JackSun-Developer** [comment]
目前nacos-spring对于json的处理方式是最基础的（单节点），没有对于复杂的json的支持，因为复杂json的情况太多了，这一块可以根据需要自己进行封装。

**Comment by zhongjunDeng** [comment]
这个问题现在有解决的办法吗
