### ISSUE TITLE
RefreshScope 添加到Controller类上， 修改配置不生效

### ISSUE THREAD

**Issue by miludedeng** [alibaba/nacos#507]
@RestController
@RefreshScope
public class IndexController {

    @Value("${user}")
    String user;

    @Value("${age}")
    int age;

    @GetMapping("/user")
    @RefreshScope
    public String index(){
        return String.format("user: %s, age: %d", user, age);
    }
}

**Comment by ancientelves** [comment]
+1 我的也不生效

**Comment by hxy1991** [comment]
也可以请参看下：
- [quick-start-spring-cloud](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html)
- [nacos-spring-cloud-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example)

**Comment by yanxiaojun617** [comment]
你的配置要是在共享配置文件，要如下方式启用刷新，参考：https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html
  cloud:
    nacos:
      config:
        # 配置中心地址
        server-addr: 192.168.88.5:8848
        # 配置文件格式
        file-extension: yaml
        # 共享配置
        shared-configs:
          - data-id : demo-default-${spring.profiles.active}.yaml
            # 让扩展配置刷新
            refresh : true

**Comment by yanxiaojun617** [comment]
你的配置要是在共享配置文件，要如下方式启用刷新，参考：https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html
```
  cloud:
    nacos:
      config:
        # 配置中心地址
        server-addr: 192.168.88.5:8848
        # 配置文件格式
        file-extension: yaml
        # 共享配置
        shared-configs:
          - data-id : demo-default-${spring.profiles.active}.yaml
            # 让扩展配置刷新
            refresh : true
```
