### ISSUE TITLE
Non-ephemeral details page `healthy` status  error 

### ISSUE THREAD

**Issue by haoyann** [alibaba/nacos#5070]
**Describe the bug**
The client has stopped, the list page is displayed correctly, and the detail page is wrong.

![image](https://user-images.githubusercontent.com/43994656/110620667-3c522b80-81d4-11eb-9626-af9c0712e1fc.png)

![image](https://user-images.githubusercontent.com/43994656/110620691-483ded80-81d4-11eb-8aa9-977f1865370d.png)

`com.alibaba.nacos.naming.core.v2.index.ServiceStorage#getData`
![image](https://user-images.githubusercontent.com/43994656/110622115-fe560700-81d5-11eb-916b-8830ba49a757.png)

`com.alibaba.nacos.naming.utils.ServiceUtil#selectInstances`
![image](https://user-images.githubusercontent.com/43994656/110622261-36f5e080-81d6-11eb-9a4c-bc931b874f75.png)

`com.alibaba.nacos.naming.utils.ServiceUtil#selectInstances` have some problems.
**Expected behavior**
 details page instance `healthy` is false;

**Acutally behavior**
details page instance `healthy` is true;

**How to Reproduce**
1. register non-ephemeral instance. 
2. stop the client.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.0, nacos-client 2.0]
 - Module [e.g. naming]
 - SDK [e.g. java]

**Additional context**

**Comment by haoyann** [comment]
I found that it is the result of triggering the threshold protection. The threshold is zero by default, and it will be triggered when the number of instances is zero.

**Comment by KomachiSion** [comment]
the threshold is reach, so we will change healthy status before return data so that client will not route all flowing to the only healthy nodes.

For console, it should show the true status. Is the v1.x show unhealthy in detail page?

**Comment by haoyann** [comment]
v1.x version show unhealthy in detail page.

**Comment by pixystone** [comment]
I will resolve this.
