### ISSUE TITLE
JAVA_HOME not found error message should remove "We need java(x64)" since arm64 is already supported from 1.4.1

### ISSUE THREAD

**Issue by ensean** [alibaba/nacos#5073]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by ensean** [comment]
![image](https://user-images.githubusercontent.com/12255172/110732796-ce534600-825f-11eb-8dae-7d324248029c.png)

**Comment by JackSun-Developer** [comment]
看起来是你的java版本装的不对，或者java环境变量没有配置。

**Comment by ensean** [comment]
@JackSun-Developer 我想表达的是1.4.1版本已经支持在Java(arm64)环境运行了，是否可以考虑把报错提示里的”(x64)“ 移出。

**Comment by KomachiSion** [comment]
因为还有人可能会使用x86版本的 所以提示应该还是必要的。

只是提示不影响你使用

**Comment by ensean** [comment]
> 因为还有人可能会使用x86版本的 所以提示应该还是必要的。
> 
> 只是提示不影响你使用

这会给人错误信息以为nacos只支持x64 Java?

**Comment by KomachiSion** [comment]
我们无法保证32位java和系统是否能够运行出正确的结果，或许只是能够启动但运行结果是有问题的（比如涉及到一些位运算的时候）。为此我们统一使用x64的Java，并显示提示。
