### ISSUE TITLE
控制台编辑的服务元数据（非服务实例元数据），会被哪里使用到

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#5074]
nacos版本：1.4.0
在控制台编辑服务元数据，并保存后，发现服务的监听者没有被触发事件。想问下，服务的元数据在通过控制台编辑完后，是被哪里使用的。

在控制台编辑服务实例的元数据并保存后，服务的监听者的事件是被触发了的。

**Comment by JackSun-Developer** [comment]
修改元数据应该不会通知服务监听者，增删服务下面的实例才会通知服务监听者。

**Comment by wanghuigithub** [comment]
> 修改元数据应该不会通知服务监听者，增删服务下面的实例才会通知服务监听者。

嗯，所以对于在控制台修改服务的元数据这个功能的用户有点疑问。修改了的服务元数据会被哪里用到

**Comment by KomachiSion** [comment]
服务元数据是给服务端使用的，比如阈值保护的阈值。您可能需要修改的是实例元数据。

**Comment by wanghuigithub** [comment]
> 服务元数据是给服务端使用的，比如阈值保护的阈值。您可能需要修改的是实例元数据。

服务端是指Nacos节点么

**Comment by KomachiSion** [comment]
是的
