### ISSUE TITLE
新增服务后网关服务无法动态获取到该服务的路由

### ISSUE THREAD

**Issue by hanzhen1989** [alibaba/nacos#5076]
**Describe the bug**
服务可以正确注册到nacos上，也可以被别的服务正确获取到，但是网关服务无法动态添加到路由中。重启网关服务才可以添加到路由中

**Expected behavior**
不用重启网关服务，新增加的服务可以动态路由

**Desktop (please complete the following information):**
 - spring cloud:Hoxton.SR8
 - spring boot:2.3.3.RELEASE
 - nacos:2.2.2.RELEASE

**Comment by KomachiSion** [comment]
网关的问题，网关需要订阅服务才能收到推送，并且需要添加listener来处理收到的推送数据。

**Comment by hanzhen1989** [comment]
其他注册中心（如consul）没有出现该问题，是否nacos需要支持一下（原来2.1.X版本的nacos是支持的），或者是提供下自己实现的话的demo或wiki。
以下是在网关提问题时，网关给的回复：
https://github.com/spring-cloud/spring-cloud-gateway/issues/2181

**Comment by KomachiSion** [comment]
我看完网关给的回答，感觉和nacos更没有关系了， 他自己都说是根据他的route定义，那么gateway需要去进行route和service更新。而他们在新版本自己删除了这个逻辑，但是没有使用新逻辑代替。因此无法获取新发布的服务（非旧服务的新实例）。这个属于网关的用法问题吧。

**Comment by KomachiSion** [comment]
而且你贴出的源代码里不是已经查出问题了吗？它使用了缓存的servicelist 不去更新。
