### ISSUE TITLE
控制台中订阅者列表数据，多次查询的结果不一致

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#5078]
nacos版本：1.4.0

问题描述：在控制台中查询服务订阅者。多次查询的结果不一致。查询期间订阅者一直存在，没有停止。
有时可以查到订阅者，有时查不到。但是更改实例信息时，订阅者的事件是可以接到通知的。

以往的issue中有两个相同的问题，但是没有说明原因，所以又开了一个issue

**Comment by KomachiSion** [comment]
issue描述不清，你的部署结构是怎样的？ 是一直查询同一台nacos服务还是挂了域名和vip，会随机查询不同的nacos服务。

建议先测试一下是不是同一台nacos查询的结果就是变化的，并且订阅者没有一直在变更。

**Comment by wanghuigithub** [comment]
> issue描述不清，你的部署结构是怎样的？ 是一直查询同一台nacos服务还是挂了域名和vip，会随机查询不同的nacos服务。
> 
> 建议先测试一下是不是同一台nacos查询的结果就是变化的，并且订阅者没有一直在变更。

是有VIP的。 订阅者是没有变更的，期间订阅者一直可以收到事件通知。

**Comment by KomachiSion** [comment]
能否升级之后再试一下？

**Comment by wanghuigithub** [comment]
> 能否升级之后再试一下？

看了下1.4.1的代码，有问题的部分和1.4.0的代码是一致的，没有变动

**Comment by wanghuigithub** [comment]
补充一下：
![image](https://user-images.githubusercontent.com/11936135/110926561-81569900-835f-11eb-8bfe-e68ed22b062e.png)

返回结果不OK时，打印错误日志是不是比较好。

**Comment by brothelul** [comment]
I will try to sovle this issue.
