### ISSUE TITLE
Instance's "healthy" is not correct in Java SDK or OpenAPI

### ISSUE THREAD

**Issue by perryzheng2015** [alibaba/nacos#5083]
**Describe the bug**
Nacos 1.4.1 always return "**true**" for healthy although the instance was stopped. 
The healthy is correct on Nacos Control Page, but it was wrong in Java SDK or OpenAPI.
Correct on Nacos Control Page:
![image](https://user-images.githubusercontent.com/12287134/110887905-1f2d7200-8326-11eb-9b18-f1036d006756.png)
![image](https://user-images.githubusercontent.com/12287134/110887942-2bb1ca80-8326-11eb-941e-fb96b5185ce9.png)
Wrong in Java SDK or OpenAPI:
Invoke by "http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=?"
![image](https://user-images.githubusercontent.com/12287134/110888033-53a12e00-8326-11eb-91d6-6464dfa69526.png)
Invoke by "namingService.getAllInstances()"
![image](https://user-images.githubusercontent.com/12287134/110888072-67e52b00-8326-11eb-9fdb-4b48b0781d15.png)

The interest thing is that it was correct when used the interface "Search Instance Details" on OpenAPI, as below,
"http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=Email-1&ip=127.0.0.1&port=8002"
![image](https://user-images.githubusercontent.com/12287134/110888622-839d0100-8327-11eb-9b11-b05a2f10574a.png)

**Expected behavior**
The healthy should be returned as "false"

**Acutally behavior**
The healthy was returned as "true"

**How to Reproduce**
1. Register one Non-ephemeral instance
2. Make the instance service stop
3. Use Java SDK or OpenAPI to get the instance status info

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [nacos-server 1.4.1, nacos-client 1.2]

**Additional context**
This should be one issue that easily to reproduce.

**Comment by haoyann** [comment]
This is because the threshold protection is triggered, so we will change healthy status before return data.

**Comment by perryzheng2015** [comment]
Thanks for your comment.
If set the threshold protection as "0",  Nacos still return "true" for above case.
Does it mean there is no way to disable the threshold protection?
Because I just use Nacos as the instance register to check whether the server be worked in my local scenario.

Regards,

**Comment by haoyann** [comment]
You may be able to set the threshold to a negative number.this will not trigger the threshold protection, but I don’t think it’s a good way.

**Comment by perryzheng2015** [comment]
Thanks, got it.
We can close this incident at now.
