### ISSUE TITLE
Some questions about nacos.

### ISSUE THREAD

**Issue by KevinClair** [alibaba/nacos#5086]
## Issue Description
你好，请问一下我在使用nacos作为注册中心的时候，在同一个服务下的实例。在其中的一个实例配置发生变更后，我在通过订阅这个SeriviceName之后，怎么做才可以只接收到变更的那个实例的数据。目前的情况是会接收到该服务下所有的实例数据。

Hello, please tell me how to receive only the data of the changed instance after one of the instances configuration changes under the same service when I use Nacos as the registry. The current situation is that all instance data under the service will be received.

### Describe what happened (or what feature you want)
```java
public void subscribe(@RequestParam("name") String name) throws NacosException {
    namingService.subscribe(name, new EventListener() {
        @Override
        public void onEvent(Event event) {
            logger.info("Event:{}", JSON.toJSONString(event));
        }
    });
}
```

**Comment by KomachiSion** [comment]
设计上就是返回最新的全量数据。 如果有特殊需求，需要自行对比找到。

**Comment by JackSun-Developer** [comment]
>在其中的一个实例配置发生变更后，我在通过订阅这个SeriviceName之后，怎么做才可以只接收到变更的那个实例的数据

可以自己本地维护一个Set<Instance>，接收到Nacos侧的事件之后，和本地的Set<Instance>对比一下。

**Comment by KevinClair** [comment]
> 可以自己本地维护一个Set，接收到Nacos侧的事件之后，和本地的Set对比一下。

感谢回复，目前也是这么去做的，但是还是希望Nacos本身能够考虑支持一下。

**Comment by KomachiSion** [comment]
目前没有支持的计划， Nacos设计是针对服务发现的， 服务发现的结论就是发现最新的服务列表是什么，无论是否是增加还是减少，无所谓增加的是哪些，减少的是哪些。

**Comment by KevinClair** [comment]
> 目前没有支持的计划， Nacos设计是针对服务发现的， 服务发现的结论就是发现最新的服务列表是什么，无论是否是增加还是减少，无所谓增加的是哪些，减少的是哪些。

感谢回复。
