### ISSUE TITLE
windows nacos 1.4.0 + mysql5.7.31-log 无法登录

### ISSUE THREAD

**Issue by Joyonline** [alibaba/nacos#5089]
使用windows nacos 1.4.0连接数据库5.7.31成功，但始终无法登录。5秒钟访问一次的jdbcTemplate始终无法获取数据，从而userMap没有数据【[LOAD-USERS] load failed】

but
nacos 1.4.0连接5.7.32是可以的。另外linux下是可以的。
![image](https://user-images.githubusercontent.com/28465958/110919404-2e78e380-8357-11eb-998b-68b210c382a0.png)

**Comment by Joyonline** [comment]
再次验证，连接5.7.33也是正常的。故目前5.7.31不行

**Comment by KomachiSion** [comment]
那应该是mysql-jdbc和mysql在window下的问题，不是nacos的问题
