### ISSUE TITLE
Can you publish the nacos-config-1.3.2 and nacos-console-1.3.2 to maven repository

### ISSUE THREAD

**Issue by luchangjiang** [alibaba/nacos#5090]
## Issue Description
**we need nacos-config-1.3.2 and nacos-console-1.3.2 jar through maven for our server, 
but found it has stopped to publish since 0.8.0 version.
For our company rule, any jar that want put into our company maven repository, it must come from 
the https://mvnrepository.com/, otherwise it will be forbidden.**

so i want below:
**1. publish nacos-config-1.3.2.jar to mvnrepository
2. publish nacos-console-1.3.2.jar to mvnrepository
3. continue to support these 2 jar files to mvnrepository when upgrade, such as 1.4.1 version .**

I will be quite appreciate for you weather you accept or reject my apply.

**Comment by KomachiSion** [comment]
server part do not publish to mvn repository.

**Comment by luchangjiang** [comment]
thank you for your quickly reply
