### ISSUE TITLE
java.net.ConnectException: no available server, currentServerAddr : http://nacos.XXXXX:8848

### ISSUE THREAD

**Issue by huanghuaquan** [alibaba/nacos#5106]
我们的服务经常连不上注册中心，就是报标题的这个错。发现报错的前后文打印：2021-03-09 05:48:15.161 [DubboSaveMetadataReport-thread-1] INFO  com.alibaba.nacos.client.config.NacosConfigService:255 。同步元数据是否会很耗时导致注册中心响应不过来？

**Comment by JackSun-Developer** [comment]
您可以提供一下版本信息么？（以及其他信息，最好用ISSUE模板规范一下）

**Comment by jackwang-wangcb** [comment]
我也遇到这个问题了，版本1.4.1
官方能不能尽快搞定这个问题，我都快没信心用这个nacos了

**Comment by KomachiSion** [comment]
> 我也遇到这个问题了，版本1.4.1
> 官方能不能尽快搞定这个问题，我都快没信心用这个nacos了

可以提个新的issue，按照issue模版，把信息填写完整。你看这个issue现在的信息，你能知晓问题吗？

**Comment by KomachiSion** [comment]
Author no response for a long time, and no enough information. So Close issue.
