### ISSUE TITLE
Nginx discover

### ISSUE THREAD

**Issue by YeautyYE** [alibaba/nacos#511]
希望像Consul-template一样提供相似或更好的解决方案.

业务场景:公司目前是java给php提供服务，rpc用的Thrift。如果php每次请求前都curl去nacos获取服务列表，对各方面都不太好。我们希望能使用Nginx来反代.

**Comment by anjia0532** [comment]
不建议用原生nginx+lua，挺难整，建议使用openresty+lua（或者kong）,并且更新权重

如果非要用原生nginx，建议ansible+nginx

**Comment by YeautyYE** [comment]
我们目前使用Agent的方式做Nginx的自动发现
以下是解决方案:
https://github.com/YeautyYE/nacos-nginx-template

**Comment by nkorange** [comment]
> 我们目前使用Agent的方式做Nginx的自动发现
> 以下是解决方案:
> https://github.com/YeautyYE/nacos-nginx-template

Nice project!
