### ISSUE TITLE
Update to version 1.4.1 Nacos mate data inconsistent

### ISSUE THREAD

**Issue by thomastttttt** [alibaba/nacos#5111]
nacos pods have diffent mate data ,when update to 1.4.1. raftGroupMember do not include nacos-0 recorder . Is this normal ?
![image](https://user-images.githubusercontent.com/26315134/111253671-8a40b680-864e-11eb-8999-4d8b607bb76d.png)
![image](https://user-images.githubusercontent.com/26315134/111253913-f4595b80-864e-11eb-98bc-f81c9b67b137.png)
![image](https://user-images.githubusercontent.com/26315134/111253940-fd4a2d00-864e-11eb-82e7-4e8fc0c0c22e.png)

if I recreate  nacos-0 pod.Does it will sync mate data?

**Comment by KomachiSion** [comment]
duplicate with #4929
