### ISSUE TITLE
One of my service is frequently added and removed at the same time 

### ISSUE THREAD

**Issue by MumfordSons** [alibaba/nacos#5115]
naming-raft.log
![image](https://user-images.githubusercontent.com/45234194/111277082-ff25e780-8672-11eb-8b1f-d0fafc4f96d6.png)

but service log dont output error message

nacos version: 1.3.0

**Comment by MumfordSons** [comment]
other services are normal but this wrap service . so how to trace this question

**Comment by KomachiSion** [comment]
The old raft will be deprecated. And we can't reproduce your problem.

From your provided information, it might usage problem. Maybe you register ephemeral instance and persistent instance at the same time. So the distro create service but raft do not have this service, so remove it. And as a loop.

**Comment by KomachiSion** [comment]
You can try to fix it by delete the service in console manually. And make sure the service is cleaned completely. Then register it again only by ephemeral or persistent.

**Comment by MumfordSons** [comment]
> You can try to fix it by delete the service in console manually. And make sure the service is cleaned completely. Then register it again only by ephemeral or persistent.

deleting that service on web console i had tried but that service is also added and removed frequently

**Comment by MumfordSons** [comment]
> You can try to fix it by delete the service in console manually. And make sure the service is cleaned completely. Then register it again only by ephemeral or persistent.

i update version to 1.4.0 and the problem is solved

**Comment by KomachiSion** [comment]
after 1.4.0 old raft will be deprecated and use jraft.
