### ISSUE TITLE
Wildcards are not supported for Dubbo service registration*

### ISSUE THREAD

**Issue by dwhgygzt** [alibaba/nacos#5119]
**Describe the bug**
We plan to use Dubbo's packet aggregation service, 
Using Nacos as the registration center,

**but ?_?**  Wildcards are not supported for Dubbo service registration *

**Expected behavior**
Start the normal with springboot

**Acutally behavior**
dom name can only have these characters: 0-9a-zA-Z-._

**How to Reproduce**
1. add  YML file configuration

```ymal
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://xxxxxxx:8848
    check: false
  protocol:
    name: dubbo
    port: 20880
  consumer:
    timeout: 30000
    retries: 0
    check: false
```

2.  Dubbo consumers
```java
    @DubboReference(version = "1.0", group = "*", merger = "true")
    protected DataPublishRpcService dataPublishRpcService;

```

3. start springboot 

**Desktop :**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-api 1.4.1, nacos-client 1.4.1, nacos-common 1.4.1]
 - Module [e.g. api/naming/config]
 - SDK [e.g. original, dubbo-registry-nacos, dubbo2.7.8]

**Comment by KomachiSion** [comment]
Service name only support `[0-9a-zA-Z@\.:_-]`
The reason nacos need write some cache data and persistent data to os filesystem. But some os can't use some of special word as file name. So the 1.X version limit the service name.

It might be solved in 2.X

**Comment by dwhgygzt** [comment]
ok  thanks
