### ISSUE TITLE
可否添加不同配置文件的比对功能？

### ISSUE THREAD

**Issue by missfmaster** [alibaba/nacos#5120]
目前使用nacos的namespace区分测试环境、生产环境；
但是有时测试环境新增的配置，发布到生产环境时，会遗漏几个，导致生产环境莫名报错；
所以，能不能通过工具避免这种问题？
比如，添加不同namespace下的配置文件列表比较，可以明显查看到各namespace下多哪个配置、少哪个配置？
然后再添加不同namespace下相同名称配置文件的内容比较，可以把差异明显比较出来，类似BeyondCompare？

**Comment by haoyann** [comment]
#4452
