### ISSUE TITLE
（ErrCode : 500） in 2.0.0-BETA with standalone mode.

### ISSUE THREAD

**Issue by Chivenh** [alibaba/nacos#5126]
### When I update the weight for my service instance,the error happend: 
>  errCode: 500, errMsg: do metadata operation failed; com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_instance_metadata] did not find the Leader node

![image](https://user-images.githubusercontent.com/28721089/111411687-f508f500-8715-11eb-966e-e26a7ea65743.png)

**Comment by KomachiSion** [comment]
Your raft status is error. Please remove nacos/data and restart if your local ip changed.

**Comment by lpaz010** [comment]
it works for me.

> Your raft status is error. Please remove nacos/data and restart if your local ip changed.
