### ISSUE TITLE
nacos 1.4.1 configservice.getConfig cannot get  configs  success, tips config data not exist 

### ISSUE THREAD

**Issue by hongye1114** [alibaba/nacos#5127]
![image](https://user-images.githubusercontent.com/23633287/111430640-9784a080-8735-11eb-9e7d-17b0ac2034bb.png)

![image](https://user-images.githubusercontent.com/23633287/111430675-a8351680-8735-11eb-88d6-811729ef15e2.png)

As shown in the figure, the console can check the configuration, and neither configService nor http access can get the configuration.

如图,控制台可以查到配置,configService 和http 访问都获取不到配置

**Comment by KomachiSion** [comment]
可能是命名空间问题吧

**Comment by hongye1114** [comment]
> 可能是命名空间问题吧

用的是默认的

**Comment by hongye1114** [comment]
> 可能是命名空间问题吧

同样的情况 切换成nacos-server1.4.0 没有问题

**Comment by haoyann** [comment]
@hongye1114 我本地用develop分支在控制台创建了一个配置，然后接口请求是可以获取到配置的，请问怎么复现呢?

**Comment by hongye1114** [comment]
> @hongye1114 我本地用develop分支在控制台创建了一个配置，然后接口请求是可以获取到配置的，请问怎么复现呢?

@haoyann 辛苦
我第一次下载的1.4.1 的版本  操作流程就是上面两张图  无法通过api获取数据
于是下载1.4.0版本重试,获取数据成功
今天切换成1.4.1版本  同样的流程,获取数据成功,复现失败
找了台新机器  重新安装1.4.1,依然复现失败
麻烦先关闭issue
