### ISSUE TITLE
tenant有一个明显的Bug，麻烦看一下

### ISSUE THREAD

**Issue by lasting0001** [alibaba/nacos#5133]
版本：1.4.1

有个明显的Bug，新增了命名空间后：
1、http获取配置的接口里，tenant参数使用的是数据表tenant_info.tenant_id字段
2、而控制台Console新增配置的操作后，数据表config_info.tenant_id存储的是tenant_info.tenant_name字段
导致：http接口发布的配置，在控制台里面看不到；而控制台新增的配置，在http接口也获取不到。

综上：
分析了源码，控制台设置config_info.tenant_id字段，使用的是tenant_info.tenant_name的值，http发布接口中tenant_id参数，使用的是tenant_info.tenant_name的值。

这个问题必须改掉，否则完全没法正常使用nacos。只有限制新增命名空间，禁止http客户端发布配置，才能正常使用

**Comment by sanxun0325** [comment]
@lasting0001 使用接口查询配置和发布配置时 tenant参数使用tenantId，没有问题。在控制台发布的时候tenant 也是利用的tenantId.

**Comment by KomachiSion** [comment]
我在console.nacos.io试了一下 没有出现你所说的问题。

http://console.nacos.io/nacos/#/configurationManagement?dataId=&group=&appName=&namespace=test-issue-5133-id&pageSize=&pageNo=&namespaceShowName=test-issue-5133-name

应该还是使用方法错误导致的吧

**Comment by KomachiSion** [comment]
Any process? we can't reproduce this problem in 1.4.1. Can you provide detail steps and demo codes?

If no more response, we will close issue.

**Comment by JackSun-Developer** [comment]
> 2、而控制台Console新增配置的操作后，数据表config_info.tenant_id存储的是tenant_info.tenant_name字段

这个描述是不对的，参考ExternalStoragePersistServiceImpl.java的插入配置代码

例如
```
    @Override
    public void insertTenantInfoAtomic(String kp, String tenantId, String tenantName, String tenantDesc,
            String createResoure, final long time) {
        try {
            jt.update(
                    "INSERT INTO tenant_info(kp,tenant_id,tenant_name,tenant_desc,create_source,gmt_create,gmt_modified) VALUES(?,?,?,?,?,?,?)",
                    kp, tenantId, tenantName, tenantDesc, createResoure, time, time);
        } catch (DataAccessException e) {
            LogUtil.FATAL_LOG.error("[db-error] " + e.toString(), e);
            throw e;
        }
    }
```

插入的时候也是根据tenant_id作为主键的

**Comment by JackSun-Developer** [comment]
1、
> 分析了源码，控制台设置config_info.tenant_id字段，使用的是tenant_info.tenant_name的值

这句话是不成立的，nacos在对配置进行增删改查的时候，源码里全都是以tenant_id作为主键的。可以看一下ExternalStoragePersistServiceImpl.java的所有sql语句。

2、
> 只有限制新增命名空间，禁止http客户端发布配置，才能正常使用

这句话是说新增命名空间需要受限，这个我正在另一个ISSUE修复，目标是剥离出来一个单独的模块来对于新增命名空间进行限制。

**Comment by horizonzy** [comment]
控制台发布配置时,config_info的tenant_id用的时teant_info.tenant_id字段。

目前在对配置发布以及服务注册时，并没有对tenant对应的tenant_id是否存在做校验是否存在。需要用户在使用时注意，让发布端和订阅端使用相同的tenant_id.

**Comment by KomachiSion** [comment]
From the community response, it seems some mistake for usage.
