### ISSUE TITLE
关于springcloudnacos0.7版本注册的时候namespace，secure配置无效

### ISSUE THREAD

**Issue by 18980808191** [alibaba/nacos#514]
在springcloud项目中，配置
spring.cloud.nacos.discovery.namespace=
spring.cloud.nacos.discovery.access-key=
spring.cloud.nacos.discovery.secure=
三个均无效，需要控制台可以配置服务的鉴权码。

**Comment by nkorange** [comment]
namespace功能正在开发，会在0.8.0发布，请参考 #498
