### ISSUE TITLE
Add unit tests to package com.alibaba.nacos.naming.consistency.ehpemeral.distro.v2 in nacos 2.0

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5143]
This ISSUE is a sub-issue of #4982
The unit test coverage of package 'com.alibaba.nacos.naming.consistency.ehpemeral.distro.v2' is too low, could you provide more unit tests?

**Comment by JackSun-Developer** [comment]
@i will solve it@

**Comment by shalk** [comment]
@ i will solve it@
