### ISSUE TITLE
 node.js 调用gRpc服务

### ISSUE THREAD

**Issue by magdsnail** [alibaba/nacos#5145]
服务通过nacos-sdk-nodejs client 已经注册到注册中心，怎么调用其他服务提供的 gRpc 接口？

**Comment by KomachiSion** [comment]
调用是你自己进行的，注册到注册中心只是能够让你的客户端感知到要调用的接口有那些ip。 实际去调用还是要自己进行。

**Comment by magdsnail** [comment]
> 调用是你自己进行的，注册到注册中心只是能够让你的客户端感知到要调用的接口有那些ip。 实际去调用还是要自己进行。

那如果我们调用的服务有多个，怎么动态的匹配，是不是要自己实现负载均衡？

**Comment by KomachiSion** [comment]
服务发现提供的能力是记录你注册的服务，并帮助你发现服务下的实例列表。至于获取到实例列表后调用哪一个，按照什么策略调用，应该属于应用框架或RPC框架的问题。

标准Grpc我理解只提供了RPC的能力，没有注册，订阅，调用和负载均衡等能力，这部分需要用户或者应用框架来帮忙。

由于我对nodejs不是很了解，因此我不清楚是否Grpc能够自主注册和调用，或者有没有类似的框架进行。

**Comment by magdsnail** [comment]
> 服务发现提供的能力是记录你注册的服务，并帮助你发现服务下的实例列表。至于获取到实例列表后调用哪一个，按照什么策略调用，应该属于应用框架或RPC框架的问题。
> 
> 标准Grpc我理解只提供了RPC的能力，没有注册，订阅，调用和负载均衡等能力，这部分需要用户或者应用框架来帮忙。
> 
> 由于我对nodejs不是很了解，因此我不清楚是否Grpc能够自主注册和调用，或者有没有类似的框架进行。
好的 我知道了 谢谢您

**Comment by magdsnail** [comment]
> > 服务发现提供的能力是记录你注册的服务，并帮助你发现服务下的实例列表。至于获取到实例列表后调用哪一个，按照什么策略调用，应该属于应用框架或RPC框架的问题。
> > 标准Grpc我理解只提供了RPC的能力，没有注册，订阅，调用和负载均衡等能力，这部分需要用户或者应用框架来帮忙。
> > 由于我对nodejs不是很了解，因此我不清楚是否Grpc能够自主注册和调用，或者有没有类似的框架进行。
> > 好的 我知道了 谢谢您



> 服务发现提供的能力是记录你注册的服务，并帮助你发现服务下的实例列表。至于获取到实例列表后调用哪一个，按照什么策略调用，应该属于应用框架或RPC框架的问题。
> 
> 标准Grpc我理解只提供了RPC的能力，没有注册，订阅，调用和负载均衡等能力，这部分需要用户或者应用框架来帮忙。
> 
> 由于我对nodejs不是很了解，因此我不清楚是否Grpc能够自主注册和调用，或者有没有类似的框架进行。

好的 我知道了谢谢您
