### ISSUE TITLE
Why my nacos configuration can only be refreshed once?

### ISSUE THREAD

**Issue by xuehairui** [alibaba/nacos#5146]
## Issue Description
Why my nacos configuration can only be refreshed once in 1.4.1？
Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
when i use nacos config ，the first time config change can be refresh ,but from the second time nacos config refresh failure
my nacos version is 1.4.1
### Describe what you expected to happen
16:21:45.383|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |o.s.boot.SpringApplication|The following profiles are active: dev
16:21:45.394|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |o.s.boot.SpringApplication|Started application in 1.104 seconds (JVM running for 65.699)
16:21:45.395|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.c.config.http.ServerHttpAgent|com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown begin
16:21:45.396|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|WARN |com.alibaba.nacos.client.naming|[ConfigHttpClientManager] Start destroying NacosRestTemplate
16:21:45.396|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|WARN |com.alibaba.nacos.client.naming|[ConfigHttpClientManager] Destruction of the end
16:21:45.396|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.c.identify.CredentialWatcher|[null] CredentialWatcher is stopped
16:21:45.396|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.c.identify.CredentialService|[null] CredentialService is freed
16:21:45.396|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.c.config.http.ServerHttpAgent|com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown stop
16:21:45.396|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.c.config.impl.ClientWorker|com.alibaba.nacos.client.config.impl.ClientWorker do shutdown begin
16:21:47.278|[com.alibaba.nacos.client.naming.updater]|INFO |c.a.n.c.identify.CredentialWatcher|null No credential found
16:21:48.430|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.c.config.impl.ClientWorker|com.alibaba.nacos.client.config.impl.ClientWorker do shutdown stop
Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.
16:21:48.691|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |o.s.c.e.event.RefreshEventListener|Refresh keys changed: [streamax.smscode.isdebug]
16:21:48.692|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.client.config.impl.CacheData|[fixed-192.168.180.76_8848-namespace-local] [notify-ok] dataId=saas-auth, group=enterprise, md5=ed7f475fa3608d6a9e42193073b64ac0, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@63a67e9e 
16:21:48.692|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|INFO |c.a.n.client.config.impl.CacheData|[fixed-192.168.180.76_8848-namespace-local] [notify-listener] time cost=4405ms in ClientWorker, dataId=saas-auth, group=enterprise, md5=ed7f475fa3608d6a9e42193073b64ac0, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@63a67e9e 
16:21:48.694|[com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.180.76_8848-namespace-local]|ERROR|c.a.n.c.config.impl.ClientWorker|longPolling error : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e769fa8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@37eb0cf0[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:21:52.172|[MessageBroker-1]|INFO |o.s.w.s.c.WebSocketMessageBrokerStats|WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 4, active threads = 1, queued tasks = 1, completed tasks = 2]

### How to reproduce it (as minimally and precisely as possible)

1. when application is running,  first i set streamax.smscode.isdebug=true the change will be refresh to my application 
2. then i change the config isdebug=false, the console will print the error like the description above
3.

**Comment by KomachiSion** [comment]
duplicate with alibaba/spring-cloud-alibaba#1926
