### ISSUE TITLE
新版本的nacos，新服务上线时，无法自动被网关服务路由到了

### ISSUE THREAD

**Issue by hanzhen1989** [alibaba/nacos#5147]
关联上一个issue：#5076
其他注册中心（如consul）没有出现该问题，是否nacos需要支持一下（原来2.1.X版本的nacos是支持的），或者是提供下自己实现的话的demo或wiki。
以下是在网关提问题时，网关给的回复：
https://github.com/spring-cloud/spring-cloud-gateway/issues/2181

_Originally posted by @hanzhen1989 in https://github.com/alibaba/nacos/issues/5076#issuecomment-802575408_

**Comment by KomachiSion** [comment]
我觉得你给出的源代码已经给出问题了。他们缓存了servicelist，但是不去更新。那新发布的服务肯定是获取不到的啊。

**Comment by KomachiSion** [comment]
consul肯定是gateway通过其他手段获取了并更新了服务列表。

**Comment by hanzhen1989** [comment]
nacos能否也做一些处理（或者是给一些建议性的处理或demo），来帮助spring cloud gateway的使用者来解决这个问题啊？ 毕竟我们水平有限，代码的优雅性和健壮性可能会有所欠缺。

**Comment by ctlove0523** [comment]
Spring Cloud Gateway更新路由信息是依赖接收到ApplicationEvent事件，nacos提供的`spring-cloud-starter-alibaba-nacos-discovery`会周期性的发布HeartbeatEvent事件，Spring Cloud Gateway接收到该事件首先要调用HeartbeatMonitor的update方法更新heartbeat状态，如果更新成功则发布RefreshRoutesEvent事件更新路由信息。所以可以确认一下下面这个值的配置以及多长时间内Spring Cloud Gateway无法找到新注册的服务：
~~~
	/**
	 * watch delay,duration to pull new service from nacos server.
	 */
	private long watchDelay = 30000;
~~~

**Comment by hanzhen1989** [comment]
> Spring Cloud Gateway更新路由信息是依赖接收到ApplicationEvent事件，nacos提供的`spring-cloud-starter-alibaba-nacos-discovery`会周期性的发布HeartbeatEvent事件，Spring Cloud Gateway接收到该事件首先要调用HeartbeatMonitor的update方法更新heartbeat状态，如果更新成功则发布RefreshRoutesEvent事件更新路由信息。所以可以确认一下下面这个值的配置以及多长时间内Spring Cloud Gateway无法找到新注册的服务：
> 
> ```
> 	/**
> 	 * watch delay,duration to pull new service from nacos server.
> 	 */
> 	private long watchDelay = 30000;
> ```

谢谢回复。我使用的是默认配置，spring cloud gateway多长时间都找不到新注册的服务。 我之前简单断点调试了下，貌似是nacos发布的心跳事件没有能触发网关的刷新路由的事件（新加的服务，所有服务都能获取到，网关也能获取到，但是路由信息不更新），不知道是我的nacos哪里出了问题还是什么原因。 你的不需要做任何处理就可以正常更新路由吗？ 你是用的 springcloud gateway 和 nacos的版本是什么啊？

**Comment by KomachiSion** [comment]
这里其实有3个部分
Spring cloud gateway -- Spring cloud alibaba -- nacos client
如果gateway需要通过SCA注入或主动更新服务列表的化，可能需要给SCA提issue，让他们去更新新版本的gateway。
如果gateway是自己维护缓存，那么需要看gateway是如何以及什么时候去更新的。Consul既然可以使用那么一定存在更新服务列表缓存的操作，只是不清楚gateway实现的位置；如果是gateway需要某种能力而client没有提供，可以讨论是否增加这个能力。

**Comment by ctlove0523** [comment]
> > Spring Cloud Gateway更新路由信息是依赖接收到ApplicationEvent事件，nacos提供的`spring-cloud-starter-alibaba-nacos-discovery`会周期性的发布HeartbeatEvent事件，Spring Cloud Gateway接收到该事件首先要调用HeartbeatMonitor的update方法更新heartbeat状态，如果更新成功则发布RefreshRoutesEvent事件更新路由信息。所以可以确认一下下面这个值的配置以及多长时间内Spring Cloud Gateway无法找到新注册的服务：
> > ```
> > 	/**
> > 	 * watch delay,duration to pull new service from nacos server.
> > 	 */
> > 	private long watchDelay = 30000;
> > ```
> 
> 谢谢回复。我使用的是默认配置，spring cloud gateway多长时间都找不到新注册的服务。 我之前简单断点调试了下，貌似是nacos发布的心跳事件没有能触发网关的刷新路由的事件（新加的服务，所有服务都能获取到，网关也能获取到，但是路由信息不更新），不知道是我的nacos哪里出了问题还是什么原因。 你的不需要做任何处理就可以正常更新路由吗？ 你是用的 springcloud gateway 和 nacos的版本是什么啊？

版本信息：
Nacos Server：2.0.0
Spring Cloud Gateway：2.2.5.RELEASE
spring-cloud-starter-alibaba-nacos-discovery：2.2.5.RELEASE
spring cloud：2.2.5.RELEASE

使用上面的版本我测试正常，新服务上线可以被正常发现。你可以提供复现问题的样例代码吗？我测试的代码可以从[这里](https://github.com/ctlove0523/spring-samples)获取，子项目分别为：spring-cloud-nacos和spring-cloud-gateway-nacos

**Comment by hanzhen1989** [comment]
> > > Spring Cloud Gateway更新路由信息是依赖接收到ApplicationEvent事件，nacos提供的`spring-cloud-starter-alibaba-nacos-discovery`会周期性的发布HeartbeatEvent事件，Spring Cloud Gateway接收到该事件首先要调用HeartbeatMonitor的update方法更新heartbeat状态，如果更新成功则发布RefreshRoutesEvent事件更新路由信息。所以可以确认一下下面这个值的配置以及多长时间内Spring Cloud Gateway无法找到新注册的服务：
> > > ```
> > > 	/**
> > > 	 * watch delay,duration to pull new service from nacos server.
> > > 	 */
> > > 	private long watchDelay = 30000;
> > > ```
> > 
> > 
> > 谢谢回复。我使用的是默认配置，spring cloud gateway多长时间都找不到新注册的服务。 我之前简单断点调试了下，貌似是nacos发布的心跳事件没有能触发网关的刷新路由的事件（新加的服务，所有服务都能获取到，网关也能获取到，但是路由信息不更新），不知道是我的nacos哪里出了问题还是什么原因。 你的不需要做任何处理就可以正常更新路由吗？ 你是用的 springcloud gateway 和 nacos的版本是什么啊？
> 
> 版本信息：
> Nacos Server：2.0.0
> Spring Cloud Gateway：2.2.5.RELEASE
> spring-cloud-starter-alibaba-nacos-discovery：2.2.5.RELEASE
> spring cloud：2.2.5.RELEASE
> 
> 使用上面的版本我测试正常，新服务上线可以被正常发现。你可以提供复现问题的样例代码吗？我测试的代码可以从[这里](https://github.com/ctlove0523/spring-samples)获取，子项目分别为：spring-cloud-nacos和spring-cloud-gateway-nacos

万分感谢，我把nacos-discovery的版本改为2.2.5.RELEASE之后（我原来为2.2.2.RELEASE），网关路由正常了，可以自动上下线服务了。应该是2.2.2.RELEASE版本的nacos-discovery有些问题。
