### ISSUE TITLE
读官网博客产生的问题

### ISSUE THREAD

**Issue by wanghuigithub** [alibaba/nacos#5162]
读了官网的这篇博客：https://nacos.io/zh-cn/blog/alibaba-configserver.html

感觉文中提到的Eureka1.0架构存在的几个问题，在Nacos1.4.*版本中依然存在

1、每一台Server都需要存储全量的服务数据，Server的内存明显会成为瓶颈。
2、当订阅者却来越多的时候，需要扩容Eureka集群来提高读的能力，但是扩容的同时会导致每台server需要承担更多的写请求，扩容的效果不明显。
3、组成Eureka集群的所有server都需要采用相同的物理配置，并且只能通过不断的提高配置来容纳更多的服务数据

请问nacos有针对上述问题的一些最佳实践么

**Comment by KomachiSion** [comment]
Nacos 1.X架构和Eureka其实有一定的相似性，Consul也是一样，由于大多数场景不实用持久化存储，因此信息需要存储在集群内存中，这是不可避免的。 

而在实际使用过程中，我们发现实际内存成为瓶颈的情况并不太多，而大量瓶颈出现在网络协议请求上，也即HTTP来保持实例活性及客户端服务端数据一致性需要消耗大量资源（心跳以及读请求）。 因此2.0我们修改了客户端和服务端之间的通信方式，换成grpc来提升性能。
