### ISSUE TITLE
Too much Integration Tests in package com.alibaba.nacos.test.naming cannot pass, could you fix them?

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5171]
## Issue Description

Too much Integration Tests in package  **com.alibaba.nacos.test.naming** cannot pass, could you fix them?

### Describe what happened (or what feature you want)

More than a half of the Intergrate Tests in package **com.alibaba.nacos.test.naming** cannot pass.

### Describe what you expected to happen

Let 100% of them pass.

![image](https://user-images.githubusercontent.com/58767027/112293199-d59d3980-8ccc-11eb-9198-f4efd8220089.png)

**Comment by JackSun-Developer** [comment]
@ i will solve it@
