### ISSUE TITLE
nacos springcloud接入方式下，@NacosConfigListener注解失效

### ISSUE THREAD

**Issue by xiaofeiahaha** [alibaba/nacos#5173]
**Environment**
nacos-client : 1.2.0
nacos-spring-cloud-starter : 2.2.3.RELEASE
spring-boot: 2.2.2.RELEASE

**Describe the question**
使用nacos-spring-cloud-starter接入nacos作为springcloud的配置中心，使用file-extension的配置方式可以读取到yaml的值。
但是想继续使用@NacosConfigListener，指定dataId获取配置文件，发现注解未生效。
目前我只能使用configService手动获取配置。

请问是我的使用姿势不正确还是别的什么原因？谢谢

**Comment by KomachiSion** [comment]
请到Spring-cloud-alibaba社区进行提问。
