### ISSUE TITLE
springboot + nacos 怎么禁用nacos及禁止本地缓存

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#5174]
有开关可以关闭nacos + springboot吗，比如在nacos服务不可用时，直接在application层关闭nacos功能，及本地cache功能，谢谢

**Comment by KomachiSion** [comment]
目前没有类似的功能。

为什么需要禁用缓存，如果nacos服务不可用，应用不是应该使用缓存来运行吗？ 您是希望有failover？ failover的话 nacos是可以提供的。

**Comment by FengJinghHua** [comment]
@KomachiSion 我们在集成pg + nacos，现在nacos只支持nacos+mysql，所以想在pg环境上先禁用nacos，读取原生的application.properties配置文件，springboot + nacos有类似 spring.cloud.nacos.config.enabled 这种配置来禁用nacos吗

**Comment by KomachiSion** [comment]
可以吧 具体得看一下spring cloud的文档， 我理解这个enabled=false就不会使用nacos去读取config了，但是在改为true重建之前，都是无法读取的。

**Comment by FengJinghHua** [comment]
但是这个不是spring cloud的配置吗，springboot呢

**Comment by KomachiSion** [comment]
spring boot可能没有这个配置，如果不需要动态刷新应该直接不引入或者不标记注解就可以了吧

**Comment by JackSun-Developer** [comment]
>有开关可以关闭nacos + springboot吗

我理解你们的目的是不使用nacos提供的配置获取及动态刷新功能，可以不标注@NacosValue
