### ISSUE TITLE
war打包部署到weblogic，停止某个应用后，后台仍然有线程长轮询。

### ISSUE THREAD

**Issue by whoischildvideo** [alibaba/nacos#5181]
**Describe the bug**
在使用war部署到weblogic后，在weblogic后台停止应用并删除后，在nacos后台中，停掉nacos中注册的同分组的其他服务，发现这个已经从weblogic删除的应用日志中，仍然接收着nacos推送过来的服务上线下线通知。

**Expected behavior**
如何确保weblog中删除某个应用后，该应用彻底关闭，不再有向nacos长轮询的线程？
 
nacos client 1.3.1  
server：1.3

**Comment by KomachiSion** [comment]
看下关闭应用时是否有调用的shutDown方法？

weblogic我并不清楚他的删除和彻底关闭是否是真的彻底关闭，如果还有长轮询线程，那就是没彻底关闭，应该和weblogic的关闭逻辑有关。

**Comment by whoischildvideo** [comment]
> 看下关闭应用时是否有调用的shutDown方法？
> 
> weblogic我并不清楚他的删除和彻底关闭是否是真的彻底关闭，如果还有长轮询线程，那就是没彻底关闭，应该和weblogic的关闭逻辑有关。

目前我是放到了springboot启动类退出的时候处理：
```java
@Autowired
    private NacosConfigManager nacosConfigManager;


    @PreDestroy
    public void onExit(){
        try {
            nacosConfigManager.getConfigService().shutDown();
            NacosRegistryServiceImpl.getNamingInstance().shutDown();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
但是这样处理在非weblogic的web容器中会报错。

**Comment by KomachiSion** [comment]
长轮询线程是一个线程池， 除非显示调用shutdown停止或依附的JVM被释放，否则会一直持有。

我不清楚weblogic的保持逻辑，可能需要您在合适的地方显示去停止。

**Comment by mvpbang** [comment]
> **Describe the bug** 在使用war部署到weblogic后，在weblogic后台停止应用并删除后，在nacos后台中，停掉nacos中注册的同分组的其他服务，发现这个已经从weblogic删除的应用日志中，仍然接收着nacos推送过来的服务上线下线通知。
> 
> **Expected behavior** 如何确保weblog中删除某个应用后，该应用彻底关闭，不再有向nacos长轮询的线程？
> 
> nacos client 1.3.1 server：1.3

hi,可以分享下war的版本的吗？
