### ISSUE TITLE
历史版本中没有操作人

### ISSUE THREAD

**Issue by mawujun1234** [alibaba/nacos#5187]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
当我修改之后，在历史版本中查看的时候，发现“操作人”这列没有记录是谁修改的！

图片内容如下：
![image](https://user-images.githubusercontent.com/3039351/112405349-12107a00-8d4d-11eb-859f-8398e274dd26.png)

### How to reproduce it (as minimally and precisely as possible)

1. 新建一个dataId=test的配置
2. 修改配置
3. 在历史记录中查看，发现操作人没有

### Tell us your environment
版本是1.4.1，使用的是官网的docker集群

**Comment by KomachiSion** [comment]
未开启鉴权的情况下不会记录操作人

**Comment by mawujun1234** [comment]
收到，谢谢
