### ISSUE TITLE
nacos 2.0.0 registration information is out of sync 

### ISSUE THREAD

**Issue by jzdayz** [alibaba/nacos#5189]
**Describe the bug**
![image](https://user-images.githubusercontent.com/35563513/112424296-21082400-8d6f-11eb-8ce8-bb2857c0734f.png)
![image](https://user-images.githubusercontent.com/35563513/112424319-28c7c880-8d6f-11eb-9265-25bdf6fb1688.png)
![image](https://user-images.githubusercontent.com/35563513/112424331-2f564000-8d6f-11eb-8fe0-f603d5a29e8b.png)

cluster.conf
```text
10.1.XX.XX:8841
10.1.XX.XX:8851
10.1.XX.XX:8861
```

**Expected behavior**
cd-project service is sync in nacos cluster

**Acutally behavior**
not work

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: centos7
 - Version nacos-server:2.0.0   nacos-client: 1.4.1
 - Module naming  
 - SDK spring-cloud-alibaba-nacos

**Additional context**

**Comment by jzdayz** [comment]
What's log should i see?

**Comment by KomachiSion** [comment]
see naming-server in 8861 and 8851 node

And check all naming-distro + protocol-distro, see whether the target client be synced to other nodes.
