### ISSUE TITLE
login error but no logging

### ISSUE THREAD

**Issue by AcrazyDog** [alibaba/nacos#5190]
#### class in com.alibaba.nacos.client.security.SecurityProxy :
```
    public boolean login(List<String> servers) {

        try {
            if ((System.currentTimeMillis() - lastRefreshTime) < TimeUnit.SECONDS.toMillis(tokenTtl - tokenRefreshWindow)) {
                return true;
            }

            for (String server : servers) {
                if (login(server)) {
                    lastRefreshTime = System.currentTimeMillis();
                    return true;
                }
            }
        } catch (Throwable ignore) {
        }

        return false;
    }
```

**Comment by ShawnSiao** [comment]
@i will solve it@

**Comment by haoyann** [comment]
login methed catch `Exception`, if it will throw `Throwable`, I think replace `Exception` here a with `Throwable` better.
https://github.com/alibaba/nacos/blob/f22b93cac3d7c1afcf2194508e70751383700688/client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java#L154

**Comment by KomachiSion** [comment]
Welcome to enhance it like https://github.com/alibaba/nacos/pull/5235 without code style problem.

**Comment by brothelul** [comment]
I will try to solve it.

**Comment by brothelul** [comment]
I reviewed the login code, I think we catch the Throwable is unnecessary. the main logic in login 
[https://github.com/alibaba/nacos/blob/f22b93cac3d7c1afcf2194508e70751383700688/client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java#L129](https://github.com/alibaba/nacos/blob/f22b93cac3d7c1afcf2194508e70751383700688/client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java#L129)
[https://github.com/alibaba/nacos/blob/f22b93cac3d7c1afcf2194508e70751383700688/client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java#L154](https://github.com/alibaba/nacos/blob/f22b93cac3d7c1afcf2194508e70751383700688/client/src/main/java/com/alibaba/nacos/client/security/SecurityProxy.java#L154) method has catch the Exception and return false. If an error was maked, I think the follow codes after the login method shouldn't be ran. What's your opinion? @KomachiSion @haoyann

**Comment by KomachiSion** [comment]
If we remove this catch, whether will stop the schedule of scheduleWithFixedDelay?

**Comment by brothelul** [comment]
Yes, if there is an Exception. I think we should catch it, and keep the schedule task can re-run it. but if an Error occured, I am not sure need we stop it and make user to unknow the Error? usually, An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. If we need catch the Error as well, I will change my codes  to re-catch the throwable and print the error detail.

**Comment by KomachiSion** [comment]
There must be retry for login, I think. It is a protection for client.

**Comment by brothelul** [comment]
OK, thank you. I will change this later.
