### ISSUE TITLE
2.0.0健康检查方式

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#5191]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by woshishitou** [comment]
您好，2.0.0的健康检查方式相比于之前的，有什么改动吗？
Hello, is there any change in the health check method of 2.0.0 compared with the previous one

**Comment by woshishitou** [comment]
通过了解，我知道了以前的健康检查方式。对于临时实例是心跳，对于持久化实例可以使用http接口。
I learned that the previous health check was a heartbeat for temporary instances, and the HTTP interface was available for persistent instances

**Comment by KomachiSion** [comment]
2.0.0的非持久化实例使用TCP连接时间+连接keepalive代替原来的实例心跳。持久化实例保持和原来一样的健康检查方式

**Comment by woshishitou** [comment]
> 2.0.0的非持久化实例使用TCP连接时间+连接keepalive代替原来的实例心跳。持久化实例保持和原来一样的健康检查方式

了解了，多谢回复
