### ISSUE TITLE
找不到nacos2.0 完整的部署文档，只好在这里提一下，希望得到回复

### ISSUE THREAD

**Issue by jackwang-wangcb** [alibaba/nacos#5195]
在官方文档https://nacos.io/zh-cn/docs/2.0.0-compatibility.html中找到这么一句话
Nacos2.0版本相比1.X新增了gRPC的通信方式，因此需要增加2个端口。新增端口是在配置的主端口(server.port)基础上，进行一定偏移量自动生成。

端口 | 与主端口的偏移量 | 描述
9848 | 1000 | 客户端gRPC请求服务端端口，用于客户端向服务端发起连接和请求
9849 | 1001 | 服务端gRPC请求服务端端口，用于服务间同步等

如果三个nacos组成集群，并用nginx做代理，是不是需要 nginx需要http 代理8848 端口进行管理登录，tcp代理9848进行客户端与服务器的代理，而9849内部端口只需在内网暴露出来即可，还是说在cluster.conf里进行配置，例如这样：
192.168.16.101:9849
192.168.16.102:9849
192.168.16.103:9849

如果服务端与客户端用 gRPC进行通信，客户端配置是否有变化呢，配置的参数有哪些，哪里能查到呢？

真希望官方的文档 详细点，猜来猜去的真的好费劲啊

**Comment by KomachiSion** [comment]
`客户端拥有相同的计算逻辑，用户如同1.X的使用方式，配置主端口(默认8848)，通过相同的偏移量，计算对应gRPC端口(默认9848)。`

就在你贴的下面一句不就有写吗？
