### ISSUE TITLE
/nacos/v1/auth/users/login?encoding=UTF-8&username=nacos HTTP/1.1" 404

### ISSUE THREAD

**Issue by xrwang8** [alibaba/nacos#5197]
![image](https://user-images.githubusercontent.com/68765051/112569484-32a90480-8e1f-11eb-998a-162bc267e01a.png)

**Comment by JackSun-Developer** [comment]
只提供了username，没提供password

**Comment by KomachiSion** [comment]
> 只提供了username，没提供password

password应该在body里 显示不出来

@xrwang8 有其他的信息吗？ 麻烦按照issue模版填写一下，否则信息太少 无法判断。

**Comment by xrwang8** [comment]
问题我已找到了，是seata 的nacos缺少端口号2021年3月26日 下午1:45，杨翊 SionYang ***@***.***> 写道：
只提供了username，没提供password
password应该在body里 ***@***.*** 有其他的信息吗？ 麻烦按照issue模版填写一下，否则信息太少 无法判断。—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by victory0519** [comment]
为什么我在接口文档里面没有找到这个接口
