### ISSUE TITLE
nacos api 注销服务不生效？

### ISSUE THREAD

**Issue by xiebin2015** [alibaba/nacos#5198]
A服务注册到nacos，在A服务里面写了个接口，调用namingService的deregisterInstance方法进行实例注销
调用代码如图：
![image](https://user-images.githubusercontent.com/14512197/112572629-7c94e900-8e25-11eb-83c1-bb8e77a1c613.png)

但是无论怎么，服务依然还在，这是为什么？

**Comment by JackSun-Developer** [comment]
可能性1:命名空间-group-服务名 这三个都核对一下，是不是写错了和服务端不一致。
可能性2:有其他的实例正在不停的发送心跳，又把服务注册回去了。

**Comment by xiebin2015** [comment]
核对过 ，一样呢   ，就在服务里面写的接口

**Comment by KomachiSion** [comment]
麻烦按照issue模版描述一下问题。

比如版本之类的信息都没有 无法判断问题。

目前最可能的原因， 注册和注销使用的不是同一个NamingService，您新创建的NamingService并不会关闭另一个NamingService的心跳线程，导致心跳还会继续发送。

我看您用的是spring cloud， 可以尝试直接获取spring cloud nacos bean中的namingService，然后调用注销。

**Comment by xiebin2015** [comment]
你好，根据你的提示检查了我的代码，之前的代码
NamingService namingService=NacosFactory.createNamingService(nacosDiscoveryProperties.getNacosProperties());
调整后的代码
 NamingService namingService=nacosDiscoveryProperties.namingServiceInstance();
 目前可以正常注销，谢谢
