### ISSUE TITLE
spring-cloud-alibaba-nacos-config 和 spring-cloud-starter-alibaba-nacos-discovery 不支持jdk9以及以上模块化吗？

### ISSUE THREAD

**Issue by ancientelves** [alibaba/nacos#520]
Error:java: the unnamed module reads package com.netflix.loadbalancer from both ribbon.httpclient and ribbon.loadbalancer
Error:java: the unnamed module reads package com.netflix.client.http from both ribbon.httpclient and ribbon.core
Error:java: the unnamed module reads package com.netflix.client from both ribbon.loadbalancer and ribbon.core
Error:java: the unnamed module reads package org.springframework.cloud.alibaba.nacos from both spring.cloud.alibaba.nacos.discovery and spring.cloud.alibaba.nacos.config
Error:java: the unnamed module reads package org.springframework.cloud.alibaba.nacos from both spring.cloud.alibaba.nacos.discovery and spring.cloud.alibaba.nacos.config

由于我使用了jdk11的模块化。不同jar中出现了相同包名导致分裂包编译失败？请问你们如何解决或者是在下一个版本会处理吗？

**Comment by nkorange** [comment]
Report it to [Spring Cloud Alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba)
