### ISSUE TITLE
Nacos YAML format has no value, the Java code pulled matching Nacos set file information to report an error (nacos yaml格式没有值，java 代码拉取配nacos置文件信息报错)

### ISSUE THREAD

**Issue by dearMOMO** [alibaba/nacos#5202]
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lettuceConnectionFactory' defined in class path resource [com/momo/configuration/RedisConfiguration.class]: Unsatisfied dependency expressed through method 'lettuceConnectionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genericObjectPoolConfig' defined in class path resource [com/momo/configuration/RedisConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.commons.pool2.impl.GenericObjectPoolConfig]: Factory method 'genericObjectPoolConfig' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.com.momo.configuration.RedisConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.redis.password' in value "${spring.redis.password}"
2021-03-26 13:44:39.849  INFO 10644 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-03-26 13:44:39.860 ERROR 10644 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'lettuceConnectionFactory' defined in class path resource [com/momo/configuration/RedisConfiguration.class]: Unsatisfied dependency expressed through method 'lettuceConnectionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'genericObjectPoolConfig' defined in class path resource [com/momo/configuration/RedisConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.commons.pool2.impl.GenericObjectPoolConfig]: Factory method 'genericObjectPoolConfig' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.com.momo.configuration.RedisConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.redis.password' in value "${spring.redis.password}"

**Comment by dearMOMO** [comment]
spring:
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    database: 0
    timeout: 300000

**Comment by dearMOMO** [comment]
spring:
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    database: 0
    timeout: 300000

**Comment by KomachiSion** [comment]
麻烦按照issue模版填写， 缺少必要信息， 无法判断问题
