### ISSUE TITLE
How use /nacos/v1/ns/service/list?pageNo=1&pageSize=1 API to get all services?

### ISSUE THREAD

**Issue by ctlove0523** [alibaba/nacos#5204]
I hava two service spring-cloud-nacos and spring-cloud-gateway-nacos in DEFAULT_GROUP,when i use `/nacos/v1/ns/service/list?pageNo=1&pageSize=1` the result like follow:

**Case1:**
curl -i http://10.0.75.1:8848/nacos/v1/ns/service/list?pageNo=1&pageSize=1
*Response；*
~~~
{
    "doms": [
        "spring-cloud-nacos"
    ],
    "count": 1
}
~~~

**Case2**
curl -i http://10.0.75.1:8848/nacos/v1/ns/service/list?pageNo=2&pageSize=1
*Response:*
~~~
{
    "doms": [
        "spring-cloud-gateway-nacos"
    ],
    "count": 1
}
~~~

**Case3:**
curl -i http://10.0.75.1:8848/nacos/v1/ns/service/list?pageNo=3&pageSize=1
*Response:*
~~~
{
    "doms": [
        "DEFAULT_GROUP@@spring-cloud-nacos",
        "DEFAULT_GROUP@@spring-cloud-gateway-nacos"
    ],
    "count": 2
}
~~~
when increase the value of pageNo the response is same.

**How can I use this api to get all  services in nacos?**

**Comment by shalk** [comment]
becasue this is pageable api, if you want get all service, you could make pageSize big enough to get all services in one page.

like ` /nacos/v1/ns/service/list?pageNo=1&pageSize=1000000`

**Comment by ctlove0523** [comment]
because i only have two service,so pageSize = 10 is enough.when i call api like this:

curl -i http://10.0.75.1:8848/nacos/v1/ns/service/list?pageNo=1&pageSize=10
Response is:
~~~
{
    "doms": [
        "spring-cloud-nacos",
        "spring-cloud-gateway-nacos"
    ],
    "count": 2
}
~~~

curl http://10.0.75.1:8848/nacos/v1/ns/service/list?pageNo=2&pageSize=10
~~~
{
    "doms": [
        "DEFAULT_GROUP@@spring-cloud-nacos",
        "DEFAULT_GROUP@@spring-cloud-gateway-nacos"
    ],
    "count": 2
}
~~~

can the api return totalCount of service,so i can use api to get all service and determine when to stop?

**Comment by ctlove0523** [comment]
@shalk 
Thanks,i will try read source code,if this is a really bug i can help to fix it.

**Comment by haoyann** [comment]
@ctlove0523 
What version do you use, I cannot reproduce it locally using the develop branch.
1. http://localhost:8848/nacos/v1/ns/service/list?pageNo=1&pageSize=10
![image](https://user-images.githubusercontent.com/43994656/112756556-56836a80-9018-11eb-8c6b-696cb677b1dc.png)

2. http://localhost:8848/nacos/v1/ns/service/list?pageNo=2&pageSize=10
![image](https://user-images.githubusercontent.com/43994656/112756565-6438f000-9018-11eb-853b-1e6836887a39.png)

**Comment by ctlove0523** [comment]
@haoyann 
I use this version `2.0.0 (Mar 20th, 2021)` for test. Code in develop branch works well.

**Comment by lingsamuel** [comment]
This bug still exists. 

![image](https://user-images.githubusercontent.com/14567045/120929583-2e04a480-c71c-11eb-8ff9-05184e2ec3e3.png)

I am using `nacos/nacos-server:latest` digest `2096d66ae793`
