### ISSUE TITLE
suppose upgrade lib mockito from 2.34.4 to 3.40.0+

### ISSUE THREAD

**Issue by shalk** [alibaba/nacos#5206]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
current mockito verion is 2.34.4 from spring-boot-dependencies 2.1.17.RELEASE  in dependencyManagement

"Mockito 3 does not introduce any breaking API changes, but now requires Java 8 over Java 6 for Mockito 2."

I suppose try to upgrade the lib , since 3.40.0+ , mockito can mock static method without powermock.

lib scope is test , i think this is no risk only benefit.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
When upgrade to mockito3, should we need to change our test codes?
