### ISSUE TITLE
无法注册持久化实例

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#5208]
服务：
nacos2.0.0
应用：
从官方文档上找的示例
https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-discovery-example/nacos-spring-cloud-provider-example
其中使用的client的版本是1.0.0

部署位置：
应用与nacos服务在同一台服务器上
服务运行方式：
单个服务独立运行
sh startup.sh -m standalone

启动时试过在配置文件配置
spring.cloud.nacos.discovery.ephemeral=false
控制台上还是显示为临时实例

然后尝试用命令直接修改应用为持久化实例
curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?port=8070&healthy=true&ip=对应ip&weight=1.0&serviceName=service-provider&ephemeral=false&namespaceId=public'
返回ok
但是控制台上还是显示为临时实例

了解到有ap和cp模式，有说需要调整成cp模式，才能支持持久化实例，于是使用以下请求修改模式
curl -X PUT '$NACOS_SERVER:8848/nacos/v1/ns/operator/switches?entry=serverMode&value=CP'
返回ok
再尝试使用
curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?port=8070&healthy=true&ip=对应ip&weight=1.0&serviceName=service-provider&ephemeral=false&namespaceId=public'
修改应用为持久化实例
返回ok
但是控制台上还是显示为临时实例

**Comment by woshishitou** [comment]
能帮忙看下怎么回事吗，多谢了

**Comment by woshishitou** [comment]
对了，这个我也试过了
curl -X PUT '$NACOS_SERVER:8848/nacos/v1/ns/operator/switches?entry=defaultInstanceEphemeral&value=false'

**Comment by jackwang-wangcb** [comment]
我这里也是 实例无法持久，实例持久不满足我的需求，所以没研究

**Comment by woshishitou** [comment]
我把nacos服务端重启，然后那个实例就变成false了。
但是，用另一个服务做试验，无法复现。
也就是说，我还是不知道怎么把实例注册或者修改成持久化实例。

**Comment by woshishitou** [comment]
被注册为永久实例的，我配置了http的健康检查，也没看到我定制的检查接口被调用了。能说下具体是什么调用机制吗？隔多长时间调用一次？

**Comment by KomachiSion** [comment]
1. 可能是example使用的SCA和client版本比较旧，没有读取到持久化参数。注册成了临时实例
2. 2.0之后，如果某个服务被注册成非持久化，后续的实例应该都无法注册成持久化实例，只是目前没有报错
3. 修改实例的接口不应该能够修改实例的持久化类型，否则数据一致性可能会出现问题
4. 我拿2.0.0的demo （console.naco.io)试了一下，无法复现问题

![image](https://user-images.githubusercontent.com/37170243/112775697-3a131c80-9070-11eb-9ca6-de0284ba1e27.png)
![image](https://user-images.githubusercontent.com/37170243/112775710-44cdb180-9070-11eb-8552-eeb43e5ec0dc.png)

**Comment by woshishitou** [comment]
非常感谢。
我这边是sca版本的问题，example中用的sca版本是0.9.0，比较老了，无法读取spring.cloud.nacos.discovery.ephemeral这个配置。我只过2.1.4和2.2.5这两个版本的sca都可以，其他版本没有测试。
