### ISSUE TITLE
Reflections Exception warning

### ISSUE THREAD

**Issue by luterc** [alibaba/nacos#5209]
**Describe the bug**
with Spring boot 2.3.9 and spring cloud alibaba 2.2.5 ,when starting ,there is a warning :

`org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Library/Java/Extensions/libsigar-universal64-macosx.dylib]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.`

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1.  start 

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur  11.2.3
 - Version  nacos-server-2.0.0 & nacos-client-2.0.0
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
It seems not nacos' problem, your system don't has `file:/Library/Java/Extensions/libsigar-universal64-macosx.dylib`. You should check and fix it by yourself.

Or provide more detail information about nacos'

**Comment by shaohaikkk** [comment]
I also encountered this mistake base docker images java:8. If it appears under the general basic mirror, it means that the probability of everyone appearing is still very high, and the repair that we hope can be obtained. BEST WISH !!!
