### ISSUE TITLE
Dubbo注册的服务无法编辑设置权重

### ISSUE THREAD

**Issue by wzlee** [alibaba/nacos#521]
相关版本：
dubbo: 2.6.5
dubbo-registry-nacos:  0.0.2
nacos-client: 0.7.0
spring-cloud-starter-alibaba-*: 0.2.1.BUILD-SNAPSHOT
nacos控制台提示信息：

metadata format incorrect:owner=leo,side=provider,accepts=10000,application.version=1.0.0,methods=searchByNickname,count,save,update,findPage,delete,findByAccountId,get,findList,exists,dubbo=2.0.2,threads=1000,pid=93514,interface=com.example.demo.api.service.HelloService,threadpool=eager,generic=false,serialization=fst,protocol=dubbo,application=demo-core,organization=landray,category=providers,dispatcher=execution,anyhost=true,bean.name=ServiceBean:com.example.demo.api.service.HelloService,status=server,timestamp=1545729908337

**Comment by wzlee** [comment]
补充一点：discovery注册的服务可以编辑权重，但调用的时候不生效

**Comment by mercyblitz** [comment]
It's unimplemented now, it will be supported in the future.

**Comment by nkorange** [comment]
This feature requires development in Dubbo, please submit a issue in Dubbo repository.

**Comment by hanzeyao** [comment]
同  dubbo 2.7.3  nacos 1.1.4 权重不生效
