### ISSUE TITLE
Nacos client add method to get all service

### ISSUE THREAD

**Issue by ctlove0523** [alibaba/nacos#5218]
**Describe the solution you'd like**
`NamingService` add `ListView<String> getServicesOfServer() throws NacosException;`

**Additional context**
1、add method is compatible

**Comment by Jayice-zjw** [comment]
If this feature is needed, I can solve it

**Comment by KomachiSion** [comment]
Refuse this feature, this API has provided, if you can accept the cost of this API, you can use getServicesOfServer(int pageNo, int pageSize) to get all service. make the pageSize as Integer.Max 

Nacos client will provider the API to get `ALL` service to avoid the error usage which cause server down.
