### ISSUE TITLE
nacos-springboot支持aes256吗

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#5219]
nacos1.3.0, 配置了aes256加密/解密，如aaa=ENC(y29oR+BG0TqGJeXh4GeD2C+ggkL7WGjPHYoDajcQ1b9pT5tM4ewTcpYND9CHrEOp)，这个写在application.properties上可以正常解密，但是写在controller上面解密不了     
@NacosValue(value = "${kyligence.cloud.security-admin-role:admin_group_placeholder}", autoRefreshed = true)
    private String adminGroup;

访问的时候现实的 还是ENC(y29oR+BG0TqGJeXh4GeD2C+ggkL7WGjPHYoDajcQ1b9pT5tM4ewTcpYND9CHrEOp)
这个是个by design的设计吗，config的值的解密有应用程序处理

**Comment by JackSun-Developer** [comment]
`
@NacosValue(value = "${kyligence.cloud.security-admin-role:admin_group_placeholder}", autoRefreshed = true)
private String adminGroup;
 `

nacos-springboot应该没有提供默认的加解密程序，这个加解密程序应该是交由用户根据自己的需要来自定义的。
