### ISSUE TITLE
0.7.0版本权重写0时生效，配置大于0时均是55开

### ISSUE THREAD

**Issue by zympig** [alibaba/nacos#522]
![image](https://user-images.githubusercontent.com/26918258/50420278-798aa700-0870-11e9-9ea1-e1c7407f8d14.png)
如下结果交替出现，但是权重置零时生效
![image](https://user-images.githubusercontent.com/26918258/50420267-6677d700-0870-11e9-96a4-84322c31a7bf.png)
![image](https://user-images.githubusercontent.com/26918258/50420285-827b7880-0870-11e9-8321-03fd4b1abb48.png)

**Comment by xuechaos** [comment]
@zympig  已经沟通过，spring cloud alibaba 这个问题下个版本考虑做进去。感谢你的反馈，👍。
