### ISSUE TITLE
k8s集群部署，节点ip解析混乱

### ISSUE THREAD

**Issue by liuyunlong1229** [alibaba/nacos#5222]
**Describe the bug**
因为节点ip解析的问题，会导致一个pod生成2个节点，导致集群状态不稳定，参考下图

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
我们在k8s环境中搭建了1个集群，为供2套环境使用，因此定义了2套service作为访问入口。

集群部署文件如下：

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos-c1-pre-pro
  labels:
    appEnv: pre
    appName: nacos-c1-pre-pro
  namespace: nacos
spec:
  serviceName: nacos-c1-pro
  replicas: 3
  selector:
    matchLabels:
      appEnv: pre
      appName: nacos-c1-pre-pro
  template:
    metadata:
      labels:
        appEnv: pre
        appName: nacos-c1-pre-pro
    spec:
      tolerations:
        - key: "topology.kubernetes.io/region"
          operator: "Equal"
          value: "xxx"
          effect: "NoSchedule"
        - key: "topology.kubernetes.io/zone"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "topology.kubernetes.io/env"
          operator: "Equal"
          value: "xxx"
          effect: "NoSchedule"
        - key: "topology.kubernetes.io/type"
          operator: "Equal"
          value: "xxx"
          effect: "NoSchedule"
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: topology.kubernetes.io/region
                 operator: In
                 values:
                 - xxx
               - key: topology.kubernetes.io/zone
                 operator: Exists
               - key: topology.kubernetes.io/env
                 operator: In
                 values:
                 - xxx
               - key: topology.kubernetes.io/type
                 operator: In
                 values:
                 - xxx
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 100
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                   - key: appName
                     operator: In
                     values:
                     - xxxxxxxxx
               topologyKey: topology.kubernetes.io/zone
      dnsPolicy: ClusterFirst
      containers:
      - name: nacos
        image: xxx/nacos-server:1.4.0
        ports:
        - containerPort: 8848
        env:
        - name: NACOS_REPLICAS
          value: "3"
        - name: MYSQL_SERVICE_HOST
          value: xxxxxxxxxxxx
        - name: MYSQL_SERVICE_DB_NAME
          value: xxxxxxxxx
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_USER
          value: nacos
        - name: MYSQL_SERVICE_PASSWORD
          value: xxxxxxxx
        - name: MODE
          value: cluster
        - name: NACOS_SERVER_PORT
          value: "8848"
        - name: PREFER_HOST_MODE
          value: hostname
        - name: SPRING_DATASOURCE_PLATFORM
          value: mysql
        - name: TOMCAT_ACCESSLOG_ENABLED
          value: "true"
        - name: NACOS_AUTH_ENABLE
          value: "true"
        - name: NACOS_SERVERS
          value: nacos-c1-pre-pro-0.nacos-c1-pro.nacos.svc.cluster.local:8848 nacos-c1-pre-pro-1.nacos-c1-pro.nacos.svc.cluster.local:8848 nacos-c1-pre-pro-2.nacos-c1-pro.nacos.svc.cluster.local:8848
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/hosts
          name: vol-generic-hosts
      volumes:
      - name: vol-generic-hosts
        hostPath:
          path: /etc/hosts`

service定义文件如下：

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-c1-pre
  namespace: nacos
  labels:
    appEnv: pre
    appName: nacos-c1-pre-pro
spec:
  selector:
    appEnv: pre
    appName: nacos-c1-pre-pro
  ports:
    - name: nacos
      port: 8848
      targetPort: 8848
      protocol: TCP
  sessionAffinity: None
  clusterIP: None
  topologyKeys:
  - "kubernetes.io/hostname"
  - "topology.kubernetes.io/zone"
  - "topology.kubernetes.io/region"
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-c1-pro
  namespace: nacos
  labels:
    appEnv: pro
    appName: nacos-c1-pre-pro
spec:
  selector:
    appEnv: pre
    appName: nacos-c1-pre-pro
  ports:
    - name: nacos
      port: 8848
      targetPort: 8848
      protocol: TCP
  sessionAffinity: None
  clusterIP: None
  topologyKeys:
  - "kubernetes.io/hostname"
  - "topology.kubernetes.io/zone"
  - "topology.kubernetes.io/region"

集群起来后，会生成一个如下的节点

**10-20-236-212.nacos-c1-pre.nacos.svc.cluster.local:8848** 

其中的10-20-236-212为某个pod的ip，nacos-c1-pre为pod对应另外一个环境的service的名称（上面的文件种有定义），此时的cluster.conf中也会多一条记录

[root@nacos-c1-pre-pro-0 conf]# cat cluster.conf
#2021-03-22T11:39:19.162
**10-20-236-212.nacos-c1-pre.nacos.svc.cluster.local:8848**
nacos-c1-pre-pro-0.nacos-c1-pro.nacos.svc.cluster.local:8848
nacos-c1-pre-pro-1.nacos-c1-pro.nacos.svc.cluster.local:8848
nacos-c1-pre-pro-2.nacos-c1-pro.nacos.svc.cluster.local:8848

**Desktop (please complete the following information):**
  版本信息
 - k8s版本 v1.19.0
 - nacos 版本 v1.4.0

**Additional context**
![图片1](https://user-images.githubusercontent.com/16921480/112796253-4d3be180-909c-11eb-90c7-c89b485ca8b6.png)
![集群状态图](https://user-images.githubusercontent.com/16921480/112794373-5e372380-9099-11eb-8dd0-cd2e4f7f3e3e.png)

**Comment by KomachiSion** [comment]
Can you provide the `conf/cluster.conf` file?

**Comment by liuyunlong1229** [comment]
> Can you provide the `conf/cluster.conf`
现在我集群重启了，没法提供该文件，重启之前发现生成了除server_List外的，新生成一条记录，也就是截图上面的10.20.246.37-nacos-c8-pre……的记录。

**Comment by wangweizZZ** [comment]
部署的yaml 文件也提供下呢

**Comment by liuyunlong1229** [comment]
> 部署的yaml 文件也提供下呢

已经提供，部署集群和service定义都在上面了

**Comment by liuyunlong1229** [comment]
> 部署的yaml 文件也提供下呢

已经提供，部署集群和service定义都在上面了

**Comment by wangweizZZ** [comment]
为何需要两个service，明明就是一套服务。另外/etc/hosts也不必挂载吧。

**Comment by KomachiSion** [comment]
应该是k8s生成的环境带了多个hostname，然后取到了其中一个。

k8s我不是特别熟悉，只知道生成多个hostname就和多网卡一样，nacos需要指定一下nacos.server.ip=hostname。

或者修改k8s配置，让他不生成多hostname。

**Comment by clannon** [comment]
遇到了同样的问题，nacos 1.4.1，和楼主不同的是，我这边k8s是正常的3节点，传统服务器部署反而多了一个

**k8s的集群环境（k8s-v4c）：**

![image](https://user-images.githubusercontent.com/34529891/113393196-e5053c80-93c8-11eb-9e5c-7add859ab54f.png)

只简单用了configmap：

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cm-nacos
      namespace: k8s-v4c
    data:
      MODE: cluster
      PREFER_HOST_MODE: hostname
      NACOS_REPLICAS: "3"
      NACOS_AUTH_TOKEN: xxxx
      NACOS_SERVERS: "nacos-server-0.nacos-server.k8s-v4c.svc.cluster.local:8848 nacos-server-1.nacos-server.k8s-v4c.svc.cluster.local:8848 nacos-server-2.nacos-server.k8s-v4c.svc.cluster.local:8848"
      MYSQL_SERVICE_HOST: xxxx
      MYSQL_SERVICE_DB_NAME: xxxx
      MYSQL_SERVICE_USER: xxxx
      MYSQL_SERVICE_PASSWORD: xxxx


**传统部署**（k8s-v4h混合环境，微服务用k8s，数据库、中间件等程序使用传统部署）：

![image](https://user-images.githubusercontent.com/34529891/113394154-52659d00-93ca-11eb-9482-0a6ad6cb64b5.png)

从nginx负载访问，第一个会随机变

application.properties开启了这个：

    nacos.inetutils.prefer-hostname-over-ip=true

conf/cluster.conf：

    k8s-v4h-nacos-server01
    k8s-v4h-nacos-server02
    k8s-v4h-nacos-server03

/etc/hosts 解析：

    192.168.3.x     ecs13 ... k8s-v4h-nacos-server01
    192.168.3.y     ecs14 ... k8s-v4h-nacos-server02
    192.168.3.z     ecs15 ... k8s-v4h-nacos-server03

nacos似乎又去找了自己的hostname（或者第一个host），然后加进了集群？
日志中也在不停的刷：

![image](https://user-images.githubusercontent.com/34529891/113394646-3282a900-93cb-11eb-9291-71f5060ba8a9.png)

**Comment by clannon** [comment]
补充一下节点元数据：

正常的：

![2021-04-06_101131](https://user-images.githubusercontent.com/34529891/113649720-84744900-96c1-11eb-9051-d03f7d4fdcae.png)

不正常的：

![2021-04-06_101013](https://user-images.githubusercontent.com/34529891/113649738-8b9b5700-96c1-11eb-88c1-24152df95563.png)


这个问题好复现，开了三个虚拟机用传统部署方式，按照上面的配置用host做集群就有问题了

**Comment by clannon** [comment]
补充一下节点元数据：

正常的：

![2021-04-06_101131](https://user-images.githubusercontent.com/34529891/113649720-84744900-96c1-11eb-9051-d03f7d4fdcae.png)

不正常的：

![2021-04-06_101013](https://user-images.githubusercontent.com/34529891/113649738-8b9b5700-96c1-11eb-88c1-24152df95563.png)


这个问题好复现，开了三个虚拟机用传统部署方式，按照上面的配置用host做集群就有问题了

**Comment by KomachiSion** [comment]
那就是环境问题啊， 配置的域名和本地域名不一样。nacos认为自己不在集群里，于是尝试添加进去。

cluster.conf需要配置可访问可读取的域名， 如果是多域名多网卡的模式，需要使用-Dnacos.server.ip=${domain}方式指定排错。Docker和application.properties都有对应的参数修改这个值， 细节看看文档和docker项目的wiki
