### ISSUE TITLE
nacos2.0.0不支持将服务注册到多nacos中，并且使用权限认证的用户登录报403

### ISSUE THREAD

**Issue by Jamel-jun** [alibaba/nacos#5232]
## spring-cloud-alibaba: 2.2.5.RELEASE

# 1. 服务注册到多nacos中
** bootstrap.yaml **
![image](https://user-images.githubusercontent.com/50609931/112835388-c999e900-90cb-11eb-9d86-19c33c0f4d9a.png)
两个nacos控制台中，只有前者会显示(bootstrap: server-addr 第一个地址)，后面那个没有注册上去 但是没有报错。
在1.4.1中是没有问题的

# 2. 权限认证
** 用户列表 **
![image](https://user-images.githubusercontent.com/50609931/112835545-006fff00-90cc-11eb-9577-c89a9d293865.png)
** 角色列表 **
![image](https://user-images.githubusercontent.com/50609931/112835582-0bc32a80-90cc-11eb-8abf-014efd74a7c2.png)
** 权限列表 **
![image](https://user-images.githubusercontent.com/50609931/112835604-12ea3880-90cc-11eb-9076-923082edb635.png)
** bootstrap.yaml **
![image](https://user-images.githubusercontent.com/50609931/112835696-34e3bb00-90cc-11eb-8709-ce8b98c04eb3.png)

** 错误信息 **
![image](https://user-images.githubusercontent.com/50609931/112835857-69f00d80-90cc-11eb-9920-e4e574123d6c.png)
注: 密码没问题，控制台中可直接访问，telnet网络是通的，采用nacos admin管理员用户 是可以的

**Comment by haoyann** [comment]
有指定namespace吗？

**Comment by KomachiSion** [comment]
看设置并没有问题，nacos应该是管理员用户

有更多的错误信息吗？ 你贴出的错误信息看不出来问题。也没有403提示

关于多nacos的问题，没看懂，你2个地址是一样。而且nacos也不支持多注册中心，提供多个地址是做负载均衡的，这些地址应该是一个集群。。

**Comment by Jamel-jun** [comment]
> 有指定namespace吗？

有的，同样的配置在1.4.1下是可以用的

**Comment by Jamel-jun** [comment]
> 看设置并没有问题，nacos应该是管理员用户
> 
> 还有更多的错误信息吗？你贴出的错误信息看不出来问题。也没有403提示
> 
> 关于多nacos的问题，没看懂，你2个地址是一样。而且nacos也不支持多注册中心，提供多个地址是做负载均衡的，这些地址应该是一个占用。。
nacos版本1.4.1中是可以注册到多个nacos中的，已经上生产，没有问题。
在2.0.0中无法注册多个地址。
** 最新bootstrap.yaml **
![image](https://user-images.githubusercontent.com/50609931/112922364-f804dc00-913e-11eb-8212-68e76a69fd1d.png)

**Comment by warthur1214** [comment]
403的问题看下这个issue: #https://github.com/alibaba/nacos/issues/5215

**Comment by KomachiSion** [comment]
@Jamel-jun 新增用户报错的话，需要看一下账号是否有对应namespace的权限。

**Comment by Jamel-jun** [comment]
> 403的问题看下这个issue: #5215
> nacos2.0的账号必须分配public空间权限

分配public空间权限后解决了权限用户这个问题，但是注册多个nacos还是不行

**Comment by Jamel-jun** [comment]
> @Jamel-jun 新增用户报错的话，需要看一下账号是否有对应namespace的权限。

分配public空间权限后解决了权限用户这个问题，但是注册多个nacos还是不行

**Comment by KomachiSion** [comment]
本来就不支持注册多nacos。

那个,是让你填同一个集群的不同机器的，用于负载均衡。
