### ISSUE TITLE
The page can be edited while the publishing-config request is processing

### ISSUE THREAD

**Issue by zhangcly** [alibaba/nacos#5234]
**Is your feature request related to a problem? Please describe.**
when i publish the config, and the backend is blocked, the config-editing page still can be edited

**Describe the solution you'd like**
after a publishing-config request, the page should pending until request finished or time out

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/43567778/112855173-2784fb80-90e1-11eb-8806-8a1ec4db65aa.mp4

**Comment by ShawnSiao** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
How to solve it? @ShawnSiao , can you describe solution in issue?

**Comment by ShawnSiao** [comment]
Before i took this issue,i thought when i click the confirm button,i can set the page be in loading like other pages.
Now i read some of the code, i found this page's request function is different to others.
Maybe i need to modify public component to fix this issue.
Give me a few days to try to solve it,if i can not solve it i will comment.
Thanks. @KomachiSion
