### ISSUE TITLE
nacos v2.0.0 server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by EvilDrag0n** [alibaba/nacos#5238]
**Describe the bug**
I follow the [tutorial](https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html) to deploy the cluster mode in the virtual machine.
我是按照[教程](https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html)来在虚拟机部署集群模式。
But in the registration service step
但是在注册服务步骤
`curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'`
Unexpected prompt appears
在该步骤时出现提示
`server is DOWN now, please try again later!`

**Expected behavior**
Hope to deploy correctly according to the tutorial
希望能按照教程正确部署

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. Modify the cluster.conf to add more ip and port 
2. init db
3. modify application.properties add db connection information
4. start the nacos
5. `curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'`
6. `server is DOWN now, please try again later!`

**Desktop (please complete the following information):**
 - OS: Cent OS 7.4
 - Version nacos 2.0.0
 - Module all
 - SDK original

**Additional context**
#### cluster.conf content
```
#2021-03-30T16:43:13.408
192.168.64.131:8848
192.168.64.132:8848
192.168.64.133:8848
```
![image](https://user-images.githubusercontent.com/29672402/112963683-31a70880-917a-11eb-802c-1ab59ea97df4.png)
#### console node list
![image](https://user-images.githubusercontent.com/29672402/112963827-5602e500-917a-11eb-87a9-93ec7ed33641.png)

**Comment by KomachiSion** [comment]
节点元数据不正确， 没有raft的内容，查看一下alipay-jraft.log ， protocol-raft.log

另外确认下虚拟机的7848端口，9848端口和9849端口是否开放。

2.0.0 文档 https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by EvilDrag0n** [comment]
> 节点元数据不正确， 没有raft的内容，查看一下alipay-jraft.log ， protocol-raft.log
> 
> 另外确认下虚拟机的7848端口，9848端口和9849端口是否开放。
> 
> 2.0.0 文档 https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

`2021-03-30 19:02:50,038 WARN Node <naming_persistent_service_v2/192.168.64.133:7848> channel init failed, address=192.168.64.131:7848.

2021-03-30 19:02:50,038 WARN Channel[192.168.64.132:7848] in TRANSIENT_FAILURE state 21 times, will be reset connect backoff.
`
👍
建议文档补上 7848端口开放
