### ISSUE TITLE
服务端由1.1.3升级到2.0.0，命名空间的处理

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#5247]
我们之前一直使用的是nacos1.1.3服务，现在想要升级到2.0.0。

关于命名空间这一块，我们是让各应用启动时指定命名空间ID来确定环境的，现在想要升级，是不是只要在2.0.0里面把之前所有的命名空间创建好（按照1.1.3中的ID和名称），然后让应用改成指向新部署的nacos2.0.0服务地址（这里不讨论客户端版本的问题），最后重启应用就可以了？

我观察到1.1.3和2.0.0在创建命名空间时有区别，后者可以自定义命名空间ID，而前者不可以，这是否是为升级考虑的？

**Comment by KomachiSion** [comment]
自定义ID是1.2.1开始就可以的功能，对于升级来说并没有区别，只需要保证ID是一致就可以。由于namespace应该是持久化到数据库了，所以应该保证连接同一个数据库就可以。

**Comment by KomachiSion** [comment]
2.0.0理论上支持1.X版本的平滑升级，如果像要使用双注册中心进行升级，那么需要2.0这边创建好命名空间。

如果使用同一个数据库，应该直接能够获取到。

**Comment by woshishitou** [comment]
明白了，感谢
