### ISSUE TITLE
tag:v2.0.0 openApi-heartbeat interface has some bug

### ISSUE THREAD

**Issue by masterhHy** [alibaba/nacos#5249]
使用openApi /nacos/v1/ns/instance/beat 接口时，服务端(注册中心) 不能连续感知到 客户端发来的心跳包，导致注册列表的应用不健康下线。等客户端在发心跳包时，nacos才感知(ps:客户端设置发送心跳 2秒一次)

**Comment by horizonzy** [comment]
你好，能够确认客户端每2秒发送一次心跳请求到服务端吗？
1.服务端如果没有关闭access_log的话能够在access_log看到客户端的心跳请求是否到了服务端。
2.如果没有的话，在本地通过tcpdump把抓一下到nacos服务端的包，看下心跳请求是否是2秒一次到了服务端。

**Comment by KomachiSion** [comment]
1. 确认下是否所有的服务端都已经是2.0的状态模式。
2. 是自己调用openAPI发送的心跳还是使用nacos-client发送的。
3. 如果是自己调用的openAPI，需要使用轻量化心跳模式；如果不是轻量化模式，请升级到2.0.0-bugfix再尝试。

**Comment by masterhHy** [comment]
确认已连续发送，服务端access_log 也收到了，但是还出现上述情况

**Comment by KomachiSion** [comment]
我这边复现不出这个问题，推测还是集群状态没有正确搭建，

https://nacos.io/zh-cn/docs/2.0.0-upgrading.html

可以看下这个文档，其中5，7，8.1步骤需要仔细确认一下。
