### ISSUE TITLE
nacos config客户端从1.1.4升级到2.0.0，如何把配置的内容打印出来

### ISSUE THREAD

**Issue by zqr95518** [alibaba/nacos#5250]
nacos config客户端从1.1.4升级到2.0.0
本来会有一个yaml内容的content的打印，请问如何显示出来

**Comment by KomachiSion** [comment]
2.0客户端应该也会打印。能提供更多信息吗？

**Comment by shiyiyue1102** [comment]
> 出来

你指定的哪个地方会打印呢，麻烦提供详细些的信息

**Comment by zqr95518** [comment]
2.0.0的nacos客户端读取配置的时候只会显示

**Comment by KomachiSion** [comment]
你这个日志是从哪里看到的， 到${user.home}/logs/nacos/config.log下看看

**Comment by zqr95518** [comment]
这个是我客户端上的log，不是服务端上的，我希望客户端上打印yaml的内容

**Comment by KomachiSion** [comment]
${user.home}/logs/nacos/config.log 这个就是客户端日志

**Comment by zqr95518** [comment]
我客户端没有本地日志，我想打印到控制台要怎么配日志

**Comment by KomachiSion** [comment]
nacos的客户端日志不应该打印到你业务里。之前可能是因为和SCA融合有bug。导致大量打印到业务日志里。

${user.home}/logs/nacos/config.log到这个下面去找nacos的客户端日志才是正确的。

**Comment by zqr95518** [comment]
我这个服务一般只能看到控制台的，访问文件目录很麻烦，自己配的配置文件，怕配错配置，所以希望在启动的时候，客户端的控制台上显示一次nacos上更改了那些配置项

**Comment by KomachiSion** [comment]
那需要找SCA实现一下这个功能。

Nacos客户端不希望吧日志打印在业务日志，主要原因是当网络出现问题或者注册/配置中心出现问题时，客户端会打印大量错误日志。如果输出到业务日志，会对业务本身排查错误有极大的影响。

**Comment by zqr95518** [comment]
我觉得可以把这些日志都放到debug层级，需要的人手动打开

**Comment by KomachiSion** [comment]
那会对nacos本身的问题排查有极大影响。。

**Comment by zqr95518** [comment]
是否获取到了正确的配置应该也是一个需要排查的内容吧？分组，分profile啥的

**Comment by KomachiSion** [comment]
因此我建议到SCA那边申请打印出来。SCA是应用层框架，应用框架打印应用配置内容到应用日志，我认为比较合理。

nacos打印的日志语意是nacos的客户端和服务端通信的相关信息，接收到的配置只是其中一个内容。我认为还是打印在独立日志里比较合理。
