### ISSUE TITLE
dubbo registry nacos2.0 use-as-config-center=false not work

### ISSUE THREAD

**Issue by warthur1214** [alibaba/nacos#5252]
我使用dubbo注册nacos，为了防止dubbo服务信息出现在了配置列表里，
我在nacos1.4.1上通过dubbo.registry.use-as-config-center=false配置已经解决。

但在nacos2.0上又出现了，如下图：
![image](https://user-images.githubusercontent.com/13415982/113127687-9da57180-924b-11eb-9a82-77c72bbaa54c.png)

相关组件版本：
spring-cloud-starter-alibaba-nacos-discovery: 2.2.5.RELEASE
spring-cloud-starter-alibaba-nacos-config: 2.2.5.RELEASE
spring-cloud-starter-dubbo: 2.2.5.RELEASE
nacos-client: 2.0.0

dubbo配置：
```ruby
dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}?username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}
    parameters:
      namespace: ${spring.cloud.nacos.discovery.namespace}
    group: dubbo
    simplified: true
    use-as-config-center: false
    register: true
    subscribe: true
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.warthur.nacos.demo.domain.dubbo
  consumer:
    filter: ConsumerAuthFilter
  provider:
    filter: AuthorizationFilter
  cloud:
    subscribed-services: spring-cloud-nacos-demo
```

**Comment by KomachiSion** [comment]
这个nacos应该没有关系，服务名是什么都是dubbo或SCA传递给nacos-client的，issue可能需要转到SCA或者dubbo社区
