### ISSUE TITLE
compile  error 

### ISSUE THREAD

**Issue by shadow2016yy** [alibaba/nacos#5259]
i try to compile the project,but i got this error,i tried to change to 2.0 branch,it is the same error, what is wrong?
![image](https://user-images.githubusercontent.com/22142708/113233004-d63b5e80-92d0-11eb-8fb0-228d8654cc9b.png)

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/2.0.0-compatibility.html FaQ
