### ISSUE TITLE
Exception in thread "main" ErrCode:-401, ErrMsg:Client not connected,current status:STARTING

### ISSUE THREAD

**Issue by Tearan** [alibaba/nacos#5264]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Tearan** [comment]
![Uploading image.png…]()

**Comment by Tearan** [comment]
String content = configService.getConfig(dataId, group, 5000);
获取为空，dataID，group和NACOS匹配

**Comment by KomachiSion** [comment]
应该是客户端和服务端连接不上，看一下配置是否有问题。 看一下官方文档关于2.0兼容性和部署那一部分。

**Comment by KomachiSion** [comment]
There is no more response from author, so we think it is a usage problem.
