### ISSUE TITLE
nacos  2.0 搭建nginx集群问题：Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'},

### ISSUE THREAD

**Issue by SANDUO421** [alibaba/nacos#5269]
** 配置信息：

   #设定负载均衡的服务器列表 ：
   upstream nacos-cluster-test{
    server 172.22.1.82:8848 weight=1;
    server 172.22.1.83:8848 weight=1;
    server 172.22.1.84:8848 weight=1;
   }
  upstream nacos-grpc-9848{
      server 172.22.1.82:9848 weight=1;
      server 172.22.1.83:9848 weight=1;
      server 172.22.1.84:9848 weight=1;
   }
  upstream nacos-grpc-9849{
      server 172.22.1.82:9849 weight=1;
      server 172.22.1.83:9849 weight=1;
      server 172.22.1.84:9849 weight=1;
   }
  server {
        listen       8848;
        server_name  localhost;
        location / {
                       #请求转向taishan定义的服务器列表
                       proxy_pass http://nacos-cluster-test;
                       #将请求头转发给后端服务器
                       proxy_set_header Host $host:8848;
                       #后端的Web服务器可以通过X-Forwarded-For获取用户真实IP
                       proxy_set_header X-Forward-For $remote_addr;
                       root  /nacos/;
                       index index.php index.html index.htm;               
                 }
    }
    
    # grpc 代理配置
    server {
        listen 9848 http2; # grpc方式对外暴露端口
	server_name localhost;
	access_log logs/access1.log main;
	proxy_ignore_client_abort on;
        location / {
            grpc_pass grpc://nacos-grpc-9848; # 此处配置grpc服务的ip和端口
        }
    }
    server {
        listen 9849 http2; # grpc方式对外暴露端口
	server_name localhost;
	access_log logs/access2.log main;
	proxy_ignore_client_abort on;
        location / {
            grpc_pass grpc://nacos-grpc-9849; # 此处配置grpc服务的ip和端口
        }
    }

** 报错如下:

2021-03-30 18:04:21.066 ERROR 52104 --- [s.client.Worker] com.alibaba.nacos.common.remote.client   : Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, retryTimes=2,errorMessage=java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
2021-03-30 18:04:21.069 ERROR 52104 --- [s.client.Worker] c.a.n.client.config.impl.ClientWorker    : Async listen config change error 

com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked

**Comment by xulingfeng931027** [comment]
我也是这个问题 用2.0客户端连不上rpc端口  telnet又是通的 很奇怪

**Comment by Liu3334** [comment]
解决了吗

**Comment by KomachiSion** [comment]
不能以http2在nginx上暴露， 否则会在nginx会主动断开连接。

使用tcp转发来暴露试一下。

**Comment by KomachiSion** [comment]
There is no response. So we think it is a usage problem.

**Comment by SANDUO421** [comment]
没有解决，你解决了？如果解决了，请告诉我正确的配置谢谢！



联系人：张先生
电   话 : 18700191127
邮   箱 ***@***.***
 
发件人： Liu3334
发送时间： 2021-04-07 15:57
收件人： alibaba/nacos
抄送： sanduo; Author
主题： Re: [alibaba/nacos] nacos 2.0 搭建nginx集群问题：Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, (#5269)
解决了吗

**Comment by SANDUO421** [comment]
你解决了？如果解决了，请告诉我正确的配置谢谢！


联系人：张先生
电   话 : 18700191127
邮   箱 ***@***.***
 
发件人： 徐凌峰
发送时间： 2021-04-06 08:56
收件人： alibaba/nacos
抄送： sanduo; Author
主题： Re: [alibaba/nacos] nacos 2.0 搭建nginx集群问题：Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, (#5269)
我也是这个问题 用2.0客户端连不上rpc端口 telnet又是通的 很奇怪

**Comment by SANDUO421** [comment]
tcp没有解决，你解决了？如果解决了，请告诉我正确的配置谢谢！



联系人：张先生
电   话 : 18700191127
邮   箱 ***@***.***
 
发件人： 杨翊 SionYang
发送时间： 2021-04-08 14:44
收件人： alibaba/nacos
抄送： sanduo; Author
主题： Re: [alibaba/nacos] nacos 2.0 搭建nginx集群问题：Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, (#5269)
不能以http2在nginx上暴露， 否则会在nginx会主动断开连接。
使用tcp转发来暴露试一下。

**Comment by SANDUO421** [comment]
> 解决了吗

没有解决，你解决了？

**Comment by SANDUO421** [comment]
能否给一个解决方案，在线等

**Comment by SANDUO421** [comment]
> 我也是这个问题 用2.0客户端连不上rpc端口 telnet又是通的 很奇怪

解决了没？

**Comment by SANDUO421** [comment]
> There is no response. So we think it is a usage problem.

能够尽快给一个解决方案，谢谢

**Comment by SANDUO421** [comment]
> 不能以http2在nginx上暴露， 否则会在nginx会主动断开连接。
> 
> 使用tcp转发来暴露试一下。

# tcp 代理配置
stream {
    upstream nacos-grpc-9848{
	  server 172.22.1.82:9848 weight=1;
	  server 172.22.1.83:9848 weight=1;
	  server 172.22.1.84:9848 weight=1;
	}
    upstream nacos-grpc-9849{
	  server 172.22.1.82:9849 weight=1;
	  server 172.22.1.83:9849 weight=1;
	  server 172.22.1.84:9849 weight=1;
   }
	server {
		listen 9848 ; # grpc方式对外暴露端口
		proxy_connect_timeout 1s;
		proxy_timeout 3s;
		proxy_pass nacos-grpc-9848; # 此处TCP端口转发代理
	}
	server {
		listen 9849 ; # grpc方式对外暴露端口
		proxy_connect_timeout 1s;
		proxy_timeout 3s;
		proxy_pass nacos-grpc-9849; # 此处TCP端口转发代理
	}

}	


失败
报错：om.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

**Comment by SANDUO421** [comment]
> There is no response. So we think it is a usage problem.
# tcp 代理配置
stream {
    upstream nacos-grpc-9848{
	  server 172.22.1.82:9848 weight=1;
	  server 172.22.1.83:9848 weight=1;
	  server 172.22.1.84:9848 weight=1;
	}
    upstream nacos-grpc-9849{
	  server 172.22.1.82:9849 weight=1;
	  server 172.22.1.83:9849 weight=1;
	  server 172.22.1.84:9849 weight=1;
   }
	server {
		listen 9848 ; # grpc方式对外暴露端口
		proxy_connect_timeout 1s;
		proxy_timeout 3s;
		proxy_pass nacos-grpc-9848; # 此处TCP端口转发代理
	}
	server {
		listen 9849 ; # grpc方式对外暴露端口
		proxy_connect_timeout 1s;
		proxy_timeout 3s;
		proxy_pass nacos-grpc-9849; # 此处TCP端口转发代理
	}

}	
om.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

**Comment by Yvan0329** [comment]
请问解决了吗，我也碰到了这个问题。

**Comment by Liu3334** [comment]
服务器hosts问题，改了hosts找不到ip


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月11日 18:16:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] nacos  2.0 搭建nginx集群问题：Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, (#5269)




 
请问解决了吗，我也碰到了这个问题。

**Comment by Yvan0329** [comment]
> There is no response. So we think it is a usage problem.

同样的问题，使用nginx，client无法注册

**Comment by Yvan0329** [comment]
> > There is no response. So we think it is a usage problem.
> 
> ## tcp 代理配置
> stream {
> upstream nacos-grpc-9848{
> server 172.22.1.82:9848 weight=1;
> server 172.22.1.83:9848 weight=1;
> server 172.22.1.84:9848 weight=1;
> }
> upstream nacos-grpc-9849{
> server 172.22.1.82:9849 weight=1;
> server 172.22.1.83:9849 weight=1;
> server 172.22.1.84:9849 weight=1;
> }
> server {
> listen 9848 ; # grpc方式对外暴露端口
> proxy_connect_timeout 1s;
> proxy_timeout 3s;
> proxy_pass nacos-grpc-9848; # 此处TCP端口转发代理
> }
> server {
> listen 9849 ; # grpc方式对外暴露端口
> proxy_connect_timeout 1s;
> proxy_timeout 3s;
> proxy_pass nacos-grpc-9849; # 此处TCP端口转发代理
> }
> 
> }
> 
> ## 失败 ：om.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

请问你解决了吗？我也是跟你一样的错误

**Comment by zzx769394358** [comment]
nacos2.0集群+nginx解决方案：
https://github.com/alibaba/nacos/issues/7556

**Comment by freemankevin** [comment]
it's work.
```shell
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  4096;
    multi_accept on;
    use epoll;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    keepalive_requests 100;

    # Buffer size settings
    client_header_buffer_size 1k;
    large_client_header_buffers 4 4k;
    client_body_buffer_size  128k;

    # Timeouts
    client_body_timeout 12;
    client_header_timeout 12;
    send_timeout 10;

    # Gzip Settings
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;


    # Upstream configuration for Nacos cluster
    upstream nacos {
        server nacos1:8848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos2:18848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos3:28848 weight=1 max_fails=2 fail_timeout=5s;
        keepalive 32; # Keep a pool of connections open to each upstream
    }


    # HTTP Server
    server {
        listen       8848;
        listen  [::]:8848;
        server_name  localhost;

        ignore_invalid_headers off;
        client_max_body_size 0;
        proxy_buffering off;
        proxy_request_buffering off;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 300;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            chunked_transfer_encoding off;
            proxy_pass http://nacos;
        }
    }
    
}

stream {
    upstream nacos-grpc {
        server nacos1:9848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos2:19848 weight=1 max_fails=2 fail_timeout=5s;
        server nacos3:29848 weight=1 max_fails=2 fail_timeout=5s;
    }

    server {
        listen 9848;
        listen [::]:9848;

        proxy_connect_timeout 1s;
        proxy_timeout 3s;
        proxy_pass nacos-grpc;
    }
}
```
