### ISSUE TITLE
nacos  + dubbo 在实例注册成功后会有几秒的时间调用不到提供者

### ISSUE THREAD

**Issue by ZhangShaoWu** [alibaba/nacos#5270]
您好！
   我们这边用的是spring-cloud-alibaba ，在项目上线的时候服务在启动的过程中发现服务启动了，nacos也注册上去了，会有消费者还是没有办法调用到提供者的情况。

1，这个时间点是实例注册到nacos中的时间

![3d3f638c32f73ea7bbce80cc0d3c12e7](https://user-images.githubusercontent.com/19930444/113389419-9359b380-93c2-11eb-9063-23925380e9ca.png)

2，这个时间是dubbo初始化完成的时间
![图二](https://user-images.githubusercontent.com/19930444/113389443-a1a7cf80-93c2-11eb-8741-dc56182a0780.png)

在图一的这个时间nacos已经注册了，那么nacos会将用户的流量分配到注册的机器，但是这个时候dubbo的初始化还没有完成，消费者调用这个提供者的时候就会出现找不到提供者异常，只有在dubbo初始化完成之后才能调用成功，请问下这个问题有成熟的解决方案吗？

**Comment by horizonzy** [comment]
能否提供一个稳定复现的demo。上传到你的github仓库中，我会看一下这个问题。

**Comment by KomachiSion** [comment]
其实从描述上看，这并非是nacos的问题，是spring加载启动顺序和注册顺序的问题。需要转移issue到应用框架上修复。
