### ISSUE TITLE
Shall we have a plan to support some other external dbs like pg in config?

### ISSUE THREAD

**Issue by rodbate** [alibaba/nacos#5271]
**Is your feature request related to a problem? Please describe.**
 + Support some other external dbs like pg in the config

**Describe the solution you'd like**
+ Add new DataSource
+ Refactor external storage persist services and do extensions
+ Add new db and tables schema to adjust new db

**Describe alternatives you've considered**

**Additional context**

**Comment by JackSun-Developer** [comment]
Nacos now support mysql and Derby, but is open for other db implementation, in detail, nacos provides an interface named "PersistService", you can implement it for your pg database support.

**Comment by KomachiSion** [comment]
see branch feature_multiple_datasource_support
