### ISSUE TITLE
nacos 2.0.0 jraft 选主失败导致服务不可用 是否可以让读请求继续可用？

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#5272]
注意到升级到2.0.0版本之后很多用户都提到
**code:503,msg:server is DOWN now, please try again later!**
这一问题，按照nacos文档给的解决方案
![image](https://user-images.githubusercontent.com/53824889/113406602-56031f00-93de-11eb-86ba-4e40cf7839c6.png)
我理解这只是一个临时的解决方案对吧？
jraft 所使用的 data/protocol/raft/ 目录下面的各snapshot 里面的存储的是旧的host信息，扩缩容导致新的集群信息跟这里的旧的host信息冲突就很有可能导致选主失败，这个我使用**2.0.0-bugfix**版本可以稳定复现。
我觉得扩缩容或者机器替换、ip变动应该是个很常见的场景吧？所以请问：

1. 这个地方是否有后续的优化计划？
2. 选主失败的情况下，是否应该让读操作可用，而不是任何读请求都被拦截然后返回503错误？举个例子，我们仅使用注册中心功能，且仅注册临时服务，只需要distro协议进行同步，这种情况下可不可以即使选主失败，依然让nacos节点工作，只是输出ERROR信息？这样跟出现选主失败然后节点直接503的情况比起来，在生产环境是否影响面小一点？

感谢解答！

**Comment by JackSun-Developer** [comment]
@ i will fix it@

**Comment by MajorHe1** [comment]
> @ i will fix it@

请问fix 这个问题的时候是否考虑我说的问题2，即选主失败的情况下依然让distro协议相关的临时服务读写可用呢？

**Comment by KomachiSion** [comment]
1、 优化计划一定是有的，逐渐将使用jraft变得更正确
2、 这个问题不是nacos的，而是所有raft协议都存在的。除非更换协议，否则解决不掉。

**Comment by KomachiSion** [comment]
关于第二点 补充一下当时的设计原因：

服务在启动时，会通过两种协议初始化持久化服务和非持久化服务的数据。 当初始化数据完成后，服务端才能够提供服务，否则客户端可能读取到空数据或者错误数据导致运行时故障。只是加入了jraft之后，选主严格容易出现这个问题，需要优化，根据不同协议走不同逻辑，也需要给出更合理的提示。

**Comment by MajorHe1** [comment]
> 关于第二点 补充一下当时的设计原因：
> 
> 服务在启动时，会通过两种协议初始化持久化服务和非持久化服务的数据。 当初始化数据完成后，服务端才能够提供服务，否则客户端可能读取到空数据或者错误数据导致运行时故障。只是加入了jraft之后，选主严格容易出现这个问题，需要优化，根据不同协议走不同逻辑，也需要给出更合理的提示。

初始化数据完成后再提供服务没有问题，一个小小的建议是在运行期间万一由于扩缩容导致jraft选主失败，可不可以让distro协议负责的非持久化数据依然可读可写？正如采访稿中说的， 外面业界的主流场景都是非持久化服务，您觉得让jraft不要影响distro的想法合理吗？

**Comment by JackSun-Developer** [comment]
@MajorHe1  jRaft的选主失败，确实不应该影响distro协议的可读性，设计成两者分离，让jRaft挂掉之后，Distro依然可用，是正确的思路，但这个修复需要一些时间。
目前我先提交一个暂时的方案吧，把jRaft出现的详细报错信息提供给用户，而不是只是说server is down
