### ISSUE TITLE
请问怎么更新配置文件中的某一行内容

### ISSUE THREAD

**Issue by tianbao54** [alibaba/nacos#5278]
**Is your feature request related to a problem? Please describe.**
我使用： curl -X POST "http://x.x.x.x:8848/nacos/v1/cs/configs" -d "dataId=gateway.properties&group=DEFAULT_GROUP&&tenant=86ee1b5c-5c61-47b4-a95c-5c74cfa90c8c&content=spring.cloud.gateway.routes[5].uri=115.152.175.199"
希望仅更新 spring.cloud.gateway.routes[5].uri 这一行内容， 但似乎会把 gateway.properties 所有内容都冲掉

请问有办法只更新某一行的内容吗？

**Comment by JackSun-Developer** [comment]
目前只能全部更改。。只更新一行，可以考虑自己写个程序，先对该配置进行查询，查询结果中添加一行，然后再把添加后的全文post上去。

**Comment by tianbao54** [comment]
> 目前只能全部更改。。只更新一行，可以考虑自己写个程序，先对该配置进行查询，查询结果中添加一行，然后再把添加后的全文post上去。

好的， 谢谢。

**Comment by KomachiSion** [comment]
没有，配置文件内容对nacos来说是一个整体，不会去感知内容中某一个key是什么。
