### ISSUE TITLE
consistency模块缺失entity目录（The consistency module is missing the entity directory ）

### ISSUE THREAD

**Issue by RGaius** [alibaba/nacos#5279]
**Describe the bug**
consistency模块缺失entity目录以及对应java文件
The consistency module is missing the entity directory and the corresponding java file

![image](https://user-images.githubusercontent.com/19511826/113650858-85a67580-96c3-11eb-9b7b-a36ec5f2d37e.png)

**Expected behavior**

**Acutally behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by JackSun-Developer** [comment]
entity模块是grpc自动生成的代码，需要mvn clean install -Dmaven.test.skip=true之后才能出现。

**Comment by lualeslie** [comment]
> entity模块是grpc自动生成的代码，需要mvn clean install -Dmaven.test.skip=true之后才能出现。

您好，我试了一下这个命令，build success了，但是entity还是没有出现，这是为什么？

**Comment by haoyann** [comment]
@lualeslie 
命令：`mvn compile install -Dmaven.test.skip=true`
文档: https://nacos.io/zh-cn/docs/faq.html#3.19
