### ISSUE TITLE
服务注册到nacos,不加webmvc依赖不能注册。

### ISSUE THREAD

**Issue by leikun3163** [alibaba/nacos#5284]
服务发现依赖:
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-alibaba-nacos-discovery</artifactId>
        </dependency>
不加
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
不能进行注册

**Comment by JackSun-Developer** [comment]
I can't get the meaning of the problem.

**Comment by leikun3163** [comment]
> I can't get the meaning of the problem.

我想知道为什么要加这个依赖

**Comment by JackSun-Developer** [comment]
> > I can't get the meaning of the problem.
> 
> 我想知道为什么要加这个依赖

因为这个依赖是Springboot提供的web服务的基础包，不加就启动不起来web服务。

**Comment by leikun3163** [comment]
> > > I can't get the meaning of the problem.
> > 
> > 
> > 我想知道为什么要加这个依赖
> 
> 因为这个依赖是Springboot提供的web服务的基础包，不加就启动不起来web服务。



> > > I can't get the meaning of the problem.
> > 
> > 
> > 我想知道为什么要加这个依赖
> 
> 因为这个依赖是Springboot提供的web服务的基础包，不加就启动不起来web服务。

嗯嗯，已经调试了源码，web类型有none、servlet、reactive，不加web基础包就是none、加了就是servlet，createApplicationContext：AnnotationConfigServletWebServerApplicationContext.class
