### ISSUE TITLE
nacos的服务名默认都是小写的，如果使用restTemplate调用的话，原来eureka大写的就找不到服务了

### ISSUE THREAD

**Issue by vic-miao** [alibaba/nacos#5285]
从eureka迁移到nacos，发现nacos的服务名默认都是小写的，还没有提供修改的配置项。如果使用restTemplate调用的话，原来eureka大写的就找不到服务了，就不能像euerka一样大小写都支持吗？搞的所有使用服务名的地方都得修改一下，在迁移过程中两种注册中心都存在的情况那就糟糕了

**Comment by JackSun-Developer** [comment]
> nacos的服务名默认都是小写的

这句话有误，nacos是区分大小写的，你提交时用的服务名是大写，nacos就存储为大写；是小写，nacos就存储为小写。

> 原来eureka大写的就找不到服务了，就不能像euerka一样大小写都支持吗

另外，这句话也有误，eureka貌似会把所有的服务名转化为大写，这个是eureka的设计。

如果需要在eureka两者兼容的话，建议在nacos注册服务时，自己设置为大小写。
