### ISSUE TITLE
nacos auth

### ISSUE THREAD

**Issue by erioe-m** [alibaba/nacos#5286]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos开启鉴权之后拿不到配置

### How to reproduce it (as minimally and precisely as possible)

1. console 模块 application.properties 中的 nacos.core.auth.enabled=true
2.  client端配置:
nacos.config.server-addr=127.0.0.1:8849
nacos.config.namespace=f2a3a19b-7fa5-4d67-832c-39e26dd63209
nacos.config.username=nacos
nacos.config.password=abc123

### Tell us your environment
nacos 1.4.1

**Comment by erioe-m** [comment]
springboot 2.4.4
      client版本 
      <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.1</version>
        </dependency>

**Comment by JackSun-Developer** [comment]
鉴权的使用方法详见：https://nacos.io/zh-cn/docs/auth.html

**Comment by erioe-m** [comment]
我自己debug弄好了，版本问题，这文档我早看过了，对我的问题没帮助
