### ISSUE TITLE
服务注册问题

### ISSUE THREAD

**Issue by dzh6699** [alibaba/nacos#5287]
**Describe the bug**
此服务在服务器能正常注册，本地无法注册，本地有几个服务可以注册，有几个不可以。
![image](https://user-images.githubusercontent.com/29142176/113808160-ff0f9800-9797-11eb-8f9b-76c661fe9cc3.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by JackSun-Developer** [comment]
>在服务器能正常注册

服务器能正常注册是什么意思？用控制台吗？

>本地无法注册

本地无法注册又是什么意思？用nacos-client吗？

以及你使用的是nacos哪个版本？

**Comment by dzh6699** [comment]
nacos版本 1.4.1
意思是有A、B两个服务
A在服务器启动，可以注册到nacos，在我本地启动无法注册
B服务在服务器能注册成功，本地也能注册成功。
目前A就如图所示，显示的instanceId为null

**Comment by dzh6699** [comment]
> > 在服务器能正常注册
> 
> 服务器能正常注册是什么意思？用控制台吗？
> 
> > 本地无法注册
> 
> 本地无法注册又是什么意思？用nacos-client吗？
> 
> 以及你使用的是nacos哪个版本？

nacos版本 1.4.1
意思是有A、B两个服务
A在服务器启动，可以注册到nacos，在我本地启动无法注册
B服务在服务器能注册成功，本地也能注册成功。
目前A就如图所示，显示的instanceId为null

**Comment by KomachiSion** [comment]
没有注册成功是控制台看不到吗？ 还是你自己没有读到？

instanceId为null是正常的，说明你没有设置id

**Comment by dzh6699** [comment]
没有注册成功，今晚重启一下服务器上的nacos再试试看




周杰伦说
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 服务注册问题 (#5287)





 
没有注册成功是控制台看不到吗？ 还是你自己没有读到？
 
instanceId为null是正常的，说明你没有设置id

**Comment by dzh6699** [comment]
> 没有注册成功是控制台看不到吗？ 还是你自己没有读到？
> 
> instanceId为null是正常的，说明你没有设置id

已恢复
