### ISSUE TITLE
[NA] notify error for service异常

### ISSUE THREAD

**Issue by YorkHwang** [alibaba/nacos#5292]
https://github.com/alibaba/nacos/blob/2ded5a24fc68a733df7620211f76a3958914ba05/client/src/main/java/com/alibaba/nacos/client/naming/core/EventDispatcher.java#L175

nacos client 服务重启时这里 报错：
java.util.ConcurrentModificationException: null

原因：
nacos在服务启动时，向listeners添加listener，此时异步线程执行Notifier任务，迭代listeners， 导致报错。
listeners 是一个 Collections.synchronizedList(new ArrayList<EventListener>()) ，建议修改成  new CopyOnWriteArrayList<>()

**Comment by JackSun-Developer** [comment]
您这份代码的版本是？

**Comment by KomachiSion** [comment]
EventDispatcher.java 已废弃， 1.4.1版本更换了实现，应该不会出现了。
