### ISSUE TITLE
Some thoughts about Service Discovery Open API

### ISSUE THREAD

**Issue by spacewander** [alibaba/nacos#5296]
**Is your feature request related to a problem? Please describe.**

Currently, the `list instance` API only supports listing an instance of a given service. If you have 1000 services, you need to call it 1000 times. The complexity is O(n), which makes scale really hard. What's worse, there is not `watch` operation in Open API. So to ensure the instance list up-to-date, you need to call it repeatedly in a short time.

**Describe the solution you'd like**

1. It would be better to allow querying instances from several services in a single call, like POST a list of service names, and then get a map of service-instances.
2. We can use HTTP long poll to watch the instance change. Another configuration server, [Apollo](https://github.com/ctripcorp/apollo), supports the watch operation in this way. By using pure HTTP, there is no need to introduce an additional UDP connection.

**Comment by JackSun-Developer** [comment]
there is not watch operation in Open API. So

**Comment by spacewander** [comment]
> If you implement such an API to query a batch of 1000 services, you should also loop 1000 times in your function, the complexity is also O(n).

Executing a loop in a function locally doesn't have the same cost as an HTTP request.
It is quite trivial.

> A better choose is subscribe such 1000 services, and there changes will be push to your client on time.
> This is already supported, see "subscribe" API in nacos.

There is not "subscribe" **in the Open API**. Please read my post carefully. It is quite easy to confirm by using Ctrl+F on this page: https://nacos.io/en-us/docs/open-api.html

As for the "subscribe" in the Java SDK, it is actually an HTTP poll at intervals (not HTTP long poll!) plus UDP push (not so reliable).

By switching to HTTP long poll, we can save many network operations and per-service threads.

**Comment by KomachiSion** [comment]
query 1000 service by http maybe cause your http package larger than http limit. And you will block or error in your application.

If you query 1000 times one by one. it is only slow.

For the subscribe, you can try to use 2.0. It will used grpc stream to push subscribe data. Not poll~

**Comment by spacewander** [comment]
Where is the doc from the gRPC way?

**Comment by KomachiSion** [comment]
upgrade to 2.0 for server and client。 Same usage with 1.X version。

https://nacos.io/en-us/docs/2.0.0-compatibility.html

**Comment by spacewander** [comment]
> Compared with 1.X, Nacos2.0 adds gRPC communication mode

So where is the doc for "gRPC communication mode", and how can we use it in the Open API?

**Comment by spacewander** [comment]
If we want to use gRPC in the Open API, at least we need to see the `.proto` file.

For example, skywalking defines its protocol like this: https://skywalking.apache.org/docs/main/latest/en/protocols/trace-data-protocol-v3/ and https://github.com/apache/skywalking-data-collect-protocol.

Another example from Envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#envoy-v3-api-msg-config-rbac-v3-rbac and https://github.com/envoyproxy/envoy/blob/4ecf3f7efed97529dc064223f3697a8d4d1101b9/api/envoy/config/rbac/v3/rbac.proto#L72

**Comment by KomachiSion** [comment]
So you only want to use openAPI rather than client? If so, there is only way to get services and get one by one.
