### ISSUE TITLE
nacos是否能提供一个入口，对获取的配置进行预处理，如对密码的加密解密

### ISSUE THREAD

**Issue by zhenlanzhuang** [alibaba/nacos#5298]
nacos是否能提供一个入口，对获取的配置进行预处理，或者有什么手段对springboot加载配置之前，获取配置，对配置进行预处理之后，再加载至内存里

**Comment by JackSun-Developer** [comment]
配置加解密功能正在开发中

**Comment by zhenlanzhuang** [comment]
计划在哪个版本release吗

**Comment by zhenlanzhuang** [comment]
> 配置加解密功能正在开发中

有计划在哪个版本release出来吗？

**Comment by KomachiSion** [comment]
duplicate with #5367

**Comment by Byhuang1998** [comment]
> nacos是否能提供一个入口，对获取的配置进行预处理，或者有什么手段对springboot加载配置之前，获取配置，对配置进行预处理之后，再加载至内存里

这个功能目前有了吗？
