### ISSUE TITLE
支持 spring xml 注入配置吗？

### ISSUE THREAD

**Issue by ChenAt** [alibaba/nacos#530]
传统的 spring 项目，xml 文件里的 bean 的属性配置能从 nacos 加载吗？
我们之前用的 disconf 是可以支持的，不知道 nacos 是否支持?

**Comment by hxy1991** [comment]
> 貌似没有写进文档，不过看到个例子。
> https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-example/nacos-spring-config-datasource-example

支持的。关于这例子详细的文章可以参看：https://mp.weixin.qq.com/s/xV2X0FQNerEpCuT7irPVeQ
