### ISSUE TITLE
当nacos集群的某一个pod所在的k8s node节点异常宕机，然后节点恢复后，nacos集群中会多出一个异常节点

### ISSUE THREAD

**Issue by AllenJol** [alibaba/nacos#5302]
As follows：
![image](https://user-images.githubusercontent.com/28972707/113964444-1913ae00-985e-11eb-80c1-6549c7566498.png)

my nacos is cluster mode，and when i have a node down and then restore，then nacos cluster have a Exceptional cluster node

**Comment by AllenJol** [comment]
nacos version is 1.4.1

**Comment by JackSun-Developer** [comment]
各个节点上的cluster.conf配置、节点元数据，以及alipay-raft.log可以提供一下么

**Comment by KomachiSion** [comment]
你的k8s设置可能有问题，恢复后hostname变了， 导致nacos读取到的hostname不在配置的cluster.conf里 就会尝试添加进去。

还是排查k8s的环境问题把

**Comment by AllenJol** [comment]
谢谢 JackSun,我发现这个问题是 我k8s中node节点宕机后，nacos某一个pod在这个宕机的节点上，节点恢复后，nacos就出现了这么一个问题了。我怀疑是和我集群环境中设置的  pod反亲和性、节点亲和性和污点有关系。
