### ISSUE TITLE
about namespace's config max limit

### ISSUE THREAD

**Issue by erioe-m** [alibaba/nacos#5303]
![image](https://user-images.githubusercontent.com/42257376/113965270-a4417380-985f-11eb-9ea3-5011968c3daf.png)

1. The maximum number of configurations is 200,What was the design for at that time?
2. How to break through the limitation?
3. What is the impact of breaking through the restrictions？

**Comment by JackSun-Developer** [comment]
The 200 is not the liminition number of configurations, the liminition number of configurations is infinite, as long as your DB supports.

**Comment by erioe-m** [comment]
![image](https://user-images.githubusercontent.com/42257376/113975301-dfe53900-9871-11eb-9f55-78545105bab1.png)


You're right. I've tried. It can exceed 200. What's the meaning of 200？

**Comment by JackSun-Developer** [comment]
No meaning, ...seems a redundant tag

**Comment by erioe-m** [comment]
Ah! I see.. Is there any plan optimization? Beginners will misunderstand it like me
