### ISSUE TITLE
namespace detail display bug

### ISSUE THREAD

**Issue by erioe-m** [alibaba/nacos#5304]
**Describe the bug**
nacos-server1.4.1,namespace detail display ambiguity,  It can exceed 200
![image](https://user-images.githubusercontent.com/42257376/113978079-11600380-9876-11eb-925d-0734f52330c5.png)

**Expected behavior**
only the number of configurations is shown here

**Comment by JackSun-Developer** [comment]
我跟这一块代码的作者确认了一下，这个200是容量限制，开启的方法是把setCapacityLimitCheck环境变量设置为true，而并不是显示错误（抱歉，在另一个ISSUE里回答错了）

**Comment by shiyiyue1102** [comment]
the second number 200 is the max limit capacity of config in this namespace ,but the capacity management function is not open default  , you can set env param "isCapacityLimitCheck=true " to open it and try it again ,refer to this method for detail com.alibaba.nacos.config.server.utils.PropertyUtil#setCapacityLimitCheck

**Comment by erioe-m** [comment]
ok, I see, thanks
