### ISSUE TITLE
如何配置支持达梦数据库？

### ISSUE THREAD

**Issue by liujiajing** [alibaba/nacos#5306]
如何配置支持达梦数据库？有这样的功能么

**Comment by KomachiSion** [comment]
社区正式版本暂时只支持mysql和derby数据库。
分支`feature_muiltple_datasource`暂时能够通过jpa支持oracle， pg等常用数据库。

其他数据库目前需要自行修改源码。

后续版本可能会支持多数据库类型插件。

**Comment by xrwang8** [comment]
feature_muiltple_datasource 这个版本可以用k8s部署吗

**Comment by dylan-tao** [comment]
> 如何配置支持达梦数据库？有这样的功能么

nacosplus针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
