### ISSUE TITLE
C++的NACOS支持或者提供一个负载均衡的C++算法

### ISSUE THREAD

**Issue by SBFVYGA** [alibaba/nacos#531]
希望能更快支持C++语言，项目中部分Java提供的服务已经改造完毕，但是C++的服务目前是使用http注册一个服务，然后五秒提交一次心跳数据去维持健康状态。但是获取可用健康服务（这里指的是Java SDK中的selectOneHealthyInstance方法），这里计算的负载均衡算法是在客户端实现的，并非像Nginx负载均衡的实现方式。所以C++想要获取一个负载均衡的实例需要由java去算出来，再返回给C++。

**Comment by hxy1991** [comment]
有哪个 CPP 大牛贡献一个吗？😁

**Comment by xuechaos** [comment]
@SBFVYGA 默认的负载均衡算法是随机，selectOneHealthyInstance中增加了权重的配比，根据加权进行随机选取，可以通过C++来直接请求Http，实现这部分内容。
目前C++这块还是空白，我们努力尽快推动，如果可以，也欢迎一起过来共建实现这一块。

**Comment by jiangminbing** [comment]
selectOneHealthyInstance 有没有提供多种算法可供配置，默认是根据权重随机算法，有没有提供轮询，最小负载，最小响应时间等方式可供配置？

**Comment by nkorange** [comment]
> selectOneHealthyInstance 有没有提供多种算法可供配置，默认是根据权重随机算法，有没有提供轮询，最小负载，最小响应时间等方式可供配置？

 目前没有，需要客户端自己实现。

**Comment by jiangminbing** [comment]
selectOneHealthyInstance 在获取统一分组，不同服务的时候居然查到自己注册的服务！！不知是否有这样的bug，当把自己注册的服务下线后就没有这样的情况。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
> 希望能更快支持C++语言，项目中部分Java提供的服务已经改造完毕，但是C++的服务目前是使用http注册一个服务，然后五秒提交一次心跳数据去维持健康状态。但是获取可用健康服务（这里指的是Java SDK中的selectOneHealthyInstance方法），这里计算的负载均衡算法是在客户端实现的，并非像Nginx负载均衡的实现方式。所以C++想要获取一个负载均衡的实例需要由java去算出来，再返回给C++。

请问你们的C++是通过第三方库进行http的，还是自己实现了http的部分功能（例如用read和write系统调用）

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
希望有人能一起來提交代碼：
https://github.com/TTTTTAAAAAKKKKEEEENNNN/nacos-cpp-cli

目前大部分功能已經實現
