### ISSUE TITLE
nacos2.0.0 serious bug:can not register service without any error;node be‘server is DOWN now, please try again later!’frequentlly

### ISSUE THREAD

**Issue by zzps** [alibaba/nacos#5314]
nacos2.0.0 在服务端和客户端都是2.0.0情况下，获取配置正常，客户端向服务端注册服务时没有报错，但是在控制台上看不到服务列表，通过openapi也获取不到，而且openapi请求时频繁看到节点报server is DOWN now, please try again later!

相关日志搜集：
nacos.log:java.lang.IllegalStateException: old raft protocol already stop
	at com.alibaba.nacos.naming.controllers.RaftController.vote(RaftController.java:97)

还有很多其他的日志有报错不一一列举了

**Comment by KomachiSion** [comment]
并非bug， 而是当前服务发现的集群状态初始化有问题。配置获取正常是因为配置不需要使用jraft。而服务发现有可能使用，jraft初始化失败的时候不能提供服务，以免出现数据错误问题。

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/2.0.0-compatibility.html

FAQ `Error code:503,msg:server is DOWN now, please try again later! during using.`

**Comment by zzps** [comment]
> 
> 
> 并非bug， 而是当前服务发现的集群状态初始化有问题。配置获取正常是因为配置不需要使用jraft。而服务发现有可能使用，jraft初始化失败的时候不能提供服务，以免出现数据错误问题。

我不认为这不是bug，我是从1.4.0版本切换过来，切换到2.0版本后本地使用单例注册服务的时候可以看到服务，但是部署成集群环境后注册服务就不行，即使集群各节点正常也无法注册，而且客户端不报错。节点经常性因为raft挂掉是另一个同时发现的问题
