### ISSUE TITLE
2.0 集群节点列表信息有个问题想请教一下

### ISSUE THREAD

**Issue by lovemianhuatang** [alibaba/nacos#5315]
[https://github.com/nacos-group/nacos-docker/issues/175](url)

请问这个mate信息正常吗？
我是3台电脑，各有一个nacos服务。启动方式是使用docker stack deploy.

三个节点的naming_persistent_service 的 leader都是nacos1:7848

三个节点的其他mate 的 leader都是nacos2:7848

{ "lastRefreshTime": 1617892880057, "raftMetaData": { "metaDataMap": { "naming_instance_metadata": { "leader": "nacos2:7848", "raftGroupMember": [ "nacos3:7848", "nacos1:7848", "nacos2:7848" ], "term": 1 }, "naming_persistent_service": { "leader": "nacos1:7848", "raftGroupMember": [ "nacos3:7848", "nacos1:7848", "nacos2:7848" ], "term": 1 }, "naming_persistent_service_v2": { "leader": "nacos2:7848", "raftGroupMember": [ "nacos3:7848", "nacos1:7848", "nacos2:7848" ], "term": 1 }, "naming_service_metadata": { "leader": "nacos2:7848", "raftGroupMember": [ "nacos3:7848", "nacos1:7848", "nacos2:7848" ], "term": 1 } } }, "raftPort": "7848", "readyToUpgrade": true, "version": "2.0.0" }

![image](https://user-images.githubusercontent.com/41498415/114123177-62c6cc00-9924-11eb-8e22-b3b111203598.png)
![image](https://user-images.githubusercontent.com/41498415/114123199-6c503400-9924-11eb-89a0-c9088ded8546.png)

![image](https://user-images.githubusercontent.com/41498415/114123217-740fd880-9924-11eb-9707-c8f4a2717892.png)

**Comment by JackSun-Developer** [comment]
正常，naming_persistent_service和naming_instance_metadata是两个分离的group（参考SofajRaft协议的gorup概念），两个group分开选主，工作方式不会相互影响。

**Comment by lovemianhuatang** [comment]
好的，谢谢。
