### ISSUE TITLE
Nacos1.4.0版本回滚配置之后，类型丢失了

### ISSUE THREAD

**Issue by 985391294** [alibaba/nacos#5318]
![nacos1](https://user-images.githubusercontent.com/57293296/114135282-9f51f200-993b-11eb-9e0d-fc923b9ec23a.png)
![nacos2](https://user-images.githubusercontent.com/57293296/114135284-a0831f00-993b-11eb-9ce4-f5f1302de5f0.png)
![nacos3](https://user-images.githubusercontent.com/57293296/114135285-a11bb580-993b-11eb-92be-2e2985e8573b.png)
![nacos4](https://user-images.githubusercontent.com/57293296/114135286-a1b44c00-993b-11eb-8078-f773eaad9e18.png)
![nacos-mysql](https://user-images.githubusercontent.com/57293296/114135417-c8728280-993b-11eb-9e31-8b324af79ed1.png)
持久化策略使用的是mysql存储，更改完之后发现config_info表里面的type字段丢失了。

**Comment by haoyann** [comment]
我在develop分支没有复现，应该是修复了。

**Comment by 985391294** [comment]
您那边能提供一下是在哪个版本修复的吗？我这边好升级一下对应的版本

**Comment by KomachiSion** [comment]
@985391294 可以先clone develop分支，然后打包先试用下。

**Comment by KomachiSion** [comment]
Community can't reproduce in develop branch, and user has no response. Close first
