### ISSUE TITLE
How to get current service health status?

### ISSUE THREAD

**Issue by Jackjun724** [alibaba/nacos#5320]
问题：
最近出现了未知的客户端掉线的问题，服务端与客户端都是K8S集群内的服务，我们现在想获取服务当前的健康状态，用来配合K8S健康检查机制进行自动重启，但是没有找到相关源码，请问有什么公开方法是可以获取当前服务的健康状态的吗？

English version problem:
Recently, there has been an unknown client disconnection problem. Both the server and the client are services in the K8S cluster. We now want to obtain the current health status of the service, which can be used to automatically restart in conjunction with the K8S health check mechanism, but the relevant source code has not been found. Is there any disclosure method that can obtain the health status of the current service?

**Comment by 1019822077** [comment]
如果是nacos集群部署，发现此问题的时候，可以去看看集群元数据中的leader是否都一样，如果不一样，那说明是脑裂了。

**Comment by KomachiSion** [comment]
问题不是很明白
1. 客户端掉线是什么意思？ 是说业务服务启动着，但是从nacos控制台上已经不见了？还是nacos的服务端挂掉了？
2. 你要探测的服务是业务服务还是nacos服务？
3. 有什么日志信息吗？

**Comment by KomachiSion** [comment]
The problem is not clear and no more response from author.

**Comment by Jackjun724** [comment]
问题已解决，应用启动时在nacos还未启动就去调用了其他服务导致报错，nacos注册失败，我想问的是能不能获取当前服务的健康状态，即当前服务在Nacos注册中心的状态，Up 或者 Down，然后开放接口配合K8s的探针进行重启
