### ISSUE TITLE
Nacos2.0 最新分支 consistency 下 entity 包缺失

### ISSUE THREAD

**Issue by langteng** [alibaba/nacos#5322]
最新2.0.0 bugfix 分支拉下来编译提示下面 entity 包不存在
import com.alibaba.nacos.consistency.entity.ReadRequest;
import com.alibaba.nacos.consistency.entity.Response;
import com.alibaba.nacos.consistency.entity.WriteRequest;

**Comment by haoyann** [comment]
编译一下：`mvn clean compile`

**Comment by gary-liu** [comment]
他的文件在proto包下面，这里面的文件是protobuf文件，他里面有一个protobuf编译插件 用那个插件编译一下protobuf:compile,在target里面就可能找到相关的文件

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/2.0.0-compatibility.html FAQ

**Comment by JackSun-Developer** [comment]
Please use mvn -Dmaven.test.skip=true clean install to compile, then the entity package will come into being.
