### ISSUE TITLE
nacos k8s 部署内存一直上升

### ISSUE THREAD

**Issue by bestpayAmes** [alibaba/nacos#5337]
nacos 1.4.1 k8s集群部署，内存一直缓慢上升，Xmx配了2g,整个pod内存占用能达到5g,这个是什么原因？

**Comment by KomachiSion** [comment]
不知道，肯定不是nacos的原因。 应该是k8s的bug， 内存没有limit住。

**Comment by bestpayAmes** [comment]
没限制最大内存，如果限制了，这样一直上升，到了限制的值，就被杀掉了，我看jvm里面是正常的，但是整个pod内存就是会一直上升。好奇怪

**Comment by XiaoFei200320** [comment]
后面有解决吗？怎么解决的呢，我用docker启动的，内存也是一直在上升
