### ISSUE TITLE
增加对postgresql数据库的支持

### ISSUE THREAD

**Issue by qdlake** [alibaba/nacos#534]
**Is your feature request related to a problem? Please describe.**
仅使用postgresql数据库，仅仅为了存储Nacos的配置信息，而再加入mysql数据库。

**Describe the solution you'd like**
修改需涉及跟涉及跟数据源及CRUD操作相关的类，并增加nacos-postgres.sql数据库脚本。

**思路1**：直接修改BasicDataSourceServiceImpl，根据url，自动判断是mysql或postgresql数据库；

**思路2**：增加一个新类，实现DataSourceService接口；并修改DynamicDataSource的getDataSource方法。

都需要涉及sql的兼容性修改、测试。

建议：
1、postgresql没有read-only模式，checkMasterWritable直接返回true；

2、postgresql10之后，直接支持generated by default as identity类型，暂时只支持10之后的版本；

3、derby数据库的schema.sql比nacos-mysql.sql多了几张app打头的表，暂时还不知道这几张表的作用？

4、将dbcp换成HikariCP或者Druid连接池？

**Describe alternatives you've considered**
是否还需要支持其他数据库，譬如：oracle？

**Additional context**
目前只是初步想法，欢迎大家提出建议。

**Comment by qdlake** [comment]
@TsingLiang @yanlinly @xuechaos 是否还需要增加一个类似于com.alibaba.nacos.naming.healthcheck.MysqlHealthCheckProcessor的健康检测处理器类?

**Comment by TsingLiang** [comment]
Multiple storage will certainly be supported later.
We will discuss it later.

**Comment by DemonJun** [comment]
希望能添加PostgreSQL数据库支持
希望数据库连接池换成HikariCP，该数据库连接池较druid更轻量级；

**Comment by kelvinji2009** [comment]
@TsingLiang Any update after half year?Thanks.

**Comment by qmdx** [comment]
@xuzhenen  建议抽象 DB 层接口方式提供更方便扩展，源码写死 mysql 不可取

**Comment by chuntaojun** [comment]
或许需要维护多种数据库的sql语句（某些sql语句涉及了数据库的方言），目前正在考虑直接将sql拎出代码层，使用mybatis进行多数据库支持

**Comment by qmdx** [comment]
@chuntaojun 抽象一层然后 orm 层可以插件化，默认一种实现可以考虑下 https://github.com/baomidou/mybatis-plus 目前已支持主流数据库适配

**Comment by chuntaojun** [comment]
大家使用的oracle数据库版本是多少

**Comment by Liu-Junlin** [comment]
> 大家使用的oracle数据库版本是多少

普遍10g+吧

**Comment by KingZxx** [comment]
作为微服务得核心基础设施，单纯依赖mysql真的不好，希望能支持更多得数据库

**Comment by dudiao** [comment]
希望支持更多得数据库，或者留出入口自己适配也行

**Comment by Liu-Junlin** [comment]
我的应用目前主要还是使用postgresql，目前为了nacos单独维护了一个mysql库

**Comment by humbinal** [comment]
支持postgresql的建议提了一两年了，很多人因为不支持其他数据库用不起来，postgresql、oracle、sqlserver这几个最流行的还是有必要支持的，不知道社区怎么计划的？

**Comment by vnobo** [comment]
这个是什么时候,去做呢,我觉得spring boot 里面对驱动判断,它自动选择dataSoure类型,这个可以参考.

**Comment by 505831001** [comment]
You are advised to use the MySQL and PostgreSQL databases and use the configuration document.

**Comment by 505831001** [comment]
个人玩转Nacos修改支持MySQL以及PostgreSQL数据源。下载Code/Tags中版本1.3.2和1.4.0等成功。有需要联系哈。

**Comment by 505831001** [comment]
nacos修改默认数据源mysql同时支持postgresql也就这么几步：
0、引入：org.postgresql依赖包；
1、修改：ExternalDataSourceProperties驱动类名JDBC_DRIVER_NAME="org.postgresql.Driver"；
1、或者：environment.getProperty("db.driver")）到配置中；
2、修改：application.properties中db.num，db.url.0，db.user，db.password，或者db.driver等为postgresql；
3、修改：ExternalStoragePaginationHelperImpl类中limit a,b为offset a limit b分页语法；
4、修改：ExternalStoragePersistServiceImpl类中limit a,b为offset a limit b分页语法；
5、数据库postgresql初始化；技巧从mysql导出12张表（文本）再到postgresql导入12张表（文本）；
------ 就这么简单 ------

**Comment by 505831001** [comment]
nacos修改默认数据源mysql到支持postgresql也就这么几步：
1、修改：ExternalDataSourceProperties驱动类名JDBC_DRIVER_NAME="org.postgresql.Driver"；
2、引入：org.postgresql依赖包；
3、修改：application.properties中db.num，db.url.0，db.user，db.password等为postgresql；
4、修改：ExternalStoragePaginationHelperImpl类中limit a,b为offset a limit b分页语法；
4、修改：ExternalStoragePersistServiceImpl类中limit a,b为offset a limit b分页语法；
5、数据库postgresql初始化；技巧从mysql导出12张表（文本）再到postgresql导入12张表（文本）；
------ 就这么简单 ------

**Comment by 505831001** [comment]
下载nacos 1.3.2或者nacos 1.4.1版本修改数据源为PostgreSQL，然后一键打包（mvn -Prelease-nacos -DskipTests clean install -U），再覆盖容器nacos-server.jar，通过k8s集群模板部署（nacos-0.1.2.tgz），由于修改过后的容器会被重置，只能docker restart nacos，然后将运行镜像打镜像包。欢迎评论……

**Comment by 505831001** [comment]
3452352345234523452345

**Comment by lhaixiong** [comment]
> 下载nacos 1.3.2或者nacos 1.4.1版本修改数据源为PostgreSQL，然后一键打包（mvn -Prelease-nacos -DskipTests clean install -U），再覆盖容器nacos-server.jar，通过k8s集群模板部署（nacos-0.1.2.tgz），由于修改过后的容器会被重置，只能docker restart nacos，然后将运行镜像打镜像包。欢迎评论……

大佬求分享博文 @505831001

**Comment by LeeJEric** [comment]
有打算支持postgreSQL吗?

**Comment by duhongx** [comment]
支持postgreSQL有计划么？

**Comment by dylan-tao** [comment]
> 支持postgreSQL有计划么？

目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb

**Comment by idlesysman** [comment]
玛雅，已经过去8年了

**Comment by royalzzz** [comment]
到底一游，为PG呐喊！

**Comment by royalzzz** [comment]
到此一游，为PG加油助威！🎉
