### ISSUE TITLE
秒级上下线问题

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#5341]
## Issue Description

feature request

### Describe what happened (or what feature you want)

在nacos控制台上下线服务，都会有一定延迟。（我们服务里都默认使用了ribbon）

### Describe what you expected to happen

请问现在是否有成熟的解决方案了？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
使用了ribbon的话就没有办法了， ribbon自己有缓存机制，似乎是每30s刷新一次。
