### ISSUE TITLE
JRaft协议初始化失败导致集群不可用问题纵览

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5343]
## 问题描述

在Nacos社区中，最为常见的ISSUE之一是：JRaft协议初始化经常失败，导致集群中一台或几台机器无法正常工作。该ISSUE将作为所有此类的根ISSUE。

## 二级子ISSUE

Nacos1.4.x中，JRaft协议初始化失败导致集群不可用问题纵览 #5344

Nacos2.0.x中，JRaft协议初始化失败导致集群不可用问题纵览 #5346

## 问题背景

自1.4.1版本、及其后（包括2.0.0），Nacos使用SofaJraft替换了自研的Raft实现。

Jraft的选主比原先自研的Raft更加严格，会记录之前启动时的ip或host。因此重启时如果ip变动了，有可能造成选主失败，从而导致nacos无法正确提供服务。

另外，Nacos中还存在Nacos请求进行处理时，会先用Filter拦截，并判断Distro（AP）协议和jRaft（CP）协议是否都是可用。
如果两者中有任何一个不可用，就会把请求拒绝掉，并报503错误：Server is Down, please try again latter。
这样，CP和AP就严格绑定，每次CP协议挂掉之后，都会导致AP协议也不可用。（该问题在nacos1.4.x和nacos2.0.x中都存在，但修复思路不同，具体内容详见相应二级子ISSUE）
![image](https://user-images.githubusercontent.com/58767027/114399725-d4787180-9bd3-11eb-9df3-13105905e7d0.png)

持续更新中...

**Comment by MajorHe1** [comment]
`Jraft的选主比原先自研的Raft更加严格，会记录之前启动时的ip或host。因此重启时如果ip变动了，有可能造成选主失败，从而导致nacos无法正确提供服务。`

请问关于这一问题的优化计划或者思路是什么呢， data/protocol/raft/ 目录下面的各snapshot 里面的存储的是旧的host信息导致选主失败，这一场景实在是太容易触发了

**Comment by KomachiSion** [comment]
snapshot里不会存储host信息， 存储的应该在metadata里。关于这一点，需要给Sofa Jraft提issue， 优化一下方式以进一步适应云环境。

目前提供的思路是在nacos这一侧，使用host/domain而非ip作为集群节点的标示。

当然这个问题一般在单机测试环境比较容易出现。集群模式下只要满足半数以上存活，理论上不会出现选主失败的问题。

**Comment by MajorHe1** [comment]
> snapshot里不会存储host信息， 存储的应该在metadata里。关于这一点，需要给Sofa Jraft提issue， 优化一下方式以进一步适应云环境。
> 
> 目前提供的思路是在nacos这一侧，使用host/domain而非ip作为集群节点的标示。
> 
> 当然这个问题一般在单机测试环境比较容易出现。集群模式下只要满足半数以上存活，理论上不会出现选主失败的问题。

我把三台节点的集群中的某一台机器压测到full gc，然后再重启该节点，整个集群就选主失败了……
这几天碰到很多次选主失败了，所以很关心这个问题，没有信心直接拿2.0上生产环境

**Comment by kuaile-zc** [comment]
> 
> 
> snapshot里不会存储host信息， 存储的应该在metadata里。关于这一点，需要给Sofa Jraft提issue， 优化一下方式以进一步适应云环境。
> 
> 目前提供的思路是在nacos这一侧，使用host/domain而非ip作为集群节点的标示。
> 
> 当然这个问题一般在单机测试环境比较容易出现。集群模式下只要满足半数以上存活，理论上不会出现选主失败的问题。

那么是否可以这么认为当Sofa Jraft集群存活少于一半就大概率出现选主问题（脑裂等问题）
那么K8s环境下Nacos重启当Pod kill之后在拉起新Pod K8s判定已经健康但是Spring 和 Nacos本身Init需要一段时间
所以在云原生环境下基本上nacos集群重启就会出现脑裂或者集群不同步现象，是否有一些好的建议能解决问题呢？

Is it acceptable to assume that when Sofa Jraft clusters survive less than half, there is a high probability of primary selection problems (brain split, etc.)?  
Then Nacos restarts in K8s environment. After Pod kill, K8s is judged to be healthy after pulling up the new Pod. However, it takes some time for Spring and Nacos to Init  
Therefore, in the cloud native environment, basically when the NACOS cluster is restarted, there will be brain split or cluster out of sync. Are there any good suggestions to solve the problem?

**Comment by CherishCai** [comment]
面对这个 k8s 云环境这种上下线/重启等成员 ip 变动大的情况，常常遇到 issue 里描述的问题；
而 Nacos 还是 AP 用法，所以 CP 不应该作为影响集群整体可用性的拦路虎；
而且 nacos-client 也会不断 beat 补全注册的数据，从而我这边增加了一个重置整个集群选举的入口 resetPeers （用于真的无法选主时的极限运维，总好过集群整体挂掉）

![image](https://user-images.githubusercontent.com/16837364/164158902-6a376963-1383-4549-addc-2ef04fb5ee35.png)

```java

    /**
     * resetPeers. ## nacos-enhance ##.
     * <p>只有在非常紧急并且可用性更为重要的情况下使用：https://www.bookstack.cn/read/sofa-jraft/3.md#6.3%20多数节点故障</p>
     */
    RESET_PEERS(JRaftConstants.RESET_PEERS) {
        @Override
        public RestResult<String> execute(CliService cliService, String groupId, Node node, Map<String, String> args) {
            final Configuration newConf = new Configuration();
            String peers = args.get(JRaftConstants.COMMAND_VALUE);
            for (String peer : peers.split(",")) {
                newConf.addPeer(PeerId.parsePeer(peer.trim()));
            }
            
            final PeerId nodePeerId = node.getNodeId().getPeerId();
            Status status = cliService.resetPeer(groupId, nodePeerId, newConf);
            if (status.isOk()) {
                return RestResultUtils.success();
            }
            return RestResultUtils.failed(status.getErrorMsg());
        }
    };
```

**Comment by CherishCai** [comment]
还写了一段【集群多主检测并自适应调整】代码，实现方式比较 low 不敢随意提交，怕社区大佬们嘲笑～
![image](https://user-images.githubusercontent.com/16837364/164163389-39718dcf-1519-4e5c-8647-f843901c9ffc.png)

**Comment by li-sen** [comment]
在k8s中ip变动不是很正常的事，刚从1.1.x 切到2.0.4 一堆坑，集群在k8s中极其不稳定，集群经常挂，要不就是503了，控制台上看是up状态实际集群是有问题的

**Comment by jefferson-chern** [comment]
@realJackSun  您好，您有钉钉吗？我们是nacos1.4.2版本，用的都是duubo临时实例，没有出现这个问题，可以加钉钉请教一下吗

**Comment by SZMOFEI** [comment]
mark
