### ISSUE TITLE
k8s部署1.4.1Nacos出现节点连接失败

### ISSUE THREAD

**Issue by waidinsamkeit** [alibaba/nacos#5355]
# nacos-Cluster.log
```shell
ERROR failed to report new info to target node : nacos-2.nacos-headless.default.svc.cluster.local:8848, error : caused: Connection refused;
```
![图片](https://user-images.githubusercontent.com/52663349/114504751-ec96d200-9c61-11eb-9704-46c5a6e67e06.png)
# 调用
我用java客户端注册服务的时候,其中某一个节点动不动就会挂掉 只能注册到nacos-0 和nacos-1上面
# Pod内部解析
```shell
nacos-2.nacos-headless.default.svc.cluster.local
内部解析全部是ok的
且所有容器中8848和7848端口可正常通信

**Comment by KomachiSion** [comment]
`Connection refused`

无非就是端口没有监听，比如程序没有正确启动。
或者网络环境不通导致的。

需要排查下环境问题。

**Comment by waidinsamkeit** [comment]
@KomachiSion 环境问题已经检测过了 所有的端口全部都是通着的 所有的IP都可以Ping成功

**Comment by waidinsamkeit** [comment]
@KomachiSion 我在调用的时候服务可以注册到三个Nacos上面 但是Idea给我的反馈只推送道了一个节点上,但是实际上三个服务已经注册到nacos上

**Comment by KomachiSion** [comment]
没有看懂问题。你给的错误是服务端之间的通信异常。但是后续问题又是客户端只发送到一个节点上。

先梳理清楚问题。按照issue模版重新提一个吧。
