### ISSUE TITLE
nacos support add a new file

### ISSUE THREAD

**Issue by purekeeper** [alibaba/nacos#5357]
Does nacos support add a new config file and my service dont't need restart ?

**Comment by JackSun-Developer** [comment]
> Does nacos support add a new config file and my service dont't need restart ?

I can't get the meaning. Nacos does support add a new config, just use **publishConfig** API, and nothing should restart.

**Comment by purekeeper** [comment]
> > Does nacos support add a new config file and my service dont't need restart ?
> 
> I can't get the meaning. Nacos does support add a new config, just use **publishConfig** API, and nothing should restart.
我的service 是gateway 因为想把nacos 配置按照微服务service name 拆分配置，比如servicename1.yaml servicename2.yaml,如果新增一个servie接入到我的gateway 我希望能够直接 在nacos 下创建serivcename3.yaml ,然后我的gateway不用重启直接能够获取到这个新增的service3.yaml 配置，不知道nacos能不能支持

**Comment by luoxiner** [comment]
> 
> 
> > > Does nacos support add a new config file and my service dont't need restart ?
> > 
> > 
> > I can't get the meaning. Nacos does support add a new config, just use **publishConfig** API, and nothing should restart.
> > 我的service 是gateway 因为想把nacos 配置按照微服务service name 拆分配置，比如servicename1.yaml servicename2.yaml,如果新增一个servie接入到我的gateway 我希望能够直接 在nacos 下创建serivcename3.yaml ,然后我的gateway不用重启直接能够获取到这个新增的service3.yaml 配置，不知道nacos能不能支持

支持，使用 getConfig 就可以从server拉取相关的配置

**Comment by purekeeper** [comment]
> > > > Does nacos support add a new config file and my service dont't need restart ?
> > > 
> > > 
> > > I can't get the meaning. Nacos does support add a new config, just use **publishConfig** API, and nothing should restart.
> > > 我的service 是gateway 因为想把nacos 配置按照微服务service name 拆分配置，比如servicename1.yaml servicename2.yaml,如果新增一个servie接入到我的gateway 我希望能够直接 在nacos 下创建serivcename3.yaml ,然后我的gateway不用重启直接能够获取到这个新增的service3.yaml 配置，不知道nacos能不能支持
> 
> 支持，使用 getConfig 就可以从server拉取相关的配置

这个我尝试了   ，但是这个getconfig 只能拉取，后面如果这个新增的yaml文件有变化，怎么样才能进行refresh

**Comment by luoxiner** [comment]
> 
> 
> > > > > Does nacos support add a new config file and my service dont't need restart ?
> > > > 
> > > > 
> > > > I can't get the meaning. Nacos does support add a new config, just use **publishConfig** API, and nothing should restart.
> > > > 我的service 是gateway 因为想把nacos 配置按照微服务service name 拆分配置，比如servicename1.yaml servicename2.yaml,如果新增一个servie接入到我的gateway 我希望能够直接 在nacos 下创建serivcename3.yaml ,然后我的gateway不用重启直接能够获取到这个新增的service3.yaml 配置，不知道nacos能不能支持
> > 
> > 
> > 支持，使用 getConfig 就可以从server拉取相关的配置
> 
> 这个我尝试了 ，但是这个getconfig 只能拉取，后面如果这个新增的yaml文件有变化，怎么样才能进行refresh

你可以使用 addListener api 写一个 listener 在配置变更之后会执行listener对应的方法，详情请看java api 监听配置 相关文档
https://nacos.io/zh-cn/docs/sdk.html

**Comment by luoxiner** [comment]
nacos-example 中也有相关的例子（ConfigExample），你也可以参考一下。

**Comment by purekeeper** [comment]
> > > > Does nacos support add a new config file and my service dont't need restart ?
> > > 
> > > 
> > > I can't get the meaning. Nacos does support add a new config, just use **publishConfig** API, and nothing should restart.
> > > 我的service 是gateway 因为想把nacos 配置按照微服务service name 拆分配置，比如servicename1.yaml servicename2.yaml,如果新增一个servie接入到我的gateway 我希望能够直接 在nacos 下创建serivcename3.yaml ,然后我的gateway不用重启直接能够获取到这个新增的service3.yaml 配置，不知道nacos能不能支持
> 
> 支持，使用 getConfig 就可以从server拉取相关的配置
