### ISSUE TITLE
回滚配置，整个配置直接被删除了

### ISSUE THREAD

**Issue by 985391294** [alibaba/nacos#5358]
1.4.0版本中测试的回滚配置，类型会丢失，这个问题是我前几天才提过的issues，说的是之前可能已经修复过了。详见：[https://github.com/alibaba/nacos/issues/5318](url)。
但是今天下载的2.0.0bugfix版本的，测试回滚之后整个配置直接被删除了。
![nacos1](https://user-images.githubusercontent.com/57293296/114533238-45756300-9c80-11eb-9fbb-1391c13b5f17.png)
![nacos2](https://user-images.githubusercontent.com/57293296/114533245-473f2680-9c80-11eb-9890-ae16c31405b7.png)
![nacos3](https://user-images.githubusercontent.com/57293296/114533248-473f2680-9c80-11eb-9ac5-8b4a7dac4da8.png)
![nacos4](https://user-images.githubusercontent.com/57293296/114533250-47d7bd00-9c80-11eb-9fdd-698f4a5e7b3e.png)
还有个问题就是我在搜索框里面没有输入过dataId和group，但是为什么他会存在，而且刷新整个页面之后也不会被清除掉，这样子不干扰用户吗？
![nacos5](https://user-images.githubusercontent.com/57293296/114533525-8cfbef00-9c80-11eb-8045-8eea00801106.png)

**Comment by 985391294** [comment]
比如我新添加了个dataId为test1的，那我刚返回到配置列表是看不到我新添加的test1的，这样子很不友好吧。还有回滚被删除的那个走了个delete请求。
![nacos6](https://user-images.githubusercontent.com/57293296/114535059-3b546400-9c82-11eb-976f-05f3d52878d8.png)。
在历史版本里面的搜索框dataId和group能不能不要都是必填项，假如我想看我所有的历史版本岂不是看不了了吗？
![nacos7](https://user-images.githubusercontent.com/57293296/114535165-5a52f600-9c82-11eb-87ee-761f656130f0.png)

**Comment by lzp0412** [comment]
可以看下这个issue，看是否一样的问题: https://github.com/alibaba/nacos/issues/4064

**Comment by KomachiSion** [comment]
你前面提的那个issue是配置类型丢失问题，可以试一下。

这个issue的问题是概念理解有误的文件，看一下之前那个issue的解释就懂了

**Comment by 985391294** [comment]
> 你前面提的那个issue是配置类型丢失问题，和这个问题不一样，不要混淆。
> 
> 这个issue的问题是概念理解有误的问题，看一下之前那个issue的解释就懂了

我知道不是一個問題，只是跟你们阐述一下之前我碰到的问题。另外配置列表和历史版本的搜索框的问题，什么都没输入，就自动补入了，刷新页面都刷不掉，而且还是精确匹配不是模糊匹配。尤其是历史版本列表的搜索还是必填项，有点不太合理吧。

**Comment by 985391294** [comment]
另外如果回滚的是第一次创建的，直接给删除了是不是有点不合理，要么就第一次添加的配置不显示回滚按钮，要么在回滚的时候给个提示回滚第一次添加的配置会被删除。正常来说我回滚到哪一个版本就会选择到哪次，但是你们这个设计好像有点反人类吧。
