### ISSUE TITLE
[SecurityProxy] login http request failed url

### ISSUE THREAD

**Issue by xiaomo-23** [alibaba/nacos#5359]
use environment:
nacos server: 2.0.0
nacos client: 1.4.1
spring cloud 2020.0.2
spring cloud alibaba 2020.0.RC1

This problem occurs when using nacos config

error log:
[SecurityProxy] login http request failed url: http://192.168.80.140:8848/nacos/v1/auth/users/login, params: {username=naocs}, bodyMap: {password=nacos}, errorMsg: errCode: 100, errMsg: Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed.

**Comment by xiaomo-23** [comment]
**supplementary description**:

bootstrap.yml 
config:
server-addr: ${spring.cloud.nacos.config.server-addr}
username: ${spring.cloud.nacos.config.username}
password: ${spring.cloud.nacos.config.password}
file-extension: yaml
prefix: ${spring.application.name}

profiles: dev

application.yml
discovery:
server-addr: ${spring.cloud.nacos.config.server-addr}
username: ${spring.cloud.nacos.config.username}
password: ${spring.cloud.nacos.config.password}

same configuration, I can not reproduce the problem at home

configuration of the computer used at home
os：macOS Big Sur 11.2.3
nacos server: 2.0.0
nacos client: 1.4.1

**only difference**
home used localhost
company used Virtual Machine
Virtual Machine OS Centos7.3

**Comment by haoyann** [comment]
Let me try.

**Comment by luoxiner** [comment]
Did it occur randomly ?

**Comment by xiaomo-23** [comment]
I do not know,but I have tried the same computer, the same set of configuration, one has this problem, the other project does not appear

**Comment by Maijh97** [comment]
> I do not know,but I have tried the same computer, the same set of configuration, one has this problem, the other project does not appear
Please trace the following code when this problem occurs, I want to know which responseHandler is obtained when the problem occurs.

https://github.com/alibaba/nacos/blob/acb02f6bf3e7a623ee695d8081795926d5c528c0/common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java#L479

**Comment by Maijh97** [comment]
> I do not know,but I have tried the same computer, the same set of configuration, one has this problem, the other project does not appear

Please trace the following code when this problem occurs, I want to know which responseHandler is obtained when the problem occurs.

https://github.com/alibaba/nacos/blob/acb02f6bf3e7a623ee695d8081795926d5c528c0/common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java#L479

**Comment by haoyann** [comment]
1. 使用一个错误的账号、密码，登陆返回403；
![image](https://user-images.githubusercontent.com/43994656/115408846-c950c180-a223-11eb-802b-242e4ef80893.png)
2.  登陆失败打印异常日志，`SECURITY_LOGGER.error("login failed: {}", JacksonUtils.toJson(restResult));`；
3. httphead 里有不合法数据，导致json序列化错误；
![image](https://user-images.githubusercontent.com/43994656/115409111-07e67c00-a224-11eb-9ca4-39c01b2d9fa6.png)
![image](https://user-images.githubusercontent.com/43994656/115409152-1339a780-a224-11eb-9b57-ab1a58773fbb.png)
4. 我使用develop分支和2.0分支打一个client包，没有复现这个问题；
![image](https://user-images.githubusercontent.com/43994656/115409426-54ca5280-a224-11eb-9b25-c1d905fee807.png)
![image](https://user-images.githubusercontent.com/43994656/115409465-5d228d80-a224-11eb-8349-ff84f8b9eb2c.png)

**Comment by KomachiSion** [comment]
> 1. 使用一个错误的账号、密码，登陆返回403；
>    ![image](https://user-images.githubusercontent.com/43994656/115408846-c950c180-a223-11eb-802b-242e4ef80893.png)
> 2. 登陆失败打印异常日志，`SECURITY_LOGGER.error("login failed: {}", JacksonUtils.toJson(restResult));`；
> 3. httphead 里有不合法数据，导致json序列化错误；
>    ![image](https://user-images.githubusercontent.com/43994656/115409111-07e67c00-a224-11eb-9ca4-39c01b2d9fa6.png)
>    ![image](https://user-images.githubusercontent.com/43994656/115409152-1339a780-a224-11eb-9b57-ab1a58773fbb.png)
> 4. 我使用develop分支和2.0分支打一个client包，没有复现这个问题；
>    ![image](https://user-images.githubusercontent.com/43994656/115409426-54ca5280-a224-11eb-9b25-c1d905fee807.png)
>    ![image](https://user-images.githubusercontent.com/43994656/115409465-5d228d80-a224-11eb-8349-ff84f8b9eb2c.png)

我记得那个null key的问题已经解决掉了， 在之前的那个PR里

https://github.com/alibaba/nacos/issues/3695

**Comment by haoyann** [comment]
#3695 是在`head`里面处理的，这里的null key出现在`originalResponseHeader`，我看 #4870，已经处理了这个问题。

**Comment by xiaomo-23** [comment]
这个问题我在重新创建一个项目的时候就会消失，又遇到过一次，重新创建项目就没有了，配置信息都是基本一致的

用户名与密码均正确

1. 这是项目首次运行的时候
![微信截图_20210422165901](https://user-images.githubusercontent.com/51806785/115686933-45feaf80-a38c-11eb-9666-ac3d61d4a91e.png)

2. 这是项目后续 nacos 自动请求的情况
![微信截图_20210422165936](https://user-images.githubusercontent.com/51806785/115687087-69c1f580-a38c-11eb-9c25-35fbdff0bfcb.png)

这个demo项目晚上我会使用另外一台电脑来测试一下

**Comment by Maijh97** [comment]
@xiaomo-23 看到错误日志为errorMsg: errCode: 100, errMsg: Nacos serialize for class [com.alibaba.nacos.common.http.HttpRestResult] failed， Nacos serialize for class 异常日志只有在使用com.alibaba.nacos.common.utils.JacksonUtils才会出现。 麻烦你那边在出现该问题时，帮忙查看一下取到ResponseHandler是什么

https://github.com/alibaba/nacos/blob/acb02f6bf3e7a623ee695d8081795926d5c528c0/common/src/main/java/com/alibaba/nacos/common/http/client/NacosRestTemplate.java#L479

**Comment by Maijh97** [comment]
> 这个问题我在重新创建一个项目的时候就会消失，又遇到过一次，重新创建项目就没有了，配置信息都是基本一致的
> 
> 用户名与密码均正确
> 
> 1. 这是项目首次运行的时候
>    ![微信截图_20210422165901](https://user-images.githubusercontent.com/51806785/115686933-45feaf80-a38c-11eb-9666-ac3d61d4a91e.png)
> 2. 这是项目后续 nacos 自动请求的情况
>    ![微信截图_20210422165936](https://user-images.githubusercontent.com/51806785/115687087-69c1f580-a38c-11eb-9c25-35fbdff0bfcb.png)
> 
> 这个demo项目晚上我会使用另外一台电脑来测试一下

403应该是账号密码错误导致的。但是errcode 为100是另外的一个问题

**Comment by Maijh97** [comment]
> 这个问题我在重新创建一个项目的时候就会消失，又遇到过一次，重新创建项目就没有了，配置信息都是基本一致的
> 
> 用户名与密码均正确
> 
> 1. 这是项目首次运行的时候
>    ![微信截图_20210422165901](https://user-images.githubusercontent.com/51806785/115686933-45feaf80-a38c-11eb-9666-ac3d61d4a91e.png)
> 2. 这是项目后续 nacos 自动请求的情况
>    ![微信截图_20210422165936](https://user-images.githubusercontent.com/51806785/115687087-69c1f580-a38c-11eb-9c25-35fbdff0bfcb.png)
> 
> 这个demo项目晚上我会使用另外一台电脑来测试一下

![image](https://user-images.githubusercontent.com/37288946/115809637-12209a00-a41f-11eb-874a-ebc879d55016.png)

这里看到header 是为LinkedHashMap， 目前1.4.1应该是为TreeMap才对。麻烦确认一下nacos-client是否为1.4.1

**Comment by xiaomo-23** [comment]
搞定了，这个问题是因为SpringCloud Alibaba依赖自带的 Nacos Client客户端版本低导致的，需要将SpringCloudAlibaba自带的client忽略，然后自行导入client 2.0.0，就不会出现序列化错误


会存在一个unknown user的问题，也就是会进入
![image](https://user-images.githubusercontent.com/51806785/115826072-f0361000-a43c-11eb-9c74-0cb47e8f75f3.png)

这个问题不会影响正常使用，进行通过配置日志等级即可进行忽略。

**Comment by 373616885** [comment]
@xiaomo-23 这个unknown user的问题什么情况，谁能解释一下
