### ISSUE TITLE
【咨询】nacos对于数据源的判断逻辑

### ISSUE THREAD

**Issue by julingpu** [alibaba/nacos#5366]
版本：1.4.1

背景：
nacos目前不支持postgresql数据源，想自己改造一下

问题：
1、nacso集群模式是否可以使用内嵌数据源？有的地方说可以有的地方说不行
说可以的地方：https://github.com/nacos-group/nacos-docker/issues/128
说不可以的地方：https://developer.aliyun.com/ask/317393
同时我发现PropertyUtil.isDirectRead()中的判断条件是 单机 && 内嵌数据源，
这种判断方式是不是代表集群可以使用内嵌数据源？

2、另外代码里有的地方（比如LocalDataSourceServiceImpl）是通过PropertyUtil.isUseExternalDB()判断数据源,
有的地方（比如DynamicDataSource）是通过PropertyUtil.isEmbeddedStorage()判断数据源。这种判断不统一是不是因为开发人员不一致导致的？还是有其他隐情？

**Comment by JackSun-Developer** [comment]
> nacos目前不支持postgresql数据源，想自己改造一下

多数据源分支： feature_multiple_datasource_support

> nacos集群模式是否可以使用内嵌数据源？有的地方说可以有的地方说不行

不管是集群模式，还是单机模式，都支持内嵌:
集群启动:"bash startup.sh -p embedded"，单机启动：“bash startup.sh -p embedded -m standalone"

**Comment by julingpu** [comment]
请问feature_multiple_datasource_support这个分支的状态是什么样的？
我看了下com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties#build方法里面还是mysql驱动

**Comment by julingpu** [comment]
请问feature_multiple_datasource_support这个分支的状态是什么样的？
我看了下com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties#build方法里面还是mysql驱动

**Comment by haoyann** [comment]
> 请问feature_multiple_datasource_support这个分支的状态是什么样的？
> 我看了下com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties#build方法里面还是mysql驱动

`feature_multiple_datasource_support`分支参考这个issue #5052

**Comment by KomachiSion** [comment]
> nacso集群模式是否可以使用内嵌数据源？有的地方说可以有的地方说不行

1.3.0版本后，可以在集群模式下使用内嵌数据库，开启方式：application.properties里面注释掉和mysql有关的相关配置，并使用startup.sh -p embedded命令启动。 一致性使用jraft保证。

> 另外代码里有的地方（比如LocalDataSourceServiceImpl）是通过PropertyUtil.isUseExternalDB()判断数据源,
有的地方（比如DynamicDataSource）是通过PropertyUtil.isEmbeddedStorage()判断数据源。这种判断不统一是不是因为开发人员不一致导致的？还是有其他隐情？

通过独立语意进行判断，而非耦合语音（比如收敛成同一个is判断）是当时的设计，以此进行干扰隔离，之后重构的时候如果发现没必要可能会统一。
