### ISSUE TITLE
集群启动一个节点后 再启动另一个节点，为什么各自的nacos.log会不停的打日志

### ISSUE THREAD

**Issue by DillonPu** [alibaba/nacos#5368]
集群部署了三台机器， 192.168.2.24， 192.168.2.25，192.168.2.29
1.当在192.168.2.29上sh startup.sh启动了该机器上的nacos节点后，启动正常，运行访问正常，29这台的nacos.log此时不会一直打日志
2.当启动了192.168.2.24这台机器上的nacos节点后，192.168.2.29就会不停的打日志，如下图
![image](https://user-images.githubusercontent.com/17973774/114693894-9eaac880-9d4c-11eb-907f-618ca122bfc5.png)

3.192.168.2.24这台机器的nacos.log也会不停打日志，但是单独访问nacos都能访问，节点列表也有显示
![image](https://user-images.githubusercontent.com/17973774/114694585-458f6480-9d4d-11eb-93ba-e35ca9ccbe2f.png)

**Comment by DillonPu** [comment]
nacos2.0版本

**Comment by KomachiSion** [comment]
说明集群之间的通信可能存在问题。检查一下集群间的网络是否正常，端口是否正常通信。

https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by DillonPu** [comment]
> 说明集群之间的通信可能存在问题。检查一下集群间的网络是否正常，端口是否正常通信。
> 
> https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

第一个节点启动后，在第二个节点也能访问第一个节点的nacos信息

**Comment by DillonPu** [comment]
> > 说明集群之间的通信可能存在问题。检查一下集群间的网络是否正常，端口是否正常通信。
> > https://nacos.io/zh-cn/docs/2.0.0-compatibility.html
> 
> 第一个节点启动后，在第二个节点也能访问第一个节点的nacos信息

防火墙是还需要开放7847端口嘛

**Comment by KomachiSion** [comment]
看你的防火墙作用范围，如果是单台机器，那就需要，如果是只在客户端环境和服务端环境之间的防火墙，而服务端之间没有防火墙，就不需要

**Comment by KomachiSion** [comment]
No more response from author, so we think it is usage problem for firewall
