### ISSUE TITLE
仅能通过properties来进行共享配置而无法使用yaml

### ISSUE THREAD

**Issue by WangZhenyu1992** [alibaba/nacos#5372]
配置中心配置共享配置  redis.yaml

client端配置bootstrap.yaml
    nacos:
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        extension-configs:
          - data-id: redis
 发现并未生效，无法读到redis中的配置内容

经过阅读源码，定位到，配置信息是通过com.alibaba.cloud.nacos.client.NacosPropertySourceLocator#loadNacosConfiguration读取的
刚方法中通过dataId分割点号获得文件后缀 
这里我的data-id没有后缀，于是使用了默认后缀
/**
* default extension.
*/
private static final String DEFAULT_EXTENSION = "properties";

而服务端我配置的是yaml，无法解析；

但是如果data-id 配置为redis.yaml
文件后缀可以正确获得，但在发送请求调用server端的openApi的时候，传的参数直接是data-id
拼接处的url为：http://localhost:8848/nacos/v1/cs/configs?dataId=redis.yaml&group=COMMON_GROUP
返回结果异常，如果dataId为redis，则可以正常返回对应配置文件

这里就形成了矛盾
当前仅能通过properties来进行共享配置而无法使用yaml

在com.alibaba.cloud.nacos.client.NacosPropertySourceLocator#loadNacosConfiguration该方法里，是否不应直接通过config.getDataId()传入，而应该像后缀一样，根据DOT截取真正的dataId呢？

目前server端使用2.0.0  client端版本为2.2.5.RELEASE

还有想顺便问下，shared 和 extension 有什么区别么，根据源码来看似乎处理逻辑是一致的

2021-04-15 补充：
经查阅，可以通过在8848/nacos 配置的时候，指定dataId 为带后缀的dataId，即redis.yaml。 但是由于dataId不能修改，这样如果下次想要改成其他后缀，就只能通过新增一个了，这样的设计似乎不太合理吧

**Comment by KomachiSion** [comment]
This is design of Spring cloud or some usage problem of Spring cloud alibaba. Please move this issue to Spring Cloud Alibaba community.
