### ISSUE TITLE
注册中心集群节点之间信息不传播(Information is not propagated between registry cluster nodes)

### ISSUE THREAD

**Issue by mingrn97** [alibaba/nacos#5376]
**Describe the bug**

注册中心链式注册，在每个注册中心节点上得到的注册信息是在配置文件 `cluster.conf` 中配置的节点而不是链式注册的全部节点。

Registry chain registration, the registration information obtained on each registry node is the node configured in the configuration file `cluster.conf` rather than all the nodes in the chain registration.

**Expected behavior**

使用链式注册节点，在每个节点上都能看到链式注册的所有节点信息。

With chained registration nodes, you can see all the chained registration node information on each node

**Acutally behavior**

链式注册后，在每个节点上看到的注册中心信息只是在配置文件 `cluster.conf` 中指定的注册节点信息，而不是全部的节点信息。

After the chain registration, the registry information you see on each node is only the registration node information specified in the configuration file `cluster.conf`, not all the node information

**How to Reproduce**

1、准备三台 `Ubuntu 20.04 LTS x86-64` 机器，IP 分别是：

Prepare three machines(`Ubuntu 20.04 LTS x86-64`), IP is：

- `192.168.1.115`
- `192.168.1.138`
- `192.168.1.149`

Openjdk version `1.8.0_282`

2、在 Github Release 页面下载 1.3.2 版本

Download version 1.3.2 from the GitHub Release page

```bash
https://github.com/alibaba/nacos/releases/download/1.3.2/nacos-server-1.3.2.tar.gz
```

3、之后修改每台服务器上的 `cluster.conf` 文件。

Then modify the `cluster.conf` file on each server

`192.168.1.115` 机器中 `cluster.conf` 配置内容如下
The `cluster.conf` configuration in machine `192.168.1.115` is as follows

```
192.168.1.138:8848
```

`192.168.1.138` 机器中 `cluster.conf` 配置内容如下
The `cluster.conf` configuration in machine `192.168.1.138` is as follows

```
192.168.1.149:8848
```

`192.168.1.149` 机器中 `cluster.conf` 配置内容如下
The `cluster.conf` configuration in machine `192.168.1.149` is as follows

```
192.168.1.115:8848
```

之后使用集群模式启动服务，启动成功后结果如下：
The services are then started using cluster mode, The results after successful startup are as follows:

![image](https://user-images.githubusercontent.com/32328109/114813633-1c221780-9de5-11eb-8932-9a71068fb63e.png)

![image](https://user-images.githubusercontent.com/32328109/114813666-2b08ca00-9de5-11eb-9711-fe1c00671064.png)

![image](https://user-images.githubusercontent.com/32328109/114813704-3956e600-9de5-11eb-897c-89836bbd4c9e.png)

**最后得到的结论是：注册中心链式注册的形式节点信息不回传播。**
**Finally, the conclusion is that the node information in the form of the chain registration of the registry is not transmitted back.**

**Desktop (please complete the following information):**
 - OS：`Ubuntu 20.04 LTS x86-64`
 - Version：`nacos-server-1.3.2`
 - Module：`registry`
 - SDK：original

**Comment by JackSun-Developer** [comment]
首先，这个配置方式是不对的，cluster.conf中应该包含所有的集群中的机器，但是你配置的cluster.conf只有一台。

>192.168.1.115 机器中 cluster.conf 配置内容如下
>The cluster.conf configuration in machine 192.168.1.115 is as follows

>192.168.1.138:8848

**Comment by JackSun-Developer** [comment]
把你的每台机器上的cluster.conf换成如下内容，就能正常运行了。

>192.168.1.115
>192.168.1.138
>192.168.1.149

**Comment by mingrn97** [comment]
> 把你的每台机器上的cluster.conf换成如下内容，就能正常运行了。
> 
> > 192.168.1.115
> > 192.168.1.138
> > 192.168.1.149

你说的这个我试了，是没问题的。实际上我上述说的那种链式配置也是没问题的。在注册服务时节点都能够被传播到每个注册中心上。

我的疑问是：服务注册到集群中的任何一个注册中心，集群中的所有注册中心都能看到该服务。为什么对于注册中心却不传播？

如果只能通过在 `cluster.conf` 配置文件中进行配置注册中心才能在页面上显示，对于灰度发布某个时刻需要增加一个注册中心节点其他运行中的注册中心岂不是同样不能一直不能在页面上显示该注册中心节点？

**Comment by JackSun-Developer** [comment]
> 对于灰度发布某个时刻需要增加一个注册中心节点其他运行中的注册中心岂不是同样不能一直不能在页面上显示该注册中心节点

nacos会持续监控这个cluster.conf，要增加新的注册中心节点，直接把新增的节点在cluster.conf中添加即可。

**Comment by mingrn97** [comment]
> > 对于灰度发布某个时刻需要增加一个注册中心节点其他运行中的注册中心岂不是同样不能一直不能在页面上显示该注册中心节点
> 
> 应该是，nacos会持续监控这个cluster.conf，要增加新的注册中心节点，直接把新增的节点在cluster.conf中添加即可。

我当前演示的示例已经运行了几个小时....... 

我现在的是在 `cluster.conf` 文件中将手动配置的注册节点重新了一遍，对于新增的注册中心节点是一直没有被添加进去。

**Comment by KomachiSion** [comment]
你是想，让集群节点自动添加？

那样有很多场景需要考虑，会变得很复杂， 注册中心和配置中心这种组件，其实不太对经常扩缩容，相反的它需要自身运行稳定。
因此我们认为不自动添加，而是通过显示修改文件/地址服务器的方式更加稳妥和可控。

**Comment by KomachiSion** [comment]
至于你提的问题，修改cluster.conf将所有节点添加之后仍然没有全节点列表，我这里在本地和k8s环境都尝试了，没有复现。
如果您这边还是复现，麻烦提供具体的步骤和日志。

**Comment by mingrn97** [comment]
> 你是想，让集群节点自动添加？
> 
> 那样有很多场景需要考虑，会变得很复杂， 注册中心和配置中心这种组件，其实不太对经常扩缩容，相反的它需要自身运行稳定。
> 因此我们认为不自动添加，而是通过显示修改文件/地址服务器的方式更加稳妥和可控。

我的意思不是说在 `cluster.conf` 文件中自动添加，而是新增一个注册中心节点后在控制台界面中的节点了列表中并没有显示。

**Comment by KomachiSion** [comment]
你修改了cluster.conf吗？ 添加了之后还没有显示吗？

**Comment by KomachiSion** [comment]
要集群中所有节点的cluster.conf都添加新的节点才行。

**Comment by mingrn97** [comment]
> 要集群中所有节点的cluster.conf都添加新的节点才行。

我的疑问就在这里，必须要所有节点的 `cluster.conf` 都添加新的节点才行，如果在一个已运行的集群环境中添加一个新注册节点，要想在列表中显示这个新节点岂不是要将以启动的节点都要修改 `cluster.conf` 后重新启动才行？

**Comment by KomachiSion** [comment]
不需要重新启动，只需要修改所有的cluster.conf
