### ISSUE TITLE
Nacos 服务端 1.3.0版本 数据库连接池内存泄漏

### ISSUE THREAD

**Issue by JackSlamDunk** [alibaba/nacos#5377]
nacos团队你们好：
最近发现nacos集群三台机器内存频率报内存不足，经发现nacos内存占用较高，而且服务内存占用率会不断上升
经过dump文件分析，com.mysql.jdbc.NonRegisteringDriver$ConnectionPhantomReference 对象占了堆内存的大部分空间
初步判断是创建大量的连接池在ConnectionPhantomReference 的虚引用，废弃的数据库连接对象堆积，最终导致 full gc 时间过长。
还请帮忙指点迷津！
![image](https://user-images.githubusercontent.com/58261759/114829904-36b4ba80-9dfe-11eb-8cf5-20b4c57aab41.png)

**Comment by KomachiSion** [comment]
该引用在jdbc内部，nacos的旧版本中连接池数量是可配置的，不存在泄漏问题，可能是mysql jdbc的bug 可以试着升级一下nacos版本来升级jdbc，看下是否能够解决该问题。
