### ISSUE TITLE
Use assert instead of System.out

### ISSUE THREAD

**Issue by SunJiFengPlus** [alibaba/nacos#5380]
![图片](https://user-images.githubusercontent.com/39667700/114871586-02f08980-9e2c-11eb-9bbc-151d6d4dfdc0.png)

Please assign it to me, I'd love to do it

**Comment by KomachiSion** [comment]
Thanks for your contribution.
But I see your provided picture, all most of them are just want to show test detail rather than assert case.

So I think there is no need to change them to assert.

**Comment by SunJiFengPlus** [comment]
not as much as in the picture, just a few points.

![图片](https://user-images.githubusercontent.com/39667700/114964590-9f08a800-9ea1-11eb-85e6-a00bb7631813.png)
![图片](https://user-images.githubusercontent.com/39667700/114964595-a2039880-9ea1-11eb-8ce7-8171711c6491.png)
![图片](https://user-images.githubusercontent.com/39667700/114964601-a465f280-9ea1-11eb-8334-2add64db9a2e.png)

**Comment by KomachiSion** [comment]
Yes, we need to discuss whether these case is need be assert or just a print dependency

**Comment by SunJiFengPlus** [comment]
> ![图片](https://user-images.githubusercontent.com/39667700/114964590-9f08a800-9ea1-11eb-85e6-a00bb7631813.png)
> ![图片](https://user-images.githubusercontent.com/39667700/114964595-a2039880-9ea1-11eb-8ce7-8171711c6491.png)
> ![图片](https://user-images.githubusercontent.com/39667700/114964601-a465f280-9ea1-11eb-8334-2add64db9a2e.png)


I think there are three ```System.out``` need to replace it with assert, and if confirmed, I'll start.

**Comment by KomachiSion** [comment]
go ahead please, these case should add assert to ensure.
