### ISSUE TITLE
pm2 无法正常启动nacos

### ISSUE THREAD

**Issue by PanHywel** [alibaba/nacos#5383]
**Is your feature request related to a problem? Please describe.**
某些情况下，我不得使用pm2启动nacos，但我发现使用pm2 启动nacos会导致pm2无法正常监听进程，并且无限循环重启。

**Describe the solution you'd like**
我希望能在pm2下正常使用

**Describe alternatives you've considered**
现在关掉自动重启功能使用
  {
    "name": "nacos",
    "script": "/gensee/nacos/bin/startup.sh",
    "args": "-m standalone",
    "exec_interpreter": "none",
    "exec_mode": "fork_mode",
    "autorestart": false
  }

**Additional context**
  {
    "name": "nacos",
    "script": "/nacos/bin/startup.sh",
    "args": "-m standalone",
    "exec_interpreter": "none",
    "exec_mode": "fork_mode",
    "autorestart": true
  }

**Comment by KomachiSion** [comment]
Have some nodejs users help us to check this problem?

**Comment by plusmancn** [comment]
@PanHywel  Please provide the version of pm2. 

Furthermore, if you can wrap your sample configs into the code block of Markdown that will make the issue more readable, for example: 
```json
{
  "name": "nacos",
  "script": "/nacos/bin/startup.sh",
  "args": "-m standalone",
  "exec_interpreter": "none",
  "exec_mode": "fork_mode",
  "autorestart": true
}
```

**Comment by PanHywel** [comment]
hi @plusmancn , PM2 version: 4.2.0

**Comment by plusmancn** [comment]
@PanHywel 
Actually, This problem is neither of PM2 and Nacos, but about the Linux shell command `nohup`.

If we execute the command `./nacos/bin/startup.sh -m standalone` in the shell, the program will exit with code `0` immediately which results in the PM2 daemon thinks that the process is dead, and then Pm2 will try to restart the process indefinitely.

**Comment by plusmancn** [comment]
@PanHywel @KomachiSion This issue should be closed.

**Comment by PanHywel** [comment]
@plusmancn thank
