### ISSUE TITLE
Upgrade to 2.0.0

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#5386]
hi all:
nacos 2.0.0 修改了客户端和服务端之间的通信方式，换成grpc。
现在如果从1.3.0升级到2.0.0，我各个服务的spring-cloud-starter-alibaba-nacos-discovery或nacos-config-spring-boot-starter的版本需要升级才会从http切换到grpc吗？
如果需要请问要用哪个版本？2021.1？
如果是要用2021.1版本，是不是对springboot的版本也有要求？因为我尝试在我现有的springboot版本上使用2021.1版本，启动会报Error processing condition on com.alibaba.cloud.nacos.discovery.reactive.NacosReactiveDiscoveryClientConfiguration.nacosReactiveDiscoveryClient

**Comment by KomachiSion** [comment]
您可以先升级nacos服务端到2.0，2.0的服务端支持旧版本http客户端。

之后可以慢慢升级客户端spring-cloud-starter-alibaba-nacos-discovery 或者修改pom 自行引入nacos-client 2.0.0

**Comment by KomachiSion** [comment]
spring-cloud-starter-alibaba-nacos-discovery 目前最新默认的客户端引入应该是1.4.1。 暂时还没有升级到2.0

具体依赖请关注到SCA社区

**Comment by saiyujs** [comment]
我排除nacos-client 1.3.0，重新引用nacos-client 2.0.0了，有什么办法可验证现在到底用的是http还是grpc？

**Comment by KomachiSion** [comment]
如果你确认已经更换成2.0.0的客户端，那么一定大多数请求是使用grpc。因为新客户端将大部分调用逻辑改成grpc了。

如果一定要确认，目前可以有两种方法。

1. 抓包，看调用的端口是8848还是9848（默认）
2. 看下服务端的naming-server.log日志 看下Client XXX connected中的XXX格式，如果是ip_port_timestamp 就是grpc，如果是ip:port#true 就是http
