### ISSUE TITLE
设置nacos客户端本地缓存文件名称

### ISSUE THREAD

**Issue by caichb** [alibaba/nacos#5387]
question:
      中文： nacos客户端的server-addr配置太长时，nacos生成缓存文件（fixed-xxx）受系统的限制（超过系统允许的长度）。请问是否有配置本地缓存文件名称的配置。
       english:   When the server-addr configuration of the nacos client is too long, the cache file (fixed-xxx) generated by nacos is restricted by the system (exceeding the length allowed by the system). Is there a configuration to configure the name of the local cache file?

**Comment by KomachiSion** [comment]
是配置文件的缓存文件还是服务的？

**Comment by caichb** [comment]
配置的缓存，看生成的文件是 fixed-${server-addr}  是这么个开头的

**Comment by KomachiSion** [comment]
所以是${server-addr}太长导致超出系统允许长度？

那是否应该自行改短${server-addr}？

可能考虑到缓存的唯一性，增加使用了server-address作为标记

**Comment by caichb** [comment]
nacos集群环境，客户端通过ip直连，在减少server-addr 配置，客户端是否可以感知到所有nacos服务端节点？（就是客户端会自动从一个server-addr获取所有nacos服务端节点信息，客户端内部会维护一个nacos集群内所有服务的ip:port列表）。就是不影响使用。

**Comment by KomachiSion** [comment]
没懂问题。 不是因为域名太长导致的超出允许长度吗？  修改域名就好了吧。 如果用ip还超长，那应该需要看下你dataId是否可以改短。还超长就得看是否是文件夹深度太大了。

**Comment by KomachiSion** [comment]
Maybe usage problem, and author has no more response for a long time.
