### ISSUE TITLE
Not consider multiple project run on one user home after user nacos make file conflict.

### ISSUE THREAD

**Issue by zxdposter** [alibaba/nacos#5392]
**Is your feature request related to a problem? Please describe.**
multiple project all use nacos, produce all at same place.

**Describe the solution you'd like**
please add some way, can split them.
I already try `-DJM.LOG.PATH=${COMMON.BASE:-${HOME}/common}/logs/nacos/${PID} ` or  `-DJM.LOG.PATH=${COMMON.BASE:-${HOME}/common}/logs/nacos/${spring.application.name} `(spring.application.name is undefined)

**Comment by KomachiSion** [comment]
The only supported variable for `JM.LOG.PATH` is ${user.home}.

```
        String loggingPath = System.getProperty(NACOS_LOGGING_PATH_PROPERTY);
        if (StringUtils.isBlank(loggingPath)) {
            String userHome = System.getProperty("user.home");
            System.setProperty(NACOS_LOGGING_PATH_PROPERTY, userHome + File.separator + "logs");
        }
```

**Comment by KomachiSion** [comment]
So please do replace for `${spring.application.name}` in your start shell script.

**Comment by zxdposter** [comment]
@KomachiSion  Already try, will become `spring.application.name_IS_UNDEFINED`.

**Comment by zxdposter** [comment]
@KomachiSion have any advices?
