### ISSUE TITLE
X-Forwarded-For allows spoofing client address

### ISSUE THREAD

**Issue by haby0** [alibaba/nacos#5406]
**Describe the bug**

X-Forwarded-For records the path a given request has taken. The first IP is the origin client, each subsequent IP denotes a path along the way (proxies, load balancers, whatever). However, blindly trusting the header obviously allows anyone to spoof the origin IP. 

[problem code](https://github.com/alibaba/nacos/blob/develop/config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java#L51)

E.g: 
X-Forwarded-For: client, proxy1, proxy2. User can forge client.

**Reference**
https://www.f5.com/company/blog/security-rule-zero-a-warning-about-x-forwarded-for

**Comment by KomachiSion** [comment]
I can't understand your problem, please provide more information.

**Comment by haby0** [comment]
Using `X-Forwarded-For` to get the client ip is not safe, because `X-Forwarded-For` can be forged.
There are several ways to use the client ip in the code:
- [Configuration cache related](https://github.com/alibaba/nacos/blob/9bcb901174598c049f9ec20213a964695611ac1e/config/src/main/java/com/alibaba/nacos/config/server/service/ConfigCacheService.java#L535)
- [Logging](https://github.com/alibaba/nacos/blob/394230309d157f08510f42266e4a92a189e6b5d7/config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java#L160)

**Comment by haby0** [comment]
https://github.com/alibaba/nacos/blob/394230309d157f08510f42266e4a92a189e6b5d7/config/src/main/java/com/alibaba/nacos/config/server/utils/RequestUtil.java#L51-L54
This is the extracted source code. When there is `X-Forwarded-For` in the request header, the first ip will be returned. 

`X-Forwarded-For: client1, proxy1, proxy2, proxy3` This is the general format of the request header. The value of `client1` comes from the client, and the value here can be forged. And the program is to get X-Forwarded-For The first value of. 

In addition, I searched the program code and found that the client ip was used in the logging and caching code.

**Comment by KomachiSion** [comment]
Yes, we want to get the first clientIp because config module beta feature need the true client IP. 
If we close or ignore this header, use Request.getRemoteIp, config module may get the ip of VIP/SLB/VPN, which will cause the beta config can't push to beta client right.

The first client ip should add by nacos client, I think. If users or other people forge it. It just add one invalid beta client only.

**Comment by haby0** [comment]
Ok, I will close this issue.
