### ISSUE TITLE
建议注册中心服务详情页面增加翻页功能

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#5407]
注册中心的某个服务超过10个实例时，服务详情只显示10条，没有翻页选项，手工在url上加pageNo和pageSize也没有效果。
难道服务详情最多显示10个instance？

**Comment by haoyann** [comment]
已经修复了 #4898.

**Comment by zrlw** [comment]
nacos1.2.1可以翻页
nacos1.4.1翻不了页，js的instance变量名写错了。
