### ISSUE TITLE
nacos-config-spring-boot-autoconfigure   中 NacosPropertiesBuilder类引用StringUtils问题

### ISSUE THREAD

**Issue by liyanglin** [alibaba/nacos#5409]
### nacos-config-spring-boot-autoconfigure-0.2.7  
![image](https://user-images.githubusercontent.com/33758785/115247695-96da9200-a159-11eb-8791-21c8c7b12baa.png)
NacosPropertiesBuilder该类引用StringUtils  使用了org/apache/commons/lang3   导致使用时需要强制导入lang3依赖但是
StringUtils  在com.alibaba.nacos.common.utils    中是存在且是原有方法不依赖于其他，因此NacosPropertiesBuilder该类应该import com.alibaba.nacos.common.utils.StringUtils 而不是lang3

**Comment by KomachiSion** [comment]
从程序角度来说，nacos-spring-boot使用nacos-client应该面向提供的api接口编程。

nacos-common中的工具类是提供给nacos自身使用的，随时会发生重构，移动，删除等操作，并非提供外部使用的api。虽然可以使用，但是容易造成版本间的兼容性问题。

相反，lang3本身作为工具类提供api接口，一般能够保证接口版本间的稳定性，因此spring（-boot）项目中使用lang3作为工具类。

如果需要移除lang3依赖，需要改成使用spring的工具类或者在nacos-spring-context里面实现给spring体系用的工具类。

最稳定的方法肯定是实现自己的工具类，用spring的工具类同样可能有版本升级导致的不兼容性。
