### ISSUE TITLE
How to keep Chinese comments in Yaml?

### ISSUE THREAD

**Issue by yuchengnormanliu** [alibaba/nacos#5412]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
If there are Chinese comments in the yaml format configuration information, the microservice can't read the configuration information in the Nacos configuration center. If you delete the Chinese comments, you can read them immediately. 

### Describe what you expected to happen
What can I do if I want to keep the Chinese comments in YAML?

### How to reproduce it (as minimally and precisely as possible)

1. If there are Chinese comments in the yaml format configuration information, the microservice can't read the configuration information in the Nacos configuration center.
2.  Delete the Chinese comments, you can read them immediately. 
3. 

### Tell us your environment
we are trying to use Nacos 2.2.5.release as the micro service registry and configuration center, and the configuration information is put in MySQL database. Now I have a small problem. I can't find a satisfactory solution on the Internet.

**Comment by KomachiSion** [comment]
Please check configuration in console, and check the logs in ${user.home}/logs/nacos/config.log in your client machine, to see whether the configuration get from server contains chinese. From our test, nacos support chinese in configuration.

**Comment by yuchengnormanliu** [comment]
I have solved this problem. Add -Dfile.encoding=utf-8 (it must be placed before -jar, utf-8 or UTF-8 in both case) in java command line. Otherwise, the information in the Nacos configuration center cannot be read when the microservice is started in windows
