### ISSUE TITLE
nacos 控制台 服务详情 集群数目很多情况下的分页问题

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#5417]
注意到控制台的服务详情页，只针对同一个集群下的实例在实例数很多的情况下实现了分页；
现在有这样一种场景，服务有一千多个实例，分五十个集群部署，但是控制台似乎是将五十个集群页面都塞到一个页面里面；
请问nacos 会考虑在集群维度提供分页查询能力吗？

**Comment by KomachiSion** [comment]
暂时不考虑提供，因为Nacos2.0开始会逐渐弱化集群的概念，将其只作为实例的一个标示或元数据。
