### ISSUE TITLE
The class com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl lacks a lot of Unit tests (Both in Nacos1.4.1 and 2.0.0)

### ISSUE THREAD

**Issue by JackSun-Developer** [alibaba/nacos#5418]
The class com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl lacks a lot of Unit tests (Both in Nacos1.4.1 and 2.0.0), could you provide?

**Comment by li-xiao-shuang** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
Only submit to develop branch is ok. we can merge it to 2.0.X

**Comment by li-xiao-shuang** [comment]
> Only submit to develop branch is ok. we can merge it to 2.0.X
ok
