### ISSUE TITLE
nacos 支持项目配置文件中数据库密码加密刷新吗

### ISSUE THREAD

**Issue by Fangzhongpeng** [alibaba/nacos#5423]
nacos 支持项目配置文件中数据库密码加密刷新吗

**Comment by sanxun0325** [comment]
No, it is not the responsibility of NACOS. NACOS only supports configuration refresh.

**Comment by KomachiSion** [comment]
We are planing and designing the configuration encrypt plugin features. detail in #5367 .

But Nacos will not do encrypt for specified key in configuration for now.
If you want to do this. You can try to implement one plugin by yourself.

**Comment by RobberPhex** [comment]
> nacos 支持项目配置文件中数据库密码加密刷新吗

@Fangzhongpeng 

#5367 提出了加密插件的设计，可以自己扩展加密方式。
但是你说的加密刷新是什么意思？
