### ISSUE TITLE
对集群的一些疑问 Some questions about clustering

### ISSUE THREAD

**Issue by QBH-insist** [alibaba/nacos#5431]
## Issue Description
对集群的一些疑问：采用了 Distro 协议，是代表每个节点都有能力处理注册写事件吗？然后节点之间会互相同步整合数据，
这个跟 Eureka 有点像。同时 Nacos 还采用了 Jraft 进行主从选举，选主从的作用是？我理解采取临时节点注册的方式，每个节点都是 peer to peer 的关系 。因为在官网找不到集群同步的一些信息，所以来这里提问，麻烦了。
Some questions about clustering, Does the adoption of Distro protocol mean that each node is capable of handling registered write events?The nodes then synchronize the data with each other,This is like Eureka. At the same time, NACOS also uses JRAFT to conduct master-slave election. What is the meaning of master-slave election? I understand that temporary node registration is adopted, and each node is a peer-to-peer relationship. Unable to find some information on cluster synchronization on the official website, so come here to ask questions

### Tell us your environment
1.4.1 window

**Comment by MajorHe1** [comment]
服务分临时服务（ephemeral）和持久服务（persistent）。
临时服务使用Distro协议进行同步，集群计算服务的权威节点，权威节点负责该服务的写入。详情可以查看DistroController.java  、DistroFilter.java 和 DistroMapper.java。
持久服务使用raft协议进行同步，怎么个同步法就是raft协议的事情了。

**Comment by JackSun-Developer** [comment]
临时服务（ephemeral service）-> use Distro protocol (AP) , because ephemeral instances sends heartbeats always, AP may lost consistency for some register requests, but after a long period the non-consistency will be adjusted.
持久化服务（persistent service）-> use jRaft protocol (CP), because som persistent service register only once and doesn't send hearbeats after that, if the one-time register request is on an partitioned server, the lost of consistency will be unaffordable.

**Comment by MajorHe1** [comment]
正好接着这个问题问一下：
nacos 2.0之后使用grpc协议注册的临时服务是没有心跳的，那Distro协议的注册和同步是怎么工作的？相关的代码写在哪里？

**Comment by JackSun-Developer** [comment]
@MajorHe1 
DistroDelayTaskProcessor.java 可以沿着这个类追踪一下，Distro协议的注册和同步应该也是用grpc做的。

**Comment by MajorHe1** [comment]
> @MajorHe1
> DistroDelayTaskProcessor.java 可以沿着这个类追踪一下，Distro协议的注册和同步应该也是用grpc做的。

@JackSun-Developer  用grpc进行节点间的distro协议同步没有问题，我想知道服务使用grpc进行注册的时候，有没有计算权威节点和将写请求转发给权威节点执行这个过程，如果有的话在哪里

**Comment by QBH-insist** [comment]
> 集群计算服务的权威节点，权威节点负责该服务的写入



> 服务分临时服务（ephemeral）和持久服务（persistent）。
> 临时服务使用Distro协议进行同步，集群计算服务的权威节点，权威节点负责该服务的写入。详情可以查看DistroController.java 、DistroFilter.java 和 DistroMapper.java。
> 持久服务使用raft协议进行同步，怎么个同步法就是raft协议的事情了。



> 服务分临时服务（ephemeral）和持久服务（persistent）。
> 临时服务使用Distro协议进行同步，集群计算服务的权威节点，权威节点负责该服务的写入。详情可以查看DistroController.java 、DistroFilter.java 和 DistroMapper.java。
> 持久服务使用raft协议进行同步，怎么个同步法就是raft协议的事情了。
你好，“集群计算服务的权威节点，权威节点负责该服务的写入”，这句话不是很明白。
权威节点是指 raft 协议选出来的 leader 节点吗？
该服务的写入是指处理注册等写请求吗？
Distro 协议下，每个节点都有能力处理写请求吧？
如果我的服务都是临时服务，部署2节点集群（官方推荐是最少三个）是否也可以？

**Comment by QBH-insist** [comment]
> 服务分临时服务（ephemeral）和持久服务（persistent）。
> 临时服务使用Distro协议进行同步，集群计算服务的权威节点，权威节点负责该服务的写入。详情可以查看DistroController.java 、DistroFilter.java 和 DistroMapper.java。
> 持久服务使用raft协议进行同步，怎么个同步法就是raft协议的事情了。

**Comment by QBH-insist** [comment]
> 服务分临时服务（ephemeral）和持久服务（persistent）。
> 临时服务使用Distro协议进行同步，集群计算服务的权威节点，权威节点负责该服务的写入。详情可以查看DistroController.java 、DistroFilter.java 和 DistroMapper.java。
> 持久服务使用raft协议进行同步，怎么个同步法就是raft协议的事情了。

你好，“集群计算服务的权威节点，权威节点负责该服务的写入”，这句话不是很明白。
权威节点是指 raft 协议选出来的 leader 节点吗？
该服务的写入是指处理注册等写请求吗？
Distro 协议下，每个节点都有能力处理写请求吧？
如果我的服务都是临时服务，部署2节点集群（官方推荐是最少三个）是否也可以？

**Comment by KomachiSion** [comment]
> > @MajorHe1
> > DistroDelayTaskProcessor.java 可以沿着这个类追踪一下，Distro协议的注册和同步应该也是用grpc做的。
> 
> @JackSun-Developer 用grpc进行节点间的distro协议同步没有问题，我想知道服务使用grpc进行注册的时候，有没有计算权威节点和将写请求转发给权威节点执行这个过程，如果有的话在哪里

grpc之后使用了长连接，distro的维度变了，从服务变成了连接，详情可以读一下2.0的代码。

**Comment by KomachiSion** [comment]
> > 服务分临时服务（ephemeral）和持久服务（persistent）。
> > 临时服务使用Distro协议进行同步，集群计算服务的权威节点，权威节点负责该服务的写入。详情可以查看DistroController.java 、DistroFilter.java 和 DistroMapper.java。
> > 持久服务使用raft协议进行同步，怎么个同步法就是raft协议的事情了。
> 
> 你好，“集群计算服务的权威节点，权威节点负责该服务的写入”，这句话不是很明白。
> 权威节点是指 raft 协议选出来的 leader 节点吗？
> 该服务的写入是指处理注册等写请求吗？
> Distro 协议下，每个节点都有能力处理写请求吧？
> 如果我的服务都是临时服务，部署2节点集群（官方推荐是最少三个）是否也可以？

Distro协议的权威节点或者叫责任节点和raft的leader不是一个概念。 责任节点更像是redis的分片写入节点。其他节点都是该分片的只读节点。

**Comment by MajorHe1** [comment]
> 权威节点是指 raft 协议选出来的 leader 节点吗？

不是，权威节点是Distro协议的概念，跟raft协议没关系，临时服务使用的Distro协议和持久服务使用的raft协议是地位对等，并行工作的。

> 该服务的写入是指处理注册等写请求吗？
> Distro 协议下，每个节点都有能力处理写请求吧？

 是的。每个节点通过Hash算法成为不同服务的权威节点。详情参见DistroMapper.java


> 如果我的服务都是临时服务，部署2节点集群（官方推荐是最少三个）是否也可以？

当然可以，只是不推荐。

**Comment by MajorHe1** [comment]
> grpc之后使用了长连接，distro的维度变了，从服务变成了连接，详情可以读一下2.0的代码。

@KomachiSion 可以请您解释一下“从服务变成了连接”这句话吗？意思是对于grpc协议而言，DistroMapper这个根据服务计算权威节点的逻辑可以不用了吗？或者请您简单指明一下相关的代码在哪里，自己抓不住重点有点难以理解。

**Comment by MajorHe1** [comment]
> > grpc之后使用了长连接，distro的维度变了，从服务变成了连接，详情可以读一下2.0的代码。
> 
> @KomachiSion 可以请您解释一下“从服务变成了连接”这句话吗？意思是对于grpc协议而言，DistroMapper这个根据服务计算权威节点的逻辑可以不用了吗？或者请您简单指明一下相关的代码在哪里，自己抓不住重点有点难以理解。

看了一下源码，发现对于grpc协议，DistroMapper计算权威节点的依据从服务名改成了ip+port. 
现在的疑问在于，假如服务注册上报连接的节点和Distro计算的权威节点不是同一个，那么：
1.服务注册是在上报节点做的还是权威节点做的？如果是在权威节点做的，转发grpc注册请求的代码在哪里？
2.健康检查是在上报节点做的还是权威节点做的？由于服务只跟上报节点有连接，如果是上报节点做的，那岂不是会出现非权威节点进行写操作的情况？如果是权威节点做的，那夸节点的健康检查是怎么实现的？
看心跳检查那一块的代码没看明白，希望得到您详细的解答，谢谢

**Comment by KomachiSion** [comment]
gprc请求不需要再转发， 长连接的特性在于连接存在就会一直由这台服务端进行处理，因此这个链接不断，这台服务端就是责任节点。（ConnectionedBasedClient 中的 isNative）

http的同样需要映射到类似的概念上，因此使用的ip+port来模拟长连接的分配。

2.0之后不再使用服务名作为Distro计算责任节点的tag了。
