### ISSUE TITLE
Optimize the ConfigType.isValidType method

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#5432]
motivation：

Optimize the ConfigType.isValidType method

**Comment by JackSun-Developer** [comment]
改动之前：每次调用isValidType，都会遍历一遍所有的ConfigType
改动之后：用一个localMap缓存所有的Type，每次调用isValidType时，直接从localMap中取即可。

**Comment by JackSun-Developer** [comment]
My question is:  can you replace "Map" with "Set". It seems more convinent to use set in this modification.

**Comment by xiaoheng1** [comment]
Generally speaking, we use configType to get the corresponding value, set cannot do this step.

**Comment by KomachiSion** [comment]
I have no idea about the frequent count of this method.
If no much frequently called, I think the enhancement is not neccessary.

**Comment by xiaoheng1** [comment]
The isValidType method is used in com.alibaba.nacos.config.server.controller.ConfigController#publishConfig. 

So I think it can be enhanced.
