### ISSUE TITLE
Does Nacos server support the active push of service discovery changes to clients

### ISSUE THREAD

**Issue by shaohaikkk** [alibaba/nacos#5435]
i wan't to confirm it that is nacos server support push change to clients, thx;

**Comment by JackSun-Developer** [comment]
> Does Nacos server support the active push of service discovery changes to clients

Yes, it supports change pushing. see the document nacos.io "Subscribe" API

**Comment by shaohaikkk** [comment]
During my testing, I found that other services perceived that there was a delay in offline (the client ribbon I used). What do I need to do to turn on the server and actively push it to the client? Do I need to implement the subcribe interface function myself?



***@***.***
 
From: 杨翊 SionYang
Date: 2021-04-22 09:33
To: alibaba/nacos
CC: zero; Author
Subject: Re: [alibaba/nacos] Does Nacos server support the active push of service discovery changes to clients (#5435)
Closed #5435.
