### ISSUE TITLE
Using mysql data source, why the data directory still stores data

### ISSUE THREAD

**Issue by xhsky** [alibaba/nacos#5438]
The mysql data source is used. After the configuration is created, it can be found in the mysql table. However, there will also be configuration records in the nacos/data/config-data/ directory. Why is a piece of data recorded twice?
nacos version: 1.4.1

**Comment by JackSun-Developer** [comment]
I think nacos/data/config-data/ is used for snapshot, e.g., If the mysql is down, the file system can be used to recover.

**Comment by xhsky** [comment]
If it is used for data recovery, mysql itself can perform data backup and recovery functions, and there is no need to rely on other records, right?

**Comment by KomachiSion** [comment]
see config log to find whether dump related config ok.

**Comment by KomachiSion** [comment]
> If it is used for data recovery, mysql itself can perform data backup and recovery functions, and there is no need to rely on other records, right?

1. If your mysql down and no snapshot, you will can't get config.
2. If all get config request send to mysql, when your app number is large, nacos can add node to cover, but mysql can't.
