### ISSUE TITLE
Param 'serviceName' is illegal

### ISSUE THREAD

**Issue by huhudiedie** [alibaba/nacos#5448]
java.lang.IllegalArgumentException: Param 'serviceName' is illegal, serviceName is blank
	at com.alibaba.nacos.api.naming.utils.NamingUtils.getGroupedName(NamingUtils.java:47) ~[nacos-api-1.4.1.jar:na]

在使用nacos  2021.1时报这个错误,如果使用2.1.0.RELEASE则不会
错误位置为
    public static String getGroupedName(final String serviceName, final String groupName) {
        if (StringUtils.isBlank(serviceName)) {
            throw new IllegalArgumentException("Param 'serviceName' is illegal, serviceName is blank");
        }
        final String resultGroupedName = groupName + Constants.SERVICE_INFO_SPLITER + serviceName;
        return resultGroupedName.intern();
    }

**Comment by JackSun-Developer** [comment]
This is related with an adjustment of  Nacos serviceName (The removal of groupName@@ prefix) in version 1.x ,see #4885 for the detail

**Comment by huhudiedie** [comment]
I'm a beginner. How can I solve this problem?

**Comment by JackSun-Developer** [comment]
> I'm a beginner. How can I solve this problem?

Upgrade to Nacos2.0.0

**Comment by huhudiedie** [comment]
使用2.0.0也是不行
我之前使用的版本如下:
![image](https://user-images.githubusercontent.com/67212456/115691381-94ae4880-a390-11eb-854a-942f011366b8.png)

**Comment by KomachiSion** [comment]
和版本没什么关系， 和配置有关系，你注册的服务，服务名是空的，这是不允许的。

**Comment by huhudiedie** [comment]
配置没有改,用老版本是可以的
![image](https://user-images.githubusercontent.com/67212456/115697221-f45b2280-a395-11eb-9a18-c3a68a3faf6e.png)
![image](https://user-images.githubusercontent.com/67212456/115697248-fcb35d80-a395-11eb-9270-15889f7629f4.png)

**Comment by Zze0** [comment]
我这边也有同样的问题，不过当我把bootstrap.yml改成使用application.yml就可以启动了。 @KomachiSion

**Comment by Zze0** [comment]
翻了一下官方文档，（可能对于2.0是这么要求的）
spring.cloud.nacos.discovery.*的配置应该放置到application.yml/properties中。
spring.cloud.nacos.config.*的配置应该放置到bootstrap.yml/properties中。

这主要涉及到一个加载顺序的问题，discovery放到bootstrap配置文件中时，NacosDiscoveryProperties类无法成功加载到实际的配置，就采用自身默认的配置，所以serviceName是空的。

不知道我说的对不对。 @huhudiedie

**Comment by huhudiedie** [comment]
你是对的，我在application.yml中加上application.name就不会出现这个错误，但是出现其他错误了
    ![image](https://user-images.githubusercontent.com/67212456/115812658-49de1080-a424-11eb-86a2-ec89120e6f9b.png)
@Zze0

**Comment by huhudiedie** [comment]
非常感谢！ @Zze0

**Comment by KomachiSion** [comment]
这是Spring Cloud的设计，和Nacos关系不大。

**Comment by Zze0** [comment]
> 你是对的，我在application.yml中加上application.name就不会出现这个错误，但是出现其他错误了
> ![image](https://user-images.githubusercontent.com/67212456/115812658-49de1080-a424-11eb-86a2-ec89120e6f9b.png)
> @Zze0

其实不然，因为SpringCloud2020版本默认不启用bootstrap配置。需要在pom里面显式地引入：
```xml
<dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
```
这样配置就生效了，不关是不是用application.yml/properties的问题。
不知道你那边是个具体什么情况。但我这边引了这个包就正常了。

具体参见官方文档：https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-first-bootstrap

**Comment by huhudiedie** [comment]
@Zze0 哇，真的是这个问题，感谢大佬！

**Comment by huhudiedie** [comment]
感谢各位大佬！

**Comment by huazhiliange** [comment]
> > 你是对的，我在application.yml中加上application.name就不会出现这个错误，但是出现其他错误了
> > ![image](https://user-images.githubusercontent.com/67212456/115812658-49de1080-a424-11eb-86a2-ec89120e6f9b.png)
> > @Zze0
> 
> 其实不然，因为SpringCloud2020版本默认不启用bootstrap配置。需要在pom里面显式地引入：
> 
> ```
> <dependency>
>  <groupId>org.springframework.cloud</groupId>
>  <artifactId>spring-cloud-starter-bootstrap</artifactId>
> </dependency>
> ```
> 
> 这样配置就生效了，不关是不是用application.yml/properties的问题。
> 不知道你那边是个具体什么情况。但我这边引了这个包就正常了。
> 
> 具体参见官方文档：https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-first-bootstrap



> > 你是对的，我在application.yml中加上application.name就不会出现这个错误，但是出现其他错误了
> > ![image](https://user-images.githubusercontent.com/67212456/115812658-49de1080-a424-11eb-86a2-ec89120e6f9b.png)
> > @Zze0
> 
> 其实不然，因为SpringCloud2020版本默认不启用bootstrap配置。需要在pom里面显式地引入：
> 
> ```
> <dependency>
>  <groupId>org.springframework.cloud</groupId>
>  <artifactId>spring-cloud-starter-bootstrap</artifactId>
> </dependency>
> ```
> 
> 这样配置就生效了，不关是不是用application.yml/properties的问题。
> 不知道你那边是个具体什么情况。但我这边引了这个包就正常了。
> 
> 具体参见官方文档：https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-first-bootstrap

确实是这样，引入就正常了

**Comment by huazhiliange** [comment]
> > 你是对的，我在application.yml中加上application.name就不会出现这个错误，但是出现其他错误了
> > ![image](https://user-images.githubusercontent.com/67212456/115812658-49de1080-a424-11eb-86a2-ec89120e6f9b.png)
> > @Zze0
> 
> 其实不然，因为SpringCloud2020版本默认不启用bootstrap配置。需要在pom里面显式地引入：
> 
> ```
> <dependency>
>  <groupId>org.springframework.cloud</groupId>
>  <artifactId>spring-cloud-starter-bootstrap</artifactId>
> </dependency>
> ```
> 
> 这样配置就生效了，不关是不是用application.yml/properties的问题。
> 不知道你那边是个具体什么情况。但我这边引了这个包就正常了。
> 
> 具体参见官方文档：https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#config-first-bootstrap

确实是这样，引入就正常了

**Comment by Leowuqunqun** [comment]
这是因为spring boot 2.4x之后的版本 默认bootstrap失效，而nacos文档默认推荐配置在bootstrap，所以当你的版本升级了之后就会不好用

**Comment by ybasefinal** [comment]
我也遇到这个问题了，有点坑
