### ISSUE TITLE
Config tags cannot  be updated

### ISSUE THREAD

**Issue by hundanLi** [alibaba/nacos#5451]
**Describe the bug**
Config tags cannot  be updated.

**Expected behavior**
Config tags should be changed successfully.

**Acutally behavior**
The web page become whole white.

**How to Reproduce**
Edit config and clear old tags.

**Desktop (please complete the following information):**
 - OS: Ubuntu18.04
 - Version nacos-server 2.0.0
 - Module  config
 - SDK original

**Additional context**
Older versions also has the problem.

**Comment by brothelul** [comment]
@KomachiSion 这个问题我定位到了，我可以修复这个问题。
