### ISSUE TITLE
更新配置后，操作人未写入

### ISSUE THREAD

**Issue by liyanglin** [alibaba/nacos#5452]
**Describe the bug**
nacos控制台更新配置，然后查看历史版本的修改人，为空，数据库 his_config_info src_user 里面也没值，相当于没写进去

**Expected behavior**
更新配置，查看历史版本应该有修改人的字段值

**Acutally behavior**
更新配置，查看历史版本修改人的字段值始终为空

**Desktop (please complete the following information):**
nacos-server 2.0.0-bugfix (Mar 30th, 2021)
![image](https://user-images.githubusercontent.com/33758785/115685667-04213980-a38b-11eb-9ac9-f86ef2d9389c.png)

**Comment by KomachiSion** [comment]
未打开权限控制的时候，不会写入操作人。

detail #3548

**Comment by liyanglin** [comment]
> 未打开权限控制的时候，不会写入操作人。
> 
> detail #3548
权限控制已打开，添加了对应的角色，也分配了对应的权限
![image](https://user-images.githubusercontent.com/33758785/115697711-629fe500-a396-11eb-83f3-420f8f545632.png)
