### ISSUE TITLE
Some question about nacos server need ports

### ISSUE THREAD

**Issue by xhsky** [alibaba/nacos#5454]
After nacos cluster mode is started, three ports will be opened:
     8848 is the default web port
     7848 is the port of raft, how this port is specified by configuration rather than automatically calculated.
     There is also a random port, what is the port used for

**Comment by KomachiSion** [comment]
1. 7848 is calculate from 8848. the diff from main port can't config for now.
2. the random port maybe is UDP port. Used for received `naming` module UDP push ACK to get the data has push successfully.

**Comment by xhsky** [comment]
> 1. 7848 is calculate from 8848. the diff from main port can't config for now.
> 2. the random port maybe is UDP port. Used for received `naming` module UDP push ACK to get the data has push successfully.

Can this random port be customized? Or does it have to be random?
