### ISSUE TITLE
Not consider multiple project run on one user home after user nacos make file conflict. 

### ISSUE THREAD

**Issue by zxdposter** [alibaba/nacos#5459]
**Is your feature request related to a problem? Please describe.**
multiple project all use nacos, produce all at same place.

**Describe the solution you'd like**
please add some way, can split them.
I already try -DJM.LOG.PATH=${COMMON.BASE:-${HOME}/common}/logs/nacos/${PID} or -DJM.LOG.PATH=${COMMON.BASE:-${HOME}/common}/logs/nacos/${spring.application.name} 

I already try use ${spring.application.name},  but var will become spring.application.name_undefined

**Comment by KomachiSion** [comment]
I said in #5392, you need replace var in your `startup`. If you input var to application, vars can't be identified.

It is not nacos' problem, it's your problem.

If you do not how to replace var, I suggest you use hard code in you `startup` script.

**Comment by zxdposter** [comment]
@kakawei Now I know what you mean~

I should specify `spring.application.name` in my environment variable, because System.getProperty cannot get this var.

But I have two questions:
1. Why cannot doing like spring boot read var from bootstrap.yml, in spring boot bootstrap.yml can specify log file place.
2. Why nacos use self log system, not share log setting with spring boot? Maybe can use spring log setting manager nacos log output.

**Comment by zxdposter** [comment]
I use my way to solve this problem, also has effect on arthas project, there also have this problem.

first add config class
```java
package cn.server.framework.config;

import com.alibaba.cloud.nacos.NacosConfigBootstrapConfiguration;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;

import javax.annotation.PostConstruct;
import java.util.Objects;

@Configuration(proxyBeanMethods = false)
@AutoConfigureBefore(NacosConfigBootstrapConfiguration.class)
@AutoConfigureAfter(Environment.class)
@RequiredArgsConstructor
public class GlobalCommonVarConfig {
    private final Environment environment;

    private static final String APPLICATION_NAME_KEY = "spring.application.name";
    private static final String SERVER_COMMON_BASE_KEY = "SERVER_COMMON.BASE";
    private static final String SERVER_COMMON_BASE_VALUE = "${HOME}/server-common";
    private static final String ARTHAS_LOG_PATH_KEY = "ARTHAS_LOG_PATH";
    private static final String ARTHAS_LOG_PATH_VALUE = "${SERVER_COMMON.BASE:-${HOME}/server-common}/logs/arthas/${spring.application.name}";
    private static final String ARTHAS_OUTPUTPATH_KEY = "arthas.outputPath";
    private static final String ARTHAS_OUTPUTPATH_VALUE = "${SERVER_COMMON.BASE:-${HOME}/server-common}/arthas-output/${spring.application.name}";
    private static final String RESULT_LOG_FILE_KEY = "RESULT_LOG_FILE";
    private static final String RESULT_LOG_FILE_VALUE = "${SERVER_COMMON.BASE:-${HOME}/server-common}/logs/arthas-cache/${spring.application.name}/${spring.application.name}-result.log";
    private static final String JM_LOG_PATH_KEY = "JM.LOG.PATH";
    private static final String JM_LOG_PATH_VALUE = "${SERVER_COMMON.BASE:-${HOME}/server-common}/logs/nacos/${spring.application.name}";
    private static final String JM_SNAPSHOT_PATH_KEY = "JM.SNAPSHOT.PATH";
    private static final String JM_SNAPSHOT_PATH_VALUE = "${SERVER_COMMON.BASE}/config";

    @PostConstruct
    public void initEnv() {
        System.setProperty(APPLICATION_NAME_KEY,
                Objects.requireNonNull(environment.getProperty(APPLICATION_NAME_KEY)));

        if (!System.getProperties().containsKey(SERVER_COMMON_BASE_KEY)) {
            System.setProperty(SERVER_COMMON_BASE_KEY, environment.resolvePlaceholders(SERVER_COMMON_BASE_VALUE));
        }

        System.setProperty(ARTHAS_LOG_PATH_KEY,
                environment.resolvePlaceholders(ARTHAS_LOG_PATH_VALUE));
        System.setProperty(ARTHAS_OUTPUTPATH_KEY,
                environment.resolvePlaceholders(ARTHAS_OUTPUTPATH_VALUE));
        System.setProperty(RESULT_LOG_FILE_KEY,
                environment.resolvePlaceholders(RESULT_LOG_FILE_VALUE));
        System.setProperty(JM_LOG_PATH_KEY,
                environment.resolvePlaceholders(JM_LOG_PATH_VALUE));
        System.setProperty(JM_SNAPSHOT_PATH_KEY,
                environment.resolvePlaceholders(JM_SNAPSHOT_PATH_VALUE));
    }
}
```


second  in `spring.factories`
```java
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
    cn.server.framework.config.GlobalCommonVarConfig
```

**Comment by KomachiSion** [comment]
Because nacos-client is a sdk, should not bind to spring.

**Comment by KomachiSion** [comment]
But as the properties increment, It is a enhancement for nacos-client to has one Unified way to get properties.

**Comment by zxdposter** [comment]
Maybe can simulate log ouput like jackson or spring-security or someothers, they not use log setting, only print log, let user decision log setting.
I can understand set up the config directory location,but not understand  set up log, it means I have two log system in my project.

**Comment by KomachiSion** [comment]
There are many different with jackson, spring framework.  They are sync usage for users, and they usually are in the main logic of users. Their error and logs print to application log of users is better. So their logging is completely load by users log config.

But nacos is a service registery, which is asynchronous featrures and a lot of content are on non-main logic, for example heartbeat or longpulling. So Nacos' log is not suitable to print application logs. So we set an default log path of nacos to avoid. And add some properties to make it configurable.

**Comment by zxdposter** [comment]
Ok, thanks for answer, now I understand your point of view~
