### ISSUE TITLE
cant control namespace read and write by role setting?

### ISSUE THREAD

**Issue by yankai913** [alibaba/nacos#5460]
version : 2.0.0-bugfix
description: i add  a new user named "test_user", add three new namespaces "test", "uat"and "prd",  add a new role named "ROLE_DEV" which only can read and write the "test" namespace. when  i use "test_user" to login in, i also can see other namespace "uat" , "prd" expect "test", is it sth wrong?

**Comment by yankai913** [comment]
i have granted ROLE_DEV to test_user

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/auth.html

**Comment by KomachiSion** [comment]
you can see the namespace in controller, but when you try to entry other namespace or access the resource of other namespace, you will get 403.

Of cource, you should open auth. Otherwise you can do anything with any user.
