### ISSUE TITLE
Questions about the use of data sources

### ISSUE THREAD

**Issue by xhsky** [alibaba/nacos#5461]
1. In cluster mode, using derby and MySQL as data sources respectively, what is the performance gap? Is there any hidden danger?
2. If MySQL is used as the data source, does it support the connection mode of MySQL mgr cluster?
3. The document recommends the use of MySQL master-slave mode, is the nacos connection still using the stand-alone mode connection?

**Comment by JackSun-Developer** [comment]
1. There is a performance report for mysql based Nacos, https://nacos.io/zh-cn/docs/nacos2-config-benchmark.html
**Derby based** nacos performance is not reported, but it may be inferior to **mysql based** nacos.

**Comment by JackSun-Developer** [comment]
> The document recommends the use of MySQL master-slave mode, is the nacos connection still using the stand-alone mode connection?

3. Currently Nacos does support master-slave and you can configure both **the master mysql address and slave mysql address** in nacos.

**Comment by xhsky** [comment]
> > The document recommends the use of MySQL master-slave mode, is the nacos connection still using the stand-alone mode connection?
> 
> 1. Currently Nacos does support master-slave and you can configure both **the master mysql address and slave mysql address** in nacos.

**Comment by xhsky** [comment]
> > The document recommends the use of MySQL master-slave mode, is the nacos connection still using the stand-alone mode connection?
> 
> 1. Currently Nacos does support master-slave and you can configure both **the master mysql address and slave mysql address** in nacos.

I see the configuration of multiple data sources on the document, is the MySQL master-slave configured here? What is the specific usage mode after multi-data source configuration?

**Comment by KomachiSion** [comment]
multiple data sources is means that support many kinds of datasource. No support more than one datasource at the same time.

MySQL master-slave configured is a failover feature, If the master down, and there are a slave MySQL. Nacos can use the slave to public and get configuration.

But the design seems out of date, we may remove it in future.

**Comment by xhsky** [comment]
> multiple data sources is means that support many kinds of datasource. No support more than one datasource at the same time.
> 
> MySQL master-slave configured is a failover feature, If the master down, and there are a slave MySQL. Nacos can use the slave to public and get configuration.
> 
> But the design seems out of date, we may remove it in future.

If I want to use HA mode data source, does Nacos support MySQL Router + Mgr mode ?

**Comment by KomachiSion** [comment]
It depend your HA mode implementation. Nacos support master-slave mode and auto switch in nacos.

If you use MySQL HA cluster, you need change the url and make sure this url can switch and route to right MySQL. Nacos just use this url as JDBC.

**Comment by WywTed** [comment]
> It depend your HA mode implementation. Nacos support master-slave mode and auto switch in nacos. You need config one master url of MySQL and multiple slave url of MySQL in `application.properties`.

look int this: https://github.com/nacos-group/nacos-docker/issues/76
Does nacos still support master-slave  mysql? If do, where can i find the document  about the configuration.

**Comment by WywTed** [comment]
> > The document recommends the use of MySQL master-slave mode, is the nacos connection still using the stand-alone mode connection?
> 
> 1. Currently Nacos does support master-slave and you can configure both **the master mysql address and slave mysql address** in nacos.

Where is the guide to config  master address and slave address.
