### ISSUE TITLE
Nacos支持zkclient.sh/etcdctl这样的命令行方式，黑屏操作比较方便

### ISSUE THREAD

**Issue by TsingLiang** [alibaba/nacos#5462]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by JackSun-Developer** [comment]
Good idea, @TsingLiang Welcome to join Nacos community to contribute to this feature.

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-ctl
