### ISSUE TITLE
spring-cloud-alibaba.version2.2.5.RELEASE 配置namespace和group无效

### ISSUE THREAD

**Issue by jgswp** [alibaba/nacos#5463]
在nacos页面创建分组和命名空间，在springboot里面配置分组一直读取不到
<img width="862" alt="图片" src="https://user-images.githubusercontent.com/35256326/115823697-591b8900-a439-11eb-88c2-92ba7a69a7e6.png">

这里需要填写的是
<img width="670" alt="图片" src="https://user-images.githubusercontent.com/35256326/115823762-76505780-a439-11eb-8098-754743401238.png">
里面的namespace 的id，
开发在配置文件里面写肯定是创建的namespace 而不是一串md5值
md5值在代码里面不具备可读性
希望能改善下换成配置的namespace和不是namespace 的id

**Comment by jgswp** [comment]
问题解决了 直接改db里面的租户id，就可以，但是还是希望你们能改善下
<img width="1637" alt="图片" src="https://user-images.githubusercontent.com/35256326/115823895-bc0d2000-a439-11eb-9bd0-d62a013b3bbc.png">

**Comment by CherishCai** [comment]
创建命名空间的时候，可以指定 id

**Comment by KomachiSion** [comment]
1.2版本后可以自定义namespaceId。
