### ISSUE TITLE
nacos 配置 spel 表达式偶现为 空

### ISSUE THREAD

**Issue by Johnson-Jia** [alibaba/nacos#5465]
nacos 配置中心  ,代码如下 ，偶现list 对象为空对象。
```
    @Value("#{'${csm.select.default.extension.moduleCode}'.split(',')}")
    private List<String> defaultSelectExtensionModuleCodes;
```
nacos  1.4.1 
nacos-client 1.4.1
spring-boot 2.2.13
spring-cloud-alibaba 2.2.5

**Comment by JackSun-Developer** [comment]
您好，Value是SpringBoot自带的注解，报这个错应该是您SpringBoot的使用方法有误。

NacosValue才是Nacos-spring提供的注解。

**Comment by KomachiSion** [comment]
Spring Cloud的问题请提到Spring cloud alibaba 社区

**Comment by Johnson-Jia** [comment]
@KomachiSion   但是问题现象是，nacos 配置中心服务端 随便加个空格 重新提交下对应的 properties 就没问题了，可以正常解析。
