### ISSUE TITLE
nacos2.0 protocol/raft_meta里，有节点显示.0.0.0:0

### ISSUE THREAD

**Issue by evaxiang** [alibaba/nacos#5471]
protocol/raft_meta里，如：data/protocol/raft/naming_service_metadata/meta-data/raft_meta
有个nacos节点数据是.0.0.0:0
其他节点数据是：jraft.StablePBMeta1nacos-1.nacos-headless.ops.svc.cluster.local:7848  （leader的地址？）

这个是集群有问题吗？ 还是本来如此？

**Comment by KomachiSion** [comment]
raft_meta是Jraft写入的元数据， Nacos并不清楚记录的这个结果是否正确。

您可以从控制台看下Nacos的元数据，看下是否正确，如果正确的，这个内容就不需要关心了。

**Comment by evaxiang** [comment]
> raft_meta是Jraft写入的元数据， Nacos并不清楚记录的这个结果是否正确。
> 
> 您可以从控制台看下Nacos的元数据，看下是否正确，如果正确的，这个内容就不需要关心了。

我理解，里面记录的是选举leader后的信息，0.0.0.0的就是选举失败的那个节点，是这样吗？

**Comment by KomachiSion** [comment]
里面记录的是该raft-group的一些元数据信息， 具体0.0.0.0是什么含义，需要到Jraft社区求解，Nacos作为Jraft的使用方，并不关心Jraft的元数据存储的是什么。
