### ISSUE TITLE
2.0版本经常服务注册进去了列表没显示啊

### ISSUE THREAD

**Issue by lingdu990130556** [alibaba/nacos#5473]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by lingdu990130556** [comment]
集群启动的时候服务列表为空

**Comment by KomachiSion** [comment]
麻烦在issue模版详细填写一下问题描述，否则完全不知道是什么问题。

**Comment by lingdu990130556** [comment]
> 麻烦在问题模版详细填写一下问题描述，否则完全不知道是什么问题。

就是我之前用的是1.3.2 集群启动的 后来替换成2.0集群启动后项目启动总是报com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later! 但是直接访问nacos控制台是没有问题的能进去

**Comment by lingdu990130556** [comment]
> > 麻烦在问题模版详细填写一下问题描述，否则完全不知道是什么问题。
> 
> 就是我之前用的是1.3.2启用启动的后来替换成2.0复制启动后项目启动总是报com.alibaba.nacos.api.exception.NacosException：服务器现在关闭，请稍后重试！但是直接访问nacos控制台是没有问题的能进去

集群启动的

**Comment by MajorHe1** [comment]
> > 麻烦在问题模版详细填写一下问题描述，否则完全不知道是什么问题。
> 
> 就是我之前用的是1.3.2 集群启动的 后来替换成2.0集群启动后项目启动总是报com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later! 但是直接访问nacos控制台是没有问题的能进去

控制台进去后，按F12，看网络通信，你还是能看到有的请求是失败的，com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later
重复的ISSUE #5361 

查看 https://nacos.io/zh-cn/docs/2.0.0-compatibility.html FAQ

**Comment by KomachiSion** [comment]
Can you use 2.0.1 version retry?

**Comment by KomachiSion** [comment]
No response from author for a long time , so we think new version has solve this problem.
