### ISSUE TITLE
[Enhancement] Configuration rollback add hint.

### ISSUE THREAD

**Issue by haoyann** [alibaba/nacos#5475]
**Is your feature request related to a problem? Please describe.**
When the configuration is rolled back, the configuration will be deleted if the operation type is insert, users will feel a little confused. I think a hint can be added, like this: 
![image](https://user-images.githubusercontent.com/43994656/115960693-776eab00-a545-11eb-8521-a2d44b4e072b.png)
Refer to : #4064 , #2731 ,#5358
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JackSun-Developer** [comment]
![image](https://user-images.githubusercontent.com/58767027/115977752-6e192900-a5ad-11eb-8a14-1c4d54d24819.png)
Nacos have already this hint, I think this hint is enough.

**Comment by KomachiSion** [comment]
I think this hint is an enhancement for users.

If console can judgement rightly and hint will be better.

And we also add some description in document to explain why rollback the first config will delete config.

**Comment by brothelul** [comment]
I will work on this feature and add the description in domcument.
