### ISSUE TITLE
The information of InstancesChangeEvent and NamingEvent is not enough

### ISSUE THREAD

**Issue by zzlInGitHub** [alibaba/nacos#5480]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I got a InstancesChangeEvent or NamingEvent like an instance is downed from nacos,but I didn't know which instance it was.

**Describe the solution you'd like**
I want that the InstancesChangeEvent and NamingEvent what I subscribe from nacos can give me more information,like which instance is downed,what is the ip and port of the instance.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/33978065/115978843-f5b66600-a5b4-11eb-9041-88a2f6581b28.png)

**Comment by KomachiSion** [comment]
For most of usage like RPC or application framework do not pay attention to which instance down or up. They are care about current instance list of specified services. So the InstancesChangeEvent is return the newest instance list to listener.

If you must get the changed instance. you should cache the older instance list and compare with new one by yourself.

**Comment by KomachiSion** [comment]
For gateway, I think is same as RPC or application framework. Only need new instance list, is not care about which down or up. Just use new one to replace old one.

**Comment by zzlInGitHub** [comment]
> For most of usage like RPC or application framework do not pay attention to which instance down or up. They are care about current instance list of specified services. So the InstancesChangeEvent is return the newest instance list to listener.
> 
> If you must get the changed instance. you should cache the older instance list and compare with new one by yourself.

As you noted,I can cache the older instance list and compare with new one by myself.but when the gateway init,I can only get the instances from DiscoveryClient and it return ServiceInstance to me.It is troublesome to transform ServiceInstance to Instance because they are unconnected.And you had already did those things:
![image](https://user-images.githubusercontent.com/33978065/115983079-b21e2500-a5d1-11eb-8e9f-c5cbac97e37a.png)

So I think that modify the InstancesChangeEvent seem to be a better way.

**Comment by KomachiSion** [comment]
No, we don't think is better way. 

client do this filter is to reduce the ChangeEvent. Only the instance list changed will give an event for new instance list.

For most of discovery situation, the event of newest instance is better.

Of cource, you can modified client and event, then build and use by yourself.
