### ISSUE TITLE
mac系统启动失败

### ISSUE THREAD

**Issue by 993235078** [alibaba/nacos#5489]
<img width="1088" alt="WechatIMG37" src="https://user-images.githubusercontent.com/43432778/115986494-07aefd80-a5e3-11eb-81a3-e2456906a40f.png">
**Describe the bug**
启动失败，具体异常参考图片

**Expected behavior**
正常启动应用

**Acutally behavior**
服务启动失败

**How to Reproduce**
1. git下载，解压
2. cd /.../nacos/bin
3. sh startup.sh -m standalone

**Desktop (please complete the following information):**
 - OS: macos big sur 11.0
 - Version nacos-server-2.0.0-bugfix

**Additional context**
nothing

**Comment by KomachiSion** [comment]
duplicate with #4336
