### ISSUE TITLE
When publish Beta, the tags\description\type of config are lose. 

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5494]
**Describe the bug**
When publish Beta, the tags\description\type of config are lose. 
like below:
origin content
![image](https://user-images.githubusercontent.com/25661357/115996037-51620d00-a610-11eb-94f2-a2cd36e96021.png)
beta content
![image](https://user-images.githubusercontent.com/25661357/115996059-66d73700-a610-11eb-9932-b755d0553322.png)

**Expected behavior**
should keep the same as origin content, otherwise the content or the changes in Beta page will lost when we publish the config in Beta page.

**Acutally behavior**
As the question description.

**How to Reproduce**
1. Go to 'edit the config' in console
2. publish beta
3. compare the origin content and beta content.

**Desktop (please complete the following information):**
 - OS:  windows
 - Version 1.4.2-SNAPSHOT
 - Module console

**Additional context**
If we need to fix this problem, please assign it to me. I will follow this problem and solve it.

**Comment by haoyann** [comment]
I find `com.alibaba.nacos.config.server.service.repository.PersistService#findConfigInfo4Beta` lost this message. 
https://github.com/alibaba/nacos/blob/81c1e53ac6c6d99f81a066c29ce26eb2f266ae4d/config/src/main/java/com/alibaba/nacos/config/server/service/repository/embedded/EmbeddedStoragePersistServiceImpl.java#L690-L692

**Comment by brothelul** [comment]
yes, config type also lost. I think the  missing of config type is more important than other field, when we use nacos spring the missing will cause parse exception. 
![image](https://user-images.githubusercontent.com/25661357/116221794-868d6d00-a780-11eb-9dda-1a084e249698.png)

**Comment by brothelul** [comment]
config type also has the same problem.
