### ISSUE TITLE
Configuration may not take effect, but the client and config server are not aware of it

### ISSUE THREAD

**Issue by XCXCXCXCX** [alibaba/nacos#550]
# Reporting bugs
version 0.7.0

This may not be a bug, but I think we should do better.

// 这可能算不上bug，但我认为应该做的更好 

Because the way to pull the configuration is http request, there may be network anomalies and other reasons for the failure of the request, the result of the request is not seen on the client console, and it is impossible to determine whether the configuration is effective on the Nacos console.

// 由于拉取配置的方式是http请求，可能存在网络异常等原因请求失败，在客户端控制台上没有看到请求结果，在nacos控制台上也无法确定该配置是否生效 

# Expect effect
It is hoped that the client can provide information on whether the configuration is successful or save a list of valid instances in config server to show the effect in the Nacos console.

// 希望可以在客户端提供配置是否拉取成功的信息，或者是在config server保存一份已生效instance列表，在nacos控制台展示效果。

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by hxy1991** [comment]
赞，不错的想法。

**Comment by nkorange** [comment]
该需求需要额外的组件来存储推送的轨迹，目前开源暂时不会考虑。
