### ISSUE TITLE
DataId and  Group lost  in Ip query option mode

### ISSUE THREAD

**Issue by brothelul** [alibaba/nacos#5517]
**Describe the bug**
the Ip query option mode the DataId and  Group lost  when we swith the option 配置 to IP 
配置选项结果：
 
![image](https://user-images.githubusercontent.com/25661357/116264672-121cf300-a7ad-11eb-9ae8-35fd74c7ac83.png)

切换为IP结果：
![image](https://user-images.githubusercontent.com/25661357/116264754-2660f000-a7ad-11eb-83e4-296db10cfe39.png)

**Expected behavior**
donot show the data or complete the Group and DataId

**Acutally behavior**
the Group and DataId lost in IP query option.

**How to Reproduce**
1. Go to '监听查询'
2. Click on '查询维度，切换为IP'
3. See the data table.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [the lasted]
 - Module [console]

**Additional context**
no

**Comment by brothelul** [comment]
I find that the result of IP query is loaded from 配置 query result. maybe we need to add a new default IP value to search the result when we switch the query option.

**Comment by drgnchan** [comment]
maybe it is not lost,but not clearing the result after changing the query type.
