### ISSUE TITLE
Add unit tests to package com.alibaba.nacos.naming.controllers in nacos 2.0

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5519]
This is a sub-issue of #4982

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tangyunxun** [comment]
@I will solve it@

**Comment by brotherlu-xcq** [comment]
@tangyunxun Do you still work on this? if no, I will continue the left work.
