### ISSUE TITLE
Add unit tests for package com.alibaba.nacos.naming.core.v2.cleaner in nacos2.0

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5520]
sub-issue of #4983

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by JackSun-Developer** [comment]
@ i will solve it@

**Comment by brotherlu-xcq** [comment]
@realJackSun If you are busy on other work, you can assign it to me.
