### ISSUE TITLE
建议集群状态还是现实谁是leader等

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/nacos#5523]
建议这个地方还是显示具体集群角色，是leader等标记清楚好些

![image](https://user-images.githubusercontent.com/62740686/116350317-51d2f180-a824-11eb-8a48-fcac3468705e.png)

**Comment by KomachiSion** [comment]
Raft协议有RaftGroup的概念， 每一个RaftGroup都有自己的leader，可能Node1是某一个Raftgroup的leader，但是是另一个group的follower，所以这怎么统一标记呢？

**Comment by chuntaojun** [comment]
其实nacos本身是不存在Leader还是Follower的概念的，是里面提供的一些服务存在Leader和Follower的概念，所有nacos节点对外（即对用户侧来说）都是一样的
