### ISSUE TITLE
org.apache.dubbo.rpc.RpcException: No provider available in

### ISSUE THREAD

**Issue by hqfgithub** [alibaba/nacos#5531]
org.apache.dubbo.rpc.RpcException: No provider available in

**Comment by hqfgithub** [comment]
用的是 albaba dubbo  消费端重启报找不到服务

**Comment by brothelul** [comment]
可以提供以下你的dubbo版本还有nacos版本吗？

**Comment by KomachiSion** [comment]
能否看一下nacos的客户端日志，看一下是否有订阅需要的provider，如果有订阅是否有收到ip列表。

**Comment by hqfgithub** [comment]
> 可以提供以下你的dubbo版本还有nacos版本吗？

我用的是  spring-cloud-alibaba-dependencies 2.2.1版本   我升级到最新版本   问题解决了
