### ISSUE TITLE
nacos 2.0长连接技术方案疑问

### ISSUE THREAD

**Issue by jixue** [alibaba/nacos#5537]
你好，最近看了这篇文章，https://mp.weixin.qq.com/s/dBVo6w0sjUORd6Axpj3zTg，
咨询下nacos2.0长连接方案为什么使用grpc，不使用websocket呢？

**Comment by CliffsideZhai** [comment]
https://www.cnblogs.com/kirito-c/p/10360309.html
希望对你有帮助

**Comment by KomachiSion** [comment]
主要是综合考虑了应用场景、多语言适配难度、社区发展程度和活跃度，最终选择了gRPC作为默认实现。

**Comment by jixue** [comment]
> https://www.cnblogs.com/kirito-c/p/10360309.html
> 希望对你有帮助

好的 我看一下～ 感谢
