### ISSUE TITLE
There are some failed test cases

### ISSUE THREAD

**Issue by SunJiFengPlus** [alibaba/nacos#5538]
**Describe the bug**
![图片](https://user-images.githubusercontent.com/39667700/116557071-afecfb00-a930-11eb-8004-56c793f9de7b.png)

![图片](https://user-images.githubusercontent.com/39667700/116557325-eb87c500-a930-11eb-9225-e334ea9781c9.png)

If it passes, I can do this.

**Comment by JackSun-Developer** [comment]
@ i will solve it@

**Comment by KomachiSion** [comment]
@KeRan213539 Please check it

**Comment by KomachiSion** [comment]
There are two PR for this issue? @KeRan213539 @SunJiFengPlus We need discuss first how to fix it.
