### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by mostcool** [alibaba/nacos#554]
docker-compose.yml
![image](https://user-images.githubusercontent.com/2172570/50584289-a448b100-0ea9-11e9-9a30-9c5e64d2e10e.png)

In CentOS 7.4 run docker-compose up-d to report errors:
 standard_init_linux.go:190: exec user process caused "no such file or directory"
What's the matter?

![image](https://user-images.githubusercontent.com/2172570/50584973-a7de3700-0ead-11e9-902e-ba805c9c18d9.png)
![image](https://user-images.githubusercontent.com/2172570/50584981-af054500-0ead-11e9-90c8-32a18c57946d.png)

**Comment by xuechaos** [comment]
Are you using a nacos-docker image? If you build it yourself, you need to pay attention to whether the shell is compatible with "#!/bin/sh" in the base image. It may not be suitable.
