### ISSUE TITLE
the nacos architecture now is rubbish 

### ISSUE THREAD

**Issue by wei7202839** [alibaba/nacos#5540]
The best architecture  should be a nice combination of vipserver and sofaRegistry，but now , current version of nacos is
rubbish
i can easily list some reasons to prove my judgment:
1.  DistroConsistencyServiceImpl can easily cause an OOM exception when the EphemeralData become larger and larger, you know, in service discovery and registry scene, the EphemeralData contribute the majority  amount of naming data，sofaRegistry design a session layer to resove this problem，nacos shoud copy it

2.  muti-group raft protocol is not supported，unlike tidb, each shard need a raft group；however，in my opinion, leveldb with master-slave sync-renew and version control may be a better choice than raft protocol

3. client-side heartbeat report and server-side heathCheck shoud be  isolated strictly，one for Ephemeral scene and anther for persist，server-side heathCheck machines shoud be an independent cluster because sessionNode and dataNode both may have a  heavy load

**Comment by JackSun-Developer** [comment]
> client-side heartbeat report and server-side heathCheck shoud be isolated strictly，one for Ephemeral scene and anther for persist，server-side heathCheck machines shoud be an independent cluster because sessionNode and dataNode both may have a heavy load

Actually, nacos is designing the Support for serviceMesh, i think this feature can be supported after that.

**Comment by JackSun-Developer** [comment]
> 2. muti-group raft protocol is not supported，unlike tidb, each shard need a raft group；however，in my opinion, leveldb with master-slave sync-renew and version control may be a better choice than raft protocol

Multi-group may bring higher load capacity, but also higher opearate cost. Anyway, this seems a reasonable proposal, you could open this up in another ISSUE.

**Comment by wei7202839** [comment]
i know in k8s stateless eviroment, many things become difficult
this issue is only for your reference
thanks for your attention and reply
