### ISSUE TITLE
How to know the instanceId of the current app?

### ISSUE THREAD

**Issue by woohanhan** [alibaba/nacos#5543]
App needs to know its own instanceId.But I can’t find a proper way to do it.

Is there a certain rule to know the instanceId of the current app from the instanceId list?

thx

**Comment by KomachiSion** [comment]
In nacos, instanceId is generated by server part for now. You can specified the instance id by yourself when you register it.

If you do not set, server will generated by serviceName, ip, port. 

For Nacos, the instanceId is not the content that should be obtained, but the content that needs to be set.

**Comment by LongCodeShort** [comment]
how to specified it?
