### ISSUE TITLE
[Question] `com.alibaba.nacos.naming.core.CatalogServiceV2Impl#pageListServiceDetail` is empty

### ISSUE THREAD

**Issue by haoyann** [alibaba/nacos#5544]
### Describe what happened (or what feature you want)
I find  `com.alibaba.nacos.naming.core.CatalogServiceV2Impl#pageListServiceDetail` is empty method. Doesn't it need to be implemented or is it omitted
https://github.com/alibaba/nacos/blob/ef15888658eeb0a37672d27d3cec23daa6a80ec7/naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java#L164-L167

**Comment by KomachiSion** [comment]
During my refactor for nacos 2.0. I found this API is not called by console. And this CatalogService is just for console. But I'm not sure whether no others use this API. So I do not implement. If upgrade to 2.1.0, and no other response for using this API, I will remove it.

**Comment by haoyann** [comment]
Get it.
