### ISSUE TITLE
1.4.2 + k8s ，集群启动时，节点投票抛出vote failed: 500

### ISSUE THREAD

**Issue by julingpu** [alibaba/nacos#5553]
背景
nacos版本：1.4.2
集群启动时，节点投票抛出vote failed: 500，导致无法选主成功，节点之间可以ping通
![image](https://user-images.githubusercontent.com/13026222/116674541-5c81b800-a9d7-11eb-9370-8c74c4ece763.png)

**Comment by JackSun-Developer** [comment]
您好，您的集群中是不是新老版本并存呢？我看到您的日志中有1.3.x以下的旧版本的raft报错。

**Comment by julingpu** [comment]
并没有哇，都是1.4.2

**Comment by julingpu** [comment]
另外在nacos.log里面发现如下日志：ip: 10.18.0.18:8848 is not in serverlist

**Comment by JackSun-Developer** [comment]
那alipay.log 和 nacos.log和protocol-raft.log 和cluster.conf 可以提供一下吗
最好把所有的日志都上传到云盘里，分享给我

**Comment by julingpu** [comment]
日志：https://share.weiyun.com/8yjbofJm

cluster.conf 
![image](https://user-images.githubusercontent.com/13026222/116684203-424dd700-a9e3-11eb-90f2-aff09fb5e650.png)

**Comment by JackSun-Developer** [comment]
分析是有老的data目录残留导致的，可以把~/nacos/data删除掉之后，重试

**Comment by julingpu** [comment]
请问nacos.inetutils.prefer-hostname-over-ip=false这个配置有问题么？

**Comment by julingpu** [comment]
另外1.4.2版本编译后的目录结构是什么样的？不应该有data目录是么？

**Comment by julingpu** [comment]
另外还有个问题：我本地在cluster.conf中配置了
localhost:8848
localhost:8849
localhost:8850

但是我启动之后cluster.conf里面有增加了一行LAPTOP-QFGB3CA7:8848
这个是什么原因？

**Comment by julingpu** [comment]
@JackSun-Developer  求赐教上面两个问题

**Comment by JackSun-Developer** [comment]
> 请问nacos.inetutils.prefer-hostname-over-ip=false这个配置有问题么？

如果cluster.conf里面希望用域名(hostname)配置，就把它设置为true；如果cluster.conf里面希望用IP配置，就把它设置为false。
这是这个配置的含义。

**Comment by JackSun-Developer** [comment]
> 另外还有个问题：我本地在cluster.conf中配置了
> localhost:8848
> localhost:8849
> localhost:8850
> 
> 但是我启动之后cluster.conf里面有增加了一行LAPTOP-QFGB3CA7:8848
> 这个是什么原因？

Nacos有一个寻址机制：当它无法在cluster.conf中查找到本机IP时，就会把本机IP添加进去。

这可能是因为，您把上述那个配置设置成false，导致了nacos无法识别cluster.conf，所以强行加了一个本机IP。您可以修改一下配置nacos.inetutils.prefer-hostname-over-ip，或者干脆把cluster.conf中全部替换为127.0.0.1再试试

**Comment by JackSun-Developer** [comment]
另外，nacos不支持localhost，建议换成本机的IP地址。@julingpu

**Comment by KomachiSion** [comment]
Way 1: modified application.properties

```
nacos.inetutils.prefer-hostname-over-ip=true
nacos.inetutils.ip-address=localhost
```

Way 2:  add JVM properties

```
-Dnacos.server.ip=localhost

```

**Comment by 294033186** [comment]
我也遇到了相同的问题，我的问题是集群节点之间的7848端口忽然就不通了，导致了出这个错误，端口通了我得问题就解决了
