### ISSUE TITLE
recruit a core maintenance member of the official website 

### ISSUE THREAD

**Issue by xuechaos** [alibaba/nacos#556]
The Nacos community is now recruiting a core maintenance member of the official website https://nacos.io, which needs to maintain the activity of https://nacos.io and is responsible for updating and maintaining the information of nacos.io, including
1. Blog update & version update
2. Document update and maintenance
We will add you directly to the nacos-group group members and give priority to becoming a Committer. Thank you for reading, welcome to build.
The Nacos community is now recruiting a core maintenance member of the official website https://nacos.io. It needs to maintain the activity of https://nacos.io and is responsible for updating and maintaining the information of nacos.io, including

Nacos社区现在招募一名官方网站 https://nacos.io 的核心维护成员，需要保持https://nacos.io的活跃度，并负责nacos.io的信息更新和维护，包括
1. blog的更新& 版本的更新
2. 文档的更新和维护

我们会把你直接加入到nacos-group的组成员，优先推荐成为Committer。感谢你的阅读，欢迎你共建。

**Comment by XCXCXCXCX** [comment]
如何参与？有哪些要求呢？

**Comment by huangyunbin** [comment]
我有兴趣。之前阅读nacos源码的时候，自己也写过一些blog

**Comment by xuechaos** [comment]
@XCXCXCXCX 找我报名就好 微信 xxc-2426 或者 钉钉群 ，要求主要是能保持信息更新，和官网的演进。👍

**Comment by xuechaos** [comment]
@huangyunbin 那太好了，也联系我一下，我们可以沟通一下细节。

**Comment by XCXCXCXCX** [comment]
> @XCXCXCXCX 找我报名就好 微信 xxc-2426 或者 钉钉群 ，要求主要是能保持信息更新，和官网的演进。👍

添加了哦~
是不是目前人选已经确定下来了，还没有通过~

**Comment by xuechaos** [comment]
@XCXCXCXCX 并没有呢

**Comment by lywlefan** [comment]
@xuechaos 有确定下来没？我有信心把这件事做好

**Comment by lywlefan** [comment]
@xuechaos I'd like to help. I'm sure I can do it well

**Comment by nkorange** [comment]
@caojiele 目前是主要的维护者，@lywlefan你也可以开始贡献你的PR

**Comment by caojiele** [comment]
> @xuechaos I'd like to help. I'm sure I can do it well

Hi, nice to meet you, welcome to build ecological Nacos website！
