### ISSUE TITLE
2.0版本做了集群之后服务列表点击服务详情报错

### ISSUE THREAD

**Issue by 13039223364** [alibaba/nacos#5569]
**Cluster**

**Describe the bug**
2.0版本做了集群之后服务列表点击服务详情报错
三台服务器
10.199.12.26【Nginx】
10.199.12.32【Nacos-1】
10.199.12.41【Nacos-2】
通过访问10.199.12.26:8848[【Nginx】

**查看日志**
10.199.12.32：8848【Nacos-1】
10.199.12.41：8848【Nacos-2】
查看一下/usr/local/nacos/log/nacos.log
![image](https://user-images.githubusercontent.com/39184216/117099468-d634ef80-ada3-11eb-934f-667d3f1a90e8.png)
![image](https://user-images.githubusercontent.com/39184216/117099474-dc2ad080-ada3-11eb-8098-150c670dba90.png)
报错如下

**配置**
其余配置都是按照文档配置
并且在集群管理--》节点列表
![image](https://user-images.githubusercontent.com/39184216/117099550-0b414200-ada4-11eb-921e-baca3e681e3a.png)
状态都是Up

请教各位老师，这个怎么解决？？

**Comment by 13039223364** [comment]
![image](https://user-images.githubusercontent.com/39184216/117105209-25811d00-adb0-11eb-8dd9-a10fec56a4f6.png)
![image](https://user-images.githubusercontent.com/39184216/117105220-2b76fe00-adb0-11eb-8e29-8af0af7f5bc0.png)

**Comment by JackSun-Developer** [comment]
您好，可否提供一下alipay-jraft.log，看一下日志里面报什么错误。

**Comment by lpaz010** [comment]
[官网文档](https://nacos.io/zh-cn/docs/deployment.html)->集群部署说明->预备环境准备，小节里指出**3个或3个以上Nacos节点才能构成集群（3 or more Nacos Nodes）**。

为什么3台服务器有2台是nacos服务器，这是我的疑问哈。

**Comment by KomachiSion** [comment]
报错一直显示服务端之间的grpc连接无法建立， 你看下是否是9849端口没有无法通信

关于端口可以看下这个文档 https://nacos.io/en-us/docs/2.0.0-compatibility.html
