### ISSUE TITLE
the result of get node list in cluster mode using nacos-k8s is different from using nacos-docker

### ISSUE THREAD

**Issue by zcz3313** [alibaba/nacos#5572]
**Describe the bug**
succeed in nacos-docker, failed in nacos-k8s

**Expected behavior**
same as in nacos-docker
![image](https://user-images.githubusercontent.com/8746495/117237262-2328cc80-ae5d-11eb-850e-e9ecb6040f6a.png)

**Acutally behavior**
failed in nacos-k8s
![image](https://user-images.githubusercontent.com/8746495/117236952-6afb2400-ae5c-11eb-832e-819d1af7f928.png)

**How to Reproduce**
1. deploy 3 replicas in cluster mode and embeded storage using nacos-k8s
2. login web-console
3. click ‘get node list’ of cluster manager.

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 1.4.1]
 - Module [naming/config]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**
1. the request api in nacos-docker is '/nacos/v1/core/cluester/nodes' 
2. the request api in nacos-k8s is 'nacos/v1/ns/operator/cluster/states'

**Comment by JackSun-Developer** [comment]
您好，我没有复显出来，请问您使用的nacos-k8s详细部署方式，包括镜像、yaml可以提供一下么？

**Comment by zcz3313** [comment]
> 您好，我用官方的k8s部署方式没有复显出来，请问您使用的nacos-k8s详细部署方式，包括镜像、yaml可以提供一下么？
你好，
k8s部署方式：
使用nacos-group/nacos-k8s项目中提供的helm包，将values.yaml中的global.mode设置成cluster，并将deployment.yaml中的内容新增如下环境变量
![image](https://user-images.githubusercontent.com/8746495/117387132-d5729980-af1a-11eb-812a-b6d3dfdb06ec.png)
其他保持默认。
docker部署方式：
使用nacos-group/nacos-docker项目中example/cluster-embedded.yaml文件，并用docker-compose部署。

两者的版本号都是1.4.1

**Comment by zcz3313** [comment]
@JackSun-Developer 你好，这个问题可以看一下嘛？

**Comment by KomachiSion** [comment]
清理下浏览器缓存。您的控制台还是旧版本的js。 旧接口早已删除。

**Comment by zcz3313** [comment]
> 清理下浏览器缓存。您的控制台还是旧版本的js。 旧接口早已删除。

thankyou， you're right.
