### ISSUE TITLE
nacos 配置文件依赖，依赖加载优化建议

### ISSUE THREAD

**Issue by a852203465** [alibaba/nacos#5573]
Describe the bug
当在nacos中配置多个配置文件，并存在依赖会出现无法加载依赖的配置文件

How to Reproduce
配置说明： nacos中存在 account.yml， account-dev.yml

当在 account.yml 中文件中配置spring.profiles.active=dev时（说明需要依赖account-dev.yml的配置），如此是不能进行加载account-dev.yml的配置

Desktop (please complete the following information):
Nacos2.0

**Comment by a852203465** [comment]
修改标题

**Comment by JackSun-Developer** [comment]
您的意思是，在nacos配置中心中，不同dataId的两个配置文件之间存在依赖关系的时候，nacos应该对他们之间的依赖关系进行分析，并提供给用户？

**Comment by a852203465** [comment]
对，&nbsp;
1. 但这样可能涉及到nacos需要解析配置文件内容，
2. 也可以不提供给用户， 当不同dataId的两个配置文件发现存在依赖关系时，自动隐式操作，对于用户来说是无感的，只要两个文件能正常读取加载即可


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上7:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos 配置文件依赖，依赖加载优化建议 (#5573)





 
您的意思是，在nacos配置中心中，不同dataId的两个配置文件之间存在依赖关系的时候，nacos应该对他们之间的依赖关系进行分析，并提供给用户？

**Comment by KomachiSion** [comment]
是spring boot还是spring cloud？

您的意思是你需要加载多个带依赖关系的配置文件？

**Comment by a852203465** [comment]
1. 是spring cloud
2. 是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos 配置文件依赖，依赖加载优化建议 (#5573)





 
是spring boot还是spring cloud？
 
您的意思是你需要加载多个带依赖关系的配置文件？

**Comment by KomachiSion** [comment]
我有2个疑问：
1. spring cloud 那边好像有个ext配置可以允许加载多个配置dataId， 这个是否能满足你的需求
2. nacos本身应该没有配置的依赖关系，也不关心，配置加载顺序和读取是否应该是spring等框架去控制的事情，加载的配置调用nacos客户端接口订阅或直接获取即可？

**Comment by a852203465** [comment]
好的，&nbsp; 我试试你说的方式，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos 配置文件依赖，依赖加载优化建议 (#5573)





 
我有2个疑问：
  
spring cloud 那边好像有个ext配置可以允许加载多个配置dataId， 这个是否能满足你的需求
 
nacos本身应该没有配置的依赖关系，也不关心，配置加载顺序和读取是否应该是spring等框架去控制的事情，加载的配置调用nacos客户端接口订阅或直接获取即可？
