### ISSUE TITLE
如何使用本地缓存的配置文件?

### ISSUE THREAD

**Issue by wuwu955** [alibaba/nacos#5586]
修改本地的缓存的配置文件 能否直接读取呢? 想不从配置中心读取配置 直接读取本地的缓存配置文件

**Comment by JackSun-Developer** [comment]
没有太明白您的意思，“缓存的配置文件”是指？

**Comment by wuwu955** [comment]
不好意思 没有说清楚 我说的是指 {user.home}/nacos/config/ 目录里的配置文件 
我现在想修改里面配置文件里的配置 然后项目启动是读取 上述目录里的配置文件 需要怎么弄呢? 
> 没有太明白您的意思，“缓存的配置文件”是指？

**Comment by wuwu955** [comment]
我已经知道了

**Comment by RekaDowney** [comment]
@wuwu955 请问一下，是怎么处理的呢

**Comment by wuwu955** [comment]
在{user.home}/nacos/config/serviceName_nacos/ 下新建 data/config-data 目录 然后把 group 目录下的文件copy 过去 进行修改 即可 详情 可以看看 NacosConfigService getConfigInner 方法

**Comment by wuwu955** [comment]
> @wuwu955 请问一下，是怎么处理的呢

在{user.home}/nacos/config/serviceName_nacos/ 下新建 data/config-data 目录 然后把 group 目录下的文件copy 过去 进行修改 即可 详情 可以看看 NacosConfigService getConfigInner 方法
