### ISSUE TITLE
结束进程的时候NacosServiceManager.nacosServiceShutDown 报NPE

### ISSUE THREAD

**Issue by jinchaofeiyang** [alibaba/nacos#5588]
![image](https://user-images.githubusercontent.com/15242669/117292613-ff887500-aea2-11eb-802a-65433e3d5f43.png)

**Comment by haoyann** [comment]
请问用的什么 sdk，版本是多少？

**Comment by jinchaofeiyang** [comment]
jdk1.8 nacos服务端2.0 使用的spring-cloud-starter-alibaba:2.2.5RELEASE

**Comment by KomachiSion** [comment]
麻烦将issue转移至spring cloud alibaba 社区。
