### ISSUE TITLE
2.0.1版本 jwt不会失效，切换命名空间返回了无权限数据

### ISSUE THREAD

**Issue by rutine** [alibaba/nacos#5594]
1. 从1.2.1升级到2.0.1，发现jwt版本升级了，token有效期18000秒，登录后超过token有效期，但控制台页面一直不失效。
2. 对于命名空间权限问题，用户没有授予对应命名空间的权限，点击切换仍然可以查看无权限空间的数据

**Comment by brothelul** [comment]
I reproduced the two problem. I will fix them.

**Comment by KomachiSion** [comment]
No more response from author, so we think it is a usage problem.
