### ISSUE TITLE
Where is the document address for service routing.

### ISSUE THREAD

**Issue by MrZhangisGood** [alibaba/nacos#5597]
Hi, anybody manager,

Where is the document address for service routing.

I need the document  to realize Service discovery.

**Comment by JackSun-Developer** [comment]
You can find the features that nacos supports here.   https://nacos.io/

**Comment by MrZhangisGood** [comment]
> You can find the features that nacos supports here. https://nacos.io/

Hello, do you have any documents about the routing policy of "nearby access"? I haven't found them in the official website. How to enable the routing policy of "nearby access".
 您好，请问有没有关于“就近访问”的路由策略文档。在官网里面，找了一圈没找到。该如何启用“就近访问”路由策略。

**Comment by KomachiSion** [comment]
routing policy is implement by rpc, application framework or users, not in nacos, you search it in nacos document will not get result.
