### ISSUE TITLE
why to read config local file first ?

### ISSUE THREAD

**Issue by jiangguilong2000** [alibaba/nacos#5598]
**Describe the bug**
when remote config renewed, server still read old config content 

**Expected behavior**
when remote config renewed,server can read the last newed content.

**Acutally behavior**
as bug description above,we review the code as follows :
```
// 优先使用本地配置
 String content = LocalConfigInfoProcessor.getFailover(worker.getAgentName(), dataId, group, tenant);
```
看样子是先读取本地文件，读不到的话再远程读取，不知为何这种设计？
还有本地的这个文件是在什么时候去生成的，
It seems to read the local file first, and then read it remotely if it cannot be read. I don't know why this design?
And when the local file was generated,
C:\Users\DELL\nacos\config\config_rpc_client_nacos\data\config-data-tenant\dev\game\1-4

**Comment by xueshuai0922** [comment]
debug 看看呢

**Comment by jiangguilong2000** [comment]
> debug 看看呢

debug过了，就是不知道这文件什么时候生成的

**Comment by JackSun-Developer** [comment]
> why to read config local file first ?

这是为了分担服务端的压力，所以客户端优先从snapshot读取。

**Comment by wuwu955** [comment]
> > debug看看呢
> 
> debug过了，就是不知道这文件什么时候生成的

貌似这个data \config-data-tenant \ 这个目录是手动创建的 
自动创建的是{user.home}/nacos/config/ servername_nacos/snapshot 目录

**Comment by jiangguilong2000** [comment]
> > > debug看看呢
> > 
> > 
> > debug过了，就是不知道这文件什么时候生成的
> 
> 貌似这个data \config-data-tenant \ 这个目录是手动创建的
> 自动创建的是{user.home}/nacos/config/ servername_nacos/snapshot 目录

OK，thank you

**Comment by KomachiSion** [comment]
Failover是用于容灾的，如果出现客户端和服务端完全无法通信，但又需要修改配置的时候，手动创建failover目录及对应dataid配置内容，客户端就会使用您手动创建的配置文件了。
