### ISSUE TITLE
[doc requirement] quick start with spring, spring boot and spring cloud

### ISSUE THREAD

**Issue by pguo65535** [alibaba/nacos#56]
we have to create a quick start tutorial about how to quickly use Nacos with Spring, use Nacos with Spring Boot, use Nacos with Spring Cloud

Both Chinese version and English Version are needed.

**Comment by hxy1991** [comment]
# 中文

- [Nacos Spring 快速开始](https://nacos.io/zh-cn/docs/quick-start-spring.html)
- [Nacos Spring Boot 快速开始](https://nacos.io/zh-cn/docs/quick-start-spring-boot.html)
- [Nacos Spring Cloud 快速开始](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html)


# English

- [Quick Start for Nacos Spring Projects](https://nacos.io/en-us/docs/quick-start-spring.html)
- [Quick Start for Nacos Spring Boot Projects](https://nacos.io/en-us/docs/quick-start-spring-boot.html)
- [Quick Start for Nacos Spring Cloud Projects](https://nacos.io/en-us/docs/quick-start-spring-cloud.html)
