### ISSUE TITLE
The permission control of the 2.0.0 version namespace does not take effect

### ISSUE THREAD

**Issue by zyzyzy523** [alibaba/nacos#5607]
The permission control of the 2.0.0 version namespace does not take effect.

**Comment by brotherlu-xcq** [comment]
@zyzyzy523 please check if the config of console `nacos.core.auth.enabled`  is enabled.

**Comment by KomachiSion** [comment]
Can you upgrade to 2.0.1 and retry？

**Comment by zyzyzy523** [comment]
> Can you upgrade to 2.0.1 and retry？
Has been upgraded to 2.0.1
![image](https://user-images.githubusercontent.com/48322364/117622444-38776100-b1a5-11eb-87f8-872d3fc8315a.png)

**Comment by zyzyzy523** [comment]
> @zyzyzy523 please check if the config of console `nacos.core.auth.enabled` is enabled.

@KomachiSion I configured it like this, but it doesn't take effect

**Comment by zyzyzy523** [comment]
> @zyzyzy523 please check if the config of console is enabled.`nacos.core.auth.enabled`

我使用k8s部署，在环境变量配置了nacos.core.auth.caching.enabled=true，我使用1.4.1的版本是生效的，但是升级到2.0.+版本就不生效了

**Comment by KomachiSion** [comment]
需要配置的是application.properties的`nacos.core.auth.enabled`

如果你用的是官方镜像，可以到nacos-docker 的wiki中看一下需要配置哪个环境变量，但肯定不是`nacos.core.auth.caching.enabled`

**Comment by zyzyzy523** [comment]
我在JAVA_OPT里面添加了nacos.core.auth.enabled=true也是不行

**Comment by zyzyzy523** [comment]
可以了，应该配置环境变量NACOS_AUTH_ENABLE=true， 我在JAVA_OPT 里面添加nacos.core.auth.enabled=true不管用
