### ISSUE TITLE
Can we set multiple selector when set the routing type?

### ISSUE THREAD

**Issue by MrZhangisGood** [alibaba/nacos#5612]
![image](https://user-images.githubusercontent.com/16771383/117530685-15b44380-b011-11eb-98c4-a3253658851e.png)

**Comment by KomachiSion** [comment]
This feature is not completed for now, only a beta feature.

**Comment by KomachiSion** [comment]
Can community enhance and design it?

**Comment by brotherlu-xcq** [comment]
I will try to add this feature.

**Comment by MrZhangisGood** [comment]
> Can community enhance and design it?

如果能够支持多个表达式，并且多个表达式之间，有先后次序的支持“就近访问”的话，就很好了。比如，同一个机房找不到的，可以匹配同一个城市，同一城市找不到，在取全量ip。

**Comment by brotherlu-xcq** [comment]
@KomachiSion @MrZhangisGood how about this design?  the relation between multiple selectors like `OR`. if the first has matched instanse will not execute the left match. 
![image](https://user-images.githubusercontent.com/25661357/117766439-2b6c7780-b262-11eb-9006-4e0acb2b2bc9.png)

**Comment by MrZhangisGood** [comment]
> @KomachiSion @MrZhangisGood how about this design? the relation between multiple selectors like `OR`. if the first has matched instanse will not execute the left selectors.
> ![image](https://user-images.githubusercontent.com/25661357/117766439-2b6c7780-b262-11eb-9006-4e0acb2b2bc9.png)

this design is very nice, it can return the result if one has matched.

**Comment by MrZhangisGood** [comment]
@brotherlu-xcq  it can let me more easy to use if put a example in the input box.

**Comment by brotherlu-xcq** [comment]
@KomachiSion Now we save the Selector not the List<Selector>. This change will change the old use of OpenAPI, see the pricture. 
![image](https://user-images.githubusercontent.com/25661357/117941650-e8cb9d80-b33c-11eb-8998-7167dd51494f.png)

I'm not sure need we compatible the old way like add a new field selectors, keep the use of selector and selectors working fine at the same time. Could you help to review my design?

**Comment by brotherlu-xcq** [comment]
the screenshot in my local.
![image](https://user-images.githubusercontent.com/25661357/118125367-72f13000-b429-11eb-9ab8-97ddb64986c4.png)

**Comment by KomachiSion** [comment]
I have some different design for this.

The selector is designed to support extension by users. `Label` is a default and example implementation for user.

We should open this SPI, and let users implementation their own selector like this `MulitpleSelector`. 
And we should redesign the console make user can config which selector used and what the parameters for their own selector.

**Comment by Jarvis8099** [comment]
可以自定义实现AbstractLoadBalancerRule路由规则，根据客户端cluster-name标识配置优先调用本机房服务。实现与Eureka zone分区同等配置效果。亲测可用

**Comment by brotherlu-xcq** [comment]
Hi, @MrZhangisGood @Jarvis8099 . I make an an implement of Selector in #6301, I provide detail design on there. Welcome to discuss it !
