### ISSUE TITLE
历史版本详情页返回时查询参数丢失

### ISSUE THREAD

**Issue by MisterChangRay** [alibaba/nacos#5617]
**Describe the bug**
按照如下操作:
点击历史版本菜单 ->  输入查询参数 -> 点击查询 -> 点击查看详情 -> 点击详情页返回按钮

页面返回后 历史版本页面的查询参数丢失了

**Expected behavior**
查询参数应该保留

**Acutally behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by plusmancn** [comment]
@KomachiSion This issue can be closed.

**Comment by KomachiSion** [comment]
@plusmancn  Thanks.
