### ISSUE TITLE
Limiter  DEFAULT_LIMIT optimization

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/nacos#562]
```
private static final String DEFAULT_LIMIT = "5";
private static double limit = 5;

String limitTimeStr = System.getProperty("limitTime", DEFAULT_LIMIT);
``` 

limit and DEFAULT_LIMIT is same mean,no need use two field.
optimization:

`
String limitTimeStr = System
                .getProperty("limitTime", String.valueOf(limit));
`

**Comment by hxy1991** [comment]
Merged: [PR#563](https://github.com/alibaba/nacos/pull/563)
