### ISSUE TITLE
The page can not be synchronized when I update the instanse mate in serivce detail 

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5624]
**Describe the bug**
The update of  instanse meta can not take effect in the console page.
I update the meta from 1 to 2. the instanse updates successfully but the page still keep 1.
![image](https://user-images.githubusercontent.com/25661357/117568565-90ee2600-b0f3-11eb-8cb9-4beb5b5b4b6f.png)

after change successfully:
![image](https://user-images.githubusercontent.com/25661357/117568601-c85cd280-b0f3-11eb-8313-f4518d598a6c.png)

**Expected behavior**
-

**Acutally behavior**
-

**How to Reproduce**
1. Go to '服务详情'
2. Click on '编辑'
3. update the meta value
4. See instanse meta

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [1.4.2,2.0.1]
 - Module [console]

**Additional context**
--

**Comment by KomachiSion** [comment]
Refresh console please, the metadata update maybe async, and may be not got with a very short interval
