### ISSUE TITLE
The service instanse is always health and will not be removed even if it's an invalid IP address.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5625]
**Describe the bug**
The service instanse is always health and will not be removed even if it's an invalid IP.

**Expected behavior**
removed the invalid instanse.

**Acutally behavior**
A clear and concise description of what you actually to happen address. this can work fine in version 1.x.
![image](https://user-images.githubusercontent.com/25661357/117568743-c8110700-b0f4-11eb-9c00-bf672658827a.png)

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [2.0.1]
 - Module [naming]

**Additional context**
--

**Comment by KomachiSion** [comment]
If you send beats(for 1.x client) or not close connection or client (for 2.x client). It should be health.

The ip and port is register by yourself, even you set it not a real ip.
