### ISSUE TITLE
[Major BUG 2.0] The latest  Cluster will cover the old Cluster, just keep the latest Cluster in one Service. And the Instanse In same service and cluster just keep one.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5627]
**Describe the bug**
The latest  Cluster will cover the old Cluster, just keep the latest Cluster in one Service.And the Instanse In same service and cluster just keep one.
due to the data structure make the service and  instanse keep one-one relationship.
![image](https://user-images.githubusercontent.com/25661357/117574802-68752480-b111-11eb-9d24-71313dd151de.png)

**Expected behavior**
can work normal

**Acutally behavior**
see the issue description.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [2.0.1]
 - Module [naming]

**Additional context**
no

**Comment by JackSun-Developer** [comment]
in Nacos2.x, the instance informations are stored in client.

One client only store one instance for one service.

**Comment by JackSun-Developer** [comment]
举例说明一下：
Nacos2.x中的Client为客户端注册上来的所有信息的集合，以IP为主键，Client的主键为address + "#" + ephemeral。
场景：
IP为1.1.1.1和2.2.2.2的机器各自均发布了2个服务service1和service2，则其注册到nacos端之后，我们一共会创建4个Instance对象，和2个Client对象。

4个Instance对象：
1.1.1.1#8848#clusterName#service1
1.1.1.1#8848#clusterName#service2
2.2.2.2#8848#clusterName#service1
2.2.2.2#8848#clusterName#service2
第一个和第三个隶属于service1（可以参考Nacos分层数据结构），第二个和第四个隶属于service2。
在nacos端，会从Instance对象生成出来4个InstancePublishInfo对象，然后分别把这4个InstancePublishInfo对象放在Client的protected final ConcurrentHashMap<Service, InstancePublishInfo> publishers中。
因此，前两个Instance对象会放在1.1.1.1:8848#true的publishers里面，后两个Instance对象会放在2.2.2.2:8848#true的publishers里面。Instance对象的增删改查也是通过Client对象来实现的。
而如果同一台机器注册两个IP、Port完全相同的Instance，会存在相互覆盖的问题，其实并不是BUG，因为，这种情况nacos2默认他们就是同一个Instance，只不过进行了信息的修改，所以对他们进行覆盖。

**Comment by KomachiSion** [comment]
2.X的客户端，同一条连接针对同一个服务只能注册一个实例，如果重复在同一个客户端注册同一个服务，从语意上覆盖也是正确的。
