### ISSUE TITLE
为啥我的服务命名注册上了，但是feign调用的时候一致提示找不到

### ISSUE THREAD

**Issue by yy306525121** [alibaba/nacos#5628]
![image](https://user-images.githubusercontent.com/12985872/117576203-8e9dc300-b117-11eb-8649-169db638531a.png)
![image](https://user-images.githubusercontent.com/12985872/117576209-99585800-b117-11eb-8626-1b5af902c801.png)

**Comment by JackSun-Developer** [comment]
@yy306525121 您可以使用openAPI来测试一下，能否成功发现该服务。

>curl -X GET '127.0.0.1:8848/nacos/v1/ns/service?serviceName=nacos.test.2'

如果上面这条命令能够成功调用的话，nacos就是正常工作的。

另外，这里有一个成功修复的案例，希望帮到您 https://github.com/alibaba/spring-cloud-alibaba/issues/1072

**Comment by JackSun-Developer** [comment]
@yy306525121 您可以使用openAPI来测试一下，能否成功发现该服务。

>curl -X GET '127.0.0.1:8848/nacos/v1/ns/service?serviceName=nacos.test.2'

如果上面这条命令能够成功调用的话，nacos就是正常工作的。

另外，这里有一个成功修复的案例，希望帮到您 https://github.com/alibaba/spring-cloud-alibaba/issues/1072

**Comment by yy306525121** [comment]
@JackSun-Developer 谢谢，  是我自己代码的问题， 已解决。
