### ISSUE TITLE
与SpringCloud Gateway 整合时报404

### ISSUE THREAD

**Issue by Taogang00** [alibaba/nacos#5631]
**Describe the bug**

你好，我在使用SCA+nacos2021.1+ SpringCloud 2020.0.2+ SpringBoot2.4.5 创建了2个服务， spring cloud gateway 和一个account-service 。nacos作服务发现组件，nacos-server 用的1.4.1的版本，我同时启动这2个服务，单独调用account-service时没有问题，但是我要通过gateway 调用时，就会出现404的错误，一开始我以为启动顺序的问题，然后我重启account-service,然后再通过网关来访问account, 这里有概率的事件，有的时候能访问成功，有的时候还是404，写了个demo可以复现: https://github.com/Taogang00/cloud.git

**Expected behavior**

通过网关访问服务成功，并且不应该有启动顺序的限制吧？记得之前eureka和consul 好像是没有限制的

**Acutally behavior**
404

**How to Reproduce**

1.同时启动 gateway （端口9999）和 account（端口9001） 服务

2.单独调用account 服务：http://localhost:9001/guanwei-cloud-account-service/1 调用成功

3.通过gateway 调用account 服务 http://localhost:9999/guanwei-cloud-account-service/1 调用失败 404

4.重启account 服务,通过网关调用：有的时候调用成功，有的时候调用404

**Desktop (please complete the following information):**
 - OS: idea+win10
 - Version:SCA2021.1,SpringCloud 2020.0.2
 - Module 
 - SDK:  spring-cloud-starter-alibaba-nacos-discovery

**Additional context**

**Comment by Taogang00** [comment]
非nacos和gateway的问题，是我在配置routes 是有误~~ O(∩_∩)O

**Comment by mchgood** [comment]
> 非nacos和gateway的问题，是我在配置routes 是有误~~ O(∩_∩)O

你好，你是哪里配置出现了问题？我现在也遇到这种偶发情况
