### ISSUE TITLE
com.alibaba.nacos.common.remote.exception.RemoteException: errCode: 500, errMsg: Unknown payload type:NotifySubscriberReques

### ISSUE THREAD

**Issue by NobiLee** [alibaba/nacos#5632]
## Describe what happened (or what feature you want)
com.alibaba.nacos.api.remote.PayloadRegistry#scan()
com.alibaba.nacos.api.naming.remote.request.NotifySubscriberRequest was not registered during execution。I don't know what request or response data is
`
{ "metadata": { "type": "NotifySubscriberRequest", "clientIp": "192.168.1.110" }, "body": { "value": "{\"headers\":{},\"requestId\":\"5948\",\"serviceInfo\":{\"name\":\"system\",\"groupName\":\"DEFAULT_GROUP\",\"clusters\":\"\",\"cacheMillis\":10000,\"hosts\":[{\"ip\":\"192.168.1.110\",\"port\":8103,\"weight\":1.0,\"healthy\":true,\"enabled\":true,\"ephemeral\":true,\"clusterName\":\"DEFAULT\",\"serviceName\":\"DEFAULT_GROUP@@cfs-system\",\"metadata\":{\"preserved.register.source\":\"SPRING_CLOUD\"},\"instanceHeartBeatInterval\":5000,\"ipDeleteTimeout\":30000,\"instanceHeartBeatTimeOut\":15000}],\"lastRefTime\":1620468875146,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true},\"module\":\"naming\"}" } }
`
com.alibaba.nacos.common.remote.client.grpc.GrpcClient#bindRequestStream
`
Object parseBody = GrpcUtils.parse(payload);
`
Throw an exception
`
com.alibaba.nacos.common.remote.exception.RemoteException: errCode: 500, errMsg: Unknown payload type:NotifySubscriberRequest at com.alibaba.nacos.common.remote.client.grpc.GrpcUtils.parse(GrpcUtils.java:169) at com.alibaba.nacos.common.remote.client.grpc.GrpcClient$1.onNext(GrpcClient.java:160) at com.alibaba.nacos.common.remote.client.grpc.GrpcClient$1.onNext(GrpcClient.java:152) at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:429)
`
## How to reproduce it (as minimally and precisely as possible)
I don't know how to reproduce it

Tell us your environment
Nacos 2.0.1
SpringCloud 2.1.11

**Comment by KomachiSion** [comment]
@NobiLee I fail to reproduce the problem with 2.0.1 server and 2.0.1 client. Can you provider more information ?

Can you provider more information in #5615. 

like what's your nacos-client version?
