### ISSUE TITLE
docker中安装nacos2.0 cluster 报错

### ISSUE THREAD

**Issue by 5433zzz** [alibaba/nacos#5634]
配置文件 nacos-hostname.env
PREFER_HOST_MODE=ip
NACOS_SERVER_IP=192.168.181.128
NACOS_APPLICATION_PORT=8860
NACOS_SERVERS=192.168.181.128:8860 192.168.181.129:8860 192.168.181.130:8860
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=192.168.31.181
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_DB_NAME=nacos_config
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=dev_123456

启动
docker run \
-p 8860:8860 --privileged=true --restart always \
--name nacos_2 \
-e MODE=cluster \
--env-file=/usr/local/docker/nacos2.0/env/nacos-hostname.env \
-v /usr/local/docker/nacos2.0/logs:/home/nacos/logs \
-v /usr/local/docker/nacos2.0/init.d/custom.properties:/home/nacos/init.d/custom.properties \
-d nacos/nacos-server:2.0.1

在日志中  tail -f logs/nacos.log  无限报连接错误，是我的配置项有问题吗？

 INFO [Cluster-192.168.181.130:8860] fail to connect server,after trying 170 times, last try server is {serverIp='192.168.181.130', server main port=8860},error=unknown
 INFO [Cluster-192.168.181.130:8860] fail to connect server,after trying 171 times, last try server is {serverIp='192.168.181.130', server main port=8860},error=unknown

在集群的日志 tail -f nacos-cluster.log  提示我已经成功了
INFO start a new rpc client to member - > : Member{ip='192.168.181.129', port=8860, state=UP, extendInfo={lastRefreshTime=1620619962605, naming={voteFor=192.168.181.129:8860, ip=192.168.181.129:8860, heartbeatDueMs=5000, term=51, leaderDueMs=19437, state=LEADER}, raftPort=7860, readyToUpgrade=true, version=2.0.1}

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/2.0.0-compatibility.html

nacos2.X需要额外的端口用于grpc通信，请确认服务端之间可以进行该端口的通信。
