### ISSUE TITLE
Spring-cloud-nacos does not support yml/yaml configuration

### ISSUE THREAD

**Issue by zlt2000** [alibaba/nacos#565]
Nacos version: 0.7.0

// Nacos版本：0.7.0 

Finding the problem: spring-cloud-starter-alibaba-nacos-config does not support yml/yaml configuration, only properties can work

// 发现问题：spring-cloud-starter-alibaba-nacos-config 不支持yml/yaml 的配置，只有 properties 能生效

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by stalary** [comment]
you can use spring.cloud.nacos.config.file-extension=yml

**Comment by zlt2000** [comment]
@stalary thx
