### ISSUE TITLE
2.0.1 DataID and Group are not carried over when click the back button from the History Details page

### ISSUE THREAD

**Issue by darkelf21cn** [alibaba/nacos#5667]
Whenever users click the `back` button on the `History Details` page to get back to the `History Version` page, the DataID and Group are not carried over. Users have to manually fill the DataID and the Group to get the result. It is not convenient when users want to compare many historical versions.

**How to Reproduce**
1. Go to 'ConfigManagement -> Configurations'
2. Choose any of the configurations, then click more -> Historical Versions
3. Click Details on any of the configuration histories, then click back
4. Historical Versions page shows an empty result

**Comment by haoyann** [comment]
Maybe similar to #5617.
