### ISSUE TITLE
nacos client can not use context-path

### ISSUE THREAD

**Issue by zhangtingshu** [alibaba/nacos#5668]
When deploying the nacos cluster environment, the application configuration file of the server can configure the context-path. After I changed the context-path from the original /nacos to /, the client cannot access it. After trying multiple versions, I checked. Source code, found that in the source code, nacos-client writes /nacos as a fixed path in many places. In nacos-config, you can configure the context-path, but the configuration / will still report an error, because when the url is assembled, it becomes // Yes No access error is reported; the configuration of context-path is not directly supported as a registration center.

I modified the client source code to adapt to the server after repackaging, but still need the community to upgrade the client.

(在部署nacos集群环境的时候，服务端的application配置文件可以配置context-path，我将context-path从原来的 /nacos 变更为 /后，客户端无法访问，尝试多个版本也不可以之后我查看了源码，发现源码中，nacos-client多个地方将 /nacos写成了固定路径，在nacos-config中，可以配置context-path，但配置/依旧会报错，因为组装url的时候变成了  //  会访问不到报错；作为注册中心直接不支持配置context-path。

我修改了客户端源码，重新打包后能适配服务端，但任然需要社区进行client的升级。)

demo:
ParamUtil  :defaultContextPath = System.getProperty("nacos.client.contextPath", "nacos");
UtilAndComs:      public static String webContext = "/nacos";

ServerHttpAgent:  method->private String getUrl(String serverAddr, String relativePath) ,Need to replace the "//" in the uri with "/"

**Comment by wangweizZZ** [comment]
hi,  please try client version 1.4.1+ when you need this part of the function .you can change context path by  `properties.setProperty("contextPath", "/")` and  remove the ending  '/' of `serverAddr`. If still have problems, please provide your test sample and client version.

**Comment by zhangtingshu** [comment]
use   properties.setProperty("contextPath", "/") ， It can solve the problem of nacos.client.contextPath, and you can also add system variables at startup, but this increases the cost of client use, and there are other places where "/nacos" is used as a fixed variable. When the server contextPath=/,  the client still has the problem of "//"

**Comment by wangweizZZ** [comment]
1. ` increases the cost of client use`. can you please tell me more detail?
2. `there are other places where "/nacos" is used as a fixed variable` .can you give me an example or simply list? Also  welcome to contribute pr to repair
3. `contextPath=/ still has the problem of "//"`. did you add the suffix '/' to the `serverAddr` value?

**Comment by zhangtingshu** [comment]
![image](https://user-images.githubusercontent.com/24650415/117914426-e9047280-b315-11eb-859b-eadb5e0cf1b2.png)
![image](https://user-images.githubusercontent.com/24650415/117914384-d1c58500-b315-11eb-894a-dd4f717cf6a2.png)

**Comment by zhangtingshu** [comment]
![image](https://user-images.githubusercontent.com/24650415/117914970-e0f90280-b316-11eb-87b9-273c0f6ad8d1.png)
![image](https://user-images.githubusercontent.com/24650415/117915029-06860c00-b317-11eb-87df-a770d9a8c48e.png)

**Comment by zhangtingshu** [comment]
主要就是上面两个问题吧。
至于properties.setProperty("contextPath", "/")这个，可以通过启动参数等方式进行修改，但增加了用户使用成本，不看源码不知道这个参数的来源是system，修改为配置文件的参数更好一些。

修改都不大，不过影响的地方比较多，我这边修改的代码不符合项目的代码style就不提了。

要是服务端没有修改content-path是没问题的，但修改后客户端就没法用了，客户端使用“/nacos”的硬编码比较多

**Comment by wangweizZZ** [comment]
"//" 你截图的是老版本的代码 。配置文件的话。那个是 SpringCloud Alibaba里的使用吧？看上去这个还不支持context-path自定义。nacos-client是支持的。下面那俩图看着也是老的代码。可以看下nacos-client 1.4.1+ 的。里边这个截图部分的值会被InitUtils.initWebRootContext()更新。

**Comment by zhangtingshu** [comment]
感谢解答，在nacos-client 1.4.1+确实已经修复了context-path中大多数问题，只是SpringCloud Alibaba中的服务注册还不支持context-path自定义，目前也只能修改SpringCloud Alibaba或者nacos-client源码对这点进行支持了。
