### ISSUE TITLE
请问Feign、RestTemplate如何发现指定的namespace或者指定的group下的服务？

### ISSUE THREAD

**Issue by fanrenren** [alibaba/nacos#5670]
目前默认Feign、RestTemplate只能发现public命名空间下的DEFAULT_GROUP分组。

**Comment by warthur1214** [comment]
spring cloud项目bootstrap.yaml里配置：
```
spring.cloud.nacos.discovery.namespace=dev/test/prod
spring.cloud.nacos.discovery.group=DEFAULT_GROUP
```

**Comment by fanrenren** [comment]
> 与Feign、RestTemplate没关系，和你的服务发现配置相关。
> 
> spring cloud项目bootstrap.yaml里配置：
> 
> ```
> spring.cloud.nacos.discovery.namespace=dev/test/prod
> spring.cloud.nacos.discovery.group=DEFAULT_GROUP
> ```

谢谢
