### ISSUE TITLE
The Service detail don't show the label's experiess and the locale of router type is always in English

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5678]
**Describe the bug**
The Service detail don't show the label's expression and the locale of router type is always in English.
please see the screenshot:
![image](https://user-images.githubusercontent.com/25661357/117832632-3cd87280-b2a8-11eb-9d4f-b906cac4f3cd.png)

**Expected behavior**
see the issue. show the expression in Service Detail and the locale is same with the system setting.

**Acutally behavior**
see the description

**How to Reproduce**
see the screenshot

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [1.4.2]
 - Module [console-ui]

**Additional context**
-

**Comment by KomachiSion** [comment]
the type is not suitable to translate to Chinese, If you want to use Chinese, the ui should transfer and maintain the relationship.

What's more, the type is not enum type. Users can implement and set the type by themself. You has no way to know types users added.

**Comment by brotherlu-xcq** [comment]
I am just confused by the different language between serivce edit popup and service detail.  
![image](https://user-images.githubusercontent.com/25661357/117960678-d149e000-b34f-11eb-824e-06ca676f7138.png)

and I am not sure if we need add the expression in service detail page when have the expression like above screenshot.

**Comment by KomachiSion** [comment]
refer to #5612, design together.
