### ISSUE TITLE
Errors in Nacos Cluster Deployment

### ISSUE THREAD

**Issue by liyueforever** [alibaba/nacos#568]
I used three machines to do cluster deployment tests. The address is as follows:

// 我使用了三台机器做集群部署测试,地址如下： 

192.168.0.72，192.168.0.73，192.168.0.74
The cluster.conf and application.properties configuration of Nacos running on three machines are the same, as follows:

// 三台机器运行的Nacos的cluster.conf和application.properties配置相同，如下： 

![image](https://user-images.githubusercontent.com/46366155/50675686-91a9b580-102a-11e9-8f87-cb94fed404ba.png)
![image](https://user-images.githubusercontent.com/46366155/50675697-a4bc8580-102a-11e9-80ca-a16d9a4a546a.png)
执行启动脚本后，三台机器都打印了： Nacos started successfully in cluster mode.
But then I found the following mistakes:

// 但在后续我发现了下面的错误： 

The following exceptions are printed in the logs/naming-server.log of the three machines:

// 三台机器的logs/naming-server.log中都打印了下面的异常： 

![image](https://user-images.githubusercontent.com/46366155/50675815-6378a580-102b-11e9-9461-a5367556b111.png)
At the same time, I found that nacos. log printed the following error on 73. This exception was not found on 72,74:

// 同时在73上我发现了nacos.log打印了如下错误，此异常在72，74上没有发现： 

![image](https://user-images.githubusercontent.com/46366155/50675860-c8cc9680-102b-11e9-838b-3f0cf5794864.png)
We look forward to your reply!

// 期待您的回复！

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by nkorange** [comment]
@liyueforever It's because cluster mode needs some time to elect the leader. Any write operation before it's done will fail. 

This error should only appear at the start of the cluster. After a little while everything will work ok.

**Comment by liyueforever** [comment]
> @liyueforever这是因为集群模式需要一些时间来选举领导者。完成之前的任何写操作都将失败。
> 
> 此错误应仅出现在群集的开头。过了一会儿一切都会好起来的。

上述错误一直在持续，我认为是naming-server.log中的打印的错误导致了现在的问题
IllegalArgumentException: ip: 127.0.0.1:8848 is not in serverlist

**Comment by liyueforever** [comment]
在naming-raft.log中我发现了新的错误
![image](https://user-images.githubusercontent.com/46366155/50676208-1e09a780-102e-11e9-87aa-92d88f289204.png)
@nkorange

**Comment by liyueforever** [comment]
please  help me.

**Comment by nkorange** [comment]
@liyueforever Your machine's host file is not properly configured so Nacos gets a wrong local IP: 127.0.0.1. It's should be something like '192.168.0.xxx'. 

What's the content in your /etc/hosts file? Usually this happened because your /etc/hosts file has the following configuration:
```
127.0.0.1  YOUR_HOST_NAME
```

**Comment by liyueforever** [comment]
> @liyueforever Your machine's host file is not properly configured so Nacos gets a wrong local IP: 127.0.0.1. It's should be something like '192.168.0.xxx'.
> 
> What's the content in your /etc/hosts file? Usually this happened because your /etc/hosts file has the following configuration:
> 
> ```
> 127.0.0.1  YOUR_HOST_NAME
> ```

非常感谢您的回复！/etc/hosts文件的内容如下：
![image](https://user-images.githubusercontent.com/46366155/50677294-06cdb880-1034-11e9-8fbf-8f5b01120671.png)

**Comment by liyueforever** [comment]
> @liyueforever Your machine's host file is not properly configured so Nacos gets a wrong local IP: 127.0.0.1. It's should be something like '192.168.0.xxx'.
> 
> What's the content in your /etc/hosts file? Usually this happened because your /etc/hosts file has the following configuration:
> 
> ```
> 127.0.0.1  YOUR_HOST_NAME
> ```

您的意思是 我需要在hosts中指定192.168.0.xxx吗

**Comment by liyueforever** [comment]
我尝试在/etc/hosts中配置192.168.0.xxx，但Nacos启动后，还是发生了上述错误 @nkorange

**Comment by nkorange** [comment]
> 我尝试在/etc/hosts中配置192.168.0.xxx，但Nacos启动后，还是发生了上述错误 @nkorange

Try reboot your machine. Anyway, make sure the following command prints '192.168.0.xx'

```
hostname -i
```

**Comment by liyueforever** [comment]
> hostname -i

您好！我尝试了您说的方式，还是一样的错误，我发现 启动时总是会先报一个NPE异常，然后才是llegalArgumentException: ip: 127.0.0.1:8848 is not in serverlist
会是因为这个NPE的原因吗？
![image](https://user-images.githubusercontent.com/46366155/50680866-400e2480-1044-11e9-8eca-dd2e620046b2.png)
真的非常感谢您的耐心解答！^_^

**Comment by liyueforever** [comment]
从日志开始的打印中可以知道 是获取到了cluster.conf中的server list配置的
newHealthyList [192.168.0.72:8848, 192.168.0.73:8848, 192.168.0.74:8848]
@nkorange

**Comment by nkorange** [comment]
@liyueforever The Nacos server gets its local IP using:
```
InetAddress.getLocalHost().getHostAddress()
```
This local IP will be compared with the server list in cluster.conf. If it's not in the serverlist, Nacos reports an error as you pasted above.

So you problem is `InetAddress.getLocalHost().getHostAddress()` didn't get the right IP `192.168.0.xx`, instead it got `127.0.0.1`.

**Comment by liyueforever** [comment]
> @liyueforeverThe Nacos server gets its local IP using:
> 
> ```
> InetAddress.getLocalHost().getHostAddress()
> ```
> This local IP will be compared with the server list in cluster.conf. If it's not in the serverlist, Nacos reports an error as you pasted above.
> 
> So you problem is`InetAddress.getLocalHost().getHostAddress()`didn't get the right IP`192.168.0.xx`, instead it got`127.0.0.1`.

目前我机器的/etc/hosts文件中只配置了一行信息：
192.168.0.72   localhost localhost.localdomain localhost4 localhost4.localdomain4
Nacos是使用InetAddress.getLocalHost().getHostAddress()获取本机IP，那么应该可以得到192.168.0.72才对
能麻烦您告诉我为什么获取到的还是127.0.0.1吗？多谢了！

**Comment by nkorange** [comment]
@liyueforever You can write a demo to print the result of `InetAddress.getLocalHost().getHostAddress()` to testify your guess.

**Comment by liyueforever** [comment]
> @liyueforever You can write a demo to print the result of `InetAddress.getLocalHost().getHostAddress()` to testify your guess.

好的，多谢您的耐心回复！非常感谢

**Comment by liyueforever** [comment]
我通过更改机器的hostname，再在hosts中为新的hostname指定IP地址的方式解决了集群部署不成功的问题。
但Nacos启动时，naming-server.log中的NEP异常依然存在，我不知道是不是BUG。可能需要您看一下
![image](https://user-images.githubusercontent.com/46366155/50746588-b9875c00-126a-11e9-8389-df0c5bb92517.png)
以下为个人建议：
1.建议将IP地址作为参数，可以在application.properties进行配置。
目前我在部署时，每一台机器我都需要先更改一个hostname，然后再去配置这个hostname的IP映射。但是在实际生产环境中，hostname可能因为权限问题或者其它原因是无法更改的

2.建议在Nacos的web控制台中增加集群信息的展示页面。
目前集群启动成功后，不能从页面上直观的看到整个集群的节点信息和各节点的状态信息，建议增加此页面进行监控

最后，真的非常感谢您这么久的耐心解答！ @nkorange

**Comment by nkorange** [comment]
@liyueforever 
1. This NPE is just a startup warning, we will fix it in later version.
2. Your suggestion is quite good, it is now related to #580 .
