### ISSUE TITLE
nacos 2.0.1 snowflake instance id not work

### ISSUE THREAD

**Issue by devane001** [alibaba/nacos#5680]
Old version : 1.3.1
New version: 2.0.1

set `preserved.instance.id.generator` when application start

``` java
nacosDiscoveryProperties.getMetadata().put(PreservedMetadataKeys.INSTANCE_ID_GENERATOR, Constants.SNOWFLAKE_INSTANCE_ID_GENERATOR);
```
1.3.1 : 

![image](https://user-images.githubusercontent.com/12882801/117906971-848ee680-b308-11eb-8565-42e1f7b05129.png)

2.0.1 :
![image](https://user-images.githubusercontent.com/12882801/117906739-18ac7e00-b308-11eb-9f9b-e89963986c38.png)

does `preserved.instance.id.generator` be changed?

**Comment by KomachiSion** [comment]
There are something changes for instance id in 2.X. Because we think the instanceId might generated in client id will be right.

Community need more discussion and determine how to implement it.

**Comment by wmzzh117** [comment]
``

**Comment by wmzzh117** [comment]
> There are something changes for instance id in 2.X. Because we think the instanceId might generated in client id will be right.
> 
> Community need more discussion and determine how to implement it.

Sometimes we use the instance id of Nacos as part of the data worker id.

It is a great feature instead of an additional snow id generator.

😔😔😔

**Comment by KomachiSion** [comment]
Fixed in new version
