### ISSUE TITLE
 Bad handshake

### ISSUE THREAD

**Issue by ToBeIronMan** [alibaba/nacos#5681]
k8s nacos连接数据库报错  Bad handshake，之前以前一直可以正常运行的
![image](https://user-images.githubusercontent.com/53281822/117913082-48ad4e80-b313-11eb-9f3b-80d690c1eeec.png)

**Comment by KomachiSion** [comment]
Bad handshake说明无法连接数据库，确认该pod和数据库本身是可以通信的。并且url等内容均配置正确。

可以搜索一下其他日志，看一下无法连接的真正原因。

**Comment by ToBeIronMan** [comment]
@KomachiSion 
pod确定可以访问mysql,这个是按照nacos-k8s的deployment部署的，我之前一直是好的，不过关了服务器重启的时候，重新拉了nacos/nacos-server:latest镜像，不知道是不是版本更新了，导致的这个问题

**Comment by KomachiSion** [comment]
找找其他信息，看下具体是什么导致的连接失败

**Comment by ToBeIronMan** [comment]
@KomachiSion 
天坑，我按照log找到了java.security找到了SSLv3的支持，原来镜像的mysql5.7不支持，而当我替换mysql8.0.16时候，可以了。看来版本升级，自己还是要保存镜像到本地

**Comment by KomachiSion** [comment]
没理解，mysql8的新版本驱动是兼容mysql5.7的，application.properties也能配置Driver的类名，即使mysql驱动无法自动适配，也能手动选择旧版本驱动类，至于SSL支持，url里应该有对应参数可以控制。

看描述像是新驱动默认使用SSL，但是mysql5.7服务端没有，那应该在参数中关闭SSL就可以了。

**Comment by KomachiSion** [comment]
既然问题已经解决 那我就先关闭issue了
