### ISSUE TITLE
get 504 code form nacos 

### ISSUE THREAD

**Issue by AArenxiaoming** [alibaba/nacos#5682]
i run nacos as docker-compose standalone
nacos version: 1.3.2 

java 
[com.alibaba.nacos.client.Worker.longPolling.fixed-xxxxx.com_80-9e7823cf-47a5-45ca-b005-ae75913ece5f] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-xxxxxxx.com_80-9e7823cf-47a5-45ca-b005-ae75913ece5f] [check-update] get changed dataId error, code: 504

config-client-request.log like this 
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341

**Comment by KomachiSion** [comment]
What's the error info of `504`？

**Comment by AArenxiaoming** [comment]
this is the message i have see in java response

[com.alibaba.nacos.client.Worker.longPolling.fixed-xxxxx.com_80-9e7823cf-47a5-45ca-b005-ae75913ece5f] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-xxxxxxx.com_80-9e7823cf-47a5-45ca-b005-ae75913ece5f] [check-update] get changed dataId error, code: 504

and this is see in nacos logs which names 
config-client-request.log
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341

**Comment by AArenxiaoming** [comment]
> What's the error info of `504`？

this is the message i have see in java response

[com.alibaba.nacos.client.Worker.longPolling.fixed-xxxxx.com_80-9e7823cf-47a5-45ca-b005-ae75913ece5f] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-xxxxxxx.com_80-9e7823cf-47a5-45ca-b005-ae75913ece5f] [check-update] get changed dataId error, code: 504

and this is see in nacos logs which names
config-client-request.log
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341
2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341

**Comment by Maijh97** [comment]
Check whether the network of the nacos server host is normal.

**Comment by KomachiSion** [comment]
`2021-05-12 14:11:15,954|29500|timeout|10.4.2.212|polling|4|341` is longpollig trace log. timeout means no config changed. It is no problem.

The `504` is http response error code. We need the information or message of this code. Otherwise we can't know what happen in your environment.

**Comment by KomachiSion** [comment]
No more response from author, and no enough information to judge problem. Close first.

**Comment by zhiwangXu** [comment]
I found this problem,too.
