### ISSUE TITLE
nacos2.0.1 always write log

### ISSUE THREAD

**Issue by 232526** [alibaba/nacos#5684]
nacos always write log by 30s

log details is 
 [ com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.1.193_8848-b12bd53d-342b-499b-8806-1eb03ce6f36f:149827 ] - [ INFO ] | [] |  get changedGroupKeys:[]

i see nacos fix this issues by 1.3.1

**Comment by li-xiao-shuang** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
Where this log print？ config.log or your log?

**Comment by 232526** [comment]
@KomachiSion  my log ,  use log4j .  
add "log4j.logger.com.alibaba.nacos.client.config.impl=WARN " to  log4j.properties can solved the problem
