### ISSUE TITLE
2.0.1版本和springBoot版本

### ISSUE THREAD

**Issue by luyi1023** [alibaba/nacos#5687]
## Issue Description

Type:  feature request

### Describe what happened (or what feature you want)
  请问2.0.1和springBoot版本对应关系是什么？还有我能在哪儿看到nacos各个版本和spring-boot版本的对应关系

**Comment by KomachiSion** [comment]
spring boot 会使用nacos-client，对应版本关系可以需要看spring boot依赖的client版本。

和服务端的版本号关系不大。

**Comment by luyi1023** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2021年5月12日(星期三) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] 2.0.1版本和springBoot版本 (#5687)





 
spring boot 会使用nacos-client，对应版本关系可以需要看spring boot依赖的client版本。
 
和服务端的版本号关系不大。
