### ISSUE TITLE
[Enhancement] update the NamingExample in Nacos 2.x

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5689]
**Describe the bug**
https://github.com/alibaba/nacos/blob/d929c2e328a1ae0256449ead9c90028a84ea93a6/example/src/main/java/com/alibaba/nacos/example/NamingExample.java#L52

update the NamingExample in Nacos 2.x, as we know, Nacos 2.x  use grpc connection to bind Client with Server, one Client can only register one Instance. So I think we can update the NamingExample, or else it will confuse the user.

**Expected behavior**
update the NamingExample

**Acutally behavior**
--

**How to Reproduce**
run the NamingExample, you will get no instanse.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [2.0.1]
 - Module [example]

**Additional context**
no

**Comment by JackSun-Developer** [comment]
@i will solve it@

**Comment by JackSun-Developer** [comment]
This can truely confuse the users

**Comment by brotherlu-xcq** [comment]
Hi, @JackSun-Developer . How about this issue? if you have no time to do it, I think you can assign it to me. I will try to fix it.

**Comment by JackSun-Developer** [comment]
@brotherlu-xcq thanks
