### ISSUE TITLE
[nacos-client-2.0.0] 客户端获取配置 若指定命名空间为public 则获取不到

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#5690]
**Describe the bug**
1.客户端版本 【nacos-client-2.0.0】
2.两个命名空间 【public】 与 【test】，均有配置test
![image](https://user-images.githubusercontent.com/53824889/117982156-4e814f00-b368-11eb-875c-deb129b2d556.png)
3.测试代码如下
![image](https://user-images.githubusercontent.com/53824889/117982208-5b9e3e00-b368-11eb-9601-bafaba65d0e7.png)
4.测试结果如下
![image](https://user-images.githubusercontent.com/53824889/117982223-61941f00-b368-11eb-9af5-cd32875bea8e.png)

**Expected behavior**
代码里面的4种方式均能获取到相应的配置

**Acutally behavior**
1.要获取命名空间为public的配置，需要不指定命名空间名称
2.要获取命名空间为[其他]的配置，需要指定命名空间的id，而不是名称

**Additional context**
请问这是符合nacos设计初衷的还是意外情况？

**Comment by brotherlu-xcq** [comment]
Now. the namespace confuse with the tenantId, the namespace you set will be use as tenantId when search the config. please refer #4892

**Comment by haoyann** [comment]
duplicate with #4682.

**Comment by MajorHe1** [comment]
> public namespace id is empty. duplicate with #4682.

@haoyann  疑问在于官方怎么看待这个事情
1.public 则认为是 empty，这算是bug还是feature？
2.访问其他命名空间，需要指定id而不是命名空间名称，疏漏还是设计如此？如果id用作命名空间的唯一区分，那为什么不在新建命名空间的时候就禁止重名？
