### ISSUE TITLE
Summer 2021 For Nacos

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#5693]
`Summer 2021` is a program hosted by  ISCAS(Institute of Software Chinese Academy of Sciences) and openEuler community. It is very similar with Google Summer of Code.

Nacos will join The Summer 2021 as the mentoring organization.

Home page, https://summer.iscas.ac.cn

Nacos community will select some challenging topics, so that more college students can improve their abilities through the community. At the same time, Nacos community will obtain more new contributors.

Topic list:

- Adapt to the new version of gRPC interface for Nacos Python SDK. #5694
- Add a plugin SPI for configuration encryption and decryption for Nacos 2.0. #5695
- Add a plugin SPI for authentication for Nacos 2.0.  #5696
- Add new monitor observability Nacos 2.0. #5697
- Build an embedded anti-fragile system plug-in. #5698

--------------------

“开源之夏2021”是由ISCAS（中国科学院软件研究所）和openEuler社区托管的程序。 与Google Summer of Code非常相似。

Nacos将会作为指导组织参加本次的“开源之夏2021”。

“开源之夏2021”的官方网站为：https://summer.iscas.ac.cn

Nacos社区将选择一些具有挑战性的主题，让更多的高校学子能够通过贡献社区提高自己的能力。 同时，Nacos社区将获得更多新的贡献者。

主题列表如下：

- 为Nacos Python SDK适配新版本gRPC接口。#5694
- 为Nacos2.0添加配置加解密的插件SPI。#5695
- 为Nacos2.0添加鉴权的插件SPI。#5696
- 为Nacos2.0添加新的可观测性系统。#5697
- 构建内嵌的反脆弱体系插件。 #5698

**Comment by fengkai8** [comment]
Students Only?

**Comment by hjq2016** [comment]
can socical software engineer join?

**Comment by grumpyAmber** [comment]
> can socical software engineer join?

sorry, students only.

**Comment by KomachiSion** [comment]
If no students join after Summer 2021 finished, Community can start to do.

**Comment by firedtoad** [comment]
Can continued education students join?

**Comment by jiazhiyuans** [comment]
i am student iwant to join

**Comment by lxb567** [comment]
为什么要说英文啊奇奇怪怪，不参加也罢

**Comment by LovingANA** [comment]
> 为什么要说英文啊奇奇怪怪，不参加也罢

zhuang bi

**Comment by chenaichenet** [comment]
> 为什么要说英文啊奇奇怪怪，不参加也罢

差点以为是国外的活动
