### ISSUE TITLE
[Summer 2021] Adapt to the new version of gRPC interface for Nacos Python SDK.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#5694]
# Background

With the release Nacos 2.0, the communication protocol between the client and server will use gRPC instead of HTTP 1.1 to improve performance. Now, Java SDK, Go SDK and C# SDK has basically completed the adaptation, and C++ SDK is processing.

But Python SDK and NodeJs SDK, there are no contributors to adapt this feature. So Nacos community open Python SDK adapting task to `Summer 2021`.

# Target

Adapting the new version of the gRPC interface for Nacos Python SDK, so that Python micro-service clients can also enjoy the performance improvements brought by Nacos 2.0.

# Difficulty

*Easy*

# Mentor

@JackSun-Developer 
yongyue.sl@alibaba-inc.com

# Output Requirements

- Add gRPC request processing module to Nacos Python SDK.
- Adapt to Nacos2.0 configuration center gRPC interfaces.
- Adapt to Nacos2.0 service management gRPC interfaces.

# Technical Requirements

- Familiar with Python programming language.
- Understand the basic principles and usage of gRPC.

----------------

# 背景

随着Nacos2.0的发布，客户端和服务器之间的通信协议将使用gRPC代替HTTP 1.1来提高性能。 现在，Java SDK，Go SDK和C＃SDK已基本完成适配，并且C ++ SDK正在处理中。

但Python SDK 和 NodeJs SDK 目前没有贡献者开始这项适配工作。因此Nacos社区将Python SDK的适配工作开放至“开源之夏2021”中。

# 目标

为Nacos的Python SDK 适配新版本gRPC接口，让Python的微服务客户端也能享受Nacos2.0带来的性能提升。

# 难度

*简单*

# 导师

@JackSun-Developer 
yongyue.sl@alibaba-inc.com

# 产出要求

- 为Nacos Python SDK添加gRPC请求处理模块。
- 适配Nacos2.0 配置中心gRPC对应接口。
- 适配Nacos 2.0 服务管理gRPC对应接口。

# 能力要求

- 熟悉Python开发语言。
- 了解gRPC基本原理及使用 。

**Comment by JackSun-Developer** [comment]
Thanks @KomachiSion .

Python SDK is a vital feature for Nacos community, as well as an attractive technology adopting gRPC. Welcome to join and develop.

**Comment by plusmancn** [comment]
@KomachiSion @JackSun-Developer Where is the issue of Node.JS SDK, or it has been processing in AliGroup.
