### ISSUE TITLE
[Summer 2021] Build an embedded anti-fragile system plugin.

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#5698]
# Background

In last year's ASoC 2020, building an anti-fragile system was a difficult topic, but no contributors were able to complete the topic. Therefore, we need to continue to build an anti-fragile system.

In this anti-fragile system topic, the Nacos community lowered certain requirements, focusing on judging whether Nacos reached the upper limit of capacity, and how to reasonably trigger the fuse mechanism to protect the high availability of Nacos.

Parent Issue: #2853

# Target

Add expandable capacity threshold protection, fuse protection anti-fragile system plugins.

# Difficulty

*Hard*

# Mentor

@shiyiyue1102 
zunfei.lzf@antgroup.com

# Output Requirements

- Add a set of easily expandable capacity protection monitoring and fuse protection anti-fragile system SPI interface.
- Use appropriate design patterns to implement the plugin of capacity monitoring and fuse interface.
- Add query openAPI for capacity monitoring query and fuse configuration.
- Added capacity monitoring content and fuse configuration pages on the console(front-end).

# Technical Requirements

- Familiar with Java programming language.
- Familiar with Java class loading mechanism.
- Familiar with Java SPI loading mechanism.
- Familiar with HTTP/TCP protocol
- Understand common design patterns
- Understand the use of monitoring interfaces such as Metrics

----------------

# 背景

在去年的ASoC中，构建反脆弱体系是一个困难课题，但没有贡献者能够完成该课题。因此需要继续构建反脆弱体系。

在本次反脆弱体系课题中，Nacos社区降低了一定的要求，集中关于与判断Nacos是否达到容量上限，并如何合理触发熔断机制保护Nacos自身的高可用性。

原始Issue：#2853

# 目标

添加可扩展的容量阈值保护、熔断保护等反脆弱体系插件。

# 难度

*困难*

# 导师

@shiyiyue1102 
zunfei.lzf@antgroup.com

# 产出要求

- 添加一套易于扩展的容量保护监控及熔断保护的反脆弱体系SPI接口。 
- 使用合适的设计模式实现容量监控及熔断接口的插件化实现。 
- 添加对应容量监控查询及熔断配置的控制接口。
- 在控制台上添加容量监控内容及熔断配置相关页面（前端）。

# 能力要求

- 熟悉Java开发语言 
- 熟悉Java 类加载机制 
- 熟悉Java SPI加载机制 
- 熟悉HTTP/TCP协议 
- 了解常用设计模式 
- 了解Metrics等监控接口使用

**Comment by korbanr** [comment]
Ok

**Comment by cazzlben6707** [comment]
DATA*.M.ME@MAGGIE71
