### ISSUE TITLE
HostReactor  processServiceJson

### ISSUE THREAD

**Issue by hxlzpnyist** [alibaba/nacos#5699]
![image](https://user-images.githubusercontent.com/4377393/118097408-3a3f5f80-b405-11eb-9013-0c62bd9b106e.png)

这个地方咋不直接用 changed == true 判断呢

**Comment by Maijh97** [comment]
Contributions welcome 👏🏻

**Comment by JackSun-Developer** [comment]
@i will solve it@

**Comment by brotherlu-xcq** [comment]
Hi @JackSun-Developer , If you have no  time to do this. I am very happy to help fix it.
