### ISSUE TITLE
Nacos2.0.1版本开启beta发布后， 所有的客户端依然可以读取nacos服务端配置

### ISSUE THREAD

**Issue by heyangang** [alibaba/nacos#5701]
Nacos2.0.1版本开启beta发布之后灰度的ip依然可以读取nacos服务端配置

**Comment by JackSun-Developer** [comment]
“灰度的ip”是指发布beta版本配置的IP吗，如果您是这个意思的话，我认为它能够读取到beta配置是合理的（而其他IP能够不应该读
取到）。

**Comment by KomachiSion** [comment]
是说beta发布的配置， 在指定ip后，所有其他ip的客户端都可以取到beta配置？

**Comment by heyangang** [comment]
> 是说beta发布的配置， 在指定ip后，所有其他ip的客户端都可以取到beta配置？
是的，beta发布后，配了指定的IP和没有配进去的ip都可以读取到nacos服务端的配置！这个是什么原因呢？

**Comment by heyangang** [comment]
> “灰度的ip”是指发布beta版本配置的IP吗，如果您是这个意思的话，我认为它能够读取到beta配置是合理的（而其他IP能够不应该读
> 取到）。
和你说的刚好相反，beta发布之后所有的ip都能够读到nacos服务端的配置

**Comment by heyangang** [comment]
> “灰度的ip”是指发布beta版本配置的IP吗，如果您是这个意思的话，我认为它能够读取到beta配置是合理的（而其他IP能够不应该读
> 取到）。

**Comment by heyangang** [comment]
> 是说beta发布的配置， 在指定ip后，所有其他ip的客户端都可以取到beta配置？
请问这个问题该怎么解决？

**Comment by shiyiyue1102** [comment]
> > 是说beta发布的配置， 在指定ip后，所有其他ip的客户端都可以取到beta配置？
> > 请问这个问题该怎么解决？

能够复现吗？还不清楚你具体的问题，能讲下复现步骤，看你描述是不是beta删除配置？
