### ISSUE TITLE
Nacos2.0.1版本删除某个配置文件后，到历史版本列表回滚提示回滚成功，但是实际上配置列表没有显示回滚的配置文件

### ISSUE THREAD

**Issue by heyangang** [alibaba/nacos#5702]
Nacos2.0.1版本删除某个配置文件后，到历史版本列表回滚提示回滚成功，但是实际上配置列表没有显示回滚的配置文件

**Comment by JackSun-Developer** [comment]
我重现了一下整个过程，最后一个操作是删除操作
![image](https://user-images.githubusercontent.com/58767027/118120198-13dbed00-b422-11eb-8b8b-cd06f673a03e.png)

然后点回滚
![image](https://user-images.githubusercontent.com/58767027/118120259-2c4c0780-b422-11eb-8237-74bbbd6bc34d.png)

点击OK
![image](https://user-images.githubusercontent.com/58767027/118120311-40900480-b422-11eb-955c-3428f636a6c7.png)

显示回滚成功
![image](https://user-images.githubusercontent.com/58767027/118120339-4c7bc680-b422-11eb-8794-4a608ae40122.png)

回到配置列表，文件已经恢复了
![image](https://user-images.githubusercontent.com/58767027/118120378-5e5d6980-b422-11eb-81d8-556a9aa012ca.png)

**Comment by JackSun-Developer** [comment]
@heyangang 你是这个操作步骤吗？我这边实验出来，完全没有问题。

**Comment by KomachiSion** [comment]
选第一个回滚的话 应该是删除配置。

可以看下这个issue的解释

https://github.com/alibaba/nacos/issues/4064

**Comment by heyangang** [comment]
> @heyangang 你是这个操作步骤吗？我这边实验出来，回滚功能完全没有问题。

是的，你用的是2.0.1版本的吗？

**Comment by JackSun-Developer** [comment]
> > @heyangang 你是这个操作步骤吗？我这边实验出来，回滚功能完全没有问题。
> 
> 是的，你用的是2.0.1版本的吗？

是的。

**Comment by heyangang** [comment]
> > > @heyangang 你是这个操作步骤吗？我这边实验出来，回滚功能完全没有问题。
> > 
> > 
> > 是的，你用的是2.0.1版本的吗？
> 
> 是的。

如果我开启了权限，但是我给对应的项目配置的用户名和密码都是最大权限的nacos，那样就会出现上面都我说的问题

**Comment by heyangang** [comment]
> > > @heyangang 你是这个操作步骤吗？我这边实验出来，回滚功能完全没有问题。
> > 
> > 
> > 是的，你用的是2.0.1版本的吗？
> 
> 是的。

要不你连我的环境看看？

**Comment by JackSun-Developer** [comment]
> > > > @heyangang 你是这个操作步骤吗？我这边实验出来，回滚功能完全没有问题。
> > > 
> > > 
> > > 是的，你用的是2.0.1版本的吗？
> > 
> > 
> > 是的。
> 
> 要不你连我的环境看看？

好的，您可以提供一下登陆方式？我连上去看看。
