### ISSUE TITLE
Is there an interface to get the information and health status of all instances

### ISSUE THREAD

**Issue by 50133142** [alibaba/nacos#5708]
**Describe the bug**
Is there an interface to get all the instance information and health status, and get the instance data without user information

Currently nocas/v1 / ns/catalog/service, users need information to get the data

* 是否存在这样接口：获取所以实例的信息和健康状态，不用用户信息就可以拿到实例信息的数据
目前nocas/v1/ns/catalog/service,获取需要用户信息才能拿到数据

**Comment by KomachiSion** [comment]
try https://nacos.io/en-us/docs/open-api.html Query instances

**Comment by 50133142** [comment]
谢谢
