### ISSUE TITLE
配置中心修改不生效(Configuration Center changes do not take effect)

### ISSUE THREAD

**Issue by HaoLi-Rainbow** [alibaba/nacos#5711]
在启用了@RefreshScope之后，仍然无法刷新配置（@RefreshScope加在了启动类上）,也没有日志输出。
After enabling @RefreshScope, the configuration is still not refreshed (@RefreshScope is added to the startup class), and there is no log output.

版本信息 Version
Nacos 2.0
SpringBoot 2.1.1.RELEASE
SpringCloud Greenwich.SR6
SpringCloud Alibaba 2.1.4.RELEASE

**Comment by HaoLi-Rainbow** [comment]
在nacos中查看监听查询也是空的，没有数据。但是其他项目添加到启动类上就可以在监听查询中查看监听的信息。是不是因为其他项目的springboot版本比这个高的问题呢

**Comment by KomachiSion** [comment]
那应该是没有监听到对应的dataid， debug一下看看，或者把issue和可复现的代码转到SCA社区看看。

或者使用原生的nacos-client测试一下

**Comment by weissxu** [comment]
@RefreshScope  加到service bean（需要注入Value属性的bean）上试试看。

**Comment by HaoLi-Rainbow** [comment]
> 那应该是没有监听到对应的dataid， debug一下看看，或者把issue和可复现的代码转到SCA社区看看。
> 
> 或者使用原生的nacos-client测试一下

这个没办法复现呀，就是加了几个pom.xml和一个注解而已，我可以吧日志贴上来，您可以帮我看看嘛

**Comment by HaoLi-Rainbow** [comment]
> 那应该是没有监听到对应的dataid， debug一下看看，或者把issue和可复现的代码转到SCA社区看看。
> 
> 或者使用原生的nacos-client测试一下

当时用nacos的时候就是想要他的刷新配置中心的，结果他不管用了，很难过呀

**Comment by illeagalName** [comment]
我也遇到几次了，修改了配置，但是配置死活不生效

**Comment by HaoLi-Rainbow** [comment]
> 我也遇到几次了，修改了配置，但是配置死活不生效

你的监控查询是空的吗？
