### ISSUE TITLE
管控台上回车查询，url 地址上不会带上查询条件，在查看详情后返回丢失查询条件

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#5713]
1. 管控台上回车查询，url 地址上不会带上查询条件，在查看详情后返回丢失查询条件

2. 而管控台上点击查询，url 地址上会带上 查询条件，查看详情后返回还有旧的查询条件

![image](https://user-images.githubusercontent.com/16837364/118238155-b8196e80-b4ca-11eb-82fb-e761461bfd36.png)

期望：回车查询与点击查询一致

**Comment by brotherlu-xcq** [comment]
I will fix it.
