### ISSUE TITLE
nacos-spring-boot-project

### ISSUE THREAD

**Issue by liaozan** [alibaba/nacos#5721]
nacos-spring-boot-project 能不能更新一下？
现在能用上nacos的，几乎都是 springboot 或者 springcloud 项目了吧？
为啥好像又是一个 kpi project 呢

**Comment by KomachiSion** [comment]
那您是否有兴趣加入一起更新呢？

**Comment by KomachiSion** [comment]
近期社区应该会更新一下，适配1.4.X客户端。

如果有需求，可以考虑加入社区，帮助贡献。

**Comment by li-xiao-shuang** [comment]
> 近期社区应该会更新一下，适配1.4.X客户端。
> 
> 如果有需求，可以考虑加入社区，帮助贡献。

需要改变什么？我可以参与下
