### ISSUE TITLE
nacos console，Subscribers list, the column of app shows: ‘unknown’

### ISSUE THREAD

**Issue by weissxu** [alibaba/nacos#5723]
**Describe the bug**
Please look at the pic below:
![image](https://user-images.githubusercontent.com/1793302/118276410-36d9d000-b4fa-11eb-8733-9428a747df6c.png)

**Expected behavior**
show the app name or service name.

**Acutally behavior**
tell me: 'unknown'.

**How to Reproduce**
1. Go to left menu
2. Click on 'ServiceManagement'
3. Click on 'Subscribers'

**Desktop (please complete the following information):**
 

**Additional context**
I donot understand ,why 'unknown' is here?
 Is there someone explain it to me?

**Comment by KomachiSion** [comment]
duplicate with #5268
