### ISSUE TITLE
[Code Quality] improve the code quality of Nacos 2.0.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#5726]
***Description*** 

The Nacos becomes huge now, and some codes have bad smell and are not easy to understand. I create issue to make an overview to improve the code quality in Nacos 2.0. The sub issues will make the code quality changes. I will keep the progress of this issue. 

the code quality problem mainly contains bellow（if has omission, feel free to change it）:

- add the missing javadoc in interface and change the Chinese javadoc to English.
- remove the no-use assign/use/import.
- optimize the judge logic, reduce the for/if nest, improve logic the readability.
- optimize the method using.
- move the variable position to match the code habits.
- create constant directory to put the magic number in constants.
- other.

if you work on the sub-issue of this, please check the point before you do the code quality work.

***Standard***
If you work on the sub issue, please format your sub-issue and PR name to the standard name for easy managment.
Sub Issue name:
`[Code Quality] [nacos-xxx] [sub issue] improve the code quality of module nacos-xxx. `
constant enhance PR name:
`[For #5726 directoryName] [constans enhancement] improve the code quality of nacos-xxx`

***To do list*** 

> if the module has no code quality problem, please make the status done.

progress:  

code quality enhancement
| total module | done  | doning | waiting |
| ------------------ | -------------- | :----: | ------- | 
| 16 | 16 | 0 | 0 |

 constant export
| total module | done  | doning | waiting |
| ------------------ | -------------- | :----: | ------- | 
| 16 | 1 | 0 | 15 |

detail:
> the contants separating is a big task, so we put the fix PR to table column（constant enhance PR）. if you work on this, please separating constant  uses the solution in #3046 . 

| module             | sub issue      | assign | status  |  constant sub issue | constant assign | constant status |
| ------------------ | -------------- | :----: | ------- |   -------  |  -------  |  -------  | 
| nacos-api | #5915 |  @brotherlu-xcq  | done |  #6487  | @brotherlu-xcq  | done |
| nacos-address      | #5766 |   @brotherlu-xcq | done | waiting to do |
| nacos-auth         | none |   @brotherlu-xcq      |  done | #7114  | @onewe | done |
| nacos-client       |  #5771 |     @realJackSun  @brotherlu-xcq    | done | #7225 | @onewe | doing |
| nacos-cmdb         | none |    @brotherlu-xcq     | done | waiting to do |
| nacos-common       | #5802  |     @brotherlu-xcq    | done | waiting to do |
| nacos-config       | #5727  |   @brotherlu-xcq   | done | waiting to do |
| nacos-consistency  | #5836  |   @brotherlu-xcq      | done | waiting to do |
| nacos-console      | #5843 |   @brotherlu-xcq      | done | waiting to do |
| nacos-core         | #5877  |   @brotherlu-xcq      |  done | waiting to do |
| nacos-distribution | none |  @brotherlu-xcq       | done | waiting to do |
| nacos-example      | none  |  @brotherlu-xcq    | done | waiting to do |
| nacos-naming       |  #5774 |     @li-xiao-shuang   | done | waiting to do |
| nacos-sys          | #5904 |  @brotherlu-xcq       | done | waiting to do |
| nacos-istio | #6010 |  @brotherlu-xcq | done | waiting to do |
| nacos-test | none | @brotherlu-xcq  | done |  waiting to do |

**Comment by JackSun-Developer** [comment]
I will do the client module

**Comment by JackSun-Developer** [comment]
https://github.com/alibaba/nacos/issues/5771 @brotherlu-xcq plz add this issue in the table

**Comment by brotherlu-xcq** [comment]
> #5771 @brotherlu-xcq plz add this issue in the table

done. plz go ahead.

**Comment by brotherlu-xcq** [comment]
Now, the first time code quality job has been finished. But the enhancement of constant does not start. If anyone interests in this job, you can just reply the module you want on this issue.

**Comment by brotherlu-xcq** [comment]
OK, just start your work. look forward to your PR.

**Comment by onewe** [comment]
Let me start doing the nacos-client module.🦉

**Comment by brotherlu-xcq** [comment]
just do it, Bro
