### ISSUE TITLE
Cannot use sh startup.sh -m standalone in Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by SuperMaskv** [alibaba/nacos#5728]
**Describe the bug**
Can't use "sh startup.sh -m standalone" startup nacos 2.0.1 in standalone mode with Ubuntu 20.04.2 LTS. 
Log always shows "nacos is starting with cluster", and than startup fail.

**Expected behavior**
nacos startup successfully in standalone mode.

**Acutally behavior**
nacos can't startup.

**How to Reproduce**
1. download
2. unpack
3. sh startup.sh -m standalone
4. see logs

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Version nacos-server 2.0.1
 - Module config
 
**Additional context**
But I can use "bash startup.sh -m standalone" to startup porperly.

**Comment by KomachiSion** [comment]
I can't reproduce your problem, Please provide more information about the reason why can't start.
You can try to delete the nacos/data dir and retry.

**Comment by SuperMaskv** [comment]
Thx for replying. 
I have tried to delete the nacos/data dir and retry to start up, but it still doesn't work.
I don't know what more information you need, here are logs.
**console logs:**
```
sh startup.sh -m standalone

startup.sh: 86: [[: not found
startup.sh: 90: [[: not found
startup.sh: 99: [[: not found
startup.sh: 101: [[: not found
startup.sh: 108: [[: not found
/home/dev/jdk-11.0.11+9/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/dev/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/home/dev/jdk-11.0.11+9/jre/lib/ext:/home/dev/jdk-11.0.11+9/lib/ext -Xloggc:/home/dev/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/home/dev/nacos/plugins/health,/home/dev/nacos/plugins/cmdb -Dnacos.home=/home/dev/nacos -jar /home/dev/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/home/dev/nacos/conf/ --logging.config=/home/dev/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
startup.sh: 129: [[: not found
nacos is starting with cluster
nacos is starting，you can check the /home/dev/nacos/logs/start.out
```
**start.out:**
```
/home/dev/jdk-11.0.11+9/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/dev/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/home/dev/jdk-11.0.11+9/jre/lib/ext:/home/dev/jdk-11.0.11+9/lib/ext -Xloggc:/home/dev/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/home/dev/nacos/plugins/health,/home/dev/nacos/plugins/cmdb -Dnacos.home=/home/dev/nacos -jar /home/dev/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/home/dev/nacos/conf/ --logging.config=/home/dev/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
-Djava.ext.dirs=/home/dev/jdk-11.0.11+9/jre/lib/ext:/home/dev/jdk-11.0.11+9/lib/ext is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```

**Comment by KomachiSion** [comment]
you can retry to use `bash startup.sh -m standalone` .

If it still has error with `-Djava.ext.dirs=/home/dev/jdk-11.0.11+9/jre/lib/ext:/home/dev/jdk-11.0.11+9/lib/ext is not supported.  Use -classpath instead.` 

maybe you need has some change in your local startup.sh with this error hint.

**Comment by SuperMaskv** [comment]
yes, I can use `bash startup.sh -m standalone` as I mentioned in additional context.
but I am still curious about why this error occur in Ubuntu 20.04.2 LTS. 
I can use `sh startup.sh -m standalone` in other Linux distribution.

**Comment by KomachiSion** [comment]
This is Ubuntu system problem. We use some bash program in script, and set the header as bash.

But Ubuntu do not read header and just use your command to run. So with error :`startup.sh: 86: [[: not found`.

**Comment by orionmeetartemis** [comment]
you can use bash instead of sh.
