### ISSUE TITLE
When can the function of authority management be improved?

### ISSUE THREAD

**Issue by fireflyhoo** [alibaba/nacos#573]
No authority to manage the use of wood ah, when can we get access ah...

// 没有权限管理木法用啊, 啥时候能弄上来权限啊.....

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by leizhen** [comment]
agree.. if we can suport authentication and authority OOB,  this will be helpful for su to migrate the projects to prod. is there any update?
