### ISSUE TITLE
The local microservice connection to NaCos is unstable

### ISSUE THREAD

**Issue by MrGAbetter** [alibaba/nacos#5736]
When I was working on a local microservice project for learning, I had four microservices, three of which connected properly to NAOCS, and one of which was very unstable, with instances in seconds and no instances in seconds.

**Comment by KomachiSion** [comment]
There are two possible for your problem:

1. your instances has some problem like FGC and so on, which make the heartbeat can't be send to server.
2. your nacos cluster status is not right, so the data and request may show error.

You do not provide version and more information like logs or steps. We can't help you more. You need check and find out reason by yourself.

**Comment by KomachiSion** [comment]
No response for a long time, close issue first.
