### ISSUE TITLE
权限管控问题

### ISSUE THREAD

**Issue by erdengzhazha** [alibaba/nacos#5755]
问题描述： 
 1. 我创建的一个非nacos管理员用户，  竟然可以修改namespace！！！！ 
 2.在自己的业务服务中连接nacos使用账号密码配置
   spring.cloud.nacos.username=xxxx
   spring.cloud.nacos.password=123456
 明文去传递是不是有安全风险。。。 ， 目前有解决方案吗？

**Comment by KomachiSion** [comment]
1. https://nacos.io/en-us/docs/auth.html
2. 暂时没有，需要和鉴权插件一起重新设计一下。

**Comment by erdengzhazha** [comment]
好的👌谢谢

**Comment by erdengzhazha** [comment]
> 1. [https://nacos.io/zh-CN/docs/auth.html](https://nacos.io/en-us/docs/auth.html)
> 2. 暂时没有，需要和鉴权插件一起重新设计一下。

您好大佬，刚毕业一年的菜鸟 斗胆再问问 ！！！ 第一点 ， 我是真的没有找到 ，普通用户对namespace的限制 ， 只能看到权限的开启（这一步我已经做过了。。。）

看了源码
后端： 这边查询namepace并没有对角色进行过滤
`@GetMapping
    public RestResult<List<Namespace>> getNamespaces(HttpServletRequest request, HttpServletResponse response) {`

前端：是在前端进行权限校验，限制删除和修改的么？ 前端代码我看不懂。。
` rendernamespace(namespaceList) {
    const { nownamespace } = this.state; // 获得当前namespace
    const namespacesBtn = namespaceList.map((obj, index) => {
      const style =
        obj.namespace === nownamespace
          ? { color: '#00C1DE', marginRight: 10, border: 'none', fontSize: 12 }
          : { color: '#666', marginRight: 10, border: 'none', fontSize: 12 };
      return (
        <div key={index} style={{ float: 'left', cursor: 'pointer' }}>
          {index === 0 ? '' : <span style={{ marginRight: 5, marginLeft: 5 }}>|</span>}
          <span
            type={'light'}
            style={style}
            onClick={this.changeNameSpace.bind(this, obj.namespace, obj.namespaceShowName)}
            key={index}
          >
            {obj.namespaceShowName}
          </span>
        </div>
      );
    });
    return <div style={{ paddingTop: 9 }}>{namespacesBtn}</div>;
  }`


![91DD4FBC-7ACE-4D23-BBA0-C527C59B1E7E](https://user-images.githubusercontent.com/43720808/118490752-d8f2f580-b750-11eb-8163-e0f29709ebbc.png)

**Comment by erdengzhazha** [comment]
补充一句，我对xiuer这个用户设置了namespace的权限的，按道理prod这个ns我不该能进行删除，更改操作

**Comment by erdengzhazha** [comment]
没问题了， 我草。。。。这个设计。。这个拦截果然在前端做的。。。。登录普通用户在命名空间处进行修改和删除操作， 
做到最后等点击确认的按钮，前端再去做的拦截，一开始就吓得我都没敢去按。。。
