### ISSUE TITLE
Publisher code optimization

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#5762]
movitation：

1.DefaultPublisher increases the log when the event is lost
2.DefaultSharePublisher does not add subscriber to the parent subscribers. Adding it will not be executed, so it will not be added.

**Comment by KomachiSion** [comment]
For the second changes. Do you think it is a useless codes?

**Comment by xiaoheng1** [comment]
@KomachiSion yes, Because DefaultSharePublisher uses subMappings. If add it to the subscribers of the parent class, it will be misleading on the one hand, and on the other hand, it will increase the cost of traversal of the parent class’s message notifications.

**Comment by KomachiSion** [comment]
What's you think about the first change? 

Should return directly?

**Comment by xiaoheng1** [comment]
> What's you think about the first change?
> 
> Should return directly?

The previous logic is to ignore this message when there is no subscriber. My idea is to add log reminders so that you can find problems later. If it returns directly, it cannot be found later.

**Comment by KomachiSion** [comment]
I think log this waring is ok. But after log waring, can it return directly?

**Comment by xiaoheng1** [comment]
> I think log this waring is ok. But after log waring, can it return directly?

i think it is ok, i will modify it.
