### ISSUE TITLE
当项目用了多个数据源并配置spring.cloud.nacos.config.refreshable-dataids 时线程数不停飙升

### ISSUE THREAD

**Issue by airship-lion** [alibaba/nacos#5764]
使用的nacos版本1.3.2
spring boot 版本  2.1.3.RELEASE
spring-cloud-alibaba 版本 0.9.0.RELEASE
我的项目配置了多数据源，如

spring.datasource.gps.jdbc-url= serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.gps.username=
spring.datasource.gps.password= 
spring.datasource.gps.driver-class-name=com.mysql.jdbc.Driver

spring.datasource.crm.jdbc-url= serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.crm.username= 
spring.datasource.crm.password= 
spring.datasource.crm.driver-class-name=com.mysql.jdbc.Driver

当同时配置了 spring.cloud.nacos.config.refreshable-dataids
的时候线程数会飙升，就算配置没有改动也会升高。
当去掉 spring.cloud.nacos.config.refreshable-dataids 配置  或 只配置一个数据源的时候正常

spring boot admin 的  refreshScope  是DOWN状态
报
errororg.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'crmDataSource': Could not bind properties to 'HikariDataSource' : prefix=spring.datasource.crm, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource.crm' to javax.sql.DataSource | error | org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'crmDataSource': Could not bind properties to 'HikariDataSource' : prefix=spring.datasource.crm, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource.crm' to javax.sql.DataSource
error | org.springframework.boot.context.properties.ConfigurationPropertiesBindException: Error creating bean with name 'crmDataSource': Could not bind properties to 'HikariDataSource' : prefix=spring.datasource.crm, ignoreInvalidFields=false, ignoreUnknownFields=true; nested exception is org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource.crm' to javax.sql.DataSource

但是项目是可以正常运行的

看了nacos的文档
客户端CPU高，或者内存耗尽的问题
问题的现象是依赖Nacos客户端的应用，在运行一段时间后出现CPU占用率高，内存占用高甚至内存溢出的现象，可以参考issue：[https://github.com/alibaba/nacos/issues/1605](https://github.com/alibaba/nacos/issues/1605)。这种情况首先要做的是分析CPU高或者内存占用高的原因，常用的命令有top、jstack、jmap、jhat等。其中一种情况是Nacos客户端实例在Spring Cloud Alibaba服务框架中被反复构造了多次，可以参考issue：[https://github.com/alibaba/spring-cloud-alibaba/issues/859](https://github.com/alibaba/spring-cloud-alibaba/issues/859)。这个问题已经得到了修复，预期会在下个Spring Cloud Alibaba版本中发布。

这个问题是不是类似的，要升级到哪个版本可以解决

**Comment by KomachiSion** [comment]
1. 什么线程数不断飙升？
2. 什么导致CPU高？
3. 0.9.0似乎是非常旧的客户端的了，可能需要升级
4. 配置多数据源会飙升，是不是说不配置多数据源就不会，那是不是多添加的数据源的问题，而非nacos的问题？

**Comment by airship-lion** [comment]
1、项目进程的线程数飙升
2|我理解的是同 #859 类似，不同之处是那里是有刷新配置的时候会创建新Nacos客户端实例。
而我这里是配置没改也这样，Nacos客户端实例 不停创建。
原因感觉是配置多数据源后加上 spring.cloud.nacos.config.refreshable-dataids  ，spring boot admin 监控到的refreshScope 是报错的，然后加上#859 那里的bug导致不停新建Nacos客户端，从而线程数飙升，CPU变高。
3、#859的问题现在哪个版本已经修复了，看文档说后续版本修复，不知道哪个版本已经修复。
4、不配置多数据源不会飙升，不配置spring.cloud.nacos.config.refreshable-dataids 也不会飙升，2个都配置的时候才会飙升。
添加的多数据源本身项目是可以正常访问的，只是refreshScope  会报错。

**Comment by KomachiSion** [comment]
spring.cloud.nacos.config.refreshable-dataids是spring cloud的配置 #859 是nacos客户端的issue。 不是用一个东西。
如果是spring.cloud.nacos.config.refreshable-dataids导致的，建议升级sping cloud版本。应该就能够解决。具体哪个版本修复的可以到SCA社区询问一下

**Comment by kimmking** [comment]
看起来跟这个有关系：https://www.liaochuntao.cn/2019/09/04/java-web-53/

**Comment by ZH379411584** [comment]
我碰到如下的情况，刷新配置，导致Controller销毁，但是这个Controller并发很高，导致 大量线程排队等待销毁，一下子线程数上来，导致CPU飙升。[记一次 nacos 刷新配置导致cpu飙升](https://www.jianshu.com/p/4590af901106)
