### ISSUE TITLE
the service instance list is inconsistent in the nacos 2.0.2

### ISSUE THREAD

**Issue by xiaoqunge** [alibaba/nacos#5769]
**Describe the bug**
after we upgrade nacos client and server form 1.4.1 t0 2.0.1，in a nacos cluster, we have three nodes .about the service instances .Two of the nodes were normal, and the last one had an extra service instance that had been offline for four days and may from 1.4.1.
**Expected behavior**
All nodes should have their consistent list of service instances correctly
**Acutally behavior**
A clear and concise description of what you actually to happen.
Two of the nodes were normal, and the last one had an extra service instance that had been offline for four days.
**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 2.0.1, nacos-client 2.0.1]
 - Module [naming]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**

**Comment by KomachiSion** [comment]
Sorry, I can't get the problem from your description.

Do you means that there are two nodes have services but one has no service?

If so, I suggest you check whether all nodes upgrade to 2.0.X version and run with 2.0 mode.
And whether close double write?

steps like https://nacos.io/en-us/docs/2.0.0-upgrading.html

**Comment by richardo12388** [comment]
Why

**Comment by xiaoqunge** [comment]
After the cluster upgrade is completed, one node still has service instances registered with the 1.4.1 Client in its service instance list, while the other nodes are normal

**Comment by KomachiSion** [comment]
nacos 2.X server is support 1.X client。 So 1.4.1 client register service is right？

You mean the instance and service is unregister, but still exist?

**Comment by xiaoqunge** [comment]
yes

**Comment by xiaoqunge** [comment]
and just in some nodes

**Comment by xiaoqunge** [comment]
leader node is ok

**Comment by KomachiSion** [comment]
try to fix by close double write.

https://nacos.io/en-us/docs/2.0.0-upgrading.html

**Comment by xiaoqunge** [comment]
Double writing has been turned off

**Comment by xiaoqunge** [comment]
而且有意思的是，当我把从节点的本地数据全部删除后，重启服务节点，从节点并没有在从主节点复制全量数据的前提下就提供服务了，这我也觉得是不太对劲的

**Comment by xiaoqunge** [comment]
当没有删除本地数据的时候，重启从节点的服务时服务列表的数据是从本地拉取的，所以错误数据并不能剔除。

**Comment by xiaoqunge** [comment]
我现在怀疑有可能是两个原因导致的，一个是因为新老版本升级过程中有问题导致的，还有一个是因为数据同步的问题，目前我的做法是把nacos 服务端的data，status目录全部删掉然后重启服务，再观察一阵把

**Comment by KomachiSion** [comment]
你注册的是持久化的服务嘛？ 如果不是的话，就没什么联系。

**Comment by KomachiSion** [comment]
Can try to use develop branch and retry. See #5918 .
