### ISSUE TITLE
Nacos banner server port is incorrect

### ISSUE THREAD

**Issue by flystar32** [alibaba/nacos#577]
When I changed the port to 8849, I found that banner still displayed 8848 at startup.

// 当我把端口修改为8849时，发现启动时banner仍然显示8848 

Viewed the banner.txt file under nacos-core

// 查看了nacos-core下的banner.txt文件 

`
     ,--.
   ,--.'|
,--,: : | Nacos 0.7.0
,--.'| ' : ,---. Running in ${nacos.mode} mode
| : : | | ' ,'\ .--.--. Port: 8848
: | \ | : ,--.--. ,---. / / | / / ' Pid: ${pid}
| : ' '; | / \ / . ; ,. :| : /./ Console: http://${nacos.local.ip}:8848/nacos/index.html ' ' ;. ;.--. .-. | / / '' | |: :| : ;_ | | | \ | \__\/: . .. ' / ' | .; : \ \ . https://nacos.io
' : | ; .' ," .--.; |' ; :__| : | ----. \ | | '--' / / ,. |' | '.'|\ \ / / /--' / ' : | ; : .' \ : : ----' '--'. /
; |.' | , .-./\ \ / --'---' '---' -----' ----'
`
Here the port is written to death and should be dynamically retrieved with placeholders

// 这里把端口写死了，应该用占位符动态获取 

This issue is feedback from here, https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/241

// 这个 issue  是从这里反馈过来的， https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/241

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by hxy1991** [comment]
#512
