### ISSUE TITLE
nacos 2.0.1 内存问题

### ISSUE THREAD

**Issue by anryHan** [alibaba/nacos#5770]
生产上大概有两百多个服务实例，属于预上线阶段，目前几乎没有什么访问量
使用nacos 版本是2.0.1 （客户端，服务端），nacos内存随时间使用慢慢升高，
（4台nacos构成集群，每台堆内存4G，新生代2G）
请问这个不会有什么隐患吧？配置中心的内容也很少，但是nacos监控有时候最高的内存超过80%

[
<img width="943" alt="屏幕快照 2021-05-18 15 54 23" src="https://user-images.githubusercontent.com/13831076/118614583-7f430780-b7f2-11eb-83e5-2d4fc309c340.png">
](url)

**Comment by KomachiSion** [comment]
这个是正常的， 和JVM参数设置有关（可以自行搜索一下相关内容）。

主要关注点在于内存占用量是否会超出你设置的最大内存过多以及程序的GC情况。
重点在于GC， 如果完全没有FGC，只有不频繁的YGC。那么就不会有问题。

**Comment by anryHan** [comment]
> 这个是正常的， 和JVM参数设置有关（可以自行搜索一下相关内容）。
> 
> 主要关注点在于内存占用量是否会超出你设置的最大内存过多以及程序的GC情况。
> 重点在于GC， 如果完全没有FGC，只有不频繁的YGC。那么就不会有问题。

看了gc日志，并没有Full GC出现，但是YGC差不多7-8分钟一次。
两百多个服务，在没有什么访问量的情况下，nacos 4G堆内存到达80%? 是正常情况吗？
YGC大概能从70% 左右回收到20%，正常情况下在垃圾回收完成后nacos会重新创建很多对象吗？

**Comment by KomachiSion** [comment]
正常啊， 因为你的请求会不断的尝试占用新内存。 堆内存一旦申请不会返回给系统。这就是java的jvm机制。如果你确定用不到那么大的堆内存 可以把堆调小。注意GC频率即可。

从你反馈的GC频率和回收率来看，完全没有问题。
