### ISSUE TITLE
[Code Quality] [nacos-client] [sub issue] improve the code quality of module nacos-client. 

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5771]
## Description

Module: nacos-address

This issue is the sub issue of #5726 , it will improve the code quality of module nacos-client. I take a look at this module, find that the files and problems are little. so we will improve the code quality by whole module.

**Comment by brotherlu-xcq** [comment]
Hi, @realJackSun . If you have no time to do it, you can assign it to me.
