### ISSUE TITLE
1.xupgraded2.0.1, "upgrade check result false"

### ISSUE THREAD

**Issue by yumin5723** [alibaba/nacos#5785]
The service can be used normally, but the upgrade check result is still false in the log after about an hour. How long does this process take?

**Comment by KomachiSion** [comment]
Still print `upgrade check result false` means the services and instances in 1.x mode is different with 2.x mode. 

Can you provide more information? Or downgrade to old version and remove all v2 data. Then upgrade again with https://nacos.io/en-us/docs/2.0.0-upgrading.html
