### ISSUE TITLE
nacos 注册的服务自动清理了 services are automatically cleaned

### ISSUE THREAD

**Issue by qzy-joe** [alibaba/nacos#5799]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
nacos 启动成功后，注册成几个服务后，有一个服务注册失败，查看nacos的日志naming-server.log。显示该服务：
2021-05-20 17:23:10,705 WARN namespace : public, [DEFAULT_GROUP@@designer-solr] services are automatically cleaned
不知道有没有谁遇到过，能给我一个建议。
如下图：
![1621505857(1)](https://user-images.githubusercontent.com/32728026/118962889-7429dc00-b998-11eb-97ae-f59eb0b3aff9.jpg)

![1621506252(1)](https://user-images.githubusercontent.com/32728026/118963052-a1768a00-b998-11eb-90b9-03676e6640a4.png)

**Comment by JackSun-Developer** [comment]
nacos会定期清理空服务，如果服务下面没有实例，就会被清理掉。

**Comment by KomachiSion** [comment]
如果您不希望清理空服务，可以调整`nacos.naming.clean.empty-service.interval` 参数，把间隔调大。我们推荐定期清理空服务，释放内存资源。

**Comment by qzy-joe** [comment]
> nacos会定期清理空服务，如果服务下面没有实例，就会被清理掉。

谢谢你的分享，nacos判断空服务的标准是什么，我看服务是正常启动的，注册nacos也显示成功，但是过两分钟就看到日志显示，该服务被清理了。

**Comment by qzy-joe** [comment]
> nacos.naming.clean.empty-service.interval

我在nacos的配置文件application.properties里面没有看到这个参数，但是有如下三个参数：
nacos.naming.empty-service.auto-clean=false
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000

auto-clean这个参数的默认值是true，我改成了false，也没有效果。能说明下你说的这个参数的配置方法吗

**Comment by KomachiSion** [comment]
最初nacos是没有删除空服务的
nacos.naming.empty-service.auto-clean=false 这个参数是添加删除空服务后，用于兼容旧版本而加的开关，只有1.X版本生效
2.X版本已废弃，可以讨论是否还需要添加回去

另外两个配置同样在经过重构后也在2.X版本废弃。

新的配置应该是
```
nacos.naming.clean.empty-service.interval（扫描间隔）
nacos.naming.clean.empty-service.expired-time（空服务删除过期时间，默认1min）
```

**Comment by qzy-joe** [comment]
> 最初nacos是没有删除空服务的
> nacos.naming.empty-service.auto-clean=false 这个参数是添加删除空服务后，用于兼容旧版本而加的开关，只有1.X版本生效
> 2.X版本已废弃，可以讨论是否还需要添加回去
> 
> 另外两个配置同样在经过重构后也在2.X版本废弃。
> 
> 新的配置应该是
> 
> ```
> nacos.naming.clean.empty-service.interval（扫描间隔）
> nacos.naming.clean.empty-service.expired-time（空服务删除过期时间，默认1min）
> ```

好的，谢谢你的分享

**Comment by qzy-joe** [comment]
问题已解决

**Comment by zengjun630** [comment]
请问是什么问题，我碰到了一个问题：某个服务重启时，会导致另外一个服务从Nacos下线。然后从日志中看到： WARN namespace : services are automatically cleaned

**Comment by qzy-joe** [comment]
我也忘记了当时怎么解决的，后来就好了.可以用最新版本的nacos试试，再就是配置的时候最好注意重名的情况

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月30日 15:52 |
| 收件人 | alibaba/nacos ***@***.***> |
| 抄送人 | qzy-joe ***@***.***>,
State ***@***.***> |
| 主题 | Re: [alibaba/nacos] nacos 注册的服务自动清理了 services are automatically cleaned (#5799) |

请问是什么问题，我碰到了一个问题：某个服务重启时，会导致另外一个服务从Nacos下线。然后从日志中看到： WARN namespace : services are automatically cleaned

**Comment by wingyiu** [comment]
使用 weight=0  替代enabled=false
