### ISSUE TITLE
spring-cloud-starter-bus-amqp整合问题

### ISSUE THREAD

**Issue by xiaohuziaps** [alibaba/nacos#581]
When the project refers to the spring-cloud-starter-bus-amqp package, the status of service discovery is shown as STARTING, and other services cannot find the service:

// 当项目引用了spring-cloud-starter-bus-amqp包后，服务发现的状态显示为STARTING ，其它服务就无法找到该服务： 

![image](https://user-images.githubusercontent.com/3488917/50751032-d29c0700-1282-11e9-92f0-0aacf05d4690.png)
Is there a configuration problem or a package conflict?

// 请问是否配置问题还是包有冲突？

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by xiaohuziaps** [comment]
引用版本如下：
``<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Finchley.SR1</version>
                <type>pom</type>
                <scope>import</scope>
 </dependency>
 <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.2.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>

**Comment by nkorange** [comment]
SpringCloudAlibaba doesn't work with Eureka.
