### ISSUE TITLE
Why his_config_info is so big?It's comsumed almost 17GB table space.

### ISSUE THREAD

**Issue by N0mansky** [alibaba/nacos#5811]
**Describe the bug**
I am using nacos cluster mode base on 1.4.0,and  I found his_config_info was unreasonable growing up to 17 GB.After that, it's stop growing up. 
I thought configuration record retained for 30 days is the reason which it so big,but after 2 month later the his_config_info  doesn't have any shrink, and i didn't find any configurations can deal with this probleam.

**Expected behavior**
The his_config_info table should keep in a resonable size ,not more than 2GB or smaller.

**Acutally behavior**
The his_config_info table comsumed almost  17GB table space.

**How to Reproduce**
1. Set up nacos cluster with 3 nodes.
2. Check MySQL table size

**Desktop (please complete the following information):**
 - OS: CentOS 7.4
 - Version [nacos-server 1.4.0]
 - Module [config]
 - SDK [dubbo]

**Additional context**
The following is his_config_info sql snippet example.
```
INSERT INTO `nacos`.`his_config_info`(`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`) VALUES (206547, 1517021, 'com.pingxx.id.api.IDGeneratorRpcService:1.0.0::consumer:report', 'dubbo', '', '{\"init\":\"false\",\"side\":\"consumer\",\"release\":\"2.7.8\",\"methods\":\"parseID,getID,getIdQueue,getIDResult\",\"dubbo\":\"2.0.2\",\"check\":\"false\",\"interface\":\"com.pingxx.id.api.IDGeneratorRpcService\",\"version\":\"1.0.0\",\"qos.enable\":\"false\",\"revision\":\"1.0.0\",\"metadata-type\":\"remote\",\"application\":\"report\",\"sticky\":\"false\",\"mock\":\"false\"}', '34e7cb364298ba5bd706c11cd3dd3a3c', '2021-05-21 05:27:46', '2021-05-21 05:27:47', NULL, '172.16.16.145', 'U', '1742c5b8-550b-4eb5-a4ee-f687d89a037f');
```

**Comment by JackSun-Developer** [comment]
Maybe your configuration very frequently modified?This table is used to cache the history of configuration.

**Comment by N0mansky** [comment]
> Maybe your configuration very frequently modified?This table is used to cache the history of configuration.

Thanks for your reply. If i  don't need history data,can i just truncate his_config_data table?

**Comment by KomachiSion** [comment]
> > Maybe your configuration very frequently modified?This table is used to cache the history of configuration.
> 
> Thanks for your reply. If i don't need history data,can i just truncate his_config_info table?

Of course you can. But if you truncate this table, you will not rollback the history config.

**Comment by N0mansky** [comment]
I decided to empty his_config_info
