### ISSUE TITLE
nacos长轮询如何解决客户端断开导致的半关闭问题

### ISSUE THREAD

**Issue by Novery** [alibaba/nacos#5812]
当nacos服务端与客户端建立连接后
在服务端hold等待数据变更时，客户端断开，发起TCP FIN包
服务端因为未有数据变更或到单次轮询时间，是否导致此时处于TCP CLOSE_WAIT状态
nacos是否尝试处理这种半关闭状态

**Comment by KomachiSion** [comment]
会，到达轮训时间后会回复response，之后就会关闭了。
