### ISSUE TITLE
The property 'nacos.inetutils.prefer-hostname-over-ip' in application.properties does not work.

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#5816]
### What the bug is

When I set the property 

> nacos.inetutils.prefer-hostname-over-ip=true

Nacos still regard IP address , instead of the host name,  as local address. 

It may be caused by this line:
![image](https://user-images.githubusercontent.com/58767027/119221353-86835180-bb21-11eb-9ccf-d0b11779b03d.png)

I think the 'if' this line cannot be satisfied, becaused the hostName cannot equals to the IP address.

### What it will bring about

In some case, this may cause a redundant member in ServerMemberManager, e.g., If I use k8s to deploy my nacos, and configure the cluster.conf as:

```
hostname1.svc.cluster.local
hostname2.svc.cluster.local
hostname3.svc.cluster.local
```
If the local address is 192.168.0.3, it will change the cluster.conf into:

```
192.168.0.3
hostname1.svc.cluster.local
hostname2.svc.cluster.local
hostname3.svc.cluster.local
```

Then an redundant member will be addded.

**Comment by KomachiSion** [comment]
I'm not sure whether this judgment is useless. We need more discussion.
