### ISSUE TITLE
Can user remove raft logic?

### ISSUE THREAD

**Issue by Xezeloh** [alibaba/nacos#5822]
**Is your feature request related to a problem? Please describe.**
We use Nacos only as registry and register only ephemeral instances to Nacos, in the other words we don't have any demand on raft logic, but those raft-related logic still starts threads and cost memory and CPU. So I am wondering if there are some ways to remove the raft logic or just keep them unstarted.

**Describe the solution you'd like**
We use Nacos at version 1.3.2, is there any way to easy remove raft logic? Other than persistent instances, which data is synced by raft? In the future, can Nacos uncouple specific consistency protocol from data type, so that we can choose consistency protocol for each data type and keep those unused consistency protocol unstarted?

**Describe alternatives you've considered**

**Additional context**

**Comment by weissxu** [comment]
**There is no way to do that!**

But, in the future plan of 2.x, with plugins feature ,may nacos meet the needs of you, ofcource my needs too!

**Comment by JackSun-Developer** [comment]
Approve @weissxu , Currently not way to remove the raft logic, but after nacos supporting plugins, users can decide the functions they want to close.

**Comment by KomachiSion** [comment]
Maybe can't remove for a short time.

The persistency service and metadata need raft to keep consistency. So it's hard to remove.

We only will remove old self-implementation raft in 2.1.X and only keep the Jraft implementation.

**Comment by Xezeloh** [comment]
> Maybe can't remove for a short time.
> 
> The persistency service and metadata need raft to keep consistency. So it's hard to remove.
> 
> We only will remove old self-implementation raft in 2.1.X and only keep the Jraft implementation.

Why is metadata kept consistency by Raft instead of Distro?

**Comment by KomachiSion** [comment]
Because metadata is the ops information, which is only controlled by operator not app. So we think the metadata should to be persist so that it can be failover when server has problem.

 In future design, you can register new ephemeral service and instance with init metadata when raft has problem, but it is hard to modified metadata and status by controller. Because if raft has problem, the nacos cluster is in unhealthy, need some fixes and entry an protection mode.

**Comment by Xezeloh** [comment]
> Because metadata is the ops information, which is only controlled by operator not app. So we think the metadata should to be persist so that it can be failover when server has problem.
> 
> In future design, you can register new ephemeral service and instance with init metadata when raft has problem, but it is hard to modified metadata and status by controller. Because if raft has problem, the nacos cluster is in unhealthy, need some fixes and entry an protection mode.

后面那段方便用中文表达下不，有点没看懂😂

**Comment by KomachiSion** [comment]
> > Because metadata is the ops information, which is only controlled by operator not app. So we think the metadata should to be persist so that it can be failover when server has problem.
> > In future design, you can register new ephemeral service and instance with init metadata when raft has problem, but it is hard to modified metadata and status by controller. Because if raft has problem, the nacos cluster is in unhealthy, need some fixes and entry an protection mode.
> 
> 后面那段方便用中文表达下不，有点没看懂😂

之后能够在raft出问题后继续注册和使用非持久化实例和服务，只是不能通过控制台修改其元数据和运行状态。因为如果raft协议出现问题，集群其实是处于非健康的状态，需要进行一定的修复，所以进入了一个保护状态，只能使用部分功能。
