### ISSUE TITLE
nacos-consistency  缺少 entity

### ISSUE THREAD

**Issue by gp16860** [alibaba/nacos#5827]
![image](https://user-images.githubusercontent.com/57736919/119302997-97ee6a00-bc97-11eb-848b-f4174dfe61a8.png)

![image](https://user-images.githubusercontent.com/57736919/119303136-d08e4380-bc97-11eb-80af-7e0740cc8db4.png)

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/faq.html#3.19
