### ISSUE TITLE
Demo Error Information on NacosDiscovery Official Website

### ISSUE THREAD

**Issue by bilaisheng** [alibaba/nacos#583]
Official website demo address:

// 官网demo地址： 

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery
1. There is less information about configuration items.

// 1、配置项信息中少了关于 

spring.cloud.nacos.discovery.cluster-name  
This note.

// 这个的说明。 

There are 14 configuration items under discovery. Only 13 configuration explanations are given on the official website.

// discovery下一共有14个配置项。官网上只给出了13个配置项解释 

2. Annotation errors

// 2、注释错误 

![image](https://user-images.githubusercontent.com/20394370/50760046-a5128600-12a1-11e9-8df3-4e03343c76f5.png)
3、Provider -> application.properties 中name为【nacos-producer】
Under Consumer, the acquisition becomes a nacos-provider, resulting in instances not being available. NullPointException.

// 到了Consumer下面获取就变成了【nacos-provider】，导致instance获取不到. NullPointException。

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by xuechaos** [comment]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/244
