### ISSUE TITLE
Nacos 1.4.2 管控台创建用户多一个 ',' 前缀

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#5835]
![image](https://user-images.githubusercontent.com/16837364/119346234-896e7580-bccc-11eb-97a0-a1b1f0277241.png)

![image](https://user-images.githubusercontent.com/16837364/119346248-8e332980-bccc-11eb-9960-bcb1602c53f5.png)

看出原因是 url 上拼了一段 &username=
所以变成了  username  数组，spring 解析 成 ,xxxx

**Comment by li-xiao-shuang** [comment]
@i will solve it@
