### ISSUE TITLE
Servermanager.java method of putserviceandinit does not need to get the service from the map again, just use the service of the input parameter

### ISSUE THREAD

**Issue by lilei0527** [alibaba/nacos#5844]
![image](https://user-images.githubusercontent.com/55618021/119475864-1a525900-bd80-11eb-9772-6992c8f4dc6f.png)

**Comment by KomachiSion** [comment]
Please do not remove this line.

This line is to solve thread safe problem.

You can use annotate to  find out relative issue and PR.

**Comment by lilei0527** [comment]
Yes,I get it

**Comment by lilei0527** [comment]
能否给public void putService(Service service)添加上返回值，比如

public Service putService(Service service) {
        if (!serviceMap.containsKey(service.getNamespaceId())) {
            synchronized (putServiceLock) {
                if (!serviceMap.containsKey(service.getNamespaceId())) {
                    serviceMap.put(service.getNamespaceId(), new ConcurrentSkipListMap<>());
                }
            }
        }
      return  serviceMap.get(service.getNamespaceId()).putIfAbsent(service.getName(), service);
    }

这样是不是可以少一次map查询 @KomachiSion
