### ISSUE TITLE
InitUtils.java The method of initNamespaceForNaming has redundant codes

### ISSUE THREAD

**Issue by lilei0527** [alibaba/nacos#5845]
<img width="358" alt="微信截图_20210525174855" src="https://user-images.githubusercontent.com/55618021/119477558-a3b65b00-bd81-11eb-8f73-7a07e2828ed3.png">
<img width="694" alt="微信截图_20210525174925" src="https://user-images.githubusercontent.com/55618021/119477563-a44ef180-bd81-11eb-98a1-0dbbe37da19e.png">

**Comment by mask616** [comment]
@i will solve it@
