### ISSUE TITLE
讨论 ServerMemberManager 和 ServerListManager 在职责上的划分

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#5849]
ServerMemberManger 和 ServeerListManager 在功能上有重合，是否考虑使用 ServerMemberManager 来取代 ServerListManager ?

**Comment by KomachiSion** [comment]
是这么设计的，ServerListManager是1.3以前使用的，用来维护节点间状态的。

1.3之后使用ServerMemberManger，ServerListManager作为兼容保留，并且调用ServerListManager作为实际存储。

计划在2.1版本删除对1.3版本的升级兼容，就会删除ServerListManager

**Comment by xiaoheng1** [comment]
明白了，感谢答复
