### ISSUE TITLE
Nacos server-side 'contextPath' changes

### ISSUE THREAD

**Issue by tian-qingzhao** [alibaba/nacos#5858]
The client sends the service registration to the server. 
If the server's contextPath is changed, the client will not find the server's address,
 because the client module requests the server interface's contextPath with a fixed value of 'nacos',
 as well as the interface that sends the heartbeat.
So I think this place can add a configuration to make it more flexible?
![nacos1](https://user-images.githubusercontent.com/57293296/119618542-98246c00-be35-11eb-83d7-13df6dc5ef87.png)
![nacos2](https://user-images.githubusercontent.com/57293296/119618547-98bd0280-be35-11eb-9098-43a1528a3028.png)

**Comment by KomachiSion** [comment]
I remember new version seem fix this problem, you can search issue to find out.

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/issues/5668
