### ISSUE TITLE
注册问题——服务列表中服务时有时无

### ISSUE THREAD

**Issue by wytjiayou** [alibaba/nacos#5859]
**Describe the bug**
服务端三节点集群部署，客户端配置三个服务端地址，没有修改其他默认的配置，如心跳检测时间间隔等等。服务启动注册到nacos服务正常，运行一段时间后在nacos服务列表中发现服务不存在，但服务仍在正常运行，刷新后又注册上来，再刷新又被nacos剔除。排除服务不健康和网络原因，因为同一台服务器上还部署了其他n个服务，都能与nacos保持正常心跳。

**Desktop (please complete the following information):**
 - Version [e.g. nacos-server 1.4.0, nacos-client 1.3.3]

**Comment by chouxiaozi1989** [comment]
我也发现这个问题了，leader上的实例列表是全的，但是follower节点上不是，启动后会有一会儿注册正常，然后就被剔除了，naming-server.log中显示healthy是false

**Comment by KomachiSion** [comment]
看描述很像是起了3台standalone模式，没有组成集群，因为心跳是随机发送的，所以看上去像是一直在不停的移除，注册。

建议排查下集群部署是否正确。正常组成的话只有1个节点会移除服务。

或者升级版本，再尝试。

**Comment by wytjiayou** [comment]
> 看描述很像是起了3台standalone模式，没有组成集群，因为心跳是随机发送的，所以看上去像是一直在不停的移除，注册。
> 
> 建议排查下集群部署是否正确。正常组成的话只有1个节点会移除服务。
> 
> 或者升级版本，再尝试。

配置了cluster.conf ，以集群模式启动的，组成了集群

**Comment by KomachiSion** [comment]
那就升级版本再试试， 可能是触发了什么问题。根据描述也不好判断。

**Comment by KomachiSion** [comment]
Any process？

**Comment by KomachiSion** [comment]
No more response from author and not enough information to judge problem.
