### ISSUE TITLE
core-auth.log 疯狂输出 WARN Invalid server identity value for serverIdentity from xxx

### ISSUE THREAD

**Issue by cjk87927** [alibaba/nacos#5861]
ip是nginx的ip,用于转发至后端3台nacos

![image](https://user-images.githubusercontent.com/6744728/119629120-4c2af480-be40-11eb-9e68-f58925717277.png)

- OS:Centos 7.7
- Version nacos-server 2.0.1
- 配置了:
1. nacos.core.auth.enabled=true
2. nacos.core.auth.enable.userAgentAuthWhite=false
3. nacos.core.auth.server.identity.key=xxx
4. nacos.core.auth.server.identity.value=yyy

- 原因:心跳检测是没有携带相应的头(不限于心跳,所有客户端的访问都会出现这个问题)
- 代码:com.alibaba.nacos.core.auth.AuthFilter, line:89
- url:/v1/ns/instance/beat

nacos.core.auth.server.identity.key/nacos.core.auth.server.identity.value不应该是只影响集群内部的通信?为什么还会影响客户端的调用

**Comment by KomachiSion** [comment]
因为权限校验是对所有http请求。换成2.0.1客户端就不会了

**Comment by cjk87927** [comment]
> 因为权限校验是对所有http请求。换成2.0.1客户端就不会了

感谢回复
Java Client 换成了 2.0.1
还是会有相应的警告,只是获取配置,监听不会再报警告, 通过http鉴权的时候还会有,请问这是正常的吗?

**Comment by KomachiSion** [comment]
login应该只会报1～2次，不会一直有。这个告警就是一个提示。提示方式可以优化，这个问题可以忽略。

**Comment by cjk87927** [comment]
了解,建议优化下这块,不然容易引起歧义
