### ISSUE TITLE
registerInstance 注册覆盖前面的实例，不能注册多实例

### ISSUE THREAD

**Issue by tonyfud** [alibaba/nacos#5863]
NamingService.registerInstance

使用的 nacos-client. 2.0.1
nacos server. 阿里云的 微服务治理， nacos 2.0 版本。

用 clinet 的这个方法进行 注册服务， 会覆盖前面的服务，多个服务端口不一样的情况下。 

 是我使用不正确吗 ？ 还是有问题存在？

2 个实例， ip 不一样。  103， 先注册成功到 nacos ， 后面到 23 注册时， 103 会被覆盖掉。 在nacos 列表里找不到了。
serviceName=MARKETING.CENTER-INNER-SERVICE, Ip=192.168.0.103, port=8080
serviceName=MARKETING.CENTER-INNER-SERVICE, Ip=192.168.0.23, port=8080

NamingService.registerInstance(instance.getAppName(), "DEFAULT_GROUP", instance.getIPAddr(), instance.getPort());

**Comment by tonyfud** [comment]
使用的  nacos-client. 2.0.1

**Comment by tonyfud** [comment]
nacos server.  阿里云的 微服务治理， nacos 2.0 版本。

**Comment by KomachiSion** [comment]
同一个客户端注册同一个服务的不同实例？

这是什么需求？  同一个客户端注册同一个服务的实例，理论上就是应该覆盖吧。

**Comment by tonyfud** [comment]
https://github.com/nacos-group/nacos-sync/issues/235

我使用这个 nacos-sync 的时候 没法吧 相同服务名，多实例同步到 nacos 2.0 . 然后我去看了下他的 同步代码 发现是用 NamingService.registerInstance 这个方法来注册服务到 nacos 上， 所以就来这么请教一下了。 

![image](https://user-images.githubusercontent.com/15663374/119757457-8eebdb80-bed7-11eb-8a80-5f7f940ff9d8.png)

**Comment by KomachiSion** [comment]
那就是需要一个batch注册的接口，正常的注册覆盖应该才是正确的。

**Comment by brotherlu-xcq** [comment]
批量注册的话，我们现在的数据模型会有影响吗？因为我们现在clientId和service还有instance是一一对应的。如果需要支持这个功能的话，好像和数据模型有些冲突。

**Comment by KomachiSion** [comment]
batch的时候需要将多个Instance合并成一个Instance，并且在生成数据的时候需要进行一定的解析。

**Comment by zrlw** [comment]
看了一下SOFARegistry使用的clientId是sourceAddress+targetAddress，感觉可以借鉴。

**Comment by zrlw** [comment]
如果觉得目前的鉴权机制不够用，可以考虑增加代理注册地址白名单配置，把nacos sync地址加进来，对于来自代理注册地址白名单的请求，按1.x的clientId规则取clientId。

**Comment by wangwei-ying** [comment]
> batch的时候需要将多个Instance合并成一个Instance，并且在生成数据的时候需要进行一定的解析。

有没有人做这个batch的功能，我这边打算加下这个功能，确实是需要多集群同步，nacos线上挂了两次，

**Comment by wangwei-ying** [comment]
> 可否将InstanceRequestHandler的registerInstance和deregisterInstance方法里调用clientOperationService注册或解注册方法时传入的clientId从 meta.getConnectionId()改为IpPortBasedClient.getClientId(request.getInstance().toInetAddr(), request.getInstance().isEphemeral()) ?这样就和1.x的clientId保持一致了。

老哥有解决这个双中心的问题吗

**Comment by zz630** [comment]
> > batch的时候需要将多个Instance合并成一个Instance，并且在生成数据的时候需要进行一定的解析。
> 
> 有没有人做这个batch的功能，我这边打算加下这个功能，确实是需要多集群同步，nacos线上挂了两次，

试了下sync用多个NacosNamingService去注册，不到1k实例不一会就报错OutOfMemoryError: unable to create new native thread。
感觉就算用了2.xclient的sync可以注册多个同service的实例到nacos也不靠谱，sync一挂，同步过去的实例又全部没了。多sync重复执行相同同步任务的话不知道可不可以，但nacos的连接量就上去。觉得sync注册实例实例会好一些

**Comment by jefferson-chern** [comment]
> > 可否将InstanceRequestHandler的registerInstance和deregisterInstance方法里调用clientOperationService注册或解注册方法时传入的clientId从 meta.getConnectionId()改为IpPortBasedClient.getClientId(request.getInstance().toInetAddr(), request.getInstance().isEphemeral()) ?这样就和1.x的clientId保持一致了。
> 
> 老哥有解决这个双中心的问题吗

请教一下，你们现在用的是nacos2.x吗？这个多中心同步的问题现在怎么解决的？

**Comment by jefferson-chern** [comment]
> > > batch的时候需要将多个Instance合并成一个Instance，并且在生成数据的时候需要进行一定的解析。
> > 
> > 
> > 有没有人做这个batch的功能，我这边打算加下这个功能，确实是需要多集群同步，nacos线上挂了两次，
> 
> 试了下sync用多个NacosNamingService去注册，不到1k实例不一会就报错OutOfMemoryError: unable to create new native thread。 感觉就算用了2.xclient的sync可以注册多个同service的实例到nacos也不靠谱，sync一挂，同步过去的实例又全部没了。多sync重复执行相同同步任务的话不知道可不可以，但nacos的连接量就上去。觉得sync注册实例实例会好一些

感觉更多的应该是去修改nacos的代码，让nacos支持nacos-sync，增加批量注册，然后nacos-sync去调用这个批量注册的接口。

**Comment by zrlw** [comment]
> > 可否将InstanceRequestHandler的registerInstance和deregisterInstance方法里调用clientOperationService注册或解注册方法时传入的clientId从 meta.getConnectionId()改为IpPortBasedClient.getClientId(request.getInstance().toInetAddr(), request.getInstance().isEphemeral()) ?这样就和1.x的clientId保持一致了。
> 
> 老哥有解决这个双中心的问题吗

我们目前用的自己修改的1.4.2版本以便做sync同步双中心，后续打算换其他注册中心软件了。

**Comment by zrlw** [comment]
我在nacos-sync提了一个nacos2集群之间批量同步临时实例的PR：https://github.com/nacos-group/nacos-sync/pull/335
nacos2新增的批量注册接口只支持临时实例，所以这个PR解决不了nacos2集群之间同步持久化实例的问题。
