### ISSUE TITLE
nacos心跳检测上报失败

### ISSUE THREAD

**Issue by bugDesigner1** [alibaba/nacos#5864]
问题背景：本项目UserService中由于方法和参数过大，导致client上报nacos server 心跳时url拼接参数过长报错400 bad request

问题：为什么不采用post请求方式 将方法名和请求参数放在请求体中呢

**Comment by KomachiSion** [comment]
1. 心跳从定义上应该是PUT
2. 最早期版本没有使用body，不知道为什么。之后为了兼容只能继续沿用

可以尝试更换2.0版本，就不会有心跳问题了。
