### ISSUE TITLE
mvn -Prelease-nacos clean install -U 各种报错

### ISSUE THREAD

**Issue by pptfz** [alibaba/nacos#5867]
下载源码包，执行 `mvn -Prelease-nacos clean install -U` 各种报错，有能通过的没？有的话发个详细操作步骤吧，官方文档中啥也没写。mavnen3.2.5版本
![image](https://user-images.githubusercontent.com/44946546/119760542-c5782500-bedc-11eb-8a1e-038f4a4448ca.png)

**Comment by KomachiSion** [comment]
升级maven试试看， 我本地3.6.3版本 在nacos根目录上执行 没有问题

**Comment by KomachiSion** [comment]
最多是有可能用例不过

**Comment by pptfz** [comment]
最新版3.8.1也试了，不好使，难道是版本太高？
这官方文档是啥也不写啊，已经排了一堆坑了

**Comment by KomachiSion** [comment]
mvn打包要什么文档。。  就在根目录执行一个命令而已。

看报错好像是找不到类。估计还是环境问题。

**Comment by coderDylan** [comment]
跳过测试吧

**Comment by pptfz** [comment]
不会弄。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by anryHan** [comment]
我本地也是3.6.3 启动源码各种报错，各种少类，少包

**Comment by pptfz** [comment]
> 我本地也是3.6.3 启动源码各种报错，各种少类，少包

有解决方法没，跪求，我这里是无解

**Comment by bywwcnll** [comment]
![image](https://user-images.githubusercontent.com/14292067/120255313-3bee9b80-c2be-11eb-8cb2-27f51ea4350b.png)
刚试的，没问题

**Comment by KomachiSion** [comment]
源码启动少类少包的看官方文档FaQ

用mvn install打包出错的只能自己查问题了。

github CI自动环境都跑了这么久了 没有问题。

**Comment by pptfz** [comment]
各位牛逼  先撤一步
