### ISSUE TITLE
/actuator/env 可以读取到系统配置

### ISSUE THREAD

**Issue by ZhaiRuiPu** [alibaba/nacos#5868]
nacos/actuator/env 暴露出服务的相关配置 
2.0.1

**Comment by ZhaiRuiPu** [comment]
/nacos/actuator/heapdump

**Comment by KomachiSion** [comment]
actuator是springboot提供的能力，如果不需要在配置文件中自行关闭即可。

**Comment by KomachiSion** [comment]
https://docs.spring.io/spring-boot/docs/2.3.1.RELEASE/reference/html/production-ready-features.html#production-ready-endpoints
