### ISSUE TITLE
nacos会自动删除空服务,有没有不自动删除的方法

### ISSUE THREAD

**Issue by liutaot** [alibaba/nacos#5876]

**Comment by WywTed** [comment]
-Dnacos.naming.empty-service.auto-clean=false

**Comment by KomachiSion** [comment]
什么版本 1.X的话 在application中配置`nacos.naming.empty-service.auto-clean=false`

2.X的话 无法关闭，但是可以调整删除时间`nacos.naming.clean.empty-service.expired-time` 单位ms

**Comment by WywTed** [comment]
> 2.X的话 无法关闭，但是可以调整删除时间`nacos.naming.clean.empty-service.expired-time` 单位ms

基于什么考虑去掉了直接删除的控制呢，为什么不保留两个钟策略呢？

**Comment by KomachiSion** [comment]
因为没有必要，空服务为什么要一直保留呢？ 长时间没有实例的服务可能就是已经下线掉的服务，自动移除没有问题。

无非就是过期时间的判定可能不通罢了，所以过期时间是可以配置的。

原本v1中加开关也只是为了兼容性，并不是说不该移除。

至于是否需要有这种策略， 得根据实际需求来，如果确实有合理场景需要，那么加一个开关是很容易的事情。
