### ISSUE TITLE
schema.sql、nacos-mysql.sql标准到底使用哪个

### ISSUE THREAD

**Issue by dislazy** [alibaba/nacos#5880]
**Describe the bug**
看了issue（结论没给出），看了官方文档（给的是nacos-mysql.sql），然后比对  schema.sql、nacos-mysql.sql 发现差别还是挺大的，官方能不能给一个标准的说法，到底初始化数据库用哪个sql文件

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by dislazy** [comment]
nacos版本是2.0.1，看官网的https://nacos.io/zh-cn/docs/2.0.0-upgrading.html 升级文档中描述说1.4版本和2.0.1版本数据表不一致，也没说明白哪不一致

**Comment by KomachiSion** [comment]
1. 两个文件使用的是不同数据库，你使用哪个数据库就比对哪个。
2. 升级文档没有说表结构不一致啊，说的是 数据结构 不一致，不是表结构，请不要自行想象。
3. 文档里已经给出明确的说法了nacos-mysql.sql，是因为derby数据库不需要你去初始化，程序会用sql文件自己去初始化， 你要做的就是按照文档说的用nacos-mysql.sql去初始化就行了。

**Comment by dislazy** [comment]
好的  感谢

**Comment by yjqg6666** [comment]
https://github.com/alibaba/nacos/issues/344#issuecomment-449925187  建议修改一下文件名。
