### ISSUE TITLE
NacosRegistryFactory  setProperties Parameter bug

### ISSUE THREAD

**Issue by yulei-helian** [alibaba/nacos#5881]
![image](https://user-images.githubusercontent.com/84949441/119923101-b4461b80-bfa3-11eb-965b-bf5f1f0a7839.png)
1、setProperties In the method NAMESPACE Parameter repeat call ,meaningless
2、NacosConfigProperties.configServiceInstance()  CONTEXT_PATH  never assign to properties
![image](https://user-images.githubusercontent.com/84949441/119923276-fd966b00-bfa3-11eb-85f9-ce6c01764171.png)

**Comment by KomachiSion** [comment]
Please move issue to SCA community
