### ISSUE TITLE
nacos2.0.1-编辑配置界面，发布配置，前端提示报错，导致不能发布配置

### ISSUE THREAD

**Issue by soladed** [alibaba/nacos#5883]
![image](https://user-images.githubusercontent.com/39592842/119949098-1e72b680-bfcc-11eb-95cb-d3b16cb94b49.png)
查看配置的详情界面的版本比较弹窗，也存在这个问题。

**Comment by brotherlu-xcq** [comment]
@soladed 我在Chrome浏览器下试了一下，没有复现你出现的这个问题。你可以把你的js请求的network贴一下吗？还有你使用的浏览器的信息。

**Comment by KomachiSion** [comment]
清理浏览器缓存之后重试呢？

**Comment by soladed** [comment]
> 清理浏览器缓存之后重试呢？

清除缓存后，正常了。
