### ISSUE TITLE
Feature: ResourceParser groupName change the splicing method.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#5888]
不知道为什么 groupName 的拼接 依赖 dataId 的判空，我基于权限的增强来看，可以基于 group 来作整个分组的权限授予，
我已变更其拼接方式，作验证中，现提交一个 pr，若有其他原因的考虑请拒绝。

**Comment by KomachiSion** [comment]
@TsingLiang Can you answer this question?

**Comment by TsingLiang** [comment]
因为接口参数定义都是内部做的，dataId存在的时候group应该也存在，改之后严谨一点，可以改改优化一下

**Comment by CherishCai** [comment]
在控制台查询的时候，是可以仅传参 groupName 无 dataId 的，所以如果 groupName 不依赖 dataId 可以做到 group 分组授权。

**Comment by KomachiSion** [comment]
能在PR中添加一下UT吗？ 以保证除了你新增的这种情况，其他情况下解析的结果都保持一致吗？

**Comment by CherishCai** [comment]
> 能在PR中添加一下UT吗？ 以保证除了你新增的这种情况，其他情况下解析的结果都保持一致吗？

好的，晚点提交
