### ISSUE TITLE
请问下单机部署的nacos有好的办法平滑升级到集群吗

### ISSUE THREAD

**Issue by feixia5712** [alibaba/nacos#5892]

**Comment by KomachiSion** [comment]
单机部署一般用于本地测试，不建议直接生产使用。

目前没有办法直接将单机升级至集群，需要先停止单例，修改集群配置文件和启动命令才可以

**Comment by feixia5712** [comment]
看了官网好像没有这方面的文档，在请教下，nacos1.4.0集群扩容内存的话，目前集群是3台，扩容策略是先扩容follewer然后在leader节点吗？详情是，先stop掉一台follower节点，然后扩容关机重启，等待他加入到节点之后，然后在扩容另外一台的follower节点，以此往后，这样顺序对吗
