### ISSUE TITLE
nacos作为配置中心，client端长轮训逻辑

### ISSUE THREAD

**Issue by mayang2465** [alibaba/nacos#5893]
在LongPollingRunable的run方法中，会首先：checkLocalConfig（cacheData），即本地文件，关于此两个疑问：
（1）：在其中实现中，只要检测本地有配置文件，就会设置isUseLocalConfigInfo为true，如此服务端的配置信息 出现更改，是否就不会及时拉取本地中？
（2）：checkLocalConfig方法中检测的本地文件在什么时间写入，什么时候会出现更新或者删除？
谢谢解答。

**Comment by KomachiSion** [comment]
1. 会，长轮训检测的是配置的md5值，只要cache中的和服务端的不一致，就会拉取新的数据
2. 从服务端获取更新时写入，删除也是一样。
