### ISSUE TITLE
com.alibaba.nacos.naming.core.DistroMapper#responsible(java.lang.String) 讨论

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#5902]
版本：develop

int index = servers.indexOf(EnvUtil.getLocalAddress());
int lastIndex = servers.lastIndexOf(EnvUtil.getLocalAddress());

是否可以直接使用 server.indexOf(EnvUtil.getLocalAddress()) 来判断，返回的时候，只要 target == index 即可返回 true。

```
public boolean responsible(String serviceName) {
        final List<String> servers = healthyList;
        
        if (!switchDomain.isDistroEnabled() || EnvUtil.getStandaloneMode()) {
            return true;
        }
        
        if (CollectionUtils.isEmpty(servers)) {
            // means distro config is not ready yet
            return false;
        }
        
        int index = servers.indexOf(EnvUtil.getLocalAddress());
        int lastIndex = servers.lastIndexOf(EnvUtil.getLocalAddress());
        if (lastIndex < 0 || index < 0) {
            return true;
        }
        
        int target = distroHash(serviceName) % servers.size();
        return target >= index && target <= lastIndex;
    }
```

**Comment by KomachiSion** [comment]
It is used for different weights for server nodes.

**Comment by xiaoheng1** [comment]
> It is used for different weights for server nodes.

但是同一个节点只会在 healthyList 列表中出现一次吧？

**Comment by KomachiSion** [comment]
会出现多次

**Comment by xiaoheng1** [comment]
> 会出现多次

请教下，在那种情况下会出现多次了？我看了下 healthyList 使用的是 com.alibaba.nacos.core.cluster.ServerMemberManager#allMembers 这个属性，而这个属性的 key 是 address，所以，理论上是不会出现 healthyList 中同一个节点出现多次的，还望指点下，感谢。

**Comment by KomachiSion** [comment]
初始化的时候是通过allMembers初始化的， 但是之后监听变更事件的时候应该会根据权重属性调整healthyList中的个数才对。

有可能是社区多次重构之后把这个逻辑移除了。

**Comment by xiaoheng1** [comment]
> 初始化的时候是通过allMembers初始化的， 但是之后监听变更事件的时候应该会根据权重属性调整healthyList中的个数才对。
> 
> 有可能是社区多次重构之后把这个逻辑移除了。

那上面那个优化逻辑还需要修改不？还是说后续基于权重属性调整 healthyList 的这段逻辑会添加回来？

**Comment by KomachiSion** [comment]
暂时不需要修改。如果需要修改，我觉得可以抽象成接口，然后通过不同的实现去区分。

**Comment by xiaoheng1** [comment]
> 暂时不需要修改。如果需要修改，我觉得可以抽象成接口，然后通过不同的实现去区分。

好的，那就先不修改。
