### ISSUE TITLE
ServerMemberManager的onXXX方法都没有捕获异常，导致I/O reactor status STOPPED

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#5905]
**Describe the bug**
这个问题是个附加赠送的问题，原始问题是nacos1.4.1注册中心节点运行一段时间后，莫名其妙地开始频繁建立到集群其他节点的连接，注册中心端口出现阻塞，netstat看各节点注册中心监听端口的连接数飞涨，rcv-q和snd-q均开始堆积，导致各节点到其他节点之间建连超时，ServerMemberManager的onXXX方法没有捕获异常，导致I/O reactor status STOPPED。
nacos-cluster.log日志开始是频繁刷超时日志：
ERROR failed to report new info to target node : x.x.x.x:xxxx（注：nacos注册中心集群其他节点地址和端口）, error : caused: Timeout connecting to [/x.x.x.x:xxxx];
刷了一段时间后就是：
ERROR failed to report new info to target node : x.x.x.x:xxxx, error : caused: I/O reactor has been shut down;
ERROR failed to report new info to target node : x.x.x.x:xxxx, error : caused: Request cannot be executed; I/O reactor status: STOPPED;
这种情况出现后，只能重启nacos进程了。
我们自己写代码时碰到过同样的问题，异步httpclient的onXXX方法抛异常就是这个结果，需要自己catch掉。

**Comment by KomachiSion** [comment]
I see the `DefaultAsyncHttpClientRequest` has catch the exception. So I think it is not the reason.

**Comment by zrlw** [comment]
是com.alibaba.nacos.core.cluster.ServerMemberManager，这里的onXXX方法调用MemberUtil.onFail没有catch异常。

**Comment by KomachiSion** [comment]
MemberUtil.onFail 会抛出异常吗？ 抛出什么异常？ 什么情况下会抛出异常？

**Comment by nullmc** [comment]
nacos日志没有开debug，只是根据nacos-cluster的异常信息搜索nacos的cluster代码进行的推断。

1. 在nacos-cluster日志出现I/O reactor has been shutdown前半个小时，nacos.log开始出现:
ERROR Failed to complete processing of a request
java.lang.OutofMemoryError: Java heap space

2. 在nacos-cluster日志出现I/O reactor has been shutdown前1分钟， protocol-distro.log开始出现：
ERROR [DISTRO-FAILED] java.lang.OutofMemoryError: GC overhead limit exceeded
nacos.log开始出现：
ERROR Failed to complete processing of a request
java.lang.OutofMemoryError: GC overhead limit exceeded

根源应该还是http request请求塞满了jvm。

**Comment by KomachiSion** [comment]
是因为异常导致Request没有被清理吗？还是就有这么多请求导致的？可以适当调大tomcat的worker线程看下是不是能够改善。

**Comment by KomachiSion** [comment]
relative #5898
