### ISSUE TITLE
nacos2.01 config ldap error

### ISSUE THREAD

**Issue by MRwangyd** [alibaba/nacos#5909]
Nacos version 2.01 is configured with LDAP integration. Unable to log in after configuration. Logs report no error output
The documentation on the official website does not find any more description of the LDAP configuration, as well as the configuration of the LDAP administration user and password
The LDAP configuration has no problems integrating with other systems

The configuration file is as follows：
![image](https://user-images.githubusercontent.com/27405334/120185475-d611fd80-c244-11eb-82fe-6a9c52d1fec8.png)
Login error
![image](https://user-images.githubusercontent.com/27405334/120185405-bf6ba680-c244-11eb-8501-88dfb552ad54.png)

**Comment by KomachiSion** [comment]
LDAP feature is contributed by community completely. Welcome community contributors to research and solve it.

**Comment by andotorg** [comment]
@i will solve it@

**Comment by x-lambda** [comment]
> @i will solve it@

hello, Can nacos 1.4.2 use ldap ?

**Comment by jiaozh8** [comment]
> 

不是的。我是用的2.0.3

**Comment by KeithTt** [comment]
How to config `nacos.core.auth.ldap.userdn`? I did not find a related page in the official guide.

**Comment by panjhgit** [comment]
我想问一下我配置的ldap报错是怎么回事
"POST /nacos/v1/auth/users/login HTTP/1.1" 500 21 7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)
