### ISSUE TITLE
文档错别字

### ISSUE THREAD

**Issue by 362460453** [alibaba/nacos#591]
单词拼写错误
地址：https://nacos.io/en-us/docs/quick-start-spring-cloud.html

最好从自下而上看，在Enable Service Discovery中有一段话：
ii. Add the Spring Cloud native annotation of @EnableDiscoveryClient to enable service dicovery. Add the @LoadBalanced annotation for the RestTemplate instance,  and enable the integration of @LoadBalanced and Ribbon:
错误单词：dicovery

**Comment by hxy1991** [comment]
多谢，已修复。
