### ISSUE TITLE
ERROR Fail to refresh route configuration for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_persistent_service]

### ISSUE THREAD

**Issue by kevin518** [alibaba/nacos#5912]
ERROR Fail to refresh leader for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: Fail to init channel to 192.168.0.42:7848, Fail to init channel to 192.168.0.149:7848, Fail to init channel to 192.168.0.103:7848]

2021-06-01 10:30:40,329 ERROR Fail to refresh route configuration for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_persistent_service]

**Comment by kevin518** [comment]
这个事什么原因造成的？

**Comment by KomachiSion** [comment]
网络原因 jraft无法与另外3台服务端建立连接，无法选主。

**Comment by kevin518** [comment]
为什么是7848这个端口有点没明白
