### ISSUE TITLE
文档很不完善

### ISSUE THREAD

**Issue by bigbugbean** [alibaba/nacos#5917]
作为一个注册中心，最起码说一下用了什么一致性算法吧

**Comment by KomachiSion** [comment]
你是用注册中心为什么会关注用了什么一致性算法？使用文档一般只是说明如何使用吧，用了什么一致性算法应该是原理性的。

如果您觉得文档不是很完善，可以帮社区一起去完善。

**Comment by bigbugbean** [comment]
一般做技术选型的时候都会简单了解一下原理，Nacos的文档原理性的描述比较少。个人感觉Nacos的文档是写给领导看的，不是写给开发者的，建议参考竞品的文档，抱着做好开源的心态共同完善社区。
