### ISSUE TITLE
创建服务或者更新元数据之后，需要手动刷新当前页面才能看到最新内容

### ISSUE THREAD

**Issue by weissxu** [alibaba/nacos#5926]
**Describe the bug**

After login console with your account,
1. click on 'ServiceManageMent --> ServiceList'
1. create new service  or modify service alreay exists in the further step
1. after submit, you will see the page is the same as  you modify before!
1. so ,I have to refresh it to see the changes.

**Expected behavior**
the newest result.

**Acutally behavior**
the old result.

**How to Reproduce**
1. click on 'ServiceManageMent --> ServiceList'
1. create new service  or modify service alreay exists in the further step
1. after submit, you will see the page is the same as  you modify before!
1. so ,I have to refresh it to see the changes.

**Desktop (please complete the following information):**
 - OS: [Centos,windows]
 - Version [nacos-server 2.0.0-bugfix]
 - Module [console]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
May be the other page have the same problem.

**Comment by JackSun-Developer** [comment]
I think you may turned this filter on, so the created service is filtered.
![image](https://user-images.githubusercontent.com/58767027/120438142-9289d180-c3b3-11eb-802c-2cacb1ba5499.png)

If you turn this off, You don't have to refresh

**Comment by weissxu** [comment]
As you say,  I turned this off, when i create a new service, 
 I still  have to refresh it  to see the newest infos.

**Comment by KomachiSion** [comment]
I test in `http://console.nacos.io/nacos` it can work well. 

Does you use the SLB or VIP to do loadbalance? So it might be in sync data when you create service and auto refresh, so that the refresh request to the node which has no finished the data sync.

Some data is generate and sync by async thread. So might has some delay.
