### ISSUE TITLE
nacos删除接口突然异常

### ISSUE THREAD

**Issue by feixia5712** [alibaba/nacos#5933]
nacos1.4.0集群
![image](https://user-images.githubusercontent.com/12670758/120579147-98d28900-c459-11eb-8889-8b0cc7f20e87.png)

造成的现象是，实例列表里面很多应该删除的实例没有被删除(全部为14个正常)
![image](https://user-images.githubusercontent.com/12670758/120579981-f3b8b000-c45a-11eb-9443-e2d129e77ad7.png)

naming-server.log日志显示一直在变化
![image](https://user-images.githubusercontent.com/12670758/120579869-c9ff8900-c45a-11eb-91e5-d31f6098f0f3.png)
请教下该怎么排查

**Comment by JackSun-Developer** [comment]
从两个方面排查：
1、核对一下实例的ip、port、service是否都正确
2、检查一下naming-server.log中是否还存在如下字眼
‘remove instance from non-exist service’字眼，说明请求中服务名有问题.
3、另外看一下naming-server.log中 是否存在'Client remove for service'字眼

**Comment by feixia5712** [comment]
目前日志搜索了关键字remove 命令：grep -i "remove" naming-server.log|less  没有搜索到
实例目前正常，集群没问题
出现这种现象是这样来的，原来的实例注册成功了(有个集群的名字叫做集群:NorthRegion-01)，后来修改了集群的名字(集群新名称为:NorthRegion)再次进行注册的时候,新实例都正常注册，老的集群有很多实例都没有删除掉，查看naocs的监控出现了delete接口异常
![image](https://user-images.githubusercontent.com/12670758/120740444-cdac1200-c525-11eb-8d14-eda5b960c47c.png)
昨天进行集群扩容，先后把每台nacos机器都重启了(一台台进行的升级扩容)，通过监控查看delete都正常了
![image](https://user-images.githubusercontent.com/12670758/120740812-85d9ba80-c526-11eb-865e-b7aaac021721.png)
但是查看实例，部分删除了，但是并未全部恢复(全部为14正常)
![image](https://user-images.githubusercontent.com/12670758/120740851-9c801180-c526-11eb-9092-83a216cdebea.png)
持续刷新监控发下delete一会正常一会不正常(现在又不正常了)
![image](https://user-images.githubusercontent.com/12670758/120741117-0993a700-c527-11eb-88a1-09df097ce32d.png)

**Comment by feixia5712** [comment]
原来的实例时这样的
![image](https://user-images.githubusercontent.com/12670758/120741620-e87f8600-c527-11eb-93fe-5d6094bdc156.png)
后台只是改了集群的名称，其他信息一样

**Comment by KomachiSion** [comment]
看下naming-server是不是有删除失败的ERROR日志，异常报错信息是什么？

**Comment by KomachiSion** [comment]
Author has no more response, and community can't reproduce problem. Close first.
