### ISSUE TITLE
nacos导入配置文件无法覆盖原有的配置文件

### ISSUE THREAD

**Issue by xrwang8** [alibaba/nacos#5934]
**Describe the bug**
我使用nacos导入配置文件的时候无法覆盖原有的配置
![image](https://user-images.githubusercontent.com/68765051/120580576-02539700-c45c-11eb-92d6-3cd35259427d.png)
![image](https://user-images.githubusercontent.com/68765051/120580621-15666700-c45c-11eb-86bd-afac4239dc33.png)
导入之后原有dateid的配置没有被覆盖
导入的压缩文件如下
![image](https://user-images.githubusercontent.com/68765051/120580763-4e9ed700-c45c-11eb-9785-68bd1e9fb152.png)
![image](https://user-images.githubusercontent.com/68765051/120580780-552d4e80-c45c-11eb-8770-95ae5c13ef9c.png)

nacos版本1.4.1 内嵌数据库集群部署

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KeRan213539** [comment]
该问题已在1.4.2中修复, 请升级到 1.4.2 试试

**Comment by KeRan213539** [comment]
确认该问题存在, 1.4.2 也存在该问题, 我们会尽快修复
