### ISSUE TITLE
guava版本冲突

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#5935]
issue类型：
question

环境：
nacos2.0.1客户端

问题：
guava版本冲突
将项目中的nacos客户端由1.0.0升级到2.0.1，但在启动项目的时候，报了错（下面贴出来）
项目之前依赖的guava版本是16.0
我尝试了强制升级guava版本这个错误就消失了。但了解到guava好像存在严重的向后兼容问题，不敢随便升级。
接下来了解到nacos使用了maven-shade-plugin去封装自己使用的guava，但在项目中使用的时候，好像没有生效？（也许是我不会用。）

想问下有人遇到了这种问题吗？一般怎么解决呢？

**Comment by woshishitou** [comment]
2021-06-03 14:15:02.007 ERROR [main][LoggingFailureAnalysisReporter.java:42] -

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.reflections.Reflections.expandSuperTypes(Reflections.java:380)

The following method did not exist:

    com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;

The method's class, com.google.common.collect.Sets$SetView, is available from the following locations:

    jar:file:/home/end_group/zlb_file/bosstest/dmqk-cloud-boss2-service-0.0.2-SNAPSHOT.jar!/BOOT-INF/lib/guava-16.0.jar!/com/google/common/collect/Sets$SetView.class

It was loaded from the following location:

    jar:file:/home/end_group/zlb_file/bosstest/dmqk-cloud-boss2-service-0.0.2-SNAPSHOT.jar!/BOOT-INF/lib/guava-16.0.jar!/


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.google.common.collect.Sets$SetView

**Comment by woshishitou** [comment]
2021-06-03 14:15:02.007 ERROR [main][LoggingFailureAnalysisReporter.java:42] -

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.reflections.Reflections.expandSuperTypes(Reflections.java:380)

The following method did not exist:

    com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;

The method's class, com.google.common.collect.Sets$SetView, is available from the following locations:

    jar:file:/home/tt_group/zzz/test/test-service-0.0.2-SNAPSHOT.jar!/BOOT-INF/lib/guava-16.0.jar!/com/google/common/collect/Sets$SetView.class

It was loaded from the following location:

    jar:file:/home/tt_group/zzz/test/test-service-0.0.2-SNAPSHOT.jar!/BOOT-INF/lib/guava-16.0.jar!/


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.google.common.collect.Sets$SetView

**Comment by woshishitou** [comment]
现在虽然除了强制升级guava版本之外，还没有想到别的办法。但对问题本身有了更多的理解。

首先，nacos使用maven-shade-plugin封装自己使用的guava，这个本身是生效了的，从jar包里的一个import就知道了，如下
import com.alibaba.nacos.shaded.com.google.common.collect.Sets;

但是，nacos使用了0.9.11版本的reflections，而这个版本的reflections依赖了20.0的guava。而nacos在打包的时候，并没有把reflections也使用maven-shade-plugin封装起来。所以当nacos通过原生的reflections间接调用guava的时候，还是会引发版本问题，因为reflections的类Reflections头部的引用是
import com.google.common.collect.*;

倒不是说nacos处理的不好，只是感觉这种guava版本不兼容的问题真是不好解决，虽然有神器maven-shade-plugin，还是会出现各种问题。

**Comment by JackSun-Developer** [comment]
目前没有很好的方法，如果nacos打包时把间接引用的包一起封装起来，会增加nacos包的重量；用户侧在业务中出现冲突问题，需要使用maven-shade-plugin来处理引入的冲突。

**Comment by KomachiSion** [comment]
maven-shade-plugin目前主要解决的是gRPC的冲突问题。Reflections的guava冲突可能需要看一下如何解决。

**Comment by woshishitou** [comment]
你们好，我看最新的2.0.3版本里，你们提到已经解除了对guava的依赖（[#6446] Remove dependency of guava.），但我引入2.0.3客户端后，还是有这个冲突问题。请问下你们解除的是nacos对guava的直接依赖，而不是Reflections对guava的依赖是吗？

**Comment by KomachiSion** [comment]
2.1.0移除了Reflections的依赖， 该issue应该已经解决了。
