### ISSUE TITLE
Nacos集群部署环境中注册的服务报503

### ISSUE THREAD

**Issue by ModnRay** [alibaba/nacos#5938]
code:503 msg: server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]

**Comment by KomachiSion** [comment]
`Distro protocol is not initialized` 数据未初始化完成。排查下是不是集群搭建有问题，或者网络有问题导致无法同步数据。

如果不在意数据初始化完成前就提供服务，可以设置`nacos.naming.data.warmup=false`

**Comment by KomachiSion** [comment]
#5920
