### ISSUE TITLE
能根据服务名获取该服务使用了哪些dataId吗

### ISSUE THREAD

**Issue by gitzhoujw** [alibaba/nacos#5942]
能根据服务名获取该服务使用了哪些dataId吗

**Comment by KomachiSion** [comment]
不能，服务名和dataId之间没有关联，服务需要哪些dataId配置服务自己能够知道，nacos只是把这个配置推送给这个订阅者ip。

**Comment by KomachiSion** [comment]
nacos能够知道订阅这个dataId的是哪些ip哪些应用，但是反过来nacos是不关心的。
