### ISSUE TITLE
回滚yaml类型的配置成功后，配置类型变成text了。

### ISSUE THREAD

**Issue by water040501212** [alibaba/nacos#5943]
**Describe the bug**
zh-cn：回滚yaml类型的配置成功后，配置类型变成text了。
en-us：After rolling back the YAML configuration successfully, the configuration type becomes TEXT.

**Expected behavior**
zh-cn：配置类型保持不变。
en-us：The configuration type remains the same.

**Acutally behavior**
zh-cn：配置类型从yaml变为text了。
en-us：The configuration type changed from YAML to Text.

**How to Reproduce**
zh-cn：配置为yaml类型。
1. 配置列表 -> 编辑 -> 发布配置
2. 历史版本 -> 查询 -> 回滚 -> 回滚配置
3. 配置列表 -> 编辑
这时发现配置类型从yaml变为text了。

en-us：Configure the original type to YAML.
1. Configuration list -> Edit -> Release configuration
2. Historical Version -> Query -> Rollback -> Roll back the configuration
3. Configuration list -> Edit
The configuration type has changed from YAML to Text.

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Version [nacos-server 2.0.1, nacos-client 1.4.1]
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos, dubbo]

**Comment by realJackSun** [comment]
历史版本是不是存在不符合yaml类型的内容？导致yaml格式校验失败，nacos自动给转换为了txt

**Comment by brotherlu-xcq** [comment]
@realJackSun @water040501212 我这边试了一下，好像确实可以复现。原因好像是因为在回滚配置的时候，前端是没有传入配置类型的相关字段，导致默认就是text。
![image](https://user-images.githubusercontent.com/25661357/120950193-d8aab080-c778-11eb-8e75-30007c630b9f.png)

**Comment by brotherlu-xcq** [comment]
我看了一下，根本原因应该是历史配置的表结构中没有配置类型相关字段，同样的问题也存在于beta发布功能。前面我有提到一个类似的issue #5494 。

**Comment by water040501212** [comment]
@realJackSun @brotherlu-xcq 1. 历史版本都是规范的yaml配置。2. 看图片中的传递参数，确实是少了一个类似"configType"的属性，配置类型缺失了。

**Comment by water040501212** [comment]
@realJackSun @brotherlu-xcq 1. 历史版本都是规范的yaml配置。2. 看图片中的传递参数，确实是少了一个类似"configType"的属性，配置类型缺失了。

**Comment by kuaile-zc** [comment]
@KomachiSion 我发现历史配置存储表中没有储存文件类型和文件描述，回滚之后会导致这两个字段缺失，是否考虑加入这两个字段？
附带表结构
CREATE TABLE his_config_info (
  id bigint NOT NULL,
  nid bigint NOT NULL generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id varchar(128) NOT NULL,
  tenant_id varchar(128) default '',
  app_name varchar(128),
  content CLOB,
  md5 varchar(32) DEFAULT NULL,
  gmt_create timestamp NOT NULL DEFAULT '2010-05-05 00:00:00.000',
  gmt_modified timestamp NOT NULL DEFAULT '2010-05-05 00:00:00.000',
  src_user varchar(128),
  src_ip varchar(20) DEFAULT NULL,
  op_type char(10) DEFAULT NULL,
  constraint hisconfiginfo_nid_key PRIMARY KEY (nid));

CREATE INDEX hisconfiginfo_dataid_key_idx ON his_config_info(data_id);
CREATE INDEX hisconfiginfo_gmt_create_idx ON his_config_info(gmt_create);
CREATE INDEX hisconfiginfo_gmt_modified_idx ON his_config_info(gmt_modified);
