### ISSUE TITLE
2.0.1使用本地存储，修改cluster.conf后jraft异常

### ISSUE THREAD

**Issue by pengten** [alibaba/nacos#5948]
刚开始三台机器正常工作， 后来改了一台机器的IP和port， 发现日志一直处于 starting 状态， alipay-jraft.log 报错信息却是以前的IP和port。    难道集群启动后，IP和prot就不能改了吗？

At first, the three machines worked normally. Later, the IP and port of one machine were changed. It was found that the log was always in the starting state, but the error message in alipay-jraft.log was the previous IP and port. Can't IP and prot be changed after the cluster is started?

**Comment by realJackSun** [comment]
虽然不建议这样做，但集群启动后，IP和port是可以改的。请从两个方面排查：
1、启动之前，磁盘上有没有残存的{nacos_home}/data/protocol文件，如果有，请删除再启动
2、请在日志中出现started sucess字样之后，再修改；即 starting 状态结束之后再修改。

**Comment by KomachiSion** [comment]
1. jraft的metadata中会存储之前的leader信息，修改ip port肯定是可以的，但是每次改动必须小于半数，保证能够成功选主。只有成功选主之后，才能更新元数据信息，更新leader及raft member的信息。
2. 一直处于starting状态，说明您应该使用的是derby数据库，启动时需要从数据库加载配置数据，由于jraft一直无法选主，因此dump数据一直被拒绝，所以一直starting。

**Comment by pengten** [comment]
清除/data/protocol文件后可以正常启动了
