### ISSUE TITLE
nacos编辑器优化 nacos config editor optimize

### ISSUE THREAD

**Issue by forfuns** [alibaba/nacos#5951]
我们在使用nacos配置管理的时候，里面的纯文本编辑实在太累人了，能不能加上一些书写检测或者提交检测：
- 属性名重复
- 符号缩进等格式检查，比如yml
- 配置自动排序 ASCII 排序

不然我们在不同环境更新配置的时候会造成配置非常乱，都需要人工检查。
如果无法内置到nacos程序上，社区有没有什么工具可以帮助配合解决我上述的问题

---------
When we use Nacos configuration management, the plain text editing in it is too tiring, can we add some writing check or submit check:
- Duplicate property name
- Format checks such as symbol indentation, such as YML
- Configure automatic sorting ASCII sorting

Otherwise, when we update the configuration in different environments, the configuration will be very messy and need to be checked manually.
If it can't be built into the Nacos application, is there any tool in the community that can help me solve the above problem

**Comment by realJackSun** [comment]
welcome to contribute~
