### ISSUE TITLE
2.0.x NamingClientProxyDelegate subscribe方法有bug吗

### ISSUE THREAD

**Issue by AYue-94** [alibaba/nacos#5958]
https://github.com/alibaba/nacos/blob/d1a818036e20675874649b30847c706698be0c3f/client/src/main/java/com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate.java#L140-L151
serviceInfoHolder.processServiceInfo(result)是不是应该放在if (null == result)里面？
```java
@Override
  public ServiceInfo subscribe(String serviceName, String groupName, String clusters) throws NacosException {
      String serviceNameWithGroup = NamingUtils.getGroupedName(serviceName, groupName);
      String serviceKey = ServiceInfo.getKey(serviceNameWithGroup, clusters);
      ServiceInfo result = serviceInfoHolder.getServiceInfoMap().get(serviceKey);
      if (null == result) {
          result = grpcClientProxy.subscribe(serviceName, groupName, clusters);
          serviceInfoHolder.processServiceInfo(result);
      }
      serviceInfoUpdateService.scheduleUpdateIfAbsent(serviceName, groupName, clusters);
      return result;
  }
```

**Comment by shalk** [comment]
can  you explain the bug directly ?

**Comment by realJackSun** [comment]
应该是先读缓存，缓存没有再去远程订阅

**Comment by KomachiSion** [comment]
不应该，肯定是要放后面，否则只会在启动时候处理一次。
那个判断只是判断数据从哪里取， 不管从哪里取 都是要进行处理的。

**Comment by AYue-94** [comment]
serviceInfoHolder. processServiceInfo是唯一更新内存注册表的入口，只有在服务端推送服务变更和客户端主动拉取注册表的情况下才会调用。这里从内存注册表获取ServiceInfo，然后再调用processServiceInfo去更新内存注册表，为啥？
