### ISSUE TITLE
2.0.1版本仍然可以通过api直接新增用户

### ISSUE THREAD

**Issue by jxwuqingyan** [alibaba/nacos#5960]
经测试发现，最新的2.0.1版本，仍然存在网络上已经发现的鉴权漏洞，可直接调用添加用户接口，添加新用户（ POST http://127.0.0.1:8848/nacos/v1/auth/users?username=test&password=test ）,然后使用新添加的用户test登录console，访问、修改、添加数据，望官方能尽快修复

**Comment by shalk** [comment]
you should check if config nacos.core.auth.enabled=true ?

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/120949034-22de6280-c776-11eb-895a-769ee9a52520.png)

There is no problem, you do not open `auth.enabled=true` and not set `auth.enable.userAgentAuthWhite=false`

**Comment by jxwuqingyan** [comment]
OK, configfile default set is auth.enabled=false
