### ISSUE TITLE
nacos com.alibaba.nacos.naming.consistency.ephemeral.distro.DistroConsistencyServiceImpl#onReceiveChecksums 优化讨论

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#5964]
版本：develop

如下代码摘自 develop 分支：
```
public void onReceiveChecksums(Map<String, String> checksumMap, String server) {
        
        if (syncChecksumTasks.containsKey(server)) {
            // Already in process of this server:
            Loggers.DISTRO.warn("sync checksum task already in process with {}", server);
            return;
        }
        
        syncChecksumTasks.put(server, "1");
      .......
}
```

个人认为需要增加双重判断，并且应该将 syncChecksumTasks.put(server, "1");  修改为 syncChecksumTasks.putIfAbsent(server, "1");

**Comment by KomachiSion** [comment]
Why? Can you describe the reason detailly?

**Comment by xiaoheng1** [comment]
如果在并发情况下，两个线程 syncChecksumTasks.containsKey(server) 都判定为 false，那么都会向下执行，然后都执行 syncChecksumTasks.put(server, "1"); 这条语句，然后执行后续的检查操作. 但实际上，只需要一个线程执行即可. 如果将 put 方法改为 putIfAbsent 并在后续增加一次 containsKey 检查，可以规避这个问题。

**Comment by KomachiSion** [comment]
这个方法应该是接受来自其他服务器的对账信息，我记得一个服务器不会并发的发起对账请求，似乎没有必要。

**Comment by xiaoheng1** [comment]
我的想法是增加并发处理的逻辑，这样健壮性会更好，并且不会损失性能.

**Comment by KomachiSion** [comment]
并发发送对账逻辑？ 那改动可就大了，完了并发发送，但是处理端又加锁只处理一个？ 意义不明。。

**Comment by xiaoheng1** [comment]
了解了，感谢解答，我这边先关闭这个问题。
