### ISSUE TITLE
When I started Nacos and started registering some services, the CPU was 100%

### ISSUE THREAD

**Issue by lzhpo** [alibaba/nacos#5966]
I found that my computer fan is very loud, the CPU is 100%, and when I register a large number of services, the computer sometimes shuts down directly.
<img width="972" alt="截屏2021-06-07 上午1 07 49" src="https://user-images.githubusercontent.com/42663571/120937893-b5650e80-c742-11eb-9232-a2267c2723f2.png">

Then I used the tool to analyze the heap memory and CPU situation
![截屏2021-06-07 上午3 36 01](https://user-images.githubusercontent.com/42663571/120937753-c8c3aa00-c741-11eb-9d8e-8f26d6e1d3c8.png)

![截屏2021-06-07 上午3 37 06](https://user-images.githubusercontent.com/42663571/120937756-cfeab800-c741-11eb-9e18-7dfe17a63e90.png)

Finally, I located the code problem here: 
`com.alibaba.nacos.naming.remote.udp.UdpConnector.UdpReceiver#run`
https://github.com/alibaba/nacos/blob/develop/naming/src/main/java/com/alibaba/nacos/naming/remote/udp/UdpConnector.java#L182

<img width="1427" alt="截屏2021-06-07 上午3 29 52" src="https://user-images.githubusercontent.com/42663571/120937758-d5480280-c741-11eb-8a30-eee0141eac73.png">

Although I can adjust the nacos parameter to solve the excessive memory usage of the jvm, I think you may be able to optimize it, such as: may sleep for a few milliseconds in some places, etc.?

By the way, my nacos version is 2.0.1.

**Comment by KomachiSion** [comment]
Logger cause much cpu and IO. You need to check the disk first and check why so much error logs are printed.

**Comment by lzhpo** [comment]
> Logger cause much cpu and IO. You need to check the disk first and check why so much error logs are printed.


Yes, you are correct, I used the `Proxifier` global enhanced proxy tool, which caused this problem.

I ran the nacos source code that I pulled, because no error logs were printed on the console. After your guidance, I found these error logs in the log directory of nacos. Thank you for your help! 👍👍👍

<img width="765" alt="截屏2021-06-07 下午12 49 42" src="https://user-images.githubusercontent.com/42663571/120960913-60031e80-c78f-11eb-9887-1267a8be7734.png">

![截屏2021-06-07 下午12 51 00](https://user-images.githubusercontent.com/42663571/120961098-b6705d00-c78f-11eb-87cc-b7b6fc73f1b8.png)
