### ISSUE TITLE
是否能支持按照IP+Port进行下线

### ISSUE THREAD

**Issue by hyang214** [alibaba/nacos#5967]
对于一个应用上包含多组dubbo服务的情况。
使用nacos控制台上的下线操作，只能每次针对单个接口进行上下线。
对于需要临时将整个应用实例摘除的情况，不是很方便。

**Comment by realJackSun** [comment]
个人观点，接口即服务是dubbo独特的实现方式；而nacos作为一个服务注册中心，如果为了适配dubbo而增加“将整个应用实例摘除”的功能，会使nacos不具有普适性。

**Comment by KomachiSion** [comment]
是接口还是应用对nacos来说都一样，只是应用注册的时候是以应用还是以接口来当作`服务`注册。 nacos的下线操作根据最小范围原则，需要指定服务下的某一个ip port（即实例）。至于他指代的是一个接口还是一个应用，那是`业务`语意，nacos不应该关心。

如果您希望针对整个应用下线，可以考虑用dubbo3的应用级服务发现，或者用SCA+dubbo2，转成应用级服务发现。这都是在应用语意上的修改。
