### ISSUE TITLE
Nacos后台页面打开没有权限控制

### ISSUE THREAD

**Issue by crazyCodeMh** [alibaba/nacos#5969]
Nacos后台页面打开没有权限控制这个菜单，我看了一下globalAdmin是false，这是为什么，我登录用户用的都是默认账号，账号密码都是nacos

**Comment by realJackSun** [comment]
你用的Nacos版本是？

**Comment by crazyCodeMh** [comment]
> 你用的Nacos版本是什么？
我用的1.3.2

**Comment by crazyCodeMh** [comment]
![image](https://user-images.githubusercontent.com/42796472/120950485-730af400-c779-11eb-9d87-d36f89f75993.png)

**Comment by KomachiSion** [comment]
说明你的nacos不是管理员用户， 没有初始化用户数据。

**Comment by crazyCodeMh** [comment]
> 说明你的nacos不是管理员用户， 没有初始化用户数据。

麻烦问一下我应该怎么调整一下

**Comment by caojiele** [comment]
> > 说明你的nacos不是管理员用户， 没有初始化用户数据。
> 
> 麻烦问一下我应该怎么调整一下

nacos做一下配置持久化

**Comment by KomachiSion** [comment]
conf目录下应该有sql文件，如果用的是mysql就用mysql的文件，里面有初始化用户和管理员权限的相关SQL，执行一下重启应该就好了

**Comment by caojiele** [comment]
> 户和管理

@crazyCodeMh `users`、`permissions`和`roles` 三个表

**Comment by KomachiSion** [comment]
No more response from author, this problem seems usage problem.
