### ISSUE TITLE
nacos配置变动，项目中业务日志不打印（不是必现的）

### ISSUE THREAD

**Issue by py199541** [alibaba/nacos#5970]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 您好！我们业务中引入了nacos的配置中心，在代码中对指定配置加了监听器，监听器里面有日志的最新配置变更的打印逻辑
2. 每次更改配置时，我们会在管理控制台修改配置的值
3. 配置变动之后，业务有的时候就不能打印业务日志了，除非重启项目，或者等待日志滚动（比如：日志是按天打印的，要等待到第二天才会在新文件中进行打印）

### Tell us your environment
spring boot 2.x + log4j 1.2.16 + nacos 1.3.0

**Comment by realJackSun** [comment]
怀疑是与业务中listener写法不对有关，方便的话可以贴出来监听配置相关的代码么？

**Comment by py199541** [comment]
/**
     * 注册版本变动的监听器
     *
     * @throws NacosException
     */
    private void registerVersionListener() throws NacosException {
        configService.addListener(versionConfigureDataId, DEFAULT_GROUP, new Listener() {
            @Override
            public Executor getExecutor() {
                return null;
            }

            @Override
            public void receiveConfigInfo(String content) {
                Map<String, String> tmpMap = new ConcurrentHashMap<>(64);
                setVersionMap(content, tmpMap);
                try {
                    writeLock.lock();
                    versionsMap = tmpMap;
                } finally {
                    writeLock.unlock();
                }
                LOGGER.info("current versionInfo are {}", versionsMap);
            }
        });
    }

监听器的代码是这个样子的，里面主要是更新了JVM 内存，并打印了一条日志

我用的是log4j  我看nacos底层自定义的日志用的是logback 或者 log4j2  当然log4j也支持 ，不知道是不是日志框架的问题，还是别的什么问题！

谢谢！！

**Comment by KomachiSion** [comment]
是不是没有正确触发dump配置的操作？ 升级一下服务端和客户端版本再试试。

**Comment by KomachiSion** [comment]
There is no more response from author, so we think upgrade can fix this problem.
