### ISSUE TITLE
Nacos proerpties文件解析json配置

### ISSUE THREAD

**Issue by wnn1029** [alibaba/nacos#5975]
使用 nacos-spring-context 1.1.1 版本
1、代码配置默认json格式数据，nacos也有配置，启动时解析没有问题，再次修改nacos配置配置之后，解析有问题
     1.1 启动之后 修改前解析json格式数据：{"0":{"1":"180,181,182","2":"183,184,185"},"10":{"13":"280,281,282","14":"283,284,285"},"12":{"19":"380,381,382","20":"383,384,386"}}
     1.2 修改之后解析的json格式：{"0":{"1":"180,181,182","2":"183,184,185"},"10":{"13":"280,281,282","14":"283,284,285"},"12":{"19":"380,381,382","20":"383,384,3800"}},"10":{"13":"280,281,282","14":"283,284,285"},"12":{"19":"380,381,382","20":"383,384,385"}}}

**Comment by realJackSun** [comment]
![image](https://user-images.githubusercontent.com/58767027/121017896-62399d00-c7d0-11eb-80f6-efed48c069bd.png)

修改之后不是标准的json了吧？大括号匹配似乎有点问题

**Comment by caojiele** [comment]
> 使用 nacos-spring-context 1.1.1 版本
> 1、代码配置默认json格式数据，nacos也有配置，启动时解析没有问题，再次修改nacos配置配置之后，解析有问题
> 1.1 启动之后 修改前解析json格式数据：{"0":{"1":"180,181,182","2":"183,184,185"},"10":{"13":"280,281,282","14":"283,284,285"},"12":{"19":"380,381,382","20":"383,384,386"}}
> 1.2 修改之后解析的json格式：{"0":{"1":"180,181,182","2":"183,184,185"},"10":{"13":"280,281,282","14":"283,284,285"},"12":{"19":"380,381,382","20":"383,384,3800"}},"10":{"13":"280,281,282","14":"283,284,285"},"12":{"19":"380,381,382","20":"383,384,385"}}}

![image](https://user-images.githubusercontent.com/29936718/121489737-f3925480-ca06-11eb-92a1-a7f52594844b.png)

**Comment by horizonzy** [comment]
It be fixed by https://github.com/nacos-group/nacos-spring-project/pull/262
