### ISSUE TITLE
2.0.1版本AddressServerMemberLookup.syncFromAddressUrl方法与nacos endpoint不兼容

### ISSUE THREAD

**Issue by MI-cool** [alibaba/nacos#5999]
**Is your feature request related to a problem? Please describe.**
AddressServerMemberLookup.syncFromAddressUrl方法需要后端服务返回json格式数据，而nacos endpoint返回的是简单字符串。这样导致同类功能接口需要重复建设

**Describe the solution you'd like**
修改genericType定义为GenericType\<String\>

**Comment by KomachiSion** [comment]
这个方法从1.3发布开始就一直是这个类型，能麻烦提供更多相关信息吗

**Comment by MI-cool** [comment]
nacos server通过address-url获取server节点列表和nacos client通过endpoint获取server节点列表在使用场景上是类似的，这是前提。
以下的server端处理过程需要address-url返回json格式数据 https://github.com/alibaba/nacos/blob/ac3280aa5b006fc4279b1a1cdf77acdf9624478c/core/src/main/java/com/alibaba/nacos/core/cluster/lookup/AddressServerMemberLookup.java#L165 
而client端处理过程需要nacos endpoint返回内容为换行分隔的nacos server ip:port列表字符串 https://github.com/alibaba/nacos/blob/ac3280aa5b006fc4279b1a1cdf77acdf9624478c/client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java#L351 
应用场景类似却需要不同接口定义，感觉没什么必要
