### ISSUE TITLE
his_config_info tables src_user is all null

### ISSUE THREAD

**Issue by shmily2038** [alibaba/nacos#6013]
**Describe the bug**
历史版本，无法查看操作人，只记录了操作ip，操作人名称没有

**Expected behavior**
能够看到操作人是谁，好清楚是谁修改的。

**Acutally behavior**
A clear and concise description of what you actually to happen.
操作完，只记录操作人的ip地址，没有记录操作人名称 src_user

**How to Reproduce**
1、在1.4.1的nacos server服务端，使用账号登录；
2、修改配置，提交
3、查看此配置的历史版本
4、
![图片](https://user-images.githubusercontent.com/16485682/121282501-36233680-c90c-11eb-86a5-9683dee1ef9a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
duplicate with #3548

**Comment by shmily2038** [comment]
> 
> 
> duplicate with #3548

要增加什么配置，在1.4.1版本，就可以用？ 

还是要等1.4.3版本，后面，不需要配置就有？

**Comment by shmily2038** [comment]
@KomachiSion 
要增加什么配置，在1.4.1版本，就可以用？

还是要等1.4.3版本，后面，不需要配置就有？
