### ISSUE TITLE
Nacos-Server1.4.2 & Nacos-Client1.2.1无法获取配置中心配置，新增和移除正常

### ISSUE THREAD

**Issue by fengjian1993** [alibaba/nacos#6016]
public static void main(String[] args) {
        try {
            String serverAddr = "10.20.4.91:8848";
            String dataId = "cn.service.acceptrule.cache.AddressCache";
            Properties properties = new Properties();
            properties.put("serverAddr", serverAddr);
            properties.put("username", "giraffe");
            properties.put("password", "giraffe");
            ConfigService configService = NacosFactory.createConfigService(properties);
            boolean r = configService.publishConfig(dataId, "woWwo", "xx");
            System.out.println("插入: " + r);
            String content = configService.getConfig(dataId, "woWwo", 3000);
            System.out.println("获取: " + content);
            r = configService.removeConfig(dataId, "woWwo");
            System.out.println("移除: " + r);
        } catch (
                Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
插入: true
获取: null
移除: true

此nacos为容器部署，比较疑惑的是为什么只有查询不行？ debug到httpGet方法HttpResult result = HttpSimpleClient.httpGet(this.getUrl(currentServerAddr, path), newHeaders, paramValues, encoding, readTimeoutMs, false);显示404

**Comment by KomachiSion** [comment]
写入的数据可能会由于异步同步和dump缓存而有一定的延迟，建议稍微等一会儿再查询或者使用listener的方式来监听配置变更。

**Comment by fengjian1993** [comment]
> 写入的数据可能会由于异步同步和dump缓存而有一定的延迟，建议稍微等一会儿再查询或者使用listener的方式来监听配置变更。

这个我只是写一个例子，事实上 多久以前写入的配置我都无法获取到，但是却可以移除

**Comment by fengjian1993** [comment]
curl -X GET 'http://10.20.4.91:8848/nacos/v1/cs/configs?dataId=cn.service.acceptrule.cache.AddressCache&group=woWwo&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaXJhZmZlIiwiZXhwIjoxNjIzMjQ3MDY1fQ.tQ-Hit3w8d4C6Qhv5paDXQVzTTAv6y_zsQG3LAbg_tY'
config data not exist

**Comment by KomachiSion** [comment]
我复现不了你的问题， 我自己测试是可以的，可能还是需要自己看下是不是有地方配置错了，比如dataId或者namespace之类的

**Comment by KomachiSion** [comment]
看下社区是否有人能复现这个问题。加入排查下。

**Comment by fengjian1993** [comment]
> 看下社区是否有人能复现这个问题。加入排查下。



> 我复现不了你的问题， 我自己测试是可以的，可能还是需要自己看下是不是有地方配置错了，比如dataId或者namespace之类的

**Comment by fengjian1993** [comment]
> 我复现不了你的问题， 我自己测试是可以的，可能还是需要自己看下是不是有地方配置错了，比如dataId或者namespace之类的

我就这个main方法 没有什么其他的配置，主要是写删可以，查不行，404这个确实诡异

**Comment by xiaoheng1** [comment]
> > 我复现不了你的问题， 我自己测试是可以的，可能还是需要自己看下是不是有地方配置错了，比如dataId或者namespace之类的
> 
> 我就这个main方法 没有什么其他的配置，主要是写删可以，查不行，404这个确实诡异

写和删可以，是因为直接走库了，而读是从缓存中读取的。

写完后，会通过任异步任务更新缓存数据，@KomachiSion 也提到了，存在一定的延迟。但是如果很长时间读不到，就有问题。你可以写完后 sleep 一段时间后，再 get 的看下。

**Comment by realJackSun** [comment]
代码修改成，发布之后休息三秒再查询，试一试？
`
            String serverAddr = "127.0.0.1:8848";
            String dataId = "cn.service.acceptrule.cache.AddressCache";
            Properties properties = new Properties();
            properties.put("serverAddr", serverAddr);
            properties.put("username", "giraffe");
            properties.put("password", "giraffe");
            ConfigService configService = NacosFactory.createConfigService(properties);
            boolean r = configService.publishConfig(dataId, "woWwo", "xx");
            System.out.println("插入: " + r);
            TimeUnit.SECONDS.sleep(3);
            String content = configService.getConfig(dataId, "woWwo", 3000);
            System.out.println("获取: " + content);
            r = configService.removeConfig(dataId, "woWwo");
            System.out.println("移除: " + r);

`

**Comment by realJackSun** [comment]
另外，你使用的curl
```
curl -X GET 'http://10.20.4.91:8848/nacos/v1/cs/configs?dataId=cn.service.acceptrule.cache.AddressCache&group=woWwo&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnaXJhZmZlIiwiZXhwIjoxNjIzMjQ3MDY1fQ.tQ-Hit3w8d4C6Qhv5paDXQVzTTAv6y_zsQG3LAbg_tY'
config data not exist
```
尝试检查一下，是不是dataId,或者groupId,或者namespace填写的不对？

**Comment by xiaoheng1** [comment]
@realJackSun 话说我们是否要保证线性读？即写入成功后再读，一定保证能读取到这个值？

**Comment by realJackSun** [comment]
> @realJackSun 话说我们是否要保证线性读？即写入成功后再读，一定保证能读取到这个值？


Nacos会把写请求先落盘，然后异步地更新内存中的缓存。
读流量来的时候，就会直接从缓存中读取，这样就可以保证对于后面的磁盘的流量保护。
如果每次读请求都去磁盘读，确实可以保证线性读，但是这样就会把所有读请求都打在磁盘上，降低读TPS。所以权衡一下，Nacos采用了缓存来优化性能，牺牲了一定的读实时性。

**Comment by xiaoheng1** [comment]
还有一个办法是，在写的时候，写完数据库后更新本机缓存，把这两步放在一起进行，成功后返回给用户，然后再异步通知其他节点，那么下次用户在读的时候，大概率能读取到数据。

**Comment by KomachiSion** [comment]
那就有事务性了，写数据库成功更新缓存失败怎么办。然后再依靠异步更新缓存重试来恢复吗？ 那其实还是保留现状的好。加了事务逻辑必然复杂化且大量降低性能。

**Comment by xiaoheng1** [comment]
> 那就有事务性了，写数据库成功更新缓存失败怎么办。然后再依靠异步更新缓存重试来恢复吗？ 那其实还是保留现状的好。加了事务逻辑必然复杂化且大量降低性能。

这个确实是一个问题，在更新数据库成功后，同步的先更新缓存一次，不论是否发生异常。这样也不能完全避免写入后读取不到数据的问题。如果要保证强一致，必然会牺牲性能。

**Comment by KomachiSion** [comment]
所以我觉得没有必要强行去刷新一次。 异步dump正常情况下1s以内就能完成，没有那么大的延迟，另一方面从客户端使用来说，建议使用listen来监听。 如果一定要使用getConfig，那么就需要在发布后有一定时间的等待，哪怕改成直接更新，也一样需要，因为事务性问题，不能保证更新缓存100%成功，还是需要异步兜底。

**Comment by xiaoheng1** [comment]
好的

**Comment by KomachiSion** [comment]
From community feedback, the get feature is work well but need some delay time. And author has no more response for a long time, so we think the problem has been fixed.
