### ISSUE TITLE
spring中存在定时任务，用@value动态刷新失败，并且每次发布新值会新建多余线程

### ISSUE THREAD

**Issue by hzh18580624796** [alibaba/nacos#6026]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Please fill the issue template. Only title we can't know what's your problem.
