### ISSUE TITLE
 DNS server is unavailable/feign interface timeout

### ISSUE THREAD

**Issue by BlankOfPi** [alibaba/nacos#6030]
**Describe the bug**
Using the Nacos registry, when the server is deployed on the intranet, the configured DNS server is unavailable or the response is slow, the calls between microservices are easily timed out. Is there any optimization solution?

**How to Reproduce**
1. Configure an unavailable dns service
2. feign interface timeout：Read timed out executing GET http://console-api/xxxxxx

**Desktop (please complete the following information):**
 - OS: [e.g. Centos7]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Comment by KomachiSion** [comment]
It is not nacos' problem and responsible. Nacos push the service list to your consumer. and your consumer call provider timeout or network problem, nacos' can't know that. You should retry to call other provider or use other way to cover it.

**Comment by BlankOfPi** [comment]
The calls between microservices are matched through the Dns service, so when the DNS resolution service is unavailable, will it cause the resolution timeout and the interface timeout?

**Comment by BlankOfPi** [comment]
My project is an intranet project. When you set a unavailable DNS address. this situation can often be encountered.

**Comment by KomachiSion** [comment]
It's still not nacos' problem. nacos is for service discovery, your service is registered to nacos and send beat to keep alive. Your consumer get the ips list of services ok. The nacos' works is finished. 

Nacos can't know what's your DNS server work and the network between your applciations.
