### ISSUE TITLE
服务已经关闭,但是健康检查到还是健康的

### ISSUE THREAD

**Issue by 65487123** [alibaba/nacos#6032]
我先往本地nacos中注册了一个服务实例。
通过nacos提供的web界面能看到已经注册成功。
然后我把服务实例停了（server端口都释放了)
但是通过nacos 界面看到这个服务还是健康的。

![image](https://user-images.githubusercontent.com/47898230/121466470-13ffe600-c9ea-11eb-9568-239bb436cda7.png)

其实服务都根本不可用了

![image](https://user-images.githubusercontent.com/47898230/121465127-cf734b00-c9e7-11eb-95d3-17bc67393c03.png)

nacos版本是1.3.1

不知道是如何做健康检查的，明明是不可达的服务，为什么还显示是健康的呢？后续的版本也是这样的吗？

**Comment by realJackSun** [comment]
过一段时间再看看？nacos的健康检查，默认过30s才会将实例设置成unhealthy的。

**Comment by 65487123** [comment]
> 过一段时间再看看？nacos的健康检查，默认过30s才会将实例设置成unhealthy的。

我是通过java客户端注册的服务，如果直接停了jvm，过30s是会变成unhealthy的。 但是如果不停JVM，只释放实例监听的端口，nacos是检测不到这个实例已经关闭的，过几十分钟都一直在。

**Comment by 65487123** [comment]
> 过一段时间再看看？nacos的健康检查，默认过30s才会将实例设置成unhealthy的。

我是通过java客户端注册的服务，如果直接停了jvm，过30s是会变成unhealthy的。 但是如果不停JVM，只释放实例监听的端口，nacos是检测不到这个实例已经关闭的，过几十分钟都一直在。  难道nacos健康检查的原则是只要ip能通就算健康，不管端口的吗？  但是这样也说不通呀，关了JVM，ip也是通的，但却能检测到实例不健康了。。。。 而且我也没一直持有java客户端"NamingService"的引用呀。。 没看nacos的源码，不知道到底是如何健康检查的。

反正现在的情况是，nacos上的实例的ip+port不能建立tcp连接，但是健康检查却没检查出来，现在的大部分的rpc都是基于tcp的，所以我觉得这样不合理。

**Comment by 65487123** [comment]
> 过一段时间再看看？nacos的健康检查，默认过30s才会将实例设置成unhealthy的。

我是通过java客户端注册的服务，如果直接停了jvm，过30s是会变成unhealthy的。 但是如果不停JVM，只释放实例监听的端口，nacos是检测不到这个实例已经关闭的，过几十分钟都一直在。 难道nacos健康检查的原则是只要ip能通就算健康，不管端口的吗？ 但是这样也说不通呀，关了JVM，ip也是通的，但却能检测到实例不健康了。。。没看过这块代码，不知道健康检查的逻辑到底是怎样的。

反正现在的情况是，nacos上所注册的服务实例的port根本是没有socket监听的，也就是不管是tcp还是udp，肯定都是不通的，健康检查却检查不出来，这应该是有问题的吧？ 我刚才试了下1.4.2版本的nacos，情况也是一样的。

**Comment by 65487123** [comment]
> 过一段时间再看看？nacos的健康检查，默认过30s才会将实例设置成unhealthy的。

我刚才又试了下，随便注册一个ip+port， nacos都认为是健康的。估计nacos是根据客户端是否存活来判断的了，客户端挂了就把注册的实例标记不健康，而Java客户端根本没提供手动close的api，也就是只有jvm挂了或者客户端和nacos-server的网络不通了，这些注册的实例才会被标记为unhealthy。nacos 根本就不会管注册的实例内容到底是什么，ip可不可达都不管。。

**Comment by KomachiSion** [comment]
非持久化实例是通过心跳维持

持久化实例才是由服务端探测端口或者api。

如果注册了非持久化实例，只是关闭端口，没有停止心跳。那就依旧是健康的

**Comment by 65487123** [comment]
> 我先往本地nacos中注册了一个服务实例。
> 通过nacos提供的web界面能看到已经注册成功。
> 然后我把服务实例停了（server端口都释放了)
> 但是通过nacos 界面看到这个服务还是健康的。
> 
> ![image](https://user-images.githubusercontent.com/47898230/121466470-13ffe600-c9ea-11eb-9568-239bb436cda7.png)
> 
> 其实服务都根本不可用了
> 
> ![image](https://user-images.githubusercontent.com/47898230/121465127-cf734b00-c9e7-11eb-95d3-17bc67393c03.png)
> 
> nacos版本是1.3.1
> 
> 不知道是如何做健康检查的，明明是不可达的服务，为什么还显示是健康的呢？后续的版本也是这样的吗？

**Comment by 65487123** [comment]
> 非持久化实例是通过心跳维持
> 
> 持久化实例才是由服务端探测端口或者api。
> 
> 如果注册了非持久化实例，只是关闭端口，没有停止心跳。那就依旧是健康的

那这样的话，非持久化实例的健康只是nacos client健康，而不是真的服务健康。这不太合理吧。。除非在nacos client的api文档上写明注册的实例ip必须和本机ip一致并且释放服务监听的端口时必须手动注销实例或者关闭nacos client。
