### ISSUE TITLE
Does not take effect after modifying the UI style

### ISSUE THREAD

**Issue by mayouzi** [alibaba/nacos#6033]
## Does not take effect after modifying the UI style

Type: *feature request*

### Describe what happened (or what feature you want)

- does not take effect after modifying the UI style

### Describe what you expected to happen

- UI is displayed as modified

### How to reproduce it (as minimally and precisely as possible)

```
1. cd console-ui
2. npm install
3. npm run build
4. cd ..
5. mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U
```

### Tell us your environment
Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by realJackSun** [comment]
What modification in console-ui have you made? And what's your nacos version?

**Comment by mayouzi** [comment]
> What modification in console-ui have you made? And what's your nacos version?

```console-ui/src/layouts/Header.js```
change the `home` link value

nacos version is `2.0.1`
```
HEAD detached at 2.0.1
```

**Comment by KomachiSion** [comment]
I can't reproduce your problem. Does you modify with error so that the build fail?

**Comment by mayouzi** [comment]
> I can't reproduce your problem. Does you modify with error so that the build fail?

build successful with no error, It has also been modified in the file `index.html`

Is it the exclusion in the POM file that caused it?

**Comment by mayouzi** [comment]
![image](https://user-images.githubusercontent.com/18528873/121620513-0e170d00-ca9d-11eb-981d-7e691ff4ed1b.png)

**Comment by mayouzi** [comment]
but some `WARNING`
![image](https://user-images.githubusercontent.com/18528873/121621073-060b9d00-ca9e-11eb-8d91-0544d1551948.png)

**Comment by mayouzi** [comment]
node v14.17.0
npm 6.14.13

**Comment by mayouzi** [comment]
Is this cause it?

![image](https://user-images.githubusercontent.com/18528873/121622525-bda1ae80-caa0-11eb-957d-5e11d2915cfd.png)

**Comment by KomachiSion** [comment]
I think there is no effect for pom excludes. This exclude is for rat or checkstyle which only is check in mvn package.

your npm install will not read pom config.

Warning maybe will not cause your UI build fail. I you modify and no effect. Please remove your cache in webbroser and retry.

Or solve these problem by yourself.

**Comment by mayouzi** [comment]
The problem caused by browser cache, Thank you for your reply
