### ISSUE TITLE
nacos client @PostConstruct阶段nacos动态刷新不生效

### ISSUE THREAD

**Issue by JackieChan007** [alibaba/nacos#6034]
**环境:**
nacos-client1.2.0
nacos-server1.4.1
**场景:**
`@NacosConfigurationProperties(prefix = "cts", dataId = "local-api", groupId = "V2.6", autoRefreshed = true)
@Configuration
@Data
public class TestCofgPrefix {

    private Map<String, String> ctsMap;
    private List<String> ctsList;
    private Student ctsPojo;

    @Data
    public static class Student {
        private String name;
        private int age;
    }
}`
调用：
`	@PostConstruct
	public void injectBean(){
		while (true) {
			System.out.println("++++++++++++++++++++++++++++++++++");
			System.out.println(JSONObject.toJSON(cofgPrefix.getCtsList()));
			System.out.println(JSONObject.toJSON(cofgPrefix.getCtsMap()));
			System.out.println(JSONObject.toJSON(cofgPrefix.getCtsPojo()));
			System.out.println(JSONObject.toJSON("+++++++++++++++test nacos value: " + testCofgValue.getAutoValue()));
			System.out.println(JSONObject.toJSON("+++++++++++++++test spring value: " + testCofgValue.getSpringValue()));
			try {
				TimeUnit.SECONDS.sleep(5);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
	}`
在这个阶段配置无法动态刷新

**Comment by realJackSun** [comment]
参考一下nacos.io官网上nacos-spring或者nacos-spring-boot模块，动态刷新配置的用法。

**Comment by realJackSun** [comment]
动态刷新配置，可以参考官网，https://nacos.io/zh-cn/docs/quick-start-spring-boot.html nacos-spring或者nacos-spring-boot的用法。

**Comment by JackieChan007** [comment]
好的，我试试

**Comment by JackieChan007** [comment]
> 动态刷新配置，可以参考官网，https://nacos.io/zh-cn/docs/quick-start-spring-boot.html 中配置动态刷新部分的介绍。
> 或者[https://nacos.io/zh-cn/docs/sdk.html中监听配置部分的介绍。](https://nacos.io/zh-cn/docs/sdk.html%E4%B8%AD%E7%9B%91%E5%90%AC%E9%85%8D%E7%BD%AE%E9%83%A8%E5%88%86%E7%9A%84%E4%BB%8B%E7%BB%8D%E3%80%82)



这个是bean加载的生命周期导致的吧？我测试换到监听启动完成时间里面就可以了，我看你说的两个文章里面似乎没有提到这个问题
