### ISSUE TITLE
nacos server2.0.1 Edit Cluster bug

### ISSUE THREAD

**Issue by CNWangTy** [alibaba/nacos#6035]
**Describe the bug**
click Details of server, then click Edit Cluster, click OK. You will find that the Form Data of this request doesn't contain checkPort, so the Status Code will be 400.
服务列表中点击一个服务详情，点击集群配置，直接点击确认。没有任何反应。发现此次请求的数据中没有检查端口参数，导致400错误。
**Desktop (please complete the following information):**
  -- nacos server 2.0.1
  利用官方提供的docker compose启动nacos-standalone
**Additional context**

**Comment by realJackSun** [comment]
![image](https://user-images.githubusercontent.com/58767027/121481902-2cc6c680-c9ff-11eb-86da-05d9786d87c2.png)
我这边复现，确实没有checkPort参数，但是返回的是200。是我复现方法有问题吗？或者你可否提供一下问题的详细复现方式

**Comment by CNWangTy** [comment]
> ![image](https://user-images.githubusercontent.com/58767027/121481902-2cc6c680-c9ff-11eb-86da-05d9786d87c2.png)
> 我这边复现，确实没有checkPort参数，但是返回的是200。是我复现方法有问题吗？或者你可否提供一下问题的详细复现方式

![image](https://user-images.githubusercontent.com/41817792/121488500-b4173880-ca05-11eb-92f9-2cddc1a213c5.png)
我是使用官方提供的docker compose在本机docker环境启动的server，版本是2.0.1，注册的服务是dotnet的，dotnet客户端应该不对此产生影响吧？
直接在docker启动，之后启动应用，然后就出现了这个问题。
当我把server版本切换为1.4.2，就没有这个问题。

**Comment by KomachiSion** [comment]
清理浏览器缓存后重试

**Comment by CNWangTy** [comment]
> 清理浏览器缓存后重试

清理后依然得到了  caused: Param 'checkPort' is required.;

**Comment by KomachiSion** [comment]
I use 2.0.2 release to test and find it has been fixed.

PR #4750.

I suggest you upgrade to 2.0.2 and clean web cache. And retry.

**Comment by CNWangTy** [comment]
> I use 2.0.2 release to test and find it has been fixed.
> 
> PR #4750.
> 
> I suggest you upgrade to 2.0.2 and clean web cache. And retry.

是的～2.0.2版本的Form Data中有了checkPort参数，现在是正常的了
