### ISSUE TITLE
font icon could not be displayed normally

### ISSUE THREAD

**Issue by videomonster** [alibaba/nacos#6036]
> Version: 2.0.1 release

After I modified the "context-path" in the configuration file and restarted the service, I visited the homepage and found that the font icon could not be displayed normally, like this: 
![bug](https://user-images.githubusercontent.com/19369884/121480771-05bbc500-c9fe-11eb-8247-cb4a91ba5031.png)

 When I press F12 and refresh the page again, I found that the "context-path" in the request path of the font icon library is hard-coded "nacos" instead of my modified one, like this:
![ request path](https://user-images.githubusercontent.com/19369884/121481459-baee7d00-c9fe-11eb-8e75-851c584b439f.png)

**Comment by realJackSun** [comment]
您用的版本号是？

**Comment by videomonster** [comment]
2.0.1-release




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月10日(星期四) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] font icon could not be displayed normally (#6036)





 
您用的版本号是？

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/121519057-d455f000-ca23-11eb-8188-7311cfb6af63.png)
请清理浏览器缓存后重试，如果仍然有问题请更换浏览器，还不行可能是您环境的问题了，换一个环境试试。

**Comment by videomonster** [comment]
请问你的字符库请求路径是修改contextpath之后的么？



发自我的iPhone


------------------ Original ------------------
From: 杨翊 SionYang ***@***.***&gt;
Date: Thu,Jun 10,2021 7:42 PM
To: alibaba/nacos ***@***.***&gt;
Cc: 塟愛鎵镞の怪仯 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [alibaba/nacos] font icon could not be displayed normally (#6036)





 

 请清理浏览器缓存后重试，如果仍然有问题请更换浏览器，还不行可能是您环境的问题了，换一个环境试试。
