### ISSUE TITLE
No servers available for service, 找不到实例

### ISSUE THREAD

**Issue by polandeme** [alibaba/nacos#6039]
Spring cloud gateway + feign + nacos

偶现找不到实例情况，但是控制台上面显示实例存在且正常。
开始怀疑是feign client 和 + Ribbon负载问题，但是这两个都是本地调用的方法依赖，理论上不会出现偶现。部署环境也在多台均做过验证。

通过断点调试：
定位到负载均衡里面包

```
org.springframework.cloud.loadbalancer.blocking.client
BlockingLoadBalancerClient#choose源码：

	@Override
	public <T> ServiceInstance choose(String serviceId, Request<T> request) {
		ReactiveLoadBalancer<ServiceInstance> loadBalancer = loadBalancerClientFactory.getInstance(serviceId);
		if (loadBalancer == null) {
			return null;
		}
                // 偶现问题主要出现在此处，获取实例信息的时候正常会返回具体实例，但是现在偶现为空情况。request输入一样
		Response<ServiceInstance> loadBalancerResponse = Mono.from(loadBalancer.choose(request)).block();
		if (loadBalancerResponse == null) {
			return null;
		}
		return loadBalancerResponse.getServer();
	}

```

nacos 源码定位：
```
    public List<ServiceInstance> getInstances(String serviceId) throws NacosException {
        String group = this.discoveryProperties.getGroup();

       // 这里发现为空
        List<Instance> instances = this.namingService().selectInstances(serviceId, group, true);
        return hostToServiceInstanceList(instances, serviceId);
    }

```

有什么定位方式可以判断是不是nacos的问题么，看了nacos的各种日志，也不太清楚每个日志是做什么的。

也没有发现在找不到的时候出现什么异常日志，且偶现概率大约20%，如果一旦出现偶现，就会集中出现几次

**Comment by KomachiSion** [comment]
feign + Ribbon 自身有缓存，几分钟更新一次，导致nacos推送的地址列表失效

可以试着排查下nacos的日志，${user.home}/logs/nacos/naming.log 看下是不是有收到新的地址列表，有的话就不是nacos的问题。

**Comment by KomachiSion** [comment]
nacos日志也可能打在你们自己的日志里面。搜一下关键字`received` `current ips`之类的

**Comment by polandeme** [comment]
> feign + Ribbon 自身有缓存，几分钟更新一次，导致nacos推送的地址列表失效
> 
> 可以试着排查下nacos的日志，${user.home}/logs/nacos/naming.log 看下是不是有收到新的地址列表，有的话就不是nacos的问题。

目标服务只有一台实例，而且是一直有效。如果有缓存的话，但是nacos上面的实例没有变更，也是没影响的。`${user.home}/logs/nacos/naming.log `地址一直有推送上去，但是一直都是固定的一个地址

**Comment by polandeme** [comment]
naming-push.log中存在错误日志：
```
naming-push.log:2021-06-10 20:35:49,770 ERROR [PUSH-FAIL] 1ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
naming-push.log:2021-06-10 20:36:10,907 ERROR [PUSH-FAIL] 2ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
naming-push.log:2021-06-10 20:36:11,930 ERROR [PUSH-FAIL] 1ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
naming-push.log:2021-06-10 20:36:12,954 ERROR [PUSH-FAIL] 1ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
naming-push.log:2021-06-10 20:39:52,403 ERROR [PUSH-FAIL] 20011ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 20:40:19,542 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 20:41:47,041 ERROR [PUSH-FAIL] 20009ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 20:42:15,589 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 20:42:42,201 ERROR [PUSH-FAIL] 20009ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 20:59:26,487 ERROR [PUSH-FAIL] 20007ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 21:00:22,967 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 21:01:23,051 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 21:02:00,761 ERROR [PUSH-FAIL] 20009ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 21:04:56,815 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
naming-push.log:2021-06-10 21:14:23,418 ERROR [PUSH-FAIL] 20007ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198

```

**Comment by realJackSun** [comment]
> 也没有发现在找不到的时候出现什么异常日志，且偶现概率大约20%，如果一旦出现偶现，就会集中出现几次

可能是feign + Ribbon的缓存导致在短时间之内无法进行服务发现和推送。

这个问题过一段时间应该就能自愈吧？

**Comment by polandeme** [comment]
> > 也没有发现在找不到的时候出现什么异常日志，且偶现概率大约20%，如果一旦出现偶现，就会集中出现几次
> 
> 可能是feign + Ribbon的缓存导致在短时间之内无法进行服务发现和推送。
> 
> 这个问题过一段时间应该就能自愈吧？

没有发现自愈情况，另外也debug看了feign Ribbon 和nacos的链路，目前没有发现哪里问题，也在推测是缓存问题导致，还在跟进中

**Comment by KomachiSion** [comment]
推送失败的原因是什么？应该更详细的日志内容

**Comment by polandeme** [comment]
> naming-push.log中存在错误日志：
> 
> ```
> naming-push.log:2021-06-10 20:35:49,770 ERROR [PUSH-FAIL] 1ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
> naming-push.log:2021-06-10 20:36:10,907 ERROR [PUSH-FAIL] 2ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
> naming-push.log:2021-06-10 20:36:11,930 ERROR [PUSH-FAIL] 1ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
> naming-push.log:2021-06-10 20:36:12,954 ERROR [PUSH-FAIL] 1ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=Network is unreachable (sendto failed), target=192.160.8.198
> naming-push.log:2021-06-10 20:39:52,403 ERROR [PUSH-FAIL] 20011ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 20:40:19,542 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 20:41:47,041 ERROR [PUSH-FAIL] 20009ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 20:42:15,589 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 20:42:42,201 ERROR [PUSH-FAIL] 20009ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 20:59:26,487 ERROR [PUSH-FAIL] 20007ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 21:00:22,967 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 21:01:23,051 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 21:02:00,761 ERROR [PUSH-FAIL] 20009ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 21:04:56,815 ERROR [PUSH-FAIL] 20008ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> naming-push.log:2021-06-10 21:14:23,418 ERROR [PUSH-FAIL] 20007ms, Service{namespace='public', group='DEFAULT_GROUP', name='xxx-server', ephemeral=true, revision=1}, reason=null, target=192.160.8.198
> ```
这个是推送日志的内容，里面没有具体的失败详情，reason=null

**Comment by KomachiSion** [comment]
前面几行暴露出来的是`Network is unreachable (sendto failed)`

我觉得应该是网络问题导致的。

**Comment by polandeme** [comment]
> 前面几行暴露出来的是`Network is unreachable (sendto failed)`
> 
> 我觉得应该是网络问题导致的。

nacos和服务在同一台机器也会出现类似现象

**Comment by KomachiSion** [comment]
从ip来看应该不是回环地址，流量还是要出机器然后再路由回来的。 有可能是绕出去的这条链路有什么问题，然后导致了unreachable.

**Comment by KomachiSion** [comment]
@polandeme Any process?

**Comment by polandeme** [comment]
@KomachiSion  目前没有其他进展，最近又不复现了，先close了吧。
