### ISSUE TITLE
when I modify the metadata of service node ,  an error has occurred~

### ISSUE THREAD

**Issue by radishT** [alibaba/nacos#6041]
nacos console 2.0.3
![image](https://user-images.githubusercontent.com/32050371/121510350-1e39d880-ca1a-11eb-99c1-f2c6f33fcd7f.png)

**Comment by radishT** [comment]
quick start     ,   -Dnacos.standalone=true    !!!!!!!!!!!!!!!!!!!

**Comment by KomachiSion** [comment]
did not find the leader node !!!!!!!! The error has told you.

**Comment by KomachiSion** [comment]
try to remove /nacos/data/protocol/raft and restart

**Comment by radishT** [comment]
> try to remove /nacos/data/protocol/raft and restart

It was started with nacos-all in my idea ~ where is the /nacos/data/protocol/raft?

**Comment by KomachiSion** [comment]
maybe under ${user.home}/nacos
