### ISSUE TITLE
look for the class  BeatTask! it will override init metadata to modified metadata

### ISSUE THREAD

**Issue by radishT** [alibaba/nacos#6042]
look for the class  BeatTask! it will override init metadata to modified metadata
请看下BeatTask 这个类，这个类会在server端修改完metadata后，仍以初始化时的metadata保持心跳！

class BeatTask implements Runnable {
        
        **BeatInfo beatInfo;**
        
        public BeatTask(BeatInfo beatInfo) {
            this.beatInfo = beatInfo;
        }
        
        @Override
        public void run() {
            if (beatInfo.isStopped()) {
                return;
            }
            long nextTime = beatInfo.getPeriod();
            try {
                JsonNode result = serverProxy.sendBeat(beatInfo, BeatReactor.this.lightBeatEnabled);
                long interval = result.get("clientBeatInterval").asLong();
                boolean lightBeatEnabled = false;
                if (result.has(CommonParams.LIGHT_BEAT_ENABLED)) {
                    lightBeatEnabled = result.get(CommonParams.LIGHT_BEAT_ENABLED).asBoolean();
                }
                BeatReactor.this.lightBeatEnabled = lightBeatEnabled;
                if (interval > 0) {
                    nextTime = interval;
                }
                int code = NamingResponseCode.OK;
                if (result.has(CommonParams.CODE)) {
                    code = result.get(CommonParams.CODE).asInt();
                }
                if (code == NamingResponseCode.RESOURCE_NOT_FOUND) {
                    Instance instance = new Instance();
                    instance.setPort(beatInfo.getPort());
                    instance.setIp(beatInfo.getIp());
                    instance.setWeight(beatInfo.getWeight());
                    **instance.setMetadata(beatInfo.getMetadata());**
                    instance.setClusterName(beatInfo.getCluster());
                    instance.setServiceName(beatInfo.getServiceName());
                    instance.setInstanceId(instance.getInstanceId());
                    instance.setEphemeral(true);
                    try {
                        serverProxy.registerService(beatInfo.getServiceName(),
                                NamingUtils.getGroupName(beatInfo.getServiceName()), instance);
                    } catch (Exception ignore) {
                    }
                }
            } catch (NacosException ex) {
                NAMING_LOGGER.error("[CLIENT-BEAT] failed to send beat: {}, code: {}, msg: {}",
                        JacksonUtils.toJson(beatInfo), ex.getErrCode(), ex.getErrMsg());
    
            } catch (Exception unknownEx) {
                NAMING_LOGGER.error("[CLIENT-BEAT] failed to send beat: {}, unknown exception msg: {}",
                        JacksonUtils.toJson(beatInfo), unknownEx.getMessage(), unknownEx);
            } finally {
                executorService.schedule(**new BeatTask(beatInfo)**, nextTime, TimeUnit.MILLISECONDS);
            }
        }
    }

**Comment by KomachiSion** [comment]
是的，肯定是这样。  如果实例不掉线，metadata会保留，如果掉线之后再通过心跳重新注册， 那只能保持注册时的元数据。因为你修改的元数据不是通过客户端修改的，心跳里面没有修改信息。

**Comment by radishT** [comment]
为什么不能提供类似ext的形式，让系统断心跳后再注册保持提供自己的某些特征值到metadata去，能够理解我的意思吗？比如我有个Bank服务，带着一些runtime时会持续变更的特征值，这个特征值会因为网络分区等原因断了心跳后被nacos清空，但实际上内存中仍存在那些特征~
