### ISSUE TITLE
nacos-client 1.4.2 https证书问题

### ISSUE THREAD

**Issue by westcows00481** [alibaba/nacos#6044]
服务端开启https无问题， 客户端启动时证书检查IP有问题
客户端配置-Dtls.enable=true，忽略证书检查，最后还是检查信任库

**Comment by wangweizZZ** [comment]
是说`com.alibaba.nacos.common.tls.SelfHostnameVerifier` 这部分逻辑是吗？目前的实现就是比较简单的对ip的放行。你是希望有更严格的验证，包括hostname是否在自己信任列表里是么？

**Comment by westcows00481** [comment]
docker环境没办法设置固定IP, 这种做法有问题。如果不校验就存在安全隐患

**Comment by KomachiSion** [comment]
@westcows00481 您可以修改下，添加几种新的校验类型，比如通过hostname，或者其他手段来校验

**Comment by zx0zx9zx1zx9** [comment]
@westcows00481 看了下，程序里判断如果是ip，直接返回true了，感觉不应该有这个问题，是什么问题导致的？

    @Override
    public boolean verify(String hostname, SSLSession session) {
        if (LOCALHOST_HOSTNAME[0].equalsIgnoreCase(hostname) || LOCALHOST_HOSTNAME[1].equals(hostname)) {
            return true;
        }
        if (isIP(hostname)) {
            return true;
        }
        return hv.verify(hostname, session);
    }

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
