### ISSUE TITLE
修改context-path之后, 字符库资源无法正常加载

### ISSUE THREAD

**Issue by videomonster** [alibaba/nacos#6045]
请注意, 是修改了nacos配置文件中的context-path

![image](https://user-images.githubusercontent.com/37170243/121519057-d455f000-ca23-11eb-8188-7311cfb6af63.png)
请清理浏览器缓存后重试，如果仍然有问题请更换浏览器，还不行可能是您环境的问题了，换一个环境试试。

_Originally posted by @KomachiSion in https://github.com/alibaba/nacos/issues/6036#issuecomment-858549325_

**Comment by videomonster** [comment]
请问是否修改了配置文件中的context path之后进行的尝试， 是否可以看一下请求路径

**Comment by KomachiSion** [comment]
http://console.nacos.io/nacos

**Comment by KomachiSion** [comment]
请修改issue标题。现在的标题根本不明白什么意思。

**Comment by videomonster** [comment]
> http://console.nacos.io/nacos

![image](https://user-images.githubusercontent.com/19369884/121626888-db731180-caa8-11eb-9520-22e0ab8cde17.png)

在application.properties中修改了context-path, 但是字符库资源加载还是从nacos路径下加载, 这个是我描述的问题

**Comment by KomachiSion** [comment]
应该是前端框架无法同步到context-path的修改，在前端框架里只会去找nacos路径的资源。得找前端大佬看下能否解决。

**Comment by fanfuqiang123** [comment]
可以修改源码，把console\src\main\resources\static\css\main.css下的/nacos/路径改为你的上下文根，重新打包即可，命令：
mvn -Prelease-nacos clean install -U  -Dmaven.test.skip=true

**Comment by videomonster** [comment]
亲别急，我会尽快回复的。
