### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by adpw001** [alibaba/nacos#6047]
### 1、一般在接入 nacos 配置中心时里面都放什么配置？

据官网文章 [典型的应用场景](https://nacos.io/zh-cn/blog/5w1h-where.html) 描述，数据库连接信息、限流阈值和降级开关是很好的实践。

- 数据库连接信息 是在项目启动时读取的，假设当前是独立的 SpringBoot 的应用（没有使用 SpringCloud），又无法直接在项目启动时从 nacos 中获取配置。这点在官网 [issue](https://github.com/alibaba/nacos/issues/4924) 中找到类似的疑问。如果我现在就想把数据库信息托管在 nacos，必须使用 SpringCloud？
- 限流阈值和降级开关，关于这点，与将这些信息放在 Redis、ZK 等中间件，有什么区别？

### 2、动态 key 该如何访问？

下面是网提供的例子，访问的静态 key。简单的 k-v 配置。
```java
@NacosValue(value = "${useLocalCache:false}", autoRefreshed = true)
private boolean useLocalCache;
```
假设现在有个 业务项配置 需要根据 某个用户参数 进行获取（**key 里包含动态数据**），这种场景在 nacos 下面是否可行？假如可行，如何实现？

**Comment by KomachiSion** [comment]
1、 不是必须，您可以自己实现Listener，当配置变化的时候重新生成DataSource替换旧的DataSource，只是Spring Cloud可能会自动帮您做这个事。
2、 如果只把这些内容看成数据，那么存放在哪里都没有区别，甚至存在本地文件都可以。只是说适合放在nacos里面，提供稳定的变更感知和下发能里。
3、 只要是需要变更的配置信息，都适合用。至于是用SB还是SCA还是自己实现替换逻辑，都可以。
