### ISSUE TITLE
2.0.1在ARM 64 下 ，无法删除【配置管理】-【配置列表】中的配置文件

### ISSUE THREAD

**Issue by gongjiang1** [alibaba/nacos#6048]
请问2.0.1适配ARM架构服务器吗？
我在ARM服务器上可以正常启动2.0.1，删除已建的配置文件，无删除成功的提示框，且文件未删除，查找nacos,log也无相关日志。
请问nacos现在或者以后是否适配ARM架构？谢谢

**Comment by KomachiSion** [comment]
可以创建 不能删除？ 那么就和ARM应该没有关系。

您需要排查下有没有什么错误信息之类的。

目前由于依赖jraft，而jraft默认使用rocksdb存储日志。所以启动的时候可能会依赖ARM，如果正确启动之后应该是没有问题的。

**Comment by gongjiang1** [comment]
您好：
     可以正常创建，查看了logs下的多个日志文件，nacos.log、start.out、还有跟jraft相关的日志文件，均无异常。
     删除的时候抓包看了一下，发现如下问题。请问后续应该向那个方向排查？感谢！！
                                                                                                                                                                                                                                                                                                                                                                                                 
 
发件人： 杨翊 SionYang
发送时间： 2021-06-11 11:38
收件人： alibaba/nacos
抄送： gongjiang1; Author
主题： Re: [alibaba/nacos] 2.0.1在ARM 64 下 ，无法删除【配置管理】-【配置列表】中的配置文件 (#6048)
可以创建 不能删除？ 那么就和ARM应该没有关系。
您需要排查下有没有什么错误信息之类的。
目前由于依赖jraft，而jraft默认使用rocksdb存储日志。所以启动的时候可能会依赖ARM，如果正确启动之后应该是没有问题的。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KomachiSion** [comment]
我这边没有ARM环境，复现不了，排查方向的话，就是看哪里有报错，或者定位到阻塞在哪里。

**Comment by gongjiang1** [comment]
好的，谢谢！
 
发件人： 杨翊 SionYang
发送时间： 2021-06-15 11:31
收件人： alibaba/nacos
抄送： gongjiang1; Author
主题： Re: [alibaba/nacos] 2.0.1在ARM 64 下 ，无法删除【配置管理】-【配置列表】中的配置文件 (#6048)
我这边没有ARM环境，复现不了，排查方向的话，就是看哪里有报错，或者定位到阻塞在哪里。

**Comment by KomachiSion** [comment]
可以打开浏览器控制台看一下，返回了些什么信息。

**Comment by gongjiang1** [comment]
是不是请求根本就没有到后台呀？access.log中没有delete的日志

 
发件人： 杨翊 SionYang
发送时间： 2021-06-16 11:00
收件人： alibaba/nacos
抄送： gongjiang1; Author
主题： Re: [alibaba/nacos] 2.0.1在ARM 64 下 ，无法删除【配置管理】-【配置列表】中的配置文件 (#6048)
可以打开浏览器控制台看一下，返回了些什么信息。

**Comment by realJackSun** [comment]
@gongjiang1 

> 是不是请求根本就没有到后台呀？access.log中没有delete的日志 

如果是这样的话，检查一下网络联通性吧；或者看有没有nginx或其他代理进行了拦截转发。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem in other stages. So close it first.
