### ISSUE TITLE
一直没有适配其他数据库

### ISSUE THREAD

**Issue by yangliu817** [alibaba/nacos#6051]
你们能不能把持久层组件化,接口化, 像依赖一样集成进去, 让大家自己扩展都行, 一直没有官方适配其他数据库, 用其他数据库的企业想用nacos用不了,自己去改吧又不能升级

**Comment by realJackSun** [comment]
1、多数据源功能正在feature_multiple_datasource_support分支开发中。
2、另外后面nacos也会进行插件化，支持用户自己扩展相应数据库的插件。
