### ISSUE TITLE
The '@' symbol has been escaped

### ISSUE THREAD

**Issue by tian-qingzhao** [alibaba/nacos#6053]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![正常的](https://user-images.githubusercontent.com/57293296/121657600-20ac3900-cad3-11eb-8e63-a628b2b0fdef.png)
![被转义的](https://user-images.githubusercontent.com/57293296/121657609-2275fc80-cad3-11eb-9fc5-2516bc426f09.png)

**Comment by shalk** [comment]
duplicate with https://github.com/alibaba/nacos/issues/3992
