### ISSUE TITLE
权限模块增加group的权限控制

### ISSUE THREAD

**Issue by zx0zx9zx1zx9** [alibaba/nacos#6055]
目前权限模块 只对namespace做了read和write的权限控制。
而对于不同group的用户可以互相查看和修改对方的配置，这有很大的安全风险。

希望在roles表中增加group_id字段：
CREATE TABLE `roles` (
	`username` varchar(50) NOT NULL,
	`role` varchar(50) NOT NULL,
        `group_id` vachar(50) NOT NULL,
	UNIQUE INDEX `idx_user_role` (`username` ASC, `role` ASC) USING BTREE
);

一个group包含多个role，比如leader和dev，2种role下面有多个username；
role 管控者 namespace的read和write权限；
dataId 属于一个group；
只有本group的user可以增加、修改、删除、查看本group的dataId

**Comment by CherishCai** [comment]
这个是否可以解答你的疑问？ group 本身已经是 permission 的 resource 的一段了
https://github.com/alibaba/nacos/issues/5888

**Comment by zx0zx9zx1zx9** [comment]
1、如果用户有group1和group2权限，控制台查询配置列表，一般让group默认为空，用户进入，应列出group1和group2的dataId列表，目前的设计，会报告权限错误吗？除非用户输入group1来搜索
2、控制台支持group和dataId的模糊查询，如果用户输入group*，应该也会报权限错误吧？
3、看起来目前控制台增加权限时，没有对resource段中的group做设置，全部都是*  ，所以目前控制台看起来是不同group可以读写对方dataId？

**Comment by CherishCai** [comment]
> @CherishCai
> 1、如果用户有group1和group2权限，控制台查询配置列表，一般让group默认为空，用户进入，应列出group1和group2的dataId列表，目前的设计，会报告权限错误吧？除非用户输入group1来搜索
> 2、控制台支持group和dataId的模糊查询，如果用户输入group*，应该也会报权限错误吧？
> 3、看起来目前控制台增加权限时，没有对resource段中的group做设置，全部都是* ，所以目前控制台看起来是不同group可以读写对方dataId？

@zx0zx9zx1zx9 
答复 1 与 2、是的。所以我目前自己做定制时，加入了一个 search 权限，也就是可搜索权限赋予所有人，有些麻烦；而且要提示用户那些 dataId 是无权限的，暂且我采用 AOP 代理解决，少变更开源社区代码，减少冲突
![image](https://user-images.githubusercontent.com/16837364/121980172-14b7c400-cdbe-11eb-9ac2-d3e6b48094f0.png)
![image](https://user-images.githubusercontent.com/16837364/121980340-59435f80-cdbe-11eb-90eb-a301cea6e3c4.png)

3、确实管控台上的权限授予比较落后，这部分得前后端配合去升级处理了，其实目前的权限控制的实现还是比较灵活的了。

**Comment by zx0zx9zx1zx9** [comment]
嗯，这样实现也很好。还有添加，修改，删除，只能改自己group的dataId.

**Comment by CherishCai** [comment]
如果需要官方支持，得社区怎么讨论一种更完善的权限设计~
