### ISSUE TITLE
Does  MemberUtil.singleParse maybe setExtendVal ?

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#6056]
**Describe the bug**
Member.setExtendInfo original putAll into map but now is replace the map, Cause the original Member init attribute to be lost.
![image](https://user-images.githubusercontent.com/16837364/121763344-d9bf5180-cb6d-11eb-9a2f-7b210aa81cbd.png)

![image](https://user-images.githubusercontent.com/16837364/121763301-733a3380-cb6d-11eb-83fe-c02c71db07f6.png)

![image](https://user-images.githubusercontent.com/16837364/121763318-8220e600-cb6d-11eb-947a-98a3de375eae.png)

**Expected behavior**
So does  MemberUtil.singleParse maybe setExtendVal ?

**Comment by KomachiSion** [comment]
No, singleParse only parse the basic information like ip and port.

Other information should be added by report api.

I remember we only change the ip or port changed members. These members with same ip and port will not be replaced.

**Comment by CherishCai** [comment]
> No, singleParse only parse the basic information like ip and port.
> 
> Other information should be added by report api.
> 
> I remember we only change the ip or port changed members. These members with same ip and port will not be replaced.

The newExtendInfo Map must replace the old this.extendInfo in Figure1.

**Comment by KomachiSion** [comment]
So you want to keep the older extendInfo? Why? the method named `set` means replace completedly.

If you want to keep and only add the new infos, the method should named `put` or `putAll`.

There are different for some situation:
1. Member is self node, which should init with ip port and set some default value like your Figure1. And then set extendInfo one by one. For the self node Member, should send to other nodes by `report` api.
2. Member is other nodes, which should init from cluster.conf or addressServer, the extendInfo should set and replace by `report` api. So the default value in Figure1 is invalid.

**Comment by CherishCai** [comment]
Thanks, I still don't know all the background enough.

**Comment by CherishCai** [comment]
thank you for your reply.

**Comment by CherishCai** [comment]
我暂时这样修改跑一段时间，没问题再来反馈。

![image](https://user-images.githubusercontent.com/16837364/122658522-ed3b6f80-d1a0-11eb-8128-235ace05d7e2.png)

![image](https://user-images.githubusercontent.com/16837364/122658525-f298ba00-d1a0-11eb-9001-1d9c9c5269de.png)


![image](https://user-images.githubusercontent.com/16837364/122658519-e7458e80-d1a0-11eb-8e95-d7e07176449e.png)
