### ISSUE TITLE
Has logged in, show no permissions

### ISSUE THREAD

**Issue by tian-qingzhao** [alibaba/nacos#6065]
**Describe the bug**
Version 2.0.2
![nacos没有权限](https://user-images.githubusercontent.com/57293296/121997371-d978bd80-cddc-11eb-9515-bbb84d6896f9.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Have you provide auth for this user to this namespace?

**Comment by tian-qingzhao** [comment]
I don't know how the server can authorize different users based on the namespace, and I didn't have this problem when I deployed Nacos on another server, version 2.0.1

**Comment by tian-qingzhao** [comment]
Restart once again good, do not know what reason

**Comment by KomachiSion** [comment]
Maybe your web cookie or cache has some effect for this.
