### ISSUE TITLE
Unable to call API after NACOS has enabled permission authentication.（nacos开启权限认证后，无法调用api。）

### ISSUE THREAD

**Issue by zzf1208** [alibaba/nacos#6066]
Unable to call API after NACOS has enabled permission authentication.（nacos开启权限认证后，无法调用api。）
After online research, it is found that after the permission authentication is enabled, the AccessToken parameter needs to be added during the call, but how to generate this token？（经过网上调研，发现开启权限认证后，需要在调用时增加accessToken参数，但是这个token如何生成？）

**Comment by KomachiSion** [comment]
call login API first. and get the accessToken.
And then call your api with accessToken.

You can see the console request how to get and set them as a example.

**Comment by KomachiSion** [comment]
Usage problem and author has no more response for a long time.
