### ISSUE TITLE
could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so

### ISSUE THREAD

**Issue by shaohaikkk** [alibaba/nacos#6077]
error: could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so
environment: docker +java:8
describe: when i run in docker by java:8 images,i got this exception. java:8 is a common base image used by most people.so can fix
this problem to provide convenience for everyone. BEST WISHs!!!

**Comment by KomachiSion** [comment]
It is not nacos' problem, it is your env problem. Your installed java 8 can't create VFS in your env. Please search and fix it by yourself.
