### ISSUE TITLE
When you obtain a fixed namespace configuration, you must configure the namespaceId to get it. You cannot obtain it by using the namespace name.

### ISSUE THREAD

**Issue by fudali113** [alibaba/nacos#608]
Happening:
// 情况：
Tenant parameter must pass id to get the parameter
// tenant 参数必须传 id 才能获取到参数

Imagine:
// 预想：
The tenant parameter must pass the id or the name to get the parameter.
//  tenant 参数必须传 id 或者名称都能获取到参数

// ***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by helpless1** [comment]
Fixed namespace

**Comment by SKYhuangjing** [comment]
I have same scenario, when i try to intergrate dubbo-metedata-report-nacos, i need a fixed namespace, but i won't use nacos default namespace, so nacos offical teams can give me some idea?

**Comment by losphantom** [comment]
The namespace ID is unreadable and means nothing

**Comment by nkorange** [comment]
@fudali113 You cannot use namespace name, this is by design. The same logic is used on Alibaba Cloud.
