### ISSUE TITLE
Add SPI extension to add headers to request

### ISSUE THREAD

**Issue by bdqfork** [alibaba/nacos#6081]
Note that in the implementation of some plug-ins, such as configuring encryption plug-ins, one or more new headers need to be added to the request. The current way is to modify the code directly. Once it needs to be maintained or updated, it needs to be modified again. I think this is not elegant enough. Adding header is the requirement of plug-in implementation, which should be maintained by plug-in implementation.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I think we can provide a SPI extension to add custom headers to the request, such as HeaderProvider, which returns a set of headers to be added. In this way, if you need to add a custom header in the implementation of plug-ins or other applications, you only need to implement the HeaderProvider at the same time.

**Describe alternatives you've considered**

**Additional context**
The SPI extension points can be located in the following locations.
![截屏2021-06-16 下午2 58 46](https://user-images.githubusercontent.com/23702980/122172480-5c6c4780-ceb3-11eb-873e-bc56611da341.png)

**Comment by CherishCai** [comment]
我目前是通过 HttpClientRequestInterceptor 增加一个拦截器实现 EnhanceMetaRequestInterceptor , 仅供参考
```java

/**
 * Nacos enhance meta in client. {@link #init()} must be invoked once.
 * <p> http request add custom param. </p>
 *
 * @author mengyuan
 * @version Id: EnhanceMetaRequestInterceptor.java, v 0.1 2021年05月19日 11:18 上午 mengyuan Exp $
 * @since 1.0.0
 */
public class EnhanceMetaRequestInterceptor implements HttpClientRequestInterceptor {

    private EnhanceMetaRequestInterceptor() { }

    private static final Logger LOGGER = LoggerFactory.getLogger(EnhanceMetaRequestInterceptor.class);

    /**
     * meta will be add to RequestHeader.
     */
    private static Map<String, String> META;

    /**
     * Maybe private, public JustForTest.
     */
    public static final EnhanceMetaRequestInterceptor INSTANCE = new EnhanceMetaRequestInterceptor();

    /**
     * must be invoked once.
     * <li>Before this, invoker have to check <pre>EnhanceNacosUtils.isPresentNaocsClazz()</pre> is true.</li>
     */
    public static void init() {
        if (LOGGER.isInfoEnabled()) {
            LOGGER.info("EnhanceMetaRequestInterceptor inited.");
        }

        List<HttpClientRequestInterceptor> interceptors = ConfigHttpClientManager.getInstance().getNacosRestTemplate().getInterceptors();
        if (!interceptors.contains(INSTANCE)) {
            interceptors.add(INSTANCE);
        }
    }

    @Override
    public HttpClientResponse intercept() {
        // ERROR, Can not do this
        throw new UnsupportedOperationException("EnhanceMetaRequestInterceptor.intercept can't be invoke.");
    }

    @Override
    public boolean isIntercept(URI uri, String httpMethod, RequestHttpEntity requestHttpEntity) {

        try {
            enhanceModifyHeader(requestHttpEntity);
        } catch (Exception e) {
            LOGGER.error("EnhanceMetaRequestInterceptor.isIntercept error", e);
        }
        // must be return false, just enhance meta.
        return false;
    }

    private void enhanceModifyHeader(RequestHttpEntity requestHttpEntity) {
        final Map<String, String> enhanceHeaderMeta = new HashMap<>(this.getMeta());
        // @since 1.0.0
        enhanceHeaderMeta.put(EnhanceMetaConstants.ENHANCE_META_ENV_PROP_NAMES_WITH_ORDER,
                EnvironmentHolder.getPropertySourceNamesWithSplitter());
        if (LOGGER.isDebugEnabled()) {
            LOGGER.debug("EnhanceMetaRequestInterceptor,enhanceHeaderMeta={}", enhanceHeaderMeta);
        }

        requestHttpEntity.getHeaders().addAll(enhanceHeaderMeta);
    }

    private Map<String, String> getMeta() {
        if (META == null) {
            Map<String, String> meta = new HashMap<>(16);
            meta.put(EnhanceMetaConstants.ENHANCE_META_APP, EnvUtils.getApplicationName());

            meta.put(EnhanceMetaConstants.ENHANCE_META_TENANT, EnvUtils.getSiteName());
            meta.put(EnhanceMetaConstants.ENHANCE_META_SITE, EnvUtils.getSiteName());

            meta.put(EnhanceMetaConstants.ENHANCE_META_WORKSPACE, EnvUtils.getWorkspaceNameOrDefault(null));
            meta.put(EnhanceMetaConstants.ENHANCE_META_DATACENTER, EnvUtils.getDataCenterNameOrDefault(null));

            meta.put(EnhanceMetaConstants.ENHANCE_META_REGION, ClusterUtils.getRegionId());
            meta.put(EnhanceMetaConstants.ENHANCE_META_ZONE, ClusterUtils.getAvailabilityZone());

            META = Collections.unmodifiableMap(meta);
        }
        return META;
    }

}

```

**Comment by bdqfork** [comment]
> HttpClientRequestInterceptor

我的理解啊，这个应该是只对短链接的场景生效吧？长链接是通过GrpcSdkClient请求的，应该不经过这个拦截。

**Comment by CherishCai** [comment]
> @CherishCai
> 
> 我的理解哈，您的这个方案，应该是只对短链接的场景生效吧？长链接是通过GrpcSdkClient请求的，应该不经过这个拦截。

哦，是的。现在看到说的是 Nacos 2.x 的，那是有必要啦，目前没有入口

**Comment by Wadyasafslsa** [comment]
> 我 目前 是 通过 HttpClientRequestInterceptor 增加 一个 拦截 器 实现 EnhanceMetaRequestInterceptor ، 仅供 参考
> 
> ```java
> / **
>  * تعمل Nacos على تحسين التعريف في العميل. يجب استدعاء { link #init ()} مرة واحدة. 
> * < p > http طلب إضافة معلمة مخصصة. </ P> 
> * 
> * author mengyuan 
> * version رقم: EnhanceMetaRequestInterceptor.java، والخامس 0.1 2021年05月19日11:18上午mengyuan إكسب $ 
> * since 1.0.0 
> * / العامة الطبقة EnhanceMetaRequestInterceptor الأدوات HttpClientRequestInterceptor { 
>     
> 
>      EnhanceMetaRequestInterceptor الخاص () {}
> 
>     خاص  ثابت  النهائي  المسجل  المسجل  =  LoggerFactory . getLogger ( EnhanceMetaRequestInterceptor . class) ؛
> 
>     / **
>       * ستتم إضافة meta إلى RequestHeader. 
> * / خريطة ثابتة خاصة < سلسلة ، سلسلة > META ؛     
>        
> 
>     / **
>       * ربما JustForTest عام وخاص. 
> * / public static final EnhanceMetaRequestInterceptor INSTANCE = new EnhanceMetaRequestInterceptor () ؛     
>            
> 
>     / **
>       * يجب استدعاءه مرة واحدة. 
>      * < لى > قبل هذا، المنادي أن تحقق < قبل > EnhanceNacosUtils.isPresentNaocsClazz () </ قبل> هو الصحيح. </ لى> 
> * / العام ساكنة باطلة الحرف الأول () {
>          إذا ( المسجل . isInfoEnabled ()) {
>              المسجل . info ( " EnhanceMetaRequestInterceptor inited. " ) ؛     
>        
>         }
> 
>         قائمة < HttpClientRequestInterceptor > اعتراضية =  ConfigHttpClientManager . getInstance () . getNacosRestTemplate () . getInterceptors () ؛
>         إذا ( ! اعتراضات . تحتوي على ( INSTANCE )) {
>             المعترضون . add ( INSTANCE ) ؛
>         }
>     }
> 
>     Override 
>     public  HttpClientResponse  intercept () {
>          // ERROR ، لا يمكن تنفيذ هذا 
>         بطرح  UnsupportedOperationException الجديد  ( " لا يمكن استدعاء EnhanceMetaRequestInterceptor.intercept. " ) ؛
>     }
> 
>     Override 
>     الجمهور  منطقية  isIntercept ( URI  اوري ، سلسلة  httpMethod ، RequestHttpEntity  requestHttpEntity ) {
> 
>         حاول {
>             EnhanceModifyHeader (requestHttpEntity) ،
>         } catch ( استثناء هـ) {
>              LOGGER . خطأ ( " EnhanceMetaRequestInterceptor.isIntercept error " ، e)؛
>         }
>         // يجب أن يكون إرجاع خطأ ، فقط قم بتحسين meta. 
>         عودة  كاذبة .
>     }
> 
>     private  void  ImprovementModifyHeader ( RequestHttpEntity  requestHttpEntity ) {
>          final  Map < String ، String > ImprovementHeaderMeta =  new  HashMap <> ( this . getMeta ())؛
>         // since 1.0.0 
>         EnhancedHeaderMeta . ضع ( EnhanceMetaConstants . ENHANCE_META_ENV_PROP_NAMES_WITH_ORDER ،
>                  EnvironmentHolder . getPropertySourceNamesWithSplitter ()) ؛
>         إذا كان ( LOGGER .isDebugEnabled ()) {
>              المسجل . debug ( " EnhanceMetaRequestInterceptor، ImprovementHeaderMeta = {} " ، ImprovementHeaderMeta)؛
>         }
> 
>         requestHttpEntity . getHeaders () . addAll (EnhanHeaderMeta) ؛
>     }
> 
>      الخريطة  الخاصة < String ، String > getMeta () {
>          if ( META  ==  null ) {
>              Map < String ، String > meta =  new  HashMap <> ( 16 )؛
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_APP ، EnvUtils . getApplicationName ()) ،
> 
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_TENANT ، EnvUtils . getSiteName ()) ،
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_SITE ، EnvUtils . getSiteName ()) ،
> 
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_WORKSPACE ، EnvUtils . getWorkspaceNameOrDefault ( null )) ؛
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_DATACENTER ، EnvUtils . getDataCenterNameOrDefault ( فارغ )) ؛
> 
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_REGION ، ClusterUtils . getRegionId ()) ،
>             ميتا . ضع ( EnhanceMetaConstants . ENHANCE_META_ZONE ، ClusterUtils . getAvailabilityZone ()) ،
> 
>             META  =  المجموعات . خريطة غير قابلة للتعديل (ميتا) ؛
>         }
>         عودة  META ؛
>     }
> 
> }
> ```
