### ISSUE TITLE
本地打开1.4.1源码的依赖问题

### ISSUE THREAD

**Issue by sqskg** [alibaba/nacos#6084]
![image](https://user-images.githubusercontent.com/14267002/122240413-56e32180-cef4-11eb-8ef9-8c4d1f59b33a.png)

**Comment by sqskg** [comment]
这一个个的unknown是什么原因啊

**Comment by quhailong** [comment]
是不是你maven配置的问题

**Comment by sqskg** [comment]
Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:2.1.17.RELEASE from/to sona (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/springframework/boot/spring-boot-dependencies/2.1.17.RELEASE/spring-boot-dependencies-2.1.17.RELEASE.pom. Return code is: 500, ReasonPhrase: Internal Privoxy Error.

**Comment by sqskg** [comment]
这句话是啥意思啊

**Comment by KomachiSion** [comment]
你本地环境的网络问题。连接不上远程仓库。

**Comment by sqskg** [comment]
这里的ID一定要在maven setting文件中存在于server下的ID 这句话啥意思啊

**Comment by quhailong** [comment]
你换阿里仓试试吧

**Comment by sqskg** [comment]
![image](https://user-images.githubusercontent.com/14267002/122320393-b96c0a00-cf54-11eb-9532-972613339d2f.png)

**Comment by sqskg** [comment]
![image](https://user-images.githubusercontent.com/14267002/122320461-d4d71500-cf54-11eb-8223-02eaf98b2535.png)

**Comment by sqskg** [comment]
Downloading的时候就是个unknown版本，打死也下不下来啊

**Comment by quhailong** [comment]
![image](https://user-images.githubusercontent.com/26958237/122320850-7eb6a180-cf55-11eb-9e96-431fbe55ea42.png)
我这1.4.1没啥问题，你刷新一下idea的maven试试

**Comment by sqskg** [comment]
妥了，把本地仓库的spring-boot-dependencies/2.1.17.RELEASE删除；再重新导入即可。

**Comment by sqskg** [comment]
妥了，把本地仓库的spring-boot-dependencies/2.1.17.RELEASE删除；再重新导入即可。

**Comment by sqskg** [comment]
> ![image](https://user-images.githubusercontent.com/26958237/122320850-7eb6a180-cf55-11eb-9e96-431fbe55ea42.png)
> 我这1.4.1没啥问题，你刷新一下idea的maven试试

没错！

**Comment by sqskg** [comment]
> 你本地环境的网络问题。连接不上远程仓库。

多谢

**Comment by quhailong** [comment]
> > ![image](https://user-images.githubusercontent.com/26958237/122320850-7eb6a180-cf55-11eb-9e96-431fbe55ea42.png)
> > 我这1.4.1没啥问题，你刷新一下idea的maven试试
> 
> 没错！多谢

不客气
