### ISSUE TITLE
1.4.2客户端多了个udp随机端口，有什么办法屏蔽这个端口吗

### ISSUE THREAD

**Issue by westcows00481** [alibaba/nacos#6085]
1. 1.4.2客户端多了个udp随机端口，有什么办法屏蔽这个端口吗？
2. 这个端口是否能被其他机器探测到，有什么安全保障？

**Comment by KomachiSion** [comment]
UDP一直都在，用于1.X的服务列表推送

> 1.4.2客户端多了个udp随机端口，有什么办法屏蔽这个端口吗？

暂时无法屏蔽

> 这个端口是否能被其他机器探测到，有什么安全保障？

自行搜索UDP相关网络内容，可以考虑用防火墙阻拦除允许端口以外端口。

**Comment by westcows00481** [comment]
1. 这个端口是什么协议， ssl吗？
2. nacos-server的udp端口怎么指定固定值

**Comment by westcows00481** [comment]
1. 客户端设置push.receiver.udp.port=12000有效， 但是server端怎么指定？

**Comment by westcows00481** [comment]
https://github.com/alibaba/nacos/pull/6090

**Comment by KomachiSion** [comment]
@westcows00481 2.0已经开始使用grpc作为请求和推送的方式，udp保留仅是为了兼容旧版本客户端，因此不再计划支持这方面功能的修改。您如果考虑安全问题希望屏蔽udp端口，可以升级至2.0.2（客户端服务端都需要升级），然后防火墙屏蔽服务端所使用的4个端口以外的其他端口。

**Comment by jefferson-chern** [comment]
> 1. 客户端设置push.receiver.udp.port=12000有效， 但是server端怎么指定？

请问，是怎么设置的，是修改linux机器的环境变量还是在java代码的配置文件设置的？
