### ISSUE TITLE
1.4.2的nacose-server的udp端口怎么指定固定值

### ISSUE THREAD

**Issue by westcows00481** [alibaba/nacos#6087]
1. 1.4.2的nacose-server的udp端口怎么指定固定值？ 或者指定范围

**Comment by westcows00481** [comment]
已经找到了原因了，麻烦阿里大神修复下
https://github.com/westcows00481/nacos/commit/96941a0e9cb3376fe75a7b430663910523b6ed24
https://github.com/westcows00481/nacos/commit/3a8f63d4cfe037e62b1632822a242c35b264e67c

**Comment by westcows00481** [comment]
麻烦看下
https://github.com/alibaba/nacos/pull/6090

**Comment by KomachiSion** [comment]
2.0 will use grpc as push way. UDP will be removed in future and only for adapt nacos 1.x client.
