### ISSUE TITLE
/distro/datums returns dirty data

### ISSUE THREAD

**Issue by Hptux** [alibaba/nacos#6093]
**Describe the bug**
version 2.0.1
k8s pod count 3 (nacos0  nacos1   nacos2)，double write closed
some instance is sync from eureka by nacos-sync
after run 10 days, pod nacos2 restarted because some unknown reason,then this some service of on thid node has dirty instance（registed long time ago） data and intance list is diffrent with other node，and deregister dirty instance use openapi not work

2.0.1nacos版本，运行在k8s里，三个pod，双写已关闭
部分实例是由eureka同步到nacos的，使用的工具是nacos-sync
集群已经运行了10天，nacos2这个pod不知道什么原因重启了，然后部分服务就出现了脏数据，出现了很久之前注册进来的实例，nacos0和nacos1两个pod没有这个实例，而且这种实例通过openapi进行注销，无法注销成功

注：脏数据实例ip端口是可重用的，而且由于刚好被别的服务重用了，这些实例不会被nacos标识为不健康

**Expected behavior**
service instance list sync correct in cluster，and up to date
服务实例在不同节点可以正常同步，而且保持最新
api /distro/datums must return the newest data，to make warmup process right
/distro/datums接口应该返回最新数据，使其他节点warmup操作正确进行

**Acutally behavior**
service instance list diffrent in cluster nodes，and dirt data exists
服务实例列表在不同节点不同步，存在脏数据
api /distro/datums returned dirty data
/distro/datums接口返回的使陈旧数据

**How to Reproduce**
Steps to reproduce the behavior:（may work）
1、start cluster and close double write
2、start service instances，register， after a several minutes or hours，restart service instance register with another ip，old ip is reusable，start a new service use that old ip
3、restart one node of nacos cluster
4、check restarted node data，and query /distro/datums from other node

**Comment by KomachiSion** [comment]
nacos的心跳是按照实例维度的，每个服务的每个实例都会有心跳，服务A ip1 port1如果不发心跳了，只会删除这一个实例，如果有一个服务B ip1 port1继续发心跳，那么服务A的实例会删除，服务B的不会。

所以你所说的脏数据应该不会出现。建议在你的环境排查下，可能出现这种现象的原因。

**Comment by Hptux** [comment]
![image](https://user-images.githubusercontent.com/5194425/122348079-580c6100-cf7d-11eb-8b68-c0c0413abc5e.png)
如图中所示，两个实例，上面的实例是脏数据，只有在nacos2节点上存在，01上没有这条实例
这个ip现在是一个前端项目在使用，而nacos-sync也不可能维持心跳，因为把服务停止依然会存在这条数据
还有什么排查的方法吗？

**Comment by KomachiSion** [comment]
升级2.0.2试试

**Comment by KomachiSion** [comment]
There is no more response from author, so we think the problem has been fixed in new version.
