### ISSUE TITLE
Get wrong instance list at first time

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#61]
How to reproduce this issue, refer to followings:
1. I have registered 2 instances (ex service name  are all 'a') to nacos server
2. Then I stop them
3. After a while, I do step 1 again
4. Then I get 2 instances from interface, for first time, it returns 1 instance or 0 instance. But I invoke again, it is fine to return 2 instances. Guess the cache issue?

**Comment by HaojunRen** [comment]
Sorry, that is Spring Cloud Nacos Discovery issue, refer to https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/19

**Comment by HaojunRen** [comment]
I am wrong, what i pull request just resolve half of issue

**Comment by nkorange** [comment]
Should be caused by #64 .

**Comment by nkorange** [comment]
Already fixed in #64
