### ISSUE TITLE
How to view the cluster status?

### ISSUE THREAD

**Issue by starlifht** [alibaba/nacos#610]
The page does not currently see a clustered display;
// 页面目前没看到有集群状态的展示；
The open API documentation also did not see the relevant interface, how can I view the status of the cluster?
// open API的文档也没看到有相关接口，请问 如何才能查看集群的状态

// ***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by nkorange** [comment]
Will be supported in 0.8.0
