### ISSUE TITLE
Enhancement of Nacos UI

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#6100]
1. 是否可以支持配置的文本区域适配高度，尽可能让编辑区域变大
![图片](https://user-images.githubusercontent.com/42354711/122390655-d29ca700-cfa4-11eb-9a12-76def71f2dd8.png)

2. 是否不要支持换行，影响阅读
![图片](https://user-images.githubusercontent.com/42354711/122393312-53f53900-cfa7-11eb-8361-5f03147c667e.png)

**Comment by KomachiSion** [comment]
Welcome front programmer enhance this issue.
