### ISSUE TITLE
There is a problem with the configuration file loading logic

### ISSUE THREAD

**Issue by lnsane** [alibaba/nacos#6103]
- Chinese

我看了Nacos的源码在Spring Cloud 中 配置文件的加载机制默认是这样的:

bootstrap.yml - > spring.application.name - > spring.application.name.file-extension  -> spring.application.name.[activeProfiles].file-extension

为什么设置了file-extension还要一定加载 spring.application.name 这一步骤？ 是否存在多余？

- English

I read the Nacos source code in Spring Cloud. The configuration file loading mechanism defaults to this:

bootstrap.yml -> spring.application.name -> spring.application.name.file-extension -> spring.application.name.[activeProfiles].file-extension

Why must the spring.application.name step be loaded when the file-extension is set? Is there any redundancy?

**Comment by lnsane** [comment]
Q2：
- Chinese

场景： 我一个项目有不同的后缀文件加载，现在配置无解。

比如 我要加载dev,yml 还要加载 dev.logback.xml 

我有一个想法你觉得这样的是否合理？

以 file-extension 为key List<Config> 为value 进行改造！

- English 

Scenario: I have a project with different suffix files loaded, and now the configuration is unsolvable.

For example, if I want to load dev, yml also needs to load dev.logback.xml

I have an idea. Do you think this is reasonable?

Use file-extension as the key and List<Config> as the value for transformation!

**Comment by KomachiSion** [comment]
Please move issue to spring cloud community
