### ISSUE TITLE
nacos start faile

### ISSUE THREAD

**Issue by percy-circle** [alibaba/nacos#6105]
on my macos(10.13.6) start nacos,the start.out print this logs：
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/n9/h_10fnwj2tdg304hr88fnnc40000gn/T/librocksdbjni8359342911720779518.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/n9/h_10fnwj2tdg304hr88fnnc40000gn/T/librocksdbjni8359342911720779518.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by realJackSun** [comment]
This  is caused by the  incompatibility between rocksdb and your device. Someone have tried to solve it, please see
#4336

**Comment by linxiangqian** [comment]
I also encountered this problem, how did you solve it?

**Comment by linxiangqian** [comment]
#7175  I also encountered this problem, how did you solve it?
