### ISSUE TITLE
Nacos 2.0.0 配置中心异常

### ISSUE THREAD

**Issue by gfgfggf1988** [alibaba/nacos#6108]
新建json格式配置测试过程中发现。
【数据格式】
```java
int size = 20000;
JSONArray array = new JSONArray(size);
for(int i=0;i<size;i++) {
	JSONObject obj = new JSONObject();
	obj.put("app", "dig-dp");
	obj.put("nid", UUID.randomUUID().toString());
	obj.put("tid", "tenant"+i);
	array.add(obj);
}
```
【数据长度】1628891
【效果】
![异常](https://user-images.githubusercontent.com/16377180/122531724-5eb8d800-d052-11eb-9829-7a7bd3dc2da5.png)

```bash
保存300万长度的字符串，类型为text也是截图异常，即使长度过大也不应该是【required string parameter ‘dataId‘is not present】异常
```

**Comment by gfgfggf1988** [comment]
补充一个新的问题
使用上诉java块中的代码，在单机的nacos生成app_5000.json与app_10000.json文件
![数据](https://user-images.githubusercontent.com/16377180/122539999-c70bb780-d05a-11eb-8752-85944627794c.png)
使用
```java
long start = System.currentTimeMillis();
Properties properties = new Properties();
properties.put(PropertyKeyConst.SERVER_ADDR, "172.16.26.79:8848");
ConfigService configService = NacosFactory.createConfigService(properties);
String content = configService.getConfig("app_5000.json", "DEFAULT_GROUP", 3000L);
System.out.println(content.length());
System.out.println("当前数据的执行时间："+(System.currentTimeMillis()-start));
```
代码块进行获取数据的链接测试。返回content为空，.length()空指针

导出的文件：
[nacos_config_export_20210618173127.zip](https://github.com/alibaba/nacos/files/6676108/nacos_config_export_20210618173127.zip)

**Comment by KomachiSion** [comment]
问题1：
字段超长可能导致你的url过长被截断，导致dataId丢失。

问题2:
创建和删除操作为同步写数据库操作，读取时使用的是本地缓存数据，写入和更新本地缓存是异步操作，如果使用getConfig，请等待数秒再去查询。
可以从服务端的config-trace.log中搜索对应dataId的dump相关日志，看到对应时间关系。

**Comment by gfgfggf1988** [comment]
> 问题1：
> 字段超长可能导致你的url过长被截断，导致dataId丢失。
> 
> 问题2:
> 创建和删除操作为同步写数据库操作，读取时使用的是本地缓存数据，写入和更新本地缓存是异步操作，如果使用getConfig，请等待数秒再去查询。
> 可以从服务端的config-trace.log中搜索对应dataId的dump相关日志，看到对应时间关系。

好的  谢谢
