### ISSUE TITLE
-Dnacos.logging.path无法设置客户端日志目录

### ISSUE THREAD

**Issue by xuguoqi302** [alibaba/nacos#6110]
文档上说明设置客户端日志目录参数为：-Dnacos.logging.path=xxx
但是设置该系统参数后不生效
如果设置了-DJM.LOG.PATH=xxx可以设置客户端日志目录位置
请问这是文档说明不对还是我操作设置的有误

**Comment by KomachiSion** [comment]
应该是在重构中统一了一下变量，文档没有及时修改，能提一个PR进行修改吗？

**Comment by xuguoqi302** [comment]
> 应该是在重构中统一了一下变量，文档没有及时修改，能提一个PR进行修改吗？

可以的

**Comment by jiangluqiang** [comment]
您好 无法设置客户端日志目录 这个解决了吗？
