### ISSUE TITLE
每次想重新定义derby-data的目录，都需要重新改正多个变量。能否用一个变量统一一下路径？

### ISSUE THREAD

**Issue by SageX1** [alibaba/nacos#6112]
每次想重新定义derby-data的目录，都需要重新改正多个变量。能否用一个变量统一一下路径？
![image](https://user-images.githubusercontent.com/86160674/122647294-200c4600-d156-11eb-9444-2cc139328fee.png)

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by realJackSun** [comment]
@i will fix it@

**Comment by device911** [comment]
use a variable to fix it

**Comment by joshryan8** [comment]
SATO: Tuesday UPDATE. Your Application for Assistance has been Accepted!

View Your New Programs HERE
-> https://sat-o.com/UUR09Hf

**Comment by joshryan8** [comment]
Where can i type blockchain to convert message

**Comment by aoiuyalong** [comment]
Use variables to fix it

**Comment by LscSir** [comment]
淦

**Comment by zhiyouliao** [comment]
牛批

**Comment by hxydmt** [comment]
很好

**Comment by MpLove1** [comment]
converting through translation

**Comment by omkhairnar** [comment]
use a variable

**Comment by gongzhijian** [comment]
Can the issue  be fixed by others?

**Comment by rojgarsangam** [comment]
Can the issue be fixed by others?

**Comment by Ruby6789** [comment]
Ok

**Comment by Ruby6789** [comment]
On 19 Jun

**Comment by Ruby6789** [comment]
#6112
