### ISSUE TITLE
nacos namespace useless

### ISSUE THREAD

**Issue by UnseemlyCloud** [alibaba/nacos#6113]
nacos namespace ineffective，awalys public - -

 - OS: [MACOS]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Comment by KomachiSion** [comment]
Please provider more information, I test the namespace feature is work well.

**Comment by UnseemlyCloud** [comment]
I set up the address of Nacos and the UUID of namespace（spring.cloud.nacos.discovery.namespace=3bab8e9d-972c-4b11-a44f-74714ac7f471）, and I can register it, but I always register it in public namespace


In addition, I use the bigsur version of MacOS M1 chip. Every time I start, I must be able to access port 8848 in standalone mode, but not in cluster mode. In addition, during the test, I found that version 1.4.2 must be started in standalone mode to access port 8848, and version 2. X can't access port 8848 no matter what mode it starts





thanks
--------------------------------------------------------
我设置了nacos的地址和namespace的UUID，并且能注册上去，但是总是注册到public下
另外我用的是macos m1芯片 bigSur版本，每次启动的时候都必须是standalone 模式下 8848端口可以访问,集群模式无法访问，而且测试的时候发现1.4.2版本都必须是standaone模式启动才能访问8848端口，2.x版本无论什么模式启动后都无法访问



谢谢




















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos namespace useless (#6113)



 Please provider more information, I test the namespace feature is work well.

**Comment by KomachiSion** [comment]
Maybe your configuration for spring cloud is wrong or your spring cloud version has some problem. Please move to spring cloud community to feedback.

Or use original nacos-client to set namespaceId and try to test.
