### ISSUE TITLE
get /health/atuator  return DOWN  because nacosDiscovery is down

### ISSUE THREAD

**Issue by yujun110** [alibaba/nacos#6117]
**Describe the bug**
get /health/atuator  return DOWN  because nacosDiscovery is down.but on nacos dashboard i can see the service.
/health/atuator  result as following：
`{
    "status":"DOWN",
    "components":{
        "discoveryComposite":{
            "status":"UP",
            "components":{
                "discoveryClient":{
                    "status":"UP",
                    "details":{
                        "services":[
                            "kaihu-micro-helper",
                            "kaihu-micro-operate",
                            "kaihu-gateway"
                        ]
                    }
                }
            }
        },
        "diskSpace":{
            "status":"UP",
            "details":{
                "total":3833041485824,
                "free":3113200898048,
                "threshold":10485760,
                "exists":true
            }
        },
        "livenessState":{
            "status":"UP"
        },
        "nacosConfig":{
            "status":"UP"
        },
        "nacosDiscovery":{
            "status":"DOWN"
        },
        "ping":{
            "status":"UP"
        },
        "reactiveDiscoveryClients":{
            "status":"UP",
            "components":{
                "Simple Reactive Discovery Client":{
                    "status":"UP",
                    "details":{
                        "services":[

                        ]
                    }
                }
            }
        },
        "readinessState":{
            "status":"UP"
        },
        "refreshScope":{
            "status":"UP"
        }
    },
    "groups":[
        "liveness",
        "readiness"
    ]
}`

spring-cloud-alibaba-nacos-discovery version:2.2.2

**Comment by KomachiSion** [comment]
Please move issue to spring cloud comunity
