### ISSUE TITLE
nacos1.4.2部署在不同机器上（内网），有个节点一直 no leader is available now!

### ISSUE THREAD

**Issue by f1558** [alibaba/nacos#6119]
## Issue Description
1、nacos1.4.2 is deployed on different machines (intranet), and one node has always been no leader is available now！
2、Sometimes it is impossible to select the master node, or there is a delay.

### How to reproduce it (as minimally and precisely as possible)

1.  The problem is as follows：
![image](https://user-images.githubusercontent.com/49510754/122737596-c91c8300-d2b3-11eb-8ce8-4f7641151ff5.png)

### Tell us your environment
The intranet environment we use (e. G： 172.56.23.130)

**Comment by KomachiSion** [comment]
The old raft will be removed. if your cluster deploy correctly. the old raft system will close. so you should check whether your cluster deploy correctly.

**Comment by f1558** [comment]
> 旧木筏将被移除。如果您的集群部署正确。旧的筏系统将关闭。所以你应该检查你的集群部署是否正确。

1、Cluster deployment is based on documentation
2、I copied two copies of the Nacos of a single node and deployed them on one of the machines and one on the other machine, a total of three
3、Changed cluster.conf（Using intranet IP）

**Comment by realJackSun** [comment]
> > 旧木筏将被移除。如果您的集群部署正确。旧的筏系统将关闭。所以你应该检查你的集群部署是否正确。
> 
> 1、Cluster deployment is based on documentation
> 2、I copied two copies of the Nacos of a single node and deployed them on one of the machines and one on the other machine, a total of three
> 3、Changed cluster.conf（Using intranet IP）

You means that the 1st and 2nd node are on the same machine, and the 3rd is on another machine? I don't think this is a correct way to deploy Nacos cluster. The correct way is that each nacos node is deployed on an unique machine.
anyway, can you show your cluster.conf ?

**Comment by f1558** [comment]
yes,  that the 1st and 2nd node are on the same machine, 3rd is on another machine.
Do you mean that the correct deployment method is that each machine can only have one node?
Currently, the cluster.conf of each node is the same(as shown in the figure below)
![image](https://user-images.githubusercontent.com/49510754/122952558-a7ed8c80-d3b0-11eb-974e-c24ca9cde06d.png)

**Comment by KomachiSion** [comment]
The node in same machine is ok. But you need to check whether they can connect to each other.

Your problem means there are some nodes can't get other node report so that it can't get the cluster status to close old raft.

you need to check this.

**Comment by f1558** [comment]
This is my cluster.conf
  172.16.66.101:18848
  172.16.66.102:18848
  172.16.66.102:18850

They are in the same network segment. I think these nodes can connect normally，the firewall also opens these ports

I didn't find the cluster deployment document in the official website document, only the single node deployment document, or where can I find the detailed cluster deployment document

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

maybe you do not read document. Nacos document use one node per machine as an example. 

Even three nodes in one machine, the steps are not changes. And I can deploy well in my local env with three nodes.

So your cluster can't work well is your env problem. And you should check more information.

**Comment by realJackSun** [comment]
have it be solved? @f1558

**Comment by f1558** [comment]
Resolved, network, environmental issues
