### ISSUE TITLE
nacos  client 怎么打出发布包

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#6123]
注意到直接使用maven 依赖的nacos-client结构如下图所示
![image](https://user-images.githubusercontent.com/53824889/122768598-57a1fc00-d2d6-11eb-9ff6-2eb8fa5a8d17.png)

自己从nacos-all使用源码mvn install 的方式只能打出下面的包
![image](https://user-images.githubusercontent.com/53824889/122768812-8b7d2180-d2d6-11eb-89c8-b6bf7304f086.png)

如果要依赖自己打包的nacos-client的话，还要手动依赖nacos-api和nacos-common

就算手动把nacos-client目录下的pom.xml文件里面的optional 注释掉，在依赖自己打包的nacos-client的时候也不过是级联依赖nacos-api和nacos-common

请各位大佬赐教一下，如何才能打出上传到仓库里面的这种nacos-client包呢？

**Comment by KomachiSion** [comment]
mvn clean install -Prelease-nacos -U -Dmaven.test.skip=true

**Comment by MajorHe1** [comment]
已明确，进入到nacos-client目录下使用 mvn clean  install -Prelease-nacos 即可
