### ISSUE TITLE
java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by qovd520** [alibaba/nacos#6125]
![image](https://user-images.githubusercontent.com/39698224/122853839-6a9fe500-d345-11eb-9f82-4e89a79d4917.png)

![image](https://user-images.githubusercontent.com/39698224/122853864-78556a80-d345-11eb-9175-41cd85972167.png)
nacos 集群后通过nginx进行代理，微服务连接单个nacos 可以，但是连接nginx代理的地址就一值报错，还自动更改连接端口

**Comment by MajorHe1** [comment]
![image](https://user-images.githubusercontent.com/53824889/122855524-f1ee5800-d347-11eb-8420-34a004ac60f7.png)

可以参考 https://nacos.io/zh-cn/docs/2.0.0-compatibility.html
