### ISSUE TITLE
Service offline problem

### ISSUE THREAD

**Issue by keweiLv** [alibaba/nacos#6126]
In version 2.0.0, click offline service appears to be wrong:
caused: errCode: 500, errMsg: do metadata operation failed ;caused: com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_instance_metadata] did not find the Leader node;caused: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_instance_metadata] did not find the Leader node;
I'm sorry, I can't solve the problem。So I chose to upgrade version 2.0.2。
But new problems arise：In the new version, the service can be used offline. After a short delay, the service is not available, but it is always displayed as health service in the service list.This is the latest version, I don't know how to solve it

**Comment by keweiLv** [comment]
In addition, it is started in standalone mode

**Comment by KomachiSion** [comment]
`NoLeaderException` `did not find the Leader node`. I is not relative to version. It is your cluster deploy problem so that the jraft can't vote a leader.

You should check the alipay-jraft.log and naming-raft.log to find out why your cluster can vote leader.

**Comment by keweiLv** [comment]
I understand that the problem lies in the leader node, but I don't understand why it appears and how to solve it. I made the same mistake using the official zip package. I can see the log you said, which is also a leader node and metadata problem. Do you have any direct or clear solutions?

**Comment by keweiLv** [comment]
> `NoLeaderException` `did not find the Leader node`. 它与版本无关。这是您的集群部署问题，因此 jraft 无法投票给领导者。
> 
> 您应该检查 alipay-jraft.log 和 Naming-raft.log 以了解为什么您的集群可以投票为领导者。

I understand that the problem lies in the leader node, but I don't understand why it appears and how to solve it. I made the same mistake using the official zip package. I can see the log you said, which is also a leader node and metadata problem. Do you have any direct or clear solutions?

**Comment by keweiLv** [comment]
> `NoLeaderException` `did not find the Leader node`. It is not relative to version. It is your cluster deploy problem so that the jraft can't vote a leader.
> 
> You should check the alipay-jraft.log and naming-raft.log to find out why your cluster can vote leader.

Moreover, at this time, the service registration and discovery functions are normal, but the service cannot be edited, such as modifying the weight and offline.

**Comment by keweiLv** [comment]
> `NoLeaderException` `did not find the Leader node`. It is not relative to version. It is your cluster deploy problem so that the jraft can't vote a leader.
> 
> You should check the alipay-jraft.log and naming-raft.log to find out why your cluster can vote leader.

Moreover, at this time, the service registration and discovery functions are normal, but the service cannot be edited, such as modifying the weight and offline.

**Comment by KomachiSion** [comment]
> > `NoLeaderException` `did not find the Leader node`. It is not relative to version. It is your cluster deploy problem so that the jraft can't vote a leader.
> > You should check the alipay-jraft.log and naming-raft.log to find out why your cluster can vote leader.
> 
> Moreover, at this time, the service registration and discovery functions are normal, but the service cannot be edited, such as modifying the weight and offline.

Your cluster is in problem, so only some core feature can be used, some feature will be limited before your cluster fixed.

Community don't have your environment, so you should check log by yourself and provide key informations.

**Comment by keweiLv** [comment]
> > > `NoLeaderException` `did not find the Leader node`. 它与版本无关。这是您的集群部署问题，因此 jraft 无法投票给领导者。
> > > 您应该检查 alipay-jraft.log 和 Naming-raft.log 以了解为什么您的集群可以投票为领导者。
> > 
> > 
> > 而且，此时服务的注册和发现功能是正常的，但是不能对服务进行编辑，比如修改权重、下线等。
> 
> 您的集群有问题，因此只能使用某些核心功能，在您的集群修复之前，某些功能将受到限制。
> 
> 社区没有你的环境，所以你应该自己检查日志并提供关键信息。

OK, I'll try

**Comment by keweiLv** [comment]
> > > `NoLeaderException` `did not find the Leader node`. It is not relative to version. It is your cluster deploy problem so that the jraft can't vote a leader.
> > > You should check the alipay-jraft.log and naming-raft.log to find out why your cluster can vote leader.
> > 
> > 
> > Moreover, at this time, the service registration and discovery functions are normal, but the service cannot be edited, such as modifying the weight and offline.
> 
> Your cluster is in problem, so only some core feature can be used, some feature will be limited before your cluster fixed.
> 
> Community don't have your environment, so you should check log by yourself and provide key informations.

I've tried to solve the problem as much as I can. But there are still problems. In my local environment, there was also an abnormal offline problem, but when I restart the Nacos service, it will return to normal without other changes. In the test environment, the above methods did not solve the problem. I checked a lot of logs, but I didn't find any obvious error. I always do metadata operation failed. Can you provide some solutions.

**Comment by KomachiSion** [comment]
Check alipay-jraft.log and Naming-raft.log. The reason why you can't vote leader is in these two logs.

The leader is jraft leader, not nacos' leader. So you should learn raft protocol first and read alipay-jraft.log. 

Most likely problems are ip changes more than half of nodes. Or more than half node can't be connected.

**Comment by keweiLv** [comment]
> Check alipay-jraft.log and Naming-raft.log. The reason why you can't vote leader is in these two logs.
> 
> The leader is jraft leader, not nacos' leader. So you should learn raft protocol first and read alipay-jraft.log.
> 
> Most likely problems are ip changes more than half of nodes. Or more than half node can't be connected.

I checked the log carefully again, and I saw the voting exception in alipay-jraft.log: node < naming_ persistend_ service_ V2 / 128. XXX. XXX. XXX: 7848 > can't do prevote as it is not in conf < configurationentry [id = logid [index = 1, term = 1], conf = 172.20.10.5:7848, oldconf = >. Among them, 128 is my server IP, but the server is multi NIC. I set the nacos.inetutils.ip-address parameter to specify the IP, but 172.20xxx is the LAN IP of my local win machine, I don't know why it has something to do with my hometown. In addition, in the Nacos console, I also found that the node metadata is also the LAN IP 172.20xxx of my local win machine. Is there any other configuration file? I can't find the relevant configuration file in application. Properties. In short, I think it may be the problem of multiple network cards or the impact of unknown configuration files. I look forward to your answer.

**Comment by keweiLv** [comment]
Great. I've solved this problem by modifying application. Properties to specify the IP address. Now it's in normal use. However, I still have doubts about why the IP address I tested locally is synchronized to the server, which is also shown in the metadata. I have not found the relevant configuration file. I think this is the root cause of the abnormality.

**Comment by iswift** [comment]
> Great. I've solved this problem by modifying application. Properties to specify the IP address. Now it's in normal use. However, I still have doubts about why the IP address I tested locally is synchronized to the server, which is also shown in the metadata. I have not found the relevant configuration file. I think this is the root cause of the abnormality.

How you solved? I have the same problem @keweiLv

**Comment by keweiLv** [comment]
As I said above: first of all, check whether it is multi NIC setting. If it is, you can specify your IP by modifying application.properties: nacos.inetutils.ip-address. Similarly, your corresponding service registration address should be the same. In addition, you can try to delete the default configuration folder of Nacos, because I think its historical data may have an impact. If it's a Windows system, its default address is C:: (users) {user name} Nacos. If it's a Linux system, there may be an automatically created ACOS folder on the upper layer of your deployment Nacos folder. Try to delete it and restart the Nacos service. @iswift

**Comment by realJackSun** [comment]
@iswift  Could you contribute your experience to nacos document site?
https://github.com/nacos-group/nacos-group.github.io

Or you can just make it as a FAQ and I can help you to make it on the site.

**Comment by KomachiSion** [comment]
> Great. I've solved this problem by modifying application. Properties to specify the IP address. Now it's in normal use. However, I still have doubts about why the IP address I tested locally is synchronized to the server, which is also shown in the metadata. I have not found the relevant configuration file. I think this is the root cause of the abnormality.

Jraft is strict raft implementation, all metadata and operation will store in log and persistent into disk. And any changes or operation need to do with leader. So if you IP has some change, or IP set error, will cause the raft metadata is wrong and can't vote a new leader.

**Comment by iswift** [comment]
I've solved this problem by modifying nacos.inetutils.ip-address to 172.18.0.3, I am curious why the leader's IP is 172.18.0.3。
The server does not have this IP，Nacos server uses docker to deploy。standalone

![image](https://user-images.githubusercontent.com/3256088/124062384-3c1bbb80-da63-11eb-84f7-80e3659332e9.png)

final nacos node metadata:
![image](https://user-images.githubusercontent.com/3256088/124062553-76855880-da63-11eb-96cf-10302973cf88.png)

**Comment by KomachiSion** [comment]
Maybe the ip is the last time you start up.

**Comment by KomachiSion** [comment]
There is no more response from author. Close it first.
