### ISSUE TITLE
Nacos use MySQL8 driver is not support MySQL8

### ISSUE THREAD

**Issue by peggypig** [alibaba/nacos#613]
Purpose: Start a cluster of nacos 0.7
// 目的：启动nacos 0.7的集群
Accident: Startup error, error: DumpService was not created successfully
// 意外：启动出错，报错：DumpService没有创建成功
![image](https://user-images.githubusercontent.com/22925560/51024121-9ee31900-15c3-11e9-9c9e-745399f86f64.png)
![image](https://user-images.githubusercontent.com/22925560/51024133-a60a2700-15c3-11e9-8d8b-32b494120230.png)

Check the configuration file without errors
// 检查配置文件并没有错误
============================👇===================================
Replace the mysql database version, the result is successful! ! !
// 更换mysql数据库版本，结果成功！！！
Cause **The mysql driver used by nacos does not support mysql8. **
// 原因 **nacos使用的mysql驱动不支持mysql8。**
Can support mysql8.
// 可以对mysql8进行支持。

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by yanj0609** [comment]
According to MySQL manual, Connector J/5.1 provides compatibility with all the functionality of MySQL 8.0, though Connector J/8.0 is the recommended version.

Connector/J version | JDBC version | MySQL Server version | JRE Supported | JDK Required for Compilation | Status
-- | -- | -- | -- | -- | --
8.0 | 4.2 | 5.5, 5.6, 5.7, 8.0 | 1.8.x | 1.8.x | General availability. Recommended version.
5.1 | 3.0, 4.0, 4.1, 4.2 | 5.5, 5.6*, 5.7*, 8.0* | 1.5.x, 1.6.x, 1.7.x, 1.8.x* | 1.5.x and 1.8.x | General availability

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-versions.html

**Comment by naturalyui** [comment]
我用的mysql8.0.14也遇到了无法连接的问题，下载了0.8.0的源码自己调试
以下是我的尝试（前提是将jdbc.url改为自己的mysql）
1、升级mysql-connector-java驱动到8.0.14，将JDBC_DRIVER_NAME改为com.mysql.cj.jdbc.Driver,提示找不到'com.mysql.cj.jdbc.Driver'
2、不修改源码，报空指针，定位到
![image](https://user-images.githubusercontent.com/26024263/51583440-89e37f80-1f0b-11e9-9d41-37742c01b19f.png)
原因很明了了，因为my.cnf中没有配置character_set_server属性
解决方案:
修改/etc/my.cnf配置文件，在[mysqld]下添加编码配置，如下所示：
[mysqld]
character_set_server=utf8
保存，重启mysql服务
systemctl restart mysqld
问题解决

**Comment by quzhixue-Kimi** [comment]
hi all,

The repository has been downloaded into my local MacOS and, the version of mysql-connector-java has been replace with 8.0.14. But, there is one error occurred. As com.mysql.jdbc.jdbc2.optional.MysqlDataSource could not be found.

My local environment is mysql 8.0.X

It is appreciated that the nacos could support the version 8 later.

BR
Kimi

**Comment by TsingLiang** [comment]
1.0版本会支持mysql 8.X版本

**Comment by zhuyeqing5828** [comment]
`/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Djava.ext.dirs=/usr/lib/jvm/java-1.11.0-openjdk-amd64/jre/lib/ext:/usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/ext:/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/plugins/cmdb:/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/plugins/mysql -Xloggc:/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos -Dloader.path=/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/plugins/health -jar /home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/conf/ --logging.config=/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
-Djava.ext.dirs=/usr/lib/jvm/java-1.11.0-openjdk-amd64/jre/lib/ext:/usr/lib/jvm/java-1.11.0-openjdk-amd64/lib/ext:/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/plugins/cmdb:/home/zx/git/nacos/distribution/target/nacos-server-1.1.3/nacos/plugins/mysql is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
`
 the same problom use 1.1.3 source build
