### ISSUE TITLE
如图 nacos 2.0 集群问题

### ISSUE THREAD

**Issue by qovd520** [alibaba/nacos#6131]
![image](https://user-images.githubusercontent.com/39698224/122880042-21af5700-d36c-11eb-8c67-178b87e55df3.png)

**Comment by qovd520** [comment]
nacos 2.x 部署文档 麻烦补充一下nginx 代理配置

**Comment by realJackSun** [comment]
https://nacos.io/zh-cn/docs/2.0.0-compatibility.html
![image](https://user-images.githubusercontent.com/58767027/122929522-a1a1e500-d39d-11eb-8aae-1eac0691a409.png)
@qovd520 文档上有一个简略的描写，你还踩了什么坑？在这里发出来，我加上去

**Comment by qovd520** [comment]
看了一问题记录有好多和我一样的问题 #6072 、#5269

**Comment by qovd520** [comment]
把可行的 nginx tcp 转发配置贴出来就行

**Comment by KomachiSion** [comment]
nginx配置不应该出现在nacos的文档上吧，方法已经说明了，如何配置应该可以自行搜索。

**Comment by zzx769394358** [comment]
> 

nacos2.0的集群+nginx你可以了吗
我也遇到了nginx配置文件的问题，  web管理页面可以访问，但服务注册不上去。
你要解决了的话发下？

**Comment by JaneYork** [comment]
> #5269

还有nginx相关配置了吗？网站地址不存在了？
