### ISSUE TITLE
控制台登录问题

### ISSUE THREAD

**Issue by Dduanduan** [alibaba/nacos#6143]
nacos控制台能否支持直接调用API登录（不只是获取accesstoken），而不用手动输入用户名和密码？

//有道翻译
Can the Nacos console support direct API login calls (not just getting Accesstoken) without manually entering a username and password?

**Comment by KomachiSion** [comment]
没理解，不输入用户名密码怎么登陆？调用第三方oauth？

**Comment by Dduanduan** [comment]
就是想通过调用API携带登录信息进行登录后跳转到页面，省略手动输入用户名密码的步骤。

**Comment by KomachiSion** [comment]
应该不支持吧，好像没有这么做的。一般都是未登陆或者登录信息失效转到登陆界面然后登陆。
