### ISSUE TITLE
集群部署时，使用同一个主机。 同IP，不同端口。 启动报错：Caused by: java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by fenght** [alibaba/nacos#6145]
1.2.0 版本正常启动，cluster.conf内容如下
192.168.xxx.1:8848
192.168.xxx.2:8848
192.168.xxx.2:8849

2.0.2 版本报错（相同配置），cluster.conf内容如下
192.168.xxx.1:8848
192.168.xxx.2:8848
192.168.xxx.2:8849

**Comment by KomachiSion** [comment]
读一下nacos2.0的问题，知道一下需要哪些端口，再提问

https://nacos.io/en-us/docs/2.0.0-compatibility.html
