### ISSUE TITLE
nacos集群节点角色一直是candidate

### ISSUE THREAD

**Issue by wytjiayou** [alibaba/nacos#6146]
**Describe the bug**
nacos集群有三个几点，一个角色为leader，一个为follower，一个一只是candidate

**Expected behavior**
不知道节点什么时候开始变成candidate角色的，但是今天一天都是这个角色没有变换成follower。
![image](https://user-images.githubusercontent.com/21037575/123075985-49c1b780-d44b-11eb-9042-32d9936dff7b.png)

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [ nacos-server 1.4.0, nacos-client 1.3.3]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
1.4.0 use jraft replace old raft. Old raft will be removed.

This problem has been fixed in 1.4.1. After all cluster upgrading to 1.4.1 and upon, the old raft information will be deleted.
