### ISSUE TITLE
Java SDK 获取文件扩展名

### ISSUE THREAD

**Issue by Ifdevil** [alibaba/nacos#6147]
ConfigService接口可以添加获取配置文件内容以及扩展名的接口吗？或者现在有什么其他方法获取吗？

**Comment by KomachiSion** [comment]
没看懂问题。 获取配置内容不是有接口吗 getConfig
扩展名是什么意思，文件扩展名吗？ 那就是dataId的内容，nacos不管的。

**Comment by Ifdevil** [comment]
> 没看懂问题。 获取配置内容不是有接口吗 getConfig
> 扩展名是什么意思，文件扩展名吗？ 那就是dataId的内容，nacos不管的。

是的，文件扩展名，可能我姿势不对？我在dataId中写了文件扩展名，调用getConfig获取不到内容，我再看看吧，谢谢大佬，可以关闭了

**Comment by Ifdevil** [comment]
> 没看懂问题。 获取配置内容不是有接口吗 getConfig
> 扩展名是什么意思，文件扩展名吗？ 那就是dataId的内容，nacos不管的。

明白了，谢谢，我dataId没有写文件扩展名，只在页面选了properties类型，可以关闭了哈
