### ISSUE TITLE
Start nacos cluster in a multi-NIC environment

### ISSUE THREAD

**Issue by peggypig** [alibaba/nacos#615]
Environment: The machine has two network cards, one is 192 ip, one is 10 ip
// 环境：机器有两个网卡，一个是192的ip，一个是10的ip
Purpose: Start nacos cluster and create service
// 目的：启动nacos cluster并且创建service
Accident: No leader is available now!
// 意外：报错no leader is available now!
Cause: The nacos instance reads the 192 ip, then I configured the 10 ip in the cluster.conf.
// 原因：nacos实例时读取了192的ip，然后我在cluster.conf配置的是10的ip
Hope: nacos can support the function of type ipPrefer of spring cloud
// 希望：nacos可以支持类型spring cloud 的ipPrefer的功能
![image](https://user-images.githubusercontent.com/22925560/51027846-daceac00-15cc-11e9-8355-874a375b2c50.png)

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by nkorange** [comment]
This is related to #580 .

**Comment by peggypig** [comment]
@nkorange #580 跟我描述的问题类似
希望在nacos后期版本中，能加入主机Ip地址配置过滤的功能
