### ISSUE TITLE
nacos 监控没有nacos_exception_total异常指标

### ISSUE THREAD

**Issue by lanyuange** [alibaba/nacos#6151]
[root@ddll-nacos1 ~]# curl -s http://127.0.0.1:8848/nacos/actuator/prometheus | grep "nacos_exception_total"
[root@ddll-nacos1 ~]#
没有收到nacos_exception_total
<img width="1378" alt="aa" src="https://user-images.githubusercontent.com/19629949/123210731-03289780-d4f5-11eb-9e9f-dcb6b9a69367.png">
这个指标的监控

**Comment by KomachiSion** [comment]
which version you used?

**Comment by lanyuange** [comment]
2.0.1

**Comment by KomachiSion** [comment]
2.X may removed this monitor items.

**Comment by lanyuange** [comment]
2.x的监控手册有吗？

**Comment by KomachiSion** [comment]
和1.X的监控手册应该是差不多的，只是删去了一些关于异常的内容。

主要原因是内部有大量重构导致异常位置有很大变动，需要重新寻找重要异常埋点并重新统计。
