### ISSUE TITLE
2.0.2在修改配置文件,确认发布时报错

### ISSUE THREAD

**Issue by gjen1996** [alibaba/nacos#6152]
caused: PreparedStatementCallback; SQL [INSERT INTO his_config_info (id,data_id,group_id,tenant_id,app_name,content,md5,src_ip,src_user,gmt_modified,op_type) VALUES(?,?,?,?,?,?,?,?,?,?,?)]; Field 'nid' doesn't have a default value; nested exception is java.sql.SQLException: Field 'nid' doesn't have a default value;caused: Field 'nid' doesn't have a default value;

**Comment by KomachiSion** [comment]
I can't reproduce your problem. It seems that your tables create error.
