### ISSUE TITLE
nacos 除MySQL外关于达梦等其它数据库存储支持

### ISSUE THREAD

**Issue by beijixing1745** [alibaba/nacos#6155]
用的nacos 版本 2.0.1，需要用到达梦关系型数据库作为存储配置的数据库。

参考 https://github.com/alibaba/nacos/issues/2328
        
参考 https://github.com/alonelaval/nacos 已 适配了 1.4.1版本的已配达梦，人大金仓

通过源码比较发现：
（1）config maven子工程，有几个类写死了mysql的字符串判断来判断是否为外部数据库存储？
（2）ExternalStoragePaginationHelperImpl的分页通过几个函数写死了分页查询适配的数据库？

如果想适配其它外部数据库存储，是否只需求修改主要这两个地方和代码中的sql语句？

建议外部数据库建立连接池用的jdbcDriverName，testQuery等跟连接池相关都可外部配置？
nacos外部存储的数据库连接池是否可以只建立一个DataSource，通过外部数据库集群保证外部数据库的高可用，减少数据库存储这块复杂度？

另：
（1）naming maven子工程，也有一些写死的mysql health相关的判断，是否也需要修改？

烦请指导，谢谢！

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/tree/feature_multiple_datasource_support

多数据库支持的测试分支，用的jpa，但是没有经过足够测试，没有合并到主干分支。
并且jpa太重，计划还是希望用更简单的方式去做。

**Comment by beijixing1745** [comment]
看feature_multiple_datasource_support的代码了，里面代码是nacos 1.4.2。我们用的是spring boot 2.4.6 spring cloud 2020.0.3，spring cloud alibaba 2021.1，所以想用2.0.x的nacos。

还有几个其它疑问？

（1）.为了适配多数据库的支持，只修改一个config子工程就可以吗？
    naming maven子工程，也有一些写死的mysql health相关的判断，是否也需要修改？
麻烦回复。

（2）jpa本身可能有点重，但从兼容性上来说可以尽量少的修改代码兼容不同的数据库，hibernate几乎适配了大部分市面上的数据库，国产数据库也会提供相应的jar。

  另如采用其它方式兼容不同数据库
（1）是否可以把外部数据库支持需要实现的接口调整一个包下，想自己扩展可以更好知道扩展那些类，验证后的代码也好回馈社区。
（2）sql语句是否可以抽到配置文件，扩展其它数据库修改配置文件sql，分页配置等即可？

**Comment by KomachiSion** [comment]
1. 和naming应该关系不大，目前只有config和auth使用了数据库
2. jpa非常重，重到需要改大量代码来适配jpa，而且jpa实现和jpa本身是两回事，hibernate的大小本身就快比得上一个nacos了
3. 其他方式目前构想是把执行SQL和生产SQL的逻辑拆分开，执行SQL统一，生产SQL通过扩展插件来实现，不同的数据库使用插件生产不同sql即可。至于是放在配置文件里还是写死在代码里就是看插件实现人的想法了。
4. 要实现3的部分也需要改动代码，将持久化部分解耦抽象出去，这块工作的风险比较大，目前还没有committer有空来执行这项改动。

**Comment by beijixing1745** [comment]
谢谢，KomachiSion回复！

个人认为，nacos作为一个产品更重要的是他的注册中心，配置中心，客户端、服务端功能以及集群功能更重要些。
对于config、auth持久化方式：
1.用个功能较全面的使用面广的orm框架的jpa，持久化适配的数据库会更多点。
2.或配置文件的mybatis方式。
会更好些，自己再实现生产SQL，执行SQL逻辑，有可能会带来SQL注入，数据库兼容性问题。

因为查询条件的动态组合写死到代码或使用到的数据库函数一旦写死到代码，都有可能带来数据库兼容性问题。

**Comment by KomachiSion** [comment]
因为他是一个比较基础的中间件，所以应该尽量轻量，减少过重依赖，JPA显然不满足。

mybatis虽然写SQL灵活，但是适配多类型数据源还是不不够灵活。我们还是期望能够减少依赖，尽量只通过SPI来实现。
