### ISSUE TITLE
请问SpringCloud中如何配置服务的分组？

### ISSUE THREAD

**Issue by MeSilence** [alibaba/nacos#6158]
请问SpringCloud配置文件中discovery为什么没有group的配置，如：
spring.cloud.nacos.discovery.group: XXX_GROUP

应该如何配置组名称呢？还是不需要配置？

使用版本：
    - spring-boot-starter-web:2.1.6.RELEASE
    - spring-cloud-starter-alibaba-nacos-discovery:2.1.0RELEASE

![image](https://user-images.githubusercontent.com/44824747/123358943-f3fe2400-d59e-11eb-9035-4eafb9031572.png)

**Comment by zzq1314zll** [comment]
@MeSilence ,升级你的spring-cloud-starter-alibaba-nacos-discovery版本

**Comment by zzq1314zll** [comment]
![image](https://user-images.githubusercontent.com/33930711/123365991-f154fc00-d5a9-11eb-82a1-1ca82c667851.png)
在最新版本中客户端在注册的时候有传group的

**Comment by vansAir** [comment]
> @MeSilence ,升级你的spring-cloud-starter-alibaba-nacos-discovery版本

哪个版本有这个?用了最新的2021.1都没有找到getgroup这句代码
