### ISSUE TITLE
nacos 2.01重启后注册的服务分组信息丢失

### ISSUE THREAD

**Issue by moruikang** [alibaba/nacos#6159]
**Describe the bug**
nacos 2.0.1 集群部署，重启后发现服务分组信息丢失了
原来是：
![image](https://user-images.githubusercontent.com/20991830/123360631-38d68a80-d5a0-11eb-95a2-c48f166e2ad9.png)

重启后变成：
![image](https://user-images.githubusercontent.com/20991830/123360676-49870080-d5a0-11eb-8aa6-4c5d9f57e558.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Can you provide the reproduce steps? 
Or upgrade 2.0.2 and retry?

**Comment by moruikang** [comment]
> Can you provide the reproduce steps? such as start with standalone/cluster mode, restart one by one or together.
> Or upgrade 2.0.2 and retry?

重启几次后 就恢复正常了 我是部署在k8s里面

**Comment by KomachiSion** [comment]
我理解应该是先停止单例然后在扩容成3节点集群。但是我试了几次都没有复现你的问题。

是使用的openAPI还是nacos的客户端的哪个api？

**Comment by moruikang** [comment]
原本是3个pod，设置statesfulsets replica=0 后会逐个pod停止。

访问接口是： /nacos/v1/ns/service/names?namespaceId=4804405f-f1b6-4534-8478-53aab1a18253

我在issue上查到这个bug fix： https://github.com/alibaba/nacos/issues/5872
是不是这个原因引起的？

**Comment by KomachiSion** [comment]
可以升级2.0.2试一下还能不能复现。

**Comment by KomachiSion** [comment]
There is no more response from author, so we think new version has solved this problem.
