### ISSUE TITLE
When will the v0.8.0 release be released?

### ISSUE THREAD

**Issue by thousmile** [alibaba/nacos#616]
Spring cloud Pay attention to this project when you post news on twitter.
// spring cloud 在twitter 发新闻的时候，就注意这个项目了。
I tried it this evening! Nacos's documentation is really good and written very comprehensively.
// 今天晚上试了一下啊！nacos的文档是真的好，写的非常全面。
Unlike a registry "consul", the document is really uncomfortable.
// 不像某注册中心 “consul” 那文档看的真的难受。
Very easy to use, get started in two hours. By the way! When will v0.8.0 be released? I am looking forward to it!
// 非常好用，两小时上手。顺便问一下啊！v0.8.0什么时候发布？挺期待的！

*** WE STRONGLY SUGGEST YOU TO DESCRIBE YOUR ISSUE IN ENGLISH ***

**Comment by pguo65535** [comment]
本来计划 1.15 release，现在在努力放在年前release 0.8

**Comment by hxy1991** [comment]
https://github.com/alibaba/nacos/releases/tag/0.8.0
