### ISSUE TITLE
服务器磁盘空间满了之后点击发布配置丢失

### ISSUE THREAD

**Issue by NPFDamon** [alibaba/nacos#6166]
**Describe the bug**

nacos版本2.0.1，存储方式为MySQL，在nacos服务器磁盘空间满的时候，新加配置点击发布导致页面展示异常

**Desktop (please complete the following information):**
 - OS: centOS-7.6
 - Version 2.0.1
 - Module 
 - SDK spring-cloud-alibaba-nacos

**Additional context**

**Comment by KomachiSion** [comment]
异常信息是什么？ nacos的配置中心有自我保护能力，磁盘满了，无法dump的时候会进行自杀，以保证数据一致。

**Comment by NPFDamon** [comment]
没有查看到异常信息 就只是web界面无法加载到配置信息

**Comment by KomachiSion** [comment]
那可能是web页面出错了。打开浏览器控制台，看一下错误是什么。

**Comment by NPFDamon** [comment]
现在磁盘已经被清理了 暂时无法复现了

**Comment by KomachiSion** [comment]
那信息不足无法进行判断了，如果之后再有该问题，可以打开浏览器控制台，看一下错误是什么。保留当时的信息和日志，再提issue反馈一下。 这个issue先关闭了。
