### ISSUE TITLE
Fuzzy query failure

### ISSUE THREAD

**Issue by MaybenYi** [alibaba/nacos#6168]
**Describe the bug**
A fuzzy query is used to search for a data id in the configuration list

**Expected behavior**
For example, if I input MB, I will output a match,

**Acutally behavior**
 but there will be no match

**How to Reproduce**
1. Enter the graphical interface of NACOS
2. Click Configuration Management -> Configuration List
3. Enter MB in the Data ID

![PE3(H%PV_OA 3%9AP~ C{AQ](https://user-images.githubusercontent.com/39932181/123499206-a4375f80-d667-11eb-93f8-3a9602a9cbfb.jpg)
![B6)H45`C@KFOX)U~EIU{X@W](https://user-images.githubusercontent.com/39932181/123499212-a8637d00-d667-11eb-85a4-9b26e25f4672.jpg)

**Comment by zzq1314zll** [comment]
@i will fix it@

**Comment by KomachiSion** [comment]
我记得模糊搜索要加* 在新版本中好像已经修改过提示了

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/123566575-9104cb00-d7f2-11eb-8662-d2b846838be4.png)
