### ISSUE TITLE
I want to unify Stringutil in nacos（如果把工具类统一会不会更好呢?）

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#6172]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/33930711/123512011-81cd3280-d6b7-11eb-81a8-ecaf2c6edbf2.png)
I want to unify Stringutil in nacos.

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
There are many people do this many times. but still can't unify totally.

I perfer unify all common util to `common` module, but there is much risk before the unit test finished.

If you want to unify StringUtil. Please unify to common module and write enough unit test before you do unify.

**Comment by realJackSun** [comment]
If you want to unify all the Utils, Please make sure the Unit Tests and Intergration Tests  are updated  simultaneously。

**Comment by mask616** [comment]
@zzq1314zll If you don't have time, I can try to solve it

**Comment by KomachiSion** [comment]
Finished by #3102
