### ISSUE TITLE
config data not exist

### ISSUE THREAD

**Issue by samunbest** [alibaba/nacos#6177]
**Describe the bug**
nacos-client 1.4.2 server 2.0.2 config data not exist,
the logs show request is /nacos/v1/cs/configs?dataId=x&tenant=x&group=x,
however when i change the url into /nacos/v1/cs/configs?dataId=x&namespace=x&group=x ,it works.

**Desktop (please complete the following information):**
 - OS: centos 7.6
 - Version nacos-server 2.0.2, nacos-client 1.4.2]
 - Module config
 - SDK java sdk

**Comment by KomachiSion** [comment]
maybe your tenant is error.

if you use namespace attributes, the config api will auto inject the default tenant, and find the dataid in default tenant.

when you use tenant, the tenant is error and can't find the dataid in wrong tanant, so config data not exist.

**Comment by samunbest** [comment]
> maybe your tenant is error.
> 
> if you use namespace attributes, the config api will auto inject the default tenant, and find the dataid in default tenant.
> 
> when you use tenant, the tenant is error and can't find the dataid in wrong tanant, so config data not exist.

no,i am certain i just change the query param from teanant to namespace

**Comment by samunbest** [comment]
> maybe your tenant is error.
> 
> if you use namespace attributes, the config api will auto inject the default tenant, and find the dataid in default tenant.
> 
> when you use tenant, the tenant is error and can't find the dataid in wrong tanant, so config data not exist.

yes,it is a mistake
