### ISSUE TITLE
Does nacos still support master-slave mysql?

### ISSUE THREAD

**Issue by WywTed** [alibaba/nacos#6180]
https://github.com/alibaba/nacos/issues/5461
On this issue, 
![image](https://user-images.githubusercontent.com/12699301/123575734-cd412700-d804-11eb-9f11-ec7519f4c8ef.png)
It says we can config mysql master url and slave url in the application.properties file. 
But i cant find the guide to config it.

**Comment by realJackSun** [comment]
See this
https://github.com/nacos-group/nacos-docker/blob/master/build/conf/application.properties

**Comment by WywTed** [comment]
![image](https://user-images.githubusercontent.com/12699301/124108567-e19d5200-da98-11eb-91e2-9000856cbefb.png)

It's very confused. In the configuration, 
db.url.0=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM
db.url.1=jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME}?${MYSQL_SERVICE_DB_PARAM

db.url.0 is the same with db.url.1; Is it designed like this or we can thange it to different host/port ?

**Comment by WywTed** [comment]
If it can set different host/port , the first is the master and others are slave? or others?

**Comment by KomachiSion** [comment]
1. can be different
2. you don't consider which one is master, nacos will do an insert operation to test which one is master.

**Comment by WywTed** [comment]
Thanks, i'll have a tryl.
