### ISSUE TITLE
403, unknown user

### ISSUE THREAD

**Issue by erioe-m** [alibaba/nacos#6182]
**Describe the bug**
After Nacos turns on authentication, the user name and password settings of the configuration file are invalid, and the user is still 403, unknown user,user java sdk

     Properties properties = new Properties();
        properties.setProperty("serverAddr", "10.12.112.208");
        properties.setProperty("namespace", "9fe861e4-ffc8-450f-8c9a-5c8076f8d3f5");
        properties.setProperty("username", "nacosclient");
        properties.setProperty("password", "zZHh9Wcqh2xa");

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [e.g. naming]
 - SDK [e.g. original, java]

**Comment by zzq1314zll** [comment]
I tried it and didn't find the problem you said. Please check your username and password

**Comment by realJackSun** [comment]
Please recheck the username and password

**Comment by MajorHe1** [comment]
![image](https://user-images.githubusercontent.com/53824889/123923914-08d22180-d9bc-11eb-927c-04d42ba4a49a.png)
unknown user 这个异常是这里报出来的，所以：
1.确认你的这个username 对应的 user 是否在数据库里面有记录（控制台-权限管理-用户列表）
2.如果有，那可能只是nacos-server还没有加载到数据，因为nacos-server在初始化后默认5秒钟才去load数据库里面的信息

**Comment by KomachiSion** [comment]
There is no response from author, and community can't reproduce this problem. So we think this is an usage problem.
