### ISSUE TITLE
nacos can't change the configfile context

### ISSUE THREAD

**Issue by liyin37** [alibaba/nacos#6185]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42507175/123615177-a18b6480-d837-11eb-8657-32322cbc8680.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: kylin OS arm64
 - Version：nacos-server 1.3.1
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by realJackSun** [comment]
1、Make sure the network has no problem.
2、If you use embedded storage, recheck that You have the permission {nacos_home}/data/derby-data
    If you use external storage, recheck that your mysql works correctly.

**Comment by KomachiSion** [comment]
No more information from author and current information is not enough to judge problems.

**Comment by liyin37** [comment]
@KomachiSion I use external storage, the mysql works correctly , how this happen?

**Comment by liyin37** [comment]
buy the way , I docker build the nacos image use arm64 ，use the dockerfile is in https://github.com/nacos-group/nacos-docker/blob/1.3.1/build/Dockerfile
