### ISSUE TITLE
@NacosConfigurationProperties有什么作用？怎么用？

### ISSUE THREAD

**Issue by Dayugu** [alibaba/nacos#6187]
在nacos管理的服务多数据源配置的时候，之前是要使用@ConfigurationProperties读取本地的配置文件，但是数据库链接信息放到nacos之后这个从本地获取配置信息的注解就不能使用了，请问各位大神，@NacosConfigurationProperties是不是对ConfigurationProperties的升级，它到底有什么用？怎么去用

**Comment by realJackSun** [comment]
@NacosConfigurationProperties 是Nacos根据自身数据结构，对于ConfigurationProperties的一种继承，示例：
https://github.com/nacos-group/nacos-spring-boot-project/blob/d77d02926da347bc72f900a2c95bfd8229132197/nacos-spring-boot-samples/nacos-config-sample/src/main/java/com/alibaba/boot/nacos/sample/Foo.java
