### ISSUE TITLE
Remove common-lang3 dependency 

### ISSUE THREAD

**Issue by Moskalnazar** [alibaba/nacos#6196]
我是这样想的，因为我已经替换完了嘛，然后按照以下步骤，每个步骤提交一个pr
1.  把common-lang2 的一些工具类给粘贴到nacos-common 工程中（这个还需要不需要测试?）
2. 然后下面每个工程提交一个pr
![image](https://user-images.githubusercontent.com/33930711/123582106-cec41c80-d80f-11eb-8aa8-4bfe1324414e.png)
3. 最后改pom
@KomachiSion

_Originally posted by @zzq1314zll in https://github.com/alibaba/nacos/issues/6174#issuecomment-869352274_

**Comment by realJackSun** [comment]
这个步骤是可以的，注意一下工具类到nacos-common的时候，删除冗余代码，以及保留原始的copyright,author信息，另外备注一下Nacos进行的更改。

**Comment by realJackSun** [comment]
@Moskalnazar 可以加钉钉群23335652讨论一下

**Comment by KomachiSion** [comment]
refer #3102
