### ISSUE TITLE
 Unnecessary class: com.alibaba.nacos.common.utils.Objects

### ISSUE THREAD

**Issue by SunJiFengPlus** [alibaba/nacos#6197]
## Issue Description
```com.alibaba.nacos.common.utils.Objects``` and ```java.util.Objects``` have most of the same code.

The only difference is that ```com.alibaba.nacos.common.utils.Objects::requireNonNullElse```, I did a global search and there was no other place to use it, ```Optional``` can be instead of this method. 

So I wonder if I can delete it.

if it pass, i can do this.

**Comment by KomachiSion** [comment]
I think the `com.alibaba.nacos.common.utils.Objects` is copy from jdk. Because before nacos 2.0, the nacos-client is compile with jdk1.6. `java.util.Objects` add since 1.7. So add this Util to use.

Now we can replace back to jdk's util and remove old util.
