### ISSUE TITLE
BUG nacos-common>utils>StringUtils.join method NullPointerException

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#6198]
```java
        ArrayList<Object> objects = new ArrayList<>();
        objects.add(null);
        Assert.assertNull(StringUtils.join(null, "a"));
        Assert.assertEquals(StringUtils.EMPTY, StringUtils.join(Arrays.asList(), "a"));
        Assert.assertEquals(StringUtils.EMPTY, StringUtils.join(objects, "a")); // NullPointerException
        Assert.assertEquals("a;b;c", StringUtils.join(Arrays.asList("a", "b", "c"), ";"));
        Assert.assertEquals("abc", StringUtils.join(Arrays.asList("a", "b", "c"),  null));// NullPointerException
```

**Comment by realJackSun** [comment]
目前Nacos是这样实现的：
StringUtils.join(null, "a") 返回null
StringUtils.join(Arrays.asList("a", "b", "c"),  null)的结果也是null
而StringUtils.EMPTY是“”
所以对两者直接判断的话，就肯定发生了报错。

个人建议，对于String判空的时候，使用StringUtils.isBlank(StringUtils.join(objects, "a"))

**Comment by zzq1314zll** [comment]
我描述的不够清除
1. 执行StringUtils.join(Arrays.asList("a", "b", "c"),  null) 这个操作应该返回什么，是返回"null"还是null还是"abc"还是"anullbnullc"(我想应该是"abc")
2. 执行StringUtils.join(objects, "a")这个，应该返回null 还是""(我想应该是""而不是null)
3. 如果执行StringUtils.join(objects, "a") objects 中有多个null 这段代码会抛出NullPointerException

**Comment by realJackSun** [comment]
这几种和null相关的边界情况目前似乎处理的确实不好

**Comment by realJackSun** [comment]
@zzq1314zll 我们让nacos的实现完全和commons.lang3一致

> 执行StringUtils.join(Arrays.asList("a", "b", "c"), null) 这个操作应该返回什么，是返回"null"还是null还是"abc"还是"anullbnullc"(我想应该是"abc")

这个确实应该返回"abc"

>  执行StringUtils.join(objects, "a")这个，应该返回null 还是""(我想应该是""而不是null)

这个也应该是""

或许可以用一些这样的代码，来进行转换

![image](https://user-images.githubusercontent.com/58767027/123894571-f8f11800-d990-11eb-8664-7fcd3d47a73b.png)


> 如果执行StringUtils.join(objects, "a") objects 中有多个null 这段代码会抛出NullPointerException

这个确实会报错，问题来源是join()方法里面的toString会出现异常
![image](https://user-images.githubusercontent.com/58767027/123894440-bfb8a800-d990-11eb-8fa7-4028fe17f6b2.png)

**Comment by zzq1314zll** [comment]
已经提交PR了，但是编译过程中失败了，并不是我提交代码的问题 @realJackSun
