### ISSUE TITLE
nacos2.x在docker环境下集群部署，一直自动重启

### ISSUE THREAD

**Issue by savvyray** [alibaba/nacos#6200]
Both versions of nacos2.0.0 and nacos2.0.2 were tried, unable to cluster successfully under mac and centos, the log output service is being restarted, unable to start normally, and cannot complete the election.
尝试了nacos2.0.0和nacos2.0.2两个版本，在mac和centos下都无法集群成功，日志一直输出服务在重启，无法正常启动，也无法完成选举.

**Comment by savvyray** [comment]
The reason may be that due to lack of memory, other service can not start normally, and finally, the service reported wrong and restart all the time. By increasing docker, the service in the cluster can start normally, and finally solve the problem
原因可能是由于docker环境下，内存不足导致另外的服务无法正常启动，最后导致服务报错，一直重启，通过增大docker限制内存，使集群内的服务都正常启动，最终解决问题

**Comment by realJackSun** [comment]
Thanks for sharing your fix case, we will Add this case into FAQ of nacos documentation, please copy this issue to the nacos document github repository.
https://github.com/nacos-group/nacos-group.github.io/issues

**Comment by shihap233** [comment]
نعم. من المهم تقصي الحقيقه

**Comment by MaryJaneLove4** [comment]
Důvodem může být to, že kvůli nedostatku paměti se jiná služba nemůže spustit normálně a nakonec služba nahlásila chybu a restartovala celou dobu. Zvýšením ukotvitelný panel, služba v clusteru lze spustit normálně, a konečně vyřešit problém

**Comment by Checosco57** [comment]
> Both versions of nacos2.0.0 and nacos2.0.2 were tried, unable to cluster successfully under mac and centos, the log output service is being restarted, unable to start normally, and cannot complete the e

**Comment by Checosco57** [comment]
Higjgg

**Comment by andakumar** [comment]
Nice

**Comment by Hackarking** [comment]
Follow me Thank you 😂
