### ISSUE TITLE
服务成功注册到nacos后掉线，查看服务所在机器与nacos集群的网络状态，发现CLOSE_WAIT

### ISSUE THREAD

**Issue by ZhangLaibao** [alibaba/nacos#6203]
环境：
linux版本：CentOS Linux release 7.8.2003 (Core) （业务服务和nacos服务均运行在此版本的机器上）
nacos版本：2.0.0（3节点集群）
nacos client版本：1.4.1
spring版本：Spring boot 2.3.1 / Spring Cloud Hoxton.SR8 / Spring Cloud Alibaba 2.2.5
jdk版本：1.8.0_65

业务服务启动后可以成功注册到nacos，在服务列表中可以查询到，过一段时间（约几分钟），服务健康状态转为false并被下线。
在业务服务器上执行以下命令查看业务服务端口状态，（10.6.124.194为业务服务本机IP， 10.6.124.132/3/4为nacos 集群三个示例的IP）可以看到业务服务到nacos服务的连接为CLOSE_WAIT 状态。
```
netstat -anlp|grep 8848 | grep 10.6.124.13
tcp6       1      0 10.6.124.194:40838      10.6.124.132:8848       CLOSE_WAIT  9858/java
tcp6       1      0 10.6.124.194:47264      10.6.124.134:8848       CLOSE_WAIT  9858/java
tcp6       1      0 10.6.124.194:40840      10.6.124.132:8848       CLOSE_WAIT  9858/java
tcp6       1      0 10.6.124.194:54960      10.6.124.133:8848       CLOSE_WAIT  9858/java
tcp6       1      0 10.6.124.194:54954      10.6.124.133:8848       CLOSE_WAIT  9858/java
```

**Comment by KomachiSion** [comment]
看一下服务端是不是FullGC的状态，或者有中间层比如ngnix进行了拦截。 

另外升级一下客户端试试， 升级到1.4.2再试一下。

**Comment by ZhangLaibao** [comment]
> 看一下服务端是不是FullGC的状态，或者有中间层比如ngnix进行了拦截。
> 
> 另外升级一下客户端试试， 升级到1.4.2再试一下。

已解决，skywalking-agent插件包管理混乱造成对http客户端增强逻辑出错导致。
乌龙，抱歉。
