### ISSUE TITLE
Why not make a simple annotation to automatically register with Nacos when the project start?

### ISSUE THREAD

**Issue by James-JavaBaby** [alibaba/nacos#6209]
Hello, I‘m James, After reading the official website documents,  When we use the spring project as the client of the micro-service, web need to register with Nacos manually, We must invoke interface ip:8848/nacos/v1/ns/instance?serviceName=example  to register the service. The readability of the nacos code are not very good, Why not make a simple annotation to automatically register with Nacos when the project start? Did I not find it or  not develop it?

**Comment by realJackSun** [comment]
Nacos-spring have developed automatically read, but cannot register automatically. 
James, maybe you can join nacos-group to discuss this feature and develop it.
