### ISSUE TITLE
Feature：main.js and main.css 摘要打包

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#6212]
**Is your feature request related to a problem? Please describe.**
前端的 main.js main.css 为固定的，而由于浏览器有缓存，有前端页面的升级是，而需要用户给浏览器清楚缓存才能及时获得。

---
The front-end main.js main.css is fixed, and because the browser has a cache, there is an upgrade of the front-end page, and the user needs to clear the cache for the browser to get it in time.

**Describe the solution you'd like**
是否考虑每次打包生成 一段摘要后缀，例如  main.6666.js main.777.css 然后也把 index.html 里的名字替换掉；
这样也需要考虑另一个问题是，提交 git 时需要把旧版删除即可；
望采纳

---
Do you consider generating a summary suffix every time you package, such as main.6666.js main.777.css and then replace the name in index.html;
This also needs to be considered. Another issue is that you need to delete the old version when submitting git;
Hope to adopt

**Comment by KomachiSion** [comment]
nodejs自动打包支持这个功能吗？ 如果需要手动改 我觉得会有问题。

**Comment by CherishCai** [comment]
> nodejs自动打包支持这个功能吗？ 如果需要手动改 我觉得会有问题。

我见过不少前后端分离的项目，前端可以打出摘要包，这个问题看下熟悉前端的同学能否给个准确答复。
