### ISSUE TITLE
nacos client 多个端口注册到nacos 问题

### ISSUE THREAD

**Issue by tuofenggit** [alibaba/nacos#6214]
我有一个springboot 服务，此服务开启了 http 和 https 两个端口，注册到nacos上的端口是 https端口，但是我想注册到nacos的端口是 http 对应的端口，有没有什么办法？

**Comment by MajorHe1** [comment]
nacos client 是你自己显式引入的吗，那客户端端注册的时候，registerInstance() 方法也应该是你自己调用的？调用这个方法传入的Instacne里面把端口设置为你想设置的http对应的端口不就可以了？

**Comment by tuofenggit** [comment]
> nacos 客户端自己是你显式日期吗，那客户端端注册的时候，registerInstance() 方法也应该是你自己调用的？端口不就可以了？

我是在springboot 中直接依赖jar 的， 通过bootstrap yml 文件配置nacos信息的，并没有直接调用registerInstance() 方法
