### ISSUE TITLE
ServerHttpAgent never retried if long polling failed and it will cause no available server, currentServerAddr error

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#6215]
**Describe the bug**  

This is a old story relate to `no available server, currentServerAddr ...` here is the code  

<img width="1209" alt="截屏2021-06-30 下午8 22 44" src="https://user-images.githubusercontent.com/6041166/123960496-ef43d080-d9e1-11eb-9648-ed5d85593ab5.png">

I think do-while should change if socketTimeoutException occur then it will have no chance to retry, endtime = now + timeout, if timeout then endtime also arrive and do-while break then the exception throw.

I think should make a change as below:

change  

`final long endTime = System.currentTimeMillis() + readTimeoutMs;`  

to  

  `final long endTime = System.currentTimeMillis() + (readTimeoutMs * retryTimes);`

**Comment by KomachiSion** [comment]
2.0中已经变更为grpc了 httpagent即将移除
