### ISSUE TITLE
SQL keyword naming is not uniform

### ISSUE THREAD

**Issue by mask616** [alibaba/nacos#6216]
I found that in some places the SQL keyword is lowercase, but in some places the SQL keyword is uppercase. Can I unify them?
For example: 
![image](https://user-images.githubusercontent.com/33280931/123964186-c4f41200-d9e5-11eb-9b4a-41897538a5c7.png)

![image](https://user-images.githubusercontent.com/33280931/123964283-d806e200-d9e5-11eb-932a-b5b807fb881e.png)

**Comment by realJackSun** [comment]
Welcome to unify them.
