### ISSUE TITLE
nacos client security log output too many msg when login failed

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#6219]
**Describe the bug**
nacos client security log output too many msg when login failed

**Expected behavior**
nacos client security log output useful msg when login failed

**Acutally behavior**
nacos client security log output too many msg when login failed

**Desktop (please complete the following information):**
 - Version [nacos-client 2.0.2]

**Additional context**
![image](https://user-images.githubusercontent.com/53824889/123990429-55d5e800-d9fc-11eb-99cb-da8f223b2811.png)
日志里面打印 JacksonUtils.toJson(restResult)，连整个html的页面都输出了
我认为输出有用的 code, message 和 data信息即可
奇怪的是这个问题没有稳定复现，有时候是输出 code, message, data和header 信息，有时候是html页面

**Comment by MajorHe1** [comment]
![image](https://user-images.githubusercontent.com/53824889/124087234-6631a580-da84-11eb-8a00-f87523d8ef37.png)
如图所示，出现的情况明确了：
如果是通过构造HTTP请求去访问服务发现、配置发现这一类带 Secured 注解的方法，在 AuthFilter 里面进行权限检查，验证账号密码失败的时候抛出异常，AuthFilter 执行 resp.sendError() 方法，所以客户端拿到的结果 restResult 的 message 里面包括了整个个html页面。
如果是通过构造HTTP请求去访问login这个不带 Secured 注解的方法，异常直接抛给框架层面，客户端拿到的结果就是真正想要的 code、message、data信息了

**Comment by MajorHe1** [comment]
尝试做了一下修改，不用 resp.sendError() 的方式，换成
![image](https://user-images.githubusercontent.com/53824889/124095842-a432c780-da8c-11eb-92a1-d63420c62eb8.png)
这样的话客户端就不会看到一整个html页面，只有真正有用的message信息
也不会影响控制台前端页面的信息提示
不知道这样的改法怎么样？

**Comment by MajorHe1** [comment]
> 尝试做了一下修改，不用 resp.sendError() 的方式，换成
> ![image](https://user-images.githubusercontent.com/53824889/124095842-a432c780-da8c-11eb-92a1-d63420c62eb8.png)
> 这样的话客户端就不会看到一整个html页面，只有真正有用的message信息
> 也不会影响控制台前端页面的信息提示
> 不知道这样的改法怎么样？

这个改法有问题，会在配置列表的页面点删除配置看不到鉴权失败的弹窗。
看样子为了兼容控制台的显示，这个异常信息没办法精简。

**Comment by brotherlu-xcq** [comment]
返回网页实际是我们的http在请求的时候没有指定header的`Accept`，没有指定那么我们默认返回html类型的返回。解决办法：
1.服务端，不要直接使用response，而是使用使用`@RestControllerAdvice` 配合`@ExceptionHandler`去做全局的异常拦截，返回json体。
2.客户端，请求的时候带上Header `Accept=application/json`。
这两种改动方式影响面都比较大。鉴于现在我们没有对异常做统一拦截和处理，基本都是每个模块各自为营，返回值json格式千奇百怪。趁这个机会，我建议我们可以开一个单独的feature来将web接口返回做一个统一化。
@KomachiSion @realJackSun @MajorHe1 你们觉得呢？

**Comment by MajorHe1** [comment]
> 返回网页实际是我们的http在请求的时候没有指定请求header的`Accept`，没有指定那么默认返回html类型的返回。解决办法：
> 1.服务端，不要直接使用response，而是使用使用`@RestControllerAdvice` 配合`@ExceptionHandler`去做全局的异常拦截，返回json体。
> 2.客户端，请求的时候带上Header `Accept=application/json`。
> 这两种改动方式影响面都比较大。鉴于现在我们没有对异常做统一拦截和处理，基本都是每个模块各自为营，返回值json格式千奇百怪。趁这个机会，我建议我们可以开一个单独的feature来将web接口返回做一个统一化。
> @KomachiSion @realJackSun @MajorHe1 你们觉得呢？

请问一下这套方案会只处理http接口相关的web接口对吧，grpc的接口不在这之内，不受影响？

**Comment by brotherlu-xcq** [comment]
grpc接口不会受到影响，现在是因为HTTP接口导致的问题。

**Comment by KomachiSion** [comment]
Fixed after 2.1.0
