### ISSUE TITLE
Hello: now Java is running in k8s. Please ask the question of graceful offline of Nacos. How to use curl - x to execute? thank. I think it's useful on the Internet / Nacos / V1 / NS / instance? Interface, using Nacos Version 1.2.1

### ISSUE THREAD

**Issue by zhangxuebao** [alibaba/nacos#6224]
你好：我们现在java 在k8s 里面跑着，请教下nacos 优雅下线的问题，请教这样怎么使用 curl -X 执行？ 感谢。我看网上有用 /nacos/v1/ns/instance? 接口 ，使用的nacos 版本1.2.1
Hello: now Java is running in k8s. Please ask the question of graceful offline of Nacos. How to use curl - x to execute? thank. I think it's useful on the Internet / Nacos / V1 / NS / instance? Interface, using Nacos Version 1.2.1

  
![image](https://user-images.githubusercontent.com/27907749/124079585-ea335f80-da7b-11eb-9a52-9a25e09acc73.png)

**Comment by zhangxuebao** [comment]
请教怎么将 10.2.27.183 服务优雅下线，可以通过 curl -X 的用法？Please tell me how to elegantly offline the 10.2.27.183 service by using curl - x?

**Comment by li-xiao-shuang** [comment]
> 请教怎么将 10.2.27.183 服务优雅下线，可以通过 curl -X 的用法？Please tell me how to elegantly offline the 10.2.27.183 service by using curl - x?

可以看看Runtime.exec() 或者 ProcessBuilder 能否满足你的需求

**Comment by KomachiSion** [comment]
If you ask how to use curl -X, I think you should go to search engine. No here.

If you ask how to offline your instance, please change your question discuss and re-submit issue.
