### ISSUE TITLE
nacos server log path

### ISSUE THREAD

**Issue by flmelody** [alibaba/nacos#6230]
run nacos in docker on linux,two folders created in root path
![image](https://user-images.githubusercontent.com/47545727/124089839-dd683900-da86-11eb-8140-32b0cc5520ad.png)
should be created here? and how can I disable it or change path.thanks

**Comment by realJackSun** [comment]
logs路径没有办法修改（除非改代码），nacos是可以通过环境变量${nacos.home}修改的

**Comment by KomachiSion** [comment]
What's the context in logs dir?

**Comment by flmelody** [comment]
Linux user‘s root path,out of docker container

**Comment by KomachiSion** [comment]
Maybe you mount your root path to docker container. So the docker container path will input to your root path. It should be your env problem.

**Comment by flmelody** [comment]
I didn't mount anything

**Comment by KomachiSion** [comment]
Whether you mount, the container print something in the host machine which means your env may have some config to tell docker do this behavior. It is not nacos problem. You should find out what happen for your docker container or docker core.

**Comment by flmelody** [comment]
I just call docker run --name nacos -e TZ='Asia/Shanghai' -e MODE='standalone' -p 8848:8848 -d nacos;1.4.1,when it start up,those folders not created,but when some service register to nacos,they will,I don't think there are some problems with this script.

**Comment by flmelody** [comment]
if there are some config with my env,why there aren't anything for other containers?

**Comment by KomachiSion** [comment]
You should check and search the env problem for yourself. In other words, your provided containers are the real sys and env for nacos server. Nacos server only think your containers is a dependent machine and do log print into the container path. 

For Why the log print out to container and into your linux machine, you should ask for docker community.

**Comment by flmelody** [comment]
I don't known why you say that,you hard code this
![image](https://user-images.githubusercontent.com/47545727/125391091-7592e600-e3d6-11eb-8e72-81a07e0de053.png)
and without any mentions for the variables of doc，just tell us,just do it,there are some error with your env.

**Comment by KomachiSion** [comment]
Because it just your env problem. you told me that your container log appear out to container. Does the program skip the container and directly print and write the file to the host?

**Comment by KomachiSion** [comment]
BTW, your provided code is for nacos-client, not for nacos-server, I'm still confused which side you said.

**Comment by KomachiSion** [comment]
In my opinion, whatever nacos server or nacos client, nacos just use container as real machine, and use machine disk to print logs and data.

If the logs out from container. It must be env problem and docker setting problem. The greatest possibility is the mount setting.
