### ISSUE TITLE
Incomprehensible "//TODO"

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#6231]
Hi! @KomachiSion There is a todo I can’t understand its meaning
![image](https://user-images.githubusercontent.com/33930711/124090642-9af32c00-da87-11eb-819f-04353b9816b7.png)
Do you want to define a "selector" to complete the "pageServiceName()" function?

**Comment by realJackSun** [comment]
这是一个开发中的feature，后期将会在这里加上一个使用selector筛选instance的逻辑

**Comment by KomachiSion** [comment]
#5612
