### ISSUE TITLE
Why do service names and group names exchange？

### ISSUE THREAD

**Issue by robotLJW** [alibaba/nacos#6232]
**Describe the bug**
I found out during my Nacos performance test that long connections could be disconnected, resulting in service and grouping names swapping.And the quantity is not right.

![image](https://user-images.githubusercontent.com/27326092/124091788-c1fe2d80-da88-11eb-9118-4113ffd6140f.png)

**Expected behavior**
There is no such bug, and the number of services is correct.

**Acutally behavior**
There is a bug of exchanging service name and group name, and the number of services is not right.

**How to Reproduce**
![image](https://user-images.githubusercontent.com/27326092/124092486-7c8e3000-da89-11eb-9b43-2e7fa1ab403d.png)

1. deploy [Nacos 2.0.2](https://nacos.io/zh-cn/docs/nacos2-naming-benchmark.html), **but I use a single node**
2. deploy and use microservices, [code](https://github.com/robotLJW/nacos-sdk-go-example/blob/main/discovery/main.go)

> one pod corresponds to one container for 50 processes

**deployment: ** 
![image](https://user-images.githubusercontent.com/27326092/124093360-5fa62c80-da8a-11eb-8ea5-97fcabf4d82b.png)

![image](https://user-images.githubusercontent.com/27326092/124093460-7a78a100-da8a-11eb-8a9c-4ec2ee905d5e.png)

3. See nacos/index.html

**Desktop (please complete the following information):**
 - OS: linux
 - Version nacos-server 2.0.2, nacos-sdk-go v2.0.0-Alpha.1

**Additional context**

naming-server.log
![image](https://user-images.githubusercontent.com/27326092/124094380-5073ae80-da8b-11eb-9592-4e2aab1aa533.png)

**Comment by robotLJW** [comment]
@KomachiSion

**Comment by MajorHe1** [comment]
And the quantity is not right

**Comment by robotLJW** [comment]
> And the quantity is not right
> 请问 意思是 注册的服务数量与预期计算的数量（容器副本数 * 每个进程注册的服务数）不符吗？

yes

**Comment by realJackSun** [comment]
我这边也没有遇到过，看您的描述是压测的时候出现的？那小流量的情况下会不会出现这个问题？

**Comment by robotLJW** [comment]
> 我这边也没有遇到过，看您的描述是压测的时候出现了group和serviceName反了？那小流量的情况下会不会出现这个问题？
> 
> 或者您检查一下，是不是注册请求的时候填反了？

https://github.com/robotLJW/nacos-sdk-go-example/blob/7bcb8d66d65714e94613ee5fecbb743a5274b31b/discovery/main.go#L67

**Comment by robotLJW** [comment]
Maybe it's a go SDK problem: 
https://github.com/nacos-group/nacos-sdk-go/blob/3466363959de3fec4b9deb55647801902f1ab9a1/util/common.go#L53

https://github.com/nacos-group/nacos-sdk-go/blob/3466363959de3fec4b9deb55647801902f1ab9a1/clients/naming_client/naming_grpc/connection_event_listener.go#L72

**Comment by MajorHe1** [comment]
> And the quantity is not right
> 请问 意思是 注册的服务数量与预期计算的数量（容器副本数 * 每个进程注册的服务数）不符吗？
> 我用 nacos-client 2.0.0的 java客户端进行压测的时候，也在容器副本数目和每个进程注册的服务数目达到一定的规模之后（万级），就开始出现控制台显示的注册服务数与预期数目不符的情况了。
> 不过服务名和分组名对换的情况倒没有碰到过。
> 期待一下官方解答

这个应该是容器的资源给的太少，或者是用并发的线程在注册服务，因为资源的竞争导致某些连接注册服务是失败的，而且没有重试机制。
建议可以看一下客户端的日志输出是不是有注册失败的日志，或者等到2.0.3版本发布后再看看。
