### ISSUE TITLE
Why Nacos doesn't support service instance details showing and manage by Nacos console UI?

### ISSUE THREAD

**Issue by gotoworld** [alibaba/nacos#6236]
**Is your feature request related to a problem? 
---
1、Why Nacos doesn't support service instance details showing and manage by Nacos console UI?
2、Why Nacos doesn't show instance status by Nacos console UI?

![image](https://user-images.githubusercontent.com/8605471/124122689-f71a7800-daa8-11eb-8558-f6d78aa86c53.png)

**Describe the solution you'd like**
---
3、While in Eureka, there is instance level showing and install level showing, as below snapshot showing.

![image](https://user-images.githubusercontent.com/8605471/124121421-74dd8400-daa7-11eb-9ef7-0f08807cb01d.png)

**Comment by gotoworld** [comment]
Actually , i have found nacos have instance level details API for showing and Manage.

Seems it is not big problem to implement instance level details showing and manage, So why the feature is missing?

**Comment by gotoworld** [comment]
Nacos OpenAPI showing install level info
---

![image](https://user-images.githubusercontent.com/8605471/124124183-ba4f8080-daaa-11eb-8432-a5ecc5adc79c.png)

**Comment by KomachiSion** [comment]
If you like Eureka's UI style, go ahead to do change in your fork. 

we think operation should be separated with the context show.

**Comment by gotoworld** [comment]
> If you like Eureka's UI style, go ahead to do change in your fork.
> 
> we think operation should be separated with the context show.

I think display instance level info and provide easy way to operate it is useful.
That's why i am here to learn about whether there is a plan or it's some special reason to not provide this.
