### ISSUE TITLE
java.lang.IllegalStateException: old raft protocol already stop

### ISSUE THREAD

**Issue by lovewuqiang** [alibaba/nacos#6246]
version：nacos 2.0.2
根据官方https://github.com/nacos-group/nacos-k8s/blob/master/README-CN.md 部署k8s nacos集群，mysql数据库独立使用rds；
nacos.log报错
java.lang.IllegalStateException: old raft protocol already stop
kubectl logs -f nacos-0可以看到报错
2021/07/02 00:13:43 lookup nacos-headless on 10.0.0.2:53: no such host
svc 的nacos-headless是无头服务，clusterIP是none

**Comment by KomachiSion** [comment]
1. 那个错误没有关系， 旧raft系统已经被jraft代替，为了兼容旧版本升级没有删除接口。
2. 从kebectl日志看是集群本身搭建有问题。ip或端口不正确。需要自行排查下。
