### ISSUE TITLE
服务注册有时候是上线状态，有时候又是下线状态

### ISSUE THREAD

**Issue by xiJuanZhongYuan** [alibaba/nacos#6248]
使用的是nacos 2.0版本，register-enabled 属性已经设置为true了，但是服务器启动时候，经常是下线状态，需要手动点击上线才可以，不是必线的，看了启动日志，没有任何错误日志

**Comment by KomachiSion** [comment]
两种可能：
1、 设置的不正确，注册服务的默认值还是true。
2、 这个服务曾经被下线过，然后短期内重启又注册回来， 部分元数据会保留走raft协议被持久化保留。

**Comment by xiJuanZhongYuan** [comment]
@KomachiSion  你好，谢谢你的回答
1.register-enabled 确实设置为true了
2.数据被raft协议持久化保留，如果要清空这批数据，是需要重启nacos吗？

**Comment by KomachiSion** [comment]
需要关闭nacos后删除/nacos/data/protocol目录，而且是所有节点。

**Comment by xiJuanZhongYuan** [comment]
收到了，谢谢，我还是在启动完成之后，在脚本里面手动调用一下上线的接口吧
