### ISSUE TITLE
请问大家有没有遇到过引入nacos做配置中心部署到生产环境后，启动没报错，一切正常，访问却502？

### ISSUE THREAD

**Issue by heguanming** [alibaba/nacos#6249]
请问大家有没有遇到过引入nacos做配置中心部署到生产环境后，启动没报错，一切正常，访问却502？
![image](https://user-images.githubusercontent.com/27660059/124244676-c80c1100-db51-11eb-96ab-68625b0f0ff9.png)
![image](https://user-images.githubusercontent.com/27660059/124244696-cfcbb580-db51-11eb-9c77-e2adfa151fe9.png)
![image](https://user-images.githubusercontent.com/27660059/124244784-e540df80-db51-11eb-98fc-aa52c5e3da84.png)
![image](https://user-images.githubusercontent.com/27660059/124244829-f0940b00-db51-11eb-8a08-65fee2ce5822.png)

**Comment by zzq1314zll** [comment]
@heguanming 您好，请排查生产环境的调用链路来缩小问题范围，从客户端到服务是否经过了一些代理、转发服务呢？

**Comment by KomachiSion** [comment]
部署到生产环境有问题说明其他环境没有问题，那大概率就是生产环境本身的环境问题。502是你nginx爆的错误，所以你需要查看一下是不是nginx有问题。

**Comment by heguanming** [comment]
> 部署到生产环境有问题说明其他环境没有问题，那大概率就是生产环境本身的环境问题。502是你nginx爆的错误，所以你需要查看一下是不是nginx有问题。

但是我把nacos相关代码去掉，代码复原，他又能访问了。。。。。

**Comment by heguanming** [comment]
> 部署到生产环境有问题说明其他环境没有问题，那大概率就是生产环境本身的环境问题。502是你nginx爆的错误，所以你需要查看一下是不是nginx有问题。

但是我把nacos相关代码去掉，代码复原，他又能访问了。。。。。

**Comment by lonelydog1279** [comment]
我的server在阿里云上，开了VPN也是这个问题，关掉重启就好了
