### ISSUE TITLE
What's the best way to call all service instance method in Spring Cloud using Nacos registry?

### ISSUE THREAD

**Issue by VAEAZE** [alibaba/nacos#6261]
I have four service instances,each instance have local cache.I use this code to call the method to refresh cache,but I find that each time it only call one service instance. How to change my code if I want to call all of four service instance to refresh cache?

`ResponseEntity<String> re=restTemplate.getForEntity("http://SERVICE/refreshCache",String.class);`

**Comment by KomachiSion** [comment]
Nacos client provide `getAllInstance` method to get all instance for one service.

There is no way to get all services and all instances for one method.
