### ISSUE TITLE
[question] 关于nacos数据库表的一些问题请教

### ISSUE THREAD

**Issue by weissxu** [alibaba/nacos#6264]
Nacos数据库中，config_info_aggr, config_info_beta, config_info_tag,  group_capacity这几张表当前有起来吗？
目的分别是什么呢？

**Comment by KomachiSion** [comment]
`config_info_aggr` 用于存储聚合配置
`config_info_beta` 用于存储beta灰度发布配置
`config_info_tag`  用于存储配置和配置的tag的映射关系
`group_capacity` 集群、各Group容量信息表
