### ISSUE TITLE
nacos集群环境，宕机一台后，宕机节点进入SUSPICIOUS状态后，集群其余节点的 /nacos/v1/ns/instance/beat 返回500错误

### ISSUE THREAD

**Issue by simplesimplehappy** [alibaba/nacos#6268]
"PREFER_HOST_MODE=hostname",
"version": "1.3.1",

naming-server.log 错误日志如下：
明确的错误日志：
WARN Exception while request: http://10.1.3.12:8848/nacos/v1/ns/instance/beat?app=unknown&
namespaceId=public&port=0&nofix=1&ip=10.1.3.47&serviceName=DEFAULT_GROUP%40%40consumers%3Acom.baturu.finance.api.service.supplier.se
ttlement.SupplierSettlementPurchaseBizQueryService%3A1.0.0&encoding=UTF-8&, caused: {}

**Comment by realJackSun** [comment]
10.1.3.12是宕机的那一台还是其他的几台的IP？

**Comment by simplesimplehappy** [comment]
> 10.1.3.12是宕机的那一台还是其他的几台的IP？

就是我k8s部署的nacos集群环境，宕机后，集群节点状态是SUSPICIOUS状态，应用注册请求就报500错误，看报错信息是请求到的是宕机的那个节点了

**Comment by KomachiSion** [comment]
版本太旧了，升级一下吧。 旧版本可能有bug，无法从SUSPICIOUS变为down

**Comment by KomachiSion** [comment]
No more response from author, so we think this problem has been fixed in new version.

**Comment by taeyangee** [comment]
> 版本太旧了，升级一下吧。 旧版本可能有bug，无法从SUSPICIOUS变为down

影响面是什么？我有个三节点场景
raft leader所在服务器直接强关。
raft重新选举正常。 但该原leader 始终显示为SUSPICIOUS，然后同节点的服务也始终没有被剔除

版本是 nacos 1.4
