### ISSUE TITLE
About the 'checksum' data process

### ISSUE THREAD

**Issue by SiouWang** [alibaba/nacos#6270]
Here is a question I don't understand:
version:2.0.1
The request from: other Members 'checksum' request.
The processData type: "com.alibaba.nacos.naming.iplist.*".
The process method: DistroConsistencyServiceImpl.processData(byte[] data).
This method is called by other Members. it has two "Loop", the first loop is to insert "Datum" into "DataStore". and trigger ServiceManager.onChange event. The ServiceManager can insert Service to the listener list. 
The second loop judges whether the Service exists in the listener or not. Then trigger the Service.onChange() event to update clusterMaps. 
Finally, insert "Datum" into "DataStore" again. The notes say: "Update data store if listener executed successfully", but the listener is just changing the status of Service and Instance. 
They maybe deleted or updated, so why do we need to put it again in the second loop? Because the original "Datum" is not fresh anymore.

**Comment by realJackSun** [comment]
1、 com.alibaba.nacos.naming.iplist.* is the logic in Nacosv1, Nacos v2 uses "v2.ClientData"

**Comment by SiouWang** [comment]
Thank you bro :)
Just 20min ago，I found the problems . When I am using 'ip:port/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false' to set doubleWriteEnabled to false,   'DistroLoadDataTask' does not get DistroData for the  'com.alibaba.nacos.naming.iplist.*' type . 

So, When we use the 2.0.X，we must be close the DoubleWrite(No consideration of compatibility)?

**Comment by SiouWang** [comment]
Thank you bro :)
Just 20min ago，I found the problems . When I am using 'ip:port/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false' to set doubleWriteEnabled to false,   'DistroLoadDataTask' does not get DistroData for the  'com.alibaba.nacos.naming.iplist.*' type . 

So, When we use the 2.0.X，we must be close the DoubleWrite(No consideration of compatibility)?

**Comment by KomachiSion** [comment]
DistroLoadDataTask only run when server start, not when you close double write.

2.0.X can run without close doublewrite. But there are cost double resource of system. so you should close it after the cluster upgrade to 2.0.X.

The doublewrite just for upgrading step. Should not run in a long time.
