### ISSUE TITLE
NacosWatch 影响zipkin链路追踪

### ISSUE THREAD

**Issue by suqinghzhou2019** [alibaba/nacos#6271]
NacosWatch 注入的参数taskScheduler为LazyTraceThreadPoolTaskScheduler,将会导致每半分钟向zipkin-server发送无用信息，
`[{"traceId":"2de22ad748eac957","id":"2de22ad748eac957","name":"async","timestamp":1625464726537000,"duration":311,"localEndpoint":{"serviceName":"organization","ipv4":"192.168.180.1"}}]`
**Desktop (please complete the following information):**
 - Version

> Spring Cloud Alibaba  2.1.4.RELEASE 

> Spring Cloud Greenwich.SR6

**Comment by zzq1314zll** [comment]
这个定时任务用来同步服务列表的，并不无用，如果您不想看到它的话，你可以在zipkin上把这个链路给屏蔽掉

**Comment by KomachiSion** [comment]
Please move issue to spring cloud community
