### ISSUE TITLE
server/leave: There is a loop in the interface, and there is no end condition

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#6273]
**Describe the bug**
/nacos/core/cluster/server/leave; There is a loop in the interface, and there is no end condition
NacosClusterController#leave

![image](https://user-images.githubusercontent.com/16837364/124426265-655a8580-dd9c-11eb-8d0a-df98b9f8715a.png)

**Comment by realJackSun** [comment]
I don't think it has no end condition, it just loop for every node except itself.
![image](https://user-images.githubusercontent.com/58767027/124449116-b460e480-ddb5-11eb-92b5-3e11a28f8a3b.png)

**Comment by CherishCai** [comment]
> I don't think it has no end condition, it just loop for every node except itself.
> ![image](https://user-images.githubusercontent.com/58767027/124449116-b460e480-ddb5-11eb-92b5-3e11a28f8a3b.png)

And then, other node will call this node again?

**Comment by CherishCai** [comment]
@realJackSun 
例如: A,B,C,D,E

leave A 调用到 node B

B -> C,D,E params A

And then
C -> B,D,E params A
D -> B,C,E params A
E -> B,C,D params A

递归没有终结条件

**Comment by KomachiSion** [comment]
notifyOtherMembers=false

other node will not notify again

**Comment by CherishCai** [comment]
> notifyOtherMembers=false
> 
> other node will not notify again

是的这部分是我改的，我看代码这逻辑是会有死循环。没实际尝试过调用，看起来就是会死循环

**Comment by KomachiSion** [comment]
Try to call once and see the behavior first?

**Comment by realJackSun** [comment]
More than 7 days no response, close

**Comment by wangdongyun** [comment]
这个接口在内部注释掉了
