### ISSUE TITLE
DELETE /nacos/v1/ns/instance注销实例，返回OK，但实例仍然存在

### ISSUE THREAD

**Issue by Phoebus888** [alibaba/nacos#6274]
命令:curl -X DELETE 'nacos-server:8848/nacos/v1/ns/instance?serviceName=task-center&ip=172.18.176.183&port=8499&clusterName=DEFAULT'
返回结果是ok,但是nacos实例还在注册中心
![image](https://user-images.githubusercontent.com/45359605/124432117-d18cb780-dda3-11eb-9248-917ef6c890bb.png)
![image](https://user-images.githubusercontent.com/45359605/124432181-e9fcd200-dda3-11eb-91cc-06c9c3ba8ee6.png)

**Comment by realJackSun** [comment]
版本号和部署方式是？

**Comment by Phoebus888** [comment]
> 版本号和部署方式是什么？

k8s镜像部署,版本号是1.4.2

**Comment by Phoebus888** [comment]
现在那个版本是正常的 我可以先先切换到那个正常版本中

**Comment by KomachiSion** [comment]
这个ip是不是还在发心跳，那删除时不会生效的。

**Comment by Phoebus888** [comment]
> 这个ip是不是还在发心跳，那删除时不会发生动作的。
那这个怎么解决  我发送这个请求过后如果这个实例没有下线,我在等待30秒是没有意义的,发版过程中老的pod有可能还会存在nacos注册中心中,客户端请求又有可能去请求老的pod,从而出现超时

**Comment by KomachiSion** [comment]
这个指令不是下线指令，是删除，如果心跳还在发送，会补偿回来。

可以用控制台中的下线功能先下线，然后在关闭。

或者在应用进程里调用deregister接口，这样就会删除的同时停止心跳。

**Comment by Phoebus888** [comment]
> 这个指令不是下线指令，是删除，如果继续发送，会证明回来。
> 
> 可以用先下线的下线功能，然后在关闭。
> 
> 或者在应用进程里调用deregister，这样就会出现的同时停止心跳。

k8s是随机删除某个pod的,不可能手动用下线功能进行下线,
就是你们那边能不能出一个下线的openapi,我就不使用删除的这个api了  不好用

**Comment by Phoebus888** [comment]
> 版本号和部署方式是？

k8s是随机删除某个pod的,不可能手动用下线功能进行下线,
就是你们那边能不能出一个下线的openapi,我就不使用删除的这个api了 不好用

**Comment by KomachiSion** [comment]
控制台不是有个下线按钮吗？ 那个调用的是update接口，能够下线。 下线是修改了元数据中的enabled字段，标记为false，这样客户端就查不到这个实例了。

2.0版本的时候，如果这个ip又重新启动了，可能需要再调一下接口，把enabled字段改成true。 如果k8s的调度ip变了就不需要。

**Comment by KomachiSion** [comment]
No more response from author, so community think the update api can solve problem.

**Comment by HSPCode** [comment]
1、问题描述：
（1）DELETE请求方式，/nacos/v1/ns/instance删除某个实例返回ok，但实例依然存在；
（2）同一个服务下的多个实例，停止instance-a后端一段时间，实例列表还是有instance-a；
2、nacos-discovery版本：
`        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.0.1.RELEASE</version>
        </dependency>
`
3、额外补充：
（1）列表截图：
![image](https://user-images.githubusercontent.com/47849395/127135636-01f61960-c1eb-42f9-a91b-3a2e312b5cc7.png)
（2）先下线instance-a，在调用注销实例API也无效

**Comment by wonsaign** [comment]
把源码拉下来跑一下，然后debug一下试试看？我也是发现了这个问题，但是我的实例都是ephemeral=false，然后我的Delete请求没有带上ephemeral参数，这行代码，就默认给我加了ephemeral=true，导致一直返回ok，然后删除失败
![image](https://user-images.githubusercontent.com/37646254/127139569-5052f353-b324-46eb-abb8-a60b31c556d8.png)

**Comment by moyuntiandi** [comment]
curl -X POST 'xxx.xxx.xxx.xxx:8848/nacos/v1/ns/instance?serviceName=xxx&ip=x.x.x.x&port=8106&groupName=DEFAULT_GROUP&enabled=false&namespaceId=xxxxxxxxxxxxxx'

**Comment by qikunlun** [comment]
> 把源码拉下来跑一下，然后debug一下试试看？我也是发现了这个问题，但是我的实例都是ephemeral=false，然后我的Delete请求没有带上ephemeral参数，这行代码，就默认给我加了ephemeral=true，导致一直返回ok，然后删除失败 ![image](https://user-images.githubusercontent.com/37646254/127139569-5052f353-b324-46eb-abb8-a60b31c556d8.png)

正解，需要带上：“ephemeral | boolean | 否 | 是否临时实例，的参数”，因为你创建时选择的是ephemeral=false。
