### ISSUE TITLE
ReadRequest Response WriteRequest not found class

### ISSUE THREAD

**Issue by andotorg** [alibaba/nacos#6275]
**Describe the bug**

why this is there class not found ? 
import com.alibaba.nacos.consistency.entity.ReadRequest;
import com.alibaba.nacos.consistency.entity.Response;
import com.alibaba.nacos.consistency.entity.WriteRequest;

but import jar package?

**Comment by realJackSun** [comment]
Use 'mvn clean compile ' to generate them
