### ISSUE TITLE
Add some parameters to the startup script.

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#6276]
**Describe the solution you'd like**
Em... How about adding some parameters to the startup script?
For example, port、log path、 configuration file path.

**Comment by realJackSun** [comment]
I think application.properties can already manage port, configuration.

As for Log path, I think it would be difficult to set, because it is written in xmls and code:
![image](https://user-images.githubusercontent.com/58767027/124448700-4e745d00-ddb5-11eb-8654-60a406f8aff6.png)

**Comment by zzq1314zll** [comment]
This is the case. When I use nacos, I hope to start multiple instances on one machine by specifying different ports, and the log directories are also different. Then I found that it seems that nacos is still very troublesome to deploy in this way.

**Comment by KomachiSion** [comment]
改shell脚本就可以了，在JVM参数中添加对应变量

但是我不建议修改，配置最好还是收敛在一个地方，比如application文件，这样排查问题时会方便一些。
