### ISSUE TITLE
Feature: beta api in client.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#6285]
**Is your feature request related to a problem? Please describe.**
在服务端已经有 beta 灰度等能力，是否考虑把 灰度 api 也融入到 client 提供；毕竟客户端目前的 api 只有 一把梭哈。不满足灰度的流程

**Describe the solution you'd like**
客户端提供 api 相关的接口，并提供灰度进度相关的查询。

**Comment by KomachiSion** [comment]
不考虑，这不是客户端的功能，是管控端的功能。

客户端是使用方，不应该加上运维管控能力。

**Comment by CherishCai** [comment]
客户端有一把梭哈的能力，也就是 客户端的 publishConfig 会直接所有生效

**Comment by KomachiSion** [comment]
客户端添加这个接口是给客户端发布自身需要的配置用的，如果这个配置是同一个应用都在用的，那他不适合在客户端发布。

**Comment by CherishCai** [comment]
嗯嗯，我先内部增强客户端。按照使用来说，会存在使用场景
