### ISSUE TITLE
config console optimization suggestion

### ISSUE THREAD

**Issue by martinzh717** [alibaba/nacos#6286]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when open the nacos console

**Describe the solution you'd like**
why the menu disappears when go to config details? 
why the config area too small? can you expand it adaptively?
![image](https://user-images.githubusercontent.com/25218080/124549135-525db900-de61-11eb-8125-0cf31528e7d1.png)

**Describe alternatives you've considered**
use eureka? consul?

**Additional context**
UX is bad, it should be optimized

**Comment by KomachiSion** [comment]
1. Can you describe why you want to use menu in config detail or edit page? We think remove menu can reduce the wrong operation.

2. duplicate with #6100

**Comment by KomachiSion** [comment]
No more response from author. Close issue
