### ISSUE TITLE
Nacos running issue

### ISSUE THREAD

**Issue by love-freedom777** [alibaba/nacos#6293]
## Issue Description
我在运行运行最新版本的nacos时，在网页上也登录成功了，本地的数据库也连接成功了，能够在配置管理里面新增删除内容，数据库中也会相应的变化，但在创建命名空间时，输入相应的信息，点击确定后就确定按钮变灰，一直停在那个创建的窗口，然后关闭该创建窗口发现没有能成功新增命名空间。换了一个版本的nacos也是这样，请问这是什么原因呢？？
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos为2.0.2，mysql为5.7.19，maven为3.6.3

**Comment by KomachiSion** [comment]
I can't reproduce your problem, can you provider more information?

Such as the error infor or log in nacos server, webbroser console request response infor an so on.
