### ISSUE TITLE
服务enabled设置为false后，服务重新发布，状态依旧为false

### ISSUE THREAD

**Issue by wangdafang** [alibaba/nacos#6295]
Client版本 1.2.1
Server版本2.0.2

现象：
通过Api：PUT /nacos/v1/ns/instance?serviceName=&namespaceId=&ip=&port=&enabled=&metadata=
设置服务enabled为false后，服务重新发布、注册，服务启动成功后，服务enabled仍然为false
可是之前使用1.1.4版本Server，服务发布后enable会变为true

疑问：
这一点在升级文档中并未体现出来，我们在线上迁移后，发现这个问题。
翻阅源码后，发现2.0后的版本新增了缓存，但是并未给出缓存的清除参数，或者过期时间。

尝试：
尝试过设置nacos.naming.clean.expired-metadata.expired-time，依次设置为10/5/0，可是清除缓存的时间依然不固定，最快大概30秒，长可能1分两分钟。

这个问题，麻烦帮忙解释一下并给出一个解决方案。在线等

**Comment by KomachiSion** [comment]
`nacos.naming.clean.expired-metadata.expired-time` 这个就是过期时间。
`nacos.naming.clean.expired-metadata.interval=` 可以再试着调低这个值，默认是5000.

**Comment by wangdafang** [comment]
这两个值均设置为0之后，实例也是需要3*5秒的心跳失效时间+3*5秒的过期删除时间+10秒的rpc删除时间等待时间，也是需要40秒之后才能被删除

现在这个2.0的缓存有没有禁用的开关啊，这个问题影响我们线上现在已经快20小时了。有什么解决方案么

**Comment by wangdafang** [comment]
而且客户端重新启动，带着的原信息enabled就是true的，为什么到服务端还是使用false，这本身就是个问题啊

**Comment by KomachiSion** [comment]
因为你曾经下线过啊，你有操作过下线，服务端认为他就是应该是下线状态，如果你只是网络问题导致的错误摘除呢？ 然后注册回去又上线了？ 那才是有问题。

**Comment by KomachiSion** [comment]
考虑到旧版本模式可能有大量人员使用，下个版本会进行一些重构，保证旧接口行为和以前一致，既不进行缓存和记忆。

同时新增v2版本接口，采用新模式进行覆盖。

**Comment by KomachiSion** [comment]
> 考虑到旧版本模式可能有大量人员使用，下个版本会进行一些重构，保证旧接口行为和以前一致，既不进行缓存和记忆。
> 
> 同时新增v2版本接口，采用新模式进行覆盖。

重新评估了一下，2.0版本的update接口无法区分实例是通过1.X客户端还是2.X客户端注册的，因此元数据更新很难直接覆盖原有实例。

可能无法实现类似原有版本的能力。

**Comment by KomachiSion** [comment]
只能通过遍历，并且添加保留字段`reserved.client.id` 来记录实例对应连接id的方式来实现。

**Comment by KomachiSion** [comment]
> 只能通过遍历，并且添加保留字段`reserved.client.id` 来记录实例对应连接id的方式来实现。

实现之后测试发现，nacos修改实例直接替换原有实例的方案可能会导致无法触发同步，从而导致集群数据不一致，因此确实无法实现直接替换的能力。

**Comment by KomachiSion** [comment]
看下是否能够使用策略模式来控制使用哪部分数据生效。

**Comment by ClearLove007** [comment]
我们在cicd时会去调用nacos open api摘除指定机器的流量，如果这个状态问题暂时不能解决。暂时能想到的解决方案是更改发布脚本的执行逻辑大概如下：
1.调用open api下线
2.sleep 10s
3.发布
....
10.调用open api上线

在之前1.x版本时是没有最后一步的

**Comment by CaoZhenggg** [comment]
nacos.naming.clean.expired-metadata.interval
nacos.naming.clean.expired-metadata.expired-time

这2个配置需要重启nacos，如果在openapi的请求里可以指定过期时间不是更好吗

**Comment by wingyiu** [comment]
问题已经存在
