### ISSUE TITLE
Deleted and add the same log, Nacos Web displays existed config

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#6296]
**Describe the bug**
When I delete an existed config, then add that same config again. Nacos Web will display 'the config has already existed'. Refer to pictures

![图片](https://user-images.githubusercontent.com/42354711/124687709-01ed6680-df08-11eb-9839-ea00f9f71f32.png)
![图片](https://user-images.githubusercontent.com/42354711/124687722-0c0f6500-df08-11eb-9a4b-bd31feee9284.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 2.02
 - Module config
 - SDK spring-cloud-alibaba-nacos

**Additional context**

**Comment by zarkzheng** [comment]
Did you republish your config in newconfig page?
After you have published the configuration once, the page will not jump. At this time, if you repeatedly click the publish button, there will be such a prompt.

**Comment by brotherlu-xcq** [comment]
> Did you republish your config in newconfig page?
> After you have published the configuration once, the page will not jump. At this time, if you repeatedly click the publish button, there will be such a prompt.

Yes, I reproduce it by this way. I think maybe we can jump the page to config list page after we save the config successfully.
