### ISSUE TITLE
nacos support what kind of spi plug-ins

### ISSUE THREAD

**Issue by Cczzzz** [alibaba/nacos#6297]
nacos都支持哪些spi插件啊，今天看见一个ConfigFilter的官方都没写，那么nacos都支持那些插件呢。有没有一个列表

ConfigFilter supports SPI plugins, which are supported by Nacos. ConfigFilter supports SPI plugins, which are supported by Nacos. Is there a list

**Comment by KomachiSion** [comment]
SPI插件化还在开发中，后续会逐渐开放，同时补充文档，请先等待一下。

**Comment by KomachiSion** [comment]
Refer to #5695，#5696

**Comment by Cczzzz** [comment]
> Refer to #5695，#5696

加密的spi有人在开发吗

**Comment by KomachiSion** [comment]
有 编程之夏的所有课题都有学生入选。

**Comment by KomachiSion** [comment]
refer to #6301
