### ISSUE TITLE
[Nacos Console] Cluster management search optimization 

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#6304]
![image](https://user-images.githubusercontent.com/33930711/124784933-fede8e80-df78-11eb-899a-d66e9cc210d4.png)
![image](https://user-images.githubusercontent.com/33930711/124784985-0a31ba00-df79-11eb-985f-06c06ff872cc.png)
这个地方开放出来的api如果能根据ip+端口并支持模糊查询会不会更好呢？
然后我们在nacosCtl 上也加一个这样的功能，这样是不是非常Nice
![image](https://user-images.githubusercontent.com/33930711/124785273-4e24bf00-df79-11eb-8a39-d78cf6072f66.png)

**Comment by KomachiSion** [comment]
1. 目前版本已经支持前缀匹配搜索，我感觉nacos-server的节点数本身就不多，大多数人可能就3节点5节点，不需要检索全部展示问题都不大，而且端口一般也都是一致的，真的会有按照端口来查的吗？有多少人需要模糊搜索呢？
2. nacos-ctl如果要-p 那就在ctl中加就好了，如果服务端改了， 那就需要版本感知了，不同的版本接口行为不一样，会导致有的可用有的不可用
