### ISSUE TITLE
nacos registryInstance metadata can't override

### ISSUE THREAD

**Issue by vivikcat** [alibaba/nacos#6305]
**Describe the bug**
我们目前使用springboot开发，使用nacos注册服务时，会带入一些业务的元信息，存在metadata中。
升级到2.0.2版本后，修改应用nacos元信息，却发现服务端不能生效。

**Expected behavior**
重新注册时，可以覆盖元信息。

**Acutally behavior**
重新注册元信息不能被修改。

**How to Reproduce**
code 
1、业务应用第一次启动
`
 HashMap<String, String> metadata = new HashMap<>();
metadata.put("myconfig", "aaaa");
 instance.setMetadata(metadata);
producer.registerInstance(srv, instance);
`
2、业务变更，并修改配置
·
 HashMap<String, String> metadata = new HashMap<>();
metadata.put("myconfig", "bbbb");
 instance.setMetadata(metadata);
producer.registerInstance(srv, instance);
·

**Comment by KomachiSion** [comment]
是否有在控制台上进行过元数据操作或者上下线操作？

**Comment by vivikcat** [comment]
> 是否有在控制台上进行过元数据操作或者上下线操作？

没有通过控制台操作，我们的应用程序重启速度比较快，大概在30秒以内。

**Comment by KomachiSion** [comment]
是否有调用过update的接口更新过元数据。 我测试如果没有控制台操作过或者调用过update openAPI。 重新注册的时候会覆盖metadata。

**Comment by vivikcat** [comment]
> 是否有调用过update的接口更新过元数据。 我测试如果没有控制台操作过或者调用过update openAPI。 重新注册的时候会覆盖metadata。
确实有通过openapi调用过，规则优先级是：控制台或openapi  > registryinstance；
