### ISSUE TITLE
why nacos config need to add bootstrap.properties to config,not use springboot default application.properties?

### ISSUE THREAD

**Issue by AndyT0** [alibaba/nacos#6306]
I use nacos as config center, find that, need to add bootstrap.properties to config, Why not apply the SpringBoot default configuration application.properties? This compatibility process is so cumbersome。

**Comment by KomachiSion** [comment]
This is Spring Cloud design, I don't know how to tell you. Maybe you can move this issue to spring cloud community to ask.
