### ISSUE TITLE
switch the cluster mode and the standalone mode,configuration file missing

### ISSUE THREAD

**Issue by shy-stone** [alibaba/nacos#6309]
## Issue Description
Hello everyone,
At the moment, I set up Nacos on a single server, and configured MySQL information in the application.properties file. Then I started the service using **startup.sh**. After uploading the service configuration file, I started the service and found that there were problems with the service.So I start it with standalone mode, use startup.sh-m standalone, then the previous configuration is gone! please help me  whats happended?
Type: *bug report* 
The nacos version is 1.4.0
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
1. your standalone config problem cause standalone use derby db and your cluster use mysql. so configuration miss.
2. your cluster config problem, use error mysql or use derby db.
3. your db config has been truncate.

You can try to check these problem.

**Comment by shy-stone** [comment]
When I switch the boot mode, I don't change the configuration file(application.properties),I  just switch startup.sh into startup.sh -m standalone,but only one nacos server.
this is db config
![image](https://user-images.githubusercontent.com/46125480/124886808-2da34600-e007-11eb-9f1f-ebc6cecd51d4.png)

**Comment by shy-stone** [comment]
When I start in cluster mode and start with stand-alone mode, there is only one NAOCS server

**Comment by KomachiSion** [comment]
`spring.dartasource.platform=mysql`

This line you comment, so the problem happened.

**Comment by shy-stone** [comment]
Thanks so much. I got it
