### ISSUE TITLE
If nacos start with No DataSource set, it will not auto restart.

### ISSUE THREAD

**Issue by zqr95518** [alibaba/nacos#6318]
**Describe the bug**
当nacos和nacos对应的mysql同时启动的时候，有时nacos会比mysql先启动成功，这时候会报错No DataSource set，并不会自动重启。
When the mysql corresponding to nacos and nacos are started at the same time, sometimes nacos will start successfully before mysql. At this time, it will prompt No DataSource set and will not restart automatically.

**Expected behavior**
报错并自动重启。
Report an error and restart automatically.

**Acutally behavior**
让mysql后与nacos启动。
Let mysql start after nacos.

**How to Reproduce**
1. 启动nacos
2. 启动附属的mysql
3. nacos报错并不会重启

1. Start nacos
2. Start the attached mysql
3. Nacos reports an error and will not restart

**Desktop (please complete the following information):**
nacos-server:2.0.1
mysql:8.0.16

**Comment by realJackSun** [comment]
You use Docker to start nacos and MySQL? Recommend to use Docker-compose, can define the starting order.

**Comment by KomachiSion** [comment]
Of course, Nacos config and auth depend database. If no database ready, config data can't dump and ready to provide server. failure for starting is expected behavior.

**Comment by zqr95518** [comment]
我可以理解他会启动失败，但是不理解失败以后为什么不会自动退出，而是保持卡住的状态。
I can understand that it will fail to start, but I don't understand why it will not automatically exit after failure, but will remain stuck.

**Comment by KomachiSion** [comment]
I think it is to allow the naming module to continue to work, but naming and config run in same process so that it is hard to judge whether should go ahead to open port.

We can discuss in this issue with more community’s member to find out the solution that whether shutdown after datasource load failed.

**Comment by realJackSun** [comment]
正常的状态应该是：配置模块由于加载数据库失败而无法启动，应该只卡住配置模块的启动，而不应该影响服务模块的启动。
不过这个Nacos社区后续会通过插件化，实现配置和服务两者的解耦。

**Comment by KomachiSion** [comment]
There is no more response from community. Close first
