### ISSUE TITLE
server check fail, please check server 127.0.0.1 ,port 9848 is available

### ISSUE THREAD

**Issue by smile0821** [alibaba/nacos#6326]
I start in nacos2.0.2, nacos server running fine,but when I run nacos client,it can be register success,but have error log "server check fail, please check server 127.0.0.1 ,port 9848 is available",I find there are three times to retry connect to 127.0.0.1 9848,I want to know what 9848 port for? and why client can register successfully when 9848 port fail to connect
looking forward to reply,thx

**Comment by realJackSun** [comment]
9848 is used for gRPC communication.
See https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by mifashion** [comment]
能否提供下解决方案呢
