### ISSUE TITLE
Do we have a plan to adapt the nacos 2.0.x to the latest spring cloud?

### ISSUE THREAD

**Issue by longzhihun** [alibaba/nacos#6333]
I have checked the version mapping in the repo, didn't find the nacos 2.0.x version in the mapping, so do we have a plan to adapt it in spring cloud?

**Comment by realJackSun** [comment]
Nacos 2.0.x has release for a long time, it is stable and fast now, I think it would be good to let Spring-cloud to adapt nacos 2.x.
You can also make an issue in Spring-cloud community, ask wether they plan to change to nacos2.x.

**Comment by KomachiSion** [comment]
It is an issue for Spring cloud community not nacos.
When Spring cloud community upgrade to 2.X depend on Spring cloud community, not nacos community.

**Comment by longzhihun** [comment]
Got, thanks.
