### ISSUE TITLE
Authentication of permissions

### ISSUE THREAD

**Issue by tian-qingzhao** [alibaba/nacos#6337]
**Describe the bug**
Set open permission, console prompts permission access failure, encountered before, passed a period of time is good, this clear cache is not good.Version 2.0.0.
![QQ截图20210713092551](https://user-images.githubusercontent.com/57293296/125375835-55eec400-e3bc-11eb-8fd1-9accf1fd0b54.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by MajorHe1** [comment]
nacos-server在启动之后5秒钟才会去数据库里面加载用户、角色和权限信息，你看一下是不是这个问题
![image](https://user-images.githubusercontent.com/53824889/125379431-15df0f80-e3c3-11eb-83ee-1efa308165fd.png)

**Comment by tian-qingzhao** [comment]
我等了得有好几分钟都不行，换浏览器也不行

**Comment by MajorHe1** [comment]
> 我等了得有好几分钟都不行，换浏览器也不行

是一直不行还是过一会儿就好了
看一下数据库里面你的nacos用户是否对public命名空间有权限（虽然默认都有）

**Comment by tian-qingzhao** [comment]
之前没有权限表，加了一张权限表好了，感谢提示。
