### ISSUE TITLE
请问大佬们，哪里能找到nacos静态资源：js，css的cdn啊，我用的1M带宽的云服务器，要加载2分钟。。

### ISSUE THREAD

**Issue by larva2333** [alibaba/nacos#6338]

**Comment by KomachiSion** [comment]
最新版本main.js 1.4MB 1M带宽估计也就下载10s左右 不会超过20s。
如果你需要用cdn提速，需要你自行上传js和css到你自己的cdn上，同时还需要改动console的代码来导入加载cdn中的js和css。
