### ISSUE TITLE
dubbo provider service register nacos with 3 instance, but only 2 instance called by.

### ISSUE THREAD

**Issue by IssacYoung2013** [alibaba/nacos#6343]
The duubo service proivder register nacos with three instance successfully. But only two instance was called by consumer. When I make the un-called instance offline and online, then all three instance can be called by dubbo consumer.

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 1.3.2]
 - SDK [nacos-client, dubbo-spring-boot-starter]

**Comment by KomachiSion** [comment]
Please check in console whether has three providers for service, and check the consumer logs in {user.home}/logs/nacos/naming.log whether consumer get 3 ips for providers.

If so, it is no nacos' problem.
