### ISSUE TITLE
derby支持分页删除吗？



### ISSUE THREAD

**Issue by hieastz** [alibaba/nacos#6347]
在使用Derby的过程中，每隔10分钟会有一个这样的SQL执行，这个SQL会报错。  

syntax error: encountered 'OFFSET' at line，column 52。

delete from his_config_info where gmt_modified < ? OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY

好像不支持分页删除啊。

PersistService的removeConfigHistory实现方法

**Comment by brotherlu-xcq** [comment]
查了一圈资料，我本地也试了一下，应该是不支持的。看注释，当时这里分页删除目的是为了不报错。
![image](https://user-images.githubusercontent.com/25661357/128289147-86a69c20-4e22-4cbb-8e63-216299fbf7db.png)
我觉得可以有两个方案解决这个问题：
1.把Derby的分页删除逻辑去掉。
2.调整删除语句为: `delete from his_config_info where id in ( select id from his_config_info where gmt_modified < ? OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY);`
按照作者当时的思路，我觉得可以取第二种解决方案。
