### ISSUE TITLE
nacos1.x 配置监听，为什么要服务端延迟29.5秒而不是客户端延迟29.5秒呢？

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#6350]
我们目前有2000多微服务在使用nacos做配置中心以及服务发现，client 端每天都会上报十多次：no available server, currentServerAddr : 异常，这个问题我在前面有反馈，重试机制有问题，其实第一次超时即超时，不可能有第二次重试。
最近发现配置监听也有问题，server 会延迟29.5秒返回，这能保证配置变更后，尽快返回，即配置变更后，一次请求就能返回，增大了配置变更获取到的几率，但也使 server 内存暴涨。为何不client 端延迟15秒再次获取呢？

<img width="1130" alt="截屏2021-07-14 上午11 07 42" src="https://user-images.githubusercontent.com/6041166/125555655-50b2642c-3ba6-4c21-af95-e1a9a51de82c.png">
这里 client 端一旦长轮询结束，就又立刻马上长轮询，当微服务数量有限时，这或许很不错，在我个人压测中，当有数百个微服务时，内存就会暴涨，这块是否可以改为：client 端间隔轮询，server端立刻返回？

**Comment by KomachiSion** [comment]
长轮询需要在服务端测有变化时立刻返回response，所以是在服务端持有29.5s。 如果是客户端等待29.5s。 那期间不能最快的感知到变化。

**Comment by ijustyce** [comment]
> 长轮询需要在服务端测有变化时立刻返回response，所以是在服务端持有29.5s。 如果是客户端等待29.5s。 那期间不能最快的感知到变化。

我之前理解有误，server 并不会总是等待29.5秒再返回，确切说是server最迟29.5秒后返回，等待期间如果配置变化了，则立刻返回。

但是我同样有一个疑问，线上环境，其实很少会改动配置，即使作为配置中心，似乎也对及时性要求不高，这种优化的确很适合频繁配置变更的场景，能做到真正的监听配置变更，能确保变更后最快获取到，但也加重了系统负担，能否给个选项，选项打开后，客户端每隔一定时间，获取一次配置，服务端也直接返回，类似心跳的设计，服务端返回一个延迟的时间，客户端根据服务端的返回sleep指定时间，然后继续获取，这对很少变更配置的场景很有用。

**Comment by KomachiSion** [comment]
可以选择升级2.0，长连接之后就不再使用长轮询了。
