### ISSUE TITLE
[ERROR][check-update] get changed dataId error, code: 408

### ISSUE THREAD

**Issue by xaoyur** [alibaba/nacos#6353]
**Describe the bug**
 error日志信息:
[com.alibaba.nacos.client.Worker.longPolling.fixed-1xx.xx.xx.xx_28888-ca5a5303-fdbc-47f2-baa3-82bca612e7d9][com.alibaba.nacos.client.config.impl.ClientWorker][[fixed-1xx.xx.xx.xx_28888-ca5a5303-fdbc-47f2-baa3-82bca612e7d9] [check-update] get changed dataId error, code: 408]

MAVEN依赖信息:
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.1.0.RELEASE</version>
</dependency>

nacos-server版本:
[nacos-server-2.0.2.zip]

**Expected behavior**
项目上一直打印这个error日志, 该如何解决这个问题.
各位大佬帮帮忙~~ 感谢感谢~

**Comment by realJackSun** [comment]
有更完整的日志吗？比如config-server.log中有没有更详细的信息？

**Comment by xaoyur** [comment]
大佬您好，问题我大概已经定位到了，但是没搞清楚原因， 还麻烦帮忙分析下。
出现的原因：是因为我本机启动了代理工具“DevSidecar”。然后执行到这段代码就是返回的rest.code就是408,
`                HttpResult result = this.agent.httpPost("/v1/cs/configs/listener", headers, params, this.agent.getEncode(), this.timeout);
`
能否帮忙分析下原因，感谢~

**Comment by xaoyur** [comment]
> 有更完整的日志吗？比如config-server.log中有没有更详细的信息？

大佬您好，问题我大概已经定位到了，但是没搞清楚原因， 还麻烦帮忙分析下。
出现的原因：是因为我本机启动了代理工具“DevSidecar”。然后执行到这段代码就是返回的rest.code就是408,
HttpResult result = this.agent.httpPost("/v1/cs/configs/listener", headers, params, this.agent.getEncode(), this.timeout);
能否帮忙分析下原因，感谢~

**Comment by KomachiSion** [comment]
可能是代理改变了http请求的内容，需要您自行抓包对比一下。

**Comment by xaoyur** [comment]
好的谢谢
