### ISSUE TITLE
Variable declared but not used

### ISSUE THREAD

**Issue by SiouWang** [alibaba/nacos#6355]
Version: 2.0.1

When an ephemeral client registers, a ClientBeatCheckTaskV2 will be created by IpPortBasedClient's constructor, and scheduled by "HealthCheckReactor.scheduleCheck(BeatCheckTask task)". 

In scheduleCheck(BeatCheckTask task) method, declared a new variable named "wrapperTask", but the "wrapperTask" is not used. 

Why create  "wrapperTask" ?

当注册一个临时服务的时候，会创建对应的Client(IpPortBasedClient)，它的构造方法内创建了ClientBeatCheckTaskV2，并使用HealthCheckReactor进行调用，HealthCheckReactor.scheduleCheck(BeatCheckTask task)方法内创建了一个wrapperTask，真正执行线程的时候传入的还是入参的task，为什么要创建一个wrapperTask？

HealthCheckReactor.scheduleCheck(BeatCheckTask task)
  public static void scheduleCheck(BeatCheckTask task) {
        Runnable wrapperTask = task instanceof NacosHealthCheckTask ? new HealthCheckTaskInterceptWrapper((NacosHealthCheckTask) task) : task;
        futureMap.computeIfAbsent(task.taskKey(),  k -> GlobalExecutor.scheduleNamingHealth(task, 5000, 5000, TimeUnit.MILLISECONDS));
    }

**Comment by realJackSun** [comment]
Good Question. 我认为这个wrapper是方便未来的扩展，未来希望在每次心跳的时候执行一些别的任务（比如对于每次心跳检查时添加对于数据来源的鉴别；只不过当前还没有加进去）。
![image](https://user-images.githubusercontent.com/58767027/125735983-ecb37da7-9095-4808-be0f-4bee0cd47635.png)

**Comment by SiouWang** [comment]
非常感谢，经过你的解释明白了。
