### ISSUE TITLE
CP mode in cluster environment bug (集群环境下CP模式问题)

### ISSUE THREAD

**Issue by AI96** [alibaba/nacos#6361]
Nacos service version 1.4.1, starter version 2.2.5
In cluster environment, CP is used. Micro service configuration ephemeral: false.
Failed to start microservice:
com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:1111]) tried: ErrCode:500, ErrMsg:caused: Raft put failed, key:com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@mall-goods, value:{"instanceList":[{"instanceId":"172.16.1.97#18081#DEFAULT#DEFAULT_GROUP@@mall-goods","ip":"172.16.1.97","port":18081,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":false,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@mall-goods","metadata":{"preserved.register.source":"SPRING_CLOUD"},"lastBeat":1626331902096,"marked":false,"app":"unknown","instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000,"instanceHeartBeatInterval":5000}]}

nacos服务版本1.4.1, starter版本2.2.5
集群环境下,使用CP。微服务配置ephemeral: false。
启动微服务失败：com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:1111]) tried: ErrCode:500, ErrMsg:caused: Raft put failed, key:com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@mall-goods, value:{"instanceList":[{"instanceId":"172.16.1.97#18081#DEFAULT#DEFAULT_GROUP@@mall-goods","ip":"172.16.1.97","port":18081,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":false,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@mall-goods","metadata":{"preserved.register.source":"SPRING_CLOUD"},"lastBeat":1626331902096,"marked":false,"app":"unknown","instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000,"instanceHeartBeatInterval":5000}]};

**Comment by realJackSun** [comment]
Raft协议出现问题，怀疑是有上次的集群信息启动的残留。把{nacos_home}/data/protocol删除，然后重启一下nacos试试

**Comment by AI96** [comment]
不行哦
