### ISSUE TITLE
加载spring.main.xxx不生效

### ISSUE THREAD

**Issue by RookieOfCoder** [alibaba/nacos#6362]
在nacos配置中心使用spring.main.allow-bean-definition-overriding=true配置不生效，还是必须在bootstrap.yml里面配置。

**Comment by zzq1314zll** [comment]
@RookieOfCoder 不明白您表达的意思，`spring.main.allow-bean-definition-overriding=true` 和 nacos 配置中心没有关系吧

**Comment by zarkzheng** [comment]
You can find the answer in spring-projects/spring-boot#15037.
