### ISSUE TITLE
config file delete problems

### ISSUE THREAD

**Issue by liuchunlincom** [alibaba/nacos#6363]
**Describe the bug**
删除配置文件，页面显示正常（被删除）
![image](https://user-images.githubusercontent.com/24267789/125747315-ff6e7441-4664-4935-b10f-edf45a944840.png)
但是通过API接口 (nacos/v1/cs/configs?dataId=pgis-zf-analysis-4.yaml&tenant=fe2b8187-cab2-41c1-ad41-e70423ee0039&group=PGIS_GROUP)仍然可以查询到配置文件
![image](https://user-images.githubusercontent.com/24267789/125748329-c398e831-d8d5-46bd-accc-264db5aa6f2d.png)

**Expected behavior**
被删除的配置文件可以通过API接口（ nacos/v1/cs/configs?dataId=pgis-zf-analysis-4.yaml&tenant=fe2b8187-cab2-41c1-ad41-e70423ee0039&group=PGIS_GROUP）查询到

**Acutally behavior**
被删除的接口不应通过API接口（ nacos/v1/cs/configs?dataId=pgis-zf-analysis-4.yaml&tenant=fe2b8187-cab2-41c1-ad41-e70423ee0039&group=PGIS_GROUP）查询到

**How to Reproduce**
1. 创建配置文件
2. 删除配置文件
3. 通过页面查看文件是否被删除
4. 确认页面中文件已经被删除后，通过API查询被删除的配置文件

**Comment by realJackSun** [comment]
config-server.log中有删除的记录么？

**Comment by liuchunlincom** [comment]
重新试了一遍，没有删除记录日志
![image](https://user-images.githubusercontent.com/24267789/130041019-30a17c79-192b-4c97-9ff7-f39e8499d250.png)
