### ISSUE TITLE
Do we have a guideline of migrating from spring cloud config to nacos config? 

### ISSUE THREAD

**Issue by longzhihun** [alibaba/nacos#6371]
Currently we want to use nacos config to replace spring cloud config, bu we have too many configurations in git which need to be reconfig in nacos, so do we have any guideline fo the data migration from spring cloud config to nacos config?

**Comment by realJackSun** [comment]
Nacos has a spring-cloud usage guideline. 
https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html
But if you have Nacos usage problem, you should refer to the nacos deployment documents.
