### ISSUE TITLE
设计问题 ControllerMethodsCache

### ISSUE THREAD

**Issue by 18678224309** [alibaba/nacos#6372]
为什么这个类的 方法初始化调用要放在ConsoleConfig中？ 这两个类有什么直接的关联吗？ 通过Spring生命周期回调的方式来进行方法调用会不会更好?

**Comment by KomachiSion** [comment]
1. ControllerMethodsCache会被AuthFilter等http filter使用，用于找到uri对应的java method。放在ConsoleConfig中是因为Console能够获取到所有的uri，避免依赖问题。
2. Spring生命周期回调或许可以满足，需要调研。
3. 最好的方法可能是拿到Spring mvc的uri和method的mapping，当初这个部分的作者可能没有想到去spring中获取或者发现不容易获取才自己添加了一个。
