### ISSUE TITLE
【v2.0.2】nacos client启动失败  io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x 

### ISSUE THREAD

**Issue by orange4573** [alibaba/nacos#6373]
nacos-server 为2.0.2版本，nacos-client也是2.0.2版本
client启动报错：Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
server nacos.log 报错：io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /nacos/v1/auth/users/login?username=nacos
问一下，2.0.2版本的client必须支持http2吗，需要在自己实现转换http2吗，期待回复

**Comment by KomachiSion** [comment]
能提供下完整的堆栈吗？

**Comment by orange4573** [comment]
问题已经解决了，是我自己的配置错误

**Comment by xifeng** [comment]
> 问题已经解决了，是我自己的配置错误

我这边遇到了相似的问题，能分享下你的解决方式？

**Comment by HappyDoyourself** [comment]
请问下怎么解决的

> 问题已经解决了，是我自己的配置错误
