### ISSUE TITLE
Java package missing in nacos-consistency

### ISSUE THREAD

**Issue by DickensTone** [alibaba/nacos#6375]
**Describe the bug**
我发现了nacos-consistency的几个java文件存在引入包丢失的问题，造成我的IDE编译报错。
There was a problem.When my IDE compile the source code, some errors occur; IDE tells me, the file can't import some  classes.

**Expected behavior**
我认为应该是有一个entity包漏提交了
I found there lost a package ‘entity’ in nacos-consistency.
Here are erior files:
com/alibaba/nacos/consistency/ConsistencyProtocol.java
com/alibaba/nacos/consistency/ProtoMessageUtil.java
com/alibaba/nacos/consistency/RequestProcessor.java

**Acutally behavior**
丢失的包如下
the mising packages are here:
`import com.alibaba.nacos.consistency.entity.ReadRequest;`

`import com.alibaba.nacos.consistency.entity.Response;`

`import com.alibaba.nacos.consistency.entity.WriteRequest;`

**How to Reproduce**
1. 克隆源码 git clone the source code
2. 编译 compile
3. 报错 errors occur

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version [nacos-2.0.2]
 - Module [nacos-consistency]
 - SDK [java 15]

**Additional context**

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/faq.html#3.19

**Comment by DickensTone** [comment]
> https://nacos.io/zh-cn/docs/faq.html#3.19

#6357 OK gays, we should search in Issues before create new one;
