### ISSUE TITLE
历史记录能否保留更多时间，建议配置成为可以自定义的时间

### ISSUE THREAD

**Issue by Shanrunan** [alibaba/nacos#6378]
在日志文件操作的历史记录中，建议能够自己配置历史记录保留的时间，目前只有30天，时间太短了

**Comment by CherishCai** [comment]
@Shanrunan  看起来就是有的，默认 30天，可以设置更久，单位是 天
![image](https://user-images.githubusercontent.com/16837364/128137671-611e1b0c-db82-43e3-b9de-00a63d966f91.png)
![image](https://user-images.githubusercontent.com/16837364/128137810-f98b818a-5c80-47f2-9cb7-81915a5ddfcc.png)
