### ISSUE TITLE
Istiod couldn’t sense the crd’s change when config a nacos mcp service

### ISSUE THREAD

**Issue by noob-noob** [alibaba/nacos#6379]
**Describe the bug**
i start istio with nacos mcp server, here is the istio’s demo.yaml
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
meshConfig:
accessLogFile: /dev/stdout
configSources:
- address: xds://10.15.4.2:18848
```
the mcp server works well, service information pass through to the cluster. but when i try to config a istio gateway, it doesn’t work. and i try to config a virtualservice ,doesn’t work either.

here is what i found . when i start istio without mcp server config, the istiod would print logs while deploy CRD like gateway.
![image](https://user-images.githubusercontent.com/18344133/126095720-99592697-4068-4eba-9356-851f45f67c85.png)

but when start istio with mcp server config, the istiod print nothing.

**Expected behavior**
crd works

**Acutally behavior**
crd not works

**How to Reproduce**

1. start nacos 2.0.2 with mcp server
2. add configSources: - address: xds://10.15.4.2:18848 to istio demo.yaml
3. start istio 1.10.2 with istioctl apply -f demo.yaml
4. apply gateway on port 80.
![image](https://user-images.githubusercontent.com/18344133/126095788-2e6cdeb3-6cbb-4623-b002-db7d74d747c5.png)

5. run 'istioctl proxy-config listener $ingress_pod_name -n istio-system' to see whether the ports is on

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]   Centos 7.5
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] nacos 2.0.2
 - Module [e.g. naming/config]  
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by lzp0412** [comment]
Can you give print log  with mcp server config?

**Comment by noob-noob** [comment]
> Can you give print log with mcp server config?

Problem solved, thanks a lot.

I want to use both k8s registry and nacos registry, so i should config both configSource address.

Here is my correct config:

```
configSources:
- address: xds://10.15.4.2:18848
- address: k8s://127.0.0.1:6443
```
