### ISSUE TITLE
(0.8-SNAPHOST) How to login

### ISSUE THREAD

**Issue by zl4881663** [alibaba/nacos#638]
I don't know the default username and password to login UI in 0.8-SNAPHOST version.

**Comment by pig4cloud** [comment]
Really concealed...
Suggested to write to the document
![image](https://user-images.githubusercontent.com/12409311/51375072-ce53d180-1b3f-11e9-972f-5a02f63dd54b.png)

**Comment by zl4881663** [comment]
> Really concealed...
> Suggested to write to the document
> ![image](https://user-images.githubusercontent.com/12409311/51375072-ce53d180-1b3f-11e9-972f-5a02f63dd54b.png)

Thank you sincerely
