### ISSUE TITLE
在登陆控制台的时候，用默认的nacos作为用户名和密码，无法登陆，说用户名密码错误

### ISSUE THREAD

**Issue by ManuRodgers** [alibaba/nacos#6382]

**Comment by KomachiSion** [comment]
Please check your init username and password is right.

the default SQL is in nacos/conf/nacos-mysql.sql.

**Comment by ManuRodgers** [comment]
![image](https://user-images.githubusercontent.com/33333844/126413775-2907972d-c370-4483-b709-e4d8ad28571c.png)

**Comment by zarkzheng** [comment]
Did you build nacos in windows and run it with `sh startup.sh`?
You got this `Algorithm HmacSHA256 not available` error because your app cannot load the Java security libs correctly (So you cannot using JDK's own encryption and decryption algorithm).

See this line in `distribution/bin/startup.sh`:
```shell
JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"
```

In windows environment, using `:` you cannot successfuly load the `${JAVA_HOME}/jre/lib/ext` dir. Change  `:` to `;` in windows; or just delete this line, so it can use JDK's default dir.

```shell
JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext;${JAVA_HOME}/lib/ext"
```

**Comment by ManuRodgers** [comment]
> Did you build nacos in windows and run it with `sh startup.sh`?
> You got this `Algorithm HmacSHA256 not available` error because your app cannot load the Java security libs correctly (So you cannot using JDK's own encryption and decryption algorithm).
> 
> See this line in `distribution/bin/startup.sh`:
> 
> ```shell
> JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"
> ```
> 
> In windows environment, using `:` you cannot successfuly load the `${JAVA_HOME}/jre/lib/ext` dir. Change `:` to `;` in windows; or just delete this line, so it can use JDK's default dir.
> 
> ```shell
> JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext;${JAVA_HOME}/lib/ext"
> ```

I am using Mac system

**Comment by zarkzheng** [comment]
> > Did you build nacos in windows and run it with `sh startup.sh`?
> > You got this `Algorithm HmacSHA256 not available` error because your app cannot load the Java security libs correctly (So you cannot using JDK's own encryption and decryption algorithm).
> > See this line in `distribution/bin/startup.sh`:
> > ```shell
> > JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In windows environment, using `:` you cannot successfuly load the `${JAVA_HOME}/jre/lib/ext` dir. Change `:` to `;` in windows; or just delete this line, so it can use JDK's default dir.
> > ```shell
> > JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext;${JAVA_HOME}/lib/ext"
> > ```
> 
> I am using Mac system

Can you check the `-Djava.ext.dirs` value in your startup command output?

**Comment by ManuRodgers** [comment]
![image](https://user-images.githubusercontent.com/33333844/126434804-bb1ae81d-6833-4e55-8e84-c432e63c27d1.png)

**Comment by zarkzheng** [comment]
I see. In version 2.0.3-SNAPSHOT that you used, they change the shell from `JAVA_OPT="${JAVA_OPT} -Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"` to `JAVA_OPT_EXT_FIX="-Djava.ext.dirs=\"${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext\""`, in order to **Fix the problem of startup error when the JAVA_HOME path contains spaces under Linux/Unix/Mac system**, see #6335.
Could you try remove the `\"` around and just change to `JAVA_OPT_EXT_FIX="-Djava.ext.dirs=${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext"` and try again? It should be work then.

**Comment by ManuRodgers** [comment]
![image](https://user-images.githubusercontent.com/33333844/126580190-fd15f87f-2401-41b2-b441-5490169fb8f4.png)
it is still not working after I removed `\"` .

**Comment by ManuRodgers** [comment]
Perhaps, I can use other versions of Nacos to avoid this issue from happening?

**Comment by zarkzheng** [comment]
But I can still see the `"` behind `-Djava.ext.dirs=` in your console output.
![image](https://user-images.githubusercontent.com/26575256/126580499-24b84374-0c83-4e0c-8fe3-07b45eb8200e.png)
You may need rebuild your project.

**Comment by KomachiSion** [comment]
Can you make sure whether #6409 can fix this problem and whether #6335 cause this problem? If can't fix this problem, please close  #6409 and submit new PR to revert #6335.

**Comment by zarkzheng** [comment]
@KomachiSion Yes, I am pretty sure #6409 can fix this problem, and i checked on both Ubuntu and Windows.
The correct output should be :
```
## CORRECT
-Djava.ext.dirs=JAVA_HOME/jre/lib/ext:JAVA_HOME/lib/ext
```
but not this one :
```
## ERROR
-Djava.ext.dirs="JAVA_HOME/jre/lib/ext:JAVA_HOME/lib/ext"
```
And based on #6335 , 6409 also can handle the  `JAVA_HOME` path which contains spaces now.

**Comment by ManuRodgers** [comment]
> But I can still see the `"` behind `-Djava.ext.dirs=` in your console output.
> ![image](https://user-images.githubusercontent.com/26575256/126580499-24b84374-0c83-4e0c-8fe3-07b45eb8200e.png)
> You may need rebuild your project.

After removing that double quote, everything works. Thank you guys for your help and patience.

**Comment by xuweiwei0819** [comment]
application.properties文件修改JAVA_HOME
export JAVA_HOME=/path_to_Java
