### ISSUE TITLE
由于GRPC启动导致Nacos无法动态刷新配置文件(Nacos cannot dynamically refresh configuration files due to GRPC boot)

### ISSUE THREAD

**Issue by HaoLi-Rainbow** [alibaba/nacos#6385]
由于GRPC启动导致Nacos无法动态刷新配置文件(Nacos cannot dynamically refresh configuration files due to GRPC boot)

版本信息(Version Information)
GRPC version: 1.14
nacos客户端: 2x
spring-boot.version: 2.1.1.RELEASE
spring-cloud.version: Greenwich.SR6
spring-cloud-alibaba.version: 2.1.1.RELEASE

所遇问题(Problems encountered):
一旦进入GRPC的start方法之后就不进入以下类, 导致无法动态刷新配置文件
Once the GRPC start method is entered, the following classes are not entered, making it impossible to dynamically refresh the configuration file
![image](https://user-images.githubusercontent.com/49888630/126114155-942a8c3a-650e-4fc4-b138-d5d5ce18175f.png)

GRPC start代码如下:

`@Slf4j
@Component
public class BaseGrpcServerRunner implements ApplicationRunner {

    @Autowired
    private QuoteWisonControlServer quoteWisonControlServer;
    @Autowired
    private GreetControlServer greetControlServer;
    @Autowired
    private ContractWisonControlServer contractWisonControlServer;
    @Autowired
    private ListNodeWisonControlServer listNodeWisonControlServer;
    @Autowired
    private ListPosWisonControlServer listPosWisonControlServer;
    @Autowired
    private OwnerSupplyBomControlServer ownerSupplyBomControlServer;
    @Autowired
    private WisonOsdControlServer wisonOsdControlServer;
    @Autowired
    private InquiriesAnnexesControlServer inquiriesAnnexesControlServer;
    @Autowired
    private QuoteSummariesControlServer quoteSummariesControlServer;
    @Autowired
    private MaterialSupplySubstituteServer materialSupplySubstituteServer;
    @Autowired
    private UpdateContractPushStatusServer updateContractPushStatusServer;

    private Server server;

    public void start(BindableService... services) throws IOException {
        //这个部分启动server
        int port = 50052;
        ServerBuilder<?> serverBuilder = ServerBuilder.forPort(port);

        for (BindableService service : services) {
            serverBuilder.addService(service);
        }

        server = serverBuilder.build().start();

        log.info("Server started, listening on " + port);
        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                log.info("*** shutting down gRPC server since JVM is shutting down ***");
                BaseGrpcServerRunner.this.stop();
                log.info("*** server shut down ***");
            }
        });
    }

    private void stop() {
        if (server != null) {
            server.shutdown();
        }
    }

    /**
     * block 一直到退出程序
     *
     * @throws InterruptedException
     */
    public void blockUntilShutdown() throws InterruptedException {
        if (server != null) {
            server.awaitTermination();
        }
    }

//    public static void main(String[] args) throws IOException, InterruptedException {
//        final BaseGrpcServerRunner server = new BaseGrpcServerRunner();
//        //启动server
//        server.start(greetControlServer);
//        //block server防止关闭
//        server.blockUntilShutdown();
//    }

    @Override
    public void run(ApplicationArguments args) throws Exception {
        final BaseGrpcServerRunner server = new BaseGrpcServerRunner();
        //启动server
        server.start(greetControlServer,
                quoteWisonControlServer,
                contractWisonControlServer,
                listNodeWisonControlServer,
                listPosWisonControlServer,
                wisonOsdControlServer,
                ownerSupplyBomControlServer,
                inquiriesAnnexesControlServer,
                materialSupplySubstituteServer,
                quoteSummariesControlServer,
                updateContractPushStatusServer);
        //block server防止关闭
        server.blockUntilShutdown();
    }
}`

**Comment by HaoLi-Rainbow** [comment]
请问如何可以 让GRPC启动也可以让nacos刷新配置呢, 望解答, 谢谢

**Comment by lpaz010** [comment]
截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！nacos-client 1.x.x是不用grpc的。

**Comment by HaoLi-Rainbow** [comment]
> 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。

用naocs-client2X会内存泄漏

**Comment by HaoLi-Rainbow** [comment]
> 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。

我GRPC是我们服务用的, 不是给nacos用的

**Comment by lpaz010** [comment]
> > 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。
> 
> 我GRPC是我们服务用的, 不是给nacos用的

起初以为是nacos-client的grpc，由此看来你的issue描述有问题吖，给大佬们信息不够是没办法解决的

**Comment by HaoLi-Rainbow** [comment]
> > > 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。
> > 
> > 
> > 我GRPC是我们服务用的, 不是给nacos用的
> 
> 起初以为是nacos-client的grpc，由此看来你的issue描述有问题吖，给大佬们信息不够是没办法解决的

仁兄所言极是, 多谢提醒

**Comment by MajorHe1** [comment]
> > 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。
> 
> 用naocs-client2X会内存泄漏

nacos-client 2.X内存泄露的场景建议开一个issue描述一下看是什么问题

你用nacos 客户端调用一下 publishConfig 方法，就能一路跟踪进入到 ClientWorker

**Comment by HaoLi-Rainbow** [comment]
没响应了吗? @realJackSun

**Comment by HaoLi-Rainbow** [comment]
加上@Async就好了, 改为异步就好了
![image](https://user-images.githubusercontent.com/49888630/126480301-a5401ec3-0dc2-465d-a421-a6ac4eeaeeac.png)

**Comment by HaoLi-Rainbow** [comment]
> > > 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。
> > 
> > 
> > 用naocs-client2X会内存泄漏
> 
> nacos-client 2.X内存泄露的场景建议开一个issue描述一下看是什么问题
> 
> 你用nacos 客户端调用一下 publishConfig 方法，就能一路跟踪进入到 ClientWorker

请问我都要提供什么呢

**Comment by MajorHe1** [comment]
> 请问我都要提供什么呢
nacos-server用什么版本，怎么部署的；
nacos-client怎么使用的，构造异常的步骤是怎么样的；
在什么样的场景下，nacos-client内存泄露了，有没有程序出现的某种现象或者日志进行辅助说明

**Comment by HaoLi-Rainbow** [comment]
> > > 截图显示是naocs-client `1.1.4`，不是`2.0.x`吧！？nacos-client 1.x.x是不用grpc的。
> > 
> > 
> > 用naocs-client2X会内存泄漏
> 
> nacos-client 2.X内存泄露的场景建议开一个issue描述一下看是什么问题
> 
> 你用nacos 客户端调用一下 publishConfig 方法，就能一路跟踪进入到 ClientWorker

https://github.com/alibaba/nacos/issues/6667 #6667
