### ISSUE TITLE
nacos 2.0.2 k8s nfs 方式部署，跑一段时间后报错

### ISSUE THREAD

**Issue by zhangwenliang012** [alibaba/nacos#6388]
![图片](https://user-images.githubusercontent.com/29650981/126117480-86d5f315-8499-44f0-af9a-887cb03c9c6a.png)
"naming_persistent_service": {
                "errMsg": "Error [type=ERROR_TYPE_STATE_MACHINE, status=Status[EBUSY<1009>: FSMCaller is overload.]]",

2.0.0 也会报错
naming_persistent_service": {
                "errMsg": "Error [type=ERROR_TYPE_META, status=Status[EIO<1014>: Fail to save raft meta, path=/home/nacos/data/protocol/raft/naming_persistent_service/meta-data]]",
                "leader": "nacos-1.nacos-headless.default.svc.cluster.local:7848",
                "raftGroupMember": [

**Comment by zhangwenliang012** [comment]
nacos-pvc-nfs.yaml
 nacos-quick-start.yaml    quick start没有这样的问题，我想了解下，共享目录比没有共享目录的方式，好在哪里？是不是quick start 就够了，也已经实现了高可用了

**Comment by realJackSun** [comment]
> Fail to save raft meta

是不是你的宿主机上容量不够导致的报错？

多nacos集群都是可以实现高可用的，和你的部署方式，是否共享目录没有直接关系。

**Comment by zhangwenliang012** [comment]
我是用的阿里云的ask，日志目录是挂载的阿里云的oss，空间没有满，三个节点挂载的一个oss，写入日志都写在同一个文件了，这样是不是有问题？

**Comment by realJackSun** [comment]
> 我是用的阿里云的ask，日志目录是挂载的阿里云的oss，空间没有满，三个节点挂载的一个oss，写入日志都写在同一个文件了，这样是不是有问题？

我认为应该不是日志目录的问题，三个节点写入同一个日志，顶多会把三份日志混在一起让人无法区分开，不会对启动造成影响。

**Comment by KomachiSion** [comment]
写的是同一个文件？那肯定有影响，raft是需要文件锁的，如果多个节点使用同一个文件，只有一个节点能写入，会导致所有raft请求都会失败。

**Comment by zhangwenliang012** [comment]
那就理解了谢谢

**Comment by hulei17** [comment]
怎么解决的呢，各位大神
