### ISSUE TITLE
这个问该如何排查，nocas-common的版本1.0.0会出现这个问题，1.1.4则不会，原因是啥？

### ISSUE THREAD

**Issue by henpangpang** [alibaba/nacos#6392]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method nacosDiscoveryHealthIndicator in com.alibaba.cloud.nacos.endpoint.NacosDiscoveryEndpointAutoConfiguration required a bean of type 'com.alibaba.cloud.nacos.NacosDiscoveryProperties' that could not be found.

Action:

Consider defining a bean of type 'com.alibaba.cloud.nacos.NacosDiscoveryProperties' in your configuration.

**Comment by KomachiSion** [comment]
版本不兼容吧。一般升级可以兼容，降级不一定。
