### ISSUE TITLE
异常处理可能让健康检查失效

### ISSUE THREAD

**Issue by guohangbk** [alibaba/nacos#6394]
![image](https://user-images.githubusercontent.com/58763031/126283322-4e9d33c0-7800-4f7d-b765-7a72011ab05a.png)

![image](https://user-images.githubusercontent.com/58763031/126283400-b9c6ee4d-a833-45e5-a772-d50aa40c1d42.png)

在NacosDiscoveryClient的getServices()中，方法在下层可能会抛出异常，但是在这里将异常捕捉以后返回了空的集合。
在DiscoveryClientHealthIndicator的 health()中就不会拿到异常，会骗过健康检查。

**Comment by KomachiSion** [comment]
Please move issue to Spring cloud alibaba community.
