### ISSUE TITLE
When one Client create 2 NamingService request the server will meet error.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#6396]
**Describe the bug**

I create 2 NamingService in the same Client, when the naming2 request the server error meeting.
![image](https://user-images.githubusercontent.com/25661357/126320976-f5873f54-4849-4cfc-9693-58c71ce13606.png)

**Expected behavior**

can also work and no error.

**Acutally behavior**

meet error.

**How to Reproduce**

see the screeshot.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.0.2, nacos-client 2.0.2]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
In My test, I create 100 NamingService and do register/query/subscribe are all ok.

So I don't think it is nacos-client problem. 
Or can you provide more information to help us find the problem.

**Comment by KomachiSion** [comment]
And from you error information, the connection is not ready yet when you call `getAllInstance`, maybe you wait a very few time it will work well.

**Comment by brotherlu-xcq** [comment]
I cleared my local limitRule data, then it can work normal. It due to my local test cache.

**Comment by brotherlu-xcq** [comment]
this issue due to the compare when register connection to ConnectionManager.
com.alibaba.nacos.core.remote.ConnectionManager#isOverLimit
```java
    /**
     * check if over limit.
     *
     * @return over limit or not.
     */
    private boolean isOverLimit() {
        return connectionLimitRule.countLimit > 0 && currentSdkClientCount() >= connectionLimitRule.getCountLimit();
    }
```
my local countLimit 1.

**Comment by InsaneLighter** [comment]
> this issue due to the compare when register connection to ConnectionManager. com.alibaba.nacos.core.remote.ConnectionManager#isOverLimit
> 
> ```java
>     /**
>      * check if over limit.
>      *
>      * @return over limit or not.
>      */
>     private boolean isOverLimit() {
>         return connectionLimitRule.countLimit > 0 && currentSdkClientCount() >= connectionLimitRule.getCountLimit();
>     }
> ```
> 
> my local countLimit 1.

now you know how the nacos server do this? just add content to this file causing client cannot startup
my local file was in the same situation as your
