### ISSUE TITLE
关于故障转移的疑问

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#6397]
分支：develop

请教下 failover 只能手动的在 failvoer 目录下创建 00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00 这个文件，然后写入 1 吗？能否自动的进行故障转移？

**Comment by realJackSun** [comment]
是的，failover是一种容灾备份，是自己手动创建写入的

**Comment by xiaoheng1** [comment]
明白了。感谢
