### ISSUE TITLE
关于故障转移文件名编码问题

### ISSUE THREAD

**Issue by xiaoheng1** [alibaba/nacos#6398]
分支：develop

摘抄自 master:

com.alibaba.nacos.api.naming.pojo.ServiceInfo#getKeyEncoded

```
public String getKeyEncoded() {
        String serviceName = getGroupedServiceName();
        try {
            serviceName = URLEncoder.encode(serviceName, "UTF-8");
        } catch (UnsupportedEncodingException e) {
            //do nothing
        }
        return getKey(serviceName, clusters);
    }
```

按我理解，clusters 应该也参与到编码中，即：先将 groupName + name + clusters 拼接，然后再统一使用 URLEncoder.encode 来编码。

另外，在 com.alibaba.nacos.client.naming.backups.FailoverReactor.FailoverFileReader#run 中

ServiceInfo dom = new ServiceInfo(file.getName()); 

这里获取到的 serviceName 是一个编码后的文件名，应该先解码。

如果确定这个需要修改的话，我来修复这个问题。

**Comment by realJackSun** [comment]
![image](https://user-images.githubusercontent.com/58767027/126414817-76bbfb02-afa8-48ce-ad72-e1807607b489.png)
> 按我理解，clusters 应该也参与到编码中，即：先将 groupName + name + clusters 拼接，然后再统一使用 URLEncoder.encode 来编码。

您看一下getKey里面，似乎是拼接了clusters的？

> 另外，在 com.alibaba.nacos.client.naming.backups.FailoverReactor.FailoverFileReader#run 中

> ServiceInfo dom = new ServiceInfo(file.getName());

> 这里获取到的 serviceName 是一个编码后的文件名，应该先解码。

“编码后”是指经过了拼接吗，不过在ServiceInfo的构造方法中似乎是有一个解拼接的过程的
![image](https://user-images.githubusercontent.com/58767027/126415117-c7457d21-f6c4-45b5-afae-10da93cf9db2.png)

**Comment by xiaoheng1** [comment]
不是，@@ 在经过 urlEncoder 后会变成 %40，如果直接用 @@ 来做分割是达不到效果的，所以，在 com.alibaba.nacos.client.naming.backups.FailoverReactor.FailoverFileReader#run 中应该先将 %40 还原成 @@，然后在使用 SerrviceInfo 中的切割方法。

还有一个问题是，getKeyEncoded 确实拼接了 clusters，但是前面一节是经过 urlEncoder 的，后面拼接的 @@clsuters 没有进过 urlEncoder，我的意见是这里是否都要统一经过 urlEncoder?

**Comment by KomachiSion** [comment]
之前运行好像一直没有问题，不仅是failover， snapshot应该也是运用的同一套机制，

encode应该是为了防止servicename中出现一些非法字符，不是为了转移@@。

**Comment by xiaoheng1** [comment]
snapshot 的这块逻辑还没看，我验证下快照包的保存和加载逻辑。
