### ISSUE TITLE
istio同步nacos服务过去后如何调用

### ISSUE THREAD

**Issue by spurtAndy** [alibaba/nacos#6405]
![image](https://user-images.githubusercontent.com/19886532/126442809-aa53f5da-0ecb-460b-8962-1a3f5adc0571.png)
上图是我同步过来的服务，但是我再另外的pod中无法通过hostname去调用。

**Comment by lzp0412** [comment]
你使用的istio版本是哪个？

**Comment by spurtAndy** [comment]
@lzp0412  我用到1.10.0

**Comment by lzp0412** [comment]
@spurtAndy ping一下或者解析下hostname看是否能解析出域名？还有就是看是否开启了istio dns劫持。

**Comment by lzp0412** [comment]
@spurtAndy ping一下或者解析下hostname看是否能解析出域名？还有就是看是否开启了istio dns劫持。
https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/

**Comment by spurtAndy** [comment]
@lzp0412 
尝试了打开以下两个开关
![image](https://user-images.githubusercontent.com/19886532/126962336-45b95f48-d616-4881-90c7-4fdbc34e136f.png)
注册信息
![image](https://user-images.githubusercontent.com/19886532/126962216-c632e5cb-5bb6-4038-bad0-8baa38268ddd.png)
中的240.240.0.2是自动生成的，我ping是可以看到已经解析到这个地址，但是服务访问不通。
![image](https://user-images.githubusercontent.com/19886532/126962559-bb5669f7-8734-402a-83c9-ba64ef21f939.png)
我不清楚是什么原因。
麻烦解答下，谢谢。

**Comment by spurtAndy** [comment]
可以了 谢谢

**Comment by siaron** [comment]
@spurtAndy 怎么实现调用的呀. 直接调用: demo3.DEFAULT_GROUP.public.nacos 吗?

**Comment by siaron** [comment]
@spurtAndy 这个同步服务信息怎么获取到的呀.

**Comment by yichouchou** [comment]
> 可以了 谢谢

您好，请问您图片上的内容是如何获取到的，看上去像是nacos的api?

**Comment by mark8s** [comment]
@spurtAndy 怎么解决的呀？

是这样？？

```
ISTIO_META_DNS_CAPTURE: "true"
# Enable automatic address allocation, optional
ISTIO_META_DNS_AUTO_ALLOCATE: "true"
```
???

**Comment by spurtAndy** [comment]
@mark8s  是的，打开智能DNS

**Comment by spurtAndy** [comment]
@yichouchou  是istiod的api  /debug/endpointz
