### ISSUE TITLE
nacos集群中的某个节点如果没有配置在clusetr.conf配置中，启动后，服务消费者有时获取不到注册在nacos的服务

### ISSUE THREAD

**Issue by Tanky-Zhang** [alibaba/nacos#6406]
近期在生产环境上我的nacos集群在启动线下测试节点的时候，由于该节点未在在clusetr.conf配置，所以当启动以后服务消费者有时获取不到注册在nacos的服务。是否可以帮忙解答。

**Comment by KomachiSion** [comment]
信息太少，只能推断是集群创建不正确导致的。

**Comment by MajorHe1** [comment]
个人猜测：由于该节点未在在clusetr.conf配置，所以你的生产环境的集群不认为线下测试节点是合法的集群成员，所以线下测试的节点上的服务数据不会同步给生产集群，所以消费者从 生产环境集群获取到的服务数据 跟 线下测试节点的服务数据 不一致，就出现了你说的有时候获取不到注册的服务。

注意，这本来就不是正确的集群创建方式。

**Comment by Tanky-Zhang** [comment]
> 个人猜测：由于该节点未在在clusetr.conf配置，所以你的生产环境的集群不认为线下测试节点是合法的集群成员，所以线下测试的节点上的服务数据不会同步给生产集群，所以消费者从 生产环境集群获取到的服务数据 跟 线下测试节点的服务数据 不一致，就出现了你说的有时候获取不到注册的服务。
> 
> 注意，这本来就不是正确的集群创建方式。
数据不会同步，但是为什么请求会打到线下那个节点呢，我是用的nginx，nginx配置的是线上的机器，并未配置线下节点，我服务的消费侧也是请求的线上的域名

**Comment by Tanky-Zhang** [comment]
> 个人猜测：由于该节点未在在clusetr.conf配置，所以你的生产环境的集群不认为线下测试节点是合法的集群成员，所以线下测试的节点上的服务数据不会同步给生产集群，所以消费者从 生产环境集群获取到的服务数据 跟 线下测试节点的服务数据 不一致，就出现了你说的有时候获取不到注册的服务。
> 
> 注意，这本来就不是正确的集群创建方式。



数据不会同步，但是为什么请求会打到线下那个节点呢，我是用的nginx，nginx配置的是线上的机器，并未配置线下节点，我服务的消费侧也是请求的线上的域名

**Comment by MajorHe1** [comment]
> > 个人猜测：由于该节点未在在clusetr.conf配置，所以你的生产环境的集群不认为线下测试节点是合法的集群成员，所以线下测试的节点上的服务数据不会同步给生产集群，所以消费者从 生产环境集群获取到的服务数据 跟 线下测试节点的服务数据 不一致，就出现了你说的有时候获取不到注册的服务。
> > 注意，这本来就不是正确的集群创建方式。
> 
> 数据不会同步，但是为什么请求会打到线下那个节点呢，我是用的nginx，nginx配置的是线上的机器，并未配置线下节点，我服务的消费侧也是请求的线上的域名

你确定会有生产环境线上的请求打到线下？那岂不是谁任意起线下节点，在cluster.conf强行加上你们生产环境的机器，就能破坏你们的生产环境了？

所以建议你还是明确一下，谁（线上客户端还是线下客户端）的什么请求（服务发现还是注册），能打到你的线下节点，并且建议提供一下现象截图或者日志说明

**Comment by KomachiSion** [comment]
1. 客户端配置问题，把请求直接打到线下了。
2. nginx配置错误，把线上线下集群放到一个域名或者转发配置下了
3. 线上cluster。conf配置错误，把线下ip也加进去了。

**Comment by KomachiSion** [comment]
No more response from author, it seems usage problem.
