### ISSUE TITLE
1.4.2 中 nacos集群的leader是另外一个nacos集群的节点，这种情况有人遇到过吗

### ISSUE THREAD

**Issue by Tanky-Zhang** [alibaba/nacos#6411]
我有两个线上nacos集群，但是有一个集群的leader节点是另外一个集群中的节点，是需要做什么配置吗，如下图：
![image](https://user-images.githubusercontent.com/48041180/126461805-9ab94928-5edb-4625-afcb-0deb3b4b5bf0.png)

**Comment by KomachiSion** [comment]
那肯定是集群创建部署有问题啊， 配置错了。

重新确认cluster.conf，然后清理nacos/data/protocol/ 重启集群再看看

**Comment by Tanky-Zhang** [comment]
> 那肯定是集群创建部署有问题啊， 配置错了。
> 
> 重新确认cluster.conf，然后清理nacos/data/protocol/ 重启集群再看看

cluster.conf确实两份不重叠的，应该没有问题：截图如下：
![image](https://user-images.githubusercontent.com/48041180/126583807-60ba34a8-c03f-4513-ae81-5a4bc4c9f1ad.png)

![image](https://user-images.githubusercontent.com/48041180/126583866-e409e261-d547-49f4-be69-332e88347f4c.png)
然后您所说的nacos/data/protocol/ 我只在一个节点上清理重启是不是不会对这个节点起作用，是不是必须对所有节点清理，因为这是线上节点，有线上流量，不太敢直接全部清理重启

**Comment by KomachiSion** [comment]
一个集群的cluster.conf不重叠就意味着问题严重

同个集群的这个配置应该要一模一样

**Comment by KomachiSion** [comment]
No more response from author, it seems cluster deploy problem.
