### ISSUE TITLE
集群模式下面启动项目访问nacos中的/nacos/v1/ns/instance报错

### ISSUE THREAD

**Issue by xigpz** [alibaba/nacos#6413]
com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.207.129:8860]) tried: ErrCode:503, ErrMsg:server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]，我试过了删除/data目录也是不行，启动方式是docker

**Comment by KomachiSion** [comment]
duplicate with #6072
