### ISSUE TITLE
nacos 作为注册中心 多套环境的问题

### ISSUE THREAD

**Issue by zhangle910522** [alibaba/nacos#6421]
请问nacos 是否支持同一套环境共用某些服务，但是个别服务是独立的这种情况吗。
比如我有一套开发环境，有A、B、C、D 四个微服务，公用开发环境都有部署，A和B这两个服务有问题，我想在本地联调，但是又不想使用namespace把整个A、B、C、D 这几个服务都启动起来（这样会很占用本地电脑资源，而且当服务很多时，本地根本没法启动这么多服务）  
是否能做到服务调用链为  A（本地启动的）--》B（本地启动的）--》C（公用开发环境的）--》D（公用开发环境的）
如果能 需要如何配置，谢谢

**Comment by KomachiSion** [comment]
部署在同一个namespace下即可
