### ISSUE TITLE
nacos集群正常运行，但是当在内网中不再集群的cluster.conf的某个单节点nacos启动后日志会有报错

### ISSUE THREAD

**Issue by Tanky-Zhang** [alibaba/nacos#6425]
问题描述：
我有一个nacos集群，具体的cluster.conf配置如下：
![image](https://user-images.githubusercontent.com/48041180/126583414-14db2f87-7ab1-4499-a730-5eaf06662e9a.png)
此时我启动另外一个ip不在这个文件中，但是同在一个内网中nacos节点的时候日志会报错，并且有时候服务消费端获取的服务实例为空

**Comment by KomachiSion** [comment]
请按照issue模版来描述，你的描述我只能认为是你集群部署错误，导致出现了2个集群，所以有报错，获取不到服务实例，因为就是2个集群。一个集群是没数据的。
