### ISSUE TITLE
spring cloud gateway nacos register discovery exception

### ISSUE THREAD

**Issue by JacksonPan123** [alibaba/nacos#6426]
description：
The nacos client was upgraded to 2.0.2 request nacos server failed, but the nacos client version 1.4.1 was fine, the error message is as follows：

![image](https://user-images.githubusercontent.com/87793735/126587121-86902cc8-ed12-4b53-8826-8cecf5eaa20a.png)
![image](https://user-images.githubusercontent.com/87793735/126587236-b75adc40-571f-4a80-b90f-4f8151295ff9.png)

config：
![image](https://user-images.githubusercontent.com/87793735/126587621-7513c95f-d7d5-4e34-b53f-d10dbbb7d125.png)
![image](https://user-images.githubusercontent.com/87793735/126587633-a139ff56-9eb0-4c57-a80e-0ae5dbbdefe8.png)

version：
spring-cloud-starter-gateway - 2.2.3.RELEASE
spring-cloud-starter-alibaba-nacos-config - 2.2.3.RELEASE
spring-cloud-starter-alibaba-nacos-discovery - 2.2.3.RELEASE
nacos-client - 2.0.2

**Comment by MajorHe1** [comment]
检查一下grpc使用的端口9848是否正常工作。
1.4.1的版本使用http访问的服务端端口是8848，
2.0.2的版本使用grpc访问的端口是9848
![image](https://user-images.githubusercontent.com/53824889/126609785-8646ee8d-83c1-4f2c-9cd8-d60679d34f33.png)

**Comment by JacksonPan123** [comment]
grpc 访问端口 9848 是能够正常使用的

**Comment by MajorHe1** [comment]
> grpc 访问端口 9848 是能够正常使用的

服务端已经升级到2.0.2版本完成了吗

**Comment by MajorHe1** [comment]
我出现类似的异常，是程序里面并发很多个线程，每个线程都试图创建namingService对象去访问服务端，然后就出现这个等待超过3000ms的问题。
考虑到你这里是个网关，检查一下代码是不是跟我碰到一样的问题
