### ISSUE TITLE
consistency module lose entity package

### ISSUE THREAD

**Issue by ChoviWu** [alibaba/nacos#6427]
rt. consistency module lose entity package, 
I guess it may be because commit did not submit the entity package.
![image](https://user-images.githubusercontent.com/19967338/126597809-aeadf2eb-4fbe-47e8-b603-d3bfee665420.png)
![image](https://user-images.githubusercontent.com/19967338/126597850-430463db-5743-4d7d-8f0c-39f23bec7cc7.png)

**Comment by shalk** [comment]
thes files will be generate when compile

**Comment by ChoviWu** [comment]
> thes files will be generate when compile

thanks, i'll looking code.
