### ISSUE TITLE
[Feature Selector] [Sub Issue] Integrate this workflow to Nacos 2.0, including all sence like Grpc, Http and add unit test.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#6430]
**Is your feature request related to a problem? Please describe.**

This issue is the sub issue of #6301. 

**Describe the solution you'd like**

Integrate this workflow to Nacos 2.0, including all sence like Grpc, Http and add unit test.

**Describe alternatives you've considered**
NO

**Additional context**
No

**Comment by mmm0171** [comment]
$ yarn build
0xa36fD8fF0524f287422337d99bABdf05923f581B

**Comment by MBANKm** [comment]
https://app.circleci.com/pipelines/github/MBANKm/mkdocs-windmill?invite=true
