### ISSUE TITLE
最新版本的 nacos 2.0.2 单独启动时，项目启动成功，集群模式启动失败。

### ISSUE THREAD

**Issue by jeceldx** [alibaba/nacos#6431]
最新版本的 nacos 2.0.2 单独启动时，项目能启动，集群启动下不能启动。
1.部署在三台内网服务器中，用单机模式启动时项目启动没问题，但是集群启动时配置中心界面无法启动即8848没有启动，7848启动了，是否还有其他需要开放的端口，在centos7中开放其他相关的服务端口以支持集群。

初次使用集群模式，烦请解答，多谢

**Comment by MajorHe1** [comment]
![image](https://user-images.githubusercontent.com/53824889/126656181-4b453693-7236-4e8e-a336-845ff1f0465f.png)
https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by jeceldx** [comment]
> ![image](https://user-images.githubusercontent.com/53824889/126656181-4b453693-7236-4e8e-a336-845ff1f0465f.png)
> https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

开放端口后查看jraft.log 报错Invalid hos or port :7848 ,并且nacos 集群日志一起提示Nacos is Starting...，请问一下有可能是什么问题

**Comment by brotherlu-xcq** [comment]
看你这个截图里的信息，这个异常里面的host是空的，你检查一下你的集群的IP和port有正确的配置呢？

**Comment by brotherlu-xcq** [comment]
集群部署文档地址：https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

**Comment by jeceldx** [comment]
> 看你这个截图里的信息，这个异常里面的host是空的，你检查一下你的集群的IP和port有正确的配置呢？

已检查，目前来看不是配置问题，其中有一台是arm服务器，集群启动时并没有报错，单机时才发现它无法启动，如果在cluster.conf中加入它后会导致配置文件中自动加入一条:8848的配置，然后我修改过server.port，就导致报出上述的错误了。。

**Comment by jeceldx** [comment]
其中一台节点以arm启动报错，导致集群通信出现上述问题，去除arm节点后服务无问题

**Comment by jeceldx** [comment]
其中一台节点以arm启动报错，导致集群通信出现上述问题，去除arm节点后服务无问题
