### ISSUE TITLE
springcloud 2020报错Param 'serviceName' is illegal, serviceName is blank

### ISSUE THREAD

**Issue by zlygit** [alibaba/nacos#6435]
配置1 
![image](https://user-images.githubusercontent.com/19401107/126727104-baf825da-1c0d-498d-8942-5ee38fbe1ab5.png)
如果配置文件是bootstrap.yml,正常，如果改成application.yml,可以正常启动 ，但是配置文件无效（即获取不到配置文件对应的配置属性值）
配置2 使用Spring Cloud 2020.0.0 
![image](https://user-images.githubusercontent.com/19401107/126727301-387b9c5f-083f-4847-8ae8-ab52fc8408a0.png)
application.yml,可以正常启动 ，但是配置文件无效 ，如果改成 bootstrap.yml
 直接运行不起来 报错
java.lang.IllegalArgumentException: Param 'serviceName' is illegal, serviceName is blank
我知道spring cloud 2020修改了加载配置方式，但是pom引入
![image](https://user-images.githubusercontent.com/19401107/126727443-fa30b8a2-431b-47f6-abf4-c9f7cfc690ba.png)
也不行，
配置文件都是一样的 ，只是改了文件名

![image](https://user-images.githubusercontent.com/19401107/126727509-0d5d873f-ea05-423c-a105-480f4c464258.png)
是不是我的配置文件有问题，还是最新的2020真的还有缺陷

**Comment by realJackSun** [comment]
先直接通过OpenAPI 来直接发布一下配置，定位一下是否有同样的问题。

**Comment by zarkzheng** [comment]
可以提供一下你的`pom.xml`文件看一下。

**Comment by KomachiSion** [comment]
建议到Spring Cloud alibaba社区问一下， 或者提供更多关于nacos的信息。

**Comment by zlygit** [comment]
![image](https://user-images.githubusercontent.com/19401107/126927830-74b63aae-5c44-49fd-a543-3c0b55d8ffa8.png)
![image](https://user-images.githubusercontent.com/19401107/126927844-c343a4aa-7e26-4578-85a1-c33c83ea6b27.png)
pom如上  配置文件也在上面的解决，这个项目是个demo，代码也是最基础的 ，项目是springboot ，现在就是不止2020的哪里配置错了

**Comment by zarkzheng** [comment]
Spring Cloud的依赖版本号应该是 `2020.0.0` 或 `Hoxton.SR9` 这种形式，没有 `Spirng Cloud 2020.0.0` 这种。你确定一下你项目里是否能正常加载到依赖。
我本地测试，使用Spring Cloud 2020.0.0和Spring Cloud Alibaba 2021.1，添加了 `spring-cloud-starter-bootstrap` 依赖是可以正常加载到 `bootstrap.yml` 里的配置的。

**Comment by zlygit** [comment]
@zarkzheng  是的 Spring Cloud的依赖版本形式写多了，按照官网的版本匹配 ，结果自己写错了，还想请教一个问题，比如使用spring cloud 2020.0版本的 配置文件一定要是bootstrap.yml吗,我改成application.yml 就不行

**Comment by zarkzheng** [comment]
是的，如果要使用远程配置中心的属性，是必须要配置`bootstrap.yml`的。issues里有相关的问题和解答，你也可以Google一下相关信息。

**Comment by zlygit** [comment]
非常感谢 进一步了解了 @zarkzheng
