### ISSUE TITLE
nacos-discovery2021.1版本中  如何集成feign与ribbon

### ISSUE THREAD

**Issue by sunset535** [alibaba/nacos#6439]
因为服务中es的版本问题，将个体服务使用了最新版的spring-cloud-starter-alibaba-nacos-discovery 2021.1版本
集成的spring-cloud-starter-netflix-ribbon与spring-cloud-starter-openfeign 为2.2.8.RELEASE版本
在feign调用时，报错如下：
![image](https://user-images.githubusercontent.com/3860179/126734859-5a5fde2b-8b00-43b4-adab-af2c8b95479c.png)

追踪问题发现2021.1版本中的已经取掉了ribbon的初始化，对比2021.1版本与2.2.1.RELEASE如下
2021.1
![image](https://user-images.githubusercontent.com/3860179/126735021-83d08d4f-1deb-4449-bceb-66df1ecabf44.png)
2.2.1.RELEASE
![image](https://user-images.githubusercontent.com/3860179/126735050-ddcf7ac6-f0a1-4e1f-852e-1c66c6c7ba38.png)
那么2021.1版本中如何集成ribbon调用

**Comment by KomachiSion** [comment]
到spring cloud alibaba中问一下吧。
