### ISSUE TITLE
naming 模块（2.0.3 版本）无法启动

### ISSUE THREAD

**Issue by xinghp** [alibaba/nacos#6442]
下载源码后未作修改，加参数-Dnacos.standalone=true 启动naming
1，报错找不到bean AuthConfigs，在入口处的scanPackages加上"com.alibaba.nacos.auth"可以了
2，但又有新的报错提示bean AuthManager 找不到
3，好不容易搜到一个issue [click](https://github.com/alibaba/nacos/issues/3042) 说要启动console模块，但是启动console又报错，详细日志在附件。
另外，源码的启动方式坑有点多，可不可以出一个简单的说明文档？

[nacos.log](https://github.com/alibaba/nacos/files/6871786/nacos.log)

**Comment by brotherlu-xcq** [comment]
看了一下你的日志，基本都是jar包找不到。你下载了源码，项目依赖都导入了还需要build一下。

**Comment by brotherlu-xcq** [comment]
可以参照CI里面的maven命令install一下项目中依赖的其他包。
https://github.com/alibaba/nacos/blob/a5cc7178fcc84e63ffa5f00110e40694e91e46ee/.github/workflows/ci.yml#L34-L35

**Comment by zarkzheng** [comment]
源码/IDE方式启动的流程为：
1. clone源码，导入IDE，build项目下载依赖或直接执行 `mvn clean install -Dmaven.test.skip=true` 下载依赖；
2. 注释掉项目根目录和 `nacos-console` 目录下两个 `pom.xml` 文件中的 `tomcat-embed-jasper` 依赖，解决 `java.io.FileNotFoundException: xxx.jar (The system cannot find the file specified)` 的问题；
3. 使用 `-Dnacos.standalone=true` VM option 启动 `console` 模块下的 `com.alibaba.nacos.Nacos`；

**Comment by KomachiSion** [comment]
推测你是直接在naming模块启动了，源码启动需要用console模块的Nacos来启动才是正确的。
