### ISSUE TITLE
2.0.0版本linux单机模式下启动报错，无法加载application.properties

### ISSUE THREAD

**Issue by formeky** [alibaba/nacos#6449]
**Describe the bug**
2.0.0版本linux单机模式下启动报错，无法加载application.properties

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by brotherlu-xcq** [comment]
报的什么错呢？详细的场景和异常堆栈可以描述的详细些吗？

**Comment by formeky** [comment]
2.0.0版本在单机环境下启动失败，无法加载application.properties配置文件，还报了UnknownHostException这个异常(我没有修改过application.properties这个配置文件)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月25日(星期天) 晚上11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 2.0.0版本linux单机模式下启动报错，无法加载application.properties (#6449)





 
报的什么错呢？详细的场景和异常堆栈可以描述的详细些吗？

**Comment by KomachiSion** [comment]
建议按照issue模版重新填写， 您这个回答方式应该没人能帮助到你。
