### ISSUE TITLE
Support for dynamically modifying the log level?

### ISSUE THREAD

**Issue by fufenghua** [alibaba/nacos#645]
支持动态修改日志级别吗

**Comment by huangyunbin** [comment]
这个想法挺好的，我这边也有对应的实现。如果觉得这个功能需要的话，我可以提交下我的实现。

**Comment by fufenghua** [comment]
> 这个想法挺好的，我这边也有对应的实现。如果觉得这个功能需要的话，我可以提交下我的实现。

是的，之前使用springcloudAdmin的时候，就可以直接动态调整日志等级，所以我觉得nacos应该也有才对

**Comment by nkorange** [comment]
@huangyunbin 可以提交一个PR

**Comment by nkorange** [comment]
将在 #882 里跟踪
