### ISSUE TITLE
单台机器上模拟集群启动 nacos server 失败

### ISSUE THREAD

**Issue by 270686992** [alibaba/nacos#6450]
**Describe the bug**
单台机器模拟集群启动nacos失败，电脑系统: macOS High Sierra 10.13.6，nacos server 版本: 1.4.2, mysql 版本: 8.0.16, 访问 nacos web 页面如下图：
![image](https://user-images.githubusercontent.com/42317058/126875627-72879d82-2831-4709-9db6-20b24bcded68.png)

但是单节点模式启动可以正常启动，如下图：
![image](https://user-images.githubusercontent.com/42317058/126875591-9f1eaada-c6b6-42be-bed6-c2ebddeab1b2.png)
![image](https://user-images.githubusercontent.com/42317058/126875609-cb0b9aed-c3f6-4727-8073-41b887755e65.png)

**Expected behavior**
预期集群方式启动成功，可以正常访问 nacos web 页面。

**Acutally behavior**
实际上集群方式启动失败，访问不了 nacos web 页面。

**How to Reproduce**
1. 配置了 cluster.conf 配置如下:
![image](https://user-images.githubusercontent.com/42317058/126875486-5f7cee4c-9a08-41e5-8da0-74ccee3f602d.png)

2. 复制多份配置相同的 nacos 文件夹:
![image](https://user-images.githubusercontent.com/42317058/126875465-efe63042-be0b-4965-873f-0c7b3f1a12e0.png)

3. 修改上面复制的 nacos 文件夹中的启动端口号配置:
![image](https://user-images.githubusercontent.com/42317058/126875466-d4c09dbf-986e-4e8b-ab78-3b38096eb793.png)
![image](https://user-images.githubusercontent.com/42317058/126875483-10473ccf-3a75-4ba1-97e1-650bfbdd8858.png)

4. 依次启动
![image](https://user-images.githubusercontent.com/42317058/126875505-7835fcb8-cb56-49ea-ae3e-f4338eeeb8ce.png)

5. 启动日志报错
![image](https://user-images.githubusercontent.com/42317058/126875516-274b5098-3170-4c93-bb90-2802376574ce.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Version nacos-server 1.4.2
 - Module /nacos/bin/startup.sh

**Additional context**
该怎么样可以正常集群启动？

**Comment by 270686992** [comment]
# 补充说明
上面启动的 3 个 nacos server 的数据源配置都是以下图中的配置：
![image](https://user-images.githubusercontent.com/42317058/126875872-f0c72776-261e-45d2-8c8c-8faa79b03a25.png)
数据库也已创建：
![image](https://user-images.githubusercontent.com/42317058/126875880-d031980f-ba43-450a-a3c5-1a84c273ef97.png)

**Comment by KomachiSion** [comment]
我在本地中可以启动， 推测是jraft依赖的racksdb在你的系统中无法启动，可以参看https://github.com/alibaba/nacos/issues/4336 试着解决下。

单机版能够启动是因为没有使用到jraft。
