### ISSUE TITLE
make NamingProxy be single

### ISSUE THREAD

**Issue by chen-gliu** [alibaba/nacos#6454]
**Describe the bug**    

The NamingProxy's instance will be create in NacosNamingMaintainService and NacosNamingService.In the NamingProxy construction method,a thread pool will be created to periodically execute the refreshsrvifneed() and login() methods,
This means that two thread pools do the same thing. Is this a waste of resources.

在NacosNamingMaintainService和NacosNamingService中都会新创建NamingProxy类的实例，
而在NamingProxy构造方法中会创建线程池周期性的执行 refreshSrvIfNeed()和login()方法。如果创建了两个NamingProxy实例，也就意味着有两个线程池做着相同的事情，这样是不是有些浪费资源。

**Expected behavior**
make NamingProxy be single  

只创建一个NamingProxy的实例，在NacosNamingMaintainService，NacosNamingService中共用这一个实例。

**Desktop (please complete the following information):**
 - OS: Windows
 - Version nacos-server 1.4.1, nacos-client 1.4.1
 - Module naming
 - SDK original, spring-cloud-alibaba-nacos

**Comment by KomachiSion** [comment]
`NacosNamingMaintainService` 是一个独立的运维使用的对象，并非应用使用的对象，将来可能会从client中移除。一般框架应该只会使用`NacosNamingService `

如果您同时使用了这两个对象，可以先自行优化下。主分支会向着移除NacosNamingMaintainService的方向去计划和处理。

**Comment by chen-gliu** [comment]
> `NacosNamingMaintainService` 是一个独立的运维使用的对象，并非应用使用的对象，将来可能会从client中移除。一般框架应该只会使用`NacosNamingService `
> 
> 如果您同时使用了这两个对象，可以先自行优化下。主分支会向着移除NacosNamingMaintainService的方向去计划和处理。

嗯，我只是提一下优化建议。
