### ISSUE TITLE
main class

### ISSUE THREAD

**Issue by zhuhongxu** [alibaba/nacos#6457]
I want to read the source code of nacos server, but I can not find the entrance, in the startup.sh of 141 line, I find it will invoke nacos.nacos, but which class represent the nacos.nacos?

**Comment by brotherlu-xcq** [comment]
you can download the source code and read the module you want instead of the compiled files.

**Comment by KomachiSion** [comment]
Nacos.java in console module

**Comment by zhuhongxu** [comment]
thank you very much.
