### ISSUE TITLE
nacos 2.0.2 cluster publish exist CLOSE_WITE question

### ISSUE THREAD

**Issue by andotorg** [alibaba/nacos#6459]
**Describe the bug**
https://github.com/alibaba/nacos/issues/3651
https://github.com/alibaba/nacos/pull/3703
up link fix nacos cluster CLOSE_WITE 
but nacos 2.0.2 find this is  problem。

**How to Reproduce**

Current problems
1. three alibaba cloud server publish nacos 2.0.2 cluster
2. config save mysql ， mysql is alibaba cloud instance
3. current find two connection CLOSE_WITE status

**Desktop (please complete the following information):**
 - OS: Centos
 - Version centos 7
 - Module config

**Comment by realJackSun** [comment]
Could you provide the version information, and your service TPS?

**Comment by realJackSun** [comment]
The problem occurs in version 2.0.2? could you provide detailed logs?

**Comment by andotorg** [comment]
The problem has been solved, but there is another question

The reason for the above problem is that I added the agent jar package of skywalking at startup

error log ： grpc cannot be cast to class io.grpc.ManagedChannel

I wonder if the GRBC in naocs conflicts with the jar package of skywalking

**Comment by KomachiSion** [comment]
`The problem has been solved, but there is another question` So I will close this issue.

Skywalking problem is solving in Skywalking. #6325

**Comment by andotorg** [comment]
thanks
