### ISSUE TITLE
Application registration is not available

### ISSUE THREAD

**Issue by UUvUU** [alibaba/nacos#646]
# Reporting bugs
写了几个应用注册到nacos本来是好的，第二天突然注册不上去了，只有其中一个能注册上。代码也并没有什么改动。后面新建项目按照示例写也同样注册不上去。并且也没有相关日志，注册不上也没有报错

![_20190118105321](https://user-images.githubusercontent.com/34811401/51362649-743b1800-1b0f-11e9-9d70-4a02b85c6663.png)
![_20190118105335](https://user-images.githubusercontent.com/34811401/51362650-743b1800-1b0f-11e9-8a41-8d6c0dc8bb04.png)
![_20190118105345](https://user-images.githubusercontent.com/34811401/51362651-74d3ae80-1b0f-11e9-8116-52ae13e782d5.png)
![_20190118105412](https://user-images.githubusercontent.com/34811401/51362652-74d3ae80-1b0f-11e9-9a34-7e64210254d2.png)
![_20190118105242](https://user-images.githubusercontent.com/34811401/51362653-74d3ae80-1b0f-11e9-91d8-a97438b38c7c.png)

# 报告错误

如果Nacos项目的任何部分存在问题或文档问题，请通过[opening an issue](https://github.com/alibaba/nacos/issues/new)告诉我们。我们非常认真地对待错误和错误，在产品面前没有不重要的问题。不过在创建错误报告之前，请检查是否存在报告相同问题的issues。

为了使错误报告准确且易于理解，请尝试创建以下错误报告：

- 具体到细节。包括尽可能多的细节：哪个版本，什么环境，什么配置等。如果错误与运行Nacos服务器有关，请附加Nacos日志（具有Nacos配置的起始日志尤为重要）。

- 可复现。包括重现问题的步骤。我们理解某些问题可能难以重现，请包括可能导致问题的步骤。如果可能，请将受影响的Nacos数据目录和堆栈strace附加到错误报告中。

- 不重复。不要复制现有的错误报告。

在创建错误报告之前，最好阅读下[Elika Etemad关于提交好错误报告的文章](http://fantasai.inkedblade.net/style/talks/filing-good-bugs/)，相信 会给你启发。

我们可能会要求您提供更多信息以查找错误。将关闭重复的错误报告。

[nacos-issue](https://github.com/alibaba/nacos/issues/new)
[filing-good-bugs](http://fantasai.inkedblade.net/style/talks/filing-good-bugs/)

**Comment by nkorange** [comment]
Check your local nacos client log: `{user.home}/logs/nacos/naming.log` . See what error happened.

**Comment by UUvUU** [comment]
> 检查您当地的nacos客户端日志：`{user.home}/logs/nacos/naming.log`。看看发生了什么错误。

刚才检查了，我之前说的唯一的可以注册的在日志有正常输入，未注册上的那个，日志里面没有。

这个是未正常注册的
![1](https://user-images.githubusercontent.com/34811401/51363283-473c3480-1b12-11e9-9e05-1128da3141aa.png)
这个是正常注册的
![2](https://user-images.githubusercontent.com/34811401/51363285-473c3480-1b12-11e9-8986-e122e9332efb.png)

日志：
![3](https://user-images.githubusercontent.com/34811401/51363286-473c3480-1b12-11e9-956f-35412b93537d.png)

**Comment by fangjian0423** [comment]
Hi @UUvUU 

You could debug in `NacosServiceRegistry#register` method to see what happened in `namingService.registerInstance`.

**Comment by UUvUU** [comment]
@fangjian0423 
我刚刚测试了，可以注册上的那个进入NacosServiceRegistry#register方法了，其他没注册上的没有进入NacosServiceRegistry#register方法中

**Comment by fangjian0423** [comment]
@UUvUU 

You could try to degrade spring boot version to 2.0.6.RELEASE, maybe something compatibility with 2.1.2.RELEASE. If it does not take effect, you could try to debug in `AbstractAutoServiceRegistration#start` method to see what happened.

**Comment by UUvUU** [comment]
@fangjian0423 
我没有使用 springcloud 只使用了0.2.1的spring-cloud-starter-alibaba-nacos-discovery  我看示例是这么写的

**Comment by UUvUU** [comment]
@fangjian0423 
刚测试了下2.1.2版本可以连上的那个应用 里面之前引入了Greenwich.RC2版本的springcloud，所以能连上，把springcloud去掉就连不上了。去掉的话只能把springboot降级到2.0.6才可以连接

**Comment by fangjian0423** [comment]
Yes. It will using Spring Cloud Finchley if you do not import Spring Cloud version. So it is incompatibility with Spring Boot 2.1.2.RELEASE.

You can see this issue for more details: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/105

**Comment by UUvUU** [comment]
@fangjian0423 
好的，非常感谢
