### ISSUE TITLE
nacos集群配合sentinel推拉持久化的时候有个问题，sentinel修改了配置有个接口实际上只修改了单台机器的，限流也只针对单台

### ISSUE THREAD

**Issue by xigpz** [alibaba/nacos#6460]
nacos集群的时候，sentinel项目的配置文件中配置的是
```
#nacos
nacos.server.ip=192.168.207.128
nacos.server.port=8850
nacos.server.namespace=？？？？
nacos.server.group-id=DEFAULT_GROUP
```
这会导致对限流进行修改的时候，利用
`configService.publishConfig(app + NacosConfigConstant.FLOW_DATA_ID_POSTFIX, nacosConfigProperties.getGroupId(), converter.convert(rules));`更新nacos中的数据的时候只是更新了其中一台，虽然nacos集群界面表现出来的数据是都改变了，但是这是两个接口，下面第一张图怎是实际修改以及限流查询时使用到的
![image](https://user-images.githubusercontent.com/33861765/126957205-2822a898-b148-4d3c-a42c-7e143e17f360.png)
第二张是nacos控制台查看显示的
![image](https://user-images.githubusercontent.com/33861765/126957426-847b4fed-3113-44ce-9f2a-14feb1f444e8.png)
第二个接口不管是哪个节点，其实数据都是最新的，但是第一张图的那个接口则是针对单台机器的，这就会存在限流只会针对连接那个实际查询到的限流规则的状况，所以我想问下这是不是有问题，源码里面修改其实是针对第一个接口数据内容进行了修改，但是第二个接口数据相同是因为节点数据同步了，但是第一个接口数据只是针对真正修改的结果，谁对其修改就显示真实修改数据，并不会像同步数据那样使得各节点数据结果一致，这个两个接口路径一致，只是传参不一致，jar包中调用的都是第一个张图的结果，并不是第二张图各节点统一的数据，引入的jar是
![image](https://user-images.githubusercontent.com/33861765/126958720-d88ae114-d273-4ad5-95be-c116b96fbb61.png)

是否这个jar不适配此版本2.0.2的nacos导致的问题，这里面的获取配置应该使用第二个接口参数获取数据，这样的数据是所有节点一致的数据,这问题挺严重的吧

**Comment by KomachiSion** [comment]
完全看不懂问题，配置中心只要修改了配置，所有订阅这个dataId的客户端都会获取到最新的配置，感觉是你使用方法的问题吧，和nacos没有关系。

**Comment by xigpz** [comment]
但是sentinel中调用查询的接口针对的是单台机子的，而且那个查询nacos配置的接口和nacos上面查询配置的接口，传参个数是不同的，nacos上面那个接口参数比较多，查出来是所有节点数据相同的结果，而sentinel依赖的nacos-client调用的查询配置的接口针对单台查询的确实真实修改的，例如我绑定这台是没问题，但是我的意思是如果其他台修改了配置，即使nacos集群各个节点已经同步了，nacos上面数据也是同步的，但是sentinel调用查询配置的接口是针对真实修改的接口，感觉两个接口传参个数不一样导致的查询结果也是不一样的，那这样是否限流只针对单台机子的配置，我想要的是sentinel根据nacos各个节点同步后的数据进行查询限流，而不是查询到真实操作的结果，就跟假删除一样，我可以理解为这两个接口因为传参个数不同其实是两个接口吗

**Comment by xigpz** [comment]
nacos集群重启后就读到都是对的了，是不是nacos有缓存，是否需要配置什么参数

**Comment by xigpz** [comment]
一切源于集群搭建有问题
