### ISSUE TITLE
Edas不支持nacos2.0.2使用自建nacos吗？根据edas的说明配置了-Dnacos 参数无效。

### ISSUE THREAD

**Issue by soulyu2021** [alibaba/nacos#6465]

**Comment by realJackSun** [comment]
应该是支持的。你们自建部署Nacos的方案能提供一下吗？

**Comment by soulyu2021** [comment]
> 应该是支持的。你们自建部署Nacos的方案能提供一下吗？

Nacos1.4.1的client可以支持 但是换成2.0.2的client就没法支持了. 自建的nacos使用的是集群。按edas里说的添加 两个启动参数-Dnacos。

**Comment by KomachiSion** [comment]
Edas问题请到Edas相关询问。
