### ISSUE TITLE
AtomicInteger Replace with AtomicIntegerFieldUpdater

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/nacos#6466]
![image](https://user-images.githubusercontent.com/33930711/127080654-2619846d-b613-4321-91d9-a451d3d26fb3.png)
Can "Atomic*" be replaced with "Atomic*FieldUpdater to reduce memory usage

**Comment by KomachiSion** [comment]
Why？ I don't think it can enhance much memory but add much difficulty for readable

**Comment by zzq1314zll** [comment]
emm.. I think this [article](https://www.javamex.com/tutorials/synchronization_concurrency_7_atomic_updaters.shtml) is good. I now think this issue can be closed. 😄
