### ISSUE TITLE
nacos 1.4.2 版本配置tidb 4.x/5.x版本，更新配置出现nested exception is java.sql.SQLIntegrityConstraintViolationException异常

### ISSUE THREAD

**Issue by zhuozuozhang** [alibaba/nacos#6473]

**Comment by zhuozuozhang** [comment]
问题是因为：com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl 代码行号347行，没有对org.springframework.transaction.TransactionSystemException进行异常处理
添加一下代码就行：`try {
   addConfigInfo(srcIp, srcUser, configInfo, time, configAdvanceInfo, notify);
  } catch (DataIntegrityViolationException ive) { // Unique constraint conflict
   updateConfigInfo(configInfo, srcIp, srcUser, time, configAdvanceInfo, notify);
  } catch (TransactionSystemException tse) {
   Throwable rootEx = tse.getRootCause();
   if (rootEx instanceof SQLIntegrityConstraintViolationException) { // Unique constraint conflict for tidb
    updateConfigInfo(configInfo, srcIp, srcUser, time, configAdvanceInfo, notify);
   } else {
    throw tse;
   }
  }`

**Comment by KomachiSion** [comment]
那应该是tidb没有按照mysql的标准协议来，代码中我们处理了Unique constraint conflict，但是tidb抛出了不一样的异常类型，导致该问题。

今后支持多数据源插件的时候，考虑把Unique constraint conflict的判断也提取出去，让不同数据库实现，目前仅支持mysql协议的唯一键冲突及derby的唯一键冲突。

**Comment by KomachiSion** [comment]
您可以先自行修改，然后编译使用。主干分支可能不方便定制修复。
