### ISSUE TITLE
nacos1.4.1 dubbo2.7.8版本本地服务启动后会影响正常服务

### ISSUE THREAD

**Issue by 985177520** [alibaba/nacos#6474]
![image](https://user-images.githubusercontent.com/43394661/127124355-e3205fb3-126b-458e-bdb5-dfb174b79d48.png)
问题1：本地启动实例注册到nacos后，会影响到服务器上正常的服务，并且会使其健康状态变成false，但是将整个服务点击删除后，又会将服务器上正常的服务注册到nacos。
问题2：本地服务下线后，会一直注册在nacos但是建康状态为false，然后线上服务调用时会调用健康状态为false的已经关闭的错误服务
报错如下
![image](https://user-images.githubusercontent.com/43394661/127127610-3d5b1c36-302e-41d8-b341-4ce4a96663f1.png)
![image](https://user-images.githubusercontent.com/43394661/127127770-5903de1c-be84-42d4-bdbe-88005e206761.png)

**Comment by 985177520** [comment]
但是正常的服务是在线的，且状态为true

**Comment by KomachiSion** [comment]
无法复现你的问题，建议自查一下操作，或nacos服务端日志，看一下是不是不发送心跳了。

**Comment by 985177520** [comment]
> 无法复现你的问题，建议自查一下操作，或nacos服务端日志，看一下是不是不发送心跳了。

我是在本地调试打断点时，会影响到正在使用的服务。。然后在nacos本地这个服务的健康状态就会是false之后我本地关闭后，线上服务还会调用到本地服务。不知道是不是有些配置有问题

**Comment by KomachiSion** [comment]
dubbo可能没有使用是否健康的字段，dubbo有自己的健康检查体系，只要这个ip的这个端口可以通，他就认为可以调用，正确的做法应该是本地环境和线上环境分离，分到不同的namespace去。

或者手动点击下线，把本地实例下线掉。
