### ISSUE TITLE
Can't get service metadata from java sdk?

### ISSUE THREAD

**Issue by wangdongyun** [alibaba/nacos#6479]
**Describe the bug**
Nacos service has a field named metadata and could be viewed and update on the provided nacos-console.
Bug i find that, with newest SDK, use the method`namingMaintainService queryService(String serviceName, String groupName)` , the reponse has nothing about metadata which field is empty.
I am very confused about this.
More, i want subscribe a service to get a notice(call back)  when the service metadata change.
**Expected behavior**
1. expect fetch the service meta with provided sdk
2. expect subscribe the service to get noticed when the service meta changes.

**How to Reproduce**

code follows

        Service service1 = new Service();
        service1.setAppName("AppName");
        service1.setName("serviceName");
        service1.setProtectThreshold(1.0F);
        Map<String, String> map = new HashMap<>();
        map.put("kk", "vv");
        map.put("cc", "dd");
        map.put("route", "zone");
        map.put("raft", "true");
        service1.setMetadata(map);
        namingMain.createService(service1, new NoneSelector());//注册service

        Service service = namingMain.queryService("test", "group");
        System.out.println(service.toString());
        System.out.println(new Gson().toJson(service.getMetadata()));`

**Comment by KomachiSion** [comment]
Yes, you should focus on the instance metadata for your applications. The service metadata is design for admin not for consumer.

**Comment by wangdongyun** [comment]
> Yes, you should focus on the instance metadata for your applications. The service metadata is design for admin not for consumer.

so what is the purpose of service meta? how to use it

**Comment by wangdongyun** [comment]
> > Yes, you should focus on the instance metadata for your applications. The service metadata is design for admin not for consumer.
> 
> so what is the purpose of service meta? how to use it

use openapi instead of sdk get fetch service meta.

**Comment by KomachiSion** [comment]
service metadata is design for admin, so it can be query and modified by console or openAPI.

Such as set Protect Threshold.

**Comment by KomachiSion** [comment]
I don't know why you want to use service metadata, for applications they should focus on instance metadata.

**Comment by wangdongyun** [comment]
> I don't know why you want to use service metadata, for applications they should focus on instance metadata.

instance metadata is the basic information, but in some case  service has special route strategy, so i want specify it and be read by rpc client .

**Comment by KomachiSion** [comment]
Not support for now. Service metadata is designed for admin, and used in nacos server part. even the route strategy also used in server party by `Selector`

**Comment by wangdongyun** [comment]
OK thanks ！
