### ISSUE TITLE
请问一下，多数据源feature分支是从哪个版本切出来的？

### ISSUE THREAD

**Issue by ly3299297** [alibaba/nacos#6480]
请问一下，多数据源feature分支是从哪个版本切出来的？

**Comment by brotherlu-xcq** [comment]
这个分支
![image](https://user-images.githubusercontent.com/25661357/127279629-186fb855-3b4d-45cc-b050-f5a888a67416.png)

**Comment by KomachiSion** [comment]
没记错应该是1.4.1

**Comment by ly3299297** [comment]
![image](https://user-images.githubusercontent.com/22093961/127280786-c868947b-ef50-4e17-866d-20f6f88ac8c3.png)
我们安全扫描出了有安全问题，未授权也能访问
![image](https://user-images.githubusercontent.com/22093961/127280999-e72f8177-d5c1-4205-8e44-5038876575fa.png)
如果是1.4.1版本，这个问题应该修复了吧

**Comment by brotherlu-xcq** [comment]
我试了一下，现在的主干版本是没有这个问题的了。

**Comment by KomachiSion** [comment]
> ![image](https://user-images.githubusercontent.com/22093961/127280786-c868947b-ef50-4e17-866d-20f6f88ac8c3.png)
> 我们安全扫描出了有安全问题，未授权也能访问
> ![image](https://user-images.githubusercontent.com/22093961/127280999-e72f8177-d5c1-4205-8e44-5038876575fa.png)
> 如果是1.4.1版本，这个问题应该修复了吧

看下release note
