### ISSUE TITLE
curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos.cfg.dataId&group=test&content=helloWorld" 发布配置后，默认配置格式是text，如何把它指定为想要的格式，比如yml格式。未找到运维文档，希望能够得到帮助

### ISSUE THREAD

**Issue by shiyi-ly** [alibaba/nacos#6485]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brotherlu-xcq** [comment]
可以参考OpenAPI文档：https://nacos.io/zh-cn/docs/open-api.html
![image](https://user-images.githubusercontent.com/25661357/127294710-82d2044f-b4d7-4103-bd2a-6b53597f4042.png)

**Comment by shiyi-ly** [comment]
> 可以参考OpenAPI文档：https://nacos.io/zh-cn/docs/open-api.html
> ![image](https://user-images.githubusercontent.com/25661357/127294710-82d2044f-b4d7-4103-bd2a-6b53597f4042.png)

非常感谢
![image](https://user-images.githubusercontent.com/71128366/127295297-0897f406-041f-4f63-8e5a-ff2df42bdb30.png)
我一直在看运维文档。

**Comment by shiyi-ly** [comment]
已解决
