### ISSUE TITLE
support a way to easier config cluster

### ISSUE THREAD

**Issue by lqclester** [alibaba/nacos#649]
现在nacos集群需要在配置文件写ip，这种方式可以进行优化，应该动态配置和集群，可参考consul的集群机制。

-----------------------------------------------------------------------

if u want to cluster, u need to config ip in file, i sugguest support a better way like dynamic config and auto cluster.

**Comment by XCXCXCXCX** [comment]
> 现在nacos集群需要在配置文件写ip，这种方式可以进行优化，应该动态配置和集群，可参考consul的集群机制。
> 
> if u want to cluster, u need to config ip in file, i sugguest support a better way like dynamic config and auto cluster.

Hello, can you elaborate on your thoughts? I have not yet thought of a very good solution for the user experience.

Just provide cluster ip configuration on the interface? This still requires deploying more nacos nodes.

**Comment by KomachiSion** [comment]
Will be enhanced by plugin #8310
