### ISSUE TITLE
建议把配置text配置文件的样例、和使用展示出来It is recommended to display a sample configuration text configuration file and its use

### ISSUE THREAD

**Issue by nameLeeHui** [alibaba/nacos#6491]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nameLeeHui** [comment]
It is recommended to display a sample configuration text configuration file and its use

建议把配置text配置文件的样例、和使用展示出来

**Comment by KomachiSion** [comment]
duplicate with #6492
