### ISSUE TITLE
show  me your demo!!!

### ISSUE THREAD

**Issue by nameLeeHui** [alibaba/nacos#6492]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nameLeeHui** [comment]
我找不到你在java中使用text配置文件的样例
I couldn't find an example of you using a text configuration file in Java

**Comment by KomachiSion** [comment]
I don't know what's your problem. Whatever type the configuration you set, they just a `String` for nacos. nacos will return `String` to your application through listener or getConfig API.

How to use the configuration is your application works. Why need nacos teach you how to use text configuration? It's your application works.
