### ISSUE TITLE
Nacos default port changed from 8080 to 8848

### ISSUE THREAD

**Issue by yanlinly** [alibaba/nacos#65]
Q: why do we change port?

In generally speaking, 8080  or 80 reference public web server host (i.e. Nginx, Apache etc...), so 8080 is very easy to conflict with the customer's web application.

Q: why Nacos choose 8848 as the default port?

 First of all, it is very convenient to remember
 Again，8848 represents the height of the highest peak Mount Everest(珠穆朗玛峰)，Nacos team hope we can create a obviously and great product through our efforts.

**Comment by libinglong** [comment]
nice port with nice description
