### ISSUE TITLE
com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance/list after all servers([xxxx.xxxx.xx.186:8846]) tried: ErrCode:503, ErrMsg:server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized] docker部署集群后，可以正常访问，集成springcloud时控制台报错，有遇到的小伙伴吗，求帮助

### ISSUE THREAD

**Issue by shiyi-ly** [alibaba/nacos#6504]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shiyi-ly** [comment]
1

**Comment by shiyi-ly** [comment]
猜测可能是docker容器之间网络不互通的原因

**Comment by realJackSun** [comment]
> 猜测可能是docker容器之间网络不互通的原因

登入docker，互相ping一下，能ping通吗

**Comment by KomachiSion** [comment]
Please use issue template to describe your problem.

**Comment by thanks-git** [comment]
同样的问题：
![image](https://user-images.githubusercontent.com/40749598/151097928-488fcb7e-660f-4a0b-a470-afd992e51aff.png)
