### ISSUE TITLE
What can this parameter do “nacos.core.auth.default.token.secret.key”

### ISSUE THREAD

**Issue by kuaile-zc** [alibaba/nacos#6508]
Hi Developer ：
### The default token:
nacos.core.auth.default.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789
  
I want to know what this parameter can do.

**Comment by zarkzheng** [comment]
It's a algorithm-specific signature verification key used to validate any discovered JWS digital signature (for [JWT](https://github.com/jwtk/jjwt)). So that nacos can use this key to create token, validate token and get authentication from a given token.
It's used for nacos security module.

**Comment by kuaile-zc** [comment]
> It's a algorithm-specific signature verification key used to validate any discovered JWS digital signature (for [JWT](https://github.com/jwtk/jjwt)). So that nacos can use this key to create token, validate token and get authentication from a given token.
> It's used for nacos security module.
Thank you for your answer. 
Until I saw this answer I thought it was a default Token that could be used as a login user's permission.
