### ISSUE TITLE
Can you consider storing the parameters of historical configuration files ”config type” and "config describe "？

### ISSUE THREAD

**Issue by kuaile-zc** [alibaba/nacos#6509]
When I deleted the configuration file and tried to roll back from the historical configuration, I found that two parameters were lost, the configuration type and the configuration description. 

So I check the sql and find this table.

`CREATE TABLE his_config_info (
  id bigint NOT NULL,
  nid bigint NOT NULL generated by default as identity,
  data_id varchar(255) NOT NULL,
  group_id varchar(128) NOT NULL,
  tenant_id varchar(128) default '',
  app_name varchar(128),
  content CLOB,
  md5 varchar(32) DEFAULT NULL,
  gmt_create timestamp NOT NULL DEFAULT '2010-05-05 00:00:00.000',
  gmt_modified timestamp NOT NULL DEFAULT '2010-05-05 00:00:00.000',
  src_user varchar(128),
  src_ip varchar(20) DEFAULT NULL,
  op_type char(10) DEFAULT NULL,
  constraint hisconfiginfo_nid_key PRIMARY KEY (nid));`

Perhaps the configuration description occupies a lot of space, but the configuration type does not occupy much storage. Do you consider storing this field? 

Whether to add “type” and “desc”  in subsequent versions ？

**Comment by brotherlu-xcq** [comment]
It seem like duplicate with https://github.com/alibaba/nacos/issues/5943. We discussed before but have no result. I have made a solution before in https://www.yuque.com/brotherlu/cby6eg/eni4c9.
