### ISSUE TITLE
2.0.3版本，编辑配置界面F1全屏编辑功能异常

### ISSUE THREAD

**Issue by 77321660** [alibaba/nacos#6510]
**Describe the bug**
升级到2.0.3版本，编辑配置界面F1全屏编辑功能异常
**Expected behavior**
配置编辑界面按F1，正常显示全屏编辑

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. 登录
2. 配置列表
3. 编辑配置文件
4. 按F1全屏编辑，只显示半屏

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Version [nacos-server 2.0.3]
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**

**Comment by brotherlu-xcq** [comment]
I will check it and try to fix.

**Comment by brotherlu-xcq** [comment]
This issue is caused by PR #6163 . due to the fix height of code editor.
