### ISSUE TITLE
bootstrap配置文件不优先加载（失效）问题

### ISSUE THREAD

**Issue by TapGoNow** [alibaba/nacos#6512]
- os: windows10
- springboot version: 2.3.7 RELEASE
- spring cloud: Hoxton.SR9

spring cloud中配置文件应该首先读取`bootstrap.properties`，但是现在我配置中`boostrap.properties`没有优先读取。本地程序和nacos配置中心都会优先读取`application.yml`文件,并且启动台会报警告

![image](https://user-images.githubusercontent.com/50830927/127672762-9e983267-194a-481c-abbf-dac8f41e911e.png)

### 疑问

这里加载顺序很奇怪，它会优先找`application.yml`的配置，如果没有发现对应的配置，才会去找`bootstrap.yml`。而且抛出了这样一个空白配置文件的警告，而别人配置正确的应该是不会抛出这个警告的，应该像下面这样
![image](https://user-images.githubusercontent.com/50830927/127673207-aa31978f-24df-42f1-83a5-60d5e8d6f73e.png)

最神奇的一点是，虽然抛出了那个警告，但是在下面的打印台中还是会打印出读取了这些配置文件

**Comment by realJackSun** [comment]
请咨询SpringCloud社区
