### ISSUE TITLE
nacos 2.0无法读取远程配置中心数据

### ISSUE THREAD

**Issue by iyezhou** [alibaba/nacos#6515]
<spring-boot.version>2.4.2</spring-cloud.version>
<spring-cloud.version>2020.0.0</spring-cloud.version>
<spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
<nacos-config.version>2021.1</nacos-config.version>
<nacos.version>2.0.3</nacos.version>

日志信息如下，config=空，另外，一直报 Send request fail, request=... ... retryTimes=0,errorMessage=Client not connected,current status:STARTING，确认8848，9848，9849端口均已开放

![微信图片_20210731131813](https://user-images.githubusercontent.com/26378961/127729618-5923bec9-e2df-47d7-92b3-7482d010c595.png)
![微信图片_20210731131912](https://user-images.githubusercontent.com/26378961/127729625-a0648577-5d78-4018-a4bc-3406fbec9527.png)
![微信图片_20210731131934](https://user-images.githubusercontent.com/26378961/127729628-90c5a575-e17e-49ab-8f21-963370b73864.png)
![微信图片_20210731132004](https://user-images.githubusercontent.com/26378961/127729631-0ae700da-3e5e-480d-9237-dc75b4484602.png)

**Comment by realJackSun** [comment]
需要您设置一下环境变量ok.cloud.name

**Comment by iyezhou** [comment]
是我的配置问题，谢谢
