### ISSUE TITLE
v1.4.2 和1.4.1源代码提交不完整

### ISSUE THREAD

**Issue by liuyunlong1229** [alibaba/nacos#6517]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
下载nacos的源代码后，无法启动 nacos-console

### Describe what you expected to happen
 源代码完整，可以基于源代码启动 nacos-server

### How to reproduce it (as minimally and precisely as possible)

1.  根据tag（1.4.1，1.4.2 下载源代码）
2.  启动控制台程序
3.  提示无法启动，报类找不到

### Tell us your environment
Mac ，JDK 1.8
![Xnip2021-08-01_23-01-11](https://user-images.githubusercontent.com/16921480/127775785-ea5d3744-f1eb-4fc7-92b8-01f0b6e34b41.jpg)

**Comment by brotherlu-xcq** [comment]
需要编译，https://github.com/alibaba/nacos/issues/6507

**Comment by liuyunlong1229** [comment]
Mac m1 的笔记本，直接执行是没有用的，
首先直接执行 nacos-all 执行compile 是看不到任何错误信息的，需要单独对nacos-consistency，执行compile才能看到 
提示找不到“com.google.protobuf:protoc:exe:osx-aarch_64:3.12.0”，
此时，需要修改pom的插件配置，改成osx-x86_64

                  <plugin>
                            <groupId>org.xolstice.maven.plugins</groupId>
                            <artifactId>protobuf-maven-plugin</artifactId>
                            <version>0.5.0</version>
                            <configuration>
                                <protocArtifact>com.google.protobuf:protoc:${protobuf-java.version}:exe:osx-x86_64</protocArtifact>

                                <pluginId>grpc-java</pluginId>
                                <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc-java.version}:exe:osx-x86_64</pluginArtifact>

                            </configuration>
                            <executions>
                                <execution>
                                    <goals>
                                        <goal>compile</goal>
                                        <goal>compile-custom</goal>
                                    </goals>
                                </execution>
                            </executions>
                        </plugin>
