### ISSUE TITLE
微服务项目在客户端和服务端均为2.0.2版本上注册服务显示失败，失败有两个：1、Client not connected,current status:STARTING；2、Server check fail, please check server localhost ,port 9848 is available , error ={} 

### ISSUE THREAD

**Issue by Throb571** [alibaba/nacos#6518]
服务端采用单机模式启动，启动日子没有报任何错误，并且gRPC相关的端口（9848、9849和7848）在防火墙上都放行了，并且telnet是可以通的，不知道为啥就是注册不了服务。相关情况截图如下：
1、错误截图：
![image](https://user-images.githubusercontent.com/54920007/127777669-8030511c-c7b5-4292-b851-f924a5a9bdf9.png)
2、docker单机启动：
![image](https://user-images.githubusercontent.com/54920007/127777680-1b6c7db8-b9f9-45f3-af6e-a71dbf15c5cf.png)
3、防火墙截图：
![image](https://user-images.githubusercontent.com/54920007/127777684-632740e2-0726-472f-9058-57863dc38421.png)

**Comment by brotherlu-xcq** [comment]
你的客户端也是部署在这台机器吗？

**Comment by Throb571** [comment]
> 你的客户端也在这台机器上吗？

不是，微服务是我本地上的，而nacos是远程服务器上面的， 然后在docker上单机部署的

**Comment by brotherlu-xcq** [comment]
你的错误日志里面，server的地址是localhost，你检查一下你的本地client的配置呢
![image](https://user-images.githubusercontent.com/25661357/127887747-f0a11a70-7e0d-4dde-a0ec-beaf4b61b0a4.png)

**Comment by Throb571** [comment]
> 你的错误日志里面，server的地址是localhost，你检查一下你的本地client的配置呢
> ![image](https://user-images.githubusercontent.com/25661357/127887747-f0a11a70-7e0d-4dde-a0ec-beaf4b61b0a4.png)

![image](https://user-images.githubusercontent.com/54920007/127940945-bc8cb4d4-6e47-48f9-b985-3b9affe6f986.png)
注册中心配置不是配置的本地，而且那段话的翻译是，服务检查失败，请检查本地服务9848端口是否可用？

**Comment by Throb571** [comment]
> > 你的错误日志里面，server的地址是localhost，你检查一下你的本地client的配置呢
> > ![image](https://user-images.githubusercontent.com/25661357/127887747-f0a11a70-7e0d-4dde-a0ec-beaf4b61b0a4.png)
> 
> ![image](https://user-images.githubusercontent.com/54920007/127940945-bc8cb4d4-6e47-48f9-b985-3b9affe6f986.png)
> 注册中心配置不是配置的本地，而且那段话的翻译是，服务检查失败，请检查本地服务9848端口是否可用？

然后我本地上面telnet 都行，如图所示：
![Uploading image.png…]()

**Comment by Throb571** [comment]
> 你的错误日志里面，server的地址是localhost，你检查一下你的本地client的配置呢
> ![image](https://user-images.githubusercontent.com/25661357/127887747-f0a11a70-7e0d-4dde-a0ec-beaf4b61b0a4.png)

而且我本地telnet那个端口 可行的 如图所示：
![image](https://user-images.githubusercontent.com/54920007/127941295-56a7cdfe-6426-40b0-9577-69bd08e137e1.png)
![image](https://user-images.githubusercontent.com/54920007/127941321-d1f6cd62-eeab-495c-af06-1eb79d9b13aa.png)

**Comment by brotherlu-xcq** [comment]
看你这个错误是拉取配置失败，你的yaml里面只配置了服务发现的地址，你把配置中心的yaml配置也加上呢？可以参考SCA的文档配置https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme.md

**Comment by KomachiSion** [comment]
应该是地址配置错了，配置成localhost了

**Comment by kukukakiki** [comment]
我也遇到同样的问题
nacos服务端版本：2.0.3
工程版本：2.2.6.RELEASE
spring-cloud-starter-alibaba-nacos-discovery
spring-cloud-starter-alibaba-nacos-config
spring-cloud-starter-dubbo
nacos-clinet：2.0.3
启动后控制台错误：
![image](https://user-images.githubusercontent.com/7196408/128993329-2410c09d-69cb-43bc-8b05-0cc8d6eb78ae.png)

跟中启动源码：
1、GrpcClient.java的264行，将我设置nacos服务端80端口，默认增加了1000
2、GrpcClient.java的145行，检查服服务是否成功中，调用RequestGrpc.request方法
3、RequestGrpc.java的213行，访问的服务地址错误，应该是80端口，实际代码访问的是1080
![image](https://user-images.githubusercontent.com/7196408/128993852-0470fc6d-f9e1-447a-9423-c385c118d7c9.png)

处理思路：
1、如果配置了nginx代理将增加1000以后的两个端口开放出来（tcp方式）
2、如果没有nginx代理，本机telnent一下增加1000后的端口是否能通，不同那就是nacos服务器的问题，自行检查
我通过上面的方式解决了这个启动错误

**Comment by Wang-Jun-Chao** [comment]
> 我也遇到同样的问题
> nacos服务端版本：2.0.3
> 工程版本：2.2.6.RELEASE
> spring-cloud-starter-alibaba-nacos-discovery
> spring-cloud-starter-alibaba-nacos-config
> spring-cloud-starter-dubbo
> nacos-clinet：2.0.3
> 启动后控制台错误：
> ![image](https://user-images.githubusercontent.com/7196408/128993329-2410c09d-69cb-43bc-8b05-0cc8d6eb78ae.png)
> 
> 跟中启动源码：
> 1、GrpcClient.java的264行，将我设置nacos服务端80端口，默认增加了1000
> 2、GrpcClient.java的145行，检查服服务是否成功中，调用RequestGrpc.request方法
> 3、RequestGrpc.java的213行，访问的服务地址错误，应该是80端口，实际代码访问的是1080
> ![image](https://user-images.githubusercontent.com/7196408/128993852-0470fc6d-f9e1-447a-9423-c385c118d7c9.png)
> 
> 处理思路：
> 1、如果配置了nginx代理将增加1000以后的两个端口开放出来（tcp方式）
> 2、如果没有nginx代理，本机telnent一下增加1000后的端口是否能通，不同那就是nacos服务器的问题，自行检查
> 我通过上面的方式解决了这个启动错误

我使用docker启动，开放了8848，9848端口，telnet 9848的是通的。启动服务却说有问题。

**Comment by KomachiSion** [comment]
服务端配置的主端口是x 那grpc端口就是x+1000.
如果有端口转发或vpn，请自行匹配端口映射
然后客户端配置请配置主端口x，不要配置x+1000

https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by zuihou** [comment]
> 

我已经确保了 8848、9848、7848 等端口全通的，而且 nacos-server 也是单机部署，nacos-server 和 nacos-client (spring cloud) 也是部署在一台物理机上， 但同时启动多个client时， 还是会报这个错, 单独一个client 一个client的启动没问题。

**Comment by lxlhz** [comment]
> > 你的错误日志里面，server的地址是localhost，你检查一下你的本地client的配置呢
> > ![image](https://user-images.githubusercontent.com/25661357/127887747-f0a11a70-7e0d-4dde-a0ec-beaf4b61b0a4.png)
> 
> 而且我本地telnet那个端口 可行的 如图所示： ![image](https://user-images.githubusercontent.com/54920007/127941295-56a7cdfe-6426-40b0-9577-69bd08e137e1.png) ![image](https://user-images.githubusercontent.com/54920007/127941321-d1f6cd62-eeab-495c-af06-1eb79d9b13aa.png)

你的问题解决了，我和你情况一样，telnet也是一样的
