### ISSUE TITLE
nacos配置中心，动态配置不生效

### ISSUE THREAD

**Issue by MEIIT** [alibaba/nacos#6519]
版本：nacos2.0.1 server，spring.cloud.alibaba.version 2.2.6.RELEASE，系统阿里云ecs Centos
是否必现：是
以nohup java -Djava.ext.dirs=.lib -jar xxxxxxx.jar --spring.profiles.active=pro > nohup.log 2>&1 &命令运行jar包，配置中心的动态刷新会失效，只有将所有jar打成一个jar，用nohup java -jar xxxxxxx.jar --spring.profiles.active=pro > nohup.log 2>&1命令运行动态刷新配置才正常

**Comment by realJackSun** [comment]
Nacos有现成的部署方案和启动脚本，为什么要自己打jar包？

**Comment by realJackSun** [comment]
https://nacos.io/en-us/docs/quick-start.html
