### ISSUE TITLE
kill服务后，出现NullPointerException

### ISSUE THREAD

**Issue by KingSirLee** [alibaba/nacos#6525]
如题，正常kill java进程(不是kill -9)，报错如下：

o.s.beans.factory.support.DisposableBeanAdapter - Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/3985861/127849755-11b91451-5e92-4b16-8a2f-c4648ce466fe.png)

**Comment by JMMMM** [comment]
我也遇到了，如何解决

**Comment by kevinYuan2017** [comment]
> 同样的问题, IDEA启动项目正常, 停止项目时signal是2, 但是到最后的shutdownhook执行阶段, 爆了这个NPE, 详细日志如下:
> 
> ```
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::                (v2.5.7)
> 
> 2021-12-01 20:01:37.882  INFO 36098 --- [           main] c.h.d.s.StatusAlignApplication           : Starting StatusAlignApplication using Java 1.8.0_162 on MacBookPro with PID 36098 (/Users/zhongkaiyuan/Desktop/demo/target/classes started by zhongkaiyuan in /Users/zhongkaiyuan/Desktop/demo)
> 2021-12-01 20:01:37.884  INFO 36098 --- [           main] c.h.d.s.StatusAlignApplication           : The following profiles are active: nacos
> 2021-12-01 20:01:38.853  INFO 36098 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
> 2021-12-01 20:01:38.855  INFO 36098 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
> 2021-12-01 20:01:38.876  INFO 36098 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 6 ms. Found 0 Redis repository interfaces.
> 2021-12-01 20:01:39.039  INFO 36098 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=ab76f7ab-7589-3de2-81ee-93baac3aea3c
> 2021-12-01 20:01:39.354  INFO 36098 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
> 2021-12-01 20:01:39.365  INFO 36098 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2021-12-01 20:01:39.365  INFO 36098 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.55]
> 2021-12-01 20:01:39.447  INFO 36098 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> 2021-12-01 20:01:39.447  INFO 36098 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1525 ms
> 2021-12-01 20:01:40.801  WARN 36098 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
> 2021-12-01 20:01:40.806  INFO 36098 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
> 2021-12-01 20:01:41.124  INFO 36098 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
> 2021-12-01 20:01:41.305  INFO 36098 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, DEFAULT_GROUP demo 192.168.20.100:8080 register finished
> 2021-12-01 20:01:41.321  INFO 36098 --- [           main] c.h.d.s.StatusAlignApplication           : Started StatusAlignApplication in 3.771 seconds (JVM running for 4.476)
> 2021-12-01 20:01:44.372  WARN 36098 --- [       Thread-7] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
> 2021-12-01 20:01:44.373  WARN 36098 --- [      Thread-14] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher
> 2021-12-01 20:01:44.373  WARN 36098 --- [      Thread-14] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end
> 2021-12-01 20:01:44.373  WARN 36098 --- [       Thread-7] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end
> 2021-12-01 20:01:44.407  INFO 36098 --- [ionShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registering from Nacos Server now...
> 2021-12-01 20:01:44.881  INFO 36098 --- [ionShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registration finished.
> 2021-12-01 20:01:52.143  WARN 36098 --- [ionShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Custom destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException
> 
> Process finished with exit code 130 (interrupted by signal 2: SIGINT)
> ```

jdk版本: 1.8.0_162
nacos server版本: 2.0.3
nacos依赖包:
```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>${alibaba-nacos.version}</version>
</dependency>
```
版本号用过2.1.3.RELEASE, 2.2.6.RELEASE, 2021.1
问题复现方法: 启动项目后, 停止项目即可, 不要点强制停止

**Comment by kevinYuan2017** [comment]
> 如题，正常kill java进程(不是kill -9)，报错如下：
> 
> o.s.beans.factory.support.DisposableBeanAdapter - Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException
> 
> ![image](https://user-images.githubusercontent.com/3985861/127849755-11b91451-5e92-4b16-8a2f-c4648ce466fe.png)

看到你在8月3号关闭了这个issue, 可以贴一下具体情况吗? 非常感谢.

**Comment by kevinYuan2017** [comment]
[https://github.com/alibaba/spring-cloud-alibaba/issues/2283](url)
