### ISSUE TITLE
Inconsistent results returned by different versions of the open-api `/nacos/v1/ns/service`

### ISSUE THREAD

**Issue by YangHuiFor** [alibaba/nacos#6535]
**Describe the bug**
In version 1.4.x，GET `/nacos/v1/ns/service`  querying a not exist service , return status code `500`.  return message body `caused: service api@@hyperf is not found!`

But in version 2.0.x ，return status code `200` ， return message body `{"namespaceId":"67f9ce9b-c3d5-4dbb-acf8-308b6b0b928e","groupName":"api","name":"hyperf","protectThreshold":0.0,"metadata":{},"selector":{"type":"none"},"clusters":[]}`

why？

**Comment by realJackSun** [comment]
Is it because the service was and empty service and been autocleaned by nacos1.4.x?

**Comment by YangHuiFor** [comment]
> Maybe the service was and empty service and been autocleaned by nacos1.4.x?

Services are registered for the first time。 
in version 2.0, the service information was returned, which caused a bug in the program
