### ISSUE TITLE
多数据源源代码貌似缺少一些类

### ISSUE THREAD

**Issue by xianlinyi** [alibaba/nacos#6536]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47588282/127977583-e21c2ac9-82b2-4efd-aef5-038a6315985b.png">

这些类找不到

**Comment by brotherlu-xcq** [comment]
https://nacos.io/en-us/docs/faq.html ,需要编译一下。

**Comment by xianlinyi** [comment]
> https://nacos.io/en-us/docs/faq.html ,需要编译一下。
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/47588282/127979204-bbf08acf-f134-46ca-b245-adabb4d25d58.png">

不是FAQ里面那个东西吧，这些类是引用的同一模块下的包路径，编译这个模块肯定通不过呀

**Comment by haoyann** [comment]
也是一样的，`mvn clean compile` 编译一下。

**Comment by xianlinyi** [comment]
> 也是一样的，`mvn clean compile` 编译一下。

谢谢，编译确实可以，但是只是在target里面生成了这些文件，请问idea下有没有什么办法让他在源文件里生成，或者说不报错啊

**Comment by haoyann** [comment]
@xianlinyi 你在`idea`里面编译一次就行了，后面也不会报错。
![image](https://user-images.githubusercontent.com/43994656/128279449-485a6853-4350-443a-b02d-6788929b51b7.png)

**Comment by xianlinyi** [comment]
> @xianlinyi 你在`idea`里面编译一次就行了，后面也不会报错。
> ![image](https://user-images.githubusercontent.com/43994656/128279449-485a6853-4350-443a-b02d-6788929b51b7.png)

好的，找到了，多谢
