### ISSUE TITLE
Nacos切换成集群模式后，服务无法正常注册。

### ISSUE THREAD

**Issue by RedStone365** [alibaba/nacos#6539]
![image](https://user-images.githubusercontent.com/23112024/127996850-6f0aea31-49a3-4b96-b9d4-2490518fbaf5.png)
![image](https://user-images.githubusercontent.com/23112024/127996776-0a0e75c4-2417-4ae1-a492-72bd32816f55.png)
报错，原因是我们在cluster配置中，使用了域名。需要修改为真实内网IP地址才可以。

**Comment by realJackSun** [comment]
Set this to "true" and retry
![image](https://user-images.githubusercontent.com/58767027/128109674-4921e582-2e6f-4232-96d3-e96df1f7136a.png)
