### ISSUE TITLE
重启mysql8后,nacos2.0.3无法重新连接成功.报错是Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by mosaicwang** [alibaba/nacos#6545]
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: Centos7.6
 - Version nacos:2.0.3 docker
- Mysql Version:8.0.26 docker

**Additional context**

**Comment by brotherlu-xcq** [comment]
It seems the problem caused by Mysql, maybe you can refer this article https://blog.csdn.net/Yuriey/article/details/80423504.
