### ISSUE TITLE
2.0.1版本 服务详情页 过滤按钮不显示文本

### ISSUE THREAD

**Issue by ch-ningyi** [alibaba/nacos#6551]
nacos 2.0.1版本 服务详情页 集群过滤按钮不显示文本
![T0K 1HP@)`51UYW8J8W0A}U](https://user-images.githubusercontent.com/66402361/128111603-690fb5da-33b2-4584-8645-396c62c022e8.png)

**Comment by brotherlu-xcq** [comment]
应该是上层的js没有将i18n对象传入到下层导致的，我这边看看。
