### ISSUE TITLE
Can I use jvm arguments to config my application nacos address ?

### ISSUE THREAD

**Issue by leanderli** [alibaba/nacos#6559]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lpaz010** [comment]
嗨，在确保没有conf/cluster.conf这个文件情况下，然后试一试`-Dnacos.member.list=${MEMBER_LIST}`

**Comment by leanderli** [comment]
> 嗨，在确保没有conf/cluster.conf这个文件情况下，然后试一试`-Dnacos.member.list=${MEMBER_LIST}`，多个地址使用英文逗号隔开。

It's work! Thank you very much
