### ISSUE TITLE
Nacos0.8.0 use @Value display error "Could not resolve placeholder"

### ISSUE THREAD

**Issue by ankeway** [alibaba/nacos#656]
Spring Boot 2.0.6

bootstrap.yml
 spring
   nacos:
      discovery:
        server-addr: 192.168.14.187:8848
        # if you just want to subscribe, but don't want to register your service, set it to false.
        register-enabled: true
      config:
        server-addr: 192.168.14.187:8848
        ext-config:
        - data-id: redis-conf.properties 
          group: default
          refresh: true

nacos config 
redis-conf.properties
Content is 
redis.host=192.168.14.220

@RefreshScope

	@Value("${redis.host}")
	private String redishost;

Run Application display
java.lang.IllegalArgumentException: Could not resolve placeholder

**Comment by hxy1991** [comment]
请参看下：[nacos-spring-cloud-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example)

**Comment by ankeway** [comment]
> 请参看下：[nacos-spring-cloud-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example)
确定试过了吗？nacos 0.8 通过配置连接redis正常说明可以正确读取到配置信息，@value 无法取到值， value设置默认值可以不报错，但是还是取不到变量值

**Comment by hxy1991** [comment]
> > 请参看下：[nacos-spring-cloud-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example)
> > 确定试过了吗？nacos 0.8 通过配置连接redis正常说明可以正确读取到配置信息，@value 无法取到值， value设置默认值可以不报错，但是还是取不到变量值

是没问题的。你能否提供下你的完整 demo，还有在 Nacos 控制台新建配置的 Data ID / Group / 
 配置内容？

**Comment by ankeway** [comment]
> > > 请参看下：[nacos-spring-cloud-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example)
> > > 确定试过了吗？nacos 0.8 通过配置连接redis正常说明可以正确读取到配置信息，@value 无法取到值， value设置默认值可以不报错，但是还是取不到变量值
> 
> 是没问题的。你能否提供下你的完整 demo，还有在 Nacos 控制台新建配置的 Data ID / Group /
> 配置内容？

**Comment by ankeway** [comment]
我知道为什么了，只要是spring.application.name的名称和Data Id的名字一样就会无法获取对应文件里的属性值，比如 nacos-demo.properties 如果你的spring.application.name=nacos-demo，那么nacos-demo.properties就为{}
 "name": "NACOS:nacos-demo.properties",
"properties": {}

**Comment by hxy1991** [comment]
Nacos Spring Cloud 中 spring.application.name 是构成 Data ID 的一部分，如

```
spring.application.name=nacos-demo

# 指定配置的后缀，支持 properties、yaml、yml，默认为 properties
spring.cloud.nacos.config.file-extension=properties
#spring.cloud.nacos.config.file-extension=yaml
```

则会获取 Data ID 为 `nacos-demo.properties`， Group 为 `DEFALT_GROUP` 的。

能否贴下你的 `bootstrap.properties` 的配置，还有你在控制台新建的 Data ID / Group /
配置内容？

**Comment by ankeway** [comment]
我理解是按照ext-config的配置加载配置文件了，实际spring.application.name 默认会  DataId=${spring.application.name}.properties Group=DEFALT_GROUP覆盖同名其他Group

的配置文件

**Comment by ankeway** [comment]
看了nacos源码，最后理解了，是使用优先级的问题，https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config文章末尾讲到了优先级的问题，https://blog.csdn.net/ankeway/article/details/88055746，写了一个博客作为解释

**Comment by Joker1995** [comment]
我以为在写配置格式是YAML，内容就写成YAML格式，没想到内容填写还是K-V格式，这里没看说明还真被填写的字眼误导了

**Comment by lybaiyu** [comment]
我的是因为namespace用的名称而不是ID
