### ISSUE TITLE
2.0.1 2.0.2 2.0.3 k8s方式部署出现以下报错

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#6560]
完全按照https://github.com/nacos-group/nacos-k8s 的nfs方式部署
2.x.x版本集群方式部署报错，只修改了nacos镜像版本号和mysql相关配置。
版本号改为1.4.2一切正常，2.x.x版本修改脚本改为单节点方式部署正常。

日志稍后补上

**Comment by sundong1982** [comment]
nacos.log没有任何报错，全是INFO
其他日志也没发现错误。

3个节点都是up状态
http://ip:8848/nacos/v1/ns/operator/cluster/state
随机出现
caused: unable to find local peer: nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:8848, all peers: [];
caused: unable to find local peer: nacos-server-1.nacos-server-headless.nacos-server.svc.cluster.local:8848, all peers: [];
{"ip":"nacos-server-2.nacos-server-headless.nacos-server.svc.cluster.local:8848","term":-1,"leaderDueMs":12789,"heartbeatDueMs":1687,"state":"FOLLOWER"}

只有节点2正常 


日志到INFO Nacos started successfully in stand alone mode. use external storage终止

缺少
INFO Initializing Servlet 'dispatcherServlet'
INFO Completed initialization in 82 ms

**Comment by realJackSun** [comment]
"一开始出现
server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]" 这个错误持续了多久？

**Comment by sundong1982** [comment]
@realJackSun 10多秒

**Comment by KomachiSion** [comment]
那是正常的，启动过程中协议没有启动完成，报错是正常的。

**Comment by sundong1982** [comment]
@KomachiSion 启动过程中协议没有启动完成，  这个怎么破，等官方更新版本 还是 k8s脚本需要修改。

**Comment by sundong1982** [comment]
不是
