### ISSUE TITLE
如何开启nacos的持久化服务功能

### ISSUE THREAD

**Issue by shadow-lyvee** [alibaba/nacos#6564]
createEmptyService(namespaceId, serviceName, instance.isEphemeral()); 这个是nacos2.0当中的源码
其中 instance.isEphemeral()默认为true 我该如何修改这个值为false呢？客户端能否配置

**Comment by haoyann** [comment]
这个方法`com.alibaba.nacos.api.naming.NamingService#registerInstance(java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)`，修改 `Instance` 的 `ephemeral` 属性。
