### ISSUE TITLE
[nacos 1.x] service change event merge algorithm lost efficacy when multiple instances of the same service changed at the same time

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#6565]
**Describe the bug**
when multiple instances of the same Service changed at the same time,  service change event merge algorithm  of Nacos 1.x lost efficacy because futureMap had nothing yet.
it will cause the main process almost hang if too many events of the same serivce are not merged at serviceChange().

**Comment by zrlw** [comment]
The default listener that Spring implements is synchronous. The publish method will wait until the methods of all the listeners have completed successfully.

**Comment by zrlw** [comment]
Synchronous publish-subscribe is blocking in nature, can have bad impact on application performance. To get rid of this, Spring provides asynchronous event listener using ```@async``` annotation. The first step is to enable the async processing by annotating the component with ```@EnableAsync```

**Comment by zrlw** [comment]
it might like asynchronous that using threadpool in synchronous application event handler, but there are no need to use synchronous application event handler with threadpool,  using threadpool directly is enough.

**Comment by zrlw** [comment]
merging service change event publish operation at serviceChange(), changing onApplicationEvent to async mode, removing threadpool from onApplicationEvent give us such advantages:
1. more quickly （service register、 client subscribe）
2. less consumption （cpu、memory）

**Comment by zrlw** [comment]
we enclose two fix methods for comparison.
PS: 
Event pub-sub might not be suitable for high concurrency enviroment.

**Comment by zrlw** [comment]
我们提的两个PR关闭了，原因是issue描述不清楚，直接中午解释一下问题过程吧。
代码：nacos 1.x版本的PushSevice
背景知识：
1. spring默认的事件机制是同步的，也就是说没有@Async注解的onApplicationEvent事件处理方法是在事件发布线程调用publishEvent时直接执行的，publishEvent方法直接调用了onApplicationEvent方法；
2. 同步方式下的事件处理方法应当尽可能快，否则会长时间阻断main process继续执行。
问题现象：
我们在一键重启应用的测试过程发现客户端不能及时收到nacos注册中心的服务通知，伴随的现象是nacos注册中心资源消耗冲高（cpu、内存），查看nacos日志，里面有很多同一服务的变动通知，时间几乎相同。
排查过程：
1. debug跟踪发现PushSevice的seviceChange方法判断是否重复通知的机制失效，用来判重的futureMap里面还没有存入对应的key；
2. 发现PushService发布的serviceChangeEvent事件只有PushService自己消费，并且采用的是spring默认的同步模式，调用publishEvent之后会等待事件处理方法onApplicationEvent返回。
不同方案测试结果对比：
1. 在onApplicationEvent事件处理方法里加double检查机制
因为spring执行onApplicationEvent事件处理方法采用single-thread模式，包括main在内的其他线程都会等待，所以在这个方法再次判断futureMap有没有对应的key不存在多线程的问题。
效果：断点确认serviceChange的publishEvent调用方法依旧存在排队等待的情况；nacos服务假死，管理页面刷不出来；日志确认同一服务的事件通知得到合并。
2.在serviceChange方法中直接用线程池执行原来onApplicationEvent的方法，同时将判重机制全部并入serviceChange，删除事件处理机制，修改内容见 #6615 
效果：断点确认serviceChange执行顺畅；nacos注册中心管理页面正常；日志确认同一服务的事件通知得到合并。
3. 保留事件机制，将通知判重控制机制提前至 serviceChange方法，修改内容见 #6566
效果和2类似。

**Comment by zrlw** [comment]
@KomachiSion @horizonzy

**Comment by KomachiSion** [comment]
2.0 已经不使用spring 的application event了。
