### ISSUE TITLE
Bug: Rollback configuration loss type, beta to full release also.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#6567]
**Describe the bug**
The table  `his_config_info` does not have a type field. When the operation on the page is rolled back, it is published directly with the historical configuration, but the type field is missing. After publishing, it is restored to text (default is text).

his_config_info  表没有 type 字段，在页面上操作回滚的时候，为直接用历史的配置发布，但是缺失 type 字段，publish 后还原为 text （默认为 text）。

and table `config_info_beta` also does not have a type field.

**Expected behavior**
The rollback configuration also retains the type and restores it.

回滚配置也保留 type 并还原。

**Acutally behavior**
The type field is missing in the rollback configuration, and it will be restored to text after rollback (the default is text).

回滚配置缺失 type 字段，回滚后还原为 text （默认为 text）。

**How to Reproduce**
1. Fix SQL `config_info_beta` and `his_config_info` add `type`
```SQL
ALTER TABLE `config_info_beta`
	ADD COLUMN `type` varchar(64) NULL COMMENT '配置格式';
ALTER TABLE `his_config_info`
  ADD COLUMN `type` varchar(64) NULL COMMENT '配置格式';

```
2.  Fix related SQL operations, data read and write logic.

**Comment by brotherlu-xcq** [comment]
this is an old problem, same to https://github.com/alibaba/nacos/issues/6509

**Comment by CherishCai** [comment]
> this is an old problem, same to #6509

Thanks.
