### ISSUE TITLE
mac big sur 启动nacos失败

### ISSUE THREAD

**Issue by gaojunhuiBS** [alibaba/nacos#6569]
错误日志：
/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/java -Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/ext  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xloggc:/Users/gaojunhui/Downloads/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/gaojunhui/Downloads/nacos/plugins/health,/Users/gaojunhui/Downloads/nacos/plugins/cmdb -Dnacos.home=/Users/gaojunhui/Downloads/nacos -jar /Users/gaojunhui/Downloads/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/Users/gaojunhui/Downloads/nacos/conf/ --logging.config=/Users/gaojunhui/Downloads/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
Error: Unable to access jarfile /Users/gaojunhui/Downloads/nacos/target/nacos-server.jar

**Comment by KomachiSion** [comment]
`Unable to access jarfile /Users/gaojunhui/Downloads/nacos/target/nacos-server.jar` maybe no permission in your system file.
