### ISSUE TITLE
nacos1.4.1配置中心修改自定义config文件导致logback日志输出停止

### ISSUE THREAD

**Issue by WanYanSiR** [alibaba/nacos#6570]
使用nacos1.4.1@RefreshScope、@Value能正常读取到远程配置，修改后能刷新进来读取到最新值，但修改后会导致logback日志停止输出，但logstash收集端能正常收集进来日志信息。本地开发环境刷新正常、日志正常；测试、生产环境刷新正常、日志输出中断。

**Comment by WanYanSiR** [comment]
submit once again

**Comment by wanglin0413** [comment]
spring cloud项目在监听到Refresh Event后，PropertySourceBootstrapConfiguration会重新初始化，这个过程会调用reinitializeLoggingSystem方法，可以看看是不是这里把日志的一些配置覆盖掉了
