### ISSUE TITLE
换了版本还不行呢。控制台一直打印：

### ISSUE THREAD

**Issue by g0123** [alibaba/nacos#6571]
换了版本【2.2.6.RELEASE】还不行呢。控制台一直打印：
17:34:16,638 |-INFO in ReconfigureOnChangeTask(born:1628155576637) - Empty watch file list. Disabling 
17:34:17,912 |-INFO in ReconfigureOnChangeTask(born:1628155277911) - Empty watch file list. Disabling 
17:34:17,940 |-INFO in ReconfigureOnChangeTask(born:1628155277940) - Empty watch file list. Disabling 
17:34:18,070 |-INFO in ReconfigureOnChangeTask(born:1628155278068) - Empty watch file list. Disabling

_Originally posted by @g0123 in https://github.com/alibaba/nacos/issues/3252#issuecomment-893313270_

**Comment by KomachiSion** [comment]
Please move to spring cloud alibaba community

**Comment by ilaotan** [comment]
请参考 配置文件中 <configuration scan="false" scanPeriod="60 seconds" debug="false">的改动  https://github.com/alibaba/nacos/blob/1.4.5/client/src/main/resources/nacos-logback.xml 
https://github.com/alibaba/nacos/blob/develop/client/src/main/resources/nacos-logback.xml
