### ISSUE TITLE
外网无法获取配置

### ISSUE THREAD

**Issue by AoeSyL** [alibaba/nacos#6578]
![image](https://user-images.githubusercontent.com/28856703/128351524-3ebf6494-0004-4a0e-bb17-7524d41b0f4b.png)

![image](https://user-images.githubusercontent.com/28856703/128351648-8f8dbcdd-f207-47f0-88df-e2f0c530e6f2.png)

测试环境在云端  开发环境在本地
更改了nacos ip为外网地址，应用连接nacos  还是只能在测试环境中 获取到配置  本地用公网ip无法获取

**Comment by KomachiSion** [comment]
那说明不是nacos的问题，是你的网络环境的问题。

**Comment by AoeSyL** [comment]
> 那说明不是nacos的问题，是你的网络环境的问题。

需要如何解决呢？正常的http是可以和这个服务器互通的。
