### ISSUE TITLE
Is there any way to change the leader node manually?

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#6579]
When our team restarted the nacos cluster last month, there were heartbeat and long polling failures. My colleague told me that this was caused by restarting the leader node.

If the leader node is shut down, nacos will select a new leader node, which will take some time. During this period, both heartbeat and long polling requests will fail. I know this is fine, but I hope there is any way to change the leader node or manually trigger the nacos cluster to select a new leader.

We want to update nacos server from 1.3.2 to 2.0.3 so I hope get your help, thanks in advance.

上个月，我们团队重启 nacos 集群时，服务出现了抖动，心跳和配置的长轮询失败，我同事说这是她重启leader节点造成的，如果重启 leader 节点，nacos 将会重新选举新的 leader 节点，在这期间，心跳和长轮询会失败，虽然这对业务不会有实际的影响，但是我希望能手动修改或者触发 nacos 集群重新选举。

我们准备将 nacos 从 1.3.2 升级到 2.0.3 ，在我本地实际操作时，重启 leader 节点，的确会抖动，而重启普通节点则不会，希望能帮忙解答下，多谢，如果有钉钉群，麻烦告知，我们团队大规模使用 nacos

**Comment by KomachiSion** [comment]
raft协议只有持久化服务和部分nacos自身元数据使用，和心跳长轮训均无关系。
你说的抖动可能是因为重启节点时，其他节点感知延迟导致的，一般不会超过5s。
