### ISSUE TITLE
为什么要优先获取本地配置

### ISSUE THREAD

**Issue by LBJWt** [alibaba/nacos#6587]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 想问一下为什么配置中心获取配置为什么要优先本地配置，什么场景下会使用这个
2. 
3.

**Comment by MajorHe1** [comment]
你问的是客户端还是服务端？
以及你所说的本地配置，应该是指相对于数据库里面的数据而言，缓存在本地磁盘上的配置信息吧？
如果你问的是服务端，根据我的理解，配置中心应该是 【只用】 本地磁盘的配置，而不是 【优先用】 本地磁盘的配置。
至于原因，我个人猜想是两个方面：
1.保障配置中心不会因为数据库的失效而失效
2.读操作不会访问数据库，提升读操作QPS能力的同时，也不会对数据库的请求频繁而影响数据库

**Comment by LBJWt** [comment]
> 你问的是客户端还是服务端？
> 以及你所说的本地配置，应该是指相对于数据库里面的数据而言，缓存在本地磁盘上的配置信息吧？
> 如果你问的是服务端，根据我的理解，配置中心应该是 【只用】 本地磁盘的配置，而不是 【优先用】 本地磁盘的配置。
> 至于原因，我个人猜想是两个方面：
> 1.保障配置中心不会因为数据库的失效而失效
> 2.读操作不会访问数据库，提升读操作QPS能力的同时，也不会对数据库的请求频繁而影响数据库

是客户端，客户端获取配置
![e900fce1ebeff4b2d6d2d8ce4b90e29](https://user-images.githubusercontent.com/16012187/128483476-ac69b73e-c0b6-4632-aa34-e7314d4107f6.png)， 就是这里第一个，这里的文件一般来说都是空的，我现在的疑问就是这个文件什么时候会生成

**Comment by MajorHe1** [comment]
印象中以前也有用户问过类似的问题。根据我的印象，应该这个文件夹以及里面的文件是需要人工去生成的。
nacos客户端提供这个能力的初衷应该是，在配置中心失联的情况下，给用户提供能力，可以修改配置。
如果配置中心恢复，删除掉这个文件夹即可。

**Comment by LBJWt** [comment]
> 印象中以前也有用户问过类似的问题。根据我的印象，应该这个文件夹以及里面的文件是需要人工去生成的。
> nacos客户端提供这个能力的初衷应该是，在配置中心失联的情况下，给用户提供能力，可以修改配置。
> 如果配置中心恢复，删除掉这个文件夹即可。

这么说可以理解一点，但是这里为什么不用快照呢

**Comment by lpaz010** [comment]
根据MajorHe1老师，觉得这个逻辑就是一个优先级问题：人工干预优先级最高，其次是远程配置中心，最后才是快照。

**Comment by MajorHe1** [comment]
> 这么说可以理解一点，但是这里为什么不用快照呢

正如楼上所言，人工干预的地方和快照是需要进行区分的，快照的本质是远程配置中心内容的一个本地副本，快照是一定存在的，相当于在远程配置中心失联的情况下的兜底方案，但是不一定任何时候都需要人工干预。

**Comment by LBJWt** [comment]
> > 这么说可以理解一点，但是这里为什么不用快照呢
> 
> 正如楼上所言，人工干预的地方和快照是需要进行区分的，快照的本质是远程配置中心内容的一个本地副本，快照是一定存在的，相当于在远程配置中心失联的情况下的兜底方案，但是不一定任何时候都需要人工干预。

明白了，感谢解答
