### ISSUE TITLE
nacos-1.4.2版本自启动了多个进程

### ISSUE THREAD

**Issue by C-Gausse** [alibaba/nacos#6589]
**自启动了多个进程**
即使有正常的进程在跑，还是会自启动多个进程。全部杀掉后还是会自动启动，导致内存资源被占满。
没发现有定时脚本在执行。

**Comment by realJackSun** [comment]
您是用ide启动的么？用IDE可能会开启多个进程。

**Comment by C-Gausse** [comment]
@realJackSun 不是，是在linux上跑的，集群部署。文件夹重新命名后就正常了，但没有发现相关的定时脚本...

**Comment by KomachiSion** [comment]
应该是您环境自身的问题，可能要排查下你们的启动命令了，不是nacos的问题。
