### ISSUE TITLE
一直想问这个问题，为什么在CMD中启动nacos2.0.3时，有的时候非得按鼠标右键，启动进度才往下走呢？

### ISSUE THREAD

**Issue by startjava** [alibaba/nacos#6591]
大家有这种情况吗？？

我使用：
C:\nacos-server-2.0.3\nacos\bin>startup.cmd -m standalone

**Comment by lpaz010** [comment]
以**Windows 10**为例:
**现象描述**：老版本cmd命令窗口默认会开启`快速编辑模式`即`quickEdit mode`功能，一些操作会“暂停”程序导致你所描述现象。
**关闭快速编辑模式方法**：右键“属性”-点击“选项”-去掉勾选“快速编辑模式”，然后重启cmd命令窗。
> 另：新版命令窗PowerShell没有此问题。

**Comment by startjava** [comment]
感谢，解决！这么晚还没有休息啊！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月7日(星期六) 凌晨0:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 一直想问这个问题，为什么在CMD中启动nacos2.0.3时，有的时候非得按鼠标右键，启动进度才往下走呢？ (#6591)





 
以Windows 10为例:
 现象描述：老版本cmd命令窗口默认会开启快速编辑模式即quickEdit mode功能，一些操作会“暂停”程序导致你所描述现象。
 关闭快速编辑模式方法：右键“属性”-点击“选项”-去掉勾选“快速编辑模式”，然后重启cmd命令窗。
  
另：新版命令窗PowerShell没有此问题。
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KomachiSion** [comment]
No nacos problem
