### ISSUE TITLE
[nacos 2.x] nacos 2.x 有没有支持多中心的计划

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#6600]
**Is your feature request related to a problem? Please describe.**
在nacos 1.x生态圈里有nacos sync可以同步多个nacos注册中心之间的注册实例，但是目前版本的nacos 2.x并不支持nacos sync：
nacos sync本质上只是一台nacos client，它首先去订阅一个nacos注册中心的service的事件，收到服务变动通知后从注册中心取得发生变动service的所有实例信息，然后将这些instance重新注册到另一个nacos 注册中心，但是nacos 2.0注册中心并不支持同一个nacos client对同一service进行多个instance注册，我们看到相关的issue： #5863 ，但没有看到有什么进一步的推进计划。
我们想确认一下：
1. nacos2.x和1.x差异很大，在2.x经过充分测试验证前，我们生产环境应该会持续使用1.x一段时间，我们想确认一下1.x的更新还会持续多久?
2. nacos 2.x是否支持多中心? 有支持nacos 2.x的多注册中心之间的实例同步工具吗（商业、开源均可）？

**Comment by zrlw** [comment]
另外提一个建议，建设好nacos-group需要相互协调，对于可能影响到其他开源软件的重大调整，最好是先沟通，再动手，免得相互拆台。

**Comment by KomachiSion** [comment]
1. nacos-sync可以继续使用nacos-client1.x ，nacos2.0server能够兼容。
2. nacos-group是社区化开源，肯定是需要在主干分支发布后做适配，而不是同步。
3. 多中心属于用户的业务架构或部署架构，或者说是解决方案，不属于nacos本身的架构设计。没有什么支持不支持，如果有需要可以通过一些组件帮助你实现，组件你可以自己搞，也可以贡献社区一起搞。
4. nacos社区目前大多数的项目应该都是apache2.0协议，自行了解一下。

**Comment by zrlw** [comment]
我们测试结果确认了nacos-sync社区维护者亲自提出的issue：
”Nacos 2.0 目前只支持一个客户端连接注册一个实例,如果同步多个实例会被覆盖,举例子 服务A有{A1,A2,A3}服务,那么同步到Nacos只会有一个, 后续版本Nacos会进行优化“
https://github.com/nacos-group/nacos-sync/issues/235
讨论问题要以事实为依据吧，你可能比较忙，没时间对问题细节进行验证确认，但是已经被其他社区确认的问题你自己认为不需要修复就关贴是不负责任的。
翻翻这里被关掉的issue，里面很多问题都不是个别情况，也不止一个人反馈过，然而并没有后续。
一个开放发展的开源社区，需要很多有能力、有奉献精神的人共同参与，作为一个社区管理员，更应该有兼收并蓄的胸怀，如果自己的确没有精力和时间，看见issue就烦，那就别强求自己，这样不仅耽误了自己，也会毁了社区的发展。
