### ISSUE TITLE
NACOS 实例问题

### ISSUE THREAD

**Issue by fanqinghui** [alibaba/nacos#6603]
**Describe the bug**
我有一个服务部署在容器里，起了3个实例   (I have a service deployed in the container and have three instances)
<img width="429" alt="1628490589(1)" src="https://user-images.githubusercontent.com/1312707/128667585-fce8826a-184a-48a9-8790-b383692ffea2.png">

但是nacos里，显示了5个实例（but in nacos，show 5 instances ）
<img width="624" alt="1628490633(1)" src="https://user-images.githubusercontent.com/1312707/128667666-d3e7046a-0f69-4414-8037-f5cd205b1d72.png">
<img width="812" alt="1628490658(1)" src="https://user-images.githubusercontent.com/1312707/128667842-f709a3c2-7b75-45d2-9768-bf3e90f63045.png">

目前我只能把不存在的2个实例下线（now i stop that 2 instances）
这个问题我应该怎么排查原因？（ what should I do? ）

nacos is cluster（3 node）

**Comment by fanqinghui** [comment]
help help help

**Comment by QiaChen** [comment]
我也遇到这个问题了，我把所有实例都停掉了，还剩了两个一直在，重启了nacos也，nacos版本2.0.2

**Comment by KomachiSion** [comment]
那说明这两个ip一直在发心跳，自查一下。

可以把nacos-event的debug日志打开，看一下是不是一致发，还不对就netstat看一下连接是不是一直有，抓包看下是不是一直有请求。

**Comment by shaohaikkk** [comment]
> 那说明这两个ip一直在发心跳，自查一下。
> 
> 可以把nacos-event的debug日志打开，看一下是不是一致发，还不对就netstat看一下连接是不是一直有，抓包看下是不是一直有请求。



> 那说明这两个ip一直在发心跳，自查一下。
> 
> 可以把nacos-event的debug日志打开，看一下是不是一致发，还不对就netstat看一下连接是不是一直有，抓包看下是不是一直有请求。

我也遇到了这样的问题，查看了下 nacos-event 确实发现有这种日志，但是查看连接处已经显示的ip 的机器的tcp连接都没有找到

**Comment by KomachiSion** [comment]
look like usage problem, use users check the beats source and solve by themselves.
