### ISSUE TITLE
nacos of sys module application.properties not exist！

### ISSUE THREAD

**Issue by Arlmls** [alibaba/nacos#6606]
**Describe the bug**
sys module application.properties not exist！

**Expected behavior**
add application.properties file

**Acutally behavior**
sys module application.properties not exist！

**How to Reproduce**
![image](https://user-images.githubusercontent.com/23259825/128689431-7da4e4ed-cba2-4af0-b7d9-1a9800f2466d.png)
![image](https://user-images.githubusercontent.com/23259825/128689494-9b9d945e-8920-4dbb-9e62-03dfa260f12c.png)

**Comment by brotherlu-xcq** [comment]
你这个场景是怎么出现的呢？我这边正常启动Nacos没有出现这个问题。

**Comment by KomachiSion** [comment]
why you need application.properties in sys module?

**Comment by KomachiSion** [comment]
maybe you has some misunderstand for this module.
