### ISSUE TITLE
nacos未来版本是否考虑在spring整合中交由spring容器托管(非springmvc容器, 这两个是有区别的)

### ISSUE THREAD

**Issue by yipixiaofeiyang** [alibaba/nacos#6607]
**env info
   spring: 5.3.9
   spring mvc: 5.3.9
   nacos: 2.0.3

**Is your feature request related to a problem? Please describe.**
最近在尝试将nacos整合到已有项目(spring+springmvc)中去, 却发现
1: 将nacos交由spring托管, @NacosValue和@Value都是取不到值的
2: 将nacos交由spring mvc托管, 项目直接报错
3: 将nacos分别spring和spring mvc都托管, 项目可以运行, @NacosValue和@Value都能取到值, 关键点在于 键值更新后@NacosValue还是获取到原来的值

(上述问题, 不存在data-id不存在, 版本问题)

上issue查看了之前各位大神提出的问题, 发现不止我一个碰到这样的问题了, 都被closed, 不知道是出于什么原因, ssm+dubbo的群体其实还是很高的...
注: 如果问题无法复现, 留言,我会提供一份简易, 但完整的demo

**Comment by yipixiaofeiyang** [comment]
spring mvc容器能读取到spring管理的bean, 但是spring却读不到spring mvc管理的bean, 这是个很重要的参考点

**Comment by KomachiSion** [comment]
问题迷惑，你是问nacos服务端是否可以托管吗？ 还是问客户端？

@NacosValue和@value都是取不到值的这些都是客户端的东西，和nacos使用spring mvc有什么关系。

如果是需要托管服务端，那和@NacosValue和@value有啥关系？

**Comment by KomachiSion** [comment]
No response from author and problem is not clearly. So close issue first.
