### ISSUE TITLE
使用startup.sh启动nacos时，如果JAVA_OPT_EXT_FIX变量值为空，将不能正常启动

### ISSUE THREAD

**Issue by yylhbb** [alibaba/nacos#6609]
**Describe the bug**

当变量`$JAVA_OPT_EXT_FIX`的值为空时，执行命令`sh startup.sh -m standalone`，nacos不能正常启动，直接使用`java -jar xxx`却可以正常启动。

![image](https://user-images.githubusercontent.com/35439699/128723538-b516e5bf-e141-42c2-a4a1-dc1e4b9da7f1.png)

**Expected behavior**
执行启动脚本`startup.sh -m standalone`后，nacos应当正常启动。

**Acutally behavior**

执行命令`bin/startup.sh -m standalone`后，查看日志`start.out`，结果如下：
```
[root@yylhbb nacos]# cat logs/start.out 
/usr/java/jdk-16.0.2/bin/java   -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xlog:gc*:file=/usr/local/nacos/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400 -Dloader.path=/usr/local/nacos/plugins/health,/usr/local/nacos/plugins/cmdb -Dnacos.home=/usr/local/nacos -jar /usr/local/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/usr/local/nacos/conf/ --logging.config=/usr/local/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
错误: 找不到或无法加载主类 
原因: java.lang.ClassNotFoundException: 
```
执行命令`sh -x startup.sh`后发现如下现象：

![image](https://user-images.githubusercontent.com/35439699/128725670-60bf24c0-d82d-4222-894e-f955abba7140.png)

**How to Reproduce**
1. 确保JDK版本大于等于9
2. 执行脚本：`sh startup.sh -m standalone`

**Desktop (please complete the following information):**
 - OS: Centos 8 
 - Version：nacos-server 2.0.3
 - Module：nothing
 - SDK：nothing

**Additional context**
修改脚本后，nacos能够通过脚本正常启动，建议使用`${JAVA_OPT_EXT_FIX}`代替`"$JAVA_OPT_EXT_FIX"`

![image](https://user-images.githubusercontent.com/35439699/128727910-30f4434a-8f7e-4c48-b71d-984fd0d14555.png)

**Comment by KomachiSion** [comment]
能试一下改变之后在jdk8下面能否正常运行吗？ 如果也可以正常运行，那就提一个pr修复吧。

**Comment by brotherlu-xcq** [comment]
There are many users reporting this problem recently. I will try to check and resolve it later.

**Comment by brotherlu-xcq** [comment]
I will try to fix it.

**Comment by Q007shi** [comment]
/root/JDK/jdk-17.0.1/bin/java   -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xlog:gc*:file=/root/softWare/nacos/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400 -Dloader.path=/root/softWare/nacos/plugins/health,/root/softWare/nacos/plugins/cmdb -Dnacos.home=/root/softWare/nacos -jar /root/softWare/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/root/softWare/nacos/conf/ --logging.config=/root/softWare/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
错误: 找不到或无法加载主类 
原因: java.lang.ClassNotFoundException:

**Comment by Lin1Yang** [comment]
当我删除Dnacos.member.list 和 Dloader.path程序就可以启动了。但是在目前只能用command的形式启动。

**Comment by Lin1Yang** [comment]
当我复制从-Dnacos.stand 直到524288，然后删除Dnacos.member.list 和 Dloader.path部分，在command中用java+这段信息。 程序就可以启动了。但是在目前只能用command的形式启动。

**Comment by cnlinjie** [comment]
jdk11,报错：Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 


修改 startup.sh 脚本
将执行代码，原：
```
nohup "$JAVA" "$JAVA_OPT_EXT_FIX" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &

```
改为：
```
nohup ${JAVA} ${JAVA_OPT_EXT_FIX} ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
```

其实就是去掉了双引号。

**Comment by cnlinjie** [comment]
jdk11,报错：Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException: 


修改 startup.sh 脚本
将执行代码，原：
```
nohup "$JAVA" "$JAVA_OPT_EXT_FIX" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &

```
改为：
```
nohup ${JAVA} ${JAVA_OPT_EXT_FIX} ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
```

其实就是去掉了双引号。

**Comment by wuma2020** [comment]
> 
mac os 11.3.1 
nacos-server-2.0.3.zip 
openjdk 16 
出现相同问题，按照这个修改可以正常启动了

**Comment by wuma2020** [comment]
> > 
> 
> mac os 11.3.1 nacos-server-2.0.3.zip openjdk 16 出现相同问题，按照这个修改可以正常启动了



> jdk11,报错：Error: Could not find or load main class Caused by: java.lang.ClassNotFoundException:
> 
> 修改 startup.sh 脚本 将执行代码，原：
> 
> ```
> nohup "$JAVA" "$JAVA_OPT_EXT_FIX" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
> ```
> 
> 改为：
> 
> ```
> nohup ${JAVA} ${JAVA_OPT_EXT_FIX} ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
> ```
> 
> 其实就是去掉了双引号。

mac os 11.3.1
nacos-server-2.0.3.zip
openjdk 16
出现相同问题，按照这个修改可以正常启动了

**Comment by Cole4eva123** [comment]
corretto-20
nacos 2.2.3
corretto-20.0.2.1
出现相同问题，修改完还是报找不到或无法加载主类

> 修改

**Comment by Cole4eva123** [comment]
> > > 
> > 
> > 
> > mac os 11.3.1 nacos-server-2.0.3.zip openjdk 16 出现相同问题，按照这个修改可以正常启动了
> 
> > jdk11,报错：Error: Could not find or load main class Caused by: java.lang.ClassNotFoundException:
> > 修改 startup.sh 脚本 将执行代码，原：
> > ```
> > nohup "$JAVA" "$JAVA_OPT_EXT_FIX" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改为：
> > ```
> > nohup ${JAVA} ${JAVA_OPT_EXT_FIX} ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其实就是去掉了双引号。
> 
> mac os 11.3.1 nacos-server-2.0.3.zip openjdk 16 出现相同问题，按照这个修改可以正常启动了

nacos 2.2.3
corretto-20.0.2.1
出现相同问题，修改完还是报找不到或无法加载主类
，JAVA_HOME也配置了

**Comment by Cole4eva123** [comment]
macos  m1
nacos 2.2.3
jdk 20
startup.sh改好后已经不报找不到主类的错误了，但是启动后都是 ${BASE_DIR}/logs/start.out: ambiguous redirect报这个错误是为什么呢

**Comment by whooyun** [comment]
21年的问题，24年了，这。。。。。。。
