### ISSUE TITLE
希望提供增量更新的服务发现能力

### ISSUE THREAD

**Issue by jiangguilong2000** [alibaba/nacos#6610]
这边在用nacos做用服务发现功能遇到个问题：
**需求背景**:是一款游戏项目，多服多区模式，后续会不断开新区，目前是所有的游戏区放在一个叫game的服务中，每个游戏区就是一个实例，用于管理各个区服列表的dir服订阅该服务，监听服务下的实例列表变化。
![image](https://user-images.githubusercontent.com/5009933/128802898-16903b90-e6a0-484c-ac5a-2769813746e3.png)
当某个区的属性（主要是状态）发生变化时，期望的是某个变化的实例(增量推送变化的实例)。
为何不用全量，因为一个游戏大区会有几千个区左右，每天都在不断的开新区，会导致每次同步的都是大量的冗余的数据，这是很没意义的。
代码实现如下：
```java
private void subscribe(String key, Map<Integer, Server> store) {
        try {
            namingService.subscribe(key, key, event -> {
                NamingEvent namingEvent = (NamingEvent) event;
                List<Instance> list = namingEvent.getInstances();
                for (Instance e : list) {
                    Server server = JSONUtils.parseObject(e.getMetadata(), Server.class);
                    store.put(server.getId(), server);
                }
            });
        } catch (NacosException e) {
            logger.error(e.getMessage(), e);
        }
    }
```

实际表现：dir服接收到的是全量的实例列表。
![image](https://user-images.githubusercontent.com/5009933/128802986-f321151e-908f-4e32-80df-973e29d1012f.png)
像如上列表中，只是5666的instance做了更新而已。

**Comment by BlackBAKA** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
For most of situation, the full instance list is more useful. If you need get the changes instances. You can do filter by yourself in listener of out of listener.

**Comment by jiangguilong2000** [comment]
即使我做了listener，接收的数据还是全量的，只是自己再做了下过滤，是这样去实现吧？能否在监听时有个开关属性来告知服务器推送给我全量还是增量的，我们游戏服务器这边instance真心用不到全量的，就像我想要买一个瓜，你非得送我一车瓜一样



---原始邮件---
发件人: "杨翊 ***@***.***&gt;
发送时间: 2021年8月12日(周四) 上午9:56
收件人: ***@***.***&gt;;
抄送: "Allen ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 希望提供增量更新的服务发现能力 (#6610)




 
For most of situation, the full instance list is more useful. If you need get the changes instances. You can do filter by yourself in listener of out of listener.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangguilong2000** [comment]
Even I do filter by yourself in listener of out of listener,at client side, however,I still receive the full amount of data , Isn't  it? Can there be a switch attribute  to tell the server to push me the full amount or incremental when client subscribe? ,as current situation, just like I want to buy a melon, you have to send me a cart of melons.

**Comment by jiangguilong2000** [comment]
Even I do filter by yourself in listener of out of listener,at client side, however,I still receive the full amount of data , Isn't it? Can there be a switch attribute to tell the server to push me the full amount or incremental when client subscribe? ,as current situation, just like I want to buy a melon, you have to send me a cart of melons. @KomachiSion

**Comment by jiangguilong2000** [comment]
Even I do filter by yourself in listener of out of listener,at client side, however,I still receive the full amount of data , Isn't it? Can there be a switch attribute to tell the server to push me the full amount or incremental when client subscribe? ,as current situation, just like I want to buy a melon, you have to send me a cart of melons. @KomachiSion

**Comment by jiangguilong2000** [comment]
> @i will solve it@

yes,this enhancement is what I want. Very Well

**Comment by jiangguilong2000** [comment]
yes,this enhancement is what I want. however,if I only want receive the  modify host （ Set<Instance> modHosts）,  all the host list  (List<Instance> hosts)no need deliver to me @BlackBAKA

**Comment by zrlw** [comment]
哪怕只有一个服务实例发生了变化，nacos servce也会全量推送全部的实例清单给订阅者，如果实例数量很多，比如你这种几千个区的游戏应用，网络带宽和资源消耗都会很大。
nacos目前的设计框架没有考虑服务实例频繁发生变动的场景，你的这种需求不仅要改nacos client，还要改nacos server，属于伤筋动骨性质的改造，还不如去看看其他产品靠谱。

**Comment by jiangguilong2000** [comment]
> 哪怕只有一个服务实例发生了变化，nacos servce也会全量推送全部的实例清单给订阅者，如果实例数量很多，比如你这种几千个区的游戏应用，网络带宽和资源消耗都会很大。
> nacos目前的设计框架没有考虑服务实例频繁发生变动的场景，你的这种需求不仅要改nacos client，还要改nacos server，属于伤筋动骨性质的改造，还不如去看看其他产品靠谱。

谢谢，所以我想的是，订阅时能否加个参数，通过参数服务端决定推送的是增量的还是全量的

**Comment by zrlw** [comment]
你可以把代码下载下来搜一下ServiceChangedEvent，发生实例变动时，nacos服务端会创建这个事件然后交由推送线程去推，但是nacos创建的这个事件里面只有服务名称，并没有发生变动的实例，所以从基础层面上都满足不了你的需求。
实现你要的效果，要重新设计nacos事件处理体系，和重新写一套差不多了，等着社区提供目前看起来不太现实，要么你自己动手改，要么需要去找其他产品了。

**Comment by zrlw** [comment]
如果你用的是dubbo，推荐你看看etcd，dubbo新支持的注册中心，相比于ZK或者nacos， etcd不需要每次子节点变更都重新全量拉取节点数据。

**Comment by zrlw** [comment]
阿里自己的注册中心有你说的功能：
1. 增量推送，服务列表变化之后只推送变化的数据；
2. 首次全量推送采用压缩推送；
3. 频繁变更采用聚合推送
这篇文章有介绍：
https://archsummit.infoq.cn/2020/shenzhen/presentation/2310
不清楚是否单独卖。

**Comment by jiangguilong2000** [comment]
对，就是我们要的功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月12日(周四) 晚上10:03
收件人: ***@***.***&gt;;
抄送: "Allen ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 希望提供增量更新的服务发现能力 (#6610)




 
阿里自己的注册中心有你说的功能：
  
增量推送，服务列表变化之后只推送变化的数据； 

首次全量推送采用压缩推送； 

频繁变更采用聚合推送
 这篇文章有介绍：
 https://archsummit.infoq.cn/2020/shenzhen/presentation/2310
 不清楚是否单独卖。 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zrlw** [comment]
应该就是Nacos对应的商业化产品-微服务引擎（Micro Service Engine），简称 MSE，阿里云上有。

**Comment by zrlw** [comment]
所以这些功能在开源版本的nacos不太可能见到了
