### ISSUE TITLE
有几个问题想咨询下，关于docker部署nacos1.4.2遇到的问题

### ISSUE THREAD

**Issue by summer-a** [alibaba/nacos#6618]
1. 为什么1.4.2从推荐列表移除了？
2. 官方docker配置中没有开放7848端口，这个端口是用于选举的吗？我用官方案例选举失败，开放后成功。
3. 访问api提示caused: old raft protocol already stop;
4. 这几天有个项目，没有改动什么代码，但是在启动时获取到的nacos配置并不是该项目的配置，导致启动失败。

环境：Docker部署1.4.2版本的nacos

**Comment by KomachiSion** [comment]
1. 社区将主要演进2.0版本，1.X版本不再增加新功能，仅对一些bug进行fix，因此不再推荐使用
2. 可以提issue到nacos-docker中
3. 1.3开始使用jraft代替自研raft。jraft启动后自研raft会关闭，调用会出现如上报错，忽略即可。
4. 需要自查下nacos服务端配置是否正确，检查下服务端是否dump到新数据，客户端是否获取到新数据。
