### ISSUE TITLE
直接更改nacos数据库的content值，多长时间后生效

### ISSUE THREAD

**Issue by childewuque** [alibaba/nacos#6621]
nacos作为配置中心时
并且md5等其他字段没有改

接口nacos/v1/cs/configs，以及ui
时间好像不是固定的，因为不了解nacos server的缓存机制，所以求教

偶尔有批量更改的需求，通过sql更改方便

**Comment by MajorHe1** [comment]
搜 DumpService.java 看源码，你就能得到想要的答案。
几个关键点：

**Comment by childewuque** [comment]
> 搜 DumpService.java 看源码，你就能得到想要的答案。
> 几个关键点：
> 1.nacos server 从数据库里面更新配置，6小时一次。本质上就不是增量更新，而是全量dump。
> 2.客户端用的配置发现的接口，跟控制台ui访问的接口，不是同一个接口。客户端配置发现的接口，访问的数据是nacos-server的本地文件缓存。 控制台ui访问的数据，是直接访问的数据库，两者是不一致的。
> 3.通过sql直接改数据库是很危险的行为，不建议使用。

多谢！
下了源码查看，确实
直接改数据库主要是批量改项目配置，项目几千个。偶尔为之，DBA备份操作

**Comment by MajorHe1** [comment]
> 多谢！
> 下了源码查看，确实
> 直接改数据库主要是批量改项目配置，项目几千个。偶尔为之，DBA备份操作
没有更多问题了的话，可以关闭ISSUE 
: )
