### ISSUE TITLE
problems with the startup script

### ISSUE THREAD

**Issue by pirateskipper** [alibaba/nacos#6623]
**Describe the bug**
Start the script error under jdk8 according to the official website（https://nacos.io/zh-cn/docs/quick-start.html）

- `sh startup.sh -m standalone`

**Acutally behavior**

- `错误: 找不到或无法加载主类
原因: java.lang.ClassNotFoundException:`

**Expected behavior**

**How to Reproduce**

- `sh startup.sh -m standalone`
- `cat start.out`

**Desktop (please complete the following information):**
 - OS: [mac 11.1]
 - Version [nacos-server:2.0.3]
 - Module [noting]
 - SDK [1.8]

**Additional context**

**Comment by KomachiSion** [comment]
I can't reproduce your problem, maybe your env has problem.

**Comment by KomachiSion** [comment]
No response from author, should be users' env problem.
