### ISSUE TITLE
[控制台Bug]配置管理-配置列表, 增加搜索条件后, 切换配置空间, 搜索条件还在, 但是搜索结果不对

### ISSUE THREAD

**Issue by yipixiaofeiyang** [alibaba/nacos#6625]
![1628666853(1)](https://user-images.githubusercontent.com/49892927/128987873-117958b1-e9bf-4617-a491-5b66b6dba151.png)

**Comment by myifeng** [comment]
You can use * for fuzzy search, the default is to match all. 

The search criteria have actually been cleared when the space is switched, but the page is still displayed. I think this is a bug!

I don't know whether to keep search criteria when switching namespaces. 
If you don’t keep it, I think the problem should lie here:  replace `defaultValue`with `value`

https://github.com/alibaba/nacos/blob/46c1f7e6df711ac000a74435ac13214201afad9b/console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js#L1135

If you want to keep it, I think the search criteria should be in the url.

Before switching namespace:

![image](https://user-images.githubusercontent.com/26652657/129007211-297cac65-ac29-4369-bdc2-eb6457370eb8.png)

After switching namespace:

![image](https://user-images.githubusercontent.com/26652657/129007559-b35f3e2e-4a59-41ff-917e-105dd599673b.png)

**Comment by myifeng** [comment]
Looking forward to the maintainer's reply, I think I can fix this problem!
