### ISSUE TITLE
客户端设置 cacheData.setUseLocalConfigInfo(true)是不是多余了

### ISSUE THREAD

**Issue by wy1689979008** [alibaba/nacos#6627]
![image](https://user-images.githubusercontent.com/48091964/128995372-37174f3b-9dd8-43e2-a4e2-a0f8548ab30f.png)
 if (cacheData.isUseLocalConfigInfo() && path.exists() && cacheData.getLocalConfigInfoVersion() != path
                .lastModified()) {
            String content = LocalConfigInfoProcessor.getFailover(agent.getName(), dataId, group, tenant);
            final String md5 = MD5Utils.md5Hex(content, Constants.ENCODE);
            cacheData.setUseLocalConfigInfo(true);
            cacheData.setLocalConfigInfoVersion(path.lastModified());
            cacheData.setContent(content);
            LOGGER.warn(
                    "[{}] [failover-change] failover file changed. dataId={}, group={}, tenant={}, md5={}, content={}",
                    agent.getName(), dataId, group, tenant, md5, ContentUtils.truncateContent(content));
        }
你好，这里已经判断是本地配置了，再设置一次是不是多余了，请问是基于什么考虑呢

**Comment by wy1689979008** [comment]
而且这里实际上MD5值已经改变了，为什么不在这里面直接调用safeNotifyListener方法呢？

**Comment by pengten** [comment]
checkLocalConfig这个方法没有被使用，感觉应该删除了。
@KomachiSion 可以的话，我很乐意处理该问题。
