### ISSUE TITLE
Remove redundant functional interfaces

### ISSUE THREAD

**Issue by hunjipo** [alibaba/nacos#6628]
**Is your feature request related to a problem? Please describe.**
In nacos-common moudle, there are two functional interfaces is `BiFunction` and `BiConsumer.` They are all copied from jdk8 or Apache Commons. I guess these functional interfaces were created because nacos used a JDK version lower than 8, but we wanted to use functional interfaces. But now, nacos depends on the JDK version. The minimum requirement is 8. Therefore, we can delete these interfaces and use the interfaces provided by JDK.

**Describe the solution you'd like**

Can I mention a PR to delete these interfaces?

**Describe alternatives you've considered**

**Additional context**

**Comment by BlackBAKA** [comment]
@i will solve it@
