### ISSUE TITLE
kubernetes delopy nacos cluster error

### ISSUE THREAD

**Issue by yangkangwei** [alibaba/nacos#6630]
kubernetes yaml  file :
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.db.name: "nacos_config"
  mysql.db.host: "rm-xxx.mysql.rds.aliyuncs.com"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "root"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8snacos
          imagePullPolicy: Always
          image: nacos/nacos-server:1.4.1
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos

################
Deployment succeeded

The leader changes from side to side
![image](https://user-images.githubusercontent.com/35650198/129015112-c55541e6-65f6-4499-91d8-2db81bbdf160.png)

Idea console error
![7193636492e9448fc3db846c4d8d2e6](https://user-images.githubusercontent.com/35650198/129015022-f355d8da-0df3-4873-849d-cbbeec4f6379.png)

**Comment by kevinw66** [comment]
参考这个试试，7848端口应该是必开的吧，还有环境变量好像有个版本从`NACOS_SERVER_PORT`改成了`NACOS_APPLICATION_PORT`，所以这边是两个都配置的
https://github.com/nacos-group/nacos-k8s/blob/c71147c8afcd7a7597bc66225a72cd8f631b64dd/deploy/nacos/nacos-quick-start.yaml

**Comment by KomachiSion** [comment]
No more response from author, so this problem might be solved.
