### ISSUE TITLE
为什么我打的包这么小

### ISSUE THREAD

**Issue by lulg** [alibaba/nacos#6635]
![image](https://user-images.githubusercontent.com/28698352/129126563-0e9dbb20-de6a-4f90-9b9f-3b79579be5c9.png)
我自己打的nacos-client包，只有253kb，官方的包确有14M
![image](https://user-images.githubusercontent.com/28698352/129127381-c818d562-7bc2-4b1f-badb-b3721c6d0e78.png)

是我自己打的命令错了吗？
我的命令  
mvn -Prelease-client -DskipTests clean package -U -Dcheckstyle.skip=true

**Comment by myifeng** [comment]
me too，253kb

**Comment by KomachiSion** [comment]
mvn clean install -Prelease-nacos -U -Dmaven.test.skip=true 

你们打出的包其实没有问题，只是没有shade grpc相关的内容，可能会出现grpc的依赖冲突，需要自行解决。
