### ISSUE TITLE
centos 7  openjdk 11 启动 Nacos 2.0.3 启动报错

### ISSUE THREAD

**Issue by c5p0** [alibaba/nacos#6647]
/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el8_4.x86_64/bin/java   -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xlog:gc*:file=/usr/local/nacos/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400 -Dloader.path=/usr/local/nacos/plugins/health,/usr/local/nacos/plugins/cmdb -Dnacos.home=/usr/local/nacos -jar /usr/local/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/usr/local/nacos/conf/ --logging.config=/usr/local/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

Error: Could not find or load main class 
Caused by: java.lang.ClassNotFoundException:

**Comment by superbing09** [comment]
maybe you can try jdk8

**Comment by illeagalName** [comment]
I had the same problem

**Comment by brotherlu-xcq** [comment]
duplicate with https://github.com/alibaba/nacos/issues/6609
