### ISSUE TITLE
About nacOS share configuration....NACOS配置中心共享配置相关问题

### ISSUE THREAD

**Issue by xiaopangzhi795** [alibaba/nacos#6648]
- 配置项
`spring.cloud.nacos.config.shared-configs[0].data-id`
- 问题
该配置配置完成后，无法获取到共享配置。
执行顺序：
1.获取sharedConfigs
com.alibaba.cloud.nacos.NacosConfigProperties#getSharedConfigs获取null值
2.加载配置文件
com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder#loadNacosData
3.才去设置sharedConfigs
com.alibaba.cloud.nacos.NacosConfigProperties#setSharedConfigs

ps：
- 只有共享配置无法读取，nacos-config-dev.properties可以正常读取出来，并且成功运行
- dataid是正确的
- 分组是默认的
- 除了共享配置导致异常之外，其他应用均无异常，新建的spring boot项目
- nacos配置是OK的，配置创建方式和nacos-config-dev.properties一样
- 配置文件中的配置是存在的

nacos-config.properties | DEFAULT_GROUP |   | 详情\|示例代码\|编辑\|删除\|更多
nacos-commons.properties | DEFAULT_GROUP |   | 详情\|示例代码\|编辑\|删除\|更多

也可能是我的配置导致了该问题，如果有什么不对，麻烦指出一下，非常感谢。

测试版本：2.2.5.RELEASE & 2.2.6.RELEASE
下面是我的配置

```
//配置文件
spring.application.name=nacos-config

spring.profiles.active=dev

spring.cloud.nacos.config.server-addr=localhost:8848
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.refresh-enabled=true
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos

spring.cloud.nacos.config.shared-configs[0].data-id=nacos-commons.properties

//获取方式
```
@RestController
@Reference
public class ConfigAPI {

    @Value("${config.name}")
    private String configName;   //nacos-config-dev.properties 读取正常

    @Value("${config.commons}")
    private String configCommons;   //nacos-commons.properties  读取失败
    ....
}

**Comment by xiaopangzhi795** [comment]
已经解决：配置文件名字，必须得是bootstrap才可以，bootstrap.properties 或者 bootstrap.yml。

**Comment by zhuqingshen** [comment]
可以告诉下Spring boot的版本吗
