### ISSUE TITLE
The namespace is configured in the service discovery, but the filtering error is selected in the management interface after the service is registered.

### ISSUE THREAD

**Issue by dengyao** [alibaba/nacos#665]
在服务发现里面配置了namespace但是服务注册上后在管理界面选择通过那么namespace选择筛选服务无效，注册的服务在任何一个namespace下都能看到

**Comment by nkorange** [comment]
@dengyao Paste your code please.

**Comment by nkorange** [comment]
Namespace for service discovery is supported in Nacos 0.8.0

**Comment by yiminyangguang520** [comment]
yes，I meet the same problem, nacos server is 0.9.0, spring-cloud-starter-alibaba-nacos-discovery 0.2.1.RELEASE, can you help me ?
