### ISSUE TITLE
why SDK still invoke NamingProxy.queryList 

### ISSUE THREAD

**Issue by inkinworld** [alibaba/nacos#6659]
## Issue Description

Type: *bug*

### Describe what happened (or what feature you want)
after upd push update sdk cache, why still invoke NamingProxy.queryList.

com.alibaba.nacos.client.naming.core.HostReactor UpdateTask#run

```
                if (serviceObj.getLastRefTime() <= lastRefTime) {
                    updateService(serviceName, clusters);
                    serviceObj = serviceInfoMap.get(ServiceInfo.getKey(serviceName, clusters));
                } else {
                    // if serviceName already updated by push, we should not override it
                    // since the push data may be different from pull through force push
                    refreshOnly(serviceName, clusters);
                }
```

### Describe what you expected to happen
skip NamingProxy.queryList  invoke

**Comment by KomachiSion** [comment]
UDP is not stable, it maybe fail. So need another way to make sure the data can be updated.

**Comment by inkinworld** [comment]
> UDP is not stable, it maybe fail. So need another way to make sure the data can be updated.

but refreshOnly(serviceName, clusters) not update local cache, it just send http request then ignore response.
