### ISSUE TITLE
JDK11启动nacos

### ISSUE THREAD

**Issue by illeagalName** [alibaba/nacos#6662]
jdk11下启动nacos(2.0.3)出现错误：
错误: 找不到或无法加载主类
原因: java.lang.ClassNotFoundException:

**Comment by karluto** [comment]
我也有这个问题，mac 10.15.7  jdk11

**Comment by LonePheasantWarrior** [comment]
我也有这个问题，Ubuntu 20.04.2 LTS

**Comment by pirateskipper** [comment]
Version: 2.0.3 
jdk version: 11.0.10
os: mac 11.1

How to Reproduce：
- Modify the startup script（startup.sh）
- The original script is: nohup "$JAVA" "$JAVA_OPT_EXT_FIX" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &
- Try the modified script is : nohup ${JAVA} ${JAVA_OPT_EXT_FIX} ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &

others:
- If the build command is mvn clean compile && mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U.and the parameter path("${JAVA_OPT} -jar ${BASE_DIR}/target/${SERVER}.jar") in the script is inconsistent with the actual path,and The actual build path is ("${JAVA_OPT} -jar ${BASE_DIR}/target/${PROJECT_VERSION}/target/${SERVER}.jar").

**Comment by 379464828** [comment]
Under bin / startup.sh
JAVA_ OPT_ EXT_ FIX configuration will cause JDK11 error

please replace bin / startup.sh

x JAVA_ OPT_ EXT_ FIX="-Djava.ext.dirs=${JAVA_ HOME}/jre/lib/ext:${JAVA_ HOME}/lib/ext"
√ JAVA_ OPT="${JAVA_ OPT} -Djava.ext.dirs=${JAVA_ HOME}/jre/lib/ext:${JAVA_ HOME}/lib/ext"

x echo "$JAVA $JAVA_ OPT_ EXT_ FIX ${JAVA_ OPT}"
√ echo "$JAVA ${JAVA_ OPT}"

x echo "$JAVA $JAVA_ OPT_ EXT_ FIX ${JAVA_ OPT}" > ${BASE_ DIR}/logs/start.out 2>&1 &
x nohup "$JAVA" "$JAVA_ OPT_ EXT_ FIX" ${JAVA_ OPT} nacos.nacos >> ${BASE_ DIR}/logs/start.out 2>&1 &
√ echo "$JAVA ${JAVA_ OPT}" > ${BASE_ DIR}/logs/start.out 2>&1 &
√ nohup $JAVA ${JAVA_ OPT} nacos.nacos >> ${BASE_ DIR}/logs/start.out 2>&1 &

**Comment by brotherlu-xcq** [comment]
duplicate with https://github.com/alibaba/nacos/issues/6609
