### ISSUE TITLE
!-- Here is for bug reports and feature requests ONLY! 

### ISSUE THREAD

**Issue by paruza89** [alibaba/nacos#6665]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by paruza89** [comment]
Duplicate of #

**Comment by paruza89** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by paruza89** [comment]
!-- Here is for bug reports and feature requests ONLY!

**Comment by KomachiSion** [comment]
Did you help github test issue feature?
