### ISSUE TITLE
Under bin / startup.sh   JAVA_ OPT_ EXT_ FIX configuration will cause JDK11 error!!!!!!

### ISSUE THREAD

**Issue by 379464828** [alibaba/nacos#6671]
Under bin / startup.sh
JAVA_ OPT_ EXT_ FIX configuration will cause JDK11 error

please replace!!!!

x JAVA_ OPT_ EXT_ FIX="-Djava.ext.dirs=${JAVA_ HOME}/jre/lib/ext:${JAVA_ HOME}/lib/ext"
√ JAVA_ OPT="${JAVA_ OPT} -Djava.ext.dirs=${JAVA_ HOME}/jre/lib/ext:${JAVA_ HOME}/lib/ext"

x echo "$JAVA $JAVA_ OPT_ EXT_ FIX ${JAVA_ OPT}"
√ echo "$JAVA ${JAVA_ OPT}"

x echo "$JAVA $JAVA_ OPT_ EXT_ FIX ${JAVA_ OPT}" > ${BASE_ DIR}/logs/start.out 2>&1 &
x nohup "$JAVA" "$JAVA_ OPT_ EXT_ FIX" ${JAVA_ OPT} nacos.nacos >> ${BASE_ DIR}/logs/start.out 2>&1 &
√ echo "$JAVA ${JAVA_ OPT}" > ${BASE_ DIR}/logs/start.out 2>&1 &
√ nohup $JAVA ${JAVA_ OPT} nacos.nacos >> ${BASE_ DIR}/logs/start.out 2>&1 &

**Comment by brotherlu-xcq** [comment]
duplicate with https://github.com/alibaba/nacos/issues/6609
