### ISSUE TITLE
k8s集群外部使用nacos报错

### ISSUE THREAD

**Issue by shixinghong** [alibaba/nacos#6678]
: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)

如上报错 

使用的版本是nacos2.0.3
如果我想在集群外部使用nacos 是不是同时需要暴露8848和9848 这两个端口 是否可以禁用grpc呢？

**Comment by realJackSun** [comment]
不需要，只暴露8848即可，9848是集群间通信的接口，不需要手动暴露

**Comment by shixinghong** [comment]
> 不需要，只暴露8848即可，9848是集群间通信的接口，不需要手动暴露

嗯嗯 谢谢 可能是调用的时候哪里出来问题

**Comment by zhiqiangjia** [comment]
@shixinghong   请问你是如何解决的？
