### ISSUE TITLE
NACOS1.4.2集成dubbo2.7.12，客户端调用服务接口会调用到非指定命名空间下的同名服务

### ISSUE THREAD

**Issue by gfgfggf1988** [alibaba/nacos#6679]
dubbo客户端运行期间，在nacos控制台手动点击调用的dubbo服务下线后再上线，nacos1.4.2版本的dubbo客户端会调用到非编码指定的dubbo服务接口
【测试环境配置】
----nacos本地单机服务中心：1.4.2 
----dubbo服务端应用：dubbo2.7.12+nacos 1.4.2 * 2
----dubbo客户端应用：dubbo2.7.12+nacos1.4.2与dubbo2.7.12+nacos1.3.2
【正确效果 dubbo2.7.12+nacos1.3.2环境】
![image](https://user-images.githubusercontent.com/16377180/129545298-7a66830b-44fa-4121-8fdf-e16c9d8e807d.png)
【异常效果 dubbo2.7.12+nacos1.4.2环境】
![image](https://user-images.githubusercontent.com/16377180/129545835-c9796708-fe1d-4fa0-95e3-9a87e5f50c8d.png)
【操作过程】
1.分别在nacos中注册两个含有dubbo服务接口的应用，并且该接口中相同的show方法返回值不同。
   N1返回值是custom-DemoService show
   N2返回值是DemoService show
![image](https://user-images.githubusercontent.com/16377180/129543583-4496936f-4dca-4aae-a253-4f6cb6953080.png)
![image](https://user-images.githubusercontent.com/16377180/129543297-42841497-63ed-4f81-8cbe-35b677199a59.png)
2.本地分别启动不同nacos版本的dubbo客户端应用
其中dubbo服务获取与调用使用编码方式
![image](https://user-images.githubusercontent.com/16377180/129543914-432af4a0-b8ef-4ee6-8c2b-4da7fa07fdd4.png)
3.本地先循环调用两次dubbo服务后，在nacos控制台下线n2命名空间下的demoService服务。客户端再执行两次后，上线该服务，此时存在调用异常
【核心代码】
DubboUtil的getReference方法，返回ReferenceConfig对象通过 ReferenceConfigCache.getCache(cacheName).get(reference)方式
![image](https://user-images.githubusercontent.com/16377180/129544324-935b1c53-2754-4443-b32c-67c73bcbc29c.png)
【怀疑代码】
目前怀疑nacos高版本的DefaultPublisher类在nacos服务端下线服务时，调用notifySubscriber方法发出通知。被AbstractDirectory实现类接受该通知并处理时缓存更新存在bug

**Comment by gfgfggf1988** [comment]
@realJackSun 有新的进展么？

**Comment by gfgfggf1988** [comment]
@KomachiSion 有空处理该问题么？

**Comment by KomachiSion** [comment]
你贴出的代码都是dubbo的代码，能否给出${user.home}/logs/nacos/naming.log 中的信息，看一下这个服务什么时间点收到的地址列表，列表是否正确。

如果正确的话请将问题移交至dubbo社区。

**Comment by HTFX-Cloud** [comment]
> 你贴出的代码都是dubbo的代码，能否给出${user.home}/logs/nacos/naming.log 中的信息，看一下这个服务什么时间点收到的地址列表，列表是否正确。
> 
> 如果正确的话请将问题移交至dubbo社区。

检查了一下naming.log，似乎看不初什么问题。跟踪了一下nacos 1.4.2的源码
1.dubbo会根据多个命名空间创建不同的namingservice，并给DefaultPublisher添加Subscriber
【堆栈信息如下】
Thread [main] (Suspended (breakpoint at line 131 in DefaultPublisher))	
	owns: ReferenceConfig<T>  (id=113)	
	owns: ConcurrentHashMap$ReservationNode<K,V>  (id=62)	
	DefaultPublisher.addSubscriber(Subscriber) line: 131	
	NotifyCenter.addSubscriber(Subscriber, Class<Event>) line: 211	
	NotifyCenter.registerSubscriber(Subscriber) line: 194	
	HostReactor.<init>(NamingProxy, BeatReactor, String, boolean, boolean, int) line: 119	
	NacosNamingService.init(Properties) line: 96	
	NacosNamingService.<init>(Properties) line: 81	
	NativeConstructorAccessorImpl.newInstance0(Constructor<?>, Object[]) line: not available [native method]	
	NativeConstructorAccessorImpl.newInstance(Object[]) line: 62	
	DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45	
	Constructor<T>.newInstance(Object...) line: 423	
	NamingFactory.createNamingService(Properties) line: 60	
	NacosFactory.createNamingService(Properties) line: 77	
	NacosNamingServiceUtils.createNamingService(URL) line: 112	
	NacosRegistryFactory.createRegistry(URL) line: 54	
	NacosRegistryFactory(AbstractRegistryFactory).getRegistry(URL) line: 154	
	RegistryFactoryWrapper.getRegistry(URL) line: 34	
	RegistryFactory$Adaptive.getRegistry(URL) line: not available	
	InterfaceCompatibleRegistryProtocol(RegistryProtocol).getRegistry(URL) line: 366	
	InterfaceCompatibleRegistryProtocol(RegistryProtocol).refer(Class<T>, URL) line: 462	
	ProtocolListenerWrapper.refer(Class<T>, URL) line: 72	
	ProtocolFilterWrapper.refer(Class<T>, URL) line: 81	
	QosProtocolWrapper.refer(Class<T>, URL) line: 73	
	Protocol$Adaptive.refer(Class, URL) line: not available	
	ReferenceConfig<T>.createProxy(Map<String,String>) line: 378	
	ReferenceConfig<T>.init() line: 313	
	ReferenceConfig<T>.get() line: 206	
	ReferenceConfigCache.lambda$3(ReferenceConfigBase, String, String) line: 111	
	173259631.apply(Object) line: not available	
	ConcurrentHashMap<K,V>.computeIfAbsent(K, Function<? super K,? extends V>) line: 1660	
	ReferenceConfigCache.get(ReferenceConfigBase<T>) line: 110	
	DubboUtil.getReference(boolean, String, String, String, String, String, Class<T>, String, Integer, String) line: 425	
	DubboUtil.getReference(String, String, String, String, String, Class<T>, Integer, String) line: 171	
	DubboUtil.getReference(String, String, String, Class<T>, String) line: 114	
	Task.run() line: 22	
	Test.main(String[]) line: 41	
2.当nacos控制台中点击服务上、下线操作，DefaultPublisher会给所有的subscriber发送namingevent，导致所有的subscriber都会对同一个event做出反应，导致之前汇报的问题现状。
【堆栈信息如下】
Daemon Thread [nacos.publisher-com.alibaba.nacos.client.naming.event.InstancesChangeEvent] (Suspended)	
	NacosRegistry(AbstractRegistry).notify(URL, NotifyListener, List<URL>) line: 409	
	NacosRegistry(FailbackRegistry).doNotify(URL, NotifyListener, List<URL>) line: 372	
	NacosRegistry(FailbackRegistry).notify(URL, NotifyListener, List<URL>) line: 364	
	NacosRegistry.notifySubscriber(URL, NotifyListener, Collection<Instance>) line: 534	
	NacosRegistry.lambda$subscribeEventListener$10(URL, String, NotifyListener, Event) line: 512	
	1678856266.onEvent(Event) line: not available	
	InstancesChangeNotifier.onEvent(InstancesChangeEvent) line: 125	
	InstancesChangeNotifier.onEvent(Event) line: 39	
	DefaultPublisher$1.run() line: 198	
	DefaultPublisher.notifySubscriber(Subscriber, Event) line: 208	
	DefaultPublisher.receiveEvent(Event) line: 186	
	DefaultPublisher.openEventHandler() line: 117	
	DefaultPublisher.run() line: 94	
3.本地尝试进行了模拟，如图所示。服务的event与namingservice不能一一对应
![image](https://user-images.githubusercontent.com/89976406/132441838-e3c976e4-4f42-4b16-b456-5ff4949c3e8d.png)

跟踪nacos1.3.2的源码发现，
2 的事件通知堆栈信息如下，
Daemon Thread [com.alibaba.nacos.naming.client.listener] (Suspended (breakpoint at line 499 in NacosRegistry))	
	NacosRegistry.lambda$subscribeEventListener$10(URL, String, NotifyListener, Event) line: 499	
	535910992.onEvent(Event) line: not available	
	EventDispatcher$Notifier.run() line: 177	
	ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1149	
	ThreadPoolExecutor$Worker.run() line: 624	
	Thread.run() line: 748	
本地使用同样测试代码，nacos1.3.2客户端模拟，如图所示。可以保证服务的event与namingservice可以一一对应
![image](https://user-images.githubusercontent.com/89976406/132442233-69c3062f-2b35-498c-82cc-1e81cc3ecfe0.png)

**Comment by HTFX-Cloud** [comment]
目前不清楚，nacos1.4.2这个客户端是bug还是就是这样的设计。要是namingevent是给所有的Subscriber都发送通知，那我们需要对客户端做改造，并且把该问题汇报给dubbo社区寻求帮助。望答复

**Comment by HTFX-Cloud** [comment]
@KomachiSion @realJackSun 求关注该问题
