### ISSUE TITLE
前端页面显示：内部系统，不可暴露到公网

### ISSUE THREAD

**Issue by gzwxh** [alibaba/nacos#6683]
**Describe the bug**

**Expected behavior**
If the same configuration file is started on different servers, the front-end pages displayed are inconsistent
Display "internal system, not exposed to the public network"

**Acutally behavior**
commonly

**How to Reproduce**
Deploy according to the document
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html

**Desktop (please complete the following information):**
 - OS:Centos7
 - Version nacos-server 2.0.3

就按照官网的文档：https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html 进行部署按照，结果再不同的内网IP地址段，显示不一样。
172.16.X.X 不显示    内部系统，不可暴露到公网
10.10.X.X   就会显示 ：内部系统，不可暴露到公网

**Comment by bobo325** [comment]
我看公司这边测试环境nacos好像也有这样的显示

**Comment by KomachiSion** [comment]
new version will show this hint. old version without, you can refresh you browser cache and retry.

**Comment by rainbowyao** [comment]
> new version will show this hint. old version without, you can refresh you browser cache and retry.

能不能提示下是那个版本开始增加这个提示语的？
