### ISSUE TITLE
单节点非临时实例重启后丢失

### ISSUE THREAD

**Issue by ld000** [alibaba/nacos#6684]
**Describe the bug**
在单节点nacos中注册非临时实例，在JRaft快照生成后重启nacos，实例信息会丢失。

Register a non-temporary instance in single-node nacos, and restart nacos after the JRaft snapshot is generated, the instance information will be lost.

**How to Reproduce**
1.open api 创建非临时实例
2.等待快照生成
3.重启nacos服务
4.页面上只剩下service，instance信息丢失

1.open api creates a non-temporary instance
2.Wait for the snapshot to be generated
3.Restart nacos service
4.Only service is left on the page, and the instance information is lost

**Desktop (please complete the following information):**
 - OS: Centos
 - Version nacos 2.0.1
 - Module naming

**Comment by brotherlu-xcq** [comment]
我试了一下，本地没有复现到你说的问题。你的openAPI的请求参数这些可以贴一下吗？

**Comment by ld000** [comment]
> 我试了一下，本地没有复现到你说的问题。你的openAPI的请求参数这些可以贴一下吗？

curl -X POST "http://localhost:8848/nacos/v1/ns/instance?ip=192.168.2.1&port=7002&enabled=true&healthy=true&serviceName=abc&groupName=testg&ephemeral=false"

**Comment by ld000** [comment]
> 我试了一下，本地没有复现到你说的问题。你的openAPI的请求参数这些可以贴一下吗？

页面上的实例数量都未0
![image](https://user-images.githubusercontent.com/10431666/129722615-62c91dcd-3cea-4bee-bea3-d0c2ee6af991.png)

**Comment by 474420502** [comment]
@ld000  果然, 我之前掉失一次. 全部数据掉失. 而且我看到不少issue掉失的.

**Comment by ld000** [comment]
我看了下，快照中的信息是全的，好像没有问题。但是加载快照的时候，只重加载了 `ServiceManager` 和 `PersistentIpPortClientManager`。接口和自动清除service任务等读取的indexs缓存都是空的。不知道这些缓存的关系是什么，在`IpPortBasedClient`类`loadClientSyncData`方法中重建instance缓存是否可以修复？

**Comment by KomachiSion** [comment]
升级到2.0.3试试， 应该是旧版本的问题。

**Comment by KomachiSion** [comment]
fixed by #5782
