### ISSUE TITLE
Why is it allowed to submit configuration with syntax errors？

### ISSUE THREAD

**Issue by VivienZhai** [alibaba/nacos#6687]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)
Why is it allowed to submit configuration with syntax errors？

**Comment by Spectature** [comment]
@jameslcj This is the association modification [#337](https://github.com/alibaba/nacos/issues/337)

**Comment by KomachiSion** [comment]
Whether configuration syntax was, they just are some `String` for nacos server. Submit `String` to server and saved in database, then get from database and send `String` to console or sdk.

In console, nacos has weak hint in editor, for application, you should check the config in your applications.
