### ISSUE TITLE
nacos配置管理监听查询为空

### ISSUE THREAD

**Issue by zhaofengcumt** [alibaba/nacos#6689]
版本：2.0.3
启动方式：standalone
现象：应用可以正常获取配置，且配置能够动态更新，但是监听查询为空：
![image](https://user-images.githubusercontent.com/30680275/129829403-2c6802cb-627a-495d-be8a-79336ca29235.png)

**Comment by 474420502** [comment]
@zhaofengcumt standalone 这个模式我试过非法关闭后数据掉失的, 缓存的数据不要放在/tmp文件夹.

**Comment by zhaofengcumt** [comment]
我没有关闭，启动后就一直没有

**Comment by 474420502** [comment]
@zhaofengcumt 坦白说nacos非常不稳定. 其他bug可以接受. 掉数据莫名其妙的, 我以后用回appollo了. 估计他们没随机测试和压测范围不到位. 工程太欠缺稳定了.

**Comment by zarkzheng** [comment]
从你提供的图片里看，你没有设置Data ID和Group信息，所以是获取不到对应的监听数据的。

**Comment by zarkzheng** [comment]
@474420502 Standalone Mode数据源也分Embedded Storage和External Storage，你说的数据丢失具体是指什么？或者你可以提一个issue详细描述一下你说的问题。

**Comment by 474420502** [comment]
@zarkzheng  https://github.com/alibaba/nacos/issues/4544

**Comment by 474420502** [comment]
@zarkzheng  
官方首页standalone启动, 而且日志不难看, 后面一直重复. 数量就那么多. 竟然还要关闭issue.  
如果我全部日志给,都嫌弃太多的话, 其他无能为力, 东西不是我写的,  我整理不了什么给你们, 现在更加整理不了时间太久.
问题就是很简单, 忽然挂了, 数据一点都找不回.  凭一些历史记录. 我一点点手动打回了. 
现在我都是每几分钟备份配置一次. 这个系统改动太麻烦.

**Comment by zarkzheng** [comment]
你能提供一下你当时的`application.properties`配置文件里的`db.num`对应的值吗？
因为看你日志里，确实是有`[db-load-error]load jdbc.properties error`和`db.num is null`对应的错误日志。
```
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; 
nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
```

**Comment by zarkzheng** [comment]
@474420502 有两点疑惑：
1. 如果是配置了MySQL数据源，配置记录应该都在远程数据库里，这个可以直接重启Nacos正常加载，为什么需要你“手动打回”？
2. 你一直提到的/tmp文件夹是什么，是把Nacos主目录放到/tmp目录下吗？

**Comment by zarkzheng** [comment]
@474420502 有两点疑惑：
1. 如果是配置了MySQL数据源，配置记录应该都在远程数据库里，这个可以直接重启Nacos正常加载，为什么需要你“手动打回”？
2. 你一直提到的/tmp文件夹是什么，是把Nacos主目录放到/tmp目录下吗？

**Comment by MajorHe1** [comment]
> @zarkzheng
> 官方首页standalone启动, 而且日志不难看, 后面一直重复. 数量就那么多. 竟然还要关闭issue.
> 如果我全部日志给,都嫌弃太多的话, 其他无能为力, 东西不是我写的, 我整理不了什么给你们, 现在更加整理不了时间太久.
> 问题就是很简单, 忽然挂了, 数据一点都找不回. 凭一些历史记录. 我一点点手动打回了.
> 现在我都是每几分钟备份配置一次. 这个系统改动太麻烦.

这个ISSUE是你自己关闭的，如果你觉得没有解决，重新打开然后继续讨论就是。
就算你不整理日志，别人都已经帮你发现是db.num配置出错的问题了，如果还存在问题，建议重新开一个issue讨论
不要在别人的issue下面讨论无关的问题

**Comment by MajorHe1** [comment]
> 版本：2.0.3
> 启动方式：standalone
> 现象：应用可以正常获取配置，且配置能够动态更新，但是监听查询为空：
> ![image](https://user-images.githubusercontent.com/30680275/129829403-2c6802cb-627a-495d-be8a-79336ca29235.png)

回答一下原issue的问题：
我本地无法复现，我觉得问题就是，
1. 如 @zarkzheng 所说，从你提供的图片里看，你没有设置正确的Data ID和Group信息，所以是获取不到对应的监听数据的。
2. 你的应用并没有监听配置。监听配置需要用客户端调用` configService.addListener`方法或者`configService.getAndSignListener`方法注册一个监听，你从控制台上才能查询得到，而不是`configService.getConfig()`方法就监听了的。

**Comment by 474420502** [comment]
@Maijh97  相似问题不要讨论? 你看了吗, 他要关闭. 我关闭是帮他完成最后一步. 还有你也不要发无关的东西

**Comment by 474420502** [comment]
@zarkzheng 
standalone 模式不是单机模式吗? 官方首页的模式, 理论上nacos不会自建一个数据库吧, 默认就是nacos放到/tmp/nacos. 因为我没改过.
2020年的了. 早没了.  维护人都不想看, 我留着也没用, 已经重建. 
我手动打回是指数据没了. 但是配置的信息能在我工作debug机器上一点点找回. 
操作日志应该在  data/derby-data/log/log1.dat 上吧.
算了, 不需要你们解决了, 我感觉我还熟一点. 虽然我没怎么看源码.

**Comment by KomachiSion** [comment]
> 从你提供的图片里看，你没有设置Data ID和Group信息，所以是获取不到对应的监听数据的。

Should be this problem.
