### ISSUE TITLE
I found a place code wrong in nacos-client:2.0.2(有一个代码的bug).

### ISSUE THREAD

**Issue by kangarooking** [alibaba/nacos#6692]
也就是在nacosConfigService类中getConfigInner方法中使用了LocalConfigInfoProcessor.getFailover方法；
而这个方法在配置刷新之后，server端反馈给client端，最后调用spring的刷新机制，spring最后又会调用nacos-client的getConfig方法，在这里本来不应该再去请求server端了，因为之前nacos-client端已经请求过server，得到变更的配置并且更新仔本地文件中，我认为这里的LocalConfigInfoProcessor.getFailover(worker.getAgentName(), dataId, group, tenant) getFailover是废弃方法，它根本拿不到本地文件的最新配置，导致又请求了nacos-server，没有必要多做这一次请求，所以我觉得这里应该调用getSnapshot方法来获取本地最新的content然后直接返回
`private String getConfigInner(String tenant, String dataId, String group, long timeoutMs) throws NacosException {
        group = blank2defaultGroup(group);
        ParamUtils.checkKeyParam(dataId, group);
        ConfigResponse cr = new ConfigResponse();
        
        cr.setDataId(dataId);
        cr.setTenant(tenant);
        cr.setGroup(group);
        ************************************** **************************************
        **// i think this can not use getFailover,it need use getSnapshot.
       //Otherwise, the local config will not be used here, and the server will always be requested.
      //This will cause the client to request the server twice when refreshing the configuration.
     //And there is no savefailover,so I guess the code here is your careless mistake.**
 ************************************** ************************************** **********************************
        **String content = LocalConfigInfoProcessor.getFailover(worker.getAgentName(), dataId, group, tenant);**
 ************************************** ************************************** **************************************
        if (content != null) {
            LOGGER.warn("[{}] [get-config] get failover ok, dataId={}, group={}, tenant={}, config={}",
                    worker.getAgentName(), dataId, group, tenant, ContentUtils.truncateContent(content));
            cr.setContent(content);
            String encryptedDataKey = LocalEncryptedDataKeyProcessor
                    .getEncryptDataKeyFailover(agent.getName(), dataId, group, tenant);
            cr.setEncryptedDataKey(encryptedDataKey);
            configFilterChainManager.doFilter(null, cr);
            content = cr.getContent();
            return content;
        }
        
        try {
            ConfigResponse response = worker.getServerConfig(dataId, group, tenant, timeoutMs, false);
            cr.setContent(response.getContent());
            cr.setEncryptedDataKey(response.getEncryptedDataKey());
            configFilterChainManager.doFilter(null, cr);
            content = cr.getContent();
            
            return content;`

**Comment by MajorHe1** [comment]
1. getFailover 并不是废弃方法，而是提供在配置中心失联的紧急情况下的干预手段。Failover是用于容灾的，如果出现客户端和服务端完全无法通信，但又需要修改配置的时候，手动创建failover目录及对应dataid配置内容。
 2. getSnapshot 并不是用来获取最新的配置，而是提供在配置中心失联的情况下的，人工的 容灾干预是滞后的，这个时候客户端至少还可以从snapshot中获取旧的配置，而不至于直接报错罢工。
 3. getConfig方法每一次都会请求nacos-server，这是合理的，在配置中心正常工作的情况下，该方法获取到的配置可以确认一定是最新可靠的。
 4. 如果不想因为每一次获取配置都去请求nacos-server造成配置中心压力过大，应该使用监听的方式。这样客户端只会在启动的时候访问一次nacos-server，之后依赖配置中心的主动推送异步更新配置，而不是每一次用到配置了就去发起请求。

**Comment by MajorHe1** [comment]
可以 refer to #6587 参考一下

**Comment by kangarooking** [comment]
我主要的疑问是，为什么需要两次请求，因为第一次请求其实已经拿到修改的配置了。当我们在server的界面更改配置，server推送dataid，group，文件名 到client端，client端感知到就会直接请求server拿到具体的更改配置细节。然后client给spring发送refresh的事件，最后spring那边又会掉用client的getConfig方法，又请求了一次server端去获取修改配置的细节，我的疑问是这个第二次请求是否是不必要的。因为其实在client端第一次请求就已经拿到修改的配置信息了，然后spring那边，过来的话 我认为应该走缓存去获取吧。

**Comment by MajorHe1** [comment]
> 然后client给spring发送refresh的事件，最后spring那边又会掉用client的getConfig方法

你说的这个不是原生的nacos-client的逻辑吧？是nacos-config-spring-boot-starter的逻辑还是spring-cloud-alibaba里面的逻辑？
nacos spring相关的东西我不熟，没办法给你更多的帮助了，等一下其他的大佬解答吧

**Comment by kangarooking** [comment]
nacos配置中心，自动刷新配置的功能，在nacos管理界面修改相关应用配置，nacos-clinet最终会请求两次server获取具体的修改细节。确实不是nacos-client的原生逻辑，发送事件给spring的逻辑在nacos-config starter里面的NacosContextRefresher类。最后spring那边处理的过程中会重新生成上下文，在这个过程中就调用到了nacosConfigService的getConfig方法，又请求了一次server（也就是第二次请求server）
下面是从第一次请求server到第二次请求server 代码的一个执行顺序：
![第一次请求server](https://user-images.githubusercontent.com/52196004/130340885-25b1024e-0823-4d4b-892b-f4ce186b52d6.jpg)
![获取configinfo](https://user-images.githubusercontent.com/52196004/130340908-fbbab136-1b37-48aa-9953-2c3e441e52e7.jpg)
![发布refresh事件](https://user-images.githubusercontent.com/52196004/130340914-652acf4d-e412-4f70-9259-2744b973b252.jpg)
![刷新配置动态](https://user-images.githubusercontent.com/52196004/130340925-4272c88c-b8f2-41c5-8d1c-6295847c9aea.jpg)
![第二次请求server](https://user-images.githubusercontent.com/52196004/130340929-7c0bfc2c-bee7-4b17-b48f-2b012ede853f.jpg)

**Comment by kangarooking** [comment]
Can someone help me answer this question? thank you

**Comment by kangarooking** [comment]
不对啊 这个东西不是设计上面的问题吗  配置刷新 理论上 client端只请求一次服务端就行了啊，但是我亲测  springCloud下面有两次请求，多余的一次请求是不是应该在后续的版本中去除呢。不然浪费网络资源呀。（还有 这个情况你们应该要先验证一下吧，应该也很好验证吧，也有可能是你们设计本来如此，毕竟这个东西是你们开发的，我只是以客观的角度去看，发现跟我预想的有偏差）

**Comment by kangarooking** [comment]
我把这个问题提到alibabaSpringCloud，他们那边又叫提到nacos社区、、。。。。

**Comment by KomachiSion** [comment]
> 不对啊 这个东西不是设计上面的问题吗 配置刷新 理论上 client端只请求一次服务端就行了啊，但是我亲测 springCloud下面有两次请求，多余的一次请求是不是应该在后续的版本中去除呢。不然浪费网络资源呀。（还有 这个情况你们应该要先验证一下吧，应该也很好验证吧，也有可能是你们设计本来如此，毕竟这个东西是你们开发的，我只是以客观的角度去看，发现跟我预想的有偏差）

getConfig是由外部组件或用户自己调用的。 你需要找到哪里调用了2次，将堆栈给出。如果两次都是SCA调用的，就让他们解释为什么要调用两次。
