### ISSUE TITLE
nacos 2.x open api: register service and send heartbeats must use DEFAULT_GROUP as groupName

### ISSUE THREAD

**Issue by zivmc** [alibaba/nacos#6693]
**Describe the bug**
Here is the situation.

1. I started nacos-server-2.0.0 on my PC;
2. I use nacos open api to register a service;
3. I keep sending heartbeat to keep the service healthy (every three seconds and using open api).

**Expected behavior**

The service I registered keeps a health status of true in nacos.

**Acutally behavior**

The problem is, if I use a groupName other than DEFAULT_GROUP when I register the service and send heartbeats, the service's health status will be sometimes true and sometimes false. If I use the groupName DEFAULT_GROUP exactly, the problem wouldn't occur. 

**How to Reproduce**

I was actually use nacos-python-sdk when I found this issue, but to make this issue clearer, I used curl to request nacos open apis and reproduced this issue.

Here I wrote a srcipt `test_nacos_open_api.sh` to reproduce this issue:

```
#! /bin/bash
if [ $# -ne 2 ]
then
    echo -e "Usage: $(basename $0) service_name group_name\n"
    exit 1
fi

echo -e "register service: serviceName: $1, groupName: $2\n"
curl -X POST "http://localhost:8848/nacos/v1/ns/instance?username=nacos&password=nacosb&ip=10.1.2.75&port=18000&serviceName=$1&weight=1&enable=True&healthy=True&clusterName=DEFAULT&ephemeral=True&groupName=$2&metadata=%7B%7D&namespaceId=public"

while sleep 3;
do
  echo -e "send heartbeat: serviceName: $1, groupName: $2\n"
  curl -X PUT "http://localhost:8848/nacos/v1/ns/instance/beat?serviceName=$1&beat=%7B%22serviceName%22%3A+%22$1%22%2C+%22ip%22%3A+%2210.1.2.75%22%2C+%22port%22%3A+18000%2C+%22weight%22%3A+1.0%2C+%22ephemeral%22%3A+true%2C+%22cluster%22%3A+%22DEFAULT%22%7D&groupName=$2&namespaceId=public&username=nacos&password=nacos"
done
```

You just need to start nacos-server-2.0.0 (and above version), then run these commands in a bash terminal:

```
./test_nacos_open_api.sh test-service ANOTHER_GROUP
./test_nacos_open_api.sh test-service DEFAULT_GROUP
```

The first command will reproduce this issue and the second command should work fine.

I also tested on nacos-server-1.4.2, and this problem does not occur.

**Desktop (please complete the following information):**
 - OS: Mac OS 11
 - Version nacos-server-2.0.0 nacos-server-2.0.3
 - Module naming
 - SDK original

**Additional context**

用中文再简单说一下，问题在 nacos 2.x 的 open api 上，使用 open api 注册服务并持续发送心跳（每3秒发一次），如果传的 groupName 不是 DEFAULT_GROUP，那么服务健康状态一会儿是好的，一会儿是坏的。groupName 传DEFAULT_GROUP时，在各个版本上都没有问题，服务一直都是好的。

在 nacos-server-1.4.2 上测试了没有出现这个问题。

上面给的脚本可以很容易复现这个问题。

**Comment by zivmc** [comment]
These requests in the bash scripts are encoded. The decoded contents are as follows:

```
http://localhost:8848/nacos/v1/ns/instance?username=nacos&password=nacosb&ip=10.1.2.75&port=18000&serviceName=$1&weight=1&enable=True&healthy=True&clusterName=DEFAULT&ephemeral=True&groupName=$2&metadata={}&namespaceId=public


http://localhost:8848/nacos/v1/ns/instance/beat?serviceName=$1&beat={"serviceName": "$1", "ip": "10.1.2.75", "port": 18000, "weight": 1.0, "ephemeral": true, "cluster": "DEFAULT"}&groupName=$2&namespaceId=public&username=nacos&password=nacos
```

**Comment by zarkzheng** [comment]
@i will solve it@

**Comment by zarkzheng** [comment]
In fact, if you want send heart beat with open api, **you should set `serviceName` to `group@@serviceName` in `beat` parameter**. The official document does not make this clear.
Take a look at this code in `ClientBeatProcessorV2` and `NamingUtils`:
```java
// ClientBeatProcessorV2
String serviceName = NamingUtils.getServiceName(rsInfo.getServiceName());
String groupName = NamingUtils.getGroupName(rsInfo.getServiceName());
Service service = Service.newService(namespace, groupName, serviceName, rsInfo.isEphemeral());
HealthCheckInstancePublishInfo instance = (HealthCheckInstancePublishInfo) client.getInstancePublishInfo(service);

// NamingUtils
public static String getGroupName(final String serviceNameWithGroup) {
    if (StringUtils.isBlank(serviceNameWithGroup)) {
        return StringUtils.EMPTY;
    }
    if (!serviceNameWithGroup.contains(Constants.SERVICE_INFO_SPLITER)) {
        return Constants.DEFAULT_GROUP;
    }
    return serviceNameWithGroup.split(Constants.SERVICE_INFO_SPLITER)[0];
}
```

If your `serviceName` in `beat` is not `group@@serviceName`, the it will return `DEFAULT_GROUP`, so you cannot get service and instance correctly.

**Comment by zivmc** [comment]
> In fact, if you want send heart beat with open api, **you should set `serviceName` to `group@@serviceName` in `beat` parameter**. The official document does not make this clear.
> Take a look at this code in `ClientBeatProcessorV2` and `NamingUtils`:
> 
> ```java
> // ClientBeatProcessorV2
> String serviceName = NamingUtils.getServiceName(rsInfo.getServiceName());
> String groupName = NamingUtils.getGroupName(rsInfo.getServiceName());
> Service service = Service.newService(namespace, groupName, serviceName, rsInfo.isEphemeral());
> HealthCheckInstancePublishInfo instance = (HealthCheckInstancePublishInfo) client.getInstancePublishInfo(service);
> 
> // NamingUtils
> public static String getGroupName(final String serviceNameWithGroup) {
>     if (StringUtils.isBlank(serviceNameWithGroup)) {
>         return StringUtils.EMPTY;
>     }
>     if (!serviceNameWithGroup.contains(Constants.SERVICE_INFO_SPLITER)) {
>         return Constants.DEFAULT_GROUP;
>     }
>     return serviceNameWithGroup.split(Constants.SERVICE_INFO_SPLITER)[0];
> }
> ```
> 
> If your `serviceName` in `beat` is not `group@@serviceName`, the it will return `DEFAULT_GROUP`, so you cannot get service and instance correctly.

Thanks for your help. I tested with beat_data in format of `group@@serviceName`, and the problem does not occur any more.

**Comment by zarkzheng** [comment]
I think should handle the `serviceName` in heart beat request at `InstanceController`(this is the easiest way), or just like `ServiceNameFilter` do, it replace the `serviceName` with `groupName@@serviceName` in filter.
@i will solve it@
