### ISSUE TITLE
url传递accessToken不安全，如果要改成header传递要改哪些地方呢

### ISSUE THREAD

**Issue by superhu** [alibaba/nacos#6696]
安全规则有一条，url中禁止明文存放SessionId,非一次性认证票据(如GET)等敏感信息。
如果要改代码适配，只认header中的accessToken，大概要改哪些地方呢，麻烦帮忙指点下，谢谢!

**Comment by MajorHe1** [comment]
![企业微信截图_16293557691727](https://user-images.githubusercontent.com/53824889/130021564-7c1854ba-7b2c-4f24-a4d9-8f6b8a53222d.png)
改一下这个地方试一下？只从上面的方法获取token，不从request.getParamater获取Token，试试？

**Comment by superhu** [comment]
好的，谢谢，我试下
