### ISSUE TITLE
2.0.3版本Ephemeral设置为false注册服务，再通过删除命令无法删除服务

### ISSUE THREAD

**Issue by qinjay519** [alibaba/nacos#6699]
1.    测试： 2.0.3版本Ephemeral设置为false注册服务，此时nacos 服务列表注册的服务 Ephemeral是false(持久化实例 非临时实例)。当我主动将服务停止，nacos的服务依然存在，因为是持久化所以不会自动下线，这点理解
2. 手动点页面的删除按钮提示：caused: Service DEFAULT_GROUP@@MiC.ApiGateway1111111 is not empty, can't be delete. Please unregister instance first;   
3. 但是我如果要删除这个不需要的测试服务时，我利用官网提供的删除命令去删除，返回的结果也是OK，回来服务列表，那个测试服务依然存在，始终无法删除掉。

**Comment by zarkzheng** [comment]
多试几次，可能是浏览器缓存的问题。
试试用别的浏览器打开，或者接口调用删除之后再手动点击删除按钮。
（我也复现了这个现象，手动再次删除或隐私模式打开新的浏览器，现象消失）

**Comment by qinjay519** [comment]
请再次确认是否是BUG,我换了电脑，每个电脑换不同浏览器，问题依旧，清楚缓存也无效。手动不行，调用接口返回OK 还是没有删除。

**Comment by brotherlu-xcq** [comment]
@qinjay519 服务有实例的时候，是无法直接删除服务的，会提示你上面到`caused: Service DEFAULT_GROUP@@MiC.ApiGateway1111111 is not empty, can't be delete. Please unregister instance first;`. 这边是我复现你问题的步骤，你可以看看有哪里不一样的，我暂时没有复现到你的问题。
![image](https://user-images.githubusercontent.com/25661357/130036563-d1445bcf-afae-4c07-86e3-6826f6b54843.png)

额外补充一下，如果你删除一个不存在的服务，api也会返回ok。你可以检查一下你用OpenAPI删除的时候是不是传入了正确的服务名这些。

**Comment by KomachiSion** [comment]
并非bug `caused: Service DEFAULT_GROUP@@MiC.ApiGateway1111111 is not empty, can't be delete. Please unregister instance first;` 提示中已经提示，该服务下仍然存在实例，需要先注销实例。

**Comment by xunfeng224** [comment]
/nacos/v2/ns/instance调用实例注销api时注意加上该参数ephemeral=false
