### ISSUE TITLE
Limit the total number of instances实例总数限制问题

### ISSUE THREAD

**Issue by 602297770** [alibaba/nacos#6706]
At present, our implementation idea is to store the total number of instances in yaml or database.

Then, judge whether the current total number of instances has reached the specified number in the registerinstance method of instanceoperatorclientimpl class.

Does the official have any plans or suggestions for relevant functions.

In addition, does Nacos support a method that can take effect without restart after modifying yaml.

**Comment by KomachiSion** [comment]
Refer to #5698
