### ISSUE TITLE
The document has punctuation issues

### ISSUE THREAD

**Issue by csxiaoshang** [alibaba/nacos#6707]
## Issue Description

Type: *document error* 

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/20570530/130166957-5d0b4f79-e18e-4420-8122-a1b9b2f183f8.png)
![image](https://user-images.githubusercontent.com/20570530/130167009-b9a5cba3-8146-41ab-baf5-793447b2e346.png)

There is a problem with the punctuation after personnel

### Describe what you expected to happen
 should remove the comma

**Comment by brotherlu-xcq** [comment]
Hi, @AayushSaini101 . I have no permission assign, if you want to work on it, you can just reply the module you want to do on the issue's comment. and then start to code. I will add your name to the module you are doing.

**Comment by brotherlu-xcq** [comment]
you can follow the example of #5726 . create a issue of of your module first and then code.

**Comment by brotherlu-xcq** [comment]
This issue has been solved in https://github.com/nacos-group/nacos-group.github.io/pull/234.
