### ISSUE TITLE
Nocos2.0.0 控制台修改服务的权重报错500

### ISSUE THREAD

**Issue by IvesQing** [alibaba/nacos#6709]
**Describe the bug**
Nocos2.0.0 Error 500 was reported when the console changed the service weight；
Nacos2.0.3 the same issue;

**How to Reproduce**
1. window10 Environment
2. startup.cmd -m standalone
3. Service registration succeeded
4. Modify the service weight

**Desktop (please complete the following information):**
 - OS: [e.g. Window10]
 - Version [e.g. nacos-server 2.0.0, nacos-client 2.0.0]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos 2.2.5.RELEASE, dubbo]

**Additional context**
Error message is as follows:
caused: errCode: 500, errMsg: do metadata operation failed ;
caused: com.alibaba.nacos.consistency.exception.ConsistencyException: 
com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: 
The Raft Group [naming_instance_metadata] did not find the Leader node;
caused: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException:
 The Raft Group [naming_instance_metadata] did not find the Leader node;

screenshot as follows：
![image](https://user-images.githubusercontent.com/26543986/130177318-f023ac81-a7a6-416b-a2aa-34440abdc8b5.png)

**Comment by MajorHe1** [comment]
这里确实是个问题。
单机模式启动的时候，控制台修改元数据信息，代码没有判断是否是单机模式，依然走的raft同步，然后报错没有主节点。
我看一下有没有低成本的解决方案先。

**Comment by MajorHe1** [comment]
![企业微信截图_16294465973125](https://user-images.githubusercontent.com/53824889/130202366-169ac75e-145b-4cc1-99ef-9f285b7c27ba.png)
我初步的想法是，在这个方法里面判断是否是单机模式，如果是，直接调用`InstanceMetadataProcessor` 或者 `ServiceMestadataProcessor` 的 `onApply`方法就行了。
但是没有弄明白底层是怎么实现把 `operationLog` 分配到正确的processor上面的。
不知道这个方法是否可行，以及是否会跟2.1.0版本正在进行的元数据管理策略模式改造冲突。
等一下官方解答 @KomachiSion

**Comment by KomachiSion** [comment]
直接调用会丢失raft日志，如果你可以接受的话就自行修改然后打包运行，社区认为持久化信息不应该丢失。

**Comment by KomachiSion** [comment]
另外issue问题来源于jraft无法选主，请检查alipay-jraft.log以及protocol-raft.log找到原因。

单机模式很可能是因为ip变动导致无法选主，删除/nacos/data然后重启一下试试。

**Comment by KomachiSion** [comment]
No more response
