### ISSUE TITLE
nacos不支持powerlinux 即ppcle64linux Caused by: java.lang.RuntimeException: librocksdbjni-linux-ppc64.so was not found inside JAR.

### ISSUE THREAD

**Issue by z787804918** [alibaba/nacos#6711]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
duplicate with #4336
