### ISSUE TITLE
单机模式下OpenApi的查询实例列表返回的实例状态和实际不一致。

### ISSUE THREAD

**Issue by kobe-2020** [alibaba/nacos#6715]
**Describe the bug**
VERSION：V2.0.3，same V1.4.2，V1.3.2
OS: Centos7

控制台界面下服务状态为false。调用实例列表查询返回对应的健康状态为true，调用实例详情接口返回的健康状态为false。

**How to Reproduce**
1. 启动： ./startup.sh -m standalone ,没有任何自定义配置项。
2. 创建服务：POST http://10.38.115.10:8848/nacos/v1/ns/service?serviceName=jiang_service&protectThreshold=1.0
3. 注册实例：POST http://10.38.115.10:8848/nacos/v1/ns/instance?ip=10.34.98.189&port=8000&serviceName=jiang_service&ephemeral=false （该服务实例实际未拉起。且创建的服务没有其他的实例，只有这一个实例）
4. 查看控制台的实例健康状态为false
5. 实例了列表查询：GET http://10.38.115.10:8848/nacos/v1/ns/instance/list?serviceName=jiang_service&healthyOnly=true
  接口response: ....."instance":"10.34.98.189","healthy":true,"enabled":true.....这里省略其他的返回信息。。
6.实例详情查询：GET http://10.38.115.10:8848/nacos/v1/ns/instance?ip=10.34.98.189&port=8000&serviceName=jiang_service
接口response:{"service":"xxxx","ip":"10.34.98.189","port":8000,"healthy":false,....}

多次测试，列表查询返回的健康状态一直都是true，无论实际状态如何。请问，这个是我配置的不对还是BUG呢？
因为是使用的python,所以只能使用openApi，另，没有试过集群模式下是否会有该现象。

**Comment by zarkzheng** [comment]
这里的主要原因是你设置了服务的保护阈值 `Protect Threshold` 为 `1`，且只有一个实例。所以这个实例不论是否健康，都会在服务列表里返回为 `true`；但是实际的服务实例详情里的真实状态又是 `false`。

[保护阈值](https://nacos.io/zh-cn/docs/concepts.html)

> 健康保护阈值
为了防止因过多实例 (Instance) 不健康导致流量全部流向健康实例 (Instance) ，继而造成流量压力把健康实例 (Instance) 压垮并形成雪崩效应，应将健康保护阈值定义为一个 0 到 1 之间的浮点数。当域名健康实例数 (Instance) 占总服务实例数 (Instance) 的比例小于该值时，无论实例 (Instance) 是否健康，都会将这个实例 (Instance) 返回给客户端。这样做虽然损失了一部分流量，但是保证了集群中剩余健康实例 (Instance) 能正常工作。

**Comment by kobe-2020** [comment]
> 这里的主要原因是你设置了服务的保护阈值 `Protect Threshold` 为 `1`，且只有一个实例。所以这个实例不论是否健康，都会在服务列表里返回为 `true`；但是实际的服务实例详情里的真实状态又是 `false`。
> 
> [保护阈值](https://nacos.io/zh-cn/docs/concepts.html)
> 
> > 健康保护阈值
> > 为了防止因过多实例 (Instance) 不健康导致流量全部流向健康实例 (Instance) ，继而造成流量压力把健康实例 (Instance) 压垮并形成雪崩效应，应将健康保护阈值定义为一个 0 到 1 之间的浮点数。当域名健康实例数 (Instance) 占总服务实例数 (Instance) 的比例小于该值时，无论实例 (Instance) 是否健康，都会将这个实例 (Instance) 返回给客户端。这样做虽然损失了一部分流量，但是保证了集群中剩余健康实例 (Instance) 能正常工作。

你好，根据你的提示，我讲服务的阈值分别调整为0和0.1进行了测试。每次测试都添加了2个实例，且分别为健康和非健康状态。在这个场景下，使用列表查询，只会返回其中不健康的实例，且健康状态为true。截图如下。
控制台截图：
![DF0EA3C9-955E-4B6E-8368-BA89FBC40419](https://user-images.githubusercontent.com/60385640/130309689-0d5fec78-5fbf-481b-9ee3-cc5f0a23942d.jpeg)

![469C5509-E060-4973-83B5-5FE7170DA072](https://user-images.githubusercontent.com/60385640/130309703-a3eda813-d6b4-48c8-b86f-5f1dd58e4bb5.jpeg)

实例列表查询接口图分别为heaythonly为true好玩false的结果：

![42E086B0-143A-49E9-BB8A-CFF627E47BBB](https://user-images.githubusercontent.com/60385640/130309738-5ce33c3b-b83e-4657-a077-9281b28656ad.jpeg)

![6970DA68-0555-4C00-9246-E17A696E37AB](https://user-images.githubusercontent.com/60385640/130309751-aab75b5e-9af5-41b2-b7c2-2ca5a22a0ed0.jpeg)

因公司不能外网，手机拍照不清楚之处请见谅

**Comment by kobe-2020** [comment]
重新补充下控制台的清晰截图：
![C0C49554-1DFB-4137-86C3-FED1F398DB81](https://user-images.githubusercontent.com/60385640/130309803-36b09434-faff-42e7-907e-2c6419fd282a.jpeg)

![B041539E-0264-43A7-8F63-7C4440CB1DF8](https://user-images.githubusercontent.com/60385640/130309812-17f78836-47fd-4e63-8cd3-92ac31280136.jpeg)

**Comment by zarkzheng** [comment]
我本地复现的情况是，如果`healthyOnly=false`，api请求列表里至少应该返回**所有的实例，不管是否是健康实例**。
你再尝试几次看看。

**Comment by kobe-2020** [comment]
> 我本地复现的情况是，如果`healthyOnly=false`，api请求列表里至少应该返回**所有的实例，不管是否是健康实例**。
> 你再尝试几次看看。





> 我本地复现的情况是，如果`healthyOnly=false`，api请求列表里至少应该返回**所有的实例，不管是否是健康实例**。
> 你再尝试几次看看。

请问，你之前本地复现的时候添加实例是否添加了clusterName参数？
我这尝试复现，发现如果添加实例的时候使用默认集群（没有clusterName参数），这个时候使用列表查询则会只返回一个实例，且healthy为true，无论是否健康。但是添加实例下发了集群名之后，列表查询就正常了，能查出来所有的，健康状态也正确。具体步骤如下：

1.添加服务。参数：serviceName=jiang&protectThreshold=0.0
2.添加实例，没有集群名：
ip=xxx&port=8000&serviceName=jiang&ephemeral=false&healthy=false
3.添加第二个实例，参数同上，端口号不同。
4.列表查询：serviceName=jiang&healthOnly=false
这时返回结果中只有一个实例。
5.删除所有的实例重新添加2个实例，增加集群名。
ip=xxx&port=8000&serviceName=jiang&ephemeral=false&healthy=false&clusterName=test
6.实例列表查询，这个时候能查出来所有的实例。

环境：随便部署了一个测试环境，里面没有任何别的服务或者组。

尝试多次，这个是必现的，感觉问题在默认集群上。

**Comment by zarkzheng** [comment]
抱歉，按照你的参数，创建的服务实例无论是否带有`clusterName`参数，都是可以获取完整的实例列表的。用的也是2.0.3版本的server。

**Comment by zarkzheng** [comment]
不过我也确实发现在实例列表接口获取的实例健康状态会有些问题。

**Comment by kobe-2020** [comment]
能告诉下我，你的步骤和对应的请求参数吗？
谢谢

**Comment by zarkzheng** [comment]
## 启动v2.0.3版本server
```
startup.cmd -m standalone
```

## 创建服务
```
## POST 
http://localhost:8848/nacos/v1/ns/service?serviceName=jiang&protectThreshold=0.0
```

## 注册实例
```
## POST
http://localhost:8848/nacos/v1/ns/instance?ip=127.0.0.1&port=8080&serviceName=jiang&ephemeral=false&healthy=false

http://localhost:8848/nacos/v1/ns/instance?ip=127.0.0.1&port=8081&serviceName=jiang&ephemeral=false&healthy=false
```

## 获取实例列表
```
## GET
http://localhost:8848/nacos/v1/ns/instance/list?serviceName=jiang

{
  "name": "DEFAULT_GROUP@@jiang",
  "groupName": "DEFAULT_GROUP",
  "clusters": "",
  "cacheMillis": 10000,
  "hosts": [
    {
      "instanceId": "127.0.0.1#8080#DEFAULT#DEFAULT_GROUP@@jiang",
      "ip": "127.0.0.1",
      "port": 8080,
      "weight": 1.0,
      "healthy": true,
      "enabled": true,
      "ephemeral": false,
      "clusterName": "DEFAULT",
      "serviceName": "DEFAULT_GROUP@@jiang",
      "metadata": {},
      "ipDeleteTimeout": 30000,
      "instanceHeartBeatTimeOut": 15000,
      "instanceIdGenerator": "simple",
      "instanceHeartBeatInterval": 5000
    },
    {
      "instanceId": "127.0.0.1#8081#DEFAULT#DEFAULT_GROUP@@jiang",
      "ip": "127.0.0.1",
      "port": 8081,
      "weight": 1.0,
      "healthy": true,
      "enabled": true,
      "ephemeral": false,
      "clusterName": "DEFAULT",
      "serviceName": "DEFAULT_GROUP@@jiang",
      "metadata": {},
      "ipDeleteTimeout": 30000,
      "instanceHeartBeatTimeOut": 15000,
      "instanceIdGenerator": "simple",
      "instanceHeartBeatInterval": 5000
    }
  ],
  "lastRefTime": 1629544246901,
  "checksum": "",
  "allIPs": false,
  "reachProtectionThreshold": true,
  "valid": true
}
```

## 获取实例详情
```
## GET 
http://localhost:8848/nacos/v1/ns/instance?serviceName=jiang&ip=127.0.0.1&port=8080

{
  "service": "DEFAULT_GROUP@@jiang",
  "ip": "127.0.0.1",
  "port": 8080,
  "clusterName": "DEFAULT",
  "weight": 1.0,
  "healthy": false,
  "instanceId": "127.0.0.1#8080#DEFAULT#DEFAULT_GROUP@@jiang",
  "metadata": {}
}

## GET 
http://localhost:8848/nacos/v1/ns/instance?serviceName=jiang&ip=127.0.0.1&port=8081

{
  "service": "DEFAULT_GROUP@@jiang",
  "ip": "127.0.0.1",
  "port": 8081,
  "clusterName": "DEFAULT",
  "weight": 1.0,
  "healthy": false,
  "instanceId": "127.0.0.1#8081#DEFAULT#DEFAULT_GROUP@@jiang",
  "metadata": {}
}
```

> 可以看出获取实例列表的实际健康状态和实例详情的健康状态会对不上。

**Comment by zarkzheng** [comment]
https://github.com/alibaba/nacos/blob/5889b3a5de32bebeb1c2d6b0dc8d2ce2c3752b46/naming/src/main/java/com/alibaba/nacos/naming/utils/ServiceUtil.java#L302-L316

看了下源码的实现，实际逻辑是：**只要健康实例数占总实例数的比例不大于`threshold`，就会把所有实例的健康状态设置为`true`**，而不是设置一定比例的实例使健康实例的占比达到`threshold`。

**Comment by KomachiSion** [comment]
控制台上有一个是否触发保护阈值的列表内容，你看一下是不是true，如果是的话，那就是正常的。

可以通过控制台修改服务元数据中的保护阈值内容。 

前面大家的解答已经非常详细了。

**Comment by kobe-2020** [comment]
健康状态那个确实是保护阀值配置导致的，后面列表查出来不一样就很神奇，搞不懂了。具体状态上面截图都有。

**Comment by KomachiSion** [comment]
No more response
