### ISSUE TITLE
java.lang.UnsatisfiedLinkError:/tmp/librocksdbjni4935347250006226380.so failed to map segment from shared object

### ISSUE THREAD

**Issue by zhuziying** [alibaba/nacos#6718]
## Issue Description
![WechatIMG611](https://user-images.githubusercontent.com/4710245/130339221-0fb2c2ae-54aa-4282-a4dd-cbc6f1bc612e.jpeg)
![WechatIMG612](https://user-images.githubusercontent.com/4710245/130339224-7e35d14a-f02d-435b-8f51-0c3f6d0bed3e.jpeg)

### Describe what happened (or what feature you want)
The TMP directory does not have execution permission, and Nacos cannot start
tmp目录没有执行权限，nacos无法启动

### Describe what you expected to happen
How to run Nacos successfully without changing TMP permissions
怎么样才能不改变tmp权限的情况下，成功运行nacos

### Tell us your environment
nacos2.0.0
中科方德
linux version 4.19.113-1.nfs.28.x86_64 (gcc version 8.3.1 20190507(NFS Server 8.3.1-5)(GCC))
### Anything else we need to know?
My judgment is that rocksdb uses the files in the TMP path. The TMP permission cannot be changed. I don't know which Nacos version doesn't use rocksdb
我的判断是rocksdb使用了tmp路径中的文件，tmp这个权限是不能改得，不知道哪个nacos版本是不使用rocksdb的

**Comment by KomachiSion** [comment]
duplicate with #4336

**Comment by zhuziying** [comment]
thank u for your help




At 2021-08-24 09:59:28, "杨翊 SionYang" ***@***.***> wrote:

Closed #6718.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wyx1280** [comment]
您好，我这边也碰到这个问题了，您这边当时是如何解决的

**Comment by wyx1280** [comment]
您好，我之前也遇到过这个问题，您这个是怎么解决的

**Comment by yangjb0913** [comment]
我是通过重新打包rpm解决的，主要在于指定环境变量LD_LIBRARY_PATH和使用脚本启动。

1.创建一个shell脚本startup.sh，将startup.sh放到/data/nacos/bin/目录下，内容如下：
#!/bin/bash

export LD_LIBRARY_PATH=/data/nacos/lib && /usr/bin/java -server -Xms512m -Xmx512m -Dnacos.standalone=true -Dnacos.home=/data/nacos -jar /data/nacos/target/nacos-server.jar --spring.config.location=file:./,file:/data/nacos/conf/,/data/nacos/init.d/ --spring.config.name=application,custom

2.将对应的librocksdbjni-linux-aarch64.so放到/data/nacos/lib目录下（注意我是银河麒麟arm架构的服务器，用的是aarch64的文件，如果是中科方德x86架构的服务器，需要替换成librocksdbjni-linux64.so）

3.创建一个nacos.service，内容如下：
[Unit]
Description=Nacos
After=network-online.target

[Service]
Type=simple
WorkingDirectory=/data/nacos
ExecStart=/usr/bin/bash /data/nacos/bin/startup.sh
RestartSec=10
Restart=always
StartLimitInterval=0
User=root
Group=root

[Install]
WantedBy=multi-user.target

5.rpm打包

这里我遇到的坑，rpm包装完之后需要覆盖一次/data/nacos/target目录下的nacos-server.jar，重启服务之后才能正常运行。
