### ISSUE TITLE
startup.cmd bug

### ISSUE THREAD

**Issue by ankeway** [alibaba/nacos#672]
There is  a  Bug in Nacos Server Folder ，Bin directory ，startup.cmd File,
if not ""%2"" == "cluster" (
)
if  you run startup.cmd -m cluster can’t startup with cluster mode，
if not "%2" == "cluster" (
)
run startup.cmd -m cluster  Ok，you can running in cluster mode

**Comment by chinchillia** [comment]
CREATE TABLE users (
	username varchar(50) NOT NULL PRIMARY KEY,
	password varchar(500) NOT NULL,
	enabled boolean NOT NULL
);

CREATE TABLE roles (
	username varchar(50) NOT NULL,
	role varchar(50) NOT NULL
);

INSERT INTO users (username, password, enabled) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE);

INSERT INTO roles (username, role) VALUES
