### ISSUE TITLE
nacos 2.0.1 client can not conllection server

### ISSUE THREAD

**Issue by hicker-kin** [alibaba/nacos#6721]
i use nacos 2.0.1 client to testing server conllection,it is failed ,and return the error message: 

**ErrCode:-401, ErrMsg:Client not connected,current status:STARTING**

![image](https://user-images.githubusercontent.com/42539536/130367239-473eecfd-849e-4723-a497-c40b60095369.png)

i debug and find grpc create connection failed !!  this is Why? how can i resolve it ?  thank you!

**Comment by KomachiSion** [comment]
see document https://nacos.io/zh-cn/docs/2.0.0-compatibility.html first

**Comment by KomachiSion** [comment]
No more response
