### ISSUE TITLE
openapi服务实例例下线ok，但再次刷新服务列表还存在该实例，nacos版本2.0.3

### ISSUE THREAD

**Issue by AmyYuan555** [alibaba/nacos#6723]
本地注册服务后，调用服务下注销实例操作
localhost:8848/nacos/v1/ns/instance?serviceName=cwos-meta-test&ip=127.0.0.1&port=8080
![image](https://user-images.githubusercontent.com/28822685/130381533-4554bb1e-8ad8-4be1-9c46-18816763091c.png)
查看服务实例表，还存在
![image](https://user-images.githubusercontent.com/28822685/130381517-422121c3-08b1-421a-9a7b-e8b5772f49fe.png)

**Comment by zarkzheng** [comment]
实例是持久化实例还是临时实例？如果是持久化实例，需要添加`&ephemeral=false`参数才能正常注销实例。

**Comment by AmyYuan555** [comment]
临时实例
![image](https://user-images.githubusercontent.com/28822685/130382872-c4ed4bcc-245b-4a72-8ab2-0ceca0134209.png)

**Comment by MajorHe1** [comment]
如果注册临时实例的进程一直在正常工作，你调用openapi注销了，但是原进程又会把实例注册上去

**Comment by AmyYuan555** [comment]
意思临时实例不能通过openapi完成注销实例吗

**Comment by AmyYuan555** [comment]
意思临时实例不能通过openapi完成注销实例吗

**Comment by AmyYuan555** [comment]
临时实例怎么注销呢

**Comment by MajorHe1** [comment]
> 临时实例怎么注销呢

把进程停了，这个实例就注销了

**Comment by korbanr** [comment]
Ok
