### ISSUE TITLE
linux(centos) start failed (version nacos-server 2.0.3 ）

### ISSUE THREAD

**Issue by jinxilongjxl** [alibaba/nacos#6726]
[root@iZuf6g6gmwubu8usf4dio6Z bin]# **sh startup.sh -m standalone**
/root/app/JDK11/bin/java   -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xlog:gc*:file=/root/app/NACOS2/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400 -Dloader.path=/root/app/NACOS2/plugins/health,/root/app/NACOS2/plugins/cmdb -Dnacos.home=/root/app/NACOS2 -jar /root/app/NACOS2/target/nacos-server.jar  --spring.config.additional-location=file:/root/app/NACOS2/conf/ --logging.config=/root/app/NACOS2/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos is starting with standalone
nacos is starting，you can check the /root/app/NACOS2/logs/start.out
[root@iZuf6g6gmwubu8usf4dio6Z bin]# **tail -f  /root/app/NACOS2/logs/start.out**
/root/app/JDK11/bin/java   -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xlog:gc*:file=/root/app/NACOS2/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400 -Dloader.path=/root/app/NACOS2/plugins/health,/root/app/NACOS2/plugins/cmdb -Dnacos.home=/root/app/NACOS2 -jar /root/app/NACOS2/target/nacos-server.jar  --spring.config.additional-location=file:/root/app/NACOS2/conf/ --logging.config=/root/app/NACOS2/conf/nacos-logback.xml --server.max-http-header-size=524288
**Error: Could not find or load main class
Caused by: java.lang.ClassNotFoundException:**

**Comment by brotherlu-xcq** [comment]
duplicate with https://github.com/alibaba/nacos/issues/6609

**Comment by Lin1Yang** [comment]
当我复制从-Dnacos.stand 直到524288，然后删除Dnacos.member.list 和 Dloader.path部分，在command中用java+这段信息。 程序就可以启动了。但是在目前只能用command的形式启动。
