### ISSUE TITLE
 Cluster instance status is inconsistent

### ISSUE THREAD

**Issue by jzdayz** [alibaba/nacos#6728]
**Describe the bug**
node1
![image](https://user-images.githubusercontent.com/35563513/130435610-f3d9a3f3-e18f-4eee-a3fb-5c91fa764a70.png)
node2
![image](https://user-images.githubusercontent.com/35563513/130435647-a2c19012-6174-44a7-9ccd-ce2c61496307.png)
node3
![image](https://user-images.githubusercontent.com/35563513/130435685-b2baaeb6-58f3-47b6-b79d-bbd64fb366a2.png)

How do I troubleshoot？

server: 2.0.0
client: 1.4.1

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
please upgrade to 2.0.3 and retry

**Comment by KomachiSion** [comment]
No more response
