### ISSUE TITLE
nacos 2.0.3启动脚本startup.sh错误导致在openjdk11下启动失败 

### ISSUE THREAD

**Issue by zhangzhiwei-163** [alibaba/nacos#6730]
问题截图：
![image](https://user-images.githubusercontent.com/60091656/130540183-e81dc5c6-5935-4efc-8f20-fae76f8fb72a.png)
修改方式，亲测有效：
源代码（startup.sh）
![image](https://user-images.githubusercontent.com/60091656/130540341-5968eaff-52ef-4169-8419-18784912efa5.png)
修改后：
![image](https://user-images.githubusercontent.com/60091656/130540406-61ecd77f-fbb6-440a-bc3a-abc0e51fd80f.png)

PS：感谢前面大佬们的帮助

**Comment by brotherlu-xcq** [comment]
It can work but there is still a problem, you can see #6335 . I try to fix it in PR #6725 .
