### ISSUE TITLE
Unbalanced service invocation load

### ISSUE THREAD

**Issue by houbinghao** [alibaba/nacos#6731]
Nacos version 1.3.2 uses Dubbo for service registration

A service has three registered servers. When calling a service, most requests will be loaded on two of them, and the other server will be called occasionally. Why? Isn't the load policy of Nacos polling? How should we solve this problem?

**Comment by realJackSun** [comment]
Which load balance protocol did you use in you client?

**Comment by KomachiSion** [comment]
No more  response
