### ISSUE TITLE
使用nacos作为配置中心，运行一段时间出现错误

### ISSUE THREAD

**Issue by Tmac007** [alibaba/nacos#6745]
[com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.client.naming - [callServer,617] - [NA] failed to request
java.net.SocketException: 打开的文件过多
不知有没有哪位同行遇到过此问题！

**Comment by realJackSun** [comment]
Nacos版本？以及报错信息？

**Comment by realJackSun** [comment]
另外，老兄你的题目是使用nacos作为配置中心，但是报错日志貌似是服务注册报错日志？

**Comment by Tmac007** [comment]
nacos 2.0.3，报错信息就是正文那个

**Comment by Tmac007** [comment]
> Nacos版本？以及报错信息？
nacos 2.0.3，报错信息就是正文那个

**Comment by KomachiSion** [comment]
No more response
