### ISSUE TITLE
springboot 多个配置文件下 nacos 只能读取到localhost:8848 serverAddr 地址的问题 

### ISSUE THREAD

**Issue by zhutie8111** [alibaba/nacos#6748]
**Describe the bug**
使用的环境是springboot，分别两个配置文件boostrap.properties 和 application-dev.properties，nacos的配置放在application-dev.properties配置文件中，发现系统启动后，NacosConfigProperties 这个类并不能读取到nacos的配置，在NacosConfigService这个类初始化时候 会读取Properties中的属性来创建ServerHttpAgent对象，但是 这时候在Properties中的属性还是localhost:8848,，创建ServerHttpAgent之后，里面的地址便无法修改，后面还会有一次读取application-dev.properties中nacos配置到NacosConfigProperties 对象的机会，但是已经无法改变ServerHttpAgent对象中的值，并且线程已经开始运行。

**Expected behavior**
希望ServerHttpAgent 这个能够正确读取到配置

**Acutally behavior**
由于ServerHttpAgent已经创建所以无法改变里面的 serverAddr，系统只能连接 localhost:8848 不停报错

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by zhutie8111** [comment]
> 1. spring boot 有 boostrap.properties？
> 2. 放在application-dev.properties中，你就需要在启动的时候制定环境为dev，否则spring不会读这个文件。
>    从描述上看像是spring的使用问题，应该不是nacos的问题。

第一点是笔误，应该是bootstrap.properties，这个应该不是用使用问题，是nacos使用springboot starter过早的启动了一些类，导致后面读取正确的nacos配置读取不到。启动时候肯定会指定一个profile。

**Comment by yuhuangbin** [comment]
你是使用Spring Cloud框架吧? 如果是的话请你把Nacos 配置相关的信息写在 `bootstrap-dev.properties`

**Comment by KomachiSion** [comment]
No more response from author, and this problem should be spring usage problem, not nacos' problem.
