### ISSUE TITLE
最新的版本控制台无法关闭吗？

### ISSUE THREAD

**Issue by shixitong** [alibaba/nacos#6751]
### turn off security
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**
增加了以下配置，但是打开控制台还是需要登录，有什么办法关闭吗？

**Comment by KomachiSion** [comment]
最开始是没有登录，后来做了鉴权和登录就一直在了，得让社区前端大佬看看有没有办法
