### ISSUE TITLE
nacos 2.0 版本，集群环境，微服务在k8s里，重启微服务，会导致nacos服务节点注册信息不一致

### ISSUE THREAD

**Issue by lnat** [alibaba/nacos#6757]
服务集群与nacos集群能正常启动注册，也能发现服务，但是，当微服务的pod大面积重启后，会发现nacos集群从节点注册信息没有，只有主节点能看到微服务注册的信息。nacos api无法调用 8848  8847  9848 9847 都是正常的。ui界面也是正常。

**Comment by realJackSun** [comment]
最后定位问题是由于重启的pod持久化信息丢失吗？@Inat

**Comment by lnat** [comment]
> @realJackSun 
> 
> 最后定位问题是由于重启的pod持久化信息丢失吗？@iNat
没有定位出来，目前是回退版本到1.2解决

**Comment by KomachiSion** [comment]
由于信息不足，无法判断具体原因， 推测是集群搭建有问题，比如没有完全按照文档升级到2.0模式，
又或者cluster.conf配置有问题等。

具体由于用户现场丢失，且缺少当时信息，且无法进行复现，因此先关闭issue。
