### ISSUE TITLE
是否有配置，让服务启动后可以注册到nacos，但默认是下线状态？

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#6759]
需求场景是这样的，我们准备了一些临时的服务节点，紧急情况需要加节点的话，我们可以随时启动这些临时节点。但这些节点是没有被验证过的，即，不知道上线后是否会报各种错误。
如果可以配置节点启动后默认下线的话，我们可以启动临时节点后，切很少的流量给它，如果有问题，及时下线。

**Comment by water040501212** [comment]
服务详情里面有“下线/上线”操作

**Comment by woshishitou** [comment]
> 服务详情里面有“下线/上线”操作

嗯嗯，谢谢，我知道有这个操作。我希望的是，服务启动后注册到nacos，默认是下线状态。否则从服务注册到nacos上到我点击下线，这段时间内，会有请求打过来。

**Comment by haoyann** [comment]
服务注册的时候设置`com.alibaba.nacos.api.naming.pojo.Instance#enabled`为false。

**Comment by woshishitou** [comment]
> 服务注册的时候设置`com.alibaba.nacos.api.naming.pojo.Instance#enabled`为false。

请问这是要在代码里写吗？还是可配置的？能麻烦说的详细一点吗？还有，想请教下您是从哪儿知道这么做的，我也找了一段时间，没找到。

**Comment by haoyann** [comment]
@woshishitou 在 SDK 里面 `com.alibaba.nacos.api.naming.NamingService#registerInstance(java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)` ，注册服务的时候。

**Comment by woshishitou** [comment]
> @woshishitou 在 SDK 里面 `com.alibaba.nacos.api.naming.NamingService#registerInstance(java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)` ，注册服务的时候。

明白了，非常感谢

**Comment by water040501212** [comment]
@woshishitou @haoyann 我的nacos-client1.4.1版本，按照haoyann说的，我在yml中设置了spring.cloud.nacos.discovery.instance-enabled: false，达到了woshishitou想要的效果：服务注册成功就是下线状态。

**Comment by woshishitou** [comment]
> @woshishitou @haoyann 我的nacos-client1.4.1版本，按照haoyann说的，我在yml中设置了spring.cloud.nacos.discovery.instance-enabled: false，达到了woshishitou想要的效果：服务注册成功就是下线状态。

请问您那边的nacos服务端版本是多少？我这边的服务端是2.0.1，客户端是1.4.1，按您说的在application.yml配置，发现配置本身确实有效（按住ctrl+单击能跳到对应代码），但启动服务后，在nacos上看不见

**Comment by water040501212** [comment]
@woshishitou 我这边服务端和客户端用的都是1.4.1版本。建议服务端和客户端版本保持一致。项目复杂的情况下，两者不一致的情况下出错的概率比较大。

**Comment by woshishitou** [comment]
> @woshishitou 我这边服务端和客户端用的都是1.4.1版本。建议服务端和客户端版本保持一致。项目复杂的情况下，两者不一致的情况下出错的概率比较大。

嗯嗯，明白了，感谢回复
