### ISSUE TITLE
The configuration information may has a syntax error. Are you sure to submit?

### ISSUE THREAD

**Issue by hxy1991** [alibaba/nacos#676]
Content: 
```
spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.initial-size=10
spring.datasource.max-active=20
```

![image](https://user-images.githubusercontent.com/2517258/51511030-9fd53f80-1e3a-11e9-86bc-99b2803f4b45.png)

![image](https://user-images.githubusercontent.com/2517258/51511041-a663b700-1e3a-11e9-9d03-13ad027881eb.png)

**Comment by YoReay** [comment]
`validateProperties(str = '') {
    const reg = /^[^=]+=[^=]+$/;
    return str
      .replace('\n\r', '\n')
      .split('\n')
      .every(_str => reg.test(_str.trim()));
  },`
=>
`validateProperties(str = '') {
    const reg = /^[^=]+=[\S]+$/;
    return str
      .replace('\n\r', '\n')
      .split('\n')
      .every(_str => reg.test(_str.trim()));
  },`

**Comment by YoReay** [comment]
It is caused by a regular expression.
