### ISSUE TITLE
[nacos 2.0.3] 两节点同时重启，会导致服务注册异常

### ISSUE THREAD

**Issue by welpeng** [alibaba/nacos#6763]
3个节点的集群，当宕机了2个节点，再启动宕机的一个或两个节点的时候，服务注册会发生异常，服务会反复的注册
![捕获](https://user-images.githubusercontent.com/24447512/131216824-6d6b52b1-4f40-45e4-ae9b-b17c74dff1e6.PNG)

**Comment by realJackSun** [comment]
可以看一下唯一没重启的机器的alipay-jraft.log，看看最后有没有选主成功

**Comment by KomachiSion** [comment]
No response from author, and from log we can see `receive invalid redirect request` which means the cluster deploy problem. So it should be an usage problem and users may have solved. Close issue.
