### ISSUE TITLE
The ClientWork.executeConfigListen() method on the client side of version 2. X has more than 150 lines, which is too long

### ISSUE THREAD

**Issue by seeger12138** [alibaba/nacos#6764]
**Is your feature request related to a problem? Please describe.**
1. The ClientWork.executeConfigListen() method has more than 150 lines, which is too long and not very readable.
2. The judgment of needAllSync and hasChangedKeys in ClientWork.executeConfigListen() method has nothing to do with the code segment of removeListenCachesMap.isEmpty(). If the removeListenCachesMap.isEmpty() function can return directly, it can avoid making judgment again, resulting in a small amount of performance loss

**Describe the solution you'd like**
1. The ClientWork.executeConfigListen() method extracts multiple functions 
2. returns directly when removeListenCachesMap. isEmpty(), without further judgment.

**Additional context**
![Code snippet for removeistencachesmap. Isempty()](https://user-images.githubusercontent.com/24733128/131218987-535cb9e1-5187-4500-b717-1e40daa2abbf.png)

**Comment by seeger12138** [comment]
I'd love to contribute it

**Comment by KomachiSion** [comment]
Assignees has no action for a long time, close first.
