### ISSUE TITLE
在nacos console点击服务下线后，服务还是会被调用

### ISSUE THREAD

**Issue by hegphegp** [alibaba/nacos#6766]

**Comment by realJackSun** [comment]
可能是点击下线之后，由于客户端尚未刷新服务列表，短时间之内还会访问下线的服务？

**Comment by gfgfggf1988** [comment]
针对之前提给你们的问题，尝试使用2.0.3版本。dubbo服务端下线，客户端依然能调用到服务，原先的no privider失效

**Comment by gfgfggf1988** [comment]
> 可能是点击下线之后，由于客户端尚未刷新服务列表，短时间之内还会访问下线的服务？

升级2.0.3版本后，双nacos服务在不同命名空间下提供同名接口dubbo服务。
1.控制台点击下线，客户端50多秒左右才会出现no provider效果
2.只下线n1空间下的dubbo服务接口，但是调用n2同名服务接口也出现no provider

**Comment by gfgfggf1988** [comment]
> 可能是点击下线之后，由于客户端尚未刷新服务列表，短时间之内还会访问下线的服务？

升级2.0.3版本后也会有该问题，双nacos服务在不同命名空间下提供同名接口dubbo服务。该问题采用https://github.com/alibaba/nacos/issues/6679测试过程
1.控制台点击下线，客户端50多秒左右才会出现no provider效果
2.只下线n1空间下的dubbo服务接口，但是调用n2同名服务接口也出现no provider

**Comment by KomachiSion** [comment]
可能是推送有问题，需要看一下naming-push.log 看下是否有推送失败。

关于问题2： namespace是强隔离，出现该问题一定是你注册错了namespace，或n2的对应服务出问题导致的。

**Comment by realJackSun** [comment]
@hegphegp make sure the NamingService which register and the NamingService which disable is the same one.
More than 7 days no response, close
