### ISSUE TITLE
Optimizing join and conditions in dynamic SQL

### ISSUE THREAD

**Issue by dingli985** [alibaba/nacos#6768]
## Issue Description

Type: *bug report* or *feature request*

### Tell us your environment
 - OS: [e.g. Windows10]
 - Version [e.g. nacos-server 2.0.3]
 - Module [e.g. config]

### Anything else we need to know?
This is the first time FOR me to submit questions and PR. Please tell me if there is anything wrong.

**Comment by KomachiSion** [comment]
Nobody want to do this enhancement. Expired
