### ISSUE TITLE
How can I choose bootstrap.yml according to db config?

### ISSUE THREAD

**Issue by VAEAZE** [alibaba/nacos#6778]
I have two nacos bootstrap.yml which means two nacos with different ip, I want to load one of the bootstrap.yml according to db config.

For example, if my loadVariable value from db config is A, I want to load bootstrap-a.yml. How can I do that?

Here is my purpose step:

1:search data from db to decide load bootstrap-a.yml or bootstrap-b.yml
2:register the service to nacos according to bootstrap config file

**Comment by KomachiSion** [comment]
1. boostrap.yml is a spring cloud file, not nacos'. please ask spring cloud community.
2. I think if spring clould file load successfully, the register feature will work well.

Please move to spring cloud community ask for answer.
