### ISSUE TITLE
nacos服务列表出现跳变

### ISSUE THREAD

**Issue by yangbo1987** [alibaba/nacos#6780]
环境：
boot 2.2.6.RELEASE
nacos:1.2.1 
cloud: Hoxton.SR3 
alibaba:2.2.1.RELEASE

**Comment by yangbo1987** [comment]
问题同#3945 不过这边使用的是cloud没有用dubbo

**Comment by KomachiSion** [comment]
跳变原因就2种：
1. 集群搭建有问题，导致数据同步或心跳路由出现问题。
2. 应用自身问题或网络问题，导致不停注销注册服务。

**Comment by yangbo1987** [comment]
> 跳变原因就2种：
> 
> 1. 集群搭建有问题，导致数据同步或心跳路由出现问题。
> 2. 应用自身问题或网络问题，导致不停注销注册服务。

nacos-server有多个namespace(用作环境区分) 就其中一个namespace有问题   同一个namespace下 注册了多个微服务实例，就其中一个服务频繁掉线  nacos-server重启后， 一下都OK了

**Comment by KomachiSion** [comment]
那可能是旧版本的bug，最好是升级新版本。

**Comment by realJackSun** [comment]
Long time no response from author, close.
