### ISSUE TITLE
客户端从注册中心找的服务的端口有时候不正确

### ISSUE THREAD

**Issue by zyzyzy523** [alibaba/nacos#6782]
版本信息
客户端版本 2.0.3
服务端版本 v2.0.3
部署方式 k8s部署3个服务端节点

问题：
服务间调用偶发会走80端口的地址，比如有两个服务。A和B ，A服务端口为9083，B服务端口9084。 正常B服务调用A服务，应该访问A服务的9083端口，但是有时候会访问A服务的80端口，导致调用异常。实际nacos注册中心注册A服务的端口是9083。
偶尔出现一次，什么都不进行操作，马上又对了。
下图为我们出现的情况：
![image](https://user-images.githubusercontent.com/48322364/131596788-6e767651-7154-43a8-864e-c5e13cb54a29.png)
![image](https://user-images.githubusercontent.com/48322364/131596907-b90bafe4-bacf-4939-9471-200097be65ae.png)

**Comment by KomachiSion** [comment]
看一下 ${user.home}/logs/nacos/naming.log 中的地址和端口是不是正确的，如果是正确的，可能是你的应用程序，或其他组件对端口进行了修改。

**Comment by zyzyzy523** [comment]
我看了，地址和端口都是正确的，而且就偶发的出现一下。不作任何操作马上有好了。

**Comment by KomachiSion** [comment]
那就不是nacos的问题了，应该是你的组件或者应用程序有缓存或者默认端口之类的，导致了这个问题，再推送刷新了数据之后就正常了。
