### ISSUE TITLE
Does namingService method has timeout properties

### ISSUE THREAD

**Issue by jxd134** [alibaba/nacos#6786]
https://github.com/alibaba/nacos/blob/9658d23b079d801ec436ef62bde40d6c32de7e6a/api/src/main/java/com/alibaba/nacos/api/naming/NamingService.java#L278

I want to using namingService to list instances of special micro service in spring cloud.
But i can't find timeout prop for listInstances method.
> nacos-client version is 1.4.2, sprin-cloud-starter-alibaba-nacos-config version is 2.2.6.RELEASE

**Comment by KomachiSion** [comment]
`-Dcom.alibaba.nacos.client.naming.rtimeout` for 1.X client

**Comment by caochengxiang** [comment]
> `-Dcom.alibaba.nacos.client.naming.rtimeout` for 1.X client

Excuse me, why is this value set to 50 seconds, which is greater than 30 seconds of long polling? What is the purpose of consideration
