### ISSUE TITLE
后期是否会考虑增加服务的作用域

### ISSUE THREAD

**Issue by bluesecret** [alibaba/nacos#6787]
1.在学习过程中，发现每个服务的作用范围只在所属namespace下的group中， 后期是否考虑添加服务的作用范围（如跨group可见）

2.namespace作用在于环境隔离，是否考虑添加一个共享的namespace呢

**Comment by KomachiSion** [comment]
1. 目前就是跨group可见可访问
2. 不考虑，namespace就是为了强隔离而存在的， 一旦有互通的namespace就没有意义了。
