### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-config集成最新版本client2.0.3问题

### ISSUE THREAD

**Issue by LBJWt** [alibaba/nacos#6788]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. nacos client 2.0.3版本已经发布了，但是spring-cloud-starter-alibaba-nacos-config 里面集成的client最新的还是1.4.2,有没有集成最新的client到starter的计划
2. 
3.

**Comment by KomachiSion** [comment]
需要询问下spring-cloud-alibba社区
