### ISSUE TITLE
如何获取json格式的数据

### ISSUE THREAD

**Issue by jiangqs3** [alibaba/nacos#6790]
我在nacos服务端配置了json格式的数据，在bootstrap.properties里配置了：
spring.cloud.nacos.config.extension-configs[0].data-id=xxx.json
spring.cloud.nacos.config.extension-configs[0].group=DEFAULT_GROUP
spring.cloud.nacos.config.extension-configs[0].refresh=true
在nacos中配置的内容为：
{"id": 1, "name": "tom"}
这样我要怎么在程序中获取到配置的json数据呢（通过修改配置，在日志中可以看到数据刷新），比如，用properties格式配置，我在程序里用@Value("${key}")获取到对应的value值，但是json格式的怎么获取呢？还请大佬指导下。

**Comment by KomachiSion** [comment]
在spring里，所有格式的配置最终都会转化成properties格式， 如果你希望获取json格式，需要自行添加typeHandler。

具体实现需要自行搜索下如何实现。

**Comment by WilliamShoww** [comment]
> 在spring里，所有格式的配置最终都会转化成properties格式， 如果你希望获取json格式，需要自行添加typeHandler。
> 
> 具体实现需要自行搜索下如何实现。
看源码好像没有看到拦截器相关，能仔细说一下typeHandler吗？或者提供一个博客链接。谢谢
