### ISSUE TITLE
Console UI bug

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#680]
1. Click update cluster button, redirect to login page:
![image](https://user-images.githubusercontent.com/4593375/51523053-c0ff5580-1e65-11e9-9e44-ae26e87d3b28.png)

2. Prompt 'ProtectThreshold' is required while ProtectThreshold is already assigned:
![image](https://user-images.githubusercontent.com/4593375/51523087-d8d6d980-1e65-11e9-9462-8e2d1d417901.png)

**Comment by loadchange** [comment]
Fixes #862
