### ISSUE TITLE
nacos客户端升级为2.0之后，springboot容器无法获取nacos中配置

### ISSUE THREAD

**Issue by hjc970414** [alibaba/nacos#6804]
springboot服务中nacos客户端升级为2.0后，直接运行jar包可以获取到nacos配置，使用容器方式启动服务无法获取nacos中配置。
使用nacos 1.0版本，直接运行jar和容器启动都可以获取nacos配置。

**application.yml文件内容**
nacos:
  config:
    type: yaml
    server-addr: 192.168.xxx.xxx:8848
    namespace: xxx
    data-id: xxx
    auto-refresh: true
    group: xxx
    username: nacos
    password: nacos
    bootstrap:
      enable: true
      log:
        enable: true
spring:
  profiles:
    active: dev
logging:
  config: ./config/log4j2-dev.xml

**Dockerfile文件内容**
ARG JDK_IMAGE
ARG GO_IMAGE
FROM ${GO_IMAGE} as builder
WORKDIR /build
COPY xjar.go /build/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o xjar .
FROM ${JDK_IMAGE}
MAINTAINER Galaxy
VOLUME /tmp
WORKDIR /xxx
COPY --from=builder /build .
COPY config config
ARG JAR_FILE
COPY ${JAR_FILE} xxx.xjar
ENV JAVA_OPTS=" -Xmx10g -Xms10g -Xmn512m -Xss256k -XX:MetaspaceSize=128m -XX:MaxPermSize=128m -XX:SurvivorRatio=2 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:+UseCMSCompactAtFullCollection -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 "
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
ENTRYPOINT [ "sh", "-c", "./xjar java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar xxx.xjar" ]

代码中获取单个配置
@NacosValue(value = "${xxx.xxx}", autoRefreshed = true)

**Comment by KomachiSion** [comment]
单纯升级nacos客户端可能会导致问题，建议升级nacos-spring-boot的最新版本。

**Comment by realJackSun** [comment]
More than 7 days no response, close
