### ISSUE TITLE
升级2.0后，springboot服务是否需要配置9848，9849端口

### ISSUE THREAD

**Issue by hjc970414** [alibaba/nacos#6809]
![image](https://user-images.githubusercontent.com/78406684/132272138-c54ac7c9-48aa-4b05-a72e-18ffb49cbcf1.png)

按照官方文档说明，升级2.0后，以docker方式启动springboot服务，该怎么配置9848，9849端口

**Comment by wangdongyun** [comment]
不需要

**Comment by JavaAjust** [comment]
> 不需要

那服务器需要暴露9848和9849端口出来吗 @wangdongyun

**Comment by realJackSun** [comment]
暴露出来8848和9849即可，参考一下这个图
![image](https://user-images.githubusercontent.com/58767027/132782532-266313c8-1873-4e31-b800-9b2766dfa965.png)

**Comment by 9AM751** [comment]
`docker run --name nacos -e MODE=standalone -p 8848:8848 -p 9848:9848 -d nacos/nacos-server:latest`
