### ISSUE TITLE
nacos start.cmd默认以集群方式启动，建议修改成单机启动

### ISSUE THREAD

**Issue by lecysky** [alibaba/nacos#6811]
默认是以集群方式启动，建议修改成单机

**Comment by DickensTone** [comment]
你能详细说说你为什么这样建议吗？我学习nacos一直使用的是单机模式，感觉改为单机启动确实方便我学习。

Can you elaborate on why you suggest this? I always use the stand-alone mode when learning Nacos. I feel that changing to stand-alone startup is really convenient for me to learn.

**Comment by lecysky** [comment]
> 你能详细说说你为什么这样建议吗？我学习nacos一直使用的是单机模式，感觉改为单机启动确实方便我学习。
> 
> Can you elaborate on why you suggest this? I always use the stand-alone mode when learning Nacos. I feel that changing to stand-alone startup is really convenient for me to learn.

作为一个初学者，我的考虑是：
     1. 下载完nacos后。首先要确保我电脑的运行环境没有问题，且下载的nacos-server是完整的，因此想首先以单机模式启动。
     2. 集群模式相比单机模式是更高一级的启动，学习的优先级较低，应该单机模式-->集群模式。
     3. 大部分人下载nacos是为了学习（仅使用单机模式），start.cmd集群模式需要配置（初学者一般不知道），默认集群模式是启动不起来的。

**Comment by realJackSun** [comment]
不默认以集群模式启动，怎么让初学者有动力去学习集群模式，提升技术，哈哈
