### ISSUE TITLE
naocs 集群 mysql 删除配置文件失败

### ISSUE THREAD

**Issue by 408484409** [alibaba/nacos#6812]
nacos:2.0.3 使用 mysql 集群 删除配置文件失败
net::ERR_EMPTY_RESPONSE
![image](https://user-images.githubusercontent.com/28914368/132279536-63517404-09c3-4a2d-b155-74b862b2c62c.png)

**Comment by KomachiSion** [comment]
麻烦提供服务端对应的错误日志。
