### ISSUE TITLE
Jar package startup parameters are not refreshed

### ISSUE THREAD

**Issue by malversation** [alibaba/nacos#6815]
Console modify gateway route configuration parameters, idea mode will be refreshed, jar package mode is not refreshed.
After checking the information said that the version of the problem, the use of other versions of the problem still exists.

Idea Startup mode Log information is as follows
u.j.c.RefreshScopeRefreshedEventListener : Refreshing cached encryptable property sources
u.j.c.RefreshScopeRefreshedEventListener : Refreshing cached encryptable property sources
o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [spring.cloud.gateway.routes[1].predicates[0]]

The log information about the jar package startup mode is as follows
u.j.c.RefreshScopeRefreshedEventListener : Refreshing cached encryptable property sources
u.j.c.RefreshScopeRefreshedEventListener : Refreshing cached encryptable property sources
o.s.c.e.event.RefreshEventListener       : Refresh keys changed: []

nacos server version: 2.0.3
nacos client version: 2.0.3
spring boot version: 2.3.2.RELEASE
spring cloud alibaba version: 2.2.6.RELEASE
spring cloud version: Hoxton.SR9

The trouble can be solved. It has been bothering me for a long time. Thanks.

**Comment by realJackSun** [comment]
spring boot version: 2.3.2.RELEASE

改成spring boot 2.0.3试一试？

**Comment by KomachiSion** [comment]
If idea model can work well, it means the code and nacos are not problem. It might be your environment problem. 

Or provide nacos logs in ${user.home}/logs/nacos to check whether the configuration has been pushed into your app but your app not fresh cache.

**Comment by malversation** [comment]
The replacement version cannot be resolved. There are push messages in the NACOS log.

The differences between logs are as follows:

Initial Startup Log
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[lover-gateway] & group[DEFAULT_GROUP]
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[lover-gateway-dev.yaml] & group[DEFAULT_GROUP]

Gateway parameters were modified
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[null.properties] & group[DEFAULT_GROUP]
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[null-dev.properties] & group[DEFAULT_GROUP]

Why the dataId obtained by dynamic refresh is null，and the format is still properties，the bootstrap file has the configuration format YAML，I think that's the problem.

**Comment by malversation** [comment]
@KomachiSion 
The replacement version cannot be resolved. There are push messages in the NACOS log.

The differences between logs are as follows:

Initial Startup Log
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[lover-gateway] & group[DEFAULT_GROUP]
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[lover-gateway-dev.yaml] & group[DEFAULT_GROUP]

Gateway parameters were modified
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[null.properties] & group[DEFAULT_GROUP]
c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[null-dev.properties] & group[DEFAULT_GROUP]

Why the dataId obtained by dynamic refresh is null，and the format is still properties，the bootstrap file has the configuration format YAML，I think that's the problem.
