### ISSUE TITLE
ClientWorker中的cacheMap 在启动完成后  什么情况下size还会增加，需要10ms去轮询它的大小？

### ISSUE THREAD

**Issue by neilxxx** [alibaba/nacos#6816]
ClientWorker中的cacheMap 在启动完成后  什么情况下size还会增加，需要10ms去轮询它的大小？

**Comment by realJackSun** [comment]
cacheMap是用来缓存被订阅的配置的，当新订阅一些配置的时候，他的size就会增加。

**Comment by neilxxx** [comment]
> cacheMap 是免被订阅的配置的，当新订阅一些配置的时候，他的大小就会增加。

没理解，配置不是在项目启动时就已经订阅所有该项目的配置了么 ，用什么方式可以在项目启动后再增加新订阅？

**Comment by neilxxx** [comment]
> > cacheMap 是免被订阅的配置的，当新订阅一些配置的时候，他的大小会​​增加。
> 
> 没理解，配置不是在项目启动时就已经订阅了所有该项目的配置了么，用什么方式可以在项目启动再添加新订阅？

就是scheduleWithFixedDelay这个线程池每１０ｓ轮询一次的意义是什么？
什么情况下在项目启动后还会执行addListener方法？目前只看到在onApplicationEvent事件中会去执行，没有发现在在已经运行的情况下调用addListener的情况，所以已运行情况下cacheMap 的ｓｉｚｅ应该不会变吧？需要每１０ｓ去执行么

**Comment by water040501212** [comment]
客户端为了提升寻找要调用服务的效率，会将服务端的服务注册信息缓存一份在本地。服务端的注册信息会因为业务系统的节点上线下线而改变，客户端需要与服务端尽量即时的保持同步，所以会使用定时任务去重新获取服务端最新的注册信息。
