### ISSUE TITLE
最新版本2.0.3，服务详情里面有分页，但是固定只能选每页10条，没办法更改条数

### ISSUE THREAD

**Issue by PEIYANGXINQU** [alibaba/nacos#6819]
![image](https://user-images.githubusercontent.com/3368962/132384061-40f28ac5-715c-4742-8f12-d781ceee9083.png)
服务列表有条数设置，但是进去服务详情列表，不能设置，建议增加条数设置选项
![image](https://user-images.githubusercontent.com/3368962/132384235-555e8f78-8b0c-4215-b211-85e97099a348.png)

**Comment by brotherlu-xcq** [comment]
是的，实例列表这里前端没有做分页。

**Comment by PEIYANGXINQU** [comment]
收到，谢谢！
