### ISSUE TITLE
namingLoadCacheAtStart="true"  Cause No servers found 

### ISSUE THREAD

**Issue by wushengju** [alibaba/nacos#6821]
**Describe the bug**
if i have set namingLoadCacheAtStart="true",then i run my application, it can‘t find the service

**Expected behavior**
io.grpc.StatusRuntimeException: UNAVAILABLE: No servers found for xxxx
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall$original$3JHVp7Vj(ClientCalls.java:156)
	at io.grpc.stub.ClientCalls.blockingUnaryCall$original$3JHVp7Vj$accessor$GlMOoaFN(ClientCalls.java)
	at io.grpc.stub.ClientCalls$auxiliary$ufSDDyB4.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.StaticMethodsInter.intercept(StaticMethodsInter.java:83)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java)

 
i find error in code

//1.serviceName=DEFAULT_GROUP@@aaa ,clusters=""
public ServiceInfo getServiceInfo(final String serviceName, final String clusters) {
        
        NAMING_LOGGER.debug("failover-mode: " + failoverReactor.isFailoverSwitch());
        String key = ServiceInfo.getKey(serviceName, clusters);
        if (failoverReactor.isFailoverSwitch()) {
            return failoverReactor.getService(key);
        }
        //2.use key=DEFAULT_GROUP@@aaa get serviceObj is not null
        ServiceInfo serviceObj = getServiceInfo0(serviceName, clusters);
        
        if (null == serviceObj) {
            serviceObj = new ServiceInfo(serviceName, clusters);
            
            serviceInfoMap.put(serviceObj.getKey(), serviceObj);
            
            updatingMap.put(serviceName, new Object());
            updateServiceNow(serviceName, clusters);
            updatingMap.remove(serviceName);
            
        } else if (updatingMap.containsKey(serviceName)) {
            
            if (UPDATE_HOLD_INTERVAL > 0) {
                // hold a moment waiting for update finish
                synchronized (serviceObj) {
                    try {
                        serviceObj.wait(UPDATE_HOLD_INTERVAL);
                    } catch (InterruptedException e) {
                        NAMING_LOGGER
                                .error("[getServiceInfo] serviceName:" + serviceName + ", clusters:" + clusters, e);
                    }
                }
            }
        }
        
        scheduleUpdateIfAbsent(serviceName, clusters);
        //3. serviceObj.getKey()=DEFAULT_GROUP@@aaa@@DEFAULT serviceInfoMap has not value
        return serviceInfoMap.get(serviceObj.getKey());
    }

is this is ok or is a bug

**Comment by KomachiSion** [comment]
namingLoadCacheAtStart="true", will load snapshot from local disk when start nacos-client. 
If no snapshot in your local disk, can't find service is normal.

Failover is other feature, your print codes is not relative with namingLoadCacheAtStart="true",

**Comment by KomachiSion** [comment]
duplicate with #6823
