### ISSUE TITLE
Nacos 2.0.3 (docker Derby ) auth controls failure

### ISSUE THREAD

**Issue by iPush** [alibaba/nacos#6822]
**Describe the bug**
Running Nacos 2.0.3 by  [Nacos Docker Derby](https://nacos.io/zh-cn/docs/quick-start-docker.html)

I created two namespaces and associated users&roles.

| namespace | role |  user | auth |
| --- | --- | --- | --- |
| a | a_admin | a | RW |
| b | b_admin | b | RW |

 

**Expected behavior**
User a should only read/write configs in namespace a. So do user b

**Acutally behavior**
Log in Nacos in User a , I can still see configs in namespace b. And even create/edit/delete any configs in namespace b.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: OSX mojave
 - Version 2.0.3
 - Module  config
 - SDK web

**Additional context**

**Comment by iPush** [comment]
<img width="946" alt="nacos_角色" src="https://user-images.githubusercontent.com/899754/132438291-04dad123-c749-4452-a47c-567d04365904.png">
<img width="1021" alt="nacos_权限" src="https://user-images.githubusercontent.com/899754/132438309-bbd1be83-d45f-4422-8f0c-8fcb5ba72a8d.png">
![Uploading nacos_a_view_ns.png…]()

<img width="1241" alt="nacos_b_write_ns_a_succesfully" src="https://user-images.githubusercontent.com/899754/132438324-ee19a812-92ab-4b67-b846-4e8833ee2bb0.png">

**Comment by realJackSun** [comment]
鉴权插件正在开发中，#5696
开发完成之后，就可以通过配置鉴权插件来进行更精密的权限控制了。

The authentication plugin is under development, #5696
After completion, you can carry out better authentication control by authentication plug-ins.

**Comment by KomachiSion** [comment]
你没看鉴权吧，建议仔细看看文档，我本地测试下是没问题的。

**Comment by iPush** [comment]
我根据 [Nacos 权限认证](https://nacos.io/zh-cn/docs/auth.html) 这篇文档，添加环境变量之后启动 `nacos`

```
export NACOS_AUTH_ENABLE=true

docker-compose -f example/standalone-derby.yaml up
```

还是类似的结果。
为了避免干扰，参照上次测试的方法，新建了用户 `c`， 授予用户 `c` 对于 `namespace c` 权限

但是 `c` 仍然可以对其他 namespace 配置进行读写/创建




> 你没开鉴权吧，建议仔细看看文档，我本地测试下是没问题的。

**Comment by iPush** [comment]
或者说 `nacos` 目前只是认证？ 没有做 `RBAC` 这样的鉴权？
我之前的操作，都是在 `nacos UI` 上，通过 `Authority Control` 进行的

**Comment by iPush** [comment]
@realJackSun @KomachiSion  所以这个问题，究竟是一个待开发的权限插件问题，还是我本地环境的配置问题？ 谢谢
