### ISSUE TITLE
when set loadCacheAtStart=true cause problem

### ISSUE THREAD

**Issue by wushengju** [alibaba/nacos#6823]
**Describe the bug**
when set loadCacheAtStart=true then load cache file from disk,the file name is "DEFAULT_GROUP%40%40xxx-cloud-provider@@DEFAULT", but serviceInfoMap key is "DEFAULT_GROUP%40%40xxx-cloud-provider" is will cause service can't find
![image](https://user-images.githubusercontent.com/9883734/132440485-18134b7c-f750-494c-a671-720d3247d617.png)
!

i think the problem may be in the code
public ServiceInfo(String key) {
        int maxIndex = 2;
        int clusterIndex = 1;
        int serviceNameIndex = 0;
        String[] keys = key.split("@@");
        if (keys.length >= maxIndex) {
            this.name = keys[serviceNameIndex];
            this.clusters = keys[clusterIndex];
        }

        this.name = keys[0];
    }

when the paramter is DEFAULT_GROUP%40%40xxx-cloud-provider@@DEFAULT ,name=DEFAULT_GROUP and clusters=xxx-cloud-provider 
you can see the picture 
[image](https://user-images.githubusercontent.com/9883734/132440528-923d3932-7b39-4d06-8518-9f20e0bd2c28.png)

**Comment by KomachiSion** [comment]
can you update to 1.4.2 or 2.0.3 and retry. I remember the problem has been fixed in some version.
