### ISSUE TITLE
Nacos1.0 was upgraded to 2.0

### ISSUE THREAD

**Issue by ruirui9** [alibaba/nacos#6826]
![5d5c2f2e0451aad8242ba6c7679fd60](https://user-images.githubusercontent.com/60023402/132444294-5c3f244a-63c1-4c74-a4e2-e0c503fd557a.png)

**Comment by brotherlu-xcq** [comment]
你检查一下你的/usr/local/nacos/conf/schema.sql文件还在吗？还有检查一下你的logs/nacos.log里面的异常堆栈呢？里面会有具体的异常信息

**Comment by ruirui9** [comment]
![image](https://user-images.githubusercontent.com/60023402/132610837-f3761f59-ab03-4d2f-bfb0-166c93819e16.png)
wenj文件在的 我是把新版本的conf目录都拷贝过来了    这个异常好像是创建什么东西没创建成功 下边还有好多

**Comment by brotherlu-xcq** [comment]
nacos-api依赖冲突了，这个1.x的api应该没有这个字段。把低版本的nacos-api去掉。
![image](https://user-images.githubusercontent.com/25661357/132611660-bc09f316-5b86-4459-8492-128689e93f5e.png)

**Comment by ruirui9** [comment]
> nacos-api依赖冲突了，这个1.x的api应该没有这个字段。把低版本的nacos-api去掉。
> ![image](https://user-images.githubusercontent.com/25661357/132611660-bc09f316-5b86-4459-8492-128689e93f5e.png)

冒昧的问一下 是根据这个url把里边的字段注释掉么

**Comment by brotherlu-xcq** [comment]
不是的，看你的报错信息，应该是你的工程里面有低版本的nacos-api jar包低版本和高版本的共存了。所以出现了NoSuchFieldError的异常。你把低版本的去掉应该就可以正常启动了。

**Comment by ruirui9** [comment]
> 不是的，看你的报错信息，应该是你的工程里面有低版本的nacos-api jar包低版本和高版本的共存了。所以出现了NoSuchFieldError的异常。你把低版本的去掉应该就可以正常启动了。
可是我target目录下就一个高版本jar包 好奇怪

**Comment by realJackSun** [comment]
可以用maven里面的<exclude>解决一下依赖冲突

**Comment by ruirui9** [comment]
> 可以用maven里面的 exclude或者shade解决一下依赖冲突

抱歉啊 我不太懂这个java目录结构 上午看了一下你说的东西 每太看明白 能否换个平台交流

**Comment by realJackSun** [comment]
@ruirui9 现在解决了吗？
