### ISSUE TITLE
nacas 某个微服务实例为0，却能提供服务

### ISSUE THREAD

**Issue by henpangpang** [alibaba/nacos#6828]

**Comment by henpangpang** [comment]
nacas 1.4.0版本，nacos某个微服务的实例为0，却能提供服务
nacas-api maven版本是1.0

**Comment by realJackSun** [comment]
从这个log中看,你的服务提供者在不停的变更，检查一下原因 @henpangpang

**Comment by KomachiSion** [comment]
先确认下consumer端是否收到了该服务的空列表推送，如果收到了，还在调用，那多半是你应用的问题。
1. 可能用的根本不是这个服务
2. 可能你应用有某些处理，会继续使用。

**Comment by henpangpang** [comment]
> 从这个log中看,你的服务提供者在不停的变更，服务调用者调用时存在一定的刷新时间，所以出现了有时候调用不到的情况，检查一下业务方频繁变更的原因 @henpangpang

应用的问题，把日志清了就没啥问题了，有点神奇

**Comment by henpangpang** [comment]
> 先确认下consumer端是否收到了该服务的空列表推送，如果收到了，还在调用，那多半是你应用的问题。
> 
> 1. 可能用的根本不是这个服务
> 2. 可能你应用有某些处理，会继续使用。

应用的问题，把日志清了就没啥问题了，有点神奇

**Comment by realJackSun** [comment]
看起来已经解决了，先关闭issue
