### ISSUE TITLE
nacos2.0.0集群关闭双写失败

### ISSUE THREAD

**Issue by malin18280496983** [alibaba/nacos#6829]
Describe the bug
在nacos集群中网关服务一直在处理请求，但是控制台的注册列表中没有展示网关服务

Acutally behavior
尝试关闭双写来解决：curl -X PUT 'localhost:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false'
但是执行失败：{"timestamp":"2021-09-08T15:32:56.399+08:00","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/ns/operator/switches"}
我猜想是因为nacos启用鉴权导致的吗？这种情况要如何关闭双写呢

**Comment by brotherlu-xcq** [comment]
这个是鉴权问题，可以先登录，然后获取到token，请求关闭双写的时候带上。

**Comment by malin18280496983** [comment]
> 这个是鉴权问题，可以先登录，然后获取到token，请求关闭双写的时候带上。

确实如此，有个accessToken的参数用于鉴权。
