### ISSUE TITLE
nacos config bug

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#6830]
我创建了两份配置，Data ID分别是Redis和Cassandra，配置格式都是用properties。
两份配置里都有字段port。当我拉取Data ID是Redis的配置，取到的port是Cassandra里的配置。

nacos 版本是2.0.0
config引用： 
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.1</version>
 </dependency>

是引用太旧本来有bug，还是nacos的问题？

**Comment by realJackSun** [comment]
应该不会是版本太旧，检查一下nacosPropertySource中的配置是否是正确的？
