### ISSUE TITLE
How to modify ribbon scheduled task time?

### ISSUE THREAD

**Issue by waidinsamkeit** [alibaba/nacos#6832]
Microservices deployed in kubernetes are slow to access for the first time after each flush is started
The Nacos page service is still not offline, and  need to wait 10s or more to register with Nacos
I What are the solutions.

**Comment by realJackSun** [comment]
Modify the ribbon to a shorter time?
e.g.
eureka.client.registryFetchIntervalSeconds=1

**Comment by waidinsamkeit** [comment]
We don't use Eureka. We only use Nacos, ribbon, and feign

**Comment by waidinsamkeit** [comment]
> Modify the ribbon to a shorter time?
> e.g.
> eureka.client.registryFetchIntervalSeconds=1
Is it added directly like this? Where can I add it?
ribbon.client.registryFetchIntervalSeconds=1

**Comment by waidinsamkeit** [comment]
We didn't use Eureka. Did we set Eureka field to ribbon directly

**Comment by waidinsamkeit** [comment]
> 将丝带修改为更短的时间？
> 例如，
> 尤里卡.客户端.注册内部秒=1
We didn't use Eureka. Did we set Eureka field to ribbon directly
