### ISSUE TITLE
How to migrate data when version is upgraded

### ISSUE THREAD

**Issue by naturalyui** [alibaba/nacos#684]
**Is your feature request related to a problem? Please describe.**
您好，我想从nacos-server-0.7.0升级到nacos-server-0.8.0我应该怎么把旧的配置数据迁移过去？旧版本是不是需要将数据存入mysql中才能迁移？

English translation：Hello, I want to upgrade from nacos-server-0.7.0 to nacos-server-0.8.0. How should I migrate the old configuration data? Does the old version need to store data in mysql to migrate?

**Describe the solution you'd like**
支持批量的导入和导出

English translation：Support batch import and export

**Comment by yanlinly** [comment]
refer:https://github.com/alibaba/nacos/releases/tag/0.8.0
Mysql adds the following two tables to decompress and upgrade directly, compatible.

Add users/roles tables

CREATE TABLE users (
	username varchar(50) NOT NULL PRIMARY KEY,
	password varchar(500) NOT NULL,
	enabled boolean NOT NULL
);

CREATE TABLE roles (
	username varchar(50) NOT NULL,
	role varchar(50) NOT NULL
);

INSERT INTO users (username, password, enabled) VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', TRUE);

INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');

**Comment by naturalyui** [comment]
Thanks for the reply, I have completed the data migration through mysql as a medium, expecting the later version to support one-click import and export :)
