### ISSUE TITLE
When Tomcat is stopped, the nacos process cannot be shutdown.

### ISSUE THREAD

**Issue by SamaDream** [alibaba/nacos#6842]
**Describe the bug**
After tomcat is shutdown, the tomcat thread is still running.  

**Expected behavior**
After tomcat is shutdown, the tomcat thread ends normally .

**How to Reproduce**
1. Start Tomcat, deploy nacos standalone server .
2. the program runs normally.
3. shutdown Tomcat, a warning message is displayed, the nacos process cannot be shut down.

**Desktop :**
 - OS：windows 10
 - Version ：nacos-server 2.0.1
 - JDK：jdk1.8.0_291
 - Tomcat：apache-tomcat-9.0.50

**Additional context**
`09-Sep-2021 14:52:19.054 信息 [main] org.apache.catalina.core.StandardServer.await 通过关闭端口接收到有效的关闭命令。正在停止服务器实例。
09-Sep-2021 14:52:19.055 信息 [main] org.apache.coyote.AbstractProtocol.pause 暂停ProtocolHandler["http-nio-8848"]
09-Sep-2021 14:52:19.177 信息 [main] org.apache.catalina.core.StandardService.stopInternal 正在停止服务[Catalina]
2021-09-09 14:52:19.183  INFO 12308 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2021-09-09 14:52:19.185  INFO 12308 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
09-Sep-2021 14:52:19.254 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc Web应用程序 [nacos] 注册了JDBC驱动程序 [dm.jdbc.driver.DmDriver]，但在Web应用程序停止时无法注销它。 为防止内存泄漏，JDBC驱动程序已被强制取消注册。
09-Sep-2021 14:52:19.255 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-3]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.256 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-4]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.256 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-5]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.257 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-6]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.257 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-7]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.258 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-8]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.258 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-9]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.259 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-10]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.259 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[JRaft-Closure-Executor-11]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
 java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.259 警告 [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads Web应用程序[nacos]似乎启动了一个名为[grpc-shared-destroyer-0]的线程，但未能停止它。这很可能会造成内存泄漏。线程的堆栈跟踪：[
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)]
09-Sep-2021 14:52:19.261 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@341814d3），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.261 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@4397ad89），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.261 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@59cba5a），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@1bd39d3c），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@6f19ac19），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@119cbf96），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@71329995），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@768fc0f2），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@5454d35e），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@20c0a64d），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.262 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@455b6df1），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.263 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@4ddbbdf8），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.263 严重 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks web应用程序[nacos]创建了一个ThreadLocal，其键类型为[java.lang.ThreadLocal]（值为[java.lang.ThreadLocal@3d246ea3]），值类型为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap]（值为[io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@3f67593e），但在停止web应用程序时未能将其删除。线程将随着时间的推移而更新，以尝试避免可能的内存泄漏
09-Sep-2021 14:52:19.279 信息 [main] org.apache.coyote.AbstractProtocol.stop 正在停止ProtocolHandler ["http-nio-8848"]
09-Sep-2021 14:52:19.335 信息 [main] org.apache.coyote.AbstractProtocol.destroy 正在摧毁协议处理器 ["http-nio-8848"]
Disconnected from server`

**Comment by realJackSun** [comment]
Please use 
> bash shutdown.sh 

to shutdown nacos.

**Comment by KomachiSion** [comment]
nacos add the RuntimeHook to stop threadPool, if tomcat war stop with out signal, nacos will not stop the threadpool.

Community is not support and recommend use tomcat war to deploy nacos. If you need use this way to deploy, may be you need do some enhance to shutdown nacos.
