### ISSUE TITLE
只能注册一个服务，而且没多久就会自动下线，日志抛出错误ERROR clearConfigHistory error

### ISSUE THREAD

**Issue by qb0221** [alibaba/nacos#6844]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by qb0221** [comment]
ERROR clearConfigHistory error

**Comment by brotherlu-xcq** [comment]
这个是配置中心清除历史配置的异常信息，应该和你的服务被下线没有关系。检查一下naming_push.log里面有没有推送信息。

**Comment by qb0221** [comment]
> 这是配置中心清除历史配置的异常信息，应该和你的服务被下线没有关系。检查一下naming_push.log里面有没有信息。

2021-09-09 15:51:53,240 ERROR [NACOS-PUSH] error while receiving ack data

java.lang.IllegalStateException: unable to find ackEntry for key: 127.0.0.1,38219,11400022155207216, ack json: {"type": "push-ack", "lastRefTime":"11400022155207216", "data":""}
	at com.alibaba.nacos.naming.push.PushService$Receiver.run(PushService.java:642)
	at java.lang.Thread.run(Thread.java:745)
大佬 naming_push.log 报这个错误怎么解决

**Comment by KomachiSion** [comment]
This issue is an old issue, can you use new version to retry? If issue still happen, please submit new issue with more detail informations.
