### ISSUE TITLE
控制台/OPEN-API部分操作会将注册的永久实例变为临时实例

### ISSUE THREAD

**Issue by joyeekk** [alibaba/nacos#6846]
**Describe the bug**
1. 在一个服务下注册**永久实例**，如图：
![image](https://user-images.githubusercontent.com/28078593/132677155-0ecbdd2e-0ece-4941-a0e4-ec0f51485e1a.png)

2. 然后再修改实例的属性(如将127.0.0.1:8081这个实例的权重修改为10)，这个时候再通过控制台/接口查询，所有的实例都变成了**临时实例**
![image](https://user-images.githubusercontent.com/28078593/132677461-fd1bf22d-b0eb-4b51-9ae7-035de055e45b.png)

3. 如果这时候再注册注册一个永久实例(如127.0.0.1:8082)，再通过控制台/接口查询，所有的实例又变成了**永久实例**。
![image](https://user-images.githubusercontent.com/28078593/132677774-69919855-0e81-477e-8f32-b93a67045ac3.png)

**Expected behavior**
服务实例是否为临时实例这个属性，在上述情况下应该不会变化；

**Acutally behavior**
服务实例是否为临时实例这个属性，在上述情况下发生了变化；

**How to Reproduce**
见问题描述

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version nacos-server 2.0.3
 - Module  naming
 - SDK original

**其他**
我们的场景需要通过nacos-sync来做服务的同步，如果临时/永久实例这个属性会经常变化的话，对我们的影响非常大。

**Comment by wangdongyun** [comment]
nacos 关于临时、持久实例这块 感觉到处诡异

**Comment by zz630** [comment]
我们也是用nacosSync同步实例。当同步的量大时，如果注册临时实例，nacosSync无论用nacos client1.x维持心跳，还是2.x多个NamingService维持grpc连接，单台nacosSync能维持的量是有限的，必须分片。而且nacosSync挂了还会被摘除服务，还得冗余。如果用持久化实例就不会有这样的问题。
同一个service/group，应用分区域部署，在当前nacos集群a注册当前cluster a的临时实例，在其他区域注册到其他nacos集群，再用nacosSync同步过来到nacos集群a，cluster为b/c/d等，注册为持久化实例。这样https://github.com/alibaba/nacos/pull/7239就不适用了
