### ISSUE TITLE
Dubbo以Nacos为注册中心，不提供version和group，无法调用

### ISSUE THREAD

**Issue by LeagueZhou** [alibaba/nacos#6850]
![image](https://user-images.githubusercontent.com/45708740/132716153-0ab60dea-f23d-4260-88d4-b24a3044fdd6.png)
  启动的服务没有带版本号和分组信息，可以正常注册，
但是消费的时候就无法远程调用。会抛出异常
![image](https://user-images.githubusercontent.com/45708740/132716460-4b0fa005-82be-44ff-b62d-074f4c206cbe.png)

provider会多出来两个::，是version和group没有配置，以前使用Dubbo+zk也没有使用version和group也可以正常访问。
当我给他们注册上version和group后又可以正常调用。请问这是什么原因呢？

**Comment by ingle-j** [comment]
这个是bug，正常情况下不指定版本和分组注册上去的消费服务后面应该会跟两个冒号::，dubbo订阅服务的时候从注解里拿到的version和group为空时其实也该把服务名后面默认加上两个::然后再请求nacos拉取服务信息，
但你这个很明显是bug，具体可以去看看org.apache.dubbo.registry.nacos.NacosRegistry；也可以将dubbo更新到2.7.8试试，目前我用这版没问题，他解决上面这个问题就是在拉取服务之前解析了两个服务名，一个带::，一个不带，分别去请求nacos获取服务信息，最终放到一起。这样的话相当于一个服务不同时指定版本和分组每次都得请求两次nacos。。。
