### ISSUE TITLE
升级后的nacos连接老nacos数据库

### ISSUE THREAD

**Issue by ruirui9** [alibaba/nacos#6856]
![lALPDhmOw2OK4HxZzQeA_1920_89](https://user-images.githubusercontent.com/60023402/132813426-704b6df2-530d-40b2-b958-eaaa264afef8.png)

用的是阿里云的rds做的持久化存储

**Comment by ruirui9** [comment]
我在数据库增加了这个表  这个表的字段都该写些什么
![image](https://user-images.githubusercontent.com/60023402/132814917-207430f5-9eaa-4616-9028-494f2cd918f7.png)
我只写了varchart类型的username

**Comment by brotherlu-xcq** [comment]
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html参考这里，这些表是有sql语句的，不需要你自己一个一个的去写。

**Comment by ruirui9** [comment]
> https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html 参考这里，这些表是有sql语句的，不需要你自己一个一个的去写。

![image](https://user-images.githubusercontent.com/60023402/132817319-559c1001-1e84-4201-af7b-24c927b16b1a.png)
为什么少个角色管理 好奇怪

**Comment by brotherlu-xcq** [comment]
主账号才会有角色管理
