### ISSUE TITLE
修改nacos配置发布后，通过postman查询配置不更新

### ISSUE THREAD

**Issue by westcows00481** [alibaba/nacos#6857]
修改nacos配置发布后，通过postman查询配置不更新

**Comment by westcows00481** [comment]
1.4.2版本

**Comment by li-xiao-shuang** [comment]
通过控制台修改的嘛？

**Comment by westcows00481** [comment]
不是，naocs界面

**Comment by westcows00481** [comment]
我怎么控制查询配置服务直接取数据库，临时先规避下

**Comment by li-xiao-shuang** [comment]
你是什么接入方式？springboot  还是 springcloud

**Comment by westcows00481** [comment]
springboot, https有bug， 开启后每次修改都要重启nacos。 怎么规避

**Comment by westcows00481** [comment]
nacos.cmdb.loadDataAtStart这个配资是做什么的？

**Comment by li-xiao-shuang** [comment]
> nacos.cmdb.loadDataAtStart这个配资是做什么的？



是否打开CMDB,具体的系统参数可以查看https://nacos.io/zh-cn/docs/system-configurations.html

**Comment by westcows00481** [comment]
CMDB模块具体干啥的，这个说明根本看不懂啊

**Comment by westcows00481** [comment]
有什么方式读取配置每次从数据库读取

**Comment by westcows00481** [comment]
大量内部请求用的rest， 写死的http

**Comment by li-xiao-shuang** [comment]
> CMDB模块具体干啥的，这个说明根本看不懂啊

存储Nacos元数据

**Comment by li-xiao-shuang** [comment]
> 修改nacos配置发布后，通过postman查询配置不更新

描述问题还是要清楚一点  要不没有办法解答，最好是能有复现的步骤。你可以看看和这个问题是否类似https://github.com/alibaba/nacos/issues/6853

**Comment by westcows00481** [comment]
开启https后， 管理面修改配置发布。 数据库更新了， 但是通过获取配置API不刷新， 缓存服务器的配置文件也是旧的

**Comment by westcows00481** [comment]
还没谈到客户端，仅仅说的服务端的问题

**Comment by li-xiao-shuang** [comment]
> 开启https后， 管理面修改配置发布。 数据库更新了， 但是通过获取配置API不刷新， 缓存服务器的配置文件也是旧的

通过Nacos管理界面发布配置，然后通过api获取没有更新？   通过管理界面查看详情有修改成功嘛？
