### ISSUE TITLE
1.2.1版本3节点集群模式出现数据不一致

### ISSUE THREAD

**Issue by tangshifeng** [alibaba/nacos#6862]
1.2.1版本3节点集群模式，通过nacos/v1/ns/instance/list获取可用服务列表的时候哦，其中一个节点获取可用服务列表的时候返回空，另外两个节点可以正常返回服务列表，出现部分请求no instance in service ，未找到原因，其中其它服务的3个节点都可以正常返回。

**Comment by realJackSun** [comment]
日志提供一下
nacos-cluster.log
protocol-raft.log
nacos.log
naming-server.log

**Comment by tangshifeng** [comment]
同事忘记保存当时的日志了，尴尬。。。现在只有重启最后的日志了，是不是有可能naocs服务端内存给的不够的原因？我们是服务大概30个吧，然后在线人数6，QPS每秒差不多6K。

**Comment by tangshifeng** [comment]
> 日志提供一下
> nacos-cluster.log
> protocol-raft.log
> nacos.log
> naming-server.log

同事忘记保存当时的日志了，尴尬。。。现在只有重启最后的日志了，是不是有可能naocs服务端内存给的不够的原因？我们是服务大概30个吧，然后在线人数6，QPS每秒差不多6K。

**Comment by ingle-j** [comment]
去控制台的集群管理里看看3个节点的信息是否正常，主要看leader节点是否一致，节点状态是否都是up，term是否都一致

**Comment by tangshifeng** [comment]
> 去控制台的集群管理里看看3个节点的信息是否正常，主要看leader节点是否一致，节点状态是否都是up，term是否都一致

3个节点看集群任期不一致，其中两台和另外一台不一致，分别在3台上执行curl '127.0.0.1:8848/nacos/v1/ns/raft/state' 在每一台上返回的都是一样的数据
