### ISSUE TITLE
Nacos1.4+版本服务监听异常

### ISSUE THREAD

**Issue by HTFX-Cloud** [alibaba/nacos#6864]
本地使用nacos1.3.2与nacos1.4.2客户端分别对nacos已存在注册的服务进行监听。
服务端代码截图：
分别在不同命名空间下注册不同端口的web应用
![image](https://user-images.githubusercontent.com/89976406/133015220-707c00f4-507a-4e42-8666-b5ab8ba74ace.png)

客户端截图：
1.本地尝试进行nacos1.4.2客户端模拟，如图所示。服务的event与namingservice不能一一对应
![image](https://user-images.githubusercontent.com/89976406/133011908-457b4430-a271-4c38-9e22-f9fb58eecd85.png)
2.本地使用同样测试代码，nacos1.3.2客户端模拟，如图所示。可以保证服务的event与namingservice可以一一对应
![image](https://user-images.githubusercontent.com/89976406/133011984-4294a35f-5124-4c93-8215-8fba1e59600f.png)

目前不清楚，nacos1.4.2+（本地使用nacos 2.0+也存在该问题）这个客户端呈现的效果【namingevent给所有的Subscriber都发送通知】，是bug还是设计。要是设计，那我们需要对客户端的使用进行改造。

望尽快答复。谢谢

**Comment by realJackSun** [comment]
> 目前不清楚，nacos1.4.2+（本地使用nacos 2.0+也存在该问题）这个客户端呈现的效果【namingevent给所有的Subscriber都发送通知】，是bug还是设计。

从你的描述看，nacos1.4.2似乎出现了和你预期不一致的现象？你预期看到的是什么现象可以描述清楚么？

**Comment by HTFX-Cloud** [comment]
我贴了图片，不知道能不能看见。如同上面的图片二所示。

【简单描述】
nacos客户端对【不同命名空间】下的【同名服务】进行监听（本地测试使用了两个namingservice）。在nacos控制台上任选其中【一个命名空间的服务】进行上下线，会接受到【两个服务通知】。
同样的测试代码在nacos1.3.2上测试，【能保证namingservice与namingevent一一对应】。

【源码跟踪】
跟踪nacos1.3.2的源码发现，事件通知堆栈信息如下
Daemon Thread [com.alibaba.nacos.naming.client.listener] (Suspended (breakpoint at line 499 in NacosRegistry))
NacosRegistry.lambda$subscribeEventListener$10(URL, String, NotifyListener, Event) line: 499
535910992.onEvent(Event) line: not available
EventDispatcher$Notifier.run() line: 177
ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) line: 1149
ThreadPoolExecutor$Worker.run() line: 624
Thread.run() line: 748
跟踪nacos1.4.2的源码发现，事件通知堆栈信息如下
Daemon Thread [nacos.publisher-com.alibaba.nacos.client.naming.event.InstancesChangeEvent] (Suspended)
NacosRegistry(AbstractRegistry).notify(URL, NotifyListener, List) line: 409
NacosRegistry(FailbackRegistry).doNotify(URL, NotifyListener, List) line: 372
NacosRegistry(FailbackRegistry).notify(URL, NotifyListener, List) line: 364
NacosRegistry.notifySubscriber(URL, NotifyListener, Collection) line: 534
NacosRegistry.lambda$subscribeEventListener$10(URL, String, NotifyListener, Event) line: 512
1678856266.onEvent(Event) line: not available
InstancesChangeNotifier.onEvent(InstancesChangeEvent) line: 125
InstancesChangeNotifier.onEvent(Event) line: 39
DefaultPublisher$1.run() line: 198
DefaultPublisher.notifySubscriber(Subscriber, Event) line: 208
DefaultPublisher.receiveEvent(Event) line: 186
DefaultPublisher.openEventHandler() line: 117
DefaultPublisher.run() line: 94

**Comment by HTFX-Cloud** [comment]
> > 目前不清楚，nacos1.4.2+（本地使用nacos 2.0+也存在该问题）这个客户端呈现的效果【namingevent给所有的Subscriber都发送通知】，是bug还是设计。
> 
> 从你的描述看，nacos1.4.2似乎出现了和你预期不一致的现象？你预期看到的是什么现象可以描述清楚么？

能看见最上面issue中的图片二么

**Comment by HTFX-Cloud** [comment]
> > 目前不清楚，nacos1.4.2+（本地使用nacos 2.0+也存在该问题）这个客户端呈现的效果【namingevent给所有的Subscriber都发送通知】，是bug还是设计。
> 
> 从你的描述看，nacos1.4.2似乎出现了和你预期不一致的现象？你预期看到的是什么现象可以描述清楚么？

【1.4+现状描述】
nacos客户端对【不同命名空间】下的【同名服务】进行监听（本地测试使用了两个namingservice）。在nacos控制台上任选其中【一个命名空间的服务】进行上下线，会接受到【两个服务通知】。

【期待效果】
希望同样的测试代码在nacos1.3.2上测试结果一致，【保证namingservice与namingevent一一对应】。即nacos控制台上任选其中【一个命名空间的服务】进行上下线，只接受到【所属namingservice】的【一个服务通知】。

**Comment by HTFX-Cloud** [comment]
@realJackSun

**Comment by lpaz010** [comment]
@realJackSun @HTFX-Cloud 两位看这样理解是否合理哈：
同一个jvm虚拟机实例里面NotifyCenter是单例，所以用不同的NamingService实例注册监听器都在在一个单例里面，对Naming事件触发都会通知到各自监听器里面。

结论：一个应用实例(jvm实例)一个namespace才是本来设计。

**Comment by JasonMing** [comment]
> @realJackSun @HTFX-Cloud 两位看这样理解是否合理哈： 同一个jvm虚拟机实例里面NotifyCenter是单例，所以用不同的NamingService实例注册监听器都在一个单例里面，对一个Naming事件触发都会通知到各自监听器里面，所谓的跨namespace了。
> 
> 结论：一个应用实例(jvm实例)一个namespace才是本来设计。

这个解释站不住脚。。。
比如我有多个区域的，互相隔离的，优先使用本地区域，出问题使用非本地区域。。。

这种多naming service的场景比比皆是，设计上`NamingService`之间本来就应该是完整隔离的，一个NotifyCenter把东西都乱窜了。。。
我是不知道是基于什么样的目的搞得static满天飞，nacos是这样，sentinel是这样，fastjson/dubbo也喜欢这样。。。
搞到现在我对阿里系的框架都没信心了。。。

**Comment by JasonMing** [comment]
@horizonzy 请关注下这个问题

2020 年这个 PR [#4137](https://github.com/alibaba/nacos/pull/4137/files#diff-c3ff23129fe592fdfcecd762f683c6d9e399beff620dd6b78ef70fcad57eaaf5R116-R117) 中，把专用的 `eventDispatcher` 改为全局共享的 `NotifyCenter`。
这个改动导致了nacos 1.4.1以后的所有版本在订阅多个注册中心时，任何一个注册中心触发变更都会广播到所有 `NamingService` 中。

想问问当时出于什么目的改为这种全局共享的通知？现在可以提供一个PR修复吗？

**Comment by horizonzy** [comment]
当时这个 pr 是重构，统一事件的通知。看起来确实是有问题

**Comment by liqipeng** [comment]
应该与我前面提的 #8428 是一个问题，修复思路见 https://github.com/alibaba/nacos/pull/8433#issuecomment-1134185923

**Comment by horizonzy** [comment]
> 应该与我前面提的 #8428 是一个问题，修复思路见 [#8433 (comment)](https://github.com/alibaba/nacos/pull/8433#issuecomment-1134185923)

👌

**Comment by horizonzy** [comment]
@JasonMing @HTFX-Cloud 请测试下新版本，看起来已经修复了。

**Comment by elvislou** [comment]
@horizonzy 哪个版本修复了？

**Comment by liqipeng** [comment]
@elvislou 目前还只是在开发分支上，可能会在1.4.4或2.1.1
