### ISSUE TITLE
Can I customize what the console displays?

### ISSUE THREAD

**Issue by zhupengfeivip** [alibaba/nacos#6865]
Can I customize the console title and display content, content on the above pages, etc.

Source of demand:
The production environment and the test environment are deployed separately. The two systems are currently indistinguishable and can easily be confused.

我是否可以定制控制台的标题和显示内容，以上网页上的内容等等。
![image](https://user-images.githubusercontent.com/30720809/133020483-46f77726-5f7b-41aa-8f7e-bf86939717a9.png)
如图上三个部分。

需求来源：
生产环境和测试环境分开部署，两个系统目前没有区分，很容易混淆。

**Comment by li-xiao-shuang** [comment]
可能需要修改console-ui中的源代码

**Comment by zhupengfeivip** [comment]
嗯，修改完如何替换呢，我是docker安装的。

**Comment by li-xiao-shuang** [comment]
> 嗯，修改完如何替换呢，我是docker安装的。

如果你们想基于naocs做一些自定义，就得拉下来nacos源码，修改完以后从新创建镜像 再部署。

**Comment by zhupengfeivip** [comment]
目前我已经研究出配置UI的方法。

找到target目录下，nacos-server.jar，修改里面的文件即可修改UI。
这个文件是一个jar的压缩包。


但我现在还没有研究出来，怎么生成这个jar包，重新编译了consoleUI后，生成的jar包，替换后启动不起来。

我的生成命令是
jar -cvf nacos-server.jar BOOT-INF/ META-INF/ org/
是不是有错误啊？

请各位指正一下。谢谢。

@li-xiao-shuang @realJackSun

**Comment by li-xiao-shuang** [comment]
可以拉nacos的源码修改，不要直接修改jar，jar包生成是通过maven打包的。你修改完源码之后可以执行mvn clean package -U -Dmaven.test.skip=true命令，就会在targer目录下生成新的jar包，前提是安装了maven。

**Comment by zhupengfeivip** [comment]
这个稍有点难了，我这边不是JAVA开发，还需要安装JAVA开发环境？

后续是否有计划开发一个可配置的管理后台，或者支持用户修改JS或者页面的。

比如列中的示例代码在实际使用中应该用不到

**Comment by zhupengfeivip** [comment]
consoleUI编译已经OK，是否有其他方式可以生成nacos-server.jar？不用maven呢

@li-xiao-shuang 谢谢

**Comment by li-xiao-shuang** [comment]
> 这个稍有点难了，我这边不是JAVA开发，还需要安装JAVA开发环境？
> 
> 后续是否有计划开发一个可配置的管理后台，或者支持用户修改JS或者页面的。
> 
> 比如列中的示例代码在实际使用中应该用不到

嗯 如果想要定制化或者二次开发是需要涉及到源码的修改，相应的环境肯定也是需要的。如果不熟悉的话，还是建议使用现成的。
不过你可以尝试单独部署console-ui。服务端就使用现在。应该是可以前后端分离部署的。

**Comment by zhupengfeivip** [comment]
谢谢，我试试单独部署控制台。这个应该能解决我的问题。
