### ISSUE TITLE
How to get the client ip by watching any Event?

### ISSUE THREAD

**Issue by sucaiji** [alibaba/nacos#6866]
When the client is disconnected, I want to get the ip;
I try to subscribe ClientDisconnectEvent, like this.
```
Client client = disconnectEvent.getClient();
Collection<Service> services = client.getAllPublishedService();

if (services != null || services.isEmpty()) {
    return;
}
for (Service service: services) {
    InstancePublishInfo instanceInfo = client.getInstancePublishInfo(service);
    String ip = instanceInfo.getIp();
}
```
But when the client is disconnected, first execute ```client.release()```, clean all published service.
then ```NotifyCenter.publishEvent(new ClientEvent.ClientDisconnectEvent(client));```
So I can't get ip by subscribe ClientDisconnectEvent. How could I do?

**Comment by KomachiSion** [comment]
ClientDisconnectEvent.getClient().getAllPublishedService()

client.release() will not delete the instance info in this client.
