### ISSUE TITLE
Will nacos provide the native image compiled by graalvm in the future?

### ISSUE THREAD

**Issue by WowYouCanReallyDance** [alibaba/nacos#6869]
The native image by GraalVM provide to executable files on multiple platform looks like a very nice trend.
That will help the containerization applications to small, dynamic and starting up faster ones. No more fat images with JRE, No more slowly built time. 
Will you consider to that?

**Comment by complone** [comment]
@realJackSun I want to try to solve this issue

**Comment by Leowuqunqun** [comment]
@i will solve it@

**Comment by superstarchenxin** [comment]
is the issue sovled? How can I use it?

**Comment by KomachiSion** [comment]
should has been supported after 2.2.1-RC
