### ISSUE TITLE
请问如何使Nacos支持SSL，或者说可以使用https访问，并可以在客户端注册到https的Nacos上？

### ISSUE THREAD

**Issue by hjon001** [alibaba/nacos#6870]
Please tell me how to make Nacos support SSL, that is, you want to use HTTPS: / / on the browser to access the registry.

In addition, if yes, how to register with Nacos that supports HTTPS on the client.

请问如何使Nacos支持SSL，也就是希望能在浏览器上使用https://能访问到注册中心。
另外，如果支持，如何在客户端注册到支持https的Nacos中。

**Comment by ingle-j** [comment]
直接搞nginx代理了，nacos只需在内网中访问，如果要走公网或者提供域名，都走nginx。这样做还可以减少nacos-client的长连接数量，可以减少nacos节点数量n 的  n-1/n 的长连接

**Comment by KomachiSion** [comment]
Not support for now, nobody contribute this feature for a long time. Most of users use nginx or vip as a frontend which to support https protocol.
