### ISSUE TITLE
nacos控制台 服务管理/订阅者列表 应用名无法显示

### ISSUE THREAD

**Issue by wzhj2326** [alibaba/nacos#6872]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.03, nacos-client 2.0.3]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos]

**Additional context**
![20210914104939](https://user-images.githubusercontent.com/15643447/133186916-96d0adc9-053e-4792-b657-465179508e96.jpg)

spring boot 应用 应用名显示为unknown，可否显示为 调用者的注册的服务名？

**Comment by li-xiao-shuang** [comment]
尝试配置 spring.application.name

**Comment by wzhj2326** [comment]
> 尝试配置 spring.application.name

配置了的，没有效果

**Comment by lpaz010** [comment]
应用名在Nacos2.0.X目前不支持了。
分析：因为订阅请求header没有放入app的值，服务端是这么获取的`String app = request.getHeader("app", "unknown");`

**Comment by brotherlu-xcq** [comment]
GRPC和HTTP的取app的放入header的逻辑都是一样的从代码上来看。

https://github.com/alibaba/nacos/blob/bfa94e318d998c7c2f2e21a14877fbc47df6f5c9/client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc/NamingGrpcClientProxy.java#L262-L281

https://github.com/alibaba/nacos/blob/bfa94e318d998c7c2f2e21a14877fbc47df6f5c9/client/src/main/java/com/alibaba/nacos/client/naming/remote/AbstractNamingClientProxy.java#L82-L99

**Comment by wzhj2326** [comment]
对spingboot应用 nacos client 获取app name 为空

https://github.com/alibaba/nacos/blob/bfa94e318d998c7c2f2e21a14877fbc47df6f5c9/client/src/main/java/com/alibaba/nacos/client/utils/AppNameUtils.java#L50-L84

**Comment by lpaz010** [comment]
@wzhj2326 解决了吗？通过源码看，jar包启动可以配置`-Dproject.name=xxxApp `，  war包启动应该可以自动识别。
