### ISSUE TITLE
scheduleWithFixedDelay每10ms轮询一次cacheMap是为啥

### ISSUE THREAD

**Issue by neilxxx** [alibaba/nacos#6874]
cacheMap会在addListener时增加元素

但是在什么情况下在项目启动后还会执行addListener方法？目前只看到在onApplicationEvent事件中会去执行，没有发现在程序启动完毕后还会调用addListener的情况，所以程序启动完毕后cacheMap 的size应该不会变吧？还需要每10ms去执行么

如果程序启动后还可以往cacheMap内置入元素，可以举个简单例子么

**Comment by realJackSun** [comment]
你说的是ClientWorker中的cacheMap吗？它缓存的应该是被监听的配置.

>如果程序启动后还可以往cacheMap内置入元素，可以举个简单例子么

当监听一个配置的时候，就会放入元素
然后定期刷新，查看该配置是否有变更

**Comment by MajorHe1** [comment]
> 当监听一个配置的时候，就会放入元素
> 然后定期刷新，查看该配置是否有变更
所以我理解配置推送的本质还是轮询对不对？轮询的周期是10ms？

**Comment by neilxxx** [comment]
> 你说的是ClientWorker中的cacheMap吗？它缓存的应该是被监听的配置。
> 
> > 如果程序启动后启动缓存Map建入元素，可以举个简单的例子么
> 
> 实时监听一个动态，
> 然后定时刷新，查看该配置是否有变化

**Comment by neilxxx** [comment]
> 你说的是ClientWorker中的cacheMap吗？它缓存的应该是被监听的配置。
> 
> > 如果程序启动后启动地图建入元素，可以举个简单的例子么
> 
> 实时监听一个动态，
> 然后定时刷新，查看配置是否有变化

cacheMap里存的是被监听的配置
目前只看到onApplicationEvent事件中会往cacheMap里增加监听配置，在服务启动完成后cacheMap的size应该不会变了 为什么还需要每隔10ms去轮询它的size?  如果有其他操作能触发往cacheMap里增加监听，能举个例子么？
