### ISSUE TITLE
Nacos 2.0.3 ERROR_TYPE_STATE_MACHINE 

### ISSUE THREAD

**Issue by warmonipa** [alibaba/nacos#6877]
**Describe the bug**
Nacos 2.0.3 Cluster based k8s encounter an unrecoverable error, error log :
```
"naming_persistent_service": {
    "errMsg": "Error [type=ERROR_TYPE_STATE_MACHINE, status=Status[ESTATEMACHINE<10002>: StateMachine meet critical error when applying one or more tasks since index=1365161, 
    Status[ESTATEMACHINE<10002>: StateMachine meet critical error: java.lang.IllegalArgumentException: No enum constant com.alibaba.nacos.naming.consistency.persistent.impl.
    BasePersistentServiceProcessor.Op.\n\tat java.lang.Enum.valueOf(Enum.java:238)\n\tat com.alibaba.nacos.naming.consistency.persistent.impl.BasePersistentServiceProcessor$Op
    .valueOf(BasePersistentServiceProcessor.java:63)\n\tat com.alibaba.nacos.naming.consistency.persistent.impl.BasePersistentServiceProcessor.onApply(BasePersistentServiceProcessor.java:170)
    \n\tat com.alibaba.nacos.core.distributed.raft.NacosStateMachine.onApply(NacosStateMachine.java:115)\n\tat com.alipay.sofa.jraft.core.FSMCallerImpl.doApplyTasks(FSMCallerImpl.java:539)
    \n\tat com.alipay.sofa.jraft.core.FSMCallerImpl.doCommitted(FSMCallerImpl.java:508)\n\tat com.alipay.sofa.jraft.core.FSMCallerImpl.runApplyTask(FSMCallerImpl.java:440)
    \n\tat com.alipay.sofa.jraft.core.FSMCallerImpl.access$100(FSMCallerImpl.java:73)\n\tat com.alipay.sofa.jraft.core.FSMCallerImpl$ApplyTaskHandler.onEvent(FSMCallerImpl.java:148)
    \n\tat com.alipay.sofa.jraft.core.FSMCallerImpl$ApplyTaskHandler.onEvent(FSMCallerImpl.java:142)\n\tat com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:137)
    \n\tat java.lang.Thread.run(Thread.java:748)\n.]]]",
    "leader": "nacos-0.nacos-headless.nacos.svc.cluster.local:7848",
```
**Expected behavior**
No error.

**Acutally behavior**
jRaft state machine encountered unrecoverable error.

**Desktop (please complete the following information):**
 - OS: [K8S 1.19.6]
 - Version: nacos-server 2.0.3

**Comment by realJackSun** [comment]
删除~/nacos/data/protocol，然后再重启一次

**Comment by wangdongyun** [comment]
> 删除~/nacos/data/protocol，然后再重启一次

现在状态机 某条log 执行出现报错 就会导致整个nacos raft 不可用？

**Comment by wangdongyun** [comment]
> 现在状态机 某条log 执行出现报错 就会导致整个nacos raft 不可用？

如果有3节点的nacos，有两个节点 状态机 处理报错，就会整个集群GG，而且找不到恢复的手段！

**Comment by wangzhenxyz1** [comment]
> 删除~/nacos/data/protocol，然后再重启一次
> 

昨天nfs重建了，今天又挂了，已经降级1.4.2

**Comment by wangzhenxyz1** [comment]
别沉了，bump

**Comment by horizonzy** [comment]
我看一下这个问题。

**Comment by suanyi001** [comment]
有更新吗 我们也遇到了同样的问题.

**Comment by horizonzy** [comment]
> 有更新吗 我们也遇到了同样的问题.

能够稳定复现吗？

**Comment by suanyi001** [comment]
> > 有更新吗 我们也遇到了同样的问题.
> 
> 能够稳定复现吗？

我们已经遇到了几次，我把详细的过程整理到[这个issue上](https://github.com/alibaba/nacos/issues/6877 )，麻烦大佬帮忙看看！

**Comment by bizhenchao1201** [comment]
> > 删除~/nacos/data/protocol，然后再重启一次
> 
> 昨天nfs重建了，今天又挂了，错误是一致的，已经降级1.4.2，但142还有stop的bug，希望大佬尽快发布143，待203修复上面的问题再升级

存储在nfs，是否会因为网络抖动导致存储失败？对于nacos集群一致性的数据是不是应该存在本地磁盘上？

**Comment by zrlw** [comment]
> stop的bug
```142还有stop的bug```指的是什么？有相关的issue链接么？

**Comment by wangzhenxyz1** [comment]
> > stop的bug
> 
> `142还有stop的bug`指的是什么？有相关的issue链接么？ 如果指的是I/O reactor status: STOPPED，我们采用的方法是把2.0分支的 #6441 补丁搞到1.4.2分支上，这个补丁不仅捕获了IOException（ConnectionClosedException 属于IOException ），而且捕获了全部RuntimeException，可能比#7299 讲的升级httpcore版本的方法更稳妥一些。

对的，就是I/O reactor status: STOPPED的问题

**Comment by zrlw** [comment]
更新一下，心跳数量超大情况下，版本1也会出现同样的问题，只有Ieader的控制台页面显示有注册的服务实例（且数量不稳定），其他节点都是ERROR_TYPE_STATE_MACHINE状态，控制台页面显示没有一个服务注册实例。

**Comment by zrlw** [comment]
这个问题我们通过修改代码增加异常捕获解决了。https://github.com/alibaba/nacos/issues/7757
