### ISSUE TITLE
Import configuration format problem

### ISSUE THREAD

**Issue by 602297770** [alibaba/nacos#6889]
The exported configuration is formatted.but reimport these configurations. The format is not displayed by default when editing the configuration.

**Comment by realJackSun** [comment]
> the format is not displayed by default when editing the configuration.

You mean you edit the exported data? and then reimport them ?

**Comment by 602297770** [comment]
The following scenario：Export configuration first，Then delete all configurations，Finally, import the configuration exported at the beginning，Editing the imported configuration does not display the format at this time.
