### ISSUE TITLE
nacos config 日志在不断的加载配置

### ISSUE THREAD

**Issue by zhangle910522** [alibaba/nacos#6891]
我使用了 spring-cloud-gateway 并通过nacos config 作为路由的配置中心，使用 com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2.2.6.RELEASE 版本 发现日志不断的在刷新配置  一秒钟都有好几次，请问这个刷新频率是根据什么来的，配置文件只配置了nacos地址

[] 10:29:39 INFO  com.alibaba.nacos.client.config.impl.ClientWorker [430] - [fixed-192.168.65.50_8848-public] [polling-resp] config changed. dataId=whxh-gateway.service.yml, group=DEFAULT_GROUP, tenant=public
[] 10:29:39 INFO  com.alibaba.nacos.client.config.impl.ClientWorker [537] - get changedGroupKeys:[whxh-gateway.service.yml+DEFAULT_GROUP+public]
[] 10:29:39 INFO  com.alibaba.nacos.client.config.impl.ClientWorker [556] - [fixed-192.168.65.50_8848-public] [data-received] dataId=whxh-gateway.service.yml, group=DEFAULT_GROUP, tenant=public, md5=ff76e770864ca26282460beeb20d0996, content=spring:
  cloud:
    gateway:

**Comment by Trigger-cd** [comment]
我也出现这个问题,改了group和tenant就好了

**Comment by KomachiSion** [comment]
tenant=public, please set tenant as `""`
