### ISSUE TITLE
springboot 同时使用Nacos config和Apollo 的问题

### ISSUE THREAD

**Issue by zhangle910522** [alibaba/nacos#6892]
因项目历史原因，基础配置使用的apollo进行加载，然后路由信息我想使用 nacos config 进行配置，于是项目中使用了com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config，请问这样会不会存在问题？ nacos config 会跟apollo 有冲突吗
目前集成后的结果 数据都能够读取正常，但是控制台 Nacos config会不断的打印日志 读取 路由的配置，也没有报错（频率很高，一分钟有几次）

**Comment by ingle-j** [comment]
没啥问题，但是就目前来说，作为配置中心还是apollo更好，nacos的刷新机制也太粗暴。
