### ISSUE TITLE
k8s 启动Nacos开启NACOS_AUTH_ENABLE=true后无法使用帐号密码登录web页面

### ISSUE THREAD

**Issue by Hello-Linux** [alibaba/nacos#6893]
k8s部署的nacos开启了鉴权之后，我的web使用帐号密码登录不上了，提示帐号密码错误，关闭NACOS_AUTH_ENABLE=false之后使用帐号密码就可以正常登录了，这是为啥呢?

**Comment by lucifer0x1** [comment]
发一下你用那个版本的nacos， 好像之前是因为spring cloud 对nacos 不适配造成的 #2442

**Comment by KomachiSion** [comment]
可能是账号密码前面输入错误的问题，
控制台有个登录那里有个问题， 如果输入密码时使用了中文输入法， 可以切换成英文输入法再试一下。

**Comment by lucifer0x1** [comment]
> 可能是账号密码前面输入错误的问题，
> 控制台有个登录那里有个问题， 如果输入密码时使用了中文输入法， 可以切换成英文输入法再试一下。

关闭鉴权了， 原来的账号密码就可以登录，貌似不太可能是输入错误吧，还是说， 关闭鉴权，无论账号密码对与否都能登录？

**Comment by Hello-Linux** [comment]
@lucifer0x1 重新部署了一下可以登陆了，还有一个问题就是nacos 的nodejs sdk客户端怎么使用帐号密码登陆本地nacos服务器呢？

**Comment by Hello-Linux** [comment]
@lucifer0x1  我们现在是nodejs客户端但是我看官方写的sdk不支持帐号跟密码登陆

**Comment by lucifer0x1** [comment]
> @lucifer0x1 我们现在是nodejs客户端但是我看官方写的sdk不支持帐号跟密码登陆

nodejs 我写的少， 最终也是屌用rest接口吧， 用的话，可能需要重写客户端端部分 这块我不太清楚啦   :p
