### ISSUE TITLE
绕过了鉴权，添加了新用户 (create user without authentication)

### ISSUE THREAD

**Issue by Kesling515** [alibaba/nacos#6911]
**Describe the bug**
create user success without authentication

**How to Reproduce**
1. curl XGET 'http://127.0.0.1:8848/nacos/v1/auth/users/?pageNo=1&pageSize=9'
respone：
{
    "totalCount": 1,
    "pageNumber": 1,
    "pagesAvailable": 1,
    "pageItems": [
        {
            "username": "nacos",
            "password": "$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu"
        }
    ]
}

2. curl -XPOST 'http://127.0.0.1:8848/nacos/v1/auth/users?username=test&password=test'
respone：
{
    "code":200,
    "message":"create user ok!",
    "data":null
}

3. curl XGET 'http://127.0.0.1:8848/nacos/v1/auth/users/?pageNo=1&pageSize=9'
respone：
{
    "totalCount": 2,
    "pageNumber": 1,
    "pagesAvailable": 1,
    "pageItems": [
        {
            "username": "nacos",
            "password": "$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu"
        },
        {
            "username": "test",
            "password": "$2a$10$5Z1Kbm99AbBFN7y8Dd3.V.UGmeJX8nWKG47aPXXMuupC7kLe8lKIu"
        }
    ]
}

**version**
deploy by docker 2.0.3

**Comment by brotherlu-xcq** [comment]
有添加开启认证拦截的参数吗？https://github.com/nacos-group/nacos-docker 具体的参数可以看这里。

**Comment by Kesling515** [comment]
> 有添加开启认证拦截的参数吗？https://github.com/nacos-group/nacos-docker 具体的参数可以看这里。

谢谢你的回复，我检查了下，确实是我没开启支持认证的参数。
