### ISSUE TITLE
调用python NacosClient.publish_config 时,无法将内容发布到配置列表中

### ISSUE THREAD

**Issue by vfzh** [alibaba/nacos#6912]
脚本如下所示:
import nacos

server = '192.168.78.146:8848'
name_s = 'public'
user='nacos'
passwd='tE4_hBg7Tb5sz9S3'

client = nacos.NacosClient(server,namespace=name_s,username=user,password=user)
a = client.get_config('test_0','123456')
print(a)
b = client.publish_config(data_id='test_2',group='123456', content=a,timeout=30)
print(b)

b 返回值为 true，但是在nacos web端 配置管理--配置列表 中却没有新发布的test_2.
连接账号为nacos管理员账号.

**Comment by vfzh** [comment]
Sorry.补充下，Nacos版本为 1.4.0

**Comment by AnthonyStar** [comment]
> Sorry.补充下，Nacos版本为 1.4.0
我遇到了同样的问题
请问怎么解决的呀？
