### ISSUE TITLE
nacos No DataSource set 是什么配置问题

### ISSUE THREAD

**Issue by xudan180** [alibaba/nacos#6914]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by brotherlu-xcq** [comment]
先检查一下nacos的相关表是否存在。

**Comment by juxuny** [comment]
> 先检查一下nacos的相关表是否存在。

不知道有哪些表需要创建，请相当说明在哪里？
