### ISSUE TITLE
The namespace parameter injection does not get

### ISSUE THREAD

**Issue by jxljf** [alibaba/nacos#693]
在Springframework 环境下，注入namespace无效
环境信息：
nacos  server 0.8.0
![image](https://user-images.githubusercontent.com/3088741/51594925-81ea0680-1f30-11e9-94a7-0049f2946750.png)

配置文件：
![image](https://user-images.githubusercontent.com/3088741/51595020-b1007800-1f30-11e9-9145-20ea67f7fabd.png)

nacos log文件
01 2019-01-23 16:38:31.927 INFO [RMI TCP Connection(20)-127.0.0.1:c.a.n.c.c.i.ClientWorker] [fixed-1.1.1.1:8848-${config.namespace}] [] [] [subscribe] example+DEFAULT_GROUP+${config.namespace}

**Comment by jxljf** [comment]
> > Hi @jxljf, we detect non-English characters in the issue. This comment is an auto translation from @nacos-bot to help other users to understand this issue.
> > _**We encourage you to describe your issue in English which is more friendly to other users.**_
> 
> # The namespace parameter injection does not get
> In the Springframework environment, the injected namespace is invalid.
> Environmental information:
> nacos server 0.8.0
> ![image](https://user-images.githubusercontent.com/3088741/51595210-2a986600-1f31-11e9-8e06-a29975288ffb.png)
> 
> ![image](https://user-images.githubusercontent.com/3088741/51594925-81ea0680-1f30-11e9-94a7-0049f2946750.png)
> 
> Configuration file:
> ![image](https://user-images.githubusercontent.com/3088741/51595020-b1007800-1f30-11e9-9145-20ea67f7fabd.png)
> 
> Nacos log file
> 01 2019-01-23 16:38:31.927 INFO [RMI TCP Connection(20)-127.0.0.1:c.a.n.c.c.i.ClientWorker] [fixed-1.1.1.1:8848-${config.namespace}] [] [] [subscribe] example+DEFAULT_GROUP+${config.namespace}

**Comment by nkorange** [comment]
问题是否还在？
