### ISSUE TITLE
[Bug Report] Once login to Nacos with a default account, always can open the interface even if the password has been changed.

### ISSUE THREAD

**Issue by aluneed** [alibaba/nacos#6948]
version: 2.0.1

I can still open up nacos interface since the password has been changed (If I didn't logout).
Trying to login with the same account and password in an another browser is not allowed.

**Comment by MajorHe1** [comment]
在没有logout之前，原接口依然可用， 是因为浏览器携带token来操作nacos-server，token没有过期之前都是合法的。
想要达到密码一变化，token就失效的效果，感觉不太好搞的样子，看有没有大佬能提出可行的方案。

**Comment by andotorg** [comment]
I claim it

**Comment by SteafanMrZhou** [comment]
这个问题是否和这个 issue #7096 重复，针对 issue #7096 ，我已经提交了 PR ，烦请大佬们看下，谢谢。
