### ISSUE TITLE
nacos upgrade check result false

### ISSUE THREAD

**Issue by cielswift** [alibaba/nacos#6949]
nacos version 2.0.3

![image](https://user-images.githubusercontent.com/42295829/133954425-c945a183-ad15-464b-9b68-48f61746bb24.png)
The nacos cluster has a local area network id, which was not added by me
![image](https://user-images.githubusercontent.com/42295829/133954438-131daf91-4dfa-4ed8-a5b0-bfc261b15541.png)

Cause the service upgrade to fail

**Comment by cielswift** [comment]
The others are public IP. When I change all the nodes to LAN IP, it can work normally

**Comment by cielswift** [comment]
I tried to specify the public IP to start but failed.    server.address=xxxx

**Comment by realJackSun** [comment]
Try to remove the public IP in cluster.conf?
