### ISSUE TITLE
0.8.0 version login exception

### ISSUE THREAD

**Issue by xiaoyaojc** [alibaba/nacos#695]
0.8.0版本启动后，我登录之后，然后打开服务列表中的某个服务详情。此时一切正常。
然后我给了我同事我打开的nacos地址，他打开后是直接登录的，任何页面都不需要登录。此处存疑?是否有问题。
接着，我刷新了我查看的服务详情页面，发现也是登录的，可以继续操作上下线。但是我点击左侧的菜单栏，却提示我登录？此处也存疑？应该也有问题。
问题有二：1、复制的url应该不能带登录的信息，否则他人可直接登录。
2、不知道是否支持单一登录？如果不支持，那么为啥我点击左侧菜单却提示我登录？如果支持，那为啥我在当前页面刷新也能继续操作?

**Comment by yanlinly** [comment]
目前在登录入口把namespace所有相关请求了。 其他的url暂时没拦截，因为这样会影响server的openapi。 后续我们会设计api鉴权逻辑，然后把控制台api和server api分开。
![image](https://user-images.githubusercontent.com/17695352/51718104-bc61b980-207e-11e9-858d-144381adc27d.png)
