### ISSUE TITLE
nacos部署在k8s集群上支持使用derby-db吗？如果支持，应该如何配置？

### ISSUE THREAD

**Issue by liruishan** [alibaba/nacos#6961]
**Describe the bug**
nacos部署在k8s集群上支持使用derby-db吗？

**Expected behavior**
支持derby-db

**Acutally behavior**
支持derby-db

**How to Reproduce**
我在k8s集群上配置nacos，并且使用derby-db，环境变量配置如下：
  env:
            - name: NACOS_REPLICAS
              value: "2"
            - name: EMBEDDED_STORAGE
              value: "embedded"
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848"
启动后，发现一直打印如下log，nacos没有成功启动：
2021-09-22 16:42:54,341 INFO Nacos is starting...

2021-09-22 16:42:55,342 INFO Nacos is starting...

2021-09-22 16:42:56,346 INFO Nacos is starting...

2021-09-22 16:42:57,346 INFO Nacos is starting...

**Desktop (please complete the following information):**
 - OS: centos7.6
 - Version :latest
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by realJackSun** [comment]
nacos-group项目组下面有nacos-k8s项目，里面提供了yaml文件。

**Comment by liruishan** [comment]
> nacos-group项目组下面有nacos-k8s项目，里面提供了yaml文件。

yaml文件里没有内置数据库的配置
