### ISSUE TITLE
errCode: 500, errMsg: load schema.sql error.

### ISSUE THREAD

**Issue by Jnoee** [alibaba/nacos#6962]
使用docker 部署 nacos-server:2.0.2 的 standalone 模式，出现以下错误：
`
nacos          | Caused by: java.lang.RuntimeException: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: load schema.sql error.
nacos          |        at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:60)
nacos          |        at com.alibaba.nacos.config.server.service.repository.embedded.StandaloneDatabaseOperateImpl.init(StandaloneDatabaseOperateImpl.java:60)
nacos          |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos          |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos          |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos          |        at java.lang.reflect.Method.invoke(Method.java:498)
nacos          |        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
nacos          |        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
nacos          |        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
nacos          |        ... 158 common frames omitted
nacos          | Caused by: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: load schema.sql error.
nacos          |        at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.reload(LocalDataSourceServiceImpl.java:102)
nacos          |        at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.initialize(LocalDataSourceServiceImpl.java:169)
nacos          |        at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.init(LocalDataSourceServiceImpl.java:85)
nacos          |        at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:49)
nacos          |        ... 166 common frames omitted
nacos          | Caused by: java.sql.SQLTimeoutException: Login timeout exceeded.
nacos          |        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
nacos          |        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
nacos          |        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
nacos          |        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
nacos          |        at org.apache.derby.jdbc.InternalDriver.timeLogin(Unknown Source)
nacos          |        at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
`

不是每次都会复现的，在机器较为繁忙时（用docker-compose同时启动多个服务）出现该问题的几率较大。
翻阅了之前提的bug，有显示已修复该问题，但实际并未修复。
出现该问题时，nacos-server 容器状态是正常的，容器重启机制失效，不会因为出错而重启容器，导致要注册的服务全部启动失败。

**Comment by liujiling1** [comment]
+1，愁死了

**Comment by zcz3313** [comment]
版本：1.4.2
使用k8s-helm部署
同样遇到此问题
我们的步骤是：
1.机器断电
2.机器恢复供电，依靠k8s重新调度部署pod
3.nacos无法启动，查看报错日志和楼主相同

两个怀疑方向：
1.是否和断电操作导致数据损坏有关？
2.是否和恢复供电时的启动风暴有关（大量pod争抢cpu时间片，I/O过高，导致timeout）？
@realJackSun

**Comment by xtadg** [comment]
非docker，虚拟机里也出现 +1

**Comment by KomachiSion** [comment]
derby 数据库是本地内存形数据库， 登陆超时大概率就是本地环境导致derby数据库无法响应导致的，从大家描述来看在系统繁忙时容易出现这个问题，应该和#3607不是同一个本质问题。

可以试着修改连接超时时间来看看能否解决。
