### ISSUE TITLE
questions about the data directory

### ISSUE THREAD

**Issue by Chris0408** [alibaba/nacos#6964]
**Describe the bug**

What is the role of the "/nacos/data" directory? Is it necessary to persist the dir when deploy nacos by k8s?

We found that when two nodes of a three-node nacos cluster crash at the same time, the cluster cannot automatically recovery because of the persistence of the "/nacos/data" directory, and the data in the "/nacos/data" directory needs to be manually deleted。

when the "/nacos/data" directory is not persisted, it can be automatically recoveryed  when the cluster crashes, and the startup speed is also faster

Use the official helm:  `https://github.com/nacos-group/nacos-k8s` 

**How to Reproduce**
1. Kill any two nodes in a three-node cluster with k8s statefulSet，the cluster cannot automatically recovery
2.  Turn off "/nacos/data" directory persistence, kill any two nodes in a three-node cluster with k8s statefulSet,the cluster automatically recovery
**Desktop (please complete the following information):**
 - OS: centos
 - Version  nacos-server 1.4.2, nacos-server 2.0.3

**Comment by realJackSun** [comment]
/nacos/data stores the snapshot and information of jRaft, and recovery data for config.
 
> We found that when two nodes of a three-node nacos cluster crash at the same time, the cluster cannot automatically recovery because of the persistence of the "/nacos/data" directory

Recommend to use docker/k8s to deploy nacos, in this way, if some of the nacos crashes, they can recover by the reboot of pod, which is not affected by the /nacos/data directory.

**Comment by Chris0408** [comment]
We have used k8s  statefulsets to deploy nacos cluster,the above problems will still occur。Use the official helm: `https://github.com/nacos-group/nacos-k8s`,

**Comment by Chris0408** [comment]
My question is can I turn off the persistence of the data directory during deploy nacos cluster with k8s statefulsets?

**Comment by guillaume-lin** [comment]
> My question is can I turn off the persistence of the data directory during deploy nacos cluster with k8s statefulsets?

they said the data dir is just for cache, so you can turn off the persisitence for it.
