### ISSUE TITLE
nacos控制台规律性提示“Server failed,errCode: 500, errMsg: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The conformance protocol is temporarily unavailable for reading, Invalid state for readIndex: STATE_ERROR.“

### ISSUE THREAD

**Issue by huazai0803** [alibaba/nacos#6965]
nacos使用集群方式部署，服务出现“com.alibaba.nacos.api.exception.NacosException: Request nacos server failed:”
登录nacos控制台发现“Server failed,errCode: 500, errMsg: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The conformance protocol is temporarily unavailable for reading, Invalid state for readIndex: STATE_ERROR.“
nacos server版本：v2.0.3

**Comment by realJackSun** [comment]
paste your alipay-jraft.log nacos-cluster.log and naming-server.log

**Comment by huazai0803** [comment]
> paste your alipay-jraft.log nacos-cluster.log and naming-server.lo
[alipay-jraft.log](https://github.com/alibaba/nacos/files/7214773/alipay-jraft.log)
[nacos-cluster.log](https://github.com/alibaba/nacos/files/7214781/nacos-cluster.log)
[naming-server.log](https://github.com/alibaba/nacos/files/7214782/naming-server.log)
g

**Comment by MajorHe1** [comment]
`2021-09-23 09:45:13,718 ERROR failed to report new info to target node : nacos-1.nacos-headless.default.svc.cluster.local:8848, error : caused: Connection refused;`
从 nacos-cluster的日志来看，是nacos 集群节点之间网络通信失败了，应该先检查一下集群的连通性，尤其是这种不是直接通过ip通信，还带有域名解析的，看域名解析或者转发的组件是否存在问题
