### ISSUE TITLE
nacos集群distro引发的血案

### ISSUE THREAD

**Issue by ingle-j** [alibaba/nacos#6967]
nacos版本：1.4.2、1.4.3-snapshot、2.0.3、2.1.0-snapshot
nacos-client：1.4.2
nacos集群3个节点，不同ip，dubbo服务以backup方式注册到nacos集群
**Describe the bug**
1.陆续启动3个nacos节点，待集群状态正常
2.将dubbo服务注册到nacos上，能正常使用
3.某些nacos节点因为客观因素挂了（gc、数据库连接不稳等），或手动杀进程
4.此时如果只有一台nacos，那么毫无问题能提供服务
5.只要多启动一台nacos，此时所有存活的nacos节点将变得卡顿，集群状态里信息不同步
6.看了nacos源码进行对照实验把心跳请求的CanDistro去掉集群能正常启动，但是服务列表里的服务状态会经常出现心跳不健康的服务

**Expected behavior**
重启nacos节点不应该影响到现有集群

**Acutally behavior**
重启nacos节点会导致整个集群提供不了服务，之前因为这个问题导致了线上3个小时的事故

**How to Reproduce**
1.启动nacos集群，3个节点
2.把dubbo服务注册上来，量估计要多一点，大概能保证时刻都有心跳进来即可
3.关掉2台或者关掉整个集群的所有节点
4.陆续启动nacos节点，只要有2台以上的节点，那么整个集群会变得卡顿，从管理界面进去都会卡
5.用源码自己打包，把心跳请求的CanDistro去掉就不会存在上述情况

**Comment by MajorHe1** [comment]
有几个问题要明确一下：
`nacos版本：1.4.2、1.4.3-snapshot、2.0.3、2.1.0-snapshot`

是所有的版本都会出现这个问题，还是你的集群节点是这几种不同的版本混部的？

`只要多启动一台nacos，此时所有存活的nacos节点将变得卡顿，集群状态里信息不同步`
卡顿的表现是什么？新注册的服务注册不上去？集群状态信息不同步，是nacos-server自身集群节点信息不同步？大概率是因为此时raft协议是失效的

`把心跳请求的CanDistro去掉集群能正常启动，但是服务列表里的服务状态会经常出现心跳不健康的服务`
把CanDistro注解去掉，相当于跳过了DistroFilter的逻辑，那么在 1.X版本的nacos逻辑中，客户端的注册或者心跳请求无法被转发到正确的责任节点上，nacos-server集群内部同步服务健康状态的机制也就不能正常工作，所以某些节点就会判断服务失活。

**建议**
1、如果坚持使用1.X版本的客户端，服务端重启之前删除 {nacos.home}/data目录的内容，避免raft协议选主失败造成的影响，再看看？
2、建议升级2.X版本的客户端，客户端用长连接来代替心跳和心跳的distro转发，情况应该会好很多

**Comment by wangzhenxyz1** [comment]
遇到类似的问题， 特别是集群出问题的时候控制台基本没有任何响应，还有就是在k8s下，有时候节点的leader信息就不一致了，
需要重启节点加入，而且也不是重启问题节点就行的，经常需要反复重启每个节点

**Comment by wangzhenxyz1** [comment]
大佬 @realJackSun ，修复了吗?

**Comment by zrlw** [comment]
我们已经碰到过多次这个问题了，重启一个节点导致所有节点雪崩。我们分析的原因是连接请求超过节点的处理能力了，应对措施采用的是调大注册中心tomcat的线程数，增加服务节点。甚至规定重启注册中心前要先停掉一些应用，以便把心跳请求数量先减下来。
nacos注册中心启动脚本加上自动删除 {nacos.home}/data目录的内容这个方法我们没用过，有时间可以测试一下看看效果
