### ISSUE TITLE
nacos 和grpc service和istio整合. 

### ISSUE THREAD

**Issue by siaron** [alibaba/nacos#6973]
2.0.3 支持将http协议服务同步到istio. 如果服务内部通信采用的是grpc. 目前2.0.3支持将grpc协议的服务同步吗?

**Comment by siaron** [comment]
https://github.com/alibaba/nacos/blob/5a4d433970be9b8402f57e65bffa497027f21e30/istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java#L70 这里写死了http服务.

**Comment by SpecialYang** [comment]
> https://github.com/alibaba/nacos/blob/5a4d433970be9b8402f57e65bffa497027f21e30/istio/src/main/java/com/alibaba/nacos/istio/mcp/NacosToMcpResources.java#L70
> 
> 这里写死了http服务.

是的，这个版本确实是写死了http。这个pr里修复了这个问题，你可以看下https://github.com/alibaba/nacos/pull/6746

**Comment by siaron** [comment]
这里针对istio同步有几个问题.咨询下. 
1. 默认同步的serviceEntry的name为service.group.public.nacos. 这个是不是有可以配置?
2. 时效性. 目前是定时同步服务列表. 服务实时上线下同步istio有相关设计吗? 
3. nacos相比k8s作为istio的服务发现有哪些优势.

**Comment by SpecialYang** [comment]
问题1：是个好问题，这个命名格式我们是尽量向k8s全限定服务名靠拢设计的，也是Nacos融入Istio服务网格生态后，保证服务信息风格与k8s统一。欢迎提PR来支持服务名格式自定义，我想应该很容易。

问题2：目前默认是3秒一次判断服务信息是否有变更，我们自己内部线上设置的是2秒。其实在Nacos客户端，如使用Nacos作为注册中心的RPC框架都有对订阅的服务信息有缓存，都存在一定的时效性问题。最佳实践是 服务消费者对于订阅服务的节点信息要有离群异常节点的治理能力，结合无损上下线，才能真正的做到流量无损。当前的实现方式确实会有时效性问题，但从实践结果来看，整体还是符合预期的。

问题3：我个人觉得，Nacos、Eureka、Zookeeper之类属于传统注册中心，结合RPC框架可以快速搭建一套分布式系统，但这种方案服务治理与业务代码紧耦合，而ServiceMesh的出现将两者进行了很好的分离。有许多业务系统开始从传统的架构向ServerMesh演进，起初演进时肯定不可能直接把服务发现切换为K8s Service，所以Istio提出了MCP协议来对接第三方注册中心，方便业务迁移。另外，用户的业务由于历史的原因，服务发布、订阅已经与自身业务紧耦合，并且也围绕着这些注册中心建设了许多稳定性架构，所以用户一般不会轻易丢弃这类注册中心去选择CoreDNS。总结：老业务从稳定性考虑不会轻易更换注册中心，所以需要服务网格生态集成传统注册中心。当然了新业务没有历史包袱，可以随意选型。

**Comment by siaron** [comment]
> 问题1：是个好问题，这个命名格式我们是尽量向k8s全限定服务名靠拢设计的，也是Nacos融入Istio服务网格生态后，保证服务信息风格与k8s统一。欢迎提PR来支持服务名格式自定义，我想应该很容易。
> 
> 问题2：目前默认是3秒一次判断服务信息是否有变更，我们自己内部线上设置的是2秒。其实在Nacos客户端，如使用Nacos作为注册中心的RPC框架都有对订阅的服务信息有缓存，都存在一定的时效性问题。最佳实践是 服务消费者对于订阅服务的节点信息要有离群异常节点摘除的治理能力，结合无损上下线，才能真正的做到流量无损。当前的实现方式确实会有时效性问题，但从实践结果来看，整体还是符合预期的。
> 
> 问题3：我个人觉得，Nacos、Eureka、Zookeeper之类属于传统注册中心，结合RPC框架可以快速搭建一套分布式系统，但这种方案服务治理与业务代码紧耦合，而ServiceMesh的出现将两者进行了很好的分离。有许多业务系统开始从传统的架构向ServerMesh演进，起初演进时肯定不可能直接把服务发现切换为K8s Service，所以Istio提出了MCP协议来对接第三方注册中心，方便业务迁移。另外，用户的业务由于历史的原因，服务发布、订阅已经与自身业务紧耦合，并且也围绕着这些注册中心建设了许多稳定性架构，所以用户一般不会轻易丢弃这类注册中心去选择CoreDNS。总结：老业务从稳定性考虑不会轻易更换注册中心，所以需要服务网格生态集成传统注册中心。当然了新业务没有历史包袱，可以随意选型。

感谢回复. 后续nacos有没有计划直接对接envoy. 治理流量.成为envoy的控制面. 这样是不是更加契合云原生. 当然envoy也有sdk的java/go控制面支持. 能结合使用是不是更好. 不知道理解对不对.

**Comment by SpecialYang** [comment]
Envoy是可以直接对接Nacos的，对于xDS协议来说，我们其实把Istio看做LDS和RDS server的，然后把Nacos看做CDS、EDS Server。我们目前之所以没这么做，是因为如果将Nacos作为CDS、EDS Server，那么会丢失一些Istio的流量控制，比如DestinationRule。

其实我们更加希望能够构建围绕Nacos作为控制面做一整套自己的服务网格生态，这个还在讨论和思考中。
