### ISSUE TITLE
2.0.3 source code class not found!

### ISSUE THREAD

**Issue by angeltping** [alibaba/nacos#6976]
import com.alibaba.nacos.consistency.entity.ReadRequest;
import com.alibaba.nacos.consistency.entity.Response;
import com.alibaba.nacos.consistency.entity.WriteRequest;

in com.alibaba.nacos.config.server.service.repository.embedded.DistributedDatabaseOperateImpl this class
import error not find three class

**Comment by brotherlu-xcq** [comment]
https://nacos.io/zh-cn/docs/faq.html#3.19
![image](https://user-images.githubusercontent.com/25661357/134653148-35e1f301-31bc-43a0-8893-ba9ea594167f.png)

**Comment by DickensTone** [comment]
一开始我也遇到这个错了，搜一下issues，你就会发现你不是孤独的。
At the beginning, I also encountered this mistake. Search issues, and you will find that you are not alone.
