### ISSUE TITLE
nacos-address 1.4.1 校验登录无法获取 token

### ISSUE THREAD

**Issue by 976595496** [alibaba/nacos#6980]
通过 mvn -Prelease-address clean install -Dmaven.test.skip=true  打包的 nacos-address-1.4.1 启动后所有的请求都会被拦截跳转登录页面  http://ip:8080/login    用户名密码如何获取

**Comment by kolema-tech** [comment]
> 通过 mvn -Prelease-address clean install -Dmaven.test.skip=true 打包的 nacos-address-1.4.1 启动后所有的请求都会被拦截跳转登录页面 http://ip:8080/login 用户名密码如何获取

我们的做法是自己在address-service中加上了Spring Security

```
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity security) throws Exception {
        security.csrf().disable().cors().disable().httpBasic().disable().anonymous();
    }
}
```
