### ISSUE TITLE
关于注销实例

### ISSUE THREAD

**Issue by 1327681842** [alibaba/nacos#6984]
nacos-client2.0.3版本，运行的springboot程序，被kill掉时，需要手动去注销nacos注册中心的本实例吗？如何通过onApplicationEvent手动注销实例呢？

初次使用，谢谢指导

**Comment by MajorHe1** [comment]
不需要手动注销实例，2.X版本的客户端，进程kill掉，连接就断开了，nacos-server自动注销

**Comment by 1327681842** [comment]
谢谢

**Comment by 1327681842** [comment]
> 不需要手动注销实例，2.X版本的客户端，进程kill掉，连接就断开了，nacos-server自动注销

好的，谢谢
