### ISSUE TITLE
nacos docker,more than one node??

### ISSUE THREAD

**Issue by yangyang122** [alibaba/nacos#6993]
docker ce deployed, start cmd
docker run -d \
-e MODE=cluster \
-e PREFER_HOST_MODE=hostname \
-e NACOS_SERVERS=nacos-node1,nacos-node2,nacos-node3 \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.1.3 \
-e MYSQL_SERVICE_PORT=3307 \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=deploy \
-e MYSQL_SERVICE_PASSWORD=xxx \
-p 192.168.1.9:8850:8848 \
--name nacos-node1 \
--restart=always \
--network inner_network \
nacos/nacos-server:v2.0.3

docker run -d \
-e MODE=cluster \
-e PREFER_HOST_MODE=hostname \
-e NACOS_SERVERS=nacos-node1,nacos-node2,nacos-node3 \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.1.3 \
-e MYSQL_SERVICE_PORT=3307 \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=deploy \
-e MYSQL_SERVICE_PASSWORD=xxx\
-p 192.168.1.9:8851:8848 \
--name nacos-node2 \
--restart=always \
--network inner_network \
nacos/nacos-server:v2.0.3

docker run -d \
-e MODE=cluster \
-e PREFER_HOST_MODE=hostname \
-e NACOS_SERVERS=nacos-node1,nacos-node2,nacos-node3 \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.1.3 \
-e MYSQL_SERVICE_PORT=3307 \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=deploy \
-e MYSQL_SERVICE_PASSWORD=xxx\
-p 192.168.1.9:8852:8848 \
--name nacos-node3 \
--restart=always \
--network inner_network \
nacos/nacos-server:v2.0.3

There should be three nodes, but there is one more node, resulting in abnormal cluster status, but the dataset can be configured normally。

Can you help me？ Can you help me？

**Comment by yangyang122** [comment]
配置了三个节点，无缘无故的多出一个集群节点来，导致集群状态不正常，无法正常显示集群状态

**Comment by kevinw66** [comment]
多出来的这个节点也是nacos？
看看docker里cluster.conf配置是啥样的

**Comment by yangyang122** [comment]
类似这样的：  
#2021-09-27T11:11:58.027
1e0738548565:8848
nacos-node1:8848
nacos-node2:8848
nacos-node3:8848

最上面的是多出来的，和其中一个节点的hostname相同

**Comment by yangyang122** [comment]
使用固定ip，可以正常显示，集群状态正常

**Comment by kevinw66** [comment]
在启动的时候会判断cluster.conf里是否含有本地地址，但是本地地址都是由 ip:port 代表的，在配置文件里都是hostname的时候就找不到这个地址，就会自动加上
<img width="1410" alt="image-20210927135113719" src="https://user-images.githubusercontent.com/31196226/134852470-992e8e26-b184-4eef-a672-8767eecd377e.png">

**Comment by yangyang122** [comment]
是名称的时候，校验下是同一个主机，再添加呢

**Comment by kevinw66** [comment]
启动docker的时候指定一下hostname和name一致试一试

**Comment by kevinw66** [comment]
-e PREFER_HOST_MODE=hostname --name nacos-node1 --hostname nacos-node1

**Comment by yangyang122** [comment]
可以，可以，多谢两位大佬。
