### ISSUE TITLE
docker-compose  mysql5.7.33 数据库无法连上

### ISSUE THREAD

**Issue by zhourong119** [alibaba/nacos#6994]
Exception occurred when using docker compose - f * * *. Yaml deployment
`nacos.log:Caused by: com.mysql.cj.exceptions.CJException: Unknown error 1045
nacos.log:      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
nacos.log:      at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)`
Docker image version: Nacos / Nacos server: v2.0.3
MySQL version: 5.7.33
Enter the container and use the MySQL command to link the database normally

ps:MySQL is deployed normally for 8.0.21

**Comment by kevinw66** [comment]
是不是连接参数的问题？

**Comment by zhourong119** [comment]
useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
应该不是
我自己本地装了5.7\8.0的mysql镜像，然后nacos去连接，都无法连上,不知道是不是有什么网络的机制
但是我spring-boot项目是可以正常连接的
 url: jdbc:mysql://localhost:3306/nacos?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456

**Comment by kevinw66** [comment]
docker compose文件咋写的呢？

**Comment by kevinw66** [comment]
也可以进到docker里看看logs/nacos.log打印了什么信息

**Comment by zhourong119** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.0.3.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)

**Comment by zhourong119** [comment]
version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:v2.0.3
    volumes:
      - ./cluster-logs/nacos:/data/service/cdn-center-nacos
      - ./init.d/custom.properties:/data/service/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    env_file:
      - ../env/nacos-online.env
    restart: always

**Comment by zhourong119** [comment]
version: "3"
services:
  nacos1:
    hostname: nacos
    container_name: nacos
    image: nacos/nacos-server:v2.0.3
    volumes:
      - ./cluster-logs/nacos:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    env_file:
      - ../env/nacos-online.env
    restart: always

**Comment by zhourong119** [comment]
env:
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=127.0.0.1
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3308
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=123456
MYSQL_SERVICE_DB_PARAM=useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

**Comment by zhourong119** [comment]
nacos-standalone-mysql  | 2021-09-27 13:41:04,912 ERROR Application run failed
nacos-standalone-mysql  | 
nacos-standalone-mysql  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.0.3.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
nacos-standalone-mysql  |       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
nacos-standalone-mysql  |       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
nacos-standalone-mysql  |       at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
nacos-standalone-mysql  |       at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
nacos-standalone-mysql  |       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
nacos-standalone-mysql  |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
nacos-standalone-mysql  |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
nacos-standalone-mysql  |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
nacos-standalone-mysql  |       at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos-standalone-mysql  |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql  |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql  |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql  |       at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql  |       at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos-standalone-mysql  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos-standalone-mysql  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos-standalone-mysql  |       at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
nacos-standalone-mysql  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1402)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos-standalone-mysql  |       at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
nacos-standalone-mysql  |       ... 27 common frames omitted
nacos-standalone-mysql  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos-standalone-mysql  |       at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
nacos-standalone-mysql  |       at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
nacos-standalone-mysql  |       ... 41 common frames omitted
nacos-standalone-mysql  | Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:236)
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:52)
nacos-standalone-mysql  |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql  |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql  |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql  |       at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
nacos-standalone-mysql  |       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
nacos-standalone-mysql  |       ... 53 common frames omitted
nacos-standalone-mysql  | Caused by: java.lang.IllegalStateException: No DataSource set
nacos-standalone-mysql  |       at org.springframework.util.Assert.state(Assert.java:73)
nacos-standalone-mysql  |       at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:77)
nacos-standalone-mysql  |       at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
nacos-standalone-mysql  |       at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
nacos-standalone-mysql  |       at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
nacos-standalone-mysql  |       at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:473)
nacos-standalone-mysql  |       at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:480)
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.findConfigMaxId(ExternalStoragePersistServiceImpl.java:658)
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.processor.DumpAllProcessor.process(DumpAllProcessor.java:51)
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:293)
nacos-standalone-mysql  |       at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:205)

**Comment by kevinw66** [comment]
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.0.3.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
> No DataSource set
> at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
> at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)

nacos.log里应该不止这么一点信息的，这个是控制台输出的信息么？

**Comment by zhourong119** [comment]
还有奇怪的是，启动的时候  Caused by: java.lang.IllegalStateException: No DataSource set
mysql 的日志，没有连接的日志，怀疑网络层就不通，不太清楚 nacos 连数据库使用的协议
2021-09-27T05:56:53.372783Z	   19 Connect	root@172.17.0.1 on  using TCP/IP

**Comment by kevinw66** [comment]
```
Caused by: com.mysql.cj.exceptions.CJException: Unknown error 1045
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:786)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:711)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:679)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:128)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:466)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:171)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1342)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850)
	... 187 common frames omitted
```

```
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
	... 185 common frames omitted
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
	... 188 common frames omitted
```

我看到了这两个错，不过是先后顺序的。nacos容器里连得上mysql么？

**Comment by zhourong119** [comment]
可以是在配置mysql时，没有指定mysql的版本，采用默认的版本，默认的版本过高，本地版本低。因为在mysql5中，jdbc的驱动是com.mysql.jdbc.Driver，而mysql6以及以上是com.mysql.cj.jdbc.Driver。所以在配置时要配置mysql版本号，主要配置数据源的驱动

**Comment by zhourong119** [comment]
用mysql 命令是可以连上的

**Comment by kevinw66** [comment]
看了一下你的compose文件，你docker里的nacos是想连宿主机的mysql么？按我了解的话这个默认是连不上的，你可以查一查

**Comment by zhourong119** [comment]
多谢提醒，不应该用127.0.0.1. 我现在本地8.0 ok，5.7 也ok 了，应该不是数据库版本问题，生产上的5.7.33 不行，我先试试把数据库重新建立一下，
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=192.168.3.33
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=123456
MYSQL_SERVICE_DB_PARAM=useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8

**Comment by zhourong119** [comment]
不好意思，那个数据库连接异常是我调试故意用了个不可达的host，给忘记了,这个才是正确的
[nacos.log](https://github.com/alibaba/nacos/files/7234009/nacos.log)

**Comment by zhourong119** [comment]
但是错误却是是同一个，容器内到msyql网络是通的

**Comment by kevinw66** [comment]
> 不好意思，那个数据库连接异常是我调试故意用了个不可达的host，给忘记了,这个才是正确的
> [nacos.log](https://github.com/alibaba/nacos/files/7234009/nacos.log)

`Unknown error 1045`，这个日志文件报错很明确哈，你可以查一下。
还有 给容器加点内存吧，全是memory的报错

**Comment by zhourong119** [comment]
我这边确定了，数据库密码为特殊字符时会有问题，我把生产上的复杂密码 设置为我本地的密码，其他的未修改，复现该问题
我数据密码包括 { , $

**Comment by zhourong119** [comment]
不支持密码包含英文逗号
