### ISSUE TITLE
Is there a way to reload the logback.xml file when doing logging configuration refreshing?

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [alibaba/nacos#6999]
Here is my situation( something similar with issues below)
[issue 6344](https://github.com/alibaba/nacos/issues/6344)
[issue 2259](https://github.com/alibaba/nacos/issues/2259)
but these issues seems not to give any constructive ideas how to achieve my goals.

I want to achieve 4 goals:
1. (already done) To make several of the same logback-spring.xml file from my applications into one , then put it into nacos.

2. (already done) To make sure when configurations were modified, the local log configurations will be change immediately.

3. (stucked and unsolved) When the application started, do use the logback-spring.xml in nacos instead of local one, but it seems no way to configure using ```logging.config:http://${spring.cloud.nacos.config.server-addr}/nacos/v1/cs/configs?group=DEFAULT_GROUP&tenant=${spring.cloud.nacos.config.namespace}&dataId=logback-spring.xml``` because I have turned on the authToken function, it will throw 403 exception.

4. (stucked and unsolved) If the method ```reinitializeLoggingSystem``` was invoked after someting was chaged in nacos configuration center, the logback-spring.xml should be reloaded in conditional when reinitializing the context, to make sure if there is a change in logback-spring.xml.

So far I have found that each time nacos refreshing the config, ```initializeWithConventions``` will be invoked and reload the local logback-spring.xml, but still not get any approaching to problem 3 and 4.

**Comment by WilliamChen-luckbob** [comment]
In this way, I have to only restart the applications once, to add the new dependency of logback-module, then problems were solved.

**Comment by flmelody** [comment]
you got the other way, I guess you want to change you logging configuration in runtime,you could do like below
 1.define a properties bean with your need properties.
 2.define a ApplicationListener ,like NacosLoggingListener , ContextRefreshedEvent and RefreshScopeRefreshedEvent you could have a try.
 3.append your logging appender to logging system  after event publish.

**Comment by hujun-w-2** [comment]
@i will solve it@

**Comment by hujun-w-2** [comment]
这是nacos sdk的一个bug  只要引用了nacos sdk  应用的自身的logback就不会自动刷新了，我尝试解决一下这个问题

**Comment by KomachiSion** [comment]
The solution of #6999 will cause some problem for nacos logs, so revert it and will found other way to fix.
