### ISSUE TITLE
It's better to add version label nearby NACOS banner on Nacos server bat or sh console

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#70]
As title

**Comment by HaojunRen** [comment]
Just like 'Spring Boot  vxx.xx"

**Comment by yanlinly** [comment]
0.3.0 has supported
http://console.nacos.io/nacos/index.html

**Comment by HaojunRen** [comment]
这个问题，不是说是在界面上，而是在dos窗口或者linux窗口上显示版本号，在nacos起来的时候
