### ISSUE TITLE
Problem caused by the change in the meaning of "count" in the return of com.alibaba.nacos.naming.controllers.ServiceController#list in v2.0

### ISSUE THREAD

**Issue by vanto-** [alibaba/nacos#7001]
**Describe the bug**
The meaning of "count" in the return of com.alibaba.nacos.naming.controllers.ServiceController#list changes in v2.0，v1.0 returns totalCount, while v2.0 returns pageSize, which can lead to some software logic errors, such as When dubbo uses nacos as a registry, get all service list is incomplete. @see org.apache.dubbo.registry.nacos.NacosRegistry#getAllServiceNames

![image](https://user-images.githubusercontent.com/3469401/135064355-0b940378-ee88-41e9-9704-3e900d590ba3.png)

 - Version [nacos-server 2.0.3, nacos-client 1.4.2, dubbo-2.7.12]

Problems with nacos-client 2.0.3 persist

**Comment by brotherlu-xcq** [comment]
yes, it's totalCount in Nacos 1.x, but count in Nacos 2.x. return the current count is no use for user, I think we should keep return the totalCount.

**Comment by vanto-** [comment]
@brotherlu-xcq When can we resume this problem?

**Comment by brotherlu-xcq** [comment]
If others agree this change, I will fix it as soon as possible.
