### ISSUE TITLE
2.x,1.x  EncryptedData bug in client.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#7039]
**Describe the bug**
relate [ISSUE #5367]SPI IConfigFilter (#5369) 

1.4.2 Implementation of IConfigFilter spi configuration decryption, there is a problem when CacheData maintains the content and md5 values, the maintenance is encrypted content, and md5 is obtained from the decrypted content; because CacheData.md5 is wrong, every time checkUpdateDataIds will get changedGroupKeys, thus continuously GetServerConfig after listening. For details, please see LongPollingRunnable.

---

1.4.2 实现 IConfigFilter spi 配置解密，在 CacheData 维护 content 和 md5 值时有问题，维护的为加密内容，且md5从解密内容得到；因 CacheData.md5 不对，所以每次 checkUpdateDataIds 都会得到 changedGroupKeys，从而不断地进行 listening 后 getServerConfig。具体情况请看 LongPollingRunnable 

![image](https://user-images.githubusercontent.com/16837364/136642330-3d47ab15-b3c3-4d33-a065-06bcc7f96026.png)

**Expected behavior**
CacheData  cache decryptContent and decryptContent's md5.

**Acutally behavior**
CacheData cache encryptedContent  and encryptedContent's md5.

**Comment by CherishCai** [comment]
AbstractConfigChangeListener parseChangeData not right content bug.

![image](https://user-images.githubusercontent.com/16837364/147043901-9fe8b6f9-4222-48b7-a418-189937dfac10.png)

**Comment by CherishCai** [comment]
这里还会有一个 bug，因为 `String content = getConfig(dataId, group, timeoutMs);` 拿到的是解密后的内容；然后 worker.addTenantListenersWithContent 的逻辑再执行了一次。看了代码不好解决，还是期待一次重构治理。
暂时调用分开为 getConfig 和 addListener 吧[笑哭]
```java
@Override
    public String getConfigAndSignListener(String dataId, String group, long timeoutMs, Listener listener)
            throws NacosException {
        String content = getConfig(dataId, group, timeoutMs);
        worker.addTenantListenersWithContent(dataId, group, content, Arrays.asList(listener));
        return content;
    }
```

**Comment by CherishCai** [comment]
2.x 的加解密一样存在问题，以下列出的是临时修复方案

https://github.com/alibaba/nacos/pull/7191
https://github.com/alibaba/nacos/pull/7479

**Comment by CherishCai** [comment]
@li-xiao-shuang 哈哈，2.x 这部分加解密要不要统一看下

**Comment by li-xiao-shuang** [comment]
1.x  服务端没有适配加解密，加解密只在 > 2.0.3 做了

**Comment by li-xiao-shuang** [comment]
> @li-xiao-shuang 哈哈，2.x 这部分加解密要不要统一看下

如果你要使用配置加解密 建议就使用2.x 的版本，如果 2.x 的有什么bug可以一起解决下

**Comment by CherishCai** [comment]
@li-xiao-shuang 没事哈，我内部都定制了，所以知道客户端有些 bug ，才提的 issue 和 PR

**Comment by li-xiao-shuang** [comment]
> @li-xiao-shuang 没事哈，我内部都定制了，所以知道客户端有些 bug ，才提的 issue 和 PR

客户端这块  2.x  我有空在详细看看

**Comment by CherishCai** [comment]
@ ready to close @

2.x fix in  #8463 , 1.4.x encrypted imperfect, so no need to deal with.

2.x 已修复，1.4.x 配置加密并不完善，故无需处理。
