### ISSUE TITLE
Nacos cluster mode starts, if there are multiple NICs in the local, it will not be able to resolve ip

### ISSUE THREAD

**Issue by vicykie** [alibaba/nacos#704]
![image](https://user-images.githubusercontent.com/9333444/51670498-b4afff80-2001-11e9-8d23-d0785aae2caa.png)

建议增加配置解析指定网卡

**Comment by yanlinly** [comment]
Multicast, you can specify native IP through this parameter
-Dnacos.server.ip=xx

![image](https://user-images.githubusercontent.com/17695352/51885150-44202e80-23c5-11e9-80d7-40c5f1c962a7.png)
