### ISSUE TITLE
Compile Nacos2.0, protobuf dependency is missing

### ISSUE THREAD

**Issue by complone** [alibaba/nacos#7047]
**Describe the bug**

Compile Nacos2.0, protobuf dependency is missing

**Expected behavior**

**Acutally behavior**
The nacos-isito module lacks related proto files

**How to Reproduce**
I am trying to make an image for nacos based on GraalVM, but first need to package nacos 2.0, the work content is as follows:
https://github.com/alibaba/nacos/issues/6869

Use the following plugin to package: 

https://www.graalvm.org/reference-manual/native-image/NativeMavenPlugin/

1. When compiling the nacos-istio module of nacos, the google/api/field_behavior.proto and "google/rpc/status.proto" files are missing. I am trying to migrate related files from googleapi.
Porting files from googleapi: https://github.com/googleapis/googleapis/tree/master/google

2. After compiling and generating the class file, com.google.protobuf.AbstractMessage.InternalOneOfEnum could not find the relevant file, and the answer is [unable-to-use-oneof- symbol-internaloneofenum-missing](https://stackoverflow.com/questions/58537310/grpc-maven-unable-to-use-oneof-symbol-internaloneofenum-missing). Hope to upgrade the version of protobuf from 3.8.0 to 3.9.0. So that I can complete the compilation work

**Desktop (please complete the following information):**
 - OS: Ubantu 16.04
 - Version nacos 2.0
 - Module  nacos-isito

**Additional context**

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
