### ISSUE TITLE
Nacos 2.0.3 启动无报错，无法访问 Web 控制台

### ISSUE THREAD

**Issue by ageovb** [alibaba/nacos#7056]
### 问题现象

Docker 安装 Nacos 2.0.3，将容器内的 /home/nacos/conf/application.properties 映射到主机中，然后修改主机的 application.properties 将数据源修改为 MySQL，重新启动 Nacos 后，无法访问 Web 控制台。

但是如果不进行配置文件的映射，直接修改容器里的  application.properties，是可以正常访问 Web 控制台的。

### 复现方法

1. Docker 安装 MySQL 8.0.26 并创建一个名为 nacos_config 的 schema，然后创建 Nacos 2.0.3 数据库表。
2. Docker 安装 Nacos 2.0.3
3. 主机中创建映射文件夹：`mkdir -p /opt/nacos/conf/`
4. 启动容器：`docker run -d --name nacos -p 8848:8848 nacos/nacos-server`
5. 获取容器 ID（如 a7f8f0567703）：`docker ps | grep nacos`
6. 拷贝配置文件：`docker cp a7f8f0567703:/home/nacos/conf/application.properties /opt/nacos/conf/application.properties`
7. 强制删除容器：`docker rm -f nacos`
8. 查看 bridge 网络信息，找到 MySQL 内网 IP 地址：`docker network inspect bridge`
9. 修改配置文件，将 Nacos 数据源切换为 MySQL：`vim /opt/nacos/conf/application.properties`
10. 启动容器：
```
docker run -d --name nacos -p 8848:8848 \
--restart always \
-e MODE=standalone \
-e PREFER_HOST_MODE=hostname \
-v /opt/nacos/conf:/home/nacos/conf \
nacos/nacos-server
```
11. 访问`主机IP:8848/nacos`

### 环境信息
操作系统：WLS 2 Ubuntu-20.04

Docker Engine - Community 20.10.7

**Comment by onewe** [comment]
@ageovb 无法打开控制台是因为 nacos 无法连接到数据库, 你可以验证一下 nacos 容器访问 mysql 的 3306 端口是否是通的.(如果没记错,默认情况下是隔离的)

**Comment by Nicemale** [comment]
> @ageovb 无法打开控制台是因为 nacos 无法连接到数据库, 你可以验证一下 nacos 容器访问 mysql 的 3306 端口是否是通的.(如果没记错,默认情况下是隔离的)

我用你们linux alibaba 5.x os启动1..4.1可以运行，但是启动2.0.x的都是停在初始化完成那里，就再也没动静了，也没报错，config-fatal.log里也没东西，就一句isQuickStart=false和mysql连接信息的info打印，mysql连接是ok的。

**Comment by onewe** [comment]
@Nicemale 描述一下复现步骤

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
