### ISSUE TITLE
Cannot log in after entering the user name and password in version 0.8.0

### ISSUE THREAD

**Issue by shikonglaike** [alibaba/nacos#706]
登陆以后输入用户名和密码。无法登陆，前台报错，见下图。我还没找到具体具体原因。
![image](https://user-images.githubusercontent.com/19699936/51728257-90f4c400-20aa-11e9-8369-b5c0e9a998eb.png)

**Comment by echooymxq** [comment]
use OpenJDK?

**Comment by yanlinly** [comment]
please look it this.
https://github.com/jwtk/jjwt/issues/429
