### ISSUE TITLE
com.alibaba.nacos.consistency 是不是缺失了 entity 的包？？

### ISSUE THREAD

**Issue by hsamgle** [alibaba/nacos#7062]
com.alibaba.nacos.consistency 是不是缺失了 entity 的包？？

ConsistencyProtocol 里面的 

import com.alibaba.nacos.consistency.entity.GetRequest;
import com.alibaba.nacos.consistency.entity.Log;
import com.alibaba.nacos.consistency.entity.ReadRequest;
import com.alibaba.nacos.consistency.entity.WriteRequest;

报错，无效引入

**Comment by realJackSun** [comment]
mvn compile一下就出来了。

**Comment by hsamgle** [comment]
执行了不行哦！ 代码是compile 自动生成的吗?

分支 2.0.0 ,如果所示 com.alibaba.nacos.consistency 包内并没有 entity 包
![image](https://user-images.githubusercontent.com/18696503/136928635-a4a2275a-76b4-493e-a211-6be8f25cee5c.png)

**Comment by qiao-zhi** [comment]
mac 环境下如何操作？
