### ISSUE TITLE
nacos的集群模式支持使用内置derby数据库吗？

### ISSUE THREAD

**Issue by liruishan** [alibaba/nacos#7066]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by MajorHe1** [comment]
显然支持。
值得注意的是，使用内置derby数据库，由raft协议保证节点间数据一致性。

**Comment by MajorHe1** [comment]
https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html
