### ISSUE TITLE
@NacosConfigListener在spring-cloud-starter-alibaba-nacos-config不生效

### ISSUE THREAD

**Issue by superbing** [alibaba/nacos#7075]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.6.RELEASE</version>
        </dependency>
2. @NacosConfigListener(dataId = "cloud-config.properties")
    public void onChangeValue(String value) {
        System.out.println(value);
    }
3.

**Comment by future94** [comment]
So do I. Did you fix it？
