### ISSUE TITLE
[nacos-server-2.0.3]startup.sh脚本有误,java11,mac m1。已修改，修改后的兼容Java9以下

### ISSUE THREAD

**Issue by jktimmer** [alibaba/nacos#7086]
java
![image](https://user-images.githubusercontent.com/37511333/137592857-b969f1b5-e270-4871-a156-f800aefeb212.png)
---
platform
![image](https://user-images.githubusercontent.com/37511333/137592969-db0ce096-99d8-429c-85fd-8574c56704ac.png)
##
下载的sh脚本(error line)
![image](https://user-images.githubusercontent.com/37511333/137593324-a1b490e9-856a-44ba-adcd-be977e869d40.png)
##
更改后正确的
![image](https://user-images.githubusercontent.com/37511333/137593361-4d9945f3-80a7-4a09-98d3-8571ffb265f4.png)

**Comment by jktimmer** [comment]
顺带说一句，启动报错也报错
[start.log](https://github.com/alibaba/nacos/files/7357778/start.log)

**Comment by brotherlu-xcq** [comment]
启动有报错吗？这里家引号主要是为了兼容jdk8下，java路径里面有空格的问题。

**Comment by jktimmer** [comment]
是的，有引号的sh，启动显示没有找到clss类，去掉引号就正常了，我更换成java8，去除引号的sh也可以使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月18日(周一) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] [nacos-server-2.0.3]startup.sh脚本有误,java11,mac m1。已修改，修改后的兼容Java9以下 (#7086)




 
启动有报错吗？这里家引号主要是为了兼容jdk8下，java路径里面有空格的问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
