### ISSUE TITLE
My project can't start up because the DubboServiceMetadataRepository is null

### ISSUE THREAD

**Issue by 17722626616** [alibaba/nacos#7089]
**Environment:**
1. Spring Cloud + Spring Boot + Dubbo + Nacos
1) Spring cloud : Greenwich
2) Spring Boot : 2.1.5.RELEASE
3) Dubbo 2.7.8
4) Nacos 1.4.2

**Expected Result**

It can startup normally.

**Actual Result**

Our project is using the Spring Cloud + Spring Boot + Dubbo + Nacos, but
![1](https://user-images.githubusercontent.com/52815396/137667622-b238791a-bd89-4721-839e-ab2d417d5b03.png)
![2](https://user-images.githubusercontent.com/52815396/137667633-0c3004b6-4211-44bb-a518-92b95541817c.png)

When I start up my project ,it encounterred the DubboServiceMetadataRepository NullPointException,

could you help me regarding this problem? 

and the following dubbo and nacos version that I am using:

1. dubbo 
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-dubbo</artifactId>
	<version>2.1.4.RELEASE</version>
	<exclusions>
		<exclusion>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
		</exclusion>
	</exclusions>
</dependency>

2.nacos
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
	<version>0.9.0.RELEASE</version>
</dependency>

3. spring cloud :
 Greenwich

4. spring boot
<dependency>
     <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-dependencies</artifactId>
      <version>2.1.5.RELEASE</version>
</dependency>

**Comment by lee-0421** [comment]
same for me have you resolved this problem?

**Comment by KomachiSion** [comment]
I think it's duddo problem. Not nacos.
