### ISSUE TITLE
修改密码后，重启nacos，无需登录也能进入

### ISSUE THREAD

**Issue by amazCode** [alibaba/nacos#7096]
1.nacos版本 ：2.0.3
2.目前修改的配置：开启了数据库配置；修改为单机启动；
1.遇到的问题：第一次登录后，修改了密码，然后重启nacos，输入登录地址，直接进入主页面

**Comment by yybht155** [comment]
请问这个有解决办法了吗

**Comment by SteafanMrZhou** [comment]
看了下源码，用户在修改密码完成之后，只是同步更新了下数据库，并没有做后续的鉴权操作。

**Comment by SteafanMrZhou** [comment]
按照现在的源码逻辑，用户在修改完密码之后，需要重新生成用户的 token ，并返回给前端：
![image](https://user-images.githubusercontent.com/23360739/144992956-9172fcf2-bdf1-41a6-853b-65829bdf703d.png)
然后，在用户刷新界面的时候，Nacos 会获取当前 Nacos 的 Server State 信息，可以在这个 state 接口中增加对用户登录状态的判断：
![image](https://user-images.githubusercontent.com/23360739/144993637-18685621-8ad5-4a97-8d4e-d656ace3c344.png)
即将 accessToken 与新生成的 newStatusToken 作比较，如果两者相同，则不需要重新登录，否则，前端控制强制跳转到 Nacos 的登录页，指引用户重新登录。

**Comment by SteafanMrZhou** [comment]
@realJackSun 我提交了 PR ，辛苦大佬看下哈。
