### ISSUE TITLE
nacos 2.0.3 ldap 当有多个ou时，不能索引所有的记录

### ISSUE THREAD

**Issue by jy00278439** [alibaba/nacos#7099]
nacos.core.auth.ldap.userdn=cn={0},dc=test,dc=com
nacos.core.auth.ldap.userdn=cn={0},ou=ops,dc=test,dc=com

ldap 当有多个ou时，不能索引所有的记录

![image](https://user-images.githubusercontent.com/3014548/137899689-9aaa9590-4463-4a8f-8085-51a456719bd0.png)

**Comment by KeithTt** [comment]
Same problem here.

Nacos version: 2.0.4

Is there any update...?

**Comment by jy00278439** [comment]
从配置文件上看，没有变化。
后面并没有使用这个版本，所以现在也不清楚。

**Comment by KeithTt** [comment]
@jy00278439 之前的版本调好了吗？是不是每个 OU 都单独加一个配置就可以？
