### ISSUE TITLE
Improved support for MySQL 8.*

### ISSUE THREAD

**Issue by Dhweicheng** [alibaba/nacos#710]
问题代码：
@Service("basicDataSourceService")
public class BasicDataSourceServiceImpl implements DataSourceService {
    private static final String JDBC_DRIVER_NAME = "com.mysql.jdbc.Driver";
}
config模块指定了driverClassName，造成不支持高版本数据库；
可通过修改当前类下的reload方法实现：
//自定义driverClassName
 val = env.getProperty("db.driverClassName." + i);
                if (null == val) {
                    fatalLog.error("db.driverClassName." + i + " is null");
                    throw new IllegalArgumentException();
                }
                ds.setDriverClassName(val.trim());
并在nacos\conf\application.properties增加配置：
spring.datasource.platform=mysql
db.num=1
db.driverClassName.0=com.mysql.cj.jdbc.Driver
db.url.0=***
同时修改naming模块： import com.mysql.jdbc.jdbc2.optional.MysqlDataSource; 改成 import com.mysql.cj.jdbc.MysqlDataSource;
希望后期通过配置实现。

**Comment by SessionBest** [comment]
you can dependency the mysql high version.

<dependency>
 <groupId>mysql</groupId>
 <artifactId>mysql-connector-java</artifactId>
 <version>8.0.14</version>
</dependency>

fix it for mysql 8 ~

**Comment by TsingLiang** [comment]
mysql 8.x will be surported in 1.0 release
