### ISSUE TITLE
nacos 2.0.2 openapi 取不到配置

### ISSUE THREAD

**Issue by samunbest** [alibaba/nacos#7101]
**Describe the bug**
使用openapi有时取到旧版配置 有时取不到配置 日志没有相关报错

**Expected behavior**
修改配置客户端能正常拉取到最新的

**Acutally behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: centos7.6
 - Version nacos-server 2.0.2, nacos-client 2.0.2
 - Module config
 - SDK openapi

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
