### ISSUE TITLE
nacos2.0.3集群在UI界面点击某个节点下线后，集群异常

### ISSUE THREAD

**Issue by jacknotes** [alibaba/nacos#7108]
nacos2.0.3集群在UI界面点击某个节点下线后，集群异常，如图
正常集群状态：
![image](https://user-images.githubusercontent.com/58760465/138198542-ab5799c6-be77-44df-9695-8dcf28e135a6.png)
关闭192.168.13.31:8848这个节点后状态：
![image](https://user-images.githubusercontent.com/58760465/138198643-7b3af762-bb4e-422e-8814-2c9b1ff0e9ce.png)
点击下线这个服务关闭的节点：
![image](https://user-images.githubusercontent.com/58760465/138198747-ed5c0c8a-cd76-4815-891a-29ee72e87876.png)
下线后状态时不时的异常：
![image](https://user-images.githubusercontent.com/58760465/138198818-2cdb0147-e691-4991-aeb1-f8e609becc15.png)
重新加入节点：
1. 3个节点的端口侦听状态
![image](https://user-images.githubusercontent.com/58760465/138199364-1a1e285e-dd85-40eb-b6bc-c14e10f31320.png)
2. 配置conf/cluster.conf，添加新节点，但是此时文件不让修改，无法配置成功。
![image](https://user-images.githubusercontent.com/58760465/138199337-a332adba-bc73-4447-83a9-2c442e8961d2.png)
3. 删除新加入节点旧数据，然后启动服务
![image](https://user-images.githubusercontent.com/58760465/138200327-2b30bff7-6e0b-468a-b6cd-1a612102f625.png)
![image](https://user-images.githubusercontent.com/58760465/138200441-cc0f82ce-bc1f-4d42-a9dd-f2eccf0b63b8.png)
4. 集群192.168.13.32:8848和192.168.13.33:8848UI上无法显示192.168.13.31:8848在线，但是raft协议识别了192.168.13.31:8848
![image](https://user-images.githubusercontent.com/58760465/138200650-4f826388-654d-4baf-969d-8828348501b0.png)
![image](https://user-images.githubusercontent.com/58760465/138200689-45abdc9b-707e-46a1-b540-82f1934c2bf8.png)
而192.168.13.31:8848显示正常，但往192.168.13.31:8848注册服务时无法正常，而往192.168.13.32:8848和192.168.13.33:8848注册服务正常：
![image](https://user-images.githubusercontent.com/58760465/138200775-11d5dcee-bc1e-4d36-b2d4-d27adc0aa607.png)
![image](https://user-images.githubusercontent.com/58760465/138200907-1ff3cb4b-2465-47de-9d4d-67af594f01cf.png)

**Comment by yb2020** [comment]
我也遇到了同样的问题，下线后集群各种不正常，是否集群三个节点，这种部署方式压根不能做为高可用的方案？需要3+以上的节点？因为宕掉或下线一个节点，server集群不正常，注册的服务数量也不正常。我预期的是部署了集群，可能在短时间继续提供服务。

**Comment by jacknotes** [comment]
是的，不知道怎么解决，现在没有好的解决办法，能做的是不在UI界面对节点进行管理。

**Comment by liudechao1** [comment]
我也遇到了这个问提，管理端下线集群节点后，再恢复节点，没下线的两个节点cluster.conf文件不能修改加入新的节点，这个目前有什么办法解决？

**Comment by fency12** [comment]
这个集群管理太坑了。我也是下线了一个节点，然后机器服务器重装了 系统，重新启动docker，集群就异常了，服务一会好一会坏的，折腾了一个多小时。最后把所有节点都点击下线，然后重启才好。不知道是为啥，我用的还是外置数据库。

**Comment by jacknotes** [comment]
> 我也遇到了这个问提，管理端下线集群节点后，再恢复节点，没下线的两个节点cluster.conf文件不能修改加入新的节点，这个目前有什么办法解决？

你们有解决办法了吗？

**Comment by jacknotes** [comment]
> 这个集群管理太坑了。我也是下线了一个节点，然后机器服务器重装了 系统，重新启动docker，集群就异常了，服务一会好一会坏的，折腾了一个多小时。最后把所有节点都点击下线，然后重启才好。不知道是为啥，我用的还是外置数据库。

这个问题你们有解决办法了吗？

**Comment by KomachiSion** [comment]
下线的接口已经暂时被移除了，如果后续没有好的设计方案，后续将不会开放这种运维方式。
