### ISSUE TITLE
能提供一下Grpc请求注册实例的json样例吗，十分感谢！Could you please provide the JSON sample of Grpc request registration instance? Thank you very much  

### ISSUE THREAD

**Issue by kuaile-zc** [alibaba/nacos#7110]
**Describe the bug**
我在进行压力测试，当我测试到grpc的时候使用jmeter-grpc插件
但是我查看nacos_grpc_service.proto 文件的时候发现了一个Any 。在我绞尽脑汁一阵狂敲键盘之后我发现无法征服Any这个字段
--
I'm doing stress testing and using the Jmeter-grPC plug-in when I'm testing GRPC  
But when I look at nacOS_GRpc_service. proto, I find an Any.  After a while of typing furiously at my brain, I found myself unable to conquer the Any field  
message Payload {
  Metadata metadata = 2;
  google.protobuf.Any body = 3;
}

请求官方帮助能提供一个注册实例的Json样例吗？我的样例如下但是无法成功：
Can request official help provide a Json sample of the registered instance?  My example is the following but failed:  
{
  "metadata" : 
	{"clientIp": "127.0.0.1", 
	"type":"InstanceRequest", 
	"headers": {},
  "body" : {
  "namespaceId": "8bc62a63-ac99-44fc-86bc-b042ed7da6a3",
  "serviceName": "test_nacos",
  "groupName": "test",
  "type": "registerInstance",
  "instance" : {
			"ip": "127.0.0.1",
			"port": "8848",
			"serviceName": "test_nacos"
		}
  
	}
}
我猜想一定是body 这个类型 Any没有正确的使用。我查看官网之后发现官网的描述也是寥寥无几
I guess the body type Any is not being used correctly.  After checking the official website, I found that the description on the official website is also very few  
![图片](https://user-images.githubusercontent.com/37325510/138252105-092a15eb-828d-46be-98fd-91c8fdd1228a.png)

![图片](https://user-images.githubusercontent.com/37325510/138252312-1b8bb2a8-708b-4f1a-baaf-a3efbacfabd2.png)

所以希望能得到帮助。
So I hope I can get help.

Could you please provide the JSON sample of Grpc request registration instance? Thank you very much  

**Desktop (please complete the following information):**
 - OS: Linux k8s
 - Version nacos 2.0.3
 - Module all
 - SDK Jmeter
**Additional context**

**Comment by kuaile-zc** [comment]
@KomachiSion ，大佬你们内部测试Grpc有例子吗？求sample。
Hi BIG-HAND! Do you have any examples of internal Grpc testing? For the sample

**Comment by onewe** [comment]
@kuaile-zc  You can see NamingGrpcClientProxyTest.java

**Comment by onewe** [comment]
@kuaile-zc 
The 'Any' object in java is a InstanceRequest Object when the nacos client registers service. I run NamingGrpcClientProxyTest and get json string.

```json
{
	"headers": {
		"app": "unknown"
	},
	"requestId": "xxxxxx",
	"namespace": "ns1",
	"serviceName": "service1",
	"groupName": "group1",
	"type": "registerInstance",
	"instance": {
		"ip": "1.1.1.1",
		"port": 1111,
		"weight": 1.0,
		"healthy": true,
		"enabled": true,
		"ephemeral": true,
		"serviceName": "service1",
		"metadata": {},
		"instanceHeartBeatInterval": 5000,
		"instanceHeartBeatTimeOut": 15000,
		"ipDeleteTimeout": 30000,
		"instanceIdGenerator": "simple"
	},
	"module": "naming"
}
```

**Comment by kuaile-zc** [comment]
> 
> 
> @kuaile-zc The 'Any' object is a InstanceRequest Object when the nacos client registers service. I run NamingGrpcClientProxyTest and get json string.
> 
> ```json
> {
> 	"headers": {
> 		"app": "unknown"
> 	},
> 	"requestId": "xxxxxx",
> 	"namespace": "ns1",
> 	"serviceName": "service1",
> 	"groupName": "group1",
> 	"type": "registerInstance",
> 	"instance": {
> 		"ip": "1.1.1.1",
> 		"port": 1111,
> 		"weight": 1.0,
> 		"healthy": true,
> 		"enabled": true,
> 		"ephemeral": true,
> 		"serviceName": "service1",
> 		"metadata": {},
> 		"instanceHeartBeatInterval": 5000,
> 		"instanceHeartBeatTimeOut": 15000,
> 		"ipDeleteTimeout": 30000,
> 		"instanceIdGenerator": "simple"
> 	},
> 	"module": "naming"
> }
> ```

Thanks！！

**Comment by onewe** [comment]
@kuaile-zc  That's all right.

**Comment by DSSLP** [comment]
> > @kuaile-zc The 'Any' object is a InstanceRequest Object when the nacos client registers service. I run NamingGrpcClientProxyTest and get json string.
> > ```json
> > {
> > 	"headers": {
> > 		"app": "unknown"
> > 	},
> > 	"requestId": "xxxxxx",
> > 	"namespace": "ns1",
> > 	"serviceName": "service1",
> > 	"groupName": "group1",
> > 	"type": "registerInstance",
> > 	"instance": {
> > 		"ip": "1.1.1.1",
> > 		"port": 1111,
> > 		"weight": 1.0,
> > 		"healthy": true,
> > 		"enabled": true,
> > 		"ephemeral": true,
> > 		"serviceName": "service1",
> > 		"metadata": {},
> > 		"instanceHeartBeatInterval": 5000,
> > 		"instanceHeartBeatTimeOut": 15000,
> > 		"ipDeleteTimeout": 30000,
> > 		"instanceIdGenerator": "simple"
> > 	},
> > 	"module": "naming"
> > }
> > ```
> 
> Thanks！！

想问下最后在jmeter发送的request是长这样的吗？我这边按这么测试还是不行，能给个最终的请求样例吗？十分感谢！！！
{
  "metadata": {
    "type": "InstanceRequest",
    "clientIp": "10.78.75.254"
  },
  "body": {
    "headers": {
      "app": "unknown"
    },
    "requestId": "xxxxxx",
    "namespace": "ns1",
    "serviceName": "service1",
    "groupName": "group1",
    "type": "registerInstance",
    "instance": {
      "ip": "1.1.1.1",
      "port": 1111,
      "weight": 1,
      "healthy": true,
      "enabled": true,
      "ephemeral": true,
      "serviceName": "service1",
      "metadata": {},
      "instanceHeartBeatInterval": 5000,
      "instanceHeartBeatTimeOut": 15000,
      "ipDeleteTimeout": 30000,
      "instanceIdGenerator": "simple"
    },
    "module": "naming"
  }
}
