### ISSUE TITLE
能否加一个配置，让nacos-2.0.x启动后，doubleWriteEnabled为false。

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#7112]
容器如果出现意外，容器重启后doubleWriteEnabled又开启了
要去执行一次curl -X PUT 'localhost:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false'

**Comment by kuaile-zc** [comment]
兄弟双写是啥意思？能解释一下，我这边K8s集群2.0.3杀掉一个实例之后重启。集群正常之后会出现一定量的错误。与这个有关系吗？

**Comment by MajorHe1** [comment]
> 兄弟双写是啥意思？能解释一下，我这边K8s集群2.0.3杀掉一个实例之后重启。集群正常之后会出现一定量的错误。与这个有关系吗？

nacos 1.X版本和2.X版本的服务模型不一样，为了能够完成平滑升降级，需要将数据进行双写，分别生成Nacos1和Nacos2的数据结构进行存储。因此会对性能有一定影响。当集群升级并稳定运行后，可以关闭双写，关闭双写后将会失去平滑降级的功能。https://nacos.io/zh-cn/docs/2.0.0-upgrading.html

要看你的错误是什么东西才能判断是什么原因导致的，建议另开issue讨论

**Comment by kuaile-zc** [comment]
> 
> 
> > 兄弟双写是啥意思？能解释一下，我这边K8s集群2.0.3杀掉一个实例之后重启。集群正常之后会出现一定量的错误。与这个有关系吗？
> 
> nacos 1.X版本和2.X版本的服务模型不一样，为了能够完成平滑升降级，需要将数据进行双写，分别生成Nacos1和Nacos2的数据结构进行存储。因此会对性能有一定影响。当集群升级并稳定运行后，可以关闭双写，关闭双写后将会失去平滑降级的功能。https://nacos.io/zh-cn/docs/2.0.0-upgrading.html
> 
> 要看你的错误是什么东西才能判断是什么原因导致的，建议另开issue讨论

哥帮忙看看这个问题有遇到过吗，我感觉在K8s上面部署集群问题很多。
https://github.com/alibaba/nacos/issues/7158

**Comment by iQuanhe** [comment]
> 

so do i

**Comment by dennissky** [comment]
关闭双写会影响1.x的客户端吗

**Comment by KomachiSion** [comment]
2.1.0 solved。
