### ISSUE TITLE
[Code Quality] export the constants of module nacos-auth.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/nacos#7114]
**Description**

This issue is the sub-issue of #5726 , it mainly work on exporting the constants of module `nacos-auth`. you can find more detail info and rule in #5726.

**Comment by onewe** [comment]
@brotherlu-xcq Hi bro, I had finished it at the summer2021_issue#5696 branch. 
@KomachiSion  I think  that the Constants.java file call "AuthModuleConstant.java" better. So I want refactor this. 🤷‍♂️
