### ISSUE TITLE
service not found

### ISSUE THREAD

**Issue by chen462488588** [alibaba/nacos#7115]
**Describe the bug**
启动nacos和一个springboot测试项目，无法通过curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=example&ip=127.0.0.1&port=8080' 注册服务，报错caused: service not found, namespace: public, service: Service{namespace='public', group='DEFAULT_GROUP', name='spring-cache', ephemeral=true, revision=0}

When I started nacos server and a  demo project (a springboot project ,named spring-cache ) ， I can't regist  the demo service with the openAPI of 
```curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=example&ip=127.0.0.1&port=8080' ```, the response error message is:
caused: service not found, namespace: public, service: Service{namespace='public', group='DEFAULT_GROUP', name='spring-cache', ephemeral=true, revision=0}

**Expected behavior**
希望成功注册一个spring-cache 服务
Hope the registration is successful
**Acutally behavior**
Response with error.
caused: service not found, namespace: public, service: Service{namespace='public', group='DEFAULT_GROUP', name='spring-cache', ephemeral=true, revision=0}

**How to Reproduce**
使用我列出的版本包就能复现
Use the version I list below can reproduce the problem.

**Desktop (please complete the following information):**
 - OS: Manjaro 21.1.6 Pahvo
 - Version nacos-config-spring-boot-starter：0.2.10 ，nacos-discovery-spring-boot-starter：0.2.10，
 nacos-server：2.0.3   
 - Module 
 - SDK  JDK：1.8，spring-boot:   2.3.7.RELEASE

**Additional context**
我的服务是存活的，能访问，不知为何报服务找不到。
My service is alive, but I don't understand why  the response says "service not found"

**Comment by tianyu150** [comment]
坑人啊，在hub.docker上提供的PUT 方法。
https://hub.docker.com/r/nacos/nacos-server
