### ISSUE TITLE
nacos配置中心长连接问题

### ISSUE THREAD

**Issue by diqiutasuo123** [alibaba/nacos#7128]
为什么配置中心启用了gRPC长连接以后不能直接推送配置给客户端，而是采用了客户端使用定时任务的方式拉取配置？

**Comment by SteafanMrZhou** [comment]
长连接是一种很消耗性能的措施，本身使用长连接就增加了性能消耗，如果要在长连接的基础上进行主动推送至客户端，那就需要另启线程处理，会增加额外的性能开销，如果一有配置更新就主动另启线程推送，那这样的性能开销想必是很大的，所以采用了客户端使用定时任务的方式向服务端拉取配置，但是这种情况可能会出现更新的配置信息和拉取的配置信息中间出现延迟。

**Comment by diqiutasuo123** [comment]
但是配置中心服务端确实是通过长连接通知客户端配置更新的（具体可看com.alibaba.nacos.config.server.remote.RpcConfigChangeNotifier），只不过是没有带上配置内容罢了，为什么不利用这个通知将配置内容同时推送下去呢？这样就不需要服务端另启线程推送增加性能消耗，而且客户端也不需要再拉取一遍配置内容了。

**Comment by diqiutasuo123** [comment]
> 长连接是一种很消耗性能的措施，本身使用长连接就增加了性能消耗，如果要在长连接的基础上进行主动推送至客户端，那就需要另启线程处理，会增加额外的性能开销，如果一有配置更新就主动另启线程推送，那这样的性能开销想必是很大的，所以采用了客户端使用定时任务的方式向服务端拉取配置，但是这种情况可能会出现更新的配置信息和拉取的配置信息中间出现延迟。

**Comment by diqiutasuo123** [comment]
> 长连接是一种很消耗性能的措施，本身使用长连接就增加了性能消耗，如果要在长连接的基础上进行主动推送至客户端，那就需要另启线程处理，会增加额外的性能开销，如果一有配置更新就主动另启线程推送，那这样的性能开销想必是很大的，所以采用了客户端使用定时任务的方式向服务端拉取配置，但是这种情况可能会出现更新的配置信息和拉取的配置信息中间出现延迟。

**Comment by diqiutasuo123** [comment]
但是配置中心服务端确实是通过长连接通知客户端配置更新的（具体可看com.alibaba.nacos.config.server.remote.RpcConfigChangeNotifier），只不过是没有带上配置内容罢了，为什么不利用这个通知将配置内容同时推送下去呢？这样服务端不需要另启线程推送增加性能消耗，而且客户端不需要再拉取一遍配置内容了。

**Comment by SteafanMrZhou** [comment]
> 但是配置中心服务端确实是通过长连接通知客户端配置更新的（具体可看com.alibaba.nacos.config.server.remote.RpcConfigChangeNotifier），只不过是没有带上配置内容罢了，为什么不利用这个通知将配置内容同时推送下去呢？这样服务端不需要另启线程推送增加性能消耗，而且客户端不需要再拉取一遍配置内容了。

这个就要看官方咋说了，他说可以加进去，那就能加进去了。
