### ISSUE TITLE
The version 0.8.0 is in the stand-alone startup mode. After the network is replaced, the configuration cannot be obtained.

### ISSUE THREAD

**Issue by dyc87112** [alibaba/nacos#714]
# 报告错误

- 使用版本：0.8.0
- 启动方式：单机模式

RT，在更换不同网络之后，会获取不到Nacos中的配置。

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
