### ISSUE TITLE
请问暴露的Metrics是否可以添加认证

### ISSUE THREAD

**Issue by fashengba** [alibaba/nacos#7148]
你好，Nacos团队，我这有个疑问，默认设置暴露的Nacos Prometheus指标接口 nacos/actuator/prometheus  是否可以设置认证方式，比如Basic Auth 或  OAuth ， 如果可以，请问如何设置？
此问题的背景，主要是利用安全工具漏扫，会认为此接口是非安全认证的，会认为是安全问题。

**Comment by MajorHe1** [comment]
蹲一下这个问题。
我自己的解决方案是在外层包一个filter拦截请求单独处理，没找到使原生nacos的Prometheus开启认证的方法。添加spring-security的配置也不行。

**Comment by realJackSun** [comment]
这个prometheus接口目前确实没有提供安全性认证机制，建议先使用外层的网关进行拦截（一些企业也是这么生产实践的）。等Nacos鉴权插件化完善之后，会提供完善的安全性解决方案。

> 你好，Nacos团队，我这有个疑问，默认设置暴露的Nacos Prometheus指标接口 nacos/actuator/prometheus 是否可以设置认证方式，比如Basic Auth 或 OAuth ， 如果可以，请问如何设置？ 此问题的背景，主要是利用安全工具漏扫，会认为此接口是非安全认证的，会认为是安全问题。

**Comment by fashengba** [comment]
> 这个prometheus接口目前确实没有提供安全性认证机制，建议先使用外层的网关进行拦截（一些企业也是这么生产实践的）。等Nacos鉴权插件化完善之后，会提供完善的安全性解决方案。
> 
> > 你好，Nacos团队，我这有个疑问，默认设置暴露的Nacos Prometheus指标接口 nacos/actuator/prometheus 是否可以设置认证方式，比如Basic Auth 或 OAuth ， 如果可以，请问如何设置？ 此问题的背景，主要是利用安全工具漏扫，会认为此接口是非安全认证的，会认为是安全问题。

您好，请问Nacos团队这块，预计在将来的那个版本，会提供Nacos鉴权插件化安全性解决方案？

**Comment by KomachiSion** [comment]
这块和nacos关系不大，这个接口是spring的actuator接口，我记得spring文档里有actuator如何添加鉴权的文档。有需要的自行添加。
