### ISSUE TITLE
Start error,but can be registered

### ISSUE THREAD

**Issue by fengkuangdefc** [alibaba/nacos#715]
As shown in figure
<img width="1115" alt="_20190128135702" src="https://user-images.githubusercontent.com/30796442/51817127-69009d00-2304-11e9-8145-6d368252d8bf.png">
<img width="1203" alt="_20190128135711" src="https://user-images.githubusercontent.com/30796442/51817131-6bfb8d80-2304-11e9-908e-d9daa4fc85da.png">

**Comment by xiaoyaojc** [comment]
如果你也用nacos做配置中心，那我也遇到过这个问题，通过把spring.cloud.nacos.config.server-addr的地址配置后，问题就解决了。希望能帮到你

**Comment by fengkuangdefc** [comment]
> 用nacos做配置中心，那我也遇到过这个问题，通过把spring.cloud.nacos.config.server-addr的地址配置后，问题就解决了。希望能帮到你

**Comment by fengkuangdefc** [comment]
> 如果你也用NACOS做配置中心，那我也遇到过这个问题，通过把spring.cloud.nacos.config.server-ADDR的地址配置后，问题就解决了。希望能帮到你

这个配置我已经加了

**Comment by xiaoyaojc** [comment]
可以配置成一样的，如果你的配置中心和注册中心的地址是一样的话，spring.cloud.nacos.discovery.server-addr和spring.cloud.nacos.config.server-addr分别对应注册中心和配置中心，不仔细看会以为是同一个
