### ISSUE TITLE
springboot使用nacos配置中心读取配置，对于key相同的配置项，为什么优先使用了本地yml文件的配置，而没有使用nacos配置中心的配置

### ISSUE THREAD

**Issue by dimiduhezi** [alibaba/nacos#7155]
**Describe the bug**
springboot使用nacos配置中心读取配置，对于key相同的配置项，为什么优先使用了本地yml文件的配置，而没有使用nacos配置中心的配置

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1.在nacos配置中心配置一个key相同的配置
2. 在本地配置文件bootstrap.yml中加入相同配置，并在nacos.config.data-ids 中添加远程配置文件的文件名
3. 启动服务，打印key的数据

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [nacos-config-spring-boot-starter：0.2.10，nacos-discovery-spring-boot-starter 0.2.10]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by changhr2013** [comment]
可以看看 Spring Boot 加载到的 PropertySource 顺序，一般 Spring Boot 获取配置只会获取最先能获取到的，可能是 nacos 的 PropertySource 顺序太靠后导致的，通过 ConfigurableEnvironment 的 getPropertySources() 获取到所有加载的 PropertySource，通过迭代器打印出来顺序看看。

**Comment by onewe** [comment]
@dimiduhezi see https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.7-%E4%BB%A5%E5%8F%8A-0.1.7-%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#nacos-config-spring-boot
