### ISSUE TITLE
服务启动中向Nacos注册服务成功，服务最终因为端口冲突启动失败，实例健康状态没有改变

### ISSUE THREAD

**Issue by onlymate918** [alibaba/nacos#7164]
场景：
1、A服务启动8233，服务启动成功并注册成功了
![1635846127(1)](https://user-images.githubusercontent.com/53428286/139823391-b4d062b6-26ef-49b3-9230-606f79a0e808.jpg)
2、启动B服务端口也是8233，这时候会先向nacos注册服务，然后由于端口冲突服务启动失败，调用服务注销接口
![image](https://user-images.githubusercontent.com/53428286/139823493-ebc8e38a-c1c4-4b10-8b55-46bef472a50c.png)
![image](https://user-images.githubusercontent.com/53428286/139823610-9b4452e6-1426-4f04-b1e4-c7da29fd82e1.png)

问题：
在第二步注销服务实例时，没有真正的注销服务实例
![image](https://user-images.githubusercontent.com/53428286/139823864-717c97c2-3d15-4e35-9665-f8d4d79cbf62.png)
在nacos管理页面还是能看到健康的服务实例，导致请求分流到这个服务实例上而报错
![image](https://user-images.githubusercontent.com/53428286/139823960-79f79685-8b03-4bb1-a4a6-4ce4e1973203.png)

**Comment by onewe** [comment]
@onlymate918 
Describe the Spring boot version 、Nacos client version and Nacos server version Please.

**Comment by onlymate918** [comment]
> @onlymate918 Describe the Spring boot version 、Nacos client version and Nacos server version Please.

不好意思，提问题时拷贝漏了环境部分
spring-boot：2.4.2
spring-cloud：2020.0.0
spring-cloud-alibaba：2021.1
Nacos客户端：1.4.2
Nacos服务端：1.4.2

**Comment by onewe** [comment]
@onlymate918 I have tried it, but I didn't trigger this problem. Can you provide more detail?

**Comment by onlymate918** [comment]
@onewe 我使用的是JDK11，是启动A，B两个不同服务，相同服务端口冲突不会复现
![1636016125(1)](https://user-images.githubusercontent.com/53428286/140285958-4be183f8-52a2-407e-b744-84cdb2025d98.jpg)
![1636016290(1)](https://user-images.githubusercontent.com/53428286/140285989-b49559a1-b459-47f4-b71c-0d478cfd244a.png)

**Comment by onewe** [comment]
I'm sorry about that, I have tried it again, but I don't still trigger it. 🤷‍♂️  
![image](https://user-images.githubusercontent.com/38708836/140292207-a377fc5d-7185-4dda-b968-f43048405266.png)
![image](https://user-images.githubusercontent.com/38708836/140292407-5417b8e4-fea8-4e01-a191-d9fd233df449.png)

**Comment by onlymate918** [comment]
@onewe 
我根据你的启动日志做对比，差异点是Tomcat初始化后，没有将服务立即注册到注册中心
![1636019705(1)](https://user-images.githubusercontent.com/53428286/140294055-d4b05fda-a9c9-4fd9-9951-6c37dd3f158d.jpg)
我的服务有这一步操作是因为加了手动注册服务
![image](https://user-images.githubusercontent.com/53428286/140294214-7f0b596c-d07b-4a72-ac20-72393c90072b.png)
公司生产环境是通过Tomcat的方式部署的，Tomcat启动成功后是不会将服务注册到Nacos的，你们提供的解决方案也是以上这种，那么这个问题该如何解决呢？

**Comment by onewe** [comment]
Do you have any code of example? 😂

**Comment by onlymate918** [comment]
@onewe 你可以在你的项目中加上这个配置
`@Configuration
public class NacosLifecycle implements ApplicationContextAware {

    @Autowired(required = false)
    private NacosAutoServiceRegistration registration;

    @Autowired
    private Environment environment;

    @Override
    public void setApplicationContext(ApplicationContext context) throws BeansException {
        if (registration != null) {
            String port = environment.getProperty("server.port");
            registration.setPort(Integer.parseInt(port));
            registration.start();
        }
    }
}`
然后再重现这个场景

**Comment by onlymate918** [comment]
![image](https://user-images.githubusercontent.com/53428286/144337922-e09d9e19-0c75-49de-bbe4-ba553df6b7aa.png)
用Tomcat进行手动注册Nacos，注册实例时服务并没有完全启动成功，如果后续启动爆错了，也一样的存在这个情况，这个问题有没有更进一步的解决方案呢。

**Comment by onewe** [comment]
@onlymate918 我这边是真的没复现出来,能复现出来就好处理了.. 尴尬. 要不你传一个能百分百复现的案例上来,我本地跑一跑,看看能不能复现.

**Comment by onewe** [comment]
@onlymate918 或者我们私聊,我挺好奇这个问题的.

**Comment by onlymate918** [comment]
我这周弄一个案例出来

**Comment by kevinYuan2017** [comment]
最近我也在琢磨nacos的使用, ***@***.*** ***@***.***>提供的信息, 的确可以复现所述的问题


我认为, 能够出现启动失败但是依然有注册和取消注册这些动作的原因就是自定义的这个ApplicationContextAware接口实现引起的, 这里自定义的注册动作, 是初始化context时直接掉用registration.start(), 这与遵守springcloud-common标准的nacos-discovery包是不一致的, 同样是通过初始化context的过程中启动注册, springcloud-common里可以看到, 是通过监听webserver初始化这个event来启动注册的



并且, 注册前后, 还发布了2个事件, 方便开发者扩展
这就是为什么那样的配置类会引起端口冲突的程序启动失败还会有注册动作, 而普通的写法(就是最简单的引入一个starter然后啥也不管那种)反而不会出现这种奇怪问题
我是这么看的

**Comment by onewe** [comment]
@kevinYuan2017 你是直接放在tomcat里面跑然后复现的? 还是用 java -jar 的方式复现的? 难道是我的姿势不对?

**Comment by onlymate918** [comment]
@onewe  通过这段时间的使用中暴露的问题，主要原因是你们推荐使用外置tomcat启动项目增加以下配置造成的
`
@Configuration
public class NacosLifecycle implements ApplicationContextAware {

    @Autowired(required = false)
    private NacosAutoServiceRegistration registration;

    @Autowired
    private Environment environment;

    @Override
    public void setApplicationContext(ApplicationContext context) throws BeansException {
        if (registration != null) {
            System.out.println("*************************手动注册服务*************************");
            String port = environment.getProperty("server.port");
            registration.setPort(Integer.parseInt(port));
            registration.start();
            registration.stop();
        }
    }
}
`
这样会导致服务没有真正启动成功就注册服务，我自己实践发现使用这种方式手动注册更加合理，这种方式会在容器完全启动成功后，才会注册服务。
`
@Component
public class ApplicationReadyEventListener implements ApplicationListener<ApplicationReadyEvent> {
    private static Logger logger = LoggerFactory.getLogger(ApplicationReadyEventListener.class);

    @Autowired
    private NacosAutoServiceRegistration registration;
    @Autowired
    private Environment environment;

    @Override
    public void onApplicationEvent(ApplicationReadyEvent event) {
        System.out.println("*************************手动注册服务*************************");

        String port = environment.getProperty("server.port");
        registration.setPort(Integer.parseInt(port));
        registration.start();
        registration.stop();
    }
}
`

同时，附上一个可以复现问题的demo，这个是
@Value("${cust.name}")
private String custName;
没有赋值导致启动报错，但是通过ApplicationContextAware依旧成功注册服务的场景（这样导致注册服务成功，启动失败的场景还有很多）
https://igetit.oss-cn-shenzhen.aliyuncs.com/demo.war

**Comment by onlymate918** [comment]
以上的demo直接放在tomcat中运行

**Comment by onewe** [comment]
我后面空了复现一下,最近有点忙,抱歉了.
