### ISSUE TITLE
我好奇源码缺少一个包，命令行build竟然直接过了

### ISSUE THREAD

**Issue by ZzuMrW** [alibaba/nacos#7166]
![image](https://user-images.githubusercontent.com/12119047/139865544-f80fbd8e-bb4f-4851-98b5-64a8d81e2396.png)

**Comment by onewe** [comment]
@ZzuMrW That entities will have been created in Java compile period

**Comment by brotherlu-xcq** [comment]
duplicate with https://github.com/alibaba/nacos/issues/7124
