### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by linxiangqian** [alibaba/nacos#7175]
**Describe the bug**
I got an error when I started nacos：

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/x6/mmnfn23n6vx3dxgwnwdx0h6r0000gn/T/librocksdbjni3928116129825104226.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/x6/mmnfn23n6vx3dxgwnwdx0h6r0000gn/T/librocksdbjni3928116129825104226.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Expected behavior**
Normal startup

**Acutally behavior**
Startup error

**How to Reproduce**
1. bin/startup.sh  -m standalone
2. tail -f  /Users/linxiangxian/soft/nacos/nacos-2.0.3/logs/start.out

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15
 - Version nacos-server 2.0.3

**Additional context**

**Comment by ljt7560868** [comment]
怎么解决的？升级mac os版本？

**Comment by woshiqiuxiaoyan** [comment]
> 怎么解决的？升级mac os版本？

为了启个 nacos 还要升级 mac 版本吗
