### ISSUE TITLE
免登陆

### ISSUE THREAD

**Issue by wanghwtaiji** [alibaba/nacos#7180]
我看配置中 在1.2.0的时候可以通过配置，实现免登陆，那现在在2.0.0的时候 该如何实现呢？

**Comment by wanghwtaiji** [comment]
### If enable spring security, this option is deprecated in 1.2.0:
# spring.security.enabled=false
### The ignore urls of auth, is deprecated in 1.2.0:
nacos.security.ignore.urls=/**
# nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

**Comment by Liubey** [comment]
use nacos.core.auth.enabled=false to nologin
