### ISSUE TITLE
mac 2020 m1处理器 执行quick-startup.sh后报错

### ISSUE THREAD

**Issue by realray** [alibaba/nacos#7187]
**Describe the bug**
mac book 2020  m1 , execute quick-startup.sh from official, but failed.

**Expected behavior**
mysql service and the nacos service can run successfully.
**Acutally behavior**
mysql service  cant not run successfully.always in status CrashLoopBackOff,and nacos service always in status pending.

**How to Reproduce**
1. quick-startup.sh  form official.

**Desktop (please complete the following information):**
 - OS: macos big sur
 - SDK k8s-nacos

**Additional context**
logs:
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc
runtime stack:
runtime.throw(0x524da0, 0x9)
/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82002c000, 0xc82003bfc0)
/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x555ce8, 0x0)
/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
/usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5c4300)
/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
/usr/local/go/src/runtime/proc1.go:674
goroutine 1 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820026770 sp=0xc820026768
runtime.main()
/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200267c0 sp=0xc820026770
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200267c8 sp=0xc8200267c0

**Comment by realJackSun** [comment]
duplicate with https://github.com/alibaba/nacos/issues/7152
