### ISSUE TITLE
client module getConfig() method response null result

### ISSUE THREAD

**Issue by hy0619** [alibaba/nacos#7192]
### when I used client module  getConfig() method to get config value in nacos  , the nacos console show the value of the same dataId and groupid but when i used api  it return null 

![image](https://user-images.githubusercontent.com/20480464/140636677-e2b7d8c2-3bfd-4d16-8a13-48a94c2b25c3.png)
![image](https://user-images.githubusercontent.com/20480464/140636701-0ceac7a8-3064-4504-b7e7-8a69a5dc6dfe.png)

### environment

win10  + nacos 2.1.0-SNAPSHOT  + server standalone

**Comment by zxcvbnm3057** [comment]
我这边2.0.3docker版也出了一样的问题，不知道为啥
