### ISSUE TITLE
nacos create  Too many threads and cpu very high

### ISSUE THREAD

**Issue by tanranv5** [alibaba/nacos#7194]
**Describe the bug**
nacos create  Too many threads and cpu very high

**Expected behavior**
nacos normal

**Acutally behavior**

nacos create  Too many  "com.alibaba.nacos.client.config.security.updater" threads

![image](https://user-images.githubusercontent.com/51186467/140702283-d55c51e2-eb81-49ff-9518-8a8d7e3466cc.png)

![image](https://user-images.githubusercontent.com/51186467/140702589-d28a6cb7-b4bb-40de-a57e-9aa8baaf8b50.png)

The thread pool should be set to a maximum value

**Desktop (please complete the following information):**
 - OS: centos
 - Version nacos-client 1.3.2
 - SDK spring-cloud-alibaba-nacos

**Comment by tanranv5** [comment]
感谢你的解答，请问namespace 会有什么问题呢？ 开发环境测试不出来，定位不到问题，但生产环境一直线程过多，翻开源码，发现这个无限大的线程池。请问这个线程池是做什么的？什么样的故障会出发这个操作。

**Comment by realJackSun** [comment]
这个线程池貌似在新版本中被删除掉了？是做鉴权的。

**Comment by tanranv5** [comment]
> 这个线程池貌似在新版本中被删除掉了？是做鉴权的。

nacos-client 2版本都去除了这个线程池 ，那我想请教下，nacos服务端版本是1.3.2，nacos-client 可以用2.0.3版本吗？ 会出现什么不兼容的情况？

**Comment by tanranv5** [comment]
> > 这个线程池貌似在新版本中被删除掉了？是做鉴权的。
> 
> nacos-client 2版本都去除了这个线程池 ，那我想请教下，nacos服务端版本是1.3.2，nacos-client 可以用2.0.3版本吗？ 会出现什么不兼容的情况？

 刚看文档说nacos-client2.0 不兼容nacos的服务端，那么除了升级，能不能提高一种 解决方案吗，或者找出对应的问题？
