### ISSUE TITLE
Nacos2.0.3 集群中一个节点的状态一直处于CANDIDATE状态

### ISSUE THREAD

**Issue by chenhao26-nineteen** [alibaba/nacos#7196]
![image](https://user-images.githubusercontent.com/35129699/140710146-ea66d3c4-2052-4a29-b121-2196c9fa9366.png)

**Comment by lpaz010** [comment]
给的信息太少了吧，就一张截图-。-！

**Comment by Chaos-coder** [comment]
集群从1.4升级到2.0.3的过程中。集群一共有5个节点，一个LEADER，三个FOLLOWER，一个CANDIDATE。理论上有了LEADER，然后CANDIDATE会变成FOLLOWER？CANDIDATE状态已经持续两周。
