### ISSUE TITLE
nacos集群配置节点中存在虚拟IP，虚拟路由，引发的血案

### ISSUE THREAD

**Issue by shy-stone** [alibaba/nacos#7204]
Hello，BOSS，my nacos clusters(4 nodes) have a  problem
**How to Reproduce**
my NACOS cluster configuration with the following configuration:
![image](https://user-images.githubusercontent.com/46125480/140887468-08082bfa-3f95-4d53-ab80-f74828dfc0f1.png)
#2021-11-09T15:19:47.871
10.30.25.26:21980
10.30.25.35:21980
10.30.25.41:21980
10.30.25.42:21980
When I started with a cluster like this, I had no problems. When I configured the virtual IP and virtual routing,then reboot nacos, which got a problem. The virtual routing IP became a node, which caused my cluster configuration to change from 4 to 5, but this was not the most important things, my cluster failed!The connection between clusters report errors
![image](https://user-images.githubusercontent.com/46125480/140888480-9e064b95-2a07-4eb5-afcc-a88ebf48b88f.png)

**Desktop (please complete the following information):**
 - OS: centos7.5
 - Version nacos-server 1.4.0,
 - Module 
![image](https://user-images.githubusercontent.com/46125480/140888910-d6b95842-2447-4b93-b0df-abc113ed98ff.png)
java version "1.8.0_131"

**Comment by realJackSun** [comment]
用文件寻址方式确实存在这种问题，兄弟或许可以尝试一下地址服务器寻址？

**Comment by chuntaojun** [comment]
> 用文件寻址方式确实存在这种问题，兄弟或许可以尝试一下地址服务器寻址？

他这种情况必须要制定下nacos-server的ip是什么，才不会有问题，这是默认寻找自己ip的问题
