### ISSUE TITLE
配置sentinel持久化报错403

### ISSUE THREAD

**Issue by resetmylife** [alibaba/nacos#7213]
报错如下：
[ERROR] [fixed-localhost_8848] [check-update] get changed dataId error, code: 403

bootstrap.yml 配置如下

spring:
    profiles:
        active: local
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
            config:
                namespace: a1a6bc48-1b44-4b0b-930f-328e34d8b50d
                file-extension: yml
                shared-dataids: common.yml,redis.yml,log.yml,mq.yml

        sentinel:
            filter:
                enabled: false
            transport:
                port: 8081
                dashboard: 172.30.103.68:8080
            #限流
            datasource:
                ds1:
                    nacos:
                        server-addr: localhost:8848
                        username: nacos
                        password: nacos
                        dataId: middle-sentinel-local
                        groupId: SENTINEL_GROUP
                        refresh: true
                        data-type: json
                        rule-type: flow

**Comment by KomachiSion** [comment]
This should be sentinal verison problem, old sentinal not support config username and password
