### ISSUE TITLE
nacos2.0.3集群中节点shutdown后再次启动， readyToUpgrade 字段丢失

### ISSUE THREAD

**Issue by anryHan** [alibaba/nacos#7224]
**nacos2.0.3集群中节点shutdown后再次启动， readyToUpgrade 字段丢失**

集群信息如下图：
[
![屏幕快照 2021-11-11 下午6 46 15](https://user-images.githubusercontent.com/13831076/141285831-0dc13d60-ff77-4452-8558-c17849fbaebe.png)
](url)

shutdown 集群节点【10.3.17.175:8868】之后，再次启动此节点，节点元信息里边readyToUpgrade 没有了，这个是怎么回事？
节点元信息如下图：
[
![屏幕快照 2021-11-11 下午6 55 11](https://user-images.githubusercontent.com/13831076/141287073-bde76e36-3065-4c9f-8534-6c4d62bafc31.png)
](url)

[
![屏幕快照 2021-11-11 下午6 57 17](https://user-images.githubusercontent.com/13831076/141287306-756092be-8fbe-4f05-9877-d9584f449c32.png)
](url)

**Comment by SteafanMrZhou** [comment]
@anryHan 跟踪源码发现，shutdown 节点之后，首先进行参数处理的 MemberUtil.multiParse(params) 方法内部，又调用了 singleParse 方法，最终在 singleParse 方法内部，并没有同步更新 readyToUpgrade 属性：
![image](https://user-images.githubusercontent.com/23360739/143842403-44f3400e-9b07-4f0a-bd56-71175f3193a5.png)
图中红框圈起来的注释部分是我改动的代码，该方法的最后部分，节点 shutdown 之后，只写回了默认的 Nacos 端口，并没有同步更新 readyToUpgrade 属性，放开代码注释部分，readyToUpgrade 字段正常显示。

**Comment by li-xiao-shuang** [comment]
你可以提交一个pr 让 @realJackSun  帮你review 下

**Comment by chuntaojun** [comment]
感觉，是不是把自己的元数据持久化到cluster.conf比较好？

**Comment by SteafanMrZhou** [comment]
@chuntaojun 貌似不可以，这个是对 Nacos 中的服务节点之元数据进行操作，如果持久化到 cluster.conf ，当发生服务节点切换时，会频繁更新 cluster.conf 文件，增加 Nacos 的 IO 压力，这种更新操作应该比只更新一个对象元数据的引用开销要低很多。

**Comment by SteafanMrZhou** [comment]
@realJackSun 针对本 issue 的修改，已经提交了 PR ，希望您能看下，谢谢

**Comment by SteafanMrZhou** [comment]
提交了 PR 没人管了吗，有没有结果说句话啊？？

**Comment by wangwei-ying** [comment]
这里可以直接设置true吗？ 要全部ready才能设置为true，如果之前是false的话，会不会走到这里来

**Comment by SteafanMrZhou** [comment]
> 这里可以直接设置true吗？ 要全部ready才能设置为true，如果之前是false的话，会不会走到这里来

单节点模式下可以直接设置，集群模式下需要同步修改，无论是单节点模式还是集群模式，源码中都遗漏了对于 readyToUpgrade 字段逻辑的更新。

**Comment by wangwei-ying** [comment]
> > 这里可以直接设置true吗？ 要全部ready才能设置为true，如果之前是false的话，会不会走到这里来
> 
> 单节点模式下可以直接设置，集群模式下需要同步修改，无论是单节点模式还是集群模式，源码中都遗漏了对于 readyToUpgrade 字段逻辑的更新。
```
 private boolean checkForUpgrade() {
        if (!useGrpcFeatures.get()) {
            boolean selfCheckResult = selfUpgradeChecker.isReadyToUpgrade(serviceManager, doubleWriteDelayTaskEngine);
            Member self = memberManager.getSelf();
            self.setExtendVal(MemberMetaDataConstants.READY_TO_UPGRADE, selfCheckResult);
            memberManager.updateMember(self);
            if (!selfCheckResult) {
                NamingExecuteTaskDispatcher.getInstance().dispatchAndExecuteTask(AsyncServicesCheckTask.class,
                        new AsyncServicesCheckTask(doubleWriteDelayTaskEngine, this));
            }
        }
        boolean result = true;
        for (Member each : memberManager.allMembers()) {
            Object isReadyToUpgrade = each.getExtendVal(MemberMetaDataConstants.READY_TO_UPGRADE);
            result &= null != isReadyToUpgrade && (boolean) isReadyToUpgrade;
        }
        return result;
    }
```
这个字段在checkForUpgrade里检查状态后设置，但是useGrpcFeatures==true的时候，是不会设置这个值。

**Comment by SteafanMrZhou** [comment]
> > > 这里可以直接设置true吗？ 要全部ready才能设置为true，如果之前是false的话，会不会走到这里来
> > 
> > 
> > 单节点模式下可以直接设置，集群模式下需要同步修改，无论是单节点模式还是集群模式，源码中都遗漏了对于 readyToUpgrade 字段逻辑的更新。
> 
> ```
>  private boolean checkForUpgrade() {
>         if (!useGrpcFeatures.get()) {
>             boolean selfCheckResult = selfUpgradeChecker.isReadyToUpgrade(serviceManager, doubleWriteDelayTaskEngine);
>             Member self = memberManager.getSelf();
>             self.setExtendVal(MemberMetaDataConstants.READY_TO_UPGRADE, selfCheckResult);
>             memberManager.updateMember(self);
>             if (!selfCheckResult) {
>                 NamingExecuteTaskDispatcher.getInstance().dispatchAndExecuteTask(AsyncServicesCheckTask.class,
>                         new AsyncServicesCheckTask(doubleWriteDelayTaskEngine, this));
>             }
>         }
>         boolean result = true;
>         for (Member each : memberManager.allMembers()) {
>             Object isReadyToUpgrade = each.getExtendVal(MemberMetaDataConstants.READY_TO_UPGRADE);
>             result &= null != isReadyToUpgrade && (boolean) isReadyToUpgrade;
>         }
>         return result;
>     }
> ```
> 
> 这个字段在checkForUpgrade里检查状态后设置，但是useGrpcFeatures==true的时候，是不会设置这个值。

所以我说源码中都遗漏了对于 readyToUpgrade 字段逻辑的更新。
还有就是这部分的逻辑，我跟官方沟通了下，这部分逻辑可能后期需要变更，具体的看官方怎么说吧。

**Comment by realJackSun** [comment]
> @realJackSun 针对本 issue 的修改，已经提交了 PR ，希望您能看下，谢谢

收到，感谢贡献。我们审核一下。
