### ISSUE TITLE
nacos 2.0.3 整合 sofaboot3.9.0后，服务注册不到nacos中，请问什么原因？

### ISSUE THREAD

**Issue by 550372746** [alibaba/nacos#7227]
After integrating sofaboot3.9.0 with Nacos 2.0.3, the service cannot be registered in Nacos. What is the reason?

**Comment by MajorHe1** [comment]
这样给出来的信息太少了，没办法判断。
建议详细描述一下，nacos sever 端是否正确搭建，跑一些简单的nacos client demo看是否注册成功，
配置文件是否正确指定，服务注册的方法是否被调用，有无异常日志等等。

**Comment by 550372746** [comment]
nacos2.0.3正常搭建运行，试过spring-cloud-starter-alibaba-nacos-discovery  这是可以正常注册服务的。但是试过sofaboot3.9.0注册不进去，如果把nacos版本改成0.6.0就可以注册进去。

**Comment by MajorHe1** [comment]
那这就是sofaboot的问题了， 不是nacos的问题。由于我不熟悉sofaboot，无法给你更多的解答。
服务注册一定调用的 nacos client 源码 naming 模块的 NacosNamingService.registerInstance方法，你可以跟踪一下看看在哪里调用的，为什么没调用。

**Comment by 550372746** [comment]
谢谢，调试出来了，引用sofaboot最新版本3.9.0，nacos2.0.3。需要自定义命名空间，不同的一点是配置信息com.alipay.sofa.rpc.registry-address= nacos://127.0.0.1:8848的后面要加自定义命名空间ID, 例如完整的写法com.alipay.sofa.rpc.registry-address= nacos://127.0.0.1:8848/c9ca30c6-ff04-4fae-96f0-fbe6227bd4a3，我这边是这么解决的，已经成功注册服务了。

**Comment by MajorHe1** [comment]
> 谢谢，调试出来了，引用sofaboot最新版本3.9.0，nacos2.0.3。需要自定义命名空间，不同的一点是配置信息com.alipay.sofa.rpc.registry-address= nacos://127.0.0.1:8848的后面要加自定义命名空间ID, 例如完整的写法com.alipay.sofa.rpc.registry-address= nacos://127.0.0.1:8848/c9ca30c6-ff04-4fae-96f0-fbe6227bd4a3，我这边是这么解决的，已经成功注册服务了。

Good  : )

**Comment by 541538356** [comment]
nacos 2.0.3 com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: RPC-010060009: 订阅 provider 到 [NacosRegistry] 失败! 
nacos 升级后发现服务失败

**Comment by 550372746** [comment]
https://github.com/sofastack/sofa-boot/issues/884




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos 2.0.3 整合 sofaboot3.9.0后，服务注册不到nacos中，请问什么原因？ (Issue #7227)





 
nacos 2.0.3 com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: RPC-010060009: 订阅 provider 到 [NacosRegistry] 失败!
 nacos 升级后发现服务失败
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 541538356** [comment]
提供者能注册，消费者无法发现注册到nocos中的服务，nacos版本3.0.2，sofaboot版本3.4.8

**Comment by 550372746** [comment]
升级到sofaboot3.9.1试试，测试sofaboot3.9.1和nacos2.0.3可以注册和消费服务，我这边项目目前使用这对应版本。sofaboot版本3.4.8没去调试过


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos 2.0.3 整合 sofaboot3.9.0后，服务注册不到nacos中，请问什么原因？ (Issue #7227)





 
提供者能注册，消费者无法发现注册到nocos中的服务，nacos版本3.0.2，sofaboot版本3.4.8
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuanjinzhong** [comment]
> 升级到sofaboot3.9.1试试，测试sofaboot3.9.1和nacos2.0.3可以注册和消费服务，我这边项目目前使用这对应版本。sofaboot版本3.4.8没去调试过
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/nacos" ***@***.***&gt;; 发送时间:&nbsp;2021年12月15日(星期三) 下午5:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/nacos] nacos 2.0.3 整合 sofaboot3.9.0后，服务注册不到nacos中，请问什么原因？ (Issue #7227) 提供者能注册，消费者无法发现注册到nocos中的服务，nacos版本3.0.2，sofaboot版本3.4.8 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你好,请问nacos-client的版本是多少
