### ISSUE TITLE
update config in nacos backend caused spring applicationContext closed.(AnnotationConfigApplicationContext@3e38a596 has been closed already)

### ISSUE THREAD

**Issue by torna-group** [alibaba/nacos#7228]
**Describe the bug**
我在nacos后台修改了一个配置，但是程序缺关闭了Spring容器（执行了org.springframework.context.support.AbstractApplicationContext#doClose方法）

然后我在其它地方使用applicationContext对象时，报了一个异常`AnnotationConfigApplicationContext@3e38a596 has been closed already`

```
public class SpringContextUtil {

    private static volatile ApplicationContext applicationContext;

    public static void setApplicationContext(ApplicationContext ctx) {
        applicationContext = ctx;
    }

    public static ApplicationContext getApplicationContext() {
        return applicationContext;
    }

    public static <T> T getBean(Class<T> clazz) {
        return getApplicationContext().getBean(clazz);
    }

    public static Object getBean(String beanName) {
        return getApplicationContext().getBean(beanName);
    }
}
```

```
@Component
public class XXXX implements  ApplicationContextAware {

    @Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        SpringContextUtil.setApplicationContext(applicationContext);
    }
}
```

启动时正确设置了applicationContext，可以正常使用。

在nacos上修改了配置，然后触发容器关闭，再次使用SpringContextUtil 类获取容器就会报异常（AnnotationConfigApplicationContext@3e38a596 has been closed already）

**Desktop (please complete the following information):**
 - OS: [e.g. Centos7]
 - Version [e.g. nacos-server 1.4.2, nacos-client 1.4.2]

**Comment by torna-group** [comment]
![bug](https://user-images.githubusercontent.com/7940438/141461888-2e2f9a8d-b167-4282-9b1e-d72ddff6f48a.png)
这个是断点图

**Comment by onewe** [comment]
你是说 ApplicationContextAware 没有触发刷新? 没有获取到新的上下文?

**Comment by onewe** [comment]
触发 close 这个是执行刷新 这是正常的. 我这边没有复现你所说的问题.而且这个不是 nacos 的问题.

**Comment by onewe** [comment]
@torna-group

**Comment by torna-group** [comment]
> 你是说 ApplicationContextAware 没有触发刷新? 没有获取到新的上下文?

触发刷新了，我用下面这种方式重新设置一遍上下文：

```
public interface ContextRefreshListener extends ApplicationListener<EnvironmentChangeEvent> {

    @Override
    default void onApplicationEvent(EnvironmentChangeEvent event) {
        Object source = event.getSource();
        if (source instanceof ApplicationContext) {
            SpringContextUtil.setApplicationContext((ApplicationContext) source);
        }
    }

}
```

然后新建一个配置类，实现ContextRefreshListener接口。

不知道还有没有其它方式。
