### ISSUE TITLE
配置中心权限管理到group

### ISSUE THREAD

**Issue by samirliu** [alibaba/nacos#7234]
nacos作为配置中心的权限管理目前是到namespace级别的，但是粒度比较粗，能否到group级别？

**Comment by CherishCai** [comment]
> nacos作为配置中心的权限管理目前是到namespace级别的，但是粒度比较粗，能否到group级别？

自定义页面，把那个资源框搞成 input 的，编写正则权限就好。

**Comment by samirliu** [comment]
> > nacos作为配置中心的权限管理目前是到namespace级别的，但是粒度比较粗，能否到group级别？
> 
> 自定义页面，把那个资源框搞成 input 的，编写正则权限就好。

感谢反馈，您的意思是nacos server端接口层面是可以支持到group级别了？我尝试修改permissions表的resource内容，但是并不起作用。

**Comment by MajorHe1** [comment]
> 感谢反馈，您的意思是nacos server端接口层面是可以支持到group级别了？我尝试修改permissions表的resource内容，但是并不起作用。

我理解nacos server底层接口并不支持group级别，对resource的判断源码在这里，你可以进去调试一下，我觉得不修改源码的情况下是无法支持group级别的
![image](https://user-images.githubusercontent.com/53824889/141984808-6127130c-81b1-4a66-9153-53d645240e6e.png)

**Comment by samirliu** [comment]
> > 感谢反馈，您的意思是nacos server端接口层面是可以支持到group级别了？我尝试修改permissions表的resource内容，但是并不起作用。
> 
> 我理解nacos server底层接口并不支持group级别，对resource的判断源码在这里，你可以进去调试一下，我觉得不修改源码的情况下是无法支持group级别的 ![image](https://user-images.githubusercontent.com/53824889/141984808-6127130c-81b1-4a66-9153-53d645240e6e.png)

感谢反馈。我看了底层源码，接口层的权限控制是基于注解的，可以实现简单的group级别，但是console端的体验不是特别好，需要改造。
