### ISSUE TITLE
nacos in k8s升级1.4.1报错

### ISSUE THREAD

**Issue by jccc187** [alibaba/nacos#7235]
nacos in k8s从1.4.0升级到1.4.1，出现Caused by: java.io.IOException: User limit of inotify instances reached or too many open files，导致Pod一直重启
![2021-11-15 17-00-22 的屏幕截图](https://user-images.githubusercontent.com/26475682/141752442-6c823f02-ef19-42b8-84f5-f9f32a1689d7.png)

**Comment by jccc187** [comment]
![2021-11-15 17-16-05 的屏幕截图](https://user-images.githubusercontent.com/26475682/141754806-7cc12c8c-3f49-463c-a437-f024e212b390.png)

**Comment by XiaoWeiKIN** [comment]
同样的问题 ，mark 下

**Comment by zhuzhiyang** [comment]
同样的问题，咋解决的， 一直重启

**Comment by KomachiSion** [comment]
This is not nacos' problem, it env problem, nacos can't get the `cluster.conf` context in this env.
