### ISSUE TITLE
OpenAPI: using consistent naming for namespace id

### ISSUE THREAD

**Issue by yaojingguo** [alibaba/nacos#7238]
[Nacos Open API](https://nacos.io/en-us/docs/open-api.html) has the section for namespace API. Several different names are used to mean namespace ID:

- In HTTP response, `namespace`
- In Create namespace, `customNamespaceId`
- In Modify namespace API and Delete namespace, `namespaceId`

I suggest to use `namespaceId` consistently in all these places.

**Comment by KomachiSion** [comment]
The old `v1` api can't change, otherwise will cause old client can't work.

We can re-design the `v2` open API according REST like #6983.

**Comment by yaojingguo** [comment]
I see.
