### ISSUE TITLE
macos 10.13.5 不能正常启动

### ISSUE THREAD

**Issue by qinglong001** [alibaba/nacos#7240]
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java -Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre/lib/ext:/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/lib/ext  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xloggc:/Users/fcj/Downloads/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/fcj/Downloads/nacos/plugins/health,/Users/fcj/Downloads/nacos/plugins/cmdb -Dnacos.home=/Users/fcj/Downloads/nacos -jar /Users/fcj/Downloads/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/Users/fcj/Downloads/nacos/conf/ --logging.config=/Users/fcj/Downloads/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 2.0.3
,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 14974
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://192.168.1.2:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

2021-11-16 15:59:53,056 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@2392212b' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2021-11-16 15:59:53,062 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2021-11-16 15:59:53,454 INFO Tomcat initialized with port(s): 8848 (http)

2021-11-16 15:59:53,933 INFO Root WebApplicationContext: initialization completed in 4667 ms

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/hj/m_ptmzjx15l4plszftvxrw540000gn/T/librocksdbjni8101576448949180174.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/hj/m_ptmzjx15l4plszftvxrw540000gn/T/librocksdbjni8101576448949180174.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by onewe** [comment]
m1 ?

**Comment by darcydai** [comment]
> m1 ?
应该是m1  我的新mac 也是一样的报错

**Comment by onewe** [comment]
m1 有兼容性问题, 羡慕你们这些有钱人买 m1 的, 如果我有 m1 我就能解决这个问题了.😮‍💨

**Comment by tiantsl** [comment]
这个不是M1，和我的一样，我的系统版本是10.13.6，老版本的Mac系统也启动不了nacos2的版本，目前我使用的是nacos1.4.1版本可以正常使用，新版本不行，启动会报类似上面截图里的错

**Comment by KomachiSion** [comment]
duplicate with #4336
