### ISSUE TITLE
nacos挂掉后重启服务无法自动注册

### ISSUE THREAD

**Issue by luolei100** [alibaba/nacos#7245]
背景：
k8s环境下，nacos服务挂掉后重启
现象：
服务无法自动注册。
线程堆栈信息   只找到了两个在运行的线程  其他的都是WAITING状态
"com.alibaba.nacos.client.Worker.longPolling.fixed-test-nacos_8848-1d07012a-37bb-4646-b827-6d5bdfd06d5f" #74 daemon prio=5 os_prio=0 tid=0x0000558aebd91800 nid=0x4e runnable [0x00007fcff1a36000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)

"com.alibaba.nacos.naming.push.receiver" #51 daemon prio=5 os_prio=0 tid=0x0000558aeb837000 nid=0x39 runnable [0x00007fcff3b30000]
   java.lang.Thread.State: RUNNABLE
        at java.net.PlainDatagramSocketImpl.receive0(Native Method)
        - locked <0x00000000de2f3cd0> (a java.net.PlainDatagramSocketImpl)

报错信息
java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:181)

问题：
我应该如何继续往下找到问题原因？

**Comment by luolei100** [comment]
版本是 服务端：1.2.1 客户端：1.4.1

**Comment by onewe** [comment]
@luolei100 升级客户端 1.4.2

**Comment by WindyGao** [comment]
1.4.2客户端，2.0.1服务端 也会出现这个报错
`java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:181)`

**Comment by WindyGao** [comment]
偶发的，不定时的报错

**Comment by baymax55** [comment]
> 1.4.2客户端，2.0.1服务端 也会出现这个报错 `java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:181)`

我也遇到了这个错误
