### ISSUE TITLE
Will the nacos registry be how to do multi-environment deployment?

### ISSUE THREAD

**Issue by zlt2000** [alibaba/nacos#725]
请问nacos注册中心是要怎样做多环境部署的，因为nacos的server-addr和命名空间 必需配置在bootstrap 里面，不能通过profiles 等手段在运行的时候设定不同的配置参数，这个在自动化部署的场景下，怎样动态控制不同环境不同命名空间的？

**Comment by stalary** [comment]
希望能有个多环境切换的说明，目前我正在尝试通过namespace来做环境切换

**Comment by OneMoreMile** [comment]
@stalary  通过namespace切换profile的问题有思路木有，希望可以分享下，同样遇到此问题

**Comment by stalary** [comment]
@OneMoreMile https://www.jianshu.com/p/5c84a1d3b2f9，我的博客中说了一下方法

**Comment by mylove13289** [comment]
最好的办法是将namespace 的id改成与profile相同，就可以了。
但这种方法只能通过订正数据才可以。

**Comment by mylove13289** [comment]
nacos:
      config:
        file-extension: yaml
        server-addr: 192.168.144.202:80
        namespace: ${spring.profiles.active}

**Comment by chuntaojun** [comment]
bootstrap 也可以使用profile的，这个问题仅仅是你怎么去使用spring实现变量在不同的profile下有不同的值，非nacos本身问题，这里先行关闭

**Comment by chuntaojun** [comment]
https://blog.csdn.net/u011936655/article/details/86175439
