### ISSUE TITLE
nacos DNS问题

### ISSUE THREAD

**Issue by jettjia** [alibaba/nacos#7250]
nacos 是否会支持dns这种功能，比如 consul直接暴露个端口，这样kong等可以快速配置转发
官方的 https://github.com/nacos-group/nacos-coredns-plugin
这个项目，基本上没有维护，甚至都无法编译。里面提的bug都无人跟进。

**Comment by MajorHe1** [comment]
duplicate with #6868 
只能说将来，将来要多久，就看大家的贡献了  ：）
