### ISSUE TITLE
手动监听getConfigAndSignListener 方法不停的打印info日志，即使配置中心没修改，也会把本地文件一次一次的修改

### ISSUE THREAD

**Issue by liujiling1** [alibaba/nacos#7254]
ConfigService cs = nacosConfigManager.getConfigService();
        String content = cs.getConfigAndSignListener(DATA_ID, GROUP, 5000, new Listener() {
            @lombok.SneakyThrows
            @Override
            public void receiveConfigInfo(String content) {
                
            }

            @Override
            public Executor getExecutor() {
                return null;
            }
        });

![image](https://user-images.githubusercontent.com/42994141/142382586-006d7c40-2dbd-4012-bfed-460061761b7f.png)

**Comment by onewe** [comment]
@liujiling1 Can you provide more details? such as clien version information etc.
