### ISSUE TITLE
org.springframework.web.client.unknowncontenttypeexception: could not extract response: no suitable httpmessageconverter found for response type [class com.oceanum.authorization.utils.permissionhttpresult] and content type [text/json;charset=utf-8]

### ISSUE THREAD

**Issue by wangxiaofan777** [alibaba/nacos#7260]
org.springframework.web.client.unknowncontenttypeexception: could not extract response: no suitable httpmessageconverter found for response type [class com.oceanum.authorization.utils.permissionhttpresult] and content type [text/json;charset=utf-8]

**Comment by wangxiaofan777** [comment]
本地没有问题，上线就报这个异常

**Comment by onewe** [comment]
@wangxiaofan777 这个和nacos有关系吗?
