### ISSUE TITLE
版本2.0.3集群问题，下线后，面板不再显示

### ISSUE THREAD

**Issue by schooljenry** [alibaba/nacos#7269]
我的版本是2.0.3集群了2台主机，其中一台A按了下线后，A服务器把线程关了,然后再重启A服务器，面板上没有显示有两台主机。但是当我把B服务器的线程关了后，面板就出现了两台主机，而且显示A在线，B下线。然后我再把B启动，面板又恢复正常了，两台主机显示都在线。

**Comment by 1735802356** [comment]
面板下线，服务不关，页面上还是会显示下线机器，这个问题感觉无解
