### ISSUE TITLE
nacos client 在2.x以上版本时, 通过Actuator执行相关方法报403

### ISSUE THREAD

**Issue by sucaiji** [alibaba/nacos#7276]
以NacosServiceRegistry.setStatus为例
经过debug, 在执行reqApi方法时,走到获取token这一阶段时
```
protected Map<String, String> getSecurityHeaders() {
        Map<String, String> result = new HashMap<>(1);
        if (StringUtils.isNotBlank(securityProxy.getAccessToken())) {
            result.put(Constants.ACCESS_TOKEN, securityProxy.getAccessToken());
        }
        return result;
}
```
其中securityProxy.getAccessToken() 为null
经验证SecurityProxy中username和password均不为空, 可得知当前SecurityProxy对象未执行过login()方法, 导致token为空, 导致通过actuator执行相关方法时报403错误

相关版本 spring boot 2.3.2.RELEASE   cloud  Hoxton.SR4
spring-cloud-alibaba-dependencies 2.2.1.RELEASE     nacos-client 2.0.3

该bug存在于2.x以上, 1.4.2测试功能正常

**Comment by MajorHe1** [comment]
这一段代码是spring cloud alibaba里面的吧，跟nacos源码没有关系，因此不能算nacos的bug。
我刚看了一下源码，要确保SecurityProxy执行login()方法，至少要初始化一个namingService或者configService的对象，应该可以通过启动时初始化对象来规避login()方法不执行的问题？

**Comment by sucaiji** [comment]
> 
主要在于 nacos client 在1.4.2时能正常访问    升级到2.x时无法使用了.
另外在启动时 namingService和configService都初始化了,  只不过在Actuator调用相关方法时, 没有复用namingService和configService的SecurityProxy, 而是一个新的SecurityProxy, 因此没有login

**Comment by MajorHe1** [comment]
sorry 纠正一下我前面的错误理解，SecurityProxy 并不是单例的，无论是namingService还是configService，都持有了SecurityProxy的对象并在构造函数里面初始化，所以其他使用SecurityProxy的代码必须手动完成这个过程。

另外 “通过actuator执行相关方法”具体是指啥？是指通过spring cloud alibaba提供的actuator接口来调用执行服务注册之类的方法吗？
至于 “nacos client 在1.4.2时能正常访问 升级到2.x时无法使用”，请你验证一下，是否1.4.2版本用reqApi方法的时候，是否在params里面带上了用户名跟密码？nacos服务端验证的逻辑是有token优先取token验证，无token取用户名密码验证。还要看切换到2.X版本后走的是grpc还是http。

**Comment by sucaiji** [comment]
> sorry 纠正一下我前面的错误理解，SecurityProxy 并不是单例的，无论是namingService还是configService，都持有了SecurityProxy的对象并在构造函数里面初始化，所以其他使用SecurityProxy的代码必须手动完成这个过程。
> 
> 另外 “通过actuator执行相关方法”具体是指啥？是指通过spring cloud alibaba提供的actuator接口来调用执行服务注册之类的方法吗？ 至于 “nacos client 在1.4.2时能正常访问 升级到2.x时无法使用”，请你验证一下，是否1.4.2版本用reqApi方法的时候，是否在params里面带上了用户名跟密码？nacos服务端验证的逻辑是有token优先取token验证，无token取用户名密码验证。还要看切换到2.X版本后走的是grpc还是http。

1.“通过actuator执行相关方法” 指http://127.0.0.1:8080/actuator/service-registry?status=down 类似这样的链接. 会调用org.springframework.cloud.client.serviceregistry.endpoint.ServiceRegistryEndpoint类的setStatus方法.
```
@WriteOperation
public ResponseEntity<?> setStatus(String status) {
Assert.notNull(status, "status may not by null");

if (this.registration == null) {
	return ResponseEntity.status(HttpStatus.NOT_FOUND)
			.body("no registration found");
}

this.serviceRegistry.setStatus(this.registration, status);
return ResponseEntity.ok().build();
}
```
nacos实现了ServiceRegistry接口, 名为NacosServiceRegistry.  在该类中会调用NamingMaintainService.updateInstance()完成instance状态更改

**Comment by MajorHe1** [comment]
OK，已经明确了，确实是2.X版本nacos client的问题。
1.4.2版本
