### ISSUE TITLE
升级版本后出现无法获取配置信息

### ISSUE THREAD

**Issue by GreatWriter** [alibaba/nacos#7279]
![企业微信截图_16377374306493](https://user-images.githubusercontent.com/57381087/143191284-5e111528-2167-4e0e-9adc-8a209d7b9622.png)
![企业微信截图_1637737599634](https://user-images.githubusercontent.com/57381087/143191302-728f2ddc-9421-4a44-858d-69e1f08bda8c.png)
![企业微信截图_16377376315981](https://user-images.githubusercontent.com/57381087/143191319-c5a4c191-e68b-458a-af8b-3c241e75abbc.png)

![企业微信截图_1637737846221](https://user-images.githubusercontent.com/57381087/143191565-d6ad3917-fa0b-4806-8ea0-7b8b4b88a623.png)

### 启动后的端口是默认的8080，不是nacos中指定的端口。

**Comment by yumendedao** [comment]
请问这个问题解决了吗？我从1.4.1升级到2.0.4页出现同样的问题了
