### ISSUE TITLE
nacos必须在bootstrap.yml文件中配置，在application-dev.yml文件中会报异常的问题

### ISSUE THREAD

**Issue by TannnnnnnnnnnnnnnnK** [alibaba/nacos#7290]
主要异常关键信息：
`07:51:00.588 [com.alibaba.nacos.client.remote.worker] ERROR c.a.n.c.r.c.g.GrpcClient - [printIfErrorEnabled,99] - Server check fail, please check server localhost ,port 9848 is available , error ={}`
`Caused by: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception`
`Caused by: com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:9848
Caused by: java.net.ConnectException: Connection refused`
`07:51:00.588 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [4347ec55-69ef-4d91-a4fd-22e166e5acef_config-0] fail to connect server,after trying 143 times, last try server is {serverIp='localhost', server main port=8848},error=unknown`
可以看到是nacos配置没有生效，使用默认配置“localhost”
项目配置文件结构是
bootstrap.yml（spring.profiles.active=dev）
application-dev.yml
application-test.yml
在application-dev.yml中配置nacos并不会生效
`spring
  cloud:
    nacos:
      discovery:
        server-addr: 10.*.*.5:8848
      config:
        server-addr: 10.*.*.5:8848`
移到bootstrap.yml配置中就生效了，没有异常

但是最基本的需求是不同环境使用不同的nacos地址，然后用spring.profiles.active来管理

**Comment by MajorHe1** [comment]
我们之前使用spring cloud gateway 集成nacos的时候用的 2.x版本，也需要在bootstrap.yml里面指定
后面将 spring cloud gateway升级到3.x版本，就不用 bootstrap.yml文件了。
总之是spring cloud 版本的问题，建议升级试试

**Comment by william-xu** [comment]
nacos由于要先于应用其他配置项进行配置，所以必须放在bootstrap文件中，不同profile的配置要放在bootstrap-{profile}.{file-extension}中，应用的不同profile通过在nacos中个添加application+不同profile+file-extendsion来配置

**Comment by winlong** [comment]
我们在启动应用模块时也遇到了同样的问题：
ERROR c.a.n.c.r.c.g.GrpcClient - [printIfErrorEnabled,99] - Server check fail, please check server 172.25.2.118 ,port 9848 is available , error ={}
很奇怪的事，同样的jar包，在一台服务器上运行没有问题，但在另外一台服务器上运行就出现这样的错误提示。

**Comment by RealMuDao** [comment]
2.2.7.REALEASE版本，测试有效果！

**Comment by laoliugotoA** [comment]
6666

**Comment by Axin9944** [comment]
我在启动应用模块时遇见了同样的问题：
如果配置文件是 application.yml, 初始化的ServerListManager是 fixed-localhost_8848,
导致我的服务会同时访问两个9848端口。

<img width="1344" height="828" alt="Image" src="https://github.com/user-attachments/assets/0cd722f7-5f6c-4c6f-80ed-58006dfb8e7b" />

<img width="2186" height="341" alt="Image" src="https://github.com/user-attachments/assets/a41f40e9-001f-482d-b807-55fcb37edc2c" />
