### ISSUE TITLE
Code Cleanliness needs improvement in NamingHttpClientProxy.java

### ISSUE THREAD

**Issue by ArthurMograbi** [alibaba/nacos#7291]
**Describe the bug**
Using a PMD, I was able to detect an elevated concentration of code smells and anomalies, including several labeled as critical.

**Expected behavior**
Little to no presence of PMD anomalies, indicating an optimally refactored code.

**Acutally behavior**
An elevated concentration of code smells and anomalies were present.

**How to Reproduce**
1. Have an command line pmd tool
2. Run on NamingHttpClientProxy.java
OR
1. Have eclipse-pmd installed on your eclipse distribution
2. Right-click on 'NamingHttpClientProxy.java', go to the PMD options and click on check code

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [nacos 2.0.3]
 - Module [client\src\main\java\com\alibaba\nacos\client\naming\remote\http\]
 - SDK [original]

**Comment by Liubey** [comment]
@realJackSun when I run with Ali-Check,I find nothing, am wrong?

**Comment by ArthurMograbi** [comment]
> @realJackSun when I run with Ali-Check,I find nothing, am wrong?

The objective is not to remove NACOS errors, but rather to make the code more cohesive, readable and maintainable

**Comment by KomachiSion** [comment]
The pmd check will run for each PR, no problem for now, I think this issue is not clear enough
