### ISSUE TITLE
I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by zcz3313** [alibaba/nacos#7299]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8746495/143536414-21070444-3f2d-4b28-aa9f-d943d78d7f6c.png)
this node can't sync correct service instance list to other nodes.
I have trace the code, and also find logs as follow:
![image](https://user-images.githubusercontent.com/8746495/143536748-421e9a3f-621b-4844-b8d5-077ced1d4da8.png)

So I keep going on the source code. The method ```endOfInput``` is:
![image](https://user-images.githubusercontent.com/8746495/143537524-bf6e9e73-73ba-4cd7-acb4-6c4a51ac1637.png)
This class does not have a parameterless constructor:
![image](https://user-images.githubusercontent.com/8746495/143538117-27a6c268-a32b-4b78-8cf6-9a9193d1492e.png)

I don't know how to reproduce this bug. But I have searched some information on the internet, may be this could be helpful:
https://www.cnblogs.com/quwenli/p/15050215.html

**Expected behavior**
The I/O reactor thread could keep running when exception throws

**Acutally behavior**
The I/O reactor thread stop

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version nacos-server 1.4.2
 - Module all

**Comment by CherishCai** [comment]
relate https://github.com/alibaba/nacos/issues/5138

**Comment by CherishCai** [comment]
![image](https://user-images.githubusercontent.com/16837364/143806538-2a11bfd2-c8a9-4aa8-b0ab-7d3e2ffd9d97.png)

看起来这版本号管理得不好，引了两个版本

**Comment by CherishCai** [comment]
当前 1.4.2 的依赖树：
![image](https://user-images.githubusercontent.com/16837364/143815818-b1dc7a6d-039c-4150-ab61-c3fbea48c8a8.png)

我先尝试下升级到以下版本。感谢楼主提供参考方案
```xml
<httpcore.version>4.4.13</httpcore.version>
<httpclient.version>4.5.13</httpclient.version>
<httpasyncclient.version>4.1.4</httpasyncclient.version>
```

**Comment by zcz3313** [comment]
> 
> ```
> <httpcore.version>4.4.13</httpcore.version>
> <httpclient.version>4.5.13</httpclient.version>
> <httpasyncclient.version>4.1.4</httpasyncclient.version>
> ```
Yeah, I think ```<httpcore.version>4.4.13</httpcore.version>``` will just work.
But I'll upgrade all these three artifacts anyway.

**Comment by zcz3313** [comment]
@realJackSun Can you consider solving this bug in the next 1.4.x version, eg ```1.4.3``` ?

**Comment by zrlw** [comment]
2.0分支有个已经合并的pr，它是通过增加IOReactorExceptionHandler防止出现I/O reactor status: STOPPED：
https://github.com/alibaba/nacos/pull/6441

**Comment by zrlw** [comment]
#6441 不仅捕获了IOException（ConnectionClosedException 属于IOException ），而且捕获了全部RuntimeException，可能要更稳妥一些。

**Comment by zrlw** [comment]
更新一下，#6441拦截不了error，所以搞不定nacos依赖组件版本不兼容导致的问题，需要删掉nacos的pom文件里定义的httpcore和httpcore-nio版本，直接用springboot定义的版本： #7698
