### ISSUE TITLE
About Nacos Security

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#730]
Nacos 0.8描述，说添加了安全认证（账号密码登录），但就目前来看，这个防君子不防小人。
控制台需要登录，但是应用注册到Nacos上是不需要填写账号密码的。Nacos是提供HTTP接口让人操作Nacos中的数据的，这意味着，只要构造相应参数，并发送请求，完全可以绕开账号密码登录的机制，去搞Nacos数据。
建议改进。

**Comment by mr253727942** [comment]
> Nacos 0.8描述，说添加了安全认证（账号密码登录），但就目前来看，这个防君子不防小人。
> 控制台需要登录，但是应用注册到Nacos上是不需要填写账号密码的。Nacos是提供HTTP接口让人操作Nacos中的数据的，这意味着，只要构造相应参数，并发送请求，完全可以绕开账号密码登录的机制，去搞Nacos数据。
> 建议改进。

从开源系统的安全角度来说 我也认同这一点 应该做一个开关配置出来 是否需要用户密码验证功能

**Comment by nkorange** [comment]
该问题会在 #1105 跟踪
