### ISSUE TITLE
Spring Boot 2.4 Config Data Loader Support

### ISSUE THREAD

**Issue by 879913935** [alibaba/nacos#7306]
Spring Boot 2.4之后配置加载的推荐方式有变动，原先是通过PropertySourceLocator加载到bootsrap上下文，最新的版本虽然还可以手动启用bootsrap上下文来过渡，不过标准的模式还是要按照最新的接口来扩展

现在推荐的应该是`ConfigDataLocationResolver`和`ConfigDataLoader`这一对，其实都一年了，还未升级和跟进，希望能尽快提供新的配置方式

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-spring-boot-project/pull/194
