### ISSUE TITLE
Nacos login page's bug

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#731]
One has logined, When comes to `http://localhost:8848/nacos/#/login` , Nacos comes out login page as well.
I think this Should be avoid.

**Comment by mr253727942** [comment]
QAQ I may not agree with you. Maybe some one just  want to use another username  to login the system

**Comment by eacdy** [comment]
@mr253727942 If he wants to change username, he Should logout first rather than go back to login page directly.
===
PS. 如果一个人想切换账号，他应该先退出，然后再到登录页输入其他账号登录。而不是直接访问登录页。
另外，相信市面上没有成熟的系统是这样设计的，用户登录了账号A，不做退出，直接访问登录页依然让登录账号B。都应该做控制，对于登录的用户，不允许重复登录。
===
再举个例子，你登录了淘宝后，再点击返回按钮，让它跳转到登录页或者直接数据登录页的URL地址，看下界面。

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
