### ISSUE TITLE
nacos2.0.1重启后配置文件丢失

### ISSUE THREAD

**Issue by usechant** [alibaba/nacos#7319]
1.重启后工作空间和配置文件丢失

2.环境 centos7.0 单机 nacos2.0.1  项目环境不允许mysql

3.期望重启配置文件存在

**Comment by caomingjie-code** [comment]
这个新版本应该已经支持了，你是重启的nacos服务呢还是重启的是服务器呢

**Comment by usechant** [comment]
重启的服务器

**Comment by usechant** [comment]
我是否换成2.0.3 就可以了？
