### ISSUE TITLE
Maybe urls of Open API are not elegant enough.

### ISSUE THREAD

**Issue by eacdy** [alibaba/nacos#732]
https://nacos.io/zh-cn/docs/open-API.html

举几个例子：
/nacos/v1/cs/configs
/nacos/v1/cs/configs/listener
/nacos/v1/ns/instance/beat
/nacos/v1/ns/instance

1. 为什么configs用复数，instance用单数？能否统一起来？至少在风格上……
2. 不建议将Configuration Set简写成cs，不是每个人都会去看文档了解概念的……同理，ns也是……在我看来，尽量在同一个产品里用统一的词汇描述一件事情才是最佳实践。缩写sh什么的当然也可以，但文档也得跟上，否则会增加理解成本。
3. 是否可以参考Eureka的REST API设计？URL规划得比较清晰： <https://github.com/Netflix/eureka/wiki/Eureka-REST-operations>

我不是来拆台的，我很看好Nacos，故而提建议改进。

**Comment by nkorange** [comment]
Any suggestion on what the API URLs going to be exactly?

**Comment by eacdy** [comment]
统一单复数，建议复数；缩写改全称；url尽量restful。

**Comment by nkorange** [comment]
@eacdy 
1. 'configs' has nothing to do with 'instance', so they don't have to be in the same form. You can also see singular form path in config module.
2. 'cs' is the abbreviation of 'configuration service', not of 'configuration set', same as 'ns'. If 'cs' is replaced by 'configuration', it is conflicting with the following 'configs'. But your suggestion on document supplementary is very good.
3. This has been fully disscussed before our first release. One reason of the choice of our current URLs is that we consider the standard RESTful URLs is not flexible enough for extension.

**Comment by eacdy** [comment]
@nkorange 
1. OK, I see.
2. If the doc <https://nacos.io/zh-cn/docs/open-API.html> never writes about the 2\. 'cs' is the abbreviation of 'configuration service', Who knows?
3. They're only some advices. Sometimes We May need to write nacos client in other language such as php or other language Nacos never supports ( <https://nacos.io/zh-cn/docs/other-language.html> ), or , We May just wanna use HTTP API do some tests. I don't think the urls in the current form are good enough, or good enough to understand. In my opinion, We Should build url easily without reading the document again and again.
haha.
B.T.W, They're only some advices.

**Comment by nkorange** [comment]
@eacdy As I said, you suggestion on document is very good.
