### ISSUE TITLE
nacos-client 无法从nacos服务器获取最新的配置

### ISSUE THREAD

**Issue by zhangchaoyanggit** [alibaba/nacos#7321]
版本：1.4.2  型号 macbook pro m1

问题描述：
 在nacosWeb页面修改了配置后，本地拉取的还是老配置。

通过源码追踪我发现代码ServerHttpAgent.httpGet()方法拉取的也是老配置，我根据nacosWeb端查看配置文件的资源路径 与nacos client路径对比后发现
加上&show=all参数以后才可以获取最新的配置信息。但是代码中并没有此参数? 是我配置有问题呢还是哪里出了问题。
还有一种就是重启nacos服务器 会拉取最新代码。

**Comment by onewe** [comment]
Provide the more information for this issue please. such as environment information and code example etc.

**Comment by zhangchaoyanggit** [comment]
#### Sorry, this is my first submission.




这个是加入show=all之前
![image](https://user-images.githubusercontent.com/24430480/144156785-a52f1699-88e8-4eca-887c-25e3dddcf9df.png)



加入show=all 之后
![image](https://user-images.githubusercontent.com/24430480/144156885-b82d8fd8-63cd-4955-836e-a62f56de6d7c.png)

加入show=all之前 
gateway.white.list 的配置为  /platform-oauth/oauth/**



加入show=all之后 
gateway.white.list 的配置为  /platform-fkd/auth/oauth/**

这种情况不只是发生在mac，根据同事反应windows也有这种情况。

这里是我的yaml配置
![image](https://user-images.githubusercontent.com/24430480/144157322-8d4dc174-63d0-42d4-bf70-6450c5fdaf80.png)



#### Please help me, thank you very much.

**Comment by onewe** [comment]
Bro,I haven't reproduced it yet. What's your Nacos server version? @zhangchaoyanggit 
Before
![image](https://user-images.githubusercontent.com/38708836/144163945-950d5b76-385e-4ee2-8d57-1d9c3ad8e9b1.png)
Then edit it
![image](https://user-images.githubusercontent.com/38708836/144164037-8900f55d-765b-4fc2-9e99-fd8f189c0167.png)
After
![image](https://user-images.githubusercontent.com/38708836/144164116-a94fb135-980b-4c93-b5d0-44541bfc1393.png)

My nacos server version is 1.4.2
![image](https://user-images.githubusercontent.com/38708836/144164218-53ebe814-8f44-423c-b652-020f101e16a7.png)

**Comment by onewe** [comment]
Isn't my step wrong?

**Comment by zhangchaoyanggit** [comment]
我用的是1.4.2版本的，这个问题不是必现，但是经常出现。
 查看了源码调用了/v1/cs/ops/localCache 接口就好了，但是是暂时性的，还会复现。

**Comment by zhangchaoyanggit** [comment]
请问后续还会跟进此问题？

**Comment by onewe** [comment]
@zhangchaoyanggit 会继续跟进的,目前我还没复现这个问题,尴尬了.你的 nacos 是集群吗？

**Comment by zhangchaoyanggit** [comment]
单节点
