### ISSUE TITLE
这是我们配置文件，连接外部的mysql,不成功同样的错误，ping网络没问题

### ISSUE THREAD

**Issue by zhaoyanwenqi** [alibaba/nacos#7323]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.host: "10.7.11.63"
  mysql.db.name: "nacos_devtest"
  mysql.port: "30306"
  mysql.user: "nacos"
  mysql.password: "nacos"
---

你是想在k8s里连接非k8s部署的mysql？

只要网络通就没有问题。但是yml的配置需要你自己修改一下。

_Originally posted by @KomachiSion in https://github.com/alibaba/nacos/issues/5347#issuecomment-818673576_

**Comment by KomachiSion** [comment]
1. telnet可能不通
2. 配置没有在nacos中生效。
