### ISSUE TITLE
Docker  启动链接数据库问题

### ISSUE THREAD

**Issue by RoeGross** [alibaba/nacos#7325]
docker  run --name nacos -d -p 8848:8848 --privileged=true --restart=always -e JVM_XMS=256m -e JVM_XMX=256m -e MODE=standalone -e PREFER_HOST_MODE=hostname -v /home/mydata/nacos/logs:/home/nacos/logs -v /home/mydata/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties nacos/nacos-server

Docker  启动已将配置文件挂载，启动未链接数据库，必须进容器修改数据库配置或在启动上加命令？？

**Comment by SSDespair** [comment]
version: '3.3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    restart: always
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
			MYSQL_SERVICE_HOST: ip
			MYSQL_SERVICE_DB_NAME: 数据库名称
			MYSQL_SERVICE_PORT: 端口
			MYSQL_SERVICE_USER: 用户
			MYSQL_SERVICE_PASSWORD: 密码
			MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
      JVM_XMS: 1g
      JVM_XMX: 1g
      JVM_XMN: 512m
    volumes:
      - /root/docker:/home/nacos/data
    ports:
      - 8848:8848

使用docker-compose 启动试试，上面是脚本文件修改自己的数据库就可以运行
