### ISSUE TITLE
在看nacos源码时，应该从那个分支进行作为入口。

### ISSUE THREAD

**Issue by caomingjie-code** [alibaba/nacos#7329]
## Issue Description
1.我在阅读源码的时候发现分支特别多. 目前我在看develop.
 不知是否可以。是否可以对develop分支进行测试，
如果发现问题可以进行修改吗？

**Comment by li-xiao-shuang** [comment]
> ## Issue Description
> 1.我在阅读源码的时候发现分支特别多. 目前我在看develop. 不知是否可以。是否可以对develop分支进行测试， 如果发现问题可以进行修改吗？

可以的 develop是开发分支 是2.x 版本

**Comment by kuaile-zc** [comment]
develop branch!
