### ISSUE TITLE
Created many HostReactor Obj,Excessive memory usage

### ISSUE THREAD

**Issue by SuperEdison** [alibaba/nacos#7338]
**Describe the bug**
内存不给多的情况经常full gc，创建很多HostReactor对象，整个jvm都是这个对象占了很大部分内存
![image](https://user-images.githubusercontent.com/84554944/144396075-70b7e2e5-093b-44c8-a6ae-2eb8bf433bb5.png)
![image](https://user-images.githubusercontent.com/84554944/144396194-9cdde5c3-d4dd-420d-acb9-8e19de05a758.png)
![image](https://user-images.githubusercontent.com/84554944/144396398-cce86a85-07dd-48dd-8504-ea43c176c015.png)

**Expected behavior**
不应该创建这么多相同的对象

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version nacos-client 1.3.3 nacos-server 1.3.2
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo] com.alibaba.nacos nacos-client

**Additional context**
firstly submit issue，The format is not very formal,forgive me

**Comment by lpaz010** [comment]
能升级nacos版本就升级版本吧:D

**Comment by SuperEdison** [comment]
> 能升级nacos版本就升级版本吧:D

1.3.2都会有这个问题吗

**Comment by whaiq** [comment]
i have the same issue , hava any resolves?

**Comment by whaiq** [comment]
> > 能升级nacos版本就升级版本吧:D
> 
> 1.3.2都会有这个问题吗

升级到哪个版本？解决了吗？
