### ISSUE TITLE
[enhancement]  Authentication

### ISSUE THREAD

**Issue by flystar32** [alibaba/nacos#734]
**Is your feature request related to a problem? Please describe.**

 add Authentication  when Nacos client  call   Nacos Server API

**Describe the solution you'd like**
none

**Describe alternatives you've considered**
none

**Additional context**
none

refer to https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/334

**Comment by nkorange** [comment]
duplicated with #730
