### ISSUE TITLE
Permission management data redundancy: two records appear under the same ns and the same resource

### ISSUE THREAD

**Issue by hujun-w-2** [alibaba/nacos#7356]
**Describe the bug**

Permission management data redundancy: two records appear under the same ns and the same resource
（权限管理数据冗余：同一个ns，同一个资源，可以同时出现两条记录）
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
![image](https://user-images.githubusercontent.com/39894911/144711015-64291bb8-4ba5-460b-9b69-272a6350f2c5.png)
**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by hujun-w-2** [comment]
i think this should be resolved

**Comment by lpaz010** [comment]
权限安全管理插件已经在开发中，所以等待吧:smiley:
