### ISSUE TITLE
Why don't  support LDAP Auth in  Nacos Server dashboard ?

### ISSUE THREAD

**Issue by ZuoGuocai** [alibaba/nacos#7362]
I use Nacos in my project and find it's so hard to  face  growing number of people and services's  challenge.  I wonder that ：Is it  support  ldap auth in the dashboard？ I search some items about ldap like  in the application.properties. But I don't know  how it working in nacos dashboard login ?  

 ```
nacos.core.auth.system.type=ldap
nacos.core.auth.ldap.url=ldap://ip:389
nacos.core.auth.ldap.userdn=cn={0},ou=user,dc=company,dc=company
```

**Comment by zhangwenliang012** [comment]
I had the same problem
