### ISSUE TITLE
2.0.1版本部署到k8s上，共三个节点，一个节点重启后，web页面刷新发现注册服务不一样，存在数据不一致问题。

### ISSUE THREAD

**Issue by JingmoXi** [alibaba/nacos#7374]
**Describe the bug**

一个nacos pod重启后，刷新页面发现一个已经下线的服务，多次刷新，出现服务“忽上忽下”
的情况，排查日志发现是数据出现了不一致。

**Expected behavior**

通过查看nacos-cluster.log等日志，选举正常，也没发现脑裂。倒是出现了一个{IP-DEAD}的奇怪信息，说明nacos已经知道改服务已经有问题，但是一直没有下线。

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by YogurtOlderMan** [comment]
我也是出现此类问题，微服务也一直报连不上nacos，估计请求转发到了不健康的实例上去了
