### ISSUE TITLE
nacos-client 2.0.3 program memory overflow

### ISSUE THREAD

**Issue by Comven** [alibaba/nacos#7377]
nacos-server-2.0.3
nacos-client-2.0.3

Memory overflow occurred when the client program was running for several hours.The hprof file analysis results are shown in the figure below:
![image](https://user-images.githubusercontent.com/8464801/145135197-c51b1e55-1b08-44e1-bb38-c12b7f1791cf.png)

Among them, the largest object java.lang.object [] data reaches 100000, and the main contents are as follows:
![image](https://user-images.githubusercontent.com/8464801/145135587-9ccd1247-742d-402c-9e85-76fb5e100851.png)

and main data are as follows:
![image](https://user-images.githubusercontent.com/8464801/145135287-ad61cc1f-5dc7-491d-9337-62a35ac645b0.png)

The feeling is that when the Nacos client cannot access the Nacos server in some cases, some grpc information will always be placed in its own cache and cannot be released. It is recommended to clean it regularly. 

In fact, the program can be called by other programs before memory overflow. Although I don't understand the specific overflow reason, I personally think that some communication problems between the Nacos client and the Nacos server should not cause the memory overflow of the client business program.

Please pay attention to this problem. Thank you very much!

**Comment by MajorHe1** [comment]
client 端 是每一次请求都 new 了新的 namingservice 或者  configservice 对象，还是复用同一个对象

**Comment by Comven** [comment]
> client 端 是每一次请求都 new 了新的 namingservice 或者 configservice 对象，还是复用同一个对象

这个客户端程序完全是一个被动被其他业务程序调用的程序,不会使用nacos-client来主动进行其他业务通信，内存溢出完全是该程序的nacos-client组件与nacos-server之间通信造成的。在该程序的nacos-client的gRPC缓存导致内存溢出前，程序假死前，其他程序完全可以正常调用这个程序，因为业务需求有另外程序每一分钟会调用一次该程序。换成1.4.2的nacos-client就是一直正常运行的。

**Comment by MajorHe1** [comment]
nacos 2.x 的版本是基于连接的，如果每一次被调用都使用新的 namingService 或者 configService对象就会造成 grpc 内存溢出。
建议先检查一下这个，使用nacos -client 组件的方式，是不是每次都创建了新的对象

**Comment by Comven** [comment]
> 

你能举个例子吗？我使用的是SpringCloudAlibaba组件，所有配置都采用默认的。但是个人认为即使每次创建新对象都不应该无限缓存像这种数据
![image](https://user-images.githubusercontent.com/8464801/145219487-4a05f64a-bdb1-4146-8003-e4950b327e2a.png)
因为这样缓存没有实际意义，还不如抛出异常，让开发者和使用者更容易知道问题。

**Comment by MajorHe1** [comment]
使用spring cloud alibaba 组件最后还是依赖nacos client在工作
我上次碰到内存溢出就是每一笔跟nacos server的交互请求都在创建新的 namingService对象导致的
所以我建议你先检查一下这个，可以检查一下端口，是不是一个程序跟nacos server建立了多个连接

**Comment by Comven** [comment]
> 

如果是你说的这个原因，如果修改解决这个问题呢，比如说时需要对配置做一下变动吗？

**Comment by Comven** [comment]
> 使用spring cloud alibaba 组件最后还是依赖nacos client在工作 我上次碰到内存溢出就是每一笔跟nacos server的交互请求都在创建新的 namingService对象导致的 所以我建议你先检查一下这个，可以检查一下端口，是不是一个程序跟nacos server建立了多个连接

如果是你说的这个原因，如果修改解决这个问题呢，比如说时需要对配置做一下变动吗？

**Comment by MajorHe1** [comment]
不是改变配置，是建议检查一下源码，同一个程序保证使用namingService的单例。
极端情况下，一个程序确实需要创建多个namingService对象（例如网关代注册同一个服务的不同实例），也应该保证namingService的可数，而不是一笔请求就创建一个。
当然，这只是最有可能的错误，毕竟是我自己碰到过的。
从你贴出来的OOM信息来看，排查思路还是建立在检查grpc连接数上面，理想情况下，一个程序使用一个namingService对象，跟nacos-server建立一个grpc连接。

**Comment by Comven** [comment]
> 不是改变配置，是建议检查一下源码，同一个程序保证使用namingService的单例。 极端情况下，一个程序确实需要创建多个namingService对象（例如网关代注册同一个服务的不同实例），也应该保证namingService的可数，而不是一笔请求就创建一个。 当然，这只是最有可能的错误，毕竟是我自己碰到过的。 从你贴出来的OOM信息来看，排查思路还是建立在检查grpc连接数上面，理想情况下，一个程序使用一个namingService对象，跟nacos-server建立一个grpc连接。

我不明白你说的看源码是看我们自己的业务代码还是nacos-client的源码。如果是看自己的源码的话，感觉没有意义。因为这个程序不会主动调用其他业务程序，没有在自己写的代码里面有主动调用远程服务的操作。参数配置上，我们也没有单独针对gRPC做任何的配置，都是采用默认的在测试。那如果是nacos-client的源码问题，还是希望官方能够修复解决。不过这两月nacos进度像是停滞了一样。

**Comment by MajorHe1** [comment]
是看你们自己的源码。

> 不会使用nacos-client来主动进行其他业务通信，内存溢出完全是该程序的nacos-client组件与nacos-server之间通信造成的

跟调用业务程序没有关系，显然不可能用nacos -client 来进行什么业务通信

> 因为业务需求有另外程序每一分钟会调用一次该程序。换成1.4.2的nacos-client就是一直正常运行的。

我只是根据上述背景，怀疑问题有可能出在这里。我理解别的业务程序调用出问题的该程序，一分钟一次，是不是该程序被调一次，就发生一次跟nacos-server的交互，然后每一次交互都在创建namingService 或者 configService对象，又因为长连接对象不释放，就OOM了。为什么1.4.2没有出问题，是因为1.x的版本是基于http短连接的，2.x是基于长连接的，所以建议看看连接数。

> 不过这两月nacos进度像是停滞了一样。

确实，可能官方在忙双11双12吧。

**Comment by Comven** [comment]
> 

我们自己的代码没有问题，我们有很多接口程序，使用1.4.2版本没有任何问题，最长的都跑了快一年了，一换成2.0.3过几个小时就出现内存溢出，一分钟调用一次是把业务调用关闭后为了看到效果用另外一个程序做了一个定时调用。
> 是不是该程序被调一次，就发生一次跟nacos-server的交互，然后每一次交互都在创建namingService 或者 configService对象，又因为长连接对象不释放，就OOM了

关于这个说法，我们无从下手，nacos-client与nacos-server的调用是完全SpringCloudAlibaba组件自动封装和完成的，不在我们业务代码的控制范围。所以之前我才说不明白你说的为啥要看源码。我们将程序的组件从eureka到nacos1.4.2都OK，只是升级到nacos-2.0.3就出现这问题，个人觉得这个是nacos-client底层缓存处理的问题，包括你说的长连接释放问题。我觉得都要从nacos-client底层逻辑去解决。

**Comment by MajorHe1** [comment]
> 只是升级到nacos-2.0.3就出现这问题

是只替换了nacos-2.0.3的jar，升级 spring cloud alibaba 了吗 （ 当然我也不清楚最新的 spring cloud alibaba 是否完美支持 nacos -client 2.x 的版本）

我们自己有一个网关，应该跟你说的场景很相似，接收业务程序的调用，然后依赖nacos-client去跟nacos-server交互，每一笔调用请求都会交互一次，使用nacos-2.0.3至今，线上跑了将近三个月了没有出现OOM问题。从这个角度来看 nacos-client应该不存在什么重大BUG必然导致OOM，问题有可能出在spring cloud alibaba的封装操作上。

所以如果你的OOM是必现的话，不翻源码也可以在程序运行期间直接用命令看跟nacos-server的连接，是不是一直在增长。
