### ISSUE TITLE
retention config history by threshold

### ISSUE THREAD

**Issue by Liubey** [alibaba/nacos#7378]
**Is your feature request related to a problem? Please describe.**
When I use nacos config to do such as keep heartbeat,I find that his_config_info have huge rows,so there is have function retention by days,I think it is not enough.
我在用nacos做心跳检测时，很多节点，每个节点5秒钟更新一次配置里的心跳时间，我发现his_config_info表里的数据实在是太多太多了

**Describe the solution you'd like**
a new feature to retention config history by threshold,just keep threshold rows one config

于是我想新增一个功能，能定时清除这些key的历史记录，仅保持可配置的最新的条数（如10条），当然这个功能默认不开启。
**Describe alternatives you've considered**

**Additional context**

**Comment by Liubey** [comment]
@i will solve it@

**Comment by MajorHe1** [comment]
为什么要用配置中心的配置来做心跳检测

**Comment by Liubey** [comment]
@MajorHe1 因为配置信息是用来共享给后续主服务通信使用的，每个服务实例的每一段逻辑都会有一个心跳时间，不知道这么说能不能理解

**Comment by MajorHe1** [comment]
> @MajorHe1 因为配置信息是用来共享给后续主服务通信使用的，每个服务实例的每一段逻辑都会有一个心跳时间，不知道这么说能不能理解

发布配置同样要定义配置的dataId，那为什么不自己定义这个服务实例的 serviceId，然后注册到注册注册中心，元数据里面随便填多少逻辑的不同心跳时间，服务发现的时候按这个serviceId发现，这样做不行吗

怎么发布配置的就怎么注册服务，怎么获取配置的就怎么服务发现，拿服务的元数据当配置的内容用，我觉得没有什么区别

**Comment by Liubey** [comment]
dataId是由client和server端共同约定的一个业务唯一标识来自动生成的，这个唯一标识是每一段逻辑有一个，也就是说一个服务下面有多个共同商议好的唯一标识（也就是dataId）
serviceId在我们这是由spring.application.name来区别和标识的。我刚才说了这段唯一标识和serviceId无法绑定，这段逻辑可以出现在任何项目中，serviceId也就无法固定，如果想维系一个serviceId和dataId的关系，还要再加一层映射？

**Comment by Liubey** [comment]
另外这个元数据里存心跳怎么更新比较优雅？

**Comment by MajorHe1** [comment]
发布配置需要指定 dataId， group,  configContent存你的心跳时间；
把dataId当做服务注册的serviceId来用，用元数据来存你的心跳时间；

> 你总不能强求每个业务方都是配置中心和服务发现同时使用的，得给人家选择权嘛，万一就不用服务注册发现呢

你已经启用了nacos当配置中心了，就算nacos-server的启动模式 function-mode = config，也是自带注册中心能力的，对于使用nacos-client的客户端而言，既然发布配置可以new出来 configService对象操作配置，那就一定可以new出来namingService对象操作服务，连额外的jar包都不用引入。
业务方不关心，中间件怎么封装完全可以控制。

**Comment by Liubey** [comment]
唉……拿着锤子看哪里都是钉子。请问我拿dataId当服务去注册，叫使用nacos的人和做服务治理的同事咋办？让他们人肉排除掉这些dataId？那让那些serviceId和cmdb绑定来控制服务注册安全的二次开发的公司开个口子叫我随便往上注册服务吗？ @MajorHe1 ，是吧

另外我刚才试验把心跳当做服务的元数据写到注册中心，发现只启动时能写入，后续的定时线程无法再更改了。
`        while (true) {
            Map<String, String> metadata = nacosDiscoveryProperties.getMetadata();
            metadata.put("startup.time", DateTime.now().toString("yyyy-MM-dd HH:mm:ss"));
 `
namingservice里面的Instance也拿不到这数据，是我的用法有问题吗……

**Comment by Liubey** [comment]
对了，我刚才看了圈代码，我用的是nacos 1.2.
我看最新分支上com.alibaba.nacos.naming.core.Instance里有个lastBeat，不知道你指的是不是这个？服务级别的

**Comment by MajorHe1** [comment]
> com.alibaba.nacos.naming.core.Instance里有个lastBeat
