### ISSUE TITLE
nodejs设置配置时总是更新为text类型

### ISSUE THREAD

**Issue by zhupengfeivip** [alibaba/nacos#7382]
**Describe the bug**
我在配置中创建的是JSON类型，但通过nodejs设置配置时总是更新为text类型，调用时也没有让传数据类型。

**Expected behavior**
类型不改变，或者在调用时设置

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1. 创建一个JSON类型的配置
2. 调用publishSingle更新
3. 在管理后台查看类型已经变成了TEXT类型

**Additional context**
是否与以下信息有关
![image](https://user-images.githubusercontent.com/30720809/145176388-97956cdb-ca55-4618-9d2d-07dc6f2b7a4c.png)

**Comment by zhupengfeivip** [comment]
@jun1st @martin-g @zhfish 这个问题没人处理吗？还是已经解决了？

**Comment by martin-g** [comment]
I am not sure why you pinged me here, @zhupengfeivip
