### ISSUE TITLE
Some enhancement for common tools

### ISSUE THREAD

**Issue by karsonto** [alibaba/nacos#7387]
I found a bug in common cache util,it will skip the cache object timeout checking.

**Comment by onewe** [comment]
@karsonto Can you describe it please?

**Comment by karsonto** [comment]
please help to commit the changes AutoExpireCache.class  

    @Override
    public V get(K key, Callable<? extends V> call) throws Exception {
      //  return this.delegate.get(key, call);
        //for bug fix [issues]7387 modify by karson.
        V cachedValue = this.get(key);
        if(null == cachedValue){
            V v2 = call.call();
            this.put(key,v2);
            return v2;
        }
        return cachedValue;
    }

**Comment by onewe** [comment]
@karsonto Thanks. I will fix it

**Comment by onewe** [comment]
@onewe will solve it@

**Comment by onewe** [comment]
I have had a look at the code.
`LruCache`、`AutoExpireCache`  and `SynchronizedCache` depend on the `SimpleCache` in the `CacheBuilder`.
```java
// CacheBuilder#118
 public Cache<K, V> build() {
        Cache<K, V> cache = new SimpleCache<>(initializeCapacity);
        if (lru) {
            cache = new LruCache<>(cache, maximumSize);
        }
        if (expireNanos != -1) {
            cache = new AutoExpireCache<>(cache, expireNanos);
        }
        if (sync) {
            cache = new SynchronizedCache<>(cache);
        }
        return cache;
    }
```
So, They have same logic finally.
```java
// SimpleCache#49
  @Override
    public V get(K key, Callable<? extends V> call) throws Exception {
        if (cache.containsKey(key)) {
            return cache.get(key);
        } else {
            V v2 = call.call();
            cache.put(key, v2);
            return v2;
        }
    }
```

@karsonto 
Why do you want to change the logic of the `AutoExpireCache `.

**Comment by karsonto** [comment]
because AutoExpireCache #61 return this.delegate.get(key, call) is call SimpleCache #49,  only put the object into a hashmap

**Comment by karsonto** [comment]
please add my wechat ID : gzsdcjw and discuss
