### ISSUE TITLE
Provide a new api for fetching all instance of the service 

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#739]
Just as described in the title,   we want a new api  for fetching all instance of the service, which is important for sync all instances to another cluster

**Comment by plusmancn** [comment]
I guess this feature has been supported according to the source code of `com.alibaba.nacos.client.naming.NacosNamingService#getAllInstances(java.lang.String)`, and then the APIs were exported by nacos client, see: https://nacos.io/zh-cn/docs/sdk.html.

Therefore, the issue should be closed.  @nkorange
