### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bolukezz** [alibaba/nacos#7391]
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project nacos-consistency: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-x86_64:3.8.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.8.0 -Dclassifier=osx-x86_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.8.0 -Dclassifier=osx-x86_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]         1) com.alibaba.nacos:nacos-consistency:jar:2.0.0
[ERROR]         2) com.google.protobuf:protoc:exe:osx-x86_64:3.8.0
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   com.alibaba.nacos:nacos-consistency:jar:2.0.0

**Comment by bolukezz** [comment]
Does anybody know what the problem is？

**Comment by Liubey** [comment]
https://blog.csdn.net/qq_42651904/article/details/120923278 看看这个

**Comment by bolukezz** [comment]
好的
