### ISSUE TITLE
InstanceController 未按照 ServiceControllerV2 版本做代码迭代，并完善UserController及关联类中对于用户状态的判断逻辑

### ISSUE THREAD

**Issue by SteafanMrZhou** [alibaba/nacos#7393]
**Describe the bug**
1.不算是Bug，InstanceController 未按照 ServiceControllerV2 版本做代码迭代，我可以来迭代一下。
It's not a bug. Instancecontroller doesn't iterate the code according to the servicecontrollerv2 version. I can iterate.
2.看到过有朋友提交了关于用户修改密码后用户状态判断的逻辑问题，所以完善了对UserController及关联类中对于用户状态判断的逻辑代码。
I've seen a friend submit a logical question about the user status judgment after the user changes the password, so I improved the logical code for the user status judgment in usercontroller and associated classes.

**Comment by SteafanMrZhou** [comment]
@ I will solve it @

**Comment by SteafanMrZhou** [comment]
#7394

**Comment by realJackSun** [comment]
@SteafanMrZhou 收到，感谢贡献。社区正在审核。

**Comment by realJackSun** [comment]
![image](https://user-images.githubusercontent.com/58767027/153113731-d6912ad0-1a14-4c1a-94c4-50da0b879e5e.png)
@SteafanMrZhou 你这里有很多其他的Controller，能否把这个ISSUE改一下，和PR一致？

**Comment by SteafanMrZhou** [comment]
> ![image](https://user-images.githubusercontent.com/58767027/153113731-d6912ad0-1a14-4c1a-94c4-50da0b879e5e.png) @SteafanMrZhou 你这里有很多其他的Controller，能否把这个ISSUE改一下，和PR一致？

收到，我现在修改在，感谢审核。

**Comment by SteafanMrZhou** [comment]
> > ![image](https://user-images.githubusercontent.com/58767027/153113731-d6912ad0-1a14-4c1a-94c4-50da0b879e5e.png) @SteafanMrZhou 你这里有很多其他的Controller，能否把这个ISSUE改一下，和PR一致？
> 
> 收到，我现在修改在，感谢审核。

已经同步修改了ISSUE，感谢您的审核。

**Comment by SteafanMrZhou** [comment]
已同步修改了ISSUE，烦请审核下哈，谢谢 @realJackSun

**Comment by KomachiSion** [comment]
Relative and move to #8308
