### ISSUE TITLE
nacos2.0和dubbo3.0在springboot中如何使用长连接，有没有demo

### ISSUE THREAD

**Issue by gang0713** [alibaba/nacos#7395]
nacos2.0和dubbo3.0在springboot中如何使用长连接，有没有demo

**Comment by MajorHe1** [comment]
使用 nacos 2.x 的版本注册临时服务（ephemeral =  true）就默认用的grpc长连接

**Comment by ToryZhou** [comment]
我也想要 dobbo 3.0.4 注册到nacos 2.0.3的例子，我试了注册不成功

**Comment by gang0713** [comment]
> 使用 nacos 2.x 的版本注册临时服务（ephemeral = true）就默认用的grpc长连接

没有看到那里有说明这个配置是使用长连接呀。
