### ISSUE TITLE
How does a service instance get current instance information

### ISSUE THREAD

**Issue by moil-xm** [alibaba/nacos#7397]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)

How does a service instance get current instance information
Or the list of service instances that you get how do you determine which of them is the information for the current instance

一个服务实例如何获取当前实例信息
或者是 获取的服务实例列表 如何判断其中那个是当前实例的信息

**Comment by MajorHe1** [comment]
没有理解具体什么意思。
如果一个实例想要获取自己的实例信息，该实例在注册上去的时候就自己初始化了instance信息，这个肯定是自己知道的。
如果程序里用了什么框架，底层实现了对instance的初始化和注册，那应该看代码是怎么封装的。
再不济，服务发现获取了该服务的所有实例列表，遍历看哪个实例的ip跟当前实例一致，那就是当前实例的信息。但这个方法不推荐，因为nacos 2.x基于连接的特性完全有可能同一个ip注册多个实例（使用不同的namingService即可）。
