### ISSUE TITLE
做配置中心启动报错

### ISSUE THREAD

**Issue by youyong1979** [alibaba/nacos#7405]
我是参照这个文档做的：https://blog.csdn.net/qq_31457665/article/details/115919711
nacos服务器用的http://8.129.78.48:8848/nacos
注解：@Value-->@NacosValue
启动报错：[NACOS SocketTimeoutException httpGet] currentServerAddr:http://localhost:8848， err : connect timed out

**Comment by li-xiao-shuang** [comment]
配置文件中填写的服务端地址是什么？

**Comment by youyong1979** [comment]
spring:
  application:
    name: ras-api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 8.129.78.48:8848/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 做配置中心启动报错 (Issue #7405)





 
配置文件中填写的服务端地址是什么？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by li-xiao-shuang** [comment]
> spring: application: name: ras-api-gateway cloud: nacos: discovery: server-addr: 8.129.78.48:8848/
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/nacos" ***@***.***&gt;; 发送时间:&nbsp;2021年12月13日(星期一) 中午11:12 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alibaba/nacos] 做配置中心启动报错 (Issue #7405) 配置文件中填写的服务端地址是什么？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

server-addr: 8.129.78.48:8848
把/ 去掉再试试呢？

**Comment by li-xiao-shuang** [comment]
> 启动报错：[NACOS SocketTimeoutException httpGet] currentServerAddr:[http://localhost:8848，](http://localhost:8848%EF%BC%8C) err : connect timed out

启动报错：[NACOS SocketTimeoutException httpGet] currentServerAddr:http://localhost:8848， err : connect timed out
你的日志报的是链接本地  可能是配置没有生效  使用springcloud alibaba 的话 可以把配置放在bootstrap中试试看

**Comment by yanlinly** [comment]
运行目录下 ~/logs/nacos-client最新日志请提交一下

**Comment by zhangjun106203** [comment]
是否grpc端口未开通
