### ISSUE TITLE
Log4j update to  version 2.16.0

### ISSUE THREAD

**Issue by karsonto** [alibaba/nacos#7414]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by li-xiao-shuang** [comment]
我已经移除了 log4j 的依赖

**Comment by karsonto** [comment]
好的👌

**Comment by li-xiao-shuang** [comment]
> 我已经移除了 log4j 的依赖

经过讨论不打算移除了  你可以把pr重新打开嘛

**Comment by karsonto** [comment]
好的，谢谢你提醒～

**Comment by li-xiao-shuang** [comment]
> 好的，谢谢你提醒～

感谢 pr

**Comment by li-xiao-shuang** [comment]
> 好的，谢谢你提醒～

哈喽 朋友  我们准备发布新版本了   需要你在签署一下CLA    在 #7657

**Comment by karsonto** [comment]
Done,thanks
