### ISSUE TITLE
使用自定义的命名空间拿到的配置是null

### ISSUE THREAD

**Issue by fatetop** [alibaba/nacos#7419]
在nacos中新建了命名空间
本地连接的时候可以正常访问新命名空间的数据(使用的是命名空间ID) 
但是部署到服务器上面 就拿不到配置数据不知道是为什么
有大佬遇到这个问题吗
nacos版本是 2.2.1
nodejs是12.22.7

**Comment by caojiele** [comment]
现在最高版本才2.0.3哦～检查下服务器上读取命名空间环境变量的配置文件是否正确。

**Comment by fatetop** [comment]
> 现在最高版本才2.0.3哦～检查下服务器上读取命名空间环境变量的配置文件是否正确。

是 nacos 这个包的版本是 2.2.1   nacos的服务是 2.0.3 没问题 
不读取配置文件
是写死的代码 
我本地可以调用 除了 public 以外的 命名空间的配置 但是服务器上面只能调用public的配置

**Comment by fatetop** [comment]
相同的代码 没有获取配置文件配置 dataID 和 groupID 还有 namespace 都是写死的 本地开发的时候是好好的 可以获取到配置的数据的 但是在服务器上部署的时候就获取不到数据了 获取到的值是 null

**Comment by f-zm** [comment]
也碰到了同样的问题。

**Comment by singletoint** [comment]
使用自定义的命名空间拿到的配置是nul，有解决吗？本地是好的，k8s 里面就不行了，只能拉去到 public 的数据

**Comment by fatetop** [comment]
> 

当时直接restful访问了 没有使用nacos包了
