### ISSUE TITLE
nacos client1.2.1 项目启动时报403

### ISSUE THREAD

**Issue by wowArthas** [alibaba/nacos#7421]
同 issue #4442一样的问题，jar包版本和nacos配置和我其他的项目都一样，其他项目能注册上nacos，但这个新建的项目就一直报403，注册不上

**Comment by li-xiao-shuang** [comment]
是开启auth了吗？

**Comment by wowArthas** [comment]
> 

嗯，username和password都是和之前一样的配的，几个服务都是连的同一个nacos，就我刚新建的这个服务不行

**Comment by wowArthas** [comment]
> 是开启auth了吗？

嗯，username和password都是和之前一样的配的，几个服务都是连的同一个nacos，就我刚新建的这个服务不行

**Comment by li-xiao-shuang** [comment]
> > 是开启auth了吗？
> 
> 嗯，username和password都是和之前一样的配的，几个服务都是连的同一个nacos，就我刚新建的这个服务不行

检查一下你的服务依赖的版本和其他服务是否一致   是springcloud 方式接入的嘛？

**Comment by wowArthas** [comment]
> > > 是开启auth了吗？
> > 
> > 
> > 嗯，username和password都是和之前一样的配的，几个服务都是连的同一个nacos，就我刚新建的这个服务不行
> 
> 检查一下你的服务依赖的版本和其他服务是否一致 是springcloud 方式接入的嘛？

好像是IDEA缓存问题，重启了下IDEA又好了
