### ISSUE TITLE
Hide the namespaces for user who has no access in the page header tabs.

### ISSUE THREAD

**Issue by qngl** [alibaba/nacos#7425]
In v2.0.3, the admin can create user and namespace, then set privileges on the user to some namespaces. Now when I use the created user account in the admin console, I can see all the namespaces, not only the ones I have privileges but also the ones I have no access. 
And if I click on the link, it is saying that "Auth failed". It's not user friendly. So please only show the ones I have access on them.

**Comment by seedscoder** [comment]
@seedscoder will solve it@

**Comment by GOODBOY008** [comment]
@i will fix it@

**Comment by GOODBOY008** [comment]
@li-xiao-shuang Please assigne to me ,Thank you.

**Comment by li-xiao-shuang** [comment]
> @li-xiao-shuang Please assigne to me ,Thank you.

You can put forward your idea first

**Comment by GOODBOY008** [comment]
Class `NamespaceController`'s method `getNamespaces`  does not  check  permission of current user.The console of nacos use annotation `Secured` and  `NacosAuthManager`'s  method `auth` to check permission.

**Comment by zrfan2016** [comment]
Use `Secured `is suitable or get `NacosUser `from `Request `? 
And `NacosUser `add an attribute `Set<String> roles`, in method `getNamespaces `,get roles from NacosUser .
If user is admin ,then get all `TenantInfo `.If not ,query by roles .
After that ,already get all `TenantInfos `,then can create `Namespace `by `TenantInfo`.
@li-xiao-shuang

**Comment by Vassilis-Boubis** [comment]
Is this issue still open?

**Comment by li-xiao-shuang** [comment]
> Class `NamespaceController`'s method `getNamespaces` does not check permission of current user.The console of nacos use annotation `Secured` and `NacosAuthManager`'s method `auth` to check permission. I will add get current user read permission of namespace in class `NamespaceController`'s method `getNamespaces`. @li-xiao-shuang

Have you made any progress

**Comment by zrfan2016** [comment]
Can i sumit my PR   ?

**Comment by li-xiao-shuang** [comment]
> Can i sumit my PR ?

yes，very welcome

**Comment by KomachiSion** [comment]
The auth feature is for check the operation, not check for context. So see all namespace is under expected.

If we want to check the auth for context, we need redesign the auth system. It will cause high changes.
