### ISSUE TITLE
Any user can leave a cluster node in the management UI by clicking Leave button

### ISSUE THREAD

**Issue by qngl** [alibaba/nacos#7427]
1. Create a user who can access public and any other namespace. 
2. Goto ClusterManagement section, choose a node, click the Leave button. Then the node leave the cluster, and I cannot get it back. 

I think the function of ClusterManagement should be limited to non admin users.

**Comment by caomingjie-code** [comment]
@i will solve it@

**Comment by Jepriko** [comment]
Iam newby

**Comment by wangdongyun** [comment]
我已经决定注释掉这个接口了~~ 私有分支，这个下线按钮生产点了下，搞死了~

**Comment by payephyoeaung87** [comment]
Hi

**Comment by gregddmedeiros** [comment]
i need to understand it.

**Comment by payephyoeaung87** [comment]
I don't know who is there now I do not know who is there now CC I do not know who I am now, I do not know where to start because I need a secure internet connection

**Comment by farhad663** [comment]
HelloThis is Farhad Daudzai is anybody communicate with me help me

Sent from Yahoo Mail on Android 
 
  On Mon, 2 May 2022 at 5:18, ***@***.***> wrote:   


I don't know who is there now I do not know who is there now CC I do not know who I am now, I do not know where to start because I need a secure internet connection

**Comment by payephyoeaung87** [comment]
I am in Burma, my internet is under attack.

**Comment by payephyoeaung87** [comment]
Now if this link comes out The Internet is bad english I could not speak yesterday video callcall

**Comment by payephyoeaung87** [comment]
I did not see any phone calls. Call me one of the Feel free to contact me With some kind of internet

**Comment by payephyoeaung87** [comment]
payephyoeaung87@gmail.com.  To Please contact me as an expert in Myanmar language. Please help.

**Comment by rookie-ricardo** [comment]
@i will solve it@

**Comment by rookie-ricardo** [comment]
@KomachiSion 
#8700  已经处理过了
