### ISSUE TITLE
nacos能否考虑配置中心多集群之间数据同步支持？（Can Nacos consider supporting data synchronization between multiple clusters in the configuration center?）

### ISSUE THREAD

**Issue by hujun-w-2** [alibaba/nacos#7434]
**Is your feature request related to a problem? Please describe.**
如果配置需要下发到多个机房，修改配置的时候，需要每个集群都修改一次，如果能做到不同集群之间的配置数据同步会更好。
（If the configuration needs to be delivered to multiple equipment rooms, you need to modify the configuration for each cluster. It is better to synchronize configuration data between clusters.  ）
**Describe the solution you'd like**
虽然数据库这侧可以通过主从实现同步，当时缓存文件这快也可以多集群之间的同步
（While the database side can be synchronized from master to slave, cache files can also be synchronized between multiple clusters  ）
**Describe alternatives you've considered**
拍脑袋方案：增加集群的管理，在配置变更的时候，同时将配置变更事件发送到其他集群，类似集群类配置同步
（Head shot solution: add the management of the cluster. When the configuration is changed, the configuration change event is sent to other clusters, similar to the cluster configuration synchronization  ）

**Additional context**

**Comment by Malikh12** [comment]
Ou télécharger le fichier

**Comment by Leachan129** [comment]
Menjaga akun situs saya aman dr bajak atau hacker

**Comment by hujun-w-2** [comment]
目前想到的方案，大家一起讨论一下：
1.将每个集群的地址，账号等信息，在控制台写入一个配置中。
2.每个集群使用同一个数据库，利用mysql来实现数据同步。
3.新增一个集群配置变化事件。
4.当配置发生变动时，异步向每个集群通过grpc发送集群配置变化事件，发送失败时进行重试（这块可以参照集群内部的配置变更逻辑）。
4.其他集群中某个服务收到配置变更事件时，更新文件缓存。

**Comment by hujun-w-2** [comment]
Let's discuss the current scheme:
1. Write the address, account number and other information of each cluster into a configuration on the console.
2. Each cluster uses the same database and uses Mysql to realize data synchronization.
3. Add a cluster configuration change event.
4. When the configuration changes, send the cluster configuration change event to each cluster asynchronously through grpc, and retry when the sending fails (you can refer to the configuration change logic inside the cluster).
4. When a service in other clusters receives a configuration change event, it updates the file cache.

**Comment by hujun-w-2** [comment]
![image](https://user-images.githubusercontent.com/39894911/146755054-1ad5ea50-084a-4812-a5b8-b408c19e852f.png)

**Comment by li-xiao-shuang** [comment]
> 方案1： 1.每个集群使用不同的数据库 2.将每个集群的地址，账号信息，在控制台写入一个配置cluster config中 3.用户在控制台新增配置时如果选择了同步到其他集群，则继续执行下面的逻辑 4.异步向每个集群通过grpc发送ConfigPublishRequest，发送时根据第一步的集群配置信息，获取grpc连接，并且将连接缓存下来方便下次同步时复用。 5.被通知集群中某个服务收到配置变更请求时，执行原来处理sdk配置变更逻辑。 不支持在 Docs 外粘贴 block 方案2： 1.每个集群使用同一个数据库集群 每个服务定时按照配置更新时间增量从数据库同步 缺点： 1.配置延迟高于方案1 2.不能实现配置同步集群的可选，只能一刀切同步到所有集群

可以考虑以插件或组件的方式来实现嘛

**Comment by hujun-w-2** [comment]
组件形式
cluster-sync组件，代理配置发布请求，根据所选机房再维护任务同步到各个机房
![image](https://user-images.githubusercontent.com/39894911/146758613-07d039a3-a617-47c8-82aa-b4b062697570.png)

**Comment by hujun-w-2** [comment]
但是如果这样的话，还需要保证cluster的高可用才行

**Comment by onewe** [comment]
简单暴力的方式,就整个同步工具,同步配置的时候用一下就行了,没必要一直开着.

**Comment by hujun-w-2** [comment]
就是需要实时同步呀

**Comment by onewe** [comment]
也可以定时向主集群同步

**Comment by hujun-w-2** [comment]
这个就是我上面的方案2了

**Comment by hujun-w-2** [comment]
定时同步延迟会高一点

**Comment by hujun-w-2** [comment]
![image](https://user-images.githubusercontent.com/39894911/146865615-c20d7e3b-b356-4c1f-acd2-2e65ccd5322f.png)
可以配置新增修改删除接口的aop里面做这件事情

**Comment by chuntaojun** [comment]
对于第一方案，应该是问问社区，是不是可以走webhook的形式，将Nacos内部的一些Event通过webhook的方式通知给订阅方

**Comment by Ayoub12321** [comment]
I don't understand this app

**Comment by MasoudMsd** [comment]
:-?

**Comment by hujun-w-2** [comment]
方案1：
1. 以插件的方式来实现集群配置同步功能，插件名：cluster-sync-plugin
2. 通过 nacos-address 进行集群的管理
3. 用户在控制台新增配置时如果选择了同步到其他集群，则继续执行下面的逻辑
4. 拦截配置新增修改删除操作，判断是否引用了 cluster-sync-plugin核心类，如果引用，则异步执行cluster-sync-plugin 逻辑：
  - 通过request中携带需要同步的集群名向 nacos-address 获取集群信息
  - 利用nacos提供给sdk添加配置的grpc端口，异步向每个集群发送集群同步请求，失败重试，重试超过一定次数则打印错误日志。
![image](https://user-images.githubusercontent.com/39894911/150898350-c304e592-2aa7-4968-b2d9-fb65949265a9.png)

方案2：
1.每个集群使用同一个数据库集群
每个服务定时按照配置更新时间增量从数据库同步
缺点：
1.配置延迟高于方案1
2.不能实现配置同步集群的可选，只能一刀切同步到所有集群

**Comment by Gangjean032716** [comment]
Jeff

**Comment by Omonike** [comment]
What is this app all about

**Comment by Mcr12** [comment]
> Ou télécharger le fichier

Osuruktan teyyare selam söyle o yare

**Comment by Dggwhhr** [comment]
*ASDFGHJKL;'
4
';LKJHGFDSASDFGHJ

**Comment by Mrjalol252** [comment]
hi

**Comment by KomachiSion** [comment]
> 对于第一方案，是不是可以走webhook的形式，将Nacos内部的一些Event通过webhook的方式通知给订阅方，即不会无端为Nacos-Server引入多中心的代码，同时也可以自己根据webhook自行扩展相关逻辑

I agree this way, hook plugin is working in Asoc2022, and then we can add an plugin to publish event and other cluster to sub events to get the changes. It's really like the canal.

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/plugin/config-change-plugin/

After nacos 2.3, support config change plugin which can support users implement format check feature by plugin

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/plugin/config-change-plugin/

After nacos 2.3, support config change plugin which can support users implement format check feature by plugin
