### ISSUE TITLE
How can i upgrade log4j-api in nacos server

### ISSUE THREAD

**Issue by pccai** [alibaba/nacos#7436]
Verson: 2.13.3

![image](https://user-images.githubusercontent.com/2232794/146335958-9e7659d0-8082-4d31-aa8a-3a479c26a6e0.png)

tks.

**Comment by onewe** [comment]
@pccai You can just modify here.https://github.com/alibaba/nacos/blob/78f783f55bacefebb00e3161aeeefe77b676f186/pom.xml#L140
