### ISSUE TITLE
address这个模块是否已经废弃不用了

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#7437]
当前的代码貌似没有发现使用address模块。

**Comment by zrlw** [comment]
core模块里虽然有AddressServerMemberLookup，但是貌似和address的controller对应不上，有demo么？

**Comment by kolema-tech** [comment]
> core模块里虽然有AddressServerMemberLookup，但是貌似和address的controller对应不上，有demo么？

可以看`AddressServerControllerTests` 的单元测试用法。


`AddressServerMemberLookup ` 这个类是需要改配置文件的，
```
### MemberLookup
### Addressing pattern category, If set, the priority is highest
nacos.core.member.lookup.type=address-server
```
