### ISSUE TITLE
Nacos web page failed to obtain the application name

### ISSUE THREAD

**Issue by weihubeats** [alibaba/nacos#7453]
**Describe the bug**
Nacos web page failed to obtain the application name
![image](https://user-images.githubusercontent.com/42484192/146702080-9a055f6f-0705-400a-84ac-a4664422b2c8.png)

**Expected behavior**
Correctly display the application name
**Acutally behavior**
App name is displayed as unknown
**How to Reproduce**
spring cloud version
![image](https://user-images.githubusercontent.com/42484192/146701904-3a38b68e-c64c-4e2b-8465-a34bec65586c.png)

**Desktop (please complete the following information):**
 - OS: Client:Apple M1 mac os 12.0.1 
 - Version [e.g. nacos-server 2.0.3, nacos-client 2.0.3]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by onewe** [comment]
You can use `project.name` properties. Add to your java command line.
@weihubeats

**Comment by onewe** [comment]
You can see here: `com.alibaba.nacos.client.utils#getAppName`
![image](https://user-images.githubusercontent.com/38708836/146708535-209588ea-b583-49e1-9687-3d224071ed0f.png)

**Comment by weihubeats** [comment]
Thank you, I thought it was more reasonable to get the spring.application.name property in springboot directly. Is it more reasonable to get spring.application.name directly?

**Comment by onewe** [comment]
Eh, I think so. but the nacos client doesn't depend on the spring, It's a independent library. Perhaps the nacos-spring-project can add this feature.
