### ISSUE TITLE
Nacos client注册provider不能分组？

### ISSUE THREAD

**Issue by tiger822** [alibaba/nacos#7454]
**Describe the bug**
No matter how you configure Dubbo registry, you cannot specify group.

**Expected behavior**
Service provider  can be grouped.

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
The source:
org.apache.dubbo.registry.nacos.NacosRegistry#doRegister, --> namingService.registerInstance(serviceName, instance);

com.alibaba.nacos.client.naming.NacosNamingService#registerInstance(java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)
this.registerInstance(serviceName, "DEFAULT_GROUP", instance); // fixed group name??

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Zonestc18** [comment]
Xxx

**Comment by tiger822** [comment]
依赖版本升对2021.1就行了

Zonestc18 ***@***.***> 於 2021年12月26日 週日 下午10:43寫道：
