### ISSUE TITLE
Change the README.md file, adding the e-book link.

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#7459]

**Comment by sguzowski86** [comment]
https://github.com/realJackSun/nacos/commit/7d1ca3b05ef618496eb20d84edf95c43191a6992
Here is a link to the realJackSun / nacos website

**Comment by naniyerragangu99** [comment]
iam already running code

**Comment by keubb** [comment]
oi

**Comment by Ellendumpa** [comment]
7459

**Comment by Ellendumpa** [comment]
عاوزه ارجع جميل

**Comment by Ellendumpa** [comment]
حد يساعدني

**Comment by kanwalbou** [comment]
Jaazcash

**Comment by Maricruzhdz** [comment]
Qqq

**Comment by Dyzinto** [comment]
> _No description provided._

README.md

**Comment by Dyzinto** [comment]
] Change the README.md file, adding the e-book link.

**Comment by Anacarladossantos** [comment]
Vamos altera  o arquivo ReADME.md,e adicionando o link do e-book

**Comment by Kay-Ceee** [comment]
Please follow me I have a lot instored 🥺🦋🤧

**Comment by Mikecarbon** [comment]
Config\READ.e-book.md

**Comment by halid55** [comment]
I started my project

**Comment by Adnanfir14** [comment]
#7459

**Comment by Adnanfir14** [comment]
#7459

**Comment by Dariinkaa** [comment]
#7669 
Duplicate of #

**Comment by labareda09** [comment]
opaa

**Comment by rookie-ricardo** [comment]
@i will solve it@

**Comment by rookie-ricardo** [comment]
“https://github.com/ready to close@”
