### ISSUE TITLE
It is recommended that the nacos console use namespaceid as the login username.

### ISSUE THREAD

**Issue by 18980808191** [alibaba/nacos#746]
现状：
1、目前nacos控制台用户只能在数据库创建，不适用。
2、用户没有管理员和普通用户的区分。
3、多个项目共用一个nacos配置注册中心时，nacos配置文件容易被其他同事更改，导致系统故障。
分析：
 多租户隔离很必要，各个项目只能更改自己租户内的配置文件。
实现：
1、建议将namespaceId作为租户。管理员在新建namespace时,增加密码，将namespaceid作为租户id，并用于登录控制台，身份为普通用户。
2、租户角色分为普通和管理员。普通角色只能操作自己租户的配置，管理员可以操作所有的配置及创建新租户。

**Comment by nkorange** [comment]
Can be considered with #1105
