### ISSUE TITLE
nacos和keepAlived部署在一个机器的时候，nacos无法使用

### ISSUE THREAD

**Issue by shiyezheng** [alibaba/nacos#7464]
**Describe the bug**
用4台服务器部署了nacos集群，绑定了4台机器的内网ip，由于节省成本，需要在其中两台机器上部署keepAlived，生成一个外网vip，请求通过这个vip接入进来。从理论上讲，外网vip和nacos用的内网ip应该是不影响的，但实际验证发现nacos也尝试绑定这个vip，导致nacos集群都不可用了。

**Comment by stephenZkang** [comment]
开启arp抑制

**Comment by shiyezheng** [comment]
麻烦详细说下怎么开启
________________________________
发件人: 乔@康 ***@***.***>
发送时间: 2021年12月31日 13:35
收件人: alibaba/nacos ***@***.***>
抄送: aaronshi ***@***.***>; Author ***@***.***>
主题: Re: [alibaba/nacos] nacos和keepAlived部署在一个机器的时候，nacos无法使用 (Issue #7464)


开启arp抑制

―
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falibaba%2Fnacos%2Fissues%2F7464%23issuecomment-1003275456&data=04%7C01%7C%7C36b26bf126b24899fde408d9cc1f4ceb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765257087515745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HECS9j7ZRXMeJJNk9Z92PmC%2FiGMwI%2BvDEMVastMRa4g%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABLTFW4ZUS4CWHP2ITOSEITUTU6IRANCNFSM5KPEFLMQ&data=04%7C01%7C%7C36b26bf126b24899fde408d9cc1f4ceb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765257087515745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k99DYnSdkIEIcIikNSp95gi%2ByEiPopYXmUhZwB61hv0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C36b26bf126b24899fde408d9cc1f4ceb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765257087671972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZzcRufxcNgqDRVOFs35IxBEyWelt0t4MCy6SlS1ohd8%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C36b26bf126b24899fde408d9cc1f4ceb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637765257087671972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DQYCg72dvuFW14uGmR3lZBHPZjz1GaWa2gTa%2BJYbNKA%3D&reserved=0>.
