### ISSUE TITLE
upgrade log4j to 2.17.0 for develop 

### ISSUE THREAD

**Issue by dislazy** [alibaba/nacos#7468]
<!-- Here is for bug reports and feature requests ONLY! 

If you're looking for help, please check our mail list、WeChat group and the Gitter room.

Please try to use English to describe your issue, or at least provide a snippet of English translation.

log4j non-secure version

**Describe the bug**

log4j non-secure version

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by li-xiao-shuang** [comment]
暂时先不着急升 在观察下log4j的情况  升级需要把1.x-develop也处理下

**Comment by li-xiao-shuang** [comment]
可否在提个pr 把 v1.x-develop也修复下？
