### ISSUE TITLE
version 2.0.3 is not support chinese path 

### ISSUE THREAD

**Issue by HoneyYan** [alibaba/nacos#7471]
**Describe the bug**
can't support chinese path
**Expected behavior**
should support chinese path

**Acutally behavior**
when I start nacos server in chinese path is faile.

**How to Reproduce**
1. install nacos-2.0.3 in chinese path;
2.use command "startup.cmd -m standalone" start nacos server;
3.throw exception and start faile;
4.when I use english path is ok;

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Version [e.g. nacos-server 2.0.3]

**Additional context**
![image](https://user-images.githubusercontent.com/17638362/146907098-3820e8ac-e72b-4eec-9c43-fe6fa5835680.png)

**Comment by onewe** [comment]
Eh, It looks like RocksDB's problem.
