### ISSUE TITLE
注册中心在应用服务后启动时，首次鉴权会提示unknown user!

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#7481]
**Describe the bug**
本机测试1.4.2nacos注册中心，默认Derby数据库，开启鉴权， 开启了nacos.core.auth.cacheing.enable。
如果应用先于注册中心启动，那么首次鉴权80%的概率会失败，提示unknown user!
debug跟踪nacos注册中心可稳定复现，异常抛出代码位置在```org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider```151行，原因是retrieveUser查询nacos用户时抛UsernameNotFoundException，分析是derby数据库尚未完成初始化，数据库没有nacos记录。

**Comment by zrlw** [comment]
还有一些其他问题：
ConfigController.publishConfig方法有```@Secured```注解，需要鉴权，但是应用先启动时，发送的请求既没有accessToken，也没有username和password，导致鉴权失败。

**Comment by zrlw** [comment]
换成mysql，也是如此，注册中心运行在standalone模式。

**Comment by zrlw** [comment]
原因找到了，NacosUserDetailsServiceImpl的reload方法在启动后5秒初始化userMap，如应用先于注册中心启动，在reload方法执行前注册中心大概率会收到nacos client的login请求，此时userMap为空，因为cacheEnable设置为true（为了提高鉴权处理效率），userMap为空也不从数据库读，所以找不到用户。

**Comment by MajorHe1** [comment]
already fix by #6204

**Comment by zrlw** [comment]
> already fix by #6204

1.x没有人管了吧
还有我看了6204的修复方式，不敢苟同，username如果就是没有，再去数据库里取也取不到，白白浪费时间

**Comment by MajorHe1** [comment]
1.x应该继续在维护吧，只是最近官方团队忙，理不过来。

去数据库取一次是为了解决，通过控制台或者数据库新增了用户信息，还没有同步到内存中时（addRole接口并没有add进内存），客户端过来的请求不至于鉴权失败。

用PostConstruct的方式需要验证一下，调用reload方法的时候操作数据库的对象是否都已经准备好了。这个我并不知道它们的初始化顺序，所以就请赐教了。

**Comment by zrlw** [comment]
赐教实不敢当，只是探讨一下，PostConstruct这个相当于在注册中心对外提供服务前完成userMap缓存初始化，我们实际测试过了，应该没有问题。
之所以开启cache，是因为我们在运行期间基本没有增加nacos用户的需求，即使增加用户，15秒后生效我们也可以接受，其二是我们注册实例数量过万，曾经出现过部分实例的nacos用户密码配置错误频繁访问数据库导致注册中心崩溃的问题，所以我们的应用对nacos访问数据库的频率敏感。

**Comment by MajorHe1** [comment]
其实我之前提过把 initialDelay 改成 0 的方案，也实际测试过没有问题，但是貌似官方不认可这样的改动，see #6142

我们只能从实践上判断“应该没有问题”，但其实还是不知道操作数据库的对象初始化和这里postconstruct的执行顺序，这一块属实知识短板了。

> 应用对nacos访问数据库的频率敏感 

倒是提醒了我， #6204 这一块还有优化的空间，从数据库加载上来的数据set到内存中，减少对数据库的访问

**Comment by zrlw** [comment]
我们考虑的还有配错了用户名的情况，我们并不打算继续使用社区版本了，因为很多优化策略可能并不是适合所有应用场景，比如鉴权，我们打算用有效期限自动清除功能的token缓存减少鉴权消耗的CPU资源，以及依据token缓存进行的实例纬度鉴权校验等等，这些功能未必适合其他应用，所以没有提交

**Comment by zrlw** [comment]
autowired注入和postconstruct的先后顺序是确定的，注入autowired对象是构建对象的过程，对象构建好了才执行postconstruction

**Comment by zrlw** [comment]
schedule是异步执行的，即使initialdelay设置为0也不能保证在Login请求之前执行。

**Comment by MajorHe1** [comment]
其实我们这边用的也不是社区版本，也自己实现了一版token缓存方案，否则因为token的存在QPS只能上到2000左右。这个问题以前社区讨论过，就是鉴权并不是nacos的核心功能，nacos目前只提供一个基础的简单实现。只不过现在nacos不方便扩展，后续改成插件化架构后应该可以更方便的支持用户自定义鉴权实现。

> autowired注入和postconstruct的先后顺序是确定的，注入autowired对象是构建对象的过程，对象构建好了才执行postconstruction
> schedule是异步执行的，即使initialdelay设置为0也不能保证在Login请求之前执行。

受教了。
