### ISSUE TITLE
push configuration without auth！！That would be a huge risk

### ISSUE THREAD

**Issue by shy-stone** [alibaba/nacos#7492]
**Describe the bug**
When I push some configuration to Nacos, I am not required any authenticate the interface, in other words, anyone can modify my configuration without authentication!!! That would be a huge risk hole
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
https://nacos.io/en-us/docs/auth.html

nacos provide a simple demo for auth, if you has other auth request, you should develop based on nacos source codes.
