### ISSUE TITLE
k8s 部署 nacos集群，在一定条件下，会出现配置文件错误

### ISSUE THREAD

**Issue by iwfun** [alibaba/nacos#7493]
故障表象
所有服务突然不能进行心跳上报

1.怀疑Nacos资源不足
有一个Pod资源占用不高（怀疑挂掉了），另外两个Pod资源占用很高，增加到5个Pod问题依旧

2..集群配置错误
询问社区人员，告知集群配置可能存在异常 ，“那就是集群搭建的有问题， distro协议认为请求非法了”
检查配置信息如下

![image](https://user-images.githubusercontent.com/26781465/147216279-4128eeb9-0ede-4d62-ae47-821ce45e3aae.png)
确实配置出问题了（多了个点），但是这个配置...我们并不知情

追查得知该配置是由项目 nacos-peer-finder-plugin  维护的，该项目目的是为了让nacos支持动态扩容（缩容）

后续
网络同事发现 nacos-2 早上自动重启了2次后，开始报上述错误（开始多了一个点）

原因未明白，麻烦看看 谢谢了

**Comment by MajorHe1** [comment]
nacos k8s 的问题，建议去这里提issue看看？

**Comment by iwfun** [comment]
> nacos k8s 的问题，建议去这里提issue看看？ https://github.com/nacos-group/nacos-k8s/issues

谢谢，已经去那边建了
