### ISSUE TITLE
nacos控制台登录界面不用密码可以直接进入BUG

### ISSUE THREAD

**Issue by SvenNJ** [alibaba/nacos#7494]
1、版本：2.0.3
2、必现
3、登录地址： http://xxxx:8848/nacos
4、复现步骤： 多次点击左上角的 NACOS  图标， 可以直接进入系统，无需输入密码

**Comment by MajorHe1** [comment]
服务端没有打开鉴权吧

**Comment by li-xiao-shuang** [comment]
> 1、版本：2.0.3 2、必现 3、登录地址： http://xxxx:8848/nacos 4、复现步骤： 多次点击左上角的 NACOS 图标， 可以直接进入系统，无需输入密码

我尝试了下  开启鉴权是没有这个问题的  未开启鉴权的情况下确实是可以通过频繁点击然后进入的 ，这个可能是页面上的一个问题

**Comment by GKGMK11** [comment]
Leave a comment

**Comment by SvenNJ** [comment]
好的👌
