### ISSUE TITLE
Version 2.0.1 does not have an import button

### ISSUE THREAD

**Issue by danieLkin2** [alibaba/nacos#7495]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by danieLkin2** [comment]
Version 2.0.1 does not have an import button

**Comment by li-xiao-shuang** [comment]
> 

Nacos 2.0.1 doesn't have an import button?

**Comment by realJackSun** [comment]
@danieLkin2 We cannot reproduce it, can you show your console.
