### ISSUE TITLE
这广告，太过分了！！！

### ISSUE THREAD

**Issue by cn-src** [alibaba/nacos#7496]
一个空的 Maven 工程，就全局的 settings.xml 里面配置了阿里云的镜像。
但是就这样能把广告打到了构建工具里就太过分了吧？我能认为这是病毒入侵么？
![image](https://user-images.githubusercontent.com/8263180/147247954-c83d633d-1f36-4348-8057-bd94973f7fe5.png)

**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by linghengqian** [comment]
This is just an Info-level log, I don't think there is anything wrong with this. In fact, you can see this behavior in many projects, a typical example is that `ATOMIKOS` also has this kind of introduction.

**Comment by KomachiSion** [comment]
The project is your own project, and the setting is also your own setting. It has nothing to do with the nacos community. The issue will be closed.
