### ISSUE TITLE
springcloud alibaba + nacos + dubbo 先启动消费方再启动提供方 可正常调用 此时 重启提供方 则@DubboReference远程调用服务失败，但使用ReferenceBean api 可以正常获取代理对象调用

### ISSUE THREAD

**Issue by dhais-rs** [alibaba/nacos#7497]
版本 ：
spring-cloud-alibaba-dependencies 2.2.5.RELEASE
dubbo 2.7.8

**Comment by itbac** [comment]
我是 使用  spring-cloud-alibaba-dependencies 2.2.6.RELEASE  。你试试 。 
[https://mp.weixin.qq.com/s?__biz=Mzg5NDU5NDY1OA==&mid=2247483812&idx=1&sn=63c7d15f03711ee38510dfebc92943c3&chksm=c01c7aa9f76bf3bff1b09a7e4b0247c6f48e0c3846ecf23456283c8fdcd3c3e56182406c2820&token=2031399015&lang=zh_CN#rd](我遇到一个并发修改异常的问题)

**Comment by dhais-rs** [comment]
> 我是使用 spring-cloud-alibaba-dependencies 2.2.6.RELEASE 。你好好利用。 `https://mp.weixin.qq.com/s?__biz=Mzg5NDU5NDY1OA==&mid=2247483812&idx=1&sn=63c7d15f03711ee38510dfebc92943c3&chksm=c01c7aa9f76bf3bff1b09a7e4b0247c6f48e0c3846ecf23456283c8fdcd3c3e56182406c2820&token=2031399015&lang=zh_CN#rd`

试了一下 没有起作用 。。。。。

**Comment by dhais-rs** [comment]
终于解决了，看了其他issue 把dubbo版本升级到2.7.10以上修复了这个问题。
