### ISSUE TITLE
Maybe rename instanceFilter.js to InstanceFilter.js because some machines are case sensitive.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#7498]
Some machines are case sensitive.
so
console-ui/src/pages/ServiceManagement/ServiceDetail/instanceFilter.js
to
console-ui/src/pages/ServiceManagement/ServiceDetail/InstanceFilter.js

After renaming, build main.js without any changes.

**Comment by li-xiao-shuang** [comment]
You can try to deal with it

**Comment by CherishCai** [comment]
But now main.css and main.js not the newest in v1.x-develop?  When `npm run build` will get new files.

**Comment by ilaotan** [comment]
after rename, centos build is ok
