### ISSUE TITLE
Some sugestions for nacos

### ISSUE THREAD

**Issue by paderlol** [alibaba/nacos#75]
#### Suggestions

In the process of making the docker image, I found some points that could be improved,as follow:

- I think we need to refactor the startup.sh, preferably to build a script for docker containers. For example, remove the JAVA_HOME judgment function from the script,write as many common env variables as possible in the **dockerfile**

   In a docker environment, you don't need to worry about different systems, so we don't care about the JDK version or whether there are environment variables configured

- Unifying the contents of different versions of startup scripts, I found that the 0.1.0 and 0.2.0-rc1 scripts were different.

- There are no log files that specifically record startup errors, such as database connection failures and registering connection IP

- Finally, I don't quite understand why we don't use the **spring. config.additional -location**  instead of **spring. config.location**

#### conclusion

 emm....   that's all my found

**Comment by yanj0609** [comment]
spring.config.additional-location is an alternative way to assign custom external configuartion location. 
spring.config.location works here as well as spring.config.additional-location. But the later is more simple and direct.

I think i will create to a pull request to improve it later after some tests. Thanks your suggestions.
