### ISSUE TITLE
getConfig value return null without error but  real value is not null

### ISSUE THREAD

**Issue by slievrly** [alibaba/nacos#750]
nacos-sample:
![image](https://user-images.githubusercontent.com/8758457/52620329-3f886980-2edf-11e9-9a8b-0a8b6d5f3004.png)
![image](https://user-images.githubusercontent.com/8758457/52620428-84140500-2edf-11e9-9f96-b054378f3bae.png)

**Comment by TsingLiang** [comment]
1.check if the nacos is report error log.
2.check configuration dataId group is right

**Comment by a421134331** [comment]
请问解决了不？  我也遇到了同样的问题，  nacos无error日志，  dataId&group 也是正确的
