### ISSUE TITLE
nacos-client 获取IP方法BUG 导致nacos集群运行一段时间后就假死雪崩

### ISSUE THREAD

**Issue by xiongchaogithub** [alibaba/nacos#7501]
- 操作系统: Linux (3.10.0-1127.el7.x86_64)
- 体系结构: amd64 64bit
- Java 主目录: /usr/java/jdk1.8.0_251/jre
- ava 版本: 1.8.0_251
- VM: Java HotSpot(TM) 64-Bit Server VM (25.251-b08, mixed mode)
- Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1和1.1.3]
- Module [e.g. naming/
- 
[
![MAT异常类分析](https://user-images.githubusercontent.com/34825350/147378592-407c7461-db03-4674-8805-269846c572ce.jpg)

**
![MAT异常分析变量](https://user-images.githubusercontent.com/34825350/147378590-916533eb-051f-4200-b4a2-01168a62ca3a.png)

       1.从堆栈信息上面来时由于应用有大量的服务实例查询请求阻塞 GET /nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=rights&clientIP=resolve_failed 

![客户端获取IP方法](https://user-images.githubusercontent.com/34825350/147378593-354cc87a-b7f1-422d-bb02-be5e809cd3ca.jpg)
       2. IP获取方法捕获到了异常 但是没有处理异常。可以参看 spring-cloud-alibaba-nacos-discovery 中获取IP的方法。
       
![线程具体阻塞的方法](https://user-images.githubusercontent.com/34825350/147378596-526eba9b-1b15-4441-b1d2-0e25f6b8b461.jpg)
![引起线程阻塞的业务](https://user-images.githubusercontent.com/34825350/147378598-62cdd637-c210-46b4-a7d4-91707db4c7d1.png)
       3.客户端将错误的IP【clientIP=resolve_failed】发送到了服务端，导致JDK8  checkLookupTable方法在特殊的情况下锁【图片：线程具体阻塞的方法】。导致checkLookupTable方法死锁的原因，这个有可能和JDK本身的BUG有关，可以参考：https://wiki.zimbra.com/wiki/Configuring_for_IPv4。

       
![系统环境1](https://user-images.githubusercontent.com/34825350/147378594-7648b85c-99ff-4480-a68b-633a8f889946.png)

![系统环境2png](https://user-images.githubusercontent.com/34825350/147378595-19837aa1-c98e-4575-916a-7e7f61f21ca8.png)

](url)

 基于上面的异常，提出几点不太成熟的建议：

      1.完善客户端获取IP的方法或者处理捕获到的异常

      2.对客户端和服务端的http请求和socket链接增加超时的处理。

      3.针对JDK本身的BUG做一个规避的方案。【参考：https://wiki.zimbra.com/wiki/Configuring_for_IPv4】

**Comment by CherishCai** [comment]
nacos-client 1.4.1  是有一个类似的 bug，建议看下 1.4.2 的 release note 是否对应。

**Comment by xiongchaogithub** [comment]
按照您的建议了解了一下 1.4.2 的 release note 确实有好几个BUG和这个获取本地IP方法相关。同时也了解了一下2.0.3版本对应的相关部分，2.0.3版本已经做了完善处理。
