### ISSUE TITLE
Xxx

### ISSUE THREAD

**Issue by Zonestc18** [alibaba/nacos#7504]
Xxx

_Originally posted by @Zonestc18 in https://github.com/alibaba/nacos/issues/7454#issuecomment-1001193680_

**Comment by li-xiao-shuang** [comment]
> Xxx
> 
> _Originally posted by @Zonestc18 in [#7454 (comment)](https://github.com/alibaba/nacos/issues/7454#issuecomment-1001193680)_

Please revise the title
