### ISSUE TITLE
naocs not work fine on spring-boot-2.1.x

### ISSUE THREAD

**Issue by morisenmen** [alibaba/nacos#751]
nacos:0.8.0 
nacos-spring-boot-starter:0.2.1
spring-boot-starter:2.1.x
dubbo:2.6.5
use this  combination,we could not start dubbo rest protocol.
because spring-boot-starter upgrade tomcat-embed,there is a Connection.setProtocol has been deleted from tomcat-embed 9.

**Comment by TsingLiang** [comment]
what is the problem?

**Comment by morisenmen** [comment]
this is the error message:
An attempt was made to call the method org.apache.catalina.connector.Connector.setProtocol(Ljava/lang/String;)V but it does not exist. Its class, org.apache.catalina.connector.Connector, is available from the following locations:

**Comment by morisenmen** [comment]
It's a issue for dubbo 2.6.5
