### ISSUE TITLE
这段代码使得注册中心地址缺少最后一个字符

### ISSUE THREAD

**Issue by cxxwl96** [alibaba/nacos#7517]
![image](https://user-images.githubusercontent.com/54365686/147588739-232abb74-155d-4a28-8b22-f3f3006a212e.png)

**Comment by cxxwl96** [comment]
2.1.0.RELEASE

**Comment by onewe** [comment]
@onewe will solve it@

**Comment by onewe** [comment]
I have seen this code at the spring-cloud-alibaba. The latest version has already fixed.  @cxxwl96

**Comment by KomachiSion** [comment]
Please move issue to SCA community.
