### ISSUE TITLE
Count(*) costs too much time, could you please optimize it?

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#7519]
**Describe the bug**
In the ExternalStoragePersistServiceImpl class, there is a count(*) operation, it costs too much time.
![image](https://user-images.githubusercontent.com/58767027/147632650-61a6556f-951b-4f58-8def-f312a3b966e4.png)
It is used to clean the history table:
![image](https://user-images.githubusercontent.com/58767027/147632707-ca9ba9cd-300a-4c03-8342-3b8d56df01a2.png)

But actually the cleaning operation can be optimized by a batch operation.

**Expected behavior**
A more fast cleaning operation in DumpService.

**Comment by hujun-w-2** [comment]
@i will solve it@

**Comment by caomingjie-code** [comment]
count(*) = count(number) > count(字段)。这个地方我认为没有必要优化。
官方解释：https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_count
InnoDB handles SELECT COUNT(*) and SELECT COUNT(1) operations in the same way. There is no performance difference.
