### ISSUE TITLE
什么时候优化下nacos-client包，居然有14m

### ISSUE THREAD

**Issue by 501956430** [alibaba/nacos#7520]
什么时候优化下包大小，简直天花板了
<img width="1232" alt="截屏2021-12-29 15 11 33" src="https://user-images.githubusercontent.com/20204491/147636491-7fdd859c-3784-4b6a-8a36-9ea6255ab583.png">

**Comment by li-xiao-shuang** [comment]
确实有点大  目前有啥影响嘛？

**Comment by 501956430** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zzq1314zll** [comment]
@501956430 @li-xiao-shuang 伙计我看现在2.1.0的cliet包已经很小了，之前依赖了许多的第三方依赖去除之后小了很多

**Comment by KomachiSion** [comment]
Refer to #8840
