### ISSUE TITLE
生产集群环境，是选择使用derby，还是mysql

### ISSUE THREAD

**Issue by magicgw0928** [alibaba/nacos#7521]
生产集群环境，是选择使用derby，还是mysql作为数据源，哪个靠谱一些？还是都可以？
我试了内置derby启动集群模式，节点间数据都是可以同步的，重启后也都同步。现在有些纠结，选择哪个比较好？是否有大牛可以简单分析一下2种数据源的利弊？

**Comment by li-xiao-shuang** [comment]
个人感觉Mysql会好一点  排查问题、查询信息方便一些
