### ISSUE TITLE
nacos集群模式多节点：同一个实例，不同的节点查出来的心跳时间不一致

### ISSUE THREAD

**Issue by bangbang2333** [alibaba/nacos#7526]
**Describe the bug**
实例的心跳时间没有实时同步。

**Expected behavior**
本地部署nacos集群模式，有三个节点。注册了一个实例上去，节点之间成功的同步了这个实例的信息。查询实例的详细信息的时候，所有节点查出来的该实例的心跳时间应该是一样的。

**Acutally behavior**
本地部署nacos集群模式，有三个节点。注册了一个实例上去，节点之间成功的同步了这个实例的信息。但是查询实例的详细信息的时候，只有责任节点的心跳时间是实时更新的，其他节点查出来的心跳时间没有变化。（需要触发事件才能重新同步心跳时间）

**How to Reproduce**

![截屏2021-12-30 上午11 29 51](https://user-images.githubusercontent.com/43024629/147719553-edf0faa6-866d-4999-8745-fb56f2205502.png)

**我的解决思路**
![截屏2021-12-30 上午11 33 16](https://user-images.githubusercontent.com/43024629/147719677-a616b776-49a1-43b0-b1e9-dc11f51bfaf5.png)

**Comment by MajorHe1** [comment]
CatalogController 这个接口应该还好，印象中只有控制台页面在访问这个接口，量不大就没事。

**Comment by bangbang2333** [comment]
自己顶自己
