### ISSUE TITLE
Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html. 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271)

### ISSUE THREAD

**Issue by GitTigers** [alibaba/nacos#7529]
https://github.com/alibaba/nacos/issues/6791#issue-986953608

Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html. 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271)

可以看到他使用的是2.0.3的版本，请问本来就是2.X的版本还需要升级吗
我也遇到了相同的问题，如果需要某个开关才能open 2.0 mode，请给一个具体的链接。在官方的文档并不能找到具体的操作步骤。
谢谢。

**Comment by vividfish** [comment]
检查下你的/home/{userName}/nacos是不是有1.x的数据。如果有nacos会对这些数据升级

**Comment by GitTigers** [comment]
你好 我之前没有安装部署过nacos 我直接使用的nacos的2.0.3的镜像进行了部署 所以道理上不可能存在1.X的数据 但是为了排除您的疑虑 我还是重新开了一个新的数据库 里面没有数据 直接使用nacos包中的sql文件新建数据库 但是还是出现了那个错误。

**Comment by MajorHe1** [comment]
这个升级不是说升级nacos的版本，而是 nacos 2.0.x为了兼容 nacos 1.x 和 nacos 2.x，首先会以1.x的模式启动，然后向其他节点检查是否都升级至2.x模式完毕了，如果都升级完毕了，再切换成 2.x的模式，在这之后才可以接受GRPC请求 。
出现这个问题，说明要么集群构建的方式有问题，要么集群网络通信有问题。建议：
1、删除 {nacos.home}/data 目录然后重启，或者重新部署镜像，跟数据库里面有没有数据没有关系
2、如果上面不能解决问题，集群每个节点都调用该方法，强制开始2.x模式
![image](https://user-images.githubusercontent.com/53824889/147800056-8496d646-db39-4ef1-a21b-0345802c70bd.png)

**Comment by GitTigers** [comment]
你好 我查看了那个日志文件 似乎找到了问题的关键 升级步骤已经启动 但是没有升级成功 请看下面日志
![image](https://user-images.githubusercontent.com/50431798/147807234-41dd90eb-5b8c-48fe-b015-25859b1f3497.png)

**Comment by MajorHe1** [comment]
日志是这里抛出来的，看样子还是网络通信失败
![企业微信截图_16409330773922](https://user-images.githubusercontent.com/53824889/147808105-e99394fd-d98f-41cb-9950-1346244c9593.png)
复杂的办法：逐个节点手动调这个接口看看有没有问题，如果没有问题，再排查K8S网络层面的原因，因为你用的域名而不是ip
简单的办法：逐个节点关闭双写，强行开启2.x模式。

**Comment by dockeryun** [comment]
我觉得这种机制害死人，是否有方法改进。

**Comment by PFyyh** [comment]
我也遇到过这个问题，大概率集群配置问题，检查一下cluster.conf文件，并检查集群设置上线情况。我设置localhost不同端口，导致部分节点无法上线，注册服务失败。

**Comment by dockeryun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by PFyyh** [comment]
我也遇到过这个问题，大概率集群配置问题，检查一下cluster.conf文件，并检查集群设置上线情况。我设置localhost不同端口，导致部分节点无法上线，注册服务失败。

**Comment by limeng3150** [comment]
我也遇到了Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.

每次我启动一个服务节点偶发性的出现这个错误，然后我只能去再次的重启我的服务，才恢复正常

**Comment by yanlinly** [comment]
检查一下集群每个节点中cluster.conf配置文件，看看自己升级的节点是否在这个文件中，需要保证这个文件内容正确。

**Comment by java-aodeng** [comment]
我也遇到了，项目里面2.0.3 nacos集群三个都是2.0.3 版本都是一致的。有时候报错，有时候不报错
![lQLPDhtvXhapla7NAtjNBqKw5xTAipbmBPsChyNEMwC8AA_1698_728](https://user-images.githubusercontent.com/35907367/168994748-bdd71309-6039-47ac-9eb2-10211abc8169.png)

**Comment by dockeryun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by java-aodeng** [comment]
> 我也遇到了，项目里面2.0.3 nacos集群三个都是2.0.3 版本都是一致的。有时候报错，有时候不报错 ![lQLPDhtvXhapla7NAtjNBqKw5xTAipbmBPsChyNEMwC8AA_1698_728](https://user-images.githubusercontent.com/35907367/168994748-bdd71309-6039-47ac-9eb2-10211abc8169.png)

解决了，隔壁项目组里面用的1.0，用我们的2.0的集群，平滑降级了[大狗头]

**Comment by hillbun** [comment]
可以在NACOS启动JVM增加参数 -Dnacos.core.support.upgrade.from.1x=false 实现吗

**Comment by dockeryun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by BrucerTao** [comment]
我也出现了这种情况，然后执行关闭了双写之后业务代码启动正常。
但是想问下，修复之后会不会出现原先注册的或者新注册的grpc接口有影响的情况

**Comment by beausoft** [comment]
关闭双写后正常了

**Comment by dockeryun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zyhui98** [comment]
> 关闭双写后正常了

我也是。

**Comment by dockeryun** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
