### ISSUE TITLE
Is there a plan to implement, the local configuration overrides the remote configuration, and the requirement is that the developer temporarily adjusts the configuration.

### ISSUE THREAD

**Issue by AaronChen2012** [alibaba/nacos#753]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nanamikon** [comment]
I think this issus related to spring not nacos，  you can add a new profile for dev or special local configuration with SpringBootTest

**Comment by AaronChen2012** [comment]
比如有两个开发人员对应一个spring boot对开发，都使用了 dev profile。其中一个开发人员可能因为特殊情况要修改下某个配置，这个需求还是存在的。spring cloud config 是支持覆盖远程的开关控制的！
