### ISSUE TITLE
获取nacos 上的配置文件数据偶尔为空

### ISSUE THREAD

**Issue by dach-wh** [alibaba/nacos#7530]
问题：获取nacos 上的配置文件数据偶尔为空（真实业务场景）
背景：用户程序直接裸调用 configService.getConfig(dataId, group, 5000) 获取配置 ，未配置监听器异步刷新配置
根本原因：本地缓存文件并发读写非线程安全，读文件时，有线程在写文件，导致获取数据为空
分析 之 nacos client 读取配置流程：
1. 读本地配置文件 
2. 有则返回，无则 访问 nacos server
3. 访问 nacos server ：限流检测（client 端 sdk 限流，5r/s），超速，返回401，读取本地缓存文件；未超速，发生请求到 nacos server，写本地缓存，返回

上述问题逻辑阐述：首次读取，成功，写缓存文件 -> 速率超过5r/s ，读取缓存文件 ; 1s 后 限速解除，此时 A 线程读缓存文件，B 线程获取到了远程配置，写缓存文件，并发读写非线程安全，A获取数据为空

复现日志：

20:08:47.136 [pool-2-thread-6] ERROR com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor - [sub-server] write server config, content before write: dc_test=1, write data: dc_test=1, dataId=dc_test, group=DEFAULT_GROUP, tenant=public
20:08:47.134 [pool-2-thread-9] ERROR com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor - [get-config] get snapshot failed, dataId=dc_test, group=DEFAULT_GROUP, tenant=public, config=

**Comment by 694303720** [comment]
模拟复现代码

    ```
@Test
    public void getConfig() throws InterruptedException {
        String serverAddr = "xxx:80";
        final String dataId = "dc_test";
        final String group = "DEFAULT_GROUP";
        ExecutorService threadPool = Executors.newFixedThreadPool(20);
        for (int i = 0; i < 20; i++) {
            threadPool.execute(new Runnable() {
                public void run() {
                    try {
                        int i = 0;
                        while (true) {
                            i++;
                            TimeUnit.MILLISECONDS.sleep(10);
                            String content = configService.getConfig(dataId, group, 5000);
                            if (StringUtils.isEmpty(content)) {
                                LOGGER.error("config file is empty, content: {}", content);
                                LOGGER.error("concurrent read cache file when write cache file: file content may be null while data is in flush");
                                LOGGER.error("end");
                            } else {
                                LOGGER.info(String.format("thread:%s request num: %d, content:%s", Thread.currentThread().getName(), i, content));
                            }
                        }
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    } catch (NacosException e) {
                        e.printStackTrace();
                    }
                }
            });
        }
        threadPool.awaitTermination(1, TimeUnit.HOURS);
        LOGGER.info("done");
    }
```

**Comment by caomingjie-code** [comment]
首先要説，这个不是线程安全的问题。线程安全问题是你有可能读取数据时只读到一半正在写的数据。数据读取一半的情况属于线程安全问题。你可以理解为在写的时候不可读，所以你读到的数据就是空。这种情况通常让线程间歇一下再去读取数据即可。并设置读取的次数。在nacos中的读和写没有做读写锁，这样会非常影响性能。
