### ISSUE TITLE
NamingService#registerInstance无法注册多个实例？

### ISSUE THREAD

**Issue by wanna280** [alibaba/nacos#7539]
在`Nacos`的`API`方式使用中，当使用如下的代码去进行注册服务时，在不同的版本的`Nacos Client`当中出现了不同的结果。

```java
try {
            NamingService namingService = new NacosNamingService("localhost:8848");
            namingService.registerInstance("wanna", "localhost", 8889);
            namingService.registerInstance("wanna", "localhost", 8890);

            TimeUnit.SECONDS.sleep(500);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
```

* 1.在使用`Nacos Client`和`NacosServer`版本为`1.4.2`的版本当中，该代码正常运行，也能往`NacosServer`当中注册上去两个`Instance`。
* 2.在使用`Nacos Client`和`NacosServer`版本为`2.0.2`的版本当中，该代码只能往`NacosServer`当中注册一个`Instance`，后进行注册的8890，将会替代之前的8889，`NacosServer`中只有一个`Instance`。
* 3.在`Nacos Client`使用`1.4.2`的版本，`Nacos Server`使用`2.0.2`的版本中，也能正常注册。
* 4.在`Nacos Client`使用`2.0.2`的版本，`Nacos Server`使用`1.4.2`的版本中，`Client`直接报错，不能启动。(符合官网文档预期)

是否是Client的问题？

**Comment by MajorHe1** [comment]
设计如此。
nacos 2.x的版本是基于长连接的，一个客户端的namingService对象只能注册某个service的一个instance。如果需要注册同一个service的多个instance，请new出来不同的namingService对象。
