### ISSUE TITLE
@XW512

### ISSUE THREAD

**Issue by Andac3838** [alibaba/nacos#7540]
@XW512
![image](https://user-images.githubusercontent.com/33930711/147855713-39981f2a-1681-46a3-b9b1-9d8bc4374cc8.png)
不知道您指的是不是这个[系统参数](https://nacos.io/zh-cn/docs/system-configurations.html)

_Originally posted by @zzq1314zll in https://github.com/alibaba/nacos/issues/7510#issuecomment-1003583898_

**Comment by li-xiao-shuang** [comment]
> @XW512 ![image](https://user-images.githubusercontent.com/33930711/147855713-39981f2a-1681-46a3-b9b1-9d8bc4374cc8.png) 不知道您指的是不是这个[系统参数](https://nacos.io/zh-cn/docs/system-configurations.html)
> 
> _Originally posted by @zzq1314zll in [#7510 (comment)](https://github.com/alibaba/nacos/issues/7510#issuecomment-1003583898)_

直接在对应的issue下评论就行 不用创建新的issue
