### ISSUE TITLE
mac 上启动nacos 报错了

### ISSUE THREAD

**Issue by smm113522** [alibaba/nacos#7544]
mac 版本
硬件概览：

  型号名称：	MacBook Air
  型号标识符：	MacBookAir7,2
  处理器名称：	Intel Core i5
  处理器速度：	1.8 GHz
  处理器数目：	1
  核总数：	2
  L2 缓存（每个核）：	256 KB
  L3 缓存：	3 MB
  内存：	8 GB
  Boot ROM 版本：	195.0.0.0.0
  SMC 版本（系统）：	2.27f2
  序列号（系统）：	FVHV98WVJ1WK
  硬件 UUID：	13DC8C81-6E70-5A83-9B39-E7AFCEFAEA1E

启动 sh startup.sh -m standalone

错误日志
xxx-Air:logs xxx$ cat nacos.out
cat: nacos.out: No such file or directory
shinaimengdeMacBook-Air:logs shinaimeng$ cat start.out 
/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/java -Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/ext  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xloggc:/Users/shinaimeng/Desktop/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/shinaimeng/Desktop/nacos/plugins/health,/Users/shinaimeng/Desktop/nacos/plugins/cmdb -Dnacos.home=/Users/shinaimeng/Desktop/nacos -jar /Users/shinaimeng/Desktop/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/Users/shinaimeng/Desktop/nacos/conf/ --logging.config=/Users/shinaimeng/Desktop/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 2.0.3
,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 83115
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://192.168.0.192:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

2022-01-03 18:43:13,198 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@28f8e165' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2022-01-03 18:43:13,269 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2022-01-03 18:43:14,408 INFO Tomcat initialized with port(s): 8848 (http)

2022-01-03 18:43:15,541 INFO Root WebApplicationContext: initialization completed in 16269 ms

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/q3/753tdh7d7s35t2rnvllclwt80000gn/T/librocksdbjni6040411840040829922.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/q3/753tdh7d7s35t2rnvllclwt80000gn/T/librocksdbjni6040411840040829922.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

请问一下，这个怎么解决呢？

**Comment by KomachiSion** [comment]
duplicate with #4336
