### ISSUE TITLE
nacos获取时间问题

### ISSUE THREAD

**Issue by zuo-xie** [alibaba/nacos#7546]
如果我在  nacos上的配置文件 编写下面这种格式，我在以 `@Value("${service.time}")`的方式获取，那么他就会变成一个 `new Date().toString()` 的参数，而我想要原来的参数。
```yml
service:
  time: 2022-01-04
```

**Comment by hujun-w-2** [comment]
加上双引号可以解决这个问题

**Comment by hujun-w-2** [comment]
不过这和spring @value注解不一致  使用@value注解不使用配置中心时不需要加双引号

**Comment by hujun-w-2** [comment]
@i will solve it@

**Comment by hujun-w-2** [comment]
@realJackSun 有空帮忙看看这个issue和PR
