### ISSUE TITLE
springcloud gateway + nacos ，服务启动后自动注册了路由到gateway

### ISSUE THREAD

**Issue by rola0411** [alibaba/nacos#7547]
springcloud gateway + nacos 
现在得问题是，当我得服务注册到nacos，就自动在gateway中增加了路由，
这让我十分困扰，我想在gateway中通过在nacos增加路由配置而生效，而不是我注册了服务，gateway就可以路由到。
请问这个问题该如何解决。谢谢

**Comment by rola0411** [comment]
[{
	"predicate": "Paths: [/test-api/**], match trailing slash: true",
	"metadata": {
		"nacos.instanceId": "172.16.15.200#8084#DEFAULT#TESTGROUP@@test-api",
		"nacos.weight": "1.0",
		"nacos.cluster": "DEFAULT",
		"nacos.ephemeral": "true",
		"nacos.healthy": "true",
		"preserved.register.source": "SPRING_CLOUD"
	},
	"route_id": "ReactiveCompositeDiscoveryClient_test-api",
	"filters": ["[[RewritePath /test-api/?(?<remaining>.*) = '/${remaining}'], order = 1]"],
	"uri": "lb://test-api",
	"order": 0
}]
我想问题我的nacos.instanceId 这个配置项有数据的原因，正常应该为null

**Comment by YunWZ** [comment]
set `spring.cloud.gateway.discovery.locator.enabled=false`.
设置配置项`spring.cloud.gateway.discovery.locator.enabled`为`false`.

**Comment by rola0411** [comment]
> set `spring.cloud.gateway.discovery.locator.enabled=false`. 设置配置项`spring.cloud.gateway.discovery.locator.enabled`为`false`.

设置了这个之后， 网关路由中配置的lb://xxxx 就无法访问服务了。

**Comment by YunWZ** [comment]
> > set `spring.cloud.gateway.discovery.locator.enabled=false`. 设置配置项`spring.cloud.gateway.discovery.locator.enabled`为`false`.
> 
> 设置了这个之后， 网关路由中配置的lb://xxxx 就无法访问服务了。

可以的,检查下你的nacos客户端版本和SCG版本.lb的本质是通过`DiscoveryClient`获取服务实例,只要你的SCG集成了服务发现客户端,就可以通过`lb://service-name`的方式转发请求.
