### ISSUE TITLE
Nacos配置中心管理页面，Data ID搜索框在切换namespace后失效，不起过滤作用。

### ISSUE THREAD

**Issue by LijiahaoGit** [alibaba/nacos#7548]
Nacos配置中心管理页面，Data ID搜索框在切换namespace后失效，不起过滤作用。

**Comment by brotherlu-xcq** [comment]
I can not reproduce in develop branch, maybe it has been fixed by #6625

**Comment by LijiahaoGit** [comment]
The version of my Nacos is 2.0.3. I'm not sure if it  has been fixed after version 2.0.3
