### ISSUE TITLE
我重启nacos,报错

### ISSUE THREAD

**Issue by eternalsilencer** [alibaba/nacos#7549]
我用的是官方helm 部署，用的mysql作为持久化存储，我关闭了双写模式，当我docker serverce restart 后，nacos正常启动，但是naming-server.log报这个错，其它服务也不能正常注册
![image](https://user-images.githubusercontent.com/51810383/148040343-b594eb55-7a0e-48ef-94ad-578089ff6923.png)

**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
拒绝连接，进程没启动或端口没坚挺或网络不通

**Comment by eternalsilencer** [comment]
> 拒绝连接，进程没启动或端口没坚挺或网络不通
当我使用docker server restart 时候，我注册的服务报了acos cluster is running with 1.X mode, can't accept gRPC request temporarily.这个错误，但是之前我已经把这个关闭了
