### ISSUE TITLE
说好的支持jdk8以上呢。jdk11就启动不起来

### ISSUE THREAD

**Issue by mx189** [alibaba/nacos#7562]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by brotherlu-xcq** [comment]
启动失败是什么错误呢？可以贴一下吗？

**Comment by mx189** [comment]
centos、jdk-11.0.12,脚本为做修改，启动的时候提示找不到或无法加载主类。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 说好的支持jdk8以上呢。jdk11就启动不起来 (Issue #7562)





 
启动失败是什么错误呢？可以贴一下吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brotherlu-xcq** [comment]
这个问题应该在 https://github.com/alibaba/nacos/issues/6609 中修复了，develop的分支现在是最新的代码，可以尝试先使用develop分支里面的脚本。

**Comment by mx189** [comment]
好的。感谢。我目前是用的jdk1.8启动的，等下我找一下，再用jdk11去启动试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 说好的支持jdk8以上呢。jdk11就启动不起来 (Issue #7562)





 
这个问题应该在 #6609 中修复了，develop的分支现在是最新的代码，可以尝试先使用develop分支里面的脚本。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by realJackSun** [comment]
@mx189 Any progress?
