### ISSUE TITLE
Nacos2.0.3版本，只读权限用户依旧可以修改发布配置

### ISSUE THREAD

**Issue by LijiahaoGit** [alibaba/nacos#7567]
Nacos2.0.3版本，只读权限用户依旧可以修改发布配置。这有点离谱！！

**Comment by tigerlan98** [comment]
请问这个是bug吗？

**Comment by MajorHe1** [comment]
检查服务端鉴权有没有打开

**Comment by liaojiede** [comment]
我也遇到这个问题，部分配置如下：
nacos.core.auth.caching.enabled=true
nacos.core.auth.enable.userAgentAuthWhite=false
nacos.core.auth.server.identity.key=serverIdentity
nacos.core.auth.server.identity.value=security


求解决!
