### ISSUE TITLE
用域名配置nacos地址，请求报错。

### ISSUE THREAD

**Issue by mx189** [alibaba/nacos#7571]
版本  <alibaba.nacos.version>2.0.3</alibaba.nacos.version>
![image](https://user-images.githubusercontent.com/16896138/148371310-067e82f5-4b5a-44e1-806f-609a543c53e6.png)
 - Server check fail, please check server nacos.255px.com ,port 1080 is available , error ={}

**Comment by hujun-w-2** [comment]
grpc的四层负载没配吧

**Comment by mx189** [comment]
找到问题了，我nacos放在云服务器上。开放外网了。然后只开放80和443端口。不行，还必须要开放9848端口才不报错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 晚上10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 用域名配置nacos地址，请求报错。 (Issue #7571)





 
grpc的四层负载没配吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
