### ISSUE TITLE
支持M1平台

### ISSUE THREAD

**Issue by YunWZ** [alibaba/nacos#7572]
**Is your feature request related to a problem? Please describe.**
Cannot compile 2.x version on Apple silicon (M1).
无法在m1芯片平台上编译2.x版本.
由于2.x版本使用grpc,项目依赖的`protobuf-java`和`protoc-gen-grpc-java`版本过低,没有对应m1平台的版本.

报错信息如下:
```java
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project nacos-consistency: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.8.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.8.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.8.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
```

**Describe the solution you'd like**
升级grpc相关依赖到支持m1平台的版本.

**Comment by xiaochangbai** [comment]
我按这个方法弄好了，https://blog.csdn.net/qq_42651904/article/details/120923278

**Comment by YunWZ** [comment]
> 我按这个方法弄好了，https://blog.csdn.net/qq_42651904/article/details/120923278

我知道怎么在本地编译,只是希望官方能直接支持,而不是下载代码后,还要自己手动该pom文件.

**Comment by pixystone** [comment]
目前我在用M1，最好的方式就是遇到兼容性问题时，使用x86的JDK（牺牲一点性能）。

具体参考：https://github.com/alibaba/nacos/issues/4336#issuecomment-821246302

**Comment by KomachiSion** [comment]
Please submit issue to protobuf community to push them adapt M1.

**Comment by YunWZ** [comment]
> Please submit issue to protobuf community to push them adapt M1.

protoc plugin `protoc-gen-grpc-java` support apple silicon since version `1.42.1`.
But Nacos dependent on `protoc-gen-grpc-java` version `1.24.0`.
