### ISSUE TITLE
does the nacos can support https server register

### ISSUE THREAD

**Issue by wearybird** [alibaba/nacos#7584]
i  use nacos in spring cloud ,now ,my cloud micro server must use https  with ssl include  the gateway  server .but when i  visit the  one micro server through  gateway server ,the url change to http url .is the nacos does not support https? anyway ,the https client  server can register to the nacos server .

我的基于spring cloud的微服务因为某些原因必须使用https，这些服务能注册到nacos，但是我通过网关访问这些服务的时候，发现网关转发的请求地址变成了http的，请问这个因为nacos不支持https的微服务调用吗？

**Comment by wearybird** [comment]
<spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
<nacos.version>2.0.2</nacos.version>

**Comment by YunWZ** [comment]
Confirm whether your gateway converts https requests into http requests.
确认你的网关是否将https请求转换成了http请求.

**Comment by wearybird** [comment]
我的网关服务是https，在路由的时候我也没有添加任何处理去将https请求转发成http请求，下面是我通过网关访问注册的微服务的时候输出的日志：
01-09 14:05:02.953 INFO  [com.alibaba.nacos.client.naming] - init new ips(1) service: DEFAULT_GROUP@@513-cloud-module-core-wy -> [{"ip":"2.0.1.3","port":8981,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@513-cloud-module-core-wy","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatTimeOut":15000,"instanceHeartBeatInterval":5000,"ipDeleteTimeout":30000}]
01-09 14:05:02.953 INFO  [com.alibaba.nacos.client.naming] - current ips:(1) service: DEFAULT_GROUP@@513-cloud-module-core-wy -> [{"ip":"2.0.1.3","port":8981,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@513-cloud-module-core-wy","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatTimeOut":15000,"instanceHeartBeatInterval":5000,"ipDeleteTimeout":30000}]
01-09 14:05:03.523 INFO  [com.alibaba.nacos.common.remote.client] - [e0e09f6d-0929-4f48-9b93-99c997d96e88]receive server push request,request=NotifySubscriberRequest,requestId=8442
01-09 14:05:03.524 INFO  [com.alibaba.nacos.common.remote.client] - [e0e09f6d-0929-4f48-9b93-99c997d96e88]ack server push request,request=NotifySubscriberRequest,requestId=8442
01-09 14:05:03.619 DEBUG [reactor.netty.http.client.HttpClientConnect] - [id:a9f2636f-1, L:/2.0.1.3:59054 - R:/2.0.1.3:8981] Handler is being applied: {uri=http://2.0.1.3:8981/js/a, method=GET}
01-09 14:05:03.637 DEBUG [reactor.netty.http.client.HttpClientOperations] - [id:a9f2636f-1, L:/2.0.1.3:59054 - R:/2.0.1.3:8981] Received response (auto-read:false) : [Content-Type=text/plain;charset=UTF-8, Connection=close]
01-09 14:05:03.666 DEBUG [reactor.netty.http.client.HttpClientOperations] - [id:a9f2636f-1, L:/2.0.1.3:59054 ! R:/2.0.1.3:8981] Received last HTTP packet

我现在就是不清楚明明是注册的https的微服务，怎么uri从https变成了http，anyone has more ideas？
ps:直接用 https://2.0.1.3:8981/js/a是可以正常访问我这个注册的服务的。

**Comment by wearybird** [comment]
我调试了我的网关注册的过程，发现注册的时候不是以https服务注册的，将spring.cloud.nacos.discovery.secure设置成true就可以了。
