### ISSUE TITLE
集群模式+内置数据库配置中心配置文件丢失

### ISSUE THREAD

**Issue by ccoke** [alibaba/nacos#7593]
**Describe the bug**
生产环境使用了集群模式+内置数据库，当nacos某节点重启时，会出现在nacos/data/config-data目录中的配置文件丢失的情况，且节点运行一段时间以后，目录中的配置文件也没有恢复，该现象导致了微服务无法获取指定Data ID的配置。Debug了下nacos-config ConfigCacheService类中的代码，发现dump之前会先将配置目录删除，再根据本地数据库和内存缓存中配置内容的MD5比较，如果相同则不写到磁盘，应该是漏了一个逻辑：本地数据库和内存缓存中的数据一致，且判断磁盘中是否有对应文件，如果没有，才不写磁盘。

**Expected behavior**
节点重启，配置能正常写入磁盘

**Acutally behavior**
生产环境使用了集群模式+内置数据库，当nacos某节点重启时，会出现在nacos/data/config-data/prod目录中的配置文件丢失的情况

**How to Reproduce**
1. 启动三个节点，集群模式+内置数据库
2. 上传配置文件
3. 停止任意一个节点，多次重启服务，观察nacos/data/config-data

**Desktop (please complete the following information):**
 - OS: [Ubuntu20.04]
 - Version [nacos-server 1.4.2]
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**

**Comment by MajorHe1** [comment]
请教一下 
>发现dump之前会先将配置目录删除

这一段逻辑代码在哪，我确实没有找到

以及
> 本地数据库和内存缓存中的数据一致，且判断磁盘中是否有对应文件，如果没有，才不写磁盘

是否打错了，本意是 如果磁盘中有对应的文件才不写磁盘

**Comment by ccoke** [comment]
@MajorHe1
> 这一段逻辑代码在哪，我确实没有找到

DumpService.java中dumpConfigInfo方法260行

> 是否打错了，本意是 如果磁盘中有对应的文件才不写磁盘

看ConfigCacheService.java中方法dump方法第94行，现在只有条件：
`if (md5.equals(ConfigCacheService.getContentMd5(groupKey)))`
我的意思是改成这种方式，可以避免配置丢失：
`if (md5.equals(ConfigCacheService.getContentMd5(groupKey)) && DiskUtil.targetFile(dataId, group, tenant).exists()) `

**Comment by MajorHe1** [comment]
` if (md5.equals(ConfigCacheService.getContentMd5(groupKey)) && DiskUtil.targetFile(dataId, group, tenant).exists()) `

这个改法我觉得没有问题，我觉得可以提个PR到 1.x的分支和当前develop分支，看官方团队怎么看待这个改动。

不过有个问题我没有明白，就是ConfigCacheService的内存CACHE有这个item，但是磁盘上不存在这个配置文件，这个场景是怎么触发的，看代码
![image](https://user-images.githubusercontent.com/53824889/148765380-358df608-9437-4c8a-849d-1025c9efabe3.png)
如果你方便调试的话可以看看，是不是这个地方触发了多次。（但是从代码来看，如果触发多次，会导致所有的配置文件丢失，而不是个别）

**Comment by ccoke** [comment]
> 不过有个问题我没有明白，就是ConfigCacheService的内存CACHE有这个item，但是磁盘上不存在这个配置文件，这个场景是怎么触发的，看代码 ![image](https://user-images.githubusercontent.com/53824889/148765380-358df608-9437-4c8a-849d-1025c9efabe3.png) 如果你方便调试的话可以看看，是不是这个地方触发了多次。（但是从代码来看，如果触发多次，会导致所有的配置文件丢失，而不是个别）

这里我调试过，只有server启动时初始化触发。确实出现过配置全丢的情况。我会在稍后提一个pr看看，谢谢您的帮助。

**Comment by MajorHe1** [comment]
不用客气，并没有帮助您多少。

> 确实出现过配置全丢的情况

配置全丢就是调用了  ` DiskUtil.clearAll();` 方法，该方法一路往上跟踪，只有可能会在这个地方调用多次。
如果只有Server启动时初始化触发，那解释不了为什么CACHE有item，而磁盘上文件不存在，所以还是麻烦再试试看？
