### ISSUE TITLE
如何在springboot上以文件路径的方式读取nacos管理的配置文件

### ISSUE THREAD

**Issue by xiaoaiseeing** [alibaba/nacos#7595]
最近在做项目的配置迁移至nacos, 想要请问一下: 如何以文件路径的方式使用nacos管理的配置文件。比如在项目代码中会有
`FileInputStream in = new FileInputStream(redission.yaml的路径)`

如果讲的redission.yaml放在nacos管理后，此处的路径值怎么确定，或者说需要改上面的代码(不支持以路径方式读取)

**Comment by onewe** [comment]
配置都放入到 nacos 了,就别用文件读的方式了吧.

**Comment by xiaoaiseeing** [comment]
> 

主要是将之前组内的项目配置迁移nacos，想对业务代码的修改尽可能少，不知道这种情况是否已有解决方案

**Comment by YunWZ** [comment]
自己监听配置文件,封装成可以被业务代码识别的POJO类.
