### ISSUE TITLE
NamingRemoteConstants should include action "updateInstance"

### ISSUE THREAD

**Issue by yangyanqing** [alibaba/nacos#7597]
**Is your feature request related to a problem? Please describe.**
Interface `[Put] /nacos /instance` was provided in http mode, but was missing in grpc mode.
```java
package com.alibaba.nacos.api.naming.remote;

/**
 * Retain all naming module request type constants.
 *
 * @author liuzunfei
 * @author xiweng.yy
 */
public class NamingRemoteConstants {
    
    public static final String REGISTER_INSTANCE = "registerInstance";
    
    public static final String DE_REGISTER_INSTANCE = "deregisterInstance";
    
    public static final String QUERY_SERVICE = "queryService";
    
    ...
}

```

**Describe the solution you'd like**
Add action `updateInstance` in grpc mode.

**Describe alternatives you've considered**
Using http mode even on nacos 2.0 server.

**Additional context**
n/a

**Comment by hujun-w-2** [comment]
1.[Put] /nacos /instance 主要是控制台调用做实例上下线用，sdk一般并不需要使用这个接口
2. 2.x的sdk依然存在http模式的类可以调这个接口：NacosNamingMaintainService
