### ISSUE TITLE
The problem of micro-service metadata presentation when nacos is used as a registry

### ISSUE THREAD

**Issue by zsjzero** [alibaba/nacos#760]
Nacos integrates with springcloud, and web pages only show  service-consumer,I hope nacos can show the invocation relationship between services and some operation and maintenance problems, such as service weight setting, load balancing and so on, just like dubbo admin

**Comment by nkorange** [comment]
Nacos cannot do this, because it has no idea what the relations between services. Only Dubbo client knows.
