### ISSUE TITLE
[Optimize]gitignore config doesn't ignore log files after run the integration-test

### ISSUE THREAD

**Issue by onewe** [alibaba/nacos#7600]
- config-test doesn't ignore log files
- core-test doesn't ignore log files
- naming-test doesn't ignore log files

## How to fix it
add `*.log` to gitignore files

**Comment by Liubey** [comment]
data文件夹不需要过滤么

**Comment by onewe** [comment]
我没看到有 data 文件夹呀 @Liubey

**Comment by onewe** [comment]
你是指的是在用户目录生成的那些文件吗？
