### ISSUE TITLE
什么时候可以支持SqlServer，oracle，和一些主流的数据库呀

### ISSUE THREAD

**Issue by wolfyg** [alibaba/nacos#7606]

**Comment by onewe** [comment]
之前有个大佬提了个 PR 的,不过好像被社区否了

**Comment by wolfyg** [comment]
我看到到了，这是不打算支持了吗

**Comment by wolfyg** [comment]
我看到到了，这是不打算支持了吗

**Comment by onewe** [comment]
应该是要把数据库给去掉吧.估计

**Comment by li-xiao-shuang** [comment]
你是有这个需求嘛?

**Comment by wolfyg** [comment]
> 

是的

**Comment by Davion2017** [comment]
gitee上有个做了jpa适配的，但是版本比较旧，可以参考一下去改造
https://gitee.com/yangliu817/nacos-jpa

**Comment by Davion2017** [comment]
另外官方的意思好像是不愿意引入一些orm框架，想要保持nacos的轻量

**Comment by wolfyg** [comment]
如果自己改的话很麻烦nacos是他用jdbc干的还有一些mysql函数其他数据库适配不了，改完以后要全面覆盖测试，改不动

**Comment by limng06** [comment]
jpa也不算太重量级，nacos专心做好自己的事情就好了，为什么一定要去纠结数据库实现呢。
我发现写代码的各个都是强迫症

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/plugin/datasource-plugin/

https://github.com/nacos-group/nacos-plugin/

**Comment by limng06** [comment]
> https://nacos.io/docs/latest/plugin/datasource-plugin/
> 
> https://github.com/nacos-group/nacos-plugin/

点赞 datasource-plugin改进了，现在看来应该是支持oracle 扩展了，之前是不支持的
