### ISSUE TITLE
How to package  nacos-server.jar

### ISSUE THREAD

**Issue by codexinfeng** [alibaba/nacos#7609]
I download source code (2.0.3) and use idea complete  mvn clean install package ,but I don not find nacos-server.jar in the
target file, where is nacos-server.jar or nacos-server-2.0.3.jar （I note maven-checkstyle-plugin in the pom.xml, because I change some code）

**Comment by onewe** [comment]
Hey Bro @codexinfeng , you can see: https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html
Here:
![image](https://user-images.githubusercontent.com/38708836/148740020-c0a28f09-2834-4f4d-843e-c5cbcebb7f4f.png)

**Comment by codexinfeng** [comment]
Thank you Bro, I tried and success
