### ISSUE TITLE
Nacos as a registration center, when registering the dubbo service, the project has just started the health status to true, and after 1 or 2 seconds, the health status is false! And the number of clusters shows 2. I only started one machine! Local boot, win10，nacos0.8

### ISSUE THREAD

**Issue by POWERzhangdi** [alibaba/nacos#761]
英文不好，怕描述不清晰！理解一下！虽说是国际的，不过问题可以是多种语言描述吗！毕竟是国内开源的！谢谢！
![default](https://user-images.githubusercontent.com/23517198/52756276-ca7e7680-303b-11e9-86c0-9d6b7d945695.png)
![default](https://user-images.githubusercontent.com/23517198/52756286-ceaa9400-303b-11e9-8399-c9b251fe4bab.png)
![default](https://user-images.githubusercontent.com/23517198/52756290-d0745780-303b-11e9-957b-ed523f3234a7.png)
![1](https://user-images.githubusercontent.com/23517198/52756296-d2d6b180-303b-11e9-9e83-7241ecbd226e.png)
![2](https://user-images.githubusercontent.com/23517198/52756299-d407de80-303b-11e9-9b28-56fc01edc068.png)
![3](https://user-images.githubusercontent.com/23517198/52756303-d5d1a200-303b-11e9-83e3-5f6d6408d93e.png)
![4](https://user-images.githubusercontent.com/23517198/52756305-d702cf00-303b-11e9-97c3-c7fa62730c27.png)

**Comment by nkorange** [comment]
@POWERzhangdi 
1. 点击详情，看下具体是哪两个集群；
2. 看下nacos-client版本是多少？

**Comment by yfh0918** [comment]
I have encountered similar problems , because my server version is 0.7.0, 
upgraded to 0.8.0 and returned to normal.

**Comment by POWERzhangdi** [comment]
@nkorange client的版本是0.8

**Comment by nkorange** [comment]
> @nkorange client的版本是0.8

你是用nacos-client 0.8.0？

**Comment by POWERzhangdi** [comment]
@nkorange 是啊。

**Comment by nkorange** [comment]
> @nkorange 是啊。

你是用最新的nacos-client覆盖了是吧，因为默认的dubbo-client依赖的是老的客户端
