### ISSUE TITLE
修改nacos服务端contextPaht属性后，springboot客户端无法连接

### ISSUE THREAD

**Issue by 896938034** [alibaba/nacos#7617]
**Describe the bug**
当我安装好nacos服务端后，修改服务端application.properties的server.servlet.contextPath属性为pro-nacos，配置开启认证、使用mysql作为数据源之后启动nacos服务；然后在springboot项目中使用nacos-config-spring-boot-starter集成nacos，并且我确认使用了正确的配置，配置如下：
nacos:
  config:
    bootstrap:
      enable: true
      log-enable: true
    server-addr: 10.7.132.220:8848
    context-path: /pro-nacos
    data-id: cms
    group: local
    username: nacos
    password: Ys$H1#rRa
    type: yaml
    auto-refresh: true
    enable-remote-sync-config: true

我发现我的项目连接不上nacos服务端，报错信息如下：
![image](https://user-images.githubusercontent.com/26057188/148874000-0084af5b-ca4b-431c-937b-834d6372e5d5.png)
然后我在Issue上搜索相应关键字发现有类似问题，按照对应的解决办法尝试解决问题，但最终并没有解决我的问题；然后我开始debug跟踪nacos客户端启动的源码发现虽然将contextPath这个值存储environment中，但是在com.alibaba.boot.nacos.config.util.NacosPropertiesBuilder#buildNacosProperties这个方法里，并没有将contextPath这个值设置到Properties中，并向后传递，导致在后面进行认证的时候，取到的仍然是默认值"/nacos"，而不是我修改后的contextPath，具体代码参见com.alibaba.nacos.client.security.SecurityProxy#SecurityProxy，所以在后续调用com.alibaba.nacos.client.security.SecurityProxy#login方法和nacos服务端认证的时候url是错误的，请求返回的http状态码为404;
之后我将代码debug到com.alibaba.boot.nacos.config.util.NacosPropertiesBuilder#buildNacosProperties的86行，通过IDEA自带的功能手动向properties变量中放入contextPath=/pro-nacos，发现项目可以正常启动。

**How to Reproduce**
1. 下载并解压nacos服务端后，修改application.properties的server.servlet.contextPath属性为pro-nacos；
2. 搭建普通springboot项目，并集成web模块；项目并使用<dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>nacos-config-spring-boot-starter</artifactId>
      <version>0.2.10</version>
  </dependency>集成nacos
3.启动项目，就可以看到报错

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version  
   nacos服务端版本：nacos-server-2.0.3；[e.g. nacos-server 1.3.1, nacos-client 1.3.1] 
  nacos客户端版本：
  <dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>nacos-config-spring-boot-starter</artifactId>
      <version>0.2.10</version>
  </dependency>
 - Module config
 - SDK
  nacos客户端版本：
  <dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>nacos-config-spring-boot-starter</artifactId>
      <version>0.2.10</version>
  </dependency>

**Additional context**
有一些静态资源中也写死了/nacos，导致修改contextPath后，一些静态资源加载不到。

**Comment by hujun-w-2** [comment]
什么场景下需要修改contextpath呢

**Comment by 896938034** [comment]
测试环境部署nacos服务端的时候我修改了contextPath，发现springboot的客户端连接不上nacos，但是springcloud的客户端可以，具体的原因我已经在Issue中截图了；
您说的什么场景我目前没想到，只是发现了这个问题。



***@***.***
 
发件人： 胡俊
发送时间： 2022-02-13 17:18
收件人： alibaba/nacos
抄送： nancy; Author
主题： Re: [alibaba/nacos] 修改nacos服务端contextPaht属性后，springboot客户端无法连接 (Issue #7617)
什么场景下需要修改contextpath呢
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
