### ISSUE TITLE
ldap doesn't work.

### ISSUE THREAD

**Issue by dbses** [alibaba/nacos#7618]
**Describe the bug**
I configured `nacos.core.auth.ldap.url` and `nacos.core.auth.ldap.userdn`, but it doesn't work.

**Expected behavior**
Only the `userdn` configuration item is seen in the `application.properties` file. How to configure `basedn` and `password`?
Please provide the ldap usage documentation.

**Acutally behavior**
Login fail. 

**How to Reproduce**

**Desktop (please complete the following information):**

**Additional context**

**Comment by KomachiSion** [comment]
LADP feature is developed by community, need community help.

**Comment by StandardStudent** [comment]
Also hope to get an accurate answer

**Comment by KeithTt** [comment]
+1

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/8062
