### ISSUE TITLE
spring-boot-admin + nacos 一个服务出现多个实例（实际只有一个实例）

### ISSUE THREAD

**Issue by fatcatmaster** [alibaba/nacos#7619]
![image](https://user-images.githubusercontent.com/37321423/148913949-7d8d9e4f-e9df-4a65-a9c9-febaaa4abf21.png)
如图：除了 SBA 自身，其他两个服务都出现多个实例
但是再看 nacos 的服务列表：
![image](https://user-images.githubusercontent.com/37321423/148914146-832292a4-6ce8-4e09-a3a0-507071be4887.png)

更换成 eureka 作为注册中心则是正常一个服务一个实例，猜测是nacos自身的问题，导致 SBA 从 nacos 拉取服务和列表信息出现了异常
以上问题产生环境均是本地开发环境：
平台：Windows
spring-cloud：Hoxton.RELEASE
spring-boot：2.2.1.RELEASE
spring-boot-admin：2.2.1
spring-cloud-alibaba：2.2.0.RELEASE
nacos：spring-cloud-alibaba 默认的版本

**Comment by andotorg** [comment]
springboot admin不是每个应用上依赖jar导致的吗

**Comment by zhangbx3** [comment]
我也是
![image](https://user-images.githubusercontent.com/59250785/171582095-6d2d965e-f986-415e-bd15-0e8d9c8b8994.png)

**Comment by aurong** [comment]
我发现把siringboot admin注册进nacos，同时配置spring.boot.admin.client.url 就会导致出现2个

**Comment by Tancen** [comment]
> springboot admin不是每个应用上依赖jar导致的吗

什么意思？

**Comment by r-rhythm** [comment]
直接从服务中心获取实例的话, 其他服务就不需要配置  spring.boot.admin.client.url=http://localhost:xxxx了,否则就会出现多一个实例这种情况

**Comment by wangzhiwei61** [comment]
请问最后是怎么处理的,如果可以的话,麻烦解答下呢

**Comment by fatcatmaster** [comment]
> 请问最后是怎么处理的,如果可以的话,麻烦解答下呢

注释掉 spring.boot.admin.client 的相关属性再试试
