### ISSUE TITLE
Nacos Raft Meta Data Issue v2.0.3

### ISSUE THREAD

**Issue by sohskd** [alibaba/nacos#7629]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

The raft for the 4 groups only register itself and not the other nacos instance. 

<img width="1395" alt="Screenshot 2022-01-11 at 22 07 34" src="https://user-images.githubusercontent.com/18133864/148958445-9869797c-84f7-42d2-b7cf-afe324dce388.png">
<img width="1298" alt="Screenshot 2022-01-11 at 22 07 23" src="https://user-images.githubusercontent.com/18133864/148958453-54ddf890-a4a7-4108-a4de-28bcb995aa37.png">
<img width="1182" alt="Screenshot 2022-01-11 at 22 07 13" src="https://user-images.githubusercontent.com/18133864/148958456-8a5a407e-9db9-4273-94cf-4e4b07f9e38f.png">

### Describe what you expected to happen

All raftMetaData should have the 3 ips

### How to reproduce it (as minimally and precisely as possible)

I am using the Nacos v2.0.3. I have used address server as the lookup mode. 

1) First, I deployed the address-server. 
2) Next, I deployed 3 instance of nacos in cluster mode.
3) Lastly, I just post call /nacos/v1/as/nodes?ips=10.129.107.129,10.129.103.231,10.129.107.167
 
As seen in the attachment, it seems the raft for the 4 groups only register itself and not the other nacos instance. Could you please advise on this? Thanks!

### Tell us your environment

cluster mode deployment using address-server

### Anything else we need to know?

v2.0.3 nacos

**Comment by hujun-w-2** [comment]
我在本地使用了一下address来启动服务，一切正常，可以参照排查一下你哪里出了问题
1.address服务使用standalone模式启动，启动参数 ：
-Dnacos.standalone=true -Dnacos.home=/Users/hujun/Documents/cluster-config7
2.使用postman接口调用/nacos/v1/as/nodes 设置集群
![image](https://user-images.githubusercontent.com/39894911/154832300-7559dfe7-1312-484a-ade6-28a0e50860ac.png)
3.启动各个nacos服务，启动参数
-Daddress.server.domain=localhost -Dserver.port=8848 -Dnacos.home=/Users/hujun/Documents/cluster-config4
-Daddress.server.domain=localhost -Dserver.port=8868 -Dnacos.home=/Users/hujun/Documents/cluster-config6
-Daddress.server.domain=localhost -Dserver.port=8858 -Dnacos.home=/Users/hujun/Documents/cluster-config5
4.等所有nacos实例启动成功后，在控制台查看集群列表，符合预期
![image](https://user-images.githubusercontent.com/39894911/154832346-d3764ef1-ee16-4e3a-8a2e-ab1ba898cf72.png)
![image](https://user-images.githubusercontent.com/39894911/154832356-ce744a5c-3b7e-4b14-bd0a-acbe6b53321f.png)
5.查看本地/Users/hujun/Documents/cluster-config5配置，符合预期
#2022-02-20T14:56:07.458
192.168.31.210:8848
192.168.31.210:8858
192.168.31.210:8868
6.调用address服务接口查看集群列表，符合预期
![image](https://user-images.githubusercontent.com/39894911/154832398-c1450285-b5a8-4c4d-b5a1-ac17919a0a00.png)


附上postman接口文件（需修改后缀为json后使用）：

[nacos-address.postman_collection.txt](https://github.com/alibaba/nacos/files/8103556/nacos-address.postman_collection.txt)

备注：
1.因为最新address不支持传ip加端口，我对com.alibaba.nacos.common.utils.InternetAddressUtil#checkIPs 做了如下改动：
public static String checkIPs(String... ips) {
        
        if (ips == null || ips.length == 0) {
            
            return CHECK_OK;
        }
        // illegal response
        StringBuilder illegalResponse = new StringBuilder();
        for (String ip : ips) {
            if (InternetAddressUtil.isIP(ip) || InternetAddressUtil.isIP(ip.split(":")[0])) {
                continue;
            }
            illegalResponse.append(ip + ",");
        }
        
        if (illegalResponse.length() == 0) {
            return CHECK_OK;
        }
        
        return ILLEGAL_IP_PREFIX + illegalResponse.substring(0, illegalResponse.length() - 1);
    }
2.为了绕过address对权限控制，对pom做了修改
<dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>nacos-naming</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>nacos-cmdb</artifactId>
                </exclusion>
                <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-security</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by sohskd** [comment]
@hujun-w-2 My company does not provide static ip. Therefore, I have to deploy the nacos instance **first** to get the ips. Then, I post the ips to address server. 

So in your example, I have to do step 3 first, then step 1. Is this an issue?

**Comment by hujun-w-2** [comment]
@sohskd  You can start the Nacos instance first, and then add IP to the address service. I tried and it was OK

**Comment by hujun-w-2** [comment]
@sohskd  You can first publish Nacos to get the IP, then set it to the address service, and finally re publish Nacos

**Comment by hujun-w-2** [comment]
@sohskd You can first publish Nacos to obtain IP, then set it as an address service, then clean up the raft data generated on the Nacos machine (nacos.home directory), and finally republish Nacos

**Comment by sohskd** [comment]
Hi @hujun-w-2 , could i clarify what is meant by re-publish? Because if i re-publish nacos in a last step, i will get different ips. My situation is that I can only publish nacos to obtain an IP, and then set it in the address service. Which is what i did in the example, so is it possible to not republish after? Thanks!

**Comment by hujun-w-2** [comment]
@sohskd I don't know if this is a bug, because Nacos doesn't support this operation for the time being. At present, I have modified some codes to support your operation, but I don't know whether the code can be merged into the Nacos warehouse. You can download the branch corresponding to the PR submitted by me to solve this problem

**Comment by hujun-w-2** [comment]
@realJackSun @KomachiSion please review this issue and PR
