### ISSUE TITLE
Is it possible to disable the nacos-server UDP push?

### ISSUE THREAD

**Issue by hanxiaop** [alibaba/nacos#7633]
## Issue Description
Currently I'm trying to use Nacos as the registry for my Dubbo services. However, I don't really want the server `push` logic to sync the instances. Are there any ways to disable the UDP push action?

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zrlw** [comment]
有个pushEnabled选项可以通过v1/ns/operator/switches接口关掉，或者你改一下SwitchDomain，把这个默认值改为false。

**Comment by hanxiaop** [comment]
@zrlw Thanks!
