### ISSUE TITLE
nacos prometheus metrics

### ISSUE THREAD

**Issue by leoxhj** [alibaba/nacos#7634]
Hello team,

by reading the doc for prometheus monitoring. we could not find out how to aggregate metrics for instance running on k8s.

say if we have 3 nacos instances running in ks8: 
nacos-1
nacos-2
nacos-3

how to do configuration in prometheus for retrieving all instances metrics?

if we do below configuration, we can only get one of instances metric (randomly)

      additionalScrapeConfigs:
        internal:
          jobList:
            - job_name: 'nacos'
              scrape_interval: 1m
              scrape_timeout: 30s
              scheme: 'https'
              static_configs:
                - targets: [ 'test.com' ]
              metrics_path: "/nacos/actuator/prometheus"
              tls_config:
                insecure_skip_verify: true

**Comment by zhangle910522** [comment]
如果使用 rate(nacos_timer_seconds_sum{}[1m] 等函数 需要调整采集数据间隔（scrape_interval），不然rate 会因为采集不到多个数据点 而现实数据为空。
scrape_interval: 15m
