### ISSUE TITLE
what is the point of NamingService.deregisterInstance()

### ISSUE THREAD

**Issue by pansong291** [alibaba/nacos#7637]
## Issue Description

Type: *simple question*

### Describe what happened (or what feature you want)
a question of #6723 , if i have to kill the process to deregister instance, then what is the role of the api NamingService.deregisterInstance() ?
it doesn't make any sense.

**Comment by pansong291** [comment]
i found the reason, it looks like heartbeat checking needs to be turned off.
but the api NamingService.deregisterInstance() has already turn it off.
so i found #5198 , i use an instance to create namingService, it didn't work.
i try to use NacosDiscoveryProperties, it works.
although i don't know it's correct or not.
the code just like the following:
```java
    @Autowired
    private NacosDiscoveryProperties nacosDiscoveryProperties;

    private void aMethod() {
        try {
            NamingService naming = nacosDiscoveryProperties.namingServiceInstance();
            naming.deregisterInstance("provider-name", "192.168.0.144", 8888);
        } catch (NacosException e) {
            e.printStackTrace();
        }
    }
```

**Comment by MajorHe1** [comment]
考虑代注册的场景（sidecar , mesh一类的），客户端提供deregisterInstance() 就有必要了

**Comment by vividfish** [comment]
这个接口是提供给非持久化的服务实例使用的
