### ISSUE TITLE
dynamically modify parameters will throw exception after upgrading the Nacos to 2.0

### ISSUE THREAD

**Issue by Cherry-Ran** [alibaba/nacos#7640]
After updated Nacos to 2.0.2,when i modify a parameter in nacos,the console will print the error log.
such as:
![image](https://user-images.githubusercontent.com/32769218/149144605-b22cc6da-6fe5-49f1-849d-4227d8f0f4a5.png)
![image](https://user-images.githubusercontent.com/32769218/149144628-d44033ba-b0be-4eec-831d-bcf4ab92ebfd.png)

**Comment by hujun-w-2** [comment]
报错显示类型不匹配，检查一下报错配置引用的地方类型是否正确
