### ISSUE TITLE
logging.level does not work

### ISSUE THREAD

**Issue by zywj** [alibaba/nacos#7644]
The config of `logging.level.root` or `logging.level.xxxx.yyyy.zzzz` does not work. 

Spring Boot: `2.3.12.RELEASE`
Nacos: `2.0.3`  
The Nacos env uses the cmd `docker run --name nacos-quick -e MODE=standalone -p 8848:8848 -d nacos/nacos-server`

### Reproducible exmaple:
The application.properties:
```
nacos.config.server-addr=192.168.56.100:8848
```

The Spring Boot code:
```
package com.example.ttttt;

import com.alibaba.nacos.spring.context.annotation.config.NacosPropertySource;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@NacosPropertySource(dataId = "example", autoRefreshed = true)
public class TttttApplication {

    public static void main(String[] args) {
        SpringApplication.run(TttttApplication.class, args);
    }
}
```

Nacos配置如下：
![image](https://user-images.githubusercontent.com/5554211/149257318-c4752c2d-a792-4333-9e05-f90dc146d3e1.png)

The CONSOLE only ouput level `info` log:
![image](https://user-images.githubusercontent.com/5554211/149258774-9575c8d3-c444-4edf-b707-4c789e1bfb0c.png)

I also using the properties config, and the result is same.
The application.properties:
```
nacos.config.server-addr=192.168.56.100:8848
nacos.config.bootstrap.enable=true
nacos.config.type=properties
nacos.config.data-id=example
```

SpringBoot code:
```
package com.example.ttttt;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TttttApplication {

    public static void main(String[] args) {
        SpringApplication.run(TttttApplication.class, args);
    }
}
```

It seems the  `logging.level.`  only works in the application.properties:
```
nacos.config.server-addr=192.168.56.100:8848
nacos.config.bootstrap.enable=true
nacos.config.type=properties
nacos.config.data-id=example
logging.level.root=DEBUG   # only work here 
```

**Comment by hujun-w-2** [comment]
你是希望logging.level.root=DEBUG 配置放在nacos控制台也生效吗？

**Comment by hujun-w-2** [comment]
你好，这是你的使用问题。经过源码确认与实测，你需要设置这个参数  nacos.config.bootstrap.logEnable=true  能够实现你想要的效果。
这是由于当未设置以上参数的时候，springboot加载日志配置的时候，nacos配置还没有被加载
另外说一句，nacos以后也会提供托管日志的xml配置。

**Comment by zywj** [comment]
@hujun-w-2 感谢回复。 之前用apollo，刚转到nacos下，问题已解决 👍
