### ISSUE TITLE
Nacos JRaft困惑

### ISSUE THREAD

**Issue by Belyenochi** [alibaba/nacos#7645]
启动一个3节点的Nacos集群扩容到5节点，再缩容到3节点，Raft的Meatdata还是显示5节点的信息，数据库用的是derby，请问这是JRaft的预期行为吗，缩容到3节点重新启动后为啥member没有同步到最新的启动数据
![image](https://user-images.githubusercontent.com/26409132/149279129-6a287d44-6187-4433-8a1b-2abdfc921f37.png)
![image](https://user-images.githubusercontent.com/26409132/149279165-3b85b8e6-d63e-433a-b869-c8876f3ba61c.png)
![image](https://user-images.githubusercontent.com/26409132/149279289-f2ed889b-1eff-4cf1-a524-557024f9355a.png)

**Comment by MajorHe1** [comment]
建议每次重启之前都删除 {nacos.home}/data 目录试试看

**Comment by Belyenochi** [comment]
> 建议每次重启之前都删除 {nacos.home}/data 目录试试看

这有点不合理，每次需要删除PV，但是实际上缩容的时候调用下线接口就可以了，我想知道这个节点元信息存储在了哪里？derby数据库里还是本地文件，本地文件我没有找到

**Comment by Belyenochi** [comment]
> 建议每次重启之前都删除 {nacos.home}/data 目录试试看

我理解这个节点元信息需要由Raft Member同步，这是否意味着Nacos 使用JRaft的姿势有问题？

**Comment by Belyenochi** [comment]
> ![image](https://user-images.githubusercontent.com/53824889/149303388-e2148299-047c-4f1b-8c54-b83094b1dce8.png) https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

这里验证发现用下线接口可以实现RaftGroup同步

**Comment by Belyenochi** [comment]
> ![image](https://user-images.githubusercontent.com/53824889/149303388-e2148299-047c-4f1b-8c54-b83094b1dce8.png) https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

感谢回复！

**Comment by MajorHe1** [comment]
不客气

**Comment by qngl** [comment]
问题是data目录删了，所有的配置信息也丢了，这解决方案也太优雅了吧！
