### ISSUE TITLE
发布配置或修改配置时，配置的文本内容过大，导致写不进去报错，报错的异常是[NACOS ConnectException] currentServerAddr

### ISSUE THREAD

**Issue by lichuangjian** [alibaba/nacos#7646]
![image](https://user-images.githubusercontent.com/47874284/149285329-9dacff78-a7b4-4dc1-8d9c-b347106ed288.png)

**Comment by hujun-w-2** [comment]
控制台还是sdk 什么版本

**Comment by lichuangjian1994** [comment]
> 什么版本
控制台打印的错误日志，用的nacos的包是1.3.3，nacos客户端是2.0.3还有1.4.1都会报这个错

**Comment by hujun-w-2** [comment]
配置内容贴出来

------------------ 原始邮件 ------------------
发件人: lichuangjian1994 ***@***.***&gt;
发送时间: 2022年1月16日 21:48
收件人: alibaba/nacos ***@***.***&gt;
抄送: 胡俊 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [alibaba/nacos] 发布配置或修改配置时，配置的文本内容过大，导致写不进去报错，报错的异常是[NACOS ConnectException] currentServerAddr (Issue #7646)





  
什么版本
 控制台打印的错误日志，用的nacos的包是1.3.3，nacos客户端是2.0.3还有1.4.1都会报这个错
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lichuangjian1994** [comment]
> 配置内容贴出来
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lichuangjian1994 ***@***.***&gt; 发送时间: 2022年1月16日 21:48 收件人: alibaba/nacos ***@***.***&gt; 抄送: 胡俊 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [alibaba/nacos] 发布配置或修改配置时，配置的文本内容过大，导致写不进去报错，报错的异常是[NACOS ConnectException] currentServerAddr (Issue #7646) 什么版本 控制台打印的错误日志，用的nacos的包是1.3.3，nacos客户端是2.0.3还有1.4.1都会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by lichuangjian1994** [comment]
> 配置内容贴出来
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lichuangjian1994 ***@***.***&gt; 发送时间: 2022年1月16日 21:48 收件人: alibaba/nacos ***@***.***&gt; 抄送: 胡俊 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [alibaba/nacos] 发布配置或修改配置时，配置的文本内容过大，导致写不进去报错，报错的异常是[NACOS ConnectException] currentServerAddr (Issue #7646) 什么版本 控制台打印的错误日志，用的nacos的包是1.3.3，nacos客户端是2.0.3还有1.4.1都会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

> 可以私信吗？或者加你钉钉？因为配置内容不太方便发出来。

**Comment by lichuangjian1994** [comment]
> 配置内容贴出来
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lichuangjian1994 ***@***.***&gt; 发送时间: 2022年1月16日 21:48 收件人: alibaba/nacos ***@***.***&gt; 抄送: 胡俊 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [alibaba/nacos] 发布配置或修改配置时，配置的文本内容过大，导致写不进去报错，报错的异常是[NACOS ConnectException] currentServerAddr (Issue #7646) 什么版本 控制台打印的错误日志，用的nacos的包是1.3.3，nacos客户端是2.0.3还有1.4.1都会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;
[AUTHORIZED.txt](https://github.com/alibaba/nacos/files/7880574/AUTHORIZED.txt)

**Comment by lichuangjian1994** [comment]
> 配置内容贴出来
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lichuangjian1994 ***@***.***&gt; 发送时间: 2022年1月16日 21:48 收件人: alibaba/nacos ***@***.***&gt; 抄送: 胡俊 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [alibaba/nacos] 发布配置或修改配置时，配置的文本内容过大，导致写不进去报错，报错的异常是[NACOS ConnectException] currentServerAddr (Issue #7646) 什么版本 控制台打印的错误日志，用的nacos的包是1.3.3，nacos客户端是2.0.3还有1.4.1都会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

大佬，配置内容已经粘贴出来了

**Comment by hujun-w-2** [comment]
看起来不是配置内容过大的原因，可能是配置内容影响了传递到服务端到参数，可以先采用base64编码之后再上传可以暂时解决这个问题

**Comment by lichuangjian1994** [comment]
> 看起来不是配置内容过大的原因，可能是配置内容影响了传递到服务端到参数，可以先采用base64编码之后再上传可以暂时解决这个问题

目前我们这边通过修改nacos服务端的配置添加了server.tomcat.max-http-post-size=10485760，是可以将配置文件写入的，但是nacos的源码设置了三秒的超时时间，客户端发起请求三秒还没得到响应，还是会报错Read Time。报错截图如下
这个超时时间，我们是不能修改的。
