### ISSUE TITLE
服务管理里面的服务元数据中文变成问号

### ISSUE THREAD

**Issue by lichuangjian** [alibaba/nacos#7648]
![image](https://user-images.githubusercontent.com/47874284/149306068-f5391147-c3fe-45b3-ae00-9b5402260678.png)

**Comment by hujun-w-2** [comment]
什么环境呢，两个实例启动的方式有什么不一样的吗

**Comment by lichuangjian1994** [comment]
> 

部署在k8s集群的，同样的启动方式，都一样的配置。
