### ISSUE TITLE
是否可以增加完整的接口级别的指标监控，包括http接口以及Grpc接口，指标分为：接口级别的总请求数，平均时延，最大时延，最小时延

### ISSUE THREAD

**Issue by pengkai242** [alibaba/nacos#7649]
**Is your feature request related to a problem? Please describe.**
Whether to add complete interface-level indicators, including HTTP interfaces and Grpc interfaces, to monitor the total number of requests, average latency, maximum latency, and minimum latency

**Describe the solution you'd like**
Monitoring indicator statistics can be performed on all requested interfaces in a unified entry,Includes HTTP and GRPC

**Describe alternatives you've considered**
Add filter in HTTP request entry, monitor interface indicators in GRPC RequestHandler, and count the number of requests, return codes, and latency of each interface

**Additional context**

**Comment by KomachiSion** [comment]
Refer to summer 2022
