### ISSUE TITLE
can't install mitmf requirements.txt

### ISSUE THREAD

**Issue by ray5123** [alibaba/nacos#7651]
**Describe the bug**
Installed all the dependencies as per required but still i cant install the requirements.txt file for mitmf app
**Expected behavior**
I was expecting the commands to be executed since i have fulfilled every dependencies but it comes out with error 

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [WSL-2  KALI}
 - Version [2021.4]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
here is the issue
[mitmf.txt](https://github.com/alibaba/nacos/files/7864953/mitmf.txt)

**Comment by ray5123** [comment]
well solve the issue finally by myself

**Comment by KomachiSion** [comment]
It is not nacos' problem
