### ISSUE TITLE
how nacos server judge client down

### ISSUE THREAD

**Issue by codexinfeng** [alibaba/nacos#7658]
If nacos client is down by network,client do not send heartbeat ,how  nacos server judge ,service is Ephemeral,nacos-server version : 2.0.3
can anybody list relative Classes and methods

**Comment by MajorHe1** [comment]
这个 down 描述的有点模糊，分情况讨论。
1、nacos-client是 1.x的版本，客户端基于http短连接5秒一次心跳，那么 server端 15秒检测失活，30秒剔除，see `IpPortBasedClient`
2、nacos-client是 2.x 的版本，客户端基于grpc长连接，继续分情况
     如果是进程kill，长连接断开，server端立即剔除， see `ConnectionBasedClient`
     如果是网络隔离/拔网线，server端检测长连接失效，20秒剔除，see `ConnectionManager`

**Comment by codexinfeng** [comment]
非常感谢，今天也看了源码，针对2.x版本
a：客户端正常关闭，长连接断开,抓包时,客户端会发送一个【RST】包，GRPC连接会感知， 会调用 BaseGrpcServer 类startServer 方法里面绑定的  ServerTransportFilter类的transportTerminated 方法 ，会立即调用  connectionManager.unregister(connectionId) 进行正在剔除
b：通过手动禁止网络（模拟网络情况不好）,ConnectionManager 下的run 方法里面，会有个定时的任务，每3s执行一次,
    1： 主要代码： else if (now - client.getMetaInfo().getLastActiveTime() >= KEEP_ALIVE_TIME) ，当前时间-上次更新时间>=20s 先记录,随后会异步回调客户端： connection.asyncRequest(clientDetectionRequest, new RequestCallBack()，成功则更新ConnectionMeta 类lastActiveTime的属性为当前时间，回调失败，则走 unregister(outDateConnectionId) 进行真正的剔除
    2：客户端会定时上报请求（HealthCheckRequest）或者每一分钟获取一次Service (ServiceQueryRequest)都会更新当前
         连接的lastActiveTime，代码：GrpcRequestAcceptor    connectionManager.refreshActiveTime(requestMeta.getConnectionId());
