### ISSUE TITLE
nacos released 2.0.4, but did not update the docker image

### ISSUE THREAD

**Issue by dislazy** [alibaba/nacos#7662]
nacos released 2.0.4, but did not update the docker image

**Comment by dislazy** [comment]
nacos/nacos-server

**Comment by myifeng** [comment]
See [nacos/nacos-server:latest](https://hub.docker.com/layers/nacos/nacos-server/latest/images/sha256-6d64015f93306d39047825e8d4bf56a6974ff66c91afaed61c9bd863b21a0863?context=explore)
