### ISSUE TITLE
nacos 2.0.4 发布的版本为啥是 2.1.0-SNAPSHOT 的？？？

### ISSUE THREAD

**Issue by jinshengyong** [alibaba/nacos#7663]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
已重新发布了， 再试下。
