### ISSUE TITLE
Service cannot be registered

### ISSUE THREAD

**Issue by little-eight-china** [alibaba/nacos#767]
When the Springboot version is 2.1.2 (currently tested only for this, and possibly the same for other adjacent versions), Nacos will not be detected, resulting in the inability to register services.
Versions 2.0.4 and 2.0.6 passed the test.
I don't know if it's a bug in spring boot itself.

**Comment by nkorange** [comment]
@little-eight-china 
Please inform your client dependency and nacos server version.

**Comment by flystar32** [comment]
refer to this https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/105
