### ISSUE TITLE
how to disable nacos config?

### ISSUE THREAD

**Issue by hsapphire** [alibaba/nacos#7670]
spring.cloud.nacos.config.enabled=false 
it is not work . 
i want to use application-dev.properties to replace nacos config, 
the vesion is 2.1.2

**Comment by YunWZ** [comment]
Did you  config `spring.cloud.nacos.config.enabled=false` in **bootstrap.properties**?

**Comment by YunWZ** [comment]
> yes, it is not working

Refer to the official Spring documentation for instructions:
> If you want to retrieve specific profile configuration, you should also set `spring.profiles.active` in `bootstrap.[properties | yml]`.

> You can disable the bootstrap process completely by setting `spring.cloud.bootstrap.enabled=false` (for example, in system properties).
