### ISSUE TITLE
2.0.4版本源码包中的revision版本貌似有问题<revision>2.1.0-SNAPSHOT</revision>

### ISSUE THREAD

**Issue by heyuqiang** [alibaba/nacos#7671]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by li-xiao-shuang** [comment]
具体是哪个pom文件中引用的？

**Comment by heyuqiang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 晚上11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 2.0.4版本源码包中的revision版本貌似有问题<revision&gt;2.1.0-SNAPSHOT</revision&gt; (Issue #7671)





 
具体是哪个pom文件中引用的？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KomachiSion** [comment]
删除本地pom缓存的nacos2.0.4，再试一下？ 应该已经重新发布过了。
