### ISSUE TITLE
nacos 1.4.2   出现假死现象，影响服务调用

### ISSUE THREAD

**Issue by anuserin** [alibaba/nacos#7672]
环境：linux
版本：nacos-server 1.4.2，Nacos-client 1.4.2集群模式：使用内置数据库存储，无vip，采用直连方式
问题现象：
nacos-server运行一段时间后，建链数增加到约7000~15000（正常情况下约为1300-1500），查看nacos-cluster.log发现一直在调用beat探测接口直到超时，这段时间，其他2个nacos都处于端口8848正常监听状态。但访问页面发现一直在等待卡顿，疑似被挂起等待无响应状态，可能内在的tomcat线程数耗尽（线程数已增，但无缓解），而已处于假死状态状态，导致后续间接影响服务交易（dubbo clint调用p端错误提示无法使用该服务地址）推测应该与该状态有关
疑虑点：
1 一段时间后，现象频繁出现，原因是什么？
2 可以规避或解决吗？

**Comment by icodening** [comment]
1. jstack查看tomcat的线程状态，是不是在等待什么资源
2. jstat 查看nacos server gc情况，是否存在因大量gc导致无法正常处理请求的情况

**Comment by anuserin** [comment]
1 线程无等待，还很充裕
2 gc 回收正常
3 目前排查崩溃的集群环境linux 系统参数somaxconn 监听队列默认为128 现改为65535 不知此参数是否对该问题有影响

**Comment by zrlw** [comment]
可以改一下HttpClientManager的内部类ApacheSyncHttpClientFactory的buildHttpClientConfig方法，把里面的连接池参数加大。
我们之前遇到过类似的问题，调大nacos内置的tomcat的maxThreads参数有些效果，但压测时发现还是会出现。
ApacheSyncHttpClientFactory的buildHttpClientConfig设置的连接池参数是给nacos各节点之间通讯用的，主要是转发临时实例的beat心跳请求到责任节点，实例数量多的时候，心跳转发会很多，这个方法只按cpu核数设置连接池，太少了，不适用临时实例多的场景，可以和前面的AsyncHttpClientFactory对比一下，AsyncHttpClientFactory是持久实例的连接池参数配置。
1. setMaxConnPerRoute这个我们从核数改成200了，这个配置的是到每个目标节点的最大连接数, 我们的tomcat用的是默认的工作线程数200，最大连接数配多了也需要等待空闲线程。不止一个人说过ApacheSyncHttpClientFactory这个连接池配置太小，对于临时实例多的应用场景，心跳转发会非常频繁，假设nacos各节点配置cpu核数是16个，16个连接根本撑不起来几十万个临时实例的心跳转发（你还要加一下从连接池获取空闲连接的超时设置，这个是另外一个问题，1.4.2的代码获取连接是无限等待的方式，当连接池不够用的时候堆起来的beat请求会把nacos注册中心击溃，现象就是注册中心的控制台页面都很难打开）。
2. setMaxConnTotal这个可以参照 setMaxConnPerRoutes设置的值 *（nacos集群节点数-1）设置。
这两个可以搞两个启动参数，buildHttpClientConfig时调用System.getProperty获取。
另外setConnectionTimeToLive这个我们改成-1了，我们都是dubbo临时实例，nacos节点之间临时实例的心跳包很频繁，这个参数对我们没什么用处，设超时反而可能会把还在用的连接给关了。
