### ISSUE TITLE
Nacos 2.0.3版本通过API接口注册永久实例失败

### ISSUE THREAD

**Issue by wjkaola123** [alibaba/nacos#7675]
**Describe the bug**
Nacos 2.0.3版本通过API接口注册永久实例失败， 接口返回OK，但是页面上没有显示注册成功，看不到服务上线。
但是可以注册临时实例， 临时注册的实例会上线。

**Expected behavior**
通过API接口可以注册永久实例，并成功上线。

**Acutally behavior**

**How to Reproduce**
【永久实例情况】:
1.  接口调用成功
![image](https://user-images.githubusercontent.com/19920489/150102527-f224d1f4-7301-4236-839f-bd9265a3add1.png)
2.  服务没有在线
![image](https://user-images.githubusercontent.com/19920489/150102630-1f394aab-566e-4983-93e0-ea2d934927d6.png)

【临时实例情况】：
1.  接口调用成功

![image](https://user-images.githubusercontent.com/19920489/150103171-06465f8a-2841-47a7-bd4f-fd7463844328.png)

2. 服务会显示在线

![image](https://user-images.githubusercontent.com/19920489/150103046-6553b32c-8c60-4360-a316-e8725246e9b0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.0.3]
 - Module [调用API接口注册nacos实例]

**Additional context**

**Comment by anAtCloudfall** [comment]
2.0.4 也遇到了这个问题

**Comment by vividfish** [comment]
你好，你所提出的问题我在2.0.3standalone模式下没有复现出来 ，我调用api或者在管理页面创建都是能够成功的，能提供下更详细的信息吗？
比如你的部署模式

**Comment by realJackSun** [comment]
@wjkaola123 你是使用集群模式启动的吗？

**Comment by hujun-w-2** [comment]
@wjkaola123  你是看到健康状态是false就认为实例没在线吗，持久化实例虽然显示健康状态是false，实际上消费者也能拿到这个实例,也是属于在线实例的范围
