### ISSUE TITLE
Limit of content length when using openAPI to publish config?

### ISSUE THREAD

**Issue by jxl4650152** [alibaba/nacos#7681]
According to doc https://nacos.io/zh-cn/docs/open-api.html, config content is put into query string of URL when published to Nacos server via OpenAPI. Generally, there is a length limit on the url. Does Nacos server have a similar restriction?  If yes, are there other ways to publish large config file via OpenAPI?

**Comment by onewe** [comment]
POST method's body is not limit. you can put it into body,like form submit.
@jxl4650152

**Comment by jxl4650152** [comment]
Thanks. Should this be added to the documentation?
