### ISSUE TITLE
控制台5秒一次ERROR错误: Error to process server push response

### ISSUE THREAD

**Issue by ChannD** [alibaba/nacos#7696]
Naocs服务端版本 2.0.3
具体报错如下, 每5s一次, 一直解决不掉, 也没啥头绪, 可能是gRPC的异常, 请告诉我如何解决这个异常, 感谢.
c.a.n.c.remote.client.grpc.GrpcClient 为 com.alibaba.nacos.common.remote.client.grpc.GrpcClient

Naocs server version 2.0.3
The specific error is as follows, once every 5s, it has not been solved, and there is no clue. It may be an abnormality of gRPC, please tell me how to solve this abnormality, thank you.
c.a.n.c.remote.client.grpc.GrpcClient is com.alibaba.nacos.common.remote.client.grpc.GrpcClient

`2022-01-22 11:45:01.121 ERROR 49916 --- [ient-executor-8] c.a.n.c.remote.client.grpc.GrpcClient    : [1642823094465_127.0.0.1_56998]Error to process server push response: {"headers":{},"requestId":"6006","serviceInfo":{"name":"service-admrank","groupName":"ADM_DIVIESION","clusters":"","cacheMillis":10000,"hosts":[{"ip":"172.22.208.1","port":8012,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"ADM_DIVIESION@@service-admrank","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}],"lastRefTime":1642823101119,"checksum":"","allIPs":false,"reachProtectionThreshold":false,"valid":true},"module":"naming"}
`

**Comment by brotherlu-xcq** [comment]
代码里面没有答应异常堆栈，你结合前面的日志输出看看呢？
https://github.com/alibaba/nacos/blob/a19d3fd068262e2047ee2b1a6a1677b6a18e1741/common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java#L164-L199

**Comment by ChannD** [comment]
> 代码里面没有承诺异常，你结合前面的日志输出看看呢？
> 
> https://github.com/alibaba/nacos/blob/a19d3fd068262e2047ee2b1a6a1677b6a18e1741/common/src/main/java/com/alibaba/nacos/common/remote/client/grpc/GrpcClient.java#L164-L199

感谢, 但是在控制台并没有异常输出, 我不确定是否是nacos服务端推送消息我客户端收不到,还是我客户端推消息服务端收不到. 且在nacos服务端修改配置, @RefreshScope并不生效, pom文件去掉 nacos-client后, @RefreshScope可以正常使用.

**Comment by realJackSun** [comment]
@ChannD 这个日志输出需要开启debug模式之后才能看到的。

**Comment by realJackSun** [comment]
@ChannD 另外你们的业务是否受到影响，还是只是报了这个错误而并未影响业务。
另，或许可以尝试用Arthas抓一下？

**Comment by ChannD** [comment]
> @ChannD 另外你们的业务是否受到影响，还是只是报了这个错误而并未影响业务。 另，或许可以尝试用Arthas抓一下？

我放弃使用了 nacos-client了, 从pom里面去除了此包, 一切变得正常,  @RefreshScope可以正常使用.

**Comment by adminSxs** [comment]
我也遇到这个问题，通过debug发现，好像是PlayloadRegistry中的 REGISTRY_REQUEST，没有注册NotifySubscriberRequest ，从服务端push一个这个类型的消息过来。

**Comment by adminSxs** [comment]
我这里的问题找到了，好像是一个reflections依赖的问题，我的依赖是 0.9.9,改成0.9.11就可以了
```
 <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.11</version>
        </dependency>
```

**Comment by luying777** [comment]
> 我这里的问题找到了，好像是一个reflections依赖的问题，我的依赖是 0.9.9,改成0.9.11就可以了，在启动的时候扫描xxxReqeust，把notifySubscriberReqeuest这个类给忽略了所以没有加入到REGISTRY_REQUEST里面去
> 
> ```
>  <dependency>
>             <groupId>org.reflections</groupId>
>             <artifactId>reflections</artifactId>
>             <version>0.9.11</version>
>         </dependency>
> ```

感谢 @adminSxs，这下解决了；

**Comment by johnnylc** [comment]
> 我这里的问题找到了，好像是一个reflections依赖的问题，我的依赖是 0.9.9,改成0.9.11就可以了，在启动的时候扫描xxxReqeust，把notifySubscriberReqeuest这个类给忽略了所以没有加入到REGISTRY_REQUEST里面去
> 
> ```
>  <dependency>
>             <groupId>org.reflections</groupId>
>             <artifactId>reflections</artifactId>
>             <version>0.9.11</version>
>         </dependency>
> ```

您好 我这边reflections升级到0.9.11还是会报错，请问还需要进行什么操作呢？

**Comment by adminSxs** [comment]
> 
没有了，我就是引入一个依赖就解决了

**Comment by KomachiSion** [comment]
Please use 2.1.0 sdk and retry

**Comment by 2777192213** [comment]
我抛出这个异常：解决的办法是，
          <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>${spring-cloud-starter-alibaba-nacos-config.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.alibaba.nacos</groupId>
                        <artifactId>nacos-client</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>${spring-cloud-starter-alibaba-nacos-discovery.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.alibaba.nacos</groupId>
                        <artifactId>nacos-client</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            `<dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>${本人nacos客户端的版本}</version>
            </dependency>`
这样抛弃服务发现与注册和配置中心的nacos-client的版本号，再引入自己nacos客户端的版本。本人小白，经验稀缺，如有理解不当，还望各位大佬发表你们的宝贵建议。
