### ISSUE TITLE
责任节点向其他节点同步临时实例校验和时，其他节点不更新实例心跳时间戳导致的扩缩容问题

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#7697]
责任节点向其他节点同步临时实例校验和时，其他节点没有更新自己保存的实例时间戳，这些实例时间戳一直都是首次创建的时间戳，当nacos集群扩缩容时，临时实例对应的责任节点发生了变更，大部分实例会变更责任节点，而对应的节点保存的时间戳太过陈旧，心跳检查线程会将这些实例直接下线。

**Comment by zrlw** [comment]
大规模注册实例运行场景下，启动之前停掉的nacos节点也是有问题的：
1. DistroProtocol的isInitialized从false变为true的前提条件是startLoadTask方法执行成功：至少要从其他一个节点获取全部快照成功，大规模实例场景下全部快照获取耗时很长，测试30万实例快照获取耗时大约16秒，已经超出心跳默认超时15秒了；
2. DistroProtocol的isInitialized为false时，TrafficReviseFilter会拒绝收到的临时实例心跳请求；

这样刚刚重启的节点会直接将自己负责的很多实例变成不健康甚至下线了事，然后通过DistroVerifyTask定时任务同步到其他节点，相关实例在所有的nacos节点控制台都会变成不健康甚至DOWN。

这个参数可以在客户端配置注册中心的URL时配置preserved.heart.beat.timeout进行调整，但是客户端如果非常多，难免会有疏漏，nacos服务端尚未提供可以配置的方式，需要自己修改代码。

**Comment by zrlw** [comment]
有一个尚未解决的问题：
当实例数量多的时候，新启动的节点从其他节点拉取快照耗时超过了15秒，这种情况下还需要定制：
方法1：改代码，把默认的心跳超时15秒调大，要超过拉取快照的耗时。
方法2：在nacos集群前面的负载均衡设施增加http健康检查机制，通过httpget对应nacos节点/health接口判断节点是否健康，这样就能把心跳请求绕过正在启动的节点。

这么做的原因在于：打开了监听端口但尚未完成快照拉取操作的节点会把收到的心跳请求拒掉，极端情况下（运气比较差），客户端每次包括重试都把心跳发到了这个节点，那么等待这个节点完成快照拉取，心跳也超时了，注意，这些心跳包括需要转发到其他节点的实例心跳，所以影响的范围不仅是刚启动的节点负责的临时实例，还有其他节点负责的实例。

**Comment by ijustyce** [comment]
我这边是 nacos server 源码改了，不往下推送 空 hosts 信息，即 hosts 为空，则不推送，通过接口拉取时，如果 hosts 为空，则返回 null，这种情况下，我 nacos 三个节点全部宕机，也只影响服务发布，已有服务无影响，主要还得容灾搞好，bug 难免。非常建议官方能将  dubbo.registry.parameters.namingPushEmptyProtection 的配置默认为 true

**Comment by zrlw** [comment]
> 我这边是 nacos server 源码改了，不往下推送 空 hosts 信息，即 hosts 为空，则不推送，通过接口拉取时，如果 hosts 为空，则返回 null，这种情况下，我 nacos 三个节点全部宕机，也只影响服务发布，已有服务无影响，主要还得容灾搞好，bug 难免。非常建议官方能将 dubbo.registry.parameters.namingPushEmptyProtection 的配置默认为 true

可以测试一下这个ISSUE对应的PR，我们之前遇到的no provider问题都是启停nacos节点时出现的，目前修订之后40万注册实例，任意启停节点都不再出现实例变动了，要看各个节点的naming-event.log日志有没有变化，没有变化说明当前节点保存的实例未变化，肉眼看控制台是看不过来的。

**Comment by ijustyce** [comment]
> > 我这边是 nacos server 源码改了，不往下推送 空 hosts 信息，即 hosts 为空，则不推送，通过接口拉取时，如果 hosts 为空，则返回 null，这种情况下，我 nacos 三个节点全部宕机，也只影响服务发布，已有服务无影响，主要还得容灾搞好，bug 难免。非常建议官方能将 dubbo.registry.parameters.namingPushEmptyProtection 的配置默认为 true
> 
> 可以测试一下这个ISSUE对应的PR，我们之前遇到的no provider问题都是启停nacos节点时出现的，目前修订之后40万注册实例，任意启停节点都不再出现实例变动了，要看各个节点的naming-event.log日志有没有变化，没有变化说明当前节点保存的实例未变化，肉眼看控制台是看不过来的。

40万 注册实例啊，你们 nacos server 配置如何？我这边只有 3K 的 dubbo 服务，300 个微服务，我个人查阅源码发现 no provider 有两种可能，一个是请求接口时返回了 空 hosts，一个是推送，只要处理掉这两个即可，这两个是根本原因，比如这个 issue https://github.com/alibaba/nacos/issues/7687
即使心跳正常了，也可能依然出现，类似的问题可能还会有。

**Comment by zrlw** [comment]
#7687也是我提的，这个PR一起搞了，忘了加注解。
这个PR涉及#7687 的修订内容有两部分：
1. Distro协议未完成初始化或完成初始化之后尚未满一个心跳超时（刚启动的节点），不做节点之间的同步，不做udp推送，收到服务列表查询时直接返回空列表（客户端收到空列表不会更新）
2. 当服务列表发生变化时（有新的服务节点加入集群或集群有的节点退出），和1一样暂停同步、推送、返回空列表，等待一个心跳超时后再恢复。
之所以这样做，是因为上述情况下大部分临时实例的责任节点将发生改变，各节点都需要重新收全自己负责的实例心跳，此时如果继续同步或推送，就会把自己没收全的服务实例列表同步给其他节点或推送给客户端。

注册实例推空保护机制我们也曾尝试过，但是我们有服务端实际下线后客户端需要准实时感知的需求，所以这个开关对我们来说用处不大。

**Comment by zrlw** [comment]
目前我们实际的注册实例数量还没有达到这个量级，现在只是先做一下压测，看看是不是还有哪些坑在等着填，server端用的7个16c32g的虚拟机，consumer是自己写的java request测试类，一台windows16c32g模拟了800个服务，每个服务500个实例。

**Comment by ijustyce** [comment]
> #7687也是我提的，这个PR一起搞了，忘了加注解。 这个PR涉及#7687 的修订内容有两部分：
> 
> 1. Distro协议未完成初始化或完成初始化之后尚未满一个心跳超时（刚启动的节点），不做节点之间的同步，不做udp推送，收到服务列表查询时直接返回空列表（客户端收到空列表不会更新）
> 2. 当服务列表发生变化时（有新的服务节点加入集群或集群有的节点退出），和1一样暂停同步、推送、返回空列表，等待一个心跳超时后再恢复。
>    之所以这样做，是因为上述情况下大部分临时实例的责任节点将发生改变，各节点都需要重新收全自己负责的实例心跳，此时如果继续同步或推送，就会把自己尚未收集完整的服务实例列表同步给其他节点或推送给客户端。
> 
> 注册实例推空保护机制我们也曾尝试过，但是我们有服务端实际下线后客户端需要准实时感知的需求，所以这个开关对我们来说用处不大。

我这边暂时没这个需求，所以简单粗暴的进行了推空保护，哦，对了，怎么联系你，以后可以一起多多交流，我目前主要负责我们集团的 nacos 中间件，基本快要踩平了，我在你个人资料中未找到邮箱。

在需要准实时感知 provider 不存在的情况下，你的修改更合理，我这边的情况目前是永远不会出现 下线所有 provider 的情况。

**Comment by zrlw** [comment]
profile填加了邮箱，就是同名sina邮箱，欢迎交流。
我们现在压测环境还触发了一个issue还没有定位： #7698， 压测运行一两天莫名其妙有一个节点提示I/O Reactor STOPPED，节点同步给其他节点的httpclient线程挂了，后果就是这个节点负责的实例无论增加还是减少都是只有它自己知道，其他节点一概收不到这个节点的同步请求。

**Comment by li-xiao-shuang** [comment]
> profile填加了邮箱，就是同名sina邮箱，欢迎交流。
> 我们现在压测环境还触发了一个issue还没有定位： #7698， 压测运行一两天莫名其妙有一个节点提示I/O Reactor STOPPED，节点同步给其他节点的httpclient线程挂了，后果就是这个节点负责的实例无论增加还是减少都是只有它自己知道，其他节点一概收不到这个节点的同步请求。

有交流群 可以进群交流

**Comment by hundanLi** [comment]
> > profile填加了邮箱，就是同名sina邮箱，欢迎交流。
> > 我们现在压测环境还触发了一个issue还没有定位： #7698， 压测运行一两天莫名其妙有一个节点提示I/O Reactor STOPPED，节点同步给其他节点的httpclient线程挂了，后果就是这个节点负责的实例无论增加还是减少都是只有它自己知道，其他节点一概收不到这个节点的同步请求。
> 
> 有交流群 可以进群交流

请问怎么加群

**Comment by zrlw** [comment]
> 
首页README.md 有钉钉群二维码
