### ISSUE TITLE
[1.4.2] AbstractHttpClientFactory的getConnectionManager创建了IOReactorExceptionHandler之后依然会有I/O reactor has been shutdown

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#7698]
参照
https://github.com/alibaba/nacos/pull/6441
在1.4.2的AbstractHttpClientFactory的getConnectionManager增加了IOReactorExceptionHandler之后，
仍然会出现java.lang.IllegalStateException: I/O reactor has been shutdown，后续调用NacosAsyncRestTemplate的所有方法都是java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED，只能重启服务。

出现上述问题的具体过程如下：
5个nacos节点，800个dubbo服务，每个服务400个临时实例，nacos控制台显示32万实例，nacos各节点日志均无异常，
测试leader节点异常，kill -9把leader节点的nacos进程杀掉，剩余4个节点的naming-server日志开始出现告警。
和其他节点相比，出现I/O reactor has been shutdown问题的节点首先的告警日志是
```
[STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: 被杀节点的ip和端口 
org.apache.http.ConnectionClosedException: Connection closed unexpectedly
```
然后才和其他节点一样开始输出
``` 
Exception while request: http://被杀节点/nacos/v1/ns/instance/beat, caused: {}
java.net.SocketException: Connection reset
```
持续输出若干上述异常日志后，然后出现了一条NacosAsyncRestTemplate.delete操作异常：
```
ERROR [IP-DEAD] failed to delete ip automatically, ip: { ... } , error: {}
java.lang.IllegalStateException: I/O reactor has been shutdown
```
之后就是持续的 I/O reactor status: STOPPED了。

还有一个问题是访问这个问题节点的/v1/ns/health/server依然返回健康状态，没办法通过健康检查机制将其排除。

**Comment by zrlw** [comment]
有时kill -9停节点没问题，但再重新启动节点偶尔会出现 I/O reactor status: STOPPED

**Comment by zrlw** [comment]
加了ioreactor.getAuditLog之后终于定位到问题原因是nacos依赖的http-core的版本是4.4.1，http-core-nio的版本是4.4.13, http-core4.4.1的ConnectionClosedException没有缺省构造方法，http-core-nio 4.4.13的HttpAsyncRequestExecutor#endOfInput执行line 356```handler.failed(new ConnectionClosedException());```时触发NoSuchMethodError致使I/O Reactor线程shutdown。

**Comment by hundanLi** [comment]
> 加了ioreactor.getAuditLog之后终于定位到问题原因是nacos1.4.2依赖的http-core的版本是4.4.1，http-core-nio的版本是4.4.13, http-core4.4.1的ConnectionClosedException没有缺省构造方法，http-core-nio 4.4.13的HttpAsyncRequestExecutor#endOfInput执行line 356`handler.failed(new ConnectionClosedException());`时触发NoSuchMethodError致使I/O Reactor线程shutdown。
> 
> java.lang.NoSuchMethodError: org.apache.http.ConnectionClosedException: method ()V not found at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:356) at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261) at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) at java.lang.Thread.run(Thread.java:748)
> 
> nacos2.0没有这个问题，是2.0修订了pom.xml把相应的版本统一到了4.4.13，这也说明1.x分支的确不怎么维护了。

请问在哪里调用ioreactor.getAuditLog可以看到异常日志

**Comment by dingaiminGIT** [comment]
> 

同问

**Comment by zrlw** [comment]
PR#7801 DefaultAsyncHttpClientRequest.java
```
                        LOGGER.error("[DefaultAsyncHttpClientRequest] IllegalStateException! I/O Reactor error time: {}",
                                event.getTimestamp(), event.getCause());
```

**Comment by maguanggit** [comment]
Under what circumstances can this problem be repeated?
