### ISSUE TITLE
debian system us sh error.

### ISSUE THREAD

**Issue by cuisongliu** [alibaba/nacos#77]
system : Deepin 4.14.12-2

sh:  sh bin/startup.sh  or  bin/startup.sh 

"bin/startup.sh: 40: bin/startup.sh: [[: not found"

not use sh an use bash is ok.
then 

``` bash bin/startup.sh```  is ok.

**Comment by nickycheng** [comment]
debian default use dash, not support  [[ ]]
maybe we can replace it.

line 49: if [[ "${MODE}" == "standalone" ]]; then
=> if [ "${MODE}" = "standalone" ]; then

line 60: if [[ "$JAVA_MAJOR_VERSION" -ge "9" ]] ; then
=> if [ "$JAVA_MAJOR_VERSION" -ge "9" ] ; then

line 78: if [[ "${MODE}" == "standalone" ]]; then
=> if [ "${MODE}" = "standalone" ]; then
