### ISSUE TITLE
为啥maven中央仓库里不放0.8.0以上的版本了？

### ISSUE THREAD

**Issue by xcf007** [alibaba/nacos#7701]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
因为服务端的依赖不会以maven形式被用户引用， 只有client相关的依赖会通过maven引用， 因此后续版本不会将服务端相关包上传maven。
