### ISSUE TITLE
如何避免dubbo服务的信息自动注册到配置中心？

### ISSUE THREAD

**Issue by txlaijava** [alibaba/nacos#7703]
Dubbo版本：2.7.15
Nacos版本：2.0.3
Dubbo的服务会注册到配置中心，请问这个是正常逻辑吗？还是什么地方配置有误？这样会导致配置中心的数据越来越多。
![image](https://user-images.githubusercontent.com/12961378/150729282-30d357a6-9914-4e0e-8c57-a1d1a7ec4068.png)

**Comment by KomachiSion** [comment]
It's dubbo's problem, please move to dubbo.
