### ISSUE TITLE
request help: Cooperation invitation from Apache APISIX community

### ISSUE THREAD

**Issue by lijing-21** [alibaba/nacos#7705]
Hi community,

I am Jing Li, from the Apache APISIX community. Apache APISIX is a Cloud-native API gateway, and it is the top-level project of the Apache Software Foundation. You can get more details from GitHub: https://github.com/apache/apisix.

Apache APISIX has added the nacos as service discovery registery.[1] I think it's a meaningful feature for both communities, as it enriches the surrounding ecology of Nacos and APISIX. 

Rencently, we are writing a blog for this feature to explain in detail how to use it.  It will be a nice guide for our developers. In addition, it will help Apache APISIX and Nacos publicize and let more developers and companies know about them. So I am wondering if I could post this blog on the Nacos's blog website when it's finalized.

Looking forward to your reply~

[1]https://github.com/apache/apisix/pull/3820

**Comment by li-xiao-shuang** [comment]
I think it's great

**Comment by KomachiSion** [comment]
Nice information. We are happy to build an ecosystem with other communities.

**Comment by lijing-21** [comment]
Thanks a lot!

The blog may be finished after the Spring Festival. I will submit it at that time~

**Comment by lijing-21** [comment]
Hi, I have submitted this blog[1], please kindly take a look. Thanks!

[1]: https://github.com/nacos-group/nacos-group.github.io/pull/257

**Comment by KomachiSion** [comment]
Nice!, I will review it.

**Comment by KomachiSion** [comment]
> Hi, I have submitted this blog[1](https://github.com/nacos-group/nacos-group.github.io/pull/257), please kindly take a look. Thanks!

Already merged and visible https://nacos.io/zh-cn/blog/index.html
