### ISSUE TITLE
Why signature of com.alibaba.nacos.api.grpc.auto.RequestGrpc.newFutureStub is different in nacos-client and nacos-api

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#7707]
I don't known whether this is a bug or not.

Our team try to upgrade to nacos server 2.0.3 and exception occur when client try to register service. The error say no such method com.alibaba.nacos.api.grpc.auto.RequestGrpc.newFutureStub

Finally we find newFutureStub method has different params in nacos-client and nacos-api

nacos-api:
```java
  public static RequestFutureStub newFutureStub(
      io.grpc.Channel channel) {
    return new RequestFutureStub(channel);
  }
```

nacos-client
```
  public static RequestFutureStub newFutureStub(
      com.alibaba.nacos.shaded.io.grpc.Channel channel) {
    return new RequestFutureStub(channel);
  }
``` 

If add follow code to the top pom.xml the error disappear
```
<dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-api</artifactId>
            <version>2.0.3</version>
            <scope>provided</scope>
</dependency>
```

我们最近在升级 nacos 到 2.0.3 版本，但是客户端报错，找不到 com.alibaba.nacos.api.grpc.auto.RequestGrpc.newFutureStub 这个方法，查阅了源码确认有这个方法，最后发现依赖中有 nacos-client 以及 nacos-api 两个包，但是 nacos-api 中该方法的签名和 nacos-client 中的签名不一致，在 pom.xml 中将 nacos-api 的作用域设置为 provided 后问题修复，不清楚这是bug 还是设计如此？

**Comment by vividfish** [comment]
nacos-client版本是？

**Comment by ijustyce** [comment]
> nacos-client版本是？

nacos-client 版本和 nacos-api 版本均为 2.0.3

**Comment by JasonMing** [comment]
插眼

同样的，看起来是同样的东西，但是shade了之后成了不同类型，导致NoSuchMethodError。

不明白为什么同样的代码不直接使用依赖，而是使用重复打包的方式分别进入 nacos-api 和 nacos-client。。。

**Comment by moxingwang** [comment]
确实是这个问题， 昨天我也遇到，排除了jar 就可以了

**Comment by leeroy-code** [comment]
遇到了+1

**Comment by leeroy-code** [comment]
浪费下好久的时间
