### ISSUE TITLE
nacos服务端，线程数很多，达到几千

### ISSUE THREAD

**Issue by G-Aaron** [alibaba/nacos#7709]
jvm_threads_states_threads{state="runnable",} 561.0
jvm_threads_states_threads{state="blocked",} 0.0
jvm_threads_states_threads{state="waiting",} 3621.0
jvm_threads_states_threads{state="timed-waiting",} 166.0
jvm_threads_live_threads 4349.0

nacos 2.0.3

**Comment by G-Aaron** [comment]
"nacos-grpc-executor-105" #405 daemon prio=5 os_prio=0 tid=0x00007fe6a8067000 nid=0x67fd waiting on condition [0x00007fe5ca316000]
"nacos-grpc-executor-104" #404 daemon prio=5 os_prio=0 tid=0x00007fe6a8065800 nid=0x67fc waiting on condition [0x00007fe5ca417000]
"nacos-grpc-executor-103" #403 daemon prio=5 os_prio=0 tid=0x00007fe6a8063800 nid=0x67fb waiting on condition [0x00007fe5ca518000]
"nacos-grpc-executor-102" #402 daemon prio=5 os_prio=0 tid=0x00007fe6b8dd5000 nid=0x67fa waiting on condition [0x00007fe5ca619000]
"nacos-grpc-executor-101" #401 daemon prio=5 os_prio=0 tid=0x00007fe6b8dd1800 nid=0x67f9 waiting on condition [0x00007fe5ca71a000]
"nacos-grpc-executor-100" #400 daemon prio=5 os_prio=0 tid=0x00007fe6b8dd0800 nid=0x67f8 waiting on condition [0x00007fe5ca81b000]
"nacos-grpc-executor-99" #399 daemon prio=5 os_prio=0 tid=0x00007fe6b80ca000 nid=0x67f7 waiting on condition [0x00007fe5ca91c000]
"nacos-grpc-executor-98" #398 daemon prio=5 os_prio=0 tid=0x00007fe6b80c8000 nid=0x67f6 waiting on condition [0x00007fe5caa1d000]
"nacos-grpc-executor-97" #397 daemon prio=5 os_prio=0 tid=0x00007fe6b80c6800 nid=0x67f5 waiting on condition [0x00007fe5cab1e000]
"nacos-grpc-executor-96" #396 daemon prio=5 os_prio=0 tid=0x00007fe6a8062000 nid=0x67f4 waiting on condition [0x00007fe5cac1f000]
"nacos-grpc-executor-95" #395 daemon prio=5 os_prio=0 tid=0x00007fe6a8060000 nid=0x67f3 waiting on condition [0x00007fe5cad20000]
"nacos-grpc-executor-94" #394 daemon prio=5 os_prio=0 tid=0x00007fe6a805e000 nid=0x67f2 waiting on condition [0x00007fe5cae21000]
"nacos-grpc-executor-93" #393 daemon prio=5 os_prio=0 tid=0x00007fe6a805c800 nid=0x67f1 waiting on condition [0x00007fe5caf22000]

**Comment by ijustyce** [comment]
我这边发现的问题是 client 端近乎疯狂的发送请求给后端，频率很高（600毫秒左右）感觉和你的问题应该是同一个问题，另外，你这个线程数是在哪个文件中查看的，dubbo 服务数量多少个呀？

**Comment by G-Aaron** [comment]
spring cloud 
![image](https://user-images.githubusercontent.com/13374575/150944046-b30e1c53-4628-4ba7-82a8-f1f92ee55443.png)

**Comment by G-Aaron** [comment]
> 我这边发现的问题是 client 端近乎疯狂的发送请求给后端，频率很高（600毫秒左右）感觉和你的问题应该是同一个问题，另外，你这个线程数是在哪个文件中查看的，dubbo 服务数量多少个呀？
我用的spring boot ，客户端也是2.0.3的

**Comment by rmzf9192** [comment]
we meet it too。 thread pool thread is daemonThread

**Comment by YunWZ** [comment]
能否描述一下复现步骤呢?

**Comment by onewe** [comment]
是创建过这么多线程,但存活的线程只有几个? 还是实际存活线程就很多？

**Comment by onewe** [comment]
nacos-grpc-executor 这个玩意儿 waiting 这么多？..

**Comment by G-Aaron** [comment]
嗯，实际创建了这么多，看了下源码，不做任何配置的情况下，我的机器是80c的，默认这个线程池会创建2048个线程，头大，还没有参数配置文档

**Comment by onewe** [comment]
😂 你配置太顶了, 默认参数的情况下,创建出 2048个线程也就正常了。

**Comment by G-Aaron** [comment]
有参数文档么？

**Comment by onewe** [comment]
没有, 你可以参考源码来自定义线程数

**Comment by onewe** [comment]
remote.executor.times.of.processors 和 nacos.core.sys.basic.processors

**Comment by G-Aaron** [comment]
好吧

**Comment by onewe** [comment]
nacos-grpc-executor 和 nacos-cluster-grpc-executor 线程池线程数量 = remote.executor.times.of.processors * nacos.core.sys.basic.processors .
如果不指定的话:
remote.executor.times.of.processors 默认是 16
线程池线程数量就是 核心数*16



写一下,免得后面的人去翻源码

**Comment by ijustyce** [comment]
> Referenc

你这个是 客户端配置还是 server？看你写的配置那么高，不太像是 client 呀。

**Comment by G-Aaron** [comment]
线程池线程数量就是 比 核心数*16 这个值大的 第一个2的次幂。值

**Comment by G-Aaron** [comment]
服务端

**Comment by rmzf9192** [comment]
这个bug修复了？ 为什么关闭了啊？

**Comment by G-Aaron** [comment]
上面不是给解决方案了吗？

**Comment by rmzf9192** [comment]
自己来修改源码，这个最好可以支持自定义线程池的配置。社区中其他人也会遇到这样的问题，其他人在遇到的话，节省时间

**Comment by G-Aaron** [comment]
@rmzf9192 
都是定义好的，配置上去就可以
nacos.core.sys.basic.processors 这个在配置文件里面配置
remote.executor.times.of.processors 这个加到启动脚本里面

**Comment by rmzf9192** [comment]
了解

**Comment by shalk** [comment]
if the nacos node 's machine have very many cpu cores like 64c or 128c,  nacos.core.sys.basic.processors  should be configured.
