### ISSUE TITLE
Nacos's raft may coexist for two leaders for a long time

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/nacos#771]
nacos 的raft可能长时间两个leader并存

要把旧的leader变成follower的前提条件是新leader的term更大。
但是旧leader在变成follower之前，是一直认为自己是leader，就可以处理请求，term就一直增加。
如果新leader的term增加速度更慢的话，新旧两个leader就可能一直共存。

上面说的有点抽象，我下面详细说下：
nacos的raft并不是严格意义上的raft，一个写请求是leader直接成功的，并不需要半数以上的确认。所以旧leader是可以一直认为自己是leader的。

leader变成follower的唯一条件是收到心跳，但是收到心跳还是要判断term的，所以term就成为关键了。
只要旧leader有写请求过来，虽然这个时候不会有其他的follower转发请求过来，但是他本身是会收到鞋请求的，流量不一定均匀，旧leader的流量可能和新leader的流量差不多，就会一直两个leader并存了。

**Comment by nkorange** [comment]
In fact, there are two conditions when leader steps down to follower:
1. receive higher term vote from a candidate;
2. receive higher or equal term heartbeat from a leader;

So no matter what the term of each leader is, they can quickly come to a consensus about who is the leader.

**Comment by huangyunbin** [comment]
你上面的说法是基于一个假设：新旧leader的网络连接是ok的。
当新旧leader网络不通的情况下呢？

**Comment by nkorange** [comment]
这种情况是两个leader，网络分区下无法自动将为Follower，一个写请求到leader就成功，这个是基于客户端会一直心跳上报，这种情况下有多个leader也没关系。并不是所有写请求都会到leader就成功的，要求强一致性的写请求会同步写Follower。
