### ISSUE TITLE
使用docker运行nacos后，读取配置内容中文乱码

### ISSUE THREAD

**Issue by mogoboss** [alibaba/nacos#7714]
1、不在docker中运行时，没有乱码
2、unicode编码在dokcer时没有正确解析为中文
3、jvm中已指定Dfile-encoding=utf-8，一样乱码

**Comment by YunWZ** [comment]
检查你的配置文件编码是否为UTF-8

**Comment by azhsmesos** [comment]
docker 编码和项目编码要一致，否则单独设置utf-8还是会乱码的

**Comment by hzq001** [comment]
`-Dfile.encoding=UTF-8` ，是点不是-
