### ISSUE TITLE
nacos-2.0.3版本在k8s中集群部署，nacos重启后服务无法重新注册

### ISSUE THREAD

**Issue by zhoachenIt** [alibaba/nacos#7716]
在k8s中集群部署nacos-2.0.3版本，我们之后全部重启nacos后，发现我的服务无法自动去注册，只能手动重启每个个服务，才能注册上去，日志上也没有任何报错

**Comment by pengkai242** [comment]
> 在k8s中集群部署nacos-2.0.3版本，我们之后全部重启nacos后，发现我的服务无法自动去注册，只能手动重启每个个服务，才能注册上去，日志上也没有任何报错

兄弟你好，能问下，你出现这个情况，当时客户端版本是2.x的么。你这里重启每个服务，是指的应用服务么，还是nacos服务

**Comment by zhoachenIt** [comment]
你好，客户端是2.x，重启的是nacos服务。

发自我的iPhone

**Comment by yuqigeTwo** [comment]
你好，你应用服务是直接连的nacos节点地址还是集群统一入口地址？

**Comment by huangpj0210** [comment]
请问一下这个问题有解决方案？我也遇到了nacos莫名其妙重启动了，服务注册不上去需要挨个手动重启

**Comment by yuqigeTwo** [comment]
用的2.1.0版本，nacos重启后，业务服务没有自动恢复注册，需要手动一个个重启业务服务

**Comment by Showleen** [comment]
解决了没？

**Comment by yuqigeTwo** [comment]
nacos-client 1.4.1版本貌似有bug，升级到1.4.3好了
