### ISSUE TITLE
nacos 2.0.4 业务日志不打印，只打印nacos的日志

### ISSUE THREAD

**Issue by bestRiven** [alibaba/nacos#7717]
nacos 2.0.4 自己配置的logback业务日志不打印，只打印nacos的日志

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/7596

@hujun-w-2 Is this problem caused by your modified?

**Comment by hujun-w-2** [comment]
![image](https://user-images.githubusercontent.com/39894911/152716879-c60fbbb2-c43e-458e-bf25-a6a5dd572902.png)
我这边测试是正常的，可否发一下具体的重现步骤

**Comment by bestRiven** [comment]
已经解决了 感谢
