### ISSUE TITLE
What is the relationship between enableClientBeat and synchronous asynchronous?

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/nacos#772]
enableClientBeat 和同步异步是什么关系？
![image](https://user-images.githubusercontent.com/1046037/52848312-5e8a3400-3149-11e9-9b57-c629e04c92c7.png)

而且domain.getEnableHealthCheck() 和 domain.getEnableClientBeat()不是二选一冲突的关系吗，为什么还要红框标记的额外判断

**Comment by nkorange** [comment]
There will an article to address this. Briefly speaking, async or sync write is decided by whether the write can be lost. Client mode data can continuously send its beat to server to compensate the data, so it's not so important if the fist write operation is successful.
