### ISSUE TITLE
请增加关于2.0.4版本的加密功能使用说明

### ISSUE THREAD

**Issue by Hello-Linux** [alibaba/nacos#7725]
我看官方新增了配置文件加密存储功能，请问什么时候可以把使用说明放到官方的文档里面呢?不知道这个功能具体怎么使用

**Comment by li-xiao-shuang** [comment]
> 我看官方新增了配置文件加密存储功能，请问什么时候可以把使用说明放到官方的文档里面呢?不知道这个功能具体怎么使用

目前2.0.4只是定义了接口  实际的实现还没有合并呢

**Comment by Hello-Linux** [comment]
@li-xiao-shuang 非常感谢开发同志们的辛勤劳动，这个功能是大家非常期待的功能!!!!!!
