### ISSUE TITLE
Nacos-v1.4.2 Dynamic multi-environment switching profile does not take effect 

### ISSUE THREAD

**Issue by lwx57280** [alibaba/nacos#7731]
I am refactoring the company project configuration file. When integrating the nacos configuration center, I try to dynamically switch the profile file through maven. The dev is activated by default in the pom, but I have manually switched to test in the idea Maven window, which means that the configuration is at this time. The file points to profile.avtive=test, but why does the profile configuration always point to dev after the service is started?
I have tried the following
1. Add the following configuration to the build tag resources/resource of the parent project pom file: 

```<resources>
  <resource>
      <!-- 这里会直接把${profiles.active}对应文件夹下的内容打包到classpath下 -->
      <!--解决：无法识别 @ 在pom文件中加-->
      <directory>src/main/resources/${profiles.active}</directory>
      <includes>
          <include>**/*.yml</include>
          <include>**/*.yaml</include>
      </includes>
      <filtering>true</filtering> <!--这里不能理解为过滤，而是开启替换，为true，表明可以使用${}变量-->
  </resource>
```

## Shared configuration

![20220206182404](https://user-images.githubusercontent.com/33561119/152676601-97dde71b-eee7-41c8-afa0-57afe943057d.png)

![20220206182348](https://user-images.githubusercontent.com/33561119/152954103-30912716-c004-497e-8a84-c4bfa677004a.png)

## dev is activated by default 
![20220206182331](https://user-images.githubusercontent.com/33561119/152676603-a6802a04-1e06-47e0-817a-38a645c86385.png)

## This is the namespace logo of my nacos configuration center

![20220206182404](https://user-images.githubusercontent.com/33561119/152955287-cfdd921b-6dd3-42ea-9902-06b4c7273089.png)

**The nacos version I'm currently using is 1.4.2** 

I'm not sure if this is a nacos bug

**Comment by onewe** [comment]
是不是namespace没有替换到?

**Comment by lwx57280** [comment]
但是我的配置文件中配置namespace 动态根据当前激活环境获取对应配置；我上传了有3张关于配置文件的截图，其中有一张未能加载，我重新上传了截图

**Comment by onewe** [comment]
你的意思是 `@nacos.namespace@`这个属性已经替换成了`test`环境的`namespace`,但是你的`common.yaml`中的redis相关的变量任然是用的`dev`环境的值,或者说是用的默认值?

**Comment by lwx57280** [comment]
> 你的意思是 `@nacos.namespace@`这个属性已经替换成了`test`环境的`namespace`,但是你的`common.yaml`中的redis相关的变量任然是用的`dev`环境的值,或者说是用的默认值?

namespace 和profile都没有切换成功，是不是spring和nacos 之间的问题

**Comment by lwx57280** [comment]
> > 你的意思是 `@nacos.namespace@`这个属性已经替换成了`test`环境的`namespace`,但是你的`common.yaml`中的redis相关的变量任然是用的`dev`环境的值,或者说是用的默认值?
> 
> namespace 和profile都没有切换成功，是不是spring和nacos 之间的问题，我反复进行了各种尝试
1、手动切换maven profile  为test，然后刷新idea  Reimport All Maven配置文件；
2、对project项目进行maven clean install 后启动指定服务期望读取指定激活的环境标识始终不生效；但可以从bootrap.yml 配置参数@profiles.active@ 跳转至parent 父控pom.xml 定位到test 标识
3、当我重新对project 再次进行maven clean install 才生效，然后再次启动服务时又可以，也就是我需要进行两次maven clean install 操作，才可以成功切换环境标识，操作一次是不生成成功，需要进行两次，有点不是很理解

**Comment by onewe** [comment]
这个应该是idea的毛病,有时候会抽风. 手动跑maven命令就没这个毛病.

**Comment by KomachiSion** [comment]
It seems not nacos problem, maybe env problem or spring cloud problem
