### ISSUE TITLE
触发保护阈值有时候会莫名其妙的变成true，我的应用都是正常，重启一下nacos sever就会恢复正常

### ISSUE THREAD

**Issue by xuping962** [alibaba/nacos#7733]
nacos server 2.0.3 
请教各位，触发保护阈值有时候会莫名其妙的变成true，我的应用都是正常，重启一下nacos sever就会恢复正常。基本上每个月都会出现一次

**Comment by YunWZ** [comment]
有复现步骤吗?

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
