### ISSUE TITLE
nacos server 之间集群同步数据不一致

### ISSUE THREAD

**Issue by caorong** [alibaba/nacos#7734]
**Describe the bug**

我在用的nacos版本 1.13，在其之上支持了 httplongpolling，但是核心部分没改动。

线上/测试的 nacos 集群在运行了一段时间后，会发现新重启的实例比其他正在运行的实例少了一些。

我把 nacos 每个实例的instance 数采集到了监控，可以从下面测试环境的监控上很明显的看出： 192开头的机器，有一个实例重启后，实例数少了，172的是异地机房的，请忽略。

<img width="758" alt="image" src="https://user-images.githubusercontent.com/3087340/152730681-02fa3964-eabd-4fca-b9a5-f6035561fc38.png">

ps: 上图的nacos集群，192实例重启前已经运行了至少2个月了，有些instnace 是空的instance。根据线上情况验证，实际影响范围约1%。

我自查了下原因，nacos 集群之间同步的数据源是 datums 里面的datamap，但是，nacos client 拉的数据是从 serviceManager 里的 serviceMap 里面获取的。

然后，我对 serviceMap 也开了个类似 datums 的接口，用来查询instance 里面所有数据，发现确实 2边数据不一致，并且 datum里面的key 都没了。

某一个service，serviceManager 里面有，但是 datum 没有，所以新启动的实例，通过datums 数据同步，自然实例数少了，某些 service 没同步到。

所以，当前的现象是，运行中的nacos实例，由于会自动切换service的负责人或其他原因，导致自己的 datum数据和 serviceMap 数据不一致。

如何观察到数据不同步的情况？

可以在 ServiceController 里面的 POST: /status 接口内部，加一个日志。

```java
if (service == null) {
     LOG.warn("service :{} exist in remote:{}, but not in local:{}", serviceName, serverIP, NetUtils.localServer());
     continue;
}
```

所以，问题是，什么情况下，会导致 datums 的key 被删除？ 从而引发这个问题

我对datasotre 的 put 和 remove 操作加了日志，通过日志发现，仅会通过 onReceiveChecksums 的时候，才会删除datastore 里面的key。

后续通过日志分析，猜测大概流程如下。

1. serviceA 注册到 nacosA
2. nacosA 和集群断连，集群认为nacosA挂了， 但是，serviceA 不知道集群脑裂情况，心跳却还发到nacosA
3. 集群中接管 serviceA 的 nacosB 认为没心跳，将serviceA instnace 删除。
4. nacosA 和集群恢复，通过nacosB 同步数据，oonReceiveChecksums 时，将serviceA 的 datum 的key 删除。
5. nacosA 接管serviceA，但是 dataum不存在，service存在
6. serviceA 心跳继续发给nacosA，但是nacosA 上查不到service 了，其他nacos 实例可以查到该service。

**Expected behavior**

长期运行的 nacos server 应当保持他的 datum 和 serviceMap 数据一致。

即使不一致也应当有一个自我修复的方法。

优化思路
首先，针对临时节点来说，宁可数据多也不愿意数据丢，要尽可能保证数据不会丢失。
1. nacos 应该对上述情况有一个自动的修复方案，需要时刻保证 datum 和 serviceMap的一致。
2. nacos 删除instance 时，不能光靠client发来的beat 来续命，删除之前可以再从nacos server 处再主动做下healthcheck。

优化方案
1. 发送心跳的时候，检测下dataStore是否存在，如果不存在，根据beat信息重新register到ServiceManager，进而内部重新put dataStore。
2. 现在的Ephemeral 方式，期望在nacos集群不稳定/脑裂时，也能不丢失节点，在心跳失效后，在服务端处主动探活。

上述实现我已经在本地/测试验证通过，麻烦看下是否有更好方法，我可以提下pr

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

1. 启动一个standalone nacos 实例
2. 持续发心跳到 这个 nacos 实例
3. 删除datum 里面的数据
4. 可以发现 datum 数据没有了，但是 servicemap 数据存在，之后同步过程中，该service 将无法再同步。

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by caorong** [comment]
1.2.x 通过20404 code 在client触发 重新register，不存在新老版本client问题，该方法已够用。

**Comment by liulei08** [comment]
这个问题后续有进展吗？最新版本的nacos有修复这个问题吗？

**Comment by liulei08** [comment]
> 1.2.x 通过20404 code 在client触发 重新register，不存在新老版本client问题，该方法已够用。

上述问题你们后面的处理方案是怎么样的？1.4.X版本有修复这个问题吗？
