### ISSUE TITLE
about client

### ISSUE THREAD

**Issue by Cocowwy** [alibaba/nacos#7738]
com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy#registerService

![image](https://user-images.githubusercontent.com/63331147/152998279-6975aeb8-d596-4af9-9116-4d74705c69ff.png)

This variable  “enable” has been defined

can use ENABLE_PARAM instead of “enable”

**Comment by YunWZ** [comment]
I think it's a bug.

**Comment by hujun-w-2** [comment]
服务端优先使用enabled来接受参数，同时兼容了enable来接受参数
客户端代码应该使用enabled来进行传参
