### ISSUE TITLE
jdk17 not support

### ISSUE THREAD

**Issue by readazusa** [alibaba/nacos#7739]
Currently, the spring boot version used by Nacos is 2.1 x. The current version of ASM does not support jdk17. Can you consider upgrading the version of springboot to adapt to jdk17

With springboot 3 0 will be GA soon. The required baseline version is jdk17. Nacos recommends upgrading it for longer-term development. thanks

**Comment by rola0411** [comment]
@KomachiSion 这个计划日期别再改了兄弟们

**Comment by KomachiSion** [comment]
> @KomachiSion 这个计划日期别再改了兄弟们

Nobody want to do this, so still delay version. @rola0411 If you want to do, you can contribute it.

**Comment by ijustyce** [comment]
develop 分支最上层 的 pom.xml 中，spring boot 版本已经是 2.6.8 了，spring boot 2.5.5 开始支持 jdk17（但 lombok 有bug，不过 2.5.6 已修复），spring boot 2.6.8 对 jdk17 的支持应该是完美的，目前的问题是 nacos 源码不支持 jdk17 吗？
比如使用了反射等，这种情况下，通过 --add-opens 是否能解决呢？jdk17 的 zgc 性能实在是好的离谱，期待支持 jdk17，即使是通过 --add-opens 来达到目的。 
```
 <!-- dependency version -->
 <spring-boot-dependencies.version>2.6.8</spring-boot-dependencies.version>
```

**Comment by ijustyce** [comment]
> develop 分支最上层 的 pom.xml 中，spring boot 版本已经是 2.6.8 了，spring boot 2.5.5 开始支持 jdk17（但 lombok 有bug，不过 2.5.6 已修复），spring boot 2.6.8 对 jdk17 的支持应该是完美的，目前的问题是 nacos 源码不支持 jdk17 吗？ 比如使用了反射等，这种情况下，通过 --add-opens 是否能解决呢？jdk17 的 zgc 性能实在是好的离谱，期待支持 jdk17，即使是通过 --add-opens 来达到目的。
> 
> ```
>  
>  <spring-boot-dependencies.version>2.6.8</spring-boot-dependencies.version>
> ```

我基于 develop 分支构建了 nacos server，并使用 jdk17启动，运行正常，服务注册正常，配置管理正常。

**Comment by KomachiSion** [comment]
Nacos代码没有使用很高级的特性，考虑到很多旧版本兼容问题，很多lamda语法糖都比较克制的使用， 我理解只要jdk是兼容的，nacos不需要太大的改动， 如果2.6.8的spring boot已经支持jdk17， nacos应该也能支持，除非有依赖不支持，需要单独列出来看是否能升级支持。

**Comment by ijustyce** [comment]
> Nacos代码没有使用很高级的特性，考虑到很多旧版本兼容问题，很多lamda语法糖都比较克制的使用， 我理解只要jdk是兼容的，nacos不需要太大的改动， 如果2.6.8的spring boot已经支持jdk17， nacos应该也能支持，除非有依赖不支持，需要单独列出来看是否能升级支持。

[spring boot 官方是 2.5.5 开始支持 jdk17](https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/getting-started.html#getting-started.system-requirements)，但该版本默认的 lombok 有bug，2.5.6 已修复。2.6.8 支持 jdk17 不会有任何问题了。 我的看法是，这个 issue 应该是已完成了，基于 develop 分支构建的 nacos server，可以使用 jdk17 正常启动，不需要任何额外的配置，且服务注册、配置增删改工作正常。

**Comment by KomachiSion** [comment]
那2.1.1版本开始就已经升级到这个版本了， 所以2.1.1应该也是可以jdk17了。
