### ISSUE TITLE
The ip of the heartbeat renewal should be compensated if it does not exist on the nacos server.

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/nacos#774]
心跳续约的ip如果在nacos服务器不存在，应该要补偿注册

addIp4Dom还没有通知到其他的nacos  server，这个时候leader挂了。其他的nacos 服务器是没有这个ip的。这种情况下，心跳是直接空跑的，应该补偿注册的。

![image](https://user-images.githubusercontent.com/1046037/52849288-a1e5a200-314b-11e9-8925-67709f701ef9.png)

**Comment by nkorange** [comment]
Please refer to ApiCommands.clientBeat to see how the data is compensated.
