### ISSUE TITLE
服务的EndPoint 访问404

### ISSUE THREAD

**Issue by chaixiaoxue** [alibaba/nacos#7744]
nacos 版本 2.0.4
spring-cloud-alibaba 版本 2.2.7.RELEASE

**Comment by onewe** [comment]
会不会是配置文件里没开?

**Comment by java-aodeng** [comment]
默认就是true  https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery

**Comment by onewe** [comment]
@chaixiaoxue 能否提供一下详细的配置,我这边复现一把？

**Comment by onewe** [comment]
wiki 写的有点问题, http://127.0.0.1:8081/actuator/nacosdiscovery,没有中间的横杠.
@java-aodeng @chaixiaoxue

**Comment by chaixiaoxue** [comment]
@onewe 使用你发的这个url 可以访问，就是wiki写的有点问题

**Comment by chaixiaoxue** [comment]
已解决
