### ISSUE TITLE
The data synchronization of the nacos server depends on the heartbeat of the leader. It is very cumbersome to send all the keys and the corresponding version number.

### ISSUE THREAD

**Issue by huangyunbin** [alibaba/nacos#775]
nacos服务器的数据同步依赖于leader的心跳，要发送所有的key和对应的版本号，会非常的笨重。

服务发现的服务数量会非常的多，万级甚至十万级，遍历操作会比较繁琐，发送的数据包也会比较大，而且主要是大部分都是相同的，有很大的浪费。

**Comment by nkorange** [comment]
服务量在10万以下这个已经测试过，可以承受的。更大的量，其实已经不是优化这个心跳能解决的了，可能需要考虑集群拆分或者分片。
