### ISSUE TITLE
caused: user nacos,nacos not exist!;

### ISSUE THREAD

**Issue by shootday** [alibaba/nacos#7750]
nacos server  1..4.3 update password ：caused: user nacos,nacos not exist!;

**Comment by shootday** [comment]
springmvc  string类型的参数 在url后面以及form data里面同时有时会拼接

**Comment by jerrychern** [comment]
> nacos server 1..4.3 update password ：caused: user nacos,nacos not exist!;

1.4.2没有这个问题，这是由于PR #5566 导致，这个PR在每一个请求上都加上了 *username* ， 这个username是当前登录用户的username，导致修改用户密码的时候请求携带了两个username，后端处理的时候，收到了一个username的数组，合二为一，两个value用 , 分割了。
建议 @KomachiSion 修复一下。

**Comment by SixyuanData** [comment]
我试了一下，第一次1.4.3修改密码请求多了个username，第二次1.4.2一样，第三次1.4.1修改密码成功，切换回1.4.2、1.4.3均修改密码成功。

**Comment by hxy91819** [comment]
测试了1.4.2和1.4.0两个版本，均存在这个问题。

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/8814856/158932316-7d7f2332-74d2-40e8-b508-a92944044f36.png">

**Comment by HuangZurong** [comment]
> nacos server 1..4.3 update password ：caused: user nacos,nacos not exist!;

可以临时把http包修改一下手动提交，去掉请求url中的username参数

**Comment by hais1992** [comment]
测试了  2.0.4 一样存在这个问题。 。。。。。。。。。。。。，一个半月过去了

**Comment by li-sen** [comment]
1.4.3 2.04 使用默认存储 都是无法改默认密码。。。

**Comment by fengyonghui** [comment]
这个的发布版本在哪里？
