### ISSUE TITLE
2.0.4版本里的DDLsql建表脚本执行报错啊

### ISSUE THREAD

**Issue by hqink** [alibaba/nacos#7753]
大佬们，最新版本的sql脚本咋放到mysql里执行各种报错呢？是主流mysql库的设置吗？

**Comment by xjq1019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by MrYuguangbao** [comment]
您的邮件已收到，我会尽快给你回复。

**Comment by hujun-w-2** [comment]
报错能贴出来吗？包括mysql的版本
