### ISSUE TITLE
Nacos1.4.1节点间健康探测设计问题

### ISSUE THREAD

**Issue by lualeslie** [alibaba/nacos#7762]
有个Nacos集群节点间健康探测逻辑设计方面的问题，1.4.1版本采用了通过/v1/core/cluster/report接口的双向健康探测方式，包含了主动探测其它集群节点的可访问性以及上报自身状态给其它节点（双向方式），但是在1.3.0及之前版本采用的是/operator/cluster/state接口的单向健康探测方式，即节点将自身状态上报给其它节点。
想了解下由单向探测改为双向探测的考虑是什么？改造后的优势在哪？

**Comment by realJackSun** [comment]
添加了双重保险。双向探测保证宕机的Nacos节点更及时地被发现。

**Comment by lualeslie** [comment]
是这样的，我们遇到一种情况，Nacos节点A域名不可访问了，使得节点B探测A是失败，设置为DOWN，但是节点A又能主动上报状态给节点B，这就导致又变成UP了，所以无法维持DOWN状态，这种情况下双向探测就会存在问题了，你们有遇到这种问题吗？有什么处理方法？

**Comment by lualeslie** [comment]
> 添加了双重保险。双向探测保证宕机的Nacos节点更及时地被发现。

上面描述的问题有什么办法可以解决这个问题

**Comment by tokyohost** [comment]
“节点A又能主动上报状态给节点B” A和B 的网络是可达的重新UP 挺合理呀，如果A到B 可达，B调用A不可大，问题应该在网络上而不在nacos吧。。

**Comment by lualeslie** [comment]
> “节点A又能主动上报状态给节点B” A和B 的网络是可达的重新UP 挺合理呀，如果A到B 可达，B调用A不可大，问题应该在网络上而不在nacos吧。。

有时候网络问题是不可控的，我的理解是Nacos针对这种网络问题可以更加稳定点，另外双向比单向来看主要是时效性，这个是可以修改解决的，单向还有什么劣势？这点目前还不清楚
