### ISSUE TITLE
nacos解压后没有bin目录

### ISSUE THREAD

**Issue by myIslzj** [alibaba/nacos#7768]
nacos压缩包解压后，找不到bin目录

**Comment by onewe** [comment]
Isn't it right here? 
![image](https://user-images.githubusercontent.com/38708836/153974222-5ba2dabe-1965-4600-89c9-4f12bfa34551.png)

**Comment by realJackSun** [comment]
@myIslzj 你使用的是哪个版本？以及解压方式是？

**Comment by realJackSun** [comment]
Long time no response, close.
