### ISSUE TITLE
项目配置文件存在相应配置节点时，项目初始化不会获取nacos server中的配置

### ISSUE THREAD

**Issue by Shu-001** [alibaba/nacos#7769]
springboot项目2.3.12  nacos  官方demo
获取配置useLocalCache
![image](https://user-images.githubusercontent.com/68310544/153975390-bd31f8b1-fa62-4629-9d23-b5cb13b3f35a.png)
当配置在项目配置文件中存在
![image](https://user-images.githubusercontent.com/68310544/153975487-3637a39d-28be-410f-b39c-10155a315246.png)
nacos server上也有相应配置
![image](https://user-images.githubusercontent.com/68310544/153975587-de7e055c-a7ef-4ff5-910f-29a38a7f4a8f.png)
服务初始话后 获取到的仍为配置文件中的值
![image](https://user-images.githubusercontent.com/68310544/153975778-ff33ea60-e62b-4e97-a44f-e3979dc7d380.png)
此时 对nacos server中值重新赋相同值也不会刷新  只有将nacos server中值变更才会刷新(先改为false再改成true)
![image](https://user-images.githubusercontent.com/68310544/153975927-13b27ede-9e9a-4171-90c1-a14c997dac6b.png)
![image](https://user-images.githubusercontent.com/68310544/153975974-f03c3868-2fe9-4f8a-b330-cd6c57897e49.png)
![image](https://user-images.githubusercontent.com/68310544/153976018-acb1ecc5-5ec0-4deb-8972-a6d972964486.png)

**Comment by realJackSun** [comment]
有没有配置@NacosPropertySource注解呢?

**Comment by Shu-001** [comment]
> 有没有配置@NacosPropertySource注解呢?

工程启动项上有配置的  
![image](https://user-images.githubusercontent.com/68310544/153980425-a8dbc99d-506a-4fc8-9a5f-01a6875a71ec.png)

**Comment by onewe** [comment]
是不是和这个属性有关?`nacos.config.remote-first=true`[文档](https://github.com/nacos-group/nacos-spring-boot-project/wiki/spring-boot-0.2.7-%E4%BB%A5%E5%8F%8A-0.1.7-%E7%89%88%E6%9C%AC%E6%96%B0%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C#nacos-config-spring-boot)

**Comment by hujun-w-2** [comment]
nacos.config.bootstrap.enable =true  这个配了没 springboot应用的话，需要配一下这个初始化才会加载配置

**Comment by hujun-w-2** [comment]
> 
nacos.config.remote-first=true这个参数是设置优先级，如果是这个参数没设的话，修改配置应该也会读取本地的值

**Comment by hujun-w-2** [comment]
> 
nacos.config.remote-first=true这个参数是设置优先级，如果是这个参数没设的话，修改配置应该也会读取本地的值

**Comment by Shu-001** [comment]
> nacos.config.bootstrap.enable =true 这个配了没 springboot应用的话，需要配一下这个初始化才会加载配置
nacos.config.bootstrap.enable =true 这个参数是否还要配合其他参数一起使用，配上直接报错
![image](https://user-images.githubusercontent.com/68310544/154387917-0f255053-9a9c-4585-aafe-0aa48c75f9e1.png)

nacos.config.remote-first=true 这个配上 也没生效
配置如下
![image](https://user-images.githubusercontent.com/68310544/154387892-61f6071e-4b79-4815-b1b0-91eecd165506.png)
springboot 2.3.12.RELEASE;  nacos-config-spring-boot-starter 0.2.10

**Comment by onewe** [comment]
@Shu-001 你nacos server的版本是多少,我来复现一把看哈

**Comment by Shu-001** [comment]
> @Shu-001 你nacos server的版本是多少,我来复现一把看哈

docker部署的 docker.hub拉的最新的镜像 2.0.4

**Comment by onewe** [comment]
```properties
nacos.config.server-addr=127.0.0.1:8848
nacos.config.data-id=example
nacos.config.type=properties
useLocalCache=false
nacos.config.remote-first=true
nacos.config.bootstrap.enable=true
nacos.config.bootstrap.log-enable=true
```

**Comment by onewe** [comment]
@Shu-001 刷新的问题是因为要对比md5如果md5一致的话就不会进行刷新

**Comment by Shu-001** [comment]
> ```ini
> nacos.config.server-addr=127.0.0.1:8848
> nacos.config.data-id=example
> nacos.config.type=properties
> useLocalCache=false
> nacos.config.remote-first=true
> nacos.config.bootstrap.enable=true
> nacos.config.bootstrap.log-enable=true
> ```
> 
> 关键配置是
> 
> ```ini
> nacos.config.bootstrap.enable=true
> nacos.config.remote-first=true
> # 如果没有这个配置会出现空指针异常
> nacos.config.type=properties
> ```

果然 必须手动指定nacos.config.type
cloud版本的 默认是properties  
想当然了
![image](https://user-images.githubusercontent.com/68310544/154601637-85d2593d-7b1f-4f7d-bef3-dfab52ecac7b.png)
然后cloud版本的2.2.7竟然不行  2.2.6可以   2.2.7使用的nacos client是2.0版本  2.2.6用的1.4  让我以为是版本bug
