### ISSUE TITLE
Questions about using the "ephemeral" option

### ISSUE THREAD

**Issue by zhu121** [alibaba/nacos#7773]
Version: 2.0.4

**Describe the bug**
when registering an instance, the ephemeral value is true and then changed to false

**Expected behavior**
can be used normally

**Acutally behavior**
error log: “Current service DEFAULT_GROUP@@xxx is ephemeral service, can't register persistent instance”

**Additional context**
how to clear the relevant data records can facilitate the test

**Comment by hujun-w-2** [comment]
请问是集群模式吗，通过sdk注册，还是nacos 提供的http协议的api来注册的？

**Comment by zhu121** [comment]
> 请问是集群模式吗，通过sdk注册，还是nacos 提供的http协议的api来注册的？

运行环境：Linux 5.10.16.3-microsoft-standard-WSL2 x86_64
运行模式：bash startup.sh -m standalone
注册方式：go代码中使用nacos-sdk-go的v2.0.0，相关接口RegisterInstance()
其他问题：代码中注册成功且能查询到实例，但是在页面的服务列表里看不到数据

**Comment by zhu121** [comment]
> 先 deregister 掉，再修改 ephemeral的值，再注册 或者初始化别的 namingService对象进行注册，不要用同一个客户端对象 一个namingService对象注册某个服务的实例，不可能既是临时的，又是持久的

确实，之前的用法错了，谢谢

**Comment by cpj555** [comment]
我这边用的nacos的openapi 碰到相同的问题 。 
流程就是创建服务-创建服务实例-心跳
从表现来看ephemeral不管设true还是false,  心跳beat的接口总是返回caused: errCode: 400, errMsg: Current service xx@@xx is persistent service, can't register ephemeral instance. ;
阿里的nacos(会显示是否是临时实例,都是显示否)和自建的nacos都试过了

**Comment by DualHappiness** [comment]
看起来是前端显示有问题
