### ISSUE TITLE
我使用配置模式部署Nacos单节点测试，为什么还是能够使用注册中心的功能？

### ISSUE THREAD

**Issue by kuaile-zc** [alibaba/nacos#7774]
**Describe the bug**
我使用配置模式启动  -Dnacos.functionMode=config
发现好像nacos只是往环境变量里面注入了一个值其他的配置中心
源码逻辑如下：
初始化:
![图片](https://user-images.githubusercontent.com/37325510/154213344-2c2031f4-78b9-4bbb-bf7c-9462fcddaa76.png)
往环境变量插入 nacos.function.mode    config（all/naming）的值而已
![图片](https://user-images.githubusercontent.com/37325510/154213897-fe18f366-764b-4de9-91a1-0ccec85e0c51.png)

后续也未作任何操作
然后我尝试在config模式下面注册服务发现能够成功。
请问这个情况是否符合整个架构设计预期，选择不同模式启动是否在当前版本下暂时没什么区别？

**Desktop (please complete the following information):**
 - OS:  Windows10
 - Version nacos-service 1.4.2
 - Module config
 - SDK spring-cloud-alibaba-nacos

**Comment by onewe** [comment]
同样好奇

**Comment by kuaile-zc** [comment]
@realJackSun 您好官方开发者！这个启动模式问题能给一个回复吗，十分感谢。(*^▽^*)

**Comment by five111** [comment]
同样好奇这个问题
