### ISSUE TITLE
Data inconsistency (a-b-a) caused by concurrent execution of DumpAllProcessor and DumpProcessor

### ISSUE THREAD

**Issue by Nailcui** [alibaba/nacos#7780]
DumpAllProcessor和DumpProcessor 并发执行导致的数据不一致（a-b-a）问题

**Describe the bug**

0. At the beginning, configure group: test, dataid: test, content: a
1. During the execution of dumpallprocessor, the old version data a is queried from DB; Then start dump; Content: a
2. At this time, the configuration change triggered from the console will change a to B (at this time, DB, memory and disk have been changed); Content: B
3. The dump of step 1 starts to execute, changing B to a; Content: a
4. At this time, the configuration goes through a - > b - > A; The final configuration is a
Due to the above logic of parallel execution, the data A-B-A on the single machine; And data inconsistency between cluster nodes

0、开始时候，配置group: test，dataId: test，content: a
1、DumpAllProcessor 执行时候从db查询到了旧版本的数据a；此时content：a
2、此时从控制台触发的配置变更将a改为了b（此时db、内存、磁盘都已变更）；此时content：b
3、步骤一的dump开始执行，将b改为了a；此时content：a
4、此时配置经历了 a->b->a；最终配置是a
由于上面这种并行执行的逻辑，导致了单机上的数据a-b-a；以及集群节点间的数据不一致

**Expected behavior**

The last thing you want to query about this configuration is b
希望最后查询到此配置的内容是 b

**Acutally behavior**

The content of this configuration is a
查询到此配置的内容是a

**How to Reproduce**

1. Modify the logic of dumpallprocessor to make this case easier to reproduce. After querying the data from DB, sleep for a period of time, and then execute the next step
2. Modify the configuration to a new value and query to get a new value
3. Wait for dumpallprocessor to finish executing, and query the old value

1. 修改下DumpAllProcessor的逻辑使得此case更容易复现，从db查询到数据后sleep一段时间，sleep时候执行下一步骤
2. 修改配置为新值，查询可以得到新值
3. 等待DumpAllProcessor执行完毕，查询得到旧值

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [nacos-server 2.0.4]
 - Module [e.g. config]

**Comment by Nailcui** [comment]
![image](https://user-images.githubusercontent.com/15919746/154421639-db9023d3-fa0a-43be-9190-9b6758d0f297.png)

**Comment by onewe** [comment]
加上最后修改时间对比逻辑 应该能解决

**Comment by onewe** [comment]
@onewe will solve it@

**Comment by Nailcui** [comment]
@onewe “加上最后修改时间对比逻辑 应该能解决”，如果这种方案可以的话，那我提交一个pr来解决可以吗

**Comment by onewe** [comment]
我感觉可以哈 😂  欢迎提PR
