### ISSUE TITLE
2.0.4 GRPC health check path

### ISSUE THREAD

**Issue by whpei93** [alibaba/nacos#7781]
Hi Team,

三台nacos挂在aws的alb后面，现在要加上grpc的端口，请问检查方法的路径是什么？
下面这是aws文档
如果协议版本是 gRPC，请使用格式 /Package.Class/method 指定自定义运行状况检查方法的路径。默认为 /AWS.ALB/healthcheck。

**Comment by myifeng** [comment]
@whpei93  你使用ALB访问Nacos成功了吗？我这边一直9848连接不上，求助~

**Comment by whpei93** [comment]
> 

alb可以的访问的

**Comment by myifeng** [comment]
@whpei93 ELB用的什么协议代理的？我们的ELB工程师说gRPC只能用https，但是nacos client发出来的是http，所以ELB直接400错误，到不了nacos server。能帮忙详细说下您的ELB的配置吗？
