### ISSUE TITLE
send heart to nacos, but the response is 302

### ISSUE THREAD

**Issue by katelei6** [alibaba/nacos#7782]
**Describe the bug**
When we send heart to nacos, but the response is 302, so send failed.

**Expected behavior**
The code is same ,so what about code 302's mean?

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by hujun-w-2** [comment]
确定服务端是1.3.1吗，在2.x的服务端中302是grpc找不到handler，在1.x的开发分支中我没看到302的状态码
