### ISSUE TITLE
请问nacos的默认端口号为什么会变成8080

### ISSUE THREAD

**Issue by vb637** [alibaba/nacos#7784]
简单描述下问题发生的前置

我想在macos上部署集群环境，在三个端口启动nacos
我修改了startup.sh文件，使其能够从命令行获取端口号以启动

`while getopts ":m:f:s:c:p:t:" opt
do
    case $opt in
        m)
            MODE=$OPTARG;;
        f)
            FUNCTION_MODE=$OPTARG;;
        s)
            SERVER=$OPTARG;;
        c)
            MEMBER_LIST=$OPTARG;;
        p)
            EMBEDDED_STORAGE=$OPTARG;;
        t)
            PORT=$OPTARG;; //修改处1
        ?)
        echo "Unknown parameter"
        exit 1;;
    esac
done`

`nohup $JAVA -Dserver.port=${PORT} ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &`

修改处如上，但是如果我不带端口号启动，则nacos被部署到了8080端口号上，如果我撤销修改，则重新部署到8848，我知道nacos的默认端口是8848（我猜测是application.properties中设置的），但是我不明白为什么会获取到8080端口号，8080又是在哪里设置的呢。

**Comment by Liubey** [comment]
把-Dserver.port=${PORT}改成--server.port=${PORT} 强制springboot走这个端口也行
