### ISSUE TITLE
你好如何获取本地实例在nacos中的ip地址？

### ISSUE THREAD

**Issue by changyoutianxia** [alibaba/nacos#7794]
你好如何获取本地实例在nacos中的ip地址？

**Comment by Liubey** [comment]
从namingservice中拿到节点列表，遍历出本jvm匹配的ip和port？

**Comment by lpaz010** [comment]
本地服务实例启动时有日志，查看Finished auto register service : serviceName-demo, ip : 1.1.1.1, port : 8080

**Comment by changyoutianxia** [comment]
有没有个切入点？

**Comment by realJackSun** [comment]
> 有没有个切入点？

你的意思是要查看注册的实例的IP？
可以通过Java API或者OpenAPI或控制台查看。参考

**Comment by changyoutianxia** [comment]
没有，，，
