### ISSUE TITLE
nacos 1.3.1  升级到 2.0.4 显示 upgrade.state file is not exist

### ISSUE THREAD

**Issue by FengJinghHua** [alibaba/nacos#7814]
有点疑惑，我的环境nacos1.3.1是有配置数据的，我在进行升级到2.0.4时，参照https://nacos.io/zh-cn/docs/2.0.0-upgrading.html 升级文档，下载并解压缩nacos-server-2.0.4.tar.gz，将其下的bin，conf，target目录覆盖原Nacos1.X的安装目录下。然后修改相关的conf application.properties配置，我期待能在logs/naming-server.log 上看到类似upgrade check result等日志，但是没有，只有 upgrade.state file is not exist ；我的操作都是参考升级文档，为什么会出现不一致的结果，有点疑惑。

**Comment by onewe** [comment]
我猜你是单机模式而非集群?
@FengJinghHua

**Comment by FengJinghHua** [comment]
@realJackSun 是的，但是升级文档上也写了可以是单机的模式，所以这是一个正常的情况？

**Comment by onewe** [comment]
![image](https://user-images.githubusercontent.com/38708836/155446160-c5a327cc-f8a1-404d-8d90-dd993bd31b38.png)
文档上说的是集群吧

**Comment by vividfish** [comment]
检查下你的${nacos.home}/data（如果没有特别指定，一般在~/nacos/data下）下有没有upgrade.state文件

**Comment by FengJinghHua** [comment]
我检查过了，没有upgrade.state文件，所以如果环境是单机的情况下，怎么判断是否升级成功呢 @onewe

**Comment by vividfish** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/24951831/155477339-63f6e227-9c9f-40b0-9b3d-e95156204b61.png">
看了下源码 好像单机模式的情况下并不会生成这个文件，所以应该是正常的。
单机环境下应该不需要走升级过程

**Comment by onewe** [comment]
@FengJinghHua 这个就要问问官方了,我单机没升级过

**Comment by KomachiSion** [comment]
单机模式下是直接升级完成的，不需要进行升级check。反正就自己一台，启动就是完成的。
