### ISSUE TITLE
Nacos configuration read problem

### ISSUE THREAD

**Issue by vonzou** [alibaba/nacos#782]
我使用的依赖是nacos-config-spring-boot-starter:0.2.1，应用框架基于spring-boot:2.6.5

1. 在nacos控制台添加了一个配置项  switch=123456,配置格式为Properties，发布
2. 应用程序读取该项配置，默认值取11111，可正确读取到控制台的配置值123456
   3.将控制台中的配置更新为switch=1234567，发布
   4.应用程序读取该项配置，默认值取11111，可正确读取到控制台的配置值1234567
   以上都没问题
3. 将控制台中该项配置删除（或使用#注释掉），发布
   6.应用程序读取该项配置，默认值取11111，可正确读取到控制台的配置值1234567

按理说控制台配置已经被删除了，第6步应该读取到的值是11111，而不是1234567。 请关注该问题

**Comment by nkorange** [comment]
Repeat issue
