### ISSUE TITLE
鉴权漏洞问题

### ISSUE THREAD

**Issue by jiangboHb** [alibaba/nacos#7823]
After single start nacos, through http://localhost:8848/nacos/v1/auth/users? PageNo =1&pageSize=1, the user list is returned. The cluster mode is not tested yet

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/155288068-b7d8a977-9608-42cd-9e37-0841d68ad119.png)

test version 2.0.3.

I think you do not open auth.

**Comment by samfaker** [comment]
提供一种解决思路，在负载机上，如果使用nginx，可以在放开nacos/v1/auth/users/login的同时对nacos/v1/auth/users加上权限验证
![image](https://user-images.githubusercontent.com/23623372/155448416-8d9a8f58-035c-46cc-a3de-0737cdcd29a8.png)

**Comment by wt345316277** [comment]
v2.1.0
