### ISSUE TITLE
请问不同环境部署有最佳实践建议吗？

### ISSUE THREAD

**Issue by ProdigalWang** [alibaba/nacos#7825]
比如开发、测试、生产等多套环境
使用Nacos作为配置中心和注册中心，
1.不同环境公用一套nacos, 根据不同namespace区分
2.不同环境使用不同的nacos

这一方面官方是什么建议呢？

**Comment by realJackSun** [comment]
建议生产、测试用不同命名空间隔离。
如果初次自建Nacos，建议建立两套Nacos，一套用于配置、一套用于发现，便于出现问题时控制变量。

**Comment by kuaile-zc** [comment]
> 建议生产、测试用不同命名空间隔离。 如果初次自建Nacos，建议建立两套Nacos，一套用于配置、一套用于发现，便于出现问题时控制变量。
https://github.com/alibaba/nacos/issues/7774

请问部署两套的时候是建议使用all模式还是分别用 config  naming模式。使用不同的模式好像现在Service端没有很多明显的改变参考我上面提的问题，最近在考虑分开部署。我是想两个都用all模式启动共用一个数据库。
