### ISSUE TITLE
服务下线功能失效

### ISSUE THREAD

**Issue by amazinglogic** [alibaba/nacos#7829]
nacos1.4.2集群
dubbo2.7.8

下线一个provider接口，接口会变得非健康实例然后被清除，下次会重新注册上来是上线状态

**Comment by realJackSun** [comment]
麻烦提供一下客户端的naming.log，看一下日志。

**Comment by ingle-j** [comment]
![1](https://user-images.githubusercontent.com/65645098/155454253-3b6fd474-17cc-449b-9a4c-2ec910aeef31.jpg)
![2](https://user-images.githubusercontent.com/65645098/155454258-a7985797-0c1b-46e0-afc7-0a3befd9ddf0.jpg)

图1是nacos节点1得，图2是nacos节点2得

**Comment by KomachiSion** [comment]
升级到2.0版本吧， 1.x版本的结构注定了无法保持下线状态。

![image](https://user-images.githubusercontent.com/37170243/162658135-198c3308-b378-478f-ac79-3e53320f01e9.png)
