### ISSUE TITLE
NacosException: Client not connected,current status:UNHEALTHY

### ISSUE THREAD

**Issue by jameswuwu** [alibaba/nacos#7840]
## Issue Description
Nacos Version 2.0.1

On my Nacos, I have registered six services, all of which are running normally. 
Today, a service reported an exception, As a result, the interface failed to request successfully.
After the abnormal service was restarted, everything returned to normal

![lALPJxuMPk2mJPfNArXNBC4_1070_693](https://user-images.githubusercontent.com/52489194/155659415-8ec62458-7ab3-4d69-8614-56b3e4717754.png)

### Describe what you expected to happen
Can someone please tell me what causes this and how to solve it?    Thanks

**Comment by realJackSun** [comment]
是不是当时存在网络问题？或者上一次的service下的机器存在安全组、防火墙拦截？导致了ServerCheckRequest没有发送到Nacos Server

**Comment by realJackSun** [comment]
@jameswuwu 排查一下，先确认一下是不是网络原因导致的。

**Comment by fengxuexiaoyao** [comment]
请问这个问题是怎么解决的？

**Comment by fengxuexiaoyao** [comment]
How is this problem solved？
