### ISSUE TITLE
Nacos中的配置管理列表与数据表中的不一致

### ISSUE THREAD

**Issue by developers-youcong** [alibaba/nacos#7841]
**Describe the bug**
Nacos管理界面上的配置信息与数据表(config_info表)不一致

**Expected behavior**
希望Nacos管理界面上的配置列表信息与数据表(config_info表)保持一致

**Acutally behavior**
不一致，例如Nacos中的配置列表增加blog.properties配置文件以及blog-prod.yml文件，实际config_info表并未增加，或者是config_info表存在api.properties文件，但实际并未在Nacos中的配置列表中展现出来。

**How to Reproduce**
1. 通过Nacox新增配置信息
2. 查看数据表无对应的配置信息
3. Nacos的配置列表信息有对应的配置信息
4. Linux或Windows上无明显报错

**Desktop (please complete the following information):**
 - OS: [e.g. Centos7.5 /Window10]
 - Version [Nacos1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, Spring-Cloud-Alibaba-nacos 2.2.1.RELEASE]

**Additional context**
暂无

**Comment by chenhao26-nineteen** [comment]
> 例如Nacos中的配置列表增加blog.properties配置

是不是使用的内嵌数据库？如果是数据书不会落到mysql里面的
