### ISSUE TITLE
Not able to connect to remote server address

### ISSUE THREAD

**Issue by desmondlps** [alibaba/nacos#7843]
Hi Guys,

Im facing an issue trying to connect to Nacos server which is hosted in AWS. When i run the springboot application, it exited immediately with exit code 1 without any errors or exceptions thrown.

Here is my application.properties config
```
nacos.config.server-addr=dev-nacos.abcd.com:80
nacos.config.namespace=23ee24ad-2627-4001-b67d-fe68f574da5a
nacos.config.bootstrap.enable=true
nacos.config.group=DEFAULT_GROUP
nacos.config.type=properties
nacos.config.dataIds=test-service
```

Just to be sure its not due to connectivity or whitelist issue, i have tested it via curl api and i am able to get results successfully 
`https://dev-nacos.abcd.com/nacos/v1/cs/configs?tenant=23ee24ad-2627-4001-b67d-fe68f574da5a&dataId=test-service&group=DEFAULT_GROUP`

Is there something wrong with my config?

**Comment by desmondlps** [comment]
nacos-config-spring-boot-starter: 0.2.4
nacos-spring-boot: 0.2.4
nacos-api: 1.1.3
nacos-client :1.1.3

**Comment by vividfish** [comment]
try server-addr=http://dev-nacos.abcd.com:80 ?
https use port 443 instandof 80, suggest  use `telnet  dev-nacos.abcd.com 80 ` to confirm network

**Comment by desmondlps** [comment]
Thanks manage to get it to connect now using 

server-addr=[https://dev-nacos.abcd.com:443](http://dev-nacos.abcd.com/)
