### ISSUE TITLE
SecurityProxy的accessToken问题

### ISSUE THREAD

**Issue by flmelody** [alibaba/nacos#7844]
这个成员变量是不是应该共享的？
![1645785104(1)](https://user-images.githubusercontent.com/47545727/155700012-20c21816-7f0f-49bc-a94b-617cb4219ed6.png)
ConfigTransportClient和NamingGrpcClientProxy各自实例化了一个SecurityProxy，其中NamingGrpcClientProxy有登录刷新accessToken的机制，ConfigTransportClient是没有的，ClientWorker配置监听会一直返回403，这里accessToken是空的
![1645785080(1)](https://user-images.githubusercontent.com/47545727/155699952-b7faa652-b1b0-46ae-9990-0538d489ee4b.png)

**Comment by flmelody** [comment]
此时运行时无法刷新配置了

**Comment by hujun-w-2** [comment]
检查一下是否是在单核单线程机器运行，如果是，升级nacos-client为最新版

**Comment by KomachiSion** [comment]
不应该共享，因为可能配置中心和注册中心都不是一个nacos实例， 权限可能也不一样，所使用的用户名和密码也不一样
