### ISSUE TITLE
After the raft partition, the term has been increasing, causing the leader to be elected as a leader, but the data is incomplete.

### ISSUE THREAD

**Issue by jacky1193610322** [alibaba/nacos#785]
nacos 0.8 
当前选举，假设一个节点与其他所有节点产生分区，那么他会一直累加term，造成term累加的非常大，假设等一段时间他回归了，那么因为term非常大了，那么会被选举为leader，那么这时候他的数据是不全的，这时候选举他为leader就会有问题

**Comment by nkorange** [comment]
Registering of instance doesn't increase term. Other write operation will fail in network partition, so the global term will not increase in network partition.

**Comment by jacky1193610322** [comment]
我说的节点是nacos-server, A B C三个节点，A当前是leader，b、c是follower，当b与主和c之间网络不通的时候，那么时间超时之后就会发起选主，此时他因为网络不通，选不了主，那么就会一直循环发起选主，一段时间后，term就会累加的比较大了，此时网络通了，那么b还是会发起选主，因为term比较大，所以可以选上，那么就会发送心跳，通知其他节点。

**Comment by nkorange** [comment]
@jacky1193610322 虽然正常写操作会将leader的term加100，但是你描述的问题确实会在很罕见的情况下发生。感谢你的反馈，我们会尽快优化这个问题。当然也欢迎你贡献你的想法！

**Comment by KomachiSion** [comment]
Refer to #3635
