### ISSUE TITLE
docker容器内无法连接nacos容器please check server 172.172.172.100 ,port 9848 is available

### ISSUE THREAD

**Issue by qq670176019** [alibaba/nacos#7854]
1、dockerfile配置如下：
![image](https://user-images.githubusercontent.com/35839281/155870436-bd552974-c278-45b2-84b8-2b4c7db1cce0.png)
2、application.properties配置如下：
![image](https://user-images.githubusercontent.com/35839281/155870479-0713e020-7f31-45cb-8389-687cd2774e59.png)
3、nacos启动日志如下：
![image](https://user-images.githubusercontent.com/35839281/155870498-137bb82e-4efb-44be-badd-ecae77238486.png)
4、nacos容器内netstat如下：
![image](https://user-images.githubusercontent.com/35839281/155870515-e69d5416-0af7-4ce6-a03c-591ebed0566d.png)
5、nacos容器映射端口如下：
![image](https://user-images.githubusercontent.com/35839281/155870533-deeb533a-b296-448a-b068-d390db852364.png)
6、其他容器内需要向nacos注册的服务报错如下：
`Fail to connect server, after trying 76 times, last try server is {serverIp = '172.172.172.100', server main port = 8848}, error = unknown`

请问有没有遇到过类似问题的小伙伴，你们是怎么解决的呢？我尝试过好多次都没效果

**Comment by vividfish** [comment]
看起来像网络问题 验证下端到端的联通性？

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。

**Comment by qq670176019** [comment]
> 

在宿主机外telnet 7748 8848 9848  9849都能通

**Comment by lleiwang** [comment]
你Nacos 什么版本的？前两天遇到过这种情况

当时服务端的版本为 `2.0.0` 客户端版本为 `2.0.0`
后来升级 Nacos 客户端版本至 `2.0.4` 解决了

**Comment by qq670176019** [comment]
> 你Nacos 什么版本的？前两天遇到过这种情况
> 
> 当时服务端的版本为 `2.0.0` 客户端版本为 `2.0.0` 后来升级 Nacos 客户端版本至 `2.0.4` 解决了

我用2.0.4时候有问题，就将到2.0.3了不知道为啥。我是用的ruoyi-cloud，然后自己改了很多东西，后来重新下了一个改了下配置能跑起来了

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。

**Comment by xiawei520** [comment]
解决Nacos 9848 GRPC 端口通信超时问题 Server check fail, please check server 127.0.0.1, port 9848 is available；解决方案：在 /etc/hosts 中添加 本机 ip + hostname，解决java运行慢的问题，nacos注册就正常了。

```clean
hostname

## 返回主机名称
my-linux-04.novalocal

## 然后编辑本机hosts
vi /etc/hosts

## 文件末端添加 本机ip + 刚刚查询到的hostname，比如本机ip是192.168.68.168
192.168.68.168 my-linux-04.novalocal

## 保存编辑并刷新网络
[root@superroot mydock03]# /etc/init.d/network restart
Restarting network (via systemctl):                     
```

**Comment by hailong1398** [comment]
@xiawei520   这个方法解决了，按照提示修改 /etc/hosts解决了。 

问题描述：本地麒麟操作系统，nacos2.1 ,springboot2.3.12, 都在一台服务器上，9848端口能telnet通，但是就是报
Server check fail, please check server 172.29.60.1 ,port 9848 is available , error ={}
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 439041 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@73ad7e90[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4ce14f05, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@71dfcf21, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@b965857}}}}}]]
        at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:192)

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。
