### ISSUE TITLE
docker-compose -f example/cluster-hostname.yaml up 报错希望大佬看一下

### ISSUE THREAD

**Issue by tubushitu** [alibaba/nacos#7856]
ERROR: for nacos1  Cannot start service nacos1: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/nacos_data/init.d/custom.properties" to rootfs at "/home/nacos/init.d/custom.properties" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by myifeng** [comment]
"/home/nacos_data/init.d/custom.properties" is a directory ?

**Comment by tubushitu** [comment]
> 
这个没问题了就是好像是挂载目录的问题，

**Comment by tubushitu** [comment]
[x93 1[root@localhost nacos-docker-1.md](https://github.com/alibaba/nacos/files/8154728/x93.1.root%40localhost.nacos-docker-1.md)
