### ISSUE TITLE
Correct the exception log in ServerHttpAgent

### ISSUE THREAD

**Issue by liqipeng** [alibaba/nacos#7858]
**Describe the bug**
1. If the currentServerAddr changed, the server address output in log will not be same with current request and it is not correctly. 
```
    public HttpRestResult<String> httpGet ......
            ......
            } catch (ConnectException connectException) {
                LOGGER.error("[NACOS ConnectException httpGet] currentServerAddr:{}, err : {}",
                        serverListMgr.getCurrentServerAddr(), connectException.getMessage());
            } catch (SocketTimeoutException socketTimeoutException) {
                LOGGER.error("[NACOS SocketTimeoutException httpGet] currentServerAddr:{}， err : {}",
                        serverListMgr.getCurrentServerAddr(), socketTimeoutException.getMessage());
            } catch (Exception ex) {
                LOGGER.error("[NACOS Exception httpGet] currentServerAddr: " + serverListMgr.getCurrentServerAddr(),
                        ex);
                throw ex;
            }
```
2.  The log or exception thrown in the end of httpGet method output a message not covered all exception conditions. Maybe timeout. 
```
    public HttpRestResult<String> httpGet ......
        ......
        LOGGER.error("no available server");
        throw new ConnectException("no available server");
``` 

**Expected behavior**
Error log can describe a exact information.

**Acutally behavior**
Some log is not exact.

**How to Reproduce**
Start ConfigService with a incorrect address.

**Desktop (please complete the following information):**
 - OS: any
 - Version: nacos-client 1.4.3
 - Module: config
 - SDK: any

**Comment by Mikecarbon** [comment]
Https:\\www.agentexception.com

**Comment by KomachiSion** [comment]
ServerHttpAgent has been no used, only keep it for some special reflection usage for some version, will be removed
