### ISSUE TITLE
nacos config boot 2.1.3 Unable to dynamically refresh

### ISSUE THREAD

**Issue by maojx0630** [alibaba/nacos#786]

**Comment by xuechaos** [comment]
@maojx0630 Is springboot?

**Comment by maojx0630** [comment]
> @maojx0630是springboot吗？

对的 spring boot 2.1.3不能刷新配置 切换为2.0.6 刷新配置正常

**Comment by maojx0630** [comment]
> @maojx0630 Is springboot?

如果使用206不能正常连接mysql数据库 找不到数据库地址  
使用213可以连接数据库 但是就不能刷新配置了

**Comment by zhangmingshuang** [comment]
可以通过自己定义事件处理来进行刷新
```java
@Configuration
public class NacosRefreshEvent {


    @Bean
    public NacosRefreshEventHandler nacosRefreshListener(ContextRefresher refresh) {
        return new NacosRefreshEventHandler(refresh);
    }

    public static class NacosRefreshEventHandler {
        private ContextRefresher refresh;

        public NacosRefreshEventHandler(ContextRefresher refresh) {
            this.refresh = refresh;
        }

        @EventListener
        public void handle(RefreshEvent event) {
            this.refresh.refresh();
        }
    }
}
```

**Comment by Joker1995** [comment]
> ```java
> @Bean
>     public NacosRefreshEventHandler nacosRefreshListener(ContextRefresher refresh) {
>         return new NacosRefreshEventHandler(refresh);
>     }
> 
>     public static class NacosRefreshEventHandler {
>         private ContextRefresher refresh;
> 
>         public NacosRefreshEventHandler(ContextRefresher refresh) {
>             this.refresh = refresh;
>         }
> 
>         @EventListener
>         public void handle(RefreshEvent event) {
>             this.refresh.refresh();
>         }
>     }
> ```

我参考你的试了一下，发现没有效果，boot2.0.5.release,nacos-config-spring-boot-starter是0.2.1，spring-cloud-starter-alibaba-nacos-config是0.2.0.RELEASE
