### ISSUE TITLE
The raft peer is in error: null

### ISSUE THREAD

**Issue by asimplepeople** [alibaba/nacos#7860]
com.alibaba.nacos.api.exception.NacosException: failed to req API:172.26.124.40:31948/nacos/v1/ns/instance/beat. code:503 msg: server is DOWNnow, detailed error message: Optional[The raft peer is in error: null] 这个怎么排查？服务器集群重启后变成这样了

**Comment by realJackSun** [comment]
很有可能是重启时残余数据没有删除干净引起的，删除~/home/nacos/data目录重试一下。

**Comment by asimplepeople** [comment]
好的

**Comment by asimplepeople** [comment]
~/home/nacos/data 可以全部删除的是把

**Comment by asimplepeople** [comment]
确实有效果 谢谢了 @realJackSun   由于我是k8s 集群statefulSet 部署的 ，需要进入三个pvc里面把data都删除，之前只删除了一个重启后发现还是没生效。全部pvc 里面的data数据都删除重启就ok了
