### ISSUE TITLE
两套nacos同步问题请教

### ISSUE THREAD

**Issue by Jv0id** [alibaba/nacos#7861]
我们环境部署了两套nacos系统和两套系统， 但是共用一套MySQL数据库。
A系统更改数据后发给A nacos，请问下A nacos同步内存数据至MySQL是多长时间？还有就是B nacos获取数据时何时会同步MySQL的数据，也就是做到两套nacos数据一致。

1，nacos同步内存数据至MySQL是多久？
2，两套nacos服务使用同一个MySQL数据库能否做到实时同步？

感谢！

**Comment by MajorHe1** [comment]
1、nacos-server分为配置中心模块和注册中心模块，落盘mysql的是配置数据，服务数据都在内存里不会落盘，,所以我暂且认为你是在问配置相关的事情

>  请问下A nacos同步内存数据至MySQL是多长时间？
如上，服务数据不会落盘，配置数据在客户端更新的时候就会先写DB，写DB成功之后再发通知给同集群内的所有的节点从 DB加载该数据

>  还有就是B nacos获取数据时何时会同步MySQL的数据，也就是做到两套nacos数据一致。
我理解既然你说两套，那肯定B跟A不在同一个集群。如果是这样的话，B从数据库加载全量配置数据进行对账的周期我印象中是
6小时。这是个对账动作，最终会以数据库的内容为准。换句话说，依靠DB实现两个不同的nacos集群数据同步是不现实的。

**Comment by MajorHe1** [comment]
There is no response from author after 15 days, so we close this issue.

**Comment by wilsonwu** [comment]
@Jv0id 您好，咨询一下，您那边是在用多套 nacos 共用一个 mysql 数据库吗？
