### ISSUE TITLE
win10 standalone模式，控制台添加用户，用户名总是多了nacos,

### ISSUE THREAD

**Issue by dming** [alibaba/nacos#7869]
如题，win10 standalone模式打开，在控制台上添加用户，u=test,p=test,添加完毕后，显示添加的用户名为nacos,test，这就导致了既不能登录，也不能修改和删除这个账号。版本，最新的1.4.3和2.0.4二进制版本都一样的bug，一切都没改过，登录的账号都是默认的nacos/nacos

<img width="340" alt="1646151778(1)" src="https://user-images.githubusercontent.com/4257725/156207763-b2e21f34-1f14-4c3e-a8f9-bcfc8481934a.png">
<img width="1350" alt="1646151795(1)" src="https://user-images.githubusercontent.com/4257725/156207793-aca32d3a-a244-4751-97a2-3c090f206dac.png">
<img width="279" alt="1646151804(1)" src="https://user-images.githubusercontent.com/4257725/156207806-96858355-1249-41b3-ba6d-d8f6f818d058.png">

**Comment by onewe** [comment]
MacOS 上没有复现

**Comment by KomachiSion** [comment]
新版本没有复现

**Comment by dming** [comment]
好吧，我测试发现用api来操作是可以的，只是在chrome上登录控制台，无论操作什么账号，点了submit之后，错误提示里的user都会额外多加了nacos,这几个字符，即使用edge也一样。

**Comment by GPL1** [comment]
同样问题：
1创建用户自动加上nacos, 比如 用户a ，变成nacos,a
2.绑定角色后列表里不显示，只显示ROLE_ADMIN和nacos用户
3.删除用户提示cannot delete admin：nacos；但是我删除的并不是nacos用户，用浏览器查看请求，无论删除哪个用户参数都传nacos

**Comment by GPL1** [comment]
换个浏览器，比如火狐，问题没有了，可以试一下，我用谷歌比较新的浏览器有问题
谷歌浏览器
版本 98.0.4758.102（正式版本） （64 位）

**Comment by li-xiao-shuang** [comment]
> 

什么版本？

**Comment by li-xiao-shuang** [comment]
> 同样问题： 1创建用户自动加上nacos, 比如 用户a ，变成nacos,a 2.绑定角色后列表里不显示，只显示ROLE_ADMIN和nacos用户 3.删除用户提示cannot delete admin：nacos；但是我删除的并不是nacos用户，用浏览器查看请求，无论删除哪个用户参数都传nacos

什么版本？

**Comment by GPL1** [comment]
找到问题了，浏览器缓存。之前是用1.4的nacos，页面缓存了数据，升级2.0.4之后可能前端js有缓存吧，把缓存清理的好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 上午10:51
***@***.***&gt;;
抄送:&nbsp;"2 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] win10 standalone模式，控制台添加用户，用户名总是多了nacos, (Issue #7869)





  
同样问题： 1创建用户自动加上nacos, 比如 用户a ，变成nacos,a 2.绑定角色后列表里不显示，只显示ROLE_ADMIN和nacos用户 3.删除用户提示cannot delete admin：nacos；但是我删除的并不是nacos用户，用浏览器查看请求，无论删除哪个用户参数都传nacos
  
什么版本？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jefferson-chern** [comment]
1.4.3的nacos还是有这个问题，我清理了缓存也不行，还是多nacos,

**Comment by aninZz** [comment]
macos 1.4.3二进制版本存在同样的问题，chrome和safari同样存在

**Comment by Forwardxiang** [comment]
我也有同样的问题，试了很多版本都一样，例如v1.4.3
