### ISSUE TITLE
nacos ip泄露 /nacos/v1/core/cluster/nodes

### ISSUE THREAD

**Issue by kaomianjin** [alibaba/nacos#7872]
Access /nacos/v1/core/cluster/nodes will return to get registered network information
访问 /nacos/v1/core/cluster/nodes,会将内网ip返回出去

curl --location --request GET 'http://localhost:8819/nacos/v1/core/cluster/nodes'

{"code":200,"message":null,"data":[{"ip":"172.17.0.3","port":8848,"state":"UP","extendInfo":{"lastRefreshTime":1645670154582,"raftMetaData":{"metaDataMap":{"naming_instance_metadata":{"raftGroupMember":["172.17.0.2:7848"]},"naming_persistent_service_v2":{"raftGroupMember":["172.17.0.2:7848"]},"naming_service_metadata":{"raftGroupMember":["172.17.0.2:7848"]}}},"raftPort":"7848","version":"2.0.3"},"address":"172.17.0.3:8848","failAccessCnt":0,"abilities":{"remoteAbility":{"supportRemoteConnection":true},"configAbility":{"supportRemoteMetrics":false},"namingAbility":{"supportJraft":true}}}]}

Excuse me, how should this be handled

**Comment by vividfish** [comment]
没看到你哪个服务ip返回了

**Comment by kaomianjin** [comment]
是集群成员的ip返回了

**Comment by kaomianjin** [comment]
你没get到点,生产把内部的其他机器的ip不经限制返回出去,是不是安全漏洞

**Comment by tokyohost** [comment]
emmm, 打开鉴权呗

**Comment by vividfish** [comment]
这个接口没有鉴权

**Comment by kaomianjin** [comment]
鉴权已经打开了
nacos.core.auth.enabled=true

**Comment by vividfish** [comment]
我是说这个接口不在nacos默认的鉴权列表里，所以这个方面的安全考虑要用户自己评估。 
从另一种角度思考，nacos本来就是应用在内部网络里的，当你内部的网络都不安全了，其他也没啥可谈的了

**Comment by iQuanhe** [comment]
想要绝对安全，二开

**Comment by kaomianjin** [comment]
是这样的，我们还是决定通过iptables拦截掉，然后在服务器上用api访问




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos ip泄露 /nacos/v1/core/cluster/nodes (Issue #7872)





 
我是说这个接口不在nacos默认的鉴权列表里，所以这个方面的安全考虑要用户自己评估。
 从另一种角度思考，nacos本来就是应用在内部网络里的，当你内部的网络都不安全了，其他也没啥可谈的了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
