### ISSUE TITLE
application.properties not work

### ISSUE THREAD

**Issue by JemyXiao** [alibaba/nacos#7873]
springboot project, when i use bootstrap.properties integrated nacos, is ok!
but when i delete bootstrap.properties,add application.properties integrated nacos is not work.

        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
           <version>0.2.8</version>
        </dependency>

**Comment by vividfish** [comment]
本身就是这样设计的 当你使用nacos配置服务的时候你就明白了

**Comment by JemyXiao** [comment]
it is ok, i have change springboot version & springCloud version
