### ISSUE TITLE
nacos2.0.3 服务端内存泄漏

### ISSUE THREAD

**Issue by banjinbaijiu** [alibaba/nacos#7874]
服务端版本2.0.3，使用过程中内存一直增加。
![image](https://user-images.githubusercontent.com/38620236/156332182-9c1e0291-a653-43ac-92d8-edfd384fe549.png)
dump日志对比结果：
![Uploading image.png…]()
客户端用的版本1.4.3.

**Comment by KomachiSion** [comment]
内存增加不等于内存泄漏吧， 有出现OOM和不停的FullGC吗？

**Comment by banjinbaijiu** [comment]
> 内存增加不等于内存泄漏吧， 有出现OOM和不停的FullGC吗？

未出现OOM，有出现过FULLGC，FULLGC后内存上升。
![image](https://user-images.githubusercontent.com/38620236/157381799-29d657ac-ba82-4ca0-98fb-a451efe60090.png)

**Comment by KomachiSion** [comment]
有FullGC是正常的，重点是频率和GC时间

**Comment by banjinbaijiu** [comment]
> 有FullGC是正常的，重点是频率和GC时间

FULL GC大约一个月一次，yonggc 10分钟每次。
GC参数：-server -Xms2g -Xmx2g -XX:+UseG1GC -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=320m

怎么调整好呢，我们这边用的是2.0.3-SNAPSHOT

**Comment by banjinbaijiu** [comment]
> 有FullGC是正常的，重点是频率和GC时间

FULL GC大约一个月一次，yonggc 10分钟每次。
GC参数：-server -Xms2g -Xmx2g -XX:+UseG1GC -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=320m

怎么调整好呢，我们这边用的是2.0.3-SNAPSHOT

**Comment by KomachiSion** [comment]
这有啥调整的啊 不是正常的吗。。 感觉你可能要学习一下java的GC机制了。ISSUE先关闭了

**Comment by KeithTt** [comment]
@KomachiSion  是正常的吗？原本 2G 不停告警，改成了 4G，过了 2 天又告警了。

![image](https://user-images.githubusercontent.com/15189954/161364375-db698bad-0487-48cb-83bb-5b7181eb35a3.png)
