### ISSUE TITLE
Recruiting Nacos C++ client core leader

### ISSUE THREAD

**Issue by xuechaos** [alibaba/nacos#788]
## Recruiting Nacos C++ client core leader
The Nacos community is now recruiting C++ client core contributors to lead the design and implementation of the Nacos C++ client, expecting you to:
1. Rich C++ experience
2. Can lead the implementation of the C++ version of the Nacos client
3. Can lead the evolution of the Nacos community in the direction of C++ language
After registration, the Nacos core development team will be immediately inserted to participate in the discussion of Nacos core issues.
And the community will work together to build the C++ system, you will be responsible for the entire architecture, and after releasing the implementation version, will become a member of the github Nacos-Group group, recommended to become a community Committer, thank you for reading, welcome you to build .
## Nacos社区现在招募C++客户端核心贡献者
你将负责主导Nacos C++客户端的设计与实现，期望你能：
1. 有丰富的C++经验
2. 能主导实现Nacos客户端的C++版本
3. 能领导Nacos社区在C++语言方向的演进

报名后，将会立即拉入Nacos核心开发群，参与Nacos核心问题的讨论。
并且社区将一起来共建C++体系，你将负责整个体系架构，并且发布实现版本后，将成为github Nacos-Group分组下的一员，推荐成为社区Committer，感谢你的阅读，欢迎你来共建。

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Please kindly advise how to participate?
Actually, I used to be a C++ developer, and now migrated to Java.
But I'm interested in contributing C++ code

**Comment by nkorange** [comment]
@TTTTTAAAAAKKKKEEEENNNN Thank you for having interest. There are generally four steps to contribute a new client:
1. Use the [open-api](https://nacos.io/zh-cn/docs/open-API.html)  to implement the essential functions of a client. The basic functions that should be achieved are:
    * publish config
    * get config
    * listen config
    * remove config
    * register instance
    * deregister instance
    * query instance list for a service
    * subscribe a service for instance list change
    * send instance heartbeat to server to keep alive 

    As you have Java experience, you can refer to Nacos Java client for your client implementation.

2. Write essential test cases for your client and make sure the client works normally with the latest version Nacos server.

3. Request a review from a Nacos committer to check the code again. If the review is passed then this client will be popularized to the community.

4. Last but not least, continuously contributing for it by bugfix  and new feature requirements.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
@nkorange 
One more thing to ask:
Shall we start with a C client first, and then encapsulate it with a C++ facade ?
I think this will widen the field of application for our client.
For these C++ projects, they can use the C++ (facade) library.
For these C projects, they can also use the client.

**Comment by zxywd** [comment]
Have 5 years of experience in C++. 1 year and a half in PHP. Currently a Java developer for 2 years.
Good at C++ socket programming, game development, MFC, Qt.
Familiar with boost asio.
May not be able to be a core leader but can help.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Still working on the C++ version of Nacos client:
https://github.com/TTTTTAAAAAKKKKEEEENNNN/nacos-cpp-cli

Need your advice/comment/help

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Deregister instance function is now available.

**Comment by TTTTTAAAAAKKKKEEEENNNN** [comment]
Now the whole project is migrated to https://github.com/nacos-group/nacos-sdk-cpp
