### ISSUE TITLE
nacos服务端1.4.2版本，SpringCloud nacos 2.2.6.RELEASE 无法动态刷新配置

### ISSUE THREAD

**Issue by Harolder** [alibaba/nacos#7883]
无法动态刷新配置，有时候过了三天才可以收到配置更新，在 idea 上测试没有问题，但是在 dev 和 stg 环境不生效；

查了下服务端的 config-client-request.log  和 config-pull-check.log 都显示客户端向服务端发起了查询请求，但是始终无法拿到最新的配置

**Comment by Harolder** [comment]
nacos 重启后问题解决了

**Comment by VINO42** [comment]
碰到了同样的问题 
nacos-server 1.4.2
springboot 2.3.2 
springCloud Hoxton.SR9
alibaba 2.2.6

**Comment by VINO42** [comment]
重启nacos后可以正常接到刷新的事件

**Comment by VINO42** [comment]
看了下确实 但是这个属性看起来像是超时时间设置 不知为何会变为刷新间隔
