### ISSUE TITLE
这么严峻的国际形势是否考虑托管在国内？

### ISSUE THREAD

**Issue by huie2018** [alibaba/nacos#7891]
这么严峻的国际形势是否考虑托管在国内

**Comment by li-xiao-shuang** [comment]
gitee 有代码同步  https://gitee.com/mirrors/Nacos?_from=gitee_search

**Comment by li-xiao-shuang** [comment]
> 这么严峻的国际形势是否考虑托管在国内

gitee 有代码同步 https://gitee.com/mirrors/Nacos?_from=gitee_search
