### ISSUE TITLE
服务器已经开放8848、9848、9849端口，依然出现:Server check fail, please check server localhost ,port 9848 is available , error ={}

### ISSUE THREAD

**Issue by lxlhz** [alibaba/nacos#7893]
在服务器已经开放8848、9848、9849端口，并且服务也能成功注册到Nacos中，使用feign或者是gateway也能成功请求到服务接口，但是依然报错(After the server has opened ports 8848, 9848, and 9849, and the service can be successfully registered in Nacos, the service interface can also be successfully requested by using feign or gateway, but the error is still reported:)： 

第一个：
Server check fail, please check server localhost ,port 9848 is available , error ={}

java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 13 milliseconds, 450300 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@4948a2e3[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1d6751e3, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@2d258eff, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@64502326}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:146) [nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:268) [nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:528) [nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient$3.run(RpcClient.java:373) [nacos-client-2.0.3.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
第二个：
com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1067) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1042) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:831) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$4.run(ClientWorker.java:748) [nacos-client-2.0.3.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

**Comment by lxlhz** [comment]
telnet 9848端口出现，以下问题：
![image](https://user-images.githubusercontent.com/25732544/156868561-443c9b35-31fe-4b48-9d79-4bc4ff03aa4e.png)

**Comment by vividfish** [comment]
版本呢？

**Comment by lxlhz** [comment]
> 版本呢？

2.0.3

**Comment by lxlhz** [comment]
@vividfish 2.0.3

**Comment by vividfish** [comment]
如果你的服务端版本也是2.0.3 telnet不通，大概率是网络配置有问题

**Comment by lxlhz** [comment]
@vividfish 这个需要怎么解决呢？我是才搭建好nacos时，可以使用，然后过来一会就出现了报错

**Comment by vividfish** [comment]
不清楚你的环境

**Comment by lxlhz** [comment]
@vividfish 使用的是docker搭建，切换nacos版本还会有这个问题？

**Comment by vividfish** [comment]
客户端配端口8848试试

**Comment by jiangjialiang918** [comment]
我也发现这个问题,服务注册上去没有问题,但是多加了一个配置logging.file.path ,这个按理来说和nacos没有任何关系的,就出现启动一直报错且提示( Server check fail, please check server localhost ,port 9848 is available , error ={} ),本地是可以用Telnet访问到nacos 9848的

**Comment by youjunyi** [comment]
> 我也发现这个问题,服务注册上去没有问题,但是多加了一个配置logging.file.path ,这个按理来说和nacos没有任何关系的,就出现启动一直报错且提示( Server check fail, please check server localhost ,port 9848 is available , error ={} ),本地是可以用Telnet访问到nacos 9848的

我也有同样的问题 请问解决了吗

**Comment by lxlhz** [comment]
> > 我也发现这个问题,服务注册上去没有问题,但是多加了一个配置logging.file.path ,这个按理来说和nacos没有任何关系的,就出现启动一直报错且提示( Server check fail, please check server localhost ,port 9848 is available , error ={} ),本地是可以用Telnet访问到nacos 9848的
> 
> 我也有同样的问题 请问解决了吗

其实是操作的问题，我引入了nacos-config的maven包，但是没有配置bootstart.yaml文件导致的，把 nacos-config的maven去掉就可以了

**Comment by jiangjialiang918** [comment]
> > > 我也发现这个问题,服务注册上去没有问题,但是多加了一个配置logging.file.path ,这个按理来说和nacos没有任何关系的,就出现启动一直报错且提示( Server check fail, please check server localhost ,port 9848 is available , error ={} ),本地是可以用Telnet访问到nacos 9848的
> > 
> > 
> > 我也有同样的问题 请问解决了吗
> 
> 其实是操作的问题，我引入了nacos-config的maven包，但是没有配置bootstart.yaml文件导致的，把 nacos-config的maven去掉就可以了

官网有文档介绍么,不然还是有点奇怪为什么会要这个操作

**Comment by jiangjialiang918** [comment]
> [<img alt="@jiangjialiang918" width="20" height="20" src="https://avatars.githubusercontent.com/u/22257945?s=60&amp;u=94260a428584cdd6adbe1fe45fc9d12e5ea22709&amp;v=4">](/jiangjialiang918) [jiangjialiang918](/jiangjialiang918) mentioned this issue [ 3分钟前 ](#ref-issue-1187909984)
> [ 解决不了, 我感觉是bug,目前只能先注释掉logging相关配置 #8054](/alibaba/nacos/issues/8054)


> > > 我也发现这个问题,服务注册上去没有问题,但是多加了一个配置logging.file.path ,这个按理来说和nacos没有任何关系的,就出现启动一直报错且提示( Server check fail, please check server localhost ,port 9848 is available , error ={} ),本地是可以用Telnet访问到nacos 9848的
> > 
> > 
> > 我也有同样的问题 请问解决了吗
> 
> 其实是操作的问题，我引入了nacos-config的maven包，但是没有配置bootstart.yaml文件导致的，把 nacos-config的maven去掉就可以了

其实我注释掉logging相关配置也是可以的....

**Comment by onewe** [comment]
@jiangjialiang918 logging.file.path 这个是加在服务端 还是 server端端？

**Comment by jiangjialiang918** [comment]
> @jiangjialiang918 logging.file.path 这个是加在服务端 还是 server端端？

客户端

**Comment by youjunyi** [comment]
现在的解决办法就是把nacos的配置添加到bootstart.yaml里就可以了 不清楚为什么，官方文档并没有提到过个这个问题

**Comment by jiangjialiang918** [comment]
> 现在的解决办法就是把nacos的配置添加到bootstart.yaml里就可以了 不清楚为什么，官方文档并没有提到过个这个问题
我的情况是只要注释掉logging相关配置就没事,一旦放开,logging和nacos配置哪个放bootstrap先加载都不行

**Comment by jsonpang** [comment]
我也有类似的问题，但是为啥换一台服务器部署客户端就可以 原来的那台网络也是通的

**Comment by potterjoy** [comment]
我也遇到了，微服务中有几个应用报 Server check fail, please check server localhost ,port 9848 is available , error ={}  其他服务是好的，想请教一下你们都解决了么？怎么解决这个问题的

**Comment by yijianguanzhu** [comment]
Server check fail, please check server localhost ,port 9848 is available , error ={} 这个问题是nacos-config依赖引入了，但是没配置导致的，有的机器不配置不会报错，代码两次就取到discovery的值了，后续会生成默认值执行，然后停掉之前的定时任务，有的机器遍历几遍才会取到discovery的值，这里反而不会停止之前的定时任务，虽然报错，但是仔细看控制台，是会输出Grpc connection connect的信息，这里说明config有一个任务已经拿到discovery的配置值并生成默认值了。config的自动装配先执行，discovery的自动装配后执行，报错机制就是config的任务太多，一直在定时重连，我也没仔细DEBUG查看为什么有的机器报错有的没有，有兴趣的可以自己debug深究一下，不过这个问题主要还是nacos config依赖引入的问题，可以在配置里关掉nacos config的自动装配或移除依赖即可，没必要纠结这个啦。

**Comment by HypHao** [comment]
2.0.0也是这样。。。

**Comment by Smallballoons01** [comment]
你们的nacos是不是根本没有起来，你们使用startup.cmd -m standalone  启动

**Comment by zhaoydo** [comment]
遇到相同问题，解决了
### 现象
nacos client 1.4.2 > 2.0.3 （cloud alibaba2.2.6 Release -> 2.2.7 Release ）后，部分机器上服务启动会提示localhost 9848相关报错
### 原因
nacos client 2.x版本不识别配置在application.properties(yml)中的nacos config相关配置，会以默认参数启动nacos config.  
默认参数为：spring.cloud.nacos.config.enabled=true; spring.cloud.nacos.config.server-addr=localhost:8848
读取的是localhost的8848 9848 9849， 导致报错
### 解决
nacos config相关配置到bootstrap.properties(yml) 或者启动参数中

**Comment by Roroldo** [comment]
我也遇到了这个问题，最后是通过降低 nacos-client 客户端版本解决的
```
<!-- nacos配置中心-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <!--自带的 nacos 版本是 2.0 以上的 大坑-->
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.1.4</version>
        </dependency>
```

**Comment by dym1005** [comment]
我在本地再起个单机nacos就不报错了，不知道为什么

**Comment by zhaoydo** [comment]
> 我在本地再起个单机nacos就不报错了，不知道为什么

因为默认连接的了本地的nacos config,也就是localhost:8848 9848 9849

**Comment by parkerisme** [comment]
> 我也遇到了，微服务中有几个应用报 Server check fail, please check server localhost ,port 9848 is available , error ={} 其他服务是好的，想请教一下你们都解决了么？怎么解决这个问题的

me too

**Comment by guiji72** [comment]
有人解决过这个报错嘛，启动没错，运行一段时间后部分服务报错

**Comment by chenmonster** [comment]
> bootstrap.properti

把 conf 目录下 application.properties 文件的名称改成 bootstrap.properties ?

**Comment by dzh6699** [comment]
nacos版本2.1.2 ，也遇到这个问题，个别服务使用一段时候就报这个错，一般是半小时后。而且只有个别服务会这样，其他服务全部正常。找不到原因在哪。

**Comment by s61595579** [comment]
请问这个问题有人解决了嘛，我也碰上了，但是我的第二个异常提示的状态不太一样，我提示的是current status:UNHEALTHY

**Comment by eysam** [comment]
**环境：**
springcloud-alibaba2.2.9.RELEASE 
nacos-client 2.1.0 
spring-cloud-starter-alibaba-nacos-config 
处于192.168.1.120的nacos-server2.1.0
**问题：**
本人设置了spring.cloud.nacos.discovery.server-addr = 192.168.1.120，诡异的事情是服务成功注册进了nacos-server,在nacos-server管理界面也能看到，但gRPC疯狂刷错误，显示其正在连接localhost:9848....
**解决方式**
删除spring-cloud-starter-alibaba-nacos-config的maven依赖，重新reload一下依赖，重启就行了

**Comment by CRISPpp** [comment]
docker用户注意一下docker有没有开另外两个grpc端口的映射

**Comment by fruitfish** [comment]
![image](https://github.com/alibaba/nacos/assets/19407667/46f44420-9a0c-44f8-a2f7-8b2a6077af40)
我也遇到这个问题了，好像是集群节点间9849不通了，但我去服务器上telnet是可以连通的。nacos版本是2.0.3。已经运行了挺长一段时间了，今天出现这个问题。微服务和nacos的通信都出现了问题。最后重启了nacos集群。

**Comment by uyoaix** [comment]
我也遇到这个问题了：[Server check fail, please check server localhost ,port 9848 is available , error ={}]
腾讯云服务器，docker单节点部署的nacos：nacos/nacos-server:v2.2.0 , docker已开启8848，9848，9849端口
防火墙已放开上述3个端口

nacos镜像：`nacos/nacos-server:v2.2.0`
客户端jar版本：
```shell
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.8.RELEASE</version>
        </dependency>
```

问题：

> 只使用配置中心，不使用注册中心

1. nacos正常运行，一个application.name=A的服务使用namespace=[prod环境的id] 的命名空间连接nacos配置中心，启动成功
2. 在该服务器上准备启动第二个应用，application.name=A , namesapce=[test环境的id]，启动后，docker部署的nacos被杀死😮😮，自动重启，在启动中的这个应用报错：Server check fail, please check server localhost ,port 9848 is available，因为nacos被搞死了😮😮，然后疯狂去重试连接，CPU一下子飙到300多，服务器都快被搞死了
3. 但是在本地启动第二个应用就没有问题

**Comment by ycrxun** [comment]
同样的问题,服务端2.1.2,客户端2.0.4, telnet 可以通 
Error日志: Server check fail, please check server 172.16.6.3 ,port 9848 is available
2.x同一个包 放到另外一台服务器有又可以.
客户端回退到1.x又可以

**Comment by Zark1999** [comment]
> nacos版本2.1.2 ，也遇到这个问题，个别服务使用一段时候就报这个错，一般是半小时后。而且只有个别服务会这样，其他服务全部正常。找不到原因在哪。

同样的问题，一段时间后出现的报错，而且ip和端口显示的都没问题

**Comment by sntaoo** [comment]
同样的问题，添加了bootstrap.yml配置也没有解决

**Comment by MokongZ** [comment]
同样的问题，一段时间后出现的报错，而且ip和端口显示的都没问题

**Comment by zivfuture** [comment]
同样的问题，  初次注册没问题，9848也ok，  下线重启后同样的错,

**Comment by zhangbujin** [comment]
v2.2.3 运行一段时间，也同样出现此问题。是容器缓存还是啥原因呢?服务好像没受影响，但是经常被监控到服务异常。该如何处理？

**Comment by zhangbujin** [comment]
2023-10-16 09:56:06.737 ERROR 7 [-] [com.alibaba.nacos.client.naming.updater.1] com.alibaba.nacos.common.remote.client   Send request fail, request = ServiceQueryRequest{headers={accessToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY5NzQyNTg1MH0.C3sVDSu7joRA0WqSS9gYB2A47WxVc14DIJYgeGTS7qehF4XnDwCZy1oStG4ugsMJbiyr-Vaiu3OtU_Z-BkFhqA, app=unknown}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:UNHEALTHY
2023-10-16 09:56:06.810 ERROR 7 [-] [com.alibaba.nacos.client.remote.worker] c.a.n.c.remote.client.grpc.GrpcClient    Server check fail, please check server 192.168.10.116 ,port 9848 is available , error ={}
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 90237 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@1e22f4f3[status=PENDING, info=[GrpcFuture{clientCall=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@52ee8ee5, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@23afcb0a, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@53abe933}}}]]

**Comment by FakeTrader** [comment]
方案一：
将 spring-cloud-alibaba 升级到 2021.0.5.0 及以上
方案二：
将 nacos 配置移动到 bootstrap

**Comment by slliver** [comment]
单机的时候没有这个问题，集群模式 nacos-server 2.0.4 也发现了这个问题，我的解决办法是 客户端依赖的时候降低一个版本

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.4.2</version>
        </dependency>
启动就没问题了服务也可以注册上

**Comment by qingsanxing** [comment]
nacos导入了动态配置的包之后，一定要bootstrap.yaml(properties)文件设置动态文件获取地址，不然默认访问localhost

**Comment by Sun-Xingbin** [comment]
真是离谱的问题，找遍了全网，最后通过回退版本来解决

**Comment by guochunxing** [comment]
网络代理也会引起这个问题，感觉是端口冲突了。关掉 clash 就好了。

**Comment by uangshiyon** [comment]
我们服务器也出现过这种问题，经过分析是InetAddress.getLocalHost导致的问题，可以通过在/etc/hosts中配置解决
127.0.0.1   xxxx
::1             xxxx

xxxx自己替换成你的主机名（hostname）

**Comment by WooWhoThere** [comment]
应该是依赖了nacos-config，但是没有配置nacos-config导致的，加上
```      
spring:
  cloud:
    # nacos配置
    nacos:
      config:
        server-addr: ip:8848
        file-extension: yaml
```
可以解决这个问题 😄

**Comment by 1430148787** [comment]
离谱啊, 有没有解决办法? 已开3个端口, 依然解决不了, windows nacos就没问题

**Comment by zhaoydo** [comment]
> 离谱啊, 有没有解决办法? 已开3个端口, 依然解决不了, windows nacos就没问题

你试试在bootstrap中指定nacos config的地址。nacos config不读取application的配置，默认就是localhost

**Comment by Hasasiki** [comment]
> 网络代理也会引起这个问题，感觉是端口冲突了。关掉 clash 就好了。

我是这个问题,关了立马好了,离谱

**Comment by Fuxingwang-96** [comment]
同Nacos2.0.3  可以检查一下你的Maven打包配置  看下你打的包有没有缺失bootstrap.yml  我的是打包配置的问题

**Comment by hpkun** [comment]
> 网络代理也会引起这个问题，感觉是端口冲突了。关掉 clash 就好了。

感谢大佬，我把梯子关了真的就解决了

**Comment by chenxing0206** [comment]
搞到最后发现真的是梯子的问题，有遇到的同学可以检查一下是否有开vpn
