### ISSUE TITLE
配置中心自动更新某个配置

### ISSUE THREAD

**Issue by qhyjoe** [alibaba/nacos#7894]
我们在使用nacos的时候，配置中心莫名其妙多了一条配置，配置不定时更新，更新时间有变化，内容无变化，配置id=nacos.cfg.dataIdfoo，内容是helloWorld，有三个nacos环境出现了这种情况，请问遇到过这个种情况吗。k8s部署的nacos，版本为2.0.1。

**Comment by BerlinA4real** [comment]
你好，请问这个问题你们解决了吗？我们在这个月出现了同样的问题，尚未找到问题所在。若你们有解决的方案还劳烦告知我，谢谢。

**Comment by qhyjoe** [comment]
> 你好，请问这个问题你们解决了吗？我们在这个月出现了同样的问题，尚未找到问题所在。若你们有解决的方案还劳烦告知我，谢谢。

我们是集团内部有人在做安全测试引起的，开启认证就好了

**Comment by BerlinA4real** [comment]
> > 你好，请问这个问题你们解决了吗？我们在这个月出现了同样的问题，尚未找到问题所在。若你们有解决的方案还劳烦告知我，谢谢。
> 
> 我们是集团内部有人在做安全测试引起的，开启认证就好了

好的，谢谢您的解答
