### ISSUE TITLE
【特别关注】多租户隔离的问题哪个版本上，特别是控制台上，建议将命名空间做为租户

### ISSUE THREAD

**Issue by 18980808191** [alibaba/nacos#790]
多租户隔离的问题哪个版本上，特别是控制台上，建议将命名空间做为租户。
公司有很多个系统，每个系统都是微服务框架，想共用一个注册中心集群，必须要租户隔离开。求管理员重视下。一直想用nacos，但是不支持多租户隔离，痛苦。只能持续关注，希望管理员给个时间。

**Comment by 2417796669** [comment]
多租户隔离之后，租户之间的服务怎么调用？nacos不同命名空间下的服务不可以相互调用吧？

**Comment by 13462249457** [comment]
你这个问题目前是怎么解决的呢？多租户又想用同一个注册中心？
