### ISSUE TITLE
nacos与eureka的对比

### ISSUE THREAD

**Issue by AaronCarrier** [alibaba/nacos#7901]
eureka2.x闭源，很多使用者都会用nacos来替换老系统使用的eureka，nacos官方文档也聊到了开源之前需要适配其他系统的eureka。
能否提供详细对比来说服使用者用nacos替换eureka，或者说nacos在某些方面的能力比eureka强大，能否有实际测试的数据。nacos官方的测试单独基于nacos，没有同情况下eureka的表现。

**Comment by KomachiSion** [comment]
官方文档不会提及其他产品，只会吐露nacos自身的内容和信息，如果有这方面的对比需求，可以搜索一些文章，或者自行搭建环境进行对比。
