### ISSUE TITLE
spring boot 中使用nacos client 订阅时，导致应用名称 unknown

### ISSUE THREAD

**Issue by hadoop835** [alibaba/nacos#7907]
<img width="797" alt="1646721213617_1DA5E72A-349A-45d3-8025-434339207EC0" src="https://user-images.githubusercontent.com/8055054/157195659-3182a902-48cc-40e8-831b-cd1b096b34fe.png">

<img width="640" alt="1646721282692_505658B2-9514-4656-9982-0D76D702C683" src="https://user-images.githubusercontent.com/8055054/157195731-706c339a-c544-48e2-9cf3-4e9b017c0261.png">

**Comment by KomachiSion** [comment]
Can you submit issue and PR to spring cloud alibaba or nacos spring boot repo?
