### ISSUE TITLE
来自开源社区goodrain的合作请求

### ISSUE THREAD

**Issue by dazuimao1990** [alibaba/nacos#7908]
各位好，我来自开源社区 [goodrain](https://github.com/goodrain) ，主要运营开源产品 [Rainbond](https://www.rainbond.com/?channel=nacos)。
Rainbond 有很多用户的业务已经微服务化，所以这些用户也是 Nacos 的用户或者潜在用户。Rainbond 通过自身的应用市场机制为这些用户提供了一种选择，一键部署生产可用的 Nacos 集群，这种部署方式很受社区用户的欢迎。所以特此提出一种合作的可能，我们愿意提交一份一键部署 Nacos 的文档到 Nacos 官方的安装文档序列中去，帮助更多同时需要云原生应用管理平台和 Nacos 的用户了解到这种可能性以及其带来的便利性。

> 预计文档内容包括：
> - 图形化部署3节点 Nacos 集群 + Mysql 数据库的操作过程
> - 以环境变量的方式配置 Nacos 集群的方式方法

非常期待 Nacos 社区运营者的回复 😄

--- 

Hello, everyone, I come from the open source community [goodrain](https://github.com/goodrain), the main operation of the open source products [Rainbond](https://www.rainbond.com/?channel=nacos).
Rainbond has many users whose applications have been microservified, so these users are also Nacos users or potential users. Rainbond provides these users with the option of one-click deployment of production-usable clusters of Nacos through its own application market mechanism, which is popular with community users. Therefore, we hereby propose a request for cooperation. We would like to submit a one-click deployment document of Nacos to the installation document sequence of Nacos to help more users who need both the cloud native application management platform and Nacos to understand this possibility and the convenience it brings.

> The expected document contents include:
> - Graphical deployment of a 3-node Nacos cluster with Mysql database
> - How to configure the Nacos cluster as an environment variable

We look forward to hearing from the Nacos community operators.

**Comment by KomachiSion** [comment]
Great information!~. We are looking forward to working with various communities.

If you has finished the document, you can submit an PR to https://github.com/nacos-group/nacos-group.github.io

We will review PR and merge it if no problem.

**Comment by dazuimao1990** [comment]
This is really exciting information. I will complete the document and submit PR as soon as possible

**Comment by KomachiSion** [comment]
Merge and will be published after few days.
