### ISSUE TITLE
展示服务下所有的接口

### ISSUE THREAD

**Issue by littlefisher666** [alibaba/nacos#791]
是否可以开发一个页面，在服务详情页面展示当前服务都提供了哪些接口的

**Comment by xuechaos** [comment]
@litttlefisher 其实一般情况下 dubbo情况 服务就等同于接口，我猜你说的是接口中的方法？

**Comment by litttlefisher** [comment]
@xuechaos 是的，接口中的方法

**Comment by maobuji** [comment]
集成Swagger2就好了吧。我倒是觉得应该给个链接跳到actuator去

**Comment by litttlefisher** [comment]
@maobuji 集成Swagger可能会有些问题的
1. 假设a模块部署了3个服务，用哪一服务的Swagger页面来进行展示呢？
2. 还是假设a模块部署了3个服务，但是对应的接口稍有不同，a1新增了一个新接口，那要如何判断展示呢？
3. Swagger是以web为单位进行展示的，维护这个ip地址其实也是一个比较费力的工作，如果nacos能集成Swagger，也是不错的
