### ISSUE TITLE
nacos-clinet print the password in log

### ISSUE THREAD

**Issue by qngl** [alibaba/nacos#7912]
**Describe the bug**
nacos-clinet print the password in log

**Expected behavior**
Do not print password in log

**Acutally behavior**
com.alibaba.nacos.common.http.client.NacosRestTemplate
HTTP method: POST, url: http://xxxxx:8848/nacos/v1/auth/users/login?username=prod, body: {password=@bcD2021}

**How to Reproduce**
1. Set the log level to debug
2. Startup the application which connect to nacos
3. Look up the com.alibaba.nacos.client.naming log
4. See the password in log

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Version nacos-server 2.0.4, nacos-client 2.0.3
 - Module [e.g. naming/config]
 - SDK 
[INFO] |  |  +- com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:jar:2.2.7.RELEASE:compile
[INFO] |  |  |  +- com.alibaba.spring:spring-context-support:jar:1.0.10:compile
[INFO] |  |  |  +- com.alibaba.nacos:nacos-client:jar:2.0.3:compile

**Additional context**

**Comment by qngl** [comment]
It's critical, password should never be printed in log!

**Comment by onewe** [comment]
It's only in debug level to print, so I don't think there is a risk

**Comment by KomachiSion** [comment]
Close reason in PR https://github.com/alibaba/nacos/pull/7915
