### ISSUE TITLE
nacos-k8s缩容以后，原有nacos节点还在cluster列表中

### ISSUE THREAD

**Issue by chenhao26-nineteen** [alibaba/nacos#7914]
**Describe the bug**
After nacos-k8s deployment and capacity reduction, the original Nacos nodes will still exist in the cluster list! As shown in the figure below, nacos5 this node has been removed, but it will still be displayed in the cluster list
![image](https://user-images.githubusercontent.com/35129699/157361826-3fb15a1c-4ebb-4883-a496-d2371c4fbae5.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Do you change the cluster.conf file?

**Comment by Chaos-coder** [comment]
> Do you change the cluster.conf file?

The peer finder plug-in is used to sense the change of cluster list, and there is no manual operation of cluster.conf.

**Comment by KomachiSion** [comment]
you mean there are a plugin developed by yourself to sense the change of cluster list without cluster.conf?
Maybe you should check your plugin.

Nacos only support cluster.conf and address server for official.

**Comment by Chaos-coder** [comment]
> you mean there are a plugin developed by yourself to sense the change of cluster list without cluster.conf? Maybe you should check your plugin.
> 
> Nacos only support cluster.conf and address server for official.

I use the peer finder provided in the yaml file of the Nacos group / nacos-k8s project to sense cluster changes, which is not self-developed, so it should be the expansion and contraction of Nacos itself?

**Comment by KomachiSion** [comment]
@paderlol Can you help find the problems?
