### ISSUE TITLE
通过curl导入配置

### ISSUE THREAD

**Issue by PhilosophyYuan** [alibaba/nacos#7916]
通过Curl导入配置提示导入数据为空
导入命令为:curl -d '@nacos_config.zip' -X POST 'http://X/nacos/v1/cs/configs?import=true&namespace=test&username=x&password=x'
提示错误:{"code":100005,"message":"导入的文件数据为空","data":{}}
有大佬知道怎么解决吗?

**Comment by PhilosophyYuan** [comment]
curl -d '@nacos_config.zip' -F POST 'http://x/nacos/v1/cs/configs?import=true&namespace=test&username=x&password=x' 已解决

**Comment by boer0924** [comment]
curl -F 'file=@nacos_config_export_20230427103309.zip' -XPOST "http://<nacos-ip>/nacos/v1/cs/configs?import=true&namespace=2b780f25-29c5-46d7-bac8-fb95f02a875d&password=nacos&username=nacos"
