### ISSUE TITLE
nacos手动配置namespace=public无法获取配置

### ISSUE THREAD

**Issue by yumendedao** [alibaba/nacos#7919]
**Describe the bug**
nacos配置namespace=public无法获取配置，改为其他namespace可以获取，或者namespace不配置，获取的就是public下的配置

**Expected behavior**
获取namespace=public下的配置文件
**Acutally behavior**
获取到的结果为null

**How to Reproduce**
Properties properties = new Properties();
properties.put("serverArrd","nacos-hadless:8848");

// properties.put("namespace","test");
properties.put("namespace","public");

ConfigService configService = NacosFactory.createConfigService(properties);
	String content = configService.getConfig("database.properties", "air", 5000);
	System.out.println(content);

**Comment by yumendedao** [comment]
nacos-client 版本 2.0.3
nacos-service 版本 2.0.2

**Comment by li-xiao-shuang** [comment]
默认namespace就是public 是不需要配置的，只有当使用除public以外的命名空间时才需要配置

**Comment by yumendedao** [comment]
不需要配置也不代表配置了就无效啊，虽然是可以用了，但是这的确不应该
public应该和其他namespace一样属于可配置，而不是特殊处理

**Comment by myifeng** [comment]
`namespace`在数据的存在形式是以字段`tenant`存在的。

`public` 命名空间只是一个虚拟的，在数据库是没有存储的，`public`下的配置的`tenant_id`存储的是`NULL`，这也就决定了，你传递`namespace=public`将查不到数据。除非你手动添加一条`public`命名空间，虽然在页面添加不可行，但是手动是可以成功的。

所以，这个我觉得确实应该处理一下，这种形式确实存在问题：

1. 对于`public`而言，重复校验仅存在于前端校验，但是很轻松可以绕过校验
2. 绕开以上的限制，手动添加`public`是可以成功的
![image](https://user-images.githubusercontent.com/26652657/159649961-58dfa18d-4f1b-4619-9817-9dfbec92eee8.png)

所以，我认为`public`命名空间可以作为默认的一个，但是其本质应该与其他的命名空间保持一致，即均存在于数据库，并参与相同的校验或者查询逻辑，而非作为一个特例进行处理。

**Comment by KomachiSion** [comment]
public 是命名空间的名字， 其id是空字符串"" 手动指定应该制定成`namespace=`

**Comment by myifeng** [comment]
我觉得统一化才是合理的设计，而不是为某一个数据做特例。

现有的public命名空间为了保持其特例，在前端和后端都进行了单独的逻辑校验，如果将其与其他的统一起来，将大大降低不必要的校验，提高可用性和拓展性。

@KomachiSion 我想了解一下，团队在设计这方面的考虑是什么样的？

**Comment by KomachiSion** [comment]
最初的设计就是public("") 而Id保持唯一性， 名字不保证唯一性，因此配置时需要配置id来保证能准确制定命名空间。

只是在1.1～1.2版本间，注册中心那边由社区引入了这个bug，输入public等同于输入""，配置中心则没有这个bug。为了兼容部分已经在生产环境中使用的用户，注册中心那边保留了这个兼容，实际上是无奈之举。

如果需要配置中心也保持这个兼容，就需要更多的讨论了，毕竟这就导致public的命名空间变成了一个特殊的存在，创建命名空间时，必须要校验是否输入了public。

**Comment by myifeng** [comment]
1. 保持id的唯一性这一点，我认为设置为`""`是唯一的，设置成字符串`public`也是唯一的，更广泛的来说，设置成为任一值，都是可以保证唯一的，因为现有逻辑和数据库已经校验了id的唯一性。

2. 至于所说的 *`为了兼容部分已经在生产环境中使用的用户`* ，其实在用户升级Nacos时，出一个升级指南，或者自动化处理，将`""`更新为其他的唯一id值。

3. 现在的`public`才是特殊的存在，因为它目前只存在于内存和前端，并不存在于数据库。正如1点所述，现有逻辑已经对其唯一性进行了校验。

4. 更宽松一点来说，应该不存在所谓的`保留命名空间`的概念，每个命名空间在抽象概念上应该是一致的，开发者需要创建、使用、修改、删除哪个命名空间应该完全由开发者进行决定。

**Comment by mishi321** [comment]
我觉得这种设计不合理,如果真的不改但是至少也要在文档有个地方强调一下啊,入坑的时候被这个东西搞了好久.spring boot也不报错,也拉取得到内容,但是日志无限config change拉取

**Comment by KomachiSion** [comment]
> 我觉得这种设计不合理,如果真的不改但是至少也要在文档有个地方强调一下啊,入坑的时候被这个东西搞了好久.spring boot也不报错,也拉取得到内容,但是日志无限config change拉取

欢迎贡献到文档上。

**Comment by KomachiSion** [comment]
> 1. 保持id的唯一性这一点，我认为设置为`""`是唯一的，设置成字符串`public`也是唯一的，更广泛的来说，设置成为任一值，都是可以保证唯一的，因为现有逻辑和数据库已经校验了id的唯一性。
> 2. 至于所说的 _`为了兼容部分已经在生产环境中使用的用户`_ ，其实在用户升级Nacos时，出一个升级指南，或者自动化处理，将`""`更新为其他的唯一id值。
> 3. 现在的`public`才是特殊的存在，因为它目前只存在于内存和前端，并不存在于数据库。正如1点所述，现有逻辑已经对其唯一性进行了校验。
> 
> ```
> @GetMapping
>     public RestResult<List<Namespace>> getNamespaces(HttpServletRequest request, HttpServletResponse response) {
>         List<TenantInfo> tenantInfos = persistService.findTenantByKp(DEFAULT_KP);
>         Namespace namespace0 = new Namespace("", DEFAULT_NAMESPACE, DEFAULT_QUOTA,
>                 persistService.configInfoCount(DEFAULT_TENANT), NamespaceTypeEnum.GLOBAL.getType());
>         List<Namespace> namespaces = new ArrayList<Namespace>();
>         namespaces.add(namespace0);
>         for (TenantInfo tenantInfo : tenantInfos) {
>             int configCount = persistService.configInfoCount(tenantInfo.getTenantId());
>             Namespace namespaceTmp = new Namespace(tenantInfo.getTenantId(), tenantInfo.getTenantName(), DEFAULT_QUOTA,
>                     configCount, NamespaceTypeEnum.CUSTOM.getType());
>             namespaces.add(namespaceTmp);
>         }
>         return RestResultUtils.success(namespaces);
>     }
> ```
> 
> 5. 更宽松一点来说，应该不存在所谓的`保留命名空间`的概念，每个命名空间在抽象概念上应该是一致的，开发者需要创建、使用、修改、删除哪个命名空间应该完全由开发者进行决定。

1. 原本设计中`public`不存在特殊性，这个是中途引入的问题。如果彻底解决就需要对所有涉及到这方面的地方梳理。
2. 升级指南可以有，但是不能指望使用者都会去看这个内容，或者认真看这个内容，一旦有遗漏很可能就有较大的问题，除非是避免不了的情况，比如1.X升级2.X这种架构和数据结构都调整的情况。
3&4. `public` 只是默认命名空间的名字，默认命名空间只是个缺醒值，因为nacos必须要有命名空间才能运作，所以必须有一个默认命名空间的特殊存在，这个命名空间不能删除。否则需要对所有接口进行重构，要求必须输入命名空间id

**Comment by KomachiSion** [comment]
No more question and discussion in issue more than 2 weeks, close issue first.

**Comment by GONETHEN** [comment]
> public 是命名空间的名字， 其id是空字符串"" 手动指定应该制定成`namespace=`

感谢，我遇到了类似的问题，知道看到了您的回复。
话说这么搞这个也太坑了吧，希望下次更新能把id改成public

**Comment by lawrencewu** [comment]
在springboot中 同遇到这个问题，namespace设置为public，拉取不到配置，文档中也无说明，只好去看源代码梳理。文档中很多的TODO项至今仍是TODO; 建议提高下文档质量。
