### ISSUE TITLE
nacos-0.8.0注册中心无法获取配置信息

### ISSUE THREAD

**Issue by hadoop835** [alibaba/nacos#792]
1、官网下载nacos-0.8版本，单机和集群启动。
 2、下载下载nacos-examples实例导入idea中
 3、在nacos控制台配置
![image](https://user-images.githubusercontent.com/8055054/53070506-5996fd00-351a-11e9-9b20-ce912b4d9591.png)
4.访问http://localhost:8080/config/get地址无法获取配置信息的配置信息

**Comment by TsingLiang** [comment]
you can use http openAPI test it.
