### ISSUE TITLE
集群节点下线后，怎么重新上线？

### ISSUE THREAD

**Issue by skyjilygao** [alibaba/nacos#7928]
从集群管理-节点列表，下线节点后。
在剩余节点的cluster.conf增加新节点（新节点的cluster.conf已经加了所有节点ip:port），不生效。
必须先停止所有节点，修改`cluster.conf`，最后启动所有节点。才可以。

From cluster management - node list, after offline nodes.
In the cluster. Of the remaining nodes Conf adds a new node (all node IP: ports have been added to the cluster.conf of the new node), which does not take effect.
You must first stop all nodes and modify the cluster Conf, and finally start all nodes. Can only.

**Comment by hujun-w-2** [comment]
不需要重启  只修改cluster.conf的配置 服务会自动感知  和扩容操作一样  目前nacos不支持新增节点之后，其他节点自动感知

**Comment by KomachiSion** [comment]
可能需要看一下你的cluster.conf文件是否为软连接文件， 软连接文件是没有文件变更事件的， 会导致nacos监听不到这个文件你做了操作，从而不是重新读取。

**Comment by skyjilygao** [comment]
> 

不是软连接文件，直接是nacos下的。

**Comment by skyjilygao** [comment]
> 不需要重启 只修改每个节点cluster.conf的配置 服务会自动感知 和扩容操作一样

好的，我再试试

**Comment by skyjilygao** [comment]
> > 不需要重启 只修改每个节点cluster.conf的配置 服务会自动感知 和扩容操作一样
> 
> 好的，我再试试

顺便问下，修改cluster.conf的配置，有没有接口？不然得进到每个节点配置一次

**Comment by KomachiSion** [comment]
肯定没有啊， 从设计角度来说，通过接口改配置文件太危险了，从误操作和安全角度都不可行。
