### ISSUE TITLE
Remove redundant code about 1.x in develop branch.

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#7930]

**Comment by KomachiSion** [comment]
After PMC & Committer vote for this issue, Community will default close these feature about `Compatible with upgrade from 1.X` and remove these codes after 2.2 version.

**Comment by wangdongyun** [comment]
> After PMC & Committer vote for this issue, Community will default close these feature about `Compatible with upgrade from 1.X` and remove these codes after 2.2 version.

1.x 和 2.x 代码同时存在，太乱了

**Comment by yangzhongj** [comment]
同意云歌说法，建议直接干掉，也促使用户升级
