### ISSUE TITLE
linux 2.0.4压缩包版用户创建后，用户名自动变成nacos,xxx问题

### ISSUE THREAD

**Issue by GPL1** [alibaba/nacos#7931]
linux版本的2.0.4的压缩包版。standalone启动。
1创建用户自动加上nacos, 比如 用户a ，变成nacos,a
2.绑定角色后列表里不显示，只显示ROLE_ADMIN和nacos用户
3.删除用户提示cannot delete admin：nacos；但是我删除的并不是nacos用户，用浏览器查看请求，无论删除哪个用户参数都传nacos

**Comment by GPL1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 上午10:31
***@***.***&gt;;
抄送:&nbsp;"2 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] linux 2.0.4压缩包版用户创建后，用户名自动变成nacos,xxx问题 (Issue #7931)





 
用的啥浏览器?? 版本是多少？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by onewe** [comment]
我试了一下 无论是在 chrome 还是 firefox 上都没复现这个问题,请提供详细信息,以及复现步骤. 谢谢

**Comment by GPL1** [comment]
换个浏览器，火狐，没问题了

**Comment by GPL1** [comment]
谷歌浏览器
版本 98.0.4758.102（正式版本） （64 位）

**Comment by GPL1** [comment]
已找到问题，是页面缓存，可能之前是低版本的页面，缓存了，换2.0.4之后出现的问题，清理缓存

**Comment by GPL1** [comment]
> 我试了一下 无论是在 chrome 还是 firefox 上都没复现这个问题,请提供详细信息,以及复现步骤. 谢谢

感谢支持

**Comment by onewe** [comment]
@GPL1 这个估计是老版本前端缓存的bug
