### ISSUE TITLE
It is recommended that all open APIs unify the format of return value to reduce the user's use cost and understanding cost

### ISSUE THREAD

**Issue by Chaos-coder** [alibaba/nacos#7932]
**Describe the bug**
It is recommended that all open APIs unify the format of return value to reduce the user's use cost and understanding cost

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by kuaile-zc** [comment]
Here 

https://nacos.io/zh-cn/docs/open-api.html

**Comment by kuaile-zc** [comment]
官方有计划在官方页面提供一下nacos 2.X版本的GRPC OpenAPI吗？

**Comment by KomachiSion** [comment]
Grpc is not OpenAPI.
