### ISSUE TITLE
nacos2.0.3版本，三台服务器已经开通8848,7848,9848,9849端口，但是以集群模式启动之后还是连接失败

### ISSUE THREAD

**Issue by foreverloveali** [alibaba/nacos#7935]
naming-raft日志：
2022-03-12 09:34:05,037 ERROR NACOS-RAFT vote failed: 500, url: http://我的ip1:8848/nacos/v1/ns/raft/vote
2022-03-12 09:34:05,037 ERROR NACOS-RAFT vote failed: 500, url: http://我的ip2：8848/nacos/v1/ns/raft/vote

alipay-jraft日志：
PreVote to 我的ip:7848 error: Status[ENOENT<1012>: Peer id not found: 我的ip:7848, group: naming_persistent_service].

start.out无异常

内网ip和外网ip都试过了，都不行

**Comment by KomachiSion** [comment]
1. 已废弃接口，保留仅为了从低版本1.X（如1.2.1）进行平滑升级，报错为正常。
2. jraft显示节点（你的ip）不再配置中，自查环境搭建问题

**Comment by alang124** [comment]
试试

Nacos2.0版本相比1.X新增了gRPC的通信方式，因此需要增加2个端口。新增端口是在配置的主端口(server.port)基础上，进行一定偏移量自动生成。

端口	与主端口的偏移量	描述
9848	1000	客户端gRPC请求服务端端口，用于客户端向服务端发起连接和请求
9849	1001	服务端gRPC请求服务端端口，用于服务间同步等

**Comment by KomachiSion** [comment]
No more response from author. So close issue.
