### ISSUE TITLE
When client wants to use public namespace, the behavior is inconsistent between http and grpc

### ISSUE THREAD

**Issue by catcherwong** [alibaba/nacos#7936]
**Describe the bug**

nacos server's version is 2.0.4

When client sets the namespace to an empty string:

1. Communicating with http, we can find out instances in nacos console.
2. Communicating with grpc, we cannot find out instances in nacos console.

After taking a look on the source code, there are some different between them.

https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java#L107-L108

https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java#L48-L49

The controller has a default value when namespace is empty, but the handler does not contain this logic.

---------

当 client 把命名空间设置成空字符串的时候，

1. 用http和服务端交互，在控制台可以看到这个实例
2. 用grpc和服务端交互，在控制台看不到这个实例

查看源码后发现两者的处理逻辑有些不一样，controller 上面有一个默认值处理， handler 上面没有这一块的逻辑。

关联 https://github.com/nacos-group/nacos-sdk-csharp/issues/187

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by apfeldieb** [comment]
> **Describe the bug**
> 
> nacos server's version is 2.0.4
> 
> When client sets the namespace to an empty string:
> 
> 1. Communicating with http, we can find out instances in nacos console.
> 2. Communicating with grpc, we cannot find out instances in nacos console.
> 
> After taking a look on the source code, there are some different between them.
> 
> https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceController.java#L107-L108
> 
> https://github.com/alibaba/nacos/blob/2e07c6a0c162b5685f86414f0be5ba521a39fa39/naming/src/main/java/com/alibaba/nacos/naming/remote/rpc/handler/InstanceRequestHandler.java#L48-L49
> 
> The controller has a default value when namespace is empty, but the handler does not contain this logic.
> 
> 当 client 把命名空间设置成空字符串的时候，
> 
> 1. 用http和服务端交互，在控制台可以看到这个实例
> 2. 用grpc和服务端交互，在控制台看不到这个实例
> 
> 查看源码后发现两者的处理逻辑有些不一样，controller 上面有一个默认值处理， handler 上面没有这一块的逻辑。
> 
> 关联 [nacos-group/nacos-sdk-csharp#187](https://github.com/nacos-group/nacos-sdk-csharp/issues/187)
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Acutally behavior** A clear and concise description of what you actually to happen.
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Centos]
> * Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
> * Module [e.g. naming/config]
> * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> 
> **Additional context** Add any other context about the problem here.

**Comment by KomachiSion** [comment]
Java sdk如果设置的命名空间是空字符串，会自动的设置成默认命名空间，所以服务端就没有再做。
旧版本http接口是由于同时需要适配sdk和openAPI 因此做了兼容操作，防止openAPI漏填该项目。

因此可能需要csharp sdk在使用grpc时添加一下命名空间默认值。

**Comment by KomachiSion** [comment]
另外也可以讨论下，服务端是否要做命名空间的判断。

**Comment by catcherwong** [comment]
> 因此可能需要csharp sdk在使用grpc时添加一下命名空间默认值。

了解了，我这边适配一下。

> 另外也可以讨论下，服务端是否要做命名空间的判断。

这个服务端其实可以不需要做判断，由客户端决定即可。
