### ISSUE TITLE
Nacos has Ultra Vires Vulnerability

### ISSUE THREAD

**Issue by N1ce759** [alibaba/nacos#7937]
# Nacos has Ultra Vires Vulnerability
* Version: 2.0.4
* Description: Nacos has a defect in identifying the permissions of common users. As a result, the administrator password can be changed through common user permissions.
* Details:
Setting up the Nacos Server locally
![image](https://user-images.githubusercontent.com/100123029/158056805-0e0db9cd-b39d-4016-9e02-a2c37e1fc859.png)
![image](https://user-images.githubusercontent.com/100123029/158056811-de3d499a-d429-4796-8560-45bb1d5c4813.png)

Log in to the system using the default password **nacos:nacos** and create a **test:test** user.
![image](https://user-images.githubusercontent.com/100123029/158056825-58019d5b-f773-4877-ad7c-55359b4383c4.png)

Log in to the **test** user, change the password, change the username parameter to **nacos**, and send data packets.
![image](https://user-images.githubusercontent.com/100123029/158056849-8409ebc4-e9e9-4981-a2b2-f71cbf7a17de.png)

We can see that the changes are successful and log in to the system using **nacos:test**
![image](https://user-images.githubusercontent.com/100123029/158056872-5203488a-1f75-4e6a-bff0-479354641ce6.png)

**Comment by KomachiSion** [comment]
Do you open the auth feature?

**Comment by N1ce759** [comment]
default installation configuration is used and no additional configuration is performed

**Comment by KomachiSion** [comment]
default auth feature is closed, please open auth according document and retry again.

**Comment by KomachiSion** [comment]
If this problem no longer exist, the issue should be closed. Other problem should submit new issue with detail.
