### ISSUE TITLE
Config version diff error in Config Detail page

### ISSUE THREAD

**Issue by yuuagoo** [alibaba/nacos#7941]
**Describe the bug**
![image](https://user-images.githubusercontent.com/57406595/158295760-7b6623c6-fb04-4c71-ad5d-bfc9ac1678ff.png)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Fixed by #7964
