### ISSUE TITLE
A suggestion about the problem of configuration files being overwritten

### ISSUE THREAD

**Issue by JJBoy1995** [alibaba/nacos#7945]
### When the configuration is published, it is easy to be overwritten in the following scenarios. 
When n pages stay on the edit configuration page, the configuration published later will overwrite the configuration published earlier. 
This situation is relatively easy to occur in the dev environment development of the team. Can we introduce an optimistic lock mechanism here and verify it when updating to ensure that it is modified on the basis of the latest configuration each time?
### Here is some code to modify the configuration. The SQL part is just a simple update, which may cause the above problem.
![微信截图_20220315162935](https://user-images.githubusercontent.com/34465414/158344356-6b020f15-2501-4b59-ab64-c57b700b6caf.png)

**Comment by KomachiSion** [comment]
Nacos only apply config by request order, there is no way to controller website pages.
