### ISSUE TITLE
Nacos2.0.4 Develop分支提示encrypted_data_key列在数据库表中不存在

### ISSUE THREAD

**Issue by Chaos-coder** [alibaba/nacos#7948]
**Describe the bug**
When clicking Edit on the configuration page, an error is reported as follows:
<img width="1557" alt="image" src="https://user-images.githubusercontent.com/35129699/158571338-292969cc-d721-4527-a193-45a85fb56f21.png">

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 2.0.4]
 - Module [config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by li-xiao-shuang** [comment]
> **Describe the bug** When clicking Edit on the configuration page, an error is reported as follows: <img alt="image" width="1557" src="https://user-images.githubusercontent.com/35129699/158571338-292969cc-d721-4527-a193-45a85fb56f21.png">
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Acutally behavior** A clear and concise description of what you actually to happen.
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Centos]
> * Version [e.g. nacos-server 1.3.1, nacos-client 2.0.4]
> * Module [config]
> * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> 
> **Additional context** Add any other context about the problem here.

develop 分支目前把加解密合并进去了，数据库表新增秘钥字段，拉一下最新的代码，然后给表添加下encrypted_data_key字段

**Comment by Chaos-coder** [comment]
> > **Describe the bug** When clicking Edit on the configuration page, an error is reported as follows: <img alt="image" width="1557" src="https://user-images.githubusercontent.com/35129699/158571338-292969cc-d721-4527-a193-45a85fb56f21.png">
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Acutally behavior** A clear and concise description of what you actually to happen.
> > **How to Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. Centos]
> > * Version [e.g. nacos-server 1.3.1, nacos-client 2.0.4]
> > * Module [config]
> > * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> > 
> > **Additional context** Add any other context about the problem here.
> 
> develop 分支目前把加解密合并进去了，数据库表新增秘钥字段，拉一下最新的代码，然后给表添加下encrypted_data_key字段

我拉的是最新的代码，使用的嵌入式数据库。没有连MYSQL，这个问题还是存在。

**Comment by li-xiao-shuang** [comment]
> > > **Describe the bug** When clicking Edit on the configuration page, an error is reported as follows: <img alt="image" width="1557" src="https://user-images.githubusercontent.com/35129699/158571338-292969cc-d721-4527-a193-45a85fb56f21.png">
> > > **Expected behavior** A clear and concise description of what you expected to happen.
> > > **Acutally behavior** A clear and concise description of what you actually to happen.
> > > **How to Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Go to '...'
> > > 2. Click on '....'
> > > 3. Scroll down to '....'
> > > 4. See error
> > > 
> > > **Desktop (please complete the following information):**
> > > 
> > > * OS: [e.g. Centos]
> > > * Version [e.g. nacos-server 1.3.1, nacos-client 2.0.4]
> > > * Module [config]
> > > * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> > > 
> > > **Additional context** Add any other context about the problem here.
> > 
> > 
> > develop 分支目前把加解密合并进去了，数据库表新增秘钥字段，拉一下最新的代码，然后给表添加下encrypted_data_key字段
> 
> 我拉的是最新的代码，使用的嵌入式数据库。没有连MYSQL，这个问题还是存在。

那需要删除本地的 data 文件夹 ，让它重新创建

**Comment by Chaos-coder** [comment]
> > > > **Describe the bug** When clicking Edit on the configuration page, an error is reported as follows: <img alt="image" width="1557" src="https://user-images.githubusercontent.com/35129699/158571338-292969cc-d721-4527-a193-45a85fb56f21.png">
> > > > **Expected behavior** A clear and concise description of what you expected to happen.
> > > > **Acutally behavior** A clear and concise description of what you actually to happen.
> > > > **How to Reproduce** Steps to reproduce the behavior:
> > > > 
> > > > 1. Go to '...'
> > > > 2. Click on '....'
> > > > 3. Scroll down to '....'
> > > > 4. See error
> > > > 
> > > > **Desktop (please complete the following information):**
> > > > 
> > > > * OS: [e.g. Centos]
> > > > * Version [e.g. nacos-server 1.3.1, nacos-client 2.0.4]
> > > > * Module [config]
> > > > * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> > > > 
> > > > **Additional context** Add any other context about the problem here.
> > > 
> > > 
> > > develop 分支目前把加解密合并进去了，数据库表新增秘钥字段，拉一下最新的代码，然后给表添加下encrypted_data_key字段
> > 
> > 
> > 我拉的是最新的代码，使用的嵌入式数据库。没有连MYSQL，这个问题还是存在。
> 
> 那需要删除本地的 data 文件夹 ，让它重新创建

ok 可以啦
