### ISSUE TITLE
 nacos0.8.0版本服务权重和上线下线功能无效

### ISSUE THREAD

**Issue by 15150762026** [alibaba/nacos#795]
jdk1.8，nacos0.8.0 

使用xml的形式注册dubbo服务

注册到nacos的服务点击下线按钮后，消费者调用这服务还是能成功

我在2台服务器上部署了同样的服务，在nacos上把其中一个服务的权重改为0，但还是会请求到这台服务器

**Comment by xuechaos** [comment]
@15150762026 你的客户端版本是多少？

**Comment by 15150762026** [comment]
明天我到公司后再回复你发自我的华为手机-------- 原始邮件 --------主题：Re: [alibaba/nacos]  nacos0.8.0版本服务权重和上线下线功能无效 (#795)发件人：xxc 收件人：alibaba/nacos 抄送：15150762026 <604264765@qq.com>,Mention @15150762026 你的客户端版本是多少？

**Comment by Cryice** [comment]
环境版本：
1. spring-cloud-starter-gateway 2.0.2.RELEASE
1. nacos-client 0.6.2

路由配置方式

> spring:
  application:
    # 应用名称
    name: spring-gateway
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用 Sentinel 作为熔断器
    sentinel:
      transport:
        port: 8721
        dashboard: localhost:8080
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
          #小写服务名称
          lowerCaseServiceId: true
      # 配置路由规则
      routes:
        - id: NACOS-CONSUMER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://nacos-consumer
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST
        - id: NACOS-CONSUMER-FEIGN
          uri: lb://nacos-consumer-feign
          predicates:
            - Method=GET,POST
        - id: SENTINEL-EXAMPLE
          uri: lb://sentinel-example
          predicates:
            - Method=GET,POST
        - id: NACOS-PROVIDER
          uri: lb://nacos-provider
          predicates:
            - Method=GET,POST
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/s
        - id: taobao
          uri: https://www.jd.com/
          predicates:
            - Path=/markets/3c/tbdc
        - id: OAUTH2
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://oauth2
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST

出现权重设置无效的问题

@xuechaos

**Comment by 15150762026** [comment]
![ds5el1 f2ur6uolwq1 dvl](https://user-images.githubusercontent.com/34929752/53135408-10948680-35b6-11e9-9992-e61caad3aed8.png)
![s gao1w ab an7j9ery6a](https://user-images.githubusercontent.com/34929752/53135412-138f7700-35b6-11e9-9cfd-246ffdf4c79c.png)
@xuechaos   这是我springboot和nacos的全部配置了

**Comment by nkorange** [comment]
看下{user.home}/logs/nacos/naming.log里是否收到了权重修改的推送

**Comment by paderlol** [comment]
目前dubbo的权重目前和nacos 还没打通 暂时权重这块设置是不会起作用的。

**Comment by nkorange** [comment]
上下线功能，请使用最新的nacos-client试下

**Comment by 15150762026** [comment]
![1550837269 1](https://user-images.githubusercontent.com/34929752/53241722-8c3d2300-36dd-11e9-9b5f-b03339c92645.png)
我使用nacos-client最新版本0.8.1，这是我的具体配置，但是上下线功能还是不起作用，方便给个具体的联系方式吗，我确实不知道哪里出了问题
@nkorange

**Comment by 15150762026** [comment]
dubbo服务的上线下线功能及权重配置功能，目前nacos是否支持，能否给个准确的回复
我用的是springboot并没有使用springcloud
@nkorange @xuechaos

**Comment by paderlol** [comment]
目前dubbo的权重目前和nacos 还没打通 暂时权重这块设置是不会起作用的。

**Comment by caojiele** [comment]
我记得这个好像没有打通

**Comment by nkorange** [comment]
> dubbo服务的上线下线功能及权重配置功能，目前nacos是否支持，能否给个准确的回复
> 我用的是springboot并没有使用springcloud
> @nkorange @xuechaos

上下线是打通的，权重还没打通，可以加我微信：nkorange

**Comment by RemixJason** [comment]
@nkorange  hi，我也是同样的问题，在控制台权重设置以后没有作用，调用服务总是平均分配的。naming.log中并没有相应修改了权重的日志。
控制台
```Java
<parent>
     <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-all</artifactId>
    <version>0.9.0</version>
</parent>
```
client
```Java
<dependency>
     <groupId>org.springframework.cloud</groupId>
     <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
     <version>0.2.1.RELEASE</version>
</dependency>
```

现在是2019年03月29日，请问一下权重的功能暂时还用不了吗？

**Comment by nkorange** [comment]
@RemixJason 目前权重打通需要Dubbo这边做开发，可以给Dubbo提个issue。
