### ISSUE TITLE
Follower's state machine ignore read request.

### ISSUE THREAD

**Issue by horizonzy** [alibaba/nacos#7952]
**Expected behavior**
when follower read index failed, it will redirect to leader by raft-log read, then the raft-log will be copy to all nodes(include follower), follower will apply read raft-log also. In fact, follower can ignore read raft-log.

**Comment by Mikecarbon** [comment]
> **Expected behavior** when follower read index failed, it will redirect to leader by raft-log read, then the raft-log will be copy to all nodes(include follower), follower will apply read raft-log also. In fact, follower can ignore read raft-log.



> **Expected behavior** when follower read index failed, it will redirect to leader by raft-log read, then the raft-log will be copy to all nodes(include follower), follower will apply read raft-log also. In fact, follower can ignore read raft-log. 
Writer don't follow read raft log.

**Comment by Westside991** [comment]
Main

**Comment by KomachiSion** [comment]
I think the problem is caused by jraft system, is it?

**Comment by horizonzy** [comment]
It's nacos state machine logic, it can be enhance. @chuntaojun cc

**Comment by chuntaojun** [comment]
> It's nacos state machine logic, it can be enhance. @chuntaojun cc

yes. it's can be optimize, if read operation throuth raft log not read-index, follower not need apply

**Comment by KomachiSion** [comment]
@horizonzy do some enhancement and submit PR？
