### ISSUE TITLE
Build console-ui error cause the lowercase filename

### ISSUE THREAD

**Issue by yuuagoo** [alibaba/nacos#7957]
**Describe the bug**

The following error occurred while packaging console-ui:

![image](https://user-images.githubusercontent.com/57406595/159037013-81407bbe-99bf-4be2-acdd-aca8e216c614.png)

**Expected behavior**
console-ui build successfully

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
cd console-ui
npm run build

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
The problem has been resolved after renaming the file "instanceFilter.js" to "InstanceFilter.js"

**Comment by KomachiSion** [comment]
I never happen this problem in my environment, and I am not good at this part. need the community  help.
