### ISSUE TITLE
nacos直接通过写入数据库没有刷新配置

### ISSUE THREAD

**Issue by clcc2019** [alibaba/nacos#7958]
我们通过将配置插入mysql表的方法新增配置，nacos后台能看到配置，但是api无法获取配置，重启nacos才生效

**Comment by clcc2019** [comment]
nacos 2.0.3 on k8s

**Comment by onewe** [comment]
用openAPI 调用 dump 接口来刷新

**Comment by onewe** [comment]
nacos 是优先用本地缓存的,如果直接改数据库,nacos是不能感知数据有变化的.

**Comment by xingxing122** [comment]
能给一下具体的接口吗
