### ISSUE TITLE
nacos的 yaml配置文件 不支持注入 多个对象

### ISSUE THREAD

**Issue by aworker** [alibaba/nacos#796]
yaml文件配置的对象如下：

![_15506477281636](https://user-images.githubusercontent.com/12840800/53074807-abde1b00-3526-11e9-8a4e-9fae5c8b2339.png)

nacos相关代码如下：
![_20190220154735](https://user-images.githubusercontent.com/12840800/53074933-f95a8800-3526-11e9-9a96-d3d0b9185f62.png)

Person类定义如下：
![_20190220154909](https://user-images.githubusercontent.com/12840800/53075012-260e9f80-3527-11e9-9795-202c3d254176.png)

项目为springboot项目：
nacos坐标为：
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.1</version>
        </dependency>

nacos服务器版本为0.80

**Comment by nkorange** [comment]
@aworker Nacos Spring Boot doesn't support .yml configuration.
