### ISSUE TITLE
建议nacos的管理界面优化

### ISSUE THREAD

**Issue by comeking** [alibaba/nacos#7963]
建议将nacos的配置管理和服务管理中的Group单独调一个层级出来显示，类似namespace
系统之间会存在相互调用，使用group进行区分系统后，可以通过tab方式去展示我有哪些系统及下面的服务

**Comment by li-xiao-shuang** [comment]
> 建议将nacos的配置管理和服务管理中的Group单独调一个层级出来显示，类似namespace 系统之间会存在相互调用，使用group进行区分系统后，可以通过tab方式去展示我有哪些系统及下面的服务

感兴趣的话可以参与贡献哈

**Comment by comeking** [comment]
从实际使用架构上考虑，namespace设计的初衷是为了区分环境，不同nemespace下的服务是不互通的。研发测试生产环境在实际中是进行了物理隔离部署（分别部署），当然在研发多个team中互不干扰时用nemespace区分是不错的。一般的规模都有一些公共的基础服务，我们是希望很多team都能够调用，那么只能使用同namespace下的group，相同group下是一个scrum组在运作这个项目，可能涉及服务众多，为了便于管理，可以将namespace收缩，展开group，这样界面不会很复杂的，便于各组更便捷的区分项目和开展工作，统一进行服务的配置和服务的监管。

**Comment by KomachiSion** [comment]
@comeking 可以做个demo来展示一下吗？

**Comment by KomachiSion** [comment]
No more discuss in community and author has no response about this issue.
