### ISSUE TITLE
db.num=2, but only one mysql has data, no data in another one.

### ISSUE THREAD

**Issue by KeithTt** [alibaba/nacos#7965]
nacos version: 2.0.4
mysql: 5.7.25-TiDB-v4.0.0

```
spring.datasource.platform=mysql
db.num=2
db.url.0=jdbc:mysql://xxx
db.url.1=jdbc:mysql://xxx
db.user=user
db.password=pass
```

Only `db.url.0` hold data..

**Comment by hujun-w-2** [comment]
只会往一个mysql里面写  这里配置多个是为了使用mysql主从模式或者集群模式的用户的，比如有的用户数据库做了读写分离

**Comment by hujun-w-2** [comment]
mysql的高可用 是需要你自己保证的，当前这样的设计就是为了有的用户数据库做了读写分离  读和写是两个库

**Comment by hujun-w-2** [comment]
数据库之间的数据同步  mysql已经做的很好了，nacos没必要再实现一套

**Comment by KeithTt** [comment]
> mysql的高可用 是需要你自己保证的，当前这样的设计就是为了有的用户数据库做了读写分离 读和写是两个库

从实际情况来看，只有 `db.url.0` 在工作（读和写）。如果是主从同步或者是读写分离，那么`db.url.1` 该配置啥？从节点地址？

**Comment by KomachiSion** [comment]
从来没说数据库是双写啊， 主从同步需要使用mysql的同步能力， 配置多个db是为了容灾。

**Comment by KeithTt** [comment]
> 从来没说数据库是双写啊， 主从同步需要使用mysql的同步能力， 配置多个db是为了容灾。

@KomachiSion  谢谢，了解了。

请问一下这个容灾是怎么实现的，我当前配置两个库，只有一个在工作。如果 db0 挂了，会自动切换到 db1 ？
