### ISSUE TITLE
When the number of files in logs is too large, logback has inherent problems causing high CPU

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#7968]
nacos 默认使用logback输出日志，默认策略SizeAndTimeBasedRollingPolicy；

**背景**：项目要求日志按小时切分滚动
logback存在固有缺陷（java.io.File.listFiles()），当使用策略SizeAndTimeBasedRollingPolicy的时候，如果日志目录文件数目过多（4c容器，超过400个日志文件），日志切分的时间点附近会消耗大量的CPU

使用log4j2 可以解决这个问题

提供nacos-server端使用的nacos-log4j2.xml一份

要想将nacos-server端的日志输出改成log4j，需要
1、修改nacos-console模块的日志依赖，排除logback，使用log4j2
2、将nacos-log4j2.xml修改为 nacos-logback.xml放到conf目录下。（不知道为什么nacos-server只加载名为nacos-logback.xml的日志配置文件，没找到源码在哪里修改）

**Comment by KomachiSion** [comment]
Nacos server端只使用logback，不更换为log4j2， 如果有特殊需求需要更换为log4j2的，请自行更换。
