### ISSUE TITLE
1.4.3 error Could not resolve placeholder

### ISSUE THREAD

**Issue by rockit-ba** [alibaba/nacos#7977]
**Describe the bug**
i use 1.4.3,conf as :
spring:
  application:
    name: example
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848

![image](https://user-images.githubusercontent.com/53960157/159438881-a52369f2-c273-4bc9-8eba-d28da2b5d5f2.png)

my code :
`@RestController
@RequestMapping("/config")
@RefreshScope
public class ConfigController {

    @Value("${flag}")
    private boolean flag;

    /**
     * http://localhost:8080/config/get
     */
    @RequestMapping("/get")
    public boolean get() {
        return flag;
    }
}`

**Expected behavior**
it`s should be ini.

**Acutally behavior**
new it`s :java.lang.IllegalArgumentException: Could not resolve placeholder 'flag' in value "${flag}"

**Comment by KomachiSion** [comment]
please provide ${user.home}/logs/nacos/config.log

or move issue to Spring cloud aliabab community

**Comment by rockit-ba** [comment]
> 



> please provide ${user.home}/logs/nacos/config.log
> 
> or move issue to Spring cloud aliabab community

i can`t find this file for config.log
![image](https://user-images.githubusercontent.com/53960157/159611552-a9f2ab06-bae2-45f0-8774-27a44e0b2e18.png)

**Comment by rockit-ba** [comment]
> please provide ${user.home}/logs/nacos/config.log
> 
> or move issue to Spring cloud aliabab community

i`m sure ,that`s` version`s bug , 2.0.4 is really ok.
