### ISSUE TITLE
springcloud+nacos项目启动

### ISSUE THREAD

**Issue by cydazm** [alibaba/nacos#7978]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.4.RELEASE)

Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.nacosConfigController': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'config.appName' in value "${config.appName}"

项目获取本地nacos上的application.yaml跟项目中的bootstrap.yml能够正常启动，但是换成服务器上nacos的application.yaml跟本地的bootstrap.yml启动就报上面这个错了。尝试添加了spring-cloud-starter-bootstrap依赖跟spring-cloud-comment依赖也还是一样。

**Comment by vividfish** [comment]
检查下~/logs/nacos/config.log日志有没有获取到目标application.yaml的配置

**Comment by KomachiSion** [comment]
No more response
