### ISSUE TITLE
Optimization method definition

### ISSUE THREAD

**Issue by Oliverwqcwrw** [alibaba/nacos#7980]
## Issue Description

Type: feature request

In `com.alibaba.nacos.address.controller.AddressServerClusterController#deleteCluster`

I think it would be clearer to add a generic to the method return value，
I need to look at the whole method to know for now

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
We can't get the key meanings from your description.

**Comment by Oliverwqcwrw** [comment]
I think it would be clearer to add genericity to the method return value

**Comment by KomachiSion** [comment]
Can you submit an PR to add method comment?

**Comment by Oliverwqcwrw** [comment]
yes

**Comment by Oliverwqcwrw** [comment]
I have submited a PR #7986
