### ISSUE TITLE
首次更新配置不生效

### ISSUE THREAD

**Issue by choconana** [alibaba/nacos#7983]
**版本：**
nacos-server:1.4.2, nacos-client:1.4.1, spring-cloud-alibaba:2.2.5

**问题描述：**
启动后第一次修改nacos上的配置后，控制台打印出了更新信息，但是实际的配置没有更新。之后多次修改配置都能正常更新。
配置类代码：
~~~
@Slf4j
@Data
@Component
@ConfigurationProperties(prefix = "iptables")
@RefreshScope
public class IPtablesConfig {

    // 配置属性列表
    private List<Map<String, String>> mappings;

    // 实际使用
    public static Map<String, String> ipMap = new HashMap<>();

    /** 初始化 **/
    @Bean
    public void transfer() {
        this.toMap();
    }

    /** 监听配置刷新 **/
    @EventListener
    public void envListener(EnvironmentChangeEvent event) {
        log.info("iptables change: " + event);
        this.toMap();
    }

    // 将配置的属性列表转为实际使用的map
    public void toMap() {
        // 打印实际的ip映射信息
        log.info("ip-mappings: {}", mappings.toString());

        if (mappings == null && mappings.isEmpty()) {
            log.warn("当前不存在ip映射...");
            return;
        }
        log.info("正在构建ip映射...");
        ipMap.clear();
        mappings.forEach(map -> {
            ipMap.put(map.get("priv"), map.get("pub"));
        });
    }
}
~~~

**过程：**
启动时：
![image](https://user-images.githubusercontent.com/50023853/159674263-bd4a295d-339b-4c92-a951-f43b04b5c3ba.png)

![image](https://user-images.githubusercontent.com/50023853/159674181-b32b7e35-a164-406d-af65-4c73954ab832.png)
启动后能正常拉取配置。

第一次更新：
![image](https://user-images.githubusercontent.com/50023853/159674630-f710962e-9399-4a47-aa63-aa23b8e6b667.png)

![image](https://user-images.githubusercontent.com/50023853/159674774-02e553c8-a0fc-4509-9084-66e71f5e2202.png)
可以看到配置更新的系统日志打印出来了，但是配置类中打印出来的信息还是未更新的。

第二次更新：
![image](https://user-images.githubusercontent.com/50023853/159676077-fb55c316-3fd5-48ab-b030-22fab7344751.png)

![image](https://user-images.githubusercontent.com/50023853/159676175-fd762d1c-cc69-493c-8085-eaff410b34d7.png)
之后就可以正常刷新了。

**Comment by KomachiSion** [comment]
日志打印出新配置说明nacos-client确实接收了新的配置变更，你所说的未刷新是说spring cloud的配置没有刷新吗？

那可能需要您把这个issue转到spring cloud alibaba社区。让他们排查下第一次配置变更没有刷新的原因。

**Comment by choconana** [comment]
> 日志打印出新配置说明nacos-client确实接收了新的配置变更，你所说的未刷新是说spring cloud的配置没有刷新吗？
> 
> 那可能需要您把这个issue转到spring cloud alibaba社区。让他们排查下第一次配置变更没有刷新的原因。

好的

**Comment by saxingz** [comment]
Same issue
