### ISSUE TITLE
2.0.4 修改账号nacos的 密码

### ISSUE THREAD

**Issue by peterAndzeze** [alibaba/nacos#7988]
默认的nacos 账号的密码又不能改了。。。。

**Comment by KomachiSion** [comment]
麻烦提供更多细节

**Comment by hais1992** [comment]
>  跟这个一样  https://github.com/alibaba/nacos/issues/7750

**Comment by onewe** [comment]
@peterAndzeze 试一试清空缓存,之前接到的反馈说是浏览器缓存问题

**Comment by KomachiSion** [comment]
No more response。
