### ISSUE TITLE
I found a place that was not rigorous when i was looking at the document

### ISSUE THREAD

**Issue by zhongxiongzeng** [alibaba/nacos#7990]
I found a place that was not rigorous when i was looking at the document on the nacos official website.
ZAB should be base on Paxos, and Paxos is more complicated,  and raft is evolution of Paxos.
Is very different from Raft.

![image](https://user-images.githubusercontent.com/41657421/159915064-5b12373e-b725-4a9b-83de-b7e54dc39967.png)

![image](https://user-images.githubusercontent.com/41657421/159914954-cae387e5-c026-4678-9ecd-c98935f98585.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
I can't get your key meaning, 

this part only describe the consistency protocols, not describe they are same.

**Comment by zhongxiongzeng** [comment]
> I can't get your key meaning,
> 
> this part only describe the consistency protocols, not describe they are same.

all right, thx
