### ISSUE TITLE
2.0.4 Configuration rollback format exception

### ISSUE THREAD

**Issue by vinsonzou** [alibaba/nacos#7999]
After the nacos 2.0.4 configuration is rolled back, the original yaml configuration format becomes TEXT

**Comment by KomachiSion** [comment]
The type saved in nacos server only an auxiliary tag, not effect the configuration.

**Comment by onewe** [comment]
@onewe will resolve it@

**Comment by CherishCai** [comment]
确实是有这个问题，加一关注。

**Comment by KomachiSion** [comment]
Refer to #8799
