### ISSUE TITLE
nacos 2.0.2, Using with chrome get an Error info: "request error please try again later!"

### ISSUE THREAD

**Issue by woodmanwumeng** [alibaba/nacos#8003]
**Describe the bug**
Nacos is deployed with docker, in standalone mode and using Derby 

Nacos edition is 2.0.2

When I access the Config module by Chrome, like "http://ip:8848/nacos" , I often get an Error Info: "request error,please try again later!"

The other module seems work normally.

**Comment by KomachiSion** [comment]
I can't reproduce your problem, please provide more information.

**Comment by KomachiSion** [comment]
No more response
