### ISSUE TITLE
DistroConsistencyServiceImpl.Notifier的handle方法出现空指针异常

### ISSUE THREAD

**Issue by liqipeng** [alibaba/nacos#8012]
**Describe the bug**
在1.4.3版本遇到DistroConsistencyServiceImpl.Notifier的handle方法出现空指针异常
```
        private void handle(Pair<String, DataOperation> pair) {
            try {
                String datumKey = pair.getValue0();
                DataOperation action = pair.getValue1();
                
                services.remove(datumKey);
                
                int count = 0;
                
                if (!listeners.containsKey(datumKey)) {
                    return;
                }
                
                for (RecordListener listener : listeners.get(datumKey)) {  // 根据异常信息定位到空指针异常出现在这里
```

**Expected behavior**
不出现 NullPointerException

**Acutally behavior**
出现了 NullPointerException

**How to Reproduce**
分析：
只有并发情况才可能出现空指针异常：
```
        private void handle(Pair<String, DataOperation> pair) {
            try {
                String datumKey = pair.getValue0();
                DataOperation action = pair.getValue1();
                
                services.remove(datumKey);
                
                int count = 0;
                
                if (!listeners.containsKey(datumKey)) {   // 这里判断在listeners中存在datumKey后没有return
                    return;
                }
                
                for (RecordListener listener : listeners.get(datumKey)) {   // 但是并发情况下，这里获取listeners.get(datumKey)可能为null，才可能引起 NullPointerException
```
也就是DistroConsistencyServiceImpl#remove方法与DistroConsistencyServiceImpl.Notifier的handle方法并发执行
```
    @Override
    public void remove(String key) throws NacosException {
        onRemove(key);
        listeners.remove(key);
    }
```
而 DistroConsistencyServiceImpl#remove 只有两处
（1）com.alibaba.nacos.naming.core.ServiceManager#onDelete
（2）com.alibaba.nacos.naming.core.ServiceManager#easyRemoveService
而（1）本身来自 DistroConsistencyServiceImpl.Notifier#handle 处理队列任务时进行事件通知的调用，所以不会引发此问题，所以只有（2）会导致此异常。

ServiceManager#easyRemoveService只有以下两处调用：
（a）com.alibaba.nacos.naming.controllers.ServiceController#remove
（b）com.alibaba.nacos.naming.core.ServiceManager.EmptyServiceAutoClean#run
所以当在控制台进行服务删除操作或者开启了空服务自动清理时可能导致此问题。

**Comment by realJackSun** [comment]
@ i will solve it @

**Comment by liqipeng** [comment]
我来尝试来修复一下这个问题，已提交PR #8187
