### ISSUE TITLE
upgrade default jdk version, in order to scratch Direct memory info via prometheus

### ISSUE THREAD

**Issue by iQuanhe** [alibaba/nacos#8013]
**Is your feature request related to a problem? Please describe.**
In order to monitor the Director memory we should upgrade jdk from 8 to 11 or higher, and I just did in this way. so I suppose upgrade nacos default jdk version to 11.

**Describe the solution you'd like**
upgrade jdk from 8 to 11 or higher

**Describe alternatives you've considered**
upgrade jdk from 8 to 11 or higher

**Additional context**
![Screenshot from 2022-03-28 09-50-57](https://user-images.githubusercontent.com/22134327/160313319-8b1a3127-4902-4884-be11-3f3273736260.png)

**Comment by KomachiSion** [comment]
grpc use netty and netty needs direct buffer by cache buffer so the capacity and used is expected.

**Comment by iQuanhe** [comment]
But Direct memory jvm_buffer_memory_used_bytes can not be scratched via prom in jdk8.  And this also happened in spring-cloud gateway, it's use netty too

**Comment by iQuanhe** [comment]
forget it, and never mind.
