### ISSUE TITLE
nacos auth is disabled to access "/nacos/v1/core/cluster/nodes" endpoint

### ISSUE THREAD

**Issue by tuyongjian1991** [alibaba/nacos#8015]
**Describe the bug**
I have open nacos auth by "nacos.core.auth.enabled=true" in application.properties. When I try to access path "/nacos/v1/cs/configs", it return 403.But when I try to access path "/nacos/v1/core/cluster/nodes", I can get a response with status 200. It will expose my nacos node information.

**Expected behavior**
Return response with 403 status.

**Acutally behavior**
Return response with 200 status and nacos node data.

**How to Reproduce**
Access path "/nacos/v1/core/cluster/nodes"

**Desktop (please complete the following information):**
 - OS: Centos
 - Version nacos-server 2.0.4
 - Module config

**Comment by realJackSun** [comment]
This path "/nacos/v1/core/cluster/nodes", is originally used for intra-cluster communication to get all of the nodes currently in the cluster, so the authentication is missing.

It would be better if we use an intra-token to do inner auth.

**Comment by zhangpeibisha** [comment]
有什么快捷的方法把这个接口设置为需要授权的才能访问吗，不想进行二开，有点浪费时间。。。

**Comment by KomachiSion** [comment]
前端挂一个nginx，拦截一下这个接口

**Comment by KomachiSion** [comment]
There seems be no more discuss.

**Comment by liuzg1992** [comment]
请问，这个问题目前有解决方案了吗
