### ISSUE TITLE
Nacos client can't run with Opentelemetry java agent

### ISSUE THREAD

**Issue by tydhot** [alibaba/nacos#8023]
opentelemetry java agent will wrap the server call.
<img width="767" alt="图片" src="https://user-images.githubusercontent.com/27889201/160520680-4b7fafdf-9e4f-41a0-8ea4-ae8deae1b70f.png">
But in nacos it would get the field 'stream' directly, and it would shutdown.
![图片](https://user-images.githubusercontent.com/27889201/160520843-f480b292-bb39-4abe-b4e8-959e6b140762.png)
I think it's best to support it, and I'm interested in doing it

**Comment by CoderPoet** [comment]
Why this issue was closed?
