### ISSUE TITLE
1.4.3 权限控制功能

### ISSUE THREAD

**Issue by zhuweimin1994** [alibaba/nacos#8031]
创建用户更改用户是，用户名页面传参有问题，username 后台接收的是个数组

**Comment by zhuweimin1994** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/30627100/160567583-a6c34d99-f889-456c-9d5a-a44853597c79.png">




<img width="932" alt="image" src="https://user-images.githubusercontent.com/30627100/160567754-e4737e39-f97d-4903-b9be-bb5565d9d323.png">

**Comment by KomachiSion** [comment]
Please upgrade to 2.X, I remember this problem has fixed in 2.X.
