### ISSUE TITLE
config_tags_relation表的tag_type的作用是什么，代码里直接全部设置为null，导致唯一索引uk_configtagrelation_configidtag失去校验重复作用，出现bug。

### ISSUE THREAD

**Issue by bangbang2333** [alibaba/nacos#8038]
**Describe the bug**
![截屏2022-03-30 15 25 37](https://user-images.githubusercontent.com/43024629/160775634-0f336eef-37d0-4e71-b25b-b29039ac5669.png)
查询出现bug，一条配置查出了三条配置。
config_info表数据如下：
![截屏2022-03-30 15 29 37](https://user-images.githubusercontent.com/43024629/160776017-5d121566-49cc-4f00-89cb-73f162a623d0.png)
config_tags_relation表数据如下：
![截屏2022-03-30 15 30 34](https://user-images.githubusercontent.com/43024629/160776175-cfc01250-3a4b-494f-83ff-0a3d016aab58.png)

**Expected behavior**
期望一条配置只能查询出一条记录。
一条config_info配置，不能和多条“一摸一样”的config_tags_relation记录绑定。

**Acutally behavior**
实际一条配置可以查询出多条记录。
一条config_info配置，可以和多条“一摸一样”的config_tags_relation记录绑定。
原因是插入config_tags_relation时，tag_type写死了是null，导致唯一索性校验失效。

![截屏2022-03-30 15 37 30](https://user-images.githubusercontent.com/43024629/160777389-2f1b7060-5c4f-43bf-b450-5dff427ac398.png)

**How to Reproduce**
我们项目需要使用configTag，我们调用了如下方法进行插入，预期不存在就插入，存在就不插入了，实际情况每次都插入成功了。
![截屏2022-03-30 15 46 38](https://user-images.githubusercontent.com/43024629/160779115-d01921af-c3b4-4bcd-9036-8c6f74864f55.png)

**Additional context**
两种解决思路，config_type不要用null，或者把config_type移出唯一索引

**Comment by onewe** [comment]
tag_type 这个好像的确没啥用

**Comment by bangbang2333** [comment]
解决
