### ISSUE TITLE
文档里没有提到要用@NacosValue获取配置中心的自定义值？？？

### ISSUE THREAD

**Issue by RealMuDao** [alibaba/nacos#8039]
Spring cloud Alibaba 2021.0.1.0中，Nacos版本为1.4.2，在代码中使用@Value获取不到配置中心的自定义值。

**Comment by onewe** [comment]
如果单纯使用 spring 和 spring-boot 则需要用`@NacosValue` 这个注解,如果使用 spring-cloud 则可以不需要使用这个注解
- https://nacos.io/zh-cn/docs/quick-start-spring-boot.html
- https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html

**Comment by RealMuDao** [comment]
> 如果单纯使用 spring 和 spring-boot 则需要用`@NacosValue` 这个注解,如果使用 spring-cloud 则可以不需要使用这个注解
> 
>     * https://nacos.io/zh-cn/docs/quick-start-spring-boot.html
> 
>     * https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html

今天使用Spring cloud Alibaba2021.0.1.0版本，通过@Value始终无拿到自定义在配置中心的值，但是使用Spring cloud Alibaba 2.2.7.RELEASE版本可以。由于这两个版本背后的nacos版本不一样，所以会有这样的问题吗？

**Comment by onewe** [comment]
@RealMuDao 能给出详细的pom配置不？

**Comment by RealMuDao** [comment]
> @RealMuDao 能给出详细的pom配置不？

我找到原因了，我的pom里没有手动添加以下依赖：
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>
加上上面的依赖就可以了。

**Comment by onewe** [comment]
OK, 如果问题解决了的话请关闭一下 issue

**Comment by RealMuDao** [comment]
新版本的spring cloud 不会自动添加spring-cloud-starter-bootstrap依赖。
