### ISSUE TITLE
Back end format verification of configuration center configuration file（配置中心配置文件的后端格式化校验）

### ISSUE THREAD

**Issue by chenhao26-nineteen** [alibaba/nacos#8044]
背景
当前Nacos配置中心的文件格式化校验，主要是通过前端进行控制的，会进行友好的提示，但是还是无法防止用户提交不合法的文件内容，且还会出现偶发性的前端文件格式化校验失效的问题，针对此背景下，对Nacos配置中心的格式化需求，建议在后端加以控制。

background
At present, the file format verification of Nacos configuration center is mainly controlled through the front end, which will give friendly prompts, but it still can not prevent users from submitting illegal file contents, and there will be occasional failure of front-end file format verification. In view of this background, it is recommended to control the formatting requirements of Nacos configuration center at the back end.

设计方案(design scheme)
相关API(Related API)

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/35129699/160962075-313b8e4c-ecce-42e9-a282-30e2afd135bb.png">

校验流程(Verification process)
<img width="720" alt="image" src="https://user-images.githubusercontent.com/35129699/160962092-23519ef0-2a5d-4212-a9f2-5050343cc1fb.png">

1. Console控制台发布配置，调用API接口
2. Controller侧实现过滤器，过滤请求，校验当前数据格式是否合规
3. 数据格式校验成功，check其他参数的合法性，更新或新增配置数据
4. 数据校验失败，否则抛异常

1. The console publishes the configuration and calls the API interface
2. The controller side implements the filter, filters the request, and verifies whether the current data format is compliant
3. The data format is verified successfully, check the validity of other parameters, and update or add configuration data
4. Data verification fails, otherwise exception will be thrown

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Chaos-coder** [comment]
针对SDK侧的校验，可直接复用API校验的逻辑，但是不用注解了，直接在SDK侧嵌入格式化校验的逻辑，相对改造成本较低。配置中心配置文件格式化的逻辑可以抽取到common包中client端和api可以共用。

**Comment by KomachiSion** [comment]
从配置中心的设计来看， 配置内容其实应该是黑盒，目前的配置类型主要还是给控制台做展示格式化使用。服务端没有计划校验配置内容。

如果要做类似的功能，我的建议是在深想一层，做一个配置内容的处理器插件或者拦截器插件，我们本身不提供类似的实现，有需求的用户自行实现插件。因为配置内容对nacos来说是黑盒，但是对实际的用户不是。通过自定义插件来处理/校验内容是合理的。

也可以考虑是否在sdk测去校验和处理，当然也是通过插件式方式。
