### ISSUE TITLE
接口/nacos/v1/auth/users?pageNo=1&pageSize=9可以获取用户名密码列表

### ISSUE THREAD

**Issue by 515445681** [alibaba/nacos#8047]
版本：2.0.4
本地启动：

```
 ./startup.sh -m standalone
```

http://localhost:8848/nacos/v1/auth/users?pageNo=1&pageSize=9

<img width="903" alt="image" src="https://user-images.githubusercontent.com/11323678/160974649-70296c8f-a7db-48ca-a8b2-3a2c15b04d23.png">

**Comment by lmw0509** [comment]
这个是不是不应该直接返回密码啊？而且这个密码是直接从数据库查出来的，也没有进行脱敏处理。

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/161034256-48c0b29e-d595-4948-a2db-f008c027ae34.png)

Please see document to open auth.
