### ISSUE TITLE
nacos server auto down in standalone mode

### ISSUE THREAD

**Issue by shangkun** [alibaba/nacos#805]
nacos server auto down in standalone mode,version 0.8.0

**Comment by bigbluecat** [comment]
run with `nohup` may help

**Comment by shangkun** [comment]
thanks,I'll try it!

**Comment by Fish-Potato** [comment]
Is this problem solved?

**Comment by shangkun** [comment]
have been solved

**Comment by shangkun** [comment]
nohup sh start.sh &
