### ISSUE TITLE
启动模式不支持配置文件配置

### ISSUE THREAD

**Issue by lmw0509** [alibaba/nacos#8053]
**Describe the bug**
当前集群还是单机启动只能通过设置系统属性-Dnacos.standalone，能不能支持通过配置文件配置呢？如果暂时不支持，后续有没有该特性支持计划。

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
No plan to set standalone mode by configuration file. I can't get why config mode by file.

**Comment by lmw0509** [comment]
> No plan to set standalone mode by configuration file. I can't get why config mode by file.

好的，感谢
