### ISSUE TITLE
Nacos 启动报错 No Datasoure set

### ISSUE THREAD

**Issue by hnxyhcz** [alibaba/nacos#8058]
**Describe the bug**
电脑每次重新启动后，先启动docker（mysql数据库是使用docker创建的），然后再启动nacos服务，会报错No Datasource Set。
然后使用工具Navicat连接Mysql是能连接上，在使用navicat连接mysql后，重新启动nacos服务就能成功了。

**Expected behavior**
期望在电脑重新启动后，mysql服务也启动后，能直接启动nacos服务。不需要通过数据库连接工具连接成功后，才能启动成功。

**Acutally behavior**
我现在的情况是，需要先通过navicat连接mysql成功后，nacos才能启动成功。（连接成功后关闭navicat什么的都能成功，猜测是需要通过客户端连接一次mysql后，nacos才能连接上mysql）

**How to Reproduce**
1. 重新启动电脑
2. 打开terminal，执行wsl
3. 进入到虚拟机中，执行service docker start启动docker(mysql在docker中)
4. 启动nacos服务（这时会报错）
5. 使用navicat工具测试mysql是否能正常连接（结果能连接上mysql）
6. 重新启动nacos服务（这时就启动成功）

**Desktop (please complete the following information):**
 - OS: ubuntu(windows中的wsl)
 - Version [ nacos-server 2.0.3，2.0.4 ]
 - JDK8
![image](https://user-images.githubusercontent.com/10190358/161073991-756ab1ab-1618-4ba5-84fe-12c617b356be.png)

**Comment by myifeng** [comment]
检查一下有没有初始化数据库？

**Comment by hnxyhcz** [comment]
> 检查一下有没有初始化数据库？

你说的初始化数据库是有没有提供的nacos的表导入道库里吗？我这是导入过的，也是可以启动起来的， 就是每次重启电脑后，重新打开虚拟机，启动mysql，再启动nacos就启动不起来，但是启动mysql后，用数据库连接工具连接下，就能启动起来

**Comment by KomachiSion** [comment]
我的环境复现不了这个问题，从描述上看也不是nacos的问题，应该是你环境所部属的mysql有问题。

nacos使用的是纯粹的jdbc进行连接，出现这个错误肯定是jdbc连数据库出错才会有。还是建议自查下环境。

**Comment by XIJINIAN** [comment]
你找到是什么问题了吗？我有一摸一样的问题，非常诡异。系统为：macos Monterey 12.5.1 Apple M1 Max。Docker 用的是 cluster-hostname.yaml，其中 Nacos image 为 nacos/nacos-server:v2.1.1-slim，MySQL image 为 mysql:8.0.30（因为自带的 MySQL 跑不起来）

**Comment by domecc** [comment]
这边也是同样的问题，请问up解决了吗？

**Comment by zhoujin7** [comment]
是数据库出问题了, 重新用sql脚本初始化一下数据库

**Comment by cdpsai** [comment]
> 
![image](https://user-images.githubusercontent.com/16955674/202656934-8b3c8c01-e500-4c96-994c-186bb43b2751.png)
配置加入 allowPublicKeyRetrieval=true 即可解决该问题

**Comment by even0306** [comment]
挖个坟问下，解决了吗，怎么解决的
