### ISSUE TITLE
Nacos2.0.3在集群k8s环境部署每隔一段时间集群服务会报错

### ISSUE THREAD

**Issue by maozuoyun** [alibaba/nacos#8060]
各位nacos的技术人员，你们好！
我们企业使用的是nacos2.0.3，部署在k8s上面做集群（三台），使用nfs做为文件存储，目前线上使用过程中，发现集群环境每隔一段时间会无法连接，状态异常，服务不可用。以下是具体的nacos.log中打印的日志，麻烦看一下是什么问题？
在第二台nacos-2.nacos-headless.nacos.svc.cluster.local上面的nacos.log：

2022-03-31 16:19:46,890 ERROR [Cluster-nacos-1.nacos-headless.nacos.svc.cluster..
local:8848]Send request fail, request=DistroDataRequest{headers={}, requestId='nn
ull'}, retryTimes=0,errorMessage=Client not connected.

2022-03-31 16:20:07,819 INFO [Cluster-nacos-0.nacos-headless.nacos.svc.cluster.ll
ocal:8848] try to re connect to a new server ,server is  not appointed,will chooo
se a random server.

2022-03-31 16:19:58,504 ERROR Server check fail, please check server nacos-1.nacc
os-headless.nacos.svc.cluster.local ,port 9849 is available , error ={}

java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 121621 nann
oseconds delay) for io.grpc.stub.ClientCalls$GrpcFuture@299474d4[status=PENDING,,
 info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDess
criptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=falsee
, sampledToLocalTracing=true, requestMarshaller=io.grpc.protobuf.lite.ProtoLiteUU
tils$MessageMarshaller@45487272, responseMarshaller=io.grpc.protobuf.lite.ProtoLL
iteUtils$MessageMarshaller@4177fe03, schemaDescriptor=com.alibaba.nacos.api.grpcc
.auto.RequestGrpc$RequestMethodDescriptorSupplier@4757849}}}}}]]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.jj
ava:508)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(Grr
pcClient.java:146)

**Comment by KomachiSion** [comment]
Your network may has some problem, nacos server will send request to other servers to sync data. From your error, It seems that the connection between severs has disconnect. So I think you should check your networks in your env.

**Comment by KomachiSion** [comment]
No more response from author
