### ISSUE TITLE
官网打不开了?

### ISSUE THREAD

**Issue by lun3322** [alibaba/nacos#8061]

**Comment by lun3322** [comment]
![image](https://user-images.githubusercontent.com/3439751/161176561-bae618db-6f68-4732-bbc7-036f3941c404.png)

**Comment by onewe** [comment]
我这边可以正常打开,请检查网络环境是否有问题

**Comment by lun3322** [comment]
> 

我打开其他网站都正常

**Comment by li-xiao-shuang** [comment]
官网正常
