### ISSUE TITLE
 c.a.n.s.c.e.AnnotationNacosPropertySourceBuilder - [doBuild,188] - There is no content for NacosPropertySource from dataId

### ISSUE THREAD

**Issue by jetwu** [alibaba/nacos#8066]
连接本地环境正常，连接远程Nacos时启动  c.a.n.s.c.e.AnnotationNacosPropertySourceBuilder - [doBuild,188] - There is no content for NacosPropertySource from dataId

nascos server 版本 2.0.3/2.0.4

客户端 nacos-config-spring-boot-starter  0.2.10

核对了dataId   namespace 都是正确的。

nacos:
  config:
    bootstrap:
      enable: true
      log-enable: true
    server-addr: ip:port
    namespace: xxx_dev
    username: xxx
    password: xxx
    group: xxx_common
    type: yaml
    auto-refresh: true
    max-retry: 10
    config-retry-time: 2333
    config-long-poll-timeout: 46000
    data-ids: application-druid,application-redis
    remote-first: true

帮忙分析下原因

**Comment by li-xiao-shuang** [comment]
> 

你的namespace是创建命名空间时生成的id嘛

**Comment by jetwu** [comment]
> > 
> 
> 你的namespace是创建命名空间时生成的id嘛

在本地开发环境使用的是命名空间名称，但可正常读取，本地Nacos服务是windows版。 现已把命名空间修改为Id，连接远程nacos服务正常了。 感谢感谢

**Comment by amosnothing** [comment]
> > > 
> > 
> > 
> > 你的namespace是创建命名空间时生成的id嘛
> 
> 在本地开发环境使用的是命名空间名称，但可正常读取，本地Nacos服务是windows版。 现已把命名空间修改为Id，连接远程nacos服务正常了。 感谢感谢

遇到同样的问题，想问下这个 id 在哪里获取的。

**Comment by zhoucheng45** [comment]
遇到同样的问题。namespace是创建命名空间自动生成的id，也不行。

**Comment by MichaelScofieldAndSara** [comment]
我也遇到了同样问题, 用的是
 <dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.12</version>
</dependency>

nacos server 版本 NACOS2.3.2
搞了半天都没找到原因,debug 发现源码里合并properties配置文件的时候没有用我的配置(也不知道为啥), 最后使用启动时候加命令行参数解决!
--nacos.config.server-addr=xx.xx.xx.xx:8848

**Comment by MichaelScofieldAndSara** [comment]
我也遇到了同样问题, 用的是
 <dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.12</version>
</dependency>

nacos server 版本 NACOS2.3.2
搞了半天都没找到原因,debug 发现源码里合并properties配置文件的时候没有用我的配置(也不知道为啥), 最后使用启动时候加命令行参数解决!
--nacos.config.server-addr=xx.xx.xx.xx:8848
