### ISSUE TITLE
nacos 2.0.3控制台 配置列表  输入dataId 点击查询条件以后 切换namespace  条件不生效

### ISSUE THREAD

**Issue by niezhiliang** [alibaba/nacos#8067]
携带Data ID查询条件切换namespace时，Data ID条件不生效
![image](https://user-images.githubusercontent.com/33079130/161200980-7ca0405a-8938-4651-8de7-0767d3a5fcc5.png)
![image](https://user-images.githubusercontent.com/33079130/161201152-5e23f150-5a8d-4494-95a5-dde45365ea14.png)

**Comment by li-xiao-shuang** [comment]
这个可能是控制台的问题  切换后刷新一下还有嘛

**Comment by niezhiliang** [comment]
> 这个可能是控制台的问题 切换后刷新一下还有嘛

切换后刷新Data ID 值就没有了  个人觉得切换namespace条件也应该带过来  这里应该是前端的一个bug

**Comment by drgnchan** [comment]
你是什么版本呢？我用最新版本看，切换namespace的时候会清空dataId查询条件。

**Comment by niezhiliang** [comment]
> commented

2.0.3版本

**Comment by niezhiliang** [comment]
> 你是什么版本呢？我用最新版本看，切换namespace的时候会清空dataId查询条件。

2.0.3

**Comment by drgnchan** [comment]
> > 你是什么版本呢？我用最新版本看，切换namespace的时候会清空dataId查询条件。
> 
> 2.0.3

#6625 这个问题在新版本有被修复。

**Comment by francisberr** [comment]
Good Project

**Comment by KomachiSion** [comment]
Try 2.0.4 or 2.1.0-BETA？
