### ISSUE TITLE
Nacos 2.0.4版本通过权限控制设置只读属性后无效

### ISSUE THREAD

**Issue by cocke** [alibaba/nacos#8068]
Nacos 2.0.4版本，在权限控制菜单中增加了用户、角色后，在 "权限管理" 里增加了对某个命名空间 "动作" 为 "只读(r)" 的角色名有，用新增加的用户登录后，仍然可以删除对应的命名明见，且可以对命名空间的配置项进行修改和发布。

**Comment by li-xiao-shuang** [comment]
> Nacos 2.0.4版本，在权限控制菜单中增加了用户、角色后，在 "权限管理" 里增加了对某个命名空间 "动作" 为 "只读(r)" 的角色名有，用新增加的用户登录后，仍然可以删除对应的命名明见，且可以对命名空间的配置项进行修改和发布。

1. 创建新用户
2. 绑定用户和角色
3. 添加权限，绑定角色、资源、权限
按照这个操作试试

**Comment by cocke** [comment]
> > Nacos 2.0.4版本，在权限控制菜单中增加了用户、角色后，在 "权限管理" 里增加了对某个命名空间 "动作" 为 "只读(r)" 的角色名有，用新增加的用户登录后，仍然可以删除对应的命名明见，且可以对命名空间的配置项进行修改和发布。
> 
> 1. 创建新用户
> 2. 绑定用户和角色
> 3. 添加权限，绑定角色、资源、权限
>    按照这个操作试试

是按这个步骤进行的操作，操作后用新创建的用户登录，仍然可以对限制为只读的命名空间的配置项进行修改和发布，且可以删除对应的命名空间。

**Comment by drgnchan** [comment]
nacos.core.auth.enabled 请确认下这个开关是否为true

**Comment by cocke** [comment]
> nacos.core.auth.enabled 请确认下这个开关是否为true
将nacos.core.auth.enabled置为true，并重启nacos服务后，只读权限生效了，谢谢。 @drgnchan
