### ISSUE TITLE
nacos的服务发现怎么实现对ribbon的负载策略进行动态更新

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#8073]
使用nacos作为配置中心和服务注册与发现，通过nacos配置中心来控制服务发现时客户端的ribbon负载策略的动态更新

**Comment by MajorHe1** [comment]
如果是nacos 2.x的版本，客户端都是跟集群内某一个节点保持长连接，有问题再切换；
如果是nacos 1.x的版本，如果有这个需要建议自己在nacos-client的基础上二次开发，原生nacos-client的服务发现模块不应该耦合对配置中心的操作。

**Comment by Layfolk-zcy** [comment]
> 如果是nacos 2.x的版本，客户端都是跟集群内某一个节点保持长连接，有问题再切换； 如果是nacos 1.x的版本，如果有这个需要建议自己在nacos-client的基础上二次开发，原生nacos-client的服务发现模块不应该耦合对配置中心的操作。

这个和客户端的长连接有关系？（因为nacso这边的服务发现什么的都不太懂,只会大致使用）需要进行动态负载策略的客户端读取到nacos配置中心的负载标识改变后根据负载标识对应的负载策略来决定访问集群的服务提供者。具体使用的nacos是nacos2.x

**Comment by MajorHe1** [comment]
nacos 2.x 的版本，客户端先随机选择一台服务端，然后跟它建立长连接，之后的服务注册和发现都使用该连接跟服务端进行通信。
我理解你的需求应该是客户端在选择服务端的时候，根据自定义的策略进行选择。这需要你自己定制客户端进行二次开发。

naming模块对应的选择服务端相关的代码在这里，你需要重写这个类及依赖这个类的代码，相当于把这个类之上到接口层的代码都重写一遍。
![image](https://user-images.githubusercontent.com/53824889/161378018-718f094b-3959-4ef3-a8ea-3b396bc362ec.png)

**Comment by Layfolk-zcy** [comment]
> nacos 2.x 的版本，客户端先随机选择一台服务端，然后跟它建立长连接，之后的服务注册和发现都使用该连接跟服务端进行通信。 我理解你的需求应该是客户端在选择服务端的时候，根据自定义的策略进行选择。这需要你自己定制客户端进行二次开发。
> 
> naming模块对应的选择服务端相关的代码在这里，你需要重写这个类及依赖这个类的代码，相当于把这个类之上到接口层的代码都重写一遍。 ![image](https://user-images.githubusercontent.com/53824889/161378018-718f094b-3959-4ef3-a8ea-3b396bc362ec.png)

感谢  但是这个对这个类进行重写的需不需要我也不确定我也是刚刚需只是业务上需要这个场景 哎就叫我去研究下  自定义其他的负载策略到时不要  主要时要如何对这个类进行重写和可以让其动态的改变客户端的负载策略这个问题头疼  看源码也看不太懂头疼哎

**Comment by KomachiSion** [comment]
简单点就实现一个spring bean，来监听ribbon的策略配置，发生变更了就更新ribbon bean的配置。

**Comment by Layfolk-zcy** [comment]
> 简单点就实现一个spring bean，来监听ribbon的策略配置，发生变更了就更新ribbon bean的配置。

大佬能不能给具体一点的思路？

**Comment by KomachiSion** [comment]
> > 简单点就实现一个spring bean，来监听ribbon的策略配置，发生变更了就更新ribbon bean的配置。
> 
> 大佬能不能给具体一点的思路？

这就是具体思路啊， 再具体就是代码实现了

**Comment by Layfolk-zcy** [comment]
> > > 简单点就实现一个spring bean，来监听ribbon的策略配置，发生变更了就更新ribbon bean的配置。
> > 
> > 
> > 大佬能不能给具体一点的思路？
> 
> 这就是具体思路啊， 再具体就是代码实现了

唉 难受
