### ISSUE TITLE
配置修改错误后即使更正也必须重启服务才能生效

### ISSUE THREAD

**Issue by wendell-dev** [alibaba/nacos#8076]
**Describe the bug**
配置修改错误后，控制台报错，再次修改正确依然报错，需要重启才能生效

**Expected behavior**
配置修改错误后，再次修改为正确配置，不用重启即可生效

**How to Reproduce**
1. 开启了配置动态刷新
2. 配置一个正常的配置项，这时程序正常运行
3. 更新配置，设置为一个**错误的**配置项值，如boolean型的设置为其它值（这时候会报错BindException: Failed to bind properties under 'xxxx' to boolean）
4. 更新配置，将上一步错误的配置值**修改为正确值**（预期是能够成功应用正确的配置，但结果还是上一步的报错信息），必须要重启应用才能恢复正常，即如果中途修改为了错误的配置即使又改正确，也必须要重启应用才能恢复

**Desktop (please complete the following information):**
nacos-server 1.1.4, nacos-client 1.1.4

_Originally posted by @wendell-dev in https://github.com/alibaba/nacos/issues/3979#issuecomment-1015099582_

**Comment by MajorHe1** [comment]
1.1.4的版本太低了，建议升级一下版本再试试吧？

**Comment by KomachiSion** [comment]
No more response from author.
