### ISSUE TITLE
Error when adding configuration

### ISSUE THREAD

**Issue by TomHuangYiDa** [alibaba/nacos#8079]
**Describe the bug**
When adding a new configuration, the interface reports: "Failed to publish, please check whether the parameters are correct", the log shows: "java.lang.NullPointerException: null", located in "at com.alibaba.nacos.config.server.service.repository.extrnal .ExternalStoragePersistServiceImpl.lambda$updateConfigInfo$1(ExternalStoragePersistServiceImpl.java:235)"

**Expected behavior**
Hope to add normal configuration

**Desktop (please complete the following information):**
 - OS: Centos
 - Version: nacos-server 2.0.3
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
![image](https://user-images.githubusercontent.com/44703208/161416082-4dbdd877-53e0-43de-af05-a8649e3859ff.png)
![image](https://user-images.githubusercontent.com/44703208/161416176-cca30d47-f2f3-4e1e-bf0e-310856982317.png)
![image](https://user-images.githubusercontent.com/44703208/161416200-f70713ca-a72f-47c8-ad58-0071ace11b96.png)

**Comment by KomachiSion** [comment]
Can you test 2.1.0-Beta?

**Comment by zl4j** [comment]
与“encrypted_data_key”字段非空有关系，源码里面insert并没有对这个字段传值，所以报错了，导致走了update的方法，update未取到配置信息，直接getAppName了

**Comment by TomHuangYiDa** [comment]
出现这个问题的原因是,我的MySQL数据库是通过Docker安装的,版本是8.0.28;后来我用官方的rmp安装后,就没出现这个问题了;
