### ISSUE TITLE
Configuring automatic refresh (autoRefreshed = true) is invalid

### ISSUE THREAD

**Issue by SnailDHC** [alibaba/nacos#808]
在springMvc项目中引入nacos作为配置中心，在字段上添加注解
`@NacosValue(value = "${a:1}", autoRefreshed = true)`
添加监听器对此配置项进行监听，当控制台相关值变更之后，能够接收到nacos推送过来的信息，但是打印出a的值并没有改变，还是原值，请问是什么原因

**Comment by xuechaos** [comment]
@SnailDHC 嗯 请提供一下版本信息，包括客户端和server端，最好有部分日志。

**Comment by SnailDHC** [comment]
nacos-client版本：0.8.0
nacos-server版本：0.8.0
nacos-spring-context版本：0.2.2-RC1
sping版本：4.3.5.RELEASE
控制台没有打印日志信息

**Comment by SnailDHC** [comment]
@xuechaos 
nacos-client版本：0.8.0
nacos-server版本：0.8.0
nacos-spring-context版本：0.2.2-RC1
sping版本：4.3.5.RELEASE
控制台没有打印日志信息

**Comment by shihaor** [comment]
我也遇到了同样的问题，有解决方法了吗？@SnailDHC

**Comment by jungleyoung** [comment]
我也遇到了同样的问题，有解决方法了吗？ @SnailDHC
