### ISSUE TITLE
nacos启动cpu直接爆满

### ISSUE THREAD

**Issue by nuo010** [alibaba/nacos#8081]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
启动画面
![](https://qiniu.elel.fun/20220405183108.png)

瞬间占用31%
![](https://qiniu.elel.fun/20220405183141.png)

![](https://qiniu.elel.fun/20220405183206.png)

![](https://qiniu.elel.fun/20220405183219.png)
启动后立即查询 一共查询了3次 第三次cpu已经爆满了,卡死了

![](https://qiniu.elel.fun/20220405183324.png)
x86_64的系统,不知道为什么,在另一台机器上没有该问题,也是用docker启动
.....这该怎么办

**Comment by onewe** [comment]
能提供一下复现的步骤 以及具体的版本信息吗？

**Comment by nuo010** [comment]
![](https://qiniu.elel.fun/20220406093518.png)
你看看镜像版本吧   具体步上边不是说了吗  就是 正常启动

**Comment by onewe** [comment]
有多大的数据量？

**Comment by nuo010** [comment]
目前没有数据量  一启动 直接就满了

**Comment by KomachiSion** [comment]
我无法复现你的问题，能否拿arthas或者其他工具，打一下火焰图或者看一下是哪个线程暂用了cpu？

**Comment by MajorHe1** [comment]
这个进程所在目录的logs文件夹下有多少条日志文件？日志文件数目过多，logback会造成高cpu。

**Comment by KomachiSion** [comment]
No more response from author and current information is not enough.

**Comment by ldkkkkk** [comment]
我发现是数据库连接池里的连接失效造成的，日志里会有错误，出现错误cpu就100%
