### ISSUE TITLE
获取namespace的是不是需要应该根据用户的token获取？

### ISSUE THREAD

**Issue by Chaos-coder** [alibaba/nacos#8086]
获取用户对应的ns的api ：http://${nacos_server}:8848/nacos/v1/console/namespaces,直接不需要通过鉴权就能拿到我当前nacos集群所有的ns信息和我ns对应的所有的配置文件数量，这个是有安全隐患的？

Get the API of the NS corresponding to the user: http: / / ${nacos_server}: 8848 / Nacos / V1 / console / namespaces. You can directly get all the NS information of my current Nacos cluster and the number of configuration files corresponding to my ns without authentication. Is this a security risk?

**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
No risk I think.

only namespace info and the number of config is no useful.

**Comment by yanickxia** [comment]
seems useless, but beyond authority.
