### ISSUE TITLE
Nacos Admin Console UI display problem

### ISSUE THREAD

**Issue by mghio** [alibaba/nacos#8087]
**Describe the bug**
<img width="1610" alt="nacos-ui-bug" src="https://user-images.githubusercontent.com/43461943/161971544-f030080b-736f-4af4-8373-86b1908a8f54.png">

**Expected behavior**
Text does not exceed the box.

**Acutally behavior**
Text out of box.

**How to Reproduce**
1. Go to [official quick-start](https://nacos.io/en-us/docs/quick-start.html)
2. Visit Admin Console: http://ip:8848/nacos/index.html
3. Select 「ConfigManagement」 -> 「Configurations」 -> 「Export」

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: nacos-server 2.1.0-BETA, nacos-client 2.1.0-BETA

**Additional context**
 - Browser Version： Google Chrome Version 99.0.4844.84 (Official Build) (x86_64)

**Comment by onewe** [comment]
@onewe will resolve it@
