### ISSUE TITLE
[Optimize] Use the ExecutorFactory.Managed to create thread pools

### ISSUE THREAD

**Issue by onewe** [alibaba/nacos#8092]
When I'm reading the nacos source code, I find that some thread pools aren't created by `ExecutorFactory.Managed`. so I think that it can be optimized.
我在阅读 nacos 源码时,我发现一些线程池不是由`ExecutorFactory.Managed`创建的,所以我觉得这个可以优化一下,方便统一管理线程池

For examples:
`WatchFileCenter`:
![image](https://user-images.githubusercontent.com/38708836/162145549-1b6a7366-4d27-4438-9997-6f731c5827bb.png)

`CredentialWatcher`:
![image](https://user-images.githubusercontent.com/38708836/162145760-6c75635e-9174-4ac4-a154-8ab84d2f27e0.png)

Some thread pools aren't even closed.
有些线程池甚至都没有关闭
![image](https://user-images.githubusercontent.com/38708836/162146200-92ce0f1b-447e-46c7-8f3d-be905964dbb1.png)

**Comment by KomachiSion** [comment]
不是说有线程池都需要交由`ExecutorFactory`管理。 我看截图都是使用的`ExecutorFactory`创建，然后自行管理。其实没什么大问题。

线程池关闭的问题，如果有shutdown/close之类的method，可以在里面关闭一下。

**Comment by onewe** [comment]
Ok, 那我提个关闭的PR @KomachiSion
