### ISSUE TITLE
The official Documentation issue

### ISSUE THREAD

**Issue by Oliverwqcwrw** [alibaba/nacos#8101]
**Describe the bug**

In `Nacos Spring Boot # Enable Service Discovery` tab

> Call [Nacos Open API](https://nacos.io/zh-cn/docs/open-api.html) to register a service called example to the Nacos server.

`curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=example&ip=127.0.0.1&port=8080'`

Running the command prompts that the service cannot be found

**Expected behavior**

Change the PUT request to a POST request

**Comment by MajorHe1** [comment]
https://github.com/nacos-group/nacos-group.github.io

**Comment by Oliverwqcwrw** [comment]
@I will solve it@
