### ISSUE TITLE
nacos2.0.4 开启鉴权后 所有账号更改密码报错

### ISSUE THREAD

**Issue by Master-Jack** [alibaba/nacos#8107]
![image](https://user-images.githubusercontent.com/50773190/162403664-19aa4401-ad48-4a40-81d2-ac65b332165b.png)

**Comment by Master-Jack** [comment]
2.0.3的版本 revision 为啥是 2.1.0-SNAPSHOT

**Comment by Master-Jack** [comment]
2.0.3的版本 revision 为啥是 2.1.0-SNAPSHOT

**Comment by onewe** [comment]
如何复现这个问题呢? 是先创建用户紧接着修改密码吗？

**Comment by Master-Jack** [comment]
复现步骤：把2.0.4的拉下来开启鉴权：nacos.core.auth.system.type=nacos 运行。
修改密码就会报错，不管是那个账号。
这个是UserController #updateUser方法获取requestattribute 的 nacosuser值为空导致。还没return，继续往下执行。结果就是报错，密码也改了。

**Comment by onewe** [comment]
@i will resolve it@

**Comment by onewe** [comment]
方案一:
当后端返回401时,前端跳转到首页重新登录

方案二:
当后端解析token成功时,把`NacosUser`对象放入session

**Comment by onewe** [comment]
@dixonqin 重新登录也不行??

**Comment by dixonqin** [comment]
> @dixonqin 你的这问题 还有点不一样, 能提供复现的步骤吗？？

我现在也蒙，复现不了，但是我拆分了改密码接口从jwt拿信息，目前没有遇到了

**Comment by dixonqin** [comment]
> @dixonqin 你的这问题 还有点不一样, 能提供复现的步骤吗？？

我现在也懵，不知道咋复现，这两天试着重新上线了好几次也没遇到这个问题；目前是保险起见把修改密码接口拆分了，global admin用一个，修改自己密码用一个，这样就不需要判断is global admin这个字段了，信息都直接从jwt取，跳过了获取attribute的步骤

**Comment by dixonqin** [comment]
> @dixonqin 你的这问题 还有点不一样, 能提供复现的步骤吗？？

我这边是在2.0.x基础上做了一定的魔改，新增了一套oidc流的auth，跟nacos user做了个映射，为了兼容升级，原始的nacos user的整个体系没做修改，相当于就是通过了oidc就直接在后台开个新nacos账号或者登陆同名账号，前段时间升级了2.0.4突然出现的这个问题。

但是我看2.1.0好像改动挺大的，支持spi了，这个其实影响也不大。

**Comment by KeithTt** [comment]
把镜像版本从 2.0.3 升级到 2.1.0，发现只有默认账号 nacos 能使用，其它的账号均不能登陆。

于是尝试修改密码，但是只要更新密码点击确认按钮就会退出到登陆页。

然后尝试创建新账号，能创建，但是依然无法登陆。

最后只能回滚到2.0.3，可怕的是，回滚之后普通账号依然登陆不了...

另外还发现个问题就是，只要点击没有权限的标签，也会自动退出登陆跳转到登录页。

---

后来发现问题是，默认登陆之后会访问 public 空间，但是普通账号没有 public 权限，然而访问没权限的资源会自动退出到登录页，所以导致无法登陆，然后给账号绑定了 public 空间的权限之后就能正常登陆了。

前端首页能不能弄成一个不需要权限的公共页面，以及，页面中间主体顶部标签栏能不能过滤一下只显示有权限的空间？？？
