### ISSUE TITLE
Grpc support?

### ISSUE THREAD

**Issue by Carl-Xiao** [alibaba/nacos#812]
敢问一下~什么时候才有文档?

**Comment by xuechaos** [comment]
@Carl-Xiao GRPC 这块目前还没整合，可以多说一下具体需求场景。

**Comment by Carl-Xiao** [comment]
我本身是用SpringCloud的，仅仅出于自己的平时研究grpc东西提出的疑问。

**Comment by iamsxm** [comment]
> @Carl-Xiao GRPC 这块目前还没整合，可以多说一下具体需求场景。

我们之前分api,service层。不同工程引用api层，不同服务地址手动配置到zookeeper上，通过apiclient采用http协议调用。
现在想改为grpc进行调用，但是需要在消费端手动配置ip，端口，并且支持集群。需要自己建立个服务注册中心，启动时自动注册@gRpcServive。消费者从注册中心拉取服务列表。
我想问nacos目前支持自动注册gPrc服务吗，支持这种场景吗😀

**Comment by nkorange** [comment]
Will be supported in #1097
