### ISSUE TITLE
nacos.core.auth.enabled开启后程序启动提示403，但是通过curl可以获取配置

### ISSUE THREAD

**Issue by changs0115** [alibaba/nacos#8124]
应用配置如下
![图片](https://user-images.githubusercontent.com/39237753/162698241-b6cecea1-f6a9-4e58-a595-4d15116fc0ec.png)
启动后提示：dataId=njry-cloud-auth-dev.yml, group=NJRY_FRAMEWORK, tenant=, code=Response{resultCode=500, errorCode=403, message='unknown user!', requestId='null'}
2022-04-11 16:27:54.397 [main] ERROR c.a.cloud.nacos.client.NacosPropertySourceBuilder:101 - get data from Nacos error,dataId:njry-cloud-auth-dev.yml 
com.alibaba.nacos.api.exception.NacosException: http error, code=403,dataId=njry-cloud-auth-dev.yml,group=NJRY_FRAMEWORK,tenant=
通过浏览器访问http://[127.0.0.1:8848/nacos/v1/cs/configs?dataId=njry-cloud-auth-dev.yml&group=NJRY_FRAMEWORK&tenant=&username=user&password=user@123](http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=njry-cloud-auth-dev.yml&group=NJRY_FRAMEWORK&tenant=&username=user&password=user@123)可以正常获取配置
![图片](https://user-images.githubusercontent.com/39237753/162698577-ed875cc9-b861-458e-ae32-15aac00893d4.png)

**Comment by KomachiSion** [comment]
It might be spring's design, in spring, the special word `@` in yaml may have some special handle. Can you use original nacos-client to try again?

**Comment by zhouhai22** [comment]
check the version of spring-cloud-starter-alibaba-nacos-config, at least 2.2.2 support auth feature.

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
