### ISSUE TITLE
ADA sent from Nami wallet to a wrong network address

### ISSUE THREAD

**Issue by Shawnyklass** [alibaba/nacos#8126]
Hello, is hard to  get any support team from Nami. I mistakenly sent 250 ADA from my Nami wallet to the wrong network address on my Crypto.com account. I sent it to a Cronos address instead of a Cardano one. I have tried to reach Crypto but no resolution yet. I am desperate and wondering if there is anything Nami can do, like some process steps to recover the funds?

I am just confused and browsing the net looking for a resolution on this. I stubbled into your Telegraph chat group and an admin there asked for my Nami address. I am just worried to share anything due to scammers. Please any help would be appreciated.

**Comment by KomachiSion** [comment]
Not nacos' problem
