### ISSUE TITLE
nacos config group not work

### ISSUE THREAD

**Issue by DemonJun** [alibaba/nacos#813]
environment:
  nacos: 0.8.0( cluster mode in docker swarm)
  spring-cloud-alibaba：0.2.1.release
  nacos-client：0.8.1
  spring-boot：2.1.2.release
  spring-cloud：Greenwich.RELEASE
  jdk：11
problem：
  When I use configuration ‘group’, the client cannot get the configuration and the configuration does not exist, but it work with 'group' in 'DEFAULT_GROUP'.
 It also does not take effect when the service line and service weights are set in the nacos console. When viewing nacos's naming.log, no information about the push weight change is found.

**Comment by yeshoujquery** [comment]
bootstrap 配置一下就可以了

**Comment by DemonJun** [comment]
> bootstrap 配置一下就可以了

配置了 但是找不到
