### ISSUE TITLE
[Optimize] Exclude LdapAutoConfiguration

### ISSUE THREAD

**Issue by onewe** [alibaba/nacos#8136]
When nacos-server start, it have an error. it's a ldap configuration error. nacos-server ldap plugin doesn't need to auto configuration, so it's need to exclued.
因为 spring boot 自动配置的原因,nacos启动的时候会报错,而 nacos ldap 插件是不需要自动配置的,所以需要排除`LdapAutoConfiguration`
![image](https://user-images.githubusercontent.com/38708836/163117278-f7ea650d-0384-479e-a3a1-797bafdf8fa4.png)

**Comment by shalk** [comment]
if the ldap have been configured , Will exclude autoconfiguration occur some problem  ?

**Comment by onewe** [comment]
在没有配置ldap的情况下启动会报错,因为自动配置的原因.
在配置ldap的情况下,不需要 spring 的自动配置,因为在 ldap 插件模块中已经写了一个ldap的配置.
