### ISSUE TITLE
网络忙期间一个follower节点的状态变成了DOWN，网络空闲之后节点状态没有自动恢复为UP

### ISSUE THREAD

**Issue by zrlw** [alibaba/nacos#8139]
### Describe the bug
这个issue先在jraft社区也提了: https://github.com/sofastack/sofa-jraft/issues/813
目前收到的反馈说jraft的日志信息没有问题，所以又提到了这里。

nacos集群5个节点基于jraft做选举，期间网络流量比较大，有一台follower节点的状态变成了Down，压测结束网络空闲后也没有恢复，查看那台follower的alipay-jraft日志，发现在不间断输出下列告警信息：
```
WARN [GRPC] failed to send response.

io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
  at io.grpc.Status.asRunTimeException(Status.java:524)
  at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:341)
  at com.alipay.sofa.jraft.rpc.impl.GrpcServer$1.sendResponse(GrpcServer.java:153)
...
```
查到最早出现上述告警信息的同一时间点，lead的raft日志里有一行告警信息：
```
WARN Fail to issue RPC to 那个当前状态为Down的follower地址和端口, consecutiveErrorTimes=10, error=Status[EINTERNAL<1004>: RPC exception:DEADLINE_EXCEEDED: deadline exceeded after 2.499972257s. [remote_addr=那个当前状态为Down的follower地址]]
```
后来leader的日志充斥着
```
WARN Fail to unlock with Replicator [state=Probe, stateInfo=<running=IDLE, firstLogIndex=14, lastLogIncluded=0, lastLogIndex=14, lastTermIncluded=0>, peerId=那台Down的follower节点地址和端口，type=Follower], the lock is held by Thread[JRaft-Rpc-Closure-Executor-x-5,main] and current thread is Thread[JRaft-Rpc-Closure-Executor-y-5,main].  
```
其中Thread名称中的x和y不同，且x和y持续变化，有时x位置的Thread名称还会变成null。

其他3个节点在挂掉的 follower 节点的alipay-jraft日志里开始出现```io.grpc.StatusRuntimeException: CANCELLED: call already cancelled```同一时点起，每隔30s左右都会收到这个DOWN状态的follower节点发送的PreVoteRequest请求，但因为leader的lease is still valid，所以这些请求一直被ignore。

**Desktop (please complete the following information):**
 - OS:  Centos7
 - Version nacos-server 1.4.2
 - Module naming
 - SDK [e.g. original

**Additional context**

**Comment by zrlw** [comment]
查了这台DOWN的follower的nacos-cluster日志，确定DOWN状态的原因是网络拥塞导致这个节点没有在nacos规定时限内向其他节点报告自己的状态所致。
但是不间断输出 CANCELLED: call already cancelled的原因还没有找到。

**Comment by zrlw** [comment]
jraft社区有人反馈说原因就是网络超时，但是网络空闲之后也没有恢复

**Comment by zrlw** [comment]
这个follower节点持续FullGC，做了dump分析
![nacos-fgc](https://user-images.githubusercontent.com/40652892/163496609-03bdfdd5-0fbe-4557-abcf-9df31805a709.jpg)
：

**Comment by zrlw** [comment]
初步怀疑是收到了海量的客户端心跳请求，InstanceController调用processClientBeat创建了海量的ClientBeatProcessor任务，由NAMING_HEALTH_EXECUTOR去执行，但是NAMING_HEALTH_EXECUTOR线程池的最大容量是Integer.MAX_VALUE，直接把内存耗尽了，由于可用内存不足，正在执行ClientBeatProcessor任务的线程挂住了，FGC也回收不了这些线程占用的内存。
因为jstack操作失败，无法确认nacos的线程执行情况，所以只能猜测是上述原因了。

**Comment by zrlw** [comment]
ClientBeatProcessor这个类应该有优化空间：
1.首先这个ClientBeatProcessor的run方法是否有必要在另外一个线程里执行有待商榷，只是修改一下instance的状态和发布事件，从效率看直接作为方法由InstanceController调用也没有问题。
2. ClientBeatProcessor的run方法调用getPushService().serviceChanged方法可以先将service放入集合，PushService启动守护线程定时（10ms或100ms）从集合取出，这样可以合并大量重复的service变动事件（同一服务有成百上千个instance）。

**Comment by zrlw** [comment]
补充一下：
今天出现了OOM自动转储的dump文件，消耗7.1G的7个com.alibaba.nacos.naming.health线程都是在执行Cluster.allIps方法，推测是执行该方法的new ArrayList时内存不足导致BLOCKED，FullGC无法有效释放内存导致持续FullGC。
jtack -F运行了几个小时终于得到了结果，除了少数几个线程是IN_NATIVE外，其余线程都是BLOCKED状态。

**Comment by zrlw** [comment]
#8171修订后，重新压测（模拟海量心跳请求）nacos各节点均未再出现FullGC，原1.4.2版本能稳定复现FullGC。

**Comment by KomachiSion** [comment]
So , you want use double memory to create the index for quick search instance by ip and port, so that remove the tmp memory?

But I remember there are the max of client processor thread, Why your client processor will get all  memory and make FullGC?

**Comment by zrlw** [comment]
1. 你记错了，nacos原生的线程池除了少数几个外都是无界线程池，压力超出nacos承载时线程数会持续增长，后果就是jvm内存耗尽、绝大多数线程BLOCKED。
2. ClientBeatProcessor这个执行效率单独放在另外一个线程池执行，上下文切换的代价对于我们而言比较高，为了承载了尽可能多的临时实例心跳请求，我们调大了tomcat的maxThreads，http-nio线程数量已经是cpu核数的10倍以上，测试对比结果显示ClientBeatProcessor的run方法放到http-nio执行效率更高。
3. ClientBeatProcessor的run方法执行效率低，复制、遍历service的全部实例去匹配一个ip和port，只是为了修改一下实例的心跳时间戳和健康状态，我们每个service的instance多，对于我们而言，直接按key值取结果要快1个数量级。
上述修订只是我们的部分优化 ，实际上我们是每个接收节点直接返回临时实例的心跳请求，然后定期转发到责任节点，通过这些修订之后，我们实现了依靠节点横向扩展、支持临时实例数量线性增长的目的。
nacos原版本在扩到5节点之后就遇到了天花板，横向扩展节点也支撑不了更多的实例。

**Comment by zrlw** [comment]
我们的修订是double reference,  测试对比结果显示内存的新增消耗有限，updateIps的执行效率和之前也没有明显差异。

**Comment by KomachiSion** [comment]
>你记错了，nacos原生的线程池除了少数几个外都是无界（MaxSize=Integer.MAX_VALUE）线程池，压力超出nacos承载时线程数会持续增长，后果就是jvm内存耗尽、绝大多数线程BLOCKED。

所以内存占用不是复制set占用的而是task缓存在线程池队列里？

>ClientBeatProcessor这个执行效率单独放在另外一个线程池执行，上下文切换的代价对于我们而言比较高，为了承载了尽可能多的临时实例心跳请求，我们调大了tomcat的maxThreads，http-nio线程数量已经是cpu核数的10倍以上，测试对比结果显示ClientBeatProcessor的run方法放到http-nio执行效率更高。

这里放在单独线程池运行是希望不要阻塞io线程，毕竟io线程需要处理的不一定是心跳。心跳的线程池应该在某个版本后已经可以通过配置设置，可以直接调大心跳线程池大小来提升心跳处理效率。

> ClientBeatProcessor的run方法执行效率低，复制、遍历service的全部实例去匹配一个ip和port，只是为了修改一下实例的心跳时间戳和健康状态，我们每个service的instance多，对于我们而言，直接按key值取结果要快1个数量级。

这里确实在service的instance多的时候有一定的效率损失，如果使用新增索引的方式，相当于又多了一层缓存数据，这部分缓存数据也需要确保一致性，担心会提升数据一致性压力。

**Comment by zrlw** [comment]
1.看看nacos（包括2.0最新的代码）ExecutorFactory的代码，即使newSingleScheduledExecutorService也是造了一个最大Integer.MAX_VALUE的池子，看一下java.util.concurrent.ScheduledThreadPoolExecutor的ScheduledThreadPoolExecutor(int corePoolSize, ThreadFactory threadFactory)构造方法吧。
2. ClientBeatProcessor的run方法优化之后执行时间是ns级别的，我们的实例多，相比上下文切换导致的线程阻塞，这点消耗我们可以承受。
3. Distro协议本身就做不到各个节点实时一致，能在时间允许范围内达到最终一致性即可。另外我们用的是dubbo服务，dubbo采用的tcp长连接方式本身就具备有效性检测机制，服务下线时客户端会先于注册中心得知，所以nacos通知实例删除时有延迟也无所谓，至于新增服务延迟几秒通知对我们而言也无所谓，每个服务的实例数都很多，延迟通知几个没有什么关系。

**Comment by KomachiSion** [comment]
那我觉得应该比较明确了：
1. 线程池优化和心跳处理线程数确实可以提一个通用pr，进行一定优化和设置。
2&3. 由于多一层索引就多需要维护一层数据，保持数据一致性的代价就增加了很多（不是延迟几秒的问题，可能导致彻底丢失），对于每个服务很多实例的场景，比如你们这种情况，少几个实例可能影响不大，但对于有些实例较少甚至单例的服务可能是无法接受的， 所以这个优化暂时先不合并到1.x-develop中，保留在你们的fork里。

**Comment by zrlw** [comment]
只是在全量更新时加了一个索引更新，增加的代码量不过十几行，总耗时也是ns级别，成熟的技术而已，比数据库的索引维护简单多了，我们不认为会有什么风险。
临时实例心跳每隔5秒就会重发，我们压测至今也没有因为这十几行新增代码丢了一个实例。

**Comment by KomachiSion** [comment]
1.x版本现在进入了维护阶段，主要以稳定和修复bug，新增的代码虽然只有20行，但是却对缓存机制做了修改，（从2层变成了3层）如果出现问题不好修复。

2.x版本其实对dubbo这种场景的优化程度是很高的，可以考虑使用2.x版本来解决性能问题。有更多更好的想法可以提到nacos2.x版本上。

**Comment by KomachiSion** [comment]
No more response from author for a long time.
