### ISSUE TITLE
nacos 1.4.3集群部署，服务下线后未自动上线

### ISSUE THREAD

**Issue by shineabel** [alibaba/nacos#8140]
nacos 1.4.3集群部署，注册到nacos上的某个服务下线后未自动上线，该怎么处理呢，不想重启

**Comment by Oliverwqcwrw** [comment]
Manual offline or automatic offline？

**Comment by shineabel** [comment]
> Manual offline or automatic offline？
自动下线的，可能是因为网络抖动的原因导致的，期望能自动恢复注册上线而不重启

**Comment by Oliverwqcwrw** [comment]
You can check the connection what nacos and service,It can online automatic normally when the service is online again

Sorry, I can't recurrence this issue,You can provide more information about this issue

**Comment by KomachiSion** [comment]
I can't get the key issue from your description, when your instance set offline, if you do not set it online, why nacos can auto online it?

**Comment by shineabel** [comment]
@KomachiSion 不是手工让服务下线的，可能是网络或者某个原因从nacos上掉线了，服务其实是工作着的，肯定需要自动恢复上线呀，不然这个服务实例不重启就没法使用了

**Comment by KomachiSion** [comment]
which version of nacos-client？

**Comment by shineabel** [comment]
@KomachiSion nacos-client 1.4.1, nacos-server是1.4.3

**Comment by KomachiSion** [comment]
1.4.1有bug，如果出现域名解析错误等问题，可能会导致心跳线程中断，不再续约，可以升级nacos-client版本到1.4.2再试试

**Comment by KomachiSion** [comment]
No more response from author.
