### ISSUE TITLE
nacos 2.0.4创建账号错误

### ISSUE THREAD

**Issue by Cyyking** [alibaba/nacos#8141]
Hi, 我想使用命令空间的权限管理。

当前遇到创建test1账号，页面上显示的是nacos,test1
![image](https://user-images.githubusercontent.com/16470319/163138477-ca5a9524-7ba6-472a-8e81-ece7945447d9.png)

并且页面登录也是需要使用nacos,test1登录才行。

权限管理也没有生效,没有权限限制
![image](https://user-images.githubusercontent.com/16470319/163139439-fe5878e1-0876-4d67-a145-ac1a8af1f696.png)

**Comment by onewe** [comment]
是从旧版本升级上来的吗？ 如果是的话请清空浏览器缓存,重试一下.

**Comment by Cyyking** [comment]
@onewe 是的，我是从低版本升级上去的。我按照你说的清除了缓存。现在显示添加账号都是正确的。谢谢
