### ISSUE TITLE
Publish failed. Make sure parameters are entered correctly.

### ISSUE THREAD

**Issue by Li-n6** [alibaba/nacos#8142]
## Issue Description
我在虚拟机里通过docker启动了nacos和mysql容器，通过nacos控制台登录进去没有问题，
我也成功添加了一个命名空间，但是在配置列表里新增的时候，发布失败。

Type: *bug report* or *feature request*

### Describe what you expected to happen
I run nacos 2.0.4 version by docker with mysql8.0.
I can log in Console and add namespace successfully.
but when i add Configuration list, report a error “Publish failed. Make sure parameters are entered correctly.”

### How to reproduce it (as minimally and precisely as possible)

1. I suspect it has something wrong with the database

### Tell us your environment
1. docker 20.10.14
2. nacos 2.0.4
3. mysql8.0

**Comment by li-xiao-shuang** [comment]
可以更新下docker 项目里面的sql脚本  新增了字段

**Comment by Li-n6** [comment]
tar.gz里面的nacos-mysql.sql执行了会报这个错，估计有缺失字段，用zip的这个文件执行后，就可以了，感谢楼上的兄弟

**Comment by Li-n6** [comment]
tar.gz里面的nacos-mysql.sql执行了会报这个错，估计有缺失字段，用zip的这个文件执行后，就可以了，感谢楼上的兄弟
