### ISSUE TITLE
serverlist maybe can't be refresh

### ISSUE THREAD

**Issue by liqipeng** [alibaba/nacos#8144]
**Describe the bug**
When initialize NamingService with endpoint, it will refresh serversFromEndpoint with a ScheduledExecutor.
And the other operation from other thread will read ```serversFromEndpoint ```.
But the ```serversFromEndpoint``` does not have a ```volatile``` modifier.
So maybe there is a concurrency visibility bug.

**fix**
```
// add volatile modifier
private volatile List<String> serversFromEndpoint
```

**Comment by Oliverwqcwrw** [comment]
I think so
