### ISSUE TITLE
nacos2 integrate with istio

### ISSUE THREAD

**Issue by q710245300** [alibaba/nacos#8151]
Is there any guidance for nacos2 integrate with istio1.9 using mcp-over-xds and how to config the springboot application in istio with nacos2 , I am very confused during the integration process, and don't kown how to find the solution.

**Comment by li-xiao-shuang** [comment]
See if https://github.com/nacos-group/nacos-istio  can help you

**Comment by q710245300** [comment]
> See if https://github.com/nacos-group/nacos-istio can help you

Thanks.But It's seem like early attempts when nacos not offically support istio. It's not what i'm expected. Currently Nacos 2 can integrate with istio1.9 using mcp-over-xds offically, But I cannot find the guidelines.

**Comment by li-xiao-shuang** [comment]
@realJackSun

**Comment by YunWZ** [comment]
nacos properties:
```properties
nacos.istio.mcp.server.enabled=true # to enable nacos mcp server
nacos.istio.mcp.server.port=18848 # mcp server port
nacos.istio.mcp.push.interval=3000 # 3000ms
nacos.istio.domain.suffix=nacos
```
and config istio, add configSource

**Comment by q710245300** [comment]
> nacos properties:
> 
> ```ini
> nacos.istio.mcp.server.enabled=true # to enable nacos mcp server
> nacos.istio.mcp.server.port=18848 # mcp server port
> nacos.istio.mcp.push.interval=3000 # 3000ms
> nacos.istio.domain.suffix=nacos
> ```
> 
> nacos support `mcp` and `mcp over xds` protocol.
> 
> and config istio, add configSource

Thanks. Do you kown subsequent configuration. If application need to config nacos sdk or envoy can auto send plain application to nacos throw mcp-over-xds.

**Comment by SpecialYang** [comment]
@q710245300 Please show the meshconfig and start up logs of istiod. Thanks.

**Comment by mark8s** [comment]
@q710245300 Hello, has your problem been solved? How to solve it?
