### ISSUE TITLE
nacos 1.4.3 面板 新建配置页面bug

### ISSUE THREAD

**Issue by lingyalong** [alibaba/nacos#8152]
**Describe the bug**
nacos面板新建配置页面 配置内容输入框长度异常 只有一条黑色的线并不是正常的输入框

**Expected behavior**
新建配置页面的 配置内容旁边应该是一个输入框 而不是一条黑线

**Acutally behavior**
我想要新建配置

**How to Reproduce**
1. 打开控制面板 使用默认账号登入
2. 在配置列表点击加号 进入新建配置页面
3. 看见异常

**Desktop (please complete the following information):**
 - OS: windows10
 - Version nacos-server 1.4.3
 - Module config
 - SDK spring-cloud-alibaba-nacos

**Additional context**
![image](https://user-images.githubusercontent.com/50581353/163300062-9c520551-a3be-4b75-aab1-3514b5ba01b4.png)

**Comment by lingyalong** [comment]
经过测试 是前端页面的高度给错了 只有5px 给多点显示就没问题

**Comment by li-xiao-shuang** [comment]
> 经过测试 是前端页面的高度给错了 只有5px 给多点显示就没问题

欢迎提pr处理下

**Comment by onewe** [comment]
@lingyalong 我在 mac平台 使用 chrome 和 Firefox 均没有复现你说的问题,请提供一下详细的复现步骤

**Comment by lingyalong** [comment]
> @lingyalong 我在 mac平台 使用 chrome 和 Firefox 均没有复现你说的问题,请提供一下详细的复现步骤

大概操作是 1. 从github下载1.4.3的包 在win10环境下使用命令行 startup.cmd -m standalone 运行nacos 第一次进去就触发了这个问题后面尝试刷新

**Comment by onewe** [comment]
试了一下,也没复现😂。 你之前运行过低版本的nacos吗？

**Comment by lingyalong** [comment]
> 试了一下,也没复现😂。 你之前运行过低版本的nacos吗？

运行过1.4.1

**Comment by onewe** [comment]
那多半是缓存的问题,在新的版本我增加了 hash-tag 应该可以解决这种问题

**Comment by KomachiSion** [comment]
清理一下浏览器缓存再重试呢？
