### ISSUE TITLE
多个Nacos时配置文件无法读取的BUG

### ISSUE THREAD

**Issue by cuisuqiang** [alibaba/nacos#8158]
## Issue Description
Nacos配置连接MySQL，则新建的配置文件会存到MySQL中。
假如有这样一种场景，数据库使用的是一样，但是Nacos是多个，那么当你从Nacos1添加配置后，在Nacos2的页面上可以看到，但是程序却无法读取到。
就是你在Nacos2可以看到这个配置文件了，但是启动程序，依然是：
Ignore the empty nacos configuration and get it based on dataId

### Describe what happened (or what feature you want)
这个问题是必然发生的，我希望两个Nacos既然已经数据同步，那么程序使用时也应该一致。目前该问题通过重启Nacos才能解决。

### How to reproduce it (as minimally and precisely as possible)
1. 两个已经启动好的Nacos，且使用的是一个MySQL
2. 在Nacos1上增加配置文件
3. 启动程序访问Nacos2，启动报错

**Comment by onewe** [comment]
手动调用 dump 接口通知 nacos2 数据库更新了数据

**Comment by onewe** [comment]
因为你通过nacos1增加的数据,nacos2是无法感知的. nacos的逻辑是优先使用本地的缓存数据,所以获取不到数据库中最新的数据.

**Comment by cuisuqiang** [comment]
既然页面可以看到，那就应该同步下来数据，否则太容易混淆。可见不可得，这是程序大忌。特别是这在集群环境下的话，将会非常不友好。

**Comment by onewe** [comment]
集群模式下是没有问题的,只要不是直接从数据库中干过去的,节点会互相通知数据有变化.

**Comment by cuisuqiang** [comment]
感谢回复，使用时注意这个问题

**Comment by onewe** [comment]
如果解决了您的问题,请关闭一下 issue

**Comment by onewe** [comment]
如果解决了您的问题,请关闭一下 issue
