### ISSUE TITLE
sh 直接启动 nacos 可以,但是吧nacos 服务通过systemctl 启动则提示 Please set the JAVA_HOME variable in your environment

### ISSUE THREAD

**Issue by yu5056561661** [alibaba/nacos#8159]
sh 直接启动 nacos 可以,但是吧nacos 服务通过systemctl 启动则提示 Please set the JAVA_HOME variable in your environment
OS :contes7  jdk1.8 x64   naco-service 2.0.3

**Comment by onewe** [comment]
service 中添加 Environment 属性,设置 JAVA_HOME 环境变量

**Comment by yu5056561661** [comment]
> service 中添加 Environment 属性,设置 JAVA_HOME 环境变量
哪个service  中添加呢？ 有例子嘛？

**Comment by yu5056561661** [comment]
@onewe 哪个service  中添加呢？ 有例子嘛？

**Comment by onewe** [comment]
https://www.cnblogs.com/operationhome/p/12463779.html
善用搜索引擎

**Comment by yu5056561661** [comment]
source /etc/profile 果然加上这个也可以，谢谢了 @

**Comment by onewe** [comment]
如果解决了您的问题,请关闭一下 issue
