### ISSUE TITLE
求助关于引入nacos 在公司特定环境下无法install的问题（Help for the problem that the introduction of nacos cannot be installed in the company's specific environment）

### ISSUE THREAD

**Issue by a350844866** [alibaba/nacos#8160]
## 求助，非BUG。

Type: *bug report* or *feature request*

### 在特定公司环境下maven无法下载jar包
在公司里的devops云产品中  进行mvn clean install  时候 无法下载nacos-all,似乎是无法读取到revision属性，出现问题的环境的maven版本为3.3.9，起初怀疑为maven版本过低，似乎是3.5.0之后才可以允许使用${revision}，但是我在自己本机环境 通过更换自己的maven版本为3.3.9之后，本地mvn  clean install并不会出现这个问题。我也很困惑，但是这个平台对我来说是黑盒环境，希望可以获取大佬们的一些可能性建议,不胜感激！

_平台报错图片_
![1649945823(1)](https://user-images.githubusercontent.com/29751183/163409751-eff598ab-f0b2-41ab-8558-c8635add0969.png)

似乎是不对${revision} 进行转义 直接下载
![image](https://user-images.githubusercontent.com/29751183/163414655-e43c4bbd-192a-405e-9ef3-7505c5e7233d.png)

编译不通过的模块 pom.xml
![image](https://user-images.githubusercontent.com/29751183/163409436-7e3a078e-5522-4f5a-90b9-6b46309bb947.png)

编译不通过模块 父级pom.xml
![image](https://user-images.githubusercontent.com/29751183/163410013-003a074f-f3c5-43c3-8762-06b0bfeb00a9.png)

编译不通过模块 父级的父级pom.xml
![image](https://user-images.githubusercontent.com/29751183/163410316-4d1cfd75-2a2b-40a5-bf7a-3839f93c7211.png)
![image](https://user-images.githubusercontent.com/29751183/163410369-6546c38e-b34a-4f3d-b438-35b656931a8b.png)

### How to reproduce it (as minimally and precisely as possible)

我在开放的公网环境下无法重现这个问题，本着大佬经验多的想法，来求助一下社区，希望碰到有遇到过类似问题的人群

## English version  from google translate
In the company's devops cloud products to do mvn clean install when unable to download nacos-all, it seems that it is impossible to read the resolution properties, the problematic environment of the maven version of 3.3.9, at first suspected that the maven version is too low, it seems that 3.5.0 can only allow the use of ${revision}, but I am in my own native environment This problem does not occur by replacing your own maven version to 3.3.9 after the native mvn clean install. I'm also confused, but this platform is a black box environment for me, and hopefully I can get some possible suggestions from the big guys, which is appreciated!

**company_platform_error_picture**
![1649945823(1)](https://user-images.githubusercontent.com/29751183/163409751-eff598ab-f0b2-41ab-8558-c8635add0969.png)

It appears that ${revision} is not escaped for direct download
![image](https://user-images.githubusercontent.com/29751183/163414655-e43c4bbd-192a-405e-9ef3-7505c5e7233d.png)

Modules that fail to compile pom.xml
![image](https://user-images.githubusercontent.com/29751183/163409436-7e3a078e-5522-4f5a-90b9-6b46309bb947.png)

parent of Modules that fail to compile    pom.xml
![image](https://user-images.githubusercontent.com/29751183/163410013-003a074f-f3c5-43c3-8762-06b0bfeb00a9.png)

 root  pom.xml
![image](https://user-images.githubusercontent.com/29751183/163410316-4d1cfd75-2a2b-40a5-bf7a-3839f93c7211.png)
![image](https://user-images.githubusercontent.com/29751183/163410369-6546c38e-b34a-4f3d-b438-35b656931a8b.png)

I can't reproduce this problem in the open public network environment. Based on the idea of ​​the big guy has a lot of experience, I came to the community for help, hoping to meet people who have encountered similar problems

**Comment by Oliverwqcwrw** [comment]
I wonder if common-web.jar could not be found, so the jar of later `nacos` could not be found. Can you first solve the problem that your jar could not be found

**Comment by onewe** [comment]
@a350844866 你把私服上的 nacos 相关的 jar 全部删了 然后重新拉一下试一试

**Comment by KomachiSion** [comment]
It's not nacos‘ problem, please move to SCA community.
