### ISSUE TITLE
前端界面图标异常

### ISSUE THREAD

**Issue by qlanto224** [alibaba/nacos#8161]
版本: 2.0.4  2.1.0-beta
![image](https://user-images.githubusercontent.com/58463221/163501012-7506d50c-ed8d-4f10-aa15-3d094bfe0423.png)
![image](https://user-images.githubusercontent.com/58463221/163501036-18e8df42-68e1-4420-b760-55ebf4047a11.png)
如图

**Comment by onewe** [comment]
看看请求 是不是字体文件请求出错了？

**Comment by qlanto224** [comment]
> 查看请求 是不是字体文件请求错误了？
是的 图标文件找不到。但是实际jar中是有的。配置中修改了port，content-path

**Comment by onewe** [comment]
这就难怪了

**Comment by onewe** [comment]
@i will resolve it@
