### ISSUE TITLE
nacos集群，老年代一直占用高内存

### ISSUE THREAD

**Issue by kind1ess** [alibaba/nacos#8164]
nacos版本2.0.3
服务器环境redhat 7.6 x86_64
注册了12个实例
JVM参数：
-DembeddedStorage=true -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/deploy/nacos_8848/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Xloggc:/deploy/nacos_8848/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/deploy/nacos_8848/plugins/health,/deploy/nacos_8848/plugins/cmdb -Dnacos.home=/deploy/nacos_8848 -jar /deploy/nacos_8848/target/nacos-server.jar --spring.config.additional-location=file:/deploy/nacos_8848/conf/ --logging.config=/deploy/nacos_8848/conf/nacos-logback.xml --server.max-http-header-size=524288
YGC每5分钟一次，一次平均110毫秒
FGC每20分钟一次，一次平均300毫秒，每次FGC后老年代仍有80%以上占用率

**Comment by kind1ess** [comment]
附jmap histo图
![image](https://user-images.githubusercontent.com/51308968/163515193-d6834e61-2d20-4eec-8ad6-be2b533a35d6.png)

**Comment by iQuanhe** [comment]
具体版本、环境，以及client端应用，日志，有效信息表述一下

**Comment by iQuanhe** [comment]
具体版本、环境，注册服务实例数量，jvm参数，以及client端应用，日志。。。有效信息表述一下

从你截图，明显是jvm有问题

**Comment by iQuanhe** [comment]
好家伙，IP地址: 11.99.110.101美国俄亥俄

**Comment by KomachiSion** [comment]
你看下你配置监听长连接数有多少

config-memroy.log 里面有个client-count或者connection-count

**Comment by kind1ess** [comment]
> 你看下你配置监听长连接数有多少
> 
> config-memroy.log 里面有个client-count或者connection-count

日志里找到的client count都是0

**Comment by KomachiSion** [comment]
那把内存dump出来分析下吧， 看下是什么东西占用了内存。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find the problem.
