### ISSUE TITLE
配置中心 历史版本页面无法使用

### ISSUE THREAD

**Issue by Davion2017** [alibaba/nacos#8170]
![image](https://user-images.githubusercontent.com/49489223/163547465-37c28007-bf80-4ec6-a546-d5849bf990d0.png)

**Describe the bug**
如图所示，历史版本无法直接输入dataId，不能查询历史版本

**Comment by onewe** [comment]
@Davion2017 哪个版本？

**Comment by Davion2017** [comment]
@onewe 2.0.4

**Comment by onewe** [comment]
@i will resolve it@

**Comment by onewe** [comment]
@Davion2017 最新的版本是正常的. 这个页面中的2个下拉框的逻辑是,选择当前 namespace 中的 dataId 和 group

**Comment by Davion2017** [comment]
![image](https://user-images.githubusercontent.com/49489223/163672731-e45a963a-3710-4482-8ce8-6ad9985701da.png)
![image](https://user-images.githubusercontent.com/49489223/163672754-1320ef7c-1d5c-428a-a339-0a45fba6fc05.png)
如图，public命名空间下有配置，但是在历史版本界面下拉框没有选项

**Comment by KomachiSion** [comment]
Please use 2.1.0-BETA retry

**Comment by Davion2017** [comment]
> Please use 2.1.0-BETA retry

已验证，新版本已修复
