### ISSUE TITLE
Probably exists ArithmeticException

### ISSUE THREAD

**Issue by Oliverwqcwrw** [alibaba/nacos#8177]
**Describe the bug**
In `com.alibaba.nacos.client.naming.utils.Chooser.Ref#refresh`

> exactWeights[index++] = singleWeight / originWeightSum;

It maybe exists ArithmeticException When the service weight is 0.

e.g. I modify the weight to 0 manually

**Expected behavior**

There is no possibility of abnormal occurrence

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1.  I modify the weight to 0 manually

**Comment by KomachiSion** [comment]
```
            Double originWeightSum = (double) 0;
            
            for (Pair<T> item : itemsWithWeight) {
                
                double weight = item.weight();
                //ignore item which weight is zero.see test_randomWithWeight_weight0 in ChooserTest
                if (weight <= 0) {
                    continue;
                }
                
                items.add(item.item());
                if (Double.isInfinite(weight)) {
                    weight = 10000.0D;
                }
                if (Double.isNaN(weight)) {
                    weight = 1.0D;
                }
                originWeightSum += weight;
            }
            
            double[] exactWeights = new double[items.size()];
            int index = 0;
            for (Pair<T> item : itemsWithWeight) {
                double singleWeight = item.weight();
                //ignore item which weight is zero.see test_randomWithWeight_weight0 in ChooserTest
                if (singleWeight <= 0) {
                    continue;
                }
                exactWeights[index++] = singleWeight / originWeightSum;
            }

```

I think no possibility, if run `exactWeights[index++] = singleWeight / originWeightSum;` means that some items in itemsWithWeight has no zero weight, but if there are some items no zero weight, the `originWeightSum` is no zero also.

detail in codes line 128 to 143.
