### ISSUE TITLE
nacos1.4.2版本访问权限的问题

### ISSUE THREAD

**Issue by hanzhc** [alibaba/nacos#8188]
我使用的是nacos1.4.2版本，当在未登录的时候直接通过浏览器访问http://10.211.55.8:8848/nacos/v1/core/cluster/nodes?withInstances=false&pageNo=1&pageSize=10时，即可获取cluster的相关信息？这种做法存在一定的安全隐患。

**Comment by jefferson-chern** [comment]
这个还好吧，就是ip信息，而且都是内网ip

**Comment by KomachiSion** [comment]
duplicate with #8015
