### ISSUE TITLE
Redundant code in DefaultInstanceUpgradeHelper

### ISSUE THREAD

**Issue by qiugongzi** [alibaba/nacos#8193]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32306504/163722755-397a7123-cc9d-47e5-a91f-518eb3ffb807.png)
Class Instance extends com.alibaba.nacos.api.naming.pojo.Instance,only needs BeanUtils.copyProperties(v2, v1);
Set Method is redundant.

**Expected behavior**
Instance v1 = new Instance(v2.getIp(), v2.getPort(), v2.getClusterName());
BeanUtils.copyProperties(v2, v1);

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by pixystone** [comment]
Yes, a pr is welcome.

**Comment by qiugongzi** [comment]
@i will solve it@
