### ISSUE TITLE
Nacos-2.0.4  Dubbo多协议在Nacos只能注册成功一个

### ISSUE THREAD

**Issue by jinyingxiong** [alibaba/nacos#8195]
我们的Dubbo服务同时开启了dubbo和webservice双协议，但注册到Nacos后显示只有一个实例。
通过跟踪Dubbo的NacosRegistry代码，发现两个服务都发布实例信息到Nacos了，但两个实例信息互相覆盖最后只保留了一个实例信息。
通过检查NamingService代码和编写测试用例，发现一个NamingService实例只能对一个serviceName发布一个实例，如果想针对一个serviceName发布多个实例只能通过创建多个NamingService分别发布来实现。
能否增加新配置允许一个NamingService实例发布serviceName的多个实例并同时生效。

**Comment by KomachiSion** [comment]
双协议服务名是一样的吗？这感觉不太符合一般对于服务的概念。

目前2.0版本实例和连接是绑定，暂时不支持同一个客户端注册同一个服务的多个实例。计划是以batch注册的方式一次性注册多个实例，目前还在方案设计中。

如果这个问题无法避免，可以先使用nacos-client1.X版本，前提是需要两个不同的协议对应不同的端口。
