### ISSUE TITLE
Nacos 1.4.1 not competitable with nacos-sdk-go:v1.1.1

### ISSUE THREAD

**Issue by hundanLi** [alibaba/nacos#8198]
**Describe the bug**
When using service registry with nacos-sdk-go v1.1.1 and nacos-1.4.1, error occured. Cannot register instance.

**Expected behavior**
register instance successfully

**Acutally behavior**
Cannot register instance.

**How to Reproduce**
register service with nacos-sdk-go v1.1.1 to nacos-server-1.4.1

**Desktop (please complete the following information):**
 - OS:  Centos
 - Version nacos-server 1.4.1, nacos-sdk-go v1.1.1
 - Module naming
 - SDK original

**Additional context**

**Comment by KomachiSion** [comment]
Can you change other nacos-go-sdk or nacos-server to retry?

1.4.1 server and 1.1.1 go-sdk both not newest version, maybe the problem has been fixed.

**Comment by KomachiSion** [comment]
No more response from author, new version should have fixed this problem..
