### ISSUE TITLE
config external services with specific endpoint.

### ISSUE THREAD

**Issue by leiminghany** [alibaba/nacos#8199]
为什么不考虑支持配置外部服务呢？

**Comment by Oliverwqcwrw** [comment]
Why don't support? Such as dubbo service

**Comment by KomachiSion** [comment]
I can't get the meanings of `配置外部服务`. Can you have some detail description?

**Comment by leiminghany** [comment]
thanks for you feedback @KomachiSion 

for example. I want to get the “Weather forecast information” which is served outside and not registed in our Nacos cluster.
can I manually register that service in our Nacos cluster with that URL,  and then call it in our programs using serviceName?

**Comment by KomachiSion** [comment]
We are planing to support DNS protocol, and add some plugin to support DNS-F or coreDNS. After that, this way maybe work well.

**Comment by KomachiSion** [comment]
#8311
#50
