### ISSUE TITLE
服务端nacos2.0.1 局部升级客户端到2.0.4 （集群模式），无法注册成功

### ISSUE THREAD

**Issue by helei810304** [alibaba/nacos#8205]
nacos-server : 2.0.1
nacos-client: 大部分是1.4.x
线上部署的是nacos 集群模式.
问题描述： 我们一个应用的其中一个节点（一个应用有2-3个节点），线上升级到了客户端2.0.4 ,但是无法注册服务和收到Ack 的日志，但是在开发环境中，是可以的（开发环境是standaonle 模式）

求指导如何修复

**Comment by helei810304** [comment]
什么时候去触发这个url
curl -X PUT 'localhost:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false'

是nacos-server 完全升级成功？
还是nacos-client完全升级成功?

**Comment by KomachiSion** [comment]
是nacos-server 完全升级成功.

**Comment by KomachiSion** [comment]
> 我们一个应用的其中一个节点（一个应用有2-3个节点），线上升级到了客户端2.0.4 ,但是无法注册服务和收到Ack 的日志，但是在开发环境中，是可以的（开发环境是standaonle 模式）

需要更多信息。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
