### ISSUE TITLE
How to make version 2.1.0-BETA use PostgreSql? In addition to modifying the pom dependencies and property configuration files, is there anything that needs to be modified in the source code?

### ISSUE THREAD

**Issue by JieJieNiDeAi** [alibaba/nacos#8215]
## Issue Description
How to make version 2.1.0-BETA use PostgreSql? In addition to modifying the pom dependencies and property configuration files, is there anything that needs to be modified in the source code?
--请问怎样让版本2.1.0-BETA使用PostgreSql？除了修改pom依赖以及属性配置文件，源码有需要修改的地方吗？

Currently modified:
--目前已修改：
1、nacos-all  -> pom.xml
2、nacos-config   -> pom.xml
3、nacos-console  -> application.properties

Is there anything else that needs to be modified?
--还有其他需要修改的吗？

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by onewe** [comment]
看看 ExternalStoragePersistServiceImpl 有没有语法不兼容的

**Comment by KomachiSion** [comment]
确认PersistService中的SQL在PG中都能够正常运行，如果不能正常运作就需要修改对应SQL
