### ISSUE TITLE
403 error in Reset Password API in User Management

### ISSUE THREAD

**Issue by weihongzhoulord** [alibaba/nacos#8217]
**Describe the bug**
403 error in Reset Password API in User Management.
API：PUT /nacos/v1/auth/users
<img width="989" alt="image" src="https://user-images.githubusercontent.com/36416216/164215134-0705bcfc-679f-48a6-b3a0-6be730aafaf7.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/36416216/164216511-3380b479-701e-48b8-969d-917f9fb05189.png">

**Expected behavior**
No errors.

**How to Reproduce**
1. Go to 'User Management'
2. Click on 'Edit'
3. Input 'Password and Repeat'
4. Click on 'OK'
5. See error

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 2.0.4]
 - Module [user]

**Comment by onewe** [comment]
@i will resove it@

**Comment by li-xiao-shuang** [comment]
> **Describe the bug** 403 error in Reset Password API in User Management. API：PUT /nacos/v1/auth/users <img alt="image" width="989" src="https://user-images.githubusercontent.com/36416216/164215134-0705bcfc-679f-48a6-b3a0-6be730aafaf7.png"> <img alt="image" width="851" src="https://user-images.githubusercontent.com/36416216/164216511-3380b479-701e-48b8-969d-917f9fb05189.png">
> 
> **Expected behavior** No errors.
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'User Management'
> 2. Click on 'Edit'
> 3. Input 'Password and Repeat'
> 4. Click on 'OK'
> 5. See error
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Centos]
> * Version [nacos-server 2.0.4]
> * Module [user]

我本地并没有复现这个问题

**Comment by onewe** [comment]
@li-xiao-shuang 先登录,然后重启后端,前端界面上点击修改密码
