### ISSUE TITLE
Support for integration with Spring Boot Admin?

### ISSUE THREAD

**Issue by xuande** [alibaba/nacos#822]

**Comment by 77321660** [comment]
After the spring boot admin is started, the changes in the service in nacos cannot be monitored, and the monitoring notification reminder function cannot reflect the latest changes.

**Comment by xuande** [comment]
Yes, SBA integration Eureka, you can set `registryFetchIntervalSeconds` in `application.yml`, it can fetch all services list from Eureka and update cache, but nacos client does not provider this function.

**Comment by SoftwareKing** [comment]
Support for integration with Spring Boot Admin Example
https://github.com/SoftwareKing/sba-nacos

**Comment by seas521** [comment]
i have the same question

**Comment by xuande** [comment]
@seas521 Refer https://juejin.im/post/5cb72e41f265da035a1f1609

**Comment by nkorange** [comment]
> @seas521 Refer https://juejin.im/post/5cb72e41f265da035a1f1609

Very good post!
