### ISSUE TITLE
Improve code quality,add Null Pointer Judgement

### ISSUE THREAD

**Issue by qiugongzi** [alibaba/nacos#8222]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32306504/164274257-55df1005-9209-4d1d-916c-1fd4bd0e3303.png)
getName() maybe null,so add getName()!=null && .. is better , or add Asset.notNull(getName(),"service name cannot be null")
before it, like "The Class Cluster validate method" do !

The class is com.alibaba.nacos.naming.core.Service : validate()

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Chaos-coder** [comment]
> **Describe the bug** ![image](https://user-images.githubusercontent.com/32306504/164274257-55df1005-9209-4d1d-916c-1fd4bd0e3303.png) getName() maybe null,so add getName()!=null && .. is better , or add Asset.notNull(getName(),"service name cannot be null") before it, like "The Class Cluster validate method" do !
> 
> The class is com.alibaba.nacos.naming.core.Service : validate()
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Acutally behavior** A clear and concise description of what you actually to happen.
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Centos]
> * Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
> * Module [e.g. naming/config]
> * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> 
> **Additional context** Add any other context about the problem here.

@i will solve it@
