### ISSUE TITLE
支持nacos 2.0集群构建能选择AP/CP模式，从服务端能控制

### ISSUE THREAD

**Issue by whl12345** [alibaba/nacos#8225]
只想保留AP模式作为注册中心，能不能让服务端忽略掉jraft协议相关的逻辑

**Comment by whl12345** [comment]
目前业务场景：客户端只使用ap模式，理论上jraft相关是冗余的，jraft稳定性可能会导致整个集群问题，而不应该影响到正常的ap模式服务发现

**Comment by KomachiSion** [comment]
是不影响啊。jraft无法选主时，注册，查询，删除非持久化实例是不受影响的
只有修改元数据/注册/删除持久化实例才会受影响。

**Comment by KomachiSion** [comment]
No more response from author.
