### ISSUE TITLE
No sense Code

### ISSUE THREAD

**Issue by qiugongzi** [alibaba/nacos#8230]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32306504/164482126-acb6ca07-4b21-46de-a089-07910c7f44d2.png)
com.alibaba.nacos.naming.core.ServiceManager

"service = getService(service.getNamespaceId(), service.getName());" should be deleted,because the service ref
couldn't change after putService.
putService方法后，getService获取到的service引用必然恒等于之前的service引用。所以这次getService操作毫无意义。

**Expected behavior**
没有必要的代码

**Acutally behavior**
删除不必要的代码

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Oliverwqcwrw** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
多线程时有意义，可以再思考下。如果多线程同一个服务的情况下，不加getService的话，put的先后顺序和init的先后顺序可能不一致。
