### ISSUE TITLE
[Document] In Class view ,The 'HttpSimpleClient' is not exist

### ISSUE THREAD

**Issue by Oliverwqcwrw** [alibaba/nacos#8231]
**Describe the bug**

Path: Nacos是什么  -> 架构 -> 类视图

The 'HttpSimpleClient' is not exist, Is it replaced with 'NacosRestTemplate'

**Comment by Chaos-coder** [comment]
> **Describe the bug**
> 
> Path: Nacos是什么 -> 架构 -> 类视图
> 
> The 'HttpSimpleClient' is not exist, Is it replaced with 'NacosRestTemplate'

@ i will solve it @
