### ISSUE TITLE
nacos客户端负载均衡的流程大致是什么？

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#8238]
目前在学习nacos整合springCloud的源码知识  想尝试二次封装 nacos客户端的负载均衡策略  但是nacos内部的负载策略没有怎么捋清楚
想问问各位大佬 大致流程  十分感谢

**Comment by KomachiSion** [comment]
1. nacos客户端没有所谓的负载均衡策略，只有按照权重随机选择一个实例的能力。
2. spring cloud的负载均衡策略在SCA社区，可以到SCA社区问一下。
