### ISSUE TITLE
nacos集群启动在网络不通的情况下会在非常短的时间内占满所有硬盘空间

### ISSUE THREAD

**Issue by Orisland** [alibaba/nacos#8239]
**Describe the bug**
网络不通时，连接日志会在非常短的时间内刷满整个服务器硬盘。
Translated from Google:
When the network fails, the connect log will fill the entire server hard disk within a very short period of time.

**Expected behavior**
我只是在正常启动nacos，且并未意识到此时网络不通。
Translated from Google:
I was just starting nacos normally, and I didn't realize that the network was unavailable at this time.

**Acutally behavior**
在使用集群模式启动时（数据库连接为阿里云数据库RDS）。如果该系统此时的网络状态不通（例如gateway设置错误）会导致nacos在非常短的时间内在logs文件夹内刷出大量的日志(protocol-raft.log与protocol-raft.log.2022-04-22.0)日志中protocol-raft.log.xxxx-xx-xx.x居多，且无上限增加，2gb/个，直至整个系统空间被100%使用为止，此时日志不再增加，nacos在后台退出。集群中的任何一台在网络不通时，都会出现该问题，启动几个nacos，刷出日志的速度就会乘以几个。
我以为她会在失败时或者发现网络不通时停止尝试，但是并不会，且重试频率非常的高。
在问题期间nacos无法访问，似乎一直处于重试连接状态，由于服务器上的log文件太大我直接删除了也没有仔细查看内容，该问题在我发现网络不通并修复后消失。
Translated from Google:
The usage environment is centos, and when it is started in cluster mode (database connection is Alibaba Cloud Database RDS). If the network status of the system at this time is not working (for example, the gateway is set incorrectly), nacos will flush a large number of logs in the logs folder in a very short time (protocol-raft.log and protocol-raft.log.2022-04- 22.0) Protocol-raft.log.xxxx-xx-xx.x is mostly in the log, and there is no upper limit to increase, 2gb/pc, until the entire system space is used by 100%, at which time the log will no longer increase, and nacos will exit in the background. This problem will occur when any one in the cluster is disconnected from the network. When several nacos are started, the speed of logging out will be multiplied by several.
I thought she would stop trying when it fails or finds the network is down, but it doesn't, and the retry frequency is very high.
During the problem, nacos was inaccessible and seemed to be in a state of retrying the connection all the time. Because the log file on the server was too large, I directly deleted it and did not check the content carefully. The problem disappeared after I found that the network was blocked and repaired.

**How to Reproduce**
1.修改centos的网卡配置文件，使其错误，导致网络不通(例如乱写gateway)
2.集群的方式启动nacos（数据源为网络数据库，例如阿里的rds）
3.观察logs文件夹的占比
Translated from Google:
1. Modify the network card configuration file of centos to make it wrong and cause the network to fail (such as scribbling gateway)
2. Start nacos in a cluster mode (the data source is a network database, such as Ali's rds)
3. Observe the proportion of the logs folder

**Desktop (please complete the following information):**
 - OS: Centos7
 - Version nacos-server 2.0.4
 - Module cluster 
 - SDK spring-cloud-alibaba-nacos

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/164952383-47910c7e-40f8-4c43-b9ab-a874bd2a7391.png)

we has add the max and rolling in log, if you want to change the size, you can change the log conf in your env.
