### ISSUE TITLE
Redundant judgment

### ISSUE THREAD

**Issue by qiugongzi** [alibaba/nacos#8240]
**Describe the bug**
多余的判断逻辑
![image](https://user-images.githubusercontent.com/32306504/164889660-6f683cc6-6160-403e-a63f-34db9970e22a.png)
putIfAbsent的语义已然包含了判断，故不需要if语句。
就像下面那一行
`serviceMap.get(service.getNamespaceId()).putIfAbsent(service.getName(), service);`
并未加入if判断

**Expected behavior**
去除if语句，让代码更整洁

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by qiugongzi** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
不需要删除，如果每次都调用put，每次都需要创建新列表，重复出现GC垃圾。
