### ISSUE TITLE
页面上看不到之前的配置文件，但是本地可以正常拉取配置--The previous configuration file cannot be seen on the page, but the configuration can be pulled normally locall

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#8242]
页面上之前配置的都没有了，但是我本地可以正常访问；
在我本地改了缓存地址的情况下也可以正常访问；
也可以正常从nacos拉取配置 只是页面上看不到配置文件了
![image](https://user-images.githubusercontent.com/90117583/164953843-10705c0b-fd6d-4e68-8f11-f372f9e194f3.png)

The previous configuration on the page is gone, but I can access it locally;
I can access it normally even if I change the cache address locally;
You can also pull the configuration from nacos normally, but you can't see the configuration file on the page.

**Comment by onewe** [comment]
看看页面的请求是否正确请求到了nacos后端

**Comment by realJackSun** [comment]
1、清空一下浏览器缓存？
2、F12看一下是否到达了后端？或者后端Debug或抓包看一下

**Comment by nomatterfine** [comment]
这个问题没有复现，等下一次出现再看看了
