### ISSUE TITLE
when health check extend provider init  v2 plugin cause  IllegalStateException

### ISSUE THREAD

**Issue by mengyingsunshi** [alibaba/nacos#8243]
**Describe the bug**
when loading the v2 health checker cause IllegalStateException due to the incompatibility between the HealthCheckExtendProvider and the HealthCheckProcessorV2Delegate,the health checker is registered  to the single bean factory twice.

**Expected behavior**
v2 health check plugin is loaded correctly.

**Acutally behavior**
throw an IllegalStateException.

**How to Reproduce**
1. add the health check plugin into nacos/plugins/health
2. start up

**Desktop (please complete the following information):**
 - OS: Centos
 - Version nacos-server 2.0.4
 - Module naming/health
 - SDK 

**Additional context**
```
throw new IllegalStateException("Could not register object [" + singletonObject + "] under bean name '" + beanName + "': there is already object [" + oldObject + "] bound");
```

**Comment by mengyingsunshi** [comment]
@KomachiSion Hello, Can I consult this PR subsequent arrangement?

**Comment by mengyingsunshi** [comment]
when I implement the V1 and the V2 HealthCheckProcess, and put the jar to the /nacos/plugins/health.Then I start nacos, as the picture show, the log thow an Exception.I guess the reason is, HealthCheckExtendProvider.init() is called twice. And the V2 extend processor is not loaded.
![8d62](https://user-images.githubusercontent.com/46910331/176613235-5858e988-de3e-485d-b0da-28ccfe0f5ba0.png)
![8fdf](https://user-images.githubusercontent.com/46910331/176613773-51dbe6c9-d976-43cf-9986-f8e677c363d5.png)

![8cb8](https://user-images.githubusercontent.com/46910331/176613075-6691b341-e3cc-4da4-8a6e-f6790e131c54.png)
![8ec6](https://user-images.githubusercontent.com/46910331/176613508-d2112b9d-539c-49c6-b3fb-c937d54961ef.png)
so I commit a pr to resolve this question.I add HealthCheckProcessorExtendV2 to load extend V2 processor.

**Comment by KomachiSion** [comment]
OK, I will review the code
