### ISSUE TITLE
nacos 的如何分离部署（注册中心 和 配置中心）

### ISSUE THREAD

**Issue by wangdongyun** [alibaba/nacos#8252]
**Is your feature request related to a problem? Please describe.**
nacos 注册中心和配置中心可以分离部署，但是如何做，没有找到好的资料！
应该是有不同的编译命令？

**Describe the solution you'd like**
希望 提供可独立编译的模块，比如独立部署 config 模块，包含了核心功能 和 管理台
.

**Comment by realJackSun** [comment]
部署两个Nacos，一个用于做注册中心，一个用于做服务发现。

**Comment by wangdongyun** [comment]
ok! 这个我还没有测试，看代码我理解的用法：

打包：
使用-P 指定模块打包
启动：
使用 -f 参数

**Comment by jefferson-chern** [comment]
> ok! 这个我还没有测试，看代码我理解分两步使用：
> 
> 1. 打包：使用-P 指定模块打包
> 2. 启动： 使用 -f 参数

打包的时候都是一样的命令，就是包都是一样的，只是在启动的时候使用 -f参数区分， _startup.sh -f naming_ 就是启动注册中心，*startup.sh -f config* 就是启动配置中心。

**Comment by wangdongyun** [comment]
好的 多谢

**Comment by wangdongyun** [comment]
> > ok! 这个我还没有测试，看代码我理解分两步使用：
> > 
> > 1. 打包：使用-P 指定模块打包
> > 2. 启动： 使用 -f 参数
> 
> 打包的时候都是一样的命令，就是包都是一样的，只是在启动的时候使用 -f参数区分， _startup.sh -f naming_ 就是启动注册中心，_startup.sh -f config_ 就是启动配置中心。

不对啊，这个打包的时候也需要拆分，我自己实际测试了，不然只是页面不显示，但是 接口功能是全的

**Comment by jefferson-chern** [comment]
> > > ok! 这个我还没有测试，看代码我理解分两步使用：
> > > 
> > > 1. 打包：使用-P 指定模块打包
> > > 2. 启动： 使用 -f 参数
> > 
> > 
> > 打包的时候都是一样的命令，就是包都是一样的，只是在启动的时候使用 -f参数区分， _startup.sh -f naming_ 就是启动注册中心，_startup.sh -f config_ 就是启动配置中心。
> 
> 不对啊，这个打包的时候也需要拆分，我自己实际测试了，不然只是页面不显示，但是 接口功能是全的

怎么区分打包的？最后成功了吗？

**Comment by jefferson-chern** [comment]
> > > ok! 这个我还没有测试，看代码我理解分两步使用：
> > > 
> > > 1. 打包：使用-P 指定模块打包
> > > 2. 启动： 使用 -f 参数
> > 
> > 
> > 打包的时候都是一样的命令，就是包都是一样的，只是在启动的时候使用 -f参数区分， _startup.sh -f naming_ 就是启动注册中心，_startup.sh -f config_ 就是启动配置中心。
> 
> 不对啊，这个打包的时候也需要拆分，我自己实际测试了，不然只是页面不显示，但是 接口功能是全的

怎么区分打包的？最后注册中心和配置中心区分打包之后都成功运行了没？
