### ISSUE TITLE
nacos 线程数量异常

### ISSUE THREAD

**Issue by litaipo** [alibaba/nacos#8255]
![image](https://user-images.githubusercontent.com/20733031/165044218-da255158-63e6-491e-884a-e263e3bcaa53.png)
如图，目前只接入了几个服务，线程数已经飙到500+了，大量的waiting线程没有销毁是什么原因呢

**Comment by KeithTt** [comment]
Hi, what is this tool? It is beautiful.

**Comment by onewe** [comment]
Wow~

**Comment by whl12345** [comment]
我也发现了类似问题，2.0服务端才会出现，1.0服务端正常

**Comment by realJackSun** [comment]
你用的是2.0.几版本？能否把dump下来的线程信息上传一份，粘贴上来看看？

**Comment by KomachiSion** [comment]
只看group是Jraft所使用的线程，waiting的线程实际上不影响，或者您详细排查一下为什么Jraft group的线程这么多？

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to judge this problem.
