### ISSUE TITLE
Nacos 2.0 server+1.0 client相比于1.0 server + 1.0client有性能劣化

### ISSUE THREAD

**Issue by whl12345** [alibaba/nacos#8256]
需求：升级nacos
老版本nacos:1.14server+1.0client
新版本nacos:2.0.3server+1.0client
集群节点数：3节点
集群单机配置：8核16G

升级nacos 2.0需要先升级服务端，完成升级后发现服务端性能有劣化，相比于1.1.4容量有所降低，采用相同硬件配置，相同线上流量，2.0集群出现部分节点宕机，大量5XX。

一些现象：
2.0集群：峰值压力18000注册实例，临界cpu负载接近45左右，jvm_threads_daemon_threads单机800，集群出现不稳定表现为5XX升高，节点宕机
1.0集群：峰值压力30000注册实例， 测试临界cpu负载达到68，jvm_threads_daemon_threads仅有300，峰值压力约为2.0集群的1.5倍
问题：
请问2.0集群在兼容1.0客户端时是否引起了额外开销，官方有相关性能测试数据么？
jvm_daemon_threads线程飙高是什么原因？

**Comment by KomachiSion** [comment]
1. 请问是否关闭双写？
2. 2.0集群彻底释放性能需要客户端服务端均升级到2.0，并关闭双写，只升级服务端不关闭双写必然比1.0性能更低，关闭双写后与1.0相当
3. 关于压测之前写过一个文章，可以自行检索一下。
4. jvm_daemon_threads标高的原因需要你自行排查一下， 推测可能是有部分gprc的线程，但是大多数应该都是wating状态

**Comment by whl12345** [comment]
未关闭双写，考虑平滑回滚，平滑升级的场景

**Comment by tiger822** [comment]
> 

请教一下，你这个nacos集群，是共用同一个外部数据库的还是每个nacos服务用独立一个数据库？？

**Comment by whl12345** [comment]
> > 
> 
> 请教一下，你这个nacos集群，是共用同一个外部数据库的还是每个nacos服务用独立一个数据库？？

公用1个数据库，我们只用临时实例数据库涉及不多

**Comment by whl12345** [comment]
存量迁移，需要保持较长时间存在1.0客户端，官方是否有详细数据，开启双写集群性能劣化大概能多少？

**Comment by whl12345** [comment]
打算用新版2.1.0再测试下，我看2.1.0是默认关闭双写吧
如下命令可以开启双写吧
http://${ip}:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=true

**Comment by whl12345** [comment]
![grafana](https://user-images.githubusercontent.com/36367435/165919688-83c1350e-d035-4bea-99e3-f1dca47109e1.png)

**Comment by whl12345** [comment]
在一定压力使用一段时间，服务端会出现内存溢出 ，压测停止，内存依旧没有释放
jvm内存占用98%，主要对象如下
  1:        770839     1293092936  [Ljava.lang.Object;
   2:        701851      460414256  io.grpc.netty.shaded.io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueue
   3:         59729      238432040  [B
   4:         97134      127924568  [I
   5:        245989       83177368  [C
   6:         23097       35648208  [Ljava.util.HashMap$Node;
   7:        647848       20731136  io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache
   8:        192815        4627560  java.lang.String
   9:        106676        4267040  java.util.WeakHashMap$Entry
  10:         53990        3742896  [Lio.grpc.netty.shaded.io.netty.buffer.PoolThreadCache$MemoryRegionCache;
  11:         14853        3239552  [Ljava.util.concurrent.ConcurrentHashMap$Node;

**Comment by whl12345** [comment]
![Uploading 截屏2022-05-03 下午8.19.33.png…]()

**Comment by KomachiSion** [comment]
双写对性能损耗肯定是明显的， 特别是实例规模越大的时候，越明显，这是毋庸置疑的。

**Comment by jasonpyf** [comment]
jvm_daemon_threads标高 
![image](https://user-images.githubusercontent.com/16953632/167575879-ae1582e6-0413-443f-baf5-9c47573447cd.png)
每次grpc-client心跳都会创建线程，线程超时回收，线程池也没用到

**Comment by KomachiSion** [comment]
grpc的client是一个动态的线程池，忙时会有较多的线程创建， 闲时会回收线程，释放资源。

**Comment by KomachiSion** [comment]
No more response from author.
