### ISSUE TITLE
400 request body error encountered while modifying password

### ISSUE THREAD

**Issue by forxiu** [alibaba/nacos#8257]
**Describe the bug**
Using the cluster mode and external storage mode, the deployment is successful, but there is an error when modifying the password. Try to troubleshoot the problem. The problem is as follows: there is no error when modifying the password when using idea, and there is an error when modifying the password when running the distribution versions of windows and Linux on the server. The error response is 400 caused: user, Nacos not exist!;

**Expected behavior**
see Describe the bug

**Acutally behavior**
see Describe the bug

**How to Reproduce**
see Describe the bug

**Desktop (please complete the following information):**
 - OS: windows7/centos7.2
 - Version NACOS 1.4.3
 - Module [console]
 - SDK [null]

**Additional context**
null

**Comment by realJackSun** [comment]
"user, Nacos not exist!;" Naocs确认运行状态正常吗？
本地telnet 127.0.0.1 8848试试

**Comment by forxiu** [comment]
> "user, Nacos not exist!;" Naocs确认运行状态正常吗？ 本地telnet 127.0.0.1 8848试试

运行正常，可正常登录。修改密码报错！前端传值bug导致，还指望官方修复，结果至今未修复

**Comment by forxiu** [comment]
> 应该已经修复了， 升级至2.1.0-BETA试一下

好的，我试试

**Comment by forxiu** [comment]
已在2.1.0-BETA版本验证，已修复
