### ISSUE TITLE
The configuration in the bootstrp.yml file is not read

### ISSUE THREAD

**Issue by shangjunshang** [alibaba/nacos#8258]
the bootstrp.yml‘s content

spring:
  cloud:
    nacos:
      config:
        server-addr: ${nacos.url:127.0.0.1}:${nacos.port:8001}
        group: DEFAULT_GROUP
        prefix: pms-server-data-center
        file-extension: yaml
      discovery:
        server-addr: ${nacos.url:127.0.0.1}:${nacos.port:8001}

version：
![image](https://user-images.githubusercontent.com/49359168/165076888-7cd9f830-b5b2-48c5-bfd1-ea3a55845b80.png)

thinks for your answer

**Comment by onewe** [comment]
I guess that you may need a `spring-cloud-starter-bootstrap`, [Here is the spring cloud document](https://docs.spring.io/spring-cloud-config/docs/3.1.1/reference/html/#config-first-bootstrap).

**Comment by shangjunshang** [comment]
> I guess that you may need a `spring-cloud-starter-bootstrap`, [Here is the spring cloud document](https://docs.spring.io/spring-cloud-config/docs/3.1.1/reference/html/#config-first-bootstrap).

thinks for your answer，you are right
