### ISSUE TITLE
nacos修改密码，删除用户都报错

### ISSUE THREAD

**Issue by liang2025** [alibaba/nacos#8259]
version: 1.4.3
cluster: 3
db: mysql
error: caused: user nacos,nacos not exist!;

**Comment by onewe** [comment]
最新的版本已经解决了

**Comment by liang2025** [comment]
我测了最新版本也有这个问题啊，你修复的版本是哪个版本？

**Comment by onewe** [comment]
多半是前端缓存的问题,清除缓存,或者换个浏览器重试一下.

**Comment by liang2025** [comment]
OK

**Comment by onewe** [comment]
@liang2025 1.x 的发行版的确是有个这个问题,最新的1.x快照版本已经修复了, 你可以把源码拉取下来重新打一下包

**Comment by zhengmx1993** [comment]
忘记密码如何重置密码？如果外置数据库，可以通过修改数据库库中的密码来重置密码。但如果使用内置数据库，忘记密码了如何重置？
