### ISSUE TITLE
docker nacos cluster can't replication data

### ISSUE THREAD

**Issue by tiger822** [alibaba/nacos#8260]
Maybe my compose file is incorrect: 
compose file : https://blog.csdn.net/rocklee/article/details/124423202
`
version: "3"
services: 
    nacos1:
        container_name: nacos-server01
        hostname: nacos-server01
        image: nacos/nacos-server:v2.0.4-slim
        environment: 
            - MODE=cluster
            - PREFER_HOST_MODE=hostname
            - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=128.30.202.25
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=root
            - MYSQL_SERVICE_PASSWORD=123456
            - MYSQL_SERVICE_DB_NAME=nacos-c1
            - JVM_XMS=128m
            - JVM_XMX=256m
            - JVM_XMN=128m
        volumes: 
            - ./cluster-logs/nacos-server01:/home/nacos/logs
            #- init.d:/home/nacos/init.d
        ports: 
            - 8846:8848
            - 9555:9555
        networks:
            naco-bridge:
                aliases:
                    - nacos-server01
        restart: on-failure

    nacos2:
        container_name: nacos-server02
        hostname: nacos-server02
        image: nacos/nacos-server:v2.0.4-slim
        environment: 
            - MODE=cluster
            - PREFER_HOST_MODE=hostname
            - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=128.30.202.25
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=root
            - MYSQL_SERVICE_PASSWORD=123456
            - MYSQL_SERVICE_DB_NAME=nacos-c2
            - JVM_XMS=128m
            - JVM_XMX=256m
            - JVM_XMN=128m
        volumes: 
            - ./cluster-logs/nacos-server02:/home/nacos/logs
            #- init.d:/home/nacos/init.d
        ports: 
            - 8847:8848
        networks:
            naco-bridge:
                aliases:
                    - nacos-server02
        restart: on-failure

    nacos3:
        container_name: nacos-server03
        hostname: nacos-server03
        image: nacos/nacos-server:v2.0.4-slim
        environment: 
            - MODE=cluster
            - PREFER_HOST_MODE=hostname
            - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=128.30.202.25
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=root
            - MYSQL_SERVICE_PASSWORD=123456
            - MYSQL_SERVICE_DB_NAME=nacos-c3
            - JVM_XMS=128m
            - JVM_XMX=256m
            - JVM_XMN=128m
        volumes: 
            - ./cluster-logs/nacos-server03:/home/nacos/logs
            #- init.d:/home/nacos/init.d
        ports: 
            - 8848:8848
        networks:
            naco-bridge:
                aliases:
                    - nacos-server03
        restart: on-failure 
networks:
  naco-bridge:
    driver: bridge
`
database: mysql 5.7

I add a configuration data into server 'nacos-server01', the data has not been replicated to anothers server. **but registered services data can.** 

questions ：
1/ how to open debug switch to log the detail for input/output?
2/ why my nacos cluster can't replication data ?

**Comment by KomachiSion** [comment]
I think your cluster is not deploy rightly, you can see example in nacos-group/nacos-docker and have an understand how to deploy rightly.

**Comment by tiger822** [comment]
> nacos-group/nacos-docker
I modified my compose file and changed to env_file mode, but keep to use **standalone database** per nacos server .
I tried again and got the same result .
please try with the config files : https://blog.csdn.net/rocklee/article/details/124423202

**Comment by tiger822** [comment]
`
version: "3"

services: 
    nacos1:
        container_name: nacos-server01
        hostname: nacos-server01
        image: nacos/nacos-server:v2.0.4-slim
        env_file:
            - ./nacos-hostname.env
        environment: 
            - MYSQL_SERVICE_DB_NAME=nacos-c1
        volumes: 
            - ./cluster-logs/nacos-server01:/home/nacos/logs
            #- init.d:/home/nacos/init.d
        ports: 
            - 8846:8848
            - 9555:9555
        networks:
            naco-bridge:
                aliases:
                    - nacos-server01
        restart: on-failure

    nacos2:
        container_name: nacos-server02
        hostname: nacos-server02
        image: nacos/nacos-server:v2.0.4-slim
        env_file:
            - ./nacos-hostname.env
        environment: 
            - MYSQL_SERVICE_DB_NAME=nacos-c2
        volumes: 
            - ./cluster-logs/nacos-server02:/home/nacos/logs
            #- init.d:/home/nacos/init.d
        ports: 
            - 8847:8848
        networks:
            naco-bridge:
                aliases:
                    - nacos-server02
        restart: on-failure

    nacos3:
        container_name: nacos-server03
        hostname: nacos-server03
        image: nacos/nacos-server:v2.0.4-slim
        env_file:
            - ./nacos-hostname.env
        environment: 
            - MYSQL_SERVICE_DB_NAME=nacos-c3
        volumes: 
            - ./cluster-logs/nacos-server03:/home/nacos/logs
            #- init.d:/home/nacos/init.d
        ports: 
            - 8848:8848
        networks:
            naco-bridge:
                aliases:
                    - nacos-server03
        restart: on-failure 
networks:
  naco-bridge:
    driver: bridge


`

**Comment by tiger822** [comment]
> I think your cluster is not deploy rightly, you can see example in nacos-group/nacos-docker and have an understand how to deploy rightly.

feedbacked

**Comment by tiger822** [comment]
tested v2.0.4, v2.0.4-slim，v2.1.0-BETA
I tried again and got the same result ：
registered services can replicate to another server, but configurations can't.

**Comment by tiger822** [comment]
I change database type  to 'embedded', It works, why ?! @KomachiSion

**Comment by KomachiSion** [comment]
embedded database will use `derby` which will not connect to `mysql`.  Maybe your old problem is can't connect to your mysql so that your cluster can't works.

**Comment by KomachiSion** [comment]
No more response from author.
