### ISSUE TITLE
没有接入nacos配置中心本地是正常的，接入后报错

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#8261]
nacos 服务器版本是 NACOS2.1.0-BETA
本地springboot版本是2.1.6.RELEAS
nacos-config-spring-boot-starter版本是0.2.10

 `
Description:

Field executor in .admin.modular.contract.service.impl.ContractServiceImpl required a single bean, but 2 were found:
	- taskExecutor: defined by method 'getAsyncExecutor' in class path resource
	-  [/template/admin/config/AsyncConfig.class]
	- nacosConfigListenerExecutor: a programmatically registered singleton

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

`
以上错误没有接入配置中心的时候是正常的

**Comment by onewe** [comment]
nacos-spring-context 会在启动时注册一个 `ExecutorService` 到 `spring-context` 名字叫做: `nacosConfigListenerExecutor`,如果你项目代码中也存在把 `ExecutorService` 注册到 `spring-context` 中的话,就存在2个类型一样的 bean, 在依赖注入的时候如果不指定 bean 的名称,仅仅使用 bean 类型来注入的话就会出现这个错误.

**Comment by onewe** [comment]
建议使用  `@Qualifier ` 注解来指定需要注入的 bean 的名称

**Comment by nomatterfine** [comment]
> ContractServiceImpl

问题是不光ExecutorService 这个显示有多个，其他的对象例如ContractServiceImpl  也是显示有多个  我试过好几个版本都是这个问题

**Comment by nomatterfine** [comment]
问题是不只ExecutorService 这个显示有多个，其他的对象例如ContractServiceImpl 也是显示有多个 我试过好几个版本都是这个问题
![image](https://user-images.githubusercontent.com/90117583/165300126-42868eb5-d2ee-49ff-bd97-53c1008bce8b.png)

**Comment by nomatterfine** [comment]
发现加了在线程池上加了确实就好了，但是上面的保存显示说有其他bean也有2个，这个咋解释

**Comment by onewe** [comment]
这个错误的意思是: spring 在创建 `ContractServiceImpl `时需要一个单利 `bean`, 但 spring 找到了 2 个bean,分别是:
- taskExecutor, 在 `AsyncConfig ` 类里被定义
- nacosConfigListenerExecutor 以编程的方式被定义

**Comment by nomatterfine** [comment]
感谢！！
