### ISSUE TITLE
v1.4.3创建用户删除用户bug

### ISSUE THREAD

**Issue by selqgun** [alibaba/nacos#8264]
创建用户会无故在我输入的用户名前添加“nacos,”  
![image](https://user-images.githubusercontent.com/3361879/165336283-a520fd2c-7335-4438-a30a-8234ae2aee66.png)
删除其中一个，会说是nacos admin,不能删除  
![image](https://user-images.githubusercontent.com/3361879/165336143-665a24a2-f691-44e1-b153-e7d80f616bb3.png)
已经换了四个浏览器，删除了cookie，依然是这样。

**Comment by onewe** [comment]
1.x 版本的确是有问题, 你可以试一试2.x 版本

**Comment by onewe** [comment]
1.x 的快照版本已经修复了
