### ISSUE TITLE
配置中心怎么读取数组啊

### ISSUE THREAD

**Issue by sandubuhan** [alibaba/nacos#8265]
pom依赖：spring-cloud-starter-alibaba-nacos-discovery，spring-cloud-starter-alibaba-nacos-config，均为2.1.2.RELEASE
JDK1.8
SpringBOOT版本 2.1.8.RELEASE
我是在父子工程中，引入的cloud。
Nacos版本是2.0.4。
我想读取配置中心里的数组，但是尝试了网上的方法，都没有成功。现在的报错是：The elements [xxxx] were left unbound

**Comment by onewe** [comment]
把配置贴出来看看

**Comment by sandubuhan** [comment]
sorry,因为现在我网络的原因，在GitHub上传图片失败，我把在stackOverflow上的提问粘出来，方便的话请帮忙看看，谢谢
https://stackoverflow.com/questions/72022543/nacos-config-cant-read-the-list

**Comment by sandubuhan** [comment]
+ 或者说，有没有已经确定可以使用的读取数组形式的文章，我尝试了很多网上的答案，以及修改过很多次不一样的yml/properties格式，都没成功。

**Comment by onewe** [comment]
其实 读取数组 并不是由 nacos 负责, nacos-client 只是负责把配置拉取下来然后放入到 spring 到environment里,后续操作是由 spring 完成的.
``` java
@Data
@Component
@ConfigurationProperties(prefix = "systems")
public class CustomConfig {
   private List<String> name;
}
```
响应的配置是
``` properties
systems.name[0] = xx
systems.name[1] = xx
```

至于启动报错,这个应该是 nacos 客户端配置不对, 我从你的截图 没有看到 关于 `spring.cloud.nacos.config.extension-configs[2]` 的配置

**Comment by sandubuhan** [comment]
+ 我解决了，确实是我本地格式的原因。你说的不是由nacos负责，体会到了，哈哈。谢谢~

**Comment by onewe** [comment]
@sandubuhan 还有什么问题吗?

**Comment by sandubuhan** [comment]
+ 还是有个问题哈，spring.cloud.nacos.config.file-extension=yaml，这个配置和data-id的后缀有什么关系呢？我本地bootstrap中的file-extension配置的是yaml，然后多配制集中一个data-id是redis.properties，一个是health.yaml,但是两个都能读取

**Comment by sandubuhan** [comment]
没啦，谢谢~

**Comment by andyge2014** [comment]
> 其实 读取数组 并不是由 nacos 负责, nacos-client 只是负责把配置拉取下来然后放入到 spring 到environment里,后续操作是由 spring 完成的.
> 
> ```java
> @Data
> @Component
> @ConfigurationProperties(prefix = "systems")
> public class CustomConfig {
>    private List<String> name;
> }
> ```
> 
> 响应的配置是
> 
> ```ini
> systems.name[0] = xx
> systems.name[1] = xx
> ```
> 
> 至于启动报错,这个应该是 nacos 客户端配置不对, 我从你的截图 没有看到 关于 `spring.cloud.nacos.config.extension-configs[2]` 的配置

这样能读取数组信息，但不能动态读取，即nacos配置页面把该数组内容修改且发布了，本地获取的还是旧的配置，加上@RefreshScope也没有起效，求解
