### ISSUE TITLE
1.4.2，控制台修改/新增配置后，始终有一个节点同步失败

### ISSUE THREAD

**Issue by oupy** [alibaba/nacos#8266]
通过控制台新增/修改
![image](https://user-images.githubusercontent.com/8412102/165421751-8e9c80f0-45a1-42b0-a610-637817c50b9c.png)

三个节点，不在同一网段，都是外网IP
![image](https://user-images.githubusercontent.com/8412102/165421827-21eddd28-9199-4709-bc2a-7b878c7c7913.png)
并且都在application.properties的nacos.inetutils.ip-address配置了本机的外网IP

报错信息
![image](https://user-images.githubusercontent.com/8412102/165421165-08b44eec-0943-4d95-81bb-3d7af7b302cf.png)

后来发现，控制台从哪个节点请求nacos的api，哪个节点就会报这样的错，请问这是bug吗？怎么解决？

**Comment by onewe** [comment]
检查一下 发请求的机器 到 目标机器 8848端口是否是通的
