### ISSUE TITLE
SpringBoot3.0M2搭配Nacos2021.1启动报错，Failed to start bean 'nacosWatch'

### ISSUE THREAD

**Issue by mrtr9** [alibaba/nacos#8278]
SpringBoot3.0M2搭配spring-cloud-starter-alibaba-nacos-discovery2021.1启动不了……
报错：
Failed to start bean 'nacosWatch'; nested exception is java.lang.NullPointerException

**Comment by KomachiSion** [comment]
应该支持不了SpringBoot3.0， nacosWatch应该是SCA的类，建议转issue到SCA社区修复。
