### ISSUE TITLE
nacos 当前是否支持达梦等国产数据库？

### ISSUE THREAD

**Issue by zhengmx1993** [alibaba/nacos#8280]
请问nacos 当前是否支持达梦等国产数据库？
      如果默认是不支持，我看网上有修改原码的方式来支持达梦数据库，但担心它的可靠程度，希望能推荐一篇支持达梦数据库好的文章。

**Comment by KomachiSion** [comment]
只要支持mysql协议的数据库都可以支持。

**Comment by KomachiSion** [comment]
只要支持mysql协议的数据库都可以支持。

**Comment by zhengmx1993** [comment]
支持mysql协议？不大明白是什么意思。

**Comment by quhailong** [comment]
> 支持mysql协议？不大明白是什么意思。

jdbc:mysql://127.0.0.1:3306，这种jdbc后面为mysql的吧，国产直接用内置数据源就行了，不兼容cpu架构的话，需要在各个平台交叉编译rocksdb

**Comment by zhengmx1993** [comment]
感谢回复，之前有点担心如果使用nacos内置数据库，在nacos集群部署方面会不会有问题，现在比较放心了。
![image](https://user-images.githubusercontent.com/41073927/167051511-c9345afb-61a2-499f-981f-ebfff8c2839d.png)
![image](https://user-images.githubusercontent.com/41073927/167051745-0005eb43-cbda-4f99-aeb0-4e9d9ec847e5.png)

**Comment by zhengmx1993** [comment]
感谢[quhailong]回复
