### ISSUE TITLE
单机3节点，使用内置数据源，启动不成功，一直Nacos is starting...

### ISSUE THREAD

**Issue by changs0115** [alibaba/nacos#8288]
单机3节点，使用内置数据源，启动不成功，一直Nacos is starting...
cluster.conf
127.0.0.1:38548
127.0.0.1:38648
127.0.0.1:38748

启动
startup.cmd -p embedded

**Comment by Oliverwqcwrw** [comment]
startup.cmd -p embedded -m cluster 用这个命令试试

**Comment by changs0115** [comment]
startup.cmd -p embedded -m cluster 用这个命令试试
也一样的问题，还是一直Nacos is starting...

**Comment by changs0115** [comment]
> startup.cmd -p embedded -m cluster 用这个命令试试
也一样的问题，还是一直Nacos is starting...

**Comment by Oliverwqcwrw** [comment]
startup.cmd  -m cluster 试试这个

**Comment by changs0115** [comment]
> startup.cmd -m cluster 试试这个
这个命令启动集群应该是要配套mysql数据库的，错误如下，现在就是没有mysql数据库，想启动集群。
 Error creating bean with name 'authFilterRegistration' defined in class path resource [com/alibaba/nacos/core/auth/AuthConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.FilterRegistrationBean]: Factory method 'authFilterRegistration' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilter': Unsatisfied dependency expressed through field 'authManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthManager': Unsatisfied dependency expressed through field 'authenticationManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthConfig': Unsatisfied dependency expressed through field 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosUserDetailsServiceImpl': Unsatisfied dependency expressed through field 'userPersistService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'externalUserPersistServiceImpl': Unsatisfied dependency expressed through field 'persistService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error

**Comment by Oliverwqcwrw** [comment]
你的nacos是哪一个版本

**Comment by changs0115** [comment]
> 你的nacos是哪一个版本
nacos-2.0.3

**Comment by Oliverwqcwrw** [comment]
你这个版本我试了一下是可以成功的

> 2022-05-02 18:36:32,280 INFO Nacos started successfully in cluster mode. use embedded storage

你这种情况可能是选主失败了，可以看一下protocol-raft.log

如果cluster.conf配置没问题，依次启动每一个节点是可以成功的

**Comment by changs0115** [comment]
> 你这个版本我试了一下是可以成功的
> 
> > 2022-05-02 18:36:32,280 INFO Nacos started successfully in cluster mode. use embedded storage
> 
> 你这种情况可能是选主失败了，可以看一下protocol-raft.log
> 
> 如果cluster.conf配置没问题，依次启动每一个节点是可以成功的

2022-05-02 17:20:26,868 ERROR Fail to refresh leader for group : nacos_config, status is : Status[UNKNOWN<-1>: Unknown leader, io.grpc.StatusRuntimeException: UNAVAILABLE: io exception, Unknown leader, Unknown leader]

2022-05-02 17:20:27,148 ERROR Fail to refresh leader for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: Unknown leader, io.grpc.StatusRuntimeException: UNAVAILABLE: io exception, Unknown leader, Unknown leader]

2022-05-02 17:20:28,724 ERROR Fail to refresh route configuration for group : nacos_config, status is : Status[UNKNOWN<-1>: Fail to get leader of group nacos_config]

2022-05-02 17:20:28,725 ERROR Fail to refresh route configuration for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_persistent_service]

**Comment by Oliverwqcwrw** [comment]
把cluster.conf里面的127.0.0.1换成你本机ip试试，然后分别启动三个节点看看

**Comment by changs0115** [comment]
> 把cluster.conf里面的127.0.0.1换成你本机ip试试，然后分别启动三个节点看看
换成本机IP可以了，感谢。
