### ISSUE TITLE
Spring Boot Nacos配置extension-configs中group不生效

### ISSUE THREAD

**Issue by mrtr9** [alibaba/nacos#8289]
Nacos-Config依赖：
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.7.RELEASE</version>
</dependency>

Nacos版本：
2.1.0 环境Windows

Yml配置：
不配置cloud.nacos.config节点下的group，从而配置cloud.nacos.config.extension-configs节点下的group配置无法加载。
注：extension-configs已配置下标

**Comment by onewe** [comment]
贴一下 示例pom 和 配置

**Comment by onewe** [comment]
`bootstrap.yml`
```yaml
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 8b041b2b-497f-4f04-9117-12b0165d57d7
        extension-configs:
          - data-id: 'config.yaml'
            group: 'test2-group'
```

`pom.xml`
```xml
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.12.RELEASE</version>
    </parent>
    
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.7.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
```
我试了一下,并未复现你说的问题

**Comment by mrtr9** [comment]
> `bootstrap.yml`
> 
> ```yaml
> spring:
>   cloud:
>     nacos:
>       config:
>         server-addr: 127.0.0.1:8848
>         namespace: 8b041b2b-497f-4f04-9117-12b0165d57d7
>         extension-configs:
>           - data-id: 'config.yaml'
>             group: 'test2-group'
> ```
> 
> `pom.xml`
> 
> ```
>  <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>2.3.12.RELEASE</version>
>     </parent>
>     
>     <properties>
>         <maven.compiler.source>8</maven.compiler.source>
>         <maven.compiler.target>8</maven.compiler.target>
>     </properties>
>     
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>com.alibaba.cloud</groupId>
>                 <artifactId>spring-cloud-alibaba-dependencies</artifactId>
>                 <version>2.2.7.RELEASE</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>     
>     <dependencies>
>         <dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-web</artifactId>
>         </dependency>
>     </dependencies>
> ```
> 
> 我试了一下,并未复现你说的问题

yml

spring:
  application:
    name: trace-id-cloud-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        namespace: 4ad52e51-e307-4f04-b960-a35351548cdd
        file-extension: yml
        extension-configs:
          - dataId: trace-id-cloud-client
            group: trace-id-cloud-group
            refresh: true

pom

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
        <relativePath/> 
    </parent>
    <groupId>com.tr9</groupId>
    <artifactId>Trace-id-cloud</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Trace-id-cloud</name>
    <description>Trace-id-cloud</description>
    <packaging>pom</packaging>
    <modules>
        <module>Trace-id-cloud-Client</module>
        <module>Trace-id-cloud-Gateway</module>
        <module>Trace-id-cloud-Server_1</module>
        <module>Trace-id-cloud-Server_2</module>
    </modules>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>2021.0.2</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>8.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.10.0</version>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by mrtr9** [comment]
> `bootstrap.yml`
> 
> ```yaml
> spring:
>   cloud:
>     nacos:
>       config:
>         server-addr: 127.0.0.1:8848
>         namespace: 8b041b2b-497f-4f04-9117-12b0165d57d7
>         extension-configs:
>           - data-id: 'config.yaml'
>             group: 'test2-group'
> ```
> 
> `pom.xml`
> 
> ```
>  <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>2.3.12.RELEASE</version>
>     </parent>
>     
>     <properties>
>         <maven.compiler.source>8</maven.compiler.source>
>         <maven.compiler.target>8</maven.compiler.target>
>     </properties>
>     
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>com.alibaba.cloud</groupId>
>                 <artifactId>spring-cloud-alibaba-dependencies</artifactId>
>                 <version>2.2.7.RELEASE</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>     
>     <dependencies>
>         <dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-web</artifactId>
>         </dependency>
>     </dependencies>
> ```
> 
> 我试了一下,并未复现你说的问题

`bootstrap.yml`

`spring:
  application:
    name: trace-id-cloud-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        namespace: 4ad52e51-e307-4f04-b960-a35351548cdd
        file-extension: yml
        extension-configs:
          - dataId: trace-id-cloud-client
            group: trace-id-cloud-group
            refresh: true`

`pom.xml`

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
        <relativePath/> 
    </parent>
    <groupId>com.tr9</groupId>
    <artifactId>Trace-id-cloud</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Trace-id-cloud</name>
    <description>Trace-id-cloud</description>
    <packaging>pom</packaging>
    <modules>
        <module>Trace-id-cloud-Client</module>
        <module>Trace-id-cloud-Gateway</module>
        <module>Trace-id-cloud-Server_1</module>
        <module>Trace-id-cloud-Server_2</module>
    </modules>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>2021.0.2</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>8.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.10.0</version>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>`

**Comment by mrtr9** [comment]
> `bootstrap.yml`
> 
> ```yaml
> spring:
>   cloud:
>     nacos:
>       config:
>         server-addr: 127.0.0.1:8848
>         namespace: 8b041b2b-497f-4f04-9117-12b0165d57d7
>         extension-configs:
>           - data-id: 'config.yaml'
>             group: 'test2-group'
> ```
> 
> `pom.xml`
> 
> ```
>  <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>2.3.12.RELEASE</version>
>     </parent>
>     
>     <properties>
>         <maven.compiler.source>8</maven.compiler.source>
>         <maven.compiler.target>8</maven.compiler.target>
>     </properties>
>     
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>com.alibaba.cloud</groupId>
>                 <artifactId>spring-cloud-alibaba-dependencies</artifactId>
>                 <version>2.2.7.RELEASE</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>     
>     <dependencies>
>         <dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-web</artifactId>
>         </dependency>
>     </dependencies>
> ```
> 
> 我试了一下,并未复现你说的问题

`bootstrap.yml`

```
spring:
  application:
    name: trace-id-cloud-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        namespace: 4ad52e51-e307-4f04-b960-a35351548cdd
        file-extension: yml
        extension-configs:
          - dataId: trace-id-cloud-client
            group: trace-id-cloud-group
            refresh: true
```

`pom.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.tr9</groupId>
    <artifactId>Trace-id-cloud</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Trace-id-cloud</name>
    <description>Trace-id-cloud</description>
    <packaging>pom</packaging>
    <modules>
        <module>Trace-id-cloud-Client</module>
        <module>Trace-id-cloud-Gateway</module>
        <module>Trace-id-cloud-Server_1</module>
        <module>Trace-id-cloud-Server_2</module>
    </modules>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>2021.0.2</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
            <version>8.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.10.0</version>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by onewe** [comment]
@mrtr9 嘿,你的问题应该是没引入`spring-cloud-starter-bootstrap`依赖. 加上这个依赖就正常了. 可以看看[官方文档](https://docs.spring.io/spring-cloud-config/docs/3.1.2/reference/html/#config-first-bootstrap).

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>org.example</groupId>
    <artifactId>issue-8289</artifactId>
    <version>1.0-SNAPSHOT</version>
    
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
    </parent>
    
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2021.0.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.7.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
    </dependencies>

</project>
```

bootstrap.yaml
```yaml
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: f68a9687-5582-4be0-aa5a-b88c5828a5e9
        file-extension: yaml
        extension-configs:
          - data-id: 'config.yaml'
            group: 'test2-group'
```

**Comment by mrtr9** [comment]
> 

我加了这个依赖的，你看清楚点

**Comment by mrtr9** [comment]
> @mrtr9 嘿,你的问题应该是没引入`spring-cloud-starter-bootstrap`依赖. 加上这个依赖就正常了. 可以看看[官方文档](https://docs.spring.io/spring-cloud-config/docs/3.1.2/reference/html/#config-first-bootstrap).
> 
> pom.xml
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0"
>     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
>     
>     <groupId>org.example</groupId>
>     <artifactId>issue-8289</artifactId>
>     <version>1.0-SNAPSHOT</version>
>     
>     <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>2.6.7</version>
>     </parent>
>     
>     <properties>
>         <maven.compiler.source>8</maven.compiler.source>
>         <maven.compiler.target>8</maven.compiler.target>
>     </properties>
>     
>     <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-dependencies</artifactId>
>                 <version>2021.0.2</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>     
>     <dependencies>
>         <dependency>
>             <groupId>com.alibaba.cloud</groupId>
>             <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>             <version>2.2.7.RELEASE</version>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-web</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-cloud-starter-bootstrap</artifactId>
>         </dependency>
>     </dependencies>
> 
> </project>
> ```
> 
> bootstrap.yaml
> 
> ```yaml
> spring:
>   cloud:
>     nacos:
>       config:
>         server-addr: 127.0.0.1:8848
>         namespace: f68a9687-5582-4be0-aa5a-b88c5828a5e9
>         file-extension: yaml
>         extension-configs:
>           - data-id: 'config.yaml'
>             group: 'test2-group'
> ```

我加了这个依赖的，你看清楚点

**Comment by onewe** [comment]
@mrtr9 抱歉看飘了...

**Comment by onewe** [comment]
@mrtr9 问题 我这边复现了,感谢反馈.
