### ISSUE TITLE
Client registration returns a status code of 400

### ISSUE THREAD

**Issue by airstring** [alibaba/nacos#8290]
**Describe the bug**
curl --location --request POST  "172.1.6.89:8848/nacos/v1/ns/instance?accessToken=fyJhbGciOiJIUzI1NiJ9.eyJ4cCI6MTY1MTQxODE0MH0.wsOED_QIeo7mD1G7-SMj0QNjixGd0cI9aAqukmFTAEo&ephemeral=false&enabled=false&ip=172.2.14.73&port=**8332**&serviceName=node.metti&groupName=DEFAULT_GROUP&namespaceId=prod&metadata=metric_port=9104,metric_path=/metrics"
As a result:
{"timestamp":"2022-05-02T13:22:20.747+00:00","status":400,"error":"Bad Request","message":"receive invalid redirect request from peer 172.1.6.89","path":"/nacos/v1/ns/instance"}

When I change port 8332 to 8333，the result is ok！

why port 8332 is wrong?

**Desktop (please complete the following information):**
 - OS: centos
 - Version [nacos-server 2.0.3]

**Comment by KomachiSion** [comment]
your cluster deploy with problem  so that your request transfer to wrong node within distro protocol.
