### ISSUE TITLE
docker下的nacos在新建配置文件时报错，提示：发布失败。请检查参数是否正确。

### ISSUE THREAD

**Issue by liyanzu0926** [alibaba/nacos#8292]
centos环境下

拉取镜像，版本为最新
```dockerfile
docker pull nacos/nacos-server
```
启动nacos容器
```dockerfile
docker run -d \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=xxx.xxx.xxx.xxx \
-e MYSQL_SERVICE_USER=root \
-e MYSQL_SERVICE_PASSWORD=xxx \
-e MYSQL_SERVICE_DB_NAME=nacos_config \
-e JVM_XMS=256m \
-e JVM_XMX=256m \
-e JVM_XMN=256m \
-p 8848:8848 \
--name nacos \
--restart=always \
nacos/nacos-server
```
访问图形界面
```
xxx.xxx.xxx.xxx:8848/nacos
```
在新建配置时提示：**发布失败。请检查参数是否正确。**
而在window环境下同样的配置内容是可以发布成功的，请问是什么原因呢？

**Comment by liyanzu0926** [comment]
问题解决了。我的是mysql8，重新拉取镜像版本为 `v2.1.0-BETA` 就可以了。但为什么默认版本 `latest` 不行呢？
```
docker pull nacos/nacos-server:v2.1.0-BETA
```

**Comment by onewe** [comment]
mysql 中的表有正确初始化吗?

**Comment by liyanzu0926** [comment]
有的，我新建了一条命名空间，查看数据库可以被正常写入。
另外我发现，使用 `latest` 版本网站的图标是橘黄色的，使用 `v2.1.0-BETA` 版本网站图标是浅蓝色的，希望可以帮助你排查问题。

**Comment by onewe** [comment]
@liyanzu0926 橘黄色的图标应该是 1.x 版本, 猜测是前端缓存问题,可以帮忙确认一下吗?

**Comment by liyanzu0926** [comment]
@onewe 我刚刚又重新拉取 `latest` 版本试了一下，发现图标变成蓝色了，显示nacos版本为 `2.0.3` ，但仍然不能新建配置。

**Comment by liyanzu0926** [comment]
数据库连接是正常的，因为新建命名空间是可以正常写入的。

**Comment by onewe** [comment]
不使用数据 使用内置数据源 试一试唉？

**Comment by onewe** [comment]
我这边没复现出来 有点尴尬

**Comment by liyanzu0926** [comment]
@onewe  
嗯...我演示给你看？
腾讯会议：381-037-7787

**Comment by onewe** [comment]
@liyanzu0926 加个微信吧,刚好我今天在摸鱼

**Comment by liyanzu0926** [comment]
可以，我的微信:liguapi666

**Comment by liyanzu0926** [comment]
@onewe

**Comment by liyanzu0926** [comment]
1. 我和上面老哥拉取的 `latest` 版本不一样，原因是我们两用的镜像加速器不同，我用的阿里的，他用的网易的，所以我拉取的 `latest` 是 `2.0.3` ，他拉取的是 `2.1.0` 。
2. 另外，他的 `2.0.3` 版本是没问题的，我的就不能插入配置，猜测可能是 `centos` 系统的原因？？？换成 `ubuntu` 后就没有这个问题。
最后谢谢老哥的帮助 @onewe

**Comment by xyz985211** [comment]
您好，您的MySQL是用docker跑的，还是宿主机上跑的？

**Comment by star362** [comment]
我使用的是v2.0.4 版本的.部署集群的时候也发生这个问题了.mysql 是用docker 部署的 5.7 8.0 版本都试过了还是不好使.我准备使用楼上 **==v2.1.0-BETA==** 版本试试

**Comment by liyanzu0926** [comment]
> 好，您的 MySQL 是您用 docker 跑的，还是您用机器上跑的？

docker上

**Comment by xiaowansheng** [comment]
帮大忙了，阿里云镜像拉取的latest确实是2.0.3，我数据库和其他配置用的一直是2.1版本的配置。
