### ISSUE TITLE
nacos服务器修改节点状态，注册节点自身如何同步？

### ISSUE THREAD

**Issue by johnyannj** [alibaba/nacos#8293]
spring cloud nacos插件，注册到nacos的节点状态默认是health=true
如果nacos服务器把节点改成health=false.

如果节点和nacos之间网络失效一会，heartbeat失败，再重新注册上来，health不又变成了true了吗？

https://github.com/alibaba/spring-cloud-alibaba/issues/2519

**Comment by onewe** [comment]
变回 true 有什么问题吗？？

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/open-api.html

修改配置的openAPI中有一定的说明。

**Comment by johnyannj** [comment]
@onewe  一个微服务实例，出问题了，我想在nacos管理面上把他设置health为false，如果再被变回true，那不白设置了吗。

**Comment by KomachiSion** [comment]
> @onewe 一个微服务实例，出问题了，我想在nacos管理面上把他设置health为false，如果再被变回true，那不白设置了吗。

1.X版本是这样的， 临时实例被彻底移除时会把元数据（上下线状态，权重）一起删除，再重新注册回来的时候会根据重新注册的信息为准。

2.X会保留元数据一段时间，在保留期间注册回来会继续使用之前的元数据。

> https://nacos.io/zh-cn/docs/open-api.html
> 
> 修改配置的openAPI中有一定的说明。

**Comment by KomachiSion** [comment]
No more response from author.
