### ISSUE TITLE
nacos 2.1.0控制台默认用户名和密码无法登录，同时日志有大量java.lang.IllegalArgumentException: RowMapper is required报错

### ISSUE THREAD

**Issue by wanyy15083** [alibaba/nacos#8295]
部署包：nacos-server-2.1.0.tar.gz
报错：2022-05-05 14:36:14,940 ERROR There was an error querying the data, request : SelectRequest{queryType=3, sql='SELECT username,password FROM users WHERE  1=1  OFFSET 0 ROWS FETCH NEXT 2147483647 ROWS ONLY', args=[], className='com.alibaba.nacos.plugin.auth.impl.persistence.AuthRowMapperManager.UserRowMapper'}, error : java.lang.IllegalArgumentException: RowMapper is required

方法：com.alibaba.nacos.config.server.service.repository.RowMapperManager#registerRowMapper
可能解决方案：注册增加put rowMapper动作

  public static synchronized <D> void registerRowMapper(String classFullName, RowMapper<D> rowMapper) {
        if (mapperMap.containsKey(classFullName)) {
            LogUtil.DEFAULT_LOG.warn("row mapper {} conflicts, {} will be replaced by {}", classFullName,
                    mapperMap.get(classFullName).getClass().getCanonicalName(),
                    rowMapper.getClass().getCanonicalName());
        }
        mapperMap.put(classFullName, rowMapper);
    }

**Comment by onewe** [comment]
用的 mysql ?

**Comment by onewe** [comment]
@i will resolve it@

**Comment by wanyy15083** [comment]
不是，emble

**Comment by realJackSun** [comment]
@onewe 这个你能复现出来吗？

**Comment by onewe** [comment]
应该能, 昨天大概看了一下, 还没来得及复现. 下午试一试.

**Comment by onewe** [comment]
复现步骤:
- 开启认证
- 使用内嵌数据源
- 使用集群模式
- 无法登录

![image](https://user-images.githubusercontent.com/38708836/167235587-9e7b4efd-6b71-4b71-99fc-16e3c0b5c365.png)

**Comment by jackey35** [comment]
2.1.0发布的版本解决这个问题了吗？

**Comment by xiaobin-zhang** [comment]
2.3.0 版本集群使用内置数据库也出现了: `caused: errCode: 500, errMsg: com.alibaba.nacos.persistence.exception.NJdbcException: IllegalArgumentException:RowMapper is required `

**Comment by 6LWa6ZKx** [comment]
> 2.3.0 版本集群使用内置数据库也出现了: `caused: errCode: 500, errMsg: com.alibaba.nacos.persistence.exception.NJdbcException: IllegalArgumentException:RowMapper is required `

同样出现了，而且配置mysql就能登录，然后停掉mysql也能正常操作。

人都搞蒙了。
