### ISSUE TITLE
The cluster data is not synchronized

### ISSUE THREAD

**Issue by wonkp** [alibaba/nacos#8296]
nacos2.0.3集群服务实例数据不同步，3个节点的集群，关闭一个节点，注册永久实例，重新启动节点后，各个节点服务列表数据不一致

nacos2.0.3 Cluster service instance data is not synchronized, a cluster of 3 nodes, shut down a node, register a permanent instance, restart the node, the data of the service list of each node is inconsistent

![企业微信截图_16517437244219](https://user-images.githubusercontent.com/104979297/166898622-90c741f1-6c09-4872-9d61-b677de652cec.png)

![企业微信截图_16517438431626](https://user-images.githubusercontent.com/104979297/166898953-f62105ca-2610-4bae-bb30-b0dc91a61758.png)

![企业微信截图_1651743862857](https://user-images.githubusercontent.com/104979297/166899007-7d681c1f-2eb9-4e02-bf33-612e0cfbe99b.png)

![企业微信截图_16517438935931](https://user-images.githubusercontent.com/104979297/166899100-ca37f71b-66e0-4a35-a985-a7b704761eba.png)

**Comment by wonkp** [comment]
在2健康节点和1失败节点的时候，注册服务，重启后各节点显示的数据不一致

**Comment by KomachiSion** [comment]
1. 持久化服务应该走的是raft协议，您给的日志是distro协议的，可能是注册方式有问题，或者再看看raft相关日志寻找原因。
2. 看distro协议的日志，集群同步还是通过旧模式进行同步，说明集群搭建应该有问题，没有升级成功，如果是首次搭建集群，建议直接关闭双写，最好直接使用2.1.0版本，该版本默认不会从旧版本进行升级。

**Comment by wonkp** [comment]
[
![企业微信截图_16524542911117](https://user-images.githubusercontent.com/104979297/168312834-448b59f7-8b3e-49e0-90ee-c1357a22a8df.png)
](url)

**Comment by wonkp** [comment]
docker集群搭建，按照官网说明，不太清除为什么升级失败，我关闭双写再测试下看看吧

**Comment by wonkp** [comment]
[
![企业微信截图_16528387866141](https://user-images.githubusercontent.com/104979297/168941010-9e8b6e47-4611-442b-8db6-3c92167b31e3.png)
](url)

**Comment by wonkp** [comment]
naming_persistent_service_v2我觉得这个元数据不对，可是我又没有配置这个ip

**Comment by wonkp** [comment]
应该是data下面的文件导致了同步异常，集群部署的问题，把data文件夹下面所有文件删除后重新部署问题解决

**Comment by warriorSL2016** [comment]
> 后重新部署问题解决

删除data目录会导致数据丢失吗
