### ISSUE TITLE
nacos 2.0服务端能查看连接的客户端版本吗

### ISSUE THREAD

**Issue by whl12345** [alibaba/nacos#8297]
目前已完成Nacos服务端升级后续会推动各业务客户端升级，想要通过服务端集群感知到连接的各业务客户端版本使用情况，方便未升级完成业务的客户端升级

**Comment by realJackSun** [comment]
暂时还不行，但是下个版本或者下下版本会支持。

**Comment by KomachiSion** [comment]
Combine to #8857
