### ISSUE TITLE
服务启动出现java.lang.NoClassDefFoundError: com/alibaba/nacos/common/utils/StringUtils

### ISSUE THREAD

**Issue by shining-stars-lk** [alibaba/nacos#8300]
使用nacos的服务注册功能，在启动项目时出现java.lang.NoClassDefFoundError: com/alibaba/nacos/common/utils/StringUtils
![image](https://user-images.githubusercontent.com/40255310/167119165-97bb3b53-d0ba-4d09-a0ba-cfecde95df9e.png)

版本
springboot 2.3.12.RELEASE
springcloud Hoxton.SR12
spring-cloud-starter-alibaba-nacos-discovery 2.2.7.RELEASE

**Comment by Oliverwqcwrw** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/31796988/167228547-0f2e10ad-a12a-4ac5-bb75-b27f8482200b.png">
咱两的目录为什么不一样？

**Comment by shining-stars-lk** [comment]
找到原因了。
在将nacos-2.0.3的源码项目执行 mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U时，nacos-client模块的包会
打入本地的maven仓库中。
这时我的服务启动时，spring-cloud-starter-alibaba-nacos-discovery中引用的nacos-client就是刚才打入的包了。这里面没有
com.alibaba.nacos.common包。
但是这样我只能将确实的common放入到源码项目中。 除了这么处理外还有比较好的处理方式吗
![image](https://user-images.githubusercontent.com/40255310/167333667-54e3c20c-dd6a-48e0-85cd-269c5f12edb6.png)

**Comment by KomachiSion** [comment]
nacos-client会自动依赖引入nacos-common，包冲突和依赖问题需要您自行解决。

**Comment by A-YANGSK** [comment]
<img width="1276" height="221" alt="Image" src="https://github.com/user-attachments/assets/daa64c03-3e4d-4adb-8261-b46d91a93c0b" />

<img width="497" height="306" alt="Image" src="https://github.com/user-attachments/assets/1f266f6d-43df-4045-9319-9d93609a2c26" />怎么解决的？大佬们  求助  两天了还没运行起来
