### ISSUE TITLE
请教 , nacos可以配置连接多个命名空间下的配置文件吗

### ISSUE THREAD

**Issue by zhangwang3611** [alibaba/nacos#8302]
如题 , nacos可以配置连接多个命名空间下的配置文件吗? 或者说 我现在有两套nacos的服务端 , 一个客户端可以同时配置连接这两套nacos服务吗? 感谢回答.

**Comment by onewe** [comment]
目前应该不行. @hujun-w-2

**Comment by hujun-w-2** [comment]
可以使用原生的nacos-client实现

**Comment by zhangwang3611** [comment]
> 可以使用原生的nacos-client实现

请问有具体的实现方式实例吗? 感谢

**Comment by hujun-w-2** [comment]
https://github.com/alibaba/nacos/tree/develop/example

**Comment by zhangwang3611** [comment]
> https://github.com/alibaba/nacos/tree/develop/example

感谢感谢

**Comment by KomachiSion** [comment]
1个client实例只能连接一个命名空间，命名空间是强隔离，如果需要一个进程连接多个命名空间，需要自行创建多个client实例。
