### ISSUE TITLE
com.alibaba.nacos.api.exception.NacosException: dataId invalid

### ISSUE THREAD

**Issue by thinkerFenglm** [alibaba/nacos#8303]
**Describe the bug**
mcs:
  jdbc: mysql
spring:
  profiles:
    active: ${mcs.jdbc},decision

get data from Nacos error,dataId:mcs-cim-${mcs.jdbc}.yaml, 
com.alibaba.nacos.api.exception.NacosException: dataId invalid

**Expected behavior**
dataId:mcs-cim-mysql.yaml

**Acutally behavior**
dataId:mcs-cim-${mcs.jdbc}.yaml

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: windos 10
 - Version [nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [client]
 - SDK dubbo 2.7.14 springboot 2.1.2.RELEASE

**Additional context**

**Comment by onewe** [comment]
这个是属于变量替换 没生效. 只能检查一下你本地环境 排查一下 是 maven 的变量替换没生效 还是说运行过程中 变量替换没生效

**Comment by thinkerFenglm** [comment]
> 这个是属于变量替换 没生效. 只能检查一下你本地环境 排查一下 是 maven 的变量替换没生效 还是说运行过程中 变量替换没生效

profile变量替换这个是springboot2.4.0 以下的bug，会同时有替换和未替换的profile及${mcs.jdbc}、mysql，导致nacos通过profile组装dataId时，会有mcs-cim-mysql.yaml，mcs-cim-${mcs.jdbc}.yaml 这两种

**Comment by sunqb** [comment]
yes when you refresh project's maven ，it is ok。
