### ISSUE TITLE
nacos2.0.3版本控制台下线操作bug

### ISSUE THREAD

**Issue by ITdawang** [alibaba/nacos#8305]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
描述：nacos集群控制台提供下线操作：导致除过本服务器的其他服务器集群cluster列表中下线点击ip,集群处在不正常状态，没有提供上线功能，重启nacos集群导致因为配置不一致，无法完成集群选举。
------
Describe: The nacos cluster console provides offline operation: the cluster is in an abnormal state and does not provide online function. The restart of the nacos cluster causes that the cluster election cannot be completed due to inconsistent configurations.

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/36129423/167237474-89ce8e15-e200-47d9-9b40-1845805318c8.png)
![image](https://user-images.githubusercontent.com/36129423/167237494-9b4cb3df-ade2-4552-ad03-5b8f155c8078.png)

**Comment by onewe** [comment]
@KomachiSion 是不是要提供一个上线的功能会好点?

**Comment by KomachiSion** [comment]
我觉得还是先把下线操作取消掉吧， 这个功能是社区自行添加的，感觉现在问题很多，先去掉然后重新设计吧。

**Comment by q494165244** [comment]
可以看下元数据，大概率是脑裂。我的2.0.4就是脑裂，重新认下主就好了。

**Comment by wangdongyun** [comment]
> 我觉得还是先把下线操作取消掉吧， 这个功能是社区自行添加的，感觉现在问题很多，先去掉然后重新设计吧。

我也这么觉得
