### ISSUE TITLE
[Summer 2022] Nacos支持从K8S服务发现中同步服务元数据。

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#8309]
# Nacos支持从K8S服务发现中同步服务元数据

Nacos支持实时感知K8S的服务上下线信息，并获取其服务元数据，并将这些信息同步到Nacos的CMDB模块。最终效果为，用户通过Nacos标签查询接口指定标签条件，即可查询到满足要求的实例列表。

**Comment by xjlgod** [comment]
您好，我是在校学生，去年也参加过summer2021并成功结题。我想问下此issue中的感知K8S的服务上下线信息，是指的用户选择Nacos中的服务，然后通过api-server的接口来查询这些服务元数据吗？谢谢您的回答。

**Comment by li-xiao-shuang** [comment]
> 您好，我是在校学生，去年也参加过summer2021并成功结题。我想问下此issue中的感知K8S的服务上下线信息，是指的用户选择Nacos中的服务，然后通过api-server的接口来查询这些服务元数据吗？谢谢您的回答。

可以通过开源之夏官网联系对应的导师沟通

**Comment by xjlgod** [comment]
> 

嗯嗯好的，谢谢您
