### ISSUE TITLE
[Summer 2022] Make Nacos support DNS protocol.

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#8311]
# Nacos-CoreDNS模块支持以长连接访问Nacos服务端
当前Nacos-CoreDNS模块只支持以短连接方式访问Nacos服务端，本题目致力于让该模块支持以gRPC连接Nacos服务端。

**Comment by shubham-cmyk** [comment]
Hello, I am interested in project "_The Nacos-CoreDNS module now only supports accessing the Nacos server through short connections. This topic is dedicated to making the module support connecting to the Nacos server through gRPC."_

I want to get started and as a experience I am familiar with golang and gRPC.

**Comment by shubham-cmyk** [comment]
@JianweiWang Sorry for contacting you over Github but I was not able to locate your username on the Gitter. 

Hello sir, I am interested in the project and familiar with the golang and gRPC based plugin. I need your guidance to contribute in   _"The Nacos-CoreDNS module now only supports accessing the Nacos server through short connections. This topic is dedicated to making the module support connecting to the Nacos server through gRPC."_
