### ISSUE TITLE
[Summer 2022] Nacos多数据源插件化建设

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#8312]
# Background
The current configuration center module of Nacos is not perfect for the ability to access multiple data sources. With the growing voice of the community, we need to improve the plug-ins that support multiple data sources in Nacos. The existing SQL operations are abstracted from the SPI interface, and the implementation of Mysql is provided, and the existing SQL operations are transformed to support plug-in.

# Target
Nacos configuration management includes many SQL statements, and currently only the implementation of the MySQL version is provided. This project is dedicated to building plug-ins that generate corresponding SQL for multiple data sources (including databases such as MySQL, Oracle, etc.).

# Difficulty

*Basic*

# Mentor

@li-xiao-shuang 
644968328@qq.com

# Output Requirements
- Sort out the SQL operations of the Nacos configuration management module, and abstract a set of SPI interfaces that are easy to expand;
- Convert existing configuration management SQL operations into pluggables using appropriate design patterns;
- Provide sound design documentation and add unit tests;

# Technical Requirements
- Learn about SQL;
- Familiar with Java;
- Learn about Nacos;
- Those who love open source, have perseverance, and have the ability to learn by themselves can ignore the above points;

----------------

# 背景
Nacos 目前的配置中心模块对于接入多数据源的能力是不完善的，随着社区的呼声越来越高，我们需要完善Nacos 支持多数据源的插件。将现有的 SQL 操作抽象出 SPI 接口，并提供Mysql 的实现，改造现有的 SQL 操作，让它支持插件化。

# 目标
Nacos配置管理中包括许多SQL语句，目前只提供了MySQL版本的实现。该项目致力于构建多数据源的相应SQL（包括MySQL、Oracle等数据库）生成的插件。

# 难度

*基础*

# 导师

@li-xiao-shuang 
644968328@qq.com

# 产出要求
- 梳理Nacos配置管理模块的SQL操作，抽象出一套易于扩展的SPI接口；
- 使用合适的设计模式将现有的配置管理SQL操作转化为插件化;
- 提供完善的设计文档，并添加单元测试;

# 能力要求
- 了解 SQL；
- 熟悉 Java；
- 了解 Nacos；
- 热爱开源、有毅力、有自学能力的人可以忽略以上几点；

**Comment by The-Gamer-01** [comment]
将现有的 SQL 操作抽象出 SPI 接口，现有的SQL操作指的是配置中心模块里面的源码中的SQL部分吗

**Comment by li-xiao-shuang** [comment]
> 将现有的 SQL 操作抽象出 SPI 接口，现有的SQL操作指的是配置中心模块里面的源码中的SQL部分吗

嗯 是的 可以先看配置中心模块的

**Comment by presenth7s** [comment]
请问这个可以怎么参与呢？

**Comment by li-xiao-shuang** [comment]
> 请问这个可以怎么参与呢？

需要是在校生，如果是的话联系我就行

**Comment by The-Gamer-01** [comment]
> 请问这个可以怎么参与呢？

去搜一下开源之夏，里面有详细介绍什么的，需要是在校生，申请参加的

**Comment by lrh15983478476** [comment]
我是在校大学生，可以参加该项目吗 @li-xiao-shuang

**Comment by li-xiao-shuang** [comment]
> 我是在校大学生，可以参加该项目吗 @li-xiao-shuang

可以的  你对多数据感兴趣？

**Comment by lrh15983478476** [comment]
> > 我是在校大学生，可以参加该项目吗 @li-xiao-shuang
> 
> 可以的 你对多数据感兴趣？

感兴趣，具体怎么参与呢？

**Comment by li-xiao-shuang** [comment]
> > > 我是在校大学生，可以参加该项目吗 @li-xiao-shuang
> > 
> > 
> > 可以的 你对多数据感兴趣？
> 
> 感兴趣，具体怎么参与呢？

参考 开源之夏官网 的指南  https://summer-ospp.ac.cn/，需要编写申请书，不明白的在我主页添加联系方式交流

**Comment by lrh15983478476** [comment]
> > > > 我是在校大学生，可以参加该项目吗 @li-xiao-shuang
> > > 
> > > 
> > > 可以的 你对多数据感兴趣？
> > 
> > 
> > 感兴趣，具体怎么参与呢？
> 
> 参考 开源之夏官网 的指南 [https://summer-ospp.ac.cn/，需要编写申请书，不明白的在我主页添加联系方式交流](https://summer-ospp.ac.cn/%EF%BC%8C%E9%9C%80%E8%A6%81%E7%BC%96%E5%86%99%E7%94%B3%E8%AF%B7%E4%B9%A6%EF%BC%8C%E4%B8%8D%E6%98%8E%E7%99%BD%E7%9A%84%E5%9C%A8%E6%88%91%E4%B8%BB%E9%A1%B5%E6%B7%BB%E5%8A%A0%E8%81%94%E7%B3%BB%E6%96%B9%E5%BC%8F%E4%BA%A4%E6%B5%81)

项目的项目id怎么看呀？

**Comment by zhangsilence** [comment]
请问这个建设目前建设完了么，有没有release或者rc可以使用

**Comment by wuchubuzai2018** [comment]
一个B端工作的Java开发者路过，我的工作是BI行业，做过BI系统的多数据源，对Nacos支持多数据源感兴趣，可以参与开发吗

**Comment by The-Gamer-01** [comment]
> 

这个是一个比赛的issue，是专门给在校学生参加用的，暂时不面向其他的朋友；朋友你可以看看其他的issue的
