### ISSUE TITLE
[Summer 2022] Nacos service mesh ecological construction and optimization Nacos服务网格生态建设与优化

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#8313]
# Nacos服务网格生态建设与优化
目前Nacos已经与服务网格的标准Istio完成了基本集成工作。该课题致力于完善与优化服务网格生态，完成Nacos支持统一数据面协议(XDS协议），优化Nacos与Istio之间的节点增量推送，进一步提升Nacos在服务网格生态中的地位。

**Comment by chuntaojun** [comment]
if not one assign, can i try it ?
