### ISSUE TITLE
客户端在收到服务端ConnectResetRequest后可能会造成瞬时单节点高网络负载

### ISSUE THREAD

**Issue by lpaz010** [alibaba/nacos#8317]
**Is your feature request related to a problem? Please describe.**

在RpcClient#reconnect(final ServerInfo recommendServerInfo, boolean onRequestFail)：
```
serverInfo = recommendServer.get() == null ? nextRpcServer() : recommendServer.get();
```
当客户端在收到服务端`ConnectResetRequest`后，服务端没有recommendServerInfo时，默认会去连接下一个服务端（如上代码段），极端情况时，当前服务端所有长连接客户端都去连接同一个服务端，会不会造成这个单服务端节点瞬时高网络负载？所以，排除当前已连接服务端，随机选取剩下的其他服务端地址？
> 比如： server1有10个客户端，server2有10客户端，server3有10客户端，连接重置后变成server1有0个客户端，server2有20个，server3有10个客户端的情形。

**Describe the solution you'd like**
在**客户端侧**实现：排除当前故障服务端并随机选取一个服务端地址，在接口`ServerListFactory`中增加`default String genNextServer(String currentServer);`
```
public interface ServerListFactory {
    
     ...

    /**
     * switch to a new random server except currentServer.
     *
     * @param currentServer current server
     * @return server "ip:port".
     */
    default String getNextServer(String currentServer);

    ... 
}
```
在ConnectResetRequestHandler#requestReply中调用
```
// switchServerAsync();
String currentServer = getServerListFactory().getCurrentServer();
String nextRandomServer = getServerListFactory().getNextServer(currentServer);
switchServerAsync(resolveServerInfo(nextRandomServer ), false);
```

**Describe alternatives you've considered**
暂无

**Additional context**
暂无

**Comment by KomachiSion** [comment]
So you want to use random server but not next server?

**Comment by lpaz010** [comment]
1. **补充说明**：
10个客户端中的`ServerListManager`地址列表在初始化时做了随机选取index，若10个客户端同时连接到server1，那么10个客户端next server都是相同一个，如下：
```
currentIndex.set(new Random().nextInt(serverList.size()));
```

2. 另外一种**低的改变解决方式**：
在初始化服务端地址列表时，把地址列表顺序打乱，如下：
```
if (!serverList.isEmpty()) {
    // 新增java.util.Collections#shuffle来打乱默认的排序
    Collections.shuffle(serverList);
    currentIndex.set(new Random().nextInt(serverList.size()));
} else {
    throw new NacosLoadException("serverList is empty,please check configuration");
}
```
然后ServerListManager#getServerListFromEndpoint在返回前同样shuffle处理一下就好了。
@KomachiSion 不知道这样可以吗？这样改动小一些。

**Comment by KomachiSion** [comment]
问题本质就是负载均衡算法，目前nacos仅有轮询负载，一台台顺序尝试，

上述的修改方式都是彻底随机，虽然可能可以解决你提出的问题，但是也可能造成随机一直随到有问题的节点上。
我认为最好的方法还是做成可选择的，使用的时候根据需求选择，默认可以保持现在的轮询。

编程之夏刚好有个课题就是做`ServerListManager`相关的，可以考虑进去。

https://github.com/alibaba/nacos/issues/8310

**Comment by lpaz010** [comment]
好的，谢谢杨老师！
