### ISSUE TITLE
Can NamingService be obtained by non-annotation?

### ISSUE THREAD

**Issue by hengboy** [alibaba/nacos#832]
可以通过非注解的手段获取NamingService实例吗？我需要封装nacos作为一种服务注册方式，需要使用NamingService实例

**Comment by paderlol** [comment]
请问是要完全自己实例化一个NamingService吗?

**Comment by hengboy** [comment]
@paderlol 是的，可以通过什么方式呢？还有另外一个问题需要麻烦，Instance的元数据该怎么更新？

**Comment by paderlol** [comment]
如果需要自己创建可以通过NamingFactory。Instance里面有metadata可以更新元数据

**Comment by hengboy** [comment]
@paderlol Instance通过具体哪个方法更新元数据？我尝试了更新后，再次通过ServiceName获取Instance后仍然是之前的内容。

**Comment by paderlol** [comment]
请问你怎么更新的，能说下吗？

**Comment by hengboy** [comment]
![image](https://user-images.githubusercontent.com/39233436/53458955-fc97cb80-3a72-11e9-8beb-0348182d4922.png)

getInstanceByName()方法用于根据InstanceId匹配参数InstanceName来获取Instance实例。

再次通过namingService.getAllInstances()方法获取其中一个Instance时meta元数据还是之前的，并没有变化

**Comment by hengboy** [comment]
这是我元数据的内容：
"metadata": {
"lastHeartBeatMilliseconds": "1551169052382",
"loadBalanceWeight": "1",
"instanceAddress": "192.168.1.54:8085",
"instanceName": "192.168.1.54:8085",
"httpPort": "8085",
"jobKeys": "[\"testJob\"]",
"instanceType": "CONSUMER",
"ipAddress": "192.168.1.54",
"loadBalanceStrategy": "POLL_WEIGHT",
"instanceStatus": "UP"
}
我通过lastHeartBeatMilliseconds来确定节点是否有效，是否需要剔除，因此心跳检查一次就会更新一次这个元数据的内容

**Comment by paderlol** [comment]
你更新元数据后要重新push这个instance

**Comment by hengboy** [comment]
要通过具体哪个方法进行push？重新注册码？我现在都是通过namingService实例来进行操作的Instance

**Comment by paderlol** [comment]
对，重新register

**Comment by hengboy** [comment]
nacos内部会自动更新对应的数据？并不会重新注册吧？

**Comment by hengboy** [comment]
能加下微信吗？我微信：yuqiyu999，感谢

**Comment by hengboy** [comment]
我发现一个问题，我通过重新注册来更新元数据后好像并没有起到作用。
我新建了另外一个项目来查看Instance的元数据则还是更新之前的
而且在~/nacos/naming/default/serviceName文件名 文件内也并没有更新
```
{
    "metadata": { }, 
    "dom": "micro-job-schedule", 
    "cacheMillis": 10000, 
    "useSpecifiedURL": false, 
    "hosts": [
        {
            "valid": true, 
            "marked": false, 
            "metadata": {
                "lastHeartBeatMilliseconds": "1551235849105", 
                "loadBalanceWeight": "1", 
                "instanceAddress": "192.168.1.54:8080", 
                "instanceName": "192.168.1.54:8080", 
                "httpPort": "8080", 
                "instanceType": "SCHEDULE", 
                "ipAddress": "192.168.1.54", 
                "loadBalanceStrategy": "POLL_WEIGHT", 
                "instanceStatus": "UP"
            }, 
            "instanceId": "192.168.1.54#8080#{\"defaultCheckPort\":80,\"defaultPort\":80,\"healthChecker\":{\"type\":\"TCP\"},\"metadata\":{},\"name\":\"\",\"useIPPort4Check\":true}#micro-job-schedule", 
            "port": 8080, 
            "ip": "192.168.1.54", 
            "clusterName": "{\"defaultCheckPort\":80,\"defaultPort\":80,\"healthChecker\":{\"type\":\"TCP\"},\"metadata\":{},\"name\":\"\",\"useIPPort4Check\":true}", 
            "weight": 1, 
            "serviceName": "micro-job-schedule", 
            "enabled": true
        }
    ], 
    "checksum": "604f41e60969aae119f9b935f7b294511551236814818", 
    "lastRefTime": 1551236814818, 
    "env": "", 
    "clusters": ""
}
```
在上面`instanceStatus`字段应该是`DOWN`才对。
在非新建项目内获取该Instance的元数据是已经更新的，内容如下：
![image](https://user-images.githubusercontent.com/39233436/53462951-7aae9f00-3a80-11e9-8166-1a7f30f52bfc.png)
