### ISSUE TITLE
sofaboot3.4.1,springboot2.1.7.RELEASE连接nacos2.0.3抛出java.net.UnKnownHostException: http

### ISSUE THREAD

**Issue by Morton-Freer** [alibaba/nacos#8323]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Oliverwqcwrw** [comment]
Can you provide more exception information

**Comment by Morton-Freer** [comment]
![image](https://user-images.githubusercontent.com/82444336/167521616-0e675e9c-6405-495d-8c72-270d831722ef.png)
![image](https://user-images.githubusercontent.com/82444336/167521643-024b72c5-d0c4-4a11-b4ad-f218c430e611.png)

This is an inexplicable error thrown by my project dependencies and the console.


Remove the dependency of sofa, the project starts normally, and the nacos link works normally.

**Comment by KomachiSion** [comment]
`java.net.UnKnownHostException: http `

your config must be wrong, the exception is mean your set the nacos server address is `http`

**Comment by Morton-Freer** [comment]
> `java.net.UnKnownHostException: http `
> 
> your config must be wrong, the exception is mean your set the nacos server address is `http`
My address can be resolved normally
