### ISSUE TITLE
LocalConfigInfoProcessor  seem doesn't work correctly

### ISSUE THREAD

**Issue by Sivyer9303** [alibaba/nacos#8327]
**Describe the bug**
LocalConfigInfoProcessor is the class for store config to local file.
But does the method 'getFailover' work?I cant find where to write the content to file. Only the read operation found.
I also cant find the failover file after running application with nacos-spring almost one year.
So.is it deprecated or this is a bug?

**Expected behavior**
use the failover file correctly.

**Acutally behavior**
It seem useless.

**How to Reproduce**
run nacos application and watch the failover operation.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by Oliverwqcwrw** [comment]
`com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor#saveSnapshot`

This is the write operation

**Comment by Sivyer9303** [comment]
> `com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor#saveSnapshot`
> 
> This is the write operation

This is the operation for snapshot,not of failover

**Comment by KomachiSion** [comment]
failover will not operated by program. failover is a way for emergency problem that server is down and client `must` change config situation.

the snapshot is the common auto `failover` for program.

**Comment by Sivyer9303** [comment]
> failover will not operated by program. failover is a way for emergency problem that server is down and client `must` change config situation.
> 
> the snapshot is the common auto `failover` for program.

Thx for reply.But it seem is awkward...
