### ISSUE TITLE
缺少类

### ISSUE THREAD

**Issue by sampou** [alibaba/nacos#8329]
**Describe the bug**
The following three classes are missing from the project:

import com.alibaba.nacos.consistency.entity.ReadRequest;
import com.alibaba.nacos.consistency.entity.Response;
import com.alibaba.nacos.consistency.entity.WriteRequest;

eg:
[https://github.com/alibaba/nacos/blob/develop/consistency/src/main/java/com/alibaba/nacos/consistency/ConsistencyProtocol.java](url)

**Desktop (please complete the following information):**
 - Version [e.g. nacos-server 2.0.4]

**Comment by js20166098** [comment]
这个清理一下缓存重新编译可能是编译问题，这个类实际是通过
consistency/src/main/proto/consistency.proto编译生成的 和dubbo的RepayRequest存在相同的问题

**Comment by brotherlu-xcq** [comment]
refer https://nacos.io/zh-cn/docs/faq.html#3.19

**Comment by iRnight** [comment]
这个通过protobuf插件编译一下就行，这三个类是通过proto包中的三个proto文件编译产生的
