### ISSUE TITLE
nacos2.0.4 PoolThreadCache 内存泄露

### ISSUE THREAD

**Issue by jasonpyf** [alibaba/nacos#8336]
![1652167900885_52E5BF7E-9753-48e5-80F2-861AFEB7252D](https://user-images.githubusercontent.com/16953632/167574008-ca8c0e19-3f36-4c4b-bcfb-71640ab23c54.png)
![1652168063316_3BE4765B-9398-47b0-B4EE-D58D0B65EBB9](https://user-images.githubusercontent.com/16953632/167574205-86be43c8-c890-4a28-afa0-486f030d313d.png)

**Comment by jasonpyf** [comment]
215 instances of “com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache”, loaded by “org.springframework.boot.loader.LaunchedURLClassLoader @ 0xa001c9c0” occupy 42,104,032 (25.34%) bytes. 

Keywords
com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.buffer.PoolThreadCache
org.springframework.boot.loader.LaunchedURLClassLoader @ 0xa001c9c0

**Comment by KomachiSion** [comment]
42M buffer will leak your memory？ I think you should change your memory setting, or check your network whether work well.

**Comment by gefufeng** [comment]
我也碰到相同的问题了：
![image](https://user-images.githubusercontent.com/9637787/176603264-07d5bbff-4314-496e-a7b2-a9a71a447324.png)

**Comment by xinyuexinyan** [comment]
> 我也碰到相同的问题了： ![image](https://user-images.githubusercontent.com/9637787/176603264-07d5bbff-4314-496e-a7b2-a9a71a447324.png)

如何解决的

**Comment by lxqgithub** [comment]
how ti fix it ?

**Comment by PresidentNAN** [comment]
俺 也一样

**Comment by Panyulong9527** [comment]
1.4.2 的客户端 2.2.2 的服务端 碰到一样的问题

**Comment by Panyulong9527** [comment]
![Uploading image.png…]()

**Comment by Panyulong9527** [comment]
![screenshot-20240123-162028](https://github.com/alibaba/nacos/assets/46114652/0f7050c6-a668-4f3d-8838-28ce560ff35f)
