### ISSUE TITLE
请问nacos是否支持webhook功能?

### ISSUE THREAD

**Issue by XzBuleSky** [alibaba/nacos#8338]
你好! 

  当nacos配置中心的配置被修改后, 无法通过有效的手段来知道变更消息.   当出现未知修改或漏改情况会导致严重的生产事故.

  如果nacos能支持webhook功能,    我这边实现webhook接收器, 将配置修改的消息通知到对应人/群组,  就能尽量避免故障发生.

**Comment by li-xiao-shuang** [comment]
> 你好!
> 
> 当nacos配置中心的配置被修改后, 无法通过有效的手段来知道变更消息. 当出现未知修改或漏改情况会导致严重的生产事故.
> 
> 如果nacos能支持webhook功能, 我这边实现webhook接收器, 将配置修改的消息通知到对应人/群组, 就能尽量避免故障发生.

配置监听的接口不能够满足你的需求嘛？

**Comment by Oliverwqcwrw** [comment]
Hello @XzBuleSky ,
这个是关于监听配置的文档[Java SDK](https://nacos.io/zh-cn/docs/sdk.html),看一下是否对你有帮助

**Comment by KomachiSion** [comment]
No more response from author.
