### ISSUE TITLE
Nacos connection expired

### ISSUE THREAD

**Issue by 13539956066** [alibaba/nacos#834]
服务一直在运行，但是客户端连接后大概一两个钟后会提示下如错误

[root@k8smanager ~]# docker ps -a
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                  PORTS                                            NAMES
5655bc75c210        prom/prometheus:latest            "/bin/prometheus --c…"   4 days ago          Exited (0) 4 days ago                                                    prometheus
c47feb73b3cb        nacos/nacos-server:latest         "bin/docker-startup.…"   4 days ago          Up 4 days               0.0.0.0:8850->8848/tcp                           nacos3
53794d4d5c19        nacos/nacos-server:latest         "bin/docker-startup.…"   4 days ago          Up 4 days               0.0.0.0:8848->8848/tcp, 0.0.0.0:9555->9555/tcp   nacos1
4eae6f29075a        nacos/nacos-server:latest         "bin/docker-startup.…"   4 days ago          Up 4 days               0.0.0.0:8849->8848/tcp                           nacos2
61b622e9c103        nacos/nacos-mysql-slave:latest    "docker-entrypoint.s…"   4 days ago          Up 4 days               33060/tcp, 0.0.0.0:3305->3306/tcp                mysql-slave
8caacc73e7c8        nacos/nacos-mysql-master:latest   "docker-entrypoint.s…"   4 days ago          Up 4 days               0.0.0.0:3306->3306/tcp, 33060/tcp                mysql-master
60337b7b9f1b        grafana/grafana:latest            "/run.sh"                4 days ago          Exited (0) 4 days ago                                                    grafana
[root@k8smanager ~]# 

02-26 17:03:27.408 ERROR [c.alibaba.nacos.client.config.impl.ServerHttpAgent] - [] [] [NACOS  SocketTimeoutException] currentServerAddr:58.87.123.195:8848
02-26 17:03:27.409 ERROR [c.alibaba.nacos.client.config.impl.ServerHttpAgent] - [] [] [NACOS-0002] no available server ERR-CODE: [NACOS-0002], Type: [环境问题], More: [http://console.taobao.net/help/NACOS-0002]
02-26 17:03:27.410 ERROR [com.alibaba.nacos.client.config.impl.ClientWorker] - [fixed-58.87.123.195_8848] [] [NACOS-XXXX] [check-update] get changed dataId exception, msg=java.net.ConnectException: no available server

**Comment by paderlol** [comment]
请问是docker还是k8s，还有是否有更多的异常日志提供下？

**Comment by pcg7675018483** [comment]
我也遇到了，请问解决方法是什么

**Comment by CrisLi** [comment]
遇到了同样问题，关注中。

**Comment by liujiuwu** [comment]
这个怎么解决呢？
