### ISSUE TITLE
Nacos 1.4.3 开启认证后微服务启动报unknown user 403，不能正常注册上去

### ISSUE THREAD

**Issue by shineabel** [alibaba/nacos#8352]
```
<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>2.1.10.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Greenwich.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>2.1.0.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
				<exclusions>
					<exclusion>
						<groupId>com.alibaba.nacos</groupId>
						<artifactId>nacos-client</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>com.alibaba.nacos</groupId>
				<artifactId>nacos-client</artifactId>
				<version>1.4.2</version>
			</dependency>
```

Nacos server:1.4.3
开启认证后微服务启动报unknown user 403，不能正常注册上去

**Comment by KomachiSion** [comment]
那就是用户名密码不对啊

**Comment by shineabel** [comment]
> 那就是用户名密码不对啊

当然不是，用户名密码在nacos界面是能正常登录的，看到也有很多人提了这个问题说各种各样的原因，究竟什么版本才是正常的呀 @KomachiSion

**Comment by KomachiSion** [comment]
先尝试用纯净版本的nacos-client是否可以。我印象中nacos-client好像没有这方面的bug。可能是spring cloud的版本有问题。

**Comment by itlaonong** [comment]
尝试升级版本，如果是旧版的话检查密码是否有类似@的特殊字符，修改为简单的密码测试一下。我使用低版本的密码有@符号导致403。更换后，无此问题。

**Comment by yidaiweiren** [comment]
我也是1.4.3，出现和你相同问题，请问你后面怎么解决的
![image](https://user-images.githubusercontent.com/48823390/206331974-b14b0cc7-1084-4756-8246-2d0a0b3f8ee4.png)

**Comment by shineabel** [comment]
> 我也是1.4.3，出现和你相同问题，请问你后面怎么解决的 ![image](https://user-images.githubusercontent.com/48823390/206331974-b14b0cc7-1084-4756-8246-2d0a0b3f8ee4.png)

<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>2.3.2.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Hoxton.SR9</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>2.2.6.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
				<exclusions>
					<exclusion>
						<groupId>com.alibaba.nacos</groupId>
						<artifactId>nacos-client</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>com.alibaba.nacos</groupId>
				<artifactId>nacos-client</artifactId>
				<version>1.4.2</version>
			</dependency> 这么解决的

**Comment by yidaiweiren** [comment]
非常感谢  我先按照那你的方法尝试一下 @shineabel

**Comment by yidaiweiren** [comment]
> > 我也是1.4.3，出现和你相同问题，请问你后面怎么解决的 ![image](https://user-images.githubusercontent.com/48823390/206331974-b14b0cc7-1084-4756-8246-2d0a0b3f8ee4.png)
> 
> ```
> <dependency>
> 				<groupId>org.springframework.boot</groupId>
> 				<artifactId>spring-boot-dependencies</artifactId>
> 				<version>2.3.2.RELEASE</version>
> 				<type>pom</type>
> 				<scope>import</scope>
> 			</dependency>
> 			<dependency>
> 				<groupId>org.springframework.cloud</groupId>
> 				<artifactId>spring-cloud-dependencies</artifactId>
> 				<version>Hoxton.SR9</version>
> 				<type>pom</type>
> 				<scope>import</scope>
> 			</dependency>
> 			<dependency>
> 				<groupId>com.alibaba.cloud</groupId>
> 				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
> 				<version>2.2.6.RELEASE</version>
> 				<type>pom</type>
> 				<scope>import</scope>
> 				<exclusions>
> 					<exclusion>
> 						<groupId>com.alibaba.nacos</groupId>
> 						<artifactId>nacos-client</artifactId>
> 					</exclusion>
> 				</exclusions>
> 			</dependency>
> 			<dependency>
> 				<groupId>com.alibaba.nacos</groupId>
> 				<artifactId>nacos-client</artifactId>
> 				<version>1.4.2</version>
> 			</dependency>
> ```
> 
> 这么解决的

非常感谢 我先按照那你的方法尝试一下
