### ISSUE TITLE
通过sql修改配置不生效？

### ISSUE THREAD

**Issue by xmabul** [alibaba/nacos#8357]
通过SQL批量修改配置，sql如下：
```sql
update config_info 
set content=replace(content,'test','prod') , md5=md5(content)
where content like '%test%' and tenant_id='prod'
```
执行成功后，重启应用服务，服务获取到的配置仍是旧的（test），是不支持直接SQL变更配置吗？

**Comment by KomachiSion** [comment]
不支持，通过直接修改数据库生效需要至少5小时，建议好好研究下nacos的配置中心机制

**Comment by xmabul** [comment]
> 

谢谢，后面找到2种办法。
1. 通过SQL批量变更，再到控制台进行逐个对变更的data_id进行手动发布；
2. 另一种是调nacos的发布接口POST /nacos/v1/cs/configs
