### ISSUE TITLE
为什么nacos不采用像apollo那样动态发布配置后 在客户端使用反射去更改配置值的 方式去动态更改配置?

### ISSUE THREAD

**Issue by DeBruyne2020** [alibaba/nacos#8360]
问下各位大佬，
nacos现在动态发布配置的机制是依赖spring的RefreshScope注解，RefreshScope注解配在配置所在的类头上，类似于这样：
![image](https://user-images.githubusercontent.com/68886035/168090201-3f380f31-f6d9-4c6e-b956-ee820a67d742.png)

服务在线的情况下，发布这个配置，这会导致spring上下文重新加载，导致服务重启，表现为在注册中心（如eureka）上先down一下然后再up（虽然这个过程可能非常快），，为什么nacos不采用类似apollo的动态发布方式，也就是通过beanFactory找到对应的配置所在的类，然后用反射的方式修改具体配置的值，这样整个spring上下文是不重启的，服务不会重启。

----------------------------------------------------------------------------------------------------------------------------------------

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
因为这是spring cloud 定义的标准，依照标准运行我认为没什么问题。

其他相关细节和问题可以移步到Spring cloud alibaba社区询问。

**Comment by DeBruyne2020** [comment]
> 因为这是spring cloud 定义的标准，依照标准运行我认为没什么问题。
> 
> 其他相关细节和问题可以移步到Spring cloud alibaba社区询问。

 那问下大佬，nacos有没有其他的方式（不使用RefreshScope注解也可以），做到动态发布配置的时候，服务不重启，spring上下文不重新刷新？

**Comment by SevenBlue2018** [comment]
同问！！！
