### ISSUE TITLE
Error creating new configuration

### ISSUE THREAD

**Issue by Amber-Wish** [alibaba/nacos#8362]
在界面上进行配置信息时，出现了错误提示。如下：
When configuring information on the interface, an error message appeared. as follows:
![image](https://user-images.githubusercontent.com/55867470/168113583-fbe9366c-14c3-4f8a-9a63-153b98dda2b6.png)

version: nacos 2.0.3
deploy in k8s

**Comment by Amber-Wish** [comment]
我查阅了docker里面的日志信息，请求时发现有两个错误。第一个错误信息是：
I checked the log information in docker and found two errors when requesting. The first error message is:
`ERROR CONSOLE
org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'dataId' is not present`
第二个错误信息是：
The second error message is:
`ERROR CONSOLE
java.lang.NullPointerException: null`

**Comment by Oliverwqcwrw** [comment]
检查一下sql脚本

**Comment by KomachiSion** [comment]
duplicate with #8349

**Comment by Amber-Wish** [comment]
@Oliverwqcwrw @KomachiSion 我检查了数据库，发现his_config_info表和config_info表已经存在这个字段encrypted_data_key。
![image](https://user-images.githubusercontent.com/55867470/168200112-a3146124-7803-4e1c-ad87-37991a8ddb29.png)
![image](https://user-images.githubusercontent.com/55867470/168200134-e1b4fd0e-a7b7-43f9-ae1d-1dbf6ad25309.png)
新建配置还是失败。
