### ISSUE TITLE
nacos服务注册速度会随着已经注册的服务数量的增长而变慢？

### ISSUE THREAD

**Issue by 18205097282** [alibaba/nacos#8364]
我有两个nacos集群，集群A服务列表注册了大约5000个服务，集群B注册了大约1000个服务。

在启动dubbo项目时发现，nacos注册中心选择集群A的启动时间大约是 选择集群B的启动时间的两倍。

观察启动日志，发现主要的耗时差距在dubbo服务的注册时间上，比如集群B 1秒内可以注册5个服务，而集群A 1秒内只能注册2个服务。

其他所有条件都一样，只是选择nacos注册中心不同，会导致启动时间有明显差距。

环境：
Nacos 1.2.1
dubbo 2.7.14

**Comment by KomachiSion** [comment]
1.X版本会增加，可以升级到2.0版本尝试下

**Comment by KomachiSion** [comment]
No more response from author, the problem seems solved in new version.
