### ISSUE TITLE
springcloud 服务自动掉线 "Shutting down ExecutorService 'Nacos-Watch-Task-Scheduler' "

### ISSUE THREAD

**Issue by joseshiang** [alibaba/nacos#8370]
##### 版本信息
> Springboot  `2.3.9.RELEASE`
> SpringCloud  `Hoxton.SR9`
> SpringCloud Alibaba `2.2.6.RELEASE`
> Nacos注册发现中心 `nacos-server 2.0.2`

##### 日志信息
- 日志1
![微信图片_20220513120804](https://user-images.githubusercontent.com/19600894/168209461-3b3427e2-2e0e-4f71-a45e-28b0e1d8ba9e.png)

- 日志2
![image](https://user-images.githubusercontent.com/19600894/168209275-49f7a7d6-660b-4bf5-becd-180992933073.png)

**Comment by KomachiSion** [comment]
1. 服务掉线是由于你应用自身退出导致，上述日志是应用退出时调用了shutdown hook才又的日志，请自查应用为什么退出。
2. 上述日志报错应该是Srping cloud alibaba旧版本的bug，请将issue转移到SCA社区，或先行搜索SCA社区issue。

**Comment by joseshiang** [comment]
> 1. 服务掉线是由于你应用自身退出导致，上述日志是应用退出时调用了shutdown hook才又的日志，请自查应用为什么退出。
> 2. 上述日志报错应该是Srping cloud alibaba旧版本的bug，请将issue转移到SCA社区，或先行搜索SCA社区issu

现在自查发现了一处问题，是启动jar服务sh脚本，使用`exec`命令，而不是使用德`nohup`, 修改为`nohup`之后，目前掉线问题没有出现了。
