### ISSUE TITLE
2.1.0版本客户端使用不了https连接

### ISSUE THREAD

**Issue by sungenping** [alibaba/nacos#8372]
2.1.0版本客户端使用不了https连接。
调测发现，ServerListManager.java文件的第199行，在此版本中被修改出了问题。
ServerListManager(Properties properties)函数中的如下判断语句
if (serverAddr.startsWith(HTTP_PREFIX) || serverAddr.startsWith(HTTP_PREFIX))
应修改为
if (serverAddr.startsWith(HTTP_PREFIX) || serverAddr.startsWith(HTTPS_PREFIX))
请尽快安排修复并提供新版本，谢谢。

**Comment by Oliverwqcwrw** [comment]
@i will solve it@
