### ISSUE TITLE
集群模式下，手动点击应用下线不生效，管理界面上应用一直存在且是健康状态，但实际情况是应用无法提供服务

### ISSUE THREAD

**Issue by zengziqiang** [alibaba/nacos#8375]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我使用三台1.4.2版本的nacos搭建的集群，配置的mysql存储方式，集群正常运行后，我注册了8个服务，每个服务都是两个节点，运行有几个月后，我停止了个别节点的应用准备更新，停止后发现nacos的管理界面上一直正常显示，清除缓存并等了半个多小时后仍然存在，且节点显示健康状态。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
1.4.2  三台服务器搭建的集群

**Comment by KomachiSion** [comment]
你可能对下线这个操作有误解， 下线操作不会影响健康状态，健康状态来自于应用心跳，只要你应用运行正常，心跳正常发送，状态就是健康的。

下线操作只是让订阅者感知不到这个实例，实例本身运行不会受影响。

**Comment by zengziqiang** [comment]
你好，我通过查看你们的官网中对于下线操作的描述，给我的感觉好像是点击了下线，应用将不会在健康的实例列表里。也许是我理解有偏差。
你的意思是点击了下线，健康状态还是好的，只是请求不会轮询到下线的服务上，是这个意思吗？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 上午9:53
***@***.***&gt;;
抄送:&nbsp;"╭Mr.曾 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 集群模式下，手动点击应用下线不生效，管理界面上应用一直存在且是健康状态，但实际情况是应用无法提供服务 (Issue #8375)





 
你可能对下线这个操作有误解， 下线操作不会影响健康状态，健康状态来自于应用心跳，只要你应用运行正常，心跳正常发送，状态就是健康的。
 
下线操作只是让订阅者感知不到这个实例，实例本身运行不会受影响。

**Comment by KomachiSion** [comment]
是的，consumer测就看不到这个已经下线的实例的，但是他其实还是在nacos里的，移除的方法需要根据是否是临时实例，临时实例就是关闭进程，或者停止发送心跳。 持久化实例就是掉接口注销掉。
