### ISSUE TITLE
请问Nacos目前支持spring-boot 3.0.0-M2和spring-cloud 2022.0.0-M2嘛？

### ISSUE THREAD

**Issue by duckyduck** [alibaba/nacos#8377]
spring-boot 3.0.0-M2
spring-cloud 2022.0.0-M2
nacos 2021.0.1.0
我目前用这三个版本的搭配似乎启动不了

**Comment by KomachiSion** [comment]
spring-boot应该支持2.X版本， 3.0应该还没支持， 欢迎提PR。

spring-cloud请转移到SCA社区提问。
