### ISSUE TITLE
大无语事件，新版本的shared-configs中使用dataid的时候又不需要写后缀了，兄弟们

### ISSUE THREAD

**Issue by pkaq** [alibaba/nacos#8381]
找了半天，提示文件加载了 但是environment里 size始终是0 ，最后把dataId的后缀去掉成功

**Comment by li-xiao-shuang** [comment]
使用的是什么接入方式和版本？

**Comment by iQuanhe** [comment]
日志、具体事例、接入方式、版本、环境......，发出来。很难猜到你的问题所在

**Comment by pkaq** [comment]
所有都是最新版本 11jdk 没了 启动的main方法里打断点看environment对象就是0 dataid去掉yaml后缀秒行

**Comment by KomachiSion** [comment]
It seems problem has solved. Close it.
