### ISSUE TITLE
服务注册 - nacos本机注册到了nacos

### ISSUE THREAD

**Issue by NetRainn** [alibaba/nacos#8384]
前置：
nacos版本使用版本为2.0，jdk8
服务器 4核8G
两台服务器集群
问题：
nacos A服务器将某个服务注册到了A服务器的nacos中。
1. 经过排查 当前服务器没有该服务启动，为什么nacos检测情况为健康的
2. 该服务实例为ephemeral，但是服务重启后，为什么这个实例还在
![image](https://user-images.githubusercontent.com/35440615/168534001-f7e6cdeb-6afe-4d29-a880-e8e2c181ce0f.png)
![image](https://user-images.githubusercontent.com/35440615/168534507-ef35c3fb-cef4-421f-a53b-058f39e03070.png)

**Comment by KomachiSion** [comment]
说明一致有这个服务注册到nacos上，并且一直发送心跳或维持链接。请自查。

**Comment by NetRainn** [comment]
排查了104这台服务器，没有该服务，且端口没有被占用
也重启了nacos，但服务一直在
这个可能跟服务本身的配置有关吗？ 我们有十几个服务，只有三个服务出现这种情况

**Comment by KomachiSion** [comment]
是否有注册和端口是否有占用没有直接关系， 注册是说有应用调用过nacos-client的注册接口，有可能是其他服务或者进程代注册的。

如果用的是nacos-client1.X的客户端， 可以打开naming-event.log的debug日志看下有没有心跳。
2.X的客户端的话就看下有没有来自这个ip的链接。

**Comment by NetRainn** [comment]
我们排查了下 ，公司用的是 云环境与公司内网打通了的，然后本地调式注册到nacos ，个别服务就会展示nacos本机ip
用的2.0.4版本，查看了相关日志，确实是104这台机器在发心跳，但是不排除是云环境做了相应处理 让内网注册上去就是104本地，目前还在排查
