### ISSUE TITLE
客户端对接Nacos 2.1.0后，启动报错

### ISSUE THREAD

**Issue by yaoliu108** [alibaba/nacos#8391]
nacos-client: 2.1.0-BETA
nacos-aes-encryption-plugin: 1.0.0-SNAPSHOT
spring-cloud-starter-alibaba-nacos-config: 2021.1
启动报以下错误， 而且也读不到我加密的配置文件
Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.

java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path

Multiple resources found for 'META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib' with different content: [jar:file:/Users/liuyao/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.75.Final/netty-resolver-dns-native-macos-4.1.75.Final-osx-x86_64.jar!/META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib, jar:file:/Users/liuyao/.m2/repository/com/alibaba/nacos/nacos-aes-encryption-plugin/1.0.0-SNAPSHOT/nacos-aes-encryption-plugin-1.0.0-SNAPSHOT.jar!/META-INF/native/libnetty_resolver_dns_native_macos_x86_64.jnilib]

**Comment by yaoliu108** [comment]
java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path

**Comment by KomachiSion** [comment]
> java.lang.UnsatisfiedLinkError: no netty_resolver_dns_native_macos_x86_64 in java.library.path

You has found the problem, your env has no support for `netty_resolver_dns_native_macos_x86_64`. Please search for how to make your env support it.

BTW, the file is netty's file not nacos. so I think you can search the problem in netty community better.

**Comment by yaoliu108** [comment]
> 

现在不报错了，但是读不到加密的配置文件里的属性了
<img width="805" alt="image" src="https://user-images.githubusercontent.com/28888340/168729674-b649e7a7-a46e-4dd3-ab9e-5a298aa0fc69.png">
