### ISSUE TITLE
nacos-server 2.1.0 can't get the responsible Server for a service by openAPI

### ISSUE THREAD

**Issue by OOOOlh** [alibaba/nacos#8392]
When I use the link to get the responsible Server for a service named "microservice1",I get the response below;
link : http://[localhost:8848/nacos/v1/ns/ops/distro/server?serviceName=microservice1](http://localhost:8848/nacos/v1/ns/ops/distro/server?serviceName=microservice1)
![image](https://user-images.githubusercontent.com/83326634/168721655-4417165b-ab83-47f2-88ad-141ff3f5a582.png)
But the service is still in the console list:
![image](https://user-images.githubusercontent.com/83326634/168721786-00b01153-d101-46c3-a70b-a4212f93a8d2.png)
I am confused.
##
OS:Windows
Version:nacos-server 2.1.0
SDK: JAVA 1.8.0_301
##
And when I encounted the problem, I was running with the source code. And then I use another version which is "nacos-server 1.4.3", and the response is below:
![QQ图片20220517113151](https://user-images.githubusercontent.com/83326634/168733026-944726ee-1112-4f10-b832-aef598dd6927.png)

**Comment by xiaobailh** [comment]
And I know the entrance of the openapi, which lies in "nacos-naming.src.main.java.com.alibaba.nacos.naming.controllers.OperatorController#getResponsibleServer4Service". 
![image](https://user-images.githubusercontent.com/83326634/168735072-e425540d-4b8d-4d82-bdfd-7929c19d922f.png)

By debugging it, I find 
nacos-naming.src.main.java.com.alibaba.nacos.naming.core.ServiceManager#getService
![image](https://user-images.githubusercontent.com/83326634/168735443-f32a58a7-9435-425e-8f1e-97fe640ed3bf.png)
"serviceMap : size=0" is so strange

**Comment by KomachiSion** [comment]
2.1.0 version has close the double write for default, the v1 data has no used.

you should use 'distro/client?ip=&port=' replace
