### ISSUE TITLE
客户端对接Nacos2.1.0版本，获取不到加密配置文件的配置项

### ISSUE THREAD

**Issue by yaoliu108** [alibaba/nacos#8393]
Nacos配置项，Mysql存储显示content字段加密成功
<img width="856" alt="image" src="https://user-images.githubusercontent.com/28888340/168757134-e4274610-a1fd-4a97-b31f-45c9240f480a.png">

程序源码，取不到对应项
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/28888340/168757375-d1d1f672-85ef-4823-8021-6090b393949c.png">

pom.xml
<img width="679" alt="image" src="https://user-images.githubusercontent.com/28888340/168757760-d4dfcb93-32de-4f84-a804-879882535065.png">

**Comment by yaoliu108** [comment]
紧急，请帮忙看下 @KomachiSion

**Comment by farhad663** [comment]
Trade 

Sent from Yahoo Mail on Android 
 
  On Tue, 17 May 2022 at 13:26, 李晓双 Li Xiao ***@***.***> wrote:   


springcloud nacos 的配置提供下

**Comment by yaoliu108** [comment]
> Trade  Sent from Yahoo Mail on Android On Tue, 17 May 2022 at 13:26, 李晓双 Li Xiao ***@***.***> wrote: springcloud nacos 的配置提供下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


<img width="479" alt="image" src="https://user-images.githubusercontent.com/28888340/168772722-34c85f82-33ac-49ed-aaae-b1575b3f2e60.png">




spring-cloud-starter-alibaba-nacos-config 对应的版本是: 2021.1 

没有copier开头文件可以读到，加密的无法读取成功

**Comment by li-xiao-shuang** [comment]
配置下 spring.cloud.nacos.config.prefix：cipher-aes-uds-api-dev 试试

**Comment by yaoliu108** [comment]
> 配置下 spring.cloud.nacos.config.prefix：cipher-aes-uds-api-dev 试试

我希望项目有两个配置项，一个是明文的uds-api-dev.yaml， 另一个是加密的是cipher-aes-uds-api-dev.yaml。我希望两个文件都可以加载成功，目前只加载上了uds-api-dev.yaml。刚配置上了spring.cloud.nacos.config.prefix：cipher-aes-uds-api-dev后，可以加载加密的文件了，但是无法加载明文的uds-api-dev.yaml

**Comment by li-xiao-shuang** [comment]
> > 配置下 spring.cloud.nacos.config.prefix：cipher-aes-uds-api-dev 试试
> 
> 我希望项目有两个配置项，一个是明文的uds-api-dev.yaml， 另一个是加密的是cipher-aes-uds-api-dev.yaml。我希望两个文件都可以加载成功，目前只加载上了uds-api-dev.yaml。刚配置上了spring.cloud.nacos.config.prefix：cipher-aes-uds-api-dev后，可以加载加密的文件了，但是无法加载明文的uds-api-dev.yaml

建议你去阅读下 springcloud alibaba文档，看看 shared configs
