### ISSUE TITLE
console里分页查询nacos配置项功能，为什么不加排序字段？是有什么场景吗？

### ISSUE THREAD

**Issue by shixitong** [alibaba/nacos#8397]
对应的nacos版本2.0.3
![image](https://user-images.githubusercontent.com/7553342/168952265-d66a0152-19fa-4254-b7d8-9bc364ff0ea6.png)

**Comment by KomachiSion** [comment]
感觉不是很必要， 正常使用配置中心都是关心应用对应的配置，不怎么关心哪些配置是最新修改的。

**Comment by bangbang2333** [comment]
> 感觉不是很必要， 正常使用配置中心都是关心应用对应的配置，不怎么关心哪些配置是最新修改的。

Everything needs to be sorted, otherwise it does not meet the company's specifications -----来自非洲的设计师说到
![9A2D13A1A6167C33F8E2BACCB3F107E9](https://user-images.githubusercontent.com/43024629/169045314-d1af2df9-589b-4101-a8e4-2c66ae2132a2.png)

**Comment by shixitong** [comment]
nacos配置中心持久化目前是只支持mysql，然后如果不加排序，mysql默认是安装主键排序，所以后面就算修改，这条记录的位置是不会变动的，比如本来排在第3位，修改后还是第3位，也没啥问题，我们关注到这个问题，是因为我们增加了第三方数据库的支持，第三方数据默认不是按照主键排序的，所以修改完某个配置项后，这个配置项位置就会乱串。问这个问题也是看看nacos这边后面会不会有这个方面的考虑？

**Comment by KomachiSion** [comment]
应该不会有这个考虑， 从配置中心角度来看， 用户不应该关心哪个配置是最近被修改的，只会关注某个配置本身（dataId或group）。
因为其他的配置可能是其他人其他应用的配置，最新修改和你没什么关系。
