### ISSUE TITLE
nacos2.1.0集群模式下,控制台的操作涉及到request.getSession()的所有代码，实际是获取不到的

### ISSUE THREAD

**Issue by xunluzhe** [alibaba/nacos#8403]
**Describe the bug**
2.1.0版本，在集群模式下，使用nginx做负载后，控制台上的操作，实际上每一次请求经nginx转发后，每次都会请求到不同的服务端，
这个时候再去request.getSession()，实际上肯定获取不到，会导致操作失败，例如在控制台上修改密码的过程就会涉及到一行代码，
`if (Objects.isNull(request.getSession().getAttribute(AuthConstants.NACOS_USER_KEY))) {
            return false;
        }`
以下是翻译
In version 2.1.0, in the cluster mode, after using nginx as the load, the operation on the console will actually request to different servers after each request is forwarded by nginx,

Go to request again at this time In fact, getsession() cannot be obtained, which will cause the operation to fail. For example, the process of changing the password on the console will involve a line of code

![image](https://user-images.githubusercontent.com/96710180/168996588-1b0d3db4-dca5-4523-9033-69f4eca96d84.png)

**Expected behavior**
把request.getSession() 所有相关代码都做相应修改，集群模式下，不应从session中获取任何信息

Modify relevant codes, `request.getSession()` , In the cluster mode, no information should be obtained from the session

**Acutally behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.1.0]
 - Module [e.g. nacos-plugin-default-impl]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
有解决方案吗？

**Comment by xunluzhe** [comment]
一共有8处调用getSession()的地方，有两处是测试代码，有两处是往session里写对象，这4处都可用直接干掉，还有4处，经查都是从session中获取用户信息
![image](https://user-images.githubusercontent.com/96710180/169186070-770a25d1-31d1-4f8c-bd8d-03c75ef89cc3.png)
在 nacos.core.auth.enabled=true 时，在控制台中操作，每一次请求都会带着 accessToken 这个参数，这是一个JWT，而jwt的第二段经base64 decode后也可以得到username, 所以说username的获取完全可以从jwt中得到，session也就可以全部干掉

集群模式下 nacos.core.auth.enabled=false 时，每一次请求是否都会带着 accessToken 这个参数还有待验证

**Comment by qingshan1993** [comment]
也可以配置nginx的ip_hash的负载均衡策略来解决

**Comment by gordon-luo-9527** [comment]
老版本在 AuthFilter 里涉及 @Secured 注解的接口会走一遍 authManager.login(req)，login 实现里有 setSession 操作。

**Comment by luoniyanglan** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
> 老版本在 AuthFilter 里涉及 @secured 注解的接口会走一遍 authManager.login(req)，login 实现里有 setSession 操作，所以每次拿 session 也没啥问题。 新版本改了这个逻辑，要用 session 的话可能要加上 setSession 操作。

因为老版本只有http接口， 新版本还有grpc接口，不能依赖于Request和Session。

**Comment by KomachiSion** [comment]
我感觉保存到session中是个不太好的做法，会过于依赖某个体系导致不好扩展，最好的办法还是讲身份信息通过其他手段保存在一个上下文里

**Comment by KomachiSion** [comment]
No more response from community, I think this is not a issue..
