### ISSUE TITLE
由于加了权限之后，本地对接就需要账号密码，这个账号密码如何隐藏或者加密

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#8404]
![image](https://user-images.githubusercontent.com/90117583/169013430-4c0e4673-ac84-4f91-9038-a46827e390c6.png)
请问
    username: nacos # 开启权限后需要设置账号密码
    password: nacos 
这个怎么加密

**Comment by KomachiSion** [comment]
暂无方案， 如果有对应的需求，可以查看文档：鉴权插件， 来开发自己的鉴权插件来满足你们的安全需求。
