### ISSUE TITLE
请问openapiv1版本需要进行改进，并选择使用restful或rpc风格的的代码规范，这两种代码风格对代码进行修改后有什么实质性的好处吗

### ISSUE THREAD

**Issue by Dxcyc9** [alibaba/nacos#8406]
1. 使用这两种代码风格是否也会导致一些问题？（能具体举例说说看吗）
2. v2的openapi需要比v1的openapi具体精进在哪，哪些问题需要在v2的openapi中进行解决

**Comment by KomachiSion** [comment]
如果您不希望有统一的返回格式，统一的请求风格，统一且快速可查询的错误码，只喜欢获得简单的`true`,`ok`,``的话。 请继续使用v1的openAPI。

**Comment by KomachiSion** [comment]
另外还有一些v2之后新增的功能，只能用v2的openAPI来进行。因为v1不存在长链接等能力。

**Comment by Dxcyc9** [comment]
> 如果您不希望有统一的返回格式，统一的请求风格，统一且快速可查询的错误码，只喜欢获得简单的`true`,`ok`,``的话。 请继续使用v1的openAPI。

换用新的代码风格的好处就除了能进行统一的请求和返回格式，是否还有一些其他的好处呀

**Comment by KomachiSion** [comment]
除了可读性和风格的好处，就只有新增功能的好处了。  不然还想要哪些好处？ 接口区别除了这些，本身就没有本质区别。都是能用的。
