### ISSUE TITLE
nacos 节点数据在个别节点宕机情况下 数据很容易不一致

### ISSUE THREAD

**Issue by wangdongyun** [alibaba/nacos#8408]
单点宕机   非常容易出现distro 协议 同步队列拥堵

对于verfiy 如果有单点故障，对应日志
2022-04-07 11:07:42,137 ERROR [Cluster-10.21.42.19:8848]Send request fail, request=DistroDataRequest{headers={}, requestId='null'}, retryTimes=1,errorMessage=Client not connected.

// 同步的关键代码
 
if (waitReconnect) {
                    try {
                        //wait client to re connect.
                        Thread.sleep(Math.min(100, callback.getTimeout() / 3));
                    } catch (Exception exception) {
                        //Do nothing.
                    }
                }

这里一次阻塞100ms, 3次 重试，也就是300ms！

如果一个node上有 800个实例（responsible) 一次向故障节点的数据同步 需要 300 * 800 = 240s > 3分钟 

不同节点的数据同步的过期时间是 3分钟，如果 超过3分钟数据仍然没有同步，对方就是大面积下掉 临时实例！

假设 A\B\C\D\E组成集群

如果 A 有800个实例，C 宕机，那么A 向C同步需要 3分钟，这个时候本身没有问题，
但是 A 向B 同步，与 A 向C同步有可能使用的是一个队列，因为向C同步花费超过了3分钟，
那么向B同步必然延迟了3分钟，导致B认为A可能挂了，下掉了A的所有临时实例

这个是极其危险的

我们内部修复逻辑比较简单，尽量最小改动（nacos 更新频繁，一直在合并代码）

增加了一个参数，表示是否等待重连，
对于 集群间的数据同步设置为false，立即返回，避免了队列拥堵

![image](https://user-images.githubusercontent.com/6995309/169139565-b1d64dac-0bed-42c6-b033-1065f14d934c.png)

**Comment by wangdongyun** [comment]
另外队列是否可以拆分 避免相互影响

**Comment by KomachiSion** [comment]
你的描述不太合理啊， 不同的服务端之间链接是不同的， 重试只影响当前链接啊。

**Comment by KomachiSion** [comment]
No more response from author, and duplicate with #8099

**Comment by wangdongyun** [comment]
> 你的描述不太合理啊， 不同的服务端之间链接是不同的， 重试只影响当前链接啊。

重启确实只会影响当前连接，但是会卡主 数据同步的线程
