### ISSUE TITLE
MAC OS compatibility bug Or is a Bug

### ISSUE THREAD

**Issue by MinGRn** [alibaba/nacos#841]
First, Thanks to ali's developers！

Today, I try use `Nacos v0.8.0` on mac OS(`v10.14.2`) and Windows10. However, I found some problems with the same operation on the MAC，or is a bug？

# Test

**MySQL : `5.6.39`**

On Win10 , I'm gonna double click start. CMD in the bin directory,It starts up really fast. I access it in a browser `localhost:8848/nacos`. No problem！

Forgot to say, in the conf/application. The properties of my connection to the database configuration are as follows:

```
spring.datasource.platform=mysql
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=admin
```

Then I create a configuration in the configuration list, and the data is persisted to the database perfectly，So win10 is ok!

<img width="1381" alt="1" src="https://user-images.githubusercontent.com/32328109/53496258-9d6ea100-3adc-11e9-8bc4-3596288ff887.png">

<img width="815" alt="2" src="https://user-images.githubusercontent.com/32328109/53496291-b4ad8e80-3adc-11e9-9042-dedfb96befc6.png">

But On Mac,  The same database connection is started without any abnormal log output. However, the new configuration is not persisted to the database。I start it with `sh start.sh -m standalone` and `bash start.sh -m standalone`.Neither approach works！

Is this the reason for the `.sh` script? However, I tested the same on `Centos 7`. Found with win10, there is no problem.This problem exists only on the Mac

So,I don't know if this is a bug or a compatibility issue.

**Comment by nkorange** [comment]
@MinGRn Try the latest version please.
