### ISSUE TITLE
开发Nacos服务端鉴权插件，控制台登录失败

### ISSUE THREAD

**Issue by aojiaobaba** [alibaba/nacos#8410]
## Issue Description

Configure authentication plug-in, console login failed

### Describe what happened (or what feature you want)

Inheritance interface com.alibaba.nacos.plugin.auth.spi.server.AuthPluginService Implement and configure the authentication plug-in, Console login failed

### Describe what you expected to happen
Console login successful

### How to reproduce it (as minimally and precisely as possible)

1. Then implement com alibaba. nacos. plugin. auth. spi. server. Authpluginservice interface and add your implementation to SPI services.
2. After the plug-in is developed, it needs to be packaged into jar / zip. Please put it directly under / plugins
3. Modify conf / application The following configuration in properties
    nacos.core.auth.system.type=Plug in name
    nacos.core.auth.enabled=true
4. Console login failed

### Tell us your environment
 nacos2.1.0

### Anything else we need to know?
nothing

**Comment by onewe** [comment]
有具体的错误信息吗？

**Comment by KomachiSion** [comment]
控制台页面应该只支持nacos自带的插件，因为前端页面没法插件化。

自定义插件可能需要在插件中实现自己的登陆接口。

**Comment by aojiaobaba** [comment]
密码不采用自己编写的插件可以正常登录

**Comment by aojiaobaba** [comment]
![image](https://user-images.githubusercontent.com/62386090/169472620-b8e4c6a9-dc9f-45ed-8773-9b505e9f81cf.png)

**Comment by aojiaobaba** [comment]
看了下源代码，涉及WebSecurity和AuthenticationManagerBuilder的配置
![Uploading nacos.png…]()

**Comment by aojiaobaba** [comment]
采用默认的插件控制台可以正常登录
![image](https://user-images.githubusercontent.com/62386090/169474970-8083edfb-1786-47e8-913f-dd108359898d.png)

**Comment by aojiaobaba** [comment]
看了下源码主要涉及WebSecurity和AuthenticationManagerBuilder两个地方的配置
![nacos](https://user-images.githubusercontent.com/62386090/169475394-b616f9fb-4947-445e-b658-5121d7af9d60.png)

**Comment by KomachiSion** [comment]
Yes, you should implement your login api in your plugins.

The console api only support default plugins.
