### ISSUE TITLE
2.0.4版本中 永久实列注册逻辑问题

### ISSUE THREAD

**Issue by LeonardoEzio** [alibaba/nacos#8412]
NamingClientProxyDelegate.getExecuteCllientProxy中已经根据实列类型获取具体的NamingClientProxy，如果是临时实列则使用 NamingGrpcClilentProxy，如果是永久实列则使用 NamingHttpClientProxy，那么既然已经判断过了，为什么还要在NamingHttpClientProxy 中再次判断，也就是说下述 if 代码块根本不会进入。

@Override
    public void registerService(String serviceName, String groupName, Instance instance) throws NacosException {
        
        NAMING_LOGGER.info("[REGISTER-SERVICE] {} registering service {} with instance: {}", namespaceId, serviceName,
                instance);
        String groupedServiceName = NamingUtils.getGroupedName(serviceName, groupName);
        if (instance.isEphemeral()) {
            BeatInfo beatInfo = beatReactor.buildBeatInfo(groupedServiceName, instance);
            beatReactor.addBeatInfo(groupedServiceName, beatInfo);
        }
        final Map<String, String> params = new HashMap<String, String>(32);
        params.put(CommonParams.NAMESPACE_ID, namespaceId);
        params.put(CommonParams.SERVICE_NAME, groupedServiceName);
        params.put(CommonParams.GROUP_NAME, groupName);
        params.put(CommonParams.CLUSTER_NAME, instance.getClusterName());
        params.put(IP_PARAM, instance.getIp());
        params.put(PORT_PARAM, String.valueOf(instance.getPort()));
        params.put(WEIGHT_PARAM, String.valueOf(instance.getWeight()));
        params.put("enable", String.valueOf(instance.isEnabled()));
        params.put(HEALTHY_PARAM, String.valueOf(instance.isHealthy()));
        params.put(EPHEMERAL_PARAM, String.valueOf(instance.isEphemeral()));
        params.put(META_PARAM, JacksonUtils.toJson(instance.getMetadata()));
        
        reqApi(UtilAndComs.nacosUrlInstance, params, HttpMethod.POST);
        
    }

**Comment by KomachiSion** [comment]
`NamingHttpClientProxy`  是由旧版本（1.X）的逻辑中重构而来，因此保留了旧版本中的所有逻辑。最终应该会被彻底移除
