### ISSUE TITLE
2.1.0版本外置数据库update语句有问题,WHERE前面少了一个空格

### ISSUE THREAD

**Issue by maguanyu** [alibaba/nacos#8416]
代码位置com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl#updateConfigInfoAtomic
WHERE前面少了一个空格

            jt.update("UPDATE config_info SET content=?, md5 = ?, src_ip=?,src_user=?,gmt_modified=?,"
                            + "app_name=?,c_desc=?,c_use=?,effect=?,type=?,c_schema=?,encrypted_data_key=?"
                            + "WHERE data_id=? AND group_id=? AND tenant_id=?", configInfo.getContent(), md5Tmp, srcIp, srcUser,

**Comment by CherishCai** [comment]
已提交过合并在 develop 分支
https://github.com/alibaba/nacos/pull/8234

**Comment by maguanyu** [comment]
copy that
