### ISSUE TITLE
nacos权限认证失败，直接弹出到登陆界面

### ISSUE THREAD

**Issue by wangqingchengsg** [alibaba/nacos#8417]
<img width="444" alt="image" src="https://user-images.githubusercontent.com/22829954/169478456-707aebca-d14a-42b8-9ff8-873181c2c1a2.png">

点击后，告诉我没权限，直接弹出到登陆页面。。

nacos-server-2.1.0版本

**Comment by KomachiSion** [comment]
是不是因为token已经过期或者session已经过期导致？

**Comment by onewe** [comment]
@KomachiSion 估计是前端的那个判断有点问题,后面我复现一下

**Comment by onewe** [comment]
问题是这样的,之前为了解决 `nacos`重启`session`失效,用户任然能正常操作,只有在修改用户时,才提示`authorization failed!`. issue: https://github.com/alibaba/nacos/issues/8107 当时的解决方案是: 当后端返回`403`时,则跳转到登录页面.

**Comment by onewe** [comment]
现在又有个`public` 无权限问题 https://github.com/alibaba/nacos/issues/8107#issuecomment-1132505372

**Comment by onewe** [comment]
现在又有个`public` 无权限问题 https://github.com/alibaba/nacos/issues/8107#issuecomment-1132505372

**Comment by onewe** [comment]
@wangqingchengsg 请问你这个是升级导致的问题还是一开始就有这个问题?

**Comment by KomachiSion** [comment]
> 问题是这样的,之前为了解决 `nacos`重启`session`失效,用户任然能正常操作,只有在修改用户时,才提示`authorization failed!`. issue: #8107 当时的解决方案是: 当后端返回`403`时,则跳转到登录页面.

如果是403就出现跳转那肯定不对啊，如果是session失效导致的权限失败应该给其他的错误码。

**Comment by onewe** [comment]
@i will resolve it@
