### ISSUE TITLE
解耦commonOkHttp模块

### ISSUE THREAD

**Issue by liqipeng** [alibaba/nacos#8421]
在处理升级Spring Boot版本至2.6版本时，遇到okHttp版本问题，
发现实际是```test```模块依赖的```commonOkHttp```依赖了okHttp，
而```commonOkHttp```模块目前缺少维护，所以考虑解耦commonOkHttp模块。

相关PR：
#8184
#8185

**Comment by KomachiSion** [comment]
#8422 and #8423
