### ISSUE TITLE
2.x的auth插件模块的Spring Bean存在循环依赖

### ISSUE THREAD

**Issue by liqipeng** [alibaba/nacos#8424]
The dependencies of some of the beans in the application context form a cycle:

   nacosAuthManager (field private com.alibaba.nacos.plugin.auth.impl.JwtTokenManager com.alibaba.nacos.plugin.auth.impl.NacosAuthManager.tokenManager)
┌─────┐
|  jwtTokenManager (field private com.alibaba.nacos.plugin.auth.impl.NacosAuthConfig com.alibaba.nacos.plugin.auth.impl.JwtTokenManager.nacosAuthConfig)
↑     ↓
|  nacosAuthConfig (field private com.alibaba.nacos.plugin.auth.impl.JwtTokenManager com.alibaba.nacos.plugin.auth.impl.NacosAuthConfig.tokenProvider)
└─────┘

**Comment by liqipeng** [comment]
#8184

**Comment by KomachiSion** [comment]
Fixed by https://github.com/alibaba/nacos/pull/8418.
