### ISSUE TITLE
nacos2.0.3 绕过鉴权认证, 高版本未知

### ISSUE THREAD

**Issue by zhangpan-soft** [alibaba/nacos#8426]
今天在测试的时候, 偶然发现, nacos不需要token也可以修改配置, 获取配置, 等等. 经过测试, 已可确认, nacos不需要登录, 可访问所有nacos的数据.

**Comment by leechliao** [comment]
inpossible

**Comment by zhangpan-soft** [comment]
![image](https://user-images.githubusercontent.com/66060154/169658372-a907a2cc-abca-49bc-94b3-d8cc1f6d8528.png)
![image](https://user-images.githubusercontent.com/66060154/169658387-74597b7b-79f2-455b-8918-c8547a45cfed.png)
![image](https://user-images.githubusercontent.com/66060154/169658424-c931728c-4df3-48ce-9116-669155a691f9.png)

真的是重大漏洞, 我要验证下最新版本

**Comment by zhangpan-soft** [comment]
> inpossible

你看我新增的评论, 你可以试一下, 重大漏洞.

**Comment by zhangpan-soft** [comment]
经过测试2.1.0版本, 依然存在此漏洞, 望紧急修复下.

**Comment by leechliao** [comment]
那是你没有启用auth.enable
