### ISSUE TITLE
gh pr checkout 18067

### ISSUE THREAD

**Issue by tirthankarsutradhar** [alibaba/nacos#8427]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangpan-soft** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

我想要一个安全认证的nacos. 在我看来, 作为配置中心, 应该是绝对安全的, 不论在任何场景下, 都应该如此, 即使是内网. 然而, 我发现, nacos的登录形同虚设, api相关模块没有任何接口是有鉴权认证的, nacos的鉴权认证只在前端做了假鉴权, 我觉得这是一个重大失误. 我在想我们将要从nacos迁移到其他配置中心, 这个给我们的风险太高, 即使是内网环境.

**Comment by zhangpan-soft** [comment]
> > **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> > **Describe the solution you'd like** A clear and concise description of what you want to happen.
> > **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> > **Additional context** Add any other context or screenshots about the feature request here.
> 
> 我想要一个安全认证的nacos. 在我看来, 作为配置中心, 应该是绝对安全的, 不论在任何场景下, 都应该如此, 即使是内网. 然而, 我发现, nacos的登录形同虚设, api相关模块没有任何接口是有鉴权认证的, nacos的鉴权认证只在前端做了假鉴权, 我觉得这是一个重大失误. 我在想我们将要从nacos迁移到其他配置中心, 这个给我们的风险太高, 即使是内网环境.




> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.


> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

我已经关闭了8426, 因为我发现在application.properties里面有相关配置, 可以开启服务端鉴权.
