### ISSUE TITLE
[Doc] How to subscribe nacos email list?

### ISSUE THREAD

**Issue by Oliverwqcwrw** [alibaba/nacos#8430]
**Describe the bug**

The subscribe address is dubbo url now

<p>邮件列表建议讨论任何与Nacos有关的事情。具体请看 "https://github.com/apache/incubator-dubbo/wiki/Mailing-list-subscription-guide" 参考手册 描述如何订阅我们的邮件列表

Where is the nacos address

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
nacos email list is google email group, you can search `how to subscribe google email group` to get answer by search engine.
