### ISSUE TITLE
The official document has no console access address and account password.

### ISSUE THREAD

**Issue by tm2018** [alibaba/nacos#844]
官方文档，运维手册和控制台手册，未找到关于进入控制台的地址、用户名/密码及设置/修改账号密码的方式

**Comment by haoweizh** [comment]
http://localhost:8848/nacos/

**Comment by bobleeli** [comment]
![image](https://user-images.githubusercontent.com/11456183/55122392-c7e26700-5139-11e9-967a-c74b6360ebe4.png)

- https://nacos.io/zh-cn/docs/console-guide.html
- https://nacos.io/en-us/docs/console-guide.html
