### ISSUE TITLE
nacos client for rust

### ISSUE THREAD

**Issue by keqingyuan** [alibaba/nacos#8443]
nacos client for rust

**Comment by li-xiao-shuang** [comment]
> nacos client for rust

Do you have such a need?

**Comment by intfish123** [comment]
I has used nacos in production env.  and there are some rust service need to regist in nacos.  
But there are no sdk for rust.

**Comment by CherishCai** [comment]
I would like to contribute to the Nacos Rust sdk; let's work on this project together.

Can I contribute [CherishCai/nacos-sdk-rust](https://github.com/CherishCai/nacos-sdk-rust) to nacos-group first, and then find participants to improve it together?

**Comment by CherishCai** [comment]
https://github.com/nacos-group/nacos-sdk-rust/pull/7

---

发布了初版 nacos-sdk=0.1.1 ，Config 模块基本可用，欢迎社区同学贡献、修复和标准化 api

https://crates.io/crates/nacos-sdk

https://docs.rs/nacos-sdk/0.1.1/nacos_sdk/

**Comment by CherishCai** [comment]
发布了初版 [nacos-sdk=0.2.0](https://github.com/nacos-group/nacos-sdk-rust/releases/tag/v0.2.0-with-macro) ，Config/Naming 功能均可用，同时包括登陆鉴权，配置解密插件均在这个版本提供。

https://crates.io/crates/nacos-sdk

https://docs.rs/nacos-sdk/0.2.0/nacos_sdk/

后续请到仓库 https://github.com/nacos-group/nacos-sdk-rust ，或许这个 issue 可以关闭啦。
