### ISSUE TITLE
不健康的实例没有自动删除 版本1.4.1

### ISSUE THREAD

**Issue by lianglituan** [alibaba/nacos#8445]
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/51769592/169766019-058082fb-af9f-4810-9a01-70bbee2d21e4.png">

**Comment by onewe** [comment]
30秒后也没自动删除?

**Comment by lianglituan** [comment]
对的，都过去一天了也没删除

**Comment by onewe** [comment]
有复现的步骤吗？

**Comment by MajorHe1** [comment]
1.4.1版本已经过去挺久了，建议升级新版本试试看？
以及不要人为去控制台点下线操作，看看会不会自动剔除？

**Comment by lianglituan** [comment]
一开始就因为它不健康，过了很久也没注销，影响到服务调用了，所以才下线的。

**Comment by onewe** [comment]
集群模式？

**Comment by lianglituan** [comment]
这是我们测试环境，单机模式。 最近几天才出现这个问题。

**Comment by KomachiSion** [comment]
需要看下日志有没有相关信息

**Comment by lianglituan** [comment]
nacos server的日志还是 client的日志？

**Comment by KomachiSion** [comment]
server的

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
