### ISSUE TITLE
nacos服务端能单例跑standalone+外部数据库连接吗？

### ISSUE THREAD

**Issue by tiger822** [alibaba/nacos#8446]
如题，即使强制用下面参数启动
startup.cmd --server.port=8848 -p db --db=nacos-c1 -m standalone -Dnacos.standalone=true -DembeddedStorage=false

当使用了standalone模式还是会使用嵌入的数据库。

**Comment by MajorHe1** [comment]
修改一下conf目录的application.propertis，把db相关的配置解开注释加上数据库配置信息

**Comment by onewe** [comment]
可以 打开`application.propertis` 里的数据库配置

**Comment by tiger822** [comment]
> 可以 打开`application.propertis` 里的数据库配置

谢谢提醒，可以了。
