### ISSUE TITLE
集成Dubbo3 报错  java.lang.NoSuchMethodError: com.alibaba.nacos.api.config.ConfigService.publishConfigCas

### ISSUE THREAD

**Issue by ChenXueSong99** [alibaba/nacos#8448]
**Describe the bug**
SpringCloud 项目，使用 Nacos 2.1.0 作为注册配置中心，集成Dubbo 3.0.8 作为RPC支持，Dubbo3使用 nacos作为注册中心。
服务提供方 启动后 dubbo打印日志抛出异常，异常内容：
2022-05-24 10:08:02 [main] ERROR o.a.d.c.deploy.DefaultModuleDeployer -  [DUBBO] Dubbo Module[1.1.1] start failed: java.lang.NoSuchMethodError: com.alibaba.nacos.api.config.ConfigService.publishConfigCas(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z, dubbo version: 3.0.8, current host: 192.168.100.221
服务消费方启动正常，服务提供方 和 服务消费方，dubbo配置相同，具体dubbo配置会附录在实现bug复现步骤里面。
备注：Nacos 2.0.3 也报这个异常

**Expected behavior**
Dubbo3 支持使用 nacos作为注册中心，支持 Nacos 2.x 版本
**Acutally behavior**
服务提供方，启动发布元数据 报错，Dubbo 抛出异常 java.lang.NoSuchMethodError: com.alibaba.nacos.api.config.ConfigService.publishConfigCas

**How to Reproduce**
1. 运行环境
Windows11  openJDK 11
2. 服务
spring-cloud-alibaba 2021.1 作为基础框架支持，两个服务，服务提供方 服务消费方，使用 nacos 2.1.0 作为注册配置中心，集成 dubbo 3.0.8，服务提供方 提供一个可供消费的 接口
3. Maven配置：
````
           <!-- SpringCloud Alibaba-->
            <spring-cloud.version>2020.0.4</spring-cloud.version>
            <!-- SpringCloud Alibaba-->
            <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
            <!-- Nacos客户端 -->
            <nacos-client.version>2.1.0</nacos-client.version>
            <!-- dubbo3 RPC -->
            <dubbo.version>3.0.8</dubbo.version>

            <!-- Spring Cloud -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- Spring Cloud Alibaba -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

              <!-- nacos: 服务注册与发现 -->
              <dependency>
                  <groupId>com.alibaba.cloud</groupId>
                  <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                  <exclusions>
                      <exclusion>
                          <groupId>com.alibaba.nacos</groupId>
                          <artifactId>nacos-client</artifactId>
                      </exclusion>
                      <exclusion>
                          <groupId>org.springframework.cloud</groupId>
                          <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
                      </exclusion>
                  </exclusions>
              </dependency>
              <!-- nacos config：分布式配置中心 -->
              <dependency>
                  <groupId>com.alibaba.cloud</groupId>
                  <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                  <exclusions>
                      <exclusion>
                          <groupId>com.alibaba.nacos</groupId>
                          <artifactId>nacos-client</artifactId>
                      </exclusion>
                  </exclusions>
              </dependency>
              <dependency>
                  <groupId>com.alibaba.nacos</groupId>
                  <artifactId>nacos-client</artifactId>
                  <version>${nacos-client.version}</version>
              </dependency>

           <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>${dubbo.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-actuator</artifactId>
                <version>${dubbo.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
````

4. springboot application.yml dubbo配置

````
dubbo:
  application:
    logger: slf4j
    # 元数据中心 local 本地 remote 远程 这里使用远程便于其他服务获取
    metadataType: remote
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
    register-mode: instance
    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
      # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
      # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
      migration: FORCE_APPLICATION
  protocol:
    # 设置为 tri 即可使用 Triple 3.0 新协议
    # 性能对比 dubbo 协议并没有提升 但基于 http2 用于多语言异构等 http 交互场景
    # 使用 dubbo 协议通信
    name: dubbo
    # dubbo 协议端口(-1表示自增端口,从20880开始)
    port: -1
  # 注册中心配置
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}?namespace=${spring.cloud.nacos.discovery.namespace}
    group: DUBBO_GROUP
  # 消费者相关配置
  consumer:
    # 结果缓存(LRU算法)
    # 会有数据不一致问题 建议在注解局部开启
    cache: false
    # 支持校验注解
    validation: true
    # 超时时间
    timeout: 3000
    # 初始化检查
    check: false
  scan:
    # 接口实现类扫描
    base-packages: cn.acorg.**.dubbo
  # 自定义配置
  custom:
    # 全局请求log
    request-log: true
    # info 基础信息 param 参数信息 full 全部
    log-level: info
````

4. 启动nacos 后，启动服务提供方，服务消费方，服务提供方控制台抛出

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version nacos-server 2.1.0, nacos-client 2.1.0
 - Module  nacos-server namespace:641b6fdc-f21a-4307-b84e-b05286cbb0b2  username:nacos  password:nacos
 - SDK openJdk11  spring-cloud-alibaba 2021.1  nacos-client 2.1.0  dubbo 3.0.8

**Additional context**
服务启动控制台日志：
[服务消费方启动后控制台日志.txt](https://github.com/alibaba/nacos/files/8759286/default.txt)
[服务提供方启动后控制台日志.txt](https://github.com/alibaba/nacos/files/8759291/default.txt)

**Comment by chickenlj** [comment]
看看运行期的 nacos 是否是 2.x 版本，是不是包仲裁成 nacos 1.x 了

**Comment by karsonto** [comment]
建议在项目运行mvn dependency:tree排查版本问题

**Comment by ChenXueSong99** [comment]
> 建议在项目运行mvn依赖：tree排查版本
好的，我试一下

**Comment by ChenXueSong99** [comment]
> mvn dependency:tree
[INFO] +- com.alibaba.csp:sentinel-datasource-nacos:jar:1.8.2:compile
[INFO] |  +- com.alibaba.csp:sentinel-datasource-extension:jar:1.8.0:compile
[INFO] |  \- com.alibaba.nacos:nacos-client:jar:1.4.1:compile
[INFO] |     +- com.alibaba.nacos:nacos-common:jar:1.4.1:compile
[INFO] |     |  \- org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile
[INFO] |     |     +- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] |     |     +- org.apache.httpcomponents:httpcore-nio:jar:4.4.14:compile
[INFO] |     |     \- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |     +- com.alibaba.nacos:nacos-api:jar:1.4.1:compile


<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-nacos</artifactId>
    <version>${sentinel-datasource-nacos.version}</version>
</dependency>

应该是这个的原因

**Comment by karsonto** [comment]
看上去是这个问题

**Comment by ChenXueSong99** [comment]
> 看上去是这个问题
启动已经不报  java.lang.NoSuchMethodError: com.alibaba.nacos.api.config.ConfigService.publishConfigCas 这个异常了


> **描述bug** SpringCloud项目，使用Nacos 2.1.0作为注册配置中心，集成Dubbo 3.0.8注册作为RPC支持，Dubbo3使用nacos作为注册支持，Dubbo3使用nacos 抛出异常，异常打印内容： 2022-05 -24 10:08:02 [main] 错误 oadcdeploy.DefaultModuleDeployer - [DUBBO] Dubbo Module[1.1.1] 启动失败：java.lang.NoSuchMethodError: com.alibaba.nacos.api.config.ConfigService.publishConfigCas(Ljava/ lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z，dubbo版本：3.0.8，当前主机：192.168.100.221 服务方启动正常，服务提供方和服务消费方，dubbo配置不同，具体dubbo配置会附加在实现bug复现步骤里面。 备注：Nacos 2.0.3也报这个异常
> 
> **预期行为** Dubbo3 支持使用 nacos 作为注册中心，支持 Nacos 2.x 版本 **实际行为** 服务提供方启动发布元数据报错，Dubbo 抛出 java.lang.NoSuchMethodError: com.alibaba.nacos.api.config.ConfigService. publishConfigCas
> 
> **如何重现** 重现行为的步骤：
> 
> 1. 运行环境
>    Windows11 openJDK 11
> 2. cloud-alibaba 2021.1
>    作为基础框架支持，两个服务，服务方 消费服务方，使用nacos 2. 作为配置集成，dubbo 3.0.8注册服务提供方提供一个服务，11. 春季消费中心提供的接口
> 3. Maven配置：
> 
> ```
>            
>             <spring-cloud.version>2020.0.4</spring-cloud.version>
>             
>             <spring-cloud-alibaba.version>2021.1</spring-cloud-alibaba.version>
>             
>             <nacos-client.version>2.1.0</nacos-client.version>
>             
>             <dubbo.version>3.0.8</dubbo.version>
> 
>             
>             <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-dependencies</artifactId>
>                 <version>${spring-cloud.version}</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>             
>             <dependency>
>                 <groupId>com.alibaba.cloud</groupId>
>                 <artifactId>spring-cloud-alibaba-dependencies</artifactId>
>                 <version>${spring-cloud-alibaba.version}</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
> 
>               
>               <dependency>
>                   <groupId>com.alibaba.cloud</groupId>
>                   <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
>                   <exclusions>
>                       <exclusion>
>                           <groupId>com.alibaba.nacos</groupId>
>                           <artifactId>nacos-client</artifactId>
>                       </exclusion>
>                       <exclusion>
>                           <groupId>org.springframework.cloud</groupId>
>                           <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
>                       </exclusion>
>                   </exclusions>
>               </dependency>
>               
>               <dependency>
>                   <groupId>com.alibaba.cloud</groupId>
>                   <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
>                   <exclusions>
>                       <exclusion>
>                           <groupId>com.alibaba.nacos</groupId>
>                           <artifactId>nacos-client</artifactId>
>                       </exclusion>
>                   </exclusions>
>               </dependency>
>               <dependency>
>                   <groupId>com.alibaba.nacos</groupId>
>                   <artifactId>nacos-client</artifactId>
>                   <version>${nacos-client.version}</version>
>               </dependency>
> 
>            <dependency>
>                 <groupId>org.apache.dubbo</groupId>
>                 <artifactId>dubbo-spring-boot-starter</artifactId>
>                 <version>${dubbo.version}</version>
>             </dependency>
> 
>             <dependency>
>                 <groupId>org.apache.dubbo</groupId>
>                 <artifactId>dubbo-spring-boot-actuator</artifactId>
>                 <version>${dubbo.version}</version>
>             </dependency>
> 
>             <dependency>
>                 <groupId>org.apache.dubbo</groupId>
>                 <artifactId>dubbo</artifactId>
>                 <version>${dubbo.version}</version>
>             </dependency>
> ```
> 
> 4. springboot application.yml dubbo配置
> 
> ```
> dubbo:
>   application:
>     logger: slf4j
>     # 元数据中心 local 本地 remote 远程 这里使用远程便于其他服务获取
>     metadataType: remote
>     # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
>     register-mode: instance
>     service-discovery:
>       # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
>       # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
>       # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
>       migration: FORCE_APPLICATION
>   protocol:
>     # 设置为 tri 即可使用 Triple 3.0 新协议
>     # 性能对比 dubbo 协议并没有提升 但基于 http2 用于多语言异构等 http 交互场景
>     # 使用 dubbo 协议通信
>     name: dubbo
>     # dubbo 协议端口(-1表示自增端口,从20880开始)
>     port: -1
>   # 注册中心配置
>   registry:
>     address: nacos://${spring.cloud.nacos.discovery.server-addr}?namespace=${spring.cloud.nacos.discovery.namespace}
>     group: DUBBO_GROUP
>   # 消费者相关配置
>   consumer:
>     # 结果缓存(LRU算法)
>     # 会有数据不一致问题 建议在注解局部开启
>     cache: false
>     # 支持校验注解
>     validation: true
>     # 超时时间
>     timeout: 3000
>     # 初始化检查
>     check: false
>   scan:
>     # 接口实现类扫描
>     base-packages: cn.acorg.**.dubbo
>   # 自定义配置
>   custom:
>     # 全局请求log
>     request-log: true
>     # info 基础信息 param 参数信息 full 全部
>     log-level: info
> ```
> 
> 4. 提供服务方，启动消费方，服务提供方后开始
> 
> **桌面（请填写以下信息）：**
> 
> * 操作系统：Windows11
> * 版本 nacos-server 2.1.0，nacos-client 2.1.0
> * 模块 nacos-server 命名空间：641b6fdc-f21a-4307-b84e-b05286cbb0b2 用户名：nacos 密码：nacos
> * SDK openJdk11 spring-cloud-alibaba 2021.1 nacos-client 2.1.0 dubbo 3.0.8
> 
> **附加上下文** 服务启动分析： [服务消费方启动后分析.txt](https://github.com/alibaba/nacos/files/8759286/default.txt) [服务开始分析.txt](https://github.com/alibaba/nacos/files/8759291/default.txt)

**Comment by ChenXueSong99** [comment]
> 看上去是这个问题
已经不报这个错误了

**Comment by darth001** [comment]
```
mvn dependency:tree
[INFO] +- com.alibaba.csp:sentinel-datasource-nacos:jar:1.8.2:compile
[INFO] | +- com.alibaba.csp:sentinel-datasource-extension:jar:1.8.0:compile
[INFO] | - com.alibaba.nacos:nacos-client:jar:1.4.1:compile
[INFO] | +- com.alibaba.nacos:nacos-common:jar:1.4.1:compile
[INFO] | | - org.apache.httpcomponents:httpasyncclient:jar:4.1.4:compile
[INFO] | | +- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] | | +- org.apache.httpcomponents:httpcore-nio:jar:4.4.14:compile
[INFO] | | - org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] | +- com.alibaba.nacos:nacos-api:jar:1.4.1:compile
```
