### ISSUE TITLE
Nacos configures NacosConfigurationProperties on a class and cannot get a configuration other than DEFALUT_GROUP

### ISSUE THREAD

**Issue by longlylong** [alibaba/nacos#845]
nacos 在类上配置
@NacosConfigurationProperties(dataId = "gateway-local.properties", groupId = "GATEWAY_GROUP", autoRefreshed = true)
获取不到该组的配置 求解释

不配置可以获取到DEFALUT_GROUP的

**Comment by hxy1991** [comment]
已经新建了该配置了么？

**Comment by longlylong** [comment]
已确认有的。
通过NacosConfigurationProperties 这个配置是生效的吗？

**Comment by hxy1991** [comment]
> 已确认有的。
> 通过NacosConfigurationProperties 这个配置是生效的吗？

可以的。请参看下 [nacos-spring-config-pojo-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-example/nacos-spring-config-pojo-example)

或者提供下你的 Demo

**Comment by longlylong** [comment]
SpringCloud的项目好像不生效哦

**Comment by hxy1991** [comment]
> SpringCloud的项目好像不生效哦

请参看下 [nacos-spring-cloud-config-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example)
