### ISSUE TITLE
nacos v1.4.3 config data not exist

### ISSUE THREAD

**Issue by missfmaster** [alibaba/nacos#8451]
look this:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/13460299/170011988-4bb6035a-e3e3-453f-b8c6-ab3780afaa7e.png">

use : http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=common.yml&tenant=test&group=DEFAULT_GROUP
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/13460299/170012144-165d760d-f9f5-4482-b2a3-bfd423c122a5.png">

use : http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=common2.yml&tenant=test&group=DEFAULT_GROUP
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/13460299/170012362-c686e54c-9b91-4e2d-aaae-6b1f41a45f37.png">

so, anybody can tell me why?
<img width="135" alt="image" src="https://user-images.githubusercontent.com/13460299/170012600-3e0c141b-1843-4556-8190-ebc81c5231af.png">

**Comment by MajorHe1** [comment]
这个是在1.4.3版本上稳定复现吗

**Comment by MajorHe1** [comment]
我下了个 1.4.3的release包，本地启动，单机模式，内置数据库，无法复现这样的场景
![image](https://user-images.githubusercontent.com/53824889/170269728-fb8c2d28-0922-4ca0-b183-d33c0fd54390.png)
![image](https://user-images.githubusercontent.com/53824889/170269748-3878445a-9d08-4181-a2e2-3b2aad72a2b4.png)
![image](https://user-images.githubusercontent.com/53824889/170269768-1eb9a167-c5d0-4847-ae80-8289a02f7218.png)

**Comment by missfmaster** [comment]
> 这个是在1.4.3版本上稳定复现吗

是1.4.3版本上出现的，但是不排除其他版本也会出现。

并不是稳定出现，存在偶然性。

**Comment by missfmaster** [comment]
所以，在nacos中，可能会因为配置文件内容，而导致一个找不到配置文件的bug。

**Comment by MajorHe1** [comment]
删除配置文件重新建立
============
能详细说一下是个什么操作吗

**Comment by missfmaster** [comment]
> 

额，就是把common.yml删除，然后再新建一遍。。。
