### ISSUE TITLE
Alibaba Summer of Code (ASOC) 2022

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#8456]
# Alibaba Summer of Code (ASOC) 2022
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open source project and work with the core members of the project.

This is a master issue to track the progress and result of [Alibaba Summer of Code 2022](https://opensource.alibaba.com/asoc2022).

## What you can get?
On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship
- Get your code adopted and used by the open source project！
## Our Mentor

- @[xuechaos](https://github.com/xuechaos)  [xingxuechao@alibaba-inc.com](mailto:xingxuechao@alibaba-inc.com)
- @[yanlinly](https://github.com/yanlinly) [water.lyl@alibaba-inc.com](water.lyl@alibaba-inc.com)
- @[realJackSun](https://github.com/realJackSun) yongyue.sl@alibaba-inc.com

## Timeline
![timeline](https://user-images.githubusercontent.com/7144772/170005564-c0760a69-e153-455d-ac87-430c35409431.png)

## Apply Now!

1. Browse open idea list here:

- https://github.com/alibaba/nacos/issues/8458 *Difficulty：Advance*
- https://github.com/alibaba/nacos/issues/8460 *Difficulty：Basic*
- https://github.com/alibaba/nacos/issues/8461 *Difficulty：Basic*

2. Upload your CV and project proposal via [ASOC 2022 official website](https://opensource.alibaba.com/asoc2022)

## Contact the Organizer
If you have any questions, visit the event website: https://opensource.alibaba.com/asoc2022

Email address: [opensource@alibaba-inc.com](mailto:opensource@alibaba-inc.com)

---

# 阿里巴巴编程之夏 (ASOC) 2022
欢迎来到开源世界！ 如果你还没有计划如何度过这个夏天，那就来阿里巴巴编程之夏和我们一起编程吧！ 💻

阿里巴巴编程之夏是一个全球性项目，专注于让学生直接参与开源软件开发。 在阿里巴巴开源项目导师的指导下，学生可以在现实世界中体验软件开发。 

阿里巴巴代码之夏将于 5 月 30 日至 9 月 1 日开始。 学生可以利用暑期参与开源项目，与项目核心成员一起工作。

## 参与活动能获得什么？
在这个独家开发者之旅中，学生将有机会：

- 参与国际开源基金会的顶级项目；
- 获得阿里巴巴奖学金；
- 获得开源贡献者证书；
- 获得阿里巴巴实习快速通行证
- 让你的代码被开源项目采纳和使用！

## 活动导师

- @[xuechaos](https://github.com/xuechaos)  [xingxuechao@alibaba-inc.com](mailto:xingxuechao@alibaba-inc.com)
- @[yanlinly](https://github.com/yanlinly) [water.lyl@alibaba-inc.com](water.lyl@alibaba-inc.com)
- @[realJackSun](https://github.com/realJackSun) yongyue.sl@alibaba-inc.com

## 活动里程碑
![timeline](https://user-images.githubusercontent.com/7144772/170005564-c0760a69-e153-455d-ac87-430c35409431.png)

## 立刻申请！

1. 浏览如下课题列表：

- https://github.com/alibaba/nacos/issues/8458 *难度：进阶*
- https://github.com/alibaba/nacos/issues/8460 *难度：基础*
- https://github.com/alibaba/nacos/issues/8461 *难度：基础*

2. 通过[ASOC 2022 官网](https://opensource.alibaba.com/asoc2022)上传您的简历和项目提案

## 联系主办方
如有任何问题，请访问活动网站：https://opensource.alibaba.com/asoc2022

邮箱：[opensource@alibaba-inc.com](mailto:opensource@alibaba-inc.com)

**Comment by xiao-qiangdada** [comment]
大专行么(dog)

**Comment by KomachiSion** [comment]
> 大专行么(dog)

可以，只要有可认证的学生证即可。

**Comment by view6view** [comment]
冲冲冲，混个眼熟
