### ISSUE TITLE
（这个可以忽略了）配置在java代码里是String类型，  在nacos里配置值是0开头的话，就把0给摸平了 

### ISSUE THREAD

**Issue by DeBruyne2020** [alibaba/nacos#8457]
配置值在代码里是String类型，  如下图：
![image](https://user-images.githubusercontent.com/68886035/170236465-162ff0b8-4cf0-42fa-a5c3-5e7b9fc9ff97.png)

在nacos里配置值是0开头的话，就把0给摸平了 ，比如配置成000，
![image](https://user-images.githubusercontent.com/68886035/170236866-184b389a-c670-4a23-8eee-700ba63f87c8.png)
结果最终是0，
![image](https://user-images.githubusercontent.com/68886035/170237062-0391d9ee-8989-4c63-84cd-3198a1e3fb4e.png)

如果配是01，结果最终成了1
![image](https://user-images.githubusercontent.com/68886035/170237316-5334c27f-8a26-458f-a29a-4ad898baea6e.png)

**Comment by onewe** [comment]
你加上双引号

**Comment by DeBruyne2020** [comment]
> 这个不是nacos这边的问题,是 yaml 解析如此

@onewe   你说的对的，确实，
