### ISSUE TITLE
[ASoC 2022] Nacos supports abilities negotiation capability (Nacos 支持能力协商功能)

### ISSUE THREAD

**Issue by KomachiSion** [alibaba/nacos#8458]
# Background
This is an Advance subject of [ASoC 2022](https://opensource.alibaba.com/asoc2022) and #8456 .

As the Nacos community becomes more active and the abilities become more diverse, the degree of support for new abilities will vary greatly between different versions.

At present, many abilities are judged according to the version number, and the readability, maintainability and scalability are very poor. Therefore, I hope that students can design a capability negotiation mechanism to coordinate and aggregate the supported capabilities between the Nacos client and server, and between the server and the server.

# Target
Design and implement the capability negotiation mechanism of Nacos, so that between the client and the server of Nacos, the server nodes can obtain whether the other party supports a certain function through this mechanism, so as to negotiate whether to use the function to operate.

# Difficulty

*Advance*

# Mentor

- @[xuechaos](https://github.com/xuechaos) xingxuechao@alibaba-inc.com

# Output Requirements
- Design a capability negotiation mechanism, you can refer to the similar mechanism design of MySQL;
- Select an appropriate design mode to implement the capability negotiation mechanism;
- Provide complete design documentation and add unit tests;

# Technical Requirements
- Familiar with Java;
- Familiar with design patterns;
- Get to know Nacos;
- Understand MySQL login protocol or other capability negotiation protocols;

----------------

# 背景
这是一个[阿里巴巴编程之夏 2022](https://opensource.alibaba.com/asoc2022) 的进阶课题 #8456 。

随着Nacos社区越来越活跃，功能越来越多，不同版本间对新增功能的支持程度也会有较大区别。

目前很多功能都是根据版本号来进行判断，可读性，可维护性以及可扩展性都很差。因此希望同学能够设计一个能力协商机制，在Nacos的客户端与服务端之间，以及服务端与服务端之间对所支持的能力进行统筹聚合。

# 目标
设计并实现Nacos的能力协商机制，使得Nacos的客户端与服务端之间，服务端节点之间能够通过该机制获取对方是否支持某个功能，以协商决定是否采用该功能进行运作。

# 难度

*进阶*

# 导师

- @[xuechaos](https://github.com/xuechaos) xingxuechao@alibaba-inc.com

# 产出要求
- 设计能力协商机制，可参考MySQL的类似机制设计；
- 选择合适的设计模式，实现该能力协商机制;
- 提供完善的设计文档，并添加单元测试;

# 能力要求
- 熟悉 Java；
- 熟悉设计模式；
- 了解 Nacos；
- 了解MySQL登陆协议或其他能力协商协议；

**Comment by chuntaojun** [comment]
if not one assign, can i try it ?
