### ISSUE TITLE
Nacos集群模式下，某个节点重启后注册到nacos各节点上的服务数量不一致

### ISSUE THREAD

**Issue by ding11110991** [alibaba/nacos#8465]
**Describe the bug**
nacos版本2.0.3。集群模式部署在阿里云k8s上，启用三个nacos节点，每个节点上注册9个服务。其中一个节点重启后，刷新nacos控制台的服务列表，发现每个节点的服务数量不一致。

**Comment by Johnson-Jia** [comment]
这俩是不是同一个问题引起的 ？  #8464

**Comment by KomachiSion** [comment]
应该是你集群搭建有问题，导致你集群数据无法同步，所以出现了不一致的情况 。

**Comment by ding11110991** [comment]
> 应该是你集群搭建有问题，导致你集群数据无法同步，所以出现了不一致的情况 。

请问有哪些点可能导致集群数据同步失败呢，nacos2.0的端口偏移量也设置了呀。

> 这俩是不是同一个问题引起的 ？ #8464

不清楚呀，看你的描述好像不是一个问题

**Comment by KomachiSion** [comment]
> > 应该是你集群搭建有问题，导致你集群数据无法同步，所以出现了不一致的情况 。
> 
> 请问有哪些点可能导致集群数据同步失败呢，nacos2.0的端口偏移量也设置了呀。
> 
> > 这俩是不是同一个问题引起的 ？ #8464
> 
> 不清楚呀，看你的描述好像不是一个问题

k8s环境容易出的2个问题：
1. 配置的host和实际的host不同
2. 配置的host但是实际使用的是ip

这两个问题是k8s环境最容易遇到的问题，可以去看一下cluster.conf中是不是有多出来的ip或者host。还有就是服务端日志是不是有不认识的ip或者host。

**Comment by ding11110991** [comment]
![image](https://user-images.githubusercontent.com/36905453/170929037-de8a208f-886c-45fa-a022-45f888c2228f.png)
![image](https://user-images.githubusercontent.com/36905453/170928846-bab73544-d946-45f7-a0e0-10e51bdc6db1.png)
![image](https://user-images.githubusercontent.com/36905453/170929098-dcd21ca9-eabb-4904-879b-00a303037cfc.png)
图一是cluster.conf的配置，看起来没什么问题，图2和图3是nacos-1节点自动重启后日志文件报的错，为啥会报这个错咧

**Comment by KomachiSion** [comment]
这不是报错unknownHost了吗？ 自查环境吧。
