### ISSUE TITLE
修改nacos配置

### ISSUE THREAD

**Issue by zhizuntop** [alibaba/nacos#8469]
启动nacos
服务详情-编辑服务 填写元数据，提示：服务详情caused: metadata format incorrect
[
    {
        "id": "xxxxid",
    "predicates": [
      {
        "args": {
          "pattern": "xxxx/**"
        },
        "name": "Path"
      }
    ],
    "uri": "lb://xxxx"
    }
]

请问是什么问题？

**Comment by KomachiSion** [comment]
元数据是kv格式的， predicates是数组的value，应该不支持

**Comment by KomachiSion** [comment]
No more response from author, seems usage problem.
