### ISSUE TITLE
服务实例一直都在，但健康检查一直返回20404，导致无法正常提供服务

### ISSUE THREAD

**Issue by DemoMoon** [alibaba/nacos#8470]
**Describe the bug**
服务实例一直都在，客户端心跳健康检查一直返回20404，导致无法正常提供服务.
管理服务详情页面 ，点击下线 提示 “caused: instance not exist: 172.26.59.85:8030:unknown:DEFAULT_1.0_true_false_DEFAULT;”

**Expected behavior**
健康检查能够返回10200，能够正常提供服务.

**Acutally behavior**
客户端心跳健康检查一直返回20404，导致无法正常提供服务.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [CentOS Linux release 7.6.1810]
 - Version [e.g. nacos-server 2.0.2, nacos-client 1.3.2]
 - Module [e.g. naming/config]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**
![image](https://user-images.githubusercontent.com/5241098/170676353-72e79f89-348f-4a03-9be9-1f87fa36df3b.png)
![1653645186(1)](https://user-images.githubusercontent.com/5241098/170676458-fed57ce9-fa44-4df4-a5af-be84b264e8e2.png)
naming log
[81.tar.gz](https://github.com/alibaba/nacos/files/8785822/81.tar.gz)
[82.tar.gz](https://github.com/alibaba/nacos/files/8785829/82.tar.gz)
[83.tar.gz](https://github.com/alibaba/nacos/files/8785826/83.tar.gz)

**Comment by DemoMoon** [comment]
@KomachiSion 大佬 烦请 抽空帮忙看看什么原因哈？感谢了。

**Comment by moil-xm** [comment]
> @KomachiSion 大佬 烦请 抽空帮忙看看什么原因哈？感谢了。

https://github.com/alibaba/nacos/issues/6109 好像是这个

**Comment by DemoMoon** [comment]
把这个应用服务换台机器重新注册，会不会正常提供服务呢？大约有10几个服务，就它目前是单点提供服务。

**Comment by DemoMoon** [comment]
> 把这个应用服务换台机器重新注册，会不会正常提供服务呢？大约有10几个服务，就它目前是单点提供服务。

刚验证一下，也不行，魔怔了。

**Comment by KomachiSion** [comment]
心跳检查20404的时候，客户端会重新注册服务进去，我感觉你可能是把多台节点都是用单例模式启动了。没有责任节点导致的

**Comment by DemoMoon** [comment]
> 心跳检查20404的时候，客户端会重新注册服务进去，我感觉你可能是把多台节点都是用单例模式启动了。没有责任节点导致的

/usr/local/jdk/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/usr/local/jdk/jre/lib/ext:/usr/local/jdk/lib/ext -Xloggc:/data/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/data/nacos/plugins/health,/data/nacos/plugins/cmdb -Dnacos.home=/data/nacos -jar /data/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/data/nacos/conf/ --logging.config=/data/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 2.0.2
,`--.'`|  ' :                       ,---.               Running in cluster mode, All function modules
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 4198
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://172.26.59.81:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

2022-03-21 09:23:31,672 INFO The server IP list of Nacos is [172.26.59.81:8848, 172.26.59.82:8848, 172.26.59.83:8848]

**Comment by DemoMoon** [comment]
不是单例模式的

**Comment by DemoMoon** [comment]
![image](https://user-images.githubusercontent.com/5241098/170905316-cce0cf54-5d8c-4a62-8cc8-d7aa89878f7f.png)

**Comment by DemoMoon** [comment]
![1653877369(1)](https://user-images.githubusercontent.com/5241098/170905781-0455bf73-6f14-4dce-8011-c02235e3f1bf.png)
这两个节点的时间 有点诡异啊

**Comment by DemoMoon** [comment]
![1653877556(1)](https://user-images.githubusercontent.com/5241098/170906061-ca289be4-3214-43c1-8605-5d351e2295b4.png)

**Comment by DemoMoon** [comment]
@KomachiSion

**Comment by DemoMoon** [comment]
81的 nacos 重启了一下，可以正常提供服务了。再观察观察吧。
![1653905266(1)](https://user-images.githubusercontent.com/5241098/170970032-961d8c5b-15bb-4dc0-ae8d-9a3179c0fb2e.png)

**Comment by KomachiSion** [comment]
No more response from author, new version may solve this problem.
