### ISSUE TITLE
[Dependency Governance] Remove useless dependencies.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#8472]
**Is your feature request related to a problem? Please describe.**
Too many useless dependencies, too many and confusing.
太多无用依赖，多且让人费解。

**Describe the solution you'd like**
Dependency Governance, remove useless dependencies.
依赖治理，去除无用依赖。

**Describe alternatives you've considered**
Perhaps many of the dependencies were initially added, and after optimization and upgrading, useless dependencies were not removed.
或许很多是初期加入的依赖，然后经过优化升级后，无用的依赖就没有被去除。

**Additional context**
`mvn clean install -Dmaven.test.skip=true -P release-nacos`
Make sure there are no compile errors.
务必已保障没有编译错误。

**Comment by KomachiSion** [comment]
请先在提交PR前在issue中列举无用依赖，
讨论后再提交PR。

**Comment by CherishCai** [comment]
1. 无用上的依赖 jcip-annotations
```xml
        <dependency>
            <groupId>net.jcip</groupId>
            <artifactId>jcip-annotations</artifactId>
            <optional>true</optional>
        </dependency>

            <dependency>
                <groupId>com.google.truth</groupId>
                <artifactId>truth</artifactId>
                <version>${truth.version}</version>
            </dependency>

            <!-- commons-logging nacos 项目自身无用，可由需要的三方依赖嵌套引入 -->
            <dependency>
                <groupId>commons-logging</groupId>
                <artifactId>commons-logging</artifactId>
                <version>${commons-logging.version}</version>
            </dependency>

            <!-- commons-dbcp 无用，用的是 HikariCP -->
            <dependency>
                <groupId>commons-dbcp</groupId>
                <artifactId>commons-dbcp</artifactId>
                <version>${commons-dbcp.version}</version>
            </dependency>

            <!-- commons-logging nacos 项目自身无用 -->
            <dependency>
                <groupId>commons-cli</groupId>
                <artifactId>commons-cli</artifactId>
                <version>${commons-cli.version}</version>
            </dependency>
```
![image](https://user-images.githubusercontent.com/16837364/170903151-8ac8f742-f879-4a80-a558-775a45bfe4b1.png)
![image](https://user-images.githubusercontent.com/16837364/170903672-fbea3973-0265-4951-b814-ca307f965b39.png)


2. aop 可以由 spring-aop 统一依赖
```xml
        <!-- for aop -->
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
        </dependency>
        <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib-nodep</artifactId>
        </dependency>
```

3. no jsp, all rest api, delete tomcat-embed-jasper
```xml
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-jasper</artifactId>
                <version>${tomcat-embed-jasper.version}</version>
            </dependency>
```

4. hamcrest 可以由 spring-boot-stater-test 统一依赖
![image](https://user-images.githubusercontent.com/16837364/170904128-b7243e47-e35d-4470-b45a-eab1609fe5c5.png)

**Comment by CherishCai** [comment]
1. grpc-netty-shaded already shaded netty for grpc.  nacos-api 也不需要它。nacos 项目自身已经没有直接使用 netty。

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/16837364/170812910-35d99cc5-93e2-479d-85be-37daa4b3d8cb.png">

**Comment by KomachiSion** [comment]
> jcip-annotations

这个应该可以删，可能是以前有引入过ThreadSafe或者NotThreadSafe, 移除掉编译不报错就行。

> commons-dbcp

可以删， 以前用的dbcp，1.3以后换成hikari了

> truth

应该可以删， 测试框架应该是Junit4

> aop

可以删

> jsp

可以删

----

> commons-logging和commons-cli

这个不确定，可以再讨论下

----

> hamcrest

这个不能删，api，common，client没有依赖spring，还需要依赖

**Comment by CherishCai** [comment]
> commons-logging和commons-cli
> 这个不确定，可以再讨论下

commons-cli 确实没有被使用，commons-logging 会被其他用到的地方嵌套依赖进来，nacos 获取日志都是 Slf4j 门面 api。

---

> hamcrest
> 这个不能删，api，common，client没有依赖spring，还需要依赖

这个晚点我回滚下，会和 netty 依赖那个提交冲突 pom.xml，所以等那个 PR 合并了我再 rebase 同时回滚 hamcrest 的变动。

**Comment by CherishCai** [comment]
不好意思，重新看了下依赖情况。hamcrest 会被 junit 嵌套依赖，所以是不需要指定的

以下是 api 模块的依赖图，主 pom.xml 去掉 hamcrest 是没问题的。

![image](https://user-images.githubusercontent.com/16837364/171379524-474d942f-ba49-4803-b7c7-c9081969e56e.png)

![image](https://user-images.githubusercontent.com/16837364/171379933-4fc53ac7-1274-4744-a71c-4172c7baeb90.png)

**Comment by KomachiSion** [comment]
> 不好意思，重新看了下依赖情况。hamcrest 会被 junit 嵌套依赖，所以是不需要指定的
> 
> 以下是 api 模块的依赖图，主 pom.xml 去掉 hamcrest 是没问题的。
> 
> ![image](https://user-images.githubusercontent.com/16837364/171379524-474d942f-ba49-4803-b7c7-c9081969e56e.png)
> 
> ![image](https://user-images.githubusercontent.com/16837364/171379933-4fc53ac7-1274-4744-a71c-4172c7baeb90.png)

ok

**Comment by KomachiSion** [comment]
> > commons-logging和commons-cli
> > 这个不确定，可以再讨论下
> 
> commons-cli 确实没有被使用，commons-logging 会被其他用到的地方嵌套依赖进来，nacos 获取日志都是 Slf4j 门面 api。
> 
> > hamcrest
> > 这个不能删，api，common，client没有依赖spring，还需要依赖
> 
> 这个晚点我回滚下，会和 netty 依赖那个提交冲突 pom.xml，所以等那个 PR 合并了我再 rebase 同时回滚 hamcrest 的变动。

那`commons-logging`改成optinal+provided吧，观察几个版本看看

**Comment by CherishCai** [comment]
> 那`commons-logging`改成optinal+provided吧，观察几个版本看看

其实，是不用的。也 cherry-pick 此提交内部发布了，它会被其他三方依赖嵌套引入。
![image](https://user-images.githubusercontent.com/16837364/172085447-aaf0aaef-d178-4515-9a75-7d98357904d5.png)

![image](https://user-images.githubusercontent.com/16837364/172085872-a19ebbfb-499f-4b08-ad6f-ad19c653bf2d.png)
