### ISSUE TITLE
单纯订阅服务 列表，30 秒后订阅信息会被删掉，后续就收不到udp 推送了。

### ISSUE THREAD

**Issue by zhwaaaaaa** [alibaba/nacos#8478]
我在开发nginx 模块。通过 http 订阅服务ip 信息。

```GET /nacos/v1/ns/instance/list?serviceName=aaa%40%40cc&udpPort=7878&clientIP=127.0.0.1```

看了下 nacos 的代码。30s 后订阅信息会被删掉。
```java
class ConnectionBasedClient {
//....
   public boolean isExpire(long currentTime) {
        return !isNative() && currentTime - getLastRenewTime() > ClientConfig.getInstance().getClientExpiredTime();//30s
    }
}
```
不知道有什么简单方法可以更新lastRenewTime。订阅的clientid 被删除。

不想重新发送 /nacos/v1/ns/instance/list 请求。因为我订阅的 service 非差多，又会马上收到 udp 的推送，ip 并没有更新。

**Comment by KomachiSion** [comment]
那请更换成2.0+客户端。 1.x客户端所有的续约都是以心跳形式发送的，你订阅之后会自动间隔一段时间发送 /nacos/v1/ns/instance/list

**Comment by KomachiSion** [comment]
如果不发送 /nacos/v1/ns/instance/list续约，服务端就无法续约这个客户端，那被移除订阅者是自然的。

另外你截图的代码是长链接的代码，是2.0+客户端的对应代码， 和 /nacos/v1/ns/instance/list无关

**Comment by zhwaaaaaa** [comment]
大佬，我不是使用客户端的，我是在给nginx 写订阅 nacos 的模块，nacos 版本是2.1.0。。现在 订阅的方式是 调用， /nacos/v1/ns/instance/list。但是只是启动的时候调用一次。 发现了这个问题。大佬有什么解法吗，我这个使用场景有点特殊

**Comment by zhwaaaaaa** [comment]
大佬，我不是使用客户端的，我是在给nginx 写订阅 nacos 的模块，nacos 版本是2.1.0。。现在 订阅的方式是 调用， /nacos/v1/ns/instance/list。但是只是启动的时候调用一次。 发现了这个问题。大佬有什么解法吗，我这个使用场景有点特殊

**Comment by zhwaaaaaa** [comment]
大佬，我一个ip 订阅1000个服务，但是 我 只给一个服务续约， 好些其它服务也能收到推送。大佬觉得这个方案可行吗。 假设 nacos 重启了， 其它 999 个服务是否还能收到推送。

**Comment by KomachiSion** [comment]
应该可以，续约应该是根据ip port进行的。

**Comment by KomachiSion** [comment]
No more response from author.
