### ISSUE TITLE
为什么Nacos中的很多单例模式类的构造方法不是私有

### ISSUE THREAD

**Issue by MRGUOKING** [alibaba/nacos#8479]
为什么Nacos源码中common模块下的NotifyCenter类，plugin-auth模块下的AuthPluginManager类都是以单例模式来使用，但是构造方法都不是私有的。
![image](https://user-images.githubusercontent.com/55344330/170866471-91400678-f179-4996-b2a7-dccf6f464fc1.png)

**Comment by KomachiSion** [comment]
应该是社区同学用的IDE自动生成的构造函数，但是没改作用域，可以分析一下哪些是这样的，然后提一个PR改一下。

**Comment by MRGUOKING** [comment]
@KomachiSion OK, 我尝试提交以下PR

**Comment by tankist141091** [comment]
> 为什么Nacos源码中common模块下的NotifyCenter类，plugin-auth模块下的AuthPluginManager类都是以单例模式来使用，但是构造方法都不是私有的。 ![image](https://user-images.githubusercontent.com/55344330/170866471-91400678-f179-4996-b2a7-dccf6f464fc1.png)
