### ISSUE TITLE
我在springboot里如何配置 9848 9849端口

### ISSUE THREAD

**Issue by shouziws** [alibaba/nacos#8483]
我在springboot里如何主动配置 9848 9849端口 rt

**Comment by KomachiSion** [comment]
没看懂问题

**Comment by shouziws** [comment]
> 没看懂问题

我在springboot里如何主动配置9848 9849的连接地址和端口

**Comment by KomachiSion** [comment]
还是没看懂。。。

客户端服务端？
为什么要配置9848？
文档仔细读过吗？

**Comment by shouziws** [comment]
> 为什么要配置9848？

就是我现在是通过k8s部署的nacos测试环境，连接的时候我使用的是traefik nodeport去match nacos的service ip，此时有3个端口，需要进行匹配，我在使用traefik匹配的时候host加上8848或者9948端口就无法匹配，所以才出此下策全部用80端口去匹配，修改springboot对应的连接地址

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

看一下这个文档吧，我理解你的问题和nacos没什么关系。

客户端只要配置1个端口，其他的会自动计算。
