### ISSUE TITLE
nacos是否可以提供版本升级方案

### ISSUE THREAD

**Issue by xb2369** [alibaba/nacos#8484]
在使用过程中发现2.0.4版本存在BUG,希望升级至2.1.0时发现并无官方升级文档；
例如：部分标新增字段，是否可以在压缩包里面体现某个版本新增得字段或者数据。

希望能给出小版本升级方案。

**Comment by KomachiSion** [comment]
1.X升级2.X请参考官方升级文档。

2.X互相升级，不需要文档，就是单纯替换jar包和conf文件。压缩包内的conf目录下有sql文件，每次升级前校验一下表结构。

**Comment by xb2369** [comment]
能否在.sql 里面提供显示 
例如：v 2.1.0 新增字段。
###sql 脚本
