### ISSUE TITLE
nacos集群各节点的注册服务数量不一致！

### ISSUE THREAD

**Issue by pinpindao** [alibaba/nacos#8492]
nacos版本2.0.3
环境：centos7.8
集群节点：
192.168.0.10
192.168.0.13
192.168.0.30

集群初始状态下30节点为leader，共注册了9个微服务
![image](https://user-images.githubusercontent.com/106652818/171348472-d8a1d8e6-4807-4b69-a059-7283cb180152.png)

然后做了如下测试验证：
1. 停掉30节点的nacos，leader 节点切换成10节点，启动30，  三台节点leader都是10
2. 停10节点的nacos，刷新 其他2台主节点 leader  13 
3. 停13节点的nacos，刷新30节点  leader 还是13
4. 启动10和13 刷新 发现每台节点上注册的服务数量不一致，节点数据上查看leader也不一致

10节点服务数量变成3个
![image](https://user-images.githubusercontent.com/106652818/171349043-9c567186-cc3c-4544-af79-79b28c9798f7.png)

节点预元数据显示leader也不一致
![image](https://user-images.githubusercontent.com/106652818/171349548-4bee3934-b634-4299-bd83-27c08f96f94d.png)

**Comment by yejiawei0** [comment]
我们也遇到了 nacos 2.0.3 集群 3个  挂了其中一台机器一晚上后  第二天启动nacos  挂掉的那台不能同步nacos其他集群所注册的所有服务，并且重启也不生效， mv 挂掉的那台 /data  重启也没有作用， 在夜深人静的晚上  我们把nacos集群都停了 mv data 从好的节点开始启动 才慢慢开始把注册上来的服务都同步到集群内 。  但是好景不长 第二天发现另一台机器的注册服务数量与集群其他节点又不同了。

最终 我们把nacos 部署到了docker中 以单节点的方式  草草结束了战斗  

nacos issues 遇到相同问题的太多了 
而且观察源码 发现应该是 集群内部 对于临时数据共享 有比较严重的bug  其他几贴issues 已经详细的描述了   

有处理版本出来 我们再改为集群部署

**Comment by MajorHe1** [comment]
@pinpindao  注册的临时服务还是持久服务。如果是临时服务，是否经过一段时间后最终一致？如果经过一段时间之后还是不一致，且可以复现的话，看看 protocol-distro 和 naming-distro的日志。

另外，这个地方
![image](https://user-images.githubusercontent.com/53824889/171575646-f404a899-e43f-41ab-9fc7-4f4820aab234.png)
本来就是4个不同的raft场景，leader节点不同是正常的，应该关注在其他的节点上，相同的场景（就是外面的那个key值），对应的leader节点是否相同

**Comment by MajorHe1** [comment]
@yejiawei0 你们这边注册的服务也是临时服务吗？我自己碰到过的集群节点数目不一致，是因为集群内有节点挂了，然后重试的任务在队列里面堆积的太多，导致正常同步的任务排队时间太长，在一段时间内看起来节点数目不一致。及时从cluster.conf文件或者集群的地址服务器里面把故障节点清除，就没有这个问题了。

**Comment by KomachiSion** [comment]
> 我们也遇到了 nacos 2.0.3 集群 3个 挂了其中一台机器一晚上后 第二天启动nacos 挂掉的那台不能同步nacos其他集群所注册的所有服务，并且重启也不生效， mv 挂掉的那台 /data 重启也没有作用， 在夜深人静的晚上 我们把nacos集群都停了 mv data 从好的节点开始启动 才慢慢开始把注册上来的服务都同步到集群内 。 但是好景不长 第二天发现另一台机器的注册服务数量与集群其他节点又不同了。
> 
> 最终 我们把nacos 部署到了docker中 以单节点的方式 草草结束了战斗
> 
> nacos issues 遇到相同问题的太多了 而且观察源码 发现应该是 集群内部 对于临时数据共享 有比较严重的bug 其他几贴issues 已经详细的描述了
> 
> 有处理版本出来 我们再改为集群部署

麻烦详述bug， 根据目前反馈情况看，大多数都是没有理解用法错用导致集群重启后状态不正确导致的数据错误。仅一句存在bug没人能修复问题。

**Comment by pinpindao** [comment]
> @pinpindao 注册的临时服务还是持久服务。如果是临时服务，是否经过一段时间后最终一致？如果经过一段时间之后还是不一致，且可以复现的话，看看 protocol-distro 和 naming-distro的日志。
> 
> 另外，这个地方 ![image](https://user-images.githubusercontent.com/53824889/171575646-f404a899-e43f-41ab-9fc7-4f4820aab234.png) 本来就是**4个不同的raft场景，leader节点不同是正常的**，应该关注在其他的节点上，相同的场景（就是外面的那个key值），对应的leader节点是否相同

目前没有再模拟复现问题，重新部署后目前服务数量相同，请问这4个不同的raft场景是什么区别？还有那个key值在哪里看？如何确定哪个是leader，哪个是follower？

**Comment by pinpindao** [comment]
> > 我们也遇到了 nacos 2.0.3 集群 3个 挂了其中一台机器一晚上后 第二天启动nacos 挂掉的那台不能同步nacos其他集群所注册的所有服务，并且重启也不生效， mv 挂掉的那台 /data 重启也没有作用， 在夜深人静的晚上 我们把nacos集群都停了 mv data 从好的节点开始启动 才慢慢开始把注册上来的服务都同步到集群内 。 但是好景不长 第二天发现另一台机器的注册服务数量与集群其他节点又不同了。
> > 最终 我们把nacos 部署到了docker中 以单节点的方式 草草结束了战斗
> > nacos issues 遇到相同问题的太多了 而且观察源码 发现应该是 集群内部 对于临时数据共享 有比较严重的bug 其他几贴issues 已经详细的描述了
> > 有处理版本出来 我们再改为集群部署
> 
> 麻烦详述bug， 根据目前反馈情况看，大多数都是没有理解用法错用导致集群重启后状态不正确导致的数据错误。仅一句存在bug没人能修复问题。

@KomachiSion 目前没有再模拟复现问题，重新部署后目前服务数量相同，集群模式运行一段时间之后，节点元数据上又看到如下错误，请帮忙看下，多谢！
![image](https://user-images.githubusercontent.com/106652818/172085876-830b0459-6a97-4bc2-851f-b06a09f964d6.png)

**Comment by MajorHe1** [comment]
> 目前没有再模拟复现问题，重新部署后目前服务数量相同，请问这4个不同的raft场景是什么区别？还有那个key值在哪里看？如何确定哪个是leader，哪个是follower？

#7158

**Comment by MajorHe1** [comment]
> @KomachiSion 目前没有再模拟复现问题，重新部署后目前服务数量相同，集群模式运行一段时间之后，节点元数据上又看到如下错误，请帮忙看下，多谢！

#7757

**Comment by pinpindao** [comment]
> > 目前没有再模拟复现问题，重新部署后目前服务数量相同，请问这4个不同的raft场景是什么区别？还有那个key值在哪里看？如何确定哪个是leader，哪个是follower？
> 
> #7158

你好，我通过API查询当前集群leader时，有如下提示，请问时什么原因？
[root@host-001 ~]# curl -X GET '127.0.0.1:8848/nacos/v1/ns/raft/leader'
caused: old raft protocol already stop;

另外，我在有的资料上看节点元数据有这些内容，如下，但是实际上我查询集群节点元数据只有raftMetaData的内容，实际的集群leader在哪里查看，上面的4个raft场景下，以哪个为准呢？谢谢！
![image](https://user-images.githubusercontent.com/106652818/172784807-982aaa0d-d70e-46d2-a010-7c62fa162a77.png)

**Comment by MajorHe1** [comment]
> 你好，我通过API查询当前集群leader时，有如下提示，请问时什么原因？ [root@host-001 ~]# curl -X GET '127.0.0.1:8848/nacos/v1/ns/raft/leader' caused: old raft protocol already stop;

nacos升级迭代的过程中换了raft协议的实现，这个接口应该是旧的协议的查询接口，已经停用了
> 
> 另外，我在有的资料上看节点元数据有这些内容，如下，

资料是旧的，过期了， 以现在你在界面上看到的信息为准

>实际的集群leader在哪里查看，上面的4个raft场景下，以哪个为准呢

四个场景彼此独立，可以都有自己的leader

**Comment by pinpindao** [comment]
> > @KomachiSion 目前没有再模拟复现问题，重新部署后目前服务数量相同，集群模式运行一段时间之后，节点元数据上又看到如下错误，请帮忙看下，多谢！
> 
> #7757

@MajorHe1 您好，看了您提到的这个问题，感觉不太一样，上次在删除data下的protocol并重启nacos以后恢复了正常，目前我这边又出现了同样的问题

有两个节点192.168.0.10&192.168.0.30下报这个错误
![image](https://user-images.githubusercontent.com/106652818/174006754-eee852d9-3e57-440c-9aed-74144db0ee1b.png)
下面是正常节点192.168.0.13元数据
![image](https://user-images.githubusercontent.com/106652818/174007951-5944e63b-9ecf-4f99-84ea-b739fe80b459.png)


问题节点对应的protocol-raft.log
![image](https://user-images.githubusercontent.com/106652818/174007804-8aff83e4-65e5-4a2e-8841-0539ddc588a0.png)

目前共注册了11个临时实例，请帮忙看下这个问题，谢谢！

**Comment by MajorHe1** [comment]
![image](https://user-images.githubusercontent.com/53824889/174012839-f28b0cba-b1e1-4187-80f7-246b62d66954.png)
应该是这个地方报NPE了，e.getMessage() = null，
建议你本地在这里修改源码，做个判断，把 e  和调用堆栈打出来看看是怎么回事，然后重新打包部署，如果能复现的话就知道下一步怎么改了

**Comment by pinpindao** [comment]
> ![image](https://user-images.githubusercontent.com/53824889/174012839-f28b0cba-b1e1-4187-80f7-246b62d66954.png) 应该是这个地方报NPE了，e.getMessage() = null， 建议你本地在这里修改源码，做个判断，把 e 和调用堆栈打出来看看是怎么回事，然后重新打包部署，如果能复现的话就知道下一步怎么改了

您好，能帮忙提供下修改后的部署包吗？谢谢！

**Comment by KomachiSion** [comment]
可以试着更换2.1.0版本试试， 可能是以前修复过的一个问题。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by 1em0n9527** [comment]
也碰到类似问题了， 三个 nacos 节点，中间磁盘满导致有节点挂了， 重启两个 follow 节点，保留 leader 节点（一直没有重启）对外提供服务， 发现重启后的一个 follow 服务节点和其他节点（follow+leader）服务数量不一致，具体表现举例 serivceA 在问题节点上只有 3 个实例，在正常节点都是4个。

排查日志也没有发现 ERROR 等情况， 只有 nacos-cluster 日志一致在刷新  WARN [serverlist] updated to
arthas 进去排查内存情况，发现一些信息：一个是 clientManager.clientId 在两个 follow 节点上都一致且更新时间均为最新，
clientServiceIndexesManager.publisherIndexes 数据不一致，其更新时间都为重启的那天02-19
serviceStorage.serviceDataIndexes 数据(web 接口数据取自这个对象)也不一致，更新时间也分别为 02-24， 03-01

在 follow 节点上 tcpdump 抓 leader 发过来的包，能看到 leader 节点发送给 follow 的涉及到丢失 ip:port 的 distro 数据块都正常发送，且校验值均相等

后续不知如何排查了
