### ISSUE TITLE
关于1.3.2配置configLongPollTimeout没有生效

### ISSUE THREAD

**Issue by 517227989** [alibaba/nacos#8494]
我配置了这个参数，但是用wireshark检测出来还是30S轮询一次配置，nacos群里反馈了，席翁让我提个issue

**Comment by onewe** [comment]
@i will resolve it@

**Comment by 517227989** [comment]
> @i will resolve it@

thanks

**Comment by onewe** [comment]
@517227989 请问你配置的值是多少? 怎么配置的? 能否提供详细信息?

**Comment by presenth7s** [comment]
> @presenth7s 你也遇到这个问题了吗？ 能否提供一下详细信息, 怎么复现这个问题, 怎么配置的,配置的值是多少?

我没有遇见哦

**Comment by onewe** [comment]
经过测试, 并没有复现你说的问题:
nacos-server 版本: 1.4.3-SNAPSHOT
nacos-client 版本: 1.4.2
spring-cloud 版本: 2021.0.1
spring-cloud-alibaba 版本: 2021.0.1.0
spring-boot 版本: 2.6.3

bootstrap.properties
```properties
spring.cloud.nacos.config.config-long-poll-timeout=60000
spring.cloud.nacos.config.enabled=true
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.file-extension=properties
spring.application.name=test
```

> 新版本的 cloud 需要加入 `spring-cloud-starter-bootstrap` 依赖才能使 `bootstrap.properties` 生效

Wireshark 截图:
![image](https://user-images.githubusercontent.com/38708836/172522319-db13820f-dddf-41fb-bdde-9627b15512c4.png)

建议:
1. 升级 nacos 版本
2. 检查客户端配置是否正确

**Comment by 517227989** [comment]
> spring.cloud.nacos.config.configLongPollTimeout

spring.cloud.nacos.config.configLongPollTimeout和spring.cloud.nacos.config.config-long-poll-timeout我都配置试过了，都不起作用，官方文档里面1.1之后的版本理论就该支持该参数了，我的版本是1.3.2，是生产环境在用版本，不太好直接升级1.4.2
在这回复里面我贴不了图，可以加我微信517227989我提供复现截图证明@onewe

**Comment by githubcheng2978** [comment]
maybe you should put configuration int bootstrap.properties.  because you import spirng-cloud。 

or upgrade springboot to 2.6.x。

**Comment by 517227989** [comment]
需在launcher里手动加入config的配置，discovery的可以自动读取到
