### ISSUE TITLE
Client not connected,current status:STARTING

### ISSUE THREAD

**Issue by SuYapeng** [alibaba/nacos#8497]
我的客户端服务端都是2.0.3　　但是却始终报这个错　　　　　我的服务配置都正常

**Comment by MajorHe1** [comment]
当出现Client not connected,current status:STARTING日志的时候，一定是客户端跟服务端之间的通信出了问题，要么是服务端部署的不正确，要么是网络防火墙网关转发之类的问题
https://nacos.io/zh-cn/docs/2.0.0-compatibility.html
![image](https://user-images.githubusercontent.com/53824889/171571498-dd93f38b-8308-4105-9695-11e9b85ddf11.png)

**Comment by MajorHe1** [comment]
@wcllcw 
你这里启动日志里面的  INFO Nacos is starting 跟 Client not connected,current status:STARTING 是两回事，这两者没有关系。
从你贴出来的日志来看，就是一直处于选主过程中，大概率是因为集群只给了两个节点，建议把集群改为三个节点方便选主再试试。

**Comment by SuYapeng** [comment]
> ，一定是客

我关闭了服务器的防火墙，腾讯云的控制台放行所有的请求  这就应该是暴露了我的所有端口吧  但是依旧是这个报错

**Comment by SuYapeng** [comment]
> 当出现Client not connected,current status:STARTING日志的时候，一定是客户端跟服务端之间的通信出了问题，要么是服务端部署的不正确，要么是网络防火墙网关转发之类的问题 https://nacos.io/zh-cn/docs/2.0.0-compatibility.html ![image](https://user-images.githubusercontent.com/53824889/171571498-dd93f38b-8308-4105-9695-11e9b85ddf11.png)

我关闭了服务器的防火墙，腾讯云的控制台放行所有的请求 这就应该是暴露了我的所有端口吧 但是依旧是这个报错

**Comment by wcllcw** [comment]
@MajorHe1 谢谢你！已解决，不是集群节点的问题，生产环境就是用的两个节点，之前没用过nacos，不熟悉。是nacos-server配置没有开启鉴权导致。
=================================================================================
"在默认的Nacos server配置中，不会对客户端鉴权，即任何能访问Nacos server的用户，都可以直接获取Nacos中存储的配置。比如一个黑客攻进了企业内网，就能获取所有的业务配置，这样肯定会有安全隐患。
所以需要先开启Nacos server的鉴权。在Nacos server上修改application.properties中的nacos.core.auth.enabled值为true即可：
nacos.core.auth.enabled=true如上设置后，Nacos客户端获取配置时，需要设置上对应的用户名和密码，才能获取配置"
=================================================================================
[xxx@localhost nacos]$ tail -f ./logs/start.out
2022-06-04 11:07:28,942 INFO Nacos is starting...

2022-06-04 11:07:29,948 INFO Nacos is starting...

2022-06-04 11:07:30,953 INFO Nacos is starting...

2022-06-04 11:07:31,960 INFO Nacos is starting...

2022-06-04 11:07:32,642 INFO Nacos started successfully in cluster mode. use embedded storage

**Comment by MajorHe1** [comment]
> 我关闭了服务器的防火墙，腾讯云的控制台放行所有的请求 这就应该是暴露了我的所有端口吧 但是依旧是这个报错

@SuYapeng telnet 测试端口看网络是否通畅，默认http端口 8848，grpc端口9848

**Comment by SuYapeng** [comment]
我关闭了服务器防火墙&nbsp; &nbsp;腾讯云控制台放行所有请求，依旧是这个报错



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 2, 2022 14:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/nacos] Client not connected,current status:STARTING (Issue #8497)




 
当出现Client not connected,current status:STARTING日志的时候，一定是客户端跟服务端之间的通信出了问题，要么是服务端部署的不正确，要么是网络防火墙网关转发之类的问题
 https://nacos.io/zh-cn/docs/2.0.0-compatibility.html

**Comment by Cheeemmss** [comment]
我直接把防火墙关了也是这个报错   @@是nginx配置有问题吗？
![image](https://user-images.githubusercontent.com/95232257/211165271-35a6c923-3696-4be6-bd2c-1db24423cd2f.png)
![image](https://user-images.githubusercontent.com/95232257/211165323-8971d4cc-3955-4c7a-a8ca-2bd36e4a6b89.png)
