### ISSUE TITLE
Nacos集群三节点，一个节点down之后，整个集群不可用

### ISSUE THREAD

**Issue by zhouxwyeah** [alibaba/nacos#8499]
**Describe the bug**
Nacos v1.4.1, 使用nacos-k8s发布，三节点
20：30 其中nacos-1所在物理机资源不足，驱逐nacos-1
20：40 nacos-1重启恢复

在nacos-1不可用的过程中，console查看nacos-0和nacos-2的状态是正常的，但是整个nacos集群不可用

**Expected behavior**
三节点的情况下，预期宕机单节点，集群应该是可以服务的

**Acutally behavior**
其中一个节点不可用，导致整个集群都会无法使用，

**Desktop (please complete the following information):**
 - OS: redhat
 - Version Nacos v1.4.1
 - SDK spring-cloud-alibaba-nacos

**Additional context**
附件是Nacos-0,nacos-1，nacos-2的日志
[nacos-0.zip](https://github.com/alibaba/nacos/files/8817585/nacos-0.zip)
[nacos-1.zip](https://github.com/alibaba/nacos/files/8817586/nacos-1.zip)
[nacos-2.zip](https://github.com/alibaba/nacos/files/8817591/nacos-2.zip)

**Comment by MajorHe1** [comment]
这里的不可用具体是个什么样的状态，是服务注册不上，还是服务发现不了？

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough.
