### ISSUE TITLE
能否请问下大家，关于nacos的配置中心文件加解密存入数据库是怎么弄的吗？照着官网的没成功

### ISSUE THREAD

**Issue by ayifeng** [alibaba/nacos#8500]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by li-xiao-shuang** [comment]
https://nacos.io/zh-cn/docs/config-encryption.html   可以参考下这个文档看看

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
