### ISSUE TITLE
轮询：客户端定时向服务器发送请求，服务器接到请求后马上返回响应信息并关闭连接。

### ISSUE THREAD

**Issue by scientificCommunity** [alibaba/nacos#8501]
轮询：客户端定时向服务器发送请求，服务器接到请求后马上返回响应信息并关闭连接。 
长轮询：客户端向服务器发送请求，服务器接到请求后hold住连接，直到有新消息才返回响应信息并关闭连接，客户端处理完响应信息后再向服务器发送新的请求。 

config的长轮询，就是一直向客户端请求是否有配置出现变更，如果有，则继续通过长轮询获得新配置的过程。
优势就是相比普通的变更推送，能够同时减少客户端和服务端对于同一个配置推送是的负载峰值。因为客户端轮询具有一定的随机性。

_Originally posted by @KomachiSion in https://github.com/alibaba/nacos/issues/4105#issuecomment-719904700_

**Comment by scientificCommunity** [comment]
有一个疑惑，nacos的config采用长轮询而不是长链接，是因为该场景下长轮询更有优势吗？

**Comment by MajorHe1** [comment]
nacos config 使用 长轮询应该是 1.x的版本， 2.x的版本都是长连接了

**Comment by scientificCommunity** [comment]
> nacos config 使用 长轮询应该是 1.x的版本， 2.x的版本都是长连接了

额，这个我指导。其实我只是好奇当初为什么选择了长轮询而不是长链接...

**Comment by KomachiSion** [comment]
因为1.x没有引入长链接能力啊，只使用了http，因此只能用长轮训来模拟长链接。
