### ISSUE TITLE
nacos 1.1.4 出现 currentServerAddr: xxx err : Read timed out后服务假死，类加载失败

### ISSUE THREAD

**Issue by codelearner1024** [alibaba/nacos#8502]
**Describe the bug**
nacos 1.1.4 出现 currentServerAddr: 【xxx】 err : Read timed out后服务假死

**Expected behavior**

**Acutally behavior**
1. 类加载失败【nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.xxx】
2. grafana监控表现出断档（包括元空间，加载的类等），说明大概是k8s   pod内部服务重启了
3. 重启后grafana恢复正常，发现加载的类变少了

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [CentOS Linux release 7.7.1908 (Core)]
 - Version [e.g. nacos-server 1.1.4, nacos-client 1.1.4]
 - SDK 
 ``` xml

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.3.RELEASE</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>

  <spring-boot.version>2.3.3.RELEASE</spring-boot.version>
  <spring-cloud.version>Hoxton.SR8</spring-cloud.version>
 <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.1.1.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.1.1.RELEASE</version>
        </dependency>
 ```

**Additional context**

**Comment by MajorHe1** [comment]
1.1.4 的版本实在是有点太低了，建议升级新版本吧

**Comment by KomachiSion** [comment]
No more response from author, I think the new version has solve the problem.
