### ISSUE TITLE
Describe the bug*

### ISSUE THREAD

**Issue by hhl201413** [alibaba/nacos#8504]
**Describe the bug**

The consistency module did not submit com alibaba. nacos. consistency. entity package
consistency模块没有提交com.alibaba.nacos.consistency.entity这个包

**Comment by hhl201413** [comment]
version  2.1.0

**Comment by lpaz010** [comment]
这个包目录是由`protobuf`在编译时自动生成，您可以通过`mvn compile`来自动生成他们。如果您使用的是IDEA，也可以使用IDEA的protobuf插件。

另 [FAQ](https://nacos.io/zh-cn/docs/faq.html#3.19)
