### ISSUE TITLE
when nacos publish RefreshEvent cause dubbo shutdown

### ISSUE THREAD

**Issue by yufeng629** [alibaba/nacos#851]
### environment
        JDK 1.8
        SpringBoot 2.0.8.RELEASE
        Dubbo 2.6.5
        Dubbo-Starter 0.2.1.RELEASE
        spring-cloud-starter-alibaba-nacos-config 0.2.1.RELEASE
        spring-cloud-starter-alibaba-nacos-discovery 0.2.1.RELEASE
        spring-cloud-starter-gateway 2.0.2.RELEASE

### Anything else we need to know?
        if i set the spring.cloud.nacos.config.refresh.enabled=true in bootstrap.yaml，when i start the application, the RefreshEvent from nacos will cause dubbo shutdown，but，because i use the spring-cloud-gateway，it start an web container，so the dubbo did not really shutdown, but i down unkonw if this situation will cause other unknown problem, or, if this happen in a none-web application, will it really cause the Dubbo application shutdown?
![image](https://user-images.githubusercontent.com/15260012/53619680-24319400-3c2b-11e9-95b0-939836d8a2f1.png)

中文原意：
        当我在bootstrap.yaml中设置spring.cloud.nacos.config.refresh.enabled=true的时候，当我启动应用的时候，nacos会发布一个RefreshEvent，而这个事件会导致spring发布一个ContextClosedEvent事件，而这个事件最终会到达com.alibaba.boot.dubbo.context.event.AwaitingNonWebApplicationListener中，从而导致这个对象中等待的线程被唤醒，进而导致dubbo应用被关闭，因为我在当前项目中有使用spring-cloud-gateway，所以，dubbo应用并没有真正关闭，依然一直在正常工作，但是，我不知道这种情况会不会带来其他的未知问题，或者，如果这种情况是在一个非web的应用中，会不会导致应用真正的关闭?

**Comment by nkorange** [comment]
This is a [spring-cloud-alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) issue
