### ISSUE TITLE
not support MySQL utf8mb4

### ISSUE THREAD

**Issue by Gavinluo** [alibaba/nacos#8519]
our database is all change to utf8mb4 ,  but nacos table has error , the permissions table pk overlength
**ERROR 1071 (42000) at line 260: Specified key was too long; max key length is 767 bytes**
```
CREATE TABLE `permissions` (
    `role` varchar(50) NOT NULL,
    `resource` varchar(255) NOT NULL,
    `action` varchar(8) NOT NULL,
    UNIQUE INDEX `uk_role_permission` (`role`,`resource`,`action`) USING BTREE
);
```
may i set the resource column length to 150 ? has any efficet ？

**Comment by onewe** [comment]
Mysql 8? or 5.7?

**Comment by onewe** [comment]
How to reproduce it?

**Comment by KomachiSion** [comment]
you should change your mysql setting to allow create large index.

**Comment by Gavinluo** [comment]
i set the "resource" column length to 150  , used MySQL 5.7 
"change mysql setting to allow create large index" yes , but every developer must to set it , too troublesome
