### ISSUE TITLE
Derby cluster mode  can‘t  ’ login  default  console 

### ISSUE THREAD

**Issue by Arvinzhu** [alibaba/nacos#8526]
**Describe the bug**
I deployed a three-node cluster on a Machine on a CentOS 7.6 system using the nacos 2.1.0 version. Using the derby built-in database, the default console login failure occurs. This is not the case with a single node。

 我使用nacos2.1.0 版本在CentOS7.6系统的机器上部署了一个三节点的集群。使用derby 内置数据库，开启登录鉴权，出现了默认的控制台登录失败的现象。而单节点则无此现象。

**Expected behavior**
现象如下：
 
![image](https://user-images.githubusercontent.com/16772932/172167381-ad697036-c4bd-43a9-8749-2e37b079bec6.png)

 

**Desktop (please complete the following information):**
 - OS: CentOS  7.6
 - Version Nacos  2.1.0 
 -  Start Command:   `sh bin/startup.sh -p embedded`

**application.propertites**
 I have only modified the following configuration items, the other information has not been modified

```
### Default web context path:
server.servlet.contextPath=/nacos
### Default web server port:
server.port=33461
nacos.inetutils.ip-address=192.x.x.7
### Metrics for prometheus
management.endpoints.web.exposure.include=*
### The auth system to use, currently only 'nacos' and 'ldap' is supported:
nacos.core.auth.system.type=nacos

### If turn on auth system:
nacos.core.auth.enabled=true
```
**cluster.conf**
```
#2022-06-06T20:07:05.113
192.x.x.7:33461
192.x.x.8:33461
192.x.x.9:33461
```
谁能告诉我问题在哪里或者如何正确部署derby模式的nacos集群吗 ？ 非常感谢
Can anyone tell me where the problem is or how to properly deploy a nacos cluster in derby mode? Thank you very much

**Comment by onewe** [comment]
这个问题在最新的版本已经修复了,目前有以下3种解决方案

解决方案:
1. 不使用集群模式
2. 使用mysql
3. 使用最新的nacos源码自己打包

关闭鉴权或许有用也可以试一试

**Comment by Arvinzhu** [comment]
@onewe  你好，麻烦再问一下:
我使用IDEA打包nacos 2.1.0源码，使用得到的nacos-server-2.1.0.tar.gz 部署derby模式的nacos集群，还是一样的现象。
能麻烦你详细 描述  第三种 使用最新的nacos源码自己打包 具体是怎么操作的吗？

**Comment by onewe** [comment]
@Arvinzhu 你用的哪个分支？ 最新的在 develop 分支

**Comment by onewe** [comment]
https://github.com/alibaba/nacos/pull/8304
相关PR

**Comment by Arvinzhu** [comment]
@onewe  我使用的是 tags  2.1.0

**Comment by onewe** [comment]
不要使用 tag 就用 develop 分支代码, 用develop分支代码打包的时候 记得要修改一个配置,不然会启动不起来,是昨天升级 spring
boot 版本导致的 https://github.com/alibaba/nacos/issues/8528
