### ISSUE TITLE
内存占用是不是有点大（Is the memory usage a bit large?）

### ISSUE THREAD

**Issue by actliboy** [alibaba/nacos#8527]
**Describe the bug**
经过反复尝试，单节点最小启动内存要到400M，所以内存限制至少要500M才能启动，这还是什么都不做的情况下，这内存占用是不是有点大了，够跑个os了，配置低的服务器完全没法用（只用配置中心）
After repeated attempts, the minimum startup memory of a single node is 400M, so the memory limit must be at least 500M to start. In the case of doing nothing, is the memory footprint a bit large, enough to run an os, and the configuration is low The server is completely useless (only the configuration center is used)
**Expected behavior**
java应用可以理解，但是最小启动内存能不能降到100M以内啊
The java application is understandable, but can the minimum startup memory be reduced to less than 100M?

**Desktop (please complete the following information):**
 - OS: docker
 - Version： nacos-server 2.0
 - Module config

**Comment by KomachiSion** [comment]
可能比较难，需要长久的优化。 注册中心或配置中心作为`中心` ，需要处理大量微服务请求，需要存储和初始化大量信息，不能和普通应用消耗相比。

你可以dump出来内存，看看哪些地方占用了较多内存，另外请贴出完整的jvm参数，并不是只调整堆内存就可以了。

**Comment by actliboy** [comment]
这是我的内存参数
```yaml
  JVM_XMS: "50m"
  JVM_XMX: "256m"
  JVM_XMN: "30m"
  JVM_MS: "30m"
  JVM_MMS: "30m"
```
跑在k8s整个pod内存占用在450M左右，limit限制必须500M以上，JVM_XMX再小点应用自己就会内存不够杀掉

**Comment by KomachiSion** [comment]
能否dump出内存分析一下，什么占用的比较大？

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
