### ISSUE TITLE
Load balancing for team collaboration

### ISSUE THREAD

**Issue by RoanFan** [alibaba/nacos#8531]
Problems encountered:

In practical work, a project may have seven or eight developers jointly developing, while developing under the condition of limited computer configuration, there will be the following problems:

1. To start almost all the services for functional development, one developer maintains one NACOS, at this time, the configuration of the computer will appear early warning and cannot bear

2. If colleagues register their services with a NACCOS, the configuration of the computer can be improved in a friendly way, but conflicts are inevitable. When multiple colleagues are developing the same module/service, NacOS will poll, which is not always the result we want!!

Suggestion: You can make another switch in addition to the polling rule, whether to call the local service preferentially. If this switch is enabled, the local service will be called preferentially. If the local service is not enabled, other services will be called according to the polling rule.

**Comment by onewe** [comment]
I think the problem is a work flow problem , it's not nacos' problem. When you are developing why you need to start a nacos?
That's terrible.

**Comment by KomachiSion** [comment]
I can't get your problem. what's the means of `call the local service preferentially`? the RPC service? If so, it's not nacos' problem. nacos only provide the ip list of service, if you want to call the specified ip or `cluster`, you should subscribe or get the `cluster` of service. And when you register the service instance, you should register instance with `cluster`.
