### ISSUE TITLE
【疑问】nacos-config 包下的DynamicDataSource类 为什么要添加@Component注解

### ISSUE THREAD

**Issue by wangshengji** [alibaba/nacos#8532]
com.alibaba.nacos.config.server.service.datasource.DynamicDataSource
我认为这是一个单例类去获取数据源，但是发现没有构造私有化，增加了一个@Component注入到spring容器了，但是我看到这个类的使用都是DynamicDataSource .getInstance().getDataSource();  
spring容器中获取的bean 和 DynamicDataSource .getInstance() 并不是同一个对象呀。

![image](https://user-images.githubusercontent.com/61901649/172309730-38f547b4-e297-4ec6-aee4-18fbf333a73f.png)

**Comment by KomachiSion** [comment]
@shiyiyue1102 Component is submited by you, can you answer this problem?

**Comment by shiyiyue1102** [comment]
> DynamicDataSource

it may be a mistake, the annotation can be removed.

**Comment by Aldohomzlo** [comment]
Excelente
