### ISSUE TITLE
signHeaders empty judgment is unnecessary

### ISSUE THREAD

**Issue by david6969xin** [alibaba/nacos#8533]
`Map<String, String> signHeaders = SpasAdapter`
               ` .getSignHeaders(getResource(resource.getNamespace(), resource.getGroup()), secretKey);`

`public static Map<String, String> getSignHeaders(String resource, String secretKey) {`
        `Map<String, String> header = new HashMap<String, String>(2);`
        `String timeStamp = String.valueOf(System.currentTimeMillis());`
        `header.put(TIMESTAMP_HEADER, timeStamp);`
        `if (secretKey != null) {`
            `String signature;`
            `if (StringUtils.isBlank(resource)) {`
               ` signature = signWithHmacSha1Encrypt(timeStamp, secretKey);`
            `} else {`
                `signature = signWithHmacSha1Encrypt(resource + "+" + timeStamp, secretKey);`
            `}`
            `header.put(SIGNATURE_HEADER, signature);`
        `}`
        `return header;`
    `}`

signHeaders always contain Timestamp , so it never can`t null or empty

**Comment by KomachiSion** [comment]
Please edit your description.
