### ISSUE TITLE
NacosConfigurationPropertiesBinder bugs: if configure autoRefreshed=false, will not bind properties to @NacosConfigProperties

### ISSUE THREAD

**Issue by s614053620** [alibaba/nacos#8535]
in branch 1.1.1release, 

https://github.com/nacos-group/nacos-spring-project/blob/release1.1.1/nacos-spring-context/src/main/java/com/alibaba/nacos/spring/context/properties/config/NacosConfigurationPropertiesBinder.java

![image](https://user-images.githubusercontent.com/11168300/172348167-14d9f291-3bb5-4441-895d-e25ddfd07e20.png)

but in develop branch, no problem.

需要调整一下代码的执行顺序.  目前版本如果想要可用, 必须要将autoRefreshed配置成true

**Comment by hujun-w-2** [comment]
the bug will be fix in next release version
