### ISSUE TITLE
nacos版本2.1.0，用户登录权限问题

### ISSUE THREAD

**Issue by zyjhellohi** [alibaba/nacos#8545]
步骤：
1：新增一个test用户，新建一个命名空间test-dev，:
2：给test用户分配test-dev权限，然后修改配置文件开启权限认证
结果：使用test用户登录，接口nacos/v1/cs/configs返回403，没有public访问权限
2.1.0之前版本都能登录，请问这个是新版本的限制问题还是bug？

**Comment by zyjhellohi** [comment]
新版本只要没有对应namespace权限，点击就强制踢出，这个用户体验是不是不太友好？

**Comment by onewe** [comment]
@zyjhellohi 这个已经修复了

**Comment by kyvli** [comment]
默认用户nacos修改密码也是报403

**Comment by onewe** [comment]
@kyvli 重新登录一下试一试

**Comment by zyjhellohi** [comment]
> @zyjhellohi这个已经修复了

在哪个版本修复的，我目前使用的是最新版本2.1.0上面出现的问题。

**Comment by onewe** [comment]
@zyjhellohi 还没发版本

**Comment by zyjhellohi** [comment]
> @zyjhellohi发布版本

哦哦，有计划什么时候发这个问题的修复版本吗？

**Comment by kyvli** [comment]
> @kyvli 重新登录一下试一试

刚试了下，直接访问nacos修改密码没有问题，经过nginx做的stream代理修改密码报403，是什么原因呢？nginx代理需要什么特殊配置吗

**Comment by onewe** [comment]
@kyvli session 失效了, 403 是服务端没拿到 session 导致的, 可以做一下转发

**Comment by onewe** [comment]
@zyjhellohi  目前还不清楚啥时候发布, 可以临时解决一下, 在 nacos-server 包里把 前端的 js 文件拿出来 找到`['unknown user!', 'token invalid!', 'token expired!', 'authorization failed!']` 这行代码,然后 把 `'authorization failed!'` 去掉就行了.

**Comment by zyjhellohi** [comment]
> @zyjhellohi 目前还不清楚啥时候发布, 可以临时解决一下, 在 nacos-server 包里把 前端的 js 文件拿出来 找到`['unknown user!', 'token invalid!', 'token expired!', 'authorization failed!']` 这行代码,然后 把 `'authorization failed!'` 去掉就行了.

好的，我修改试试

**Comment by onewe** [comment]
如果你只是实验性使用,可以使用 我这边提供的快照版本 docker 镜像.  https://github.com/onewe/nacos-docker

**Comment by zyjhellohi** [comment]
我拉下来看看，感谢大佬

**Comment by kyvli** [comment]
> @kyvli session 失效了, 403 是服务端没拿到 session 导致的, 可以做一下转发

可以了，nginx配了会话保持，谢谢

**Comment by zyjhellohi** [comment]
> > @zyjhellohi 目前还不清楚啥时候发布, 可以临时解决一下, 在 nacos-server 包里把 前端的 js 文件拿出来 找到`['unknown user!', 'token invalid!', 'token expired!', 'authorization failed!']` 这行代码,然后 把 `'authorization failed!'` 去掉就行了.
> 
> 好的，我修改试试

能麻烦说下修改的js路径吗? 我在main.js里面没有找到，然后public里面一堆js

**Comment by lihuawei321** [comment]
我遇到同样的问题，创建一个用户给他分配了一个namespace，但是他还是可以看到所有的namespace，只不过点击其他ns时候会跳转出去并显示没有权限，怎么让用户只看到自己有权限的namespace呢
