### ISSUE TITLE
nacos1.4.2 服务端集群问题

### ISSUE THREAD

**Issue by wytjiayou** [alibaba/nacos#8548]
服务端三个节点：
![image](https://user-images.githubusercontent.com/21037575/172816880-53661054-c5f4-43d5-855d-f8810dd6af3a.png)
展开节点元数据，选举节点中有不存在的服务器节点：
![image](https://user-images.githubusercontent.com/21037575/172817071-c3918549-d4be-4e08-a322-d35de6a046d6.png)
cluster.conf文件配置没问题：
![image](https://user-images.githubusercontent.com/21037575/172817158-2a7ecee4-4860-493c-bd80-ef36310b668b.png)

**Comment by wytjiayou** [comment]
哪个大佬遇到过一样的问题，请问该怎么解决

**Comment by liqipeng** [comment]
（遇到过类似，分享一下问题但无解决办法。）

当时是1.4.1版，集群是naming模式，5节点，集群重启就会大量报错：
```
Fail to check replicator connection to peer=xx.xx.xx.xx:7080, replicatorType=Follower.
```
报错日志里的这个ip是不在nacos集群配置里的，但类似上面所述的节点元数据里有这个多余的ip。

后来了解到集群以前进行过一次迁移，这个报错日志里的ip是集群迁移前的机器，实际这个机器早已关机，已从配置里移除。
一开始怀疑是jraft在本地缓存了配置，所以尝试逐个将follower的机器 停止服务-清空nacos.home目录-启动服务 ，当4个follower都清理数据重新启动后，这些follower的节点元数据里已经没有这个多余ip了；但同样的清空数据并重启完leader节点后，这个多余的ip在所有节点的元数据里又出现了。

后来一个偶然的悲剧的机会，把集群全部停机并清空nacos.home重启后，这个问题已消失无法复现了。

**Comment by wytjiayou** [comment]
> 大概有两种可能，
> 
> 1. 88这台服务器依旧存在，并且通过jraft向其他节点中添加自己为member，jraft于nacos不同，raft协议允许通过协议本身自行添加member。 nacos更加严格，需要在配置中添加节点。
> 2. 先移除的cluster.conf，后停止的88节点，这会导致先写入的member信息，被88节点停止前覆盖回来，之后88节点停止后没有再想jraft member里写入内容。
> 
> 可以试一下修改cluster.conf文件，比如加个空行，或者把88加回去再删掉试试。 如果还是这样，那大概率就是第一种情况了。

**Comment by wytjiayou** [comment]
@KomachiSion 试了先把集群所有节点kill掉，然后修改cluster.conf文件，再一个个重启接口，重启后follower节点元数据中没有多余ip了，leader节点元数据仍然包含多余ip

**Comment by KomachiSion** [comment]
raftMember中有多余ip只有两种情况， 
1. 该ip存在并且通过raft协议把自身加入到member中，jraft不是通过配置文件而是通过协议自己进行member的添加和删除，nacos只是在cluster.conf修改时会将自身修复进去。
2. 该ip不存在，但是曾经加入过raft，此时已经写入的member只能通过修改cluster.conf，让nacos 重新写入新member来修复，nacos应该也提供了一个raft-ops的接口来主动请求移除某个member。详细可以找一找对应的接口，调用一下试试。

**Comment by wytjiayou** [comment]
我试试

**Comment by wytjiayou** [comment]
最后手动调用接口删掉了多余ip
