### ISSUE TITLE
When a configuration is rolled back to the original version, the configuration is deleted

### ISSUE THREAD

**Issue by HFEzreal** [alibaba/nacos#8549]
**Describe the bug**
When a configuration is rolled back to the original version, the configuration is deleted

**Expected behavior**
The rollback is normal

**Actually behavior**
When a configuration is rolled back to the original version, the configuration is deleted

The source code contains the following content which causes this bug. Is there any special use for this part：

    if (this.opType.trim() === 'I') {
      type = 'delete';
      additionalMsg = locale.additionalRollbackMessage;
    }

**Comment by KomachiSion** [comment]
It's right, the rollback of `Insert` operation is `delete`, no problem. You should know the rollback is to rollback the operation not context.

**Comment by HFEzreal** [comment]
thanks
