### ISSUE TITLE
Nacos 订阅者列表应用名unknown，为什么不使用spring.application.name来作为应用名？

### ISSUE THREAD

**Issue by wushuaiping** [alibaba/nacos#8553]
**Is your feature request related to a problem? Please describe.**
为什么使用project.name？我相信目前全球范围内，基本都是使用spring.application.name来作为应用名的指定，而不是project.name，想请问官方为什么使用project.name，原因是什么？

**Describe the solution you'd like**
我希望能添加针对于spring.application.name的支持，添加对spring.application.name的支持并不会影响原有对project.name的支持，也不会再有人提出为什么应用名为unknown的这种问题，我觉得这种是属于设计上的一种缺陷。

**Describe alternatives you've considered**
如果project.name存在就取project.name，如果spring.application.name存在就取spring.application.name
我相信对于很多nacos的使用者，是支持该功能的。
**Additional context**
无

**Comment by shalk** [comment]
i think nacos client have no relatetion with spring.

i can set any appname in system.proprety as you need. 

For example , use @Value to get  spring.application.name then set it in  nacos-client

https://github.com/alibaba/nacos/blob/develop/client/src/main/java/com/alibaba/nacos/client/utils/AppNameUtils.java#L66

**Comment by Oliverwqcwrw** [comment]
I think the configuration you mentioned is more appropriate for integration with `SpringBoot` or `SpringCloud`

**Comment by KomachiSion** [comment]
please move this issue to spring cloud alibaba community
