### ISSUE TITLE
mac  M1

### ISSUE THREAD

**Issue by mlogKey** [alibaba/nacos#8558]
今天发现nocas2.以上的版本的不支持M1，后续会修复么，还是不会支持，现在2. X的有哪个版本可以用么

**Comment by shalk** [comment]
see #4336   ; not support m1 right now

**Comment by amendgit** [comment]
我是M1，用这个跑成功了，不知道有没有帮助。

https://github.com/alibaba/nacos/issues/9286#issuecomment-1471944998
