### ISSUE TITLE
2.1.0 添加鉴权后，用户可以看到没有授权的namespace

### ISSUE THREAD

**Issue by zhujiebing** [alibaba/nacos#8560]
**Describe the bug**
2.1.0 添加鉴权后，用户可以看到没有授权的namespace，且点击未授权的namespace后提示"权限认证失败"，然后跳转到登录页面，体验很不好。

**Desktop (please complete the following information):**
nacos-server 2.1.0

![image](https://user-images.githubusercontent.com/25639514/173191831-7e127527-fccd-4c41-9dae-98ecb564c5e7.png)

**Comment by KomachiSion** [comment]
duplicate with #8545
