### ISSUE TITLE
ConfigService 查询可以 修改和删除配置无效

### ISSUE THREAD

**Issue by qq494679975** [alibaba/nacos#8563]
nacos版本 1.4.3 
nacos-client 1.4.3

查询可以返回nacos的配置
修改配置,http请求返回的是 RestResult{code=200, message='null', data=true}，但是去nacos看配置并没有修改成功

Properties prop=new Properties();
//指定nacos服务地址
prop.put(PropertyKeyConst.SERVER_ADDR,"127.0.0.1:8848");
//指定namespace
prop.put(PropertyKeyConst.NAMESPACE,"public");
prop.put(PropertyKeyConst.USERNAME, "nacos");
prop.put(PropertyKeyConst.PASSWORD, "nacos");
ConfigService configService = NacosFactory.createConfigService(prop);

String msg=configService.getConfig("demo","DEFAULT_GROUP",1000L);

configService.publishConfig(
        "demo",
        "DEFAULT_GROUP",
        "[ { \"resource\": \"/demo\", \"limitApp\": \"default\", \"grade\": 1, \"count\": 100, \"strategy\": 0, \"controlBehavior\": 0, \"clusterMode\": false } ]",
        ConfigType.JSON.getType()
);

**Comment by qq494679975** [comment]
nacos改成数据库存储 发现在命名空间是public的情况下，由页面新增的配置插入表 config_info 的数据 tenant_id 没值，所以导致现象 页面新增数据完之后，通过代码修改发现页面的值没有改变。。

**Comment by KomachiSion** [comment]
这个不是bug，你理解错误了命名空间， 这里要填的是命名空间id， public的命名空间id是空字符串。
