### ISSUE TITLE
dubbo2.7.8和nacos1.4.1整合，nacos权重不生效

### ISSUE THREAD

**Issue by 17810257325** [alibaba/nacos#8571]
具体类似这个，https://blog.csdn.net/xinpz/article/details/124594717
我自己尝试的结果，跟上面一致。在nacos设置权重，dubbo服务没有生效

**Comment by KomachiSion** [comment]
这个是dubbo框架的问题，dubbo在自己的元数据里做了权重，nacos的权重dubbo不读取不使用
（也就是dubbo不用nacos的权重值，用了自己的权重体系）

**Comment by 17810257325** [comment]
那我怎么才能让dubbo服务用nacos里的权重设置。我现在重新了dubbo的rule规则也是没有使用到nacos里的权重。我应该怎么写，或者怎么设置才能让dubbo服务使用nacos里的权重设置。
