### ISSUE TITLE
Unable to process the request at this time：System triggered degradation

### ISSUE THREAD

**Issue by dengdalue** [alibaba/nacos#8572]
问题一：登录nacos控制台报“Unable to process the request at this time：System triggered degradation”错误，提示集群降级，通过排查发现是由于nacos日志输出过多，导致磁盘满了，我删除了日志之后，集群没有恢复，登录控制台之后报错依旧，请问有人遇到过吗，除了重启nacos，还有其他解决方案吗？
问题二：请问如何修改nacos的日志路径，我在配置文件里面没有找到相关的配置

备注：nacos版本：2.0.3

**Comment by onewe** [comment]
问题二:
设置启动参数: -Dnacos.home 可以指定路径

**Comment by onewe** [comment]
第二个问题:

export JAVA_OPT_EXT="--nacos.logs.path=/xxx/nacos/log" && sh bin/startup.sh -m standalone

**Comment by KomachiSion** [comment]
问题1  有详细一点的日志吗？

**Comment by KomachiSion** [comment]
No more response from author, one question is env problem, one question is not enough information.
