### ISSUE TITLE
nacos1.4.3 can still create users by changing the User-Agent to Nacos-Server

### ISSUE THREAD

**Issue by LWHark** [alibaba/nacos#8580]
Modify the url "yourip:8848/nacos/v1/auth/users?username=test1&password=test1" request header User-Agent to Nacos-Server, you can create test1 user.

**Comment by onewe** [comment]
you may need to enable auth

**Comment by LWHark** [comment]
@onewe After I turned on authentication, I could not view the list of services after logging in, although I could still create an account, so I can probably assume it has been resolved.Thanks!
