### ISSUE TITLE
nacos:1.4.1 not found publishConfigCas method

### ISSUE THREAD

**Issue by rottenmu** [alibaba/nacos#8582]
**Describe the bug**
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.dubbo.metadata.store.nacos.NacosConfigServiceWrapper.publishConfigCas(NacosConfigServiceWrapper.java:65)

The following method did not exist:

**Expected behavior**

**Actually behavior**
   com.alibaba.nacos.api.config.ConfigService.publishConfigCas(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z

The method's class, com.alibaba.nacos.api.config.ConfigService, is available from the following locations:

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, dubbo-registry-nacos, apache dubbo 3.0.6]

**Additional context**

**Comment by KomachiSion** [comment]
publishConfigCas supported after 2.0 version. 1.X has no this method.

**Comment by KomachiSion** [comment]
dubbo 3 only can use nacos 2.0 and upper verison.

**Comment by rottenmu** [comment]
> 
I see. Thanks .
