### ISSUE TITLE
nacos config client的fail-fast机制

### ISSUE THREAD

**Issue by shanjia-sdu** [alibaba/nacos#8586]
nacos config client有类似spring-cloud-config的fail-fast机制吗，就是客户端如果连接不上nacos配置中心，就直接报个错退出，不再启动工程

spring-cloud-config的配置是
> spring.cloud.config.fail-fast=true

**Comment by KomachiSion** [comment]
好像暂时不支持，cofing client应该是先读服务端，读不上会读本地缓存，还读不到应该会返回null，可以提issue给SCA看看， 如果是null配置，是否可以直接报错。

**Comment by KomachiSion** [comment]
No more response from author, and it seems should move to SCA community.
