### ISSUE TITLE
Bug：服务设置健康检查方式和健康检查地址成功，但服务没有实例的情况下查不出来健康检查信息

### ISSUE THREAD

**Issue by bangbang2333** [alibaba/nacos#8589]
**Describe the bug**
手动创建一个服务，给这个服务成功设置了健康检查方式和健康检查地址，如果服务有实例则可以查询到服务设置的健康检查信息，如果没有没有实例则查不到服务设置的健康检查信息。

**Expected behavior**
只要服务存在就可以设置健康检查信息，理应和服务是否存在实例没有关系。应该只要设置了，就应该都可以查出来。

**Actually behavior**
服务设置了健康检查信息，没有实例则查不出健康检查信息。

**How to Reproduce**
1.创建服务
![image](https://user-images.githubusercontent.com/43024629/174235102-578e3feb-51af-4578-8102-e04d391a715a.png)

2.设置健康检查方式
![image](https://user-images.githubusercontent.com/43024629/174235060-07052dd7-8e21-4038-8194-a20d319db3b1.png)

3.查询服务详情（会返回健康检查方式）

![image](https://user-images.githubusercontent.com/43024629/174235009-e12a702d-8386-4005-a79a-df222095e8e7.png)

**Comment by KomachiSion** [comment]
不是bug， 没有实例的话， 集群会被隐藏， 虽然可以修改这个集群健康检查方式，但是没有实例不会显示而已。

**Comment by bangbang2333** [comment]
我新增了一个接口，满足了我们的功能需求。
