### ISSUE TITLE
Where does Nacos support DNS-BASED service discovery?

### ISSUE THREAD

**Issue by startan** [alibaba/nacos#8598]
**Describe the bug**
![image](https://user-images.githubusercontent.com/345672/174484295-3076a946-dd7d-4fc3-a8bc-8a6194caadda.png)
Where does Nacos support DNS-BASED service discovery?

**Expected behavior**
Expect DNS-SD functionality from NACOS.

**Actually behavior**
I can't find the relevant functions and documentation.

**Comment by JianweiWang** [comment]
https://github.com/nacos-group/nacos-coredns-plugin/tree/feature_support_grpc
