### ISSUE TITLE
Nacos's cluster configuration is not very friendly for upgrading the number of cluster nodes.

### ISSUE THREAD

**Issue by ihaiker** [alibaba/nacos#860]
## Issue Description
Nacos's cluster configuration is not very friendly for upgrading the number of cluster nodes.
Nacos的集群配置方式对于升级集群节点数增加不太友好。

### Describe what happened (or what feature you want)

Current cluster configuration：
In the Nacos decompression directory Nacos / conf directory, there is a configuration file cluster. conf, please configure each line as ip: port.
```
# ip:port
200.8.9.16:8848
200.8.9.17:8848
...
```
If I want to add nodes to the cluster, I need to change the configuration of all the service nodes. And all nodes need to be restarted. Very unfriendly.

This configuration reminds me of the clustering configuration of zookeeper. But this configuration is 3.4 x before, after version 3.5 is changed to http://zookeeper.apache.org/doc/r3.5.4-beta/zookeeperReconfig.html

### Describe what you expected to happen

考虑到节点需要升级，并且对于维护人员最友好的方式是直接增加新的节点，此节点只需知道集群中任意节点地址并且加入即可，集群中对于节点的控制的配置文件(nodes.conf 或者其他)自动生成。这个配置文件内容类似于Redis集群配置的nodes.conf。

Considering that nodes need to be upgraded and the most maintainer-friendly way is to add new nodes directly, this node only needs to know the address of any node in the cluster and join, and the configuration files (nodes.conf or other) for nodes in the cluster are automatically generated.
This configuration file is similar to RedisCluster nodes.conf

**Comment by nkorange** [comment]
Yes, you have a good point. We will add it to our roadmap.

**Comment by nkorange** [comment]
Will be tracked in #649
