### ISSUE TITLE
2.0.3集群鉴权问题

### ISSUE THREAD

**Issue by lianglinhuan** [alibaba/nacos#8600]
在nacos的application.properties配置文件修改了一下内容。（三个节点的nacos都修改了）
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true

测试鉴权出现下面问题：
root@LAPTOP-T1DDL0P9:~# curl -X POST '******:8848/nacos/v1/auth/login' -d 'username=nacos&password=*****'
unknown user!

我想问下这是为什么呢？

**Comment by onewe** [comment]
能用浏览器进控制台吗？

**Comment by lianglinhuan** [comment]
可以，页面登录登录正常 @onewe

**Comment by lianglinhuan** [comment]
我可以问下，鉴权使用的密码格式有要求吗？我这边使用的密码比较复杂，会不会与这又关

**Comment by onewe** [comment]
也有可能,你可以尝试一下简单密码

**Comment by KomachiSion** [comment]
有特殊字符需要进行urlencode好像

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
