### ISSUE TITLE
nacos1.4删除命名空间，命名空间下的数据删不掉

### ISSUE THREAD

**Issue by riane2** [alibaba/nacos#8602]
**Describe the bug**
 nacos1.4删除命名空间，命名空间下的数据删不掉，配置页面和注册页面进去，数据都存在

**Expected behavior**
期望：命名空间下有数据时，要么提示用户不可删除，要么全部全量删除数据，否则会有垃圾数据

**Actually behavior**
所有命名空间下的数据都存在

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by onewe** [comment]
版本是1.4.0 吗？

**Comment by riane2** [comment]
> 版本是1.4.0 吗？

1.4.1 版本

**Comment by onewe** [comment]
目前来看没有做限制

**Comment by KomachiSion** [comment]
删除命名空间只是删空间，不会删除里面的数据， 这块确实考虑加一下校验，如果有内容不让删。
