### ISSUE TITLE
Can you set the configuration function of login failure lock? Currently, this function is not available

### ISSUE THREAD

**Issue by ymwfish** [alibaba/nacos#8603]
Can you set the configuration function of login failure lock? Currently, this function is not available

**Comment by onewe** [comment]
lock account?

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by ymwfish** [comment]
Web console. The account is locked if the user name or password is entered incorrectly for several times

**Comment by ymwfish** [comment]
Web console: Whether to add the account lock configuration if the user name or password is entered incorrectly for several times

web控制台，如果用户名或密码输入多次错误后，是否增加锁定帐号配置













在 2022-06-28 12:17:22，"杨翊 SionYang" ***@***.***> 写道：

Closed #8603 as completed.

**Comment by DL81GREY** [comment]
OK..
