### ISSUE TITLE
extension-configs 读取yaml共享配置问题

### ISSUE THREAD

**Issue by pkaq** [alibaba/nacos#8604]
使用extension-configs配置读取共享yaml文件
由于需要使用condition接口进行判断  在match方法中使用context.getEnvironment().getProperty（“ a.b.c ”）
断点发现propertysources会把配置逐行拆解为a,b,c三个 从而导致无法用的方式读取 而使用properties格式没有问题

已经可以确认是
1.配置肯定没问题 只要nacos中格式改成properties立马可以
2.file-extension: yaml 已经配置为 yaml
3.已经添加snakeyaml依赖
4.已经添加spring-cloud-starter-bootstrap依赖

使用的spring boot ， cloud， nacos版本均为最新版 ，JDK11

```yaml
a:
    b:
         c: xxx
```

**Comment by LWHark** [comment]
同样的问题，Springboot2.3.2、nacos2.1.0、spring cloud2.2.6，jdk1.8，.properties配置文件生效，.yaml文件失效

**Comment by pkaq** [comment]
`NacosDataParserHandler.getInstance().parseNacosData(dataId, data,fileExtension)` 之后 yaml内容就成了逐行解析的内容了
另外看来file-extension并未生效 

![1](https://user-images.githubusercontent.com/4537450/174806150-04184953-243b-4c33-b1ed-ac3a6f5950c5.png)
![2](https://user-images.githubusercontent.com/4537450/174806153-d720ce68-9574-423a-8325-1a194c9eb44a.png)
![3](https://user-images.githubusercontent.com/4537450/174806133-863c1738-89b2-4e43-98e0-d2cc9b98e364.png)

**Comment by pkaq** [comment]
问题已经解决 但是不妨碍这个bug的奇葩性质

解决方式为 克隆一份dataid为 a  的配置 重命名为 a.yaml， 然后 extension-config 中配置 a.yaml 后可以正常读取

我裂开了

@LWHark

**Comment by KomachiSion** [comment]
请提供nacos-client日志和快照文件

${user.home}/logs/nacos/config.log
${user.home}/snapshot/config/xxxx

配置实际的解析和应用是在spring cloud中， nacos-client不解析配置内容，请确认快照中的配置是正确的，如果是的话请移交issue到SCA社区。

**Comment by pkaq** [comment]
已经提交到SCA咯  感觉就是内部俩团队没沟通好

**Comment by 15102552479** [comment]
怎么解决的，大哥，求助，遇到了同样的问题
