### ISSUE TITLE
Client not connected

### ISSUE THREAD

**Issue by rechardwang** [alibaba/nacos#8607]
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/43982436/174958275-9c3bf212-2e33-417d-8972-c47c1dcaef2a.png">

HELLO，当前使用nacos在k8s中部署3节点的时候 出现这样的问题，当前nacos版本是2.0.3，而且在节点元数据中也出现过"naming_instance_metadata": {
                "errMsg": "Error [type=ERROR_TYPE_LOG, status=Status[EIO<1014>: Fail to append log entries]]",
这些字样，请问这个问题如何进行修复

**Comment by KomachiSion** [comment]
说明服务端和客户端之间的连接不存在， 看一下文档吧，看下是不是端口没有开或者配置错误。

**Comment by zx3305** [comment]
错误很明显，node2这台服务器连接不上。把你的nacos yaml文件的配置发出来，或者也可以对比下我曾经用过的配置。
https://zhuanlan.zhihu.com/p/496001814

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
