### ISSUE TITLE
sql源语句不匹配

### ISSUE THREAD

**Issue by yangshangzeng** [alibaba/nacos#8608]
1.打开链接：https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html
2.链接中的步骤：初始化 MySQL 数据库
[sql语句源文件](https://github.com/alibaba/nacos/blob/master/distribution/conf/nacos-mysql.sql)
3.在该配置中  对于表`config_info`的创建sql语句中，字段：`encrypted_data_key` text NOT NULL COMMENT '秘钥',是不是已经废弃掉了？
4.执行链接中的全部的sql创建语句，启动nacos  在进行配置发布的时候会报错：Field 'encrypted_data_key' doesn't have a default value

建议：com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl#addConfigInfoAtomic对于错误信息提示不明确

本人使用的nacos版本是1.4.1

**Comment by onewe** [comment]
`encrypted_data_key ` 没有被废弃, 这个字段是 2.x 版本开始有的,用于配置文件加密. 初始化数据库最好使用发行版本中附带的sql进行初始化,避免产生版本的差异.

**Comment by yangshangzeng** [comment]
好的 感谢回复
