### ISSUE TITLE
Create a api to return client remote IP and can using this ip to register server

### ISSUE THREAD

**Issue by HuashengJi** [alibaba/nacos#8612]
我使用云服务器部署我的应用，应用注册到nacos server的ip为获取到eth1的ip为内网ip，我使用ip a命令并无法找到公网ip的网卡 (eth0为127.0.0.1)，是否可以增加一个配置开关  使用client访问nacos server的访问ip作为client的服务注册IP

**Comment by KomachiSion** [comment]
register service api need you input your ip. you can get the eth1 ip as the service ip.

**Comment by HuashengJi** [comment]
> 

but i can't get pubilc ip in my server,i think this problem maybe happen on other.

**Comment by HuashengJi** [comment]
in now ,i using nginx to return remote ip to regist

**Comment by HuashengJi** [comment]
in now ,i using nginx to return remote ip to regist
