### ISSUE TITLE
Can you support graalvm build native image?

### ISSUE THREAD

**Issue by Jamel-jun** [alibaba/nacos#8617]
**Is your feature request related to a problem? Please describe.**
When using Graalvm Build Native Image, errors occur.
`Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image runtime.  To see how this object got instantiated use --trace-object-instantiation=com.alibaba.nacos.common.notify.DefaultSharePublisher. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.`

**Describe the solution you'd like**
Positioning to the bottom layer source code, the error comes from the `static` code block in the` NotifyCenter` class, and solve the problem when the `static` code block is implemented with a constructor.

**Comment by KomachiSion** [comment]
we use mvn and docker build image, no found this problem, if you use graalvm build and found some problem, you can try to solve it by yourself. Or see the community whether has someone solved this problem.

**Comment by Jamel-jun** [comment]
I used the Quarkus framework

**Comment by Jamel-jun** [comment]
Nacos-client 2.1.0 and nacos client 1.4.3 is the same

**Comment by Jamel-jun** [comment]
Version is graalvm-ce-java11-21.2.0

**Comment by KomachiSion** [comment]
Can anyone in community can reproduce this problem and found problem?

**Comment by Jamel-jun** [comment]
I believe so

**Comment by YunWZ** [comment]
How about trying the version based on Java 8? For example [graalvm-21.2.0](https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0)

**Comment by enderwsp** [comment]
Considering the native support of database mybatis, jdk11+

**Comment by KomachiSion** [comment]
Refer to #8617
