### ISSUE TITLE
How @NacosValue implements the configuration update of the Map type data structure, and how to configure it on nacos

### ISSUE THREAD

**Issue by MentosL** [alibaba/nacos#8620]
**Is your feature request related to a problem? Please describe.**
How @NacosValue implements the configuration update of the Map type data structure, and how to configure it on nacos。
currently，i hope use @NacosValue directly config map structure。

**Comment by MentosL** [comment]
Currently implemented through @NacosConfigurationProperties

**Comment by KomachiSion** [comment]
see repo https://github.com/nacos-group/nacos-spring-boot-project

**Comment by MentosL** [comment]
> see repo https://github.com/nacos-group/nacos-spring-boot-project

what？ What I want to know is how to complete the configuration of the map structure through @NacosValue

**Comment by li-xiao-shuang** [comment]
> > see repo https://github.com/nacos-group/nacos-spring-boot-project
> 
> what？ What I want to know is how to complete the configuration of the map structure through @NacosValue

Can provide your configuration structure？

**Comment by MentosL** [comment]
> > > see repo https://github.com/nacos-group/nacos-spring-boot-project
> > 
> > 
> > what？ What I want to know is how to complete the configuration of the map structure through @NacosValue
> 
> Can provide your configuration structure？

yeah；

yaml example:

```yaml
user:
  names:
       1:zhangsan
       2:lisi
       3:wangwu
       4:zhaoliu
```

**Comment by li-xiao-shuang** [comment]
> > > > see repo https://github.com/nacos-group/nacos-spring-boot-project
> > > 
> > > 
> > > what？ What I want to know is how to complete the configuration of the map structure through @NacosValue
> > 
> > 
> > Can provide your configuration structure？
> 
> yeah；
> 
> yaml example:
> 
> ```yaml
> user:
>   names:
>        1:zhangsan
>        2:lisi
>        3:wangwu
>        4:zhaoliu
> ```

It can be configured as a string in yaml format, and then obtained from the code for parsing

**Comment by MentosL** [comment]
> > > > > see repo https://github.com/nacos-group/nacos-spring-boot-project
> > > > 
> > > > 
> > > > what？ What I want to know is how to complete the configuration of the map structure through @NacosValue
> > > 
> > > 
> > > Can provide your configuration structure？
> > 
> > 
> > yeah；
> > yaml example:
> > ```yaml
> > user:
> >   names:
> >        1:zhangsan
> >        2:lisi
> >        3:wangwu
> >        4:zhaoliu
> > ```
> 
> It can be configured as a string in yaml format, and then obtained from the code for parsing

The method you mentioned can achieve business purposes, but currently there are certain requirements for those who configure this variable, and it is difficult to configure the correct format at once.

**Comment by MentosL** [comment]
The person who wants to configure in the business is different from the person who configures it. If it is a string type, it is difficult for the person who configures to see the incorrect format.

**Comment by MentosL** [comment]
Do you have a conclusion?

**Comment by DickensTone** [comment]
Do you want a map contain below ?
      `1:zhangsan
       2:lisi
       3:wangwu
       4:zhaoliu`

**Comment by MentosL** [comment]
> Do you want a map contain below ? `1:zhangsan 2:lisi 3:wangwu 4:zhaoliu`

The content configuration is like this, but I hope that the configuration format on nacos is the same as the demo I provided above

**Comment by DickensTone** [comment]
> > Do you want a map contain below ? `1:zhangsan 2:lisi 3:wangwu 4:zhaoliu`
> 
> The content configuration is like this, but I hope that the configuration format on nacos is the same as the demo I provided above

I can't find a way to inject map by using **@NacosValue** or **@Value**.
if you don't like parse String, may you consider using anoter annotation to sove it , Use **@ConfigurationProperties** 

```java
@ConfigurationProperties(prefix = "user")
@Component
@Data
public class HTestConfig {
    private Map<String, String> names;
}
```

.Notice that, there is space after :  in yaml

**Comment by MentosL** [comment]
current version not support it.   colse it
