### ISSUE TITLE
 k8s deployment nacos2.1.0 version cluster node communication is not the same as expected

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#8621]
First we only used the configuration module。In the past we were using version 1.4.x，Recently considering upgrading to the latest version for performance reasons。
I deployed nacos cluster with version 2.1.0 on k8s，type is statefulset。What I configured in cluster.conf is the domain name,for ex:
```
xxxx-0.xxxx-headless.kube-system.svc.cluster.local:28600
xxxx-1.xxxx-headless.kube-system.svc.cluster.local:28600
```
After the service starts the file becomes ,
```
#2022-06-23T15:26:05.689
172.18.0.88:28600
xxxx-0.xxxx-headless.kube-system.svc.cluster.local:28600
xxxx-1.xxxx-headless.kube-system.svc.cluster.local:28600
```
172.18.0.88 is first pod pod_ip
When I publish the configuration, the nodes communicate through the rest interface，
If I configure ip in the cluster, I will use grpc to communicate.
I want to know how the ServerMemberManager.class accidentalizes the ServerAbilities of other nodes. I didn't find the relevant code, and I don't understand why there is such a difference between the domain name and ip.

By the way, I found a lot of "/v1/core/cluster/report" requests in access.log, this communication should also be achieved through grpc,right?

**Comment by KomachiSion** [comment]
see `nacos-docker` and `nacos-k8s` repo, the example include start way with hostname.

**Comment by KomachiSion** [comment]
nacos-server will check self whether in cluster.conf. If you use hostname, you should open `prefer-hostname-over-ip`

**Comment by five111** [comment]
thank you versy much ！ already solved！
Do you think reports between nodes should also use groc communication?
