### ISSUE TITLE
[Enhance] getting arguments use an unified way in the client module

### ISSUE THREAD

**Issue by onewe** [alibaba/nacos#8622]
## 背景

There are three ways of getting arguments in the client module now, from the properties、from the Jvm arguments and from the system environment.  so it needs an unified way that get arguments.

现在总共有3种获取参数的方式在客户端模块中, 有从 `properties`中获取的、从`Jvm`参数获取的和从`System`环境变了中获取的. 所以需要一种统一获取参数的方式.

The reasons are as follows:
- switch arguments getting order
- better mock test

原因如下:
- 提供切换参数读取顺序能力
- 更方便的模拟测试

More detail see https://www.yuque.com/docs/share/e9fcd9a3-f3fb-496d-9b8b-bf4b88db4df0

**Comment by li-xiao-shuang** [comment]
链接好像失效了

**Comment by xishian** [comment]
这个类跟用户侧有什么关系？为什么出现在Java SDK的文档里？
