### ISSUE TITLE
nacos 1.3.2 NacosException: failed to req API

### ISSUE THREAD

**Issue by guoerpang** [alibaba/nacos#8634]
![image](https://user-images.githubusercontent.com/44884849/175854570-66a0fb35-8f9c-4bc8-90ba-ce8670a87363.png)

服务启动直接报如图错误，然后导致服务挂死情况

**Comment by KomachiSion** [comment]
SocketTimeout 就是网络层面超时了， 检测一下客户端和服务端之间的网络是否正常（比如能否连接上，重传是不是很高）

这个只是异步任务，去获取服务列表，服务挂死和这个报错没有关系，甚至有可能是服务挂死才导致的超时。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
