### ISSUE TITLE
nacos2021.0.1.0 服务注册后状态默认是下线，需要手动点上线才能使用

### ISSUE THREAD

**Issue by gityuany** [alibaba/nacos#8647]
![image](https://user-images.githubusercontent.com/108328956/176127460-5a2c9d96-5074-4c32-bf42-b692f23f144d.png)

已尝试过删除data下的protocol所有目录及文件，还是没用

**Comment by gityuany** [comment]
补充：查看nacos日志，均为正常的，nacos为最近升级安装，目前是单节点
![image](https://user-images.githubusercontent.com/108328956/176128133-bddfb5c2-25d6-452a-b0f3-bc1b81190d50.png)

**Comment by KomachiSion** [comment]
1. 你注册服务的时候，默认设置了enabled=false
2. 这个ip手动操作过下线，这部分内容可以读一下nacos的openAPI中更新实例那一步骤。

**Comment by gityuany** [comment]
> 1. 你注册服务的时候，默认设置了enabled=false
> 2. 这个ip手动操作过下线，这部分内容可以读一下nacos的openAPI中更新实例那一步骤。
确认过注册是默认enabled=true的
![image](https://user-images.githubusercontent.com/108328956/176823456-b3217dd7-57fb-4a58-8193-68de0eb2924f.png)
第一次注册就是下线状态，没有操作过，同样服务在另外一个节点注册就没问题

**Comment by KomachiSion** [comment]
那就是有操作过这个ip下线了，这个操作会被记忆， 同一个服务的同一个ip下次再注册时候会复用上次的上下线状态，在修改实例的openAPI中有说明。

可能是你们自动化脚本做的，每次关闭服务都会自动调用下线。
