### ISSUE TITLE
2版本的Nacos在国产化服务器启动失败，启动报错如图，1.4.1可以启动

### ISSUE THREAD

**Issue by Wujxxxx** [alibaba/nacos#8651]
![image](https://user-images.githubusercontent.com/42757699/176376994-b843eb4b-a28f-4947-9de1-f7bf86ec5802.png)

**Comment by Wujxxxx** [comment]
环境信息：中科方德操作系统
内核版本：4.19.113-1.nfs.28.x86_64

**Comment by wuchubuzai2018** [comment]
> 中科方德操作系统

帅哥，可否分享下该系统的镜像ISO资源呢

**Comment by wuchubuzai2018** [comment]
看这个好像之前有人问过类似的问题：
https://github.com/alibaba/nacos/issues/4336
https://github.com/alibaba/nacos/issues/6718

**Comment by KomachiSion** [comment]
能否提供更关键的日志信息， 图片中的日志信息是结果，不是原因。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by springcloudconf** [comment]
能不能别再给我发邮件了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 晚上6:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 2版本的Nacos在国产化服务器启动失败，启动报错如图，1.4.1可以启动 (Issue #8651)





 
Closed #8651 as completed.

**Comment by ImproveSalaryProgrammer** [comment]
![1](https://user-images.githubusercontent.com/30406198/178388737-b73e1cce-485e-4e91-8479-4daf3789a0dc.jpg)
![2](https://user-images.githubusercontent.com/30406198/178388743-951639a6-02a8-4b37-98e3-0775e8a6078c.jpg)
![Uploading 3.jpg…]()
![Uploading 4.jpg…]()

**Comment by ImproveSalaryProgrammer** [comment]
![3](https://user-images.githubusercontent.com/30406198/178388973-f1a9f29f-0de4-4dff-b875-4276d09e01bf.jpg)
![4](https://user-images.githubusercontent.com/30406198/178389038-9e75ad21-6eea-400a-89aa-0aa59f9aac1f.jpg)

**Comment by ImproveSalaryProgrammer** [comment]
中科方德系统，在启动2.0.4的nacos-server过程中，出现该问题，so文件无法被映射到，1.4.1可以正常启动
