### ISSUE TITLE
Configuration List in Configuration Management: You want to add an enable to the configuration

### ISSUE THREAD

**Issue by Shing20** [alibaba/nacos#8657]
**Is your feature request related to a problem? Please describe.**
Configuration list in Configuration Management: Configuration is not enabled, and the disabled state

**Describe the solution you'd like**
Configuration List in Configuration Management: You want to add an enable to the configuration

**Describe alternatives you've considered**
Increase the state

**Additional context**
![1656499814961](https://user-images.githubusercontent.com/62784879/176419361-66dbc222-9a66-41b7-88bf-391ddf92b631.png)

**Comment by khanrakib1** [comment]
copy link not working
song not downloading.
plz help me

**Comment by KomachiSion** [comment]
I can't get your feature point.

What's the behavior of disable one config? Only stop push or delete in client?
If the first case, unlisten config is more reasonable. If the seconds, why not delete config directly?

And config is different with naming, naming disable is to remove the offline nodes, but config disable will be effect for all nodes. I don't think it's a reasonble feature.
