### ISSUE TITLE
The nacos-server-1.4.3 registration service appears: Client not connected, current status: STARTING

### ISSUE THREAD

**Issue by Shing20** [alibaba/nacos#8658]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
The nacos-server-1.4.3 registration service appears: Client not connected, current status: STARTING
Upgrade to nacos-server-2.1.0 resolved

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
see document please
