### ISSUE TITLE
nacos server gc的问题

### ISSUE THREAD

**Issue by Master-Jack** [alibaba/nacos#8660]
版本2.0.4，集群三节点
年轻代每6秒采集一次，增长速度180MB，平均下来每秒30MB的，每半分钟就会产生一次youngGc。请问是正常吗？
30多个服务，共有七十多个实例。没使用config。
![IMG_4588](https://user-images.githubusercontent.com/50773190/176575379-108b2815-14d6-4178-ade0-9f47c617783c.JPG)
![IMG_4589](https://user-images.githubusercontent.com/50773190/176575392-f9f7932c-f115-4e73-b257-5292f2d2be87.JPG)

**Comment by wuchubuzai2018** [comment]
看你的情况还出现了FGC，感觉存储了很多的对象数据，拿工具分析下，个人笔记好奇那600万的ConcurrentSkipListMap的Node数据都是什么东西

**Comment by jefferson-chern** [comment]
这个肯定不正常，fgc次数太频繁了，可以改用G1的垃圾收集器，并提高堆内存大小。

**Comment by Master-Jack** [comment]
> 这个肯定不正常，fgc次数太频繁了，可以改用G1的垃圾收集器，并提高堆内存大小。

full Gc 几天一次应该也不算频繁吧，也可能是限制了直接内存的大小

**Comment by Master-Jack** [comment]
> 

哪些数据每次young gc后都没了，奇怪的是为什么短时间内会产生这么多的对象

**Comment by Master-Jack** [comment]
> 看你的情况还出现了FGC，确实不太正常，感觉存储了很多的对象数据，拿内存泄漏工具分析下，那600万的ConcurrentSkipListMap的Node数据都是什么东西，目前我看源代码中只有几个类用了ConcurrentSkipListMap。 建议观察下ConcurrentSkipListMap的Node的数据的变化，是否持续增长

哪些数据每次young gc后都没了，奇怪的是为什么短时间内会产生这么多的对象

**Comment by wuchubuzai2018** [comment]
> > 看你的情况还出现了FGC，确实不太正常，感觉存储了很多的对象数据，拿内存泄漏工具分析下，那600万的ConcurrentSkipListMap的Node数据都是什么东西，目前我看源代码中只有几个类用了ConcurrentSkipListMap。 建议观察下ConcurrentSkipListMap的Node的数据的变化，是否持续增长
> 
> 哪些数据每次young gc后都没了，奇怪的是为什么短时间内会产生这么多的对象

dump下看看里面的对象都是什么，内存怎么配置的，估计也比较小

**Comment by Master-Jack** [comment]
> > > 看你的情况还出现了FGC，确实不太正常，感觉存储了很多的对象数据，拿内存泄漏工具分析下，那600万的ConcurrentSkipListMap的Node数据都是什么东西，目前我看源代码中只有几个类用了ConcurrentSkipListMap。 建议观察下ConcurrentSkipListMap的Node的数据的变化，是否持续增长
> > 
> > 
> > 哪些数据每次young gc后都没了，奇怪的是为什么短时间内会产生这么多的对象
> 
> dump下看看里面的对象都是什么，内存怎么配置的，估计也比较小

这几种类型就基本上都是了。年轻代老年代各1G，直接内存256m
![1](https://user-images.githubusercontent.com/50773190/176604912-929e2e89-00bc-4e12-87e3-85ab980e3ebe.png)
![2](https://user-images.githubusercontent.com/50773190/176604919-e89114e2-cfff-4162-89f7-b2e53c07dcb5.png)
![3](https://user-images.githubusercontent.com/50773190/176604925-4e741087-bd24-431c-8dda-2f58cb776c3a.png)

**Comment by Master-Jack** [comment]
看起来大部分数据都是来自ExponentiallyDecayingReservoir，数据的key也对的上
private final ConcurrentSkipListMap<Double, WeightedSample> values; 这个是类是干嘛的？

**Comment by wuchubuzai2018** [comment]
不过话说，你的JVM内存确实太小了，建议增大后看看情况

**Comment by li-xiao-shuang** [comment]
机器啥配置？

**Comment by Master-Jack** [comment]
2核4g





------------------ 原始邮件 ------------------
发件人: 李晓双 Li Xiao Shuang ***@***.***&gt;
发送时间: 2022年6月30日 23:42
收件人: alibaba/nacos ***@***.***&gt;
抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660)





 
机器啥配置？

**Comment by KomachiSion** [comment]
jvm参数发一下，然后dump内存看具体分析一下。

**Comment by Master-Jack** [comment]
`-Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=320m -XX:MaxDirectMemorySize=256m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/tomcat/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=3 -Dnacos.member.list= -Xloggc:/data/tomcat/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/data/tomcat/nacos/plugins/health,/data/tomcat/nacos/plugins/cmdb -Dnacos.home=/data/tomcat/nacos -jar /data/tomcat/nacos/target/nacos-server.jar --spring.config.additional-location=file:/data/tomcat/nacos/conf/ --logging.config=/data/tomcat/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288`






看起来大部分数据都是来自ExponentiallyDecayingReservoir，数据的key也对的上
private final ConcurrentSkipListMap<Double, WeightedSample&gt; values;&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660)





 
jvm参数发一下，然后dump内存看具体分析一下。

**Comment by Master-Jack** [comment]
> jvm参数发一下，然后dump内存看具体分析一下。

`-Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=320m -XX:MaxDirectMemorySize=256m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/tomcat/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=3 -Dnacos.member.list= -Xloggc:/data/tomcat/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/data/tomcat/nacos/plugins/health,/data/tomcat/nacos/plugins/cmdb -Dnacos.home=/data/tomcat/nacos -jar /data/tomcat/nacos/target/nacos-server.jar --spring.config.additional-location=file:/data/tomcat/nacos/conf/ --logging.config=/data/tomcat/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288`

![IMG_4592](https://user-images.githubusercontent.com/50773190/176816153-615ba47c-cd88-47ba-803c-86e73e47ca73.JPG)

看起来大部分数据都是来自ExponentiallyDecayingReservoir，数据的key也对的上
private final ConcurrentSkipListMap<Double, WeightedSample> values;

**Comment by KomachiSion** [comment]
`ExponentiallyDecayingReservoir` 是什么？ 没有影响有这个东西，能否查一下引用？

**Comment by Master-Jack** [comment]
引用就在上面图中呀，好像是开了鉴权的问题





------------------ 原始邮件 ------------------
发件人: 杨翊 SionYang ***@***.***&gt;
发送时间: 2022年7月4日 10:11
收件人: alibaba/nacos ***@***.***&gt;
抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660)





 
ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？

**Comment by jefferson-chern** [comment]
如果是jdk8，-Xms2g -Xmx2g  -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=320m -XX:+UseG1GC 可以试试，加了鉴权性能会受影响。

**Comment by Master-Jack** [comment]
我的问题不是gc问题，而在于短时间内生产了大量的对象，每15秒几乎就占满了800mb





------------------ 原始邮件 ------------------
发件人: Jefferson Chern ***@***.***&gt;
发送时间: 2022年7月5日 08:01
收件人: alibaba/nacos ***@***.***&gt;
抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660)





 
如果是jdk8，-Xms2g -Xmx2g  -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=320m -XX:+UseG1GC 可以试试，加了鉴权性能会受影响。

**Comment by KomachiSion** [comment]
> 引用就在上面图中呀，好像是开了鉴权的问题
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang ***@***.***&gt; 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos ***@***.***&gt; 抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么

**Comment by Master-Jack** [comment]
> > 引用就在上面图中呀，好像是开了鉴权的问题
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang _**@**_._**> 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos _**@**_.**_> 抄送: Master-Jack _**@**_._**>, Author _**@**_.**_> 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么

![IMG_4611](https://user-images.githubusercontent.com/50773190/177766027-8c6e45e1-5b6f-4773-9673-6058c6639192.JPG)
ExponentiallyDecayingReservoir 引用就这些

**Comment by hujun-w-2** [comment]
客户端的版本也是2.0.4?

**Comment by KomachiSion** [comment]
> > > 引用就在上面图中呀，好像是开了鉴权的问题
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang _**@**_._**> 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos _**@**_.**_> 抄送: Master-Jack _**@**_._**>, Author _**@**_.**_> 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么
> 
> ![IMG_4611](https://user-images.githubusercontent.com/50773190/177766027-8c6e45e1-5b6f-4773-9673-6058c6639192.JPG) ExponentiallyDecayingReservoir 被ConcurrentSkipListMap引用 再往外的引用就这些。

那ConcurrentSkipListMap是被什么引用， 你得找到源头。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by fejay** [comment]
兄弟, 请问解决了吗?

**Comment by fejay** [comment]
> > > 引用就在上面图中呀，好像是开了鉴权的问题
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang _**@**_._**> 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos _**@**_.**_> 抄送: Master-Jack _**@**_._**>, Author _**@**_.**_> 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么
> 
> ![IMG_4611](https://user-images.githubusercontent.com/50773190/177766027-8c6e45e1-5b6f-4773-9673-6058c6639192.JPG) ExponentiallyDecayingReservoir 被ConcurrentSkipListMap引用 再往外的引用就这些。

请问解决了吗?

**Comment by Master-Jack** [comment]
解决了







------------------ 原始邮件 ------------------
发件人: fengjian ***@***.***&gt;
发送时间: 2022年8月3日 15:01
收件人: alibaba/nacos ***@***.***&gt;
抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660)





    
引用就在上面图中呀，好像是开了鉴权的问题
 …
 ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang @.&gt; 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos _@**._&gt; 抄送: Master-Jack ***@***.***&gt;, Author @._&gt; 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt;
  
图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么
  
 ExponentiallyDecayingReservoir 被ConcurrentSkipListMap引用 再往外的引用就这些。
  
请问解决了吗?

**Comment by fejay** [comment]
> 解决了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: fengjian ***@***.***&gt; 发送时间: 2022年8月3日 15:01 收件人: alibaba/nacos ***@***.***&gt; 抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) 引用就在上面图中呀，好像是开了鉴权的问题 … ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang @.&gt; 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos _@**._&gt; 抄送: Master-Jack ***@***.***&gt;, Author @._&gt; 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt; 图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么 ExponentiallyDecayingReservoir 被ConcurrentSkipListMap引用 再往外的引用就这些。 请问解决了吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问怎么解决的, 和我的问题一样

**Comment by Master-Jack** [comment]
把鉴权关了





------------------ 原始邮件 ------------------
发件人: fengjian ***@***.***&gt;
发送时间: 2022年8月4日 23:06
收件人: alibaba/nacos ***@***.***&gt;
抄送: Master-Jack ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660)





  
解决了
 …
 ------------------ 原始邮件 ------------------ 发件人: fengjian @.&gt; 发送时间: 2022年8月3日 15:01 收件人: alibaba/nacos @.&gt; 抄送: Master-Jack @.&gt;, Author @.&gt; 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) 引用就在上面图中呀，好像是开了鉴权的问题 … ------------------ 原始邮件 ------------------ 发件人: 杨翊 SionYang @.&gt; 发送时间: 2022年7月4日 10:11 收件人: alibaba/nacos @**.&gt; 抄送: Master-Jack @.&gt;, Author @._&gt; 主题: Re: [alibaba/nacos] nacos server gc的问题 (Issue #8660) ExponentiallyDecayingReservoir 是什么？ 没有影响有这个东西，能否查一下引用？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 图里没有， 需要的是什么东西引用了ExponentiallyDecayingReservoir， 而不是ExponentiallyDecayingReservoir内引用了什么 ExponentiallyDecayingReservoir 被ConcurrentSkipListMap引用 再往外的引用就这些。 请问解决了吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.*&gt;
  
请问怎么解决的, 和我的问题一样
