### ISSUE TITLE
9848连接着的，但是服务突然间从服务列表消失了

### ISSUE THREAD

**Issue by 410853222** [alibaba/nacos#8661]
**Describe the bug**
docker部署方式，大多数服务没问题，突然某两个服务掉线了，服务本身未出现任何异常

**Desktop (please complete the following information):**
 - OS: [debain]
 - Version [e.g. nacos-server 2.0.3, nacos-client 2.0.3]
 - 
[抓包.zip](https://github.com/alibaba/nacos/files/9016230/default.zip)

**Comment by KomachiSion** [comment]
看下掉线服务的`${user.home}/logs/nacos/`下的日志，以及nacos服务端集群的`naming-server.log` 和 `remote-digest.log` 分析下着掉线的服务是不是和服务端之间连接断开了。

从表述上看，应该server出问题的概率不大，因为只有这两个服务掉了，大概率是这两个服务出了一些问题，导致连接被断开了。
