### ISSUE TITLE
nacos客户端2.0.1 PoolThreadCache 内存溢出

### ISSUE THREAD

**Issue by gefufeng** [alibaba/nacos#8663]
![image](https://user-images.githubusercontent.com/9637787/176615367-9679950d-5df4-49b0-acde-1ea49b6100e2.png)

**Comment by hujun-w-2** [comment]
这是什么场景下？
复现步骤有吗？

**Comment by KomachiSion** [comment]
https://blog.csdn.net/qq_27785239/article/details/105904601

这是netty的机制，通过cache提高线程切换效率，具体的创建，加入，释放由netty自己以及使用了netty的grpc来控制， nacos这测并没有感知这个属性，社区可以看看能否设置这个cache的最大值。

但是应该不存在泄漏问题。

**Comment by gefufeng** [comment]
我也不知道原因，大约服务启动一天多，然后CPU就突然上去了，然后看了一下原因，是大量的GC线程，然后就用mat分析了一下，这个客户端日志：
![image](https://user-images.githubusercontent.com/9637787/176849767-4f74ae2f-7d86-4b03-a1ca-f02be04ba69d.png)

**Comment by gefufeng** [comment]
昨天出现后，我把服务内存设置成了1G，但是今天又出现这种情况了：
![image](https://user-images.githubusercontent.com/9637787/176850136-d2cfbc03-864d-4b4e-9b17-280d40dcbb9c.png)

**Comment by KomachiSion** [comment]
看起来很像是因为其他问题导致发送请求失败了，导致请求大量积压和重试，才导致的Cache不停扩大。

可以升级客户端版本试试，看下新版本是否有所优化， 然后排查一下日志和监控，看下最开始请求失败的时候，系统有没有什么变化。

**Comment by dennissky** [comment]
-Dio.netty.allocator.useCacheForAllThreads=false 
-Dio.grpc.netty.shaded.io.netty.allocator.useCacheForAllThreads=false
这样搞一下不知道是否可行？

**Comment by dennissky** [comment]
-Dio.netty.allocator.cacheTrimIntervalMillis这个默认是0吧，也就是不释放

**Comment by afushengli** [comment]
我的2.0.3的版本也会出现这个问题，瞬间把我的服务器的cpu 拉高到400%

**Comment by KomachiSion** [comment]
No more response from author, I think the solution has solve the problem.

**Comment by wangke8023** [comment]
> 

我的2.0.3也出现了

**Comment by chen15126120** [comment]
2.0.2出现了这个问题

**Comment by xlzlyyy** [comment]
2.0.3同上，内存不断增大，最后每个节点配置10G一段时间后还是内存溢出

**Comment by xlzlyyy** [comment]
> 昨天出现后，我把服务内存设置成了1G，但是今天又出现这种情况了： ![image](https://user-images.githubusercontent.com/9637787/176850136-d2cfbc03-864d-4b4e-9b17-280d40dcbb9c.png)

你好，你后面问题解决了吗。怎么处理的

**Comment by lxqgithub** [comment]
有大佬解决了吗？
