### ISSUE TITLE
nacos 1.4.0集群节点状态异常

### ISSUE THREAD

**Issue by wytjiayou** [alibaba/nacos#8664]
服务器异常宕机，nacos-server节点不能正常下线。
![image](https://user-images.githubusercontent.com/21037575/176647487-8f8f4a1c-e823-485f-aa3b-6228ac743814.png)
163服务器宕机后，163节点一直处于SUSPICIOUS状态，不能正常切换到down状态

**Comment by KomachiSion** [comment]
更新到最新版本试试

**Comment by wytjiayou** [comment]
> 更新到最新版本试试

什么原理呢请问，之前验证过手动kill掉其中一个节点，一段时间后是能切换到down状态的。这种服务器异常宕机，不是很好验证呀

**Comment by wytjiayou** [comment]
> 更新到最新版本试试

异常时的日志如下：
![image](https://user-images.githubusercontent.com/21037575/177508377-45c274d8-632f-483a-890d-fa32d3b8c5ea.png)
根据日志找到对应两处源码位置：
![image](https://user-images.githubusercontent.com/21037575/177508588-28e404aa-1212-4749-b91f-366a3cdcba9e.png)
分析是不是走到了下面这个异常里面，请问这个异常捕获里面为什么不设置节点状态呢？
