### ISSUE TITLE
控制台集群管理没有做权限控制

### ISSUE THREAD

**Issue by hujun-w-2** [alibaba/nacos#8665]
**Is your feature request related to a problem? Please describe.**
The console cluster management does not perform permission control
控制台集群管理没有做权限控制，普通只要有public权限的用户就可以看到并且操作集群管理，大家讨论一下，这块是否需要改造？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MajorHe1** [comment]
能不能新增一种角色，介于 ROLE_READ和 ROLE_WRITE之间，只对某些 group 的 服务和配置有操作权限？

**Comment by hujun-w-2** [comment]
> 能不能新增一种角色，介于 ROLE_READ和 ROLE_WRITE之间，只对某些 group 的 服务和配置有操作权限？

或者简单点，只有管理员有权限操作集群管理

**Comment by MajorHe1** [comment]
就解决这个issue而言，只有管理员才能操作集群管理看起来没问题

**Comment by li-xiao-shuang** [comment]
可以通过绑定一个角色来控制，只有分配这个角色的人才能操作

**Comment by KomachiSion** [comment]
集群管理应该只有集群管理员可以操作吧，默认插件只有一个管理员用户，有此类需求可以实现自己的鉴权插件，针对集群管理这类接口做特殊的鉴权判断。
