### ISSUE TITLE
版本 2.1.0 鉴权插件 服务端始终403问题

### ISSUE THREAD

**Issue by skippyb1** [alibaba/nacos#8669]
只有get请求可以访问  post put delete都不可以

**Comment by onewe** [comment]
有 ng 代理嘛?

**Comment by onewe** [comment]
有复现步骤嘛?

**Comment by skippyb1** [comment]
没有ng,
复现步骤：
1. 按照官网 写一个插件 放在 plugins/selector下    
2. application.properties 修改nacos.core.auth.system.type为自定义的类型 和nacos.core.auth.enabled设置为true


目前用源码定位了一下  post请求 没有进Authfilter 过滤器

**Comment by KomachiSion** [comment]
哪个接口没进入AuthFilter?  AuthFilter应该是对`/*`路径的接口都能进入，只是有部分没有Secured注解的接口会快速退出。

**Comment by skippyb1** [comment]
> 哪个接口没进入AuthFilter? AuthFilter应该是对`/*`路径的接口都能进入，只是有部分没有Secured注解的接口会快速退出。

![image](https://user-images.githubusercontent.com/23324514/176811110-28b0d1da-6964-4a0a-b0ff-c54e401e832a.png)

**Comment by skippyb1** [comment]
> 哪个接口没进入AuthFilter? AuthFilter应该是对`/*`路径的接口都能进入，只是有部分没有Secured注解的接口会快速退出。

![image](https://user-images.githubusercontent.com/23324514/176812964-0a8ba81d-9630-4b25-bf35-125bddaa9552.png)
想问一下 如果AuthSystemTypes 是自定义的 ignoreUrls是不是就空了

**Comment by KomachiSion** [comment]
> authConfigs.getNacosAuthSystemType()

是，如果是自定义插件， 那就不应该走nacos的默认插件，所以不能有默认插件相关的东西影响自定义插件的url

**Comment by KomachiSion** [comment]
如果你有需要ignore的URL， 需要在你的自定义插件中去添加。

**Comment by skippyb1** [comment]
那403的问题   有什么解决办法吗  
还有post put  delete 请求不进入 AuthFilter过滤器的问题  
目前只是把官方的插件写完了 放到plugin 不生效   是我写法有问题吗 还是需要发新版 才能解决

**Comment by KomachiSion** [comment]
不进入AuthFilter大概率是被前面的Filter已经给拦截掉了，可能需要提供更多信息排查下问题。

AuthFilter的初始化和构造是在`com.alibaba.nacos.core.auth.AuthConfig` 定义的url就是`"/*"`

**Comment by ccfish86** [comment]
习惯就好，
nacos-client 1.4.2出的时候，用1.4.1连阿里云edas-nacos果断403，
现在nacos-client 1.4.3出来了，1.4.2连连阿里云edas-nacos不出意外的403。

**Comment by Arvinzhu** [comment]
请问这个问题解决了吗？
我在开发鉴权插件时也遇到了这个问题

**Comment by taxus1** [comment]
请问这个问题不改源码解决了吗？
