### ISSUE TITLE
dubbo 3.0.3  nacos 2.0.3  server list page can not find dubbo service

### ISSUE THREAD

**Issue by hepan** [alibaba/nacos#8671]
**Describe the bug**
dubbo provider service can be called ，but naocs server list page can not find the dubbo provider

**Expected behavior**
dubbo provider can show on the server list page

**Actually behavior**
nothing on my server list page

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: docker
 - Version nacos-server 2.0.3, dubbo-spring-boot-starter 3.0.8
 - Module  naming
 - SDK original, spring-cloud-alibaba-nacos, dubbo

**Comment by KomachiSion** [comment]
Please provider more information for detail.

The RPC can success means the service register ok. can list service possible your namespace input error.

**Comment by hepan** [comment]
i checked namespace config , i did not find error.
if i input error.  provider can called consumer ?

**Comment by hepan** [comment]
nacos update to 2.1.0 fixed the problem
