### ISSUE TITLE
解决M1 无法使用nacos高版本(2.0.3)问题

### ISSUE THREAD

**Issue by GithubGey** [alibaba/nacos#8674]
原文：https://blog.csdn.net/weixin_46237429/article/details/125572308
</br>

前言：
	M1 安装nacos 2.0.3 无法启动，一直报错，在nacos社区看到，大家都有相同的问题，就是M1 不支持高版本nacos，（1.3.x版本我试了，可以正常使用），所有我在社区留言，官方回复，nacos不支持M1
![nacos社区大家对M1题问](https://img-blog.csdnimg.cn/d87d404bc8a843959b6e58d4cb28b93e.png)
**not support m1 right now（目前不支持m1）**
![nacos不支持M1 版本](https://img-blog.csdnimg.cn/5f56bd3683b34d2fb7f8a9219bb27b3c.png)
并不是没有办法，我们可以寻求其他方法，我这里使用docker安装nacos2.0.3，并且可以正常使用
## 1.下载docker
点击[docker下载](https://www.docker.com/get-started/)下载Apple chip版本
##  拉去镜像

```shell
# 注意需要加版本号，否则会拉去失败
docker pull zhusaidong/nacos-server-m1:2.0.3
```
## 2.启动容器
这里以单点的模式为例,Docker启动需要暴露8848 9848 9849三个端口
为什么要开放三个端口？
可以发现[官方文档](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html)中有这么一段话：**Nacos2.0版本相比1.X新增了gRPC的通信方式，因此需要增加2个端口。新增端口是在配置的主端口(server.port)基础上，进行一定偏移量自动生成。**
```shell
docker run --env MODE=standalone --name nacos2.0.3 -d -p 8848:8848 -p 9848:9848 -p 9849:9849  zhusaidong/nacos-server-m1:2.0.3
```
## 3.第一次测试
访问 http://localhost:8848/nacos
## 4.配置数据库
我们在开发时，会将配置文件放到数据库中，此时我们就需要用到数据库
在docker中点击 Containers - OPEN IN TERMINAL(在终端中打开),见下图
![在这里插入图片描述](https://img-blog.csdnimg.cn/d4e97e7ff4f8474fa2901687d2fea121.png)
```shell
# 查看容器中的文件
ls -l
# 进入到conf
cd conf
# 编辑配置文件
vim application.properties
```
1.设置spring.datasource.platform=mysql
2.设置db.url.0= jdbc:mysql://locahost:3306/nacos-config? 将地址写成3.host.docker.internal，连接宿主机数据库
4.注掉db.url.1
5.配置数据库用户名和账密
![nacos数据库文件配置](https://img-blog.csdnimg.cn/52cda248704a4c688f0b1bd6ed3c8453.png)
## 重新启动容器
```shell
docker restart nacos2.0.3
```
## 访问测试
http://localhost:8848/nacos

**Comment by KomachiSion** [comment]
早在1.4版本的issue #4336 就已经讨论过了， 不支持M1 原因是rocksdb， 而rocksdb测提供的方案是使用oracle jdk. 在issue中都已经给出解决了。

另外nacos-docker项目应该已经有了支持M1的镜像，好像叫xxx-slim。 可以尝试下。如果那个镜像有问题可以试着提交pr到nacos-docker项目中进行修复。

**Comment by QiaoGen** [comment]
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/48583767/177245719-48c8ace1-cb5d-4e9a-8e64-f199ebcc414c.png">
早就有了

**Comment by zqq90** [comment]
ref: #8109

**Comment by YunWZ** [comment]
如果是开发需要在本地运行nacos，可以参考我的[这篇文章](https://www.yunweizhan.com.cn/archives/221)进行编译启动，其中使用的分支已合并当前最新代码。
