### ISSUE TITLE
The `/nacos/v1/cs/configs/listener` listener does not work 

### ISSUE THREAD

**Issue by Yurunsoft** [alibaba/nacos#8683]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

The `/nacos/v1/cs/configs/listener` listener does not work 

```curl
curl --location --request POST -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs/listener?accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY1NzAwNjM3Mn0.vZekJ93itrs_qaRn-whN2c5h3JY3kfPJFDALbt5sdzU" --header "Long-Pulling-Timeout: 30000" --form "Listening-Configs=data1^2DEFAULT_GROUP^2^1"
```
![GIF](https://user-images.githubusercontent.com/20104656/177239823-83583665-4edc-4ddb-9e6a-112394cdb4a7.gif)

### Describe what you expected to happen

Publish the configuration returns the correct

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

Nacos v2.1.0 standalone

**Comment by Yurunsoft** [comment]
Problem solved, I did not read the document clearly

**Comment by Rexoen** [comment]
Same problem here. Can you tell me which part the document covers?

> Problem solved, I did not read the document clearly

**Comment by Yurunsoft** [comment]
> Same problem here. Can you tell me which part the document covers?
> 
> > Problem solved, I did not read the document clearly

You can see: <https://github.com/nacos-group/nacos-group.github.io/pull/290/files#diff-b3705d57c4f21f922c6e1b45c169d97677be490047e59731be1813487fced067>

@KomachiSion The document PR I created before has been merged, when can you update it to the documentation site?

**Comment by Rexoen** [comment]
> > Same problem here. Can you tell me which part the document covers?
> > > Problem solved, I did not read the document clearly
> 
> You can see: https://github.com/nacos-group/nacos-group.github.io/pull/290/files#diff-b3705d57c4f21f922c6e1b45c169d97677be490047e59731be1813487fced067
> 
> @KomachiSion The document PR I created before has been merged, when can you update it to the documentation site?

Problem solved here too. Thank you for the contribution.👍
