### ISSUE TITLE
Is there sdk for rust?

### ISSUE THREAD

**Issue by intfish123** [alibaba/nacos#8687]
What's the time to build sdk for rust?

**Comment by li-xiao-shuang** [comment]
> What's the time to build sdk for rust?

Do you have such a need?

**Comment by intfish123** [comment]
Yes, It's in great request!

**Comment by li-xiao-shuang** [comment]
> Yes, It's very necessary

Are your projects already using rust in production?  At present, the demand for rust sdk is still relatively small

**Comment by KomachiSion** [comment]
duplicate with #8443
