### ISSUE TITLE
Some api's of namespaces have inconsistent naming of parameters

### ISSUE THREAD

**Issue by Yurunsoft** [alibaba/nacos#8688]
**Is your feature request related to a problem? Please describe.**

Some api's of namespaces have inconsistent naming of parameters

**Describe the solution you'd like**

Uniform parameter naming

**Describe alternatives you've considered**

Add new uniformly named parameters, keep the old ones for compatibility

**Additional context**

**Comment by KomachiSion** [comment]
Close reason in PR.

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/issues/8308
