### ISSUE TITLE
/nacos/v1/ns/instance/list 实际返回结果与文档不符

### ISSUE THREAD

**Issue by Yurunsoft** [alibaba/nacos#8692]
**Describe the bug**

`/nacos/v1/ns/instance/list` 返回结果与文档不符，是文档没有及时更新吗？

![image](https://user-images.githubusercontent.com/20104656/177455691-22fdcf56-39dc-497b-89e7-3d8829944c27.png)
![image](https://user-images.githubusercontent.com/20104656/177455714-3692da52-c32e-47d7-ab9b-caf055fb6b82.png)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version v2.1.0
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
@Yurunsoft Can you help us to upgrade document?

**Comment by Yurunsoft** [comment]
> @Yurunsoft Can you help us to upgrade document?

OK

**Comment by Yurunsoft** [comment]
> @Yurunsoft Can you help us to upgrade document?

This is my pr: <https://github.com/nacos-group/nacos-group.github.io/pull/290>

I found some documentation issues during the development of the php sdk, which have been modified in this PR

This is the php sdk I developed: <https://github.com/Yurunsoft/nacos-php>

Request and response data are all strongly typed and IDE friendly.

Complete test cases and support for Swoole Coroutine.

**Comment by KomachiSion** [comment]
> > @Yurunsoft Can you help us to upgrade document?
> 
> This is my pr: [nacos-group/nacos-group.github.io#290](https://github.com/nacos-group/nacos-group.github.io/pull/290)
> 
> I found some documentation issues during the development of the php sdk, which have been modified in this PR
> 
> This is the php sdk I developed: https://github.com/Yurunsoft/nacos-php
> 
> Request and response data are all strongly typed and IDE friendly.
> 
> Complete test cases and support for Swoole Coroutine.

Nice, I will review PR.

About the PHP SDK, If you can contribute to nacos community and can maintain continuously, Nacos community is very glad to receive.

**Comment by KomangRedi** [comment]
Wow

**Comment by KomachiSion** [comment]
The document PR has merged, so I will close this issue. If you want to donate PHP-SDK, plaese submit new issue to describe it.
