### ISSUE TITLE
目前服务端启动时，grpc端口在tcp端口基础上固定漂移1000，能否在配置文件中新增配置项设置grpc端口?

### ISSUE THREAD

**Issue by jiajiangnan** [alibaba/nacos#8695]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by onewe** [comment]
偏移量是可以进行配置的 https://github.com/alibaba/nacos/issues/7149

**Comment by jiajiangnan** [comment]
> #7149 这个PR修复的偏移量是 client 的，但是 server 端启动的时候，偏移量还是无法配置。

**Comment by jiajiangnan** [comment]
> 偏移量是可以进行配置的 #7149

#7149  这个PR修复的偏移量是 client 的，但是 server 端启动的时候，偏移量还是无法配置。

**Comment by onewe** [comment]
@jiajiangnan 不好意思 看错了 😅

**Comment by jiajiangnan** [comment]
> @jiajiangnan 不好意思 看错了 😅

@onewe 我修复了，待会提一个PR.

**Comment by KomachiSion** [comment]
什么情况需要特殊配置grpc端口？ 固定偏移量有什么问题吗？

客户端需要自定义偏移量是因为用户可能会在代理和vip上配置不同的端口映射。但是服务端应该不需要。

**Comment by KomachiSion** [comment]
> > @jiajiangnan 不好意思 看错了 😅
> 
> @onewe 我修复了，待会提一个PR.

PR前请先在issue中讨论。

**Comment by jiajiangnan** [comment]
> 什么情况需要特殊配置grpc端口？ 固定偏移量有什么问题吗？
> 
> 客户端需要自定义偏移量是因为用户可能会在代理和vip上配置不同的端口映射。但是服务端应该不需要。

@KomachiSion 
如果偏移量固定了，假设本机端口 8848 空闲，而 9848 或者 9849 端口已经由其他应用占用，那么服务端启动的时候，grpc 就会因为 offset 固定而导致无法启动。

**Comment by jiajiangnan** [comment]
还有一种场景，由于服务器所在网络以及其他限制，只允许开放某些特定区间段的端口，而恰好 nacos 的通讯端口不在这个范围内，也会出现问题。

**Comment by KomachiSion** [comment]
1. 可以调整主端口8848来避开某一个其他端口占用的问题。
2. 通过vip等网络设施进行端口转发，我想有这种要求的网络环境一般都不允许直连服务器吧，都有一层网络拦截器。

**Comment by jiajiangnan** [comment]
是的，通过调整8848端口来避免端口占用，在一定程度上能够解决这个问题，但个人觉得不是很完美😄   勿怪......



本来我的思路是可以增加端口的配置项来处理，但是后来我仔细研究了一下，也不是简单改动启动配置就行，因为我发现在源码里面有多处是基于8848端口来进行固定偏移，例如Raft的端口是 -1000，grpcSdk 是 +1000，grpcCluster 是 +1001。如果简单改动了启动端口，那么无论server端或是client端，在建立通讯连接时，需要增加更多的配置，增加的了配置的复杂度。

所以我在想，是否可以提供一个接口，在服务启动的时候获取集群中各server实例基础元数据，把端口号包含在里面，
而在新启server或者client实例时，可以根据该接口中的信息来建立连接从而进行通讯。

**Comment by KomachiSion** [comment]
> 是的，通过调整8848端口来避免端口占用，在一定程度上能够解决这个问题，但个人觉得不是很完美😄 勿怪......
> 
> 本来我的思路是可以增加端口的配置项来处理，但是后来我仔细研究了一下，也不是简单改动启动配置就行，因为我发现在源码里面有多处是基于8848端口来进行固定偏移，例如Raft的端口是 -1000，grpcSdk 是 +1000，grpcCluster 是 +1001。如果简单改动了启动端口，那么无论server端或是client端，在建立通讯连接时，需要增加更多的配置，增加的了配置的复杂度。
> 
> 所以我在想，是否可以提供一个接口，在服务启动的时候获取集群中各server实例基础元数据，把端口号包含在里面， 而在新启server或者client实例时，可以根据该接口中的信息来建立连接从而进行通讯。但是这种方式的话，如果是通过vip进行端口转发，还是需要进行配置项配置。 因此，默认通过协议接口获取元数据，同时可以在配置项中强制修改对应server的通讯端口进行覆盖。

本来从设计中就是希望用户尽可能简单使用，所以只在配置中暴露主端口，其余端口通过偏移量自动计算，对于一些高能力用户，设置偏移量也是有需求的，但主要是在客户端测， 服务端测不是特别合理。

**Comment by jiajiangnan** [comment]
> 
> 本来从设计中就是希望用户尽可能简单使用，所以只在配置中暴露主端口，其余端口通过偏移量自动计算，对于一些高能力用户，设置偏移量也是有需求的，但主要是在客户端测， 服务端测不是特别合理。


嗯嗯。理解。但还是想问：后续是否有计划针对这一点进行升级。




如果有，是否可以从以下角度进行处理：

服务端：
1、保留固定偏移量的设计
2、增加各协议端口的配置项
3、新增服务节点 Metadata 元数据信息接口，便于服务集群或客户端自动获取并建立连接进行通讯

集群节点与客户端：
1、针对一般情况减少配置项：默认从服务端新增的 Metadata 元数据信息接口获取各服务节点信息，建立连接进行通讯
2、针对经过网络层面或其他处理导致实际与 Metadata 不一致的特殊情况，则可进行配置强制覆盖接口返回的信息

**Comment by KomachiSion** [comment]
目前没有这个计划， 过多依赖服务节点元数据可能会导致一系列稳定性问题，注册配置中心还是以稳定为主。
至于增加端口配置项如果社区诉求强烈其实可以考虑，无非就是要求用户所有集群配置的端口一致即可。

**Comment by jiajiangnan** [comment]
> 目前没有这个计划， 过多依赖服务节点元数据可能会导致一系列稳定性问题，注册配置中心还是以稳定为主。 至于增加端口配置项如果社区诉求强烈其实可以考虑，无非就是要求用户所有集群配置的端口一致即可。

👌 OK. 那这个 issue 关闭了哈

**Comment by hmleo** [comment]
一个客户端程序 需要连接不同的nacos服务端，而这几个服务端的grpc端口偏移量不一致怎么办？？

默认偏移1000没毛病，但还是建议支持在构造客户端的时候可以手动指定grpc端口(或偏移量)
