### ISSUE TITLE
standalone 模式下，grpc 的Cluster仍会启动

### ISSUE THREAD

**Issue by jiajiangnan** [alibaba/nacos#8696]
**Describe the bug**
standalone 模式下，grpc 的Cluster仍会启动，即8848、9848、9849端口都开启

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/43714056/177577961-0311436b-d029-4521-80c7-85449854155d.png">

**Expected behavior**
standalone 模式下，grpc 的Cluster应该不启动，即8848、9848端口开启，9849端口不应开启

**Comment by KomachiSion** [comment]
开启有何影响？我认为没必要关闭吧。先进行讨论吧，PR我先关了。

**Comment by jiajiangnan** [comment]
> 
@KomachiSion  
我的理解是：既然已经有参数用来区分单机模式与集群模式，那么启动模式应当参照这个参数的定义来设置。不然这个参数会让人感觉存在歧义。

**Comment by jiajiangnan** [comment]
> 开启有何影响？我认为没必要关闭吧。先进行讨论吧，PR我先关了。

@KomachiSion 
1、我是这样理解的，既然有 standalone 参数可以指定启动模式，那么后续的步骤应当根据参数的定义来进行。一方面定义了 standalone 启动，一方面又启动了 grpcClusterServer，容易造成参数作用歧义。
2、既然是单机启动，那就不存在服务端之间的通讯，那么多开这一个端口，并没发挥作用而形成浪费
3、在 #8695 这个issue如果讨论通过进行修复后，作为用户，设置了 standalone 模式启动，除了要配置 grpcSdkServer 的偏移量外，还要配置 grpcClusterServer 的偏移量，用户体验上会感觉有点怪异。

**Comment by KomachiSion** [comment]
1. 单例模式通常是大家的测试环境和开发环境，如果不启动grpcClusterServer，少启动了端口，当用户部署线上集群模式环境的时候，可能会因为少开启端口（如防火墙之类的）而导致数据不一致的问题。所以单例模式打开grpcClusterServer从而开启端口并没有歧义，这是在透露nacos需要这个端口。
3. 我认为这不是问题，即使增加了端口配置，单例模式可以不配置嘛

**Comment by jiajiangnan** [comment]
😊，如果是出于测试环境和开发环境的便捷性的考虑的话，我竟觉得也不是没有道理........
