### ISSUE TITLE
DeregisterInstanceTraceEvent should always hold instance port

### ISSUE THREAD

**Issue by zqq90** [alibaba/nacos#8698]
**Describe the bug**

When the heartbeat of an instance times out, it will be deregistered, and a DeregisterInstanceTraceEvent will be published,
However, this event does not hold the port of the instance

**Expected behavior**

Hold hold instance port, Consistent with 'client initiates request'

See: https://github.com/alibaba/nacos/blob/fcc9b0aef97e753650b4622c328f2913a44c5a76/naming/src/main/java/com/alibaba/nacos/naming/controllers/InstanceControllerV2.java#L159

**Actually behavior**

See: https://github.com/alibaba/nacos/blob/fcc9b0aef97e753650b4622c328f2913a44c5a76/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/heartbeat/ExpiredInstanceChecker.java#L82

**Comment by scienceZ** [comment]
thank you so much for your suggestion，the instanceIp should hold instance port. I will check this problem in all trace module.

**Comment by zqq90** [comment]
> thank you so much for your suggestion，the instanceIp should hold instance port. I will check this problem in all trace module.

The field `instanceIp` is ambiguous. It is recommended to add a new field, or rename it.

cc @scienceZ

**Comment by zqq90** [comment]
TO @KomachiSion 

The affected functions seem to be newly added in this milestone.
So can this issue catch up with version 2.1.1?

**Comment by KomachiSion** [comment]
Has Pr https://github.com/alibaba/nacos/pull/8805 fixed this problem?

**Comment by scienceZ** [comment]
> Has Pr #8805 fixed this problem?

yes
