### ISSUE TITLE
About Nacos's namespace and tenant design

### ISSUE THREAD

**Issue by xuechaos** [alibaba/nacos#870]
About Nacos's namespace and tenant design

**Comment by yd0906** [comment]
Have you solved this problem? I see that OPEN-API requires the parameter to be named "namespaceId", but the parameter encapsulated in the NaminogProxy class of "nacos-client-0.6.2.jar" is named "tenant".
How to solve this problem by registering services in different namespaces through nacos-client: 0.6.2

**Comment by nkorange** [comment]
@yd0906 Use nacos-client above 0.8.0
