### ISSUE TITLE
The address module can't use directly

### ISSUE THREAD

**Issue by onewe** [alibaba/nacos#8701]
if you start the address module directly, you wont be able to use it. the module depends on spring-security and is used the default setting, so if you open your browser and access `http://localhost:8080`, it will go to login page.
如果直接启动 `address` 模块, 是不能使用的. 这个模块依赖了 `spring-security` 并且使用的是默认配置,所以打开浏览器访问`http://localhost:8080`将会跳转到`login`页面

Does it need to ignore about the spring-security configuration?
需要忽略掉`spring-security`相关配置嘛?

**Comment by pixystone** [comment]
Make `ignore-urls` includes serverlist controller endpoints.

**Comment by pixystone** [comment]
Some ops api need to be secured.

**Comment by onewe** [comment]
Ok, I got. 

@I will resolve it@
