### ISSUE TITLE
nacos-2.1集群搭建遇到的异常

### ISSUE THREAD

**Issue by my-liu** [alibaba/nacos#8703]
**nacos2.1.0集群部署，新增nacos节点无法同步到所有节点**
我有4台服务分别的A\B\C\D ，ABC服务器nacos.cluster.conf里面的IP分别是ABC三台服务器的IP+端口 A=11110 B=11140 C=11170
三台启动在控制台看到集群-节点列表是正常的,然后我的D服务器的nacos.cluster.conf配置的IP是ABCD的四台服务的IP+端口，启动后在D的控制台是能看到其他三台nacos服务的。**但ABC三台nacos控制台是看不到D服务的**。有人知道这个是什么情况吗？
**以下是protocol-distro\protocol-raft.log日志**：
[protocol-distro.log](https://github.com/alibaba/nacos/files/9061790/protocol-distro.log)
[protocol-raft.log](https://github.com/alibaba/nacos/files/9061778/protocol-raft.log)

更详细请通过该链接查看[https://ask.csdn.net/questions/7754461?spm=1001.2014.3001.5505](https://ask.csdn.net/questions/7754461?spm=1001.2014.3001.5505)

**Comment by my-liu** [comment]
如我已经有5个nacos-server节点集群了，此时新增俩个nacos-server节点到集群中，我需要将已启动的5个节点手动在cluster.conf添加新增的2个节点的IP才能一切正常，否则就会出现上述错误，对于该问题我发邮件给官方了，目前还没有收到回复！

**Comment by KomachiSion** [comment]
肯定需要在旧节点添加，否则什么人只要随意添加一个节点到你们集群，就可以通过那个特殊节点获取所有数据了。

目前nacos仅支持两类扩容方式，第一种就是通过修改整个集群的cluster.conf，第二种是地址服务器添加地址。相关的插件化工作正在 开源之夏2022的相关课题中推进，可以关注下，后续你可以按照你的想法试试用插件的方式实现一个。
