### ISSUE TITLE
2.0 server+1.0 client组合集群负载评估

### ISSUE THREAD

**Issue by whl12345** [alibaba/nacos#8706]
Nacos集群节点数：15节点
单节点硬件：16核16G
单节点jvm配置：-Xms10g -Xmx10g -Xmn4g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
Nacos服务端版本：2.1.0，关闭双写
Dubbo 2.7依赖Nacos客户端版本：1.1.4
生产测试：dubbo 服务注册Nacos集群实例数在45000左右就会出现异常，表现为频繁full gc，临时实例丢失，部分节点挂掉的现象
目前因为客户端升级比较难推，我们想要在客户端升级到2.0之前，支持10W的实例注册，有哪些可行方案？

如何调整才能提升整个集群负载?

**Comment by KomachiSion** [comment]
增加tomcat的worker线程池试试看

使用1.x客户端的瓶颈在于distro的转发时的线程损耗。

**Comment by KomachiSion** [comment]
另外，节点数并非越多越好， 越多distro同步的压力就越大， 可以适当减少节点数，增加tomcat worker数。

**Comment by whl12345** [comment]
都使用1.1.4客户端
服务端2.0集群关双写，和1.1.4集群相比性能有多大提升？

**Comment by KomachiSion** [comment]
理论上应该性能差不多，可能会略有下降。 因为没有使用到2.0的新版本能力，仍然使用和1.1.4集群相同的逻辑。

**Comment by whl12345** [comment]
2.x协议变更是否会影响集群峰值负载稳定性
