### ISSUE TITLE
NacosNamingService.getSubscribeServices()  没有返回全部服务列表

### ISSUE THREAD

**Issue by yulinfeng1024** [alibaba/nacos#8712]
我在某个服务调用这个   NacosNamingService.getSubscribeServices()  方法的时候,返回的数据中只有当前服务的信息，没有全部的服务列表。
<img width="320" alt="1657246666074_9068E15F-CE06-4591-859B-572FDC6C4D45" src="https://user-images.githubusercontent.com/108912422/177907185-d9ca9f13-5589-46c5-bc54-be86d1cd99fd.png">
发现该map中只有当前服务，查询官网文档没有这个方法的说明，我该怎么做才能获取全部服务列表？

**Comment by YunWZ** [comment]
1. 通过“查询服务列表”接口获取服务名称--`/nacos/v1/ns/service/list`；
2. 通过服务名称查询实例列表--`/nacos/v1/ns/instance/list`；

参考[官网文档](https://nacos.io/zh-cn/docs/open-api.html)

**Comment by wuchubuzai2018** [comment]
应该是调用 NacosNamingService类中的这几个方法
@Override
    public ListView<String> getServicesOfServer(int pageNo, int pageSize, String groupName) throws NacosException {
        return getServicesOfServer(pageNo, pageSize, groupName, null);
    }
    
    @Override
    public ListView<String> getServicesOfServer(int pageNo, int pageSize, AbstractSelector selector)
            throws NacosException {
        return getServicesOfServer(pageNo, pageSize, Constants.DEFAULT_GROUP, selector);
    }
    
    @Override
    public ListView<String> getServicesOfServer(int pageNo, int pageSize, String groupName, AbstractSelector selector)
            throws NacosException {
        return clientProxy.getServiceList(pageNo, pageSize, groupName, selector);
    }

**Comment by pengweizhong** [comment]
还是无法获取到。。。
```bash
pengwz@GE66:~$ curl -X GET '192.168.1.156:8848/nacos/v1/ns/service/list?pageNo=1&pageSize=10'
{"doms":[],"count":0}
```
