### ISSUE TITLE
2.0Client rpc调用单节点问题疑问。

### ISSUE THREAD

**Issue by freedom-all** [alibaba/nacos#8715]
hi
目前2.0client 请求配置中心信息走的是grpc长连接，这样导致一个客户端永远只能nacos集群的某个单一的节点。如果这个时候该nacos节点失败下线，客户端是如何切换到其他节点获取正常服务数据。
谢谢！

**Comment by hh13516117509** [comment]
我觉得可以看看 RpcClient  中是 start方法,添加了两个异步任务,其中第二个任务在发现连接失败的时候, 会调用  reconnect(reconnectContext.serverInfo, reconnectContext.onRequestFail); 方法  ,在   serverInfo = recommendServer.get() == null ? nextRpcServer() : recommendServer.get(); 可以取到其他节点然后尝试连接. 不知道是否正确,如有其他观点,欢迎探讨.

**Comment by freedom-all** [comment]
看到了， 谢谢大家
