### ISSUE TITLE
nacos client ConfigService publishConfig interface add method contain publish appName

### ISSUE THREAD

**Issue by gitchong** [alibaba/nacos#8716]
when I publish config use nacos client, Inject NacosService, then call  method [boolean publishConfig(String dataId, String group, String content) throws NacosException;]

I want to publish appName also but I dont find a method to achieve this goal
how can I do for this ?

**Is your feature request related to a problem? Please describe.**
need a param appName

**Describe the solution you'd like**
add a new method and add appName params。

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
dataId has no relation with appName in design. If add in client api? how about publish config in console?

App is not a useful param in nacos, only help filter in listen config.

**Comment by wuchubuzai2018** [comment]
他应该是想区分是什么业务调用的服务，他们可能有很多业务系统；

**Comment by wuchubuzai2018** [comment]
> dataId has no relation with appName in design. If add in client api? how about publish config in console?
> 
> App is not a useful param in nacos, only help filter in listen config.

你怎么把别人家正经的需求关闭了呢，我发现大神你老是没深入理解别人的真实需求后就处理。不太好哦！
这个是很有用的需求啊，NacosConfigService的类屏蔽了外部手动声明appName的API，导致API层面无法动态指定appName，我是在类中增加了publishConfigAppName方法，本地测试通过了，希望可以提交我的Nacos的第二个PR，指定不了appName,控制台的归属应用就是空了，服务多了无法识别了。
希望我可以解决这个ISSUE

**Comment by gitchong** [comment]
> > dataId has no relation with appName in design. If add in client api? how about publish config in console?
> > App is not a useful param in nacos, only help filter in listen config.
> 
> 你怎么把别人家正经的需求关闭了呢，我发现大神你老是没深入理解别人的真实需求后就处理。不太好哦！ 这个是很有用的需求啊，NacosConfigService的类屏蔽了外部手动声明appName的API，导致API层面无法动态指定appName，我是在类中增加了publishConfigAppName方法，本地测试通过了，希望可以提交我的Nacos的第二个PR，指定不了appName,控制台的归属应用就是空了，服务多了无法识别了。 希望我可以解决这个ISSUE

I agree very much, I really need it

**Comment by wuchubuzai2018** [comment]
我提交了一个PR，希望通过后可以帮助到你
