### ISSUE TITLE
持久化实例更新meta后，注销实例再重新注册(meta是其他参数)，查询时会查到旧meta

### ISSUE THREAD

**Issue by zz630** [alibaba/nacos#8717]
已查过其他issue，像#6295 Fix instance metadata will not be removed for ip port client.与本例无关

**Describe the bug**
持久化实例更新meta后，注销实例再重新注册(meta是其他参数)，查询时会查到旧meta。

**How to Reproduce**
1. 在控制台更新持久化实例的meta，例如{"version":"old"}，调用PUT /nacos/v1/ns/instance，最终会更新NamingMetadataManager#instanceMetadataMap2
2.注销该实例，再用同样的ip和port注册，meta是{"test":"new"}
3.查询实例列表GET /nacos/v1/ns/catalog/instances，返回的meta是{"version":"old","test":"new"}，把旧的meta也一起返回了，原因是ServiceStorage#parseInstance会查旧的meta数据NamingMetadataManager#instanceMetadataMap2一起返回

想确定设计思路是meta修改后，就不再随着实例的注销一起删除吗？跟了代码和用arthas watch NamingMetadataManager#instanceMetadataMap2，没发现注销时有删meta

Checked other issues like #6295 Fix instance metadata will not be removed for ip port client. Not relevant to this case

**Describe the bug**
After the persistent instance updates the meta, log out the instance and re-register it (meta is another parameter), and the old meta will be found when querying.

**How to Reproduce**
1. Update the meta of the persistent instance in the console, such as {"version":"old"}, call PUT /nacos/v1/ns/instance, and finally update NamingMetadataManager#instanceMetadataMap2
2. Log out the instance, and then register with the same ip and port. The meta is {"test":"new"}
3. Query the instance list GET /nacos/v1/ns/catalog/instances, the returned meta is {"version":"old","test":"new"}, and the old meta is also returned. The reason is that ServiceStorage#parseInstance will check the old meta data NamingMetadataManager#instanceMetadataMap2 and return it together

Want to make sure that the design idea is that after the meta is modified, it will not be deleted together with the logout of the instance? Following the code and using arthas watch NamingMetadataManager#instanceMetadataMap2, I didn't find that meta was deleted when logging out

**Desktop (please complete the following information):**
 - Version [e.g. nacos-server 2.0.3, nacos-client 2.0.3]
 - Module [e.g. naming]

**Comment by KomachiSion** [comment]
1. 请细读文档
![image](https://user-images.githubusercontent.com/37170243/177967089-3f0db02a-e061-4a58-ae56-139884a245b3.png)

2. 请细读issue， 你发的issue里已经详细解释过了

**Comment by zz630** [comment]
> * 请细读文档
>   ![image](https://user-images.githubusercontent.com/37170243/177967089-3f0db02a-e061-4a58-ae56-139884a245b3.png)
> * 请细读issue， 你发的issue里已经详细解释过了

谢谢，这两个都是默认值expired-time 60000 ms和interval 5000 ms，我跟一下为什么没定时删除

**Comment by zz630** [comment]
跟了下代码，ExpiredMetadataCleaner#doClean是有定时执行的，但是ExpiredMetadataCleaner #metadataManager#getExpiredMetadataInfos()为空。
watch NamingMetadataManager#updateExpiredInfo在持久化实例注销，或者注册时，都没有被调用过。NamingMetadataManager#handleInstanceMetadataEvent的调用方只有EphemeralClientOperationServiceImpl和ExpiredInstanceChecker会去new事件，前者是临时实例的，后者watch没有执行也没找到日志

**Comment by KomachiSion** [comment]
旧版本好像有个bug， 用1.x客户端注册的服务不会发出元数据过期事件， 新版本已经修复了， 升级到2.1.0试试吧。

**Comment by KomachiSion** [comment]
升级后可能需要先把脏数据清理一下。

**Comment by KomachiSion** [comment]
@zz630 any process？

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
