### ISSUE TITLE
登录nacos时，用户密码明文传输问题

### ISSUE THREAD

**Issue by hxz123** [alibaba/nacos#8718]
nacos1.4.3版本
登录nacos时，用户密码使用的是明文传输，如何采用密文传输？

**Comment by hujun-w-2** [comment]
可以自己拓展权限插件

**Comment by springcloudconf** [comment]
你们都是谁啊，能不能别给我发邮件了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月9日(星期六) 中午12:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 登录nacos时，用户密码明文传输问题 (Issue #8718)





 
可以自己拓展权限插件

**Comment by varGengYang** [comment]
> 服务端升级到2.1.0，可以自己开拓权限插件

根据官方文档：https://nacos.io/zh-cn/docs/config-encryption.html

**Comment by wuchubuzai2018** [comment]
建议官方或者有人可以实现基于RSA的前端用户密码加密登录，像一些银行内部是很需要的

**Comment by varGengYang** [comment]
> 建议官方或者有人可以实现基于RSA的前端用户密码加密登录，像一些银行内部是很需要的
不只是银行，任何系统都不行，安全测试第一步就通不过。

**Comment by KomachiSion** [comment]
默认的鉴权实现仅是一个实现demo，并带有一点防止错用的能力，并不承诺强安全性， 这个在文档中已经明确。

考虑到公司有强安全诉求，可以通过鉴权插件开发自行对接公司的强安全鉴权体系，当然前端肯定是没法适配的，需要自行开发。
