### ISSUE TITLE
Upgrade from 0.8.0 to 0.9.0, interface error

### ISSUE THREAD

**Issue by D-PENG** [alibaba/nacos#872]
Interface
>```
> http://xxx.xxx.x.xx:8848/nacos/v1/console/server/state
>```

**Comment by D-PENG** [comment]
>```
> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Thu Mar 07 11:49:41 GMT+08:00 2019
> There was an unexpected error (type=Unauthorized, status=401).
> Unauthorized
>```

**Comment by nkorange** [comment]
Upgrade to 1.0.0 please.
