### ISSUE TITLE
2.0.x 版本的Nacos在国产化服务器启动失败，启动报错如图，1.4.1可以启动

### ISSUE THREAD

**Issue by ImproveSalaryProgrammer** [alibaba/nacos#8734]
环境信息：中科方德操作系统
内核版本：4.19.113-1.nfs.28.x86_64

错误信息如下
![1](https://user-images.githubusercontent.com/30406198/178398233-fa656c5f-4f2d-4d32-a367-9a01fc227d40.jpg)
![2](https://user-images.githubusercontent.com/30406198/178398290-0bc1bb21-58cd-4320-b394-e49709438df7.jpg)
![3](https://user-images.githubusercontent.com/30406198/178398332-0e9d5deb-4578-4b2f-8ad4-5c0a669a869b.jpg)
![4](https://user-images.githubusercontent.com/30406198/178398463-d67815c6-38a0-4bcb-b7ad-862679aa9934.jpg)

**Comment by KomachiSion** [comment]
duplicate with #4336

**Comment by ImproveSalaryProgrammer** [comment]
与4336不是一个问题，4336是windows操作系统缺少vc++2015的dll依赖文件，该问题是在国产数据库，启动nacos过程中，生成了对应的so文件在tmp目录下，在启动映射过程中，无法获取到so文件，导致nacos启动失败。
