### ISSUE TITLE
无法删除 server 实例

### ISSUE THREAD

**Issue by mingtiao13** [alibaba/nacos#8736]
nacos 版本 2.1.0
问题 ：
我在本地通过docker-compose 启动了 nacos 服务 然后启动了一个spring-alibaba-naocs 并成功注册到 nacos服务中
我在浏览 java jdk时看见了可以删除实例的 demo 但是我在本地尝试的时候 一直不能删除

我本地的服务
![image](https://user-images.githubusercontent.com/57620412/178465794-b5369876-70ad-46f7-a607-fbd2120cd413.png)

![image](https://user-images.githubusercontent.com/57620412/178465999-09ea6723-fbe6-4d72-92d6-e6899e952cdc.png)

调用的demo
![image](https://user-images.githubusercontent.com/57620412/178465916-ac3ebe44-e471-42ea-9f3e-b80f3da4b4d8.png)

jdk 中的request
![image](https://user-images.githubusercontent.com/57620412/178466443-8c238deb-ca6f-4056-8e9e-1eb00f8f82c7.png)

response
![image](https://user-images.githubusercontent.com/57620412/178466520-f62b4f65-f6a9-4154-94c1-1f64548acd17.png)

通过curl
![image](https://user-images.githubusercontent.com/57620412/178468400-0fb4cd14-2457-48fc-b4e5-df5df0cbc0b1.png)

我尝试了以上两种方式 最后的结果
![image](https://user-images.githubusercontent.com/57620412/178468535-f088f467-e34d-48d8-8254-458acc4bc2fc.png)

我现在不明白为什么

**Comment by realJackSun** [comment]
I think the heartbeats are sent continually, so the deletion cannot be done

**Comment by mingtiao13** [comment]
> I think the heartbeats are sent continually, so the deletion cannot be done
It's not like that ，when I click downline on nacos-web, the service is offline.

**Comment by KomachiSion** [comment]
肯定删不掉啊， A节点注册了服务，B节点来删除？ 这本身就是非法的。 A节点其实还存活着，即使删除掉了也会自动续约回来。想要移除掉需要A节点来注销，或者A节点实际移除，不再维持连接或者心跳。

如果都可以随意任意删除，那别人把你的服务删了怎么办。

**Comment by mingtiao13** [comment]
你说的有问题啊
  
1.既然不能删除 为什么要返回  "ok" ？
2.还有 不能删除其它的 ip 服务 sdk 中传参里的 ip + port 是做什么用的？
3.在naocs-web 中删除 不是也 B del A 么  

另外你说的 ”随意任意删除，那别人把你的服务删了怎么办“ 这个问题 
如果nacos 的密码被别人知道了  通过 代码删除 或者通过 nacos-web 点击删除 有什么不同么
 （通过 accesskey 能不能 我不太清楚）
  
其实我想做的 很简单 对于nacos 这个服务 我其实有个小的需求 因为在开发环境中 难免有些人直接把代码down 下来直接就跑 随后他本地的服务就会注册到别的nacos 上   导致一些别人看不懂的bug  当然这个跟项目中的开发规范有很大的关系  这个我承认

我一开始想增加一些权限的配置 大概的意思就是个别的命名空间只允许某些 ip 注册 可是 nacos 中并不存在这样的功能
只能是另找别的办法 当然这个方法找到了 大概是模拟 ncaos-web 中的 下线操作 这是不是传说中的后门 ？

![image](https://user-images.githubusercontent.com/57620412/178906311-c385989d-1932-4d08-b34b-45dc9a1f540e.png)

**Comment by KomachiSion** [comment]
1.  返回ok是说操作没有报错，请求被受理，不代表能真的删除。当然如果能提示不允许删除可能是更好的方式，但是这里其实又分为两类服务， 持久化服务是由控制台来进行增删的，是可以删除的，非持久化实例是由应用程序注册的，所以只能由应用程序自己删除。

2. 用于定位要删除的实例啊。

3. web中添加的B是持久化实例，这种类似dns的服务数据本身就是有控制台进行管理的，没有应用归属，自然本身就是通过控制台删除。

感觉你对nacos的概念和原理不是很了解。可以去看一下nacos的电子书理解一下。

**Comment by fengcharles** [comment]
> 
我2.0.3版本 也遇到同样的问题 调用openAPI 删除不了实例。 但是控制台确可以。 都是服务自动注册的实例
