### ISSUE TITLE
query config

### ISSUE THREAD

**Issue by BeautifulMary** [alibaba/nacos#8738]
GROUP Fuzzy query configuration result. The export query interface is empty

**Comment by KomachiSion** [comment]
Please change your issue title and describe your problem more detail, I can't get your problem from your current description.

**Comment by BeautifulMary** [comment]
Configuration management configuration list query in console UI, click export query result according to group fuzzy query result, file data is empty

**Comment by KomachiSion** [comment]
Which version？I think you should use issue template to describe your issue.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
