### ISSUE TITLE
心跳任务会未捕获Error级异常 ，出现异常后未打印任何异常信息。

### ISSUE THREAD

**Issue by Xieyuhang1992** [alibaba/nacos#8741]
### 因为版本兼容问题，心跳定时任务执行任务时出现 NoClassDefFoundError 异常后未捕获导致心跳定时任务结束。无法给服务续约，且未输出任何相关日志信息。
![image](https://user-images.githubusercontent.com/30109803/178893465-d0b36c8b-c748-423e-86be-eeb909e46eb8.png)

**Comment by Xieyuhang1992** [comment]
nacos版本 1.2.1 。 是否可使用  com.alibaba.nacos.client.naming.beat.BeatReactor#executorService 线程池时重写线程池方法 
 afterExecute 。捕获异常并让提示更加友好。

**Comment by KomachiSion** [comment]
请尝试使用新客户端版本，如1.4.2/1.4.3.
