### ISSUE TITLE
nacos mcp-over-xds ，while i update service instance weight,i found id successed， but i did work in istio's ServiceEntery

### ISSUE THREAD

**Issue by yichouchou** [alibaba/nacos#8742]
about istio mcp-over-xds ，while i update service instance weight,i found id successed， but i did work in istio's ServiceEntery
我在尝试使用istio + nacos 的 mcp-over-xds，当我修改服务的权重时，它成功了，但是在istiod 中，权重未发生变更。（仍然为默认的1）, 尝试了多次 确定未发生变更。
version
nacos@latest
istio:  1.14.1

**Comment by yichouchou** [comment]
not only weight,i found that labels can not Synchronize update to ServiceEntery
我测试后发现，不只是权重，从nacos控制面板更改实例的label，也是无法同步至ServiceEntery。

**Comment by SpecialYang** [comment]
Can you show some istiod logs?

**Comment by yichouchou** [comment]
> Can you show some istiod logs?

while i change the weight and labels,no logs append in istiod or nacos istio-main.log；
then i change service-provider deploy  replicas: 3>4, then i get serviceentry by "curl 127.0.0.1:8080/debug/configz" in istiod;
i found it works, weight and labels changed。

**Comment by SpecialYang** [comment]
> > Can you show some istiod logs?
> 
> while i change the weight and labels,no logs append in istiod or nacos istio-main.log； then i change service-provider deploy replicas: 3>4, then i get serviceentry by "curl 127.0.0.1:8080/debug/configz" in istiod; i found it works, weight and labels changed。

Please use the latest version of nacos to verify again.

**Comment by mark8s** [comment]
@yichouchou 你用的2.1.1?
