### ISSUE TITLE
能否在注册服务的时候自动创建命名空间？

### ISSUE THREAD

**Issue by ppshinebl** [alibaba/nacos#8743]
目前服务端配置不能修改默认的命名空间，能否在服务注册的时候自动创建命名空间？

**Comment by onewe** [comment]
手动新建一个名称命名空间不行嘛? 还是说有什么特殊场景?

**Comment by chenhao26-nineteen** [comment]
> 

指的是在服务注册的时候，指定了一个不存在的命名空间 虽然现实已经注册上去 但是因为这个命名空间不存在，所以在控制台看不到？我觉得这个问题还和权限有关，创建命名空间涉及到一个授权的问题，可能不自动创建也有这方面的考量？

**Comment by ppshinebl** [comment]
> 手动新建一个名称命名空间不行嘛? 还是说有什么特殊场景?

部署比较麻烦，自动化部署还得单独改下sql或者curl登录创建

**Comment by ppshinebl** [comment]
> > 
> 
> 指的是在服务注册的时候，指定了一个不存在的命名空间 虽然现实已经注册上去 但是因为这个命名空间不存在，所以在控制台看不到？我觉得这个问题还和权限有关，创建命名空间涉及到一个授权的问题，可能不自动创建也有这方面的考量？

搞个超级账户或者默认授权？

**Comment by KomachiSion** [comment]
不能，无论从管控还是从合理性上， 命名空间都是顶层存在，命名空间下的资源不能反过来创建命名空间。

我理解这个属于特殊定制需求，非通用需求，可以自己修改代码实现一下。

我理解管理员应该更希望由他们来创建命名空间，而不是让程序自己来。
