### ISSUE TITLE
Bug: nacos/v1/ns/operator/switches接口失效

### ISSUE THREAD

**Issue by whl12345** [alibaba/nacos#8745]
2.1.0开源版本
nacos.core.support.upgrade.from.1x=false
当application配置文件这个开关关闭了，下面这个接口就没法动态改开关了，无法生效
PUT http://xxx:8848/nacos/v1/ns/operator/switches?entry=pushEnabled&value=false
接口返回ok
但是GET http://xxx:8848/nacos/v1/ns/operator/switches
pushEnabled=true

**Comment by whl12345** [comment]
@GetMapping("/switches")
    public SwitchDomain switches(HttpServletRequest request) {
        if (EnvUtil.isSupportUpgradeFrom1X()) {
            return switchDomain;
        }
        SwitchDomain result = new SwitchDomain();
        result.update(result);
        result.setDoubleWriteEnabled(false);
        return result;
    }

这里get为啥要重新New对象，这样开关不是都成默认值了？

**Comment by YunWZ** [comment]
@KomachiSion `SwitchDomain result = new SwitchDomain();`这部分代码看起来好像没有做任何事情：update()方法是空的且result.update(result)让人感到困惑。

**Comment by KomachiSion** [comment]
Fixed by #8636
