### ISSUE TITLE
Disable UDP port on v2

### ISSUE THREAD

**Issue by doufum** [alibaba/nacos#8747]
我方的服务器端和客户端都已经升级到了 v2.10，但是还是会有随机的 UDP 端口创建，之前我看文档，v2.x 应该是不需要 UDP 端口了。
那么，v2.x 可以屏蔽创建这个 UDP 端口么？

如果不能屏蔽，这个 UDP 的端口生成的范围是什么？可以指定么？

-----
Our server side and client side have been upgraded to V2.10, but there will still be random UDP port creation, 
I saw the document before, V2 should not need UDP port.

Can v2.x disable the creation of this UDP port ?
If cannot, what is the range of UDP port ? 
Can I specify it?

**Comment by KomachiSion** [comment]
计划在2.2版本彻底移除。

**Comment by KomachiSion** [comment]
目前运行生成逻辑和v1版本一致，仅做了重构将其作为Deprecated

**Comment by zhanghan2585** [comment]
> 目前运行生成逻辑和v1版本一致，仅做了重构将其作为Deprecated

在这里正好请问下，客户端UDP的IP 是否可以支持设置呢？ 目前来看 取的是0.0.0.0 系统将会自动选择跃点数 来决定使用哪个IP来访问，实际的业务情况 这样的IP很可能和服务端就是不通的

**Comment by springcloudconf** [comment]
别再给我发信息了，球球了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 晚上6:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] Disable UDP port on v2 (Issue #8747)





  
目前运行生成逻辑和v1版本一致，仅做了重构将其作为Deprecated
  
在这里正好请问下，客户端UDP的IP 是否可以支持设置呢？ 目前来看 取的是0.0.0.0 系统将会自动选择跃点数 来决定使用哪个IP来访问，实际的业务情况 这样的IP很可能和服务端就是不通的

**Comment by doufum** [comment]
@KomachiSion 请问一下，我们已经将 nacos 的版本升级到v2.2.1了，但是还是可以扫描出 udp 的端口创建。请问一下，这个 upd 端口创建的删除，是要在哪个版本取消？
![图片](https://github.com/alibaba/nacos/assets/6191406/e2cf9610-a419-47c7-a213-01f7ce511d63)
