### ISSUE TITLE
nacos ks8例子中的mysql镜像过时导致nacos client报错publish nacos metadata failed 

### ISSUE THREAD

**Issue by lossend** [alibaba/nacos#8750]
背景:
搭建k8s+nacos+dubbo，参考文档https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html

按照上面文档部署nacos到k8s的时候，dubbo-nacos 3.0.9客户端链接的时候报如下错误：
 Failed to put org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@2ad49f99 to nacos {"annotations":[],"canonicalName":"com.mayfair.infra.spore.api.HelloService","codeSource":"jar:file:/var/www/app/spore-starter-1.0.0-SNAPSHOT.jar!/BOOT-INF/lib/spore-api-1.0.0-SNAPSHOT.jar!/","methods":[{"annotations":[],"name":"sayHello","parameterTypes":[],"parameters":[],"returnType":"java.lang.String"}],"parameters":{"release":"3.0.9","side":"provider","application":"spore","anyhost":"true","pid":"1","dubbo":"2.0.2","interface":"com.mayfair.infra.spore.api.HelloService","version":"1.0.0","bind.ip":"172.31.40.100","methods":"sayHello","background":"false","deprecated":"false","dynamic":"true","service-name-mapping":"true","qos.enable":"false","generic":"false","bind.port":"20880","revision":"1.0.0","timestamp":"1657852730032"},"types":[{"enums":[],"items":[],"properties":{},"type":"java.lang.String"}],"uniqueId":"com.mayfair.infra.spore.api.HelloService@jar:file:/var/www/app/spore-starter-1.0.0-SNAPSHOT.jar!/BOOT-INF/lib/spore-api-1.0.0-SNAPSHOT.jar!/"},

到客户端日志上排查后看到config.log日志里出现：
[DubboSaveMetadataReport-thread-1:c.a.n.c.c.i.ClientWorker] [fixed-nacos-headless.default.svc.cluster.local_8848] [publish-single] fail, dataId=com.mayfair.infra.spore.api.HelloService:1.0.0::provider:spore, group=dubbo, tenant=, code=500, msg=PreparedStatementCallback; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'encrypted_data_key' in 'field list'

检查mysql的config_info表的时候确实少了一个字段，通过增加encrypted_data_key后，错误消失，分析为啥少了字段encrypted_data_key

看了下nacos k8中mysql-nacos镜像中对db的初始化配置文件docker-entrypoint-initdb.d/nacos-mysql.sql，发现初始化db表少了encrypted_data_key，跟最新nacos 2.1.0 逻辑不一致,下面是

```sql
CREATE TABLE `config_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) DEFAULT NULL,
  `content` longtext NOT NULL COMMENT 'content',
  `md5` varchar(32) DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `src_user` text COMMENT 'source user',
  `src_ip` varchar(20) DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) DEFAULT NULL,
  `tenant_id` varchar(128) DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) DEFAULT NULL,
  `c_use` varchar(64) DEFAULT NULL,
  `effect` varchar(64) DEFAULT NULL,
  `type` varchar(64) DEFAULT NULL,
  `c_schema` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_configinfo_datagrouptenant` (`data_id`,`group_id`,`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='config_info';

```

**Comment by cantevenl** [comment]
encrypted_data_key 这个字段是什么用的？ 我从2.0.3升级到2.1.0也发现这个错误

**Comment by KomachiSion** [comment]
是2.1.0的镜像中的sql文件少了这个字段吗？

**Comment by cantevenl** [comment]
> 是2.1.0的这个镜像中的sql文件少了么？

把字段加进去就行了 
ALTER TABLE config_info ADD encrypted_data_key TEXT NOT NULL COMMENT '秘钥';
ALTER TABLE config_info_beta ADD encrypted_data_key TEXT NOT NULL COMMENT '秘钥';
ALTER TABLE his_config_info ADD encrypted_data_key TEXT NOT NULL COMMENT '秘钥';

**Comment by li-xiao-shuang** [comment]
> encrypted_data_key 这个字段是什么用的？ 我从2.0.3升级到2.1.0也发现这个错误

配置加解密使用的
