### ISSUE TITLE
Can `BeatReactor` change to communicate by gRPC instead of HTTP? 

### ISSUE THREAD

**Issue by ZhangShenao** [alibaba/nacos#8751]
I realized that `BeatReactor` communicates with nacos server within http? Can that change to gRPC? If not, what's the reason? Thanks very much~

**Comment by onewe** [comment]
Which version?

**Comment by ZhangShenao** [comment]
> 

Yes, the latest version.

**Comment by KomachiSion** [comment]
No, if client can use grpc, why not directly use grpc to register and save instance but use grpc to do beats? only http need do beats to server. So `change to communicate by gRPC instead of HTTP` is no reasonable.

**Comment by ZhangShenao** [comment]
OK. Thanks for answering!
