### ISSUE TITLE
Improve the documentation of encryption plug-ins

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#8754]
## Issue Description

插件实现是通过java.util.ServiceLoader#load(java.lang.Class<S>)实现，这钟方式需要到配置文件里面新增具体的实现类，但是我在文档中没有看到体现。

https://nacos.io/zh-cn/docs/config-encryption.html

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/179654966-2ea8bba2-bad4-4f03-9d60-82650dd8df79.png)
有提出是需要使用SPI的， SPI需要自行搜索学习。
