### ISSUE TITLE
官网介绍错误

### ISSUE THREAD

**Issue by shining-stars-lk** [alibaba/nacos#8758]
**官网介绍描述错误**
官网菜单
nacos2.0 
 升级文档 
  启动服务器
![image](https://user-images.githubusercontent.com/40255310/179436789-b2d152f1-91d7-49dc-9300-2935ea7f2fda.png)
这部分描述使用内嵌数据库模式下，单机和集群的启动命令一摸一样 。是不是错误了

**Comment by KomachiSion** [comment]
嗯，少了一个-m standalone

**Comment by li-xiao-shuang** [comment]
> **官网介绍描述错误** 官网菜单 nacos2.0 升级文档 启动服务器 ![image](https://user-images.githubusercontent.com/40255310/179436789-b2d152f1-91d7-49dc-9300-2935ea7f2fda.png) 这部分描述使用内嵌数据库模式下，单机和集群的启动命令一摸一样 。是不是错误了

欢迎提 pr 补充下

**Comment by stone-98** [comment]
@i will solve@
