### ISSUE TITLE
spring-cloud-starter-alibaba-nacos-discovery

### ISSUE THREAD

**Issue by rola0411** [alibaba/nacos#8760]
这个依赖怎么没人维护了吗？好久没更新了。想用最新版nacos但是还是想等alibaba-cloud更新。但是一直等不到，麻烦有内部消息告诉一下，是不是alibaba cloud团队被裁了，没人干了。

**Comment by KomachiSion** [comment]
请到spring cloud alibaba 社区提issue询问。

**Comment by KomachiSion** [comment]
据我所知，SCA社区也挺活跃的， 你看下是不是你的坐标不对， SCA分毕业前和毕业后，maven的坐标是不同的。

**Comment by wuchubuzai2018** [comment]
> 这个依赖怎么没人维护了吗？好久没更新了。想用最新版nacos但是还是想等alibaba-cloud更新。但是一直等不到，麻烦有内部消息告诉一下，是不是alibaba cloud团队被裁了，没人干了。

可以自己的项目中指定Nacos的版本就行了呀，
 <spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>
        <spring-boot.version>2.5.5</spring-boot.version>
        <alibaba.nacos.version>2.1.0</alibaba.nacos.version>
