### ISSUE TITLE
sdk client use identity key not ok, dont use username and password

### ISSUE THREAD

**Issue by tonglin96** [alibaba/nacos#8762]
**Describe the bug**
dont use username and password to get config, set header for identity key and value, but rerturn 500 errocode

**Expected behavior**
get config ok

**Actually behavior**
rerturn 500 errocode

**How to Reproduce**
for example: nacos.core.auth.server.identity.key=serverIdentity, nacos.core.auth.server.identity.value=security
1. set metadata for "serverIdentity"="security"
2. get config

**Desktop (please complete the following information):**

 - OS: mac
 - Version:  nacos-server 2.1.0, nacos-client 2.0.3
 - Module: config
 - SDK : golang

**Comment by KomachiSion** [comment]
I think you don't understand identity.key. Please see document again and has more understand for it.

**Comment by KomachiSion** [comment]
It used by server to make server communicate without auth, not for client to server.
