### ISSUE TITLE
有鉴权插件开发demo吗

### ISSUE THREAD

**Issue by tonglin96** [alibaba/nacos#8764]
有鉴权插件开发demo吗

**Comment by KomachiSion** [comment]
nacos提供的默认实现应该就算是一种demo了吧。了解一下SPI之后应该很容易实现。

**Comment by YunWZ** [comment]
参考默认实现是很好的一种方式；

。。。或者你也可以参考我的这个[开源项目](https://github.com/YunWZ/nacos-examples/blob/main/docs/src/main/asciidoc/AuthPlugin.adoc)，有文章介绍和示例代码。
