### ISSUE TITLE
关于不同命名空间下利用openfeign进行服务间通信

### ISSUE THREAD

**Issue by 15637942788** [alibaba/nacos#8766]
目前了解到的, 各个微服务通信需要注册到同一个命名空间下才行.
但是就配置而言, 我想的是不同的服务, 配置在各自所属的命名空间下, 但是这样的话, 各个微服务间的通信就不行了.
能不能有个配置来支持不同的命名空间下的服务可以通信.

**Comment by KomachiSion** [comment]
命名空间为强隔离属性， 不同命名空间不可互通。 如果您一定要进行多命名空间的互通， 需要自行开发，在程序中创建多个NacosConfigService， 每个对应一个命名空间，然后各自获取对应的配置。

**Comment by 15637942788** [comment]
> 命名空间为强隔离属性， 不同命名空间不可互通。 如果您一定要进行多命名空间的互通， 需要自行开发，在程序中创建多个NacosConfigService， 每个对应一个命名空间，然后各自获取对应的配置。

现在命名空间给我一种疑惑, 就是我注册可以在同一个命名空间下,但是我的配置是想分开管理的, 各个微服务是各自的配置,但是在 nacos 前端界面, 就会有个问题, 用于注册使用的命名空间和配置的命名空间都会在配置界面, 看着很混乱, 而又不想把不同的微服务的配置都扔在一起, 感觉上也是混乱的.

**Comment by KomachiSion** [comment]
命名空间就是个隔离资源的属性，配置中心和注册中心也可以使用不一样的命名空间，但是设置了配置的client为某个命名空间之后，这个client就只能访问这个命名空间了， 服务发现也一样。
