### ISSUE TITLE
Naocs 秒级下线

### ISSUE THREAD

**Issue by zhanghan2585** [alibaba/nacos#8772]
gateway 使用 nacos 做注册中心，通过openApi删除实例后，gateway 依然往已经删除了的实例上发消息， watchDelay ，heartBeatInterval，heartBeatTimeout 均已配置无效，请问有解决方法吗？ 达到秒级就可以

**Comment by lpaz010** [comment]
@zhanghan2585 现在用的什么版本？用2.x（推荐最新）版本长连接，可以达到秒级下线通知。

**Comment by zhanghan2585** [comment]
是最近版本 有相关文档吗？

**Comment by zhanghan2585** [comment]
> @zhanghan2585 现在用的什么版本？用2.x（推荐最新）版本长连接，可以达到秒级下线通知。

是最新版本 有相关文档吗？

**Comment by zhanghan2585** [comment]
defaultPushCacheMillis 最终的问题回到了这里，这个10s Nacos 服务端限制了最小值，难道就没有解决办法了吗？
![image](https://user-images.githubusercontent.com/18066720/179941502-b9cb26ef-ec3a-45ba-859a-caec9bdc162e.png)
结合 #3659 bug

**Comment by KomachiSion** [comment]
这和gateway的逻辑有关，如果是订阅的方式，1.x有udp，2.x有grpc推送，正常情况下都能达到秒级。

这个10s查询属于异常情况下的对账逻辑，因为udp无法保证送达。需要保证最终能够生效。

因此并非bug，可能需要看下你gateway的实现方式，以及你的环境是否禁止了udp推送。或者grpc类是否存在冲突导致服务端下推的数据无法被处理。

**Comment by zhanghan2585** [comment]
> 这和gateway的逻辑有关，如果是订阅的方式，1.x有udp，2.x有grpc推送，正常情况下都能达到秒级。
> 
> 这个10s查询属于异常情况下的对账逻辑，因为udp无法保证送达。需要保证最终能够生效。
> 
> 因此并非bug，可能需要看下你gateway的实现方式，以及你的环境是否禁止了udp推送。或者grpc类是否存在冲突导致服务端下推的数据无法被处理。

我调试发现 gateway 通过 ZoneAwareLoadBalancer  chooseServer 最终走到NacosRule selectInstances ，这个select 会有serviceInfoMap缓存，目前就是怎么能做到服务下线或者实例删除了能立马更新到这个缓存，不知道你说的udp 推送是哪一层的

**Comment by zhanghan2585** [comment]
总结如下 @lpaz010 所说的长链接 udp 是有效果的 @KomachiSion 确实是udp推送的问题，应该和Linux 防火墙有关系，本机装了Nacos 验证是通过的,在gateway chooseServer 达到秒级的时候  Naocs 本身的服务上下线通过udp 确实可以快速响应，10s的查询只是给udp【机制问题不保证成功】 兜底的.
udp接收消息代码如下
![image](https://user-images.githubusercontent.com/18066720/180170817-03593991-7c23-450f-a56e-77165ef75489.png)

**Comment by qinghuozhang** [comment]
@zhanghan2585 你好，请问你做到秒级下线了吗，gateway要做什么配置吗
