### ISSUE TITLE
gprc demo

### ISSUE THREAD

**Issue by kqbi** [alibaba/nacos#8776]
Hi Team,

请问有golang或者c++语言的通过grpc对接nacos的demo吗？
然后
client/target/classes/com/alibaba/nacos/client/naming/remote/gprc
client/src/main/java/com/alibaba/nacos/client/naming/remote/gprc
client/src/test/java/com/alibaba/nacos/client/naming/remote/gprc
这几个路径后边的单词拼写错误了

**Comment by KomachiSion** [comment]
golang有nacos-sdk，最新版本已经对接完成了
c++有c#和c++ 的sdk， 新版本应该也对接完成了

在nacos-group下，都可以试用下。

包名拼错了，后续版本会修正。

**Comment by kqbi** [comment]
C++版nacos-sdk-cpp的grpc在哪边，master中没看到，然后有个grpc_version,里边没啥东西

**Comment by kqbi** [comment]
@KomachiSion

**Comment by KomachiSion** [comment]
详细读读代码吧， c++ sdk也是社区贡献的， 我也不熟悉。只知道已经有同学对接过了。

**Comment by kqbi** [comment]
就是看过代码我才说没有的

**Comment by kqbi** [comment]
有人对接过，估计源码没贡献吧，我自己看看吧
