### ISSUE TITLE
普通用户无法登录

### ISSUE THREAD

**Issue by renjiangyang** [alibaba/nacos#8778]
**Describe the bug**
创建普通用户后,无法登录,提示如下:

权限认证失败
没有 public 命名空间的访问权限！

**Expected behavior**
用户名密码正确应该跳转主页,无public命名空间,不展示该标签即可

**Actually behavior**
目前无法登录了
![image](https://user-images.githubusercontent.com/32317608/180120313-9ca17235-8eed-4ffe-b3c5-cd8dcebebb3e.png)

**Comment by onewe** [comment]
该问题在 dev 分支已经修复了 等后续发布版本

**Comment by onewe** [comment]
see https://github.com/alibaba/nacos/pull/8419 and https://github.com/alibaba/nacos/issues/8417
