### ISSUE TITLE
启动应用时，无法注册本应用，但是通过url直接注册就可以

### ISSUE THREAD

**Issue by wushuaiping** [alibaba/nacos#8788]
**Describe the bug**
启动报错如下：
![image](https://user-images.githubusercontent.com/26813459/180416030-9d7391ee-26a5-480d-9d55-9e1a112fa186.png)

于是通过手动注册：
![image](https://user-images.githubusercontent.com/26813459/180416136-e4068a72-54de-4cc0-a744-8449b5772058.png)

注册成功：

![image](https://user-images.githubusercontent.com/26813459/180416216-32e20438-383d-4d6d-889a-e6933442c09e.png)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version all version is 2.1.0
 - Module [e.g. naming/config]
 - SDK spring-cloud-alibaba-nacos

**Additional context**

**Comment by YunWZ** [comment]
connectoin refused，ip=10.0.10.192，port=9015，确认你的应用（所处的网络）能够访问nacos服务端。

**Comment by wushuaiping** [comment]
> connectoin refused，ip=10.0.10.192，port=9015，确认你的应用（所处的网络）能够访问nacos服务端。

看我的第二张截图，我在该服务器上通过curl命令去注册是能注册成功的

**Comment by YunWZ** [comment]
> > connectoin refused，ip=10.0.10.192，port=9015，确认你的应用（所处的网络）能够访问nacos服务端。
> 
> 看我的第二张截图，我在该服务器上通过curl命令去注册是能注册成功的

嗯。看你发的另一个PR  #8779 ，监听的http协议（80端口）会返回重定向响应，不知道是否和这个有关，试一下将http请求直接转发给nacos呢？

**Comment by wushuaiping** [comment]
> > > connectoin refused，ip=10.0.10.192，port=9015，确认你的应用（所处的网络）能够访问nacos服务端。
> > 
> > 
> > 看我的第二张截图，我在该服务器上通过curl命令去注册是能注册成功的
> 
> 嗯。看你发的另一个issue #8779 ，监听的http协议（80端口）会返回重定向响应，不知道是否和这个有关，试一下将http请求直接转发给nacos呢？

我目前有几个微服务，其中gateway部署了两台，是能注册成功的，但是其他微服务就无法注册成功。
![image](https://user-images.githubusercontent.com/26813459/180584515-feca1fa9-397e-48e4-bb5b-3afaf621bf27.png)

Nginx配置
![image](https://user-images.githubusercontent.com/26813459/180584368-1fe72941-6aaf-4f67-891a-0e2c945a2652.png)
![image](https://user-images.githubusercontent.com/26813459/180584383-ee2f270f-09c8-406d-9f92-c302ed5d02e7.png)

每台应用服务器绑定hosts
![image](https://user-images.githubusercontent.com/26813459/180584437-18eef97d-63e8-4ded-bb9e-e810750fc847.png)

**Comment by wuchubuzai2018** [comment]
根据你的错误提示，我看了这个Nacos中的NameProxy的源代码，可以知道，他会判断你的服务名称是否包含端口，不包含的话，会获取一个port，所以个人认为你的问题应该是springboot的yml文件中，把80端口也加上，即服务地址写上：
nacos-register.com:80

`
public static String reqApi(String api, Map<String, String> params, String curServer) throws Exception {
        try {
            List<String> headers = Arrays.asList(HttpHeaderConsts.CLIENT_VERSION_HEADER, VersionUtils.version,
                    HttpHeaderConsts.USER_AGENT_HEADER, UtilsAndCommons.SERVER_VERSION, "Accept-Encoding",
                    "gzip,deflate,sdch", "Connection", "Keep-Alive", "Content-Encoding", "gzip");
            
            RestResult<String> result;
            
            if (!InternetAddressUtil.containsPort(curServer)) {
                curServer = curServer + InternetAddressUtil.IP_PORT_SPLITER + EnvUtil.getPort();
            }
            
            result = HttpClient.httpGet(HTTP_PREFIX + curServer + api, headers, params);
            
            if (result.ok()) {
                return result.getData();
            }
            
            if (HttpURLConnection.HTTP_NOT_MODIFIED == result.getCode()) {
                return StringUtils.EMPTY;
            }
            
            throw new IOException(
                    "failed to req API:" + HTTP_PREFIX + curServer + api + ". code:" + result.getCode() + " msg: "
                            + result.getMessage());
        } catch (Exception e) {
            Loggers.SRV_LOG.warn("NamingProxy", e);
        }
        return StringUtils.EMPTY;
    }


`

**Comment by KomachiSion** [comment]
不显示指定端口， 默认指定端口应该是8848。 可能是这个原因。试一下监听8848端口或者手动指定80

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
