### ISSUE TITLE
Propasal about Nacos supports abilities negotiation capability #8458

### ISSUE THREAD

**Issue by Daydreamer-ia** [alibaba/nacos#8789]
# Tittle

关于  `Nacos` 支持能力协商的想法，这是关于 #8458 的提案。
导师： @xuechaos 

​	各位老师，还有社区其他师兄师姐们好，我叫陈亿钦，是 `ASOC` 的一名参与者，我参与的课题是 `Nacos` 能力协商机制的实现。以下是我的想法和设计实现，但不知道目前在实现上是否还存在问题或者有其他被我遗留的地方，又或者有哪些场景使用我目前的设计无法覆盖，如果存在的话，恳请您能够指出来并在评论区给我留言，谢谢。

# Background

​	随着 `Nacos` 社区变得更加活跃，能力变得更加多样化，不同版本对新能力的支持程度将大不相同。

​	目前，许多能力都是根据版本号来判断的，可读性、可维护性和可扩展性都不太方便。因此，我尝试设计一种能力协商机制来协调和聚合 `Nacos` 客户端和服务器之间以及服务器和服务器之间支持的能力。

# How Nacos interacts at present

​	为了更好描述提案，接下来，我会给您讲述一遍 `Nacos2.X` 是如何建立和维护连接的。

​	`Nacos2.x` 开始基于grpc模式在节点之间进行交互，并取得了巨大的性能改进。完成节点间交互的主要组件是**ConnectionManager**、**Grpcbistreamrequestacceptor**、**RpcClient**和**用于处理请求和响应的Handler**。然后，我将基于这些组件做一下流程描述。
![原本的设计](https://user-images.githubusercontent.com/83362909/180590990-e8d6e26d-0948-43fc-a9f8-a9eba60cd9ba.png)
- `RpcClient` 是用于连接服务器或客户端的基类定义，它将通过 `ServerListFactory` 获取远程地址。在使用 `RpcClient` 之前，需要调用 `start()`，然后它将尝试连接到远程服务器，特定逻辑 `connectToServer(ServerInfo info)` 委托给子类实现。当前的实现是 `GrpcClient`。
- `GrpcClient::connectToServer(ServerInfo info)` 将通过 `ConnectionSetupRequest` 向服务器发送关于当前节点的一些基本消息。
- 服务端中的 `Grpcbistreamrequestacceptor` 将会接收到 `ConnectionSetupRequest`，然后传递给 `ConnectionManager`，之后通过 `register(connectionid, con)` 完成连接注册。
- `ConnectionManager` 将通知所有对连接事件感兴趣的 `ClientConnectionEventListener`，当连接断开时，它也会收到通知。同样的行为也发生在 `RpcClient` 中。
- `RpcClient` 支持用于处理来自服务器的请求的 `ServerRequestHandler`，这也是心跳感知的原理，更多的内容请查阅 `RpcClient` 。

# Proposal

## How to discover ability

- `Nacos 2.x` 支持长连接，因此当通过 `RpcClient::connectToServer(ServerInfo)` 建立连接时，当前节点的能力可以在 `ConnectionSetupRequest` 中一起携带向服务端；
- 因此，服务器可以在注册 `Connection` 时接收到从客户端的能力，然后服务器向该客户端发送 `ServerAbilitySynRequest`，告诉客户端服务端支持什么，然后客户端将发现服务器的能力；

- 一个节点的能力集合作为一个 `AbilityTable` 实例，它以 `byte[]` 的形式表现，每个标志位代表一种能力，`0` 表示关闭，`1` 表示打开；

- 当当前节点从其他节点接收到 `AbilityTable` 时，它不会立即将 `AbilityTable` 添加到当前节点，而是将其传递给 `AbilityPreProcessor` 进行预处理，并且在处理完成之前不会添加到当前节点， `AbilityPreProcessor` 是一个接口定义，用于支持未来可能的场景。例如，如果场景需要，当前节点认为所有客户端都不支持或支持某个功能，则可以实现此接口来预处理到来的 `AbilityTable`；

- 预处理的延迟取决于未来的 `AbilityPreProcessor` 实现，目前它什么都不做；

### Problem and solutions

- 如何保存和维护来自从其他节点（可能是服务器或客户端）能力表？
- 如何确保在 `RpcClient` 发出服务请求的时候已经获得 `AbilityTable`？
- 如何使用当前节点拥有的 `AbilityTable`？

### How to ensure obtained before `RpcClient` makes a service request

> 回顾

`RpcClient` 在使用之前将调用 `start()` 连接到服务器，这是一个同步操作。当连接失败时，它将调用 `switchServerAsync()` 以异步方式进行连接。但是，在 `RpcClient` 的状态更改为 `RUNNING` 之前，它都不能用于发送服务请求。

> 设计

要解决此问题，只需区分以下能力表处于的三种情况：

- 当前节点是否接收到能力表；
- 是否正在进行预处理；
- 如果收到，是否完成预处理并加入当前节点；
  - 未完成预处理，无法加入当前节点；

为 `AbilityTable` 设定生命周期 (状态模型)：

- `NOT_EXISTED` ：当前节点不存在该能力表； 
- `INITIALING`：当前节点收到该能力表，但是此时正在进行被后置处理器进行后置处理； 
- `READY` ：当前能力表已经聚合进能力控制中心；
- `EXPIRED` ：连接断开，能力表过期，很快就被移除；
  - 在这一阶段，当前节点对该能力表的能力查询都会认为不支持；

所有状态都可以通过 `AbilityControlManager` 获取，即指定的 `AbilityTable` 的状态。当 `RpcClient` 尝试连接到服务器时，它也准备好接收 `AbilityTable`。

当 `RpcClient` 尝试三次获取 `AbilityTable` 的状态但通过 `AbilityControlManager` 追踪时仍为 `NOT_EXISTED` 时，它将选择重新连接并异步获取 `AbilityTable` 。

当 `RpcClient` 收到 `AbilityTable` 时， `AbilityControlManager` 会立即将 `AbilityTable` 的状态设置为 `INITIALING`。 `RpcClient` 将等待 `AbilityTable` 完成预处理并添加到当前节点。因此，不建议在 `nacos-client` 模块(客户端)上实现过于复杂的能力表预处理操作，虽然不建议复杂操作，但它支持预处理。

### How to save

所有 `AbilityTable` 实例将保存在 `AbilityControl Manager` 的 `Map<String，AbilityTable>` 字段的中，该字段的 `key` 为连接ID，值为 `AbilityTable` 实例。结合上述状态模型，处理如下：

> #### client
![Nacos-Client能力协商](https://user-images.githubusercontent.com/83362909/180591037-9bfbef4f-deca-4d93-a9f7-aa31a6979869.png)
基于上述状态模型，客户端的能力发现过程如下：

- 在 `RpcClient` 发送 `ConnectionSetupRequest` 并成功获取 `Connection` 实例后，让 `RpcClient` 尝试跟踪 `AbilityTable` 的状态三次。如果结果总是 `NOT_EXISTED`，则建立的 `Connection` 将被视为无效，并且不会被堵塞。继续按照原程序运行，然后调用 `switchserverasync` 以异步方式运行；
- 如果正常获得 `AbilityTable`（状态为 `INITIALING`），则表示客户端已收到 `AbilityTable`，并且正在预处理中，即当前节点已经收到能力表了，因此将继续跟踪 `AbilityTable` 的状态，并等待处理完成；
- 如果 `Connection` 中途断开，`AbilityTable` 将设置为 `EXPIRED` 。它不会等待并认为这次建立的连接无效，继续按原流程运行，然后调用 `switchserverasync()` 异步执行；

在向 `ConnectionManager` 成功注册连接后，它将尝试向该客户端发送 `ServerAbilitySynRequest`。客户端将通过 `ServerAbilityRequestHandler` 接收。为了尽快返回确认信息，采用以下方法：

- 在完成 `Connection` 的建立和注册后，服务端将 `AbilityTable` 移交给 `AbilityControlManager`，然后预处理并添加它。整个过程是异步的；
- 在 `ServerAbilityRequestHandler` 从服务器接收到 `AbilityTable` 后，客户端将 `AbilityTable` 的前置处理和添加作为任务，并直接将响应返回确认信息给服务器；

由于客户端和服务器都异步处理和添加能力表，因此如果正常，响应将很快。然而，为了确保客户端能够正常接收，如果服务器在合法时间内未能接收到响应，它将尝试发送两到三次，如果都失败的话，那就会重置客户端连接重新建立。

在客户端建立 `Connection` 并正常接收服务器的 `AbilityTable` 后，它会将 `RpcClient` 的状态设置为 `RUNNING`，以接收和处理服务请求。

> #### server
![Nacos-Server能力协商](https://user-images.githubusercontent.com/83362909/180591171-cff940f5-a59a-4caf-8b6d-f9e455120ca7.png)
- 我们已经知道 `ConnectionManager` 是维护 `Connection` 的容器。当连接到来时，它将由 `ConnectionManager` 注册，如果断开连接，`ConnectionManager` 将调用 `unregister(connectionId)`；
- `ClientConnectionEventListener`（它有两种方法：`clientConnected(Connection connect)` 和 `clientDisConnected(Connection-connect)`）是一个监听器，无论是连接还是断开都被调用；
- 因此，我尝试为 `AbilityTable` 添加一个新的监听器， `ClientConnectionEventListener::clientConnected(Connection-connect)` 用于从客户端添加能力表，`clientDisConnected(Connection-connect)` 用于删除其 `Connection` 已断开的能力表；

### How to maintain `AbilityControlManager`

​	客户端和服务器都有自己的策略来实现能力控制，例如，服务器需要维护集群节点的能力控制，而客户端不需要。因此，`AbilityControlManager` 将是一个抽象基类，具体实现下放到 `ClientAbilityControlManager` 和 `ServerAbilityControlManager`。

​	考虑到一些底层通用模块将使用 `AbilityControlManager`，但具体实现在更高的模块中，例如，`nacos common` 中的 `RpcClient` 将使用 `AbilityControlManager`。因此，我试图通过 `NacosServiceLoader` 和 `Java SPI` 来维护 `AbilityControlManager`。 `AbilityControlManager`由 `NacosAbilityManagerHolder` 维护为单个实例，暴露 `getInstance()` 静态方法，存在于 `nacos common` 模块中。
![NacosAbilityManager服务发现](https://user-images.githubusercontent.com/83362909/180591184-f6e27947-f2f6-4ffc-93c9-01835c9607cc.png)
一个合法客户端或服务端应具有相应的 `AbilityControlManager`。无论是客户端还是服务器，对于控制中心实例都由 `NacosAbilityManagerHolder.getInstance()` 获得 。

## What is new

基于以上的设计实现，`nacos` 能力控制将支持以下这些内容.

### Combine cluster ability

​	我们已经知道，如果在服务端的话，`RpcClient` 将在连接之前将当前节点的基本消息发送到服务器，然后服务端将其能力表发送到客户端 `nacos core` 中的是`ClusterRpcClientProxy` 通过 `GrpcClusterClient` 维护与其他服务器节点连接的实例，`GrpcClusterClient` 是 `RpcClient` 的子类实现。它可以用于获取其他服务器节点的 `AbilityTable`。

例如，以下是来自服务器节点的  `AbilityTable`：

- `server-01`：`1110 0001`
- `server-02`：`1100 0001`
- `server-03`：`1100 0001`
- `server-04`：`1110 1101`

然后，`AbilityControlManager` 可以将上述四张表进行与运算，合并为：`1100 0001`，这就是该集群的所有节点都可以支持的能力，实现集群节点能力的内聚 (即使有节点下线后仍然不影响该功能对外开放)。如果有需要判断集群节点是否都支持某个能力时，可以通过`ServerAbilityControlManager::isClusterEnable` 获得。

### Node ability

​	我们通过从客户端收集了能力表保存在 `AbilityControlManager` 中。那么我们很容易知道客户端是否支持某个功能。这也可以通过 `AbilityControlManager::isEnable` 获得，判断集群是否对外一致支持某个能力也是类似。

​	

### Register components interested in a ability

​	在启用/关闭**当前节点**的功能后，将调用实现 `HandlerMapping` 的某些组件，例如，通过 `AbilityControl Manager::enableCurrentNodeAbility` 将当前节点的 `AbilityTable` 的标志从 `0` 更改为 `1`，这意味着运行此功能，然后它将回调所有对该能力感兴趣的 `HandlerMapping`。

​	`HandlerMapping` 是一个监听器，它有一个接口方法：`trigger(boolean isEnable)` 。在运行或关闭当前节点的某个功能后，将调用它们。每个能力都有自己的 `HandlerMapping` 组件集。如果集群的能力发生变化，它们可能也会被触发。不过针对当前节点的能力注册的监听器与针对集群能力注册的监听器是两个单独的集合。

​	`AbilityControlManager` 可以将集群中服务器节点的所有功能结合起来，得到一致的 `AbilityTable`，如 `1100 0001`。然后，如果它对某种能力感兴趣，我们可以注册一些组件。当 `Nacos` 希望在所有服务器节点支持或其中一个不支持的情况下运行或关闭某些组件时，它可以将这些组件注册到 `AbilityControlManager`，并在集群的某个功能更改后调用它们。

> 例如

​	在 `PersistentConsistencyServiceDelegateImpl` 中，如果集群中的所有服务器节点都在 `1.4.0` 之后，则 `Nacos` 使用 `BasePersistentServiceProcessor`，否则就改为 `RaftConsistencyServiceImpl` 提供一致性服务。

​	我们可以将 `persistent` 设置为服务器的能力，如果服务器版本高于“1.4.0”，则将“raft”能力设置为禁用，如果服务器版本低于“1.4.0”，则将其设置为启用。然后，我们可以将 `PersistentConsistencyServiceDelegateImpl` 注册为 `HandlerMapping`，并实现方法来为集群动态选择某些持久一致性服务。当内聚服务器节点能力时，如果集群中的一个服务器节点不支持，或集群中的所有服务器节点都支持，则将调用该命令。

### Register pre-processor

​	`AbilityTable` 在加入当前节点之前将进行预处理。如果将来需要使用一些场景，可以使用 `AbilityControlManager::registerPreprocessor`进行注册。

# 最后

​	感谢你的阅读。以上是我对 `Nacos` 能力协商的 proposal。如果有哪些场景没有考虑到或者设计上存在问题，希望你能在评论区给我留言。我期待着收到你的宝贵建议，非常感谢！

# Tittle

Some ideas about Nacos supports abilities negotiation capability.

This is a proposal about #8458. 
My instructor： @xuechaos 

​	Hello, my name is Yiqin Chen, a participant of ASOC. The topic I participated in is the implementation of the ability negotiation mechanism of Nacos. Here are my proposal and implement of my idea. I wonder if there is any problem with my proposal. Please leave your valuable suggestions if I make a mistake.

# Background

​	As the Nacos community becomes more active and the abilities become more diverse, the degree of support for new abilities will vary greatly between different versions.

​	At present, many abilities are judged according to the version number, and the readability, maintainability and scalability are not so convenient. Therefore, I try to design a capability negotiation mechanism to coordinate and aggregate the supported capabilities between the Nacos client and server, and between the server and the server.

# How Nacos interacts at present

Here, let me review for you how Nacos 2.X establishes and maintains connections.

​	Nacos 2.x starts to interact between nodes based on grpc mode, and also achieved great performance improvement. The main components to complete the interaction between nodes are **ConnectionManager**, **Grpcbistreamrequestacceptor**, **RpcClient** and **other handlers** used to process requests and responses. Then I will give a process description based on these components.

## How to process

​
![原本的设计](https://user-images.githubusercontent.com/83362909/180590990-e8d6e26d-0948-43fc-a9f8-a9eba60cd9ba.png)
​	`RpcClient` is a base class definition used to connect a server or client, and it will get the remote address by `ServerListFactory`. You need to call `start()` before using RpcClient, and then it will try to connect to the remote server. The specific logic `connectToServer(ServerInfo info)` is delegated to the subclass implementation. The current implementation is `GrpcClient`.

​	`GrpcClient::connectToServer(ServerInfo info)` will send some basic message about current node to server by `ConnectionSetupRequest`. 

​	`ConnectionSetupRequest` will be received by `Grpcbistreamrequestacceptor` in server. It will pass this connection as a `GrpcConnection` to `ConnectionManager`, and then complete the registration through `register(connectionid, con)`.

​	`ConnectionManager` will notify the `ClientConnectionEventListener` which is interested in connection events. It will also be notified when the connection is disconnected. The same behavior also occurs in `RpcClient`.

​	`RpcClient` supports `ServerRequestHandler` which is used to handle requests from server. It is also the principle of heartbeat perception, more in `RpcClient` by  `ClientDetectionRequest` and  `ClientDetectionResponse`.

# Proposal

## How to discover ability

​	Nacos 2.x supports long connections, so the abilities of the current node can be carried into the `ConnectionSetupRequest`  when establishing the connection by `RpcClient::connectToServer(ServerInfo info)`. 

​	So server can receive the abilities from client when registering the `Connection`,  and then server sends a `ServerAbilitySynRequest` to client telling what server supports. Then client will discover server's abilities.

​	The ability collection of  a node is called a `AbilityTable` instance.  It is presented as `byte[]`. Each flag bit represents a capability. `0` means closed, `1` means on.

​	When current node receives a `AbilityTable` from other node,  it will not add `AbilityTable`  to the current node immediately, but passes the it to the `AbilityPreProcessor`s for pre-processing, and will not be added to the current node until the processing is completed. `AbilityPreProcessor` is a intereface for possible scenarios in the future.  If the scenario requires, for example, the current node believes that all clients do not support or support a certain capability, this interface can be implemented to preprocess the coming `AbilityTable`.

​	The delay of preprocessing depends on the future `AbilityPreProcessor` implementation which is currently doing nothing.

### Problem and solutions

- How to finish the preservation and maintenance of ability table from other node, maybe server or client?
- How to ensure that the `AbilityTable` is obtained before the RpcClient makes a service request?
- How can I use `AbilityTable` that I have got?

These will all be solved in the `AbilityControlManager`.

### How to ensure obtained before `RpcClient` makes a service request

> Review

`RpcClient` will call `start()` to connect to the server before using, which is a synchronous operation. When the connection fails, it will call `switchServerAsync()` to do it asynchronously. However,  in either way,  it cannot be used to send service requests until `RpcClient`'s status changes to `RUNNING`.

> Design

To solve this problem, just distinguish the following two situations：

- Whether the current node receives the capability table；
- Whether the capability table is pre-processing;
- If received, whether preprocessing is completed and join the current node；
  - It cannot join the current node without completing the preprocessing；

Set the life cycle of the `AbilityTable` in `AbilityControlManager`.

- `NOT_EXISTED`：The `AbilityTable`  does not exist in the current node； 
- `INITIALING`：The current node has received the capability table, but it is being pre processed by `AbilityPreProcessor`s at this time； 
- `READY`：The `AbilityTable` has been aggregated into `AbilityControlManager`；
- `EXPIRED`：The connection was disconnected,  the  `AbilityTable` expired, and was soon removed；

 

​	All of them can be got by `AbilityControlManager` used to check the status of  `AbilityTable`. When `RpcClient` tries to connect to server, it is also ready to receive the  `AbilityTable`. 

​	`RpcClient`  will choose to reconnect  and get `AbilityTable` asynchronously when it attempts to obtain the status of `AbilityTable`  three times but gets `NOT_EXISTED`.

​	`AbilityControlManager` will set the status of  the  `AbilityTable` to `INITIALING` when `RpcClient` receives the `AbilityTable`. And `RpcClient` will wait `AbilityTable` completes pre-processing and then adds it to the current node.  So it is not recommended to implement too complex pre-operations on `nacos-client` module but it supports.

### How to save

All `AbilityTable` instance will be held in `Map<String, AbilityTable>` filed of  `AbilityControlManager` . And the key  of map is connection-id and value  of map is `AbilityTable` instance. Combined with the above status model, the processing is as follows.

> #### client

![Nacos-Client能力协商](https://user-images.githubusercontent.com/83362909/180591037-9bfbef4f-deca-4d93-a9f7-aa31a6979869.png)
Based on the above life cycle, the capability negotiation process of the client is as follows:

- After `RpcClient` sends the `ConnectionSetupRequest` and successfully obtains the `Connection` instance, let `RpcClient` try to track the status of the `AbilityTable` three times. If the results are always  `NOT_EXISTED`, then the `Connection` established  will be considered invalid and will no longer be blocked. Continue to run according to the original process, and then call `switchserverasync()` to do it asynchronously；
- If the `AbilityTable` is normally obtained (the status is `INITIALING`), it means that the client has received the  `AbilityTable` and is in the pre-processing,  so it will keep tracking the status of  `AbilityTable`  and wait for the processing to complete；
  - If the `Connection` is disconnected halfway, the`AbilityTable ` will be set to `EXPIRED`. It will not wait. It is also considered that the connection established this time is invalid. Continue to run according to the original process, and then call switchserverasync() to perform asynchronously；

After successfully registering the connection with the `ConnectionManager`, it will try to send `ServerAbilitySynRequest ` to this client. Client will receive by `ServerAbilityRequestHandler`. In order to make the information confirmed **as soon as possible**, the following methods are adopted：

- After finish the `Connection` established and registered , the server will hand over the `AbilityTable`  to the `AbilityControlManager`, and then pre-process and add it. This process is asynchronous；
- After the `ServerAbilityRequestHandler` receives the `AbilityTable` from server,  the client also takes the post-processing and addition of the  `AbilityTable` as a task and directly returns the response to the server;

Since both the client and the server add and process capacity tables, the response will be fast if it is normal. However, in order to ensure that the client can receive normally, if the server fails to receive the response in a legal time, it will try to send it twice or three times.

After the client establishes the `Connection` and receives `AbilityTable` of the server normally , it will set the status of `RpcClient` to `RUNNING` to receive and process service requests.

Adding a `ConnectionEventListener` to `RpcClient` when the connection is disconnected,  then automatically delete the  `AbilityTable` .

> #### server

![Nacos-Server能力协商](https://user-images.githubusercontent.com/83362909/180591064-2f6ed6b4-368c-4531-96f5-3e6af7d34a8e.png)
We have known that `ConnectionManager` is a container to maintain `Connection`. When a connection comes, it will be `register(connectionId, conn)` by `ConnectionManager`. `ConnectionManager` will invoked `unregister(connectionId)` if disconnected.

​	Listeners  named `ClientConnectionEventListener` (It has two method: `clientConnected(Connection connect)` and `clientDisConnected(Connection connect)`) are called whether it connect or disconnect. 

​	So I try to add a new `ClientConnectionEventListener` for `AbilityTable`.  `clientConnected(Connection connect)` is used to add ability table from client, and `clientDisConnected(Connection connect)` is used to remove ability table whose `Connection` disconnected.

### How to maintain `AbilityControlManager`

​	Client and server have their own strategies to achieve ability control, for example, the server needs to maintain the capacity of cluster nodes  but client does not.  So `AbilityControlManager` will be a abstract class, for implements `ClientAbilityControlManager` and `ServerAbilityControlManager`. 

​	Considering that some low-level common modules will use the `AbilityControlManager`, but the specific implementation is in the higher modules, for example, `RpcClient` in `nacos-common` will use the `AbilityControlManager`. So I try to maintain `AbilityControlManager` by `NacosServiceLoader` power by `Java SPI`. The `AbilityControlManager` is designed to be a single instance by `NacosAbilityManagerHolder` exposing `getInstance()` static method and is put in the `nacos-common` module. 

![NacosAbilityManager服务发现](https://user-images.githubusercontent.com/83362909/180591090-846562ec-acd8-430f-adcf-a33a74cc5c73.png)
A legal client or server should have a corresponding   `AbilityControlManager` present. The single instance is got by `NacosAbilityManagerHolder.getInstance()` no matter client or server.

## What is new

Based on the above design and implementation, Nacos capability control will support the following contents.

### Combine cluster ability

​	We have known that `RpcClient` will send basic message of current node to server before connecting, then server will send its ability table to client in server environment. `ClusterRpcClientProxy` in `nacos-core` is a instance maintaining the connection with other server node by `GrpcClusterClient` which is a subclass of `RpcClient`. It can be used to get `AbiilityTable` of other server node. 

For example, here are `AbiilityTable` from server nodes：

- `server-01`：`1110 0001`
- `server-02`：`1100 0001`
- `server-03`：`1100 0001`
- `server-04`：`1110 1101`

Then `AbilityControlManager` can combine above table to：`1100 0001` , which is all node of this cluster can support  achieving capability cohesion (No matter whcih server node down, this ability still services). This can be got by `ServerAbilityControlManager::isClusterEnable`. 

### Node ability

​	We have collected ability table from client keeping in `AbilityControlManager` by `Map<connection-id, AbilityTable>`. It is easy to know whether a client supports a certain function. This can be got by `AbilityControlManager::isEnable`, cluster too.

### Register components interested in a ability

​	Some component implementing `HandlerMapping` will be invoke after you turn on/off **the ability of current node**, for example, you turn the flag of `AbilityTable` from `0` to `1` by `AbilityControlManager::enableCurrentNodeAbility`, which means to run this ability. Then it will call back `HandlerMapping` which is interested in this ability.

​	`HandlerMapping` is a listener, which has a method：``trigger(boolean isEnable)``. They will be invoked after you run or close a certain ability of current node. Each ability has their own `HandlerMapping`. They can be *triggered* if ability of cluster changes. However, the listeners registered for the current node's capabilities and the listeners registered for the cluster's capabilities are two separate sets

​	`AbilityControlManager` can combine all ability of server node in a cluster and get a consistent `AbilityTable`, like  `1100 0001`. Then we can register some components if it is interested in a certain ability. When Nacos wants some components to run or close if all server node support or one of them not  supports, it can register these components to `AbilityControlManager` and they will be invoked after a certain ability of cluster changes.

> For example

​	In `PersistentConsistencyServiceDelegateImpl`, `Nacos` use  `BasePersistentServiceProcessor` if all of server node in cluster is `1.4.0` after, or `RaftConsistencyServiceImpl` instead. 

​	We can set `persistent` as an ability for server and set `persistent` ability disabled if version of server is higher than  `1.4.0`, and set enabled if version of server is lower than  `1.4.0`. Then we can register `PersistentConsistencyServiceDelegateImpl` as a `HandlerMapping` and implements the method to choose certain persistent consistency service dynamically for cluster. 

​	It will be invoked if one of server node in cluster not supported or all of server node in cluster supported when combining server node abilities.

### Register pre-processor

​	`AbilityTable` will be pre-process before it join current node. If there are scenarios that need to be used in the future, you can use `AbilityControlManager::registerPreprocessor` to register.

# Last

​	Thanks for your reading. The above is my implementation plan for Nacos capability negotiation. If there are any deficiencies, I hope you can leave me a message in the comment area. I am looking forward to receiving your valuable suggestions. Thank you!

**Comment by CherishCai** [comment]
> 因此，服务器可以在注册 Connection 时接收到从客户端的能力，然后服务器向该客户端发送 `ServerAbilitySynRequest`，告诉客户端服务端支持什么，然后客户端将发现服务器的能力；

是否可以通过构造 `ConnectionSetupResponse` 返回服务端支持的能力呢？

**Comment by Daydreamer-ia** [comment]
> > 因此，服务器可以在注册 Connection 时接收到从客户端的能力，然后服务器向该客户端发送 `ServerAbilitySynRequest`，告诉客户端服务端支持什么，然后客户端将发现服务器的能力；
> 
> 是否可以通过构造 `ConnectionSetupResponse` 返回服务端支持的能力呢？
在asoc的实现版本里，是通过在setup response里把server支持的能力表发送给client
