### ISSUE TITLE
Nacos 2.x admin 服务提供者页面，权重和上下线功能 设置无效果或者说是有歧义性。

### ISSUE THREAD

**Issue by evin0329** [alibaba/nacos#8793]
nacos 2.0.1 + dubbo 2.7.13

### 1. 解决方法
先说下结论吧，不要使用编辑实例信息中的权重和是否上线选项，老老实实在元数据框中配置相关字段吧，因为他不会生效或者说他满足不了你的预期。
![image](https://user-images.githubusercontent.com/35405705/180661246-e15e9154-df24-4681-a99d-b27f0864f9bc.png)

### 2. 权重功能
 对于权重功能，映射在dubbo URL参数列表中为 【weight】。虽然dubbo和nacos在这两个配置上意义一样，但是当你查看nacos返回的配置信息后，你会发现从nacos源数据转换为dubbo的URL用的是metadata中的字段而非你配置的weight字段。org.apache.dubbo.registry.nacos.NacosRegistry#buildURL
![image](https://user-images.githubusercontent.com/35405705/180660650-d104fdff-ca6d-4913-8b8b-c162bfb391a5.png)
![image](https://user-images.githubusercontent.com/35405705/180660711-f505b4f9-7b50-4f71-860e-72c22a2a483b.png)
![image](https://user-images.githubusercontent.com/35405705/180660730-1b20e0a2-769d-4d4b-be64-838890f4f73b.png)
![image](https://user-images.githubusercontent.com/35405705/180660990-f3bd85da-732c-47f3-a028-48bcce40d7a1.png)

### 3. 上下线功能
对于上下线功能，映射在dubbo URL参数列表中为 【enable】，当然会跟权重的功能产生一样的问题，不过有个不一样的地方是，当你指定一个实例下线后，你期望返回给你的enable字段为false，但是实际上是连这个服务实例信息都不会返回，并且这个功能从表面看起来，符合你的预期，因为它确实下线了，也不会再被调用，但是它实际上是因为获取到空的实例信息导致invoker被销毁了，当你再次上线时，dubbo会感知有新的服务实例上线，导致消费者端重新引用，并且重新创建连接。
![image](https://user-images.githubusercontent.com/35405705/180660889-c6446287-af14-4c0d-87e2-daa0b690dda7.png)
![image](https://user-images.githubusercontent.com/35405705/180660876-4092ae06-7094-4098-badc-6a13000d3076.png)
![image](https://user-images.githubusercontent.com/35405705/180661605-731406ec-f026-4575-9086-f292ee5b481c.png)
![image](https://user-images.githubusercontent.com/35405705/180661655-f06fde81-3fe0-4c0d-bfc3-d56e97cc76fc.png)
![image](https://user-images.githubusercontent.com/35405705/180661668-1a00f561-e17b-4778-95bb-158ce944d5b5.png)
![image](https://user-images.githubusercontent.com/35405705/180661730-816b326f-9295-4569-8f75-b10644e8244b.png)
多个服务实例也一样，下线一个会直接根据返回的实例数据，生成新的invokers，旧的invokers会被当成垃圾回收掉。在org.apache.dubbo.registry.integration.RegistryDirectory#refreshInvoker中有相关逻辑代码

### 4. 正确使用元数据框
当你在元数据框中老老实实手填相关字段后，这些功能回归正常。
![image](https://user-images.githubusercontent.com/35405705/180661047-a7053692-bab0-4a61-ae22-22e004c90c4c.png)
![image](https://user-images.githubusercontent.com/35405705/180661080-ea764868-5110-4d81-93a3-44eb6adc8e2f.png)

**Comment by KomachiSion** [comment]
dubbo使用nacos实例元数据来添加他自己的内容，而不是用nacos提供的上下线和权重作为配置内容，这个issue可能要提给dubbo。 因为nacos是公共的注册配置中心，没办法只为dubbo的元数据设置上下线功能。

另外，权重可能实际使用不生效，但是上下线功能应该是生效的，因为如果下线了，nacos直接不会推给dubbo地址，连地址都没有，dubbo元数据都读不到。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
