### ISSUE TITLE
The expected value is not set in NacosConfigProperties？bootstrap.properties中config.shared-configs[0].refresh=true

### ISSUE THREAD

**Issue by xhans** [alibaba/nacos#8794]
**Describe the bug**

bootstrap.properties中使用shared-config指定了额外的配置文件，如下：
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.shared-configs[0]=safe.properties
spring.cloud.nacos.config.shared-configs[0].group=DEFAULT_GROUP
spring.cloud.nacos.config.shared-configs[0].refresh=true

**Expected behavior**
safe.properties file, which can be accessed dynamically at runtime.
safe.properties 文件中配置，在程序运行时可以动态获取。

**Actually behavior**
After modifying the configuration in the safe.properties file and publishing it on the NACOS server management interface, the program failed to obtain the latest modified value.
在nacos服务端管理界面，修改safe.properties文件中的配置并发布，程序未能获取到最新的修改后的值。

**How to Reproduce**
refer to [Additional context]

**Desktop (please complete the following information):**
 - OS: [nacos-server linux ；other windows]
 - Version [nacos-server 2.1.0（单机）, nacos-client 2.2.0.RELEASE]
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos]
 - spring-boot：2.6.3
 - spring-cloud：2021.0.3
 - jdk：1.8

**Additional context**
After the configuration file is modified and published, the program does not obtain the modified value?
修改safe.properties配置文件内容并发布后，程序没有获取到修改后的值？
![180650872-08](https://user-images.githubusercontent.com/42534039/180682723-bea55e8f-e5ec-4152-8274-df1f1f9e62a2.png)

项目启动后在org.springframework.cloud.context.refresh.ContextRefresher的refresh 方法设置断点后，继续更新safe.properties文件内容，重新发布，没有进入断点。
项目启动时在com.alibaba.cloud.nacos.NacosConfigProperties的sharedConfigs方法设置断点，此时safe.properties文件的refresh属性为false

![180651289-2](https://user-images.githubusercontent.com/42534039/180682829-7c4b2fb1-1ed9-494a-b9dd-b926e838e10e.png)

项目启动时在com.alibaba.cloud.nacos.NacosConfigProperties的assembleConfigServiceProperties方法设置断点，此方法返回的Properties对象中有键值对:"sharedConfigs[0].refresh"->"true"，该处说明该项配置可以被读取。然而断点观察发现Properties对象在创建出ConfigService对象后，后续没有在使用？

![180652408-a3](https://user-images.githubusercontent.com/42534039/180682845-aa6e64dd-8398-4ce5-8e5a-4f1d65cda87d.png)
![180652347-4](https://user-images.githubusercontent.com/42534039/180682852-9e31bb61-716c-4def-9a96-d32ecdaed4e2.png)

**Comment by KomachiSion** [comment]
I think you should move this issue to spring cloud alibaba community. The codes in your showed is implement in there.

**Comment by xhans** [comment]
> I think you should move this issue to spring cloud alibaba community. The codes in your showed is implement in there.

ok，thanks！
