### ISSUE TITLE
does it a bug at nacos config of 'contentPath' when there is a context-path at address server url

### ISSUE THREAD

**Issue by 1em0n9527** [alibaba/nacos#8796]
**Describe the bug**
my nacos address url is something like ip:port/${address-context-path}/nacos/serverlist
nacos server url has no  context-path: ip:port/nacos
I read the  code about context-path, but a little confused about it.
below is my demo environment:
nacos address: 192.168.0.100:8080:8080/aa/bb/nacos/serverlist
nacos server: 192.168.0.101:8848,  192.168.0.102:8848,  192.168.0.103:8848

client use address server correctly, and get the url : 192.168.0.100:8080/aa/bb/nacos/serverlist
but use nacos server address wrong, the wrong url: 192.168.0.101:8848/aa/bb/nacos/bababa

client config: 
``` yml
spring:
  cloud:
    nacos:
      discovery:
        endpoint: 192.168.0.100:8080:8080
        contextPath: aa/bb
```

the contextPath will be added at endpoint of address server url , and also be added at nacos  server address. 
some code below:

-------------------------------------------------------------------------------------------------------------------------
Chinese version:
当使用带有 context-path 的 nacos address 服时候, 会错误拼接 nacos-server url, 
不知道是不是我对参数理解有误, 下面是我的测试环境:

nacos address: 192.168.0.100:8080/aa/bb/nacos/serverlist
nacos server: 192.168.0.101:8848,  192.168.0.1032:8848,  192.168.0.103:8848

当客户端使用配置:
```yml
spring:
  cloud:
    nacos:
      discovery:
        endpoint: 192.168.0.100:8080
        contextPath: aa/bb
```
将 aa/bb 都拼接到 url 了
** nacos address url : 192.168.0.100:8080/aa/bb/nacos/serverlist
nacos server url    : 192.168.0.101:8848/aa/bb/nacos/bababa**

其中 nacos-server url 为错误的 url, 导致 nacos server 读取失败

ServerListManager.java:182 line  v1.4.2
``` java
if (StringUtils.isBlank(endpoint)) {
    throw new NacosException(NacosException.CLIENT_INVALID_PARAM, "endpoint is blank");
}
this.isFixed = false;
if (StringUtils.isBlank(namespace)) {
    this.name = endpoint;
    this.addressServerUrl = String.format("http://%s:%d%s/%s", this.endpoint, this.endpointPort,
            ContextPathUtil.normalizeContextPath(this.contentPath), this.serverListName);
} else {
    this.namespace = namespace;
    this.tenant = namespace;
    this.name = this.endpoint + "-" + namespace;
    this.addressServerUrl = String
            .format("http://%s:%d%s/%s?namespace=%s", this.endpoint, this.endpointPort,
                    ContextPathUtil.normalizeContextPath(this.contentPath), this.serverListName, namespace);
}
```

ClientWorker.java:380 line v1.4.2
``` java
HttpRestResult<String> result = agent
        .httpPost(Constants.CONFIG_CONTROLLER_PATH + "/listener", headers, params, agent.getEncode(),
                readTimeoutMs);
```

ServerHttpAgent.java:250 line v1.4.2
``` java
    private String getUrl(String serverAddr, String relativePath) {
        return serverAddr + ContextPathUtil.normalizeContextPath(serverListMgr.getContentPath()) + relativePath;
    }
```

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
没有问题，contextPath是跟路径， nacos是需要查询的服务的名称， serverlist是服务地址所以合起来是`aa/bb/nacos/serverlist`

**Comment by 1em0n9527** [comment]
> 没有问题，contextPath是跟路径， nacos是需要查询的服务的名称， serverlist是服务地址所以合起来是`aa/bb/nacos/serverlist`

但是这个 根路径在 getUrl 代码里面也拼接到 nacos server 地址里面去了, 不仅仅是拼接到 服务地址

**Comment by KomachiSion** [comment]
没问题啊，客户端这个参数就是说client请求服务端的时候要带这个url啊，和地址服务还是nacos服务没关系。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
