### ISSUE TITLE
Java11 & Nacos2.0.3

### ISSUE THREAD

**Issue by SupoorMan** [alibaba/nacos#8807]
- OS: MacOS
 - Version Nacos2.0.3
 - Module -
 - SDK [Java11]

**Additional context**
start Nacos2.0.3 with java11

startup.sh with multiple java versions
If there are multiple java versions, specify the run version configuration
**export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.16.jdk/Contents/Home"**

startup.sh needs to depend on the jre package
Versions after java8 do not have their own jre package
There are two solutions:
1. Use jlink to generate jre
2. Remove "$JAVA_OPT_EXT_FIX" from the last second statement in the startup.sh script.  
`form: nohup "$JAVA" "$JAVA_OPT_EXT_FIX" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &`
`to:     nohup "$JAVA" ${JAVA_OPT} nacos.nacos >> ${BASE_DIR}/logs/start.out 2>&1 &`

Services is running.

**Comment by KomachiSion** [comment]
Please upgrade to new version, this problem has been fiexd.
