### ISSUE TITLE
Nacos 2.0.4 MacOS 10.13.6 版本兼容性疑问

### ISSUE THREAD

**Issue by luyunhua** [alibaba/nacos#8811]
## Issue Description
`

/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/bin/java -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=55742:/Applications/IntelliJ IDEA.app/Contents/bin -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/lib/tools.jar:/Users/hacktomato/src/hongsen/jeecg-boot/jeecg-boot/jeecg-cloud-module/jeecg-cloud-nacos/target/classes:/Users/hacktomato/.m2/repository/org/apache/tomcat/embed/tomcat-embed-jasper/9.0.39/tomcat-embed-jasper-9.0.39.jar:/Users/hacktomato/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.39/tomcat-embed-core-9.0.39.jar:/Users/hacktomato/.m2/repository/org/apache/tomcat/tomcat-annotations-api/9.0.39/tomcat-annotations-api-9.0.39.jar:/Users/hacktomato/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.39/tomcat-embed-el-9.0.39.jar:/Users/hacktomato/.m2/repository/org/eclipse/jdt/ecj/3.18.0/ecj-3.18.0.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-security/2.3.5.RELEASE/spring-boot-starter-security-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter/2.3.5.RELEASE/spring-boot-starter-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.3.5.RELEASE/spring-boot-autoconfigure-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.3.5.RELEASE/spring-boot-starter-logging-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.13.3/log4j-to-slf4j-2.13.3.jar:/Users/hacktomato/.m2/repository/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar:/Users/hacktomato/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-core/5.2.10.RELEASE/spring-core-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-jcl/5.2.10.RELEASE/spring-jcl-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-aop/5.2.10.RELEASE/spring-aop-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-beans/5.2.10.RELEASE/spring-beans-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/security/spring-security-config/5.3.5.RELEASE/spring-security-config-5.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/security/spring-security-core/5.3.5.RELEASE/spring-security-core-5.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-context/5.2.10.RELEASE/spring-context-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/security/spring-security-web/5.3.5.RELEASE/spring-security-web-5.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-expression/5.2.10.RELEASE/spring-expression-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-web/5.2.10.RELEASE/spring-web-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-naming/2.0.4/nacos-naming-2.0.4.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-core/2.0.4/nacos-core-2.0.4.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-common/2.0.4/nacos-common-2.0.4.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-consistency/2.0.4/nacos-consistency-2.0.4.jar:/Users/hacktomato/.m2/repository/com/caucho/hessian/4.0.63/hessian-4.0.63.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-auth/2.0.4/nacos-auth-2.0.4.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-sys/2.0.4/nacos-sys-2.0.4.jar:/Users/hacktomato/.m2/repository/io/jsonwebtoken/jjwt-api/0.11.2/jjwt-api-0.11.2.jar:/Users/hacktomato/.m2/repository/io/jsonwebtoken/jjwt-impl/0.11.2/jjwt-impl-0.11.2.jar:/Users/hacktomato/.m2/repository/io/jsonwebtoken/jjwt-jackson/0.11.2/jjwt-jackson-0.11.2.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-test/5.2.10.RELEASE/spring-test-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-test/2.3.5.RELEASE/spring-boot-test-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/com/alipay/sofa/jraft-core/1.3.8/jraft-core-1.3.8.jar:/Users/hacktomato/.m2/repository/org/ow2/asm/asm/6.0/asm-6.0.jar:/Users/hacktomato/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/hacktomato/.m2/repository/org/rocksdb/rocksdbjni/5.18.4/rocksdbjni-5.18.4.jar:/Users/hacktomato/.m2/repository/net/java/dev/jna/jna/5.5.0/jna-5.5.0.jar:/Users/hacktomato/.m2/repository/org/jctools/jctools-core/2.1.1/jctools-core-2.1.1.jar:/Users/hacktomato/.m2/repository/com/lmax/disruptor/3.3.7/disruptor-3.3.7.jar:/Users/hacktomato/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/Users/hacktomato/.m2/repository/com/alipay/sofa/hessian/3.3.6/hessian-3.3.6.jar:/Users/hacktomato/.m2/repository/io/dropwizard/metrics/metrics-core/4.1.14/metrics-core-4.1.14.jar:/Users/hacktomato/.m2/repository/com/alipay/sofa/rpc-grpc-impl/1.3.8/rpc-grpc-impl-1.3.8.jar:/Users/hacktomato/.m2/repository/org/reflections/reflections/0.9.11/reflections-0.9.11.jar:/Users/hacktomato/.m2/repository/org/javassist/javassist/3.21.0-GA/javassist-3.21.0-GA.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-api/2.0.4/nacos-api-2.0.4.jar:/Users/hacktomato/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/Users/hacktomato/.m2/repository/io/netty/netty-all/4.1.53.Final/netty-all-4.1.53.Final.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot/2.3.5.RELEASE/spring-boot-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.3.5.RELEASE/spring-boot-starter-web-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.3.5.RELEASE/spring-boot-starter-json-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.11.3/jackson-datatype-jdk8-2.11.3.jar:/Users/hacktomato/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.3/jackson-datatype-jsr310-2.11.3.jar:/Users/hacktomato/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.11.3/jackson-module-parameter-names-2.11.3.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-webmvc/5.2.10.RELEASE/spring-webmvc-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/hacktomato/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/Users/hacktomato/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/hacktomato/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/hacktomato/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/hacktomato/.m2/repository/org/apache/mina/mina-core/2.0.0-RC1/mina-core-2.0.0-RC1.jar:/Users/hacktomato/.m2/repository/org/javatuples/javatuples/1.2/javatuples-1.2.jar:/Users/hacktomato/.m2/repository/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar:/Users/hacktomato/.m2/repository/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/Users/hacktomato/.m2/repository/commons-codec/commons-codec/1.14/commons-codec-1.14.jar:/Users/hacktomato/.m2/repository/mysql/mysql-connector-java/8.0.22/mysql-connector-java-8.0.22.jar:/Users/hacktomato/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.30/log4j-over-slf4j-1.7.30.jar:/Users/hacktomato/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar:/Users/hacktomato/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-cmdb/2.0.4/nacos-cmdb-2.0.4.jar:/Users/hacktomato/.m2/repository/io/micrometer/micrometer-registry-prometheus/1.5.6/micrometer-registry-prometheus-1.5.6.jar:/Users/hacktomato/.m2/repository/io/micrometer/micrometer-core/1.5.6/micrometer-core-1.5.6.jar:/Users/hacktomato/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar:/Users/hacktomato/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/hacktomato/.m2/repository/io/prometheus/simpleclient_common/0.8.1/simpleclient_common-0.8.1.jar:/Users/hacktomato/.m2/repository/io/micrometer/micrometer-registry-elastic/1.5.6/micrometer-registry-elastic-1.5.6.jar:/Users/hacktomato/.m2/repository/io/micrometer/micrometer-registry-influx/1.5.6/micrometer-registry-influx-1.5.6.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/2.3.5.RELEASE/spring-boot-starter-actuator-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-actuator-autoconfigure/2.3.5.RELEASE/spring-boot-actuator-autoconfigure-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-actuator/2.3.5.RELEASE/spring-boot-actuator-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-istio/2.0.4/nacos-istio-2.0.4.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-client/2.0.4/nacos-client-2.0.4.jar:/Users/hacktomato/.m2/repository/io/prometheus/simpleclient/0.5.0/simpleclient-0.5.0.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-netty-shaded/1.24.0/grpc-netty-shaded-1.24.0.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-core/1.24.0/grpc-core-1.24.0.jar:/Users/hacktomato/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/Users/hacktomato/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/Users/hacktomato/.m2/repository/io/perfmark/perfmark-api/0.17.0/perfmark-api-0.17.0.jar:/Users/hacktomato/.m2/repository/io/opencensus/opencensus-api/0.21.0/opencensus-api-0.21.0.jar:/Users/hacktomato/.m2/repository/io/opencensus/opencensus-contrib-grpc-metrics/0.21.0/opencensus-contrib-grpc-metrics-0.21.0.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-protobuf/1.24.0/grpc-protobuf-1.24.0.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-api/1.24.0/grpc-api-1.24.0.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-context/1.24.0/grpc-context-1.24.0.jar:/Users/hacktomato/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar:/Users/hacktomato/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/Users/hacktomato/.m2/repository/com/google/guava/guava/26.0-android/guava-26.0-android.jar:/Users/hacktomato/.m2/repository/org/checkerframework/checker-compat-qual/2.5.2/checker-compat-qual-2.5.2.jar:/Users/hacktomato/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-protobuf-lite/1.24.0/grpc-protobuf-lite-1.24.0.jar:/Users/hacktomato/.m2/repository/io/grpc/grpc-stub/1.24.0/grpc-stub-1.24.0.jar:/Users/hacktomato/.m2/repository/com/google/api/grpc/proto-google-common-protos/1.17.0/proto-google-common-protos-1.17.0.jar:/Users/hacktomato/.m2/repository/com/google/protobuf/protobuf-java/3.16.1/protobuf-java-3.16.1.jar:/Users/hacktomato/.m2/repository/io/envoyproxy/controlplane/api/0.1.27/api-0.1.27.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-config/2.0.4/nacos-config-2.0.4.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/2.3.5.RELEASE/spring-boot-starter-jdbc-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/com/zaxxer/HikariCP/3.4.5/HikariCP-3.4.5.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-jdbc/5.2.10.RELEASE/spring-jdbc-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/org/springframework/spring-tx/5.2.10.RELEASE/spring-tx-5.2.10.RELEASE.jar:/Users/hacktomato/.m2/repository/commons-io/commons-io/2.7/commons-io-2.7.jar:/Users/hacktomato/.m2/repository/org/apache/derby/derby/10.14.2.0/derby-10.14.2.0.jar:/Users/hacktomato/.m2/repository/org/aspectj/aspectjrt/1.9.6/aspectjrt-1.9.6.jar:/Users/hacktomato/.m2/repository/cglib/cglib-nodep/2.1/cglib-nodep-2.1.jar:/Users/hacktomato/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar:/Users/hacktomato/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.13/httpcore-nio-4.4.13.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.3.5.RELEASE/spring-boot-starter-tomcat-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/glassfish/jakarta.el/3.0.3/jakarta.el-3.0.3.jar:/Users/hacktomato/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.39/tomcat-embed-websocket-9.0.39.jar:/Users/hacktomato/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.3/jackson-core-2.11.3.jar:/Users/hacktomato/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.3/jackson-databind-2.11.3.jar:/Users/hacktomato/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.3/jackson-annotations-2.11.3.jar:/Users/hacktomato/.m2/repository/org/springframework/boot/spring-boot-starter-aop/2.3.5.RELEASE/spring-boot-starter-aop-2.3.5.RELEASE.jar:/Users/hacktomato/.m2/repository/org/aspectj/aspectjweaver/1.9.6/aspectjweaver-1.9.6.jar:/Users/hacktomato/.m2/repository/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar:/Users/hacktomato/.m2/repository/org/jeecgframework/nacos/nacos-console/2.0.4/nacos-console-2.0.4.jar com.alibaba.nacos.JeecgNacosApplication

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 
,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 49156
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://192.168.0.28:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

2022-07-27 16:46:13.892  INFO 49156 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@541afb85' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-07-27 16:46:13.897  INFO 49156 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-07-27 16:46:14.060  INFO 49156 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8848 (http)
2022-07-27 16:46:14.212  INFO 49156 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1562 ms
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/8g/b33bxbhj6t77b65vpb_tn2zh0000gp/T/librocksdbjni4608195053388136110.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/8g/b33bxbhj6t77b65vpb_tn2zh0000gp/T/librocksdbjni4608195053388136110.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

`

### Additional context
从返回错误看，应该是最小兼容版本是10.15

问：如何才能在不升级系统版本的前提下解决问题（由于项目原因，确实无法升级系统版本）

### OSX 版本
10.13.6

**Comment by KomachiSion** [comment]
duplicate with other more issue, please search in issue.s
