### ISSUE TITLE
logback读取不到nacos配置中心的配置

### ISSUE THREAD

**Issue by zzb980881** [alibaba/nacos#8813]
![图片](https://user-images.githubusercontent.com/1118228/181238684-d9366a72-d415-4017-9a69-4e17ba3f7bf0.png)

如上图，logback本来通过include系统配置文件，springProperty可以读取系统配置项的，但nacos作为配置中心后，读取不到
使用
nacos.config.bootstrap.enable=true
nacos.config.remote-first=true
nacos.config.bootstrap.log-enable=true
spring.cloud.nacos.config.bootstrap.enable=true
spring.cloud.nacos.config.remote-first=true
spring.cloud.nacos.config.bootstrap.log-enable=true
都没有效果。
nacos配置中心的加载顺序是怎样，是logback前还是后，如何解决。

**Comment by yydzxz** [comment]
如果文件名是`logback.xml`的话,可以改成`logback-spring.xml`试试

**Comment by KomachiSion** [comment]
logback的include只能在启动时生效， 动态生效的配置应该是不生效的。

**Comment by KomachiSion** [comment]
这个是logback的机制吧，如果能生效，就需要看logback日志生效的时候是怎么应用过去的， 这个应该在应用框架里或者你自己的代码里，和nacos没什么关系，nacos只负责吧配置下推到应用里。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
