### ISSUE TITLE
sdk remove prometheus dependency and metrics with other way.

### ISSUE THREAD

**Issue by The-Plumber101** [alibaba/nacos#8816]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by The-Plumber101** [comment]
sdk remove prometheus dependency and metrics with other way.

**Comment by stone-98** [comment]
这个issues和https://github.com/alibaba/nacos/issues/8354类似

**Comment by stone-98** [comment]
这个issues和#8354类似

**Comment by stone-98** [comment]
这个issues和 #8354 类似

**Comment by The-Plumber101** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

**Comment by The-Plumber101** [comment]
e
