### ISSUE TITLE
Nacos container black hole file issue / nacos容器黑洞文件问题

### ISSUE THREAD

**Issue by QiaoGen** [alibaba/nacos#8818]
### 单节点nacos docker容器无限制的增长磁盘占用。已经关闭所有有关raft日志，所有的日志级别全部提升至ERROR，但还是有raft日志文件生成并产生黑洞文件。
> Environment
```
Linux debian 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
Docker version 20.10.17, build 100c701
nacos/nacos-server:v2.1.0-slim
```
<img width="645" alt="image" src="https://user-images.githubusercontent.com/48583767/181399681-576ea27f-ddd5-4f45-aea2-923047c426ea.png">

如何解决？

**Comment by KomachiSion** [comment]
这个是jraft的raft协议日志，可以到jraft社区看下有没有可以设置大小的。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
