### ISSUE TITLE
nacos 1.4.1 服务注册上，过段时间会自动掉线

### ISSUE THREAD

**Issue by w13259889276** [alibaba/nacos#8819]
Docker version 20.10.17, build 100c70
nacos 1.4.1
服务注册上，过段时间会自动掉线，cpu与内存是正常的，
nacos内没有拿到掉线原因的日志

**Comment by KomachiSion** [comment]
那就是没继续发心跳进行续约。你是怎么注册的？ demo可以发出来

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
