### ISSUE TITLE
提问：在osgi框架中引用nacos-client 2.1.0 提示ReasonException

### ISSUE THREAD

**Issue by YuanFY** [alibaba/nacos#8820]
提示错误：
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve com.xx.nacos : missing requirement [com.xxx.nacos] osgi.wiring.package; filter:="(osgi.wiring.package= com.alibaba.nacos.shaded.com.google.rpc)"

查看引用包中并没有这个包 com.alibaba.nacos.shaded.com.google.rpc， 请问nacos-client不是只需要引入这个jar包么

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.1.0</version>
        </dependency>

但看源码中确实有引用这个包下的类：
```
public final class StatusProto {
  private StatusProto() {}

  private static final Metadata.Key<com.alibaba.nacos.shaded.com.google.rpc.Status> STATUS_DETAILS_KEY =
      Metadata.Key.of(
          "grpc-status-details-bin",
          ProtoLiteUtils.metadataMarshaller(com.alibaba.nacos.shaded.com.google.rpc.Status.getDefaultInstance()));

```

**Comment by KomachiSion** [comment]
只需要引入nacos， 不清楚osgi框架是否做了些特殊的适配，看报错不像是nacos-client的问题。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
