### ISSUE TITLE
How to use function getExecutor() in listen config

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#8828]
The callback interface of the monitoring configuration has two functions. In what scenarios is getExecutor generally used?

监听配置的回调接口有两个函数，getExecutor()一般在什么场景使用？

**Comment by KomachiSion** [comment]
当需要使用指定线程来执行回调的时候使用，如果是null则默认使用Nacos-client的回调线程。

**Comment by five111** [comment]
嗯 那什么情况下需要我自己来指定线程呢 我感觉是不是大部分场景下使用nacos自己的回调线程就可以了。
或者说如果我所有的回调线程都用nacos默认的 会不会有什么问题？

**Comment by YunWZ** [comment]
> 嗯 那什么情况下需要我自己来指定线程呢 我感觉是不是大部分场景下使用nacos自己的回调线程就可以了。 或者说如果我所有的回调线程都用nacos默认的 会不会有什么问题？

getExecutor()返回null的所有listener，都会使用回调线程处理窜行执行，这意味着如果listener处理逻辑比较耗时或被阻塞，会导致其他listener无法被及时处理。

**Comment by KomachiSion** [comment]
如果都用默认回调线程处理，如果其中有一个listener执行逻辑慢或者block了，会影响其他的listener被回调，这个其实是由业务决定的， 如果不希望被阻塞，那就需要指定线程来进行回调。

**Comment by five111** [comment]
感谢回答 @KomachiSion @YunWZ
