### ISSUE TITLE
Configuration file size limit？

### ISSUE THREAD

**Issue by lsh1358046425** [alibaba/nacos#8829]
Nacos单个配置文件的大小有限制吗？在官方文档页面看见了100K的说明，我现在最大的配置文件已经快突破100K了有什么解决办法吗？
![impicture_20220729_170249](https://user-images.githubusercontent.com/45169615/181724569-053d5044-5d3b-4949-9287-7e9f38415c98.png)

**Comment by onewe** [comment]
你居然有这么大的配置🤔

**Comment by YunWZ** [comment]
可以配置的。

**Comment by YunWZ** [comment]
1. `GET /v1/cs/capacity`

   获取当前租户或者分组的容量信息(包括最大限制和当前使用情况);

2. `POST /v1/cs/capacity`

   更新当前租户或者分组的容量配置;

**Comment by KomachiSion** [comment]
大配置容易造成超时等问题，一般限制100k已经足够使用了， 如果有超过这个大小的配置，建议是拆分成两个配置。

**Comment by lsh1358046425** [comment]
> 大配置容易造成超时等问题，一般限制100k已经足够使用了， 如果有超过这个大小的配置，建议是拆分成两个配置。

@KomachiSion 是不是可以配置大小限制？像 @YunWZ 说的那样？

**Comment by lsh1358046425** [comment]
@KomachiSion 我是用Nacos+Gateway搭建了网关，并且动态刷新路由，由于接口很多，所有路由配置会很大，且无限增长，不知道对于这种情况应该怎么处理会好一点，目前想到的就是放开大小限制......

**Comment by KomachiSion** [comment]
我记得默认大小限制是关闭的，只要服务端和数据库能扛住，多大都可以。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
