### ISSUE TITLE
"serviceId" is sensitive, may change it insensitive?

### ISSUE THREAD

**Issue by MicyToy** [alibaba/nacos#883]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
I notice that, nacos's "serviceId" is sensitive, but eureka is insensitive. 
May insensitive could be better?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
nacos 0.8.0
openfeign 2.0.3-RELEASE
spring-cloud-alibaba 0.2.1-RELEASE

**Comment by nkorange** [comment]
It's a good suggestion, can you implement this feature?

**Comment by MicyToy** [comment]
Sorry, recently I have too much work to do ☹. I’m afraid I have no time to do this. Hope others can do this 😊.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by fangjianmin** [comment]
@i will solve it@

**Comment by jifengnan** [comment]
@fangjianmin 兄弟，改的咋样了，崩溃没。

**Comment by fangjianmin** [comment]
so sorry.
these times i have a lot of work to do.

**Comment by jifengnan** [comment]
@fangjianmin 别紧张，我不是催债的。我比你更早看到这个issue，也在改，只是这个东西看起来小，牵扯的地方相当多，非常头疼。

**Comment by MicyToy** [comment]
Thank you for your work, @jifengnan<mailto:notifications@github.com> , and also @fangjianmin<https://github.com/fangjianmin>.  :p

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by fangjianmin** [comment]
After I read the related source code, I want to update the class
"com.alibaba.nacos.naming.core.ServiceManager".
Add "serviceName=StringUtils.upperCase(serviceName);"  to where the “serviceName"  occurs.
Is it Ok?

**Comment by nkorange** [comment]
@fangjianmin Make a PR and we can discuss there.

**Comment by YimRay** [comment]
well done

**Comment by JerryChin** [comment]
I'd like to start a PR for this issue if no one else works on it.

**Comment by KomachiSion** [comment]
In my opinion, service name should be sensitive. the service name is user defined item, nacos should not do more operation expect check format.

**Comment by MicyToy** [comment]
I think, first, both eureka and consul use a case-insensitive solution, using a more usual solution may be better.
secondly, using a case-sensitive solution may increase the complexity of the client.
