### ISSUE TITLE
为用户分配读写权限，仍无法导入配置文件

### ISSUE THREAD

**Issue by isysc1** [alibaba/nacos#8835]
目前 Nacos 使用的版本为 1.4.2

在为用户分配读写权限后，仍旧无法导入配置文件

<img width="631" alt="image" src="https://user-images.githubusercontent.com/46256542/181917873-ed30c0b9-4d8c-431b-9540-727a1cdcab3f.png">

**Comment by chenhao26-nineteen** [comment]
> 目前 Nacos 使用的版本为 1.4.2
> 
> 在为用户分配读写权限后，仍旧无法导入配置文件
> 
> <img alt="image" width="631" src="https://user-images.githubusercontent.com/46256542/181917873-ed30c0b9-4d8c-431b-9540-727a1cdcab3f.png">

#8833 可以参考一下这个issues的回答，在最新的版本中我已经修复了

**Comment by isysc1** [comment]
> > 目前 Nacos 使用的版本为 1.4.2
> > 在为用户分配读写权限后，仍旧无法导入配置文件
> > <img alt="image" width="631" src="https://user-images.githubusercontent.com/46256542/181917873-ed30c0b9-4d8c-431b-9540-727a1cdcab3f.png">
> 
> #8833 可以参考一下这个issues的回答，在最新的版本中我已经修复了

👌 感谢
