### ISSUE TITLE
配置列表出现多余的配置

### ISSUE THREAD

**Issue by tangyuxiaoyao** [alibaba/nacos#8843]
请问下诸位是否有遇到过在配置管理出会出现服务级别注册的配置信息。

类似这样的
com.xxx.api.INameService | mapping |  

com.xxx.api.INameService:::provider:dubbo-provider | dubbo

如果有，为什么会有此信息出现在这里呢？是否可以通过配置或者修改源码去掉该部分展示么。

**Comment by chenhao26-nineteen** [comment]
> 请问下诸位是否有遇到过在配置管理出会出现服务级别注册的配置信息。
> 
> 类似这样的 com.xxx.api.INameService | mapping |  
> 
> com.xxx.api.INameService:::provider:dubbo-provider | dubbo
> 
> 如果有，为什么会有此信息出现在这里呢？是否可以通过配置或者修改源码去掉该部分展示么。

这是dubbo启动时，会把nacos作为配置中心，自动创建的，如果不想创建，可以尝试参考以下配置，
dubbo:
registry:
use-as-config-center: false

**Comment by tangyuxiaoyao** [comment]
是也要作为注册中心，展示的部分为除了正常配置之外多余的配置，麻烦告知这部分有办法去掉么。

**Comment by tangyuxiaoyao** [comment]
是也要作为注册中心，展示的部分为除了正常配置之外多余的配置，麻烦告知这部分有办法去掉么。

**Comment by tangyuxiaoyao** [comment]
> > 请问下诸位是否有遇到过在配置管理出会出现服务级别注册的配置信息。
> > 类似这样的 com.xxx.api.INameService | mapping |  
> > com.xxx.api.INameService:::provider:dubbo-provider | dubbo
> > 如果有，为什么会有此信息出现在这里呢？是否可以通过配置或者修改源码去掉该部分展示么。
> 
> 这是dubbo启动时，会把nacos作为配置中心，自动创建的，如果不想创建，可以尝试参考以下配置， dubbo: registry: use-as-config-center: false
是也要作为注册中心，展示的部分为除了正常配置之外多余的配置，麻烦告知这部分有办法去掉么。

**Comment by chenhao26-nineteen** [comment]
> > > 请问下诸位是否有遇到过在配置管理出会出现服务级别注册的配置信息。
> > > 类似这样的 com.xxx.api.INameService | mapping |  
> > > com.xxx.api.INameService:::provider:dubbo-provider | dubbo
> > > 如果有，为什么会有此信息出现在这里呢？是否可以通过配置或者修改源码去掉该部分展示么。
> > 
> > 
> > 这是dubbo启动时，会把nacos作为配置中心，自动创建的，如果不想创建，可以尝试参考以下配置， dubbo: registry: use-as-config-center: false
> > 是也要作为注册中心，展示的部分为除了正常配置之外多余的配置，麻烦告知这部分有办法去掉么。

可以参考dubbo这个issue，应该是dubbo侧的问题。https://github.com/apache/dubbo/issues/6645

**Comment by tangyuxiaoyao** [comment]
> > > > 请问下诸位是否有遇到过在配置管理出会出现服务级别注册的配置信息。
> > > > 类似这样的 com.xxx.api.INameService | mapping |  
> > > > com.xxx.api.INameService:::provider:dubbo-provider | dubbo
> > > > 如果有，为什么会有此信息出现在这里呢？是否可以通过配置或者修改源码去掉该部分展示么。
> > > 
> > > 
> > > 这是dubbo启动时，会把nacos作为配置中心，自动创建的，如果不想创建，可以尝试参考以下配置， dubbo: registry: use-as-config-center: false
> > > 是也要作为注册中心，展示的部分为除了正常配置之外多余的配置，麻烦告知这部分有办法去掉么。
> 
> 可以参考dubbo这个issue，应该是dubbo侧的问题。[apache/dubbo#6645](https://github.com/apache/dubbo/issues/6645)

好的 谢谢，这个管用，dubbo.registry.use-as-metadata-center=false 。

**Comment by zuikeb** [comment]
都需要添加
    use-as-config-center: false
    use-as-metadata-center: false

nacos server:NACOS2.1.1

mavne版本
`        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>2.7.8</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.2.1</version>
        </dependency>`
