### ISSUE TITLE
why not calc tenant

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#8849]
https://github.com/alibaba/nacos/blob/de5ec356cca80f975a03b6a2030cfae7afa52846/client/src/main/java/com/alibaba/nacos/client/config/impl/CacheData.java#L251 
CacheData rewrites the hashcode and equals methods, but according to nacos's definition of configuration, tenant should also be one of the calculation conditions，please confirm if there is a problem here
```
 @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((dataId == null) ? 0 : dataId.hashCode());
        result = prime * result + ((group == null) ? 0 : group.hashCode());
        return result;
    }
    
    @Override
    public boolean equals(Object obj) {
        if (null == obj || obj.getClass() != getClass()) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        CacheData other = (CacheData) obj;
        return dataId.equals(other.dataId) && group.equals(other.group);
    }
```
CacheData 重写了hashcode和equals方法，但是按照nacos对配置的定义 tenant也应该成为计算条件之一，请确认这里是否是个问题？

**Comment by KomachiSion** [comment]
不需要 因为单个client只允许访问一个namespace/tenant
