### ISSUE TITLE
spring-boot版本2.6.x的nacos发版时间

### ISSUE THREAD

**Issue by skippyb1** [alibaba/nacos#8850]
大佬们 问下 依赖高版本2.6.x的spring-boot的nacos 啥时候发版

**Comment by chenhao26-nineteen** [comment]
> 

已经发版了，https://github.com/nacos-group/nacos-spring-boot-project/releases，0.2.11开始就支持 spring-boot 2.6.3了

**Comment by skippyb1** [comment]
不是client端 是server端

**Comment by KomachiSion** [comment]
近期应该就会发版了
