### ISSUE TITLE
How to modify an instance enable to true when its enable state is false

### ISSUE THREAD

**Issue by Qutianyawangyue** [alibaba/nacos#8854]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by chenhao26-nineteen** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Actually behavior** A clear and concise description of what you actually to happen.
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See errors
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Centos]
> * Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
> * Module [e.g. naming/config]
> * SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
> 
> **Additional context** Add any other context about the problem here.

Use the online and offline functions of Nacos console
