### ISSUE TITLE
nacos 2.0.3 java sdk 读取配置信息为NULL

### ISSUE THREAD

**Issue by overcls** [alibaba/nacos#8855]
String serverAddr = "localhost";
        String namespaceId = "b0ceb85d-6a7a-4e4a-92b5-64578c25117d";
        String dataId = "xxx.yml";
        String group = "DEFAULT_GROUP";

        Properties properties = new Properties();
        properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
        properties.put(PropertyKeyConst.NAMESPACE, namespaceId);

        ConfigService configService = NacosFactory.createConfigService(properties);

        String config = configService.getConfig(dataId, group, 3000L);
        System.out.println(config);

 获取结果为null 这个是什么问题

**Comment by chenhao26-nineteen** [comment]
> ```
>    String serverAddr = "localhost";
>     String namespaceId = "b0ceb85d-6a7a-4e4a-92b5-64578c25117d";
>     String dataId = "xxx.yml";
>     String group = "DEFAULT_GROUP";
> 
>     Properties properties = new Properties();
>     properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
>     properties.put(PropertyKeyConst.NAMESPACE, namespaceId);
> 
>     ConfigService configService = NacosFactory.createConfigService(properties);
> 
>     String config = configService.getConfig(dataId, group, 3000L);
>     System.out.println(config);
> ```
> 
> 获取结果为null 这个是什么问题

我这边用你的demo测试是可以获取到的，可以检查一下是否配置写错，ns或dataId是否有误

**Comment by KomachiSion** [comment]
获取是null说明配置不存在或者获取失败了，然后从本地缓存中读取到了空配置。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
