### ISSUE TITLE
获取1.x版本注册上来实例的版本和语言信息，并且保存到clientManager中

### ISSUE THREAD

**Issue by hujun-w-2** [alibaba/nacos#8857]
**Is your feature request related to a problem? Please describe.**
1.4.2以前的sdk在发起注册的时候会将版本和语言信息放入header中，grpc注册也会将版本信息带入请求中，但是最新版的服务端没有将客户端传过来的属性记录到某个地方

**Describe the solution you'd like**
方便服务端掌握注册上来的客户端的版本信息，将版本信息存入到clientManager中

**Describe alternatives you've considered**

**Additional context**

**Comment by MajorHe1** [comment]
收集之后也会有地方展示吧，统计不同的版本客户端数量有多少？

以及能不能扩展一下，不仅仅收集header里面的信息，看能不能支持收集客户端上报的元数据里某个字段的信息？

**Comment by hujun-w-2** [comment]
> 收集之后也会有地方展示吧，统计不同的版本客户端数量有多少？
> 
> 以及能不能扩展一下，不仅仅收集header里面的信息，看能不能支持收集客户端上报的元数据里某个字段的信息？

展示的话，是监控的事情了，可以拓展上报信息到prometheus，然后用grafana展示，但是这都是后话了，首先得将数据存到clientnamager行为和2.x保持一致

**Comment by MajorHe1** [comment]
> 展示的话，是监控的事情了，可以拓展上报信息到prometheus，然后用grafana展示，但是这都是后话了，首先得将数据存到clientnamager行为和2.x保持一致

好的，明白了

**Comment by hujun-w-2** [comment]
方案1：将版本和语言信息统一保持到client中
方案2：2.x已经将信息保存到了clientManager中，1.x可以直接通过spring aop的方式拦截注册与反注册接口然后将服务和版本信息写入到自定义的变量中

**Comment by hujun-w-2** [comment]
类似#https://github.com/alibaba/nacos/issues/8297

**Comment by hujun-w-2** [comment]
与@KomachiSion 讨论结论：1.x与2.x版本与语言信息收集到client对象中，另外单独开一个接口负责查询实例版本信息，收集各版本的数量信息到metrics中。

**Comment by hujun-w-2** [comment]
### 一.数据获取和存储
  **各字段取值位置：**
  1.版本和语言字段：1.x在header中，key为：CLIENT_VERSION_HEADER = "Client-Version";2.x在connection的元数据中，格 
    式为：Nacos-Java-Client:v。
  2.app字段：1.x和2.x都在header中，key为：APP_FILED = "app"。
  3.ip字段：1.x可以从request中获取客户端ip，2.x可以直接从payload元数据中获取。
**数据存放位置：**
     1.x和2.x统一存放在AbstractClient中，采用变量ClientAttributes attributes来保存。

### 二.数据查询
    在CatalogController类提供根据服务名、命名空间，group来查询client基础信息的接口

### 三.监控
    开启定时任务，定期统计client的版本和语言分布情况，上报到metrics,方便prometheus做图展示

**Comment by MajorHe1** [comment]
一定需要通过定时任务上报到metrics吗，我记得 metrics统计的接口很多都是 atomic integer ，每当有变化的时候 getAndIncrement 就好了吧

**Comment by hujun-w-2** [comment]
> 一定需要通过定时任务上报到metrics吗，我记得 metrics统计的接口很多都是 atomic integer ，每当有变化的时候 getAndIncrement 就好了吧

是的，上报到metrics指的也是跟之前模式一样先上报一次，然后修改引用对象值的方式

**Comment by hujun-w-2** [comment]
发现一个问题：客户端发起请求，带着版本信息的header，如果经过了distro转发，版本信息会变成服务端的，这样就获取不到原始注册的客户端的版本了。代码如下：
![image](https://user-images.githubusercontent.com/39894911/183229454-bf06bc61-07a4-4e09-8db6-cf41cf3f69f7.png)
![image](https://user-images.githubusercontent.com/39894911/183229470-46aab6a2-8f3a-4bb5-b400-3aac786f00ad.png)

  服务端之前的转发不需要带上服务端的版本，建议去掉，或者新增一个字段放到header也可以 ,
@KomachiSion 怎么看

**Comment by KomachiSion** [comment]
需要，否则可能会出现无限转发的情况，

distroFilter里有一段代码是保护这个情况的，如果来自于UA为nacos-server，且责任节点不是本节点的，会直接报错快速失败。

**Comment by hujun-w-2** [comment]
> 需要，否则可能会出现无限转发的情况，
> 
> distroFilter里有一段代码是保护这个情况的，如果来自于UA为nacos-server，且责任节点不是本节点的，会直接报错快速失败。

这里我指的是client_version这个key,不是ua呢

**Comment by chuntaojun** [comment]
> > 需要，否则可能会出现无限转发的情况，
> > distroFilter里有一段代码是保护这个情况的，如果来自于UA为nacos-server，且责任节点不是本节点的，会直接报错快速失败。
> 
> 这里我指的是client_version这个key,不是ua呢

这里感觉应该调整下，应该是转发server的版本需要加，ClientVersion我理解不应该覆盖？

**Comment by hujun-w-2** [comment]
### 问题1
1. java和go的sdk通过lient-Version字段上报的信息不一样，go语言header中Client-Version包含了语言和版本，而java版的1.xsdk只有版本数据，2.x的sdk有版本和语言，需要按照统一的User-Agent来取,但存在的问题是User-agent在经过distro转发的时候会被服务端修改
**解决方案**：
因为只有转发时user-agent字段才会被服务端重写，所以转发时取出真实的语言和版本放入Client-Version字段中
![image](https://user-images.githubusercontent.com/39894911/187885697-60fe3c43-f06b-451f-8dfd-20db7d659def.png)

### 问题2
由于版本信息目前只在client中存储，而只有注册才会修改client对象中的版本和语言信息，这样功能上线后，已经注册过的实例client中的版本和语言信息会是null的
**解决方案：**
使用1.x的心跳接口来补偿，但是存在一个问题，心跳补偿之后只有接受心跳的节点数据会被补偿，但是剩余节点则没有这个信息，所以在补偿成功后，还需要做一次集群同步，这里集群同步考虑发布一个ClientChangedEvent事件来触发同步

**Comment by PRANRAVEE** [comment]
พี่คะต้องการ

ในวันที่ พ. 21 ธ.ค. 2022 09:23 杨翊 SionYang ***@***.***>
เขียนว่า:
