### ISSUE TITLE
关于使用dubbo3.0服务注册失败的问题

### ISSUE THREAD

**Issue by ebdmn** [alibaba/nacos#8862]
## Ask your question here
Environment
Dubbo version: 3.0.6及以后
Operating System version: Mac OS
Java version: 1.8

dubbo3.0注册服务时失败，但同样的代码在win环境下及官方安装包没有问题；
测试代码地址 https://github.com/ebdmn/ebdmn-test-dubbo
错误信息
https://github.com/ebdmn/ebdmn-test-dubbo/blob/master/error.txt
![image](https://user-images.githubusercontent.com/47840704/182509468-445851ce-acfa-408a-bd65-89f6b9e05657.png)

**Comment by chenhao26-nineteen** [comment]
> ## Ask your question here
> Environment Dubbo version: 3.0.6及以后 Operating System version: Mac OS Java version: 1.8
> 
> dubbo3.0注册服务时失败，但同样的代码在win环境下及官方安装包没有问题； 测试代码地址 https://github.com/ebdmn/ebdmn-test-dubbo 错误信息 https://github.com/ebdmn/ebdmn-test-dubbo/blob/master/error.txt ![image](https://user-images.githubusercontent.com/47840704/182509468-445851ce-acfa-408a-bd65-89f6b9e05657.png)

应该是你Nacos集群的问题，我本地跑了你的demo没有复现，如果是测试，可以尝试删除data目录，启动nacos集群再注册

**Comment by ebdmn** [comment]
> > ## Ask your question here
> > Environment Dubbo version: 3.0.6及以后 Operating System version: Mac OS Java version: 1.8
> > dubbo3.0注册服务时失败，但同样的代码在win环境下及官方安装包没有问题； 测试代码地址 https://github.com/ebdmn/ebdmn-test-dubbo 错误信息 https://github.com/ebdmn/ebdmn-test-dubbo/blob/master/error.txt ![image](https://user-images.githubusercontent.com/47840704/182509468-445851ce-acfa-408a-bd65-89f6b9e05657.png)
> 
> 应该是你Nacos集群的问题，我本地跑了你的demo没有复现，如果是测试，可以尝试删除data目录，启动nacos集群再注册。@ebdmn

我用的是源码启动，单机模式，我对比了一下 启动脚本发现 是因为没有配置nacos.home导致的；现在问题已经解决了，谢谢大佬
