### ISSUE TITLE
suggest：add web operate to delete service instance

### ISSUE THREAD

**Issue by navysummer** [alibaba/nacos#8865]
Deleting service instances through api is sometimes inconvenient

**Comment by chenhao26-nineteen** [comment]
> Deleting service instances through APIs is sometimes inconvenient
Is that what you mean？
![image](https://user-images.githubusercontent.com/35129699/182519064-7e30a4ed-3343-4da5-ba22-412a601908c4.png)

**Comment by navysummer** [comment]
> > Deleting service instances through APIs is sometimes inconvenient
> > Is that what you mean？
> > ![image](https://user-images.githubusercontent.com/35129699/182519064-7e30a4ed-3343-4da5-ba22-412a601908c4.png)

不是删除服务，是在服务详情里删除服务实例
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/17807236/182563096-a751da96-8163-4218-b146-1403ca641b10.png">

**Comment by KomachiSion** [comment]
那需要判断服务是不是持久化的服务， 如果是非持久化的服务，删除按钮其实没有用， 因为非持久化服务是由应用自注册自维护的， 从页面上删掉还会再注册回来。

**Comment by KomachiSion** [comment]
No more response from community, I think this feature is not neccessary for now.
