### ISSUE TITLE
内存过高

### ISSUE THREAD

**Issue by fejay** [alibaba/nacos#8869]
![image](https://user-images.githubusercontent.com/1419019/182578909-828a98de-f24e-4d83-b619-5d1beca4d5f4.png)
内存生成了大量的WeightedSnapshot这种实例, 其实就是metric 性能指标统计信息, 应该是jraft生成的
请问有没有设置关闭性能指标统计?

**Comment by fejay** [comment]
版本是2.0.4

**Comment by KomachiSion** [comment]
看着内存是正常的啊， 是出现了FullGC还是OOM？

**Comment by fejay** [comment]
> 看着内存是正常的啊， 是出现了FullGC还是OOM？

会频繁的yanggc .  堆内存8g, 新生代4g,  内存占用有点高. 内存一般占用5g左右, cpu占用率很低. 使用了dubbo服务注册, 为什么这么高?

**Comment by KomachiSion** [comment]
那应该是正常的， dubbo服务为了续约心跳会发很多心跳请求，ygc多是正常的，没有fullgc其实没问题。
