### ISSUE TITLE
How to solve this error

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#887]
ubuntu18.04.1

No modifications have been made to the configuration file

/# sh /opt/nacos/bin/startup.sh -m standalone
/opt/nacos/bin/startup.sh: 49: /opt/nacos/bin/startup.sh: [[: not found
/opt/nacos/bin/startup.sh: 60: /opt/nacos/bin/startup.sh: [[: not found
/usr/lib/jvm/java-8-oracle/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Djava.ext.dirs=/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/lib/jvm/java-8-oracle/lib/ext:/opt/nacos/plugins/cmdb -Xloggc:/opt/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/opt/nacos -jar /opt/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/opt/nacos/conf/ --logging.config=/opt/nacos/conf/nacos-logback.xml
/opt/nacos/bin/startup.sh: 80: /opt/nacos/bin/startup.sh: [[: not found
nacos is starting，you can check the /opt/nacos/logs/start.out

# java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by nkorange** [comment]
Duplicated with #427
