### ISSUE TITLE
nacos服务隔离之后需要使用公共服务的问题

### ISSUE THREAD

**Issue by talentwing** [alibaba/nacos#8870]
使用命名空间进行配置隔离里面可以用extension-configs来加载共享部分的配置

但是服务隔离并没有extension-configs之类的相关配置让本地开发环境去调用公共的服务...请问这块有什么变通的方式来实现吗?

**Comment by chenhao26-nineteen** [comment]
> 使用命名空间进行配置隔离里面可以用extension-configs来加载共享部分的配置
> 
> 但是服务隔离并没有extension-configs之类的相关配置让本地开发环境去调用公共的服务...请问这块有什么变通的方式来实现吗?

At present, according to the data model of Nacos, it cannot be done, but the service can be accessed across groups by changing the group level.

**Comment by KomachiSion** [comment]
强隔离只有命名空间， 只要在同一个命名空间下，服务都是可以互相发现的。

**Comment by talentwing** [comment]
> 强隔离只有命名空间， 只要在同一个命名空间下，服务都是可以互相发现的。

现在就是想我在私有的命名空间里面发现(调用)另一个命名空间(公共的)的服务

**Comment by wuchubuzai2018** [comment]
> > 强隔离只有命名空间， 只要在同一个命名空间下，服务都是可以互相发现的。
> 
> 现在就是想我在私有的命名空间里面发现(调用)另一个命名空间(公共的)的服务

个人觉得你这种情况，就得用Group去实现隔离，看Nacos的产品约定，命名空间就是租户隔离的概念，强隔离

**Comment by talentwing** [comment]
> 

有相关的文档说明吗?我看了一下github和官网的文档..并没有服务发现的group的相关说明..只有配置的

**Comment by talentwing** [comment]
> > > 强隔离只有命名空间， 只要在同一个命名空间下，服务都是可以互相发现的。
> > 
> > 
> > 现在就是想我在私有的命名空间里面发现(调用)另一个命名空间(公共的)的服务
> 
> 个人觉得你这种情况，就得用Group去实现隔离，看Nacos的产品约定，命名空间就是租户隔离的概念，强隔离


有相关的文档说明吗?我看了一下github和官网的文档..并没有服务发现的group的相关说明..只有配置的

**Comment by KomachiSion** [comment]
group就是你注册和订阅服务时候的一个标签， 在nacos里面 group的概念是一致的，和配置是同样的意义。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
