### ISSUE TITLE
配置详情页，版本对比功能无法使用

### ISSUE THREAD

**Issue by l1141806406** [alibaba/nacos#8871]
配置详情页，版本对比功能，点击后无反应，报错500，疑似参数名问题，2.0.4、2.1.0都存在此问题。1.x版本无此问题
<img width="381" alt="image" src="https://user-images.githubusercontent.com/44897903/182657005-4b61e190-57af-4ba6-a4d4-98bd1c0b5c1e.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/44897903/182657157-17f5588a-9146-46e7-ae56-492d334d1f5c.png">

**Comment by chenhao26-nineteen** [comment]
> 配置详情页，版本对比功能，点击后无反应，报错500，疑似参数名问题，2.0.4、2.1.0都存在此问题。1.x版本无此问题 <img alt="image" width="381" src="https://user-images.githubusercontent.com/44897903/182657005-4b61e190-57af-4ba6-a4d4-98bd1c0b5c1e.png"> <img alt="image" width="790" src="https://user-images.githubusercontent.com/44897903/182657157-17f5588a-9146-46e7-ae56-492d334d1f5c.png">

I can't reproduce it locally. Can you provide specific configuration text

**Comment by KomachiSion** [comment]
清理一下浏览器缓存再试呢

**Comment by l1141806406** [comment]
> 清理一下浏览器缓存再试呢

没用，以找过多个同事，都能复现
官方的试用地址也这样，也能排除安装部署问题http://console.nacos.io/nacos/

**Comment by wuchubuzai2018** [comment]
我本地2.1版本到提示的是错误信息为：caused: Incorrect result size: expected 1, actual 0;这个错误：
后端源码如下：
`  String sqlFetchRows = "SELECT nid,data_id,group_id,tenant_id,app_name,content,md5,src_user,src_ip,op_type,gmt_create,gmt_modified FROM his_config_info WHERE nid = (SELECT max(nid) FROM his_config_info WHERE id = ?) ";
        try {
            ConfigHistoryInfo historyInfo = jt
                    .queryForObject(sqlFetchRows, new Object[] {id}, HISTORY_DETAIL_ROW_MAPPER);
            return historyInfo;
        } catch (DataAccessException e) {
            e.printStackTrace();
            LogUtil.FATAL_LOG.error("[detail-previous-config-history] error, id:{}", new Object[] {id}, e);
            throw e;
        }`
经过我的测试发现，queryForObject底层方法的前提是必须返回一条数据，没有数据就报错。
而当第一次添加配置以后，此时查看版本对比会出现报错，业务本身是没有历史版本的。第二次修改以后会正常出现

不知道楼主的问题，是否和这个相似，建议测试下第一次发布配置和第二次修改配置后，该问题是否存在。如果第二次修改后，问题不存在，那应该就是我说的这个问题。
我本地将queryForObject方法更改为query方法后可以解决，然后看到BaseDatabaseOperate类是通过对异常的拦截处理的也可以解决。

可以解决。
` public ConfigHistoryInfo detailPreviousConfigHistory(Long id) {
        String sqlFetchRows = "SELECT nid,data_id,group_id,tenant_id,app_name,content,md5,src_user,src_ip,op_type,gmt_create,gmt_modified FROM his_config_info WHERE nid = (SELECT max(nid) FROM his_config_info WHERE id = ?) ";
        try {
//            List<ConfigHistoryInfo> list = jt.query(sqlFetchRows, new Object[]{id}, HISTORY_DETAIL_ROW_MAPPER);
//            if (CollectionUtils.isNotEmpty(list)){
//                return list.get(0);
//            }
//            return null;
            ConfigHistoryInfo info = jt.queryForObject(sqlFetchRows, new Object[]{id}, HISTORY_DETAIL_ROW_MAPPER);
            return info;
        } catch (IncorrectResultSizeDataAccessException e) {
            return null;
        } catch (DataAccessException e) {
            e.printStackTrace();
            LogUtil.FATAL_LOG.error("[detail-previous-config-history] error, id:{}", new Object[] {id}, e);
            throw e;
        }
    }`

我是否可以提交个PR呢，增加下这个异常方式的返回NULL

**Comment by l1141806406** [comment]
我今天刚试了一下，210版本没有问题

**Comment by farhad663** [comment]
Hello .is any body communitie with me 


Sent from Yahoo Mail for iPhone


On Wednesday, August 3, 2022, 8:42 PM, l1141806406 ***@***.***> wrote:




配置详情页，版本对比功能，点击后无反应，报错500，疑似参数名问题，2.0.4、2.1.0都存在此问题。1.x版本无此问题
