### ISSUE TITLE
配置管理-历史版本-自定义保留时间

### ISSUE THREAD

**Issue by zhangjundong1992** [alibaba/nacos#8872]
能否增加<配置管理-历史版本-自定义保留时间>功能，当前支持保留30天的历史纪录

**Comment by wuchubuzai2018** [comment]
看后端代码中DumpService类删除的时候是支持参数的好像， String val = EnvUtil.getProperty("nacos.config.retention.days");，尝试添加下nacos.config.retention.days这个启动属性，这个默认是30

**Comment by zhangjundong1992** [comment]
> 

谢谢，我尝试一下

**Comment by zhangjundong1992** [comment]
> 看后端代码中DumpService类删除的时候是支持参数的好像， String val = EnvUtil.getProperty("nacos.config.retention.days");，尝试添加下nacos.config.retention.days这个启动属性，这个默认是30

谢谢你的答复，我尝试一下。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
