### ISSUE TITLE
权限控制UI优化和权限控制逻辑冲突问题

### ISSUE THREAD

**Issue by zhangjundong1992** [alibaba/nacos#8873]
权限控制UI优化：
1、角色管理和权限管理选项下，能否将相同角色名合并为一个单元格
2、权限管理选项下，支持对某一资源权限的修改，而不是只支持删除和添加操作
权限控制逻辑冲突问题给：
1、角色对特定资源可以同时添加只读和读写权限，存在逻辑上的冲突

**Comment by KomachiSion** [comment]
nacos默认实现的权限控制是 nacos鉴权插件的默认实现demo， 只是简单实现了鉴权能力， 主要一定程度上保护产品错用和弱安全能力。 如果对鉴权有比较高的要求，建议开发自定义鉴权插件来对接自己的鉴权系统，以达到满足特定需求和高安全性的要求。

**Comment by zhangjundong1992** [comment]
> nacos默认实现的权限控制是 nacos鉴权插件的默认实现demo， 只是简单实现了鉴权能力， 主要一定程度上保护产品错用和弱安全能力。 如果对鉴权有比较高的要求，建议开发自定义鉴权插件来对接自己的鉴权系统，以达到满足特定需求和高安全性的要求。

好的，谢谢
