### ISSUE TITLE
2.1.0版本无法使用自带的derby数据库组建集群

### ISSUE THREAD

**Issue by luxiao0000** [alibaba/nacos#8875]
2.1.0版本使用derby数据库，组建三点集群后，后台日志一堆报错，使用mysql没问题
2.0.4一切正常

**Comment by l1141806406** [comment]
![image](https://user-images.githubusercontent.com/44897903/182809289-6574ba01-c66e-47ee-aa16-103b1f2c773f.png)
![image](https://user-images.githubusercontent.com/44897903/182809304-e0847a6a-05f2-400f-8bdf-98b55d884bc9.png)

**Comment by wuchubuzai2018** [comment]
derby不是集中部署模式的数据库，你集群有3个节点，就是3个derby数据库

**Comment by l1141806406** [comment]
> derby不是集中部署模式的数据库，你集群有3个节点，就是3个derby数据库

一模一样的操作，204可以，210不行

**Comment by wuchubuzai2018** [comment]
我发现了，你的第一张截图是有问题的，错误中的错误是外部数据源的类报的，不是Derby报的错误，说明了你报错的这个数据源使用的是非Derby的，建议你仔细看看自己的环境

**Comment by l1141806406** [comment]
> 我发现了，你的第一张截图是有问题的，错误中的错误是外部数据源的类报的，不是Derby报的错误，说明了你报错的这个数据源使用的是非Derby的，建议你仔细看看自己的环境

你可以亲自用210版本并且用自带的库，组建集群试试

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/182984246-94897356-3248-402e-a261-3fb40678da27.png)
外部数据源报错，说明没用上derby，derby的类是EmbbedStoragePersistService
