### ISSUE TITLE
can fix SNYK-JAVA-COMALIBABANACOS-2942437 ?

### ISSUE THREAD

**Issue by caozhiyuan** [alibaba/nacos#8878]
**Describe the bug**
can fix SNYK-JAVA-COMALIBABANACOS-2942437 ? (https://security.snyk.io/vuln/SNYK-JAVA-COMALIBABANACOS-2942437)

**Expected behavior**
no [Snyk Vulnerability](https://security.snyk.io/vuln)

**Actually behavior**
Snyk Vulnerability

**Comment by KomachiSion** [comment]
I don't think it's Vulnerability.

firsts, the token is same as username and password, the leak of token just like the leak of username and password. You should ban the username and use others.
seconds, the default impl of auth is just a demo of nacos auth plugin, only can protect wrong usage not include high security which has shown in auth document, If you has high security request, you can implement your auth plugin.

**Comment by caozhiyuan** [comment]
@KomachiSion this is problem ? https://github.com/alibaba/nacos/issues/7182

**Comment by caozhiyuan** [comment]
@KomachiSion who can communicate SNYK close this https://security.snyk.io/vuln/SNYK-JAVA-COMALIBABANACOS-2942437)?

**Comment by KomachiSion** [comment]
I don't know how to close this, but I see the original issue is no one focus it and the author has provider the solution -- change the default token.

**Comment by caozhiyuan** [comment]
@KomachiSion i had feedback to SNYK , Vulnerability had closed.
