### ISSUE TITLE
1.4的启动的了，而2.1.0不行

### ISSUE THREAD

**Issue by bladetom** [alibaba/nacos#8879]
![image](https://user-images.githubusercontent.com/40118310/182894978-4cf98ea2-0056-45ab-9c8f-39cdc01a5a7e.png)
![image](https://user-images.githubusercontent.com/40118310/182895168-62e03323-baa8-437b-9ce8-e3b02c645a1c.png)

**nacos 单机模式，我用2.1.0启动不了，一直缺少xxbean，相反1.4可以启动**

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/182984052-f6a23f3b-3768-4fee-a662-185ae42d4165.png)
端口冲突了。
