### ISSUE TITLE
注册中心雪崩预警及恢复手段

### ISSUE THREAD

**Issue by whl12345** [alibaba/nacos#8884]
注册中心雪崩现象：
1. 部分Nacos Server节点宕机
2. 整体注册实例数突降50%左右，整个集群实例数存在不一致且在一定范围抖动

3个问题？
1. 如何预警雪崩，除了压测手段，能否通过相关指标提前预警，就目前现象没有明确指标能定位到雪崩的时间点，往往性能指标没有明显征兆，突然JVM内存发生异常波动，接着就触发雪崩缺少缓冲时间
2. 如果出现雪崩，一般采用什么手段能快速恢复，这时候集群已经异常难以通过重启恢复，除非另起一份备份集群资源，或者临时把流量断掉
3. 在对Nacos集群进行压测过程中，存在脉冲现象，瞬间启动多个压测客户端，瞬时流量可能直接导致Nacos集群间jraft协议问题，导致异常，jraft相比于1.0 非标准raft是否稳定性/负载能力更差

**Comment by hujun-w-2** [comment]
你是哪个版本？

**Comment by whl12345** [comment]
2.1.0 集群+ 1.1.4客户端

**Comment by whl12345** [comment]
![Uploading jvm.png…]()

**Comment by hujun-w-2** [comment]
1.确定是持久化实例吗？
2.集群雪崩时刻相关日志呢可以贴一下？

**Comment by whl12345** [comment]
> 1.确定是持久化实例吗？ 2.集群雪崩时刻相关日志呢可以贴一下？

1. 都是临时注册实例

**Comment by whl12345** [comment]
<img width="1728" alt="截屏2022-08-06 上午10 53 41" src="https://user-images.githubusercontent.com/36367435/183230706-ac270677-c3de-46e9-a3d0-6c4ed2a59e23.png">

**Comment by whl12345** [comment]
<img width="1728" alt="截屏2022-08-06 上午10 59 49" src="https://user-images.githubusercontent.com/36367435/183230841-213f623b-8165-430d-ba19-ca424e7387b2.png">

**Comment by whl12345** [comment]
<img width="1728" alt="截屏2022-08-06 上午11 02 53" src="https://user-images.githubusercontent.com/36367435/183231018-6ba119ea-e57d-4f09-b411-5a97c8afde48.png">

**Comment by whl12345** [comment]
外部注册实例数是6w开始一直稳定，到雪崩的点突然不稳定了，然后JVM也出现不稳定波动，频繁MajorGC
注册实例数：6W，服务数：6k
注册实例：dubbo服务注册实例
nacos服务端版本：2.1.0
nacos客户端版本：1.1.4
集群硬件资源：11节点16核32G
JVM参数：-Xms22g -Xmx22g -Xmn4g -XX:+UseG1GC -XX:-TieredCompilation -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=45 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:-UseCompressedClassPointers -XX:ReservedCodeCacheSize=256m -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4

怀疑集群压力达到峰值负载，jvm内存回收引发的问题？我看随之Old Gen增长到某一时刻突然就崩了

**Comment by KomachiSion** [comment]
你客户端版本太低了，享受不到2.0带来的性能释放，建议升级到2.1版本的客户端。

**Comment by KomachiSion** [comment]
@whl12345 any more informations?
