### ISSUE TITLE
ConfigService getConfig returns old value

### ISSUE THREAD

**Issue by 123liuziming** [alibaba/nacos#8886]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I did the following series of operations:
1. publish a config to nacos
2. read the value of the config
but I found the value I read is still old, which is not the same as the value in step 1. I want to know is there a way to get the newest config value in nacos?

**Comment by chenhao26-nineteen** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
> I did the following series of operations:
> 
> 1. publish a config to nacos
> 2. read the value of the config
>    but I found the value I read is still old, which is not the same as the value in step 1. I want to know is there a way to get the newest config value in nacos?

Can you provide some detailed information?

**Comment by 123liuziming** [comment]
For example
```
String conent = "test";
configService.publishConfig(dataId, null, content);
String newContent = configService.getConfig(dataId, null, 5000);
```
The newContent sometimes is equal to the origin content. The reason is that I use 3-Node Nacos, the config needs to sync between the nodes, so I may read out the old config content.  I want to know is there a way to get the correct config in nacos after I publish a config.

**Comment by wuchubuzai2018** [comment]
感觉你这个应该的判断publishConfig这个方法的返回结果吧，有可能这个返回结果是失败的情况

**Comment by 123liuziming** [comment]
> 感觉你这个应该的判断publishConfig这个方法的返回结果吧，有可能这个返回结果是失败的情况

并没有，是正常publish的。实际的代码里是做了这个判断的，这里只是个demo

**Comment by KomachiSion** [comment]
publish之后立刻去get并不一定能获取到最新值。 建议使用监听listenConfig。

**Comment by 123liuziming** [comment]
能否提供一个新的API以保证GET能拿到最新的配置呢

**Comment by KomachiSion** [comment]
监听listenConfig即可

**Comment by 123liuziming** [comment]
好吧，我这个需求可能需要主动拉能拉到最新的配置，看来还是nacos推过来。
