### ISSUE TITLE
Create a new namespace and set the namespace ID to public. At this time, the service registration will be registered in both namespaces 

### ISSUE THREAD

**Issue by chenhao26-nineteen** [alibaba/nacos#8889]
**Describe the bug**
Create a new namespace and set the namespace ID to public. At this time, the service registration will be registered in both namespaces (when the default public space is empty, it is also public by default)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.1.0]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
refer to #3525
