### ISSUE TITLE
命名规范

### ISSUE THREAD

**Issue by liushaoyu-soft** [alibaba/nacos#8895]
**建议：包名在阿里Java开发手册里不是要求统一单数形式吗？**

![image](https://user-images.githubusercontent.com/36216908/183321988-d6a78211-c53d-476b-b3bd-2673dd23f196.png)
![image](https://user-images.githubusercontent.com/36216908/183322012-57d6e794-7c62-4ffc-a990-fdb17fe303d0.png)

**Comment by KomachiSion** [comment]
请移交到spring cloud alibaba 社区
