### ISSUE TITLE
m1芯片 docker按照官网方式执行报错 Function not implemented

### ISSUE THREAD

**Issue by debugsw** [alibaba/nacos#8898]
nacos-standalone-mysql | 16:15:05.900 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
nacos-standalone-mysql | 16:15:05.901 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
nacos-standalone-mysql | 16:15:05.901 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
nacos-standalone-mysql | 16:15:08.586 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
nacos-standalone-mysql | com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: ErrCode:500, ErrMsg:Function not implemented
nacos-standalone-mysql |        at com.alibaba.nacos.core.listener.StartingApplicationListener.loadPreProperties(StartingApplicationListener.java:161)
nacos-standalone-mysql |        at com.alibaba.nacos.core.listener.StartingApplicationListener.environmentPrepared(StartingApplicationListener.java:100)
nacos-standalone-mysql |        at com.alibaba.nacos.core.code.SpringApplicationRunListener.environmentPrepared(SpringApplicationRunListener.java:65)
nacos-standalone-mysql |        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
nacos-standalone-mysql |        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
nacos-standalone-mysql |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
nacos-standalone-mysql |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
nacos-standalone-mysql |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
nacos-standalone-mysql |        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos-standalone-mysql |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql |        at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql |        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos-standalone-mysql |        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos-standalone-mysql |        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos-standalone-mysql |        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
nacos-standalone-mysql | Caused by: com.alibaba.nacos.api.exception.NacosException: java.io.IOException: Function not implemented
nacos-standalone-mysql |        at com.alibaba.nacos.sys.file.WatchFileCenter$WatchDirJob.<init>(WatchFileCenter.java:189)
nacos-standalone-mysql |        at com.alibaba.nacos.sys.file.WatchFileCenter.registerWatcher(WatchFileCenter.java:97)
nacos-standalone-mysql |        at com.alibaba.nacos.core.listener.StartingApplicationListener.registerWatcher(StartingApplicationListener.java:167)
nacos-standalone-mysql |        at com.alibaba.nacos.core.listener.StartingApplicationListener.loadPreProperties(StartingApplicationListener.java:159)
nacos-standalone-mysql |        ... 16 common frames omitted
nacos-standalone-mysql | Caused by: java.io.IOException: Function not implemented
nacos-standalone-mysql |        at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
nacos-standalone-mysql |        at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
nacos-standalone-mysql |        at com.alibaba.nacos.sys.file.WatchFileCenter$WatchDirJob.<init>(WatchFileCenter.java:184)
nacos-standalone-mysql |        ... 19 common frames omitted
nacos-standalone-mysql | 16:15:08.597 [Thread-4] WARN com.alibaba.nacos.common.executor.ThreadPoolManager - [ThreadPoolManager] Start destroying ThreadPool
nacos-standalone-mysql | 16:15:08.600 [Thread-4] WARN com.alibaba.nacos.common.executor.ThreadPoolManager - [ThreadPoolManager] Destruction of the end

**Comment by KomachiSion** [comment]
nacos-standalone-mysql | Caused by: java.io.IOException: Function not implemented
nacos-standalone-mysql | at sun.nio.fs.LinuxWatchService.(LinuxWatchService.java:64)

你用的jdk版本不支持m1芯片

**Comment by chenshun00** [comment]
使用oracle的jdk就可以了

**Comment by debugsw** [comment]
> 使用oracle的jdk就可以了

意思是nacos官网镜像中的jdk版本不支持吗？

**Comment by debugsw** [comment]
> nacos-独立-mysql | 原因：java.io.IOException: Function not implemented nacos-standalone-mysql | 在 sun.nio.fs.LinuxWatchService.(LinuxWatchService.java:64)
> 
> 你用的jdk版本不支持m1芯片

意思是nacos官网镜像中的jdk版本不支持吗？

> nacos-standalone-mysql | Caused by: java.io.IOException: Function not implemented nacos-standalone-mysql | at sun.nio.fs.LinuxWatchService.(LinuxWatchService.java:64)
> 
> 你用的jdk版本不支持m1芯片



> nacos-standalone-mysql | Caused by: java.io.IOException: Function not implemented nacos-standalone-mysql | at sun.nio.fs.LinuxWatchService.(LinuxWatchService.java:64)
> 
> 你用的jdk版本不支持m1芯片

是我本机的jdk不支持，还是nacos镜像中引入的jdk不支持昵？

**Comment by KomachiSion** [comment]
应该你docker镜像中的jdk，不支持m1芯片架构。 nacos-docker社区好像有提供过一个m1可用的版本，好像叫-slim

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
