### ISSUE TITLE
0.9.0 cluster mode,There is a high probability that configuration cannot be updated to Java application.

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#890]
env:
nacos 0.9.0 , windows server 2016,  jdk11, spring cloud Finchley.SR2, spring cloud alibaba 0.2.1.RELEASE, spring-boot-starter-parent 2.0.7.RELEASE, mysql 5.7.

During the update process, the database was successfully updated.

when config website update the config content.
if standalone mode, it's ok.
if cluster mode only 1 node, it's ok.
if cluster mode 2,3 or 4 nodes, There is a high probability that configuration content cannot be updated to Java application. then restart the nacos server,java application will get the newest configuration content.

**Comment by sundong1982** [comment]
env:
ubuntu18,jdk8
if cluster mode only 3 nodes. it's ok.

The problem is with windows or jdk11。

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
