### ISSUE TITLE
Nacos的SLA是如何定义以及计算的

### ISSUE THREAD

**Issue by Maksim-lk** [alibaba/nacos#8903]
![image](https://user-images.githubusercontent.com/53926693/183408103-15d6a3b7-2182-4e34-b1c0-451c2af196c2.png)

上图摘自《Nacos架构&原理》，对此有如下疑问：
1.具体指标中，1w级、10w级和100w级别与1w实例的具体含义是什么？
2.只需关注Nacos的推送功能吗？
3.x S秒内，xx.xx%推送完成的具体计算方法是？

另，社区是否有可参考的SLA指标体系？

**Comment by KomachiSion** [comment]
1. 服务实例， 不同应用框架可能不同。
2. 推送是最高等级的SLA指标
3. 实例变更后，x秒内，xx.xx%的订阅者收到新地址

**Comment by KomachiSion** [comment]
> 另，社区是否有可参考的SLA指标体系？

SLA一般是针对企业服务产品的指标，社区自建的话根据自己需求定义SLA。
