### ISSUE TITLE
Exception 'java.io.IOException' is never thrown in the method [nacos-common]

### ISSUE THREAD

**Issue by liushaoyu-soft** [alibaba/nacos#8906]
Exception 'java.io.IOException' is never thrown in the method [nacos-common]

**Comment by KomachiSion** [comment]
Please provide more information about your issue.

**Comment by liushaoyu-soft** [comment]
> Please provide more information about your issue.

The exception has been caught manually and the method body will not throw any more exceptions,
method: com.alibaba.nacos.common.utils.IoUtils#tryDecompress(java.io.InputStream)
