### ISSUE TITLE
consistency缺少entity包

### ISSUE THREAD

**Issue by harimuery** [alibaba/nacos#8918]
<img width="920" alt="Snipaste_2022-08-10_09-40-26" src="https://user-images.githubusercontent.com/38996428/183791800-eedc4235-1c1c-4da3-9e84-043574a81e5a.png">
consistency模块缺少entity包，导致项目启动不了

**Comment by chenhao26-nineteen** [comment]
> <img alt="Snipaste_2022-08-10_09-40-26" width="920" src="https://user-images.githubusercontent.com/38996428/183791800-eedc4235-1c1c-4da3-9e84-043574a81e5a.png">
> 
> consistency模块缺少entity包，导致项目启动不了

这个包目录是由 protobuf 在编译时自动生成，可以通过 mvn compile 来自动生成这些代码。如果使用的是
IDEA，也可以使用IDEA的protobuf插件。

**Comment by KomachiSion** [comment]
duplicate with other many issue
