### ISSUE TITLE
linux上部署2.1版本，在服务器上运行flink程序，无法获取到nacos的最近配置，但程序在本地就可以获取到。服务器上网络是通的

### ISSUE THREAD

**Issue by Cap-DP** [alibaba/nacos#8919]
Flink程序部署在dolphinscheduler服务器，nacos在另外的服务器上，同属于一个集群。网络都是通的。但不管是在dolphinscheduler客户端上提交任务，还是在服务器上提交，都无法获取nacos更改后的配置，要重启任务很多次才能获取到。但是如果程序在本地运行，在nacos上更改配置后，本地程序就可以及时获取到。

**Comment by KomachiSion** [comment]
那说明不是nacos本身的问题，应该是前者链路过程出现问题，得自行排查一下哪个链路断了。

**Comment by Cap-DP** [comment]
> 那说明不是nacos本身的问题，应该是前者链路过程出现问题，得自行排查一下哪个链路断了。

**Comment by Cap-DP** [comment]
> 那说明不是nacos本身的问题，应该是前者链路过程出现问题，得自行排查一下哪个链路断了。

网络通，程序也不报错，可以获取到，但获取不到新配置。比如将使用旧配置的程序停止，然后在nacos上更改配置，在启动程序，这时候程序获取的还是旧配置。

**Comment by KomachiSion** [comment]
nacos的客户端日志和本地缓存文件查一下，是不是新的。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
