### ISSUE TITLE
Optimizing abstract class Subscriber suggestion

### ISSUE THREAD

**Issue by karsonto** [alibaba/nacos#8924]
I found that many Subscriber implementation classes obtain subscribeType as generic classes during reading the source code. The abstract class Subscriber can optimize the subscribeType() method to obtain the generic class of subclasses by default, reducing unnecessary code in the project.
example:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/31433550/183824968-d6ce61ce-9963-477a-b988-233023d440e2.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/31433550/183825094-c2e3d2f6-6be8-4f7e-965b-fa6bf126aac5.png">

**Comment by KomachiSion** [comment]
I comment some reason in PR #8932. I think we should has some discuss first in issue.

**Comment by vergilyn** [comment]
i like old way, but there is a doubt.

Why is the method signed with  `public Class<? extends Event> subscribeEvent()` instead of `public <T> Class<T> subscribeEvent()`?

it mean i can:
```
new Subscriber<CustomPublisherEvent>() {
	@Override
	public void onEvent(CustomPublisherEvent event) {

	}

	@Override
	public Class<? extends Event> subscribeType() {
		return XxxEvent.class;
	}
}
```

**Comment by karsonto** [comment]
I think  most of the listener event types are the same as the processing event type. I can't find any special case when I read the source code.So I submitted PR.

**Comment by karsonto** [comment]
The next time we can  develop subscriber scanner to automatically register in NotifyCenter, just like spring.

**Comment by KomachiSion** [comment]
What I am more worried about is that through automatic scanning, a lot of information may be hidden, which developer reader hard. And there may be problems with parent and child classes.
