### ISSUE TITLE
Cannot be dynamically refreshed in springboot2.1.3release

### ISSUE THREAD

**Issue by 91wangmeng** [alibaba/nacos#893]
## Issue Description
无法动态刷新
Unable to refresh dynamically

To Reproduce
用最新的springboot版本,配置无法动态刷新
With the latest springboot version, the configuration cannot be dynamically refreshed

在springboot 2.1.3.release版本中,由于EventListenerMethodProcessor类中的processBean()方法内进行Eventlistener注册时增加了!isSpringContainerClass(targetType)判断,过滤掉了org.springframework.cloud.endpoint.event.RefreshEventListener类,导致配置文件修改后触发的RefreshEvent无法触发刷新操作,从而导致动态刷新功能无法使用

In the springboot 2.1.3.release version, due to the processBean() method in the EventListenerMethodProcessor class, the Eventlistener is registered with the addition of !isSpringContainerClass(targetType), which is filtered.
      org.springframework.cloud.endpoint.event.RefreshEventListener class, which causes the RefreshEvent triggered after the configuration file modification cannot trigger the refresh operation, resulting in the dynamic refresh function being unavailable.

我目前的处理方式是 自定义一个EventListener,用以绕过`isSpringContainerClass`判断
```
@Bean
    @ConditionalOnClass(ContextRefresher.class)
    public RefreshEventListener getNacosConfigListener(ContextRefresher contextRefresher;) {
        return new NacosEventListener(contextRefresher);
    }

    private class NacosEventListener extends RefreshEventListener {
        NacosEventListener(ContextRefresher refresh) {
            super(refresh);
        }
    }
```

**Comment by maojx0630** [comment]
cloud  G.sr1?

**Comment by fangjian0423** [comment]
which version of nacos-config-starter you are using? 

Please use 0.9.0.RELEASE.

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by 91wangmeng** [comment]
@fangjian0423 spring-cloud-starter-alibaba-nacos-config 0.2.1.RELEASE  应该版本比较老了   我升级一下吧,我用的时候这个版本是最新的了

**Comment by qdlake** [comment]
按NacosEventListener这种方式，EnvironmentChangeEvent会被激发两次
