### ISSUE TITLE
[Bug] 在Nacos集群中若一Nacos实例与其他实例在不同局域网中，此实例会被注册成两个节点

### ISSUE THREAD

**Issue by lewis-wu** [alibaba/nacos#8938]
由于Nacos集群的不同实例在不同的局域网中，所以集群节点配置文件cluster.conf中的IP应该配置成公网IP。
但每个NacosServer启动时又会将自己的IP注册写入到cluster.conf文件中，此时的IP是通过InetUtils.getSelfIP()获取的内网IP，
这里的内网IP与原始文件cluster.conf中的公网IP肯定不一样，所以NacosServercluster.conf文件会追加一条内网自己的内网IP.
而服务消费者也会获取到包含这个的内网IP服务实例列表, 若是负载均衡刚好路由到这个内网IP, 则会服务调用失败，因为这个内网IP对外部不可见。

我的想法是在方法ServerMemberManager#init中改进
```java
com.alibaba.nacos.core.cluster.ServerMemberManager#init
//代码
 this.localAddress = InetUtils.getSelfIP() + ":" + port;
//替换成这个
String usedSelfIP = EnvUtil.getProperty("nacos.inetutils.ip-address", String.class, InetUtils.getSelfIP());
        this.localAddress = usedSelfIP + ":" + port;
```

**Comment by lewis-wu** [comment]
我提交了一个PR,希望可以合并到主线分支中 [#8939](https://github.com/alibaba/nacos/pull/8939)

**Comment by KomachiSion** [comment]
InetUtil 在第一次加载时会自动获取nacos.inetutils.ip-address， 不需要在ServerMemberMamagr中获取。

**Comment by KomachiSion** [comment]
另外从描述来看， 服务消费者为什么会获取到nacos 服务端的ip来做负载均衡？ 没理解你的场景

**Comment by lewis-wu** [comment]
> 另外从描述来看， 服务消费者为什么会获取到nacos 服务端的ip来做负载均衡？ 没理解你的场景
不好意思，配置的问题。我在application.yaml中设置nacos.inetutils.ip-address属性后，没有将之前NacosServer自动写入到cluster.conf的内网IP删除

**Comment by lewis-wu** [comment]
> 另外从描述来看， 服务消费者为什么会获取到nacos 服务端的ip来做负载均衡？ 没理解你的场景

不好意思，配置的问题。我在application.yaml中设置nacos.inetutils.ip-address属性后，没有将之前NacosServer自动写入到cluster.conf的内网IP删除
