### ISSUE TITLE
springboot2.4.10集成undertow2.2.10，kill -2 停机NacosWatch报异常UT015023

### ISSUE THREAD

**Issue by lijinliang83** [alibaba/nacos#8946]
springboot2.4.10集成undertow2.2.10，使用kill -2 进行服务停机。NacosWatch报error  namingService unsubscribe failed 异常为 UT015023 this context has been already destroyed。使用SpringCloud-Nacos版本是2021.1  nacos客户端是1.4.1

**Comment by KomachiSion** [comment]
应该不是nacos的问题，应用框架关闭的时候先关闭了nacos客户端，再注销服务肯定要报错.

**Comment by mingying57** [comment]
perfect answer:
http://www.metebase.top/?id=8
