### ISSUE TITLE
Nacos 2.1.1 登陆提示权限认证失败

### ISSUE THREAD

**Issue by shaonx** [alibaba/nacos#8949]
**Describe the bug**
Nacos 2.1.1 登陆提示权限认证失败，没有public命名空间权限。

**Expected behavior**
希望被授权的用户只能看到授权的命名空间信息，而不是所有的命名空间

**How to Reproduce**
1. 创建a_namespace 命名空间
2. 创建a 用户
3. 授权a_namespace给a用户
4. 登陆a用户,提示没有public命名空间权限

**Desktop (please complete the following information):**
 - OS: centos
 - Version  nacos-server 2.1.1
 - Module naming

**Additional context**

**Comment by chenhao26-nineteen** [comment]
> **Describe the bug** Nacos 2.1.1 登陆提示权限认证失败，没有public命名空间权限。
> 
> **Expected behavior** 希望被授权的用户只能看到授权的命名空间信息，而不是所有的命名空间
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. 创建a_namespace 命名空间
> 2. 创建a 用户
> 3. 授权a_namespace给a用户
> 4. 登陆a用户,提示没有public命名空间权限
> 
> **Desktop (please complete the following information):**
> 
> * OS: centos
> * Version  nacos-server 2.1.1
> * Module naming
> 
> **Additional context** Add any other context about the problem here.

默认没有public权限 需要授权

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
