### ISSUE TITLE
nacos client keeps printing logs “config changed”

### ISSUE THREAD

**Issue by li-zheng-hao** [alibaba/nacos#8954]
## issue link
i report this issue  in nacos C# sdk repo, link is [https://github.com/nacos-group/nacos-sdk-csharp/issues/226](https://github.com/nacos-group/nacos-sdk-csharp/issues/226)

## steps to reproduce

> env: windows 10, docker desktop

1. deploy nacos server: `docker run --name nacos-quick -e MODE=standalone -p 8848:8848 -p 9848:9848 -d nacos/nacos-server:2.0.2`
2. create an asp.net core webapi project,choose .net 6 version
3. use nuget to install `nacos-sdk-csharp.AspNetCore` 1.3.4 version  and `nacos-sdk-csharp.Extensions.Configuration` 1.3.4 version  
4. create a config in nacos web page with namespace `public`, group `DEFAULT_GROUP`
5. modify `appsettings.json` file refer to the link above
6. run webapi project and a lots of logs `config changed` can be seen in console window

**Comment by catcherwong** [comment]
It seems that you have solved this issue.

This issue can be closed.

**Comment by KomachiSion** [comment]
Your sdk should not set namespace = public, beacuse the namespace id is not `public` but ``.

**Comment by li-zheng-hao** [comment]
@KomachiSion thanks, i got it
