### ISSUE TITLE
nacos v2.1.1 docker 启动时报错

### ISSUE THREAD

**Issue by qsj-git** [alibaba/nacos#8957]
Describe the bug
fail to start nacos at 2.1.1 version for docker。

Actually behavior

2022-08-12 15:29:46,826 INFO 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2022-08-12 15:29:46,894 ERROR 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'server.tomcat.basedir' to java.io.File:

    Property: server.tomcat.basedir
    Value: 
    Origin: InputStream resource [resource loaded through InputStream] - 34:0
    Reason: failed to convert java.lang.String to java.io.File (caused by java.lang.IllegalStateException: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/)

Action:

Update your application's configuration

**Comment by qsj-git** [comment]
我甚至都没改如何文件

**Comment by KomachiSion** [comment]
duplicate with #8960
