### ISSUE TITLE
关于NacosEnv的疑问？

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#8963]
**Describe the question**
NacosEnv的目的是为了统一客户端获取参数的方式，我看到Nacos Server端也是同样的使用了三种获取参数的方式，目前NacosEnv的实现在Client模块，为什么不放在Common模块统一使用NacosEnv的方式获取参数呢？如果放在Client模块中，那么对于一些客户端插件、Common中的一些公共逻辑，无法使用NacosEnv，那么Client端读取顺序的设置并不会对所有的参数生效，我感觉有点不太合理。

**Comment by onewe** [comment]
目前这个还在开发阶段,还有很多不完善的地方,为了不扩大印象面,先放在 client这里。

**Comment by stone-98** [comment]
> 目前这个还在开发阶段,还有很多不完善的地方,为了不扩大影响面,先放在 client这里。

好的，我明白了，感谢回复。
