### ISSUE TITLE
绕过权限仍可创建用户

### ISSUE THREAD

**Issue by niuren930** [alibaba/nacos#8968]
最新版本
![image](https://user-images.githubusercontent.com/111275223/184605279-62cc8e91-bcae-407a-bae4-f4349fc24ee4.png)
![image](https://user-images.githubusercontent.com/111275223/184605299-0667d30c-bcb0-4a20-a668-b243a486ffb4.png)

**Comment by KomachiSion** [comment]
看文档，打开鉴权功能。

**Comment by niuren930** [comment]
> 看文档，打开鉴权功能。

看到了，谢谢哈
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
