### ISSUE TITLE
nacos-server 2.0.1 关闭doubleWrite后,升级到2.x模式集群, 服务无限创建

### ISSUE THREAD

**Issue by zhangpan-soft** [alibaba/nacos#8970]
![image](https://user-images.githubusercontent.com/66060154/184625913-46cbf09e-a19c-4d0c-99d7-5d8ea91cc524.png)

nacos2.0.1,在关闭doubleWrite后,集群升级到2.x模式, 但是因为我们客户端是新老版本,有1.x,2.x,此时再次打开doubleWrite, 但是,1.x版本的客户端注册会出现无限注册现象. 导致服务一直集群实例数一直不断升高, 可达几百之多.

**Comment by steverao** [comment]
Spring Cloud Alibaba包装的Nacos注册逻辑是这个位置：
```
@Override
	public void register(Registration registration) {

		if (StringUtils.isEmpty(registration.getServiceId())) {
			log.warn("No service to register for nacos client...");
			return;
		}

		NamingService namingService = namingService();
		String serviceId = registration.getServiceId();
		String group = nacosDiscoveryProperties.getGroup();

		Instance instance = getNacosInstanceFromRegistration(registration);

		try {
			namingService.registerInstance(serviceId, group, instance);
			log.info("nacos registry, {} {} {}:{} register finished", group, serviceId,
					instance.getIp(), instance.getPort());
		}
		catch (Exception e) {
			if (nacosDiscoveryProperties.isFailFast()) {
				log.error("nacos registry, {} register failed...{},", serviceId,
						registration.toString(), e);
				rethrowRuntimeException(e);
			}
			else {
				log.warn("Failfast is false. {} register failed...{},", serviceId,
						registration.toString(), e);
			}
		}
	}
```
我们没有处理任何Nacos自身提供的双写逻辑，初步判断这个是一个nacos-client造成的问题，你有没有debug过大致造成大量重复注册的具体代码逻辑是在哪里？

**Comment by KomachiSion** [comment]
尝试后无法复现该问题，能否提供更多信息和日志？

另外能否升级到新版本试试？

**Comment by zhangpan-soft** [comment]
@KomachiSion
将client服务,多次进行重启, 就会复现, 并且client服务要2.x和1.x并存.

**Comment by KomachiSion** [comment]
我不停的启停也没有复现出来，每次启停ip和port都是一致的，会直接覆盖上一次的内容。你看下你不停重启是不是ip或者port变了。

**Comment by zhangpan-soft** [comment]
> 我不停的启停也没有复现出来，每次启停ip和port都是一致的，会直接覆盖上一次的内容。你看下你不停重启是不是ip或者port变了。

是的,每次启动都会更换ip, 就会造成原来已shutdown掉的服务,没有自动去除. 这个最大问题在于, 在nacos最低3节点集群的情况下, 各个节点的数据是不一致的. 比如, a节点是正常的, b节点不正常. 并且这个ip是之前docker的ip,进程已经停了. 所以导致无限的情况出现. 启动多少次就会有多少. 但是有一个节点始终是正常的. 没有去看是否是master正常. 但是,如果是正常的nacos,未设置doubleWrite的情况下, 是没有问题的, 当doubleWrite被设置过一次,就会出问题. 并且始终有一个节点是正常的. 所以我觉得大概率是nacos集群机制的问题,导致各节点数据不一致. 并且是长时间的不一致,还没有什么其他的巡检方法, 去巡检各节点数据是否一致.

**Comment by KomachiSion** [comment]
那有可能是后加入的节点没有正确升级到新版本导致，那可以升级一下服务端版本试试，新版本应该有一些优化。

另外2.1.0之后可以默认关闭以双写模式启动。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
