### ISSUE TITLE
NacosConsole the configuration rollback insert type of console becomes the configuration deletion operation

### ISSUE THREAD

**Issue by chenhao26-nineteen** [alibaba/nacos#8971]
**Describe the bug**

Nacos Console Rollback：
When the rollback type is insert, the rollback will become a delete operation
When the rollback type is update, the normal rollback is an update operation. This logic is a bit convoluted, and it is easy to delete the configuration by mistake.
Recommendation: rollback of configuration of insert type is not allowed

回滚类型为插入时，回滚将成为删除操作
回滚类型为更新时，回滚正常为更新操作。这一块逻辑有点绕，容易误删配置 。
建议：不允许回滚插入类型的配置

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by chenhao26-nineteen** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
duplicate with many old issue.

I think the logic has no problem. you just want to rollback to old version before this operation. so if you rollback the `Insert` version, before you insert, the config is not exist, so delete it.
