### ISSUE TITLE
Not automatically registered to nacos

### ISSUE THREAD

**Issue by leetomlee123** [alibaba/nacos#898]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1.  new SpringApplicationBuilder(DispacherApplication.class).web(WebApplicationType.NONE).run(args);
2. 
3.

**Comment by nkorange** [comment]
More details please.

**Comment by leetomlee123** [comment]
SpringApplication.run(DispacherApplication.class); success
        new SpringApplicationBuilder(DispacherApplication.class).web(WebApplicationType.NONE).run(args); failed

**Comment by leetomlee123** [comment]
can i speak chinese

**Comment by nkorange** [comment]
> can i speak chinese

可以的

**Comment by leetomlee123** [comment]
我就是springboot结合netty写个服务用不到tomcat，所以用  这个启动 new SpringApplicationBuilder(DispacherApplication.class).web(WebApplicationType.NONE).run(args); 就是启动方式不同造成的，会是@EnableDiscoveryClient 没有生效吗

**Comment by nkorange** [comment]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba 你到这里提个issue，这个是SpringCloud客户端使用问题
