### ISSUE TITLE
自定义鉴权插件，打成外部jar包无法加载

### ISSUE THREAD

**Issue by godhth** [alibaba/nacos#8983]
#8947 
#8959 
-Dloader.path=/plugins  我加上了，主要是不生效。不是说不会加的问题。
我把官方的插件打成jar包，用-Dloader.path外部加载都没用。

**Comment by KomachiSion** [comment]
我试了 没问题啊 你是不是spi的services文件没设置或者设置错了

**Comment by godhth** [comment]
设置了，代码应该没问题。因为如果用maven引入，再重新编译nacos是可以正常使用的。
只是放在外部无法正常使用。
jar包如下：
[auth.zip](https://github.com/alibaba/nacos/files/9368023/auth.zip)

-Dloader.path=/plugins用了之后正常启动是没问题。只是 https://github.com/alibaba/nacos/blob/b584531331cc95054964ba4e33984f4cab9e582d/plugin/auth/src/main/java/com/alibaba/nacos/plugin/auth/spi/server/AuthPluginManager.java#L51
这行代码插件加载不进来。
无论是我本地debug启动还是，放linux上启动都没加载进来。

**Comment by YunWZ** [comment]
实在不会的话,可以参考我的[文章](https://github.com/YunWZ/nacos-examples/blob/main/docs/src/main/asciidoc/AuthPlugin.adoc)...

**Comment by godhth** [comment]
感谢老哥
-Dloader.path=没问题，是我的问题。
![image](https://user-images.githubusercontent.com/63696328/185583332-90a4df85-30f5-415c-8bcb-594e77fe280b.png)
官方文档这个有点问题，这个日志只有接口日志。
@YunWZ 这个老哥写的才是正确的
![image](https://user-images.githubusercontent.com/63696328/185583587-7f637d26-a72d-473c-a8b6-2cbb0705b0da.png)
感谢！

**Comment by taxus1** [comment]
@YunWZ 兄台，根据文档https://nacos.io/zh-cn/docs/auth-plugin.html 添加了自定义的鉴权插件，发现只有当nacos.core.auth.system.type的值为nacos和ldap时才能进行登录，但是此时自定义的鉴权插件又没有起作用，如果type值改成自定义插件名字在已经登录过的情况下，重启服务，刷新页面可以进入到自定义插件方法，但是此时如果退出登录后，无法登录，请问下你们有没有遇到过这个问题？还有就是nacos支持自定义登录逻辑吗？

**Comment by YunWZ** [comment]
> @YunWZ 兄台，根据文档https://nacos.io/zh-cn/docs/auth-plugin.html 添加了自定义的鉴权插件，发现只有当nacos.core.auth.system.type的值为nacos和ldap时才能进行登录，但是此时自定义的鉴权插件又没有起作用，如果type值改成自定义插件名字在已经登录过的情况下，重启服务，刷新页面可以进入到自定义插件方法，但是此时如果退出登录后，无法登录，请问下你们有没有遇到过这个问题？还有就是nacos支持自定义登录逻辑吗？

*nacos.core.auth.system.type*的值需要配置成*插件*的名称,配置为`nacos`或者`ldap`能登录是因为服务端默认实现了这两个插件. 
自定义插件时, 需要自己实现登录逻辑.
