### ISSUE TITLE
最新develop分支代码， consistency 模块缺失 entity 包，导致编译失败。

### ISSUE THREAD

**Issue by daixiansuo** [alibaba/nacos#8986]
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/41660452/185099487-2cf92f4a-1667-48f7-8ea2-26bd057002a2.png">

**Comment by daixiansuo** [comment]
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/41660452/185099415-ca89d439-5384-4bad-bcae-1b8b1d2451df.png">

**Comment by chenhao26-nineteen** [comment]
> <img alt="image" width="1893" src="https://user-images.githubusercontent.com/41660452/185099487-2cf92f4a-1667-48f7-8ea2-26bd057002a2.png">


duplicate with other many issue #8918

**Comment by daixiansuo** [comment]
好的 感谢
