### ISSUE TITLE
通过nginx转发1.4.4版本，报错（allowedOrigins cannot contain the special value "*"since that cannot be set on the "Access-Control-Allow-Origin"）

### ISSUE THREAD

**Issue by csx-chenshunxi** [alibaba/nacos#8990]
**Describe the bug**
通过nginx转发1.4.4版本，报错（allowedOrigins cannot contain the special value "*"since that cannot be set on the "Access-Control-Allow-Origin"）。

解决方案：https://www.cnblogs.com/kanie-life/p/14285217.html
报错信息：at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:69)
spring 2.6.6版本问题

**Expected behavior**
应该正常访问的

**Actually behavior**
页面接口报500

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by onewe** [comment]
已经修复了 https://github.com/alibaba/nacos/pull/8980
