### ISSUE TITLE
nacos 0.2.1-release 的健康监测问题

### ISSUE THREAD

**Issue by hackbin** [alibaba/nacos#90]
我半小时之前按照https://github.com/nacos-group/nacos-spring-boot-project的nacos-spring-boot-samples，注册了服务，然后关闭springboot程序，现在执行SecondCommandLineRunner，仍然可以获取到该服务
![image](https://user-images.githubusercontent.com/4686093/46195113-ed7ee700-c335-11e8-991a-2cde2d4c5a4a.png)
/actuator/nacos-discovery内容如下：
`{
    "nacosDiscoveryGlobalProperties": {
        "serverAddr": "localhost:8003",
        "encode": "UTF-8"
    },
    "namingServersStatus": [
        {
            "subscribeServices": [
                {
                    "jsonFromServer": "",
                    "name": "front_service",
                    "clusters": "",
                    "cacheMillis": 10000,
                    "hosts": [
                        {
                            "instanceId": "10.9.0.48#10001#DEFAULT#front_service",
                            "ip": "10.9.0.48",
                            "port": 10001,
                            "weight": 1,
                            "healthy": true,
                            "cluster": {
                                "serviceName": null,
                                "name": "",
                                "healthChecker": {
                                    "type": "TCP"
                                },
                                "defaultPort": 80,
                                "defaultCheckPort": 80,
                                "useIPPort4Check": true,
                                "metadata": {}
                            },
                            "service": null,
                            "metadata": {}
                        }
                    ],
                    "lastRefTime": 1538118447736,
                    "checksum": "e601d2177fbf4eaa54909f018e818241538118447736",
                    "allIPs": false,
                    "key": "front_service",
                    "valid": true
                },
                {
                    "jsonFromServer": "{\"dom\":\"test-service\",\"cacheMillis\":10000,\"useSpecifiedURL\":false,\"hosts\":[{\"valid\":true,\"marked\":false,\"metadata\":{},\"instanceId\":\"1.1.1.1#8002#DEFAULT#test-service\",\"port\":8002,\"ip\":\"1.1.1.1\",\"weight\":1.0}],\"checksum\":\"d76dc68287f31e42fe69f9de1b4ff7db1538120925078\",\"lastRefTime\":1538120925078,\"env\":\"\",\"clusters\":\"\"}",
                    "name": "test-service",
                    "clusters": "",
                    "cacheMillis": 10000,
                    "hosts": [
                        {
                            "instanceId": "1.1.1.1#8002#DEFAULT#test-service",
                            "ip": "1.1.1.1",
                            "port": 8002,
                            "weight": 1,
                            "healthy": true,
                            "cluster": {
                                "serviceName": null,
                                "name": "",
                                "healthChecker": {
                                    "type": "TCP"
                                },
                                "defaultPort": 80,
                                "defaultCheckPort": 80,
                                "useIPPort4Check": true,
                                "metadata": {}
                            },
                            "service": null,
                            "metadata": {}
                        }
                    ],
                    "lastRefTime": 1538120925078,
                    "checksum": "d76dc68287f31e42fe69f9de1b4ff7db1538120925078",
                    "allIPs": false,
                    "key": "test-service",
                    "valid": true
                }
            ],
            "servicesOfServer": {
                "data": [],
                "count": 2
            }
        }
    ]
}`
我的理解1.1.1.1#8002#DEFAULT#test-service应该被淘汰掉，不知道对不对？

**Comment by nkorange** [comment]
你的Springboot程序是kill -9关闭的吗？
{user.home}/logs/nacos/naming.log 看看是否有DEREGISTER-SERVICE关键字日志。

**Comment by hackbin** [comment]
springboot程序是通过IDEA的stop关闭的，全天的naming.log都没有DEREGISTER-SERVICE相关的日志，有一些registering service，我的理解是，如果遇到非正常关闭、关机、断电等问题，nacos应该可以自动淘汰掉相应的节点。

**Comment by nkorange** [comment]
@hackbin 不会的，非正常关闭还会保留实例，但是会通过健康检查淘汰不健康的实例。
当服务只剩下一个实例时，这个实例就一直认为是健康的。这是Nacos的健康保护阈值机制，可以参考：
https://nacos.io/zh-cn/docs/concepts.html

**Comment by hackbin** [comment]
哦，那就不是bug了，那个服务只有一个实例，我好好看看概念文档哈。
