### ISSUE TITLE
What if the content content is too long to publish the NACOS configuration through API

### ISSUE THREAD

**Issue by zouao0821** [alibaba/nacos#9002]
What if the content content is too long to publish the NACOS configuration through API？
POST http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=test1&group=capp&content=url%3A+d-im.cn&type=yaml
What I want to add：
`mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.immotors.lapp.privilege.pojo.po

feign:
  httpclient:
    enabled: false
    disable-ssl-validation: true
  okhttp:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  ReadTimeout: 7000
  ConnectTimeout: 7000

swagger:
  enable: false
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合
  try-host: localhost:${server.port}

knife4j:
  basic:
    enable: true`

**Comment by KomachiSion** [comment]
There is no limit for nacos publish config, but community not suggest the content more than 100k.
