### ISSUE TITLE
java 在使用 NamingService.subsrribe回调问题

### ISSUE THREAD

**Issue by a616567126** [alibaba/nacos#9005]
NamingService.subsrribe在使用过程中发现上线的服务可以获取到对应的ip端口等信息，下线的却获取不到
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/43660702/185778093-39339a8b-4b53-485c-9256-2c2fc6f85bc1.png">
在onEvent中的listener里有这些参数却不知道如何取出来
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/43660702/185778215-d63f5596-c176-441d-a86e-c1174c657fbf.png">

**Comment by a616567126** [comment]
方法已找到
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/43660702/185783008-e5ef370c-dfe5-4977-92e3-85694cf6fff4.png">

**Comment by KomachiSion** [comment]
上下线都会回调listener， listener回调的时候会带上当前的所有在线的实例信息。正常使用应该直接拿最新的hosts直接使用就好。
如果是需要识别哪些上线了哪些下线了，就需要自己在listener里面做逻辑处理了。
