### ISSUE TITLE
nacos通过maven:3.5.2-jdk-8-alpine镜像编译protoc的问题

### ISSUE THREAD

**Issue by wangleixiaoshitou** [alibaba/nacos#9007]
系统环境：
Linux host3 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Docfile文件：
FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD
MAINTAINER wanglei
# 工作目录在镜像的 /build 目录下
WORKDIR /build/
COPY pom.xml /build/
# 执行maven打包
COPY /settings.xml /root/.m2/settings.xml
ENTRYPOINT ["mvn","install", "-U", "-Dcheckstyle.skip", "-Drat.skip=true",  "-Dpmd.skip=true", "-Dmaven.test.skip=true","-X"]
容器run的时候：
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project nacos-consistency: An error occurred while invoking protoc.: Error while executing process. Cannot run program "/build/consistency/target/protoc-plugins/protoc-3.8.0-linux-x86_64.exe": error=2, No such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project nacos-consistency: An error occurred while invoking protoc.

备注：idea本地编译没问题。

**Comment by KomachiSion** [comment]
应该是系统环境或者系统版本有问题， 我以前用5u的机器运行也会出现，换成7u的系统版本就没问题。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
