### ISSUE TITLE
Corner case dataId 'cipher-' cause config fail to create

### ISSUE THREAD

**Issue by HotSince91** [alibaba/nacos#9023]
**Describe the bug**
we cannot create config dataId named 'cipher-' 

**How to Reproduce**
POST /nacos/v1/cs/configs

payload
![b3e0292f2e6235b25201050f7a6ea3a](https://user-images.githubusercontent.com/94208776/186311770-f75ebf77-89fb-44bb-9db8-7a97e8573ef2.png)

response
![241b67bfb3bdacbb7da77b31c68fb84](https://user-images.githubusercontent.com/94208776/186311796-21c9939e-be57-4abb-b5ff-1a0358e48c51.png)

**Desktop (please complete the following information):**
 - Version: nacos-server 2.1.1
 - Module: config

**Comment by HotSince91** [comment]
@i will fix it@

**Comment by KomachiSion** [comment]
Can you describe what's the problem in issue first?
