### ISSUE TITLE
Questions about com.alibaba.nacos.naming.core.DistroMapper#responsible(java.lang.String).

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#9025]
https://github.com/alibaba/nacos/blob/f1c95a8fb4fbc8219d26a7af34a3eca7b2274843/naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java#L83-L104

Why does the `responsible` method return true when `servers ` do not contain `localAddress`?

**Comment by stone-98** [comment]
If the current service is not in `healthyList`, shouldn't another service be responsible?

**Comment by KomachiSion** [comment]
localAddress is self server which can't be unhealthy, if healthyList not contain self, means your server has problem. So should not transport request with distro to other server make the problem larger.

**Comment by stone-98** [comment]
Thanks for the reply, I didn't look carefully at the source of healthyList, I now understand that it is impossible for healthyList not to contain localAddress.
