### ISSUE TITLE
user register security bug(用户注册安全问题)

### ISSUE THREAD

**Issue by 12973796** [alibaba/nacos#9034]
not need login for create user, use postman input this：
“http://127.0.0.1:8848/nacos/v1/auth/users/?username=cert1&password=cert1”
POST method， then can create user。

**Comment by chenhao26-nineteen** [comment]
> not need login for create user, use postman input this： “[http://127.0.0.1:8848/nacos/v1/auth/users/?username=cert1&password=cert1”](http://127.0.0.1:8848/nacos/v1/auth/users/?username=cert1&password=cert1%E2%80%9D) POST method， then can create user。

Authentication is not enabled，Check it

**Comment by 12973796** [comment]
how can enable Authentication ：）

**Comment by chenhao26-nineteen** [comment]
> how can enable Authentication ：）

nacos.core.auth.enabled=true

**Comment by 12973796** [comment]
yes，thanks.

**Comment by realJackSun** [comment]
@12973796 Is the problem solved?

**Comment by 12973796** [comment]
modify configuration auth.enable=true
test OK! 
:) :) :)
