### ISSUE TITLE
springboot连接nacos，获取配置，配置项的值一会是最新版本，一会是历史版本。比如我配置一个数据test=a，之后修改test=b，再之后修改test=c。最后我去获取test的值，有可能是c，有可能是b，有可能是a

### ISSUE THREAD

**Issue by liush2** [alibaba/nacos#9035]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by chenhao26-nineteen** [comment]
> ## Issue Description
> Type: _bug report_ or _feature request_
> 
> ### Describe what happened (or what feature you want)
> ### Describe what you expected to happen
> ### How to reproduce it (as minimally and precisely as possible)
> 
> ### Tell us your environment
> ### Anything else we need to know?

nacos版本，Spring boot版本，都说明下

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
