### ISSUE TITLE
Faild start the "nacos-cmdb" application

### ISSUE THREAD

**Issue by sixsixsix516** [alibaba/nacos#9039]
**Describe the bug**
The console is reported an expetion that  "InputStream must not be null"  when i starting "CmdbApp".

**Expected behavior**
Start sucessful.

**Actually behavior**
happen exception

**How to Reproduce**
Start "CmdbApp"

![image](https://user-images.githubusercontent.com/45815935/187017077-c76ad5af-4f10-40bb-9c3b-525daa35cce0.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version: Nacos 2.1.1
 - Module: cmdb
 - SDK: original

**Additional context**
nothing

**Comment by KomachiSion** [comment]
How to start？

**Comment by KomachiSion** [comment]
没配置application.properties

**Comment by HMYDK** [comment]
> 没配置application.properties

我本地直接启动「config」项目时，也是这个报错，但是「config」项目也是没有application.properties。请教下该怎么处理？

**Comment by sixsixsix516** [comment]
> > 没配置application.properties
> 
> 我本地直接启动「config」项目时，也是这个报错，但是「config」项目也是没有application.properties。请教下该怎么处理？




config 不能直接启动，启动模块应该是 console

请看这篇文章 https://sixsixsix516.blog.csdn.net/article/details/128355599
