### ISSUE TITLE
2.1.1版本 “配置管理”新增时报空指针异常

### ISSUE THREAD

**Issue by huatao0221** [alibaba/nacos#9040]
使用 nacos添加配置管理时，报错，查看log日志为空指针异常。
具体贴图查看如下链接
[查看问题](https://www.oschina.net/question/3535099_2326763)

**Comment by lyf712** [comment]
插入前看看数据库的config_info的数据看看 data_id,group_id,tenant_id 有没有和该次插入的重合，按逻辑当唯一主键冲突才执行更新逻辑，所以说进入更新 则该数据应该是在的，就不会空指针，除非在此过程中突然数据又掉了。可以尝试打断点追一下，换一个数据库或用内嵌数据库都去试试呢。

**Comment by onewe** [comment]
表结构是按照 发行版中的 sql 文件创建的么?

**Comment by onewe** [comment]
有条件的话可以在 ExternalStoragePersistServiceImpl.addConfigInfo#182 中打个断点看看, 猜测是 his_config_info 表中的数据 主键冲突了. 可以把数据库重建一下 看看是否依旧有问题

**Comment by huatao0221** [comment]
> 表结构是按照 发行版中的 sql 文件创建的么?

是文件中的sql，已经自行解决，用的mysql5.5的版本升级到8.0+就没问题了
