### ISSUE TITLE
使用dubbo，配置文件未能注册到对应命名空间

### ISSUE THREAD

**Issue by 112292454** [alibaba/nacos#9041]
应用中配置了discovery和config里的namespace，配置文件仍然被注册到public，但在服务管理中成功注册到了对应的命名空间。nacos版本2.0.0
效果如图：

![image](https://user-images.githubusercontent.com/92578848/187026664-5d32bb29-0ab8-452f-aca1-f190ece756f8.png)

![image](https://user-images.githubusercontent.com/92578848/187026680-47972d27-1779-491f-abef-473a84ec2509.png)

![image](https://user-images.githubusercontent.com/92578848/187026701-5b5ddc22-489d-4c35-8c43-356af692a8cf.png)

在init里面调试看到namespace有传进去。

![image](https://user-images.githubusercontent.com/92578848/187026784-1fb95f6e-28cf-4d65-9e71-6c7f8f382156.png)

看其他的issue，在dubbo的address后加了?namespace=xxxx成功注册。这是预期之中的设计吗

**Comment by KomachiSion** [comment]
当然，你上文中的配置没有配置dubbo的命名空间，只配置了sca的命名空间， dubbo自然认为你是默认命名空间的服务。

**Comment by 112292454** [comment]
啊……抱歉，之前开学刚才看到。前面的学习大多照着书上做的，现在去测试了一下这个和之前的一些服务接入nacos的方式

我理解是  这样配置的应用，在nacos里面没有它对应的配置文件时，好像不会新建一个配置文件（无法新建？或者可以开启？）；而接入dubbo之后，dubbo会给服务默认新建几个对应的配置文件（截图那几个public的，也因此所以group都是dubbo或者xxx.dubbo之类）而这样通过dubbo新建就要在它里面去写命名空间，不然就是public。此外，服务管理里面，注册服务是直接nacos，不通过dubbo，于是注册到了预期的命名空间。是这样子吗？

之前以为dubbo只是提供一个rpc的调用功能，配置啥的与他无关，所以不理解为啥命名空间不对

> 当然，你上文中的配置没有配置dubbo的命名空间，只配置了sca的命名空间， dubbo自然认为你是默认命名空间的服务。
