### ISSUE TITLE
源码无法运行 

### ISSUE THREAD

**Issue by encrylife** [alibaba/nacos#9044]
程序包com.alibaba.nacos.consistency.entity不存在，我在源代码里去看了 的确是没有这个包。但是引用的还不少 包括nacos-core

**Comment by onewe** [comment]
see https://nacos.io/zh-cn/docs/faq.html#3.19

**Comment by onewe** [comment]
At first you might need to run `mvn clean install -DskipITs` and then run the project

**Comment by encrylife** [comment]
thanks,I try it
