### ISSUE TITLE
信创专用机启动报错

### ISSUE THREAD

**Issue by rxb1992** [alibaba/nacos#9057]
部署环境：
    nacos版本：2.0.3 、2.1.0；
    操作系统版本：银河麒麟（SVS2.19.2）
    内核版本：4.19.90.S001
    CPU 飞腾S2500

机器：
   信创专用机

通过standalone模式启动时，发现会在/tmp目录下生成随机文件名的librocksdbjnixxxxxxx.so的文件，但是因为在信创专用机上，默认生成的文件是没有执行权限的，导致启动报错如下：
![85bb680d01abffac4774d98fb104c3e](https://user-images.githubusercontent.com/5337222/187612572-5878a82d-3401-4fdd-9aff-00b2d85b2f5d.jpg)

请问该文件是必须要生成执行的吗？是否可以避开？

**Comment by rxb1992** [comment]
> 这个文件是rocksdb所需要的文件，如果没有的话rocksdb应该无法启动。
> 
> rocksdb是jraft依赖的本地kv数据库，用来保存raft变更日志的，可能需要提issue到jraft社区，找一个其他的kv数据库替换掉。

有哪个版本不依赖jraft可以用的吗？

**Comment by KomachiSion** [comment]
1.4以前的版本
