### ISSUE TITLE
nacos打印注册成功日志，实际注册失败

### ISSUE THREAD

**Issue by huo-ran** [alibaba/nacos#9058]
环境：
jdk：1.8
spring-boot：2.3.12.RELEASE
spring-cloud：Hoxton.SR12
spring-cloud-alibaba：2.2.7.RELEASE
nacos-server：2.0.3

本地环境启动服务可以正常注册到nacos，通过name调用正常。

部署到云环境启动提示注册成功，并无其他异常日志。
com.alibaba.cloud.nacos.registry.NacosServiceRegistry - nacos registry, XX XX XX:8080 register finished
但是在nacos服务页面上查询不到服务，并且通过name调用也获取不到服务。
java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: XX

其他服务部署到云环境却能正常注册到nacos。

**Comment by YunWZ** [comment]
你的服务确实注册到同一个nacos集群了吗？

**Comment by chenhao26-nineteen** [comment]
> 环境： jdk：1.8 spring-boot：2.3.12.RELEASE spring-cloud：Hoxton.SR12 spring-cloud-alibaba：2.2.7.RELEASE nacos-server：2.0.3
> 
> 本地环境启动服务可以正常注册到nacos，通过name调用正常。
> 
> 部署到云环境启动提示注册成功，并无其他异常日志。 com.alibaba.cloud.nacos.registry.NacosServiceRegistry - nacos registry, XX XX XX:8080 register finished 但是在nacos服务页面上查询不到服务，并且通过name调用也获取不到服务。 java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: XX
> 
> 其他服务部署到云环境却能正常注册到nacos。

检查一下namespace有没有写对 @huo-ran

**Comment by huo-ran** [comment]
> > 环境： jdk：1.8 spring-boot：2.3.12.RELEASE spring-cloud：Hoxton.SR12 spring-cloud-alibaba：2.2.7.RELEASE nacos-server：2.0.3
> > 本地环境启动服务可以正常注册到nacos，通过name调用正常。
> > 部署到云环境启动提示注册成功，并无其他异常日志。 com.alibaba.cloud.nacos.registry.NacosServiceRegistry - nacos registry, XX XX XX:8080 register finished 但是在nacos服务页面上查询不到服务，并且通过name调用也获取不到服务。 java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: XX
> > 其他服务部署到云环境却能正常注册到nacos。
> 
> 检查一下namespace有没有写对 @huo-ran

是同一个，这个已经确认过了的。

**Comment by huo-ran** [comment]
> 你的服务确实注册到同一个nacos集群了吗？
同一个集群了，配置这些都是确认过好几遍了

**Comment by KomachiSion** [comment]
看下${user.home}/logs/nacos/naming.log 服务实际注册到哪个namespace， 服务名具体是什么。

**Comment by huo-ran** [comment]
> 看下${user.home}/logs/nacos/naming.log 服务实际注册到哪个namespace， 服务名具体是什么。

这个也确认了好几遍了，和注册正常的都没区别。然后也特意打印了nacos的日志，日志显示注册过程都是正常的，但就是服务端查不到。

**Comment by huo-ran** [comment]
已经找到原因了，是因为nacos与saturn冲突造成的。
Saturn 启动时， 修改了系统的namespace配置，导致nacos获取namespace时，获取到了saturn的namespace，造成了注册失败问题。
![image](https://user-images.githubusercontent.com/19793664/189047873-4f6f8a69-bc82-4aaf-b204-b64164d0021c.png)
