### ISSUE TITLE
nacos-server 2.1.1 Output event warning log continuously

### ISSUE THREAD

**Issue by ForJ-W** [alibaba/nacos#9060]
```
Env:
    nacos-server:
        Docker version 20.10.8
        nacos/nacos-server:v2.1.1
        in cluster mode. use external storage

    nacos-client:
        SpringCloud 2021.0.3
        SpringCloud Alibaba 2021.0.1.0
        nacos-client 2.1.1
```

Hello, may I ask why the nacos-server warning log keeps appearing after the upgrade from 2.1.0 to 2.1.1 (without any change except the version):

```
WARN There are no [com.alibaba.nacos.common.trace.event.naming.PushServiceTraceEvent] publishers for this event, please register
WARN There are no [com.alibaba.nacos.common.trace.event.naming.DeregisterInstanceTraceEvent] publishers for this event, please register
```
Could you please tell me how to eliminate this warning?  If you can answer the reason of the warning, it would be better.  Thank you~

**Comment by YunWZ** [comment]
just ignore these warnings.

**Comment by KomachiSion** [comment]
this is the 2.1.1 beta feature trace event.  if there are no subscriber to handle TraceEvent, will print this log.

ignore it in 2.1.1 version, We will enhance it in 2.1.2.
