### ISSUE TITLE
数据不一致  data inconsistency

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#9069]
通过k8s搭建的三节点的NACOS2.1.1集群，发现改了配置之后，本地拉取的信息不对；
例如在配置文件中修改端口为8082，然后本地会拉取之前的8083的信息；
但是我在数据库中的信息也是8082，只有拉取到本地的数据不对，这个可以是因为集群搭建有问题吗？节点通讯有问题？需要如何检查一下
k8s的脚本使用的是 https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-no-pvc-ingress.yaml

The three-node NACOS2.1.1 cluster built by k8s found that after the configuration was changed, the locally pulled information was incorrect;
For example, modify the port to 8082 in the configuration file, and then the previous 8083 information will be pulled locally;
But my information in the database is also 8082, only the data pulled locally is wrong. Could this be because there is a problem with the cluster setup? Is there a problem with node communication? how to check
The script of k8s is https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-no-pvc-ingress.yaml

**Comment by KomachiSion** [comment]
有可能是水平通知问题导致其他节点从数据库中dump失败， 一般这个情况会在时区或时钟有问题的时候出现，看一下数据库连接url里有没有指定timeZone之类的，导致插入的配置的创建时间或者更新时间快了或者慢了。

**Comment by nomatterfine** [comment]
> 有可能是水平通知问题导致其他节点从数据库中dump失败， 一般这个情况会在时区或时钟有问题的时候出现，看一下数据库连接url里有没有指定timeZone之类的，导致插入的配置的创建时间或者更新时间快了或者慢了。

不是这个原因，我单节点也是出现这个问题，我在页面修改了配置，在数据库中显示已经修改了，但是本地的缓存也是错误的

**Comment by nomatterfine** [comment]
> 有可能是水平通知问题导致其他节点从数据库中dump失败， 一般这个情况会在时区或时钟有问题的时候出现，看一下数据库连接url里有没有指定timeZone之类的，导致插入的配置的创建时间或者更新时间快了或者慢了。

问题找到了，是因为脚本修改了命名空间不统一
