### ISSUE TITLE
nacos cpu过高

### ISSUE THREAD

**Issue by GG22G2** [alibaba/nacos#9071]
我使用nacos 2.1.0，已经有一个多月了，每天都是在打开nacos2小时后，cpu就会突然占满，并且一直持续下去。

nacos配置:
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://localhost:3306/ry-config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user=root
db.password=password

![B VS4Q(E9B@MXA%5@JW`S13](https://user-images.githubusercontent.com/31408730/188054695-19012d4e-1f88-44fe-8739-89fad32be73a.png)

![~E(3@){3W$)V2BGZ`6()BX0](https://user-images.githubusercontent.com/31408730/188054679-c83e3ed1-8afd-417e-9de6-fa53306f7d89.png)

使用idea的得到的统计信息：
![1H{RL9HP8H%AP1GN97C(_~X](https://user-images.githubusercontent.com/31408730/188055822-9c7c6317-3d74-447a-b7c4-40d6abc980f8.png)

**Comment by YunWZ** [comment]
能否dump一下线程，看看在执行什么任务

**Comment by zhu1147212910** [comment]
解决了没，我刚用 2.1.0 版本 也遇到这个问题，只能重启来解决

**Comment by ldkkkkk** [comment]
2个小时数据库连接池里的连接失效了，可能操作系统的事，然后cpu就100%了

**Comment by YunWZ** [comment]
JDK的selector死循环问题?换OpenJDK试一下吧

**Comment by KomachiSion** [comment]
以前issue有排查过， 换一个jdk版本试试。

**Comment by KomachiSion** [comment]
#3903
