### ISSUE TITLE
@Aspect类中的配置不刷新

### ISSUE THREAD

**Issue by augustazz** [alibaba/nacos#9072]
配置的内容不刷新
环境：
nacos-client:2.0.4
spring-cloud-starter-alibaba-nacos-config:2021.1
spring-cloud-starter-bootstrap:3.1.0
spring-boot:2.6.3

**Describe the bug**
在使用了` @Aspect` 注解的切面类中增加配置

```java
@Value("${enableRemoteApiLog:true}")
private boolean enableRemoteApiLog;
```
配置项始终不刷新，尝试了加上@RefreshScope也不行

同项目的其他配置类，没有发现这个问题，所以怀疑是不是和Aspect有关系

**Comment by augustazz** [comment]
```java
@Value("${enableRemoteApiLog:true}")
private Boolean enableRemoteApiLog;
```
在配置中心中配置了值时，系统运行时获取到的是null，默认配置和nacos配置都不生效

**Comment by CaiGaoQing** [comment]
是能获取到，先看看注解扫描到了吗。加到Spring中了吗。
但是如果加了@RefreshScope会使 切面类加载2次
注解会修改bean的作用域为自定义的refresh导致他不是单例的，这个时候如果再配置Spring其他的组件注解就会导致容器中有两个相同的bean（如果是切面 就会导致切面执行两次），RefreshScope动态刷新配置的原理也就在此，他开启了对象代理模式，我们引用的都是它的代理对象，当接收到属性更新事件时会先摧毁该bean然后重新走一次bean创建的过程来达到配置刷新的目的

**Comment by CaiGaoQing** [comment]
![image](https://user-images.githubusercontent.com/29398395/188381646-d0be9f5e-98c7-456a-bb7f-29e116499e17.png)

**Comment by augustazz** [comment]
> 是能获取到，先看看注解扫描到了吗。加到Spring中了吗。 但是如果加了@RefreshScope会使 切面类加载2次 注解会修改bean的作用域为自定义的refresh导致他不是单例的，这个时候如果再配置Spring其他的组件注解就会导致容器中有两个相同的bean（如果是切面 就会导致切面执行两次），RefreshScope动态刷新配置的原理也就在此，他开启了对象代理模式，我们引用的都是它的代理对象，当接收到属性更新事件时会先摧毁该bean然后重新走一次bean创建的过程来达到配置刷新的目的

类上加了@Component；
RefreshScope如果不加的话，又会有配置不刷新的问题

**Comment by augustazz** [comment]
目前的临时办法是把这个配置提到另一个config properties的bean中
