### ISSUE TITLE
helm 部署 nacos2.1.0  代码不能访问，ui可以访问

### ISSUE THREAD

**Issue by heidaodageshiwo** [alibaba/nacos#9075]
![image](https://user-images.githubusercontent.com/29905182/188098803-48fda68b-77ba-4f21-8ce5-8bd81bc35d2f.png)
本人使用helm部署的。
看到端口都已经开放出来了。
![image](https://user-images.githubusercontent.com/29905182/188099026-9ea55cd1-2b8a-46dd-a1a8-42146b04f316.png)
这些都是可以访问的
![image](https://user-images.githubusercontent.com/29905182/188099165-bd875578-1a14-4b82-8115-361eb30908cb.png)
![image](https://user-images.githubusercontent.com/29905182/188099222-89974276-499b-4a79-8358-5f703fe3e067.png)
teltelnet  31862端口是通的。
![image](https://user-images.githubusercontent.com/29905182/188099360-d7118209-fc05-4559-a131-43bb7e2f8168.png)
![image](https://user-images.githubusercontent.com/29905182/188099409-8a9b0e07-f20e-4d19-a4c3-f832708aac1f.png)

tetelnet 31112也是通的， 但是一敲击回车就报错：
![image](https://user-images.githubusercontent.com/29905182/188099503-dcd37073-7edf-484c-8dd7-be6f979fe130.png)
代码连接方式：
![image](https://user-images.githubusercontent.com/29905182/188099651-ea5920ff-f98e-4b32-b1d5-0b72f23ba9be.png)
或者是把端口改成31112 都连接不上
![image](https://user-images.githubusercontent.com/29905182/188099830-77e30363-6d06-4baa-ac5c-e8e9aaa5f6eb.png)
按照官网这个也看了，也排查了都连接不上：
![image](https://user-images.githubusercontent.com/29905182/188099952-b7a8b28d-86e6-451b-afea-70be5ffe0c35.png)

能解决一下这个问题么：helm部署的。

**Comment by heidaodageshiwo** [comment]
1.使用k8s  端口转发也不行
2.集群部署方式也连接不上
3.开启防火墙（8848，,3862等8个端口），关闭防火墙这些都试了，都是连接不上。

**Comment by heidaodageshiwo** [comment]
我在本地使用命令测试：
![image](https://user-images.githubusercontent.com/29905182/188104606-31fae2d0-29d0-4cd5-a485-0706449d5ec0.png)

界面展示：
![image](https://user-images.githubusercontent.com/29905182/188104693-549bf470-56a2-4ce9-abfe-440a701e6899.png)
![image](https://user-images.githubusercontent.com/29905182/188104719-a7038125-a112-4a55-807d-cdacc18a56d3.png)
zhe这些都是没有问题的就是：
![image](https://user-images.githubusercontent.com/29905182/188104873-f6ab6dc0-2122-4ea6-a47e-3b2dd346b0b5.png)
就是代码连不上！连不上！

**Comment by heidaodageshiwo** [comment]
我使用docker部署：

![image](https://user-images.githubusercontent.com/29905182/188250979-a68022f7-267a-4b37-8b3a-89566baa9648.png)

访问界面：

![image](https://user-images.githubusercontent.com/29905182/188250985-aac38629-c185-4e71-ac64-6585d45b446b.png)
服务列表
![image](https://user-images.githubusercontent.com/29905182/188251011-6f40391b-01bb-4c9c-806b-28e618e8c344.png)
访问的地址：
![image](https://user-images.githubusercontent.com/29905182/188251031-509543e6-6c29-4c37-8b57-98ccf720cddf.png)
代码：
![image](https://user-images.githubusercontent.com/29905182/188251042-7c20ac5e-6091-43b3-9b0d-0b89e9afd067.png)

看到服务已经注册到nacos中了。

1.一模一样的代码连接docker部署的是没有问题的。
2.连接windows启动的nacos使用这份代码我也连接过了，也可以注册进去服务。
3.但是helm部署的端口确实是都代理出来了。就是连接不上

**Comment by heidaodageshiwo** [comment]
1.本人已经经过各种测试，不管是helm部署的还是k8s部署的，我这里都是连接不上的。
2.我把springboot项目打成jar包发布到相同的机器上去访问这个地址也是访问不通的。
3.比较欣慰的是，我使用pod的ip地址进行注册成功了！

代码：
这是我代码中的连接：
![image](https://user-images.githubusercontent.com/29905182/188257556-dc28db42-3f2d-4b3e-879c-5c4966fc35de.png)
这个是我使用k8s部署的nacos，我是用了2个节点，3个pod的没起来但是不影响使用。
![image](https://user-images.githubusercontent.com/29905182/188257595-fc397d1f-4f64-4d7c-848b-856ec949294c.png)
请看：
![image](https://user-images.githubusercontent.com/29905182/188257622-4d335d53-407f-48e7-9bda-0e832fe7301b.png)
windows:界面能访问：nacos：但是死活注册不进去
![image](https://user-images.githubusercontent.com/29905182/188257639-8ae7a850-ffab-4b48-8f4b-f19de8d0314c.png)
我使用pod的ip地址进行放在代码里面注册：10.244.166.155这个ip：8848 就注册进去了！
请看：
![image](https://user-images.githubusercontent.com/29905182/188257679-937d2104-0d32-4075-8e0b-b649e320d2e2.png)

个人总结：
1.windows，docker部署的nacos可以访问并注册
2.k8s，helm部署的nacos我这里是死活注册不进去
3.对pod的ip地址是可以注册进去的

**Comment by heidaodageshiwo** [comment]
个人总结：
1.既然知道了集群是没有问题的，可以访问pod的ip 加端口，那么也可以代理出来的
2.代理：本人采取了pod name选取的方式进行暴露nacos-0  nacos-1  nacos-2 这些节点(本人机器数量有限，可自行选择几台机器部署。)
3.先看效果：
![image](https://user-images.githubusercontent.com/29905182/188258239-978c854c-aeac-4c8c-b467-409968d52071.png)
我的代码里面写的可是：31000  了 不是pod  的ip了
![image](https://user-images.githubusercontent.com/29905182/188258257-d0cbb750-3541-4ba1-b075-13168dd1e1d5.png)
nacos:
![image](https://user-images.githubusercontent.com/29905182/188258266-a73d0651-d26d-49d8-ae1f-e40decf2a787.png)
4.美滋滋
5.代理的完整service.yaml（个人选取pod进行代理）
apiVersion: v1
kind: Service
metadata:
  name: service-nacos-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: nacos-0
  ports:
    - name: client-port
      port: 8848
      protocol: TCP
      targetPort: 8848
      nodePort: 31000
    - name: bus-port
      port: 9848
      protocol: TCP
      targetPort: 9848
      nodePort: 32000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: service-nacos-1
spec:
  selector:
    statefulset.kubernetes.io/pod-name: nacos-1
  ports:
    - name: client-port
      port: 8848
      protocol: TCP
      targetPort: 8848
      nodePort: 31001
    - name: bus-port
      port: 9848
      protocol: TCP
      targetPort: 9848
      nodePort: 32001
  type: NodePort
---


6.这样代理出来执行就能把 不管是helm还是k8s部署的nacos都能代理出来了
7.不足：这只是单纯的代理1个或几个pod，前面可加一层负载  nginx或traefik
8.完结！

**Comment by KomachiSion** [comment]
看表述和nacos没什么关系啊， 属于你部署的环境单纯网络不通。

**Comment by KomachiSion** [comment]
ui可以访问应该是开通了8848端口的映射， 程序不同可能是9848端口未映射，建议看一下nacos的文档。里面有所需要的端口以及映射关系。

**Comment by heidaodageshiwo** [comment]
我上面已经把地址给代理出来了，官方给的，代码是觉对访问不了的。

**Comment by KomachiSion** [comment]
那其实还是网络设置的问题，如果你觉得nacos-k8s提供的用例有问题， 可以提issue到nacos-k8s， 如果能提PR是最好的。

**Comment by MrLiuFang** [comment]
此问题 很严重  nodeport 暴露端口的时候  k8s  默认情况不支持30000以下的端口    nacos 也没可修改的配置     郁闷

**Comment by MrLiuFang** [comment]
![截图 2022-12-09 11-15-50](https://user-images.githubusercontent.com/25580414/206616426-bc90f406-84f9-41d1-ae04-31d7d0179da4.png)
可以设置 nacos.server.grpc.port.offset和nacos.remote.client.grpc   把9848  9849  7848 …… 这几个端口配置到30000以上就可以通过nodeport映射出去


或者直接把k8s 里的8848端口 改成31500也可以    9848  9849  7848   这几个端口就可以通过偏移量 变成30000 以上     通过nodeport映射就没问题了
![image](https://user-images.githubusercontent.com/25580414/206616771-2d14cc18-c5d1-4d30-82d1-75043705f4f9.png)

**Comment by MrLiuFang** [comment]
![image](https://user-images.githubusercontent.com/25580414/206617245-d02ce345-1843-4b33-a369-e8c1758c51ca.png)
端口全部变成30000 以上  完美解决
