### ISSUE TITLE
Questions about publishing configuration parameters.

### ISSUE THREAD

**Issue by stone-98** [alibaba/nacos#9081]
https://github.com/alibaba/nacos/blob/0aa695e0d3ae5209f015bf9fd23ea7f06632c002/config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java#L128-L142
上述代码，Controller有两个与tag相关的参数，分别是tag和config_tags
![image](https://user-images.githubusercontent.com/35629966/188252899-8efb3c3d-4968-4a63-a62d-460860fe8239.png)
![image](https://user-images.githubusercontent.com/35629966/188252913-2085d8ad-21f3-4c61-8db1-32ef1064ae52.png)
控制台请求Controller也有两个与tag相关的参数，分别是config_tags和configTags。
我没有找到Controller中tag参数的来源，所以这个参数的来源是哪里？
还有一个就是控制台请求Controller的参数configTags应该是无效的把。

**Comment by lyf712** [comment]
你好，请问你的版本号是多少啊？我用2.1.1的调试控制台没有看到configTags呢，在控制台的前端NewConfig.js中也可发现没有这个请求字段。
![image](https://user-images.githubusercontent.com/62736461/189471564-2dafea40-645a-4c3f-92d9-3f170fd65729.png)

对于后端的设计是我理解的是tag的空与否去判断是单个tag(则是单个字符串)还是tags(则是strList),而在控制台请求设计时应该为了方便调用统一采用config_tags了并未去单个tag（单个tag也可以理解为特殊的strList），在OpenApi时你可进行tag字段的选择。关于具体代码，可以将NewConfig.js的请求部分代码及该部分的后端代码调试一下，希望有所帮助。
![image](https://user-images.githubusercontent.com/62736461/189471782-7f907275-84c4-4884-b6ac-4ce8b9a4aa2f.png)

**Comment by realJackSun** [comment]
这个tag还有个作用是后续为了方便实现tag发布功能（将新版本的配置发布到指定的tag上）

**Comment by stone-98** [comment]
感谢回复，我明白了。

**Comment by stone-98** [comment]
> 你好，请问你的版本号是多少啊？我用2.1.1的调试控制台没有看到configTags呢，在控制台的前端NewConfig.js中也可发现没有这个请求字段。 ![image](https://user-images.githubusercontent.com/62736461/189471564-2dafea40-645a-4c3f-92d9-3f170fd65729.png)
> 
> 对于后端的设计是我理解的是tag的空与否去判断是单个tag(则是单个字符串)还是tags(则是strList),而在控制台请求设计时应该为了方便调用统一采用config_tags了并未去单个tag（单个tag也可以理解为特殊的strList），在OpenApi时你可进行tag字段的选择。关于具体代码，可以将NewConfig.js的请求部分代码及该部分的后端代码调试一下，希望有所帮助。 ![image](https://user-images.githubusercontent.com/62736461/189471782-7f907275-84c4-4884-b6ac-4ce8b9a4aa2f.png)

我调试时使用的是develop最新代码，Beta发布时才会出现configTags字段，我觉得可以去掉这个字段，因为本身就已经有config_tags字段了，但是我不熟悉前端。

**Comment by KomachiSion** [comment]
configTags 有可能是早起控制台传的值，为的是兼容旧接口吧，如果可以完全确认不再读取这个字段，可以从前端改动删除掉，不过我觉得问题不大。
