### ISSUE TITLE
The dataid name uses a -separated question that causes the service name to not be used -

### ISSUE THREAD

**Issue by longlylong** [alibaba/nacos#909]
server_gateway-local.properties
server_gateway application name只能这样写

server-gateway这样写就会找不到 server-gateway-local的dataid
求解释

**Comment by jifengnan** [comment]
啥意思，没懂。
Can you describe it more clearly?

**Comment by longlylong** [comment]
不知道是不是版本的问题。我用1.0.0就就没问题了
