### ISSUE TITLE
读取nacos配置的值和实际值不一样

### ISSUE THREAD

**Issue by Cocowwy** [alibaba/nacos#9090]
When i use @Value to get the config from nacos,but the read value not equals the real config.

 - OS: [MC OS]
 - Version [spring-cloud-starter-alibaba-nacos-config  2.1.1.RELEASE, nacos-server 2.1.1]
 - Module [naming/config]
 
![image](https://user-images.githubusercontent.com/63331147/188301355-0588ed0c-1b41-4cab-b01c-9c1f11fe9288.png)

We can see，the real value ‘redis.pwd’ is 000415 but use '@Value' to read config  ,we get 269, i promise ,i didn't change the config on others channel . BTW, the 'redis.url' , is  equals . Just ‘redis.pwd’ not equals.

**Comment by chenhao26-nineteen** [comment]
> * [spring-cloud-starter-alibaba-nacos-config

I can't reproduce locally. Try spring-cloud-starter-alibaba-nacos-config 2.1.2 or higher

**Comment by Cocowwy** [comment]
> > * [spring-cloud-starter-alibaba-nacos-config
> 
> I can't reproduce locally. Try spring-cloud-starter-alibaba-nacos-config 2.1.2 or higher

Tks！ After I have modified the version, I succeeded

**Comment by Cocowwy** [comment]
> > * [spring-cloud-starter-alibaba-nacos-config
> 
> I can't reproduce locally. Try spring-cloud-starter-alibaba-nacos-config 2.1.2 or higher
<spring-cloud-alibaba.version>2.2.7.RELEASE</spring-cloud-alibaba.version>
I had use 2.1.1.RELEASE
I change my pwd to others , like '123123123', then ，the result is right ,  maybe '000415' decoding error？

**Comment by Cocowwy** [comment]
> > * [spring-cloud-starter-alibaba-nacos-config
> 
> I can't reproduce locally. Try spring-cloud-starter-alibaba-nacos-config 2.1.2 or higher

I tracked the source code，and i find，the nacos config same to my real config。
But  in com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder#loadNacosData ，
`Properties properties = NacosDataParserHandler.getInstance().parseNacosData(data, fileExtension);`
The ‘redis.pwd’ in data is '000415' bug in properties is '269'
Look at the next two pictures
**This is my config data ‘redis.pwd-test’**

![image](https://user-images.githubusercontent.com/63331147/188425944-0e10c7c0-beaf-435c-936b-5c5dce84bacc.png)


**This is  properties by use** `Properties properties = NacosDataParserHandler.getInstance().parseNacosData(data, fileExtension);`

![image](https://user-images.githubusercontent.com/63331147/188426179-98c4f4ee-2935-44d3-8583-cabe77739a32.png)

⚡ Until I tracked in `org.springframework.beans.factory.config.YamlPropertiesFactoryBean#createProperties`
It may be an error when parsing yaml
So I make a test，I think ，may be Spring‘s bug..⚡ 
![image](https://user-images.githubusercontent.com/63331147/188427466-7e16707c-d423-4230-9d93-76e44b833b3a.png)

**Comment by chenhao26-nineteen** [comment]
If Nacos is not introduced, reading yaml format files directly will also have this problem, so it has nothing to do with Nacos parsing. I think you can either fill in the original data format, or provide issue for yaml parsing, or modify the data format to. Properties。@Cocowwy
