### ISSUE TITLE
The parameter 'PUSH_RECEIVER_UDP_PORT ' should keep the same style with others in PropertyKeyConst.java

### ISSUE THREAD

**Issue by HaojunRen** [alibaba/nacos#9095]
其它静态变量都是驼峰形式命名，但这个变量不是，会导致其它中间件统一解析这个变量的时候失败

**Comment by KomachiSion** [comment]
UDP在client相关内容可能2.2版本就彻底删除了，看下是否有需要修改。

不过我好奇为什么会导致其他中间件解析异常？ `.`分层在properties也是常规用法；或者仅作为字符串处理也行。 还得看看具体错误是什么。

**Comment by HaojunRen** [comment]
象Spring Cloud Alibaba有个enrich properties的算法

举个例子

在nacos里的配置是namingPushEmptyProtection，那么在Spring Cloud Alibaba会变成spring.cloud.nacos.config.naming.push.empty.protection，SCA会去轮询所有nacos有关的配置

一旦nacos有一个变量不是遵循驼峰方式，这个enrich properties的算法在那个UDP配置上会失效

**Comment by KomachiSion** [comment]
那需要在nacos-client里面做一个适配了。

**Comment by cbcbcbcbcbc** [comment]
css

**Comment by KomachiSion** [comment]
PUSH_RECEIVER_UDP_PORT 参数已在新版本中被废弃。
