### ISSUE TITLE
集群模式修改实例的权重和上下线不起作用

### ISSUE THREAD

**Issue by qhyjoe** [alibaba/nacos#9096]
使用的是k8s部署的3个节点nacos集群，服务端版本2.1.0，客户端2.1.0，修改服务实例的权重和上下线不起作用
1、只有一个pod中修改的数据生效了，另外两个节点数据没有修改；
2、前端查询调用就会出现一会正确一会不正确的场景
3、怀疑是数据同步出现了问题

**Comment by KomachiSion** [comment]
未复现该问题， 通常有这个问题大概率是集群搭建有问题，导致raft选主出现问题，请排查是否alipay-jraft.log有异常。

**Comment by qhyjoe** [comment]
> 未复现该问题， 通常有这个问题大概率是集群搭建有问题，导致raft选主出现问题，请排查是否alipay-jraft.log有异常。

日志中未见异常，开的debug级别日志

**Comment by qhyjoe** [comment]
> 未复现该问题， 通常有这个问题大概率是集群搭建有问题，导致raft选主出现问题，请排查是否alipay-jraft.log有异常。

选主看着确实有问题 ，没个日志里都有 become leader of group，这应该怎么解决呢

**Comment by KomachiSion** [comment]
选主有问题就修复掉选主问题。 如果是配置错误导致选主失败就修复配置。
如果是网络问题就修复网络， 上文中也没有给出选主失败的原因，所以我也不好给解决方案
