### ISSUE TITLE
No DataSource set

### ISSUE THREAD

**Issue by WuZhiMing2** [alibaba/nacos#9098]
mysql版本8.x
使用docker-compose方式启动
standalone-mysql-8.yaml
`
version: "2"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    privileged: true
`
env/nacos-standlone-mysql.env
`
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=192.168.122.125
MYSQL_SERVICE_DB_NAME=nacos_root
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=321
MYSQL_SERVICE_PASSWORD=123
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
`
yaml文件中，删除了mysql容器，并修改nacos-standlone-mysql.env文件中的连接信息。nacos依然无法成功启动
`
nacos  | Caused by: java.lang.IllegalStateException: No DataSource set
nacos  | 	at org.springframework.util.Assert.state(Assert.java:76)
nacos  | 	at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:86)
nacos  | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
nacos  | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465)
nacos  | 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:475)
nacos  | 	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:508)
nacos  | 	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:515)
nacos  | 	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.findConfigMaxId(ExternalStoragePersistServiceImpl.java:674)
nacos  | 	at com.alibaba.nacos.config.server.service.dump.processor.DumpAllProcessor.process(DumpAllProcessor.java:51)
nacos  | 	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:282)
nacos  | 	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:195)
`

**Comment by wuchubuzai2018** [comment]
Nacos一般出现了这个错误，都是数据库连接的问题，一种是数据库链接参数本身错误，一种是连接超时(默认是3S，由于BUG无法外部设置)，

**Comment by WuZhiMing2** [comment]
> Nacos 一般出现错误，一种是数据库本身的错误，一种是数据库连接的问题，由于这个错误，一种是连接的连接参数（默认是 3S，外部设置），

 数据库本身没问题，外部访问也没问题，问题大概率出在docker容器的网络上。我想要的效果是：nacos对接已存在的mysql而不是在docker再创建一个mysql容器

**Comment by KomachiSion** [comment]
那就是环境问题了，需要自行解决docker容器内与外部网络的访问问题了
