### ISSUE TITLE
The same service of different groups, different health status.

### ISSUE THREAD

**Issue by lsh1358046425** [alibaba/nacos#9110]
相同的服务（IP端口一致）分组不同健康状态不一致，实际服务是Down的，但是有的分组服务实例状态是健康的？
甚至分组相同的不同服务，但是实例地址是一样的，健康状态也不一样，这是什么情况？

环境：
OS：Ubuntu16.04
版本：Nacos 2.1.0
实例类型：永久实例

**Comment by KomachiSion** [comment]
麻烦提供更多信息，比如相关日志，相关操作等。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
