### ISSUE TITLE
NACOS2.1.1 权限问题

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#9114]
NACOS2.1.1通过脚本启动k8s，除了数据库和命名空间之外的所有配置都没有改；
启动后台需要登陆才能访问，但是本地拉取配置不需要账号密码，这里面有什么问题吗？

**Comment by nomatterfine** [comment]
https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-no-pvc-ingress.yaml

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/auth.html

**Comment by nomatterfine** [comment]
现在需要鉴权，加了环境无法启动
            - name: NACOS_AUTH_ENABLE
              value: true
k8s如何开启鉴权呢

**Comment by nomatterfine** [comment]
解决了
- name: NACOS_AUTH_ENABLE
value: “true”
