### ISSUE TITLE
when release Nacos 1.0.0 ？

### ISSUE THREAD

**Issue by TenYearsIn** [alibaba/nacos#912]
#896 this issue gives me answer 。But please tell me when U plan to release Nacos 1.0.0。
Thank You ！！！

**Comment by Carl-Xiao** [comment]
wait~~

**Comment by TenYearsIn** [comment]
> wait~~
Game Over ！！

**Comment by nkorange** [comment]
Nacos 1.0.0 release will be available in next week if everything goes well.
Today Nacos 1.0.0-RC1 will be published. Thanks.

**Comment by TenYearsIn** [comment]
@nkorange  Thank You for Your reply， Nacos is very Good ，And The community is very active . Good Open Project！！！
