### ISSUE TITLE
源码方式启动Nacos真的是一言难尽

### ISSUE THREAD

**Issue by zh-Aispaly** [alibaba/nacos#9122]
2.0.4 启动报找不到：程序包istio.mcp.v1alpha1.MetadataOuterClass不存在
然后呢又继续编译proto文件，生成这个文件也是个坑有的没有生成出来，maven pom中配置也不对
你们团队传的源代码你确定能跑吗？

**Comment by onewe** [comment]
先执行`mvn clean install -DskipITs`

**Comment by zh-Aispaly** [comment]
> 先执行`mvn clean install -DskipITs`

这说的也太笼统了吧，你试过源码启动吗？在idea跑起来很困难

**Comment by wuchubuzai2018** [comment]
IDEA安装protobuf插件，然后项目根目录进行maven编译，然后启动环境设置为独立模式，同时增加nacos.home地址

**Comment by hoErYu** [comment]
istio.mcp.v1alpha1.MetadataOuterClass这个类是protobuf生成的，通过
![image](https://user-images.githubusercontent.com/56863753/189792864-9b51c61a-8273-46e4-97b1-6b972ca3b115.png)
就能编译出来这个类

**Comment by zh-Aispaly** [comment]
> istio.mcp.v1alpha1.MetadataOuterClass这个类是protobuf生成的，通过 ![image](https://user-images.githubusercontent.com/56863753/189792864-9b51c61a-8273-46e4-97b1-6b972ca3b115.png) 就能编译出来这个类

2.1.0我不知道，你这样的操作我试过好多次，编译后要么不生成要么直接报错编译通不过因为没有那个文件。
后面发现要先mvn clean，然后 mvn install 并且跳过测试。这时候target目录里面会有生成的文件，拷贝出来丢到项目中。这样才启动成功。。。

**Comment by hoErYu** [comment]
> 

我这选的是2.0.4的tag，我是直接clean然后compile，再配置vm单机参数就直接能启动了

**Comment by zh-Aispaly** [comment]
> > 
> 
> 我这选的是2.0.4的tag，我是直接clean然后compile，再配置vm单机参数就直接能启动了

![image](https://user-images.githubusercontent.com/32315687/189796940-666c7498-4d8b-415e-942b-18406e8bc0c4.png)
编译成功，但是你启动不了的，因为没有生成entity这个包，istio中也没有生成

**Comment by hoErYu** [comment]
![image](https://user-images.githubusercontent.com/56863753/189802340-7c9dc1e6-e77a-4996-b4d3-de5eddd2432f.png)
我刚刚试了compile找不到nacos-common等包，然后install再reload一下就可以启动了。就是按图里的123执行一遍就能启动了

**Comment by ArryLuo** [comment]
我按照上面的操作来，还是不行

**Comment by Wuzj-dev** [comment]
istio 里没有ResourceSourceGrpc.ResourceSourceImplBase 这个类？  其他类可以target目录里找到

**Comment by SoThisMint** [comment]
well naco is a pile of shit, how did u code like  that?
