### ISSUE TITLE
SSM框架集成nacos，在controller层获取不到最新的值

### ISSUE THREAD

**Issue by yue1998** [alibaba/nacos#9125]
nacos配置
![image](https://user-images.githubusercontent.com/30933030/189538875-281f3b38-1af8-4ada-b7c8-0ea8db15eaee.png)
nacos没修改之前的值：
![06567f8ed6e50c935307d530aedcd63](https://user-images.githubusercontent.com/30933030/189539270-fb92098b-09d2-42e8-9e69-9cd8e3a7d5f8.jpg)

修改之后controller层获取不到最新的值
![5b50c3d9f5e8b7986f98697f9c0027d](https://user-images.githubusercontent.com/30933030/189539238-4712f54f-330f-4fd2-b57c-4bf5e51928d6.jpg)

发现spring mvc获取不到nacos最新的值，只能从Environment中获取值，

**Comment by yue1998** [comment]
对应service层
![image](https://user-images.githubusercontent.com/30933030/189540354-1f506627-d451-427d-bacf-50de698d8cc1.png)

**Comment by yue1998** [comment]
对应nacos的值
![image](https://user-images.githubusercontent.com/30933030/189540891-d0cd35f1-9355-4bf1-9fc9-fc71e4546846.png)

**Comment by onewe** [comment]
建议去 SCA 社区提问
