### ISSUE TITLE
Remove redundant nullcheck code in ClientTrackService

### ISSUE THREAD

**Issue by jjastan** [alibaba/nacos#9135]
**Describe the bug**
In ClientTrackService#listSubStatus exists redundant nullcheck of record, which is known to be non-null
![image](https://user-images.githubusercontent.com/81030751/189845556-650838ad-58f3-4194-ad08-395a36b656b0.png)

**Expected behavior**
Remove the redundant nullcheck code

**Comment by chenhao26-nineteen** [comment]
PR Welcome @jjastan
