### ISSUE TITLE
nacos 1.4.4  nginx 转发报错

### ISSUE THREAD

**Issue by xinwwx** [alibaba/nacos#9143]
1.4.2 用nginx 转发请求到 nacos端口，请求登录都正常。
1.4.2升级到 1.4.4 单机启动后，登录提示密码错误，报如下错误。

2022-09-14 15:42:02,408 ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [/nacos] threw exception

java.lang.IllegalArgumentException: When allowCredentials is true, allowedOrigins cannot contain the special value "*" since that cannot be set on the "Access-Control-Allow-Origin" response header. To allow credentials to a set of origins, list them explicitly or consider using "allowedOriginPatterns" instead.

**Comment by KomachiSion** [comment]
Can you try to login without nginx?

**Comment by onewe** [comment]
这个问题是升级 spring 版本引起的, 1.x dev 分支已经修复了

**Comment by KomachiSion** [comment]
@onewe which PR, please comment in issue and mark this issue as `duplicated` and close this issue.

**Comment by onewe** [comment]
see https://github.com/alibaba/nacos/pull/8980
