### ISSUE TITLE
The mothod parseKey in GroupKey throws NullPointerException.

### ISSUE THREAD

**Issue by jjastan** [alibaba/nacos#9147]
**Describe the bug**
When I used the method GroupKey#parseKey, it throws NPE.
![image](https://user-images.githubusercontent.com/81030751/190302255-25529ba3-78b0-4707-ad0a-16bdceb50db4.png)

**Expected behavior**
Add assert for this method and the others such as:
    com.alibaba.nacos.config.server.utils.GroupKey2#parseKey
    com.alibaba.nacos.client.config.common.GroupKey#parseKey

**Comment by KomachiSion** [comment]
What's  the input values?

**Comment by jjastan** [comment]
> What's the input values?

null input throws NPE.
I think throws IllegalArgumentException like other in this method is better.

**Comment by KomachiSion** [comment]
which situation will input null?

**Comment by jjastan** [comment]
I'm not found situation input null and I will close the issue.
