### ISSUE TITLE
我想使用nacos的服务发现功能，把nacos-console模块作为依赖引入到自己的项目中但是项目无法启动

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#9148]
想要实现自己的项目导入nacos模块(依赖的形式)后具有对应模块的功能，因为不想在原有的nacos代码结构中添加自己的模块代码，启动后无法初始化上下文。
springboot 2.6.3
nacos  2.0.4 

![image](https://user-images.githubusercontent.com/59356890/190306252-d1d7777e-bbb9-4b86-9f8e-5fbec6fec391.png)
    
`
 

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-console</artifactId>
            <version>2.1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <artifactId>nacos-config</artifactId>
                    <groupId>com.alibaba.nacos</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>nacos-api</artifactId>
                    <groupId>com.alibaba.nacos</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>nacos-common</artifactId>
                    <groupId>com.alibaba.nacos</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>nacos-client</artifactId>
                    <groupId>com.alibaba.nacos</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-auth</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-config</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-core</artifactId>
            <version>2.1.0-SNAPSHOT</version>
        </dependency>
`

求路过大佬支个招 谢谢

**Comment by chenhao26-nineteen** [comment]
为什么不直接引入Nacos Client？或者和其他框架集成使用Nacos，譬如Spring Cloud Alibaba。

**Comment by Layfolk-zcy** [comment]
> 为什么不直接引入Nacos Client？或者和其他框架集成使用Nacos，譬如Spring Cloud Alibaba。

直接引入Spring Cloud Alibaba的pom的话服务只能作为客户端使用注册到官方提供的服务端jar上面  我是想自己搞一个服务端项目所以从git上拉的源码 但是又不想在这个源码项目上动他们的代码(我觉得我这想法有点子奇葩)所以把源码的每个项目install到本地供其他项目作为依赖引用

**Comment by chenhao26-nineteen** [comment]
你这样肯定不行。可以fork一份到你的仓库就，你可以任意修改你的仓库的代码。

**Comment by hoErYu** [comment]
![image](https://user-images.githubusercontent.com/56863753/190562557-c974a6ae-d072-45a6-b213-64c38556ec29.png)
你的把console的配置复制过来啊。
不过不知道你为啥要这么玩~
ps:我没打包2.0.4就将就用1.4.2的搞一搞

**Comment by Layfolk-zcy** [comment]
> ![image](https://user-images.githubusercontent.com/56863753/190562557-c974a6ae-d072-45a6-b213-64c38556ec29.png) 你得把console的配置复制过来啊。 不过不知道你为啥要这么玩~ ps:我没打包2.0.4就将就用1.4.2的搞一搞


![Uploading 1663309254(1).jpg…]()

**Comment by Layfolk-zcy** [comment]
> ![image](https://user-images.githubusercontent.com/56863753/190562557-c974a6ae-d072-45a6-b213-64c38556ec29.png) 你得把console的配置复制过来啊。 不过不知道你为啥要这么玩~ ps:我没打包2.0.4就将就用1.4.2的搞一搞

你好我尝试了下好像还是不行不能启动项目    这样玩就是怕到时自己动到了nacos源码自己又不知道太菜了唉
![1663309254(1)](https://user-images.githubusercontent.com/59356890/190570594-ce20a662-0f60-454c-b78a-08619da1017e.jpg)

![image](https://user-images.githubusercontent.com/59356890/190570712-d55b8c3c-442e-4100-a89a-e29080ee2c88.png)

**Comment by hoErYu** [comment]
我猜是你springboot的版本不对
试下用这个springboot版本2.3.2.RELEASE

**Comment by Layfolk-zcy** [comment]
> 我猜是你springboot的版本不对 试下用这个springboot版本2.3.2.RELEASE

版本时公司规定的  唉还是搞不定  我之间在nacos源码里面添加了自己的一个模块 在这个模块里面添加自己的代码   和配置文件可以成功启动
