### ISSUE TITLE
通过jasypt-spring-boot-starter加密server-addr后发现启动的时候没有解析

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#9150]
通过jasypt-spring-boot-starter加密地址地址之后，发现启动的时候nacos地址没有解密过来，但是启动后可以正确拿到这个地址；

启动的时候是这样的
`NacosConfigProperties{serverAddr='ENC(DpDR1jck98rNPM7C6UyIX5EiZFq76hA1K/2NcRst67M=)`
![image](https://user-images.githubusercontent.com/90117583/190326627-6b787932-43ea-4324-8549-28798c8624c4.png)
启动就后可以正常获取
![image](https://user-images.githubusercontent.com/90117583/190326659-e96cb1b9-f1c8-4d90-89ff-bb45e5e52d52.png)

**Comment by wuchubuzai2018** [comment]
这个应该和nacos没关系吧

**Comment by nomatterfine** [comment]
> 这个应该和nacos没关系吧

这个是没有关系 但是不是完全没有关系，我搞了几天都发现有问题，springboot已启动就去nacos拉取配置 ，但是本地的配置文件还没有解密就去拉取配置，拉取失败了；
应该是有个方法在配置文件解密之后nacos才去拉取配置；不知道怎么配置

**Comment by KomachiSion** [comment]
应该需要自己写一个解密component， 然后在bean依赖中设置在nacos的starter拉取配置前把serverAddr解密并且覆盖进去。

**Comment by nomatterfine** [comment]
是的，需要在nacos配置加载之前修改

**Comment by withbluebell** [comment]
遇到了同样的问题，密码加密了之后无法注册到nacos上，但是明文就可以。

**Comment by ants-g** [comment]
怎么解决的？

**Comment by frankywen** [comment]
> 是的，需要在nacos配置加载之前修改

请问是怎么解决的？
