### ISSUE TITLE
nacos cluster out of sync

### ISSUE THREAD

**Issue by eaglc** [alibaba/nacos#9151]
nacos version: v2.0.4

I create a nacos cluster with 3 nodes:
```
SPRING_DATASOURCE_PLATFORM = mysql
PREFER_HOST_MODE =hostname
NACOS_SERVERS = nacos-server-0.nacos-server.crystal.svc.cluster.local:8848 nacos-server-1.nacos-server.crystal.svc.cluster.local:8848 nacos-server-2.nacos-server.crystal.svc.cluster.local:8848
MYSQL_SERVICE_USER =root
MYSQL_SERVICE_PORT =3306
MYSQL_SERVICE_PASSWORD = 123456
MYSQL_SERVICE_HOST = nacos-mysql
MYSQL_SERVICE_DB_NAME = nacos_config
MODE = cluster
JVM_XMX = 256m
JVM_XMS = 256m
JVM_XMN = 128m
```

Then our application is registered to the nacos cluster as an ephemeral node with nacos-sdk/v2, everything looks ok now: In Service Management / Service List
But when I restart a node of nacos cluster, I can't found our application in "Service Management / Service List" of this node.

**Comment by wuchubuzai2018** [comment]
这个问题2.1版本有这个问题吗，我记得以前好像2.0.3版本节点重启后，客户端会出现GRPC无法连接的情况，2.1是不是解决了

**Comment by eaglc** [comment]
> 

我们在物理机上使用同一个版本搭建了集群，未发现上述问题。
大师在k8s上有问题，不明白问题在哪里。

**Comment by KomachiSion** [comment]
What's your error information in your application. please provide application's logs in `${user.home}/logs/nacos`

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
