### ISSUE TITLE
Nullcheck of value previously dereferenced

### ISSUE THREAD

**Issue by jjastan** [alibaba/nacos#9154]
**Describe the bug**
The method TpsMonitorManager#onEvent get value from event first, and then do null check for event. 
This may cause a NPE.
![image](https://user-images.githubusercontent.com/81030751/190344883-4e952071-45aa-4cf7-a378-11af4fd85959.png)

**Expected behavior**
move null check operate forward.

**Comment by chenhao26-nineteen** [comment]
PR Welcome
