### ISSUE TITLE
Nacos 2.1.0集群操作下线某台机器后不会自动断grpc连接引发故障

### ISSUE THREAD

**Issue by goto456** [alibaba/nacos#9155]
- 环境：Nacos 2.1.0，Dubbo 2.7.16
- 操作步骤：在Nacos 集群web管理页面，点击“下线”某个节点；
- 现象：只是将该节点机器从集群中剔除，但是还有dubbo的实例与下线的节点机器保持着grpc长连接并未断开；而此时该机器上的实例已经不全了，导致dubbo的服务发现出现故障。
- 期望：web页面点击“下线”某节点后，出发该下线的节点机器断开grpc连接，触发dubbo实例重新和其他未下线的节点机器建立连接。

**Comment by realJackSun** [comment]
”下线“按钮在早期点击之后，会断开gRPC连接的；但由于下线功能存在一些问题，后来后端把这个按钮暂时关闭了，但是前端还保留。

**Comment by realJackSun** [comment]
如果社区有朋友有兴趣，可以重新理一下这个下线和上线的逻辑

**Comment by goto456** [comment]
> 

是下线nacos集群的节点，不是下线dubbo的实例

**Comment by goto456** [comment]
> 如果是服务端节点的话，”下线“按钮在早期点击之后，会断开gRPC连接的；但由于下线功能存在一些问题，后来后端把这个按钮暂时关闭了，但是前端还保留。。如果社区有朋友有兴趣，可以重新理一下这个下线和上线的逻辑 ![image](https://user-images.githubusercontent.com/58767027/190360876-b730fbdb-1d0e-4cb0-bd88-b4f0432bde02.png)

我是nacos2.1.0版本，前端点击“下线”按钮后，其他集群节点的cluster.conf中把下线的这个节点的ip剔除了，但是grpc没断开，应该就是你说的这个意思吧。

**Comment by Daydreamer-ia** [comment]
不是，他的意思是在下线nacos集群节点后，dubbo消费端仍然会去调用到那台下线机器上注册的实例。这个问题，听起来不太像是nacos这边的问题，反而像是dubbo消费端那边的。可以考虑在nacos集群节点下线后，去做一下对所有客户端通知，类似ConfigChangeNotifyRequest那样，要求客户端刷线一下本地的服务列表，让dubbo重新与集群其他没有下线的节点上注册的实例建连，这样应该可以达到楼主的要求了。

**Comment by Daydreamer-ia** [comment]
> > 如果是服务端节点的话，”下线“按钮在早期点击之后，会断开gRPC连接的；但由于下线功能存在一些问题，后来后端把这个按钮暂时关闭了，但是前端还保留。。如果社区有朋友有兴趣，可以重新理一下这个下线和上线的逻辑 ![image](https://user-images.githubusercontent.com/58767027/190360876-b730fbdb-1d0e-4cb0-bd88-b4f0432bde02.png)
> 
> 我是nacos2.1.0版本，前端点击“下线”按钮后，其他集群节点的cluster.conf中把下线的这个节点的ip剔除了，但是grpc没断开，应该就是你说的这个意思吧。

 `data: "/v1/core/cluster/server/leave API not allow to use temporarily."`

**Comment by KomachiSion** [comment]
服务端下线接口有很多问题，最新版本已经禁用了，等待社区重新设计之后再补充。

**Comment by goto456** [comment]
> 服务端下线接口有很多问题，最新版本已经禁用了，等待社区重新设计之后再补充。

好的，感谢答疑

**Comment by Linzyoo** [comment]
请问下如果手动在cluster.conf中移除某个节点是否一样存在这个问题？谢谢。如果我手动移除前，现在SLB侧将该节点ip移除，再做cluster.conf 操作，是否就不会遇到此问题？
