### ISSUE TITLE
After upgrading to 1.0, Tip when registering for service: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers ([127.0.0.1) tried: failed to req API: 8848]) tried: failed to req API: http://127.0.0.1:8848/nacos/v1/ns/instance. Code:500 msg: ErrCode:400,ErrMsg:service not found, namespace: public, service: DEFAULT_GROUP@@gateway-server

### ISSUE THREAD

**Issue by savvyray** [alibaba/nacos#916]
After upgrading to 1.0, Tip when registering for service: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers ([127.0.0.1) tried: failed to req API: 8848]) tried: failed to req API: http://127.0.0.1:8848/nacos/v1/ns/instance. Code:500 msg: ErrCode:400,ErrMsg:service not found, namespace: public, service: DEFAULT_GROUP@@gateway-server. After communicating with Zhang long, it is found that the default mode of NACOS1.0 is mixed, which requires adding services manually before registering an instance, so it is hoped that the caller can be informed of the cause of failure, such as the current mode, when prompted for errors.

**Comment by caojiele** [comment]
To remove/nacos/v1 / ns/API/all of the interface, transferred to other URL, you can refer to this #651.

**Comment by nkorange** [comment]
'service not found' means you have to create service before registering instance. To remove this limit, you can execute the following command to run server in AP mode:
```
curl -X PUT '$NACOS_SERVER:8848/nacos/v1/ns/operator/switches?entry=serverMode&value=AP'
```
Refer to #745 to understand why different running modes are supported.

**Comment by fanchangjifen** [comment]
遇到了相同的问题。。切到0.9.0版本就好了。。。但是服务注册后在nacos控制台的服务列表里面不显示。。。

**Comment by yfh0918** [comment]
发自我的华为手机默认混合模式启动，需要用URL修改下启动模式为AP       put : http：//ip：8848/nacos/v1/ns/operator/switches?entry=serverMode&value=AP-------- 原始邮件 --------主题：Re: [alibaba/nacos] After upgrading to 1.0, Tip when registering for service: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers ([127.0.0.1) tried: failed to req API: 8848]) tried: failed to req API: http://127.0.0.1:8848/nacos/v1/ns/instance. Code:500 msg: ErrCode:400,ErrMsg:service not found, namespace: public, service: DEFAULT_GROUP@@gateway-server (#916)发件人：Gilbert 收件人：alibaba/nacos 抄送：Subscribed 遇到了相同的问题。。切到0.9.0版本就好了。。。但是服务注册后在nacos控制台的服务列表里面不显示。。。

**Comment by fanchangjifen** [comment]
集群模式，返回信息server is DOWN now, please try again later!，但是控制台登录正常

**Comment by slievrly** [comment]
mark

**Comment by nkorange** [comment]
Fixed in 1.0.0-RC2

**Comment by bearwind** [comment]
> 集群模式，返回信息server is DOWN now, please try again later!，但是控制台登录正常

1.0.0-RC3依然有此问题，集群模式启动，一切正常，但是其中一个服务一直报这个错，console正常，查看该服务日志，心跳通讯都正常，重启依然如此
@nkorange

**Comment by nkorange** [comment]
@bearwind 稍等一会就行，否则可以看下 {nacos.home}/logs/naming-ephemeral.log是不是有报错

**Comment by bearwind** [comment]
> @bearwind 稍等一会就行，否则可以看下 {nacos.home}/logs/naming-ephemeral.log是不是有报错
等了很久还是这样 log一直报如下错误，麻烦看下：
```
2019-04-09 10:51:52,936 INFO waiting server list init...

2019-04-09 10:51:53,936 INFO waiting server list init...

2019-04-09 10:51:54,937 INFO waiting server list init...

2019-04-09 10:51:55,937 INFO waiting server list init...

2019-04-09 10:51:56,076 ERROR receive responsible key timestamp of com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@daoji-gateway from 192.168.88.87:8848

2019-04-09 10:51:56,937 INFO waiting server list init...

2019-04-09 10:51:57,896 DEBUG sync checksums: {com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@daoji-task=947f7c1338041b2cb3fc16d2ea115cda, com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@daoji-tourism=cf75e3171cdc1775619b77ada918b864}
```

**Comment by javais** [comment]
1.0.0同样是这个问题（server is DOWN now, please try again later!）

**Comment by nkorange** [comment]
@javais 请重开一个issue，我们会跟进。当前这个issue主题并不是你描述的那个问题
