### ISSUE TITLE
Error on upgrade nacos-server from 2.0.3 to 2.1.1

### ISSUE THREAD

**Issue by zqr95518** [alibaba/nacos#9161]
**Describe the bug**
Unknown column 'encrypted_data_key' in 'field list'

**Expected behavior**
Run without error.

**Actually behavior**
Unknown column 'encrypted_data_key' in 'field list'

**How to Reproduce**
1. upgrade nacos-server from 2.0.3 to 2.1.1

**Desktop (please complete the following information):**
 - nacos-mysql:8.0.16

**Additional context**
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.1.1.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
PreparedStatementCallback; bad SQL grammar [SELECT id,data_id,group_id,tenant_id,app_name,content,md5,gmt_modified,type,encrypted_data_key FROM config_info WHERE id > ? ORDER BY id ASC LIMIT ?,?]; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'encrypted_data_key' in 'field list'

```

**Comment by wuchubuzai2018** [comment]
这个是2.1版本新增的字段，2.1版本对相关的几个表增加了encrypted_data_key，去查看2.1版本的表SQL吧

**Comment by zqr95518** [comment]
但是nacos-mysql没有发布新版本，server升级的时候也没有做兼容处理，直接报错了，手动改不合理。

**Comment by hoErYu** [comment]
nacos-config模块里的resources/META-INF/nacos-db.sql里面有最新的sql
或者你直接在你的数据库给config_info， his_config_info，config_info_beta这三张表加上这个字段
![image](https://user-images.githubusercontent.com/56863753/190604046-f47ac4cc-1435-4e6d-a82d-00ea0a754b1f.png)

**Comment by zqr95518** [comment]
手动操作是可以的，但是现场升级的时候库都在容器里访问都访问不到怎么改，有计划做自动升级么？

**Comment by KomachiSion** [comment]
> 但是nacos-mysql没有发布新版本，server升级的时候也没有做兼容处理，直接报错了，手动改不合理。 @wuchubuzai2018

https://github.com/alibaba/nacos/blob/develop/distribution/conf/mysql-schema.sql

apply new sql file.
