### ISSUE TITLE
nacos2.1.1升级后，nacos服务端一直返回动态配置可刷新

### ISSUE THREAD

**Issue by ypp614925919** [alibaba/nacos#9163]
项目一启动，调用动态刷新配置线程从nacos服务端获取到的一直是有配置更改，但是我没有进行配置的修改

**Comment by KomachiSion** [comment]
提供下应用配置文件，以及所订阅配置的ns,group,dataId.

**Comment by ypp614925919** [comment]
group:DEFAULT_GROUP,&nbsp; dataId:cipher-aes-jac-gateway-dev.yml



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 上午9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] nacos2.1.1升级后，nacos服务端一直返回动态配置可刷新 (Issue #9163)





 
提供下应用配置文件，以及所订阅配置的ns,group,dataId.

**Comment by ypp614925919** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 上午9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] nacos2.1.1升级后，nacos服务端一直返回动态配置可刷新 (Issue #9163)





 
提供下应用配置文件，以及所订阅配置的ns,group,dataId.

**Comment by ypp614925919** [comment]
spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      username: ${LOAN_NACOS_USERNAME:}
      password: ${LOAN_NACOS_PASSWORD:}
      # 服务注册与发现地址
      server-addr: @nacos.server.addr@
      discovery:
        ## IP 容器启动注入
        ip: ${NETWORK_IP:}
        port: ${server.port}
        namespace: ${LOAN_NACOS_NAMESPACE:}
      config:
        namespace: ${LOAN_NACOS_NAMESPACE:}
        # 配置文件后缀
        file-extension: yml
        prefix: cipher-aes-${spring.application.name}-${spring.profiles.active}
        # 公共配置文件
#        shared-configs:
#          - market-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
#        refreshable-dataids: market-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        extension-configs:
          - data-id: cipher-aes-jac-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            refresh: true

**Comment by ypp614925919** [comment]
`spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      username: ${LOAN_NACOS_USERNAME:}
      password: ${LOAN_NACOS_PASSWORD:}
      # 服务注册与发现地址
      server-addr: @nacos.server.addr@
      discovery:
        ## IP 容器启动注入
        ip: ${NETWORK_IP:}
        port: ${server.port}
        namespace: ${LOAN_NACOS_NAMESPACE:}
      config:
        namespace: ${LOAN_NACOS_NAMESPACE:}
        # 配置文件后缀
        file-extension: yml
        prefix: cipher-aes-${spring.application.name}-${spring.profiles.active}
        # 公共配置文件
#        shared-configs:
#          - market-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
#        refreshable-dataids: market-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        extension-configs:
          - data-id: cipher-aes-jac-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            refresh: true`

**Comment by ypp614925919** [comment]
spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      username: ${LOAN_NACOS_USERNAME:}
      password: ${LOAN_NACOS_PASSWORD:}
      # 服务注册与发现地址
      server-addr: @nacos.server.addr@
      discovery:
        ## IP 容器启动注入
        ip: ${NETWORK_IP:}
        port: ${server.port}
        namespace: ${LOAN_NACOS_NAMESPACE:}
      config:
        namespace: ${LOAN_NACOS_NAMESPACE:}
        # 配置文件后缀
        file-extension: yml
        prefix: cipher-aes-${spring.application.name}-${spring.profiles.active}
        extension-configs:
          - data-id: cipher-aes-jac-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            refresh: true



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2022年9月19日(星期一) 上午9:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] nacos2.1.1升级后，nacos服务端一直返回动态配置可刷新 (Issue #9163)





 
提供下应用配置文件，以及所订阅配置的ns,group,dataId.

**Comment by KomachiSion** [comment]
what's the LOAN_NACOS_NAMESPACE value?

**Comment by ypp614925919** [comment]
nacos 的命名空间值&nbsp; jac-aes



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 下午2:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] nacos2.1.1升级后，nacos服务端一直返回动态配置可刷新 (Issue #9163)





 
what's the LOAN_NACOS_NAMESPACE value?

**Comment by KomachiSion** [comment]
provide ${user.home}/logs/nacos/config.log in your application.

**Comment by MonaLisaFineHair** [comment]
我在1.2.1 版本中遇到过问题，MD5工具类的问题，也有可能是服务端的MD5和客户端的MD5不一致；楼主的问题是否和这个问题类似 https://github.com/alibaba/nacos/issues/2722

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
