### ISSUE TITLE
springCloud 整合nacos服务发现  服务注册成功但是feign服务发现时调用失败 同一套代码使用eureka进行feign调用正常

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#9169]
springBoot 2.6.3
spring-cloud-dependencies 2021.0.1
spring-cloud-alibaba-dependencies 2021.0.1.0

nacos服务端使用的是1.4.2   nacos控制台中服务已经注册成功

`       
       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
`

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>`
![image](https://user-images.githubusercontent.com/59356890/190881946-4d7c8ae9-8269-4094-baaf-12cd6f3042bf.png)
![image](https://user-images.githubusercontent.com/59356890/190881953-1fd3f1ca-d9bb-493a-8f36-acfd33450d74.png)

![image](https://user-images.githubusercontent.com/59356890/190881991-339902d5-b301-4093-836d-36975434e49b.png)

**Comment by KomachiSion** [comment]
Please move to Spring cloud alibaba community find the answer.

**Comment by Layfolk-zcy** [comment]
> Please move to Spring cloud alibaba community find the answer.

去 Spring cloud alibaba community找什么意思   能不能在具体点
