### ISSUE TITLE
Once the service discovery is started separately, access the index page and see the config message

### ISSUE THREAD

**Issue by yyt701** [alibaba/nacos#917]
1. Start service discovery （naming） separately for testing;
2. Visit the home page, will display configuration management related information content
![微信图片_20190317004259](https://user-images.githubusercontent.com/685567/54478453-46432d00-484d-11e9-8112-6c2a56b61dc4.png)

**Comment by nkorange** [comment]
Already fixed in 1.0.0-RC2
