### ISSUE TITLE
Nacos 2.1.1，ldapLogin，only filter by uid

### ISSUE THREAD

**Issue by quan8888** [alibaba/nacos#9175]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

LDAP登录，发现源码是直接写死的，只能通过uid搜索筛选，这么写不太通用？
比如我公司的LDAP员工数据就没有uid这个字段；
本地调试，修改为其他字段（已有的）如sAMAccountName或mail，是通的，可以搜到相关用户。

LDAP login, found that the source code is directly written dead, can only be filtered through the UID search, so write not too common?  
For example, my company's LDAP employee data does not have the UID field.  
Local debugging, changing to other fields (existing) such as sAMAccountName or mail, is passable and can be searched for the relevant user.

![企业微信截图_a9b9ddc4-2d4a-4b3b-9fc7-994aede3138a](https://user-images.githubusercontent.com/52630628/191008051-6adc96f0-fae3-4a04-8357-cebc0a3c2d84.png)

### How to reproduce it (as minimally and precisely as possible)

能直接通过配置文件，支持各种字段搜索最好，这样就可以直接用官方镜像，不用修改源码，再打包，打镜像了

Can directly through the configuration file, support a variety of fields search best, so that you can directly use the official image, without modifying the source code, and then packaging, mirroring

**Comment by karsonto** [comment]
@i will resolve it@

**Comment by quan8888** [comment]
速度太快了，非常感谢大佬。
不知道啥时候，哪个版本能用上？就等着这个了

**Comment by karsonto** [comment]
这个要先合并后，在下个release版本才能使用。

**Comment by quan8888** [comment]
> 

这边有大概的发版计划吗？下一个release版本
