### ISSUE TITLE
在源码的工程中添加自己的模块后引入nacos-console后定义controller层无法被访问。服务能正常启动

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#9176]
自己的模块中引入的nacos-console模块，并且把nacos-console模块中的META-INF和properties文件拿到了自己的模块中。自己的项目想要连接的Oracle
`

       <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>nacos-console</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>${hutool.version}</version>
        </dependency>

        <dependency>
            <groupId>com.sunyard.staging.framework.starters</groupId>
            <artifactId>staging-framework-starter-springboot-redis</artifactId>
            <version>2.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>${org.bouncycastle.bcprov-jdk15on.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>${redisson.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-pool2</artifactId>
            <version>${lettuce.version}</version>
        </dependency>

        <dependency>
            <artifactId>staging-framework-starter-alibaba-druid</artifactId>
            <groupId>com.sunyard.staging.framework.starters</groupId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>${druid.starter.version}</version>
        </dependency>

        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc6</artifactId>
            <version>${com.oracle.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.ethz.ganymed</groupId>
            <artifactId>ganymed-ssh2</artifactId>
            <version>${ch.ethz.ganymed.ganymed-ssh2.version}</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mysql-connector-java.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
`

![image](https://user-images.githubusercontent.com/59356890/191155342-2e9d2709-a870-40b9-be20-5539764d1835.png)

猜测是Security拦截了请求所以就修改了nacos-console里面的NacosAuthConfig在自己模块下的META-INFO下添加了忽略路径，
但是好像还是没有效果
![image](https://user-images.githubusercontent.com/59356890/191155858-55a6e7c2-f70e-46dd-a8ea-1738d65b7409.png)

**Comment by karsonto** [comment]
参考一下 https://gitee.com/log4j/pig 里面的 pig-register 模块，看看是不是你想要的效果？

**Comment by Layfolk-zcy** [comment]
> 参考一下 https://gitee.com/log4j/pig 里面的 pig-register 模块，看看是不是你想要的效果？

非常感谢 这个和我想要的正好类似  但是按照对应的方式构建的时候 添加oracle的时候一直有问题  唉不太懂

`
Caused by: java.lang.IllegalStateException: dbType not support : derby, url jdbc:derby:memory:testdb;create=true
`

**Comment by KomachiSion** [comment]
说明你没有配置成是oracle， 还是使用的derby，这部分需要你自己修改源码去改了。
