### ISSUE TITLE
Please update spring-cloud-starter-alibaba-nacos-config version

### ISSUE THREAD

**Issue by suncunhu** [alibaba/nacos#918]
## Issue Description

Now , Spring Cloud Starter Alibaba Nacos Config is 0.2.1.RELEASE

Nacos Latest release is 1.0.0-RC1

Whether there is nacos client Jar release timeline ?

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
Should be a [SpringCloudAlibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) issue
