### ISSUE TITLE
手动下线某个服务（被下线的服务需要更新版本），待此服务更新重启后服务不自动上线。需手动点上线按钮！

### ISSUE THREAD

**Issue by 3721518** [alibaba/nacos#9180]
Nacos版本：
  Nacos-server：2.0.3
  Nacos-client：1.4.1
问题描述：
  某个微服务需要更新。在Nacos服务端手动点击"下线"按钮并开始更新此服务。
  待服务更新并重启完成后，在Nacos服务端查看此微服务并且此服务的在线状态不发生改变，还是下线状态。需要手动点上线才可以实现服务上线。
需求：
  需要在更新了服务后，将此服务的状态由下线状态自动更新为已上线或在线状态。

**Comment by Daydreamer-ia** [comment]
服务端要求服务实例下线了，既然这是服务端的决定。不应该受到客户端影响才对吧

**Comment by 3721518** [comment]
是的
另一种情况：
Nacos-server：1.4.0
Nacos-client：1.4.1
此版本运行的服务并在遇到更新服务时，表现出来的现象是，手动点击实例下线，待更新重启后会自动上线了。
请问这个版本跟2.x版本有什么不一样吗？

**Comment by YunWZ** [comment]
> 是的 另一种情况： Nacos-server：1.4.0 Nacos-client：1.4.1 此版本运行的服务并在遇到更新服务时，表现出来的现象是，手动点击实例下线，待更新重启后会自动上线了。 请问这个版本跟2.x版本有什么不一样吗？

2.x版本的功能,如果从控制台主动(手动)下线某个服务实例,那么即使这个实例后续注册上来了,也是*不可用*状态.

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/open-api.html

**Comment by 3721518** [comment]
> https://nacos.io/zh-cn/docs/open-api.html

还请您回答下这个问题，谢谢！！！
Nacos-server：1.4.0 Nacos-client：1.4.1 此版本运行的服务并在更新微服务时表现出来的现象是，手动点击实例下线，待更新重启后手动下线的微服务实例会自动上线（无需再次手动点击上线）。
Nacos-server：2.0.3 Nacos-client：1.4.1 ，请问这个版本下为什么实现不了跟上面同样功能？

**Comment by 3721518** [comment]
看到我想要的答案，谢谢！

**Comment by wa3926** [comment]
@3721518  请问下你是怎么解决的 遇到和你一样的问题
