### ISSUE TITLE
nacos配置列表页面能否支持按Group分组来展示Data Id？

### ISSUE THREAD

**Issue by baoachun** [alibaba/nacos#9182]
![image](https://user-images.githubusercontent.com/22114318/191233411-25174210-7491-4874-8524-09616d7a4239.png)

Group作为一级目录，相同Group的Data Id聚合起来作为二级目录展示，否则机器太多配置显示很乱

**Comment by chenhao26-nineteen** [comment]
你指的是把group显示和namespace显示一样？点击显示group内存在的dataId？

**Comment by baoachun** [comment]
> 你指的是把group显示和namespace显示一样？点击显示group内存在的dataId？

是的，否则一个Group下面有几十个dataid都平铺展示很乱，group这个字段也失去意义了，如果用namespace来区分的话，页面上面namespace那一行会很长。由于是公司的内部页面，暂时无法截图展示

**Comment by KomachiSion** [comment]
过滤条件那里写对应的group不行吗？
