### ISSUE TITLE
nacos配置中心 内嵌数据库+集群模式 是不是也会脏读

### ISSUE THREAD

**Issue by niushihao** [alibaba/nacos#9183]
集群+内嵌数据库模式因为直接读文件(依赖dump的一致性读),但是真正的读操作并没有走一致性读,所以是不是会出现脏读。

比如集群中有A,B,C三个节点 写操作发生后 A,B已经应用了状态机,并触发了dump，c节点还没触发。
此时客户端发起读操作,第一次请求到A或B节点,第二次请求 请求到C节点 (此时依然没有触发同步) 这样就会出现脏读吧

如果是这样为什么前边大费周章走raft的写和dump时走一致性读,却在最后一步读文件导致前边做的都没用了。

**Comment by niushihao** [comment]
2.1.1版本

**Comment by chuntaojun** [comment]
1. 客户端的读取操作，nacos采取的原则为尽可能走cache中进行获取
2. raft中dump之所以要走一致性读，因为 dump 是需要从存储中拉取最新的数据进行 dump 到 cache 层中
3. raft的写是为了保证集群各个节点数据一致，dump的一致性读是保证每个节点dump到cache层中的数据一致，读文件其本质是读缓存，减少对于存储层（一致性层）的读取压力

**Comment by KomachiSion** [comment]
dump配置数据成缓存是为了减少对数据库/raft leader的读压力而做的最终一致性缓存。 简单的说就是读写分离，写操作保证了绝对一致，读操作仅保证最终一致，没有事务性保证。
