### ISSUE TITLE
receive invalid redirect request from peer 导致节点数据脑裂

### ISSUE THREAD

**Issue by Jason-Yu-RD** [alibaba/nacos#9184]
**问题描述：**
生产环境，nacos节点运行一段时间突然出现节点服务注册数据脑裂，导致服务列表获取异常。观察nacos日志，有大量的receive invalid redirect request from peer 报错，报错的节点列表均为nacos 集群ip，出现周期大概每月1次，无征兆触发，管理端查看集群节点状态均正常，但服务列表各节点数据不一致，导致部分应用未注册上 或部分服务节点缺失。日志如图：
![image](https://user-images.githubusercontent.com/20910068/191397213-76a4aa73-0314-49ab-8be6-76ef0cf2add5.png)

除集群外，client端无报错。

**使用版本**
集群版本：2.0.4
client版本：1.1.4
系统：k8s，centos7.4

**使用场景**
动态接口注册，nacos作为注册中心。
服务节点：tomcat应用，单个应用节点上会动态注册多个业务服务接口，统一使用相同的 tomcat ip+端口，使用nacos client注册临时应用ip:端口至nacos，业务ID做应用标识，维持nacos心跳。
网关：从nacos获取服务列表，做服务动态路由。路由到服务节点后，通过业务ID在找到具体服务接口进行业务处理并返回。

**问题**
1. 什么原因导致的数据脑裂？集群节点循环redirect造成的？
2. 循环redirect 的原因？
3. 单个应用上，使用相同的ip+端口，应用ID不同，注册不同的服务应用到nacos，并维持心跳，这种方式是否有问题。

**Comment by KomachiSion** [comment]
这个问题大概率是集群搭建有问题，集群节点列表在每个节点都不一致导致的计算责任节点不一致。

**Comment by KomachiSion** [comment]
看下每个节点的cluster.conf文件是不是一致的

**Comment by Jason-Yu-RD** [comment]
> 看下每个节点的cluster.conf文件是不是一致的

感谢回复，确认了下所有节点下的cluster.conf文件都是一致的，而且集群状态目前正常，偶尔会出现的节点数据脑裂，而且不会自动恢复，只能重启集群解决，请问还有什么其他排查方向？

**Comment by KomachiSion** [comment]
需要在出问题的时候看，如果是一致的情况下，就看下nacos-server.log 以及 nacos-cluster.log 中的healthy list日志是否一致。

**Comment by Jason-Yu-RD** [comment]
> nacos-server.log

您好，看了下历史日志，在出现问题的时间点，nacos-cluster.log 在该时间段无日志。没有nacos-server.log文件

**Comment by KomachiSion** [comment]
> > nacos-server.log
> 
> 您好，看了下历史日志，在出现问题的时间点，nacos-cluster.log 在该时间段无日志。没有nacos-server.log文件，指naming-server.log? ![image](https://user-images.githubusercontent.com/20910068/191886139-e1b48e57-feb8-42c7-a5e7-7a8050173846.png)

对 naming-server.log

**Comment by Jason-Yu-RD** [comment]
> 对 naming-server.log
看了下，这个时间段内 health list 各个节点检查都是没有问题的
![image](https://user-images.githubusercontent.com/20910068/191905878-e8d01352-1574-4d65-8f55-d2adb6c1ee29.png)

但是排查这个日志发现，在12：23分左右，开始出现 ERROR receive invalid redirect request from peer，所有节点报错都指向的都是同一个ip，11.247.28.241，之后集群出现数据脑裂，业务告警。
![image](https://user-images.githubusercontent.com/20910068/191906177-d507c1df-0e87-4b2a-ae04-6ba4ab2da1de.png)

看 11.247.28.241 这台机器上日志，这个时间点 出现 ERROR receive invalid redirect request from peer，报错指向的是其他所有IP。
![image](https://user-images.githubusercontent.com/20910068/191907440-2d8e5533-3b68-4d1b-b463-d7ee3b33eb6e.png)

之后由该节点触发了大量的[AUTO-DELETE-IP] 导致服务注册列表异常。
![image](https://user-images.githubusercontent.com/20910068/191907792-4fae4078-81aa-457d-957c-4cb6453ebab7.png)

请问引发的原因是什么？该如何继续排查？

**Comment by KomachiSion** [comment]
NACOS-DISTRO中 new比old多了一个ip，118， 是扩容操作了吗？还是多出一个无效ip？ 多一个ip会导致每个节点计算的责任节点不同。

**Comment by Jason-Yu-RD** [comment]
> NACOS-DISTRO中 new比old多了一个ip，118， 是扩容操作了吗？还是多出一个无效ip？ 多一个ip会导致每个节点计算的责任节点不同。

没有增加ip，118在old里面也有，最后一条，换行了。new 和 old ip列表是一致的。
![image](https://user-images.githubusercontent.com/20910068/192202106-3035aa65-4990-4c75-9653-1908b2e05970.png)

**Comment by Sulbsld** [comment]
Şifre sıfırlama


26 Eyl 2022 Pzt 08:46 tarihinde Jason-Yu-RD ***@***.***> şunu
yazdı:

**Comment by Jason-Yu-RD** [comment]
> NACOS-DISTRO中 new比old多了一个ip，118， 是扩容操作了吗？还是多出一个无效ip？ 多一个ip会导致每个节点计算的责任节点不同。

IP列表前后没有变更，请问如何继续排查问题？为什么 11.247.28.241 IP会被认为invalid redirect request？ 而且 这个节点触发了[AUTO-DELETE-IP] ，看源码只有心跳超时才会触发，目前来看网络都是正常的，触发原因是什么？

**Comment by KomachiSion** [comment]
原理是收到请求之后，会根据监控的节点实例，进行hash计算， 算出来这个请求应该由哪个节点负责，如果不是本节点负责就会路由到对应责任节点负责。

如果A节点认为这个请求是B节点处理，转发到B节点之后，B节点也计算了hash，发现不是自己节点处理，就会显示这个错误。

根据原理，很好理解，就是A，B节点的hash算法不同或者健康节点列表不同导致的。

往下排查方向就是：
1. 每个节点的服务端健康列表都一致（就是上文中说到的healthy server list）
2. 另一种可能就是某些节点升级到了2.X，某些节点还是1.X， 因为2.X是根据ip+port来计算hash，而1.X是根据服务名计算hash，如果算法不同也会导致这个问题。

**Comment by Jason-Yu-RD** [comment]
> 原理是收到请求之后，会根据健康的节点实例列表，进行hash计算， 算出来这个请求应该由哪个节点负责，如果不是本节点负责就会路由到对应责任节点负责。
> 
> 如果A节点认为这个请求是B节点处理，转发到B节点之后，B节点也计算了hash，发现不是自己节点处理，就会显示这个错误。
> 
> 根据原理，很好理解，就是A，B节点的hash算法不同或者健康节点列表不同导致的。
> 
> 往下排查方向就是：
> 
> 1. 每个节点的服务端健康列表都一致（就是上文中说到的healthy server list）
> 2. 另一种可能就是某些节点升级到了2.X，某些节点还是1.X， 因为2.X是根据ip+port来计算hash，而1.X是根据服务名计算hash，如果算法不同也会导致这个问题。

对于方向2，都是使用docker镜像统一部署的，可以排除这个问题。
对于方向1，有些疑问：
1. 首先集群本身就有一致性协议，故障发生时，集群节点状态均为健康状态，说明对应节点未宕机，网络端口是通的，这时候出现healthy server list不一致的情况的可能性是healthy check 线程阻塞，未及时上报心跳，导致短暂的不一致，出现责任不一致？或者其他造成healthy server list 不一致的情况有哪些可能？
2. 当出现healthy server list 不一致时，请求1被 serverA 转发 到serverB，serverB hash计算不是本节点进行处理，之后再次转发，请求1会不会一致redirect？还是在serverB就进行了丢弃？
3. 看问题出现时的日志，healty server list 都未发生变化，这个是否绝对准确？

**Comment by KomachiSion** [comment]
1. 网络不通、healthy check失败、cluster.conf不一致都会导致healthy server list不一致
2. 路由转发只会进行一次，如果是路由的请求非本节点处理是直接丢弃快速失败，避免循环转发导致线程耗尽。
3. 准确，但是是单节点视角。

**Comment by Jason-Yu-RD** [comment]
> 2\. 另一种可能就是某些节点升级到了2.X，某些节点还是1.X， 因为2.X是根据ip+port来计算hash，而1.X是根据服务名计算hash，如果算法不同也会导致这个问题。

您好，按照您给的思路排查了一下，发现问题出现的原因在于 11.247.28.241 这个节点在故障时间点做了upgrade，由 com.alibaba.nacos.naming.core.v2.upgrade.UpgradeJudgement#initUpgradeChecker中定时任务触发，正如日志里面体现的这个时间点触发了 Upgrade to 2.0.X，之后出现节点路由异常。
![image](https://user-images.githubusercontent.com/20910068/195279018-6b6da7ee-3d0f-48da-81ef-fcf93c7289cc.png)


追踪了下代码，触发原因在于节点元数据中 readyToUpgrade属性，当所有节点元数据均为true时，触发升级操作。 看了下当前节点元数据，只有 11.247.28.241 节点的 readyToUpgrade 为true，其他均为false。

1. 搭建集群时，该节点没有特殊处理，为何元数据中 readyToUpgrade  与其他不同？
