### ISSUE TITLE
nacos-server:2.0.3 upgrade check result false 如何解决？

### ISSUE THREAD

**Issue by hillbun** [alibaba/nacos#9185]
启动了3个statefulset, 
其中  nacos-0 一直  upgrade check result false
nacos-1 和 nacos-2 成功了 Upgrade to 2.0.X

是不是在 conf/application.properties 配置
nacos.core.support.upgrade.from.1x=false
或者JVM设置参数 -Dnacos.core.support.upgrade.from.1x=false  能够解决这个问题？

**Comment by KomachiSion** [comment]
如果没有历史的升级负担， 直接升级到2.1.1版本吧

如果需要升级，这个时候可以直接用命令关闭双写。

https://nacos.io/zh-cn/docs/2.0.0-upgrading.html

**Comment by hillbun** [comment]
通过 nacos.core.support.upgrade.from.1x=false 配置是无法解决的吗？

通过 curl -X PUT 'localhost:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false' 关闭双写的话，每次重启后，是不是都回失效，需要重新执行？

**Comment by KomachiSion** [comment]
> 通过 nacos.core.support.upgrade.from.1x=false 配置是无法解决的吗？
> 
> 通过 curl -X PUT 'localhost:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false' 关闭双写的话，每次重启后，是不是都回失效，需要重新执行？

2.1.0之后才支持这个参数。 2.0.x不支持.  2.1.0之后这个参数默认就是false

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
