### ISSUE TITLE
Nacos client connect to server failed

### ISSUE THREAD

**Issue by steverao** [alibaba/nacos#9186]
**Describe the bug**
Nacos client connect to server failed

**How to Reproduce**
in nacos-client 1.4.3 and 2.x, if I set the server address as follows:
`spring.cloud.nacos.discovery.server-addr=nacos-server:8848`
it will cause connect server failed

**Desktop (please complete the following information):**
in nacos-client 1.4.3 and 2.x, if I set the server address as follows:
`spring.cloud.nacos.discovery.server-addr=nacos-server:8848`
it will cause connect server failed, I found it's the reason from domain check. it think `nacos-server` isn't a standard domain, but in Kubernetes, we use non-standard domain name like above, that is very normal, maybe we need to give up the redundant checks.

**Comment by KomachiSion** [comment]
In 1.4.3, nacos community add a check for domain following the DNS standard. 
But k8s is not match the domain standard and define its standard.

I think the best way is remove the domain check and only check the input of serverAddr is not empty. 
For the domain whether can parse to IP, I think nacos should not pay attention to .

**Comment by Daydreamer-ia** [comment]
> In 1.4.3, nacos community add a check for domain following the DNS standard. But k8s is not match the domain standard and define its standard.
> 
> I think the best way is remove the domain check and only check the input of serverAddr is not empty. For the domain whether can parse to IP, I think nacos should not pay attention to .

Yes, I think so. I'm learning this part of nacos. If it's convenient, can you assign it to me

**Comment by KomachiSion** [comment]
After my test, I found the 2.1.1 and 1.4.4 both can connect server with domain like `nacos-server`. So I think it's your network problem.

I set local `hosts` nacos-server as 127.0.0.1 and it works well.
