### ISSUE TITLE
After upgrading to 2.1.0 Occurred  java.io.FileNotFoundException: https://nacos.io/schema/nacos.xsd

### ISSUE THREAD

**Issue by lizhibo0914** [alibaba/nacos#9189]
I upgraded NACOS from 1.1.4 to 2.1.0 in the Spring MVC project. The versions of other JAR packages of NACOS refer to Figure 1. The Spring version is 5.2.5. Configuring XSD in IDEA does not work either
![image](https://user-images.githubusercontent.com/27732536/191462139-3d3d7c15-6ee6-40a4-93e9-cb8ee6a1514e.png)
![image](https://user-images.githubusercontent.com/27732536/191461850-1d736faa-dd79-4cdf-a587-960d41ee277b.png)
![image](https://user-images.githubusercontent.com/27732536/191461922-2b67fcf5-a783-4d3c-9be8-529a825cd24a.png)

**Comment by hujun-w-2** [comment]
can you provider a demo,i will debug it locally

**Comment by wuchubuzai2018** [comment]
可能是引入nacos-spring-context的依赖包有点问题吧，声明XML的方式，jar包里面的spring.schemas文件可能没有被加载到
