### ISSUE TITLE
nacos2.1.1连接mysql8BUG

### ISSUE THREAD

**Issue by this-ren** [alibaba/nacos#9191]
后面我换了一个线上的数据库，这次报错里的IP是对的，但依然无法连接。。。

我docker启动命令是172.17.0.3，但nacos日志显示： Access denied for user 'root'@'172.17.0.2' (using password: YES)

`docker run -d \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=172.17.0.3 \
-e MYSQL_SERVICE_USER=nacos \
-e MYSQL_SERVICE_PASSWORD=nacos \
-e MYSQL_SERVICE_DB_NAME=nacos_config \
-e MYSQL_SERVICE_DB_PARAM=allowPublicKeyRetrieval=true \
-p 8848:8848 \
--restart=always \
--name nacos \
nacos/nacos-server:v2.1.1`

org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'172.17.0.2' (using password: YES)
...
2022-09-21 19:42:00,574 ERROR [master-db] master db not found.

2022-09-21 19:42:01,618 ERROR [db-error] master db 172.17.0.3 down.

2022-09-21 19:42:01,866 WARN isQuickStart:false

2022-09-21 19:42:01,869 ERROR Nacos Server did not start because dumpservice bean construction failure :
java.lang.IllegalStateException: No DataSource set

**Comment by realJackSun** [comment]
application.properties里面关于MySQL的配置确认是正确的哈？

另外MySQL有没有设置白名单

**Comment by KomachiSion** [comment]
Access denied for user 'root'@'172.17.0.2' (using password: YES)

数据库用户名密码不对，或者权限不足。
