### ISSUE TITLE
nacos作为配置中心，dataId中的项目名不能有大写和横杠吗

### ISSUE THREAD

**Issue by nomatterfine** [alibaba/nacos#9194]
nacos作为配置中心，dataId中的项目名不能有大写和横杠吗

**Comment by chenhao26-nineteen** [comment]
可以有，你是什么场景有问题？

**Comment by nomatterfine** [comment]
config:
    import:  
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
如果应用名有大写或者横杠就无法加载配置

**Comment by nomatterfine** [comment]
config:
    import:  
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
如果应用名有大写或者横杠就无法加载配置

**Comment by KomachiSion** [comment]
nacos没有这个限制，可以看${user.home}/logs/nacos/config.log 看下是不是已经收到了新配置。

**Comment by nomatterfine** [comment]
> nacos没有这个限制，可以看${user.home}/logs/nacos/config.log 看下是不是已经收到了新配置。

这个感觉是个bug，例如用facecompare作为项目名称，会拉去facecompare下的配置；
但是我把用faceCompare作为项目名，结果还是拉取的facecompare配置；
好像是忽略了项目名称的大小写了

**Comment by KomachiSion** [comment]
应该没有这个变化， dataid应该都是敏感的，看下社区是否有人能复现。

**Comment by nomatterfine** [comment]
定位到问题了，是因为k8s搭建的nacos有问题
