### ISSUE TITLE
change password  登录管理 Nacos0.8 版本

### ISSUE THREAD

**Issue by 5StevenWu** [alibaba/nacos#9195]
The production environment has been launched. Does the simple login password change affect the use
生产环境已经上线 修改简单登录密码是否影响使用
官方文档里面还是旧的修改方式

**Comment by KomachiSion** [comment]
0.8版本过旧了 我记得是没有鉴权认证的，应该也没有修改用户密码一说吧。

建议升级到新版本试试。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
