### ISSUE TITLE
自己的服务是netty写的，集成spring cloud nacos 时候，发现配置的自动刷新机制不行？

### ISSUE THREAD

**Issue by qinlinxin2080** [alibaba/nacos#9198]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by chenhao26-nineteen** [comment]
Please provide details, such as the version of Nacos and the version of Spring Cloud Aliababa

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by Fox2210** [comment]
结论：复现场景发现存在无法自动刷新问题，但不是nacos本身问题, 而是netty阻塞主线程造成nacos监听器无法注册

严谨的原则提供一下使用版本号，但问题和版本没关系
spring-cloud-alibaba-dependencies version： 2.2.5.RELEASE
nacos-client version：1.4.1
netty  version：4.1.52.Final


问题原因：
   通常大部分人写netty连接都会选择阻塞模式，channelFuture.channel().closeFuture().sync()，但netty会阻塞主线程影响后续的流程，而nacos本身实现自动刷新原理是启动时注册监听器com.alibaba.cloud.nacos.refresh.NacosContextRefresher#onApplicationEvent

public void onApplicationEvent(ApplicationReadyEvent event) {
        if (this.ready.compareAndSet(false, true)) {
            this.registerNacosListenersForApplications();
        }

    }

  常规项目在程序初始化成功会执行注册监听器，而使用netty创建连接时阻塞，使监听器无法进行注册，从而导致无法接收自动刷新的配置，所以只要让netty不阻塞主流程就可以保证自动刷新机制使用。即使用单独线程或者线程池来启动netty连接就可以搞定。可以使用@async修饰ApplicationRunner的run()方法，但不建议这样做。最好是单独搞个线程来操作。

（临时代码就直接 new个线程凑合看）
 Thread thread = new Thread(() -> {
            NioEventLoopGroup boosGroup = new NioEventLoopGroup();
            NioEventLoopGroup workerGroup = new NioEventLoopGroup();
            
            ServerBootstrap serverBootstrap = new ServerBootstrap();
             //此处省列配置代码。。。。

            ChannelFuture channelFuture = serverBootstrap.bind(nettyServerPort).addListener(future -> {
                if (future.isSuccess()) {
                    log.info("绑定端口{}成功", nettyServerPort);
                } else {
                    log.error("绑定端口{}失败", nettyServerPort);
                }
            }).sync();
            channelFuture.channel().closeFuture().sync();
        });
        thread.start();
