### ISSUE TITLE
group指定为Nacos:Test 无法感知配置的变化

### ISSUE THREAD

**Issue by a1193231242** [alibaba/nacos#9203]
@Slf4j
public class NacosClientApi {
    static String dataId = "com.nacos.client.api.demo";
    static String group = "Nacos:Test";
    static String content = "myKey=myValue";

    public static void main(String[] args) throws NacosException, InterruptedException {
        Properties properties = new Properties();
        // 指定 Nacos 地址
        properties.put(PropertyKeyConst.SERVER_ADDR, "127.0.0.1:8848");
        ConfigService configService = NacosFactory.createConfigService(properties);

        //发布配置
        boolean publishConfig = configService.publishConfig(dataId, group, content);
        log.info("publishConfig: {}", publishConfig);

        configService.addListener(dataId, group, new PropertiesListener() {
            @Override
            public void innerReceive(Properties properties) {
                log.info("收到的properties变化为{}", properties);
            }
        });
        TimeUnit.SECONDS.sleep(30);
    }
}

**Comment by karsonto** [comment]
参考源码 ConfigExample 修改
<img width="871" alt="image" src="https://user-images.githubusercontent.com/31433550/191938048-f93d4765-a26c-4b84-a554-df797417dfac.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/31433550/191938110-6e8ab524-b0e8-4ebf-8999-1f38f939dcc4.png">
能正常监听变化

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
