### ISSUE TITLE
java.lang.NoSuchMethodError: com.alibaba.nacos.api.grpc.auto.RequestGrpc.newFutureStub(Lcom/alibaba/nacos/shaded/io/grpc/Channel;)Lcom/alibaba/nacos/api/grpc/auto/RequestGrpc$RequestFutureStub;

### ISSUE THREAD

**Issue by lizhibo0914** [alibaba/nacos#9205]
Nacso upgrade to 2.1 after project start error, The configuration file content cannot be obtained；
Java. Lang. NoSuchMethodError: com.alibaba.nacos.api.grpc.auto.RequestGrpc.newFutureStub(Lcom/alibaba/nacos/shaded/io/grpc/Channel;) Lcom/alibaba/nacos/api/grpc/auto/RequestGrpc$RequestFutureStub;
![image](https://user-images.githubusercontent.com/27732536/192103584-feddddbf-9b0a-4e55-b566-4cc518afc549.png)

**Comment by lizhibo0914** [comment]
![image](https://user-images.githubusercontent.com/27732536/192103685-0545951b-c8db-4868-9caf-ea64c3cfeb54.png)
When you get to this point, you get an error

**Comment by lizhibo0914** [comment]
The RPC port from the client to the server is fine. The nacos port I configured is 8009,9009 and 9010, which are fine

**Comment by lizhibo0914** [comment]
The method called with source code discovery is in NACOS-Client, and the method called when establishing RPC connection here is in NACO-API. I don't know why there is conflict, please kindly help to solve the problem as soon as possible

**Comment by lizhibo0914** [comment]
nacos-client、naco-api、nacos-commons这些jar包都引入了

**Comment by KomachiSion** [comment]
remove nacos-api and nacos-commons and retry？  nacos-client will depend api and common directly.

**Comment by lizhibo0914** [comment]
Just exclude it, so new updates can only introduce NACOS-Client, API and Commons packages can't, otherwise this will happen

**Comment by KomachiSion** [comment]
nacos-client will depend api and common auto, if you depend them by yourself, you should make sure they are same version and can't conflicts.
