### ISSUE TITLE
nacos2.0是否继续支持批量更新实例元数据

### ISSUE THREAD

**Issue by DickensTone** [alibaba/nacos#9213]
nacos2.0使用批量更新实例元数据，结果返回400。我看nacos2.0的兼容文档，是支持的。但是，我使用官方实例，报告400。
请求参数http://xxx.xxx.xxx.xxx:8848/nacos/v1/ns/instance/metadata/batch?namespaceId=123456&serviceName=V2@test-service&consistencyType=ephemeral&metadata={"age":"20","name":"cocolan"}

[下面是nacos2.0的兼容文档](https://nacos.io/zh-cn/docs/2.0.0-compatibility.html)
![OX)XO D@RSID(8G9J 8)EQV](https://user-images.githubusercontent.com/29301837/192215032-829856dd-8a29-4109-a8ad-38d8313a1b55.png)

**Comment by hoErYu** [comment]
这个接口是put请求，你看看是不是用post请求了

**Comment by DickensTone** [comment]
我用的是PUT 请求，少参数还能正常报错。**caused: Param 'metadata' is required.;**
我看官方文档400是metadata错误，于是我用的官方的实例，也还是不行。我就产生了疑问是不是没支持了。

**Comment by DickensTone** [comment]
然后我想到会不会metadata没在url里面，放到body里问题解决了
![G2V9 $2$IW~~T LO$6 R(Q](https://user-images.githubusercontent.com/29301837/192432280-c7602d7b-c4a8-421a-9ef4-31c29950e0f9.png)
