### ISSUE TITLE
nacos无法更改线上的服务参数，比如服务的权重和下线某个服务

### ISSUE THREAD

**Issue by yujunchengg** [alibaba/nacos#9217]
nacos client版本为2.0.3，我一旦更改线上的服务，它会弹窗报错，但是很奇怪的是，当这个服务刚注册上去，没有另外服务去调它的时候，它又是可以更改的，具体错误截图如下

![image](https://user-images.githubusercontent.com/36986915/192236709-5984560e-9297-4b8f-871b-ff1c3d942a9e.png)

**Comment by KomachiSion** [comment]
Your raft has some problem. No leader .

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
