### ISSUE TITLE
Nacos 2.1.1 naming_persistent_service_v2 ERROR_TYPE_SNAPSHOT Fail to save snapshot

### ISSUE THREAD

**Issue by MonaLisaFineHair** [alibaba/nacos#9221]
中文版
描述：

1、 升级2.1.1之后，集群节点元数据报错：

 "naming_persistent_service_v2": {
                "errMsg": "Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to save snapshot.]]"

2、我也搜索了其他类似的问题：

https://github.com/alibaba/nacos/issues/9139

3、发现目前在我们的Nacos上注册了一个持久实例
4、我试图想通过改变实例注册方式：由持久改为临时
      无法注册，报错：is persistent service, can't register ephemeral instance
5、于是想回滚到注册持久实例
      无法注册，报错：Could not find leader : naming_persistent_service_v2
目前，该实例完全无法在Nacos上注册了，有两个问题：

A. 遇到这个问题，该如何临时解决，期望实例能够注册上去？
B. 正对这个问题，是什么原因造成的，在哪个版本会修复？

英文版
describe:

1. After upgrading to 2.1.1, the cluster node metadata reports an error:

  "naming_persistent_service_v2": {
                 "errMsg": "Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to save snapshot.]]"

2. I also searched for other similar questions:

https://github.com/alibaba/nacos/issues/9139

3. Found that a persistent instance is currently registered on our Nacos
4. I tried to change the instance registration method: from persistent to temporary
       The result cannot be registered, and an error is reported: "is persistent service, can't register ephemeral instance"
5. So I want to roll back to the registered persistent instance
       The result cannot be registered, and an error is reported: "Could not find leader : naming_persistent_service_v2"
At present, the instance cannot be registered on Nacos at all, and there are two questions I hope to get answers to:

A. When I encounter this problem, how to solve it temporarily, hoping that the instance can be registered?
B. For this problem, what caused it and in which version will it be fixed?

**Comment by ruansheng8** [comment]
临时解决方案是重启nacos可以解决 (永久实例信息好像是存储在内存中的)
我这边生产环境没有使用永久实例 就没有具体去看原因了

**Comment by KomachiSion** [comment]
Fail to save snapshot.

说明在保存快照到本地磁盘的时候出错了， 应该是环境问题导致的， 比如没有文件的写入权限，磁盘满，文件句柄被其他节点占用等等。 需要查看日志找到跟具体的原因。

**Comment by pixystone** [comment]
4. 持久化属性是不能修改的

A. 遇到这个问题，由于JRaft要保证强一致性，所以报错后就不允许当前节点可写。必须重启。但是如果重启仍然出现，就必须解决问题B，找到根因，看看为什么SNAPSHOT损坏了。

如果SNAPSHOT路径是对的，权限也没问题，也可能文件写入时异常推出了。多节点的话，可以把 protocol 目录备份删除，它会从leader拉取数据。

**Comment by MonaLisaFineHair** [comment]
> Fail to save snapshot.
> 
> 说明在保存快照到本地磁盘的时候出错了， 应该是环境问题导致的， 比如没有文件的写入权限，磁盘满，文件句柄被其他节点占用等等。 需要查看日志找到跟具体的原因。

**需要提供哪些日志文件么？**

**Comment by MonaLisaFineHair** [comment]
> 



> 4. 持久化属性是不能修改的
> 
> A. 遇到这个问题，由于JRaft要保证强一致性，所以报错后就不允许当前节点可写。必须重启。但是如果重启仍然出现，就必须解决问题B，找到根因，看看为什么SNAPSHOT损坏了。
> 
> 如果SNAPSHOT路径是对的，权限也没问题，也可能文件写入时异常退出了。多节点的话，可以把 protocol 目录备份删除，它会从leader拉取数据。

目前我们的集群一共3台Nacos实例，分别用A、B、C表示

A、C  集群节点信息显示 naming_persistent_service_v2 的leader为 C；
B        集群节点信息显示 naming_persistent_service_v2 的leader为 B；

A、B、C 3个节点都显示 Fail to save snapshot 

**应该怎么重启？重启是否有顺序要求？**

**Comment by MonaLisaFineHair** [comment]
我通过停止全部的Nacos实例，并且删除全部实例下的protocol数据，似乎解决了问题

**Comment by MonaLisaFineHair** [comment]
”我通过停止全部的Nacos实例，并且删除全部实例下的protocol数据，似乎解决了问题“  当时确实没问题，但不知过了多久，
国庆回来之后发现问题又出现了，报错依然是：

"naming_persistent_service_v2": {
"errMsg": "Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to save snapshot.]]"

**Comment by MonaLisaFineHair** [comment]
https://github.com/alibaba/nacos/issues/8931
