### ISSUE TITLE
Table structure in docker image nacos-mysql is not compatible with version 2.1

### ISSUE THREAD

**Issue by TrevorLink** [alibaba/nacos#9223]
**Describe the bug**
The current docker image of nacos-mysql does not seem to be compatible with newer versions of nacos.

An error is reported when a new service configuration is created, indicating that `The release has failed. Please check if the parameters are correct`.

After verification, I found that the sql data tables initialized in the original image nacos-mysql were nacos 2.0 and previous versions, and when using nacos 2.1, the initialized database table structure was inconsistent and incompatible, resulting in persistence failure when publishing the configuration.

**Expected behavior**
Deploy to K8S and push the configuration normally from the configuration centre

**Actually behavior**
An error is reported when a new service configuration is created, indicating that `The release has failed. Please check if the parameters are correct`

**How to Reproduce**
1. git clone https://github.com/nacos-group/nacos-k8s.git,using official guide for deploying nacos on k8s
2. Publish configurations to the Service Configuration Centre
3. See the error message `The release has failed. Please check if the parameters are correct` (发布失败。请检查参数是否正确)

**Desktop (please complete the following information):**
 - Image Version 
   -  nacos/nacos-server:latest
   - nacos/nacos-mysql:5.7

**Comment by karsonto** [comment]
@i will resolve it@

**Comment by TrevorLink** [comment]
I've created my own image based on mysql5.7 and init with the sql scripts provided in nacos2.1 release version and post it to docker hub

**Comment by TrevorLink** [comment]
I wonder how can I contribute to slove this issue with my docker image `trevorlink/nacos-mysql` on dockerhub

**Comment by paderlol** [comment]
Fixed https://github.com/nacos-group/nacos-docker/pull/283
