### ISSUE TITLE
nacos线程太多，占用系统资源

### ISSUE THREAD

**Issue by MrShao233** [alibaba/nacos#9224]
### nacos线程太多
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/39620279/192525107-a5ed4064-bc3c-49b8-bbac-14a92bd962d9.png">
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/39620279/192525288-0a3aef57-1ba6-4ce8-8a60-3af85c2a23f7.png">
我最近发现项目启动后有大量的线程创建，经过工具分析后，发现有大量的nacos线程被创建，如上图所示，这些线程会占用我们的系统资源，有什么办法能解决这个问题吗

**Comment by KomachiSion** [comment]
您创建了过多的NacosNamingService实例， 建议复用同一个。

**Comment by MrShao233** [comment]
感谢
