### ISSUE TITLE
nacos2.0启动报java.nio.charset.UnsupportedCharsetException: GBk 

### ISSUE THREAD

**Issue by FightForBigData** [alibaba/nacos#9225]
环境：windows7
jdk版本 ：jdk_8u331_x64_1.8,jdk-8u251-windows-x64 试过好几个版本的jdk 也不行
nacos版本：单机模式启动，2.0.1,2.0.3 试过也不行。挪到其他电脑一启动就成功
charsets.jar 包也替换过
百度也没有这个问题的处理办法
一直报这个错，各位大佬求解

![image](https://user-images.githubusercontent.com/43444531/192548955-39172c5b-b0ab-4e4b-aaf0-17142d3318f4.png)

**Comment by KomachiSion** [comment]
2.x版本不支持jdk1.6 至少需要jdk1.8

**Comment by FightForBigData** [comment]
用的就是1.8的

**Comment by KomachiSion** [comment]
看起来就是jdk或者系统环境的问题， 不支持GBK编码。
