### ISSUE TITLE
nacos2.x关闭控制台登录功能的配置无效

### ISSUE THREAD

**Issue by LxQ0001** [alibaba/nacos#9241]
nacos文档-运维指南-控制台手册-登录管理
关闭登录功能
由于部分公司自己开发控制台，不希望被nacos的安全filter拦截。因此nacos支持定制关闭登录功能找到配置文件 ${nacoshome}/conf/application.properties， 替换以下内容即可。
```

## spring security config
### turn off security
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**

#nacos.security.ignore.urls=/,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/login,/v1/console/health,/v1/cs/**,/v1/ns/**,/v1/cmdb/**,/actuator/**
```

application.properties中添加了上述配置，但是控制台依然可以登录

**Comment by wuchubuzai2018** [comment]
你的自己开发的控制台前端文件得放到Nacos项目中吧

**Comment by jameingh** [comment]
@i will solve it@
没生效的直接原因是因为前端报错了，请求了接口v1/console/server/state
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/5267037/195318564-e11bf837-d29a-457f-b80a-bc2e8ed5803b.png">
没登录的情况下，这个时候还没有token，解析失败，异常捕获后，会跳转到登录页

request.js
<img width="859" alt="image" src="https://user-images.githubusercontent.com/5267037/195318121-a179bfaf-de49-436d-bd12-41ad8073fe0f.png">
 我尝试加了一段固定的token，可以不用登录就直接进入控制台。如下所示：

request.js
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/5267037/195334990-e98cb026-a090-4ef5-81dc-6b5128e839ef.png">

但是这不是一个好的方式，需要一个接口，让前端知道是否关闭了登录功能，不知道有没有现成的接口，没有的话，我可以在哪个目录这个接口吗？

**Comment by KomachiSion** [comment]
嗯 前端需要做一些适配， 最好能做成模块化的方式，能够快速的开关，甚至转跳能力。

**Comment by KomachiSion** [comment]
不过我前端贼菜，不知道怎么做，需要什么能力。

**Comment by githubcheng2978** [comment]
1. add configuration when packaging front-end resource ,just only copy welcome page to console.
2. return the console close on the console/server/state interface, so that pages can go welcome pages @KomachiSion

**Comment by llussy** [comment]
我只想关闭登录功能应该怎么操作？
```bash
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**
```
这些配置在1.2.0 中是生效的， 1.2.1及之后的版本不行 （我这测了1.2.1和1.3.2）

**Comment by KomachiSion** [comment]
upgrade to v2.2.2 or later. and set `auth.enabled=false`

**Comment by KomachiSion** [comment]
And related to #10971
