### ISSUE TITLE
请问下nacos是否有这个漏洞，在哪个版本修复了呢？

### ISSUE THREAD

**Issue by Sorieee** [alibaba/nacos#9242]
I wonder if this problem exists? And if exists, which version fixed it?
![lQLPJxa5lcYAWuPMvc0EDLBjWfPEroZpWQMxIP0ewIkA_1036_189](https://user-images.githubusercontent.com/8654292/192953488-38ca6109-2d3d-474d-8fee-1388e5aa0d40.png)

**Comment by karsonto** [comment]
请参考ISSUE #4683
