### ISSUE TITLE
nacos开启鉴权报错

### ISSUE THREAD

**Issue by KingKong1997** [alibaba/nacos#9244]
请教下大家。本地测试没问题，部署后各模块无法注册到服务列表
![image](https://user-images.githubusercontent.com/38830234/192986855-06a3ea43-078e-4c8b-94c1-83aada293915.png)
![image](https://user-images.githubusercontent.com/38830234/192986926-19717e20-bf5f-4c4e-8119-07464ed5aea8.png)
nacos版本 2.0.3
![image](https://user-images.githubusercontent.com/38830234/192987145-fdbf3d57-cbef-42df-a085-64cc1ed945c9.png)
Caused by: com.alibaba.nacos.api.exception.NacosException: unknown user!
[SecurityProxy] login http request failed url: [http://xxx.xxx.xx.xx:8848/nacos/v1/auth/users/login](https://gitee.com/link?target=http%3A%2F%2Fxxx.xxx.xx.xx%3A8848%2Fnacos%2Fv1%2Fauth%2Fusers%2Flogin), params: {username=nacos}, bodyMap: {password=nacos}, errorMsg: connect timed out

**Comment by Drolese** [comment]
client version

**Comment by KingKong1997** [comment]
> client version需要给你看版本信息吗 
![image](https://user-images.githubusercontent.com/38830234/194748724-eb7fc92d-959f-444e-ba2e-e3fbf7f0d9d3.png)

**Comment by KomachiSion** [comment]
connect timed out

和鉴权没关系， 网络不通，链接超时了。

**Comment by KingKong1997** [comment]
> 和鉴权没关系， 网络不通，链接超时了。

那要怎么处理 我用另外一个服务器就没问题

**Comment by KomachiSion** [comment]
换一个服务器可以说明代码都没有问题，环境问题需要自行排查下了。 如果换一个服务器已经可以work，那就用新服务器运行就好了，旧的释放掉。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
