### ISSUE TITLE
caused: errCode: 500, errMsg: do metadata operation failed ;caused: java.lang.IllegalArgumentException: No corresponding Raft Group found : naming_instance_metadata;caused: No corresponding Raft Group found : naming_instance_metadata;

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/nacos#9246]
**Describe the bug**
nacos版本2.1.1 standalone模式

![image](https://user-images.githubusercontent.com/31852897/193028945-4e6c4102-0ab3-4ae5-afa0-1095013bfc65.png)
想搭建源码环境 读一下nacos源码 结果启动之后对实例点击下线或者编辑 都会报错

下载官方提供的zip包启动则没有此问题 对比了所有的配置文件和jar包 并无不同之处 请指导一下该如何修复此问题

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by JavaLionLi** [comment]
官方zip包启动之后 存在如下目录
![image](https://user-images.githubusercontent.com/31852897/193029785-ae7a855e-ec9b-4154-aa54-48871dbc089d.png)

源码启动之后没有生成此目录 如何才能正常使用此功能呢

**Comment by JavaLionLi** [comment]
为什么没有人关注这个问题

**Comment by JavaLionLi** [comment]
解决了

**Comment by little-cui** [comment]
> 解决了

如何解决的？

**Comment by shihy1992** [comment]
如何解决的

**Comment by shihy0923** [comment]
> 咋解决的

启动之前，把nacos-server-2.1.0\nacos\data\protocol下的数据删除了，再重新2启动
至于为什么，抽空研究下源码

**Comment by KouShenhai** [comment]
查看源码就行解决
![image](https://github.com/alibaba/nacos/assets/48756217/fe33cbae-5f76-42e2-8f39-95c037191587)
![image](https://github.com/alibaba/nacos/assets/48756217/10050480-8626-4248-ac73-83eee164512d)
因此，这个问题，设置系统变量nacos.home就行
![image](https://github.com/alibaba/nacos/assets/48756217/d066661a-dc1d-4830-aa76-715d2b916f4c)
这就生成了raft目录
![image](https://github.com/alibaba/nacos/assets/48756217/aea1614b-9acb-4026-8e83-f9f0af935f5f)
希望对你有所帮助哦

> > 咋解决的
> 
> 启动之前，把nacos-server-2.1.0\nacos\data\protocol下的数据删除了，再重新2启动 至于为什么，抽空研究下源码

**Comment by Sulbsld** [comment]
13 May 2023 Cmt 18:50 tarihinde laokou ***@***.***> şunu
yazdı:

**Comment by Everything1sPossible** [comment]
> 解决了

老哥 你咋解决的

**Comment by ningyu1** [comment]
> 解决了

@JavaLionLi  如何解决的？分享一下

**Comment by hdfg159** [comment]
一般来说都是集群部署出现问题
- 看nacos打印出来的日志文件 `alipay-jraft.log` ，看看集群连接互通相关日志正不正常
- nacos 控制台里面的 `集群管理` > `节点列表`，不是所有都是 UP 绿色状态就代表集群是健康的，一般里面的节点元数据都是像下面这样一长串
```
{
    "supportGrayModel": true,
    "lastRefreshTime": 1762410339378,
    "version": "3.1.0",
    "raftMetaData": {
        "metaDataMap": {
            "lock_acquire_service_v2": {
                "leader": "10.18.97.111:27848",
                "raftGroupMember": [
                    "10.18.97.111:27848",
                    "10.18.97.111:17848",
                    "10.18.97.111:37848"
                ],
                "term": 1
            },
            "naming_instance_metadata": {
                "leader": "10.18.97.111:27848",
                "raftGroupMember": [
                    "10.18.97.111:27848",
                    "10.18.97.111:17848",
                    "10.18.97.111:37848"
                ],
                "term": 1
            },
            "naming_persistent_service": {
                "leader": "10.18.97.111:27848",
                "raftGroupMember": [
                    "10.18.97.111:27848",
                    "10.18.97.111:17848",
                    "10.18.97.111:37848"
                ],
                "term": 1
            },
            "naming_persistent_service_v2": {
                "leader": "10.18.97.111:27848",
                "raftGroupMember": [
                    "10.18.97.111:27848",
                    "10.18.97.111:17848",
                    "10.18.97.111:37848"
                ],
                "term": 1
            },
            "naming_service_metadata": {
                "leader": "10.18.97.111:27848",
                "raftGroupMember": [
                    "10.18.97.111:27848",
                    "10.18.97.111:17848",
                    "10.18.97.111:37848"
                ],
                "term": 1
            }
        }
    },
    "raftPort": "37848",
    "readyToUpgrade": true
}
```
