### ISSUE TITLE
能不能自己封装nacos

### ISSUE THREAD

**Issue by fastzhong** [alibaba/nacos#9249]
能不能自己封装 nacos，把它当做普通的service，自己可以做深度的定制，如使用postgresql，然后build，deploy and run？

**Comment by karsonto** [comment]
可以下载源码修改

**Comment by wuchubuzai2018** [comment]
> 能不能自己封装 nacos，把它当做普通的service，自己可以做深度的定制，如使用postgresql，然后build，deploy and run？

我之前个人改过一版的PostgreSQL支持的Nacos，感兴趣的可以看我的个人仓库，

**Comment by KomachiSion** [comment]
可以fork后自行修改源码部署使用，但是需要自行维护相关功能，由于修改导致一些问题需要自行解决。
