### ISSUE TITLE
An exception java.lang.IllegalArgumentException: Param 'vote' is required occurred

### ISSUE THREAD

**Issue by oldoldcoder** [alibaba/nacos#9256]
1.When I deploy a nacos cluster node,  An exception occurred，java.lang.IllegalArgumentException: Param 'vote' is required,I don't know why?
![图片](https://user-images.githubusercontent.com/83199123/193498077-97e7fde4-81c1-4f48-8b1e-3dee084a0628.png)

2.Environment is centos7 and nacos verison is 1.4.4,depoly three node in linux and port is 8845,8846,8847.

The file applicaiton.properties is only modified something of server.port and Database persistence
 
3.Although an exception is reported, it can still be started

I want to get help through issue，thank U :)

**Comment by KomachiSion** [comment]
The vote api is for old version (before 1.4). 
After 1.4, it change to Jraft.

the old api is only for upgrading. so ignore it is ok
