### ISSUE TITLE
BUG: based on grpc, a service can only have one ephemeral instance.

### ISSUE THREAD

**Issue by caqhy** [alibaba/nacos#9261]
**Describe the bug**
Based on http, a service can have multiple ephemeral instances.
Based on grpc, a service can only have one ephemeral instance. When different ephemeral instances are registered multiple times in a service, these ephemeral instances will be overwritten. Is this a bug?

**Expected behavior**
When registering based on grpc, a service can have multiple ephemeral instances.

**Actually behavior**
When registering based on grpc, the ephemeral instance disappears.

**How to Reproduce**
1. Use nacos-client version 2.x
2. Register multiple ephemeral instances using the client

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [nacos-server latest master, nacos-client 2.x]
 - Module [naming]
 - SDK [original]

**Comment by chenhao26-nineteen** [comment]
Due to certain changes in the registration mechanism of Nacos 2.0, the same client can only register one temporary instance for the same service. However, the batch registration feature of temporary instances is supported in 2.1.1. Please use com.alibaba.nacos.client.naming NacosNamingService # batchRegisterInstance Registers Multiple Instances

**Comment by caqhy** [comment]
@chenhao26-nineteen

**Comment by caqhy** [comment]
@chenhao26-nineteen 
I think the same client registering multiple instances should not be overwritten as long as their ip, port are different, no matter if they belong to the same service or not. NacosNamingService # registerInstance should not overwrite the previously registered instance.

**Comment by chenhao26-nineteen** [comment]
refer #5863

**Comment by caqhy** [comment]
> refer #5863

OK, I've seen discussions about issue #5863. But I found out that NacosNamingService#registerInstance allows the same client to register multiple persistent instances, is this correct?

**Comment by chenhao26-nineteen** [comment]
yes
