### ISSUE TITLE
Bug: [front] loss page condition on config management.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#9263]
**Describe the bug**
loss page condition on config management.

**Desktop (please complete the following information):**
 - Version nacos-server 2.1.1
 - Branch develop
 - Module config

**Additional context**
 1. loss page condition on config management.

![image](https://user-images.githubusercontent.com/16837364/194684376-34728646-9168-4c15-82c7-c5b132a3ecfe.png)

2. page condition on naming management.
![image](https://user-images.githubusercontent.com/16837364/194684383-7e84c99e-f1b2-42a4-85b4-8f37f5067736.png)

**Comment by zhouchunhai** [comment]
I think I made a misktake in my last PR, I deleted the Page Component, and I will submit another PR to fix it.

**Comment by zhouchunhai** [comment]
please assgin it to me.

**Comment by CherishCai** [comment]
@zhouchunhai 启动了下还是老样子耶，好像没有效果

**Comment by zhouchunhai** [comment]
![image](https://user-images.githubusercontent.com/111631755/194983221-1e3fd697-840b-4505-a301-810b4bda6398.png)
本地跑了没问题啊，你拉最新的代码了吗

**Comment by CherishCai** [comment]
好的确实有，原来是无数据时不显示

![image](https://user-images.githubusercontent.com/16837364/194983929-e63d5e99-9407-40b4-9bfa-6a1a1f0b2dda.png)

![image](https://user-images.githubusercontent.com/16837364/194983944-99c9c9e9-a6ed-40f8-8805-f9269dda29ba.png)

**Comment by zhouchunhai** [comment]
![image](https://user-images.githubusercontent.com/111631755/194984090-801323f5-4d05-42fb-95bc-6e738497dbf3.png)
