### ISSUE TITLE
nacos2.0.1至nacos-2.1.x都不支持服务注册失败重试机制吗

### ISSUE THREAD

**Issue by john1337** [alibaba/nacos#9264]
nacos2.0.1至nacos-2.1.x都不支持服务注册失败重试机制吗，正在使用的nacos-2.0.1版本，一旦服务比nacos-server晚起动就会导致服务注册不上去的问题

**Comment by Daydreamer-ia** [comment]
服务端没起来的话，在setup连接时候，会被ConnectRest的，连接重置会引导客户端选择新的server重新建连的
但如果客户端设置的服务端ip只有一个，那就会直接重连
![1665205505281](https://user-images.githubusercontent.com/83362909/194689586-e16fa522-37c1-4cbf-8f5b-ec426563de2b.png)

**Comment by john1337** [comment]
我现在使用的nacos-2.0.1版本，注册失败后不会进行重试，而且这个版本的注册是在收到WebServerInitializedEvent事件后才进行服务注册的

**Comment by Daydreamer-ia** [comment]
> 我现在使用的nacos-2.0.1版本，注册失败后不会进行重试，而且这个版本的注册是在收到WebServerInitializedEvent事件后才进行服务注册的

我记得客户端注册失败会有异常，如果出现异常说明失败，或许可以按你的策略去重新注册？

**Comment by john1337** [comment]
> > 我现在使用的nacos-2.0.1版本，注册失败后不会进行重试，而且这个版本的注册是在收到WebServerInitializedEvent事件后才进行服务注册的
> 
> 我记得客户端注册失败会有异常，如果出现异常说明失败，或许可以按你的策略去重新注册？

首先注册是nacos在实现了对应的serviceregistry接口后自定义的功能，除非去定制化register接口否则不方便去捕获这个异常吧，而且从nacos注册的角度来讲捕获异常去处理也不是很好的一个策略，侵入性都太强

**Comment by john1337** [comment]
在2020年的时候有一个merge request，就是增加了失败重试机制，不知为什么没有合并到主分支

**Comment by KomachiSion** [comment]
nacos-client都有重连和重新注册的功能，和`WebServerInitializedEvent` 没任何关系， 如果你说的是SCA的重试机制，请移步到SCA社区询问。

`com.alibaba.nacos.client.naming.remote.gprc.redo.NamingGrpcRedoService`

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
