### ISSUE TITLE
服务上下线集成钉钉通知

### ISSUE THREAD

**Issue by Liujt91** [alibaba/nacos#9267]
能不能集成服务上下线,钉钉通知功能？虽然这和服务本身功能不相关，但是可以给用户多一个选择

**Comment by john1337** [comment]
通过springboot-admin可以实现对应的功能

**Comment by KomachiSion** [comment]
It can be extend after #8481 finished

**Comment by Liujt91** [comment]
> 通过springboot-admin可以实现对应的功能

那不又多出来一个服务吗~

**Comment by john1337** [comment]
> > 通过springboot-admin可以实现对应的功能
> 
> 那不又多出来一个服务吗~

其实nacos本身支持服务上线下的通知，只不过没有对接外部的通知方式而已

**Comment by Willdas** [comment]
只需要订阅服务就可以监听到对应的服务上下线

**Comment by sabrican3532** [comment]
#9359

**Comment by sabrican3532** [comment]
￼facbook code
