### ISSUE TITLE
Client gets config timeout add configurable

### ISSUE THREAD

**Issue by SirMin** [alibaba/nacos#9268]
**Is your feature request related to a problem? Please describe.**
When the client gets the configuration, a timeout is set, but the timeout is written to 3000

**Describe the solution you'd like**
 Maybe add a configuration to obtain environment variables or other methods?

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/16568907/194696557-01e4f172-e49c-48e4-a4c6-aa66c29f0815.png)
![image](https://user-images.githubusercontent.com/16568907/194697297-04344760-d256-4ab4-b922-8fc6e3326c73.png)

**Comment by Daydreamer-ia** [comment]
It has be fix in #9017
