### ISSUE TITLE
Nacos 1.0.0 yml Integer Coercive transformation String

### ISSUE THREAD

**Issue by xingrufeng073** [alibaba/nacos#927]
ERROR：
Property: mybatis-plus.global-config.db-config.field-strategy 
Value: 1
    Origin: "mybatis-plus.global-config.db-config.field-strategy" from property source "bootstrapProperties"
    Reason: failed to convert java.lang.String to com.baomidou.mybatisplus.annotation.FieldStrategy
================================================================
description：
The same word spring config is ok。I think Nacos might force all attribute values to String。

**Comment by hxy1991** [comment]
Can you provide the sample code?

**Comment by xingrufeng073** [comment]
> Could you provide the sample code?

<dependency>
	<groupId>com.baomidou</groupId>
	<artifactId>mybatis-plus-boot-starter</artifactId>
	<version>3.0.6</version>
</dependency>

#You can put the following into the Nacos configuration center
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: 0
      field-strategy: 1
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

**Comment by hxy1991** [comment]
Are you using spring-cloud-starter-alibaba-nacos-config 0.2.1.RELEASE? I can't reproduce this problem here.

**Comment by xingrufeng073** [comment]
> Are you using spring-cloud-starter-alibaba-nacos-config 0.2.1.RELEASE? I can't reproduce this problem here.

yes
this is pom:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.8.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<version>0.2.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.baomidou</groupId>
			<artifactId>mybatis-plus-boot-starter</artifactId>
			<version>3.0.6</version>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>0.2.1.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
