### ISSUE TITLE
提供配置项搜索能力

### ISSUE THREAD

**Issue by MoyaiTing** [alibaba/nacos#9276]
当配置文件多了以后，想找某个配置在哪个配置文件中时，就不是很方便了，因为它没有提供根据配置内容去搜索配置文件的功能，需要一个文件一个文件的打开去搜索，建议提供配置搜索能力

**Comment by 985492783** [comment]
> 当配置文件多了以后，想找某个配置在哪个配置文件中时，就不是很方便了，因为它没有提供根据配置内容去搜索配置文件的功能，需要一个文件一个文件的打开去搜索，建议提供配置搜索能力

@KomachiSion @MoyaiTing 

几个问题
1.是想搜索单个配置内容还是多个配置内容
2.如果是单个的话就好解决，但是如果是多个存在一个匹配度的问题
目前的想法
一种方案是可以给维护者提供一个正则接口REGEXP去匹配相对应的内容
另一种方案就是搜全表，然后按照匹配度排序，不过效率很低下

**Comment by MoyaiTing** [comment]
1、搜索单个配置内容，例如可以直接搜索spring.redis.host这样，如果多个存在，那就是配置项重复了，这个开发者自己配【判断即可
2、之前我试过从数据库里面搜，但是配置文件都是直接一条记录，配置项全部放在一个字段里面不好搜
我现在的解决方案是直接将配置文件下载下来，利用ider的全文搜索能力去检索的，但是这样无法满足我想按照完整配置项去搜索，例如直接搜索spring.redis.host，因为现在主流配置文件格式都是yml，如果是Propertles格式可以搜完整配置

**Comment by 985492783** [comment]
> 1、搜索单个配置内容，例如可以直接搜索spring.redis.host这样，如果多个存在，那就是配置项重复了，这个开发者自己配【判断即可 2、之前我试过从数据库里面搜，但是配置文件都是直接一条记录，配置项全部放在一个字段里面不好搜 我现在的解决方案是直接将配置文件下载下来，利用ider的全文搜索能力去检索的，但是这样无法满足我想按照完整配置项去搜索，例如直接搜索spring.redis.host，因为现在主流配置文件格式都是yml，如果是Propertles格式可以搜完整配置

对，就是因为nacos支持了好几种配置格式，所以是否要全部适配成properties的格式呢？
目前可以提供一个类似tag的那种搜索方案
>![image](https://user-images.githubusercontent.com/73023513/205541572-5bbfdb85-4844-421e-84b7-1856b4a50bb8.png)
然后将匹配111并且匹配22的所有配置文件列出，是这样吗？

**Comment by MoyaiTing** [comment]
是的，建议是全部适配properties格式，因为在程序中，其实并不在意你是用哪种格式配置的，我们去开发或者维护过程中，是肯定知道配置的完整路径的，例如说我需要配置redis的host的话，在代码里面，应该就是直接${spring.redis.host}来注入的
而且根据完整路径去搜索配置项，可以避免出现很多重复项，因为正常情况下，应该就只有一个的，如果出现多个，就是重复的配置项，这个时候就应该开发者自己去判断优先级，最终程序是使用那个

**Comment by 985492783** [comment]
好，我可以试试
@KomachiSion 
@i will solve it@

**Comment by 985492783** [comment]
@MoyaiTing 我目前做了一个方案在我fork的update分支，你可以试试，如果满足需求我提就提PR了 https://github.com/985492783/nacos/tree/update

**Comment by MoyaiTing** [comment]
满足要求了，但是发现了一个bug，如果yaml格式，但是配置内容里面存在空的情况，查询就会报错
![image](https://user-images.githubusercontent.com/45963531/206082503-48b19ba2-25c4-4c86-83ee-032208a0ac02.png)
![image](https://user-images.githubusercontent.com/45963531/206082551-cf6287be-12bc-4465-9e67-6df133fa701e.png)

**Comment by MoyaiTing** [comment]
还有一个不知道算不算bug，历史版本那边进行回滚之后，回滚之后的配置文件格式会变成text

**Comment by 985492783** [comment]
> 满足要求了，但是发现了一个bug，如果yaml格式，但是配置内容里面存在空的情况，查询就会报错
> ![image](https://user-images.githubusercontent.com/45963531/206082503-48b19ba2-25c4-4c86-83ee-032208a0ac02.png)
> ![image](https://user-images.githubusercontent.com/45963531/206082551-cf6287be-12bc-4465-9e67-6df133fa701e.png)
> 

嗯，我对空的判断和异常捕获可能有点问题

**Comment by 985492783** [comment]
The design documentation for this issue is in [yuque关于nacos#9276的设计](https://www.yuque.com/g/huanzailache/fhiqcw/collaborator/join?token=C8SlxHG3l9wcOZX4)
