### ISSUE TITLE
How to monitor micro services registered in nacos

### ISSUE THREAD

**Issue by seas521** [alibaba/nacos#928]
I need to monitor services registered in nacos，trying to use spring boot admin, but once the new service is registered, spring boot admin cant find it. Is there any better way to do it?

**Comment by seas521** [comment]
anyone?

**Comment by ChunMengLu** [comment]
I looked at the new version of spring-cloud-alibaba code that has solved this problem (not yet released), you can copy this code into your project. 【我看了下 spring-cloud-alibaba 新版的代码已经解决这个问题了（尚未发布），你可以把这块代码 copy 到你的项目里。】

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosWatch.java

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClientAutoConfiguration.java#L54

**Comment by seas521** [comment]
> I looked at the new version of spring-cloud-alibaba code that has solved this problem (not yet released), you can copy this code into your project. 【我看了下 spring-cloud-alibaba 新版的代码已经解决这个问题了（尚未发布），你可以把这块代码 copy 到你的项目里。】
> 
> https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosWatch.java
> 
> https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClientAutoConfiguration.java#L54

这个有预计上线时间么

**Comment by ChunMengLu** [comment]
> > I looked at the new version of spring-cloud-alibaba code that has solved this problem (not yet released), you can copy this code into your project. 【我看了下 spring-cloud-alibaba 新版的代码已经解决这个问题了（尚未发布），你可以把这块代码 copy 到你的项目里。】
> > https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosWatch.java
> > https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClientAutoConfiguration.java#L54
> 
> 这个有预计上线时间么

我不是官方的，不晓得哦，我 copy 进我的项目里好使了

**Comment by seas521** [comment]
> > > I looked at the new version of spring-cloud-alibaba code that has solved this problem (not yet released), you can copy this code into your project. 【我看了下 spring-cloud-alibaba 新版的代码已经解决这个问题了（尚未发布），你可以把这块代码 copy 到你的项目里。】
> > > https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosWatch.java
> > > https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClientAutoConfiguration.java#L54
> > 
> > 
> > 这个有预计上线时间么
> 
> 我不是官方的，不晓得哦，我 copy 进我的项目里好使了

赞！我试一下

**Comment by ChunMengLu** [comment]
Release 0.9.0: Compatible with Spring Cloud Greenwich
Release 0.2.2: Compatible with Spring Cloud Finchley
Release 0.1.2: Compatible with Spring Cloud Edgware

@seas521 update spring-cloud-alibaba version，is ok now！

**Comment by seas521** [comment]
> Release 0.9.0: Compatible with Spring Cloud Greenwich
> Release 0.2.2: Compatible with Spring Cloud Finchley
> Release 0.1.2: Compatible with Spring Cloud Edgware
> 
> @seas521 update spring-cloud-alibaba version，is ok now！

THX, it works now, appreciate that
