### ISSUE TITLE
nacos配置中心ip为虚拟ip

### ISSUE THREAD

**Issue by dym1005** [alibaba/nacos#9280]
请问一下各位大神，我的项目使用的nacos集群，目前启动了两个同一服务，其中一个服务的IP是真实地址，另一个服务是虚拟ip，请问是因为什么？

**Comment by KomachiSion** [comment]
所注册的ip是您的应用程序自己输入的，应该从你的应用程序里去排查。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
