### ISSUE TITLE
Could not resolve placeholder

### ISSUE THREAD

**Issue by roebuck99** [alibaba/nacos#9285]
**Describe the bug**
我在本地和云服务器各装了nacos（同一个版本），本地可以正常读取nacos配置，但是云服务器读取不到。
![image](https://user-images.githubusercontent.com/84660816/194757722-8e56e194-6745-411f-8f5b-584e2fbb3784.png)
![image](https://user-images.githubusercontent.com/84660816/194757761-621fd00d-94a7-426e-8db4-1a10c04de8e7.png)

配置内容
![image](https://user-images.githubusercontent.com/84660816/194758076-b2f279fd-9038-44a7-a02f-7593f1670211.png)
=====================================
![image](https://user-images.githubusercontent.com/84660816/194758039-de18c04f-276e-4af1-94dd-6be84e2f2ec5.png)

云服务器的nacos客户端可以正常访问，本地的客户端以及项目都能正常启动
**Expected behavior**
读取配置文件中的信息

**Actually behavior**
![image](https://user-images.githubusercontent.com/84660816/194758138-5ff98d0f-f2a8-49b5-96ad-7c5d3218babb.png)

本地nacos项目正常启动，云服务器的nacos服务启动异常Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'data' in value "${data}"

**Comment by KomachiSion** [comment]
应该是环境问题， 云服务器的那个情况是不是有网络不通的问题。

**Comment by roebuck99** [comment]
@KomachiSion 
![image](https://user-images.githubusercontent.com/84660816/194795858-4891ba1f-d45f-4b73-9285-e59b74737baf.png)
但是客户端可以正常访问唉

**Comment by wuchubuzai2018** [comment]
是不是9848端口未开通呢，客户端需要2个端口，8848和8848+1000

**Comment by roebuck99** [comment]
@wuchubuzai2018 跪谢大佬，解决了
