### ISSUE TITLE
nacos启动时报错

### ISSUE THREAD

**Issue by Danmin** [alibaba/nacos#9292]
主要报错信息：
<img width="585" alt="image" src="https://user-images.githubusercontent.com/9969933/194905062-6e2dec72-c7fd-4dbe-b945-fa8c3c74720f.png">

**Comment by realJackSun** [comment]
数据库里没建立表吧？

**Comment by KomachiSion** [comment]
这个错误是加载初始化sql失败， 大概率是derby数据库启动失败了。 看下其他的报错为什么启动失败了

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
