### ISSUE TITLE
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried

### ISSUE THREAD

**Issue by quicksandznzn** [alibaba/nacos#930]
nacos-server-1.0.0-RC1   standalone mode
jdk1.8
spring boot 2.0.4.RELEASE
spring cloud Finchley.SR1
spring-cloud-alibaba 0.2.1.RELEASE

**Comment by quicksandznzn** [comment]
i use nacos-server-0.9.0 fix bug

**Comment by unknow16** [comment]
me too

**Comment by programmer-luxw** [comment]
> i use nacos-server-0.9.0 fix bug

0.9.0注册成功以后 ，UI页面不显示服务。

**Comment by YuanzhuL** [comment]
me too 
![image](https://user-images.githubusercontent.com/31835759/54662545-5000b500-4b19-11e9-89c6-8a6425d3b168.png)

**Comment by liujiuwu** [comment]
这个问题什么时候能解决？本来想用，这样又不敢用了

**Comment by SoyMeng** [comment]
spring-cloud-alibaba 0.2.1.RELEASE客户端版本与server版本不匹配，cloud版本滞后太多了

**Comment by xuechaos** [comment]
@quicksandznzn are you try it in RC2 version?

**Comment by quicksandznzn** [comment]
> @quicksandznzn are you try it in RC2 version?

no i use 0.9 version

**Comment by nkorange** [comment]
User 1.0.0-RC2 and try again.

**Comment by HuangDayu** [comment]
> User 1.0.0-RC2 and try again.

Me too ,  use NACOS1.0.0-RC2 .

**Comment by tanfeng112** [comment]
> User 1.0.0-RC2 and try again.

I have try to used 1.0.0-RC2 .   but the problem does not to be solved.  
I tried to restart the service several times.  sometimes the service startup success.  but sometimes still occur Exception
```java
failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried
```

**Comment by coder-PengWenHao** [comment]
How to solve ?
