### ISSUE TITLE
request: /nacos/v1/ns/instance/list failed, servers: [172.16.16.2:8848], code: 500, msg: Unexpected end of file from server

### ISSUE THREAD

**Issue by suliujie** [alibaba/nacos#9303]
![image](https://user-images.githubusercontent.com/50354720/195064169-2a124412-6ea6-4f4d-b979-7e8781e20d1d.png)
![image](https://user-images.githubusercontent.com/50354720/195064414-7fc5ee04-7802-4465-b65f-aecd26211803.png)

生产环境程序突然一直报这个错误，导致服务无法使用，只能通过重启解决

**Comment by suliujie** [comment]
![image](https://user-images.githubusercontent.com/50354720/195065342-0e1d3bf2-50a2-41f8-886f-7e776549c0a4.png)
nacos版本

**Comment by KomachiSion** [comment]
升级版本试试。

**Comment by suliujie** [comment]
多个服务，永远都是这个服务突然掉线，然后再也上不去，只能重启解决，但是问题出现的也不频繁   就是每次掉线后都要再次重启才行
版本关系：网关服务（也就是出现问题的服务）：spring-cloud-alibaba  2.2.6   nacos-clent 1.4.2  nacos-server 1.31   spring-cloud  Hoxton.SR9   
其他业务服务： spring-cloud-alibaba  2.1.2  nacos-client  1.4.2  nacos-server 1.3.1 spring-boot  2.1.14

**Comment by KomachiSion** [comment]
那我感觉是这个服务有问题，而不是nacos有问题。

**Comment by KomachiSion** [comment]
No more response from author, I think this is not a nacos` problem.
