### ISSUE TITLE
The default cluster information has changed so that the service cannot be deleted

### ISSUE THREAD

**Issue by XoXOoOToT** [alibaba/nacos#931]
## Issue Description

Type: *bug report* or *feature request*
The default cluster name is changed when I use configuration management and service discovery,which causes the heartbeat to be lost, even if the service is normal。

### Describe what happened (or what feature you want)
1、ERROR [IP-DEAD] failed to delete ip automatically
2、default clusterName is “DEFAULT”
3、changed clusterName is {"defaultCheckPort":80,"defaultPort":80,"healthChecker":{"type":"TCP"},"metadata":{},"name":"DEFAULT","useIPPort4Check":true}

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
1、nacos 0.9.0  standalone 
2、springboot 2.0.6
4、springcloud Finchley.SR2
3、spring-cloud-alibaba-dependencies  0.2.1

### Anything else we need to know?
When I use these two components, the cluster name becomes a json string unless I manually call the interface add service to guarantee that the cluster name is defalt

**Comment by nkorange** [comment]
@XoXOoOToT What's your nacos-client version?

**Comment by stanvl** [comment]
这个问题，我也遇到了，微服务部署在docker集群中，在nacos控制台服务列表中看到注册的IP不是宿主机的IP，服务调用不通，然后修改了配置，指定了服务nacos discovery的ip和port，ip为docker容器的hostname，port为容器端口，服务能调用，但是当重新分配宿主机后，服务列表显示原来注册的实例是非健康状态，从日志中看一直删除失败，报如下错误：

ERROR [IP-DEAD] failed to delete ip automatically, ip: ... , resp code: 400

以下为版本信息
nacos 0.9.0 cluster
nacos client 0.9.0
spring boot 2.0.6 
spring cloud Finchley.SR2
spring-cloud-alibaba-dependencies 0.2.1

**Comment by nkorange** [comment]
@stanvl Please open another issue if your problem still exists.
