### ISSUE TITLE
Nacos client 登录会有线程安全问题

### ISSUE THREAD

**Issue by SirMin** [alibaba/nacos#9315]
**Describe the bug**

**Expected behavior**
启动的时候, 只有主线程中的登录失败,com.alibaba.nacos.client.Worke线程才会再次登录

**Actually behavior**
启动的时候, 主线程中没有登录失败的日志, 但是在com.alibaba.nacos.client.Worker线程中有登录失败的日志

**How to Reproduce**
偶发行为, 重启之后就好了

**Desktop (please complete the following information):**
 - Version nacos-client 2.1.0
 - Module config
 - SDK spring-cloud-alibaba-nacos

**Additional context**
![image](https://user-images.githubusercontent.com/16568907/195490078-3d6d9e41-795c-4c33-813f-16c0d5062b54.png)
![image](https://user-images.githubusercontent.com/16568907/195490629-bcbe4464-2e97-4519-87d9-68dbf782cfab.png)
![image](https://user-images.githubusercontent.com/16568907/195490770-5d87a63e-46a5-4762-86e7-2b706fdf7430.png)

**Comment by KomachiSion** [comment]
没有线程安全问题

先同步login一次，然后再启动异步线程定期登陆。

如果是启动的时候没有错误，之后worker线程里有，那么就是第一次登陆成功了，异步的时候失败了。

**Comment by SirMin** [comment]
@KomachiSion 现在日志中的错误就很诡异啊, 如果第一次登录成功, 这时候肯定没有过期, worker线程不应该再次登录, 但是日志中并没有同步登录失败的错误, 而有了worker登录的错误

**Comment by KomachiSion** [comment]
那你可以定位一下问题，有没有可能初始化了多个nacosConfigServer，有一个成功了，另一个失败。

单独跑纯粹的nacos-client似乎没有这个问题，登陆都是先同步再起异步。

**Comment by SirMin** [comment]
我是将nacos-server部署在k8s中的, 使用的是svc地址,只有一个nacos-server地址

**Comment by SirMin** [comment]
@KomachiSion 现在我感觉可能有问题的是tokenTtl,lastRefreshTime,tokenRefreshWindow没有使用volatile,虽然loginIdentityContext使用了volatile, 但是在判断过期时间的时候并没有读取loginIdentityContext, 所以没有内存屏障,不能保证happens-before, 但是理论上这个是这个线程第一次读取, 而且必然是在主线程之后, 不应该有线程缓存, 应该会从主存读取, 所以感觉很诡异

**Comment by SirMin** [comment]
> 那你可以定位一下问题，有没有可能初始化了多个nacosConfigServer，有一个成功了，另一个失败。
> 
> 单独跑纯粹的nacos-client似乎没有这个问题，登陆都是先同步再起异步。

你这里说的nacosConfigServer是NacosConfigService么, 也没有, 我是通过下面依赖的方式使用的
```xml
<dependency>    
    <groupId>com.alibaba.cloud</groupId>     
   <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId> 
    <version>2021.1</version>
 </dependency>
```

**Comment by YunWZ** [comment]
`HttpLoginProcessor.java`:

```java
catch (Exception e) {
            SECURITY_LOGGER.error("[NacosClientAuthServiceImpl] login http request failed"
                    + " url: {}, params: {}, bodyMap: {}, errorMsg: {}", url, params, bodyMap, e.getMessage());
            return null;
        }
```

日志截图没截全，看一下`e.getMessage()`输出的信息是什么？

**Comment by SirMin** [comment]
> `HttpLoginProcessor.java`:
> 
> ```java
> catch (Exception e) {
>             SECURITY_LOGGER.error("[NacosClientAuthServiceImpl] login http request failed"
>                     + " url: {}, params: {}, bodyMap: {}, errorMsg: {}", url, params, bodyMap, e.getMessage());
>             return null;
>         }
> ```
> 
> 日志截图没截全，看一下`e.getMessage()`输出的信息是什么？

错误信息不是重点, 是在main线程中没有报错, 按照正常的流程worker线程是不应该执行这段逻辑的

**Comment by KomachiSion** [comment]
> @KomachiSion 现在我感觉可能有问题的是tokenTtl,lastRefreshTime,tokenRefreshWindow没有使用volatile,虽然loginIdentityContext使用了volatile, 但是在判断过期时间的时候并没有读取loginIdentityContext, 所以没有内存屏障,不能保证happens-before, 但是理论上这个是这个线程第一次读取, 而且必然是在主线程之后, 不应该有线程缓存, 应该会从主存读取, 所以感觉很诡异

不需要，因为一个客户端只会有一个线程同时操作上述内容。不同的ConfigService和NamingService使用的是独立的loginIdentityContext，同一个ConfigService和NamingService都是先同步登陆，再起一个异步线程单独维护。
