### ISSUE TITLE
Nacos Web UI Redirect Login Error

### ISSUE THREAD

**Issue by yimao** [alibaba/nacos#9316]
**Describe the bug**

*nacos server version: 1.4.4*

When the jwt token expires, the nacos web page will prompt a "authorization authentication failed" pop-up window, but it cannot automatically jump to the login page. Analysis of the relevant code found that the automatic jump to the login page is only valid for 'unknown user!', 'token invalid!', 'token expired!' error messages, and not handled for Frobidden. Further view the nacos server log output as

当 jwt token 过期之后，nacos web 页面会提示 “权限认证失败” 弹窗，但是却无法自动跳转到登录页面。分析相关代码发现自动跳转到登录页面仅对 ```'unknown user!', 'token invalid!', 'token expired!'```  错误消息有效，对于 ```Frobidden```  未处理。进一步查看 nacos server 日志输出内容为 

```
2022-10-13 10:53:41,996 DEBUG auth start, request: GET /nacos/v1/cs/configs

2022-10-13 10:53:41,999 DEBUG access denied, request: GET /nacos/v1/cs/configs, reason: token expired!
```

However, the content of the abnormal response received by the synchronous front-end request is:
但是同步前端请求接收到的异常响应内容为：

```
{"timestamp":"2022-10-13T10:53:42.019+08:00","status":403,"error":"Forbidden","path":"/nacos/v1/cs/configs"}
```

It is suspected that a filter in the backend service hijacked the original ``` token expired!``` abnormal information, and finally the front-end JS cannot decide to redirect to the login page according to the ``` token expired!```. Please help to check, thank you!

怀疑是后端服务某个 Filter 劫持了原本的 ``` token expired!``` 异常信息，最后导致前端 JS 无法根据```token expired!```来决定重定向到登录页面，烦请协助排查一下，谢谢！

**Additional context**

- web ui
    <img width="1184" alt="b7037c31-9ef7-4ecf-bdf9-8fb55be143fd" src="https://user-images.githubusercontent.com/46945065/195493561-259578f9-4070-4cb9-ac63-392840ea4cb0.png">

- nacos server log
    <img width="745" alt="18a087b6-0c2a-4bd6-b6a4-6f7d5fa8abf4" src="https://user-images.githubusercontent.com/46945065/195493580-6262e710-da57-4c6f-ba2f-5bf9cea34079.png">

- js code
    <img width="793" alt="image" src="https://user-images.githubusercontent.com/46945065/195493653-5c0669e3-730e-4e7b-bdd7-64c5336c76d1.png">

**Comment by wuchubuzai2018** [comment]
### 当前问题
我定位了一下代码， 发现是AuthFilter中的输出的这个日志，
`
 if (Loggers.AUTH.isDebugEnabled()) {
                Loggers.AUTH.debug("access denied, request: {} {}, reason: {}", req.getMethod(), req.getRequestURI(),
                        e.getErrMsg());
            }
            resp.sendError(HttpServletResponse.SC_FORBIDDEN, e.getErrMsg());
`
重点在于 resp.sendError这个东西在SpringBoot的环境下，默认会被封装为一个JSON结构的对象，同时呢SpringBoot中的DefaultErrorAttributes类errorAttributes.put("error", errorStatus.getReasonPhrase());会去默认值，不会输出我们的自定义的值。
目前Nacos的接口返回没有固定的结构。
可以将 AuthFilter类中的resp.sendError(HttpServletResponse.SC_FORBIDDEN, e.getErrMsg());方法，更改为如下代码
`
 resp.setStatus(HttpServletResponse.SC_FORBIDDEN);
 resp.getWriter().println(e.getErrMsg());
`
应该可以解决这个问题。

问下管理员，我可以提交下这个处理的2行代码的Pull Request吗

### 扩展说明
但是当前系统中涉及到 resp.sendError的地方大概有将近20处，未来可能看看重写某些类进行统一处理下。

**Comment by KomachiSion** [comment]
我觉得这和后端接口返回方式没关系， 主要是前端需要有办法感知到403的时候要跳转到登陆页面。

**Comment by yimao** [comment]
> 我觉得这和后端接口返回方式没关系， 主要是前端需要有办法感知到403的时候要跳转到登陆页面。

```
...... other code ......
error => {
        // 处理403 forbidden
        const { status, responseJSON = {} } = error || {};
        if (responseJSON.message) {
          Message.error(responseJSON.message);
        }
        if (
          [401, 403].includes(status) &&
          ['unknown user!', 'token invalid!', 'token expired!'].includes(responseJSON.message)
        ) {
          goLogin();
        }
        return error;
      }
...... other code ......
```

从Nacos 前端 JS 代码中这段逻辑不就是在决定跳转到登录页面么？

**Comment by yimao** [comment]
> 2.x 似乎也一样存在，目前只能右上角 退出然后重新登录下，期待有同学解决它

我把 nacos-server 从 1.4.4 版本回退到 1.4.1 版本，会有另外一个BUG，当 jwt token 过期之后，在 nacos web 页面依然可以正常访问配置内容、修改配置内容，而这个问题之前有人提出过。通过 git commit 分析，大概率为了修复前面那个BUG才引入了当前 issues #9316 的问题。总结来说应该算是修复的不够彻底吧。

**Comment by yimao** [comment]
> ### 当前问题
> 我定位了一下代码， 发现是AuthFilter中的输出的这个日志， `if (Loggers.AUTH.isDebugEnabled()) { Loggers.AUTH.debug("access denied, request: {} {}, reason: {}", req.getMethod(), req.getRequestURI(), e.getErrMsg()); } resp.sendError(HttpServletResponse.SC_FORBIDDEN, e.getErrMsg());` 重点在于 resp.sendError这个东西在SpringBoot的环境下，默认会被封装为一个JSON结构的对象，同时呢SpringBoot中的DefaultErrorAttributes类errorAttributes.put("error", errorStatus.getReasonPhrase());会去默认值，不会输出我们的自定义的值。 目前Nacos的接口返回没有固定的结构。 可以将 AuthFilter类中的resp.sendError(HttpServletResponse.SC_FORBIDDEN, e.getErrMsg());方法，更改为如下代码 `resp.setStatus(HttpServletResponse.SC_FORBIDDEN); resp.getWriter().println(e.getErrMsg());` 应该可以解决这个问题。
> 
> 问下管理员，我可以提交下这个处理的2行代码的Pull Request吗
> 
> ### 扩展说明
> 但是当前系统中涉及到 resp.sendError的地方大概有将近20处，未来可能看看重写某些类进行统一处理下。 参考资料： https://www.yisu.com/zixun/202502.html https://blog.csdn.net/dfdvf/article/details/112523392

Nacos Server 的权限校验，不仅有用户是否登录的验证，还有多租户/多角色是否有某个配置项读写权限的验证，集群之间可信的验证、纯API接口的username/password方式的验证等等。虽然开源项目里默认没有着重强调这点，但是看代码以及数据表结构上是兼顾了这些逻辑的。感觉是因为设计不够严谨或者“部分开源”？？？导致功能逻辑看起来不够顺畅，因此才出现了需要在 JS 代码中根据 error message 的内容来判断是否需要重新登录这样的 if else 逻辑。所以如果只是修改 ```resp.sendError()``` 并不够严谨，无法确保没有其他问题，以及以后的代码维护者都能够清楚知道不可以使用 ```resp.sendError()```  。

**Comment by KomachiSion** [comment]
不存在部分开源， 默认鉴权插件从始自终均为社区自行贡献的，内部使用的一致都是aksk的鉴权插件。

由于社区自行贡献的时候，大多数人只是想解决他遇到的问题或者加自己要的功能，改着改着就冗余或者为了补丁而补丁，如果有兴趣的话，可以尝试维持体系的情况下好好重构设计一下，包含前端控制台模块化能力一起。

**Comment by yimao** [comment]
> 不存在部分开源， 默认鉴权插件从始自终均为社区自行贡献的，内部使用的一致都是aksk的鉴权插件。
> 
> 由于社区自行贡献的时候，大多数人只是想解决他遇到的问题或者加自己要的功能，改着改着就冗余或者为了补丁而补丁，如果有兴趣的话，可以尝试维持体系的情况下好好重构设计一下，包含前端控制台模块化能力一起。

哦哦，原来是这样的。

**Comment by KomachiSion** [comment]
> ### 当前问题
> 我定位了一下代码， 发现是AuthFilter中的输出的这个日志， `if (Loggers.AUTH.isDebugEnabled()) { Loggers.AUTH.debug("access denied, request: {} {}, reason: {}", req.getMethod(), req.getRequestURI(), e.getErrMsg()); } resp.sendError(HttpServletResponse.SC_FORBIDDEN, e.getErrMsg());` 重点在于 resp.sendError这个东西在SpringBoot的环境下，默认会被封装为一个JSON结构的对象，同时呢SpringBoot中的DefaultErrorAttributes类errorAttributes.put("error", errorStatus.getReasonPhrase());会去默认值，不会输出我们的自定义的值。 目前Nacos的接口返回没有固定的结构。 可以将 AuthFilter类中的resp.sendError(HttpServletResponse.SC_FORBIDDEN, e.getErrMsg());方法，更改为如下代码 `resp.setStatus(HttpServletResponse.SC_FORBIDDEN); resp.getWriter().println(e.getErrMsg());` 应该可以解决这个问题。
> 
> 问下管理员，我可以提交下这个处理的2行代码的Pull Request吗
> 
> ### 扩展说明
> 但是当前系统中涉及到 resp.sendError的地方大概有将近20处，未来可能看看重写某些类进行统一处理下。 参考资料： https://www.yisu.com/zixun/202502.html https://blog.csdn.net/dfdvf/article/details/112523392

除了控制台，需要看下其他情况下的影响，比如对sdk的影响。

**Comment by KomachiSion** [comment]
There is no more response from author and community, close discussion.
