### ISSUE TITLE
2.1.0版本内置数据库集群部署，控制台登录提示unknow user

### ISSUE THREAD

**Issue by suifengershi1027** [alibaba/nacos#9319]
**Describe the bug**
两个问题：
1.用2.1.0版本部署集群后，使用的是默认用户名、密码，搭建的集群，最开始是可以登录的，运行一段时间后，再登录提示unknow user
2.尝试升级2.1.1版本，换8868新端口搭建集群，又部署不成功了，protocol-raft.log错误提示『Fail to find node xxx in group naming_persistent_service』

**Expected behavior**
1.集群部署成功，能正常登录控制台

**Comment by KomachiSion** [comment]
1. 用户名密码错误，或者用户不存在
2. 看下cluster.conf是否一致， 如果是单机启动看下是否上次启动的ip和本次启动的ip不一致。是的话删除nacos/data目录重启。

**Comment by suifengershi1027** [comment]
> 1. 用户名密码错误，或者用户不存在
----用户名密码应该没有错的，一直是nacos/nacos，最开始是可以登录的，没改过配置

> 2. 看下cluster.conf是否一致， 如果是单机启动看下是否上次启动的ip和本次启动的ip不一致。是的话删除nacos/data目录重启。
----是3台物理机部署，端口都使用8868，cluster.conf 3个机器都一致，删除nacos/data重启后还是报错，报错信息：『Fail to connect xxx:7858, remoting exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception』

**Comment by KomachiSion** [comment]
1. unknow user只能是用户不存在或密码不对， 可能是谁把密码改掉了
2. 这应该是新问题， io exception 可能是网络问题。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
