### ISSUE TITLE
nacos 2.0.4版本自动升级问题

### ISSUE THREAD

**Issue by Jason-Yu-RD** [alibaba/nacos#9320]
> 2\. 另一种可能就是某些节点升级到了2.X，某些节点还是1.X， 因为2.X是根据ip+port来计算hash，而1.X是根据服务名计算hash，如果算法不同也会导致这个问题。

您好，按照您给的思路排查了一下，发现问题出现的原因在于 11.247.28.241 这个节点在故障时间点做了upgrade，由 com.alibaba.nacos.naming.core.v2.upgrade.UpgradeJudgement#initUpgradeChecker中定时任务触发，正如之前日志里面体现的这个时间点触发了 Upgrade to 2.0.X，之后出现节点路由异常。
![image](https://user-images.githubusercontent.com/20910068/195281842-f8b48eac-6a79-46cc-bc2c-7c95e990d399.png)

追踪了下代码，触发原因在于节点元数据中 readyToUpgrade属性，**_代码逻辑为当所有节点元数据均为true时，触发升级操作。_** 看了下当前节点元数据，**只有 11.247.28.241 节点的 readyToUpgrade 为true，其他均为false，但是也触发了upgrade操作，但是其他节点没有upgrade，导致了这个问题。**

![image](https://user-images.githubusercontent.com/20910068/195281338-b5175ffc-8dbf-4664-ace0-528189272036.png)
![image](https://user-images.githubusercontent.com/20910068/195281693-02386eca-2361-4bc1-9a92-a24cea5c8da6.png)

1. 搭建集群时，该节点没有特殊处理，为何元数据中 readyToUpgrade  与其他不同？
**_应该是这个判断逻辑 要求 serviceManager.getInstanceCount() == MetricsMonitor.getIpCountMonitor().get()，而我们这边一个IP上会起多个 instance 实例，导致 readyToUpgrade  为false，而某种条件路由下，部分节点 会变为true。_**
![image](https://user-images.githubusercontent.com/20910068/195493449-62d12799-102d-4d05-9e3a-b32e6cad122e.png)

2. 集群搭建的时候，版本是2.0.4，并非从1.x升级上来，为何还会触发 upgrade 操作？
3. 部分节点为true，但是也触发了 upgrade操作？
4. 或者如何禁止掉 upgrade检查，从根源上避免这个问题？

集群升级状态如下：
![image](https://user-images.githubusercontent.com/20910068/195316633-3891a5f3-018f-4872-af18-db11dcadf1d2.png)

_Originally posted by @Jason-Yu-RD in https://github.com/alibaba/nacos/issues/9184#issuecomment-1275727375_

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/2.0.0-upgrading.html

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by jiehao2019** [comment]
> https://nacos.io/zh-cn/docs/2.0.0-upgrading.html

请问一下，这个链接不可用了。最新链接是什么呢
