### ISSUE TITLE
报错load schema.sql error

### ISSUE THREAD

**Issue by shining-stars-lk** [alibaba/nacos#9321]
**Describe the bug**
nacos运行中出现load schema.sql error错误
- 版本 2.0.3
- 只用到服务注册功能，没有用配置中心功能
- 使用的集群化配置，采用内置的数据库

**Expected behavior**
没有错误信息

**Actually behavior**
nacos运行中出现load schema.sql error错误

![0E5E1AE6-8515-4e35-BE32-6EBE3C001E1A](https://user-images.githubusercontent.com/40255310/195548306-5deea48e-00c7-44ec-9f19-0bc9a2de44ae.png)

**Comment by KomachiSion** [comment]
Login timeout, 说明内置数据库没启动起来，一般是文件系统有问题导致的。看看其他日志有没有相关信息。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by shining-stars-lk** [comment]
今天仍然出现这个问题了，我看之前也有人反应这个问题。https://github.com/alibaba/nacos/issues/3607
