### ISSUE TITLE
nacos-config-spring-boot-starter run error

### ISSUE THREAD

**Issue by YangSihong** [alibaba/nacos#9322]
maven dependency :
`
 
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
          <groupId>org.jboss.resteasy</groupId>
          <artifactId>resteasy-jackson-provider</artifactId>
        </dependency>
        <dependency>
          <groupId>org.apache.dubbo</groupId>
          <artifactId>dubbo-rpc-rest</artifactId>
          <exclusions>
            <exclusion>
              <artifactId>guava</artifactId>
              <groupId>com.google.guava</groupId>
            </exclusion>
          </exclusions>
        </dependency>
        

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
`
run error:
启动报错：

`
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.postProcessBeanFactory(NacosPropertySourcePostProcessor.java:152)

The following method did not exist:

    com.alibaba.spring.util.BeanUtils.getBeanNames(Lorg/springframework/beans/factory/config/ConfigurableListableBeanFactory;Ljava/lang/Class;)[Ljava/lang/String;

The method's class, com.alibaba.spring.util.BeanUtils, is available from the following locations:

    jar:file:/D:/svn_repository/maven/repos/com/alibaba/spring/spring-context-support/1.0.8/spring-context-support-1.0.8.jar!/com/alibaba/spring/util/BeanUtils.class

It was loaded from the following location:

    file:/D:/svn_repository/maven/repos/com/alibaba/spring/spring-context-support/1.0.8/spring-context-support-1.0.8.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of com.alibaba.spring.util.BeanUtils
`

**Comment by hujun-w-2** [comment]
看着跟报冲突相关，可以贴一下你的spring dubbo  nacos相关依赖的版本

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
