### ISSUE TITLE
使用@EventListener监听服务注册事件,事件内容不符合预期

### ISSUE THREAD

**Issue by guyuexue** [alibaba/nacos#9326]
```java
@EventListener
public void instanceRegiterdEvent(InstanceRegiterdEvent<ServiceInstance> event) {
    // TODO 
}
```
实际接收到的event中config类型是`NacosDiscoveryProperties`,预期应该是`NacosServiceInstance`
导致使用`@EventListener`中condition进行条件判断时报错,找不到`ServiceInstance`中的属性

nacos版本:1.4.1
spring cloud alibaba版本: 2021.0.1.0

**Comment by KomachiSion** [comment]
请提交该issue到Spring cloud alibaba 社区。
