### ISSUE TITLE
通过GRPC代理向服务端注册客户端实例，客户端是如何向服务端发送心跳信息？

### ISSUE THREAD

**Issue by dangcom123** [alibaba/nacos#9327]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
gRPC不需要发送心跳信息， 只需要发送pingpong确认链接是否存在。

**Comment by dangcom123** [comment]
我是否可以理解为客户端实例检测是由Channel维持的，当Channel网络状态发生变化或者断开，服务端将剔除该实例



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "杨翊 ***@***.***&gt;; 
发送时间: 2022年10月17日(星期一) 上午9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] 通过GRPC代理向服务端注册客户端实例，客户端是如何向服务端发送心跳信息？ (Issue #9327)





 
gRPC不需要发送心跳信息， 只需要发送pingpong确认链接是否存在。

**Comment by KomachiSion** [comment]
差不多可以这么理解

**Comment by dangcom123** [comment]
多谢
