### ISSUE TITLE
springboot中ConfigService addListener无效

### ISSUE THREAD

**Issue by 807801002** [alibaba/nacos#9328]
springboot中，在ApplicationRunner类中用@NacosInjected 的configService.addListener无效，需要新NacosFactory.createConfigService(properties)创建出来的configService添加监听器才有效果。但是这种方式与NacosPropertySourcePostProcessor中添加的刷新propertySource到environment中无法保证先后顺序，在addListener中拿到的Environment还是旧的，有什么方法可以在新加的listener中能获取到带最新的propertySource的Environment？

**Comment by 807801002** [comment]
springboot 2.3.12.RELEASE

**Comment by hujun-w-2** [comment]
我这边在本地试了一下你的版本在ApplicationRunner中@NacosInjected是正常的
![image](https://user-images.githubusercontent.com/39894911/196425972-58eeed6c-7505-4ab2-aadf-8b998ab78ed8.png)

**Comment by 807801002** [comment]
configInfo是可以正常打出来的，没有错，但是spring的environment中的property属性还是旧的，我的解决方法是new NacosPropertySource，把configInfo传入构造一个新的proertySource，替换到environment中即可拿到最新配置的environment
