### ISSUE TITLE
Option to add service startup mode on the page

### ISSUE THREAD

**Issue by yfh0918** [alibaba/nacos#933]
是否可以在页面上增加服务启动模式的选项

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xuechaos** [comment]
@yfh0918 服务启动模式 具体是指什么？请详细描述一下？

**Comment by nkorange** [comment]
Start mode is removed from Nacos 1.0.0.
