### ISSUE TITLE
configuration rollback missed

### ISSUE THREAD

**Issue by coder-youme** [alibaba/nacos#934]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
Do Configuration rollback, file missed in data table config_info,
but  3 in table his_config_info.

### How to reproduce it (as minimally and precisely as possible)

1. Create a config file.
2. Modify the file.
3. Historical Versions do roll back

### Tell us your environment
V0.9.0
mysql 5.7
win 7 X64
jdk 1.8

**Comment by lujian0571** [comment]
Duplicate of #112
