### ISSUE TITLE
nacos暴露出来的metrics数据,其中nacos_monitor{name='leaderStatus'}指标,获取到的数据有0,1,2,想咨询下这几个状态都是什么意思,什么状态是正常的

### ISSUE THREAD

**Issue by llybood** [alibaba/nacos#9350]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
Old自研raft用于标记节点是否是leader的。
 
1是leader， 0是follower， 2是其他错误状态。 Old raft已经在1.4.0被废弃， 2.2版本彻底删除。这个metrics应该也会被彻底删除
