### ISSUE TITLE
Feature: 2.x removeConfig support remove beta Config by ConfigRemoveRequest handle in ConfigRemoveRequestHandler.

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#9353]
SDK 1.x 中虽然没有暴露出删除 beta 配置的  api removeConfig ，但增强包装设置 beta=true 能达到目的；
故而期望 2.x 中 ConfigRemoveRequest 也提供属性 beta=false/true ，然后 ConfigRemoveRequestHandler 根据是否 beta 作配置的删除。

PMC 是否认可这个修改？

---

**Is your feature request related to a problem? Please describe.**
SDK 1.x does not expose the api removeConfig for deleting the beta configuration, but the enhanced packaging setting beta=true can achieve the goal; 
Therefore, it is expected that the ConfigRemoveRequest in 2. x also provides the attribute beta=false/true, and then the ConfigRemoveRequestHandler performs configuration deletion based on whether it is beta.

**Describe the solution you'd like**
2.x removeConfig support remove beta Config by ConfigRemoveRequest handle in ConfigRemoveRequestHandler.

**Comment by CherishCai** [comment]
nacos-sdk-rust 中期望提供 api  publish_config_beta, remove_config_beta 
https://github.com/nacos-group/nacos-sdk-rust/blob/main/src/api/config.rs#L23-L64

**Comment by KomachiSion** [comment]
除非sdk-rust定位是maintain sdk，那就另说了

**Comment by CherishCai** [comment]
好咧。留后人有需求再做考虑和定制～
