### ISSUE TITLE
启动内存占用太高了

### ISSUE THREAD

**Issue by zgqq** [alibaba/nacos#9357]
[https://github.com/alibaba/nacos/blob/a9e2cbd4d8362d1fe04d1b37252d817ebb9e4037/naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java](https://github.com/alibaba/nacos/blob/a9e2cbd4d8362d1fe04d1b37252d817ebb9e4037/naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java)
 里面的
```Java
private BlockingQueue<Pair<String, DataOperation>> tasks = new ArrayBlockingQueue<>(1024 * 1024);
```
为什么要分配这么大？看了一下占了40mb，有点看不懂

**Comment by zgqq** [comment]
强烈意见这些会影响到内存的，都做成一个可配置项，有时候只是单机部署 测试环境或者单纯只想用配置中心，没必要那么大内存

**Comment by KomachiSion** [comment]
那你可以提个pr来改动，保证默认值和当前一致即可。

**Comment by wangshengji** [comment]
请问为什么不考虑使用LinkedBlockingQueue呢

**Comment by KomachiSion** [comment]
2.2中已经删除[DistroConsistencyServiceImpl.java](https://github.com/alibaba/nacos/blob/a9e2cbd4d8362d1fe04d1b37252d817ebb9e4037/naming/src/main/java/com/alibaba/nacos/naming/consistency/ephemeral/distro/DistroConsistencyServiceImpl.java)
