### ISSUE TITLE
集群模式代码逻辑问题

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/nacos#9358]
**Describe the bug**

![image](https://user-images.githubusercontent.com/31852897/196966166-6e8925e8-6d4f-4ea0-bf1c-42a69fe168aa.png)
![image](https://user-images.githubusercontent.com/31852897/196966335-67a4228d-be04-43d8-ae26-536024fc2cba.png)
根据上方代码逻辑 只要本地有cluster.conf文件 无论怎么配置 都无法使用address-server
删除本地home目录之后 第一次启动可以连接address-server 但是获取到之后 又会再本地创建cluster.conf文件
导致 重启又会变成file模式 这也太 ..... 完全失去了使用address-server的意义啊
希望官方可以修复此问题

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by JavaLionLi** [comment]
![image](https://user-images.githubusercontent.com/31852897/196969695-5ef8f5a1-5fe3-44f2-b5d8-47368f7a064b.png)
![image](https://user-images.githubusercontent.com/31852897/196969758-eb2b3e51-3502-4051-a2ec-ac64c78c53b5.png)
你们这官方示例 忽悠人玩呢啊.....硬是加两个括号 不看源码都不知道该咋写

**Comment by JavaLionLi** [comment]
建议注释说明白 避免误解 上下方的注释全都是[address-server]是个人都会理解需要加个括号吧

**Comment by KomachiSion** [comment]
[file,xxx] 这不就是可选范围意思吗？
