### ISSUE TITLE
Nacos2.0.4版本控制台手动下线一个服务后，后续服务重新注册状态时而健康，时而异常

### ISSUE THREAD

**Issue by zzl14273119** [alibaba/nacos#9359]
**Describe the bug**
在Nacos控制台上手动下线了一个服务，当后续该服务重新注册时，服务状态时而健康，时而异常，如果注册多个实例时，有的实例能够注册成功，有的实例注册失败
![image](https://user-images.githubusercontent.com/18340619/197107321-3091b184-276b-4a93-83e3-143c3765a500.png)
![image](https://user-images.githubusercontent.com/18340619/197107458-7797cde5-19b0-43d8-8798-7bb2422e19fb.png)
![image](https://user-images.githubusercontent.com/18340619/197107572-a71a998b-f820-40e6-bfe2-b349615f7776.png)
![image](https://user-images.githubusercontent.com/18340619/197107636-cdd0d79b-12ce-46f5-9a4c-57871e6bbfb0.png)

**Expected behavior**
重新注册服务后希望状态正常

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by zzl14273119** [comment]
我的客户端版本是1.3.0，服务端版本是2.0.4，因公司内需要平滑升级，目前处于测试阶段

**Comment by KomachiSion** [comment]
下线一个服务是指什么？ 下线一个nacos节点吗？ 还是下线一个服务的实例？

**Comment by zzl14273119** [comment]
> 下线一个服务是指什么？ 下线一个nacos节点吗？ 还是下线一个服务的实例？
指的是在控制台上手动下线一个微服务实例，不是下线一个Nacos节点

**Comment by zzl14273119** [comment]
经过代码问题排查，我们自己的代码中做了扩展，有一个功能是定时动态刷新Nacos上微服务实例的元数据信息，发现动态刷新时就会影响到服务正常注册，调用的方法：namingMainService.updateInstance()，客户端版本1.3.0，服务端版本2.0.4

**Comment by zzl14273119** [comment]
定时刷新的代码如下：
![image](https://user-images.githubusercontent.com/18340619/197762197-54204d2c-9621-4ce3-83d2-709b39a612a9.png)
![image](https://user-images.githubusercontent.com/18340619/197762333-2656e9c1-2731-413b-bb28-50d205f23cfc.png)
经过测试，2.0.4的客户端版本对2.0.4的服务端版本未出现上述Bug，但是经过此定时更新的代码，导致控制台上下线不掉服务实例了，客户端会一直跟服务端保持着通信

**Comment by KomachiSion** [comment]
那应该是扩展的代码有问题，不是社区的问题。

**Comment by zzl14273119** [comment]
扩展的代码逻辑很简单，只是读取内存信息和线程池信息然后更新到服务实例的元数据上，这段代码应该不会影响客户端与服务端通信，所以感觉问题的关键不在这里，而是调用NamingMaintationService的updateInstance方法导致了客户端与服务端通信异常，官方说2.0.4的服务端是完全兼容1.3.0的客户端的，后续还是得看一下源码
