### ISSUE TITLE
Nacos console Properties file configuration syntax exception

### ISSUE THREAD

**Issue by yyc-dev** [alibaba/nacos#936]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

Syntax error when using performance configuration format
For example: spring.datasource.url=jdbc:mysql://rm-xxx.com:3306/db?useUnicode=true
But in fact the syntax of the above example should be correct.

在使用Properties配置格式时会出现语法错误
例如：spring.datasource.url=jdbc:mysql://rm-xxx.com:3306/db?useUnicode=true
但是实际上面例子的语法应该是正确的

### Describe what you expected to happen

Please tell me the solution, or you can fix it
(请告诉我解决方案，或者你们可以修复它)

### How to reproduce it (as minimally and precisely as possible)

1. Create a configuration in the naocs console
2. Select the Properties format
3. Fill in spring.datasource.url=jdbc:mysql://rm-xxx.com:3306/db?useUnicode=true
4. A syntax error will occur when submitting

### Tell us your environment
NACOS1.0.0-RC1
Chrome 72

**Comment by Albert-Hugo** [comment]
@yyc-dev I had tried your config , but it did not show error message as you did.
Or do you mean this tips ?

![image](https://user-images.githubusercontent.com/33504588/56417017-36dc5700-62c5-11e9-99fc-9635fb35aeb1.png)

**Comment by yyc-dev** [comment]
> @ yyc-dev我已经尝试过你的配置，但它没有像你那样显示错误信息。
> 或者你的意思是这个提示？
> 
> ![图片](https://user-images.githubusercontent.com/33504588/56417017-36dc5700-62c5-11e9-99fc-9635fb35aeb1.png)

是的就是这个

**Comment by yyc-dev** [comment]
> @yyc-dev I had tried your config , but it did not show error message as you did.
> Or do you mean this tips ?
> 
> ![image](https://user-images.githubusercontent.com/33504588/56417017-36dc5700-62c5-11e9-99fc-9635fb35aeb1.png)

Yes, that's what it means

**Comment by nkorange** [comment]
This message box is just a warning, doesn't influence the publish of configuration.
