### ISSUE TITLE
Bitwise OR of signed byte value

### ISSUE THREAD

**Issue by dingzx3** [alibaba/nacos#9362]
SpotBugs: Bitwise OR of signed byte value Loads a byte value
<img width="877" alt="image" src="https://user-images.githubusercontent.com/111035198/197143409-9b318482-f64c-4e2e-a51a-92096062bce9.png">

**Comment by KomachiSion** [comment]
My idea has no hint for this. Can you describe why change this?

The code is worked from 2018 and work well. If no reason I think no need to change.

**Comment by KomachiSion** [comment]
No more response from author, and no enough reason to change this.
