### ISSUE TITLE
nacos配置项secret,key修改后，控制台无法登录

### ISSUE THREAD

**Issue by JunjieBian** [alibaba/nacos#9367]
**Is your feature request related to a problem? Please describe.**
nacos.core.auth.plugin.nacos.token.secret.key，这个配置项修改为任意其它值后，控制台能正常启动，但是用默认账号密码不能登录。
这个不能修改吗？版本：2.1.2
After this configuration item is changed to any other value, the console can be started normally, but cannot log in with the default account and password.
Can't this be modified?
Version: 2.1.2

**Comment by YunWZ** [comment]
@i will resolv it@

**Comment by YunWZ** [comment]
修复此bug之前，你可以通过将密钥进行base64编码来规避此问题。（你的密钥长度不能低于32位）

**Comment by KomachiSion** [comment]
我觉得改了这个值， 插入数据库的nacos的默认密码也需要重新编码更新才行，否则对不上值应该是正常现象
