### ISSUE TITLE
关于鉴权的疑问

### ISSUE THREAD

**Issue by zgqq** [alibaba/nacos#9370]
看了官网的文档，说现在的鉴权方式不够安全，能具体在文档说明一下现在鉴权方式的缺陷吗，如果鉴权有问题的话，也不敢开放web ui到外网，大部分人用的网络和服务器网络也不是统一线路的，web ui在外网用是刚需

**Comment by KomachiSion** [comment]
默认鉴权实现是一个demo实现，目的是提供插件实现的样例以及简单的防治错用的一个鉴权能力，不保证安全能力。
简单的用户名密码及token体系在代码开源的前提下容易因泄漏或其他问题导致不安全，因此不建议开放到公网环境，而且本身nacos的产品属性就不适宜暴露的公网， 这和skywalking等一些内部中间价定位是一致的。

如果一定要使用，可以通过办公网限制等等限制非预期访问，并且最好开发自己的鉴权插件接入公司安全的体系，来提高开放到公网的安全性。
