### ISSUE TITLE
Nacos Config NacosPropertySourceBuilder parse error

### ISSUE THREAD

**Issue by Xyk859852** [alibaba/nacos#9372]
When using SpringCloudAlibaba, Nacos configuration center, using sharedConfigs or extensionConfigs to load the configuration, when the configuration is in JsonArray format, is there any exception when the configuration is refreshed? For example, can the parse object only be a JsonObject Object not a JSONArray??

The corresponding version is SpringCloudAlibaba: 2021.0.1.0 SpringCloud: 2021.0.1, SpringBoot: 2.6.8

**Comment by KomachiSion** [comment]
Please move to Spring Cloud Alibaba community, Nacos only push the original config content to application, parse config is not nacos' work.
