### ISSUE TITLE
以服务的ipv6地址注册到nacos成功，但是用FeighClient从注册中心获取的ipv6做远程调用有问题，问题如下

### ISSUE THREAD

**Issue by fufk2022** [alibaba/nacos#9374]
![注册地址](https://user-images.githubusercontent.com/109076275/197436168-56f88a92-b2ca-4747-9774-fb5e4feea46d.png)
![ipv6Error](https://user-images.githubusercontent.com/109076275/197436219-323a0495-2b87-461b-bf03-7cb8a6b69f6c.PNG)
![服务调用](https://user-images.githubusercontent.com/109076275/197436325-b3ebe2cb-9b3f-4b5b-b5a0-1d22e466d39e.PNG)

目前nacos版本：1.4.1

**Comment by fufk2022** [comment]
其他版本我看了，好像只是支持注册中心是ipv6地址的配置，不支持服务以ipv6形式进行远程调用

**Comment by KomachiSion** [comment]
这是服务自己的问题， nacos的注册和发现是正常的。
