### ISSUE TITLE
使用者99%都是国内的，不能迁移到gitee吗，git总是打不开，下载个安装包要下载几个小时。

### ISSUE THREAD

**Issue by deke1521** [alibaba/nacos#9375]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deke1521** [comment]
何必为难自己人

**Comment by linghengqian** [comment]
- FYI, platforms like `Gitee` and `Gitlab JH` adopt some static resource CDNs related to Tencent Cloud. This made it impossible to view the site properly, including in places like India and France . I would argue against moving such project principals when problems like this persist for a long time, which would greatly disrupt collaboration with upstream and downstream dependencies.

- Refer to https://jihulab.com/gitlab-cn/gitlab/-/issues/1614 .

**Comment by 412111959** [comment]
可以试试用某雷下载,速度会快很多
