### ISSUE TITLE
distro config syncTimeout is invalid 

### ISSUE THREAD

**Issue by dennissky** [alibaba/nacos#9379]
1.nacos-server:2.0.3
2.application.properties
nacos.core.protocol.distro.data.sync.timeoutMs=10000

i can see this in **nacos.log**
2022-10-24 15:16:16,225 INFO Get Distro config from env, 
DistroConfig{syncDelayMillis=1000, syncTimeoutMillis=10000, 
syncRetryDelayMillis=3000, verifyIntervalMillis=5000, verifyTimeoutMillis=6000, loadDataRetryDelayMillis=30000}
but when network shake i find **protocol-distro.log**
2022-10-23 07:01:25,589 WARN [DISTRO] Sync data change failed.
java.util.concurrent.TimeoutException: Timeout after 3000 milliseconds.
	at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection$2.onFailure(GrpcConnection.java:154)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1077)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

so i use arthas to find if the timeout is set correct
and i can see 
![image](https://user-images.githubusercontent.com/12591356/197475733-586a78a9-c802-4c24-9e66-b3d362613c68.png)

and i find the syncDelayMillis is incorrect because i find GlobalConfig overwirte this value

**Comment by dennissky** [comment]
why i set nacos.core.protocol.distro.data.sync.timeoutMs=10000
but it really work is 3000

**Comment by karsonto** [comment]
The new version has solved this problem.

**Comment by karsonto** [comment]
refer ISSUE #8050

**Comment by dennissky** [comment]
> refer ISSUE #8050

i merge my code with this[8292d9e](https://github.com/alibaba/nacos/commit/8292d9e16ccfb27dd59ead9a48e737c45747723c) use tag 2.0.3 and it dont work yet。What am I missing？

**Comment by dennissky** [comment]
> refer ISSUE #8050

i merge my code with this[8292d9e](https://github.com/alibaba/nacos/commit/8292d9e16ccfb27dd59ead9a48e737c45747723c) use tag 2.0.3 and it dont work yet。What am I missing？

**Comment by karsonto** [comment]
Invite the author to answer @onewe

**Comment by dennissky** [comment]
> Invite the author to answer @onewe

it works,my fault。thanks!
