### ISSUE TITLE
1.4.1版本Nacos出现注册实例同步问题导致实例不一致

### ISSUE THREAD

**Issue by liulei08** [alibaba/nacos#9387]
观察到Nacos节点间注册实例不一致，通过打印日志发现，serviceMap和dataStore保存的Map两者数据不一致，猜测是脑裂引起的问题，使得dataStore里面的负责实例信息被删除，导致datum同步接口因为数据丢失导致没办法同步给其它节点。之前有看到类似的issue（https://github.com/alibaba/nacos/issues/7734 ，想问下这个问题有修复吗？哪个版本修复了这个问题？解决方案是怎样的？

**Comment by KomachiSion** [comment]
升级到2.1以上版本吧， 机制都变化了。不会再有serviceMap和dataStore两层数据存储了。

**Comment by liulei08** [comment]
> 升级到2.1以上版本吧， 机制都变化了。不会再有serviceMap和dataStore两层数据存储了。

升级动作有点大，如果只对1.x版本进行bug修复，有修改方案吗？

**Comment by KomachiSion** [comment]
那需要精确问题，你关联的那个issue和你描述的问题不是同一个问题， 关联issue的问题在1.2.1已解决。

如果你需要在1.4.x修复，你需要先定位到具体问题，然后再看修改方案。

**Comment by liulei08** [comment]
> 那需要精确问题，你关联的那个issue和你描述的问题不是同一个问题， 关联issue的问题在1.2.1已解决。
> 
> 如果你需要在1.4.x修复，你需要先定位到具体问题，然后再看修改方案。

目前发现的现象是节点A的serviceMap里面存在服务a实例数据并负责该服务，但是dataStore里面不存在服务a的datum数据，此时节点B一直获取不到服务a的实例数据，即节点A和节点B服务实例数据不一致，且是个稳定的过程。

**Comment by KomachiSion** [comment]
定位到是怎么出现了吗？

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by limeuser** [comment]
nacos的代码质量真他妈垃圾
