### ISSUE TITLE
Nacos client service registration does not divide the namespace, the default registration is under the public namespace

### ISSUE THREAD

**Issue by XCXCXCXCX** [alibaba/nacos#939]
When I registered with the spring-cloud-alibaba-nacos-discovery test service, I found that regardless of whether I specified the namespace, the final service will be registered to the public namespace, and then the positioning code found that the namingService API in the nacos-api module does not provide the namespace parameter.

The spring cloud nacos discovery version is 0.2.2.BUILD-SNAPSHOT
The dependent version is nacos-api 0.6.2

Then I looked at nacos-api:1.0.0-RC1 and found that the namespace parameter is still not available in the namingService API.
Since spring cloud alibaba nacos relies on the nacos api module, I hope to improve the nacos client as soon as possible.

**Comment by nkorange** [comment]
Nacos client 0.8.0 already supports namespace. Upgrade your nacos client please.
