### ISSUE TITLE
chooser optimization reduces array usage and redundant for loops

### ISSUE THREAD

**Issue by RapperCL** [alibaba/nacos#9391]
path:com.alibaba.nacos.client.naming.utils.Chooser

chooser optimization :
reduces array usage and redundant for loops
1 The first for loop stores the nodes whose probability has been calculated through the double array;

2 The second for loop calculates the overall probability distribution array based on the probability of the first step;
The first double array is not needed, it can be replaced directly with a variable, and the two for loops should be combined into one.

![image](https://user-images.githubusercontent.com/44110731/197723329-d2559bfd-7b57-4861-8029-0545912a6336.png)

**Comment by KomachiSion** [comment]
I read this codes, I think this array size might be `index` no items.size()

**Comment by RapperCL** [comment]
> I read this codes, I think this array size might be `index` no items.size()

Supplement the screenshot after the modification. In fact, the change in general is that the original exactWeights array is replaced by the variable exactWeight, and then the two for loops are merged into one
补充上修改之后的截图，其实改动总的来说就是，将原本的exactWeights数组通过变量exactWeight替代了，然后将两个for循环合并为一个了
![image](https://user-images.githubusercontent.com/44110731/198182429-44118785-0714-48ca-b52c-6f76ea4046fc.png)

**Comment by RapperCL** [comment]
@KomachiSion  hey bro, what do you think about this now

**Comment by KomachiSion** [comment]
我知道你的改动意思， 我回复的意思是我读代码感觉后一个数组的长度不应该是item.size，
如果后一个数组的长度不应该是item.size，那么你就不能按照你这个修改来改动

**Comment by RapperCL** [comment]
> 我知道你的改动意思， 我回复的意思是我读代码感觉后一个数组的长度不应该是item.size，
> 如果后一个数组的长度不应该是item.size，那么你就不能按照你这个修改来改动

嗯，目前而言，后一个数组的长度一定是item.size， 但是你的考虑是对的，我重新修改了一下，同时对构造方法做了一点
增强，一方面避免空异常，另一方面让itemsWithWeight这个集合的初始化有了意义。
<img width="530" alt="image" src="https://user-images.githubusercontent.com/44110731/198929758-197cc21c-f79e-4387-85c8-271abc725618.png">
