### ISSUE TITLE
I hope nacos login auth can resolve url code

### ISSUE THREAD

**Issue by RuicyWu** [alibaba/nacos#9398]
![QQ图片20221026102824](https://user-images.githubusercontent.com/53590729/197925442-7f303d25-e62a-417e-bab3-42dc7c21e480.png)

Authentication function of the latest version of nacos can not resolve the password which was configured in the configuration center of nacos and contained special characters such as '!','@','+'. These special characters would be read as URL code. So i hope these URL code could be discerned.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A handler for URL code should be added to this api "/nacos/v1/auth/users/login?username=?". It can  auto-convert URL code of the password in the request body.
**Describe alternatives you've considered**

**Additional context**

**Comment by bigerro** [comment]
Which version?

**Comment by RuicyWu** [comment]
2.1.2&nbsp;发送
&nbsp;


RuicyWu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 中午11:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] I hope nacos login auth can resolve url code (Issue #9398)





 
Which version?

**Comment by RuicyWu** [comment]
2.1.2




RuicyWu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月26日(星期三) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] I hope nacos login auth can resolve url code (Issue #9398)





 
Which version?

**Comment by KomachiSion** [comment]
I remember the special words like `@` has been supported in 1.X version. 2.X has contain this fixes. If the new version cause again, need community to research problem and try to fix.

**Comment by bigerro** [comment]
I didn't find any problems 
<img width="913" alt="微信截图_20221026162150" src="https://user-images.githubusercontent.com/51319439/197973825-56cfb261-0570-4bab-a947-fcc0c57463b3.png">

**Comment by RuicyWu** [comment]
Have you put the password in  the configuration center?
![image](https://user-images.githubusercontent.com/53590729/197975239-f828e827-6e72-4898-a240-12f31de5763f.png)

**Comment by YunWZ** [comment]
which is your spring cloud alibaba version？

**Comment by RuicyWu** [comment]
2.2.3.RELEASE

**Comment by YunWZ** [comment]
> 2.2.3.RELEASE

SCA 2.2.3.RELEASE depends on Nacos 1.3.3, which is too old.
Maybe you can update to SCA 2.2.7RELEASE+, 2.2.9.RELEASE is recommended.

Full version matrix: https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by RuicyWu** [comment]
No, it didn't help. And I can't even start the demo application.
![image](https://user-images.githubusercontent.com/53590729/201309846-625b7a3a-8cbf-4058-809c-e180a0fdbeec.png)
