### ISSUE TITLE
Nacos 2.1.2 jurisdiction control is not effective

### ISSUE THREAD

**Issue by RuicyWu** [alibaba/nacos#9399]
**Describe the bug**
![image](https://user-images.githubusercontent.com/53590729/197932084-3058a0ba-29f2-449d-82a3-ec4ed6d3f21d.png)
The role ROLE_DEV is configured with read-only permission to the public space, but this role can still delete and modify the contents of the public space.

**Expected behavior**

**Actually behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 - Version [e.g. nacos-server 2.1.2]

**Additional context**

**Comment by karsonto** [comment]
do you turn on nacos.core.auth.enabled=true ?

**Comment by RuicyWu** [comment]
ok,i forget that,my fault
&nbsp;


RuicyWu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午3:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] Nacos 2.1.2 jurisdiction control is not effective (Issue #9399)





 
do you turn on nacos.core.auth.enabled=true ?
