### ISSUE TITLE
The nacos service list does not display the service, the service shows that the registration is successful.

### ISSUE THREAD

**Issue by mybug99** [alibaba/nacos#940]
代码提示注册成功，当调用服务发现也能查看到点击创建服务显示服务存在，，但是服务列表无法查看。
nacos registry, nacos-order 192.168.1.107:8090 register finished
![image](https://user-images.githubusercontent.com/43434812/54732868-2c00aa80-4bd1-11e9-9660-38c79465d516.png)
![image](https://user-images.githubusercontent.com/43434812/54732875-30c55e80-4bd1-11e9-801f-282d3a8de1db.png)
![image](https://user-images.githubusercontent.com/43434812/54732879-33c04f00-4bd1-11e9-93ed-d889c13faf41.png)

**Comment by paderlol** [comment]
请问你用的什么版本的Nacos服务端和客户端？

**Comment by mybug99** [comment]
0.9.0

**Comment by mybug99** [comment]
> 请问你用的什么版本的NACOS服务端和客户端？

0.9.0

**Comment by mybug99** [comment]
> 请问你用的什么版本的NACOS服务端和客户端？

jar是 0.2.1

**Comment by liliexuan** [comment]
me too。 
![image](https://user-images.githubusercontent.com/12954661/54733287-db3e8100-4bd3-11e9-88ee-0515b30e8df9.png)

**Comment by mybug99** [comment]
> me too。
> ![image](https://user-images.githubusercontent.com/12954661/54733287-db3e8100-4bd3-11e9-88ee-0515b30e8df9.png)

有解决方案吗，有的话回复我一下谢谢

**Comment by paderlol** [comment]
先升级客户端Nacos client到0.9.0吧

**Comment by mybug99** [comment]
> Nacos client

我用的springcloud的jar啊

**Comment by paderlol** [comment]
我知道啊，它里面也依赖了Nacos client啊

**Comment by mybug99** [comment]
> 知道啊，它里面也依赖了Nacos client啊

ok我加一下

**Comment by mybug99** [comment]
> 我知道啊，它里面也依赖了Nacos client啊

不行的如果加依赖我都不能注册的

**Comment by paderlol** [comment]
加0.9.0，不要加1.0.0-RC1

**Comment by paderlol** [comment]
指定0.9.0，不要使用latest

**Comment by mybug99** [comment]
> 加0.9.0，

> 加0.9.0，不要加1.0.0-RC1

好了，但是还是无法查看

**Comment by mybug99** [comment]
> 指定0.9.0，不要使用latest

也是指定名称在浏览器能看到注册上来的信息但是在服务列表是查不到的

**Comment by mybug99** [comment]
> 指定0.9.0，不要使用latest

多谢已经解决，清了浏览器缓存

**Comment by mybug99** [comment]
> me too。
> ![image](https://user-images.githubusercontent.com/12954661/54733287-db3e8100-4bd3-11e9-88ee-0515b30e8df9.png)

清理一下浏览器缓存

**Comment by paderlol** [comment]
好的 麻烦close一下issue

**Comment by mybug99** [comment]
> 好的麻烦关闭一下问题

好的
