### ISSUE TITLE
解析配置文件类型不太合理

### ISSUE THREAD

**Issue by Sunw730** [alibaba/nacos#9403]
目前Nacos可配置文件类型的地方有：

1. bootstrap中通过`spring.cloud.nacos.config.file-extension`指定配置类型（对于application有效）
2. 通过dataId的后缀名来指定配置类型（对于shared/ext/application生效）
3. 在nacos后台设置配置文件类型（尽管目前这个操作不会影响程序解析配置）

其中第3种方式作为新增配置的一个入口，但是nacos后台的设置文件类型功能仅仅用于页面代码的友好展示，nacos客户端并没有根据这里的类型来进行解析配置，这跟java的“一处修改，多出运行”理念不符。
所以个人建议配置类型统一由nacos服务端决定（先通过dataId后缀解析配置类型，如果没有后缀则获取nacos服务端保存的配置类型），对于客户端不支持的配置类型（如text/html）的配置，可以按照默认类型处理（解析异常直接抛出）或者直接作为异常处理。

**Comment by KomachiSion** [comment]
nacos其实不关心文件类型， 对nacos来说都是当文本处理。同样的对data-id也不关心是什么后缀。

控制台有文件类型是为了前端方便进行格式化的一个易用性优化。

目前客户端也不会去解析配置，解析工作是应用框架做的， 如果觉得解析不合理，可以移交issue到对应的应用框架社区。

**Comment by Sunw730** [comment]
> nacos其实不关心文件类型， 对nacos来说都是当文本处理。同样的对data-id也不关心是什么后缀。
> 
> 控制台有文件类型是为了前端方便进行格式化的一个易用性优化。
> 
> 目前客户端也不会去解析配置，解析工作是应用框架做的， 如果觉得解析不合理，可以移交issue到对应的应用框架社区。

nacos不关心文件类型可以理解，但是接口不应该直接返回String类型，至少把nacos里的文件类型字段返回，不然客户端只能根据客户端的配置去解析了。这就造成多种方式获取文件类型的的现状

**Comment by KomachiSion** [comment]
nacos不关心文件类型了，返回的肯定是文本。 怎么解析，是什么类型使用方才知道。即使是规范化的v2 openAPI，也不会返回类型。也是按照错误码，data等一些固定内容进行返回。
