### ISSUE TITLE
protobuf not support apple M1(aarch64)

### ISSUE THREAD

**Issue by presenth7s** [alibaba/nacos#9405]
**Describe the bug**
protobuf not support apple M1(aarch64)

**Expected behavior**
successfully

**Actually behavior**
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile (default) on project nacos-consistency: Unable to resolve artifact: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.16.1
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.16.1 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.16.1 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]   	1) com.alibaba.nacos:nacos-consistency:jar:2.1.0
[ERROR]   	2) com.google.protobuf:protoc:exe:osx-aarch_64:3.16.1
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR]   com.alibaba.nacos:nacos-consistency:jar:2.1.0
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public, releases=true, snapshots=false)

**How to Reproduce**
1. mvm compile

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Version nacos-server 2.1.2

**Additional context**

-  Whether to consider upgrading grapc and protobuf versions, and consider compatibility, the relevant version dependencies are as follows：
 `<grpc-java.version>1.43.1</grpc-java.version>`
   `<proto-google-common-protos.version>2.7.1</proto-google-common-protos.version>`
  ` <protobuf-java.version>3.19.1</protobuf-java.version>`
   `<protoc-gen-grpc-java.version>${grpc-java.version}</protoc-gen-grpc-java.version>`

**Comment by YunWZ** [comment]
the same issue as https://github.com/alibaba/nacos/issues/7572

**Comment by presenth7s** [comment]
> the same issue as #7572

can't understand why the nacos official does not solve this compatibility problem, but closes the issue directly.

**Comment by KomachiSion** [comment]
The solution is in issue, you should check the issue comment and try to solve.

You can try to upgrade version in your local env and test to use, for our test, the upgrade for protobuf and grpc will cause the jraft can't work.
