### ISSUE TITLE
服务注册到nacos1.4.2集群时，服务名中包含中横线或者随意mn的不能注册，返回400错误，而诸如hello或者world名字却能注册

### ISSUE THREAD

**Issue by jsying1570** [alibaba/nacos#9407]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
I can't reproduce your problem, please provider more information like logs or error info.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
