### ISSUE TITLE
The config refresh configuration cannot be refreshed, the client reports an error, and can be refreshed to the configuration after restarting. The controller's refresh configuration is also added.

### ISSUE THREAD

**Issue by mybug99** [alibaba/nacos#941]
ERROR 3644 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [] [NACOS-XXXX] [notify-error] dataId=nacos-order.yml, group=DEFAULT_GROUP, md5=89f4ac4415691d979ab41db6f256c7b8, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@baae415 tx=null这个错，

**Comment by mybug99** [comment]
有人知道吗，一直会报这个错，是不是cloud版本的问题

**Comment by zzps** [comment]
我使用的nacos 0-9-0版本在按照spirngcloud手册配置完成后，发现修改配置不会刷新，我可以很确定的说不是我配置的问题，在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没执行，准备用最新的rc版本试试。

**Comment by mybug99** [comment]
> 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没

最新版的你注册都注册不上的

**Comment by zzps** [comment]
> 
> 
> > 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没
> 
> 最新版的你注册都注册不上的

我刚才rc版本的下载不下来   我准备换0-7-0版本的试试

**Comment by mybug99** [comment]
> > > 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没
> > 
> > 
> > 最新版的你注册都注册不上的
> 
> 我刚才rc版本的下载不下来 我准备换0-7-0版本的试试

我的是cloud的项目家的cloud的jar

**Comment by zzps** [comment]
> 
> 
> > > > 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没
> > > 
> > > 
> > > 最新版的你注册都注册不上的
> > 
> > 
> > 我刚才rc版本的下载不下来 我准备换0-7-0版本的试试
> 
> 我的是cloud的项目家的cloud的jar
玩个蛋啊  0-7-0也不行

**Comment by mybug99** [comment]
> > > > > 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没
> > > > 
> > > > 
> > > > 最新版的你注册都注册不上的
> > > 
> > > 
> > > 我刚才rc版本的下载不下来 我准备换0-7-0版本的试试
> > 
> > 
> > 我的是cloud的项目家的cloud的jar
> > 玩个蛋啊  0-7-0也不行

 我的觉得应该是我的cloud版本问题

**Comment by zzps** [comment]
> 
> 
> > > > > > 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没
> > > > > 
> > > > > 
> > > > > 最新版的你注册都注册不上的
> > > > 
> > > > 
> > > > 我刚才rc版本的下载不下来 我准备换0-7-0版本的试试
> > > 
> > > 
> > > 我的是cloud的项目家的cloud的jar
> > > 玩个蛋啊  0-7-0也不行
> 
> 我的觉得应该是我的cloud版本问题

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config
按照上面这个链接跑是能自动更新了

**Comment by mybug99** [comment]
> > > > > > > 在项目重启后就能获取修改后的值了，我也看了他里面的的监听器就压根没
> > > > > > 
> > > > > > 
> > > > > > 最新版的你注册都注册不上的
> > > > > 
> > > > > 
> > > > > 我刚才rc版本的下载不下来 我准备换0-7-0版本的试试
> > > > 
> > > > 
> > > > 我的是cloud的项目家的cloud的jar
> > > > 玩个蛋啊  0-7-0也不行
> > 
> > 
> > 我的觉得应该是我的cloud版本问题
> 
> https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config
> 按照上面这个链接跑是能自动更新了

嗯你可以试试，我应该换个版本就可以了

**Comment by zzps** [comment]
好了   我已经确定我的springboot2.1.3和spring-cloud-starter-alibaba-nacos-config0.2.1版本不兼容 ，换成2.0.x就可以了

**Comment by mybug99** [comment]
有人吗- -

**Comment by mybug99** [comment]
有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -有人吗- -

**Comment by pguo65535** [comment]
亲，在呢...

**Comment by mybug99** [comment]
> 亲，在呢？

请问你知道我的原因吗，现在我配置文件用application:
    name: nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
客户端的Data Id 是nacos-order.yaml 无法刷新配置，然后我这边也无法拿到配置信息，如果换成yml的话都配置yml 倒是可以，但是得重启配置才刷新，现在配置都不刷新了，哎，让我头大，一下老了十几岁

**Comment by yanlinly** [comment]
@mybug99   有问题的运行目录/logs/nacos.log日志能发一下吗。

**Comment by mybug99** [comment]
> @mybug99 有问题的运行目录/logs/nacos.log日志能发一下吗。

好了，应该是nacos的问题，和我boot启动类上的注解顺序有问题，我改变了一下注解顺序解决了

**Comment by flystar32** [comment]
目前啊 spring-cloud-alibaba 还没有进入 Spring Cloud 的主版本，所以需要自行指定与 Spring Cloud 相对于的版本，版本说明参考这里  https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

Spring Boot 和 Spring Cloud 的版本说明参考这里 https://spring.io/projects/spring-cloud#release-trains

**Comment by yanlinly** [comment]
> 好了，应该是nacos的问题，和我boot启动类上的注解顺序有问题，我改变了一下注解顺序解决了

@mybug99  能帮忙详细描述一下吗，我们看看是不是后续在对应文档部分做一下强调

**Comment by mybug99** [comment]
> > 好了，应该是nacos的问题，和我boot启动类上的注解顺序有问题，我改变了一下注解顺序解决了
> 
> @mybug99 能帮忙详细描述一下吗，我们看看是不是后续在对应文档部分做一下强调

好的，我不知道您了解过byte-tcc没有不能兼容两者，我刚才试了几遍确定了问题的所在
@Import(SpringCloudSecondaryConfiguration.class) byte-tcc需要在注解引用的，加了这个我无法刷新配置，去掉即可，但是会导致byte-tcc不可用，github开源的byte-tcc
