### ISSUE TITLE
Does nacos support exporting configuration incrementally?

### ISSUE THREAD

**Issue by hdygxsj** [alibaba/nacos#9410]
As the title says, does nacos support exporting configuration incrementally by version and merging configurations when importing

**Comment by KomachiSion** [comment]
Not support for now, and no plan for recent version.

In my opinion, the feature is not used for most of situation. Nacos is no care for the config content and most of app and users only pay attention to the newest version config. 

I don't know which situation this feature need?

**Comment by zyy1161623489** [comment]
Our company has very high network security requirements, each environment (such as development environment, test environment and production environment) will deploy a nacos cluster separately, and there will be multiple test environments for different test scenarios. When the requirements enter the test phase, the configuration needs to be imported from the development environment to the test environment, which is very difficult. When we submit our code to the testers, we need to perform CI/CD, but when we CICD, we cannot automatically synchronize the newly added configuration from one nacos cluster to another nacos cluster. If we export the configuration from one nacos cluster and import it in another cluster, this overrides what I changed in the other cluster (such as the URL in a configuration). Therefore, whenever we CICD, we need to manually compare the configuration between different clusters and handle it manually, which leads to an increase in our operation and maintenance cost. If nacos supported incremental exports and incremental imports, our operations would be much easier. Or is there a better way of practice that you can provide for my reference? Thank you

————————————————————————————————————————————————————————————

我们公司的有非常高的网络安全要求，每个环境（比如开发环境，测试环境与生产环境）都会单独部署一个nacos集群，并且会有多个测试环境用于不同的测试场景。当需求进入测试阶段，需要把配置从开发环境导入到测试环境，这非常困难。当我们的代码提交给测试人员，我们需要进行CI/CD，但当我们CICD时，我们没法自动将本次新增的配置从一个nacos集群同步到另一个nacos集群。如果我们从一个nacos集群导出配置，并在另一个集群导入，这会覆盖掉我在另一个集群修改的内容（比如某项配置中的URL）。所以每当我们CICD时，都需要人工比对不同集群之间的配置，并且手工处理，这导致增加了我们的运维成本。如果nacos支持增量导出与增量导入，我们的运维工作将会轻松许多。或者有没有更好的实践方式可以提供给我作为参考，谢谢!

**Comment by zyy1161623489** [comment]
> Not support for now, and no plan for recent version.
> 
> In my opinion, the feature is not used for most of situation. Nacos is no care for the config content and most of app and users only pay attention to the newest version config.
> 
> I don't know which situation this feature need?

Our company has very high network security requirements, each environment (such as development environment, test environment and production environment) will deploy a nacos cluster separately, and there will be multiple test environments for different test scenarios. When the requirements enter the test phase, the configuration needs to be imported from the development environment to the test environment, which is very difficult. When we submit our code to the testers, we need to perform CI/CD, but when we CICD, we cannot automatically synchronize the newly added configuration from one nacos cluster to another nacos cluster. If we export the configuration from one nacos cluster and import it in another cluster, this overrides what I changed in the other cluster (such as the URL in a configuration). Therefore, whenever we CICD, we need to manually compare the configuration between different clusters and handle it manually, which leads to an increase in our operation and maintenance cost. If nacos supported incremental exports and incremental imports, our operations would be much easier. Or is there a better way of practice that you can provide for my reference? Thank you

————————————————————————————————————————————————————————————

我们公司的有非常高的网络安全要求，每个环境（比如开发环境，测试环境与生产环境）都会单独部署一个nacos集群，并且会有多个测试环境用于不同的测试场景。当需求进入测试阶段，需要把配置从开发环境导入到测试环境，这非常困难。当我们的代码提交给测试人员，我们需要进行CI/CD，但当我们CICD时，我们没法自动将本次新增的配置从一个nacos集群同步到另一个nacos集群。如果我们从一个nacos集群导出配置，并在另一个集群导入，这会覆盖掉我在另一个集群修改的内容（比如某项配置中的URL）。所以每当我们CICD时，都需要人工比对不同集群之间的配置，并且手工处理，这导致增加了我们的运维成本。如果nacos支持增量导出与增量导入，我们的运维工作将会轻松许多。或者有没有更好的实践方式可以提供给我作为参考，谢谢!

**Comment by li-xiao-shuang** [comment]
> > Not support for now, and no plan for recent version.
> > In my opinion, the feature is not used for most of situation. Nacos is no care for the config content and most of app and users only pay attention to the newest version config.
> > I don't know which situation this feature need?
> 
> Our company has very high network security requirements, each environment (such as development environment, test environment and production environment) will deploy a nacos cluster separately, and there will be multiple test environments for different test scenarios. When the requirements enter the test phase, the configuration needs to be imported from the development environment to the test environment, which is very difficult. When we submit our code to the testers, we need to perform CI/CD, but when we CICD, we cannot automatically synchronize the newly added configuration from one nacos cluster to another nacos cluster. If we export the configuration from one nacos cluster and import it in another cluster, this overrides what I changed in the other cluster (such as the URL in a configuration). Therefore, whenever we CICD, we need to manually compare the configuration between different clusters and handle it manually, which leads to an increase in our operation and maintenance cost. If nacos supported incremental exports and incremental imports, our operations would be much easier. Or is there a better way of practice that you can provide for my reference? Thank you
> 
> ————————————————————————————————————————————————————————————
> 
> 我们公司的有非常高的网络安全要求，每个环境（比如开发环境，测试环境与生产环境）都会单独部署一个nacos集群，并且会有多个测试环境用于不同的测试场景。当需求进入测试阶段，需要把配置从开发环境导入到测试环境，这非常困难。当我们的代码提交给测试人员，我们需要进行CI/CD，但当我们CICD时，我们没法自动将本次新增的配置从一个nacos集群同步到另一个nacos集群。如果我们从一个nacos集群导出配置，并在另一个集群导入，这会覆盖掉我在另一个集群修改的内容（比如某项配置中的URL）。所以每当我们CICD时，都需要人工比对不同集群之间的配置，并且手工处理，这导致增加了我们的运维成本。如果nacos支持增量导出与增量导入，我们的运维工作将会轻松许多。或者有没有更好的实践方式可以提供给我作为参考，谢谢!

我理解你是想要解决不同集群之间的配置同步？  我感觉目前大部分的做法都是 开发-上线，配置两遍  ，你是们是配置很大嘛？ 手动配置很麻烦？

**Comment by zyy1161623489** [comment]
> > > Not support for now, and no plan for recent version.
> > > In my opinion, the feature is not used for most of situation. Nacos is no care for the config content and most of app and users only pay attention to the newest version config.
> > > I don't know which situation this feature need?
> > 
> > 
> > Our company has very high network security requirements, each environment (such as development environment, test environment and production environment) will deploy a nacos cluster separately, and there will be multiple test environments for different test scenarios. When the requirements enter the test phase, the configuration needs to be imported from the development environment to the test environment, which is very difficult. When we submit our code to the testers, we need to perform CI/CD, but when we CICD, we cannot automatically synchronize the newly added configuration from one nacos cluster to another nacos cluster. If we export the configuration from one nacos cluster and import it in another cluster, this overrides what I changed in the other cluster (such as the URL in a configuration). Therefore, whenever we CICD, we need to manually compare the configuration between different clusters and handle it manually, which leads to an increase in our operation and maintenance cost. If nacos supported incremental exports and incremental imports, our operations would be much easier. Or is there a better way of practice that you can provide for my reference? Thank you
> > ————————————————————————————————————————————————————————————
> > 我们公司的有非常高的网络安全要求，每个环境（比如开发环境，测试环境与生产环境）都会单独部署一个nacos集群，并且会有多个测试环境用于不同的测试场景。当需求进入测试阶段，需要把配置从开发环境导入到测试环境，这非常困难。当我们的代码提交给测试人员，我们需要进行CI/CD，但当我们CICD时，我们没法自动将本次新增的配置从一个nacos集群同步到另一个nacos集群。如果我们从一个nacos集群导出配置，并在另一个集群导入，这会覆盖掉我在另一个集群修改的内容（比如某项配置中的URL）。所以每当我们CICD时，都需要人工比对不同集群之间的配置，并且手工处理，这导致增加了我们的运维成本。如果nacos支持增量导出与增量导入，我们的运维工作将会轻松许多。或者有没有更好的实践方式可以提供给我作为参考，谢谢!
> 
> 我理解你是想要解决不同集群之间的配置同步？ 我感觉目前大部分的做法都是 开发-上线，配置两遍 ，你是们是配置很大嘛？ 手动配置很麻烦？

每次的变化倒不是很多，但是我们有8个测试环境集群，3个生产环境集群，并且有很多项目组正在使用nacos，这导致我们需要手工配置多遍，还得调整缩进，替换ip等等，还是有一定的工作量的，在程序迭代更新过程中，nacos已有的全量导出全量导入功能好像作用不大。并且如果支持增量导出导入，我们的持续集成工具和自动化部署工具可以很好地和nacos结合，可以节约很多人工维护成本。

**Comment by KomachiSion** [comment]
我理解应该只需要配置一遍，导出导入后替换ip即可，如果缩进还需要调整说明配置本身写的就有问题吧。

Nacos并不关心配置内容，认为其是黑盒内容。就算基于版本做导入导出，也是导入导出当时那个版本的全量内容，不会做内容的差量变更。

**Comment by zyy1161623489** [comment]
感谢两位的解答，我提出这个需求因为我们公司随着业务需求更新，我们的软件在迭代更新过程中，会不断增加一些需要配置的内容，会有部分参数需要配置在Nacos中（比如可以作为某个功能的开关，因为我们是一个纯后端的系统），或者可能会因为业务扩展增加新的数据源等等，或者是因为架构升级增加新的组件。总之，随着每个月度需求的变化，我们的配置变化是不可避免的，既然增量配置违背了nacos设计，那我去想想有没有其他的方案可以解决我的问题。

**Comment by zyy1161623489** [comment]
> 我理解应该只需要配置一遍，导出导入后替换ip即可，如果缩进还需要调整说明配置本身写的就有问题吧。
> 
> Nacos并不关心配置内容，认为其是黑盒内容。就算基于版本做导入导出，也是导入导出当时那个版本的全量内容，不会做内容的差量变更。

感谢两位的解答，我提出这个需求因为我们公司随着业务需求更新，我们的软件在迭代更新过程中，会不断增加一些需要配置的内容，会有部分参数需要配置在Nacos中（比如可以作为某个功能的开关，因为我们是一个纯后端的系统），或者可能会因为业务扩展增加新的数据源等等，或者是因为架构升级增加新的组件。总之，随着每个月度需求的变化，我们的配置变化是不可避免的，既然增量配置违背了nacos设计，那我去想想有没有其他的方案可以解决我的问题。

**Comment by zyy1161623489** [comment]
> 我理解应该只需要配置一遍，导出导入后替换ip即可，如果缩进还需要调整说明配置本身写的就有问题吧。
> 
> Nacos并不关心配置内容，认为其是黑盒内容。就算基于版本做导入导出，也是导入导出当时那个版本的全量内容，不会做内容的差量变更。

感谢两位的解答，我提出这个需求因为我们公司随着业务需求更新，我们的软件在迭代更新过程中，会不断增加一些需要配置的内容，会有部分参数需要配置在Nacos中（比如可以作为某个功能的开关，因为我们是一个纯后端的系统），或者可能会因为业务扩展增加新的数据源等等，或者是因为架构升级增加新的组件。总之，随着每个月度需求的变化，我们的配置变化是不可避免的，既然增量配置违背了nacos设计，那我去想想有没有其他的方案可以解决我的问题。

**Comment by KomachiSion** [comment]
我感觉可能是项目管理或者工程管理的问题，看下来应该是多个测试环境，每个人一套测试环境，然后最后发布的时候在merge各自的改动。 我认为这不是nacos应该解决的问题。

nacos解决的是维护人员/开发人员和应用之间的关系和下发，  您的问题我感觉是多人协作的时候如何合并多人的修改。

**Comment by li-xiao-shuang** [comment]
> > 我理解应该只需要配置一遍，导出导入后替换ip即可，如果缩进还需要调整说明配置本身写的就有问题吧。
> > Nacos并不关心配置内容，认为其是黑盒内容。就算基于版本做导入导出，也是导入导出当时那个版本的全量内容，不会做内容的差量变更。
> 
> 感谢两位的解答，我提出这个需求因为我们公司随着业务需求更新，我们的软件在迭代更新过程中，会不断增加一些需要配置的内容，会有部分参数需要配置在Nacos中（比如可以作为某个功能的开关，因为我们是一个纯后端的系统），或者可能会因为业务扩展增加新的数据源等等，或者是因为架构升级增加新的组件。总之，随着每个月度需求的变化，我们的配置变化是不可避免的，既然增量配置违背了nacos设计，那我去想想有没有其他的方案可以解决我的问题。

那我建议你可以基于 Naocs 的Open API监听配置 自己写一个同步小工具，8个测试集群之间相互做增量同步，提升效率

**Comment by zyy1161623489** [comment]
> 我感觉可能是项目管理或者工程管理的问题，看下来应该是多个测试环境，每个人一套测试环境，然后最后发布的时候在merge各自的改动。 我认为这不是nacos应该解决的问题。
> 
> nacos解决的是维护人员/开发人员和应用之间的关系和下发， 您的问题我感觉是多人协作的时候如何合并多人的修改。

拿我们的的研发流程举个例子，
比如我们开发**8月份**需求的时候在开发环境配置中心有两条配置
`config1=ipA:8080
config2=222222`

当我们开发完以后，需要将这个配置同步到测试环境集群1，并且修改config1的ip，
那他在测试环境1就会变成
`config1=ipB:8080
config2=222222`

当我们完成了sit和uat测试以后，会发布到生产环境，这时配置变成了
`config1=ipC:8080
config2=222222`

到了9月的时候，开发环境新增了一项配置config3=333333
此时开发环境配置变成了
`config1=ipA:8080
config2=222222
config3=333333`

将配置同步到测试环境1的时候，如果我们选择在开发环境全量导出并在测试环境全量导入，这会导致测试环境1此时的配置从
`config1=**ipB**:8080
config2=222222`
被覆盖为
`config1=**ipA**:8080
config2=222222
config3=333333`

这时需要替换config1的ipA替换成ipB，这会产生非常多的人工成本，因为实际上会有非常多的ip需要替换。
所以我们不得不选择在测试环境1中手动添加config3=333333。

但是这同样对我们来说会有非常大的成本。因为我们的开发人员只有开发环境的权限，无法修改测试环境与生产的nacos配置，
测试环境的配置由测试环境管理员负责，生产环境的配置由生产环境管理员负责，他们往往一个人负责多个项目组。这导致他们在部署我们的程序时增加了很多的手工操作。而且即便我们通过文档告诉他们需要手动增加哪些新的配置，如果我们配置中心使用的是yaml格式，他们在添加配置的时候，往往很容易因为缩进不正确或者没有放到正确的位置导致添加配置以后程序无法启动或者配置不生效导致生产问题。

这确实是我们管理制度的问题，所以我们在寻找一些技术手段来解决我们的问题，我们公司有些项目组使用apollo作为配置中心，并修改源码使得apollo不同集群之间可以增量导出和同步，这给他们的项目管理带来了很多便利，所以我才来nacos询问nacos是否支持或者是否拥有这样的计划。

**Comment by KomachiSion** [comment]
暂时没有这样的计划， 如果必须的话， 也需要和之前使用appllo一样，自行修改源码来满足需求。
