### ISSUE TITLE
Nacos多数据源通用适配改造点优化建议: 修改用户和角色的模糊查询SQL

### ISSUE THREAD

**Issue by wuchubuzai2018** [alibaba/nacos#9414]
### 背景
社区同学进行的Nacos多数据库适配的扩展代码，看到已经合并到主分支上了，为了以后多数据库适配扩展的过程中的出现的兼容问题，建议把某些代码，更改为通用的方式，进行适配。

### 修改范围
1、ExternalUserPersistServiceImpl类的方法：findUserLikeUsername
需要修改为通用的模糊查询方式
2、ExternalRolePersistServiceImpl类的方法：findRolesLikeRoleName
需要修改为通用的模糊查询方式

### 角色和用户模糊查询方法建议：
当前代码如下：
`@Override
    public List<String> findUserLikeUsername(String username) {
        String sql = "SELECT username FROM users WHERE username LIKE '%' ? '%'";
        List<String> users = this.jt.queryForList(sql, new String[] {username}, String.class);
        return users;
    }`

建议修改为：
` @Override
    public List<String> findUserLikeUsername(String username) {
        String sql = "SELECT username FROM users WHERE username LIKE ? ";
        List<String> users = this.jt.queryForList(sql,  new String[] {String.format("%%%s%%", username)}, String.class);
        return users;
    }`
这样该SQL就可以通用性的适配其他数据库未来，减少未来插件开发者的扩展插件的时候，还需要触碰主分支。

**Comment by li-xiao-shuang** [comment]
关于角色权限相关的sql 还没有进行插件化
