### ISSUE TITLE
How could i consume/use a interface from web front?

### ISSUE THREAD

**Issue by Tairr** [alibaba/nacos#942]
**Which Component**
eg. Nacos Discovery, provider,consumer

**Describe what problem you have encountered**
I want to use the provier interface that has registered at nacos from web front .

**Describe what information you have read**
By reading official eg  I learned  that i can use Fein in consumer and get the resource from
localhost:18083/echo/test (consumer url ) , 
I wander could i  get the resource  from url like  localhost:8848/service-provider/interface ( nacos url ) ? Just like use eureka .  I couldn't find info about that from Nacos-Open-Api

**Thanks for your help and contribution**

**Comment by Tairr** [comment]
@xuechaos   @nkorange  Could you give me some suggestions ？ thanks

**Comment by nkorange** [comment]
Sorry, this feature is not supported in Nacos.
