### ISSUE TITLE
配额管理问题

### ISSUE THREAD

**Issue by Sphairis** [alibaba/nacos#9421]
**Describe the bug**
1.CapacityManagementAspect开了debug没跑进去
2.aroundSyncUpdateConfigAll参数传入不太对
![1](https://user-images.githubusercontent.com/56192846/198560340-a148feee-b74f-4dc4-8747-e2953c08aab0.PNG)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
升级最新版本，问题已经有人PR过了。

**Comment by KomachiSion** [comment]
#8721

**Comment by KomachiSion** [comment]
仔细看了一下， 配额管理功能有些问题，所以社区在较早的版本里把这部分功能关掉了。

**Comment by KomachiSion** [comment]
如果有需要可以自行打开使用一下，在彻底修复之前，就不打开该功能了。
