### ISSUE TITLE
Nacos多数据源通用适配改造点优化建议: 抽取驱动类到配置文件或单独的方言实现中

### ISSUE THREAD

**Issue by wuchubuzai2018** [alibaba/nacos#9423]
###  背景
社区同学进行的Nacos多数据库适配的扩展代码，已经被管理员合并到主分支上了，为了以后多数据库适配扩展的过程中的出现的兼容问题，建议把某些代码，更改为通用的方式，进行适配。

### 当前逻辑
当前ExternalDataSourceProperties类中写死了数据库驱动类，需要进行抽取，提供读取的代码

### 建议改动
方式一：增加driver属性，到application.properties文件中进行指定
方式二：新增数据源常见方言插件增加驱动类实现方法，然后ExternalDataSourceProperties去读取

个人之前的Nacos多数据库适配过程中，采用的是方式一。某些开源BI(dataease)项目采用的是方式二。

看看管理员的意见，然后我进行提交

**Comment by KomachiSion** [comment]
其实`DataSourcePoolProperties`里是可以设置，目前的问题只有一个，就是ExternalDataSourceProperties会完全覆盖driver的配置。 我理解只要在这里判断一下DataSourcePoolProperties里是否已经配置了driver，如果没配置再用默认值覆盖即可。

当然我认为1，2也是可以的。

**Comment by wuchubuzai2018** [comment]
> 其实`DataSourcePoolProperties`里是可以设置，目前的问题只有一个，就是ExternalDataSourceProperties会完全覆盖driver的配置。 我理解只要在这里判断一下DataSourcePoolProperties里是否已经配置了driver，如果没配置再用默认值覆盖即可。
> 
> 当然我认为1，2也是可以的。

如果是用DataSourcePoolProperties类的配置，那么配置文件中应该只配置一个驱动类字符串了，同时属性和格式如下：
db.pool.config.driverClassName=com.mysql.jdbc.Driver

你的这个思路改动比较小，目前也可以，看看未来是否有其他人需要别的方式了。我先按照你的这个思路增加个判断吧，这样改动最小，配置文件也不需要新增加配置

**Comment by li-xiao-shuang** [comment]
你是想要抽取出来 可以加载其他的数据库驱动类嘛

**Comment by wuchubuzai2018** [comment]
> 你是想要抽取出来 可以加载其他的数据库驱动类嘛

对的，这个影响多数据源适配，我现在正常尝试将之前开发的Postgresql的支持和设计在2.2上搞过来，那就得提前把某些写死的判断，改成活的，要不然插件开发完了，无法引入进去

**Comment by li-xiao-shuang** [comment]
> > 你是想要抽取出来 可以加载其他的数据库驱动类嘛
> 
> 对的，这个影响多数据源适配，我现在正常尝试将之前开发的Postgresql的支持和设计在2.2上搞过来，那就得提前把某些写死的判断，改成活的，要不然插件开发完了，无法引入进去

嗯  大佬是否可以将 Postgresql 作为插件实现  提交到 https://github.com/nacos-group/nacos-plugin
