### ISSUE TITLE
Nacos 2.x版本是否有计划优化节点间请求转发和数据同步的连接池配置

### ISSUE THREAD

**Issue by onethin** [alibaba/nacos#9429]
Nacos 1.3/1.4版本一直存在一个问题是ApacheSyncHttpClientFactory中设置的节点间请求转发和数据同步的连接池的配置是当前CPU核数2倍的问题，该配置值太小，当服务接口数量多的时候，连接数完全不够用，2.x版本是否可以优化该处逻辑，比如可以将该连接池最大连接数以配置的形式提供出来

**Comment by KomachiSion** [comment]
2.x版本集群间通行使用gRPC，不再使用http，彻底解决此类问题。
