### ISSUE TITLE
Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by xiangwbs** [alibaba/nacos#9432]
我的mac版本是10.13.4，启动报错如下

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/sy/7_grpj9902d_j1zqd52qkgl40000gn/T/librocksdbjni681257998497447125.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /private/var/folders/sy/7_grpj9902d_j1zqd52qkgl40000gn/T/librocksdbjni681257998497447125.jnilib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by KomachiSion** [comment]
duplicate with #4336
