### ISSUE TITLE
naocos-client 通过api pushConfig 数据后，nacos db 有，配置文件没有

### ISSUE THREAD

**Issue by peterAndzeze** [alibaba/nacos#9435]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
I can't reproduce in newest version, please fill the issue template to describe your problem.
