### ISSUE TITLE
Load balancing based on k8s in nacos| 在nacos中基于k8s做负载均衡

### ISSUE THREAD

**Issue by Leowuqunqun** [alibaba/nacos#9438]
**Describe the bug**
我的项目是基于k8s部署服务，我希望让k8s做负载均衡，而不是nacos，因为nacos会默认注册ip，导致本地注册到开发环境联调的时候，会混乱，我知道基于spring cloud loadbalancer 可以自定义负载均衡策略，但更希望用已有方案不去重复开发

**Expected behavior**
希望可以让配置的含义更明确，可以把spring.cloud.nacos.discovery.ip 更换为 spring.cloud.nacos.discovery.host 
把名字定义成ip我都没想到可以配置service-name 
在com.alibaba.cloud.nacos.registry.NacosRegistration中
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/11615263/198971714-e4f7a92f-9582-4ca0-b24d-9f4a3a0d9ab3.png">
源码里面就是host!!

**Comment by zyy1161623489** [comment]
我也觉得这很重要，希望nacos 能够支持注册服务的时候使用svc

**Comment by Leowuqunqun** [comment]
@zyy1161623489 问题已经解决了 就是属性的定义有瑕疵 ， ip本质上是host

**Comment by KomachiSion** [comment]
Please move to Spring cloud alibaba community.
