### ISSUE TITLE
怎么设置可以跳过登录页面？

### ISSUE THREAD

**Issue by Jnoee** [alibaba/nacos#9440]
因为是个内部系统，想完全跳过登录直接进入nacos首页。

尝试了修改 conf/application.properties 文件：
spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**

spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

但都无效，始终会跳到登录页面要求登录。

**Comment by KomachiSion** [comment]
duplicate with #9440
