### ISSUE TITLE
2.1.1版本，权限控制不起作用

### ISSUE THREAD

**Issue by yaksea** [alibaba/nacos#9441]
给角色设置只读权限，但该角色的用户仍具有写配置文件的权限
![image](https://user-images.githubusercontent.com/972850/199148566-a14ae93c-b6c0-4631-8982-264b7e387342.png)
![image](https://user-images.githubusercontent.com/972850/199148596-1cb7b191-9198-41e3-9b1f-54f049ec1120.png)
![image](https://user-images.githubusercontent.com/972850/199148612-7ada1d95-db2d-4a31-8102-0e0e0fcf667d.png)
![image](https://user-images.githubusercontent.com/972850/199148633-7431e130-de5f-4e9c-a187-7e8f91c38d7c.png)

**Comment by YunWZ** [comment]
确认开启了鉴权功能：
```properties
nacos.core.auth.enabled=true
```

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
