### ISSUE TITLE
Private network can't load fonts, 2.1.2 Releases

### ISSUE THREAD

**Issue by saytesnake** [alibaba/nacos#9448]
**Describe the bug**
Have been using version 1.4.x for a long time, and yesterday I was testing the 2.1.2 release and found that the console ui had font resources that used Alibaba Cloud CDN, and of course it's not accessible in the private network. It will cost some unnecessary system resources.

**Expected behavior**
The frontend resources should use local first maybe?

**Actually behavior**
The frontend resources use the Alibaba Cloud CDN.

**Desktop (please complete the following information):**
 - OS: OpenAnolis 7.9 GA
 - Version: Nacos 2.1.2 - Releases
 - Module: Console UI

**Additional context**
https://i.alicdn.com/artascope-font/20160419204543/font/roboto-regular.woff2
https://i.alicdn.com/artascope-font/20160419204543/font/roboto-medium.woff2
https://i.alicdn.com/artascope-font/20160419204543/font/roboto-bold.woff2
http://at.alicdn.com/t/font_1533967_slipq25tezj.woff2

**Old issues**
https://github.com/alibaba/nacos/issues/1352
https://github.com/alibaba/nacos/issues/155

**Comment by onewe** [comment]
@i will resolve it@

**Comment by onewe** [comment]
@i will resolve it@
