### ISSUE TITLE
How to upgrage nacos from 1.4.2 to 2.0.3  installed through docker

### ISSUE THREAD

**Issue by mmweiyin** [alibaba/nacos#9452]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There is an installed nacos 1.4.2 through docker ,how can i upgrade it?
**Describe alternatives you've considered**

**Additional context**

**Comment by KomachiSion** [comment]
Same way as document said. 

https://nacos.io/en-us/docs/v2/upgrading/2.0.0-upgrading.html

change `替换文件` as docker replace images
