### ISSUE TITLE
nacos 配置 读取不到

### ISSUE THREAD

**Issue by universalStarBuilding** [alibaba/nacos#9457]
使用spring.config.import 的方式读取nacos中的服务配置文件，默认namespace 中的可以读取，新建的namespace读取不到配置方式如下（使用application.yml作为启动配置文件）：
server:
  port: ${SERVER_PORT:7010}
spring:
  profiles:
    active: @profiles.active@
  application:
    name: @artifactId@
  cloud:
    nacos:
      #配置中心
      config:
        #服务地址
        server-addr: @spring-cloud-nacos-server.addr@:@spring-cloud-nacos-server.port@
        namespace: 73ea1556-af5c-4bfd-a4b1-088b875f2cdd
      #注册中心
      discovery:
        enabled: true
        #注册中心地址
        server-addr: @spring-cloud-nacos-server.addr@:@spring-cloud-nacos-server.port@
  config:
    import:
      - nacos:hw-report-prod.yml

**Comment by KomachiSion** [comment]
请提供${user.home}/logs/nacos/config.log日志 或其他相关日志。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
