### ISSUE TITLE
nacos 2.1.2客户端读取公共配置文件异常(nacos 2.1.2 The client fails to read the public configuration file)

### ISSUE THREAD

**Issue by jiangjunliu** [alibaba/nacos#9458]
**Describe the bug**
使用版本为2.1.2的nacos(客户端和服务器版本一致),本地win10能够正常工作,但是当我将服务端放在AWS上运行后,出现了无法正常读取配置的问题,即使使用的服务器程序包是同一个,也失败了

With nacos of version 2.1.2 (the client and server versions are the same), native win10 works fine, but when I ran the server on AWS EC2, I had a problem of not being able to read the configuration properly

已有的排查过程The existing troubleshooting process:
1. 使用相同版本的nacos客户端和服务端在本地机器的win10系统上运行,工作正常,
2. 将该nacos服务端程序包上传至AWS EC2并启动,并开放EC2相关端口号,表现为:可以正常访问控制台网页,并能在网页上进行所有操作,通过官方文档提供的openApi进行测试,可以正常返回配置文件内容,但是此时使用本地客户端程序进行测试,无法正常读取配置
Use the nacos client and server of the same version to run on the win10 system of the local machine and work properly. Upload the nacos server program package to AWS EC2 is started and EC2-related port numbers are opened. The results show that: the console web page can be accessed normally and all operations can be carried out on the web page. The openApi provided by the official documents can be tested and the configuration can be returned normally; However, using the local client program to test at this time, the configuration cannot be read properly

配置文件详情Configuration code :
![image](https://user-images.githubusercontent.com/22563834/199697645-0f8e4164-1193-4178-a5ae-dd7089c092e4.png)

预期期望: 能够正常读取shared-configs中列出的配置文件内容
实际表现: 本地可以正常工作,但是nacos-server运行在云服务器上时,虽然可以访问控制台和openAPI,但是无论客户端是本地启动,还是在nacos-server相同的机器上启动,都无法正常读取,
The configuration file listed in shared-configs can be read normally

Actual performance: It can work properly locally, but when nacos-server runs on the cloud server, although it can access the console and openAPI, no matter whether the client is started locally or on the same machine of nacos-server, it cannot be read normally

使用的相关技术版本(Version of the relevant technology used):
cloud:
![image](https://user-images.githubusercontent.com/22563834/199689380-c3daa163-6f5a-4e89-9122-aa06565f25cb.png)
nacos client:
![image](https://user-images.githubusercontent.com/22563834/199689533-70cfd2dd-801a-42d7-a6d6-494d59d30b4b.png)
nacos server:
![image](https://user-images.githubusercontent.com/22563834/199689806-c7486dba-a4e6-4ab6-86dd-0d5c57e038b5.png)

4. 使用官方文档提供的示例程序nacos-spring-cloud-config-example对AWS 上的nacos server进行配置读取,工作正常;该程序使用的nacos-client版本为0.6.2   Nacos-spring-cloud-config-example is used to read the configuration of nacos server on AWS by using the example program Nacos-spring-config-example provided by official documents, which works properly. The program uses nacos-client version 0.6.2
示例程序的地址(The address of the sample program):
 https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example

修改后的配置文件内容为The content of the modified configuration file is as follows:

![企业微信截图_16674711882268](https://user-images.githubusercontent.com/22563834/199698081-d8e26bc7-14d5-4fc6-a880-3366120b550c.png)

**Comment by jiangjunliu** [comment]
项目启动截图   code logo:
![image](https://user-images.githubusercontent.com/22563834/199700873-1e8a6f3e-9325-4dc4-bf59-bd9fb1fed3e2.png)
![image](https://user-images.githubusercontent.com/22563834/199700988-efe5ca71-a64a-4ea4-a6b4-9bf4579101a0.png)

**Comment by jiangjunliu** [comment]
我确信云服务器的网络通信没有阻碍,因为我可以正常访问openAPI和控制台网页I am confident that the cloud server network communication is not hindered, as I can access openAPI and console web pages normally

**Comment by jiangjunliu** [comment]
Any reply will be greatly appreciated

**Comment by YunWZ** [comment]
> 项目启动截图 code logo: ![image](https://user-images.githubusercontent.com/22563834/199700873-1e8a6f3e-9325-4dc4-bf59-bd9fb1fed3e2.png) ![image](https://user-images.githubusercontent.com/22563834/199700988-efe5ca71-a64a-4ea4-a6b4-9bf4579101a0.png)

根据第一张截图：创建bean `jwtutils`时需要获取配置项 `token.secret`，但是无法解析该配置项；
你可以根据第二张截图，确认默认分组下是否有配置文件.

**Comment by jiangjunliu** [comment]
> > 项目启动截图 code logo: ![image](https://user-images.githubusercontent.com/22563834/199700873-1e8a6f3e-9325-4dc4-bf59-bd9fb1fed3e2.png) ![image](https://user-images.githubusercontent.com/22563834/199700988-efe5ca71-a64a-4ea4-a6b4-9bf4579101a0.png)
> 
> 根据第一张截图：创建bean `jwtutils`时需要获取配置项 `token.secret`，但是无法解析该配置项； 你可以根据第二张截图，确认默认分组下是否有配置文件.


谢谢你提供的思路方向,在提出这个问题之前,我确信我的配置文件 application.yml中确实包含所需要的属性,并能在本地电脑正常工作,并且服务器上的配置文件与我本地的配置文件相同
Hey,Thank you for the direction, but before I raise the question,I make sure I have the required properties in my configuration file application.yml,And can work properly on the local computer,And the configuration file on the server is the same as my local configuration file

**Comment by YunWZ** [comment]
项目启动时会打印日志--需要加载哪些配置文件（dataid，groupname，namespace），确认一下dataid是否一致，文件是否在对应的命名空间+分组下。

**Comment by jiangjunliu** [comment]
> 项目启动时会打印日志--需要加载哪些配置文件（dataid，groupname，namespace），确认一下dataid是否一致，文件是否在对应的命名空间+分组下。

谢谢你,我确信他们确实没有出错
Thank you. I'm sure they didn't make a mistake

**Comment by jiangjunliu** [comment]
此问题已使用替代方案解决: 取消使用自定义的客户端版本2.1.2  
This issue has been resolved using an alternative: cancel the use of custom client version 2.1.2

目前解决方案如下:
修改前Modify before:
![image](https://user-images.githubusercontent.com/22563834/199878777-745edd4e-7c93-4a0d-b58a-408448a33a78.png)

修改后Modify after:
![image](https://user-images.githubusercontent.com/22563834/199879196-7ae6041b-e729-4e7c-8708-49566b2ccf72.png)

去除自定义的2.1.2版本的客户端,恢复正常
The custom 2.1.2 Client dependency is deleted, and the client works properly

spring-cloud-alibaba-dependencies 和 spring-cloud-starter-alibaba-nacos-discovery 的版本 都是 2021.0.1.0

**Comment by KomachiSion** [comment]
我直接使用2.1.2客户端和服务端（不使用Spring Clouad Alibaba）进行测试没有问题，可以监听到配置。

可能是其他地方的问题导致的。

**Comment by jiangjunliu** [comment]
> 我直接使用2.1.2客户端和服务端（不使用Spring Clouad Alibaba）进行测试没有问题，可以监听到配置。
> 
> 可能是其他地方的问题导致的。

如果方便的话 请使用以下配置尝试复现一下呢:
![image](https://user-images.githubusercontent.com/22563834/199907486-c38f1011-eed3-4fe1-a22e-caff5d0f9cee.png)
![image](https://user-images.githubusercontent.com/22563834/199907521-60eb632e-bb85-4d03-8c14-c82950ef429b.png)
![image](https://user-images.githubusercontent.com/22563834/199907591-55b4803b-dc94-4ac6-b3a7-e05954039cd4.png)

**Comment by KomachiSion** [comment]
nacos-client没有问题， 如果你觉得是spring-cloud-alibaba版本导致的，麻烦提交issue到spring-cloud-alibaba社区。

**Comment by KomachiSion** [comment]
或者能够通过nacos-client来复现，并提供复现方法， 我只使用nacos-client没有复现出来

**Comment by jiangjunliu** [comment]
> nacos-client没有问题， 如果你觉得是spring-cloud-alibaba版本导致的，麻烦提交issue到spring-cloud-alibaba社区。

好的,我知道了
