### ISSUE TITLE
nacos2.0.3 内存不断升高

### ISSUE THREAD

**Issue by mltneal** [alibaba/nacos#9472]
搭了三个节点的nacos服务 ，用了好长一段时间没啥问题，但是今天配置了监控，发现：
1、配置的2g内存 ，内存不断上升到80%多，见红色部分
2、后来改成1g内存，合理很多，见黄色部分
请问这是因为什么呢，客户端使用dubbo ，nacos-cli是1.4.2
![image](https://user-images.githubusercontent.com/19965751/199939673-460ba0d8-d3ce-4b06-836f-237ac82300dd.png)

**Comment by KomachiSion** [comment]
只看图感觉很正常啊， 对内存上涨到一定程度之后触发CMSGC销毁掉一些old区里的。

调成1g之后因为cmsgc触发经常，所以看上去好一些。

**Comment by mltneal** [comment]
但是这种销毁的频率正常吗 ，这图像是一天3次Full GC了

**Comment by KomachiSion** [comment]
确定是FullGC吗？ 内存下降不一定是FullGC， CMSGC也可以清理掉old区的内存。

如果你觉得有内存泄漏问题，还需要使用你的dump文件找到是哪个内容泄漏了， 因为我这没有类似的问题。

**Comment by mltneal** [comment]
这个是mysql版本换成了 8.0.31之后的heap ，看起来是java.lang.ref.Finalizer占用的内存比较高
![9c7df873405fd0a1b58c063d40afca8](https://user-images.githubusercontent.com/19965751/200720483-9c924789-727d-4d43-9c33-57d85e19562d.png)

**Comment by KomachiSion** [comment]
那更换一下mysql的驱动版本试试，Finalizer多可能是某个依赖包的bug使用不合理导致的， nacos代码中没有用到java.lang.ref.Finalizer.

我用8.0.21的mysql驱动没有出现过这个问题。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by mltneal** [comment]
mysql换成8.0.21后还是有内存问题，这回是LaunchedURLClasssLoader
![image](https://user-images.githubusercontent.com/19965751/202350966-ce0a0726-0976-4597-9209-eb4753d2bb15.png)

**Comment by lovlyhao** [comment]
com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.Recycler$WeakOrderQueue$Head @ 0x7962528f0 占了78%
![226091599-27f36f86-97e0-4eed-af1a-4a17398a8bf7](https://user-images.githubusercontent.com/30038949/226092754-1ba44062-1a1e-4562-ad55-a64eace614be.png)

**Comment by lovlyhao** [comment]
@KomachiSion  大佬问一下， 我看nacos-cli version: 2.0.2  客户端 1天fullgc 124 ，dump 下的内存指向com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.Recycler$WeakOrderQueue$Head， 我看到有重写finalize()  这个在那个版本有修复嘛
![Snipaste_2023-03-20_10-43-55](https://user-images.githubusercontent.com/30038949/226234699-2498aefe-dcb8-48da-8754-8d62176d0289.png)
