### ISSUE TITLE
request /nacos/v1/ns/instance/list failed,servers:[25.41.20.42],code: 500,msg: caused:no ip to serve for dom

### ISSUE THREAD

**Issue by miniygq** [alibaba/nacos#9473]
request /nacos/v1/ns/instance/list failed,servers:[25.41.20.42],code: 500,msg: caused:no ip to serve for dom

![image](https://user-images.githubusercontent.com/26639875/199940955-9a03770b-ada1-4739-ab86-c8b71ad7991e.png)

**Comment by KomachiSion** [comment]
`no ip to serve for dom`

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
