### ISSUE TITLE
持久化实例的健康检查方式改为http后，部分实例显示为不健康

### ISSUE THREAD

**Issue by zz630** [alibaba/nacos#9474]
我把nacos持久化实例的默认健康检查方式，从tcp改为http。然后发现有一部分实例不健康。实际上全部实例都是健康的。
debug发现HttpClientManager.ProcessorHttpClientFactory#buildHttpClientConfig的setMaxConnTotal(-1)不生效，因为在AbstractHttpClientFactory#getConnectionManager()里
if (maxTotal > 0) {
	poolingmgr.setMaxTotal(maxTotal);
}
判断maxTotal小于0，poolingmgr默认的MaxTotal为20，导致健康检查时HttpAsyncClient从连接池里获取不到足够的连接导致超时，从而健康检查失败

I changed the default health check method of nacos persistent instance from tcp to http. Then it was found that some instances were unhealthy. Virtually all instances are healthy.
Debug found that setMaxConnTotal(-1) of HttpClientManager.ProcessorHttpClientFactory#buildHttpClientConfig does not take effect, because in AbstractHttpClientFactory#getConnectionManager()
if (maxTotal > 0) {
poolingmgr.setMaxTotal(maxTotal);
}
It is judged that maxTotal is less than 0, and the default MaxTotal of poolingmgr is 20. As a result, HttpAsyncClient cannot obtain enough connections from the connection pool during health check, resulting in timeout and failure of health check.

nacos-server 2.0.3，查看最新分支的代码有同样问题

**Comment by zz630** [comment]
修改HttpClientManager.ProcessorHttpClientFactory#buildHttpClientConfig的setMaxConnTotal(-1)改为一个较大的数字后解决

<img width="912" alt="image" src="https://user-images.githubusercontent.com/53512996/199949329-88f40181-a6e2-4a6f-a255-9f33140b6e7b.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/53512996/199949481-fb84ad0f-7830-4fc4-81eb-aa3169e9016d.png">
<img width="784" alt="image" src="https://user-images.githubusercontent.com/53512996/199949643-8607b1aa-6d5e-427c-8ed8-f0fdf3ed94df.png">

**Comment by KomachiSion** [comment]
修改为固定较大值感觉也不合理， 是不是应该修改
if (maxTotal > 0) {
poolingmgr.setMaxTotal(maxTotal);
}
这里的判断？ 让他透传就好了。再暴露一个值出去。

@Maijh97 这里有印象吗？
