### ISSUE TITLE
There is a bug in the chooser when all instances have a zero weight

### ISSUE THREAD

**Issue by RapperCL** [alibaba/nacos#9478]
当我在为这个 [PR9392](https://github.com/alibaba/nacos/pull/9392)写测试用例时 ，发现的。
当所有权重为零时，会报出下标越界异常。
为了防止混淆，我就重新提这个issue，下面是我加的测试用例。

When I was in for this [PR9392] (https://github.com/alibaba/nacos/pull/9392) write test cases, find out.
An out-of-bounds subscript exception is reported when the ownership reweight is zero.
To avoid confusion, I'll revisit the issue, and here are the test cases I added.

    
    //Test the correctness of Chooser, the weight of the final selected instance must be greater than 0
    @Test
    public void TestChooser() {
        List<Instance> hosts = getInstanceList();
        Instance target = getRandomInstance(hosts);
        assertTrue(hosts.contains(target) && target.getWeight() > 0);
    }
    
    private List<Instance> getInstanceList() {
        List<Instance> list = new ArrayList<>();
        int size = ThreadLocalRandom.current().nextInt(0, 1000);
        for (int i = 0; i < size; i++) {
            Instance instance = new Instance();
            instance.setInstanceId(String.valueOf(i));
            instance.setWeight(i);
            list.add(instance);
        }
        return list;
    }
    
    // If there is only one instance whose weight is not zero, it will be selected
    @Test
    public void TestOnlyOneInstanceWeightIsNotZero() {
        List<Instance> hosts = getOneInstanceNotZeroList();
        
        Instance target = getRandomInstance(hosts);
        assertTrue(target.getWeight() > 0);
    }
    
    private List<Instance> getOneInstanceNotZeroList() {
        List<Instance> list = new ArrayList<>();
        int size = ThreadLocalRandom.current().nextInt(0, 1000);
        int notZeroIndex = ThreadLocalRandom.current().nextInt(0, size - 1);
        
        for (int i = 0; i < size; i++) {
            Instance instance = new Instance();
            instance.setInstanceId(String.valueOf(i));
            if (i == notZeroIndex) {
                instance.setWeight(notZeroIndex + 1);
            } else {
                instance.setWeight(0);
            }
            list.add(instance);
        }
        return list;
    }
    
    // Throw an ArrayIndexOutOfBoundsException when all instances have a weight of zero.
    @Test
    public void testInstanceWeightAllZero(){
        List<Instance> hosts = getInstanceWeightAllZero();
    
        Instance target = getRandomInstance(hosts);
    }
    
    private List<Instance> getInstanceWeightAllZero(){
        List<Instance> list = new ArrayList<>();
        int size = ThreadLocalRandom.current().nextInt(0, 1000);
        
        for (int i = 0; i < size; i++) {
            Instance instance = new Instance();
            instance.setInstanceId(String.valueOf(i));
            instance.setWeight(0);
            list.add(instance);
        }
        return list;
    }
    
    private Instance getRandomInstance(List<Instance> hosts){
        List<Pair<Instance>> hostsWithWeight = new ArrayList<>();
        for (Instance host : hosts) {
            if (host.isHealthy()) {
                hostsWithWeight.add(new Pair<>(host, host.getWeight()));
            }
        }
        Chooser<String, Instance> vipChooser = new Chooser<>("www.taobao.com", hostsWithWeight);
        
        return vipChooser.randomWithWeight();
    }
}
`
第三个测试用例场景：所有实例的权重都为零时，报出了数组下标越界异常。
The third test case scenario: An array subscript out of bounds exception is reported when the weight of all instances is zero.

为了解决这个问题，我思考了一下，我认为应该要像refresh方法一样，chooser作为一个工具类，主动抛出一个异常来解决会比较合适。
In order to solve this problem, I thought about it and decided that, like the refresh method, chooser, being a utility class, would be more appropriate to actively throw an exception to resolve it.
refresh()
<img width="888" alt="image" src="https://user-images.githubusercontent.com/44110731/200101490-142eb9b1-0940-4d3d-87d5-5af9dc7bc002.png">

我的修改：
当前面都不满足时，此时数组长度肯定是为零的，于是选择主动抛出自定义异常。
My modification:
If none of the preceding branches are satisfied, the array length must be zero, and an exception is thrown.
![image](https://user-images.githubusercontent.com/44110731/200101830-b593e181-b6cf-4cdf-ae62-5793bb917815.png)

**Comment by KomachiSion** [comment]
上一个修改的PR，修改之前也会有这个问题吗？ 如果也有是否应该回滚？

**Comment by RapperCL** [comment]
> 上一个修改的PR，修改之前也会有这个问题吗？ 如果也有是否应该回滚？

有的，但是这个两个PR修改的点不同，相互之间不影响， 我认为可以将这两个pr一起合并（一个是解决bug，一个是 逻辑优化）
