### ISSUE TITLE
关于nacos namesapce的区分环境和配置/注册

### ISSUE THREAD

**Issue by xiongwu1** [alibaba/nacos#9494]
请问命名空间如果直接定义为开发环境/测试环境... 然后注册中心和配置中心的namespace都用的同一个，但是这样就会出现配置列表中出现了服务列表。如何可以做到配置列表中不要出现服务列表？

**Comment by KomachiSion** [comment]
没看懂问题。麻烦使用issue模版进行描述。

**Comment by xiongwu1** [comment]
如下图所示，如果项目中配置的config/discovery都是同一个namespace，那么在配置列表该namespace下会同时存在配置列表和注册订阅列表
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/15642586/200751966-65950101-b335-4ce2-a164-b64beb14336b.png">

**Comment by KomachiSion** [comment]
这个是dubbo定义的，nacos无能为力，dubbo需要使用nacos配置中心来保存服务元数据， 服务在哪个namespace下， dubbo就回吧元数据写到哪个namespace下。

需要到dubbo社区询问一下能否关闭这个功能。

**Comment by xiongwu1** [comment]
> 这个是dubbo定义的，nacos无能为力，dubbo需要使用nacos配置中心来保存服务元数据， 服务在哪个namespace下， dubbo就回吧元数据写到哪个namespace下。
> 
> 需要到dubbo社区询问一下能否关闭这个功能。

好的 感谢解答
