### ISSUE TITLE
nacos启动时报如下错误

### ISSUE THREAD

**Issue by lishirge** [alibaba/nacos#9495]
![1](https://user-images.githubusercontent.com/66110145/200261468-9ca45d6e-39cc-4150-8f72-ef68a17fc189.jpg)
![2](https://user-images.githubusercontent.com/66110145/200261492-a0596113-1bde-417b-b26b-f0ae8d9494c6.jpg)

**Comment by KomachiSion** [comment]
ftp protocol can't find your host `usr`. nacos community no support ftp. I think you should check your env and your custom codes.
