### ISSUE TITLE
Support Oracle datasource plugin for nacos

### ISSUE THREAD

**Issue by li-xiao-shuang** [alibaba/nacos#9498]
link to ：https://github.com/nacos-group/nacos-plugin/issues/17

**Comment by The-Gamer-01** [comment]
@i will solve it@

**Comment by Layfolk-zcy** [comment]
这插件依赖？不太懂请教下

**Comment by li-xiao-shuang** [comment]
> 这插件依赖？不太懂请教下

你有什么问题可以直接说？是哪里不太懂？

**Comment by zhouchunhai** [comment]
i want to try this issue, can you assign it to me?

**Comment by vishalsingh2972** [comment]
@li-xiao-shuang can you assign this to me if it's still open not resolved yet ?  @onewe

**Comment by onewe** [comment]
link: https://github.com/nacos-group/nacos-plugin/pull/25

**Comment by dylan-tao** [comment]
> link to ：[nacos-group/nacos-plugin#17](https://github.com/nacos-group/nacos-plugin/issues/17)

nacosplus针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
