### ISSUE TITLE
Support PostgreSQL datasource plugin for nacos 

### ISSUE THREAD

**Issue by li-xiao-shuang** [alibaba/nacos#9499]
link to : https://github.com/nacos-group/nacos-plugin/issues/16

**Comment by wuchubuzai2018** [comment]
@i will solve it@

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-plugin/pull/18

**Comment by dylan-tao** [comment]
目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb
