### ISSUE TITLE
The console supports the ini format

### ISSUE THREAD

**Issue by tietang** [alibaba/nacos#950]
## Issue Description

Type:  feature request

### Describe what happened (or what feature you want)

Can ini format be supported? and type is ini

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xuechaos** [comment]
@tietang In config module？".ini" file mean [this](https://baike.baidu.com/item/ini%E6%96%87%E4%BB%B6)?  this only works in windows? Thank you.

**Comment by tietang** [comment]
@xuechaos  yes,that is. 
Not just Windows, u can see [this](https://baike.baidu.com/item/INI/9212321) .
U know, mysql has use ini format.
Only need to support nacos console.

**Comment by tietang** [comment]
I have viewed cod of the console project，for line 576：
```
const list = [
      { value: 'text', label: 'TEXT' },
      { value: 'json', label: 'JSON' },
      { value: 'xml', label: 'XML' },
      { value: 'yaml', label: 'YAML' },
      { value: 'html', label: 'HTML' },
      { value: 'properties', label: 'Properties' },
   
    ];
```
to add one line: `   { value: 'ini', label: 'ini' },` .
