### ISSUE TITLE
咨询一下2.x版本具体哪些场景下使用了grpc通讯

### ISSUE THREAD

**Issue by onethin** [alibaba/nacos#9502]
咨询一下2.x版本具体哪些场景下使用了grpc通讯，我看了代码发现集群间转发的DistroFilter类里面，还是使用了apache httpclient通讯，这样还是会有1.x版本的因为连接池是cpu核数的两倍，数量过小的问题，代码里用了APACHE_SYNC_NACOS_REST_TEMPLATE

**Comment by KomachiSion** [comment]
1. 2.x客户端和服务端之间的通信（注册/发布，注销/删除，订阅，查询等）
2. 2.x服务端之间的频繁数据同步（distro协议，notify通知，raft同步等）

你说的这个是1.x客户端的心跳处理， 这部分保留了原本1.x的逻辑，仅为了兼容1.x客户端而保留。 因此建议升级至2.x客户端来使用，
