### ISSUE TITLE
Service list sorting problem

### ISSUE THREAD

**Issue by godhth** [alibaba/nacos#9503]
The services in the 1.4.x version service list are displayed in order, sorted by service name, as shown in the figure
1.4.x版本服务列表中的服务是有序显示的，按服务名排序，如图
<img width="1260" alt="lx_clip1667878313925" src="https://user-images.githubusercontent.com/63696328/200477337-5fc22280-d4ee-4e1e-bec9-40deba45f107.png">

However, the service list displayed in version 2.x is out of order, which makes users feel very uncomfortable.
而2.x版本中服务列表显示是无序的，让用户感到非常的不适。
<img width="1164" alt="0880c4c80710cab38508" src="https://user-images.githubusercontent.com/63696328/200477365-270d2829-d87e-40ed-b788-678e1a5f525f.png">

I want to ask is it deliberate?
我想问下是刻意而为的么？

If it needs to be changed to orderly, I can propose pr to change it.
如果需要改为有序的我可以提个pr改一下。

So far I have two options in mind
1.Sort the interface and return it.
2.Use an ordered Set in the ServiceManager, ConcurrentSkipListSet, and a Service that implements the Comparable interface. So that the insertion is ordered.

目前我想了两个方案

1.在查询接口处排序再返回。
2.在ServiceManager中使用有序Set，ConcurrentSkipListSet，并且Service实现Comparable接口。使得插入即有序。

**Comment by wuchubuzai2018** [comment]
目前看应该是2.x的实例的存储结构变化了，开发者没考虑到这点，存储目前用的是hashset，个人觉得第2种可以

**Comment by KomachiSion** [comment]
这个问题我考虑的是有必要排序吗？实际使用时，查询的时候都会使用模糊查询来缩小范围，排序所带来的收益很小。因此2.x中不再生成数据的时候进行排序。

**Comment by godhth** [comment]
> 这个问题我考虑的是有必要排序吗？实际使用时，查询的时候都会使用模糊查询来缩小范围，排序所带来的收益很小。因此2.x中不再生成数据的时候进行排序。


服务名类似的一般是相关联的应用，展示在一起会好些，不排序有点乱，个人感觉体验不好。
如果谈收益的话那确实没必要排序，但是这个是交互问题，个人体验不同，仁者见仁。
可以看看大家意见。

**Comment by KomachiSion** [comment]
我的意见是不必排序，更多的使用是通过模糊搜索缩小了范围的，甚至精确到1个服务名，排序的意义并不大， 特别是在插入的时候直接开始排序，服务多了之后排序的性能消耗较大。

如果社区觉得一定要排序，建议在查询接口返回的地方进行排序。

**Comment by KomachiSion** [comment]
There is no more response from author and community, close discussion.
