### ISSUE TITLE
分支中的1.4.2的多数据源码 打成jar后能不能直接上生产作为server进行运行

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#9509]
1.我想问下 2.0.3的版本目前只支持derby  mysql如果相同其支持Oracle的话需要自己手动扩展修改服务端源码吗

**Comment by li-xiao-shuang** [comment]
建议测试下载进行生产使用，目前 2.2.0-beta 版本正在进行多数据源兼容测试，感兴趣可以关注下新版本

**Comment by wuchubuzai2018** [comment]
> 1.我想问下 2.0.3的版本目前只支持derby mysql如果相同其支持Oracle的话需要自己手动扩展修改服务端源码吗

可以看下我的个人仓库的主页，之前基于2.1.0版本适配了一下Oracle\Postgresql\达梦啥的，可以下载源码后自己打下包

**Comment by Layfolk-zcy** [comment]
> > 1.我想问下 2.0.3的版本目前只支持derby mysql如果相同其支持Oracle的话需要自己手动扩展修改服务端源码吗
> 
> 可以看下我的个人仓库的主页，之前基于2.1.0版本适配了一下Oracle\Postgresql\达梦啥的，可以下载源码后自己打下包

源码 这边修改使用Oracle数据库后 打成jar包 可以直接作为nacos服务端使用吗

**Comment by KomachiSion** [comment]
> > > 1.我想问下 2.0.3的版本目前只支持derby mysql如果相同其支持Oracle的话需要自己手动扩展修改服务端源码吗
> > 
> > 
> > 可以看下我的个人仓库的主页，之前基于2.1.0版本适配了一下Oracle\Postgresql\达梦啥的，可以下载源码后自己打下包
> 
> 源码 这边修改使用Oracle数据库后 打成jar包 可以直接作为nacos服务端使用吗

修改源码后自行打包，在distribution下有压缩好的服务端包
