### ISSUE TITLE
咨询nacos2.0.3某些节点突然查到服务的实例数量为0的问题

### ISSUE THREAD

**Issue by zz630** [alibaba/nacos#9513]
5节点部署，2个为k8s（重启snapshot不保留），3个为物理机（重启snapshot保留），全部实例为持久化实例
遇到2个问题：
1、单个节点长时间停止，重启后会重新加载回snapshot的数据。查代码PersistentClientOperationServiceImpl#loadSnapshot里发了ClientOperationEvent.ClientRegisterServiceEvent事件然后再发ServiceEvent.ServiceChangedEvent事件，通过PushDelayTask推送给订阅者。没找到通过raft跟其他节点做数据对比的。那么这个节点会加载了已经下线的实例，并且推送给了订阅的客户端。或者跟其他节点的数据不一致？
v1/ns/upgrade/ops/metrics显示instanceCountV2是比其他节点多很多的，但persistentInstanceCountV2数量一致。

2、5个节点修改代码（健康检查相关）后都重新部署过。一段时间后，3个物理机节点突然查到服务的实例数量为0。服务列表查到前几页的服务，集群数目、实例数、健康实例数都变成0。赶紧回滚3个物理机节点问题恢复。没有排查思路。
检查过double write是关闭的，UpgradeJudgement#useGrpcFeatures已经设置为true，checkAndDowngrade方法的调用被注释了不会降级回去
<img width="857" alt="image" src="https://user-images.githubusercontent.com/53512996/200754416-c05f9880-4166-4990-8ea6-7b92163319db.png">

**Comment by KomachiSion** [comment]
1. raft会先加载快照，然后从leader处同步log并执行onApply应用日志，如果是停机很久的建议清理本地snapshot再启动，这样会从leader处拉取最新快照。该逻辑为raft协议逻辑，具体实现由Jraft实现，nacos只进行了加载快照以及apply日志的具体实现。

2. 估计是改动的代码导致了某种问题，需要您自己排查下了。

**Comment by zz630** [comment]
> * raft会先加载快照，然后从leader处同步log并执行onApply应用日志，如果是停机很久的建议清理本地snapshot再启动，这样会从leader处拉取最新快照。该逻辑为raft协议逻辑，具体实现由Jraft实现，nacos只进行了加载快照以及apply日志的具体实现。
> * 估计是改动的代码导致了某种问题，需要您自己排查下了。

感谢。
再请教一个问题，有什么情况下，打印了“Positioning inconsistency add”，但到了推送给订阅者时却是[PUSH-SUCC]DataSize=0的？
我查日志，应该读快照加载实例成功了，执行到IpPortBasedClient#putServiceInstance打印了“Positioning inconsistency add”。但推送时实例数却为0。追查代码PushExecuteTask#generatePushData——ServiceStorage#getPushData—— ServiceStorage#getAllInstancesFromIndex，感觉是AbstractClient#getInstancePublishInfo获取不到InstancePublishInfo。
但查日志“Positioning inconsistency remove”没发现有对应的service被removeServiceInstance

**Comment by KomachiSion** [comment]
Positioning inconsistency add 是哪里的日志？ 感觉是说不一致的问题啊

**Comment by zz630** [comment]
> Positioning inconsistency add

Positioning inconsistency add有两处打印，排查日志没有打印“Client change for service”，所以确定是IpPortBasedClient#putServiceInstance在加载快照时被PersistentClientOperationServiceImpl#loadSyncDataToClient调用
<img width="474" alt="image" src="https://user-images.githubusercontent.com/53512996/202378876-46209c80-f8d3-47d0-aefd-2a58740b72f5.png">

如果加载快照后，其他节点再删除实例的话会在AbstractClient#removeServiceInstance打印“Positioning inconsistency remove”。但是日志上没找到这个

**Comment by KomachiSion** [comment]
这段代码应该是您自己加的吧， 我在最新分支里没有搜到这个日志，估计还是自行修改的代码导致了某些机制出现问题了。还是得您自己排查下

**Comment by zz630** [comment]
不好意思日志是我以前加的

**Comment by zz630** [comment]
查到问题与另一个iss

**Comment by KomachiSion** [comment]
定义依赖链来保证，这个只会导致偶现的少数据，不会导致你的一直全量是0的情况。

**Comment by zz630** [comment]
在PersistentClientOperationServiceImpl加上@DependsOn("clientServiceIndexesManager")解决这个问题。
