### ISSUE TITLE
META-INF中包含了CVE的netty依赖

### ISSUE THREAD

**Issue by nonpool** [alibaba/nacos#9537]
Nacos client(目前所有已经发布的版本)
都在打包的时候在META-INF中包含了netty的依赖信息,这些信息会导致某些CVE扫描报警:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/18347300/201056645-e98b098c-c2eb-4ed2-81ec-5f47bfdaec2f.png">

META-INF文件夹中的信息:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/18347300/201057417-75eb1445-bc99-4e9d-93cb-a40906457dc8.png">

这个问题最关键的是nacos client并没有通过maven直接依赖netty,也就是说对于我们使用者而言根本没有办法从maven或者gradle中exclude 这里的netty

希望能够尽快升级或者不要在META-INF中包含这些信息(我不知道这是否是必须的)

**Comment by KomachiSion** [comment]
升级grpc版本影响较大， 不仅影响客户端/服务端之间的请求， 还影响jraft（jraft也依赖grpc）， 需要统一进行升级。

**Comment by nonpool** [comment]
还是尽量早点升级吧 包括json依赖也是

**Comment by KomachiSion** [comment]
grpc的升级pr已经提交，待合并并发版后nacos也会升级jraft版本及grpc/netty版本
https://github.com/sofastack/sofa-jraft/pull/904

**Comment by KomachiSion** [comment]
jraft已升级， 可以升级grpc了

**Comment by nonpool** [comment]
可以,效率还是挺高的,升级grpc已经有pr了不?

**Comment by KomachiSion** [comment]
Fixed by #9772
