### ISSUE TITLE
什么时候支持一下m1的nacosserver

### ISSUE THREAD

**Issue by yhjaicly** [alibaba/nacos#9540]
M1 环境下，下载最新的nacos Server启动报错
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/48404757/201145177-1083a46a-be78-48f2-8be7-9edcdd4537c1.png">

**Comment by zz630** [comment]
https://github.com/alibaba/nacos/issues/4336

**Comment by yhjaicly** [comment]
> https://github.com/alibaba/nacos/issues/4336

- 解决方式早看过了，我问的是什么时候不用转义的jdk就可以允许了，低版本的我这里也可以运行成功的

**Comment by KomachiSion** [comment]
那需要rocksdb支持，什么时候rocksdb支持了，我们再进行升级即可。
