### ISSUE TITLE
When use mysql in standalone mode, can't get the config in customize namespace

### ISSUE THREAD

**Issue by IcebergXTY** [alibaba/nacos#955]
## Issue Description
Type: *bug report*

### Describe what happened (or what feature you want)
Hi, I use mysql in nacos's standalone mode as config-center. When the config under the default namespace "public", it works well. But when I create a new namespace, the client always return "null".

### Describe what you expected to happen
return the real config data

### How to reproduce it (as minimally and precisely as possible)

1. use nacos standalone mode with mysql
2. create a new namespace like "dev"
3. create a new config in "dev"
4.use the demo code to get the config, the content is always null
```java
String serverAddr = "localhost";
String dataId = "aaa";
String group = "bbb";
Properties properties = new Properties();
 properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
 properties.put(PropertyKeyConst.NAMESPACE, "xxx");
ConfigService configService = NacosFactory.createConfigService(properties);
 String content = configService.getConfig(dataId, group, 5000);
System.out.println(content);
```

### Tell us your environment
Windows10 64bit 1809, JDK8，nacos 1.0.0-RC2（server && client）

### Anything else we need to know?
In the ConfigServletInner.java, line 157 to 161, the code is below
```java
if (STANDALONE_MODE && !PropertyUtil.isStandaloneUseMysql()) {
   configInfoBase = persistService.findConfigInfo4Tag(dataId, group, tenant, autoTag);
} else {
    file = DiskUtil.targetTagFile(dataId, group, tenant, autoTag);
 }
```
It seems like when I use mysql in standalone mode, it will never query the database, just find on the disk, but the disk has nothing....

**Comment by IcebergXTY** [comment]
#943

**Comment by IcebergXTY** [comment]
#943

**Comment by nkorange** [comment]
```properties.put(PropertyKeyConst.NAMESPACE, "xxx");``` requires namespace ID.

**Comment by IcebergXTY** [comment]
> `properties.put(PropertyKeyConst.NAMESPACE, "xxx");` requires namespace ID.

properties.put(PropertyKeyConst.NAMESPACE, "e761e406-b85e-4b2c-84b2-4e62a1c51c80");
It's the tenant_id in table tenant_info, the sql is below.
```sql
INSERT INTO `tenant_info` VALUES (1, '1', '890e1eab-722a-4cc4-b99c-8b66d390749d', 'dev', '开发环境', 'nacos', 1553312698889, 1553312698889);
INSERT INTO `tenant_info` VALUES (2, '1', 'e761e406-b85e-4b2c-84b2-4e62a1c51c80', 'test', '测试环境', 'nacos', 1553324129769, 1553324129769);
```
It's been too long...so I'm not sure whether these data was created by me or not.:joy:

**Comment by nkorange** [comment]
Reopen this issue if your problem still exists.
