### ISSUE TITLE
为啥默认server.max-http-header-size=524288

### ISSUE THREAD

**Issue by mobile664042** [alibaba/nacos#9575]
为啥这个值默认值这么大，一个请求头就占用五百多K的字节，请求量一多的话，就很容易oom了; 是不是设置为5242个字节就够用了呢。

Why this default value is so large, a request header occupies more than 500 K bytes, request a large number of words, it is easy to oom; If 5242 bytes is enough.

![image](https://user-images.githubusercontent.com/1433479/201596526-16082a00-fe49-4d32-bdc3-89b0162b71a9.png)

**Comment by KomachiSion** [comment]
1.x会存在请求转发，当服务元数据信息多的时候，header过小会出现截断，导致请求错误。需要修改大， 如果没有使用服务，或者新版本中，可以自行修改jvm参数。

**Comment by mobile664042** [comment]
> x会存在请求转发
你说是自定义扩展请求头吗？那什么情况下会导至有这么多的元数据？

**Comment by Aresxue** [comment]
@KomachiSion 目前已经迭代到2.3.0了，这个版本是否可以去掉此参数，或者将此参数进行缩小。
