### ISSUE TITLE
nacos-client 包体积为什么这么大 

### ISSUE THREAD

**Issue by catch6** [alibaba/nacos#9576]
## Issue Description

一个简单的微服务应用，单单nacos-client就占了 14.5MB，一个包基本上抵过我整个 SpringCloud 微服务项目的体积，真的有这么多的代码量吗？

### Describe what you expected to happen
希望能做好模块规划，不要什么都往里塞

**Comment by KomachiSion** [comment]
背景： grpc版本众多且兼容性较差， 为了减少用户解决冲突导致的复杂场景，将grpc版本及对应的一些容易冲突的依赖shaded到nacos-client中。

这会导致client较大，您可以选择升级到2.1.2版本，使用pure客户端，代价是冲突需要你自行解决。

https://nacos.io/zh-cn/docs/v2/guide/user/sdk.html，
