### ISSUE TITLE
浏览器100%，页面按钮不能自适应，还得缩小

### ISSUE THREAD

**Issue by WswSummer15** [alibaba/nacos#9580]
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/34562805/201882760-3407d779-e766-40a2-b2a1-cab5f684287e.png">

**Comment by WswSummer15** [comment]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/34562805/201883160-215c74af-125a-405a-bb16-5dab0d57b753.png">

**Comment by KomachiSion** [comment]
前端页面由社区进行维护， 欢迎贡献。

**Comment by KomachiSion** [comment]
另外我的浏览器无法复现，

Chrome

**Comment by KomachiSion** [comment]
#9584
