### ISSUE TITLE
nacos升级后网页管理界面没有配置导入功能

### ISSUE THREAD

**Issue by jamene** [alibaba/nacos#9584]
我们升级nacos的版本由2.0.3到2.1.2以后，发现2.1.2的网页管理界面没有配置导入的功能了，请问是怎么回事呢

**Comment by jamene** [comment]
- 
<img width="954" alt="4" src="https://user-images.githubusercontent.com/41111997/202079957-14e49d09-226a-449b-a957-2e15d6d83a44.png">

**Comment by drgnchan** [comment]
应该是浏览器宽度为不够大，按钮被隐藏了

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/40224023/202125824-cfa3d4ab-19c3-494a-aea9-122fb2767440.png">

缩小浏览器宽度后：
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/40224023/202125844-da5d9b32-6fcb-4f70-b9f7-b507927e83ad.png">

**Comment by drgnchan** [comment]
@KomachiSion please assgin to me.

**Comment by MrYuguangbao** [comment]
您的邮件已收到，我会尽快给你回复。
