### ISSUE TITLE
docker nacos-server:2.0.3 保存配置报错

### ISSUE THREAD

**Issue by beastmouth** [alibaba/nacos#9589]
对应配置信息：
version: '3'
services:
  nacos:
    hostname: 'local.xxxxx.cn'
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    env_file:
      - ./nacos/env/nacos-mysql.env
    volumes:
      - ./nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
    networks:
      - local-network
networks:
  local-network:
    external:
      name: local-network

nacos-mysql.env
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=mysql
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=password
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

对应镜像的信息：
nacos/nacos-server:2.0.3
mysql:8.0.30

项目maven依赖信息

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>2.2.7.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>2.2.7.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>3.0.7</version>
            </dependency>

问题描述：
个人学习时发现了个问题，一开始是注册dubbo服务，上报元数据报错，后来发现页面上新增nacos配置也报错。
报错的代码都在这一行
`java.lang.NullPointerException
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.lambda$updateConfigInfo$1(ExternalStoragePersistServiceImpl.java:235)`
使用arthas查看发现获取oldConfigInfo为空，导致出现了空指针
一下为查询情况的截图：
![image](https://user-images.githubusercontent.com/42804731/202183315-d015655f-fa08-4f81-8205-52f07a0812f6.png)
![image](https://user-images.githubusercontent.com/42804731/202183346-787263c3-0c04-4f3a-a3e3-eff17ed40e85.png)
对应本地客户端config.log日志
![image](https://user-images.githubusercontent.com/42804731/202185423-084ccf63-5aa1-43e0-b7b6-3c5cefd97762.png)
希望大佬可以帮忙指点一下首次添加的时候为什么回去查询旧的配置以及这个问题该如何解决，感谢

**Comment by KomachiSion** [comment]
Please use 2.1.2 version and retry.

**Comment by beastmouth** [comment]
换成高版本错误不再复现。
请问下两者的区别就是高版本的服务端会在服务注册上来时自动为服务创建一份配置数据吗？

**Comment by KomachiSion** [comment]
自动创建配置是dubbo的逻辑，nacos不会尽心关联。
