### ISSUE TITLE
使用的2.0.1版本，nacos重启后，各服务没有自动连接配置中心

### ISSUE THREAD

**Issue by zfpromise** [alibaba/nacos#9590]
使用的2.0.1版本，nacos重启后，各服务没有自动连接配置中心

1、先启动客户端服务再启动nacos服务，访问时提示
     Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
     经排查客户端服务没有自动连接配置中心，再次启动客户端服务正常

2、在K8S环境下 先重启客户端服务再重启nacos服务，重复上述1问题

**Comment by wuchubuzai2018** [comment]
好像新版本或2.1解决了

**Comment by zfpromise** [comment]
多谢！我试试

**Comment by zfpromise** [comment]
@wuchubuzai2018 服务端版本也需要替换成2.1吗？

**Comment by zfpromise** [comment]
[https://github.com/alibaba/nacos/issues/9590#issuecomment-1317956901](url)

**Comment by zfpromise** [comment]
> 

> 好像新版本或2.1解决了



> 好像新版本或2.1解决了

dadadsd

**Comment by KomachiSion** [comment]
升级客户端到2.1.2试试。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
