### ISSUE TITLE
The features to be implemented after Nacos 1.0.0

### ISSUE THREAD

**Issue by nkorange** [alibaba/nacos#960]
After several months of work, Nacos 1.0.0 is going to be released  as the one large scale production-ready version. We are glad that many companies and users are using Nacos as their running or candidate configuration center or registry center.  At meantime we are deeply grateful to all our contributors for their commits, suggestions, bug reports and other meaningful work.

Now we invite you to contribute ideas for the future of Nacos. You can reply with your most concerned features that you want Nacos to implement after Nacos 1.0.0. Please provide some backgrounds or details for your suggestion, so we can understand your idea more appropriately.

**Comment by sfk123** [comment]
可不可以做成基于DNS域名的服务发现呢，spring.cloud.nacos.discovery.ip=auth-server  这样的

**Comment by slmouse** [comment]
服务上下线可配置级别场景的通知功能(dingtalk or email)

**Comment by baobeidaodao** [comment]
Will configuration center supports privilege management and gray level publishing ?

**Comment by nkorange** [comment]
> 可不可以做成基于DNS域名的服务发现呢，spring.cloud.nacos.discovery.ip=auth-server 这样的

能不能具体描述下，我理解你这个只是把注册IP改成注册hostname？

**Comment by ankeway** [comment]
> > 可不可以做成基于DNS域名的服务发现呢，spring.cloud.nacos.discovery.ip=auth-server 这样的
> 
> 能不能具体描述下，我理解你这个只是把注册IP改成注册hostname？

like eureka 
use-dns-for-fetching-service-urls
eureka-server-d-n-s-name

**Comment by nkorange** [comment]
> Will configuration center supports privilege management and gray level publishing ?

Good suggestion, these two features are already in our roadmap. You will see them soon in our coming version.

**Comment by nkorange** [comment]
> 服务上下线 不可用时 可配置级别场景的通知功能(dingtalk or email)

理解你的意思，这块应该需要支持扩展点，接入一个通知中心

**Comment by bing086** [comment]
按命名空间划分的服务隔离还不行吗

**Comment by smartheye** [comment]
Will configuration center support discovery based on dns to support cloud foundry.

**Comment by caojiele** [comment]
能动态发布服务，服务下线，服务限流，服务负载，流量调度。

**Comment by Skqing** [comment]
作为dubbo的注册中心，配置中心和元数据中心吧。

**Comment by stanvl** [comment]
1、支持灰度发布功能：能按照客户端IP和namespace做控制
2、发布操作分离：将配置项编辑后的保存操作和发布操作分开，避免误编辑操作
3、权限控制：可以多用户管理，并可以按照namespace和data id授权
4、支持在不同namespace同步相同data id配置

**Comment by mieuf** [comment]
把配置中心和注册中心分离开，做成精简版（只支持配置中心/只支持注册中心）和全量版（配置中心和注册中心都支持）

**Comment by caojiele** [comment]
能动态发布服务，服务负载和限流，还有支持权限控制和流量调度等等。

**Comment by xsdt** [comment]
1、nacos支持ipv6的访问
2、客户端注册时可以根据配置的iptype参数选择注册的是ipv4还是ipv6，服务发现时也需要

**Comment by lzp0412** [comment]
1、配置中心支持加解密功能 类似Spring Cloud Vault
2、cmdb支持更多扩展 列如：增加可用区，大区等功能
3、名字服务支持基于就近的负载均衡

**Comment by sundong1982** [comment]
bootstrap.properties的namespace填的是id而不是名称，在开发环境比较常见的情况是一个开发团队同一套源码托管(bootstrap.properties包含namespace.id)，和每个开发人员自己创建一个nacos-server及mysql作为储存，但每个人建的namespace.id都会不同，而代码托管上是同一个namespace.id，需要大家去修改mysql的tenant_id达到统一。有更好的解决方式吗？

**Comment by shinji3887** [comment]
1、注册中心持久化方案能支持oracle
2、集成ldap和ad域，便于用户管理，同时对于配置的变更有审计

**Comment by gumutianqi** [comment]
Nacos 1.0 之后设计规范，增加插件中心和插件应用商店；
例如可以作为插件存在的模块：

> Sentinel 集成
> WebHook Notify
> DingTalk Notify
> Service Discovery Coverage Dashboard
> Load Banlance ehance rule
> ……


让社区助力 Nacos 的发展；

**Comment by nkorange** [comment]
> Nacos 1.0 之后设计规范，增加插件中心和插件应用商店；
> 例如可以作为插件存在的模块：
> 
> > Sentinel 集成
> > WebHook Notify
> > DingTalk Notify
> > Service Discovery Coverage Dashboard
> > Load Banlance ehance rule
> > ……
> 
> 让社区助力 Nacos 的发展；

非常好的提议！

**Comment by myoss** [comment]
配置的变更有审计信息

**Comment by stanvl** [comment]
support to register a instance with host name

**Comment by abcnny** [comment]
zuul动态路由的支持，貌似对Spring Cloud的事件不支持，不能自动刷新

**Comment by HashZhang** [comment]
调用权重在Spring Cloud的环境下生效

**Comment by dengzy007hi** [comment]
1.0了....mysql8支持貌似还没好？

**Comment by paderlol** [comment]
> 1.0了....mysql8支持貌似还没好？
可以看下这个PR,已经支持mysql 8了
https://github.com/alibaba/nacos/pull/855#issue-257639526

**Comment by abcnny** [comment]
加入对PostgreSQL的支持

**Comment by winnyboy** [comment]
最基本的服务注册的认证要有吧， 不是任何服务都可以注册的

**Comment by liupengpop** [comment]
Can database dependencies be removed if only service registration is used?

**Comment by stanvl** [comment]
1、nacos支持使用hostname注册服务，方便docker环境部署。
2、nacos-sync对nacos集群之间的同步似乎支持不是很好，我们想在不同的IDC，能够同步配置，支持指定namespace和dataId
3、nacos的控制台能否支持在不同namespace下同一dataId的配置同步呢，现在用namespace区分不同的环境，有一些配置项不同环境其实没差异，还得在不同namespace下分别添加

**Comment by chenshun00** [comment]
> zuul动态路由的支持，貌似对Spring Cloud的事件不支持，不能自动刷新

这个需要自己去引入一个动态刷新的过程，感觉 nacos-context 是可以解决这一块的。还有 `zuul` 会定时去获取可用的实例，通过测试发现，即使我将这个实例永久下线，还是会去请求，可以配置成，5秒请求一次，10秒请求一次，30秒请求一次，1分钟，2分钟，5分钟，10分钟，20分钟，30分钟，1个小时. 这种.

**Comment by ShuaiShuaiDa8888** [comment]
nacos1.0.0支持ipv6吗？如果支持，如何从ipv4升级到ipv6?

**Comment by chensp0668** [comment]
> > Nacos 1.0 之后设计规范，增加插件中心和插件应用商店；
> > 例如可以作为插件存在的模块：
> > > Sentinel 集成
> > > WebHook Notify
> > > DingTalk Notify
> > > Service Discovery Coverage Dashboard
> > > Load Banlance ehance rule
> > > ……
> > 
> > 
> > 让社区助力 Nacos 的发展；
> 
> 非常好的提议！

DingTalk Notify有了么？
