### ISSUE TITLE
[nacos-client] rpc communication failed by adding dependency of jsonschema2pojo

### ISSUE THREAD

**Issue by EricLoveMia** [alibaba/nacos#9600]
**Describe the bug**
     environment：springboot 2.7.5  &.  spring cloud 2021.0.4 & nacos 2.1
     when I try to add dependency jsonschema2pojo into my project,  As shown below
    
![image](https://user-images.githubusercontent.com/30768637/202601783-3226422e-bc9f-4fd4-a3a8-9933888b99a8.png)

     Exception thrown during project startup：
     com.alibaba.nacos.shaded.io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
s
     I find the reason is jsonschema2pojo has dependency com.google.android:android, when I set it exclusion as blow
     
![image](https://user-images.githubusercontent.com/30768637/202607043-73405808-92ec-4305-8791-ca9e7ecaf678.png)

       project startup success！
                        

**Expected behavior**
     I wonder if it is possible to resolve this conflict

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS:  Mac m1
 - Version nacos-server 2.1
 - Module 
 - SDK spring-cloud-starter-alibaba-nacos-config / spring-cloud-starter-alibaba-nacos-discovery

**Additional context**

**Comment by KomachiSion** [comment]
you can try to use pure client and solve conflict by yourself.

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
