### ISSUE TITLE
nacos2.x版本，同一个ip地址不能创建同一个服务的两个实例

### ISSUE THREAD

**Issue by nicheng0019** [alibaba/nacos#9601]
**Describe the bug**
nacos2.x版本，同一个ip地址创建两个实例，使用c++ sdk，分别运行两个程序，两个实例的服务名核和ip地址一样，端口号不一样，创建同一个服务的两个永久实例，第二个实例创建不久后断开。

version nacos2.x, create two instances with the same ip using c++ sdk, the two instances have the same service name and ip, but different ports, the two instances are both ephemeral, the second instance disconnect soon after being created.

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
same problem with #9492

**Comment by KomachiSion** [comment]
没看懂问题， 创建2个实例， ip和端口不一致就是独立的两个，断开和nacos应该没有关系。持久化实例健康检查不通过也不会删除，只是标记为不健康。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by nicheng0019** [comment]
> 没看懂问题， 创建2个实例， ip和端口不一致就是独立的两个，断开和nacos应该没有关系。持久化实例健康检查不通过也不会删除，只是标记为不健康。

抱歉才看到回复，谢谢您的解答，后来发现和ephemeral 设置为true还是false有关，设置为false就正常了， 设置为true的话如果两个实例ip一样，端口不一样， 其中一个服务实例就会不健康。
