### ISSUE TITLE
Nacos正常退出抛出ClosedWatchServiceException

### ISSUE THREAD

**Issue by karsonto** [alibaba/nacos#9603]
如题：

系统关闭期间ShutdownHook 触发watchService.close(),但工作线程在阻塞等待 watchService,导致抛出ClosedWatchServiceException

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/31433550/202647620-5aae8010-8e35-42de-8c6d-b552c225d9e8.png">

建议catch ClosedWatchServiceException 异常信息并吞掉

**Comment by presenth7s** [comment]
Please advise the steps to reproduce, and the relevant context, e.g. version、os
