### ISSUE TITLE
nacos-client 2.1.1读取nacos配置错误

### ISSUE THREAD

**Issue by icesugar** [alibaba/nacos#9605]
bootstrap.properties 配置开发环境密码并指定spring.profiles.active=prod
application-prod.properties 配置生产环境密码
部署到生产后 能成功注册、发布配置、订阅配置，但是服务日志报错
-----------------------------------------------------------------------------------
Bootstrap.properties configures the development environment password and specifies spring.profiles.active=prod.
Application-prod.properties configure production environment password.
After deployment to production, you can successfully register, publish and subscribe to the configuration, but the service log reports an error.

service log
```
[com.alibaba.nacos.client.Worker] c.a.n.c.a.i.process.HttpLoginProcessor   login failed: {"code":403,"message":"unknown user!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"13","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Fri, 18 Nov 2022 07:59:39 GMT","Keep-Alive":"timeout=60","Vary":"Access-Control-Request-Headers"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["13"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Fri, 18 Nov 2022 07:59:39 GMT"],"Keep-Alive":["timeout=60"],"Vary":["Access-Control-Request-Headers","Access-Control-Request-Method","Origin"]},"charset":"UTF-8"}}
```

**Desktop (please complete the following information):**
 - OS: windows
 - Version nacos-server 2.1.1, nacos-client 2.1.1
 - Module naming/config
 - SDK  spring-cloud-alibaba-nacos

**Comment by YunWZ** [comment]
这种“login failed”的日志多吗？是偶尔出现，还是经常出现？
能否提供demo项目复现该问题？

**Comment by gaspire** [comment]
我也出现了，开发环境没问题，切到生产环境就报错了，同样代码
