### ISSUE TITLE
springboot2.5.2  nacos2.1.2  只能通过@NacosPropertySource 获取配置，在application.yml配置 不生效

### ISSUE THREAD

**Issue by windforcetech** [alibaba/nacos#9611]
**Describe the bug**
springboot2.5.2  nacos2.1.2  只能通过@NacosPropertySource 获取配置，在application.yml配置 不生效

配置文件application.yml
nacos:
  config:
    server-addr: localhost:8848

启动类:
@EnableScheduling
@SpringBootApplication()
@NacosPropertySource(dataId = "client-pord.yaml",autoRefreshed = true)
public class Application {
}
此时可以读取配置，项目正常启动.

如果在application.yml 配置data-id，则不能读取配置
nacos:
  config:
    server-addr: localhost:8848
    namespace: public 
    group: DEFAULT_GROUP
    type: yaml  
    data-id: client-prod.yaml
    auto-refresh: true 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine suitable jdbc url
**Expected behavior**
请确认是否存在bug

**Comment by KomachiSion** [comment]
非bug， spring boot机制如此， 如果需要同时生效，可能需要使用spring cloud而非spring boot
