### ISSUE TITLE
ERROR Server check fail, please check server nacos.cfaoe.local ,port 10206 is available

### ISSUE THREAD

**Issue by dahai9594** [alibaba/nacos#9612]
The service error log suddenly reported nacos error, only for a period of time, and did not affect the use.

**Comment by KomachiSion** [comment]
maybe network problem or server running with some GC. Should be checked by yourself.

**Comment by dahai9594** [comment]
Could it be that there is no problem with the double write feature? Because sometimes you get errors.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
