### ISSUE TITLE
可以支持达梦数据库么，必须修改源码么

### ISSUE THREAD

**Issue by hw1992** [alibaba/nacos#9614]
担心后续漏洞等升级

**Comment by godhth** [comment]
2.2.0数据库操作是插件形式，自己可以实现一个数据源插件就行，可以不用改源码。

**Comment by hw1992** [comment]
> 

有demo么

**Comment by li-sen** [comment]
目前确实很多2+8行业都需要信创产品，数据库很多都是选型达梦，人大金仓之类的

**Comment by Layfolk-zcy** [comment]
> > 
> 
> 有demo么

同问 之前找过但是没有找到

**Comment by wuchubuzai2018** [comment]
我之前基于Nacos2.1版本，适配了下达梦(用的Oracle的实现作为基础)，感兴趣的可以看我的主页的项目

**Comment by wuchubuzai2018** [comment]
Nacos2.2版本的数据库适配插件尚不成熟，目前可以对外置的Postgresql扩展支持，达梦一般是基于Oracle适配，Nacos主分支还有一些Oracle的兼容性未处理，还有一段时间才行

**Comment by li-xiao-shuang** [comment]
> > 
> 
> 有demo么

参考主仓库中的 mysql 、derby 实现自行实现即可

**Comment by vyan** [comment]
@li-xiao-shuang 我们想提交对postgresql openGauss数据源的支持，社区接受么

**Comment by KomachiSion** [comment]
> @li-xiao-shuang 我们想提交对postgresql openGauss数据源的支持，社区接受么

pg已经有了， openGauss欢迎。

**Comment by dylan-tao** [comment]
> 担心后续漏洞等升级

nacosplus针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
