### ISSUE TITLE
Nacos Service lists cannot display services registered in other namespaces

### ISSUE THREAD

**Issue by JavaArthur** [alibaba/nacos#962]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

I used the Nacos namespace function and found that the function worked, but the Nacos console could not display the corresponding services in the corresponding namespace in the service list.

### Describe what you expected to happen

Display the corresponding service in the corresponding namespace in the service list
### How to reproduce it (as minimally and precisely as possible)

1. create a new namespace in nacos
2. used params ` -Dspring.cloud.nacos.config.namespace=yournamespace` 
3. look nacos console services list
4. You will find that they are all registered in public

### Tell us your environment
nacos 1.0.0-RC2
spring cloud Greenwich.SR1
spring boot 2.1.3.RELEASE

### Anything else we need to know?
Solve it as soon as possible, thanks!

**Comment by JavaArthur** [comment]
spring-cloud-starter-alibaba-nacos-config 0.2.1.RELEASE

**Comment by junwangit** [comment]
Is a bug, I thought it was my configuration error.

**Comment by JavaArthur** [comment]
I've already solved it, because the nacos-client version of Spring Cloud Alibaba is 0.6, too low, and the updated version is 1.0.0-RC2. Waiting for Spring Cloud Alibaba of version 0.2.2. RELEASE.
```  
 <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
      <version>0.2.1.RELEASE</version>
      <exclusions>
        <exclusion>
          <groupId>com.alibaba.nacos</groupId>
          <artifactId>nacos-client</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
      <version>1.0.0-RC2</version>
    </dependency>
```

**Comment by linzixiang199141** [comment]
yeah, we hava the same problem, now waiting for spring cloud alibaba of version 0.2.2

**Comment by zzps** [comment]
in my project, I config that register the services in develop namespace when in develop environment,but it 
aways registered into public namespace

**Comment by JavaArthur** [comment]
> in my project, I config that register the services in develop namespace when in develop environment,but it
> aways registered into public namespace

change your nacos-client ,as stated above
