### ISSUE TITLE
Nacos configService  serverStatus is always up

### ISSUE THREAD

**Issue by ruansheng8** [alibaba/nacos#9621]
**Describe the bug**

Nacos configService  serverStatus is always `up`

nacos-client version: `2.1.2`

**Expected behavior**
If nacos server is down , configService.serverStatus should be change to `DOWN`

**Actually behavior**
Even if you shut down the nacos service , nacos configService status is still `UP`

**How to Reproduce**
nacos-client: `2.1.2`
See demo: 
```
    public static void main(String[] args) throws NacosException {
        // nacos is not startup 
        ConfigService configService = NacosFactory.createConfigService("127.0.0.1:8848");
        String config = configService.getConfig("test.yml", "DEFAULT", 1000);
        String serverStatus = configService.getServerStatus();
        // serverStatus is always 'UP' even if the nacos service is stopped
        System.out.println(serverStatus);
    }
```

**Additional context**
In `ClientWorker.java` ,  i found method `setHealthServer` is nerver used .
If this is a bug , i will submit a PR to solve it.
![image](https://user-images.githubusercontent.com/24709538/203237362-b851f7bd-bd39-49a6-a3d7-5fd5ea427c5d.png)

**Comment by YunWZ** [comment]
@i will resolve it@
