### ISSUE TITLE
Nacos pull config failure did not throw an exception

### ISSUE THREAD

**Issue by ruansheng8** [alibaba/nacos#9626]
**Describe the bug**

nacos-client version: `2.1.2`

When I turn off the nacos server and clear nacos local snapshot files , now i use `ConfigService#getConfig` of `Nacos JavaSDK` to pull nacos server remote config , it not as described in the [Nacos Document](https://nacos.io/zh-cn/docs/v2/guide/user/sdk.html)
![image](https://user-images.githubusercontent.com/24709538/203462548-6ad99237-0cae-4a9a-8644-8a6e54cb4078.png)

**Expected behavior**
When nacos server is `stopeed` and has `no snapshot file` in local, pull nacos config should throw an `NacosException`

**Actually behavior**
It will return `null` , maybe it should be add an errorCode of `-401` ?

![image](https://user-images.githubusercontent.com/24709538/203462102-39546312-f698-4fe2-a3f4-5d626675aba8.png)
![image](https://user-images.githubusercontent.com/24709538/203463750-241d34a1-c90a-4bff-8cd5-a6678a41d6cb.png)

**How to Reproduce**

See demo
```
    public static void main(String[] args) throws Exception {
        ConfigService configService = NacosFactory.createConfigService("127.0.0.1:8848");
        String result = configService.getConfig("test.yml", "DEFAULT_GROUP", 5000);
        // nacos server is stopped , but result is null , it should be throw an `NacosException` 
        System.out.println(result);
    }

```

**Comment by karsonto** [comment]
i will resolve it after discuss

**Comment by shiyiyue1102** [comment]
It should not throw exception where connection fail , when server down, it should read content from local snapshot.

**Comment by ruansheng8** [comment]
> It should not throw exception where connection fail , when server down, it should read content from local snapshot.

在catch异常的时候 判断如果是`客户端无法连接`的异常 , 先标记异常编码 , 然后继续走下面的获取本地快照配置 , 如果本地快照配置也不存在 , 再继续判断前面标记过的异常 , 如果存在则抛出异常 , 这个逻辑是否行得通

**Comment by KomachiSion** [comment]
如果本地存在配置应该读本地配置， 如果本地不存在再抛出异常应该才合理，毕竟本地缓存文件就是用来容灾的。

**Comment by KomachiSion** [comment]
There is no more response from author and community, close discussion.
