### ISSUE TITLE
@NacosPropertySource 注解参数配置

### ISSUE THREAD

**Issue by tiancaipei** [alibaba/nacos#9628]
配置中心的groupId是用来区分不同环境的配置，使用xml来配置时，可以放在对应的环境下写死配置，现在想通过注解的方式来配置nacos配置中心，如何在注解上区分不同环境？
![image](https://user-images.githubusercontent.com/41528403/203493505-5b71f312-9eed-488d-8602-9ac07cd3a210.png)
![lQLPJxbmRwuwbmzNAT7NBxqwhrj4j6EoRooDelpeeAD0AA_1818_318](https://user-images.githubusercontent.com/41528403/203493441-0d817adc-4383-4ce3-bebc-2793bdcc0da8.png)

**Comment by hujun-w-2** [comment]
这种情况可以使用spring的条件注入

**Comment by tiancaipei** [comment]
已解决
