### ISSUE TITLE
【NACOS2.1.0-BETA】 偶尔会出现编辑配置后无法动态刷新到服务里，需要点击多次发布

### ISSUE THREAD

**Issue by UltramanNoa** [alibaba/nacos#9629]
nacos-client version: NACOS2.1.0-BETA

<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
	<version>2021.0.4.0</version>
</dependency>

偶尔会出现编辑配置后无法动态刷新到服务里，需要点击多次发布

**Comment by KomachiSion** [comment]
更新新版本客户端试试， 同时看下${user.home}/logs/nacos/config.log 日志

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
