### ISSUE TITLE
发布新配置无法获取到新配置

### ISSUE THREAD

**Issue by poisonduyao** [alibaba/nacos#9630]
spring boot 2.5.14
nacos客户端 0.2.12
nacos 服务器端 NACOS 2.2.0-BETA
出现问题：springboot单体中 nacos重新发布配置后，客户端不能更新配置，就算重启服务也获取得老配置信息

**Comment by karsonto** [comment]
会不会是网络问题，导致获取了客户端本地文件保存的配置？

**Comment by KomachiSion** [comment]
提供一下${user.home}/logs/nacos/config.log

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
