### ISSUE TITLE
@NacosValue 无法动态获取值

### ISSUE THREAD

**Issue by Cherry-Ran** [alibaba/nacos#9638]
我在nacos控制台修改了str1的值，然后Java代码中无法动态获取str1的值，@NacosValue(value="${str1}",autoRefreshed = true)

**Comment by RongXiong2016** [comment]
可以提供下能复现的代码？

**Comment by KomachiSion** [comment]
建议先使用sample代码测试一下。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
