### ISSUE TITLE
Nacos 2.1.2，OpenAPI v2 API is not working

### ISSUE THREAD

**Issue by shixinyu** [alibaba/nacos#9644]
## Issue Description

Based on Documents, [Open-API](https://nacos.io/zh-cn/docs/v2/guide/user/open-api.html), these V2 API should be work for 2.1.2 version, but I tried and just v1 API is working, v2 API is not working. Just tried any v2 API just return 404, and v1 API return 200 successful.
基于[Open-API](https://nacos.io/zh-cn/docs/v2/guide/user/open-api.html)文档，这些v2API在2.1.2版本下应该是工作的，但是我尝试过，只有v1的API是可用的，v2的API都不可用。任何v2 API请求返回的都是404，而v1接口则是200成功。

### Tell us your environment
Rocky 8, Corretto JDK 8, Nacos 2.1.2

**Comment by lyf712** [comment]
你好，请检查一下请求路径；（请问是naming的请求吗？文档这儿应该写错了(instance)；
![image](https://user-images.githubusercontent.com/62736461/204529355-e7c2b26f-f554-44ef-bb31-42e0415572ea.png)

**Comment by shixinyu** [comment]
![image](https://user-images.githubusercontent.com/6237141/204534400-9e0c9a1a-ce43-4c24-88ce-323c33fb45b3.png)

多谢，测试的是这个接口，返回404。同样功能的v1接口则正常返回，如下图：
Thx, I tried above API service and return 404. Same function with v1 API service and works, as below:
![image](https://user-images.githubusercontent.com/6237141/204542638-b9224240-b7f0-4a05-bbdb-8fa3de66f1e2.png)

![image](https://user-images.githubusercontent.com/6237141/204543070-f47ff800-552f-462c-ad7c-25cea5d89765.png)

**Comment by lyf712** [comment]
V2版本换成 config了 
![image](https://user-images.githubusercontent.com/62736461/204546607-f618a005-11dc-4401-aa66-903dad65d610.png)

**Comment by shixinyu** [comment]
抱歉，未截图config接口的请求，也是404：
![image](https://user-images.githubusercontent.com/6237141/204551956-05cddb35-188c-4b74-8dc7-7bfc03ea7ab9.png)
另外还测试了两个接口也是404，就好像v2这个路由都不存在：
![image](https://user-images.githubusercontent.com/6237141/204552291-14b44bac-f7af-4c17-aae8-bb859a968945.png)

**Comment by KomachiSion** [comment]
应该是文档没有写明， v2的openAPI是在2.2.0-BETA版本才加入了。
