### ISSUE TITLE
2.2.0分支nacos-datasource-plugin个别分页查询无starRow、pageSize参数

### ISSUE THREAD

**Issue by zhangdp** [alibaba/nacos#9645]
没有传入starRow、pageSize参数，而是使用了预编译占位符，在mysql中的分页"limit startRow, pageSize"改成postgresql后语法为"limit ? offset ?"，按照预编译占位符的顺序最终结果将变成"limit startRow offset pageSize"，实际上应"limit pageSize offset startRow"才对。比如ConfigInfoMapper.getTenantIdList()方法。

**Comment by li-xiao-shuang** [comment]
欢迎提交pr处理

**Comment by wuchubuzai2018** [comment]
> 没有传入starRow、pageSize参数，而是使用了预编译占位符，在mysql中的分页"limit startRow, pageSize"改成postgresql后语法为"limit ? offset ?"，按照预编译占位符的顺序最终结果将变成"limit startRow offset pageSize"，实际上应"limit pageSize offset startRow"才对。比如ConfigInfoMapper.getTenantIdList()方法。

个人觉得问题不大，这种情况应该修改postgresql的SQL实现为 offset startRow limit pageSize，我之前自己开发的Postgresql的实现中，就是在方言中用这种方式去控制的。postgresql支持这种写法。
例如在我的postgresql是这么设计的：
@Override
    public String getLimitPageSql(String sql) {
        return sql + "  OFFSET ? LIMIT ? ";
    }

**Comment by 985492783** [comment]
> 欢迎提交pr处理

这如果要改，得在plugin/datasource里面单独对postgresql做一个适配吧

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-plugin/pull/18
