### ISSUE TITLE
2.2.0分支nacos-datasource-plugin的com.alibaba.nacos.config.server.service.repository.embedded.EmbeddedStoragePersistServiceImpl的batchRemoveAggr方法未使用预编译有sql注入风险

### ISSUE THREAD

**Issue by zhangdp** [alibaba/nacos#9646]
List<String> datumList未使用预编译占位符而是使用字符串直接拼接的方式有sql注入的风险，且代码冗余创建的datumString无任何使用。
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/26567414/204692311-15fde246-c1e6-4e98-80c7-5a44e41fdae8.png">
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/26567414/204692916-c412ed56-7308-4643-9ddd-2f2640a4739a.png">

**Comment by li-xiao-shuang** [comment]
欢迎提交pr处理

**Comment by wenxuan70** [comment]
@i will solve it@
