### ISSUE TITLE
找不到v2接口，有人看一下么

### ISSUE THREAD

**Issue by licheng1013** [alibaba/nacos#9647]
**Describe the bug**
找不到v2接口，有人看一下么。。
![image](https://user-images.githubusercontent.com/46236080/204702954-ad4d3ee4-0885-4159-9f02-1cd670fcb074.png)

**Comment by rookie-ricardo** [comment]
下载源码看一下呢？或者参看官方文档的路径

**Comment by licheng1013** [comment]
> 下载源码看一下呢？或者参看官方文档的路径

![image](https://user-images.githubusercontent.com/46236080/205071162-6eefc63b-c111-4ec3-a142-231f39650ec7.png)
请问你说的路径是这个吗？

**Comment by licheng1013** [comment]
> 

我请求的就是这个路径。。这是文档没更新吗。。。。

**Comment by licheng1013** [comment]
> > > 下载源码看一下呢？或者参看官方文档的路径
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/46236080/205071162-6eefc63b-c111-4ec3-a142-231f39650ec7.png) 请问你说的路径是这个吗？
> 
> 是的 你可以注意到文档里的接口是有v1和v2的分别的，你也可以直接在github去找。

我请求的就是这个路径。。这是文档没更新吗。。。。

**Comment by rookie-ricardo** [comment]
> > > > 下载源码看一下呢？或者参看官方文档的路径
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/46236080/205071162-6eefc63b-c111-4ec3-a142-231f39650ec7.png) 请问你说的路径是这个吗？
> > 
> > 
> > 是的 你可以注意到文档里的接口是有v1和v2的分别的，你也可以直接在github去找。
> 
> 我请求的就是这个路径。。这是文档没更新吗。。。。

你可以具体看你一下你那个版本的路径，去源码里面看吧，一般不会出现文档不更新的情况，都是新接口替换老接口，老接口依然能用。
我建议你登陆控制台，点点创建配置之类的按钮，通过控制台查看相关的路径，将其前缀复制到你这里。

**Comment by licheng1013** [comment]
> > > > > 下载源码看一下呢？或者参看官方文档的路径
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/46236080/205071162-6eefc63b-c111-4ec3-a142-231f39650ec7.png) 请问你说的路径是这个吗？
> > > 
> > > 
> > > 是的 你可以注意到文档里的接口是有v1和v2的分别的，你也可以直接在github去找。
> > 
> > 
> > 我请求的就是这个路径。。这是文档没更新吗。。。。
> 
> 你可以具体看你一下你那个版本的路径，去源码里面看吧，一般不会出现文档不更新的情况，都是新接口替换老接口，老接口依然能用。 我建议你登陆控制台，点点创建配置之类的按钮，通过控制台查看相关的路径，将其前缀复制到你这里。

Ok，后面我试试吧。
