### ISSUE TITLE
findConfigInfoLike4PageCountRows方法传入参数有误

### ISSUE THREAD

**Issue by 985492783** [alibaba/nacos#9648]
### 这个是个bug吧，传入的参数是所有的参数个数，但是接口需要传入的参数是tagList.size()，导致报错

![image](https://user-images.githubusercontent.com/73023513/204721120-c573c86e-8374-4d92-83ef-9c50246b8f7d.png)
![image](https://user-images.githubusercontent.com/73023513/204722210-9ba893ab-1a47-4661-a0f6-b9bce50606d6.png)
![image](https://user-images.githubusercontent.com/73023513/204722131-7629f96f-c07c-4d29-a9d3-d8daf50823f2.png)

**Comment by 985492783** [comment]
如果是一个bug我可以提PR修复

**Comment by li-xiao-shuang** [comment]
> 如果是一个bug我可以提PR修复

看起来是有问题的 ，欢迎提交pr
