### ISSUE TITLE
K8s deployment, registration center report 400

### ISSUE THREAD

**Issue by rhce123** [alibaba/nacos#965]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. curl -X PUT 'http://127.0.0.1:30001/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'

ErrCode:400,ErrMsg:service not found, namespace: public, service: DEFAULT_GROUP@@nacos.naming.serviceName

**Comment by nkorange** [comment]
Use POST instead of PUT please.

**Comment by rhce123** [comment]
version：nacos-k8s,1.0.0-rc1
curl -X POST 'http://127.0.0.1:30001/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'  
Same error：
ErrCode:400,ErrMsg:service not found, namespace: public, service: DEFAULT_GROUP@@nacos.naming.serviceName

**Comment by nkorange** [comment]
You have to upgrade to 1.0.0-RC2.

**Comment by rhce123** [comment]
ok，thx

**Comment by rhce123** [comment]
Update to 1.0.0-RC2. There is no problem. thx.

**Comment by paderlol** [comment]
目前没有1.0.0-RC2 docker镜像

**Comment by rhce123** [comment]
Download nacos-k8s version is 0.9.0, not 1.0.0-rc2, return to 0.9.0nacos cluster registration is normal

**Comment by paderlol** [comment]
i will upgrade the docker image later
