### ISSUE TITLE
nacos 2.1.2 deployed in k8s cluster mode popup error msg  "server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]" when click "service list" button in web console

### ISSUE THREAD

**Issue by winer632** [alibaba/nacos#9656]
**Describe the bug**
docker image is from docker hub  nacos/nacos-server:v2.1.2
Image ID:       docker-pullable://nacos/nacos-server@sha256:149ef53f4cef5bf204cd9175a4bb20b701941d40e1c491506a5cef49ccfe078e

nacos is deployed in k8s cluster mode , see picture below

in web console when click "service list" button, we can see 503 error, error msg is 
"server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]"

![411669907512_ pic](https://user-images.githubusercontent.com/4931801/205088679-3d2acbce-2494-4e57-928b-95ac84a4c9cf.jpg)

![WXWorkCapture_16698935843336](https://user-images.githubusercontent.com/4931801/205088819-ea854e81-edfb-4fbb-93da-4cd580f5d165.png)

<img width="2188" alt="企业微信截图_f872013b-8705-4a21-abf8-d82badb32c42" src="https://user-images.githubusercontent.com/4931801/205073755-1f7acad7-3711-453d-a0a4-3290d9734fb6.png">
<img width="2188" alt="企业微信截图_2640a4c3-7689-44fe-ba7f-f81f1fd5ab45" src="https://user-images.githubusercontent.com/4931801/205073800-5099f156-18d8-47c4-82ee-31c5a323dafa.png">

protocol-distro.log keep printing "INFO [DISTRO-INIT] waiting server list init..." for more than 3 hours 
what ip port does nacos 2.1.2 use to init server list ? what should I check ?
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/4931801/205073682-cdf9e076-477c-4cfe-afce-dae38d2f7be6.png">

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Version  nacos-server 2.1.2, nacos-client 2.1.2
 - Module naming
 - SDK 

**Additional context**
![341669904833_ pic](https://user-images.githubusercontent.com/4931801/205078090-ae22a91c-4aa7-405c-b0fc-8073a81c8203.jpg)

<img width="1620" alt="image" src="https://user-images.githubusercontent.com/4931801/205075539-d2a65dc5-0d25-4580-ad86-97947dbb138e.png">

![371669905614_ pic](https://user-images.githubusercontent.com/4931801/205081630-748419f5-3794-4d8e-b218-cdd63304e4ca.jpg)

![351669904883_ pic_hd](https://user-images.githubusercontent.com/4931801/205078308-ee933e60-7573-4716-a21d-9c00a4538127.jpg)

<img width="563" alt="image" src="https://user-images.githubusercontent.com/4931801/205078632-e8f7efb2-a431-481a-b297-edd9e2479704.png">

![381669905702_ pic](https://user-images.githubusercontent.com/4931801/205081466-7073f5bf-0746-49c7-9b0f-f78ea28fe25c.jpg)

**Comment by winer632** [comment]
维护nacos的同事方便的话可以加我微信，我提供远程桌面定位问题
![391669907162](https://user-images.githubusercontent.com/4931801/205089417-5ed76159-656c-4c7f-bf35-e18751d2ff41.jpg)

**Comment by winer632** [comment]
![421669908947_ pic](https://user-images.githubusercontent.com/4931801/205094498-40e52004-48bf-4c07-972d-4f1fbfc381b1.jpg)

下面这两个接口在 https://nacos.io/zh-cn/docs/open-api.html 官方API文档没有查到，都是503错误 『server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]』

http://si-nacos.sensetime.com/nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=10&serviceNameParam=&groupNameParam=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY2ODQ1MzY3M30.bEoqpeMfgxQfoYDpMgF7WLVNfQmvdlsiWwBlZtuKWiY&namespaceId=

http://si-nacos.sensetime.com/nacos/v1/ns/service/subscribers?serviceName=web-mgt&groupName=&pageSize=10&pageNo=1&namespaceId=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY2ODQ1MzY3M30.bEoqpeMfgxQfoYDpMgF7WLVNfQmvdlsiWwBlZtuKWiY&username=nacos

**Comment by KomachiSion** [comment]
集群搭建有问题， 找不到其他节点，看下cluster.conf文件以及nacos-cluster.log日志，member是不是没有。

或者集群管理页面里是不是全是down的。

**Comment by KomachiSion** [comment]
空白说明集群模式但是没有指定其他节点，可找不到快照加载集群启动未完成报错很正常。

**Comment by hillbun** [comment]
那如何解决？  2.1.1 版本是正常的

**Comment by KomachiSion** [comment]
参考部署文档，配置cluster.conf

**Comment by hillbun** [comment]
我用的是 nacos/nacos-server:v2.1.2 这个镜像，启动后 cluster.conf 内容是空的

用 nacos/nacos-server:v2.1.1 这个镜像的话，启动后  cluster.conf 内容是正常的

#2022-12-13T17:19:36.651
nacos-0.nacos-hs.default.svc.cluster.local:8848
nacos-1.nacos-hs.default.svc.cluster.local:8848
nacos-2.nacos-hs.default.svc.cluster.local:8848

**Comment by winer632** [comment]
更新一下，实在搞不定v2.1.2，上周换成v2.1.1了。目前v2.1.1是正常的

**Comment by hillbun** [comment]
@winer632   你也是用DOCKER版本的吗

**Comment by paderlol** [comment]
嗯 确实有问题,给大家带来不便十分抱歉, 因为一个PR导致了k8s helm部署直接没有了动态扩缩容能力，必须写死NACOS_SERVER, 目前确定受到影响的只有v2.1.2这一个镜像.
解决方案:
1. 直接升级成为v2.2.0的镜像
2. 重新拉取v2.1.2镜像(重新修复的版本)

**Comment by jumping** [comment]
k8s用阿里云ack pro版本，换工作节点后，nacos（2.1.2）出现 server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]这样的错误。按照https://github.com/alibaba/nacos/issues/9656，重新拉过镜像，也还存在这样的错误。
