### ISSUE TITLE
Why use timestamps instead of version Numbers for data consistency synchronization between nodes

### ISSUE THREAD

**Issue by zhuyuehui** [alibaba/nacos#966]
## Issue Description

Using timestamps for comparison can be problematic
### How to reproduce it (as minimally and precisely as possible)

how about using version number to compare？

**Comment by nkorange** [comment]
Can you paste some code of 'timestamp' please? Nacos actually uses version instead timestamp.

**Comment by zhuyuehui** [comment]
@nkorange 
``
receivedKeysMap.put(datumKey, 1);

                try {
                    if (datums.containsKey(datumKey) && datums.get(datumKey).timestamp.get() >= timestamp && processedCount < beatDatums.size()) {
                        continue;
                    }

                    if (!(datums.containsKey(datumKey) && datums.get(datumKey).timestamp.get() >= timestamp)) {
                        batch.add(datumKey);
                    }

                    if (batch.size() < 50 && processedCount < beatDatums.size()) {
                        continue;
                    }

                    String keys = StringUtils.join(batch, ",");

                    if (batch.size() <= 0) {
                        continue;
                    }
``
 
``
 if (!switchDomain.isSendBeatOnly()) {
                for (Datum datum : datums.values()) {

                    JSONObject element = new JSONObject();

                    if (KeyBuilder.matchServiceMetaKey(datum.key)) {
                        element.put("key", KeyBuilder.briefServiceMetaKey(datum.key));
                    } else if (KeyBuilder.matchInstanceListKey(datum.key)) {
                        element.put("key", KeyBuilder.briefInstanceListkey(datum.key));
                    }
                    element.put("timestamp", datum.timestamp);

                    array.add(element);
                }
            }
``

this is reciveBeat and sendBeat

**Comment by nkorange** [comment]
The timestamp here is actually a version number. When data changed, this timestamp increases itself by one.

**Comment by zhuyuehui** [comment]
oh , I see,ths

**Comment by zhuyuehui** [comment]
But another question is, if receiveBeat needs to synchronize the latest data in batches, every 200ms interval, will sendBeats execute during this period？

**Comment by nkorange** [comment]
It's OK if they executed concurrently. The data can be eventually consistent.

**Comment by zhuyuehui** [comment]
When update dataum entry,Stop the beat, won't it be better？

**Comment by nkorange** [comment]
I understand your concern, SendBeat is used to compensate data for nodes which didn't receive data in a normal raft publish. It's necessary and important.
