### ISSUE TITLE
订阅者列表会存在脏数据

### ISSUE THREAD

**Issue by a1156698162** [alibaba/nacos#9666]
**Describe the bug**
版本1.4.2
OS：win10
我之启动了两个应用，一个comsumer，一个provider。点击provider的订阅者列表时会出现脏数据
![image](https://user-images.githubusercontent.com/72338463/205634012-2c5e99aa-5f6d-4001-9122-9549f4c66dc9.png)
![image](https://user-images.githubusercontent.com/72338463/205634101-632c47d5-a105-48e0-b50b-e5dfdd5072c6.png)
出现这种原因是因为在这之前我启动过一个名字为provider1的应用，但是已经停掉了。在debug过程成中发现clientMap中并没有移除下线的服务
![image](https://user-images.githubusercontent.com/72338463/205635009-0b10b1aa-4357-4be3-a055-3f674d45f421.png)
![image](https://user-images.githubusercontent.com/72338463/205635094-2c26afbb-f9ae-496b-9d2c-5d98d6c1df4d.png)
并且provider.indexOf(provider1)>=0成立
例如
![image](https://user-images.githubusercontent.com/72338463/205636109-a2b4549b-c01c-4b51-9008-a976795c20cb.png)
所以会往clients中加入脏数据

**Expected behavior**
当服务下线后clientMap中的数据会刷新

**Additional context**
请问这是bug吗？

**Comment by xiangtianyu** [comment]
我也遇到了这个问题，这是版本问题还是设计如此？

**Comment by a1156698162** [comment]
![image](https://user-images.githubusercontent.com/72338463/205869773-779311ca-6bc4-4a0d-aa8e-0ef706bf9e21.png)
![image](https://user-images.githubusercontent.com/72338463/205869831-fdb3d0bd-d81c-41cb-a5c2-96bc8ed14420.png)
还是存在脏数据问题

**Comment by a1156698162** [comment]
> 升级到1.4.4版本试试？

可以看到脏数据的问题依然存在

**Comment by xiangtianyu** [comment]
@KomachiSion 请问下目前这个有结论了吗？

**Comment by KomachiSion** [comment]
1.X中有一个clean zombie client的逻辑，应该在PushService里，可以看一下是不是没有触发zombie client的判断，或者还有查询请求在续约。

**Comment by a1156698162** [comment]
@KomachiSion 我跟了以下源码，确实调用了清理僵尸客户端的方法，但是在清理条件成立的情况下并没有清理掉僵尸客户端。而且我还有一个新的疑问
![image](https://user-images.githubusercontent.com/72338463/206971910-caa343c7-fe6f-4dbf-b891-7235b4598802.png)
为什么同样的ip和port可以代表不同的客户端？
我的测试就使用了一个provider和一个consumer服务。
您可以在本地复现一下问题先先启动服务consumer和provider1。查看订阅者列表信息。然后将provider1服务停掉改名为provider在启动服务。然后在查看订阅者列表。你就会发现脏数据了。
以外我使用的consumer和provider代码是nacos上给的样例源码。
![image](https://user-images.githubusercontent.com/72338463/206972540-4289e6c9-0631-4728-a4d8-1a80962c563f.png)

**Comment by a1156698162** [comment]
@KomachiSion 此外，我上面说的调用了清理方法，但是却没清理掉。我也很纳闷。下面是debug情况。
![image](https://user-images.githubusercontent.com/72338463/206973785-bcd19e76-fcd0-4f47-8d0d-acc044166930.png)
![image](https://user-images.githubusercontent.com/72338463/206973812-6cb40169-4cab-435d-b80d-5ea2b907c7bd.png)
![image](https://user-images.githubusercontent.com/72338463/206973824-e23e0d1b-40da-4c68-90e9-790be3542653.png)
图中可以看到时间。
确实clientConcurrentMap的size在移除后减少了1，但是在第三幅图中又size又莫名变成了2

**Comment by KomachiSion** [comment]
那就说明还有请求在发送， 导致client又被注册上了， 抓包查一下吧。

**Comment by a1156698162** [comment]
@KomachiSion  经过一系列的排查，最终发现了问题所在。
服务在server端下线并不会立马被移除。此时依旧会将还没检测到下线的服务信息发送给所有client端。因为client端会调用以下方法从server获取数据。
![image](https://user-images.githubusercontent.com/72338463/207222503-6616859b-864e-48dc-ac7a-26ca5ccf2deb.png)
![image](https://user-images.githubusercontent.com/72338463/207222536-666f7efb-13da-402e-9284-764e33b7c728.png)
![image](https://user-images.githubusercontent.com/72338463/207222574-da8c01a6-e4a5-46c3-b1b5-8004c4daf41a.png)
此时获取的数据中就包含已经下线但未被及时检测的服务信息。
client会向server端
![image](https://user-images.githubusercontent.com/72338463/207223178-f17e422e-d8b1-4895-9d0c-c6f5f6bb847c.png)
最终client端会调用queryList往server端发送请求
![image](https://user-images.githubusercontent.com/72338463/207225914-a1c681dd-0aa5-4139-ab43-29a15b96061f.png)
server端在处理请求时调用doSrvIpxt方法
![image](https://user-images.githubusercontent.com/72338463/207226028-ab9df81c-52ca-467c-ae82-b6b1ab68ec2d.png)
![image](https://user-images.githubusercontent.com/72338463/207226101-24c24751-c757-4a5d-9c43-bdb040b38065.png)
![image](https://user-images.githubusercontent.com/72338463/207226124-3a32b6d7-2048-4c89-adf6-6ea58df7c97d.png)
问题就在new PushClient(...)中
![image](https://user-images.githubusercontent.com/72338463/207226205-2cfdf7a6-2063-4efc-899a-5c1c962b17ff.png)
哪怕是已下线的服务在new PushClient时lastRefTime的值也是当前时间。
![image](https://user-images.githubusercontent.com/72338463/207226343-8460eb2e-84e7-41d4-bf89-f7db28024926.png)
导致最终会判断失败，下线的服务信息依旧存在。

**Comment by a1156698162** [comment]
@KomachiSion 我认为出现问题的原因是client端维护的serviceInfoMap并没有移除下线服务的操作，client端回像server端要服务列表维护到自己serviceInfoMap中，但是对于server端已经下线的服务，client端并没有从serviceInfoMap中移除，导致client端会针对已下线的服务和server端保持连接。

**Comment by a1156698162** [comment]
@KomachiSion 我认为出现问题的原因是client端维护的serviceInfoMap并没有移除下线服务的操作，client端回像server端要服务列表维护到自己serviceInfoMap中，但是对于server端已经下线的服务，client端并没有从serviceInfoMap中移除，导致client端会针对已下线的服务和server端保持连接。

**Comment by KomachiSion** [comment]
会移除，每次收到服务端的数据都会进行对比，移除不存在实例， 所以没有移除一定是服务端里还有数据， 客户端收到了新数据还带有这个实例。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
