### ISSUE TITLE
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([39.x.x.162]) tried

### ISSUE THREAD

**Issue by myishuohuo** [alibaba/nacos#967]
My fescar-server service Startup errors.My command is sh ./fescar-server.sh 8091 /usr/local/fescar/data  and My nacos service is running. My registry.conf  type = "nacos" and  serverAddr is  nacos service address Ip
![图片](https://user-images.githubusercontent.com/31065623/55129443-17349180-5152-11e9-838c-6c60cbcafb00.png)

**Comment by nkorange** [comment]
@myishuohuo Provide your nacos server version and client version please.

**Comment by myishuohuo** [comment]
fescar-server-0.4.0.tar.gz
nacos-server-1.0.0-RC2.tar.gz
![图片](https://user-images.githubusercontent.com/31065623/55132055-0557ec00-515c-11e9-9846-b90b0b51220a.png)

**Comment by myishuohuo** [comment]
This is my nacos service,It's running
![图片](https://user-images.githubusercontent.com/31065623/55132258-bcecfe00-515c-11e9-84df-46521db42c1a.png)

**Comment by nkorange** [comment]
@myishuohuo Look for error in {user.home}/logs/nacos/naming.log

**Comment by myishuohuo** [comment]
I saw the following exception from naming-server. Log
![图片](https://user-images.githubusercontent.com/31065623/55134603-32100180-5164-11e9-9eec-1452262c16c2.png)

**Comment by nkorange** [comment]
It's a fescar issue, refer to [fescar#647](https://github.com/alibaba/fescar/issues/647)
