### ISSUE TITLE
ERROR: Cannot create stream 3967 greater than Last-Stream-ID 3965 from GOAWAY.

### ISSUE THREAD

**Issue by DaiYuanchuan** [alibaba/nacos#9670]
同样的情况，nacos2.1.2
一开始连接是没有问题的 ，但它总会在一个时间段内报 连接失败的 错误

这是我一开始使用nginx配置的
![image](https://user-images.githubusercontent.com/38415417/206071459-13800555-6b3a-4ec7-b959-2535c75924c5.png)
一开始是可以连接的，可是用着用着就会报连接异常，过一段时间又会自动恢复，我开始以为是我的nginx不支持长连接，或者是nginx是问题，所以改成了下面的，使用ip直接连接到nacos
![image](https://user-images.githubusercontent.com/38415417/206078275-bc3605f9-4120-4dd8-9e80-b113ae65fe0d.png)

但是我依旧在日志里面找到了连接异常的问题
![image](https://user-images.githubusercontent.com/38415417/206078408-71eaea93-e579-4627-8727-2d5f5d9ebeef.png)

找到了日志时间节点对应的nacos节点的日志，那一个时间段内，nacos在大量的报错
![image](https://user-images.githubusercontent.com/38415417/206078578-7c32f768-342a-4e2c-8c01-3c4767e45bfe.png)

过了那个时间段，它又会恢复正常 ......

**Comment by leizq** [comment]
我也遇到了和你一样的问题，您有解决掉吗

**Comment by DaiYuanchuan** [comment]
> 我也遇到了和你一样的问题，您有解决掉吗

报的一样的错么？
我目前不确定它是怎么出现的
我尝试着增加nacos容器的可用内存，也许是错觉，感觉会好一点

**Comment by leizq** [comment]
是的，报一样的错误，服务经常性的过一段时间就会连接不上nacos

**Comment by KomachiSion** [comment]
可以试着直连一下看看， 有可能是nginx的问题

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
