### ISSUE TITLE
源码拉取后本地install打成jar包后nacos-console-2.0.3.jar不能单独运行？

### ISSUE THREAD

**Issue by Layfolk-zcy** [alibaba/nacos#9674]
![image](https://user-images.githubusercontent.com/59356890/206152266-fe68b6a6-192a-4970-9393-8babfe105689.png)

**Comment by YunWZ** [comment]
打包release版，`mvn package -Prelease-nacos`, 不需要单测可以加参数跳过。

**Comment by KomachiSion** [comment]
nacos-console只是console模块的jar包， 没有依赖也没指定主类。使用distribution中的压缩包解压出来后部署使用。
