### ISSUE TITLE
feign调用服务，nacos无法解析服务名为对应URL

### ISSUE THREAD

**Issue by blurmemo** [alibaba/nacos#9675]
environmrnt
jdk17
spring-boot-starter-parent：2.7.2
spring-cloud-dependencies：2021.0.3
spring-cloud-alibaba-dependencies：2021.0.1.0
spring-cloud-starter-openfeign：3.1.3
feign-httpclient：12.1

quession
请问在environment不变的情况下，如何修改可以将服务名（例如demoService）解析为对应URL（不用将URL写死）

error
2022-12-08 01:08:19.109 ERROR 35212 --- [nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.RetryableException: 不知道这样的主机。 (demoService) executing GET http://demoService/demo/test] with root cause

**Comment by blurmemo** [comment]
已经解决

**Comment by KomachiSion** [comment]
@blurmemo 可以把问题原因和如何解决在issue中写一下， 方便后续同学遇到同样的问题有一个解决的思路。

**Comment by blurmemo** [comment]
没问题👌发自我的 iPhone在 2022年12月9日，14:01，杨翊 SionYang ***@***.***> 写道：﻿
@blurmemo 可以把问题原因和如何解决在issue中写一下， 方便后续同学遇到同样的问题有一个解决的思路。

**Comment by blurmemo** [comment]
application.yml配置负载均衡规则但是没有成功配置，原因是在启动类中忘记添加
@Bean
    @LoadBalanced
    public RestTemplate restTemplate(){
        return new RestTemplate();
    }
同时没有导入
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
            <version>3.1.3</version>
</dependency>

**Comment by KomachiSion** [comment]
> application.yml配置负载均衡规则但是没有成功配置，原因是在启动类中忘记添加 @bean @LoadBalanced public RestTemplate restTemplate(){ return new RestTemplate(); } 同时没有导入spring-cloud-starter-loadbalancer这个依赖，本人用的是3.1.3版本的

Thanks
