### ISSUE TITLE
Please define the auth key in NacosDiscoveryProperties

### ISSUE THREAD

**Issue by ZenkieBear** [alibaba/nacos#9678]
**Is your feature request related to a problem? Please describe.**
No, but it made me feel at a loss
The auth configuration is not expose, I have to search for a long time to know the key"spring.cloud.nacos.discover.username&password'. It's not friendly for new developers.
Official document is still unclear

**Describe the solution you'd like**
We can define the keys in the class `NacosDiscoveryProperties`, dont user Properties methods to read the property.
Then everyone will get the right way.

**Comment by KomachiSion** [comment]
Please move to Spring cloud alibaba
