### ISSUE TITLE
2.1.2集群开启鉴权后，页面权限正常，服务启动注册报unknown user

### ISSUE THREAD

**Issue by justinlau0118** [alibaba/nacos#9682]
sping boot 2.6.6版本，nacos-server2.1.2，服务使用同目录下bootstrap.yml连接nacos集群，以下为文件内容：之前用的是nginx地址,截图的时候连接的是nacos集群单个节点的地址，直接写上三个节点地址也是一样报下面的错
![image](https://user-images.githubusercontent.com/36322686/206453157-f38e3f7f-7d9d-4f68-bd6f-28f9f32181e2.png)
如引入nacos-client-2.1.2和2.0.1版本，报错都是下面的com.alibaba.nacos.api.exception.NacosException: unknown user!
![image](https://user-images.githubusercontent.com/36322686/206455009-6c02f646-4d14-4a5e-bd82-9f65ccc1121b.png)
如引入nacos-client1.4.1版本，报错是 
![image](https://user-images.githubusercontent.com/36322686/206456654-203d1486-0fe5-4888-ab84-0877bcb626a0.png)

**Comment by YunWZ** [comment]
用得Spring-Cloud-Alibaba是哪个版本？每个版本的SCA都有对应的nacos-client版本依赖，建议和SCA官方依赖保持一致。

**Comment by justinlau0118** [comment]
> 用得Spring-Cloud-Alibaba是哪个版本？每个版本的SCA都有对应的nacos-client版本依赖，建议和SCA官方依依保持一致。

![image](https://user-images.githubusercontent.com/36322686/206615557-51f996ff-0062-4a7e-b922-9455e9c9f230.png)
我是不应该用2.0.4的nacos集群试一下？

**Comment by YunWZ** [comment]
看一下SCA社区的版本依赖矩阵，
之前我遇到这个问题是自己配置的nacos客户端依赖高于SCA自身依赖的nacos-client版本。
用SCA依赖的那个nacos-client版本，连接高版本的nacos-server应该是没有问题的。（Nacos服务端都是兼容低版本的客户端的。）

**Comment by justinlau0118** [comment]
@YunWZ 好的。感谢，我再试试

**Comment by KomachiSion** [comment]
第一张图的日志可以看到username和password根本没有传进去，所以才报的错，需要看spring cloud 从哪个版本开始支持这两个参数。

**Comment by justinlau0118** [comment]
@KomachiSion 谢谢。我看看再试试

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
