### ISSUE TITLE
nacos can't find loading config logs 

### ISSUE THREAD

**Issue by km11221122** [alibaba/nacos#9683]
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>2.2.9.RELEASE</version>
</dependency>
 When the application is started, the console does not find the specific configuration file that is loaded and the configuration content. When the configuration file is dynamically refreshed, there is no related log. The log level is only debug, but too many debug logs make it difficult for me to find related configuration information

This log was displayed in the console during the older version but not after the 2.1.0 upgrade

![图片](https://user-images.githubusercontent.com/38622267/206603926-a966355c-9752-49b8-ba46-d3c55f817edb.png)

![图片](https://user-images.githubusercontent.com/38622267/206604059-367cb5c6-aae7-492d-9324-ee56a042ca3d.png)

Another question: Can the default page values for configuration management be changed?
![图片](https://user-images.githubusercontent.com/38622267/206604212-701f9de3-a0d4-4b14-9f9c-d695c315d501.png)

**Comment by km11221122** [comment]
`<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version> 2.2.9.RELEASE</version>
</dependency>`

**Comment by KomachiSion** [comment]
1. Please make sure the dataId, group, namespace is right.
2. check ${user.home}/logs/nacos/config.log in your application.
3. If `${user.home}/logs/nacos/config.log` has logs when configuration is changed, please submit issue to Spring Cloud Alibaba community.
4. default page values can't change, if you want to change you can change the code by yourself.

**Comment by km11221122** [comment]
> 1. Please make sure the dataId, group, namespace is right.
> 
>     2. check ${user.home}/logs/nacos/config.log in your application.
> 
>     3. If `${user.home}/logs/nacos/config.log` has logs when configuration is changed, please submit issue to Spring Cloud Alibaba community.
> 
>     4. default page values can't change, if you want to change you can change the code by yourself.

already make sure the dataId, group, namespace is right.
I would like to confirm whether the current version can only be output in the log file. Because I read the source code only debug can output. I wonder if there is a configuration item that can be exported to the application console so that I can locate the problem more easily. Because it used to be possible to output to the application console with the older version.

**Comment by KomachiSion** [comment]
nacos-client has many async tasks and may print many logs in your application logs. For not effect users analyze their application logs, nacos-client will print logs into special dirs, by default `${user.home}/logs/nacos`.

The old version SCA has bug which will overwrite the nacos-client log config so that these logs print into application logs.

If you want to print logs into application, you can try to set nacos log config into your application log config file.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
