### ISSUE TITLE
咨询：SLB负载端口，应该配置几个？

### ISSUE THREAD

**Issue by daanhan** [alibaba/nacos#9685]
- 在文档 https://nacos.io/zh-cn/docs/cluster-mode-quick-start.html 中提到“http://nacos.com/:port/openAPI 域名 + SLB模式(内网SLB，不可暴露到公网，以免带来安全风险)，可读性好，而且换ip方便，推荐模式”，**请问，需要在SLB配置几个端口？是8848和9848吗？**
- 在SLB的端口配置中，应该配成什么策略？随机？最小连接数？平均？
- 如果某客户端通过SLB连接到A机nacos server的8848，再通过SLB连接到B机nacos server的9848，是否OK？
- 咱们官网的文档，还有很多1.x的文档，缺少2.x的文档，是否安排分开的版本啊？

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-compatibility.html

如果是默认值的话，只需要8848和9848.

**Comment by KomachiSion** [comment]
文档已经分开
