### ISSUE TITLE
HA solution across datacenter / cluster with all applications being active

### ISSUE THREAD

**Issue by chingjustwe** [alibaba/nacos#9689]
## Issue Description

Type: *Question*

### Describe what happened (or what feature you want)

We have spring boot based application deployed in multiple datacenters all over the world, we want to have a place to centralized manage them, **Nacos** could be a nice choice. 

But seems there is no good way to achieve high availability, because **Nacos** has to be deployed in multiple (two) datacenters, and our applications all need to be alive.

### Describe what you expected to happen

Assuming there are two **Nacos** clusters deployed on Primary DC **A** and Secondary DC **B**, and our applications could be located in any DC **A**, **B**, **C**...
Below are the approaches we've thought about:
1. All applications connect to Primary **Nacos** cluster by default, and when disaster happens, they can auto failover to Secondary **Nacos**. - not sure if it is possible, **can someone advise if *Nacos* or client side spring boot application can achieve this?**
2. Let our application connect to Primary and Secondary **Nacos** at the same time, and handle failover logic on client side. - also **not sure if it is possible to connect to multiple register / config center.**
3. Deploy one **Nacos** cluster across DC. - **is it a suggested action? If yes, can this *Nacos* cluster still working if nodes on one DC all down?**
4. **Is there a middleware layer between end application and multiple *Nacos* clusters which handles HA, like a floating VIP or DNS, so that application just need to connect to this middleware?**

### How to reproduce it (as minimally and precisely as possible)

NA

### Tell us your environment

Production

### Anything else we need to know?

Really appreciate for any comments or suggestion.

**Comment by KomachiSion** [comment]
If the network connected, Nacos can support deploy in multiple DC. You can deploy nacos nodes in two or three DC and make them as one cluster. 

If there are only two DC and the Primary DC down, it might cause the persistent service feature and service metadata feature has problem but the config and ephemeral service will work well still.

If there are three DC, any one DC is down has no effect.

**Comment by chingjustwe** [comment]
Thanks @KomachiSion for your comment.

If I deploy *Nacos* nodes in multiple DCs and federate them as one cluster, would there be some network issues? Because the network status between each DC could be unstable, not sure if the latency / jitter would impact *Nacos* cluster, please advise, thanks.
