### ISSUE TITLE
nacos在配置管理里面千万不要使用user.name！！！哈哈哈哈

### ISSUE THREAD

**Issue by Prometheusxiao** [alibaba/nacos#9697]
配置：
user: 
  name: adawdwa我打完1
  test: dawdaw达瓦达瓦

得到的结果：
{"name":"你电脑的主机名称，哈哈哈","test":"dawdaw达瓦达瓦"}

问题说明：
就是你配置的user.name没有效果，他显示的是你的主机名~~！

**Comment by KomachiSion** [comment]
应该是你的代码里自己修改成了你的主机名。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
