### ISSUE TITLE
question：配置更新，触发属性变更额外的操作

### ISSUE THREAD

**Issue by hqgordon** [alibaba/nacos#9698]
Is it possible to listen for configuration changes and trigger additional actions in addition to property changes? For example, do something like upload

监听配置的变更，触发除了属性变更额外的操作可以做到吗？，例如做一些上传之类的操作

**Comment by KomachiSion** [comment]
你可以监听配置，当配置变更时自行触发。 nacos只负责同志配置变更。

**Comment by hqgordon** [comment]
> 

怎么实现呢，没有查询到相关的文章教程，这边有推荐的么，谢谢
