### ISSUE TITLE
Need network port in Search result on Listening Query TAB

### ISSUE THREAD

**Issue by qintianjie** [alibaba/nacos#970]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
Only IP in search result, can't distinct service on the same host.

### Describe what you expected to happen
Show IP + PORT in search result

### How to reproduce it (as minimally and precisely as possible)

1.  show in GUI

### Tell us your environment
1.0.0-RC2

**Comment by zhaoyuguang** [comment]
![image](https://user-images.githubusercontent.com/10150229/62341816-2fa92400-b517-11e9-9794-2fccdd83b848.png)
在ip温度的搜索时  这里增加port一个搜索框么？ 然后在在list里面增加对应的数据？
