### ISSUE TITLE
Dependency nacos-client 2.1.x version can not registry service to nacos-server 2.1.0. When change client version to 2.0.4,it be ok

### ISSUE THREAD

**Issue by chengyouling** [alibaba/nacos#9702]
**Describe the bug**
Dependency nacos-client 2.1.x version can not registry service to nacos-server 2.1.0. When change client version to 2.0.4,it be ok.

**Expected behavior**
Give the reason and publish new release to adapter nacos-server 2.1.0.

**Actually behavior**
Dependency nacos-client 2.1.x version can not registry service to nacos-server 2.1.0.
 When change client version to 2.0.4,it be ok.

**How to Reproduce**
Give the reason and publish new release to adapter nacos-server 2.1.0.

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Version [nacos-server 2.1.0, nacos-client 2.1.x]
 - Module [naming]
 - SDK [dubbo]

**Additional context**
Current has no.

**Comment by KomachiSion** [comment]
I can register service, what's your error information?

**Comment by chengyouling** [comment]
I debugger in local,it can be create namingService and enter the registry method.But nacos-server can not see the register server info.

**Comment by KomachiSion** [comment]
I use nacos-client 2.1.x register service to nacos-server 2.1.0 directly ok.

You can try to see the logs in `${user.home}/logs/nacos`

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
