### ISSUE TITLE
can "/nacos/v2/ns/instance/list" return instance record which  enabled was false?

### ISSUE THREAD

**Issue by afeiluo** [alibaba/nacos#9703]
I noticed that the endpoint “/nacos/v2/ns/instance/list” which Open-API offered only return enabled instance, if return all instances will be fantastic for me, Any plan to support that feature?

**Comment by KomachiSion** [comment]
the open only return enabled instances from it's design. Just like `/nacos/v1/ns/instance/list` do.

**Comment by KomachiSion** [comment]
Your feature request I think is the `v2` admin or console API. Has some one can support it?

**Comment by YunWZ** [comment]
> Your feature request I think is the `v2` admin or console API. Has some one can support it?

@i will resolve it@

**Comment by KomachiSion** [comment]
@YunWZ We need to discuss first.

I think can't add featreu in `/nacos/v2/ns/instance/list` API, It's a openAPI might face to `client` not for `admin` or `console`.

If want to add this feature, add an new console/admin api will be better.

**Comment by KomachiSion** [comment]
the catalog api can support this feature.
