### ISSUE TITLE
Consultation: CloseableHttpAsyncClient does not clean up expired and invalid connections

### ISSUE THREAD

**Issue by zz630** [alibaba/nacos#9708]
咨询：CloseableHttpAsyncClient没清理过期连接和无效连接的问题

**Additional context**
我把持久化的实例默认健康检查方式从tcp改为http，然后对DefaultAsyncHttpClientRequest#asyncClient的连接池PoolingNHttpClientConnectionManager做了监控。监控发现5k+的实例，经过一段时间的运行后，连接池状态PoolStats的leased+available数据接近5k。nacos5节点部署的话，我理解每个节点经过HealthCheckResponsibleInterceptor#intercept，hash分配的健康检查任务，就算有倾斜，每个节点的发起http检查的数量也不会有这么多。检查2.0.3和develop的分支，没找到CloseableHttpAsyncClient清理过期连接和无效连接的代码

**Describe alternatives you've considered**
在DefaultAsyncHttpClientRequest的构造函数，CloseableHttpAsyncClient.start()时新建线程，定时对ConnectionManager进行closeExpiredConnections和closeIdleConnections操作。

**Additional context**
I changed the default health check method of the persistent instance from tcp to http, and then monitored the connection pool PoolingNHttpClientConnectionManager of DefaultAsyncHttpClientRequest#asyncClient. The monitoring found 5k+ instances. After a period of operation, the leased+available data of the connection pool status PoolStats is close to 5k. For nacos5 node deployment, I understand that each node passes through HealthCheckResponsibleInterceptor#intercept, the health check task assigned by hash, even if there is a skew, the number of http checks initiated by each node will not be so many. Checked the 2.0.3 and develop branches, but did not find the code for CloseableHttpAsyncClient to clean up expired and invalid connections

**Describe alternatives you've considered**
Create a new thread in the constructor of DefaultAsyncHttpClientRequest, CloseableHttpAsyncClient.start(), and perform closeExpiredConnections and closeIdleConnections operations on ConnectionManager regularly.

**Comment by KomachiSion** [comment]
是不是使用方法上有问题，需要在请求结束时调用DefaultHttpClientRequest的close方法？

**Comment by KomachiSion** [comment]
目前应该只在callback中关闭了response， 是否request也需要关闭才是正确的用法？

**Comment by zz630** [comment]
> 目前应该只在callback中关闭了response， 是否request也需要关闭才是正确的用法？

在DefaultAsyncHttpClientRequest#execute中的HttpRequestBase没找到close方法。

参考了一些CloseableHttpAsyncClient的介绍，说
```
HttpClient采取一个策略，通过一个后台的监控线程定时的去检查连接池中连接是否还“新鲜”，如果过期了，或者空闲了一定时间则就将其从连接池里删除掉。但异步HttpClient中没有自动清理设置，需要自行实现手动启用一个线程，定时运行closeExpiredConnections 和closeIdleConnections方法，清理过期连接和无效连接。
```
跟了一下nacos依赖版本的httpclient的源码，符合描述

参考
https://blog.51cto.com/u_12302929/3391575
https://www.cnblogs.com/trust-freedom/p/6349502.html
https://blog.csdn.net/dh753655485/article/details/107912818

**Comment by KomachiSion** [comment]
可以提个PR优化一下。

**Comment by zz630** [comment]
@i will solve it@
