### ISSUE TITLE
Prometheus接口不支持鉴权，新增对该接口的鉴权

### ISSUE THREAD

**Issue by realJackSun** [alibaba/nacos#9710]
![image](https://user-images.githubusercontent.com/58767027/207760465-5f83c336-4365-459c-ae3c-b952bf06c34a.png)

**Comment by vividfish** [comment]
我试下  @ i will solve it @

**Comment by KomachiSion** [comment]
这个接口是暴露给prometheus进行服务发现的， 那如果需要加鉴权需要看下prometheus来查询的时候是否能够扩展带上身份信息。
