### ISSUE TITLE
nacos2.0.3 OOM

### ISSUE THREAD

**Issue by zz630** [alibaba/nacos#9711]
-Xms6g -Xmx6g -Xmn3g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
5k实例，相同配置的同一个集群内，其中一个节点频繁fullgc触发oom，其他节点gc正常，运行时间都有几个月了。mat分析结果如下
<img width="835" alt="image" src="https://user-images.githubusercontent.com/53512996/207796895-84247e33-448b-4777-b221-28695c4d002d.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/53512996/207797349-514da88f-82c5-4abd-843c-e43435b2b881.png">

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/53512996/207797535-a6b6e200-e47e-4138-b0ef-387960cf07ad.png">

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/53512996/207797975-4bd40301-7690-498d-92bf-16b23356a154.png">

**Comment by zz630** [comment]
jraft有类似问题， https://github.com/sofastack/sofa-jraft/issues/833

**Comment by KomachiSion** [comment]
可以升级到最新版本试试， 新版本可能升级过jraft

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
