### ISSUE TITLE
 Registry service list is empty

### ISSUE THREAD

**Issue by bodhili** [alibaba/nacos#9712]
**Describe the bug**
- Registry service list is empty

**Expected behavior**

- Registry service list is not empty
- If the cookie or token expires and you need to log in again, a prompt should be given instead of directly displaying an empty list

**Actually behavior**
- Registry service list is empty

**How to Reproduce**
1. After logging in, do not log out, and then enter the viewing list after a while, it will be empty

**Comment by KomachiSion** [comment]
I can't reproduce your problem, it might be your app problem which make the login thread stopped so that the token can't auto updated after expired.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
