### ISSUE TITLE
open API能否提供对配置集里面的某一配置项更新的接口？ UPDATE config

### ISSUE THREAD

**Issue by hwsmithhuangwu** [alibaba/nacos#9713]
需要通过open API去改写nacos的配置集里面的某一个配置项，再写回到nacos数据库的完整程序代码，dataID为yaml格式。xxxx.yml
这个很难处理，需要自己去处理解析yaml格式文件？如果能提供一个API，可以让我们去更新某一配置项，会方便很多。

We need to update a configuration item in the configuration set of nacos through the open API, and then write the complete Data back to the nacos database. The dataID is in yaml format.，for example, "xxxx.yml"

This is difficult to handle. We have to process and parse the yaml format file by ourself. If you can provide an API to update a configuration item in a DataID file, it will be much more convenient.

**Comment by YunWZ** [comment]
应该不会做这个功能。。处理yaml格式，可以用[SnakeYAML](https://mvnrepository.com/artifact/org.yaml/snakeyaml)，

**Comment by KomachiSion** [comment]
配置内容对Nacos来说是一个黑盒， 里面是yaml还是properties都无关。

因此对于需要修改yaml中的一个key的需求，应该暂时不会有计划。
