### ISSUE TITLE
How is use the Nacos-Address-Server 如何使用 Nacos Address Server

### ISSUE THREAD

**Issue by sixsixsix516** [alibaba/nacos#9716]
## Issue Description

我猜测两种方式
1. Nacos Address Server 采用 standalone 模式启动，Nacos 节点就可以通过 address server 方式的寻址。
2. Nacos Address Server 采用 cluster.conf 文件方式启动，cluster.conf 文件存放初始机器节点。随后可通过 接口进行动态添加节点、移除节点。不过这样的方式，address server 会通过 distro 协议将节点信息同步到其他节点，而 其他节点使用 Nacos Server Address 是使用 HTTP 接口请求的方式，这样让我有点混乱。

### Describe what happened (or what feature you want)
网上查询了如何使用 NacosServerAddress ，但我没有查询到信息。

### Describe what you expected to happen
所以希望官方告知下该如何部署使用。

**Comment by KomachiSion** [comment]
没看懂你混乱的点。

Nacos Address Server本质是Nacos服务发现内核的一个拓展模块， 实现一个类似DNS的功能，通常用作服务自身的节点管理和域名转换成ip的功能。

使用方式和nacos是一样的。暴露的是http接口。

地址服务器并不是给自己的集群使用的，而是给别的集群，比如其他的nacos集群，来替代cluster.conf 文件进行节点变更。
