### ISSUE TITLE
Start with the source code of version 2.2.0. RequestMappingHandlerMapping reports two errors of the same type

### ISSUE THREAD

**Issue by twelvet-s** [alibaba/nacos#9717]
**Describe the bug**
No qualifying bean of type 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping' available: expected single matching bean but found 2: requestMappingHandlerMapping,controllerEndpointHandlerMapping

There is no such problem when using 2.2.0.PIGOEM

**Comment by KomachiSion** [comment]
Maybe you submit issue to error community, nacos has no `2.2.0.PIGOEM` version.

**Comment by twelvet-s** [comment]
> 可能你提交 issue 到 error community，nacos 没有 `2.2.0.PIGOEM`版本。
This is the warehouse. Maven Center can search for this version

**Comment by twelvet-s** [comment]
> Maybe you submit issue to error community, nacos has no `2.2.0.PIGOEM` version.

This is the warehouse. Maven Center can search for this version

**Comment by KomachiSion** [comment]
please submit your url of Maven Center for `2.2.0.PIGOEM`

**Comment by twelvet-s** [comment]
> This is the warehouse. Maven Center can search for this version

https://central.sonatype.dev/artifact/io.springboot.nacos/nacos-config/2.2.0.PIGOEM

**Comment by twelvet-s** [comment]
> please submit your url of Maven Center for `2.2.0.PIGOEM`

不好意思，可能是我弄错了官方镜像，我看到了一个com.alibaba.nacos

**Comment by twelvet-s** [comment]
> please submit your url of Maven Center for `2.2.0.PIGOEM`

Sorry, I may have mistaken the official image. I saw a com.alibaba.nacos

**Comment by twelvet-s** [comment]
> Sorry, I may have mistaken the official image. I saw a com.alibaba.nacos

However, the 2.2.0 release is not found in the groupid. Which is the official image

**Comment by YunWZ** [comment]
@i will resolve it@

**Comment by KomachiSion** [comment]
> > This is the warehouse. Maven Center can search for this version
> 
> https://central.sonatype.dev/artifact/io.springboot.nacos/nacos-config/2.2.0.PIGOEM

The location is not nacos community, Maybe you should connect the released group to discuss your problem.

**Comment by twelvet-s** [comment]
> > > This is the warehouse. Maven Center can search for this version
> > 
> > 
> > https://central.sonatype.dev/artifact/io.springboot.nacos/nacos-config/2.2.0.PIGOEM
> 
> The location is not nacos community, Maybe you should connect the released group to discuss your problem.

OK. That community has released version 2.2.0.1 and solved this problem. Thank you very much
