### ISSUE TITLE
What is the strategy for invoking service load balancing or polling? Can it be modified?

### ISSUE THREAD

**Issue by RemixJason** [alibaba/nacos#972]
## Issue Description

Type: *Seek help*

### Describe what happened (or what feature you want)
nacos的轮询策略，或者说负载均衡策略是怎么决定的？目前使用的是feign调用方式，知道feign是Ribbon的封装。但是是怎么个逻辑呢？切入点是哪里？QQQ！

**Comment by nkorange** [comment]
Nacos本身不绑定Spring体系的负载均衡策略。对于SpringCloud来说，可以使用Ribbon去修改默认的负载均衡策略。
