### ISSUE TITLE
BUG Report : Nacos Address Server 调用 HTTP 接口 无法添加节点

### ISSUE THREAD

**Issue by sixsixsix516** [alibaba/nacos#9722]
**Describe the bug**
我下载了已发行版本源码 Nacos 2.2.0

当我启动 Nacos Address Server 后，调用如下接口完成添加节点

POST http://localhost:8080/nacos/v1/as/nodes?product=life&cluster=default&ips=127.0.0.2:8080

![image](https://user-images.githubusercontent.com/45815935/208235867-b31235dd-49c4-4345-90e7-c8ae5271086e.png)

但是 Nacos Address Server 却返回了 illegal ip: 127.0.0.2:8080

**Expected behavior**
期望注册成功

**Actually behavior**
注册不成功

**How to Reproduce**
正常运行即可复现

**Desktop (please complete the following information):**
 - OS: Win11
 - Version：Nacos 2.2.0
 - Module：address
 - SDK 源码方法直接运行
**Additional context**

** 我排查到了问题原因 **
![image](https://user-images.githubusercontent.com/45815935/208235987-2321e998-595d-448b-9084-db28798c3b99.png)

String[] ipArray = addressServerManager.splitIps(ips);
该方法返回的是 按照 逗号 分割的数据，参数为 127.0.0.2:8080 该方法返回 ["127.0.0.2:8080"]

而接下来的方法
InternetAddressUtil.checkIPs(ipArray);
校验 IP 是否合法，该方法只能对单个 ip 进行校验，如果ip:port 形式 则返回失败。 但是调用校验ip方法的参数 确实包含了端口的。

所以这里有个冲突。

这里我猜测难道不能指定port? 只能使用单个ip？ 然后端口就用默认的8848？

不过随着我后面的继续翻阅源码。

就是这里，根据 ip 生成 实例 的时候却 取了该字段 （以冒号形式进行了拆分），也就是后面解析了ip:port方法
![微信截图_20221217174957](https://user-images.githubusercontent.com/45815935/208236171-7404150f-4156-49ca-b434-d3ca3d1457b5.png)

但是带 port 的ip是传递不过来的

**Comment by KomachiSion** [comment]
地址服务器是不能带port的， 是一个类似dns的服务。

**Comment by sixsixsix516** [comment]
> 地址服务器是不能带port的， 是一个类似dns的服务。

不是？我添加一个Nacos节点只能传递IP的意思是 端口只能是 8848？ 意思我所有集群的节点端口都必须是8848吗，但是我看源码后面明明对我传进去的 数据 继续了 ip:port 这种格式的解析后，将port字段赋值给了instance对象，如果没传port才给端口8848，这后面的代码不是明明处理了端口吗，为什么请求的时候还不能传？ 这里前后不一致吧？ 这是怎么回事呢

**Comment by KomachiSion** [comment]
地址服务器只记录ip作为有效内容， 端口是nacos-naming的需要， 地址服务器会记录这个默认值，调用地址服务器的接口时返回的也只有ip。

说白了这个地方默认为8848和0是一样的。

**Comment by KomachiSion** [comment]
一种用法约定吧，就好比DNS只解析域名， 地址服务器也只转成ip，端口可以忽略。

@JianweiWang
