### ISSUE TITLE
nacos-client 模块中MetricsMonitor的监控指标是怎么使用的？

### ISSUE THREAD

**Issue by MangerLe** [alibaba/nacos#9723]
在其余模块中同过actuator 暴露了出来，但是nacos-client模块的数据是怎么使用的？可以通过Spring-boot-actuator暴露吗？
可以的话是怎么暴露的？

**Comment by MangerLe** [comment]
> 在其余模块中同过actuator 暴露了出来，但是nacos-client模块的数据是怎么使用的？可以通过Spring-boot-actuator暴露吗？
> 可以的话是怎么暴露的？
actuato暴露的话是需要拿到 PrometheusMeterRegistry 的bean,才是可以的啊。但是nacos-client客户端里面的那种写法，我测试没办法直接暴露出来，可以的话麻烦能简单说说吗？

![image](https://user-images.githubusercontent.com/51878514/208332067-25fdead0-43d8-4368-896c-05b4cf6d31ed.png)

**Comment by MangerLe** [comment]
> MetricsMonitor使用的是io.micrometer的标准接入， 可通过任意具体实现，如prometheus等进行暴露，actuator也是可以的。

actuator暴露的话是需要拿到 PrometheusMeterRegistry 的bean,才是可以的啊。但是nacos-client客户端里面的那种写法，我测试没办法直接暴露出来，可以的话麻烦能简单说说吗？ 或者是使用Metrics工具类写出来的可以通过actuator可以暴露出来

![image](https://user-images.githubusercontent.com/51878514/208332156-7ec62dac-0c70-4fed-ab63-e9a09ff48787.png)

**Comment by KomachiSion** [comment]
无注册器的register会注册到默认的注册器中， 将PrometheusMeterRegistry作为默认注册器就可以了， 这个属于micrometer用法，与nacos无关，请自行研究。

**Comment by MangerLe** [comment]
> 个属于micrometer用法，与nacos无关，请自行研究。

多谢大佬
