### ISSUE TITLE
nacos容器wss内存不释放

### ISSUE THREAD

**Issue by yinweiliaojie08** [alibaba/nacos#9724]
在kubernetes使用nacos时一直正常，直到在宿主机执行清理内存的操作，即echo '3' > /proc/sys/vm/drop_caches的操作，糟糕的事情发生了，nacos集群中运行在这台宿主机的pod wss内存不再释放了，以持续上涨的状态一直递增，涉及到业务，无法重启pod或者宿主机来测试重启的具体结果，我应该如何处理，是否遇到过相似场景

**Comment by yinweiliaojie08** [comment]
版本：NACOS2.0.2

**Comment by yinweiliaojie08** [comment]
![image](https://user-images.githubusercontent.com/67277453/208336208-215fed38-ddab-4162-b5dd-a375aecd1d95.png)

**Comment by KomachiSion** [comment]
我没有遇到过， 看下社区是否有其他同学遇到

**Comment by KomachiSion** [comment]
另外能否看下是什么东西占用的WSS

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
