### ISSUE TITLE
service subscriber: Why is /nacos/#/subscriberLists  empty?

### ISSUE THREAD

**Issue by shouldsee** [alibaba/nacos#9725]
**Describe the bug**
Not a bug. Just wondering whether nacos maintain a list of service subscriber internally?

**Expected behavior**
When consumer subscribe provider, an entry produced in /nacos/#/subscriberList

**Actually behavior**
Nothing.

**Desktop (please complete the following information):**
 - OS:  ubuntu
 - Version  nacos-server 2.2.0
 - Module na
 - SDK na

**Additional context**

**Comment by Daydreamer-ia** [comment]
Here are all open-api: https://nacos.io/zh-cn/docs/open-api.html

**Comment by shouldsee** [comment]
> Here are all open-api: https://nacos.io/zh-cn/docs/open-api.html

I checked api doc and found no related info. The problem is about the frontend react-based console-ui, not the http api....

**Comment by Daydreamer-ia** [comment]
> > Here are all open-api: https://nacos.io/zh-cn/docs/open-api.html
> 
> I checked api doc and found no related info. The problem is about the frontend react-based console-ui, not the http api....

Yes, nacos-server maintains listeners for config and also service, you can check the component named **ConfigChangeListenContext** and **ClientManager**.

The frontend data controller is in **nacos-console** module, and I cannnot find any implements about what you describe.

**Comment by shouldsee** [comment]
> 

Cool thanks. I am not very familiar with components. Does that mean I have to interact with it through grpc and not with http?

**Comment by KomachiSion** [comment]
listener and subscriber can be searched in console. 
But only support for accurate service(include group and service name) and config(include group and dataId).
