### ISSUE TITLE
nacos可以继承公共配置项吗？

### ISSUE THREAD

**Issue by hsming** [alibaba/nacos#9726]
举个例子，A、B、C服务使用的是同一个数据库连接下的不同DB，那么希望能将数据库ip、端口、用户名密码作为公共配置:

    mysql.ip=127.0.0.1
    mysql.port=3306
    mysql.user=root
    mysql.password=******

A服务中引用为

    spring.datasource.url=jdbc:mysql://${mysql.ip}:${mysql.port}/db_aaaa
    spring.datasource.username=${mysql.user}
    spring.datasource.password=${mysql.password}`

B服务中引用为

    spring.datasource.url=jdbc:mysql://${mysql.ip}:${mysql.port}/db_bbbb
    spring.datasource.username=${mysql.user}
    spring.datasource.password=${mysql.password}`

**目前看到的文档都是引用完整的公共配置文件，怎么才能做到引用公共配置中的单个配置项呢？**

**Comment by Daydreamer-ia** [comment]
nacos好像并不关心配置是什么内容

**Comment by KomachiSion** [comment]
配置之间的互相关联，互相依赖需要在应用测自行处理。nacos只负责将配置推送至应用，应用如何使用，如何关联如何依赖已经超出了nacos可管理的范围。

**Comment by YunWZ** [comment]
你可以问下SCA社区，是可以配置监听其他group下的配置文件的。具体参考spring-cloud-alibaba官方文档。
