### ISSUE TITLE
nacos 2.2.0 支持 prometheus http sd 但访问接口，返回空数组[]

### ISSUE THREAD

**Issue by cavellpotter** [alibaba/nacos#9728]
![image](https://user-images.githubusercontent.com/49619105/208430703-cd73e951-9f98-4ed1-a167-d7f838385b72.png)
而实际上有服务注册到nacos，配置文件也添加nacos.prometheus.metrics.enabled=true
请问是什么问题导致获取到空

**Comment by karsonto** [comment]
有没有服务注册到nacos?

**Comment by cavellpotter** [comment]
> 有没有服务注册到nacos?

有注册，但不是default命名空间

**Comment by cavellpotter** [comment]
注册到default也没有

**Comment by karsonto** [comment]
我这边执行 curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
能正确显示
<img width="962" alt="image" src="https://user-images.githubusercontent.com/31433550/208572661-22c774e5-acbc-4d76-86e4-fbc4a0685214.png">

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by easy117** [comment]
same question, i register a service with group:test and it can be find in dashboard
![image](https://user-images.githubusercontent.com/112168508/209803801-3817de4f-72b3-4a89-87b0-0da472bd97ca.png)

but can not find by curl
![image](https://user-images.githubusercontent.com/112168508/209803903-b8c7ec71-be6f-4608-ad84-850fa4f9bd19.png)

**Comment by karsonto** [comment]
@easy117 用我测试的方法注册实例能看到吗？

**Comment by cavellpotter** [comment]
@karsonto 依然是空[]，获取不到服务列表，prometheus配置http sd 监控不到任何服务的

**Comment by karsonto** [comment]
@cavellpotter 明白，我这边用程序注册实例再测试看看

**Comment by cavellpotter** [comment]
@karsonto 我做了测试，注册到public命名空间才会有，而注册到别的命名空间就没有了
![image](https://user-images.githubusercontent.com/49619105/210160272-f36907c7-eda1-47bf-979a-10a8ae107e19.png)

![image](https://user-images.githubusercontent.com/49619105/210160316-bc260d22-b79a-4c98-8767-66fc3b642a90.png)

**Comment by karsonto** [comment]
@cavellpotter 嗯，我提交了PR解决这个问题
