### ISSUE TITLE
多数据源插件，可以考虑为Mapper接口添加 default 方法，对通用的SQL进行默认实现

### ISSUE THREAD

**Issue by xzxiaoshan** [alibaba/nacos#9730]
多数据源插件，可以考虑为Mapper接口添加 default 方法，原因有下：
1、大部分的SQL都是标准的SQL，也就是可以在多种数据库中通用的。
2、对这些预判比较通用的SQL，写在Mapper接口中使用 default 方法来提供默认实现。
3、将类似分页这种肯定需要特定数据库实现的SQL定义为必须实现的方法，不使用 default。
这样以来，在为新的数据源写插件时，只需要重写需要重写的接口方法，而不再需要将所有SQL都拷贝一遍。这样更有利于避免或降低主版本需要修改SQL这种升级导致的插件不可用问题。

**Comment by li-xiao-shuang** [comment]
目前一些基础的sql 通过抽象类实现了，可以看看剩余的sql 还有哪些需要提供默认实现，可以提提建议或者pr

**Comment by xzxiaoshan** [comment]
好像只有分页相关的几个SQL不通用，其他的SQL我过了一遍，几乎都是标准SQL，绝大部分通用。

**Comment by xzxiaoshan** [comment]
@li-xiao-shuang 我准备来搞一下，然后提交一个PR过来。
