### ISSUE TITLE
nacos 2.2.0 source start fail

### ISSUE THREAD

**Issue by bingyang001** [alibaba/nacos#9731]
nacos 2.2.0 source start fail ,how to solve?,thanks

1、start console moudle. Nacos class
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/4987950/208590072-e265d08f-3bf7-4bbc-b03f-d25ff6b5dacb.png">
2、error message:
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/4987950/208590250-2f31542b-bb15-4309-97f9-8510d7d5e6ac.png">

**Comment by a25017012** [comment]
[AuthHeaderUtil](https://github.com/alibaba/nacos/blob/2.2.0/auth/src/main/java/com/alibaba/nacos/auth/util/AuthHeaderUtil.java)

本地试了下 好使，您可以找下这个文件 看看有没，或者重新导入

**Comment by bingyang001** [comment]
> [AuthHeaderUtil](https://github.com/alibaba/nacos/blob/2.2.0/auth/src/main/java/com/alibaba/nacos/auth/util/AuthHeaderUtil.java)
> 
> 本地试了下 好使，您可以找下这个文件 看看有没，或者重新导入

有这个包，其他模块有类似的包引用错误，但是项目编译能通过。官方发布的release 版本按理应该可以直接跑起来的，手动导入包，不太合理
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/4987950/208705096-2ee6b76b-9616-4654-942b-c0c5999a6ed5.png">

**Comment by KomachiSion** [comment]
那就是你idea环境的问题， 需要您自行解决了。

**Comment by bingyang001** [comment]
> 那就是你idea环境的问题， 需要您自行解决了。

那奇怪了2.1.2 版本源码编译，启动都没问题。2.2.0 源码就报包引用无效

**Comment by YunWZ** [comment]
> > 那就是你idea环境的问题， 需要您自行解决了。
> 
> 那奇怪了2.1.2 版本源码编译，启动都没问题。2.2.0 源码就报包引用无效

可能是IDE的问题，删除IDE的索引看看能不能解决。
