### ISSUE TITLE
[2.1.1] Nacos-Server NPE occurred when process ConfigBatchListenRequest

### ISSUE THREAD

**Issue by MajorHe1** [alibaba/nacos#9733]
2.1.1 版本，生产和UAT环境都会不定期报NPE异常，如下图，生产的规模是12台机器，大概每天1到2笔该异常
![企业微信截图_16715249936214](https://user-images.githubusercontent.com/53824889/208620955-0f6648b7-683d-43c7-86ca-6ecb522f1a77.png)
对应的客户端日志：
![企业微信截图_16715252015496](https://user-images.githubusercontent.com/53824889/208621266-2e1a366d-0c97-4be1-a19a-ead7d9efe8bf.png)

已知信息有：
1、均由ConfigBatchListenRequest导致，暂未发现其他request触发该问题的情况。
2、均发生在配置变更后。服务端存在一个配置以10秒每次的固定频率更新。客户端得知配置变更后，创建ConfigBatchListenRequest来查配置，然后触发NPE异常，服务端返回ErrorResponse{resultCode=500, errorCode=500}，客户端配置变更失败。
3、不定时不定期出现，频率大概每天1到2笔，不影响整体运行

猜想：（更多的日志打印信息是我修改源码主动加上去的）
![企业微信截图_16715261248599](https://user-images.githubusercontent.com/53824889/208623828-c2c75efc-5e18-413b-8762-5703d3fc7089.png)
从代码来看，能报出NPE异常，只有可能 connection 为 null， 或者 connection.getMetaInfo() 为 null，那，问题的根因是啥呢？

**Comment by Daydreamer-ia** [comment]
Meta不应该会是null，因为是先创建好后才传入的，之后就没动过了
![image](https://user-images.githubusercontent.com/83362909/209145109-e32fef6a-ef54-41cc-a78f-e6a3070888e8.png)
可能是Connection被unregister了，因为上面走到 `conn.getMeta()` 之前，是先检查过Connection是否存在的，存在才会走到你说的这个位置
![image](https://user-images.githubusercontent.com/83362909/209145434-fa30e4ff-4585-4171-849c-f9f806e48d64.png)

**Comment by Daydreamer-ia** [comment]
感觉是网络环境导致有些推送失败了

**Comment by Daydreamer-ia** [comment]
应该不是连接，我感觉是 `RequestHandler` 中报出来的。走到这里，`Meta` 不会是null，`Connection` 也是先 `checkValid` 是否存在的

**Comment by MajorHe1** [comment]
> 应该不是连接，我感觉是 `RequestHandler` 中报出来的。走到这里，`Meta` 不会是null，`Connection` 也是先 `checkValid` 是否存在的

加了日志看堆栈信息，等UAT复现吧。如果UAT不能复现，就上生产去看。讨论认为大概率是 RequestHandler 中的问题。不过奇怪的是为啥只有 ConfigBatchListenRequest 触发异常，所以还是要等堆栈日志出来再定位

**Comment by MajorHe1** [comment]
UAT复现了，均是如下异常

[grpc] Fail to handle request from connection [1672720641027_172.*.*.*_30068], error message :java.lang.NullPointerException, request type :ConfigBatchListenRequest, request :ConfigBatchListenRequest{headers={accessToken=eyJhb####df04, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=4bfa0##e337, Client-RequestTS=1672737679394, exConfigInfo=true, X-Real-IP=172.*.*.*}, requestId='null'}, 

stack trace :
java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936), com.alibaba.nacos.config.server.remote.ConfigChangeListenContext.addListen(ConfigChangeListenContext.java:57), com.alibaba.nacos.config.server.remote.ConfigChangeBatchListenRequestHandler.handle(ConfigChangeBatchListenRequestHandler.java:66), com.alibaba.nacos.config.server.remote.ConfigChangeBatchListenRequestHandler.handle(ConfigChangeBatchListenRequestHandler.java:41), com.alibaba.nacos.core.remote.RequestHandler.handleRequest(RequestHandler.java:58), com.alibaba.nacos.core.remote.RequestHandler$$FastClassBySpringCGLIB$$6a0564cd.invoke(<generated>), org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218), org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163), org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763), org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89), com.alibaba.nacos.config.server.aspect.RequestLogAspect.interfaceListenConfigRpc(RequestLogAspect.java:218), sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634), org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624), org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175), org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763), org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97), org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186), org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763), org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708), com.alibaba.nacos.config.server.remote.ConfigChangeBatchListenRequestHandler$$EnhancerBySpringCGLIB$$ea6ee936.handleRequest(<generated>), com.alibaba.nacos.core.remote.grpc.GrpcRequestAcceptor.request(GrpcRequestAcceptor.java:179), com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.lambda$addServices$0(BaseGrpcServer.java:176), io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172), io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35), io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23), io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40), io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86), io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331), io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820), io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37), io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)

![企业微信截图_1672801958389](https://user-images.githubusercontent.com/53824889/210477481-c19a2247-fee6-4fe9-adde-b1584b704e47.png)

**Comment by MajorHe1** [comment]
猜想一下是不是 StringPool.get(groupKey) 把这个groupKey搞成null了
![企业微信截图_16728154575988](https://user-images.githubusercontent.com/53824889/210518165-fc58c65b-2648-4b98-b3fa-a70e059885da.png)
