### ISSUE TITLE
Nacos集群宕机一台节点，剩余两台数据不一致

### ISSUE THREAD

**Issue by guozongkang** [alibaba/nacos#9736]
Nacos不是高可用的么？为什么我们生产环境集群三台机器，宕机了一台，剩下的两台数据不一致啊  版本2.0.2.....

**Comment by guozongkang** [comment]
![1280X1280](https://user-images.githubusercontent.com/36061267/208805557-984df3d0-61a5-462d-8fab-a41d9e70fe97.JPEG)

**Comment by KomachiSion** [comment]
说明集群搭建可能有问题， 之前3台机器没有彻底组成集群，靠其中一台成为leader和中继维系，down机后现存活的两台没有被组成集群。

**Comment by KomachiSion** [comment]
另外看下双写等功能是否关闭。 如果其中一台关闭， 另一台没有关闭，也会导致这种情况。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
