### ISSUE TITLE
load schema.sql error错误

### ISSUE THREAD

**Issue by shining-stars-lk** [alibaba/nacos#9737]
**Describe the bug**
nacos运行中出现load schema.sql error错误
- 版本 2.0.3
- 只用到服务注册功能，没有用配置中心功能
- 使用的集群化配置，采用内置的数据库

**Expected behavior**
没有错误信息

**Actually behavior**
nacos运行中出现load schema.sql error错误

![Dingtalk_20221221134704](https://user-images.githubusercontent.com/40255310/208830967-ce575427-ea13-4c7f-8ae8-799f609dbe29.jpg)

**Comment by shining-stars-lk** [comment]
我看之前也有人提出了这个问题 https://github.com/alibaba/nacos/issues/3607

**Comment by godhth** [comment]
可能是文件系统出问题了
确认下这个目录是不是可读可写
nacos\data\derby-data

**Comment by shining-stars-lk** [comment]
已经替换成了mysql外置数据库，仍然报错

**Comment by shining-stars-lk** [comment]
已经替换成了mysql外置数据库，仍然报错

**Comment by KomachiSion** [comment]
新的错误信息是什么，如果还是这个错误说明没有切换成mysql数据库。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
