### ISSUE TITLE
derby db init error

### ISSUE THREAD

**Issue by ilbcj** [alibaba/nacos#9742]
open derby datasource error while the first time startup nacos in standalone mode.

operating environment :
Thu Dec 22 10:23:35 CST 2022:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance a816c00e-0185-37a4-91b6-000010800000 
on database directory /home/test/nacos220/data/derby-data with class loader org.springframework.boot.loader.LaunchedURLClassLoader@61832929 
Loaded from jar:file:/home/test/nacos220/target/nacos-server.jar!/BOOT-INF/lib/derby-10.14.2.0.jar!/
java.vendor=Oracle Corporation
java.runtime.version=11.0.14+8-LTS-263
user.dir=/home/test/nacos220/bin
os.name=Linux
os.arch=amd64
os.version=5.17.5-100.fc34.x86_64
derby.system.home=null
Database Class Loader started - derby.database.classpath=''

**How to Reproduce**
1. upload nacos-server-2.2.0.tar.gz to linux server,  the path is '/home/test'
2. unzip pacakge  'tar zxvf nacos-server-2.2.0.tar.gz'
3. change directory name 'mv  nacos  nacos220'
4. startup nacos  'cd nacos220/bin'  -- > './startup.sh  -m  standalone'

**Desktop (please complete the following information):**
 - OS: [Fedora release 34]
 - Version: [nacos-server-2.2.0]
 - Module: [naming/config]
 
**Additional context**
the error log info is:

> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 
> 2022-12-22 10:24:03,119 ERROR Application run failed
> 
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
>         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
>         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
>         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
>         at com.alibaba.nacos.Nacos.main(Nacos.java:35)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
>         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
>         at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
>         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
>         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
>         ... 27 common frames omitted
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
>         at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
>         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
>         ... 41 common frames omitted
>     Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'standaloneDatabaseOperateImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: load derby-schema.sql error.
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
>         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
>         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
>         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
>         at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
>         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
>         at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
>         at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
>         ... 55 common frames omitted
>     Caused by: java.lang.RuntimeException: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: load derby-schema.sql error.
>         at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:60)
>         at com.alibaba.nacos.config.server.service.repository.embedded.StandaloneDatabaseOperateImpl.init(StandaloneDatabaseOperateImpl.java:60)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
>         at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
>         ... 68 common frames omitted
>     Caused by: com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 500, errMsg: load derby-schema.sql error.
>         at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.reload(LocalDataSourceServiceImpl.java:100)
>         at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.initialize(LocalDataSourceServiceImpl.java:167)
>         at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.init(LocalDataSourceServiceImpl.java:83)
>         at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:49)
>         ... 76 common frames omitted
>     Caused by: java.sql.SQLTimeoutException: Login timeout exceeded.
>         at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
>         at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
>         at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
>         at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
>         at org.apache.derby.jdbc.InternalDriver.timeLogin(Unknown Source)
>         at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
>         at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
>         at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
>         at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
>         at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354)
>         at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
>         at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
>         at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554)
>         at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
>         at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
>         at com.alibaba.nacos.config.server.service.datasource.LocalDataSourceServiceImpl.reload(LocalDataSourceServiceImpl.java:95)
>         ... 79 common frames omitted
>     Caused by: org.apache.derby.iapi.error.StandardException: Login timeout exceeded.
>         at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
>         at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
>         ... 95 common frames omitted
>     2022-12-22 10:24:03,140 WARN [ThreadPoolManager] Start destroying ThreadPool
> 
>     2022-12-22 10:24:03,171 WARN [ThreadPoolManager] Destruction of the end

**Comment by ilbcj** [comment]
in my tests ,this bug occurs randomly.
sometimes, restart nacos the error will disappears,  
sometimes,  restart nacos the error is still there.

**Comment by ilbcj** [comment]
这个问题，反反复复open了很多次，#3607，#9321，#9737，能不能重视一下？

**Comment by KomachiSion** [comment]
这个问题是环境问题， login timeout是因为你本地环境问题导致derby数据库无法登陆导致的，你需要在你本地找出derby数据库启动的问题，通常是磁盘问题去解决。 社区大多数人无法复现该问题。只有能够复现的人排查下环境问题。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by Accelerator96** [comment]
@KomachiSion 我发现这个问题应该是derby还没启动 然后nacos就开始写入sql 导致的报错 
我使用默认的配置-Ddb.pool.config.connectionTimeout=30000 启动会报错
然后把时间改成60000之后就不会有问题
是不是可以把application里面默认的30000改成60000会好些

**Comment by Accelerator96** [comment]
@KomachiSion 我发现把db的connectionTimeout改成60000几乎可以100%的解决这个问题 
-Ddb.pool.config.connectionTimeout=60000
是不是可以考虑把默认的配置从30000上调到60000

**Comment by Qloop** [comment]
> @KomachiSion 我发现把db的connectionTimeout改成60000几乎可以100%的解决这个问题 -Ddb.pool.config.connectionTimeout=60000 是不是可以考虑把默认的配置从30000上调到60000
我也是暂时这么解决的，应该是环境问题 我们只有一个节点可以复现，大家有啥排查思路？derby的日志没有看到

**Comment by youngcle** [comment]
＠Qloop
赞，我刚试了，如你所说，正确答案。



我不认同＠KomachiSion的说法，
１、我用docker方式，就是为了屏蔽”环境问题”。
２、另外在我的机器上，2.1.1之前可以正常启动，后面就再也不行了，恰恰环境没变。我的硬件设备太过老旧？


这个问题在我的ubuntu上，下载jar包本地直接运行时，没有出现。
在windows wsl,docker desktop上，也没有。

在另一边
在nacos-group/nacos-docker那边有几个这issue，有说什么要写明ip的，总之都不管用。




如果docker-hub上镜像是社区官方发布的，我认为还是应该修复这个问题。

如果nacos社区认为　这问题不是问题，那么文档中应该更新，各个版本standalone模式对硬件环境有啥特殊要求，让使用者在上线之前自我检讨一下自己是不是目标用户。

**Comment by yanchaosb123** [comment]
> @KomachiSion 我发现把db的connectionTimeout改成60000几乎可以100%的解决这个问题 -Ddb.pool.config.connectionTimeout=60000 是不是可以考虑把默认的配置从30000上调到60000

这个参数在哪配置啊？ 我看环境变量不支持传递 JAVA_OPTS 啊

**Comment by dannyxu2015** [comment]
> > @KomachiSion 我发现把db的connectionTimeout改成60000几乎可以100%的解决这个问题 -Ddb.pool.config.connectionTimeout=60000 是不是可以考虑把默认的配置从30000上调到60000
> 
> 这个参数在哪配置啊？ 我看环境变量不支持传递 JAVA_OPTS 啊

参阅文档：https://nacos.io/en-us/docs/v2/guide/admin/system-configurations.html

我也碰到同样的问题，准备按照 @Accelerator96 的方法试试， 为何这个issue就这样草草被关闭了呢？？？

**Comment by dannyxu2015** [comment]
实测有效，不过改成60000还不够，我再加了个0，另外[文档](https://nacos.io/en-us/docs/v2/guide/admin/system-configurations.html)也有点旧了，不是startup.sh，而是docker-startup.sh。我用docker启动，版本是v2.4.3

启动命令：`docker run --name nacos -d -p 8848:8848 -p 9848:9848 -e MODE=standalone  -v /root/x.properties:/home/nacos/conf/application.properties -v /root/x.sh:/home/nacos/bin/docker-startup.sh nacos/nacos-server`

更改了docker-startup.sh：  
在`JAVA_OPT="${JAVA_OPT} -Dnacos.home=${BASE_DIR}"`后面增加了一行：  
`JAVA_OPT="${JAVA_OPT} -Ddb.pool.config.connectionTimeout=600000"`
