### ISSUE TITLE
篡改登录响应访问nacos后台漏洞

### ISSUE THREAD

**Issue by keep-learning-hub** [alibaba/nacos#9744]
### 描述
篡改登录响应实现nacos后台访问

### 版本
<=2.2.0

### 前提
可访问的nacos，且拥有所有权限的用户为nacos

### 实现前准备
1.下载安装并打开一个抓包软件，例如Charles，进入nacos后台登录页面，用户名和密码随便输入提交，在抓包软件上将nacos登录请求打上断点
2.登录一个已知nacos用户名和密码的nacos获取登录成功后的响应保存备用

### 实现步骤
1.进入nacos后台登录页面（不是之前获取响应的那台nacos），用户名和密码随便输入提交
![1671699972209](https://user-images.githubusercontent.com/58358777/209098476-265d61a4-72f0-4480-be9f-dd6748856d78.png)
2.请求放过，在响应中的Headers中将:status: 值修改为200,JSON Text值修改为已知nacos用户名和密码的nacos获取登录成功后的响应
![1671700067944](https://user-images.githubusercontent.com/58358777/209098769-b7b747a8-747b-4800-91c3-0105f9d44ce3.png)
![1671700198749](https://user-images.githubusercontent.com/58358777/209099485-e2111797-5d08-456f-8689-4b278865dc8e.png)
3.提交响应后即可进入nacos后台操作页面，可进行任何操作
![1671700347209](https://user-images.githubusercontent.com/58358777/209099679-05070040-b95e-48a1-82e6-57442f2772fd.png)

**Comment by karsonto** [comment]
nacos配置有开启鉴权？

**Comment by keep-learning-hub** [comment]
> nacos配置有开启鉴权？
有开启
nacos.core.auth.enabled=true

**Comment by tokyohost** [comment]
tokenTtl 过期之后就不行了吧，这好像就是tokenTtl存在的意义

**Comment by keep-learning-hub** [comment]
> tokenTtl 过期之后就不行了吧，这好像就是tokenTtl存在的意义

篡改上去的响应数据是我从别的nacos中获取的，比如本地，如果token过期也可以重复操作从而登录进去

**Comment by badx** [comment]
应该是nacos的jwt生成密钥都一样所以可以使用,所以篡改后可以使用
建议官方放开通过配置文件可配置token生成的key

**Comment by keep-learning-hub** [comment]
> 应该是nacos的jwt生成密钥都一样所以可以使用,所以篡改后可以使用 建议官方放开通过配置文件可配置token生成的key

其实是放开的，默认配置是这个
nacos.core.auth.plugin.nacos.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789

**Comment by badx** [comment]
> > 应该是nacos的jwt生成密钥都一样所以可以使用,所以篡改后可以使用 建议官方放开通过配置文件可配置token生成的key
> 
> 其实是放开的，默认配置是这个 nacos.core.auth.plugin.nacos.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789

嗯嗯,那就修改这个配置自定义Key就能避免这个问题了

**Comment by keep-learning-hub** [comment]
修改默认配置皆可避免
nacos.core.auth.plugin.nacos.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789

**Comment by AlienTQH** [comment]
https://nacos.io/zh-cn/docs/auth.html
按照官网进行了如下配置
`
NACOS_AUTH_ENABLE=true
NACOS_AUTH_TOKEN=字符串
`
还是可以按照题主的方式，进行登录操作呢，所以2.2.0还是没有解决这个问题吗

**Comment by keep-learning-hub** [comment]
> https://nacos.io/zh-cn/docs/auth.html 按照官网进行了如下配置 `NACOS_AUTH_ENABLE=true NACOS_AUTH_TOKEN=字符串` 还是可以按照题主的方式，进行登录操作呢，所以2.2.0还是没有解决这个问题吗

修改nacos.core.auth.enabled=true和nacos.core.auth.plugin.nacos.token.secret.key后是不能的，除非你知道配置的secret.key，之前能够成功的原因是两台nacos都没有修改secret.key

**Comment by keep-learning-hub** [comment]
> > > [nacos.io/zh-cn/docs/auth.html](https://nacos.io/zh-cn/docs/auth.html) 按照官网进行了如下配置 `NACOS_AUTH_ENABLE=true NACOS_AUTH_TOKEN=字符串` 还是可以按照题主的方式，进行登录操作呢，所以2.2.0还是没有解决这个问题吗
> > 
> > 
> > 修改nacos.core.auth.enabled=true和nacos.core.auth.plugin.nacos.token.secret.key后是不能的，除非你知道配置的secret.key，之前能够成功的原因是两台nacos都没有修改secret.key
> 
> 试过了, 用docker镜像的`NACOS_AUTH_TOKEN `配置后没有效果, 依然没修改默认秘钥, 镜像版本: 2.2.0

我测试是可以的哦,登录进去后因为token的问题导致获取配置的时候报token无效，你获取token的nacos和要篡改登录的nacos的key会不会是一样的
![1672883509671](https://user-images.githubusercontent.com/58358777/210683761-7d9e3ad7-7806-426a-9da2-b25cac5e3450.png)

**Comment by keep-learning-hub** [comment]
> > > > > [nacos.io/zh-cn/docs/auth.html](https://nacos.io/zh-cn/docs/auth.html) 按照官网进行了如下配置 `NACOS_AUTH_ENABLE=true NACOS_AUTH_TOKEN=字符串` 还是可以按照题主的方式，进行登录操作呢，所以2.2.0还是没有解决这个问题吗
> > > > 
> > > > 
> > > > 修改nacos.core.auth.enabled=true和nacos.core.auth.plugin.nacos.token.secret.key后是不能的，除非你知道配置的secret.key，之前能够成功的原因是两台nacos都没有修改secret.key
> > > 
> > > 
> > > 试过了, 用docker镜像的`NACOS_AUTH_TOKEN `配置后没有效果, 依然没修改默认秘钥, 镜像版本: 2.2.0
> > 
> > 
> > 我测试是可以的哦,登录进去后因为token的问题导致获取配置的时候报token无效，你获取token的nacos和要篡改登录的nacos的key会不会是一样的 ![1672883509671](https://user-images.githubusercontent.com/58358777/210683761-7d9e3ad7-7806-426a-9da2-b25cac5e3450.png)
> 
> 我就改了默认秘钥的最后一个数字, 感觉好像是nacos对过长的字符进行了截取(配置文档没写要填多少位), 导致修改没效果, 把秘钥改短后生效了

官网对该key的描述是推荐将配置项设置为Base64编码的字符串，且原始密钥长度不得低于32字符，没有对字符最大长度做描述，我刚才是直接在原始密钥上加了个0也是可以的

**Comment by Westbrookadmin** [comment]
楼主你提的这个问题去年就有人提过，具体是这个[issue](https://github.com/alibaba/nacos/issues/7182)。
但是昨天测试，生成jwt时，key随意填写，header跟payload不变，这种情况生成的jwt也可以进入后台，但是某些功能使用会受限；此外还发现了未授权漏洞。

**Comment by keep-learning-hub** [comment]
> 

具体是如何操作的，你说的和我的操作好像是一样的，但是在获取配置时会因token无效而返回到登录页面

**Comment by keep-learning-hub** [comment]
> 楼主你提的这个问题去年就有人提过，具体是这个[issue](https://github.com/alibaba/nacos/issues/7182)。 但是昨天测试，生成jwt时，key随意填写，header跟payload不变，这种情况生成的jwt也可以进入后台，但是某些功能使用会受限；此外还发现了未授权漏洞。

具体是如何操作的，你说的和我的操作好像是一样的，但是在获取配置时会因token无效而返回到登录页面

**Comment by Westbrookadmin** [comment]
> > 楼主你提的这个问题去年就有人提过，具体是这个[issue](https://github.com/alibaba/nacos/issues/7182)。 但是昨天测试，生成jwt时，key随意填写，header跟payload不变，这种情况生成的jwt也可以进入后台，但是某些功能使用会受限；此外还发现了未授权漏洞。
> 
> 具体是如何操作的，你说的和我的操作好像是一样的，但是在获取配置时会因token无效而返回到登录页面

是的，测试时用随意key生成的jwt可以进入后台，获取配置列表时没权限，但是可以查询节点列表以及命名空间，所以感觉危害有限。

**Comment by JavaAjust** [comment]
> > > > > [nacos.io/zh-cn/docs/auth.html](https://nacos.io/zh-cn/docs/auth.html) 按照官网进行了如下配置 `NACOS_AUTH_ENABLE=true NACOS_AUTH_TOKEN=字符串` 还是可以按照题主的方式，进行登录操作呢，所以2.2.0还是没有解决这个问题吗
> > > > 
> > > > 
> > > > 修改nacos.core.auth.enabled=true和nacos.core.auth.plugin.nacos.token.secret.key后是不能的，除非你知道配置的secret.key，之前能够成功的原因是两台nacos都没有修改secret.key
> > > 
> > > 
> > > 试过了, 用docker镜像的`NACOS_AUTH_TOKEN `配置后没有效果, 依然没修改默认秘钥, 镜像版本: 2.2.0
> > 
> > 
> > 我测试是可以的哦,登录进去后因为token的问题导致获取配置的时候报token无效，你获取token的nacos和要篡改登录的nacos的key会不会是一样的 ![1672883509671](https://user-images.githubusercontent.com/58358777/210683761-7d9e3ad7-7806-426a-9da2-b25cac5e3450.png)
> 
> 我就改了默认秘钥的最后一个数字, 感觉好像是nacos对过长的字符进行了截取(配置文档没写要填多少位), 导致修改没效果, 把秘钥改短后生效了

怎么生效的？ 我试了自定义token没用；用默认的token生成access_token还是可以访问
