### ISSUE TITLE
BeatReactor register an instance after the ephemecal instance is de-registered in some case

### ISSUE THREAD

**Issue by chndzcl** [alibaba/nacos#9746]
BeatReactor will create an persist instance after the  `deregisterInstance` in `NacosNamingService` class called.

According to the code in class `com.alibaba.nacos.client.naming.beat.BeatReactor` below:

```java
                if (code == NamingResponseCode.RESOURCE_NOT_FOUND) {
                    Instance instance = new Instance();
                    instance.setPort(beatInfo.getPort());
                    instance.setIp(beatInfo.getIp());
                    instance.setWeight(beatInfo.getWeight());
                    instance.setMetadata(beatInfo.getMetadata());
                    instance.setClusterName(beatInfo.getCluster());
                    instance.setServiceName(beatInfo.getServiceName());
                    instance.setInstanceId(instance.getInstanceId());
                    **instance.setEphemeral(true);**
                    try {
                        serverProxy.registerService(beatInfo.getServiceName(),
                                NamingUtils.getGroupName(beatInfo.getServiceName()), instance);
                    } catch (Exception ignore) {
                    }
```

However, a BeatTask is created only when the instance is ephemecal.

**Expected behavior**
Instance registered by BeatReactor should be a ephemecal instance.

```java
                if (code == NamingResponseCode.RESOURCE_NOT_FOUND) {
                    Instance instance = new Instance();
                    instance.setPort(beatInfo.getPort());
                    instance.setIp(beatInfo.getIp());
                    instance.setWeight(beatInfo.getWeight());
                    instance.setMetadata(beatInfo.getMetadata());
                    instance.setClusterName(beatInfo.getCluster());
                    instance.setServiceName(beatInfo.getServiceName());
                    instance.setInstanceId(instance.getInstanceId());
                    **instance.setEphemeral(false);**
                    try {
                        serverProxy.registerService(beatInfo.getServiceName(),
                                NamingUtils.getGroupName(beatInfo.getServiceName()), instance);
                    } catch (Exception ignore) {
                    }
```

**How to Reproduce**
1. Register an ephemecal instance using the nacos-client; 
2. Deregister the instance;
3. The issue occurs only when the deregister action is done when the BeatTask is performing the code below:

```java
        @Override
        public void run() {
            if (beatInfo.isStopped()) {
                return;
            }

            // the deregister instance is perform by other thread at this time
            long nextTime = beatInfo.getPeriod();
            try {
                // then the sendBeat will got RESOURCE_NOT_FOUND response
                JsonNode result = serverProxy.sendBeat (beatInfo, BeatReactor.this.lightBeatEnabled);
```

**Desktop (please complete the following information):**
 - OS: CentOS-7
 - Version nacos-client 1.4.2
 - Module naming
 - SDK original

**Comment by KomachiSion** [comment]
If you want to deregister an ephemecal instance, you should call deregister in `NacosNamingService` .

`NacosNamingService` will stop the beat task and them call deregister API to server.

**Comment by chndzcl** [comment]
@KomachiSion  I do deregister service by calling `deregisterInstance` in `NamingService`; part of the code is:

```java

import com.alibaba.cloud.nacos.NacosServiceManager;

    private final NacosServiceManager nacosServiceManager;

    public void deregisterInstance(String applicationName, String ip, Integer port) {
        try {
            this.nacosServiceManager.getNamingService(this.nacosProperties).deregisterInstance(applicationName, properties.getGroupName(), ip, port);
        } catch (NacosException e) {
            // ...
        }
    }
```

I found the following line in my log file:

```text
... [BEAT] removing beat: xxx:240.0.1.61:8080 from beat map.
```

And then the following log after the above line:

```text
... [REGISTER-SERVICE] DEFAULT registering service ... with instance: ..."
```

Actually, the deregister method in `NacosNamingService` will call `removeBeatInfo` in `BeatReactor` and set the  `stopped` variable to `true`; and then call the api of nacos server to deregister the instance.

But the BeatTask is not cancelled immediately. I think the BeatTask is running and will call nacos server to register the instance again. After the successful register of a non-ephemecal instance, the BeatTask won't be scheduled next round as it is stopped.

So, a instance is remain forever.

**Comment by KomachiSion** [comment]
There is no problem. Because the beat task has been removed, the temp registered instance will be removed.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
