### ISSUE TITLE
2.1.1版本，集群节点同步数据服务失败

### ISSUE THREAD

**Issue by shunfengli** [alibaba/nacos#9748]
java.lang.NoSuchMethodError: com.alibaba.nacos.api.grpc.auto.RequestGrpc.newFutureStub(Lcom/alibaba/nacos/shaded/io/grpc/Channel;)Lcom/alibaba/nacos/api/grpc/auto/RequestGrpc$RequestFutureStub;

**Comment by shunfengli** [comment]
![image](https://user-images.githubusercontent.com/45599246/209444444-4bfd6d5f-5344-4891-b9b3-cc46af49fcea.png)

**Comment by Daydreamer-ia** [comment]
依赖有问题

**Comment by Daydreamer-ia** [comment]
依赖有问题，或者是打包的时候有问题

**Comment by KomachiSion** [comment]
官方2.1.1包无法复现，是否是自己修改过依赖的版本然后编译的？

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by shunfengli** [comment]
谢谢，自己修改过依赖 导致出现依赖问题!

**Comment by shunfengli** [comment]
谢谢，自己修改过依赖 导致出现依赖问题!
Thank you, I modified the dependency, resulting in dependency problems!

**Comment by shunfengli** [comment]
谢谢，自己修改过依赖 导致出现依赖问题!
Thank you, I modified the dependency, resulting in dependency problems!
