### ISSUE TITLE
major gc的时间突然暴涨

### ISSUE THREAD

**Issue by yanyixin1993** [alibaba/nacos#9750]
nacos已经稳定运行了几个月了，但是今天看prometheus监控，凌晨5点的时候突然间这个major gc的时间暴涨了，重启所有nacos的机器也降不下来。由于是周末，所以可以确定没有操作过什么，为什么这个gc时间会瞬间暴涨呢？
PromQL的语句是: max(rate(jvm_gc_pause_seconds_count{action="end of major GC"}[5m])) * 300
<img width="448" alt="截屏2022-12-26 15 44 05" src="https://user-images.githubusercontent.com/22984307/209522005-fd0507cf-f1fc-43ec-8975-fa83c7afbd93.png">
而且我上机器上查gc的情况，显示的full gc次数是0?
![截屏2022-12-26 16 10 26](https://user-images.githubusercontent.com/22984307/209523178-f0574eba-0d27-43c4-abf8-aa73f21ca0ee.png)

**Comment by yanyixin1993** [comment]
十几个小时后又降了回去了，然后我看近一两个月的记录，发现半个月前也出现了这样的情况，飙高了一天，之后又降回去了，这是什么情况呢？

**Comment by KomachiSion** [comment]
有很多定期任务， 但是周期不会有半个月这样的， 最长间隔的是删除配置历史表的过期记录。间隔为一天。

major gc的监控可能吧ygc监控成major gc了，需要看下对应jdk版本是不是导致了监控统计的bug。或者是监控本身的bug。

nacos的gc监控复用的io.micrometer的gc监控，看下是否这个依赖版本有bug，有的话需要升级下 依赖版本。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
