### ISSUE TITLE
Docker version do not support LDAP

### ISSUE THREAD

**Issue by lucumt** [alibaba/nacos#9751]
Check `/home/nacos/config/application.properties` in nacos docker instance,we can find below configuration,it doesn't support `LDAP` feature(it says currrently only `nacos` is supported)
![image](https://user-images.githubusercontent.com/5226038/209527059-734ad933-b8f9-470f-88cb-8adf723a1463.png)

However,if we download the standard version of zip file,we can see it supports both `nacos` and `ldap`
![image](https://user-images.githubusercontent.com/5226038/209527586-44a3cbbd-43f0-4303-b71d-818774464a56.png)

So I am wondering if the docker version will support `LDAP` or not,thanks in advance!

**Comment by KomachiSion** [comment]
default docker is only support default plugin.

ldap need other configuration, but docker images not support for them.

If you want to use ldap plugin, you can build docker by yourself with changing the dockerfile in nacos-docker.

**Comment by lucumt** [comment]
@KomachiSion Yeah,I can build an image that support `LDAP` by myself,but many users have the same requirements,so I am wondering why not provide one? Thanks a lot.

**Comment by KomachiSion** [comment]
docker repo is only a demo and simple images for community, will not contain custom plugin. 

Any users or contributor can build their feature and plugin by themself, but can't force others use the images.
