### ISSUE TITLE
Nacos 2.1.0: Client not connected, current status:STARTING

### ISSUE THREAD

**Issue by hsiong** [alibaba/nacos#9758]
**Describe the bug**
我按照[版本匹配](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)配置了相关的依赖版本, 但是终端却提示`Client not connected, current status:STARTING`; 
> I tried the version as the [ Component version relationship](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E) shows, but the console reported that `Client not connected, current status:STARTING`; 

当我按照[cnblog](https://www.cnblogs.com/life-x-yk/articles/16186158.html)所示的将 Spring cloud alibaba 的依赖版本从 2.2.9.RELEASE 降到 2.2.6.RELEASE 后, 服务注册就正常了; 
> After i changed the version of Spring cloud alibaba from `2.2.9.RELEASE` to `2.2.6.RELEASE` as the [cnblog](https://www.cnblogs.com/life-x-yk/articles/16186158.html) shows , the service registry works fine; 

同时在完成一次服务注册以后, 再将 Spring cloud alibaba 的依赖版本改为 2.2.9.RELEASE, 就没有再出现 `Client not connected, current status:STARTING` 这个问题;
> Since the afore-mentioned steps completed, i changed the version of Spring cloud alibaba to `2.2.9.RELEASE`, and no further bug `Client not connected, current status:STARTING` had been reported.  

想要知道该问题出现的原因; 谢谢
> Hope someone to solve this question later. Thx

**Expected behavior**

**Actually behavior**

**How to Reproduce**

**Desktop:**
 - OS: MacOS 12.5.1
 - Version: 
    + Java: 17
    + Spring boot: 2.3.12.RELEASE
    + Spring cloud: Hoxton.SR12
    + Spring cloud alibaba: 2.2.9.RELEASE
    + Nacos: 2.1.0-slim
 - docker 
```shell
docker run -d --name nacos-standalone \
-e MODE=standalone \
-p 8848:8848 \
-p 9848:9848 \
-p 9849:9849 \
-d nacos/nacos-server:v2.1.0-slim
```

**Additional context**

**Comment by KomachiSion** [comment]
the error means your client can't connect to your server. please make sure your address is right and your 9848 port is listened.

**Comment by zhaoxinhu** [comment]
你好，我这边遇到了类似的问题。使用docker启动了一个nacos-server，并开放了9848端口，使用demo测试时，遇到了相同的错误。
具体错误可以参考issues：https://github.com/alibaba/nacos/issues/9810
可以帮忙看下具体什么原因吗？
我telnet了9848，是通的。
![image](https://user-images.githubusercontent.com/34291938/211236505-216afb4a-dbed-405d-b8da-7770c4a96811.png)
![image](https://user-images.githubusercontent.com/34291938/211236557-c7365ce7-0888-4e5a-b1f7-166a61ba9261.png)

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by hsiong** [comment]
> 你好，我这边遇到了类似的问题。使用docker启动了一个nacos-server，并开放了9848端口，使用demo测试时，遇到了相同的错误。 具体错误可以参考issues：#9810 可以帮忙看下具体什么原因吗？ 我telnet了9848，是通的。 ![image](https://user-images.githubusercontent.com/34291938/211236505-216afb4a-dbed-405d-b8da-7770c4a96811.png) ![image](https://user-images.githubusercontent.com/34291938/211236557-c7365ce7-0888-4e5a-b1f7-166a61ba9261.png)

在 docker 映射一下 9849 端口试试

**Comment by hsiong** [comment]
> 你好，我这边遇到了类似的问题。使用docker启动了一个nacos-server，并开放了9848端口，使用demo测试时，遇到了相同的错误。 具体错误可以参考issues：#9810 可以帮忙看下具体什么原因吗？ 我telnet了9848，是通的。 ![image](https://user-images.githubusercontent.com/34291938/211236505-216afb4a-dbed-405d-b8da-7770c4a96811.png) ![image](https://user-images.githubusercontent.com/34291938/211236557-c7365ce7-0888-4e5a-b1f7-166a61ba9261.png)

在 docker 中再多映射一个 9849 端口, 或许可以解决这个问题
> Mapping one more port `9849` in docker  may be solve this problem
