### ISSUE TITLE
Add postgresql as external data source support

### ISSUE THREAD

**Issue by cloorc** [alibaba/nacos#9760]
In our circumanstance, we've only used PostgreSQL as our relational database storage. So we need a postgres external data source support.

A possible solution is implementing new postgres mapper implementation to support it.

**Comment by KomachiSion** [comment]
duplicate with #9499

**Comment by dylan-tao** [comment]
目前我这边已经开源支持postgresql的nacos-2.2.0版本（已投产），可以直接食用：https://github.com/dylan-tao/nacos-gaussdb
