### ISSUE TITLE
prometheus nacos_monitor data exception

### ISSUE THREAD

**Issue by Accelerator96** [alibaba/nacos#9765]
prometheus

<img width="534" alt="image" src="https://user-images.githubusercontent.com/13599846/209920860-f6fe79db-5b55-40c2-94cb-0623400f9054.png">

 the nacos_monitor index 'avgPushCost' and 'maxPushCost' is always -1 

nacos-server 2.0.4

**Comment by KomachiSion** [comment]
If always -1 means your push never occurs.
