### ISSUE TITLE
数据备份

### ISSUE THREAD

**Issue by luohua13** [alibaba/nacos#9771]
statefulset 集群模式挂载 pv，如果进行冷备的话是不是只需要备份 data/naming 的数据就可以了？data/protocol, data/tps等目录内容是不是没用？我测试的结果是只备份 naming 目录数据然后 copy 到另外一套 nacos 的存储目录，数据都是正常的。如果 data/protocol, data/tps等目录内容没用，是不是不用持久化存储？只持久化 naming 目录就可以了？

**Comment by KomachiSion** [comment]
都有用， data/naming是旧版本部分数据的快照存放目录， data/protocol是jraft的日志及快照存放目录，data/tps是限流相关的配置存放目录。

如果你正好没有用到对应的内容，不持久化是可以的，但是一旦用到了就会丢失对应数据。具体是否备份依照您自己使用进行。

**Comment by luohua13** [comment]
好的，多谢 @KomachiSion

**Comment by luohua13** [comment]
@KomachiSion 或者我们会出冷备方案，更新到官方文档？
