### ISSUE TITLE
It is recommended that SQL statements be either all uppercase or all lowercase  Different databases have different SQL case requirements

### ISSUE THREAD

**Issue by beijixing1745** [alibaba/nacos#9780]
It is recommended that SQL statements be either all uppercase or all lowercase

Different databases have different SQL case requirements

example

final String sqlCount = "SELECT count(*) FROM config_info  a LEFT JOIN config_tags_relation b ON a.id=b.id";

recommend

final String sqlCount = "select count(*) from config_info  a left join config_tags_relation b on a.id=b.id"

or

final String sqlCount = "SELECT COUNT(*) FROM CONFIG_INFO  A LEFT JOIN CONFIG_TAGS_RELATION B ON A.ID=B.ID"

**Comment by KomachiSion** [comment]
It's not reasonable, some words like `SELECT` and `FROM` is keywords. So keep them uppercase to highlight.

some works like `config_info ` is a table name for nacos, use lowercase to make it clear.

For your said Different databases, The special SQL should be cased in databases plugins. Not in common or MySQL/Derby plugin.
