### ISSUE TITLE
grpc connection keep-alive mechanism question

### ISSUE THREAD

**Issue by xingdong015** [alibaba/nacos#9782]
When starting the grpc service in nacos, there is the following code

```
if (REQUEST_BI_STREAM_SERVICE_NAME.equals(call.getMethodDescriptor().getServiceName())) {
    Channel internalChannel = getInternalChannel(call);
    ctx = ctx.withValue(CONTEXT_KEY_CHANNEL, internalChannel);
}
```

Here, the underlying channel of grpc is obtained through reflection, but the acquisition of this channel has been discarded in the higher version of grpc.
I think this channel will eventually be encapsulated into grpcConnection, which is used to verify the legitimacy of the channel, ```isConnection``` and close ```close()```.
So how to implement the corresponding functions in the higher version of grpc?

In ConnectionManager, it checks the availability of connection and heartbeat detection (via ConnectionManager#refreshActiveTime) through scheduled tasks.

Here I would like to ask, why not use ```ServerBuilder.keepAliveTime()``` to keep the server connection alive? Let the connection status be handled by grpc?
Reference [https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md](url)

**Comment by KomachiSion** [comment]
For current depend grpc version, the connection is hided by grpc, so get channel and keep it by nacos to maintain the connection.

If the higher version can provide api to manage connection and can used by nacos, the reflection and maintain connection logic can be removed.

**Comment by xingdong015** [comment]
>
