### ISSUE TITLE
Why not webHook?

### ISSUE THREAD

**Issue by zhaoche27** [alibaba/nacos#979]
1. Why does the listener configuration (/nacos/v1/cs/configs/listener) change the way long connections are used instead of using the "Webhook" approach.

2. /nacos/v1/cs/configs/listener, not near real-time, with a maximum delay of 30 seconds

**Comment by ddatsh** [comment]
may be consider "old tech" compatibility
Webhook should use new url

**Comment by hxy1991** [comment]
I think this is a historical reason. Nacos will abstract the push channel in the future and support more communication methods.
