### ISSUE TITLE
错误：Server check fail, please check server 10.110.141.46 ,port 9848 is available , error ={}

### ISSUE THREAD

**Issue by beanlks** [alibaba/nacos#9791]
Nacos版本：2.2.0
使用docker单机运行，命令：docker run -e MODE=standalone --name nacos --net=host -d -p 8848:8848 -p 9848:9848 -p 9849:9849 -e SPRING_DATASOURCE_PLATFORM=mysql -e MYSQL_SERVICE_HOST=连接地址 -e MYSQL_SERVICE_DB_NAME=数据库名 -e MYSQL_SERVICE_PORT=端口 -e MYSQL_SERVICE_USER=账号 -e MYSQL_SERVICE_PASSWORD=密码 镜像id
容器是可以正常运行起来的。

docker部署在ip=10.110.141.46的服务器
应用服务部署在ip=10.110.141.44的服务器

在10.110.141.44的服务器去ping 10.110.141.44 9848是可以通的，端口都开放了

应用服务连接nacos就报错：Server check fail, please check server 10.110.141.46 ,port 9848 is available , error ={}

两个服务器都是在同一个局域网。

最终拉取不到nacos上面的配置。

**Comment by KomachiSion** [comment]
`Server check fail, please check server 10.110.141.46 ,port 9848 is available` 说明客户端尝试检查服务端是否正常失败了，环境问题需要自行排查下

**Comment by beanlks** [comment]
@KomachiSion 由于服务器是客户的，环境比较封闭，无法联网。我想宏观上大概定位一下问题，9848是grpc，会不会有可能是服务器没有http2功能，导致无法连接上9848？

**Comment by KomachiSion** [comment]
http2只是7层协议，和有没有功能没有关系， nacos server只要正确启动肯定是支持的，可以尝试在nacos server上部署一个简单demo，如果能够正常访问，那说明nacos没有问题，有问题的是外侧的网络环境。

**Comment by zgqq** [comment]
`docker stats` 看下占用内存，如果低于200M，就是启动失败了

**Comment by KomachiSion** [comment]
是client的配置直接设置了9848端口？

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
