### ISSUE TITLE
nacos springcloud alibaba the ribbon retry mechanism fails！

### ISSUE THREAD

**Issue by 65725738** [alibaba/nacos#9794]
NACOS2.0.4
        <spring-boot.version>2.3.12.RELEASE</spring-boot.version>
        <spring-cloud.version>Hoxton.SR12</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.7.RELEASE</spring-cloud-alibaba.version>

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 2

Ribbon configuration, MaxAutoRetriesNextServer: 2 this is not to take effect. What's the reason for this? Is there any special configuration required?

**Comment by KomachiSion** [comment]
Please move issue to SCA community
