### ISSUE TITLE
适配Oracle后 权限控制-权限管理功能报错（ORA-00936）

### ISSUE THREAD

**Issue by kookse** [alibaba/nacos#9796]
权限控制-权限管理功能报错（ORA-00936）：
查询语句为：SELECT role,resource,action FROM permissions WHERE 1=1
resource是保留关键字，这个问题是否只能通过修改nacos源代码解决了？

**Comment by KomachiSion** [comment]
默认鉴权插件只支持MySQL数据库， 需要开发自定义鉴权插件。

**Comment by dylan-tao** [comment]
> 权限控制-权限管理功能报错（ORA-00936）： 查询语句为：SELECT role,resource,action FROM permissions WHERE 1=1 resource是保留关键字，这个问题是否只能通过修改nacos源代码解决了？

自己给resource字段加双引号，然后打包。或者修改Oracle创建的库和表的字段均为大写即可解决。

另外：nacosplus针对多种数据库（包含信创数据库）提供支持，详见：https://github.com/dylan-tao/nacos-plus
