### ISSUE TITLE
在生产环境是否建议使用内置数据库derby？

### ISSUE THREAD

**Issue by frankywen** [alibaba/nacos#9800]
想尽量减少中间件的依赖，想在生产环境中直接使用内置数据库。
官方是否建议在生产环境集群下使用内置数据库？使用内置数据库的话，有什么需要注意的？

**Comment by karsonto** [comment]
生产环境肯定用外置数据库比较靠谱

**Comment by 985492783** [comment]
不建议使用内置数据库，换环境咋迁移数据

**Comment by frankywen** [comment]
> 

把derby-data目录迁移走就可以吧

**Comment by KomachiSion** [comment]
主要不推荐的原因：
1. 依赖Jraft，Jraft选主异常时不可读写，MySQL或外置数据库可以做主从切换来保持稳定性，但是Jraft超过半数就会有问题。
2. 磁盘压力，通常MySQL或外置数据库可以统一做高性能磁盘，而nacos一般只有少量持久化数据和日志，不需要过高性能的磁盘，如果走derby集群模式，需要性能较高的磁盘，且集群多大就需要多少个高性能磁盘，成本会比较高。
3. 数据查询不便， 通常MySQL或外置数据库可以通过其他手段进行连接（如cli，jdbc）然后查看数据，但derby没有，derby只能通过nacos暴露的一个执行SQL的接口执行一些操作或查看落地数据。

通常推荐测试或确定不是用配置中心时用derby，其他情况均使用外置数据库。

**Comment by lovejaychou** [comment]
> 主要不推荐的原因：
> 
> 1. 依赖Jraft，Jraft选主异常时不可读写，MySQL或外置数据库可以做主从切换来保持稳定性，但是Jraft超过半数就会有问题。
> 2. 磁盘压力，通常MySQL或外置数据库可以统一做高性能磁盘，而nacos一般只有少量持久化数据和日志，不需要过高性能的磁盘，如果走derby集群模式，需要性能较高的磁盘，且集群多大就需要多少个高性能磁盘，成本会比较高。
> 3. 数据查询不便， 通常MySQL或外置数据库可以通过其他手段进行连接（如cli，jdbc）然后查看数据，但derby没有，derby只能通过nacos暴露的一个执行SQL的接口执行一些操作或查看落地数据。
> 
> 通常推荐测试或确定不是用配置中心时用derby，其他情况均使用外置数据库。

使用MySQL，Nacos节点不也会全量拉取MySQL中的所有配置存储到本地嘛，磁盘成本也高吧

**Comment by HUWEIWEI0105** [comment]
> 主要不推荐的原因：
> 
> 1. 依赖Jraft，Jraft选主异常时不可读写，MySQL或外置数据库可以做主从切换来保持稳定性，但是Jraft超过半数就会有问题。
> 2. 磁盘压力，通常MySQL或外置数据库可以统一做高性能磁盘，而nacos一般只有少量持久化数据和日志，不需要过高性能的磁盘，如果走derby集群模式，需要性能较高的磁盘，且集群多大就需要多少个高性能磁盘，成本会比较高。
> 3. 数据查询不便， 通常MySQL或外置数据库可以通过其他手段进行连接（如cli，jdbc）然后查看数据，但derby没有，derby只能通过nacos暴露的一个执行SQL的接口执行一些操作或查看落地数据。
> 
> 通常推荐测试或确定不是用配置中心时用derby，其他情况均使用外置数据库。

如果是只用作注册中心是不是就没什么问题了，不使用raft进行读写，集群扩展性相对于使用外置数据库会有问题吗？
