### ISSUE TITLE
Nacos 2.1.2压测性能问题反馈

### ISSUE THREAD

**Issue by elvislou** [alibaba/nacos#9808]
各位好，日前我们对nacos2.1.2版本进行了性能测试，发现了一些问题，想请教一下如何排查：

### 环境：
linux 虚机， nacos服务端2.1.2  5个nacos节点  运行nacos的jvm -Xmx=10G tomcat_max_threads=4000

### 背景：
我们的nacos只用作dubbo(2.7.x)的注册中心，之前我们参考https://github.com/alibaba/nacos/issues/7302 这里的压测模型，对nacos服务端1.2.1进行了压测，得出的结论跟帖子里的差不多，就是nacos 1.2.1压测的上限大概是支持稳定的5.5~7万实例左右。
后面我们想用同样的场景和方法对nacos2.1.2进行压测，看看性能是否有所提升。

### 现象：
在针对2.1.2（5节点）做压测时，曾经能够支撑到9万实例稳定运行，有一两次压测做到了这个效果。
但是，在服务端没做任何改动的情况下，后面的压测情况就变了，在客户端实例数达到2.8w的时候就大量报错，并且重试了多次都是同样的现象，具体表现为：

1. 压测客户端出现大量的 java.net.SocketTimeoutException: Read timed out
2. 访问nacos的网页控制台出现卡顿，几乎不可访问。
3. 网页控制台上，集群管理出现不健康节点，出现了两个节点显示节点状态：DOWN
4. naming-server.log中出现大量类似如下报错：
     WARN Exception while request: https://nacos-app5:8080/nacos/v1/ns/instance/beat, caused:{}
java.net.SocketTimeoutException: Read timed out
     at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
      .....（这里堆栈就不一一列出了）
5. 查看了jvm内存使用和gc情况，是正常的，占用的内存并不多。

请大家帮忙看看这是不是2.1.2的稳定性问题，或者是bug？，有需要其他的信息可在comment中留言。

**Comment by KomachiSion** [comment]
1. 是否关闭双写。
2. Read timed out说明请求无法被及时响应，有可能是网络问题，也可能是服务端没有足够的worker线程处理，或者资源争抢导致处理速度跟不上，这方面需要根据使用情况和现场场景进行分析了。
3. 可以尝试升级nacos-client至2.1.2版本再尝试。

**Comment by elvislou** [comment]
1. 我从nacos的官方文档里看到从2.1.0起，双写是默认关闭的，我们是全新安装的集群，没有改过相关的配置，所以可以认为双写是关闭的吧？
2. 这点就是我们想向社区咨询的地方，可以从哪些日志或者哪些方法来分析这个问题，根据之前的经验，这个问题是服务端收到客户端heartbeat之后，在服务端节点之前转发的时候压力太大，处理不过来，导致的read timed out，但是1.2.1的版本的服务器性能明显好于2.1.2很多，这是我们不太好理解的地方。
3. 我们之所以采用1.x的client的模型进行压测，是因为目前生产环境已上线系统都采用的是1.xclient，这个暂时没法大规模升级，所以眼下还是得用1.x client。

**Comment by KomachiSion** [comment]
从我们的压测来看， 2.x对1.x的客户端的性能基本没有区别。

原理上，1.x的客户端请求都会经过责任节点判断并转发， 在判断责任节点时有一些区别，1.x服务端是以服务名来计算，2.x是ip：port来计算， 理论上能够排除热点服务导致某一台责任节点接受过多转发请求的热点问题。 在极端场景下应该比1.x还要更好。

对于你的压测场景， 应该需要额外再进行分析。

**Comment by KomachiSion** [comment]
另外可以看一下压测用例， 是否没有进行ip：port打散， 只进行服务名打散， 如果ip：port没有打散，压力会集中在某几台服务器上，那的确容易出问题。
