### ISSUE TITLE
java: 程序包com.alibaba.nacos.consistency.entity不存在

### ISSUE THREAD

**Issue by zhaoxinhu** [alibaba/nacos#9810]
我把项目拉到本地报错了。默认分支：develop。切换到master后同样的错误。
![image](https://user-images.githubusercontent.com/34291938/210973921-0073a194-d2af-49cb-bf18-dab8373ed737.png)

**Comment by YunWZ** [comment]
`mvn clean compile`编译一下

**Comment by zhaoxinhu** [comment]
编译过之后。还是报红，不过不影响demo测试了。

**Comment by zhaoxinhu** [comment]
测试过程中遇到了一个错误。
首先我在本地部署了一个nacos
![image](https://user-images.githubusercontent.com/34291938/211021654-d12c846d-1623-4bc5-87ed-03f856d24bee.png)

1、 我先测试getConfig。发现没有获取到config内容。截图如下：
![image](https://user-images.githubusercontent.com/34291938/211021915-5a75f53b-5199-47f3-879a-dcfb34d9ed7c.png)
2、 断点进入获取server的config方法中，报错如下：Client not connected, current status:STARTING
![image](https://user-images.githubusercontent.com/34291938/211022095-0cc43a77-9c51-441d-93d6-ab5c55e05ff3.png)

**Comment by zhaoxinhu** [comment]
看到有一个跟我类似的issues。发现回复说是9848端口没有开。我重启docker容器，开放了9848端口。开放如下：
![image](https://user-images.githubusercontent.com/34291938/211023445-1966e6a8-0952-4d72-b388-ef15a063aded.png)

重新测试后还是一样的错误

**Comment by wenbin-usr** [comment]
entity包中的类是需要通过protoc生成的，基于这两个proto文件
![QQ截图20230107132122](https://user-images.githubusercontent.com/83151102/211132576-762d0239-0554-4085-941a-b33beb134f8a.png)

**Comment by zhaoxinhu** [comment]
> entity包中的类是需要通过protoc生成的，基于这两个proto文件 ![QQ截图20230107132122](https://user-images.githubusercontent.com/83151102/211132576-762d0239-0554-4085-941a-b33beb134f8a.png)

好的，多谢解答

**Comment by gt2ming** [comment]
执行一遍就能跑通Junit

> mvn clean compile
