### ISSUE TITLE
arm64编译运行nacos 2.1.2的疑问

### ISSUE THREAD

**Issue by wuyad** [alibaba/nacos#9811]
官方目前还不支持arm64以及apple M1，实际在apple M1下编译的nacos 2.1.2也无法正常启动，但官方提供了arm64的docker镜像（nacos/nacos-server:v2.1.2-slim），说明是可以在arm64下编译运行的，此矛盾何解？

**Comment by YunWZ** [comment]
1. arm64下（苹果芯片），如果要本地运行，需要使用x86的jdk。

2. 估计下个版本会支持arm64平台

**Comment by gnmsss** [comment]
最新项目需要，为此开始使用微服务相关技术，中间件使用Nacos。开发操作系统是Mac M1 13.1版本，不管是本地运行，还是使用官方镜像，都有各种各样的问题，为此看到了很多帖子。我在这里提出几个疑问。
1: 阿里巴巴大厂，开源了自己的相关技术框架和中间件。对应两年的时间里，别的平台不说，首先说Mac M1操作平台上。至今还没有解决。我不知道为什么。难道阿里技术部门没有用Mac M1系统吗？如果有，为什么不能解决呢？是没有时间吗？
2: 在一枝独秀的微服务整套解决方案当中。官方针对mac arm64架构应该出来对应的相关版本。这对企业使用官方的Nacos也有推进作用。为此希望能得到官方的重视。

**Comment by KomachiSion** [comment]
1. 不支持M1 是rocksdb的问题，非nacos的，rocksdb目前应该已经支持，后续随jraft进行升级时应该就能支持上。
2. arm64架构同上。

**Comment by KomachiSion** [comment]
duplicate with #4336

**Comment by wuyad** [comment]
回复人没有注意关键的信息：官方提供了arm64的docker镜像（nacos/nacos-server:v2.1.2-slim），所以问题其实是：官方是如何在arm64下编译运行，从而build出docker镜像的？

**Comment by BR-Liu** [comment]
> 1. rocksdb

请问是在2.2.1版本吗？

**Comment by BR-Liu** [comment]
> 1. arm64下（苹果芯片），如果要本地运行，需要使用x86的jdk。
> 2. 估计下个版本会支持M1

请问是在2.2.1版本吗？

**Comment by YunWZ** [comment]
> > 1. arm64下（苹果芯片），如果要本地运行，需要使用x86的jdk。
> > 2. 估计下个版本会支持M1
> 
> 请问是在2.2.1版本吗？

2.2.1正式版尚未发布，你可以基于源码自己编译本地运行。

**Comment by BR-Liu** [comment]
> > > 1. arm64下（苹果芯片），如果要本地运行，需要使用x86的jdk。
> > > 2. 估计下个版本会支持M1
> > 
> > 
> > 请问是在2.2.1版本吗？
> 
> 2.2.1正式版尚未发布，你可以基于源码自己编译本地运行。

谢谢，我可以自行编译源码运行。另外请问下jraft已经发布的1.3.12版本已经完成了对m1的支持，nacos的2.2.1正式发布版本是否会将依赖升级至该版本？

**Comment by 774649283** [comment]
目前2.2.2还未解决M1/M2问题，镜像版本起不起来，本地脚本启动，导入配置按钮又没法用。
