### ISSUE TITLE
Mac M1 nacos/nacos-server最新版本启动后报错

### ISSUE THREAD

**Issue by gnmsss** [alibaba/nacos#9812]
系统：Mac M1 13.1 版本 
镜像:  nacos/nacos-server:latest    440657d52bc3   2 weeks ago     1.07GB
docker-compose.yml信息:
version: '3'
services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    networks:
      - inside
    environment:
      TZ: Asia/Shanghai
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_NAME: nacos
    volumes:
      - .logs/:/home/nacos/logs

networks:
  inside:
    external: true

错误日志:
 20:25:31.839 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
nacos  | com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: ErrCode:500, ErrMsg:Function not implemented
nacos  | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.loadPreProperties(StartingApplicationListener.java:164)
nacos  | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.environmentPrepared(StartingApplicationListener.java:107)
nacos  | 	at com.alibaba.nacos.core.code.SpringApplicationRunListener.environmentPrepared(SpringApplicationRunListener.java:60)
nacos  | 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
nacos  | 	at java.util.ArrayList.forEach(ArrayList.java:1259)
nacos  | 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
nacos  | 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
nacos  | 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
nacos  | 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:343)
nacos  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301)
nacos  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
nacos  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
nacos  | 	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos  | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos  | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
nacos  | Caused by: com.alibaba.nacos.api.exception.NacosException: java.io.IOException: Function not implemented
nacos  | 	at com.alibaba.nacos.sys.file.WatchFileCenter$WatchDirJob.<init>(WatchFileCenter.java:186)
nacos  | 	at com.alibaba.nacos.sys.file.WatchFileCenter.registerWatcher(WatchFileCenter.java:94)
nacos  | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.registerWatcher(StartingApplicationListener.java:170)
nacos  | 	at com.alibaba.nacos.core.listener.StartingApplicationListener.loadPreProperties(StartingApplicationListener.java:162)
nacos  | 	... 20 common frames omitted
nacos  | Caused by: java.io.IOException: Function not implemented
nacos  | 	at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
nacos  | 	at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
nacos  | 	at com.alibaba.nacos.sys.file.WatchFileCenter$WatchDirJob.<init>(WatchFileCenter.java:181)
nacos  | 	... 23 common frames omitted

**Comment by KomachiSion** [comment]
```
nacos | Caused by: java.io.IOException: Function not implemented
nacos | at sun.nio.fs.LinuxWatchService.(LinuxWatchService.java:64)
```
Your jdk problem, the exception is thrown by jdk, you should check your jdk env by yourself.
