### ISSUE TITLE
nacos1.4.1升级到2.2.0按照升级文档描述要开启双写。

### ISSUE THREAD

**Issue by Mnnuzhy** [alibaba/nacos#9815]
nacos1.4.1升级到2.2.0按照升级文档描述要开启双写，我配置文件没有配置nacos.core.support.upgrade.from.1x=true，为什么也能升级成功。数据存储模式为mysql。

**Comment by KomachiSion** [comment]
2.2.0已经不支持从1.x进行升级， changelog中已经描述， 文档还没有这方面的更新，可以提个PR帮助更新下文档

**Comment by yangmeiooo** [comment]
@KomachiSion ,
pls asign to me, first attend. Thanks!
@i will solve it@

**Comment by Daydreamer-ia** [comment]
i will resolve it
