### ISSUE TITLE
Nacos 2.1.1集群环境 springboot注册nacose服务不上去，服务列表为空

### ISSUE THREAD

**Issue by zijianlee** [alibaba/nacos#9817]
三个虚拟机搭建nacos2.1.1集群环境成功。集群管理-节点列表，可以见到三个主机的IP.
开始启动springboot，注册服务，提示注册成功。但是nacos控制台上，服务列表下为空，还是老问题一直存在。
到底这个nacos的集群环境还能用吗？

**Comment by KomachiSion** [comment]
控制台上没有服务，要么是命名空间错了， 要么是根本没注册。建议用纯净nacos-client进行一下注册，有可能是你应用有问题，没有发起注册。

或者到nacos-client的日志中查看是否有报错等信息（${user.home}/logs/nacos)

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by zijianlee** [comment]
不是应用的问题，还是你们的docker启动的命令缺少ip的事，按官网的命令，不成功

发自我的iPhone
