### ISSUE TITLE
nacos 2.2.0 版本，配置 nginx 反向代理时，无法通过 nginx 反向代理修改 nacos 密码

### ISSUE THREAD

**Issue by JRU1** [alibaba/nacos#9819]
Nginx 配置如下：

upstream nacos-server {
  server 172.31.1.186:8848 weight=1 max_fails=2 fail_timeout=30s;
  server 172.31.1.186:8850 weight=1 max_fails=2 fail_timeout=30s;
  server 172.31.1.186:8852 weight=1 max_fails=2 fail_timeout=30s;
}

server {
    listen       8000;
    server_name  localhost;
    charset utf-8;
    default_type text/html;

    location ~ /nacos/* {
        proxy_pass http://nacos-server;
        client_body_buffer_size 10M;
        client_max_body_size 10G;
        proxy_buffers 1024 4k;
        proxy_read_timeout 300;
        proxy_next_upstream error timeout http_404;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header User-Agent;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
    }
   
}

**Comment by YunWZ** [comment]
前端接收到的响应是什么呢？

**Comment by JRU1** [comment]
> 

1、 报 session expired!
![Uploading Snipaste_2023-01-09_18-07-02.png…]()


2、请求接口会报 401.
![Uploading Snipaste_2023-01-09_18-06-17.png…]()

**Comment by YunWZ** [comment]
看起来是个bug，目前修改密码时需要路由到同一个后端。

**Comment by YunWZ** [comment]
@i will resolve it@

**Comment by KomachiSion** [comment]
默认插件实现中，用户名相关信息是存储在session中的，nginx反向代理可能会导致多次请求处于不同的session中？

**Comment by YunWZ** [comment]
> 默认插件实现中，用户名相关信息是存储在session中的，nginx反向代理可能会导致多次请求处于不同的session中？

只有登陆接口会主动讲用户信息设置到session中，与此同时默认鉴权插件中基于spring-security实现的鉴权机制不起作用，导致其他服务端节点不存储session（只有接受了login请求的节点才存储session）

**Comment by JRU1** [comment]
为 Nginx 反向代理配置会话保持（添加 nginx-sticky-module 模块）后，会存在一些偶发性修改成功的情况，并不能保证每一次都修改成功。（基本上全部失败的，貌似会话保持没有生效）
upstream nacos-server {
       sticky;
       server 172.31.1.186:8848 weight=1 max_fails=2 fail_timeout=30s;
       server 172.31.1.186:8850 weight=1 max_fails=2 fail_timeout=30s;
       server 172.31.1.186:8852 weight=1 max_fails=2 fail_timeout=30s;
}

**Comment by YunWZ** [comment]
> 为 Nginx 反向代理配置会话保持（添加 nginx-sticky-module 模块）后，会存在一些偶发性修改成功的情况，并不能保证每一次都修改成功。（基本上全部失败的，貌似会话保持没有生效） upstream nacos-server { sticky; server 172.31.1.186:8848 weight=1 max_fails=2 fail_timeout=30s; server 172.31.1.186:8850 weight=1 max_fails=2 fail_timeout=30s; server 172.31.1.186:8852 weight=1 max_fails=2 fail_timeout=30s; }

如果用户登陆时请求发送到服务实例a，那么只有修改用户密码的请求被转发到实例a时才能成功。

如果继续修改用户密码，可以试下直接使用服务实例的地址访问控制台（而不是使用nginx的代理地址）
