### ISSUE TITLE
Question about ServerListManager(Nacos-client module)

### ISSUE THREAD

**Issue by YunWZ** [alibaba/nacos#9824]
**Is your feature request related to a problem? Please describe.**
I noticed that the `nacos-client` module has two different `ServerListManager` classes. But they have similar behavior.
`com.alibaba.nacos.client.config.impl.ServerListManager` and `com.alibaba.nacos.client.naming.core.ServerListManager`

BTW, I think it should be refactored.

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/8310

plan to uniq in 2.3.0
