### ISSUE TITLE
There is no problem with the nacos console. When I call another service, I will always report an error.

### ISSUE THREAD

**Issue by mybug99** [alibaba/nacos#983]
启动没什么错，注册中心也都有当调用别的服务，一会控制台就开始报错，我增加了个zipkin应该没什么问题吧但是之前是没问题的
![image](https://user-images.githubusercontent.com/43434812/55301684-650e0a00-5470-11e9-9454-0b4f9851d4fc.png)
![image](https://user-images.githubusercontent.com/43434812/55301693-76efad00-5470-11e9-876b-2be78768360b.png)

**Comment by mybug99** [comment]
我将zipkin的jar去掉以后就没有问题了，有人吗是不兼容了???

**Comment by mybug99** [comment]
有人吗？？？？？

**Comment by nkorange** [comment]
@mybug99 zipkin目前不支持Nacos，需要开发zipkin插件，我们尽快支持。
