### ISSUE TITLE
NacosException(NacosException.NOT_FOUND, "cluster " + clusterName + " is not found!");

### ISSUE THREAD

**Issue by 0utman1** [alibaba/nacos#9831]
https://github.com/alibaba/nacos/blob/97c5ac42e602f8264905ff9cc8cb67ca80d60ab1/naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java#L123
nacos server集群是2.0.3版本，3节点
client是1.3.3版本，查看client的注册信息的时候，catalog/instances接口会报错，刷新页面时有时无的，服务接口完全无法正常调用，Gateway报错404
经过排查发现有个server节点注册信息不正常，这个问题应该如何避免？

**Comment by KomachiSion** [comment]
应该是集群搭建有问题， 有一台节点和其他的节点没有组合正确的集群， 导致这部分数据没有同步过去。

部署的时候要check 每台节点上是否都正确识别了其他节点，可以通过控制台的集群管理， cluster/nodes接口和 core-cluster.log日志检查。

**Comment by fusiming** [comment]
我已经收到你的邮件，我稍后会给你回复。

**Comment by 0utman1** [comment]
只有个别的几个服务有此问题，大部分服务的注册信息都是正常的。
我们经过排查发现是集群中的一个节点没有此服务信息，经过重启后正常，使用nacos两年来，第一次遇到这个问题。
即便有一个节点有问题，其他两个节点也是正常的，gateway为何也没拿到注册信息呢？
此问题能否通过升级client版本的方式解决呢？

**Comment by KomachiSion** [comment]
首先不是client的问题，因为client不会调用catalog/instances接口， 这个是控制台接口。

另外1.X client版本主要是通过定时轮训获取服务实例， 如果获取到有问题节点上的数据， 那就会认为发生了变化，保留作为新列表，此时看到的现象应该是时有时无（网关测）

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
