### ISSUE TITLE
/nacos/v2/ns/instance 和  /nacos/v1/ns/instance的区别

### ISSUE THREAD

**Issue by pengkang1991** [alibaba/nacos#9833]
nacos版本：2.2.0
部署方式：docker-compose
是否集群：是
数据库：mysql8
今天突然发现/nacos/v2/ns/instance这个接口也能使用，如下： curl -X POST 'http://127.0.0.1:8848/nacos/v2/ns/instance?serviceName=APISIX-NACOS
但是用V2接口注册的服务在集群的其它节点却看不到，nacos/v1/ns/instance 注册的其它集群节点是能正常发现的，想请问一下，这个V2接口作用是啥，为啥V2接口注册的服务在集群的其它节点却看不到。
还有我是用dockers 方式部署的，但是官网上https://nacos.io/zh-cn/docs/v2/quickstart/quick-start-docker.html 这个文档丝毫没有提及部署前需要初始化SQL的事情，希望你们抽空能补充一下。还有后续如果我想升级到2.3.0+的版本，数据表结构如果有变化，我该如何升级？能不能参考一下Archery的升级文档，它的倒是蛮详细的：https://archerydms.com/installation/upgrade/

**Comment by KomachiSion** [comment]
1. v2接口和v1接口是都可以注册，注册的数据均可以互相发现，实际上走的数据流是一样的，只是对参数的校验，入参和返回有一定区别，其他服务无法发现一定是有内容没有对上，比如ns，比如group或者服务名。

2. 欢迎提交PR帮助优化文档。
