### ISSUE TITLE
注册服务的时候加上ephemeral=false这个参数服务就一直在，不加就很快消失

### ISSUE THREAD

**Issue by pengkang1991** [alibaba/nacos#9834]
nacos版本：2.2.0
部署方式：docker-compose
是否集群：是
数据库：mysql8

我看到官方文档上写的是ephemeral是默认为false的，但是奇怪的是
注册服务的时候加上ephemeral=false这个参数服务就一直在，不加就很快消失。
如下：
健康>不健康>很快消失：curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=APISIX-NACOS&ip=127.0.0.1&port=5555'
会一直为健康：curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=APISIX-NACOS&ip=127.0.0.1&port=5555&ephemeral=false'

**Comment by KomachiSion** [comment]
![image](https://user-images.githubusercontent.com/37170243/212227971-eb26c6ed-bf38-4159-be08-415460b18003.png)

文档时说的是非必选， 没有说默认值是false， 实际上默认值一直是true
