### ISSUE TITLE
【Question】Some questions about the body of Paydload object?

### ISSUE THREAD

**Issue by xingdong015** [alibaba/nacos#9840]
### In GrpcUtils.java there is the following code

```
    public static Payload convert(Request request) {
        
        Metadata newMeta = Metadata.newBuilder().setType(request.getClass().getSimpleName())
                .setClientIp(NetUtils.localIP()).putAllHeaders(request.getHeaders()).build();
        
        byte[] jsonBytes = convertRequestToByte(request);
        
        Payload.Builder builder = Payload.newBuilder();
        
        return builder
                .setBody(Any.newBuilder().setValue(UnsafeByteOperations.unsafeWrap(jsonBytes)))
                .setMetadata(newMeta).build();
        
    }
```

For example, when the service is registered, the request param type is InstanceRequest.

What I want to ask is why not serialize the InstanceRequest into a pb object and set it in the payload. Instead, convert it to json and put it in the payload.

**Comment by KomachiSion** [comment]
similar reason in https://github.com/alibaba/nacos/pull/9805.

**Comment by KomachiSion** [comment]
Grpc connection use pb, but other connection implementation maybe not.
