### ISSUE TITLE
nacos client 2.1.0 will tranform https to http compulsorily

### ISSUE THREAD

**Issue by withbluebell** [alibaba/nacos#9842]
**Describe the bug**
When my springcloud application uses Nacos Server 2.1.1 as a config server, 
I define the pom with Springboot 2.3.12.RELEASE, and SpringCloud Hoxton.SR12, and spring-cloud-starter-alibaba-nacos-config 2.2.9.RELEASE(whitch  nacos-client 2.1.0 included)，when I define this property [spring.cloud.nacos.config.server-addr] with prefix https, it will transform https to http in class [ServerListManager] line 198

this is the bug here

**Comment by KomachiSion** [comment]
which `ServerListManager`?
