### ISSUE TITLE
NamingService still return UP though user auth failed

### ISSUE THREAD

**Issue by AlbumenJ** [alibaba/nacos#9852]
**Describe the bug**
NamingService still return UP though user auth failed

**Expected behavior**
Return "DOWN"

**Actually behavior**
Return "UP"

**How to Reproduce**
1. Create a naming service client with wrong username or password
2. test `namingService.getServerStatus`
3. See result

**Comment by KomachiSion** [comment]
The feature has no problem, the ServerStatus means the server status whether up. When you login fail or auth fail means server is UP only your user and password not right, which not server problem, but your app problem.

So the status return UP is right. return DOWN is bug.

**Comment by ikhtearalamshawonmollah54321** [comment]
> **Describe the bug** NamingService still return UP though user auth failed
> 
> **Expected behavior** Return "DOWN"
> 
> **Actually behavior** Return "UP"
> 
> **How to Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a naming service client with wrong username or password
> 2. test `namingService.getServerStatus`
> 3. See result

Duplicate of #
