### ISSUE TITLE
手动点击下线dubbo provider服务后，consumer仍然可以调通

### ISSUE THREAD

**Issue by lidaoyang** [alibaba/nacos#9854]
手动点击下线dubbo provider服务后，consumer仍然可以调通。
dubbo版本:3.1.4
nacos-client:2.1.0
nacos-server:2.2.0

操作步骤：
nacos控制台-服务列表，点击provide 服务详情-点击下线
到页面访问接口仍然可以访问

**Comment by KomachiSion** [comment]
唯一的一个provider下线可能触发了dubbo的推空保护，或者看下是否开启了nacos的推空保护。

**Comment by lidaoyang** [comment]
> 唯一的一个provider下线可能触发了dubbo的推空保护，或者看下是否开启了nacos的推空保护。

推空保护在哪里看

**Comment by KomachiSion** [comment]
1. 看下是否开启了nacos的推空保护， 在配置文件中是否有`namingPushEmptyProtection=true`
2. dubbo3 有自己的推空保护，具体请到dubbo社区询问。
