### ISSUE TITLE
nacos 2.0.0 grpc端口可以通过配置文件配置吗?

### ISSUE THREAD

**Issue by saiyujs** [alibaba/nacos#9856]
因为服务器端口开放有限制，grpc默认的端口是主端口+1000、1001，能否通过配置文件动态配置？

**Comment by wuchubuzai2018** [comment]
应该是不行的，只能修改偏移量的大小，把默认的1000,1001的偏移量修改下

**Comment by PRANRAVEE** [comment]
XpressLoan-workingcapital_csa.pdf
<https://drive.google.com/file/d/1MLKWJyCx3pa1bsf3QlBpY2EuV2NMliEY/view?usp=drivesdk>

  888221000449.pdf
<https://drive.google.com/file/d/1KOdAfSUzbyJt9MZ9-z5aa8zSRUbTXqR7/view?usp=drivesdk>

  http://www.free.txt
<https://drive.google.com/file/d/1FhX4J_grKxgHnlEtL5PBy3VqhWgeRg4V/view?usp=drivesdk>

  GitHub-Mark.zip
<https://drive.google.com/file/d/146r7_S0jdxBrC3-3Nk2lA6lP6bm4iiY9/view?usp=drivesdk>

  freewallet_transactions
<https://docs.google.com/spreadsheets/d/12Q3geBOZy9xpEMohjdthHlpfy7YNNuWG/edit?usp=drivesdk&ouid=104014003129866457997&rtpof=true&sd=true>

  eth:0xcb7eee9c3.txt
<https://drive.google.com/file/d/1IOlsCZHKzbWNHE4HqGvA-tXkMTMqfi9h/view?usp=drivesdk>

  EPR00104923011.PDF
<https://drive.google.com/file/d/1dPRuD66PDT9CoRdldWhwv43iiIoUqZgn/view?usp=drivesdk>

  Dividend Payment_KKP SMART MV.xlsx
<https://docs.google.com/spreadsheets/d/10Tm2qhGrFikQ1LwenV6ofqVeRRSjuOlk/edit?usp=drivesdk&ouid=104014003129866457997&rtpof=true&sd=true>

  EPR02042830106.PDF
<https://drive.google.com/file/d/1cPDE1O0CF-euV42EPstgQjf_mjerXWU1/view?usp=drivesdk>

  20220524-true-investor_kit-packet.zip
<https://drive.google.com/file/d/14UInrLnHclExp0d0kpFdSQKv00UralY7/view?usp=drivesdk>


ในวันที่ ส. 28 ม.ค. 2023 08:43 杨翊 SionYang ***@***.***>
เขียนว่า:
