### ISSUE TITLE
Nacos organized the exception throwing for some reason

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/nacos#9857]
### env
Please See https://github.com/yuluo-yx/spring-boot-2.7.7-.git

### question
The exception is processed by listeners and rethrown by Spring Boot as expected, but I think that something with nacos is preventing this exception from being reported and failing the app properly. I'm closing this issue as this doesn't look related to Spring Boot. Please reach out to the nacos community about this. Feel free to reopen this issue if you manage to reproduce this problem without nacos being involved.

### retition
run `service-exam.tx.edu.cn`, And change the configuration file to test, prod, dev, and run the test separately

**Comment by KomachiSion** [comment]
I can't open your repository, and your description has no key meaning so that community can't understand your problem.

**Comment by yuluo-yx** [comment]
Thank you very much. I created a new project and solved the problem

> I can't open your repository, and your description has no key meaning so that community can't understand your problem.
