### ISSUE TITLE
org/slf4j/impl/StaticLoggerBinder not found

### ISSUE THREAD

**Issue by Bin1993** [alibaba/nacos#9860]
**Describe the bug**
I am using springboot 3.0.1 , nacos 2.2.1 RC, when i startup , the console print "NacosLogging    Load Logback Configuration of Nacos fail, message: org/slf4j/impl/StaticLoggerBinder", I have inspect nacos code, I found that StaticLoggerBinder usually offers by Logback or Log4J, but the springboot 3.0.1 default import logback  1.4.5, it doesn‘t offer StaticLoggerBinder. So I think, nacos should adapter for logback 1.4.5

**Expected behavior**
"NacosLogging    Load Logback Configuration of Nacos fail, message: org/slf4j/impl/StaticLoggerBinder", this warning dong't show again.

**How to Reproduce**
use springboot 3.0.1

**Comment by YunWZ** [comment]
refer [this issue](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/471) :

spring-boot 3.0 dependency`Logback 1.4`, so you needed to explicitly downgrade logback-core and logback-classic to 1.2.10.

**Comment by PRANRAVEE** [comment]
ในวันที่ อ. 17 ม.ค. 2023 13:13 Bin1993 ***@***.***> เขียนว่า:

**Comment by Torboxin** [comment]
我尝试依靠jvm的类加载机制解决，就像logback提供StaticLoggerBinder的时一样但效果并不理想，项目中多个模块都需要添加com.alibaba.nacos.client.logging.logback.LogbackNacosLogging包与类并重写loadConfigurationOnStart()方法获取LoggerContext对象的片段代码，这让我感到非常的繁琐。

**Comment by hujun-w-2** [comment]
正在适配中
