### ISSUE TITLE
ldap login，nested exception is javax.naming.PartialResultException: Unprocessed Continuation Reference(s); remaining name '/'

### ISSUE THREAD

**Issue by ylq5126** [alibaba/nacos#9862]
**Describe the bug**
使用ldap 登陆时，需要支持配置LdapTemplate选项ignorePartialResultException 为true

when use ldap authentication， should support LdapTemplate ignorePartialResultException configuration

LdapTemplate  ignorePartialResultException 
org.springframework.ldap.PartialResultException: Unprocessed Continuation Reference(s); nested exception is javax.naming.PartialResultException: Unprocessed Continuation Reference(s); remaining name '/'

nacos ldap config 
nacos.core.auth.ldap.url=ldap://localhost:389
nacos.core.auth.ldap.basedc=DC=example,DC=org
nacos.core.auth.ldap.userDn=admin@example.org
nacos.core.auth.ldap.password=admin
nacos.core.auth.ldap.filter.prefix=sAMAccountName
nacos.core.auth.ldap.case.sensitive=true

**Desktop (please complete the following information):**
 - OS: windows  JDK17
 - nacos-server 2.2.0
 - spring-cloud-alibaba-nacos

**Comment by karsonto** [comment]
@i will solve it@
