### ISSUE TITLE
 nacos-client get changed dataId error, code: 400

### ISSUE THREAD

**Issue by WuGuozhi** [alibaba/nacos#9874]
服务运行一段时间之后个别服务自动重启，打印日志 
[com.alibaba.nacos.client.Worker.longPolling.fixed-nacos-standalone-svc_8848-ccbb8bac-4ba2-4dc1-95bf-036646a1cd15] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-nacos-standalone-svc_8848-ccbb8bac-4ba2-4dc1-95bf-036646a1cd15] [check-update] get changed dataId error, code: 400

nacos-server 2.0.2
nacos-client 1.4.1 
spring-cloud-alibaba-nacos 2021.1

期间Nacos-server 无异常。10-20天会发生1-5次
重启之后应用服务为下线状态。需要手动上线。

**Comment by KomachiSion** [comment]
1. 长轮训监听的偶尔失败可以忽略，不影响任何内容（可以理解为定期30s对帐偶尔超时一次）
2. 重启应用后为下线状态，看下是否在停止的时候调用了下线接口，参考openAPI更新实例中的说明，更新实例状态有保留时间。
3. 如果没有下线接口调用，那就是注册的时候注册成了下线状态，无论哪种，都需要在应用ready之后再次调用上线接口来运维完整性。

**Comment by sixsixsix516** [comment]
请将 nacos-server 与 nacos-client 版本保持一致

出现该问题原因是：

**NacosClient 1.4.1** 版本请求 /listener 接口为 POST 方式
```java
  HttpRestResult<String> result = agent
                    .httpPost(Constants.CONFIG_CONTROLLER_PATH + "/listener", headers, params, agent.getEncode(),
                            readTimeoutMs);
```

而 **NacosServer 2.0.2** 版本的 /listener 接口为 GET 方式

```java
    @GetMapping("/listeners")
    public JsonNode getAllListeners(HttpServletRequest request, HttpServletResponse response) {
        if (versionJudgement.allMemberIsNewVersion()) {
            throw new IllegalStateException("old raft protocol already stop");
        }
        ObjectNode result = JacksonUtils.createEmptyJsonNode();
        Map<String, ConcurrentHashSet<RecordListener>> listeners = raftCore.getListeners();
        
        ArrayNode listenerArray = JacksonUtils.createEmptyArrayNode();
        for (String key : listeners.keySet()) {
            listenerArray.add(key);
        }
        result.replace("listeners", listenerArray);
        
        return result;
    }
```

**Comment by KomachiSion** [comment]
> ```java
> listeners
> ```

不是同一个接口，一个是监听接口，一个是查询监听者接口。

**Comment by WuGuozhi** [comment]
分析整体问题：
1.长轮训监听的偶尔失败
2.失败后服务健康状态down
3.K8S 健康检测 10/s 次，连续3次标记失败，重启服务。


1.停止的时候确认调用了下线接口，已经调整实例状态有保留时间。
2.调整 k8s 探活时间为30秒 防止因[长轮训监听的偶尔失败] 导致服务重启
