### ISSUE TITLE
集群中一个节点内存持续增高

### ISSUE THREAD

**Issue by shunfengli** [alibaba/nacos#9878]
我目前使用的集群有三个节点，其中一个节点（其它两个节点正常）随着时间增加 内存会持续增高，目前不知道造成该问题的原因，请教下是否遇到过该问题，或给个解决思路！
The cluster I'm currently using has three nodes, one of which (the other two are fine) will continue to grow in memory over time, and I don't know what's causing this problem,Ask if you have encountered the problem, or give a solution ideas!

**Comment by KomachiSion** [comment]
什么内存持续增高？

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
