### ISSUE TITLE
如何关闭心跳日志，路径（C:\Windows\System32\config\systemprofile\logs\nacos）下的config.log和naming.log两个文件

### ISSUE THREAD

**Issue by alvhui0914** [alibaba/nacos#9880]
C盘路径（C:\Windows\System32\config\systemprofile\logs\nacos）下的config.log和naming.log两个文件，怎么不让往这里写日志，或者减少变大的速度

**Comment by KomachiSion** [comment]
1. 日志文件最大10M ，会自动轮转。
2. 心跳日志为debug日志，说明你把日志级别开成了debug，nacos默认是info
3. 可以修改日志的输出位置，具体根据你使用的版本，查看nacos-client.jar中 nacos-logback.xml 或 nacos-log4j.xml的配置。

**Comment by alvhui0914** [comment]
1.日志文件没有自动轮转，一直增大
2.这个没有设置，一直是默认的
3.我想的事不产生日志，换个位置还是很大




刘文政
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] 如何关闭心跳日志，路径（C:\Windows\System32\config\systemprofile\logs\nacos）下的config.log和naming.log两个文件 (Issue #9880)





  
日志文件最大10M ，会自动轮转。
 
心跳日志为debug日志，说明你把日志级别开成了debug，nacos默认是info
 
可以修改日志的输出位置，具体根据你使用的版本，查看nacos-client.jar中 nacos-logback.xml 或 nacos-log4j.xml的配置。

**Comment by KomachiSion** [comment]
版本信息缺失，可以升级版本试试，最新版本肯定是会轮转的，除非有自己的设置。
心跳日志是debug，如果未设置不会打印， 既然打印了一定有地方修改了设置。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
