### ISSUE TITLE
UI中新增配置可以折叠代码，编辑配置折叠代码功能失效

### ISSUE THREAD

**Issue by zhaobingss** [alibaba/nacos#9881]
**Describe the bug**
UI中新增配置可以折叠代码，编辑配置折叠代码功能失效

**Expected behavior**
编辑配置也可以折叠代码

**Actually behavior**
编辑配置不可以折叠代码

**How to Reproduce**
1. 新建配置
<img width="987" alt="image" src="https://user-images.githubusercontent.com/14836112/215687829-aafd7df4-8bde-40fe-8e88-77630550588c.png">
3. 保存配置
4. 编辑配置
<img width="898" alt="image" src="https://user-images.githubusercontent.com/14836112/215688155-963c083f-16ad-4645-b2d6-8362a9a4918d.png">

**Desktop (please complete the following information):**
 - OS: []
 - Version [nacos-server 2.2.0]
 - Module []
 - SDK []

**Additional context**

**Comment by caixiaomao** [comment]
@i will solve it@

**Comment by caixiaomao** [comment]
@ready to close@
