### ISSUE TITLE
k8s 的 docker 环境下  nacos2.0.4 内存一直在不停增加！最后k8s自动重启nacos应用

### ISSUE THREAD

**Issue by fengcheche** [alibaba/nacos#9883]
注册的实例数据大概在40个，spring cloud alibba2021.1。

**Describe the bug**
![image](https://user-images.githubusercontent.com/7406807/215932386-d5dfa421-5303-42dc-aea7-b8aa0d125f54.png)

dump文件
![image](https://user-images.githubusercontent.com/7406807/215932814-88eeff58-01a0-4a49-9c95-df5d1cceda43.png)

对象实例大小
![image](https://user-images.githubusercontent.com/7406807/215933841-5ce6699a-e60d-46a6-b153-dc83fa297d0f.png)

![image](https://user-images.githubusercontent.com/7406807/215933780-138d6571-fc58-4591-a667-ffe387839541.png)

对象实例数
![image](https://user-images.githubusercontent.com/7406807/215933527-4e61147f-4dfd-433a-b6a1-5433a9d8cd4c.png)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
1. jvm参数如何设置， pod的limit和request如何设置
2. dump的截图中没找到泄漏点，对象大小占比都不是很大。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
