### ISSUE TITLE
nacos 1.0.0 版本性能测试报告

### ISSUE THREAD

**Issue by qnnn** [alibaba/nacos#9887]
## Issue Description
各位老师好，关于Nacos1.0.0性能测试结果有一些疑问，如在查询实例接口的性能压测中，此处的tps与注册实例数的关系是什么呢，客户端sdk默认情况下每3秒查询一次实例，tps为13604时，是否3秒内只能处理40812个客户端查询实例的请求，类似40812个实例查询。不清楚我理解的是否正确，辛苦各位老师解答。
![image](https://user-images.githubusercontent.com/65326092/215991882-9511dce9-7bd6-4262-affa-8c74ee8ac1e5.png)

**Comment by KomachiSion** [comment]
单次查询的数据量会影响tps，比如一个服务10000个实例和1个服务10个实例， 查询的rt会不同，从而导致tps会不同。

> 客户端sdk默认情况下每3秒查询一次实例，tps为13604时，是否3秒内只能处理40812个客户端查询实例的请求，类似40812个实例查询。

基本可以这么理解。

**Comment by qnnn** [comment]
> 单次查询的数据量会影响tps，比如一个服务10000个实例和1个服务10个实例， 查询的rt会不同，从而导致tps会不同。
> 
> > 客户端sdk默认情况下每3秒查询一次实例，tps为13604时，是否3秒内只能处理40812个客户端查询实例的请求，类似40812个实例查询。
> 
> 基本可以这么理解。

好的，感谢老师解答。还有一个地方不太懂，在Nacos1.0.0版本配置模块压测报告中，测试环境的虚机是8C16G的，但是为应用设置的堆内存大小却只有4G，这是为什么呢，在非堆内存的使用上会占用很多吗。
![image](https://user-images.githubusercontent.com/65326092/216219319-3f719481-91b7-433a-aa76-43094423273e.png)

**Comment by KomachiSion** [comment]
应该是写错了吧，正常应该至少堆总数是总内存的一半。

**Comment by qnnn** [comment]
> 

好的老师。如果用4C8G的虚机搭建nacos1.4.x集群，在JVM参数设置和tomcat配置上有什么最佳实践吗。

**Comment by KomachiSion** [comment]
具体需要根据你自己的实际情况设置。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.
