### ISSUE TITLE
使用 feign 扩服务调用时，无法 获取到 nacos 上的 服务

### ISSUE THREAD

**Issue by dyhyao6** [alibaba/nacos#9891]
日志信息：
![image](https://user-images.githubusercontent.com/49445844/216248942-b3f5242e-5435-4733-be0f-51a1dbf21dbd.png)
代码示例：
![image](https://user-images.githubusercontent.com/49445844/216249030-2ce59c9d-62d3-4d51-8b1d-6b62734a3089.png)
nacos 注册中心 服务注册信息：
![image](https://user-images.githubusercontent.com/49445844/216249186-b82a7e85-a220-48c9-84d5-607ddaf42755.png)
在我的项目里跨服务调用都无法使用，感觉是 nacos 服务不正常
@jun1st @zhfish @mercyblitz

**Comment by KomachiSion** [comment]
注册中心有服务， 消费者没有使用，大概率是消费者应用有问题。

要不然是配置有问题，确认命名空间，group和服务名是否完全一致。

或者是feign的问题，可以看下消费者应用所在节点的${user.home}/logs/naming.log 看下有没有订阅对应服务，订阅之后有没有收到对应服务列表。

**Comment by dyhyao6** [comment]
> 注册中心有服务， 消费者没有使用，大概率是消费者应用有问题。
> 
> 要不然是配置有问题，确认命名空间，group和服务名是否完全一致。
> 
> 或者是feign的问题，可以看下消费者应用所在节点的${user.home}/logs/naming.log 看下有没有订阅对应服务，订阅之后有没有收到对应服务列表。

服务是单节点，nacos 和 服务都是部署在同一台机器上的,并且都是一个实例， ${user.home}/logs/naming.log 这个日志 指的是 消费者自己的服务日志吗，还是 nacos 的日志 ？

**Comment by KomachiSion** [comment]
消费者所在节点上的nacos-client日志

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
