### ISSUE TITLE
修改配置后内存飙升到百分百导致服务器崩溃

### ISSUE THREAD

**Issue by goooool** [alibaba/nacos#9894]
修改nacos的配置之后内存就开始稳定上升直到七点四十左右近百分之百导致连接失败。
![image](https://user-images.githubusercontent.com/56424910/216506238-3c96e738-84d1-4abb-9448-dcbe967a02a1.png)
后面重启服务器就正常了。
会和之前客户端版本从2.1.2改为了2.0.4，但订阅者里却还有两个版本的信息有关吗？
![image](https://user-images.githubusercontent.com/56424910/216506534-e6a90ced-e267-4366-b3b5-cc650462f3b9.png)

**Comment by KomachiSion** [comment]
是服务端上升还是客户端？

**Comment by goooool** [comment]
服务端

**Comment by KomachiSion** [comment]
客户端需要你自己分析使用了， 是不是有错误的使用或者配置刷新后你的应用自己有内存泄漏。

**Comment by goooool** [comment]
![image](https://user-images.githubusercontent.com/56424910/217197536-df039e42-f80b-432f-8bea-58c88e98c0a6.png)
那像这种实际只起了一个应用但是订阅者列表有不同版本的两个客户端是这么回事？是修改版本后会有缓存吗？

**Comment by KomachiSion** [comment]
旧的链接已经关闭了嘛？ 可以到这个地址上，看一下有多少9848的链接。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
