### ISSUE TITLE
更新实例信息接口增加metadata则接口400

### ISSUE THREAD

**Issue by jwrwst** [alibaba/nacos#9896]
**Describe the bug**
更新实例信息，带上metadata元数据更新直接400，postman和java代码请求效果相同
地址示例：http://192.168.1.124:8848/nacos/v1/ns/instance?serviceName=cosmo-glm&namespaceId=cosmosource&ip=192.168.1.1&port=8081&metadata={}
![image](https://user-images.githubusercontent.com/24490695/216540514-19ef57ba-462e-4af9-ae48-bfb5b4e59b11.png)
去掉metadata参数可正常使用，请问增加metadata需要怎么处理？
**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by YunWZ** [comment]
你应该将请求参数放到请求body中,更确切地说是放到表单中(`Content-Type: application/x-www-form-urlencoded`).

**Comment by KomachiSion** [comment]
urlencode please
