### ISSUE TITLE
连续点击 Nacos 图标可以越过登录直接进入管理页面

### ISSUE THREAD

**Issue by JCXTB** [alibaba/nacos#9903]
连续点击 Nacos 图标可以越过登录直接进入管理页面，虽然看不到已有的配置文件，但是可以越权删除已存在的 namespace
Nacos 版本： 2.0.4
浏览器： Chrome 108.0.5359.125（正式版本） （64 位）
重现步骤：
1. 打开 nacos 登录页面
2. 重复点击登录页面左上角的图标，直到进入管理页面（3-5秒钟连续点击即可）
![image](https://user-images.githubusercontent.com/19177719/216888972-c7b21ce1-6767-4c8d-b424-0913c86759ca.png)
3. 看不到已经存在的配置
![image](https://user-images.githubusercontent.com/19177719/216889545-7893e7ec-98f5-4922-a7a6-679056d7b9ff.png)
4. 可以删除已经存在的 namespace（点击确认后可能会返回到登录页面，但是 namespace 删除成功了）
![image](https://user-images.githubusercontent.com/19177719/216889774-fb9dad9e-4b2e-4ff6-9c34-0509bcfb5b01.png)

**Comment by YunWZ** [comment]
之前登陆过账号吗?(具有管理员权限的账号)

**Comment by JCXTB** [comment]
> 之前登陆过账号吗?(具有管理员权限的账号)
我发现问题的机器是登录过的，打开浏览器的无痕可以复现，换了一台没有登录过系统的机器也是可以复现的

**Comment by YunWZ** [comment]
没有复现出来, 直接访问`http://127.0.0.1:8848/nacos/index.html`(ip改成服务队地址) 看看能不能行呢, 确认下开启了鉴权功能.

**Comment by JCXTB** [comment]
@YunWZ 问题解决了，application.properties 配置文件没看到这个变量 NACOS_AUTH_ENABLE=true，漏配置了
