### ISSUE TITLE
如何扩展客户端的健康检查机制？

### ISSUE THREAD

**Issue by CopyOfXuech** [alibaba/nacos#9904]
一个服务是否可用通常不仅仅取决于心跳正常，可能依赖数据库、Redis等，希望能提供自定义检查自身状态的机制

**Comment by KomachiSion** [comment]
那您需要使用持久化类型的服务。持久化服务可以定义是进行tcp、http检查

**Comment by CopyOfXuech** [comment]
但是我又希望在服务实例不健康的时候，可以像临时服务一样，被剔除出服务实例列表，目前的nacos能否实现呢

**Comment by 47295743** [comment]
服务提供者把自己的协议地址注册到Nacos server
    服务消费者需要从Nacos Server上去查询服务提供者的地址（根据服务名称）
    Nacos Server需要感知到服务提供者的上下线的变化
    服务消费者需要动态感知到Nacos Server端服务地址的变化

**Comment by 47295743** [comment]
Nacos 提供对服务的实时的健康检查，阻止向不健康的主机或服务实例发送请求。Nacos 支持传输层 (PING 或 TCP)和应用层
(如 HTTP、MySQL、用户自定义）的健康检查。对于复杂的云环境和网络拓扑环境中（如 VPC、边缘网络等）服务的健康检查，Nacos提供了 agent 上报模式和服务端主动检测2种健康检查模式

**Comment by KomachiSion** [comment]
> 但是我又希望在服务实例不健康的时候，可以像临时服务一样，被剔除出服务实例列表，目前的nacos能否实现呢

目前还没有实现这种，但是是有计划的。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
