### ISSUE TITLE
nacos从2.0.4升级到2.1.1报错

### ISSUE THREAD

**Issue by opencmit2** [alibaba/nacos#9909]
![6dde91b70a29432c8362943e1659ba2f](https://user-images.githubusercontent.com/112474703/217177780-41b91ea8-cf7d-4428-a12a-38e21beec150.png)

nacos从2.0.4升级到2.1.1报错,上图为报错原因

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/8960
