### ISSUE TITLE
Naocs通过插件支持将自身监控数据写入TDengine,而不是InfluxDB

### ISSUE THREAD

**Issue by SoftwareKing** [alibaba/nacos#9911]
Naocs通过插件支持将自身监控数据写入TDengine,而不是InfluxDB。因为InfluxDB集群是商业收费

**Comment by KomachiSion** [comment]
Nacos使用mircometer写入监控数据，mircometer的实现目前有prometheus、InfluxDB、ES等。

 TDengine是否有mircometer实现，有的话就可以自行依赖即可，如果没有的话，请给TDengine社区提交issue，请其支持mircometer。这个和nacos无关。
