### ISSUE TITLE
【求助】集群模式下节点列表不显示

### ISSUE THREAD

**Issue by JaneYork** [alibaba/nacos#9917]
## 前情提示

- 一台服务器，伪集群，三个不同端口，18848,28848,38848
- nginx负载均衡，域名访问nginx
- centos7.9 阿里云2核8G
- nacos 2.1.0

## 问题描述
三个节点都启动成功，而且单独访问ip:port都可以。`Nacos started successfully in cluster mode. use external storage
`
但是节点列表里，只显示了一只。
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/29787967/217427560-8d4dbefb-d46b-467a-a2b0-8a1fb94281af.png">

**Comment by JaneYork** [comment]
原来是我点击了下线，把cluster.conf里其他Ip配置自动移除了。

那如果我想要其他节点再次上线如何操作？
每个节点手动添加Ip配置？然后每个节点重启？？？

**Comment by KomachiSion** [comment]
修改cluster.conf文件，会自动读取并且加入回去。

另外，这个接口在新版本中已经禁用， server节点的上下线运维操作等未来重新设计。
