### ISSUE TITLE
Code Optimize Suggestion

### ISSUE THREAD

**Issue by ZhangShenao** [alibaba/nacos#9922]
Hi~
In the constructor of `ConfigChangeHandle`，why not use List.addAll() instead of iterator when add all elements into `parserList` ?

**Comment by Dario-s-j** [comment]
Em qua, 8 de fev de 2023 06:10, ZhangShenao ***@***.***>
escreveu:

**Comment by PRANRAVEE** [comment]
ในวันที่ พ. 8 ก.พ. 2023 16:12 Dario-s-j ***@***.***> เขียนว่า:
