### ISSUE TITLE
为啥要直接load class bytestream 读取版本号，class 文件被加密了导致 grpc 无法处理扫描类

### ISSUE THREAD

**Issue by ZouTrankil** [alibaba/nacos#9926]
**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Please describe your problem more detail.
