### ISSUE TITLE
Nacos部署在docker容器中引用系统环境变量不生效

### ISSUE THREAD

**Issue by XiaoPenPen** [alibaba/nacos#9927]
环境：
Centos9虚机， nacos版本: 2.2.0单节点

在docker容器启动命令中通过  --env-file /home/env.list 将宿主机env挂到nacos容器中并且成功。如下图所示。
![image](https://user-images.githubusercontent.com/42669253/217979155-189c2b96-001a-42ce-b49e-91bb06f12be4.png)

我想在nacos配置中心的yaml文件中引用这些变量，如下图。
![image](https://user-images.githubusercontent.com/42669253/217979260-f0260a23-3ea9-47fd-8aad-031b05416a00.png)
结果没有成功，想请教下是否可以这样操作?

**Comment by KomachiSion** [comment]
配置内容对nacos是黑盒，nacos不会到配置内容中替换你所谓的`配置变量`。这个功能需要你在获取到nacos给予的配置之后，自行替换。

**Comment by XiaoPenPen** [comment]
感谢回复，nacos是否存在类似的变量替换的操作，实际使用场景中经常需要更换环境，每次都需要手动进入yaml文件中修改或自行跑脚本替换有些麻烦。

**Comment by XiaoPenPen** [comment]
顺序理解错了 现在明白了，感谢答复
