### ISSUE TITLE
How to access the Nacos2.1.0 console without logging in

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#9928]
I want to click url "http://127.0.01:8848/nacos/index.html" into nacos console directly without username and password. I follow the guide of  "https://nacos.io/zh-cn/docs/console-guide.html" to add some configurations
(spring.security.enabled=false
management.security=false
security.basic.enabled=false
nacos.security.ignore.urls=/**
#nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**,/nacos/index.html#/login)
into application.propertits, reboot the nacos server, but it isn't work, still need input username and password, so is there any other way to access the console directly.

**Comment by KomachiSion** [comment]
the console ui has no completed plugin and module abilities, so the console ui should login for now.

The guide document is to ignore the login page for `spring security`. If you are interesting to make console ui as plugin, welcome to submit pr.

**Comment by KomachiSion** [comment]
the console ui has no completed plugin and module abilities, so the console ui should login for now.

The guide document is to ignore the login page for `spring security`. If you are interesting to make console ui as plugin, welcome to submit pr.

**Comment by huayangchan** [comment]
> And If you only want to remove the ui login page, you should change the source code of console ui. and remove the relative pages.

OK， thank u
