### ISSUE TITLE
>

### ISSUE THREAD

**Issue by Rigavinil201** [alibaba/nacos#9933]
>

_Originally posted by @Rigavinil201 in https://github.com/alibaba/nacos/issues/9753#issuecomment-1396278346_

**Comment by Rigavinil201** [comment]
Ок

**Comment by PRANRAVEE** [comment]
เกี่ยวกับอะไร
คุณสามารถตอบฉันเป็นภาษาไทย

ในวันที่ จ. 13 ก.พ. 2023 20:59 @Perfect_VIP_Girl ***@***.***>
เขียนว่า:
