### ISSUE TITLE
关于服务优雅下线

### ISSUE THREAD

**Issue by jekran** [alibaba/nacos#9939]
想问下大佬们，nacos更新到目前为止，要实现服务优雅下线还是得靠手动调用客户端的api进行下线服务操作吗，还是有其他更好的办法，目前服务端使用的是2.0.4版本，还存在延迟的问题，下线过后该机器还是存在于应用调用方本地实例缓存列表中

**Comment by KomachiSion** [comment]
客户端呢？ 客户端可以升级到2.1以上， 延迟应该会短很多。

**Comment by jekran** [comment]
> 要完全的优雅下线， 最好是先调api下线，确认无流量之后再停服务。

了解了，谢大佬答疑
