### ISSUE TITLE
Nacos Config配置中心修改了数据库地址项目运行时获得的数据还是修改之前的数据库数据?

### ISSUE THREAD

**Issue by GimGong777** [alibaba/nacos#9941]
我在nacos的配置中心修改了数据库地址，把本地的换成线上的，但是运行的结果还是本地的数据库中的数据，而且从配置中心拿到的数据库地址是我改了之后的线上数据库地址，求解？？？

**Comment by KomachiSion** [comment]
配置中心只负责下发配置， 配置使用是应用的工作，从你描述来看，配置已经正确下发， 只是你的应用程序不使用新的配置去访问，还在使用就的数据库连接访问。 您需要自行排查应用。
