### ISSUE TITLE
Is it possible to hide the namespace without permission?

### ISSUE THREAD

**Issue by IcebergXTY** [alibaba/nacos#9942]
**Is your feature request related to a problem? Please describe.**
Hi, everyone. We enable the authority control and find user can see all the namespaces though he dosen't have the authority like below. Is it possible to hide the namespace without permission?
![image](https://user-images.githubusercontent.com/15325243/218653902-574da15a-b7e7-4c55-ae9c-2f6fca878b5c.png)

**Additional context**
Nacos 2.2.0

**Comment by KomachiSion** [comment]
No plan for now, the auth plugin is a extension module, should not be inject to the main workflow.

**Comment by KomachiSion** [comment]
If you want to do this, you can implement your console ui logic and develop your own auth plugin to do this.
