### ISSUE TITLE
why some module of version 2.1.0 cann't be found in  mvnrepository ,such as (nacos nacos-naming, nacos-core,eg.)?

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#9944]
In mvnrepository(https://mvnrepository.com/artifact/com.alibaba.nacos), i cann't some module of version 2.1.0 cann't be found in  mvnrepository ,such as (nacos nacos-naming, nacos-core,eg.)

**Comment by KomachiSion** [comment]
server part module will not release to mvn repository. they should only run in server which release as a runnable file not as a jar.
