### ISSUE TITLE
【求助】nacos 2.0 nginx集群域名访问教程

### ISSUE THREAD

**Issue by JaneYork** [alibaba/nacos#9946]
## 环境说明
nacos2.x
centos7.9
宝塔LNMP
为了顺利测试， 防火墙安全组全部关闭了

## nginx配置
```
upstream nacosCluster {
        server 172.19.14.25:18848;
        server 172.19.14.25:28848;
        server 172.19.14.25:38848;
        keepalive 120;
 ```

## 代码集成
代码直接用的aa.b.com:80

## 问题
项目启动后，过段时间报错：com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

## 解决
详见内部文档，或者https://pgz-sbv-gf.pusdn.com/

**Comment by JaneYork** [comment]
> ## 环境说明
> nacos2.x centos7.9 宝塔LNMP
> 
> ## nginx配置
> ```
> upstream nacosCluster {
>         server 172.19.14.25:18848;
>         server 172.19.14.25:28848;
>         server 172.19.14.25:38848;
>         keepalive 120;
>     }
> 
> server
> {
>     listen 80;
> 		listen 443 ssl http2;
>     server_name aa.b.com 47.104.109.95;
>     # index index.php index.html index.htm default.php default.htm default.html;
>     root /www/wwwroot/aa.b.com;
> 
>     #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
>     #error_page 404/404.html;
>     ssl_certificate    /www/server/panel/vhost/cert/aa.b.com/fullchain.pem;
>     ssl_certificate_key    /www/server/panel/vhost/cert/aa.b.com/privkey.pem;
>     ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
>     ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
>     ssl_prefer_server_ciphers on;
>     ssl_session_cache shared:SSL:10m;
>     ssl_session_timeout 10m;
>     add_header Strict-Transport-Security "max-age=31536000";
>     error_page 497  https://$host$request_uri;
> 		#SSL-END
> 
>     #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
>     #error_page 404 /404.html;
>     #error_page 502 /502.html;
>     #ERROR-PAGE-END
> 
>     #PHP-INFO-START  PHP引用配置，可以注释或修改
>     include enable-php-00.conf;
>     #PHP-INFO-END
> 
>     #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
>     include /www/server/panel/vhost/rewrite/aa.b.com.conf;
>     #REWRITE-END
> 
>     #禁止访问的文件或目录
>     location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
>     {
>         return 404;
>     }
> 
>     #一键申请SSL证书验证目录相关设置
>     location ~ \.well-known{
>         allow all;
>     }
> 
>     #禁止在证书验证目录放入敏感文件
>     if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
>         return 403;
>     }
> 
>        location /nacos {
>         proxy_pass http://nacosCluster;
>         proxy_set_header Host $http_host;
> proxy_set_header X-Real-IP $remote_addr;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> 
>     access_log  /www/wwwlogs/nacos.pusdn.com.log;
>     error_log  /www/wwwlogs/nacos.pusdn.com.error.log;
> }
> ```
> 
> 第二个配置
> 
> ```
> upstream erp-nacos-grpc{
>   hash $remote_addr consistent;
>   server 172.19.14.25:19848 weight=1;
>   server 172.19.14.25:29848 weight=1;
>   server 172.19.14.25:39848 weight=1;
> }
> upstream erp-nacos-grpc9{
>   hash $remote_addr consistent;
>   server 172.19.14.25:19849 weight=1;
>   server 172.19.14.25:29849 weight=1;
>   server 172.19.14.25:39849 weight=1;
> }
> # grpc 代理配置
> server {
>   listen 1080; # grpc方式对外暴露端口
>   proxy_connect_timeout 10s;
>   proxy_timeout 10s;
>   proxy_pass erp-nacos-grpc;
> }
> 
> # grpc 代理配置
> server {
>   listen 1081; # grpc方式对外暴露端口
>   proxy_connect_timeout 10s;
>   proxy_timeout 10s;
>   proxy_pass erp-nacos-grpc9;
> }
> ```
> 
> ## 代码集成
> 代码直接用的aa.b.com:80
> 
> ## 问题
> 项目启动后，过段时间报错：com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason

@KomachiSion

**Comment by JaneYork** [comment]
https://github.com/alibaba/nacos/issues/7556#issuecomment-1008648847

**Comment by KomachiSion** [comment]
nginx配置问题需要自己排查一下， 或者看下社区有没有有兴趣的一起排查。

**Comment by YunWZ** [comment]
2.x 版本使用grpc协议。如果你的客户端使用的也是2.x版本，也许需要在nginx中支持转发grpc请求。

**Comment by KomachiSion** [comment]
不能设置为grpc转发，会导致断链。

需要设置成tcp转发。保持keepalive。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
