### ISSUE TITLE
the source 2.2.0 cannot be compile

### ISSUE THREAD

**Issue by huangxuanheng** [alibaba/nacos#9953]
I clone source 2.2.0 to local idea and want to run ,but error occur,pealse help me what can I do?
![image](https://user-images.githubusercontent.com/10696294/218945480-fd85c219-a9d8-4ba4-9264-1bde3332d0a3.png)

**Comment by lpaz010** [comment]
阅读[Nacos官方文档](https://nacos.io/zh-cn/docs/v2/guide/user/faq.html#3.19)可得到如下描述：
```text
找不到符号com.alibaba.nacos.consistency.entity

这个包目录是由protobuf在编译时自动生成，您可以通过mvn compile来自动生成他们。如果您使用的是IDEA，也可以使用IDEA的protobuf插件。
```

**Comment by YunWZ** [comment]
try execute `mvn compile -DskipTests`

**Comment by huangxuanheng** [comment]
> 
thank you very much.it has already run
