### ISSUE TITLE
How to startup nacos2.1.0 in cluster mode using embedded storage instead of external storage?

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#9955]
I want startup nacos2.1.0 in cluster mode using embedded storage, I add a command "-DembeddedStorage=true" in VM options of IDEA, the "Nacos is starting..." is printed continuously, and finaly failed. So is it possible to startup nacos2.1.0 in cluster mode using embedded storage  instead of external storage?

**Comment by KomachiSion** [comment]
No problem for use embedded storage with cluster mode.

What's your failed log and information of more details?

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
