### ISSUE TITLE
nacos长连接无法接收数据

### ISSUE THREAD

**Issue by dongduang** [alibaba/nacos#9958]
springboot服务启动后，通过java sdk(ConfigService configService = NacosFactory.createConfigService(properties))并添加监听器来监听远程配置，长期运行后，只能看到nacos打印如下‘错误日志’，并未接收到数据

错误日志只打印如下三行：
第一行：receive server push request,request=ConfigChangeNotifyRequest,requestId=282
第二行：[server-push] config changed. dataId=***, group=***,tenant=***
第三行：ack server push request,request=ConfigChangeNotifyRequest,requestId=282

正常日志会继续向下打印并输出远程配置项：
第四行：[config_rpc_client] [data-received] dataId=***, group=***, tenant=***, md5=***, content=远程配置项
, type=text
第五行：[config_rpc_client] [notify-listener] time cost=1ms in ClientWorker, dataId=***, group=***, md5=***, listener=com.navercorp.pinpoint.profiler.monitor.DefaultRemoteConfigMonitor$1@71f16ba4
第六行：[config_rpc_client] [notify-ok] dataId=***, group=***, md5=***, listener=com.navercorp.pinpoint.profiler.monitor.DefaultRemoteConfigMonitor$1@71f16ba4 ,cost=2 millis.

**Comment by KomachiSion** [comment]
没有一行是错误日志， 全是收到数据的日志。

你是说dataId，group，md5等都是没有内容？

**Comment by dongduang** [comment]
都是INFO日志，通过注册监听器Listener，能正常进入receiveConfigInfo方法的日志会打印上述6行日志，异常情况下即无法进入receiveConfigInfo的只能打印前三行（服务长时间运行就无法接收到数据）。

 Listener result = new Listener() {
            @Override
            public void receiveConfigInfo(String configInfo) {
                if(logger.isDebugEnabled()){
                    logger.debug("recieve remote configInfo : [{}]",  configInfo);
                }
            }
            @Override
            public Executor getExecutor() {
                return null;
            }
        };

**Comment by KomachiSion** [comment]
那应该是监听器没有注册上或者监听器监听的dataId不对没匹配上导致没有回调，看日志是客户端是收到了配置的。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
