### ISSUE TITLE
client心跳恢复正常后无法重新自动注册到server

### ISSUE THREAD

**Issue by zhangchengkun** [alibaba/nacos#9959]
client因某种原因出现问题并自动恢复后，发送心跳给nacos server，nacos server提示service not found未触发自动注册，导致服务消费方获取不到服务实例列表。
版本： clientv1.4.2，serverv2.1.1
client日志：
![image](https://user-images.githubusercontent.com/12931375/219262400-f2b4cc7f-0d44-47bc-9a9e-38d89e182153.png)
server日志：
![image](https://user-images.githubusercontent.com/12931375/219262492-033ec9ab-6478-4daa-9310-9c3bb868346a.png)

**Comment by KomachiSion** [comment]
正常情况下， 这个异常分支不会进入：
1. 客户端不存在 或 客户端存在但未注册该服务的场景，会返回给客户端`实例不存在`，客户端会重新注册 。
2. 客户端存在且注册过该服务实例的场景下，才会往后执行，此时服务管理器里不可能不存在服务。
3. 服务管理器里删除服务只有两种可能：服务实例为0且超过1min未更新；通过删除接口删除，但客户端存在且注册过该服务实例的场景下，服务实例必不为0，因此不会自动清楚；通过接口删除时，也会判断是否存在实例，有实例时是不允许删除的，所以也不可能。

因此需要排查下是否有修改过源代码，通过非正常手段清理了服务管理器中的服务。

**Comment by zhangchengkun** [comment]
> 

源码未修改过，也未清理过服务。服务持续1小时一直未注册自动服务，只能重启nacos解决
（1）客户端心跳逻辑有注册服务的逻辑，为什么未触发这个逻辑
![image](https://user-images.githubusercontent.com/12931375/220316510-ab5f2e33-8b2d-4f7d-a847-bc4520145097.png)
（2）服务端心跳处理逻辑中这个分支未触发
![image](https://user-images.githubusercontent.com/12931375/220316026-05891753-4949-4604-a46e-e7b2c87ca55b.png)

**Comment by KomachiSion** [comment]
1. 客户端未出触发这个逻辑是因为服务端出发了红框逻辑， 说明当时有这个client数据并且client中有注册过这个服务。
2. 之所以服务端这里要抛异常是希望终止这次心跳请求，一段时间不发心跳会让client的实例被移除，并且移除client，让服务端走到红框中的逻辑进行数据自我修正。
3. 您持续一个小时在报这个错误， 说明这个client中的实例一直处于存在状态。您需要排查的事为什么client中的实例一直存在，是否变成了持久化实例等等。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
