### ISSUE TITLE
CreatedTime  of configuration history version is all 2010-05-05T00:00:00.000+00:00.

### ISSUE THREAD

**Issue by jafferCc** [alibaba/nacos#9962]
**Describe the bug**
Check the configuration history version. The value of createdTime is 2010-05-05T00:00:00.000+00:00.

**Expected behavior**
The configured creation time should be the same as the actual value.

![image](https://user-images.githubusercontent.com/109120029/219356660-641fc015-4638-4095-b8ed-0ef47a155b9d.png)
![image](https://user-images.githubusercontent.com/109120029/219356676-c9da2bdc-55ba-4b24-a31b-4395522548f4.png)

**Comment by 985492783** [comment]
2010-05-05 00:00:00是数据库中datetime类型的默认值，应该是rollback的api里没有提供这个字段信息

**Comment by KomachiSion** [comment]
没看懂问题。
