### ISSUE TITLE
how to use accessKey and accessSecret in java client?

### ISSUE THREAD

**Issue by lchpersonal** [alibaba/nacos#9964]
Alibaba Cloud provides configurations such as "spring.cloud.nacos.config.access-key" to realize the connection between the java client and the server. How do I use this feature in the open source version?

In our business scenario, the service function is to modify the configuration of the production nacos. After the authentication is enabled, the configuration file of the service itself is writen by  developers, and the password of the nacos account is known. However, the production environment only wants to retain the view permission for developers. How to realize this business scenario?

**Comment by IJiaPu** [comment]
specify:
nacos.core.auth.enabled=true

**Comment by IJiaPu** [comment]
You can try.
This is not what you want.

**Comment by lchpersonal** [comment]
> specify: nacos.core.auth.enabled=true

this is not what i want.  I already open this option。 but use java client must provide username and password. this config can be read by every developers

**Comment by IJiaPu** [comment]
您好，我理解这个问题可能有些悖论，下午由于问题没看仔细，以为您是要问如何开启该功能！

下面回到问题本身：
1、一般这些配置文件里面不应直接写入其他应用的ID与密码，应使用其系统发放的token/accessKey
2、生产环境往常的数据库、配置中心等应当是有专门的权限控制的，Nacos中也提供了只读、读写的权限控制，在用户管理里面可以看到。
例如该文章介绍：https://developer.aliyun.com/article/782864
3、即使配置文件只存放了token等，但开发人员依旧有办法可以访问，所以例如贝壳这些公司的做法是将生产环境隔离开来。
4、您的问题总结起来就是既需要该账号密码可以修改配置文件，又想让其只拥有读的权限！这个据我所知只能将测试、生产环境这些隔离起来。

**Comment by lchpersonal** [comment]
> 



> 您好，我理解这个问题可能有些悖论，下午由于问题没看仔细，以为您是要问如何开启该功能！
> 
> 下面回到问题本身： 1、一般这些配置文件里面不应直接写入其他应用的ID与密码，应使用其系统发放的token/accessKey 2、生产环境往常的数据库、配置中心等应当是有专门的权限控制的，Nacos中也提供了只读、读写的权限控制，在用户管理里面可以看到。 例如该文章介绍：https://developer.aliyun.com/article/782864 3、即使配置文件只存放了token等，但开发人员依旧有办法可以访问，所以例如贝壳这些公司的做法是将生产环境隔离开来。 4、您的问题总结起来就是既需要该账号密码可以修改配置文件，又想让其只拥有读的权限！这个据我所知只能将测试、生产环境这些隔离起来。

那么，在开源私有化部署的场景里，如何在配置文件中防止accessKey和accessSecret呢？ 好像只有阿里云有这个功能

**Comment by KomachiSion** [comment]
不配置accessKey，accessSecret，就不会执行相关的功能。
