### ISSUE TITLE
Nacos 2.x gRPC 已经完全替代了 HTTP吗？

### ISSUE THREAD

**Issue by Jedore** [alibaba/nacos#9968]
请问，在 2.x 版本中，gRPC 协议实现的功能已经完全替代了 HTTP 功能了吗？
比如 gRPC 是否只能注册临时实例？
因为没有看到有相关的说明资料，提前感谢！

**Comment by KomachiSion** [comment]
1. HTTP协议不会被取消， 运维接口以及控制台接口还是需要HTTP接口交互。
2. 大部分非运维/控制台功能内容已经用gRPC取代， 还有少量功能也会在后续版本中替换为gRPC。

**Comment by Jedore** [comment]
好的， 多谢
