### ISSUE TITLE
How to create ephemeral service

### ISSUE THREAD

**Issue by Daydreamer-ia** [alibaba/nacos#9969]
**Describe the bug**
I cannot create a actual ephemeral  service in console when nacos server start in standalone mode.
The error is  as follow, and i wonder why no leader error happens when nacos server start in standalone mode.
![1676696930156](https://user-images.githubusercontent.com/83362909/219840981-50904ff1-afb2-47e1-8d35-cf0ebe20b15c.png)
![1676697170742](https://user-images.githubusercontent.com/83362909/219841904-2aacd691-2eb2-4b2a-9973-8b76b5993b7e.png)

**How to Reproduce**
nacos server version: NACOS 2.2.0-BETA
start nacos server with vm option "-Dserver.port=8848 -Dnacos.standalone=true"

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/guide/user/open-api.html

**Comment by KomachiSion** [comment]
Or register an ephemeral instance , the service will be auto created.

**Comment by Daydreamer-ia** [comment]
@KomachiSion Sorry, i made a mistake in expression. The service is persistent not ephemeral. I try again in 2.2.1-SNAPSHOT version and find it still failed.
