### ISSUE TITLE
How does the nacos client customize the registration timing

### ISSUE THREAD

**Issue by GGGGGHT** [alibaba/nacos#9972]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

I have a springboot project that uses nacos as the registration center. I want to register with nacos after the service is warmed up.
That is, after spring publishes ApplicationReadyEvent, it registers instead of WebServerInitializedEvent 
### Describe what you expected to happen

I know that NacosAutoServiceRegistration listens to WebServerInitializedEvent, I removed this listener, but there are other listeners that will complete the function of service registration.

### How to reproduce it (as minimally and precisely as possible)

1. create a spring cloud project
2. add nacos dependency

### Tell us your environment

openjdk version "1.8.0_332"
springboot 2.7.0
nacos 2.2.0

**Comment by KomachiSion** [comment]
You can directly depend `nacos-client` and build your bean by yourself. And register your services in any time you wanted.

**Comment by KomachiSion** [comment]
But if you use SCA or nacos-spring-boot-starter, the framework has defined the registered time, it hard to change the register time.

**Comment by GGGGGHT** [comment]
I use the `nacos-spring-boot-starter` , if I have to modify the registration time of the client, how should I do it. @KomachiSion

**Comment by YunWZ** [comment]
Ref `NacosDiscoveryAutoRegister`:
```java
@Component
public class NacosDiscoveryAutoRegister
        implements ApplicationListener<WebServerInitializedEvent> {
    @Override
    public void onApplicationEvent(WebServerInitializedEvent event) {

        if (!discoveryProperties.isAutoRegister()) {
            return;
        }
//...
}
```

First, u should disable `auto-register` property;
Second, u need to implement yourself Register and DeRegister.

**Comment by KomachiSion** [comment]
1. Your app must know when it has finish started and should register to service.
2. At this time your app call nacos-client api to do register, see document https://nacos.io/zh-cn/docs/v2/guide/user/sdk.html

No body can help you do example because no one know how to judge your app finish started.
