### ISSUE TITLE
python-sdk for nacos2.x

### ISSUE THREAD

**Issue by Jedore** [alibaba/nacos#9973]
Current nacos-sdk-python only supports nacos1.x,  i want to code a python-sdk for nacos2.x. I want to select gRPC. 
But i am not sure about whether gRPC feature can replace HTTP absolutly in nacos2.x. And i'm not good at Java.
Please give me some advices. Thanks. 👨‍💻   @KomachiSion

**Comment by KomachiSion** [comment]
https://github.com/nacos-group/nacos-sdk-python/tree/summer2021_issue%235694

And we are welcome you can join us and continue maintain the python sdk 2.0.

**Comment by Jedore** [comment]
Thanks, i would think over it.  Because my project needs to use nacos2.x with python, so i must implement a micro nacos-sdk-python2 now.
