### ISSUE TITLE
请问有没有通过静态路由调用服务的机制

### ISSUE THREAD

**Issue by liseri** [alibaba/nacos#9974]
## 环境
nacos, 和服务A 在docker中跑(bridge网络模式)
服务B在idea中启动， 服务B通过feign调用服务A, 
服务B报错：feign.RetryableException: Connection timed out: no further information executing GET http://服务A名称/...
## 诉求
希望将 ***http://服务A名称*** 样式的请求 转换为 ***http://可连通服务A的ip*** 样式

**Comment by ruansheng8** [comment]
看下nacos中的服务列表 ,  服务A的IP是否能够和宿主机正常通信 , 可以将服务A在nacos上IP地址使用宿主机暴露

**Comment by KomachiSion** [comment]
I seems no nacos' problem.
