### ISSUE TITLE
2.1.0  内存持续飙高

### ISSUE THREAD

**Issue by sunset535** [alibaba/nacos#9984]
![image](https://user-images.githubusercontent.com/3860179/220259947-54ae7787-615f-453e-9698-7fe04f6fbcd8.png)
![image](https://user-images.githubusercontent.com/3860179/220259992-c9344a47-8565-4718-8cd1-77036e878ff5.png)
![image](https://user-images.githubusercontent.com/3860179/220260059-88ea89f4-7814-4162-ad1a-5af37d23c345.png)

**Comment by KomachiSion** [comment]
It seems not nacos' problem. it should be your app's problem. Please check your app by yourself.

**Comment by YunWZ** [comment]
See about this pr: https://github.com/grpc/grpc-java/issues/5671
