### ISSUE TITLE
spring boot 3 服务注册不了, 无报错, 服务可读取 nacos 配置, 但是 服务列表查询结果总是空的

### ISSUE THREAD

**Issue by 15637942788** [alibaba/nacos#9987]
use version: 
<maven.compiler.source>17</maven.compiler.source>
<spring-cloud.version>2022.0.1</spring-cloud.version>
<spring-cloud-alibaba.version>2021.0.4.0</spring-cloud-alibaba.version>
<spring-boot.version>3.0.2</spring-boot.version>
try:
1. Modify the nacos configuration file to determine that it affects the normal startup of the program. For example: Modify the mysql port. (It only affects at startup)
my bootstrap.yml:
# Tomcat
server:
  port: xxxx

# Spring
spring: 
  application:
    # 应用名称
    name: xxx
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      server-addr: xxx.xxx.xxx.xxx:8848
      username: 'xxx'
      password: 'xxxx'
      discovery:
        # 服务注册地址
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        enable-remote-sync-config: true # 监听器首次添加时拉取远端配置 默认false
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.server-addr}
        # 配置文件格式
        file-extension: yml
        # 共享配置
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

**Comment by 15637942788** [comment]
没问题了, 原因是 <spring-cloud-alibaba.version>2021.0.4.0</spring-cloud-alibaba.version> 版本用的不对, 我这边用的是 spring cloud 官网的 最终版, 应该参考的是这个: https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
我用的版本是:  <spring-cloud-alibaba.version>2022.0.0.0-RC1</spring-cloud-alibaba.version>

**Comment by PRANRAVEE** [comment]
ส่งจากโทรศัพท์มือถือ Huawei ของฉัน-------- ข้อความต้นฉบับ --------จาก: 15637942788 ***@***.***>วันที่: อ. 21 ก.พ. 2023 14:40ถึง: alibaba/nacos ***@***.***>สำเนา: Subscribed ***@***.***>เรื่อง: Re: [alibaba/nacos] spring boot 3 服务注册不了, 无报错, 服务可读取 nacos 配置, 但是 服务列表查询结果总是空的 (Issue #9987)
Closed #9987 as completed.

**Comment by PRANRAVEE** [comment]
ส่งจากโทรศัพท์มือถือ Huawei ของฉัน-------- ข้อความต้นฉบับ --------จาก: 15637942788 ***@***.***>วันที่: อ. 21 ก.พ. 2023 14:10ถึง: alibaba/nacos ***@***.***>สำเนา: Subscribed ***@***.***>เรื่อง: [alibaba/nacos] spring boot 3 服务注册不了, 无报错, 服务可读取 nacos 配置, 但是 服务列表查询结果总是空的 (Issue #9987)

use version:

<maven.compiler.source>17</maven.compiler.source>

<spring-cloud.version>2022.0.1</spring-cloud.version>

<spring-cloud-alibaba.version>2021.0.4.0</spring-cloud-alibaba.version>

<spring-boot.version>3.0.2</spring-boot.version>

try:

Modify the nacos configuration file to determine that it affects the normal startup of the program. For example: Modify the mysql port. (It only affects at startup)

my bootstrap.yml:

Tomcat

server:

port: xxxx

Spring

spring:

application:

# 应用名称

name: xxx

profiles:

# 环境配置

active: dev

cloud:

nacos:

server-addr: xxx.xxx.xxx.xxx:8848

username: 'xxx'

password: 'xxxx'

discovery:

# 服务注册地址

server-addr: ${spring.cloud.nacos.server-addr}

config:

enable-remote-sync-config: true # 监听器首次添加时拉取远端配置 默认false

# 配置中心地址

server-addr: ${spring.cloud.nacos.server-addr}

# 配置文件格式

file-extension: yml

# 共享配置

shared-configs:

- application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
