### ISSUE TITLE
请问如何动态读取nacos数组配置信息

### ISSUE THREAD

**Issue by andyge2014** [alibaba/nacos#9990]
请问如何动态读取nacos数组配置信息？
可以动态获取非数组信息。

环境信息：
- nacos server v2.2.0
- java
```xml
<spring-cloud.version>Greenwich.SR6</spring-cloud.version>
<dependency>
    <groupId>com.alibaba.boot</groupId>
    <artifactId>nacos-config-spring-boot-starter</artifactId>
    <version>0.2.12</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/10277356/220301347-e2fb8da5-b038-4fda-8d7d-329eeebc4ad1.png)
此时修改配置中心的配置，并发布，再次测试获取到的还是修改前的结果

**Comment by IJiaPu** [comment]
把nacos-config-spring-boot-starter改成spring-cloud-starter-alibaba-nacos-config的包试试，我用这个没问题，Spring版本2.3.7.RELEASE，config版本2021.1

**Comment by KomachiSion** [comment]
Please run example and learn the usage https://github.com/nacos-group/nacos-spring-boot-project/tree/master/nacos-spring-boot-samples/nacos-config-sample
