### ISSUE TITLE
Nacos is using a reliable library - netty-codec 4.1.48.Final version which has several vulnerabilities

### ISSUE THREAD

**Issue by orrin1001** [alibaba/nacos#9991]
In the latest nacos, it is using netty-codec 4.1.48.Final version, which has several vulnerabilities, wish it would be fixed in the coming release.

Vulnerabilities of netty-codec:
https://mvnrepository.com/artifact/io.netty/netty-codec/4.1.48.Final

Reliable library info in nacos-client-2.2.0\META-INF\maven\io.netty\netty-codec\pom.xml:
 
![image](https://user-images.githubusercontent.com/59193501/220318292-f8e243b8-74bd-41d5-b00b-e06ff7e845fd.png)

**Comment by KomachiSion** [comment]
dupliated by #9537
