### ISSUE TITLE
set "nacos.core.auth.enabled=true" problem.

### ISSUE THREAD

**Issue by isgbuddy** [alibaba/nacos#9993]
**Describe the bug**
set "nacos.core.auth.enabled=true", Then only "nacos" username can login OK in springboot nacos client.

开启权限认证后，客户端只有 nacos 这个系统管理员用户可以登录，其它新建的账户都登录不了。

nacos server version is 2.0.3
nacos client version is 2.0.4

**Comment by isgbuddy** [comment]
# Nacos认证信息
spring.cloud.nacos.discovery.username=test
spring.cloud.nacos.discovery.password=test123
# Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
spring.cloud.nacos.discovery.server-addr=test-nacos.com:8848

新建用户无法访问成功，改成 nacos/nacos 就能访问成功

**Comment by YunWZ** [comment]
新创建的用户分配权限了么？

**Comment by IJiaPu** [comment]
管理员账户创建相应权限角色，绑定角色给用户

**Comment by isgbuddy** [comment]
角色、权限都跟着新账户都建了

**Comment by isgbuddy** [comment]
我在 nacos 服务器上抓了包，用户登录没问题，
客户端，在 8848 端口访问 
POST /nacos/v1/auth/users/login?username=
成功返回了
{"accessToken":"xxxxxxxxxxxxxxxxxxx","tokenTtl":18000,"globalAdmin":false,"username":"xxx"}
但是在 9848 端口上
SubscribeServiceRequest:{xxxxxxxxxxxxxxxxxxx
返回的是
SubscribeServiceResponse.V.T{"resultCode":500,"errorCode":403,"message":"authorization failed!","success":false}

**Comment by isgbuddy** [comment]
如果是 nacos 用户，那么 SubscribeServiceResponse 这里返回的是 
SubscribeServiceResponse.V.T{"resultCode":200,"

**Comment by isgbuddy** [comment]
这个是不是 grpc 认证过程有问题？怎么解决？

**Comment by YunWZ** [comment]
> 这个是不是 grpc 认证过程有问题？怎么解决？

你可以尝试如下步骤：

1. 用创建的新用户登陆控制台，访问相应的命名空间， 确认是否用访问权限；
2. 提供一个可以复现此问题的demo项目；

**Comment by KomachiSion** [comment]
是不是只创建了角色，权限，没做关联。

**Comment by Louis2014** [comment]
I also had the same problem，nacos client version is 2.0.4, nacos server version is 2.1.2

**Comment by KomachiSion** [comment]
> 我在 nacos 服务器上抓了包，用户登录没问题， 客户端，在 8848 端口访问 POST /nacos/v1/auth/users/login?username= 成功返回了 {"accessToken":"xxxxxxxxxxxxxxxxxxx","tokenTtl":18000,"globalAdmin":false,"username":"xxx"} 但是在 9848 端口上 SubscribeServiceRequest:{xxxxxxxxxxxxxxxxxxx 返回的是 SubscribeServiceResponse.V.T{"resultCode":500,"errorCode":403,"message":"authorization failed!","success":false}

login成功不代表有权限，只是用户密码正确， 报错是无权限， 说明当前的权限没有赋予角色和用户。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
