### ISSUE TITLE
gRPC message exceeds maximum size

### ISSUE THREAD

**Issue by xy37** [alibaba/nacos#9994]
gRPC message exceeds maximum size #7429

**Comment by xy37** [comment]
nacos是否可以支持自动将快照文件分批传输呢？而不是通过修改-Dnacos.remote.client.grpc.maxinbound.message.size=
-Dnacos.remote.server.grpc.maxinbound.message.size=。在扩容场景，用户无法预料自己的快照数据有多大，通过设置size感觉不太友好

**Comment by KomachiSion** [comment]
快照模式主要是兼容和沿用1.x的模式， 如果不需要支持1.x客户端，快照这步骤可以直接省略掉， 通过verify方式逐个数据同步。

计划未来快照模式是要移除的。当前配置maxinbound即可。
